### ISSUE TITLE
Java API

### ISSUE THREAD

**Issue by Sponges** [Microsoft/BotBuilder#1]
<3

**Comment by itsGhost** [comment]
no you gay twat... just kidding dont shoot my dog.

PS: Hey, Microsoft staff. Still have that dart board with my face on? I guess we will see at your next event.

**Comment by j0ach1mmall3** [comment]
d@nk :+1:

**Comment by hlaaftana** [comment]
yuck horrible java is gay delet

**Comment by Sponges** [comment]
HLAFF
STOP
HACING!

**Comment by hlaaftana** [comment]
@everyone

**Comment by Luigifan** [comment]
hi....can u make visual basic api too? thx

**Comment by itsGhost** [comment]
> hi....can u make visual basic api too? thx. i want to maek bot but dont know c

cant tell if trolling

**Comment by Luigifan** [comment]
no i'm srs...i want discord bot using this api in vb. can u tell me how?

**Comment by hlaaftana** [comment]
That has made my blood boil, i see another world war taking place, will be the so called "refugees" and muslims against everyone else what the fuck have the goverments if Europe and Great Britain done, fucked their countrys that what, i say kick them out send em back if they dont want to fucking pit them of a boat send em out to the middle of the Atlantic ocen and leave the fuckers to die in hell. People may say these thoughts are racist or nazi like, well if they are I'll happily be called those names, the native people to the countrys will be minoritys by 2020 like in germany Britain france and so on, they need to start going around with massive trucks putting the cunts in the back and dumping them in a dessert with nothing but the clothes on their back. When i go back tp England in june if its is still like this or worse i will not be going back until changes have been made. People say muslims are peaceful, well watch and listen to the video 96% if the murders rapes and violent crimes in the europens and british countrys and being commited by them! It has raised at a 600% in the past 2years. Why are we letting this happen! They want shira law inforced. The law is from the fucking 14th century cutting finger and hands off petty theives, letting aged men have sex with children. Have multiple wives at once. This is a atrocity these people need to be get rid of once and for all! Send the fuckers back who ever thinks they belong in those country may as well just move to syria pakistan and so on. Go join the fuckers if you love their way so much go get beaten and raped murdered and so on. As you can tell i have a passion to get rid of them people should not be minoritys in their own countrys. Rant over fuuck if you read that all well done if you thing im a rasist or nazi, open your eyes and see the bigger picture.

**Comment by Raidein** [comment]
@hlaaftana fucking gay

**Comment by j0ach1mmall3** [comment]
That has made my blood boil, i see another world war taking place, will be the so called "refugees" and muslims against everyone else what the fuck have the goverments if Europe and Great Britain done, fucked their countrys that what, i say kick them out send em back if they dont want to fucking pit them of a boat send em out to the middle of the Atlantic ocen and leave the fuckers to die in hell. People may say these thoughts are racist or nazi like, well if they are I'll happily be called those names, the native people to the countrys will be minoritys by 2020 like in germany Britain france and so on, they need to start going around with massive trucks putting the cunts in the back and dumping them in a dessert with nothing but the clothes on their back. When i go back tp England in june if its is still like this or worse i will not be going back until changes have been made. People say muslims are peaceful, well watch and listen to the video 96% if the murders rapes and violent crimes in the europens and british countrys and being commited by them! It has raised at a 600% in the past 2years. Why are we letting this happen! They want shira law inforced. The law is from the fucking 14th century cutting finger and hands off petty theives, letting aged men have sex with children. Have multiple wives at once. This is a atrocity these people need to be get rid of once and for all! Send the fuckers back who ever thinks they belong in those country may as well just move to syria pakistan and so on. Go join the fuckers if you love their way so much go get beaten and raped murdered and so on. As you can tell i have a passion to get rid of them people should not be minoritys in their own countrys. Rant over fuuck if you read that all well done if you thing im a rasist or nazi, open your eyes and see the bigger picture.

**Comment by j0ach1mmall3** [comment]
#1 #2 #3 #4 #5 #6

**Comment by itsGhost** [comment]
> #1 #2 #3 #4 #5 #6

wat

**Comment by Stevenic** [comment]
We're totally open to creating language bindings for other languages. For now we'll lock this issue and re-visit the language bindings we support at some point in the future. Thanks everyone!
