### ISSUE TITLE
Alarm Bot Documentation Missing Details

### ISSUE THREAD

**Issue by bryantlikes** [Microsoft/BotBuilder#10]
http://docs.botframework.com/sdkreference/csharp/dialogs.html

The Alarm Bot section is missing some details like adding the Chronic Nuget package and it doesn't explain what to do in the MessageController or how to interact with the bot.

**Comment by Stevenic** [comment]
Thanks for the feedback. We'll have someone look into it.

**Comment by msft-shahins** [comment]
@bryantlikes if you open the [main solution](https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Microsoft.Bot.Builder.sln), it has the [SimpleAlarmBot ](https://github.com/Microsoft/BotBuilder/tree/master/CSharp/Samples/SimpleAlarmBot) project that has all the nuget dependencies required to build and run the alarm bot. You can start that project and use [Bot Framework Emulator](http://docs.botframework.com/connector/tools/bot-framework-emulator/#navtitle) to interact with it locally.

**Comment by Stevenic** [comment]
Please re-open if this is still causing you grief.
