### ISSUE TITLE
support for Messenger Platform

### ISSUE THREAD

**Issue by luisrudge** [Microsoft/BotBuilder#100]
Not sure what's the best place to ask, but it would be really awesome to support this new platform! https://messengerplatform.fb.com/

**Comment by Stevenic** [comment]
We saw the keynote. Stay tuned :)

**Comment by luisrudge** [comment]
❤️






On Wed, Apr 13, 2016 at 12:43 AM -0700, "Steven Ickman" <notifications@github.com> wrote:





We saw the keynote. Stay tuned :)

---

**Comment by Stevenic** [comment]
Please vote on this over on UserVoice:

https://feedback.botframework.com/forums/354219-bot-connector/suggestions/13398783-will-support-be-added-for-newly-released-fb-messen
