### ISSUE TITLE
NoResumeHandlerException: IDialog method execution finished with no resume handler specified through IDialogStack.

### ISSUE THREAD

**Issue by GerryWilko** [Microsoft/BotBuilder#1002]
I'm trying to use the LuisDialog and I get the exception above. I'm sure I'm missing something simple but I am receiving the following exception even when using just the default None handler.

Called here:
        `await Microsoft.Bot.Builder.Dialogs.Conversation.SendAsync(activity, () => new Stream_StarterDialog(_eventRepository, _userRepository));`

LuisDialog:

        [LuisIntent("")]
        public async Task None(IDialogContext context, LuisResult result)
        {
            await context.PostAsync("Sorry I did not understand. Ask me questions like \"What events are on in Seattle?\" or manage your current events with \"Show me the events I have supported as a Viewer.\".");
            context.Wait(MessageReceived);
        }

**Comment by willportnoy** [comment]
The current version of your code looks correct:
https://docs.botframework.com/en-us/technical-faq/#ensure-all-dialog-methods-end-with-a-plan-to-handle-the-next-message

However, you might consider clearing your conversation state in case it corresponded to an older version of the code:
https://docs.botframework.com/en-us/technical-faq/#my-bot-is-stuck--how-can-i-reset-the-conversation

**Comment by GerryWilko** [comment]
Yep that fixed it thanks again Will!
