### ISSUE TITLE
[Node] Slack or Bot Connector not working for individual users

### ISSUE THREAD

**Issue by AidanBr** [Microsoft/BotBuilder#1003]
Midway through conversations with the bot in slack the bot has stopped responding to the user. There is no traffic to our node server from these conversations.
Additional user's conversations have also stopped working with no pattern between them.
Other users on slack and other clients can still access and chat with the bot. 

Is there a limit on messages in slack or bot connector? 

LUIS is also being used but pretty confident were not hitting their limit either as other users can get responses.

Thanks.

UPDATE:

The bot has started working again now. Would be great if you could shed some light on why this would happen.

**Comment by Andrea-Orimoto** [comment]
Hi AidanBr, what's the bot handle? https://dev.botframework.com/bots?id=<bothandle>

**Comment by AidanBr** [comment]
Hey,

The bot handle is SelfServiceBot

Thanks.

**Comment by Andrea-Orimoto** [comment]
@AidanBr sorry, did not have time to investigate yet. I'm going to close this issue since it's not affecting you anymore, but I've opened a ticket to do some investigation. Will post here some more info if we get to it. Thanks!
