### ISSUE TITLE
Unable to deserialize the response.

### ISSUE THREAD

**Issue by aqalalwa** [Microsoft/BotBuilder#1004]
Today, I moved to learn about Bots Framework provided by Microsoft, so I followed the documentation for getting started with it. I cloned the CSharp version of the BotBuilder and created a new project using its template. When I tried to test it on the Bots Emulator it crashed when I sent a message.

![image](https://cloud.githubusercontent.com/assets/11869771/17697222/2ae7379a-63bc-11e6-897f-6409ab860a6a.png)

**Comment by willportnoy** [comment]
Can you share the call stack?

It seems possible your asp.net server is not sending back a json formatted response (it may be sending html instead, for example).

**Comment by aqalalwa** [comment]
@willportnoy 
public async Task<HttpResponseMessage> Post([FromBody]Activity activity)
        {
            if (activity.Type == ActivityTypes.Message)
            {
                string outputStr = "I'm not here!";
                LUISResult luis = await GetEntityFromLUIS(activity.Text);
                if (luis.intents.Count() > 0)
                {
                    switch (luis.intents[0].intent)
                    {
                        case "StockPrice":
                            string entityType = luis.entities[0].type;
                            string stockSymbol = luis.entities[0].entity;
                            if (entityType == "StockSymbol")
                                outputStr = await GetStock(stockSymbol);
                            break;
                        case "Weather":
                            string location = "";
                            string var = null;
                            foreach(Entity entity in luis.entities)
                            {
                                if (entity.type == "WeatherVar")
                                    var = entity.entity;
                                else if (entity.type == "GeoLocation")
                                    location = entity.entity;
                            }
                            outputStr = await GetWeatherDesc("6935fb2b1e1b4c5da82114118161708",location,var);
                            break;
                        default :
                            outputStr = "Sorry, I didn't catch that!";
                            break;
                    }
                }
                ConnectorClient connector = new ConnectorClient(new Uri(activity.ServiceUrl));
                Activity reply = activity.CreateReply(outputStr);
                await connector.Conversations.ReplyToActivityAsync(reply);
            }
            else
            {
                HandleSystemMessage(activity);
            }
            var response = Request.CreateResponse(HttpStatusCode.OK);
            return response;
        }

**Comment by willportnoy** [comment]
@aqalalwa do you have the call stack where the exception is thrown?

**Comment by willportnoy** [comment]
I'm going to close this issue, but feel free to open a new issue with more information.
