### ISSUE TITLE
Slack: Meta-Tags in Button-Action cause Error 500

### ISSUE THREAD

**Issue by NanashiGIT** [Microsoft/BotBuilder#1005]
Hello!
Im trying to use Meta-Tags in my Button Actions with PostBack, so i can determine some data better when the button is clicked.

It is working fine in Skype, but when I click that button in Slack, i get an Internal Server Error (From the Connector i assume, because I get an HTML-Styled Exception in the Log-Streaming of Azure).

My code for the button (Which is the same for skype):
```cs
CardAction plButton = new CardAction()
            {
                Value = $"ClickMe <meta actionType='ButtonClick'    Action='A' />",
                Type = ActionTypes.PostBack,
                Title = "ActionA"
            };
```
Does someone have an idea?

Greetings

**Comment by craigjensen** [comment]
Please add your botId and i'll investigate

**Comment by NanashiGIT** [comment]
If you mean the microsoft app id:
4998a523-b204-4f22-b137-37ba8e808e3a

**Comment by craigjensen** [comment]
I'm seeing several http 500 errors coming from your bot's endpoint.  Can you add the CorrelationId from one of the errors you are referring to above?

**Comment by NanashiGIT** [comment]
Im not sure what you mean by correlationId.

All i have is the Log-Stream in Azure. I just triggered an example exception with a button click. The steam shows me the following:

`
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"> 
<head> 
<title>IIS Detailed Error - 500.0 - Internal Server Error</title> 
<style type="text/css"> 
 
</style> 
 
</head> 
<body> 
<div id="content"> 
<div class="content-container"> 
<h3>HTTP Error 500.0 - Internal Server Error</h3> 
<h4>The page cannot be displayed because an internal server error has occurred.</h4> 
</div> 
<div class="content-container"> 
<fieldset><h4>Most likely causes:</h4> 
<ul> 	<li>IIS received the request; however, an internal error occurred during the processing of the request. The root cause of this error depends on which module handles the request and what was happening in the worker process when this error occurred.</li> 	<li>IIS was not able to access the web.config file for the Web site or application. This can occur if the NTFS permissions are set incorrectly.</li> 	<li>IIS was not able to process configuration for the Web site or application.</li> 	<li>The authenticated user does not have permission to use this DLL.</li> 	<li>The request is mapped to a managed handler but the .NET Extensibility Feature is not installed.</li> </ul> 
</fieldset> 
</div> 
<div class="content-container"> 
<fieldset><h4>Things you can try:</h4> 
<ul> 	<li>Ensure that the NTFS permissions for the web.config file are correct and allow access to the Web server's machine account.</li> 	<li>Check the event logs to see if any additional information was logged.</li> 	<li>Verify the permissions for the DLL.</li> 	<li>Install the .NET Extensibility feature if the request is mapped to a managed handler.</li> 	<li>Create a tracing rule to track failed requests for this HTTP status code. For more information about creating a tracing rule for failed requests, click <a href="http://go.microsoft.com/fwlink/?LinkID=66439">here</a>. </li> </ul> 
</fieldset> 
</div> 
 
<div class="content-container"> 
<fieldset><h4>Detailed Error Information:</h4> 
<div id="details-left"> 
<table border="0" cellpadding="0" cellspacing="0"> 
<tr class="alt"><th>Module</th><td>&nbsp;&nbsp;&nbsp;ManagedPipelineHandler</td></tr> 
<tr><th>Notification</th><td>&nbsp;&nbsp;&nbsp;ExecuteRequestHandler</td></tr> 
<tr class="alt"><th>Handler</th><td>&nbsp;&nbsp;&nbsp;System.Web.Http.WebHost.HttpControllerHandler</td></tr> 
<tr><th>Error Code</th><td>&nbsp;&nbsp;&nbsp;0x00000000</td></tr> 
 
</table> 
</div> 
<div id="details-right"> 
<table border="0" cellpadding="0" cellspacing="0"> 
<tr class="alt"><th>Requested URL</th><td>&nbsp;&nbsp;&nbsp;https://Signl4-Bot:80/api/messages</td></tr> 
<tr><th>Physical Path</th><td>&nbsp;&nbsp;&nbsp;D:\home\site\wwwroot\api\messages</td></tr> 
<tr class="alt"><th>Logon Method</th><td>&nbsp;&nbsp;&nbsp;Anonymous</td></tr> 
<tr><th>Logon User</th><td>&nbsp;&nbsp;&nbsp;Anonymous</td></tr> 
 
</table> 
<div class="clear"></div> 
</div> 
</fieldset> 
</div> 
 
<div class="content-container"> 
<fieldset><h4>More Information:</h4> 
This error means that there was a problem while processing the request. The request was received by the Web server, but during processing a fatal error occurred, causing the 500 error. 
<p><a href="http://go.microsoft.com/fwlink/?LinkID=62293&amp;IIS70Error=500,0,0x00000000,9200">View more information &raquo;</a></p> 
<p>Microsoft Knowledge Base Articles:</p> 
  
 
</fieldset> 
</div> 
</div> 
</body> 
</html> 
`

Thats pretty much all i have.
 Maybe its this you meant?
 
POST /api/messages X-ARR-LOG-ID=b8885d01-a4a3-4890-98a3-c61daf2cc2e5 443 - 52.160.104.193 - ARRAffinity=608d736279cfd2ca340b73d57d6f432f9833b2412eb160fddb97812230566484;+$Port

**Comment by craigjensen** [comment]
I was able to include meta tags in card values without any issues.  Are your actions working without the meta tags?

**Comment by NanashiGIT** [comment]
Thanks for your help.

It turns out, that it was partially my fault. 
The problem is, that when pressing the button in skype, it sends:
"ClickMe <meta actionType='ButtonClick'    Action='A' />"
Just the value of the button, which is what I think is good.

But when i click the button in slack i get the following:
&lt;meta actionType='ButtonClick' Action='A' /&gt;

For some reason, it serializes it differently than in slack. Is this subject to change, because I think its a bit "meh" that they behave differently in this regards?
The error happened then, when I parsed it the wrong way.

**Comment by craigjensen** [comment]
We have a fix ready for this and it will deployed soon.

**Comment by craigjensen** [comment]
Fix was deployed today.  Please reopen if the problem still exists
