### ISSUE TITLE
[Node.js] How to send video

### ISSUE THREAD

**Issue by Avartarus-Testicus** [Microsoft/BotBuilder#1007]
Hi, 
how is it possible to send videos, indipendent of the channel (skype, telegram) with nodeJS. For images there is already a common way for implementing, but what about videos!!!:

var msg = new builder.Message(session)
            .attachments([{
                contentType: "image/jpeg",
                contentUrl: "http://www.theoldrobots.com/images62/Bender-18.JPG"
            }]);
        session.send(msg);

I tried to change "contentType" but this didn't worked. I tried also another way via Herocard-->Card Actions, but this wasn't successfull too. Has anybody a clue what to do. Have I to use a rich-card-object or can I achieve it via builder.Message. Whats the best way ??
Thanks

**Comment by reyesrico** [comment]
Hi, 
The way to send videos is using the contentType: "video/{format}". 

Here it is an example of sending video/mp4 video:

	var msg = new builder.Message(session).attachments([{
		contentType: "video/mp4",
		name: "Big Buck Bunny 240p 1mb.mp4",
		contentUrl: "http://www.sample-videos.com/video/mp4/240/big_buck_bunny_240p_1mb.mp4"
	}]);
	session.send(msg);	

The supported formats depend on the channel that you want to deploy your bot. Here it is a link with the Skype video supported formats: 
https://docs.botframework.com/en-us/skype/getting-started/#messages

**Comment by Avartarus-Testicus** [comment]
Hi, 
thanks a lot for your fast answer. The fault was on my side...anyway....your example is working fine :+1:

**Comment by palmerabollo** [comment]
@reyesrico According to the [attachments documentation](https://docs.botframework.com/en-us/csharp/builder/sdkreference/activities.html#attachmentscardsactions), an attachment can have `contentType`, `contentUrl` and `contentType` (but not `name`). In [the source code](https://github.com/Microsoft/BotBuilder/blob/master/Node/core/src/interfaces.d.ts#L71), the interface `IAttachment` also declares those fields. Why do you use `name` instead?
