### ISSUE TITLE
ask email on skype

### ISSUE THREAD

**Issue by filipeperdigaosousa** [Microsoft/BotBuilder#1009]
If I ask the user via a dialog to give me their email, it's returning it as <ahref="mailto:matt@geckolabs.co.uk">matt@geckolabs.co.uk</a>.

Do you know how can i solve this?

**Comment by nickcordrey** [comment]
Hi could you describe in a bit more detail the issue you are seeing - is the email address formatted incorrectly? It looked OK in the example above but I may be missing the issue.

**Comment by changhc** [comment]
I guess you mean that it returns something like mailto:XXX. 
But it's still a string and you can just record its substring.

**Comment by ankitbko** [comment]
I use simple regex match to get the email.
```CSharp
var match = Regex.Match(userEmail, @"[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?")
```

**Comment by KrishnanA** [comment]
Can we treat this issue as resolved?

**Comment by filipeperdigaosousa** [comment]
Yes,  trained my luis to recongize email inside tags
