### ISSUE TITLE
Issue Registering New Bot on botframework.com

### ISSUE THREAD

**Issue by oztheozoz** [Microsoft/BotBuilder#1012]
I have been able to successfully register a bot on botframework.com before.
After I enter all the information to register a bot and click submit, I am getting this error message and cannot proceed further:
"Object reference not set to an instance of an object."

Looks like a null pointer to me. Anyone from MS able to take a look at this?

**Comment by faso** [comment]
I am having the same issue right now. I hosted it on Azure and it works properly with the emulator.

**Comment by mshula** [comment]
I'm having the same issue.

**Comment by HardikShah289** [comment]
Make sure you fill the page data correctly.
enter URL  when it is require.. at least in URL format like http://google.com in terms to use, privacy statement. I got the same, but after putting data in correct format, it is resolved.,

**Comment by oztheozoz** [comment]
@HardikShah289 that worked! Thank you very much. Funny thing is before registering this recent bot, I registered multiple bots without problems but must have by chance just included http://. It's definitely still worth someone at MS looking into putting a more meaningful error message if http:// is what they are expecting for those fields.

**Comment by HardikShah289** [comment]
I agree!

**Comment by mshula** [comment]
Thank you! yes, that worked! :) My issue was that I didn't have a URL in in terms of use.

**Comment by oztheozoz** [comment]
@Andrea-Orimoto , I know we were able to get things working but I was just wondering if there was a fix with better messaging if people leave out the http:// (see my last comment for more details)?
