### ISSUE TITLE
FormFlow and HeroCard not work properly

### ISSUE THREAD

**Issue by rcarmonad** [Microsoft/BotBuilder#1014]
Hi, i'm building a chatbot app using the c# api.
I have a form flow app that shows the result using a carousel of herocards, just like this [example](https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Samples/EchoBot/EchoAttachmentDialog.cs). 
When i try using the Channel Emulator, it works fine

<img width="1100" alt="chat bot emulator example" src="https://cloud.githubusercontent.com/assets/770705/17716975/9c0f5874-63e1-11e6-8660-8e23d674d7a2.png">

But, this isn't showing anything, nor facebook, telegram or embeded app
![facebook](https://cloud.githubusercontent.com/assets/770705/17717003/c631e536-63e1-11e6-8b84-34596f40d005.png)
![Iframe](https://cloud.githubusercontent.com/assets/770705/17717035/f4a5e944-63e1-11e6-871e-e95af9f5f561.png)

Can you tell me if anything is wrong with the integration? or the example isn't right?

**Comment by rcarmonad** [comment]
So, now it's working.
The only thing i changed was that i put "Value" to the CardButton:

```
var actions = new List<CardAction>();

actions.Add(new CardAction
{
    Title = "¡Lo quiero!",
    Value = "http://www.google.cl",
    Type = ActionTypes.ImBack
});
```

That's all folks!
Greets

**Comment by willportnoy** [comment]
Thank you for the follow-up comment explaining how to fix the issue!
