### ISSUE TITLE
Hyperlink issue in webchat

### ISSUE THREAD

**Issue by Sams4u** [Microsoft/BotBuilder#1015]
Hi, Am trying to create a hyperlink which should directly open an IM window upon clicking. 
Hyperlink is created using following syntax context.PostAsync($"Please click on [Title](sip:user@domain.com)");
It works with emulator but not with webchat. When i checked the html <a> tag is getting generated but href is not.

**Comment by willportnoy** [comment]
I'm surprised a hyperlink is generated at all - it looks like you're posting plain text to the user with your PostAsync call.  Did GitHub formatting strip out some content?

**Comment by Sams4u** [comment]
My bad. I think some formatting issue. 
Syntax:- await context.PostAsync($"Please click on [Title]({user@domain.com})");

**Comment by Sams4u** [comment]
Sorry github doesn't allow me to paste syntax as it is. I have followed normal syntax to create  a hyperlink nothing special. For a hyperlink to invoke IM, href should be somewhat like sip:user@domain.com. same if i use in BOT, webchat renders is as anchor tag with no href. But the same work with emulator.

**Comment by willportnoy** [comment]
The chat control uses markdown:

https://docs.botframework.com/en-us/support/embed-chat-control2/

**Comment by willportnoy** [comment]
I'm going to close this issue, but feel free to open a new issue with further questions.
