### ISSUE TITLE
Add bot to skype link format (add bot directory to the skype client)

### ISSUE THREAD

**Issue by dmdnkv** [Microsoft/BotBuilder#1016]
Is it possible to add skype bot to skype via simple link directly passing it to the skype client without going through `join.skype.com` and its authentication mechanism.
For instance:

```
<a href="skype:bot-guid-here?add">Run skype and add bot or chat with bot</a>
```

**Comment by KrishnanA** [comment]
Sorry, there is no other way besides the join link to add the bot to your contact list.

**Comment by dmdnkv** [comment]
Are there any plans to add such feature?

For instance, absence of this feature might lead to the point when users that forgot their password but auto-authorized in skype clients prefer to avoid bots usage because it requires additional steps.

**Comment by KrishnanA** [comment]
We currently don't have this planned. But we will look into this. Thanks for the feedback.

**Comment by glebkudr** [comment]
It will be a great feature!

**Comment by sergey-safonov** [comment]
Actually, it would be really great to have this feature, please add it to your plans.
