### ISSUE TITLE
Skype call drops after 13 sound play prompts

### ISSUE THREAD

**Issue by mghimp** [Microsoft/BotBuilder#1018]
I have a Skype calling bot that sends back to skype audio files as play prompt. The call drops each time after 13 audio files have been played.

**Comment by KrishnanA** [comment]
Could you share your bot id please? We have a limit on the number of serial workflows that can be given by a bot and the behavior you are explaining might be a result of that.

**Comment by mghimp** [comment]
Microsoft App ID: c277b29c-65f2-4883-b7bb-0664ac959670

**Comment by KrishnanA** [comment]
Thanks. I can confirm that the behavior that you are seeing is a result of the limit that we have on the number of back and forth interactions. We will look into increasing the limit.

**Comment by mghimp** [comment]
Please look into removing the limit at all. It might be extremely difficult  to run a conversational bot with limit when the call drops when limit is reached. This would be bad from both the conversation-with-bot-experience point of view and from skype-call-experience point of view. Thanks.

**Comment by KrishnanA** [comment]
Thanks for your feedback. We will definitely look into this holistically.
