### ISSUE TITLE
Suggestion: LuisResult.TryFindEntity Regex Support

### ISSUE THREAD

**Issue by rodzillarr** [Microsoft/BotBuilder#102]
Currently supports searching by a string based type name which is great.  But, it would be easier if I want to search for any type that falls within the `builtin.geography.*` types (us_state, country, et al) to just use a regex phrase to include any entity (or a collection thereof) which satisfies the expression. 

Thanks for all the work on this.  It's a fun ride digging into everything.

-r

**Comment by Stevenic** [comment]
Is this for C# or Node?

**Comment by rodzillarr** [comment]
C#

**Comment by msft-shahins** [comment]
@rodzillarr since Entities in the LuisResult is an IList, you can easily do any kind of filtering by writing the appropriate linq query. Thanks for your suggestion about adding another extension method for LuisResult.
