### ISSUE TITLE
DirectLine messages format

### ISSUE THREAD

**Issue by filipeperdigaosousa** [Microsoft/BotBuilder#1020]
I'm using DirectLine API an when I receive a confirm prompt i receive a message like this: "Is it correct? (1. yes or 2. no)".

Is it possible to receive the message in another format in order to understand that this message is a confirmation?

It can be very usefull in confirmations, attachements and this kind of messages in order to help use custom controls like buttons, cards, ...

**Comment by Samurais** [comment]
Indeed, I have come to the same problem. It should be more flexible here.

**Comment by filipeperdigaosousa** [comment]
Currently I am parsing messages with regular expressions in order to
extract information about those kind of actions and build my own  controls

Em 18/08/2016 10:20 da manhã, "Hain" <notifications@github.com> escreveu:

**Comment by dandriscoll** [comment]
Hi @filipeperdigaosousa, the Direct Line 1.0 protocol isn't going to change (we can't change it without breaking existing clients) but the next version will include messages with full card support and more properties.

In the meantime, you can use the ChannelData field as a tunnel between your bot and the client. This field can contain any data you'd like.

**Comment by dandriscoll** [comment]
Closing as the behavior for Direct Line 1.0 is locked and this will be fixed in the next revision.
