### ISSUE TITLE
Button not displayed on iFrame

### ISSUE THREAD

**Issue by HardikShah289** [Microsoft/BotBuilder#1021]
In my code, i have used
` CardAction plButton = new CardAction()
                {
                    Value = "https://en.wikipedia.org/wiki/Pig_Latin",
                    Type = "openUrl",
                   Title = "Submit"
                   
                };
                CardAction plButton1 = new CardAction()
                {
                    Value = "https://en.wikipedia.org/wiki/Pig_Latin",
                    Type = "openUrl",
                    Title = "Submit"

                };

but, on web page it is displayed as hyperlink, while on emulator it is displayed like button. what i did wrong? attached the snapshot.
![webchat_button](https://cloud.githubusercontent.com/assets/20954239/17742864/564f6636-6467-11e6-9903-3c6666930c24.PNG)
![emulator_chat_button](https://cloud.githubusercontent.com/assets/20954239/17742865/5650a6b8-6467-11e6-836c-2a50d050ac10.PNG)
![json response](https://cloud.githubusercontent.com/assets/20954239/17742866/56522966-6467-11e6-8533-1d52fb78b293.PNG)

`

**Comment by danmarshall** [comment]
Hi @HardikShah289 the webchat currently does not display cards - this is a known issue that we are working on. We will be posting news on our blog when we have a webchat update, thanks.
