### ISSUE TITLE
Node.js ConsoleConnector fails to reset Session.sendingBatch

### ISSUE THREAD

**Issue by Thegaram** [Microsoft/BotBuilder#1023]
The code below sends only one message instead of two.

```js
var connector = new builder.ConsoleConnector().listen();
var bot = new builder.UniversalBot(connector, {
    autoBatchDelay: 0
});

bot.dialog('/', function (session) {
    session.send("First");

    setTimeout(() => { 
        session.send("Second");
    }, 0);
});
```

When we call `Session.send`, the code flow will eventually reach `ConsoleConnector.send`. As this function does not call the provided callback (unlike `ChatConnector.send`), `session.sendingBatch` will not be reset to `false`, and subsequent calls to `Session.send` will be ignored (due to the check in `Session.startBatch`).

Note: without the timeout this issue will not arise, as `Session` does automatic batching inside the time interval defined by `autoBatchDelay` (for which the default is 250ms).

**Comment by Stevenic** [comment]
Looks like you fixed the issue... thanks. Will be in next release.

**Comment by palmerabollo** [comment]
We're also facing this issue. Any plans to release a new nodejs sdk version?

**Comment by Stevenic** [comment]
Should be fixed.
