### ISSUE TITLE
Skype responses always have extra line

### ISSUE THREAD

**Issue by MironV** [Microsoft/BotBuilder#1025]
Whenever I look at my bot on Skype, his responses include a blank line. This doesn't seem to happen when I chat in Skype in general and it happens on all platforms. I'm not sending any newlines to my knowledge.

**Comment by wiltodelta** [comment]
I have repeated only in mac desktop client, web client (https://web.skype.com) works fine!

**Comment by gplumb** [comment]
@MironV Is this on the Windows 10 Skype Preview client by chance?  This client does appear to have some aggressive bottom padding in its chat bubbles...

**Comment by HKOLWD** [comment]
Noticing the same in multiple skype clients. Always seems to append an empty line

**Comment by tomlm** [comment]
I believe this has been fixed.
