### ISSUE TITLE
Registration of bot in the portal fails

### ISSUE THREAD

**Issue by reghrafa** [Microsoft/BotBuilder#1027]
When trying to register a new Bot under https://dev.botframework.com/bots/new and providing all required information the website responds with "Object reference not set to an instance of an object.".
<img width="410" alt="screenshot 2016-08-17 23 57 46" src="https://cloud.githubusercontent.com/assets/6999002/17761658/ecb79020-64d6-11e6-96a0-c868a4bcb77b.png">

**Comment by Mashakal** [comment]
Make sure all your urls have https://

**Comment by reghrafa** [comment]
great! thanks, that was it :)

**Comment by maestrow** [comment]
Issue shold be reopened because message is meaningless for the user.
