### ISSUE TITLE
Ping to user.. similar to notification Node.js

### ISSUE THREAD

**Issue by VishalWaman** [Microsoft/BotBuilder#1028]
I need to ping user with a message like 'Gentle reminder for outstanding payments'...

How to we initiate conversation to a specific user from bot framework node.js

**Comment by changhc** [comment]
Hi @VishalWaman. After a user talked to your bot for the first time, you can save his or her connection data recorded in `session.message.address` in a database or some external storage. When you are sending that user a proactive message, you can create a message variable like this:
```JavaScript
var message = {
    address: addr,  //session.message.address you saved previously
    user: addr.user,
    text: text,    //message you want to send
    agent: 'botbuilder',    //must be this
    type: 'message'    //you're sending a message
};
```
and then you can use this method `bot.send(message)` .

As an alternative, you can use `bot.beginDialog(addr, dialog)`, where dialog is a new dialog you'd like to start. In that dialog, you can simply use `session.send(text)` as usual.

See more [here](https://docs.botframework.com/en-us/node/builder/chat-reference/classes/_botbuilder_d_.universalbot.html) or [here](https://docs.botframework.com/en-us/node/builder/chat-reference/interfaces/_botbuilder_d_.imessage.html).

**Comment by VishalWaman** [comment]
I will try it.. 

Thanks

**Comment by ChandrikaC** [comment]
How this will work if my Twilio SMS is configured?

**Comment by changhc** [comment]
I guess they're the same. ChannelId is included in addr, so messages should be delivered to different channels correctly. Doesn't it work after you've done your bot?
