### ISSUE TITLE
Disable exception sent to client

### ISSUE THREAD

**Issue by kenyeung128** [Microsoft/BotBuilder#1029]
Hi, How could I stop the exception being sent and displayed on the client like facebook messenger? Thanks.

**Comment by NanashiGIT** [comment]
Do you mean that standard message like "My bot code is having an issue"?

If so, i'd want to disable it too.

**Comment by kenyeung128** [comment]
no, it's on the client side, like facebook messenger, the exception string got throw to client, which i want to stop it. do you know how?

**Comment by willportnoy** [comment]
I think these are the relevant commits, right?

https://github.com/Microsoft/BotBuilder/commit/bf0d5172bb715b0447aeb580da33b997972a87ff
https://github.com/Microsoft/BotBuilder/commit/278ba9b569bdddc198149528ca7fd6ef3450e003

You could avoid sending the message to the user by just avoiding unhandled exceptions.

As a secondary option, you can remove that IPostToBot middleware from the container.

**Comment by kenyeung128** [comment]
Thanks @willportnoy for the secondary options, how could I remove that IPostToBot container? How can this be done with AutoFac? Thank you

**Comment by willportnoy** [comment]
This is how we normally register the chain of IPostToBot middleware:

https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Dialogs/DialogModule.cs#L171

This is our default container:

https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Dialogs/Conversation.cs#L49

You can update the container using the ContainerBuilder like this:

https://github.com/Microsoft/BotBuilder/blob/44d9667878759f9676c615365a818525ffe00ebd/CSharp/Tests/Microsoft.Bot.Builder.Tests/ExceptionTests.cs#L65

I realize it's cumbersome to duplicate the chain registrations without the PostUnhandledExceptionToUserTask middleware.  If anybody is a DI/Autofac expert, I'd love to hear suggestions for better patterns.

**Comment by kenyeung128** [comment]
Thanks @willportnoy , it works for me now. I just re-register without PostUnhandledExceptionToUserTask

**Comment by willportnoy** [comment]
@kenyeung128 I'm glad it works for you - I'm going to close this issue, but feel free to open a new issue for further discussions.

**Comment by rposbo** [comment]
@kenyeung128 would you be able to explain how you re-registered `PostUnhandledExceptionToUserTask`? I'm having great difficulty doing this in my project.. :disappointed:

**Comment by willportnoy** [comment]
@rposbo https://github.com/Microsoft/BotBuilder/issues/1136#issuecomment-244414222 has an alternate solution you might find easier to implement.

**Comment by kenyeung128** [comment]
@rposbo, you can do this to re-register (basically excluding PostUnhandledExceptionToUserTask)
            var builder = new ContainerBuilder();

            builder.Register(c =>
                {
                    var cc = c.Resolve<IComponentContext>();

                    Func<IPostToBot> makeInner = () =>
                    {
                        var task = cc.Resolve<DialogTask>();
                        IDialogStack stack = task;
                        IPostToBot post = task;
                        post = new ReactiveDialogTask(post, stack, cc.Resolve<IStore<IFiberLoop<DialogTask>>>(), cc.Resolve<Func<IDialog<object>>>());
                        post = new ExceptionTranslationDialogTask(post);
                        post = new LocalizedDialogTask(post);
                        post = new ScoringDialogTask<double>(post, stack, cc.Resolve<IComparer<double>>(), cc.Resolve<ITraits<double>>(), cc.Resolve<IScorable<double>[]>());
                        return post;
                    };

                    IPostToBot outer = new PersistentDialogTask(makeInner, cc.Resolve<IMessageActivity>(), cc.Resolve<IConnectorClient>(), cc.Resolve<IBotToUser>(), cc.Resolve<IBotData>());
                    outer = new SerializingDialogTask(outer, cc.Resolve<ResumptionCookie>(), c.Resolve<IScope<ResumptionCookie>>());

                    return outer;
                })
                .As<IPostToBot>()
                .InstancePerLifetimeScope();

**Comment by b4usat** [comment]
@kenyeung128 I am actually trying overriding the `PostUnhandledExceptionToUserTask`. But end up in error saying Autofac Registration issue. I am actually referring the this [post](http://robinosborne.co.uk/2016/11/02/botframework-exception-wrapping-and-custom-error-message/#comment-58544)
