### ISSUE TITLE
Doesn't seem to be a way to clear the iBotDataBags

### ISSUE THREAD

**Issue by rodzillarr** [Microsoft/BotBuilder#103]
I can overwrite key values but can't get rid of the keys.  Haven't found any methods on any of the other objects to reset state.

Thanks!

Roland

**Comment by tomlm** [comment]
You don't say which platform library you are using, but you can clear out any botdata by calling the connector.Bots.SetBotData() with empty data property.

**Comment by rodzillarr** [comment]
Thanks Tom.  I'm on C# working through the chat emulator.  Having trouble finding access to the current connector instance.

**Comment by tomlm** [comment]
You can just new it up
   var connector = (message.From.ChannelId == "emulator") ?  new ConnectorClient(new Uri("http://localhost:9000/api/messages"), new ConnectorCredentials());: new ConnectorClient();
