### ISSUE TITLE
GroupMe V3 Bot Not Responding Consistently

### ISSUE THREAD

**Issue by XelaMon** [Microsoft/BotBuilder#1030]
I have made a bot for GroupMe using the v3 Bot Framework. I have added it to a group using the provided test link. However, the bot doesn't seem to be receiving messages from the Bot Connector Service consistently. I will send one message to which it responds, and then another message, to which the bot never responds. What could be happening here?

Additionally, adding a bot to GroupMe doesn't seem to ever add it to the members of a group.

**Comment by egoward** [comment]
Hi XelaMon, I can't reproduce any inconsistencies in normal operation here.  Does the bot function consistently on other frameworks?  Maybe you're doing automated testing and hitting some kind of rate limit, or maybe there is an issue with a certain type of content not being supported and silently disappearing.  We can dig deeper if you can provide some more details repro steps.

In GroupMe, a bot is always associated with a single user and can only function in groups and doesn't appear in the members list.  We are looking at changing this in the future.

**Comment by zkahmad1** [comment]
Hi XelaMon and egoward, i'm having the same issue. The bot responds consistently to some users, but to others it is only responding to select messages.

My messaging endpoint is https://ffbot.azurewebsites.net/api/messages

**Comment by reyesrico** [comment]
XelaMon, zkahmad1: some questions that could help to understand more the issue:
1. Have you tried to use the bot in another channel? 
2. Are you making sure that your bot is joined in a group?
3. Can you call your bot inside the group with @your-bot-name ?
4. Have you identified which pieces of your code are not working?

**Comment by reyesrico** [comment]
It seems that you are not having this issue. If you still have more comments, please reopen the issue. Thank you.
