### ISSUE TITLE
Facebook Oauth when published is not working in skype.

### ISSUE THREAD

**Issue by sruthi-chelukala** [Microsoft/BotBuilder#1032]
I have integrated Facebook Oauth in my bot implementation.It is working fine when tested locally in emulator but when published ,it is not redirecting to the facebook page.Instead it is giving us a bad request in browser.The atachement is the error that we are getting when we click the url that redirects to facebooklogin page.

Please do help to resolve this issue.Thanks in advance.

![facbook loginerror](https://cloud.githubusercontent.com/assets/20094783/17763450/74956c42-6536-11e6-94e3-90c6cb1ddbde.png)

**Comment by JPThorne** [comment]
Hi there. I think we are seeing a similar issue, but with Oauth and facebook messenger. We are currently getting this error:

`Facebook graph API call failed with: BadRequest {"error":{"message":"(#100) The parameter [text] is required","type":"OAuthException","code":100,"fbtrace_id":"EKfT60urKRO"}}`

on our Facebook messenger channel in the bot framework site. We have 3 other bots running, all with the same setup, all working. I've re-created the bot, the facebook page and the app, still no luck. 

Is this a known issue with facebook or the bot connector?

Any feedback would be much appreciated.

**Comment by Kris-Nimmagadda** [comment]
Facebook Sample Auth doe not work on Skype but works fine on Emulator. The moment the WebHook goes on to Azure, it stops working. Has anybody got it working ?

**Comment by msft-shahins** [comment]
this https://github.com/Microsoft/BotBuilder/commit/4de17cc4fddba29454c07d65d2a0a42f249b2182 should solve this issue.
