### ISSUE TITLE
Skype bot doesn't work after migration to v3

### ISSUE THREAD

**Issue by wiltodelta** [Microsoft/BotBuilder#1034]
I understand that writing here is not the right place.

I have a test bot (contento-staging) that is used for development. After migrating to v3 has stopped working with Skype, just not getting the message to the bot.

<a href="https://join.skype.com/bot/6adc20e8-f5fd-40a5-9c5d-e2e688e8bb1e"><img src="https://dev.botframework.com/Client/Images/Add-To-Skype-Buttons.png"></a>

<img width="711" alt="screen shot 2016-08-18 at 09 46 40" src="https://cloud.githubusercontent.com/assets/1192743/17764578/e6267350-6528-11e6-8fb7-d6745ad71b3e.png">

<img width="709" alt="screen shot 2016-08-18 at 09 46 57" src="https://cloud.githubusercontent.com/assets/1192743/17764571/e1c5504c-6528-11e6-9213-7f1097c7a0b2.png">

**Comment by Thegaram** [comment]
I had similar problems; deleting and readding the Skype channel helped.

**Comment by wiltodelta** [comment]
@Thegaram thanks!
