### ISSUE TITLE
Base64-encoded images are not passing through

### ISSUE THREAD

**Issue by mvasilyev** [Microsoft/BotBuilder#1035]
Passing this payload
`
{
"type": "message/image",
"attachments": [
    {
        "contentUrl": "/9j/4AAQSkZJRgABAQADHwMfAAD/4QCMRXhpZgAATU0AKgAAAAgABQESAAMAAAABAAEAAAEaAAUAAAABAAAASgEbAAUAAAABAAAAUgEoAAMAAAABAAIAAIdpAAQAAAABAAAAWgAAAAAAAAMfAAAAAQAAAx8AAAABAAOgAQADAAAAAQABAACgAgAEAAAAAQAAAGSgAwAEAAAAAQAAAD8AAAAA/+0AOFBob3Rvc2hvcCAzLjAAOEJJTQQEAAAAAAAAOEJJTQQlAAAAAAAQ1B2M2Y8AsgTpgAmY7PhCfv/AABEIAD8AZAMBEgACEQEDEQH/xAAfAAABBQEBAQEBAQAAAAAAAAAAAQIDBAUGBwgJCgv/xAC1EAACAQMDAgQDBQUEBAAAAX0BAgMABBEFEiExQQYTUWEHInEUMoGRoQgjQrHBFVLR8CQzYnKCCQoWFxgZGiUmJygpKjQ1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4eLj5OXm5+jp6vHy8/T19vf4+fr/xAAfAQADAQEBAQEBAQEBAAAAAAAAAQIDBAUGBwgJCgv/xAC1EQACAQIEBAMEBwUEBAABAncAAQIDEQQFITEGEkFRB2FxEyIygQgUQpGhscEJIzNS8BVictEKFiQ04SXxFxgZGiYnKCkqNTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqCg4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2dri4+Tl5ufo6ery8/T19vf4+fr/2wBDAAQDAwQDAwQEAwQFBAQFBgoHBgYGBg0JCggKDw0QEA8NDw4RExgUERIXEg4PFRwVFxkZGxsbEBQdHx0aHxgaGxr/2wBDAQQFBQYFBgwHBwwaEQ8RGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhr/3QAEAA3/2gAMAwEAAhEDEQA/APdbfx14bvdegvNS8PQaciAAz2jkOpHRigG1h1BB55ripdP68V+t/UMJKm6cW0n2k/8AOx+axx2IU+d2b9Eeupq3w5g1WSeOKzuHvMNJkAKC2eqn5QeOcevNeKy6cx6DNc/9j0XDkdaem2ux0rNKilzezj9x0nijT/B0SXNz4Y1lCsrho7did0B6lMdweeT09TXJw+HbzUXKafZ3F1IP4YYi5GfpXrUaEMNbnryaX8zX+X5nJPESrX5aS+VyRddbSLmCbTrwO4G4GJmBQ9ME+v0qj/wiWsTfajBpt5J9kUtcYhb90B1LZ6V38uEatOSd9r2/pnP7XEJ3jF6drnex/FzU761tre+MchgOY5fL/eA4x1zzXk5ilj5UkfSsv7HwV3KMEmzVZpiLJSbdj6F0r4gQaogg1pVuEZceaqDcPqO9eBWWrXWnzpJGSWU8V59Xh+i9aej8tDrp5u9pnu7+B9K1G5M+jXaW8rcqASpz6FTXE6L8R7WSIxa3FOjEYWaNQxX345Brz6mDzGguWLbX3noQxeEqa6fkO8dTarp8aW9tcvp96g2iSJtsch7dPun9DVDxfeS61YPcWt9FqMCcBvuzLx/EO/5V6WW03GdqqV/Nfo/0OfF1U43g9P67HE+DPiTrPhrxqNR1jUp4pEVo5w8HnK/H3Si9OnVfrzXJXXmtJ82SysSG6MD9etfYV8BhcZh/Y1YK3kl+q0Pm6ePrYer7SEn8z6A8PftTXmpS3MV/o9vHM+DbJHIce4JI5+uK+cooZbeZZoGKSKchgK8utwtlFSK5KSTXm/xOuln+Mi/fldfI+8/AniTW/EDXb61Z2tkqhGjEE/nA7hnk4G09OK+ZPDnx28T6Pph068ittTiKeWGlUQtjtuZR83vmvicw4Vxk5JUIQSXVP/5I+iw2f4VK85Sv5r/I+xH1Fl1BbJbeZnMXm+YF/d4zjG719q+M/wDhafjqzk26XPdWcZAMSLbtJtU5xjIPy+g9q5VwdinDScb+bf6XNXxFh1LVSt/Xc+2NrHkMRXyBpnjn4jaraidfFcKFWKMr4DAjsQB15rlnwpiKcuWVaH/k3+R0Qz6jUV405fh/mf/Q91k0fkhgQPYV2sumnnIr76OOfc+A+reRzFr4HOrKBZXtn5zdIpMxt+HUVumxdG3Rkqw6EHBpSxVZ6wnb5G0aNL7cL/M5fU/Bes+HIxPNG0KHI8yCbH4ZBBrqLy41C4t/IuJWmQDA3ckfjV0sXiHK1VxaKqUKCX7tNM8zmW7juXntp7i3kbglZ3yeMcknJ/Gurm0pjnEZP4V6ccVC1nscfsJ3ujzi80rznLBOT1wuMn1run01o8n5kDDaSOMg9RXZDH20TMnhW3qcDZ+CtR1bd/Zto9wVOMJySfYd67yyNzpF2tzpszRSocgjv9RVVMwxHLek1fzuVTwdK9qifyOFvfAWv6NbvNf6Rc28J+UySRZUfjk4r16+8favqds9rcrbQxvgM0cJY/kTXHSzPMXJe1hG3k3/AME6Z4HBqP7ucr+aR4FeaXL97y2jU9ADn9a9qg0/w3c2gXVrcRSk5SaGF4s+x6gj+Vdyzp03Zwb9Fc5nlvOrqSPGtC8Ef25eqtze22nWauPPubiTbsX+LbwQWxnANe+3moaNeaDbaT9gsT9mXbA8VyE2nscMAST3BrmnnuKqScIwcF30f4Pb8TaOU4eEVKUlJ9tf6/I4vU/gd4RS2jbTfFd8ZZPuF7ZZk6d9igjP1r2bSPG9glpFDfMYZI0C565wO9fOvN83oTfvSf8A4C//AG09f+zMuqx2S+//AOSPkLWPBt3od/Ja3SB2Q8SIp2uOxGfWvrzUNWtPENvPZ2X2WRXGCJZVUsc9q9qhxTikkq9L53t+Fjy6uQ4dtulU+Vv1ufPPhn4gaj4b0FtL06xBnkkJafzCGPoB3/CvT/EXhyFWCwpDZny8ODhwzf7J4/Wh4/A46p7WpSu/N3/If1TF4aHJCpp6HC3njTUDKD4g8G6deXhUZlurUs7L25Hatq18K37Rk2s8Kx57z7Ofpmq9pgo6OKXo2vwuZunipa8z+5P9D//R+g5vHd7JGPKuLbIHLLAMn8ya+WYfiVFv3GRHA7g4P8q/GZ18/lq8RP72vyseRyR7H0VdeKdXmJK6hMB6JsX/ANlrwVfinb/MZJcgDoVzXM6mePerP/wKX+Ycq7Hr13rutMDt1G/B9ph/QV5bF8S7KT7zFcjPDA8VSxGcR3qT/wDApf5hZdjvZNZ8Uw5a31fVos9dt2cVxkfxBsmHyTp9GJqvr2bL7c//AAKX+Y9FsjprvxV45ki8seItV8vrtdopB/48hrn4/HVhI2XlVeOxyK3hmmaw1U5L5v8AzE3fcvDxx8QbF0Nprsbsudvn2EJI9eQBUK+MdJbIa4j69wa7YZ9m8VrOT+8VkST/ABb+IaBft1vo9+qdGFoYz+atTU17SJs/v4/1rshxRmtLVSYnGL3Niy/an8V6d+71bwrYajb42lUvXhP1/wBU2fzFYrTaFKSZJEBPU8Gtf9asa/iX4L/IpNrY6wftX6PNsXVPAmqwkDYz291a3Hyf3R5m0muJm0zw9KSyzbwe3l5/pXVDi/FR6Mbd9z07TP2jvhIoH9paZrNkxGNs+kvNgd8mIsCa8fm8KaJdk+VEWJ/2SK7FxlXfx3/r5iSS+yvuPe1+PXwavnR/7Ws4FYYIuNOmg2gf7wABr5xufh5aPzDCyj13V0U+MbaP9f8AMGk94r7j6Sh+PnwxtZQYNSs7pG+RBbWkzAHsSfTmvl5vhxCmT5Klv9pd1dseMKDVpwv/ANvNf5iV1svwPp+5+NXhRZcxa7YBWG4KsUhC57fdr5eTwFHg4S2HPdcGuuPGWFSs6X4/8Ahwu7n/0vmODSNWOd0seB/st/Vq2PtJZtu5fmOFyhr4x4upvyr7jg5ipHo2p8eZdxr9IuP/AEOr6XDsCoIZuwCAdPrUSxdV9F9y/wAhubZDDpcsWTLex8+idf1q0s820kFj82DgKKyeIqPe34f5E8zHJCEba1wXHXiM1NGLk/wZ57t2rCVZvV2/ATdyVAifKqF/+AkUhhukyqqm4EZG44rPnTEW1leLARB07oeKpGNy+19gY5yOajmTA1E1O4RQAETn+4B/WsvyCwA3EbjjAPWl7nYDbPiq5iGI3hUDHUAf1rAa3YdFfBOQRtFChT7Bc3H8aXycpcqQDxtQfpWE1pL0KsW68SAVSjR/lX4Bdm6/jrVlO0XRz0+WMiuee28vO/AduCNxP64qlCj/ACr7h3ZszeNdTbJW9uVHpkVz7xoq4ZYwmQPvsf6VajS6RX3ILyNh/GOqIWzqFx0B/wBaPr2rCzbrk+UhZRz1PtWiUP5fwQm2bX/Ca6n/ABXsmR6yn+tYn2mAklohnPcf/XquWP8AL+Qrs//Z"
    }
]
}
`

to URL `https://apis.skype.com/v3/conversations/<chat_id>/activities` results in error:
`
{
  "error": {
    "message": "contentUrl property not base64 encoded"
  }
}
`

while `contentUrl` is properly base64-encoded image. (Why even it's called contentUrl?)

**Comment by puneetsngh** [comment]
{
            "type":"message/image",  
            "attachments": [{
                "contentType":type,
                "contentUrl": 'data:'+type+';base64,'+response.encode("base64").replace("\n", "")
}]
}

If you have any other issue you can see this
https://github.com/puneetsngh/pythonSkypeBot

**Comment by mvasilyev** [comment]
@puneetsngh yes, this is solution. Must've been noted in docs, since in previous API version it worked with just base64 data.

**Comment by and7ey** [comment]
The documentation still doesn't explain it. Why the issue has been closed?

**Comment by Codelica** [comment]
And why would "content**Url**" contain the actual encoded attachment data vs "content" which appears to also be a property?  This seems odd..
