### ISSUE TITLE
Send typing activity

### ISSUE THREAD

**Issue by wiltodelta** [Microsoft/BotBuilder#1037]
How to send a typing activity to chat using IDialogContent?

**Comment by NanashiGIT** [comment]
Do you mean IDialogContext?
Then i would be something like:
msg = context.MakeMessage();
msg.Type = ActivityTypes.Typing;
context.PostAsync(msg);

Havent done it with context yet but it should work. (Afaik at the moment Skype doesnt support it)

**Comment by wiltodelta** [comment]
@NanashiGIT Thank you, it obviously was.

**Comment by wiltodelta** [comment]
@NanashiGIT Slack, Telegram and Facebook support typing.
