### ISSUE TITLE
MS Bot Emulator doesn't run

### ISSUE THREAD

**Issue by aqalalwa** [Microsoft/BotBuilder#1039]
I started using MS Bot Emulator Channel about 2 days ago, it was going well at the beginning, until I started to receive an unhandled exception when I run the emulator. I tried to uninstall and reinstall but didn't work. I did debug on the crash on VS 2015 and it displayed the following the exception details:

> **System.NullReferenceException was unhandled
> Message: An unhandled exception of type 'System.NullReferenceException' occurred in Microsoft.Bot.Connector.Emulator.Core.dll
> Additional information: Object reference not set to an instance of an object.**

**Comment by Mashakal** [comment]
Have you tried deleting the emulator's .service file?  It's in your temp folder, mine is located at the following location: C:\Users\t-alneue\AppData\Local\Temp\emulator.service

**Comment by aqalalwa** [comment]
Yeah it really worked for me!. But it doesn't make sense to delete such file in order to make it run, does it?

**Comment by Mashakal** [comment]
I think it's currently possible to put bad data in the URLs and close the emulator, therefore storing those values to be loaded when it's opened again and the exception that's thrown isn't handled. I'm not sure that's the exact problem though.

**Comment by Andrea-Orimoto** [comment]
Thanks for reporting this, we've filed it as a bug to investigate.
