### ISSUE TITLE
Sending a formatted link to client

### ISSUE THREAD

**Issue by muchimoto** [Microsoft/BotBuilder#104]
I have tried:
```
1. session.send('[display text] (http://ww.bing.com)')
2. session.send('[display text (http://ww.bing.com)]') 
3. session.send('(display text) [http://ww.bing.com]') 

```
What is the correct way to send formatted links?

**Comment by tomlm** [comment]
`[display](http://link)`
http://docs.botframework.com/connector/message-content/#navtitle 

NOTE: Some channels (like SMS) don't support named links, and so it will render as 
`display http://link`

**Comment by muchimoto** [comment]
Does this work without bot-connector? I am using BotBuilder for Node.

**Comment by tomlm** [comment]
No, if you are binding directly to an environment then it is up to you to figure out how to render in that environment.  
The connector acts as layer to isolate you from having to do that, and it does that by translating from markdown to the target environment.

Skype doesn't support markdown, but it does support `<b>bold</b><I>italic</I> and <quote>quotedtext</quote> <s>strikethrough</s>"

**Comment by muchimoto** [comment]
>  Skype doesn't support markdown, but it does support <b>bold</b><I>italic</I> and <quote>quotedtext</quote> <s>strikethrough</s>

So currently there is no way to send a formatted link via SkypeBot? 

Also, could you point me in the direction of where it is documented how to render in the skype environment, specifically (other than the formatted link) I am also trying to send Images to client without the shaded image and link source text on the bottom left corner.

**Comment by tomlm** [comment]
skype currently will add better support in the near future.

**Comment by OleksandrBezhan** [comment]
Facebook also doesn't support named links, as I have found today.
