### ISSUE TITLE
Bot Post Activity doesn't contain the 'ReplyToId' field

### ISSUE THREAD

**Issue by aqalalwa** [Microsoft/BotBuilder#1040]
I started to implement a bot to be connected to Skype, so I followed the basic template and cleared the data of the 'Post' method to implement mine. I published the bot to 'Azure' and registered it through 'Bot Framewrok' and then activated the Skype channel. In Skype, it has been connected successfully, and it is capable to process input and return response, but I needed to know the 'Username' of the connected Skype account, so I called 'activity.ReplyToId'. But it unfortunately return nothing!

- Code snapshot:
![image](https://cloud.githubusercontent.com/assets/11869771/17779422/41cc3e3c-6570-11e6-87e0-65d7a817ed3f.png)

**Comment by Thegaram** [comment]
The documentation says:

> replyToId: the original id this message is a response to

i.e. it is the ID of the previous activity that `activity` is a response to (not the user's ID!). When you call `activity.CreateReply`, it does this:

```cs
...
reply.ReplyToId = this.Id;
...
```

It is understandable that this field is `null` in your case, as the initial message is not a reply to anything. How about using `activity.From.Name` for getting the username?

**Comment by aqalalwa** [comment]
You were right about the 'ReplyToId' filed. I should initiate the replying activity before I use it.

But 'activity.From.Name' in Skype returns the user nickname, while I wanted the unique username of the Skype account which is the identifying ID for each account.

**Comment by Thegaram** [comment]
How about `activity.From.Id`? It is a unique identifier for the user. It probably isn't the same as the ID used by Skype though.

[This](https://docs.botframework.com/en-us/skype/getting-started/#navtitle) says regarding `activity.From.Id`:

> Each Skype user is assigned a unique ID for your bot, which is sent along with the Display Name with every message.

**Comment by tomlm** [comment]
From.Id is the unique id of the user on the channel
From.Name is the name if available for the user on the channel
To reply you want to do
      Activity reply = activity.CreateReply("this is my message");
      await connector.Conversations.ReplyToActivityAsync(reply);
or 
      Activity reply = activity.CreateReply();
      reply.Text = "this is my message";
      await connector.Conversations.ReplyToActivityAsync(reply);
