### ISSUE TITLE
Facebook Messenger Emot Intent

### ISSUE THREAD

**Issue by JpEncausse** [Microsoft/BotBuilder#1041]
Hi,
Is there a convenient way / best practice to match incoming emot icon that can be:

- The big blue thumbUp (it seems to be a sticker id ?)
- The emot (look likes encoded chars in text : ""
- The manual emot like :-) :) :-P

Question: How to set a list of Emot/Sticker/... has a dialog intent/regexp/luis ?

Thanks

**Comment by reyesrico** [comment]
One way that emoticons can be managed is this one:
1. Use a global emoji cheat sheet list. 
(http://www.webpagefx.com/tools/emoji-cheat-sheet/)
2. Map of the emoji code and its unicode data 
(http://unicode.org/emoji/charts/full-emoji-list.html)
3. Implement a dictionary in your C# or NodeJS with this map.
4. Use an Unicode code point utility to proper manage your code. 
(i.e. CodePoint for NodeJS - https://www.npmjs.com/package/codepoint).

**Comment by reyesrico** [comment]
If you still have more comments, please reopen the issue. Thank you.
