### ISSUE TITLE
[Telegram] - Prompt.choice button not working

### ISSUE THREAD

**Issue by Hanoko** [Microsoft/BotBuilder#1042]
Hi, 
Trying to make a prompt.choice list buttons working on Telegram and doesn't work. It appears as a list but if i click on one if the options doesn't do anything. It does work on the emulator.

Tried to use ListStyle.button but still not working:
var options = {listStyle: builder.ListStyle.button};
builder.Prompts.choice(session, prompts.runPrompt, titles, options);

runPrompt: 'Which test would you like to run?'
for(index = 0; index < tests.length; index++) {
	titles[tests[index].description +" ("+ tests[index].numQuest+ ")"] = tests[index].id;
}

In v1.0/1.1 it used to work on Telegram.
Thanks.

**Comment by eanders-MS** [comment]
@Hanoko is telegram reporting an error on your bot's channel configuration page? If so, this may provide more information about cause of the failure.

**Comment by Hanoko** [comment]
Nope, Telegram shows as Running in the configuration channel. 

If I write the number of the option I want to choose it works, but I want the user to click the button instead of writing the option.

**Comment by eanders-MS** [comment]
We just rolled out an improved portal UI for viewing channel errors. We now show a list of errors rather than only the most recent one. You might try reproducing the problem again in Telegram, and then go check the portal page for a logged error.

Have you configured Azure App Insights for you bot? Helpful status and error messages can accumulate there as well.

What is your bot id?

**Comment by Hanoko** [comment]
I have reproduced the error and nothing appears on the portal UI. 

Haven't configured Azure App Insights.

My bot id is pablobot. Or did you mean Microsoft App Id?

**Comment by eanders-MS** [comment]
Looking through our logs for Telegram, I only successful transactions with your bot. Choice replies look correctly formatted, and are accepted by your bot. Can you provide more information about the error? A fiddler trace may be helpful as well.

**Comment by Hanoko** [comment]
Yeah, that replies are when I write the answer. What is not working seems like it is done to do so. 
I have uploaded two screenshots: when I have to write to make it work and one when clicking one button.

![img_0706](https://cloud.githubusercontent.com/assets/8871984/17859216/f8c4cdb4-6888-11e6-9b0d-03fa0a0d7172.PNG)
![img_0707](https://cloud.githubusercontent.com/assets/8871984/17859221/0579da4a-6889-11e6-8390-3b072e8e1998.PNG)

**Comment by Hanoko** [comment]
Ok, it is solved.

It was a problem with 

session.message.sourceEvent.callback_query.message.from.first_name
and
session.message.sourceEvent.message.from.first_name

**Comment by eanders-MS** [comment]
Oh that's great. So glad you got it solved. One other thing to keep in mind is the size limit Telegram puts on the value of the button response. They limit it to 64 characters. Documented here:
https://core.telegram.org/bots/api#inlinekeyboardbutton

Cheers, Eric
