### ISSUE TITLE
When a "Choice" is selected, I want to build a Form

### ISSUE THREAD

**Issue by Kris-Nimmagadda** [Microsoft/BotBuilder#1044]
I have a scenario wherein, I show Choices, based on the choice the user selects, I will create a new Dialog like below : 
              
                _internal static IDialog<XYZData> MakeXYZDialog()
                {
                       return Chain.From(() => FormDialog.FromForm(FormDialogBuild.BuildXYZForm));
                 } 
                internal static IDialog<ABCData> MakeABCDialog()
               {
                      return Chain.From(() => FormDialog.FromForm(FormDialogBuild.BuildABCForm));
                }_
        
ABC, XYZ are the choices (Services as I call them) and when I identify the choice the user selects, this is how I am navigating to the respective dialog like this from the resumeAfter of the Choice, here is how my resume function looks like :
             
               _public async Task ResumeAndCallDialogAsync(IDialogContext context, IAwaitable<Services> argument)
               {
                     Services service = await argument;          
                     await context.PostAsync($"Ok, here we go with {service}");
                     if (service == Services.ABC)
                     {
                             context.Call<ABCData>(MakeABCDialog(), ABCStopAsync);
                     }
                    else if (service == Services.XYZ)
                    {
                           context.Call<XYZData>(MakeXYZDialog(), XYZStopAsync);
                    }
             }_
           
Here is the Problem :  when the user selects a choice, say, XYZ or ABC, I want the respective Form Prompts to show up. 
In the chat window this is what happens : User selects a choice, the selected choice is printed by the Bot, then it **waits**. Since I am calling context.Call, I expect it to go ahead prompt me with the selected Dialog's Form field Promts after showing the selected choice as per its BuildForm implementation.
But, it only happens after I give some random message. It doesn't matter what I give... WHY ? there are no Context.Wait that I am calling explicitly in this flow, then why should it wait ? Is the choice that gets printed by the Bot is making the current dialog go into wait-state ? Been pulling my hair for the last 2 days...
if it were not a choice, it was working fine, if they are strings and not enums (my choices).

**Comment by ejadib** [comment]
In the FormDialog.FromForm try specifying the FormOptions with the value PrompInStart. 

`FormDialog.FromForm(FormDialogBuild.BuildABCForm, FormOptions.PromptInStart);`

**Comment by Kris-Nimmagadda** [comment]
ooh my God .... that's it .... it works... killing myself for the last 2 days for this... :-(  -   Thanks a ton !!!

**Comment by Kris-Nimmagadda** [comment]
Also never mind with the sleazy way of string comparisons ...

**Comment by Kris-Nimmagadda** [comment]
Thank you again .. I am closing this issue.
