### ISSUE TITLE
I can't register my bot on the framework

### ISSUE THREAD

**Issue by zayy862** [Microsoft/BotBuilder#1045]
I am having an issue with registering my bot. It pops up with the error
Object reference not set to an instance of an object.
I read in an earlier message that you had to make sure all of the url links used https:// which mine does.
Has anyone else ran into this issue?
I also have tested it with the emulator locally and it all checks out

![2016-08-18](https://cloud.githubusercontent.com/assets/11012246/17798519/6da81446-6597-11e6-9b39-034282119fe0.png)

**Comment by kienct89** [comment]
I ran into this issue once, that was because I didn't fill in the microsoft app id.
Make sure that you have entered all required values.

**Comment by zayy862** [comment]
I do have it filled out. It was put in automatically when I created the app I'd and password. I have been trying to figure out the issue with it but have had no luck.

I even tried to use a different Microsoft account and recreated the entire bot on another azure portal and etc but it is the same issue.

Get Outlook for Android<https://aka.ms/ghei36>

**Comment by craigjensen** [comment]
There is a bug in the bot validation code that will be fixed soon.  For now make sure you fill in all the properties with valid values.
