### ISSUE TITLE
[Rest API] Requests to skype.botframework.com return 202 and do not work

### ISSUE THREAD

**Issue by skyrpex** [Microsoft/BotBuilder#1046]
Hi all,

I'm using the Rest API. I use the activity->serviceUrl to create the URL to send activities (message/text) to the user, but doesn't work for Skype. It works if I use https://apis.skype.com.

Is there a service URL that works for every channel?

Thanks.

**Comment by Thegaram** [comment]
`serviceUrl` is channel-specific. What URL does Skype give you? Doesn't it work with `skype.botframework.com`?

Generally, you should never manually specify the `serviceUrl` but instead use the one sent to you by the channel. For example, you can use the one specified in the message of type `conversationUpdate` that you receive when your bot is added to a conversation.

**Comment by skyrpex** [comment]
The activity I receive (given an user's message written to the bot) gives me serviceUrl ```https://skype.botframework.com```, but posting activities there seems to have no effect. I'm currently replacing ```https://skype.botframework.com``` with ```https://apis.skype.com``` in order for it to work.

**Comment by Thegaram** [comment]
What are you experiencing exactly? `https://skype.botframework.com` replies me as expected. Using `serviceUrl` should work, as that's what the SDK uses (as far as I know).

**Comment by skyrpex** [comment]
If I send a POST request to ```https://skype.botframework.com/v3/conversations/12345/activities``` nothing happens at all and I get this response:

```json
{
    "statusCode":202,
    "reasonPhrase":"Accepted",
    "bodyContents":""
}
```

If I send the same POST request to ```https://apis.skype.com/v3/conversations/12345/activities``` I **do** receive the message in my chat, and I get this response:
```json
{
    "statusCode":201,
    "reasonPhrase":"Created",
    "bodyContents":""
}
```

Maybe I'm missing a parameter used at the botframework API in my request... I send this:

```json
{
    "type":"message/text",
    "from":"...",
    "text":"..."
}
```

**Comment by skyrpex** [comment]
I think I've fixed it adding the *conversation* and *channelId* attributes to the request.

**Comment by msft-shahins** [comment]
The message type should be `message`, `message/text` is not a valid type for skype.botframework.com.
