### ISSUE TITLE
FaceBook user Profile

### ISSUE THREAD

**Issue by JpEncausse** [Microsoft/BotBuilder#1047]
Hi,

I implement a middleware to get the user profile from Facebook because it seems not available from MS Bot Framework. Am I right ?
https://developers.facebook.com/docs/messenger-platform/user-profile
- How can I get the Facebook email ? it seems not available from user's profile. 
- Geolocation is also not available ? (A user can send it's geoloc, but it's not an always available field)

Thanks

**Comment by J3QQ4** [comment]
1) No way to grab the email from the bot. The page app is very limited in that, unlike normal facebook app. 

2) Not available. Someone told me it can be stored in activity.Entities if the user shares the location to you manually, but it didn't work for me either, both the Attachments and Entities are empty.

**Comment by slidenerd** [comment]
@J3QQ4 have you tried to access the data under sourceEvents to get the email?

**Comment by J3QQ4** [comment]
@slidenerd I'm not sure where that is in the C# version which I'm using.

**Comment by chrimc62** [comment]
@msft-shahins can you comment or close as appropriate?

**Comment by msft-shahins** [comment]
@JpEncausse currently it is not possible to access the email address with the page access token. You can only access the fields that are listed [here](https://developers.facebook.com/docs/messenger-platform/user-profile#request) by making user profile api calls using the page access token (this is enforced by facebook). 

@JpEncausse, @J3QQ4, if the user choose to share location with your bot, you can find the geo-coordinates of the user either in the channel data of the activity (by parsing the original message sent by facebook) or in the entities. Here is an example of how you can access the geo-coordinates shared by user from the entities: https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Samples/EchoBot/EchoLocationDialog.cs#L110
