### ISSUE TITLE
Facebook Auth works on Emulator and not on skype

### ISSUE THREAD

**Issue by Kris-Nimmagadda** [Microsoft/BotBuilder#1048]
Facebook Auth Sample not working on Skype. It works fine on the Emulator. The moment I deploy it to Azure it says bad request while exchanging the Code with Access token - while it says the redirect_uri is not matching, it is sure that they match. Can somebody help out.

**Comment by msft-shahins** [comment]
this commit [https://github.com/Microsoft/BotBuilder/commit/4de17cc4fddba29454c07d65d2a0a42f249b2182] should solve this issue.
