### ISSUE TITLE
Unable to send data uri based images in response

### ISSUE THREAD

**Issue by perusworld** [Microsoft/BotBuilder#1049]
Eg. 

        var card = new builder.HeroCard(session)
            .title("Microsoft Bot Framework")
            .text("Your bots - wherever your users are talking.")
            .images([
                builder.CardImage.create(session, "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==")
            ]);
        var msg = new builder.Message(session).attachments([card]);
        session.send(msg);

**Comment by msft-shahins** [comment]
Having a base64 encoded image in a card is not yet supported in Skype. You can only have a base64 encoded image as an attachment for now.
