### ISSUE TITLE
Remove Implicit Any from Included TypeScript Definition File

### ISSUE THREAD

**Issue by thoughtentity** [Microsoft/BotBuilder#105]
The bundled TypeScript definition file included in npm package will cause build errors durring a TypeScript build if a user's `tsconfig.json` file has the `noImplicitAny` option set.

<img width="932" alt="screen shot 2016-04-14 at 12 16 46 am" src="https://cloud.githubusercontent.com/assets/208549/14519867/41581b72-01d6-11e6-9a2f-7f48bc38a557.png">

**Comment by Stevenic** [comment]
I've checked in a fix for this. Should be pushed in the next version of the library I'm planning to release later tonight.

**Comment by Stevenic** [comment]
So to be clear... I think the issue you're seeing is that YOU have noImplicitAny enabled for your project and I had missed a couple of spots in my .d.ts file. I've checked in fixes for those issues which should allow your project to build now.

**Comment by Stevenic** [comment]
Should be fixed in v0.9.0
