### ISSUE TITLE
Is it possible to edit \ update previously sent message to skype \ telegram \ slack? 

### ISSUE THREAD

**Issue by dmdnkv** [Microsoft/BotBuilder#1050]
Actually, telegram Bot API has this feature https://core.telegram.org/bots/api#updating-messages
Slack also has this feature https://api.slack.com/methods/chat.update
What about skype, I didn't find the answer.

I wonder whether it is possible or not to edit previously sent message by bot framework?

**Comment by eanders-MS** [comment]
The botbuilder SDKs do not support this directly, but you can do it using the channelData field of the message activity. The channelData field allows your bot to send channel-native messages. Some documentation exists here (not specific to C#, even though it is in the URL):
https://docs.botframework.com/en-us/csharp/builder/sdkreference/channels.html

**Comment by dmdnkv** [comment]
Great, thanks. But what about skype there is no any mention of it on that page, is it means that skype is not support this feature?

**Comment by eanders-MS** [comment]
No, Skype does not support editing /updating previously sent messages.

**Comment by dmdnkv** [comment]
@eanders-MS ok, got it

**Comment by marcussacana** [comment]
a old api version, i can send a message, pick your ID and edit it...

**Comment by srozga** [comment]
I understand that this is not supported but it appears that slack enables this behavior by exposing a editMessage endpoint on their API (as opposed to postMessage which just adds a message). Using channelData we cannot tell the connector which slack endpoint to use. How can the bot builder framework support the edit scenario on slack?
