### ISSUE TITLE
DescribeAttribute image not displaying

### ISSUE THREAD

**Issue by chocvanstraw** [Microsoft/BotBuilder#1051]
I have several enums that use the [Describe] attribute to specify a description and an image.  As follows:

public enum DrinkOptions
{
[Describe("Small Soda", "http://someurl/small.jpg"]
SmallSoda,
[Describe("Large Soda", "http://someurl/large.jpg"]
LargeSoda
}

When using the bot channel emulator these values are rendered as buttons with both the text and the image as expected.  However, when I run the same in Slack or Skype only the button and text is rendered.  No image is displayed.

Is this a limitation of Skype and Slack?

Thanks

**Comment by msft-shahins** [comment]
@chocvanstraw have you tried this with nuget 3.2 release? They should be mapped to cards with the latest release.

**Comment by chocvanstraw** [comment]
That seemed to work a little better.  How difficult would it be to allow image locations to be injected into this attribute so it is easier to move through environments?  I created a custom version of the attribute to accomplish this but it's not the greatest solution.  Also, would it be possible to specify image sizes in this attribute?
