### ISSUE TITLE
when user does a POST request to directline it should return a response back from the bot

### ISSUE THREAD

**Issue by bluekite2000** [Microsoft/BotBuilder#1052]
Currently I have to do a GET. And If I do the GET too quickly bot hasn't responded yet.

**Comment by dandriscoll** [comment]
Hi @bluekite2000, this would only be possible for v1 bots (which _may_ send a reply to a message) but it's not possible for v3 bots. V1 will be retired soon and we're not planning on adding this feature before that happens.
