### ISSUE TITLE
[C#] Telegram - error when get response : error_code":400,"description":"Bad Request: Url host is empty"

### ISSUE THREAD

**Issue by Varooneh** [Microsoft/BotBuilder#1053]
Hi, when I want work with botframework and telegram, I get this error 
{"ok":false,"error_code":400,"description":"Bad Request: Url host is empty"}
what is this? and how to fix?

**Comment by eanders-MS** [comment]
Hi Varooneh, What are you trying to do when you receive this error? Also, what is your bot handle?

**Comment by Varooneh** [comment]
Hi @eanders-MS, when I want answer to user request from my bot engine, data from user send successfully to my service with botframework but in response step to user I see this error in botframework Bot List, I've this error for all bot created in telegram, I've 20 bot and get this error for all. 
for sample : @AbanSampleBot or @BahounehFoodBot, bot's and api's work perfect in skype and etc but in telegram I've error.
Log:
8/24/2016, 12:31:25 PM	POST to AbanSampleBot failed: POST to the bot's endpoint failed with HTTP status 500
8/24/2016, 2:42:38 AM	There was an error sending this message to your bot: InternalServerError
8/24/2016, 2:07:51 AM	POST to AbanSampleBot failed: POST to the bot's endpoint failed with HTTP status 500
8/24/2016, 1:41:38 AM	{"ok":false,"error_code":400,"description":"Bad Request: Url host is empty"}
8/21/2016, 2:59:23 PM	{"ok":false,"error_code":400,"description":"Bad Request: Url host is empty"}
8/21/2016, 8:18:03 AM	POST to AbanSampleBot failed: POST to the bot's endpoint failed with HTTP status 500
8/21/2016, 8:18:02 AM	There was an error sending this message to your bot: InternalServerError
8/21/2016, 5:29:28 AM	{"ok":false,"error_code":400,"description":"Bad Request: Url host is empty"}
8/21/2016, 5:27:33 AM	{"ok":false,"error_code":400,"description":"Bad Request: Url host is empty"}
8/20/2016, 3:12:33 PM	{"ok":false,"error_code":400,"description":"Bad Request: Url host is empty"}
8/20/2016, 12:21:55 PM	{"ok":false,"error_code":400,"description":"Bad Request: Url host is empty"}
8/20/2016, 12:21:53 PM	{"ok":false,"error_code":400,"description":"Bad Request: Url host is empty"}
8/20/2016, 12:21:53 PM	{"ok":false,"error_code":400,"description":"Bad Request: Url host is empty"}
8/20/2016, 12:21:48 PM	{"ok":false,"error_code":400,"description":"Bad Request: Url host is empty"}
8/20/2016, 11:58:33 AM	{"ok":false,"error_code":400,"description":"Bad Request: Url host is empty"}
8/20/2016, 11:58:30 AM	{"ok":false,"error_code":400,"description":"Bad Request: Url host is empty"}
8/20/2016, 11:58:29 AM	{"ok":false,"error_code":400,"description":"Bad Request: Url host is empty"}
8/20/2016, 11:58:29 AM	{"ok":false,"error_code":400,"description":"Bad Request: Url host is empty"}
8/20/2016, 11:58:27 AM	{"ok":false,"error_code":400,"description":"Bad Request: Url host is empty"}
8/20/2016, 11:47:01 AM	{"ok":false,"error_code":400,"description":"Bad Request: Url host is empty"}

![untitled](https://cloud.githubusercontent.com/assets/16257304/17977792/51dd5fde-6b08-11e6-8fdc-95381b7bed5e.png)

**Comment by eanders-MS** [comment]
It looks like the message you're sending contains formatting that Telegram is trying to interpret as a markdown link, and failing to do so. For example: [/ShowMenu]. In markdown syntax, square brackets indicate a link, and so Telegram is trying to parse the contents inside the brackets as a URL.

You might try escaping them, but I'm uncertain whether Telegram supports escaping of special characters.

`\[/ShowMenu\]`

Eric

**Comment by Varooneh** [comment]
Thank you for reply.
When I send /ShowMenu to backend, just /ShowMenu (without brackets) post to server like /start or and telegram command: /help, /cancel or etc... command (this is default way for telegram command [https://core.telegram.org/bots#commands](url) ), 2 or 3 week ago system worked successfully but know, when I want use telegram bot with botframework I've this error. telegram bot support says : Can you send the exact request you are trying to do (including the parameters)? but I can not access to this data, also when I set webhook to another web service (without/outside botframework), telegram with this /ShowMenu worked successfully.

**Comment by Varooneh** [comment]
![untitled1](https://cloud.githubusercontent.com/assets/16257304/17979038/fbe81c62-6b0d-11e6-9793-6540ccb8a916.png)

See this picture, when I send /start (default command for all bot), I've data successfully in my database in server but when service want to send data to user i've again error.

**Comment by eanders-MS** [comment]
What happens when you send the message without the brackets? Are you seeing the same error?

**Comment by Varooneh** [comment]
Yes, I see same error for all user entry like /start or int value or string value or /ShowMenu or /ContactUs or etc... in all bot, when user send /ShowMenu (without brackets) when click on it (user no need type /ShowMenu just click on it and telegram send only /ShowMenu like /start), in database I create a log (log created successfully) then, I get bot handle from activity and make a menu based on bot handle (menu created successfully) and pass to user then, user follow the manual. All of this process worked successfully in 2, 3 week ago .

**Comment by eanders-MS** [comment]
When it was working 2-3 weeks ago, was the message formatted like it is now, with the slash command in square brackets? When formatted like this `1- پیتزا - [/XedRZs]`, it was working?

Looking through our Telegram service logs, the most recent failure from one of your bots happened at 10:26 AM PST (about 30 mins ago). The message still contained the slash command surrounded by square brackets (the [ and ] characters). Telegram is rejecting the message because the text inside the brackets is expected to be a URL. Telegram tries to parse the slash command as a URL, doesn't find a hostname, and returns an error.

As a test, are you able to successfully send the same message without the brackets? e.g., this:
`1- پیتزا - /XedRZs`
instead of:
`1- پیتزا - [/XedRZs]`

**Comment by Varooneh** [comment]
When user want to work with bot, in menu user see `1- پیتزا - [/XedRZs]` , for response, user can send 1 or click on `/XedRZs` like link and then, 1 or `/XedRZs` send to server, brackets just use like a border and not send to server, I traced input string from user and it's ok.

> When it was working 2-3 weeks ago, was the message formatted like it is now, with the slash command in square brackets? When formatted like this 1- پیتزا - [/XedRZs], it was working?

Yes, it was like it is now and it's worked successfully, I'm sure square brackets not send to server but for for greater certainty I test again.

> Looking through our Telegram service logs, the most recent failure from one of your bots happened at 10:26 AM PST (about 30 mins ago). The message still contained the slash command surrounded by square brackets (the [ and ] characters). Telegram is rejecting the message because the text inside the brackets is expected to be a URL. Telegram tries to parse the slash command as a URL, doesn't find a hostname, and returns an error.

Yes, I know telegram check bracket and markdown styling but (for me) also /start doesn't work, this is default bot command in telegram bot, all telegram bot for begin conversation with user have /start command at first and according to you (telegram bracket exception) /start should not to work because this is like link.

> As a test, are you able to successfully send the same message without the brackets? e.g., this:
1- پیتزا - /XedRZs
instead of:
1- پیتزا - [/XedRZs]

Yes but, I try to change the code and test again .

Thank you for help me.

**Comment by Varooneh** [comment]
@eanders-MS , I talk with telegram support and he/she say : I think it will be related to html parse mode. You may be adding an empty href parameters. We fixed a bug and this is not anymore supported.
this is a bug from telegram but I need changes all code and structure, telegram says you cannot use /text without command registered or link url.

I, close this issue and very very thank you for help me .
