### ISSUE TITLE
Localization - Facebook Messenger / Webchat

### ISSUE THREAD

**Issue by NicolasHumann** [Microsoft/BotBuilder#1056]
Hi,

The current thread CurrentUICulture is not set with the user localization in Facebook Messenger and Webchat.
The default culture (en) is set whereas Facebook Messenger is in French (tested on mobile with full french (os + app) and in the web site). I have the same behavior in the Webchat iframe, it's always in english (the http header of the browser is also set in french).

Do I missed something ? 

Thanks

**Comment by NicolasHumann** [comment]
Hi,

I found a workaround. The primary issue is  the property activity.Locale is not set.
My workaround is to ask facebook to give me the user locale:


`if (activity.ChannelId.Equals("facebook", StringComparison.InvariantCultureIgnoreCase))
            {
                using (WebClient client = new WebClient())
                {
                    var json =
                        await
                            client.DownloadStringTaskAsync(
                                $"https://graph.facebook.com/v2.6/{activity.From.Id}?fields=first_name,last_name,profile_pic,locale,timezone,gender&access_token=<PAGE_ACCESS_TOKEN>");
                    dynamic jObject = JObject.Parse(json);
                    string locale = jObject.locale;
                    activity.Locale = locale.Replace("_", "-");
                }
            }`

**Comment by willportnoy** [comment]
I think the feature request would be to "set the activity locale from the facebook user's profile".

**Comment by Andrea-Orimoto** [comment]
Added to our backlog for future consideration. Thanks!

**Comment by picatextra** [comment]
Hello, it think still have this issue

**Comment by kevinport** [comment]
me too

**Comment by sherifadel-msft** [comment]
me as well

**Comment by AndreMantas** [comment]
@Andrea-Orimoto what is the state of this task on your backlog after 3 years?
