### ISSUE TITLE
TextFormat - Facebook Messenger

### ISSUE THREAD

**Issue by NicolasHumann** [Microsoft/BotBuilder#1057]
Hi 

According to the documentation, **text** puts the text in bold. This works fine in the emulator and webchat but not in facebook messenger.
In FB, **text** renders *text*

There is a work around ?

Thanks

**Comment by msft-shahins** [comment]
Facebook Send Api only supports plain text at the moment: https://developers.facebook.com/docs/messenger-platform/send-api-reference/text-message
