### ISSUE TITLE
LUIS - Entity - Datetime - 

### ISSUE THREAD

**Issue by sundarradnus** [Microsoft/BotBuilder#1058]
In LUIS, pre-defined entity "datetime" is added.  When the phrase "usage for last month" is entered, the date is not recongized by the following statement:
var date = builder.EntityRecognizer.resolveTime(args.entities); 

If the phrase is "usage for 4 am", it resolves the time properly.

How to get this working for "last month" or "current month", etc.

**Comment by willportnoy** [comment]
In C#, this is the code we use to parse the LUIS datetime resolutions:

https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Luis/Resolution.cs
https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Luis/EntityToType.cs

You may want to use similar logic.

@muzahmed @Stevenic do you have other suggestions?

**Comment by chrimc62** [comment]
@Stevenic or @maxpert can you please comment?

**Comment by Stevenic** [comment]
We're tracking a general work item to improve the way LUIS datetimes get resolved. There are numerous issues. Closing this until that work is done.
