### ISSUE TITLE
Facebook: CardAction: Fail with call and mailto

### ISSUE THREAD

**Issue by JpEncausse** [Microsoft/BotBuilder#1060]
Hi,

I try to set card's button
- openUrl works fine IF the url is http*
- it fails if openUrl is a mailto:. Is there a workaround ?
- it fails if action is call and the number is a string like "+111 11 1111" is there a format ?

If button label is "CALL" it is translated to "Appeler" in french by Facebook ?!

Thanks

**Comment by J3QQ4** [comment]
I believe this is just disabled by Facebook. There seems to be no way to make the call button work there.

**Comment by chrimc62** [comment]
If Facebook does support this and something is missing in the Bot Framework platform, please reopen.

**Comment by Kauntal** [comment]
1 possible work around for mailto can be using a wrapper html page.
`
<html>
<head><meta http-equiv="refresh" content="0; url=mailto:{MAIL TO EMAIL ID}"></head>
<body>
<script type='text/javascript'>
window.setTimeout(function(){window.open('','_self');window.close();},1000);
</script>
</body>
</html>
`
Host this html page on your server and use the hosted link in an URL button of any Facebook messenger template which support URL buttons
