### ISSUE TITLE
Unable to register bot on dev.botframework.com

### ISSUE THREAD

**Issue by karlovnv** [Microsoft/BotBuilder#1061]
I'm trying to register bot (https://dev.botframework.com/bots/new) and every time a get an error: "Object reference not set to an instance of an object."

**Comment by FreakDroid** [comment]
Would be greate if you can share a couple of thing, Where are your bot running? and What is the configuration that you are doing to register the bot? becuase "Object reference not set to an instance of an object." does not say a lot.

**Comment by craigjensen** [comment]
We have a fix going out soon to fix the error message.  For now, make sure you set all properties to valid values, especially the urls.
