### ISSUE TITLE
builder.AttachmentLayout.carousel does not work as expected in slack.

### ISSUE THREAD

**Issue by FreakDroid** [Microsoft/BotBuilder#1062]
Hi guys, today I'm working in create a carousel that show diferents cards, If I understand right the carousel let me select one option as a carouse, but the only that I have is a list (see the picture below):

![carousel](https://cloud.githubusercontent.com/assets/5360335/17867336/7a2048ce-6880-11e6-94fb-a79560bc57b7.jpg)

I don't know If I confused about this functionality, but that I expected that only show one card and a couple of arrow where I can change the options like:

![carousel2](https://cloud.githubusercontent.com/assets/5360335/17867523/36a308ec-6881-11e6-85c4-6f3d422159e0.jpg)
**Note: this is an example that What I expected.**

The code that I'm using is the same from the example  that microsoft provide ([Link here](https://github.com/Microsoft/BotBuilder/blob/master/Node/examples/demo-skype/app.js))

Thanks.

**Edit:** 
For some reason that is not working for slack, in FB-messenger is working ok, and for Skype we need to wait the next release.

**Comment by craigjensen** [comment]
Several channels including Slack do not support native carousels so we fall back to a list which is what you are seeing.  If Slack ever supports carousels we will update the channel to support it.

**Comment by FreakDroid** [comment]
Thanks a lot @craigjensen
