### ISSUE TITLE
[Node.js] Purpose of ConversationId with respect to Facebook connector

### ISSUE THREAD

**Issue by iangriggs** [Microsoft/BotBuilder#1064]
Hi @Stevenic ,

I'm working on an updated version of the `botbuilder-facebook` (https://github.com/andrew-makarenko/botbuilder-facebook/) module that will allow me to use BotBuilder framework v3 and the new UniversalBot. At this point in time it appears the original developer of this module isn't intending to update (for perfectly valid reasons) it so I've taken it up myself to implement something I can use instead.

I'm pretty much complete apart from fully understanding the purpose of the 'conversation id' required in the `address` object response from both the`startConversation` and within the `address` object mapped from Facebook schema to the BotBuilder message schema and passed to the `onEvent` handler.

My gut instinct is that the conversation id is probably not that relevant for a Facebook Messenger bot conversation but would be good to know for sure. I noticed that the conversation id still needs to be set to something in order for dialog conversational state to be persisted. As things stand I'm simply using the users Facebook messenger id for want of a better alternative.

e.g.

```
  this.startConversation = function(address, cb) {
    var adr = Object.assign({}, address);
    adr.conversation = {
      id: address.user.id
    };
    cb(null, adr);
  };
```

Can you explain or point me at some documentation that gives a little bit more information that could clarify things as I've searched the code and nothing is jumping out that explains its purposes beyond its name. As things stand it is all is working but I'm nervous I'm not appreciating something significant that could come back to bite me later.

Thanks.

**Comment by Stevenic** [comment]
@iangriggs sorry for the delay... For facebook, conversationId can probably just be the userId and you're correct it's not that relevant.  It becomes relevant when you can have group conversations as the conversationId might be the ID of either a user or the group you're replying to. On dlack for instance this is typically the channel ID you're replying to. Make sense?

**Comment by iangriggs** [comment]
@Stevenic many thanks for responding. I'd come to that conclusion so good to hear you confirm that directly. The only difference I made since logging this issue was in using the bot identifier, rather than the user identifier as the conversation id. Using that seemed to flow through nicely into how our custom storage handler handled saving both private and global conversation state with both user and conversation as a composite key. More info that you wanted I'm sure but just mentioning out of interest :-)

You might also be interested in knowing that we're successfully running the BotBuilder framework on AWS as a Lambda implementation and storing session state in a SQL based DB - all working really well. Appreciate you would probably prefer it to be Azure based but company policy means we're tied to using AWS at the moment for the hosting. ;-)

Thanks again.

**Comment by Stevenic** [comment]
I had helped someone adapt botbuilder to lambda so we're not biased :)
