### ISSUE TITLE
MS Bot HTTPS connectivity issues on AWS Beanstalk Environment

### ISSUE THREAD

**Issue by stevinraj** [Microsoft/BotBuilder#1065]
I deployed a bot from VB 2015 through AWS add-on in VB successfully. Testing the bot connection on bot framework site failed. I realized the https port was not open in the AWS Elastic Beanstalk Environment. To open the port I need an SSL certification. When trying to get a new certification it is asking for my website. What website is this. I am just trying to deploy a bot. I do not have any website. What should I do.

**Comment by willportnoy** [comment]
Your bot has an endpoint, right?  The "website" is the domain of the bot message endpoint that you enter into the Bot Framework portal.

**Comment by stevinraj** [comment]
Exactly.. I did copy paste the address of my bot..something like botapplication5-dev.us-west-2.elasticbeanstalk.com... because I am hosting my app on AWS....and I get an error message saying "you cannot give amazon site address in here."!! Am I wrong somewhere.  Thanks for your help.

**Comment by willportnoy** [comment]
Where did you see that error message?  I don't know of any hosting restrictions for bots inside the Bot Framework.

Were you trying to set up SSL?

**Comment by stevinraj** [comment]
Yes. After publishing the bot on to AWS Cloud we need an endpoint address for the Bot Framework to communicate with the bot and that is through SSL. I was trying to get an SSL instance in AWS and this is where I am asked for my website address. Now I dont understand what website address is required here.

**Comment by willportnoy** [comment]
You might consider searching for "amazon add ssl aws cloud" and finding an appropriate forum - this question doesn't seem Bot Framework related, so I'm going to close this issue for now.  Feel free to open a new issue for Bot Framework related discussion.
