### ISSUE TITLE
How can I guarantee message delivery when using IDialogContext.PostAsync?

### ISSUE THREAD

**Issue by eydelrivero** [Microsoft/BotBuilder#1067]
I'm sending two messages through the Facebook channel using this code:

```
              `try
                {
                    Task task = context.PostAsync(dummyActivity);
                    await task;
                    await context.PostAsync("Message terminated normally");
                }
                catch (Exception e)
                {
                    await context.PostAsync(e.Message);
                }`
```

The task is just to see what's going on with PostAsync. The first message is not delivered but the second one arrives without problems. Then when I check the Developer portal I see these errors:

> 8/24/2016, 11:08:27 AM    Facebook graph API call failed with: BadRequest {"error":{"message":"(#105) param [elements] has too many elements.","type":"OAuthException","code":105,"fbtrace_id":"Ci6t+CNISwX"}}
> 8/24/2016, 11:08:17 AM  POST to MyBot failed: A task was canceled.
> 8/24/2016, 11:08:17 AM  Facebook graph API call failed with: BadRequest {"error":{"message":"(#105) param [elements] has too many elements.","type":"OAuthException","code":105,"fbtrace_id":"GvTURHxYEBM"}}
> 8/24/2016, 11:08:16 AM  There was an error sending this message to your bot.
> 8/24/2016, 11:08:06 AM  Facebook graph API call failed with: BadRequest {"error":{"message":"(#105) param [elements] has too many elements.","type":"OAuthException","code":105,"fbtrace_id":"GNb\/PRAS6Fz"}}
> 8/24/2016, 11:08:05 AM  Facebook graph API call failed with: BadRequest {"error":{"message":"(#105) param [elements] has too many elements.","type":"OAuthException","code":105,"fbtrace_id":"EWcQJDuOq9t"}}

which seems to indicate I'm sending to many cards within the same attachment in dummyActivity. Is there a way to know that the message failed when doing `await context.PostAsync(dummyActivity);`?

**Comment by willportnoy** [comment]
That seems like a bug - the task should not be marked as completed until the message has been handed off to Facebook.

**Comment by chrimc62** [comment]
@willportnoy can you please investigate or close as appropriate?

**Comment by willportnoy** [comment]
@chrimc62 it's been labeled as a possible bug in the Facebook channel already and added to our internal backlog for investigation.

**Comment by msft-shahins** [comment]
This should be fixed now. Feel free to open a new issue if you are still seeing this issue.
