### ISSUE TITLE
Delivery failure on Skype

### ISSUE THREAD

**Issue by filipeperdigaosousa** [Microsoft/BotBuilder#1069]
I created have a Nodejs bot that already worked on skype.
I needed to create the bot in a new microsoft account, so I deleted the older and created a new one with same configurations.

Now i can communicate through widget and emulator but skype messages are not being delivered, appearing a little warning icon on each message.

Anyone knows why is it happening?

**Comment by graphnode** [comment]
Having the exact same problem.

I tested it on the Facebook Messenger channel and it worked and the test button also works but on skype I always get delivery failure after the bot is added successfully.

**Comment by filipeperdigaosousa** [comment]
my skype bot is working again

**Comment by graphnode** [comment]
Can confirm, it stared working. I think it was some service or deploy that went wrong.

Could we get information when this happens on the dashboard? The issue count was 0.

**Comment by KrishnanA** [comment]
Hello, sorry for the trouble. We had to rollback a deployment when we noticed the issue. We will look into making information available on the dashboard.

**Comment by murtazadhari** [comment]
I have suddenly started to get delivery failure on skype? any reason for this?

**Comment by KrishnanA** [comment]
Can you please provide your bot Id and more information on what failure you are seeing? There are currently no known incidents.

**Comment by carvalThi** [comment]
Hello,

I am having the same issue : Delivery failure while trying to talk to my bot on Skype. It was working before but i deleted it and created it again with a new account and now it does not work anymore.
It works perfectly on the other channels.

Is there another similar incident at Microsoft ?

Thanks
