### ISSUE TITLE
BotConnectorBot cannot send multiple messages in one dialog handler

### ISSUE THREAD

**Issue by shtas** [Microsoft/BotBuilder#107]
Same issue as the [comment](https://github.com/Microsoft/BotBuilder/issues/26#issuecomment-207630477) made by @mikkhait in #26

I'm trying to send two consecutive messages without prompting for a response.

This works fine with a TextBot, but not with a BotConnectorBot
```javascript
var builder = require('botbuilder'),
    restify = require('restify');

var textbot = new builder.TextBot(),
    botConnectorBot = new builder.BotConnectorBot();

var sayTwoThings = function (session) {
   session.send('Say this');
   session.send('And then this');
};

textbot.add('/', sayTwoThings);
botConnectorBot.add('/', sayTwoThings);

textbot.listenStdin();

var server = restify.createServer();
server.post('/api/messages', botConnectorBot.verifyBotFramework(), botConnectorBot.listen());
server.listen(3978);
```
Typing something in the command prompt after running the above produces:
```
Say this
And then this
```
Typing something in the Bot Framework Emulator just produces this:
```
Say this
```

I'm using botbuilder 0.8.0

**Comment by wkadwaikar** [comment]
I have the same issue. Not sure what would be the alternative.

**Comment by Stevenic** [comment]
Oh I see the issue... You need to tell the BotConnetcorBot you're using the emulator:

```
// Check for emulator usage
if (process.env.EMULATOR_PORT) {
    bot.configure({
        endpoint: 'http://localhost:' + process.env.EMULATOR_PORT
    });
}
```
The default port is 9000 I've been bit by this before too.

**Comment by shtas** [comment]
Got it. Thanks! :smile:
