### ISSUE TITLE
Processing the completed order

### ISSUE THREAD

**Issue by sudeepsama** [Microsoft/BotBuilder#1070]
(BotBuilder/CSharp/Samples/AnnotatedSandwichBot/Controllers/MessagesController.cs ) inside MakeRootDialog()  function, when we try to process the completed variable, the formflow object skips the completion block and restarts formflow.
For example, I am trying to process the final order from 'completed' object. But it doesn't allow to use the object to retrieve value from another object based on result. 
Where as if we directly use it in postasync, we are able to send the complete order to bot chat window.
Am I missing anything?

**Comment by willportnoy** [comment]
Generally you call the FormDialog as a child dialog, and it returns the completed form to your resume handler.

call:
https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Samples/PizzaBot/PizzaOrderDialog.cs#L61

resume with form value:
https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Samples/PizzaBot/PizzaOrderDialog.cs#L69
