### ISSUE TITLE
"To" field is missing from messages in DirectLine (and WebChat) API

### ISSUE THREAD

**Issue by rzmoz** [Microsoft/BotBuilder#1072]
Hi,

I'm implementing a custom sms channel using DirectLine for integration. The Issue is that the direct line messages api doesn't have the TO field set:
https://docs.botframework.com/en-us/restapi/directline/#!/Conversations/Conversations_GetMessages

This makes it impossible to send the sms without storing the TO filed somewhere on the client side.

As a side note, I tried the webchat API as well as they have identical protocols but it lacks the TO field as well.

**Comment by NicolasHumann** [comment]
Hi, for me the To field your are looking for is the conversationId

**Comment by dandriscoll** [comment]
That's correct, @NicolasHumann, @rzmoz, the protocol designates that all messages are sent to the conversation, not to a particular recipient.

If you would like to pass additional information to your bot, you can use the ChannelData field, which is a tunnel between your bot and your client. You can put a To field, or any other field you like, in ChannelData.
