### ISSUE TITLE
[Node.js] Expand hero card in skype

### ISSUE THREAD

**Issue by Avartarus-Testicus** [Microsoft/BotBuilder#1074]
Hi,
I tested some stuff with herocard for skype...like below:

var card = new builder.HeroCard(session)
    .title(test)
    .text(test + ':' + '\n\n'+
          test +
          test +
         '\n\n')
    .buttons([test])

...and I noticed, If the content in .text() is too long, the hero-card isn't expanding. At beginning you can see your text, but at a certain point the content isn't shown anymore. Is there a trick or styling-property, by which I can scale the card ??

**Comment by reyesrico** [comment]
I have reproduced the same that you are facing. It seems that Skype channel has a limit of characters like Facebook channel. I have tried with WebChat and Telegram and the long-text is being displayed successfully.

**Comment by v-ms** [comment]
Skype Hero cards have the following limitations on the number of lines displayed:

title - 2 lines max
subtitle - 2 lines max
text - 2 lines or more if either Title or Subtitle are not present. If Title is missing, 2 more lines of text are allowed. If SubTitle is missing another 2 lines of text are allowed.

So the maximum number of lines for text (if both title and subtitle are missing) is 6 lines.

**Comment by Avartarus-Testicus** [comment]
Too bad, that there is no way for expanding. But thanks for your answers
