### ISSUE TITLE
Where does IBotDataStore save data?

### ISSUE THREAD

**Issue by afficionaddo** [Microsoft/BotBuilder#1075]
Hi,
I am using BotState to maintain conversation of the chat.

May be I am just spitballing here:
But where exactly does it save data?...what's the location? Some server of yours?

**Comment by willportnoy** [comment]
https://docs.botframework.com/en-us/technical-faq/#where-is-conversation-state-stored

Tell me if you have further questions.

**Comment by afficionaddo** [comment]
Super @willportnoy .....the FAQs are awesome.

**Comment by slidenerd** [comment]
So basically the IBotState is a Hashmap in simple words that maintains data as long as the server is running or we havent exceeded 32kb of storage?
