### ISSUE TITLE
How to send Facebook's Quick Replies

### ISSUE THREAD

**Issue by kenyeung128** [Microsoft/BotBuilder#1077]
Hi, it doesn't seems the botbuilder framework support Quick Replies from Facebook:
https://developers.facebook.com/docs/messenger-platform/send-api-reference/quick-replies

Would it be a workaround for it or plan for next release? Thank you

**Comment by willportnoy** [comment]
The node version supports quick replies: more information on https://github.com/Microsoft/BotBuilder/issues/585.

The C# version might support it through channel data - I haven't tried it myself.

**Comment by ejadib** [comment]
@kenyeung128 I just tried using channel data in C# per Will suggestion and it's working

```
public async virtual Task MessageReceivedAsync(IDialogContext context, IAwaitable<IMessageActivity> result)
        {
            var message = await result;

            var reply = context.MakeMessage();
           // reply.Text = "test";

            var channelData = new JObject();
            var child = new JObject();
            child.Add("content_type", "text");
            child.Add("title", "Red");
            child.Add("payload", "DEVELOPER_DEFINED_PAYLOAD_FOR_PICKING_RED");
            channelData.Add("quick_replies", new JArray(child));
            reply.ChannelData = channelData;

            await context.PostAsync(reply);
            context.Wait(this.MessageReceivedAsync);
        }
```

**Comment by kenyeung128** [comment]
great! @ejadib It works! Since this only works for facebook, I would put a if-clause to check if it's a facebook channel too.
