### ISSUE TITLE
[Node.js] intent has score 0 but it shouldn't

### ISSUE THREAD

**Issue by ziggy42** [Microsoft/BotBuilder#1079]
I created a LUIS application with some intents and all was working fine.
Then I added a new intent and when I send a message that should match that intent I always end up in `onDefault` . All I get is `{ score: 0, intent: null }`.
But in the LUIS dashboard I can see that those utterances are correctly classified, sometimes even with a 1.

**Comment by DOMZE** [comment]
Did you update (publish) your LUIS to take in effect your changes?

**Comment by willportnoy** [comment]
I agree @DOMZE that seems like the likely cause.

**Comment by ziggy42** [comment]
Ops, I didn't know I had to do it 😅 thanks!
