### ISSUE TITLE
How to change LUIS model dynamically

### ISSUE THREAD

**Issue by kenyeung128** [Microsoft/BotBuilder#1081]
Hi

How would it be possible to update the LUIS Model in LuisDialog dynamically? There is LuisModel attribute but I can't see where I could change this model dynamically, if user change the language. Thanks!

    [LuisModel("xxxxxx-xxxxx-xxxxx-xxxx-xxxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxxxxxxxxxx")]
    [Serializable]
    public class WelcomeDialog : LuisDialog<WelcomeScreen>{
}

**Comment by willportnoy** [comment]
The LuisDialog constructor takes an ILuisService:

https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Dialogs/LuisDialog.cs#L146

You can implement ILuisService to select which underlying LuisService/LuisModelAttribute you'd like to use based on your language signal.

**Comment by palmerabollo** [comment]
@willportnoy Thanks for the answer. Do you know if that also applies to the Node.js version of the SDK?

**Comment by willportnoy** [comment]
@Stevenic @muzahmed can you comment?

**Comment by jorenl** [comment]
@willportnoy @palmerabollo The Node.JS [IntentDialog](https://docs.botframework.com/en-us/node/builder/chat-reference/classes/_botbuilder_d_.intentdialog.html) constructor takes a list of [IIntentRecognizer](https://docs.botframework.com/en-us/node/builder/chat-reference/interfaces/_botbuilder_d_.iintentrecognizer.html)'s.  The recognizer's are passed a [context](https://docs.botframework.com/en-us/node/builder/chat-reference/interfaces/_botbuilder_d_.irecognizecontext.html) which includes dialogData and the message object. One approach would be to implement your own IIntentRecognizer which just shims your language-specific LUIS models based on, for example, a language flag in dialogData or on the message.

**Comment by kenyeung128** [comment]
Thanks @willportnoy , so I will have 2 seperate dialogs with different language LUIS Service.
