### ISSUE TITLE
LUIS: Transition from one dialog to another, with the new dialog processing the original message sent by the user

### ISSUE THREAD

**Issue by DOMZE** [Microsoft/BotBuilder#1082]
Hello,

As discussed in the following [post](https://github.com/Microsoft/BotBuilder/issues/127) by @ylibrach

Trying to transition a message i.e. LuisDialog A picks up a message, and then decides to transfer the message to LuisDialog B.

Overriding LuisDialog.MessageReceived to save the original Message in LuisDialog A, then call LuisDialog B with a method calling the base implementation of MessageReceived, throws a NotImplementedException.

It would be good to have a smooth way to pass the message from a parent dialog to a child dialog when using IDialogStack<R>.Call method

**Comment by willportnoy** [comment]
IDialogStack.Forward, exposed through the IDialogContext is a good way to forward the original message to a child dialog.  Does that work for you?

**Comment by DOMZE** [comment]
@willportnoy Forward does indeed forward the request (message)
However, I am getting a System.Runtime.Serialization.SerializationException.

Basically what I am doing is I took the pizza order sample and tried to chain it with another dialog I have (LUIS)

in my luisintent method I am calling the following:
await context.Forward(Chain.From(() =>new PizzaOrderDialog(BuildForm)),OnPizzaOrderingDone, _message, CancellationToken.None);

Where _message is the the IActivity message saved from the override of the MessageReceived method

**Comment by willportnoy** [comment]
Right - Activity itself is not serializable.  Does it need to be preserved across a turn of conversation with the user?  If not, then mark it with the [NonSerialized] attribute or null it out.

**Comment by DOMZE** [comment]
Yes that works perfectly.
Making the field [NonSerialized] solved the problem!
