### ISSUE TITLE
Can't upgrade to Microsoft.Bot.Builder v3.x

### ISSUE THREAD

**Issue by validian** [Microsoft/BotBuilder#1083]
I have been using Microsoft.Bot.Builder v1.x and its been working fine. Once I try to switch to any version 3 of Microsoft.Bot.Builder I get the following error:

Assembly 'Microsoft.Bot.Builder' with identity 'Microsoft.Bot.Builder, Version=3.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' uses 'Microsoft.Bot.Connector, Version=3.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' which has a higher version than referenced assembly 'Microsoft.Bot.Connector' with identity 'Microsoft.Bot.Connector, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

Here is a line of code the references this error:  
return await Conversation.SendAsync(message, () => new MainDialog());

MainDialog is implemented like such (minus methods that aren't constructors to save space on screen here)
//Redacted keys for luis
   [LuisModel("xxxx","xxxx")] 
    [Serializable]
    public class MainDialog : LuisDialog<object>
    {
       public MainDialog(ILuisService service) : base(service)
        {
        }
        public MainDialog()
        {

        }
       
    }
Whatever version I try to install gives me the same error with the version number changing to reflect the version I have installed. This is true for all except v3.2 (which throws an error because I can't update Microsoft.Rest.ClientRuntime above v1.8.2 since Microsoft.Bot.Connector v1.1 doesn't support anything higher than this)

Any help getting this figured out would be greatly appreciated.

**Comment by Thegaram** [comment]
You don't need the `Microsoft.Bot.Connector` package, so just remove it. I'd suggest manually deleting both dlls (`Microsoft.Bot.Connector` and `Microsoft.Bot.Builder`) and then trying to install the updated version of the latter.

**Comment by validian** [comment]
Ok, once I did that (removed both packages and made sure they wern't in packages folder and deleted the bin folder of project so DLL's wouldn't be there) and re-installed to v3.2 of Microsoft.Bot.Connector I get that Message cannot be found:

public async Task<Message> Post([FromBody]Message message)

This is in my Messages controller.

**Comment by validian** [comment]
Nvm, I re-looked at the documentation looks like I should be using Activity now instead of Message.

**Comment by willportnoy** [comment]
@validian I think your issue has been solved - I'm going to close this issue but feel free to open a new issue for further discussions.
