### ISSUE TITLE
Locale files in Node.js SDK

### ISSUE THREAD

**Issue by palmerabollo** [Microsoft/BotBuilder#1085]
I'd like to use `session.ngettext` and `session.gettext`. Where should I put my i18n files and what format should I use to find a text by its `msgid`?

There are classes such as [`DefaultLocalizer`](https://github.com/Microsoft/BotBuilder/blob/master/Node/core/src/DefaultLocalizer.ts#L39) in the repository. If I'm not wrong, they try to parse json files in a `/locale`folder, but the SDK is not clear about how to use them in a `UniversalBot`. Are there any examples available?

**Comment by muzahmed** [comment]
@palmerabollo you'll want them sibling to your bot's app.js file.

take a look at: https://github.com/Microsoft/BotBuilder/tree/master/Node/examples/basics-localization for an example, I'll add some more docs (and features!) around the localization stuff shortly, so stay tuned. 

If you have other questions etc, lmk

**Comment by Andrea-Orimoto** [comment]
@palmerabollo closing this issue, if you still have questions, let us know. Thanks!

**Comment by palmerabollo** [comment]
Thanks for the answer, @muzahmed.

The latest npm package (botbuilder@3.2.3) was released 2 weeks ago, so the following code does not work:

```js
var bot = new builder.UniversalBot(connector, {localizerSettings: { ... }});
```

because there is not a `localizerSettings` property in the `IUniversalBotSettings` interface definition yet. This interface changed only 11 days ago (see [your commit](https://github.com/Microsoft/BotBuilder/commit/cc9228092f6c0fb564cced7af333a4de8f129709#diff-1d1b0cdfb27ad88c7c3e691e9d16bb7b)).

Would it be possible to release a new botbuilder@3.3.0 version with this feature?

**Comment by muzahmed** [comment]
@palmerabollo yup, we will be releasing a new update in the next week that addresses that and provides further features and bug fixes!

**Comment by palmerabollo** [comment]
@muzahmed Do you still think the new release will be ready this week? (this feature is blocking us somehow). Thank you!

**Comment by palmerabollo** [comment]
A suggestion/feature request: load all files under locale/*/*.json (not only locale/*/index.json) to be able to work in different libraries/dialogs in parallel (each library having its own locale file(s)).

**Comment by palmerabollo** [comment]
Any plans to release the new version with i18n support soon?
