### ISSUE TITLE
[Question] Get group info on launch.

### ISSUE THREAD

**Issue by zzzbatmand** [Microsoft/BotBuilder#1088]
Is it possible for the bot "on launch" to detect all friends/groups/chats it's a part of?

I currently have it so the user has to type to the bot atlas once to make it remember the session, but if i remove the bot or add it to a new chat, i want it to know it, every time i launch the program, if this has happened. I have an "on contactRelationUpdate" function, but this only runs if the bot is active and i want it to get the info whether it's active or not.

I catch the `session.message.address` currently when a user messages it, so it can store it, but i want it to detect it by itself, is this possible?

**Comment by hailiu2586** [comment]
which channel are you looking to add this functionality facebook/slack/groupme/skype?

**Comment by zzzbatmand** [comment]
@hailiu2586 It's for skype, i forgot to write it.

**Comment by streamy878** [comment]
I am also interested in this issue. I have similar task. I'm trying to get away from the use of desktop Skype API with wrapper skype4com. I look in the direction of Microsoft Bot Framework. I created and registered my Skype bot with the Microsoft Bot Connector like here: https://docs.botframework.com/en-us/csharp/builder/sdkreference/gettingstarted.html  

Also I added my bot into several group conversations. Now I have a task to write a message to a specific group conversation. For this I need to get a list of group conversations and information about each conversation in which the bot is. I have been unable to find any information about it. Anyone know how to get a list of all groups conversations for Microsoft Bot?

**Comment by streamy878** [comment]
No one has no idea how to get all the group conversations of your bot?

**Comment by jameslew** [comment]
Right now this is not enumerable within the Bot Framework SDK (or the protocol).  The system assumes the bot caches information about the messages/groups its in when the bot is added to a given conversation.

**Comment by zzzbatmand** [comment]
@jameslew So it's not possible at all, or is there a way around it?

**Comment by jameslew** [comment]
I've tagged the Skype team to see if they have any additional info, but at this time I don't know of any way around it.  The Bot Framework service itself does not have a list of the groups your bot is in.

**Comment by streamy878** [comment]
Thank you for your answers. They confirmed my suspicions.

**Comment by nickcordrey** [comment]
Confirming that in Skype there is no way to enumerate the conversations that a bot is currently active in.
