### ISSUE TITLE
Can I upload and publish bot to external server except Microsoft Azure and still accessible from Microsoft bot directory

### ISSUE THREAD

**Issue by remyagiri** [Microsoft/BotBuilder#1089]

**Comment by ankitbko** [comment]
Yes. You can publish bot anywhere with only requirement that it should be accessible over internet over HTTPS.

**Comment by Andrea-Orimoto** [comment]
ankitbko is correct, you can publish anywhere, as long as you have a public https endpoint.

**Comment by jorhendz** [comment]
https://davaointernationaltr.ipage.com/bot/

I successful publish my on but i get error, message couldnt send. please help

**Comment by JasonSowers** [comment]
@jorhendz tis is not an error this is the default web page for your bot.  You can access your bots endpoint by adding /api/messages to the end of the url.  You would need to use a channel to actually talk to you bot though.  Which channel are you trying to use?

**Comment by jorhendz** [comment]
@JasonSowers im using microsoft bot framework, what do you mean by channel? like skype? yes, i want to add my bot in skype, i follow the steps. i register my bots in https://dev.botframework.com/bots/new, amd i add the endpoint like this https://davaointernationaltr.ipage.com/bot/api/messages, and generate microsoft id and password. i also update the web.config using my new generate id and password. when i test in webchat. the message couldnt send. please help.
