### ISSUE TITLE
[NodeJS] Message formatting fails if automatic translation is used

### ISSUE THREAD

**Issue by FedericoElles** [Microsoft/BotBuilder#109]
If I talk to my bot in English, the answers are formatted correctly.
If I switch to German language ("let speak german"), the bot does still understand me (awesome!), but the answers are not formatted at all.

**Screenhot:**
![bot_switch_lang_formatting](https://cloud.githubusercontent.com/assets/1033020/14528258/eb63fcd0-024e-11e6-878b-188a29ac94fb.png)

**Tech**
- Bot answers always in German
- LUIS app model trained in English since no German available yet
- AppID: cassiebot

**Comment by tomlm** [comment]
Looking at the object you are returning you are saying that your language is "en" but you are returning german, which means we are running it through the translator and I think that's messing up the markup.
When you return your text field, set the language to 'de' so we see that we don't need to translate it.

 "sourceText": "**Hier sind die fünf neusten Artikel:**\n\n1. Börse New York: Schluss mit der Partylaune - [Artikel öffnen](http://www.wiwo.de/boerse-new-york-schluss-mit-der-partylaune/13451788.html?share=bot) *(vor einer Stunde)*\n\n\n\n2. US-Notenbank: Fed macht Milliarden mit Staatsanleihen - [Artikel öffnen](http://www.wiwo.de/us-notenbank-fed-macht-milliarden-mit-staatsanleihen/13451746.html?share=bot) *(vor 2 Stunden)*\n\n\n\n3. Musterdepots: Den Weißkopfseeadler im Blick - [Artikel öffnen](http://www.wiwo.de/musterdepots-den-weisskopfseeadler-im-blick/13451696.html?share=bot) *(vor 3 Stunden)*\n\n\n\n4. Der Werber Rat: Der Tod lauert in der Dusche - [Artikel öffnen](http://www.wiwo.de/der-werber-rat-der-tod-lauert-in-der-dusche/13451606.html?share=bot) *(vor 3 Stunden)*\n\n\n\n5. Kapitalmarktgeschäfte: Was die Investmentbanker von Trump halten - [Artikel öffnen](http://www.wiwo.de/kapitalmarktgeschaefte-was-die-investmentbanker-von-trump-halten/13451552.html?share=bot) *(vor 4 Stunden)*\n\n\n\n",
    "sourceLanguage": "en",
    "language": "de",
    "text": "** Hier Sind Die Fünf Neusten Artikel: **\n\n1. Börse New York: Schluss Mit der Partylaune - [Artikel Öffnen] (http://www.wiwo.de/boerse-new-york-schluss-mit-der-partylaune/13451788.html?share=bot) *(vor einer Stunde) *\n\n\n\n2. US-Notenbank: Fed Macht Records Mit Staatsanleihen - [Artikel Öffnen] (http://www.wiwo.de/us-notenbank-fed-macht-milliarden-mit-staatsanleihen/13451746.html?share=bot) *(vor 2 Stunden) *\n\n\n\n3. Musterdepots: Den Weißkopfseeadler Im Blick - [Artikel Öffnen] (http://www.wiwo.de/musterdepots-den-weisskopfseeadler-im-blick/13451696.html?share=bot) *(vor 3 Stunden) *\n\n\n\n4. der Werber Ratte: Der Tod Lauert in der Dusche - [Artikel Öffnen] (http://www.wiwo.de/der-werber-rat-der-tod-lauert-in-der-dusche/13451606.html?share=bot) *(vor 3 Stunden) *\n\n\n\n5. Kapitalmarktgeschäfte: Wurde die Investmentbanker von Trump Halten - [Artikel Öffnen] (http://www.wiwo.de/kapitalmarktgeschaefte-was-die-investmentbanker-von-trump-halten/13451552.html?share=bot) *(vor 4 Stunden) *\n\n\n\n",

**Comment by falvhb** [comment]
Solved!

I use now:

      session.send({
          "language": session.message.sourceLanguage || session.message.language,
          "text": text
      });

which prevents any translation.
Thanks a lot!

**Comment by Stevenic** [comment]
You can also use the new Message class in 0.8 to build up your message as it has a setLanguage() method.
