### ISSUE TITLE
Carousel is not working in Facebook - BOT - Nodejs - Reg.

### ISSUE THREAD

**Issue by giriganapathy** [Microsoft/BotBuilder#1090]
![32fbcf56571baedc](https://cloud.githubusercontent.com/assets/18748896/18008986/fdb127d6-6bc7-11e6-8d2d-c674eeec155f.gif)

Hello Steve,

The carousel is not working in Facebook, and I am getting the below error:
Facebook graph API call failed with: BadRequest {"error":{"message":"(#194) param message[quick_replies] has too few elements.","type":"OAuthException","code":194,"fbtrace_id":"COhgOFiKq6h"}}

Could you please help here to resolve it .

My bot id: VZEntBot (Node js) version.

Regards,
Giri G.

**Comment by VishalWaman** [comment]
Just a shot as per my experience on node bot card...
Just check length on title , subtitle valid url  in images and tab...Make sure they are not longer then guidelines provided by Facebook. Try by test data...

**Comment by giriganapathy** [comment]
I have a proper title length and images...Still it is not coming up.

Steve, Could you please review my code and let me know....I have to present to my next level about this carousel piece.

Appreciate your help here.

Regards,
Giri G.

**Comment by JpEncausse** [comment]
One issue I get into is that HeroCards MUST all have the same size (aka components) on Facebook. For instance you can't have a card with a button and an other without in the carousel

**Comment by muzahmed** [comment]
@giriganapathy would you be willing to share the carouselArr?
I can try to repro with your specific code/values

**Comment by Stevenic** [comment]
@giriganapathy sorry for the delay. did you get this figured out?
