### ISSUE TITLE
How can we integrate a payment gateway which opens in a browser

### ISSUE THREAD

**Issue by satyajit-behera** [Microsoft/BotBuilder#1092]
Does bot allow to open a link in a browser from within the bot?

If yes, then, can we notify to the user using bot about the confirmation using some technology such as Signal R or some other method from the server side.

Thanks

**Comment by Thegaram** [comment]
Well, you can always send a link to the user and ask her to open it. I doubt that for example Facebook allows bots to navigate to a different page.

**Comment by jameslew** [comment]
Most channels do allow your bot to pass a http link to the user (or https in some cases) via the activity object and that would be a reasonable approach.  Even Facebook allows you to link out (in a card for example).

As far as your payment processor, I'd assume they had some way you could monitor for payments that happened and then you could act based on that.

**Comment by satyajit-behera** [comment]
Thanks. Suppose, I open a browser and do the processing and send the response to the BOT server from there with the user name. How can I push the response back to the user back from the server without the user calling any POST method in the server?
