### ISSUE TITLE
No documentation or examples of the usage of IntentDialog in C#

### ISSUE THREAD

**Issue by v-tbert** [Microsoft/BotBuilder#1094]
Documentation indicates LuisDialog is deprecated:

https://docs.botframework.com/en-us/node/builder/chat-reference/classes/_botbuilder_d_.luisdialog
https://docs.botframework.com/en-us/node/builder/chat/IntentDialog/

However, it doesn't appear that there are any examples of its use with C#, or anything indicating that it is a node only class.

**Comment by Andrea-Orimoto** [comment]
C# is still using the LuisDiaolg, example here https://docs.botframework.com/en-us/csharp/builder/sdkreference/dialogs.html#alarmBot. We're working on IntentDialog for C#, stay tuned. Feel free to reopen the issue if you still have questions. Thanks.
