### ISSUE TITLE
Refresh access token failed with status code: 401

### ISSUE THREAD

**Issue by kams451** [Microsoft/BotBuilder#1095]
Running on local server via Pagekit tunnel.

**Codes running:**
`bot.dialog('/', function (session) {
    session.send("Hello World");
});`

**In response to any DM to bot,throws out following error:**
`Error: Refresh access token failed with status code: 401
    at Request._callback (/Users/test/skype/node_modules/botbuilder/lib/bots/ChatConnector.js:447:28)
    at Request.self.callback (/Users/test/skype/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/test/skype/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/test/skype/node_modules/request/request.js:965:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)`

**However when i switch the code to following, No error occurred, response is as expected.:**
`bot.on('contactRelationUpdate', function (message) {
    console.log(message);
});`

-  botbuilder: 3.2.3
-  restify: 4.1.1
-  npm: 3.10.3
-  node: 6.3.1

**Comment by satb** [comment]
Mine turned out to be an issue with not setting the right app id/secret.

**Comment by muzahmed** [comment]
@kams451  are you still experiencing the 401?

**Comment by tobybrad** [comment]
Getting this right now. Tried regenerating secrets. No luck.

**Comment by muzahmed** [comment]
@tobybrad can you paste your code where you create the connector? (don't paste the secret if  you have it in there)

**Comment by tobybrad** [comment]
```
function createChatConnector() {

  let opts = {
    appId: config.get('MICROSOFT_APP_ID'),
    appPassword: config.get('MICROSOFT_APP_PASSWORD')
  };

  let chatConnector = new botbuilder.ChatConnector(opts);

  let server = restify.createServer();
  server.listen(process.env.port || process.env.PORT || 3978, function () {
    console.log('%s listening to %s', server.name, server.url);
  });

  server.post('/qna', chatConnector.listen());

  return chatConnector;
}
```

**Comment by tobybrad** [comment]
Ok.. this is solved for me now. I was seeing this issue using the webchat control. The issue was that I was mixing up the application password and the secret you need to provide in the iframe control. I was reusing a previous Bot config and had forgotten their even was a password as well as the secret.

A note on the secret generating page to remind this is not the same as the password would he helpful. Once you've generated the initial password there's no clue anywhere on the config page that it ever existed to remind you of the fact.

**Comment by muzahmed** [comment]
@tobybrad glad to hear you got it working -- good tip!
