### ISSUE TITLE
Send message with multiple line breaks

### ISSUE THREAD

**Issue by kenyeung128** [Microsoft/BotBuilder#1096]
Hi, I am trying to send message with 2 line breaks in between sentence, but it will just trim to 1 line break (in facebook messenger), is there anyway to workaround that?

I tried to add "\n\n \n\n", but it still just give 1 line break.

Thanks.

**Comment by HKOLWD** [comment]
Same "problem" with skype output. No way to paragraph a message

**Comment by somprabhsharma** [comment]
Any update on this ?

**Comment by dandriscoll** [comment]
Hi folks, markdown collapses newlines. You can find more detail here: http://daringfireball.net/projects/markdown/syntax#p

Some channels support the `<br/>` element, which can be used to insert a linebreak. This works in Skype and I don't have an example handy in Facebook but you could try it there.

**Comment by jameslew** [comment]
I'm assuming your question has been answered.  If not, please create a new issue.  Thanks!
