### ISSUE TITLE
Attachments property is null in webchat

### ISSUE THREAD

**Issue by TechWatching** [Microsoft/BotBuilder#1099]
Attachments property of IMessageActivity is null while I tried to access it in a web chat. Is this a normal behaviour ? Shouldn't be just a an empty List ? That's the case on the emulator.

**Comment by willportnoy** [comment]
Consistency would be best, of course.  I assume for now you can work around it, but I'll file this as a bug in our internal backlog.

**Comment by dandriscoll** [comment]
Hi @TechWatching, we're going to patch up the emulator in the future so it drops the empty arrays. Typically code that processes JSON should allow emptys to be missing, null, or empty.

**Comment by dandriscoll** [comment]
Closing this issue as this is just a cleanup task on our end. All of our channels and the emulator are sending acceptable values, and bots should expect to see missing, null, or empty arrays.
