### ISSUE TITLE
Question: Starting a conversation with a bot not in English language

### ISSUE THREAD

**Issue by FedericoElles** [Microsoft/BotBuilder#110]
I did setup a VM with language settings set to German and open a bot via webchat.

1. Why is the initial message ("Hi! I'm .... like to chat") from the bot not in German language?
2. If I start a conversation in German language, this is somehow not recognized. I would expect the bing translator to kick in before sending the questions to LUIS for example.
3. Can I help the framework by defining translation hints somewhere?

**Example**
![bot_detect_language](https://cloud.githubusercontent.com/assets/1033020/14530503/91f928f4-0259-11e6-8ae9-9a874b2bdb00.png)

**Comment by tomlm** [comment]
#1 is a bug we will fix.
for #2 if we know nothing about you we start a conversation in English.  If you have had enough conversations in another language, that becomes the default language for a NEW conversation.

**Comment by FedericoElles** [comment]
Thanks for clarifiying. I understand that the BotFramework does not know initially anything about the user. 
In my business case, the bot is only designed for the German market. Can I somehow change the initial language from English to German?
Otherwise I do not see a chance to onboard our users.

Maybe the different channels (web, telegram, skype) can later provide some hints regarding the user language like `navigator.language || navigator.userLanguage` for the web.

**Comment by tomlm** [comment]
You raise a great point, and I have made the following change:
* When a new conversation is started where we don't know anything about the users language we default the conversation to the language of the bot.

In your case, that means new users will default to "de", and then if they ask to change it to something else they can.

"old" users will default to whatever language we have observed them use the most.

**Comment by FedericoElles** [comment]
Thanks you very much for the quick fix. I'm afraid I ran into another issue after setting my bot to "de" language:

I'm using LUIS in the backend which does only support English, French, Spanish, Italien und Chinese. No German for now. No problem I thought:

- I turned on the automatic Bing Translations in the BotFramework.
- I trained LUIS in English language since the Bing translation from German to English is quite good

You guess it: After setting the bot to "de", Bing translations were turned of and all questions are forwarded to LUIS in German which it does not understand.

Adding an optional "User default language" setting in the bot details, which overrides the bot language for the initial conversation, would solve this issue, too. This could enable all developers to use LUIS even their target audience language is not supported yet and without the need for an additional external translation service.

**Future thoughts:**
I thought what would happen if my bot will someday support multiple languages: For the bot replies, I would not rely on automatic translations, but define those myself in any supported language.
How can I make sure the users of my english website can start speaking in English and another user on the german website can start the conversation in German?

**Comment by klausualk** [comment]
Hi!

Is there a difference in LUIS processing logic if you have the bot network in EN and just train relevant  DE language utterance strings,  compared to having the bot network in DE and doing all training in DE language utterances?

In other words, does (and if yes then how) LUIS consider language rules if it is fed EN, ES, or some less used, for example ET language samples?

**Comment by thermous** [comment]
With yesterdays release this should be fixed.
1. We added a Default language for new conversations for a bot 
2. We fixed bugs in the handling of language
