### ISSUE TITLE
Push notification for (Luis) Dialog

### ISSUE THREAD

**Issue by satyajit-behera** [Microsoft/BotBuilder#1101]
Is it possible to do a push notification for a Lius dialog which is dependent on processing of a third party process and the application waits for the process to complete. And send the confirmation to the user after the process is complete.

Can it happen in Async fashion too?

Can we use Signal R to push any notification to the bot user?

**Comment by ankitbko** [comment]
I don't know if I understood your question correctly. If you want to send a message to the user post completion of a long running process, you can do it. If your long running process returns a `Task`, the straightforward approach would be to create a continuation to the task and pass in the `IDialogContext` to it. In the continuation you could use the context to create a reply message and send it to the user.

You won't need to use SignalR anywhere to communicate with the user simply because there is no direct socket connection established between channel and the bot. Using bot framework, we rely on Bot Connector to reliably deliver our message to the user. Are you planning to use SignalR in some other way?

**Comment by satyajit-behera** [comment]
Thanks.
I am planning to communicate to the user for a long running process which is not started by the POST request starting the dialog. It is an external process and should be able to communicate to the user from a separate process. Signal R: Not sure will use the exact same thing. But felt if it is needed in this case?

**Comment by ankitbko** [comment]
To send a message to the user, all you need to do is send a POST request to the Bot Connector Service URL with correct `Conversation`, `From` and `Recipient` fields in request body. You can read more about how to do it [here](https://docs.botframework.com/en-us/csharp/builder/sdkreference/routing.html).
So as long as your separate process can formulate and send the POST request, you can send message to the user.

In bot framework, all communications happen over HTTP(S). Therefore you don't need to use SignalR as there is no direct socket connection established.

**Comment by satyajit-behera** [comment]
Thanks. No issues in sending a POST. I am trying if I can notify user without a POST request. He would have started the conversation dialog with his first POST request. Then, can I get the user Id and send him a notification without POST when some background process is completed.

**Comment by ankitbko** [comment]
There are actually two request being sent for a single to-fro communication. The user sends message to the bot in first POST request. The bot replies to user by creating _another_ POST request to bot connector. The reply is not returned _inline_ to the first request. It is something like this.
```
User sends message: User ----> Bot Connector --[POST]--> Our Bot
Bot replies to user:  Our Bot --[different POST]--> Bot Connector ----> User
```

The bot reply is sent as a separate request to the connector. In your case it would look something like this

```
User sends message: User ----> Bot Connector --[POST]--> Our Bot
... some background task happens...
... keeps on happening for a day...
...next day...
Bot replies: Bot/Another Process --[POST]--> Bot Connector ----> User
```
The only thing you need to get is the Conversation, From and Recipient fields from the first request that User sent to your bot. Using those data, you can send (by swapping From and Recipient) you can send message to user anytime.

Is there any reason you don't want to send a POST request to send reply?

**Comment by satyajit-behera** [comment]
Thanks. Will try this.

**Comment by willportnoy** [comment]
We also have a sample for one possible way to handle proactive bots that respond to external events:

https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Samples/AlarmBot/Models/ExternalEvent.cs#L29

**Comment by satyajit-behera** [comment]
@ankitbko hi, I tied it using the method described in your remarks, but the bot emulator does not receive any responses.

**Comment by satyajit-behera** [comment]
@willportnoy hi, can you explain a little more on this, how to accomplish this. How to identify the user and push the message to the user from the server. Thanks.

**Comment by willportnoy** [comment]
@satyajit-behera you can save the information in the ResumptionCookie - it's the addressing information necessary to contact the user "later".

**Comment by satyajit-behera** [comment]
@willportnoy Thanks a lot. Will try this.

**Comment by satyajit-behera** [comment]
@willportnoy it worked 👍 Thanks a lot.

```
ResumptionCookie cookie = new ResumptionCookie(activity);
await Conversation.ResumeAsync(cookie,activity);
```

**Comment by willportnoy** [comment]
Great to hear - thank you for the follow up.

I'm going to close this issue - free to open a new issue for further discussions.
