### ISSUE TITLE
markdown doesn't allow IM hyperlink in webchat

### ISSUE THREAD

**Issue by Sams4u** [Microsoft/BotBuilder#1103]
The hyperlink i am using has following syntax:-
await context.PostAsync("Please click on [HelpDesk](sip:user@domain.com)");
But webchat is rendering it as <p>Please click on <a>HelpDesk</a></p>
At the same time emulator is picking it up correctly.
I had raised a similar issue few days back, but closed by giving a link for markdown syntax. It seems like a bug. I have tried the same in different markdown online editors some produce expected HTML but others not. Attached the screenshot of an online markdown editor with similar behavior.
![image](https://cloud.githubusercontent.com/assets/20707001/18042366/746e7e7e-6dde-11e6-8571-a4d6f919b840.png)

**Comment by willportnoy** [comment]
Does it only occur when the uri scheme is "sip" rather than "http"?  I wonder if there is some url validation involved.

**Comment by Sams4u** [comment]
yes i think. It works fine with **mailto** [mailto:user@domain.com] as well. As of now problem is with sip and as you said some validation in the webchat window is preventing anchor tag to render properly.

**Comment by danmarshall** [comment]
This is being filtered out by Angular's [aHrefSanitizationWhitelist](https://docs.angularjs.org/api/ng/provider/$compileProvider) - we will look at the sip protocol to see if there are any security risks involved with enabling this. If so, this might need to be a user-configurable option in a future version of the webchat control.

**Comment by danmarshall** [comment]
For future reference - it may be as easy as adding 
```
      $compileProvider.aHrefSanitizationWhitelist(/^\s*(https?|ftp|mailto|tel|file|sip):/);
```
in the config of app.js

**Comment by chrimc62** [comment]
@danmarshall can you please comment further or close?

**Comment by danmarshall** [comment]
@Sams4u we have a new open-source version of our webchat control, which should enable this behavior. If you go to your bot's Channel config page for webchat, you can create a new site definition for a webchat and click the "webChat Preview" checkbox to get the new version.

**Comment by dandriscoll** [comment]
Closing as this has been fixed.
