### ISSUE TITLE
Add Google/Bing search API in Bot

### ISSUE THREAD

**Issue by afficionaddo** [Microsoft/BotBuilder#1108]
Hi,
This is more of a clarifying question.

I want to integrate Google/Bing custom search in my BOT.
So what's the way "to interpret the data" as I want to show them as CARDS to the end-user?

any suggestions?

**Comment by msft-shahins** [comment]
You can write a dialog that makes the Google/Bing API call based on incoming message and after you get the result from search API, you can map them to cards an send them in the reply. For example, you can map the top 5 results returned by the search API into a carousal with each card representing one entry in the search result.

**Comment by puneetsngh** [comment]
@afficionaddo I too used bing search api for my multipurpose bot developed in Python.

That's pretty impressive & I believe there cognitive Api's are the only thing properly documented. But 1000 queries are pretty less.
