### ISSUE TITLE
Error when sending multiple replies through async Lambda expression

### ISSUE THREAD

**Issue by afficionaddo** [Microsoft/BotBuilder#1109]
Hi,

I am trying to send multiple replies to the user though an "async lambda expression" as follows:

```
ConnectorClient connector = new ConnectorClient(new Uri(activity.ServiceUrl));
                // return our reply to the user
                List<Activity> reply = await ReplyToUserMessage(activity);
                reply.ForEach(async (rply) =>
               {
                   await connector.Conversations.ReplyToActivityAsync(rply);
               });

```

**But this gives me an error in Emulator::** 
_"An asynchronous module or handler completed while an asynchronous operation was still pending."_

Any suggestions on what am I doing wrong here?

**Comment by willportnoy** [comment]
Yes, this is a combination of ASP.NET and the task parallel library.

In your Foreach closure, you are initiating asynchronous tasks, but the calling code in List<T>.ForEach is not waiting for their completion.

ASP.NET will detect whether you still have asynchronous tasks running after the http request completes, and will throw that exception.

If you want to send a series of messages, you might consider:

await Task.WhenAll(reply.Select(r => connector.Conversations.ReplyToActivityAsync(r)))

though of course, there's no guarantee of delivery order expected in either case.

**Comment by willportnoy** [comment]
I'm going to close this issue, but feel free to open a new issue for further discussions.
