### ISSUE TITLE
Make "Message Text" bold

### ISSUE THREAD

**Issue by afficionaddo** [Microsoft/BotBuilder#1110]
Hi,

I am sending messages to FB messenger. I am stuck as to how to implement formatting of text like Bold, Italic etc

Any suggestions?

**Comment by reyesrico** [comment]
Facebook Generic Template only supports to send plain text messages. 
(https://developers.facebook.com/docs/messenger-platform/send-api-reference/text-message)

I suggest to:
1.  Use a HeroCard - title  that will be formatted in Bold. 
2.  Use emojis before the text to make some difference between the plain text.

**Comment by reyesrico** [comment]
If you still have more comments, please reopen the issue. Thank you.

**Comment by Bohdan-Sydor** [comment]
Does this work for anybody right now? For me messages are displayed w/o formatting in Messenger, but * are removed

**Comment by akshithreddy502** [comment]
'* ' is making the word itallic.Is there a way to make the word 'BOLD'

**Comment by akshithreddy502** [comment]
'**' will make the word BOLD
'*'  will make the word ITALLIC
'***'  will make the word both 'Bold' and 'Itallic'
