### ISSUE TITLE
Implement "pagination type" thing for long text

### ISSUE THREAD

**Issue by afficionaddo** [Microsoft/BotBuilder#1111]
Hi, 
Any suggestion on how to show long-text in pagination style in the chat interface::

xxxxxxxxxxxxxx
xxxxxxxxxxxxxx
xxxxxxxxxxxxxx
     Show More

xxxxxxxxxxxxxx
xxxxxxxxxxxxxx
xxxxxxxxxxxxxx
     Show More

**Comment by msft-shahins** [comment]
You can send a card that has your text and a `show more` button and then implement the logic that when `show more` is pressed, you send rest of the text in another card.

**Comment by afficionaddo** [comment]
Thanks for your reply @msft-shahins !

Do you recommend storing large text in IBotState as a property?

**Comment by msft-shahins** [comment]
@afficionaddo  the maximum size of data that you can store in each data store is limited to [32kb](https://docs.botframework.com/en-us/technical-faq/#is-there-a-limit-on-the-amount-of-data-i-can-store-using-the-state-api). I recommend keeping the text in your own data store and keep a continuation token that can be used to calculate the next page in the IBotState.
