### ISSUE TITLE
How to insert Blank Lines?

### ISSUE THREAD

**Issue by acparas** [Microsoft/BotBuilder#1112]
How do I add blank lines in messages?

e.g.

<img width="167" alt="blankno" src="https://cloud.githubusercontent.com/assets/7927517/18057800/5408a226-6dc6-11e6-8de4-c097241c79ba.png">
<img width="143" alt="blankyes" src="https://cloud.githubusercontent.com/assets/7927517/18057802/55195700-6dc6-11e6-84da-990bba73139d.png">

**Comment by liiver** [comment]
actually my question would be how to add a line break in skype chats. I have not been able to do that
Adding \n to the line end gives me no line break
Adding \n\n to the end of line, gives be a blank line like in here example 2.
I would need to get smth like in here example 1, with just a simple line break. I am using "markdown" style in messages (I need to, since I need to parse hyperlinks)

**Comment by acparas** [comment]
@liiver 

"\n\n" gives you example 2? That's odd. 
"\n\n" gives me example 1.

For instance, doing

<code>session.send("Hello\n\nWorld!");</code>

gives me

"Hello
World"

**Comment by liiver** [comment]
i'm using C#, if that makes any difference but this is indeed the case for me

**Comment by acparas** [comment]
I'm using node. That makes sense. It could be a difference in the language implementations

**Comment by ankitbko** [comment]
End your sentence with two white-space and one \n. That would give you line break. For example

```CSharp
string response = "this is one line  \n"; // Notice two white space before \n
response += "next line"
```

**Comment by gplumb** [comment]
The break tag <br/> will also work.

**Comment by Sams4u** [comment]
2 space and \n should work.
"  \n next line"

**Comment by acparas** [comment]
@gplumb 

I can confirm that using <code>&lt;br/&gt;&lt;br/&gt;</code> produces a full, blank line (not just a line break).

However, <code>&lt;br&gt;</code> __fails__. It even spawned multiple runtime errors in my program.

So, to anyone reading this, __you must include the "/" in &lt;br/&gt;__.
<br>

Tested on:
  - Node.js
  - Skype

**Comment by acparas** [comment]
The above solution only works for __Skype__.

Therefore, I am re-opening this issue for the other platforms.
I confirm that it doesn't work for <iframe> and SMS via Twilio.

**Comment by msft-shahins** [comment]
similar to issue #920 and [this](https://github.com/Microsoft/BotBuilder/issues/920#issuecomment-243938371) should have the answer. 

Also markup, e.g. `<br/>`, is only supported by Skype channel: https://github.com/Microsoft/BotBuilder/blob/c4dbb7183cc1c23837b6d6c8bc03fe8c54ba1f55/CSharp/Library/Microsoft.Bot.Connector/TextFormatTypes.cs#L22

**Comment by Rohit573** [comment]
I am using REST APIs in python. For me "  \n  \n" <2 spaces followed by \n followed by another 2 spaces and a \n> generates a response in next line
"HELLO  \n  \nWorld" generates the following in SfB (not sure if its the same for Skype) 
HELLO
WORLD

**Comment by ganesh1190** [comment]
@Rohit573  two white-space and one \n worked for SKype for business.
Do you know how do we send Bold, Italic text to Skype for business . As it does nor support markdown and html.

**Comment by Rohit573** [comment]
@ganesh1190 SfB is absolutely cold hearted. It converts every thing to plain text. No BOLD, ITALICS, etc. (worked on this 1.5 months ago)
