### ISSUE TITLE
Group chat in Skype

### ISSUE THREAD

**Issue by s-rya** [Microsoft/BotBuilder#1113]
I tried adding my bot to a group. After adding the bot, my bot starts creating different session for each user. Is there any means by which a single session can be maintained as in 1:1 chat ?

**Comment by willportnoy** [comment]
Which language SDK are you using?  You have user, group, private bot data bags that you can share across multiple users.  The state of the dialog stack is stored in the private conversation data bags in C#, though:

https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Dialogs/DialogModule.cs#L155

**Comment by s-rya** [comment]
@willportnoy I am using NodeJs SDK.

**Comment by willportnoy** [comment]
@Stevenic @muzahmed how can you change which bag stores the conversation state?

@s-rya you still may want to have the dialog stack stored per user - otherwise, it can get very confusing for multiple users to interact with the same bot.

**Comment by s-rya** [comment]
@willportnoy  yeah..... Its very confusing.

For example, My bot orders a pizza, so X and Y want to order pizza using my bot in group chat.
Sceanario :
X : @bot Hi
bot : Hi I am pizza bot. What type of pizza do you want to order. 1 - Veg 2 - Non Veg
Y : @bot Veg
bot : Hi I am pizza bot. What type of pizza do you want to order. 1 - Veg 2 - Non Veg

So in this case if Y says Veg, i want it to continue and ask the next question but my bot treats Y as a new user and starts a separate conversation for him.
Can you help me on this?

**Comment by deztin** [comment]
"@Stevenic @muzahmed how can you change which bag stores the conversation state?"

I'm also interested in having dialogs work in Skype group chats via Node.js. Can you provide some sample code?

**Comment by Stevenic** [comment]
Yes... We'll need to talk about this internally some. The SDK's don't currently support tracking the conversations state at the group level. It's always at the individual level. We'll need to get back to you on a potential solution.

**Comment by euanlau** [comment]
Any update on this?

**Comment by Stevenic** [comment]
Not yet... On the Node side of things I can think about how we'd support this in our 3.6 release. It's too late to do anything in v3.5

**Comment by chrimc62** [comment]
Adding other SDK people to make sure this is considered.  I also filed a new feature request in our backlog to make sure we consider it in planning.

**Comment by Stevenic** [comment]
We have a basic plan for how to support this in 3.6
