### ISSUE TITLE
botframework webchat control has queuing issue

### ISSUE THREAD

**Issue by ubreddy** [Microsoft/BotBuilder#1116]
what is expected ?
user input1, response1, input2, response2, input3,response3

what I get
user input1, no response, input2, response1, input3,response2...

Is there a way to get the code of the web chat control? I tried getting it but I get a securityexception as domain name is different.

**Comment by ubreddy** [comment]
Anyone from microsoft who can correct this ? 

pollmessages function in chatlib there is a for loop which has ++i.   should be i++. can you please change it and commit the code?  line no: 199 in chat.js

**Comment by danmarshall** [comment]
Thanks @ubreddy for the debug! I will take a look, test this, and get back to you.

**Comment by danmarshall** [comment]
@ubreddy I looked but unfortunately this is not a solution.

```
var a = [0,1,2,3,4,5,6,7]
for (i = 0; i < a.length; i++) {console.log(i, a[i]);}
for (i = 0; i < a.length; ++i) {console.log(i, a[i]);}
```
In both of these cases, ```i``` is already incremented by the time it is used.

I believe that the real issue is in the network responses. I am looking into this, several others have reported this as well.

**Comment by danmarshall** [comment]
original issue: https://github.com/Microsoft/BotBuilder/issues/957
