### ISSUE TITLE
session.userData and session.send

### ISSUE THREAD

**Issue by vinnitu** [Microsoft/BotBuilder#1118]
I set data (more > 65K) in session.userData before sending message to user,
but session.send seems doesn't work without any error messages...

I know why but how to handle this situation?

**Comment by ubreddy** [comment]
max allowed is 32K as per the documentation

**Comment by vinnitu** [comment]
ok, but how to hanlde this error?

**Comment by willportnoy** [comment]
I believe in the Node version you can observe any errors in sending messages by calling "send batch".  But in general, you should send less data.

**Comment by vinnitu** [comment]
session.userData = [big data];
session.send("here message");
session.sendBatch(function(error) {
    // am I right?
})

**Comment by willportnoy** [comment]
@vinnitu it looks right, but I'll leave it to @Stevenic to confirm.

**Comment by Stevenic** [comment]
@vinnitu that's correct... You can also enable [gzip compression](https://docs.botframework.com/en-us/node/builder/chat-reference/interfaces/_botbuilder_d_.ichatconnectorsettings.html#gzipdata) for your `ChatConnector` but in general we recommend treating the data bags (especially userData) more like cookie storage.  It's not a replacement for all storage.

**Comment by slidenerd** [comment]
You are right @Stevenic because with gzipData: true I see the UX lag on messenger. its almost as if there is some decompression going on for each message
