### ISSUE TITLE
How do I build the option list dynamically?

### ISSUE THREAD

**Issue by jsucupira** [Microsoft/BotBuilder#112]
Hello,
I am following the sample code on the project "Microsoft.Bot.Sample.PizzaBot", everything works great, however I need to be able to build a option list dynamically.

This is my workflow.
1) User enters an address
2) I make a web request and get the list of stores available close to that location (could be more than one)
3) I ask the user to choose one of the returned stores.

I appreciate any help.

Thank you

**Comment by chrimc62** [comment]
You can derive from Field<T> and implement IFieldState<T>.  The next release (should be tomorrow) will make it so that should work.  The current release would also work, but you would need to explicitly set the recognizer as well.

**Comment by jsucupira** [comment]
Would you have same samples anywhere?

Thank you,
