### ISSUE TITLE
Webchat need css update

### ISSUE THREAD

**Issue by Sams4u** [Microsoft/BotBuilder#1121]
I am using a webchat for BOT. I feel there should be some changes to be done.
One is, after a few chats once the scroll bar comes into the chat window, afterwards when ever we type something it waits for the response to come before gets automatically scrolled down. This makes a feel that user hasn't typed anything even though text is there at the bottom. 
Second is a CSS fix to be applied. Because of the following css words breaks at the end of each line.
```
.message-panel {
    margin-top: 10px !important;
    margin-bottom: 0px;
    min-width: 0px !important;
    max-width: 80% !important;
    border: 0px !important;
    box-shadow: none;
    -webkit-box-shadow: none;
    -moz-box-shadow: none;
    -o-box-shadow: none;
    word-break: break-all;
}
```
If you can change the style **word-break: break-all;** it will be fixed i think.
Screenshot attached.
![image](https://cloud.githubusercontent.com/assets/20707001/18090831/2d35085a-6ee4-11e6-97e4-1d2777080ee0.png)

**Comment by Andrea-Orimoto** [comment]
Hi @Sams4u , thanks a lot for this feedback. I've added it to our backlog and assigned to the proper developer. Thank you!
