### ISSUE TITLE
Error in IDialog.Wait<R>

### ISSUE THREAD

**Issue by afficionaddo** [Microsoft/BotBuilder#1122]
Hi,
 please see the below code:
`private async Task MessageReceivedAsync(IDialogContext context, IAwaitable<IMessageActivity> result)
        {
            var message = await result;

            if (message.Text.ToLower() == "hi")
            {
                context.Wait(AfterHiAsync);
            }
            else if (message.Text.ToLower() == "reset")
            {                
                context.Wait(AfterResetAsync(context,result));
            }            
        }`

I get an error in the line:                  **context.Wait(AfterResetAsync(context,result));**

_The type arguments for method 'IDialogStack.Wait<R>(ResumeAfter<R>)' cannot be inferred from the usage. Try specifying the arguments explicitly._

Please help what am I doing wrong?

**Comment by willportnoy** [comment]
The second line should be something like this:

context.Wait(AfterResetAsync);

You should pass the Wait method a delegate representing the next method you want to execute after the user's message, not a result from calling that method.
