### ISSUE TITLE
DirectLine API in JavaScript

### ISSUE THREAD

**Issue by srozga** [Microsoft/BotBuilder#1124]
Was looking into writing a web page with a textview/textbox to talk to a bot. Seems that writing some JavaScript code to talk to the DirectLine API should be fairly easy. The only issue I can see is with regards to storing the secret in the client. Anyone will be able to get the key and then call into our bot through their third party app. Any recommendations around dealing with this?

**Comment by dandriscoll** [comment]
Hi @srozga, Direct Line has a token system you can use to exchange your secret for a token on a server, and then deliver the token to a client. The token is usable only for a single conversation and must be refreshed every 30 minutes to stay alive.

Directions are shown on this page for the Web Chat control. Web Chat uses the Direct Line protocol, so the behavior is the same. (See Step 2, Option 1.)

https://docs.botframework.com/en-us/support/embed-chat-control2/#navtitle

**Comment by srozga** [comment]
Thanks @dandriscoll , this is super helpful. Incidentally, the WebChat client seems to be down at the moment? See attached image.
![error](https://cloud.githubusercontent.com/assets/1940385/18106348/54387bb6-6ed1-11e6-93d2-5de8f1f6e667.PNG)

**Comment by dandriscoll** [comment]
Things seem to be working -- I'll check my logs. Can you send the URL you're using? Please remove the secret before sending it. I'm looking for the page you're accessing and the bot ID or site ID. You can post it here or send it to dandris@microsoft.com. Thanks

**Comment by srozga** [comment]
So this was my mistake. I missed copy-ing a few characters from the secret into the iframe uri. I suppose a better error message might be helpful, maybe a 403. I'll close this one, thanks guys!
