### ISSUE TITLE
List items end with &#13; in Kik whereas other channels fine

### ISSUE THREAD

**Issue by intranetchris** [Microsoft/BotBuilder#1125]
When I send a list (Markdown format) using bot framework, there is a `&#13;` at the end of each list item on the Kik channel. This shows only in Kik, but not in Skype, Messenger, SMS or Slack.

Using node.js 3.1 version of botbuilder.

# Kik screenshot:
![kik](https://cloud.githubusercontent.com/assets/19203848/18108363/e68b8096-6ed9-11e6-866a-ccbb984ebfa3.PNG)

# Slack screenshot:
![slack](https://cloud.githubusercontent.com/assets/19203848/18108364/e68f4e1a-6ed9-11e6-9817-84114f500823.PNG)

# Messenger screenshot:
![messenger](https://cloud.githubusercontent.com/assets/19203848/18108366/e6978c2e-6ed9-11e6-8ff3-009fb3b53132.PNG)

# SMS screenshot:
![sms](https://cloud.githubusercontent.com/assets/19203848/18108365/e691d842-6ed9-11e6-9350-bff2b5dfac14.PNG)

**Comment by LarsLiden** [comment]
Thanks for the head's up.  Bug has been fixed and will show up in our next push
