### ISSUE TITLE
Testing contactRelationUpdate with Emulator

### ISSUE THREAD

**Issue by JpEncausse** [Microsoft/BotBuilder#1126]
Hi,

I'd like to test Facebook "greeting". It seems we have to implement a listener on "contactRelationUpdate".

- On Facebook I don't find how to reset greeting step
- On the Emulator I don't know how to trigger it 

Any ideas ?

**Comment by msft-shahins** [comment]
you can send different activity types, e.g. contact relationship update - add, from emulator to your bot: 

![image](https://cloud.githubusercontent.com/assets/17562300/18109541/c4b51e68-6ec6-11e6-8d50-054d5c0bd1f3.png)

**Comment by slidenerd** [comment]
Do these events exist on Node.js for facebook, can you please tell me which source file has it, I searched Session.js and universalbot.js and couldnt find anything.
