### ISSUE TITLE
Sending multiple requests when the bot is running

### ISSUE THREAD

**Issue by irynabond** [Microsoft/BotBuilder#1128]
Hello,
My bot is using a Web Chat channel and hosted on azurewebsites.net. When I open the webpage and Fiddler I see that this webpage makes thousands requests. Here is a fiddler screenshot:
<img width="936" alt="botrequests" src="https://cloud.githubusercontent.com/assets/13076334/18112543/58d93bb8-6edd-11e6-9261-8faf7fd0cbc7.PNG">

Why is it happening? Is it possible to fix? Thank you!

**Comment by palmerabollo** [comment]
MS can confirm it, but your bot is polling for new messages.

In my opinion, it's a pity that directline –and apparently other channels– doesn't come with some kind of push mechanism. In some scenarios (ex. mobile app) it could be a blocking issue (ex. battery drain). I don't know if there is a recommended way to solve this issue.

**Comment by Thegaram** [comment]
@palmerabollo As you mentioned, this is true for clients using the Direct Line API, like Web Chat or mobile apps. Not true, however, for other channels, as they use the Bot Connector API which does not store messages. (Just clarifying your remark regarding *other channels*.)

**Comment by irynabond** [comment]
Thanks for replies! 
I don't use the Direct Line API . Now it's a simple url wrapped in <iframe> generated by web chat channel and embedded into html code. 
I'm going to develop my own UI and to use the Direct Line API. Is there a chance that it will solve this problem? This is CaptionBot developed by Microsoft https://www.captionbot.ai . When I open Fiddler there are no multiple requests from this page.

**Comment by msft-shahins** [comment]
Webchat  is using Direct line API which uses a polling mechanism to fetch messages from bot.

**Comment by irynabond** [comment]
Thank you, now I understand why it's happening.
