### ISSUE TITLE
Markdown bugs

### ISSUE THREAD

**Issue by wiltodelta** [Microsoft/BotBuilder#113]
I checked markdown parsing/transfromation in Slack, Telegram & Skype:

```
**Bold**

*Italic*

**_Bold and Italic_**

~~Strikethrough~~

# Header 1

## Header 2

### Header 3

---

[link](https://google.com)

![img](http://netdna.webdesignerdepot.com/uploads/2013/07/icons-animation.gif)

> Quote

`Code`

😀

😬😁😂😃😄😅😆😇

* Item 1
* Item 2

1. Item 1
2. Item 2
```
Skype (iOS):
![skype_ios_01](https://cloud.githubusercontent.com/assets/1192743/14552158/2f0127c0-02e4-11e6-814c-0f01ffd26105.png)
![skype_ios_02](https://cloud.githubusercontent.com/assets/1192743/14552159/2f0145f2-02e4-11e6-8471-f7093cc2da95.png)

Slack:
<img width="569" alt="slack_01" src="https://cloud.githubusercontent.com/assets/1192743/14552160/2f01bcbc-02e4-11e6-8e81-f3d332be140c.png">
<img width="182" alt="slack_02" src="https://cloud.githubusercontent.com/assets/1192743/14552161/2f02c62a-02e4-11e6-9647-adb89e6baba4.png">

Telegram:
<img width="438" alt="telegram" src="https://cloud.githubusercontent.com/assets/1192743/14552162/2f0324a8-02e4-11e6-9938-b0860bc81790.png">

**Comment by srisaiswaroop** [comment]
I have similar issue when i tried formatting my data. 
This is what it looks like in skype(its only visible after i restart my Skype, not before that, that another issue i have with long text). 

Here is my sample data: I am using builder.prompts.text(session,data). I have tried session.send as well, both have same issue with skype.
<b>1. </b> <b>data1</b> <i> (date1 time1)</i> -----&gt; <b>data2</b> <i> (date1 time2)</i>
<b>XYZ123 - </b> <i>PQRS 12</i>
<b>data2</b> <i> (date1 time3)</i> -----&gt; <b>data3</b> <i> (date1 time4)</i>
<b>XYZ123  - </b> <i>PQRS 123</i>
<b>1 LMN - PQRS 12</b>
<hr>
<b>2.</b> <b>data1</b> <i> (date1 time1)</i> -----&gt; <b>data2</b> <i> (date1 time2)</i>
<b>XYZ123 - </b> <i>PQRS 12</i>
<b>data2</b> <i> (date1 time3)</i> -----&gt; <b>data3</b> <i> (date1 time4)</i>
<b>XYZ123  - </b> <i>PQRS 123</i>
<b>1 LMN - PQRS 12</b>
<hr>
<b>3. </b> <b>data1</b> <i> (date1 time1)</i> -----&gt; <b>data2</b> <i> (date1 time2)</i>
<b>XYZ123 - </b> <i>PQRS 12</i>
<b>data2</b> <i> (date1 time3)</i> -----&gt; <b>data3</b> <i> (date1 time4)</i>
<b>XYZ123  - </b> <i>PQRS 123</i>
<b>1 LMN - PQRS 12</b>
<hr>
Please Select the options 1, 2 or 3 from above

It doesn't show me anything during the conversation, then when i select 1 or 2 or 3 it goes ahead with the conversation.

**Comment by tomlm** [comment]
Markdown support is mapped to the capibilities of the client.  It turns that skype clients are not consistent in their support,  but that is something the skype team will be addressing soon.
