### ISSUE TITLE
[C#] How to keep conversation in child dialog?

### ISSUE THREAD

**Issue by wswijaya** [Microsoft/BotBuilder#1130]
Hi,
I want to forward conversation from main dialog to a child dialog. I uses context.Forward() and the message successfully pass to child dialog. However I couldn't keep the conversation within the child dialog. How can i overcome this?

MainDialog
` 
        OverseasNotificationDialog dialog = new OverseasNotificationDialog(); 
await context.Forward(dialog, OverseasNotificationCompleted, message, CancellationToken.None);
` 

OverseasNotificationDialog
`
        public async Task StartAsync(IDialogContext context)
        {
            context.Wait(ONMessageReceivedAsync);
        }

        public async Task ONMessageReceivedAsync(IDialogContext context, IAwaitable<IMessageActivity> argument)
        {
            var message = await argument;
            ChatResponse chatResponse = new ChatResponse();

            if (message.Text.StartsWith("cancel"))
            {
                context.Done("I noted that you have decided to cancel your overseas notification. Thank you.");
                return;
            }
            bool isDone = false;
            // Prepare respond 
            if (isDone)
            {
                context.Done("Thank you. Have a nice trip!");
                return;
            }

            await context.PostAsync("some text");
            context.Wait(ONMessageReceivedAsync);
        }

`

**Comment by msft-shahins** [comment]
Here is an example of how you can achieve this. the MainDialog forwards the message to the ChildDialog and ChildDialog will receive the rest of messages till the users says cancel.

```csharp

    [Serializable]
    public class MainDialog : IDialog<object>
    {
        public async Task StartAsync(IDialogContext context)
        {
            context.Wait(MessageReceivedAsync);
        }

        public virtual async Task MessageReceivedAsync(IDialogContext context, IAwaitable<IMessageActivity> argument)
        {
            await context.Forward(new ChildDialog(), Resume, await argument, CancellationToken.None);
        }

        public async Task Resume(IDialogContext context, IAwaitable<string> argument)
        {
            await context.PostAsync(await argument);
            context.Wait(MessageReceivedAsync);
        }
    }

    [Serializable]
    public class ChildDialog : IDialog<string>
    {
        protected int count = 1;

        public async Task StartAsync(IDialogContext context)
        {
            context.Wait(MessageReceivedAsync);
        }

        public virtual async Task MessageReceivedAsync(IDialogContext context, IAwaitable<IMessageActivity> argument)
        {
            var message = await argument;
            if (message.Text.StartsWith("cancel"))
            {
                context.Done("I noted that you have decided to cancel the child dialog. Thank you.");
            }
            else
            {
                await context.PostAsync("some text");
                context.Wait(MessageReceivedAsync);
            }
        }
    }

```
