### ISSUE TITLE
Styling web chat control

### ISSUE THREAD

**Issue by srozga** [Microsoft/BotBuilder#1131]
Obviously, we can't apply CSS and use JS to modify the contents of an iframe with a different origin. The styling section on this page [https://docs.botframework.com/en-us/support/embed-chat-control2](url) is thin. 

Things like fonts, margins, colors, etc would be really good to be able to style. 

Any thoughts or idea on how custom styling of the control could be enabled?

**Comment by danmarshall** [comment]
Hi @srozga this is a popular request. We are coming up with a solution, please watch our blog for updates.

**Comment by srozga** [comment]
Thanks!

**Comment by kkarsah** [comment]
Any update on this thread ?

**Comment by EricDahlvang** [comment]
@kkarsah The webchat repository now has numerous samples demonstrating how to style the control when not using the iframed version: https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples
