### ISSUE TITLE
wrong result when debugging GetKey(BotDataKey key, BotStoreType botStoreType) in "..\BotBuilder\CSharp\Library\Dialogs\BotData.cs"

### ISSUE THREAD

**Issue by ranjan-ranjan** [Microsoft/BotBuilder#1132]
I was debugging the bot framework and found that `GetKey(BotDataKey key, BotStoreType botStoreType)` in  https://github.com/Microsoft/BotBuilder/blob/1958a3f946c2e8a540196b7d12fd15255932ce7c/CSharp/Library/Dialogs/BotData.cs doesn't debug properly.

The result is like this `conversation:testBot:Test:7c430ce2-da52-4098-8da3-f6c26e5172aa`

The `{key.BotId}` and `{key.ChannelId}` are not getting assigned to the result to be returned. Only `{key.ConversationId}` is being assigned.

**Comment by msft-shahins** [comment]
@ranjan-ranjan how do you generate the message? The result that you are mentioning above is the right key for the test message that we generate for out tests: https://github.com/Microsoft/BotBuilder/blob/1958a3f946c2e8a540196b7d12fd15255932ce7c/CSharp/Tests/Microsoft.Bot.Builder.Tests/DialogTestBase.cs#L129

 GetKey(...) is a helper for the [InMemoryDataStore](https://github.com/Microsoft/BotBuilder/blob/1958a3f946c2e8a540196b7d12fd15255932ce7c/CSharp/Library/Dialogs/BotData.cs#L97) implementation and all our test cases uses that implementation. The InMemoryDataStore implementation assumes that channelId exist (which is extracted from the message) and botId is resolved through [BotIdResolver](https://github.com/Microsoft/BotBuilder/blob/1958a3f946c2e8a540196b7d12fd15255932ce7c/CSharp/Library/Dialogs/DialogModule.cs#L97).

**Comment by ranjan-ranjan** [comment]
Yes I am debugging using test cases here is my output: 
![2](https://cloud.githubusercontent.com/assets/16834561/18158379/a22c881a-7040-11e6-86c6-62fc17762853.png)

**Comment by ranjan-ranjan** [comment]
Wrong results are being shown. The values are not being assigned as shown in Immediate Window.

**Comment by msft-shahins** [comment]
@ranjan-ranjan I cannot follow what you mean by wrong results being shown in the immediate window. For test cases, channel id is set to `test`: https://github.com/Microsoft/BotBuilder/blob/1958a3f946c2e8a540196b7d12fd15255932ce7c/CSharp/Tests/Microsoft.Bot.Builder.Tests/DialogTestBase.cs#L129

An BotIdResolver will set the botId to `TestBot`: https://github.com/Microsoft/BotBuilder/blob/1958a3f946c2e8a540196b7d12fd15255932ce7c/CSharp/Tests/Microsoft.Bot.Builder.Tests/DialogTestBase.cs#L70
