### ISSUE TITLE
Facebook: bug with begin/end dialog flow ?

### ISSUE THREAD

**Issue by JpEncausse** [Microsoft/BotBuilder#1134]
Hi,

It seems I have a bug only with Facebook (not with the emulator) with the followinf flow:

- session.send(Message 1)
- session.beginDialog A
- =>user write something X
- session.endDialog A
- session.beginDialog A
- session.send(Message 2)
- =>user write something Y

On Facebook the user Y text is scoped outside the dialogA. it's like if endDialogA is executed after the 2nd beginDialog A

Any ideas ? 
Is there a way to flush the order ? 

Thanks

**Comment by JpEncausse** [comment]
I had a clue because 
- I create a bessage
- I begin dialog
- I send the message

I thought it could messup the behavior of Facebook.

At last I write my own "prompt" without dialogs

**Comment by muzahmed** [comment]
@JpEncausse is it working as expected for you now?

**Comment by JpEncausse** [comment]
Well Instead of using Dialogs, I set a flag on a conversation and a callback function. It's not stateless but it works well.

Navigating throught dialogs is really hard for users, so we put all sentences under root dialog and use prompt to ask simple questions

**Comment by Stevenic** [comment]
Can you share a simplified version of your code and I can potentially provide a little feedback on structure

**Comment by JpEncausse** [comment]
My Workaround ? Very simple:

I store a callback for a given conversation, then later, on dialog / I call it back
```
let convId = inMsg.address.conversation.id;
PROMPT_CALLBACK[convId] = callback;
```

I know it's not stateless but my usecase is to make it work in Node-RED and it works very well :-)

**Comment by Stevenic** [comment]
ok... so long as you realize your going to have to make sure the same process gets called back that seems reasonable.
