### ISSUE TITLE
PostUnhandledExceptionToUserTask should use config value instead of Debugger.IsAttached

### ISSUE THREAD

**Issue by qswinson** [Microsoft/BotBuilder#1136]
It would be very helpful if the PostUnhandledExceptionToUserTask used a configurable flag to determine if the exception should be returned as the message to the user instead of the generic "Sorry, my bot code is having an issue." message. Getting quick access to the exception is very helpful for testing and a tester should not have to have an environment where they can attach a debugger to the chat bot.

**Comment by msft-shahins** [comment]
you can implement your custom [IPostToBot](https://github.com/Microsoft/BotBuilder/blob/1958a3f946c2e8a540196b7d12fd15255932ce7c/CSharp/Library/Dialogs/DialogTask.cs#L442) and register it in your custom container to implement your desired behavior. Here is how DialogModule register the default implementations: https://github.com/Microsoft/BotBuilder/blob/1958a3f946c2e8a540196b7d12fd15255932ce7c/CSharp/Library/Dialogs/DialogModule.cs#L171

**Comment by willportnoy** [comment]
You can also override it more easily through the container by specifying a ResourceManager that overrides that one message and delegates to a base implementation otherwise.

**Comment by qswinson** [comment]
For anyone who comes across this issue and finds the MS recommendations lacking, I've created a [gist with my ExceptionHandlerDialog here.](https://gist.github.com/qswinson/39a36e485df488b710f8a9ba224627af)

I use this as my top level dialog in my controller and pass a function into the constructor that builds the dialog chain with the actual business logic.

**Comment by willportnoy** [comment]
@qswinson that's a good suggestion - thank you for the code sample.

**Comment by willportnoy** [comment]
fyi, this commit https://github.com/Microsoft/BotBuilder/commit/31048a2173313c81a2db47efce6a8a869b4ec284 should help disable PostUnhandledExceptionToUser.
