### ISSUE TITLE
message sent from Skype does not show up in bot engine

### ISSUE THREAD

**Issue by euanlau** [Microsoft/BotBuilder#1137]
This started this morning. Messages sent from Skype no longer triggers the dialogs in the engine. I have the same bot running for Telegram and it works fine.

**Comment by safiresh** [comment]
Yes.. I got Same issue.. I cant receive any msg from skype  but  BOT to Skype working.

**Comment by safiresh** [comment]
Team. This issue resolved.. Now i Got from msg Skype to BoT. 
@euanlau  Kindly check  your  Bot too 👍

**Comment by msft-shahins** [comment]
Thanks for your report. We had a short degradation of service Wednesday morning that was causing this issue. Everything should be normal now. Please let us know if your bot is still not working.

**Comment by euanlau** [comment]
Yes. It is back to normal now. Thanks for checking!
