### ISSUE TITLE
Adding Facebook Channel Causes Bot to Show on botframework.com

### ISSUE THREAD

**Issue by oztheozoz** [Microsoft/BotBuilder#1138]
Tried adding FB channel to my bot. The credentials checked out fine but the bot was not added to the channel list. I tried refreshing and now there is a problem displaying the bot's page. See below. It looks like there is some problem with the connection between the botframework and FB. See images linked below.

![image](https://cloud.githubusercontent.com/assets/4121069/18148169/eb2cd5d8-6f8c-11e6-9bff-856c1db5c7f8.png)

![image](https://cloud.githubusercontent.com/assets/4121069/18148157/de72cb9a-6f8c-11e6-8162-a76027b58197.png)

The code errors on line 2141 of app.js?v=121 because a.href does not exist. This is probably the reason why the page won't load.
I looked at another bot of mine that already had the FB channel added and on line 2141, there is a whole slew of info related to FB.

**Comment by msft-shahins** [comment]
@oztheozoz can you check and see if the problem still exist? a fix pushed that should resolve this.

**Comment by oztheozoz** [comment]
Works now. I can see the bots. Thanks for the quick fix.
