### ISSUE TITLE
skybot attachment

### ISSUE THREAD

**Issue by MakePLAN** [Microsoft/BotBuilder#114]
Hi, 

I was testing the send attachment for testbot skype bot. I did not get the image in the text. I am not sure if the code is not working...

**Comment by Stevenic** [comment]
Sorry for the delay.  The node version of the SkypeBot SDK doesn't currently support sending images. I'm working with them to try and see if there's actually a way I can format the message for images my self. I'll keep you posted.

**Comment by anoopnair** [comment]
@MakePLAN: Did you use the C# version or the Node version? Were you able to get this working?

**Comment by Stevenic** [comment]
So if you use the Node version and go through the BotConnectorBot, images should work just fine. The limitations surround the native SkypeBot class.
