### ISSUE TITLE
Using BotBuilder with Hapi

### ISSUE THREAD

**Issue by somprabhsharma** [Microsoft/BotBuilder#1142]
BotBuilder does not work with Hapijs, Is there any way to get it work with Hapijs ?

**Comment by palmerabollo** [comment]
What do you mean? What error do you get? MS Bot Framework is not tied to any specific nodejs framework. The official examples use [restify](http://restify.com/) but we are successfully using expressjs, and I'm sure you can use hapijs as well.

**Comment by somprabhsharma** [comment]
No we can use hapijs, as hapijs puts a wrapper arround the raw request object and you are using req.on events(of raw request object) in the code which hapijs does not understand so it throws below error.
`Debug: internal, implementation, error 
    Error: Uncaught error: Unknown event data
    at Object.exports.unique.exports.contain.exports.reachTemplate.exports.assert.condition [as assert] (/Users/somprabhsharma/projects/test/microsoftbot/node_modules/hapi/node_modules/hoek/lib/index.js:736:11)
    at internals.Podium.registerEvent.internals.Podium.registerPodium.internals.emit.internals.Podium.on.internals.Podium.addListener (/Users/somprabhsharma/projects/test/microsoftbot/node_modules/hapi/node_modules/podium/lib/index.js:279:10)
    at ChatConnector.listen (/Users/somprabhsharma/projects/test/microsoftbot/node_modules/botbuilder/lib/bots/ChatConnector.js:39:21)
    at Object.exports.execute.internals.prerequisites.internals.handler.callback [as handler] (/Users/somprabhsharma/projects/crowdfire/microsoftbot/node_modules/hapi/lib/handler.js:96:36)
    at /Users/somprabhsharma/projects/test/microsoftbot/node_modules/hapi/lib/handler.js:30:23
    at internals.Protect.run.finish [as run] (/Users/somprabhsharma/projects/test/microsoftbot/node_modules/hapi/lib/protect.js:62:12)
    at exports.execute.finalize (/Users/somprabhsharma/projects/test/microsoftbot/node_modules/hapi/lib/handler.js:24:22)
    at internals.Request.internals.Request._execute.internals.Request._lifecycle.each (/Users/somprabhsharma/projects/test/microsoftbot/node_modules/hapi/lib/request.js:380:16)
    at iterate (/Users/somprabhsharma/projects/test/microsoftbot/node_modules/hapi/node_modules/items/lib/index.js:36:13)
    at done (/Users/somprabhsharma/projects/test/microsoftbot/node_modules/hapi/node_modules/items/lib/index.js:28:25)
`

**Comment by somprabhsharma** [comment]
Any update on this ?

**Comment by efog** [comment]
@msft-shahins Hi, the issue remains. Is it something being looked at?

**Comment by msft-shahins** [comment]
@Stevenic or @maxpert can you comment about this?  @efog and @somprabhsharma, I am not familiar with hapijs framework but I believe you can implement a custom connector based on the hapijs request that wraps the chat connector and implements its own listen() function based on happijs events.

**Comment by maxpert** [comment]
I think it will be **totally impractical** for us to implement integration with all possible NodeJS frameworks out there. Having said that, every framework must be able to give you raw request and response objects (consumed by Connector). If for any framework you are not getting raw request and response objects, you should be banging on the doors of framework's team to ask for your basic right. 

So in-case of **hapijs** after 2 minutes of searching around I found there is a simple way to get raw request and response objects from (hint hint it's under ```request.raw```); combining them with connector you should be able to compose a simple function that forwards the request, and response objects to connector, here is an example:

```Javascript
const server = new Hapi.Server();
server.connection({ port: 3000 });

// Initialize your connector
const connector = new builder.ChatConnector({
    appId: process.env.MICROSOFT_APP_ID,
    appPassword: process.env.MICROSOFT_APP_PASSWORD
});

const bot = new builder.UniversalBot(connector);
//=========================================================
// Bots Dialogs
//=========================================================

bot.dialog('/', function (session) {
    session.send("Hello World");
});

// Here botHandler is a function that takes raw request and response object
const botHandler = connector.listen();
server.route({
    method: 'POST',
    path: '/api/messages',
    handler: function (request, reply) {
        botHandler(request.raw.req, request.raw.res); // Forwarded!!!
    }
});
```

Now *I have not tried or tested the above code at all*, but if I am [reading the code right](https://github.com/hapijs/hapi/blob/master/lib/request.js#L134), this should work. Let me know if you are able to get it to work, or if you need to do anything different.

**Comment by efog** [comment]
Thanks mate, some of us aren't too familiar with every intricacies. Your input is greatly appreciated. Will try this.

Regards,

Etienne Brouillard
Sent from Polymail<https://polymail.io/?utm_source=polymail&utm_medium=referral&utm_campaign=signature>

On mer. 23 nov. 2016 at 15:07 Zohaib Sibte Hassan <Zohaib Sibte Hassan <mailto:Zohaib%20Sibte%20Hassan%20<notifications@github.com>> > wrote:

I think it will be totally impractical for us to implement integration with all possible NodeJS frameworks out there. Having said that, every framework must be able to give you raw request and response objects (consumed by Connector). If for any framework you are not getting raw request and response objects, you should be banging on the doors of framework's team to ask for your basic right.

So in-case of hapijs after 2 minutes of searching around I found there is a simple way to get raw request and response objects from (hint hint it's under request.raw); combining them with connector you should be able to compose a simple function that forwards the request, and response objects to connector, here is an example:

const server = new Hapi.Server();
server.connection({ port: 3000 });

// Initialize your connector
const connector = new builder.ChatConnector({
    appId: process.env.MICROSOFT_APP_ID,
    appPassword: process.env.MICROSOFT_APP_PASSWORD
});

const bot = new builder.UniversalBot(connector);
//=========================================================
// Bots Dialogs
//=========================================================

bot.dialog('/', function (session) {
    session.send("Hello World");
});

// Here botHandler is a function that takes raw request and response object
const botHandler = connector.listen();
server.route({
    method: 'POST',
    path: '/api/messages',
    handler: function (request, reply) {
        botHandler(request.raw.req, request.raw.res); // Forwarded!!!
    }
});

Now I have not tried or tested the above code at all, but if I am reading the code right<https://github.com/hapijs/hapi/blob/master/lib/request.js#L134>, this should work. Let me know if you are able to get it to work, or if you need to do anything different.

-

**Comment by maxpert** [comment]
👍 do share if you are able to get it to work, this will help others in community as well.

**Comment by Stevenic** [comment]
Thanks @maxpert ... Yes. If you can access the raw request & response object you can just pass it through, otherwise you have to mock them up. In the case of services like AWS Lambda or Azure Functions you can't actually access the raw request & response so you're left mocking them up. Fortunately, we only need like 5 things of the req & response so the mockup is pretty easy to do.  In this case sounds like you're able to access the raw objects so you should be good.

**Comment by akerr95** [comment]
@maxpert  trying your method doesnt solve it .... also my problem is it doesnt even throw an error as what may be wrong.

**Comment by maxpert** [comment]
Interesting... I would have to actually create a hapi.js app to try out what is going on. I will get back to you on this. What version of node are you using? I will try to replicate your environment.

**Comment by akerr95** [comment]
node v6.9.2 @maxpert

**Comment by maxpert** [comment]
Hey so turns out there were two wrapper methods missing so I just created fake wrapper objects, and everything seems to be working now:

```javascript
'use strict';

const Hapi = require('hapi');
const botbuilder = require('botbuilder');

const server = new Hapi.Server();
server.connection({ port: 3000 });

/**
 * interface IWebResponse {
 *     end(): this;
 *     send(status: number, body?: any): this;
 *     send(body: any): this;
 *     status(code: number): this;
 * }
 */
function responseWrapper(res) {
    return {
        end() {
            res.end();
            return this;
        },

        send(statusOrBody, maybeBody, callback) {
            var responseCode = 200;
            var responseBody = maybeBody;

            if (typeof statusOrBody == 'number') {
                responseCode = statusOrBody;
                responseBody = maybeBody;
            } else {
                responseBody = statusOrBody;
            }

            if (typeof responseBody != 'string') {
                responseBody = JSON.stringify(responseBody);
            }

            res.writeHead(responseCode);
            res.setHeader("Content-Type", "application/json");
            res.write(responseBody, callback);
            res.end();
            return this;
        },

        status(code) {
            res.writeHead(code);
            return this;
        }
    }
}

/**
 * 
 * interface IWebRequest {
 *     body: any;
 *     headers: {
 *         [name: string]: string;
 *     };
 *     on(event: string, ...args: any[]): void;
 * }
 * 
 */
function requestWrapper(request) {
    return {
        body: request.payload,
        headers: request.headers,
        on(event, listener) {
            request.raw.req.on(event, listener)
            return this;
        }
    }
}

// Initialize your connector
const connector = new botbuilder.ChatConnector({
    appId: 'YOUR APP ID',
    appPassword: 'YOUR APP PASSWORD'
});

const bot = new botbuilder.UniversalBot(connector);
const botHandler = connector.listen();
//=========================================================
// Bots Dialogs
//=========================================================

bot.dialog('/', function (session) {
    session.send("Hello World");
});

server.route({
    method: 'POST',
    path: '/api/messages',
    handler: function (request, reply) {
        var wrappedResponse = responseWrapper(request.raw.res);
        var wrappedRequest = requestWrapper(request);
        botHandler(wrappedRequest, wrappedResponse); // Forwarded!!!
    }
});

server.route({
    method: 'GET',
    path: '/',
    handler: function (request, reply) {
        var req = request.raw.req, 
            res = request.raw.res;
        reply('Hello, world!');
    }
});

server.start((err) => {
    if (err) {
        throw err;
    }

    console.log(`Server running at: ${server.info.uri}`);
});
```

 I tested changes working on a bot and it works fine with hapi.js now. @akerr95 please let me know if these changes work for you. I am keeping the issue closed for now. I wrote and tested this code on 6.9.2 as per your comment so the new syntax should work fine (for older versions you can refactor requestWrapper and responseWrapper objects method).

@Stevenic one take away from this can be that we should stop taking dependency on Restify's request/response methods (send, and status) and only rely only on core methods. That will help us keep library framework agnostic. So if someone comes in saying I need to run it on expressjs it's matter of just handing over raw objects.

**Comment by akerr95** [comment]
@maxpert  :') tears of joy i tell you thanks for the help! Works as intended
