### ISSUE TITLE
When bots will be available in other countries?

### ISSUE THREAD

**Issue by VitalyGorelov** [Microsoft/BotBuilder#1143]
Skype FAQ has description how to add bot https://support.skype.com/en/faq/FA34646/what-are-skype-bots-and-how-do-i-add-them
But bots are available only in Australia, Canada, UK, Ireland, India, New Zealand, Singapore and the US. And I haven't this feature in Russia, for example.

When bots will be available in other countries?

**Comment by nickcordrey** [comment]
Bots are available and can be added via join link in a Skype app in any country. However, the bot directory is only shown in the Skype app in certain countries, and we're working on the plan for how to extend to all Skype markets including Russia.

**Comment by VitalyGorelov** [comment]
Unfortunatelly, link is not working for iPad and other non-Microsoft devices.
