### ISSUE TITLE
FormFlow Saying "No" to form confirmation shows redundant text

### ISSUE THREAD

**Issue by wolfer001** [Microsoft/BotBuilder#1145]
I have a FormFlow dialog, and once the fields are filled it prompts a confirmation that all of the fields are correct, if you say "no" it then sends a message asking to to clarify which field you want to change. However when it does this the message sends the field name twice. Once as written in my code with no spaces and again with the spaces and current selection. Is there a way to remove this redundant text?

Example in picture

![screenshot_090116_103601_am]
(https://cloud.githubusercontent.com/assets/19231385/18171411/e22c68a6-702f-11e6-9306-a49aa61d4f5f.jpg)

**Comment by chrimc62** [comment]
Have you changed the NavigationFormat template?  Normally the template is {&}({}) which should show Location(Downtown).  It looks like it might be defined as ({&}({}) {&}.  Let me know if you did not do this and I will look into it further.
