### ISSUE TITLE
How to store appID and appPassword in other host

### ISSUE THREAD

**Issue by tungnt244** [Microsoft/BotBuilder#1147]
When using azure host server, i can store the value of appId and appPassword in Application Setting on Azure, but how can i do that when i deploy it to other host rather than Azure( in my case, it's amazonaws).
I try to change the process.env with my actual appID and appPassword provided by botframework, but it was failed. I'm very appreciated your help.
```
var connector = new builder.ChatConnector({
    appId: process.env.MICROSOFT_APP_ID,
    appPassword: process.env.MICROSOFT_APP_PASSWORD
});
```

**Comment by willportnoy** [comment]
Did you set those variables in the process environment?

**Comment by muzahmed** [comment]
@tungnt244 I'm not familiar with aws, I can help dig into it for you, but to unblock you, you can pass in the appId and password as strings into the builder.ChatConnector call

eg.
`
var connector = new builder.ChatConnector({
    appId: "myAppId",
    appPassword: "myPassword"
});
`

you may also be able to use a package to help store configs: https://www.npmjs.com/package/config 

if you're still blocked on aws, let me know, and we can look into it together
