### ISSUE TITLE
LUIS Authentication 

### ISSUE THREAD

**Issue by irynabond** [Microsoft/BotBuilder#1148]
Hello,
I am using LUIS model with C# Bot Builder SDK. 
I put my luis app id and luis subscription key in this format:
`[LuisModel("<YOUR_LUIS_APP_ID>", "<YOUR_LUIS_SUBSCRIPTION_KEY>")]`
Does SDK provide secure authorization to LUIS service? Do I need to implement additional security procedures within my code when sending requests to LUIS service? Thank you!

**Comment by msft-shahins** [comment]
All the calls that the Luis client implementation in the bot builder is making is over https: https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Luis/LuisService.cs#L86
and this is where the request is getting generated: https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Luis/LuisService.cs#L95

**Comment by dandriscoll** [comment]
Closing this issue as SSL/TLS is industry standard for securing communication and verifying the identity of the service you are calling.
