### ISSUE TITLE
Suggestion: ability to change welcome message "Hi, I'm ... - Say hi if you'd like to chat"

### ISSUE THREAD

**Issue by J3QQ4** [Microsoft/BotBuilder#1149]
When using the web interface for the bot, the greeting message is "Hi, I'm a [bot name]. Say 'hi' if you'd like to chat." and it cannot be changed.

Would it be possible to add a config option to change that default message? 

Thanks.

**Comment by jameslew** [comment]
We'd like to do this, but it's not available right now (though it's on our roadmap).  We'll hopefully be able to add it soon.

**Comment by Sutthipong** [comment]
Any news on this?
