### ISSUE TITLE
Chat Emulator Source Code

### ISSUE THREAD

**Issue by larsontim** [Microsoft/BotBuilder#115]
Would it be possible to get the sourcecode for the chat emulator?  I would like to look into making my own and it would be nice to have a strating place.

**Comment by larsontim** [comment]
Any update if the source code for this or some sample similar could be released?

**Comment by danmarshall** [comment]
Hi @larsontim , this is a great idea and we've heard others ask for this, so we're considering open sourcing it.

**Comment by v-thgratMSGit** [comment]
Thanks @danmarshall. Closing this issue for now.  Please open a new issue for further discussion if necessary.  This would also be worth supporting on [UserVoice](https://feedback.botframework.com/forums/354213-general/suggestions/13393263-bot-framework-emulator-console-app-source-code).  Thanks!
