### ISSUE TITLE
Internal Server Error/Unable to deserialiaze to response in local emulator

### ISSUE THREAD

**Issue by shahriarhossain** [Microsoft/BotBuilder#1150]
Whenever I tried to run the Bot template(File > New > Bot application) I encounter a problem. 

As you can see from the following image I sent "Hello World" from the local emulator. The "_reply_" variable was successfully able to process my text. 
![new](https://cloud.githubusercontent.com/assets/6463320/18193921/f8a8156a-7103-11e6-91b0-900e7b74cc1b.png)

As soon it hits "**await connector.Conversations.ReplyToActivityAsync(reply);**" this throwing an exception.

The emulator shows the **Internal Server Error** exception:
![botemulator3](https://cloud.githubusercontent.com/assets/6463320/18194032/aceffa7e-7104-11e6-92b2-63c5fa03d11b.PNG)

When I drill down the exception I found "**Unable to deserialize the response**".

Here is the stack:
**Exception**: {"Unable to deserialize the response."}
**InnerException**: Message	"Unexpected character encountered while parsing value: <. Path '', line 0, position 0."
**Source**: Newtonsoft.Json
**StackTrace**: 		StackTrace	"   at Newtonsoft.Json.JsonTextReader.ParseValue()\r\n   at Newtonsoft.Json.JsonTextReader.Read()\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)\r\n   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)\r\n   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)\r\n   at Microsoft.Rest.Serialization.SafeJsonConvert.DeserializeObject[T](String json, JsonSerializerSettings settings)\r\n   at Microsoft.Bot.Connector.Conversations.<ReplyToActivityWithHttpMessagesAsync>d__7.MoveNext()"	string

Can somebody point me a solution?

**Comment by shahriarhossain** [comment]
@willportnoy need help on this !

**Comment by ejadib** [comment]
@shahriarhossain try updating the Bot.Builder NuGet package. The template is using v3.0.0 and current version is 3.2.0

**Comment by shahriarhossain** [comment]
Did that already, but still am unable to work with the local emulator. Please note: The same code works smoothly in Azure.

**Comment by ejadib** [comment]
The emulator URL is wrong in your screenshot is wrong. Try replacing http://localhost:3979 with http://localhost:9000/. Just the first url. The Bot url is ok.

**Comment by shahriarhossain** [comment]
@ejadib :  Now its working :+1:
