### ISSUE TITLE
Bot framework in C# does not respect activity.TextFormat on certain channels

### ISSUE THREAD

**Issue by DrWala** [Microsoft/BotBuilder#1152]
I've set activity.TextFormat to be "plain", however the formatting is not respected in Slack and Telegram. However, The bot framework emulator does respect it. The text in the activity looks like this:

#Something 

However, even with TextFormat set to plain, the words are bolded on Telegram, and Slack displays it as # Something #.

Do let me know what other screenshots I need to provide to assist in investigating this. I'm using the C# SDK, with BotFramework v3

**Screenshots:**
![Telegram text response that is bolded despite TextFormat being plain](https://cloud.githubusercontent.com/assets/6803997/18196413/d01c22f6-7123-11e6-989f-97c79313f605.png)
Telegram text response that is bolded despite TextFormat being plain (Incorrect)

![Slack response that surrounds text with '#' despite TextFormat being plain](https://cloud.githubusercontent.com/assets/6803997/18196452/11db58b0-7124-11e6-9d7d-9246d18d8bb3.png)
Slack response that surrounds text with '#' despite TextFormat being plain (Incorrect)

![Bot framework emulator response that is not formatted when TextFormat is plain](https://cloud.githubusercontent.com/assets/6803997/18196434/ec5404b6-7123-11e6-9543-dee484912649.png)
Bot framework emulator response that is not formatted when TextFormat is plain (Correct)

**Comment by eanders-MS** [comment]
Hi DrWala, looks like a bug. Thank you for reporting. I will reply here when a fix for this goes live. Small issues like this typically have fast turnaround.

**Comment by DrWala** [comment]
Hi, any update?

**Comment by eanders-MS** [comment]
Hi @DrWala, apologies for the delay. Before we make a fix I'd like to understand a little better what you think correct behavior should be here. Would you expect markdown to be stripped from the message? Or, would markdown formatting remain, and be treated as plaintext? I'm guessing the latter.

**Comment by eanders-MS** [comment]
@DrWala A fix has been made for Telegram. We've taken a TODO to update Slack, but do not have a timeline for this yet. This fix will be available in the next production update. Production updates typically happen about once a week.

**Comment by LarsLiden** [comment]
The extra # at end of the line is being added by Slack, not by the Bot Framework.

**Comment by pchoudhari** [comment]
We rolled out a fix for this. Please verify.

**Comment by nwhitmont** [comment]
@poojashivach You are commenting on a closed issue. 

If you have a question or problem, please [open a new issue.](https://github.com/microsoft/botbuilder/issues/new)
