### ISSUE TITLE
Keeping large number of data-bags

### ISSUE THREAD

**Issue by afficionaddo** [Microsoft/BotBuilder#1153]
Hi,

The bot I am building can have upto 5000 users.
For every user I'll be maintaining a data-bag for holding some custom data.

1. Is this the right approach?
2. Any restrictions or limit on the data-bags as it will be stores in your Azure of BotState.
3. Any impacts due to so many databags being maintained?

**Comment by willportnoy** [comment]
https://docs.botframework.com/en-us/technical-faq/#is-there-a-limit-on-the-amount-of-data-i-can-store-using-the-state-api

We don't have any limits on the number of users.  Longer term, you can always write your implementation of the state store interfaces.

**Comment by willportnoy** [comment]
I'm going to close this issue, but free to open a new issue for further discussions.
