### ISSUE TITLE
Trying to create a nuget package on azure

### ISSUE THREAD

**Issue by mephisto83** [Microsoft/BotBuilder#1154]
We are trying to create a nuget package on azure with the Microsoft.Bot.Builder which has a dependency with the Microsoft.Rest.ClientRuntime. We have a dependency on the Newtonsoft.Json also, which seems to be creating a conflict. Any insites would be helpful.

******************************************************************************
Starting: NuGet Packager
******************************************************************************
Preparing task execution handler.
Executing the powershell script: C:\a\_tasks\NuGetPackager_333b11bd-d341-40d9-afcf-b32d5ce6f24b\0.1.67\NuGetPackager.ps1
C:\a\1\s\NugetPackage
C:\LR\MMS\Services\Mms\TaskAgentProvisioner\Tools\agents\2.105.5\externals\nuget\NuGet.exe pack "C:\a\1\s\U4.Bot.Util\U4.Bot.Builder.csproj" -OutputDirectory "C:\a\1\s\NugetPackage" -Properties Configuration=release -IncludeReferencedProjects  -version 2.0.53
MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.
Attempting to build package from 'U4.Bot.Builder.csproj'.
Packing files from 'C:\a\1\s\U4.Bot.Util\bin\Release'.
'Microsoft.Rest.ClientRuntime' already has a dependency defined for 'Newtonsoft.Json'.
System.Exception: Unexpected exit code 1 returned from tool NuGet.exe
   at Microsoft.TeamFoundation.DistributedTask.Task.Internal.InvokeToolCmdlet.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
PowerShell script completed with 1 errors.

**Comment by willportnoy** [comment]
Perhaps your packages depend on different versions than specified in our nuspec?

https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Microsoft.Bot.Builder.nuspec#L29

**Comment by dandriscoll** [comment]
Hi @mephisto83, I believe @willportnoy is correct that this is due to a version mismatch. Please take a look and let us know if fixing the versions does not address the problem.

**Comment by dandriscoll** [comment]
If you encounter issues after resolving the version problem, please open a new issue. Thanks
