### ISSUE TITLE
language translation

### ISSUE THREAD

**Issue by rebeker** [Microsoft/BotBuilder#1156]
hi,

I cannot see the "Translate Channel Messages" button in my bot in bot framework developer portal.

am I missing anything?

Thanks.
R.

**Comment by willportnoy** [comment]
Can you tell me where in the documentation you see a mention of "Translate Channel Messages"?  I don't believe that feature is available in V3.

**Comment by jameslew** [comment]
Will is correct, auto-translate was removed from the Bot Framework with the V3 upgrade.  The developer and user experience are better when the bot calls the service directly rather than the Bot Framework trying to infer language preference and user intent.

**Comment by willportnoy** [comment]
I'm going to close this issue, but free to open a new issue for further discussions.
