### ISSUE TITLE
NodeJS: UserData not saved

### ISSUE THREAD

**Issue by JpEncausse** [Microsoft/BotBuilder#1158]
Hi,
I may have missed something, tested with the emulator,

```
bot.dialog('/', [(session) => {
   session.userData.cpt = (session.userData.cpt || 0) + 1;
 }]);
```

User data seems to be never saved ?

**Comment by JpEncausse** [comment]
Ok calling session.save() after a modification will work.
I thought it was magically saved();

**Comment by Stevenic** [comment]
Can you show the rest of your code please?  If all you're doing is modifying `userData` and you're not calling `send()` or `beginDialog()` afterwards you will need to call `save()`. You also need to call `save()` if you do something like make an async call and simply want to persist something to `userData` afterwards.  Think of it more like cookie storage. Modifications are bounded to the lifetime of your bots response.

**Comment by JpEncausse** [comment]
Hum, that might be that.

I made a little implementation of MSBot in NodeRED. So I may or may not call send() while storing some data.

At last, I always call save() so i'm sure not to lost something
