### ISSUE TITLE
ReceiptCard -  tax and total fields appear by default, even when not specified

### ISSUE THREAD

**Issue by naeemshaikh27** [Microsoft/BotBuilder#1159]
Here is the code
```

var msg = new options.builder.Message(session)
            .attachments([
              new options.builder.ReceiptCard(session)
              .title("Loan ")
              .items([])
              .facts([
                options.builder.Fact.create(session, "1234567898", "Loan Number")
              ])
            ]);
          session.send(msg);
```

I have not specified any tax or total for the receipt card. But somehow it still shows those fields but empty.

![capture](https://cloud.githubusercontent.com/assets/6553193/18206332/c3307a2c-7143-11e6-817e-f29f4ca9ae0f.PNG)

Works fine on emulator

**Comment by jameslew** [comment]
Can you confirm which channel you're working with?  Both Skype and Facebook implement the receipt card.

**Comment by naeemshaikh27** [comment]
i am working on web chat.

**Comment by hamzassi** [comment]
These fields appear on default even if not initialized. Notice that 'Tax' field is not mandatory, but 'Total' is. So if you pass a value to 'Total', 'Tax' will be ignored, but not the opposite!

**Comment by naeemshaikh27** [comment]
@hamzassi isnt that an issue that needs a fix, if tax appears even when not specified. Also is there any way you can create a card which is not a reciept, i.e. doesnt need a tax and total field. In my case i am creating a card to show user loan details, which need not have a total field. I can use markdown to format my text in tabular format, but table markdown doesn't work on all channels

**Comment by hamzassi** [comment]
@naeemshaikh27 I've contacted the devs at Microsoft and they gave me a reasonable explanation for that: "A receipt denotes a payment or request for payment", so the 'Total' field cannot be omitted apparently. You can check the 'HeroCard' and 'ThumbnailCard' cards. They're more flexible which gives the ability to add and omit fields as you please. Regarding the tabular format, I'm not very sure about that, as I've never done it or needed to do it before.
