### ISSUE TITLE
Adding examples for other .Net Languages

### ISSUE THREAD

**Issue by WilliamBerryiii** [Microsoft/BotBuilder#1162]
I'd like to start adding samples for other .Net languages; but the project structure is not supportive of this activity.  I'd like to suggest that the `CSharp` folder be renamed to `DotNet` and that the sample folder be subdivided further by language grouping.  Perhaps with a structure like `Samples -> CSharp -> SampleEchoBot`.  Once this work is complete the support for adding examples, in say VB or F#, should be trivial.

**Comment by willportnoy** [comment]
That sounds reasonable - we have some samples pending that follow that structure somewhat, and we were hoping to reorganize the existing samples/examples in that format.

**Comment by WilliamBerryiii** [comment]
What do you think the ETA on this might be?  Would you just like a PR with the change?

**Comment by willportnoy** [comment]
@jameslew @Andrea-Orimoto any thoughts on when we could check in the new samples?

**Comment by Andrea-Orimoto** [comment]
Without committing to a specific date, I'd say we should be able to begin rolling out the new samples this month. Stay tuned! I'm closing this issue for now, let us know if you have any more questions. Thank you!

**Comment by WilliamBerryiii** [comment]
@Andrea-Orimoto can I ask why the issue is being closed?

**Comment by Andrea-Orimoto** [comment]
@WilliamBerryiii sorry, I thought we answered your question, the new sample structure is coming soon. Basically this is a feature request that is being addressed, and we usually close these types of issues once answered, otherwise they remain open indefinitely. If you want to keep track of it on your side, feel free to reopen it. Thanks!

**Comment by WilliamBerryiii** [comment]
@Andrea-Orimoto this was about a structural change to the project to support other language samples contributed from outside - i.e. VB and F# ... please see the initial issue comment.

**Comment by Andrea-Orimoto** [comment]
@WilliamBerryiii yes, that's exactly what we're going to do. Current thinking is that there will be a new top level /samples folder, with a structure like /samples/sample-name/language. For example

* samples
 * echobot
   * C#
    * Node
 * another sample
   * C#
    * Node
 * etc...

This should address your request, sorry if it was not clear. Let us know if you still have questions. Thank you.

**Comment by WilliamBerryiii** [comment]
Can I make the suggestion that the breakdown be by language so that the project names can stay the same without conflicting? I.E. `Samples -> CSharp -> SimpleEchoBot` and `Samples -> FSharp -> SimpleEchoBot`

**Comment by Andrea-Orimoto** [comment]
Good suggestion, we'll consider it. What do you mean by "conflicting" exactly? thanks.

**Comment by WilliamBerryiii** [comment]
Ignore the `conflicting` remark ... I would still vote for the by language orientation rather than the by example.
