### ISSUE TITLE
[C#] Facebook Authentication in Skype keep failing

### ISSUE THREAD

**Issue by wswijaya** [Microsoft/BotBuilder#1163]
I create a bot that uses fb authentication. I tested it in Skype desktop, the link is generated and i can login. when i tried in skype ios, it keeps throwing "The redirect_uri URL is not properly formatted".
The same link works in Telegram.

I noticed that in Skype when that link is click it encoded % to %25 which invalidate the link. is this a skype ios  bug?

**Comment by msft-shahins** [comment]
@wswijaya have you tried using a [Sign-In](https://docs.botframework.com/en-us/csharp/builder/sdkreference/attachments.html#signincard) card rather than sending the url?

**Comment by wswijaya** [comment]
Just tried. It works. Thank you so much.
