### ISSUE TITLE
NodeJS - Facebook Stickers

### ISSUE THREAD

**Issue by JpEncausse** [Microsoft/BotBuilder#1164]
Hi,
How can I send a Facebook sticker from my bot ?
I could set an attachement but how can I set the sticker_id ?

**Comment by msft-shahins** [comment]
Currently stickers are not supported by facebook send api: https://developers.facebook.com/docs/messenger-platform/send-api-reference

> We support multiple types multimedia and templates attachments:

> * image
> * audio
> * video
> * file
> * generic template
> * button template
> * receipt template

**Comment by BlonDev** [comment]
Hey, this is now over one year old.  
Is it still the case that stickers are not supported by the facebook send api?
