### ISSUE TITLE
BotBuilder localhost is not getting created

### ISSUE THREAD

**Issue by anshulgupta09** [Microsoft/BotBuilder#1166]
Using simple code to activate localhost at port 3978 is not working using botbuilder. Here is the code:

var restify = require('restify');
var builder = require('../../core/');

//=========================================================
// Bot Setup
//=========================================================

// Setup Restify Server
var server = restify.createServer();
server.listen(process.env.port || process.env.PORT || 3978, function () {
   console.log('%s listening to %s', server.name, server.url); 
});
  
// Create chat bot
var connector = new builder.ChatConnector({
    appId: process.env.MICROSOFT_APP_ID,
    appPassword: process.env.MICROSOFT_APP_PASSWORD
});
var bot = new builder.UniversalBot(connector);
server.post('/api/messages', connector.listen());

//=========================================================
// Bots Dialogs
//=========================================================

bot.dialog('/', function (session) {
    session.send("Hello World");
});

**Comment by jameslew** [comment]
How do you know that it isn't getting created?  Unable to connect to it?  From which?

**Comment by anshulgupta09** [comment]
Hi James, I tried opening that port on a webpage but getting 404 error. below is snapshot.
![snap](https://cloud.githubusercontent.com/assets/21671948/18226814/858ddb3c-722f-11e6-8fb7-83494dcc62d1.jpg)

**Comment by muzahmed** [comment]
@anshulgupta09 I think its running since you are getting a 404. Since you dont have any GET routes registered, you wont be able to hit it via the browser.

If you're curious, you can add a GET route to return hello world, or you can post via postman and see the response. Let me know if you have further troubles!
