### ISSUE TITLE
How to add a new channel to support another App?

### ISSUE THREAD

**Issue by kenyeung128** [Microsoft/BotBuilder#1168]
Hi

I am looking for a solution of how to add a channel to interact with the ms bot framework, did anyone try before? I have my own app, so would like to redirect the message to the bot and get the reply back.

Thanks.
Ken

**Comment by dandriscoll** [comment]
Hi @kenyeung128, the Direct Line API is designed for this scenario. You can embed your bot in any app or webpage by adding the Direct Line channel, generating a secret, and coding to the Direct Line REST API.

https://docs.botframework.com/en-us/restapi/directline/

**Comment by kenyeung128** [comment]
thanks @dandriscoll , it's great with the Direct Line, i missed it out before. But it seems I have to keep polling the rely? it doesn't support push?

**Comment by dandriscoll** [comment]
We're working on adding a push protocol to Direct Line, likely for the next version.

**Comment by kenyeung128** [comment]
sounds great @dandriscoll  thanks.
