### ISSUE TITLE
How does Microsoft Bot Builder handle messsages

### ISSUE THREAD

**Issue by tungnt244** [Microsoft/BotBuilder#1169]
When i have a lot of customer chat with my bot at the same time. 
How does the bot handle these messages ?
Does it create an instance for every customer or just a few instance handle all that messages?

**Comment by willportnoy** [comment]
Your bot is a web service, typically hosted within ASP.NET.  It uses the same model as any other web service for handling requests.  You might want to read more about the ASP.NET request pipeline, for example.

**Comment by willportnoy** [comment]
I'm going to close this issue for now, but free to open a new issue for further discussion.
