### ISSUE TITLE
Accessing intents/entities during the IntentDialog execution

### ISSUE THREAD

**Issue by haggaishachar** [Microsoft/BotBuilder#1171]
Hello,

I'm trying to access the recognized intent/entities info anytime during the execution of the IntentDialog.  

I tried to use the bot's _receive_ and _botbuilder_ middlewares, and also dialog _onBegin_ hook, but unfortunately, all are executing **before** the recognizers code. 
I tried also to play with the RecognizeMode with no luck. 

What would you suggest? 

Thank you,
Haggai.

**Comment by Stevenic** [comment]
If you look at the note in the reference docs for [IntentDialog.matches()](https://docs.botframework.com/en-us/node/builder/chat-reference/classes/_botbuilder_d_.intentdialog.html#matches) they get passed in via the [args](https://docs.botframework.com/en-us/node/builder/chat-reference/interfaces/_botbuilder_d_.iintentrecognizerresult) param of your first waterfall step. I realize that's not super obvious in the docs so we're working to improve the docs as a whole.

**Comment by haggaishachar** [comment]
Hey Steve, 
Thank you for this info, it's helpful. 

I was hoping though for something less intrusive, something that would not require me to touch the dialog's specific code.

My goal is to develop a middleware that can help me (and others) keep track of the recognized intents and to use this info to better optimize the model. 

BR,
Haggai.

**Comment by dandriscoll** [comment]
Hi @haggaishachar, it looks like this question has been resolved. Steve is working on docs so they will be better over time. Please feel free to open a new issue if you have further questions. Thanks

**Comment by Stevenic** [comment]
@haggaishachar I see... Let me think about adding an event or something you can hook.

**Comment by Stevenic** [comment]
@haggaishachar we were just talking internally and the right way to do this currently would be to create a logging class that wraps the `LuisRecognizer` class. This will let you log the results of any call to LUIS. If you make it a generic `IntentRecognizer` wrapper it will work with any potential recognizer service.

That will let you see the raw calls to LUIS but won't tell you who ultimately won in the case where multiple recognizers are used. We'll think about that scenario some more on our end.

**Comment by haggaishachar** [comment]
Thank you Steve for bringing this topic back.

My goal is to develop a BI to AI solution, which can analyze intents and entities and use this information to optimize the AI models.
I was hoping to generalize this concept and to let anyone who is using the BotBuilder nice dashboard with easy instrumentation . A middleware would be the perfect solution i think.

**Comment by Stevenic** [comment]
We have a plan but not sure on the when for this.  I'll circle back to the thread when it gets in.

**Comment by chrimc62** [comment]
@Stevenic or @maxpert was this resolved?

**Comment by Stevenic** [comment]
closing for now
