### ISSUE TITLE
DirectLine - From

### ISSUE THREAD

**Issue by NicolasHumann** [Microsoft/BotBuilder#1172]
Hi,

In the directline API (I use the C# sdk), the FromProperty ("from" in json) is a single string. This is enough when I have to check the sender of the message comming from the GetMessagesAsync method.
But in the bot code, the Activity.From property is set from the "from" property of directline. The activity.From is a ChannelAccount object which is usefull to know the  ChannelId and the friendly name, but both property are set with the single string.

I purpose to change the directline api of the "from" property to a ChannelAccount object

Thanks

**Comment by dandriscoll** [comment]
Hi @NicolasHumann, good suggestion. The next release of Direct Line will include updated names. Unfortunately, we cannot change the current version without breaking clients.
