### ISSUE TITLE
Slack API token or Slack events from Bot Framework

### ISSUE THREAD

**Issue by hughcameron** [Microsoft/BotBuilder#1174]
Hi there - we've built a Slack bot using the MS Bot Framework (V3), bot id is buttonai.

Can the Bot Framework can expose the Slack API token or Slack events?

We'd like to perform some tasks that would benefit from this access, i.e. 
- getting the team information
- getting the user’s information
- send message when bots is added

Any assistance would be greatly appreciated!

**Comment by somprabhsharma** [comment]
+1

**Comment by craigjensen** [comment]
We are working on an update that will send the token as part of the ChannelData on every message.  You can then extract the token and make your own Slack RTM Api calls.  The update should be published soon - hopefully in the next couple days.

**Comment by hughcameron** [comment]
Hey Craig - thanks so much for letting me know! That should help button a lot ;)

Do you mind if I keep this open until that update?

**Comment by craigjensen** [comment]
Update is deployed in production.  Please give it a try and reopen if needed.

**Comment by duncanmak** [comment]
@craigjensen I'm building a proactive bot, what's a way for me to get the token on startup? Are there events that I can register to on start-up or on channel join?

**Comment by craigjensen** [comment]
Pretty much every message sent to your bot will contain the token in ChannelData/SourceEvent.  The first message you should receive is the installationUpdate activity when a user registers your bot in their channel.  You'll also receive messages when your bot is added to a channel.  You can get the token from any of these.

**Comment by duncanmak** [comment]
@craigjensen I'm writing my bot in Typescript. Do I always have to start with `bot.dialog("/", ...)` to get at the `session` object in order to access channel data?

It's my understanding `dialog` won't be triggered until something is said in the channel.

The bot I'm trying to write is only for Slack.

Thanks!
