### ISSUE TITLE
[.Net] How to get Topic Name of Skype conversation in moment when bot was added to group conversation?

### ISSUE THREAD

**Issue by streamy878** [Microsoft/BotBuilder#1175]
I use .Net SDK. When I add bot to Skype group conversation I get activity object with property "TopicName" = null. The only way that I found  to get the conversation the topic name - to change it and handle "TopicName" property. Is there any possibility to get a group conversation name at the time of adding the bot to it?

**Comment by nickcordrey** [comment]
Unfortunately getting topic name is not supported in Skype today.
