### ISSUE TITLE
Calls to DirectLine repeatably return "Internal Server Error" when sending a message in rapid succession

### ISSUE THREAD

**Issue by rposbo** [Microsoft/BotBuilder#1176]
If I create an HttpClient in C# using code similar to:

```csharp
// configure the httpclient with baseaddress and auth headers
var client = new HttpClient {BaseAddress = new Uri("https://directline.botframework.com")};
client.DefaultRequestHeaders.Accept.Clear();
client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("BotConnector", MyDirectLineSecret);

// make an initial request to ensure auth worked
var response = await client.GetAsync("/api/tokens/", HttpCompletionOption.ResponseHeadersRead).ConfigureAwait(false);
response.EnsureSuccessStatusCode();

// create a conversation
response = await client.PostAsJsonAsync("/api/conversations/", new object()).ConfigureAwait(false);
response.EnsureSuccessStatusCode();

// read the conversation and auth token data
var convoInfo = await response.Content.ReadAsAsync<JObject>();
var convoId = (string)convoInfo["conversationId"];
var scopedToken = (string)convoInfo["token"];

// set auth header to new token
client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("BotConnector", scopedToken);
```

If I then have a method which sends a new message:

```csharp
// create new message
var newMessage = new
{
    id = Guid.NewGuid().ToString(),
    created = DateTime.UtcNow,
    from = "MyTestBot",
    text = "some test text",
    eTag = "*"
};

// post message to conversation - this is the line that returns the HTTP 500
var response = await client.PostAsJsonAsync($"/api/conversations/{convoId}/messages", newMessage).ConfigureAwait(false);
response.EnsureSuccessStatusCode();
```

It will work (returning HTTP 200) if I call it patiently, but calling it twice in rapid succession causes an HTTP 500 Internal Server Error with the content 
```json
{
  "message": "failed to send message"
}
```

Application Insights for Bot Connector just shows HTTP 500/Internal Server Error. 

What is the underlying error? What can I do to mitigate this? Am I sending invalid data (given that it works if I make the requests sslloowwllyy, I doubt that's the cause)?

**Comment by rposbo** [comment]
Example conversation ID in which this error occurred: **J1QN4LyLcq6** (~ 10:14AM 06 Sept BST)

**Comment by dandriscoll** [comment]
Hi @rposbo, looking at the logs for your conversation, your bot is throwing an error when we try to contact it.

Do you have AppInsights configured for your bot, or do you have any internal tracing?

Direct Line is the only channel that communicates bot errors back to the client, so this is somewhat expected. You may actually be hitting this error in other channels but the messages are being dropped.

**Comment by rposbo** [comment]
Hi @dandriscoll - yep, we have App Insights set up:

```
"POST to the bot's endpoint failed with HTTP status 500"
[{"parsedStack":[{"assembly":"Microsoft.Bot.ChannelConnector, Version=3.1.1.0, Culture=neutral, PublicKeyToken=null","method":"Microsoft.Bot.ChannelConnector.BotAPI+<PostMessageToAppAsync>d__14.MoveNext","level":0,"line":227,"fileName":"C:\\a\\1\\s\\Microsoft.Bot.ChannelConnector\\API\\BotAPI.cs"}],"outerId":"0","message":"POST to the bot's endpoint failed with HTTP status 500","type":"System.Exception","id":"46050481"}]
```

:'(

**Comment by dandriscoll** [comment]
I'm surprised you're not getting a response body in that trace. I can post a more detailed stack if you're interested.

**Comment by vikanti** [comment]
its getting because you have pass extra slash in emulator url, pls check it

**Comment by rposbo** [comment]
Hi @vikanti - I'm not using the emulator in this example; which URL are you referring to? AFAIK they're all correct. Especially since they work when requested slowly and only fail when called in rapid succession.

**Comment by dandriscoll** [comment]
Followed up offline. This is an error generated within the bot.
