### ISSUE TITLE
"There was an error sending this message to your bot" When using the Direct Line API 

### ISSUE THREAD

**Issue by brendanarnold** [Microsoft/BotBuilder#1177]
Hi,

I get an intermittent error in Direct Line where the Bot Framework fails to connect to my Azure hosted bot in the background. The error reads "There was an error sending this message to your bot."

It seems to be mostly when first using the bot it fails, the second time it works OK. The bot doesn't do any really heavy actions other than calling the LUIS API.

Is this a timeout issue when spinning up the bot for the first time? The initial call to init the conversation API seems to work OK but this may not call the Azure hosted bot.

This happens for another bot I have using Direct Line as well.

**Comment by rposbo** [comment]
Looks like you're having the same problem as me in #1176

**Comment by dandriscoll** [comment]
Hi @brendanarnold, typically this means your bot is generating an exception.

Do you have AppInsights set up in the Bot Framework dev portal, or do you have any internal tracing to see errors your bot is generating?

Most channels drop these errors but Direct Line sends them back to the client. It's possible your bot is throwing these exceptions on all channels but they're being ignored in other cases.

**Comment by dandriscoll** [comment]
Closing issue as this is most likely an error in the bot.
