### ISSUE TITLE
problem on the FB carousel display

### ISSUE THREAD

**Issue by KIBASSA** [Microsoft/BotBuilder#1183]
Hi, 
In my carousel when the HeroCard has no action buttons, it comes out of the carousel.
As in the example below:

![carousel](https://cloud.githubusercontent.com/assets/8443316/18285357/4b77dc18-746e-11e6-8077-8576e621cfa9.png)

The first 4 HeroCard does not have buttons so it leaves the carousel.

How can I do to incorporate that?

This is how i added to attachments list: 
 var noSeanceAttch = new HeroCard()
       {
                 Title = room.element.Name,
                 Text = $"Il n'y a plus de séance disponible pour aujourd'hui."
       };
      Reply.Attachments.Add(noSeanceAttch.ToAttachment());

Thank you in advance, 
Kibassa

**Comment by danmarshall** [comment]
I can't say specifically but this other thread may have some insights: https://github.com/Microsoft/BotBuilder/issues/1090

**Comment by reyesrico** [comment]
It seems that every item inside a carousel must have at least one button to be processed.

Here it is the Facebook Developer API reference:
https://developers.facebook.com/docs/messenger-platform/send-api-reference/generic-template
