### ISSUE TITLE
[Feature Request] Ability to hook just after intent resolution, before method call

### ISSUE THREAD

**Issue by andrew-kennedy** [Microsoft/BotBuilder#1185]
I would love the ability to execute code easily after a LuisDialog resolves an intent, but before it calls the corresponding annotated method. 

My primary use case is that I want to be able to record the last intent that was "hit" so that I can essentially do a state update and call that method again. 

For example, the user can perform some query and then say "what about `<different item>`" and I redo the same code path but with a different bot state. This allows me to have a generic "UpdateAndRepeatAction" intent. 

It would also be nice to have an easy way to call a method that corresponds to an intent.

At present, I am adding code to all my annotated intent methods that could have later refinements, and storing the intent in the bot state. Then in my "UpdateAndRepeatAction" method I am using a switch case to call the correct method again after updating state. This is just sort of brittle and requires many changes any time I want to add a new method or Intent, since it must be hard coded in as a string to match against.

**Comment by haefele** [comment]
**For your first question:**
It should be quite easy to add a "BeforeIntentHandler" protected virtual method to the LuisDialog.

**For your second question:**
You can actually do this right now.
The LuisDialog has a protected Dictionary<string, IntentActivityHandler> called *handlerByIntent*.
You can just execute it like this:
``` c#
string intentYouWantToExecute = "something";

IntentActivityHandler handler = null;
if (base.handlerByIntent.TryGetValue(intentYouWantToExecute, out handler))
{
    await handler(context, awaitableMessageActivity, yourLuisResult);
}
```

**Comment by haefele** [comment]
Thinking about it, you can propably override the *GetHandlersByIntent* method and wrap each IntentActivityHandler with your special code.

``` c#
protected override IDictionary<string, IntentActivityHandler> GetHandlersByIntent()
{
    var handlersByIntent = base.GetHandlersByIntent();
    return handlersByIntent.ToDictionary(f => f.Key, f => this.Wrap(f.Value));
}

private IntentActivityHandler Wrap(IntentActivityHandler handler)
{
    return async (context, message, result) =>
    {
        //Your common code you want to execute before a handler is executed

        await handler(context, message, result);
    };
}
```

**Comment by willportnoy** [comment]
You might consider overriding BestIntentFrom, delegate to the base implementation, then save the selected intent in your class member variable.

https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Dialogs/LuisDialog.cs#L166

**Comment by willportnoy** [comment]
:) happy to hear.  I'm going to close this issue, but free to open a new issue as needed.
