### ISSUE TITLE
Custom BotConnector

### ISSUE THREAD

**Issue by afficionaddo** [Microsoft/BotBuilder#1187]
Hi,

May be I am just spit-balling here.

I want to use BotFramework for my coding.  But BotConnector is like a 3rd party dependancy for me.
Is there a way to implement custom BotConnector through which I can talk directly to a channel?

Apologize if I sound naive....but just an idea.

**Comment by jameslew** [comment]
In the end, the Bot Framework is design to make work you already could do easier.  Ie the chat services (with the exception of Skype) all have their own dedicated Bot API's that you could code to directly; but you would have to code to each channel that you wanted to and take care of managing them individually.

**Comment by afficionaddo** [comment]
Yes, but you see the 'Bot Connector' ties my bot to microsoft infrastructure i.e. a dependancy for my bot. Now if I pitch this to some clients,  chances are they might not like this and highlight it as a risk.
For e.g,  if in future any policy or other terms of Microsoft Bot Framework change.

**Comment by jameslew** [comment]
Absolutely.  As I was saying, you can code directly to those services API's without taking a dependency on Bot Framework (by using them directly).  You just also don't get the benefits of Bot Framework.

Right now there aren't any current plans to make the connector service something you can host in your own deployment.

**Comment by Thegaram** [comment]
I think the main part of the Bot Framework is the Bot Connector, with the Connector API abstracting out the channel details, as @jameslew said. Bypassing this means not using the Bot Framework. (The Bot Builder SDKs are basically just helpers to use the Connector and State APIs.)

**Comment by jameslew** [comment]
I'm going to close this for now assuming your question has been answered.  Feel free to create a new one if we didn't appropriately cover the question.

**Comment by Xzya** [comment]
I am in a similar position. It seems that now you need a subscription on Azure Bot Service to use it, and the WebChat and DirectLine channels are not *free* anymore (and I'm sure there are some other hidden costs as well).

So I was wondering if it's possible to make my own custom connector which connects to facebook/web etc. (by implementing `IConnector`, similar to how the ChatConnector and ConsoleConnector work) ?

This seems possible, but I haven't seen anyone doing this, so I was wondering if I'm missing something (everyone uses the DirectLine to make new "Connectors").

Thank you!
