### ISSUE TITLE
[.Net] Allow Choice PromptOptions to take different types

### ISSUE THREAD

**Issue by rposbo** [Microsoft/BotBuilder#1189]
The default `PromptStyler` will always render a `HeroCard` when the `PromptStyle` is set to `Auto`:

https://github.com/Microsoft/BotBuilder/blob/1958a3f946c2e8a540196b7d12fd15255932ce7c/CSharp/Library/Dialogs/PromptDialog.cs#L212

It will also always call ".ToString()" on each option for all `PromptStyle`s except `PromptStyle.None`; if the "options" are `string` or `int` then this isn't a problem, **however** when the options are `ThumbnailCard`s (for example) then the resulting message is a `HeroCard` containing one button `CardAction` per `ThumbnailCard`, all of which have the button text and value set to `Microsoft.Bot.Connector.ThumbnailCard`.

This _can_ be overridden with a custom `PromptStyler`, such that a list of `ThumbnailCard`s are rendered nicely.

**However**, `Prompt.Choice` ultimately calls `context.Call`: 

https://github.com/Microsoft/BotBuilder/blob/1958a3f946c2e8a540196b7d12fd15255932ce7c/CSharp/Library/Dialogs/PromptDialog.cs#L325

and `context.Call`'s params must be of the same generic type, i.e..:

`void Call<R>(IDialog<R> child, ResumeAfter<R> resume)`

The problem here is that _if_ you can successfully render a series of `ThumbnailCard`s via a custom `PromptStyler`, you are still required to have a `ResumeAfter` which takes a `ThumbnailCard` since that's the type of the list of options you're passing in to the `Choice`; and having a `ThumbnailCard` being submitted back (i.e., by clicking a `CardAction` button in the `ThumbnailCard`) doesn't appear to be possible.

Request: allow `Context.Call` to have a `ResumeAfter<R> resume` taking a different type to `IDialog<R> child`. Or something like that. 

Hopefully that makes sense... :smiley:

**Comment by chrimc62** [comment]
@msft-shahins can you please comment or file a TFS item and close?

**Comment by msft-shahins** [comment]
@rposbo by definition prompt choice selects the object T that is selected by the user. If you want to map the selected option to another object you can inherit from PromptDialog and implement your custom prompt choice with a TryParse function that implements the functionality you expect above. For example, you can implement a TryParse function that finds the right thumbnail card based on the option selected by the user.
