### ISSUE TITLE
[Node.js] I'm stuck in an endless "I didn't understand" loop"

### ISSUE THREAD

**Issue by ziggy42** [Microsoft/BotBuilder#1190]
I've done something like this:
```
const list = []
builder.Prompts.choice(session, "some text", list)
```
And now everything I send to the bot it responds to me that I have to choose an option from the list. But the list didn't have any options, so what do I do?
I've tried calling `endDialog` in some places and other weird stuff but didn't help.

**Comment by muzahmed** [comment]
@ziggy42 good find! I've got a fix ready, should be available in our next release!
