### ISSUE TITLE
Optional field not working with custom Validation

### ISSUE THREAD

**Issue by gsegares** [Microsoft/BotBuilder#1192]
I have issues making a field Optional (using the annotation). I'm using FormFlow and I when I build the form I add a custom validation to the field, just to add some extra logic if the field has a value, but the bot keeps prompting for the field if no value is provided. If I remove my custom validator then the Optional works as expected but I really need to have both in my implementation.
<img width="667" alt="screen shot 2016-09-07 at 4 39 44 pm" src="https://cloud.githubusercontent.com/assets/2272565/18332167/39bf58ba-7519-11e6-94b9-57721eea03d3.png">

How can I make the Optional and the validator work together?

**Comment by chrimc62** [comment]
This seems to work fine on the current release if you return new ValidateResult() { IsValid = true} from your field validation.
