### ISSUE TITLE
Get conversation ID of newly created conversation in Node

### ISSUE THREAD

**Issue by Thegaram** [Microsoft/BotBuilder#1193]
In the Node.js SDK conversation creation is hidden; if the conversation for the message passed to `UniversalBot.send` does not exist (i.e. `message.address.conversation` is undefined), the SDK creates it first. In this case, is there a way to get the conversation ID of that newly created conversation?

My use case: Proactive messages. I know the address of the user I'd like to contact. At first, I'd like to create a new conversation and then I'd like to use that conversation for subsequent messages (without the need to receive a message from that user).

If this is not possible, let's start a discussion whether this feature might be useful. It could be implemented for example by passing the conversation ID as a new parameter to the `done` callback passed to `UniversalBot.send`.

**Comment by muzahmed** [comment]
@Thegaram You can call bot.send multiple times and it should deliver the message to the user on the same conversation (it handles this under the scenes for you!). Let me know if you're not seeing that behavior, and we can re-open this issue.

**Comment by Thegaram** [comment]
@muzahmed Wait, how does it know if I want to create a new conversation or use an existing one? Isn't it overly restrictive if we limit the developer to one conversation per user?

**Comment by jameslew** [comment]
If you want to create a new conversation, just delete the Conversation property on the message before sending a new one and the Builder will create new on the fly.

**Comment by Thegaram** [comment]
@jameslew You mean delete `message.address.conversation`? (We're talking Node.js here.)

So my scenario is this. I have the address of a user on a channel:

```js
var address = {
    channelId: 'channelId',
    user: {
        id: 'userChannelId'
    },
    bot: {
        id: 'botChannelId'
    },
    serviceUrl: 'serviceUrl',
    useAuth: true
};
```

At one point I create a message object with this address and send it to this user using `UniversalBot.send`. This method will take care of creating a new conversation. Let's say the conversation ID of this new conversation is `abcd1234`.

At some point later, I send a message again using the same address.

a) According to @muzahmed, if I use the same address object (i.e. don't specify `address.conversation`), the SDK will send the message to the conversation `abcd1234` automatically.

b) According to @jameslew, if I omit the `conversation`  property, the SDK will create a new conversation on the fly.

Which one is the case for the Node.js SDK? If the latter, then I do need to gain access to the new conversation ID (`abcd1234`) if I would like to send subsequent messages to the same conversation. If the former, is it a design decision to limit the developer to one conversation per user? (I realize most channels don't allow multiple conversations with the same user but this might not be true for all of them.)

**Comment by jameslew** [comment]
Tagging in @Stevenic to correct me but if I read correctly, a and b are not mutually exclusive.  You can re-use an existing conversation id if you wish to continue a conversation, or clear the conversation id if you want to get a new one (then cache and re-use it when the user responds to you).  That would allow essentially (n) conversations with the user.  Whether that actually is supported by any channels is as you say a different question.

**Comment by Stevenic** [comment]
Sorry for the late reply...

@Thegaram  try using `bot.beginDialog()` instead. It we'll create a new `conversationId` just like `send()` does but you'll be able to save the address object with the new conversationId within your dialog handler.

**Comment by Thegaram** [comment]
@Stevenic Thanks!
