### ISSUE TITLE
Delete user profile on redeploy

### ISSUE THREAD

**Issue by dbondarchuk** [Microsoft/BotBuilder#1194]
Hi guys!
I had a trouble when changed a flow in my bot (from FormFlow to Dialog): when i deployed my bot Azure, old users had the old flow. Only sending '/deleteprofile' resolved problem for them.
How can I reset sessions, when new changes are deployed to prod?

**Comment by palmerabollo** [comment]
You could use [`Middleware.dialogVersion`](https://docs.botframework.com/en-us/node/builder/chat-reference/classes/_botbuilder_d_.middleware.html#dialogversion). This middleware manages the versioning of your dialogs. You can specify a version so major version increments in new deployments result in existing conversations between the bot and user being restarted.

```js
var dialogVersionOptions = {
    version: 1.0,
    message: 'Bot update. Your conversation has been restarted.',
    resetCommand: /^reset/i
};
bot.use(BotBuilder.Middleware.dialogVersion(dialogVersionOptions));
```

**Comment by dbondarchuk** [comment]
Is there such case for C# SDK?

**Comment by jameslew** [comment]
There isn't currently such a feature for the C# SDK, but as we drive towards parity we'll be closing up the gaps between the SDK's.  I'll make sure this is on that list.  In the mean time you can use deleteprofile .

**Comment by dbondarchuk** [comment]
Thanks!

**Comment by msft-shahins** [comment]
C# SDK adds `deleteprofile` scorable by default to dialog module: https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Dialogs/DialogModule.cs#L166. This means that user can type `/deleteprofile` to reset all the contextual stores at anytime. Adding a versioning middleware is in our backlog.
