### ISSUE TITLE
how to get "conversationId"  for sending skype message

### ISSUE THREAD

**Issue by shijuamt** [Microsoft/BotBuilder#1196]
How to get conversationId for skype user for sending skype message

**Comment by jameslew** [comment]
Hi Shijuamt,

Which API are you using?  If you're using the C# SDK there are CreateConversation and CreateDirectConversation methods that will give you an id to use in subsequent calls.  Read here for more detail:  https://docs.botframework.com/en-us/csharp/builder/sdkreference/routing.html

**Comment by palmerabollo** [comment]
@jameslew what is the equivalent to CreateConversation and CreateDirectConversation in the NodeJS SDK?

**Comment by Thegaram** [comment]
@palmerabollo I believe this is hidden in the Node.js SDK. If you don't specify `message.address.conversation`, the SDK will automatically create a new conversation for you. (See `Universalbot.ensureConversation`)

This is somewhat related: #1193

**Comment by muzahmed** [comment]
@Thegaram yup, thats correct -- thanks!

@palmerabollo let us know if you have further questions/issues -- closing this for now.

**Comment by josejohny** [comment]
is there any possible way to get skype bot id ?

**Comment by TrashCoder96** [comment]
somebody help with getting conversations id by REST Skype API?

**Comment by annstriganova** [comment]
@TrashCoder96 have the same question and spent a lot of time to find the answer, but unsuccessful. The only thing I found out: It's possible to obtain conversationId by sending `/get name` to specified chat, answer will be like this: `name=19:6bdf98504....9@thread.skype`

P. S. `/get name` is unavailable on Skype for Linux Beta
