### ISSUE TITLE
[Node.js] session.reset() doesn't seem to work

### ISSUE THREAD

**Issue by ziggy42** [Microsoft/BotBuilder#1197]
So here's my code:
```
const firstRun = [
    session => 
        builder.Prompts.text(session, session.userData.reask ? "a message" : "another message"),
    (session, results) => {
        const submittedValue = results.response
        if (isValidValue(submittedValue)) {
            builder.Prompts.confirm(session, "some text")
        } else {
            session.send("some text")
            session.userData.reask = true
            session.reset("/firstRun")
        }
    },
    (session, results) => {
        if (results.response)
            session.beginDialog("/otherDialog")
        else {
            session.userData.reask = true
            session.beginDialog("/firstRun")
        }
    }
]
```

If I call reset it doesn't work as I thought it would, because after the child /firstRun dialog is completed, the parent is resumed.
So, what's the proper way to "restart" a dialog?

**Comment by muzahmed** [comment]
@ziggy42 use i think for your case, you want to use session.replaceDialog dialog instead

here's an example with breaking out the prompt into its own dialog:

`bot.dialog('/', [
    function (session) {
        session.beginDialog('/question');
    },
    function (session, results) {
        // child response here
        session.send("done" + results.r);
    }
]);

bot.dialog('/question', [function(session) {
    builder.Prompts.confirm(session, "proceed");
},  function(session, results) {
    if (results.response) {
        session.endDialogWithResult({r: results.response});
    } else {
        session.replaceDialog('/question');
    }
}]);`
