### ISSUE TITLE
NodeJS FormFlow?

### ISSUE THREAD

**Issue by xumx** [Microsoft/BotBuilder#120]
Is there a NodeJS version of FormFlow dialog?

**Comment by Stevenic** [comment]
Not yet but we're evaluating how to add the Node equivalent.

**Comment by Stevenic** [comment]
Moving to UserVoice:

https://feedback.botframework.com/forums/354222-bot-builder-sdk/suggestions/13463400--nodejs-formflow

**Comment by maba4891** [comment]
Any news on this issue? The user interface of selection forms in NodeJS is cumbersome at this point

**Comment by Stevenic** [comment]
We've learned a lot since doing form flow for C#. We're thinking about what makes sense for a Form Flow 2.0 that would cover both Node and C#.  Can ask specifics about what you find cumbersome with collecting form input in Node?  I agree that collecting form data could be easier in Node but I'm more curious about your thoughts for how it could be made simpler?  

Take a look at [this sample](https://github.com/Microsoft/BotBuilder/blob/master/Node/examples/basics-loops/app.js), it shows how to create a dialog that asks a series of questions and returns a JSON object with the answers.  Form Flow is a lot more than that but my question is how far does that get you towards what you want?

**Comment by vindhya2505** [comment]
hello stevenic, is there any update on the node js version of form flow?

**Comment by Stevenic** [comment]
Nothing planned quite as of yet. Things are changing rapidly so we're evaluating several alternatives to form flow as it currently exists.

**Comment by maba4891** [comment]
What I am currently missing in Node is a nice way to let users choose between different options. When I use 
`builder.Prompts.choice(session, "What language do you code Node using?", ["JavaScript", "CoffeeScript", "TypeScript"]);`
in Node I get a simple, non-clickable list: 1. JavaScript 2. CoffeeScript 3. TypeScript

In C# these choice items are nicely formatted an clickable, which makes it much easier to use.

Not sure if this has anything to do with FormFlow but this is a feature that I would love to see in Node (or am I missing something?) ;)

**Comment by dgkanatsios** [comment]
Just published a small library that does this, check [here](https://dgkanatsios.com/2017/03/21/formflow-for-microsoft-node-js-botbuilder-sdk/)

**Comment by kumarvikramaditya1** [comment]
Are there any updates yet ? Is it even in the roadmap ? The nodejs version would really help.

**Comment by GeetaKrishna** [comment]
Guys, I don't know if it will help. I started working using an NPM module.
https://www.npmjs.com/package/botbuilder-formflow

**Comment by profbiyi** [comment]
Any update on form flow for Nodejs?

@dgkanatsios is there a way to display all user's entries and allow them to make changes to a single or more form entry like we have in the .NET version?

**Comment by dgkanatsios** [comment]
@profbiyi not sure I follow the question (it's been over a year since I wrote it), but in the sample code (https://github.com/dgkanatsios/formflowbotbuilder/blob/master/README.md) there is this:
```javascript
 // responses from the user are in results variable as well as in the responses callback argument
        session.send('results: ' + JSON.stringify(responses));
```
I suppose you are looking for something different?

**Comment by profbiyi** [comment]
@dgkanatsios thanks for the prompt response. It's actually working fine, but not doing the C# formflow thing I am looking at.

I don't just want a display of the result, I want a case where users can confirm all their entries and even gets to change a single or more entry like in the C# Formflow.

Thanks once again
