### ISSUE TITLE
Stateless scaling

### ISSUE THREAD

**Issue by ubreddy** [Microsoft/BotBuilder#1200]
Bot Storage System. is this machine dependent ? if yes, how do we scale users across multiple machines? is there stickiness involved? 

session.userData is stored in the storage system and retrieved based on storageCtx.  will this be available if I have multiple servers hosting the bot for scaling purposes?

if not, is statelessness guaranteed?

**Comment by willportnoy** [comment]
You might be interested in this faq:
https://docs.botframework.com/en-us/technical-faq/#where-is-conversation-state-stored

I assume you're asking about the Bot State service?  It's a remote service so it's available from multiple machines.  It uses etags for resolving concurrency concerns:
https://docs.botframework.com/en-us/technical-faq/#what-is-an-etag--how-does-it-relate-to-bot-data-bag-storage

Your bot web service is stateless as long as you don't add any additional state not tracking in the conversation, user, private, or dialog data bags.

**Comment by ubreddy** [comment]
Thank you. This answers my question.
