### ISSUE TITLE
FormBuilderJson nested dialogs

### ISSUE THREAD

**Issue by FordSoft** [Microsoft/BotBuilder#1203]
Hello, 

How can I organize nested dialogs and transitions between the dialogue (from parent to child) I use JSON scheme and class FormBuilderJson.

When I use it

```
...
"properties": {
    "Ingredients": { //it is not a nested dialog, but would like to get through to FormBuilderJson, he was treated as a nested dialog at the end of the dialogue with the transition to the parent. Is that possible?

          "type": "object",
          "required": [ "Bread" ],
           "properties": {
                 ...
           }
   }
}
...
```
, It turns out that I'm going through all the attached property does not mean that this new dialogue.

**Comment by chrimc62** [comment]
I don't understand your question.  FormFlow works across the whole structure which can include nested complex objects.  FormFlow does not though support things like an array of complex objects.  It would be great to add that and you should add it to user voice if that is what you are looking for.

**Comment by FordSoft** [comment]
Thanks for the answer, the question is closed. I made the transitions between dialogue manually.
