### ISSUE TITLE
Not able to send '_' in hero card title in telegram

### ISSUE THREAD

**Issue by somprabhsharma** [Microsoft/BotBuilder#1204]
I am getting below error if I try to send '_' in title of hero card.

`{"ok":false,"error_code":400,"description":"Bad Request: Can't parse message text: Can't find end of the entity starting at byte offset 0"}`

It is compulsory for me to send underscore or any other special character in the title as per my need. So I can not remove the '_' from title.

While if I send '_' in simple session.send() then it let me send it and I get no error.

**Comment by jameslew** [comment]
The error you're reporting is the error we're getting back from telegram when sending your card to the service, we're passing it along.  The _ is a special character in markdown (for italics) so it's possible it's being handled specially.

Two requests:

1) try setting the message TextFormat to "plain"
2) Post the code or JSON here so we can try to repro

Thanks!

**Comment by jameslew** [comment]
If those steps didn't work, please raise another issue, closing this item as it hasn't had any activity.

**Comment by slidenerd** [comment]
so how do you set the text format to plain if you are on node.js? any examples

**Comment by eanders-MS** [comment]
Hi @slidenerd, use the `textFormat` accessor:
```javascript
bot.dialog('/', (session) => {
    const msg = new builder.Message(session)
        .textFormat('plain')
        .text("*Hello*");
    session.send(msg);
});
```

**Comment by eanders-MS** [comment]
Tracking this internally. Closing issue.
