### ISSUE TITLE
Add Powershell as integrated terminal in VSC for Windows? [Feature Request]

### ISSUE THREAD

**Issue by saifali96** [Microsoft/BotBuilder#1205]
Guys I love the work you people are doing! Just make it more lovable by adding/allowing Powershell in integrated terminals.

**Comment by jameslew** [comment]
Is this related to Bot Framework/BotBuilder?  If so, can you clarify your ask?  Otherwise maybe you hit the wrong forum?

**Comment by saifali96** [comment]
Woah! Sorry had two tabs open! I'm using VSC to code the bot in Node through BFW!
Sorry! :)
