### ISSUE TITLE
bot.use / Logging Node.js

### ISSUE THREAD

**Issue by VishalWaman** [Microsoft/BotBuilder#1206]
@Stevenic 

How can we have a common place where i can log all My Incoming/ outgoing Messages

We need to log all Incoming and Outgoing messages
Message text + UserID

As of now i am able to capture all incoming messages by "bot.use"..

Not sure how can we get outgoing messages

**Comment by muzahmed** [comment]
@VishalWaman try this:

```
bot.use({
    receive: function (event, next) {
        console.log("rec", event);
        next();
    }, 
    send: function (event, next) {
        console.log("snd", event);
        next();
    }
});
```

closing for now, let me know if you have any further trouble and we'll re-open!
