### ISSUE TITLE
HeroCard and Carousel layout not working web channel

### ISSUE THREAD

**Issue by ubreddy** [Microsoft/BotBuilder#1210]
I am using Skype Demo on web channel.

hero card is being displayed without buttons.
![image](https://cloud.githubusercontent.com/assets/2233628/18422756/422b84dc-78bc-11e6-913e-a4e72ca6489b.png)

Carousel layout is being displayed as below... 
![image](https://cloud.githubusercontent.com/assets/2233628/18422773/6a242106-78bc-11e6-84ed-b5566c8d893b.png) and one after then other...

**Comment by dandriscoll** [comment]
Hi @ubreddy, the web chat control does not support cards. The next version will support them.

**Comment by ubreddy** [comment]
Thanks @dandriscoll. Any idea on how soon that would be?

Plus is it possible to customise the styling including the inner controls in next release?

**Comment by dandriscoll** [comment]
I don't have specifics to share but styling is definitely something we're working on.

**Comment by slidenerd** [comment]
in the meantime ubreddy, for the web chat, you can probably add a check to see if the source is a webclient and invoke a special method that converts your json template with data into a renderable css block with the same effect 💃

**Comment by dandriscoll** [comment]
The new version of the web chat control is available, and now supports cards.

**Comment by sandeepshm** [comment]
Is it possible to have custom stylesheet on hero card button's in Microsoft bot framework.

**Comment by dandriscoll** [comment]
Hi @sandeepshm, you can customize the control by forking the BotFramework-WebChat repo and modifying it.

https://github.com/Microsoft/BotFramework-WebChat
