### ISSUE TITLE
Getting 401 unauthorised response 

### ISSUE THREAD

**Issue by pandubalraj** [Microsoft/BotBuilder#1211]
Hi,
I have created a bot application using NodeJS SDK. 
I deploy the application in azure with default azure url http://tschatterbot.azurewebsites.net.
And the url is working fine with https://tschatterbot.azurewebsites.net with **HTTPS**

I am getting "Accepted" response from the Test connection to you bot in https://dev.botframework.com page.

When I embed the code in web chat. I am not getting any response. I gave the correct secret and code.

I tried to get the response from the emulator using ngrok. I am getting 401 unathorized in the emulator. Please find the attached image.

Thanks in advance for your valuable solution.

![emulator](https://cloud.githubusercontent.com/assets/1173047/18426266/e07af836-78dd-11e6-9c60-f8743cd54ff2.png)

**Comment by inornos** [comment]
Same Problem Facing in C# When sending some request in Emulator It not wrking and giving error like 401 Unauthorised Please help
![image](https://cloud.githubusercontent.com/assets/14770190/18434858/a1f45ca8-78a4-11e6-9359-3594ad687a93.png)

**Comment by dandriscoll** [comment]
Hi @pandubalraj, and @inornos, have you followed the steps in the auth troubleshooting guide, and specifically the instructions in Step 2?

https://docs.botframework.com/en-us/support/troubleshooting-bot-framework-authentication/

**Comment by pandubalraj** [comment]
Hi @dandriscoll,

Thanks for your step. I have rectified the issue. The issue occurs due to invalid Microsoft APP ID & APP Password. I have created a new one and the issue is resolved by giving the proper endpoint url with proper 'https' url. 

@inornos, please check your app id and password and its configuration in the C#. I hope that will rectify your problem.

**Comment by inornos** [comment]
Now it running on in my local machine But when i publish project on my domain it not working its giving me this error **

> Could not load file or assembly 'stdole' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)

**

![image](https://cloud.githubusercontent.com/assets/14770190/18474892/20475c66-7979-11e6-9f59-1b14e480939c.png)

**Comment by Chetanchezz** [comment]
Hi @dandriscoll .My bot works fine in the emulator,even with Microsoft app id and password but when I'm testing it at https://dev.botframework.com i get a message "couldn't send message retry".I get a 401 unauthorized error when I'm trying to get a reply from the emulator with bot url https://botwebdeployment.azurewebsites.net/ (deployed in azure).I have added my bot  in microsoft bot directory and have enabled skype .But even on my machine i can send message on skype app to bot but i don't get any reply.
![401](https://user-images.githubusercontent.com/18398086/28492708-b5fb7862-6f25-11e7-8785-f6ff7eaf0569.JPG)
![error1](https://user-images.githubusercontent.com/18398086/28492720-f3db6778-6f25-11e7-9fbc-b23ac3bbfd40.JPG)

**Comment by nicksav** [comment]
Very strange, but started having the same issue. Any help?

**Comment by Cley-94** [comment]
Same issue here @Chetanchezz.

**Comment by iantje31** [comment]
Same issue @Chetanchezz @nicksav

**Comment by EricDahlvang** [comment]
This is a closed issue.  Please open a new issue on the repository for the sdk you are using, or ask a question on StackOverflow:
https://stackoverflow.com/questions/tagged/botframework
https://github.com/Microsoft/botbuilder-js
https://github.com/Microsoft/botbuilder-dotnet
