### ISSUE TITLE
getting input from bot if it posts message twice

### ISSUE THREAD

**Issue by ranjan-ranjan** [Microsoft/BotBuilder#1213]
I am doing unit testing on a bot made by me and I am following https://github.com/Microsoft/BotBuilder/tree/master/CSharp/Tests/Microsoft.Bot.Sample.Tests
The problem I am getting is when the bot is doing `await context.PostAsync("string");` twice. how do I do `Assert.IsTrue(toUser.Text.ToLower().Equals("string"));` ? Kindly help by giving example.

**Comment by msft-shahins** [comment]
You can use the BotToUserQueue as the IBotToUser implementation: https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Tests/Microsoft.Bot.Builder.Tests/DialogTestBase.cs#L99

This causes all of the messages from bot to user to be queued in the queue you pass to the BotToUserQueue: 
https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Tests/Microsoft.Bot.Builder.Tests/DialogTestBase.cs#L85

Then after each message, you can dequeue all message and do your assertion: https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Tests/Microsoft.Bot.Builder.Tests/DialogTestBase.cs#L164
