### ISSUE TITLE
[Feature Request] Go Lang Support

### ISSUE THREAD

**Issue by cristianchaparroa** [Microsoft/BotBuilder#1214]
Hi, are there some plans to implement a `BotBuilder` support for `Go Lang` ?

**Comment by jameslew** [comment]
At the current time we're focusing on the Node & .Net SDK's and making them the best they can be for building great bots.  We're always looking for feedback though, I'll increment the count on the feature request for GoLang support.

**Comment by stevengum** [comment]
Reopening for tracking.

**Comment by sgellock** [comment]
If Azure decides this is a supported language across the platform, then we will fall inline and support adding another language

**Comment by sgellock** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botbuilder-channels/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team

**Comment by sgellock** [comment]
Thanks for raising this.  As I look at our product roadmap, I believe we will deliver Python and Java SDKs before we consider Go support.

**Comment by tiger5226** [comment]
shame...was going to build a bot but, no go support.

**Comment by PrasadG193** [comment]
@sgellock is there any plan to support Go Lang in the future releases?

**Comment by sgellock** [comment]
@PrasadG193 Unfortunately, we do not have the Go language SDK work planned at this time.

**Comment by ylluminate** [comment]
What is stopping it @sgellock?

**Comment by sgellock** [comment]
customer interest hasn't been strong.  it's not been zero, but we haven't had the level of customer interest that has caused a priority change for us.

**Comment by tiger5226** [comment]
How can we as customers make our interests known via the proper channels?

**Comment by PrasadG193** [comment]
Hi folks,
We have started developing unofficial Bot Framework SDKs for Go (as we need this on priority for [BotKube](https://www.botkube.io)). Any PRs, feedback or reviews are welcome.

https://github.com/infracloudio/msbotbuilder-go
