### ISSUE TITLE
Feature request: add a unique session identifier

### ISSUE THREAD

**Issue by palmerabollo** [Microsoft/BotBuilder#1216]
It would be interesting to add a unique id to each `Session`. That way we could track sessions in logs, etc. As I workaround, I currently have a middleware (nodejs) that adds a `sessionId` field to `session.conversationData`, but I think it's not a good enough solution.

The new session id could be a field on its own or a field in the existing `session.sessionState`.

**Comment by jameslew** [comment]
Currently we have the Conversation Id and the Activity ID.  The definition of Session though is variable and therefore we've left it up to the developer to define.  Is it defined by gaps in the conversation, or a completed transaction of some part, etc?

**Comment by palmerabollo** [comment]
You are right, the current `session.message.address.conversation.id` sounds good.
