### ISSUE TITLE
Is there a way to lookup bot's slack user id without session?

### ISSUE THREAD

**Issue by onikiri2007** [Microsoft/BotBuilder#1218]
Hi,
I'm trying to use the Slack's Event api to receive the event from slack and I'd like to send the message when event has been received via ChatConnector however since I don't have a session I won't know the bot's slack user id to create the address object.

Is there a method to retrieve bot's slack user id based on the team id?

**Comment by jameslew** [comment]
We don't have that particular method, but it should be attached to the recipient field of any incoming message to the Bot.  There may be additional data in the ChannelData field you can use.

**Comment by craigjensen** [comment]
We don't yet support Slack's new Events api but are looking into adding support in the future.  I may not be understanding your question correctly, but it sounds like you are planning on implementing your own Events based integration with Slack.  Is there a reason you can't use our current message-based Slack integration?  That will provide you with all the context you need to send replies.

**Comment by onikiri2007** [comment]
HI,
So I was trying to implement similar scenario like one in here https://github.com/Microsoft/BotBuilder/issues/1181 via Slack event api.
However I can't send the message to the user via bot since I don't have the bot user id.

**Comment by dandriscoll** [comment]
Hi @onikiri2007, you should have the bot's Slack ID in the activity.From.Id field. Can you see if this is the ID you're looking for?

**Comment by jameslew** [comment]
Given lack of activity, I'm assuming your request has been resolved and am closing the issue.  Thanks!
