### ISSUE TITLE
[Question] Finding conversations / users

### ISSUE THREAD

**Issue by remms** [Microsoft/BotBuilder#1219]
Hello,
My objective is to create a proactive conversation knowing only user or slack channel alias;
Does it bridge the API for extra channel features, for example: List of users from a Slack team, so that I can find the id for the user? 

Thanks,
Renato

**Comment by craigjensen** [comment]
Slack messages now contain the Api token in ChannelData that you can use to make direct calls to the Slack Api.  The [users.list](https://api.slack.com/methods/users.list) method will get you all users in the team, etc.
