### ISSUE TITLE
Support for Facebook bots

### ISSUE THREAD

**Issue by wbreza** [Microsoft/BotBuilder#122]
What is the plan for Facebook bot support?

**Comment by ignatandrei** [comment]
please see https://developers.facebook.com/docs/messenger-platform/quickstart    - I hope it should not be so difficult

**Comment by wbreza** [comment]
I agree.  Just asking if it will soon be supported as a first class connector like slack,  Skype,  etc.

**Comment by Stevenic** [comment]
Merged with existing UserVoice request for voting purposes:

https://feedback.botframework.com/forums/354219-bot-connector/suggestions/13398783-will-support-be-added-for-newly-released-fb-messen
