### ISSUE TITLE
Hot to show a 'typing bubble' & send 'messages with a delay' to the end-user

### ISSUE THREAD

**Issue by afficionaddo** [Microsoft/BotBuilder#1221]
Hi, 
1. While I am fetching data from DB, I want to show a 'typing bubble' to the user.
So how to implement this please suggest.

2. How to send messages with a bit of delay so that it feels more of a human chat?

**Comment by jameslew** [comment]
@afficionado, depending on what channel you use, you can use the "typing" ActivityType to communicate to the user that you're typing.  Which channel are you working on?

**Comment by afficionaddo** [comment]
Facebook messenger.

**Comment by dandriscoll** [comment]
Hi @afficionaddo, please use the Typing activity to send this notification.
