### ISSUE TITLE
Conversation state persisted when using emulator (Node)

### ISSUE THREAD

**Issue by letmaik** [Microsoft/BotBuilder#1222]
(continuation from https://github.com/Microsoft/BotBuilder/issues/987#issuecomment-246407137)

The [Bot Framework docs](https://docs.botframework.com/en-us/technical-faq/#where-is-conversation-state-stored) say the following:

> The Bot Framework Emulator provides an in-memory implementation of this interface for debugging your bot. This data expires when the emulator process exits.

When I restart the bot application and use the bot framework emulator then I am still in the same dialog step. This means that it is not using the in-memory storage. How is this possible? Where is it storing the data?

I use the Node version of the bot framework and run the bot locally (with App ID and password set to null) as a simple express-based server (no ngrok or anything like that).

**Comment by ejadib** [comment]
@letmaik Are you also closing the emulator?

**Comment by letmaik** [comment]
I did not, and in fact this resets the conversation. But still, which part is actually saving the conversation state and where if I don't restart the emulator?

**Comment by jameslew** [comment]
@letmaik the emulator provides an implementation of the client state API (in memory in the emulator).  When you restart your bot app and make a new request, if the emulator is still running it will continue to have the state storage available for the bot.

**Comment by letmaik** [comment]
Ah I see, that makes sense. I think I was a bit confused that there was a MemoryBotStorage implementation in the botbuilder library, but this is probably used for the console bot, right?

**Comment by willportnoy** [comment]
@letmaik I believe that's accurate that MemoryBotStorage is used for the console bot.

**Comment by dandriscoll** [comment]
Please feel free to open a new issue if you have additional questions.

**Comment by mageshpurpleslate** [comment]
Hi,

I found the same behaviour with Facebook messenger as well. Does it mean FB messenger also has client state API implemented?

**Comment by willportnoy** [comment]
The state service is a separate service from the channel connector services.

**Comment by mageshpurpleslate** [comment]
Yes. Realised that. We wanted to capture some information from the incoming conversation and pass it on to outgoing conversation. Written that in the send and receive middlewares. We are passing that information around, by setting a property. Is this fine ?

**Comment by willportnoy** [comment]
That seems reasonable, to use a property to store information across send and receive middleware invocations, assuming you're attaching the property to something with the appropriate lifetime scope.
