### ISSUE TITLE
Could not load file or assembly 'stdole' or one of its dependencies

### ISSUE THREAD

**Issue by inornos** [Microsoft/BotBuilder#1223]
My Bot Not Working Because of this error after publish on my domain **Could not load file or assembly 'stdole' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)**

Please help

![image](https://cloud.githubusercontent.com/assets/14770190/18474790/ab074a6a-7978-11e6-88cc-11e965cd1925.png)

**Comment by willportnoy** [comment]
I don't believe the Bot Framework has a "stdole.dll" file, but if you want to prevent ASP.NET from opening the file while compiling the contents of the bin directory, you can use a solution like this (different cause, possibly the same solution):

http://blog.willportnoy.com/2011/07/badimageformatexception-with-aspnet-and.html

**Comment by dandriscoll** [comment]
You can also use the Fusion log to get more detail on assembly load errors. https://msdn.microsoft.com/en-us/library/e74a18c4(v=vs.110).aspx

**Comment by dandriscoll** [comment]
Closing this as it's not really related to the Bot Framework. There are some suggestions above but since it's not our area of expertise, I don't think we'll be able to help much past that. Please open a new issue if you find there is something specific to Bot Framework we need to address. Thanks
