### ISSUE TITLE
BotData.SetProperty throws if value is null; null is a valid and meaningful value that I would like to store.

### ISSUE THREAD

**Issue by BrainSlugs83** [Microsoft/BotBuilder#1227]
Currently, there's no way to unset a reference type value (i.e. put it back to `null`), and in my bot, this is something that I would like to be able to do.

Further, `null` is a meaningful value, and it's very common for a developer to want to store it in a property bag, etc. (and it has a different meaning that is separate from `string.Empty`, etc.)

Here is some sample code that triggers the issue:

```
// Unset 'Foo' and 'Bar'
userData.SetProperty<MyClass>("Foo", null);
userData.SetProperty<string>("Bar", null);
```

**Comment by willportnoy** [comment]
How about RemoveValue for unsetting a value?

https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Dialogs/IBotDataBag.cs#L73

**Comment by dandriscoll** [comment]
Hi @BrainSlugs83, this looks like a valid issue -- I'm seeing the same thing. Even with the other accessor, SetProperty should let you clear a value. (Or we should have a ClearProperty call.)

**Comment by dandriscoll** [comment]
Fixed in https://github.com/Microsoft/BotBuilder/commit/dbd6e82c6c68e6bfecd76e325a28ad61d6700085 and will be included in the next SDK release.

**Comment by BrainSlugs83** [comment]
Awesome!
