### ISSUE TITLE
ChatConnector.send does not go through 'send' middleware.

### ISSUE THREAD

**Issue by strangecyan** [Microsoft/BotBuilder#1228]
A proactive message sent via ChatConnector.send does not go through the 'send' middleware. Is this intended behaviour?

**Comment by Stevenic** [comment]
Sorry for the delay... Yes... The middleware pipeline is driven by the `UniversalBot` class. You should be calling `bot.send()` if you want middleware run.  The connector is just that... A raw connector. What are you trying to do?
