### ISSUE TITLE
How can I check if the message got delivered to user or not?

### ISSUE THREAD

**Issue by somprabhsharma** [Microsoft/BotBuilder#1229]
I want to check if the message sent by bot to user got delivered or not so that I can resend the message in case of non delivery. Is there any way to check this ?

**Comment by dandriscoll** [comment]
Hi @somprabhsharma, most of the platforms we connect to guarantee delivery within the system as long as your POST to the Bot Connector service was accepted.

However, most systems do not guarantee delivery to a particular user. The user may uninstall the app and never see the message.

In most cases, though, a successful POST means the message will be made available to clients. The only exception I can think of is email, where a failure may occur long after the message is sent. (However, your bot will likely get a bounce message reply.)

**Comment by dandriscoll** [comment]
Please feel free to open a new issue if you have further questions.
