### ISSUE TITLE
sample tests where response is coming from https://www.luis.ai/

### ISSUE THREAD

**Issue by ranjan-ranjan** [Microsoft/BotBuilder#1230]
What are these test for https://github.com/Microsoft/BotBuilder/tree/master/CSharp/Tests/Microsoft.Bot.Sample.Tests?

1) To test Bot Framework, or

2) To test the bot that I have created.

I am asking this because `SetupLuis` is used in `SimpleAlarmBotTests.cs`, which is a method of `LuisTestBase` class. And the parameter to `SetupLuis` is `SetupLuis<SimpleAlarmDialog>(luis, a => a.SetAlarm(null, null), 1.0, entityTitle, entityDate, entityTime);`. So this is pretty much obvious that we are not sending the request to [LUIS: Language Understanding Intelligent Service (beta)](http://luis.ai/) and the request and response is being mocked. Its like testing 2 + 2 = 4. Kindly explain.

**Comment by willportnoy** [comment]
Those tests are to validate that the alarm sample works properly, not to check anything about the LUIS service.  It's good practice to mock external dependencies so that the unit tests can run quickly without non-deterministic failures due to network conditions, etc.
