### ISSUE TITLE
Bot is not working as expected.

### ISSUE THREAD

**Issue by rehtinavelmoorthy** [Microsoft/BotBuilder#1231]
I am developing one chat bot using Microsoft Bot Framework in NodeJs. Most of the time it works perfectly as expected. But sometimes when I am communicating with the bot, I'm not getting the response immediately. After entering the second question it is responding both the questions continuously. Help me to fix this issue. Should I do something on the server side?

**Comment by dandriscoll** [comment]
Hi @rehtinavelmoorthy, which channel are you using?

**Comment by dandriscoll** [comment]
If you're using web chat, we have an open bug that should be fixed sometime in the upcoming week.

**Comment by rehtinavelmoorthy** [comment]
Yes. I am using web chat and thanks for the info.

**Comment by rehtinavelmoorthy** [comment]
Kindly update once the issue has been fixed. 
Thanks!

**Comment by rehtinavelmoorthy** [comment]
Is this issue got any updates for fixes?

**Comment by dandriscoll** [comment]
Yes, the fix was pushed out yesterday. Please force-reload the control and try again -- can you let me know if you still see the issue?

**Comment by Andrea-Orimoto** [comment]
Fix should be out, closing this issue. If you're still experiencing the problem, please reopen. Thanks!
