### ISSUE TITLE
Question: How to Allow Third Party Systems change the bot state for a specific user

### ISSUE THREAD

**Issue by ernanirst** [Microsoft/BotBuilder#1232]
Hey guys, I'm having trouble to think about a scenario with Bot Framework.

Let's say I need my customer to pay for a product, because I'm using facebook I will probably have to get the user to another page/app so he/she can pay for it.
But, once the customer payed, how do I notify my bot that the user has paid? Well, I'm using restify, so the way would be create an endpoint that receive a HTTP message from my system that changes the state of the bot for that specific customer.
So here is the real question, how do I make external systems change the bot state for a specific user?

Is there a proper way of doing it? Is there any example on the documentation that I'm missing?

**Comment by willportnoy** [comment]
You could modify the bot's data bags through the bot state client:
https://github.com/Microsoft/BotBuilder/blob/aaf86d7b0542c8e2758bf14baa6b7cc67291e390/CSharp/Library/Microsoft.Bot.Connector/StateAPI/IStateClient.cs

or you might choose to model it as an external event - e.g. here is an example in C#:
https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Samples/AlarmBot/Models/ExternalEvent.cs#L29

**Comment by ernanirst** [comment]
Sorry, I forgot to mention I'm using NodeJS. Do you know if there is any equivalent on Node?

**Comment by willportnoy** [comment]
https://github.com/Microsoft/BotBuilder/blob/c00c529c008a3149cccc22f47a244deeee88be77/Node/core/src/bots/ChatConnector.ts implements https://github.com/Microsoft/BotBuilder/blob/c4dbb7183cc1c23837b6d6c8bc03fe8c54ba1f55/Node/calling/src/storage/BotStorage.ts#L50 - maybe that can be used separately?

**Comment by ernanirst** [comment]
I don't think so, since `IBotStorage` is an interface, it can't work alone. But even if I can, I'm not sure what would be the point. Create a ChatConnector from an existing storage?

**Comment by dandriscoll** [comment]
Hi @ernanirst, the ChatConnector class does indeed connect to the Bot Framework's default Bot State implementation. You can see the default endpoints configured in the constructor. You just have to supply your credentials and the object will allow you to issue getData and saveData calls to manipulate your bot's data.

**Comment by ernanirst** [comment]
Ok, I will try that, thanks @dandriscoll and @willportnoy

**Comment by ernanirst** [comment]
Sorry to come with this again but I kept stuck. For now, what I was able to do is serialize the address of a particular user and later use this address to build a message and send to the user, something like this:
```
sendTextMessage: function(address, text){
    var msg = new builder.Message();
    msg.address(address);
    msg.text(text);
    bot.send(msg);
  }
```
But now what I want is to create the session object again, so I can change the state of the bot for that particular user. Can I create a session object with the address? Or do I need to serialize something else too?

**Comment by ernanirst** [comment]
After a few days diging into the SDK I was able to find a method on the UniversalBot class that begins a new dialog with an address. 

```
server.post('/', function (req, res, next) {
    var address = req.params
    bot.beginDialog(address, '/2')
    res.send("addr: " + JSON.stringify(req.params));
})
```

So, the code above adds a new endpoint that receives an address, now all I do is to begin a new dialog for the user this is intended to.

Cheers
