### ISSUE TITLE
Urgent:: Tap action on thumbnail or hero card

### ISSUE THREAD

**Issue by afficionaddo** [Microsoft/BotBuilder#1234]
Hi,

I want to open the image in full screen on a "TAP" over the HeroCard or ThumbnailCard.

What's the way to implement the above to open the cardImage in full-screen or in a large size?

**Comment by dandriscoll** [comment]
Hi @afficionaddo, currently the behavior of URL open actions is defined by the chat service (e.g. Skype) and the client platform (mobile, Windows, web, etc.). We do not have a way to control this behavior.

**Comment by dandriscoll** [comment]
Thinking about this more, some channels may expose this through their API and you could trigger it via ChannelData. Which channel are you using?

**Comment by afficionaddo** [comment]
I'm using facebook messenger.

**Comment by eanders-MS** [comment]
Hi @afficionaddo We send Hero cards to Facebook using the [Generic Template](https://developers.facebook.com/docs/messenger-platform/send-api-reference/generic-template). Images on the card are encoded in the template as an [Element](https://developers.facebook.com/docs/messenger-platform/send-api-reference/generic-template#element). The Element includes a field called `item_url`, which will be opened when the element is tapped, but we're only filling it out for the SignIn action type currently. Let me take this as a research item. We might be able to improve this.

**Comment by eanders-MS** [comment]
Apologies, we are in fact assigning `item_url` when action type is ShowImage and others such as PlayVideo, PlayAudio, etc. We're doing the best we can within the limits of Facebook's schema. Have you tried sending Tap.Type = ActionTypes.ShowImage?

**Comment by afficionaddo** [comment]
Thanks for the reply @eanders-MS !

I will try the above and let you know!
