### ISSUE TITLE
Bot in facebook messenger does not recognize ConversationUpdate or other type

### ISSUE THREAD

**Issue by afficionaddo** [Microsoft/BotBuilder#1235]
Hi,

When I add my bot in messenger screen, I was hoping it will go to 'conversation Update' or other 'types' and trigger the logic.

But instead nothing happens and replies only when the TYPE is 'message'.

**Comment by somprabhsharma** [comment]
Please refer to issue `#1261`.

**Comment by jameslew** [comment]
I'm assuming you got the answer you needed from the referred issue and am closing.  Please open again if your issue isn't resolved.
