### ISSUE TITLE
Delete "Typing" message

### ISSUE THREAD

**Issue by afficionaddo** [Microsoft/BotBuilder#1236]
Hi,

I sent a message of type 'Typing' to user but it is being shown constantly and that too at the below of all other messages sent after it.

How can I "show & remove" this 'typing' bubble for a moment when other messages are received?

**Comment by dandriscoll** [comment]
Hi @afficionaddo, which channel are you using?

Most channels display the typing bubble for 3 seconds and then it goes away.

**Comment by afficionaddo** [comment]
Facebook msgnr

**Comment by dandriscoll** [comment]
Currently on Facebook Messenger, the only way to delete the icon is to send an additional message to clear the status. We'll take a look at making this a little easier.
