### ISSUE TITLE
Message of type 'TYPING' once sent is constantly appearing on FB messenger

### ISSUE THREAD

**Issue by afficionaddo** [Microsoft/BotBuilder#1237]
Hi.

I had initially sent a message of type 'TYPING' to FB messenger. But even after code removal & repeated publish of code. The 'bubble of typing' is appearing constantly.

Don;t know why? Please give some recommendations.

**Comment by afficionaddo** [comment]
It gets removed when I send a message and the next reply comes.

**Comment by JpEncausse** [comment]
I tried to reply typing as soons as I receive a message but 
- It seems the typing is not sent immediatly it's like if there is a batch or somthing like that 
- Anyway it's not a workaround with facebook seems to lag

**Comment by afficionaddo** [comment]
In my case, I send 3 or 4 messages in one go.
And add the 'typing' message also in that.

Is this the correct way to proceed because if I send 'typing' as soon as i receive a message, the 'typing bubble' is still shown...don't know why?

**Comment by dandriscoll** [comment]
Since this issue is covered in #1236, I'm going to close this issue and track against that one. Please comment on that one, or open a new issue if you have unrelated questions/requests. Thanks
