### ISSUE TITLE
NodeJS / Facebook greeting message

### ISSUE THREAD

**Issue by JpEncausse** [Microsoft/BotBuilder#1238]
Following this issue:
https://github.com/Microsoft/BotBuilder/issues/991

I listen to the Bot Event and send back a message (tested with the emulator)

The first time a user is connected to the bot it should also diplay a greeting button according to the documentation:
https://developers.facebook.com/docs/messenger-platform/thread-settings/get-started-button

But I absolutly don't understand how to reproduce that with the BotFramework.

**Comment by SamuelTassell** [comment]
So I actually used a separate node server to handle the Facebook messenger setup as it's nothing to do with the botframework really:

Quick note, I'm not 100% sure this still all works with the recent update of messenger, so you'll need to check the Facebook API etc...

**app.js**
```
var request = require('request');

//=========================================================
// Facebook setup // Run only when need updating.
//=========================================================

// Set FB bot greeting text
facebookThreadAPI('./fb-greeting-text.json', 'Greating Text');
// Set FB bot get started button
facebookThreadAPI('./fb-get-started-button.json', 'Get Started Button');
// Set FB bot persistent menu
facebookThreadAPI('./fb-persistent-menu.json', 'Persistent Menu');

// Calls the Facebook graph api to change various bot settings
function facebookThreadAPI(jsonFile, cmd){
    // Start the request
    request({
        url: 'https://graph.facebook.com/v2.6/me/thread_settings?access_token='+process.env.FB_PAGE_ACCESS_TOKEN,
        method: 'POST',
        headers: {'Content-Type': 'application/json'},
        form: require(jsonFile)
    },
    function (error, response, body) {
        if (!error && response.statusCode == 200) {
            // Print out the response body
            console.log(cmd+": Updated.");
            console.log(body);
        } else { 
            // TODO: Handle errors
            console.log(cmd+": Failed. Need to handle errors.");
            console.log(body);
        }
    });
}
```
**fb-greeting-text.json**
```
{
  "setting_type":"greeting",
  "greeting":{  
    "text":"Your greeting text here."
  }
}
```
**fb-get-started-button.json**
```
{
  "setting_type":"call_to_actions",
  "thread_state":"new_thread",
  "call_to_actions":[
    {
      "payload":"action?POSTBACKHERE"
    }
  ]
}
```
**fb-persistent-menu.json**
```
// Just using the menu to do a single button admin reset
{
  "setting_type" : "call_to_actions",
  "thread_state" : "existing_thread",
  "call_to_actions":[
    {
      "type":"postback",
      "title":"Admin Reset",
      "payload":"action?POSTBACKHERE"
    }
  ]
}
```
I'm mean you could do this all in your main app but I seems unnecessary as it only needs to be called when changes are made etc...

Hope this helps :).

**Comment by SamuelTassell** [comment]
I'd also add that these features from FB messenger can be a little buggy. For instance if you set or change the greeting or menu etc... when using the browser you tend to have to clean the cache in order for the changes to appear, with the apps, a simple restart of the app normally works. Not only that but the menu seems quite buggy, sometimes just not appearing but I'm not sure if it's the new version of messenger as mentioned above.

**Comment by JpEncausse** [comment]
@SamuelTassell thanks it works great !

**Comment by slidenerd** [comment]
Instead of a separate server @SamuelTassell  you can use the sourceEvents to send these on the firstRun of our bot. Have you tried it 💃

**Comment by SamuelTassell** [comment]
Haha, nice call. I hadn't tried it as I only needed to setup messenger the once, so having it handled separately was cleaner for me :smile:.

**Comment by cesarvarela** [comment]
@slidenerd Do you have an example of how to do that? Thanks!

**Comment by cesarvarela** [comment]
if anyone is interested, I made a command line tool to ease working with Facebook thread settings:

https://www.npmjs.com/package/fb-thread-settings

**Comment by slidenerd** [comment]
Haven't tested this yet but regardless of JSON format changes , this should work perfectly, let me know if you think it can be improved

```
const request = require('request')

class MessengerProfile {
    constructor(token, options = {}) {
        this.token = token
        this.version = options.version || 'v2.9'
        this.greetingText = options.greetingText || {}
        this.getStartedButton = options.getStartedButton || {}
        this.persistentMenu = options.persistentMenu || {}
        this.whitelistedDomains = options.whitelistedDomains || {}
    }

    setGreetingText(json) {
        this.greetingText = json
        threadSetup(JSON.parse(this.greetingText))
    }

    setGetStartedButton(json) {
        this.getStartedButton = json
        threadSetup(JSON.parse(this.getStartedButton))
    }

    setPersistentMenu(json) {
        this.persistentMenu = json
        threadSetup(JSON.parse(this.persistentMenu))
    }

    whitelistDomains(json) {
        this.whitelistDomains = json
        threadSetup(JSON.parse(this.whitelistDomains))
    }

    threadSetup(json) {
        // Start the request
        request({
            url: `https://graph.facebook.com/${this.version}/me/messenger_profile?access_token=${this.token}`,
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            form: json
        }, (error, response, body) => {

            if (!error && response.statusCode == 200) {
                console.log(`Updated ${body}`);
            } else {
                console.log(`Failed ${body} Error ${error}`);
            }
        })
    }
}
```
