### ISSUE TITLE
is there a way to identify timezone of the user

### ISSUE THREAD

**Issue by ashfaq-uddin** [Microsoft/BotBuilder#1240]

**Comment by dandriscoll** [comment]
Are you looking for an annotation on an object, or are you looking for an interactive mechanism to ask the user which timezone they're in?

**Comment by ashfaq-uddin** [comment]
annotation on an object

**Comment by dandriscoll** [comment]
Hi @ashfaq-uddin, unfortunately most clients do not give us this information.

On SMS, for instance, it is impossible to know what timezone the sender is in. The same is true for email and Kik and others.

Telegram, for instance, does allow the user to send this data to a bot. This data appears in the ChannelData field.

Generally speaking, this data is not available in a reliable fashion across channels.

**Comment by dandriscoll** [comment]
https://github.com/Microsoft/BotBuilder/issues/813

**Comment by dandriscoll** [comment]
Same as #813

**Comment by jameslew** [comment]
I'm assuming your question has been answered.  I'm closing the issue, please open a new one if you have need further clarification.
