### ISSUE TITLE
Impossible to log on botframework.com

### ISSUE THREAD

**Issue by KIBASSA** [Microsoft/BotBuilder#1242]
Hi, 
When I try to log on dev.botframework.com, I have the following message:
"Login failed due to account collision."
And impossible to connect. 
What does that mean? Do you have an idea ?

Thank you in advance for your help

Junior

**Comment by tiksn** [comment]
I have the same issue.

**Comment by dandriscoll** [comment]
There was a large-scale DNS outage this morning that may have affected login. Can you try to log in again?
