### ISSUE TITLE
The remote name could not be resolved: 'api.projectoxford.ai'

### ISSUE THREAD

**Issue by rposbo** [Microsoft/BotBuilder#1243]
Looks like endpoint on which `LuisService.cs` [depends](https://github.com/Microsoft/BotBuilder/blob/aaf86d7b0542c8e2758bf14baa6b7cc67291e390/CSharp/Library/Luis/LuisService.cs#L88) is sporadically down for the past hour. 

We're receiving "The remote name could not be resolved: 'api.projectoxford.ai'" in our logs.

**Comment by dandriscoll** [comment]
Hi @rposbo, thanks for reporting. We're looking into it.

**Comment by CarolHanna** [comment]
Hi @rposbo, apology for this inconvenience. Azure is experience some instabilities that is affecting our service.

**Comment by dandriscoll** [comment]
This was related to an Azure DNS interruption which has been resolved.

**Comment by PratsBhatt** [comment]
I am still facing this issue.
