### ISSUE TITLE
Misspelling on the SMS Configuration page

### ISSUE THREAD

**Issue by devinrader** [Microsoft/BotBuilder#1244]
https://sms.botframework.com/Dev/?botId=DevinsLookupBot

TwiML is misspelled on the second step:

![image](https://cloud.githubusercontent.com/assets/1095289/18558291/8841d594-7b40-11e6-9405-b5665d54f3ba.png)

**Comment by dandriscoll** [comment]
Thanks @devinrader, will have this fixed in the next release!
