### ISSUE TITLE
Exception after `Quit` from FormFlow dialog.

### ISSUE THREAD

**Issue by myarotskaya** [Microsoft/BotBuilder#1248]
In the source code I can see that if the direction of the next step of FormDialog is `StepDirection.Quit` then an exception is thrown and the message `Sorry, my bot code is having an issue` is sent to the chat.

But as a user, I don't want to see `Sorry, my bot code is having an issue.` message after quit from the dialog. Is there any ability to change this behavior?

**Comment by willportnoy** [comment]
You can catch the FormCanceledException in the method you specified as the resumption method after calling the child form dialog.

**Comment by myarotskaya** [comment]
Will, thank you for the reply! After the handling of FormCanceledException everything works as expected. But I'm just curious, why a user should see this message after `quit` by default? And why the exception is throwed despite the fact that bot's state is ok and it can consume and handle further messages?

Here is some code example for those who will face with this problem:
```
[LuisIntent("YourIntent")]
public Task ProcessIntentAsync(IDialogContext dialogContext, LuisResult luisResult)
{
    var dialog = FormDialog.FromForm(YourForm.BuildForm, FormOptions.PromptInStart);

    dialogContext.Call(dialog,
        async (context, result) =>
            {
                try
                {
                    await result;
                }
                catch (FormCanceledException)
                {
                    context.Wait(MessageReceived);
                    return;
                }

                context.Wait(MessageReceived);
            });

    return Task.CompletedTask;
}
```

**Comment by chrimc62** [comment]
This was a feature request from customers--they wanted to be able to know where people were quitting from forms.  Exceptions provide a way of communicating that information "out of band".

**Comment by jdavidbambrick** [comment]
I'm following along in the sandwich maker example - and while I can handle the sandwich maker quit exception ... it continues afterward to give me an Exception: Form quit {File of type 'text/plain'] - where do I catch this to prevent it from showing up afterward?
