### ISSUE TITLE
Can't add facebook messenger to my bot

### ISSUE THREAD

**Issue by mephisto83** [Microsoft/BotBuilder#1249]
I am getting a 500 (Internal server error) at https://facebook.botframework.com/Dev/EnableChannelForBot.

**Comment by alonsonic** [comment]
I'm having a similar problem but instead of an 500 internal server error I'm getting an error page saying it couldn't find a bot with that name. Is there an on going problem with the platform?

**Comment by jameslew** [comment]
We fixed an issue on Thursday.  Are you still having the problem?  Are you willing to share your bout handle so I can investigate?

**Comment by dandriscoll** [comment]
Hi @mephisto83 and @alonsonic, we had an interruption that was causing this problem, and has been fixed. If you continue to encounter problems, please feel free to open a new issue.
