### ISSUE TITLE
EntityRecognizer.find* Methods Should Support LUIS Child Entities

### ISSUE THREAD

**Issue by thoughtentity** [Microsoft/BotBuilder#125]
This one kind of caught me off guard. The current `EntityRecognizer.find*` methods require an exact match of the LUIS entity type name to match. If a LUIS entity is defined with child entities then a user will be required to know how LUIS constructs the entity type names with a child entity type (`'ParentEntity::ChildEntity'`) in order to match it. This isn't very appreant in the documentation.

In order to better support this scenario, the `EntityRecognizer.find*` methods could either provide explicit overloads to take the child entity type or take a regular expression to do a regex match.

```TypeScript
let args: IEntity[] = [
    {
        ...
        type: 'Category::News'
    },
    {
        ...
        type: 'Category::Videos'
    }
]

/* Explicit Overloads */
static EntityRecognizer.findEntity(args: IEntity[], parent: string): IEntity|null
static EntityRecognizer.findEntity(args: IEntity[], parent: string, child: string): IEntity|null

// usage
EntityRecognizer.findEntity(args, 'Category') // should return 'Category::News'
EntityRecognizer.findEntity(args, 'Category', 'Videos') // should return 'Category::Vidoes'
EntityRecognizer.findEntity(args, 'Category', 'Cats') // should return null

/* RegEx Overload */
static EntityRecognizer.findEntity(args: IEntity[], regex: RegEx): IEntity|null

// usage
EntityRecognizer.findEntity(args, /^Category/) // should return 'Category::News'
EntityRecognizer.findEntity(args, /Videos$/) // should return 'Category::Vidoes'
EntityRecognizer.findEntity(args, /Cats$/) //should return null
```

**Comment by Stevenic** [comment]
Yes it should... LUIS child entities were added at the same time we released the Bot Builder SDK and to be honest we didn't actually know that change was coming. I just haven't had time to refactor LuisDialog or the EntityRecognizer to deal with this and a few other changes they made.

## Breaking Change
As a heads up I'm planning to rework both the LuisDialog and EntityRecognizer classes to support all of the new stuff LUIS added. As part of this I'm probably going to rename EntityRecognizer to LuisEntityRecognizer which would be a breaking change for a lot of people.

**Comment by Stevenic** [comment]
Moved to UserVoice:

https://feedback.botframework.com/forums/354222-bot-builder-sdk/suggestions/13463382--nodejs-entityrecognizer-find-methods-should-sup
