### ISSUE TITLE
Token authentication error on Facebook Messenger

### ISSUE THREAD

**Issue by afficionaddo** [Microsoft/BotBuilder#1252]
Security token for MicrosoftAppId: xxxx is unauthorized to post to connector!

But my "Endpoint authorization is succeeded" on "MyBots' page.

Why still am I getting this error???
Another thing I observed is that the issue occurs sometimes  not always.
That is sometimes I get messages but not so lucky on other instances.

Please help;(

**Comment by afficionaddo** [comment]
I have two bots....both are giving the same exception 'Unauthorized Access Exception for TOKEN'. ????

`Buffer="{ "message": "An error has occurred.", "exceptionMessage": "Security token for MicrosoftAppId: 01752554-bd59-4a92-ba6b-a7908daade6e is unauthorized to post to connector!", "exceptionType": "System.UnauthorizedAccessException", "stackTrace": " at Microsoft.Bot.Connector.JwtTokenRefresher.<SendAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n at Microsoft.Bot.Connector.Conversations.<ReplyToActivityWithHttpMessagesAsync>d__7.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at Microsoft.Bot.Connector.ConversationsExtensions.<ReplyToActivityAsync>d__15.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at NaMoBot.MessagesController.<Post>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"`

**Comment by dandriscoll** [comment]
Hi @afficionaddo, I've looked through our logs and it appears this was related to an interruption we had on our Facebook service. Can you try again to see if it works now? That will let us know if it's the same issue or if there's a different issue. Thanks
--Dan

**Comment by jameslew** [comment]
Very odd, I haven't seen this one.  Have you confirmed you haven't swapped them or something odd?  And you say its only some posts?  Is there a bot handle I could check the logs for?

**Comment by afficionaddo** [comment]
I think the issue is fixed. @dandriscoll 

But I am really curious as to what was the issue in 'Facebook service'. ?

**Comment by dandriscoll** [comment]
We have a Bot Framework service in front of the Facebook Messenger service. The Bot Framework service converts Bot Framework messages to the Facebook schema.
