### ISSUE TITLE
How to catch when Azure goes down?

### ISSUE THREAD

**Issue by SamuelTassell** [Microsoft/BotBuilder#1253]
So essentially, I had a meeting with an investor yesterday around the same time the Azure DNS issues were happening. I was frantically trying to find out why the bot just stopped responding, without knowing Azure broke... ended up having to show a static version of the service. _Not good_.

**My question is:** How do we implement something to test that the botframework/Azure is working as it should, or more to the point when it falls on it's arse. It would be good to have a function that tests this prior to doing anything. We can then handle it by saying `"Sorry the service is down at the moment"` etc... instead of it just breaking. Just to note my service is running on Heroku so the only bottleneck is the botframework as it's using Azure. I moved to Heroku as the Azure servers aren't up to the task for me but it seems I'm stuck with them at least partly if I use the botframework.

**Comment by dandriscoll** [comment]
Hi @SamuelTassell, it's a fair question.

You can probably work out an endpoint to hit to look at our servers, but that's only part of the picture. Really, you're looking for an indication that the Bot Framework will deliver traffic between your bot and your users. That's the thing your customers (and investors) will care about when they use your system or watch your demo.

If we look at what it takes to get traffic between your bot and an end user, there are a lot of links in the chain. Here's a list of the steps between your bot and a hypothetical demo running on, say, SMS:
- Logic in your bot
- Our SDK
- Connectivity from your machine to an Azure datacenter   <-- this is what failed earlier this week, but could just as easily have been another connectivity failure
- Bot Framework servers
- Connectivity from BF servers to Twilio (our SMS provider)
- Twilio's servers
- Twilio's connectivity to your carrier
- Cellular traffic to your phone, and the phone software itself

Reason I bring this up is that all of these have to be working properly for your demo to work. Without a complete path through, getting to our servers doesn't tell you the whole story.

If you're running a critical application -- and it sounds like your system is indeed important for your success -- you may want to consider end-to-end monitoring that takes into account Bot Framework, Azure, and the end clients where your messaging will appear. I will say that this is more complicated than a single endpoint, and may involve work to manually inspect a client chat application that has no programmatic API.

But, this is really the only way to have a complete picture of end-to-end connectivity.

**Comment by rposbo** [comment]
Our "solution" to this currently is have an `/available` endpoint in our bot code that actually creates an instance of a directline client, creates a conversation, and sends a "hello" message to our bot, expecting a canned response to come back; if the canned response isn't there, or an HTTP Exception is thrown, or any other exception is thrown, then we assume the bot is not available and fail over to something else.

**Comment by slidenerd** [comment]
@rposbo  how often are you pinging your bot to check if its running?
