### ISSUE TITLE
Critical Issue with Facebook Connector on BotFramework.com

### ISSUE THREAD

**Issue by ernanirst** [Microsoft/BotBuilder#1254]
Me and at least three other people on Gitter are experiencing this issue, if you try to add or edit facebook messenger, you will se the following error:

![screenshot from 2016-09-16 09-49-55](https://cloud.githubusercontent.com/assets/5594085/18586443/f5b6ee36-7bf2-11e6-9e92-7f47ba7a1c09.png)

This is happening for EVERY single bot I have.

**Comment by alonsonic** [comment]
This issue started yesterday and I think it's related to other issues that state that the bots are losing messages when talking on Facebook.

**Comment by bobzsj87** [comment]
Same here. Tried many times and didn't work once.
Also messages from Messenger are very unstable, slow, lost, no response.

**Comment by gobaldia** [comment]
My team and I have the same problem. As @alonsonic and @bobzsj87 said, it's not the only problem with Facebook. We also experienced slowness and lost of messages on Facebook (note that Skype's bot works well).

**Comment by sMorac** [comment]
Same problem here for me, Facebook Channel is dropping messages while Skype Channel works well. Nothing is reported on FB Messenger API. I got the Sad Bot page as well earlier today.

**Comment by ddalledo** [comment]
Add me to the list. Can't edit old facebook channels, and can't add channel to new bots. 
And messages drops and are VERY slow.

**Comment by CLOUD9111** [comment]
Same here Facebook only issue surfaced a couple of days ago without alert; here's the Insight's output exception and call stack:

![capture](https://cloud.githubusercontent.com/assets/22240158/18590209/40559128-7c2e-11e6-935f-554da15340c9.PNG)

**Comment by CLOUD9111** [comment]
Same here; the issue suddenly surfaced when connecting to a Facebook channel, here's the call stack from app insights:

![capture](https://cloud.githubusercontent.com/assets/22240158/18590429/10d3854e-7c2f-11e6-9be5-95e0e0b7c6af.PNG)

**Comment by jameslew** [comment]
Thanks everyone for the reports, we're looking into this right now.

**Comment by dandriscoll** [comment]
We've tracking a few issues here.

The dev portal should be fixed now.

We're seeing some sensitivity on Facebook's side to image Content-Types, so if you're including images and their content-type is e.g. "image/jpg" instead of "image/jpeg," that's failing the request. I don't know if Facebook was sensitive to this before.

**Comment by dandriscoll** [comment]
@CLOUD9111 , your issue appears to a be a problem within your bot. That's different from the other errors we're investigating.

**Comment by dandriscoll** [comment]
Hi @ernanirst and @sMorac , if you see the Sad Bot page again, please at-mention me. We believe that's fixed.

**Comment by dandriscoll** [comment]
Looking through our logs, everything should be back to normal (and actually has been for a while, but wanted to be sure before I said so). @ernanirst, @alonsonic, @bobzsj87, @gobaldia, @sMorac, @ddalledo, and @CLOUD9111, can you please check and at-mention if you see any further issues?

**Comment by ernanirst** [comment]
@dandriscoll seems fine now. Thanks.

**Comment by gobaldia** [comment]
@dandriscoll for me it's ok right now. Also it's ok what I mentioned in #1257 
Thanks!

**Comment by dandriscoll** [comment]
I'm going to close the issue as the service problem has been resolved and confirmed by a few folks. If you see failures or page load issues that you think are a recurrence of this problem or that you think are widespread failures, please open a new issue and we'll take care of it promptly.

Thanks all for reporting the issue and your patience as we resolved it.

**Comment by CLOUD9111** [comment]
Problem solved on my side and everything is back to normal, many thanks for your efforts guys.

**Comment by sMorac** [comment]
@dandriscoll Thanks, it's working now! Great job!
