### ISSUE TITLE
PromptDialog or another from ConnectorClient

### ISSUE THREAD

**Issue by wiltodelta** [Microsoft/BotBuilder#1255]
How to start dialog from ConnectorClient?

**Comment by willportnoy** [comment]
ConnectorClient is for sending messages from the bot to the user.

Maybe your question is how to start a dialog from an external event - this code might help you:
https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Samples/AlarmBot/Models/ExternalEvent.cs#L29
