### ISSUE TITLE
Bug in version 3.2.1

### ISSUE THREAD

**Issue by kenyeung128** [Microsoft/BotBuilder#1256]
The new version introduces a bug in ResumptionCookie, the default constructor is removed, so it will cause this error in the FacebookAuthentication sample "A class should either have a default constructor, one constructor with arguments or a constructor marked with the JsonConstructor attribute."

The lines below will trigger the exception as above.

context.PrivateConversationData.SetValue("persistedCookie", ResumptionCookie);

dataBag.PrivateConversationData.TryGetValue("persistedCookie", out pending)

**Comment by kenyeung128** [comment]
Actually It seems it's the new class Address missing the default constructor, when I add the default constructor in the class Address, it works.

**Comment by jameslew** [comment]
I'll get this in front of the SDK developers.

**Comment by kenyeung128** [comment]
thanks, it fixed now.
