### ISSUE TITLE
Lost of messages in Facebook

### ISSUE THREAD

**Issue by gobaldia** [Microsoft/BotBuilder#1257]
Since yesterday, me and more people are experiencing a lost of messages in Facebook.
For example, if the bot should send 3 messages, it only sends 2. Then, it sends all messages, then it sends another 2 messages (totally random).

**Comment by ddalledo** [comment]
I have a even worst problem with facebook as I keep getting error page when I edit properties or add it as a new channel in my bots page:

> Sad bot is sad because unable to find bot named [bot name]

Configured bots seams to work, but they drop messages too. All others channels works with (almost) no problem.

**Comment by gobaldia** [comment]
@ddalledo please check issue #1254 for the 

> Sad bot is sad because unable to find bot named [bot name]

My bot also works properly in the other channels.

**Comment by raphael-abreu** [comment]
Same problem with me

**Comment by dandriscoll** [comment]
Hi all, thanks for your patience. We had some degradation of the service but it appears to be resolved now. Please let us know if you see the problem again.

**Comment by dandriscoll** [comment]
Same issue as 1254, so closing this.
