### ISSUE TITLE
Question: How to load and pass JSON for facebook greeting screen c#?

### ISSUE THREAD

**Issue by afficionaddo** [Microsoft/BotBuilder#1258]
Hi,

What's the way to implement greeting screen of FB messenger c# for the bot?

**Comment by jameslew** [comment]
For the moment you may have to make a call directly to Facebook to do this particular operation.  Setting it is not part of the Message API, it's a separate direct call.  The API for that call is reference here:

https://developers.facebook.com/docs/messenger-platform/thread-settings/greeting-text

We're looking at ways we can expose this sort of setup settings in the Bot Framework API.

**Comment by afficionaddo** [comment]
Thanks for the reply @jameslew 

But I am confused, when do i make this API call. As when i add my bot in FB messenger, I dont know for some reason my code in ActivityType.conversationUpdate or relationupdate does not get triggered. 


More so FB does not trigger anything on adding the bot. It only does so when I message the bot.

What am I missing here.

**Comment by somprabhsharma** [comment]
You need to make the curl request separately. It does not have anything to do with your bot code.T his is only one time task. You can open cmd or terminal and run that code with your fb page access token and your customised greeting text. for some cases you might need to install curl before you can run this command.

**Comment by afficionaddo** [comment]
Thanks for the reply.

See my bot is not yet approved. Still in development.

So you are saying that I just make the curl request independently and whenever next time a user adds my bot...it will show the greeting screen?

**Comment by jameslew** [comment]
Yes, currently you'll need to make the separate curl call (albeit it doesn't have to be curl, you could make an http call within your bot's startup code to set the settings).
