### ISSUE TITLE
Incorrect Bing Search Images V5 Base Uri in GIF Search Bot Example

### ISSUE THREAD

**Issue by tjoudeh** [Microsoft/BotBuilder#1260]
The Base Uri for the Search Images V5 (https://bingapis.azure-api.net/api/v5/images/search) in the example [https://docs.botframework.com/en-us/bot-intelligence/search/#example-gif-search-bot](https://docs.botframework.com/en-us/bot-intelligence/search/#example-gif-search-bot) **is incorrect**, the Base Uri should be updated to (https://api.cognitive.microsoft.com/bing/v5.0/images/search)

**Comment by jameslew** [comment]
Thank you, we'll get the sample updated.

**Comment by Andrea-Orimoto** [comment]
This has been fixed, thanks a lot for reporting the issue!
https://docs.botframework.com/en-us/bot-intelligence/search/
