### ISSUE TITLE
On adding my bot to messenger, it does not trigger 'conversationUpdate' or 'contactRelationUpdate'

### ISSUE THREAD

**Issue by afficionaddo** [Microsoft/BotBuilder#1261]
Hi,

When I add my bot to messenger, it does not trigger 'conversationUpdate' or 'contactRelationUpdate'.

Actually i want to show greeting screen so I was hoping that could be accomlished through these 'ActivityTypes' and then send the json through channel field.

But it does not trigger any of the types except 'message'.

Please help.

**Comment by somprabhsharma** [comment]
Which Channel ? It works fine for skye and kik, in telegram there is a start button and in messenger you can add a get started button and you can respond to the event on get started button to send greeting text in telegram and messenger. Only in case of skype it does not work right now.

**Comment by afficionaddo** [comment]
Facebook.

**Comment by jameslew** [comment]
The greeting page is configured via settings calls to Facebook, that are currently outside the scope of the Bot Framework API.  You can call Facebook directly to set things like the greeting page message via direct https calls to the Facebook API.  

We've added this type of setting to the feature request backlog for the Bot Framework API.

**Comment by slidenerd** [comment]
do contactrelationupdate, deleteuserdata and other activities work only on C# or is there a node.js version of them? I could not find it in the node.js docs

**Comment by jameslew** [comment]
The iContactRelationUpdate interface event and iConversationUpdate event are there; you could also be able to look at the Type of the message object.

**Comment by craigjensen** [comment]
It doesn't look like Facebook sends a message when a user adds a bot to messenger but a ConversationUpdate activity message should be sent the first time a user converses with your bot.

**Comment by slidenerd** [comment]
if it isnt too much to ask, can anyone clarify what is the difference between conversationUpdate and contactRelationUpdate? do they both do the same thing across all platforms? is there any case where only one of them is triggered? I read the docs and contactRelationUpdate says "triggered when the person adds the bot to his/her contact list" Does that mean a simple "hi" said by the user triggers this event as the bot gets added to his/her recent conversations? Also if the bot runs in a group, how does conversationUpdate work?
