### ISSUE TITLE
Chain with different types of Dialogs?

### ISSUE THREAD

**Issue by etiago** [Microsoft/BotBuilder#1263]
Hi everyone,

I'm trying to build a bot in C# that has the following flow:
- UnauthenticatedDialog (the bot can do some basic unauthenticated tasks for the user like some greetings and help menus, and the user can also transition to the... )

- AuthenticationDialog (the bot gives the user a link to Auth0, the user clicks the link, is redirected to a LoginCallback on the same WebApp as where the bot is running and stores this for this particular user. When the authentication succeeded, we transition to the...)

- CreateStuffDialog (this dialog extends from a LuisDialog which, via generics, wraps around a class with properties that have attributes like Prompt, Template, etc)

The CreateStuffDialog class itself has Luis dialogs such as LuisModel (to specify which model to bind to) and LuisIntents to bind methods to specific intents.

Now, I started from the FacebookAuth example where we make the root chain as follows:
```csharp
public static readonly IDialog<string> dialog = Chain
            .PostToChain()
            .Switch(
                new Case<IMessageActivity, IDialog<string>>((msg) =>
                {
                    var regex = new Regex("^login", RegexOptions.IgnoreCase);
                    return regex.IsMatch(msg.Text);
                }, (ctx, msg) =>
                {
                    // User wants to login, send the message to Facebook Auth Dialog
                    return Chain.ContinueWith(new SimpleFacebookAuthDialog(msg),
                                async (context, res) =>
                       {
                           // The Facebook Auth Dialog completed successfully and returend the access token in its results
                           var token = await res;
                           var valid = await FacebookHelpers.ValidateAccessToken(token);
                           var name = await FacebookHelpers.GetFacebookProfileName(token);
                           context.UserData.SetValue("name", name);
                           return Chain.Return($"Your are logged in as: {name}");
                       });
                }),
                new Case<IMessageActivity, IDialog<string>>((msg) =>
                {
                    var regex = new Regex("^logout", RegexOptions.IgnoreCase);
                    return regex.IsMatch(msg.Text);
                }, (ctx, msg) =>
                {
                    // Clearing user related data upon logout
                    ctx.PrivateConversationData.RemoveValue(AuthTokenKey);
                    ctx.UserData.RemoveValue("name");
                    return Chain.Return($"Your are logged out!");
                }),
```

In this example, however, all the Case objects are using a ```<IMessageActivity, IDialog<string>>``` generic definition. In my case, for Unauthenticated and AuthenticationDialog I could use the IDialog<string>, but when it comes to the CreateStuffDialog, this one extends from a LuisDialog<StuffClass>. Thus, when I try to chain IDialog<string> with CreateStuffDialog, I get a compiler error saying that this is not possible.

Does anyone have any idea how I could work around this? I'm still trying to wrap my head around the bot framework and now I'm very much stuck on this :disappointed: 

Thanks in advance!

**Comment by willportnoy** [comment]
You could use a Select to cast the result to IDialog<object> so the types are the same.

**Comment by etiago** [comment]
I think I managed to work around this today by using a generic "object" for the LuisDialog instead of having it as a fixed type... will confirm tomorrow :+1: thanks for the help!
