### ISSUE TITLE
Customize WebChat

### ISSUE THREAD

**Issue by kenyeung128** [Microsoft/BotBuilder#1268]
Hi, is there any way to customize WebChat? like a message with multiple HeroCard, could it display as carousel slide like facebook messenger?

thanks

**Comment by dandriscoll** [comment]
Hi @kenyeung128, a new, customizable Web Chat control is in development. We will make an announcement when it is available.

In the meantime, one option is to code your own control against the Direct Line API. Web Chat uses Direct Line already and you may be able to use the JS as an example.

**Comment by irynabond** [comment]
Hi @dandriscoll , 
is there approximate date when a customizable Web Chat control becomes available? It's going to save a lot of time.

**Comment by dandriscoll** [comment]
Hi @irynabond, I wish I had a timeline I could share. We're hard at work on it.

**Comment by kenyeung128** [comment]
thanks @irynabond
