### ISSUE TITLE
Are you planning to add new channel to Microsoft Bot Framework?

### ISSUE THREAD

**Issue by somprabhsharma** [Microsoft/BotBuilder#1271]
We are using Microsoft Bot Framework to create bot for telegram, messenger, skype, slack and kik. We want to create bots for line and wechat. So I want to know that are you planning to add line, wechat?

**Comment by jameslew** [comment]
We don't have anything to announce at this time - but we're always looking at which channels it makes to integrate next.  I'll note the additional interest in these channels in our backlog.

**Comment by alex182** [comment]
How about a Skype for Business channel?

**Comment by dandriscoll** [comment]
Sorry, we don't have anything to announce right now.
