### ISSUE TITLE
is it possible to put ads in a bot?

### ISSUE THREAD

**Issue by fercom** [Microsoft/BotBuilder#1274]
My bot is getting more users and I need to pay for services that it uses, I want to integrate something like google adsense but I understand that this is just for websites, Is there any way to integrate a service like this?

**Comment by Andrea-Orimoto** [comment]
Hi @fercom, it is currently not allowed under our terms of service https://www.botframework.com/Content/Microsoft-Bot-Framework-Preview-Online-Services-Agreement.htm, section 4.13. Hope this answers your question.
