### ISSUE TITLE
Microsoft Bot

### ISSUE THREAD

**Issue by BalajiMano** [Microsoft/BotBuilder#1275]
Hi,

I am planning to propose microsoft bot instead of traditional IVR application to one of my banking customer, so bot will be act as IVR application to server customer queries. I have two questions,

1. Can I propose this solution and is that legal to use Microsoft bot for commercial purposes?

2. If I propose this solution, Could I deploy my bot in Microsoft Windows server instead of Azure ? Can I access my bot if that hosted in Microsoft server from all the channel?

Kindly some one help me.

Regards
Balaji

**Comment by dandriscoll** [comment]
Hi @BalajiMano, you can use any hosting platform to host your bot, as long as it can be accessed on the internet. Windows Server is acceptable.

**Comment by BalajiMano** [comment]
Thank you so much dandriscoll :).
