### ISSUE TITLE
Image not fully visible using CardImage feature of HeroCard in skype and facebook

### ISSUE THREAD

**Issue by senthil2m** [Microsoft/BotBuilder#1277]
Hi,

I used CardImage in HeroCard to render an image of resolution 450*350 (smartphone jpeg image url) in node.js sample code. But the image rendered is not fully visible in skype and facebook channel. Part of image at the top and bottom is cut in these channels but same thing works fine in webchat with full image displayed.

Need help to render full image in facebook and skype channels using nodejs.

Thanks,
Senthil M

**Comment by willportnoy** [comment]
I don't believe we're truncating the image in the channel adapters, but it's possible the channel itself chooses to crop the image to preserve the aspect ratio instead of displaying empty bars on the side (and perhaps web chat allows some flexibility in the available image space).

**Comment by Andrea-Orimoto** [comment]
Yes, Skype and Facebok crop images.

- Facebook https://developers.facebook.com/docs/messenger-platform/guidelines 
- Skype https://docs.botframework.com/en-us/skype/getting-started/#cards-and-buttons

Hope this helps
