### ISSUE TITLE
Issues in Typing Bubble

### ISSUE THREAD

**Issue by senthil2m** [Microsoft/BotBuilder#1278]
Hi,

I used the below nodejs code to display typing bubble when bot replies back.
bot.use(builder.Middleware.sendTyping());
I get couple of issues.
Issue 1 : In FB messenger, When bot requires prompt.choice from user, the prompt options are not visible rather than typing bubble keeps visible without getting disappeared. This issue occurs in fb messenger of android but works fine in web messenger.
Issue 2 :  Typing bubble continuously visible even after bot replies back. In this case, it should get disappear once bot replies back. This issue occurs in fb messenger of android but works fine in web messenger.
Issue 3 : Typing indicator not visible in skype and webchat.

Need clarifications on above issues.

Thanks,
Senthil M

**Comment by dandriscoll** [comment]
Hi @senthil2m, notes on each issue you described:

1. Facebook Messenger displays the typing indicator for 20s. This is specific to the channel.
2. This appears to be a bug in Facebook's UI.
3. Skype will support the typing indicator soon, and Web Chat will support it in the next release.

**Comment by senthil2m** [comment]
Hi dandriscoll,
Thanks a lot for the reply. I am still not clear with the point no.1,
 Issue 1 : In FB messenger, When bot requires prompt.choice from user, the prompt button options are not visible instead typing indicator keeps visible and this happens in android fb messenger app.

**Comment by dandriscoll** [comment]
That sounds like a separate issue. If the prompt isn't showing, it's probably not related to the typing indicator. You can verify by temporarily disabling the typing indicator in your code and seeing if the choice prompt appears.

**Comment by senthil2m** [comment]
Yes but prompt works fine when there is no typing indicator.

**Comment by dandriscoll** [comment]
@Stevenic, any issues you can see?
@senthil2m, can you send your bot ID or a conversation ID where you experienced problems, and I can take a look on the service.

**Comment by senthil2m** [comment]
Bot id is 4fcd0d6f-20f1-43be-9bd7-233db6ad0b1e
Issue occurs in facebook messenger in android phones.
1. typing indicator is not dismissed.
2. prompt choices are not showing

**Comment by seb0zz** [comment]
I have exactly the same issue. Works perfectly on web and iOS but not on Android.

**Comment by seb0zz** [comment]
Should be related to #1434 posted a temporary workaround for NodeJS there.

**Comment by Stevenic** [comment]
Yes... There's a known issue on android. You have to manually send a stop typing indicator.

**Comment by senthil2m** [comment]
@seb0zz 
@Stevenic 
Thanks a lot for the update.
