### ISSUE TITLE
Newly registered bot but automatically added skype bot cant be used (added/messaged) in skype - MAC ONLY, windows works

### ISSUE THREAD

**Issue by Daij-Djan** [Microsoft/BotBuilder#1280]
Hi
I newly registered my bot on botframework.com. azure hosted, all working fine in emulator, all looks ok.

BF added a skype channel for my bot automatically but it cant be used (addew/messaged) in skype:
https://join.skype.com/bot/40b69265-52e4-4416-8c1b-d69813df1d20

skype only show some weierd ID 28234:24398-23-324i-24 (or so) and the bot cant be messaged or added
- MAC ONLY, windows works

**Comment by nickcordrey** [comment]
Please could you let me know which version of the Mac client you are using?

**Comment by Daij-Djan** [comment]
Version 7.18 (342) — auto updating didn’t work. Ill try with the latest version again today!

LG
Dominik

Web: https://pich.info
Twitter: @DaijDjan
Facebook: Dominik.Pich

**Comment by Daij-Djan** [comment]
works with 7.37

LG
Dominik

Web: https://pich.info
Twitter: @DaijDjan
Facebook: Dominik.Pich
