### ISSUE TITLE
Prompt localization using _promptDefinition doesn't work

### ISSUE THREAD

**Issue by mitkodi** [Microsoft/BotBuilder#1281]
If you set in resource file for a given form ***FieldName*_promptDefinition;LIST** it doesn't take effect.

ps
I can workaround it by adding **_promptSet = true;** in **Field.cs** (but not sure is it OK in other cases):
```
if (localizer.LookupValues(_name + nameof(_promptDefinition), out patterns))
            {
                _promptDefinition.Patterns = patterns;
                _promptSet = true;
            }
```

**Comment by ejadib** [comment]
@mitkodi another workaround would be leaving an empty PromptAttribute in your fields.

**Comment by mitkodi** [comment]
Thanks @ejadib !

**Comment by mitkodi** [comment]
It seems that it doesn't work if the field type is a class (which is neither string nor IsIEnumerable).
Maybe because ProcessFieldAttributes is not called for these fields?

**Comment by mitkodi** [comment]
Please ignore the above post/reopen. It seems that such type of fields are not supported. I thought that I could set the real value for such field through validate, but I'm wrong.
