### ISSUE TITLE
Channel Emulator crashes on startup: Failed to start callback server, access denied

### ISSUE THREAD

**Issue by rschacherl** [Microsoft/BotBuilder#1282]
Whenever I start the Microsoft Bot Framework Channel Emulator (3.0.0.59) I immediately get the message "Zugriff verweigert" ("Access denied") and the title of the message box says "Failed to start callback server".

I've tried reinstalling it, I deleted the "%temp%\emulator.service" file, I tried to start the emulator as an administrator, I changed the port and I checked the firewall settings. No success.
Currently I get SocketExceptions and HttpRequestExceptions and a 500 Internal Server Error response whenever I send a message to my bot.

Any help would be appreciated!

Edit: When I first tried to run the emulator as an administrator through the start menu, the app didn't even start. Now I looked for the path of the .exe file (in AppData\Local\Apps) and started it directly as an administrator - that works! Also the errors are gone, my bots are working as expected. Starting the emulator without administrator rights brings back the exception.

**Comment by willportnoy** [comment]
It sounds like a firewall issue - I run the emulator successfully without administrator access.

**Comment by Andrea-Orimoto** [comment]
@rschacherl closing this issue because it looks like something we can't address. Feel free to reopen if you still have issues and need our help. Thanks!

**Comment by gzhebrunov** [comment]
Just got same issue:
![image](https://cloud.githubusercontent.com/assets/5611745/19356790/f9d01f92-913c-11e6-95e6-82730744ad3c.png)
Emulator version 3.0.0.59.
OS: Windows 10 Pro
Tried to play with ports, 8080, 9006, etc. 
Tried to add ports to Firewall.
Tried to turn off Firewall.
Tried to run in the Administrator mode (nothing happening if I do this from start menu), but same error still appears if I run it directly from file explorer in Admin mode.

On other computer (Windows 10 too) emulator working fine, but can not run on this computer. Are there any logs where I can see what exactly is used by another process? Is it really file or port?
