### ISSUE TITLE
Unable to find a version of 'Microsoft.Rest.ClientRuntime' that is compatible with 'Microsoft.Bot.Connector.DirectLine

### ISSUE THREAD

**Issue by ADefWebserver** [Microsoft/BotBuilder#1284]
The Microsoft.Bot.Connector.DirectLine 1.0.2 has a constraint: Microsoft.Rest.ClientRuntime (>= 1.8.2 && < 2.0.0)'. Microsoft.Rest.ClientRuntime is up to version 2.3.3 (and climbing). Is there a reason for this constraint?

Thanks!

See:
http://stackoverflow.com/questions/39563768/unable-to-find-a-version-of-microsoft-rest-clientruntime-that-is-compatible-wi

**Comment by dandriscoll** [comment]
Hi @ADefWebserver, we're still working out how to upgrade the UWP version of Direct Line. That package doesn't work with ClientRuntime 2.3.2 (the most recent one I tested) and needs to be modified. It's in our backlog at the moment. Is this a blocking problem?

**Comment by ADefWebserver** [comment]
It is only blocking my blog post :) If you upgrade your web project to "all the latest updates" using the NuGet Wizard, you will get errors and your web application will no longer build.

I will just put my blog post aside and come back to this topic later. If I need to proceed I can always call the Directline API using HTTP calls.

Thanks for the follow-up.

**Comment by JasonBSteele** [comment]
I have this problem and it's blocking my upcoming hackathon!

**Comment by ADefWebserver** [comment]
Remember you can always call the REST API directly. You do not NEED the Client. See: https://docs.botframework.com/en-us/restapi/directline/

**Comment by JasonBSteele** [comment]
@ADefWebserver sure, I could, there's quite a few models there to reproduce - being a bit lazy I guess! I've tried finding the source for Microsoft.Bot.Connector.DirectLine but it doesn't seem to be in the main BotBuilder solution. Any ideas? Or have you caved in and rolled your own which you could share in your blog post? ;)

**Comment by ADefWebserver** [comment]
@JasonBSteele I am able to make my code work with Microsoft.Rest.ClientRuntime 1.8.2. I looked for examples calling the REST endpoint directly and couldn't find any. I know I saw them before but after 10 minutes of Googling I could not come up with anything :(

**Comment by JasonBSteele** [comment]
@ADefWebserver yeah, I tried to find some actual code that does it but drew a blank. Thanks for looking though.

**Comment by JasonBSteele** [comment]
I've updated my duplicate issue at https://github.com/Microsoft/BotBuilder/issues/1381 with a workaround for those that may want to include both versions of the dll.
