### ISSUE TITLE
Changing colour of string in bot framework

### ISSUE THREAD

**Issue by dipumon** [Microsoft/BotBuilder#1287]
Is there any option to change the font color of string that is sent from bot to user instead of default black in  .NET?

I am trying to change the color of text appearing in cards in bots

**Comment by dandriscoll** [comment]
Hi @dipumon, which channel are you using?

**Comment by dipumon** [comment]
I am using skype channel.

**Comment by nickcordrey** [comment]
Skype doesn't support changing font color. https://docs.botframework.com/en-us/csharp/builder/sdkreference/activities.html has a list of supported tags.

**Comment by anandvardhandas** [comment]
can we change the color of the text we send in Webchat Directline? Also can we send at least the CSS class name so that with help of that class name, we can change the color at our webchat end?

**Comment by EricDahlvang** [comment]
Hi @anandvardhandas 

If you are not using the iframed version of webchat, you can override the css using normal means of css overriding.

Please ask your question on StackOverflow, and someone will assist you promptly.  (The Bot Framework team prefers that the GitHub repository be used for bug reports and feature requests.)
