### ISSUE TITLE
Is it possible for Bot to proactively message to any specific contact via channel like Skype/FB/Slack?

### ISSUE THREAD

**Issue by barmangaurav** [Microsoft/BotBuilder#1288]
Based on some activity message, I want to send a proactive message from Bot side to a specific user on its contact list using any of the supported messaging channels like Skype/FBMessenger/Slack. 
This specific user has not done any conversation with the bot yet; but added the bot to its contact list on the same channel. I am using **C#** to develop my Bot.

Example:
Message from me(barmangaurav) to Bot: 
Please initiate a sale transaction for my car, buyer name: XYZ

**Message from Bot to XYZ: 
A sale transaction has been initiated for the purchase of car, Please ping the OTP to confirm and finish transaction. Seller name: barmangaurav | OTP: s2DwQT4**

Message from Bot to me(barmangaurav): 
As requested, a transaction has been initiated and OTP has been sent to XYZ, your transaction will be finished once buyer confirms by sending the OTP.

P.S. - XYZ is the registered username on any of the channel.

Any help or advice is much appreciated.

**Comment by Daij-Djan** [comment]
I can only answer for Facebook and only for doing it without the botframework :D there it is possible only after the user opt-in to be contacted by you ONCE -- e.g. in technical terms you need his page_scoped userId which you get after the user does the opt-in (he doesn't have to message you (!))

**Comment by brandonh-msft** [comment]
It is possible. @EricaWu did this w/ the [Olympics Bot](https://github.com/ericawu/TwitterStreamEventBot):

https://channel9.msdn.com/Blogs/Seth-Juarez/Erica-Wu-on-the-Bot-Framework-and-Cognitive-Services

**Comment by Daij-Djan** [comment]
awesome - how then :D
LG
Dominik

Web: https://pich.info
Twitter: @DaijDjan
Facebook: Dominik.Pich

**Comment by brandonh-msft** [comment]
that's why i linked the source ;)
but [here's the method that does it](https://github.com/ericawu/TwitterStreamEventBot/blob/master/TwitterStreamEventBot/Services/CheckTrends.cs#L47)

**Comment by Daij-Djan** [comment]
sorry and thanks - saw only the huge video on the page :)

LG
Dominik

Web: https://pich.info
Twitter: @DaijDjan
Facebook: Dominik.Pich

**Comment by barmangaurav** [comment]
That's great news.. Let me implement the same and I share my feedback afterwards.

Thanks a ton Daij-Djan and brandonh-msft

**Comment by barmangaurav** [comment]
Well, after going through the github code, I have learnt that TwitterStreamEventBot is storing user details (Service URL, Recipient and From) into a topic dictionary whenever a user subscribe for any topic. 
Later, at every 15 seconds if the subscribed topic is a trending one, Bot sends proactive message(trending topic details) to the subscribed user. 

This proactive messaging works fine for a user who has already interacted with the Bot once.

My initial query was to proactively messaging a new contact(UserB) which has never interacted with the bot based on some event or a request by any user(UserA) interacting with the bot. I presume that feature is not available in order to **avoid spamming**. 
I will work out with current available features and tweak my use case to fit a publisher-subscriber model.

Many thanks for your guideline and support @Daij-Djan , @brandonh-msft , @EricaWu

Regards,
Gaurav Barman

**Comment by SurabhiKandi** [comment]
I have also have the same question but i am developing my bot in Node Js.
How can i send message and receive particular reply for that message in Node Js?

Any help or advice is much appreciated.

**Comment by brandonh-msft** [comment]
@SurabhiKandi: https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node/core-CreateNewConversation

**Comment by SurabhiKandi** [comment]
Thanx brandonh-msft , 
     I am able to send the message to user but not able to receive user reply . I am not getting any error and also not receiving any user reply. So, how could i do that ?

**Comment by piffarettig** [comment]
@barmangaurav how did it go?

Could you find some way of making a Facebook Messenger bot send a message to their users? By users here I mean users that like the Facebook Page, but never sent a message to the bot.

**Comment by stelazh** [comment]
@piffarettig have you find a solution ? I'm creating a messenger bot , and i need to create a module to send broadcast message to users in a specific time .

**Comment by stelazh** [comment]
Ok , this is possible in my case...i will send notification after they will request to be notify ...i want to know how to initialize a conversation when in my database i will have one info . 

For example user want to get notification when we have a racing . I have to send notification to user 1 hour before the event will be online
