### ISSUE TITLE
WebChat stops polling for new messages

### ISSUE THREAD

**Issue by arieschwartzman** [Microsoft/BotBuilder#1289]
Some times (like a lot) the WebChat control will stop polling the messages API. Later, when sending new message from the user, will wake up the polling mechanism again. 

I see that you had others complaining about the same issue.

Thanks

**Comment by dandriscoll** [comment]
Hi @arieschwartzman, we have this issue fixed and it should be deployed soon.

**Comment by arieschwartzman** [comment]
Great ! Thanks

**Comment by dandriscoll** [comment]
Closing, please see #965
