### ISSUE TITLE
NodeJS: endDialog() do not default to top dialog

### ISSUE THREAD

**Issue by JpEncausse** [Microsoft/BotBuilder#129]
Hi,

I have a root dialog to '/' and a test dialog to '/test'.

I enter to /test with :
root.matches('^set test', function (session) { session.beginDialog('/test') });

But session.endDialog(); do not leave /test (because, I assume, there is no other upper dialog). A kludge workaround is to call session.beginDialog('/');

I think the bug should be fixed by calling session.beginDialog('/'); if there is no other dialog otherwise fallback on previous dialog.

**Comment by Stevenic** [comment]
session.endDialog() does leave the '/test' dialog but it will call your closure a second time so it looks like you're just starting '/test' again. You have to guard against this in your handler or use one of the other ways to start a dialog which already guard against it.

if all you're doing is trying to call your '/test' dialog you can either use 'DialogAction.beginDialog('/test')' which has the guard or the shorthand version 'root.matches('^set test', '/test')` which essentially calls DialogAction.beginDialog() for you.

If you need to do some processing before calling your '/test' dialog you can use a waterfall which naturally protects against this.

It's a much longer explanation for why the endDialog() call re-enters like this (trust me this is way better than the alternative) and I should probably try to document this behavior better but my intention was that you'd generally be using waterfalls or one of the Dialog Actions to do stuff which guard against us. There are plenty of cases where the simple closure is useful (it's the Hello World sample) but in this case you do have to use it with care.

**Comment by Stevenic** [comment]
Please re-open this if you didn't understand my explanation of the issue you're running into and how to avoid it.
