### ISSUE TITLE
Microsoft Bot Skype channel not replying from today

### ISSUE THREAD

**Issue by subhans3tech** [Microsoft/BotBuilder#1291]
i have microsoft bot working properly but suddenly today it stops replying it was deployed on azure and  its app id is   b55480e2-6f71-4b9a-94a0-d1fb0448093a

**Comment by dandriscoll** [comment]
Hi @subhans3tech, the bot seems to be responsive and our logs don't indicate any errors. What behavior are you seeing?

**Comment by subhans3tech** [comment]
it become unresponsive for three hours but suddenly start replying
Thanks

**Comment by dandriscoll** [comment]
Closing this issue as the problem appears to be resolved. Please feel free to open a new issue if you see further problems.
