### ISSUE TITLE
[Feature Request] Docs > How to build Node SDK from source

### ISSUE THREAD

**Issue by morsh** [Microsoft/BotBuilder#1292]
Hi,
I want to edit and offer a pull request to the node.js module, but the development process is unclear to me.
1. It seems that there are missing files (specifically immited ".vscode/*" files that define how to compile the ts files and generate the js code and d.ts files.
2. The root directory of the npm module is unclear (Node/ or Node/core/)
3. Is there anything else I need to know when building the project for local development?

Would really appreciate some help.

Thanks,
Mor

**Comment by morsh** [comment]
Hi @Stevenic, anything new?

**Comment by palashjhabak** [comment]
I would like to know this as well. @morsh, were you able to achieve this?

**Comment by Stevenic** [comment]
We'll add some docs on how to build. Valid criticism.  You'll need VSCode + TypeScript.  Once you install VSCode, the first time you try to build (ctrl+b) it will prompt you to configure your TypeScript task runner. The defaults should work.

**Comment by Stevenic** [comment]
You can also build from the command line by just installing typescript:

```
npm install --g typescript
```

And then running `tsc` from the `src` folder. Output files go to the `build` folder and should be manually copied to `lib`.

**Comment by morsh** [comment]
Hi @Stevenic 
[@palashjhabak]
I've tried above method (after pull).

There are a few issues::
1. I'm getting errors:
`
$ tsc
Session.ts(143,58): error TS2339: Property 'toString' does not exist on type 'never'.
bots/ChatConnector.ts(320,73): error TS2339: Property 'toString' does not exist on type 'never'.
bots/ChatConnector.ts(402,77): error TS2339: Property 'toString' does not exist on type 'never'.
bots/ChatConnector.ts(409,21): error TS2339: Property 'code' does not exist on type 'Error'.
bots/Library.ts(91,22): error TS2405: The left-hand side of a 'for...in' statement must be of type 'string' or 'any'.
bots/Library.ts(92,25): error TS2342: An index expression argument must be of type 'string', 'number', 'symbol', or 'any'.
bots/UniversalBot.ts(525,60): error TS2339: Property 'toString' does not exist on type 'never'.
dialogs/EntityRecognizer.ts(260,29): error TS2339: Property 'toString' does not exist on type 'never'.

dialogs/IntentDialog.ts(261,65): error TS2339: Property 'toString' does not exist on type 'never'.
dialogs/IntentDialog.ts(314,58): error TS2339: Property 'toString' does not exist on type 'never'.
dialogs/LuisRecognizer.ts(135,77): error TS2339: Property 'toString' does not exist on type 'never'.
`

2. Probably some changes of version for "tsc" [My Version: 2.1.0-dev.20161019] but most of the files under "lib" are marked as changed by simple changes like :
`
var sprintf = require('sprintf-js');
var Channel = require('./Channel');
var consts = require('./consts');
var prompts = require('./dialogs/Prompts');
`

Updated to (quotes instead of single quote):
`
var sprintf = require("sprintf-js");
var Channel = require("./Channel");
var consts = require("./consts");
var prompts = require("./dialogs/Prompts");
`

3. should the file "botbuilder.d.ts" be copied manually as well?

Other than that, running a few "node app.js" from the examples works fine.

Thanks.

**Comment by nwhitmont** [comment]
relates to #1217

**Comment by nwhitmont** [comment]
@Stevenic any update on this?

**Comment by bilby91** [comment]
I'm having different errors when trying to compile source code on `src` folder.

```
Session.ts(265,12): error TS2394: Overload signature is not compatible with function implementation.
dialogs/EntityRecognizer.ts(39,11): error TS2430: Interface 'ILuisDateTimeEntity' incorrectly extends interface 'IEntity<string>'.
  Types of property 'resolution' are incompatible.
    Type '{ resolution_type: string; date?: string; time?: string; comment?: string; duration?: string; }' has no properties in common with type 'IEntityResolution<string>'.
dialogs/EntityRecognizer.ts(49,11): error TS2430: Interface 'IChronoDuration' incorrectly extends interface 'IEntity<string>'.
  Types of property 'resolution' are incompatible.
    Type '{ resolution_type: string; start: Date; end?: Date; ref?: Date; }' has no properties in common with type 'IEntityResolution<string>'.
dialogs/EntityRecognizer.ts(104,26): error TS2345: Argument of type '(entity: ILuisDateTimeEntity) => void' is not assignable to parameter of type '(value: IEntity<string>, index: number, array: IEntity<string>[]) => void'.
  Types of parameters 'entity' and 'value' are incompatible.
    Type 'IEntity<string>' is not assignable to type 'ILuisDateTimeEntity'.
      Types of property 'resolution' are incompatible.
        Type 'IEntityResolution<string>' is not assignable to type '{ resolution_type: string; date?: string; time?: string; comment?: string; duration?: string; }'.
          Property 'resolution_type' is missing in type 'IEntityResolution<string>'.
dialogs/PromptRecognizers.ts(83,18): error TS2430: Interface 'IChronoDuration' incorrectly extends interface 'IEntity<string>'.
  Types of property 'resolution' are incompatible.
    Type '{ start: Date; end?: Date; ref?: Date; }' has no properties in common with type 'IEntityResolution<string>'.
dialogs/PromptRecognizers.ts(279,27): error TS2345: Argument of type 'IChronoDuration' is not assignable to parameter of type 'IEntity<string>'.
  Types of property 'resolution' are incompatible.
    Type '{ resolution_type: string; start: Date; end?: Date; ref?: Date; }' has no properties in common with type 'IEntityResolution<string>'.
```

**Comment by sgellock** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botbuilder-channels/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
