### ISSUE TITLE
Registered treated as a keyword in Enum definition

### ISSUE THREAD

**Issue by rohanbadlani** [Microsoft/BotBuilder#1293]
Hi,

I was using FormFlows and used "Registered" as a enum element. Although the form rendered the enum element but the form does not accept "Registered" as an option on the Emulator.

Regards,
Rohan

**Comment by chrimc62** [comment]
I tried this and it worked fine.  I also can't think of any reason that there would be anything special about registered.  Can you give supply more details on how to repro this?
