### ISSUE TITLE
skype client carousel not working

### ISSUE THREAD

**Issue by ashay-88** [Microsoft/BotBuilder#1294]
Hi, 
I have created a bot, its on skype. in reply it returns carousel card to user. carousel doesnt particularly includes image. all it has is some text and select button. 
Works good on emulator but tried on Skype windows desktop client, skype android, skype web client and skype web developer edition , no luck.
can anybody help me to figure out, which platform of skype supports carousel cards.

Thanks, 
Ashay

**Comment by dipumon** [comment]
At present, skype channel only allows upto 5 cards in a carousel.
If the carousel has more than 5 cards, then it won't work in skype.

**Comment by brandonh-msft** [comment]
Another thing to note is that, at present, the Skype Preview UWP app doesn't handle them that well, either. Best to test with Skype Web or Desktop client.

**Comment by nickcordrey** [comment]
Please also make sure that images conform to the requirements in https://docs.botframework.com/en-us/skype/getting-started/#cards-and-buttons i.e.

Images sent to Skype cards need to be stored on an HTTPS endpoint
Images should be HTTPS, up to 1024x1024, up to 1MB in size, and PNG or JPEG

Please reopen if the above doesn't address your issue - thanks!

**Comment by ashay-88** [comment]
Hi Nick,
I am not using any image in my carousel hero card. I mentioned in my question, I am having a button and text. 

I understand as of Skype carousel  is not supporting more than 5 cards.
But if I have less than 5, still I am not getting appropriate reply. 
PS: I updated my SKype android client, also Skype Desktop. 
I get this response on desktop and on skype android, it comes with card but card looks empty, just "Play" text appears. I click on play but no luck.

![image](https://cloud.githubusercontent.com/assets/20703721/18775862/9312d0f2-8182-11e6-825e-39a06dc07b6a.png)

**Comment by slidenerd** [comment]
so basically let me summarize this, if skype has a limit of 5 items in a carousel and messenger has a limit of 15 items in the carousel, should i use the session.message.agent  to identify who is the client and render carousels based on that? that would it cross platform right or is there any other way to find out the type of client you are interacting with
