### ISSUE TITLE
Direct Line API GET

### ISSUE THREAD

**Issue by SamuelTassell** [Microsoft/BotBuilder#1297]
So I've got a simple node app running using the 'directline-line' package on npm. My question is, is there a better way of checking for new messages other that using a 'setTimeout' to GET from the API to check for the messages continually? I can't imagine this is the most efficient way. Examples would be great, thank you.

**Comment by dandriscoll** [comment]
Hi @SamuelTassell, for now, the GET in a loop is the best way. We're working on a new version where the polling GET isn't necessary.

**Comment by SamuelTassell** [comment]
Ok good to know. Great to hear you're working on an alternative. Ta :)
