### ISSUE TITLE
Documentation for Bot Builder v1

### ISSUE THREAD

**Issue by varunsethnsit** [Microsoft/BotBuilder#1298]
We have build a bot with Bot Builder v1, however, we don't find any documentation for the same as of now, its v3 all the way. Please help with the documenation for the earlier bot version v1.

**Comment by dandriscoll** [comment]
Hi @varunsethnsit, you can find our v1 docs at http://docs-v1.botframework.com/

**Comment by Andrea-Orimoto** [comment]
Closing this issue as resolved, @varunsethnsit  please reopen if you need further info. thanks!
