### ISSUE TITLE
Some behaviours with prompt.choice

### ISSUE THREAD

**Issue by Hanoko** [Microsoft/BotBuilder#1299]
Hi,

I have two things that I don't know if I can change them:
1. Everytime I use a Prompt.choice I get a "Options:" message. Can I delete this somehow? 

2. When I use the Prompt.choice Telegram can put the choices into the keyboard, not into a message. Can we do this with the BotBuilder or is impossible?

Thank and best regards,
Pablo

**Comment by eanders-MS** [comment]
Can you post an example of how you're calling Prompts.choice?

In Telegram, we display Prompts.choice as a set of buttons to the user. Telegram won't display buttons unless some text accompanies them, so if there is no text sent along, we add "Options:" so that Telegram will not reject the message.

**Comment by eanders-MS** [comment]
The other part of your question about keyboards: While we don't directly support Telegram's popup keyboard, it is still possible to display one by sending a channel-specific command in the channelData field of the message activity. In BotBuilder/NodeJS this field is called sourceEvent. Here's an example:

This keyboard would resemble a numeric keypad:
```
reply.sourceEvent = {
    telegram: {
        method: "sendMessage",
        parameters: {
            text: "This is a reply keyboard",
            parse_mode: "Markdown",
            reply_markup: JSON.stringify({
                "keyboard": [
                    [{ text: "1" }, { text: "2" }, { text: "3" }],
                    [{ text: "4" }, { text: "5" }, { text: "6" }],
                    [{ text: "7" }, { text: "8" }, { text: "9" }],
                    [{ text: "*" }, { text: "0" }, { text: "#" }]
                ]
            })
        }
    }
};
```

**Comment by eanders-MS** [comment]
@Hanoko closing this issue now. If you're still having trouble please open a new issue and we'll continue to troubleshoot.
