### ISSUE TITLE
Bot Builder for NodeJs - error in example

### ISSUE THREAD

**Issue by Aleksion** [Microsoft/BotBuilder#13]
Hi,

I apologize if I'm reporting in the wrong place - but this had be stumble when I first tried out the code.

The example on: http://docs.botframework.com/builder/node/guides/core-concepts/#publishing-to-the-bot-connector-service

has an error in the code: it uses a textBot even though it should be using a BotConnectorBot.

The text states this correctly, however, the coding example doesn't

**Comment by Stevenic** [comment]
Thanks for the fix... I merged it :)
