### ISSUE TITLE
[NodeJS] Mixing LUIS and Command Dialog

### ISSUE THREAD

**Issue by JpEncausse** [Microsoft/BotBuilder#130]
Hi,

I'm using LUIS for all "official" commands but I also want to mix it with Command Dialog because it's a real pain if you forget a LUIS action.

For instance I want to add /quit on my LuisDialog
- I have to create an Intent
- I wan't add a quick regexp and I can't put 2 dialog on the same path.

May by I should use a Middleware ?

**Comment by Stevenic** [comment]
We've talked about adding the matches() function to the LuisDialog for just this case. In the short run you could do your on RegEx based matching in LuisDialog.onDefault() which could avoid the need to chain dialogs together.

**Comment by Stevenic** [comment]
As a side note let me give my quick thoughts on the use of middleware. At this point I foresaw middleware being used in two primary cases. 1) you want to add a helper function or property onto the Session object that's available globally. or 2) you want to redirect an incoming message to a different dialog flow (first run experience, flighting, etc.)

You could argue that '^quit' might be something you want to handle globally so you could do it as middleware but to get it to work properly you'd have to do some serious surgery on the sessions sessionState object. I'd do it there as a last resort.

**Comment by Stevenic** [comment]
Merged with a UserVoice issue for voting purposes as it's essentially the same request:

https://feedback.botframework.com/forums/354222-bot-builder-sdk/suggestions/13457397-adding-multiple-dialogs-luis-or-others-to-a-bot
