### ISSUE TITLE
sourceEvent with prompts for client using Direct Line API

### ISSUE THREAD

**Issue by SamuelTassell** [Microsoft/BotBuilder#1301]
So we are building our own client. After starting the conversation the bot sends a prompt with a couple of options, currently when I recieve the message from the bot in my client it returns as a string:

`Hi ryi8kXbT, what can I help you with?\n   1. Maintenance\n   2. Billing\n   3. General\n   4. Emergency`

My question is how can I send the prompt in a custom schema for my client to handle?

For example, with Facebook to use their new bits and bobs we use sourceEvent:

```
var replyMessage = new builder.Message(session).text("Testing");

replyMessage.sourceEvent({ 
        facebook: { 
            quick_replies: [{
                content_type:"text",
                title:"Red",
                payload:"DEVELOPER_DEFINED_PAYLOAD_FOR_PICKING_RED",
                image_url:"https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Button_Icon_Red.svg/300px-Button_Icon_Red.svg.png"
            },            
            {
                content_type:"text",
                title:"Blue",
                payload:"DEVELOPER_DEFINED_PAYLOAD_FOR_PICKING_BLUE",
                image_url:"https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Button_Icon_Blue.svg/768px-Button_Icon_Blue.svg.png"
            },
            {
                content_type:"location"
            }]
        }
    });

session.send(replyMessage);
```

So for directline can I do something like:

```
var replyMessage = new builder.Message(session).text("Testing");

replyMessage.sourceEvent({ 
        directline: { ... }
    });

session.send(replyMessage);
```

Or even better (somehow setting the client name as the source?):

```
var replyMessage = new builder.Message(session).text("Testing");

replyMessage.sourceEvent({ 
        MYCLIENTNAME: { ... }
    });

session.send(replyMessage);
```

Thank you, any help would be amazing :)

**Comment by dandriscoll** [comment]
Once you're down to the ChannelData field, that property is sent unmodified to the client.

@stevenic, is sourceEvent keyed by channel or is it a bare wrapper for ChannelData?

**Comment by SamuelTassell** [comment]
Just to add I'm currently doing this:

```
builder.Prompts.choice(session, `Hi ${session.userData.name}, what can I help you with?`, ["Maintenance","Billing","General","Emergency"]);
```


I'd like to keep the above so I can test with the emulator but then adding...
```
.sourceEvent({ 
        directline: { ... }
    });
```
...to this somehow?

I've noticed I can get the `session.message.source`, so in the emulators case it's `emulator` and directlines case `directline`. So I could do something like:

```
if ( session.message.source == 'directline' ){
   var replyMessage = new builder.Message(session).text("Testing");
   replyMessage.sourceEvent({ 
        directline: { ... }
   });
   session.send(replyMessage);
} else {
   builder.Prompts.choice(session, `Hi ${session.userData.name}, what can I help you with?`, ["Maintenance","Billing","General","Emergency"]);
}
```

But I'd like to chain it like the following:

```
builder.Prompts
     .choice(session, `Hi ${session.userData.name}, what can I help you with?`, ["Maintenance","Billing","General","Emergency"])
     .sourceEvent({ 
          directline: { ... }
     });
```
Unfortunately I'm unable to test anything as I'm away from the PC, the answer might be right in front of me :)

**Comment by SamuelTassell** [comment]
Ok so after loads of trail and error(s) this is as far as I've got:
```
var msg = new builder.Message(session).text(question).sourceEvent({ 
    directline: {
        message: {
            text: question,
            buttons:[{
                type: "postback",
                title: "Maintenance",
                payload: "Maintenance"
            },
            {
                type: "postback",
                title: "Billing",
                payload: "Billing"
            },
            {
                type: "postback",
                title: "General",
                payload: "General"
            },
            {
                type: "postback",
                title: "Emergency",
                payload: "Emergency"
            }]
        }
    }
});
builder.Prompts.choice(session, msg, ["Maintenance","Billing","General","Emergency"]);
```
It's really close to what I need but the buttons aren't showing in the emulator, I need to be able to test in the emulator and directline at the same time if possible.

Thanks in advance :)

**Comment by SamuelTassell** [comment]
So according to the [documentation](https://docs.botframework.com/en-us/node/builder/chat-reference/classes/_botbuilder_d_.prompts.html#choice). If I add a `IMessage` to the `choice`... `Any listStyle options will be ignored`. So that explains why I'm not getting the buttons in the emulator.

So the question is, is there a better way of doing things to avoid the `listStyle` from being stripped in the emulator and I'm assuming other platforms, like FB Messenger?

This works, but seems overkill:

```
let question = `Hi ${session.userData.name}, what can I help you with?`;
let msg;

if ( session.message.source == 'directline' ){
    msg = new builder.Message(session).text(question).sourceEvent({ 
        directline: {
            message: {
                text: question,
                buttons:[
                    { type: "postback", title: "Maintenance", payload: "Maintenance" },
                    { type: "postback", title: "Billing", payload: "Billing" },
                    { type: "postback", title: "General", payload: "General" },
                    { type: "postback", title: "Emergency", payload: "Emergency" }
                ]
            }
        }
    });
} else {
    msg = question;
}

builder.Prompts.choice(session, msg, ["Maintenance","Billing","General","Emergency"]);
```
Again, thanks in advance :)

**Comment by SamuelTassell** [comment]
I tided up the above and got rid of the unnecessary data, limiting to one line within a dialog using a basic function:
```
function botPrompt(session: any, question: string, options: Array<string>){
    let msg: any;
    if ( session.message.source == 'directline' ){
        msg = new builder.Message(session).text(question).sourceEvent({ 
            directline: {
                message: {
                    text: question,
                    buttons: options
                }
            }
        });
    } else {
        msg = question
    }
    return builder.Prompts.choice(session, msg, options);
}
```
```
botPrompt(session, `Hi ${session.userData.name}, what can I help you with?`, ["Maintenance","Billing","General","Emergency"]);
```

I'd still like a cleaner example if possible.

**Comment by SamuelTassell** [comment]
Added the `retryPrompt` in the same function. This is getting messy, can someone tell me if this is the right way of doing it. I think I might be better validating the users answer client side, prior to sending... Using this in real-time messaging might be a little problematic.
```
function botPrompt(session: any, question: string, retry: string, options: Array<string>){
    console.log(session);
    let msg: any;
    let rePrompt: any;
    if ( session.message.source == 'directline' ){
        msg = new builder.Message(session).text(question).sourceEvent({ 
            directline: {
                message: {
                    text: question,
                    buttons: options
                }
            }
        });
        rePrompt = new builder.Message(session).text(retry).sourceEvent({ 
            directline: {
                message: {
                    text: retry,
                    buttons: options
                }
            }
        });
    } else {
        msg = question;
        rePrompt = retry;
    }
    return builder.Prompts.choice(session, msg, options, { retryPrompt: rePrompt } );
}
```
```
botPrompt(session, `Hi ${session.userData.name}, what can I help you with?`, "I'm sorry that wasn't an option, please choose again.", ["Maintenance","Billing","General","Emergency"]);
```

**Comment by slidenerd** [comment]
I was testing your code @SamuelTassell and it seems it doesnt work
Look at this screenshot, I tried it on both desktop and mobile to confirm this isnt a desktop issue
![test](https://cloud.githubusercontent.com/assets/5139030/18878962/3c8ad5c4-84f0-11e6-8554-71505d73d5cd.gif)

`let replyMessage = new builder.Message(session).text('testing')
    replyMessage.sourceEvent({
        facebook: {
            quick_replies: [{
                content_type:"text",
                title:"Red",
                payload:"DEVELOPER_DEFINED_PAYLOAD_FOR_PICKING_RED",
                image_url:"https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Button_Icon_Red.svg/300px-Button_Icon_Red.svg.png"
            },            
            {
                content_type:"text",
                title:"Blue",
                payload:"DEVELOPER_DEFINED_PAYLOAD_FOR_PICKING_BLUE",
                image_url:"https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Button_Icon_Blue.svg/768px-Button_Icon_Blue.svg.png"
            },
            {
                content_type:"location"
            }]
        }
    });
    session.send(replyMessage);`
Exact code i guess

**Comment by slidenerd** [comment]
@SamuelTassell sorry mate, there was a duplicate send in my code overwriting the previous one, your code is perfect 💃 i should have known better

**Comment by SamuelTassell** [comment]
@slidenerd: Haha not to worry. Always a few bugs when you use other people's code :). As far as this issue goes... Dev's, can you have a read through and at least tell me whether my approach is the only way?

**Comment by palmerabollo** [comment]
@SamuelTassell Thank you very much for sharing your code. I'm following this issue very closely because I have exactly the same question. Lets see if people at Microsoft can clarify it because this is is a must to be able to build rich clients using the Direct Line channel.

**Comment by chrimc62** [comment]
@dandriscoll could you comment?

**Comment by Stevenic** [comment]
@SamuelTassell sorry for the delay. In general I think you're approach is fine. You might look at [this example](https://github.com/Microsoft/BotBuilder/tree/master/Node/examples/basics-customChoicePrompt) for ways of packaging up your choice prompt to look more like the built-in one.

**Comment by gilesbutler** [comment]
I'm currently facing the same issue as the OP. I know this has been closed a while but it still feels like it isn't solved. We have various bots already built and we don't want to go through each one adding extra code just to handle choice prompts in DirectLine. Plus every time we create a new bot we have to remember to add extra code to support DirectLine, we can't just enable it and use it with our custom client. 

It would be great if the choices were returned as a separate property, something like this...

    {
      "type": "message",
      "id": ...
      "timestamp": ...
      "channelId": "directline",
      "from": ...
      "conversation": ...
      "replyToId": ...
      "text": "Have you used a bot before?",

      "choices": [
        "Yes", "No"
      ]
    }

Is this possible @Stevenic?

Thanks

**Comment by dandriscoll** [comment]
Hi @gilesbutler, are you using Direct Line 1.1 or 3.0?

**Comment by gilesbutler** [comment]
Hey @dandriscoll, I'm using Direct Line 3.0. Thanks
