### ISSUE TITLE
Be able to kick-off many conversations

### ISSUE THREAD

**Issue by just1689** [Microsoft/BotBuilder#1303]
I would like to be able to start the conversation between a bot and a user from the bot's side. 
Also, I need to be able to do this for many users.

**Comment by brandonh-msft** [comment]
[see here](https://github.com/Microsoft/BotBuilder/issues/1288#issuecomment-248688004)

and no reason you can't simply repeat that process for many users.

**Comment by just1689** [comment]
Thanks. That's interesting.

**Comment by msft-shahins** [comment]
You can look at these samples showing how you can proactively create a new conversation with a user that your bot have interacted with before: 

C#: https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/core-CreateNewConversation
Node: https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node/core-CreateNewConversation
