### ISSUE TITLE
ChoiceStyleOptions in FormFlow as Quick replies

### ISSUE THREAD

**Issue by kenyeung128** [Microsoft/BotBuilder#1305]
Hi, right now, ChoiceStyleOptions in FormFlow has several options, but not supporting style like"Quick Replies" in facebook for users to choose. Is there anything to override it or support it? Thanks.

**Comment by ejadib** [comment]
Hi @kenyeung128, a few days ago I wrote something for Prompt Dialogs. You might take some ideas and make it work for Forms: http://southworks.com/blog/2016/09/21/using-facebooks-quickreplies-with-promptdialogs/

**Comment by kenyeung128** [comment]
hi @ejadib , that's a great article. Thanks a lot, i will try to make one for flowforms
