### ISSUE TITLE
Telegram - message.user.name is not set

### ISSUE THREAD

**Issue by pcostantini** [Microsoft/BotBuilder#1306]
Hi!
I'm using **session.message.user.name** to display the user's name.
Through the Telegram channel, the *name* field is not set in the *user* object. It seams that the incoming message to the Bot API endpoint is not including the *name* field in the *from* object. Other channels are including this field.

BTW, the same occurs with the C# SDK.

**Incomming Message to API Messages endpoint**
![image](https://cloud.githubusercontent.com/assets/57197/18766637/9ed47f1c-80f1-11e6-867b-3d559187e805.png)

The same is ocurring in C#:
![image](https://cloud.githubusercontent.com/assets/57197/18766653/acdc4ea0-80f1-11e6-9a4c-b8cd644de567.png)

A workaround in the meantime is to use *sourceEvent.callback_event.from.first_name* when the message comes from Telegram:
![image](https://cloud.githubusercontent.com/assets/57197/18766698/deab4f08-80f1-11e6-9d3d-e97f63e06c1e.png)

Should this be considered an SDK bug or an API bug?
Thanks in advance!
PabloC.

**Comment by eanders-MS** [comment]
The Telegram user's username is sent in this field, if provided. Telegram usernames are optional. This is a privacy feature of Telegram. You can set your username in the Settings section of Telegram.

Read more about Telegram usernames here: https://telegram.org/faq#usernames-and-telegram-me

**Comment by pcostantini** [comment]
That was it! Thanks @eanders-MS !

**Comment by Nisthar** [comment]
@pcostantini So, there's no way to get the username if the user didn't set it already?
