### ISSUE TITLE
DirectLine API Conversation crossing browsers

### ISSUE THREAD

**Issue by MohawkMan** [Microsoft/BotBuilder#1307]
I posted a quest on stackoverflow earlier about having conversations cross browsers: 
[http://stackoverflow.com/questions/39649732/bot-connector-direct-line-api-cross-conversation](url)

After, digging a little deeper and stepping through the emulator I realized that the emulator is using a different sub domain (webchat as apposed to directline). I also realized that webchat is using a cookie to store a UserId. Since the emulator makes the message post with from: null I can only assume you are setting the from prop of the messages server side with the UserId from the cookie. 

So as I see it right now, if you write your own JS to work with the DirectLine API you either have to generate a temporary "UserID" and use it in the from of each message or send the initial message with from: null and get the Id the API generated by pulling the messages and reading it out. Is that right? It seems like there would be an easier way. Is there anything wrong with just generating a random id to use in the from property? 

On the other side, this also means if you are using the emulator, the user can't restart the bot without killing the cookie. Which could be good and bad.

Am I missing something?

**Comment by dandriscoll** [comment]
Hi @MohawkMan, you should generate a random ID when your client loads. (Or, you can use an existing user ID within your application, like a device ID.) The auto-assign behavior has been a source of confusion and will not exist in the next version of Direct Line.

**Comment by MohawkMan** [comment]
Thanks, it is easy enough to do I just didn't know if it would affect anything else. I am working with another developer that actually did the bot design so I wasn't sure. I guess on his end whatever I put in the from came through as both ChannelAccountID and ChannelAccountName, so i wanted to ask before I did it.

Thanks for the quick reply.

**Comment by MohawkMan** [comment]
@dandriscoll One more quick question, I know the documentation says the messages aren't stored for very long. Does that mean it is safe to assume that the random ID does not need to be a GUID? HOw long does that value live in the system?

**Comment by dandriscoll** [comment]
The user ID is not stored, but it can be used inside your bot to correlate state, so it depends on how your bot is set up. Worst case, your bot uses that ID forever and never expires it (which is the default behavior), so you would need to plan accordingly.

A GUID is probably the safest answer; you can base-48 or base-62 (yes, 62) encode it if you want to make it more compact.

**Comment by dandriscoll** [comment]
Closing this older issue. Please feel free to open a new issue if you have further questions.
