### ISSUE TITLE
Suggestion - change Extension methods from internal to public

### ISSUE THREAD

**Issue by kenyeung128** [Microsoft/BotBuilder#1308]
hi, it looks like a number of useful extension methods as below that are only internal in the BotBuilder, would it be possible to make it public?

internal static IList<Attachment> GenerateHeroCards(this FormPrompt prompt)

internal static IList<Attachment> GenerateHeroCard(this FormPrompt prompt)

**Comment by Andrea-Orimoto** [comment]
@kenyeung128, great suggestion, we've added it to our backlog. No timeline yet. Feel free to reopen if you have more questions. Thank you!
