### ISSUE TITLE
Restrict Firewall Port on my Cloud Server to MSBot Server

### ISSUE THREAD

**Issue by JpEncausse** [Microsoft/BotBuilder#1312]
Hi,
I opened a port on my cloud server to talk to MS Bot Framework.
Can I restrict incoming request to a given IP Address to avoid atacks / port scanner, etc ... ?
What IP address should I set ?

**Comment by brandonh-msft** [comment]
see my response on #1318

**Comment by dandriscoll** [comment]
Responded on the related issue that @brandonh-msft linked. Closing this issue so we have a single thread.
