### ISSUE TITLE
Bot in a clustered express application

### ISSUE THREAD

**Issue by naeemshaikh27** [Microsoft/BotBuilder#1313]
Hi all,

I wanted to scale my node-express-bot application with the usual code.

```
if( cluster.isMaster ) {
  // Create a worker for each CPU
  for( var i = 0; i < cCPUs; i++ ) {
    cluster.fork();
  }
}
else {
  var app    = express();
  var routes = require( './routes' )( app );
  app
    .use( express.bodyParser() )
    .listen( port );
}
```
Now this server also runs my bot, the problem is i can not get `session.privateConversationData.persistSession` persisted on all the processes running in the cluster. Is there any way I can have the session to be stored somewhere outside, like Redis, so the data will be available to whole cluster? Or is it still impossible to scale the bot on a clustered environment?

**Comment by willportnoy** [comment]
The idea behind the bot data bags (e.g. private conversation data) is that they're stored externally to your bot in the Bot Framework State Service, so that you can scale across multiple nodes.  Do you see some evidence that state is not persisted across nodes?

More details at:
https://docs.botframework.com/en-us/technical-faq/#where-is-conversation-state-stored

**Comment by naeemshaikh27** [comment]
yes I get `session.privateConversationData.persistSession` as  `undefined ` across multiple nodes

**Comment by naeemshaikh27** [comment]
I find from documentation that we need to provide a storage as an option to universal bot connector, and it says we need to write `saveData `and `getData `methods of our own, so do we require the `deleteData `method to be implemented as well?

**Comment by naeemshaikh27** [comment]
@willportnoy can you tell me when `deleteData()` gets called? I need to test my implementation of `deleteData`

**Comment by mxiamxia** [comment]
@naeemshaikh27 I have the same need that have to put session to the external storage. The document indicates I can set RedisStore under ChatConnector, but no sure what is the key(sessionid) to retrieve the specific conversation session object from other instance? Can you share some piece of your code here?

**Comment by willportnoy** [comment]
@naeemshaikh27 I don't see it called when I search through the source.  Normally, we have a "/deleteprofile" slash command that will clear the bot data bags - @Stevenic is that correct?

**Comment by naeemshaikh27** [comment]
@mxiamxia  here is sample code i wrote
```
var storage = require('../storage/bot.storage.js');
var bot = new builder.UniversalBot(connector,{storage:storage});
```
And the bot.storage.js

```
var redis = require("redis");
var client = redis.createClient();

client.on("error", function (err) {
    console.log("Not able to connect to Redis " + err);
});

exports.saveData = function (context, data, callback) {
    if (context.userId) {
            if (context.persistUserData) {
                client.set(context.userId+'_userStore',JSON.stringify(data.userData || {}));
            }
            if (context.conversationId) {
                client.set(context.userId+':'+context.conversationId+
                    '_conversationStore',JSON.stringify(data.privateConversationData || {}));
            }
        }
        if (context.persistConversationData && context.conversationId) {
            client.set(context.conversationId+'_conversationStore',JSON.stringify(data.conversationData || {}));
        }
        callback(null);
};

```

Similar to `saveData()` method you have to implement `getData()`

**Comment by slidenerd** [comment]
I am assuming @naeemshaikh27 that you want to store data in the master process so that the workers can share it, have you tried [THIS](https://www.npmjs.com/package/cluster-store) library

**Comment by naeemshaikh27** [comment]
@slidenerd that module will cause trouble if you scale horizontally(on multiple machines)

**Comment by Stevenic** [comment]
I haven't implemented delete yet. We should add a work item for that @willportnoy

**Comment by willportnoy** [comment]
@stevenic I'll add to TFS a work item for "exposing delete on bot data bags through Node"

**Comment by willportnoy** [comment]
I'm going to close this item for now - we're tracking the feature enhancement in our internal backlog.  Please open a new issue for further discussions.
