### ISSUE TITLE
How to get ChannelIdin OnCompletionAsyncDelegate

### ISSUE THREAD

**Issue by Johndgnzj** [Microsoft/BotBuilder#1315]
I am using a IDialog with FormFlow to build a bot
i'm confused how to get correct context.ChannelId in event of "OnCompletionAsyncDelegate"
a simple code like below:
```
    [Serializable]
    public class OrderDialog
    {
        public static IForm<OrderDialog> BuildForm()
        {
            var builders = new FormBuilder<OrderDialog>();
            OnCompletionAsyncDelegate<OrderDialog> processOrder = async (context, state) =>
            {
                IMessageActivity reply = context.MakeMessage();
                reply.Text = string.Format("You come from {0} ", context.ChannelId ); // but context.ChannelId equals null...
                await context.PostAsync(reply);
            };
            return new FormBuilder<OrderDialog>()
                    .OnCompletion(processOrder)
                    .Build();
        }

    }
```

**Comment by willportnoy** [comment]
You might consider using the dialog that calls the FormDialog to access properties from the message in case they're not available in the [completion] delegates within FormDialog.

**Comment by chrimc62** [comment]
Let us know if this does not solve your issue.

**Comment by Johndgnzj** [comment]
dialog solve my problem.

btw, i would like to know how long will context's userdata live in session?
is any document write about this?

**Comment by willportnoy** [comment]
@Johndgnzj https://docs.botframework.com/en-us/technical-faq/#where-is-conversation-state-stored has more details.  in general, the data in the state service lives until you delete it.  you can implement the bot state interfaces to get other behavior.  please open a new issue for further discussion.
