### ISSUE TITLE
Sending FB's quick reply using Microsoft Bot Framework c#

### ISSUE THREAD

**Issue by KIBASSA** [Microsoft/BotBuilder#1319]
Hi, 
I implemented my bot following the proposed procedure on this link
https://blog.botframework.com/2016/09/15/facebook-messenger-updates/

But when I click on the button, I do not get the "payload" but rather "title"

How can I do to get the 'payload' from message.Text (message is Activity)   ?

Thank you in advance for your help

Kibassa

**Comment by jameslew** [comment]
That's odd.  I'll be back in the office in the morning and take a look.  What do you get in channelData (or sourceEvent) from Facebook?

**Comment by ejadib** [comment]
@KIBASSA I don't think you will get the payload in the activity.Text property. The payload of the selected quick reply will come as part of the channelData. Complementing the post @jameslew wrote, I put together an [small sample](http://southworks.com/blog/2016/09/15/sending-facebooks-quick-replies-using-microsoft-bot-framework/) showing how to access the payload of the selected quick reply.

**Comment by KIBASSA** [comment]
Thanks for your help.
It's exactly that
