### ISSUE TITLE
[Question] Priority with Enhancements

### ISSUE THREAD

**Issue by khrome83** [Microsoft/BotBuilder#132]
I see a lot of enhancement requests coming in. FanOut, Facebook, etc. 

I am still learning, but I hope to participate when I get a better grasp of everything. Until then, do we have some way to prioritize the backlog? Is there any way to upvote enhancements (user voice) or something?

For example, I would put FaceBook before FanOut, due to the amount of exposure it would garner the project.

**Comment by Stevenic** [comment]
UserVoice is [here](https://feedback.botframework.com/forums/354222-bot-builder-sdk)

**Comment by Stevenic** [comment]
I moved all of the enhancement requests to UserVoice so they can be voted on by the community.
