### ISSUE TITLE
Bot on AWS hosting

### ISSUE THREAD

**Issue by afficionaddo** [Microsoft/BotBuilder#1321]
Hi,

I am trying to host my bot c# on AWS. 
I am facing an issue in SSL.

I generated certificate from StartSSl.com but it gives an 500 internal server error in BotManagerController.cs when I do 'Test connection to bot'.

I am unable to debug the issue. Please help or recommend what kind of certificates will work for the bot framework? Will certificates from third-arty free sites like StartSsl work?

**Comment by puneetsngh** [comment]
@afficionaddo you can try cloudflare, getting and setting ssl certificate with cloudflare is easy

**Comment by willportnoy** [comment]
You should also be able to verify the SSL certificate for you web site in your browser as well, before even considering it as a web service.

**Comment by afficionaddo** [comment]
Thanks for the reply @puneetsngh 
Buddy do I need to configure anything else? Also the HTTPS cert will be a normal one or something extra property should it have for BotFramework compatibility. Sorry if sound naive!

**Comment by afficionaddo** [comment]
Thanks for the reply @willportnoy !
Do I need to configure anything else also or just the HTTPS cert apply, verification in browser and i am good to go?

**Comment by willportnoy** [comment]
@afficionaddo with regard to SSL, testing the https endpoint in the browser should be sufficient.  Once you have that working, then you'll need to deploy your bot code and make sure bot authentication works as well.

**Comment by dandriscoll** [comment]
It depends on which OS you're using. If you're using a stock Windows installation from Microsoft, using a browser is probably a decent test. If possible, please try your certificate before buying it.

**Comment by willportnoy** [comment]
I'm going to close this issue, but feel free to open a new issue for further discussions.
