### ISSUE TITLE
"The 'form' field is unrecognized" - Facebook REST

### ISSUE THREAD

**Issue by Freshchris01** [Microsoft/BotBuilder#1322]
When I send a message to the Facebook bot via REST Api with the following JSON, I get the response the 'from' field is unrecognized, but it's actually here.
`{
  "type": "message",
  "id": "...",
  "timestamp": "2016-09-24T02:47:03.8956722Z",
  "serviceUrl": "https://facebook.botframework.com",
  "channelId": "facebook",
  "from": {
    "id": "...",
    "name": "..."
  },
  "conversation": {
    "id": "..."
  },
  "recipient": {
    "id": "...",
    "name": "bstest"
  },
  "text": "Hy, from remote!",
  "channelData": {
    "sender": {
      "id": "..."
    },
    "recipient": {
      "id": "..."
    },
    "timestamp": 1474685223681,
    "message": {
      "mid": "...",
      "seq": 35,
      "text": "Testtest"
    }
  }
}`

**Comment by dandriscoll** [comment]
Hi @Freshchris01, the 'from' field's ID must match your bot's identity within the channel (i.e., your bot's FB ID) and it must be consistent with the MSA App ID your bot used to authenticate the request.

The Bot Builder copies this from the 'recipient' field in incoming requests. Is that the value you're using?

**Comment by Freshchris01** [comment]
Thanks for your reply, it works quite well now.
