### ISSUE TITLE
Facebook location quick_reply 

### ISSUE THREAD

**Issue by bobzsj87** [Microsoft/BotBuilder#1326]
I've been searching in the code and didn't find the `contentType: "location"` quick reply of Messenger. I wonder it is not implemented. Is it possible to do under validatedPrompt (but what's the prompttype as I need to get from session.message.entities)... Thanks

**Comment by slidenerd** [comment]
have you tried using the sourceEvent to send that quick reply?

**Comment by bobzsj87** [comment]
@slidenerd thanks for the reply. I've thought about it and it should probably work. But problem is how do I the the result like the prompt in the waterfall manner, i.e.,with `(session, results)`?
Thanks again.

**Comment by slidenerd** [comment]
i have the same requirement @bobzsj87 to handle location in my bot, will try something and if I find a solution, will come back and update this thread

**Comment by slidenerd** [comment]
@bobzsj87  did you check [THIS](http://southworks.com/blog/2016/09/15/sending-facebooks-quick-replies-using-microsoft-bot-framework/) i am trying it out

**Comment by slidenerd** [comment]
let replyMessage = new builder.Message(session).text('Can you please share your location?');
    replyMessage.sourceEvent({
        facebook: {
            quick_replies: [
                {
                    content_type: "location"
                }
            ]
        }
    });
    session.send(replyMessage);

This doesnt work, just publishes an undefined after saying can you please share your location

**Comment by slidenerd** [comment]
This doesnt work either
    let replyMessage = new builder.Message(session).text('Can you please share your location?');
    replyMessage.sourceEvent({
        facebook: {
            recipient: {
                id: session.message.user.id
            },
            message: {
                text: "Please share your location:",
                quick_replies: [
                    {
                        content_type: "location",
                    }
                ]
            }
        }
    });
    session.send(replyMessage);

**Comment by slidenerd** [comment]
This is the closest i have got in testing quick replies
![test](https://cloud.githubusercontent.com/assets/5139030/18879013/76597d28-84f0-11e6-9d47-6a0b01b24b58.gif)

```
let replyMessage = new builder.Message(session).text('testing')
    replyMessage.sourceEvent({
        facebook: {
            quick_replies: [{
                content_type:"text",
                title:"Red",
                payload:"DEVELOPER_DEFINED_PAYLOAD_FOR_PICKING_RED",
                image_url:"https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Button_Icon_Red.svg/300px-Button_Icon_Red.svg.png"
            },            
            {
                content_type:"text",
                title:"Blue",
                payload:"DEVELOPER_DEFINED_PAYLOAD_FOR_PICKING_BLUE",
                image_url:"https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Button_Icon_Blue.svg/768px-Button_Icon_Blue.svg.png"
            },
            {
                content_type:"location"
            }]
        }
    });
    session.send(replyMessage);
```

**Comment by jameslew** [comment]
@slidenerd, I just re-verified that your last sample (when session.send is the last thing the bot does) leave the buttons up Facebook Messenger (mobile and web).    Technically I'm using a var instead of let, but can't imagine that would matter.

**Comment by slidenerd** [comment]
thank you @jameslew and it works @bobzsj87 
the above code I pasted actually works, I just had a duplicate send overriding the results

**Comment by bobzsj87** [comment]
@slidenerd thank you. I just wrote a simple Prompt like dialog to get user location in Messenger:

```
bot.dialog('/facebook_location', new builder.SimpleDialog((session, args) => {
    args = args || {};
    // initial setup
    let initialRetry = 3;
    session.dialogData.shareText = args.shareText || session.dialogData.shareText;
    session.dialogData.wrongLocationText = args.wrongLocationText || session.dialogData.wrongLocationText;

    let retry = session.dialogData.hasOwnProperty('maxRetries') ? session.dialogData.maxRetries : initialRetry;
    let entities = session.message.entities;

    // only dialogData has "maxRetries" property, otherwise do not check as first runs
    // because using session data directly would possibly cause infinite loop
    if (session.dialogData.hasOwnProperty('maxRetries') && Array.isArray(entities) && entities.length && entities[0].geo){
        session.endDialogWithResult({response:entities[0].geo})
    }
    else if (retry == 0){
        // max retry, quit
        session.endDialogWithResult({});
    }
    else{
        if (retry < initialRetry){
            session.send(session.dialogData.wrongLocationText || "Looks it is not a valid location.");
        }

        let replyMessage = new builder.Message(session).text(session.dialogData.shareText || "Please share your location.");
        replyMessage.sourceEvent({
            facebook: {
                quick_replies:
                [{
                    content_type:"location"
                }]
            }
        });
        session.send(replyMessage);

        retry -= 1;
        session.dialogData.maxRetries = retry;
    }

}))
```



So you can basically use it like `session.beginDialog("/facebook_location", {shareText:"just give me your location"});`

**Comment by jameslew** [comment]
Looks like this is resolved, I'm going to go ahead and close it.
