### ISSUE TITLE
Question: Why does the BOT endpoint should be 'https'?

### ISSUE THREAD

**Issue by afficionaddo** [Microsoft/BotBuilder#1327]
Hi,

May be I am just spitballing here, but my question is

Why does the BOT endpoint should be 'https'?

**Comment by slidenerd** [comment]
well i guess they dont want anyone snooping on people s messages as it is estimated that a lot of personal information will be sent out on these channels, the finance bots that you see currently on the botstore already ask tonnes of personal questions

**Comment by palmerabollo** [comment]
It could be useful if the emulator could work with http bots (for development). For production I agree that making https mandatory is a good practice that prevents third-parties from eavesdropping on your personal conversations.

**Comment by dandriscoll** [comment]
SSL/TLS has become pervasive enough that many sites, services, and libraries are making HTTPS mandatory. We rely on the x.509v3 to help ensure the bot's endpoint is authentic, and we feel HTTPS is appropriate for the kind of data sent between a bot and the Bot Framework.

Many hosting providers, including Azure Web Apps, make it easy to create a website accessible via HTTPS. There are still configurations that will not work (and certificate authorities that have not been verified/approved into Microsoft's root program) but in general, there are many options to create a bot that sits behind a secured endpoint.

**Comment by jameslew** [comment]
I'm assuming your question has been answered.  Feel free to ping us again if you need any further clarifications.  In the mean time I'm going to close the issue.
