### ISSUE TITLE
Trouble with Dialog Chains

### ISSUE THREAD

**Issue by MCKRUZ** [Microsoft/BotBuilder#1330]
So I have this dialog chain which I'm calling like so...

public static readonly IDialog<string> dialog = Chain.PostToChain()

        .Select(msg => msg.Text)

        .Switch(
             new RegexCase<IDialog<string>>(new Regex("^hi", RegexOptions.IgnoreCase), (context, txt) =>
             {
                 return Chain.ContinueWith(new GreetingDialog(),
                        async (ctx, res) =>
                        {
                            var token = await res;
                            var name = "User";
                            context.UserData.TryGetValue<string>("Name", out name);
                            return Chain.Return($"You are logged in as: {name}");
                        });
             }),
             new DefaultCase<string, IDialog<string>>((context, txt) =>
             {
                 int count;
                 context.UserData.TryGetValue("count", out count);
                 context.UserData.SetValue("count", ++count);
                 string reply = string.Format("{0}: You said {1}", count, txt);
                 return Chain.Return(reply);
             })).Unwrap().PostToUser();

The dialog looks like this

[Serializable]

public class GreetingDialog : IDialog
{

    public async Task StartAsync(IDialogContext context)
    {
        await context.PostAsync("Hi I'm John Bot");
        context.Wait(MessageReceivedAsync);
    }

    public async Task MessageReceivedAsync(IDialogContext context, IAwaitable<IMessageActivity> argument)
    {
        var message = await argument;
        var userName = String.Empty;
        var getName = false;
        context.UserData.TryGetValue<string>("Name", out userName);
        context.UserData.TryGetValue<bool>("GetName", out getName);

        if (getName)
        {
            userName = message.Text;
            context.UserData.SetValue<string>("Name", userName);
            context.UserData.SetValue<bool>("GetName", false);
        }

        if (string.IsNullOrEmpty(userName))
        {
            await context.PostAsync("What is your name?");
            context.UserData.SetValue<bool>("GetName", true);
        }
        else
        {
            await context.PostAsync(String.Format("Hi {0}.  How can I help you today?", userName));
        }
        context.Wait(MessageReceivedAsync);
    }
}

when I try to run this I get back an error that says "Exception: Microsoft.Bot.Builder.Internals.Fibers.ClosureCaptureException: anonymous method closures that capture the environment are not serializable, consider removing environment capture or using a reflection serialization surrogate"

Can someone point me in the right direction? I'm not sure what I'm doing wrong here.

**Comment by willportnoy** [comment]
The ClosureCaptureException should mention which object has been captured in the message - what does it say?

More information:
https://docs.botframework.com/en-us/technical-faq/#ensure-that-all-dialogs-are-serializable

**Comment by MCKRUZ** [comment]
I figured it out.  Here is the solution

The issue seems to be with the following anonymous method:

async (ctx, res) =>
{
    var token = await res;
    var name = "User";
    context.UserData.TryGetValue<string>("Name", out name);
    return Chain.Return($"You are logged in as: {name}");
});
Try replacing that with a method instead:

return Chain.ContinueWith(new GreetingDialog(), AfterGreetingContinuation);

private async static Task<IDialog<string>> AfterGreetingContinuation(IBotContext context, IAwaitable<object> res)
{
    var token = await res;
    var name = "User";
    context.UserData.TryGetValue<string>("Name", out name);
    return Chain.Return($"You are logged in as: {name}");
}
However, take into account that the continuation method won't likely be called until you "end" the GreetingDialog with a context.Done().

**Comment by vamsitp** [comment]
I guess the actual issue was with using `context` instead of `ctx ` inside the anonymous method
