### ISSUE TITLE
Security - Keys

### ISSUE THREAD

**Issue by remms** [Microsoft/BotBuilder#1331]
Hi,

Let's suppose that signing keys from bot framework leaks - in this case the bot implementation may be unsecured up to 5 days until the keys are updated, even the leakage being known by the team responsible for the connector, right?

Would be interesting to have an activity "reset keys" telling the bots to refresh;

Or at least, is there a way to configure the cache to be smaller than 5 days? So that at least we reduce the window for potential attackers.

**Comment by dandriscoll** [comment]
Hi @remms, we're reducing the refresh interval to 24 hours to match industry norms. There is still a theoretical 24-hour vulnerability window although this can be addressed by restarting any instances, which typically causes them to refresh their cache.

**Comment by dandriscoll** [comment]
Closing as we're following industry standard here. Please at-mention or open a new issue if you'd like to discuss further. Thanks!
