### ISSUE TITLE
Slack: Removing a bot from channel does not trigger conversationUpdate

### ISSUE THREAD

**Issue by euanlau** [Microsoft/BotBuilder#1332]
`conversationUpdate` event is received when the bot is added to the channel.
However, removing a bot from channel does not generate such event.

**Comment by craigjensen** [comment]
I can confirm that this is a bug in the Slack channel.  We have a fix in testing and will get it deployed soon.

**Comment by craigjensen** [comment]
Fix has been deployed.  Please reopen if you are still seeing this issue
