### ISSUE TITLE
Which userid is consistent at all times?

### ISSUE THREAD

**Issue by slidenerd** [Microsoft/BotBuilder#1333]
First of all, thank you for your fantastic efforts guys, I have a few questions about the framework. I researched this stackoverflow issue thread extensively before posting these. Hopefully, I did not miss something.

What is the difference between session.message.sourceEvent.sender.id and session.message.user.id, do they always reflect the same values? 

The address field also seems to have user ids inside it. Which of these user ids stay consistent all the time? 

What happens to conversations when multiple conversations exist with the same user. On the bot emulator, you can easily change the conversation but when is a new conversation created with real channels like facebook, slack, twitter etc. 

Are you supposed to save conversation objects in the database once the 32kb bot bag becomes full? If yes, should it be stored as an array for each user since each user will have multiple conversations.

Thank you for all the answers in advance

**Comment by willportnoy** [comment]
sourceEvent/ChannelData generally reflects the native channel format so these will differ across channels.

I don't believe we modify the user IDs or maintain some mapping between channel userID and connector userID.  The channel itself may have some mapping to prevent leaking userIDs that are global across multiple bots.

The address field is supposed to be a representation of the conversation (serviceUrl, channelId, conversationId, botId, userId).

You might consider using the "private user in conversation" data bag if you want a more narrowly scoped data bag.

**Comment by slidenerd** [comment]
Thank you for all the answers, it really helped a lot
