### ISSUE TITLE
Old dialog version being reused?

### ISSUE THREAD

**Issue by srozga** [Microsoft/BotBuilder#1337]
Hi

I have a bot that I have developed and tested locally. I have enabled the Skype channel and have been testing it to test my code. I have been testing the conversation and have made some code updates to dialog that is invoked down the conversation chain. However, those changes to the dialog do not seem to take effect through the Skype client. I've tried rebuilding and republishing the app. I've tried /deleteprofile and each time I enter the dialog, I hit the issue that an old version of my code is executing.

I tried debugging the app through the emulator with ngrok. And I run into the same issues. This really surprises me as I keep on starting a new conversation each time in the emulator, so I would assume it wouldn't be caching any version of my assembly that is no longer valid. 

Any advice?

thanks!

**Comment by willportnoy** [comment]
In the C# version of the SDK, we don't serialize any code - we just serialize the class member state of the dialogs on the stack.  So if you're hitting older code, it must be an issue with the code available at that endpoint.  For example, perhaps the deployment does not contain the code you think it does?

**Comment by iassal** [comment]
@srozga, there might be old assemblies in the server. If you are using Web deploy, select remove additional files at destination on your publish profile.

![image](https://cloud.githubusercontent.com/assets/4086459/18890399/442ed256-8501-11e6-8b02-770dbedc3b10.png)

**Comment by srozga** [comment]
Thanks, I did have a mess on the server. Not a bot framework issue.
