### ISSUE TITLE
Problems running demo-skype-calling from localhost via ngrok

### ISSUE THREAD

**Issue by gkc** [Microsoft/BotBuilder#1340]
Worked fine when I deployed to an internet-facing machine

**Comment by rposbo** [comment]
but ngrok *is* an internet-facing machine.. how odd..

**Comment by gkc** [comment]
With my bot running on my laptop, on a LAN, communicating via ngrok, when I place a Skype call to my bot, then the call drops after a short while. On a couple of occasions, the failed to connect at all.

With my bot running on a host on the internet (not via ngrok) then the demo works perfectly

I have not tried using ngrok with my bot on an internet-facing host

**Comment by tomlm** [comment]
I am guessing that you there is something about ngrok proxying which is not working.  Closing as an ngrok issue
