### ISSUE TITLE
Calling option not showing up in Skype client

### ISSUE THREAD

**Issue by gkc** [Microsoft/BotBuilder#1341]
Documentation in app.js says:
"If you're adding calling to an existing bot can take a few minutes for the calling option to show up."

I waited 10 minutes, stopped & re-started Skype several times. Still no option to call. Went for a walk. An hour later, still no option to call.

Resolved by removing the Skype contact completely and re-adding it (via the bot page on dev.botframework.com)

**Comment by jameslew** [comment]
Ill make sure the documentation is updated to reflect this.

**Comment by KrishnanA** [comment]
Thanks for the report. We will update the documentation to indicate that it can take up to 24 hrs.

**Comment by Andrea-Orimoto** [comment]
Hi @gkc, you mention the documentation in app.js, where is it exactly?

**Comment by Andrea-Orimoto** [comment]
This has been fixed in the sample comment
https://github.com/Microsoft/BotBuilder/blob/master/Node/examples/demo-skype-calling/app.js

Thanks a lot for reporting this issue, and let us know if you have any further questions.
