### ISSUE TITLE
BOT need to send google map to Skype 

### ISSUE THREAD

**Issue by dhirajgupta1** [Microsoft/BotBuilder#1342]
Hello,

Is there any way to display google map with markers by Skype chat bot.
Please suggest how to achieve this.

Thanks,
Dhiraj

**Comment by willportnoy** [comment]
You can send cards with images, but I don't believe there are clickable regions on those images.

**Comment by nickcordrey** [comment]
Yes you would need to convert the map into an image and send as a card, with URL to launch the map.
