### ISSUE TITLE
[C#] Slow response

### ISSUE THREAD

**Issue by wswijaya** [Microsoft/BotBuilder#1343]
Hi,
Whenever I initiate a conversation to my bot after it was idle for sometime I have to wait for at least 30s before it response, subsequent request get fast respond, around 3s. 
What could be the cause? could it be the bot authentication? any suggestion to resolve this issue?

thanks & regards,
Wongso

**Comment by jameslew** [comment]
If you're the only one using your bot, its probably the cloud hosting service letting your web app "go to sleep".  Once your bot is getting more traffic on a regular basis it won't do that anymore.

**Comment by wswijaya** [comment]
thanks James, im currently doing testing, so it is a small group and low volume. I enabled "alwayson" and notice improvement.
