### ISSUE TITLE
No message received from Slack when a Slack channel is mentioned using #....

### ISSUE THREAD

**Issue by gcsonka** [Microsoft/BotBuilder#1347]
I am getting no response in the bot framework when a message is sent from Slack where a Slack channel  (like '#general') is mentioned in the message.

Looks like my MessageController (straight from the bot builder sample code)  never receives the payload.

In application Insight I can see the activity for the "typing" event, but note for the message event that typically follows.
I tried using the bot connector NuGet package as well as building it from latest source  - no luck.

**Comment by willportnoy** [comment]
I wonder if the '#' character is being interpreted by markdown.

**Comment by craigjensen** [comment]
This is a bug in our Slack channel.  Fix will be deployed soon

**Comment by gcsonka** [comment]
Thank you. Any idea when the fix will be released?

**Comment by craigjensen** [comment]
Fix has been deployed.  Please reopen if you are still seeing this issue
