### ISSUE TITLE
source event is not working for kik

### ISSUE THREAD

**Issue by somprabhsharma** [Microsoft/BotBuilder#1348]
I am trying to send a customized message using source event in kik. But I am getting Internal Server Error, Please provide a example for kik to send a customized message using source event.
The code which I am trying is below -
`const quickReplyKik = {
    'type': 'text',
    'body': 'Or pick an option below',
    'keyboards': [
      {
        'type': 'suggested',
        'responses': [
          {
            'type': 'text',
            'body': 'Help'
          },
          {
            'type': 'text',
            'body': 'Report Card'
          }
        ]
      }
    ]
  }
  session.send(new builder.Message(session)
    .sourceEvent({kik: quickReplyKik}))`

**Comment by LarsLiden** [comment]
Your message is malformed and being rejected by Kik with the following error:  

> "{\"message\":\"[] is too short\",\"error\":\"InvalidParameters\"}"

**Comment by LarsLiden** [comment]
A few things to note in your code:
- The Kik native message must be in the form of an array of messages
- The Kik native message must include a recipient (i.e. at "To")

Here's the properly formatted message:
```
var to = session.message.user.name;
const quickReplyKik = { 'messages' : [ { 'to' : to, 'type': 'text', 'body': 'Or pick a option below', 'keyboards': [ { 'type': 'suggested', 'responses': [ { 'type': 'text', 'body': 'Help' }, { 'type': 'text', 'body': 'Report Card' } ] } ] } ]}; 
session.send(new builder.Message(session).sourceEvent({kik: quickReplyKik}));`
```

Also, there's no need to resort to a Kik native message.  You can create a keyboard (as per below) that will display buttons on all the channels:

```
	var buttons = [];	
	buttons.push(builder.CardAction.imBack(session, "Help", "Help"));
	buttons.push(builder.CardAction.imBack(session, "Report Card", "ReportCard"));
	
	var card = new builder.HeroCard(session).title("Or pick an option below").buttons(buttons);	
	var attachments = [];					
	attachments.push(card);
												
	var msg = new builder.Message(session)
	.attachments(attachments);
	session.send(msg);
```
