### ISSUE TITLE
I can't seem to get Confirm in the FormBuilder to work

### ISSUE THREAD

**Issue by mindcrash** [Microsoft/BotBuilder#135]
So I've made a pretty straight forward form flow similar to the one demonstrated at Build:

```csharp
return new FormBuilder<StockForm>()
        .Message("Welcome to the Stock Bot")
        .Field("Symbol", validate: async (state, val) =>
        {
            var quote = await quotes.GetAsync((string)val);

            var result = new ValidateResult();

            if (quote.Symbol == string.Empty)
            {
                result.Feedback = string.Format("{0} is not a valid symbol", quote.Symbol.ToUpper());
                result.IsValid = false;
            }
            else
            {
                result.Feedback = string.Format("{0} is at {1}", quote.Symbol.ToUpper(), quote.Price);
                result.IsValid = true;
            }

            return result;
        })
        .Field("BuyOrSell")
        .Field("Units")
        .Field("TransactionDate")
        .Confirm("I will {BuyOrSell} {Units} units of {Symbol} at {TransactionDate}. Please confirm that this is OK.")
        .AddRemainingFields()
        .Message("Thanks for ordering stocks")
        .Build();
```

Every step from the "Symbol" field down to the confirmation is processed correctly. But when the bot is at the confirm step it either gets stuck (while sending "yes" or "Yes" to it) or it sometimes does respond but sends back the following message ("Thanks for ordering stocks") a few times.

Did I make a mistake somewhere or did I stumble upon a bug in the form builder?

**Comment by chrimc62** [comment]
This looks like it should be totally fine.  What version of the Builder are you using?  We are getting close to a new release that includes better support for exceptions--it is possible you are getting an exception?

**Comment by mindcrash** [comment]
I am using 1.0.2 and as far as I can tell haven't seen any exceptions pop up until now...

**Comment by chrimc62** [comment]
There are two issues:
1) A deadlock which will be fixed in the next release.
2) I suspect you are not connecting up your form in such a way that it restarts.  You should do something like:
       internal static IDialog<StockOrder> MakeRoot()
        {
            return Chain.From(() => FormDialog.FromForm(StockOrder.MakeForm));
        }

**Comment by mindcrash** [comment]
Hah, that was it indeed and something I overlooked. Thanks!
