### ISSUE TITLE
Support facebook echo messages?

### ISSUE THREAD

**Issue by kenyeung128** [Microsoft/BotBuilder#1350]
Hi, is there anyway to get the messages sent through facebook through the botbuilder framework? the reason is to get what messages (including message id) has been sent in facebook format and logged it using bot analytics tools like dashbot.io.

**Comment by jameslew** [comment]
I'm not sure I'm quite clear on your question - but I think you're asking if you can get to the raw Facebook message from the user.

If so, you can get that out of ChannelData (on the C# SDK) or SourceEvent on the Node SDK.  They include the original message content sent from Facebook to the bot.

**Comment by kenyeung128** [comment]
Thanks @jameslew , I can get the message sent from facebook to bot, but I would like the message from bot to facebook, do you know how to get it?Thanks

**Comment by jameslew** [comment]
We don't have a way for you to get that.   The message you send to the bot framework is transformed on the way through to Facebook.  I can add this as an enhancement request though for a future release.

**Comment by jameslew** [comment]
I've added this enhancement request.  Right now it would not be easy in our current model to do this, so it will take some consideration.
