### ISSUE TITLE
FormFlow: skipping steps

### ISSUE THREAD

**Issue by mitkodi** [Microsoft/BotBuilder#1351]
There is a problem with skipping dependent/cascading fields or confirmations, which happens if we pass steps and return back to a previous (master) one that resets subsequent (dependent) field(s) or invalidate confirmation.

**Example of skipping dependent/cascading fields**
Let we have a from with 3 fields (F1, F2 and F3) and possible choices for F2 depends on F1, so every time we change the value of F1 we clear the current value of F2. If we fill up F1 and F2 and re-enter F1 (which resets F2) we won't be asked to re-enter F2 leaving its value as unspecified.

**Example of skipping confirmation**
In AnnotatedSandwichBot, where the cost depends on sandwich's length, after confirming the price we could change the length but won't be asked to confirm the new cost.

I found that I can overcome these issues with small change in FormDialog.MoveToNext which setts the Phase for a Completed step to Ready if the underlying field is unknown. The single problem that I found with this was repeating existing confirmation step(s) (for confirmation fields IsUnknown is always true), but I can easily solve it by using condition for confirmation fields. Even though I think that I have a solution, I would prefer if I could solve it without maintaining my own version of bot builder.

Any suggestions?

**Comment by chrimc62** [comment]
Thanks for bringing this to our attention.  I've made a fix and it should work (unless your field is optional) in the next release.

You can make this work in several ways in the current release including using SetNext on a field to define the delegate for determining the next step.  I do agree though that this is more difficult than making it happen automatically.  To that end for a non-optional field if you set its value to unknown, then the step will be marked ready again and re-executed in your case.  Optional fields have unknown as an acceptable value so we have no reliable way to make that happen so I left it alone.

**Comment by mitkodi** [comment]
I don't think that SetNext could be useful in this case.
