### ISSUE TITLE
Let user know when bot is not available

### ISSUE THREAD

**Issue by vboctor** [Microsoft/BotBuilder#1356]
When I publish my bot with a coding bug that makes it crash, I can send messages to from Skype with no response from the bot.  I expect that all these messages end up being dumped, but the user has no understanding of what is going on and doesn't known that they should retry later.

From memory, Skype also shows the bot as online even though it is in a crashed state and can't even boot up.  I suspect there is no heartbeat and Skype always marks bots as online.

Not sure about the right experience here.

**Comment by slidenerd** [comment]
Well I assume you are loading something like perhaps setting up the Skype API or data from LUIS Intent or something of that sort. If you observe the source code closely, there is a Session.js file which has a variable called autoBatchDelay with a value of 250 ms, This value is being used in session.send, in simple words
if your bot.dialog('/', (session)=>{}) gets triggered and you are processing something here, one way you can do is call 
session.send('trying to my brains, please give me a moment, my bonehead creator just left it on the table')

setTimeout(()=>{
heavyOps()
}, AUTO_BATCH_DELAY_TIMEOUT + 50) //extra 50 ms to ensure the message is sent first and then the op is done

this way, your message goes first regardless of whether your op succeeded for failed

**Comment by tomlm** [comment]
We've gone back and forth on this.  

One way of doing this is responding back to the user with "We couldn't talk to the bot".  I think some channels will do this and some don't.

Modeling online status is something we should add to the protocol (for example Skype 4 Business has presence information which is "person is away from desk") 

One of the reasons we have a Ping activity is the thought we would use that to monitor the "health" of a bot and then we could set online status as appropriate.

**Comment by chrimc62** [comment]
@tomlm can you comment or close as appropriate?

**Comment by dandriscoll** [comment]
I think it depends a bit on the channel, but I'm not sure that presence is the right way to communicate a failure.

We implement this in Web Chat by showing a small error message to the user if the client tried to send a message to the bot and the bot returned an error.

Similarly, in Skype, I've seen a small orange icon appear if I try to send a message to a bot that's misconfigured. The error message appears near the text input box.

I think both of these are better than modifying the bot's presence. The crash may only be occurring for a single user, so changing the bot's online/offline status seems problematic. Indicating a delivery failure is much closer to the right behavior.
