### ISSUE TITLE
"activity.Attachments" act differently on Skype & Bot Framework Emulator

### ISSUE THREAD

**Issue by chungweileong94** [Microsoft/BotBuilder#1357]
In my code I wrote something like:
`if(activity.Attachments == null) { //Execute some code }`

This line of code act differently on Skype & Bot Framework Emulator, if user didn't send any attachments. 

_Below are what they both act:_

**Skype**
if user didn't send any attachments, the `activity.Attachments` will always return `null`

**Bot Framework Emulator**
if user didn't send any attachments, the `activity.Attachments` will not return `null`, instead the `activity.Attachments.Count` will return 0

It took me an hour to realize the issue, since it is not easy to debug on Skype
Is it one of the SDK bug or ???
Will it also happen if I deploy on other platform like Facebook messager or Slack?

**Comment by danmarshall** [comment]
which SDK, C# or Node ?

**Comment by chungweileong94** [comment]
@danmarshall C#

**Comment by msft-shahins** [comment]
This is not a bug in the SDK. It is different behavior in the activity sent by emulator vs skype. @tomlm can comment more on this discrepancy. But I highly recommend writing your code in a way that is more resilient to these minor behavior differences from channel to channel. For example, in your case the following check `if (message.Attachments?.Any() == true)` might be a better check.

**Comment by chungweileong94** [comment]
@msft-shahins Thanks for help!
