### ISSUE TITLE
Bot emulator (v3.0.0.59) encounters array index out of bounds exception and crashes

### ISSUE THREAD

**Issue by Lee-William** [Microsoft/BotBuilder#1358]
Hi! 

I can't seem to get the bot emulator to work properly. 

Steps: 
1. Run Bot Emulator -> OK 
2. Run Bot program -> OK
3. type hi in Bot Emulator -> OK 
4. Bot program returns a "Welcome" message -> NOK, Emulator crashes (See screenshot attached)

Bot Emulator Version: 3.0.0.59 

![emulator exception](https://cloud.githubusercontent.com/assets/12124953/19013296/72d37480-87ff-11e6-9d9e-dea7dd04f0b7.PNG)

Would you be able to provide the bot emulator program pdb files so that we can debug on our end?

**Comment by chrimc62** [comment]
We have released a new much improved emulator.  Please try it out and if you have a problem open a new issue.

**Comment by Lee-William** [comment]
Thanks !
