### ISSUE TITLE
'quick reply''s image is different on smartphone compared to webbrowser

### ISSUE THREAD

**Issue by KIBASSA** [Microsoft/BotBuilder#1359]
Hi to all, 
I have a problem with my chatbot.
Images on the 'quick reply' appear differently on Samrtphone compared to the webbrowser.
How can I do to have a good image on smartphone
Someone has an idea?
Thanks advance for your help
![imageemiko2](https://cloud.githubusercontent.com/assets/8443316/19017230/badbb296-8832-11e6-9cc3-f3d9a7875544.png)
![emokoimagephone](https://cloud.githubusercontent.com/assets/8443316/19017229/badb0328-8832-11e6-87a3-fcc751b4ea80.png)

**Comment by LarsLiden** [comment]
Can you try this with a pre-existing bot (not yours) that runs on Facebook?  It would be good to eliminate the Facebook client as the source of the problem.  Do they render find with a different bot?

**Comment by KIBASSA** [comment]
I have found the solution
The size of my images was too small.
The minimum accepted by facbook is 200 x 200
I replaced by larger image and it works.
I follows facebook recommendations for Open Graph image dimensions/aspect https://developers.facebook.com/docs/sharing/best-practices?hc_location=ufi#images

Thanks
