### ISSUE TITLE
FormFlow prefilling values and go to specific step

### ISSUE THREAD

**Issue by kenyeung128** [Microsoft/BotBuilder#1360]
Hi, in Formflow from c#, is there any way prefilling values and go to specific step? Because sometimes some information has been filled by user and most likely they are the same next time. Thank you.

**Comment by willportnoy** [comment]
Yes, pass an initial state to the FormFlow constructor:

https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/FormFlow/FormDialog.cs#L152

**Comment by chrimc62** [comment]
Let us know if this does not address your issue.
