### ISSUE TITLE
Question:: How can I get the original FB messenger JSON that FB accepts/recognizes?

### ISSUE THREAD

**Issue by afficionaddo** [Microsoft/BotBuilder#1363]
Hi,

I am setting up analytics for my bot. But the tool recognizes only FB-messenger JSON.

So how/ or where can I see/get the JSON that FB messenger accepts?
I want to track incoming messages so will the channel field be of any help?

**Comment by rposbo** [comment]
I've not set up FB messenger with a bot yet myself, so I'm making some assumptions here: are you asking how to intercept the actual request/response that hits the `/api/messages` endpoint when accessing your bot via facebook messenger?

If so, perhaps something like `ngrok` (although this may not be realistic, given how long FB can take to accept a messenger bot perhaps) - like this? https://robinosborne.co.uk/2016/09/19/debugging-botframework-locally-using-ngrok

If that's not suitable, then perhaps proxy your bot and use this proxy url within the bot portal; try 
* http://requestb.in/
* https://www.runscope.com/

I believe both of these will intercept *and forward* traffic, such that you can continue to use your bot but also view the raw HTTP traffic that passes to and from it.
