### ISSUE TITLE
[Skype] conversationUpdate membersRemoved bug?

### ISSUE THREAD

**Issue by divinemanwah** [Microsoft/BotBuilder#1365]
When listening for the event `conversationUpdate`, the `membersRemoved` property holds incorrect data. For example, I removed a user from the group, but the entity it holds is that of the bot instead of the removed user/s.

BotBuilder version 3.2.3
Platform: NodeJS

**Comment by nickcordrey** [comment]
Thanks for reporting - we are aware of this issue and will be resolving it in a forthcoming release.
