### ISSUE TITLE
demo-skype-calling bot doesn't pick up call and no request from Skype seen in ngrok

### ISSUE THREAD

**Issue by MikeLeonard** [Microsoft/BotBuilder#1367]
Hi

I have demo-skype working, but when I run demo-skype-calling and call it from the development version of the web-app (https://web.skype.com/en/?ecsoverride=developer), it just rings and rings. I can't see any data in the ngrok web interface either so I don't think Skype is sending anything.

Am I doing something wrong? Is there something else I can try, or is the problem perhaps on the Skype end? Thanks in advance.

Please note that:
- The bot does work in Skype for messaging, i.e. it says 'Hi... Please call me to interact with me.' Other example Skype messaging bots I've tried have also worked.
- I've set "<ngrok link>/api/calls" as my bot calling endpoint, and have my CALLBACK_URL in the app.js set as the same.
- I've tried this for a couple of days now, so it's not due to Skype taking several hours to update on the backend.
- I'm calling from chrome on a Macbook in case that's important.
- Like I said, in the ngrok web interface I see the requests from skype for messenging, but nothing comes through for /api/calls.
- I've also tried this on a couple of different home wifi's, not that that should make any difference to it reaching ngrok.

**Comment by MikeLeonard** [comment]
Also...

It doesn't actually 'ring'... it just says 'connecting' and makes a 'dripping water' connection sound while the loading spinner thing spins.

One more thing: I've just got one person using the bot (me) and it's unpublished.

**Comment by KrishnanA** [comment]
Hello, could you let us know if the scenario works from a non-web skype client? Can you provide your Bot Id or Join link please?

**Comment by KrishnanA** [comment]
My mail id is krisana@microsoft.com, in case you want to send me your bot id via email.

**Comment by MikeLeonard** [comment]
Hi Krishnan thanks for looking at this.

I've sent you my join link via email, thanks.

Regarding trying the bot from a non-web skype client, the call button is greyed out for my bot from the Skype mac app... I think because the ability to call bots isn't available in the general-release version of skype yet, is that right? (I read that somewhere on the bot framework site but I can't find where for you sorry). That's where I got the link to development version of the web app (https://web.skype.com/en/?ecsoverride=developer).

**Comment by KrishnanA** [comment]
Thanks Mike. I will investigate and reply back to you via email. I will close this thread since we are following up on email.
