### ISSUE TITLE
session variable value not persisting in waterfall

### ISSUE THREAD

**Issue by irenenaya** [Microsoft/BotBuilder#1368]
Hello. I am having a very strange situation in my code. I have a waterfall dialog in which, at some point, i have the following:

```
function(session, result, next) {
    if (session.message.text == 'forever') {
        session.userData.duration = Infinity; 
        console.log(session.userData.duration); // if i print the value after the assignment, it's correct
        builder.Prompts.time(session, "what time do you want to start?") 
    }
    // more code here in an else block
},
function(session, result, next) {
    console.log(session.userData.duration); } // if i print it here it's null. 

```
So, for some reason, the value of Infinity doesn't persist from one function to the other. The strange thing is that if, instead of assigning Infinity, i assign something else (a string, for example) the value does persist and the second console.log is equal to the first. 
This means i can solve it (hack it, actually) by assigning a string in the first block and then checking if the value is that string, then assigning Infinity in the second block. But i was wondering if there's something intrinsic to the value of Infinity that causes this, or if it's some bug. 

Thank you for any thoughts and thank you for all the awesome work put in the framework!

**Comment by Stevenic** [comment]
It's probably a serialization issue... We use JSON.stringify() and JSON.parse() to persist the value of userData and I don't believe values like `Infinity` or `NaN` will roundtrip properly.  Same thing goes with Dates and RegEx's.

**Comment by irenenaya** [comment]
Oh, cool!!!! That would explain why i was having a nightmare a couple of days ago trying to get the valuesOf() of a date to work properly too!!! It's good to know!
Thanks a lot for your quick and helpful reply, Stevenic! I now know how to work around it. Thank you!
