### ISSUE TITLE
System.Web, System.Configuration, WebApi dependencies

### ISSUE THREAD

**Issue by Maarten88** [Microsoft/BotBuilder#1370]
After a lot of struggle I succeeded getting the BotBuilder running in a selfhosted Owin environment, which  usually is easy with WebApi. I had to learn a lot about the use of Autofac in BotBuilder, which I generally didn't like as it does lots of logic and parameter passing in non-obvious ways.
I eventually worked around those problems, but I think I encountered some bugs and issues that could be fixed or improved. The easiest way to find these issues is to remove the dependency on System.Web, and try to configure the connector without using AppSettings. I few things I found:

BotAuthentication does:

```
MicrosoftAppId = MicrosoftAppId ?? ConfigurationManager.AppSettings[MicrosoftAppIdSettingName ?? "MicrosoftAppId"];
```

A more correct implementation would be:

```
MicrosoftAppId = MicrosoftAppId ?? (actionContext.Request.GetDependencyScope().GetService(typeof(MicrosoftAppCredentials)) as MicrosoftAppCredentials)?.MicrosoftAppId;
```

BotAuthentication also has this no-no:

```
if (HttpContext.Current != null)
    HttpContext.Current.User = Thread.CurrentPrincipal;
```

I think that should be:

```
actionContext.RequestContext.Principal = Thread.CurrentPrincipal;
```

MicrosoftAppCredentials uses a System.Web.HttpRuntime.Cache (which I replaced with a MemoryCache) and inspects the HttpContext.Current.User in ShouldSetToken, which I removed (even if I didn't fully understand what that does, but it still works "on my machine").

I think it would be better to factor out the whole WebApi dependency from the Connector as it seems only required for the BotAuthentication attribute. That attribute could be distributed as a separate nuget, so that it becomes easy to make an AspNetCore implementation in another nuget.

**Comment by chrimc62** [comment]
@dandriscoll can you comment or close as appropriate?

**Comment by dandriscoll** [comment]
@msft-shahins may be better able to weigh in -- he's looking at how this layer sits on frameworks like .Net Core.

**Comment by msft-shahins** [comment]
We prereleased Microsoft.Bot.Connector nuget [3.5.1-alpha](https://www.nuget.org/packages/Microsoft.Bot.Connector/3.5.1-alpha) which adds support for asp.net core to connector SDK. Bot authentication is now implemented as a middleware: https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Microsoft.Bot.Connector.AspNetCore/BotAuthentication.cs#L73 and here is an example asp.net core bot: https://github.com/Microsoft/BotBuilder/tree/master/CSharp/Samples/Microsoft.Bot.Sample.AspNetCore.Echo

Feel free to comment about changes and send pull requests for missing features and bugs.
