### ISSUE TITLE
Config for text length in Hero Card

### ISSUE THREAD

**Issue by astrung** [Microsoft/BotBuilder#1372]
Hi. how can we config for text length when send a card (ex:Hero Card ???) When i send a long message , i get message : "..." instead of a full message !!! So how can we config text length when show messages, or to show full message ??

**Comment by astrung** [comment]
Can any one help me ??

**Comment by LarsLiden** [comment]
Each channel has different limitations on the number of characters they allow.  For example, Skype only allows 51 chars in the Title, Subtitle and Text on a HeroCard.  Kik limits to 87 on text, Telegram to 200 characters.

**Comment by charea** [comment]
hi @LarsLiden, is it possible somehow to change limitation on the number of characters allowed?

**Comment by ashice** [comment]
Hi @LarsLiden @nwhitmont  Has this changed or we are still limited to showing limited chars?

If yes, what is the recommended solution, breaking message into multiples or something else?

**Comment by nwhitmont** [comment]
@ashice You are commenting on a closed issue. 

If you have a question or problem, please [open a new issue.](https://github.com/microsoft/botbuilder/issues/new)
