### ISSUE TITLE
Webchannel: wrodwrap is not working correctly

### ISSUE THREAD

**Issue by ubreddy** [Microsoft/BotBuilder#1374]
in webchannel iframe widget the lines are getting not at whitespaces but with words getting cut. Looks real bad. can we have the wrap functionality without words being cut?

**Comment by Andrea-Orimoto** [comment]
Hi @ubreddy, this will be fixed in the next version, thanks for reporting the issue.

**Comment by ubreddy** [comment]
how would I know when the next release is made/due? is it not better to close the issue once the issue is fixed?
