### ISSUE TITLE
MBF delivering multiple proactive messages in a short time in wrong order.

### ISSUE THREAD

**Issue by somprabhsharma** [Microsoft/BotBuilder#1375]
I am sending multiple proactive message together. So MBF is not delivering the message in correct order. I want to maintain the correct order of the message without giving any timeout in the code. How can I do this ?

**Comment by LarsLiden** [comment]
What channel are you using?  Which language? C# or Node.js?

**Comment by somprabhsharma** [comment]
@LarsLiden: I am using Node.js, and I am using it for messenger, slack, skype, telegram, kik and for channels its happening. If i give a delay of 300ms between those messages, then it works fine otherwise the messages are getting delivered in random order.

**Comment by somprabhsharma** [comment]
@LarsLiden Any update on this?

**Comment by Stevenic** [comment]
@somprabhsharma I'm sorry for the delay. You would need to call `bot.send()` with an array of all the messages to help ensure the delivery order and even that isn't 100% guaranteed.  The other option is you can make individual calls to `bot.send()` but you'll need to pass a callback and wait for each individual delivery to finish.

**Comment by tomlm** [comment]
Many channels don't support guaranteed delivery (email, sms, etc.) Adding delay will help in most cases
