### ISSUE TITLE
PromptDialog.Confirm Supports markdown?

### ISSUE THREAD

**Issue by tjoudeh** [Microsoft/BotBuilder#1376]
I'm trying to display some text in the **PromptDialog.Confirm** in bold using the markdown syntax as the below:
`Dear **{0}** is there anything else I can help you with?` but it is displayed as the following: `Dear **User1** is there anything else I can hep you with?`

The same is working for **PromptDialog.Text**, any clue how to use markdown in PromptDialog.Confirm?

**Comment by LarsLiden** [comment]
Which channel are you using?

**Comment by tjoudeh** [comment]
Testing on Emulator now.

Get Outlook for iOS<https://aka.ms/o0ukef>




On Tue, Oct 4, 2016 at 6:18 PM +0300, "Lars Liden" <notifications@github.com<mailto:notifications@github.com>> wrote:


Which channel are you using?

-

**Comment by tomlm** [comment]
what textformat are you using? make sure it is not set to plain, but "markdown"

**Comment by chrimc62** [comment]
Closed due to age.  If it is still an issue, please reopen.

**Comment by blueprintChris** [comment]
How does one go about changing the textformat from plain to markdown?
