### ISSUE TITLE
Microsoft Bot (webchat channel): 500 Internal Server error: failed to send message

### ISSUE THREAD

**Issue by shahsagarin** [Microsoft/BotBuilder#1378]
We have embedded a Bot on a web page through the web chat channel, if the Bot is **idle** for 10 minutes or so and then a question is asked, the Bot does not respond to it, however when the same question is asked again immediately it responds as expected.

On investigating the network capture, we observed the response received when the question was asked for the first time was 500: Internal Server Error with message as "failed to send message"

**Comment by LarsLiden** [comment]
Some additional information would be helpful for debugging this.  What channel are you using?  Can you share some code?

**Comment by shahsagarin** [comment]
Hi Lars,

It's a web chat control, embedded on web page. Please find below snippet for the issue that we are facing:
![image](https://cloud.githubusercontent.com/assets/8536246/19104782/0c82e85a-8afc-11e6-8349-d7affe21fa31.png)

Note: We checked the logs (issues) for the Web Chat Channel and below is the screenshot for the same -
![image](https://cloud.githubusercontent.com/assets/8536246/19104874/989b2064-8afc-11e6-8eab-4c722c5a5d9e.png)

Hope this helps!

**Comment by dandriscoll** [comment]
Hi @shahsagarin, you bot is generating errors when the web chat control is trying to send messages to it. Please look at your bot's error logs to get more detail.

If you have an Application Insights container, copying the Instrumentation Key into your bot's dashboard in the Bot Framework developer portal will allow you to see detailed error logs, including messages generated from your bot.

**Comment by tomlm** [comment]
Closing due to age
