### ISSUE TITLE
Scalability across machines in Bot

### ISSUE THREAD

**Issue by satyajit-behera** [Microsoft/BotBuilder#1379]
In the Bot documentation, there is a statement:
"Every time we call IDialogContext.Wait our bot is suspended and can be restarted on any machine that receives the message".

My Question is: Where does the Bot store the message and flow and resumes it from any other machine? How is the scalability maintained within the Bot? 

Thanks

**Comment by ankitbko** [comment]
The context and the current state of the bot gets serialized and is stored by the Bot Connector in Bot State Service. The bot maintains a Dialog Stack, when you do `context.Wait(Method1)`, it pushes the method on top of the stack. The stack is then serialized along with other context information and is stored by the Bot Connector. When user sends the message, the corresponding dialog stack and other information is sent to the bot, which can be serialized on any machine, where your 'Method1' will get called.

**Comment by willportnoy** [comment]
@ankitbko is correct - some more details here:
https://docs.botframework.com/en-us/technical-faq/#where-is-conversation-state-stored

**Comment by willportnoy** [comment]
I'm going to close this issue for now - feel free to open a new issue for further discussion.
