### ISSUE TITLE
Microsoft.Bot.Connector.DirectLine still using Microsoft.Rest.ClientRuntime v1.8.2

### ISSUE THREAD

**Issue by JasonBSteele** [Microsoft/BotBuilder#1381]
Hi,

I have an API App that uses the latest BotBuilder 3.2.1 which is dependant on Microsoft.Rest.ClientRuntime > 2.0.0. The API App also provides a service to make DirectLine calls to the bot so uses Microsoft.Bot.Connector.DirectLine. But this is dependant on Microsoft.Rest.ClientRuntime < 2.0.0 so I get problems with method not found or could not load assembly for Microsoft.Rest.ClientRuntime due to the incompatability.

Can Microsoft.Bot.Connector.DirectLine be updated to use the same version of  Microsoft.Rest.ClientRuntime as the BotBuilder?

**Comment by ADefWebserver** [comment]
See the comment on this issue: https://github.com/Microsoft/BotBuilder/issues/1284 it appears that the UWP implementation is causing the issue and they are working on it.

**Comment by JasonBSteele** [comment]
Ah yes, looks like I've created a duplicate - thanks @ADefWebserver.

Still, this is a real pain for me as it will mean re-architecting may application or going back to V1 😒

**Comment by JasonBSteele** [comment]
I have worked around this issue by including the 1.8.2 in a folder other than bin (I caked it bin2) and updating the config to find it like this:

      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Rest.ClientRuntime" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <codeBase version="1.0.0.0" href="bin2/Microsoft.Rest.ClientRuntime.dll" />
        <codeBase version="2.3.2.0" href="bin/Microsoft.Rest.ClientRuntime.dll" />
      </dependentAssembly>

You will need to include bin2 in your project and set it's properties to Content, Do Not Build. I found the older dll in a packages folder and I included it's xml file (not sure if that is necessary).

HTH, Jason

**Comment by elliatab** [comment]
I have a simple client for DirectLine: https://github.com/elliatab/directlineclient 
it's not as complete as the official one but it may help if you have a simple use-case

**Comment by JasonBSteele** [comment]
Thanks @elliatab, this could be really useful if I need to compile it as a Portable Class Library so that a Xamarin mobile app can talk to my bot. (Unfortunately the MS DirectLine client isn't a PCL).

**Comment by tomlm** [comment]
This should be fixed in new client lib releasing in the next week.
