### ISSUE TITLE
[Node] Memory Storage used when instantiating Bot w/o connector

### ISSUE THREAD

**Issue by jmendiara** [Microsoft/BotBuilder#1382]
Not setting an optional connector parameter when instantiating the bot, but using the `connector` method, causes the bot to use the default storage (memory) instead of the connector one

``` ts
let bot = new BotBuilder.UniversalBot(null, {});
let connector = new BotBuilder.ChatConnector({...});
bot.connector('*', connector);
```

**Comment by Stevenic** [comment]
This should be fixed in the latest 3.3.x release.
