### ISSUE TITLE
Link es6 template in examples

### ISSUE THREAD

**Issue by brene** [Microsoft/BotBuilder#1385]
I have recently discovered that there is not a proper ES6 enabled botbuilder template. So I created one myself and added features like autorestarts of the server when the file changes etc. 
It would be great if you could link this in your examples because a lot of people don't want to mess with the configuration but would still like to write ES6.

The template repo is [brene/botbuilder-es6-template](http://github.com/brene/botbuilder-es6-template)

**Comment by willportnoy** [comment]
I added a link to the technical faq:
https://docs.botframework.com/en-us/technical-faq/#what-are-some-community-authored-templates

@brene thank you for sharing.

I'm going to close this issue for now - feel free to open a new issue for further discussion.
