### ISSUE TITLE
how to authenticate user in skype bot by using azure directory

### ISSUE THREAD

**Issue by subhans3tech** [Microsoft/BotBuilder#1387]

**Comment by jameslew** [comment]
I believe you're asking about using Azure Active Directory.  If so, there's not a built in functionality for this, however @matvelloso has a great sample in his github repo.  https://github.com/matvelloso/authbot

**Comment by subhans3tech** [comment]
i have seen it but how can we do it in nodejs

**Comment by subhans3tech** [comment]
how can i do it on nodejs

**Comment by matvelloso** [comment]
We're working on a NodeJS version which relies on passport

**Comment by subhans3tech** [comment]
can you please tell me some time limit

**Comment by chrimc62** [comment]
@matvelloso can you comment on this?

**Comment by matvelloso** [comment]
Update: This is a preliminary version of authbot for Node. This one relies on passport so Node devs should find things familiar: https://github.com/CatalystCode/node-authbot/

**Comment by dandriscoll** [comment]
Closing this issue here. Please feel free to discuss on the node-authbot repo, or open a new issue here if the sample does not meet your needs.
