### ISSUE TITLE
Embedded chat control: How to set username?

### ISSUE THREAD

**Issue by syedaliammar** [Microsoft/BotBuilder#1389]
Hi,
I've embedded the chat control iframe on my webpage and can talk to the bot. However, it greets me like this: _Good afternoon! How can I help you today Mr. 78TJ3FfGDhs?_

The question here is: **How can I set/send the user name property when a user sends the bot a message using the embedded chat control?**

The "Bot Framework Channel Emulator" comfortably allows you to write your name in the "Name" field which can be accessed using the **incomingActivity.From.Name** property:
![image](https://cloud.githubusercontent.com/assets/6023536/19117685/27a8850e-8b1a-11e6-99b6-f44048e2c78f.png)

Thanks, Ammar

**Comment by jameslew** [comment]
That's a great suggestion, but we don't have that capability currently.  I've added it to the enhancement request list for the WebChat control.

**Comment by sitecorian** [comment]
Would be great to be able to pass a query string params that will be picked up as initialization values and passed into user data accessible via API.

**Comment by chrimc62** [comment]
@eanders-MS can you comment or close as appropriate?

**Comment by eanders-MS** [comment]
Hi @syedaliammar This is not possible with the current webchat control, but there is an alternative. We recently released a new webchat control that is in preview, and this control supports passing in an optional username and optional userid.

There is one problem with using this today in an IFRAME scenario: We don't currently provide a way to pass these values as url parameters. We have made a fix for this internally, and it will be available in production soon. Once it is available, you will be able to provide these values on the url, like this:

`https://webchat.botframework.com/embed/YOUR_BOT_ID?s=YOUR_BOT_SECRET&username=DESIRED_USERNAME&userid=DESIRED_USERID`

Each value is optional. If userid is omitted, we generate a random one. If username is omitted, we default to 'You'.

The new webchat control is not enabled by default, but you can enable it by editing your bot's Web Chat channel configuration in the [Dev Portal](https://dev.botframework.com).

**Comment by syedaliammar** [comment]
Hi @eanders-MS,
Thanks, I'll give it a try soon!

**Comment by eanders-MS** [comment]
@syedaliammar, This feature is now live. Please give it a try!

**Comment by sevetseh28** [comment]
@eanders-MS If multiple users are able to set the UserID and Username from the client side then multiple conversations could potentially have the same username and userid? Is that secure? Is there an easy way to generate a random and UNIQUE UserID/Username by default and disallow the client to specify those?
Thanks.

**Comment by debnathSD** [comment]
@eanders-MS I am passing a secret token through the username field (can't pass it through userid because its length is greater than 64 characters) of the webchat URL. But in the webchat, the token is visible as it has been passed via username field. Is there a way to reset the username to 'You' or any other name after passing a token through the username field in the webchat?

**Comment by fjlogrono** [comment]
the same thing happens to me as to you @debnathSD. Have you solved it?
Any other way to pass the token?

**Comment by debnathSD** [comment]
@fjlogrono: Yes!

 In between I have introduced one table where I am storing those long secret tokens with respect to a primary key, I am passing that primary key (which is a unique combo of 32 characters) in the userid field now and getting what I want in my bot!!

**Comment by fjlogrono** [comment]
@debnathSD thanks for the reply. I do not get it.

I'm using bot framework and the direct line channel. When executing in the browser, I send the token with a post activity, so I can make a call to the API and know who the user is.:

```
directLine.postActivity({
      from: { id: 'myUserId', name: 'myUserName' }, // required (from.name is optional)
      type: 'message',
      text: 'This is the token'+token  //Split text on server
  }).subscribe(
      id => console.log("Posted activity, assigned ID ", id),
      error => console.log("Error posting activity", error)
  );
```
In the console everything seems to be fine, but the bot only pulls "message 0"
I can not get a welcome message in the bot, something like 'hello Peter!' and, every time I type something in the bot,, a new session appears, I think by using bot.use ({receive ...

This is my code:


```
bot.dialog('/', [
    function (session, par) {
        if(par!=undefined){
            session.userData.myname = par;
            console.log('init done: '+ par);
            session.send(`Hello ${par}!`);
            console.log(session.message.address.id);
            console.log(session.message.address.conversation.id);
            var message1 = new builder.Message().address(session.message.address).text('message 0');
            bot.send(message1, function (err) {});  // simulate proactive message to user
            console.log('hi again' + session.userData.myname);
            builder.Prompts.text(session, 'How are you '+session.userData.myname+'?');
        }else{
            if(!session.userData.myname){
                console.log(session.userData);
                 console.log('empty');
            }else{
                console.log(session.userData.myname);
            }   
        }
        
    },
    function (session, results) {
        var msj = results.response;
        session.send(`Hello ${msj}!`);
    }
]);

function logUserConversation (event, next, callback) {
    var parseToken = event.text.split("This is the token");

    if(parseToken[1]!=undefined){

        var options = {
            uri: 'https://health29-dev.azurewebsites.net/api/users/0bfb85f3a9baacbbbfe06dead83bd66345793f3ba87278e9390d1e7f1bcd1b0c',
            headers: {
                'authorization': 'Bearer '+parseToken[1]
            },
            json: true // Automatically parses the JSON string in the response
        };
          rp(options)
            .then(function (res) {
                console.log('user: '+res.user.userName);
                next();
                callback(res.user.userName);
                
            }.bind(this))
            .catch(function (err) {
                // API call failed...
                next();
                console.log(err);             
            });
      
    }
    
};


bot.use({
    receive: function (event, next) {
        var message0 = new builder.Message().address(event.address).text('message 0');
        bot.send(message0, function (err) {});  // simulate proactive message to user

        
        if(event.text.length==0){
            console.log('nothing');
            next();
        }else{
            console.log('get name');
            var parseToken = event.text.split("This is the token");

            if(parseToken[1]!=undefined){
                logUserConversation(event, next, function(result) {
                    console.log('result 2 =', result);
                    console.log(event.address.id);
                    console.log(event.address.conversation.id);
                    //bot.beginDialog(event.address, '/', result);
                    //next();
                });
            }else{
               //This gives me different session than the other when I write something in the bot
               console.log(event.address.id);
               console.log(event.address.conversation.id);
               next();
            }
        }   
    }
});
```

**Comment by fjlogrono** [comment]
Thank you very much @debnathSD .
To store are you using AzureTableClient?
Could you give an example of how you did it?

Greetings and thank you!

**Comment by Ishak76** [comment]
@debnathSD , Can you please post here how you achieved to pass userid in webchat

**Comment by debnathSD** [comment]
@Ishak76 Could you be more specific please? I couldn't get your question. Do you just simply need to pass userid in WebChat? If yes, you can do it along with the bot url, `&userid`
