### ISSUE TITLE
session.send sends only first attempt.

### ISSUE THREAD

**Issue by vzayko** [Microsoft/BotBuilder#139]
Hello!
NodeJs 5.x, botbuilder 0.9.1. I try to send two messages in separate calls, but only the first one is sent. Here is the code:
```
bot.add('/', function(session) {
  session.send('Message 1');
  session.send('Message 2');
});
```
Emulator receives "Message 1" only.

**Comment by Stevenic** [comment]
I'm going to work on improving this but you currently need to add the following lines to your bot:

```
// Check for emulator usage
if (process.env.EMULATOR_PORT) {
    bot.configure({
        endpoint: 'http://localhost:' + process.env.EMULATOR_PORT
    });
}
```
Then you need to specify the emulator port `set EMULATOR_PORT=9000`

**Comment by srisaiswaroop** [comment]
This works with the emulator. 

Just to be clear, port has to be 9000 for everyone. Its not the port on which your server is listening.

**Comment by Stevenic** [comment]
Right.
