### ISSUE TITLE
call back when user comes to my bot's chat?

### ISSUE THREAD

**Issue by palashjhabak** [Microsoft/BotBuilder#1390]
is it possible to get a callback when user just opens my bot's chat window in skype bot ? 

Use Case: As I want to serve user in as few steps I can, if I know a user has come to my chat window I can immediately start talking to him rather than user initiating the conversation.

**Comment by jameslew** [comment]
This is not an event currently exposed by Skype or the Bot Framework.  We can add it to the suggestion backlog however.  Thanks.
