### ISSUE TITLE
location sharing in skype bot?

### ISSUE THREAD

**Issue by palashjhabak** [Microsoft/BotBuilder#1391]
I wonder why is it not possible ? Is it due to some kind of a privacy concern ? I mean I think it is absolutely necessary for a bot to get user's location to serve him in a much much better way. 

Thanks,
Palash

**Comment by jameslew** [comment]
This is a popular request, but is not currently in the Skype channel.  I know this is on their feature request list for the future however.

**Comment by nickcordrey** [comment]
This is definitely something we want to support. Please could you expand on the use case you have in mind as that helps to identify the best solution.

**Comment by palashjhabak** [comment]
sure. as me move from installing multiple apps to conversational bots, having user's location by their consent is a key thing for bots to function properly. I want my bot to order food, cab, medical help etc. its quick if bot already has my location. 

It can be added as a permission in the Get Started page. Just like apps. If user agrees, bots have their location. Otherwise not.

**Comment by nickcordrey** [comment]
Thanks that's helpful - for these use cases you need location on request rather than continuous location.

**Comment by ping13** [comment]
I second the need for this feature ("location on request"). Our use case: We have a bot which alerts a user for nearby train delays. The monitoring is actively requested by the user.

**Comment by suprak** [comment]
I just added Cortana in Skype and it prompted me for my permission to use my location.

How do we implement this feature for our own bots?

**Comment by stevengum97** [comment]
If you're talking about accessing user contextual info such as location, addresses, or preferences you can find more information on this under these two links: [Cortana User Profile & Contextual Information Reference](https://docs.microsoft.com/en-us/cortana/reference/contextual-info) & [User Profile & Contextual Information](https://docs.microsoft.com/en-us/cortana/tutorials/bot-skills/bot-entity-channel-data#User-Profile-Information)

In the future (and if the above information hasn't answered your question) please file a [new issue](https://github.com/Microsoft/BotBuilder/issues/new) with your details and question as this issue has been closed.
