### ISSUE TITLE
[C#] Encounter failed POST on telegram

### ISSUE THREAD

**Issue by wswijaya** [Microsoft/BotBuilder#1392]
Hi,
I encounter "POST to <bot name> failed: A task was cancelled" in Telegram often but not in Skype and FB Messenger. I have attached a screenshot for reference. I am using the latest telegram client and running on iOS 10. 

I observe this error only occur when respond has attachment. 

thanks,
wongso

![20161005_104624000_ios](https://cloud.githubusercontent.com/assets/650007/19143966/95a89fde-8bd9-11e6-9e74-a270ba444315.png)

**Comment by eanders-MS** [comment]
@wswijaya Are you using Node or C# BotBuilder?

**Comment by wswijaya** [comment]
@eanders-MS C#

**Comment by eanders-MS** [comment]
Hi @wswijaya We are receiving this exception message from your bot, and logging it on its behalf. I think the next step would be to run your bot in a debugger and try to capture the exception when it is thrown, in order to diagnose this issue further.

**Comment by wswijaya** [comment]
hi @eanders-MS, thank you. I will debug my bot.

**Comment by wswijaya** [comment]
Hi @eanders-MS ,
I did debug and it seems error "Post to AskJamie failed: A task was cancelled" occur before it reach controller. I stay in the breakpoint for awhile and the error pop out on my Telegram.   

![2016-11-02_10-02-03](https://cloud.githubusercontent.com/assets/650007/19914212/7a8fd73e-a0e3-11e6-9890-10fd491074d9.gif)

**Comment by wswijaya** [comment]
Hi @eanders-MS ,
I notice it only occurs when bot is taking longer time to response. Probably timeout. Anyway to adjust the timeout?

**Comment by eanders-MS** [comment]
@wswijaya It turns out we were incorrectly categorizing some exceptions as coming from the bot in our Telegram adapter. A fix for this is scheduled to go out today. Once that fix is live, we will see better error reporting from the adapter and should be able to get more information about what is really failing here.
