### ISSUE TITLE
Facebook typing indicator time really 20s?

### ISSUE THREAD

**Issue by seb0zz** [Microsoft/BotBuilder#1397]
Hi,

I was just playing with the typing indicator on facebook. The indicator itself works fine but it's does not "type" for 20s. Instead it's just visible for approximately <= 1 second. So what I did for now to achieve a longer typing duration I just called it like 10 times in a row without a delay inbetween. When I do that the indicator will display for approximately 10 seconds. 

Is the documentation just out of date or am I doing something wrong?

Cheers!

**Comment by jameslew** [comment]
What I've found in most cases where I've debugged this is the bot (including two of mine <sigh>) actually was sending another message after sending the typing indicator, which cleared it.

I have tested on my bot and when the bot is working, it sticks around for the 20s.

**Comment by seb0zz** [comment]
You are right, that was the issue
