### ISSUE TITLE
Required Help

### ISSUE THREAD

**Issue by vignestheo** [Microsoft/BotBuilder#1399]
how to send notification message to few senders, how i can achieve it say example i am having members in two to three location so now i have to send a message only to member who located in only in one location. Please provide your assistance

**Comment by brandonh-msft** [comment]
Bot doesn't inherently know where a user is located, so you'd need to associate a location with a user via the `.UserData` property bag. Once you've done that, checking the Users in a Conversation then sending messages out only to users whose location matches what you're looking for could easily be done via a proactive message which has been covered quite a bit in various issues already filed & closed (#1303, #1247, #1180, #1288)

**Comment by tomlm** [comment]
closing due to age
