### ISSUE TITLE
Long user input doesnt get recognized

### ISSUE THREAD

**Issue by bluekite2000** [Microsoft/BotBuilder#140]
I have 

> context.Call<AskRoom>(new FormDialog<AskRoom>(new AskRoom(), options: FormOptions.PromptInStart),OnRoomQuestionAnswered);

If I enter a long input (for ex I want to book a room) function OnRoomQuestionAnswered doenst get callled. If I enter "I want to" or something short it gets called. Any idea?

**Comment by willportnoy** [comment]
What does AskRoom look like?  If your question requires an answer that is a single piece of text, you might consider using the prompts instead of form.

**Comment by srisaiswaroop** [comment]
I have the same issue with prompts as well. when i give user 3 options and ask him to select one from it, skype doesnt show the text(until i restart my Skype). I have pasted my Sample input in #113 . Even with session.send() it has the same issue with long text. It works fine with webchat interface and emulator for me. I have not tried other channels.

**Comment by chrimc62** [comment]
Check the answer in #113 and if that does not address your issue, please reopen.
