### ISSUE TITLE
session.sendTyping() does not work fine in slack.

### ISSUE THREAD

**Issue by somprabhsharma** [Microsoft/BotBuilder#1400]
In slack it keeps showing user is typing even 2-3 seconds after delivery of the message. While in other channels its works fine and stops showing user is typing as soon as message is delivered.

**Comment by jameslew** [comment]
After delivery of the typing message, or after delivery of the subsequent message?

**Comment by somprabhsharma** [comment]
after delivery of the subsequent message.

**Comment by tomlm** [comment]
this should be working correctly now.

**Comment by craigjensen** [comment]
If this is still a problem you can try setting the "as_user=true" in channel data to force Slack to remove the typing message.
