### ISSUE TITLE
Required help in retrieving facebook username 

### ISSUE THREAD

**Issue by vignestheo** [Microsoft/BotBuilder#1401]
Hello Team 

How to retrieve Facebook name using BOT Framework in node js?

**Comment by jameslew** [comment]
The "user" object on the incoming message has the user's Facebook name in it.

**Comment by vignestheo** [comment]
How to represent the syntax in coding since I am new to this I am not aware
of it.

**Comment by danmarshall** [comment]
@vignestheo does this help? https://developers.facebook.com/docs/messenger-platform/user-profile

**Comment by vignestheo** [comment]
Thanks for your response I have a another query
How to send messages to only certain users of it matches with some
variables as condition e.g. Location is Madurai then I will take their
facebook id's and using that facebook id's whether I can send broadcast
message to only those users.

**Comment by chrimc62** [comment]
@Stevenic or @maxpert can you comment or close appropriately?

**Comment by Stevenic** [comment]
Sorry for the delay... @vignestheo did you figure this out? unfortunately you'll need to track the [address](https://docs.botframework.com/en-us/node/builder/chat-reference/interfaces/_botbuilder_d_.imessage.html#address) object of every user that contacts your bot and then do your own segmentation based on region.  To send a notification you'll then need to do a `bot.send()` to each user in the given region.

**Comment by vignestheo** [comment]
How to do session reset ? and how to clear the session data? and how to do
set time out for the particular session

**Comment by Stevenic** [comment]
This issue is getting a little overloaded. Could you create a new issue and provide more details about what you're trying to do?

**Comment by chitrang89** [comment]
I just went through this as part of BotBuilder v3.8, and I decided to write about the steps here if anyone is interested:) 

http://chitrang.me/2017/05/24/facebook-user-name-bot-framework-botbuilder/
