### ISSUE TITLE
[Nodejs] group chat

### ISSUE THREAD

**Issue by wormen** [Microsoft/BotBuilder#1408]
tell me how to get messages  in skype from all users in group?
regardless, they are turning to the bot or not

**Comment by divinemanwah** [comment]
I think the bot can only get messages *IF* it is directly addressed to it. It cannot listen to the group's conversation in any way as far as I'm concerned.

**Comment by wormen** [comment]
@divinemanwah 
about the treatment directly to the bot, I know
but the question was not about that

**Comment by tomlm** [comment]
you can't, by policy of the skype team
