### ISSUE TITLE
Sending a message to an ongoing conversation outside of Post

### ISSUE THREAD

**Issue by jakobpn** [Microsoft/BotBuilder#141]
What is the minimal amount of information that I need to populate a new Message object with in order to send a message to an ongoing conversation.

My code is outside of the Post([FromBody]Message message) method and looks similar to this:

var connector = new ConnectorClient();

Message message = new Message
{
  Text = "Message"
  // What else need to be provided to send the message?
};

await connector.Messages.SendMessageAsync(message);

**Comment by willportnoy** [comment]
I'm not exactly sure - Message.CreateReplyMessage seems to fill in To, ReplyToMessageId, Participants, and TotalParticipants, and then these fields if available: From, ConversationId, ChannelConversationId, ChannelMessageId.

**Comment by jakobpn** [comment]
Thx @willportnoy. I need to transfer all of the required parameters in the URL to a login page so I like to keep this as minimal as possible. It would be cool if ReplyToMessageId was enough information to send the reply.

**Comment by wiltodelta** [comment]
@jakobpn Experimentally found necessary parameters for Slack, Skype, Telegram:

```
Message message = new Message
{
  ChannelConversationId = channelConversationId,
  From = new ChannelAccount
  {
    ChannelId = channelId,
    Address = botAddress,
    IsBot = true
  },
  To = new ChannelAccount
  {
    ChannelId = channelId,
    Address = userAddress
  },
  Text = text
};
```

ChannelConversationId only necessary Slack, otherwise the message will be added @userAddress.

**Comment by tomlm** [comment]
The minimum information is to have the From,To fields filled out and  some sort of payload:
* Text, Attachments, ChannelData

If you give no ConversationId/ChannelConversationId then it will be considered a new conversation.  If you provide a previous ConversationId/ChannelConversationId then it will be routed as a reply to the existing conversation.
