### ISSUE TITLE
Channel Specific Testing

### ISSUE THREAD

**Issue by hughcameron** [Microsoft/BotBuilder#1411]
Hi there,

Hoping to get a recommendation on the best method of testing bot behaviour within channels. The emulator appears to focus on functionality and I'm keen to test channel specific things like dialogue formatting that can’t be seen in the command line. 

As we’re using continuous deployment to a web app from BitBucket is it possible to set up a test bot based off a testing branch?

Any tips would be much appreciated!

**Comment by brandonh-msft** [comment]
Couple of thoughts here:
1. testing a specific channel is best done (today) by simply enabling the bot on that channel, performing the integration steps, and then using the bot on that channel
2. you can "customize" a bot's responses to a channel by inspecting the `IActivity.ChannelId` and acting accordingly
3. To use CI, I would set up different bots for different branches; remember, bots aren't deployed to the world until you say to do so - until that point you can test them at your heart's content. You could also simply deploy each branch to a `-dev.azurewebsites.net` instance and have one bot set up there, then deploy prod bot to an endpoint without `-dev`.

Those are just a few ideas I could come up with :) hopefully you find one/more useful.

**Comment by hughcameron** [comment]
Hi @brandonh-msft - thanks so much for your assistance! We managed to set up a testing environment using option #3.
