### ISSUE TITLE
FormFlow: change generated by navigation template messages

### ISSUE THREAD

**Issue by mitkodi** [Microsoft/BotBuilder#1412]
If we reject a confirmation the list of options for each dependent field would use field name as message for each navigation option. Is it possible to change that (and localize it), because using field names as responses could sometime be a little strange to the user.

**Comment by chrimc62** [comment]
Yes, you can change the NavigationFormat template which controls what is displayed.

**Comment by mitkodi** [comment]
I didn't ask for the displayed text, but for the generated as a reply from the user text (after clicking a button).
