### ISSUE TITLE
[node.js] Keyboard and IKeyboard are not exposed

### ISSUE THREAD

**Issue by palmerabollo** [Microsoft/BotBuilder#1416]
The SDK doesn't expose the `Keyboard` class and `IKeyboard` interface to the developers.

They should be publicly exposed so you can do things like this:

``` js
    var buttons: botbuilder.CardAction[] = [];
    buttons.push(botbuilder.CardAction.imBack(session, 'Option 1', 'Option 1'));
    buttons.push(botbuilder.CardAction.imBack(session, 'Option 2', 'Option 2'));

    var msg = new botbuilder.Message();
    msg.text('Hi, these are some options')
           .attachments([new Keyboard(session).buttons(buttons)]);
```

Edit: the same happens to `Channel` that contains some handy utility functions.

On a side note, I don't think that [passing the `Session` to the `Keyboard` constructor](https://github.com/Microsoft/BotBuilder/blob/5cf71c742f27d89e9dbc4076f850122bd6edac11/Node/core/src/cards/Keyboard.ts#L32) is a good idea. It doesn't look like a good design. In fact, the `Session` is not used.

**Comment by Stevenic** [comment]
So the Keyboard not being exposed was an oversight and should be fixed now.

Channel isn't exposed currently but we probably will expose and improved version of Channel at some point.

I'm not crazy about passing in the `session` object to the constructor but its generally needed for localization purposes. Yes its not actually used by the Keyboard currently but it may be at some point so I just passed it in for constancy purposes. If you notice the Keyboard is the base class of HeroCard & ThumbnailCard which do use it.

I'd like to eventually remove the need to pass the session into those classes at all but it's going to take a fair amount of work.

**Comment by chrimc62** [comment]
@Stevenic or @maxpert please comment or close as appropriate.

**Comment by Stevenic** [comment]
This should be fixed in the next release if you're using TypeScript (it was already fixed for JavaScript users.)
