### ISSUE TITLE
FormFlow: change generated by navigation template messages #2

### ISSUE THREAD

**Issue by mitkodi** [Microsoft/BotBuilder#1418]
Maybe I wasn't clear enough in #1412
I didn't ask for the displayed text, but for the **generated as a reply from the user** text (after clicking a button to change corresponding field).

Example:
**Bot**
>What do you want to change?
>\<Field 1 Description>
>\<Field 2 Description>

*after clicking the first button for changing field1*:
**You**
>Field1Name

**Comment by chrimc62** [comment]
[Describe("This is the foo field", Message="foo")]
[Terms("foo")]
public string Foo;
Then foo will be typed when you press the "This is the foo field".
