### ISSUE TITLE
[Skype] waterfall flow inside builder.IntentDialog().matches()

### ISSUE THREAD

**Issue by divinemanwah** [Microsoft/BotBuilder#1419]
Consider the following example:

``` javascript
bot.dialog('/', new builder.IntentDialog()
    .matches(/keyword (.*)/i, [
        function (session, matches, next) {

            builder.Prompts.choice(session, 'A question', ['a', 'b', 'c'], {
                retryPrompt: [
                        'A message',
                        'Another message'
                    ],
                maxRetries: 2
            });
        },
        function (session, results) {

            // Awesome code here
        }
    ])
);
```

Produces:

```
A question
1. a
2. b
3. c
```

When inside a 1-on-1 conversation with the bot, using either `1`, `2`, `3` or `a`, `b`, `c` works just fine. But when used inside a group conversation, using only the numeric value of the choices yields incorrect results. The exact text must be typed in or copy-pasted for it to work correctly, which I think is a little bit of a hassle to the users.

BotBuilder version 3.2.3
Platform: NodeJS

**Comment by chrimc62** [comment]
@Stevenic or @maxpert can you comment?

**Comment by Stevenic** [comment]
Sorry I missed this... I'm not sure why this would be an issue for group conversations. Are you sure? What channel are you trying this on?

**Comment by divinemanwah** [comment]
> Are you sure? What channel are you trying this on?
Yes I'm sure. At the time that I wrote this, it wasn't really working as expected (don't know now after maybe a couple of updates). It was a Skype bot that I was experimenting.

**Comment by maxpert** [comment]
Closing issue. Please reopen if you are still facing the issue.
