### ISSUE TITLE
[Question] Alternatives to enums in C# samples?

### ISSUE THREAD

**Issue by pedronahum** [Microsoft/BotBuilder#142]
Hi,

First and foremost, great work with the bot framework! 

Maybe this is a very basic question, apologies in advance. In the C# examples, lets say the PizzaBot example, enums are used along with attributes to show the Size Options, Topping Options, etc. 

How could these attributes (ie, terms and describe) be passed if the data, such as "herb and cheese blend" was provided by an inventory [eg, web api]? 

Thanks in advance,

Pedro

**Comment by chrimc62** [comment]
There is not an easy way to do this now, but our next release which should be soon adds a way to dynamically define fields, messages and confirms.  To do this in the current framework you need to define your own implementation of IField<T>.  In the new release you can use the fluent methods off of Field<T> or FieldReflector<T> to do so.
