### ISSUE TITLE
FormFlow confirmation options not overwritten

### ISSUE THREAD

**Issue by galazzo** [Microsoft/BotBuilder#1420]
Hi,

I'm facing with an issue ovewriting confirmation options yes/no.
While it works for other options the yes/no string array is not affected then is a big issue when working with languages different from english, like italian. This make users unable to confirm their chooses being locked into FormFlow.

**Comment by chrimc62** [comment]
Can you be more specific?  Our tests include lots of examples of confirmations in other languages and they all pass.  Are you talking about the regular choice prompt rather than form flow?

**Comment by galazzo** [comment]
Hello,

nothing special, here my code:

`var form = new FormBuilder<CertificatoNascitaOrder>()
		.Message("Ho necessità di alcuni dati")
		.Field(nameof(Name))
		.Field(nameof(Surname))
		.Field(nameof(Birthdate))                        
		.AddRemainingFields()
		.Confirm("Conferma quindi la richiesta per un certificato di nascita a nome di {Name} {Surname}\nnato a {Birthplace} {?il {Birthdate}}\n con email {Email}?")
		.Message("Grazie, abbiamo completato il processo.")
		.Message("La sua richiesta è stata inoltrata all'ufficio competente. Riceverà risposta non appena possibile alla email da lei indicata.")
		;
		
form.Configuration.Yes = new string[] { "si", "ok", "yes", "certo", "va bene", "procediamo" };

return form.Build();`

If I run a debugging code after initialization of Yes sentences I get the correct result:
`foreach ( var str in form.Configuration.Yes)
            {
                System.Diagnostics.Debug.WriteLine("yes:" + str);
            }`

But once compiled an running it is not affected, you get original settings.

**Comment by chrimc62** [comment]
I am unable to reproduce this.  I replaced yes and it ended up matching as expected.  What version of the Bot Builder are you running?  Is it the latest?

**Comment by galazzo** [comment]
I use lastest version: 3.3.0 from nuget

**Comment by chrimc62** [comment]
I am unable to repro this.  Can you share your GitHub?

**Comment by khaueviana** [comment]
@galazzo this error ocurred because you have to set this configuration before add steps

Like this:

`          var builder = new FormBuilder<DeveloperDialogOrder>();

            builder.Configuration.DefaultPrompt.ChoiceStyle = ChoiceStyleOptions.Auto;

            builder.Configuration.Yes = new string[] { "yes", "sim" };
            builder.Configuration.No = new string[] { "no", "não" };`

**Comment by gianvi** [comment]
Hi, can you suggest me which configuration need to be set to change the "What do you want to change?" after saying no in confirmation at the end of the formflow?
Thx
