### ISSUE TITLE
don't want to use bot connector in the middle of conversation between user and bot 

### ISSUE THREAD

**Issue by venkey1000** [Microsoft/BotBuilder#1421]
As a part of reducing latency I don't want to use bot connector. What are the consequences if we take bot connector out of the scenario and want to use just bot builder SDK. I want to use it for Facebook channel only, Facebook any way posts the messages that are coming to our page to any endpoint we have mentioned in Facebook app. Is there any problems that come up if we don't use bot connector.

**Comment by danmarshall** [comment]
which sdk, C# or Node ?

**Comment by venkey1000** [comment]
@danmarshall, I am building with node js.

**Comment by danmarshall** [comment]
You can write your own connector, take a look at [ConsoleConnector](https://github.com/Microsoft/BotBuilder/blob/master/Node/core/src/bots/ConsoleConnector.ts) for an example of a connector implementation. You would just need to map Facebook's schema onto the BF schema.
