### ISSUE TITLE
Send Game in Telegram

### ISSUE THREAD

**Issue by dimoibiehg** [Microsoft/BotBuilder#1426]
Hi,
I want to use "**sendGame**" function in Bot Framework for Telegram.
But, apparently it is not supported in the current version of the Bot Framework (version 3.0).
Please consider about that.

Thanks in advance.

**Comment by hmkavousi** [comment]
We have the same priority as well, any progress is welcome.

**Comment by eanders-MS** [comment]
We're adding support for sending of the "sendGame" message through the channelData field of the message activity (called sourceEvent in the Node BotBuilder). These changes will go live sometime this week. I will report here when this is available.

**Comment by eanders-MS** [comment]
The update is live. You should now be able to send Telegram game messages through the activity.channelData field. ChannelData is for sending channel-native messages. For an example of sending a channelData message to Telegram, see issue https://github.com/Microsoft/BotBuilder/issues/1299.
