### ISSUE TITLE
401 Unauthorized response from GoDaddy hosted Bot

### ISSUE THREAD

**Issue by wilsoncgp** [Microsoft/BotBuilder#1428]
Hi, no idea where else to put this but I need help trying to decipher a bug.

So I'm completely stuck trying to figure out what the problem is with my bot that I'm publishing to my GoDaddy hosted site: https://liamwilson.co.uk/

I've tested the bot locally with the Channel Emulator with my App ID and App Password and it works fine, no problems getting responses from it. I push it onto GoDaddy and tested using both ngrok & the Channel Emulator and 'dev.botframework.com' with the Test connection button and both are just giving me 401 Unauthorized.

I don't want to have to go through Azure just to use my bot. I have this server space available to use so would like to be able to publish it and use it from there.

Is there any way I can actually debug this kind of problem to see where the authentication is failing? Seems strange that it works locally but fails when its on the server. I haven't seen any tutorials or blog posts around publishing bots which don't involve Azure either.

**Comment by kenrick95** [comment]
Can you check your program log on your server? Probably there's some error(s) that reject your request.

**Comment by wilsoncgp** [comment]
I've spent a long time trying to fix this, couldn't set log4net up properly on the server either.

Figures I managed to fix the breaking issues for both by forcing the Trust level to be Full in the site's Web.config. It seems to be Medium by default on the server.

**Comment by mwaqas14** [comment]
hey wilsoncgp you are great. I've been trying to fix the issue one of my bot that is hosted on godaddy site for last more than 5 days. Today I had a long distance call with their tech support of around 45 minutes but no solution. 
I just changed the setting as you mentioned all of sudden all is working as it should be. 

Thanks wilsoncgp
