### ISSUE TITLE
Facebook messenger button: Can not show long message on buttons of  HeroCard

### ISSUE THREAD

**Issue by astrung** [Microsoft/BotBuilder#1431]
From facebook messenger doc : Our button text is 320 characters.
But when i send to facebook messenger text button in Hero card, it is rename as " .... " with long message.
But it still shows full button text on Channel Emulator .
How to fix it ??

**Comment by danmarshall** [comment]
The emulator is just an approximation of the channel, it is not exact.

**Comment by afficionaddo** [comment]
Hi,

regarding "From facebook messenger doc : Our button text is 320
characters." -- It's 20 characters if a button as per FB docs.

To make sure all of the button text is shown, use three words short if
possible.
Keep the starting word short and no apostropher as it induces '...' in the
button text. [purely FB handling and nothing in MSFT Bot Frameowrk' side].

**Comment by danmarshall** [comment]
Thanks, can you add links to where you are seeing these in the documentation? (both FB and BF)

**Comment by Badolfo** [comment]
Danmarshall, you can check here:

https://developers.facebook.com/docs/messenger-platform/send-api-reference/generic-template

**Comment by astrung** [comment]
Thanks. so it depends on our channel (facebook).

**Comment by chrimc62** [comment]
Yes it depends on your channel.  We are working on documenting all the channel information in one place and should be releasing it soon.
