### ISSUE TITLE
"Typing" reply never disappear on Facebook Messenger Android app

### ISSUE THREAD

**Issue by valse** [Microsoft/BotBuilder#1434]
Hi,
   in my C# bot I always reply to my users with a "Typing" activity type before forward the message to my main dialog class... so the user knows that my bot is responding.

`// typing
var connector = new ConnectorClient(new Uri(activity.ServiceUrl));
var isTypingReply = activity.CreateReply();
isTypingReply.Type = ActivityTypes.Typing;
await connector.Conversations.ReplyToActivityAsync(isTypingReply);

await Conversation.SendAsync(activity, MakeRoot);`

However I saw that in the Facebook Messenger (Android) app this activity never disappear, neither after 20 seconds as written in the [Facebook documentation](https://developers.facebook.com/docs/messenger-platform/send-api-reference/sender-actions).

In the Facebook Messenger for Web (and Skype too) it works like expected... so I' don't know if this is an app problem or a Connector problem that maybe must send a "typing_off" command after the next bot answer.

Thanks
Marco

**Comment by danmarshall** [comment]
Thanks @valse for reporting the issue. @reyesrico can we create a test for this?

**Comment by reyesrico** [comment]
I could reproduce the problem and I can confirm that the typing activity never disappear only in Facebook Messenger Android app. This is a bug directly with the Facebook channel not with the Bot Framework tool. I just have reported a bug inside Facebook platform: https://developers.facebook.com/bugs/1179569982103956/ 

If you still have more comments, please reopen the issue. Thank you.

**Comment by seb0zz** [comment]
If anyone is interested in a workaround. In NodeJS I have stopTyping method that looks like:

```javascript
const stopTyping = (session, callback) => {
  const stopTypingOptions = {
    uri: `https://graph.facebook.com/v2.6/me/messages?access_token=${process.env.FACEBOOK_PAGE_ACCESS_TOKEN}`,
    method: 'POST',
    json: {
      recipient: {
        id: session.userData.facebookUser.id
      },
      sender_action: 'typing_off'
    }
  };

  request(stopTypingOptions, (error, response) => {
    if (error || response.statusCode < 200 || response.statusCode >= 300) {
      logger.error({
        message: error
      });

    }

    callback();
  });
};
```

**Comment by seb0zz** [comment]
One more hint: On android there is another issue even if you use the workaround I mentioned above. The bug occurs when you try to do the following combination:

1. Send typing indicator (see my workarond above)
2. Stop typing indicator
3. Send gif as an attachment
4. Send typing indicator
5. Stop typing indicator
6. Send `builder.Prompts.choice`

This scenario works perfectly on iOS but will not work on Android. On Android the typing indicator in step 4 will not disappear. So in this case what we did was: 

1. Send typing indicator
2. Stop typing indicator
3. Send gif as an attachment
4. Send `builder.Prompts.choice`

The interesting part is that it also works when you don't send a gif attachment but only a text message. 

¯\_(ツ)_/¯
