### ISSUE TITLE
Require help in integrating with facebook page

### ISSUE THREAD

**Issue by vignestheo** [Microsoft/BotBuilder#1436]
Hello Guys

I am developing bot with MS Bot framework in node js after using ngork i am able to send message to FB messenger and its working but when session is closed and when i tired to send message again to initate the session i am getting error in ngork as 404 not found and bot also not responding to messenger with any message. 

Please correct me what i am wrong?

**Comment by danmarshall** [comment]
which session are you referring to?

**Comment by vignestheo** [comment]
Hello Dan 

Let consider scenario that i have to maintain two different user session with bot 

first i tried with facebook messenger but with only one user account i can send and receive message from bot and for another user i didnt get any response.

second,  how to test the same scneario in Stimulator ?

My requirement : Let us consider one user requesting to contact members who located in one location, once user provide the location then i have to send a message to the use facebook users who was located in that location.

Please provide your assistance

**Comment by danmarshall** [comment]
From the [Facebook documentation](https://developers.facebook.com/docs/messenger-platform/product-overview/launch): 

> When your app is in Development Mode, your bot will work for admins, developers and testers of the app. After your app is approved and public, it will work for the general public.

**Comment by vignestheo** [comment]
oh, thanks for response, could you please provide your assistance to achieve my requirement.

**Comment by danmarshall** [comment]
As for the Emulator, you can change the userid to simulate a group conversation.

**Comment by danmarshall** [comment]
For your requirement, you will need to back your bot application with your own storage. Then once a user provides a location to your bot, you would query against your own storage.

**Comment by vignestheo** [comment]
myself fine with storage i will make http request  to store and retrieve location but here my question how i can send the message to only selected users?

**Comment by danmarshall** [comment]
Are you using Node.js or C# ?

**Comment by danmarshall** [comment]
Please find the "Create New Conversation" examples from https://github.com/Microsoft/BotBuilder-Samples

**Comment by vignestheo** [comment]
I am using node Js

**Comment by vignestheo** [comment]
Thanks for your response, even i added one of m friend facebook id as admin in Facebook page but still my bot is not reponding to his facebook id , Bot is responding to only my facebook id.

**Comment by tomlm** [comment]
They have to accept the request to make them an admin
