### ISSUE TITLE
Separated assembly with base test objects/mocks

### ISSUE THREAD

**Issue by GhostAtom** [Microsoft/BotBuilder#1438]
Hi,

Did you planned to split the tests and tests base objects? (ie DialogTestBase)
It could be interesting for reuse purpose to do a separated dll.

Thanks
Thomas

**Comment by willportnoy** [comment]
We did not have immediate plans to do so - the test assembly is reference-able as a project though, so your scenario should be supported, modulo layering concerns.  Is that what you mean?
