### ISSUE TITLE
Would it be possible to add support for wit.ai? #question

### ISSUE THREAD

**Issue by kmariano** [Microsoft/BotBuilder#144]
Would it be possible to add support for wit.ai by adding a new dialog that implements the IntentDialog interface? The implementation could be very similar to the LuisDialog and would allow users to build  bots that could use both LUIS and Wit.ai.

**Comment by Stevenic** [comment]
Yes. I just haven't had time to write it but totally possible. I'm actually planning to deprecate the IntentDialog class and replace it with just the LuisDialog class. There are a few reasons for this so I'd wait and look at that class for inspiration on building a Wit.ai based dialog.

**Comment by Stevenic** [comment]
Moved to UserVoice for tracking and voting.

https://feedback.botframework.com/forums/354222-bot-builder-sdk/suggestions/13494474--nocejs-add-a-wit-ai-dialog-class-similar-to-luis

**Comment by venkat345** [comment]
Is it Possible to integrate wit.ai with Mircrosoft bot framework? Is there any documents for this?

**Comment by adebisi-fa** [comment]
@venkat345 There is a prototype of LUIS implementation for [Wit.Ai (C#) here](https://github.com/adebisi-fa/Bot.Builder.WitAi).  It implements the **ILuisService** for [Wit.Ai](http://wit.ai).  Sample will be added to the repo, asap.  It's available on [NuGet here](https://www.nuget.org/packages/Adfa.Bot.Builder.WitAi/0.1.0).  

Hope it helps.

**Comment by deksden** [comment]
Here is nice NPM module for Bot Framework for Node.js : https://github.com/sebsylvester/botbuilder-wit

**Comment by joeseos** [comment]
@Stevenic Anything new on this one? Or better, Swedish, Norwegian & Danish support in Luis :)
