### ISSUE TITLE
Session reset not working on upgrade experience node.js

### ISSUE THREAD

**Issue by slidenerd** [Microsoft/BotBuilder#1441]
First of all, thank you for your fantastic work, I am trying to persist my session object containing useful information in a mongodb database. I changed the schema of the database slightly and figured out that the session needs to be reset. On further inspection of the Middleware class, I notice this

```
if (major > curMajor) {
                        // Run user through full first run experience
                        session.beginDialog(consts.DialogId.FirstRun, <IFirstRunDialogArgs>{
                            version: options.version,
                            dialogId: options.dialogId,
                            dialogArgs: options.dialogArgs
                        });
                    } else if (options.version > cur && options.upgradeDialogId) {
                        // Run user through upgrade experience
                        session.beginDialog(consts.DialogId.FirstRun, <IFirstRunDialogArgs>{
                            version: options.version,
                            dialogId: options.upgradeDialogId,
                            dialogArgs: options.upgradeDialogArgs
                        });
                    } else {
                        next();
                    }
```

Does that mean session is reset only for full first run experience and not for upgrade experience? 
**A second doubt**
What would be the best way in node.js to achieve the following? After the last conversation with a particular user, say if 10 mins have elapsed, I would like to save all the variables of the user from session to mongodb, I already store the address object of each user in the database, so when there are a bunch of users interacting with the bot framework, should I keep a global variable with an array of addresses and simply pop addresses to persist. Is there any data structure provided or callback mechanism provided by the bot framework after N minutes of inactivity to save user data on persistent storage. Thank you for your answers in advance

**Comment by Stevenic** [comment]
So for the first part you're asking a question about the `dialogVersion()` middleware but showing me code for the `firstRun()` middleware. Which are you using?

**Comment by Stevenic** [comment]
For your second question... Doing any sort of "Elapsed Timer" stuff in a bot is tricky... When I say it's tricky I mean its tricky to do in any sort of way that will scale and be reliable. If your bot is limited to running on a single node you can theoretically just keep an in-memory table and call `setTimeout()` to periodically flush things.  If your bot runs across multiple nodes (which I can argue you should always have at least 2 nodes for reliability purposes) this this is tricky...

Can I ask for a little more details about what you're trying to save?

**Comment by slidenerd** [comment]
**Part 1**
I am trying to use the firstRun method in my code. I think that the firstRun method is not called when the version changes from 2.1 to 2.2 , however it jump from 2 to 3, it gets called because of the floor statement used in the code above. What I would like to do is reset the session when the code changes from 2.1 to 2.2, what would be the recommended way to go about this

**Part 2**
My bot asks a lot of questions while in conversation like what is your favorite movie etc etc. In the first run I get the details of the user and save it to the database. 

To save the details gathered from the user, I have 2 options. 

1. Get all the variables inside session.userData and save them to the database or persist them to the database on each conversation. Simple words = everytime a person says something to the bot, make a query to the db and store new information gathered

2 Wait till the user has been inactive for say 10 minutes or so and then save all the information gathered during the conversation to the database in a single query

3 I thought of this one which is a highly modified version of the 1 where on each conversation, I compare the existing session.userData.user object with all information with the new session.userData.user object and persist only if both are different.

What would be the right way to ensure that any information gathered as the conversation progresses is saved aptly

thank you for your answers in advance

**Comment by Stevenic** [comment]
__Part 1__
You can just pass the same dialogId for the both dialogs then.That will catch both minor an major updates then.

__Part 2__
So to avoid data loss you should persist the answers in between each turn of the conversation.  I just posted a new [basics-loops](https://github.com/Microsoft/BotBuilder/tree/master/Node/examples/basics-loops) example which shows how to ask a dynamic set of questiosn for the user which might provide some insperation for you.

On the storage side I have a similar problem to you... I need to potentially write back any changes you've made to `userData` or `dialogData` after each turn of the conversation. Problem is I don't know a) if you've modified anything, and b) if you have are you done? 

To solve a) what I do is cache a hash of the userData & dialogData object before I give you them. When I'm ready to write out potential changes, I re-hash the objects and then compare the hashes to see if anythings changed. I only write out the data if it's changed.

Solving b) is a little trickier. While I can't now 100% that you're done touching things I do have some clues. I wait until you cal send() or otehr functions on the session and then I start a timer. I'll wait for 250ms after I see you stop touching things before I commit any changes you've made. I have an additional optimization that if you call in of the Prompts or you call endConversation() then I know you're done and will flush the changes immediately. In general this strategy works well.

I honestly doubt you need anything that sophisticated but again... Maybe it helps.
