### ISSUE TITLE
Urgent: Bot not responding

### ISSUE THREAD

**Issue by afficionaddo** [Microsoft/BotBuilder#1444]
Hi my bot is not responding. It is setup with FB messenger.

Can the support team help in anyway.
I have checked my DB, server, debugged locally with emulator....it seems to be working fine.

Please help urgent! Can you check the logs.
What details should I provide here?

**Comment by afficionaddo** [comment]
I checked Azure logs as well. It seems to be something in Bot.Connector service. See below:

3. Checked Azure logs. See below the trace:

`Buffer="{ "message": "An error has occurred.", "exceptionMessage": "Precondition Failed", "exceptionType": "Microsoft.Rest.HttpOperationException", "stackTrace": " at Microsoft.Bot.Connector.ErrorHandling.HandleError[ObjectT](HttpOperationResponse`1 result)\r\n at Microsoft.Bot.Connector.BotStateExtensions.<SetUserDataAsync>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n at NaMoBot.MessagesController.<ReplyToUserMessage>d__7.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at NaMoBot.MessagesController.<Post>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()" }"`

**Comment by afficionaddo** [comment]
I tried putting Try, Catch around the BotState code at each and every place in my code. But not able to log any exception.

Please help/suggest what should I do?

**Comment by AmineI** [comment]
Is it responding with a dummy fb account ? Watch out, sometimes facebook flag your messages as "spam messages" and the bot can't see them anymore

**Comment by afficionaddo** [comment]
No, it is not responding to any FB account.

**Comment by danmarshall** [comment]
Take a look at some of the other issues with the "Precondition Failed" error: https://github.com/Microsoft/BotBuilder/issues?q=Precondition%20Failed

**Comment by afficionaddo** [comment]
Thanks for the reply @danmarshall . But i have commented my whole code and kept just a simple 'text reply'. Even then I am not getting any reply.

Is there any way you can check any logs if I provide you the AppId. May be you can point any error I am not able to see.

**Comment by danmarshall** [comment]
Can you provide your AppID and if possible, a code sample.

**Comment by afficionaddo** [comment]
Thanks for the prompt reply @danmarshall .

The appID: 15825bdd-6da5-4a9c-8f2f-7ed445a53827
The bot is with FB messenger.

The only code running right now is a simple text reply. See below:

public async Task<HttpResponseMessage> Post([FromBody]Activity activity) { 
ConnectorClient connector = new ConnectorClient(new Uri(activity.ServiceUrl)); 
if (activity.Type == ActivityTypes.Message) 
{ // return our reply to the user await connector.Conversations.ReplyToActivityAsync(activity.CreateReply("Sorry, I am down right now!")); 
}
 else { HandleSystemMessage(activity); } 
var response = Request.CreateResponse(HttpStatusCode.OK); 
return response; 
}

As per my debug, The message is received from FB but reply does not reach back.

Please help as I not able to identify the issue and am in deep trouble.

regards.

**Comment by danmarshall** [comment]
Sorry I meant I need your Bot id from your Bot Framework registration.

**Comment by afficionaddo** [comment]
The BotHandle is 'Namo'.

**Comment by afficionaddo** [comment]
Hi @danmarshall ....any update?

I remoted debugged the above code through Azure.

The message is received from facebook but the reply back does not reach facebook.
No exception in the above code and the flow. I have checked it with try, catch.

Please help!

**Comment by afficionaddo** [comment]
Hi @msft-shahins , @danmarshall .

I know you are busy people but did you get any chance to identify the issue? As my bot is still down and I am stuck
Please help!

**Comment by msft-shahins** [comment]
@afficionaddo I looked at the logs for your bot and see this in our logs: 
>  Facebook graph API call failed with: BadRequest {"error":{"message":"Error validating access token: The session has been invalidated because the user has changed the password.","type":"OAuthException","code":190,"error_subcode":460,"fbtrace_id":"BrS8P06B9CO"}

have you changed your password recently? I guess facebook will invalidate the page access token after a password change and you need to update your page access token in botframework. If you debug your bot, you should see that you calls to botframework are failing with that error from facebook.

**Comment by afficionaddo** [comment]
Hi @msft-shahins , you are my hero of the week.

Thanks a lot buddy!!!!!

**Comment by kienct89** [comment]
I also have this problem recently
I've already updated the page token, but it still doesn't work.

@msft-shahins could you help please?

**Comment by clockwisemusic** [comment]
Thank you @msft-shahins - you are now my hero of the week.
