### ISSUE TITLE
Cannot override PostUnhandledExceptionToUserTask 

### ISSUE THREAD

**Issue by rposbo** [Microsoft/BotBuilder#1445]
Sorry to resurrect this question since it's been mentioned so many times previously, however I _still_ cannot get this working even after following the advice on other issues.

I want to stop showing "Sorry, my bot code is having an issue"; in fact, I want to override that content.

I have created an autofac module where I replace `PostUnhandledExceptionToUserTask` with `PostUnhandledExceptionToUserOverrideTask`:

``` csharp
public class DefaultExceptionMessageOverrideModule : Module
{
    protected override void Load(ContainerBuilder builder)
    {
        builder.Register(c =>
        {
            var cc = c.Resolve<IComponentContext>();

            Func<IPostToBot> makeInner = () =>
            {
                var task = cc.Resolve<DialogTask>();
                IDialogStack stack = task;
                IPostToBot post = task;
                post = new ReactiveDialogTask(post, stack, cc.Resolve<IStore<IFiberLoop<DialogTask>>>(), cc.Resolve<Func<IDialog<object>>>());
                post = new ExceptionTranslationDialogTask(post);
                post = new LocalizedDialogTask(post);
                post = new ScoringDialogTask<double>(post, stack, cc.Resolve<CompositeScorable<double>>());
                return post;
            };

            IPostToBot outer = new PersistentDialogTask(makeInner, cc.Resolve<IMessageActivity>(), cc.Resolve<IConnectorClient>(), cc.Resolve<IBotToUser>(), cc.Resolve<IBotData>());
            outer = new SerializingDialogTask(outer, cc.Resolve<Address>(), c.Resolve<IScope<Address>>());
            outer = new PostUnhandledExceptionToUserOverrideTask(outer, cc.Resolve<IBotToUser>(), cc.Resolve<TraceListener>());
            return outer;
        })
        .As<IPostToBot>()
        .InstancePerLifetimeScope();
    }
}
```

The code for `PostUnhandledExceptionToUserOverrideTask` is below, where `Common.SomethingWentWrong` is some custom content:

``` csharp
public class PostUnhandledExceptionToUserOverrideTask: IPostToBot
{
    private readonly IPostToBot _inner;
    private readonly IBotToUser _botToUser;
    private readonly TraceListener _trace;

    public PostUnhandledExceptionToUserOverrideTask(IPostToBot inner, IBotToUser botToUser, TraceListener trace)
    {
        SetField.NotNull(out _inner, nameof(inner), inner);
        SetField.NotNull(out _botToUser, nameof(botToUser), botToUser);
        SetField.NotNull(out _trace, nameof(trace), trace);
    }

    async Task IPostToBot.PostAsync<T>(T item, CancellationToken token)
    {
        try
        {
            await _inner.PostAsync(item, token);
        }
        catch (Exception error)
        {
            try
            {
                if (Debugger.IsAttached)
                {
                    await _botToUser.PostAsync($"Exception: {error}", cancellationToken: token);
                }
                else
                {
                    await _botToUser.PostAsync(Common.SomethingWentWrong, cancellationToken: token);
                }
            }
            catch (Exception inner)
            {
                _trace.WriteLine(inner);
            }

            throw;
        }
    }
}
```

This is all wired up within an autofac bootstrapper class with logic like this:

``` csharp
var builder = new ContainerBuilder();
builder.RegisterModule(new DefaultExceptionMessageOverrideModule());
```

I have a wrapper Dialog to capture exceptions - `ExceptionHandlerDialog` - which definitely gets called, as I've set breakpoints which are getting hit:

``` csharp
[Serializable]
public class ExceptionHandlerDialog<T> : IDialog<object>
{
    private readonly IDialog<T> _dialog;

    private static ILogger Logger => // code to get a Logger instance

    public ExceptionHandlerDialog(IDialog<T> dialog)
    {
        _dialog = dialog;
    }

    public async Task StartAsync(IDialogContext context)
    {
        try
        {
            context.Call(_dialog, ResumeAsync);
        }
        catch (Exception e)
        {
            Logger.Error(e);
        }
    }

    private async Task ResumeAsync(IDialogContext context, IAwaitable<T> result)
    {
        try
        {
            context.Done(await result);
        }
        catch (Exception e)
        {
            Logger.Error(e);
        }
    }
}
```

My problem is that `PostUnhandledExceptionToUserOverrideTask` is never getting called, and instead the default `PostUnhandledExceptionToUserTask` is still being called when an exception occurs.

I believe it's down to the order/timing of autofac registration, since I wire mine up in a bootstrapper class that is fired off from the Global.asax's `Application_Start`, whereas the default one appears to get wired up from `Conversation`'s static constructor, which will get called at the point of firing off the static method `Conversation.SendAsync` which calls `DialogModule_MakeRoot`:

https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Dialogs/Conversation.cs#L54

Which in turn loads the `DialogModule`:

https://github.com/Microsoft/BotBuilder/blob/5cf71c742f27d89e9dbc4076f850122bd6edac11/CSharp/Library/Dialogs/DialogModule.cs#L237

Which is where the `PostUnhandledExceptionToUserTask` is wired up:

https://github.com/Microsoft/BotBuilder/blob/5cf71c742f27d89e9dbc4076f850122bd6edac11/CSharp/Library/Dialogs/DialogModule.cs#L212

So - how can I override something that appears to be so exceptionally late-bound in IoC? Should I start a dummy Conversation to force the static constructor to fire, then override it?.. Is there an autofac setting to say "don't you dare override this registration, m'kay"?

pls help ktnxbai

**Comment by willportnoy** [comment]
Do you call builder.Update(Conversation.Container)?

Separately, does Logger.Error propagate the error?

**Comment by rposbo** [comment]
No, no calls to builder.Update; should there be?

And good question about error propagation; I need to dig into the implementation..

**Comment by willportnoy** [comment]
Yes, to update the container you package up the changes with a ContainerBuilder and then you need to call the builder's Update method on the static Conversation.Container (or build your own custom container and use how you like).

**Comment by msft-shahins** [comment]
As @willportnoy mentioned you should update the container that is used by the conversation. Here is an example of how you can add/override a registration within the container: https://github.com/Microsoft/BotBuilder/blob/5cf71c742f27d89e9dbc4076f850122bd6edac11/CSharp/Tests/Microsoft.Bot.Builder.Tests/ScorablesTests.cs#L115

Another approach is that you can have your own custom container and implement what conversation.Send is implementing to post the incoming activity to the bot. Here is an example of that: https://github.com/Microsoft/BotBuilder/blob/5cf71c742f27d89e9dbc4076f850122bd6edac11/CSharp/Tests/Microsoft.Bot.Builder.Tests/PromptTests.cs#L96

**Comment by rposbo** [comment]
Hi,

Thanks for your feedback. The links you've shared, @msft-shahins , are to tests that don't seem to use `Conversation` so I'm assuming are just to show how `builder.Update` can be called?

If you try that example code you've pasted and try to register something that is already registered in the `DialogModule` then you'll find that calling `Conversation.SendAsync` will override your registration, since `Conversation` is static and the registration of `DialogModule` happens in the static constructor which is only called the first time you call `SendAsync`..

In fact, I've now tried using `builder.Update` pretty much everywhere I can think of leading up to the `MessagesController`, and it's always overridden by `Conversation`'s static constructor registration of `DialogModule`.

The only solution I've found, was from my question at the end of my first post: start a dummy Conversation to force the static constructor to fire, then override it. This is the horrific - but functional - result:

```csharp
        static MessagesController()
        {
            // I'm so, so sorry. 
           // Force the static constructor to fire
            try { Conversation.SendAsync(null, () => null); } // don't await cos it doesn't matter
            catch (Exception) { } // nulls will throw

            // now I can override Conversation's registration
            var builder = new ContainerBuilder();
            builder.RegisterModule(new DefaultExceptionMessageOverrideModule());
            builder.Update(Conversation.Container);
        }
```

Hopefully you can now see my situation, and can see how Conversation's static constructor's late registration of `DialogModule` will always override any custom registration of `IPostToBot` - I believe all other users who have raised this issue may not have been using `Conversation`.

Statics. Ouch.

Thoughts? Can we improve this? I'll dig around and probably submit a PR shortly

**Comment by msft-shahins** [comment]
@rposbo static constructor will be called before `builder.Update(Conversation.Container);` since that call is accessing a static member of the static class: 

> A static constructor is called automatically to initialize the class before the first instance is created or any static members are referenced.
https://msdn.microsoft.com/en-us/library/k9x6w0hc.aspx

**Comment by rposbo** [comment]
Yes, I understood how the static constructor worked, hence my hack to force it to fire by creating a dummy message first! It looks like I was not passing in `Conversation.Container` correctly to the `builder.Update` - an utterly fundamental requirement for this override to work!

Thank you all for your patience - I've got there in the end by adding the following at the end of my IoC boostrapper:

```csharp
var conversationBuilder = new ContainerBuilder(); 
conversationBuilder.RegisterModule(new DefaultExceptionMessageOverrideModule());
conversationBuilder.Update(Conversation.Container);
```

**Comment by willportnoy** [comment]
fyi, this commit https://github.com/Microsoft/BotBuilder/commit/31048a2173313c81a2db47efce6a8a869b4ec284 should help disable PostUnhandledExceptionToUser.
