### ISSUE TITLE
Index was outside the bounds of the array

### ISSUE THREAD

**Issue by ZOXEXIVO** [Microsoft/BotBuilder#1447]
Sometimes bot is unavailable and very slow to answer. In log i see

Index was outside the bounds of the array

**Comment by danmarshall** [comment]
Can you add a code snippet? Are you in C# or Node.js ? And, which channel? Or are you seeing this in the emulator?

**Comment by ZOXEXIVO** [comment]
Problem in Telegram.
Skype work perfect, but Telegram most time is very slow and in bot logs i find this error.
I move from Async to Sync. 
Bot send is HeroCard

HeroCard plCard = new HeroCard
            {
                Text = post.Text,
                Buttons = new List<CardAction>
                                        {
                                            new CardAction
                                            {
                                                Value = command,
                                                Type = "postBack",
                                                Title = "Next"
                                            },
                                            new CardAction
                                            {
                                                Value = "GET#" + post.SysId,
                                                Type = "postBack",
                                                Title = "Open"
                                            },
                                            new CardAction
                                            {
                                                Value = ".menu",
                                                Type = "postBack",
                                                Title = "Menu"
                                            }
                                        },
                Images = !string.IsNullOrWhiteSpace(post.ImageUrl) ? new List<CardImage> { new CardImage(url: post.ImageUrl) } : new List<CardImage>()
            };`

**Comment by eanders-MS** [comment]
@ZOXEXIVO We're logging this error on behalf of your bot. Your bot is throwing this exception. Have you tried running your bot locally in a debugger to catch the exception at the moment it is thrown?

**Comment by ZOXEXIVO** [comment]
@eanders-MS My code haven't places, that must throw this Exception. 
MVC Action executes with success result and ExceptionFilter not catch anything. 
WebChat, Skype works ok.

**Comment by eanders-MS** [comment]
@ZOXEXIVO what is your bot id?

**Comment by eanders-MS** [comment]
Resolved with https://github.com/Microsoft/BotBuilder/issues/1563
