### ISSUE TITLE
How to have multiple users participating on the same conversation?

### ISSUE THREAD

**Issue by ejadib** [Microsoft/BotBuilder#145]
Hi,

I'm building a simple bot in C# that will be used on Slack. The idea is to send a message to the bot with a list of users that should participate of the conversation, something like:

@bot start @user1 @user2 @user3

Then the idea is to have the bot asking each of the users mentioned to answer some questions. So far I was able to get that running only for the user than initiates the conversation. 

This should emulate the flow I'm envisioning:

**user1**: @bot colors @user1 @user2
**bot**: OK, tell me your favorite colors. @user1 you start:
**user1**: red
**user1**: blue
**user1**: done => this triggers the end of @user1 answers
**bot**: ok, great. your fav colors are red and blue.
**bot**: @user2 you go next
**user2**: green =====> here is where I'm stuck. even if @user2 responds or send a message the bot is not recognizing that message as part of the same conversation.

So the question: Is it possible to add users to a conversation based on the mentions in the first message so the bot can recognize a message of a user different from the one that initiates the conversation?

Thanks in advance!

**Comment by tomlm** [comment]
Interesting.  Currently the bot needs to be mentioned by user2 to be added to conversation.  We should probably make it that the bot mentioning user2 adds them to the conversation as well.  I will add that as a bug.

**Comment by ejadib** [comment]
Thanks for your response @tomlm. When the user2 mentions the bot is added to the conversation, however it's starting from the first dialog even. Is there a way to pass the user2 messages directly to the second dialog started to by the conversation of user1?

My flow, this time with dialogs:

**user1**: @bot colors @user1 @user2 => main dialog
**bot**: OK, tell me your favorite colors. @user1 you start: => instantiates second dialog
**user1**: red => messages received in the second dialog
**user1**: blue
**user1**: done => end of second dialog (context.Done...)
**bot**: ok, great. your fav colors are red and blue. => back to the main dialog
**bot**: @user2 you go next => instantiates second dialog

If there isn't a way to do that I think that I can handle that in the code and instantiates the second dialog once I receive the message from the user2 and not once user1 ends.

**Comment by v-thgratMSGit** [comment]
This feature request has been moved to UserVoice: https://feedback.botframework.com/forums/354213-general/suggestions/13621638--request-multiple-users-in-same-conversation

**Comment by giriganapathy** [comment]
Any updates on this.  I have such requirements where user 2 should talk to user 1 via bot.  Is that possible?

**Comment by giriganapathy** [comment]
let me brief my scenario: 
a. say my bot is talking to customer...
b. at one point, customer needs a real human/agent to discuss. so in this case, I have to invite somehow a real agent/human to join this ongoing session, and connects this agent with customer.  once the agent joined the session, all the conversation (made between my bot and customer) should get copied to agent, and from there the agent continue with the customer.

I envisioned like the real agent also should be interacted with bot and ask question, and the bot should post it to customer, and also the customer reply should go to bot, and my bot should forward the same to agent.

Is it possible now?
