### ISSUE TITLE
Can't use prompts  in  WEB CHAT channel

### ISSUE THREAD

**Issue by rociocastillo** [Microsoft/BotBuilder#1450]
Hello, I'm trying this example using as web chat channel and is not running the second function that is where prompt response processes.
the same example works well on facebook.

bot = new builder.UniversalBot(connector);

bot.dialog('/', [
    function (session) {
        builder.Prompts.text(session, "Hello... What's your name?");
    },
    function (session, results) {
        session.userData.name = results.response;
        builder.Prompts.number(session, "Hi " + results.response + ", How many years have you been coding?"); 
    },
    function (session, results) {
        session.userData.coding = results.response;
        builder.Prompts.choice(session, "What language do you code Node using?", ["JavaScript", "CoffeeScript", "TypeScript"]);
    },
    function (session, results) {
        session.userData.language = results.response.entity;
        session.send("Got it... " + session.userData.name + 
                     " you've been programming for " + session.userData.coding + 
                     " years and use " + session.userData.language + ".");
    }
]);

Thank you very much for your help.

**Comment by danmarshall** [comment]
Can you open F12 developer tools in your browser to see if there are any errors in the console?

**Comment by rociocastillo** [comment]
yes, no error

**Comment by somuit91** [comment]
I am also facing the same issue, did you/anyone fix the issue?

**Comment by chrimc62** [comment]
@danmarshall is there anything else you need to diagnose the issue?

**Comment by danmarshall** [comment]
Hi @rociocastillo do you still see this issue?  Also we have a preview version of our web chat control, you may want to try it out.

**Comment by rociocastillo** [comment]
Hi, already solved was a problem of sending messages to directiline.

Thank you.
regards
