### ISSUE TITLE
NotImplementedException is thrown even though code doesn't hit the call

### ISSUE THREAD

**Issue by panuganti** [Microsoft/BotBuilder#1451]
It is very common to have some parts of the code with throw NotImplementedException during the development process. 

When using the framework with Facebook, if any method has this exception and even though the code line corresponding to it is not hit yet, it still throws the exception.

**Comment by danmarshall** [comment]
Are you using C# or Node.js ?

**Comment by willportnoy** [comment]
@panuganti can you share a stack trace for the original throw of the NotImplementedException?

**Comment by panuganti** [comment]
@danmarshall  c#
