### ISSUE TITLE
Callstack is invalid after new NodeJS deployment

### ISSUE THREAD

**Issue by seb0zz** [Microsoft/BotBuilder#1453]
Hi,

I am using the BotBuilder on Heroku (NodeJS) together with the Facebook messenger. Everything really works like a charm. There is only one issue with the conversation state after deployments. Everytime I do a new deployment to Heroku (NodeJS will be restarted and local memory cleared). When a Prompt is started for a user before the deployment and the users answers to that Prompt after the deployment, the session state will be resetted so the answer of the user does not come back into my current dialog flow. I can see a corresponding message in my log file in that situation:

`2016-10-18T11:15:32.958546+00:00 app[web.1]: ....Prompts.choice - WARN: Callstack is invalid, resetting session.`

Does anyone have a clue how to fix this issue? If you need some more code snippets just let me know.

**Comment by Stevenic** [comment]
Are you making significant changes to the bots dialogs?  We do a scan to see if any of the dialogs on the callstack are missing. If they are the bot will eventually hit a dead end so we just clear everything and start over.

**Comment by seb0zz** [comment]
No. The bug also occurs when I deploy no changes to dialogs or to anything else that could affect the bot. The issue even occurs when I deploy with exact the same code base :/

Sent from my phone

**Comment by Stevenic** [comment]
Hmm... I just looked at the code and it would only trigger that error if it couldn't find a dialog that's listed as being on the stack.  You're not dynamically adding dialogs to bot are you?  By that I mean do you ever call `bot.dialog()` in response to some user action or after some sort of async operation completes? That's the only thing I could think of that would cause this behavior.

**Comment by seb0zz** [comment]
@Stevenic That was a good hint! Actually I am adding dialogs dynamically and that must be the issue 🙈 you are a genius 😄 

I close this issue as I am pretty sure this will be the fix 👍

**Comment by Stevenic** [comment]
I just wrote the damn thing is all :)

**Comment by Stevenic** [comment]
Additionally... We like hearing all of your issues, even when they're your own so that we can think about changes to the framework that would help avoid this in the future.  I've already made several changes purely because people kept getting hung up in the same spot.
