### ISSUE TITLE
How to confirm if message reply is delivered

### ISSUE THREAD

**Issue by afficionaddo** [Microsoft/BotBuilder#1455]
Hi,

I am working on a bot with FB messenger & MSFT BotFramework 
How do I check if the message-reply is successfully delivered to FB messenger?

Does it return any type of data after reply is sent?
How can I verify that no error occured at BotConnector's end while delivering?

**Comment by VishalWaman** [comment]
+1

**Comment by tomlm** [comment]
The return code will be 200 or 201 if it successfully is submitted to facebook, otherwise the statuscode will be the statuscode returned by facebook.
