### ISSUE TITLE
System.Net.Http.HttpRequestException: An error occurred while sending the request

### ISSUE THREAD

**Issue by arpan14** [Microsoft/BotBuilder#1458]
I have made a basic bot. Earlier it was working when I had the following as my BOT URL
**https://localhost:3979/api/messages** . However now it is throwing me an error. 

The stack trace can be found in the attached image below.

![issue](https://cloud.githubusercontent.com/assets/13822925/19493150/2df8b6e0-9597-11e6-9c32-3bb3ae3e236a.PNG)

Now the following error gets resolved when you use the link, however I get **401 Unauthorized error.**
http://localhost:3979/api/messages as your BOT URL.

Ultimately I want the BOT to be hosted on **Azure** and therefore would require **https**. 
Any fix to the above issue?

**Comment by danmarshall** [comment]
Is your issue similar to this: https://github.com/Microsoft/BotBuilder/issues/1211

**Comment by tomlm** [comment]
I would restart the emulator.

**Comment by huxaiphaer** [comment]
What is the solution guys
