### ISSUE TITLE
How To Use Multiple Luis Models in a same program.I am using C#. Please provide a sample code if anyone have .

### ISSUE THREAD

**Issue by Masssluis** [Microsoft/BotBuilder#1460]
@msft-shahins , @msftgits @b4usat @willportnoy @evnik  please help

**Comment by jameslew** [comment]
Can you share your code that you've tried so far?  Are you using the BotBuilder SDK or the Connector SDK?

**Comment by willportnoy** [comment]
@Masssluis you can simply use multiple LuisModel attributes on your class, or pass multiple ILuisService instances to your LuisDialog constructor, as in this unit test:
https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Tests/Microsoft.Bot.Builder.Tests/LuisTests.cs#L243

Beware of the caveats: https://docs.botframework.com/en-us/technical-faq/#how-can-i-use-more-than-one-luis-model

**Comment by Masssluis** [comment]
Thanks a lot @willportnoy  for your help. The code is working now.
