### ISSUE TITLE
LUIS App Unable to recognize few words after certain time

### ISSUE THREAD

**Issue by PrasenjitSaha** [Microsoft/BotBuilder#1461]
Hi I have created a LUIS app 2/3 months ago. It was working perfectly fine. But now I have noticed one problem. If I don't use this app for some time say 1/2 weeks. Few words my App can't recognise ( It is forgetting my trained words). Again I need to click on Train button and publish my app. Can you please tell me why this kind of behaviour is happening?

Is this behaviour normal? If yes then what is the time frame to train & publish this app again?

**Comment by CarolHanna** [comment]
No, this behavior is not normal can you please share with us your app ID and examples queries to help us investigate the issue.

**Comment by PrasenjitSaha** [comment]
Hi Carol,
Today (21-Oct-2016 11:35 AM) also that issue happened. My Application ID: b24fa810-2888-4293-8f91-ce33fbb4893d

In LUIS.ai it is showing me right Intent and Entities but in my published API I am getting wrong Intent. And as I mentioned earlier if I click on Train button and republish it it will show me correct intent. 

In my LUIS.ai app Where **no** is my **entity** and **Intent** is **Negative** it is taking correctly

But in my published (https://api.projectoxford.ai/luis/v1/application?id=b24fa810-2888-4293-8f91-ce33fbb4893d&subscription-key=6a0d5b3b04b4498c9c285ae19e433f53&q=no ) json it is showing intents as None

{
  "query": "no",
  "intents": [
    {
      "intent": "None",
      "score": 0.684182763
    },
    {
      "intent": "Negative",
      "score": 0.456288844
    },

Yesterday it was working perfectly.

Regards-
Prasenjit

**Comment by v-youel** [comment]
Hi Prasenjit,

So I checked the logs and it seems that the predictions changed AFTER a publish on 20/10/106 10:42 am. You might have added utterances that negatively affected your 'Negative' intent model. After a publish that was done on 21/10/2016 1:02 pm the model seems to have improved.

The model should **not** work differently between different publishes. Any changes you make should be reflected on LUIS after you train (but not on the endpoint). Once you publish the latest TRAINED models will be published and these models will be used for the endpoint.

Hope that helps.

Best regards,
Youssef

**Comment by PrasenjitSaha** [comment]
Hi, Again same things happened. "hello" is trained as "Greetings" Intent in Luis.ai but in my published url it is showing "None".  https://api.projectoxford.ai/luis/v1/application?id=b24fa810-2888-4293-8f91-ce33fbb4893d&subscription-key=6a0d5b3b04b4498c9c285ae19e433f53&q=hello . Result is coming like -
{
  "query": "hello",
  "intents": [
    {
      "intent": "None",
      "score": 0.9616027
    },
    {
      "intent": "Greetings",
      "score": 0.8632229
    },
    {
I have submitted the Intent again and again. But in Publish api it is showing different. I believe that is a bug. Can you please look into it?

**Comment by PrasenjitSaha** [comment]
Hi,
Hi, Again same things happened. "hello" is trained as "Greetings" Intent in Luis.ai but in my published url it is showing "None". https://api.projectoxford.ai/luis/v1/application?id=b24fa810-2888-4293-8f91-ce33fbb4893d&subscription-key=6a0d5b3b04b4498c9c285ae19e433f53&q=hello . Result is coming like -
{
"query": "hello",
"intents": [
{
"intent": "None",
"score": 0.9616027
},
{
"intent": "Greetings",
"score": 0.8632229
},
{
I have submitted the Intent again and again. But in Publish api it is showing different. I believe that is a bug. Can you please look into it?

LUIS.ai Screen shot –

[cid:image001.png@01D2307D.33C6AF70]
Last Trained : [cid:image002.png@01D2307D.33C6AF70]

Published :
[cid:image005.jpg@01D2307D.9EEA0DB0]

Regards-
Prasenjit

**Comment by CarolHanna** [comment]
This behavior is expected because what you are getting on the UI is not the model prediction but the label yet when you hit the endpoint, this is the real prediction score of the model. Since those are machine learned models there is still percentage error on the training data. I will change the UI to show the confidence in case of labeled data because it’s always confusing to the users.

**Comment by PrasenjitSaha** [comment]
Thank you Carol for your reply & help. 
There is one confusion that **LUIS** UI may not show the actual prediction( Accordingly your version) but how come my end point which was working previously and not working for some time & after republish it is working. Actually we have created a BOT using MS BOT and LUIS. We have proposed it to multiple client. If this kind of experience happen it will create a bad impression. I have working experience with other NLP tools like IBM watson / LUCY they don't have that kind of issue. **So, may I request you to check my LUIS app and find out is there any abnormality happening?** Basically I have trained this app with 3 types of cases - 
1. My password is not working , 2. My internet is not working & 3. I need a device with it I have other Intent like Hi, Hello , No, Yes, bye bye that kind of intent.

**Comment by chrimc62** [comment]
@CarolHanna can you comment or close as appropriate?  thanks!

**Comment by stelazh** [comment]
i have the same error...did you resolve it ?

**Comment by ramicodes** [comment]
same issue here
