### ISSUE TITLE
[UI Issue] Carousel Dialogue Not Working for Web Chat Channel using iframe

### ISSUE THREAD

**Issue by abhayverma** [Microsoft/BotBuilder#1462]
- The Carousel Dialogue is not displayed in Web Chat, instead it's shown as a list.
- Also, the Cards don't have title binded with the Card Image, instead the title is shown as a text message after the image.

**Note : The above listed issues are UI specific.**

**Comment by jameslew** [comment]
The webchat control currently has limited capability with respect to cards and carousels.  We're working on an updated version with richer support for these features.

**Comment by digitallawyer** [comment]
@jameslew is the update to the webchat with richer support for cards far out on the roadmap? Trying to get a sense to help with internal planning. 

Thanks for all the hard work!

**Comment by chrimc62** [comment]
We have released a new emulator and web chat to open source.  Please try them out and if you have an issue, propose a fix or let us know.

**Comment by ubreddy** [comment]
can you update your iframe to have the latest webchat? otherwise what is the point of you having webchannel that is not current and has not been updated to latest webchat release?
