### ISSUE TITLE
[node.js] Missing locale property on IRecognizeContext interface

### ISSUE THREAD

**Issue by JoseAntonioRodriguez** [Microsoft/BotBuilder#1463]
It seems like the `IRecognizeContext` interface declared in `botbuilder.d.ts` is missing the `locale` property, so you cannot pass a locale to `recognize` methods of `LuisRecognizer` or `IntentDialog` classes.

**Comment by Stevenic** [comment]
I think I added it but it didn't get copied to the released lib. I'll double check.

**Comment by dandriscoll** [comment]
It appears locale/preferredLocale() has been added to botbuilder.d.ts. Closing issue.
