### ISSUE TITLE
Cannot disable localizer

### ISSUE THREAD

**Issue by seb0zz** [Microsoft/BotBuilder#1466]
Currently it is not possible to disable the localizer entirely. Even when `localizer: false` is passed to the bot settings a default localizer will be used. Don't know if this is by design and/or if not at least this would be something to discuss about 😉 

Why I was stumbling upon this is because my app is always throwing the following warning and my bot doesn't need any i18n at the moment:
`WARN: localizer::couldn't find directory: ./en`

**Comment by ponarunkumar** [comment]
![image](https://cloud.githubusercontent.com/assets/6130502/19525403/d3f4c122-95ee-11e6-96db-7917a3f378eb.png)
the localizer samples would definitely help.

**Comment by Stevenic** [comment]
I saw the warning as well and will remove them in the next release.  The `localizer` param is for passing in a custom localizer implementation so not a flag. You can safely ignore the warning for now.
