### ISSUE TITLE
Skype Receipt Documentation wrong description for fields "total", "tax", "vat", "items"

### ISSUE THREAD

**Issue by iassal** [Microsoft/BotBuilder#1467]
https://docs.botframework.com/en-us/skype/getting-started/#cards-and-buttons

![image](https://cloud.githubusercontent.com/assets/4086459/19524845/5f7136e2-961f-11e6-9c35-d03194342d38.png)

**Comment by nickcordrey** [comment]
Thanks very much for raising this issue the page has been updated.
