### ISSUE TITLE
Required Help in configuring proxy in VS Code 

### ISSUE THREAD

**Issue by vignestheo** [Microsoft/BotBuilder#1469]
Hello Team 

I developed bot everything is working fine for me without any configuration for proxy [where i can install extension and can access bot out side via ngork too] but when i thought of sending bot data to my custom API using Request module in Node js.

It's keep on throwing me error that configure the proxy but i kept the settings in both node npm config and in VS code but nothing helps ... :-(

Please some one provide your assistance

**Comment by vignestheo** [comment]
when i tried to acccess URL i.e. API by using below coding 
bot.dialog('/', [
    function (session) {


        request("http://theoteq.xyz/fruitroid/home/getDonor", function(error, response, body) {
                 console.log(body);
                 
            });

  Unfortunately, you do not have the correct                                                                                               
            proxy settings configured to access the internet.                                                                                        
This is what printing in command prompt

**Comment by eanders-MS** [comment]
@vignestheo This sounds like a platform configuration problem rather than botbuilder. Are you able to query the url using a command line tool like `curl`? e.g.:
```
C:\> curl http://theoteq.xyz/fruitroid/home/getDonor
```
If success, you should see:
```
StatusCode        : 200
StatusDescription : OK
...
```

**Comment by vignestheo** [comment]
even i am not able to get output for any http protocol URL say eg http://www.modulus.io

but when i provide it as https protocol its working for me :-( then is it mandatory to change my to https instead of http?

**Comment by vignestheo** [comment]
When i hit the URL in browser , Please see the screenshot for the same

![image](https://cloud.githubusercontent.com/assets/20864942/19536427/8643cfd8-9669-11e6-9027-2ba0bb1f0e5f.png)

**Comment by vignestheo** [comment]
Myself Resolved the issue anyway thanks for your immediate response.

I am happy i resolved...:-D
