### ISSUE TITLE
on message received send back to message received

### ISSUE THREAD

**Issue by alokraj68** [Microsoft/BotBuilder#1471]
Hi,
What should I do to close a conversation on a message received and send back to the beginning stage?

The whole data can be reset if needed.

Just want to begin the whole dialogue again.

**Comment by palmerabollo** [comment]
You can do ```session.replaceDialog(your_dialog_id)```

**Comment by alokraj68** [comment]
@palmerabollo Let's say, am in a function,I give a prompt and user types in something, whatever the message be I want to send him to the starting of the whole conversation.
I don't have any session set as of now.

```
        private Task SendtoStart(IDialogContext context, IAwaitable<object> result)
        {
            context.Reset();
           // need to reste and send to MessagesController as a new msg from here
        }
```

**Comment by palmerabollo** [comment]
Sorry, I thought you were using the node.js SDK. There must be something similar in the C# implementation, but I can't help you here.

**Comment by alokraj68** [comment]
It's fine i got the code for that!

**Comment by palmerabollo** [comment]
@alokraj68 It would be nice if you could share it

**Comment by alokraj68** [comment]
@palmerabollo its actually a bad method. and am having some issues in that. once the issues are solved, i shall post it here.
