### ISSUE TITLE
Passing custom args to intentDialog.matches.

### ISSUE THREAD

**Issue by strangecyan** [Microsoft/BotBuilder#1472]
I have a dialog that is triggered from a LUIS model:
`IntentDialog.matches('luisIntentID', 'dialogID', customArgs);`

I want to pass the customArgs into the start of the 'dialogID' dialog but they're overwritten by the LUIS information (entities, intents, confidence, etc). Is there anyway to persist those custom args?

Thanks in advance.

**Comment by Stevenic** [comment]
Are you saying your customArgs aren't in the set? I just looked at the code and they should definitely be there.  They will get merged with the intents, entities, and score from LUIS. are you needing them to not be merged?  If so, there's no way to prevent that but what you could do is add a level a redirection so pass in { custom: {customArgs} } instead.

Steve

**Comment by strangecyan** [comment]
Thanks Steve,

Now I look at it again, it is merging but not the way I was expecting. `customArgs` in my case is a string and it seems to separate each character into it's own property. 

```
{  
   "0":"c",
   "1":"u",
   "2":"s",
   "3":"t",
   "4":"o",
   "5":"m",
   "score":0.7555546,
   "intent":"isg.lockedOut",
   "intents":[...],
   "entities":[...]
}
```

Object work as you'd expect and just merge into the args object but strings are split up into their characters and for arrays, each property is merged into the args, instead of remaining in an array; `[string, custom]` turns into `"0":"string",  "1":"custom"`.

Thanks,
James

**Comment by Stevenic** [comment]
customArgs MUST be an object.
