### ISSUE TITLE
Luis : a paying service? 

### ISSUE THREAD

**Issue by TechWatching** [Microsoft/BotBuilder#1474]
Will there be a way of using Luis for free in the future? According to Luis site next year it won't be possible to use Luis without requesting an Azure key which is not available without paying...
I wonder what's the point of spending time understand Luis and how to use it in the bot framework if that service become a paid service  once learnt. Why is there not a plan for free usage of Luis with a limited amount of request? Or is it I who did not understand correctly the future changes for Luis? 

.

**Comment by jameslew** [comment]
LUIS actually does have a model where a number of requests are free (as of the time I type this it's 10k transactions per month); after which you need paid service.  The current pricing details for all of the Cognitive Services can be found here:

https://www.microsoft.com/cognitive-services/en-us/pricing

--jim

**Comment by CarolHanna** [comment]
LUIS offers a free tier with 10k free transaction per month with 5 QPS. This is for the runtime/endpoint but the model authoring will remain totally for free.

**Comment by TechWatching** [comment]
OK thanks.
