### ISSUE TITLE
Bug on API v3

### ISSUE THREAD

**Issue by dhanielfv** [Microsoft/BotBuilder#1476]
From error

**The 'from' field is unrecognized**

https://directline.botframework.com/v3/conversations/<conversationId>/activities

Post data:

```
{   
    "type":"message",
    "from": {"id":"@mybot", "name":"test"},
    "text": "Test"
}

```

Result:

```
{
  "message": "The 'from' field is unrecognized"
}
```

if  remove "from", but in swagger from is not required

```
{
  "message": "The 'from' field is required"
}
```

**Comment by dandriscoll** [comment]
Hi @dhanielfv, the Direct Line channel talks two different protocols: Direct Line 1.0, and Bot Framework v3.

/v3/conversations is the Bot Framework v3 endpoint for bots.

/api/conversations in the Direct Line 1.0 endpoint for clients. Reference documentation here: https://docs.botframework.com/en-us/restapi/directline/

To send a Direct Line 1.0 message, POST your request to /api/conversations and include "from" as a string. Here is an example from the document I linked:

-- connect to directline.botframework.com --
POST /api/conversations/abc123/messages HTTP/1.1
Authorization: BotConnector RCurR_XV9ZA.cwA.BKA.iaJrC8xpy8qbOF5xnR2vtCX7CZj0LdjAPGfiCpg4Fv0
[other headers]

{
  "text": "hello",
  "from": "user1"
}
