### ISSUE TITLE
IDialog method execution finished with no resume handler specified through IDialogStack. c#

### ISSUE THREAD

**Issue by alokraj68** [Microsoft/BotBuilder#1477]
Here is my code

**The following code works in bot emulator but not in skype.**

This code gives 

> IDialog method execution finished with no resume handler specified through IDialogStack
in skype and in Bot emulator it works without any issues! 

`
 using Microsoft.Bot.Builder.Dialogs;
 using System;
 using System.Threading.Tasks;

 namespace test
 {
     [Serializable]
    public class test : IDialog<object>
    {
        public Task StartAsync(IDialogContext context)
        {

            context.PostAsync("Hello,Welcome to bot");
            context.PostAsync("Hello,Welcome to bot");
            context.PostAsync("Hello,Welcome to bot");
            context.Wait(MessageReceived);
            return Task.CompletedTask;
        }

        private Task MessageReceived(IDialogContext context, IAwaitable<object> result)
        {
            string WelcomeMsg = "";
            WelcomeMsg = "Hello!";

            try
            {
                var PromptOptions = new string[] { "Yes", "No" };
                PromptDialog.Choice(
                context,
                WelcomePrompt,
                PromptOptions,
                WelcomeMsg, promptStyle: PromptStyle.Auto
                );
            }
            catch (TooManyAttemptsException ex)
            {
  await context.PostAsync(ex.ToString());
            }
            return Task.CompletedTask;
        }

        private async Task WelcomePrompt(IDialogContext context, IAwaitable<string> result)
        {
            var Prompt = await result;
            string PromptString = Prompt.ToString().ToLower().Trim();

            if (PromptString.Length > 0)
            {

                PromptString = PromptString.Trim();

                if (PromptString == "give me predictions")
                {

                   await context.PostAsync("Can we continue?");
                    
                    First F = new First(1);
                    await F.StartAsync(context);
                }
                else
                {

                    await context.PostAsync("Can we continue?");
                   sec s = new sec();
                    await s.StartAsync(context);
                }
            }
        }

    }

}

`

**Comment by willportnoy** [comment]
I don't see any call to IDialogStack.Wait in MessageReceived, so the code seems incorrect regardless.  Generally, you don't call StartAsync yourself - it's called by the framework when you call a child dialog with IDialogStack.Call.

**Comment by alokraj68** [comment]
@willportnoy so how should the class be rewritten?

and also why does the error don't show in bot emulator? it works well there :(

**Comment by willportnoy** [comment]
WelcomePrompt might use context.Call(new First(), ResumeAfterFirst) or context.Call(new Second(), ResumeAfterSecond) to call a child dialog.

I'm not sure about the emulator difference.  That seems like a code difference, or possibly a serialized dialog stack from a previous version of the code.

**Comment by alokraj68** [comment]
@willportnoy  Yea, it was because skype was keeping the old session of the user. I deleted it using,
`                    activity.GetStateClient().BotState.DeleteStateForUser(activity.ChannelId, activity.From.Id);
                    await activity.GetStateClient().BotState.DeleteStateForUserAsync(activity.ChannelId, activity.From.Id);
`

Thank you! You can close this issue now 👍

**Comment by willportnoy** [comment]
Thank you - feel free to open a new issue for further discussion.
