### ISSUE TITLE
Attachment size

### ISSUE THREAD

**Issue by fercom** [Microsoft/BotBuilder#1478]
Is it possible to know the file size of an attachment before the bot process it? like in the message controller? I am getting very large files

**Comment by palmerabollo** [comment]
Maybe you can make a HEAD HTTP request to the attachment contentUrl to get the Content-Length response header and decide whether to download it or not.

**Comment by tomlm** [comment]
That's the correct method, it's standard HTTP stuff.

**Comment by fercom** [comment]
Thank you!
