### ISSUE TITLE
Context based on unique userdata peoperty

### ISSUE THREAD

**Issue by palashjhabak** [Microsoft/BotBuilder#1479]
Hi,

I know it is currently not possible.

But I have a scenario in which I get callbacks on a webhook url from a 3rd party service on which I dont have any control over. They send their unique userd ids. So is the only option for me to have some sort of a mapping (their user id to botframework channel specific user id) in a separate database ?

Could it be possible to create context based on some unique userdata property?

Thanks

**Comment by ankitbko** [comment]
Maybe I didn't really understood your complete flow. You have your user talking to the bot using a channel; and a 3rd party service will give you a callback with a id per user. Why can't you store this 3rd party id in the Bot State service under User property? So next time the user sends you the message, you get your unique id in the context.

**Comment by palashjhabak** [comment]
yes but I want to send message as and when I get callback from 3rd party service.

**Comment by ankitbko** [comment]
Ah now I get it. Then you will need to maintain a map in your DB.

**Comment by palashjhabak** [comment]
yup. wouldnt it be great to create context/session based on unique userdata we set.

**Comment by ankitbko** [comment]
Well you can implement [IBotDataStore](https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Dialogs/BotData.cs#L58) and store it with any key as you want. I created one to use [Redis](https://github.com/ankitbko/Microsoft.Bot.Builder.RedisStore) to store the context.

**Comment by palashjhabak** [comment]
Hey,

even if I create the context after I receive the callback, how do I send message to user?

**Comment by tomlm** [comment]
If you have the conversationId you can reply back at any time
If you don't have the conversationId you can create a conversation (getting a conversation Id) and then send a message to it.

Look at this info for basic patterns in C# land, they are wrappers around the REST API
https://docs.botframework.com/en-us/csharp/builder/sdkreference/routing.html
