### ISSUE TITLE
FullScreen and Local Web Client

### ISSUE THREAD

**Issue by JpEncausse** [Microsoft/BotBuilder#1480]
Hi,
I have to demo MS Bot Framework locally on my computer (without web access) in a shinny web UI.

I wondering if someone already did a MS BotFramework Web Client working locally with the running server on http://127.0.0.1 ?

(The other idea is to also trigger local IoT because client and server are on the same computer)

**Comment by kenrick95** [comment]
You can demo it using [Bot Framework Channel Emulator](https://docs.botframework.com/en-us/tools/bot-framework-emulator/).

If not, you'll have to build the web client from scratch, with API defined in [Direct Line REST API](https://docs.botframework.com/en-us/restapi/directline/) I think.

**Comment by JpEncausse** [comment]
I assume Direct Line REST API talk to MSServer that will forward to my server.
Because I'll have no connectivity I'm looking for a library to handle JSON locally.

Not very hard, jsut wondering if someone already did it :-)

**Comment by kenrick95** [comment]
I see what you mean, I think the offline capability is [on progress (see this pull request)](https://github.com/Microsoft/BotBuilder/pull/1320)
