### ISSUE TITLE
Questions for WebBot 

### ISSUE THREAD

**Issue by arjunanc** [Microsoft/BotBuilder#1484]
I am a beginner for  developing the Web Bot using C# and get connected with MS-Azure, Following are the Blocks happened for simple Applications.
1. Couldn't able to do a basic data type Validations  
2. Set /Retrieve Alert Message
3. Also general Logical implementation not working

**Comment by Andrea-Orimoto** [comment]
do you have a public repo with your code?

**Comment by chrimc62** [comment]
Closing due to age.  If you still have an issue, please let us know.
