### ISSUE TITLE
contactRelationUpdate not working on Slack

### ISSUE THREAD

**Issue by stanleycyang** [Microsoft/BotBuilder#1485]
I want my bot to send a welcome message when added to the team for Slack. My code looks like this: 

``` js
bot.on('contactRelationUpdate', function (message) {
    if (message.action === 'add') {
        var name = message.user ? message.user.name : null;
        var reply = new builder.Message()
                .address(message.address)
                .text("Hello %s... Thanks for adding me. Say 'hello' to see some great demos.", name || 'there');
        bot.send(reply);
    } else {
        // delete their data
    }
});
```

Taken from [this example](https://github.com/Microsoft/BotBuilder/blob/master/Node/examples/demo-skype/app.js).

However, the bot never sends a welcome message when added.

This is a requirement to get approval in the Slack store, so there must be a way to handle this.

Any suggestions?

**Comment by tomlm** [comment]
Slack doesn't support the concept of contacts
Slack should send a conversationUpdate activity
see https://docs.botframework.com/en-us/csharp/builder/sdkreference/activities.html

*conversationUpdate* - your bot was added to a conversation or other conversation metadata changed 
*contactRelationUpdate* - The bot was added to or removed from a user's contact list
