### ISSUE TITLE
Facing issue in repying back to emulator

### ISSUE THREAD

**Issue by vignestheo** [Microsoft/BotBuilder#1489]
Hello Team 

Previous coding was working fine i am not sure suddenly i faced micorsoft.net framework issue and then after that i am not able to send the bot response to Emaulator but message is sent to my bot from emulator 

![image](https://cloud.githubusercontent.com/assets/20864942/19620322/ca491536-9898-11e6-8474-3a43ba67ba16.png)

Please help me to resolve this issue

**Comment by eanders-MS** [comment]
Is your bot running on localhost or is it hosted externally (on Azure, or other cloud service)? If external, then you might have a misconfigured service url (where the bot calls back to your emulator).

**Comment by vignestheo** [comment]
Hello Eanders

We are running localhost only.

![image](https://cloud.githubusercontent.com/assets/20864942/19638995/02210fb6-99f4-11e6-9310-bcd6b1c2fae4.png)


Please help me at earliest. I am not sure why bot was not able to send the message to emulator

**Comment by willportnoy** [comment]
So the message sent from the bot to the user shows up in the emulator window, but the call to the bot state service fails?

**Comment by vignestheo** [comment]
No message itself not sending to bot.

E.g. When I send hello from emulator it's showed status accepted but in
order to respond with bot state welcome message it's not send to bot
throwing error as shown in screenshot in above message chain.

**Comment by vignestheo** [comment]
Bot is running in local host

**Comment by eanders-MS** [comment]
@Stevenic Does BotBuilder throw an exception if a botstate query returns 404? @vignestheo In your second screenshot it seems you were able to get past the ECONNREFUSED error. Is that the case?

**Comment by vignestheo** [comment]
Second screenshot we have to consider

**Comment by Stevenic** [comment]
@eanders-MS it would throw an error if it got a 404 because it should never get a 404. When a users data isn't found its supposed to be returning the object below:

```
{
   "etag": "*"
}
```

**Comment by Stevenic** [comment]
This doesn't reproduce for me at all so not sure what's going on.

**Comment by Stevenic** [comment]
@vignestheo are you on a mac by chance? Is this the command line emulator or the windows based emulator?

**Comment by vignestheo** [comment]
Windows based emulator

**Comment by tomlm** [comment]
I have seen ports get stuck, I know it's lame but try rebooting

**Comment by vignestheo** [comment]
I tried after many reboot but nothing works, please provide your help but bot is working in Messenger/Skype but its not working for only emulator. Please provide your assitance

**Comment by tomlm** [comment]
What are your settings for port and serviceurl?

**Comment by vignestheo** [comment]
Where I can see my settings

**Comment by willportnoy** [comment]
At the top of the emulator window.

**Comment by vignestheo** [comment]
[image: pasted1]

**Comment by vignestheo** [comment]
![image](https://cloud.githubusercontent.com/assets/20864942/20112311/e2d07ece-a611-11e6-9883-24fc2f0b00a8.png)

**Comment by chrimc62** [comment]
We have released a new emulator.  If this does not solve your issues, please let us know.

**Comment by sappy5678** [comment]
I have the same problem on the latest version of emulator.
I use this url to connect

`
    http://localhost:3978/api/messages
`
