### ISSUE TITLE
Create a button to call the forward command in Telegram

### ISSUE THREAD

**Issue by dimoibiehg** [Microsoft/BotBuilder#1491]
Is there any way to create a button to call Forward command for each message?

**Comment by eanders-MS** [comment]
I believe this is possible. The BotBuilder SDK doesn't directly support calling Telegram's forwardMessage, but you can still call it via the channelData field of the message activity (called sourceEvent in the Node SDK). If your "forward" button were to imBack the id of the message you wanted to forward (and you saved off that message somewhere for lookup), you can then forward it via channelData. See this issue for an example of sending a Telegram-native message via channelData: https://github.com/Microsoft/BotBuilder/issues/1299

**Comment by dimoibiehg** [comment]
As I found, It is not possible! ForwardMessage does not work such that you said.

**Comment by eanders-MS** [comment]
Which part failed? I admit I have not tried this myself, but I believe it is possible. If you'd like to continue to pursue this, I'd be happy to troubleshoot further with you.

**Comment by eanders-MS** [comment]
One thing to check: In your parameters to forwardMessage, make sure message_id is the Telegram message id, not the Bot Framework's message id. The original Telegram message can be found in channelData on the incoming activity. You'll want to get the message id from there.

**Comment by dimoibiehg** [comment]
Many thanks. The last comment (message id from channel data) might be helpful. I'll try that.

**Comment by eanders-MS** [comment]
Closing this issue now. If you're still having trouble please reopen a new issue. Thanks.
