### ISSUE TITLE
Form dialogue not ignoring thread replies via email channel

### ISSUE THREAD

**Issue by Daimwn** [Microsoft/BotBuilder#1492]
Enabled email channel for a form dialogue.
Dialogue can't handle all the text that gets passed from back and forth email replies.
Handles first response but all subsequent responses are difficult unless user deletes all the text before typing their response.
This issue would include users email signatures. Which may be a great way of getting user contact data but hard to isolate user responses for a form dialogue.

**Comment by chrimc62** [comment]
We do strip out quoted bodies, but there is no reliable way to identify the signature in an email.  If you know that you are doing interactive style things like FormFlow you can override IPostToBot to only pass on the first line with characters.  That way the response will be passed into your dialog without the signature.
