### ISSUE TITLE
When trying to display a thumbnail card i get the following message in Skype: Eek! We can’t show this card on the version of Skype you have.

### ISSUE THREAD

**Issue by masdc** [Microsoft/BotBuilder#1493]
Im trying to display a thumbnail card but Skype is unable to do it. i get the following message in skype: 
"Eek! We can’t show this card on the version of Skype you have."

 When using the emulator it gets displayed correctly.  What can be going on?

This is my code: 
`Activity replyToConversation = activity.CreateReply();                    
                        replyToConversation.Type = "message";
                        replyToConversation.Attachments = new List<Attachment>();
                        List<CardImage> cardImages = new List<CardImage>(); cardImages.Add(new CardImage(url: "https://www.davivienda.com/wps/wcm/connect/f87d7025-69fd-4931-851d-595919fd9b0b/DINERS-CLUB.png?MOD=AJPERES&CACHEID=f87d7025-69fd-4931-851d-595919fd9b0b"));                      
                        List<CardAction> cardButtons = new List<CardAction>();
                        CardAction plButton = new CardAction()
                        {
                            Value = "https://www.davivienda.com/wps/portal/personas/nuevo/personas/aqui_puedo/comprar_lo_que_deseo/tarjeta_de_credito/diners_club/diners_club/b4e62285-d4aa-43e7-ba7d-9bcdfbeda4c2/!ut/p/b1/pZbtbqM6EIavpRfQMjbGxj8JkGxIbEJs8sGfimx39wTKpmo5S-Dq16m65yhpCloVkBDiHc_DOzMWVmZtCeLIXI5tbazsZ_5r_yOv94ef-ePpOaP3tpsQGY2wmPHIBU_wsa89YU89bARbI4APDg_O49WY2yYelO_xGIFC1trayrdFelQfL8LjFR2In9nn8X6MHfNajIKACUQCGIrvze_7A_njCf5M_OsH9vDH6bv494K-ImA88P0Y9-V3h_K7Kf1L_98LevgnswH_T4LP1G8yI5-q30kwMESRle131V3ztbqDO5tSBAyAMuxSQh0zItnrAn1D1lvh0wD0C1C_4LWFe1cYswGBGkjx2mVDfZb1NwIZElBLfjlU36ytkbGP541Z2toAuVdF-zTtym5ZwHGuylrq8gCoWAlRBGuZlkjxNVJBbo9G02qm8iqrqqdcbZ9un6t4fzh4ITp-xc3NzXmBHXBtQNxxXYcgaltr_xLocoDfA3XLWHVho4uwQzpt5fMulXosVT2WMuQRCtJGBFmstUAqfEGy_rJ4WC3Tkedv23TUnQMRsCk2TBQo5owAtdZhr0emWvYVpIUuVpFIHQFFaku9Mx49Cv2gkAhxh-Zpo8JD91IkSOlooeXiDWnk_3OsJudIzCWOywnCDLCLuTFp0m-Se8UkloB6ToxJEwxBiuqyW0s9QUrmSIf1zIwOkkBAlrfwEjatrDd_TJpOp9vwomqUOi4gYhMbMDBrPe0HUilcA5LBUuiSAJRwVLtFInWIpbHoJfyBULAGMU9Ad2Er03-PSs7fgDyclPmvcyDOGGannYLYjBKzTcz6-9r3r_R1c5RaYK23R9NGjeo2qxOQqCNzQ3PQaSeDpJWdabFgHNe1fgMKbAl8eQHEXca4C47DHewwQyQuiS63PvsKUatMVvE8bVBqLEq7U2PH8uFBqmK5gN1KqNKJFDxJpZeRrP-z6FirpL2oGXGow82_jWNTzpApWmxV2eO83f9_3KpleDq_B5vuW3676y5v3s3Nb-JzYto!/dl4/d5/L2dBISEvZ0FBIS9nQSEh/",
                            Type = "Conocer más",
                            Title = "Conocer más"
                        };
                        cardButtons.Add(plButton);
                        ThumbnailCard plCard = new ThumbnailCard()
                        {
                            Title = "Tarjeta de crédito",
                            Subtitle = "Diners Club: Es la Tarjeta de Crédito exclusiva del portafolio de Davivienda que le ofrece los mejores privilegios y experiencias únicas a nivel nacional e internacional.",
                            Images = cardImages,
                            Buttons = cardButtons
                        };
                        Attachment plAttachment = plCard.ToAttachment();
                        replyToConversation.Attachments.Add(plAttachment);`

**Comment by tomlm** [comment]
Your cardAction.Type is not valid, should be "imBack" or "postBack"
