### ISSUE TITLE
3 different channels in the same conversation

### ISSUE THREAD

**Issue by ispadoto** [Microsoft/BotBuilder#1494]
I'm trying to do a MVC WebApplication for human-hybrid bots support customers, so I can't create a conversation between 3 different channels. 

Example: 

1-) An user start a chat with my bot in facebook;
2-) When the bot receive the activity, he adds a new guy in conversation (directline, that's I have conversationId). 
3-) The facebook user now, is chatting with other 2 users (bot and directline User), is the correctly logic ?

Could you help me with an example in C#, please? Or give me some direction to solve... 

Thanks! 

Iberê

**Comment by vjirovsky** [comment]
Hello ispadoto.
I don't recommend to your situation solve this way as you describe.

In case, that your bot will invite live person in conversation, will be little bit confusing for user and you will have to solve, that from "invitation moment" bot needs to terminate his activity.

I would recommend to you to create some API, that user will be behind bot. It will be much better user experience.
VJ

**Comment by ispadoto** [comment]
Hi vjirovsky ! Thanks for the advice!

But how can I do that? I need create some conversation proxy or other thing like?

Could you help me to solve, giving me a way? 

Thank you!

**Comment by ispadoto** [comment]
In my researches, I found in Microsoft MVA, this course: https://mva.microsoft.com/en-US/training-courses/react-the-definitive-beginners-guide-16547
In lesson 6, they get conversation of pizza bot using API but, I have no idea how to do. 
The source code of that bot is not available (/api/human).

**Comment by vjirovsky** [comment]
You can for example use UserData ( https://docs.botframework.com/en-us/csharp/builder/sdkreference/stateapi.html )  to save flag like "isTransferedToHuman" (when is flag set, do not reply by bot, and forward message to human). Also you need to save conversation connectionstrings (ResumptionCookie  https://docs.botframework.com/en-us/csharp/builder/sdkreference/dc/d2b/class_microsoft_1_1_bot_1_1_builder_1_1_dialogs_1_1_resumption_cookie.html ) in your database. By this cookie you can send message from other part of your application when you want.

**Comment by ispadoto** [comment]
Thanks vjirovsky! 

I will try this at night!
