### ISSUE TITLE
Node.js deployment on Azure

### ISSUE THREAD

**Issue by gcrev93** [Microsoft/BotBuilder#1496]
After deploying the bot on Azure, my html code is not found! When i test the bot it says 'Accepted" but when i run the web app via azure, i get this error: {"code":"ResourceNotFound","message":"/ does not exist"}

**Comment by willportnoy** [comment]
"/" doesn't seem like the correct path - isn't the web service url typically "/api/messages"?  In particular, the url in the web browser would be "https://yourbot.azurewebsites.net/api/messages" (though you have to POST to it, not just GET).

**Comment by Andrea-Orimoto** [comment]
@gcrev93, what do you mean by "when I run the web app via azure"? are you visiting the web app with your browser? If that's the case, the error you're seeing is expected. 
Most likely you have the following code fragment in your bot, where you tell node what uri it should listen to in server.post(). If you didn't change it from what it is in our samples, that url is '/api/messages'.
`// Create chat bot
var connector = new builder.ChatConnector({
    appId: process.env.MICROSOFT_APP_ID,
    appPassword: process.env.MICROSOFT_APP_PASSWORD
});
var bot = new builder.UniversalBot(connector);
server.post('/api/messages', connector.listen());
`

If you want to interact with the bot, you need to connect it to a channel. Try one of the following:
- use the Web channel emulator https://docs.botframework.com/en-us/tools/bot-framework-emulator/
- try the webchat control https://docs.botframework.com/en-us/support/embed-chat-control2/
- connect to a channel (e.g. Skype, go to your bot dashboard, and click on the "Add to Skype" button)

Hope this helps

**Comment by Andrea-Orimoto** [comment]
@gcrev93, I'm closing this issue, I think our answers should address your problem. Feel free to reopen if you still need help. Thanks a lot!

**Comment by pdtran3k6** [comment]
@gcrev93 
In order for you to call https://yourbot.azurewebsites.net/ like this, you have to add this piece of code into your server.js or app.js file:
`server.get(/.*/, restify.serveStatic({
	'directory': '.',
	'default': 'index.html'
}));`
and create an index.html file in the same folder of your server.js

Let me know if it helps!

**Comment by vishmonne** [comment]
@pdtran3k6  hi, even adding the code server.get , i am still facing the same issues like resource code not found.
