### ISSUE TITLE
Facebook quick replies missing

### ISSUE THREAD

**Issue by JPThorne** [Microsoft/BotBuilder#1497]
The 3.3 update says:
- Add support for keyboard card and Facebook quick replies

I see a .AddKeyboardCard() on IMessageActivity, but where are the quick replies? 

It would be helpful if releases could be accompanied by small samples showing how to use the new things. Or if the documentation could be updated at least/links to the relevant docs could be included.

**Comment by valse** [comment]
Hi,
   I attach a KeyboardCard to my reply; for example:

`reply.Attachments.Add(new KeyboardCard {
   Text = "Test",
  Buttons = new List<CardAction> {
                    new CardAction {
                        Type = "postBack",
                        Title = "Button1",
                        Value = "Value1"
                    },
                    new CardAction {
                        Type = "postBack",
                        Title = "Button1",
                        Value = "Value1"
                    }
                }
}.ToAttachment())`

**Comment by JPThorne** [comment]
Ah so that's where it is. Thanks

**Comment by slidenerd** [comment]
Does this work on node.js? [THIS ](https://docs.botframework.com/en-us/csharp/builder/sdkreference/df/d41/class_microsoft_1_1_bot_1_1_builder_1_1_connector_ex_1_1_facebook_quick_reply.html)seems pretty specific to c#
