### ISSUE TITLE
Customize hero card,Like skyscanner or hipmunk flights results

### ISSUE THREAD

**Issue by ravipulluri** [Microsoft/BotBuilder#1499]
Need hero card like skyscanner or hipmunk flights results.....
Attached is screenshot marked in Green I need....
![untitled](https://cloud.githubusercontent.com/assets/409435/19645954/f27980b8-9a14-11e6-8f56-6d65adb632e1.png)

**Comment by willportnoy** [comment]
Can you generate that green region as an image?  Does the region need to have clickable hot spots?

**Comment by ravipulluri** [comment]
So you are saying that we need to generate the images and upload them server,give that url to hero card...is that right?
hot spots not required...

**Comment by willportnoy** [comment]
@ravipulluri yes, or dynamically create them in the web service behind the ContentUrl you send as an attachment.
