### ISSUE TITLE
Issue with Web Chat component

### ISSUE THREAD

**Issue by fiamesmann** [Microsoft/BotBuilder#15]
Not sure if this is the right place to post... but here goes...

First of all the SDK is excellent, great work everyone involved.

My bot works in the emulator, but I have come across a snag when I try to embed a web chat onto my page.
As far as I can see, I have configured everything appropriately, enabled the web chat channel in the bot portal, but when I use the web chat, the bot is not responding.

[see example](https://webchat.botframework.com/embed/buttybot?s=H--TORcLaa0.cwA.xj4.NNuz4_-gkUddHS4vd0zrurjaHATwJCZ99dlcZoGTvI8)

Note this happens inside an iframe and if i navigate to the URL directly.
Looking inside fiddler I can see that I am getting a 403 forbidden from the endpoint https://webchat.botframework.com/api/conversations. (error detail: 
"Missing token or secret").

**Comment by gbdrm** [comment]
I have the same error - cannot embed bot into the site. I've tried both options: iframe with secret and with token. 503 in first case and cross-origin request in second

**Comment by fiamesmann** [comment]
Just for info... I've tried both options as well, 

I think https://webchat.botframework.com/api/conversations needs to support the CORS preflight for this to work.

**Comment by chgc** [comment]
I think the embed url that gave us is wrong. the BuildBot's embed url is using token with t=xxxxxx.
however, the embed Url is using secret (s=xxxx). and that's the reason why getting 403.

**Comment by gbdrm** [comment]
@chgc There should be 2 options how is it possible to embed chat control:
http://docs.botframework.com/connector/embed-chat-control/#navtitle
One option with secret (s=..) and another one with token (t=...)

**Comment by gbdrm** [comment]
Sample that doesn't work:
https://questbot.azurewebsites.net/

**Comment by chgc** [comment]
ok, i got it to work. the changes  I made are
1. change s=xxx => t=xxxx
2. make sure Endpoint url is using https://xxxx.xxxx

**Comment by fiamesmann** [comment]
Thanks @chgc changing s= to t= works now.

For clarity and anyone who comes across this in future, the embed needs to use 
t=<secret> and not s=<secret>.

This does contradict the documentation [here](http://docs.botframework.com/connector/embed-chat-control/#navtitle) which says the indended use of t= should be for a one time token.  E
