### ISSUE TITLE
Serialization Error when using a class in an assembly that is not marked Serializable

### ISSUE THREAD

**Issue by panuganti** [Microsoft/BotBuilder#1502]
I'm using a class from an API (Google Cloud Storage API - that's where I'd like to store some data) in a dialog. However, when I use that API, I get an exception saying that class. Google.Apis.Storage.v1.StorageService in some assembly is not marked as serializable. 
I have no way to mark that class as serializable. How do I get around this issue ?

**Comment by willportnoy** [comment]
Here are some options:
https://docs.botframework.com/en-us/technical-faq/#how-can-i-reference-non-serializable-services-from-my-c-dialogs

I'm happy to discuss further.

**Comment by willportnoy** [comment]
I'm going to close this issue, but feel free to open a new issue for further discussion.

**Comment by panuganti** [comment]
@willportnoy I've overcome this issue by moving the dependence to another http service that handles storage and making network calls to it. Thanks.
