### ISSUE TITLE
Bing Speech API integration into Bot Framework & WebChat Control

### ISSUE THREAD

**Issue by ubreddy** [Microsoft/BotBuilder#1504]
While Botframework has UniversalCallBot it works only on Skype. Bing Speech API integration can enable Speech on webChat control and possibly other channels too. Is this being planned? if not can this be included in next release?

**Comment by Andrea-Orimoto** [comment]
Hi @ubreddy , thanks for the suggestion, this has been added to our backlog, and it'll be considered for future releases. Thank you.

**Comment by mohit-jcc** [comment]
Hi @Andrea-Orimoto , please let us know what is the status on this. How can I proceed with adding this feature if it's included now. Thanks.
