### ISSUE TITLE
ERROR: ChatConnector: receive - no security token sent.

### ISSUE THREAD

**Issue by dhirajsharma072** [Microsoft/BotBuilder#1505]
I am using Node.js and my bot framework version is 3.3.3. I have already configured "Skype" channel and its working fine. However in case of "Facebook Messenger" I am getting error "No security token sent". I am using ngrok . Here is my configuration of chatBot

```
var server = restify.createServer();
server.use(restify.CORS());
server.use(restify.queryParser());
server.listen(process.env.port || process.env.PORT || 4000, function () {
    console.log('%s listening to %s', server.name, server.url);
});
// Create chat bot
var connector = new builder.ChatConnector({
    appId: _config.ms.appId,
    appPassword: _config.ms.password
});

var bot = new builder.UniversalBot(connector);

server.post('/', connector.listen());

server.get('/', function (req, res) {
if (req.query.hub.verify_token === _config.ms.messengerSecret) {
        res.write(req.query.hub.challenge);
        res.end();
    } else {
        res.send('Error, wrong validation token');
    }
});

```

I have attached screenshots of configuration of webhooks(facebook app) and messaging end point(botframwork
![botframework_message_endpoint](https://cloud.githubusercontent.com/assets/6939665/19678138/19f5cbc8-9acf-11e6-8efa-086c7ed77a72.png)
![vchat](https://cloud.githubusercontent.com/assets/6939665/19678149/22b3d430-9acf-11e6-9a4a-a7ec2c3789bb.png)

Please let me know the solution of it. Thanks!

**Comment by willportnoy** [comment]
It looks like your settings are leading the code to this "else" branch:
https://github.com/Microsoft/BotBuilder/blob/9a1d8e78b9fe1d81bd9b481d2743006a6032f7b9/Node/core/src/bots/ChatConnector.ts#L182

Does it work without ngrok?

**Comment by dhirajsharma072** [comment]
@willportnoy Thanks for  your response. When I test using bot framework it says accepted but when I try to send message with messenger I get  this "ERROR: ChatConnector: receive - no security token sent.". I am using mac os and node.js so I am not able to use emulator.

**Comment by dhirajsharma072** [comment]
@willportnoy 
I have seen [Facebook messenger document](https://developers.facebook.com/docs/messenger-platform/quickstart),there is sample app, using this app I am able to send and receive message to my page. So do I need to implement it by own?
Please let me know. Thanks!

**Comment by dhirajsharma072** [comment]
In [ChatConnector.js](https://github.com/Microsoft/BotBuilder/blob/9a1d8e78b9fe1d81bd9b481d2743006a6032f7b9/Node/core/lib/bots/ChatConnector.js) following  code  is used for fetching token. 

        var token;
        var isEmulator = req.body['channelId'] === 'emulator';
        if (req.headers && req.headers.hasOwnProperty('authorization')) {
            var auth = req.headers['authorization'].trim().split(' ');
                 if (auth.length == 2 && auth[0].toLowerCase() == 'bearer') {
                      token = auth[1];
                  }
         }
 
But I am getting req.headers look like this 

     {      
           host: 'c5dcbaa5.ngrok.io',
            accept: '*/*',
            'accept-encoding': 'deflate, gzip',
            'content-type': 'application/json',
            'x-hub-signature': 'sha1=****************86e8c84c',
            'content-length': '265',
            'x-forwarded-proto': 'https',
            'x-forwarded-for': '***. ***. ***. 136' 
}


It does not contain "**authorization**" attribute in req.headers.

**Comment by dkenzik** [comment]
I'm receiving this error with BotBuilder as well. I do not receive the issue when using BotKit. I've used a simple contrived echo example for both tests.

I'm using Ngrok for local testing. Inbound webhook URLs are exactly the same for each example. That tells me that Ngrok is likely not the issue (I don't think it strips anything out of the request by design.)

I've dumped the `req.headers` for the incoming POST with both examples. Neither of them contain an ``authorization`` header, which I find very odd.

I'm still digging into it.

**Comment by dhirajsharma072** [comment]
In case of Skype channel I'm getting req.headers look like this:

{ authorization: 'Bearer  ****.......LysN17so7Q',
  'user-agent': 'BF-Skype (Microsoft-BotFramework/3.1 +https://botframework.com/ua)',
  contextid: 'tcid=*************7312, server=********0961',
  'x-correlating-operationid': 'M2z4l1yniiM=.dAA=.********************.aDANpOAw0gE=.********=.********iL2PIYY6LSK7cD**********kzISie0=',
  'content-type': 'application/json; charset=utf-8',
  host: 'f830c68f.ngrok.io',
  'content-length': '729',
  'x-forwarded-proto': 'https',
  'x-forwarded-for': '**. **. ** .180' }

It works fine. It also has  **authorization**  attribute in req.headers.

**Comment by tomlm** [comment]
Is this issue still happening?

**Comment by dhirajsharma072** [comment]
Thanks for your response Tom! Yes,I am getting same error.

Thanks & Regards,
Dhiraj Sharma
Software Engineer

**Comment by shanepeckham** [comment]
I am also getting this error

**Comment by chrimc62** [comment]
@tomlm do you need more information to track this down?

**Comment by dandriscoll** [comment]
Hi @dhirajsharma072 and @shanepeckham, can you send a conversation ID and channel ID where you are seeing this problem and we can investigate?

**Comment by piyush-dholariya** [comment]
I am also getting same error when I post anything from postman to my bot application.

**Comment by dandriscoll** [comment]
Hi @piyush-dholariya, can you send a conversation ID and channel ID where you're seeing this problem?

**Comment by dandriscoll** [comment]
Closing due to age. Please feel free to at-mention or file a new issue and we will take a closer look.

**Comment by piyush-dholariya** [comment]
@dandriscoll  #1856  & #1903  can you give answer of these questions? I have post them separately.

**Comment by dandriscoll** [comment]
Hi @piyush-dholariya, I've taken a look but I don't know the answer to either. The people assigned to each issue are the right ones to weigh in -- I'll send them a followup email to remind them.

**Comment by picatextra** [comment]
It happened for me when setup webhook after credentials

**Comment by stujo** [comment]
Still getting this issue OSX using local bot connection and the sample code form the node.js setup

https://docs.botframework.com/en-us/node/builder/overview/#navtitle

@dandriscoll Maybe re-open?

**Comment by stujo** [comment]
I was able to fix this error by providing the APP_ID and PASSWORD in the emulator.

This may be obvious but the docs say this isn't required for local connections:

https://github.com/Microsoft/BotFramework-Emulator/wiki/Getting-Started#connect-to-a-bot-running-on-localhost

I will submit a pull request to fix the docs

**Comment by juharris** [comment]
I'm trying to set up a bot with a Microsoft Teams channel and I get `ERROR: ChatConnector: receive - no security token sent.` when a message is sent in a channel mentioning the bot but replies to individual messages do work are fine and the bot replies as expected.

Here's my app.js:
```
require('dotenv-extended').load();

var builder = require('botbuilder');
var restify = require('restify');

var server = restify.createServer();
server.listen(process.env.port || process.env.PORT || 3978, function () {
    console.log('%s listening to %s', server.name, server.url);
});

var connector = new builder.ChatConnector({
    appId: process.env.MICROSOFT_APP_ID,
    appPassword: process.env.MICROSOFT_APP_PASSWORD
});

server.post('/api/messages', connector.listen());

var bot = new builder.UniversalBot(connector, function (session) {
    session.send("Hi");
});
```

The bot does reply to the Teams channel but the message is always "Sorry, there was a problem encountered with your request"

The logs show HTML for a 401 error page. It says:
```
Most likely causes:
   The authenticated user does not have access to a resource needed to process the request.
...
Detailed Error Information:
    ...
    Requested URL	   https://MaDinnerBot:80/app.js
    Physical Path	   D:\home\site\wwwroot\app.js
...
```

Is there somewhere where I should be setting a token? I did get a token when adding the bot to Teams but I'm not sure where to put it. Thanks.

**Comment by willportnoy** [comment]
@juharris please open a top level issue for your question, and feel free to reference this closed issue.

**Comment by juharris** [comment]
@bhanu2507 are you asking me? You can see my referenced issue above. I just set up a Linux server and ngrok manually and it worked. Though my colleague made a bot last week and it worked fine doing things the automatic way with an Azure App.

**Comment by alundiak** [comment]
node `v8.8.1`, npm `v5.4.2`.

I can confirm, that using emulator I also have `ERROR: ChatConnector: receive - no security token sent.` - I typed messages but they didn't go through. And time ago all was good.

And I also solved it using APP_ID and APP_PASSWORD in emulator, as @stujo mentioned above. Which is odd, because it's not required locally.

My new dependencies:
```
"dependencies": {
  "body-parser": "^1.18.2",
  "botbuilder": "^3.12.0",
  "express": "^4.16.2",
  "restify": "^6.3.4"
}


Interesting, that a few month ago I did not have this issue. My dependencnies were:
```
  "dependencies": {
    "botbuilder": "^3.11.0",
    "restify": "^6.2.3"
  }
```


and btw, after updating to latest version, my 2 bots codebases niw have another warning in logs:
`The Bot State API is deprecated.  Please refer to https://aka.ms/I6swrh for details on how to replace with your own storage.`

**Comment by cext001** [comment]
I am also getting the same issue. This is really frustrating

**Comment by chakrihacker** [comment]
Any updates??

**Comment by AskYous** [comment]
I have the same issue as well. If I specify the app id and password in the code, it throws this error. If I take them out, it doesn't throw this error (but I get other errors).

**Comment by rkbala** [comment]
Guys, just make the appID and appPassword as null if you don't want to use the same as part of testing from emulator. (Emulator local testing does not need appid and apppassword)

//use this for testing in local and if you don't have appid and app password

var appId = null; 
var appPassword = null;

This will resolve this error. Thanks.
