### ISSUE TITLE
Web chat not showing the buttons in the herocard

### ISSUE THREAD

**Issue by somuit91** [Microsoft/BotBuilder#1507]
I am using herocard to get the user activity in callback, it is working fine in the emulator but after i publishied in the website it won't work. it simply display the content.

My code:
```
var replyMessage = context.MakeMessage();
                List<CardAction> cardButtons = new List<CardAction>();
                CardAction plButton = new CardAction()
                {
                    Value = "Reserve Book",  
                    Type = "imBack",
                    Title = "Reserve Book"
                };
                cardButtons.Add(plButton);

                HeroCard plCard = new HeroCard()
                {
                    Buttons = cardButtons
                };
                replyMessage.Attachments = new List<Attachment>();
                replyMessage.Attachments.Add(plCard.ToAttachment());
                await context.PostAsync(replyMessage);
                context.Wait(MessageReceivedAsync);
```

I have tried both imBack and postBack CardAction, it is working fine in the bot emulator but it is not working in the web chat

**Comment by eanders-MS** [comment]
Hi somuit91. The current webchat control does not support buttons. We have a new webchat control in the works that will support a wide range of rich interaction, including buttons and carousels. This new webchat control will be released sometime in late November.

**Comment by Andrea-Orimoto** [comment]
Closing this issue, since it has been answered. @somuit91 feel free to reopen it if you need more info. Thanks!
