### ISSUE TITLE
Question: Can I use same  HTTPS cert on multiple bot endpoints

### ISSUE THREAD

**Issue by afficionaddo** [Microsoft/BotBuilder#1508]
Hi,

I have purchased a HTTPS cert from Go daddy.

I wanted to ask can I use this same HTTPS cert on multiple bot endpoints??
 As all of my bots are on AWS so I was hoping if I could use the same HTTPS for multiple bots?

**Comment by willportnoy** [comment]
This doesn't really have anything to do with the Bot Framework, but in general, if your SSL certificate is for multiple domains, then you can use the same certificate for multiple bot endpoints.

(of course, you can use the same SSL for a single domain with multiple, different paths)

**Comment by chrimc62** [comment]
Question answered and closed due to lack of activity.  If you have an issue please reopen.
