### ISSUE TITLE
/deleteprofile doesn't work in Facebook

### ISSUE THREAD

**Issue by gobaldia** [Microsoft/BotBuilder#1510]
/deleteprofile doesn't work in Facebook.
I tried it with and without a space in the front.

**Comment by willportnoy** [comment]
Is this the C# or Node version of the SDK?  "/deleteprofile" is implemented in the bot builder library, not the channel.

**Comment by alokraj68** [comment]
delete the user data by using the following code.
this will delete the user state and all the conversation data.

`activity.GetStateClient().BotState.DeleteStateForUser(activity.ChannelId, activity.From.Id);`

**Comment by gobaldia** [comment]
@alokraj68 where have I to put this?

**Comment by willportnoy** [comment]
@gobaldia you can place it anywhere you have access to an Activity and you want to reset the user's data.  This won't reset the dialog stack, but in C#, we use the "/deleteprofile" and the DeleteProfileScorable for that.

**Comment by alokraj68** [comment]
@gobaldia  its very simple!. keep a variable with delete data. when to delete data is true, run this in messageController.cs the moment a message comes, check if delete is true.
