### ISSUE TITLE
Improve Localization Error Debugging

### ISSUE THREAD

**Issue by Caldas** [Microsoft/BotBuilder#1513]
When starting to work with localized dialogs I was not receiving any error that wasn't helping me to solve the issue.

Than I just realize that there was a try/catch on **FormBuilderBase** class at **Build** method that was handling **MissingManifestResourceException** exception and doing nothing with this

**Assembly**: Microsoft.Bot.Builder
**Version**: 3.2.1.0
**Code**:

``` csharp
catch (MissingManifestResourceException)
{
// Resource was not localized
}
```

**File**: FormBuilder.cs
**Line**: 139

**Comment by willportnoy** [comment]
Can you add the error?

**Comment by Caldas** [comment]
Hey @willportnoy I update the issue, the error was about other issue that I will create later

On this issue I would like to suggest to remove this catch on FormBuilder.cs since it avoid us developers to understand problems on FormDialog Localization feature

**Comment by Caldas** [comment]
to help @willportnoy I also created the [PR](https://github.com/Microsoft/BotBuilder/pull/1514) please if possible take a look
