### ISSUE TITLE
Web channel not responding

### ISSUE THREAD

**Issue by ashay-88** [Microsoft/BotBuilder#1516]
Hi,
I have a bit strange issue, no clue what is missing. 
When I communicate with BOT from emulator (locally and once deployed on Azure using ngrok) it works fine.
Then I put embedded iFrame code for webchat in default.html page, deployed on azure again. control appears on page but unfortunately I dont get any respond. 
So I created a empty website , added a form, put iframe inside that, executed locally, same issue.
It shows I sent Hi, but I dont get reply back. I havent published my bot. 
Then I thought it might be issue because of that so I have published now. it is under review.

Am I missing some step? I had similar issue in my previous bot where it worked on Skype channel but not on webchat. 

Update: I used sample bot application, deployed on azure , registered and checked if webchat works, yes it worked.  My bot has LUIS,  ditto steps, but no luck. 
Pls help.

**Comment by ashay-88** [comment]
I doubt this could be issue in my configuration, pls check this too. 
![image](https://cloud.githubusercontent.com/assets/20703721/19714243/3312db3c-9b6a-11e6-9547-58446cb9e996.png)

**Comment by jameslew** [comment]
I don't see anything in our logs that would imply any error was occurring.  Have you tried configuring Azure Application Insights for your bot and putting the instrumentation key in the bot framework?  If you do, we'll send all the events we see from your bot your app insights.

**Comment by Andrea-Orimoto** [comment]
@ashay-88 I've tried regenerating the webchat key, but it didn't work (this means the webchat now has a new key). We should be pushing an update soon that might fix this. Let's retest once the update is out and go from there. I'm assigning this to myself to follow up. Thanks.

**Comment by Andrea-Orimoto** [comment]
@ashay-88, we have a new deployment out there, are you still experiencing this issue?

**Comment by ashay-88** [comment]
@Andrea-Orimoto , no luck. 
I have removed azure app insights key. 
When you said key, do you mean web chat secret? 
it is still not working , and I wonder I am unable to see any issues being reported at botframework.com for web channel.  
Thanks

**Comment by tomlm** [comment]
looking in the logs I see messages being sent to your bot and your bot accepting them, and then I see no attempts to send a message back.

This means either your 
1. bot isn't replying
2. it is replying, but for some reason it's using the wrong serviceUrl (you should use the one that comes in the activity.serviceUrl parameter)
3. It is replying, but it has wrong credentials (if your appId as a valid appid, but your password was wrong you might see this)

At any rate, all of these point to something wrong in your bot itself.

**Comment by ashay-88** [comment]
@tomlm I have added skype as channel. I understood your points mentioned, but this works fine on Skype. My understanding is if at all there was problem with serviceUrl or it had some incorrect credentials or something was wrong in bot itself,  it would not have worked on any of the channel. it gives replies nicely on skype channel. emulator works fine too.

**Comment by ashay-88** [comment]
any update?

**Comment by chrimc62** [comment]
@tomlm or @Andrea-Orimoto is there anything we can do to help?

**Comment by danmarshall** [comment]
@ashay-88 we have a new webchat control, called the "webchat preview" - can you try using that?

**Comment by ashay-88** [comment]
@danmarshall I'll try that control and shall update here soon.

**Comment by dandriscoll** [comment]
Hi @ashay-88, is this problem still occurring for you?

**Comment by dandriscoll** [comment]
Haven't heard back, so closing issue for now. Please at-mention or open a new issue if you'd like further assistance. Thanks!
