### ISSUE TITLE
when bot send a url by bot framework , how to attachment it with html page ( by url ) ?

### ISSUE THREAD

**Issue by astrung** [Microsoft/BotBuilder#1517]
Example:
When i send a url on messenger, messenger attachment html page by url, like this : 
![example](https://cloud.githubusercontent.com/assets/9162294/19715623/a64dc59c-9b80-11e6-861e-34276b356478.png)
But when i send an url by bot framework with session.send ( url ) , it is only a text without html page.
How can i show html page with url when bot send an url ?

**Comment by astrung** [comment]
Any one can help me ?

**Comment by tomlm** [comment]
Try setting Textformat=plain

**Comment by tomlm** [comment]
Can you show sample json of your activity you are sending?

**Comment by reyesrico** [comment]
@astrung if you need the video displayed inside the you can try sending the video link as an attachment instead of as a text.

If you still have more comments, please reopen the issue. Thank you.
