### ISSUE TITLE
Hero Card works in Bot emulator but not in skype C#

### ISSUE THREAD

**Issue by alokraj68** [Microsoft/BotBuilder#1518]
Hi,
Am using the following code in order to create a hero card.
It shows up inBot framework but not in Skype.

code:

`        public async Task MessageReceived(IDialogContext context, IAwaitable<IMessageActivity> argument)
        {
            var reply = context.MakeMessage();
            reply.Text = string.Format("Select months");

            reply.Attachments = new List<Attachment>();

            string[] months = DateTimeFormatInfo.CurrentInfo.MonthNames;
            reply.AttachmentLayout = AttachmentLayoutTypes.Carousel;
            for (int i = 0; i < 12; i++)
            {
                await context.PostAsync("looping,no: " + i);
                reply.Attachments.Add(
                     new HeroCard
                     {
                         Title = months[i],
                         Images = new List<CardImage>
                        {
                                new CardImage
                                {
                                    Url = $"http://www.delhionlinegifts.com/images/36Pink_roses.jpg"
                                }
                        },
                         Tap = new CardAction { Type = "imBack", Value = months[i] },
                     }.ToAttachment()
                );
            }
            await context.PostAsync(reply);
        }`

Please let me know what is missing 👍

**Comment by jameslew** [comment]
A Skype Carousel can only have up to five cards in it, so that may be the issue.  Failing that, you might also verify that your image isn't too large.

**Comment by Andrea-Orimoto** [comment]
@alokraj68 the limit has been increased to 10 in skype. just tested and decreasing the loop to just show max 10 items worked. Any more items causes the carousel to not show on skype. Feel free to reopen the issue if you have more questions. Thanks.
