### ISSUE TITLE
Nodejs Localization : how to set up bot's locale directory (not by default)

### ISSUE THREAD

**Issue by astrung** [Microsoft/BotBuilder#1519]
My locale directory is : "./localization/en/index.js".
And i set up for bot in app.js : 
`var bot = new builder.UniversalBot(connector, {
  localizerSettings: {
    defaultLocale: "en",
    botLocalePath: "./localization"
  }
});`
But when i try to use : session.send("greeting"), it show "greeting" on message, not by "greeting" value in index.json file .
I can not understand what i wrong . Please help

**Comment by palmerabollo** [comment]
What does a `console.log(session.preferredLocale())` give you?

**Comment by astrung** [comment]
it gives : "en".
app.js is same directory with localization directory , like as : 

    /project
        dialog
            menu.js
            main.js
            ....
        localization
            en
                index.js
        app.js

**Comment by palmerabollo** [comment]
Looks good. Just in case it's not a typo, the file must be called "index.json" (not .js).

**Comment by astrung** [comment]
I changed to json file, but still same error

**Comment by astrung** [comment]
i have a bug when change js file to json file. It is fine now. I can send message with locale by `session.send` , but can not send message with card . I created new issue for it : [new issue with card and localization](https://github.com/Microsoft/BotBuilder/issues/1538)
