### ISSUE TITLE
Using the Bot Emulator while developing in a Linux VM

### ISSUE THREAD

**Issue by TibboddiT** [Microsoft/BotBuilder#1521]
Here is my setup:
- Windows 7 as host
- A Linux install in a VirtualBox VM
- Some NAT settings to allow the emulator to talk to the bot running in the VM, e.g. host:3978 -> guest:3978
- Port forwarding in Windows to allow the bot to talk to the emulator: `netsh interface portproxy add v4tov4 listenport=9000 connectaddress=localhost connectport=9000`. 

But there is a problem: the emulator is responding with a depressing 400 status when the bot try to talk to it, because of the invalid hostname.

Is it possible to tell the emulator to accept requests from others interfaces than the loopback one? (i mean from hosts like '192.168._._')

Also, I'm working behind a proxy,  and even if I use addresses like localhost:9000, the emulator returns an error 407. Does the emulator has to access internet in some way, or is it a conception flaw ?  (I can join the bot from the host with curl or other tools with the proxy enabled)

Please notice that the first question is not related to that proxy thing, as i run into the invalid hostname when the proxy is disabled.

Thanks !

**Comment by tomlm** [comment]
I recommend you use ngrok (http://ngrok.io) to create publically addressable mappings for both sides and everything should work just fine.
