### ISSUE TITLE
ERROR: ChatConnector: receive - invalid signing key or OpenId metadata document.

### ISSUE THREAD

**Issue by cnrudd** [Microsoft/BotBuilder#1522]
Hi,

this morning when I send a msg from the Channel Emulator (3.0.0.59) to my bot running on localhost:3978/   I get this error msg:

ERROR: ChatConnector: receive - invalid signing key or OpenId metadata document.

This is the first time I see this.  Worked fine yesterday and in the previous weeks.  

Any idea what causes this?

What could have changed a signing key or OpenId metadata doc?   I have not been working in either of these domains: signing key, metadata docs...

Thanks!

**Comment by Andrea-Orimoto** [comment]
@cnrudd are you implementing an auth library by any chance? https://docs.botframework.com/en-us/restapi/authentication/#enabling-authentication-from-the-bot-framework-emulator

**Comment by cnrudd** [comment]
Hi thanks for the reply.   
I am not implementing an auth lib.

I determined last night that the issue was caused by VirtualBox 5.0.28 r111378.  I had upgraded to this version of VB from VirtualBox 5.0.26 r108824.   It looks like the 5.0.28 version has some networking bugs.

If anyone else has this issue, what solved it for me was changing VB 5.0.28 r111378's networking setting from NAT to Bridged.
