### ISSUE TITLE
Few  questions around ChoiceStyle and HTML support

### ISSUE THREAD

**Issue by dhirajgupta1** [Microsoft/BotBuilder#1523]
I have few queries around Microsoft bot .Net framework
1) Is it possible to set ChoiceStyle on the basis of channel (i want it PerLine for web chat and buttons for Skype and messenger)
2) I want to render numbers with choices on buttons, how to achieve it? (Like 1.Choice1 , 2. Choice2)
3) Is it possible to return a link or HTML in ValidateResult in form flow(I used FeedbackCard and able to return an image)
4) When i have multiple choices Skype render them in 2 columns carousal, is there any way to change the default rendering? I want to render them in a single column.
5) Is it possible to return HTML to channels on form completion?
6) Pdf attachment  is not working in web chat any suggestions? 

Thanks,
Dhiraj

**Comment by tomlm** [comment]
4. No, it is not supported
5. No, but you can send a link to a html web page
6. I think we are fixing that in next release of web chat

**Comment by chrimc62** [comment]
@willportnoy or @msft-shahins can you comment on 1-3?

**Comment by willportnoy** [comment]
Regarding number 3, I don't think FormFlow's ValidateResult allows complete flexibility in the feedback message.  It's possible that markdown might work.

**Comment by msft-shahins** [comment]
Here are answers to questions that are not covered yet: 

1. you can look at the channelId of the incoming activity and set the ChoiceStyle based on the channel when you create the prompt dialog. 
2. you can implement your custom prompt styler that implements its custom [Apply](https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Dialogs/PromptDialog.cs#L227) function to generate the buttons with the appropriate title.

**Comment by dhirajgupta1** [comment]
Thanks Everyone for your valuable response!!

@msft-shahins , For first point I am using Prompt attribute, is it possible with attribute too?

Thanks,
Dhiraj

**Comment by willportnoy** [comment]
@dhirajgupta1 I don't think FormFlow's prompt attribute has the same options for channel-specific overloads but @chrimc62 @msft-shahins correct me if I'm wrong.
