### ISSUE TITLE
Is there an example showing how to use LUIS actions, prompting the user for more information?

### ISSUE THREAD

**Issue by andradedearthur** [Microsoft/BotBuilder#1524]
I'm using a `LuisDialog`, and I would like to know if there's an example showing how to use the `LuisResult`to detect the actions, parameters and prompt the user for the missing parameters. I know the `LuisResult`already contains the actions and parameters, however I don't know what is the best way to prompt the user, or how to send that information back to LUIS using the `contextId`.

**Comment by tomlm** [comment]
The answer to this is so domain specific that I don't know if you can give a precise answer.

Basically it is an intersection of 
* what you know
* what you need
And binding that to an expression that gets what you want.
