### ISSUE TITLE
Form Flow Numeric attribute not working C#

### ISSUE THREAD

**Issue by alokraj68** [Microsoft/BotBuilder#1526]
Hi,

Am using the following code. the bug is that even if enter a numeric over the limits, it don't take it as an error. rather Numeric takes in strings as inputs. 

Code:

`[Serializable]
    public class Ask
    {
        [Numeric(1, 31)]
        [Prompt("Please enter Date (1-31)")]
        public string DateOfBirth { get; set; }
    }`

is there anything more I should do than this?

**Comment by Andrea-Orimoto** [comment]
try this
` [Serializable]
    public class Ask
    {
       [Numeric(1, 31)]
        [Prompt("Please enter Date (1-31)")]
        public int DateOfBirth;
    }`
      
your property is of type string. also, remove { get; set; }. Closing this issue, please reopen it if needed.
thanks!
