### ISSUE TITLE
Sending a reply starting with the sequence "0. " followed by any character will crash the bot framework channel emulator.

### ISSUE THREAD

**Issue by mikeschat** [Microsoft/BotBuilder#1528]
Bot framework channel emulator version: 3.0.0.59

Sending any reply starting with the sequence "0. c" or any other character, or sequence of characters will result in an error, with the stack trace that is at the bottom of this post being printed in the chat window as the bot response.
The "text property" in the JSON string on the right side of the emulator shows the message just fine, indicating that the JSON string was indeed correctly recieved by the emulator. This is why i suspect that there is a problem with the parser that composes the response chat messages.

some examples in c# below:

```
Activity reply = activity.CreateReply("0. c test 123");
await connector.Conversations.ReplyToActivityAsync(reply);
```

Results in an error being thrown.

```
Activity reply = activity.CreateReply("random text 0. c test 123");
await connector.Conversations.ReplyToActivityAsync(reply);
```

Works just fine.

Stack trace:

System.Windows.Markup.XamlParseException: 'Set property 'System.Windows.Documents.List.StartIndex' threw an exception.' Line number '3' and line position '29'. ---> System.ArgumentException: '0' is not a valid value for property 'StartIndex'. at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal) at System.Windows.Baml2006.WpfMemberInvoker.SetValue(Object instance, Object value) at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(XamlMember member, Object obj, Object value) at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(Object inst, XamlMember property, Object value) --- End of inner exception stack trace --- at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri) at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, Boolean skipJournaledProperties, Uri baseUri) at System.Windows.Markup.XamlReader.Load(XamlReader xamlReader, ParserContext parserContext) at System.Windows.Markup.XamlReader.Load(XmlReader reader, ParserContext parserContext, XamlParseMode parseMode) at System.Windows.Markup.XamlReader.Load(XmlReader reader) at Microsoft.Bot.Framework.Emulator.Message2XamlConverter.Convert(Object value, Type targetType, Object parameter, CultureInfo culture)

**Comment by jameslew** [comment]
Thanks; we're working on updated to the Bot Framework Emulator and I'll add that to the issues list to look at.

**Comment by tomlm** [comment]
Yeah, we are rebuilding it, but if you want a workaround the problem is that it is interpreting the text as markdown for a numbered list. 

You can change TextFormat=plain to disable markdown
You can put a space at the beginning of the line to disable the detection of the ordered list promotion.
You can start with 1. instead of 0.
