### ISSUE TITLE
[.Net] LuisDialog does not fire an exception if subscription key is invalid 

### ISSUE THREAD

**Issue by ghostinside** [Microsoft/BotBuilder#153]
[LuisModel("model id", "invalid subscription id")]
    [Serializable]
    public class SimpleLuisDialog : LuisDialog<SimpleLuisDialog>

even default intense will not be fired, as a result you will recieve an empty responce message, think the Luis service has to fire an exception

**Comment by willportnoy** [comment]
I can't reproduce this issue - when I used an invalid subscription ID, I get an HttpRequestException with "access denied", and this is propagated to the caller of the luis dialog.

**Comment by ghostinside** [comment]
try to add in LUIS web your azure subscription key(guid with -) and put it as a  subscription key in Luis model. I did it this way, just later i figured out that in exaples we have subscription key without "-", then looked in LUIS web and found that LUIS generated for me another subscription key, probably based on my Azure subscription key

**Comment by msft-shahins** [comment]
[commit aa6487](https://github.com/Microsoft/BotBuilder/commit/aa6487aec293256c371e1fca71411e7e77e38e9d) should propagate the exception that is happening in the Luis service http call up to the user and you should be able to see the internal server error rather than empty message in the reply.
