### ISSUE TITLE
[Known Issue] Why does BotBuilder.Prompts.number method parse like this?

### ISSUE THREAD

**Issue by jorge-sanz** [Microsoft/BotBuilder#1530]
I am using `BotBuilder.Prompts.number` method. 

What is the purpose of parsing like this (check bellow) and not reject it and consider it like something that is not a real number? 
Input: `v66v6` -> Parsed answer: `66`

**Comment by msft-shahins** [comment]
based on the syntax I assume that this is a node.js bug. Can you confirm this?

**Comment by Stevenic** [comment]
The RegEx we're using doesn't look to be strict enough. I'll try to improve it.

**Comment by chrimc62** [comment]
@Stevenic or @maxpert did 3.5 fix this?

**Comment by Stevenic** [comment]
It's not in 3.5. I'll have to work on it for 3.6

**Comment by nwhitmont** [comment]
[Bugfix] PR: https://github.com/Microsoft/BotBuilder/pull/2553

**Comment by stevengum97** [comment]
Enhancements for number parser still needed, reopening issue.

**Comment by nwhitmont** [comment]
@Stevenic Any updates on the number recognizer fix?

**Comment by nwhitmont** [comment]
relates to Intercom#15644

**Comment by nwhitmont** [comment]
Currently, this is expected behavior.
