### ISSUE TITLE
Using Bot Framework as a Platform

### ISSUE THREAD

**Issue by coolace** [Microsoft/BotBuilder#1531]
Hi,
Is it compliant with the terms of use, especially in regard to "Section 4 - Use Restrictions", to use the Bot Framework (and Connector Service) as a Bot Platform where users can create their own bots that essentially all run on the same Bot Builder Project?
Thanks,
Maro

**Comment by jameslew** [comment]
We didn't write them to specifically prevent one developer providing multiple bots for their customers regardless of hosting model, but I'd probably need to understand more.  

Can you describe your model with any more detail? Do all of your users have bot framework accounts and bot registrations, and their bots just run on your service each with their own endpoint/auth keys?

**Comment by coolace** [comment]
Hey jameslew, thanks for the quick answer. We are planning to develop a platform where people can register their facebook pages and create bots via a custom CMS (somehow similar to chatfuel for example). These bots all run on the same project (which we would like to build on top of MS Bot Framework). So our users wouldn't register bot framework accounts and/or bot registrations, they would essentially all run on our endpoint.

**Comment by tomlm** [comment]
We have work to do to enable this.  We have taken steps in this direction (new SDK will allow you to have multiple bot credentials associated with a single endpoint) but we have more work to do primarily around enabling the programmatic defining of channel configurations.

**Comment by lonche** [comment]
Hey. Any news about this ?

**Comment by cesarvarela** [comment]
I'm interested in knowing the status of this too.

**Comment by DL-LiveTiles** [comment]
Same here, we need an API to programmatically register a bot in the bot framework portal.

**Comment by DL-LiveTiles** [comment]
Is this feature logged somewhere so that we can follow progress or vote for it?
Same question here: https://stackoverflow.com/questions/42172304/is-it-possible-to-register-provision-a-bot-via-service/44125048#44125048

**Comment by lonche** [comment]
How to vote for that feature ? Should i mark that as favourite ?

**Comment by rysbilinski** [comment]
We also require the ability to register bots programmatically and configure their associated channels. Happy to go manual for the time being, however really need an expected timeline
