### ISSUE TITLE
[C#] FormFlow Validation sends empty message

### ISSUE THREAD

**Issue by ankitbko** [Microsoft/BotBuilder#1534]
In FormFlow ValidateAsyncDelegate, if the `ValidateResult.IsValid` is set to true and `Feedback` is set to `String.Empty`, the bot sends an empty message to user. Is this a feature or a bug?
To not send any message I have to set `Feedback` to `null`.

**Comment by willportnoy** [comment]
It seems like you can get reasonable behavior by using "null" as "don't send a message".  @chrimc62 seem reasonable?

**Comment by chrimc62** [comment]
This is by design.
