### ISSUE TITLE
Node.js SDK Documentation "bugs"

### ISSUE THREAD

**Issue by michhar** [Microsoft/BotBuilder#1537]
I tried to find the docs to do a pull request so if you could point me there I'd be happy to do so.  Otherwise, two problems in the Bot Builder for Node.js Documentation on Debug Locally with VSCode [here](https://docs.botframework.com/en-us/node/builder/guides/debug-locally-with-vscode/).  1) TextBot ([this](https://docs.botframework.com/en-us/node/builder/chat-reference/classes/_botbuilder_d_.textbot.html)) class is deprecated and 2) TodoBot link ([this](https://github.com/Microsoft/BotBuilder/tree/master/Node/examples/todoBot)) appears broken.  Not sure if the instructions are the same for issue (1) when using the ConsoleConnector class.  Thanks in advance.   -Micheleen

**Comment by Andrea-Orimoto** [comment]
@michhar thanks a lot for reporting this, we already have a bug in our backlog for this. If you want to submit a PR just fork the repo and follow these instructions https://help.github.com/articles/creating-a-pull-request-from-a-fork/. Thanks a lot!
