### ISSUE TITLE
Nodejs Localization: send a card with locale message

### ISSUE THREAD

**Issue by astrung** [Microsoft/BotBuilder#1538]
Localization works when i send a message, but it doesn't work when i send a card .

Examples:

my index.json file : 

    {
      "hello": "Good morning!"
    }

 and my bot :
 
    var card = new builder.HeroCard();
    card.title("hello");
    var msg = new builder.Message(session).attachments([card]);
    session.send(msg);
    session.send("hello");

It show on channel emulator : 
![Card error](https://cloud.githubusercontent.com/assets/9162294/19794064/d6a2d73a-9cf9-11e6-8e78-710e8c0bcc8b.png)

So how can i use localization with card text ?

**Comment by Andrea-Orimoto** [comment]
@astrung try using session.localizer.gettext().
https://docs.botframework.com/en-us/node/builder/chat/localization/#localizing-prompts
https://docs.botframework.com/en-us/node/builder/chat-reference/interfaces/_botbuilder_d_.ilocalizer#gettext

**Comment by Stevenic** [comment]
You should pass in the session object to the HeroCard. So:

```
var card = new builder.HeroCard(session);
card.title("hello");
var msg = new builder.Message(session).attachments([card]);
session.send(msg);
session.send("hello");
```

At some point we're going to try to remove that requirement but it's a fairly significant change to do so.
