### ISSUE TITLE
Email Channel doesn't work

### ISSUE THREAD

**Issue by kienct89** [Microsoft/BotBuilder#1539]
Microsoft App ID: 0f950627-b77b-458b-ba2f-37fd0220bfcc

The email channel was working properly for the last few weeks, and it stopped working since yesterday.
I tested with other channel (Skype, Telegram, SMS) and all of them are working.
How should I get it fixed?

Thanks.

**Comment by craigjensen** [comment]
I'm seeing a bunch of posts to your bot that are returning 500 errors.  Did anything change on your end?

**Comment by kienct89** [comment]
@craigjensen I didn't change anything in my back-end code, and it was working with all other channels.

I tried to disable and re-enabled the email channel, but it still doesn't work.

Is there anyway I can find out what the exception is?
Thanks.

**Comment by tomlm** [comment]
Looking in the dev portal (see the RED number next to the Email channel?  If you click on it shows 20 most recent errors)
I see:
‎10‎/‎30‎/‎2016‎ ‎10‎:‎37‎:‎11‎ ‎PM
POST to ms_ops_bot failed: POST to the bot's endpoint failed with HTTP status 500

When I look in the logs for the last 24 hours I see a bunch of success, so I will assume you have figured out your issue.  Please reopen if it is still happening
