### ISSUE TITLE
Bot template for Xamarin Studio

### ISSUE THREAD

**Issue by rlingineni** [Microsoft/BotBuilder#154]
I know that there is a sample VSTemplate for Visual Studio, would like to know if there was a template/addin we could have for Xamarin Studio on OSX?

**Comment by chrimc62** [comment]
We will look into this, thanks for the suggestion.

**Comment by Stevenic** [comment]
Moved to UserVoice to enable voting:

https://feedback.botframework.com/forums/354213-general/suggestions/13626936-bot-template-for-xamarin-studio
