### ISSUE TITLE
Push bot automaticaly to user

### ISSUE THREAD

**Issue by alokraj68** [Microsoft/BotBuilder#1541]
Is there any way to push the bot to message the user o a particular time of the day?

so that bot sends hi to the user. or any internal clock?

**Comment by cejixo3** [comment]
Yes, you can use createDialog method

**Comment by alokraj68** [comment]
Where should i use that?! and how to schedule bot to do it?

**Comment by cejixo3** [comment]
This is method of botbuilder instance. You could use It any where. For scheduling you could use some of external npm modules. I can provide example of call when I will be at home :)

**Comment by cejixo3** [comment]
for example

bot.beginDialog({
    channelId: 'skype',
    user: {
        id: <skype user id>
    },
    bot: {
        id: <id of your bot>
    },
    conversation: {
        id: <conversation id>
    },
    serviceUrl: 'https://skype.botframework.com',
    useAuth: true
}, '/notify/new_build', data);

**Comment by alokraj68** [comment]
Thats cool. Am working with c# , know the code in that?

**Comment by cejixo3** [comment]
No. But as I know it will be simmular to nodejs sdk.

**Comment by alokraj68** [comment]
Yea!. am waiting for someone to answer the method to schedule in c# sdk

**Comment by kienct89** [comment]
@alokraj68 is this what you're looking for? (http://stackoverflow.com/questions/38431234/how-to-schedule-tasks-in-microsoft-bot-framework-c/)

**Comment by alokraj68** [comment]
Let me see if that works @kienct89

**Comment by palmerabollo** [comment]
@cejixo3 what if the conversation has already finished? (ex. the `token` is no longer valid).

**Comment by cejixo3** [comment]
In nodejs for dialog initiation we need only transport, skype Id, and service url. We do not keep any tokens by hand. But I think you told about session token between not and skype services, right?

**Comment by alokraj68** [comment]
I have not yet used a token in C#. my bot is currently working well, but i got no idea how to make this auto push to an user on a predefined time, if he is subscribed to notifications.

**Comment by valse** [comment]
Hi,
  I use an external windows service to push updates to my subscribed users.

You need to initialize a new IMessageActivity like:
```c#
Activity.CreateMessageActivity();
```

and then fill these fields:
- From
- Recipient
- Conversation
- Text (or what you need)

To check the unsubscribed users I parse the response after sent the push:
```c#
var res = await connector.Conversations.SendToConversationAsync((Activity)message);
```
If I had an error I remove the user from my push list.

If you use the Facebook Messenger channel you could also specify the push notification type to _REGULAR_ so the user will receive the notification to his smartphone notification hub too.
```c#
message.ChannelData = JObject.FromObject(new {
  notification_type = "REGULAR"
});
```

**Comment by alokraj68** [comment]
Hi @valse ,
I have been trying to use hangfire for the purpose, but could not configure it until now.
can you help me out? 

http://stackoverflow.com/questions/38431234/how-to-schedule-tasks-in-microsoft-bot-framework-c/38435130?noredirect=1#comment68043314_38435130

Which tool are you using?

**Comment by valse** [comment]
I'm using [Quartz.NET](http://www.quartz-scheduler.net/) for scheduling a process that retrieve info from a sql server db and do the job... but I think that use [hangfire](http://hangfire.io/) is a better choice 😉

**Comment by alokraj68** [comment]
@valse why do you think so? am having trouble with hangfire as my MySQL server is not in azure.

**Comment by alokraj68** [comment]
@valse quartz works with mysql?  Hangfire does not. Am looking for somthing with mysql support.

**Comment by chrimc62** [comment]
Closing due to age, change of topic and lack of activity.  Please reopen if you still have a bot framework issue.

**Comment by alokraj68** [comment]
Can someone provide a working code on how to use azure cron job or any other service for the same in c#

**Comment by alokraj68** [comment]
@chrimc62 Please provides help before closing this.
