### ISSUE TITLE
[NODE] TS: Backwards compatibility broken in 3.4.0

### ISSUE THREAD

**Issue by jmendiara** [Microsoft/BotBuilder#1543]
In https://github.com/Microsoft/BotBuilder/commit/73c815bb4ca91b783866adca1ce40dfa73ced840#diff-6c2ced06d82a56ab98a8ce59d2d1e27bR1773 the definition for the library name changed to `namespace` 

But in the code you still refer to `name`  https://github.com/Microsoft/BotBuilder/blob/master/Node/core/src/bots/Library.ts#L53

CC @Stevenic

**Comment by jmendiara** [comment]
Related #911

**Comment by Stevenic** [comment]
That was actually just a typo in the botbuilder.d.ts. I didn't mean to change that property. I was trying to make some argument names more consistent and got a little overly aggressive. I've fixed the .d.ts file in v3.4.2.  As for following semver I'm trying to avoid truly breaking changes.

**Comment by jmendiara** [comment]
Thanks @Stevenic !
