### ISSUE TITLE
Unit testing dialogs

### ISSUE THREAD

**Issue by fricke** [Microsoft/BotBuilder#1547]
Hello,

I'm in the process of unit testing our dialogs and was looking for some advice.  I've reviewed the tests that are part of this repository and I was hoping to do something similar with or dialogs, but am running into issues.  

In our current setup, we have implemented a bot.dialog('/', ...) and some setup code happens there for our users.  The tests in botbuilder specifically uses this to start a conversation and go through a flow to test the functionality of the botbuilder itself, but not necessarily the handler/waterfall functions.  If I issue a command it's going to start in my '/' dialog, but I really need a way of triggering any dialog I want from outside of dialog (no access to session.beginDialog obviously before a flow starts).  Right now, it looks like I can only start a conversation, but is there a way to start that conversation to go into a specific dialog?  This might be a very n00b question, but I'm not having much luck here.  Further, I really only want to test that things happen in my dialogs, like session.replaceDialog is called but not executed, so I'll need to stub out those calls.  I'm just hitting a brick wall when trying to start the flow and I'm hoping to get some help here on that (if it's even possible).  

Would be nice to maybe have new builder.TestBot(connector) where you can setup some mappings for tests.  

Since I haven't been able to get the aforementioned setup that I'd like, I've went the route of just mocking the entire bot.dialog functionality.  So, I just override bot.dialog with my own function and mock up a session (w/ all the necessary methods).  Downside of this is that it really takes the bot functionality out of the equation, but maybe that's ok.  

Any advice would be very appreciated!

Chris

**Comment by Stevenic** [comment]
So to start with we should probably put some more thought into unit testing individual dialogs.  To answer at least part of your question you can actually start from an arbitrary dialog if you call `bot.beginDialog(address, '/myDialog');`  If you're using the `ConsoleConnector` the address should be:

```
{
                    channelId: 'console',
                    user: { id: 'user', name: 'User1' },
                    bot: { id: 'bot', name: 'Bot' },
                    conversation: { id: 'Convo1' }
                }
```

The `TestBot` or something similar isn't a bad idea. We're working on v3.5 right now and we're pretty booked work wise for that release but this might be a candidate for v3.6.

**Comment by fricke** [comment]
Great, thanks for the quick reply!  Let me know if you need a tester when you guys get to it, would be happy to help out!

**Comment by Stevenic** [comment]
Closing this issue for now.

**Comment by matts310** [comment]
@fricke I know I may be late to the party, but I found that setting up tests for dialogs a pain too. I made a testing framework that easily tests bot dialogs and state. E.g.
``` javascript
    it('Can simulate conversation', () => {
        bot.dialog('/', [(session) => {
            new builder.Prompts.text(session, 'Hi there! Tell me something you like')
        }, (session, results) => {
            session.send(`${results.response} is pretty cool.`);
            new builder.Prompts.text(session, 'Why do you like it?');
        }, (session) => session.send('Interesting. Well, that\'s all I have for now')]);


        const {
            executeDialogTest,
            SendMessageToBotDialogStep,
        } = testSuiteBuilder(bot);
        
        return executeDialogTest([
            new SendMessageToBotDialogStep('Hola!', 'Hi there! Tell me something you like'),
            new SendMessageToBotDialogStep('The sky', ['The sky is pretty cool.', 'Why do you like it?']),
            new SendMessageToBotDialogStep('It\'s blue', 'Interesting. Well, that\'s all I have for now')
        ])
    })
```

check it out! [github.com/matts310/BotTester](github.com/matts310/BotTeste)
