### ISSUE TITLE
Alternatives to channel language translation?

### ISSUE THREAD

**Issue by dzrhythm** [Microsoft/BotBuilder#1548]
Automatic language translation was a nice feature (even imperfect translations can be preferable to costly full i18n/l10n effort, at least initially). Since it was dropped in v3, what is the current guidance on language translation?

A reply to [issue 1156](https://github.com/Microsoft/BotBuilder/issues/1156) mentions doing translation from within the bot. Is there a hook that can be leveraged to translate every incoming and outgoing message from dialogs (especially LuisDialogs) and form flows?

Some documented guidance/examples in this area would be helpful.

Thanks.

**Comment by Andrea-Orimoto** [comment]
@dzrhythm does this help?
https://docs.botframework.com/en-us/csharp/builder/sdkreference/forms.html#localizingSection

**Comment by Stevenic** [comment]
You'll want to create a piece of middleware that does the translation. Unfortunately we don't have any code examples of this yet.

**Comment by tomlm** [comment]
It's pretty easy to do without middleware as well.

http://docs.microsofttranslator.com/ 

When you receive a message, translate the message (I usually add originalText and originalLanguage as properties).

When you send a reply, create helper and use the originalLanguage to translate the reply before you send it out.
