### ISSUE TITLE
Chaining IFormDialog

### ISSUE THREAD

**Issue by dparra0007** [Microsoft/BotBuilder#155]
HI,

Using C# SDK, I'm trying without success to chain different IFormDialogs to the first one:

Chain.From(() => FormDialog.FromForm(FlightOrder.BuildForm))

I have tried with several fluent methods from Microsoft.Bot.Builder.Dialogs.Chain but I have not get a correct implementatino yet. Neither with Select, neiher, SelectMany, neither ContinueWith, ...

Anybody can share how to Chain IDialogs, and specially IFormDialogs?

Thanks,

**Comment by willportnoy** [comment]
Can you give more details?  I suspect you want to pass FormOptions.PromptInStart, if you're not seeing the dialog initiate the conversation.

**Comment by willportnoy** [comment]
I'm going to close this item for now, but feel free to reopen with more information.
