### ISSUE TITLE
ScorableBase<IActivity, Tuple<string, string>, double> layer cannot trigger LuisDialog Methods anymore

### ISSUE THREAD

**Issue by kevinport** [Microsoft/BotBuilder#1550]
My bots are based on the AlarmBot Example, since the change of 
AlarmScorable from 
`Scorable<double>`
 to 
`ScorableBase<IActivity, Tuple<string, string>, double>` 
the method 
`public override async Task PostAsync(IActivity item, Tuple<string, string> verbTitle, CancellationToken token)` 
did not allow verbs which are also defined as an intent in the LuisDialog.

For Example:

I've got an Card with 3 Buttons one button should trigger an LuisIntent im my LuisDialog

> button-ChangeProperty-A
> 
> this pattern is defined in my LuisModel, but now the Luis Method isnt triggered anymore.

**Comment by willportnoy** [comment]
The change to ScorableBase should have just introduced more static type checking.

I'm having trouble understand your question.  The current implementation of PostAsync uses the "state" object from IScorable to dispatch to a regular C# method, which just happens to be the method used for processing a LuisIntent:
https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Samples/AlarmBot/Models/AlarmScorable.cs#L121

**Comment by kevinport** [comment]
ok, its hard to explain.......

i will split up the problem...

**Comment by kevinport** [comment]
First question:

how can i start a new FormFlow from a herocard button, based on the alarmbot sample?

**Comment by willportnoy** [comment]
https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Tests/Microsoft.Bot.Builder.Tests/ScorablesTests.cs#L273 is an example of starting a dialog based on a scorable - you can similar use the scorable to listen for the activity corresponding to the button's press.

**Comment by kevinport** [comment]
I need to reopen the issue.... I tested your suggestion but there is no example with a FormFlow..

and if i rewrite the code for a FormFlow only the first field is asked.. For Example

> What kind of pizza do you want? 

if i enter the answer my sourrounding dialog catches the answer and my new created dialog ends

**Comment by willportnoy** [comment]
To be clear, I assume the interrupting child dialog is a FormFlow?  Are you passing an initial state that's filled in?  The "void" chain method will swallow the result of the child dialog, and then restart the wait for the next user message to be sent to the interrupted dialog.

**Comment by kevinport** [comment]
Yes my subdialog is an dialog with an FormFlow.
Here my code:

`    case Verbs.MyTestAction:
          var message = (IMessageActivity)item;
          using (var scope = DialogModule.BeginLifetimeScope(Global.FindContainer(), message))
          {
            // find the bot data interface and load up the conversation dialog state
            var botData = scope.Resolve<IBotData>();
            await botData.LoadAsync(token);

            // resolve the dialog stack
            var stack = scope.Resolve<IDialogStack>();
            // make a dialog to push on the top of the stack
            var child = scope.Resolve<MyTestDialog>();
            // wrap it with an additional dialog that will restart the wait for
            // messages from the user once the child dialog has finished
            var interruption = child.Void<object, IMessageActivity>();

            try
            {
              // put the interrupting dialog on the stack
              stack.Call(interruption, null);
              // start running the interrupting dialog
              await stack.PollAsync(token);
            }
            finally
            {
              // save out the conversation dialog state
              await botData.FlushAsync(token);
            }
          }
          break;`

**Comment by willportnoy** [comment]
What is the lifetime of MyTestDialog?  Is InstancePerDependency so that you get a fresh copy of the state each time?

**Comment by kevinport** [comment]
The dialog should only start if the user clicked a special herocard button... after the user finishes the MyTestDialog the sourrounding dialog should continue...

In my Module i got this code:
`builder.Register((c, p) => new MyTestDialog()).AsSelf().InstancePerDependency();`

So it should be a fresh copy..

**Comment by willportnoy** [comment]
I presume MyTestDialog is still a FormFlow dialog?  What does MyTestDialog look like?

**Comment by kevinport** [comment]
Yes it's still a FormFlow...

[Serializable]
public sealed class MyTestDialog : LuisDialog<object>
  {
    public static TravelOrder order { get; set; }
    public override async Task StartAsync(IDialogContext context)
    {
      var pizzaForm = new FormDialog<TravelOrder>(order, BuildForm, FormOptions.PromptInStart | FormOptions.PromptFieldsWithValues, new List<EntityRecommendation>());
      context.Call<TravelOrder>(pizzaForm, FormComplete);
    }
    private static IForm<TravelOrder> BuildForm()
    {
      var builder = new FormBuilder<TravelOrder>();
      return builder
          .Field("hotel.WithBreaktfast")
          .Field("hotel.RoomCount")
          .Build();
    }
    private async Task FormComplete(IDialogContext context, IAwaitable<TravelOrder> result)
    {
      context.Wait(MessageReceived);
    }
  }

**Comment by chrimc62** [comment]
@willportnoy can you comment or close as appropriate?

**Comment by willportnoy** [comment]
@chrimc62 kevinport's issue is that "i rewrite the code for a FormFlow only the first field is asked".

Kevin, it seems likely your issue is caused by using a static TravelOrder as your initial state, and it's already been filled in by some previous call to the FormFlow dialog.

**Comment by kevinport** [comment]
Yes it is already filled, therefore i used the FormOptions.PromptFieldsWithValues option. (The bug i submitted some weeks ago)

I will test it with an non static field..

**Comment by kevinport** [comment]
Even with an non static field it doesnt work..

**Comment by kevinport** [comment]
![github error](https://cloud.githubusercontent.com/assets/20930799/20649259/73483ae8-b4bb-11e6-8a56-26a2243d86ae.PNG)

As you can see, after the first question the new Dialog exits and the surrounding want to catch my answer...

**Comment by chrimc62** [comment]
Sorry for the delay in responding.  I am unable to reproduce your issue.  Whatever value your initial state has, you will still get prompted with the default value if FormOptions.PromptFieldsWithValues is passed in.  It also works if you pass in LUIS entities and that flag.  I've got tests for multiple values, ambiguous values, numeric, where validation fails and others and they all work fine.  Could you possibly share your whole bot?

**Comment by chrimc62** [comment]
Here also is an example where a FormDialog is launched from a LUIS intent. https://github.com/Microsoft/BotBuilder-Samples/blob/master/CSharp/intelligence-LUIS/Dialogs/RootLuisDialog.cs

**Comment by chrimc62** [comment]
If your issue is still not solved, please reopen.
