### ISSUE TITLE
Cannot update bot details

### ISSUE THREAD

**Issue by josephktcheung** [Microsoft/BotBuilder#1552]
Hi,

I tried to update bot's messaging end point this morning but the page failed to save changes and prompted "Please correct the errors and try again."

I looked into the network request and I saw the failed PUT request to `BotManager?forPublishing=false` with error response `{"Errors":[{"Field":"Id","Message":"Bot ID has invalid characters"}]}`

<img width="1276" alt="screen shot 2016-10-31 at 11 16 19 am" src="https://cloud.githubusercontent.com/assets/4270232/19843267/81994bd4-9f5b-11e6-911c-20613e44c9dc.png">

I don't understand why I have this error because the bot ID is not allowed to be changed, it doesn't have any special characters just english characters and I didn't have this error before when I changed the messaging end point. 

Best,
Joseph

**Comment by dandriscoll** [comment]
Hi @josephktcheung, does your bot ID have a small number of characters? If so, we should have this fixed shortly.

**Comment by josephktcheung** [comment]
Yes, it only has 3 characters.
