### ISSUE TITLE
I tried an example from bot framework documentation page, I am not able to connect to LUIS.AI and redirrecting me to default dialog

### ISSUE THREAD

**Issue by siddiq-rehman** [Microsoft/BotBuilder#1553]
var builder = require('botbuilder');

// Create bot and bind to console
var connector = new builder.ConsoleConnector().listen();
var bot = new builder.UniversalBot(connector);

// Create LUIS recognizer that points at our model and add it as the root '/' dialog for our Cortana Bot.
var model = 'https://api.projectoxford.ai/luis/v1/application?id=c413b2ef-382c-45bd-8ff0-f76d60e2a821&subscription-key=&q=';
var recognizer = new builder.LuisRecognizer(model);
var dialog = new builder.IntentDialog({ recognizers: [recognizer] });
bot.dialog('/', dialog);

// Add intent handlers
dialog.matches('builtin.intent.alarm.set_alarm', builder.DialogAction.send('Creating Alarm'));
dialog.matches('builtin.intent.alarm.delete_alarm', builder.DialogAction.send('Deleting Alarm'));
dialog.onDefault(builder.DialogAction.send("I'm sorry I didn't understand. I can only create & delete alarms."));
![image](https://cloud.githubusercontent.com/assets/22259730/19844116/3866bc3c-9f4f-11e6-8f12-a917c0bb550d.png)

**Comment by msft-shahins** [comment]
looking at the code snippet pasted, I see that you miss subscription key from you luis url and probably that is the reason that calls to Luis are failing in your bot. Here is an example using the same model: https://github.com/Microsoft/BotBuilder/blob/5cf71c742f27d89e9dbc4076f850122bd6edac11/Node/examples/basics-naturalLanguage/app.js#L19

**Comment by siddiq-rehman** [comment]
Hi, I have added the subscription key, as 

var model = process.env.model || 'https://api.projectoxford.ai/luis/v1/application?id=c413b2ef-382c-45bd-8ff0-f76d60e2a821&subscription-key=1be925f44e414e1481024a6d43a7eff5&q=';

Now getting the below error,
![image](https://cloud.githubusercontent.com/assets/22259730/19918541/1b352b4a-a0f2-11e6-8c69-68f837d47961.png)

**Comment by willportnoy** [comment]
When I open that url in the browser, I see this error message:

{ "statusCode": 401, "message": "Access denied due to invalid subscription key. Make sure to provide a valid key for an active subscription." }

**Comment by msft-shahins** [comment]
@siddiq-rehman If you look at sample, this should be the url for the model: https://api.projectoxford.ai/luis/v1/application?id=c413b2ef-382c-45bd-8ff0-f76d60e2a821&subscription-key=6d0966209c6e4f6b835ce34492f3e6d9&q=

**Comment by msft-shahins** [comment]
Closing this. Feel free to open another issue if you need help.
