### ISSUE TITLE
Sometimes I need to re-submit the same text via Facebook Messenger multiple times before it reaches my Api.

### ISSUE THREAD

**Issue by willemodendaal** [Microsoft/BotBuilder#1554]
I notice that often messages sent to the Facebook Messenger channel don't reach my bot at all, until I re-type the same message one or more times. My api runs as an Azure App Service and I trace whenever a message hits my Api (before even starting to process), so I doubt the issue is on my Api's side. It looks like the message is not hitting the Api at all, until I retry a few times. 

Please help?

From the Azure streaming logs (on success, the ignored responses don't show up at all):
2016-10-31T07:42:08  PID[6316] Information Request, Method=POST, Url=https://myurl.azurewebsites.net/api/messages, Message='https://myurl.azurewebsites.net/api/messages'
2016-10-31T07:42:08  PID[6316] Information Message='Messages', Operation=DefaultHttpControllerSelector.SelectController
2016-10-31T07:42:08  PID[6316] Information Message='TheProduct.BotSite.Controllers.MessagesController', Operation=DefaultHttpControllerActivator.Create

Here is  screenshot of the chat:
![2016-10-31 09_47_14-messenger](https://cloud.githubusercontent.com/assets/915354/19847364/037d7948-9f4f-11e6-8291-77946e8f37ad.png)

**Comment by willemodendaal** [comment]
After some more testing I can confirm that this is only for some users, not others. And only on facebook messenger, not Skype. The error occurs when I write the messages as one of the bot's facebook page administrators (I don't know if being an admin has an impact).

**Comment by willemodendaal** [comment]
Also, when I disable the Facebook Messenger channel in the bot framework the messages still go through to the bot. I have double-checked that I have no other bots pointing to the same channel.

**Comment by willemodendaal** [comment]
Hi @tomlm . I've tried from both those pages/controls and get the same behavior.

**Comment by tomlm** [comment]
It almost sounds like you have your endpoint registered multiple times with facebook.  I would double check your configuration.

**Comment by willemodendaal** [comment]
I couldn't spot any multiple registrations, but maybe I'm missing something. At least the problem does not occur when I use another user. And if I'm the only one getting the issue I guess the problem must be on my side.
