### ISSUE TITLE
Direct Line API down

### ISSUE THREAD

**Issue by quaddamage87** [Microsoft/BotBuilder#1555]
Hi all,

We're currently experiencing problems with the Direct Line API.
It stopped working and calls to the API only return the following:

HTTP 403:
{
  "message": "BadArgument:Site missing or disabled"
}

Anyone else experiencing the same?

**Comment by myarotskaya** [comment]
We have the same issue.

**Comment by tjoudeh** [comment]
Yes same here too! It is happening on some bots not all of them.

**Comment by tjoudeh** [comment]
+1 not happening on all bots, but I'm facing the same on one of my bots.

**Comment by brene** [comment]
I'm experiencing issues with CORS can you guys also confirm this?

**Comment by erlendw** [comment]
I'm getting almost the same error! Mine just says forbidden. The thing is, the token regen on direct line seems to not be working. I have tried to regenerete the secret multiple times but it just keeps giving the same secret. Might have something to do with this.

**Comment by dandriscoll** [comment]
Hi @quaddamage87, @myarotskaya, @tjoudeh, @brene, and @erlendw, we have a now build out that should have everything working. Can you take a look and let me know if you're hitting any further issues?

**Comment by quaddamage87** [comment]
Hi @dandriscoll , I just tested it and everything is working again! Thanks a lot, we really appreciate your quick support!

**Comment by quaddamage87** [comment]
@myarotskaya, @tjoudeh, @brene, and @erlendw, please let me know if your related issues are also resolved so I can close this issue. Thanks!

**Comment by tjoudeh** [comment]
@quaddamage87 @dandriscoll looks good for me too, thanks for following up.

**Comment by quaddamage87** [comment]
Alright, I'm closing this issue.

**Comment by dandriscoll** [comment]
Thanks @quaddamage87  😄
