### ISSUE TITLE
How to pass data from a website to a botframework web chat bot?

### ISSUE THREAD

**Issue by simonneve** [Microsoft/BotBuilder#156]
We are building a c# MS botframework bot that will be hosted on a website that we control.

Is there a way to pass a session ID from the host website to the web chat bot widget so that it is accessible when processing messages from within the bot?

If not, is it possible to access the 't' token parameter as described here http://docs.botframework.com/connector/embed-chat-control/

Thanks

**Comment by simonneve** [comment]
Asked the same question on SO.

T Laird-McConnell answered:

> Currently there is no way to do this with the chat control.
> 
> If you want tighter integration you should consider using the DirectLIne API and build your own UX experience via that.
> 
http://stackoverflow.com/users/6137227/t-laird-mcconnell

Is this is a feature that could be added?

**Comment by Stevenic** [comment]
Moved to UserVoice for voting:

https://feedback.botframework.com/forums/354219-bot-connector/suggestions/13626999-support-passing-data-from-a-website-to-a-botframew
