### ISSUE TITLE
PizzaBot LUIS Model Id/SubscriptionKey doesn't work

### ISSUE THREAD

**Issue by abusazzad** [Microsoft/BotBuilder#1561]
Hi,
I'm trying to use the PizzaBot sample solution/project from my Bot Channel Emulator(3.0.0.59). The LUIS Model Id/SubscriptionKey I have in the PizzaOrderDialog.cs file is as below:

**[LuisModel("4311ccf1-5ed1-44fe-9f10-a6adbad05c14", "6d0966209c6e4f6b835ce34492f3e6d9")]**

However I'm getting the following exception (tracked via Fiddler) when running:

> While trying to retrieve the URL: api.projectoxford.ai:443 
> The following error was encountered: 
> Cache Access Denied. 
> Sorry, you are not currently allowed to request: 
>     api.projectoxford.ai:443
> from this cache until you have authenticated yourself. 

Any chance the Model Id/SubscriptionKey has been changed or is there any other issue involved?

Thanks in advance.

**Comment by willportnoy** [comment]
It sounds like you're using a proxy cache that requires authentication (possibly from your organization or ISP).  I don't think the LUIS service will generate that error.
