### ISSUE TITLE
Prompts in proactive dialog not working for negative responses

### ISSUE THREAD

**Issue by dks-ait** [Microsoft/BotBuilder#1562]
I have written a proactive bot, which works fine. Unfortunately, waterfall model is working partially - ONLY YES variant work for builder.Prompts.confirm(). Its never goes to the waterfall step after user responds with a negative option.

The channel I am using is skype. 

The conversation on skype is as below 

[3:36:40 PM] TestBot: ProductName stock has gone below reorder level. Should the order be placed for the same? (1. yes or 2. no)
[3:36:43 PM] Devesh: no
[3:37:03 PM] Devesh: yes
[3:37:04 PM] TestBot: ProductName stock has gone below reorder level. Should the order be placed for 
the same? (1. yes or 2. no)

----------------------------------------------------------
[3:38:00 PM] TestBot: ProductName stock has gone below reorder level. Should the order be placed for the same? (1. yes or 2. no)
[3:38:15 PM] Devesh: yoyo
[3:38:17 PM] TestBot: ProductName stock has been reorder to the supplier

----------------------------------------------------------
[3:38:25 PM] TestBot: ProductName stock has gone below reorder level. Should the order be placed for the same? (1. yes or 2. no)
[3:38:28 PM] Devesh: dada
[3:38:29 PM] TestBot: I didn't understand. Please answer 'yes' or 'no'.
[3:38:41 PM] Devesh: yes
[3:38:42 PM] TestBot: ProductName stock has been reorder to the supplier

As can be seen above the bot works fine with any variant of yes, but gets stuck and never goes to the next waterfall method for negative choices.

The code I am using looks like : 
``` 
bot.dialog('/Notify', [
	function(session, args, next){
		console.log('in skype notify ');
		// Get the product name from ARGS
		builder.Prompts.confirm(session, 'ProductName stock has gone below reorder level. Should the order be placed for the same?');

		// session.prompt('ProductName stock has gone below reorder level. Should the order be placed for the same?');		
	}, function(session, results){
		if (results.response) {
			var txt = results.response;
			console.log(txt + ", type :: " + typeof(txt));
			if(txt){
				session.endConversation('ProductName stock has been reorder to the supplier');
			} else {
				session.endConversation("We would soon run out of stocks. I hope you understand the issues!!");
			}
		}
	}]);
```

Already looked at this : 
https://github.com/Microsoft/BotBuilder/issues/785 
https://github.com/Microsoft/BotBuilder/issues/478

**Comment by chrimc62** [comment]
@Stevenic or @maxpert can you comment?

**Comment by Stevenic** [comment]
What version of t he Node SDK are you using? Definitely should be only matching on "yes" or "no" if you're using 3.4 as we no longer use a RegEx to match against

**Comment by dks-ait** [comment]
I was using 3.2.3 SDK as 3.4 was broken at that point.

**Comment by dks-ait** [comment]
I updated to 3.4.4 but still see that same problem.

**Comment by Stevenic** [comment]
I'm sorry the answer was staring me right in the face.  For `confirm()` the results.response is a Boolean which corresponds to the users answer.  It's set to false if they say no. You're treating it like a text field so you never hit the inside of your `if (results.response)` statement unless they say yes. try:

``` 
bot.dialog('/Notify', [
	function(session, args, next){
		console.log('in skype notify ');
		// Get the product name from ARGS
		builder.Prompts.confirm(session, 'ProductName stock has gone below reorder level. Should the order be placed for the same?');

		// session.prompt('ProductName stock has gone below reorder level. Should the order be placed for the same?');		
	}, function(session, results){
		if (results.response) {
			session.endConversation('ProductName stock has been reorder to the supplier');
		} else {
			session.endConversation("We would soon run out of stocks. I hope you understand the issues!!");
		}
	}]);

**Comment by dandriscoll** [comment]
Hi @dks-ait, have you had a chance to try this solution?

**Comment by maxpert** [comment]
Closing issue. Please reopen if you still face the issue.
