### ISSUE TITLE
HeroCard button "postback" action is very slow in Telegram

### ISSUE THREAD

**Issue by ZOXEXIVO** [Microsoft/BotBuilder#1563]
Try to send button menu with "postBack" action and try to press button in this menu.
Skype work quick, but Telegram very slow and throws "Index was outside the bounds of the array" what can't be catched in Bot Framework and visible only in Bot Console

**Comment by eanders-MS** [comment]
@ZOXEXIVO what is your bot id or your msa app id? With this information I can search our service logs for more information.

**Comment by ZOXEXIVO** [comment]
AppId: 090b92fe-4c55-4349-9dea-14c2dceb419f

**Comment by eanders-MS** [comment]
This was due to a bug in our Telegram adapter. Thank you for reporting it. The fix will go live the next time we update production. We publish to production about once a week.

**Comment by bhanuprakashk** [comment]
I am still facing the same issue, if I try to call  "await context.PostAsync(message);" with hero card inside the message it never work with telegram, but if I use PromptDialog then it works..

  Is there any chance that we can broadcast herocard or image with out using promptdialog.

Thanks
