### ISSUE TITLE
Add support to Twitter Bot (PM)

### ISSUE THREAD

**Issue by JpEncausse** [Microsoft/BotBuilder#1566]
Hello,

Do you have any plan in the roadmap to add twitter :-)
https://blog.twitter.com/2016/speed-up-customer-service-with-quick-replies-welcome-messages-in-direct-messages

**Comment by chrimc62** [comment]
@LarsLiden can you comment?

**Comment by dandriscoll** [comment]
Hi @JpEncausse, we don't have any plans to share about adding new channels to the Bot Framework other than the Cortana channel that was announced earlier in December.
