### ISSUE TITLE
Issue in getting callback query from Telegram

### ISSUE THREAD

**Issue by dimoibiehg** [Microsoft/BotBuilder#1568]
Hi,
I sent the following message to Telegram as an inline message into a group conversation. 
I got the message in a correct format with a callback button.
BUT the callback button did not work properly. As I clicked on it, I did not get any callback query in
my bot. Any suggestion? @eanders-MS 

```javascript
{
  "method": "answerInlineQuery",
  "parameters": {
    "inline_query_id": "479778281665093155",
    "results": [
      {
        "type": "photo",
        "id": "43543654675",
        "photo_url": "https://upload.wikimedia.org/wikipedia/en/archive/a/a9/20151112035044!Banyan_Tree_(_Shiv_Bajrang_Dham_Kishunpur).jpeg",
        "thumb_url": "https://upload.wikimedia.org/wikipedia/en/archive/a/a9/20151112035044!Banyan_Tree_(_Shiv_Bajrang_Dham_Kishunpur).jpeg",
        "reply_markup": {
          "inline_keyboard": [
            [
              {
                "text": "Click On Me",
                "callback_data": "Click"
              }
            ]
          ]
        }
      }
    ]
  }
}
```

**Comment by dimoibiehg** [comment]
As I found, it might be not implemented in Bot Framework. Because the result of callback button is a Callback Query which the message is embedded in it; hence, I think this is not implemented in custom messaging with Telegram in Bot Framework. Is this true?

**Comment by eanders-MS** [comment]
This should should work. It looks like you might be sending the incorrect value for the inline_query_id value. Be sure to send the inline_query.id value from the Telegram message, not the Bot Framework activity. The native Telegram message can be found in the channelData/sourceEvent of the incoming activity.

**Comment by dimoibiehg** [comment]
Thanks @eanders-MS . As you said, I've gotten the inline_query.id like the following:

`JToken token = JObject.Parse(activity.ChannelData.ToString());
if (token["inline_query"] != null)
{
     string query = (string)token["inline_query"]["query"];
     string queryId = (string)token["inline_query"]["id"];
}`.

But it didn't worked, as I mentioned in the issue report.

**Comment by eanders-MS** [comment]
@dimoibiehg I had a look through our service logs, and found what I think is a transaction between your bot and Telegram. The message had an invalid conversation id. It was set to the name of your bot. This is not a field you need to set explicitly. It gets initialized for you when you call activity.CreateReply().

**Comment by dimoibiehg** [comment]
Many Thanks @eanders-MS . As you said, I send my response like the following code:

`var reply = activity.CreateReply();'
`reply.ChannelData = requestJson;`
`await connector.Conversations.ReplyToActivityAsync(reply);`

Is there any guess about where Conversation Id is changed, as I didn't set the conversation Id manually?

**Comment by dimoibiehg** [comment]
My entire sample comes in the following. It is an inline bot.

```CSharp
public async Task<HttpResponseMessage> Post([FromBody]Activity activity)
{
   ConnectorClient connector = new ConnectorClient(new Uri(activity.ServiceUrl));
   if (activity.ChannelId == "telegram")
   {
      var requestJson = "";
      JToken token = JObject.Parse(activity.ChannelData.ToString());
      if (token["inline_query"] != null)
      {
         string query = (string)token["inline_query"]["query"];
         string queryId = (string)token["inline_query"]["id"];
         requestJson = "{";
         requestJson += "'method': 'answerInlineQuery',";
         requestJson += "'parameters': {";
         requestJson += "'inline_query_id': '" + queryId + "',";
         requestJson += "'results': [";
         requestJson += "{";
         requestJson += "'type': 'photo',";
         requestJson += "'id': '" + (new Guid()).ToString().Substring(0, 6) + "',";
         requestJson += "'photo_url': 'https://upload.wikimedia.org/wikipedia/en/archive/a/a9/20151112035044!Banyan_Tree_(_Shiv_Bajrang_Dham_Kishunpur).jpeg',";
         requestJson += "'thumb_url': 'https://upload.wikimedia.org/wikipedia/en/archive/a/a9/20151112035044!Banyan_Tree_(_Shiv_Bajrang_Dham_Kishunpur).jpeg',";
         requestJson += "'reply_markup': {";
         requestJson += "'inline_keyboard': [";
         requestJson += "[";
         requestJson += "{";
         requestJson += "'text': 'Click On Me',";
         requestJson += "'callback_data': 'Click'";
         requestJson += "}";
         requestJson += "]";
         requestJson += "]";
         requestJson += "}";
         requestJson += "}";
         requestJson += "]";
         requestJson += "}";
         requestJson += "}";
      }
   }
   var reply = activity.CreateReply();
   reply.ChannelData = requestJson;
   await connector.Conversations.ReplyToActivityAsync(reply);
   var response = Request.CreateResponse(HttpStatusCode.OK);
   return response;
}
```

**Comment by eanders-MS** [comment]
@dimoibiehg I've enabled additional logging to try to diagnose this issue. Can you give it a try again when you have a chance? Thanks.

**Comment by dimoibiehg** [comment]
@eanders-MS It has been done. Thanks to your response.

**Comment by eanders-MS** [comment]
@dimoibiehg Ok I see an entry for your latest answerInlineQuery. Telegram is returning `Bad Request: QUERY_ID_INVALID`. Your value for `inline_query_id` does appear to be invalid. It has the same value as the reply activity's `replyToId` field. It is improbable this could ever be valid.

You code above appears to pull the query id from the correct place, but the value I see in the log is obviously not correct.

Note that inline_query_ids are only valid for 15 seconds or so before Telegram expires them.

**Comment by dimoibiehg** [comment]
@eanders-MS I've logged my test inline query too. When getting query from bot framework, activity_id and inline_query_id, which I received, were the same. Therefore, if this similarity is a problem, it's come from the bot framework. am I right? 
Also, the first message which I got from telegram, when wrote an inline query as a user, comes in the following image.
![bfdebug](https://cloud.githubusercontent.com/assets/22638310/20028615/0b1efa9a-a34c-11e6-8983-a7fde117eecf.png)

**Comment by eanders-MS** [comment]
Ok, sorry for the confusion. It stemmed from my lack of understanding about how we process Telegram inline queries. The activity's id is indeed set to the incoming query id in this case. Your inline_query_id value is correct after all.

I'm going to try to repro locally.

**Comment by dimoibiehg** [comment]
Ok. Thanks very much. I'm looking forward to hear from you.

**Comment by dimoibiehg** [comment]
Hi @eanders-MS,
Is there any progress on this issue? (a simple sample code which works as an inline bot that consists of a callback button)

Many thanks in advance.

**Comment by eanders-MS** [comment]
Sincere apologies for the delay in response. I believe you must serialize the JSON of your `results` value to a string. Please read the documentation for this field here: https://core.telegram.org/bots/api#answerinlinequery

**Comment by eanders-MS** [comment]
Closing the issue. If you're still having problems please open a new one.

**Comment by dimoibiehg** [comment]
The problem is not solved as you can see in [this issue](https://github.com/Microsoft/BotBuilder/issues/1716). You can follow the current issue, in [the issue](https://github.com/Microsoft/BotBuilder/issues/1716).
