### ISSUE TITLE
Every message is 'default_error'.

### ISSUE THREAD

**Issue by strangecyan** [Microsoft/BotBuilder#1569]
We have a bot that has been up and running for around 3 months now and from a recent update of npm packages, it is now replying with 'default_error' for every message. I attempted to fix this by forcing a locale, which I saw in another issue related to this, which seemed to work for a while but has seemed to stopped working.

I think it's related to this commit:
https://github.com/Microsoft/BotBuilder/commit/9a1d8e78b9fe1d81bd9b481d2743006a6032f7b9

Any help would be appreciated, thanks,
James

**Comment by Stevenic** [comment]
So first let's try to address why you're getting an error for every message. There's likely an exception being thrown somewhere which could be related to the update but we haven't had any other reports of this so I'd ask if there's anyway you can check your logs to see what the error is? Also can you verify that you're at versions 3.4.2?

As for the fact you're always seeing 'default_error' that would imply that the locale files aren't being loaded.  I think you're probably on the right path with its something around localization I'm just not sure what it would be without knowing where the exception is.  

If the problem persists and you just want the bot working again you could update your package.json file to force the use of version 3.2.1 which was before we added localization support.

**Comment by jdwilkin** [comment]
This is most likely the same issue that I brought up in #1559

**Comment by Stevenic** [comment]
Please try v3.4.4 to see if the 'default_error' part of this goes away. Does look like that part at least is most likely related to a case insensitivity issue.

**Comment by chrimc62** [comment]
Closing due to lack of response.  If you are still having the issue please let us know.
