### ISSUE TITLE
Add buttons as markdown in the web chat control?

### ISSUE THREAD

**Issue by simonneve** [Microsoft/BotBuilder#157]
Is it possible to add buttons as mark down in the web chat control so that users can select the response rather than typing using the keyboard?  Slack and Telegram have reaction buttons I believe.

This is particularly important for mobile devices where touch is preferred over typing.

Thanks

**Comment by chrimc62** [comment]
This is something we are definitely looking into how best to support.

**Comment by dandriscoll** [comment]
Yep! Great suggestion. Moved to https://feedback.botframework.com/forums/354219-bot-connector/suggestions/13641096-add-button-support-to-the-web-chat-control
