### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by felaray** [Microsoft/BotBuilder#1572]
My bot is work from other channel.

but  web chat have error in 500.

[website](http://botsolo.azurewebsites.net/index.aspx) on azure

<img width="525" alt="bot-1" src="https://cloud.githubusercontent.com/assets/5403865/19945541/9158f14c-a17b-11e6-8e92-c1fa085f26e3.png">

<img width="368" alt="bot-2" src="https://cloud.githubusercontent.com/assets/5403865/19945542/915a85fc-a17b-11e6-88da-d4c4f2c1639e.png">

**Comment by dandriscoll** [comment]
Hi @felaray, it looks like your bot is generating HTTP 400 errors. When your bot generates an error, we return an HTTP 500 error back to your client.

Do you know why your bot is returning an HTTP 400 error?

**Comment by felaray** [comment]
thanks reply. I have no idea. I just connect Bot with Luis...no write any code...

BOT -> Luis(preview) -> call Azure Logic App 
and return json back to luis and show on bot...

that's work on some channel(lile email/skype)
so I don't know why can't user on webchat.

(POST) https://prod-04.eastasia.logic.azure.com:443/workflows/fc5e9ad7b6234274979f6c57c5339b67/triggers/request/run?api-version=2016-06-01&sp=%2Ftriggers%2Frequest%2Frun&sv=1.0&sig=IaxCZRi-1B1UJedQibZIgUAUVHbppEEaVRMAZjtJv8A

**Comment by felaray** [comment]
I found that json "type:message" will cause errors.
but other action like ping/typing is work. { "type": "typing" }

<img width="1069" alt="default" src="https://cloud.githubusercontent.com/assets/5403865/19966946/ff975878-a208-11e6-93fd-ea1208904979.png">

======== full json ==============

{
  "type": "message",
  "id": "4007fa42e0e1407fb18119fdc572b389",
  "timestamp": "2016-11-03T12:58:40.9520975Z",
  "serviceUrl": "http://localhost:9000/",
  "channelId": "emulator",
  "from": {
    "id": "2c1c7fa3",
    "name": "User1"
  },
  "conversation": {
    "isGroup": false,
    "id": "2c1c7fa3",
    "name": "User1"
  },
  "recipient": {
    "id": "56800324",
    "name": "Bot1"
  },
  "text": "hi",
  "attachments": [],
  "entities": []
}

**Comment by tomlm** [comment]
I don't know that the current emulator puts the red circle on failed submissions that aren't message.  Click on the typing message and look in the right panel at the bottom to see what status code your bot is returning.

**Comment by felaray** [comment]
Dear Tomlm.

Thanks reply. it's "200 ok". 

Try it on your emulator if you want. 

Bot url:
https://luis-actions.cloudapp.net/api/v1/botframework?app-id=bd347ea5-b1b6-4c83-ac0c-cd2b245a73cb&subscription-key=e4f672dd1f28419aa3a1b7901e4751a1

ID
396e5f1f-4dd5-4a22-b6f5-599f9d68da74

PWD
pBKVHjx9ooobRnPTU6Ed1Qd


<img width="1083" alt="bot" src="https://cloud.githubusercontent.com/assets/5403865/20031254/6fa4784c-a3af-11e6-89ac-989a15076b32.png">

**Comment by tomlm** [comment]
I just tried it and it worked fine.  Looking at your screen shot you have http://localhost:9000 as your serviceurl.  That won't work when talking to a web hosted bot.  If you look at the activity which is sent to your bot it has the **serviceUrl** property which defines the service your bot should talk back to.  In your screen shot it is **http://localhost:9000** which is NOT accessible by your bot in the cloud.

What happens is your bot attempts to POST back to the emulator channel using http://locahost:9000 which it can't. 

You need to download a tool like ngrok (http://ngrko.io) and then use the ngrok url as your service url

![image](https://cloud.githubusercontent.com/assets/17789481/20039753/2ca7ba6e-a3fe-11e6-981c-cd5b573c3648.png)
