### ISSUE TITLE
Is it not possible to attach IntentDialog into calling Bot? like chat bot?

### ISSUE THREAD

**Issue by ubreddy** [Microsoft/BotBuilder#1575]
I am getting internal server error when I attach Luis Intent dialog to the root of the Calling bot. Is there a way to have LUIS work with calling bot ?

**Comment by tomlm** [comment]
Which library, node or c#?

**Comment by ubreddy** [comment]
Node
On 04-Nov-2016 1:55 AM, Tom Laird-McConnell <notifications@github.com> wrote:Which library, node or c#?

**Comment by tomlm** [comment]
Can you show example code of what you are trying?

**Comment by ubreddy** [comment]
var bot = new builder.UniversalBot(connector, {
			autoBatchDelay : 1500
		});

	cConnector = new calling.CallConnector({
			callbackUrl : 'https://0149d34b.ngrok.io/test/calls',
			appId : skypeAuth.appId,
			appPassword : skypeAuth.appPassword
		});
	bot.use({
		botbuilder : function (session, next) {
			// session.sendTyping();
			// console.log('Time',session.message.timestamp,'Text:',session.message.text,'User:',session.message.user.id);
			if (!session.userData.firstTime) {
				session.userData.firstTime = true;
				session.send(prompts.landingMessage);
			}
			next();
		}
	});
	cBot.use({
		botbuilder : function (session, next) {
			// session.sendTyping();
			// console.log('Time',session.message.timestamp,'Text:',session.message.text,'User:',session.message.user.id);
			if (!session.userData.firstTime) {
				session.userData.firstTime = true;
				session.send(prompts.landingMessage);
			}
			next();
		}
	});
	var model = process.env.model;
	var recognizer = new builder.LuisRecognizer(model);
		var dialog = new builder.IntentDialog({
				recognizers : [recognizer]
			});
	var cDialog = new builder.IntentDialog({
	 		recognizers : [recognizer]
	 	});
	bot.dialog('/', dialog);
	cBot.dialog('/', cDialog);
	
	dialog.matches('as.intent.describe', [builder.DialogAction.send(prompts.helpMessage)]);
	cDialog.matches('as.intent.describe',[function (session) {
	 			session.send(prompts.helpMessage);
	 		}
	 	]);
	dialog.onDefault([builder.DialogAction.send(prompts.didntGetIt + prompts.helpMessage)]);
	cDialog.onDefault([function (session) {
			session.send(prompts.didntGetIt + prompts.helpMessage);
			}
	 	]);

**Comment by ubreddy** [comment]
I get 500 internal server error.. but no error reported on console.

**Comment by Stevenic** [comment]
No... There's no way to use LUIS with a calling bot unfortunately :(

**Comment by slidenerd** [comment]
@ubreddy  how come your Universal Bot takes an object with {autoBatchDelay: 0} as the property when the constructor of Universal Bot clearly takes an IDialogWaterfallStep or its array
