### ISSUE TITLE
bot is not waiting for Prompts.choice input

### ISSUE THREAD

**Issue by rampratheek** [Microsoft/BotBuilder#1576]
Ran the following code and the prompt was not waiting for the client's selection of choice.
`bot.dialog('/Choices',[`
                        function(session){
                                session.send("Please select one of the following Choices")
                                builder.Prompts.choice(session," ","Choice1|Choice2|Choice3");
                        },
                        function(session,results){
                            console.log("Prompt Response")
                            session.beginDialog("/"+results.response.entity);
                        }
                        ])`

Bot was taking the " undefined " as the choice and giving the following Error

`Error: Dialog[*:/undefined] not found. at Session.beginDialog (/home/user/node_modules/botbuilder/lib/Session.js:134:19) at Array.<anonymous> (/home/user/workspace/XCubeLabsBOT/BOT2.js:141:35) at SimpleDialog.waterfallAction [as fn] (/home/user/node_modules/botbuilder/lib/dialogs/DialogAction.js:116:32) at SimpleDialog.dialogResumed (/home/user/node_modules/botbuilder/lib/dialogs/SimpleDialog.js:20:14) at Session.endDialog (/home/user/node_modules/botbuilder/lib/Session.js:214:28) at Array.<anonymous> (/home/user/workspace/XCubeLabsBOT/BOT2.js:65:33) at SimpleDialog.waterfallAction [as fn] (/home/user/node_modules/botbuilder/lib/dialogs/DialogAction.js:116:32) at SimpleDialog.dialogResumed (/home/user/node_modules/botbuilder/lib/dialogs/SimpleDialog.js:20:14 at Session.endDialogWithResult (/home/user/node_modules/botbuilder/lib/Session.js:237:28) at SimpleDialog.waterfallAction [as fn] (/home/user/node_modules/botbuilder/lib/dialogs/DialogAction.js:123:19)`

**Comment by Stevenic** [comment]
does is just get back 'undefined' as the choice? Or does it call the next waterfall step before the user even types anything?  I see nothing wrong with this code at first blush. Is this the actual code or a simplified version?

**Comment by rampratheek** [comment]
bot calls the next waterfall step before the user types anything and takes undefined as the choice.Thus the  " /undefined " not found is coming in my error log.

**Comment by ritazh** [comment]
+1

**Comment by Stevenic** [comment]
@rampratheek I tried the exact code above and couldn't get the issue to reproduce with either the ChatConnector or ConsoleConnector classes.  What version of the SDK are you using?

**Comment by bearnshaw** [comment]
@rampratheek not sure if this applies in your case, but if you pass arguments containing the key "resumed" to a waterfall step, that step will be ignored and execution will be passed to the next step.

**Comment by chrimc62** [comment]
Closing due to lack of response.  If you are still having the issue, please reopen and we will look into it more.

**Comment by Zelophobian** [comment]
I have the same problem at the moment. My bot does not wait for the user to input something. It just moves on. the results.response is true, but I have no idea why. The results.response.entity is undefined. Which leads to a loop, because the user enters what he wants and the bot starts over.

**Comment by Arpafaucon** [comment]
Reopening because having the same issue.

```typescript
    bot.dialog('qdj', [
        function (session) {
            session.send("Paré pour la QDJ?");
            builder.Prompts.choice(session, "Tu lis les nouvelles?", {
                "sur ton café électronique": 1,
                "en lisant une tartine ouverte à la bonne page": 2
            }, {listStyle: builder.ListStyle.auto});
        },
        function (session, results) {
            console.log("immediate response", results.response);
            session.send("tu as choisi : %s", results.response.entity);
            session.send("Merci d'avoir répondu!");
            session.endDialog();
        }
    ]).triggerAction({
        matches: /^qdj$/i
    });
```

With the result : 

![issuechoice](https://user-images.githubusercontent.com/19834684/29751722-78130c02-8b51-11e7-9b03-79ef66c8dd8c.png)

I noticed that all the messages are sent at once, as if it directly skipped to the next waterfall function.

**Comment by janhim89** [comment]
I am facing the same issue. :(

**Comment by Zelophobian** [comment]
As I recall it, the problem was the missing if Statement in the followed function after the choise to check if a results.response was given or not.
I think that fixed it.
