### ISSUE TITLE
[Feature Request] EntityRecognizer.parseNumber should take locale into account

### ISSUE THREAD

**Issue by palmerabollo** [Microsoft/BotBuilder#1577]
The [current implementation uses a regular expression](https://github.com/Microsoft/BotBuilder/blob/391969125513160c599ea7bd18c5a6729b3611f9/Node/core/lib/dialogs/EntityRecognizer.js#L204) that doesn't work with some cultures (for example, in Spain or Brazil we use a comma instead of a period as the decimal separator).

For this reason, in these cultures, `Prompts.number(...)` is not able to understand the user input (for example 10,5 is parsed as 10).

It should parse numbers that mix periods/commas (such as 1,283.38), too.

**Comment by Stevenic** [comment]
There are broader problems with the current recognizer but we should add this to the list.

**Comment by chrimc62** [comment]
@Stevenic or @maxpert have you entered this a TFS issue?

**Comment by nwhitmont** [comment]
The [](https://docs.botframework.com/en-us/node/builder/chat/prompts/#promptsnumber) docs could use some more specific details on supported input types (eg. input floats supported? locale support?) with example code.

**Comment by nwhitmont** [comment]
The [Prompts.number() docs](https://docs.botframework.com/en-us/node/builder/chat/prompts/#promptsnumber) could use some more specific info on supported input types. Eg. floats supported? locale support? must input floats in decimal format. do not use commas.

**Comment by nwhitmont** [comment]
@Stevenic any updates on `Prompts.number()` accepting localized number formats?

**Comment by sgellock** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botbuilder-channels/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
