### ISSUE TITLE
Is bot Data stored in Hub inspite of Implementing custom BotState (StateApi) apis?

### ISSUE THREAD

**Issue by beadarsh** [Microsoft/BotBuilder#1580]
Hello we are building a bot where we get personally identifiable information from the user. Hence we need to make sure that this data is not saved in any way on any Microsoft database. Hence We are currently building our own BotState (StateApi) to connect our personal DB instead of the default Azure one available out of the box.

When we connect to our Bot using Direct Line Apis using the following steps:

1) The DirectLineApi posts message to the bot using  userConversations.PostMessage(conversationId, msg)
    ----> This hits our custom BotState source code as expected.

2) But when we call userConversations.GetMessages(conversationId), --> It does not seem to invoke our BotState code. But the messages have appeared on the client side.

3) We also tried closing down this connection and tried to call the userConversations.GetMessages(conversationId) after 2 minutes. It again seem to have not invoked our code, but have the messages appear to the user.

This gives us a feeling our messages are further stored somewhere in Hub (probably directline.botframework.com?) which is a concern for us. Could someone please throw some light on if and how the messages are stored in the hub inspite of us overriding the BotState?

Also how does watermark work when the BotState does not seem to have anything to do with watermarks.
userConversations.GetMessages(conversationId, waterWark.ToString());

**Comment by tomlm** [comment]
Currently the bot state api is only used to store internal tracking information for the BOT itself. 

DirectLine is a channel and it uses azure table storage with the data encrypted to provide clients ability to get the state of a conversation.  It does not use the bot state api.  Allowing it to have a conversation storage API is good idea and we will add to our enhancement list.

**Comment by beadarsh** [comment]
Thanks for your reply. Do we know how long would that data in azure be stored (Also which DataCenter)? Is there a chance we can dictate the datacenter that this storage can take place in the future for legal reasons? Also Does that mean other channels also use their own table storage?

**Comment by tomlm** [comment]
No, all of the other channels are able to pass their data through, they act as a proxy which takes care of transport and translation but no storage.  The DirectLine channel on the other hand is acting as a store and forward service, aka, you have a mobile app which is started up and connects to a conversation to get the latest messages from the conversation.  This requires the data to be stored in an intermediate server awaiting a client to ask for it.

We are looking at ways that we can have directline store the data in dev controlled location, but as of now we don't support it.

I believe we store the data encrypted in our storage layer, and I don't know what the expiration but I know the data does expire (I think it is 7 days)

**Comment by dandriscoll** [comment]
Data retention in Direct Line is 24 hours although we've had many requests to shorten/eliminate this, and we're considering it for our backlog.

**Comment by beadarsh** [comment]
Ok...Thank you for your replies. Now it all makes sense. 

Unfortunately data retention in Directline is a showstopper for us as data retention is a definite no-no. We might spend some time to implement a custom connector and bypass the framework if its easy enough for the time being.

It would be great if you can keep us updated on this feature.  Thanks

**Comment by chrimc62** [comment]
@tomlm  or @dandriscoll is this in TFS and do you want to keep this item open?

**Comment by dandriscoll** [comment]
We've got some thinking around this but as it's a new feature area for the product, we probably won't keep it around as a GitHub issue. Any launch we do of a feature like this will be accompanied by an announcement or blog post.
