### ISSUE TITLE
Messaging after entering intent (LUIS)

### ISSUE THREAD

**Issue by piffarettig** [Microsoft/BotBuilder#1581]
Im using Bot Framework and LUIS, and I need to find a way to ask the user messaging to enter some parameters if the parameters werent detected on the utterance that caused the intent.
So, after an intent gets detected and called,  I need to check if a certain parameter is in the LuisResult, like this:

```
[LuisIntent("DoSomething")]
public async Task DoSomething(IDialogContext context, LuisResult result)
{
     string aParameter;
     if (TryGetParameter(result, out aParameter))
      {
         // do something with the parameter
      }
      else
      {
         // ask the user to enter the needed parameter... and so on if there are more parameters needed
        // here a new message flow starts, asking the user for the parameters... How can I do this without 'leaving' the intent? 
       }
       context.Wait(MessageReceived);
 }
```

I need something simpler than FormFlow, as FormFlow use hardcoded enums to options, and in my case parameters options are something dynamic.

Thanks in advance.

**Comment by willportnoy** [comment]
Instead of calling
context.Wait(MessageReceived)

unconditionally, add a new method
private async Task AfterUserInput(IDialogContext context, IAwaitable<IMessageActivity> result)

and call
context.Wait(AfterUserInput);

**Comment by piffarettig** [comment]
Ok cool thanks! Now I have a couple of more questions:

1) How do I get the text the user entered. Inside the AfterUserInput function I'm doing:

` var message = await result;`

But examining that object I didn't found a property corresponding to my text.

2) And supossing that I can find the text, how can I, inside that function (AfterUserInput), call LUIS again so It can analyse the utterance again?

Code right now is like this:

```
[LuisIntent("DoSomething")]
public async Task DoSomething(IDialogContext context, LuisResult result)
{
     string aParameter;
     if (TryGetParameter(result, out aParameter))
      {
         // do something with the parameter
         context.Wait(MessageReceived);
      }
      else
      {
          context.Wait(AfterUserInput);
      }
 }

// And my AfterUserInput function goes like this right now:

  private async Task AfterUserInput(IDialogContext context, IAwaitable<IMessageActivity> result)
  {
      var message = await result;
      // assuming that I can get the text entered...
      // how can I call LUIS again (without doing the explicit call to the service), to make him analyse the text? or should I do this by hand
  }

```

Thanks in advance!

**Comment by willportnoy** [comment]
1. Look at message.Text to get the user's text.
2. Inside of AfterUserInput, call MessageReceived(context, result) to use the normal LuisDialog dispatching.

**Comment by piffarettig** [comment]
Thanks, I was just trying that but it seems that now whenever I type something to the bot, it always enters on 'AfterUserInput' function and then it enters on the 'DoSomething' intent function. Is it related to the dialog stack or something? Code now look like the one before but with the AfterUserInput function  as you said:

```
 private async Task AfterUserInput(IDialogContext context, IAwaitable<IMessageActivity> result)
        {
            var message = await result;
            string text = message.Text;
            await context.PostAsync(text);
            await MessageReceived(context, result);
        }
```

**Comment by piffarettig** [comment]
Any thoughts about that?

**Comment by willportnoy** [comment]
After receiving a user's message, it should enter whichever method was passed to context.Wait last.  If you point to the same method, it will re-enter the same method.

**Comment by piffarettig** [comment]
Thanks!
