### ISSUE TITLE
".endConversationAction" and ".beginDialogAction" not working

### ISSUE THREAD

**Issue by sitver** [Microsoft/BotBuilder#1582]
I'm trying to build a persistant menu for my bot using "bot.endConversationAction()" and "bot.beginDialogAction()", but whenever I use either of these my bot breaks and starts returning internalserver errors.  

Example of things I've tried which haven't worked:
` bot.endConversationAction('goodbye', 'Goodbye :)', { matches: /^goodbye/i });`

**Comment by sitver** [comment]
Let me know if you need more information.

**Comment by Stevenic** [comment]
What version of the SDK are you using? And when you say they don't work do they work if the user types "goodbye" ?

**Comment by sitver** [comment]
I think I was running the latest version, but I rebuilt it to run entirely on intents, so I don't need this anymore (at least I don't think I do)

**Comment by Stevenic** [comment]
Ok...
