### ISSUE TITLE
Unable to send attachment in MacOs Emulator

### ISSUE THREAD

**Issue by somprabhsharma** [Microsoft/BotBuilder#1587]
Whenever I am replying with an attachment i.e. card or image or button. The MacOs emulator is responding with an error. 

I am getting the same error mentioned in the below comment https://github.com/Microsoft/BotBuilder/issues/11#issuecomment-248861647

**Comment by chrimc62** [comment]
We have released a new emulator, please try that and let us know if you still have an issue.
