### ISSUE TITLE
Bot starting a conversation

### ISSUE THREAD

**Issue by s-rya** [Microsoft/BotBuilder#159]
Can the bot start a conversation without listening to any message or any mention?

For e.g. In the morning I want my bot to wish the user Good Morning at a specific time.

**Comment by JpEncausse** [comment]
I have the same question.
Any NodeJS sample to sens a SMS to a given number ? 

The documentations states to build a message and call `connector.Messages.SendMessage(message);` but can I reuse my BotConnectorBot to do that ? in the API there is no SensMessage method.

**Comment by tomlm** [comment]
If you have SMS channel created you use
                “channelId” :”sms”
                “address” : “+1234567890”
For From field it should be your bots phone number in twilio
For To field it should be the phone number of the user.

And then use normal SendMessage()
-Tom

**Comment by s-rya** [comment]
@tomlm : Hey Tom, Can I do the same if my channel is Skype or Slack?

**Comment by tomlm** [comment]
Yes, that is the purpose of the SendMessage API, you can send a message to any user that way.  There are some caveats:
* The From field and To field need to be on same channel
* The From field needs to be the appropriate address for that channel. (For example, your address is different for every instance of your bot in a slack channel.)
* If you haven't been in a conversation with them you may not be able to initiate a new conversation with them
* It is possible to hit rate limits for how often you can do that to prevent spam.  The rate limits are per user and reasonable, but still exist.

**Comment by mikkhait** [comment]
I think this worth re-opening or at least create a new issues. Here are some of my thoughts on this:

- Starting a conversation with an *Emulator* does not work. Even as conversation has been previously initiated.
- When used to initiate a conversation via _real_ channels, when _firstRun_ middle ware is present, there is no way to bypass it ( that's assuming both _reactive_ and _proactive_ bots leave in the same instance of `BotConnectorBot`
- Perhaps `from` could be inferred from the bot itself
- Worth linking with #196

Here is a sample using [node-cron](https://github.com/ncb000gt/node-cron)
```
var job = new CronJob({
  cronTime: '* * * * *',
  onTick: function () {
    bot.beginDialog({
      to: {
        address: "User1",
        channelId: "emulator",
        id: "2c1c7fa3",
        isBot: false
      },
      from: {
        address: "localdev",
        channelId: "emulator",
        id: "localdev",
        isBot: true
      }
    }, '/cron');
  },
  start: false,
  timeZone: 'America/Los_Angeles'
});
job.start();

bot.add('/cron', function (session) {
  session.endDialog('eat me!!!');
});
```

**Comment by alokraj68** [comment]
Is there any method similar to node-cron in c#

**Comment by PrasadKosaraju** [comment]
I've a Webchannel for created for the bot. When a user clicks on link on website a popup should open and bot should start the conversation. I want to understand any event or method i can use for the bot to start initial conversation

**Comment by McBacker** [comment]
I'm pretty sure that a Bot can't start a conversation... you (the user) should must send the first interaction.

**Comment by michaelhutchful** [comment]
Are you sure? It can. What language? Can handle system message. Message type conversation update or contact relation update

Michael
Sent from my Windows 10 phone

**Comment by McBacker** [comment]
@michaelhutchful 

At least on Telegram you couldn't send a message to a given user through a Bot that was never contacted before by that user.

And makes sense as it avoids spam.

**Comment by michaelhutchful** [comment]
Oh ok i understand

Sent from my Windows 10 phone

**Comment by PrasadKosaraju** [comment]
Yeah i need on this webchannel/website, so there is no way  i can use contact relation update. Is there another way or hack some way

**Comment by alokraj68** [comment]
@PrasadKosaraju try [this](http://bot.clickastro.com/) bot. Tell me if this is your expected behaviour.

**Comment by PrasadKosaraju** [comment]
@alokraj68 : Exactly this what i want. Can you please let me know how this is done? Is it Microsoft Bot Framework itself

**Comment by alokraj68** [comment]
@PrasadKosaraju its using conversation update and contact relation update.

**Comment by PrasadKosaraju** [comment]
@alokraj68 : Thanks a lot Alok. I tried previosuly contact relation update and didn't work on webchat. Conversation update did the trick for Web. Thanks for your direction.

**Comment by Snowflame** [comment]
I found a good snippet on stackoverflow.

[(https://stackoverflow.com/questions/43048088/microsoft-bot-framework-sending-message-on-connect#answer-43050305)]

`// Send welcome when conversation with bot is started, by initiating the root dialog
bot.on('conversationUpdate', function (message) {
    if (message.membersAdded) {
        message.membersAdded.forEach(function (identity) {
            if (identity.id === message.address.bot.id) {
                bot.beginDialog(message.address, '/');
            }
        });
    }
});`
