### ISSUE TITLE
Receiving parameters of same LUIS intent on different messages

### ISSUE THREAD

**Issue by piffarettig** [Microsoft/BotBuilder#1591]
I want to achieve a bot that asks the user to enter a message, check it with LUIS so it matches an intent, and in case that the user dind't type all the needed parameters, ask them to enter them without leaving the intent.

Supose that I ask the user to enter a new parameter after that he has typed. How can I call LUIS again but with both utterances at the same time? Something like this:

--> BOT: Hello, what do you need?
--> User: I want a Pizza

// Asks LUIS ' I want pizza' and it returns the OrderPizza intent, but some params are lacking. //

--> BOT: Ok, what kind of Pizza do you want?
--> User: A big one, with pepperonis and blue cheese.

// Asks LUIS with 'I want Pizza' + 'A big one with pepperonis and blue cheese'. It returns the OrderPizza intent with all the corresponding entities.

The main problem here is how to persist a pevious utterance to 'concat it' to a previous one and then send it as a whole utterance.

I was thinking of calling manually LUIS service inside the LUIS function, but I dont know how to achieve that because the way LUIS is called now is by using the LuisIntent[] Annotations, not by hand.

Code would be something like:

```
        [LuisIntent("Orderpizza")]
        public async Task Orderpizza(IDialogContext context, LuisResult result)
        {
            string pizzaType;
            if (TryGetPizzaType(result, out productType))
            {
             // order pizza
            }
            else
            {
                // no pizza type was specified
                await context.PostAsync($" Ok, what kind of Pizza do you want?");
                context.Wait(AfterPizzaType);
                context.Reset();
            }
        }

        private async Task AfterPizzaType(IDialogContext context, IAwaitable<IMessageActivity> result)
        {
            var message = await result;
            string pizzaType = message.Text;
            // the user has now entered the pizza type, how can I match this string with LUIS without doing an explicit call to the service?
            await MessageReceived(context, result);
        }
```

I dont want to use FormFlow!

Thanks!

**Comment by chrimc62** [comment]
@piffarettig were you able to solve this?  You can store any data you want in the per user conversation state which you can then read.  You can also create a dialog which keeps that information as a string and that will automatically be serialized and deserialized with messages.

**Comment by msft-shahins** [comment]
@piffarettig you can implement this by saving the first utterance in the private conversation data and add it to the text query sent to Luis service on the next message by overriding the GetLuisQueryTextAsync funciton: https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Dialogs/LuisDialog.cs#L226

Another way is to create a child LuisDialog in the main LuisDialog intent handler, keep the utterance as a member variable in the child dialog and have the child dialog append the utterance to the queries sent to Luis by overriding the GetLuisQueryTextAsync.
