### ISSUE TITLE
Directline CORS question

### ISSUE THREAD

**Issue by martinkr** [Microsoft/BotBuilder#1593]
Hi,

i'm running a bot occasionally. I'm using the directline API. The bot front-end runs on localhost. I used it on  Sep 26 and it worked.  Today it stopped working - all i get is "Fetch API cannot load https://directline.botframework.com/api/tokens/conversation. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.". Do i need to pass the requests through a cors-proxy? Are there changes on the API? 
Thanks in advance :)

**Comment by dandriscoll** [comment]
Looks like a bug, we'll have this fixed shortly.

**Comment by dandriscoll** [comment]
Hi @martinkr, this should be fixed in all of our datacenters now. Can you take a look?

**Comment by martinkr** [comment]
Hi @dandriscoll, works fine again. Thanks!

**Comment by suminksudhi** [comment]
Hi, 
I have the same issue while calling the api from my browser

XMLHttpRequest cannot load https://directline.botframework.com/v3/directline/tokens/generate. Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'http://localhost:4300' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.
