### ISSUE TITLE
Facebook: send button result with imBack does not work

### ISSUE THREAD

**Issue by vorti2** [Microsoft/BotBuilder#1594]
The "Select" buttons in Facebook carousel example (https://github.com/Microsoft/BotBuilder/blob/master/Node/examples/demo-facebook/app.js, line 236ff) does not work as aspected.

If the use clicks on a "Select" button nothing happens except the Facebook "waiting dots". Input of "select:101" (for example) works correctly.
  
Environment: 
* NodeJS Version: 5.10.1
* Bot Version: 3.4.4

**Comment by Stevenic** [comment]
Sorry for the delay. I can try to reproduce the issue.

**Comment by ftachon** [comment]
Hi all,

I try to used button to postBack data;

In Emulator and Skype work fine, but in Facebook when click the button appear the the message button and the  "waiting dots (...)"
  
Here part of the message

	"attachments": [{
		"contentType": "application/vnd.microsoft.card.hero",
		"content": {
			"images": [],
			"buttons": [{
				"type": "postBack",
				"title": "Option1",
				"value": "1"
			},
			{
				"type": "postBack",
				"title": "Option2",
				"value": "2"
			}]
		}
	}],

**Comment by chrimc62** [comment]
@Stevenic or @maxpert have you had a chance to look at this?

**Comment by ftachon** [comment]
Hi all,

I tray to send a native Facebook message, the buttons appear in Facebook chat, but the behavior is the same.

here part of the message

"channelData": {
		"attachment": {
			"type": "template",
			"payload": {
				"template_type": "button",
				"text": "Select a option\n",
				"buttons": [{
					"type": "postback",
					"title": "option 1",
					"payload": "1"
				},
				{
					"type": "postback",
					"title": "option 2",
					"payload": "2"
				},
				{
					"type": "postback",
					"title": "option X",
					"payload": "X"
				}]
			}
		}
	},

**Comment by tomlm** [comment]
I set a break point on your controller endpoint and inspect the message.  You should be receiving a message with the payload as the .text field

**Comment by ftachon** [comment]
Hi,
I have the acces.log form my server today, and a have all request / response from my application a didn't get response form Facebook when I click on the button

**Comment by ftachon** [comment]
Hi all,
I know why I didn't received the post back, but I need help to fix it.
When I click on Facebook's button the browser console (inspect tool) reported a error

POST https://www.messenger.com/messages/commerce/postback/?cta_id=bW5jdGE6Y3RhMV9FbnRNZXNzZW5nZXJDb21tZXJjZUl0ZW1fNjM5NTQyNTgyODk1MDkwXzA%3D&dpr=1 
500()

**Comment by Stevenic** [comment]
Not sure what's causing that. Did it include a message?

**Comment by maxpert** [comment]
Closing issue please reopen if you are still facing the issue.

**Comment by vorti2** [comment]
Solved the issue by enable option "messaging_postback" in the page Webhooksa in Facebook Developer console.
