### ISSUE TITLE
[Bug] How to get session.cancelDialog work?

### ISSUE THREAD

**Issue by zytsai** [Microsoft/BotBuilder#1599]
Hello,

I'm trying to use session.cancelDialog(<dialogId>, <replaceWithDialogId>) to cancel a parent dialog from its child and then restart the parent dialog from the beginning.
My code looks like the following, but I can't get it work.
When session.cancelDialog('/inquery', '/inquery') is executed, the bot state will be corrupted with the error "Oops. Something went wrong and we need to start over.".

Thanks for the help.

```javascript
bot.dialog('/inquery', [
   ...,
   function (session, result) {
      session.beginDialog('/confirm');
   },
   ...
]);

bot.dialog('/confirm', [
   ...,
   function (session, result) {
      /* cancel current parent dialog and restart it from the beginning */
      session.cancelDialog('/inquery', '/inquery');
   },
   ...
]);
```

**Comment by tahsintahsin** [comment]
I think you should use it as session.cancelDialog('/confirm', '/inquiry') if you want to cancel confirm and start inquiry. If you want to cancel the parent dialog, not the child, you can check replaceDialog to start parent dialog from zero, you can use it as session.replaceDialog('/inquiry')

**Comment by zytsai** [comment]
Thanks for the reply. The scenario is a little different. what I want to do is:
To make a call to cancel and restart the parent dialog "/inquery" from inside child dialog "/confirm".

According to the documentation, cancelDialog "Cancels an existing dialog and optionally starts a new one it its place."
Before calling session.cancelDialog, the state stack is "/root -> /inquery -> /confirm".
If I called session.cancelDialog('/confirm', '/inquery'), the stack would become
"/root -> /inquery -> /inquery", which is not correct.
If I called session.replaceDialog('/inquery'), the stack would also become "/root -> /inquery -> /inquery".

Is there anyway I can cancel a parent dialog from inside one of its child dialog correctly?
Thanks for the help :)

**Comment by tahsintahsin** [comment]
If you start /inquiry by session.beginDialog('/inquiry') when you are in /confirm dialog, you will be redirected to /confirm only after inquiry finished, note that if there is no waterfall steps left in /inquiry that dialog(the one you refer as parent dialog) will finish as well. To create dialog loops you can use replaceDialog method. If you can write me the exact stack you want such as /confirm -> /inquiry -> /confirm -> /confirm etc, I might help better

**Comment by zytsai** [comment]
Thanks for the reply.
The scenario are broken into the following steps:

1. The stack before: /root -> /inquiry (old) -> /confirm (prompt the user to answer Y/N)
2. In dialog "/confirm", the User answers "N", to restart the inquiry process.
3. In dialog "/confirm", make some calls so that:
(a) Both the current dialog "/confirm" and its parent "/inquiry (old)" can be cancelled.
(b) Then a new dialog "/inquiry (new)" begins, just like calling replaceDialog(inquiry) in the waterfall of "/inquiry".
4. The stack after: /root-> /inquiry (new)

What should I do in step 3 to get the result?
Thanks for the help :)

**Comment by tahsintahsin** [comment]
In step 2, is the user says no, you can simply end the dialog by session.endDialog()  that would send you back to the last question in inquiry, or you can do session.replaceDialog('/inquiry') which would put you to question 1 of inquiry. 
I think can do session.reset() to clear the dialog stack,  as discussed in #101 . You can also try replace dialog with an extra argument passed, replaceDialog('/root', {return:"true"}), sth like that so that you can process this info in root and redirect the user to the necessary dialog. 
If you can add some code that would be much easier to understand

**Comment by Stevenic** [comment]
Sorry for the delay. If I recall I fixed a bug that might be related in v3.5 which we haven't release yet. Could you install b3.5 using `npm install --save botbuilder@next` and let me know if you still see the issue?

**Comment by zytsai** [comment]
This bug remains in v3.5.3.

If you dump out the internal dialog stack, you will found that all the dialogIds are automatically added the prefix "*:".

While methods like session.replaceDialog(dialogId) convert the input dialogId automatically and work well, It seems that session.cancelDialog(dialogId) doesn't handle the *FIRST* parameter in the same way. For example, to cancel the dialog "/intro" and replace it with "/menu", I need to call session.cancelDialog("*:/intro", "/menu") rather than session.cancelDialog("/intro", "/menu");

**Comment by Stevenic** [comment]
Good catch... I'll take a look at fixing the `cancelDialog()` method.

**Comment by nwhitmont** [comment]
Hi @zytsai - Did you try calling `session.startDialog()` instead of `session.cancelDialog()`? For example:
```javascript
bot.dialog('/confirm', [
   ...,
   function (session, result) {
     // redirect to /inquery dialog
      session.startDialog('/inquery');
   },
   ...
]);
```

**Comment by zytsai** [comment]
Hi @nwhitmont - there's no method named after "startDialog" in Session class.
ref. https://docs.botframework.com/en-us/node/builder/chat-reference/classes/_botbuilder_d_.session.html
ref. https://github.com/Microsoft/BotBuilder/blob/master/Node/core/src/Session.ts

**Comment by nwhitmont** [comment]
@zytsai my bad, I meant `session.beginDialog()` - example updated.

**Comment by nwhitmont** [comment]
@Stevenic any update on fixing `cancelDialog()` as described here?

**Comment by nwhitmont** [comment]
@zytsai can you include your complete code example that is causing the error?
