### ISSUE TITLE
Multiturn bot example quitting for no apparent reason 

### ISSUE THREAD

**Issue by Meai** [Microsoft/BotBuilder#16]
I only added a few intents and a single entity on luis.ai, (no code changes in the example .js!) and then when I type in *anything* the example just exits without an explanation or error code. 
That doesn't make sense to me, it should at least throw some kind of exception or explanation right? 
It should never just quit..

**Comment by Stevenic** [comment]
Did you deploy your own model? Could you email me your code? stevenic@microsoft.com

**Comment by Stevenic** [comment]
There was a bad URL for the model. I've checked in a fix. Sorry about that.

**Comment by Stevenic** [comment]
There was also a bug that an exception was being thrown by the LuisDialog that was being eaten and causing the app to close. I'm checking in a fix that causes the error to be thrown now.
