### ISSUE TITLE
Question: Is there any way to build conversation from a JSON file?

### ISSUE THREAD

**Issue by afficionaddo** [Microsoft/BotBuilder#1602]
Hi,

I am into an experiment but would like if I can get a first-hand info of whether it is possible in BotFramework.

I have a JSON file that contains conversation in form of Key-Value pair.

My aim is :

> to achieve integration of JSON file with BotFramework C# so that I can build a conversation from the JSON file directly.

You know like build a conversation from a rule-based system which will output a JSON file and then integrate the JSON file with the BotFramework.

Is this possible/ viable? I hope I am able to state my requirement clearly.

**Comment by tomlm** [comment]
Sure, just load your data and do a for loop around it.

**Comment by afficionaddo** [comment]
Thnx for the reply @tomlm .

But I am unable to comprehend your point. 'For' loop for what operation?

See my json file will be a key-value pair like:

{"What is my name": "My name is Russell.", "Where do you live": "I live in Canada"}

So what I am trying to accomplish is to load this JSON as a conversation.
Is it viable / possible?

Looking forward to your reply.
