### ISSUE TITLE
Carousel in KiK

### ISSUE THREAD

**Issue by s-rya** [Microsoft/BotBuilder#1603]
Hi,

Does bot framework support carousels in KiK ?

Because i can see that a single card like Hero card works properly in KiK. But for carousel with buttons doesn't work properly in KiK.

I am using NodeJs SDK. And here is the code which i used to create carousel

 var msg = new builder.Message(session)
            .textFormat(builder.TextFormat.xml)
            .attachmentLayout(builder.AttachmentLayout.carousel)
            .attachments([ <New Hero card>])

Am i missing something?

**Comment by willportnoy** [comment]
@LarsLiden @eanders-MS can you help?

**Comment by LarsLiden** [comment]
Looking....

**Comment by chrimc62** [comment]
Closing due to age and answer.
