### ISSUE TITLE
Missing share button type

### ISSUE THREAD

**Issue by scibol** [Microsoft/BotBuilder#1604]
Hi,

I'm referencing this: https://developers.facebook.com/docs/messenger-platform/send-api-reference/share-button

```
  buttons: 
  [ 
     { type: 'element_share' }
  ]
```

If I try to add a button with type "element_share" I get:
Error: Request to 'https://facebook.botframework.com/v3/conversations/.../activities/...' failed: [500] Internal Server Error

**Comment by chrimc62** [comment]
@dandriscoll or @LarsLiden is this known?

**Comment by LarsLiden** [comment]
This functionality is specific to Facebook, so it should be sent using SourceEvent.   See example at #1714
