### ISSUE TITLE
Microsoft Team channel documentation.

### ISSUE THREAD

**Issue by james-lawrence** [Microsoft/BotBuilder#1606]
First off this may be the wrong place to file the issue. =)

This is actually just a few general issues with the bot framework.

General problem: there is no way to see what the channel name and the serviceURL is from the bot administration page. https://dev.botframework.com/bots
General problem: curling the swagger.json file contains invalid utf8 characters.

I've been trying to send a message to a user directly without first receiving a message and its an absolutely bear to figure out what I am doing wrong.

Issues I'm running into:
- Microsoft Team channel has no documentation for serviceURL, channel name.
- the test link `add to teams` at https://dev.botframework.com/bots causes the android application to crash. (this is the only system I have direct access to that has a native client, rest of my machines are linux)

As a result I'm currently using the skype channel and sent myself a test message.
unfortunately also hitting issues with the skype channel.

Problem 1)
CreateConversation returns an invalid ID:
```
POST /v3/conversations HTTP/1.1
Host: skype.botframework.com
User-Agent: Go-http-client/1.1
Content-Length: 123
Accept: application/json
Accept: application/xml
Accept: text/json
Accept: text/xml
Content-Type: application/json
Accept-Encoding: gzip

{"bot":{"id":"28:ac001848-d8bf-4c9e-ab86-744cc0926a9e"},"members":[{"id":"8:orgid:c3ec28d6-7188-45ec-996a-1e9341a6e307"}]}

```
result:
```
2016/11/08 10:48:05 HTTP/1.1 200 OK
Cache-Control: no-cache
Content-Type: application/json; charset=utf-8
Date: Tue, 08 Nov 2016 15:48:04 GMT
Expires: -1
Pragma: no-cache
Server: Microsoft-IIS/8.0
Strict-Transport-Security: max-age=31536000
Vary: Accept-Encoding
X-Powered-By: ASP.NET

{
  "id": "8:orgid:c3ec28d6-7188-45ec-996a-1e9341a6e307"
}
```
the id in the result is incorrect, when I receive a message by talking to my bot from https://teams.microsoft.com the conversation ID is: `19:c3ec28d6-7188-45ec-996a-1e9341a6e307_ac001848-d8bf-4c9e-ab86-744cc0926a9e@unq.gbl.spaces`

Problem 2)
the conversation id returned by the api doesn't work:
```
POST /v3/conversations/8:orgid:c3ec28d6-7188-45ec-996a-1e9341a6e307/activities HTTP/1.1
Host: skype.botframework.com
User-Agent: Go-http-client/1.1
Content-Length: 488
Accept: application/json
Accept: text/json
Content-Type: application/json
Accept-Encoding: gzip

{"attachments":null,"channelId":"skype","conversation":{"id":"8:orgid:c3ec28d6-7188-45ec-996a-1e9341a6e307"},"entities":null,"from":{"id":"28:ac001848-d8bf-4c9e-ab86-744cc0926a9e"},"localTimestamp":"2016-11-08T11:12:33.186-05:00","membersAdded":null,"membersRemoved":null,"recipient":{"id":"8:orgid:c3ec28d6-7188-45ec-996a-1e9341a6e307"},"serviceUrl":"https://skype.botframework.com","text":"Hello World","textFormat":"plain","timestamp":"2016-11-08T11:12:33.186-05:00","type":"message"}
```
```
2016/11/08 11:12:34 HTTP/1.1 504 Gateway Timeout
Content-Length: 63
Cache-Control: no-store, must-revalidate, no-cache
Content-Type: application/json; charset=utf-8
Contextid: tcid=840322408452879144,server=EAP010201024144
Date: Tue, 08 Nov 2016 16:12:34 GMT
Pragma: no-cache
Server: Microsoft-IIS/8.0
Strict-Transport-Security: max-age=31536000
X-Powered-By: ASP.NET

{"errorCode":507,"message":"Agent relationship lookup failed."}
```

Problem 3)
When attempting to call SendToConversation using the message's recipient/conversation information from when I sent my bot a test message:
```POST /v3/conversations/8:orgid:c3ec28d6-7188-45ec-996a-1e9341a6e307/activities HTTP/1.1
Host: skype.botframework.com
User-Agent: Go-http-client/1.1
Content-Length: 530
Accept: application/json
Accept: text/json
Content-Type: application/json
Accept-Encoding: gzip

{"attachments":null,"channelId":"skype","conversation":{"id":"19:c3ec28d6-7188-45ec-996a-1e9341a6e307_ac001848-d8bf-4c9e-ab86-744cc0926a9e@unq.gbl.spaces"},"entities":null,"from":{"id":"28:ac001848-d8bf-4c9e-ab86-744cc0926a9e"},"localTimestamp":"2016-11-08T11:09:19.301-05:00","membersAdded":null,"membersRemoved":null,"recipient":{"id":"8:orgid:c3ec28d6-7188-45ec-996a-1e9341a6e307"},"serviceUrl":"https://skype.botframework.com","text":"Hello World","textFormat":"plain","timestamp":"0001-01-01T00:00:00.000Z","type":"message"}
```
the following response is returned:
```
2016/11/08 10:59:07 HTTP/1.1 504 Gateway Timeout
Content-Length: 63
Cache-Control: no-store, must-revalidate, no-cache
Content-Type: application/json; charset=utf-8
Contextid: tcid=6982294149877090693,server=EAP010201024144
Date: Tue, 08 Nov 2016 15:59:07 GMT
Pragma: no-cache
Server: Microsoft-IIS/8.0
Strict-Transport-Security: max-age=31536000
X-Powered-By: ASP.NET

{"errorCode":507,"message":"Agent relationship lookup failed."}
```

**Comment by chrimc62** [comment]
@tomlm could you help?

**Comment by celloudiallo** [comment]
is this related to this other issue i created here https://github.com/Microsoft/BotBuilder/issues/1848?

Been fighting with this Gateway Timeout and would really appreciate to know that this is actually being looked at.

**Comment by RichMoeMSFT** [comment]
Regarding issue #1, neither CreateConversation nor CreateDirectConversation are supported in Teams right now.  We should have updated information in the next month or so.

**Comment by devand123** [comment]
@RichMoeMSFT Has support for this been added yet?

**Comment by celloudiallo** [comment]
I don't think so, what i ended up doing was saving the redemptionCookie from the activity and reuse that to get the conversation ID when i want to later message the user.

**Comment by RichMoeMSFT** [comment]
Support for creating a new DM in Teams is in final testing right now and should be available soon.
