### ISSUE TITLE
Skype Texting / Nodejs: Session.send returns error

### ISSUE THREAD

**Issue by austinhuang0131** [Microsoft/BotBuilder#1607]
My script is:
```js
bot.dialog('/', function (session) {
    console.log(session);
    session.send("Test");
});
```
Output:
```
(node:284617) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.
Session { ...
```
* TLDR: Can receive Skype message but cannot reply
* However, it replies in GroupMe
* #1133 ?

**Comment by austinhuang0131** [comment]
Also here's [a solution](https://github.com/neumino/rethinkdbdash/pull/307) from another repo. I couldn't see anywhere I can apply that solution (I'm just beginner ^^;) so I think it might be useful for reference.

**Comment by chrimc62** [comment]
@Stevenic or @maxpert can you help?
@austinhuang0131 are you still having an issue?

**Comment by Stevenic** [comment]
I looked and we use `new Buffer()` in our code so it must be something under us. Not sure how to narrow down where it is.

**Comment by tahsintahsin** [comment]
Have the same warning message in each conversation with our bot

**Comment by Stevenic** [comment]
Unfortunately this looks to be in a support library so not sure how we'd address it. I'm going to tag it for further investigation.

**Comment by nwhitmont** [comment]
@Stevenic when you say "this looks to be in a support library" what do you mean exactly? What library?

**Comment by nwhitmont** [comment]
@austinhuang0131 reopen if you are still experiencing the issue.
