### ISSUE TITLE
Slack conversationUpdate has incorrect user

### ISSUE THREAD

**Issue by euanlau** [Microsoft/BotBuilder#1608]
The `address` property of the `conversationUpdate` event contains incorrect `user` value.
e.g. When I add the bot to a channel, I expect to see myself in the `user` field since I am the actor. However, the property contains the bot itself.
This applies to both `membersAdded` and `membersRemoved`.

BotBuilder version 3.2.3
Platform: NodeJS

**Comment by austinhuang0131** [comment]
`conversationUpdate` is [ONLY for Skype](https://docs.botframework.com/en-us/skype/chat/#conversation-update). [This](https://api.slack.com/events/team_join) is the slack one.
* Slack does NOT allow leaving servers (even you can deactivate your account)
* Slack does NOT have event for someone else joining/leaving a private channel.

Correct me if I am wrong.

**Comment by euanlau** [comment]
@austinhuang0131 No. Both `membersAdded` and `membersRemoved` do work on Slack. The only thing that is incorrect is the `user` field.  `membersRemoved` did not work properly but it has been fixed in https://github.com/Microsoft/BotBuilder/issues/1365 .

**Comment by euanlau** [comment]
@austinhuang0131 
* Slack does NOT allow leaving servers 
Not sure what you meant here. But I am able to trigger `membersRemoved` by removing the bot from a channel.

* Slack does NOT have event for someone else joining/leaving a private channel.
This issue has nothing to do with whether the channel is public or private, but Slack DOES HAVE event for that. It is just about getting the right oauth permission.

**Comment by austinhuang0131** [comment]
@euanlau 
* Slack does not really allow users leaving servers. I forgot to exclude bots.
* OAuth...ok but it's not in RTM/events API.

I am sorry for any inconvenience that might brought.

**Comment by euanlau** [comment]
@austinhuang0131 

* Slack allows users to leave channel, not just bots.  Please note that I am talking about `coversationUpdate`, not `contactUpdate`.  I don't exactly know what you meant by`servers`.  It has nothing to do with this issue. 

* Please read https://api.slack.com/rtm. What you said is part of RTM/events API. OAuth is for getting the permission to use RTM/events API. Please do not get confused. 

Anyway, what you said has nothing to do with this issue. I am waiting for the Microsoft folks to provide feedbacks on this.

**Comment by craigjensen** [comment]
The raw Slack message should be passed in the sourceEvent property and contains the inviter and other properties you are referring to.

**Comment by euanlau** [comment]
The Slack message does not contain the inviter. It only contains the `channel` property. So I guess Slack does not provide the inviter information at all. So there is no way for the botframework to pass that information to the clients.
