### ISSUE TITLE
Can not go to next step in waterfall flow when send an attachment message

### ISSUE THREAD

**Issue by astrung** [Microsoft/BotBuilder#1610]
Example code :
 
    bot.dialog('/', [
      function (session) {
        var card = new builder.HeroCard(session);
        card.title("hello");
        var msg = new builder.Message(session).attachments([card]);
        session.send(msg);
      }, function (session, results) {
        session.send("end");
        session.endDialog();
      }
    ]);

After i send a new message to bot after "hello" message , bot never send "end" message . It always continue to send "hello" message . How can i go to next flow ? 

( I know that we can go to next flow by using Prompts, but in my case , i need send an attachment )

**Comment by Stevenic** [comment]
You can use the `next()` function to manually advance the waterfall:

```
bot.dialog('/', [
  function (session, args, next) {
    var card = new builder.HeroCard(session);
    card.title("hello");
    var msg = new builder.Message(session).attachments([card]);
    session.send(msg);
    next();
  }, function (session, results) {
    session.send("end");
    session.endDialog();
  }
]);
```

But why wouldn't you just combine the two steps?

```
bot.dialog('/', [
  function (session) {
    var card = new builder.HeroCard(session);
    card.title("hello");
    var msg = new builder.Message(session).attachments([card]);
    session.send(msg);
    session.send("end");
    session.endDialog();
  }
]);
```

**Comment by astrung** [comment]
I want to send "end" message after response from "hello" message.
By using `next()`, bot will send "end" message immediately after "hello" message

**Comment by astrung** [comment]
I tried to use `builder.Prompts.text(session, msg);` with an attachments. And i get this error : 

    Error: Data of 69461 bytes exceeds the 65000 byte limit. Consider setting connectors gzipData option. Can't post to

**Comment by Stevenic** [comment]
You're storing something big in `dialogData` which is why you're getting that error. What are you storing?

**Comment by astrung** [comment]
This bug is fixed now. I stored all data i get from database . It is ok now. But it is still can not send "end" message for response for "hello" message.

**Comment by Stevenic** [comment]
To wait for a response from the user you should use a prompt.  You can simply use `Prompts.text()` instead of `session.send()`.  You can send the exact same message using Prompts.text().

**Comment by astrung** [comment]
Ok

**Comment by Nisthar** [comment]
@Stevenic How to get the response from a herocard button in the next waterfall?
