### ISSUE TITLE
Microsoft Teams emoji bug

### ISSUE THREAD

**Issue by wiltodelta** [Microsoft/BotBuilder#1611]
Hi!

Microsoft Teams on desktop (Win + Mac) has problems with displaying emoji.

Teams:

<img width="440" alt="screen shot 2016-11-09 at 08 05 43" src="https://cloud.githubusercontent.com/assets/1192743/20127800/bc8e954c-a653-11e6-8ecd-4c478c6828c1.png">

Skype:

<img width="315" alt="screen shot 2016-11-09 at 08 08 09" src="https://cloud.githubusercontent.com/assets/1192743/20127801/c0868f38-a653-11e6-9d7a-c0ba7b4776d2.png">

**Comment by chrimc62** [comment]
@dandriscoll can you assign this to someone on Teams?

**Comment by RichMoeMSFT** [comment]
Just wanted to offer a quick follow up:  Teams does not currently support emojis, but it is on the backlog.

**Comment by dandriscoll** [comment]
Closing as this is not currently supported. If you want to discuss further, feel free to at-mention or open a new issue.
