### ISSUE TITLE
Microsoft Teams order bug

### ISSUE THREAD

**Issue by wiltodelta** [Microsoft/BotBuilder#1612]
There are problems with repeated messages and order of messages in the chat.

Skype:

<img width="771" alt="screen shot 2016-11-09 at 08 23 38" src="https://cloud.githubusercontent.com/assets/1192743/20128033/0da1f832-a656-11e6-9a96-7b8e85f22d4a.png">

Teams:

<img width="891" alt="screen shot 2016-11-09 at 08 23 49" src="https://cloud.githubusercontent.com/assets/1192743/20128034/0da27e6a-a656-11e6-818e-18a44d24e9f6.png">

**Comment by chrimc62** [comment]
I believe this is a known issue, @tomlm ?

**Comment by RichMoeMSFT** [comment]
This issue was fixed and deployed several weeks ago.
