### ISSUE TITLE
Pass arguments to builder.Prompts

### ISSUE THREAD

**Issue by astrung** [Microsoft/BotBuilder#1615]
We can pass arguments to text message when using session.send:

    session.send("ask_address", session.userData );

But can not pass arguments when using Prompts: 

    builder.Prompts.text(session, "ask_address", session.userData );

I can not use "String.replace", when "ask_address" message is multi - language with `session.preferLocale` . How can we pass arguments to Prompts ?

**Comment by palmerabollo** [comment]
You can use `session.gettext` to pass arguments to your text messages.

```
var message = session.gettext("ask_address", argument1, argument2);
builder.Prompts.text(session, message);
```

I hope that helps.

**Comment by astrung** [comment]
Thanks
