### ISSUE TITLE
Use facebook messenger platform 1.3 features

### ISSUE THREAD

**Issue by seb0zz** [Microsoft/BotBuilder#1616]
Hi,

is there any chance to use https://developers.facebook.com/docs/messenger-platform/send-api-reference/list-template right now with the Microsoft BotBuilder?

**Comment by willportnoy** [comment]
As a temporary workaround, you should be able to use the ChannelData/SourceEvent field to send the native message format for the Facebook channel.

**Comment by chrimc62** [comment]
Question was answered and is entered in TFS, so closing for age.
