### ISSUE TITLE
Directline GET API - delay in getting Message from Bot

### ISSUE THREAD

**Issue by senthil2m** [Microsoft/BotBuilder#1618]
Hi,

After posting message successfully to the bot using Directline POST API from the Android client app,  I can get the reply message from the bot if I make Directline GET API call only after 7 seconds. This happens even if the bot simply replies back without any complex logic/server call in it.
I would like to know how can this issue be fixed ? 
I have also seen an issue related to this in the forum #1297 but the issue was closed mentioning that they are working on it. I would like to know the status of this issue.
Please update.

Thanks,
Senthil M

**Comment by palmerabollo** [comment]
@senthil2m There are many issues related with latency in the Direct Line.
Check dandriscoll's answer here: https://github.com/Microsoft/BotBuilder/issues/915 and also take a look at https://github.com/Microsoft/BotBuilder/issues/1413 and https://github.com/Microsoft/BotBuilder/issues/1144.

AFAIK they already have it running in datacenters all around the globe. Where is your bot deployed? Can you try to deploy it on Azure to verify if the latency gets reduced?

**Comment by senthil2m** [comment]
@palmerabollo Issue occurs in the Bot deployed in Azure, located in South India.

**Comment by dandriscoll** [comment]
Hi @palmerabollo, can you send an example conversation ID where you're seeing this and I can look to see where the time is spent?

**Comment by chrimc62** [comment]
Closing due to lack of response.  If you still have an issue, please let us know.

**Comment by senthil2m** [comment]
I have tested even today with the REST3.0 Directline API client. I got the responses with the delay of 7 to 8 seconds.
Please find the details below for further investigation.
Bot App ID : 4fcd0d6f-20f1-43be-9bd7-233db6ad0b1e
ConversationID : Dpcn6aeHJPn

**Comment by sayyednazeer** [comment]
#2078
