### ISSUE TITLE
Whenever I send a message to bot it gives the error, "emulator.service is being used by another application"

### ISSUE THREAD

**Issue by Nexaller** [Microsoft/BotBuilder#1619]
The framework emulator opens up fine but whenever I try to send a message to it, it gives me this error:

"The process cannot access the file
'C:\Users\techk\AppData\Local\Temp\emulator.service' because it is being used by another process"

**Comment by willportnoy** [comment]
I wonder if you might use http://live.sysinternals.com/procexp.exe and Find, "Find Handle or DLL" to find which process is using that folder.

**Comment by Nexaller** [comment]
It says there is no processes using that file. What should I try now?

**Comment by chrimc62** [comment]
We have released a new version of the emulator, please let us know if you still have the issue.
