### ISSUE TITLE
About BotBuilder.EntityRecognizer.findEntity

### ISSUE THREAD

**Issue by loretoparisi** [Microsoft/BotBuilder#162]
I have a entity that is composed by more words like `neil young`.

Dumping the `args` in dialog callback `function (session, args, next)`

I get 

```json
"entities": [
    {
      "entity": "neil",
      "type": "ArtistName",
      "startIndex": 9,
      "endIndex": 12,
      "score": 0.94491
    },
    {
      "entity": "young",
      "type": "ArtistName",
      "startIndex": 14,
      "endIndex": 18,
      "score": 0.889128566
    }
  ]
```

but when I use the api `BotBuilder.EntityRecognizer.findEntity`, I get only the first one:

```javascript
var entities = {};
entities.artistName = BotBuilder.EntityRecognizer.findEntity(args.entities, Entity.Type.ArtistName);
console.log( entities );
```

```json
{
  "artistName": {
    "entity": "neil",
    "type": "ArtistName",
    "startIndex": 9,
    "endIndex": 12,
    "score": 0.94491
  }
}
```

I expected the retrieve the whole entity as was typed by the user in the utterance since the train I had recognized the composed words as a `ArtistName` entity.
So, how to get that one i.e. `neil young` via api?

**Comment by loretoparisi** [comment]
In the meanwhile I'm going to do like

```javascript
function findEntity(entities, type) {
    return entities.filter(function(item, index) {
        return item.type == type;
    }).reduce(function(acc, curr) {
        return (acc += ' ' + curr.entity).trim();
    }, '');
}
```

So that I can do

```javascript
var artistName=findEntity(args.entities,'ArtistName')
```
to get back `neill young` correctly trimmed and space.

**Comment by Stevenic** [comment]
You should use EntityRecognizer.findAllEntities() to get all of the entities for a given type back. The thing is it sounds like you've trained your model to recognize "neil" and "young" as two separate entities in the utterance "play neil young". I would have thought that you'd want to have trained the model to return "neil young" as a single entity called ArtistName so that you don't have to manually stitch the name together on your end.

**Comment by loretoparisi** [comment]
@Stevenic Thank you. I will go with the `EntityRecognizer.findAllEntities()`.
Regarding the entities, maybe I'm wrong about how to do this, Look here:

![schermata 2016-04-22 alle 09 27 35](https://cloud.githubusercontent.com/assets/163333/14734726/bac54d6c-086c-11e6-9414-20003f087e46.jpg)

I get the two words in `yellow` that is the `ArtistName` entity, buy I'm not sure if this means that the classifier considers it a single entity value. How to check this?

**Comment by Stevenic** [comment]
So when you see that in LUIS what you can do is click "neil" & "young" to remove the annotation and then click "neil" again and while holding down the mouse button drag to the right to have it highlight "niel young" as one single entities. You can then set that to be type ArtistName.

**Comment by ArtriciaDM** [comment]
Thanks

Artricia Harris

**Comment by loretoparisi** [comment]
@Stevenic ok that is not so user-friendly,
![schermata 2016-04-26 alle 14 11 06](https://cloud.githubusercontent.com/assets/163333/14817643/c57f4a74-0bb8-11e6-936c-f68554c4029d.jpg)
I got it.

**Comment by Stevenic** [comment]
Agreed that it's not always intuitive but it does work.
