### ISSUE TITLE
InternalServerError - Cannot use Emulator to debug

### ISSUE THREAD

**Issue by suvamsh** [Microsoft/BotBuilder#1622]
My bot works error free when I use the ConsoleConnector but when I use the ChatConnector and publish to Azure I get "InternalServerError". The problem is that I am developing in Node on a Mac and cannot use the Bot framework Emulator. Is there any suggestions as to how I can debug this? I have errors only in the deployed version, I would like to debug the web app which I deployed on Azure.

**Comment by willportnoy** [comment]
There is a cross-platform emulator:
https://docs.botframework.com/en-us/tools/bot-framework-emulator/#mac-and-linux-support-using-command-line-emulator

You might also consider enabling Azure App Insights on your deployed bot to get trace logs and other diagnostics information.

**Comment by suvamsh** [comment]
I installed this and I am able to debug locally emulating a server. But my Azure endpoint is still saying "InternalServerError" when I try to ping it from the botframework Bot page. Is there anyway I can debug the web endpoint directly?

**Comment by willportnoy** [comment]
You might consider following a guide like the following:
https://azure.microsoft.com/en-us/documentation/articles/web-sites-nodejs-debug/

**Comment by suvamsh** [comment]
Thanks I was able to fix my error.
