### ISSUE TITLE
System.NullReferenceException when testing bot

### ISSUE THREAD

**Issue by enzofab91** [Microsoft/BotBuilder#1623]
I'm getting this error when trying to test my bot into the dashboard.

Now it’s working local and in a server by using the bot emulator.

The full stack trace is this:

InternalServerError
{
  "message": "An error has occurred.",
  "exceptionMessage": "Referencia a objeto no establecida como instancia de un objeto.",
  "exceptionType": "System.NullReferenceException",
  "stackTrace": "   en Microsoft.Bot.Connector.ConversationsExtensions.ReplyToActivityAsync(IConversations operations, Activity activity, CancellationToken cancellationToken)\r\n   en BotPrueba.MessagesController.<Post>d__1.MoveNext()\r\n--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---\r\n   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   en System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()\r\n--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---\r\n   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   en System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---\r\n   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   en System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---\r\n   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   en System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()\r\n--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---\r\n   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   en System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"
}

**Comment by willportnoy** [comment]
Do you construct the activity from Activity.CreateReply or IBotToUser.MakeMessage?  It will ensure all of the proper fields are initialized.

**Comment by enzofab91** [comment]
It's working now, I have forgotten to create a reply to ping. Thanks

**Comment by willportnoy** [comment]
I'd suggest going through this link to diagnose authentication issues:
https://docs.botframework.com/en-us/support/troubleshooting-bot-framework-authentication/#navtitle

**Comment by chrimc62** [comment]
Closing due to lack of response.  If you still have the issue, please let us know.
