### ISSUE TITLE
Make the documentation open for contribution

### ISSUE THREAD

**Issue by Deilan** [Microsoft/BotBuilder#1624]
Since some articles in [documentation](https://docs.botframework.com/en-us/) became a bit outdated and some source code from it is unable to be executed right after copy-pasting, it is proposed to make the documentation open for contribution by community members.

**Comment by willportnoy** [comment]
I believe the documentation is backed by this branch:
https://github.com/Microsoft/BotBuilder/tree/gh-pages

**Comment by Deilan** [comment]
Then it is proposed to post some sort of announce/invitation at the documentation pages which states that the documentation is opened for updating by community members and contributions are welcomed - in a similar fashion it is done at docs.asp.net:
![untitled](https://cloud.githubusercontent.com/assets/4777512/20172979/596f78e6-a748-11e6-97a8-c7fc93609250.png)

**Comment by willportnoy** [comment]
I understand - I've added this request to our internal backlog.

**Comment by willportnoy** [comment]
I've added this item to our internal backlog.
