### ISSUE TITLE
Form Flow validate a Name c#

### ISSUE THREAD

**Issue by alokraj68** [Microsoft/BotBuilder#1627]
Hi, I have used Numeric attribute of Form flow.
Found that we can use Regex to validate things.
But am not clear how to do this and on what extend we can do this.
is it possible to create a regex so that only input with above 1 alphabet is accepted without any symbols?

Help me out!

**Comment by willportnoy** [comment]
Are you asking how to create this regex?  You might consider using character classes:
https://msdn.microsoft.com/en-us/library/20bw873z(v=vs.110).aspx

**Comment by alokraj68** [comment]
Okays, i did another way out. Would paste the code soon.

**Comment by alokraj68** [comment]
used this regex to clear all symbols except underscore.

```
state.Name = Regex.Replace(state.Name, @"[^\w\s]", string.Empty);
                state.Name = state.Name.Trim();
```
