### ISSUE TITLE
How to get conversation details in microsoft bot framework for channels?

### ISSUE THREAD

**Issue by jagdish-176** [Microsoft/BotBuilder#1628]
I'm able to get conversation details for webchat using https://webchat.botframework.com/api/conversations/[conversationId]/messages

How to get conversation details for other channels like skype, groupme etc.?

**Comment by dandriscoll** [comment]
Hi @jagdish-176, are you looking for log of all messages? If so, most channels do not support this operation. Direct Line and Web Chat are the only ones I know of.
