### ISSUE TITLE
Conversation restarts for user when load increases. c# Idailog context.wait()

### ISSUE THREAD

**Issue by alokraj68** [Microsoft/BotBuilder#1629]
Hi,
We did a load test of our bot today.
what we found out is that when the number of users go above a level, the `converstaion.wait()` points resets and the bot starts from beginning of message received .
In other words the bot starts from the first point of the waterfall model.
Is this a bug? 
And also, when restarted, it takes to 3 times to get of the restore, that is next 2 msgs from user will end up in the same beginning point only. after that it will resume normally.

**Comment by willportnoy** [comment]
You might want to read this for background information:
https://docs.botframework.com/en-us/technical-faq/#where-is-conversation-state-stored

Are you sending multiple concurrent messages for a given user?

**Comment by alokraj68** [comment]
Hi,am using a idaolg extended classes inorder to make a set of conversation. Then navigate from one to another as per user replies. When i wait for a user reply using context.wait in an idalog extended class, the bot resets automatically and starts from beginning. That is the issue.

**Comment by chrimc62** [comment]
@willportnoy is there anything else we can do here?

**Comment by willportnoy** [comment]
These faqs have more information on the bot state service's update conflict model:

https://docs.botframework.com/en-us/technical-faq/#what-causes-precondition-failed-412-or-conflict-409-http-errors
https://docs.botframework.com/en-us/technical-faq/#how-can-i-fix-precondition-failed-412-or-conflict-409-http-errors

**Comment by alokraj68** [comment]
@willportnoy the issue is with skype only. in facebook it works perfect. in Direct chat also there is no issue.

**Comment by willportnoy** [comment]
@alokraj68 the state service for all channels is the same, as far as I know.  Perhaps there is a timing issue across different channels that exposes some issue related to the state service?

**Comment by alokraj68** [comment]
@willportnoy  I did a thorough check with same traffic in order o know that.

What we observed is that once the number of users rises with skype it breaks conversations from one side and the user session keeps resetting to start. in direct chat and facebook, the user session tokens are kept intact that nothing goes wrong. facebook and direct chat can have this for a pretty long time.

**Comment by willportnoy** [comment]
@alokraj68 are there any exceptions that only occur on the skype channel?  Perhaps an unhandled exception is resetting the conversation.

**Comment by alokraj68** [comment]
@willportnoy we could not find any such exceptions. I did a thorough check after you talked about exceptions.

**Comment by Muthuprasanth** [comment]
@alokraj68 
I have the same issue in Skype. When user sends voice recording in Skype, it is stored in a particular place in .m4a format. I read the file as Buffer and convert to .wav format and then create a .wav file from it. And then I send this .wav file to Bing speech api and it returns the corresponding text. When the user starts sending voice recordings for the first time, it works properly. But when the user sends next voice recordings,  the conversation starts from the beginning. I am using node.js. Did you resolve the issue @alokraj68 ?
