### ISSUE TITLE
Card - access it on (skype download url)  in Skype c#

### ISSUE THREAD

**Issue by alokraj68** [Microsoft/BotBuilder#1630]
Hi,
At certain points of conversation when the user loads increase, skype start showing Card - access it on (skype download url)

Why is this happening?
Is this not a bug
Observed only in Mobile versions (IOS,Android)

**Comment by nickcordrey** [comment]
This is a bug and is being investigated.

**Comment by chrimc62** [comment]
@nickcordrey was there ever a resolution?

**Comment by nickcordrey** [comment]
This should no longer be happening. Please re-open if you see it reoccur.

**Comment by alokraj68** [comment]
@nickcordrey was this issue resolved by the skype team?!

**Comment by thedotedge** [comment]
Curious to know what was the culprit as well.
