### ISSUE TITLE
LUIS and topScoringIntent in the response

### ISSUE THREAD

**Issue by pveller** [Microsoft/BotBuilder#1633]
LUIS started sending back a JSON that latest Bot Framework 3.4.4 (node.js) does not seem to be equipped to deal with.

I am getting back:

```javascript
{
    entities: [],
    intent: [],
    query: 'users utterance here',
    topScoringIntent: {
        intent: 'Recognized Intent',
        score: 0.92
    }
}
```

The code in `LuisRecognizer.js` expects that all intents will be in the `intents` array. The logic goes to inspect it and find the top scoring one and that one will go onto the top level `intent` and `score` of the `result` object. No code branch is looking for `topScoringIntent`.

What am I missing?

**Comment by jphgross** [comment]
We're seeing this as well. Looks like the LUIS upgrade broke the LUIS dialog.

**Comment by pveller** [comment]
Alright. I will just build my own then. It's a very simple HTTP/JSON interface. I am using other recognizers of my own anyway. Or maybe I should submit a PR? Do you guys accept external contributions?

**Comment by jphgross** [comment]
I don't appear to have the ability to issue a pull request so here's a patch that worked for me.

diff --git a/Node/core/lib/dialogs/LuisRecognizer.js b/Node/core/lib/dialogs/LuisRecognizer.js
index 1a2b191..2f3ec60 100644
--- a/Node/core/lib/dialogs/LuisRecognizer.js
+++ b/Node/core/lib/dialogs/LuisRecognizer.js
@@ -69,8 +69,13 @@ var LuisRecognizer = (function () {
                         result = JSON.parse(body);
                         result.intents = result.intents || [];
                         result.entities = result.entities || [];
-                        if (result.intents.length == 1 && typeof result.intents[0].score !== 'number') {
-                            result.intents[0].score = 1.0;
+
+                        if(result.topScoringIntent){
+                            result.intents[0] = result.topScoringIntent;
+                        }else{
+                            if (result.intents.length == 1 && typeof result.intents[0].score !== 'number') {
+                                result.intents[0].score = 1.0;
+                            }
                         }
                     }
                 }

**Comment by pveller** [comment]
@jphgross, yep. makes sense. I would then need to carry the patched module all the way to the target deployment environment (Heroku or Azure in my case). Right?

**Comment by pveller** [comment]
I ended up with a slightly different patch:

```javascript
if (!err) {
    result = JSON.parse(body);
    result.intents = result.intents || [];
    result.entities = result.entities || [];
    // <-- FIX: 1633
    if (result.topScoringIntent) {
        result.intents.unshift(result.topScoringIntent);
    }
    // <-- END FIX: 1633
    if (result.intents.length == 1 && typeof result.intents[0].score !== 'number') {
        result.intents[0].score = 1.0;
    }
}
```

**Comment by nicoschmitt** [comment]
I've just spend 1 hour trying to understand why Luis did not pick what I was saying... Until I look at the source and found that. Is it because Luis change api version to v2?

**Comment by Stevenic** [comment]
So you can fix this for now by adding "&verbose=true" to the end of the new URL. We'll have an official patch soon.

**Comment by Stevenic** [comment]
Sorry about the break everyone... We knew this was coming but there was some confusion on the when part.

**Comment by Stevenic** [comment]
There's a fix checked in which will be in the next release due out very soon.

**Comment by Stevenic** [comment]
You can get the fix now by installing the prerelease version of botbuilder:

```
npm install --save botbuilder@next
```

**Comment by VishalWaman** [comment]
Yes this works

**Comment by ChandrikaC** [comment]
Thanks everyone.. saved my day

**Comment by Stevenic** [comment]
The update with the patch should be released soon.

**Comment by chrimc62** [comment]
@Stevenic or @maxpert was this released?

**Comment by BlueHatbRit** [comment]
Just caused me an hour of debugging to find the same results as the guys above. Added the verbose url addition and it's fine now. Thanks for the fix, any idea when the release will be out for this?

**Comment by Stevenic** [comment]
Very soon... We're having to sync the release with some other changes so just in a holding pattern on the SDK side of things.

**Comment by Stevenic** [comment]
This should be fixed now. Please let me know if it's still an issue.
