### ISSUE TITLE
Localization not working for prompt with 2 items on web chat

### ISSUE THREAD

**Issue by bertique** [Microsoft/BotBuilder#1634]
I'm writing a bot using the Node sdk with a web widget front end.

For prompts with two choices, the web client doesn't properly display the options. It works for items with more options

**code:**
builder.Prompts.choice(session, "Do you like pizza?", ["Yes, thank you","No, I hate it"]);

**web widget:**
Do you like pizza? (1. Yes, thank you**list_or**2. No, I hate it)

It looks like it's not pulling the localized string for 'or'

**Comment by palmerabollo** [comment]
@bertique which botbuilder version are you using? 3.4.4?
The key "list_or" is in the [BotBuilder.json file](https://github.com/Microsoft/BotBuilder/blob/master/Node/core/lib/locale/en/BotBuilder.json#L5).

**Comment by bertique** [comment]
Yes, I'm on 3.4.4

It seems to be an issue with the web widget, since it's working fine in the emulator

**Comment by bertique** [comment]
Moved to https://github.com/Microsoft/BotFramework-WebChat/issues/162 since this seems to be a web chat issue

**Comment by bertique** [comment]
Looks like this is an issue in the BotBuilder framework after all

**Comment by bertique** [comment]
Okay seems to be fixed after updating to the latest botbuilder

**Comment by palmerabollo** [comment]
@bertique 3.4.4 is the latest, right?

**Comment by bertique** [comment]
Yes, I was just testing on 3.4.2, and also there it's fixed

**Comment by bertique** [comment]
@palmerabollo, yes you are right. Sorry, I was actually on 3.3.3 earlier. That was the problem
