### ISSUE TITLE
SigninCard does not work in Skype Group Chat

### ISSUE THREAD

**Issue by duckwaffle** [Microsoft/BotBuilder#1635]
I'm trying to authenticate user's in a group chat environment in Skype, in a 1:1 chat the following code works perfectly when the user wishes to authenticate:

`var response = context.MakeMessage();`
`response.Recipient = msg.From;`
`response.Type = "message";`
`response.Text = prompt;`
`response.AttachmentLayout = AttachmentLayoutTypes.List;`
`response.Attachments = new List<Attachment>();`
`response.Attachments.Add(SigninCard.Create("You need to authorize me",  "Click Here!", authenticationUrl).ToAttachment());`
`await context.PostAsync(response);`

However when I enable group chats on the bot, the following exception gets thrown when trying to post the SigninCard:

{  "message": "An error has occurred.",  "exceptionMessage": "invalid next: Wait: Wait IMessageActivity for ThunkResume`1.Rest have IMessageActivity ",  "exceptionType": "Microsoft.Bot.Builder.Internals.Fibers.InvalidNextException",  "stackTrace": "   at Microsoft.Bot.Builder.Internals.Fibers.Fiber`1.<Microsoft-Bot-Builder-Internals-Fibers-IFiberLoop<C>-PollAsync>d__13.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---

The exception log is from ApplicationInsights, I've truncated the full response for brevity.

Is there anything that we need to be doing differently to get SigninCard to show in Skype when in a group chat?

**Comment by nickcordrey** [comment]
Unfortunately sign in cards are not yet supported in Skype group chats.

**Comment by duckwaffle** [comment]
Yeah cool. Is there any documentation on what actually DOES work in skype group chat? Cause so far i've found that it isn't much...
