### ISSUE TITLE
Support Skype for Business 

### ISSUE THREAD

**Issue by activescott** [Microsoft/BotBuilder#1636]
I see ["from text/sms to Skype, Slack, Facebook Messenger, Kik, Office 365 mail and other popular services"](https://docs.botframework.com/en-us/faq/#navtitle) that doesn't mention Skype for Business. [In June Microsoft was explicit that Skype for Business isn't supported](https://social.msdn.microsoft.com/Forums/en-US/70656a60-4072-479f-9e0c-8863652e99f5/question-about-direction-re-skype-for-business-bots?forum=SkypeWebSDK), but will it be?

**Comment by dandriscoll** [comment]
Hi @activescott, Skype for Business is one of our most frequently requested channels but we don't have a timeline to announce yet. Please stay tuned.

**Comment by activescott** [comment]
Thank you for the prompt response. I presume we'll get notified of updates here. We're launching our integration with SfB soon and are interested in exploring bot integration with SfB.

**Comment by dandriscoll** [comment]
Generally we post announcements to the Bot Framework blog: https://blog.botframework.com/

**Comment by ronnelsantiago** [comment]
is there like a uservoice where we could vote on a feature at least

**Comment by chrimc62** [comment]
We did have a uservoice, but we retired it--there were too many support channels for us to keep on top of it.
