### ISSUE TITLE
Get userName of Skype

### ISSUE THREAD

**Issue by awadhes22** [Microsoft/BotBuilder#1637]
I am using bot framework and i want skype username (e.g xyz.abc1 as login name).
please help me ASAP.

**Comment by alokraj68** [comment]
@awadhes22 
you can only take the name from user as following inside IDailog context

```
var reply = context.MakeMessage();
reply.Recipient.Name;
```

In message controller use, 

`activity.Recipient.Name`


Thank you.!

**Comment by awadhes22** [comment]
@alokraj68 thanks for replying 
i am getting skype display name not getting username(which is unique per id).

**Comment by alokraj68** [comment]
@awadhes22 I think you cannot access that as of now.

**Comment by awadhes22** [comment]
@alokraj68 can i get username from token or have any other way. Please help me or suggest.

**Comment by alokraj68** [comment]
I don't think skype share such info as it affects user privacy.

**Comment by awadhes22** [comment]
@alokraj68 i want my skype user name anybody can know his own user name by navigating 
Menu -> Skype -> Profile -> Edit Your Profile i can see my username right.
So what is the issue over here for providing my own username by command..?

**Comment by alokraj68** [comment]
```
    {
    "channelId":"skype",
    "serviceUrl":"https://apis.skype.com",
    "conversation": {
    "id":"29:f2ca6a4a-93bd-434a-9ca5-5f81f8f9b455",
    "name":"Display Name"
    },
        "from": {
            "id":"29:f2ca6a4a-93bd-434a-9ca5-5f81f8f9b455",
            "name":"Display Name"
    },
        "recipient": {
            "id":"28:ad35d471-ae65-4626-af00-c01ffbfc581f",
            "name":"Trivia Master"
    },
        "id":"1234567890",
        "type":"message/text",
        "text":"Hello World!"
    }
```

This is the JSON we get so the data we get from skype

**Comment by awadhes22** [comment]
@alokraj68 Please check this link:
https://drive.google.com/file/d/0ByVjtpvd6mEIT2wzZDk4ZDVVR2M/view?usp=sharing
I have Skype: meet.jay1
i want to access this thing. 
If i add you on my Skype i can see your Skype name so what would be the issue over here don't know.

I already used this JSON: 

> {
>     "channelId":"skype",
>     "serviceUrl":"https://apis.skype.com",
>     "conversation": {
>     "id":"29:f2ca6a4a-93bd-434a-9ca5-5f81f8f9b455",
>     "name":"Display Name"
>     },
>         "from": {
>             "id":"29:f2ca6a4a-93bd-434a-9ca5-5f81f8f9b455",
>             "name":"Display Name"
>     },
>         "recipient": {
>             "id":"28:ad35d471-ae65-4626-af00-c01ffbfc581f",
>             "name":"Trivia Master"
>     },
>         "id":"1234567890",
>         "type":"message/text",
>         "text":"Hello World!"
>     }

But didn't got any expected results as of now.

**Comment by alokraj68** [comment]
Yes, From bot platform you cannot actually extarct the users id. as of now.

**Comment by awadhes22** [comment]
@alokraj68 sir, you saying as of now.
Can we expect this functionality in future versions or Microsoft doesn't provide this feature.
Please comment on it.

**Comment by alokraj68** [comment]
@awadhes22 No idea sir Let @willportnoy  comment on that

**Comment by alokraj68** [comment]
@awadhes22  keep this opened so that they may add to enhancements.

**Comment by awadhes22** [comment]
@willportnoy @alokraj68 Ok We are waiting..

**Comment by awadhes22** [comment]
@alokraj68 @willportnoy  We are waiting. Please inform us when you are free.

**Comment by alokraj68** [comment]
@awadhes22 he's from Microsft team. he may take time. as of now, I cannot find any solution for you.

**Comment by ejadib** [comment]
It's not possible. ince the v3 version of the API the user is now represented by a unique user ID per bot. This is to provide an extra layer of privacy to the users (pretty much like Facebook).

**Comment by nickcordrey** [comment]
Just confirming what others have said we do not send the Skype ID. What's the scenario that means you need the actual Skype ID?

**Comment by awadhes22** [comment]
https://drive.google.com/file/d/0ByVjtpvd6mEIT2wzZDk4ZDVVR2M/view?usp=sharing 
i want meet.jay1 (skype unique name)

**Comment by chrimc62** [comment]
@nickcordrey is there anything else we need to do here?

**Comment by dandriscoll** [comment]
Closing this issue, as I don't believe there are any open questions about what the current behavior is.

**Comment by vasilah** [comment]
I have a same issue in 2018. I created a bot on BotFramework platform and part of users use Skype as channel. During conversation i obtain skype name like Ivan Drozdov from context.Activity.From.Name and in most cases it works good. But in case of some users context.Activity.From.Name is null and i forced to use context.Activity.From.Id what looks like "29:1-qEDwbvRgl7gqItPxj12345678kjDjh0HW2JsZ2LOWaU". I have no idea unions that group of people.
