### ISSUE TITLE
Getting conversation members in Skype Group Chat

### ISSUE THREAD

**Issue by duckwaffle** [Microsoft/BotBuilder#1638]
Hi,

I'm trying to get an enumerable of all conversation members in a Skype Group chat, in the emulator the following code works:

var conversationMembersResponse = await connector.Conversations.GetConversationMembersWithHttpMessagesAsync(activity.Conversation.Id);
var conversationMembers = conversationMembersResponse?.Body as IEnumerable<ChannelAccount>;

However in Skype Group chat the only "ChannelAccount" that gets returned as part of that call is one which has the Id of the conversation itself, no members.

Is there any other way of interrogating the conversation to get, at a minimum, the user id of all members in a group chat?

**Comment by nickcordrey** [comment]
Not right now but this will be coming in a future release.
