### ISSUE TITLE
HELP: How to build Bot Conversation from a JSON file

### ISSUE THREAD

**Issue by afficionaddo** [Microsoft/BotBuilder#1639]
Hi,

See my json file will be a key-value pair like:

{"What is my name": "My name is Russell.", "Where do you live": "I live in Canada"}

So what I am trying to accomplish is to load this JSON as a conversation.
What are the tools for the same in BotFramework. Any reference doc for this kind of operation?

Is it viable / possible?

Looking forward to reply.

**Comment by willportnoy** [comment]
You could certainly accomplish this with the bot builder SDKs, using a regex or string match to recognize the question and provide the answer.  But that requires more of a strict match, so you might consider using LUIS to parse the natural language and understand it in terms of intents and entities.
