### ISSUE TITLE
Create PromptChoice and PromptString in a loop

### ISSUE THREAD

**Issue by Kris-Nimmagadda** [Microsoft/BotBuilder#1643]
Hello BotBuilders,
We have a scenario wherein if the user doesn't give all the entities that are needed for an intent fulfilment, then we identify the same with LUIS and then prompt for each of the missing Entities. We know what are the missing entities and their PromptStyles and all the needed info. If we call the PromptChoice or PromptString etc.  in a loop, it might not work. Any suggested way to handle this ? 

Thank you in advance for your time. 

Cheers,
Krish

**Comment by willportnoy** [comment]
I assume you're using the C# SDK.  You can't literally use a C# loop for this problem, but you can ask for missing entities with a prompt and then in the ResumeAfter delegate, you can decide whether to ask for another missing entities with a prompt, pointing to the same ResumeAfter delegate, or if you have all entities, you can take your action.  You would keep your "loop" state in the class, marked as serializable so it could be preserved across user inputs and prompt child dialog calls.

**Comment by Kris-Nimmagadda** [comment]
Thank you @willportnoy ! I am using the same way as of now. But was wondering if there is any better way, Otherwise, we are good.  But, I wonder if this is elegant.

**Comment by willportnoy** [comment]
Is this for LUIS action fulfillment, by the way?

It seems like a reasonable approach.  You might also consider pushing the "ask the user for a number of entities" loop into a separate dialog to make it more reusable.  I'm sure there is also a way to express it with Chain.While, but that might require the use of reflection serialization surrogate and doesn't strike me as more elegant.

**Comment by Kris-Nimmagadda** [comment]
Hi @willportnoy  thank you much for the answer. Yes, it is LUIS action fulfilment. We are using the same ResumptionFunction and solving this for now. Seems like the best solution of all. However, it would be good to have some way to loop through various dialogs and then it goes one after the other prompting, with their own Resumption functions. That is probably what you did using Fibers and Frames. Did I get this right ?

**Comment by willportnoy** [comment]
The fiber/frame/wait code is just to allow for stacks of dialogs, interruptible by waiting for the user's next message.

You might consider looking at the implementation of LUIS action fulfillment @msft-shahins has recently added to the LuisDialog:

https://github.com/Microsoft/BotBuilder/blob/develop/CSharp/Library/Dialogs/LuisDialog.cs

**Comment by willportnoy** [comment]
I'm going to close this issue, but feel free to open a new issue for further discussion.
