### ISSUE TITLE
Get your bot in SKype Bot search and Get Verified By skype

### ISSUE THREAD

**Issue by alokraj68** [Microsoft/BotBuilder#1646]
Hi,
We have our bot published in Bot directory for past some days.
https://bots.botframework.com/bot?id=Horoscope_Bot

But our bot is not showing up in Skype or Skype bot search. How to achieve that? and also how to get verified by skype tick in my bot.

help needed as no where i could find anything related to this.

**Comment by jameslew** [comment]
Hello @alokraj68 , right now we have a bit of a Bot backlog in the directory.  We're working through, but I can't commit to a specific time when we're able to clear the backlog.  When they get through your bot you'll be notified that they completed their review, and any feedback.
