### ISSUE TITLE
IntentDialog.onBegin( function (session, args, next)) Args is always undefined.

### ISSUE THREAD

**Issue by ubreddy** [Microsoft/BotBuilder#1647]
I am trying to capture the intent recognized on the onBegin handler. But I always see the args argument in the function called as undefined. 

dH.onBegin = function (session,args,next){
  if( args) {
  // code here is not reached.
} else { 
 // this is always reached.
}
};
var dialog = new builder.IntentDialog({
			recognizeMode : builder.RecognizeMode.onBegin,
			recognizers : [recognizer]
		});
dialog.onBegin(dH.onBegin);

**Comment by Stevenic** [comment]
`IntentDialog.onBegin()` is always called before the intent recognizers are run.  You'd need to use either `matches()` or `onDefault()` to receive the intents. Can I ask what you're trying to do? maybe I can make a suggestion.

**Comment by ubreddy** [comment]
I am trying to log to database all intents and entities chat users use. Uday 

    On Monday, 14 November 2016 4:24 AM, Steven Ickman <notifications@github.com> wrote:
 

 IntentDialog.onBegin() is always called before the intent recognizers are run. You'd need to use either matches() or onDefault() to receive the intents. Can I ask what you're trying to do? maybe I can make a suggestion.—

**Comment by Stevenic** [comment]
You could create a new custom recognizer that wraps the LuisRecognizer. This would let you log everything coming from LUIS.

**Comment by chrimc62** [comment]
Let us know if this does not work for you.

**Comment by piyush-dholariya** [comment]
I am not getting dialog in args, I can get only entities in args.
