### ISSUE TITLE
LUIS action paramters in LuisResult

### ISSUE THREAD

**Issue by jakobpn** [Microsoft/BotBuilder#165]
The LuisResult object that is currently passed to the "intent method" has a list of entities that LUIS has recognized in the query. For each entity there is has the type of the entity and a the value of the entity.

In luis.ai it is possible to specify an action on an intent and a list of named parameters. It would be very useful if the parameter name was also passed to the "intent method" in the LuisResult object.

```
  "intents": [
    {
      "intent": "set{removed}",
      "score": 0.463936955,
      "actions": [
        {
          "triggered": true,
          "name": "set{removed}",
          "parameters": [
            {
              "name": "{removed}Address",
              "required": true,
              "value": [
                {
                  "entity": "a1",
                  "type": "Cell",
                  "score": 0.9977119
                }
              ]
            },
            {
              "name": "Value",
              "required": true,
              "value": [
                {
                  "entity": "10",
                  "type": "builtin.number",
                  "score": 0.9843832
                }
              ]
            }
          ]
        }
      ]
    },
```

**Comment by chrimc62** [comment]
Thank you for the suggestion.  We will look into adding this.

**Comment by msft-shahins** [comment]
Commit [90dd703](https://github.com/Microsoft/BotBuilder/commit/90dd7034596e838bdd8b1da7fb22c1ac22faf01f) adds actions to LuisResult. This should become available in the next release.
