### ISSUE TITLE
[Facebook] Receipt Card with Shipping Charges

### ISSUE THREAD

**Issue by ernanirst** [Microsoft/BotBuilder#1652]
Hello, I know this is possible to do with bot framework I just don't know how. I'm building a receipt card using facebook and everything seemed fine until I have to set the shipping cost. According to the [documentation](https://docs.botframework.com/en-us/node/builder/chat-reference/classes/_botbuilder_d_.receiptcard.html#facts) I must create a fact and add it to the facts list. Just like I did it with `Order Number` and `Payment Method` like this: `builder.Fact.create(session, "Não confirmado", "Order Number")`.

So, my first try was this: `builder.Fact.create(session, 4.95, "Shippinh Cost")`. But nothing happend, then I tried replacing "Shipping Cost" with "Shipping Charges" and "shipping_cost" and both failed as well.

I went to facebook [documentation](https://developers.facebook.com/docs/messenger-platform/send-api-reference/receipt-template) and it seems that this option is set on the summary object. So I also tried to set the entire summary object and the summary object serialized...it didn't work as well...

So I'm kind of lost here, can someone help me to set the Shipping Cost field on facebook receipt template?

I also heard that it's possible to create your message as described on facebook API (just with JSON) and send it with MS Bot Framework, can someone point to me an example?

Best Regards,

Ernani

**Comment by craigjensen** [comment]
We currently don't support sending shipping_cost in the facts list.  I'll open a work item to investigate adding support for both shipping_cost and subtotal in the facts list in an upcoming build.

For now, you can send a complete Facebook receipt template in ChannelData as follows:

    {
     "attachment":{
      "type":"template",
      "payload":{
        "template_type":"receipt",
        "recipient_name":"Stephane Crozatier",
        "order_number":"12345678902",
        "currency":"USD",
        "payment_method":"Visa 2345",        
        "order_url":"http://petersapparel.parseapp.com/order?order_id=123456",
        "timestamp":"1428444852", 
        "elements":[
          {
            "title":"Classic White T-Shirt",
            "subtitle":"100% Soft and Luxurious Cotton",
            "quantity":2,
            "price":50,
            "currency":"USD",
            "image_url":"http://petersapparel.parseapp.com/img/whiteshirt.png"
          },
          {
            "title":"Classic Gray T-Shirt",
            "subtitle":"100% Soft and Luxurious Cotton",
            "quantity":1,
            "price":25,
            "currency":"USD",
            "image_url":"http://petersapparel.parseapp.com/img/grayshirt.png"
          }
        ],
        "address":{
          "street_1":"1 Hacker Way",
          "street_2":"",
          "city":"Menlo Park",
          "postal_code":"94025",
          "state":"CA",
          "country":"US"
        },
        "summary":{
          "subtotal":75.00,
          "shipping_cost":4.95,
          "total_tax":6.19,
          "total_cost":56.14
        },
        "adjustments":[
          {
            "name":"New Customer Discount",
            "amount":20
          },
          {
            "name":"$10 Off Coupon",
            "amount":10
          }
        ]
      }
     }
    }

**Comment by ernanirst** [comment]
Ok, thanks.

**Comment by ernanirst** [comment]
That's odd because on the docs it specifically says that for Shipping Charges I should use facts. Anyway, thanks for pointing out channelData, I will take a look at it.

**Comment by craigjensen** [comment]
The fix for adding shipping_cost and subtotal to the Facts list is checked in and will be deployed with the next build.  Probably early next week.
