### ISSUE TITLE
Editing a slack message

### ISSUE THREAD

**Issue by srozga** [Microsoft/BotBuilder#1653]
I understand that the framework doesn't support editing and we should be using the custom channel data (as per https://github.com/Microsoft/BotBuilder/issues/1050). It appears that slack supports this behavior by exposing a editMessage endpoint on their API (as opposed to postMessage which just adds a message). Using channelData we cannot tell the connector which slack endpoint to use. Any advice on how we can use the slack functionality?

**Comment by craigjensen** [comment]
The Botframework supports editing Slack messages via UpdateActivity on the ConnectorClient.

**Comment by srozga** [comment]
Ah! Ok. Makes sense. There is no integration into the IDialogContext correct? So I'd have to create a new ConnectorClient from the context and do it that way.

**Comment by craigjensen** [comment]
That's correct - you'll need to do it yourself via the ConnectorClient.
