### ISSUE TITLE
Decouple Bot Builder to multiple fine grained modules

### ISSUE THREAD

**Issue by Deilan** [Microsoft/BotBuilder#1655]
The .NET Core flavor of delivering a numerous set of small fine grained NuGet packages is one of the best things which has happened recently with .NET ecosystem. So it is proposed to make the same thing happen with Bot Builder: decouple it into multiple modules/packages with low coupling and high cohesion each.

**Comment by chrimc62** [comment]
Thank you for the suggestion.  This is something we have started to do and will be continuing to do moving forward.
