### ISSUE TITLE
Getting Slack auth token when user installs the bot

### ISSUE THREAD

**Issue by euanlau** [Microsoft/BotBuilder#1657]
Is there any way to retrieve the auth token when someone installs the bot?

**Comment by craigjensen** [comment]
It's passed in ChannelData for every message

**Comment by euanlau** [comment]
@craigjensen I want to get the token before user sends the first message.

**Comment by craigjensen** [comment]
Your bot should receive a conversationUpdate message when it's added to a channel.  The Api token is included in ChannelData for this event as well.

**Comment by euanlau** [comment]
@craigjensen I receive the update only after I invite the bot to a channel. But I want to get the token before that so that I could execute a few slack APIs (e.g. sending a welcome message to users).

**Comment by euanlau** [comment]
@craigjensen Ideally, the botframework console should allow developers to register an optional http webhook/callback that will be invoked after the slack oauth is completed.

**Comment by craigjensen** [comment]
Thanks for the feedback.  I opened a feature request to internally track this going forward.  For now you'll have to wait for the bot to be added to a channel to get the token.
