### ISSUE TITLE
Exception thrown: 'System.TypeInitializationException'  in webapp

### ISSUE THREAD

**Issue by ganeshnj** [Microsoft/BotBuilder#166]
I have an existing Asp.net MVC application and I’m trying to add BotBuilder functionality using an ApiController as shown in the getting started tutorial. Everything works fine until I don’t add Dialog. As soon as I add the below line, the application throws “**System.TypeInitializationException**”.

`return await Conversation.SendAsync(message, () => new EchoDialog());`

At the end the controller returns 500 Internet Server Error.

**Comment by darrenjefford** [comment]
Have a look at the innerexception, I had the same issue and innerexception pointed to a newtonsoft library issue. Updating the nugget package fixed it.

**Comment by willportnoy** [comment]
If you can report the inner exception within the TypeInitializationException, that would help us diagnose the issue.  There is a static constructor on the Conversation class, so I would expect it to come from that code or from a missing dependency as mentioned by @darrenjefford.

**Comment by ganeshnj** [comment]
@darrenjefford Yeah it was due to older version of newtonsoft, thanks for mentioning it. Now everything works fine.
