### ISSUE TITLE
 Initiate call from Bot to User

### ISSUE THREAD

**Issue by decv86** [Microsoft/BotBuilder#1661]
Hi!
Help me pls!
Is it possible to initiate a call from Bot to the user? In the old api it was possible, but now can not find a solution?

Thank you!

**Comment by karlbarber** [comment]
Have you tried version 3.3.0 as 3.3.1 and 3.3.2 seem to have auth issues when initiating a new conversation.

This works for me from service fabric 

                string appid = CloudConfigurationManager.GetSetting("MicrosoftAppId");
                string appsecret = CloudConfigurationManager.GetSetting("MicrosoftAppPassword");

                var connector = new ConnectorClient(new Uri("https://facebook.botframework.com/"), appid, appsecret);
                var conversationId = await connector.Conversations.CreateDirectConversationAsync(from, to);
                IMessageActivity message = Activity.CreateMessageActivity();

                message.From = from;
                message.Recipient = to;
                message.Conversation = new ConversationAccount(id: conversationId.Id);
                message.Text = text;
                var reply = await connector.Conversations.SendToConversationAsync((Activity) message);

**Comment by decv86** [comment]
thanks! 
how to initiate an audio call from bot?

**Comment by chrimc62** [comment]
@msft-shahins  can you comment?

**Comment by msft-shahins** [comment]
@decv86 currently you cannot proactively initiate an audio call to user. To workaround this, you can proactively send a message to user and ask them to call your bot. Here is a sample showing how you can proactively create a new conversation: https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/core-CreateNewConversation
