### ISSUE TITLE
telegram menu artifact

### ISSUE THREAD

**Issue by AndrewBryukhov** [Microsoft/BotBuilder#1662]
How to remove "Options:" label message for every menu with bot.dialog()?

**Comment by eanders-MS** [comment]
Telegram does not support the display of buttons without some associated content (text or image). Are you sending buttons alone?

**Comment by AndrewBryukhov** [comment]
I'm using only builder.Prompts.choice with '|' separators for buttons.

**Comment by eanders-MS** [comment]
Can you post a line of sample code of the way you're calling it?

**Comment by AndrewBryukhov** [comment]
`bot.dialog('simple menu', [
    function (session) {
        builder.Prompts.choice(session, "any caption", "button 1|button 2|button 3|button 4", {listStyle: builder.ListStyle.button});
    },
    function (session, results) {
        switch (results.response.index) {
            case 0:
                session.beginDialog('something1');
                break;
            case 1:
                session.beginDialog('something2');
                break;
            case 2:
                session.beginDialog('something3');
                break;
            default:
                session.endDialog();
                break;
        }
    },
    function (session) {
        session.replaceDialog('simple menu');
    }
])`

Without "{listStyle: builder.ListStyle.button}" or any caption i have a similar result.

**Comment by eanders-MS** [comment]
This was a bug in our Telegram channel. Thank you for reporting this. We've made a fix and it should be available in production in a few days.

In the meantime, you can work around the issue by sending a Hero Card with the prompt as the card text rather than the message text:

```
bot.dialog('simple menu', [
    function (session) {
        const card = new builder.HeroCard(session)
            .text('any caption')
            .buttons([
                builder.CardAction.imBack(session, 'option 1', 'option 1'),
                builder.CardAction.imBack(session, 'option 2', 'option 2'),
                builder.CardAction.imBack(session, 'option 3', 'option 3'),
                builder.CardAction.imBack(session, 'option 4', 'option 4')
            ]);
        const msg = new builder.Message(session).addAttachment(card);
        builder.Prompts.choice(session, msg, "option 1|option 2|option 3|option 4");
    },
    function (session, results) {
        switch (results.response.index) {
            case 0:
                session.beginDialog('something1');
                break;
            case 1:
                session.beginDialog('something2');
                break;
            case 2:
                session.beginDialog('something3');
                break;
            default:
                session.endDialog();
                break;
        }
    },
    function (session) {
        session.replaceDialog('simple menu');
    }
])
```

**Comment by chrimc62** [comment]
Sounds like the issue is fixed, let us know if you still have a problem.
