### ISSUE TITLE
email channel is dropping some emails

### ISSUE THREAD

**Issue by cnrudd** [Microsoft/BotBuilder#1663]
Hi,

I have a bot that is using only the email channel. It is connected to an office365 email account.  
In the office365 email interface for our bot's email address, emails that were forwarded to the bot always have a reply sent back to the original email address, after processing by the bot.  

There is one original email address, however, whose messages appear to never get sent to the bot. I've double checked our bot code, and there is no code path that generates 'no reply'.  Even code errors that generate the 'Oops something went wrong..'  error msg send that msg back as an email reply.  But for emails sent by this one user, nothing.

Is there any way I can analyze the cause of this?  I don't see any 'issues' listed in the email channel's issues log for the time the email in question was sent.  

Is there a log somewhere in the botframework where I can read which emails were sent to my bot? Which ones were not and what was the reason why not?
Thanks!

**Comment by craigjensen** [comment]
Please include your botId and I'll investigate.

**Comment by cnrudd** [comment]
thanks: bot id = 'dynamo'

**Comment by craigjensen** [comment]
I see a couple of timeout exceptions in our logs coming from dynamo_dev around 8:10 am PST.  Are these related to the issue you are seeing?  

If you add an Application Insights key to your bot configuration in the dev portal we will write additional debugging information to help you diagnose the problem.

**Comment by cnrudd** [comment]
Hi Craig, the issue I'm seeing is not in dynamo_dev, but in dynamo.  The email that got no reply in dynamo came in yesterday:  Nov 14, 9:44 AM Eastern

**Comment by craigjensen** [comment]
I see a message that was successfully sent to your bot at 9:44:18 AM EST yesterday.  I also see messages being sent today, most recently at 11:17:23 AM EST.  Would you mind if I try to send a test message to your bot?

**Comment by cnrudd** [comment]
I don't mind at all.  There are many messages being successfully sent.  But it seems like some are not.

**Comment by cnrudd** [comment]
Thanks for your help with this Craig.  I think I worked out what the issue was:   

Some users have massive HTML email signatures.  
These were reaching our bot, and getting sent to LUIS, which choked on them, and would send back a body = '' (empty string).  Nothing would show up in the LUIS log or suggestion panel, so it looked like nothing had come to LUIS.  

With no entity or no intent detected my bot would just stop too.

I am now stripping out all html and bracketed [] text from session.message.text before passing it off to LUIS.  Seems to solve the problem.
