### ISSUE TITLE
UserData differences between emulator and production

### ISSUE THREAD

**Issue by svickers** [Microsoft/BotBuilder#1666]
We are working on a bot that stores a user's email address in bot framework's UserData collection and then later uses it for querying a database.  This works perfectly with the emulator but when using in production no results are ever returned from the db.   

With the simple test dialog code when using the emulator the strings will match but running on Azure they wont,

    [Serializable]
    public class TestDialog : IDialog<object>
    {

        public async Task StartAsync(IDialogContext context)
        {
            context.Wait(MessageReceivedAsync);
        }
        public virtual async Task MessageReceivedAsync(IDialogContext context, IAwaitable<IMessageActivity> argument)
        {
            var message = await argument;

            string email;
            if (!context.UserData.TryGetValue<string>("email", out email))
            {
                PromptDialog.Text(context, this.ResumeAfterPrompt, $"Hi {message.From.Name}! What is your email address?");
                return;
            }

            var msg = context.MakeMessage();
            msg.Text = $"Your email address is: {email}, Match: {email == "me@me.com"}";
            await context.PostAsync(msg);

            context.Wait(MessageReceivedAsync);
        }

        private async Task ResumeAfterPrompt(IDialogContext context, IAwaitable<string> result)
        {
            try
            {
                string email = await result;
                context.UserData.SetValue<string>("email", email);
                await context.PostAsync($"Thanks '{email}'");
            }
            catch (TooManyAttemptsException)
            {
            }

            context.Wait(MessageReceivedAsync);
        }

    } 

1. Message the bot
2. Enter me@me.com when prompted
3. Send another message
4. Check _match_ result

**Comment by msft-shahins** [comment]
@svickers how do you call the TestDialog and what channel do you use for testing. The code above should work fine both for production and emulator.

**Comment by svickers** [comment]
Actually it looks like it isn't so much of the storage as it is the incoming result from the prompt.  This happens when using the slack channel.  If I hard-code the value of the email string in ResumeAfterPrompt, it works fine.

**Comment by msft-shahins** [comment]
@svickers  slack encodes the emails in the text to something like this: ``<mailto:me@me.com|me@me.com>`` and that is the reason that your match condition fails. You need to parse the result coming from PromptDialog.Text if you want to store the email address.
