### ISSUE TITLE
Self Referencing Loop When Attempting to Store LuisResult into BotData

### ISSUE THREAD

**Issue by CaptainScavo** [Microsoft/BotBuilder#1672]
I am attempting to prompt the user for required parameters that are defined in a LUIS model.
In order to be able to do this (ie call client.Reply()), I have to pass back the LuisResult on the next bot callback.

But when I attempt to store the LuisResult into BotData, I get the error shown below **(Self referencing loop detected for property 'luisResult' with type 'Microsoft.Cognitive.LUIS.LuisResult')**

When I look at the source for StateClient, it appears to be setting the JSONSerialization settings to ReferenceLoopHandling.Serialize (which I was hoping might bypass this error).

Thoughts on how I can persist the LuisResult into the next bot callback ??????

`Something unexpected happened - Self referencing loop detected for property 'luisResult' with type 'Microsoft.Cognitive.LUIS.LuisResult'. Path 'reply.target0'.\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference(JsonWriter writer, Object value, JsonProperty property, JsonContract contract, JsonContainerContract containerContract, JsonProperty containerProperty)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeISerializable(JsonWriter writer, ISerializable value, JsonISerializableContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)\r\n   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)\r\n   at Newtonsoft.Json.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value)\r\n   at Newtonsoft.Json.Linq.JToken.FromObjectInternal(Object o, JsonSerializer jsonSerializer)\r\n   at Newtonsoft.Json.Linq.JToken.FromObject(Object o)\r\n   at Microsoft.Bot.Connector.BotData.SetProperty[TypeT](String property, TypeT data)\r\n   at MessagesController.<XXXXXXXX>d__11.MoveNext() in D:\\ms-botv3\\Controllers\\MessagesController.cs:line 149\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at MessagesController.<Post>d__9.MoveNext() in D:\\ms-botv3\\Controllers\\MessagesController.cs:line 65`

**Comment by msft-shahins** [comment]
This is related to the LuisResult definition in Microsoft.Cognitivie.Luis: https://github.com/Microsoft/Cognitive-LUIS-Windows/blob/master/ClientLibrary/Structures/LuisResult.cs and not related to LuisResult implementation of bot builder. For now, Bot builder is relying on its own implementation of Luis client and Luis result. Probably worth opening an issue about this on that repo about the self referencing loop. Also you only need the context id in the LuisResult to build the next request for parameter filling.

This [change](https://github.com/Microsoft/BotBuilder/commit/5158523a3d144ad6e58b13eec44da6416780d0d7) adds support for parameter filling to the bot builder's LuisDialog. It is still in develop branch and we plan to release it in a new nuget in the near future.
