### ISSUE TITLE
In Skype, Carousel of 2 Thumbnail Cards Drops the message text

### ISSUE THREAD

**Issue by CaptainScavo** [Microsoft/BotBuilder#1673]
Create a Reply with text "abc"
Set AttachmentLayout to  "carousel"
Add 2 Thumbnail cards

In Emulator, you see:
- the text "abc" 
- carousel (card 1 and card 2)

In Skype, the text gets dropped and you only get:
- carousel (card 1 and card 2)

If I comment out **Set AttachmentLayout to  "carousel"**, then in Skype I get:
- the text "abc"
- card 1 
- card 2

Is this a limitation of Skype carousels or a bug in the Bot Framework ??

**Comment by nickcordrey** [comment]
This is a limitation of Skype carousels you cannot attach summary text to the whole carousel.
