### ISSUE TITLE
Limit size and date for voice message

### ISSUE THREAD

**Issue by Hanoko** [Microsoft/BotBuilder#1674]
Hi,

How long does the voice message sent from Telegram stay in the Microsoft's servers? And do they have a size/time limit?

When I send a voice message it is saved in an url like this;
https://bcattachmentsprod.blob.core.windows.net/636149916000000000/2A3GM2XXSJBC1

I have not any azure plan. 

Thanks,
Pablo

**Comment by eanders-MS** [comment]
Hi Hanoko, attachments from Telegram are currently cached for 2 days. We don't make this a guarantee, and it may change in the future without notice.

**Comment by Hanoko** [comment]
Hi eanders,
Thanks for the information.
Do you know where Telegram save the voice messages? Can we access those files? Are they only cached for a short time as Microsoft do?

Pablo

**Comment by eanders-MS** [comment]
I do not have that specific knowledge of the Telegram file cache. You may be able to find this information in the Telegram Bot API docs: https://core.telegram.org/bots/api/#file. You might also try asking on Telegram's `@BotSupport` channel.
