### ISSUE TITLE
Sad bot is sad - When trying to change channels.

### ISSUE THREAD

**Issue by tinod** [Microsoft/BotBuilder#1675]
When I try to edit the Skype or Teams channels, I get redirected to the corresponding page (https://msteams.botframework.com/Dev/?botId=xxx or https://skype.botframework.com/Dev/?botId=xxx) but the page only displays "Sad bot is sad".
Needless to say, the channels are not working...

Any ideas what's wrong?

**Comment by craigjensen** [comment]
Both Skype and MSTeams config pages are working for me.  If you are still seeing this please add your botId and we'll investigate.

**Comment by chrimc62** [comment]
Hopefully your issue was fixed.  If not, let us know.

**Comment by aksjd** [comment]
Same issue for me

**Comment by jamesemann** [comment]
I am seeing the same issue 02/12/16

**Comment by sagarpomal** [comment]
Same issue. Removed the Skype Channel and then added again, it doesn't work.

**Comment by waghpravin14** [comment]
Facing same issue. Getting "Sad bot is sad" message when tried to add Bot to skype.
