### ISSUE TITLE
Markdown in Skype is not rendering 

### ISSUE THREAD

**Issue by spreddy2714** [Microsoft/BotBuilder#1676]
Hi,

I am sending markdown messages(containing tabular data), which are rendering fine in emulator.
How ever skype app is not doing the rendering, is there anything I should do for this channel separately?

![image](https://cloud.githubusercontent.com/assets/6649902/20365479/0a31406e-ac6d-11e6-9929-e96cd84d0319.png)

**Comment by spreddy2714** [comment]
Web client is doing very better job for the same thing. Added reference here

![image](https://cloud.githubusercontent.com/assets/6649902/20365620/8f39427a-ac6d-11e6-9ffa-52ec6ad70b9a.png)

**Comment by tomlm** [comment]
Skype and any text based channel which doesn't have fixed width fonts do not support this.

**Comment by spreddy2714** [comment]
Is there any other option to achieve this kind of formatting in skype & messenger
