### ISSUE TITLE
Documentation for MIddlewares

### ISSUE THREAD

**Issue by cesarvarela** [Microsoft/BotBuilder#1677]
HI Guys, I can't seem to find anything related to this except for the class reference.

Is there any example or something that I can use to learn about them?

**Comment by Stevenic** [comment]
I need to write some better documentation for using middleware but you can look at the [middleware](https://github.com/Microsoft/BotBuilder/blob/master/Node/core/src/middleware/Middleware.ts) included with the SDK for ideas. I'm also happy to answer specific questions.

**Comment by cesarvarela** [comment]
My questions are about them in general, starting from what are middlewares for? What can and can't be done with them? Do these middlewares share the same philosophy behind Express' ones?

Also, the first-run middleware confuses me, because to me that is something that should be contemplated in the bot code itself, as part of the root dialog.

**Comment by Stevenic** [comment]
Middleware lets you process every incoming and outgoing message.  It's similar to Express Middleware but unlike Express which simply lets you capture incoming requests, you can capture both incoming and outgoing messages vis 3 different pipes.  

The two `receive` & `send` pipes let you inspect the raw event that was either just received or is about to be sent.  Middleware installed for eitehr of these pipes let you apply transforms to messages. For instance you can install middleware that does language detection, sentiment detection, or machine translation.

The third `botbuilder` pipe lets process a received message after its been loaded into a `Session` object.  This is probably the most useful form of middleware.  You can use it to add either new helper methods to the Session object or to conditionally intercept the message before it's routed to the dialog system.

One of the more popular uses for middleware today is to essentially customize the way messages are routed within the bot.  In fact, for the upcoming v3.5 release we completely re-wrote the SDK's routing system based on how we were seeing customers use middleware in their bots.  With v3.5 there will hopefully be less need to resort to a bunch of custom middleware but if you need a completely custom behavior for your bot, middleware is a great option.

**Comment by cesarvarela** [comment]
Thanks, that clears a lot. In fact, I just updated to `3.5.0-rc7` to use the new `triggerAction` method which simplifies some stuff a lot.

**Comment by Stevenic** [comment]
That was the goal for `triggerAction`. A lot of people were complaining that a user couldn't easily interrupt one task and start a new one.  Trigger actions combined with the new global recognizer support make that (and other scenarios) a lot easier.
