### ISSUE TITLE
.Net FormFlow field with a [Prompt("{||}")] attribute causes exception when connected via Facebook Messenger

### ISSUE THREAD

**Issue by LMEdwards** [Microsoft/BotBuilder#1678]
.Net FormFlow field with a [Prompt("{||}")] attribute causes the following error when connected to Facebook Messenger:

{"error":{"message":"(#100) Param [text] must be a non-empty UTF-8 encoded string","type":"OAuthException","code":100,"fbtrace_id":"F5k9NGkkYHr"}}

[Prompt(" {||}")] also fails.    [Prompt("X{||}")] does not.
Other channels (Skype, Slack, WebChat) do not fail with [Prompt("{||}")].

**Comment by rexad** [comment]
Any luck ? i'm having the same issue it seems its related to ChoiceStyle = ChoiceStyleOptions.Default
if you select  ChoiceStyle = ChoiceStyleOptions.PerLine it should work but with a textual menu

**Comment by rexad** [comment]
So i was able to fix this issue :
please update your bot framework to version 3.3.3.0
put  [Describe(Title = "", SubTitle = "")] at the top of the variable representing the enum 
in my case 
 [Describe(Title = "", SubTitle = "")]
 public FeatureOptions? Menu;
i think facebook make it mandatory to have the title 
et voila .

**Comment by giorgobiani** [comment]
I'm still having problem:

@rexad 's solution does not work for me and @chrimc62 's commit as I can see is roll backed as it was braking change. Below is a code:

`        [Describe(Title = "", SubTitle = "")]
        [Prompt("Gender: {||}", ChoiceStyle = ChoiceStyleOptions.Buttons)]
        public EnumGender Gender { get; set; }`

If I use Title="Test", than it works, but I don't want extra title. As soon as I put empty string, I get this error. Any ideas?

**Comment by vovanb** [comment]
Same issue with reply to Facebook:
"SendActivityToUserAsync FAILED: {\"error\":{\"message\":\"(#100) Param [elements][0][title] must be a non-empty UTF-8 encoded string\",\"type\":\"OAuthException\",\"code\":100,\"fbtrace_id\":\"BltwwnsCdZw\"}}"
Attached sample json
[sample.json.txt](https://github.com/Microsoft/BotBuilder/files/764546/sample.json.txt)

**Comment by rexad** [comment]
i think the fix not working anymore with the new build, i will take a look at it and be back with a solution.
