### ISSUE TITLE
Using Ninject with Bot Framework

### ISSUE THREAD

**Issue by kamranayub** [Microsoft/BotBuilder#1679]
I saw you are using Autofac with Bot Builder SDK--but my project uses Ninject (with Web API and MVC). I tried looking at the Autofac Simple Alarm sample but I'm afraid it's just made me more confused.

I am dealing with the same issue of service serialization as this issue #938. All I need is a service injected into my Dialog class.

Is there a reason Bot Builder doesn't just use all the same DI plumbing Web API uses, considering it has a dependency on WebApi? Just makes it confusing :( Or at least provide a similar "resolver" system frameworks like SignalR provide.

**Comment by willportnoy** [comment]
We're considering using the DI framework used by ASP.NET Core for the next version, if you have feedback.

Can you tell me more about the Signal "resolver" mechanism?  We use construction injection over service locator, so the majority of our code does not actually depend on Autofac.

**Comment by kamranayub** [comment]
Here's a good entry about it:
https://github.com/SignalR/SignalR/wiki/Extensibility

They use the built in dependency resolver framework, and you can simply
implement a couple methods to hook whatever you need in.

For now I'm just using the serialization attributes since I don't want to
deal with it.

**Comment by willportnoy** [comment]
Thank you for the information.  I'll see what we can do in that direction, minimizing our dependency on a specific DI framework.

I'm going to close this issue, but feel free to open a new issue for further discussion.
