### ISSUE TITLE
[.Net] Bot skips one of the field

### ISSUE THREAD

**Issue by ghostinside** [Microsoft/BotBuilder#168]
i have 3 fields in my form

       [Prompt("Please select an {&} of your car {||}")]
        public EngineSize? Engine;

        [Prompt("Please provide the {&} of your car")]
        public int? Mileage;

        [Prompt("Please provide the {&} of your car")]
        public int? Year;

but the Year will not be shown to the user by the bot

**Comment by chrimc62** [comment]
Are you using the FormBuilder?  If you are explicitly listing the fields in the order you want them, I suspect you have not included the Year field.  You can either do so, or use AddRemainingFields.  Something like this:
new FormBuilder<Car>()
.Field(nameof(Engine))
.Field(nameof(Mileage))
.Field(nameof(Year)
                    .Build();

**Comment by ghostinside** [comment]
thx for an example, yes i did not include fields, it was just like this

new FormBuilder().Build();

2016-04-22 20:03 GMT+03:00 chrimc62 <notifications@github.com>:

**Comment by chrimc62** [comment]
Hmmm.  FormBuilder().Build() should have worked.  Either you should have gotten all fields or none.  Could you send me your class definition and I can see why this happened?

**Comment by ghostinside** [comment]
sure, here you are

  public enum EngineSize
    {
        OneDotTwo, OneDotFour, OneDotSix, OneDotEight, OneDotNine,
TowDotZero, ThreeDotTwo
    }

    [Serializable]
    public class CarService
    {
        [Prompt("Please select an {&} of your car {||}")]
        public EngineSize? Engine;

        [Template(TemplateUsage.Integer, "Please provide the {&} of your
car")]
        public int? Mileage;

        [Template(TemplateUsage.Integer, "Please provide the {&} of your
car")]
        public int? Year;
        public static IForm<CarService> BuildForm()
        {

            return new FormBuilder<CarService>()
                    .Message("Welcome to the car service appointment bot!")
                    .Build();
        }
    }

[Serializable]
    public class CarServiceDialog : IDialog<CarServiceDialog>
    {
        internal static IFormDialog<CarService> MakeRootDialog()
        {
            return FormDialog.FromForm(CarService.BuildForm, options:
FormOptions.PromptInStart);
        }
        public async Task StartAsync(IDialogContext context)
        {
            context.Wait(MessageReceivedAsync);
        }

        public async Task MessageReceivedAsync(IDialogContext context,
IAwaitable<Message> argument)
        {
            context.Call(MakeRootDialog(), CarServiceOrderComplete);
        }

        private async Task CarServiceOrderComplete(IDialogContext context,
IAwaitable<CarService> result)
        {
            //var res = await result;
            await context.PostAsync("Goodby");
            context.Wait(MessageReceivedAsync);
        }
    }

2016-04-23 0:33 GMT+03:00 chrimc62 <notifications@github.com>:

**Comment by ghostinside** [comment]
this way also does not work

public static IForm<CarService> BuildForm()
        {

            return new FormBuilder<CarService>()
                    .Message("Welcome to the car service appointment bot!")
                    .Field(nameof(Engine))
                    .Field(nameof(Mileage))
                    .Field(nameof(Year))
                    .Build();
        }

Year does not show up

2016-04-25 13:03 GMT+03:00 Александр Ковалев <kovalevalexandr@gmail.com>:

**Comment by ghostinside** [comment]
nuget 1.1

2016-04-25 13:06 GMT+03:00 Александр Ковалев <kovalevalexandr@gmail.com>:

**Comment by ghostinside** [comment]
so i did some tests and found that the problem is in nullable int fiels, if i change the type from nullable int to int, the flow works correctly

**Comment by chrimc62** [comment]
This was a bug.  I have a fix I will check in soon and it will be in our next release--thanks for finding the issue!
