### ISSUE TITLE
How can I convert pdf attachment to image. 

### ISSUE THREAD

**Issue by ChandrikaC** [Microsoft/BotBuilder#1684]
Hello all,

Could you please all help me?

I want to receive attachment of type pdf and convert it to image and then extract text from it using cognitive service Vision API.

**Comment by palmerabollo** [comment]
@ChandrikaC There are many libraries and third-party cloud services you can use to convert pdf files to images. It doesn't have anything to do with the development of a bot. For example, if you are using Node.js you can use this module https://github.com/mooz/node-pdf-image that uses ImageMagick under the hoods.
