### ISSUE TITLE
LUIS.ai V2 model URLs don't appear to work in BotFramework

### ISSUE THREAD

**Issue by brendanarnold** [Microsoft/BotBuilder#1685]
I have a LUIS model which works when I use an old URL of the form ...

`https://api.projectoxford.ai/luis/v1/application?id=<ID_HERE>&subscription-key=<KEY_HERE>`

This works great in my IntentDialog.

However now when I click publish in LUIS a new URL is shown of the form 

`https://api.projectoxford.ai/luis/v2.0/apps/<ID_HERE>?subscription-key=<KEY_HERE>`

which does not work in my IntentDialog, luckily I still have the old URL saved.

The new URL does not cause any error, it just fails silently, reverting to the onDefault() waterfall.

I am using BotBuilder 3.4.4

**Comment by ejadib** [comment]
Try installing the prerelease version of the botbuilder

`npm install --save botbuilder@next`

or add the "&verbose=true" to the end of the new URL

**Comment by brendanarnold** [comment]
Great, the '&verbose=true` works, thanks
