### ISSUE TITLE
Question : How to send native Facebook card asynchronously

### ISSUE THREAD

**Issue by agnellodcosta** [Microsoft/BotBuilder#1686]
Hi,
I would like to send a native fb card, using bot.send(), Can you please tell me what I am doing wrong below,

var nativeMsg = new builder.Message();
var nativeMsg2 = nativeMsg.sourceEvent(args);
bot.send(nativeMsg2);

"args" is JSON, 
{"facebook": {"notification_type": "REGULAR","attachment": {"type": "template","payload": {"template_type": "generic","elements": [{"title": "Some Title", "image_url": "http://docs.botframework.com/images/demo_bot_image.png","subtitle": "Some amazing subtitle","buttons": [{"type": "postback","title": "GO", "payload": "demo"}]}]}}}}

ps: I dont have session object in this call, its invoked asynchronously as a pro-active message

**Comment by craigjensen** [comment]
Try sending just the inner part of the json:
{"notification_type": "REGULAR","attachment": {"type": "template","payload": {"template_type": "generic","elements": [{"title": "Some Title", "image_url": "http://docs.botframework.com/images/demo_bot_image.png","subtitle": "Some amazing subtitle","buttons": [{"type": "postback","title": "GO", "payload": "demo"}]}]}}}

**Comment by Stevenic** [comment]
Did you get this to work? You DO need the outer "facebook": part

**Comment by agnellodcosta** [comment]
Hi Steve
I just got it to with this weekend
Yes the outer part is needed

Thanks

**Comment by chrimc62** [comment]
It sounds like your problem is solved, so I am closing this issue.
