### ISSUE TITLE
Question : dialogData and userData

### ISSUE THREAD

**Issue by agnellodcosta** [Microsoft/BotBuilder#1687]
Hi,

If a user is in a conversation with a Bot, and a pro-active message is sent, will it invalidate the dialogData/userData and the botState of the current conversation

Thanks

**Comment by Stevenic** [comment]
Sorry for the delay... It depends on how you send it.  If you use `session.send()` then no, everything is preserved.  If you use `session.beginDialog()` then any current dialog stack will be ended and a new conversation started. The `userData` property is never impacted by a proactive message.

**Comment by chrimc62** [comment]
@agnellodcosta if this does not address your issue, please let us know.
