### ISSUE TITLE
escalate to human

### ISSUE THREAD

**Issue by bluekite2000** [Microsoft/BotBuilder#169]
Is there an option to escalate to a human username (in slack) if bot fails to answer adequately?

**Comment by chrimc62** [comment]
You can send messages to anyone if you know their ID on the channel.  This would allow your code to forward a message it does not understand to a human.  Are you using the node or C# version of the builder?

**Comment by bluekite2000** [comment]
@chrimc62 I m using c#

**Comment by bluekite2000** [comment]
@chrimc62 I m using c#. Let me know what is code to use.

**Comment by willportnoy** [comment]
You can instantiate an IConnectorClient, make an Message addressed to that user, and send it through the IConnectorClient implementation.

**Comment by willportnoy** [comment]
I'm going to close this item for now, but feel free to reopen a new item with more questions.

**Comment by ceohockey60** [comment]
What would be the node equivalent of IConnectorClient? Thank you.
