### ISSUE TITLE
Adding Bot to GroupMe broken (404 on azureedge.net)

### ISSUE THREAD

**Issue by ThisWillDoIt** [Microsoft/BotBuilder#1693]
Configuring the bot with GroupMe seems to work, but when clicking the test link to add the bot to a GroupMe conversation there is this new window where you have to select a conversation and click "Save changes".
The pages just flashes and does nothing.

The console throws a HTTP404 for 
(XHR)GET - https://bot-framework.azureedge.net/libs/jquery-1.10.2.min.map

Screenshot: http://imgur.com/a/QxxMd

**Comment by chrimc62** [comment]
@mingweiw is there anything else you need to know?

**Comment by mingweiw** [comment]
It looks like you are using Edge. Is that right? I couldn't repro. The 404 is ok, shouldn't cause an issue here. Is this still happening for you? If so can you give me your "Bot handle"? After you "save" can you chat with the bot in the conversation?

Thanks.

**Comment by ThisWillDoIt** [comment]
Yes, I am using Edge (current Windows 10 production build). I still get the same error and the bot isn't available/can't be added to any conversation.  

Because of your question I just tried it with Firefox 50.0. The site doesn't change either but I only get warnings about "Using //@ to indicate sourceMappingURL pragmas is deprecated..." and "getPreventDefault() is deprecated()".

Deleting all information on GroupMe dev and redoing the workflow to authoritze the bot with GroupMe didn't help either.

The bot handle is "protocol_bot".

**Comment by mingweiw** [comment]
I was able to add / remove your bot from my conversation groups via the UI. It's info showed up correctly in my groupme devportal as well. 

Though the bot is unresponsive in groupme, the webchat control in the portal and skype. That's probably a separate issue.

I noticed the hand icon with a red circle around it in the image below. This is from your [screenshot](http://imgur.com/a/QxxMd). I don't have that icon in my Edge. Is that an extension? Can you turn it off and try it?

![image](https://cloud.githubusercontent.com/assets/19695895/20687703/6b971cb2-b572-11e6-84b6-391966a71150.png)

**Comment by ThisWillDoIt** [comment]
Good and bad news.

Good: I can now add/remove my bot to GroupMe conversation and currently works correctly (currently listens only to specific LUIS intends, so it seemed unresponsive for you)

Bad: I have no idea what changed. The symbol you mentioned is a AdBlock extension. But could uninstalling and reinstalling it really make such a change? It's not blocking anything on that side... Was there a server update?

I am sorry, that I can't tell what changed. But thank you very much for looking into this!
