### ISSUE TITLE
Integrating BOT in Xamarin.Forms application.

### ISSUE THREAD

**Issue by vitthalpatil** [Microsoft/BotBuilder#1695]
I need to integrate Microsoft BOT into Xamarin.Forms application. I can see option with WebView. Is there any SDK available which can be used for cross platform development.

**Comment by chrimc62** [comment]
The Bot Builder should work cross-platform.  We have also released an emulator that works cross platform. Please let us know if you still have an issue.  As to integrating into Xamarin.Forms, you will need to do that yourself.
