### ISSUE TITLE
Integration with Internal Skype

### ISSUE THREAD

**Issue by forensicsguy20012004** [Microsoft/BotBuilder#1697]
How would one go about integrating a Bot into a Skype implementation not hosted in Azure but behind a company firewall?

**Comment by dandriscoll** [comment]
Hi @forensicsguy20012004, currently all Bot Framework bots must be internet-accessible. This includes bots available through Skype.

You can make your bot accessible with a tool like ngrok, or you could have your bot run outside your corporate firewall. If you're completely unable to expose your bot's endpoint, for the time being it's not possible to connect it to cloud-based chat services.

**Comment by forensicsguy20012004** [comment]
Thank you good sir for the information. One more quick question and then we can probably close this out. Would the internal Skype have the same functionality built-in ... if internal resources correctly configured and set up? Basically would the internal Skype be able to "mock" the external Skype system? I

**Comment by dandriscoll** [comment]
Can you clarify what you mean by "internal Skype?" Are you talking about Skype for Business?

If so, we haven't launched support for Skype for Business yet.

**Comment by ronnelsantiago** [comment]
@dandriscoll when is support for S4B is slotted to release?

**Comment by forensicsguy20012004** [comment]
Yeah sorry...Skype for business. ..my bad.

**Comment by dandriscoll** [comment]
We haven't announced a date yet, sorry.

**Comment by forensicsguy20012004** [comment]
I am good to close this issue if you guys want. The only thing I would request is the continued development  towards a release and integration of Skype for Business. As it sounds, that is continuing...so I am good to close this issue if everyone agrees. If everyone does...anyone can close this.

**Comment by forensicsguy20012004** [comment]
I a closing
