### ISSUE TITLE
[Help] Cancel builder.Prompts.choice()

### ISSUE THREAD

**Issue by scibol** [Microsoft/BotBuilder#1699]
My bot has a prompt that asks for user input:

```builder.Prompts.choice(session, "Is it ok?", ["Yes", "No"]);```
Now, when a user responds with something else other than "Yes" or "No" the program will always keep waiting for a reply that matches "Yes" or "No" with:

```I did not understand. Please choose an option from the list```
with the same choices as before.

I would like the bot to not ask for input again if the user types something else other than "Yes" or "No" (and reset the prompt stack so). Is there a way to do so?

Sample code of what i would like to do:
```
bot.dialog('/', [
    function (session) {
        builder.Prompts.choice(session, "Is it ok?", ["Yes", "No"]); 
    },
    function (session, results) {
        if (results.response.entity == "Yes") {
            session.send("You have chosen Yes!"); 
        } else if (results.response.entity == "No") {
            session.send("You have chosen No!");
        } else {
        // users writes something else than yes or no
        // prompts pop itself from stack like it never happened
        }
    }
]);
```

**Comment by palmerabollo** [comment]
@scibol You can probably use `IPromptOptions` to skip retries. Something along these lines:

```js
var options = {
    maxRetries: 0,
};
builder.Prompts.choice(session, "Is it ok?", ["Yes", "No"], options);
```

**Comment by scibol** [comment]
@palmerabollo Thank you very much.
