### ISSUE TITLE
Attach local images

### ISSUE THREAD

**Issue by starchand** [Microsoft/BotBuilder#1701]
How do you send locally save images not publicly hosted file? Tried file location and localhost but all error.

var msg = new builder.Message(session)
            .attachments([{
                contentType: "image/png",
                contentUrl: "http://localhost:3000/google.png"
            }]);
session.endDialog(msg);

**Comment by ronnelsantiago** [comment]
i dont think this a possible.. (but i want to be proven wrong)... if u do not want to share those resources maybe store it in.. say... azure blob storage and set it as "private".. and enable shared secret signature... just a thought...

**Comment by craigjensen** [comment]
You have two options: 1) store the image in a publicly accessible location, or 2) encode the image as a base64 encoded data url and send it inline.  See [docs](https://docs.botframework.com/en-us/core-concepts/attachments/#navtitle) for details
