### ISSUE TITLE
VideoCard ToAttachment() extension method missing?

### ISSUE THREAD

**Issue by ronnelsantiago** [Microsoft/BotBuilder#1702]
nuget 3.3.3 introduces new cards namely video card and audio card.. are there suppose to have a "ToAttachment()" extension method too? same as the other cards?

**Comment by chrimc62** [comment]
@msft-shahins could you comment?

**Comment by msft-shahins** [comment]
@ronnelsantiago commit 54c430c should address this issue and should be available in next release of bot builder.
