### ISSUE TITLE
VideoCard capability request

### ISSUE THREAD

**Issue by ronnelsantiago** [Microsoft/BotBuilder#1703]
I think it would be nice if user can have the ability to view the video in full screen?

**Comment by dandriscoll** [comment]
Hi @ronnelsantiago, are you asking about a particular channel?

**Comment by ronnelsantiago** [comment]
can we make it channel agnostic? on my requirement at the moment i need it on skype channel

**Comment by ronnelsantiago** [comment]
i stand corrected. on skype when u send a videocard it actually gives u to fullscreen.. im on skype client 7.30.64.. u just have to make sure that u have set a corresponding thumbnail for your videocard

**Comment by chrimc62** [comment]
Closing issue since it sounds like you were able to do what you wanted to do.  As to making things work cross-channel we are often at the mercy of what the specific channels support.
