### ISSUE TITLE
is there a doc/page where it listed all features suppported by each channels?

### ISSUE THREAD

**Issue by ronnelsantiago** [Microsoft/BotBuilder#1704]
Anyone knows if such documentation exists that lists all features that are supported by each channels?

Channels | Feature
----------|--------
Skype | No VideoCard support 
SMS | No VideoCard support

Its a pain to work on a feature that works on the emulator but did not on the actual channel you are targetting

**Comment by CaptainScavo** [comment]
+1. This would be very useful when trying to baseline bot functionality across multiple channels

**Comment by chrimc62** [comment]
This is a good idea and should be coming soon.  @LarsLiden ?

**Comment by LarsLiden** [comment]
Correct.  We will be releasing a Channel Inspector in the near future.
