### ISSUE TITLE
How to show confirmation popup  in microsoft bot framework

### ISSUE THREAD

**Issue by awadhes22** [Microsoft/BotBuilder#1705]
I am implementing bot in Skype using Microsoft Bot Framework. I want to show confirmation popup  (e.g  yes or no message box ) whenever the command is sent to bot.

**Comment by palmerabollo** [comment]
If you are using the Node.Js SDK you can use [`botbuilder.Prompts.confirm`](https://docs.botframework.com/en-us/node/builder/chat/prompts/#promptsconfirm). Is that what you need?

**Comment by msft-shahins** [comment]
@awadhes22 what you mean by confirmation prompt? You can use built in confirmation dialogs in bot builder to send a confirmation prompt in the form of a [HeroCard](https://docs.botframework.com/en-us/core-concepts/reference/#herocard) to user.
