### ISSUE TITLE
How to do a decision tree?

### ISSUE THREAD

**Issue by JCKodel** [Microsoft/BotBuilder#1707]
I'm building a bot for a 1st level help desk, something like:

1) Which are do you like? Products, Registration or Find a store?
2) What you want to know about products? The best product to do X? The applications of product X? Where to buy product X?

I was doing using form flow and, on completion, call or forward another flow (so I have one class for each flow, and there are thousand of them)

The problem is: when Forwarding a flow, the new flow stop responding (the prompt is executed, and any answer restart that flow - i.e. never hits .OnCompletion in the second flow =\

I was wondering: which is the best way to build complex, multi-branches bots without building a custom state machine framework on top of Bot Framework?

**Comment by chrimc62** [comment]
What you are describing with chaining FormFlow dialogs should work.  Can you share how you are moving between them?  In particular are you using FormOptions.PromptInStart?

**Comment by JCKodel** [comment]
Already solved with context.Call().
