### ISSUE TITLE
Can not pass result to builder.Prompt.text after go to other dialog

### ISSUE THREAD

**Issue by astrung** [Microsoft/BotBuilder#1712]
My bot flow :  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; It has a middle ware to check some special messages , then go to some special dialog to send some special messages before back to main waterfall flow.  
Example :  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Our middle ware :  

    bot.use({
    botbuilder: function (session, next) {
    switch (session.message.text.toLowerCase()) {
        case (session.message.text.toLowerCase().match(/why/) || {}).input:
          session.beginDialog('\why');
          break;
        ...
    }

In session.sessionState: 
![Dialog callstack](https://cloud.githubusercontent.com/assets/9162294/20513778/c582206c-b0ba-11e6-9978-96aa1c6f8b79.png)

"Why" dialog will send an message before back to previous dialog by calling `session.endDialogWithResult( session.message.text )` . And my previous dialog is `builder.Prompt.text`, so i want to pass `session.message.text` to Prompt, but i get this error :
 
`TypeError: Cannot create property 'resumed' on string 'why'`

So how to pass this string "why" to Prompt.text as a result ?

**Comment by astrung** [comment]
Well, can any one help ?

**Comment by astrung** [comment]
I think i need to use `IPromptResult<T>`, but i don't know how to convert it from message

**Comment by Stevenic** [comment]
Sorry for the delay. Can you show your code for 'why'?  From the error I'm assuming you're passing just a raw string into `endDialogWithResult()`. You should do `session.endDialogWithResult({ response: 'answer' });` instead.

**Comment by chrimc62** [comment]
@astrung are you still having the issue?

**Comment by astrung** [comment]
yes, still can not pass

**Comment by astrung** [comment]
"Why" dialog : 

    bot.dialog('/why', [
       function (session, results, next) {
       session.send("i am bot. Don't ask my reason ");
       session.endDialogWithResult({ response: session.message.text });
       }
    ]);

**Comment by Stevenic** [comment]
Oh I see... you're wanting your middleware+dialog to answer the prompt. that won't work... The prompt only looks at `session.message.text` for answers. So what you can do... Is change the value of `session.message.text` from your middleware.

**Comment by astrung** [comment]
Close. I have changed flows , and no need to use it
