### ISSUE TITLE
callback query from Telegram does not work properly

### ISSUE THREAD

**Issue by dimoibiehg** [Microsoft/BotBuilder#1716]
I have some problem in getting callback query from Telegram as I mentioned in [this issue](https://github.com/Microsoft/BotBuilder/issues/1568). In the final result, the solution was changing the result into a json string. I've done this and send the following message into the Telegram:

```CSharp
requestJson =  "{";
requestJson += "'method': 'answerInlineQuery',";
requestJson += "'parameters': {";
requestJson += "'inline_query_id': '" + queryId + "',";
requestJson += "'cache_time': 1,";
requestJson += "'results': '[\r\n  {\r\n    \"type\": \"photo\",\r\n    \"id\": \"" + Guid.NewGuid().ToString() + "\",\r\n    \"photo_url\": \"https://upload.wikimedia.org/wikipedia/en/archive/a/a9/20151112035044!Banyan_Tree_(_Shiv_Bajrang_Dham_Kishunpur).jpeg\",\r\n    \"thumb_url\": \"https://upload.wikimedia.org/wikipedia/en/archive/a/a9/20151112035044!Banyan_Tree_(_Shiv_Bajrang_Dham_Kishunpur).jpeg\",\r\n    \"reply_markup\": {\r\n      \"inline_keyboard\": [\r\n        [\r\n          {\r\n            \"text\": \"Click On Me\",\r\n            \"callback_data\": \"Click\"\r\n          }\r\n        ]\r\n      ]\r\n    }\r\n  }\r\n]'";
requestJson += "}";
requestJson += "}";
```

Also, the generated message is:

```CSharp
{
	'method': 'answerInlineQuery',
	'parameters': 
	{
		'inline_query_id': '479778282887174143',
		'cache_time': 1,
		'results': '
		[
			{
				"type": "photo",
				"id": "eb4f8fd5-cf36-492a-a198-746dc7eb7c0f",
				"photo_url": "https://upload.wikimedia.org/wikipedia/en/archive/a/a9/20151112035044!Banyan_Tree_(_Shiv_Bajrang_Dham_Kishunpur).jpeg",
				"thumb_url": "https://upload.wikimedia.org/wikipedia/en/archive/a/a9/20151112035044!Banyan_Tree_(_Shiv_Bajrang_Dham_Kishunpur).jpeg",
				"reply_markup": 
				{
					"inline_keyboard": 
					[
						[
							{
								"text": "Click On Me",
								"callback_data": "Click"
							}
						]
					]	
				}
			}
		]'
	}
}
```

As you can see the "results" field is a JSON string.

BUT, I can't get any callback message by clicking on "Click On Me" button.
So, any suggestion?

**Comment by chrimc62** [comment]
@eanders-MS can you help?

**Comment by eanders-MS** [comment]
Hi @dimoibiehg, I want to disambiguate something before trying to answer your question. The title of the issue mentions [callback query](https://core.telegram.org/bots/api/#answercallbackquery), but the code posted is answering an [inline query](https://core.telegram.org/bots/api/#inline-mode). Which one is correct?

Incidentally, I posted a simple Telegram inline query demo here: https://github.com/eanders-MS/BotFramework-Telegram-InlineQuery

I plan to post a demo for callback query later this week. Hopefully one of them will help answer your question.

**Comment by dimoibiehg** [comment]
Hi dear @eanders-MS, both of them are true. Indeed, I answered an inline query which contains a call back button. And it's expected pushing this button will send a callback query to our bot, so what is your suggestion for the title of the post?

Thanks for your demo, but it is in NodeJs and as I compared my stringify json is the same. 
Could you please say what's wrong with my code?

Thanks for planned demo.

**Comment by eanders-MS** [comment]
@dimoibiehg Can you describe what you're trying to accomplish? I think if we back up and help me better understand your goal, then the answer to the question of whether to use a callback query or inline query will become clear. In your code I see a mix of the two, and I'm not sure about which way to steer you.

**Comment by eanders-MS** [comment]
Ok after reading your earlier post again, I think you are correct in sending an inline query answer. Let me see if I can update my demo to include a button in the query results.

**Comment by eanders-MS** [comment]
@dimoibiehg It is possible that callback_data from an inline query answer choice is not a supported operation in Telegram. It may be that callback_data is only returned within a conversation. I recommend you reach out to `@BotSupport` on Telegram to get a definitive answer.

**Comment by dimoibiehg** [comment]
Dear @eanders-MS, you've found my scenario exactly. Indeed, the steps like the following:

1. User calls our inline bot in a page.
2. This query is received to the bot.
3. the bot processes this query as an inline query.
4. then it sends a response, which contains a callback button, to the user.
5. When the user gets the response, he clicks on the callback button.

My problem is in step 5: my bot cannot get the callback data which comes form  the callback button.

Ok. "It is possible that callback_data from an inline query answer choice is not a supported operation in Telegram", as you said. My guess was the same. However, it cannot be true! Because, there are some bot
in Telegram which works as we want. As a sample, **_you can see @like bot in Telegram_.**

**Comment by eanders-MS** [comment]
@like is a very cool bot! I too would like to understand how it works.

**Comment by dimoibiehg** [comment]
Dear @eanders-MS, also you can see @vote, @pollbot .

**Comment by eanders-MS** [comment]
Closing this issue now, as figuring out how those amazing bots work is out of scope for this repo.

**Comment by dimoibiehg** [comment]
@eanders-MS  why their work is out of scope for this repo?

**Comment by eanders-MS** [comment]
@dimoibiehg I believe that a bot like @like can be developed with BotBuilder using channelData to send native Telegram commands. You'll likely need to utilize the `switch_pm_text` and `switch_pm_parameter` fields of [answerInlineQuery](https://core.telegram.org/bots/api#answerinlinequery). The `switch_inline_query` field of [InlineKeyboardButton](https://core.telegram.org/bots/api#inlinekeyboardbutton) looks promising as well.

By out of scope, I only mean it is out of scope for my team to try to reverse engineer these bots.

**Comment by asajm** [comment]
Dear @eanders-MS, when I run your kind Telegram inline query demo, this error occurs:-

> Error: Request to 'https://telegram.botframework.com/v3/conversations/6490389/activities/27876009817840541' failed: [500] Internal Server Error
    at Request._callback (/Users/ABC/projects/XYZ/messages/node_modules/botbuilder/lib/bots/ChatConnector.js:523:46)
    at Request.init.self.callback (/Users/ABC/projects/XYZ/messages/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/ABC/projects/XYZ/messages/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/ABC/projects/XYZ/messages/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)

and this is a sample of incoming channel_data:-
> {
    "update_id": 875506629,
    "inline_query": {
        "id": "27876009817840541",
        "from": {
            "id": 6490389,
            "first_name": "Ahmed",
            "last_name": "Almalki",
            "language_code": "en-SA"
        },
        "query": "",
        "offset": ""
    }
} 

this error also occurs when send an answer ([answerCallbackQuery](https://core.telegram.org/bots/api#answercallbackquery)) on an incoming update ([CallbackQuery](https://core.telegram.org/bots/api#callbackquery)).
