### ISSUE TITLE
How to cancel a FormFlow when Validating

### ISSUE THREAD

**Issue by pcbarroso** [Microsoft/BotBuilder#1717]
I have a Form in my bot, but at any time the user may want to cancel and continue later. I'm using FormFlow (new FormBuilder) and what I want is to in the validate methods check if the user send a specific word like 'EXIT' and if so to cancel the form and go back to context.wait().

Is there a way to stop the form? I can't find a way to access the context before onCompletion

**Comment by chrimc62** [comment]
There is a built-in cancel.  You can override the terms if you need to by specifying your terms in FormConfiguration.Commands[FormQuit].  If that doesn't work for you, you can also use Scorables to have commands override.

**Comment by chrimc62** [comment]
@pcbarroso did this solve your problem?
