### ISSUE TITLE
Send custom parameter in `session` object

### ISSUE THREAD

**Issue by sriharshakappala** [Microsoft/BotBuilder#1718]
I am new to bot framework. I am building a bot in the context of a web application where the user can ask something like this - 'What's my schedule today?' So for this to work I have to authenticate the chat message with a custom token that is in my database. This way I can fetch that particular user's tasks from the database. But I am unable to send a custom parameter to and fro session object. Not able to find anythig promising on internet. Stuck on this! :( Is that even possible?

**Comment by Stevenic** [comment]
You can store the token in `session.userData` which will make it available to all of your dialogs.

**Comment by dandriscoll** [comment]
Closing as it appears the question was answered. Please feel free to open a new issue if you'd like to discuss further. Thanks!
