### ISSUE TITLE
 Conversation.SendAsync don't throw exception

### ISSUE THREAD

**Issue by wiltodelta** [Microsoft/BotBuilder#172]
And return message with empty text.

**Comment by msft-shahins** [comment]
This should be fixed with the following [commit aa6487](https://github.com/Microsoft/BotBuilder/commit/aa6487aec293256c371e1fca71411e7e77e38e9d). Next release should have this fix.

**Comment by wiltodelta** [comment]
@msft-shahins 1.1.0?

**Comment by msft-shahins** [comment]
No. This chnage didn't make it to 1.1.0. It is still in develop branch.
