### ISSUE TITLE
Carousel Cards working in Emulator but not working on WebChat

### ISSUE THREAD

**Issue by sriharshakappala** [Microsoft/BotBuilder#1722]
I am trying out this example on Carousel Cards - https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node/cards-CarouselCards

I am able to see the Carousel Cards on Emulator but the same when tried on WebChat I am getting the result as a conversation bubble but not as a Carousel Card. 

Attaching screenshots!

**On Emulator**

![screenshot from 2016-11-23 14-28-35](https://cloud.githubusercontent.com/assets/3955701/20556572/c968220c-b18d-11e6-8986-237a5db2cd11.png)

**On WebChat (Embedded via an iframe)**

![screenshot from 2016-11-23 15-01-05](https://cloud.githubusercontent.com/assets/3955701/20556626/04463c06-b18e-11e6-93f2-cef72ccd4bc7.png)

Dependencies

```json
"dependencies": {
   "botbuilder": "^3.2.3",
   "restify": "^4.1.1"
 }
```

**Comment by dandriscoll** [comment]
Hi @sriharshakappala, cards are supported in the preview version of the web chat control.

To enable the preview, visit the Web Chat configuration page for your bot and click the "Enable web chat preview" checkbox near the bottom of the page.

**Comment by sriharshakappala** [comment]
Thanks @dandriscoll It worked. I added a new site in the Web Chat configuration page, enabled preview and updated secret in my iframe.

However, It looks like welcome message from bot has been deprecated in preview version. Is that how it was supposed to be or is it a bug?

Attaching a side by side screenshot!

**Left - With preview disabled, Welcome message, Carousel Cards not working
Right - With preview enabled, No Welcome message, Carousel Cards working**

![screenshot from 2016-11-24 08-44-49](https://cloud.githubusercontent.com/assets/3955701/20585669/e58d0bc4-b222-11e6-9b16-af430ab65267.png)

**Comment by sriharshakappala** [comment]
@dandriscoll Is #1718 possible?

**Comment by dandriscoll** [comment]
Hi @sriharshakappala, that's correct, the new web chat control no longer displays a hardcoded welcome message. Instead, you bot can send a message when it receives the ConversationUpdate activity.

**Comment by sriharshakappala** [comment]
Okay! Got it. Thanks a lot @dandriscoll
