### ISSUE TITLE
Web Chat BOT: Font changed

### ISSUE THREAD

**Issue by shahsagarin** [Microsoft/BotBuilder#1723]
We have BOT embedded on a web page through Web Channel. As of today, we observed that font style has changed for BOT as shown below:

![today](https://cloud.githubusercontent.com/assets/8536246/20559655/a3d2c3f4-b19b-11e6-929d-8384070a5aaf.png)

Previously the font style was a bit different as shown below:
![yesterday](https://cloud.githubusercontent.com/assets/8536246/20559658/a8e62106-b19b-11e6-9280-53f8923fb1a3.png)

Is there a way to revert the font style back to it's previous one? Because it is not matching with our website font

**Comment by dandriscoll** [comment]
Hi @shahsagarin, we recently fixed a number of bugs in the web chat control, and one of them must have been causing inconsistent styling. (The new font is the styling we intended.)

If you'd like additional control over the control styling, you should consider our new web chat control, which is available as a React component and an open-source lib so you can customize the style and functionality if you want. Details are here: https://github.com/Microsoft/BotFramework-WebChat

**Comment by dandriscoll** [comment]
This should be fixed now. @shahsagarin, can you give it another shot?

**Comment by shahsagarin** [comment]
Works for me, thanks for the quick fix
