### ISSUE TITLE
GraphBot Getting Started

### ISSUE THREAD

**Issue by R2dical** [Microsoft/BotBuilder#1728]
Is there any documentation for how to use the Microsoft.Bot.Sample.GraphBot. Spent a while but could not really get anywhere.

Like how to link to AAD, register the bot, debug and test, etc?

**Comment by willportnoy** [comment]
https://github.com/MicrosoftDX/AuthBot might be a better place to start.

**Comment by willportnoy** [comment]
I'm going to close this issue for now, but feel free to open a new issue for further discussion.
