### ISSUE TITLE
keeping more than one conversation open

### ISSUE THREAD

**Issue by imangoodarzi** [Microsoft/BotBuilder#173]
My bot is supposed to handle different types of conversations and I'd like to design the dialogs separately. How can I achieve that? From the tutorial example, MessagesController Post method does the Conversation.SendAsync and that method picks up the dialog state encoded inside the message and goes from there (which is always going to be the dialog that is first initiated)

From what I understood, there should only be one root dialog that catches everything and that can contain other dialogs inside it. Is that right?

**Comment by zobnov** [comment]
Hi, as I see it, there is one root dialog, but you may add any logic into it, and start (switch, rout to) any dialogs. Could you give a bit more details on what you want to build?
Please also check this example, it describes a possible way to switch between dialogs: https://github.com/Microsoft/BotBuilder/blob/master/Node/examples/basics-firstRun/app.js
Also this example might be helpful: https://github.com/Microsoft/BotBuilder/tree/master/Node/examples/basics-multiTurn

**Comment by Stevenic** [comment]
I think he's asking about the C# version of the library.

**Comment by willportnoy** [comment]
Your statement "From what I understood, there should only be one root dialog that catches everything and that can contain other dialogs inside it. Is that right?" is correct.  You can use your root dialog to dispatch to different child dialogs to have different types of conversation.  It won't always start with the root dialog, though - it will resume with whatever dialog suspended last for that conversation and user.  So every conversation and user will have a different active dialog stack.

**Comment by imangoodarzi** [comment]
Yes I'm working with the C# SDK. What I want to achieve is:
- There are two tasks A and B (potentially there will be more task types) that should be done by the bot. A and B are totally different with no relation to each other.
- Tasks are complicated enough that they have nested dialogs with different states modelled for them.
- Message "do Task A" should initiate dialog to complete task A and "do task B" should do for task B
- Tasks should be accomplished in parallel, meaning if the user is in the middle of the dialog to complete "A" if he says "do task B", expectation is to suspend task A and start task B (or even if the decision is to not start task B until task A is done, the appropriate message should be coming from task B's dialog).
- Tasks implementations is good to be as decoupled as possible.

I see no problem having a root dialog and do the routing there but I don't want to handle all between-the-tasks-transitions inside the root as I think it's going to make the root very bulky and unmanageable.

**Comment by willportnoy** [comment]
Fyi, we're looking at methods to address this need.

**Comment by willportnoy** [comment]
I have committed some changes to the develop branch in this direction, to allow dialog stack introspection, enabling "task switching" of sorts, if you have any feedback.

https://github.com/Microsoft/BotBuilder/commit/f3c04792e2b8b0f21d5099024fb9d2e1b3b14179

**Comment by willportnoy** [comment]
Closing this issue for now - feel free to re-open to discuss.
