### ISSUE TITLE
[Facebook Messenger] Can't receive "message_reads" from FB Messenger platform

### ISSUE THREAD

**Issue by ykensuke** [Microsoft/BotBuilder#1730]
Is there any way to receive "message_reads" event from Facebook Messenger platform? I think it's great if we can get raw requests from each platform, because they are frequently updating their platforms. MS can't support all the updates as soon as they update.

**Comment by JpEncausse** [comment]
+1 would be interested if we can know when a message form Messenger has been read

@ykensuke did you find a work around ?

**Comment by ykensuke** [comment]
@JpEncausse No I haven't yet. Message echo is the similar issue, but MS haven't reacted anything about it. https://github.com/Microsoft/BotBuilder/issues/2260

**Comment by bmperrea** [comment]
Perhaps you could use middleware as I just did in #2285. Same goes for #2260.

**Comment by craigjensen** [comment]
We currently don't support message_read events but it should be possible to forward them to your bot via ChannelData/SourceEvent.  Would this work for you?

**Comment by michaelvol** [comment]
For us getting it via channel data would be great.
Afaiu it's not forwarded yet, right?
