### ISSUE TITLE
Facebook Prompt options gets trimmed.

### ISSUE THREAD

**Issue by alokraj68** [Microsoft/BotBuilder#1735]
After facebook integration, in facebook messenger and all FB platforms, all my options for prompt gets trimmed so the user does not actually see the prompt option text completely.

eg : "Yes, I wan......." for "Yes, I want to continue"
This actually affects the user experience.

is there any way to turn off that trim?

help needed.

**Comment by chrimc62** [comment]
How long is your message?  Many channels have a maximum length they allow.

**Comment by alokraj68** [comment]
It gets trimmed at 301 characters at facebook.

**Comment by chrimc62** [comment]
If that was not the issue, please reopen.
