### ISSUE TITLE
Implement PromptDialog.Time in .NET SDK.

### ISSUE THREAD

**Issue by Deilan** [Microsoft/BotBuilder#1736]
It is already implemented in Node.js SDK, [as per documentation](https://docs.botframework.com/en-us/node/builder/chat/prompts/#promptstime). Would like to see that happen in .NET SDK also.

**Comment by chrimc62** [comment]
Thanks for the suggestion, I have added this to our backlog.

**Comment by msft-shahins** [comment]
closing this since it is tracked in our backlog.
