### ISSUE TITLE
Connection error when bot is published to Bot Framework

### ISSUE THREAD

**Issue by torhhu** [Microsoft/BotBuilder#1739]
Hi,

I've had a first version of a potential demo bot up and running for a long time, and now I've updated the bot with extended functionality. However, even though the new version of the bot is running flawlessly in Visual Studio debug, I receive a connection error when it is published. I can't really make sense of the error message, and don't really see what changes I've made that should cause this (even though I've made a lot of changes...). Any help is much appreciated.
`InternalServerError
{
  "message": "An error has occurred.",
  "exceptionMessage": "Precondition Failed",
  "exceptionType": "Microsoft.Rest.HttpOperationException",
  "stackTrace": "   at Microsoft.Bot.Connector.ErrorHandling.<HandleErrorAsync>d__1`1.MoveNext()\r
  \n--- End of stack trace from previous location where exception was thrown ---\r
  \n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r
  \n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r
  \n   at Microsoft.Bot.Connector.BotStateExtensions.<SetUserDataAsync>d__3.MoveNext()\r
  \n--- End of stack trace from previous location where exception was thrown ---\r
  \n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r
  \n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r
  \n   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r
  \n   at Microsoft.Bot.Sample.SimpleEchoBot.MessagesController.<Post>d__1.MoveNext()\r
  \n--- End of stack trace from previous location where exception was thrown ---\r
  \n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r
  \n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r
  \n   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()\r
  \n--- End of stack trace from previous location where exception was thrown ---\r
  \n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r
  \n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r
  \n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r
  \n--- End of stack trace from previous location where exception was thrown ---\r
  \n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r
  \n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r
  \n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\r
  \n--- End of stack trace from previous location where exception was thrown ---\r
  \n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\r
  \n--- End of stack trace from previous location where exception was thrown ---\r
  \n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r
  \n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r
  \n   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()\r
  \n--- End of stack trace from previous location where exception was thrown ---\r
  \n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r
  \n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r
  \n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r
  \n--- End of stack trace from previous location where exception was thrown ---\r
  \n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r
  \n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r
  \n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"
}
`

**Comment by willportnoy** [comment]
Here is some more information about 412/409:

https://docs.botframework.com/en-us/technical-faq/#what-causes-precondition-failed-412-or-conflict-409-http-errors
https://docs.botframework.com/en-us/technical-faq/#how-can-i-fix-precondition-failed-412-or-conflict-409-http-errors

and here is some more background:

https://docs.botframework.com/en-us/technical-faq/#where-is-conversation-state-stored
https://docs.botframework.com/en-us/technical-faq/#what-is-an-etag--how-does-it-relate-to-bot-data-bag-storage

I'm happy to answer further questions.

**Comment by torhhu** [comment]
Thank you. I was (unnecessarily) trying to save the state several times. Fixed that and my bot is now working as expected.
