### ISSUE TITLE
When user adds a question mark to the end of his question, help menu pops up

### ISSUE THREAD

**Issue by bluekite2000** [Microsoft/BotBuilder#174]
When user types "Is tim available on friday?" the following pops up
•	You are filling in the request field. Possible responses:
•	You can enter anything (use "'s to force string).
•	Back: Go back to the previous question.
•	Help: Show the kinds of responses you can enter.
•	Quit: Quit the form without completing it.
•	Reset: Start over filling in the form. (With defaults of your previous entries.)
•	Status: Show your progress in filling in the form so far.
•	You can switch to another field by entering its name. (Request).

Is this a bug?

**Comment by chrimc62** [comment]
Yes, this is a bug--thanks for bringing it to our attention.  I'm working on a fix and our next release will fix it.

**Comment by chrimc62** [comment]
Fix is checked-in and will be in our next release.
