### ISSUE TITLE
Skype Carousel actions are disabled

### ISSUE THREAD

**Issue by spreddy2714** [Microsoft/BotBuilder#1742]
I am using Carousel layout with one/several hero cards as attachments to the message.
each card have button of dialogAction.
It is working fine in Emulator, and facebook messenger too able to perform click action on those buttons.

How ever in skype they are disabled. I wonder why is this happening?

![image](https://cloud.githubusercontent.com/assets/6649902/20642276/0f783c28-b431-11e6-89ee-8f28366d4473.png)

**Comment by nickcordrey** [comment]
Make sure that the URLs are HTTPS.

**Comment by spreddy2714** [comment]
I don't understand what you are saying, bot service api is already https. What else you are mentioning as https here?

**Comment by nickcordrey** [comment]
Please ensure that the URLs to any images referenced in your button actions are HTTPS.
________________________________

**Comment by spreddy2714** [comment]
The action is dialog action
Here is the code
builder.CardAction.dialogAction(session, 'ShowQuestion', question.id, 'Open')

It doesn't have any url references.

**Comment by dandriscoll** [comment]
@Stevenic or @carlosscastro, what kind of action will the call to .dialogAction produce in this case? Will it be openUrl, imBack, postBack, etc.? How could we find out which one?

**Comment by carlosscastro** [comment]
@dandriscoll It is of type postBack. [Here ](https://github.com/Microsoft/BotBuilder/blob/master/Node/core/src/cards/CardAction.ts#L112)is the line of code that makes it postBack.

**Comment by dandriscoll** [comment]
Ahh, thanks @carlosscastro.

Hi @spreddy2714, postBack is not currently supported in Skype. Can you switch to imBack and see if that works?

**Comment by spreddy2714** [comment]
Is there any timeline to expect it to be supported on dialogAction directly instead?
I am currently got it worked with imBack .

**Comment by nickcordrey** [comment]
postBack is now supported by Skype. Please could you retest and confirm that dialogAction works as expected?
