### ISSUE TITLE
Skype Carousel Compatibility

### ISSUE THREAD

**Issue by spreddy2714** [Microsoft/BotBuilder#1743]
Does skype supports carousel layout?
I have played with several skype apps. The response is never intended one
1.Skype for desktop : Ek, currently I can't support this message
2.Skype Preview : Rendering is problem with actions buttons are disabled
3.Skype Web : Ek, currently I can't support this message
4.Skype Android : Ek, currently I can't support this message

I don't understand how to get this right :(

**Comment by chrimc62** [comment]
@nickcordrey could you comment?

**Comment by spreddy2714** [comment]
This is node.js implementation by the way!
Am I alone facing this? I am really in dire need of this.

**Comment by dandriscoll** [comment]
Hi @spreddy2714, Skype does support Carousels. The errors you see in the UI are caused by problems within the Card or Action. Can you describe the kind of Card/Action you're trying to generate?

**Comment by spreddy2714** [comment]
This is related to this
https://github.com/Microsoft/BotBuilder/issues/1742

Wish there could be some kind of compatibility matrix to better know what exactly are supported where?

**Comment by nickcordrey** [comment]
It looks like the root cause was the postback action. postBack is now supported by Skype. Please could you retest and confirm that the carousel works as expected?
