### ISSUE TITLE
npm install of BotBuilder uses depricated uuid module

### ISSUE THREAD

**Issue by cleemullins** [Microsoft/BotBuilder#1744]
Running through the tutorials found here:
https://docs.botframework.com/en-us/node/builder/overview/

The first real step is "Install the Bot Builder":
npm install --save botbuilder

This immediately gives a warning:
npm WARN deprecated node-uuid@1.4.7: use uuid module instead

Everything else went smoothly during the install process.

**Comment by palmerabollo** [comment]
Yes, "node-uuid" has been recently deprecated in favor of "uuid". It's not a big issue (just a deprecation notice) but it should be easy to fix it.

**Comment by Stevenic** [comment]
Thanks... I'll take a look.

**Comment by Stevenic** [comment]
I've checked in a fix that will go out with next release.

**Comment by cleemullins** [comment]
Fantastic! Thanks Steve!

**Comment by Stevenic** [comment]
Just pushed update.
