### ISSUE TITLE
Animation card crashing ios app and card not supported in windows 10 skype preview app

### ISSUE THREAD

**Issue by puneetsngh** [Microsoft/BotBuilder#1745]
I implemented the animation card but it is crashing the apps. Please add support for new bot cards in your apps.

**Comment by konstlut** [comment]
@puneetsngh Could you please check if this is still an issue, and if yes - could you please provide a sample that crashes the application. Thanks!

**Comment by nickcordrey** [comment]
Please also make sure you include a thumbnail with each card and confirm if it still causes an issue in client.

**Comment by puneetsngh** [comment]
sorry for late reply but it still not working on ios client and yes im inlcuding the thumnail but still....the web client able to play it but not the phone client.

![image](https://cloud.githubusercontent.com/assets/16202640/23719515/c00220b0-0461-11e7-8e1f-7060a73e3077.png)

![image](https://cloud.githubusercontent.com/assets/16202640/23719523/c7f71d0c-0461-11e7-9271-3e8a86d6c4dc.png)
