### ISSUE TITLE
Video card is also unsupported

### ISSUE THREAD

**Issue by puneetsngh** [Microsoft/BotBuilder#1746]
I am using youtube urls for video card

and the results are these below which show me unsupported thumbnail. If youtube is not supported then what kind of videos does these card support? Do I have to add the direct url of a video file for these cards?

![image](https://cloud.githubusercontent.com/assets/16202640/20648910/2b253e0a-b4d9-11e6-8a96-eb2dd4660057.png)

**Comment by nickcordrey** [comment]
Skype does not yet fully support Bot Framework video cards although this is coming soon. The URL should be to the source of the video.
