### ISSUE TITLE
Using Google Analytics

### ISSUE THREAD

**Issue by sitver** [Microsoft/BotBuilder#1747]
Hey. I see there's a file in the Node SDK for [using Google Analytics](https://github.com/Microsoft/BotBuilder/blob/master/Node/core/docs/botframework/partials/analytics.hbs). Is there a tutorial for setting this up? What does this track?

Best,

Michael

**Comment by maxpert** [comment]
It's the analytics code for documentation not for **SDK**. If you want to use analytics for your bot you can integrate something npm like [universal-analytics](https://www.npmjs.com/package/universal-analytics).
