### ISSUE TITLE
Test Luis Bot in Bot Emulator running behind proxy

### ISSUE THREAD

**Issue by senthil2m** [Microsoft/BotBuilder#1752]
Hi,

I have the bot running without security enabled by making AppId and password as null in the node js sample. My bot invokes luis call and it initiates the conversation based on the matched intent.
I get the below timeout error when I test in Emulator running behind the closed corporate network.
![error](https://cloud.githubusercontent.com/assets/22318545/20669809/185c1d66-b59c-11e6-9c35-21f9d2343262.png)
I am not sure which call gets blocked within the proxy network. 
I need to test the bot in the emulator behind the proxy. No problem even if the security is disabled.
Also, please share the list of bot URLs which are blocked in the closed network so that we can raise the request to our network team to enable access for them.

Thanks,
Senthil M

**Comment by dandriscoll** [comment]
Hi @senthil2m, there are multiple LUIS service URLs. One of them is https://api.projectoxford.ai/luis/v1/application. The bot also uses Microsoft login and key servers when auth is enabled.
