### ISSUE TITLE
Unit testing bot framework with node.js

### ISSUE THREAD

**Issue by morsh** [Microsoft/BotBuilder#1753]
Hi,
I'm trying to unit test the api of my bot.

In the test environment I don't supply an app id and password but when running the following code with mocha, I get a 401 reply:

```js
process.env.NODE_ENV = 'test';

var chai = require('chai');
var chaiHttp = require('chai-http');
var server = require('../index');
var should = chai.should();

chai.use(chaiHttp);

describe('Test', () => {
  describe('/POST new conversation', () => {
      it('it should GET all the books', (done) => {
        chai.request(server)
            .post('/api/messages')
            .set('content-type', 'application/json')
            .send({ info: 'bla'})
            .end((err, res) => {
                res.should.have.status(200);
                res.body.should.be.a('array');
                res.body.length.should.be.eql(0);
              done();
            });
      });
  });
});
```

Hope you know how I can fix this :)

**Comment by willportnoy** [comment]
Messages are sent back to the connector service through separate http calls, which could return status code  401 without proper authorization.  Do you intend to mock that service as well?

There are some tests in https://github.com/Microsoft/BotBuilder/tree/master/Node/core/tests that you might want to model your tests on.

**Comment by Stevenic** [comment]
Yes... Testing at this low of a level could be tough for numerous reasons... If you look at the unit tests Will referenced you'll see examples of using the `ConsoleConnector` to test your bot. This would be much easier.

**Comment by morsh** [comment]
@Stevenic using console connector does the job keeping in mind that the bot dialog \ intents should be populated from a separate file to enable testing.
