### ISSUE TITLE
How to customize error message sent to an end-user when bot's endpoint is unavailable?

### ISSUE THREAD

**Issue by Deilan** [Microsoft/BotBuilder#1754]
If a user sends message to a bot while it's endpoint is unavailable or failed processing the message, the user receives an error message from Bot Connector, which seems like that:

> POST to **{SomeArbitraryBot}** failed: POST to the bot's endpoint failed with HTTP status 502

or
> POST to **{SomeArbitraryBot}** failed: A task was canceled.

etc.

Is there a way to customize logic of sending error message or to suppress it at all in such a case?

**Comment by dandriscoll** [comment]
Hi @Deilan, is this a v1 bot or a v3 bot?

The behavior was changed in v3 so that the Bot Connector returns an error to the channel but does not generate error text.

**Comment by Deilan** [comment]
It's all about the latest version: v3.

As a matter of fact this behaviour (to send error or not; if yes, then what message text to send) should be customizable. Exposing the technical issues and details to the end-users is usually undesirable (unless it's debugging or testing).

**Comment by dandriscoll** [comment]
Which channel are you using? There may be a bug in the way that channel is handling errors.

**Comment by Deilan** [comment]
@dandriscoll I am using Telegram.

**Comment by dandriscoll** [comment]
Yep, looks like a bug. Thanks @Deilan.

**Comment by Deilan** [comment]
@nwhitmont And... what is the answer? :) Having this one added to the internal backlog?
