### ISSUE TITLE
Bot in Node.js

### ISSUE THREAD

**Issue by sravaniVajjha** [Microsoft/BotBuilder#1755]
How to build a bot in node.js using visual studio as my IDE

**Comment by sc0ttwad3** [comment]
How about Visual Studio Code that also has easy debugging https://docs.botframework.com/en-us/node/builder/guides/debug-locally-with-vscode/#navtitle

**Comment by danmarshall** [comment]
Take a look at some samples to begin with. You can use any IDE that you prefer:
https://github.com/Microsoft/BotBuilder/tree/master/Node/examples
https://github.com/Microsoft/BotBuilder-Samples

**Comment by danmarshall** [comment]
@willportnoy do we have a VS project template?

**Comment by willportnoy** [comment]
@danmarshall I don't know of a Node SDK VS project template.

**Comment by danmarshall** [comment]
@sravaniVajjha have you seen https://www.visualstudio.com/vs/node-js/

**Comment by danmarshall** [comment]
Closing this issue for now. @sravaniVajjha if you have any more specific questions please open a new issue, thanks.
