### ISSUE TITLE
Can we implement autocomplete box while typing any text as input for command

### ISSUE THREAD

**Issue by immaddy718** [Microsoft/BotBuilder#1756]
I had implemented Skype-Bot 
Can we implement autocomplete box while typing any text as input for command?
Suppose my command: 
* **get project {[List]}**
{[List]} this list can be limited but can write only one at a time.
When i type get project instantly i was to populate the autocomplete box with the available project.
Is it possible for doing it so.

Thanks,
Praveen Madas

**Comment by danmarshall** [comment]
Which channel are you suggesting?

**Comment by danmarshall** [comment]
Hi @immaddy718 I have marked this as an enhancement. It would require that channel clients (such as Skype / Facebook / Kik) implement this, which is probably unlikely.
