### ISSUE TITLE
Image not get fit inside herocard,Thumbnail card.

### ISSUE THREAD

**Issue by chetanmekha** [Microsoft/BotBuilder#1758]
Hello Folks,
I want to set image in hero/thumbnail card within cards boundaries. The image get set to card but not getting fit inside card. how can i achieve it. Please guide me.

**Comment by danmarshall** [comment]
Which channel are you using?

**Comment by abhishan** [comment]
I have faced similar issue with using Skype channel. The image kept getting scaled down and then cropped on the upper and lower edges. The image dimension was 512x512.

**Comment by chetanmekha** [comment]
I tried with facebook and skype and getting the same issue.

**Comment by dandriscoll** [comment]
Hi @chetanmekha and @abhishan, the behavior depends on the channel.

For Facebook, the image will be displayed uncropped if the aspect ratio is 1.91:1. You can see documentation here: https://developers.facebook.com/docs/messenger-platform/send-api-reference/generic-template

For Skype, I don't have the aspect ratio handy, but I've asked the Skype team to help clarify.

**Comment by chetanmekha** [comment]
Hello Team, 
Thanks for the feedback. I am little bit excited regarding Image scaling functionality, up to when we can expect this to get's delivered to us?

**Comment by nickcordrey** [comment]
The aspect ratio for Skype is 16:9 (see https://docs.botframework.com/en-us/skype/getting-started/#cards-and-buttons). The image is scaled (while maintaining the aspect ratio) up or down in size until it minimally covers the image space, and then cropped horizontally and vertically from the center.

**Comment by sajadhaja** [comment]
Is it possible to limit no of images to show in screen with any parameter? 
Also image size in not able to get reduced?
Please help me

**Comment by singhsurya** [comment]
Please add a feature in hero card and thumbnail card to fix the size of the image. @dandriscoll

**Comment by EricDahlvang** [comment]
@singhsurya You are commenting on a closed issue. If you have a new feature request, please open a new issue.

However, as stated by Dan earlier in this thread: the channel is responsible for image size rendering.  So, a feature request to allow specifying image size would most likely need to be filed with the channel's forum.
