### ISSUE TITLE
Doesn't receive voice message in Telegram

### ISSUE THREAD

**Issue by wiltodelta** [Microsoft/BotBuilder#176]
Subj

**Comment by Stevenic** [comment]
Can you please clarify?

**Comment by wiltodelta** [comment]
@Stevenic When I send an image to bot, I receive a message with an attachment. This doesn't happen with a voice message.

**Comment by eanders-MS** [comment]
@wiltodelta Fixed and will be available in the next release to production.

**Comment by wiltodelta** [comment]
@eanders-MS How can I find out about new backend releases?
