### ISSUE TITLE
dialogAction is not working in skype

### ISSUE THREAD

**Issue by spreddy2714** [Microsoft/BotBuilder#1760]
With respect to issue I've created before https://github.com/Microsoft/BotBuilder/issues/1742

I found that skype is failing when my card action is dialogAction, it worked fine for openUrl.

Can some body please help me how to get this right with node js implementation.

**Comment by dandriscoll** [comment]
Hi @spreddy2714, I noticed that in #1742, you were also asking about Node.js dialogActions in Skype. Is this the same question or a different question?

**Comment by dandriscoll** [comment]
Closing as this appears to be a duplicate issue. Please at-mention or open a new issue if you'd like to discuss further.
