### ISSUE TITLE
Skype: video attachment does not show preview thumbnail

### ISSUE THREAD

**Issue by euanlau** [Microsoft/BotBuilder#1761]
I sent the message below and users on Skype did receive the video properly. However, there is no thumbnail preview shown in the skype UI. Is there anything I can do to make it happen?

```
     var msg = new builder.Message(session)
            .attachments([{
                contentType: "video/mp4",
                contentUrl: "http://mysite.com/somevideo.mp4"
            }]);
```

**Comment by nickcordrey** [comment]
Please specify a ThumbnailUrl to send an explicit thumbnail.

**Comment by euanlau** [comment]
@nickcordrey I just tried this. Once I added the thumbnail, I was not able to play the video anymore on both Skype Mac and iOS clients.
