### ISSUE TITLE
DTraceProviderBindings error on startup

### ISSUE THREAD

**Issue by agrawal-mohit** [Microsoft/BotBuilder#1764]
Following the steps as give here - https://docs.botframework.com/en-us/node/builder/overview/

When i do `node app.js` , this is the response on terminal:

```
{ [Error: Cannot find module './build/Release/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Release/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
restify listening to http://[::]:3978
```

The response on the browser when I hit 127.0.0.1:3978 is :

> {"code":"ResourceNotFound","message":"/ does not exist"}

I have tried  `npm install dtrace-provider` but that does not help.

**Environment**
 OSX 10.10.5 Yosemite
node v4.5.0
xcode version 7.0 (7A220)

**Comment by willportnoy** [comment]
I would think DTrace is unrelated - it's a system-wide profiling/monitoring tool.

Usually you post the activity object to https://127.0.0.1:3978/api/messages rather than a root path.

**Comment by danmarshall** [comment]
Check the restify issues for potential installation solutions:
https://github.com/restify/node-restify/issues/897

**Comment by danmarshall** [comment]
Hi @agrawal-mohit I'm going to close this for now, please create a new issue if you run into any further problem.
