### ISSUE TITLE
.NET Core

### ISSUE THREAD

**Issue by NicolasHumann** [Microsoft/BotBuilder#1767]
Hi,

Any plans to have bot builder running with .net core ?
It will be nice to have a bot running in docker / linux.
May be the release of .NET standards 2.0 and VS 2017 will enable this !?!

**Comment by willportnoy** [comment]
relevant issue: https://github.com/Microsoft/BotBuilder/issues/572

**Comment by willportnoy** [comment]
I'm going to close this issue as a duplicate of https://github.com/Microsoft/BotBuilder/issues/572.
