### ISSUE TITLE
Wrong markdown rendering of lists in Telegram

### ISSUE THREAD

**Issue by zobnov** [Microsoft/BotBuilder#177]
I run an example bot [testBot] (https://github.com/Microsoft/BotBuilder/tree/master/Node/examples/testBot), and see lists rendered wrong in web and iOS versions:
![image](https://cloud.githubusercontent.com/assets/2109482/14764409/38921ba0-09bf-11e6-9987-d60673cb8819.png)
The expected behaviour would be to fall back to the plain text (e.g. removing the leading '*') just as it works for Skype.

**Comment by eanders-MS** [comment]
@zobnov Issue has been fixed and will be available in the next release to production.
