### ISSUE TITLE
Add actual request examples to BotConnector REST API docs

### ISSUE THREAD

**Issue by abelnation** [Microsoft/BotBuilder#1770]
These docs are embarassing:
https://docs.botframework.com/en-us/restapi/connector/#!/Conversations/Conversations_CreateConversation

Please update the docs to show proper examples of valid json to send in the body of the request.  I appreciate that you show me what to expect as a response, but that's not really any help if I don't know what my request bodies should look like.

Apologies if this is the wrong forum for this feedback, feel free to direct it to the REST API team. 

Thanks.  

P.S. I see some examples [here](https://docs.botframework.com/en-us/core-concepts/conversation/#navtitle), but, if anything, the endpoint reference page should be the canonical location for example requests.

**Comment by ejadib** [comment]
The body is explained in that page....

![image](https://cloud.githubusercontent.com/assets/307826/20818502/c49dab22-b80c-11e6-8fa0-ceb198d4eee4.png)

**Comment by abelnation** [comment]
DOH!

My browser was sized/zoomed such that that section was cut off (and the div is not scrollable when cut off)!  Sorry for the flame-y message!

![image](https://cloud.githubusercontent.com/assets/200054/20818927/d9e3693a-b7e5-11e6-8c95-fb908122b683.png)

**Comment by abelnation** [comment]
Though, to be fair, the page really does require quite a large width for that info to be visible, combined w/ the non-scrollability, this feels like it could be improved.  I'm currently on quite a large monitor.  

Here's a screenshot, browser set to half of my standard apple monitor width, 100% zoom:
![image](https://cloud.githubusercontent.com/assets/200054/20818985/43b0a15c-b7e6-11e6-8d16-931650881976.png)
