### ISSUE TITLE
slack interactive messages not working

### ISSUE THREAD

**Issue by seaneiros** [Microsoft/BotBuilder#1772]
Hi, I have two bots connected to slack (node sdk, different apps, different teams), they're both configured according to manual and work as expected, except one of them, it fails to handle interactive messages: the app calls builder.Prompts.choice(...), buttons appear and after clicking them nothing happens...just the same dialog, the same buttons and "There was an error sending this message to your bot." message in logs; but typing 1 or 2 (or another option index) makes it work. Please can you help me with that?

**Comment by seaneiros** [comment]
it turned out the issueis only reproduced on our stage server, setting bot's endpoint to dev's station makes the thing, but still...what can be the problem? are there any specific endpoint requirements?

**Comment by danmarshall** [comment]
No there are no specific endpoint requirements, It sounds as if your staging server might be secured somehow, I I were to guess.

**Comment by seaneiros** [comment]
Seems so...any ways to get the error stack other than "There was an error..." ?
