### ISSUE TITLE
Add support for wit.ai and api.ai recognizers

### ISSUE THREAD

**Issue by GanadiniAkshay** [Microsoft/BotBuilder#1773]
I have prototyped the code for recognizer code for witRecognizer and apiaiaRecognizer on lines similar to LUISRecognizer.

How can I build the project and can I contribute this as a PR? 

**EDIT** : link to api-ai-recognizer npm module https://www.npmjs.com/package/api-ai-recognizer

**Comment by willportnoy** [comment]
I presume this is for the Node version of the SDK?

**Comment by GanadiniAkshay** [comment]
@willportnoy  yes...can I just use a normal ts compiler?

**Comment by Stevenic** [comment]
@GanadiniAkshay I'd recommend packaging your recognizers up as a separate NPM that you publish. We generally don't accept PR's for new classes into the core because it means we're on the hook to maintain them. This is a case by case decision.  I think it's awesome that you did this work and we'll certainly promote your libraries but we're even talking about removing the LuisRecognizer from the core library at some point.

**Comment by GanadiniAkshay** [comment]
@Stevenic thanks for the update. I have already published an (npm module)[https://www.npmjs.com/package/api-ai-recognizer] for api.ai will publish wit.ai support soon.

Cheers!

**Comment by Stevenic** [comment]
Awesome... just let us know :)  Also, could you install version 3.5 using `npm install --save botbuilder@next` just to verify they work with the next release? Thanks!

**Comment by sebsylvester** [comment]
@GanadiniAkshay @Stevenic. Just wanted to let you guys know that I've published a Wit.ai recognizer for Node.js to be used with the Bot Framework. The module is written in TypeScript, has plenty of comments and includes unit tests. You can view the source on https://github.com/sebsylvester/botbuilder-wit and install via ```npm install botbuilder-wit```. A shout-out to the bot community will be very much appreciated.

**Comment by adebisi-fa** [comment]
@GanadiniAkshay @Stevenic There is a prototype of LUIS implementation for [Wit.Ai (C#) here](https://github.com/adebisi-fa/Bot.Builder.WitAi).  It implements the **ILuisService** for [Wit.Ai](http://wit.ai).  Sample will be added to the repo, asap.  It's available on [NuGet here](https://www.nuget.org/packages/Adfa.Bot.Builder.WitAi/0.1.0).  

Hope it helps.

**Comment by rnjailamba** [comment]
@GanadiniAkshay  any update on your wit.ai npm module?

**Comment by GanadiniAkshay** [comment]
@rnjailamba  the one created by @sebsylvester is pretty good...I have been using it. Didn't make another one

**Comment by gohilsagar** [comment]
Please go through below link.
https://www.npmjs.com/package/botbuilder-wit

it also works as bot recognizer like this -- bot.recognizer(new WitRecognizer('Wit.ai_access_token'));
