### ISSUE TITLE
Skype Bot

### ISSUE THREAD

**Issue by thuru** [Microsoft/BotBuilder#1774]
I'm trying on simple getting started Skype bot. Where to find the bot Id ? Is it a GUID generated by the developer. In this link [https://developer.microsoft.com/en-us/skype/bots/docs]
 it says the portal will generate the Id for us but I don't find it.

**Comment by tpernice** [comment]
You can read it from the activity class instance.

```
ChannelAccount from = activity.From;
string sender = from.Name;
string id = from.Id;
```

**Comment by tpernice** [comment]
The activity class contains sender and recipient information.

```
ChannelAccount recipient = activity.Recipient;
string id = recipient.Id;
```

**Comment by danmarshall** [comment]
The document you are linking to is an older revision. Please see the latest documentation here: https://docs.botframework.com/en-us/skype/getting-started
