### ISSUE TITLE
New bot creation is not working

### ISSUE THREAD

**Issue by dotnetdude** [Microsoft/BotBuilder#1775]
In https://dev.botframework.com bot creation was working fine. But today when I create a new bot, it stopped working.  The chat window to test the bot is disappeared. But the bots created before working fine.  When i try to test the new bot with "Add to skype" test link. Its failing with this error "Oops, there was a problem with your link The bot was not found. "  Any reason why its failing?

**Comment by jamesemann** [comment]
I am seeing the same issue .  I've created another issue but I'll close it as a duplicate.

When I click edit on either MS Teams/Skype channels I see.

![image](https://cloud.githubusercontent.com/assets/6830648/20834871/59898490-b88f-11e6-9f4c-2e20dbd5eaf9.png)

Older bots seem OK when I configure the same channels so it looks like there is a problem with new Bot registration.

**Comment by jamesemann** [comment]
Further to my previous comment, it seems it's only Skype/Teams having this issue.  Other channels I've tested with a new Bot and they work fine.

**Comment by danmarshall** [comment]
Thanks for the report - we have identified an intermittent issue and a fix is being deployed today. Please retry later today.

**Comment by dotnetdude** [comment]
its working fine now. thanks for the quick fix.

**Comment by dicastro** [comment]
I am still having the same issue.

Before migration to 'Azure Bot Service' I was able to add an "unpublished" bot to skype clicking on the link.

After migration to 'Azure Bot Service', I have registered a brand new bot for testing purposes. But I am not able to add it to Skype. If I try with webchat, everything works correctly.

**Comment by dicastro** [comment]
The problem has disapeared after filling in 'Long Description' in 'Publish' tab in 'Skype' channel details and saving the form.

**Comment by desflan** [comment]
i also solved this issue by filling in 'Long Description' in 'Publish' tab in 'Skype' channel details and saving the form.

**Comment by ManoloPatrimonio** [comment]
@desflan @dicastro hey guys, did you submit the form too or just save?

**Comment by Rufus1123** [comment]
As of yesterday, I am also encountering this error (see screenshot)
Creating a new Bot Registration Channel does not help. Even more strangely: Links that I used previously to add bots to Skype give the same error now.

![image](https://user-images.githubusercontent.com/32542901/40988160-af226838-68ea-11e8-920d-513a48cfdc75.png)

**Comment by EricDahlvang** [comment]
Hey @Rufus1123 

This issue is tracking the Skype join link problem: https://github.com/Microsoft/BotBuilder/issues/4700
