### ISSUE TITLE
Determining who is in a conversation.

### ISSUE THREAD

**Issue by james-lawrence** [Microsoft/BotBuilder#1776]
Anyway to determine who is part of a conversation via api calls without having to receive a message first?
particularly for multiparty chat rooms.

`/v3/conversation/{conversationId}/members` is close but there is no way to get all the conversations.

similar issue with determine what organization a user is a part of, the api doesn't expose that information anywhere.

If not, is there an actual microsoft teams api instead of this abstraction layer?

**Comment by danmarshall** [comment]
The Bot Framework does not provide a list of all conversations, but there is nothing which stops you from implementing your own storage to save the IDs of all conversations invoked. But yes, you would have to receive a message first to get this conversation ID. 

As for a Microsoft Teams API, this is part of OfficeDev, which has a couple of API choices here: https://dev.office.com/chooseapiendpoint

**Comment by danmarshall** [comment]
also see https://dev.office.com/microsoft-teams
