### ISSUE TITLE
Can't enter any commands starting with slashes in Skype for iOS

### ISSUE THREAD

**Issue by zobnov** [Microsoft/BotBuilder#178]
It turns out to interfere with the new own command of Skype described here: https://support.skype.com/en/faq/FA10042/what-are-chat-commands-and-roles

I had to modify [testBot] (https://github.com/Microsoft/BotBuilder/tree/master/Node/examples/testBot) in order to run tests.

Please note that any text starting with '/' is intercepted by the contact called 'System', the command I enter isn't even displayed.

My solution was to remove the leading '/' from the commands of the test bot.

**Comment by Stevenic** [comment]
We run into similar issues with slack. I've been planning to drop the '/' from testbot commands.

**Comment by msft-shahins** [comment]
@zobnov I guess as a work around, you can also put a space ' /' in front of the slash and then skype and slack clients will not treat the slash commands as system commands.

**Comment by zobnov** [comment]
Thanks for your propositions. No, it didn't work for me in Skype. My
solution was to get did of the slash in the bot. Commands without it look
even better :)

**Comment by Stevenic** [comment]
I agree @zobnov. I'll remove the slashes in a future version of the test bot. In fact if you'd like to remove them and send a pull request with changes feel free. Just update the help text as well please.

Thanks!

**Comment by zobnov** [comment]
Sure, will do.

**Comment by Stevenic** [comment]
I've checked in a fix for this.
