### ISSUE TITLE
Failed to send message: bot returned an error

### ISSUE THREAD

**Issue by maheshbabuvemulapati** [Microsoft/BotBuilder#1780]
We have developed a bot and deployed to azure and was working fine. Suddenly today we are facing issue while posting a message to the bot. Failed to send message: bot returned an error

Can anyone please advise?

**Comment by danmarshall** [comment]
Can you give more details on your type of deployment: Is this an Azure **Bot** Service, or an Azure **App** Service? 

Do you have any specific exception details in your logs?

**Comment by danmarshall** [comment]
@maheshbabuvemulapati I'm going to close this issue for now. Please feel free to open a new issue with specific error messages you are seeing.
