### ISSUE TITLE
202 Status code without response json

### ISSUE THREAD

**Issue by abelnation** [Microsoft/BotBuilder#1781]
I am making api requests to the REST API endpoint `/v3/conversations/{conversationId}/activities` [docs here](https://docs.botframework.com/en-us/restapi/connector/#!/Conversations/Conversations_SendToConversation).  I am properly authenticating to receive my access_token.  When making the request, the response comes back with a 202 status code but does not return any json in the body nor does the message show up in the msteams chat (1 on 1) conversation.  Any idea what could be going on?  Thanks.  

Example post body:
```
{
    "activity": {
        "channelId": "msteams",
        "type": "message",
        "serviceUrl": "https://skype.botframework.com",
        "from": {
            "id": "28:95e28899-2c3d-4db9-b073-6d4a3419a82a",
            "name": "some-user-A"
        },
        "recipient": {
            "id": "8:orgid:bd98c969-395b-4f0c-b11d-902ee9f90aec",
            "name": "some-user-B"
        },
        "conversation": {
            "id": "19:bd98c969-395b-4f0c-b11d-902ee9f90aec_95e28899-2c3d-4db9-b073-6d4a3419a82a@unq.gbl.spaces"
        },
        "textFormat": "markdown",
        "locale": "en-US",
        "text": "Test message"
    }
}
```

**Comment by abelnation** [comment]
Figured it out.  API docs had me confused.  I took the "parameter name" to mean, the name of the key in side the body object:

![image](https://cloud.githubusercontent.com/assets/200054/20852565/3e049848-b89b-11e6-8500-811baea4089d.png)

Post body should just be the activity itself:

```
{
        "channelId": "msteams",
        "type": "message",
        "serviceUrl": "https://skype.botframework.com",
        "from": {
            "id": "28:95e28899-2c3d-4db9-b073-6d4a3419a82a",
            "name": "some-user-A"
        },
        "recipient": {
            "id": "8:orgid:bd98c969-395b-4f0c-b11d-902ee9f90aec",
            "name": "some-user-B"
        },
        "conversation": {
            "id": "19:bd98c969-395b-4f0c-b11d-902ee9f90aec_95e28899-2c3d-4db9-b073-6d4a3419a82a@unq.gbl.spaces"
        },
        "textFormat": "markdown",
        "locale": "en-US",
        "text": "Test message"
}
```

**Comment by danmarshall** [comment]
Ok thanks for posting, I'll close this for now.
