### ISSUE TITLE
Using Bot Services, unable to set up Continuous integration

### ISSUE THREAD

**Issue by bosslee** [Microsoft/BotBuilder#1782]
Starting out on the Azure with the bot service.
[Link](https://azure.microsoft.com/en-us/services/bot-service/)

I'm looking to set CI with GitHub but it keeps asking me for the username and password. Which I have also set up in the deployment credentials. But it does not match. 

Anything think I'm doing wrong here?
![2016-12-03 at 3 27 pm](https://cloud.githubusercontent.com/assets/993948/20857659/aa98faee-b96d-11e6-9ed4-ee476519e862.jpg)

**Comment by hailiu2586** [comment]
Thanks for reporting the issue. This appears to be Safari only issue and we have a fix being verified. Meanwhile, you can try use Chrome browser as work around. I will update once the fix for Safari issue is deployed.

Thank you.

**Comment by hailiu2586** [comment]
We have deployed a fix for downloading source zip file on macOS Safari. Thanks
