### ISSUE TITLE
Get non-stop exception message in Telegram

### ISSUE THREAD

**Issue by dimoibiehg** [Microsoft/BotBuilder#1785]
I wrote the following code as a simple bot:

``` C-Sharp
public async Task<HttpResponseMessage> Post([FromBody]Activity activity)
{
    if (activity.Type == ActivityTypes.Message)
    {
        ConnectorClient connector = new ConnectorClient(new Uri(activity.ServiceUrl));
        
        // I created an exception deliberately
        string str = null;
        int integer = str.Length;
                
        // return our reply to the user
        Activity reply = activity.CreateReply("You sent some characters!");
        await connector.Conversations.ReplyToActivityAsync(reply);
        }
        var response = Request.CreateResponse(HttpStatusCode.OK);
        return response;
    }
}
```
But what's happened?
If you run this code as a bot, and test it in Telegram, 
as it has an exception, you will get a non-stop exception message in your messenger (Telegram).

The question is: Does this problem come from Bot Framework or Telegram?

P.S. you can see the problem visually in the following image!
![image](https://cloud.githubusercontent.com/assets/22638310/20866352/dafc55fe-ba40-11e6-9ad0-b1f74cf2a05e.png)

Also, this issue is not related to our bot! As you can see in the following image, if there is no code behind the endpoint, I got a lot of exception messages which were 404 not found. 
![image](https://cloud.githubusercontent.com/assets/22638310/20866375/8872cf9c-ba41-11e6-9944-71a8bd87aa16.png)

**Comment by eanders-MS** [comment]
Hi @dimoibiehg Thank you for reporting this. We've made a fix for the issue, and it will be available in the next release. We make a new production release every week or so.
