### ISSUE TITLE
RecognizeMode.onBegin not working.

### ISSUE THREAD

**Issue by iassal** [Microsoft/BotBuilder#1788]
This line:
`this.recognizeMode = options.recognizeMode || RecognizeMode.onBeginIfRoot;` in [IntentDialog](../blob/master/Node/core/src/dialogs/IntentDialog.ts#L63).

This made the option `RecognizeMode.onBegin` which has the value `0` evaluate to false and fallback to `RecognizeMode.onBeginIfRoot`

**Comment by dandriscoll** [comment]
Closing as it appears the issue was fixed.
