### ISSUE TITLE
Training LUIS: programmatic API vs UI

### ISSUE THREAD

**Issue by cnrudd** [Microsoft/BotBuilder#1789]
Hi,

If I train a LUIS app via the programmatic API described here: 
https://dev.projectoxford.ai/docs/services/56d95961e597ed0f04b76e58/operations/56f8a55119845511c81de483

I find that the app never appears as trained in the UI here:
https://www.luis.ai/applicationlist

Only when I train an app via the GUI does the GUI reflect that it has been trained.

Other actions done via programmatic API, such creating a new app, adding labeled examples, do reflect in the UI.  I would have expected the same for training.

Thanks,
Colin

**Comment by cahann** [comment]
Thanks for reporting this. Will open UI bug to make sure the training is reflected in the GUI

**Comment by nagarajasr** [comment]
i also noticed that issuing a POST to /apps/{appId}/train does not actually perform the training. however, issuing a GET to the same URL starts the training. i reached this conclusion by checking the LastTrainedDate and IsTrained attributes in the response from GET /apps/{appId} which is null and false respectively in first case and shows current time and true in second case. 
tested using postman and curl

**Comment by nagarajasr** [comment]
is there a better place to report LUIS programmatic API issues? this repository is for the BotBuilder which assumes a trained model is already available

**Comment by cahann** [comment]
Yes, please reach out to use on luservice@microsoft.com or open a ticket on uservoice through our website.

To ensure the training was successful please call GetTrainStatus API

**Comment by dandriscoll** [comment]
Closing this issue as we've covered all of the open questions.
