### ISSUE TITLE
Not able to create blank lines

### ISSUE THREAD

**Issue by euanlau** [Microsoft/BotBuilder#1791]
```Text = "Test  \n  \nBreak  \nAgain"```

There should be an empty line between Test and Break. But i got the below instead.

<img width="123" alt="screen shot 2016-12-05 at 8 55 07 am" src="https://cloud.githubusercontent.com/assets/794933/20870768/93498e9c-bac8-11e6-9a03-cb3dfb0e9929.png">

**Comment by danmarshall** [comment]
I believe markdown requires 2 newlines without whitespace between: \n\n

**Comment by euanlau** [comment]
@danmarshall I tried that as well. Same result.

**Comment by danmarshall** [comment]
In which channel do you see this?

**Comment by euanlau** [comment]
slack, skype, facebook.

**Comment by euanlau** [comment]
and I am using NodeJS.

**Comment by danmarshall** [comment]
Can you share a js code snippet?

**Comment by danmarshall** [comment]
@reyesrico can you verify this?

**Comment by euanlau** [comment]
@danmarshall 
`session.send("line 1\n\n\n\nline 3");`

screenshot for slack:

![screen shot 2016-12-07 at 10 38 51 am](https://cloud.githubusercontent.com/assets/794933/20981402/6c8527d8-bc69-11e6-9524-1871d08c9e06.png)

screenshot for skype:
![screen shot 2016-12-07 at 10 40 27 am](https://cloud.githubusercontent.com/assets/794933/20981432/9b498c9e-bc69-11e6-8739-98ea01a49619.png)

**Comment by euanlau** [comment]
@danmarshall 
I tried `session.send("line 1<br/><br/>line 3");` and it works perfectly on all 3 platforms. Closing this for now. Thanks!
