### ISSUE TITLE
Can I transfer the conversation started by directline to a web chat channel ?

### ISSUE THREAD

**Issue by kanwal019** [Microsoft/BotBuilder#1794]
I am trying to initiate a bot conversation through directline channel, but I need to follow rest of the conversation through webchat channel. Is there any possible way that I can resume my conversation in web chat using the conversation Id generated ?

**Comment by dandriscoll** [comment]
Hi @kanwal019, this is possible although it requires you to host the web chat control on your own. To transfer the conversation:

1. Generate a random ID within your Direct Line conversation. Associate this ID with the current conversation.
2. Generate a link to the page hosting your Web Chat control, and pass that ID into the page
3. Inside the page, pass the ID into the Web Chat control
4. Inside the bot, look up the Direct Line conversation, and use this to restore your conversation state
5. You should delete the association between the ID and the conversation state to prevent replay attacks.

We're looking at automating this in the future but we don't yet have concrete plans or a timeline for doing this.

**Comment by dandriscoll** [comment]
Closing as we've answered the question. Please at-mention or file a new issue if you'd like to discuss further.
