### ISSUE TITLE
[MS Teams Mobile iOS] Thumbnail card bug on Team's IOS client

### ISSUE THREAD

**Issue by miaosenwang** [Microsoft/BotBuilder#1795]
Hello,
I have a thumbnail card that works fine on the emulator, Team desktop app (windows), Skype for Desktop, and Skype for Mobile on IOS. 

But on Team's IOS client, there are two issues:
1. The image is not displaying. My image is shown as a gray box. 
2. There are 2X duplicated cards. When I only have one card, the client shows two identical cards for a brief moment and then back to one card. It also happens when there are 2 or more cards.

**Comment by siduppal** [comment]
Thanks for reporting this issue.

We have developed the fixes and would be rolling them out in the next release.

**Comment by miaosenwang** [comment]
@siduppal  Hello. I updated to the latest C# Bot framework SDK. 3.5 and I am still seeing this issue with the IOS Team client.

**Comment by Andrea-Orimoto** [comment]
Hi @siduppal, was the fix released?
@miaosenwang, still having the issue?

**Comment by miaosenwang** [comment]
@Andrea-Orimoto Thank you for following up. I have updated the SDK to the latest 3.5.2. The duplicated card problem is solved. However, there is still a problem with the image. The image shows up initially, but if you scroll up until the image is invisible and then scroll down, the image becomes a gray box.

**Comment by siduppal** [comment]
iOS client fixes are supposed to rollout this week

**Comment by siduppal** [comment]
Can you please reply with version of Teams iOS app installed?
Go to More->settings->about to find it.

**Comment by miaosenwang** [comment]
@siduppal The version I have is 1.0.20446. What's the version that has the fix?

**Comment by carlosscastro** [comment]
@miaosenwang are you still experiencing this issue?

**Comment by miaosenwang** [comment]
@carlosscastro I just checked. Both problems are resolved. Thank you!
