### ISSUE TITLE
Initial conversation from bot. But start over while user input

### ISSUE THREAD

**Issue by Taroka** [Microsoft/BotBuilder#1796]
Hi guys, 

I want to start the very first conversation from bot. So I trigger the "bot.beginDialog" while "conversationUpdate" occur.

    var bot = new builder.UniversalBot(connector);

    bot.on('conversationUpdate', function(session){
		bot.beginDialog(session.address, "*:/");
	});

It works, the bot start the conversation and direct the conversation to root dialog "*:/"
But while the user reply, the conversation start over. The session id and conversation id are the same.

How can I modify the code to let the user input connect to the conversation which start by bot?
Or we should not start the very first conversation by bot?

 I put the log below.
Thank you!

```
ChatConnector: message received.
session.beginDialog(*:/)
/ - waterfall() step 1 of 1
Root dialog Address:  { id: '10a97ghj983i40jgc',
  channelId: 'emulator',
  user: { id: 'a444ihm749eg9k717c' },
  conversation: { id: 'a444ihm749eg9k717c' },
  bot: { id: 'default-bot' },
  serviceUrl: 'http://localhost:9002',
  useAuth: true }
/ - session.send()
/ - session.beginDialog(/askQuestion)
./askQuestion - waterfall() step 1 of 2
askQuestion dialog Address:  { id: '10a97ghj983i40jgc',
  channelId: 'emulator',
  user: { id: 'a444ihm749eg9k717c' },
  conversation: { id: 'a444ihm749eg9k717c' },
  bot: { id: 'default-bot' },
  serviceUrl: 'http://localhost:9002',
  useAuth: true }
./askQuestion - session.beginDialog(BotBuilder:Prompts)
..Prompts.text - session.send()
..Prompts.text - session.sendBatch() sending 2 messages
ChatConnector: message received.
session.beginDialog(/)
/ - waterfall() step 1 of 1
Root dialog Address:  { id: '8g16n7f3kg9gjb37l',
  channelId: 'emulator',
  user: { id: 'default-user', name: 'User' },
  conversation: { id: 'a444ihm749eg9k717c' },
  bot: { id: 'default-bot' },
  serviceUrl: 'http://localhost:9002',
  useAuth: true }
/ - session.send()
/ - session.beginDialog(/askQuestion)
```

**Comment by eanders-MS** [comment]
Hi @Taroka Could you please also post your emulator logs?

**Comment by Taroka** [comment]
Hi @eanders-MS , sure!

    [15:58:47] -> POST 202 [conversationUpdate] 
    [15:58:47] <- POST 200 Reply[message] This is root msg, let's go to next dialog. 
    [15:58:47] <- POST 200 Reply[message] This is the second dialog 
    [15:58:58] -> POST 202 [message] i wan to ask question  // start over to the right user flow
    [15:58:58] <- POST 200 Reply[message] This is root msg, let's go to next dialog. 
    [15:58:58] <- POST 200 Reply[message] This is the second dialog 
    [15:59:08] -> POST 202 [message] i want to ask question 
    [15:59:09] <- POST 200 Reply[message] I'm sorry. I didn't understand. 
    [15:59:09] <- POST 200 Reply[message] Do you have any other questions?

**Comment by eanders-MS** [comment]
I don't yet have a clear picture of the problem. Can you give more detail about what you're seeing vs. what you expected to happen?

**Comment by Taroka** [comment]
Sorry for the confusing. I try to make it clear.

This is what I see
![screen shot 2016-12-05 at 4 25 31 pm](https://cloud.githubusercontent.com/assets/4027421/20908168/ba7b5bbe-bb07-11e6-95ca-90722998ef5d.png)

And this is what I want:

> Bot: Hi, I'm Bot. I can answer your question
> Bot: Do you have any question?
> User: here is my quesion.
> Bot: Here is your answer.
> Bot: Do you have any other question? If you want to end this chat, please say "bye".

That is, I want the bot start a conversation and user smoothly success join the conversation which start by bot.

Right now seems the user will start another conversation once they reply the initial msg from bot. That is, bot don't know it send a message to user and still waiting for the first "Hi" from user to start the conversation.

**Comment by Taroka** [comment]
hi @eanders-MS  could you help?

**Comment by eanders-MS** [comment]
@Taroka I believe that the 'conversationUpdate' handler accepts a `message` rather than a `session`. This might be a factor. @Stevenic are you able to shed light here?

**Comment by eanders-MS** [comment]
Hi @Taroka Some experimentation led me to this, which seems to achieve what you're trying to accomplish, at least in a simplistic way:

```javascript
bot.on('conversationUpdate', (message) => {
    if (message.membersAdded) {
        const hello = new builder.Message()
            .address(message.address)
            .text("Hi, I am Bot. I can answer your question");
        bot.send(hello);
        bot.beginDialog(message.address, '*:/');
    }
});
bot.dialog('/', [
    (session) => {
        builder.Prompts.text(session, 'Do you have any questions?');
    },
    (session, results) => {
        session.send('Here is your answer');
    }
]);
```

Emulator log:
```
[00:17:15] -> POST 202 [conversationUpdate] 
[00:17:16] <- POST 200 Reply[message] Hi, I am Bot. I can answer your question 
[00:17:16] <- POST 200 Reply[message] Do you have any question? 
[00:17:27] -> POST 202 [message] my question 
[00:17:28] <- POST 200 Reply[message] Here is your answer. 
```

**Comment by Taroka** [comment]
Hi @eanders-MS thanks! And I found an interesting situation. that is the same code give me different result in different version emulators lol
![screenshot 6](https://cloud.githubusercontent.com/assets/4027421/21031414/32cfaf64-bd58-11e6-951b-acabd043bc0e.png)

**Comment by eanders-MS** [comment]
Ah, it's because you're running an older version of the new emulator than me. :) I was running an internal dev build with a bugfix you don't have yet. We're in the midst of making a new emulator release at the moment. You should get an update available prompt the next time you run it.

**Comment by dandriscoll** [comment]
Closing this issue as it appears we've addressed the problem. If you have additional questions or would like to discuss further, please at-mention either of us or open a new issue. Thanks!

**Comment by Taroka** [comment]
Thank @eanders-MS and @dandriscoll !

**Comment by slidenerd** [comment]
ok but i noticed that if you add both a first run and a conversationUpdate, both of them get triggered on facebook so arent you using a first run?

**Comment by srichakradhar** [comment]
I have the same issue, but with the Webchat (IFrame) channel. Any inputs regarding that?
