### ISSUE TITLE
Add support for HipChat

### ISSUE THREAD

**Issue by ryanackley** [Microsoft/BotBuilder#18]
I use HipChat at work so this would be great.
API reference. 
https://www.hipchat.com/docs/apiv2

**Comment by msft-shahins** [comment]
Feel free to add a feature request on https://feedback.botframework.com/.

**Comment by sandiz** [comment]
hey, that link takes you to https://docs.botframework.com/en-us/support/, which says create an issue for this on github

**Comment by codekaizen** [comment]
Yup, the support link says to post issues here.

![_ 127](https://cloud.githubusercontent.com/assets/577263/19782497/e6ce0768-9c42-11e6-929f-9a723bb2dfbc.png)

**Comment by evnik** [comment]
It seems they dropped their UserVoice feedback channel after closing of this issue.
I believe they don't monitor closed issues, so the best way to request that is creating of a new issue.
