### ISSUE TITLE
WebChat control and User Id

### ISSUE THREAD

**Issue by jakobpn** [Microsoft/BotBuilder#180]
Is there a way to get the web chat control to save the user id locally so that new sessions doesn't generate a new user id?

**Comment by dandriscoll** [comment]
The user ID is stored in a browser cookie and is shared across conversations. Is that the behavior you're seeing?

**Comment by jakobpn** [comment]
No. To me it look like a new user id is assigned every time I open the web page that has the WebChat control in it.

**Comment by dandriscoll** [comment]
OK, I'll take a look.

**Comment by dandriscoll** [comment]
Yep, this is a bug. Working on fixing it.

**Comment by Stevenic** [comment]
Did this get fixed @dandriscoll ?

**Comment by dandriscoll** [comment]
This should be fixed now, yes. Is it working for you now?

**Comment by jakobpn** [comment]
It is working for me now. Thanks @dandriscoll!

**Comment by Stevenic** [comment]
awesome!
