### ISSUE TITLE
How can I start and stop a conversation in Web Chat channel ?

### ISSUE THREAD

**Issue by kanwal019** [Microsoft/BotBuilder#1800]

**Comment by dandriscoll** [comment]
Hi @kanwal019, the conversation is started when the web chat control is opened.

Are you asking about starting/stopping the conversation within the client (i.e., controlling whether the client is connected to the server) or within the server (i.e., signaling to the server and bot that the conversation is over)?

**Comment by dandriscoll** [comment]
Haven't heard back, so I'm closing this issue for now. Please feel free to at-mention or open a new issue.
