### ISSUE TITLE
SimpleFacebookAuthBot hangs up during request for Bot data

### ISSUE THREAD

**Issue by aximus** [Microsoft/BotBuilder#181]
Hi

I try to run SimpleFacebookAuthBot and it does not work as expected
I registered an app on facebook, was able to send a message to the bot and get auth url. After successful authentication on Facebook, the OAuthCallbackController.OnOAuthCallback() is executed and it hands up during executing this line:
`var reply = await Conversation.ResumeAsync(botId.Value, userId, conversationId, msg, connectorType: connectorType);`

I dug deeper and found out that it executed IConnectorClient.LoadMessageData() that tried to get bot conversation data:

```
	var dataRetrievalTasks = new List<Task<BotData>> {
                client.Bots.GetConversationDataAsync(botId, conversationId, token),
                client.Bots.GetUserDataAsync(botId, userId, token),
                client.Bots.GetPerUserConversationDataAsync(botId, conversationId, userId, token)
            } ;
```
 
These requests were dropped with following Error message and stack:

> A  task was canceled.

 
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

>  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable1.ConfiguredTaskAwaiter.GetResult()
>    at Microsoft.Bot.Connector.Bots.<GetConversationDataWithHttpMessagesAsync>d__7.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable1.ConfiguredTaskAwaiter.GetResult()
>    at Microsoft.Bot.Connector.BotsExtensions.<GetConversationDataAsync>d__5.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at Microsoft.Bot.Connector.BotsExtensions.GetConversationData(IBots operations, String botId, String conversationId)
>    at Microsoft.Bot.Builder.Dialogs.Internals.Extensions.<LoadMessageData>d__0.MoveNext() in D:\Projects\Sandbox\BotBuilder\CSharp\Library\Dialogs\IConnectorClientFactory.cs:line 131

Looks like emulator does not respond on this request

**Comment by msft-shahins** [comment]
That was a bug in the emulator. We just pushed a new version [1.0.0.64](http://download.botframework.com/botconnector/tools/emulator/publish.htm). Try it and see if it solves your problem.

**Comment by aximus** [comment]
Now it works, thanks!

**Comment by jaliyaudagedara** [comment]
Well, I tried now and it doesn't work for me. Any ideas?
