### ISSUE TITLE
How to initiate Proactive Messages in C# (Webchat)

### ISSUE THREAD

**Issue by b4usat** [Microsoft/BotBuilder#1811]
I referred this [link](https://docs.botframework.com/en-us/node/builder/chat/UniversalBot/#proactive-messaging) for initiating proactive messages. But it is written in Node js. Please help me with some sample for C#. I am using `webchat `as a channel. I am facing one more trouble as i want to set a OAUTH token to my botstate outside of the Bot application. I tried connecting the state with MS app id and password, but to set the Botdata in store i need the `userid `which is dynamic in webchat. How can i do that?

**Comment by msft-shahins** [comment]
Here is a sample showing how to proactively create a conversation: https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/core-CreateNewConversation

**Comment by b4usat** [comment]
yeah.. i have seen this example. This is all about Bot asking questions to user. But for my case, when the Bot initialized, it should greet the user for the first time.. next time onwards, user will initialte the conversations. Is it fine i post the Greet message in `ConversationUpdate `Activity?

**Comment by msft-shahins** [comment]
@b4usat when a member is added or removed from conversation, `ConversationUpdate` activity is sent to the bot. Your bot can greet the user when user added to the conversation. Here is a way of doing it: https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Samples/EchoBot/Controllers/MessagesController.cs#L38

**Comment by b4usat** [comment]
This helps, but when deployed and tested in Webchat, `ConversationUpdate `activity is not trigerring on the load of the Web chat instead when i typed and post a message it gets triggered. Do we have a solution for this?

**Comment by kanwal019** [comment]
@msft-shahins This works in the emulator. But I am not able to get the desired result in the webchat chennel.

**Comment by msft-shahins** [comment]
@kanwal019 webchat will send `ConversationUpdate` activity to your bot first time that is loaded and you have the opportunity to send welcome message there.

**Comment by kanwal019** [comment]
@msft-shahins This works in the emulator, but in the webchat channel the "ConversationUpdate" activity, is not able to pass the username, instead displays the bot name in the welcome message.
