### ISSUE TITLE
Unit test for ReplyToActivityAsync()

### ISSUE THREAD

**Issue by Koshak118** [Microsoft/BotBuilder#1812]
Hey guys
I am trying to figure out how to create a unit test for the MessagesController which might send multiple replies with ReplyToActivityAsync(activityToReturnBack) while handling a single user request. To clarify, I'd like to validate  every single "activityToReturnBack" payload which can be returned after a user request done in the unit test code.

Doing something like 

```
               //--------------------------------------------------------------
	       //   Arrange
	       //--------------------------------------------------------------
	       MessagesController testController = new MessagesController()
               Activity mockActivity = new Activity(ActivityTypes.Message);
               
               //Doing stuff to mock the controller and the activity 
                ..........
                mockActivity.Text = "Hi there";
                mockActivity.ServiceUrl = "http://localhost:9000";    //Emulator like
               
                //--------------------------------------------------------------
                //	Act
                //--------------------------------------------------------------
                HttpResponseMessage responce = await testController.Post(mockActivity);

```
does not really make sense.

Can you please advise?

**Comment by willportnoy** [comment]
You will need to inject a mock IConnectorClient into your controller to use this approach.  You might considering a mocking library like Moq.

We tend to write our unit tests at the builder level, rather than connector REST client level.

**Comment by willportnoy** [comment]
I'm going to close this issue for now, but feel free to open a new issue for further discussion.
