### ISSUE TITLE
LUIS German Model: PromptDialog.Confirm

### ISSUE THREAD

**Issue by syedaliammar** [Microsoft/BotBuilder#1814]
Hi, I'm not really sure here whether to raise this question on the LUIS forum or here. But here it goes:

So I just built a LUIS model using the German app culture. When I need to ask Yes/No question to the user, I use the PromptDialog.Confirm(...) method. Indeed the prompt message is in German, and the user will naturally reply with Ja / Nein instead of a Yes / No.

This is a problem, because the Yes / No response is clearly translated into its bool equivalent True / False. However, Ja /Nein isn't. Or am I simply missing something very obvious?

`PromptDialog.Choice(context, AfterChoice_DoSomething, myPromptMessage, promptStyle: PromptStyle.None);`

The other option is to use PromptStyle.Auto, but that still displays a Yes and No button. Perhaps if locale could be specified somewhere, it would display Ja and Nein buttons.

**Comment by chrimc62** [comment]
PromptConfirm.Options is a property that controls what strings are used to match responses for PromptDialog.Confirm.  If you put Ja/Nein and other choices in there it should work.  You can also pass in descriptions for the labels on the buttons if you use something like PromptDialog.Choice.  
If you are saying you have a yes/no intent in your LUIS model then you could also solve the problem with a LUIS dialog that dispatches on that intent.

**Comment by syedaliammar** [comment]
Hi @chrimc62 , thanks for your response. This works nicely!

Just for my own knowledge, is there any good example which shows how to dispatch a new Dialog from an Intent handler method?

**Comment by chrimc62** [comment]
Here is an example: https://github.com/Microsoft/BotBuilder-Samples/blob/master/CSharp/intelligence-LUIS/Dialogs/RootLuisDialog.cs
