### ISSUE TITLE
Skype: Specifying thumbnailUrl disables video playing

### ISSUE THREAD

**Issue by euanlau** [Microsoft/BotBuilder#1815]
```
     var msg = new builder.Message(session)
            .attachments([{
                contentType: "video/mp4",
                contentUrl: "http://mysite.com/somevideo.mp4",
                thumbnailUrl: "http://mysite.com/someimage.jpg"
            }]);
```

The thumbnail does show up properly on both Skype iOS and Mac. However, I am not able to play the video anymore. I am able to play the video on both clients after removing the `thumbnailUrl`.

**Comment by konstlut** [comment]
Hello @euanlau! Thank you for the issue. Unfortunately I wasn't able to reproduce that myself (the video is played with and without thumbnail). Could you please provide specific urls that don't play as well as your bot Id (that could give me some pointers in our logs). Thanks!

**Comment by Andrea-Orimoto** [comment]
Hi @euanlau,
are you still experiencing this issue?

**Comment by euanlau** [comment]
@Andrea-Orimoto Yes. Just tried this again today. It is still a problem on both iOS and Mac.

```
     var msg = new builder.Message(session)
            .attachments([{
                contentType: "video/mp4",
                contentUrl: "http://d2gix7be81x68n.cloudfront.net/staging/20170217/a09b7a82-d5bc-4452-8e90-83e5a0e45909.mp4",
                thumbnailUrl: "https://d2gix7be81x68n.cloudfront.net/staging/20170217/60a8bf54-ae06-46eb-8911-1726bb9be4da.jpg"
            }]);
```

**Comment by Andrea-Orimoto** [comment]
what about using a [video card](https://docs.botframework.com/en-us/skype/getting-started/#video-card)

`

    var card = new builder.VideoCard(session)
        .image({url: 'https://d2gix7be81x68n.cloudfront.net/staging/20170217/60a8bf54-ae06-46eb-8911-1726bb9be4da.jpg'})
        .media([
            { url: 'https://d2gix7be81x68n.cloudfront.net/staging/20170217/a09b7a82-d5bc-4452-8e90-83e5a0e45909.mp4' }
        ])
        .autoloop(false)
        .autostart(false)
        .aspect('9:16');
    
    var msg = new builder.Message(session).addAttachment(card);
    session.send(msg);
`

This is working for me (but it crashes on iOS Skype). @konstlut, I've tried many permutations of the above, adding all properties, resizing the image as specified in the doc, etc... but the video card always crashes on iOS. my bot name is andreonodebasic3 (c58774e9-9fe3-425f-b463-b5342a94ed78).

btw, I can repro the original issue, if I send a video attachment with the thumbnail, it doesn't play. It plays without the thumbnail.

**Comment by euanlau** [comment]
If `VideoCard` crashes on iOS, then it isn't really a workaround.

Its great that you could reproduce the original issue.

**Comment by Andrea-Orimoto** [comment]
if it crashes it's a bug that should be fixed. Have you tried?

**Comment by aery-aery** [comment]
@euanlau We found an issue that caused iOS to crash when using video cards. As a workaround try to set one of profiles ("sd", "hd") for your media.
```
var card = new builder.VideoCard(session)
    .image({url: 'https://d2gix7be81x68n.cloudfront.net/staging/20170217/60a8bf54-ae06-46eb-8911-1726bb9be4da.jpg'})
    .media([
        { url: 'https://d2gix7be81x68n.cloudfront.net/staging/20170217/a09b7a82-d5bc-4452-8e90-83e5a0e45909.mp4',
          profile: 'sd'
       }
    ])
    .autoloop(false)
    .autostart(false)
    .aspect('9:16');

var msg = new builder.Message(session).addAttachment(card);
session.send(msg);
```

**Comment by euanlau** [comment]
@aery-aery I will give it a try and report back. Thanks!
