### ISSUE TITLE
[Skype Mobile iOS] Line Break not formatted properly on iOS

### ISSUE THREAD

**Issue by euanlau** [Microsoft/BotBuilder#1816]
Platform: NodeJS

Code:
`session.send("line 1<br/><br/>line 3");`

Skype iOS Screenshot:
![screen shot 2016-12-07 at 11 12 25 am 1](https://cloud.githubusercontent.com/assets/794933/20982609/2fa6f7ce-bc6e-11e6-9a57-1f7e4d68a9e2.png)

Skype Mac Screenshot:
![screen shot 2016-12-07 at 11 13 52 am](https://cloud.githubusercontent.com/assets/794933/20982637/43d009de-bc6e-11e6-87fc-6d48dc84e73a.png)

**Comment by konstlut** [comment]
@euanlau Thank you for the issue. I spoke to Skype iOS devs and they think formatting is correct. Could you please elaborate on what is not formatted properly. Thank you!

**Comment by euanlau** [comment]
@konstlut  The iOS bubble consumes the entire screen width. On the other hand, the Desktop bubble wraps around the text.

**Comment by euanlau** [comment]
@konstlut This happens only when `<br/>` is used as line break.
