### ISSUE TITLE
Node.js - web client authentication

### ISSUE THREAD

**Issue by haganbt** [Microsoft/BotBuilder#1817]
I am developing a web based chat bot. I have a Node.js backend using Express with a "hello world" example running using the Bot Framework Emulator.

Im now moving to develop the web frontend and looking for guidance on authentication. 

Every example provided uses the bot emulator which does not help when developing a web app. Using Curl ect would be really useful in learning the flow and authentication requirements.

Do I need to build a separate JWT session management for web authentication or can I use the Bot Builder SDK authentication mechanism in some way and pass these creds to each web front end session user? If so, is thee an example with Restify anywhere?

Appreciate any guidance.

**Comment by Stevenic** [comment]
For your website you'll need your own auth scheme as the auth that we do is to secure t he channel between your bot and our servers. You can't really piggyback off that. Let me add Dan for input though.

**Comment by haganbt** [comment]
Thanks for the reply @Stevenic and apologies, reading this again I was not particularly clear on my requirements. I am looking to implement my own web based chat UI (rather than embed the iFrame html client provided) so that I can control the dom/styling etc.

My question is with regards to the authentication being used by the bot framework i.e. to send a message from my html chat window to the server.

* Can you advise on the authentication mechanism required? Is it as documented here: https://docs.botframework.com/en-us/restapi/authentication/#authentication-calls-from-the-bot-to-the-bot-connector-service

* Given I am using the Node SDK, is there any way I can hook in client authentication required for a user of the html chat window, or do I have to wire in JWT as per the above link? The reason for this question is that as part of the above link it states:

> NOTE: If you are using the Bot Builder SDK for C# or the Bot Builder SDK for Node.js, all steps within this document are handled automatically by the SDK. All you have to do is configure it with your bot’s ID and password.

My guess is that this is referring to server side auth and NOT client side.

Appreciate any advice.

**Comment by Stevenic** [comment]
I'll let Dan comment but it seems like you'd want to use DirectLine for this. That's basically what our WebChat uses and lets you essentially borrow our auth to secure the pipe between your client and the bot.

**Comment by haganbt** [comment]
Many thanks @Stevenic , DirectLine looks ideal. 

As a new user of the platform, hopefully some useful feedback, I definitely got hung up on the "Test your bot (Windows Only)" section from here: https://docs.botframework.com/en-us/node/builder/overview/

Given im not on windows I was stuck with regards where to go. I eventually found the iFrame version which helped move along but had no idea it existed, or where to start with my own html auth. Perhaps some additional links in that section would help developers find the right path. Suggestions:

* Embed the Chat Control - quick start wen client by embedding an HTML control: https://docs.botframework.com/en-us/support/embed-chat-control2/
* Writing your own client applications, web chat controls, mobile apps? See the DirectLine API: https://docs.botframework.com/en-us/restapi/directline3/#navtitle

Thanks again for the pointer to DirectLine. Hopefully the above feedback is useful.

Best regards. Ben.

**Comment by Stevenic** [comment]
Yes... our docs were a little out of date with regards to the emulator now being supported across all platforms
