### ISSUE TITLE
Required Help to Integration MS Bot framework + Node JS + Heroku 

### ISSUE THREAD

**Issue by vignestheo** [Microsoft/BotBuilder#1818]
Hello Team 

Please provide me guidelines to do the above mentioned combination that i am using Microsoft bot framework in node js language where i am planning to deploy it in heroku but i am facing the issue that keep on getting same "\api\message" that is only greeting message none other messages i am getting :-(

**Comment by Stevenic** [comment]
Can you share your code?  I've had Heroku working before. The only thing I had to make sure of was that my package.json was setup to properly start my bot and that I had my `appId` and `appPassword` for the connector properly set. I am planning to do a guide for deploying to Heroku but not sure when

**Comment by dandriscoll** [comment]
Hi @vignestheo, can you share your code?

**Comment by Stevenic** [comment]
Closing for age

**Comment by BLCKPSTV** [comment]
Would be nice @Stevenic If you could demonstrate or document a guide through for Microsoft bot framework on Heroku. Not a lot to find about this build.
