### ISSUE TITLE
[Feature Request] Plan for DurationResolution?

### ISSUE THREAD

**Issue by miaosenwang** [Microsoft/BotBuilder#1819]
hello. Just curious, is there a plan to support parsing Luis's duration entity(builtin.datetime.duration)? I saw in the source code, a empty class called DurationResolution, so I assume the implementation is coming?

**Comment by willportnoy** [comment]
I presume this is the C# SDK?

When I wrote that code, I was trying to resolve date times primarily, with an eye toward handling the other entity types.  But there hasn't any stated demand, until your issue.  We can add it to our backlog.

**Comment by miaosenwang** [comment]
Thank you. You are correct.  I was talking about the C# SDK. 

If it can resolve Luis's duration, it would be very helpful. For example, I can start to handle time entities such as"in the next 5 hours"

**Comment by brendanarnold** [comment]
I second this - I raised an issue in the Cognitive LUIS SDK (https://github.com/Microsoft/Cognitive-LUIS-Windows/issues/27) about this. I guess ideally it would return two DateTime objects for the start and end times. e.g. Show me items from last week would return midnight Monday morning to Sunday midnight.

**Comment by cahann** [comment]
LUIS plan to offer duration resolution as one of the enhancements to datetimeV2.
