### ISSUE TITLE
SigninCard is not working in Microsoft Teams

### ISSUE THREAD

**Issue by sivakishorejvv** [Microsoft/BotBuilder#1821]
I am trying to do google authentication for my  bot. Same code base is working fine in skype channel but it is not working in Microsoft Teams. It is coming like "Please sign in using this card" but the sign card is not displaying( you need to authorize me and Connect). Any help?

**Comment by siduppal** [comment]
We are working on resolving this issue. Thanks for reporting!

**Comment by siduppal** [comment]
The fix is now being deployed. Please let us know if you see this issue.

**Comment by dandriscoll** [comment]
Closing issue, please open a new issue if you encounter this problem.
