### ISSUE TITLE
(nodejs) Prompt.confirm and Prompt.choice throw errors in Slack

### ISSUE THREAD

**Issue by BlueHatbRit** [Microsoft/BotBuilder#1823]
I've been having numerous problems with Prompt.confirm on slack and decided to take it all the way back to basics.

I used the following code to see if Prompt.confirm was even responding properly:

```javascript
let test = [
    function(session) {
        builder.Prompts.confirm(session, 'yes or no?');
    },
    function(session, results) {
        session.send('you said: ' + results.response);
        session.endDialog();
    }
]
```

Here's a screenshot of the results, after clicking the confirm button I then waited a full minute (as shown by the time tick over) to ensure the system wasn't still flushing any messages through. Then after saying "1 minute" (just an arbitrary phrase) it then spits out the result.

![screen shot 2016-12-08 at 14 15 42](https://cloud.githubusercontent.com/assets/1068477/21013166/e056747c-bd50-11e6-9fa9-d590e71a7be8.png)

Obviously it shouldn't be throwing the error that seems to be popping up in slack anyway so this seems to be a bug.

**Comment by BlueHatbRit** [comment]
I've changed the name because I've just run the `Prompt.choice` example in the documentation [here](https://docs.botframework.com/en-us/node/builder/chat/prompts/#promptschoice).

```javascript
var salesData = {
    "west": {
        units: 200,
        total: "$6,000"
    },
    "central": {
        units: 100,
        total: "$3,000"
    },
    "east": {
        units: 300,
        total: "$9,000"
    }
};

bot.dialog('/', [
    function (session) {
        builder.Prompts.choice(session, "Which region would you like sales for?", salesData); 
    },
    function (session, results) {
        if (results.response) {
            var region = salesData[results.response.entity];
            session.send("We sold %(units)d units for a total of %(total)s.", region); 
        } else {
            session.send("ok");
        }
    }
]);
```

It's also giving the same error, but this one isn't actually returning the result when another message is sent, instead it just loops around infinitely.

**Comment by BlueHatbRit** [comment]
Okay so Prompt.option works in Slack if you don't use the fancy buttons, obviously this still isn't good as most users will just click the buttons rather than replying with "yes".

**Comment by craigjensen** [comment]
Please add your botid and we'll investigate

**Comment by BlueHatbRit** [comment]
Hi @craigjensen, my connector app id is `3e266836-6112-4f53-98cb-3d5b6e4b39f1`, thanks!

**Comment by craigjensen** [comment]
Sorry, but i lost track of this over the holidays.  Are you still seeing this issue?

**Comment by BlueHatbRit** [comment]
Hi, yes I just upgraded to 3.5 of the botbuilder as well and I'm still getting this issue. It's actually impossible to avoid the issue on a cancelAction when using the prompt as well since we can't pass in configurations for the prompt style so this is now impossible to work around unless I avoid prompting for a confirmation of action cancelling.

**Comment by craigjensen** [comment]
I was able to successfully run the salesData sample you posted above in Slack.

![image](https://cloud.githubusercontent.com/assets/18585246/21825351/41f99f78-d738-11e6-846f-ae86faf8bd93.png)

Did you make sure your bot is configured correctly in Slack?  In particular, please make sure the Interactive Messages request Url is set to https://slack.botframework.com/api/Actions.

**Comment by BlueHatbRit** [comment]
I had it without `/api/Actions` it seems, I used the copy button from the box in the configurations so I'm not sure if this was an old route or something but it seems to be working fine now.

Thanks and sorry for spending your time on something so trivial! I did check this a few times last month if I recall but I guess I didn't check properly. Have a great week, feel free to close this ticket!
