### ISSUE TITLE
LUIS API authentication without the Bot Framework

### ISSUE THREAD

**Issue by eformx** [Microsoft/BotBuilder#1824]
I am working on my own Bot Builder (instead of the Bot Framework).  I currently enter my app id and subscription key to connect to the Language Understanding/MS Cognitive Services via the API in my Bot Builder and then handle the intents/actions.   I would like to share the tool with clients, each of which would have there own trained model via LUIS.

Is there a mechanism (like OAUTH) that I could use to make the link to the LUIS api endpoints so I don't have access to there app id or subscription key?  Does Luis api support something like this or is there another authentication method you can suggest?

**Comment by yshahin** [comment]
Unfortunately we don't have this kind of feature in LUIS.
Even if it exists you will still need to obtain their subscription key to access endpoint.
Either way people will have to trust you with their LUIS app key, that is if you are hosting the bots on your servers.
If your users provision an Azure key it will only have access to the endpoint its and only to the app they choose, this could be a better option for your customers. https://www.luis.ai/help#PublishingModel and scroll to the _Creating Subscription Keys Via Azure_  section

**Comment by dandriscoll** [comment]
Closing as it appears the question has been answered. If you want to discuss further, please at-mention or open a new issue.
