### ISSUE TITLE
Action Button in not able to render properly

### ISSUE THREAD

**Issue by anuxps** [Microsoft/BotBuilder#1826]
We are facing rendering issue for action button on aspx or html page. We are using Embed code to integrate with aspx/html page. I hope embed code channel would be appropriate to use in aspx/html page. We verified it in Chrome and Microsoft Edge browser.

![1](https://cloud.githubusercontent.com/assets/21247262/21022393/55e948ce-bd31-11e6-850b-544dc063f28e.png)

Here (Azure Basics) is the Button Display Text and the Url on Button Action Url. But in ASPX or html page Button Display Text(Azure Basics) converted to plane text and Button Action Url converted to Anchor tag.
Following was the result displayed in Bot Emulator, 

![2](https://cloud.githubusercontent.com/assets/21247262/21022439/78083e56-bd31-11e6-9726-e0e5bcfd9bae.png)

Please let us know how we can resolve this issue.

**Comment by eanders-MS** [comment]
Hi @anuxps I recommend trying out the new Web Chat control (in preview). The new control has richer support for buttons and cards. It is not enabled by default yet, but can be enabled from your bot's Web Chat channel configuration page on the Bot Framework dev portal. It is an open source project: https://github.com/Microsoft/BotFramework-WebChat

In addition, we released a new, open source emulator. It is cross-platform (Windows, OS X, and Linux). I encourage you to try it out: https://github.com/Microsoft/BotFramework-Emulator#download

**Comment by eanders-MS** [comment]
@anuxps going ahead and closing this issue now. Please open a new one if you need further assistance.
