### ISSUE TITLE
Microsoft Teams: Mentions only work in public rooms.

### ISSUE THREAD

**Issue by james-lawrence** [Microsoft/BotBuilder#1828]
does teams have a place to submit issues/suggestions besides here?

ideally they would work in private chat as well.

1) they support autocomplete when users are typing.
2) makes the code (on microsoft's end) more uniform.....
3) easier to parse out/deal with on the bot end.

**Comment by siduppal** [comment]
I will relay your request about having @ mentions work in private chats to the team.

Bots are only supported in private 1:1 chats in Teams right now so as a bot developer you don't have to deal with @ mentions today.

**Comment by james-lawrence** [comment]
well we want to deal with them =)

**Comment by borisovano** [comment]
+1 to @james-lawrence - we're also waiting to bots in channels and in group conversations!

**Comment by Andrea-Orimoto** [comment]
Closing this issue due to age, and because it seems that the team has gotten the feature request. Feel free to reopen if needed. Thanks!
