### ISSUE TITLE
Microsoft Teams: invite bot to team?

### ISSUE THREAD

**Issue by james-lawrence** [Microsoft/BotBuilder#1831]
how does one go about inviting a bot to a team and adding it to a group chat? using the bot uuid doesn't seem to work. I remember some documentation saying this wasn't implemented yet, but for the life of me can't find it currently.

**Comment by siduppal** [comment]
Bots in channels are not enabled in public preview right now.

**Comment by dandriscoll** [comment]
Closing this issue. Please at-mention or open a new issue if you'd like to discuss further. Thanks!
