### ISSUE TITLE
How to get more information about 500 error?

### ISSUE THREAD

**Issue by ncksol** [Microsoft/BotBuilder#1836]
I am playing with dialogues for my telegram bot and suddenly I've started to get 500 error from my bot on the following code:

```
            var messageText = Convert.ToString(activity.Text);
            if (string.IsNullOrEmpty(messageText)) return;

            if (activity.MentionsId(BotId) && messageText.ToLower().Contains("/delay"))
            {
                await Conversation.SendAsync(activity, delegate()
                {
                    var chatId = Convert.ToInt64(activity.Conversation.Id);

                    var delayDialogue = new DelayDialogue() {ChatId = chatId};                    
                    return delayDialogue;
                });
            }
```

Is there a way to see what's the actual exception that is occurring? I've tried to remote debug, but it reaches to the point of Conversation.SendAsync fine and then exceptions, never reaching the code of the delegate.

**Comment by willportnoy** [comment]
Have you tried running the code in the emulator?

https://docs.botframework.com/en-us/technical-faq/#how-can-i-troubleshoot-my-bot

**Comment by willportnoy** [comment]
I'm going to close this issue for now, but feel free to open a new issue for further discussion.
