### ISSUE TITLE
Attach image returns SendActivityToUserAsync FAILED

### ISSUE THREAD

**Issue by ispadoto** [Microsoft/BotBuilder#1838]
Hello! 

I'm trying to send images as attachment to facebook channel but the v3 API always returns this error: 

```
{
  "error": {
    "code": "ServiceError",
    "message": "SendActivityToUserAsync FAILED: {\"error\":{\"message\":\"(#546) The type of file you're trying to attach isn't allowed. Please try again with a different format.\",\"type\":\"OAuthException\",\"code\":546,\"error_subcode\":1545026,\"fbtrace_id\":\"Eb7Yagm1g4k\"}}"
  }
}
```

The object that I'm sending: 
```

{
  "type": "message",
  "id": "[my conversation ID]",
  "timestamp": "2016-11-26T16:48:56.736Z",
  "localTimestamp": "2016-11-26T16:48:56.736Z",
  "serviceUrl": "https://facebook.botframework.com",
  "channelId": "facebook",
  "from": {
    "id": "[my bot ID",
    "name": "Bot"
  },
  "conversation": {
    "isGroup": true,
    "id": "[conv ID]",
    "name": ""
  },
  "recipient": {
    "id": "[ facebook user id]",
    "name": "[facebook user name]"
  },
  "textFormat": "plain",
  "attachmentLayout": "",
  "membersAdded": [],
  "membersRemoved": [],
  "topicName": "",
  "historyDisclosed": true,
  "locale": "us",
  "text": "An image",
  "summary": "",
  "attachments": [ {
      "contentType": "image/jpeg",
      "contentUrl": "https://webappbrasil.blob.core.windows.net/teste/9d3e993a-a8b5-427c-a538-2f053351920c-pirarara.jpeg",
      "content": {},
      "name": "Image File",
      "thumbnailUrl": ""
    }
  	],
  "entities": [],
  "channelData": {},
  "action": "",
  "replyToId": "[bot id]",
  "value": {}
}
```

I'm using API https://facebook.botframework.com/v3/conversations/[conv-id]/activities
When I send a PDF File, works like expected, the problem occours when I try to send images and microsoft office files... 

Could you help me to find where I'm making mistakes? Or this is a real issue?

Thanks!

**Comment by ispadoto** [comment]
I believe I have found the problem.
My azure storage is blob type. When I put the image link in the browser, it automatically downloads, and does not display the image in the browser as it should. I used the same json object mentioned above with an image from the web and it worked normally.
I need to study Azure's storages to make it public.

**Comment by eflorespalma** [comment]
@ispadoto How do you solve that problem with the storage, i have the same problem.

**Comment by ispadoto** [comment]
I changed the storage type of my blob container (blob type) to block blob... Works fine
