### ISSUE TITLE
Entering the name of the FormFlow parameter as part of the value does not work

### ISSUE THREAD

**Issue by IanBoggs** [Microsoft/BotBuilder#184]
Hi,

Let us assume you have a FormFlow Dialog with a string parameter called 'Title' 

If, when prompted for the value of Title, you enter anything that has the word Title in it (for example 'A Godd Read, A Working Title' then it is not accepted by the Dialog and the user is prompted to enter the parameter again.

**Comment by chrimc62** [comment]
This is a bug and we will have a fix in the next release--thanks for bringing it to our attention.  In the meantime you can always force the entry by putting your response in quotes, i.e. "A working title" will not interpret the response as a navigation to the title field which is what is happening.
