### ISSUE TITLE
Get response from bot after during inactivity 

### ISSUE THREAD

**Issue by kanwal019** [Microsoft/BotBuilder#1841]
Can we get a sample response from the bot incase the user is inactive for a while.

For example -

If bot asks the user for any input and the user is not able to give any for a certain time interval. Bot should ask the user "Are you there ?" or some other message.

**Comment by kanwal019** [comment]
@msft-shahins Any solution regarding this ?

**Comment by msft-shahins** [comment]
@kanwal019 you can schedule a task, e.g. using azure scheduler or queue, to send a proactive message to user if you detect inactivity. If you look at the documentation for [proactive bot template](https://docs.botframework.com/en-us/azure-bot-service/templates/proactive/#navtitle) you can see how it queues a message in azure queue and generate triggers to the bot from messages in the queue that causes bot to send messages to the user.

**Comment by kanwal019** [comment]
@msft-shahins How can I detect inactivity in a conversation. The given example helps in sending the async messages to the user. My requirement need me to send a message to the user, only if the user is inactive more than a particular span of time

**Comment by msft-shahins** [comment]
@kanwal019 there are different ways that I can think of. Basically you need a record in your system keeping track of the last time that your bot have interacted with the user. For example, you can schedule the timer first time that you interact with the user and then reset it each time that your get a message from the user.
