### ISSUE TITLE
Missing Authentication header in CreateDirectConversationAsync

### ISSUE THREAD

**Issue by bbramsted** [Microsoft/BotBuilder#1844]
I'm trying to create a web service, which will start a new Slack conversation from a bot to a user. I use the latest c# SDK (version 3.3.3).

I have the following code:

```
var botAccount = new ChannelAccount(name: "aaa", id: "bbb");
var userAccount = new ChannelAccount(name: "ccc", id: "ddd");

MicrosoftAppCredentials creds = new MicrosoftAppCredentials("eee", "fff");
var connector = new ConnectorClient(new Uri("https://slack.botframework.com"), creds);

var conversationId = await connector.Conversations.CreateDirectConversationAsync(botAccount, userAccount);
````

This always returns 403 - Forbidden.

Using Fiddler, I can see that the POST'ed data is missing the Authentication header:

````
POST https://slack.botframework.com/v3/conversations HTTP/1.1
User-Agent: FxVersion/4.6.1586.0 Windows_10_Enterprise/6.3.14393 Microsoft.Bot.Connector.ConnectorClient/3.3.3.0
Content-Type: application/json; charset=utf-8
Host: slack.botframework.com
Content-Length: 188
Expect: 100-continue
Connection: Keep-Alive

{
  "bot": {
    "id": "aaa",
    "name": "bbb"
  },
  "members": [
    {
      "id": "ccc",
      "name": "ddd"
    }
  ]
}
````

I if manually POST the same data, but insert a valid Authentication header, the call succeeds.

Am I missing something obvious here?

**Comment by bbramsted** [comment]
Posting the above made me look at the code again. 

Adding
´´´
await connector.HttpClient.AddAPIAuthorization("eee", "fff");
´´´
before the call to CreateDirectConversationAsync fixes the problem.

That does no seem logical to me, as I have already provided the same credentials in the line just before.

**Comment by msft-shahins** [comment]
This is related to issue #1729. You can modify your code snippet to look like this and it should start setting the authorization header for the outgoing requests from your bot. 

```csharp
MicrosoftAppCredentials.TrustServiceUrl("https://slack.botframework.com");

var botAccount = new ChannelAccount(name: "aaa", id: "bbb");
var userAccount = new ChannelAccount(name: "ccc", id: "ddd");

MicrosoftAppCredentials creds = new MicrosoftAppCredentials("eee", "fff");
var connector = new ConnectorClient(new Uri("https://slack.botframework.com"), creds);

var conversationId = await connector.Conversations.CreateDirectConversationAsync(botAccount, userAccount);
```

You can read more on why it is necessary to call TrustServiceUrl here: https://github.com/Microsoft/BotBuilder/issues/1729#issuecomment-263430456
