### ISSUE TITLE
[node.js] EntityRecognizer is very relaxed when parsing afirmative/negative responses

### ISSUE THREAD

**Issue by JoseAntonioRodriguez** [Microsoft/BotBuilder#1846]
When answering to a `Prompt.confirm` dialog, `yes, please` is recognized as an affirmative response (which is great), but `yesterday` is also recognized as an affirmative response.

**Comment by cahann** [comment]
is this entity recognize a luis model?

**Comment by JoseAntonioRodriguez** [comment]
Don't think so. It's the EntityRecognizer used by `Prompts` dialogs.

**Comment by carlosscastro** [comment]
Hi Jose, 

Would you mind sharing a snippet showing your bot's code so I can see what is going on here?

Thanks!

**Comment by Stevenic** [comment]
I took the pull request
