### ISSUE TITLE
How to distinguish the message in the private and public channels?

### ISSUE THREAD

**Issue by wiltodelta** [Microsoft/BotBuilder#185]
Subj

**Comment by tomlm** [comment]
If it is a direct message the TotalParticipants count will be 2

**Comment by wiltodelta** [comment]
@tomlm It's not good solution. Because, TotalParticipants may increase in public or private channel in Slack and new users can read your personal messages from/to bot.

**Comment by aakashvit** [comment]
I am facing same issue, can you provide better solution
