### ISSUE TITLE
Bot review process so slow 

### ISSUE THREAD

**Issue by tahsintahsin** [Microsoft/BotBuilder#1850]
I have been trying to publish my skype bot to Microsoft Bot Directory, it has been almost two weeks and it is still in review. I just want my skype bot to be easily found for any skype user by simple search. My questions are:

1- Do you have a list of must haves for the bot so that they can only accept it if it fulfills these requirements? You didn't reject mine either but I will be prepared in advance in case you do.

2- If yes where can I find this info?

3- Has anyone here submitted their bot and how long did it take for them to be published?

Thank you

**Comment by JPThorne** [comment]
We're planning on publishing our bot via multiple channels in a month or so, would be good to get some indication of the submission requirements & timeframes

**Comment by LMEdwards** [comment]
We submitted out bot for review on Nov 30...still waiting.

**Comment by hailiu2586** [comment]
Thanks for submitting the issue. Can you send us the botId that has been in review for a while, so we can take look at what's going on?

**Comment by LMEdwards** [comment]
App ID  d0c51261-0af6-41c9-9654-af10bf1d4c24

**Comment by tahsintahsin** [comment]
Thank you @hailiu2586 , our app id is : 59fcba99-2720-469f-9758-d83fb6a76096​​​ .

**Comment by vignestheo** [comment]
Any one please provide guideliness for Terms of Use and Privacy URL because of those content my bot getting rejected from MS Team.. :-(

**Comment by LMEdwards** [comment]
Incident #1863 has been opened for our bot, App ID d0c51261-0af6-41c9-9654-af10bf1d4c24.   Maybe that will help to obtain an answer...or maybe not.

**Comment by Noc2** [comment]
I’m probably waiting for two months now. Once I got a message, which said that my bot was rejected and the Terms of Use were missing (which I am pretty sure wasn’t true). Getting at least some feedback would be helpful. Facebook reviewed my bot in less than a week. At the moment, I just concentrate on Facebook messenger. 
Microsoft App ID: 64ba2a82-af90-43f0-8aea-42a95405a1ba

**Comment by tahsintahsin** [comment]
Still didnt get any responses. Can @Stevenic help us or redirect us to someone who can help ?

**Comment by chetanmekha** [comment]
I face the same issue and received the same feedback from Skype side. After receiving feedback come to know that terms and condition , policy are mandatory for bot approval on Skype.

**Comment by vignestheo** [comment]
Guys any one give examples for terms and condition and policy for bot

**Comment by chetanmekha** [comment]
terms and condition : http://getmassively.com/TOS.pdf
privacy : http://getmassively.com/Privacy-Policy.pdf
You can use it as a reference.

**Comment by vignestheo** [comment]
@chetanMekha

Really thanks for your timely help

**Comment by dandriscoll** [comment]
Hi @tahsintahsin, every bot is unique and our bot review team looks at whether the bot is functioning properly and meets our policy requirements for each of our Microsoft channels (Skype, Teams, and more coming over time).

I don't have an exhaustive list of requirements. However, at a minimum, your bot must be functional in order to be reviewed. (I.e., it should return real text and not be silent or return error messages.) Additionally, the required fields in the bot submission form (fields like the Terms of Use and Privacy Policy) must contain real links to these documents.

There is currently a bit of a delay in reviewing bots, and we're working through the backlog. Very sorry for the delay. Please let us know if you have any questions.

**Comment by mohit-infostretch** [comment]
@dandriscoll 
I have also submitted a bot for publishing and have met the criteria of TOS and Privacy Policy. Considering the last comment you have given, the bot meets the required description and behaviour.
The bot id is infostretch_nest
A feedback from the review team or an email address where we can send queries related to publishing status would be helpful.

**Comment by Andrea-Orimoto** [comment]
Detailed bot review guidelines are documented here https://docs.botframework.com/en-us/directory/review-guidelines/. This includes some explanation of the required privacy and terms documents.

I believe our review team has cleared the review backlog, and there should be no pending bot older than two weeks in the queue. If anybody has an older submission stuck in review, please open a new issue specifying the bot handle (the url to the bot in the dev portal is enough), or reach out to botreview@microsoft.com.

Apologies for the delays we experienced in the past. Closing this issue, but feel free to open new ones as needed.

**Comment by jigneshroutemobile** [comment]
My Bot is in review, don't know how long it will take to approve.
My APPID: 94de2a51-4586-4d75-b782-ac431ffb5148

**Comment by jigneshroutemobile** [comment]
My Bot is Published but i am not able to search in Skype.
I can see my Bot in Microsoft Bot Directory but i am not able to search it using Skype.
can any one assist on this.??

**Comment by sunilaigal** [comment]
My BOT is in review, not sure what is wrong..
APP ID: ID: 270fcf93-1730-461a-83d6-2b6cd383760f

Can anyone help?

**Comment by qpongo** [comment]
I submitted my bot a month ago an it's still "In Review."
APP ID: e35edacc-32bd-4c9d-9dba-8005c1214e3f

The bot runs in 23 languages and supports 60 countries!

It's now been approved on Telegram, Kik and Facebook but not on Skype.

Can someone help?

**Comment by damian1976** [comment]
I have the same issue. Skype Bot is waiting in "In Review" state. APP ID is c6620653-4023-4497-a0bf-8b9bc0d33a92.

**Comment by seul88** [comment]
I'm facing the same problem - my bot stays "In Review" for over 10 days. 
(ID: da50fc85-0ae0-4424-9b3d-95097c97b55d )

**Comment by riccardo91** [comment]
Same problem here. it's **one month** that we are waiting. It's ridiculous .
No direct support, no direct email. no way to get any answer.

7792dce2-616d-466e-a2d9-bcadcb22dde3
