### ISSUE TITLE
Constant repeated reply on Microsoft Teams(when Web chat and emulator work as expected)

### ISSUE THREAD

**Issue by manums** [Microsoft/BotBuilder#1851]
My bot tries to send a signin card to the user when user has not authenticated but he tries to communicate with the bot. It starts like Bot sends a reply using "ReplyToActivityAsync" and replies with a message asking user to use below prompt to login. Bot tries to send next message with signin card next so that user can login on external application. *This works all good on web chat and even on emulator*. Web chat gives prompt with SignIn card to user and after user login it starts accepting user messages.

When messaged from **Microsoft teams bot just keeps playing first message asking user to use login, without sending sigin card or any other message**. Bot code uses ReplyToActivityAsync for almost every message including sigin message. 

Any help would be great? I'm stuck with this.

I tried logging out of teams and adding bot through test link again, adding bot after renaming bot etc. Nothing has worked till now with teams.

**Comment by siduppal** [comment]
Apologize for the confusion. There's a bug preventing sign-in card from showing up that we are actively working on addressing.

**Comment by manums** [comment]
@siduppal Is there any alternative which I can use for signin prompt? Plain attachment with an url does not look that great for signin. 

Also may I know when the fix is planned to be out?

**Comment by siduppal** [comment]
Sure, you can simply send a Hero or Thumbnail card with one action-button of type OpenUrl and specify the login URL as the value.

**Comment by manums** [comment]
Thanks will try that. If it's okay, can you please paste a snippet for reference?

**Comment by siduppal** [comment]
Instead of creating a sign-in card attachment, create one like this:

                        var card =  new Attachment()
                        {
                            ContentType = ThumbnailCard.ContentType,
                            Content = new ThumbnailCard()
                            {
                                Text = "Please login to continue",
                                Buttons = new List<CardAction>()
                                {
                                    new CardAction()
                                    {
                                        Title = "Login",
                                        Type = ActionTypes.OpenUrl,
                                        Value = "https://login.domain.com"
                                    }
                                }
                            }
                        };

**Comment by siduppal** [comment]
The fix for signin card is now being deployed.

**Comment by manums** [comment]
@siduppal  I will try signin card today by adding latest packages. you can go ahead close this issue, if it's already addressed.
