### ISSUE TITLE
Facebook Messenger UI rendering issues

### ISSUE THREAD

**Issue by ankitzaveri** [Microsoft/BotBuilder#1852]
Hello,

I am writing a bot using Ms bot framework (C#) for Facebook messenger and facing UI issues like button text getting cut(with three dots(...) appended), message got cut after certain text etc. Attached sample images for the reference. I don't see such issues in Skype or emulator.

Please let me know if there is a way to format text using C# to avoid these kind of issues or if there is any workaround. 

Thanks,
![bot_fb_issue](https://cloud.githubusercontent.com/assets/24542662/21135685/bf2ef1e2-c148-11e6-8334-61b1f982e8f2.png)
![bot_fb_issue_2](https://cloud.githubusercontent.com/assets/24542662/21135682/bda60a72-c148-11e6-8d8c-2678e8b10b1a.png)

**Comment by JPThorne** [comment]
@ankitzaveri we ran into this issue a few weeks back, as far as I'm aware there is a hard limit on the number of characters you can use for a buttons text in FB.

**Comment by msft-shahins** [comment]
Facebook send api has a limit on number of characters in the text field. Facebook connector splits the message into multiple messages if the length of text exceeds the limit enforced by Facebook send api.
