### ISSUE TITLE
Customize Carousel Cards

### ISSUE THREAD

**Issue by b4usat** [Microsoft/BotBuilder#1853]
Can we have the options to  customize carousel cards in `webchat `window at-least? Very minimal requirement for mine is changing the color of each cards as like windows tiles.

**Comment by danmarshall** [comment]
The webchat is now an open-source control that you may customize as you see fit: https://github.com/Microsoft/BotFramework-WebChat

There are instructions there as how you may develop, build, and self-host your own webchat control.
