### ISSUE TITLE
Dealing with ampersands on Kik

### ISSUE THREAD

**Issue by JamieREvans** [Microsoft/BotBuilder#1854]
Whenever I send up an ampersand as a part of a "card" to my Kik bot, it get's escaped into `&amp;`. However, if I escape or encode it, it just shows up as the escaped or encoded version. Is there any way to send an ampersand to Kik and not have it escaped?

**Comment by LarsLiden** [comment]
Replicated this issue.  Investigating.

**Comment by LarsLiden** [comment]
Issue has been resolved, fix will be included in next publish.  Thank you for finding this bug!
