### ISSUE TITLE
Missing REST API documentation

### ISSUE THREAD

**Issue by gbowerman** [Microsoft/BotBuilder#1855]
The main docs page: https://docs.botframework.com/en-us/ says:
For those using other languages, see the framework’s [REST API](https://docs.botframework.com/en-us/connector/overview/). The REST API link returns a 404.

**Comment by dandriscoll** [comment]
Fixed, thanks!

**Comment by zentoid** [comment]
From the REST API link above. 
https://docs.botframework.com/en-us/connector/overview/ <-- Returns a 404

From the "Bot Connector REST API" link on the REST API / Bots menu "Can't read from server. It may not have the appropriate access-control-origin settings.". 

This link is what is now on the "https://docs.botframework.com/en-us/" page --> https://docs.botframework.com/en-us/restapi/connector/

Returns "Can't read from server. It may not have the appropriate access-control-origin settings." for me.

**Comment by dandriscoll** [comment]
Hi @zentoid, the /en-us/connector/overview page doesn't have content, so I've fixed inbound links so they point to /en-us/restapi/connector, instead.

Can you send a screenshot of where you're seeing the error? I've tried every major browser and https://docs.botframework.com/en-us/restapi/connector/ seems to load fine.

**Comment by zentoid** [comment]
Hi @dandriscoll 

It seems to be something up with my firefox (50.1.0) as it loads ok in chrome.

Screenshot link: 
https://www.dropbox.com/s/5mga4hdhho3zwwg/Screenshot%20from%202016-12-21%2021-44-33.png?dl=0

**Comment by dandriscoll** [comment]
Strange, it works for me in both FF 50.0 and 50.1.

Are you familiar with the F12 network debugger and if so, can you see if the page is trying to issue any OPTIONS requests to the service?

**Comment by zentoid** [comment]
I removed and reinstalled Firefox and now the page seems to load fine. Not sure what it was unfortunately.

Thanks @dandriscoll
