### ISSUE TITLE
Initiating a conversation from bot

### ISSUE THREAD

**Issue by kanwal019** [Microsoft/BotBuilder#1857]
As described in issue #1811, I tried to initiate the conversation from my bot application. It gives the desired output when used in the emulator. But when I use the webchat or directline channel it does not give me the  desired result.

For example - 

If my username is User001 and botname is Bot001. The result is "Welcome User001 !" in the emulator and "Welcome Bot001 !" in the webchat and directline channels.

**Comment by eanders-MS** [comment]
Thanks for reporting this. It looks like the emulator is sending both the bot and the user in the `membersAdded` list of the `conversationUpdate` activity, but directline/webchat is only sending the bot. We will make them consistent. In the meantime, you should be able to get consistent behavior by filtering the `membersAdded` list by the `message.from.id` value.

**Comment by kanwal019** [comment]
@eanders-MS 'message.from.id' gives the same result as the 'recipent.id'. I need to show a welcome message with the username on the initiation of the webchat. Is there any other possible way to get the desired result ?

**Comment by eanders-MS** [comment]
@kanwal019 Ah, I see it now. DirectLine is not including the user in the conversationUpdate activity. This is a bug in DirectLine. A fix is in the works. In the meantime, you should be able to work around the issue by using the `message.user` field:

```javascript
bot.on('conversationUpdate', (message) => {
    if (message.membersAdded) {
        const reply = new builder.Message()
            .address(message.address)
            .text('hello ' + message.user.name || message.user.id);
        bot.send(reply);
    }
});
```

Will this work for you in the interim?

**Comment by kanwal019** [comment]
@eanders-MS  Sure, This works for me. Thnaks

**Comment by dandriscoll** [comment]
This issue was fixed in a recent deployment. Please at-mention or open a new issue if you have any questions.
