### ISSUE TITLE
Error occurred  integrating IIS Server to Microsoft Bot

### ISSUE THREAD

**Issue by sencsk1** [Microsoft/BotBuilder#1858]
Hi Team,
I'm trying to integrate Bot with Facebook. i have mentioned the steps what all i did. if anything i missed and anything i did wrong please advice and guide me.
I created the bot application and deploy through custom mode using .Net Framwork 4.6. in my server having .Net framwork V4.5.

I run the application locally using the Bot Emulator its working fine after that only i have deployed it to server its not working.   its throw me so many errors by the time by time. in my guess i deployed the Bot as sub application maybe its might be reason.

my domain: https://www.abc.com/**TSBot**/api/messages
The above url i used to configue Messaging endpoint.  i fill the app secret, app id and bot id. but its throw me the errors . one time its throw me **parameter name:Miising Appid**. other some times its throw below error

InternalServerError
{
  "message": "An error has occurred.",
  "exceptionMessage": "The object has not yet been initialized. Ensure that HttpConfiguration.EnsureInitialized() is called in the application's startup code after all other initialization code.",
  "exceptionType": "System.InvalidOperationException",
  "stackTrace": "   at System.Web.Http.Routing.RouteCollectionRoute.get_SubRoutes()\r\n   at System.Web.Http.Routing.RouteCollectionRoute.GetRouteData(String virtualPathRoot, HttpRequestMessage request)\r\n   at System.Web.Http.WebHost.Routing.HttpWebRoute.GetRouteData(HttpContextBase httpContext)"
} 

or 

Multiple types were found that match the controller named 'messages'. This can happen if the route that services this request ('api/{controller}/{id}')

Route config is 
   config.MapHttpAttributeRoutes();
              config.Routes.MapHttpRoute(
                name: "DefaultApi",
                routeTemplate: "api/{controller}/{id}",
                defaults: new {  id = RouteParameter.Optional }

Please guide me to fix it.

**Comment by msft-shahins** [comment]
This is probably related to the way that you set up the routes in your asp.net application and iis server and not related to bot builder. I did a quick search for your error and this [stackoverflow](http://stackoverflow.com/a/7842369/4237950) answer might help. 

Closing this. Feel free to open another issue in future if you have problem with bot builder.

**Comment by sencsk1** [comment]
thanks for posting msft-shahins, i have changed and tried all the cases in the route config but no use . my website is "https://www.abc.com/" and i created the application inside the aplication "TSBot" so my url look like this[https://www.abc.com/TSBot/api/messages] . if i run without api/messages then i can see the default page when i add the api/messages behind the url its wont work . my route cofig template is routeTemplate: "api/{controller}/{id}", is there any mistake so suggest me
