### ISSUE TITLE
Need help to send a message in daily basis 

### ISSUE THREAD

**Issue by vignestheo** [Microsoft/BotBuilder#1861]
Hello Team 

Need help to send bot message to users at particular time in daily basis .

I am using node js and whether we can send those message to all channels?

**Comment by palmerabollo** [comment]
Your want to send a **proactive message** from the bot to the user.
You need to store the user's address (extracted from one of the messages from that user) in your system and schedule some kind of daily timer (ex. `setTimeout`). This way you can send the message to the user. Look for proactive messages in the issues list.

**Comment by msft-shahins** [comment]
@vignestheo as @palmerabollo suggested you can schedule a task, e.g using azure task scheduler, that triggers your bot with the user's [Address](https://github.com/Microsoft/BotBuilder/blob/8f0d6bbc1ef0fcef99b04560391384aba8fcde15/CSharp/Library/Microsoft.Bot.Builder/Dialogs/Address.cs#L45) and then your bot can use the address to compose a message and send it to the user. 

You can read the documentation for [azure proactive bot template](https://docs.botframework.com/en-us/azure-bot-service/templates/proactive/#navtitle) as an example for how to send proactive messages using azure queue.
