### ISSUE TITLE
Sending a message from bot in-case of inactivity 

### ISSUE THREAD

**Issue by kanwal019** [Microsoft/BotBuilder#1865]
Can we send a message from bot incase the user is currently inactive ?

For example - 

If bot asks "Should we proceed ?" and expects a response in yes/no, the bot should resent the question or some other text to alert the user, when no response is sent from the user, even after 50-60 seconds.

**Comment by b4usat** [comment]
We implemented the similar scenario by putting a timer control. After some seconds, message will be pushed to the user.

**Comment by kanwal019** [comment]
@b4usat I am able get the same using the timer, which updates every time `(action.type === 'Receive_Message')` in `exports.history` module of `botchat.js`. Thank You :)
