### ISSUE TITLE
Microsoft botbuilder UniversalBot implicit (default) dialog throws no dialog error

### ISSUE THREAD

**Issue by var23rav** [Microsoft/BotBuilder#1867]
All [botbuilder examples](https://github.com/Microsoft/BotBuilder/tree/master/Node/examples) give **no dialog error on execution.**
`Error: Dialog[*:/] not found.`

**The second parameter ( defaultDialog ) in [UniversalBot constructor](https://docs.botframework.com/en-us/node/builder/chat-reference/classes/_botbuilder_d_.universalbot.html#constructor) not working.**

**Issues Found in**: [hello-ChatConnector](https://github.com/Microsoft/BotBuilder/blob/master/Node/examples/hello-ChatConnector/app.js#L24), [basics-waterfall](https://github.com/Microsoft/BotBuilder/blob/master/Node/examples/basics-waterfall/app.js#L19),.. etc
```
var bot = new builder.UniversalBot(connector, function (session) {
    session.send("You said: %s", session.message.text);
});
```

**Solution**:

_Explicitly specifying **default dialog( / )** and callback_
```
var bot = new builder.UniversalBot(connector)
bot.dialog('/', function (session) {
    session.send("You said: %s", session.message.text);
});
```
**It seems like we need the default dialog all the time.**

Please verify this !

**Comment by Stevenic** [comment]
These examples are designed to work with version 3.5 which hasn't been released yet. To use 3.5 you should install using "npm install --save botbuilder@next"

**Comment by var23rav** [comment]
_Since all the example codes are in_ **master** branch, I think its better to mention these dependencies in package.json file.
