### ISSUE TITLE
How to use Bing Intents and entities?

### ISSUE THREAD

**Issue by dhirajgupta1** [Microsoft/BotBuilder#1868]
Hello,

I enabled Bing Entity and Intent Detection in my bot but didn't observe any change in my bot.
Please help me in following
1) Any sample or example demonstrating how to use Bing (or Cortana) Intents and Entities (C#) ?
2) Is it possible to use Bing Intents and Entities along with my LUIS Model to make my chat bot intelligent enough to respond open world queries apart from specific business use case ?

Thanks,
Dhiraj

**Comment by msft-shahins** [comment]
@dhirajgupta1 bing entity and intent detection is a preview feature that is only available for skype channel. Detected intents and entities are coming in as part of [activity.Entities](https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Microsoft.Bot.Connector/ConnectorAPI/Models/Activity.cs#L178). Here is an example of detected intent and entities on the incoming activity.Entities when you say 'set an alarm at 8am' to the bot:

```json
Properties: {{
  "data": {
    "domain": "prebuilt",
    "intent": "microsoft.alarm.set_alarm",
    "confidence": 0.00648482656106353,
    "entities": [
      {
        "name": "microsoft.generic.time",
        "value": "08:00:00",
        "source": "8am"
      }
    ]
  }
}}
```
Currently SDK doesn't support dispatch of the activity based on the detected intents on the incoming message. It is up to developer to dispatch to the right intent handler after parsing the incoming activity's entities. For example, you can register a global scorable with your bot that interrupt the stack when it sees bing intents in the activity.Entities and implement the desired intent handling. 

You can combine multiple Luis models + bing intent and entities to implement a bot that can handle different intents by implementing the desired intent handler/action.
