### ISSUE TITLE
CreateDirectConversation with Facebook

### ISSUE THREAD

**Issue by matias87** [Microsoft/BotBuilder#1869]
Hello,

When I create a conversation with an user, I use the next code. If I use it for skype or telegram i have not problem, the CreateDirectConversationAsync method return an correct Id, but if I use it for Facebook, this method crash and return "CreateConversationAsync FAILED: Missing Bot Id", any idea?

var userAccount = new ChannelAccount()
                {
                    Id = this.IdUserBot,
                    Name = this.Name
                };
                var botAccount = new ChannelAccount()
                {
                    Id = "myIdBot",
                    Name = "myNameBot"
                };
                var connector = new ConnectorClient(new Uri(this.ServiceUrl));
                var conversationId = await connector.Conversations.CreateDirectConversationAsync(botAccount, userAccount);
                IMessageActivity message = Activity.CreateMessageActivity();
                message.From = botAccount;
                message.Recipient = userAccount;
                message.Conversation = new ConversationAccount(id: conversationId.Id);
                message.Text = "text";
                message.Locale = "es-Ar";
                var result = await connector.Conversations.SendToConversationAsync((Activity)message);

Thanks

**Comment by msft-shahins** [comment]
@matias87 are you using the bot id scoped to facebook channel? Keep in mind that you can only create a direct conversation with a user that your bot have interacted with before. 

Generally, you need to keep the [address](https://github.com/Microsoft/BotBuilder/blob/8f0d6bbc1ef0fcef99b04560391384aba8fcde15/CSharp/Library/Microsoft.Bot.Builder/Dialogs/Address.cs#L58) based on a previous conversation that your bot had with a user and use the address to proactively initiate the conversation with the user.

**Comment by matias87** [comment]
Hello @ msft-shahins yes, I save the userId (facebookId, SkypeId, etc) in the initial conversation. I have problems only with Facebook, the other platforms work well.
I understand that the CreateDirectConversationAsync method works only with the userId.
Maybe saving the last conversationId can create an activity and make a reply.

**Comment by matias87** [comment]
I solved it, I did not realize that the bot's credentials are different for facebook, telegram or skype.
In my code, "myIdBot" is diferent for each plataform.
var botAccount = new ChannelAccount()
{
Id = "myIdBot",
Name = "myNameBot"
};

Thanks a lot
