### ISSUE TITLE
LuisIntent with required parameter not being called

### ISSUE THREAD

**Issue by alexcocian** [Microsoft/BotBuilder#1870]
I have an intent with a required parameter. When I write a query without that parameter, the bot replies automatically with the message defined in the LUIS Model.
![image](https://cloud.githubusercontent.com/assets/15215157/21270516/ab38bc94-c3bf-11e6-93ec-85abe3b6b612.png)
The problem is that if I supply **just** the parameter as an answer, it does not work because it re-evaluates the text (ignoring the fact that it's an answer to a prompt).

How should these scenarios be handled?

**Comment by msft-shahins** [comment]
Are you using the bot builder [LuisDialog](https://github.com/Microsoft/BotBuilder/blob/8f0d6bbc1ef0fcef99b04560391384aba8fcde15/CSharp/Library/Microsoft.Bot.Builder/Dialogs/LuisDialog.cs#L143) to call Luis api? With C# bot builder 3.4, we added support for [LuisActionDialog](https://github.com/Microsoft/BotBuilder/blob/8f0d6bbc1ef0fcef99b04560391384aba8fcde15/CSharp/Library/Microsoft.Bot.Builder/Dialogs/LuisDialog.cs#L286) that is responsible for relaying back and forth the prompt/answers for action parameters to the Luis api. Once all of the parameters are filled and action is triggeted, LuisActionDialog returns and dispatches the result back on the LuisDialog and then the intent handler can consume the collected parameters.

Here is a sample [model](https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Samples/PizzaBot/Model/PizzaBot.json#L60) and sample [dialog](https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Samples/PizzaBot/PizzaOrderDialog.cs#L92) consuming the parameters collected by LuisActionDialog. 

If you are calling the Luis rest API directly, you need to provide the contextId of the dialog returned from previous Luis API call to let Luis know that the query you are providing is the answer to a triggered prompt dialog.

**Comment by alexcocian** [comment]
I'm not calling the API directly, I'm using a class inherited from LuisDialog<object> with a LuisModel attribute. If the user writes a query to the bot that does not have a required parameter, my code doesn't get called anymore because the "Prompt" text defined in the Luis Model is shown automatically.

Anyway, I managed to get it working by adding a Phrase List (for a predefined set of supported answers) and a JsonRequest Fulfillment. I still don't understand why it works though...or rather why it did not work before.
