### ISSUE TITLE
Calling API to talk to Bot

### ISSUE THREAD

**Issue by srozga** [Microsoft/BotBuilder#1871]
Seems like the new calling API doesn't really integrate with a bot itself. I would like to create a calling API bot that connects to a bot created using the Bot Framework. 

First, are there plans to make this more seamless at any point? 

In the meantime, it seems I can implement this. It seems that connecting it directly to my messaging controller from the calling controller does not make sense because I need to receive all the responses which technically will be going through a connector. So sounds like my calling controller should connect to directline API. For free text entry, it could use the Record action, which I could then pass through say Bing STT before sending to directline. For quick replies I could use the Recognize actions. Sounds doable. But again, do you guys have plans on tying the two together? :)

Thanks!
-s

**Comment by nwhitmont** [comment]
@srozga what version of the BotBuilder SDK are you using? C# or Node?

**Comment by srozga** [comment]
C#

**Comment by ejadib** [comment]
You don't really need Direct Line for this if your planning to talk with the bot in the skype channel where the call was originated. Once the incoming call is received, you can save the list of participants `ncomingCallEvent.IncomingCall.Participants` and then use that information to send a proactive message to the bot.

[This sample](https://github.com/daltskin/VoiceBot) does something like that. [Here ](https://github.com/daltskin/VoiceBot/blob/master/EmergencyServicesBot/IVRBot.cs#L60) is where it saves the participants and this is the [class ](https://github.com/daltskin/VoiceBot/blob/master/EmergencyServicesBot/AgentListener.cs) that sends the proactive messages.
