### ISSUE TITLE
Detect when LUIS fails and act accordingly  

### ISSUE THREAD

**Issue by cesarvarela** [Microsoft/BotBuilder#1872]
Hi, our luis model is 404ing right now, and the `onDefault` intent is being triggered.

Whats the recommended way to handle this?

We would like to show a custom message.

**Comment by msft-shahins** [comment]
@Stevenic is there a way to catch Luis service call failures in node.js SDK and send a custom message to user?

**Comment by Stevenic** [comment]
You shouldn't be getting `onDefault` for a 404 from LUIS. Any error results in `session.error()` being called. Are you sure you're utterance isn't just not being detected.  This can happen when the intent score returned is below 0.1. Typically that means you haven't trained your model enough.

**Comment by cesarvarela** [comment]
I was going over the free quota of LUIS calls, and that was what triggered  the `onDefault`.

**Comment by dandriscoll** [comment]
Hi @cesarvarela, did this answer your question?

**Comment by cesarvarela** [comment]
I'd say yes, but you might want to check what I said about going over the free quota throwing and error instead of throwing `intent = null, and score = 0.1` which isn't what is really happening.

**Comment by dandriscoll** [comment]
@Stevenic, is it possible a 429 from LUIS is resulting in `onDefault` instead of `session.error()`?

**Comment by Stevenic** [comment]
I did some fixes around this that were pushed out a few weeks ago. Please tell me if you're still seeing this issue and I'll reopen it.
