### ISSUE TITLE
Azure Assembly documentation

### ISSUE THREAD

**Issue by srozga** [Microsoft/BotBuilder#1873]
I cannot find any documentation for this assembly. Looking at the code for the .Azure assembly, I could see us using this code very soon. I am somewhat confused as to how it should be used though. Seems like there are two Modules I need to include: TableLoggerModule to get the table logging functionality and AzureModule for storing the conversation messages into an Azure table. For the TableLoggerModule I pass the Storage account in code. For the AzureModule, I need to specify the module to use TableStorage and the Table connection string in app settings? Any documentation for this?
Thanks
-s

**Comment by srozga** [comment]
bump

**Comment by lgmorand** [comment]
same question here.

**Comment by srozga** [comment]
[This repo](https://github.com/Microsoft/BotBuilder-Azure) has some good documentation around this. Biggest problem for us was figuring out that we needed to extend the Conversation.Container as we forgot about that. So that was just a small oversight but it's working. We aren't terribly happy with the TableLogger as it only has 3 columns: From, To, and the Activity in, I believe, binary serialized format. Which is tricky as we'd like to run analytics on that data. For now we're using our own logging mechanism which includes additional details.
