### ISSUE TITLE
IntentDialog doesn't match messages longer than 40 characters

### ISSUE THREAD

**Issue by selenir** [Microsoft/BotBuilder#1874]
I use `botbuilder` version `3.4.4` for node.js. Intents are not matched correctly when message is longer than 40 characters.

```
var builder = require('botbuilder');
var intents = new builder.IntentDialog();
intents.matches(/^echo/i, function (session) {
  session.send(session.message.text);
})
intents.onDefault(function (session) {
  session.send('Hello, %s!', session.message.user.name);  
});
```
Every message starting with `echo` will be matched until it has more than 40 characters, then the default intent will be selected.
Node.js `v6.9.1`
NPM `v3.10.8`

**Comment by carlosscastro** [comment]
Hi @selenir, thanks for reporting this. It is a bug on our side and we'll be working on it.

**Comment by Stevenic** [comment]
This should have been fixed in a recent release. Please let us know if it still reproduces.
