### ISSUE TITLE
Performance remarks

### ISSUE THREAD

**Issue by brunoklein99** [Microsoft/BotBuilder#1875]
I've looked through the documentation for .NET and I've found nothing talking about performance. I was wondering what kind of docs are there regarding something like Do's and Dont's in the context of performance using the BotBuilder Framework.

**Comment by msft-shahins** [comment]
@brunoklein99 thanks for your feedback. Currently we don't have any performance analysis of the bot builder SDK. I will add this to our backlog items. Also let us know if you are hitting any specific performance bottleneck and we will investigate that.

**Comment by msft-shahins** [comment]
Closing this since it is tracked as a work item in our internal tool.
