### ISSUE TITLE
Get a list of anyone who has ever talked to my bot, or has added it? (Node.js)

### ISSUE THREAD

**Issue by laptopdude90** [Microsoft/BotBuilder#1876]
I'm trying to get an array of addresses, consisting of everyone the bot has ever talked to. There are 2 things I need to accomplish: the ability to get a full address from an address.id, and the ability to generate a full contact list.

Is this possible? If not, I can create an array on the fly as message come in, and put it in a file that updates.

**Comment by msft-shahins** [comment]
@laptopdude90 your bot needs to keep track of users that it is having a conversation with to achieve this. You can use a data storage of your choice, e.g. a simple persistent hash table, to track unique users that the bot have interacted with.
