### ISSUE TITLE
Abilty to Get Notification for any incoming outgoing message

### ISSUE THREAD

**Issue by AmirSasson** [Microsoft/BotBuilder#1877]
i want to be able to log any incoming/outgoing message.
being able today to register to IOC container as IActivityLogger is fine, but i need a fine way to understand if it is incoming or outgoing message.
i do it today by checking who is the recipient and check if it is my bot, it doesnt fell right to me.
i prefer to get notification if it is incoming/outgoing from the framework.
i saw that for Skype call there are Event that are fired like: Incoming/OutgoingCall.
can you add such a feature to messages as well?

**Comment by msft-shahins** [comment]
Thanks for your feedback. Another way to work around this is wrapping the IPostToBot from container with your own implementation of IPostToBot and log the incoming messages in that independent of outgoing message path. I added this to our backlog as a work item.

**Comment by msft-shahins** [comment]
Closing this since it is tracked as a work item in our internal tool.
