### ISSUE TITLE
FB get user location with nodeJs

### ISSUE THREAD

**Issue by clari182** [Microsoft/BotBuilder#1878]
Hi all! I have a question regarding how to handle when a user sends a location. I'm working with NodeJS

I used to do the following and it worked perfectly:

```
if (session.message.entities.length > 0) {
    var type = session.message.entities[0].type;
    if (type.toLowerCase() == "place") {
        session.userData.location = session.message.entities[0].geo;
        doSomethingWithUserLocation();
    }
}
```

A few days ago it stopped working and when I debugged it I saw that the entities were empty and nothing in attachments either. So I was wondering if Facebook changed something? I have the same bot in Telegram and it still works.

Does someone have any idea about this? It's so strange!

Thanks!!

**Comment by gviddy** [comment]
Yes I have come across the same problem. Latitude and Longitude are no longer showing up in the Entity.

**Comment by dandriscoll** [comment]
Hi @gviddy and @clari182, this appears to be a Facebook problem. We stopped receiving lat/lon data but confirmed this morning that it's back.

**Comment by dandriscoll** [comment]
Can you see if it's working for you?

**Comment by gviddy** [comment]
@dandriscoll 
I just tried now on both the Messenger app on my phone and in the desktop browser. I am still getting an empty Entity list when the user clicks on Location. Hence no location information.

Also I have no idea if Skyscanner uses your framework or not but they also try to use facebook messenger location and when conversing with their bot it does nothing too.

**Comment by clari182** [comment]
@dandriscoll Just tried it and still not working :(

**Comment by clari182** [comment]
@gviddy I think it's working fine again 👍 
I just tried several times with my bot and it was receiving it well. I hope it works fine for you too!

@dandriscoll Thank you for your help!!

**Comment by dandriscoll** [comment]
Closing as it appears this issue is resolved. We received reports that this was affecting non-Bot Framework bots running on Facebook so we're going to treat this as an FB issue.

**Comment by Yudner** [comment]
Nor can I get the longitude and latitude. Someone knows another way to get that data. Thank

**Comment by Yudner** [comment]
@gviddy Hi. Can you share your class where you choose latitude / longitude in Bot Framework. Please

**Comment by jayforu** [comment]
@gviddy We too are running with same problem, we need location from Facebook's messenger but at bot's end we are getting nothing. Would you please help with code snippet for this?

**Comment by jayforu** [comment]
@Yudner and @clari182 If you have hit the target , please help me as well here. Your help would be highly appreciated

**Comment by jayforu** [comment]
@dandriscoll  Hi, Is this issue going to be closed or will be reopened? We were not able to discover stand methods to accept location from FB messenger at Bot's (Microsoft) end. If you know a way, it would be helpful.

**Comment by Yudner** [comment]
@dandriscoll  I only have one code in c #

**Comment by Yudner** [comment]
@dandriscoll here you have the class: https://github.com/Yudner/Bot-Framework-Code/blob/master/LocationFacebookControl/FacebookLocationControlDialog.cs 
you just call him in a context.Call().

**Comment by jayforu** [comment]
Thanks for your reply @Yudner
