### ISSUE TITLE
Is there any standard guideline for how much throughput Messaging endpoint support?

### ISSUE THREAD

**Issue by jagdish-176** [Microsoft/BotBuilder#1881]
I'm testing my "Messaging endpoint".
As all request are coming from "Microsoft Servers"  I want to know how much load it should support?

**Comment by dandriscoll** [comment]
Hi @jagdish-176, most calls to your bot are triggered by user activity, so the amount of load on the bot is determined by 1) the number of users interacting with your bot, and 2) the volume of requests each user sends.

Bots vary in complexity, so some bots will have an easy time handling substantial load (even on a small number of service instances) while other, more complex bots may suffer performance problems even when encountering only a few users.

The Bot Framework protocol and libraries do not have any inherent load issues that we know of, so your bot's load and scale characteristics depend almost entirely on the application-specific code inside your bot.

**Comment by dandriscoll** [comment]
Please at-mention or file a new issue if you'd like to discuss further.
