### ISSUE TITLE
triggerAction method is undefined in botbuilder 3.4.4 (npm)

### ISSUE THREAD

**Issue by sebsylvester** [Microsoft/BotBuilder#1882]
The updated examples for Node.js show the usage of the ```triggerAction```  method invoked on the ```SimpleDialog``` instance returned by ```bot.dialog```. However, after running the code, I found that this method is undefined and throws a ```TypeError: bot.dialog(...).triggerAction is not a function```. 
Is this a change in the framework that hasn't been published to npm yet?

**Comment by clari182** [comment]
Hey! I'm using it but with version 3.5.0-rc8 of botbuilder. I think you should try updating the botbuilder version in order to get it.

**Comment by msft-shahins** [comment]
triggerAction is available in RC versions of 3.5. It will be available in the official package when 3.5 is released. If you want to access the new functionality reference the RC.

**Comment by iam-peekay** [comment]
thanks for this. perhaps we should add this to the docs or readme?
