### ISSUE TITLE
Configuring the Email Connector to Bot Framework

### ISSUE THREAD

**Issue by sameerinfodb** [Microsoft/BotBuilder#1883]
Hi Team,

Note able to use the Live Email id for configuring Email channel to the bot , Always getting 
"Unable to Validate the given credentials". But i'm able to login to office 365 using the  same live Email id.

Can anybody from bot framework team help in configuring the Email connector. please.

Regards,
Sameer Ahmed.S

**Comment by sameerinfodb** [comment]
Got to know that we have to use only Office 365 Business account email id for configuring the Email channel. If we use Office 365 home it does not work.

**Comment by suryadeepchatterjee3107** [comment]
Even if I use a business account I am getting an error(Unable to save. Unable to validate the given credentials. ID: |sHlvp.43e270fd_).
Maybe, some issue with RPC over HTTP.

**Comment by pawankorotane** [comment]
I am facing the same problem I am using my business email and I am able to login to Office 365 with my email even though I am getting a validation error
