### ISSUE TITLE
Sending Hero card to Kik raises message":"[] is too short

### ISSUE THREAD

**Issue by mcsee** [Microsoft/BotBuilder#1884]
Sample code working on Telegram, Facebook, slack and webchat but not on Kik

{"type":"message","text":"hola","from":{"id":"regressionbot","name":"RegressionFB"},"recipient":{"id":"conversalab","name":"conversalab"},"attachments":[{"contentType":"application\/vnd.microsoft.card.hero","content":{"title":"BK Combos Hamburguesas","subtitle":"Extra Burger, Napolitano, Big King, Stacker\u00ae Doble, Triple, Cuadruple, Quintuple","images":[{"url":"http:\/\/static.conversalab.com\/bots\/BKcomboHamburguesa.jpg"}],"buttons":[{"title":"Pedir","type":"postBack","value":"BK Combos Hamburguesas"}]}},{"contentType":"application\/vnd.microsoft.card.hero","content":{"title":"BK Combos WHOPPER\u00ae","subtitle":"WHOPPER\u00ae Extreme, WHOPPER\u00ae Doble, WHOPPER\u00ae","images":[{"url":"http:\/\/static.conversalab.com\/bots\/BKcomboWhooper.jpg"}],"buttons":[{"title
 ":"Pedir","type":"postBack","value":"BK Combos WHOPPER\u00ae"}]}},{"contentType":"application\/vnd.microsoft.card.hero","content":{"title":"BK Combos Especiales","subtitle":"Doble Steak\u2122, churrasquito pampeano, churrasquito tradicional, Doble Patag\u00f3nico, Churrasquito Patag\u00f3nico","images":[{"url":"http:\/\/static.conversalab.com\/bots\/BKcomboEspeciales.jpg"}],"buttons":[{"title":"Pedir","type":"postBack","value":"BK Combos Especiales"}]}},{"contentType":"application\/vnd.microsoft.card.hero","content":{"title":"BK Combos Pollo","subtitle":"King de Pollo\u00ae Patag\u00f3nico, TenderGrill\u2122, King de Pollo\u00ae Franc\u00e9s, King de Pollo\u00ae, Chicken Big King, BK Nuggets\u2122","images":[{"url":"http:\/\/static.conversalab.com\/bots\/BKcomboPollo.jpg"}],"buttons":[{"title":"Pedir","type":"postBack","value":"BK Combos Pollo"}]}},{"contentType":"application\/vnd.microsoft.card.hero","content":{"title":"Cajitas m\u00e1gicas","subtitle":"Cajita m\u00e1gica con BK Nu
 ggets\u2122, con s\u00e1ndwich de jam\u00f3n y queso, con hamburguesa, con hamburguesa con queso","images":[{"url":"http:\/\/static.conversalab.com\/bots\/BKcajitaMagica.jpg"}],"buttons":[{"title":"Pedir","type":"postBack","value":"Cajitas m\u00e1gicas"}]}}],"attachmentLayout":"carousel"}

**Comment by slidenerd** [comment]
@mcsee  format that input json file, use jsonstack.viewer.hu or some json beautifier, no one wants to read that kinda unformatted json

**Comment by mcsee** [comment]
Sure ! There you go @slidenerd 

{
	"type": "message",
	"text": "hola",
	"from": {
		"id": "regressionbot",
		"name": "RegressionFB"
	},
	"recipient": {
		"id": "conversalab",
		"name": "conversalab"
	},
	"attachments": [
		{
			"contentType": "application/vnd.microsoft.card.hero",
			"content": {
				"title": "BK Combos Hamburguesas",
				"subtitle": "Extra Burger, Napolitano, Big King, Stacker® Doble, Triple, Cuadruple, Quintuple",
				"images": [
					{
						"url": "http://static.conversalab.com/bots/BKcomboHamburguesa.jpg"
					}
				],
				"buttons": [
					{
						"title": "Pedir",
						"type": "postBack",
						"value": "BK Combos Hamburguesas"
					}
				]
			}
		},
		{
			"contentType": "application/vnd.microsoft.card.hero",
			"content": {
				"title": "BK Combos WHOPPER®",
				"subtitle": "WHOPPER® Extreme, WHOPPER® Doble, WHOPPER®",
				"images": [
					{
						"url": "http://static.conversalab.com/bots/BKcomboWhooper.jpg"
					}
				],
				"buttons": [
					{
						"title": "Pedir",
						"type": "postBack",
						"value": "BK Combos WHOPPER®"
					}
				]
			}
		},
		{
			"contentType": "application/vnd.microsoft.card.hero",
			"content": {
				"title": "BK Combos Especiales",
				"subtitle": "Doble Steak™, churrasquito pampeano, churrasquito tradicional, Doble Patagónico, Churrasquito Patagónico",
				"images": [
					{
						"url": "http://static.conversalab.com/bots/BKcomboEspeciales.jpg"
					}
				],
				"buttons": [
					{
						"title": "Pedir",
						"type": "postBack",
						"value": "BK Combos Especiales"
					}
				]
			}
		},
		{
			"contentType": "application/vnd.microsoft.card.hero",
			"content": {
				"title": "BK Combos Pollo",
				"subtitle": "King de Pollo® Patagónico, TenderGrill™, King de Pollo® Francés, King de Pollo®, Chicken Big King, BK Nuggets™",
				"images": [
					{
						"url": "http://static.conversalab.com/bots/BKcomboPollo.jpg"
					}
				],
				"buttons": [
					{
						"title": "Pedir",
						"type": "postBack",
						"value": "BK Combos Pollo"
					}
				]
			}
		},
		{
			"contentType": "application/vnd.microsoft.card.hero",
			"content": {
				"title": "Cajitas mágicas",
				"subtitle": "Cajita mágica con BK Nuggets™, con sándwich de jamón y queso, con hamburguesa, con hamburguesa con queso",
				"images": [
					{
						"url": "http://static.conversalab.com/bots/BKcajitaMagica.jpg"
					}
				],
				"buttons": [
					{
						"title": "Pedir",
						"type": "postBack",
						"value": "Cajitas mágicas"
					}
				]
			}
		}
	],
	"attachmentLayout": "carousel"
}

**Comment by mcsee** [comment]
Editor destroys tabs

Online version : http://codebeautify.org/jsonviewer/cb56411c

**Comment by LarsLiden** [comment]
Replicated.  Investigating.

**Comment by LarsLiden** [comment]
Issue has been resolved, fix will be included in next publish. Thank you for finding this bug!

**Comment by Tom123Sawyer** [comment]
Hi,

I was trying using a hero card in single and carausel formats and I am facing  issues with Kik and Telegram channels. The card doesn't work , doesn't gets displayed.
I am using the same JSON as given above just with a little modification;  I have removed the from and recipient objects as I want to make the responses general to all users using my bot.


Here is my JSON:
[
            {
                "contentType": "application/vnd.microsoft.card.hero",
                "content": {
                    "title": "Muy Macho Taqueria • 4★",
                    "subtitle": "8515 14th Ave S\nSouth Park\nSeattle, WA 98108\n",
                    "images": [
                        {
                            "url": "https://s3-media3.fl.yelpcdn.com/bphoto/0cdMS-AxxHv-sokWA6xFBw/ms.jpg",
                            "tap": {
                                "type": "openUrl",
                                "value": "http://www.yelp.com/biz/muy-macho-taqueria-seattle?utm_campaign=yelp_api&utm_medium=api_v2_search&utm_source=siC8kc5ssN3MtSBk9xFJ3g"
                            }
                        }
                    ],
                    "buttons": [
                        {
                            "type": "openUrl",
                            "value": "http://maps.google.com/?q=47.5268135070801,-122.31517791748",
                            "title": "0.7 mi from KBFI"
                        },
                        {
                            "type": "openUrl",
                            "value": "http://www.yelp.com/biz/muy-macho-taqueria-seattle?utm_campaign=yelp_api&utm_medium=api_v2_search&utm_source=siC8kc5ssN3MtSBk9xFJ3g",
                            "title": "View Yelp Page"
                        },
                        {
                            "type": "openUrl",
                            "value": "tel:+12067633484",
                            "title": "Call Restaurant"
                        }
                    ]
                }
            }
        ]

Please provide help if there's anything wrong here.

**Comment by Tom123Sawyer** [comment]
Also here is my entire response object using this attachment in Kik:

   responseObj.data.kik = {
        "type": "message",
        "text": "hola",
        "attachments": [
            {
                "contentType": "application/vnd.microsoft.card.hero",
                "content": {
                    "title": "Muy Macho Taqueria • 4★",
                    "subtitle": "8515 14th Ave S\nSouth Park\nSeattle, WA 98108\n",
                    "images": [
                        {
                            "url": "https://s3-media3.fl.yelpcdn.com/bphoto/0cdMS-AxxHv-sokWA6xFBw/ms.jpg",
                            "tap": {
                                "type": "openUrl",
                                "value": "http://www.yelp.com/biz/muy-macho-taqueria-seattle?utm_campaign=yelp_api&utm_medium=api_v2_search&utm_source=siC8kc5ssN3MtSBk9xFJ3g"
                            }
                        }
                    ],
                    "buttons": [
                        {
                            "type": "openUrl",
                            "value": "http://maps.google.com/?q=47.5268135070801,-122.31517791748",
                            "title": "0.7 mi from KBFI"
                        },
                        {
                            "type": "openUrl",
                            "value": "http://www.yelp.com/biz/muy-macho-taqueria-seattle?utm_campaign=yelp_api&utm_medium=api_v2_search&utm_source=siC8kc5ssN3MtSBk9xFJ3g",
                            "title": "View Yelp Page"
                        },
                        {
                            "type": "openUrl",
                            "value": "tel:+12067633484",
                            "title": "Call Restaurant"
                        }
                    ]
                }
            }
        ]
    }

**Comment by upendra1588** [comment]
hi ,

I am implementing ChatBot and my requirement is send .Docx,.doc and pdf to user, but I am not able to return these files. can you please help me to get these files?

Thanks in advanced.
