### ISSUE TITLE
NodeJS Calling SDK should allow for clock skew when verifying auth token

### ISSUE THREAD

**Issue by ctstone** [Microsoft/BotBuilder#1885]
BotBuilder version is 3.0.1 for Node

Today I started seeing my call connector return HTTP 403 responses to Skype. I tracked the responses to `CallConnector.prototype.verifyBotFramework` which is checking the auth token NBF field against current time with no clock skew. NBF is checked in at least 2 places: once explicitly in code and another via a call to `jsonwebtoken.verify` (to my eyes, the first check is redundant) 

The jsonwebtoken library supports clock skew as an option, so it would be great to see this exposed as an option on `CallConnector`. Or simply choose a reasonable default skew allowance, per the spec:

> The nbf (not before) claim identifies the time before which the token MUST NOT be accepted for processing. The processing of the nbf claim requires that the current date/time MUST be after or equal to the not-before date/time listed in the nbf claim. **Implementers MAY provide for some small leeway, usually no more than a few minutes, to account for clock skew**.

**Comment by dandriscoll** [comment]
Agree, this should be relying on the clock skew option in jsonwebtoken.

**Comment by ctstone** [comment]
See new PR at #2502 for a more complete fix
