### ISSUE TITLE
Error Loading Data when trying to do a performance analysis with Luis.ai

### ISSUE THREAD

**Issue by maxolidean** [Microsoft/BotBuilder#1886]
Hi. I think this issue started a couple of days a go. My app id is d11468ce-7486-4150-aa1a-5558be92428f

<img width="230" alt="screen shot 2016-12-19 at 8 23 27 pm" src="https://cloud.githubusercontent.com/assets/1413756/21332763/81100bea-c629-11e6-968d-2d1fcc152632.png">

**Comment by willportnoy** [comment]
@maxolidean do you still see this issue?  I can ask the LUIS team to take another look.

**Comment by maxolidean** [comment]
It seems to be working now. Thanks.
