### ISSUE TITLE
Request for documentation | DefaultIfException

### ISSUE THREAD

**Issue by JPThorne** [Microsoft/BotBuilder#1889]
Hi there, re my SO question: http://stackoverflow.com/questions/41218861/c-sharp-ms-botbuilder-usage-of-defaultifexception 

Please could we get some documentation on how to use DefaultIfException to prevent the "sorry my bot code is having an issue" message being passed back to the user on every exception in a dialog. 

Some way of overriding the message would be great, or sample code on how to use the above extension method.

**Comment by willportnoy** [comment]
I posted an answer there: http://stackoverflow.com/a/41249263/6520103

**Comment by msft-shahins** [comment]
Generally exceptions are propagated through dialog stack and each dialog on the stack has the opportunity to catch the exceptions thrown by the child dialog in their ResumeAfter delegate. If exceptions are not handled by the dialog stack, you can register your own IPostToBot with the container wrapping the default IPostToBot implementation and send different messages to user for different type of the exceptions. Here is how SDK registers the default PostUnhandledExceptionToUserTask which is the default exception handler with the conversation container: 
https://github.com/Microsoft/BotBuilder/blob/1958a3f946c2e8a540196b7d12fd15255932ce7c/CSharp/Library/Dialogs/DialogModule.cs#L190

An alternative is the what is suggested in https://github.com/Microsoft/BotBuilder/issues/1136#issuecomment-244414222
