### ISSUE TITLE
Microsoft.Bot.Connector.DirectLine.Models -> Message.FromProperty sets From Id, not From Name

### ISSUE THREAD

**Issue by JPThorne** [Microsoft/BotBuilder#1890]
Hi there. We're using the directline nugetpackage/SDK in our project to directly interact with our bot. 

As the title suggests, setting the FromProperty on a Message results in a call to the DirectLine Api with only the id on the From set to the FromProperty value. There does not seem to be a way to set the From Name as well. 

For example: 

Calling the following, with the from param set to "IntegrationTestUser175"

```
public void SendMessage(string conversationId, string from, string messageText)
		{
			using (var client = new DirectLineClient("ourdirectlinekey"))
			{
				var userMessage = new DlMessage
				{
					FromProperty = from,
					Text = messageText
				};

				client.Conversations.PostMessage(conversationId, userMessage);
			}
		}
```

We get this message:
```
"From": {
      "id": "IntegrationTestUser175",
      "name": null
    }
```

Is there a way to set the Name as well? For example, in the emulator, we get: 

```
"from": {
    "id": "2c1c7fa3",
    "name": "User1"
  }
```

**Comment by dandriscoll** [comment]
Hi @JPThorne, Direct Line 3.0 supports setting all properties on the From field. The 3.0 protocol is in Preview and the client is in Beta, you can update the Nuget package by clicking the "Show pre-release" option in the Nuget client and then updating to 3.0.0-beta.

**Comment by JPThorne** [comment]
Thank you!

**Comment by BKbhavu** [comment]
I am not able to use FromProperty....how can i include that?

**Comment by dandriscoll** [comment]
Hi @BKbhavu, please open a new issue and include more details like the language you're using and the version of any Direct Line helper clients you're using.
