### ISSUE TITLE
Issue in updating Bot Builder with NuGet Package

### ISSUE THREAD

**Issue by arafattehsin** [Microsoft/BotBuilder#1891]
Dears

When I am trying to upgrade the Bot Builder on my current project. I'm getting this error below;

Unable to resolve dependencies. 'System.IdentityModel.Tokens.Jwt 5.1.0' is not compatible with 'Microsoft.Azure.AppService.ApiApps.Service 0.9.64 constraint: System.IdentityModel.Tokens.Jwt (>= 4.0.0)', 
'Microsoft.Bot.Builder 3.4.0 constraint: System.IdentityModel.Tokens.Jwt (>= 4.0.2.206221351 && < 5.0.0)', 'Microsoft.IdentityModel.Protocol.Extensions 1.0.3.308261200 constraint: System.IdentityModel.Tokens.Jwt (>= 
4.0.3.308261200)'

It worked when I had downgraded my System.IdentityModel.Tokens.Jwt library to less than 5.0.0 but it should have been worked. 

Please fix this dependency bug.

**Comment by msft-shahins** [comment]
This is not a dependency bug. System.IdentityModel.Tokens.Jwt has a breaking change in 5.0 version and bot builder currently implemented based on the 4.0 version. As a result we limit the version of nuget that builder is dependent on in the nuspec: https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Microsoft.Bot.Builder/Microsoft.Bot.Builder.nuspec#L30

**Comment by muebele** [comment]
This is causing an issue for us. Our project uses Twilio which depends on System.IdentityModel.Tokens.Jwt version >= 5.1.2

With this dependency conflict present, we're unable to use Bot Builder in our project. Is there an estimated timetable of when this dependency will be brought up to date?

**Comment by JasonSowers** [comment]
@muebele you are commenting on a closed issue, please open a new issue.

**Comment by muebele** [comment]
https://github.com/Microsoft/BotBuilder/issues/3298

**Comment by bhashithahemantha** [comment]
An error occurred while retrieving package metadata for 'Microsoft.Rest.ClientRuntime.2.3.2' from source 'C:\Users\Bashitha.Hemantha\documents\visual studio 2015\Projects\Bot_test2\packages'.
Since i'm new to this, can anyone explain this error for me. thank you..
