### ISSUE TITLE
Password filed in botbuilder

### ISSUE THREAD

**Issue by chetanmekha** [Microsoft/BotBuilder#1894]
Hello Team,
I want to user with their credentials, for that i ask user to enter username and password. Is there any way to hide password / accepted user password in **** / ooooo similar formats. Please help me out on the same.

**Comment by dandriscoll** [comment]
Hi @chetanmekha, there's no way to hide a password in chat. We discourage bot developers from requesting this information directly within the chat window.

One sample that shows how to log a user in is AuthBot: https://github.com/MicrosoftDX/AuthBot. Please take a look at the sample and ensure it meets your security requirements before using the code.

**Comment by abhishan** [comment]
@chetanmekha @dandriscoll We are using **Azure Multi Factor Authentication** to secure a channel and verify the user with known data (in this case mobile number from Active Directory). Its works best when the user is trying to chat with a bot on mobile devices, the authentication experience is quite seamless.
You can read more about it here: http://www.acuvate.com/solutions/bot/

**Comment by chetanmekha** [comment]
@dandriscoll thanks for the valuable guidance. Will implement the same.
