### ISSUE TITLE
How to generate new post to Bot from class which extends LuisDialog<object>?

### ISSUE THREAD

**Issue by virendrak** [Microsoft/BotBuilder#1895]
I have created one C# Bot Framework application. I'm displaying list of buttons in HeroCard based on LUIS intent. If user selects one button, that button text would be passed to other method (called **DiasplayTraining** as shown below) and displays respective information.

 
![image](https://cloud.githubusercontent.com/assets/10959600/21389758/47600d92-c7a9-11e6-9212-2ca78c7ea037.png)

> Please find below buttons which display in the HeroCard.

![image](https://cloud.githubusercontent.com/assets/10959600/21389810/862ca080-c7a9-11e6-9cc4-97460cd6bbc5.png)

> My DisplayTraining async method is as below,

![image](https://cloud.githubusercontent.com/assets/10959600/21389994/7daf7364-c7aa-11e6-928e-5b3085c34f4c.png)

If user entered/posted any text instead of selecting any button from above HeroCard, code goes to above highlighted else case, from this else block I should pass the text as new post to the bot. My else block statement **await context.PostAsync(title)** displays the text to me in the bot but not posting as new post.

Please help me how can I Post user entered text from above else block as new post to the Bot.

Thanks in Advance!
V

**Comment by willportnoy** [comment]
Are you asking how to disable threading for the message posted in the else block?  You can call MakeMessage to construct an IMessageActivity and clear out the reply ID field before sending the message with PostAsync.

**Comment by virendrak** [comment]
@willportnoy ,
No, we are not looking to disable posting a message from else block, we are looking to post as new post which should be identified by our LUIDDialog. Currently value inside title is getting displayed but we want this value should be catch by intents in the LUISDialog.

**Comment by willportnoy** [comment]
@virendrak you want to construct a new IMessageActivity (as if it came from the user to the bot) to be re-dispatched using the MessageReceived logic in LuisDialog?

**Comment by virendrak** [comment]
We are constructing IMessageActivity in <ELSE> block (as highlighted in question) as below.

```
IMessageActivity newPost = context.MakeMessage();
newPost.Text = title;
await context.PostAsync(newPost);
context.Wait(this.MessageReceived); 
```

But, it's not calling any intent in LUIS dialog. Just simply displaying the text.

**Comment by msft-shahins** [comment]
this should let you re-dispatch the activity on the same LuisDialog: 

```csharp
await MessageReceived(context, Awaitable.FromItem(context.Activity.AsMessageActivity()));
```

**Comment by RasheedSiriyala** [comment]
as we see message definition in above question, context is IDialogContext type parameter, when i'm adding above your line of code it showing me following error,
**'IDialogContext' does not contain a definition for 'Activity' and no extension method 'Activity' accepting a first argument of type 'IDialogContext' could be found (are you missing a using directive or an assembly reference?**
I couldn't find any assembly reference to resolve this.

**Comment by willportnoy** [comment]
Have you updated to the latest bot builder nuget?

**Comment by RasheedSiriyala** [comment]
Thank you @willportnoy its working after updating bot builder nugget, 
Thank you @msft-shahins your line helped us.

**Comment by virendrak** [comment]
@willportnoy, @msft-shahins Thank you so much for your help!!!
