### ISSUE TITLE
Bot disabled error

### ISSUE THREAD

**Issue by tahsintahsin** [Microsoft/BotBuilder#1896]
Hello, 
I receive this when my registered bot tries to connect to directline api v3.
({
  "error": {
    "code": "ServiceError",
    "message": "Site missing or disabled"
  }
}) 
This happens with one bot only, the other 2 seems fine. Affected bot id is: 59fcba99-2720-469f-9758-d83fb6a76096
What might be causing this? I use the exact same code in another bot and it is working fine. The problem seems specific to that id. 
Thanks

**Comment by dandriscoll** [comment]
Hi @tahsintahsin, I took a quick look and it looks like you're using the 3.0 API but support for 3.0 hasn't been enabled for your bot. I'll clean up the error message to indicate that. You can enable support for the new protocol by visiting the Direct Line configuration page where you got your keys, and clicking the checkbox marked "3.0."

**Comment by tahsintahsin** [comment]
@dandriscoll Thanks a lot for fast reply. 
I looked at it actually and saw "Bot Framework Version
3.0" on my bot registry page, but I didn't consider framework version and directline version are two separate things. Noting it here in case someone has the same misunderstanding.
Thanks again !
