### ISSUE TITLE
Filtering/Logging bot messages

### ISSUE THREAD

**Issue by davidbabicka** [Microsoft/BotBuilder#19]
Sorry if this was already available but couldn't find yet. How can I filter or log the bot messages (node.js) ? Is there a sample project?

**Comment by Stevenic** [comment]
You can use a piece of middleware to do that. I'll add a logging sample for you. It will currently only log incoming messages but I'm planning changes to middleware that will allow both incoming and outgoing hooks

**Comment by Stevenic** [comment]
I added a new logging example you can checkout. It also shows how to intercept user sent /commands to turn features on & off.

**Comment by berhir** [comment]
@Stevenic Is there also a sample for how to log all outgoing messages in c#?

**Comment by Stevenic** [comment]
+shahin

**Comment by jcmontes95** [comment]
@msft-shahins @Stevenic any updates on c# logging?

**Comment by msft-shahins** [comment]
@jcmontes95 you can implement an [IActivityLogger](https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Dialogs/IActivityLogger.cs) and register it with the conversation container. By default builder registers the (NullActivityLogger)[https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Dialogs/IActivityLogger.cs#L81] with the [container](https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Dialogs/DialogModule.cs#L235) which is a no-op. 

Here is a sample implementation of IActivityLogger using Azure table storage: https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Microsoft.Bot.Builder.Azure/TableLogger.cs#L60.

**Comment by jcmontes95** [comment]
@msft-shahins thank you!
