### ISSUE TITLE
Skype Bot beta acces

### ISSUE THREAD

**Issue by JpEncausse** [Microsoft/BotBuilder#190]
Hi,

Sorry if my question is not directly related to the API.

I'd like to connect my bot to Skype Bot, I signup a week ago (with my email Jp [at] encausse [dot] net), it seems i'm registered but I still don't have access and get redirected to signup page.

Is there a mandatory to get access ? We have Microsoft Event (in France) in May and we'd like to show a demo of  MS Bot with Skype Bot.

**Comment by tomlm** [comment]
Are you going to https://developer.microsoft.com/en-us/skype/bots ?

**Comment by JpEncausse** [comment]
I did an other test on an other computer and it works now !

OMG I understand, I think my work email has been used instead of the other and logme in without access.

Sorry I'm so n00b ^^
