### ISSUE TITLE
Botbuilder.ChatConnector  read property of undefined

### ISSUE THREAD

**Issue by yevsher** [Microsoft/BotBuilder#1902]
Hello,
I'm new to botbuilder framework and tried to create a simple bot using your examples, but when I start the bot using node app.js in windows 7 I receive the error Cannot read property 'ChatConnector' of undefined.
I tried to read articles and blogs but unfortunately did not find a solution. Could you tell me is this the error or my mistake and how to fix it. Here is the code for the bot:
var restify = require('restify');
try {
    var builder = require('botbuilder');
} catch (err) {
    console.log(err.message);
}
//Bot Setup

//Setup restify server
var server = restify.createServer();
server.listen(process.env.port || process.env.PORT || 3978, function() {
    console.log('%s listening to %s', server.name, server.url);
});

//create chat bot
var connector = new builder.ChatConnector({
    appId: '',
    appPassword: ''
});
var bot = new builder.UniversalBot(connector);
server.post('/api/messages/', connector.listen());

//Bots dialogs
var intents = new builder.IntentDialog();
bot.dialog('/', intents);

intents.matches(/^change name/i, [
    function (session) {
        session.beginDialog('/profile');
    },
    function (session, results) {
        session.send('Your name was changed to: %s', session.userData.name);
    }
]);

intents.onDefault([
    function (session, args, next) {
        if (!session.userData.name) {
            session.beginDialog('/profile');
        } else {
            next();
        }
    },
    function (session, results) {
        session.send('Hello %s!', session.userData.name);
    }
]);

bot.dialog('/profile', [
    function (session) {
        builder.Prompts.text(session, 'Hi! What is your name?');
    },
    function (session, results) {
        session.userData.name = results.response;
        builder.Prompts.text(session, 'What is your age?');
    },
    function (session, results) {
        session.userData.age = results.response;
        session.send('Thank you %s %s', session.userData.name,  session.userData.age);
        session.endDialog();
    }
]);

**Comment by yevsher** [comment]
The thing is that everything worked fine but I left the code for a week and the error appeared. Here is the command prompt window

![command_line](https://cloud.githubusercontent.com/assets/8384403/21461930/22bc04c0-c95f-11e6-8f00-356b58e91741.png)

**Comment by dandriscoll** [comment]
Hi @yevsher, is the botbuilder module being loaded? The error indicates that the call to require('botbuilder') is failing.

**Comment by yevsher** [comment]
Hi dendriscoll, you are right the error appears when node tries to load botbuilder module. In addition I'd like to add that the restify module loading was successfull. Do you have any clues about what can I do to solve this problem?

**Comment by carlosscastro** [comment]
Hello @yevsher!

I'm not sure off hand what is going on, but it seems like an environmental problem. To make sure, I tried your code and worked perfectly for me. Let me share the steps I did, and feel free to try them to fix your issue (This is for Windows - let me know if you're using another operating system):

1. Create a new directory named 'sample'
2. In the sample directory, create an empty file called 'app.js'
3. Paste your code above into app.js
4. Open a command prompt, and navigate to the sample folder
5. Run `npm install restify`
6. Run `npm install botbuilder`
7. Run 'node app.js' which should make your bot start listening
8. Test your bot :)

Let me know if these steps work for you. Thanks!

**Comment by yevsher** [comment]
Thank you carlosscastro for the help your proposition helped and this is the end of this question) but I still do not understand what heppened and why the botbuilder module did not load. Now I now what to do if this will heppen again.)

**Comment by carlosscastro** [comment]
Glad to hear it worked!

Not sure about why it happened originally. To gather more info, you could go to the folder where you're getting the error and run steps 4 to 8 in that folder. If that fixes it, it just means that you were actually missing the node modules in that folder.

Not sure if you already do, but if using [VS code ](https://code.visualstudio.com/) you can first open your directory and then, in the VS Code integrated terminal, run

`npm install --save botbuilder`
`npm install --save restify`

That way you track your dependencies and versions in a packages.json file. After that, running `npm install` in the folder should install / update all the dependencies.

**Comment by carlosscastro** [comment]
@yevsher I'm closing the issue now, but feel free to re-open if you have any follow ups :)
