### ISSUE TITLE
[LUIS] How to handle response dialog in LUIS in Node js

### ISSUE THREAD

**Issue by piyush-dholariya** [Microsoft/BotBuilder#1903]
@Stevenic  hi steve I am implementing one food bot using LUIS, so I want to take input from user & give answer, if user enters incomplete info. then I want to reply him with another dialog which I am getting from LUIS json, but how can I get those response dialog  in my Nodejs code? I can not get those dialogs in botbuilder node's intent's function response, once I required info from user, then again how can I get it back user response in my code?

sample code & my sample json is here.

```javascript
require('dotenv-extended').load();

var builder = require('botbuilder');
var restify = require('restify');

// Setup Restify Server
var server = restify.createServer();
server.listen(process.env.port || process.env.PORT || 3978, function() {
    console.log('%s listening to %s', server.name, server.url);
});

// Create chat bot
var connector = new builder.ChatConnector({
    appId: 'wffffwf',
    appPassword: 'fsfsfsf'
});
var bot = new builder.UniversalBot(connector);
server.post('/api/messages', connector.listen());

// You can provide your own model by specifing the 'LUIS_MODEL_URL' environment variable
// This Url can be obtained by uploading or creating your model from the LUIS portal: https://www.luis.ai/
const LuisModelUrl = process.env.LUIS_MODEL_URL ||
    'https://api.projectoxford.ai/luis/v2.0/apps/424244242424?subscription-key=fsdffsfsfs&verbose=true';

// Main dialog with LUIS
var recognizer = new builder.LuisRecognizer(LuisModelUrl);
var intents = new builder.IntentDialog({ recognizers: [recognizer] })
    .matches('getOrder', [
        function(session, args, next) {
            session.send('Welcome to the Food Bot! we are analyzing your message: \'%s\'', session.message.text);

            var foodNameEntity = builder.EntityRecognizer.findEntity(args.entities, 'foodName');
            var quantityEntity = builder.EntityRecognizer.findEntity(args.entities, 'quantity');
            var sizeEntity = builder.EntityRecognizer.findEntity(args.entities, 'size');

            if (session.dialog) {
                builder.Prompts.text(session, session.dialog.prompt);
            } else if (foodNameEntity && quantityEntity && sizeEntity) {
                var order = {
                    foodName: foodNameEntity.entity,
                    size: sizeEntity.entity,
                    quantity: quantityEntity.entity
                };
                next({ response: order });
            } else {
                builder.Prompts.text(session, 'Please enter your order properly.');
                session.endDialog();
            }
        },
        function(session, results) {
            if (results.response) {
                // Call LUIS and resolve matched entities
                builder.LuisDialog.recognize(session.message.text, LuisModelUrl, function(err, intents, entities) {
                    console.log('intents', intents);
                    console.log('entities', entities);
                    var from = builder.EntityRecognizer.resolveTime(args.entities);
                    if (from) {
                        // User said a valid date.
                        session.endDialog({ response: from });
                    } else if (session.dialogData.maxRetries > 0) {
                        // Re-prompt
                        session.dialogData.maxRetries--;
                        builder.Prompts.text(session, "I'm sorry I didn't get that. What date you arriving?");
                    } else {
                        // Too many retries. We end the dialog with a reason of notCompleted.
                        session.endDialog({ resumed: builder.ResumeReason.notCompleted });
                    }
                });
            } else {
                // User said 'nevermind' or something
                session.endDialog(results);
            }
            // session.send('Please wait, Getting order for you');

            // var order = results.response;

            // var order = 'Your order is: <div>FoodName: ' + order.foodName + ', </div><div>Size: ' + order.size + ', </div><div>Quantity:' + +order.quantity + '</div>';

            // session.send(order);
        },
        function(session, results) {
            session.send('Please confirm order, is it correct (Yes/No)');

            session.send(order);
        }
    ])
    .matches('Help',
        builder.DialogAction.send('Hi! Try asking me things like \'i want 3 medium size pizza\', \'get 5 sandwichwith jumbo size .\' or \'please give me 7 big cold drinks\''))
    .onDefault((session) => {
        session.send('Sorry, I did not understand \'%s\'. Type \'help\' if you need assistance.', session.message.text);
    });

bot.dialog('/', intents);

```
`{
  "query": "get 5 with jumbo size ",
  "topScoringIntent": {
    "intent": "getOrder",
    "score": 0.9999304,
    "actions": [
      {
        "triggered": false,
        "name": "getOrder",
        "parameters": [
          {
            "name": "Food Name",
            "type": "foodName",
            "required": true,
            "value": null
          },
          {
            "name": "Size",
            "type": "size",
            "required": true,
            "value": null
          },
          {
            "name": "quantity",
            "type": "quantity",
            "required": true,
            "value": [
              {
                "entity": "5",
                "type": "quantity",
                "resolution": {}
              }
            ]
          }
        ]
      }
    ]
  },
  "intents": [
    {
      "intent": "getOrder",
      "score": 0.9999304,
      "actions": [
        {
          "triggered": false,
          "name": "getOrder",
          "parameters": [
            {
              "name": "Food Name",
              "type": "foodName",
              "required": true,
              "value": null
            },
            {
              "name": "Size",
              "type": "size",
              "required": true,
              "value": null
            },
            {
              "name": "quantity",
              "type": "quantity",
              "required": true,
              "value": [
                {
                  "entity": "5",
                  "type": "quantity",
                  "resolution": {}
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "intent": "None",
      "score": 0.07642237
    },
    {
      "intent": "Help",
      "score": 9.138411E-07
    }
  ],
  "entities": [
    {
      "entity": "5",
      "type": "quantity",
      "startIndex": 4,
      "endIndex": 4,
      "score": 0.7467653,
      "resolution": {}
    }
  ],
  "dialog": {
    "prompt": "which food do you want?",
    "parameterName": "Food Name",
    "parameterType": "foodName",
    "contextId": "ae5de259-6a9b-476c-bbb8-1be7fceba761",
    "status": "Question"
  }
}`

**Comment by maxpert** [comment]
Hey @piyush-dholariya seems like you are trying to do dialog prompts. Currently I am working on a change that is going to address your issue. You will be able to neatly tie down LUIS dialog with prompts in a cleaner way.

**Comment by tlloydukdev** [comment]
I'm having the same issue, any update on this or any ideas ?

Thanks

**Comment by Stevenic** [comment]
So we don't provide a super clean way of doing this but it can be done.  What you'd want to do is create a custom prompt for each of your fields. Each of those custom prompts would be bound to your LUIS model using an `IntentDialog`. You can look at the [basics-customPrompt](https://github.com/Microsoft/BotBuilder/blob/master/Node/examples/basics-customPrompt/meaningOfLife.js) for an example of creating a prompt based on an IntentDialog. You would just bind that prompts dialog to your LUIS model.

Then in your top level dialog you'll want to call the appropriate custom prompt in sequence for each missing field. That's going to let you use LUIS to recognize the users responses for each prompt. It also lets you tweak how each prompt is recognized at the cost of a bit more coding.

We'll be exploring ways of stream lining this moving forward.

**Comment by piyush-dholariya** [comment]
Still my question remains same.

**Comment by tlloydukdev** [comment]
yes, I'm still a bit confused too I must admit. Some example code would be awesome.

**Comment by nwhitmont** [comment]
@maxpert any update on this one?

**Comment by nansravn** [comment]
I'm also having the same problem... Could you guys provide any example code?

**Comment by stevengum97** [comment]
@tlloydukdev  @nansravn, just to clarify, what are the two of you looking for?

@piyush-dholariya: 

>*hi steve I am implementing one food bot using LUIS, so I want to take input from user & give answer, if user enters incomplete info. then I want to reply him with another dialog which I am getting from LUIS json, but how can I get those response dialog in my Nodejs code?*
> *I can not get those dialogs in botbuilder node's intent's function response, once I required info from user, then again how can I get it back user response in my code?*

So if the user gives an answer that doesn't properly answer the question, they should be directed to another dialog? The next time they're asked the question their utterance should go to LUIS for parsing?

**Comment by stevengum97** [comment]
@tlloydukdev, @nansravn, @piyush-dholariya:
I believe that what you're asking for was recently discussed in issue [2741](https://github.com/Microsoft/BotBuilder/issues/2741).

**Comment by Dhanashri04** [comment]
how to recognized composite entity in LUIS using node js? also how to check whether which choice is selected by user through prompt.choice method?

**Comment by nwhitmont** [comment]
@Dhanashri04 You are commenting on a closed issue. 

If you have a question or problem, please [open a new issue.](https://github.com/microsoft/botbuilder/issues/new)
