### ISSUE TITLE
Cleaning up code handling intentions in LuisDialog

### ISSUE THREAD

**Issue by piffarettig** [Microsoft/BotBuilder#1904]
I am using a LuisDialog to handle all posible intentions in my bot. Particularly one of them is kind of complex and is handling multiple different cases. Functionality works but code is a mess, so I want to clean the code and make it modularized, classes with single responsibilites (my current LuisDialog handle all intentions and handle all the logic for them),  same abstraction level, etc.

I'd like to achieve something like this:

```
        [LuisIntent(“MyIntent”)]
        public async Task MyIntent(IDialogContext context, LuisResult result)
        {
                MyIntentHandler handler = new MyIntentHandler();
                handler.HandleMyIntent(context, result);
        }
```

instead of the messy code I have right now:

```
[LuisIntent(“MyIntent”)]
public async Task MyIntent(IDialogContext context, LuisResult result)
{
    if (EntityOneWasSpecified())
    {
        // logic here
    }
    else
    {
        if(EntityTwoWasSpecified())
        {
            //logic here
        } else {
            if(SomeOtherCondition()) 
            {
                //logic here
            } else 
            {
                //logic here
            }
        }
    }
}

```

The thing is if I create the class **'MyIntentHandler'** to delegate the logic to it, I cant call **MessageReceived** because that class is not a Dialog. Should I need to call a child Dialog to achieve that? Would `context.Forward` do the trick? What kind of dialog should be? LuisDialog? IDialog<WhichTypeGoesHere> ? 

Or is it any better way of handling complex bot intent stuff?

Thanks

**Comment by willportnoy** [comment]
You might consider the DispatchDialog - it helps with unpacking entities and selecting the proper method overload to invoke.

**Comment by piffarettig** [comment]
@willportnoy maybe I wasn't clear enough. I want to clean the code not the Dialog in runtime. As I saw the DispatchDialog is helpful to dispatch an IScorable, and I think I am not using that.

Maybe what you say is that I should create a new dialog inside the intent handling of LuisDialog, and make a context.Forward to it? And that that dialog should inherit from DispatchDialog? 

Is that what you mean? If not, could you please provide an example?

Thanks in advance

**Comment by willportnoy** [comment]
I responded on https://github.com/Microsoft/BotBuilder/issues/1918 which I presume is the same issue - tell me if otherwise.

**Comment by piffarettig** [comment]
Will keep this open until I implement what I want to do (as this is secondary now). Then I will post the code as an example for future users. Thanks :)

**Comment by willportnoy** [comment]
@piffarettig if you want to use dynamic runtime logic to override some of the dispatch dialog logic, you might consider ContinueWithNextGroup:

https://github.com/Microsoft/BotBuilder/blob/develop/CSharp/Samples/SimpleDispatchDialog/SimpleDispatchDialog.cs#L32

I'm going to close this issue for now, but feel free to open a new issue for further discussion (or I can re-open this issue if something still has not been resolved).
