### ISSUE TITLE
Dialogs appear to be cached.

### ISSUE THREAD

**Issue by michaelsrichter** [Microsoft/BotBuilder#1905]
Hi, in the code below, I want to route the user to the correct dialog. If there's an image attached, go to the PicturesDialog, if they are start a config action, go to the config dialog, otherwise go the main dialog. 

The problem is that when I start a new conv in the Emulator, the first dialog that gets used is used for all further conversation messages. When I step through the code locally, I see that the logic works and it appears that Conversation.SendAsync is getting the correct dialog, but then the execution moves to the first dialog that was used in the conversation.

Please help! Thanks, Mike

                case ActivityTypes.Message:
                {
                    if (activity.Attachments != null && activity.Attachments.Count > 0)
                    {
                        await Conversation.SendAsync(activity, () => _picturesDialog);
                    }
                    else if (activity.Text.ToLowerInvariant().StartsWith("config "))
                    {
                        await Conversation.SendAsync(activity, () => _configurationDialog);
                    }
                    else
                    {
                        await Conversation.SendAsync(activity, () => _mainDialog);
                    }
                    break;
                }

**Comment by willportnoy** [comment]
You should only have a single call to Conversation.SendAsync in your application, with a single root dialog.  if you want to dispatch to different dialogs based on activity properties, I would do so in a new, separate root dialog.

**Comment by willportnoy** [comment]
I'm going to close this issue for now, but feel free to open a new issue for further discussion.
