### ISSUE TITLE
Add a Python BotBuilder for Python 3.6 that uses asyncio.

### ISSUE THREAD

**Issue by AraHaan** [Microsoft/BotBuilder#1906]
This SDK looks promising however it would be nice if there was a Python version for those who use 3.6 so that way they can have fun with asyncio as well.

Use Web requests and whatnot? There is aiohttp and the websockets library which of course discord.py also uses (discord.py is a wrapper for the discord API in python that uses all 3 of these things).

**Comment by Andrea-Orimoto** [comment]
Hi @AraHaan, we've added this to our backlog for future consideration. Thanks!

**Comment by AraHaan** [comment]
yw
