### ISSUE TITLE
How to get user name of facebook messenger ?

### ISSUE THREAD

**Issue by areckkimo** [Microsoft/BotBuilder#1908]
How to get user name of facebook messenger?
I use Node JS SDK
please help
thanks

**Comment by willportnoy** [comment]
https://github.com/Microsoft/BotBuilder/issues/1401 and https://github.com/Microsoft/BotBuilder/issues/291 seem to be related - does the "from name" property have what you want?

**Comment by areckkimo** [comment]
thanks @willportnoy , But I use nodejs, not c#

**Comment by willportnoy** [comment]
@areckkimo it should be a similar property in Node:
https://github.com/Microsoft/BotBuilder/blob/a7370bdd38b81c9414bb8c22b047f6b3f7a5c54c/Node/core/src/interfaces.d.ts#L60

**Comment by lyzs90** [comment]
@areckkimo not sure if that's the best way but you can use `session.message.user.name` in Node, assuming the user initiates the chat

**Comment by gilesbutler** [comment]
Shame that it gives their full name. I've seen other bot platforms just show the users first name. Anyway to get just the first name?

**Comment by clari182** [comment]
A workaround is to only keep the first word assuming it's the user's first name. That's how I do it but maybe there is a better way.

**Comment by gilesbutler** [comment]
Yeah that's what I was thinking @clari182 - I'm sure there will probably be edge cases where it's not right though

**Comment by Stevenic** [comment]
Closing this for age. Please comment if you'd like it re-opened.

**Comment by bmperrea** [comment]
It would be nice to support access to first names, and actually the whole facebook graph api. Managing page_access tokens ourselves seems to undermine the purpose of the connector.

**Comment by willportnoy** [comment]
@bmperrea you might consider a new top level issue for the feature request - feel free to reference this one.
