### ISSUE TITLE
[nodejs] Documentation for bot.beginDialog() states accepting a address but really wants IBotConnectorMessage

### ISSUE THREAD

**Issue by khrome83** [Microsoft/BotBuilder#191]
The documentation for `BotConnectorBot.on()` clearly states that it returns a `iBotConnectorMessage`. 

When attempting to call `bot.beingDialog()`, the expected action from documentation is to accept a address. 

The [beginDialog()](http://docs.botframework.com/sdkreference/nodejs/classes/_botbuilder_d_.botconnectorbot.html#begindialog) states that it accepts a [IBeginDialogAddress](http://docs.botframework.com/sdkreference/nodejs/interfaces/_botbuilder_d_.ibegindialogaddress.html) when it really accepts a [iBotConnectorMessage](http://docs.botframework.com/sdkreference/nodejs/interfaces/_botbuilder_d_.ibotconnectormessage.html) as shown [here](https://github.com/Microsoft/BotBuilder/blob/00857604aabae95feb017188ca9c55ee36770295/Node/lib/bots/BotConnectorBot.js#L97)

The [.on()](http://docs.botframework.com/sdkreference/nodejs/classes/_botbuilder_d_.botconnectorbot.html#on) method returns a [iBotConnectorMessage](http://docs.botframework.com/sdkreference/nodejs/interfaces/_botbuilder_d_.ibotconnectormessage.html) which a address can be found [inside](http://docs.botframework.com/sdkreference/nodejs/interfaces/_botbuilder_d_.ichannelaccount.html#address) of.

**Fails**
```javascript
bot.on('BotAddedToConversation', function(message) {
    // Docs state method is to accept address
    bot.beginDialog(message.from.address, '/profile');
    // Fails - [Error Invalid address passed to BotConnectorBot.beginDialog().]
});
```

**Works**
```javascript
bot.on('BotAddedToConversation', function(message) {
    // Docs state method is to accept address, passing in iBotConnectorMessage instead
    bot.beginDialog(message, '/profile');
    // Success
});
```

**Expected**
Object is consistent. Either always take a address or a message. Update docs to reflect the correct type.

**Comment by Stevenic** [comment]
I see the confusion... IBeginDialogAddress isn't the same as an IChannelAddress.  They're two separate things. In your example that fails you're passing an IChannelAddress.  You could argue that I chose a bad name for IBeginDialogAddress but it's supposed to be just a subset of the IMessage fields which is why passing a full message works. At the time I honestly couldn't think of anything better to call it.

**Comment by Stevenic** [comment]
Please re-open if this is still an issue for you.
