### ISSUE TITLE
Get user info inside LuisDialog

### ISSUE THREAD

**Issue by piffarettig** [Microsoft/BotBuilder#1910]
I want to get user info (for instance his/her Skype username), but i'm doing that inside a LuisDialog.

How can I access the parent activity inside an intent handler function?. I saw this answer https://github.com/Microsoft/BotBuilder/issues/1084#issuecomment-242543615 that @willportnoy did but passing` IAwaitable<IMessageActivity> activity` as a parameter to the intent handler throws me an exception where it message its just the name of the intent (it doesnt matter which text you pass to it, it just throws the exception always).

<img width="1030" alt="screen shot 2016-12-25 at 10 41 14" src="https://cloud.githubusercontent.com/assets/16963208/21471358/b83ec340-ca8e-11e6-8fae-4d4f5ec94304.png">

I ve thought of maybe using any of the IBotDataBag inside the context (PrivateConversationData,UserData,ConversationData), but I don't know which could be the key name of the property, so I am just guessing.

I also thought of passing the original Activity to the Dialog but I cant store it as a property because its non-serializable and that would crash my bot, and storing just the username isn't exactly what I need, I want to be able to use all user data not just one property.

Any workaround for this?

Thanks!

**Comment by willportnoy** [comment]
You can use the context.Activity property to access the original incoming activity.

**Comment by piffarettig** [comment]
That property doesn't appear on my context, on which version was that introduced?

**Comment by piffarettig** [comment]
Just updated BotBuilder `(Microsoft.Bot.Builder)` to 3.4.0 and the property appeared, it seemed that I was using an old version of the framework. 

Thanks

**Comment by lonche** [comment]
How to update microsoft.bot.builder ???
