### ISSUE TITLE
Is it possible to handle user generated small-talk  through Bing & Cortana features from LUIS

### ISSUE THREAD

**Issue by Ani110591** [Microsoft/BotBuilder#1912]
I am implementing a chatbot which can help users fill a form and get relevant leads contacting the user. Now as part of this, there is a possibility that the user may come up with some small talk like "How are you?" "Who are you" "What is your name?" etc.

Though I have answers for the same, I cannot think of an efficient way than training each of these sentences as a separate LUIS intent. But since LUIS is backed by Bing and Cortana, can I utlize them to better handle small talk generated within the chat?

**Comment by chrimc62** [comment]
Either you can train as separate intent in LUIS, or you could use http://qnamaker.ai to create a database of the question/answer pairs you want  to use and combine them using scorable.

**Comment by Ani110591** [comment]
Hi chrimc62, thanks for pointing towards qnamaker.ai
Can the model created under qnamaker.ai be invoked from within an existing LUIS model. I am thinking that if we create an intent for small talk in LUIS and then invoke the model created under qnamaker.ai to answer them?
Is such a thing possible?
Thanks
