### ISSUE TITLE
IntentDialog in .Net

### ISSUE THREAD

**Issue by sebnema** [Microsoft/BotBuilder#1913]
In Bot Builder 3.3 version , I couln't see UniversalBot for .Net.  When will we be able to use IntentDialog in .Net?
https://docs.botframework.com/en-us/node/builder/chat-reference/classes/_botbuilder_d_.intentdialog

**Comment by willportnoy** [comment]
DispatchDialog is the equivalent in C# - here is a sample.  Feel free to ask further questions.

https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Samples/SimpleDispatchDialog/SimpleDispatchDialog.cs#L15

**Comment by willportnoy** [comment]
I'm going to close this issue for now, but feel free to open a new issue for further discussion.
