### ISSUE TITLE
How to Clear Chat Bot Conversation from UI (Emulator/WebChat)?

### ISSUE THREAD

**Issue by virendrak** [Microsoft/BotBuilder#1915]
I am developing a ChatBot application, where I am using Microsoft Bot Framework (.NET/C#).

![image](https://cloud.githubusercontent.com/assets/10959600/21495856/2bb1faa6-cc40-11e6-96a8-5f3babaa3171.png)

I have used Configuring Channel - Web Chat, added this chat IFrame code in my SharePoint/Web Page. I would like clear bot conversations on typing text like (reset/clear).

How to clear/reset conversations on Bot Emulator or WebChat? Is there any in-built function/method available in MS Bot-Framework (C#), to achieve this requirement?

**Comment by abhishan** [comment]
@virendrak 
We have built a similar interface, but instead of embedding the webchat as an IFrame, we have taken the code of the web chat and inserted into SharePoint as a webpart using script manager. This way you have more control over the web chat code and you can implement your custom operations to clear the window. We are using it to identify and set logged in user as the FROM identity in the conversation and using it with our Intranet Bot solution (http://www.acuvate.com/solutions/bot/)

Regards
~abhishan

**Comment by virendrak** [comment]
@abhishan , Thanks for the information!

I have followed the approach mentioned in https://github.com/Microsoft/BotFramework-WebChat/issues/228. 
I believe you have used (Node.JS) to develop your BOT. I am wondering if this can be achieved using C# by passing the message (user input) 'clear' or 'reset' as I am developing BOT using C#.

If you also developed BOT using C#, kindly provide more details on this line, - **_we have taken the code of the web chat and inserted into SharePoint_** 

Really appreciate your help on this!!!

**Comment by dandriscoll** [comment]
Hi @virendrak, you can access that level of functionality by hosting the control yourself or by cloning/modifying the repo to add that feature.

Details are probably best discussed over at the Web Chat repo: https://github.com/Microsoft/BotFramework-WebChat

**Comment by eanders-MS** [comment]
Hi @virendrak, closing this issue now. If you'd prefer it remain open, please @mention me here. Cheers.

**Comment by QaisarAwan** [comment]
Hi, I want to refresh my chatbot from the web page same as we do it from the Azure Test in Web Chat "Start Over"?

**Comment by EricDahlvang** [comment]
@QaisarAwan 'Test in Web Chat' recreates the iframe when the 'Start Over' button is clicked.

Currently, Web Chat does not support restarting without a page refresh.  Please follow along here for this feature's progress: https://github.com/Microsoft/BotFramework-WebChat/issues/1846
