### ISSUE TITLE
How to write new line at markup in emulator?

### ISSUE THREAD

**Issue by bayer07** [Microsoft/BotBuilder#1916]
AFAIK emulator have Markdown markup language

**Comment by dandriscoll** [comment]
In Markdown, you can insert a single break with two newline characters: `\n\n`

You can insert multiple breaks by using the `<br/>` element.

More details here: http://daringfireball.net/projects/markdown/syntax#p

**Comment by akontsevich** [comment]
<br/> works, \n\n - not!
