### ISSUE TITLE
DialogAction.validatedPrompt : only validate 2 times

### ISSUE THREAD

**Issue by astrung** [Microsoft/BotBuilder#1919]
i have a simple example from DialogAction.validatedPrompt example : [validatedPrompt](https://docs.botframework.com/en-us/node/builder/chat-reference/classes/_botbuilder_d_.dialogaction.html#validatedprompt) 

    bot.dialog('/', [
      function (session) {
        session.beginDialog('/meaningOfLife', { prompt: "What's the meaning of life?" });
      },
      function (session, results) {
        if (results.response) {
          session.send("That's correct! The meaning of life is 42.");
        } else {
          session.send("Sorry you couldn't figure it out. Everyone knows that the meaning of life is 42.");
        }
      }
    ]);
    bot.dialog('/meaningOfLife', builder.DialogAction.validatedPrompt(builder.PromptType.text, 
      function (response) {
      return response === '42';
    }));

It only validate input for 2 times. In next time , i get this response : "Sorry you couldn't figure it out. Everyone knows that the meaning of life is 42." 

It meant : DialogAction.validatedPrompt validates for only 2 times , then let my input go out from validated Prompt in third time . 

So how can i config how many times for validatedPrompts (no description in document ) ?

**Comment by willportnoy** [comment]
@maxpert can you pass maxRetries to DialogAction.validatedPrompt?

https://github.com/Microsoft/BotBuilder/blob/0fb918065126b1208756d2e5be0c2d00ecb55451/Node/core/src/dialogs/DialogAction.ts#L116

**Comment by astrung** [comment]
Ok . I passed it by changing calling dialog code : 

`session.beginDialog('/meaningOfLife', {prompt: "What's the meaning of life?",maxRetries: 5});`

But how can i pass to validate for infinite time ?

**Comment by astrung** [comment]
well, can we do it ?

**Comment by maxpert** [comment]
I think you can put on a real high number (something like 10000000), that is humanly impossible. I think infinite retries is not a good idea for any bot and it should not be practiced. Why do you need to try infinite number of times? What is the scenario?

**Comment by Stevenic** [comment]
Sorry for the delay... If you set `maxRetries` to 0 it will try for ever.

**Comment by Stevenic** [comment]
Closing this for now. Please feel free to add further comments.
