### ISSUE TITLE
[Numeric] attribute acceps letter a

### ISSUE THREAD

**Issue by maximilianlorent** [Microsoft/BotBuilder#1922]
Within one of our form flow dialogs we use [Numeric(20,100)] to prevent the user of entering anything else than a number.
This works quite well for everything I have tested except one case: if you enter the letter a or A it is accepted and mapped to 0, which obviously is a strange behaviour.

Is this a bug or by design? And if by design what can I do to prevent this strange behaviour?

**Comment by chrimc62** [comment]
I am unable to repro this on version 3.4 of the builder.  Are you possibly using an older version?  What is the data type of the underlying field?

**Comment by maximilianlorent** [comment]
I'm currently using version 3.3 of Microsoft.Bot.Builder and the data type of the underlying field is int in a first case and double? in a second case.
I'll also try it out with version 3.4 when I find the time. Unfortunately, I cannot update the project where the bug occurs right now to check it there. But I'll set up a test project for this issue.
When I have news I'll let you know.

Do you know whether there was a bug related to the numeric attribute in version 3.3?

**Comment by palmerabollo** [comment]
@maximilianlorent you could be facing this issue https://github.com/Microsoft/BotBuilder/issues/1530

**Comment by maximilianlorent** [comment]
Yeah this looks similar. However, behaviour and environment is a little bit different:

I'm using the .NET version of BotBuilder and for me v66v6 is filtered correctly - meaning I get an error here that v66v6 is not a number. But a66v6 again is not filtered correctly.

So I've got the problem with the a and A. All other letters work correct.

**Comment by chrimc62** [comment]
There have been some changes in regex generation that may have fixed this for you.  If you find the issue in the latest release, please reopen.
