### ISSUE TITLE
Microsoft Bot, How to ask user if wants to save the result and how to save it

### ISSUE THREAD

**Issue by msBot1111** [Microsoft/BotBuilder#1923]
Hi, i'm creating bot which will respond to questions and gets the answer from bing search API, and after the shown results i want to ask the user if the result is accurate, if it is to save the result, if not to show another result. I tried with prompt dialog but there i can't pass the result from search.

**Comment by willportnoy** [comment]
You can use the bot data bags (user, conversation, or per-user in conversation to store state), or better yet, store the search result in the dialog data (Node) or instance members of the dialog class (C#) for the dialog that calls the prompt dialog.
