### ISSUE TITLE
Using Lync as channel

### ISSUE THREAD

**Issue by fazalabbas** [Microsoft/BotBuilder#1924]
There was an earlier similar issue regarding custom channel for a custom chat app (https://github.com/Microsoft/BotBuilder/issues/1215?_pjax=%23js-repo-pjax-container). My question is regarding custom channel but for a "Microsoft" app, Lync. 

My Bot is working with Skype. I want to use Lync as a channel instead of Skype. Lync is whats available in my company, Skype is not allowed. Any pointer?

Thanks

**Comment by willportnoy** [comment]
The Bot Framework does not have a Skype for Business (Lync) channel.  It has a channel for Microsoft Teams, though:

https://blog.botframework.com/2016/11/02/teams-announce/

**Comment by fazalabbas** [comment]
@willportnoy Thanks. 
My requirement is specific to Lync. It will be hard to change in a regulations heavy company. I am looking into UCMA/UCWA Lync development also.
I am still looking for a solution of integration Bot framework with Lync. So if anyone else have any suggestion?
Thanks

**Comment by ankitbko** [comment]
A member of my team had successfully created a bot using UCWA and it worked fine. I had also created one using Lync 2013 SDK, you may find it [here](https://github.com/ankitbko/SkypeForBusinessBot).

**Comment by dandriscoll** [comment]
The Skype for Business team did a demo late last year of Bot Framework integration. We don't have a release date but we know this is frequently requested.

We make announcements when we launch new channels, so please stay tuned.

Please at-mention or open a new issue if you have further questions.

**Comment by fazalabbas** [comment]
Thanks ankitbko. 
Its great. 
Just saw your comment.
Thanks again

**Comment by wbreza** [comment]
@dandriscoll - Any status on Skype for Business channel?

**Comment by dandriscoll** [comment]
Nothing to report at the moment, sorry.

**Comment by AAGhotkar** [comment]
I don't see Lync channel for integration at dev.botframework.com. Is there any plan to release the same? In our case its not possible to migrate lycn to skype for business at client side. Let me know road map for the same and alternate ways to achieve it.
