### ISSUE TITLE
Error: Dialog[*:/myDialogue] not found.

### ISSUE THREAD

**Issue by iam-peekay** [Microsoft/BotBuilder#1925]
Hi. I keep getting the above dialogue not found error, even though I've defined the dialogue on the bot. In my default dialogue `/`, I invoked `session.beginDialog('myDialogue');` Then I have the myDialogue defined on the bot as:

```javascript
bot.dialog('myDialogue', [
    (session, args) => {
      session.send('some text');
      builder.Prompts.text(session, "what's your name?");
    },
    (session, results) => {
      if (results.response) {
        session.endDialogWithResult({ response: results.response});
      } else {
        session.endDialog(`I hear birds chirping. Let's move on.`);
      }
    }
]);
```
I'm using the `UniversalBot` and I haven't deployed it yet so I'm just using the emulator to locally test it.

```javascript
const connector = new builder.ChatConnector({
    appId: process.env.MICROSOFT_APP_ID,
    appPassword: process.env.MICROSOFT_APP_PASSWORD
});

const bot = new builder.UniversalBot(connector);

botServer.post('/api/messages', connector.listen());
```

I'm confused why even though I've defined the dialogue on the bot, it's not working? any help would be appreciated.

**Comment by iam-peekay** [comment]
sorry! I figured it out. Looks like I had a slight bug on my end with the dialogue set up.

**Comment by an0o0nym** [comment]
Do you mind sharing some details of what was the problem?
