### ISSUE TITLE
How to use Luis Recognizer inside a waterfall on raw string?

### ISSUE THREAD

**Issue by suvamsh** [Microsoft/BotBuilder#1926]
```javascript
bot.dialog('/activate_service', [
    function (session,args,next) {
        .
        ..
        ...
        session.beginDialog('/foo');
    }
]);

bot.dialog('/foo', [
    function (session) {
        builder.Prompts.text(session, "What do you want to do?");
    },
    function (session, results) {
        //I would like to use Luis Recognizer on results.response to determine what the users wants.
       //I have a raw string here, I don't want to begin a new dialog or anything.
    }
    ]);
```

In the above example I am trying to use Luis to understand a users response.

**Comment by willportnoy** [comment]
Can you call the LuisRecognizer code through the IIntentRecognizer interface?

https://github.com/Microsoft/BotBuilder/blob/eb29aa87ab90fc5215a36d1ca0232bf4be62a6e4/Node/core/src/dialogs/LuisRecognizer.ts#L42

**Comment by suvamsh** [comment]
I saw that method but I'm not too sure how to use it. Could you point me toward some example code?

**Comment by maxpert** [comment]
Yep you should be able to manually using ```LuisRecognizer.recognize``` if you want to do it manually.

**Comment by suvamsh** [comment]
I was able to get this to work. Thanks for your help!

**Comment by alokraj68** [comment]
How to do same in c#

**Comment by willportnoy** [comment]
@alokraj68 you should open top level threads for new-ish issues, otherwise they won't be seen.  You can just use the ILuisService implementation (called LuisService) directly.
