### ISSUE TITLE
There was an error sending this message to your bot: HTTP status code InternalServerError

### ISSUE THREAD

**Issue by varunsethnsit** [Microsoft/BotBuilder#1927]
We have built a bot with Bot framework (V > 3.0). 
We have been testing/working with our bot on the emulator in local machine and the results are as expected, bot works properly. However, when we start using the deployed (on Azure) version of our bot and work with FB Messenger or Skype, we get the error mentioned in the 
https://dev.botframework.com/ Channels Issues section. 
'There was an error sending this message to your bot: HTTP status code InternalServerError'.

* To add, while deploying our bot to Skype/FB, we have ensured that the AppID and AppPassword have been correctly updated and have tested the connection with test utility available on dev.botframework portal.

* We debugged to understand the issue better and it turns out that the bot is throwing on the very first SetPrivateConversationDataAsync call. 
We added exception handling to the state management calls (storing the bot data), and the exception states 'Precondition failed'.

* The documentation states Bot data storage might run into concurrency issues when multiple messages are trying to store the state. Though ours is a single bot service servicing single customer message, we tried the suggested solution 
**var builder = new ContainerBuilder();
            builder
                .Register(c => new CachingBotDataStore(c.Resolve<ConnectorStore>(), CachingBotDataStoreConsistencyPolicy.LastWriteWins))
                .As<IBotDataStore<BotData>>()
                .AsSelf()
                .InstancePerLifetimeScope();
            builder.Update(Conversation.Container);**

,however, issue fails to go away.

* We even have upgraded the bot framework to build 3.2 (and the associated dependencies to a compatible version) but still no help.

Can you please help address the issue, since we have been bogged down on this from a long time and its blocking our bot service to be integrated with FB/Skype channels.

**Comment by willportnoy** [comment]
Are you using both the REST client IStateClient and builder-level IBotData together?  If you're calling SetPrivateConversationDataAsync, that's from IStateClient.

**Comment by varunsethnsit** [comment]
This is the call we are making 
stateClient.BotState.SetPrivateConversationDataAsync(activity.ChannelId, activity.Conversation.Id, activity.From.Id, botData);
to store the modified properties of the bot.

**Comment by micml75** [comment]
Im having the same issue. I used to Azure template for Q&A with qnamaker.ai

**Comment by willportnoy** [comment]
@varunsethnsit @micml75 if you use the REST-level state client and the builder-level bot data bags at the same time, you're going to see etag consistency issues.  I'd recommend reading this faqs

https://docs.botframework.com/en-us/technical-faq/#what-is-an-etag--how-does-it-relate-to-bot-data-bag-storage

and if you want to disable etag consistency checking, you can use this code:
https://github.com/Microsoft/BotBuilder/issues/960#issuecomment-239435998

**Comment by willportnoy** [comment]
I'm going to close this issue for now, but feel free to open a new issue for further discussion.
