### ISSUE TITLE
Web Channel not showing choice options properly

### ISSUE THREAD

**Issue by jagdish-176** [Microsoft/BotBuilder#1928]
I use choice prompt like below
```
builder.Prompts.choice(
                  session,
                  "Choose",
                  options , {
                    listStyle: builder.ListStyle["button"]
                  });
```

For Web Channel

 If I try
      1) One 
      2) Two

Web channel shows properly.

But, If I give options 

1. One
2. Two

It shows 

*1. One*
*1. Two*

Its showing "1." for both choices.

**Comment by willportnoy** [comment]
Is this the new Web Chat control (possibly in the emulator?)

https://github.com/Microsoft/BotFramework-WebChat

**Comment by jagdish-176** [comment]
No, I have embedded in my webpage as shown on https://dev.botframework.com/

<iframe src="https://webchat.botframework.com/embed/test-bot?s=YOUR_SECRET_HERE" style="height: 502px; max-height: 502px;"></iframe>

**Comment by ubreddy** [comment]
yes. Buttons dont show up in web channel at all.

**Comment by eanders-MS** [comment]
@jagdish-176 Do you know if you're using the new Web Chat control, or the old version? The new control is still in preview, but has a much richer set of features. You must enable the new control on the WebChat config page in the dev portal.

**Comment by ubreddy** [comment]
@eanders-MS Isnt the webchat enabled by default on dev portal? This control is not supporting hero cards and carousal layouts. There are no two options here ( old vs New)

The open sources webchat widget uses DirectLine API and enabling this and hosting the widget ourselves is another option. But this makes default "Webchat" channel redundant. Is MS not going to upgrade or support Webchat channel whenever changes are made to Webchat widget?
btw, noticed that webchat widget is not showing the icon images properly

**Comment by eanders-MS** [comment]
Hi @jagdish-176 If you've enabled the "preview" option for your WebChat channel, you'll get the new WebChat control in your iframe. Can you check the dev portal to see if this option is enabled?

**Comment by ubreddy** [comment]
thanks this works. But I notice that the bot icon is not appearing against the bot message which was the case in original webchat... I thought it was good to show the icon.. Is there a setting or we lose this feature now with the latest version? Uday 

    On Wednesday, 1 February 2017 11:47 PM, Eric Anderson <notifications@github.com> wrote:
 

 Hi @jagdish-176 If you've enabled the "preview" option for your WebChat channel, you'll get the new WebChat control in your iframe. Can you check the dev portal to see if this option is enabled?—

**Comment by jagdish-176** [comment]
Yes, now it works.

Thank you.
