### ISSUE TITLE
intent and entity detection of slack data into chat bot

### ISSUE THREAD

**Issue by aakashvit** [Microsoft/BotBuilder#1929]
I am using Node Js
example
Lets say user is sending data from slack to chat bot. so chat bot will detect intent and entity from data and then perform certain action based on intent.

I already created app in luis.
I am able to communicate between bot and slack.but how i can use my model to detect entities and intent.???

**Comment by willportnoy** [comment]
I would use an IntentDialog:

https://docs.botframework.com/en-us/node/builder/chat/IntentDialog/#navtitle

**Comment by aakashvit** [comment]
let me clear problem statemnet
I am using this example [https://github.com/Microsoft/BotBuilder/tree/master/Node/examples/demo-slack]
example in mention link will display menu to user with few option
a) card  b) picture c) card 5) quite

let's say i am adding new functionality in given example 
6) enter anything related to weather or food
 so whenever user choose this option and send some text message from slack to our chat bot .
our chat bot should ob able to detect intent and entity in text ...
My doubt is how chat bat to slack and chat bot to our luis model communication will possible..because luis model will only responsible to extract entity and intent..

**Comment by willportnoy** [comment]
It sounds like you want to use a LUIS model to detect one of the options within "builder.Prompts.choice" - I think IntentDialog is still perhaps the best solution, but let's see if @Stevenic or @maxpert have any thoughts.

**Comment by aakashvit** [comment]
no it will not detect one of the options within "builder.Prompts.choice" .. lets say you already select options also..
this option a) card b) picture c) card d) quite are straight forward ..their is no issue with this options 
but when user  select option e) info, then user will send some query to  chat bot..at that time we want to get entity and intent from user query.

Note: Here our aim is not to detect option what user choose. we already giving "info" button as option in menu ..
Our aim is when user choose info button and send some bla bla text then get intent  and entity from text..

**Comment by aakashvit** [comment]
This is example code to detect entity from user text which we can gave input from  terminal

'var connector = new builder.ConsoleConnector().listen();
var bot = new builder.UniversalBot(connector);
var model = '';
var recognizer = new builder.LuisRecognizer(model);
var dialog = new builder.IntentDialog({ recognizers: [recognizer] });
bot.dialog('/', dialog);
dialog.matches('builtin.intent.alarm.set_alarm', builder.DialogAction.send('Creating Alarm'));`

but when we will get text from slack to chat bot then how we can pass to luis model in order to get intent and entity information?

**Comment by maxpert** [comment]
If I am understanding the problem correct, you just have to change your `ConsoleConnector` to `ChatConnector` and then use the `LuisRecognizer` with `IntentDialog` as you did above. Basically keep everything same as (slack demo)[https://github.com/Microsoft/BotBuilder/blob/master/Node/examples/demo-slack/app.js] just change routing part to use your recognition. e.g.

```javascript
var restify = require('restify');
var builder = require('botbuilder');

//=========================================================
// Bot Setup
//=========================================================

// Setup Restify Server
var server = restify.createServer();
server.listen(process.env.port || process.env.PORT || 3978, function () {
   console.log('%s listening to %s', server.name, server.url); 
});
  
// Create chat bot
var connector = new builder.ChatConnector({
    appId: process.env.MICROSOFT_APP_ID,
    appPassword: process.env.MICROSOFT_APP_PASSWORD
});
var bot = new builder.UniversalBot(connector);
server.post('/api/messages', connector.listen());

var recognizer = new builder.LuisRecognizer(model);
var dialog = new builder.IntentDialog({ recognizers: [recognizer] });
bot.dialog('/', dialog);
dialog.matches('builtin.intent.alarm.set_alarm', builder.DialogAction.send('Creating Alarm'));

// keep your rest of routes/dialog code...
```

If you want to do something extended you can use callbacks/waterfalls for intents, e.g:
```javascript
    dialog.matches('builtin.intent.alarm.set_alarm', function (session, result) {
          // use the result object to do custom prompts
    });
```

Does that help?

**Comment by aakashvit** [comment]
Thanks  for help.
Problem solved
