### ISSUE TITLE
LUIS extremely high response time  

### ISSUE THREAD

**Issue by euanlau** [Microsoft/BotBuilder#1931]
I am experiencing problems with LUIS starting this morning. Things got really slow all of a sudden. Response time ranges from 5s to 2 mins.

LUIS app id: 733c9129-7383-4dd8-9ecf-d4584d079652

**Comment by willportnoy** [comment]
FYI, the http://luis.ai page has a banner on the top: "Some of our services are experiencing downtime. We are working on it and should be back shortly. Apology for any inconvenience."

**Comment by euanlau** [comment]
Ok. Thanks. Let me close this issue.

**Comment by euanlau** [comment]
@cahann thanks for the update.
