### ISSUE TITLE
Provide decorator for IDialogContext

### ISSUE THREAD

**Issue by brunoklein99** [Microsoft/BotBuilder#1933]
Is there any already built in way in the framework to provide a decorator for `IDialogContext`?

**Comment by willportnoy** [comment]
You can update the registrations in Conversations.Container using an Autofac ContainerBuilder.

It's just a facade of several other objects (IBotTouser, IBotData) - you might prefer decorating those instead.

**Comment by brunoklein99** [comment]
I tried adding a decorator for `IDialogStack` as follows


```
public class WebApiApplication : System.Web.HttpApplication
{
    protected async void Application_Start()
    {
        GlobalConfiguration.Configure(WebApiConfig.Register);
        
        var builder = new ContainerBuilder();

        builder.RegisterDecorator<IDialogStack>(stack => new LoggingDialogStackDecorator(stack), "logging");

        builder.Update(Conversation.Container);
    }
}
```

And I simply call the following code when I receive an `Activity`

```
await Conversation.SendAsync(activity, () => 
                    new ExceptionHandlerDialog<object>(
                        new GreetingDialog<object>(
                            new DayWithinNextTwoMonthsDialog(_platformFacade))));
```

But the `IDialogStack` inside the `IDialogContext` that is used inside my dialogs is still a `Microsoft.Bot.Builder.Dialogs.Internals.DialogTask`

**Comment by brunoklein99** [comment]
Maybe `DialogModule.cs` could be updated to add names for the registrations, so we can use Autofac's decorator registration methods.

**Comment by brunoklein99** [comment]
I cannot possibly do this. I've tried everything ranging from simply trying to decorate `IDialogContext`, to also trying to decorate `DialogContext`'s constructor parameters as suggested. When that didn't work I tried to decorate `IDialogTask`, `IDialogStack` and also `IDialogTaskManager`, in an attempt to provide a custom implementation of `IDialogTaskManager.CreateDialogTask()`. I also can't find where the type `Func<IDialogStack, CancellationToken, IDialogContext>` is being registered in [here](https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Microsoft.Bot.Builder/Dialogs/DialogModule.cs#L178).

I honestly think the framework should provide an API so users can actually add their own decorator for `IDialogContext`

Thank you.

**Comment by willportnoy** [comment]
@brunoklein99 this is the pattern I'm thinking of adopting - any thoughts?

https://github.com/Microsoft/BotBuilder/blob/develop/CSharp/Library/Microsoft.Bot.Builder.Autofac/Dialogs/DialogModule.cs#L289
https://github.com/Microsoft/BotBuilder/blob/develop/CSharp/Library/Microsoft.Bot.Builder.Autofac/Base/Extensions.cs#L61

**Comment by brunoklein99** [comment]
I am not too familiar with Autofac specifically. But I gather a simple call like `builder.RegisterKeyedType<DialogContextDecorator, IDialogContext>()` would suffice? or maybe `RegisterAdapterChain` if we want chained decorators? I think this is as good as it gets.

Would we need somehow to re-register something the framework already does, because our decorators are overriding the framework's registration? I think that would be an issue.

**Comment by brunoklein99** [comment]
Ho we have an ETA for this or some kind of work around to get `IDialogContext` decorators going?

Thank you.

**Comment by willportnoy** [comment]
@brunoklein99 as a work-around, can't you register a new implementation of IDialogContext?

https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Microsoft.Bot.Builder/Dialogs/DialogModule.cs#L183

The Func<blah, IDialogContext> is automatically provided by Autofac as a delegate factory:
http://docs.autofac.org/en/latest/advanced/delegate-factories.html

**Comment by brunoklein99** [comment]
Yeah, it works if I register a new implementation which has the same constructor parameters as the original.

**Comment by JasonSowers** [comment]
@brunoklein99 I am going to close this issue for inactivity if you require further assistance please reopen.
