### ISSUE TITLE
Can't serve static attachement to Messenger App

### ISSUE THREAD

**Issue by JpEncausse** [Microsoft/BotBuilder#1934]
Hi,
I setup a MSBotBuilder bot connected to a Facebook Messenger Bot/App.

- I **can** display a Facebook card with a given image from my server in **Web** Messenger
- I **can't** display the image of that same card in **App** Messenger
- I can copy that image to my Dropbox and display it in **App** Messenger

My setup my resify like that:

```
server.get(/\/static\/?.*/, restify.serveStatic({
    directory: root,
    default: 'index.html',
    charSet: 'utf-8',
}));
```
And the server itself has a certificate. The image tested:
https://secure.encausse.net:3978/static/shot_horse2.png

I don't understand why Facebook Messenger App can display images that comes from my MSBotBuilder server but works with third party location. I set a full URL, not a relative one. And it works with Messenger webapp !

**Comment by Noc2** [comment]
I have a similar issue. I generate charts based on the user input and upload the diagram into a blob container on Azure. I can see the charts on the local emulator and the messenger web app. But I can’t see the image on Skype and Facebook Messenger app. A download link works fine on every channel. 
I’m using a HeroCard to show the image and the download link:


```
HeroCard plCard = new HeroCard()
            {
                Title = name,
                Text = text,
                Buttons = new List<CardAction>() { new CardAction(ActionTypes.OpenUrl, "Download Chart", value: imgURL) },
                Images = new List<CardImage>() { new CardImage(url: imgURL)},
            };
```

**Comment by nickcordrey** [comment]
These may or may not resolve both the above issues but on investigation we found the following two issues:

1. Image URLs cannot include port numbers - these get rejected by the Skype image service
2. Image URLs need to be https with a root certificate trusted by Microsoft - or will get rejected by the Skype image service. You can check if the certificate is trusted by opening the URL in Explorer or Edge.
