### ISSUE TITLE
Cannot escape from Dialog

### ISSUE THREAD

**Issue by anthodv** [Microsoft/BotBuilder#1935]
Hi,

Thanks for your great framework.

I face an issue with context.Done when the user is done with the current IDialog.

Even after calling context.Done the next message will automatically call the previous dialog. 

Any suggestion how to proper dispose the first dialog ?

```
            if(int.TryParse(ID, out n))
            {
                DBLookupJobInfo.StructJobInfo Info = DBLookupJobInfo.lkpJobInfo(ID);
                var attachment = GetThumbnailCardForCv(Info);
                message.Attachments.Add(attachment);

                await context.PostAsync(message);
                //context.Wait(this.MessageReceivedAsync);
                context.Done<object>(null);
          
            }
```

**Comment by willportnoy** [comment]
Do you call context.Done on all control flow paths through that method?
https://docs.botframework.com/en-us/technical-faq/#ensure-all-dialog-methods-end-with-a-plan-to-handle-the-next-message

Or is there a thrown exception that prevents your state from being serialized?
https://docs.botframework.com/en-us/technical-faq/#look-for-exceptions

**Comment by anthodv** [comment]
Thank for your answer,

Yes i do call _Call_ or _Done_ on all my paths.

I tried to call twice context.Done and the second time it breaks with an invalid state (which I assume is normal), but actualy release from the IDIalog and the next message is correctly handled by the message dispatcher.

Is there any way to diagnose the stack state through debugger ?

**Comment by anthodv** [comment]
I realised I was referencing a Singleton class at some point in this method, may it be the issue ?

from the link you gave me :
 _But beware that anonymous method closures are not serializable if they reference their outside environment to capture variables._

**Comment by willportnoy** [comment]
@anthodv I would turn on "break on thrown exceptions" to see if you have unhandled exceptions.

We have a method to reference non-serializable services:
https://docs.botframework.com/en-us/technical-faq/#how-can-i-reference-non-serializable-services-from-my-c-dialogs

**Comment by anthodv** [comment]
Thanks for the great support, I'll look into it.
