### ISSUE TITLE
TotalParticipants is wrong in Slack private channel

### ISSUE THREAD

**Issue by wiltodelta** [Microsoft/BotBuilder#194]
Bot added to the private channel Slack with 3 members. When I receive a message, TotalParticipants is 2, but must be 3.

Also, the bot receives messages without mentioning him.

**Comment by wiltodelta** [comment]
Any update?

**Comment by Stevenic** [comment]
I'll check with @tomlm to see if  anyone has looked into this yet

**Comment by wiltodelta** [comment]
I checked, bug is fixed.
