### ISSUE TITLE
NodeJS: Hosting on Linux Server

### ISSUE THREAD

**Issue by arunnanjundaswamy** [Microsoft/BotBuilder#1942]
HI, 

Is it possible to host the bot built using NodeJS on a Linux server (with Public IP) and "Register" the bot URL as "Messaging Endpoint"?

Regards,
Arun

**Comment by willportnoy** [comment]
Yes, that should work just fine, though I don't have personal experience with it.

I don't believe the Node version of the builder depends on any packages that aren't available on Linux.

**Comment by eanders-MS** [comment]
Hi @arunnanjundaswamy, closing this issue now. If you prefer it remain open, please @mention me here. Cheers.
