### ISSUE TITLE
Faulty reference to Microsoft.Bot.Connector, Version=3.3.3.0

### ISSUE THREAD

**Issue by jsiegmund** [Microsoft/BotBuilder#1948]
I've included the latest version (3.4.0) of Microsoft.Bot.Builder in my bot project which is based on the Azure Bot Service. Upon compilation, I see the following warning in the logs:

> warning CS1701: Assuming assembly reference 'Microsoft.Bot.Connector, Version=3.3.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' used by 'Microsoft.Bot.Builder.Azure' matches identity 'Microsoft.Bot.Connector, Version=3.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' of 'Microsoft.Bot.Connector', you may need to supply runtime policy

Not sure where the 3.3.3.0 reference is coming from as the version should be 3.4.0.0. At compilation time it's a warning, but trying to run it I get:

> Exception while executing function: Functions.messages. mscorlib: Exception has been thrown by the target of an invocation. f-messages__658612385: Could not load file or assembly 'Microsoft.Bot.Connector, Version=3.3.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.

So it seems there's a reference to that 3.3.3.0 version somewhere, but I have no clue where. I searched the contents of my folder but can't find anything causing this. So two questions: 1) any idea where this comes from and 2) how to supply that runtime policy as a workaround?

**Comment by jsiegmund** [comment]
Never mind, posting it I see my own mistake... It's coming from the Microsoft.Bot.Builder.Azure reference which I forgot to update to a recent version. My bad.

**Comment by jsiegmund** [comment]
Ok maybe not. Adding Microsoft.Bot.Builder.Azure does not include the required reference to Microsoft.Bot.Connector. Adding Microsoft.Bot.Builder does add that reference, but version 3.4.0.0 where the Azure package requires 3.3.3.0. 

So I tried adding Microsoft.Bot.Builder version 3.3.3.0 in combination with Microsoft.Bot.Builder.Azure version 3.1.0 and now get: 

> Exception while executing function: Functions.messages. mscorlib: Exception has been thrown by the target of an invocation. f-messages__1257297480: Could not load file or assembly 'Microsoft.Bot.Connector, Version=3.3.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.

Which is strange, since that assembly is in the Microsoft.Bot.Builder package, I can see it in my NuGet package cache. What am I missing here!?

**Comment by jsiegmund** [comment]
I'm going to reopen this again (sorry...). The error shows up *sometimes* and I can't really figure out when or why. Restarting VS solves the issue, closing the task runner task and reopening is does not (which also restarts the func process so I don't get why rebooting works and this does not). Not sure whether this is a func bug or whether it has something to do with the bot connector assemblies. I only have the issue for the bot connector, not for any other DLLs.

**Comment by jsiegmund** [comment]
Closing this again. I cannot steadily reproduce it and I've got the feeling that the functions CLI is to blame for this, not the bot framework.

**Comment by isaacy** [comment]
I'm seeing the same problem and the worst part is that only one of my bots showed this problem.  The others are fine.  And I really don't know how to debug this.

**Comment by isaacy** [comment]
I found that an easy way is just to restart the service, and the problem goes away :)

**Comment by jsiegmund** [comment]
Yeah I found the same. And it appears "sometimes" but I cannot reliably reproduce it.

**Comment by MattTatoczenko** [comment]
Thanks for the workaround of restarting to fix this. Not sure what happens.
I just did a deploy from GitHub and my bot was throwing:
Exception while executing function: Functions.messages. mscorlib: Exception has been thrown by the target of an invocation. f-messages__658612385: Could not load file or assembly 'Microsoft.Bot.Connector, Version=3.3.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.

I'm thinking it's not loading up properly on the workers my bot runs on due to being on the consumption plan. Restart gets all of that sorted out for now.
