### ISSUE TITLE
[Question][NodeJS][LUIS]  Booking an hotel room

### ISSUE THREAD

**Issue by JpEncausse** [Microsoft/BotBuilder#195]
Hi,
What are best practices to book an hotel room with a LUIS bot ? What am I doing wrong ?

1. I hook my hotel bot on /hotel
`root.matches('^/hotel', builder.DialogAction.beginDialog('/hotel'));`

2. I hook my LUIS dialog on my bot
```
var luis = new builder.LuisDialog(...)
luis.onDefault(function (session) { session.send('What ?'); });
bot.add('/hotel', luis);
```

3. I hook my intent "I want to book a room in Paris tomorrow"
```
luis.on('intent.hotel.booking', [
    function(session, args, next){
            var place = builder.EntityRecognizer.findEntity(args.entities, 'builtin.geography.city');
            var from  = builder.EntityRecognizer.resolveTime(args.entities, 'builtin.datetime.date');
            session.dialogData.hotel = { "place":  place,  "from" : from  }
            next();
        },
       function(session, results, next){
            if (session.dialogData.hotel.place){ next(); }
            builder.Prompts.choice(session, "Where ?", ["paris", "London", "Berlin", "NewYork"]);
        },
]);
```

**Questions:**
1. `resolveTime()` use Chrono so do not work in French
2. Is there a builder.Prompts.LUIS(...) ? I want to use entities of my LUIS if user only say "I want to book a room"

EDIT: 

I create an other LuisDialog registered to '/hotel/book/feats'
In my main waterfall I call `session.beginDialog('/hotel/book/feats');`
The dialog didn't wait for luis intent and call my sub waterfall

**Comment by Stevenic** [comment]
So to answer your original question you're correct Cronos is English only.  While there isn't a built in LUIS prompt for doing this you could easily build one:

```
var modelUri = 'http://luis.ai/your/model';
bot.add('/fromPrompt', function (session, results) {
    if (results) {
        if (results.response) {
            // Call LUIS and resolve matched entities
            builder.LuisDialog.recognize(session.message.text, modelUri, function (err, intents, entities) {
                var from  = builder.EntityRecognizer.resolveTime(args.entities);
                if (from) {
                    // User said a valid date.
                    session.endDialog({ response: from });
                } else if (session.dialogData.maxRetries > 0) {
                    // Re-prompt
                    session.dialogData.maxRetries--;
                    builder.Prompts.text(session, "I'm sorry I didn't get that. What date you arriving?");
                } else {
                    // Too many retries. We end the dialog with a reason of notCompleted.
                    session.endDialog({ resumed: builder.ResumeReason.notCompleted }); 
                }
            });
        } else {
            // User said 'nevermind' or something
            session.endDialog(results);
        }
    } else {
        // First call to prompt
        session.dialogData.maxRetries = 2;
        builder.Prompts.text(session, "When are you arriving?");
    }
});
```
You would call this in a waterfall just like any other prompt, `session.beginDialog('/fromPrompt').` The result of the prompt will be passed to the next step of the waterfall. This leverages an undocumented static LuisDialog.recognize() method which I may just go ahead an document. That's what LuisDialog uses internally to recognize things.  I didn't actually test this but it should work. Let me know if you have problems with it.

**Comment by Stevenic** [comment]
Please reopen if you're still having trouble with this.
