### ISSUE TITLE
Get Skype User Profile Information

### ISSUE THREAD

**Issue by piffarettig** [Microsoft/BotBuilder#1952]
I ve seen the JSON being exchanged on each message with the bot via Skype, and Skype only provides you an ID and the user's full name. As well, I ve seen over  [here](https://github.com/Microsoft/BotBuilder/issues/1637) that this guy wanted to obtain the user's username but that's not possible yet.

Is it any way of requesting a HTTP Restful API provided by Skype in order to get that info? I tried to research over Skype documentation but I didn't seem to find what I wanted. What currenty exists are different SDKS, both for web, mobile/tablet apps or even Skype uris that can be embedded on html, but no RESTful endpoints.

Docs seem to be a little bit hazy and difficult to understand.

[Doc 1](https://dev.office.com/Skype/sdks)
[Doc 2](https://msdn.microsoft.com/es-es/skype/skypedeveloperplatform)

Any help solving this? 

Thanks!

**Comment by francescacoo** [comment]
Hi,
I have seen using the node.js Skype example that they take the name on adding the contact to Skype:

bot.on('contactRelationUpdate', function (message) {
    if (message.action === 'add') {
        var name = message.user ? message.user.name : null;
        var reply = new builder.Message()
                .address(message.address)
                .text("Hello %s... Thanks for adding me. Say 'hello' to see some great demos.", name || 'there');
        bot.send(reply);
    } else {
        // delete their data
    }
});

I tried and it does work.
No idea how to take it though in other situations / not the adding to contacts?

**Comment by nwhitmont** [comment]
This is currently not possible with BotBuilder SDK as the Skype user is represented by a UUID for privacy reasons.  You would need to interact with the Skype API directly.

**Comment by piffarettig** [comment]
How can I interact with the Skype API to get user info? Of course, without authenticating the user again, as he's already authenticated. What data does the BotBuilder provide so I can use to get the username in the Skype Api?

**Comment by osvc96** [comment]
@francescacoo  Hi, does this get you the actual username or the display name?
