### ISSUE TITLE
Bot application service url IP address

### ISSUE THREAD

**Issue by nagenndrababu** [Microsoft/BotBuilder#1953]
Hi Team,

We need your support in enabling our firewall proxy settings for  testing our hosted bot application. Through our logs in the application we are seeing the following error

Bot application error
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 40.127.139.252:443

 Upon  performing the trouble shooting with the network firewall it has been observed that firewall is blocking the requests from botframework service and for every request  it comes from different IP address from microsoft service. Could you provide us the range of IP addresses from which the requests are coming. So that we will enable those range of IP in our firewall

**Comment by dandriscoll** [comment]
Hi @nagenndrababu, there is unfortunately no single list of IP addresses. Many of the Bot Framework servers are hosted on Azure, although many are not, and some of them may move without notice.

**Comment by vovanb** [comment]
We have same issue from customer which would like to protect their service by defining range of ipadresses in firewall.
I think it is reasonable requirement.

**Comment by dandriscoll** [comment]
Hi @vovanb, we don't have a single list. Traffic could originate from any Azure datacenter or any Microsoft non-Azure datacenter. You can find a list of all Azure IPs but I don't think there is a published list of other Microsoft servers.

**Comment by dandriscoll** [comment]
You can find the Azure IP ranges here: https://www.microsoft.com/en-us/download/details.aspx?id=41653

These IPs will work for some channels for now, but may break without notice (and without the possibility of reversing the change) in the future.

**Comment by dandriscoll** [comment]
Closing as we have answered the question. Please open a new issue if you'd like to discuss further.
