### ISSUE TITLE
How can I send tokens/parameters along with messages?

### ISSUE THREAD

**Issue by mohit-jcc** [Microsoft/BotBuilder#1954]
The server listens to messages via this which does not expose a `request` object.

`server.post('/api/messages', connector.listen());`

For my purpose, I need to receive a parameter token form the client app (webchat) at the time of connections. 

What is the best approach for this ?

**Comment by maxpert** [comment]
Hey seems like you are trying to intercept the request and you want to forward the request only if you get the right token. If that is the case it's pretty simple. The ```listen()``` method returns a closure function back that takes the restify request and response object you can simply wrap the object in your own closure and intercept the request example:

```javascript
var botListener = connector.listen();
server.post('/api/messages', (req, resp) => {
    if (req.query.token == '<WHATEVER YOUR TOKEN IS>') {
        botListener(req, resp);
    }
});
```

 Let me know if this works for you.

**Comment by mohit-jcc** [comment]
@maxpert this works just fine, thanks!

**Comment by abhishan** [comment]
@mohit-jcc 
Are you doing this as another level of authentication/authorization for the user with the bot? We are attempting something similar and would appreciate your thoughts/approach in this regard.
~abhishan

**Comment by mohit-jcc** [comment]
@maxpert @abhishan 

Well what Im attempting is to bind the token value passed with the session created - 

var botListener = connector.listen();
server.post('/api/messages', (req, resp) => {
    // How can I save req.query.token here so it's uniquely available within the bot session?
    botListener(req, resp);
});


var bot = new builder.UniversalBot(connector, function(session){
    session.send("Hello");
    //this is where i need to set 'session.userData.token'
    session.beginDialog('login');

});

While the solution by @maxpert works, I am still not completely through with this. Thanks.

**Comment by mohit-jcc** [comment]
@abhishan : please have a look at this - https://github.com/Microsoft/BotBuilder/issues/1996

**Comment by maxpert** [comment]
@mohit-jcc Nops session object won't directly carry the query parameters by default. But you can write a session middlewa

**Comment by mohit-jcc** [comment]
@maxpert Thanks for the heads up. So if this is added as a feature, do you suggest I wait for it or it will be good to use the middleware and have a work around? How soon can the feature be expected? Thanks.

**Comment by Stevenic** [comment]
You should be able to write a piece of middleware that extracts the token and saves it to the session object for each request. That's one of the intended reasons for supporting middleware.

**Comment by stevengum97** [comment]
Closing issue as it has been answered.
