### ISSUE TITLE
Conversation.ResumeAsync returns "Operation is not valid due to the current state of the object"

### ISSUE THREAD

**Issue by jsiegmund** [Microsoft/BotBuilder#1956]
I am trying to resume a conversation after completion of an external even. I'm using Conversation.ResumeAsync to do so, passing in the resumptionCookie and a message. I'm getting the above error in return which is not very helpful. So now I'm stuck trying to find out what it going wrong and why. Would be nice to have some pointers as to where to look! 

> Exception: System.InvalidOperationException: Operation is not valid due to the current state of the object. at Microsoft.Bot.Builder.Dialogs.Conversation.<>c3`1.<ResumeAsync>b3_0() at Microsoft.Bot.Builder.Dialogs.Internals.ReactiveDialogTask.<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d3`1.MoveNext() — End of stack trace from previous location where exception was thrown — at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Bot.Builder.Dialogs.Internals.ExceptionTranslationDialogTask.<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d21.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Bot.Builder.Dialogs.Internals.LocalizedDialogTask.&lt;Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync&gt;d__21.MoveNext() — End of stack trace from previous location where exception was thrown — at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Bot.Builder.Dialogs.Internals.ScoringDialogTask1.&lt;Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync&gt;d__31.MoveNext() — End of stack trace from previous location where exception was thrown — at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Bot.Builder.Dialogs.Internals.PersistentDialogTask.<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d3`1.MoveNext() — End of stack trace from previous location where exception was thrown — at Microsoft.Bot.Builder.Dialogs.Internals.PersistentDialogTask.<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d31.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Bot.Builder.Dialogs.Internals.SerializingDialogTask.&lt;Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync&gt;d__41.MoveNext() — End of stack trace from previous location where exception was thrown — at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Bot.Builder.Dialogs.Internals.PostUnhandledExceptionToUserTask.<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d__5`1.MoveNext()

**Comment by willportnoy** [comment]
It's coming from this line.

https://github.com/Microsoft/BotBuilder/blob/develop/CSharp/Library/Microsoft.Bot.Builder.Autofac/Dialogs/Conversation.cs#L103

I believe it's occurring because the ResumptionCookie is being used to resume a conversation where there is no state storage for that conversation.

This may be caused because the state storage for that conversation

1. has been cleared explicitly, or
2. it has been made invalid because the dialog stack could not be deserialized (perhaps the code changed?)

**Comment by jsiegmund** [comment]
I don't think either of those is the case, but I'm not super sure as well. Can I somehow check whether there is any state storage for a specific conversation?

The scenario is the following: user chats with the bot, bot sends back a card for OAuth authentication (Azure AD). User clicks the link and eventually Azure calls the return URL which in the same service (I'm actually reusing the messages endpoint for that, see http://stackoverflow.com/questions/41444626/bot-service-with-oauth-endpoint?noredirect=1#comment70098112_41444626. 

Now in the code that handles the OAuth postback, I need to resume the conversation. That's where this happens. So definitely no code change as the above is all in one chat session. If there was a problem with serialization I'd expect that to pop-up earlier, right?

**Comment by willportnoy** [comment]
As far as I understand, working backward:

1. InvalidOperationException is thrown, because
2. Func<IDialog<object>> is called, because
3. there is no dialog on the stack to which to post the activity, because
4. either
a. the stack could not be deserialized from storage (code change), or
b. the stack was not found in storage (ResumptionCookie address fields don't match storage keys)

That's my thinking - can you debug during the oauth callback and see if there are any exceptions?

**Comment by jsiegmund** [comment]
This is actually the exception that happens during the oauth callback, the rest of it works as expected. I'm trying to understand what is happening; if I understand correctly it will try to restore state based on the address stored in the ResumptionCookie. Does that also imply that this needs to take place on the same server, or is the storage located somewhere shared (azure store account? and on localhost?)? Cause I am working on creating a separate endpoint for the oauth callback flow because I didn't want that to use the messages endpoint. But if that somehow could interfere with resuming the dialog I'll need to find a different solution.

**Comment by jsiegmund** [comment]
I've got a (very rough) version of the source code up here: https://github.com/mstack/bots-jennifer. If you're able to take a quick look, that would be highly appreciated :)

**Comment by willportnoy** [comment]
@msft-shahins any thoughts?

@jsiegmund it looks like you're using the correct ResumptionCookie to set up the lifetime scope so that the IStateClient points to the same bot state bags so that the dialog stack should be able to be restored without needing to try to instantiate a new root dialog.

**Comment by jsiegmund** [comment]
Sorry to have to bump this but still haven't found the issue or a solution and this is becoming a blocking issue. Would be awesome if someone could take a further look. @msft-shahins @willportnoy

**Comment by jsiegmund** [comment]
I have the idea that when the callback returns, there's no conversation left to resume. If I understand the concept correctly, the stack should hold dialogs that are waiting for incoming messages, and the one on top will be processing the incoming message. So is the stack is empty, the message cannot be processed by a dialog.

I know there's something wrong there, because during debug starting the same dialog twice and then performing the callback does seem to work. Of course in that case the wrong dialog is handling the Conversation.Resume call, but at least it's not returning that stack exception. So I must be missing something that causes the auth dialog not to be added onto the stack for resumption. I'm just not sure what.

**Comment by jsiegmund** [comment]
I finally seem to have found something. I'm debugging using local functions-cli. I had been moving dialogs into a precompiled DLL so that I could have intellisense when writing the dialog code, since CSX doens't have intellisense yet. 

Now for the post above this one: when I move the **exact same** code into a CSX file and load that one instead: the response is being passed to the correct dialog! This is most likely also the issue with the authentication stuff, because I have that dialog in the DLL as well. It seems the bug here is that when a dialog is loaded from a precompiled DLL, there's a problem with resuming the correct dialog.

**Comment by willportnoy** [comment]
We have some code in the Azure Bot Service to handle the serialization of delegates involving dialogs:

https://github.com/Microsoft/BotBuilder-Azure/blob/master/CSharp/Library/Microsoft.Bot.Builder.Azure/AzureModule.cs#L126

It seems related to your issue.  @msft-shahins for visibility.

**Comment by msft-shahins** [comment]
@jsiegmund do you have a simple bot that repros this issue? If so, can you share the code for that bot?

**Comment by jsiegmund** [comment]
Not a simple one, no. But I suspect you can repro with a simple LUIS (or probably any type of) dialog that calls a formflow which comes from a precompiled DLL. I now moved everything into a WebAPI project and all problems completely disappeared.

**Comment by jsiegmund** [comment]
Here's a simple repo that has the same issue: https://github.com/jsiegmund/repsaj-bot-repro. The call dialog will never get beyond the first question, it's like a groundhog day dialog :)

**Comment by haligasd** [comment]
so a little more to add.  i think this is the right thread

i get the same error using the ResumptionCookie but can fix it.  I think my fix then causes proactive bots messages i am trying to do not work though.  Not 100% on that yet

so in my Global.asx while building the Autofac container if I do the following

            builder.Update(Conversation.Container);
            var container = Conversation.Container;
            config.DependencyResolver = new AutofacWebApiDependencyResolver(container);

the errors doesn't occur and I can do Conversation.ResumeAsync just fine however I have to add

                    var dialog = scope.Resolve<IDialog<object>>();
                    DialogModule_MakeRoot.Register(scope, () => dialog);

to my MessageController before calling

                    var postToBot = scope.Resolve<IPostToBot>();
                    await postToBot.PostAsync(activity, token);

to make sure i don't get a Autofac Exception.  If do the following in Global.asx

            var container = builder.Build();
            config.DependencyResolver = new AutofacWebApiDependencyResolver(container);

the Convesation.ResumeAsync gives me the "Operation is not valid due to the current state of the object" error, but I do not have to call 

                    var dialog = scope.Resolve<IDialog<object>>();
                    DialogModule_MakeRoot.Register(scope, () => dialog);

anymore and the IPostToBot resolves just fine.  All this roots from trying to get proactive dialogs working and i simply cannot.  the bot gets the first response in the proactive dialog but routes it to the route.  Scoured every example including the AlarmBot, etc and cannot get this to work.  Hopefully some of this helps.  I am on 3.5.2

**Comment by stelazh** [comment]
Could you please help me with my question : https://stackoverflow.com/questions/42298992/how-to-call-formflow-after-user-choose-an-option-from-quickreply-in-chatbot

I want to call formflow from my dialog...

**Comment by willportnoy** [comment]
@stelazh is your issue related to this issue?  you might consider opening a top level issue for your question.

**Comment by JasonSowers** [comment]
@jsiegmund have you found a workaround, or has the issue been resolved?

**Comment by nwhitmont** [comment]
@jsiegmund thanks for the update

**Comment by Yudner** [comment]
@jsiegmund and did you check to see if it works well?
