### ISSUE TITLE
Make bot send a message to a certain user in response to another user action

### ISSUE THREAD

**Issue by piffarettig** [Microsoft/BotBuilder#1957]
To put this simple:

I have **User A** and **User B**. Both have added my bot in their corresponding Skype accounts. Whenever **User A** does some specific action, I want to trigger a message to **User B**, via Skype Bot as well. So basically this is an example of a bot messaging 'proactively' but not to the same user, to a different one. That is because **User B** will be receiving a message from his bot a consequence of some action **User A** did. Whenever the **User B** receives the message, he does some action in response that goes backwards to **User A**.

Any suggestions on how should I implement this? Any examples? 

Bot Connector Service has any way of implementing this?

Thanks

**Comment by piffarettig** [comment]
I found this: [Starting Conversations](https://docs.botframework.com/en-us/csharp/builder/sdkreference/routing.html#conversation), where this code is shown as an example for starting 1:1 conversations:

```
var userAccount = new ChannelAccount(name: "Larry", id: "@UV357341");
var connector = new ConnectorClient(new Uri(incomingMessage.ServiceUrl));
var conversationId = await connector.Conversations.CreateDirectConversationAsync(botAccount, userAccount);
IMessageActivity message =  Activity.CreateMessageActivity();
message.From = botAccount;
message.Recipient = userAccount;
message.Conversation = new ConversationAccount(id: conversationId.Id);
message.Text = "Hello";
message.Locale = "en-Us";
await connector.Conversations.SendToConversationAsync((Activity)message); 
```

However I still have some doubts:
1)  How can I get the ChannelAccount properties (name and id) for the user I want to message? 
2) botAccount:ChannelAccount was never initialized in that code. I guess  `var botAccount = activity.Recipient;` would do the trick right?

Thanks!

**Comment by abhishan** [comment]
@piffarettig 
For sending messages from Bot to a user on Skype, we are saving the **ResumptionCookie** from the "conversationUpdate" activity along with the Skype user **Display Name** in a SQL Azure DB (You can store this in any external database of your choice). This is then used for sending messages to a user from the bot. We have built on top of the Proactive Bot example (https://docs.botframework.com/en-us/azure-bot-service/templates/proactive/) in .NET.

This has worked for us, but _may_ not be the most elegant (or best practice) way to do this.
@dandriscoll - Kindly share your insight on this approach.

**Comment by piffarettig** [comment]
UPDATE:

Some way I found of getting the ID of the certain user was this one:

1) Created a new Skype user to act as **User B**. Made it send a random message to the Bot.
2) Debugging the bot's logic, I saw its ChannelAccount info by doing `activity.From`.
3) Copied both name and id values.
4) Then I tested sending a message from **User A** to that **User B** (the one I ve just copied its values), changing the parameters in the userAccount (code above), for the ones I copied. 

It worked and **User B** received the message.

That was just a hardcoded test to know if that could be achieved, although I am not sure of what could be the best option to store  the user info I need to send messages proactively. What do you suggest?

**Comment by maxpert** [comment]
In order to send message to a *User B* I think you need to have some recipient info about *User B* and that can be only obtained once *User B* interacts with bot. Problem is platforms like Skype, and FB don't let you send message to people directly. I think it's possible in channels like Slack but not everywhere else. @msft-shahins should be able to add more details.

**Comment by dandriscoll** [comment]
Yes, this is possible.

You need to have the user's channel account. On Skype, this account is obfuscated to bots, so the user must contact the bot first. On other channels, like email and SMS, the account is simply the user's contact information, and you can reach out to the user on your own.

If you have a conversation ID corresponding to a discussion with the user you want to contact, you can use that conversation ID directly. (Don't try to create a conversation ID on your own.)

If you don't have a conversation ID or if you want to start a new conversation (relevant for channels like email), call the CreateConversation API and specify the user in the parameters to that call. This will return a conversation ID and you can send activities as usual.

**Comment by piffarettig** [comment]
@dandriscoll ok. Thanks. The channel I'm using is Skype. Supposing that in the interaction with the bot is carried out successful and I have the conversation ID between them:

1) What is the best option to store that ID?
2) How do I know is the first time the bot and the user started talking? Because I don't want to save the conversationId every time a message is sent.

**Comment by piffarettig** [comment]
@abhishan thanks! Proactive bot uses Azure Queue and Azure functions... How re you using that? Seems a little bit overkill for what I want to achieve.

**Comment by chetanmekha** [comment]
Hello piffaretting,
You can log user chat history in your DB, you can store field like conversation Id,bot ID, user name etc(all fields you will get it in botbuilder session).  When you want to send a message from bot to user you can use DB data.
Please refer below code for storing user chat history,
`
var bot = new builder.UniversalBot(connector);
bot.use({
    receive: function (event, next) {
        if (event.address.channelId !== 'emulator') {
            // GET CURRENT INVOICE ID
            var CurrentInvoiceID = '';
            if (event.text !== undefined) {

                var data = {
                    flintCustomerId: "FlintCustomerId",
                    customerName: event.user.name,
                    invoiceId: CurrentInvoiceID,
                    id: event.user.id,
                    message: event.text,
                    messengerChannel: event.address.channelId,
                    timeStamp: event.timestamp,
                    botId: event.address.bot.id,
                    conversationId: event.address.conversation.id
                }
                dbhelper.insertUserChatDetails(data);
                //LOG DASH BOT
                bothelper.DashLogg(event, "incoming");
            }
        }
        next();
    },
    send: function (event, next) {

        if (event.address.channelId !== 'emulator') {
            // GET CURRENT INVOICE ID
            var CurrentInvoiceID = '';
            if (event.text !== undefined) {
                var startDate = new Date();
                var data = {
                    flintCustomerId: "FlintCustomerId",
                    customerName: event.agent,
                    invoiceId: CurrentInvoiceID,
                    id: event.agent,
                    message: event.text,
                    messengerChannel: event.address.channelId,
                    timeStamp: startDate,
                    botId: event.address.bot.id,
                    conversationId: event.address.conversation.id
                }
                dbhelper.insertUserChatDetails(data);

                //SEND SMS 
                //LOG DASH BOT
                bothelper.DashLogg(event, "outgoing");
            }
        }
       // bothelper.SendTestSMS(event.text, function (res) {
       //     next();
      //  });

    }
});`

**Comment by piffarettig** [comment]
I solved it using doing mostly three things:

1) Setting up an Azure Table Storage on Azure (due to its simplicity, and that I don't require a Relational database for this).

2) Saving user channel info the first time they establish connection (in C# this is when the activity type is  **ContactRelationUpdate**. 

3) Then using the code above ([here](https://docs.botframework.com/en-us/csharp/builder/sdkreference/routing.html#conversation)), to send proactive messages from the bot to the user. As I stated:

botAccount:ChannelAccount was never initialized in that code. I guess var botAccount = activity.Recipient did the trick. This would be the new 'From' in your message. Similarly, the new Recipient is going to be the user you saved in Azure Table Storage. [Here you can learn how to use Table Storage ](https://docs.microsoft.com/en-us/azure/storage/storage-dotnet-how-to-use-tables)

**Comment by mmacneil** [comment]
@abhishan How did you detect when to save the ResumptionCookie within the "ConversationUpdate" activity.  I am using the Proactive template as a base as well and have noticed when using the  "Trigger" activity that "ConversationUpdate" is firing first and I'm struggling to determine the right state to save the conversation id etc...

Thanks

**Comment by vkapur** [comment]
@piffarettig How did you get the Conversation ID of the User B? Isn't it unique each time?

**Comment by dhinag** [comment]
@piffarettig In your case, are you using Skype as the channel? I am working on a similar scenario, but using the Webchat. In case of Webchat, I cannot identify the user uniquely. Do you have any suggestions to take this forward?

**Comment by alexandrenunes-cs** [comment]
@chetanmekha do you have any example in nodejs? 
Is it possible to send a message to a specific Skype account? 

I'm using nodejs, and Dialogflow.

Thanks!

**Comment by RohanSaini** [comment]
hi,
I am using bot framework v3  and node.
I am saving user address on the first interaction on conversationUpdate.
bot.on('conversationUpdate', (message) => {
insertaddresstoDB(message)
});
function insertaddresstoDB(message) {
          DB.insertaddress(message.user.name, message.address)
            .then((result) => {
// some code           
            })
            .catch((error) => {
//some code
            });  
}

After this when I am trying to send any msg on this address I am getting Invalid channelID error.

     MainBotDB.getaddress(username)
      .then((result) => {
        var useraddress=JSON.parse(result);
 var msg = new builder.Message()
  .text('some message')
  .address(useraddress);
 bot.send(msg, function (err, useraddress) {
   console.log('done');
 });
      });

error : 
Error: Invalid channelId='skype'
    at D:\home\site\wwwroot\node_modules\botbuilder\lib\bots\UniversalBot.js:216:31
    at UniversalBot.tryCatch (D:\home\site\wwwroot\node_modules\botbuilder\lib\bots\UniversalBot.js:516:13)
    at D:\home\site\wwwroot\node_modules\botbuilder\lib\bots\UniversalBot.js:212:23
    at D:\home\site\wwwroot\node_modules\botbuilder\lib\bots\UniversalBot.js:536:17
    at D:\home\site\wwwroot\node_modules\async\lib\async.js:52:16
    at replenish (D:\home\site\wwwroot\node_modules\async\lib\async.js:314:29)
    at D:\home\site\wwwroot\node_modules\async\lib\async.js:326:29
    at D:\home\site\wwwroot\node_modules\async\lib\async.js:44:16
    at D:\home\site\wwwroot\node_modules\botbuilder\lib\bots\UniversalBot.js:207:21
    at D:\home\site\wwwroot\node_modules\botbuilder\lib\bots\UniversalBot.js:427:53
