### ISSUE TITLE
[Feature Request] set the activity locale from the facebook user's profile

### ISSUE THREAD

**Issue by picatextra** [Microsoft/BotBuilder#1959]
I need to localize messages to Facebook user , but Activity.Locale is not set as expected.
The work around i seen on #1056 work but i think the framework should do it alone.

**Comment by willportnoy** [comment]
@maxpert this https://github.com/Microsoft/BotBuilder/issues/1056 work would be done server-side for the Facebook channel.

**Comment by nwhitmont** [comment]
@picatextra are you using C# or Node SDK for BotBuilder?

**Comment by picatextra** [comment]
I'm using both  C# and NodeJs SDK for BotBuilder (different projects)
