### ISSUE TITLE
anything like ActionFilterAttribute that applies to async callbacks?

### ISSUE THREAD

**Issue by davidlfox** [Microsoft/BotBuilder#1960]
Working on a [chat game](https://github.com/davidlfox/DrugBot/issues/5) and I'm having trouble finding anything that can inject into callbacks similar to an ActionFilterAttribute would in MVC/Web API apps.

**Use case**: a user could be at any phase of a dialog (multiple callbacks deep,) and I'd like one or more commands to be available without having to insert if-statements all over the place. Not sure what's required here.

I found `AttributeString` that `LuisIntentAttribute` inherits, but its namespace looks like it might be intentionally named "internal." Not even sure if that's the solution here, since I would need something to consistently intercept a single phrase e.g. **inventory** which would display the players inventory even if they're in the middle of another dialog.

**Comment by willportnoy** [comment]
We generally recommend scorables for pervasive interruption scenarios - for example, here is the DeleteProfileScorable:

https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Microsoft.Bot.Builder/Dialogs/DeleteProfileScorable.cs#L49

Sorry for the delay in response - somehow I missed this item.
