### ISSUE TITLE
Unable to receive Messages send through session.send command at Bot Framework Emulator

### ISSUE THREAD

**Issue by pmsudhi** [Microsoft/BotBuilder#1961]
Hi ,
         Using a hello world node.js bot for testing. the problem is when i set APP ID and password(that i generated from portal), i am unable to receive the message back to the chat window. if i keep it empty, the bot works as expected. Code Snippet is as below     
```
var restify = require('restify');
var builder = require('botbuilder');
var server =restify.createServer();
server.listen(process.env.PORT || 1976,function()
{
    console.log('% Listenting to %s',server.name,server.url);
}
);
// Create chat bot
var connector = new builder.ChatConnector
(
    
    {appid: null,appsecret: null }
  // {appid: process.env.MY_APP_ID,appPassword: process.env.MY_APP_SECRET }
); 
var bot = new builder.UniversalBot(connector);



server.post('/api/messages', connector.listen());


bot.dialog('/',function(session)
{
    session.send("You said: %s", session.message.text);
});
```     
The resultant windows is as below     
![messageback](https://cloud.githubusercontent.com/assets/16379528/21632428/5a8e47f8-d26c-11e6-9569-37b9f0166365.PNG)      

But when I set APP ID and secret, iam not receiving session.send response, though it is hitting the break point there.     
The Debug Window out put is like this     

```
node --debug-brk=19336 --nolazy app.js 
Debugger listening on [::]:19336
% Listenting to restify http://[::]:1977
ChatConnector: message received.
ChatConnector: message received.
session.beginDialog(/)
/ - waterfall() step 1 of 1
/ - session.send()
/ - session.sendBatch() sending 1 messages
```     
![noresponse](https://cloud.githubusercontent.com/assets/16379528/21632733/10a1db70-d26f-11e6-99bf-72a93d18d7ab.PNG)

**Comment by Stevenic** [comment]
Are you configuring the emulator with the same APP ID & PASSWORD?

**Comment by Stevenic** [comment]
Closing this for now. Please feel free to comment with more details and i'll re-open.

**Comment by sanketwagh06** [comment]
Please help me regarding this issue. I am facing almost exactly the same issue. For me, it does not even respond on localhost. No AppID and PSWD provided.

This is what I see:
![screen shot 2017-06-05 at 2 20 57 pm](https://cloud.githubusercontent.com/assets/13947090/26799205/3d332ab0-49fa-11e7-9c70-a27ee7f06bc5.png)

ChatConnector: message received.
UniversalBot("*") routing "Hello" from "emulator"
Session.beginDialog(/)
/ - waterfall() step 1 of 1
/ - Session.send()
/ - Session.sendBatch() sending 1 message(s)

**Comment by eanders-MS** [comment]
Hi @sanketwagh06, Try bypassing ngrok for local addresses. You will find this setting under App Settings (under the vertical ... icon next to the address bar).

**Comment by sanketwagh06** [comment]
I have already bypassed. Issue still persists.

**Comment by eanders-MS** [comment]
How are you formulating your response message?

**Comment by sanketwagh06** [comment]
for now, it's just like this:

var bot = new builder.UniversalBot(connector, function (session) {
session.send("You said: %s", session.message.text);
}

**Comment by eanders-MS** [comment]
That looks fine. What is the value of the serviceUrl in the message sent to your bot? Click on any message in the emulator to see its JSON.

**Comment by sanketwagh06** [comment]
The value of the service url is 50715, to be precise it is:  http://127.0.0.1:50715

My end goal is to be able to send and receive images and map co-ordinates. But for now I just need the emulator to respond efficiently. (Just FYI).

**Comment by pranav-nadkarni** [comment]
I also have same issue. I even see output in console for session.send by running console.log(session.send("msg"));
 but it is not reaching webchat or Skype channels or test emulator... what am I missing ?

Please help

**Comment by chaudharynitin** [comment]
I am also facing same issue . Anyone found solution ? 

please help ...

**Comment by chaudharynitin** [comment]
I can see the response in console but the same is not printed by session.send.

restify listening to http://undefined:undefined
{ answers: [ { answer: 'Hello', questions: [Object], score: 1 } ],
  score: 1,
  entities: [ { score: 1, entity: 'Hello', type: 'answer' } ],
  intent: 'qna' }


Same code is working fine on local and emulator. I am facing issue in azzure (using node).

**Comment by garvitjoshi** [comment]
It works perfectly on the windows machine but on Ubuntu, I got the same issue.
