### ISSUE TITLE
[C#]Start a new Dialog when last dialog is expired or too old.

### ISSUE THREAD

**Issue by Johndgnzj** [Microsoft/BotBuilder#1962]
Hi

Is there any way to do "/deleteprofile" manually in messagesController.cs ?
cause some users might stop or stuck some where in a dialog, and after a while(maybe a day), he won't remember what should he do now.

So i store a timestamp in userdata and check it expired or not in messagesController every time.
like:
```C#
[ResponseType(typeof(void))]
public async Task<HttpResponseMessage> Post([FromBody]Activity activity)
{
    if (activity != null && activity.GetActivityType() == ActivityTypes.Message)
    {

            StateClient stateClient = activity.GetStateClient();
            BotData userData = await stateClient.BotState.GetUserDataAsync(activity.ChannelId, activity.From.Id);
            var lastTalk = userData.GetProperty<DateTime>("lastTalk");
            bool IsExpired = false;
            if (lastTalk != null)
                IsExpired = (lastTalk.AddMinutes(10) < DateTime.UtcNow);
            if (IsExpired)
            {
                // erase old ActionDialog or create new ActionDialog
                ....
            }
            userData.SetProperty<DateTime>("lastTalk", DateTime.UtcNow);
            await stateClient.BotState.SetUserDataAsync(activity.ChannelId, activity.From.Id, userData);
            await Conversation.SendAsync(activity, () => new ActionDialog());
    }
}
```

maybe there have better way to do this, would anyone help this issue?

**Comment by willportnoy** [comment]
that's certainly the easiest, most direct way.  In the later versions of the code, you could possibly provide an adaptor IBotDataStore to clear out storage that's "too old".

https://github.com/Microsoft/BotBuilder/blob/develop/CSharp/Library/Microsoft.Bot.Builder.Autofac/Dialogs/DialogModule.cs#L156

**Comment by Johndgnzj** [comment]
Hi willportnoy
Happy to receive your reply, but i still don't know the exactly code to "**erase old ActionDialog or create new ActionDialog**"

Can you give me so sample code?

**Comment by Johndgnzj** [comment]
Hi will pornoy
i find this method might help for  delete State ,
```
stateClient.BotState.DeleteStateForUser(activity.ChannelId, activity.From.Id);
```
but is this the only way to jump out from a expired dialog?
cause userData will be erase after i run this method too.

**Comment by willportnoy** [comment]
@Johndgnzj you can just clear out this key in the private conversation data bag - it's where the dialog state is stored:
https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Microsoft.Bot.Builder/Dialogs/DialogModule.cs#L57

**Comment by Johndgnzj** [comment]
Hi
The code didn't work , is any thing wrong?
```C#
StateClient stateClient = activity.GetStateClient();
BotData userData = await stateClient.BotState.GetPrivateConversationAsync(activity.ChannelId, activity.Conversation.id);
userData.SetProperty<String>("dialogState","");
await stateClient.BotState.SetUserDataAsync(activity.ChannelId, activity.From.Id, userData);
await Conversation.SendAsync(activity, () => new ActionDialog());
```

**Comment by willportnoy** [comment]
@Johndgnzj the key doesn't look cased correctly?  it should be "DialogState":

https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Microsoft.Bot.Builder/Dialogs/DialogModule.cs#L57

**Comment by Johndgnzj** [comment]
Hi Willportnoy

i clean it and save back to UserData, but user still stock in a dialog.

should eTag needed be clean too?

**Comment by willportnoy** [comment]
You have to clear the value for the "DialogState" key within the PrivateConversation data bag, not the User data bag, and then save the updated state bag to the state service.

**Comment by Johndgnzj** [comment]
Hi willportnoy

sorry my bad, i use wrong key to clear make this stupid issue.
use key "DialogState" then it work,thanks.
