### ISSUE TITLE
[MS Teams Mobile iOS & Android] Signin Card is not working in Teams mobile app - unsupported card response

### ISSUE THREAD

**Issue by manums** [Microsoft/BotBuilder#1963]
Signin card is shown as [unsupported card] in both teams app on android and iOS both. It used to work great few weeks back.

**Comment by maxpert** [comment]
From teams you mean Microsoft teams right?

**Comment by RichMoeMSFT** [comment]
Does your same bot display the card fine on client/web?  I tried a quick sample signin card and I'm getting "Something went wrong..." message on iOS but fine in client.

**Comment by manums** [comment]
It works on Windows Microsoft Teams client but not on phone(iOS\Android).

**Comment by martinjt** [comment]
For us it's not working in the windows client either.  in the web version, you get "unsupported button type: signin"... don't know if that helps.  You get the button, just clicking on it does nothing.

**Comment by carlosscastro** [comment]
@RichMoeMSFT, @maxpert any news on this?

**Comment by RichMoeMSFT** [comment]
@manums @martinjt The "signin" type is indeed broken, but you can replace it with type: openURL.  Right now in Teams, the functionality is equivalent.
