### ISSUE TITLE
Source code for direct line

### ISSUE THREAD

**Issue by sebnema** [Microsoft/BotBuilder#1964]
When I checked webchat source code, It seems it is still dependent on the dirrectline api, Is that correct? https://github.com/Microsoft/BotFramework-WebChat/blob/master/src/directLine.ts

If yes, That means we still have security compliance issue due to whole conversation will pass through DirectLine Api. Is there a plan to release source code?

I am trying to avoid an architecture like this.
![hybridbotcommunicationdiagram](https://cloud.githubusercontent.com/assets/10426499/21639162/46b217ae-d277-11e6-8bfa-62c0df1e3160.jpg)

**Comment by dandriscoll** [comment]
Hi @sebnema, yes, the Web Chat file you linked is a Direct Line client, and we will be publishing an NPM package for it soon (although it will likely contain the entire control, not just the Direct Line client). We do not currently have plans to publish the service code.

**Comment by dandriscoll** [comment]
Yes, all Web Chat messages pass through the Direct Line service. The Direct Line backend is the service used for both the Direct Line and Web Chat channels.

**Comment by sebnema** [comment]
@dandriscoll, @billba Is it possible to extract the DL source code from emulator and package it separately, as mentioned here?
[BotFramework-Emulator-Issue 54](https://github.com/Microsoft/BotFramework-Emulator/issues/54)

**Comment by dandriscoll** [comment]
Closing as we have addressed the question. Please at-mention or file a new issue if you'd like to discuss further.

**Comment by pavei** [comment]
@dandriscoll any news about the code? Now we need to pay for using DirectLine Service..
