### ISSUE TITLE
[Feature Request] Enable ability/guidance to add registrations to Autofac container without Update

### ISSUE THREAD

**Issue by tillig** [Microsoft/BotBuilder#1966]
[Autofac is working on deprecating the `ContainerBuilder.Update()` mechanism](https://github.com/autofac/Autofac/issues/811) because it can create application inconsistency and doesn't do all the steps a standard container build does. [There is a discussion explaining this in detail.](https://github.com/autofac/Autofac/issues/811)

[The bot framework exposes an `IContainer`](https://github.com/Microsoft/BotBuilder/blob/8f0d6bbc1ef0fcef99b04560391384aba8fcde15/CSharp/Library/Microsoft.Bot.Builder/Dialogs/Conversation.cs#L49) and it appears the guidance [is to use `Update()` as the way to get custom registrations in place.](https://github.com/Microsoft/BotBuilder/blob/10893730134135dd4af4250277de8e1b980f81c9/CSharp/Tests/Microsoft.Bot.Builder.Tests/Script.cs#L66)

Based on [comments on the Autofac discussion](https://github.com/autofac/Autofac/issues/811#issuecomment-270440944) it sounds like this may be changing, but I thought it would be good to track the issue here to ensure it doesn't get lost. We/I would be happy to help talk through some of the use cases and see if there are different options available that would allow for custom registrations while not actually changing the root container contents post-build.

**Comment by andreesteve** [comment]
I think the simplest solution would be instead of hard-coding modules in the source code, move them to a [configuration file (see Autofac docs)](http://docs.autofac.org/en/latest/configuration/xml.html).

That way, the implementation service could register its own modules just by adding them to the configuration file.

As a backward compatibility solution, if no configuration file is found, then we could fallback to the existing hard-coded module definition in code.

**Comment by sgellock** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botbuilder-channels/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
