### ISSUE TITLE
Bot response issues with IE11

### ISSUE THREAD

**Issue by RasheedSiriyala** [Microsoft/BotBuilder#1968]
Hi,
We have developed one bot application and configured with webchat. It is working fine in **Microsoft Edge** & **Chrome** but responding multiple posts in **IE11**.

In IE11 its working fine when LUIS intent posting simple text messages as shown below,
![image](https://cloud.githubusercontent.com/assets/12622554/21676690/be543f68-d35c-11e6-834b-52243d538e22.png)
But when LUIS intent returning Cards with multiple buttons and, its posting text of first button (e.g Microsoft Secure) along with current post (e.g. ok/sorry) as shown below,
![image](https://cloud.githubusercontent.com/assets/12622554/21676782/2913cd50-d35d-11e6-93dd-b83c1b88e20d.png)
![image](https://cloud.githubusercontent.com/assets/12622554/21676812/4f766e30-d35d-11e6-9b70-0d6e8679b7eb.png)
When I entered ok, posting Microsoft Secure along with ok and bot responding result of both ok post and Microsoft Secure post as shown below,
![image](https://cloud.githubusercontent.com/assets/12622554/21676876/9f0c72dc-d35d-11e6-9e9e-f82b8ff54fd0.png)
Next I enetered sorry, posting Microsoft Secure along with sorry and bot responding result of both sorry post and Microsoft Secure post as shown below,
![image](https://cloud.githubusercontent.com/assets/12622554/21676925/dac926f8-d35d-11e6-9997-6351f858eb55.png)

Is it common behavior with IE11? If not where we might have gone wrong?

Thanks,
Rasheed

**Comment by maxpert** [comment]
Hmmm makes me wonder if its happening due to some HTTP push/Websocket issue have you tried looking into the network inspector? It might give you a deeper insight @danmarshall might be able to add more.

**Comment by danmarshall** [comment]
Hello @RasheedSiriyala do you still see this issue in the latest release?

**Comment by nwhitmont** [comment]
@RasheedSiriyala BotBuilder-WebChat is maintained as a separate project.  If you're having issues, the best thing to do is head on over to https://github.com/Microsoft/BotFramework-WebChat and open a new issue there.
