### ISSUE TITLE
Bot c#: How can i call method from button click and pass object

### ISSUE THREAD

**Issue by msBot1111** [Microsoft/BotBuilder#1969]
I'm creating Bot in c#, which will show to users some search results and after that i need to ask the user if the answer is ok or not, to get feedback from users. I want to have button yes/no and if user clicks yes to save the results from the search.

**Comment by maxpert** [comment]
Have you looked at [Forms](https://docs.botframework.com/en-us/csharp/builder/sdkreference/forms.html)? I guess what you are looking for is prompt.

**Comment by willportnoy** [comment]
Actually, you can use Prompt.Confirm - much simpler - to collect a yes/no answer with buttons.

**Comment by msBot1111** [comment]
yes, I've tried  Prompt.Confirm but there i can't pass the result from search to call another method

**Comment by maxpert** [comment]
@msBot1111 did that solve your issue?

**Comment by msBot1111** [comment]
yes thanks

**Comment by willportnoy** [comment]
I'm going to close this issue for now, but feel free to open a new issue for further discussion.
