### ISSUE TITLE
[Samples] Please provide exported LUIS apps for Samples that use LuisDialog.

### ISSUE THREAD

**Issue by antonvidishchev** [Microsoft/BotBuilder#197]
It is great that samples point to existing working models now, but it will be useful to have exported app as well.
It will help understanding your practices how you train your model, as well it will provide a full deployable sample.

**Comment by msft-shahins** [comment]
I just added the sample pizza bot exported luis app in the following [commit](https://github.com/Microsoft/BotBuilder/commit/a7a61acbd24eb50122cbafad0fbc10f717263c66). Here are the links to other exported apps: [todoBot](https://github.com/Microsoft/BotBuilder/blob/master/Node/examples/todoBotLuis/models/TodoBot.json) and [stockBot](https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Samples/Build-2016/Stock-LUIS/Model/Stock%20Model.json).

**Comment by antonvidishchev** [comment]
Thanks a lot!
It would be great if you could also merge this from develop to master :)

**Comment by msft-shahins** [comment]
@antonvidishchev We will merge changes to master when we are ready for our next release. It will be in the coming days. :-)
