### ISSUE TITLE
Microsoft Teams: UpdateActivity expected use case with postBack

### ISSUE THREAD

**Issue by james-lawrence** [Microsoft/BotBuilder#1972]
I just attempted to take a message I recieved via a button click (using postBack, I know it is not fully implemented), seems like the activity ID returned doesn't match the one returned by the SendToConversation.

My question is the intention that when a button is click that the message received by the http handler will have the same ID as the one returned when I sent the original message?

**Comment by RichMoeMSFT** [comment]
When you say you sent the original message, you mean you replied to a message?  Currently Teams can only reply to messages, and in this case, the message you received by your bot should have the activityID in the replyToId.

**Comment by james-lawrence** [comment]
I mean bot sends a message to a user with a button. That message is given id A (as returned by the post to the framework endpoint). Then the user clicks the button. I'd expect postBack to return to me a message with id A again saying 'hey this message's button was clicked'.

Currently I get a different id when I receive the button click from the user.

An example use case would be to clear out the buttons once a selection has been made.

**Comment by carlosscastro** [comment]
@james-lawrence are you still experiencing this issue? Let us know and we can follow up if so.

**Comment by james-lawrence** [comment]
Unknown, havent tested that particular piece of functionality. the new invoke method solves part of the issue.

**Comment by carlosscastro** [comment]
@james-lawrence that makes sense. Closing this now then, but feel free to reopen if you want to revisit.
