### ISSUE TITLE
"Required property 'participants' not found in JSON

### ISSUE THREAD

**Issue by intermension** [Microsoft/BotBuilder#1973]
Looking at the SimpleIVRBot and it fails in 

`CallingConversation. SendAsync(HttpRequestMessage toBot, CallRequestType callRequestType)`

on line:

` res = await bot.CallingBotService.ProcessIncomingCallAsync(parsedRequest.Content);`

because ProcessIncomingCallAsync passes in parsedRequest.Content for deserialization but the parsedRequest.Content has no participants field and

`Microsoft.Bot.Builder.Calling.ObjectModel.Contracts.Conversation`

requires one:

        [JsonProperty(Required = Required.Always)]
        public IEnumerable<Participant> Participants { get; set; }

This throws a deserialization exception:

"Required property 'participants' not found in JSON: 

Is the SDK out of sync with dev.botframework.com?

**Comment by kraghavk** [comment]
I just ran into this issue. No the SDK is perfectly fine, but the readme.md for SimpleIVRBot is wrong!

Basically the value for *Microsoft.Bot.Builder.Calling.CallbackUrl* app setting in web.config should be set to */api/calling/callback* and NOT */api/calling/call*. The documentation is misleading in this case.
