### ISSUE TITLE
[Localization] Inconsistent localization handling for Node.js SDK Prompts.choice()

### ISSUE THREAD

**Issue by josephktcheung** [Microsoft/BotBuilder#1976]
From [documentation](https://docs.botframework.com/en-us/node/builder/chat/localization#localizing-prompts): 
> Internally, the SDK will call session.preferredLocale() to get the users preferred locale and will then use that in a call to session.localizer.gettext() to map the message ID to its localized text string. There are times where you may need to manually call the localizer. For instance, the enum values passed to Prompts.choice() are never automatically localized so you may need to manually retrieve a localized list prior to calling the prompt:

However, from [prompts.ts](https://github.com/Microsoft/BotBuilder/blob/master/Node/core/src/dialogs/Prompts.ts#L333) if `ListStyle` is of type `list`, it uses `args.localizationNamespace` to localize choice options. Why is `ListStyle.list`'s localization handling different from other list styles? Should "enum values passed to Prompts.choice() are never automatically localized" sentence in documentation be updated? Thanks.

**Comment by Stevenic** [comment]
That's a good point. I'll investigate to understand why we do it differently in that case. Probably has to do with yes/no prompts.

**Comment by nwhitmont** [comment]
@Stevenic any updates on Prompts.choice() localization handling?

**Comment by nwhitmont** [comment]
depreciated
