### ISSUE TITLE
Skype: Not able to send file attachment to user

### ISSUE THREAD

**Issue by BirenPanigrahi** [Microsoft/BotBuilder#1980]
I am not able to send file attachment from BOT to user in Skype.

I am using BOT builder version 3.5.0.

Below is my code.

ConnectorClient connector = new ConnectorClient(new Uri(activity.ServiceUrl));
Activity reply = activity.CreateReply("blah");
reply.Attachments = new List<Attachment>();
Attachment attach = new Attachment();

attach.ContentType = "application/pdf";
// I can browse the below URL in browser and access the PDF
attach.ContentUrl = "https://test.azurewebsites.net/Image/Test.pdf"; 
attach.Name = "Test.pdf";
attach.Content = "Test";
attach.ThumbnailUrl = attach.ContentUrl;
reply.Attachments.Add(attach);
await connector.Conversations.ReplyToActivityAsync(reply);

**Comment by nickcordrey** [comment]
Send files from a user to a bot is not yet supported. We are aware of this gap and will address it as early as we can.

**Comment by abhishan** [comment]
@nickcordrey 
I assume you meant send files **from Bot to User**.
This is something that clients are asking for. Bots can send image as attachment, but clients would also like the bot to send a file to the user.
Example scenario: User asks bot information regarding some product and Bot send the Product brochure.

**Comment by YigitCiray** [comment]
Is there any update about solution?

**Comment by khushboo22singh** [comment]
any updates? I am also facing the same issue. My BoT is able to send attachments, when I test same on Emulator, bot not on skype. Please, help me out!

**Comment by ellnino50** [comment]
This would be great. Even if its a web hosted PDF. Currently my bot returns "Failed with message: Unknown attachment type"

The WebChat works perfectly tough.

**Comment by srichakradhar** [comment]
Same issue here. Any updates?

**Comment by odysseus1973** [comment]
I have same issue. How to send an .docx attachment to user?

**Comment by Ma3yTa** [comment]
@nickcordrey hi. any update on it?

**Comment by Ma3yTa** [comment]
@nickcordrey I am getting Unknown mime type for application/pdf and application/octet-stream in Skype

**Comment by Puneetjoshi24** [comment]
I am also facing the same issue in sending pdfs. Any updates?

**Comment by leungkimming** [comment]
I am also facing the same issue. Both bot framework and Skype are Microsoft products. My boss is going to kill me for using bot framework and Skype. Please help!!!
