### ISSUE TITLE
[Feature Request] Payments inside bot

### ISSUE THREAD

**Issue by spreddy2714** [Microsoft/BotBuilder#1982]
I am building an order placing application, where user have to checkout his order with some or other payment method. How can I perform this action securely using bot framework?

Can I store prompt and store payment details in bot securely?
Is there any other payment method exists to perform it?

**Comment by nwhitmont** [comment]
Payments via Bot Framework are currently under development.  Look forward some announcements on this subject mid-2017.

**Comment by nwhitmont** [comment]
Payments in Bot Framework have been announced today at Build 2017!

Find out more about Payments and other [new Bot Framework features here.](https://blog.botframework.com/2017/05/10/Build/)

Where to go from here:
- [Introduction to Bot Framework Payments](https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-request-payment)
- [Learn more about Microsoft Sellers program](https://seller.microsoft-int.com/en-us/seller)

**Comment by michaelhutchful** [comment]
Thanks for the link

Sent from Mail for Windows 10
