### ISSUE TITLE
YouTube Video in bot emulator

### ISSUE THREAD

**Issue by sgomaram** [Microsoft/BotBuilder#1984]
Hi,
I'm trying to play a Youtube video in emulator using below code. It just shows player but doesn't play or open the actual video. Am I missing something ?

```
Activity replyToConversation = activity.CreateReply("Should go to conversation, with a hero card");
replyToConversation.Attachments.Add(new Attachment(contentType: "video/mp4", name: "Simple Attachment Name", thumbnailUrl: "https://s29.postimg.org/ei98jsp7r/My_Bot.jpg", contentUrl: "https://youtu.be/A9Vu9n7YxrI"));
```

![image](https://cloud.githubusercontent.com/assets/23454390/21741359/32611974-d4f9-11e6-9fcd-de0519135714.png)

**Comment by maxpert** [comment]
I think right now it's not supported, whether it should be implemented or not is another topic of discussion, because in my head videos get noisy really quick. @danmarshall would be able to add more.

**Comment by danmarshall** [comment]
Thanks for the note @sgomaram this would be a very cool feature!
cc @eanders-MS @billba

**Comment by danmarshall** [comment]
Closing this issue here and tracking it at the source: https://github.com/Microsoft/BotFramework-WebChat/issues/272
