### ISSUE TITLE
Add implementation of IDialog for Wit.ai and API.ai

### ISSUE THREAD

**Issue by Ma3yTa** [Microsoft/BotBuilder#1986]
Add free alterative of LUIS implementation of IDialog

http://wit.ai
http://api.ai

**Comment by GanadiniAkshay** [comment]
An option to use api.ai
https://www.npmjs.com/package/api-ai-recognizer

**Comment by Ma3yTa** [comment]
@GanadiniAkshay thanks. Good to have it for .Net

**Comment by adebisi-fa** [comment]
@Ma3yTa  There is a prototype of LUIS implementation for [Wit.Ai (C#) here](https://github.com/adebisi-fa/Bot.Builder.WitAi).  It implements the **ILuisService** for [Wit.Ai](http://wit.ai).  Sample will be added to the repo, asap.  Hope it helps.

**Comment by Ma3yTa** [comment]
@adebisi-fa thank you very much. good work!

**Comment by Ma3yTa** [comment]
@adebisi-fa I added implementation of ILuisService for ApiAI [here](https://github.com/Ma3yTa/Bot.Builder.ApiAi). Feeil free to Fork
