### ISSUE TITLE
It is possible to send data through the Chat Control (iframe)?

### ISSUE THREAD

**Issue by Lipa9963** [Microsoft/BotBuilder#1987]
I'm investigating the possible use of a certain Snrio:
Suppose my client  click on link that leads to my  Bot site Contains the Chat Control. 
the link also contains user Id (POST). 
so it is possible to send the bot this user id  as soon as the customer enters the site? so the Bot can perform a specific process Against this User?

Thanks

**Comment by maxpert** [comment]
Sounds like really valid scenario, @danmarshall is it possible for someone to pass data to chat control iframe? I am not sure though how would the interoperability will work with this.

**Comment by Lipa9963** [comment]
in addition, i know that i can use Direct Line API but It means I'll have to implement full client side (for example if the API (from bot side) send Cards with buttons to the client the user see only text and if i want it to show like in the Chat control or like in the  emulator i should build this.. ) so if i can use the Built chat control and still Send through information It can be very effective.

**Comment by danmarshall** [comment]
Hi @Lipa9963 yes you can pass these additional URL parameters to your webchat iframe:
* userid
* username

This needs to be added to the documentation [here](https://docs.botframework.com/en-us/support/embed-chat-control2/) and in the dev portal.

**Comment by Lipa9963** [comment]
@danmarshall Works. Thanks!

**Comment by praveenrengarajan** [comment]
@Lipa9963  how do you achieved this? Like this?
`<iframe src="https://webchat.botframework.com/embed/smilesbot?s=<secret_code>&amp;userid=1234&amp;username=Praveen&#10;" style="height: 502px; max-height: 502px;"></iframe>`

**Comment by Lipa9963** [comment]
<iframe id="myFrame" src='https://webchat.botframework.com/embed/
smilesbot?s=secret_code&username=admin&userid=1234'></iframe>

**Comment by eanders-MS** [comment]
Sounds like this issue has been resolved. Closing now. If I'm in error, please reopen!

**Comment by insanediv** [comment]
Hi guys,
how can I read such parameters from the bot side?
Thank you very much

**Comment by danmarshall** [comment]
@insanediv is your bot in Node or C# ?

**Comment by insanediv** [comment]
Hi @danmarshall it is a node bot

**Comment by danmarshall** [comment]
@insanediv see https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node/core-GetConversationMembers

**Comment by insanediv** [comment]
@danmarshall is it possible to use this mechanism to pass arbitrary parameters to the bot via the web chat embed code?

**Comment by danmarshall** [comment]
@insanediv no. For arbitrary values, you will need to host your own custom webchat page.
See the "backchannel" in the WebChat repo [readme](https://github.com/Microsoft/BotFramework-WebChat#the-backchannel) and [example](https://github.com/Microsoft/BotFramework-WebChat/blob/master/samples/backchannel/index.html).

**Comment by insanediv** [comment]
@danmarshall Thank you very much. 
I managed to pass custom parameters to my bot, but have another question:
_How is it possible to store such parameters to the ```session.userData``` object?_ 

 I show you my code:

**Client side**
```
 botConnection.postActivity({type: "event",
                             value: "customarg", 
                             from: {id: "me" }, 
                             name: "customEvent"})
                            .subscribe(id => console.log("success"));
```
**Server side**
```
bot.on("event", function (event) {
    var msg = new builder.Message().address(event.address);
    if (event.name === "customEvent") {
        // HOW CAN I STORE event.value IN session.userData ? 
        console.log(event.value);
    }
});
```

Thank you again

**Comment by insanediv** [comment]
I finally managed to solve this. For anyone that needs please visit
[my github page](https://github.com/insanediv/microsoft-bot-framework-webchat-custom-parameters)

**Comment by kds-snyder** [comment]
For those who would like to read the user ID and user name from a C# bot, they are available in the turn context, which in my bot is available in methods 
`OnMessageActivityAsync(ITurnContext<IMessageActivity> turnContext, CancellationToken cancellationToken)` in class `DialogBot.cs`, and in `OnMembersAddedAsync(IList<ChannelAccount> membersAdded, ITurnContext<IConversationUpdateActivity> turnContext, CancellationToken cancellationToken)` in class `QnABot.cs`.

In these methods, `turnContext.Activity.From.Id` contains the passed-in user ID, and `turnContext.Activity.From.Name` contains the passed-in user name.

**Comment by noamanag** [comment]
> @insanediv see https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node/core-GetConversationMembers

I couldn't open this link, 
any idea how I could access the data passes in the iframe src in the bot?
I am using nodejs
thanks
