### ISSUE TITLE
[C#] Setting ConversationData value to null

### ISSUE THREAD

**Issue by jsiegmund** [Microsoft/BotBuilder#199]
I was looking for a way to clear out previously set ConverdationData. The IBotDataBag doesn't support removing values, so I though I'd just set it to null instead. Got an error trying to do that, which is caused by this line: 

`var token = JToken.FromObject(value);`

in BotData.cs (line 175). FromObject on JToken doesn't support null as input. Easily resolvable by setting the value to new object or something, but it shouldn't break like this. Also, it would be nice to have a way to remove items from the bag again when required.

**Comment by tomlm** [comment]
The reason we don’t use null is because we allow developers to respond with messages without setting the botdata field.
This comes through as a null, and so we model null as “no change”.

If you want to clear it set it to an empty object

**Comment by willportnoy** [comment]
IBotDataBag also has a RemoveValue method to remove a specific key-value pair:

https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Dialogs/IBotDataBag.cs#L73

**Comment by jsiegmund** [comment]
Guess I need to update my version :) Thanks guys, clear explanation and solution.
