### ISSUE TITLE
Channel detection

### ISSUE THREAD

**Issue by spreddy2714** [Microsoft/BotBuilder#1990]
How do I detect a message source channel like skype/messenger/slack in code in order to compose channel specific messages using nodejs?

**Comment by maxpert** [comment]
If you inspect the incoming payload it's part of message. Read https://docs.botframework.com/en-us/csharp/builder/sdkreference/routing.html for more details.

**Comment by maxpert** [comment]
Let me know if it works for you

**Comment by eanders-MS** [comment]
@spreddy2714 you can find the channel name in `session.message.source`
