### ISSUE TITLE
Get UserId ApiController DirectLine

### ISSUE THREAD

**Issue by whatdis2** [Microsoft/BotBuilder#1992]
The user is already logged in, in  the website using UserManager (standard MVC auth.). I want to get the user id.
Tried to use `RequestContext.Principal.Identity.GetUserId()` but this is null (although 'authenticated' is true (because of the `BotAuthentication`)). The header of the ApiController is like this:

```
[BotAuthentication]
public class ChatBotMessagesController : BaseApiController
```

If the user is normally logged via the 'UserManager', how to get his information? I thought of making a call from the View to the 'ApiController', but is not ideal since I will have to create a static variable in the ApiController. I also attempted to create a base class, but the User is null from here as well:
```

   public class BaseApiController : ApiController
   {
      private ApplicationUser _member;

      public ApplicationUserManager UserManager
      {
         get { return HttpContext.Current.GetOwinContext().GetUserManager<ApplicationUserManager>(); }
      }

      public string UserIdentityId
      {
         get
         {
            var user = UserManager.FindByName(User.Identity.Name);
            return user.Id;
         }
      }

      public ApplicationUser UserRecord
      {
         get
         {
            if (_member != null)
            {
               return _member;
            }
            _member = UserManager.FindByEmail(Thread.CurrentPrincipal.Identity.Name);
            return _member;
         }
         set { _member = value; }
      }

   }
```
Also added the user id/name when he/she logs in to the website:
```
public async Task<ClaimsIdentity> GenerateUserIdentityAsync(UserManager<ApplicationUser> manager)
{
   // Note the authenticationType must match the one defined in CookieAuthenticationOptions.AuthenticationType
   var userIdentity = await manager.CreateIdentityAsync(this, DefaultAuthenticationTypes.ApplicationCookie);
   // Add custom user claims here
   //var identity = new ClaimsIdentity(OAuthDefaults.AuthenticationType);
   **userIdentity.AddClaim(new Claim("UserName", userIdentity.Name));**
   **userIdentity.AddClaim(new Claim("UserId", userIdentity.GetUserId()));**
   return userIdentity;
}
```
But still no access from the BotFramework ApiController.

**Comment by dandriscoll** [comment]
Hi @whatdis2, users don't visit your bot's endpoint directly, so website authorization attributes won't do anything.

To log a user in, you must send them a sign-in link. An example that illustrates this is AuthBot, and you should take a closer look to see whether this works for your user experience and security requirements: https://github.com/MicrosoftDX/AuthBot

**Comment by dandriscoll** [comment]
Closing as the AuthBox sample is the right way to solve this problem. Be sure to confirm it meets your UX and security requirements.
