### ISSUE TITLE
ActivityTypes.ConversationUpdate Recipient/From name is same

### ISSUE THREAD

**Issue by b4usat** [Microsoft/BotBuilder#1994]
I need to send a greeting message to all users who starts chat with my bot, As per suggestion in this forum https://github.com/Microsoft/BotBuilder/issues/1811 i used `ConversationUpdate` activity for this. In my case I will set the user who is logged in into the Bot state for the user id. But to retrieve that state value, the  Recipient/From id from the `ConversationUpdate` activity is not allowing. Both these id's are same. But in Activity type messages i can get different Id's.

**Comment by b4usat** [comment]
Can i have any update please??

**Comment by eanders-MS** [comment]
Hi @b4usat, in your `ActivityTypes.ConversationUpdate` handler, assign the incoming activity to a `IConversationUpdateActivity`. This will give you access to the activity's `MembersAdded` list. The new user will appear in this list.

A detail to be aware of: Your bot may appear in the `MembersAdded` list as well. You may want to filter your bot by checking `activity.MembersAdded[i].Id != activity.Recipient.Id`.

**Comment by Andrea-Orimoto** [comment]
@b4usat did the above answer your question?

**Comment by b4usat** [comment]
@Andrea-Orimoto To answer you 'No'. In  our case we are using webchat control which is hosted in our server not the direct url from MS. And so we are setting the user id as params to the webchat url. But unfortunately am not able to retrieve the same id from Activity class in `ConversationUpdate `event. Instead i was getting an auto-gen id. In the same case i can retrieve the user id in the `Activity Type Message`.

**Comment by b4usat** [comment]
I'm not getting any help for this. Can somebody please help.

**Comment by msft-shahins** [comment]
This is ConversationUpdate activity received from channel and SDK doesn't do any transformation on the fields received from the channel. @danmarshall can you help with the ConversationUpdate activities generated by webchat control?

**Comment by nwhitmont** [comment]
@b4usat are you using C# or Node SDK?

**Comment by nwhitmont** [comment]
reopen if you're still experiencing the issue.
