### ISSUE TITLE
CardAction on HeroCard

### ISSUE THREAD

**Issue by sgomaram** [Microsoft/BotBuilder#1995]
I have below code to show a hero card. When I tap on hero card, it does not do openURL / playVideo.
I have CardAction on both image as well as HeroCard, non of them work in emulator. I also tried removing each of them, but no luck.
I remember it working sometime back.. but I might have done some code changes, which I could not figure-out. Is there anything wrong in code ?
```
            Activity replyToConversation = activity.CreateReply("Should go to conversation, with a hero card");
            replyToConversation.Recipient = activity.From;
            replyToConversation.Type = "message";
            replyToConversation.Attachments = new List<Attachment>();

            List<CardImage> cardImages = new List<CardImage>();
            List<CardAction> cardButtons = new List<CardAction>();
            CardAction plButton = new CardAction(value: "https://en.wikipedia.org/wiki/Pig_Latin", title: "WikiPedia Page", type: "openUrl");
            CardImage cardImage = new CardImage(url: "https://s29.postimg.org/ei98jsp7r/My_Bot.jpg", alt: "CardImage alt", tap: plButton);
            cardImages.Add(cardImage);
            cardButtons.Add(plButton);

            HeroCard plCard = new HeroCard()
            {
                Title = "I'm a hero card",
              //  Subtitle = "Pig Latin Wikipedia Page",
                Images = cardImages,
              //  Buttons = cardButtons,
                Text = "This is HeroCard text",
                Tap = new CardAction(type: "playVideo", title: "HeroCard tap", value: "https://youtu.be/A9Vu9n7YxrI")
            };
            Attachment plAttachment = plCard.ToAttachment();
            replyToConversation.Attachments.Add(plAttachment);
```

**Comment by LarsLiden** [comment]
Confirmed that they are not working in emulator.  @eanders-MS can you take a look?

**Comment by eanders-MS** [comment]
This is a current limitation of the new webchat control. Issue is being tracked here: https://github.com/Microsoft/BotFramework-WebChat/issues/271. @danmarshall for reference.

**Comment by danmarshall** [comment]
@sgomaram perhaps they were working in the previous Window-only Emulator?

**Comment by sgomaram** [comment]
@danmarshall sorry for the late response.

Yes, it was Windows emulator.. File name was something like "Bot Framework Channel Emulator.application".

I'm not sure of playVideo, but openURL worked with previous emulator. When I click on card image, it used to open a URL that was assigned to CardAction.

**Comment by eanders-MS** [comment]
This issue is better-tracked over at the WebChat repo, so I've created an issue for it there: https://github.com/Microsoft/BotFramework-WebChat/issues/335

**Comment by JasonSowers** [comment]
@sgomaram I am closing this issue as it has been resolved by creating an issue in the Web chat repo.  please reach out if you feel this issue requires more attention.
