### ISSUE TITLE
Passing extra parameter to ResumeAfter (delegate)

### ISSUE THREAD

**Issue by piffarettig** [Microsoft/BotBuilder#1997]
I am using context.Wait (where context is a IDialogContext) to suspend the current active dialog until a new message arrives, of course passing as a parameter the delegate corresponding to the ResumeAfter function.

`context.Wait(AfterInputReceived);`
` private async Task AfterInputReceived(IDialogContext context, IAwaitable<IMessageActivity> result)...`

I want to pass an extra parameter to the instruction before. **How can I achieve that?** I ve thinking of curryng the function using a lambda expression, but this couldnt be done because I dont own the parameters being passed to the delegate (specifically the result):

`context.Wait((context,result) => AfterInputReceived(context,result,EXTRA_PARAM);`

Thanks!

**Comment by willportnoy** [comment]
That's a closure that captures the environment, and compiler-generated closures are not marked serializable by default:

https://docs.botframework.com/en-us/technical-faq/#ensure-that-all-dialogs-are-serializable

1. You can store the EXTRA_PARAM in the dialog instance across the method that calls Wait and the ResumeAfter method.
2. You could enable the reflection serialization surrogate.

Did I understand your question correctly?

**Comment by piffarettig** [comment]
I think we re on the same track :)

Option 1 is the one that sounds easier (and the workaround I did to accomplish this), but of course, that is not very clean. It implies adding a new property for every each param I want to use.

Could you please explain a little bit option 2 ?

Thanks as usual @willportnoy !!!

**Comment by willportnoy** [comment]
Here is some sample code to enable the reflection serialization surrogate:

https://github.com/Microsoft/BotBuilder/issues/833#issuecomment-265549510

It should enable you to serialize that closure that captures the environment (which the compiler converts to a non-serializable class with data members) by serializing that generated class through reflection.

**Comment by piffarettig** [comment]
Thanks! Seems simple. Will check it whenever I got a couple of mins.
