### ISSUE TITLE
Bot Application template

### ISSUE THREAD

**Issue by zabom** [Microsoft/BotBuilder#200]
Hi!
I have no idea of what why I´m getting this error(s) but I´m getting them and would like some help.

**package installation Error**

Package Installation Error
Could not add all required packages to the project. The following
packages failed to install from
'C:\Users\zabom\AppData\Roaming\Microsoft\VisualStudio\14.0\projectTemplatesCache\Visual 
C#\Bot Application.zip':
Microsoft.AspNet.WebApi5.23 : Solution is not opened or not saved.
Please ensure you have an open and saved solution.
Microsoft.AspNet.WebApi.Client5.23 : Solution is not opened or not
saved. Please ensure you have an open and saved solution.
Microsoft.AspNet.WebApi.Core5.23 : Solution is not opened or not
saved. Please ensure you have an open and saved solution.
Microsoft.AspNet.WebApi.WebHost5.23 : Solution is not opened or
not saved. Please ensure you have an open and saved solution.
Microsoft.Bot.Connector1.0.0.0: Solution is not opened or not saved.
Please ensure you have an open and saved solution.
Microsoft.Rest.ClientRuntime1.8.2: Solution is not opened or not
saved. Please ensure you have an open and saved solution.
Microsoft.WindowsAzure.ConfigurationManager31.0: Solution is not
opened or not saved. Please ensure you have an open and saved
solution.
NewtonsoftJson.8A.2: Solution is not opened or not saved. Please
ensure you have an open and saved solution.

then I can press OK but nothing comes up. I can find messagecontroller and open from solution explorer but it has 26 errors and when I run it in  bot framework emulator it just answers that something went wrong.

Thanks.
//Zabom

**Comment by tomlm** [comment]
Make sure your nuget packagemaneger is enabled and configured correctly

**Comment by Trapulo** [comment]
same problem!

**Comment by SoftwareOnSailboats** [comment]
Same problem. Configured nuget package manager to check and download packages. The problem occurs when opening a new project from the Bot Application template.

**Comment by vechamkarunakar** [comment]
When you download zip from the source, you need to unblock(file properties and check unblock) the zip file and also check in visual studio --> tools --> project and solutions --> user project template location.

**Comment by noxsicarius** [comment]
Issue still relevant. I have updated all of my software, checked nuget settings, unblocked all items, made sure the directory is correct in both the settings and the actual placement of the files. I get the posted above error whenever creating a new project with the framework. The error is odd considering it says a solution is not opened and saved. It seems to be looking for a pre-existing/saved project to even attempt to add the template.

**Comment by noxsicarius** [comment]
From looking through a number of items I have found that this is a NuGet bug that has been seen in many projects and github is riddled with open issues on projects about this. An issue has been opened by a project owner that has verified the problem and can be found here https://github.com/NuGet/Home/issues/3843

**Comment by noxsicarius** [comment]
Now for the fix:
This problem is caused by an unsaved solution (obvious from the error), but you can not save the solution until after building it. This is a known issue with NuGet, not this project. To fix this error you must enable VS to save your project immediately when created.
** FIX **
go to Tools > Options > Projects and Solutions and check the *Save new projects when created* checkbox. Now create a NEW project and it should work perfectly.
