### ISSUE TITLE
facebook: webhook opt-in callback.

### ISSUE THREAD

**Issue by pfloresl** [Microsoft/BotBuilder#2001]
Hi, how could i detect from my node app and botbuilder the "opt-in" webhook event: messaging_optins. 
I need to detect when user is sign coming in via FB browser plugin in.

any of these would be good too:
- Checkbox Plugin
- Send to Messenger
- Message Us

thank you.

**Comment by OptimusRhine** [comment]
@pfloresl Did you ever figure out a way to detect the opt-in webhook event? I'm currently facing this same issue.
