### ISSUE TITLE
[Feature Request] Knowing when a Conversation has Ended via Direct Line events

### ISSUE THREAD

**Issue by Kothakapu** [Microsoft/BotBuilder#2002]
I am using **DirectLine channel** and embedding the **bot web chat** into a page.
I am getting ConversationUpdate Activity when the page is loaded and user starts chatting with the bot.

I have a requirement to **store the chat transcript for each user at the end of the conversation**. However, when user navigates away from the page, we are not getting any activity.
How do I know that a conaversation has ended for this scenario?

CC: @abhishan

**Comment by dandriscoll** [comment]
Hi @Kothakapu, we have an Activity type defined for this but it isn't wired up in any channels yet. Eventually we plan to enable support for the EndOfConversation activity type as this is a scenario we want to support.

**Comment by nwhitmont** [comment]
@Kothakapu are you using C# or Node SDK?

**Comment by nwhitmont** [comment]
@dandriscoll any updates on this one?

**Comment by sgellock** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botbuilder-channels/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
