### ISSUE TITLE
How to show carousel in web channel?

### ISSUE THREAD

**Issue by Angel-Mu** [Microsoft/BotBuilder#2008]
Hi!. I review the code and made my fork trying to check how the carousel will be displayed, but didnt make work as expected.
```
{
      text: "some text",
      type: 'message/card.carousel',
      attachmentLayout: 'carousel',
      attachments: attachments
}
```

After that Im able just to view cards as listed!

![image](https://cloud.githubusercontent.com/assets/6799039/21825331/f0276e08-d748-11e6-9a71-320b3933da51.png)

**Comment by LarsLiden** [comment]
The 1.0 version of WebChat does not support carousel.  You can use the new version (which does support carousels) by clicking "Enable Preview" in the WebChat config page.

**Comment by Angel-Mu** [comment]
just one more question... Where is the WebChat config page? are you talking about enable in repo, or in My Bots Section of MS botframework?

**Comment by a-rmz** [comment]
@LarsLiden I tried this but still getting the cards in list format.

**Comment by virendrak** [comment]
@Angel-Mu, Please follow this link, here you can find the Web Chat Sample - https://github.com/Microsoft/BotFramework-WebChat

**Comment by Angel-Mu** [comment]
Oh!!! Ok, thanks 👍
