### ISSUE TITLE
Azure Bot Service, some questions

### ISSUE THREAD

**Issue by cesarvarela** [Microsoft/BotBuilder#2009]
I'm looking a the basic template.

If I change the name or the location of the main entry point (`index.js`) and update accordingly the `main` property in the `package.json`, the bot stops working, which suggests that there is some convention in place for naming/location of this file, but I'm not able to find where is the documentation about this. 

Also what is the `function.js` file for? What about `hosts.js`? Why use a `/messages` folder and place all files inside it when most node projects start just at the root folder?

**Comment by hailiu2586** [comment]
Thanks for your questions. Azure Bot Service is built upon Azure Functions and follows Azure Functions' convention on source code structure. You can find Azure Functions documentation here  https://docs.microsoft.com/en-us/azure/azure-functions/
