### ISSUE TITLE
Embedded web chat control using token failing

### ISSUE THREAD

**Issue by genereddick** [Microsoft/BotBuilder#201]
When using the embedded web chat control, using the token process (swapping the secret for a token), the web chat control is failing at various stages. The web chat control is instantiated as expected -- in that, if the token is missing, or not the correct token from the API call, the chat window does not display. 

However, the control throws various errors, If I do not debug, or step through quickly, the initial error is a 500, message: "The requested resource does not support http method 'GET'."

https://webchat.botframework.com/api/conversations

If I debug and step through slowly, the first error is a 403, missing token or secret.

https://webchat.botframework.com/api/conversations/null/messages 

In the debugger I can step through and see the conversastionId getting set, but it is missing in the call above.

After that, it continues to poll the url, this time with a conversationId, but still returns a 403, missing token or secret.

https://webchat.botframework.com/api/conversations/JLwZUHmHHEy/messages

The embedded web chat using the secret works as expected.

**Comment by genereddick** [comment]
Missed the documentation update --changing to GET api/tokens. Working now.

**Comment by iflint** [comment]
I am having the same problem, if you could explain your solution or point me to the right section of the docs it would be really helpful.

**Comment by dandriscoll** [comment]
Are you using your WebChat secret directly in the URL or are you exchanging the secret for a token?

**Comment by iflint** [comment]
I am using the secret directly

**Comment by dandriscoll** [comment]
Two things to check.
1) Make sure the URL in your iframe is "...s=<SECRET>" instead of "...t=<TOKEN>"
2) Deauthorize and then generate a new secret for the web chat control for your bot. It's possible something has gone wrong with the secret.

**Comment by iflint** [comment]
Just did both of those. I'm getting this:
jquery.min.js:11 POST https://webchat.botframework.com/api/conversations/null/messages 403 (Forbidden)
The bot doesn't respond and a few minutes later it shows this:
jquery.min.js:11 GET https://webchat.botframework.com/api/conversations/Bv3bkhOgxas/messages?watermark=131101401454109138 403 (Forbidden)
sometimes accompanied by this:
jquery.min.js:11 POST https://webchat.botframework.com/api/conversations/Bv3bkhOgxas/messages 500 (Internal Server Error)

I assume the null in the first message is a clue. Any thoughts on what is going on?

**Comment by genereddick** [comment]
I continued to have issues with the embedded webclient, so I switched to a server-side solution using the DirectLine package and I associated my bot with the DirectLine channel on the botframework page.

Here is a simplified version of the code I'm using:

[BotCodeDirectLine] is my Direcl Line channel secret.
[botText] is the text posted from a page

```
var creds = new DirectLineClientCredentials(BotCodeDirectLine);

var uri = new Uri("https://directline.botframework.com");
var directLineClient = new DirectLineClient(uri, creds);

var convs = new Conversations(directLineClient);

var conversation = await convs.NewConversationAsync();

var message = new Microsoft.Bot.Connector.DirectLine.Models.Message(conversationId: conversation.ConversationId, text: botText);

await convs.PostMessageAsync(conversation.ConversationId, message);

///This gets the response text
var messages = await convs.GetMessagesAsync(conversation.ConversationId);

var lastMessage = messages.Messages.Last();
var responseText = lastMessage.Text;

```

**Comment by iflint** [comment]
Thanks for the responses. Looks like I had multiple problems. I switched to Azure as there was an AWS issue. Now it works, unless I send it a message within the first 2 seconds of the iframe loading (which causes the same 403). I'll put a loading bar on the client to prevent that, not ideal but it'll do for now.

**Comment by gregdegruy** [comment]
I'm getting this error jquery.min.js:11 POST https://webchat.botframework.com/api/conversations/2y7GauMpqTbAkgQ9nNaD29/messages 500 (Internal Server Error)

**Comment by akasranjan005** [comment]
i am getting 200 response but still no message getting rendered on the chat console.
https://webchat.botframework.com/v3/conversations/7VYA39JMmRxAr2d8RUAZlT/activities
