### ISSUE TITLE
Severe restart issue in Skype while waiting for user inputs c#

### ISSUE THREAD

**Issue by alokraj68** [Microsoft/BotBuilder#2013]
C# bot is having severe restart issues from time to time. it restarts for users randomly and clears user data.
But in Facebook this issue does not exist.

**Comment by willportnoy** [comment]
That's hard to debug without more information - we can reset the call stack if it fails to deserialize, which would look like the conversation failed to restart.  Are there exceptions in your logs you could share?

**Comment by alokraj68** [comment]
@willportnoy  how can i take stack for the bot running in skype?

and also i found this message comes in whenever it fails. "There was an error sending this message to your bot."

**Comment by willportnoy** [comment]
You might attach the debugger to your deployed code and communicate with it over skype.  You can use "break on thrown exceptions" to find out whether you have any thrown exceptions.

**Comment by Andrea-Orimoto** [comment]
Hi @alokraj68, were you able to figure this out?

**Comment by carlosscastro** [comment]
@alokraj68 closing the issue for now, but feel free to reopen if you were not able to figure this out.

**Comment by alokraj68** [comment]
@willportnoy , @Andrea-Orimoto , @carlosscastro I could not find out why this happens.  Our bot is working fine in KIK, Telegram, Facebook, and direct chat. the issue seems to be with only Skype.
