### ISSUE TITLE
c# Botframework update gives error 500

### ISSUE THREAD

**Issue by alokraj68** [Microsoft/BotBuilder#2014]
C# bot framework when updated the NuGet package from 3.4.0 to 3.5.0 gives internal error 500. rolling back fixes this issue.

**Comment by willportnoy** [comment]
Can you send us a call stack?

**Comment by alokraj68** [comment]
@willportnoy can i know how i can make a call stack?

**Comment by alokraj68** [comment]
@willportnoy 

Exception thrown: 'System.ArgumentNullException' in mscorlib.dll
'iisexpress.exe' (CLR v4.0.30319: /LM/W3SVC/2/ROOT-1-131291218319763603): Loaded 'Anonymously Hosted DynamicMethods Assembly'. 
Application Insights Telemetry: {"name":"Microsoft.ApplicationInsights.Dev.f57bdccecf5943fab2ee9b78a19de425.RemoteDependency","time":"2017-01-17T10:17:18.7041326Z","iKey":"f57bdcce-cf59-43fa-b2ee-9b78a19de425","tags":{"ai.internal.sdkVersion":"rddf:2.2.0-738","ai.internal.nodeName":"ARS","ai.operation.id":"Aej3vFGKe0U=","ai.location.ip":"127.0.0.1","ai.cloud.roleInstance":"ARS","ai.operation.name":"POST messages","ai.operation.parentId":"Aej3vFGKe0U="},"data":{"baseType":"RemoteDependencyData","baseData":{"ver":2,"name":"/common/v2.0/.well-known/openid-configuration","id":"FUhXEQ+G6YI=","data":"https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration","duration":"00:00:00.2990000","resultCode":"200","success":true,"type":"Http","target":"login.microsoftonline.com","properties":{"DeveloperMode":"true"}}}}
Application Insights Telemetry: {"name":"Microsoft.ApplicationInsights.Dev.f57bdccecf5943fab2ee9b78a19de425.RemoteDependency","time":"2017-01-17T10:17:19.0221684Z","iKey":"f57bdcce-cf59-43fa-b2ee-9b78a19de425","tags":{"ai.internal.sdkVersion":"rddf:2.2.0-738","ai.internal.nodeName":"ARS","ai.cloud.roleInstance":"ARS"},"data":{"baseType":"RemoteDependencyData","baseData":{"ver":2,"name":"/common/discovery/v2.0/keys","id":"ZI593qHKwrQ=","data":"https://login.microsoftonline.com/common/discovery/v2.0/keys","duration":"00:00:00.1670000","resultCode":"200","success":true,"type":"Http","target":"login.microsoftonline.com","properties":{"DeveloperMode":"true"}}}}
'iisexpress.exe' (CLR v4.0.30319: /LM/W3SVC/2/ROOT-1-131291218319763603): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Net.Http.WebRequest\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Net.Http.WebRequest.dll'. Cannot find or open the PDB file.
Application Insights Telemetry: {"name":"Microsoft.ApplicationInsights.Dev.f57bdccecf5943fab2ee9b78a19de425.RemoteDependency","time":"2017-01-17T10:17:19.5157017Z","iKey":"f57bdcce-cf59-43fa-b2ee-9b78a19de425","tags":{"ai.internal.sdkVersion":"rddf:2.2.0-738","ai.internal.nodeName":"ARS","ai.cloud.roleInstance":"ARS"},"data":{"baseType":"RemoteDependencyData","baseData":{"ver":2,"name":"/botframework.com/oauth2/v2.0/token","id":"BSjcWnHk7Ko=","data":"https://login.microsoftonline.com/botframework.com/oauth2/v2.0/token","duration":"00:00:00.6770000","resultCode":"200","success":true,"type":"Http","target":"login.microsoftonline.com","properties":{"DeveloperMode":"true"}}}}
Application Insights Telemetry: {"name":"Microsoft.ApplicationInsights.Dev.f57bdccecf5943fab2ee9b78a19de425.RemoteDependency","time":"2017-01-17T10:17:19.5056951Z","iKey":"f57bdcce-cf59-43fa-b2ee-9b78a19de425","tags":{"ai.internal.sdkVersion":"rddf:2.2.0-738","ai.internal.nodeName":"ARS","ai.cloud.roleInstance":"ARS"},"data":{"baseType":"RemoteDependencyData","baseData":{"ver":2,"name":"/botframework.com/oauth2/v2.0/token","id":"4ImzAQPRpHw=","data":"https://login.microsoftonline.com/botframework.com/oauth2/v2.0/token","duration":"00:00:00.6920000","resultCode":"200","success":true,"type":"Http","target":"login.microsoftonline.com","properties":{"DeveloperMode":"true"}}}}
Application Insights Telemetry: {"name":"Microsoft.ApplicationInsights.Dev.f57bdccecf5943fab2ee9b78a19de425.RemoteDependency","time":"2017-01-17T10:17:20.2202417Z","iKey":"f57bdcce-cf59-43fa-b2ee-9b78a19de425","tags":{"ai.internal.sdkVersion":"rddf:2.2.0-738","ai.internal.nodeName":"ARS","ai.cloud.roleInstance":"ARS"},"data":{"baseType":"RemoteDependencyData","baseData":{"ver":2,"name":"/v3/conversations/73em003ii4f4befnf/activities/lfh05n1mk58c4m6j3","id":"ApuHYepiMH8=","data":"http://localhost:9002/v3/conversations/73em003ii4f4befnf/activities/lfh05n1mk58c4m6j3","duration":"00:00:00.7470000","resultCode":"401","success":false,"type":"Http","target":"localhost","properties":{"DeveloperMode":"true"}}}}
Application Insights Telemetry: {"name":"Microsoft.ApplicationInsights.Dev.f57bdccecf5943fab2ee9b78a19de425.RemoteDependency","time":"2017-01-17T10:17:20.2202417Z","iKey":"f57bdcce-cf59-43fa-b2ee-9b78a19de425","tags":{"ai.internal.sdkVersion":"rddf:2.2.0-738","ai.internal.nodeName":"ARS","ai.cloud.roleInstance":"ARS"},"data":{"baseType":"RemoteDependencyData","baseData":{"ver":2,"name":"/v3/conversations/mll30gfkc43j72l13/activities/9504a9ge44mklel7l","id":"N0v9ccXMMrI=","data":"http://localhost:9002/v3/conversations/mll30gfkc43j72l13/activities/9504a9ge44mklel7l","duration":"00:00:00.7500000","resultCode":"401","success":false,"type":"Http","target":"localhost","properties":{"DeveloperMode":"true"}}}}
Exception thrown: 'Microsoft.Rest.TransientFaultHandling.HttpRequestWithStatusException' in Microsoft.Rest.ClientRuntime.dll
Exception thrown: 'Microsoft.Rest.TransientFaultHandling.HttpRequestWithStatusException' in Microsoft.Rest.ClientRuntime.dll
Exception thrown: 'Microsoft.Rest.TransientFaultHandling.HttpRequestWithStatusException' in mscorlib.dll
Exception thrown: 'Microsoft.Rest.TransientFaultHandling.HttpRequestWithStatusException' in mscorlib.dll
Application Insights Telemetry: {"name":"Microsoft.ApplicationInsights.Dev.f57bdccecf5943fab2ee9b78a19de425.RemoteDependency","time":"2017-01-17T10:17:21.0468163Z","iKey":"f57bdcce-cf59-43fa-b2ee-9b78a19de425","tags":{"ai.internal.sdkVersion":"rddf:2.2.0-738","ai.internal.nodeName":"ARS","ai.cloud.roleInstance":"ARS"},"data":{"baseType":"RemoteDependencyData","baseData":{"ver":2,"name":"/botframework.com/oauth2/v2.0/token","id":"L8nCFkAl274=","data":"https://login.microsoftonline.com/botframework.com/oauth2/v2.0/token","duration":"00:00:00.6310000","resultCode":"200","success":true,"type":"Http","target":"login.microsoftonline.com","properties":{"DeveloperMode":"true"}}}}
Application Insights Telemetry: {"name":"Microsoft.ApplicationInsights.Dev.f57bdccecf5943fab2ee9b78a19de425.RemoteDependency","time":"2017-01-17T10:17:21.6816579Z","iKey":"f57bdcce-cf59-43fa-b2ee-9b78a19de425","tags":{"ai.internal.sdkVersion":"rddf:2.2.0-738","ai.internal.nodeName":"ARS","ai.cloud.roleInstance":"ARS"},"data":{"baseType":"RemoteDependencyData","baseData":{"ver":2,"name":"/v3/conversations/73em003ii4f4befnf/activities/lfh05n1mk58c4m6j3","id":"DEb4nnmQKPA=","data":"http://localhost:9002/v3/conversations/73em003ii4f4befnf/activities/lfh05n1mk58c4m6j3","duration":"00:00:00.0030000","resultCode":"401","success":false,"type":"Http","target":"localhost","properties":{"DeveloperMode":"true"}}}}
Exception thrown: 'Microsoft.Rest.TransientFaultHandling.HttpRequestWithStatusException' in Microsoft.Rest.ClientRuntime.dll
Exception thrown: 'Microsoft.Rest.TransientFaultHandling.HttpRequestWithStatusException' in mscorlib.dll
Exception thrown: 'System.UnauthorizedAccessException' in Microsoft.Bot.Connector.dll
Application Insights Telemetry: {"name":"Microsoft.ApplicationInsights.Dev.f57bdccecf5943fab2ee9b78a19de425.RemoteDependency","time":"2017-01-17T10:17:21.0463141Z","iKey":"f57bdcce-cf59-43fa-b2ee-9b78a19de425","tags":{"ai.internal.sdkVersion":"rddf:2.2.0-738","ai.internal.nodeName":"ARS","ai.cloud.roleInstance":"ARS"},"data":{"baseType":"RemoteDependencyData","baseData":{"ver":2,"name":"/botframework.com/oauth2/v2.0/token","id":"AohKt7iFq5o=","data":"https://login.microsoftonline.com/botframework.com/oauth2/v2.0/token","duration":"00:00:00.6600000","resultCode":"200","success":true,"type":"Http","target":"login.microsoftonline.com","properties":{"DeveloperMode":"true"}}}}
Exception thrown: 'System.UnauthorizedAccessException' in mscorlib.dll
Exception thrown: 'System.UnauthorizedAccessException' in mscorlib.dll
Exception thrown: 'System.UnauthorizedAccessException' in mscorlib.dll
Application Insights Telemetry: {"name":"Microsoft.ApplicationInsights.Dev.f57bdccecf5943fab2ee9b78a19de425.RemoteDependency","time":"2017-01-17T10:17:21.7411975Z","iKey":"f57bdcce-cf59-43fa-b2ee-9b78a19de425","tags":{"ai.internal.sdkVersion":"rddf:2.2.0-738","ai.internal.nodeName":"ARS","ai.cloud.roleInstance":"ARS"},"data":{"baseType":"RemoteDependencyData","baseData":{"ver":2,"name":"/v3/conversations/mll30gfkc43j72l13/activities/9504a9ge44mklel7l","id":"xYGb6MHO0H8=","data":"http://localhost:9002/v3/conversations/mll30gfkc43j72l13/activities/9504a9ge44mklel7l","duration":"00:00:00.0250000","resultCode":"401","success":false,"type":"Http","target":"localhost","properties":{"DeveloperMode":"true"}}}}
Exception thrown: 'System.UnauthorizedAccessException' in mscorlib.dll
Exception thrown: 'Microsoft.Rest.TransientFaultHandling.HttpRequestWithStatusException' in Microsoft.Rest.ClientRuntime.dll
Exception thrown: 'System.UnauthorizedAccessException' in mscorlib.dll
Exception thrown: 'Microsoft.Rest.TransientFaultHandling.HttpRequestWithStatusException' in mscorlib.dll
Exception thrown: 'System.UnauthorizedAccessException' in Microsoft.Bot.Connector.dll
Exception thrown: 'System.UnauthorizedAccessException' in mscorlib.dll
Exception thrown: 'System.UnauthorizedAccessException' in mscorlib.dll
Exception thrown: 'System.UnauthorizedAccessException' in mscorlib.dll
Exception thrown: 'System.UnauthorizedAccessException' in mscorlib.dll
Exception thrown: 'System.UnauthorizedAccessException' in System.Web.Http.dll
Exception thrown: 'System.UnauthorizedAccessException' in mscorlib.dll
Exception thrown: 'System.UnauthorizedAccessException' in mscorlib.dll
Exception thrown: 'System.UnauthorizedAccessException' in mscorlib.dll
Exception thrown: 'System.UnauthorizedAccessException' in mscorlib.dll
Exception thrown: 'System.UnauthorizedAccessException' in mscorlib.dll
Exception thrown: 'System.UnauthorizedAccessException' in mscorlib.dll
Exception thrown: 'System.UnauthorizedAccessException' in mscorlib.dll
Exception thrown: 'System.UnauthorizedAccessException' in mscorlib.dll
Exception thrown: 'System.UnauthorizedAccessException' in System.Web.Http.dll
Exception thrown: 'System.UnauthorizedAccessException' in mscorlib.dll
Exception thrown: 'System.UnauthorizedAccessException' in mscorlib.dll
Exception thrown: 'System.UnauthorizedAccessException' in mscorlib.dll
Application Insights Telemetry: {"name":"Microsoft.ApplicationInsights.Dev.f57bdccecf5943fab2ee9b78a19de425.Request","time":"2017-01-17T10:17:18.2948160Z","iKey":"f57bdcce-cf59-43fa-b2ee-9b78a19de425","tags":{"ai.internal.sdkVersion":"web:2.2.0-738","ai.operation.id":"Aej3vFGKe0U=","ai.location.ip":"127.0.0.1","ai.cloud.roleInstance":"ARS","ai.operation.name":"POST messages"},"data":{"baseType":"RequestData","baseData":{"ver":2,"id":"Aej3vFGKe0U=","name":"POST messages","duration":"00:00:03.9150000","success":false,"responseCode":"500","url":"http://localhost:3979/api/messages","properties":{"DeveloperMode":"true"}}}}
Application Insights Telemetry: {"name":"Microsoft.ApplicationInsights.Dev.f57bdccecf5943fab2ee9b78a19de425.Request","time":"2017-01-17T10:17:18.5544894Z","iKey":"f57bdcce-cf59-43fa-b2ee-9b78a19de425","tags":{"ai.internal.sdkVersion":"web:2.2.0-738","ai.operation.id":"dQK4SBmBf/o=","ai.location.ip":"127.0.0.1","ai.cloud.roleInstance":"ARS","ai.operation.name":"POST messages"},"data":{"baseType":"RequestData","baseData":{"ver":2,"id":"dQK4SBmBf/o=","name":"POST messages","duration":"00:00:03.6550000","success":false,"responseCode":"500","url":"http://localhost:3979/api/messages","properties":{"DeveloperMode":"true"}}}}
The thread 0x37a0 has exited with code 0 (0x0).
The thread 0x3b34 has exited with code 0 (0x0).
The thread 0x3af8 has exited with code 0 (0x0).
The thread 0x2cdc has exited with code 0 (0x0).
The thread 0x38a0 has exited with code 0 (0x0).
The thread 0x3dbc has exited with code 0 (0x0).

this is the log i could make out

**Comment by alokraj68** [comment]
Help wanted!

**Comment by willportnoy** [comment]
I see a lot of UnauthorizedAccessException - are you using the correct authentication information?

https://docs.botframework.com/en-us/support/troubleshooting-bot-framework-authentication/

**Comment by g4mb10r** [comment]
I have the exact same issue.  Something is broken with the Skype integration.  Replying back via other channels (e.g. web chat) works fine.

**Comment by Andrea-Orimoto** [comment]
@alokraj68 , @g4mb10r , still having this issue?

**Comment by willportnoy** [comment]
@eanders-MS I presume localhost:9002 is the emulator - why would it throw a 401 when login.microsoftonline.com seems to return a 200 just a few lines earlier?

(I'll also take a look at the SDK - @msft-shahins for FYI)

**Comment by msft-shahins** [comment]
@alokraj68, @g4mb10r I believe you are using old emulator. Try to install the new emulator: https://docs.botframework.com/en-us/tools/bot-framework-emulator/#navtitle

New emulator looks like following:

![image](https://cloud.githubusercontent.com/assets/17562300/23050401/0c9992c8-f477-11e6-80d5-654fbc4848ac.png)

old emulator doesn't accept the v3.1 auth token sent by sdk version > 3.5. You can read more about changes here: https://docs.botframework.com/en-us/restapi/authentication/#changes

**Comment by willportnoy** [comment]
Sorry @msft-shahins I didn't catch that - thank you.

**Comment by alokraj68** [comment]
This issue was because we were trying access https url for http one. Its resolved.
