### ISSUE TITLE
How can I send parameters in the web chat ?

### ISSUE THREAD

**Issue by mohit-jcc** [Microsoft/BotBuilder#2015]
I am using the web chat embedded in a mobile app :

`<iframe src="https://webchat.botframework.com/embed/profilebot?s=YOUR_SECRET_HERE" style="height: 502px; max-height: 502px;"></iframe>`

I need to send a parameter to the bot server everytime a user opens the chat view in the app. 

Is it possible to append to this url and access the parameter at the server?

**Update:**
As an alternative, in the page where the web chat is embedded, I am making a post request with the token on page load.
`<server url>/api/messages?token=2143`
 
I receive the token in the server and save in token variable, but in the bot scope the token is undefined : 

```
var token;

// Listen for messages from users 
var botListener = connector.listen();
server.post('/api/messages', (req, resp) => {
    token = req.query.token;
    console.log(token); //prints the token to the terminal
    botListener(req, resp);
});

// Create your bot with a function to receive messages from the user
var bot = new builder.UniversalBot(connector, function(session){
    session.send("Hello, Welcome");
    if (token == undefined) { // the login dialog is triggered
        session.beginDialog('login');    
    } else {
        session.userData.token = token;
        session.send("How can I help you?");
    }

});

```

Any suggestions as to how can I make this approach work appreciated.
Thanks

**Comment by mohit-jcc** [comment]
@maxpert thoughts on this please?

**Comment by dandriscoll** [comment]
Hi @mohit-jcc, parameters are available if you use the Web Chat control directly: https://github.com/Microsoft/BotFramework-WebChat

If you use the control directly in your page, you can pass parameters when you create the object.

Currently we do not offer a way to pass parameters via the embed URL.

**Comment by mohit-jcc** [comment]
@dandriscoll Thanks for this suggestion, i was able to get the parameters in the bot session. I have a couple of concerns though : 

1. Is there a way for me to use this webchat interface as a part of my main bot server and to not have it run at a separate process?
2. I am not getting the messages sent from the server (session.send()) in the web chat view. Does it require any additional configuration?

Thanks

**Comment by dandriscoll** [comment]
Hi @mohit-jcc,

1. The control runs in a browser, not in the bot. Your server can deliver just the HTML, JS, and CSS files. The control talks to the Direct Line service, which then routes requests to your bot.
2. There's no additional configuration required. Are you seeing errors appear on the Direct Line or the Web Chat lines in the Bot Framework dev portal?

**Comment by mohit-jcc** [comment]
Thanks @dandriscoll 
I am serving the webchat.html. botchat.js and botchat.css from my server. But I am getting this error :
`Uncaught ReferenceError: BotChat is not defined`

**Comment by dandriscoll** [comment]
I think we've addressed the original issue. If you'd like to discuss the problem receiving messages, please open a new issue.
