### ISSUE TITLE
Bot Emulator isn't authorized after newest update of the framwork to 3.5 C#

### ISSUE THREAD

**Issue by fingejo** [Microsoft/BotBuilder#2017]
After the the Bot Framework update from 3.4 to 3.5 in c#, the local deubbing does not work anymore.
When sending a message with the bot emulator, the bot throws an unauthorized exception back.
But the online hosted version with connected channels like telegram is working just fine like before.
Rollback fixes the problem.

**Comment by willportnoy** [comment]
Are you using the latest emulator at https://docs.botframework.com/en-us/tools/bot-framework-emulator/ ?  I would also restart the emulator to make sure all updates have been applied.

**Comment by fingejo** [comment]
the new emulator is working. Thankyou!
