### ISSUE TITLE
quick replies stopped appearing as buttons in the emulator

### ISSUE THREAD

**Issue by bmperrea** [Microsoft/BotBuilder#2018]
In 3.2.3 quick replies show up as buttons, as they should on facebook.

In 3.5.3 the quick replies show up as text: "(1. answer one, 2. answer two)"

I'm using Emulator v3.5.23 on Windows, running the bot on node.

**Comment by amitbend** [comment]
@bmperrea can you add a code snippet of the call?

**Comment by bmperrea** [comment]
[a gist](https://gist.github.com/bmperrea/5f42ddc6a9e7bf86a811243d481e967b)

**Comment by Stevenic** [comment]
The new emulator doesn't support keyboards/quick replies yet so we had to turn them off. You can force the use of cards to render buttons by passing in `{ listStyle: builder.ListStyle.button }` as an option for your prompt.

**Comment by Stevenic** [comment]
Closing this for now. Please feel free to add further comments.
