### ISSUE TITLE
Adding Office365 mail account with AD FS authentication

### ISSUE THREAD

**Issue by fingejo** [Microsoft/BotBuilder#2024]
Hello again,
we use office365 with an AD FS authentication so you get redirected to a company login when you try to log into your office account in the browser.
When I'm trying to configure the E-Mail-Channel with the same data i used for the Web-Login, it says: "Unable to validate the given credentials."
It seems like this redirect is not working in the channel authentification.
Is there any solution besides creating an Office account without AD FS authentification?

**Comment by willportnoy** [comment]
@craigjensen can you help?

**Comment by craigjensen** [comment]
We don't support oAuth so you'll need to make sure your mailbox is accessible via username/password.  

Here are a couple of tools you can try to ensure that your mailbox is accessible:

EWSEditor
https://ewseditor.codeplex.com/

Remote Connectivity Test (RCA)
https://testconnectivity.microsoft.com
This is a Microsoft web site used for testing connectivity. It has a web based tester and also one for running from a desktop.

**Comment by willportnoy** [comment]
Thank you @craigjensen - I'm going to close this issue for now, but feel free to open a new issue for further discussion.
