### ISSUE TITLE
Set image to Herocard/Thumbnail card from local folder

### ISSUE THREAD

**Issue by chetanmekha** [Microsoft/BotBuilder#2027]
Hello Team,
I want to set image/picture to Herocard/Thumbnail card from my local folder. How can I do it? Please help me on the same.

**Comment by dandriscoll** [comment]
Hi @chetanmekha, you have two options.

1. You can load the file into memory and use the Attachments API to upload it to the channel.
2. If the file is small enough, you can turn it into a base64 blob and embed it as a base64 data URI. This page shows a URI like that: https://docs.botframework.com/en-us/core-concepts/attachments/ (search for "base64" to see how it's rendered into the Activity)

**Comment by Andrea-Orimoto** [comment]
Hi @chetanmekha, I'm assuming @dandriscoll's answer helped you out, so I'm closing this issue. Feel free to reopen it if this is not the case. Thanks!

**Comment by PrasadGautham** [comment]
@dandriscoll  Is it not possible to set base 64 image to herocard in the facebook channel. Its working fine in emulator but not working in fb

**Comment by JasonSowers** [comment]
@PrasadGautham does facebook support base64 attachments?

**Comment by gucompi** [comment]
Hi! 
Just put the full-path. 
thats work for me.
