### ISSUE TITLE
Node SDK IntentDialog vs TriggerAction

### ISSUE THREAD

**Issue by josephktcheung** [Microsoft/BotBuilder#2028]
Before node sdk 3.5, we use IntentDialog to match LUIS intent. After 3.5, we can use both `IntentDialog` and `dialog.triggerAction` to do the same thing. Which is the recommended way? I guess is `triggerAction` (since the latest basics-naturalLanguage example uses `triggerAction`)? When should we use IntentDialog now?

Also I'd like to know how to adjust `intentThreshold` for `triggerAction` while we can set that in `IntentDialog`. Should I instead of using `matches` use `onFindAction` in `triggerAction` and use `context.intent` to check if it is the intent I want + the matching score is above the threshold? e.g.
```javascript
bot.dialog('a', function(session) {
}).triggerAction({
  onFindAction: function(context, callback) {
    if (context.intent.intent === 'Intent' && context.intent.score > 0.3) {
      callback(null, 1.0);
    } else {
      callback(null, 0.0);
    }
  }
});
```
Is there a easier way to do it? Thanks.

**Comment by willportnoy** [comment]
I think trigger action is the more composable (and therefore likely better) method.  @Stevenic can you comment on the intentThreshold?

**Comment by fkurkowski** [comment]
I happened to stumble upon the same problem today and noticed that `intentThreshold` [is actually an option](https://github.com/Microsoft/BotBuilder/blob/2826c4757be5488ecc13926ecdf540254bf9715d/Node/core/src/dialogs/ActionSet.ts#L47) on `triggerAction`. You just have to pass it around:

```javascript
bot.dialog(...)
  .triggerAction({
    matches: 'YourIntentName'
    intentThreshold: 0.40
  });
```
