### ISSUE TITLE
Different text for different messangers

### ISSUE THREAD

**Issue by hardsky** [Microsoft/BotBuilder#2029]
Hi!
Is it possible to send different text to Skype and Telegram messangers?
I have case about help command, it shows list of command with description.
It's preferable to name command for Telegram with slash '/' and for Skype without slash.
For an example:

Telegram:
- /cost - get cost for phone numbers
- /operator - find operator for phone numbers

Skype:
- cost - get cost for phone numbers
- operator - find operator for phone numbers

I use 'UniversalBot' and NodeJs SDK in this moment. Is it possible to send different text to telegram and skype?

**Comment by chetanmekha** [comment]
You can do it with if elase condition, check for 
`if(session.message.address.channelId === "skype"){
//perform skype operation
}else if(session.message.address.channelId === "telegram"){
// perform telegram operation
}else{
// default operation.
}

`
session.message.address.channelId give you communication channel Id

**Comment by hardsky** [comment]
Thanks!
