### ISSUE TITLE
Dialog vs FormFlow

### ISSUE THREAD

**Issue by ahmettaha** [Microsoft/BotBuilder#203]
Hello,

Can you please tell me what can not be done with Dialogs that FormFlow can do? From the documentation, the only difference is FormFlow can have sequential dialogs. and Dialogs are more like standalone. Is that it? What are best uses cases for either features?

Thanks.

**Comment by chrimc62** [comment]
You can do everything in FormFlow with dialogs--it is just a question of effort.  (For that matter you don't need dialogs if you want to implement everything yourself...)   With FormFlow you create a C# class and immediately get a dialog that supports clarification, help, navigation and prompting without additional work. You can refine from there.  With dialogs you have to implement all of that yourself.  If you read through the FormFlow documentation you can get a good idea of the work it saves.
