### ISSUE TITLE
[nodejs] Access to the Session in a middleware

### ISSUE THREAD

**Issue by palmerabollo** [Microsoft/BotBuilder#2030]
Is it possible to access the `Session` in a middleware, before sending a message to the user?

For example, in this middleware, the Session is accessible in the `botbuilder` function, but not in the `receive` function (makes sense) nor in the `send` function:

```typescript
let middleware: BotBuilder.IMiddlewareMap = {
    botbuilder: (session: BotBuilder.Session, next: Function) => {
        next();
    },
    receive: (event: BotBuilder.IEvent, next: Function) => {
        next();
    },
    send: (event: BotBuilder.IEvent, next: Function) => {
        next();
    }
};
```

I want to use a middleware to convert to speech all the messages the bot sends to the users, but I am not able to access the user's preferred language because it is part of the session. Any ideas?

**Comment by Stevenic** [comment]
You need to manually hook the sessions  `onSend()` method:

```
    public middleware(): IMiddlewareMap {
        return {
            botbuilder: (session, next) => {
                // Hook onSend
                let _onSend = session.options.onSend;
                session.options.onSend = function (messages, done:) {
                        // Process messages...

                       // Call original function
                      _onSend(messages, done);
                };

                // Continue
                next();
            }
        };
    }
```

**Comment by Stevenic** [comment]
closing but please feel free to comment.

**Comment by palmerabollo** [comment]
Thanks @Stevenic. Two comments:
1. `session.options` is not accessible ([see typings](https://github.com/Microsoft/BotBuilder/blob/d51e893/Node/core/src/botbuilder.d.ts#L1256))
2. It's a bit tricky and forces us to process an array of messages. I think it would be better to include it officially in the `IMiddlewareMap`.

**Comment by palmerabollo** [comment]
@Stevenic any chance you could add `session.options` to the typings?

**Comment by ancashoria** [comment]
This would be really useful for us too.
What's the logic behind the decision to not have `session` on send hook?

**Comment by adaddeo** [comment]
Would be great to have session available in middleware.

**Comment by srichakradhar** [comment]
Any updates on this? I tried but still not access `session` from within the middleware.
