### ISSUE TITLE
Is it any way to know how long it has taken the user to respond back a message?

### ISSUE THREAD

**Issue by piffarettig** [Microsoft/BotBuilder#2031]
I am using Skype channel and C#.

Specifically I would like to know:

A) The period time that passed between the user wrote the first character of a message and then sent it (this probably doesn't exist but..) This is usually known as typing cadence.

OR

B) The time between the last message by the bot and the arrival of the response by the user.

Thanks!

**Comment by Lipa9963** [comment]
@piffarettig 
IAwaitable<IMessageActivity> result ;
 var message = await result;
 var time =message.LocalTimestamp;

**Comment by Andrea-Orimoto** [comment]
@piffarettig, I'm assuming @Lipa9963's comment helped you out, so I'm closing this. Feel free to reopen it if this is not the case. Thanks!
