### ISSUE TITLE
C# Url does not show as it is in FB chats.

### ISSUE THREAD

**Issue by alokraj68** [Microsoft/BotBuilder#2033]
The URLs that are wrapped in a name does not show up in FB chats.
example : [Clickastro](http://www.clickastro.com?utm_source=horoscopebot&utm_medium=direct)

this would come in FB like Clickastro http://www.clickastro.com?utm_source=horoscopebot&utm_medium=direct

This will show us Clickastro in skype but in FB it shows the URL also. I hope its a bug.

**Comment by craigjensen** [comment]
Messenger doesn't support markdown so we strip it and send the plain text.  If/when Facebook starts supporting markdown we'll make the necessary updates to fully support it.

**Comment by AndreMantas** [comment]
2 years later, no updates on this?

**Comment by EricDahlvang** [comment]
@AndreMantas  The issue is with Facebook Messenger.
