### ISSUE TITLE
Connecting AIML powered bots to bot framework

### ISSUE THREAD

**Issue by alokraj68** [Microsoft/BotBuilder#2034]
Hi,
I have a Aiml powered bot. I want to connect it to bot  framework front end. How can I do that?

**Comment by tomlm** [comment]
1. create bot using favorite template
2. instantiate aiml interpreter (added via npm or nugget or however)
   a. load any conversation saved state from conversation state api
3. pass activity.text to interpreter and get reply
4. save interpreter state to conversation state api
5. send reply back to user.

You now should have a HTTP endpoint which uses the AIML markup and interpreter to process text and create a reply.

**Comment by alokraj68** [comment]
@tomlm can u explain the steps 1 and 2?
