### ISSUE TITLE
IActivityLogger called twice for IBotToUser.PostAsync messages

### ISSUE THREAD

**Issue by brunoklein99** [Microsoft/BotBuilder#2035]
When calling IDialogContext.PostAsync, if we have an implementation of IActivityLogger registered it gets called twice.

Inconvenient If we are inserting a row in a database with data from the activity without a generator.

Thank you.

**Comment by willportnoy** [comment]
Any chance it's for two messages, the one to the bot, and the second to the user?

**Comment by willportnoy** [comment]
I'm going to close this issue due to inactivity.
