### ISSUE TITLE
Add new supported platform: Vkontakte

### ISSUE THREAD

**Issue by gEndelf** [Microsoft/BotBuilder#2036]
Do you have plans to add **Vkontakte** (vk.com) to supported platforms?

**Comment by dandriscoll** [comment]
We don't have any announcements about new non-Microsoft channels. Thank you for the suggestion, though.

**Comment by dandriscoll** [comment]
Closing as we have no announcements to make at this time. Please at-mention or open a new issue if you'd like to discuss further.
