### ISSUE TITLE
Users connecting form an unknown source

### ISSUE THREAD

**Issue by alokraj68** [Microsoft/BotBuilder#2037]
Hi,
I have seen recently that there are many users who connect from this address "https://smba.trafficmanager.net/apis/" Which platform is it? or how are they connecting my bots from this address? 
Can anyone Help?

**Comment by dandriscoll** [comment]
Hi @alokraj68, this is the Skype service.

**Comment by dandriscoll** [comment]
Closing as we've answered the question. Please at-mention or open a new issue if you'd like to discuss further.
