### ISSUE TITLE
Chaining multiple dialogs using Context.call/done

### ISSUE THREAD

**Issue by sushant21** [Microsoft/BotBuilder#2038]
I have a LuisDialog which calls a particular dialog if an intent is found. There,on the basis of entity extracted, I am calling another dialog, which seems to be throwing some unhandled exception.
Here is the intent in my root LuiDialog calling BuyDialog(I'm saving the LuisResult for later use)-

    [LuisIntent("Buy")]
    public async Task Buy(IDialogContext context,  LuisResult result)
    {
       var cts = new CancellationTokenSource();
       await context.PostAsync("you want to buy");
       context.PrivateConversationData.SetValue<LuisResult>("luis", result);
       context.Call(new BuyDialog(), ResumeAfterBuyDialog);
    }
     private  async Task ResumeAfterBuyDialog(IDialogContext context, IAwaitable<bool> result)
        {
            var success = await result;
            if (success)
            {
                await context.PostAsync("How else can I help you?");
                context.Wait(MessageReceived);
              }
        }

Here is my BuyDialog calling another dialog(BookDialog) if entity contains "book" string-

    else if(is_book)
                    {
                        await context.PostAsync("You selected book category");
                        context.Call(new BookDialog(),BookFormComplete);
                        context.Done(true);
                    }
     private async Task BookFormComplete(IDialogContext context, IAwaitable<bool> result)  
        {
            var BookResult = await result;
            //do something if result is true
        }

And here is my BookDialog-

    [Serializable]
    public class BookDialog : IDialog<object>
    {
        public  async Task StartAsync(IDialogContext context)
        {
            context.Wait(MessageReceivedAsync);
        }
        public async Task MessageReceivedAsync(IDialogContext context, IAwaitable<IMessageActivity> argument)
        {
            var message = await argument;
            if (message.Text == "mtl100")
            {
                await context.PostAsync("Correct");
                context.Done(true);
            }
            else
            {
                await context.PostAsync("Please enter valid course code");
                context.Wait(MessageReceivedAsync);
            }

I know the problem is in that second context.call(the call to bookDialog), because if I remove it the code works perfectly fine. Right now, I'm getting "sorry, my bot code is having an issue" when it reaches there. Any idea what's wrong?

**Comment by willportnoy** [comment]
I would break on thrown exceptions to find the actual error:

https://docs.botframework.com/en-us/technical-faq/#how-can-i-troubleshoot-my-bot-using-the-c-bot-builder-sdk

Is there any non-serializable state in the called BookDialog?

**Comment by willportnoy** [comment]
I'm going to close this issue due to inactivity.

**Comment by tishkata86** [comment]
I think the problem is when your bot catch wrong intent or your dialog don't have handler for specifical intent and than it's trow that error. If anyone have same issue, please check your luis app what response give you back when you ask it.
