### ISSUE TITLE
Having a lot of 403 errors

### ISSUE THREAD

**Issue by fercom** [Microsoft/BotBuilder#2042]
Hi, my bot is throwing a lot of "403" errors, I don't know why, can you help me?
![image](https://cloud.githubusercontent.com/assets/19654168/21995726/0374c896-dbec-11e6-813a-a7b90700156d.png)

**Comment by eanders-MS** [comment]
Hi @fercom Have you checked for channel-specific errors in the dev portal? A 403 could happen in a number valid scenarios, such as: your bot tried to post to a user, but the user has revoked permissions or blocked your bot.

**Comment by fercom** [comment]
@eanders-MS yes but there is nothing there, because it seems to be a dependency error in smba.trafficmanager.net that doesn't make the request fail (see the image)

**Comment by nickcordrey** [comment]
@fercom we've emailed you regarding your errors and issues we're seeing with traffic from your bot. Please follow up to the mail and someone from the team will be in touch.

**Comment by Andrea-Orimoto** [comment]
I'm assuming this was dealt with in a separate email thread, so I'm closing this issue. Do reopen this if you're still experiencing the issue. Thanks!
