### ISSUE TITLE
Activity contains a "mention" entity with my bot id even when message is not addressed to the bot

### ISSUE THREAD

**Issue by ncksol** [Microsoft/BotBuilder#2044]
This is happening to my bot on telegram. It is member of a group and whenever a message is posted to the group the incoming activity contains entity of type "mention" and my bot's id. This is the same for every single message in the group. It doesn't matter whether user addressed the bot through "at" symbol or not.
Essentially I have to parse the text and look for "@botname" in the message instead of using entities.

**Comment by LarsLiden** [comment]
This sounds like a bug.  We will investigate

**Comment by eanders-MS** [comment]
Verified this is happening. Was due to some legacy code. Will remove it.

**Comment by eanders-MS** [comment]
Fix has been deployed. Closing now. @ncksol If you're still seeing this behavior please @mention me or open a new issue. Thanks for taking the time to report this issue.
