### ISSUE TITLE
Support Text Markdown in Cards

### ISSUE THREAD

**Issue by miaosenwang** [Microsoft/BotBuilder#2045]
Hello, 
I am using the C# SDK. I wonder if it is possible to support text markdown in the "Text" filed of a Hero or Thumbnail card.

**Comment by alex182** [comment]
@miaosenwang what channel(s) is your bot on?

I have a bot on the MS Teams channel and I am using plain old HTML to format the text in my hero-cards.

**Comment by LarsLiden** [comment]
The native capabilities of each channel vary substantially.  Where channels do support markdown in fields the BotFramework supports it.

**Comment by miaosenwang** [comment]
@LarsLiden  I am using the Team channel, text markdown works in the IMessageAcitivity's text filed. So it is not because of the channel.

**Comment by miaosenwang** [comment]
@alex182 Hello Alex. I am using Team channel as well. Do you mind sharing more details? I created a HeroCard and set its Text field with some HTML tags "<b>something</b>", but the html tags showed up as part of the text.
