### ISSUE TITLE
Channel emulator: auth issue behind a proxy server

### ISSUE THREAD

**Issue by spulci** [Microsoft/BotBuilder#2049]
I'm experiencing an issue trying to authenticate Channel Emulator (v 3.5.23) to a Node.js bot running on localhost while using a proxy server configured in Windows. 

**Scenario to reproduce the bug:**

1.  Check that a proxy server is correctly configured to use your network on your IE Internet Settings. Also check that proxy will be ignored for local addresses

2. Start you bot running Node.js locally on your machine. (Bot could be a waterfall one or a mixed one with outgoing call to cognitive services e.g LUIS.ai)

3. Double check that inside your code, the bot uses your credentials for the ChatConnettor: AppID and AppPassword previously obtained from the Microsoft Bot Portal).

4. Start the Channel Emulator, enter your bot PATH exposed on your system as well as your  AppID and AppPassword and hit the CONNECT button

5. Wait a few secs and check the error message in the LOG section inside the channel emulator.  You could see one or two ETIMEDOUT errors for a POST call to this IP addresses (owned by Microsoft Ireland): 104.41.216.18 and 40.112.64.17 both contacted on port 443

You can't start a conversation with your bot and you won't be able to obtain a 202 HTTP "conversationUpdate" just like under a successful connection.

**Details:**
1. Note that Channel Emulator correctly use proxy to access the net when downloading an update
2. **Note that intercepting HTTP traffic using Fiddler makes no evidence of the above TIMEDOUT POST calls**
3. Channel Emulator is fully operational with a no credentials bot under a proxy server (due to the fact that no outgoing calls to Microsoft server are done)

**Comment by eanders-MS** [comment]
Hi @spulci Thank you for reporting this. It appears the emulator is not using the host proxy settings. I've created an issue to track this on the emulator's repository: https://github.com/Microsoft/BotFramework-Emulator/issues/67

**Comment by eanders-MS** [comment]
@spulci, We released a new emulator today (v3.5.25) that includes experimental proxy settings support. Could you please give it a try when you have a chance, and report back here if it works for you?

**Comment by spulci** [comment]
Here I am to report my test to you. Our proxy is under authentication and your fix seems not to support proxy with authentication.
Infact Bot Emulator now gives a new error (407-unauthenticated):

-> POST Refresh access token failed with status code: 407

Btw this is a workaround for the problem:

    Use fiddler as a tunnel for authenticated proxy. Mark "Automatically Authenticate" option under "Rules" menu
    Start the channel emulator and authenticate to your local bot obtaining a 202 conversation update :)

Please observe that your bot need to contact MS server to negotiate JWT. So you can now experience the same issue under a proxy server. To avoid this I strongly advice to use, under node.js, global-tunnel module (npm install global-tunnel) together with Fiddler running with the previous option. Remember to add this few lines of code to your bot to enable global-tunnel pointing to Fiddler proxy:

`var globalTunnel = require('global-tunnel');

process.env.http_proxy = 'http://127.0.0.1:8888';
process.env.https_proxy = 'http://127.0.0.1:8888';
globalTunnel.initialize();`

    You're now be able to have a full conversation with your bot using the channel emulator even under an authenticated proxy server.

**Comment by eanders-MS** [comment]
Hi @spulci Thanks for this info, and glad to hear there's a possible workaround with the Fiddler setting. I'll continue to work on this.

**Comment by glungu** [comment]
Hi can you help me out - I have a similar issue, but using global-tunnel does not seem to work. My nodejs bot and ms bot emulator are both on localhost. But luis is of course remote and I need to use proxy settings for luis.

1. without global tunnel proxy code, I can start conversation with my bot, but cannot access luis
2. when I add global tunnel proxy settings, I cannot even start conversation:

restify listening to http://[::]:3978
WARN: ChatConnector: receive - emulator running without security enabled.
ChatConnector: message received.
The Bot State API is deprecated.  Please refer to https://aka.ms/I6swrh for details on how to replace with your own storage.
WARN: ChatConnector: receive - emulator running without security enabled.
ChatConnector: message received.
UniversalBot("*") routing <null> from "emulator"
Session.beginDialog(/)
/ - waterfall() step 1 of 1
/ - Session.send()
/ - Session.sendBatch() sending 1 message(s)
The Bot State API is deprecated.  Please refer to https://aka.ms/I6swrh for details on how to replace with your own storage.
Error: Request to 'http://localhost:64767/v3/botstate/emulator/conversations/nnj6284k3jc7/users/default-user' failed: [500] INKApi Error
    at Request._callback (C:\SOURCE_GIT\asp-luisbot\node_modules\botbuilder\lib\bots\ChatConnector.js:535:46)
    at Request.self.callback (C:\SOURCE_GIT\asp-luisbot\node_modules\request\request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\SOURCE_GIT\asp-luisbot\node_modules\request\request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\SOURCE_GIT\asp-luisbot\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
