### ISSUE TITLE
Support multiple AppSecret and AppId

### ISSUE THREAD

**Issue by PrimeObjects** [Microsoft/BotBuilder#205]
If I want to have a bot as a service. I may want to issue different AppSecret to different apps, so I can stop the connection from an app by simply expire the appsecret. based on my understanding we have the following setting in web.config. How can I keep a list of AppSecret in a database table, so I can control the accessibility of different apps with different AppSecrets?

<add key="AppId" value="YourAppId" />
<add key="AppSecret" value="YourAppSecret" />

Thanks
Gary

**Comment by tomlm** [comment]
What language?

On c# you can do your own basic auth by commenting out the botauthirization attribute and process the header yourself.

For outgoing when you create the connector client you can new up your own client credentials instance passing in any appid/app secret.

Sent from my tumbs
________________________________

**Comment by PrimeObjects** [comment]
Hi Tom,
Thank you for the response. I went to botframework and recognized that AppId and AppSecret will be generated by botframework. However it seems botframework does not allow us manage a appid/appsecret database, unless I register same bot for each new client. 

Cheers
Gary

**Comment by tomlm** [comment]
Yes, that is correct.

We would like to support programmatic creation of bots but it is in our backlog

**Comment by Roath** [comment]
Hey Guys
I'm testing right now as I cannot get the ConnectorClient to work. I always get access denied.
I created my own controller ( in VB.net) as I am adding this to an existing collector service I have for Facebook webhooks for messages etc.

How do I add the appid and secret to the ConnectorClient  , I have tried adding the headers to the DefaultRequestHeaders but didn't work.

Thanks for such an exciting framework.. only started playing 4 hours ago and have lots working already.. I love it!!. Got web chat and facebook working, but I'm really hanging out for the Skype Bot, but I have not got the email to allow me to set that up yet! :)

Don't know if this is the right area for you guys, but I am curious if the webchat can persist between refreshes. It seems the customer looses everything on a page reload.

Many thanks

Rob

**Comment by tomlm** [comment]
You can pass them as parameters to the constructor
Client  = New ConnectorClient(appId, appSecret)

**Comment by tomlm** [comment]
That is correct.  We do not (yet) support programmatic creation of bots.

**Comment by Roath** [comment]
Thanks Tom.. I had worked it out shortly afterwards.. hence editing the original post!

Have most things working now.. but I can't work out how to use the web chat 'nicely'. There is no way to set the users name or persist the chat between refreshes ( that I can see?)

I see people are using the Skype bot.. I don't seem to be allowed to create one.. I get a form to fill out , submit it and never get an email. I'm in NZ , so I should be part of the initial trial .. any thoughts?

Sorry, I'm sure this is not your area, but does not seem to much info about this stuff around yet!

Many thanks

Rob

**Comment by Stevenic** [comment]
@Roath they're approving people pretty fast so just hang tight.

**Comment by Stevenic** [comment]
Re-open if you need Rob
