### ISSUE TITLE
Luis related test case failed

### ISSUE THREAD

**Issue by zhou-xinghai** [Microsoft/BotBuilder#2051]
hi, all luis related test case like /basics-naturalLanguage /basics-multiTurn failed to work suddenly.
return Oops. Something went wrong and we need to start over.
SyntaxError: Unexpected token A in JSON at position 0.
can you please take a look and fix the problem. all my luis related project don't work now. thanks

![image](https://cloud.githubusercontent.com/assets/8207172/22015228/1f1a60a6-dcdc-11e6-87b0-13605fe2deac.png)

**Comment by admeister** [comment]
Also getting the same problems.

**Comment by strangecyan** [comment]
Same here.

**Comment by VishalWaman** [comment]
An item with the same key has already been added. 

LUIS NOT WORKING

**Comment by chetanmekha** [comment]
facing the same issue.

**Comment by jsebrech** [comment]
Same here. It seems that luis integration is broken for everyone.

**Comment by admeister** [comment]
Currently talking to someone from https://twitter.com/AzureSupport and have raised a case on their Support Site. Will let everyone know what happens.

**Comment by PrasadGautham** [comment]
The luis response to all queries are like this now "An item with the same key has already been added."
:|

**Comment by admeister** [comment]
Fix:
Update your LUIS endpoint hostname from **api.projectoxford.ai** to **westus.api.cognitive.microsoft.com**

**Comment by karlbarber** [comment]
![capture](https://cloud.githubusercontent.com/assets/17829813/22018354/5a3f1bda-dca6-11e6-8e41-35ac052ec090.JPG)

**Comment by chetanmekha** [comment]
tried with above changes, getting below error
{ "statusCode": 500, "message": "Internal server error", "activityId": "68749226-8fe1-4ef6-bb1f-a42bb0bd2f99" }

**Comment by VishalWaman** [comment]
@admeister can you share a sample URI that worked for you ?

**Comment by VishalWaman** [comment]
Seems Working

**Comment by jsebrech** [comment]
Works for me now as well.

**Comment by dandriscoll** [comment]
Hi @zhou-xinghai, @admeister, @strangecyan, @VishalWaman, @chetanmekha, @jsebrech , @PrasadGautham, and @karlbarber, the LUIS endpoint should be working again. Please at-mention or open a new issue if you encounter further issues.

**Comment by TakesTheBiscuit** [comment]
@dandriscoll 'An item with the same key has already been added.'
3/2/2017 15:25 GMT

**Comment by dandriscoll** [comment]
@TakesTheBiscuit I'll forward to the team

**Comment by jameslew** [comment]
@TakesTheBiscuit - did you take the fix from earlier in the thread about changing the endpoint from api.projectoxford.ai to westus.api.cognitive.microsoft.com?

--jim

**Comment by TakesTheBiscuit** [comment]
Apologies @jameslew and @dandriscoll - it seems that error is coming up when you submit a duplicate &q within the query string on GET - to be honest i hadn't expected that would be the error so it threw me off.
I think the error is too inconclusive perhaps? 
For example
https://apiurl/endpoint?key=xxx&q=this+is+query&q=and+the+query

produces the same error as this thread which is now ranked highly on Google (hence how i ended up here)
