### ISSUE TITLE
LUIS stop working.

### ISSUE THREAD

**Issue by chetanmekha** [Microsoft/BotBuilder#2052]
Hello Team,
From morning I am facing strange issue with LUIS.
"An item with the same key has already been added." , I have generate the key from Azure before 31 Dec but still facing above issue.
please help me out on the same.

**Comment by PrasadGautham** [comment]
Same here...all of a sudden..... :| ...no idea why

**Comment by karlbarber** [comment]
![capture](https://cloud.githubusercontent.com/assets/17829813/22018340/4388fad2-dca6-11e6-95c6-5a52ada1f172.JPG)

**Comment by karlbarber** [comment]
see  #2051 for the new details

**Comment by chetanmekha** [comment]
tried with above changes, getting below error
{ "statusCode": 500, "message": "Internal server error", "activityId": "68749226-8fe1-4ef6-bb1f-a42bb0bd2f99" }

**Comment by dandriscoll** [comment]
Hi @chetanmekha, @PrasadGautham, and @karlbarber, the LUIS service had an interruption earlier but should be operating again. I'm closing this issue as all of our tests are passing. Please at-mention me or open a new issue if you have any further problems.
