### ISSUE TITLE
Upload local image files using Bot Framework

### ISSUE THREAD

**Issue by hahamark1** [Microsoft/BotBuilder#2053]
Within the facebook documentation the following curl command
curl  \
  -F 'recipient={"id":"USER_ID"}' \
  -F 'message={"attachment":{"type":"image", "payload":{}}}' \
  -F 'filedata=@/tmp/shirt.png;type=image/png' \
  "https://graph.facebook.com/v2.6/me/messages?access_token=PAGE_ACCESS_TOKEN"   

Is this option also available within the node js SDK?

Thanks!

**Comment by LarsLiden** [comment]
Are you looking for something beyond a [HeroCard](https://docs.botframework.com/en-us/core-concepts/reference/#herocard)?

**Comment by dandriscoll** [comment]
Hi @hahamark1, we have two options for including attachments.

1. You can use our attachment API to upload your file to our server. You can send a POST as described on this part of our API page: https://docs.botframework.com/en-us/restapi/connector/#!/Conversations/Conversations_UploadAttachment There may be a Node.js wrapper but I'm not seeing it in our sample.
2. If the file is small enough, you can load it into memory and turn it into a base64 data URI. If you search for "base64" on this page, you'll see an example. https://docs.botframework.com/en-us/core-concepts/attachments/

At the moment it looks like our samples could do a better job illustrating this, but hopefully this will get you started while we work on that.

**Comment by dandriscoll** [comment]
https://github.com/Microsoft/BotBuilder-Samples/issues/55

**Comment by Andrea-Orimoto** [comment]
Hi @hahamark1, I'm assuming the sample above helped you out, so I'm closing this issue. Feel free to reopen it if this is not the case. Thanks!

**Comment by AmolPawarGitHub** [comment]
Hi All,
I m using WebChat channel,  user uploads their error screenshot to webchat, e.g. screenshot is stored on the path D:\ErrorLog\SS.png, so how can I get this path in bot framework, I want to store that image to DB. at this moment I testing attachment upload on Emulator and i am getting path as  "http://127.0.0.1:44185/v3/attachments/ne7djbemc9f40bifi/views/original/SS.PNG"

**Comment by Jefwillems** [comment]
Hello all, i'm currently stuck on the same issue. (using Node sdk v4) 
None of the above links are still working. Any help?
