### ISSUE TITLE
Skype Calling Bot - assigning a phone number

### ISSUE THREAD

**Issue by alexsorokoletov** [Microsoft/BotBuilder#2055]
First of all, thank you for the demos and for the framework itself.
I was able to run demo-skypecalling bot and call the bot using Skype. Great!
Hardest part was to find out which urls should I put into the Skype config page and bot config, then wait around 5 minutes for settings to propagate (especially when using ngrok and changing url every day).

Skype has a paid feature called [Skype Number](https://www.skype.com/en/features/online-number/).
How do one gets a phone number assigned to a Skype calling bot?

I'm fine paying for the Skype Number for the bot 👍

**Comment by KrishnanA** [comment]
Currently adding a phone number to a Skype calling bot is not supported. We will evaluate enabling this for a later release.

**Comment by alexsorokoletov** [comment]
Thank you!

Alex

**Comment by DanielTizon** [comment]
Any advance on it? Other companies like Nuance are already offering a complete package for create a bot and be able to use a phone number to answer phone calls. So, are you going to add this feature, or should we try other alternatives?
