### ISSUE TITLE
[Question] Authentication Callback Details

### ISSUE THREAD

**Issue by deubaka** [Microsoft/BotBuilder#206]
We're creating a bot with `BotConnector` and we need to have users who install to bot verified first on our login page if they are really customers of ours. So the desired flow would be (in this case, Slack), `Add Foo Bot` → `Foo Login Page` → `If success, redirect to Slack OAuth (botframework provided)` → `Save user account with Slack Team ID`.

So, every time a user tries to ask the bot, it would go, `Lookup Team ID to get API token to user our API` → `Proceed with query to our API`.

 We did have `Botkit` before migrating totally to `botbuilder`, and it was clear back then on how to get those details/events.

How do we go about it. Given this scenario what would be the most agnostic solution to our needs.

Cheers,
Deu

**Comment by msft-shahins** [comment]
@deubaka connector provides [contextual stores](http://docs.botframework.com/connector/tracking-bot-state/#navtitle) that you can use to persist different access tokens that your bot needs for an authenticated user. 

In your case, you can register a callback to be called when the slack OAuth flow completes, and save the access tokens (or any other data needed for an authenticated user) in the botUserData (you can choose to store data in different contextual stores based on your need). Look at the [SimpleFacebookAuthBot](https://github.com/Microsoft/BotBuilder/tree/master/CSharp/Samples/SimpleFacebookAuthBot) and the way it saves the facebook access token in BotPerUserInConversationData store as an example. 

After completion of the auth flow, with any incoming message from the authenticated user, connector will pass the access tokens that your bot have written to the contextual stores. Then your bot can call into your api with appropriate access token.

**Comment by deubaka** [comment]
@msft-shahins Thank you for the reply. 

We don't necessarily need to access to a persisted token of a user/channel. The token is from our API that needs to be paired with a unique channel identifier, in the case of Slack, the TeamId.

I have to take a look at the example you've provided and see how it goes. Would this work the same with NodeJS? 

Cheers,
Deu

**Comment by msft-shahins** [comment]
@deubaka You can use the contextual stores to persist any data required for your api call, e.g. TeamId of the user. 

NodeJS doesn't implement resume yet but if you look at the C# implementation it is straight forward to replicate on the Node side. We are looking into adding support for resume conversation to NodeJS side in near future.

**Comment by adaddeo** [comment]
Any new hints on how to get this information on NodeJS?
