### ISSUE TITLE
Handling multi-line / fast responses

### ISSUE THREAD

**Issue by deniztasdogen** [Microsoft/BotBuilder#2061]
When user says "help" to my bot, it sends prompt.choice() with 7 different options. 

But sometimes, especially if it's the first message of the user in 1-2 days, bot responds slowly. I guess it's opening connections etc.

A couple of users did this. I think it skipped states because of 3 fast messages.
User: Help
User: Help
User: Help
Bot: -options here-
Bot: I didn't understand
Bot: My bot code is having issues.

Same problem may happen if user wants to add one last thing to the chat before bot can handle the first request.

Is there anyway to overcome this issue?

**Comment by palmerabollo** [comment]
This issue is related somehow https://github.com/Microsoft/BotBuilder/issues/2056

**Comment by Andrea-Orimoto** [comment]
Hi @deniztasdogen , did the related issue pointed above helped you out?

**Comment by carlosscastro** [comment]
Closing the issue for now. @deniztasdogen feel free to reopen if the issue reference above did not help you.
