### ISSUE TITLE
Accessing to callstack elements easily

### ISSUE THREAD

**Issue by tahsintahsin** [Microsoft/BotBuilder#2062]
Hello,
I need to extract which dialog the user is in and in which waterfall step. I am able to access them by:
`session.sessionState.callstack[session.sessionState.callstack.length-1].id 
`
and
`session.sessionState.callstack[session.sessionState.callstack.length-1].state["BotBuilder.Data.WaterfallStep"]`
Is there any other way to access them without going that deep?
Thanks

**Comment by willportnoy** [comment]
I don't think so - you might consider adding helper methods for those expressions.

What are you trying to accomplish?

**Comment by tahsintahsin** [comment]
I am running a separate NLP server to do some sentiment analysis. But in some dialogs, like /whatisyournamedialog, I don't want to bother my server at all.

**Comment by Stevenic** [comment]
There are a couple of helper methods you can use to simplify things:

```
let ignore = false;
let stack = session.dialogStack();
builder.Session.forEachDialogStackEntry(stack, false, function (entry) {
     switch (entry.id) {
          case '/whatisyournamedialog':
               ignore = true;
               break;
     }
});
```

**Comment by Stevenic** [comment]
Closing this but please feel free to comment.
