### ISSUE TITLE
Direct Line sending more ConversationUpdate activities than it used to

### ISSUE THREAD

**Issue by dandriscoll** [Microsoft/BotBuilder#2065]
Hello bot developers! This isn't a real issue -- it's an announcement from the Bot Framework team.

Today we rolled out a change where Direct Line will send more ConversationUpdate messages than it used to.

Old behavior: Direct Line sends a ConversationUpdate activity when the conversation is started
New behavior: Direct Line sends a ConversationUpdate activity when the conversation is started **and** when each user joins.

If you're using Direct Line 1.1 and you're seeing a ConversationUpdate activity after every message the sends, you're probably not populating the From property in your messages. You can fix this issue by choose an ID and sending that in the From field. You can read more about this issue here: https://docs.botframework.com/en-us/technical-faq/#why-does-my-direct-line-conversation-start-over-after-every-message. This issue does not exist in Direct Line 3.0.

Please let us know if you encounter any problems.

**Comment by zhou-xinghai** [comment]
hi issue 2071 https://github.com/Microsoft/BotBuilder/issues/2071 
does it get affected by your latest update. Can you pls take a look at my issue. My project don't work now. it's urgent .thanks.

**Comment by dandriscoll** [comment]
Hi @zhou-xinghai, I took a look at the other issue but at the moment we're not seeing this with other bots. Let's discuss on the other GitHub issue and try to determine the cause there.
