### ISSUE TITLE
expressions instanceof RegExp

### ISSUE THREAD

**Issue by kazsharp** [Microsoft/BotBuilder#2066]
I use BotBuilder on Node-RED.
When I use IntentDialog#matches(<RegExp>, function(session) { ... }), I got error "Oops. Something went wrong and we need to start over.".
And I found that "expressions instanceof RegExp" returns false in RegExpRecognizer.ts(line 46).
(I know the source is RegExpRecognizer.js not RegExpRecognizer.ts actually)

I edited the source from "expressions instanceof RegExp" to "expressions.constructor.name === 'RegExp'", then my programs worked correctly.

My source is below.

var connector = new context.global.builder.ChatConnector({
    appId: '************************************',
    appPassword: '****************************'
});
var bot = new context.global.builder.UniversalBot(connector);
var intents = new context.global.builder.IntentDialog(); 
bot.dialog('/', intents);

intents.matches(
    /^ping/i,
    function(session) {
        addAddress(session.message.address);
        session.send('pong');
    }
)
.onDefault(function(session) {
    addAddress(session.message.address);
    session.send("I'm sorry. I didn't understand.");
});

**Comment by Stevenic** [comment]
I'm adding a check that uses ducktyping, Should be released today or tomorrow.

**Comment by Stevenic** [comment]
Just released v3.7.0 with fix
