### ISSUE TITLE
repeated questions in Formbuilder

### ISSUE THREAD

**Issue by NaiduGiridhar** [Microsoft/BotBuilder#2068]
When i am pushing the questions through Formbuilder. Questions are repeating .How to avoid this issue

**Comment by willportnoy** [comment]
Do you see any exceptions in the debugger?

**Comment by msft-shahins** [comment]
@NaiduGiridhar have you had a chance to debug your bot? My guess is that your bot code is causing an exception in the Formbuilder and as a result you see the repetition in the questions. Closing this issue because of the age. Feel free to open another issue if you still hit this.

**Comment by willportnoy** [comment]
@NaiduGiridhar can you look for exceptions in your production tracing?
