### ISSUE TITLE
Support thumbsup/thumbsdown emojis

### ISSUE THREAD

**Issue by palmerabollo** [Microsoft/BotBuilder#2069]
The [current EntityRecognizer](https://github.com/Microsoft/BotBuilder/blob/master/Node/core/src/dialogs/EntityRecognizer.ts#L65-L66) does not support thumbsup and thumbsdown emojis (👍 and 👎). It would be interesting to add them to the valid yes/no answers.

If you think it's a good idea I can send a PR.

**Comment by Andrea-Orimoto** [comment]
@palmerabollo, please go ahead and submit the PR if you have this coded already. Will close this issue, we'll deal with this in the PR. Thanks!
