### ISSUE TITLE
Receiver address it different than slack username

### ISSUE THREAD

**Issue by ahmettaha** [Microsoft/BotBuilder#207]
Hello,

I working on nitiating a conversation with ConnectorClient and sendmessage. I can send a message with the channelid and address. However, when I initiate a conversation with send message, it prepends the addess to the beginning of the message. However, I would prefer it is the slack username of the user. Otherwise, it will be just confusing for the user. Is this possible?

something like this is displayed on slack:

@U0K7GQ189 Hey, what's up homey?

**Comment by ahmettaha** [comment]
Is there no hope for this? :(

**Comment by craigjensen** [comment]
Sorry for the delay in responding.  We're working on a fix to remove the prepended @mention for direct messages on Slack.  It's in testing now and should be deployed soon.

**Comment by Stevenic** [comment]
Are you still seeing this issue?

**Comment by ahmettaha** [comment]
no. it is fixed.

Thanks
