### ISSUE TITLE
Bot brings responses of previous conversations as well, along with the ones which were currently made.

### ISSUE THREAD

**Issue by PrasadGautham** [Microsoft/BotBuilder#2070]
The chat bot is designed using directline API.Whenever I make a conversation with the bot at the time when the server is busy or down, the bot would n't show any response, (as is expected). But later on when I make another conversation, the bot brings out the responses of all the previous conversations as well along with the response for the current query. Is there any workaround to prevent this scenario?????

**Comment by dandriscoll** [comment]
Hi @PrasadGautham, can you send your bot handle or an example conversation ID?

We've never seen this behavior (and this is not how the system is designed) but will investigate if we know of an example.

**Comment by PrasadGautham** [comment]
Hi,
      The issue never occurs while using Bot framework emulator. But when the server is busy or the request is taking to much time to load, then the previous request is send again, by the directline api or microsoft server.  
    So I face issue while using PromptDialog.Text where in while the bot is awaiting for a response from the user, the bot automatically takes the previous query as the request. So the response from the user is skipped(ie. no time is given for the user to respond, instead the bot takes the previous request from the user, as the string for promptdialog.Text) and the next line of code is getting executed. This, as I said never occur with the emulator. 
    
                   Here I will also attach the snapshot of the bot while facing issue and otherwise, so that you could better understand my question. :)
When there is issue:
![not awaiting for response](https://cloud.githubusercontent.com/assets/23548463/22138252/b6633bec-df05-11e6-9b9e-ab7699c496a1.PNG)
When it works fine:
![now its working](https://cloud.githubusercontent.com/assets/23548463/22138411/78908440-df06-11e6-92c6-47ac3f818008.PNG)


Regarding the bot handle, This is actually designed for an enterprise,so I dont know if I could do it or not, but if you could sent me your email, I could sent it. ..

**Comment by dandriscoll** [comment]
Hi @PrasadGautham, please email at dan.driscoll@microsoft.com.

**Comment by PrasadGautham** [comment]
Hi 
    Currently, our VM is in Azure. Will there be any improvement in the response time, if we move it to Azure website?

**Comment by dandriscoll** [comment]
Not necessarily. Azure Web Apps and VMs have similar performance. There are cases where one is faster than the other, but we would need to look more closely at specific circumstances to say which is better.
