### ISSUE TITLE
critical problem: directline can't get reply msg

### ISSUE THREAD

**Issue by zhou-xinghai** [Microsoft/BotBuilder#2071]
hi, I use direct line to communicate with bot framwork. It can send activity successfully but can't receiving Activities from the bot. it works all the time before,but failed several hours ago.
Can you tell me the reason or how to fix it? 
ps. the chat dialog in my bot on https://dev.botframework.com/bots don't work either, i mean it can't get reply with url like “ https://directline.botframework.com/v3/directline/conversations/89inabcHgj1I/activities?watermark=4”.

**Comment by dandriscoll** [comment]
Hi @zhou-xinghai, can you send your bot handle? I'm not seeing any problems with Direct Line or the Web Chat control but I can investigate to see what's happening with your bot.

**Comment by zhou-xinghai** [comment]
thanks, seems goes fine now..
