### ISSUE TITLE
How can I validate a code with builder.Prompts in Nodejs

### ISSUE THREAD

**Issue by 0GiS0** [Microsoft/BotBuilder#2072]
Hi folks,

I would like to validate a code in a waterfall dialog but I cannot see examples about this. The idea is the user recieves a code and he has to validate with the bot that the code he entered is the right one (maybe two retries would be useful). I'm implementing a second factor authentication so the bot cannot share the code with the user in order to demostrate that he has real access to the operation.

Any ideas?

thanks!

**Comment by aekynr** [comment]
here is a solution;
https://github.com/Microsoft/BotBuilder-Samples/tree/86ebba09bfe5ccfdbbd66eaf9c7d19fa9bb239d1/Node/demo-ContosoFlowers/bot

**Comment by Andrea-Orimoto** [comment]
Hi @0GiS0, did the sample above help you out?

**Comment by carlosscastro** [comment]
Closing for now. Let us know if that sample did not work!
