### ISSUE TITLE
FormFlow Validate entire object

### ISSUE THREAD

**Issue by srozga** [Microsoft/BotBuilder#2080]
In FormFlow, there is a way to validate each field value which we are using successfully. Is there a way to validate the entire object before it is sent to the confirmation question? In our scenario, the entire object's values need to be validated against some web services to see if it even makes sense. 

I am trying a few hacky things, but would be nice to have this in the API, unless I am missing it! :)

**Comment by chrimc62** [comment]
The field validation has access to the whole state object, so you can do whatever you need to do to validate it on any field step.  

Whether this is adequate or not depends very much on what you want to do if it is not.  Could you describe your desired behavior?   Field definitions can be fake (that is what a confirmation is) and there are also ways you can dynamically define them (through field.SetDefine) and control the flow to the next step (through field.SetNext delegate).  So you could instantiate a Confirmation object and if it didn't match what you expected control where you go to fix it.

**Comment by srozga** [comment]
Sorry for dropping out of this one. If the intent behind the flow API is to depend on fake field for a final validation step, that's great, we'll use it. Just making sure as it seemed somewhat hacky.

A few more things about the form flow:
- Is there a way to customize which words are interpreted as cancel the entire form?
- Is there a way to get access to the IDialogContext inside of the validate or prompt callbacks? For example, we have a custom way of logging a few details about the conversations before sending it over to the IDialogContext and we would like to format the messages a certain way, so it would be nice to have more control over that and being able to call IDialogContext.PostAsync ourselves as opposed to just giving form flow a string.

**Comment by chrimc62** [comment]
You can control the cancel words in FormConfiguration.Commands.
To control the message output you can define your own PromptAsyncDelegate and pass it to you builder using the Prompter method.  This gives you full control of prompts and lets you rewrite them.  We just did a release where we added state and field to that as well.
