### ISSUE TITLE
LUIS: Turning off active learning

### ISSUE THREAD

**Issue by jaskiratr** [Microsoft/BotBuilder#2081]
Hi,
Is there as way to turn off active learning for LUIS? I couldn't find the specific Node.js reference for the same.
Any help would be appreciated.

Thanks!

**Comment by cahann** [comment]
can you please follow up with luservice@mcirosoft.com on this.

**Comment by jaskiratr** [comment]
Thanks @cahann. Wrote to them.

I'm trying to recall something I came across in past. Isn't there a line of code in node.js BotBuilder script that stops LUIS from registering data that it doesn't recognize?
I'll keep digging the docs meanwhile...

**Comment by jaskiratr** [comment]
@cahann is that the correct email address for Luis Support?

**Comment by Andrea-Orimoto** [comment]
Hi @jaskiratr, I'm assuming you followed up with the luis team directly via email (yes, that's the right email address), so I'm closing this issue. Feel free to reopen if needed. Thanks!
