### ISSUE TITLE
[Skype Channel] Controlling horizontal or vertical placement of buttons

### ISSUE THREAD

**Issue by pfloresl** [Microsoft/BotBuilder#2082]
On my application buttons appear vertically layout and sometimes horizontal.  the text on the buttons is the exactly the same. Is there a way of controlling this?  Using node on SKype as client.

**Comment by dandriscoll** [comment]
Hi @pfloresl, can you provide an example of the button layout you would like? Can you include a screenshot or a diagram?

**Comment by pfloresl** [comment]
![untitled 3](https://cloud.githubusercontent.com/assets/4304843/22176625/d8381c2e-dfc3-11e6-8457-6badc239c16a.jpg).  i like to get the second style sometimes. they feel like quick replies in FB.    thanks.

**Comment by gakarnik** [comment]
Can we have the same support for all channels and not only skype? It would be great to have an option to specify the buttons layout as horizontal or vertical.

**Comment by nwhitmont** [comment]
@gakarnik each channel supports different message formatting options. Some have more options (eg. Slack), and some have less (eg. Telegram/Kik).  As the Bot Framework is still in Preview state, we are working to bring you more options for custom message formatting in the near future.  Look out for some updates at this year's MS Build conference.

**Comment by nwhitmont** [comment]
@pfloresl currently the formatting of the buttons is handled by the Skype client and is not directly configurable via Bot Framework SDK.  [For more information on messaging and buttons click here](https://docs.botframework.com/en-us/skype/getting-started/#messages)
