### ISSUE TITLE
Disable WebChat

### ISSUE THREAD

**Issue by akakoychenko** [Microsoft/BotBuilder#2083]
I want to disable WebChat channel because my bot doesn't support it and I don't want this channel communication to be reviewed.

The phrase "Your bot is enabled on this channel. Edit the channel to change this setting." is appeared when I push "Enabled - Yes" link, but there are no buttons for disabling the channel in the channel configuration menu

**Comment by dandriscoll** [comment]
Hi @akakoychenko, if the Web Chat configuration page is empty (see screenshot), the channel is disabled.

Web Chat is only active when you add a "site" to your bot.

![image](https://cloud.githubusercontent.com/assets/5069805/22175725/bd857c50-dfaf-11e6-9d74-2e65990591f8.png)

**Comment by Andrea-Orimoto** [comment]
hi @akakoychenko, were you able to figure this out?

**Comment by akakoychenko** [comment]
yep
