### ISSUE TITLE
'ru' (russian) locale for NodeJs BotBuilder

### ISSUE THREAD

**Issue by hardsky** [Microsoft/BotBuilder#2084]
Hi!
It would be nice to add an other one locale.

**Comment by Andrea-Orimoto** [comment]
hi @hardsky, you can go to [this folder](https://github.com/Microsoft/BotBuilder/tree/master/Node/core/lib/locale), create an "ru" subfolder copying the content from the "en" folder, translate the strings, and then submit a [pull request](https://help.github.com/articles/creating-a-pull-request/). Closing this issue for now, looking forward to your PR. Thanks!
