### ISSUE TITLE
StrictEntityToType.Interpret method returns wrong values in some cases

### ISSUE THREAD

**Issue by gakarnik** [Microsoft/BotBuilder#2088]
While working with StrictEntityToType.Interpret method, I noticed that it fails to return dates of the week when its the first week of the year (2017-W01, 2018-W01 etc) Seems like this part of the code does not get executed as `week != resolution.Week` is false. So it returns a date range with Start = 2017-01-01, After = 2018-01-01 which is calculated for the year component.

```
    var week = calendar.GetWeekOfYear(start, rule, firstDayOfWeek);
    if (resolution.Week >= 0 && week != resolution.Week)
    {
        start = start.AddDays(7);
        start = new DateTime(start.Year, start.Month, start.Day, 0, 0, 0, 0, start.Kind);
        while (start.DayOfWeek != firstDayOfWeek)
        {
            start = start.AddDays(-1);
        }
            after = start.AddDays(7);
            continue;
    }
```

**Comment by gakarnik** [comment]
@willportnoy It is actually the same case for month and day since both need to be initialized with value 1. Hour, minute, second should be fine since they can be initialized with 0. I am planning to put up a pull request to handle month and day.

**Comment by nwhitmont** [comment]
@gakarnik Are you still experiencing the issue after upgrading to [BotBuilder 3.8.1](https://www.nuget.org/packages/Microsoft.Bot.Builder/)?

**Comment by gakarnik** [comment]
I upgraded to BotBuilder 3.8.1 and I don't experience this issue anymore. Thanks for the fix!
