### ISSUE TITLE
Choice prompt in Node.js with multiple selections

### ISSUE THREAD

**Issue by weiligao** [Microsoft/BotBuilder#2091]
I would like to create a choice prompt in Node.js that allows the user to make multiple selections, just like in FormFlow for .NET (see the toppings prompt of the [Simple Sandwich Bot][1] where the user was able to select multiple toppings at the same time: peppers, lettuce and tomato).

Is this feature already available in Node.js? If so, is there already an example for that? Would this also be possible with buttons instead of the list shown in the Simple Sandwich Bot example?

  [1]: https://docs.botframework.com/en-us/csharp/builder/sdkreference/forms.html#simpleSandwichBot

**Comment by Stevenic** [comment]
Unfortunately we don't have a multi-select prompt in Node yet.  It's on our todo list to add but for now you'd need to write your own.

**Comment by Stevenic** [comment]
Closing for now but please feel free to comment.

**Comment by dalekunce** [comment]
any update on this feature? cc @Stevenic

**Comment by dpdonohue** [comment]
+1 for this feature

**Comment by an0o0nym** [comment]
+1 It would be awesome to have this feature!

**Comment by wacoder** [comment]
+1 for the feature

**Comment by Shon-Elias** [comment]
+1 for the feature

**Comment by sevetseh28** [comment]
Has anyone been able to write your own multiple choice recognizer? please share! Thanks

**Comment by ahle** [comment]
Does anyone know an alternative solution (multi-choices) for NodeJS ?

**Comment by jonathanhotono** [comment]
Any update on this feature?

**Comment by sprabhus** [comment]
+1 for this feature

**Comment by Jinu1994** [comment]
+1 for the feature

**Comment by serraventura** [comment]
+1

**Comment by mjimenezMBT** [comment]
+1

**Comment by esanchezlMBT** [comment]
+2

**Comment by chetanclozio** [comment]
@Stevenic  Any update on this? Or MS guy's skip this functionality?

**Comment by alexander-potemkin** [comment]
+1

**Comment by Anusri27** [comment]
+1 for this feature

**Comment by SonicZentropy** [comment]
+1 this is required before I can use MS Bot Framework

**Comment by Aleimar** [comment]
Would be exiciting and helpful if this feature is available .

+1

**Comment by EricDahlvang** [comment]
This is possible using the attachment prompt, and an adaptive card.  Or, the community library's AdaptiveCardPrompt: https://github.com/BotBuilderCommunity/botbuilder-community-js/blob/master/libraries/botbuilder-dialog-prompts/src/adaptiveCardPrompt.ts
