### ISSUE TITLE
Choice and confirm prompts do not show buttons when IMessage is used as prompt message

### ISSUE THREAD

**Issue by weiligao** [Microsoft/BotBuilder#2094]
When using a string as the prompt message, the buttons are shown:
`builder.Prompts.confirm(session, "Test", {listStyle: builder.ListStyle["button"]});`

However, when an IMessage is used as the prompt message, no buttons are shown:
```javascript
var msg = new builder.Message(session).text("Test");
builder.Prompts.confirm(session, msg, {listStyle: builder.ListStyle["button"]});
```

**Comment by willportnoy** [comment]
similar issue: https://github.com/Microsoft/BotBuilder/issues/1979

**Comment by Stevenic** [comment]
If you pass in an `IMessage` to any of the prompts you'll need to add your own buttons. This is by design as we have to give developers a way of completely customizing the message sent for a prompt. Sending an IMessage is how you do that.

**Comment by Stevenic** [comment]
Closing for now but please feel free to comment further.
