### ISSUE TITLE
How the UserData is stored?

### ISSUE THREAD

**Issue by miaosenwang** [Microsoft/BotBuilder#2097]
User data is set like this:
BotData response = await stateClient.BotState.SetUserDataAsync(activity.ChannelId, activity.From.Id, botData);

From the documentation, it is unclear to me where and how the user data is store.  Is it encrypted? Is this data cached on the user client? When I request to delete the user data, is there a possibility that not all user data got removed (e.g. cached copies)?

**Comment by dandriscoll** [comment]
Hi @miaosenwang, it depends on how you implement your bot.

If you **implement your own bot state store**, the store can be encrypted, deleted, and completely controlled by you. This approach is suitable if you're concerned about where your data is stored, for performance or compliance reasons.

If you **use our free bot state API**, the data is stored encrypted on our servers. We delete the data when you send a delete request.

Most implementers switch to using their own bot state store. You can use our BotBuilder-Azure package to implement your own state store based on your own Azure table or DocDB storage: https://github.com/Microsoft/BotBuilder-Azure

**Comment by willportnoy** [comment]
some extra information about state storage: https://docs.botframework.com/en-us/technical-faq/#where-is-conversation-state-stored

**Comment by miaosenwang** [comment]
@dandriscoll @willportnoy  Thank you for the response. They are very informative.

**Comment by dandriscoll** [comment]
Closing as it looks like we've answered the question. Please feel free to at-mention or open a new issue if you'd like other details.
