### ISSUE TITLE
Type 'Microsoft.Bot.Connector.Activity' in Assembly 'Microsoft.Bot.Connector, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' is not marked as serializable.

### ISSUE THREAD

**Issue by lonche** [Microsoft/BotBuilder#2099]
So far i have this : 

```
public async Task<HttpResponseMessage> Post([FromBody]Activity activity)
        {
            if (activity.Type == ActivityTypes.Message)
            {
                //luis 
                try
                {
                    await Conversation.SendAsync(activity, () => new RootLuisDialog(activity));
                }
                catch (Exception ex)
                {
                }

            }
            else
            {
                HandleSystemMessage(activity);
            }
            var response = Request.CreateResponse(HttpStatusCode.OK);
            return response;
        }
```

When user posts, bot forwards to RootLuisDialog.

In the RootLuisDialog, have constructor 
```
 Activity activity;

public RootLuisDialog(Activity activity)
        {
            this.activity = activity;
        }
```

This constructor i use to forward to another Facebooklogin dialog. It depends on proper LUIS intent.

`await Conversation.SendAsync(activity, () => SimpleFacebookAuthDialog.dialog);`

I used [this ](https://github.com/Microsoft/BotBuilder/tree/master/CSharp/Samples/SimpleFacebookAuthBot) to make oAuth authentication to Facebook.

So really i don't know what the problem is. But every time when post posts message, after that it throws an exception.

StackTrace for this : 

> " at System.Runtime.Serialization.FormatterServices.InternalGetSerializableMembers(RuntimeType type)\r\n at System.Runtime.Serialization.FormatterServices.GetSerializableMembers(Type type, StreamingContext context)\r\n at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitMemberInfo()\r\n at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder)\r\n at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(WriteObjectInfo objectInfo, NameInfo memberNameInfo, NameInfo typeNameInfo)\r\n at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, Header[] inHeaders, __BinaryWriter serWriter, Boolean fCheck)\r\n at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph, He ader[] headers, Boolean fCheck)\r\n at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph)\r\n at Microsoft.Bot.Builder.Internals.Fibers.FormatterStore1.Microsoft.Bot.Builder.Internals.Fibers.IStore<T>.Save(T
>   item)\r\n   at
>   Microsoft.Bot.Builder.Internals.Fibers.ErrorResilientStore1.Microsoft.Bot.Builder.Internals.Fibers.IStore.Save(T item)\r\n at Microsoft.Bot.Builder.Internals.Fibers.FactoryStore1.Microsoft.Bot.Builder.Internals.Fibers.IStore<T>.Save(T
>   item)\r\n   at
>   Microsoft.Bot.Builder.Dialogs.Internals.DialogTask.<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d__211.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at Microsoft.Bot.Builder.Dialogs.Internals.ReactiveDialogTask.d__51.MoveNext()\r\n---
>   End of stack trace from previous location where exception was thrown
>   ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
>   task)\r\n   at
>   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
>   task)\r\n   at
>   Microsoft.Bot.Builder.Dialogs.Internals.LocalizedDialogTask.<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d__21.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at Microsoft.Bot.Builder.Dialogs.Internals.ScoringDialogTask1.<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d__61.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.T askAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at Microsoft.Bot.Builder.Dialogs.Internals.PersistentDialogTask.d__61.MoveNext()\r\n---
>   End of stack trace from previous location where exception was thrown
>   ---\r\n   at Microsoft.Bot.Builder.Dialogs.Internals.PersistentDialogTask.<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d__61.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at Microsoft.Bot.Builder.Dialogs.Conversation.d__4.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Ta sk task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at Microsoft.Bot.Builder.Dialogs.Conversation.d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n at MessengerBot.MessagesController.d__1.MoveNext() in C:\myapp\BotApplication\Controllers\MessagesController.cs:line 60"
>

**Comment by AnandChitale** [comment]
This happened to me as well. It happens if your RootLuisDialog has a field or property which is not serializable. Try to ignore it for serialization.

**Comment by lonche** [comment]
Hmmm how to ignore it for serialization ? Can you post your part of code ?

**Comment by lonche** [comment]
Thank you for your reply. I realize that i cannot make another instance of Activity class in LuisDialog.
Fixed :)

**Comment by initions-wiebe** [comment]
I'm not very sure about it, but you're using a class that is not marked as `[Serializable]`. You have to make sure, that `SimpleFacebookAuthDialog` is marked as `[Serializable]`. 
It should look something like this:
`[Serializable]`
`public class SimpleFacebookAuthDialog`

**Comment by willportnoy** [comment]
If you're storing the Activity property as a member field in your dialog class, you might consider marking it as [NonSerialized] as well.

**Comment by lonche** [comment]
Yes. I am using as serializable class. 

```
 [Serializable]
    public class SimpleFacebookAuthDialog : IDialog<string>
    {
```

I have another problem. I am trying to call SimpleFacebookAuthDialog on proper LuisIntent.
This way : 


    ```
    [LuisIntent("test")]
        public async Task test(IDialogContext context, IAwaitable<IMessageActivity> argument, LuisResult result)
        {
            await Conversation.SendAsync(context.Activity, () => SimpleFacebookAuthDialog.dialog);
        }

```

But it throws an error.

> can't convert Microsoft.Bot.Connector.IActivity' to 'Microsoft.Bot.Connector.IMessageActivity

I tried also with  `await Conversation.SendAsync(context.MakeMessage(), () => SimpleFacebookAuthDialog.dialog);`

But this way, it throws an error :  

> The data is changed


And the stack trace : 

> at Microsoft.Bot.Connector.ErrorHandling.d__21.MoveNext()
>   --- End of stack trace from previous location where exception was thrown ---    at
>   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
>   task)    at
>   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
>   task)    at
>   Microsoft.Bot.Connector.BotStateExtensions.<SetConversationDataAsync>d__9.MoveNext()
>   --- End of stack trace from previous location where exception was thrown ---    at
>   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
>   task)    at
>   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
>   task)    at
>   Microsoft.Bot.Builder.Dialogs.Internals.ConnectorStore.<Microsoft-Bot-Builder-Dialogs-Internals-IBotDataStore<Microsoft-Bot-Connector-BotData>-SaveAsync>d__3.MoveNext()
>   --- End of stack trace from previous location where exception was thrown ---    at
>   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
>   task)    at
>   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
>   task)    at
>   Microsoft.Bot.Builder.Dialogs.Internals.CachingBotDataStore.<Save>d__10.MoveNext()
>   --- End of stack trace from previous location where exception was thrown ---    at
>   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
>   task)    at
>   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
>   task)    at
>   Microsoft.Bot.Builder.Dialogs.Internals.CachingBotDataStore.<Microsoft-Bot-Builder-Dialogs-Internals-IBotDataStore<Microsoft-Bot-Connector-BotData>-FlushAsync>d__5.MoveNext()
>   --- End of stack trace from previous location where exception was thrown ---    at
>   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
>   task)    at
>   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
>   task)    at
>   Microsoft.Bot.Builder.Dialogs.Internals.BotDataBase1.d__9.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Bot.Builder.Dialogs.Internals.DialogTaskManagerBotDataLoader.d__10.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Bot.Builder.Dialogs.Internals.PersistentDialogTask.d__31.MoveNext()
>   --- End of stack trace from previous location where exception was thrown ---    at
>   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
>   task)    at
>   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
>   task)    at
>   Microsoft.Bot.Builder.Dialogs.Internals.SerializingDialogTask.<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d__41.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Bot.Builder.Dialogs.Internals.ExceptionTranslationDialogTask.d__21.MoveNext()
>   --- End of stack trace from previous location where exception was thrown ---    at
>   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
>   task)    at
>   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
>   task)    at
>   Microsoft.Bot.Builder.Dialogs.Internals.LocalizedDialogTask.<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d__21.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Bot.Builder.Dialogs.Internals.PostUnhandledExceptionToUserTask.d__51.MoveNext()
>   --- End of stack trace from previous location where exception was thrown ---    at
>   Microsoft.Bot.Builder.Dialogs.Internals.PostUnhandledExceptionToUserTask.<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d__51.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Bot.Builder.Dialogs.Internals.LogPostToBot.d__3`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Bot.Builder.Dialogs.Conversation.d__4.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Bot.Builder.Dialogs.Conversation.d__2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
> at MessengerBot.MessagesController.d__0.MoveNext() in C:\app\Controllers\MessagesController.cs:line 37


Any idea ?

**Comment by msft-shahins** [comment]
as @willportnoy mentioned you are keeping activity as a member field in your dialog and activity is not serializable. Either you should mark it with [NonSerialized] attribute or keep a serializable object that includes the fields from activity that you want to serialize in your dialog.
