### ISSUE TITLE
Luis Entity - Missing Resolution Property

### ISSUE THREAD

**Issue by warrenbuckley** [Microsoft/BotBuilder#21]
After speaking with @dandriscoll via Twitter this has been agreed it's a bug. See discussion on Twitter for some context - https://twitter.com/thedandriscoll/status/715655705605189632

I am using one of the built in entities in Luis such as DateTime and when the ChatBot calls my method when it matches my Intention attribute, I was expecting the entity for the built in DateTime would be machine readable in the Entity property on the `EntityRecommendation` class or much better preffered to match better with the JSON API returned from Luis to include the `Resolution`

Here is a sample payload of JSON I receive from my Luis app
```JSON
{
  "query": "What time is it for paul at 2 in the afternoon?",
  "intents": [
    {
      "intent": "TimeForUser",
      "score": 0.602315068,
      "actions": [
        {
          "triggered": true,
          "name": "TimeForUser",
          "parameters": [
            {
              "name": "User",
              "required": true,
              "value": [
                {
                  "entity": "paul",
                  "type": "User",
                  "score": 0.9330815
                }
              ]
            },
            {
              "name": "Time",
              "required": true,
              "value": [
                {
                  "entity": "2 in the afternoon",
                  "type": "builtin.datetime.time",
                  "resolution": {
                    "time": "T14"
                  }
                }
              ]
            }
          ]
        }
      ]
    },
```

**Comment by willportnoy** [comment]
We're working to regenerate the LUIS model classes based on the full LUIS service response.

**Comment by warrenbuckley** [comment]
Thanks for the update @willportnoy

**Comment by msft-shahins** [comment]
The new release should have the missing fields.

**Comment by warrenbuckley** [comment]
@msft-shahins has this been pushed out to Nuget so I can just do a simple update package via Nuget?
