### ISSUE TITLE
is context.Wait important?

### ISSUE THREAD

**Issue by ahmettaha** [Microsoft/BotBuilder#210]
Hello,

Do we have to type context.Wait after every response? What would happen, if I dont finish with that, and just post a reply?

**Comment by willportnoy** [comment]
context.Wait is how you tell the dialog framework how you want to handle the external event (i.e. message) sent to the bot.

If you don't call it, then the bot wouldn't be able to respond to further messages because the dialog framework would not know which code to call next.

**Comment by ahmettaha** [comment]
oh ok. so it is an alternative to chaining?



.

**Comment by willportnoy** [comment]
Chaining does allow you to skip the manual calls to context.Wait, since we know the types for which we wait in the chain.

I don't think there is a default behavior when context.Wait isn't called - the next message post should fail, and the dialog state will be likely be reset.

**Comment by Stevenic** [comment]
Please re-open if this is still an issue for you.

**Comment by zmqcherish** [comment]
In the demo, Echo Bot:
EchoDialog.cs:
`public async Task MessageReceivedAsync(IDialogContext context, IAwaitable<IMessageActivity> argument)
        {
            var message = await argument;
            await context.PostAsync("You said: " + message.Text);
            //context.Wait(MessageReceivedAsync);
        }`

I still don not know why is the 'context.Wait' is used for. If I comment the last line code 'context.Wait(MessageReceivedAsync);', the code run result is the same as the uncomment result.

(In the MessagesController, the main code is bellow)
`public async Task<HttpResponseMessage> Post([FromBody]Activity activity)
        {
            if (activity.Type == ActivityTypes.Message)
            {
                await Conversation.SendAsync(activity, () => new EchoDialog());
            }
            else
            {
                await HandleSystemMessage(activity);
            }
            var response = Request.CreateResponse(HttpStatusCode.OK);
            return response;
        }`

**Comment by willportnoy** [comment]
@zmqcherish you might consider reading about context.wait in the documentation: https://docs.botframework.com/en-us/csharp/builder/sdkreference/dialogs.html

**Comment by zmqcherish** [comment]
@willportnoy well, I have read the documentation yet. I still have question about it, and I ask the question in StackOverflow [http://stackoverflow.com/questions/43625879/what-is-context-wait-use-for-in-botframework](url). The Xeno-D conclude that：“By leaving the line out in the MessageReceivedAsync method the framework will keep reusing the same method to respond to messages.“ 

But I doubt it, can you confirm it，thanks.

**Comment by willportnoy** [comment]
@zmqcherish yes, there was an improvement to reuse the previous wait when a new one was not specified: https://github.com/Microsoft/BotBuilder/commit/9732296235a274bcc429f7e647b46fc9d1f3d989

**Comment by zmqcherish** [comment]
@willportnoy thank you  very much
