### ISSUE TITLE
Node.js: Sign-in Card link not working in Teams

### ISSUE THREAD

**Issue by RichMoeMSFT** [Microsoft/BotBuilder#2104]
In Node.js bots, running in Teams, the Sign-in button / link is not working.  Works on other channels.

Using sample: node/cards-RichCards

**Comment by drudv** [comment]
Hey Richard,

do you have any update regarding this issue? I can confirm that `signin` button still doesn't work in Teams, however works in test chat on dev.botrframework.com.

Thanks.

**Comment by chris31389** [comment]
Has there been any news on this?  It doesn't work for C# bot either.

**Comment by RichMoeMSFT** [comment]
We filed a bug on this.  The button action "signin" is not supported in teams.  If you change the button type to "postUrl" (which in effect is what signin does anyway), you can get the Signin card to work.

**Comment by nwhitmont** [comment]
thanks for the update @RichMoeMSFT

**Comment by juhamust** [comment]
I can't seem to find `postUrl` in reference documentation (https://docs.botframework.com/en-us/node/builder/chat-reference/modules/_botbuilder_d_.html) or code (https://github.com/Microsoft/BotBuilder/search?utf8=%E2%9C%93&q=postUrl&type=)

Am I missing something or are you referring to openUrl?

**Comment by RichMoeMSFT** [comment]
My bad, yes `openUrl`.  Fixed above as well.

**Comment by fkatada** [comment]
@RichMoeMSFT, I tested openUrl in MS Teams Desktop and it works fine.
![ms-teams desktop](https://cloud.githubusercontent.com/assets/13221718/26441905/fa8db5e2-4164-11e7-9825-47a93bac812c.PNG)

But i have checked in MS Teams Mobile app(ios) i just sends a "sent a card" response, and in android device is a blank response.
![microsoftteams-image](https://cloud.githubusercontent.com/assets/13221718/26442040/761111a0-4165-11e7-8f43-b4d7dc4c3e17.png)

**Comment by JasonSowers** [comment]
for anyone that comes across this post, I have a simple implementation for both Node and C# in #4768

**Comment by tmhao2005** [comment]
I still get this error with personal chat. Apart from testing in team, is there a way to either fix or hack around for now?

**Comment by tmhao2005** [comment]
It seems my domain was yet in the valid domains
