### ISSUE TITLE
Delegate bot conversation to human

### ISSUE THREAD

**Issue by piffarettig** [Microsoft/BotBuilder#2105]
I ve seen this question asked multiple times but answers were never enough or included code snippets so I am open a new issue here. This is the use case I am trying to resolve:

1) Human asks a question to the  bot.
2) As bot doesn't know the answer, bot passes the question to an expert.
3) Experts gets notified that a user needs help, so he takes control of the bot.
4) A conversation starts between both humans, but via the bot (the user just sees incoming messsages by the bot).
5) Whenever they finish their conversation, bot goes back to normal state.

I ve seen many posts about this, for instance:

[Here](https://github.com/Microsoft/BotBuilder/issues/1975
)
[Here](https://github.com/Microsoft/BotBuilder/issues/1806)
[Here](https://github.com/Microsoft/BotBuilder/issues/1975
)

And I think [this is the one that has the best answer](https://github.com/Microsoft/BotBuilder/issues/2011), although, I still have some doubts about how to tackle this.

1) Is it necessary to use another GUI for the expert human? How can this be done via the same bot channel (for example Skype)? 
2) Any examples of how to use DirectLine? 

What is the best way to implement this? 

Thanks!

**Comment by willportnoy** [comment]
@LarsLiden do you have any thoughts?

**Comment by ancashoria** [comment]
I'm really interested in the solution too. Any ideas?

**Comment by justinvan0603** [comment]
I've found a solution in C# here. But the Agent UI included in this document works by a interval request to the Bot Service, it's very painful if the Bot will be in production and you have lots of customers interact with your bot
[Intermediator Bot](https://github.com/tompaana/intermediator-bot-sample)

**Comment by cocoytech** [comment]
Any sample documentation?
