### ISSUE TITLE
Node.js bot deployed to azure isn't working

### ISSUE THREAD

**Issue by irwinwilliams** [Microsoft/BotBuilder#2106]
I've deployed a bot written in node to an azure web app. 
In the console, I can see the ChatConnector getting the message, but then this error comes up:

Error: connect EACCES 127.0.0.1:50014
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)

I took the facebook sample (https://github.com/Microsoft/BotBuilder/blob/master/Node/examples/demo-facebook/app.js) and extended it.

**Comment by irwinwilliams** [comment]
Hey, it looks like this happen when you try to use the bot framework emulator to test a non-localhost bot.
Maybe the messaging around the emulator could be changed to reflect that as a limitation, if it is one.

**Comment by eanders-MS** [comment]
Hi @irwinwilliams, Emulator documentation includes a section on this topic: [Connect to an Azure Bot Service](https://github.com/Microsoft/BotFramework-Emulator/wiki/Getting-Started#connect-to-an-azure-bot-service).

**Comment by irwinwilliams** [comment]
Got it. Thanks, @eanders-MS. Understood.
