### ISSUE TITLE
Skype calling bot CollectDigits no longer works and Recognize seldom works

### ISSUE THREAD

**Issue by camer314** [Microsoft/BotBuilder#2107]
Trying to collect digits from a Skype calling bot forever returns "InternalServerError". It used to work a few weeks ago and now never works.

Also the recognize speech often fails with "InitialSilenceTimeout" or "InternalServerError" for no apparent reason.

**Comment by KrishnanA** [comment]
Can you share your bot Id please?

**Comment by camer314** [comment]
Here you go: c0b9c83d-a571-4e4c-9301-9fbc9102d751

**Comment by KrishnanA** [comment]
Thanks. I placed a call and it worked well. Can you give me the scenario that does not work and I can look.

**Comment by msft-shahins** [comment]
@camer314 do you still have this issue?

**Comment by KrishnanA** [comment]
I will go ahead and close the issue for now. Please re-activate if you are hitting the issue and let us know the exact scenario that you are trying out.
