### ISSUE TITLE
[Question] How to send a chat message during a Skype calling bot session

### ISSUE THREAD

**Issue by camer314** [Microsoft/BotBuilder#2108]
I have a calling bot and i want to send a chat message to the Skype user as part of the chat, for example a confirmation of order message. However I get the following error:

Authorization for Microsoft App ID XXX failed with status code Forbidden

If the Skype user starts a chat conversation with my bot prior to calling it then sending a chat message to them works fine.

Is there any way to send a chat message to a Skype user without them first chatting to my bot?

This is the code in my calling bot to send the message

`                    var caller = incomingCallEvent.IncomingCall.Participants.First(p => p.Originator);
                    var callee = incomingCallEvent.IncomingCall.Participants.First(p => !p.Originator);

                    var userAccount = new ChannelAccount(caller.Identity, caller.DisplayName);
                    var botAccount = new ChannelAccount(callee.Identity, callee.DisplayName);
                    var connector = new ConnectorClient(new Uri("https://skype.botframework.com"));
                    var conversationId = await connector.Conversations.CreateDirectConversationAsync(botAccount, userAccount);
                    IMessageActivity message = Activity.CreateMessageActivity();
                    message.From = botAccount;
                    message.Recipient = userAccount;
                    message.Conversation = new ConversationAccount(id: conversationId.Id);
                    message.Text = "Hello this is your bot here";
                    message.Locale = "en-us";
                    await connector.Conversations.SendToConversationAsync((Activity)message);
`

**Comment by dandriscoll** [comment]
Hi @camer314, skype.botframework.com is not guaranteed to be the Skype hostname. The URL for the Skype is passed in the "ServiceUrl" field of the ContactRelationUpdate activity when the user adds your bot as a contact.

See https://github.com/Microsoft/BotBuilder/issues/2005 for more detail.

**Comment by camer314** [comment]
Ok thats fair enough, but skype.botframework.com is what i retrieved from the ServiceUrl that comes in via a chat session for the same user and that URL works fine as mentioned if the user has already chatted to my bot before calling it. The issue only arises if i restart my bot web app and the same user calls the bot without first starting a chat conversation.

**Comment by camer314** [comment]
I am keeping this one open because i havent got a response to my above question. If i restart my bot AND all the fields are as is then i am unable to send a message to the user, only if the bot stays running can i send a message from a call.

Also, in the event that you miss ContactRelationUpdate, is there any way to get a list of contacts and process that list in batch?

**Comment by JasonSowers** [comment]
@camer314 Would you still like to keep this open or have you resolved the question/Issue?

**Comment by camer314** [comment]
This has been resolved by using MicrosoftAppCredentials.TrustServiceUrl to trust all service URLs that are loaded from resumption cookies
