### ISSUE TITLE
"message": "An error has occurred." with directline

### ISSUE THREAD

**Issue by bluekite2000** [Microsoft/BotBuilder#211]
I tried
curl -X POST -H "Authorization: BotConnector MYTOKEN" --header 'Content-Type: application/json' -d 'hi' 'https://directline.botframework.com/api/conversations/MYCONVERSATIONID/messages'
and got an error 
"message": "An error has occurred."

**Comment by msft-shahins** [comment]
Try a valid json based on the connector message schema for body of your post. For example, something like below: 

```json
{
"Text": "this is a test"
}
```

and the server should return 204 upon success.

**Comment by bluekite2000** [comment]
I tried 
curl -X POST -H "Authorization: BotConnector token" --header 'Content-Type: application/json; charset=UTF-8' -d '{"Text”:”hi”}’ 'https://directline.botframework.com/api/conversations/conversationId/messages'

and got nothing back. no 204. 
Btw should I return the 1st answer (which is a welcome message in this case for my bot)

**Comment by bluekite2000** [comment]
@msft-shahins it doesnt return 204 but I think it is successful because when I do a GET i get the messages back (which is an enumeration Please select a choice (1. Check In)) However I when I do a post with -d '{"Text":"1"} the bot doesnt recognize that I pick option 1 and move on to the next question. Any idea?
