### ISSUE TITLE
Facebook bot not receiving events

### ISSUE THREAD

**Issue by haligasd** [Microsoft/BotBuilder#2112]
bot handle beachgenius.  We have the steps over and over again and cannot get our bot to work on facebook.  Works like a champ on skype.

we are getting these as issues 

Cannot message users who are not admins, developers or testers of the app until pages_messaging permission is reviewed and the app is live - we are developing now so not sure why we see these

**Comment by haligasd** [comment]
Cannot message users who are not admins, developers or testers of the app until pages_messaging permission is reviewed and the app is live

**Comment by haligasd** [comment]
reconfigured it all and it is now working

**Comment by SarnenduDe** [comment]
haligasd, 
can you please explain the reconfigured steps. I am also facing same issue. 
please refer below link.
https://github.com/Microsoft/BotBuilder/issues/2510

**Comment by haligasd** [comment]
i had the wrong page id / app id combo.  make sure configuration is setup.  also check the errors in the bot dashboard.  make sure your account you are testing with is a dev / admin in facebook
