### ISSUE TITLE
Bot c#: How to restart the conversation with the last input from user

### ISSUE THREAD

**Issue by msBot1111** [Microsoft/BotBuilder#2113]
In my Bot I use prompt.text and in the ResumeAfter method I want to check if user said yes, no or something else, and if it's not yes or no to call again my Root dialog(which is Luis class) with the input from the user. Here is the code:
 PromptDialog.Text(context, ResumeAfterAsync, $"Was this helpful?");   
 private async Task ResumeAfterAsync(IDialogContext context, IAwaitable<string> result)
 {
        string msg = await result;
        if(msg=="yes")
        {
            await context.PostAsync($"Ok, thanks.");
        }
        else if(msg=="no")
        {
            await context.PostAsync($"another");
        }
       else
        {
             context.Wait(MessageReceived);  //-Here I need to send msg and to start again the conversation
}

**Comment by willportnoy** [comment]
You might consider using IDialogStack.Forward to forward the message on to the LUIS dialog as a new child (instead of the existing root):
https://docs.botframework.com/en-us/technical-faq/#what-is-idialogstack-forward-in-the-c-builder-sdk

But what are you going to do if the user said "yes" or "no"?  You have to go somewhere next:
https://docs.botframework.com/en-us/technical-faq/#ensure-all-dialog-methods-end-with-a-plan-to-handle-the-next-message

and would that place be the initial root LUIS dialog?

**Comment by msBot1111** [comment]
If user said "yes" or "no", I'm calling different methods, It's working well. 
I've changed the else statment with this:
  context.Forward(new MainDialog(),ResumeCopleted,msg,System.Threading.CancellationToken.None);
MainDialog is my LuisDIalog
And now in ResumeCopleted what should I do??
I've tried 
 private Task ResumeCopleted(IDialogContext context, IAwaitable<object> result)
        {
           throw new NotImplementedException();
        }
but that's not the right implementation

**Comment by willportnoy** [comment]
The IAwaitable<T> in ResumeCopleted carries the result (of type T) from the MainDialog, so that you can post a message to the user or take some other action before resuming the wait for the next user message.

**Comment by msBot1111** [comment]
![p](https://cloud.githubusercontent.com/assets/24811574/22418480/864367c6-e6d9-11e6-8988-74736bf049b1.png)
And It doesn't start the new search with cancer.I need to take that input and start the conversation with that. If I type again cancer then the result will be returned, but that's not my point.

**Comment by msBot1111** [comment]
Ok, thanks It's working now

**Comment by ghadshivedika** [comment]
Hi msBot1111
Could you please share code snippet how did u pass the user input back to Luis dialog.
Even I want map user prompt to one of the entity in the luis and set it to a variable.

**Comment by alokraj68** [comment]
how to achieve the same in v4
