### ISSUE TITLE
Create a log of triggered events

### ISSUE THREAD

**Issue by rakeshkeerthi** [Microsoft/BotBuilder#2114]
Hi, 

I know that this might not be an issue, but also not sure if this is available in azure.  

I've created a custom chat using html n Javascript. It works as follows

User enters a question - hello 
There is a rest call to Directline api 
 It internally calls the Qna maker bot 
The response is displayed back. 

My query is lets say there is an user A, he is using this service. Everything is working fine with the code. The request is properly triggered and the response is exactly received as expected.

When user asks some question. I want this to be stored in azure in a text format like

userName, question, confidenceScore, count 

The response I get is in this way

{"answer":"confidenseScore"} 

And my direct line call contains request data like this

{ type:"message", text:"myQuestion", from: { id:"userId" } } 

I've got all this information but I dunno how am I supposed to create a log in the above format. Please let me know how can I do this. A documentation or an example would be helpful.

I'm asking this, as this is some sort of chat bot that lists faqs in a side. And I want this to be on user basis, I mean user A logs in, faqs are to be generated based on what this user asked earlier.

Thanks

**Comment by nwhitmont** [comment]
@rakeshkeerthi If you're deploying your app to Azure you can enable the Application Insights that will help you track logs from your bot.  You can also enable a middleware to handle this depending on if you are using C# or Node SDK for Bot Framework
