### ISSUE TITLE
Facebook Messenger Bot: No replies to others

### ISSUE THREAD

**Issue by Sarafian** [Microsoft/BotBuilder#2115]
I've successfully created a bot and integrated with Skype and Facebook Messenger.
The Skype interface works for everyone but the Facebook one replies only to my Facebook account. 
The bot is not published and in the channels list, Facebook and Skype is enabled but not published.

I've searched online but I can't find much information, so I'm creating this issue as means to get some help and produce help for similar issues.

**Comment by hardsky** [comment]
Hi!
Do you see some errors in dev.botframework.com ?
I had similar issue. I tried to test unpublished facebook bot from account, that not linked to project as developer or QA.
Here is error from facebook in dev.botframework.com

> Cannot message users who are not admins, developers or testers of the app until pages_messaging permission is reviewed and the app is live. 


From your description, I guess you have same issue.
Seems like it's just related to facebook development specific.

**Comment by Sarafian** [comment]
@hardsky I just noticed the errors. If you hadn't mentioned it I would have probably never seen it.
I do have the same error. Any suggestions for the fix?
Should this be added to the guide? I suggest this because the guide for skype works well for all but the guide for facebook doesn't and it's a pity.

**Comment by Sarafian** [comment]
For future reference to anyone having this issue. There are two possible actions:
1. **Easy**. From developers.facebook.com add the specific people you want them to engage your bot as **testers**.
1. **Complex**. From developers.facebook.com add the **pages_messaging** to submission. This is more complex because 
  - it requires a 1024x1024 icon (I resized the [default](https://bot-framework.azureedge.net/bot-icons-v1/bot-framework-default-1.png) from the bot-framework.
  - you must add a **Privacy Policy URL**. I used the iubenda.com.
  - you must add to submission the **pages_messaging**. You need the above before you can proceed with this step.

If you are looking for a couple of people to play with your bot then option 1 is enough. If you are looking to a more dynamic experience where you share your bot link and people have then option 1 is not enough and you need to proceed with option 2.

Is it possible to add a more refined information in the dev.botframework.com?

**Comment by VineetMore** [comment]
Hi,

I need the Option 2 but whenever I am submitting the app for getting the permission for pages_messaging they are rejecting it as the Bots are not replying to them. The bots will not reply to any user outside of Developers and testers but I am unable to explain the same to the Facebook review team. Can you please guide me on how can I take it forward?
