### ISSUE TITLE
Skype bot error [413] Request Entity Too Large

### ISSUE THREAD

**Issue by FilipeDominguesGit** [Microsoft/BotBuilder#2117]
Hi all.  I'm getting error [413] on a simple skype bot. 

Error: ``` Error: Request to https://smba.trafficmanager.net/apis/v3/conversations/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/activities' failed: [413] Request Entity Too Large ```

Sample code: 

```javascript
const express = require('express');
const builder = require('botbuilder');
const app = express();

const port = process.env.PORT || 3000;

app.listen(port,()=>{
    console.log(`Server listening on port ${port}.`);
});

const connector = new builder.ChatConnector({
    appId: process.env.MICROSOFT_APP_ID,
    appPassword: process.env.MICROSOFT_APP_PASSWORD
});

const bot = new builder.UniversalBot(connector);

app.post('/api/messages', connector.listen());

bot.dialog('/', function (session) {

    var msg = new builder.Message(session)
            .attachments([{
                contentType: 'image/gif',
                contentUrl: 'http://i.imgur.com/MAQm02i.gif'
            }]); 

    session.send(msg);

});
```
It works on webclient and on the emulator but crashes on skype. Any idea whats happening ?

**Comment by weedroid** [comment]
Could it be that the gif you're trying to attach is too large for Skype? It's over 50MB in size. Have you tried using a smaller gif file?

**Comment by msft-shahins** [comment]
Skype limits size of the attachment to 20MB and as a result you are hitting that limit and get http status code 413. Different channels have different size limits for attachments. Publishing a list covering these limits is in our backlog.

**Comment by ripone07** [comment]
@msft-shahins I know it's been over a year and a half since this thread was closed, but I would really like to know if the list you refer to, got finally published, since I am not able to find any associated ticket.
I would appreciate your help.
