### ISSUE TITLE
Facebook Messenger splits and truncates messages

### ISSUE THREAD

**Issue by matthew5025** [Microsoft/BotBuilder#212]
Facebook messenger seems to be splitting and truncating messages.

Telegram: 
![image](https://cloud.githubusercontent.com/assets/1402223/14973675/4fe75fbc-111d-11e6-88c9-ac76988674eb.png)

Facebook:
![image](https://cloud.githubusercontent.com/assets/1402223/14973699/b4c9b614-111d-11e6-9dfe-bb218dd8f61f.png)

**Comment by kevinguebert** [comment]
[This github repo](https://github.com/ClaudeBot/hubot-messenger-bot#320-characters-limit) is a npm module that references a character limit to Facebook Messenger Send API. 

> 320 characters limit
> At the time of writing, the Send API only allows up to 320 characters. We strongly recommend using a plugin like hubot-longtext to gracefully handle long messages.

I checked out on the FB Developer site and it doesn't reference a character limit but I have run into one. After doing a basic type out of that first message it seems like it is hovering right around that limit of 320. 

Unsure why it is splitting messages without seeing your requests, but I would recommend looking into Facebook's Character limit.

**Comment by tomlm** [comment]
That’s right, I observed a 320 char limit, so we split into multiple posts to display longer text.

**Comment by matthew5025** [comment]
The splitting is understandable considering the circumstances, but the truncation of the messages seems wrong. 
Also, perhaps you might consider splitting along paragraph breaks, headers ets rather then a straight 320 char split.

**Comment by tomlm** [comment]
This should be fixed now.

**Comment by matthew5025** [comment]
Is there a change that I have to deploy? I'm still getting the problem where the message is truncated.

**Comment by tomlm** [comment]
From my experimentation in won’t truncate if the message is split at 300 character boundary.

We still have to split into multiple messages though

**Comment by matthew5025** [comment]
Here's a sample string that I've notice would cause problems.

`L & R: MyTransport.SG Is Smarter, Faster, More Personal. The New Journey Planner Means You'll Never Miss A Stop Again! Bus Stop Countdown And Notification Lets You Know When To Alight. B: Never Miss A Stop Again!) (White)\n\n\n---\n**SMB5016H**\n\nService: 188\n\nOperator: SMRT BUSES LTD.\n\nDepot: Kranji Depot (KJDEP)\n\nModel: Alexander Dennis Enviro500\n\nAdvert: No Advert\n\n\n---\n`

![image](https://cloud.githubusercontent.com/assets/1402223/15168053/6e1df100-1760-11e6-8791-695312d6eff6.png)

Also, I seem to be having a problem very similar to #108, but with FB Messenger. The test string above will also show this issue.

**Comment by swapnilg915** [comment]
Hello everybody, I am getting the same problem. To solve this I am dividing the message into the chunks of less than 320 charcters. But here I am getting another problem, the chunks that I am sending are getting shuffled. I tried to solve this issue by introducing delay function but still unable to solve. Please help if there is a solution for this. My main issue is sending the long messages with facebook messenger.
