### ISSUE TITLE
[Proactive Notifications] Does MSBot framework support sending automated notification after a certain time?

### ISSUE THREAD

**Issue by zeeshanhaider-devbatch** [Microsoft/BotBuilder#2120]
I want to write a BOT that (once user is friend with BOT) can send automated notifications with some link in it to the user. Is this possible?

**Comment by BenjaBobs** [comment]
Yes, I suggest reading the following resources:
[Alarm Bot Sample](https://github.com/Microsoft/BotBuilder/tree/master/CSharp/Samples/AlarmBot)
[Create New Conversation Bot Sample](https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/core-CreateNewConversation)

**Comment by eanders-MS** [comment]
Hi @zeeshanhaider-devbatch plase also have a look at Proactive Bots:
https://docs.botframework.com/en-us/azure-bot-service/templates/proactive/

**Comment by alexsorokoletov** [comment]
@zeeshanhaider-devbatch suggest you to look at Alarm bot sample mentioned above. We're using this approach and it works just fine!

**Comment by zeeshanhaider-devbatch** [comment]
@eanders-MS @alexsorokoletov Can I do some sort of notifications service with help of a REST api, If there is new item added (in certain API/DB) I notify user who has added my bot as a contact?

**Comment by zeeshanhaider-devbatch** [comment]
Thanks anyways, Alarmbot was very helpful.

**Comment by alexsorokoletov** [comment]
@zeeshanhaider-devbatch definitely you can do.
Your bot is basically a web service running on your server.
So your other API could call your bot's service and make it send a message to a certain user.

In fact, this is what we did when we created a Viber connector. It listens for events from Viber using webhook and then sends messages to the user using BotFramework
