### ISSUE TITLE
Updating the Convesation Container

### ISSUE THREAD

**Issue by srozga** [Microsoft/BotBuilder#2121]
The currently direction in C# samples like [this](https://github.com/Microsoft/BotBuilder-Azure/blob/master/CSharp/Samples/AzureTable/Global.asax.cs) is to use the ContainerBuilder.Update method to update the existing Conversation.Container. AutoFac is deprecating the use of Update. I noticed Conversation has a static constructor that builds the Container but doesn't allow for any other modules to be registered. What is the direction on this one?

**Comment by willportnoy** [comment]
relevant issue: https://github.com/Microsoft/BotBuilder/issues/1966

**Comment by willportnoy** [comment]
Here is one option, where you customize the container and fold any other updates into one place:

~~~
   [BotAuthentication]
    public class MessagesController : ApiController
    {
        public static readonly IContainer Container;

        static MessagesController()
        {
            var builder = new ContainerBuilder();
            builder.RegisterModule(new DialogModule());
            // provide a root dialog
            builder.RegisterType<EchoDialog>().As<IDialog<object>>().InstancePerDependency();

            // do other updates to the container

            Container = builder.Build();
        }

        public virtual async Task<HttpResponseMessage> Post([FromBody] Activity activity, CancellationToken token)
        {
            if (activity.Type == ActivityTypes.Message)
            {
                // start a per-request lifetime scope based on the per-bot lifetime scope
                using (var perRequest = DialogModule.BeginLifetimeScope(Container, activity))
                {
                    // resolve the top-level interface
                    var task = perRequest.Resolve<IPostToBot>();

                    // post the incoming activity to it
                    await task.PostAsync(activity, token);
                }
            }

            return new HttpResponseMessage(HttpStatusCode.Accepted);
        }
    }

~~~

**Comment by BenjaBobs** [comment]
It seems to me that having a static container and passing it around is the [service locator anti-pattern](http://blog.ploeh.dk/2010/02/03/ServiceLocatorisanAnti-Pattern/). Is there any chance of instead having the internal container exposed before it is built?

The way I see it, another alternative could be to create another IDependencyResolver which first tries to resolve using the BotBuilder internal container and a custom container. This seems like a bad idea to me though, as it could result in having registrations.

**Comment by willportnoy** [comment]
@BenjaBobs we don't depend on the container directly in our components, with the intent of avoiding the service locator pattern, preferring constructor injection.  In the "composition root", we resolve a single top-level interface and post the incoming activity to that IPostToBot implementation.

**Comment by willportnoy** [comment]
I'm going to this issue for now since we have an alternative suggestion and the issue is being tracked more as https://github.com/Microsoft/BotBuilder/issues/1966.
