### ISSUE TITLE
Chat control 

### ISSUE THREAD

**Issue by vovanb** [Microsoft/BotBuilder#2122]
Is exist a way to pass caller name (from) using web chat control? Today it always passing "You".

**Comment by eanders-MS** [comment]
If you're embedding the control in an IFRAME, you can pass userId and username as parameters on the url:

```
<iframe src='https://webchat.botframework.com/embed/YOUR_BOT_ID?s=YOUR_SECRET_HERE?username=USERNAME_HERE&userId=USERID_HERE'></iframe>
```
