### ISSUE TITLE
ChannelId parameter in StateAPI.json schema takes only specific values

### ISSUE THREAD

**Issue by alexsorokoletov** [Microsoft/BotBuilder#2123]
Spec says `channelId` is basically a string. However, passing there `viber` or `telegram2` or `custom` returns HTTP 400
```
{
  "error": {
    "code": "MissingProperty",
    "message": "You did not pass a valid channel or bot id"
  }
}
```

[Spec](https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Microsoft.Bot.Connector.Shared/Swagger/StateAPI.json#L21):

```
   "/v3/botstate/{channelId}/users/{userId}": {
      "get": {
        "tags": [ "BotState" ],
        "summary": "GetUserData",
        "description": "Get a bots data for the user across all conversations",
        "operationId": "BotState_GetUserData",
        "consumes": [],
        "produces": [ "application/json", "text/json", "application/xml", "text/xml" ],
        "parameters": [
          {
            "name": "channelId",
            "in": "path",
            "description": "channelId",
            "required": true,
            "type": "string"
          },
```

Please advise what are the supported options for `channelId` and how do I use State API for custom channel, say, Viber.

**Comment by dandriscoll** [comment]
Hi @alexsorokoletov, those channels are not supported by the Bot Framework. The best way to connect them is with Direct Line, in which case you should use the `directline` channel ID.

**Comment by alexsorokoletov** [comment]
I'm using email for now just to make sure my custom connector works. Let me try 'directline', thanks!

Alex

**Comment by alexsorokoletov** [comment]
Yep, `directline` works just fine

**Comment by dandriscoll** [comment]
Great! at-mention or open a new issue if you have further questions. Thanks

**Comment by alexsorokoletov** [comment]
Btw, I ended up using `kik` channel instead of `directline` only for one reason. Using `directline` removes all buttons so my custom connector cannot render keyboard for Viber. Kik is among channels that support keyboard (baked in the SDK :() and I'm not using it anyway so it's a great option.

Would be cool to have a baked-in channel with keyboards support like `custom-with-keyboard` and `custom-no-keyboard` instead of just `directline`.

Or... teach somehow SDK to pass keyboard data to the `directline` channel. 

@dandriscoll sorry to bug you again on that :)

**Comment by dandriscoll** [comment]
Direct Line 3.0 passes the entire payload through. Are you using Direct Line 1.1?

**Comment by alexsorokoletov** [comment]
I'm using latest SDK, 3.5.1. Not sure where can I specify Direct Line 3.0 or 1.1

**Comment by dandriscoll** [comment]
The Bot Builder SDK is for inside your bot. Direct Line is an API for your client to connect to your bot. Which client are you using?

Direct Line 3.0 (recommended): https://docs.botframework.com/en-us/restapi/directline3/#navtitle
Direct Line 1.1: https://docs.botframework.com/en-us/restapi/directline/#navtitle

**Comment by alexsorokoletov** [comment]
Hmm, I am not using any of these APIs.
What I have is a JS class inside my bot project which is basically an implementation of IChannelConnector interface and it is being used as a custom connector. Receives messages and sends them to the channel (viber in my case).

**Comment by dandriscoll** [comment]
Oh, I see, you've built your own protocol adapters.

That's certainly one way to use the Bot Builder SDK, but it doesn't work with the rest of the Bot Framework services. The fact that it works against the State API is a bit of a coincidence.

**Comment by alexsorokoletov** [comment]
@dandriscoll I was not able to stop it from going to State API. I know it is one of the unsupported scenarios. What I wanted to achieve is to have same logic (bot) defined for all channels that BotBuilder supports already and also use the same logic for my own channel. Turned out there are some challenges but as of now bot is working very nice and I really like the outcome.

There is no guide on how to write protocol adapter (is that what I have?) so I had to check few samples available from other people. Difference is that all existing "custom connectors" are used exclusively while I want to use it together with UniversalBot/ChatConnector.

I hope this makes some sense.

**Comment by alexsorokoletov** [comment]
@dandriscoll we have publish Viber connector and would like to get some help/feedback with it 
https://github.com/DreamTeamMobile/botbuilder-viber

In order to make it work we had to make connector pretend it's `kik` connector. Would be great to have it act as a `viber` connector, but changing `channelId` to `viber`.

Would be glad to get some thoughts on how to improve it.

**Comment by SychevIgor** [comment]
Looks like nobody care about viber, because simula request were closed 5 times during last 2 years.
https://github.com/Microsoft/BotBuilder/issues/2495
https://github.com/Microsoft/BotBuilder/issues/2429
https://github.com/Microsoft/BotBuilder/issues/2219
https://github.com/Microsoft/BotBuilder/issues/2123
https://github.com/Microsoft/BotBuilder/issues/1917

**Comment by SychevIgor** [comment]
Still very interesting connector, especially after telegram was blocked in Russia.

**Comment by ManjulaMalaiarasan** [comment]
Is there a way to set a custom value for the 'channelId' key??? I am customizing and hosting webchat, and would like to receive a different name instead of 'directline' to decide my response text and its format.
