### ISSUE TITLE
JSON Schema FormFlow

### ISSUE THREAD

**Issue by vovanb** [Microsoft/BotBuilder#2124]
Hi!
Is exist editor which helps creating Flow json - like in sample Microsoft.Bot.Sample.AnnotatedSandwichBot - AnnotatedSandwich.json
Thanks

**Comment by willportnoy** [comment]
I presume there are JSON Schema editors, but I don't know of editors specifically for the extra attributes in the FormFlow json.

**Comment by chrimc62** [comment]
@willportnoy answered this, so I'm closing it.
