### ISSUE TITLE
delete specific key from session 

### ISSUE THREAD

**Issue by aakashvit** [Microsoft/BotBuilder#2128]
I am using node JS
let's say I am storing name user name into name variable
 session.userData.name = results.response;
session.userData.mobileNM = results.response;

Now I want to delete only mobileNM from beg

**Comment by eanders-MS** [comment]
Have you tried clearing the value? This can be done a number of ways. `session.userData.mobileNM = undefined` should work.

**Comment by aakashvit** [comment]
Thanks!

**Comment by msft-shahins** [comment]
userData is a property bag (json object), you can delete the property by calling delete on the specific field that you want to delete. here is an example: https://github.com/Microsoft/BotBuilder/blob/2826c4757be5488ecc13926ecdf540254bf9715d/Node/examples/feature-beginDialogAction/app.js#L119
