### ISSUE TITLE
OnActionExecutingAsync dissappear after upgrade to Microsoft.Bot.Builder.3.5.0

### ISSUE THREAD

**Issue by vovanb** [Microsoft/BotBuilder#2129]
We were using below override
public override Task OnAuthorizationAsync(HttpActionContext actionContext, CancellationToken cancellationToken)
for assigning **MicrosoftAppId** according to incoming recipient.name 

  var content = actionContext.Request.Content.ReadAsStringAsync().Result;
  dynamic stuff = JObject.Parse(content);
  if (stuff.recipient == null || stuff.recipient.name == null) 

Now we get error that 
Error	CS0115	'OnAuthorizationAsync(HttpActionContext, CancellationToken)': no suitable method found to override	
Please help ASAP

BTW
Exist new override OnActionExecutingAsync, but how I can get recipient.name in this event?

**Comment by vovanb** [comment]
Guys Any feedback - the issue is showstopper after upgrade. We used your recommendation for assign MicrosoftAppId and MicrosoftAppPassword in runtime, and now you have broke the service:
https://github.com/Microsoft/BotBuilder/issues/867

**Comment by eanders-MS** [comment]
@msft-shahins can you take a look?

**Comment by vovanb** [comment]
Team any feedback or workaround will be appreciated.

**Comment by msft-shahins** [comment]
Since nuget v3.1, BotAuthentcation attribute is ActionFilterAttribute and not AuthorizationFilterAttribute. Here are the release notes: https://github.com/Microsoft/BotBuilder/releases/tag/NuGet3.1.0

Also you can now provide ICredentialProvider https://github.com/Microsoft/BotBuilder/blob/3a98a6b3d15962a57b5454bfb3f730d3588de3ef/CSharp/Library/Microsoft.Bot.Connector.Shared/CredentialProvider.cs#L13 to the BotAuthentication attribute to be able to authenticate using different MicrosoftAppId and MicrosoftAppPasswrods: https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Microsoft.Bot.Connector.NetFramework/BotAuthentication.cs#L57

**Comment by vovanb** [comment]
Can you provide example how to use ICredentialProvider and assign MicrosoftAppId and MicrosoftAppPasswrods programmatically ?

Sincerely,
Vladimir
(Sent from my mobile)

**Comment by lonche** [comment]
Did you solve this, @vovanb  ?

**Comment by vovanb** [comment]
Yes:
I used OnActionExecutingAsync instead of OnAuthorizationAsync. Inside :
var stuff = (Activity)actionContext.ActionArguments["activity"].Recipient.Name;
and called below:

            MicrosoftAppId = {config setting};
            RegisterBotDependencies(parameters);

        }

        public static void RegisterBotDependencies(string strBotId, string strAppId, string strAppPassword)
        {
            var builder = new ContainerBuilder();

              builder.Register(c => new MicrosoftAppCredentials(
                strAppId,
                strAppPassword))
                .SingleInstance();

            builder.Update(Conversation.Container);
        }

       

    }

**Comment by lonche** [comment]
Where did you insert this code ? In MessageController contstructor ? Or ?

**Comment by vovanb** [comment]
In attribute:
[AttributeUsage(AttributeTargets.Class | AttributeTargets.Method)]
	public class MSBotAuth : BotAuthentication

**Comment by lonche** [comment]
Sorry i didn't get that. Where do you call this code ? 
For authentication bot, in botframework documentation is mentioned to use BotAuthentication class before controller.  BotAuthentication has properties like appid, password, etc.
Can you better explain this ?

**Comment by lonche** [comment]
Bump.

**Comment by msft-shahins** [comment]
Here is an example using ICredentialProvider to provide MicrosoftAppId and MicrosoftAppPassword: https://github.com/Microsoft/BotBuilder/issues/2258#issuecomment-280506334
