### ISSUE TITLE
Custom Action In PromptDialog.Choice if user doesnt select a choice

### ISSUE THREAD

**Issue by alex182** [Microsoft/BotBuilder#2130]
Is there a way to handle a user sending a message instead of selecting a choice in a Choice dialog?

**Comment by willportnoy** [comment]
We usually recommend using scorable actions to allow dialogs to be interrupted - for example:

https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Tests/Microsoft.Bot.Builder.Tests/ScorableDialogTests.cs#L332

**Comment by bondz** [comment]
@willportnoy is there a ScorableDialog equivalent for NodeJS? An example maybe?

**Comment by willportnoy** [comment]
@bondz yes, you can use triggerAction and cancelAction and similar methods in Node.

**Comment by bondz** [comment]
@willportnoy thanks. Using the framework is surprisingly easy, especially with TypeScript and the docs really helped. Got a working medium size bot in two days and my first time using it. ☺

**Comment by willportnoy** [comment]
@bondz good to hear - I'm going to close this issue for now as I think both the C# and Node questions were answered - feel free to open a new top level issue for further discussion.
