### ISSUE TITLE
pass parameter in SendAsync

### ISSUE THREAD

**Issue by vovanb** [Microsoft/BotBuilder#2131]
Hi Team 
I want to pass additional parameter to MakeJsonRootDialog function

 string strPar = "SomeText";
 await Conversation.SendAsync(activity, ControllerHandler.MakeJsonRootDialog(**strPar**));

   public static IDialog<JObject> MakeJsonRootDialog(**string strParam**)
        {     
}

I got compile error :
Error	CS1503	Argument 2: cannot convert from 'Microsoft.Bot.Builder.Dialogs.IDialog<Newtonsoft.Json.Linq.JObject>' to 'System.Func<Microsoft.Bot.Builder.Dialogs.IDialog<object>>'	

Thanks

**Comment by willportnoy** [comment]
You can use a closure to capture that extra parameter.  You can't change the interface of that dialog root factory method because we wouldn't know how to pass those extra parameters to it anyway.

**Comment by vovanb** [comment]
Can you give example - is it mean that I need to put all MakeJsonRootDialog code inside of closure?

**Comment by BenjaBobs** [comment]
You can capture the closure in a lambda expression like this:
```csharp
string strPar = "SomeText";
await Conversation.SendAsync(activity, () => ControllerHandler.MakeJsonRootDialog(strPar));

public static IDialog MakeJsonRootDialog(string strParam)
{
}
```

**Comment by vovanb** [comment]
thanks a lot
