### ISSUE TITLE
[Node.js] Sending private message in Slack

### ISSUE THREAD

**Issue by sjlee235** [Microsoft/BotBuilder#2132]
I am trying to create a Slack bot where it listens to a Slack channel and when a request is given, it sends information to the user via private message. How can I specify a message in Node.js to be a private message?

Thank you!

**Comment by Stevenic** [comment]
You need to send a message to the user as a proactive message using `bot.send()`. You'll also need to delete the `conversationId` field from the messages `address` object before sending. Something like:

```
let bot = new builder.UniversalBot(connector, function (session) {
     // Create direct message
     let address = session.message.address;
     delete address.conversationId;
     let msg = new builder.Message().address(address).text('something private');

     // Send message proactively
     bot.send(msg);
});
```

**Comment by sjlee235** [comment]
Thank you! I modified the code a little and this works for me:

```
var directaddress = session.message.address;
delete directaddress.conversation;
var directmessage = new builder.Message().address(directaddress).text(replytext);
bot.send(directmessage);
```
