### ISSUE TITLE
How to check if request comes from SKYPE, WEBCHAT, DIRECTLINE, FACEBOOK etc... C#

### ISSUE THREAD

**Issue by sayyednazeer** [Microsoft/BotBuilder#2134]
How to check if request comes from SKYPE, WEBCHAT, DIRECTLINE, FACEBOOK etc... C#

**Comment by dandriscoll** [comment]
Hi @sayyednazeer, this data is available within the Activity object sent to your bot, inside the ChannelId property. How you get to that object/property depends on where you are inside the code.

Do you want to access this field within a Dialog?

**Comment by sayyednazeer** [comment]
I want to check inside both my MessagesControllers and Dialogs.

**Comment by msft-shahins** [comment]
You have access to the incoming activity in the MessageController and Dialogs. You can look at the activity.ChannelId to check which channel the request comes from. For example, [KeyboardCardMapper](https://github.com/Microsoft/BotBuilder/blob/3a98a6b3d15962a57b5454bfb3f730d3588de3ef/CSharp/Library/Microsoft.Bot.Builder/ConnectorEx/BotToUser.cs#L132) is using that information to map KeyboardCard to facebook quick replies.
