### ISSUE TITLE
next() intent handler not called automatically

### ISSUE THREAD

**Issue by bondz** [Microsoft/BotBuilder#2135]
Using the Chat Connector, and restify. The following

```js
intents.matches('Hello', [
  function botIntroduction(session, args, next) {
    // Send a greeting and show help.
    const card = new builder.HeroCard(session)
      .title('Sample Bot')
      .text('Sample Bot- Used for Examples.')
      .images([
        builder.CardImage.create(session, 'https://docs.botframework.com/images/demo_bot_image.png'),
      ]);
    const msg = new builder.Message(session).attachments([card]);
    session.send(msg);
    session.send(`Hi. I'm SampleBot. You can ask me anything`);
  },
  function checkProfile(session, args, next) {
    // See if we already know the user's name.
    if (!session.userData.name) {
      session.beginDialog('/askName');
    } else {
      // tslint:disable-next-line:no-unused-expression
      next && next();
    }
  },
  function greetUser(session) {
    session.send('Hi %s', session.userData.name);
  },
  function showHelp(session) {
    session.beginDialog('/help');
  },
]);
```

I'm using Luis and the handler gets called when the user says hi, but it gets stuck at the function `botIntroduction`, unless I add a `next()` at the end of the function. Similarly, all other intents behave the same way.

Using `NodeJS 6.9.1` and `botbuilder@3.5.4` with `typescript@2.1.5`

I'm assuming this is a bug, as I've spend the better part of 3 hours pouring over my code, I'm new to using botbuilder. The only fix now seems to add `next()` to every handler.

**Comment by willportnoy** [comment]
I think that's intentional, following similar conventions to the waterfall in async.js

https://caolan.github.io/async/docs.html#waterfall

so that you might have the option of choosing something else, like skipping the next step.

**Comment by bondz** [comment]
@willportnoy that makes sense, only that all the docs only used `next()` calls conditionally, I had assumed the next handler would be called automatically, thanks.
