### ISSUE TITLE
NodeJS - Is it possible to let the chat connector programmatically receive a message?

### ISSUE THREAD

**Issue by Lugo239** [Microsoft/BotBuilder#2136]
At the end of my last dialog i want to use the last user input as an input for my main dialog. 

`session.endDialogWithResult({
        response: session.message
    });`

Iam able to get the lase user message in the first step of my " \ " root dialog. Now i want to start a dialog based on the last user input. So is it possible to start a dialog with a specific input message?

Currently i need to type in the message again to properly manage the transition between the end of the last dialog and a "new" start of the root dialog.

**Comment by bondz** [comment]
Have you tried starting the dialog you want with [`beginDialog()`](https://docs.botframework.com/en-us/node/builder/chat-reference/classes/_botbuilder_d_.session.html#begindialog) passing in the conversation via `args`.

for example, in your last handler, you could have
```js
session.beginDialog('/', { message: session.message });
session.endDialog();
```

and then check in your dialog handler for `/`
```js
if (args.message) {
// The result of the last conversation
}
```

**Comment by Lugo239** [comment]
Hey bondz!

Thanks for your fast and helpful reply! It is working correctly.
At this point the last message can be used as an input for the first dialog of the root.

Thanks a lot!

**Comment by bondz** [comment]
@Lugo239 happy to help 😄

**Comment by Lugo239** [comment]
Hey its me again.

I have a follow up problem related to the way my main root is looping at this moment.

Iam enable to use the last message as input for the listen dialog. But now the `builder.Prompts` methods does not wait for user input anymore. Did smb of you got a similar problem?

**Comment by bondz** [comment]
If you were implementing the loop in the same dialog, you might want to take a look at the [loop example](https://github.com/Microsoft/BotBuilder/tree/master/Node/examples) using [`replaceDialog`](https://docs.botframework.com/en-us/node/builder/chat/session/#replacing-dialogs)

**Comment by Andrea-Orimoto** [comment]
Hi @Lugo239, it looks like this thread is solved, right? I'm closing this, but feel free to reopen or open a new issue if you still need help. Thanks!

**Comment by Lugo239** [comment]
Hey Guys!

Yes problem solved. Thanks to all of you!
