### ISSUE TITLE
[NodeJS] test RegExpRecognizers first before using luis

### ISSUE THREAD

**Issue by bondz** [Microsoft/BotBuilder#2137]
According to the [docs](https://docs.botframework.com/en-us/node/builder/chat/IntentDialog/#intent-recognizers)
> To improve performance, regular expressions are always evaluated before cloud based recognizer(s) and an exact match regular expression will avoid calling the cloud based recognizer(s) all together.

This however currently only applies to when regular expressions are specified in the match argument of the intent, as in `intent.matches(/^help/iu, waterfall)`

I think this should also be applied in the case of RegExpRecognizers before using the `LuisRecognizer`

In my case I have 
```js
import Recognizers, { LuisRecognizer } from './recognizers';
const intents = new builder.IntentDialog({ recognizers: [...Recognizers, LuisRecognizer] });
```

where `Recognizers` is an array of recognizers, 
```js
export const helpRecognizer = new builder.RegExpRecognizer('App:HelpIntent', /^(help|options)/iu);
export const testRecognizer = new builder.RegExpRecognizer('App:TestIntent', /^(test)/iu);
export const sampleRecognizer = new builder.RegExpRecognizer('App:SampleIntent', /^(sample)/iu);
```

when any of the regexes are matched, I didn't expect the cloud service be used, but this seems to be the case. Is there any way I could achieve this without having to put the regexes inline?

**Comment by Stevenic** [comment]
So we're updating the docs but now all recognizers are evaluated in parallel.  You can achieve what you're trying to do by creating an `IntentRecognizerSet` with the following options:

```
let set = new builder.IntentRecognuzerSet({
     recognizeOrder: builder.RecognizeOrder.series,
     stopIfExactMatch: true
}).recognizer(new builder.RegExpRecognizer(...))
  .recognizer(new builder.LuisRecognizer(...));
```

You can then use that `set` as if it were a single recognizer.

**Comment by bondz** [comment]
Oh, okay. Thanks.

**Comment by aakashkag** [comment]
@Stevenic  please correct typo error in answer. 'IntentRecognizerSet'
