### ISSUE TITLE
How can we leverage the same facebook bot on multiple pages

### ISSUE THREAD

**Issue by haligasd** [Microsoft/BotBuilder#2138]
Think white labeling bots.  Same engine different customers.  I believe we have to put in the page token in the config inside the portal which limits us to one page.  Maybe I missed something.  Thanks

**Comment by tomlm** [comment]
BotAuthenticationAttribute now supports the ability to have an ICredentialProvider interface which looks up the appid/password from a data store

https://docs.botframework.com/en-us/csharp/builder/sdkreference/d3/d4a/interface_microsoft_1_1_bot_1_1_connector_1_1_i_credential_provider.html

**Comment by amitbend** [comment]
@tomlm Is there an equivalent in Node?

**Comment by cesarvarela** [comment]
@tomlm I'm interested in the same, can you help us?

**Comment by amitbend** [comment]
@tomlm Can you please assist?
