### ISSUE TITLE
Image upload size limit?

### ISSUE THREAD

**Issue by jamtrup** [Microsoft/BotBuilder#2139]
Hi,
I'm having users upload an image with their chat; that image gets processed in some way.
The symptom I'm seeing is that for larger images, the image arrives in the bot and can be processed, but at the end of the dialog turn, an exception is thrown. From the logs, it seems to be this one:

  "message": "An error has occurred.",
  "exceptionMessage": "The request content length exceeded limit of 256k",
  "exceptionType": "Microsoft.Rest.HttpOperationException",
  "stackTrace": "   at Microsoft.Bot.Connector.ErrorHandling.<HandleErrorAsync>d__2`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

This does not happen in the emulator, but in web chat and Kik.

Since the image is getting into the bot and can be processed successfully, even ignoring that particular exception would work...

This is a C# bot, and the code handling the incoming image is roughly this (yes, this is a Luis bot)
```
        public void CheckForAttachment(IDialogContext context)
        {
            attachedImage = null;
            Activity a = (Activity)context.Activity;
            Attachment att = a.Attachments[0];
            if (att.ContentType == "image/png" || att.ContentType == "image/jpeg" || att.ContentType == "image/*")
            {
                using (var wc = new WebClient())
                {
                    attachedImage = Image.FromStream(wc.OpenRead(att.ContentUrl));
                    a.Text = att.ContentUrl;
                    a.Attachments = null;
                }
            }
        }
    

        [LuisIntent("")]
        public async Task None(IDialogContext context, LuisResult result)
        {
            CheckForAttachment(context);
            string message = $"Sorry I did not understand: " + ((Activity) context.Activity).Text + " Intent: " + string.Join(", ", result.Intents.Select(i => i.Intent));
            await context.PostAsync(message);
            context.Wait(MessageReceived);
        }
```

Any ideas?
Thanks,
Jan.

**Comment by willportnoy** [comment]
Any chance your attachedImage is a field of your dialog, and it's inadvertently being serialized to the state service?  If so, you might consider marking that field with [NonSerialized].

**Comment by jamtrup** [comment]
That was indeed the problem. 
Thanks so much!
