### ISSUE TITLE
Serialized data in DialogState

### ISSUE THREAD

**Issue by ahmettaha** [Microsoft/BotBuilder#214]
Hello,

Is there a view what's stored in DialogState? I want to be able to check if some secret fields are serialised and transmitted to the outside world.

**Comment by willportnoy** [comment]
Do you mean the C# or node SDK?  In the C# SDK, the data is serialized through the gzipped output of BinaryFormatter, and we would only be able to persist fields that are on classes marked serializable (unless you explicitly enable the reflection serialization surrogate)

I'm not sure about the node SDK.

For either, you can likely look at the outgoing Messages for the bot data in the per user-in-conversation, conversation, and user bags - I presume the node version's data is json.

**Comment by ahmettaha** [comment]
I mean c#. So I should never put a secret access token field in a CommandDialog class? it has the potential to be serialized and sent as a part of the dialog. Or do you only serialize data on those bags? 

something like below:

 [Serializable]
    public class BotCommandDialog
    {
        public static readonly CommandDialog<object> Dialog;
        public static string SecretToken{ get; set;}



.

**Comment by willportnoy** [comment]
I don't believe static data is serialized as part of object instances.  We do serialize instance data on dialog instances, through the standard .NET BinaryFormatter.
