### ISSUE TITLE
GatewayTimeout Error

### ISSUE THREAD

**Issue by Badolfo** [Microsoft/BotBuilder#2142]
Hi there,

I am experiencing some errors with Facebook channel, that has major impact in user experience since let users without any answer:
"There was an error sending this message to your bot: HTTP status code GatewayTimeout"

Can you help identifying the problem?
Bot is deployed on amazon ec2 machine and Bot Handle is BioNatural 

Thanks.

**Comment by eanders-MS** [comment]
Hi @Badolfo, Are you experiencing this currently? We saw a degradation in our Facebook service earlier today between 2pm and 5pm PST.

**Comment by msft-shahins** [comment]
Closing this since the Facebook service has been recovered. Feel free to open a new issue if you have any other issues.

**Comment by Badolfo** [comment]
Hi, having same error last night:
01/02/2017, 20:10:18	
There was an error sending this message to your bot: HTTP status code GatewayTimeout

Regarding @eanders-MS question, it was one hour previous to that time range that you mentioned.

Hoping you can give some help guys. Thanks
