### ISSUE TITLE
SSL Certificate for Microsoft Bot Builder

### ISSUE THREAD

**Issue by JpEncausse** [Microsoft/BotBuilder#2145]
Hi,

- I made a SSL Certificate with let's encrypt on ah-bot-pp.wipolo.com:1880
- I also buy a wildcard certificate at *.viseo.io at Gandi
- And also get a certificate at ssl.viseo.io

I get the following error (on an Azure server) :

`Error retrieving OpenId metadata at https://login.botframework.com/v1/.well-known/openidconfiguration, error: Error: Hostname/IP doesn't match certificate's altnames: "Host: login.botframework.com. is not in the cert's altnames: DNS:*.botframework.com"`

BUT It works with an other old domain secure.encausse.net

On Microsoft BotBuilderServer did you change something ?

**Comment by JpEncausse** [comment]
So to be sure the URL is here:
https://bothack.viseo.io:3980/api/v1/messages

I also put an intermediate certificate to be sure.

Everything is fine according to 
https://www.sslshopper.com/ssl-checker.html

But I keep getting
```
ERROR: Error retrieving OpenId metadata at https://login.botframework.com/v1/.well-known/openidconfiguration, error: Error: Hostname/IP doesn't match certificate's altnames: "Host: login.botframework.com. is not in the cert's altnames: DNS:*.botframework.com"
0|BotHack1 | ERROR: ChatConnector: receive - invalid signing key or OpenId metadata document.
```

**Comment by JpEncausse** [comment]
I put ENV var NODE_TLS_REJECT_UNAUTHORIZED=0 but it's very ugly fix.
And I still don't understand why on server A (with fixed ssl) it works and server B (with wildcard ssl) I have to do that

**Comment by dandriscoll** [comment]
Hi @JpEncausse, the issue appears to be that your client does not recognize/accept the wildcard SAN on login.botframework.com. The cert on your bot is probably OK.

Do you know anything about your HTTP client and whether it can accept wildcard subject alternative names?

**Comment by JpEncausse** [comment]
@dandriscoll after digging around it seems to be an issue with NodeJS not handling correctly certificate.

In NodeJS, the server try to check only SANs not CNs but for a wildcard domain i don't have SANs only CNs because I don't know what subdomain I will add

**Comment by jbdrucker** [comment]
Just a message to add up a little : we encounter the exact same problem. The framework can't retrieve the openId configuration files (through a proxy). Even a simple wget fails on that URL.

That said, we didn't have this problem last week... Our bot was restarting fine, and now it's kinda stuck at boot.

**Comment by dandriscoll** [comment]
Hi @JpEncausse  and @jbdrucker, did you recently update to Bot Builder SDK 3.5+?

**Comment by jbdrucker** [comment]
Two weeks ago yes. But our bot was working fine last week.
We're currently using the 3.5.4.

**Comment by jbdrucker** [comment]
Tried to reboot it 2 minutes ago, it went fine without any fix on our part. Still strange but great I guess.

**Comment by dandriscoll** [comment]
Bot Builder > 3.5 uses a new hostname for the Open ID metadata document that lists our services certificates. Based on the error you hit with your client, I'm in the process of changing the cert out for that service so it does not have any wildcards in the CN or SAN.

**Comment by dandriscoll** [comment]
Hi @jbdrucker and @JpEncausse, we've replaced the certificate on login.botframework.com with one that doesn't have a wildcard. Please at-mention or open a new issue if you encounter any problems with that server.

**Comment by catcher-in-the-try** [comment]
This issue is occurring for me right now, since a few minutes ago:

```
ERROR: Error retrieving OpenId metadata at https://login.botframework.com/v1/.well-known/openidconfiguration, error: Error: getaddrinfo ENOTFOUND login.botframework.com login.botframework.com:443
```

All of my bots stopped working.
