### ISSUE TITLE
Webchat control goes into infinite loop when uploading a file in Edge

### ISSUE THREAD

**Issue by brendanarnold** [Microsoft/BotBuilder#2146]
I have the following code opened as a `file://` from my desktop ...

```
<html>
    <head>
    </head>
    <body>
<iframe src="https://webchat.botframework.com/embed/hrkit?s=MYKEYHERE" style="height: 502px; max-height: 502px;"></iframe>
    </body>
</html
```

Clicking on the image button opens a file dialog which cannot be dismissed - it just reopens the dialog as soon as it is dismissed.

Microsoft Edge 38.14393.0.0
Microsoft EdgeHTML 14.14393

The inifinite loop does not occur with Chrome (latest standard release)

**Comment by eanders-MS** [comment]
@billba thoughts?

**Comment by billba** [comment]
We have another report of this over in the WebChat repo. Seems to only happen in Edge.

**Comment by danmarshall** [comment]
Wondering if it's related to React's synthetic events ? https://medium.com/@ericclemmons/react-event-preventdefault-78c28c950e46#.imcv0e2tj

**Comment by danmarshall** [comment]
Thanks for reporting @brendanarnold . I am going to close the issue here and we will track it in the webchat repo https://github.com/Microsoft/BotFramework-WebChat/issues/287
It's a known issue in Edge but we may be able to apply a mitigation.
