### ISSUE TITLE
Bot working in Web Chat but offline on Skype

### ISSUE THREAD

**Issue by BHouwens** [Microsoft/BotBuilder#2147]
I'm trying to test a Node.js bot, hosted on Heroku, in Skype. Bot gets added as a contact, but is offline and unable to respond to messages. It does work perfectly in the MS Web Chat on the bot page.

I'm not sure what other kind of info is necessary in order to make an assessment of what the issue might be, but let me know if there's anything more I can provide

**Comment by nickcordrey** [comment]
Please can you send an email to skypebotsupport@microsoft.com with the MSA App ID and name of your bot, referencing this github issue and we'll look into it.

**Comment by vatervonacht** [comment]
+1

**Comment by carlosscastro** [comment]
@BHouwens did you sent the email to Skype bot support? I', closing the issue for now, but reopen if they did not fix the issue.

**Comment by te-online** [comment]
@BHouwens Did you resolve this issue by sending an email to the mentioned address?

**Comment by te-online** [comment]
@carlosscastro or @nickcordrey Any idea how longs it's going to take for the bot support to answer my request? 

It's pretty disappointing: The bot is working, but Skype won't show the answers. I can see the requests in on the server from Skype, when I message the bot. They are the same as from the Web Chat and therefore receive the same answers. Difference: Web Chat shows them Skype doesn't. :-(

**Comment by mnehinger** [comment]
@nickcordrey @BHouwens I am running into the same issue described here - my bot does not appear online on Skype even though the server is running and it is responding in the web chat. Has there been any resolution?

**Comment by te-online** [comment]
@mnehinger Do you host on Heroku? I did resolve the issue by using a different hoster for my application. 

Switching to a paid dyno didn't make a difference and the people behind the mentioned email-address did not reply to my request.

If you are using Heroku and can't/don't want to change it, the most effective way might be to contact Heroku support about the issue, since Microsoft doesn't care.

**Comment by mnehinger** [comment]
@te-online thanks for the response. No, I'm not using Heroku, I was simply following instructions that Microsoft themselves provided to run your bot locally, and to use ngrok to expose an https endpoint. Ultimately I will be hosted on AWS Elastic Beanstalk. Which hosting service ended up working for you if you don't mind me asking?

**Comment by te-online** [comment]
@mnehinger Oh, that's interesting, so it's not specific to Heroku. Did you try changing the endpoint of your bot API (e.g. different ngrok domain, don't know if one can change that) and save the new URL in the bot backend. Maybe changing this URL did make the difference for me and not the change of providers. I'm using a small service called uberspace.de (unfortunately the service is only available in German).
