### ISSUE TITLE
Luis : 401 when trying to use the luis api programmatically

### ISSUE THREAD

**Issue by nmaroine** [Microsoft/BotBuilder#2148]
hi,
i have an issue when i try to use luis with the Api. i got a 401
for exemple ,this operation : 
https://westus.api.cognitive.microsoft.com/luis/v1.0/prog/apps/{appId}/train

**appid**       : get it from Luis interface
**password** : it's my api key from Azure (this key is associated with my Luis model)

i still have the 401 ...

**Comment by cahann** [comment]
The Azure key is only suitable for the endpoint, but for the programmatic APIs please use the prog. key under your user settings page.

**Comment by nmaroine** [comment]
[Resolved] thanks it's working for me !
you have to use this url and take the Programmatic API Key
https://www.luis.ai/Home/UserSettings

**Comment by msft-shahins** [comment]
Closing this issue since it is resolved. Feel free to open a new issue if you have other problems.

**Comment by punitganshani** [comment]
We are trying to train the LUIS model using Programmatic API & Keys but getting 401 access denied issue. Below is the snapshot from Postman

**appId** : from LUIS Model
**version** :  from LUIS Model
**programmaticKey** : retrieved from https://www.luis.ai/keys (this is not from Azure portal)

I've tried resetting the Programmatic API Key as well

**Request:**

```
POST /luis/api/v2.0/apps/{appId}/versions/{version}/train HTTP/1.1
Host: southeastasia.api.cognitive.microsoft.com
Ocp-Apim-Subscription-Key: {programmaticKey}
Cache-Control: no-cache

```
**Response:**

```
{
    "statusCode": 401,
    "message": "Access denied due to invalid subscription key. Make sure to provide a valid key for an active subscription."
}
```

Is there anything incorrect in this?
