### ISSUE TITLE
[NodeJS] Managing Dialog Data

### ISSUE THREAD

**Issue by JpEncausse** [Microsoft/BotBuilder#215]
Hi,
I have a tree of Dialogs:
1. LUIS Dialog => session.beginDialog('/sub')
1.1 Prompts + Command Dialog => session.beginDialog('/sub/sub')
1.1.1 Prompts
1.1.2 Prompts

At each level Prompts put answers in session.dialogData
When a sub Dialog ends, I call endDialog({response : subdata}) that merge with parent's dialogData

BUG ?
- It seems merged subdata is overrided by current dialog data (it works if there is no further steps)
- I want to populate my dialogData with my LUIS Entities but it seems session.beginDialog() put a new dialogData.

What should I do ? Should I backup everything in a userData and lost Dialog Scope ?

**Comment by JpEncausse** [comment]
At last I use userData to merge data of Dialog Flow it works well. I also reset data at the top of the flow (triggered by LUIS)

**Comment by Stevenic** [comment]
Can I see a simplified version of your code? There's a issue right now where your merged dialogData may not get saved if you don't send the user a message which I suspect is what's happening.

**Comment by Stevenic** [comment]
Trying to close out some of our issues so please re-open if you're still having issues.
