### ISSUE TITLE
Update Microsoft.Bot.Builder from 3.0.0 --> 3.5.1

### ISSUE THREAD

**Issue by NCZ-10** [Microsoft/BotBuilder#2151]
After updating the Bot.Builder to 3.5.0 (or3.5.1) I receive the following error: 
"Error: The bot's MSA appId or passsword is incorrect. Click here to edit your bot's MSA info."

With the "old" emulator (3.0.0.59):
401 Unauthorized
{
"message": "Unauthorization has been denied for this request."
}

The MicrosoftAppId and MicrosoftAppPassword is correct/registered and were working with the 3.0.0 package locally and deployed.

**Comment by willportnoy** [comment]
If you use the newer emulator (https://docs.botframework.com/en-us/tools/bot-framework-emulator/#navtitle) does it work?

**Comment by eanders-MS** [comment]
@NCZ-10 It sounds like you've already done this, but would you mind triple-checking your MSA info on both sides of the connection (bot and emulator)?

Here's a helpful auth debugging guide: https://docs.botframework.com/en-us/support/troubleshooting-bot-framework-authentication/

**Comment by NCZ-10** [comment]
I've tried the "old" and "new" emulator. MSA were added directly from the registration portal. 
The weird thing is that everything works fine with 3.0.0

When connecting without password on localhost the same error occurs.

**Comment by msft-shahins** [comment]
@NCZ-10 can you update to the latest emulator v3.5.25? https://emulator.botframework.com/ 

The JwtToken sent by bot to emulator have changed starting bot builder v3.5 and only new emulator can authenticate those tokens: https://docs.botframework.com/en-us/restapi/authentication/#changes

**Comment by NCZ-10** [comment]
Still using v3.5.25. 

Does the described changes allready implemented in v3.5 package

**Comment by eanders-MS** [comment]
@NCZ-10 In emulator v3.5.25 we introduced experimental support for using host proxy settings on all outgoing messages. Does your network have a proxy configuration? It's a shot in the dark, but if you do have a proxy set, you might try downgrading to emulator v3.5.23 to see if you have better luck. 

Emulator release page: https://github.com/Microsoft/BotFramework-Emulator/releases

**Comment by NCZ-10** [comment]
No I do not use a proxy.
I gave up and created a new solution which I have patched directly with 3.5.1.

**Comment by Andrea-Orimoto** [comment]
Seems like you were able to fix this, closing this issue. Feel free to reopen if you still need help, and sorry for the upgrade inconvenience.
