### ISSUE TITLE
WEB CHAT WIDGET SESSION

### ISSUE THREAD

**Issue by sayyednazeer** [Microsoft/BotBuilder#2152]
I have the Bot Web chat <iframe> tag in my application.
Is there any way to pass some session or viewstate values from my application to that web chat.

**Comment by eanders-MS** [comment]
The WebChat component will accept optional `username` and `userid` URL parameters. What is it you want to pass?

**Comment by sayyednazeer** [comment]
when a user login to my application i want to pass that login id to my bot and display the user details as a greeting.

**Comment by danmarshall** [comment]
Hi @sayyednazeer here is an example of passing information from your application to the web chat and through to your bot: https://github.com/Microsoft/BotFramework-WebChat/blob/master/samples/backchannel/index.html

**Comment by sayyednazeer** [comment]
i am working with c# and can you explain me in details what to do with this index.html file and also is i have to do any changes in index.html file..?
Thanks

**Comment by danmarshall** [comment]
Yes. So, you have an `<iframe>` which presumably has a `src=https://webchat.botframework.com/...`.
Instead of referencing there, you may host your own webchat page on your own site. You will still use an `<iframe>` but change the `src="https://yourwebsite/yourwebchatpage.html"`
See https://github.com/Microsoft/BotFramework-WebChat#embedded-via-iframe for more info.

**Comment by danmarshall** [comment]
Hi @sayyednazeer I'm going to close this issue for now. Please re-open this issue if your problem is not solved, thanks.

**Comment by gjayakumar92** [comment]
Hi @sayyednazeer @danmarshall
1) I have a website and i want to use chat bot in my website. as of now i am using iframe to embed web chat. but i want to create own web chat.

2) is there anyway to connect bot with my client without using bot connector?
I want to create the bot connector.

The main objective is i don't want to relay on any external services. i want to create it on my own.

Kindly help me on this.
Thanks in advance.

**Comment by sayyednazeer** [comment]
@gjayakumar92   you have to use the Direct Line API ...

Refer this for direct line code 

http://aihelpwebsite.com/Blog/EntryId/16/Calling-The-Microsoft-Bot-Framework-Using-The-Direct-Line-API

**Comment by gjayakumar92** [comment]
Hi @sayyednazeer is this possible to connect to mybot without using direct line?  i need to connect my bot directly. is that possible.

**Comment by sayyednazeer** [comment]
why you don't want to use any connector..?

**Comment by gjayakumar92** [comment]
@sayyednazeer  As per company norms, we should not rely on any external services. thats why i want to connect directly.
