### ISSUE TITLE
Microsoft Chat bot with Luis in AWS

### ISSUE THREAD

**Issue by Prabu-raj** [Microsoft/BotBuilder#2154]
I need to deploy my bot in Amazon Web Services instead of Azure along with luis service. Is there any possibility to do? How to get subscription key for luis without using Azure?

**Comment by dandriscoll** [comment]
Hi @Prabu-raj, yes, you can deploy your bot to AWS.

LUIS is a web service and is not something you deploy on your own. You can use LUIS from any platform, including AWS.

**Comment by Prabu-raj** [comment]
@dandriscoll How do i get the subscription key?

**Comment by Prabu-raj** [comment]
I am a newbie can  you please explain me in detail

**Comment by dandriscoll** [comment]
Hi @Prabu-raj, LUIS is just an HTTP service you call from your code. Inside the LUIS portal, you can click the Publish button to generate an endpoint your code can call. When you move your bot to AWS, you can still issue calls to the same LUIS endpoint.

If you're using the Bot Builder SDK, you do not have to make any changes. The SDK integrates with LUIS the same way in Azure and AWS.

**Comment by jameslew** [comment]
+1 to Dan's comments

Note, the subscription key you get from Azure (when you add cognitive services there) is copied and pasted into the settings dialog for your LUIS app.  Taking that step tells LUIS which Azure subscription to associate your bot's requests with.
