### ISSUE TITLE
Facebook like crush error

### ISSUE THREAD

**Issue by ebattulga** [Microsoft/BotBuilder#2156]
I'm using c# BotBuilder with LUIS. When user reply **Like** , framework return this "Sorry, my bot code is having an issue". 

1. How to handle like button?
2. How to localize "Sorry, my bot code is having an issue" text?

**Comment by willportnoy** [comment]
"Sorry, my bot code is having an issue" means there was an unhandled exception within your dialog code - can you run the code with the debugger attached to look for thrown exceptions?

**Comment by msft-shahins** [comment]
As @willportnoy suggested this means that your bot code is throwing an exception when it receives the like from facebook in the activity. You can attach debugger and see what is the exception that is getting thrown in your code. 

The UnhandledExceptionToUser is localized and will be loaded from the appropriate resource: https://github.com/Microsoft/BotBuilder/blob/3a98a6b3d15962a57b5454bfb3f730d3588de3ef/CSharp/Library/Microsoft.Bot.Builder/ConnectorEx/PostToBot.cs#L166
