### ISSUE TITLE
LUIS Programmatic API : how to add a new utterance and associate it to an intents with the api

### ISSUE THREAD

**Issue by nmaroine** [Microsoft/BotBuilder#2157]
hi guys,
i'm expolring the  LUIS Programmatic API refferences ,
and i couldnt found this 2 actions :

1. how to add a new utterance ?
2. how to associate to an intent (and maybe specify the entities)

thanks in advance 👍

**Comment by sayyednazeer** [comment]
@nmaroine 
To add the utterance, i have done like this and its works for me...
In body parameter i have remove the Entity object as i don't required

<script type="text/javascript">
    $(function() {
        var params = {
            // Request parameters
        };
      
        $.ajax({
            url: "https://westus.api.cognitive.microsoft.com/luis/v1.0/prog/apps/{appId}/example?" + $.param(params),
            beforeSend: function(xhrObj){
                // Request headers
                xhrObj.setRequestHeader("Content-Type","application/json");
                xhrObj.setRequestHeader("Ocp-Apim-Subscription-Key","{subscription key}");
            },
            type: "POST",
            // Request body
            data: '{ "ExampleText": "string",  "SelectedIntentName": "string"}' ,
        })
        .done(function(data) {
            alert("success");
        })
        .fail(function() {
            alert("error");
        });
    });
</script>
