### ISSUE TITLE
node CardImage : how to set thumbnail size in herocard

### ISSUE THREAD

**Issue by igorzhilin** [Microsoft/BotBuilder#2158]
Dear colleagues

I need to make larger thumbnails in the herocard (which I suppose should be done in CardImage.js). I would be glad to update the code myself, but I have no idea where to start. BotBuilder/Node/core/lib/cards/CardImage.js -- where should I put image size?

Thank you,
Igor.

**Comment by msft-shahins** [comment]
Currently bot doesn't have a control on the size of CardImage in HeroCard: https://docs.botframework.com/en-us/core-concepts/reference/#cardimage. The size is determined by different clients for different channels.

**Comment by AlbinShaji** [comment]
Is it possible to add page number in a hero card at the bottom?
