### ISSUE TITLE
Custom Facebook and Telegram messages

### ISSUE THREAD

**Issue by wiltodelta** [Microsoft/BotBuilder#216]
The documentation http://docs.botframework.com/connector/custom-channeldata/ specifies how to send custom messages to Slack. How can I send custom messages to Facebook and Telegram?

**Comment by Stevenic** [comment]
Is this on the C# side of things?

**Comment by wiltodelta** [comment]
Yes

Viсtor Kuznetsov

**Comment by tomlm** [comment]
I updated the documentation for facebook last night.  Telegram support is coming soon

**Comment by wiltodelta** [comment]
@tomlm Thanks!

**Comment by tomlm** [comment]
Also note I added “Attachments” section which talks about how to use attachments

**Comment by wiltodelta** [comment]
@tomlm how to use rich card attachments?

**Comment by tomlm** [comment]
http://docs.botframework.com/connector/message-actions/#navtitle
http://docs.botframework.com/connector/custom-channeldata/#navtitle

**Comment by wiltodelta** [comment]
@tomlm I tried, but nothing received:

```
Message replyMessage = context.MakeMessage();

replyMessage.Attachments = new List<Attachment>
{
    new Attachment
    {
        Title = title,
        TitleLink = titleLink,
        Text = text,
        FallbackText = text,
        ThumbnailUrl = thumbnailUrl,
        Actions = new List<Action>
        {
            new Action
            {
                Title = "Details",
                Url = titleLink
            }
        }
     }
};
```

**Comment by eanders-MS** [comment]
@wiltodelta Custom messages now supported in Telegram. Documentation here: http://docs.botframework.com/connector/custom-channeldata/#custom-telegram-messages

**Comment by wiltodelta** [comment]
@eanders-MS Thanks!

**Comment by wiltodelta** [comment]
@tomlm & @eanders-MS: I would like to try rich card attachments, but it not work for me.

**Comment by tomlm** [comment]
Can you share your attachment array?

Sent from my tumbs
________________________________

**Comment by wiltodelta** [comment]
I shared my code upper! ⬆️

**Comment by tomlm** [comment]
I tried that it worked for me.  I don't know what you are doing wrong
