### ISSUE TITLE
ICredentialProvider  question

### ISSUE THREAD

**Issue by vovanb** [Microsoft/BotBuilder#2163]
Hello team,
Can you provide ICredentialProvider  sample? How assign    AppId and Password in runtime depending from where from/to request come in?
Thanks

**Comment by MCKRUZ** [comment]
+1  Can someone give an example here? I'm having the same issues.

**Comment by willportnoy** [comment]
https://docs.botframework.com/en-us/technical-faq/#how-can-i-support-multiple-bots-at-the-same-bot-service-endpoint points to a comment with some sample code.

**Comment by sw-ms-roshanparmar** [comment]
Above url is not working . Can you please provide the another one.

**Comment by EricDahlvang** [comment]
[https://docs.microsoft.com/en-us/bot-framework/troubleshoot-general-problems#how-can-i-support-multiple-bots-at-the-same-bot-service-endpoint](https://docs.microsoft.com/en-us/bot-framework/troubleshoot-general-problems#how-can-i-support-multiple-bots-at-the-same-bot-service-endpoint)

Where there is a reference to: [https://github.com/Microsoft/BotBuilder/issues/2258#issuecomment-280506334](https://github.com/Microsoft/BotBuilder/issues/2258#issuecomment-280506334) (with an example implementation of ICredentialProvider).
