### ISSUE TITLE
DIRECT LINE SAMPLE CODE

### ISSUE THREAD

**Issue by sayyednazeer** [Microsoft/BotBuilder#2164]
Hi,

Does any bdy having some working sample code for BOT to call using Direct Line with Jquery Ajax.
My Bot code is in c#

**Comment by dandriscoll** [comment]
https://github.com/Microsoft/BotFramework-DirectLineJs would be a great starting point

**Comment by dandriscoll** [comment]
Also forgot about this JS sample: https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node/core-DirectLine

**Comment by thstarshine** [comment]
It would be great to list these example repos on the documentation website (https://docs.botframework.com/en-us/restapi/directline3/) , thanks!

**Comment by EricDahlvang** [comment]
I'm closing this issue since the original question has been answered.  

(also note: documentation updates coming soon)
