### ISSUE TITLE
Facing Problem with folder structure

### ISSUE THREAD

**Issue by Sid245439** [Microsoft/BotBuilder#2165]
I am not understanding from which folder I need to push my code ,I want only DemoSkypeCalling bot .
Should I push my code from /examples/DemoSkypeCalling or should I push code from root directory.
Please help me in deploying DemoSkypeCalling application.

I am delpoying it on azure!

**Comment by msft-shahins** [comment]
/examples/DemoSkypeCalling has all the code for the bot. you need to add a package.json similar to this [sample](https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node/core-SendAttachment) to make sure that your node app has all the required dependencies. 

here is also a step by step guide on how to deploy to azure: https://docs.botframework.com/en-us/node/builder/guides/deploying-to-azure/#navtitle%5D
