### ISSUE TITLE
LUIS Programmatic API : Publish error 400

### ISSUE THREAD

**Issue by nmaroine** [Microsoft/BotBuilder#2167]
im trying to publish my Luis Model via api ,
but i dont understand how it works ?
the method called : 
https://westus.api.cognitive.microsoft.com/luis/v1.0/prog/apps/{appId}/publish

there is the response bodyof my post 400
{
  "error": {
    "code": "BadArgument",
    "message": "Cannot find an application with the specified ID"
  }
}
im usind this app id 

![image](https://cloud.githubusercontent.com/assets/17453646/22553707/ffbf24ec-e95d-11e6-91c3-1457f4d78433.png)

![image](https://cloud.githubusercontent.com/assets/17453646/22553938/b5a84662-e95e-11e6-90c4-8df53c7611e8.png)

i'm i wrong ? i just want to update the luis model i just trained ...
thanks in advance .

**Comment by msft-shahins** [comment]
For luis programatic API you need to use your cognitive services subscription key which is different that Microsoft App Id. You can find further documentation here: https://dev.projectoxford.ai/docs/services/56d95961e597ed0f04b76e58/operations/5739a8c71984550500affdfa

**Comment by nmaroine** [comment]
it's not a key problem , im not geting a 401 not autorized , im getting a 400 , Bad argument ...

**Comment by msft-shahins** [comment]
I looked at the Microsoft App Id and thought you are getting 401. But you need to use luis subscription key and not the Microsoft App Id when calling to Luis programmatic api that is the main reason that you get 400.
