### ISSUE TITLE
There was a problem synchronizing your bot to Skype.

### ISSUE THREAD

**Issue by inornos** [Microsoft/BotBuilder#2168]
This Is My Skype I'm Unable To Start Chatting And Use It What i do please check below images
In My Skype Its Showing Me **Messaging disabled until request is accepted** i'm Accept Contact Request But Not Working After That

![image](https://cloud.githubusercontent.com/assets/14770190/22549803/36ef69b2-e973-11e6-8e8b-2246237f8b66.png)

In My Bot Login Its Showing Me **There was a problem synchronizing your bot to Skype.** WHat is It This is the error and my problem please Help Me
And This Is The Issue in My Bot On dev.botframework.com

![image](https://cloud.githubusercontent.com/assets/14770190/22549864/743aafd4-e973-11e6-887a-0a0561c708e6.png)

**Comment by dandriscoll** [comment]
Hi @inornos, can you send your bot's handle or app ID and we can investigate?

**Comment by inornos** [comment]
My Bot's Handle  **NimaCreation**

**Comment by dandriscoll** [comment]
Hi @inornos, we're investigating the error. This appears to be an intermittent failure, and I re-synchronized your bot and it seems to have been written successfully.

You can trigger re-synchronize by editing your bot and clicking the "save" button.

**Comment by dandriscoll** [comment]
Hi again @inornos, we figured this out.

This was a timing error on our side that we'll have fixed soon. You can clear the error from your Skype error list. It's unlikely you'll hit this problem again but if you do, simply edit and save the bot to retry.

**Comment by inornos** [comment]
Thanks For Support I tried As You Say But Some Of The Command Not Working In Skype Like **0.8-2 rd d-h if-vvs2**
Please Help

**Comment by inornos** [comment]
New Issue In My Bot See This Image

![image](https://cloud.githubusercontent.com/assets/14770190/22678989/ad986848-ed24-11e6-9035-1416409ce526.png)

Please Help It Is the Serious Issue

**Comment by inornos** [comment]
My Skype Bot Not Working

**Comment by dandriscoll** [comment]
Hi @inornos, this error means that we were not able to contact your bot's endpoint.

**Comment by inornos** [comment]
So Please Guide Me To Solve This Issue

**Comment by inornos** [comment]
Hello Please Guide Me What I Do My Skype Not Working After Edit And Re Save The Bot As You Say....

**Comment by dandriscoll** [comment]
The synchronization issues described in the original bug are resolved. Please open a new issue if you want to discuss further.

**Comment by njss** [comment]
this error still exists :(

**Comment by nwhitmont** [comment]
@njss You are commenting on a closed issue. Please open a new issue if you are experiencing problems.

**Comment by mcrepy** [comment]
obtained this error today...
