### ISSUE TITLE
send message with non devlopper account facebook  : no reply

### ISSUE THREAD

**Issue by barigo** [Microsoft/BotBuilder#217]
hi , 
i have issue with facebook bot,

when i use my own account , i can get reponse and receive message to my webhook.

but when i send message from an other user account , i got nothing.

is the app should be published and accepted by facebook to have access from all other users?

many thanks

**Comment by msft-shahins** [comment]
Your app should be reviewed and accepted by Facebook before any other user can talk to your bot. 

> To use Messenger platform, your app needs to be approved for Send/Receive API (pages_messaging).

 users listed as admins, developers, and testers for your app, can interact with the app while it is under development.

**Comment by barigo** [comment]
thanks you for your reply.
