### ISSUE TITLE
Question | DirectLine message Ids

### ISSUE THREAD

**Issue by JPThorne** [Microsoft/BotBuilder#2170]
So we've got a web interface which uses https://www.npmjs.com/package/botframework-directlinejs (works really well) and we use the fact that messages returned via directline (bot and user msgs) have a messageId of the format "G0SRNz7iwTiLehjQsXk3tI|0000001", "G0SRNz7iwTiLehjQsXk3tI|0000002" etc to sort on the sent and received ones on our FE. 

However... Messages (Activities) in the bot code itself have a messageId of the format of a GUID. Even if you got to that point in code from a request via directline. 

So my question is: does directline have some sort of interception and enrichment of the messages (ids) on your side before returning to the user? Why then do these messages not have the same ID in our bot code itself?

Reason I'm asking is, we broadcast messages to a separate 'admin-console' via signalR. But the message has a GUID id. But the message had a directline id on the webchat side.

You can imagine how this mucks with sorting messages in their correct order. Especially as the timestamp on the messages is not reliable - messages are frequently in the wrong order. 

Any feedback very much appreciated.

**Comment by dandriscoll** [comment]
Hi @JPThorne, activity IDs are designed to be stable between the bot and the client.

At the moment, our storage system is assigning serial IDs for all activities that are stored. However, not all activities are stored -- for example, Typing activities are sent without being stored in the message history. Those activities will not have serial IDs.

Are you seeing literal GUIDs as the activity ID? We don't generate any GUIDs -- even the IDs assigned to Typing activities are random strings, similar to our conversation IDs.

**Comment by JPThorne** [comment]
Hi @dandriscoll thanks for the reply. 

So, we are seeing literal GUIDs, well, a string version of a guid. For example, for the same "hi" message to our bot via directline, and then broadcasting the activity via signalR we see these two different messageIds:

0b4213bc-9c14-4787-819f-c53be27b20f0
2EUT44oscMYLKOpPmqG7bj|0000001

Maybe we're just misunderstanding things here - for example, we use IDialogContext.MakeMessage in several places to construct a message activity, and I'm seeing that that creates a new guid as the message id... obviously it wouldn't know about it's previously received messageId.

**Comment by dandriscoll** [comment]
Activity IDs are assigned exclusively by the service, so even though the SDK may be generating IDs, those will be thrown out when the message is persisted. Most of our channels do this, and this mandatory in Direct Line as the service uses the ID for sequencing. If you want to add correlation information, you can do that in the ChannelData field, which will be passed between your client and your bot.

**Comment by ederbond** [comment]
hy @dandriscoll , I'm trying to intercept all the incoming and outgoing messages on my bot code (.net) using an IActivityLogger but when the messages  (IActivity)  sent from my bot to the client gets intercepted on my IACtivityLogger it never have the "id" property filled, it is always null (even for activities of type "message"). It is driving me nuts to figure out why the activities sent from my bot to the client doesn't have the "Id" property properly assigned before it gets sent to the directline ? on my client side (directlineJS) the id propperty gets gratefully asigned for all messages in the format "2EUT44oscMYLKOpPmqG7bj|0000001". I was expecting to see the same when I intercept the messages on my IActivityLogger so I could create a history on my company's CRM software.
Is there any way I can get the same value for the IActivity.Id on both client and server side ?
