### ISSUE TITLE
In Review Status

### ISSUE THREAD

**Issue by Boober44b** [Microsoft/BotBuilder#2171]
How long does a bot normally stay in review status before it gets published?

**Comment by msft-shahins** [comment]
@jameslew or @Andrea-Orimoto can you comment?

**Comment by Andrea-Orimoto** [comment]
Hi @Boober44b,

we try to review as fast as we can, usually within a week, even though we experienced significant delays in the past. Do you have a bot stuck in review? If yes, please let us know your bot handle, and we'll take a look.

Thank you

**Comment by Andrea-Orimoto** [comment]
Closing this for now, due to inactivity. Do not hesitate to reopen it if you still need help. Thanks!

**Comment by indesit** [comment]
Hi there!
Could anybody answer how long I should wait till obt will pass through review status? It's more then month gone.
Thanks
