### ISSUE TITLE
bot.recognize runs twice once the user send a message.

### ISSUE THREAD

**Issue by Jyoti1009** [Microsoft/BotBuilder#2172]
I am trying to run something similar to the below code:
`bot.recognizer({
        recognize: function (context, done) {
        logger.info("Inside recognizer");
        //Some other code     
        }
    });`

This prints the message twice for each message from the user.
Can someone please explain why would that be?

**Comment by Stevenic** [comment]
Let me try to reproduce this...

**Comment by Stevenic** [comment]
Good bug... I'm checking in a fix now and will release a new 3.6.0 update this afternoon that will include the fix.

**Comment by Stevenic** [comment]
Closing this so please let me know if 3.6.0 doesn't fix your issue for some reason.
