### ISSUE TITLE
[MS Teams Channel] imBack support markdown

### ISSUE THREAD

**Issue by alex182** [Microsoft/BotBuilder#2173]
Say I have a heroCard that has a button of the type imBack.  Is there a way to format the text sent to the bot when that button is pressed using markdown?  I can format the text sent from the bot using markdown/html/css, but not the messages sent to the bot from the user.

**Comment by RichMoeMSFT** [comment]
We currently don't have a way to use markdown in the reply back.  Can you explain what you're looking for and the use case?

**Comment by alex182** [comment]
I was looking for a way to hide some of the text that is sent back to the bot (a guid to be exact) to get around Teams not supporting the postBack action type.  It seems like Teams HTML encodes whatever text it is sent using the imBack action.

**Comment by RichMoeMSFT** [comment]
We will be rolling out a solution for this in a few weeks.

**Comment by carlosscastro** [comment]
@RichMoeMSFT Any updates on this?

**Comment by RichMoeMSFT** [comment]
We just rolled out the new **invoke** action, which allows you to send JSON payload as a result of your button click.  Think of this as a silent postBack.  Check out the documentation [here](https://msdn.microsoft.com/en-us/microsoft-teams/botsmessages#action---invoke-new)
