### ISSUE TITLE
How to pass session variable into DialogAction.validatePrompt ?

### ISSUE THREAD

**Issue by aekynr** [Microsoft/BotBuilder#2174]
Hi, i want to pass Session variable to builder.DialogAction function.
How can i do that?

My scenario is as follows;
`session.beginDialog('validators:/begin/',{
     prompt: "hello",
     retryPrompt: "sorry",
     maxRetries: 2
});`

`library.dialog('/begin',
    builder.DialogAction.validatedPrompt(
        builder.PromptType.text, function(response){
            return validateFunction(response);
    })
);`

i need to pass session object to the validateFunction like validateFunction(session, response) but couldn't do that?

**Comment by msft-shahins** [comment]
@carlosscastro or @maxpert or @Stevenic  can you comment?

**Comment by aekynr** [comment]
Still waiting for comment..

**Comment by gEndelf** [comment]
Guys @danmarshall @msft-shahins! We still need help. thx

**Comment by aekynr** [comment]
@gEndelf let me explain how i deal with this issue.

**open:** node_modules/botbuilder/lib/dialogs/DialogAction.js
**change** this line;
`valid = validator(r.response);`
with the following one;
`valid = validator(r.response, s.dialogData);`

then you can use session.beginDialog function as follows;

```
session.beginDialog('validators:/',{
   prompt: "hello",
   retryPrompt: "i didnt understand",
   maxRetries: 2,
   userId: session.message.address.user.id
});
```

and then, you can use that variables inside of validators' file as follows;

```
library.dialog('/',
    builder.DialogAction.validatedPrompt(
        builder.PromptType.text, function(response, args){
            var userId = args.userId;
            return getAnswer(userId,response);
    })
);
```

Until they share valid answer with us, i prefer to modify core library..
@msft-shahins thank you for your interests..

**Comment by gEndelf** [comment]
@aekynr thx man! it's easy and works )

**Comment by gEndelf** [comment]
@aekynr but how it can be used on production?

**Comment by Stevenic** [comment]
So I would actually recommend building a completely custom prompt versus using the `validatedPrompt()`. As you've noticed validated prompts have some limitations and a custom prompt will let you do anything you want. See the [basics-customPrompt](https://github.com/Microsoft/BotBuilder/tree/master/Node/examples/basics-customPrompt) example.

**Comment by danmarshall** [comment]
@aekynr @gEndelf thanks for filing. Please re-open a new issue if the basics-customPrompt does not solve your issue, I'm going to close this issue for now.

**Comment by Abrahamlincoln006** [comment]
You can download the newest questions and answers in this PDF file: 
http://www.dumps4download.com/microsoft.html
