### ISSUE TITLE
Bot can't recognize messages in goups

### ISSUE THREAD

**Issue by DmitryZemlyuk** [Microsoft/BotBuilder#2175]
Hi everyone =)
Today I have a little problem: my bot stopped recognize messages in groups, but successfully recognize messages in 1:1 dialog. 
Few month ago I solved this problem with usage this issue https://github.com/Microsoft/BotBuilder/issues/860.

Example:

if (address.channelId === "skype" && address.conversation.isGroup) {
						if (message.entities.length > 0) {
							var content = message.text;
							message.entities.forEach(function(entity) {
								content = message.text.replace(entity.text, '');
							});
							session.message.text = content.trim();
						}
					}

But today problem returned - bot stopped recognize messages in groups. I don't change anything in sources before problem returned.

So, if anybody know how fix this problem - write me, please.
p.s. Bot written with usage Node.js.
p.s.s. Sorry for bad English =(

**Comment by msft-shahins** [comment]
@Stevenic or @maxpert can you comment?

**Comment by Stevenic** [comment]
@DmitryZemlyuk have you tried stepping through your code to see why its behaving differently?  I realize you didn't change anything but skype may have,

**Comment by DmitryZemlyuk** [comment]
@Stevenic few days ago I'm replace logic for answering bot (closure with regular expression). That's helped me and my bot and working now. Thanks for helping and answers.

**Comment by Stevenic** [comment]
no problem
