### ISSUE TITLE
Problem with callback url

### ISSUE THREAD

**Issue by Sid245439** [Microsoft/BotBuilder#2176]
I have deployed my code and added it into my skype account ,when I make voice call the bot in the skype it always gives me reply "You can talk to bot just yet but we are working on it ". I am not sure about the callback URL which I placed in the code and in developer portal of Skype.

I hav used following URLs
http://skypebottestd.azurewebsites.net/api/calling/callback
http://skypebottestd.azurewebsites.net/api/calling/call

**Comment by KrishnanA** [comment]
You cannot use http URLs. AFAIK, the portal prevents http URLs. Please use https URLs.
