### ISSUE TITLE
What is the difference between these 2 Middlewares

### ISSUE THREAD

**Issue by slidenerd** [Microsoft/BotBuilder#2177]
```
Middleware.dialogVersion = function (options) {
        return {
            botbuilder: function (session, next) {
                var cur = session.sessionState.version || 0.0;
                var curMajor = Math.floor(cur);
                var major = Math.floor(options.version);
                if (session.sessionState.callstack.length && curMajor !== major) {
                    session.endConversation(options.message || "Sorry. The service was upgraded and we need to start over.");
                }
                else if (options.resetCommand && session.message.text && options.resetCommand.test(session.message.text)) {
                    session.endConversation(options.message || "Sorry. The service was upgraded and we need to start over.");
                }
                else {
                    session.sessionState.version = options.version;
                    next();
                }
            }
        };
    };
    Middleware.firstRun = function (options) {
        return {
            botbuilder: function (session, next) {
                if (session.sessionState.callstack.length == 0) {
                    var cur = session.userData[consts.Data.FirstRunVersion] || 0.0;
                    var curMajor = Math.floor(cur);
                    var major = Math.floor(options.version);
                    if (major > curMajor) {
                        session.beginDialog(consts.DialogId.FirstRun, {
                            version: options.version,
                            dialogId: options.dialogId,
                            dialogArgs: options.dialogArgs
                        });
                    }
                    else if (options.version > cur && options.upgradeDialogId) {
                        session.beginDialog(consts.DialogId.FirstRun, {
                            version: options.version,
                            dialogId: options.upgradeDialogId,
                            dialogArgs: options.upgradeDialogArgs
                        });
                    }
                    else {
                        next();
                    }
                }
                else {
                    next();
                }
            }
        };
    };
```

they both take a version number. In order to provide an upgrade experience, which one do I need, it seems firstRun does everything including the part where it takes the upgradeDialogId. so what do I need the other one for

Thanks for your answers in advance

**Comment by michaelvol** [comment]
+1 for the question. 

Should these two be combined or only use firstRun? 
Is the purpose of dialogVersion to end the conversation (clear the stack) so that the next msg will get to the firstRun dialog? 
In this case looks like only a second msg sent by the user will reach session.beginDialog...?

Thanks

**Comment by Stevenic** [comment]
The `dialogVersion` middleware does something different. It's designed to address an issue that can happen when you make a radical change to your bots structure. Users can get into a stack state in certain cases and `dialogVersion` lets you track which version of the dialog system a given conversation is using. It will automatically call `endConversation()` when it detects an old version of the dialog system to avoid the user getting stuck.

The `firstRun` middleware is more user facing and lets you redirect to a different dialog flow the first time you see a user. This has nothing to do with resetting the conversation.

**Comment by slidenerd** [comment]
+1 for the answer @Stevenic  one additional question right here so that it doesnt add another issue, is there a way to customize that "sorry I upgraded that service" message to show perhaps a keyboard?
