### ISSUE TITLE
Attachment unavailable

### ISSUE THREAD

**Issue by slidenerd** [Microsoft/BotBuilder#2178]
Kindly have a look at this screenshot
![3a448c74104cc0d22ba8702ee69eea8d94e4f29910aae7db8c pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/5139030/22595668/76f0469a-ea4e-11e6-9ee5-045dcd6c5f2d.jpg)
I was trying to send a hero card with text and buttons and got this. Now this is a very rare event and I havent seen this more than twice in 200 times which brings me to a question

1. Is this related to the bot framework in any way?
2. Is there some way I can prevent such errors?

Thank you for your answers in advance

**Comment by msft-shahins** [comment]
This is an error message generated by facebook. It seems that it can be related to this facebook issue: https://developers.facebook.com/bugs/368236213542077/.
