### ISSUE TITLE
updated dialog is not applied

### ISSUE THREAD

**Issue by ahmettaha** [Microsoft/BotBuilder#218]
Hello,

When I change implementation of the dialogs, the bot acts like old code is still active, until I delete all data. Then new code becomes active. Is there a way to enforce the changes automatically? I assume this happens because the implementation of the dialog is serialised. Is this correct?

**Comment by willportnoy** [comment]
The dialog stack and state is serialized, yes, though not the actual implementation.

You would need to introduce a version to denote changes you feel are significant enough to delete the serialized dialog call stack state.  If you wanted to wipe the dialog state on every code change version, you might consider using a C# assembly version that updates on every build.

**Comment by MichaelLubow** [comment]
Does this mean that the bot framework is keeping track of the state of each user in a dialog flow automatically? So for instance, if a user is using sms to interact with a bot and I update, they will forever remain with the old dialog stack and state?

Is there a way to clear the dialog state on every commit change when using the Node implementation?

**Comment by willportnoy** [comment]
Yes, the bot framework builder SDK is persisting the dialog stack/state for every user in a conversation through the messages it sends through the bot framework connector.  They will continue to use the old state until it's cleared.  The benefit is that the bots can remain stateless across requests and scale across multiple machines.

@Stevenic how can somebody detect a significant enough change in the dialog code to warrant dropping the serialized dialog stack/data?

**Comment by Stevenic** [comment]
So a couple of things for the Node.js version... 
* We're planning to add a way to set the version of the dialogs you're using. If you then increment this version number when you make a change that will cause all older stacks to get reset. This should be in soon.
* Today you could write a piece of middleware that manually inspects the stack, `session.sessionState.callstack`, and calls `session.reset()` if you detect an issue.
* You say you're seeing a difference of behavior between BotConnectorBot & TextBot. Could you elaborate? Any differences should be minor.

**Comment by Stevenic** [comment]
Please reopen if you're still having issues.
