### ISSUE TITLE
Webchat iframe does not work on Safari

### ISSUE THREAD

**Issue by ubreddy** [Microsoft/BotBuilder#2181]
older messages are getting repeated and sometimes the answers provided to questions are not getting recognized. 
The iframe widget on safari seems to have problems. Will this browser be supported?

**Comment by eanders-MS** [comment]
Hi @ubreddy This is a good question to pose over at the WebChat's repo: https://github.com/Microsoft/BotFramework-WebChat/issues. Can you open an issue there?

**Comment by danmarshall** [comment]
Closing this issue here, and we can track it in the WebChat repo.
