### ISSUE TITLE
Webchannel does not show Bot icon

### ISSUE THREAD

**Issue by ubreddy** [Microsoft/BotBuilder#2184]
Web Channel preview iframe does not show the bot icon for each of bot messages. It is available in non-preview version. But non preview version has more issues that are fixed in preview version.

**Comment by dandriscoll** [comment]
Hi @ubreddy, this is a good discussion to have over at the Web Chat repo, can you file an issue there?

https://github.com/Microsoft/BotFramework-WebChat/issues

**Comment by ubreddy** [comment]
Sure. But web chat repo is for our own customisations isn't it?The one hosted by Microsoft belongs here or there?Anyway will report there too.On 05-Feb-2017 3:31 AM, dandriscoll <notifications@github.com> wrote:Hi @ubreddy, this is a good discussion to have over at the Web Chat repo, can you file an issue there?
https://github.com/Microsoft/BotFramework-WebChat/issues

**Comment by dandriscoll** [comment]
Hi @ubreddy, you're right, the web chat control has two homes :) This particular question is probably better answered on the other repo, though.
