### ISSUE TITLE
How to exit conversation from prompt?

### ISSUE THREAD

**Issue by deepakmhr** [Microsoft/BotBuilder#2185]
Use case:  A prompt choice implemented as infinite retries and I want to exit from the conversation without choosing any options.

are there any ways to exit from the conversation without choosing any options?

Actually I am looking for command like /reset

eg:

bot.dialog('/choose',
 [
    function (session) {
        builder.Prompts.choice(session, 'choose type:', ["Computer", "Laptop", "tablet", "Mobile", "phablet"]);
    },

    function (session, results, next) {
        switch (results.respond.index) {
            case 0:
                session.send('You selected %s', results.respond.entity)
                break;
            case 1:
                break;
                session.send('You selected %s', results.respond.entity)
            case 2:
                break;
                session.send('You selected %s', results.respond.entity)
            case 3:
                break;
                session.send('You selected %s', results.respond.entity)
            case 5:
                break;
        }
    }
]);

**Comment by amitbend** [comment]
You can:
1) use default case 
`switch(expression) {
    case n:
        code block
        break;
    case n:
        code block
        break;
    **default:
        code block**
}`

2) use global actions - so when a user says 'help' for example, he is being moved to a different dialog
see - https://docs.botframework.com/en-us/node/builder/chat-reference/classes/_botbuilder_d_.dialog.html#triggeraction

3) use your own custom prompt

**Comment by deepakmhr** [comment]
Thank you so much @amitbend

**Comment by msft-shahins** [comment]
Also you can pass maxRetries as part of prompt options to the choice prompt. here is an example: https://github.com/Microsoft/BotBuilder/blob/2826c4757be5488ecc13926ecdf540254bf9715d/Node/examples/basics-customChoicePrompt/savedListPrompt.js#L19
