### ISSUE TITLE
[MS Teams Channel] Button click from hero returns smbapostback

### ISSUE THREAD

**Issue by johnabele** [Microsoft/BotBuilder#2188]
Unmodified bot started returning the following messages from hero card button clicks breaking functionality. Works fine in slack/skype preview/web chat.

&lt;smbapostback v=&quot;V2hhdCBhcmUgdGhlIFNpeCBEaW1lbnNpb25zIG9mIFdlbGxuZXNzPw==&quot;&gt;some text&lt;/smbapostback&gt;

**Comment by alex182** [comment]
Teams doesn't support postBack.  So far it only supports imBack and openUrl as the button types. 

[Check here for more details](https://msdn.microsoft.com/en-us/microsoft-teams/bots)

**Comment by RichMoeMSFT** [comment]
We just added the **invoke** action - think of it as a silent postBack.  See [here](https://msdn.microsoft.com/en-us/microsoft-teams/botsmessages#action---invoke-new) for more information.
