### ISSUE TITLE
Sorry, my bot code is having an issue.

### ISSUE THREAD

**Issue by sayyednazeer** [Microsoft/BotBuilder#2189]
Today i am getting this response from the BOT "Sorry, my bot code is having an issue."
With Direct Line API using Jquery Ajax and my bot is in c#.

And when i go to the portal and click on test connection i got this message 
"This item cannot be accessed or modified.

![bottestconnerror](https://cloud.githubusercontent.com/assets/10753866/22637164/53846c58-ec66-11e6-9376-9354af4e65da.png)
"

**Comment by msft-shahins** [comment]
"Sorry, my bot code is having an issue." is a message generated by bot builder SDK when your code is throwing an unhandeled exception. Can you debug your instance and see what is the exception that is getting thrown?

**Comment by dandriscoll** [comment]
The error "the item cannot be accessed or modified" is a bug in our dev portal. We hope to have a fix for this available soon. You can fix the problem yourself by clearing your cookies for dev.botframework.com.

**Comment by Andrea-Orimoto** [comment]
hi @sayyednazeer, as @dandriscoll says we're working on a fix, should be deployed soon. if you're still stuck, try signing out and then signing back in. it should fix it.

**Comment by sayyednazeer** [comment]
@dandriscoll @Andrea-Orimoto  resolved thanks..
