### ISSUE TITLE
How change current form to another form?

### ISSUE THREAD

**Issue by FordSoft** [Microsoft/BotBuilder#219]
Hello. I have several forms, each with its own style. How can I change the current form, depending on the business logic? (C#)

**Comment by willportnoy** [comment]
You could have a root dialog that decides which form to call as a child, based on your business logic.

**Comment by jcalixte** [comment]
Hello, 

Is there an example of a root dialog routing to multiple FormDialog FormDialog ?

Thank you.

**Comment by FordSoft** [comment]
Thanks. Now I understand. For example see Microsoft.Bot.Sample.PizzaBot . 

you need "Call" method:

```
var pizzaForm = new FormDialog<PizzaOrder>(new PizzaOrder(), this.MakePizzaForm, FormOptions.PromptInStart, entities);
context.Call<PizzaOrder>(pizzaForm, PizzaFormComplete);
```
