### ISSUE TITLE
Not able to open www.luis.ai website.

### ISSUE THREAD

**Issue by singhsurya** [Microsoft/BotBuilder#2190]
Hi,

I am facing issue in opening [LUIS Website](https://www.luis.ai/). It hangs right on the account login page with message - Please wait a few moments... Initializing. Is there some issue in LUIS or I am missing something?

@dandriscoll

**Comment by palmerabollo** [comment]
Works for me. Can you try using an incognito window?

**Comment by jameslew** [comment]
I thought I was reproducing this, and then refreshing the window went away.  I'd agree with @palmerabollo , try incognito and see if you get a different response.

**Comment by JPThorne** [comment]
+1 this happens for us too

![image](https://cloud.githubusercontent.com/assets/1411816/22679374/59721b84-ed0a-11e6-850b-412990723965.png)

Refreshing does the trick, but this error will cause the whole site to just hang. 

The error occured when opening an app, and then pressing browser back. It's stuck on Initializing.

**Comment by jameslew** [comment]
We have a new portal UI coming with a new codebase very shortly that should address this issue.  We'll do announcements when the new UI has dropped.  In the mean time, thanks for the report!

**Comment by jameslew** [comment]
The new portal has released - it would be great to hear if you're having the same problem or not.  Thanks!

**Comment by singhsurya** [comment]
This issue is resolved but another issue I am experiencing now with new portal. In new issue, when I click on my application link under my apps tab, it hangs here and does not open the application.
