### ISSUE TITLE
[Feature Request] Call forwarding

### ISSUE THREAD

**Issue by angsm** [Microsoft/BotBuilder#2192]
Hi, 

May I know if phone numbers will be supported or is there some way I can forward a skype bot call to another user?

Thank you.

**Comment by KrishnanA** [comment]
This is not something that we support today but will consider this for a future release. It will be good if you can give more information about your scenario.

**Comment by angsm** [comment]
I intent to create a bot framework based service that when called, can either answer or forward the call to another agent with relevant information if it does not have the answer. 

If a number can be attached to the skype bot, it can be used as a frontline point of contact.

**Comment by awebdeveloper** [comment]
I am also looking forward to this. 
Here is the use case.  User calls the bot picks up. It tries to answer the user's query. If it fails to provide an answer then it needs to forward the call(skype or phone) to a human.

**Comment by berdin123** [comment]
Can i forward a call to a user with bot response now ?
