### ISSUE TITLE
How to send youtube video to the channels?

### ISSUE THREAD

**Issue by deepakmhr** [Microsoft/BotBuilder#2193]
This is the code snippet I tried but not working:

`var videoURL="https://www.youtube.com/watch?v=qO7BA9i72Gw"

    var message = new builder.Message(session)
        .attachments([{
            contentType: "video/mp4",
            contentUrl: commonFunctions.validateAndGetURL(videoURL)
        }]);

    session.send(message)`

**Comment by danmarshall** [comment]
YouTube videos are not MP4 videos, they are a proprietary YouTube format only playable in a YouTube player. So just send the URL, do not use an attachment.

**Comment by danmarshall** [comment]
I'm closing this issue for now, please re-open if needed.
