### ISSUE TITLE
[Question] Slack channels issues

### ISSUE THREAD

**Issue by sisense** [Microsoft/BotBuilder#2194]
Hi there,

I encounter many issues with the framework handling slack channels (isgroup = true)

Basically the Bot listens to all messages and not only once it is approached @MyBot

I'm solving it by modifying prepIncomingMessage in ChatConnector.js 
```
 if (isGroup && msg.text.length > 0)
   {
            if(msg.text.indexOf('@' +  msg.address.bot.name) == -1 && msg.address.channelId == 'slack'    && !msg.sourceEvent.Payload)
            {
                msg.text = '';
                msg.address = {};
                return; 
            }
            else
            {
                var x = /<\/at>\s?(.*?)$/g.exec(msg.text); 

                if(x && x.length > 0)
                msg.text = x[1];
            }
        }
```

This created an ugly error at other places but at least it works. 

Anybody have an idea how to solve it more elegantly?

DD

**Comment by willportnoy** [comment]
@craigjensen does slack have some semantic about including user names as an at-mention in the message text?

**Comment by craigjensen** [comment]
Our Slack channel strips out the native @mention from the text and replaces it with a mention entity that contains the raw text of the mention.  

For example, if ```@testbot Hello``` is sent from Slack the bot should receive a message something like this:

```
{
  "type": "message",
  "serviceUrl": "https://slack.botframework.com",
  "channelId": "slack",
  "from": {...},
  "conversation": {...},
  "recipient": {
    "id": "...",
    "name": "testbotv"
  },
  "text": " Hello",
  "entities": [
    {
      "type": "mention",
      "mentioned": {
        "id": "...",
        "name": "testbot"
      },
      "text": "@testbot"
    }
  ]
}

**Comment by nwhitmont** [comment]
@sisense reopen if you're still having issues with this.
