### ISSUE TITLE
Slack group does not get general messages

### ISSUE THREAD

**Issue by sisense** [Microsoft/BotBuilder#2195]
Hi,

Using my bot in Slack I see a strange problem: typing **help** gets into the default recogniser and not getting detected as if I would write the same in 1on1 chat with the Bot. 

Any ideas? 
DD

**Comment by chk1** [comment]
Your bot won't receive messages in a group unless you to add `@your_bot_name` to the message, see issue #1669

**Comment by kkarahainko** [comment]
Hi. 

Seems like the same issue, how to make bot answer only to "@mybot message", now it answers to all messages in a group chat (channel) like in private chat (direct messages) with bot.

Thanks.
K

**Comment by aakashvit** [comment]
@Stevenic  can u suggest something about it . I am getting same issue.
https://github.com/Microsoft/BotBuilder/issues/2196

**Comment by sisense** [comment]
Not the greatest solution but solved for now. I changed chatconnector.js prepIncomingMessage function to: 

`ChatConnector.prototype.prepIncomingMessage = function (msg) {
        utils.moveFieldsTo(msg, msg, {
            'locale': 'textLocale',
            'channelData': 'sourceEvent'
        });
        msg.text = msg.text || '';
        
        var isGroup = msg.conversation.isGroup;
 
        msg.attachments = msg.attachments || [];
        msg.entities = msg.entities || [];
        var address = {};
        utils.moveFieldsTo(msg, address, toAddress);
        msg.address = address;

      
        
        if (isGroup && msg.text.length > 0)
        {
            if(msg.sourceEvent.Payload && msg.sourceEvent.Payload.actions && msg.sourceEvent.Payload.actions[0].type && msg.sourceEvent.Payload.actions[0].type == 'button')
            {

            }
            else if(msg.text.indexOf('@' +  msg.address.bot.name) != 0 && msg.address.channelId == 'slack')
            {
                msg.text = '';
                return; 
            }
            else
            {
                var x = /<\/at>\s?(.*?)$/g.exec(msg.text); 

                if(x && x.length > 0)
                msg.text = x[1];
            }
        }
        
        msg.source = address.channelId;
        if (msg.source == 'facebook' && msg.sourceEvent && msg.sourceEvent.message && msg.sourceEvent.message.quick_reply) {
            msg.text = msg.sourceEvent.message.quick_reply.payload;
        }
    };`

**Comment by nwhitmont** [comment]
@sisense  thanks for the update. I'm glad you found a solution!
