### ISSUE TITLE
Get duration between bot sending message and user replying

### ISSUE THREAD

**Issue by slidenerd** [Microsoft/BotBuilder#2197]
Hi, first of all thank you for your awesome work in building and maintaining this library.
I have a scenario in which I need to check if the person answered within 10 seconds. I have some code that looks similar to this where I measure the start time in the first waterfall step and I measure the end time in the next waterfall step, I ll find the difference between both in the second waterfall step.
```
bot.dialog('/duration', [(session, args)=>{
    session.dialogData.startTime = new Date().getTime()
}, (session, results)=>{
    session.dialogData.endTime = new Date().getTime()
}])
```
I feel that the code above is not accurate. I have seen a session.message.timestamp property. How would it be different than the code above

1. Is there a better way to measure time differences like these?
2. How do I account for network latency in such a scenario?

Thank you for your answers in advance

**Comment by slidenerd** [comment]
I improvised a bit by having the session.message.timestamp in the answer. I am assuming this timestamp is the one generated at Facebook or is it generated when the bot framework receives the message. I would like to know the exact duration between the bot sending the message and the user replying to it

**Comment by Stevenic** [comment]
Yes... the message timestamp is probably more accurate but I don't believe its provided for all channels so I would probably use a combination of both approaches.

**Comment by Stevenic** [comment]
Closing this for now but please feel free to comment

**Comment by Samox** [comment]
Hi all !
I would like to restart a conversation if a user does not reply within some time (lets say 10 minutes). 
For instance the user is in a restaurantBookingDialog when he was prompted a restaurant name. If he comes back the next day, I want to make sure he goes back to the root dialog.

Not really sure this question belong here though.
