### ISSUE TITLE
unable to deserialize the response

### ISSUE THREAD

**Issue by lonche** [Microsoft/BotBuilder#2198]
This exception is thrown when initializing conversation with user. (locally)
So far I have this :

```
var obj = model[i];
                    var userAccount = new ChannelAccount(obj.toId, obj.toName);
                    var botAccount = new ChannelAccount(obj.fromId, obj.fromName);
                    var connector = new ConnectorClient(new Uri(obj.serviceUrl));

                    IMessageActivity message = Activity.CreateMessageActivity();
                    if (!string.IsNullOrEmpty(obj.conversationId) && !string.IsNullOrEmpty(obj.channelId))
                    {
                        message.ChannelId = obj.channelId;
                    }
                    else
                    {
                        obj.conversationId = (await connector.Conversations.CreateDirectConversationAsync(botAccount, userAccount)).Id;
                    }

                    if (botAccount.Name == "")
                        botAccount.Name = "Bot";
                    if (userAccount.Name == "")
                        userAccount.Name = "User";



                    message.From = botAccount;
                    message.Recipient = userAccount;
                    message.Conversation = new ConversationAccount(id: obj.conversationId);
                    message.Text = "Hello, this is a notification";
                    message.Locale = "en-Us";
                    await connector.Conversations.SendToConversationAsync((Activity)message);
```

My message object : 

> {Microsoft.Bot.Connector.ChannelAccount} Id: "49gjgijl7a4inc821c" Name: "Bot"
> 
> message.Recipient {Microsoft.Bot.Connector.ChannelAccount} Id: "default-user" Name: "User"
> 
> message.Conversation {Microsoft.Bot.Connector.ConversationAccount} Id: "a0m69i29gih3kjf3mc" IsGroup: null Name: null
> 
> message.Text = "Hello, this is a notification"; message.Locale = "en-Us";

I'm getting this error when trying to post :

> 
Unable to deserialize the response.

e.InnerException

> {"Unexpected character encountered while parsing value: <. Path '', line 0, position 0."} Data: {System.Collections.ListDictionaryInternal} HResult: -2146233088 HelpLink: null InnerException: null LineNumber: 0 LinePosition: 0 Message: "Unexpected character encountered while parsing value: <. Path '', line 0, position 0." Path: "" Source: "Newtonsoft.Json" StackTrace: " at Newtonsoft.Json.JsonTextReader.ParseValue()\r\n at Newtonsoft.Json.JsonTextReader.Read()\r\n at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)\r\n at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)\r\n at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)\r\n at Microsoft.Rest.Serialization.SafeJsonConvert.DeserializeObject[T](String json, JsonSerializerSettings settings)\r\n at Microsoft.Bot.Connector.Conversations.d__6.MoveNext()" TargetSite: {Boolean ParseValue()}

Any help ?

Edit : This is how I deserialize object.

 ```
HttpContent requestContent = Request.Content;
            string jsonContent = requestContent.ReadAsStringAsync().Result;
            List<ConversationModel> model = new List<ConversationModel>();


            try { 
            model = JsonConvert.DeserializeObject<List<ConversationModel>>(jsonContent);
```

This is my object content :

 

> channelId: "emulator"
>     conversationId: "a0m69i29gih3kjf3mc"
>     email: "some-email@hotmail.com"
>     fromId: "49gjgijl7a4inc821c"
>     fromName: ""
>     serviceUrl: "http://localhost:3979"
>     toId: "default-user"
>     toName: "
> 

I am adding to name and from name explicitly for local testing (see the code).

Any suggestion / help how to solve this ?

**Comment by willportnoy** [comment]
It's possible you're getting an xml error page versus a well-formed json response.  Can you use a tool like fiddler to look at the http response?

**Comment by lonche** [comment]
I solved this issue. 
So, i was getting conversation parameters after a redirect when authentication succeed. Now, i changed the code(logic), so, first i get parameters and store in a static class, then redirect the user and finally, save conversation object in database. 
Later, i initialize conversation with parameters from database. Everything works fine.

**Comment by SkyQuant** [comment]
**lonche**, could you describe fully your solution of serialization/deserialization activity for persisting in database? May be as different project on Github with activities extension method realization.

**Comment by SkyQuant** [comment]
_ResumptionCookie_ solution with GZipSerialize method quite simple.
Look at this post [http://robinosborne.co.uk/2017/01/02/sending-proactive-botframework-messages/](url)

**Comment by lonche** [comment]
You have posted invalid link. It shows error 404.
Actually, the solution i used is casting context.activity as an object of activity class.
