### ISSUE TITLE
geographic endpoint not working

### ISSUE THREAD

**Issue by stephaneey** [Microsoft/BotBuilder#2199]
Hello,

As I encounter awful response time despite of a very basic bot, I tried to use europe.directline.botframework.com instead of the default one. However, when monitoring the HTTP traffic, I see that it is not working:
![bot2](https://cloud.githubusercontent.com/assets/2558877/22655175/9db53446-ec8f-11e6-95d8-2e0201611dcd.png)

The above picture shows the websocket switch but it fails without websockets too.

Best Regards

**Comment by dandriscoll** [comment]
Hi @stephaneey, we've been experiencing intermittent interruptions in our European datacenter. We're actively fixing and monitoring this. At the moment all services appear to be stable, but please let us know if you see any additional degradation.

**Comment by stephaneey** [comment]
Hi @dandriscoll , indeed it's working now. However, I don't see any performance improvement. My message endpoint is hosted in Europe but it's calling LUIS (westus). Directline is often returning a 504 bad gateway because of the response time that exceeds 15 seconds. I thought that using the europe endpoint could help but it doesn't. My bot couldn't be simpler as it's only starting a LUIS dialog to detect the intent (nothing more). I added some execution time calculation and noticed that simply detecting the user intent takes about 7 seconds...Any clue on how to improve performance here?

thanks

**Comment by jameslew** [comment]
Hi @stephaneey .  We're currently working on deployments for Europe and other datacenters.  They are not ready for use yet, but will be very soon.

Other improvements we're making to LUIS are on some of the particularly heavily used recognizers such as the datetime and number recognizers, which are occasionally hopping to the wrong datacenter.  Finally spelling is something we're looking at; it's an off-service call if you enable it which adds latency to the call.

All up, we're working on this - knowing which features you're using would help us know how to pinpoint the latency problems you're seeing.

**Comment by sayyednazeer** [comment]
I am also getting the same error... #2078 
my LUIS takes too long time to detect which intents to called in my case it takes 24-25 sec.
Due to which it exceeds its 15 sec response time and i got the internal server or gateway timeout error.

**Comment by stephaneey** [comment]
I only have a lightweight LUIS model; no bing spell check. My LUIS takes about 7 secs but the overall process is often above the 15 seconds, hence resulting in a bad gateway problem. Code wise, I only have "case message": reply typing reply, reply with luisdialog. Inside of the triggered intent, I'm just replying a text message. This is alrready almost unusable a is and my bot is still doing nothing. My goal is to interact with some systems with the user input and that will surely take time...meaning that if things don't change, i'll always be above 15 seconds.

Also, something annoying, when a typing reply is sent by the bot, it's not taken into account by the 5 seconds delay. I understand that the reply is retrieved by the websocket channel and not by the HTTP post query but this is annoying. Maybe a good idea to increase the 15 seconds timeout or to make it configurable somehow.

**Comment by sayyednazeer** [comment]
yes you are correct, when i stuck with this issue i have also change my whole code and just write the default code to simple return the count of string, but at then also it takes long time to detect the intents.
And some time it works and detect the LUIS intent within 3-4 sec and some time it takes too long.

my code within the intents takes only 2 seconds to execute. I think 15 seconds timeout is very less as overall execution of the codes cross the 15 seconds.

**Comment by sayyednazeer** [comment]
@jameslew  any update / comment..?

**Comment by dandriscoll** [comment]
Closing this issue as functionality on all geographic Direct Line endpoints has been restored. If you want to discuss Direct Line or LUIS endpoints, please open a new issue.
