### ISSUE TITLE
Attachment with embedded content

### ISSUE THREAD

**Issue by jakobpn** [Microsoft/BotBuilder#220]
Can anyone share the sample code for sending back a reply with an image attached as an embedded object?

Thanks!

**Comment by tomlm** [comment]
“attachments”: [
                {
                                “contentType”:”image/jpeg”,
                                “contentUrl”:http://imgr.com/ahdhh
                }
]

**Comment by Stevenic** [comment]
Please re-open if this didn't answer your question.

**Comment by jakobpn** [comment]
Thx Tom and Steven. It did answer my question.
