### ISSUE TITLE
can't run a custom IDialog from Chain

### ISSUE THREAD

**Issue by DeLeneMirouze** [Microsoft/BotBuilder#2200]
I built a custom IDialog, but I am unable to run it from Chain.

I tested this:

` public static readonly IDialog MyDialog = Chain
        .PostToChain()
     .Select(_ => "Hello, what's your name?")
     .PostToUser()
     .WaitToBot()
        .ContinueWith(_ => new SimpleDialog())
        .PostToUser();`

But I get this error message: 

_The type arguments for method 'Chain.ContinueWith(IDialog, Chain.Continuation)' cannot be inferred from the usage. Try specifying the type arguments explicitly_

This is my dialog:

`[Serializable]
public class SimpleDialog : IDialog
{
    public async Task StartAsync(IDialogContext context)
    {
        context.Wait(MessageReceivedAsync);
    }

    private async Task MessageReceivedAsync(IDialogContext context, IAwaitable<IMessageActivity> argument)
    {
        IMessageActivity message = await argument;
        int length = (message.Text ?? string.Empty).Length;

        await context.PostAsync($"You sent **{message.Text}** which was **{length}** characters");
        context.Wait(MessageReceivedAsync);
    }
}`

Is there something I am missing?

**Comment by msft-shahins** [comment]
ContinueWith needs a lambda with two parameters. Also you don't need PostToUser() at the end unless you want to post the result produced by SimpleDialog to user. I modified your code and this should work:

```csharp

public class MyDialog
{

    public static readonly IDialog<object> Dialog = Chain.PostToChain().
        Select(_ => "Hello, what's your name?").
        PostToUser().
        WaitToBot().
        ContinueWith((context, acitivty) =>
        {
            return Task.FromResult<IDialog<object>>(new SimpleDialog());
        });
}

[Serializable]
public class SimpleDialog : IDialog
{
    public async Task StartAsync(IDialogContext context)
    {
        var message = (IMessageActivity)context.Activity;
        await context.PostAsync($"You sent **{message.Text}** which was **{(message.Text ?? string.Empty).Length}** characters");
        context.Wait(MessageReceivedAsync);
    }

    private async Task MessageReceivedAsync(IDialogContext context, IAwaitable<IMessageActivity> argument)
    {
        IMessageActivity message = await argument;
        int length = (message.Text ?? string.Empty).Length;
        await context.PostAsync($"You sent **{message.Text}** which was **{length}** characters");
        context.Wait(MessageReceivedAsync);
    }
}

[BotAuthentication]
public class MessagesController : ApiController
{
    /// <summary>
    /// POST: api/Messages
    /// Receive a message from a user and reply to it
    /// </summary>
    public async Task<HttpResponseMessage> Post([FromBody]Activity activity)
    {
        if (activity.Type == ActivityTypes.Message)
        {
            await Conversation.SendAsync(activity, () => MyDialog.Dialog);
        }
        var response = Request.CreateResponse(HttpStatusCode.OK);
        return response;
    }
}

```
