### ISSUE TITLE
[Direct Line]  No response from Bot.

### ISSUE THREAD

**Issue by pranavjain** [Microsoft/BotBuilder#2202]
Hi,
I am using directline API to access bot using PHP cURL. Lot of time it happens that my request is being sent to bot (via POST) but when I do GET on 'conversations/id/messages/' there is just my request but no response from bot. This issue is occurring randomly. I also tried waiting after sending POST request.
Could someone please check this?

Also, I would like to add PHP script to repository as there are many developers across different forums who want to access bot framework using PHP. {Open for Suggestions} @dandriscoll

**Comment by palmerabollo** [comment]
We are also facing issues today. I think something is broken in the Bot Connector.

**Comment by dandriscoll** [comment]
Hi @pranavjain and @palmerabollo, we have been experiencing intermittent load issues in our European datacenter. We are actively working on resolving the issue.

**Comment by pranavjain** [comment]
Thanks for the update @dandriscoll. Would you like to include PHP directline api example in documentation and repository?
I would love to contribute to BotBuilder.

**Comment by danmarshall** [comment]
Thank you for your contribution @pranavjain 
@RobStand do we have a place where we can put a PHP sample?

**Comment by pranavjain** [comment]
@RobStand  Is there an update?
@danmarshall Could you please help me to close this?

**Comment by danmarshall** [comment]
Hi @pranavjain - I do not think we have a slot in our documentation hierarchy to host a PHP specific page. The closest thing would be the https://github.com/Microsoft/botbuilder-samples repo but PHP does not have adequate coverage there.

**Comment by nwhitmont** [comment]
@pranavjain we recommend using the officially supported Direct Line client for JS here: https://github.com/Microsoft/BotFramework-DirectLineJS
