### ISSUE TITLE
[Feature Request] launch chat bot on the fly. (send invitation to other chatbot)

### ISSUE THREAD

**Issue by pvagare** [Microsoft/BotBuilder#2204]
I have one chatbot. I am talking to that chatbot. I want to launch new chatbot from one chatbot
Is it possible ? 

Please let me know the response.

**Comment by danmarshall** [comment]
Hi @pvagare this is a popular requested feature but it is currently not part of the SDK.

**Comment by pvagare** [comment]
Hi @danmarshall  I watched one Microsoft event video. In that video I saw that one user is talking chabot on skype and automatically in that conversation other chatbot introduced . suddenly second chatot started giving reply to one user in same conversation.  

Who introduced the second chatbot into the conversation ? can you help me to sort out? Or Is skype bringing second chatbot into conversation ? 

Please let me know the response ?

**Comment by danmarshall** [comment]
Can you provide a link to the video? A scenario like this can become somewhat complex.

Does the user get "transferred" to a new bot and begin a new conversation? Or are all bots in a group conversation? If so, which bot responds to which messages.

 It also depends on which channel you are on, based on that channel's capabilities. I would imagine that what you've seen was a custom engineered scenario, but there is no "one size fits all" approach.

**Comment by pvagare** [comment]
@danmarshall  Thanks for reply. I will give you the link.

**Comment by nwhitmont** [comment]
@pvagare are you using C# or Node SDK for BotBuilder?

**Comment by pvagare** [comment]
@nwhitmont I am using c#

**Comment by EricDahlvang** [comment]
Channel specific requirements and restrictions make this enhancement implausible.
