### ISSUE TITLE
Microsoft.Bot.Connector: Authorization for Microsoft App ID "X" failed with status code Forbidden.

### ISSUE THREAD

**Issue by rupeshtech** [Microsoft/BotBuilder#2205]
I am already seeing some issue related to this same issue, but none of them helped.

I am creating a BOT using azure bot service and set some intents in LUIS. When I am testing bot in Azure Portal getting the issue 
Functions.messages. Microsoft.Bot.Connector: Authorization for Microsoft App ID e1f860e9-eced-4417-9dac-f77eb985ed19 failed with status code Forbidden.

My bot name is tamtambot

**Comment by Andrea-Orimoto** [comment]
Hi @rupeshtech ,

please review this issue https://github.com/Microsoft/BotBuilder/issues/1641, it might be related. Are you replying to a ping message?

let me know if this doesn't solve your issue.

**Comment by rupeshtech** [comment]
Thanks for referring the isse 1641, but that doesn't help. 
"Are you replying to a ping message?". I didnt get this Question completely but I think the following line
await Conversation.SendAsync(activity, () => new BasicLuisDialog()); is throwing error.

![bot_error2](https://cloud.githubusercontent.com/assets/24852402/22773209/241e3268-eea1-11e6-81d0-2314dfa723e9.PNG)

**Comment by vovanb** [comment]
same problem

**Comment by willportnoy** [comment]
@rupeshtech can you share your packages.config so we can see what versions of Microsoft.Bot.* packages you're using?

**Comment by rupeshtech** [comment]
I have uploaded the whole solution on git hub... please find it here
https://github.com/rupeshtech/tamtambot

**Comment by rupeshtech** [comment]
guys , any update??

**Comment by willportnoy** [comment]
Sorry for the delay in response.

@rupeshtech we've made a release of the Bot Builder with some updated diagnostics for authentication issues:
https://github.com/Microsoft/BotBuilder/releases/tag/Nuget3.5.3

Otherwise, we recommend:

https://docs.botframework.com/en-us/technical-faq/#how-can-i-troubleshoot-my-bots-authentication

**Comment by punitganshani** [comment]
@willportnoy Even with Microsoft.Bot.Builder `3.5.5` I am facing same issue

```
Authorization for Microsoft App ID xxxx-xxxx failed with status code Forbidden and reason phrase 'Forbidden'
```

Any suggestions?

**Comment by willportnoy** [comment]
@punitganshani what happened when you followed the steps in https://docs.botframework.com/en-us/technical-faq/#how-can-i-troubleshoot-my-bots-authentication ?

**Comment by rupeshtech** [comment]
seems that issue is fixed with new realease...
