### ISSUE TITLE
Conversation restart after triggerAction

### ISSUE THREAD

**Issue by Jyoti1009** [Microsoft/BotBuilder#2208]
Hi @Stevenic, 

I need help with the triggerAction command. I am trying to code as below:

` if (<some_condition>) {
                intent = { score: 1.0, intent: 'idu' }; 
                done(null, intent);                 
            }
            `
and define the dialog as below:

`bot.dialog('/idu', [
        function (session) {
            builder.Prompts.text(<some_text>);
            session.endDialog();
        }
    ]).triggerAction({ matches: 'idu' });
`
This triggers the dialog as expected however, once the /idu dialog ends, it restarts the conversation rather than falling back to the flow where the dialog was triggered. Could you let me know if there is a way to avoid restarting the conversation from the beginning?

Thanks for your help.

**Comment by tahsintahsin** [comment]
+1

**Comment by Jyoti1009** [comment]
Hi @Stevenic  Could you please redirect me to someone who can help?

**Comment by danmarshall** [comment]
It seems from the [documentation](https://docs.botframework.com/en-us/node/builder/chat-reference/classes/_botbuilder_d_.dialog.html#triggeraction), that triggerAction is meant to clear the dialog stack. You may need to use [dialogInterrupted](https://docs.botframework.com/en-us/node/builder/chat-reference/classes/_botbuilder_d_.dialog.html#dialoginterrupted) to save the state of the current dialog prior to it being cleared.

**Comment by Stevenic** [comment]
@Jyoti1009 Dan is correct that trigger actions by default "interrupt" any current dialogs by clearing the stack.  You can avoid that by using a global `bot,beginDialogAction()` instead. So from your example try:

```
bot.dialog('/idu', [ 
     function (session) { 
          builder.Prompts.text(<some_text>); 
          session.endDialog(); 
     } 
]);
bot.beginDialogAction('beginIduDialog', '/idu', { matches: 'idu' });
```
