### ISSUE TITLE
cookie in bot framework

### ISSUE THREAD

**Issue by ashay-88** [Microsoft/BotBuilder#2209]
Hi, 
I want to use webchannel for out bot. this we'll use on our sharepoint.com homepage. 
We have certain microservices, token based authentication.
I want to access a cookie created by our sharepoint online website, and use username in that to find token and use that token for webservices. 

Is it possible for webchannel bot?
I am thinking to store token in BotData userdata.
I dont know how will I access that cookie. If i get hold on it, i can find token. 

Pls suggest. 
Regards,
Ashay

**Comment by danmarshall** [comment]
Take a look at the WebChat repo, you may be interested in using the backChannel feature to send additional information: https://github.com/Microsoft/BotFramework-WebChat#using-the-backchannel

**Comment by EricDahlvang** [comment]
I'm closing this issue, since the question has been answered.
