### ISSUE TITLE
Broken links in Facebook

### ISSUE THREAD

**Issue by wiltodelta** [Microsoft/BotBuilder#221]
Message #1:
```
LONG_TEXT
_Link:_ [Open](LONG_URL_BEGIN
```

Message #2:
```
LONG_URL_END)
```

Converting markdown markup must be performed before the separation into multiple messages. Links should be transferred fully to new message.

**Comment by v-thgratMSGit** [comment]
Closing this issue due to age. @wiltodelta - please open a new issue if this issue is not fixed and needs further discussion. @tomlm - reopen if necessary.  Thanks!
