### ISSUE TITLE
DirectLine upload endpoint file size limit

### ISSUE THREAD

**Issue by admeister** [Microsoft/BotBuilder#2210]
I've been having problems uploading photos to DirectLine taken with an iPhone camera when developing a native app.

http://stackoverflow.com/questions/42109661/upload-max-file-size-for-botframework-directline

Just wondering if there is an upload max file size limit. If so, what it it?

**Comment by dandriscoll** [comment]
Hi @admeister, I responded over on SO as well, but if you can send a Conversation ID I can see what the error is that you're hitting.
