### ISSUE TITLE
service url https://smba.trafficmanager.net/apis/

### ISSUE THREAD

**Issue by astutesoftware** [Microsoft/BotBuilder#2211]
https://smba.trafficmanager.net/apis/ endpoint when used in service url throws 500 error code.
Old conversations while using https://skype.botframework.com/v3/conversations/ still work but the newer conversations do not work on the old service url and neither in the new service url.
Help...

**Comment by dandriscoll** [comment]
Hi @astutesoftware, this is a new ServiceUrl used by the Skype service. Can you provide your bot ID or bot handle so we can investigate?

**Comment by astutesoftware** [comment]
906ff232-4a6d-4266-8d94-a632aa781575
RouteMobile

**Comment by astutesoftware** [comment]
I am trying to hit
https://smba.trafficmanager.net/apis/v3/conversations/29:1LeI7sRbDBW-9iANdAOF-Fed3AXKIVABFArq_IUafLFfHmoySBpzcX06E2BiN223j/activities

and end up with
{"message":"An error has occurred."}"
HTTP/1.1 500 Internal Server Error
Content-Length: 36
Content-Type: application/json; charset=utf-8
Server: Microsoft-HTTPAPI/2.0
Date: Wed, 08 Feb 2017 18:06:11 GMT
Connection: close

{"message":"An error has occurred."}

**Comment by konstlut** [comment]
@astutesoftware Thank you for reporting. Would you please provide an example of the payload you are sending in your hero card. I am mostly concerned about the 'images' section of the card.

**Comment by astutesoftware** [comment]
{"from":"RouteMobile@960kQbHj8Ok", "type":"message","attachmentLayout":"carousel","text":"Pricing information for Nepal","attachments":[{"contentType":"application\/vnd.microsoft.card.hero","content":{"title":"Namaste(NT Mobile)","subtitle":"\u20ac0.02400","images":{"url":"https:\/\/67.media.tumblr.com\/avatar_050b045e3b18_128.png"}}},{"contentType":"application\/vnd.microsoft.card.hero","content":{"title":"Ncell (Spice Nepal)","subtitle":"\u20ac0.06600","images":{"url":"https:\/\/67.media.tumblr.com\/avatar_050b045e3b18_128.png"}}}]}

**Comment by astutesoftware** [comment]
yes you are right.. when replaced the hero card with a generic text message with no attachments it went through. My image payload is definitely the culprit.

**Comment by konstlut** [comment]
@astutesoftware Right, so your payload is not mapping the schema. Not images should be an array. we will change 500 to 400, and here is the working example:
```
{
   "type":"message",
   "attachmentLayout" : "carousel",
   "attachments":[ 
      { 
         "contentType":"application/vnd.microsoft.card.hero",
         "content": 
          {
            "title":"Namaste(NT Mobile)",
            "subtitle":"\u20ac0.02400",
            "images": **[** {"url":"https://upload.wikimedia.org/wikipedia/en/a/a6/Bender_Rodriguez.png"} **]**
          }
      },
      {
         "contentType":"application/vnd.microsoft.card.hero",
         "content": {
            "title":"Ncell (Spice Nepal)",
            "subtitle":"\u20ac0.06600",
            "images": **[** {"url":"https://upload.wikimedia.org/wikipedia/en/a/a6/Bender_Rodriguez.pngg"} **]**
         }
      }
   ]
 }
```

**Comment by Andrea-Orimoto** [comment]
Hi @astutesoftware, seems like this issue was fixed. Please reopen if this is not the case. Thanks a lot for reporting!

**Comment by konstlut** [comment]
The fix was deployed.
