### ISSUE TITLE
reset bot in teams channel

### ISSUE THREAD

**Issue by suddenelfilio** [Microsoft/BotBuilder#2213]
Hello

is there a way to reset a bot from teams. I've tried removing the Teams channel and adding it back, but the bot won't respond to anything anymore. I kind of sitting with a mute bot in my Teams...

**Comment by danmarshall** [comment]
C# or Node.js ?

**Comment by suddenelfilio** [comment]
Node

**Comment by danmarshall** [comment]
Have you tried this:
https://docs.botframework.com/en-us/technical-faq/#my-bot-is-stuck--how-can-i-reset-the-conversation

**Comment by RichMoeMSFT** [comment]
By stuck do you mean you're not receiving anything from Teams?  Have you tried running you code locally with ngrok to see if Teams is hitting it?

https://docs.botframework.com/en-us/node/builder/guides/core-concepts/#debugging-locally-using-ngrok

**Comment by suddenelfilio** [comment]
/deleteprofile did the trick thanks a lot
