### ISSUE TITLE
Unable to retrieve matched value from a FormFlow regex pattern

### ISSUE THREAD

**Issue by Montacia** [Microsoft/BotBuilder#2215]
I am trying to retrieve phone numbers using the following code in my form:

        [Prompt("What is your new number?")]
        [Describe("Phone Number")]
        [Pattern(@"(\+?(\d{2})?[ -]?0?\d[ -]?\d{4}[ -]?\d{4})")]
        public string phone { get; set; }

        public static IForm<ContactDetails> BuildForm()
        {
            return new FormBuilder<ContactDetails>()
                .AddRemainingFields()
                .Confirm("Is this phone number correct?"
                    + "\n* Phone Number: {phone}")
                .Build();
        }

When the user replies to the prompt with a string such as "My phone number is 02 5554 7429" I am trying to capture the phone number only and store that to the phone field, 
however currently it just stores the whole string not the section that was matched which is what would be preferred in the Confirm prompt.

Is it possible to set the `phone` field to just what the pattern matches within Form Flow?

**Comment by Montacia** [comment]
Managed to extract the substring that matched the regex pattern by using `validate:` in `.Field()` when instantiating form builder like so:

       return new FormBuilder<ContactDetails>()
                .Field("phone",
            validate: async (state, response) =>
            {
                Regex pattern = new Regex(@"((((\+\d{2}[ -]?)|0?)|\d{2})\d[ -]?\d{2,4}[ -]?\d{4,5})");
                Match match = pattern.Match(response.ToString());
                var result = new ValidateResult();
                if (match.Success)
                {
                    result.IsValid = true;
                    result.Value = match.Value;
                }else
                {
                    result.Feedback = "I'm sorry but I was unable to find a valid phone number please try again.";
                    result.IsValid = false;
                }
                return result;
            })
                .AddRemainingFields()
                .Confirm("Is this phone number correct?"
                    + "\n* Phone Number: {phone}"
                .Build();


Still don't really see why it doesn't extract matched value with just the tag though, wouldn't it make more sense to store the matched value rather than the whole input string if a pattern is provided?

**Comment by msft-shahins** [comment]
@chrimc62 can you comment?

**Comment by chrimc62** [comment]
The intent of the pattern is not for extraction but for validation.  If you want to extract then writing a validator the way you did is the right solution.
