### ISSUE TITLE
I have updated the bot builder to version 3.5.2. The endpoint in LuisModel.cs is not yet changed????

### ISSUE THREAD

**Issue by PrasadGautham** [Microsoft/BotBuilder#2216]
https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Microsoft.Bot.Builder/Luis/LuisModel.cs

 public static readonly IReadOnlyDictionary<LuisApiVersion, Uri> LuisEndpoints = new Dictionary<LuisApiVersion, Uri>()
        {
            {LuisApiVersion.V1, new Uri("https://api.projectoxford.ai/luis/v1/application")},
            {LuisApiVersion.V2, new Uri("https://api.projectoxford.ai/luis/v2.0/apps/")}
        };

When will the endpoint be updated in this dll? This endpoint is going to be deprecated soon right??

**Comment by cahann** [comment]
The endpoint v1 will be deprecated in three months.

**Comment by cahann** [comment]
Can you please update the V2 URI to https://westus.api.cognitive.microsoft.com/luis/v2.0/apps/

**Comment by stevengum97** [comment]
The V2 URI has been changed to reflect the new [**endpoint**](https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Microsoft.Bot.Builder/Luis/LuisModel.cs#L165). Closing issue.
