### ISSUE TITLE
Is there any way to directly transfer control from chat application to the bot framework, ie: by excluding all the channels including directline and authentication in between?

### ISSUE THREAD

**Issue by PrasadGautham** [Microsoft/BotBuilder#2217]
We are currently using Direct line Api for communication with BOT framework. But we are facing challenges with response time. So we are  thinking if we can change the architecture so that our custom chat application will directly contact the BOT framework instead of going to Direct line and other authentication processes. Is this possible?

**Comment by gjayakumar92** [comment]
@dandriscoll i have hosted my bot application. i need to connect my bot without using directline api. can you tell me is there anyway? i mean is there anyway to create custom emulator?

**Comment by dandriscoll** [comment]
Hi @gjayakumar92, your bot is just a web service, and you can open custom endpoints on that bot if you'd like.
