### ISSUE TITLE
Json response for the intent in Luis is coming wrong, although it is set as intended by me in the Luis application.

### ISSUE THREAD

**Issue by PrasadGautham** [Microsoft/BotBuilder#2218]
I will illustrate with this example:

This is how the intent is set in the luis application. The application is trained and then updated and published:
![intent set in app](https://cloud.githubusercontent.com/assets/23548463/22771572/8e5c0b2a-eebd-11e6-8a12-3decc40fc254.PNG)

 But the Json response is as follows:

![jsonresponse](https://cloud.githubusercontent.com/assets/23548463/22771604/bb2e9546-eebd-11e6-9826-12cf5a7a3f7e.PNG)

This occurs very rarely. But can't this issue be resolved??

**Comment by yshahin** [comment]
This is a misunderstanding of the results.
The score in the JSON is the published model score of this utterance.
The score in the dropdown is either the label; which is 1 if you have labeled this before. Or if this is a new utterance its the trained model score.

What you need todo is
1. train the application and publish to push the trained model to be the published one.
2. if this doesn't solve the issue, that means the underlying ML is confused about this utterance so
    a. you need to add more examples to enforce this concept
    b. you need to add more features to help the ML model to learn this, by using phraselist or regex features

**Comment by PrasadGautham** [comment]
But I selected it to be shown as "none" intent here. So the best intent/top scoring intent should be "none" right?

**Comment by bondz** [comment]
I have a similar issue too, not as regards the intent but an entity, LUIS labels the entity in the statement in the dashboard for the app, and when I try the same statement with the publish URL, sometimes it picks it up, most times, it just doesn't which is annoying sometimes. This happens only if the particular phrase is present in the statement.
