### ISSUE TITLE
Integrate Luis Preview API

### ISSUE THREAD

**Issue by markusf** [Microsoft/BotBuilder#222]
Hey guys, are there any plans to integrate the luis preview api?

**Comment by Stevenic** [comment]
We haven't decided yet. It's not clear how stable it is yet. We do plan to fully support the non-preview parts of LUIS.

**Comment by v-thgratMSGit** [comment]
Moved to UserVoice: https://feedback.botframework.com/forums/354222-bot-builder-sdk/suggestions/13787820-integrate-luis-preview-apis
