### ISSUE TITLE
System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by vovanb** [Microsoft/BotBuilder#2220]
Updated to Microsoft.Bot.Builder to 3.5.2 and Microsoft.Bot.Builder.FormFlow.Json 3.1.0
After call to :
`   return Chain.From(() => FormDialog.FromForm(preChatInquery.BuildJsonForm))
                .Do(async (context, order) =>
                {
`
An exception of type 'System.IO.FileNotFoundException' occurred in Microsoft.Bot.Builder.dll but was not handled in user code

Additional information: Could not load file or assembly 'Microsoft.Bot.Builder, Version=3.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.

**Comment by vovanb** [comment]
Solved only by adding below to app.config: 
`
     <dependentAssembly>
        <assemblyIdentity name="Microsoft.Bot.Builder" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.5.2.0" newVersion="3.5.2.0" />
      </dependentAssembly>
`

**Comment by willportnoy** [comment]
@vovanb thank you for the fix - usually NuGet adds the bindingRedirects for you, but it looks like it missed them this time.  I'm going to close this issue for now, since it appears to have been resolved.
