### ISSUE TITLE
[Question] Localization and bot.send

### ISSUE THREAD

**Issue by michaelvol** [Microsoft/BotBuilder#2221]
Hey,

bot.send is an alternative to bot.beginDialog for proactive messages but there is no session object involved here.  
What's the correct way to use localization strings (after all, we send messages to the user...) if I only want to use bot.send (because bot.beginDialog will end the active conversation)?

On the same topic - let's say I want to include in my message some personal data that's stored in userData, how can I access this data without using bot.beginDialog?

Thanks.

**Comment by ajaxav** [comment]
Interested too. Trying to localize a welcome message on conversationUpdate.

**Comment by nwhitmont** [comment]
@michaelvol you can access the user data via the session object, eg. `session.userData`.

**Comment by nwhitmont** [comment]
For more information on localization in Bot Framework Node SDK, check out this guide: https://docs.botframework.com/en-us/node/builder/chat/localization/

**Comment by duglah** [comment]
@michaelvol and @ajaxav i found a solution for the problem:
You need the [session](https://docs.botframework.com/en-us/node/builder/chat-reference/classes/_botbuilder_d_.session.html) object for localized strings, as @nwhitmont mentioned. But for example, when you want to send a proactive message, you don't have a session. All you need is the [address](https://docs.botframework.com/en-us/node/builder/chat-reference/interfaces/_botbuilder_d_.iaddress.html) of the user and the [loadSession](https://docs.botframework.com/en-us/node/builder/chat-reference/classes/_botbuilder_d_.universalbot.html#loadsession) function:

```javascript
// req.body.address contains the address, the server saved before for this user
bot.loadSession(req.body.address, (err, session) => {
	if(err) {
		// handle error
		return;
	}
	session.send("some_localized_key");
});
```

Hope this helps.
