### ISSUE TITLE
Skype connector passing duplicated user name

### ISSUE THREAD

**Issue by srozga** [Microsoft/BotBuilder#2222]
The activities coming from the Skype bot connector include duplicate names. In the Activity, the From ChannelAccount has an id and the user name is duplicated. For example, my skype name is szymon.rozga and the field has the value "szymon.rozga szymon.rozga".

**Comment by konstlut** [comment]
@srozga We will need additional context, such as conversation id and bot id. Also I would kindly appreciate a fresh reproduction of this issue.

**Comment by konstlut** [comment]
@srozga  I am closing thing item as non-actionable from our side. Please reopen if you see this reproduced and provide bot id/conversation id. Thank you!
