### ISSUE TITLE
Bot response really slow

### ISSUE THREAD

**Issue by GhostAtom** [Microsoft/BotBuilder#2223]
Hi, I'm experiencing huge latency to get bot responses. There is a current outage or issues with LUIS or Azure bot connector?
Thanks

**Comment by willportnoy** [comment]
Could you be more specific about "bot responses"?  Is there a particular channel you're seeing something slow?  You might consider enabling telemetry for your application e.g. http://aihelpwebsite.com/Blog/EntryId/11/Using-Application-Insights-With-Microsoft-Bot-Framework

**Comment by areckkimo** [comment]
I have the same issue.
My bot deploys on Azure.
I use node.js develop the bot
How do add application insights to bot?

**Comment by PrasadGautham** [comment]
@areckkimo  even after deploying on azure website, its still slow huh??

**Comment by GhostAtom** [comment]
I fixed my issue by re-deploying the app.
Thanks for the telemetry tips.
