### ISSUE TITLE
UserData sharing across channels

### ISSUE THREAD

**Issue by srozga** [Microsoft/BotBuilder#2226]
It seems that IBotData.UserData documentation is saying that the UserData can be reused across different conversations/channels for a user. This is great but how does this work? Presumably all channels have a different user id, so how can I specify the unique id that this keys off?

![image](https://cloud.githubusercontent.com/assets/1940385/22793207/29b89940-eebd-11e6-849c-503ae8d8d57e.png)

**Comment by willportnoy** [comment]
Because user IDs vary by channel, I don't think the user data bag will be shared in practice across channels, so it seems likely that is a documentation bug.

https://docs.botframework.com/en-us/bot-framework-guide-id/

**Comment by srozga** [comment]
Ok. That's unfortunate. Obviously as you may imagine one of the things we would like to be able to do is have one user data store across channels, exactly as the documentation states. We would integrate with an external oauth to get a unique identifier which we would ideally use. Any ways in which you guys are looking to support such a scenario?

**Comment by willportnoy** [comment]
The Bot State Service is pretty trivial, once you have a "linked account" or unique identity for a user across channels.  I don't know of plans for an account linking service, but you can use any number of storage solutions to store a data bag given the user's unique identity.

**Comment by srozga** [comment]
yep, no problem there. we currently utilize doc db for this. figured if you guys did that work, we'd use your abstractions. but seems we might keep ours around. thanks.
