### ISSUE TITLE
POST Refresh access token failed with status code: 400

### ISSUE THREAD

**Issue by bsurtz** [Microsoft/BotBuilder#2227]
I get this message when I try to call my Bot from the bot emulator....  I have tried with with a blank MicrosoftAppID and MicrosoftAppPassword and with one I made up.  Neither worked.

**Comment by bsurtz** [comment]
BTW with a blank MicrosoftAppID and MicrosoftAppPassword.  I get this.

Error: The bot's MSA appId or passsword is incorrect. 
Click here to edit your bot's MSA info

**Comment by eanders-MS** [comment]
Hi @bsurtz Can you double-check to be certain you cleared the MSA credentials from both sides of the connection (bot and emulator)?

We usually recommend taking a look at this auth debugging guide as well: https://docs.botframework.com/en-us/support/troubleshooting-bot-framework-authentication/

**Comment by bsurtz** [comment]
Thanks, I got it working. I needed to add a real app ID and password. It would not work with blanks or fake ones.
