### ISSUE TITLE
LUIS does not recognize builtin.datetime.date for some timezones

### ISSUE THREAD

**Issue by gakarnik** [Microsoft/BotBuilder#2228]
My LUIS app has a builtin.datetime.date entity added to it. For this URl:

https://westus.api.cognitive.microsoft.com/luis/v2.0/apps/7e388f8a-3286-4e6a-91d5-b7fa3552ce82?subscription-key=61081fa49f244cdda471a447618a79b5&q=cancel%20time%20off%20for%20today&timezoneOffset=5.75&verbose=true

It does not recognize today as an entity. I have the same issue with few other timezoneOffset values too, where it does not recognize the entity.

**Comment by cahann** [comment]
We are working on an enhanced version of datetime pre-built entity that should be released next month

**Comment by gakarnik** [comment]
Thanks for the update.

**Comment by gakarnik** [comment]
@cahann Can you please confirm if the timezone issue has been resolved in BotBuilder 3.8.1?

**Comment by stevengum97** [comment]
Hi @gakarnik, have you tried using the new datetimeV2? Also, the timezoneOffset in your link isn't valid, try using 575 instead of 5.75 and let us know if it is working for you.

**Comment by gakarnik** [comment]
I am using the old datetime entity. You're right, when I changed the timeZone to 575, it worked. Thanks a lot!
