### ISSUE TITLE
[LUIS] ILuisModel difficult to inherit from

### ISSUE THREAD

**Issue by cglong** [Microsoft/BotBuilder#2230]
We're attempting to upgrade `Microsoft.Bot.Builder` from `3.2.1` to `3.5.1` and we've started getting build errors. Our custom implementation of `ILuisModel` is missing two new properties: `ApiVersion` and `UriBase`.

`ApiVersion` is easy to add; `UriBase` however requires referencing the framework source to reimplement:

```csharp
public LuisApiVersion ApiVersion => LuisApiVersion.V2;
public Uri UriBase => LuisModelAttribute.LuisEndpoints[ApiVersion];
```

I'm wondering if there'd be an easier way to expose the `LuisEndpoints` values. Right now, I'm thinking we could use an `Attribute` (perhaps the built-in `DescriptionAttribute`) on the `LuisApiVersion` enum values. We could also move the logic for generating the `UriBase` up to the `LuisService` layer, but that decreases flexibility.

Let me know your thoughts! I'd be happy to implement this change 😄

**Comment by willportnoy** [comment]
@msft-shahins thoughts?

**Comment by nwhitmont** [comment]
@cglong Are you still experiencing the issue after upgrading to [BotBuilder 3.8.1](https://www.nuget.org/packages/Microsoft.Bot.Builder/)?

**Comment by cglong** [comment]
Thanks for following up @nwhitmont! I just tried and it's actually become _more_ difficult 😞

1. 3.8.1 now has a new interface member, `ILuisModel.ModifyRequest`, [whose implementation](https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Microsoft.Bot.Builder/Luis/LuisModel.cs#L198-L214) looks pretty domain knowledge-heavy. We'd have to copy-and-paste it verbatim into our class.
2. The computation of `ILuisModel.UriBase` has been moved [to the `LuisModelAttribute` constructor](https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Microsoft.Bot.Builder/Luis/LuisModel.cs#L171), which is inaccessible to our class. Again, it looks like we'd have to copy-and-paste it into our implementation.

Neither of these are blockers, but copying the code into our solution isn't futureproof against new releases (in particular if the LUIS endpoint ever changes). I'm hoping we can come up with a solution that abstracts out both of these 😄

**Comment by cglong** [comment]
Hi @JasonSowers, why was this closed? It was still an issue as of 3.8.1; has it been fixed in a subsequent release?

**Comment by JasonSowers** [comment]
@cglong I apologize, I think I inadvertently closed this issue. I spoke with Will, he is going to talk it through with Shahin and we will go from there.

**Comment by cglong** [comment]
After working with @willportnoy, we were able to come up with a refactor that meets both parties' needs! Thanks for all your help 😄
