### ISSUE TITLE
Bot fails to continue conversation after some time

### ISSUE THREAD

**Issue by tylerl0706** [Microsoft/BotBuilder#2231]
I started a conversation with my bot a couple days ago on Microsoft Teams. Today, I tried to continue the conversation and it wasn't responding. I checked the logs and it showed:

```
Error: Request to 'https://smba.trafficmanager.net/v3/conversations/19%3Ac256c7b0-e94d-49c4-8585-0c7f3020bd37_94d53a41-1270-4300-a269-df272b6bee9e%40unq.gbl.spaces/activities/1486702065315' failed: [404] Not Found
    at Request._callback (D:\home\site\wwwroot\node_modules\botbuilder\lib\bots\ChatConnector.js:410:46)
    at Request.self.callback (D:\home\site\wwwroot\node_modules\botbuilder\node_modules\request\request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (D:\home\site\wwwroot\node_modules\botbuilder\node_modules\request\request.js:1048:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (D:\home\site\wwwroot\node_modules\botbuilder\node_modules\request\request.js:969:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
```

If you couldn't tell from the logs, I am using the Node.js version.

I tried a conversation from Web Chat and it responds without issue.

![image](https://cloud.githubusercontent.com/assets/2644648/22814663/3809dc28-ef0a-11e6-8c54-c30019825ac1.png)

Any thoughts?

**Comment by tylerl0706** [comment]
Has anyone gotten the chance to look at this? I've been waiting to demo something to my team at work that uses Teams but I can't demo it if the Bot Framework isn't working with Teams.

**Comment by tylerl0706** [comment]
Just to add, I've disabled and re-enabled and deleted and re-created the channel and no luck :(

**Comment by siso** [comment]
+1

Having the same issue on one of our bots (they all run the same Bot SDK version):

![image](https://cloud.githubusercontent.com/assets/1050043/23403113/8e2b3f3e-fda6-11e6-9dac-792d594cf5fb.png)

**Comment by RichMoeMSFT** [comment]
We've been making quite a few changes the past few months, but we're in a stable state now.  Are you still seeing these issues?

**Comment by tylerl0706** [comment]
Still seeing this issue, unfortunately. Let me know if there are some steps
you'd like me to take.

**Comment by RichMoeMSFT** [comment]
@tylerl0706 Can you send me the full outgoing payload so we can take a look here?  

Here are a couple general things to check:  
1) Are you hardcoding the serviceUrl in all your bot replies?  You should always reply with the serviceUrl you receive in the message, which might not stay consistant.
2) Could it be that the thread you are replying to has been deleted?

**Comment by tylerl0706** [comment]
@RichMoeMSFT : how can I get you the full payload?

1. I am not.

2. I don't know what you mean by thread. This is just a chat within Teams.

**Comment by RichMoeMSFT** [comment]
#2 is only relevant if your talking to your bot in a team channel.  So you are using the bot in 1-1?  Can you send me the botid so I can try it here?

**Comment by tylerl0706** [comment]
Yeah. I'm using it in 1-1.

Is that the botid the bot handle or the app id?

**Comment by tylerl0706** [comment]
I ended up having to create a new bot and a new Azure App Service. It works good as new now!

I was suggested to try it locally with ngrok (both with the same bot and with a new bot) as well but creating a new app service was simple to duplicate.
