### ISSUE TITLE
How can I add the capability for a bot to interact with my users in a language other than English?

### ISSUE THREAD

**Issue by andradedearthur** [Microsoft/BotBuilder#2235]
I have created a bot using a FormFlow form that displays it's options in Portuguese (pt-BR). When I ask the user he wants to confirm the information he provided, even though the emulator is sending the correct locale (pt-BR) if the user says "Sim" (Yes, in Portuguese) the bot displays "'sim' is not a option".

I would like to know how to change this behavior. I don't need do display information in different languages, I just need the bot to accept interactions based on the user locale. I noticed these files in the framework source code : https://github.com/Microsoft/BotBuilder/tree/master/CSharp/Library/Microsoft.Bot.Builder/Resource

How does the Framework use these files? If needed I could localize a file to Resources.pt.resx, but them do I need to register this file elsewhere? I could submit the localized file if it's something that would help.

**Comment by msft-shahins** [comment]
Here is documentation describing how localization works for botbuilder: https://docs.botframework.com/en-us/csharp/builder/sdkreference/forms.html#localizingSection
