### ISSUE TITLE
Markdown in messages sent to Facebook Messenger channel ignored

### ISSUE THREAD

**Issue by jakobpn** [Microsoft/BotBuilder#224]
I looks to me like even simple markdown like *bold* is ignored by the Facebook Messenger channel.

**Comment by tomlm** [comment]
That’s correct, facebook does not support markdown.  We render as text

**Comment by jakobpn** [comment]
It would be great if you could remove the markdown then.

**Comment by tomlm** [comment]
We actually do.

The rendering is a text rendering of the markdown.  For example:
This is
one line
of text

becomes:
                This is one line of text.

-Tom

**Comment by jakobpn** [comment]
But *A1* is still *A1* and not A1.

**Comment by tomlm** [comment]
yes, that is by design.  

The intent of the markdown is to express emphasis on that bit of text.  It is pretty normal for people to express emphasis for text by putting stars on either side.

**Comment by jakobpn** [comment]
OK. Got it.
