### ISSUE TITLE
[Facebook Messenger] Channel errors are not delivered to the bot

### ISSUE THREAD

**Issue by michaelvol** [Microsoft/BotBuilder#2240]
Working with messenger channel.
session.send(msg) didnt throw any error but the message never got to the user.

Under dev.botframework.com I can see that the msg was not delivered:
```
{"error":{"message":"(#200) This person isn't available right now. ","type":"OAuthException","code":200,"error_subcode":1545041}}
```
It's important to get these errors in the bot as one might want to react to that (i.e. flag the user, not send other msgs, reset the state, etc).

Thanks.

**Comment by danmarshall** [comment]
Hi @michaelvol have you tried using the [.on](https://docs.botframework.com/en-us/node/builder/chat-reference/classes/_botbuilder_d_.session.html#on) or [.error](https://docs.botframework.com/en-us/node/builder/chat-reference/classes/_botbuilder_d_.session.html#error) methods? It's not the same paradigm as try/throw/catch.

**Comment by michaelvol** [comment]
Thanks @danmarshall 
No, haven't tried it yet. Could you please point to a documentation page or an example?
Should I apply these on bot or session objects?
Thanks.

**Comment by danmarshall** [comment]
https://github.com/Microsoft/BotBuilder-Samples/blob/master/Node/core-MultiDialogs/README.md#handling-dialog-errors

**Comment by michaelvol** [comment]
I tried using session.on('error') as you suggested but I this error (person isn't available) is not caught on my side although I see it in dev.botframework.com

**Comment by Stevenic** [comment]
@michaelvol you actually want to do `bot.on('error')` and not the `session` one.

**Comment by danmarshall** [comment]
Thanks @Stevenic. @michaelvol - for reference, here is the link: https://docs.botframework.com/en-us/node/builder/chat-reference/classes/_botbuilder_d_.universalbot.html#on

**Comment by Stevenic** [comment]
We're actually adding a specific check for this so that we can throw a more useful error message.

**Comment by michaelvol** [comment]
Thanks. Tried that out with:
bot.on('error', (err) => {....}) and bot.send(....).
But it doesn't work.

Could it be this issue...?
Looks like the errorLogger is called with err=null and so my handler isn't called. 
The 403/Forbidden continues with err=null.

Also - I didnt see that the error details that are presented under dev.botframework.com are returned on this request. Could be useful to know why the channel has rejected the msg.

Thanks.

**Comment by Stevenic** [comment]
I'll have to dig into this one a bit more

**Comment by michaelvol** [comment]
Thanks!
While on this topic, 
Could it be that a message that wasn't delivered (because the deleted the conversation), is somehow queued on the SaaS, and will later (even after two weeks), be delivered to the user, once he gets back to chatting with the bot? 
Do you have any queuing mechanisms on the SaaS?
Thanks.

**Comment by nwhitmont** [comment]
@Stevenic any updates on listening for errors thrown by Facebook Messenger channel?

**Comment by nwhitmont** [comment]
@michaelvol We have just released a bunch of improvements to Bot Framework at //Build last week.  Including improved channel connector, updates to .NET and Node SDKs, and additional channel support.  [More info in this blog post.]()

Are you still experiencing the issue when using botbuilder@3.8.x?

**Comment by nwhitmont** [comment]
reopen if you're still experiencing the issue.
