### ISSUE TITLE
[MS Teams Android] CardAction attached to HeroCard Carousel is not working in Teams Android App

### ISSUE THREAD

**Issue by NCZ-10** [Microsoft/BotBuilder#2243]
Emulator and Teams Desktop App working fine. When using the android app the button is not clickable ("no imBack action")

`foreach (Models.Meetingtimesuggestion suggestion in graphRespond.MeetingTimeSuggestions)
                {
                    
                    HeroCard meetingSuggesstionCard = new HeroCard()
                    {
                        Title = $"Meetingvorschläge",
                        Images = cardImages,
                        Text = $"Suggestion",
                        Buttons = new List<CardAction>
                        {
                            new CardAction
                                {
                                Value = $"buchen,{i}",
                                Type = "imBack",
                                Title = "Buchen"
                                }
                        }

                    };

                    i++;

                    Attachment attachement = meetingSuggesstionCard.ToAttachment();
                    postGraphRespond.Attachments.Add(attachement);
}`

**Comment by NCZ-10** [comment]
I checked the Bot with iOS App and the buttton works proper. Seems there is a bug in the Android App.

**Comment by RichMoeMSFT** [comment]
@NCZ-10 I'm unable to duplicate the issue.  Still happening?

**Comment by NCZ-10** [comment]
@RichMoeMSFT Yes, when using the herocards inside a carousel the button is not clickable. Newest Android App Version (1416/1.0.0.2017032303)

**Comment by RichMoeMSFT** [comment]
@NCZ-10 I'm running same version and my sample app works fine...  You can try my bot to see if it's just code differences:  c9e8c047-2a74-40a2-b28a-b162d5f5327c    Type: carousel1 or carouselx

**Comment by nwhitmont** [comment]
@NCZ-10 are you still experiencing the issue?

**Comment by NCZ-10** [comment]
Yes! iOS and Win10 app working fine. Only Android is not clickable.

**Comment by JasonSowers** [comment]
please reopen this if needed
