### ISSUE TITLE
Getting message while login ...There was a problem synchronizing your bot to Skype

### ISSUE THREAD

**Issue by hclsoultiongroup** [Microsoft/BotBuilder#2244]
Hi ..
I have created a registered a BOT which was working fine till last week. Suddenly i started getting message " There was a problem synchronizing your bot to Skype " when i tried to add the BOT to Skype Client. Things are working perfectly fine on emulator connecting the deployed Web APP. But on both Skype Web and Desktop client BOT is not responding. Not getting any help from Application Insights.
Please help me since i need to release my BOT to customer ASAP.
My BOT Name : Analytics Chat Bot
Handle : sa_chat_bot

Thanks in Advance
~Amit R

**Comment by dandriscoll** [comment]
Hi @hclsoultiongroup, we have a temporary issue where this error appears if you create a bot without an endpoint. In most cases, you can clear the error by assigning an endpoint URL and saving your bot. Does this fix the problem for you?

**Comment by dandriscoll** [comment]
We're also experiencing a problem synchronizing to Skype from some datacenters. We're investigating.

**Comment by dandriscoll** [comment]
The synchronization process is back to normal. It will still fail if your bot is missing an endpoint, but it should succeed otherwise.

**Comment by hclsoultiongroup** [comment]
Thanks for reverting....Issue got resolved now. I just saved the BOT again with some changes in description and it works.

**Comment by sasidhar20** [comment]
Facing the same issue. "There was a problem synchronizing your bot to Skype."

When I tried to edit the config, says error in server. Web chat is also not working. Please revert for more information.

**Comment by JasonSowers** [comment]
@sasidhar20 can you please open a new issue.
