### ISSUE TITLE
Handling dynamic field with 1 option

### ISSUE THREAD

**Issue by jsiegmund** [Microsoft/BotBuilder#2248]
Disclaimer: this is not an issue, but a question.

I have managed to create a field which gets its values from a database in a dynamic way. This works, but I want to make the form a bit more intelligent then it is now. 

Let's say there are two fields in a form flow dialog: Customer and Project. Now I have an incoming message which is caught by a LUIS intent. I can extract the EntityRecommendation items and pass these to the dialog. I'd like the following to happen: 

* The database should be queried for customers. If a customer recommendation was already provided, the query should be filtered based on that text. So "Contoso Inc" should be returned when the user typed in "Contoso".
* Should the search result have only 1 value, I'd like the bot to pre-select that. Optionally it might be nice so ask something like "I found 'Contoso Inc', assume you mean that one?". 
* The database includes a relationship between customers and project, so for the next field, I want to query the Projects table for only projects that are linked to Contoso Inc. 
* And again, if only one is present; just select that one. 

Main challenges:
* The SetDefine code is called each time the form is loaded, so for each message. It doesn't make sense to go out to the database each and every time. I could do something like BotState or Redis in between, but I wonder what is best practice here.
* I haven't found a good way to auto-select a single value when only one item returns from the database.

And tips / pointers for these would be highly appreciated. Thanks!

**Comment by chrimc62** [comment]
Given the stateless nature of the SDK, we need to call SetDefine on each form load so best practice is to use a cache as you describe.

I'm not sure what you mean by "preselect".  If your field is nullable and you set it, then if FormOptions.PromptFieldsWithValues is not present the field will be skipped but show up in status and navigation.  If you do pass in PromptFieldsWithValues, then the current value will be the default one.

Your SetDefine can assign the value and if you want to skip the field you return false.  Alternatively you could define a SetNext with a delegate that determines the next step.  You could put your DB logic in the previous step to determine whether or not you move onto the singleton field.

**Comment by jsiegmund** [comment]
Thanks! By "preselect" I meant: select the one entry that was returned from the DB, paste its value into the field and advance to the next field. 

Like so: 
- 4 customers are shown
- User picks customer 1 
- DB is queried for projects, only 1 is returned
- That 1 project is set in the "Project" field
- Dialog advances to the next field, user was not bothered with the Project field. 

I'm going to try this and when I succeed I'll post the code here for future reference.

**Comment by chrimc62** [comment]
@jsiegmund were you successful at this?

**Comment by jsiegmund** [comment]
Yeah, I haven't tested this extensively yet but the following snippet seems to work: 

```
TimeRegistrationConnector timeConnector = new TimeRegistrationConnector();
recentProjects = timeConnector.GetRecentProjects(connector, customerId).ToArray();

foreach (var recentProject in recentProjects)
{
    field
        .AddDescription(recentProject.ProjectId.ToString(), recentProject.ProjectDescription)
        .AddTerms(recentProject.ProjectId.ToString(), recentProject.ProjectDescription);
}

// if there's only one option to select; select it! 
if (recentProjects.Length == 1)
{
    state.Project = recentProjects.First().ProjectId.ToString();
    return Task.FromResult(false);
}
```
