### ISSUE TITLE
Unauthorized in test Connection

### ISSUE THREAD

**Issue by vovanb** [Microsoft/BotBuilder#2249]
Using Microsoft.Bot.Sample.AnnotatedSandwichBot sample 
MicrosoftAppId = "256c26bb-d470-4429-83bd-08e9bf21d817"
Always getting Unauthorized response and There was an error sending this message to your bot: HTTP status code Unauthorized on each message
The web.config 
`
 <add key="BotId" value="SO.." />
 <add key="MicrosoftAppId" value="256c26bb-d47...9bf21d817" /> 
 <add key="MicrosoftAppPassword" value="5fJF...y0VRpV0b" />
 `

**Comment by willportnoy** [comment]
You might consider going through the steps at https://docs.botframework.com/en-us/support/troubleshooting-bot-framework-authentication/.

**Comment by vovanb** [comment]
I did all tests. I think you have issue with reading web.config in latest release . Once I assigned all attributes in code it was working.

Sincerely,
Vladimir
(Sent from my mobile)

**Comment by willportnoy** [comment]
@vovanb that's interesting - why do you think reading the settings from web.config is failing?

**Comment by vovanb** [comment]
@willportnoy simple take any of sample template (even template from nuget) and try with web.config - it is always fail.

**Comment by willportnoy** [comment]
@msft-shahins for fyi

**Comment by msft-shahins** [comment]
I couldn't repro this by creating a new bot based on the bot app template and updating the bot builder nuget to the latest version.

**Comment by willportnoy** [comment]
I'm going to close this issue for now, but feel free to open a new issue for further discussion.
