### ISSUE TITLE
[Feature Request] Show Facebook Webview

### ISSUE THREAD

**Issue by haligasd** [Microsoft/BotBuilder#2250]
https://developers.facebook.com/docs/messenger-platform/messenger-extension

Challenge is would like this embedded in a hero card.  Ideal solution is just to allow extra rendered json via ChannelData at the CardValue level.

**Comment by carlosscastro** [comment]
Hi @haligasd, thanks for reaching out! What is it you are trying to achieve? Do you still need help?

For general questions I'd suggest to reach out to StackOverflow, and use GitHub mostly for bugs.

Thanks again, and let me know if I can be of help :)

**Comment by haligasd** [comment]
so on the link above you need to be able to render buttons in facebook and pass "compact", etc to the button.  this isn't necessarily a bug but more  can we even do this

https://developers.facebook.com/docs/messenger-platform/send-api-reference/url-button

the url button works great except for the extra properties

"webview_height_ratio": "compact"

**Comment by EricDahlvang** [comment]
Closing this issue.  Messenger feature requests are tracked here: https://github.com/Microsoft/BotBuilder/issues/4360  (I've referenced this one there)
