### ISSUE TITLE
Send feedback message to Skype failed. Response 400 - Failed to decrypt pairwise Id

### ISSUE THREAD

**Issue by TzuYangLin** [Microsoft/BotBuilder#2251]
Hi.

Yesterday the bot send message back to Skype works all time but today it always response 400 and error message is 'Failed to decrypt pairwise Id'.  What does it mean?

And I note the user id from Skype is different with yesterday.

The APP's ID is "9834cd1e-a7f6-4a88-b999-38d0d8f4e189"

below is the test request;

`apiURL=https://smba.trafficmanager.net/apis/v3/conversations/29%3A11XUHDc-fLT__rlkp7tbvDFBCs_WDI9eRAOnMqXaGjRU/activities`

`
{"text":"Sorry. I do not understand what does 'yes' means?\n\nPlease ask 'help' to find out more or visit our website by clicking ","type":"message","from":{"id":"28:9834cd1e-a7f6-4a88-b999-38d0d8f4e189","name":"Auto Rebooter"},"conversation":{"id":"29:11XUHDc-fLT__rlkp7tbvDFBCs_WDI9eRAOnMqXaGjRU"},"recipient":{"id":"29:11XUHDc-fLT__rlkp7tbvDFBCs_WDI9eRAOnMqXaGjRU","name":"Daniel Lin"},"replyToId":"1487041189972"}
`

Thanks :)

**Comment by TzuYangLin** [comment]
It's works today...The code does no any change.

**Comment by konstlut** [comment]
We were able to identify and fix the problem which originated from the case when the same bot msa app id was reused by different bots. Thank you for reporting!

**Comment by ZOXEXIVO** [comment]
Open issue please. Issue appeared today for Skype
