### ISSUE TITLE
Documentation discrepancy between the emulator->bot authentication and node-sdk's implementation

### ISSUE THREAD

**Issue by mankityau** [Microsoft/BotBuilder#2252]
In the documentation ([https://docs.botframework.com/en-us/restapi/authentication/#emulator---bot-steps-1-and-2-download-the-msa-openid-metadata-document](url)) it says the OpenId metadata is "https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration"

But in the node-sdk v3.6, there is this line 
`emulatorOpenIdMetadata: 'https://login.microsoftonline.com/botframework.com/v2.0/.well-known/openid-configuration'` under ChatConnector.js.

I believe the documentation is incorrect. Can someone please confirm on this please? Thanks.

**Comment by dandriscoll** [comment]
Hi @mankityau, thank you for spotting this, the guide is out of date. This document shows the most recent auth parameters: https://docs.botframework.com/en-us/restapi/authentication/#changes

**Comment by dandriscoll** [comment]
I've updated the docs. Please at-mention or open a new issue if you'd like to discuss further.
