### ISSUE TITLE
Sample for multiple bots talking at the same end point using C#

### ISSUE THREAD

**Issue by sowsan** [Microsoft/BotBuilder#2253]
Hello Team - 

Are there any eg: on using same end point to talk to multiple end points ? There is one node.js eg: here

https://www.microsoft.com/developerblog/real-life-code/2017/01/10/Multiple-Bots-Service.html

Have tried using both ASP.NET core and traditional MVC model which is coming with the VS template by creating a new implementation of ICredentialProvider by overriding it from Microsoft.Bot.Connector. Its working for one bot and always failing for others while refreshing the JWT token. 

Thanks for your help !

Regards - 
S

**Comment by sowsan** [comment]
issue ##2163 linked to the same..

**Comment by carlosscastro** [comment]
Hi @sowsan, apologizes for the delay in an answer. Are you still needing an answer to this questions?

for the future, I'd suggest using StackOverflow for questions and discussions, and use GitHub only for bugs. 

Thanks!
