### ISSUE TITLE
How can I use bot framework to add participant in a Skype conversation?

### ISSUE THREAD

**Issue by ooclleeke** [Microsoft/BotBuilder#2254]
I have a use case to add a Skype account to the conversation, when the bot cannot handle customer request.

Scenario 1:
Step 1. Customer(Skype) send a request to bot.
Step 2. Bot cannot handle it. 
Step 3. Add an internal user(Skype) to the conversation and promote the 1:1 conversation to group conversation.

But I cannot find any function to add a participant.

I try to use the "CreateConversation" method to create a new group conversation. Let the customer chat with internal user.
Sample code: 
ConversationParameters cpMessage = new ConversationParameters(message.Recipient, true, participants, "Quarter End Discussion");
var conversationId = await connector.Conversations.CreateConversationAsync(cpMessage);

Scenario 2:
Step 1. Customer(Skype) send a request to bot.
Step 2. Bot cannot handle it. 
Step 3. Create a new group conversation. (Participants: customer, bot, internal user)

I found that the "CreateConveration" method cannot generate a new conversationId.

**Comment by rajivupreti** [comment]
I am also trying to implement similar use case. 
It seems possible by creating a desktop Skype application which monitors the conversation between user and bot and do the necessary action based on the chat contents. 
But if it would be better if we could achieve from server.

**Comment by nickcordrey** [comment]
Skype doesn't support creation of conversations by the bot. The only solution I can suggest is that you send a card explaining that the bot needs to hand off to a customer support agent and with a skype: button action for the _customer_ to create the new conversation using Skype URIs (https://msdn.microsoft.com/en-us/library/office/dn745882.aspx) something like:

skype:28:yourbotid;yourinternaluserskypeid?chat&topic=topicString

**Comment by SujithOnWeb** [comment]
https://docs.botframework.com/en-us/node/builder/chat/UniversalBot/#proactive-messaging

**Comment by MBoui** [comment]
Someone find a workaround to initiate a new chat (new topic) with a bot?
Skype uri, look not working on MacOs and IOS

My goal is create a new conversation group with 2 participants (the user and the bot) by clicking invite the user to click in one link.

**Comment by selvarsmk** [comment]
Anyone found any workaround for this.  I have exactly similar requirement.
