### ISSUE TITLE
Can we send mail from BOT to some mail id?

### ISSUE THREAD

**Issue by singhsurya** [Microsoft/BotBuilder#2257]
Hi,

We want to send mail from BOT to some email id (say abc@gmail.com). Is it possible with BOT? If yes, please let us know the way. Thanks

**Comment by msft-shahins** [comment]
you can either use email channel to have your bot receiving emails and replying to emails or use one of the programmatic email delivery services, e.g. [sendgrid](https://sendgrid.com) if you only want to send email to an email address from your bot.
