### ISSUE TITLE
LUIS recognizes 'a' as a number

### ISSUE THREAD

**Issue by camer314** [Microsoft/BotBuilder#2262]
As per title why does LUIS return 'a' as a builtin.number?

"originalQuery": "it's a 2015 model"

  "entities": {
    "builtin.number": [
      {
        "resolution": {
          "value": "1"
        },
        "name": "builtin.number",
        "value": "a",
        "score": -1.0,
        "startIndex": 5,
        "endIndex": 5
      },
      {
        "resolution": {
          "value": "2015"
        },
        "name": "builtin.number",
        "value": "2015",
        "score": -1.0,
        "startIndex": 7,
        "endIndex": 10
      }
    ]

**Comment by cahann** [comment]
this is basically to cover the scenario of "I want to order a burger" where a here refers to one burger

**Comment by siddiq-rehman** [comment]
Hi, 

I am facing the same issue, in the scenario for a banking chatbot, for quiries like "Transfer an amount of 10 dollars", here its refering "an" to a number.

**Comment by DL-LiveTiles** [comment]
Same issue with 'a' being linked to a location entity.

**Comment by cahann** [comment]
A fix will be deployed in couple of weeks to handle this.
