### ISSUE TITLE
[Feature Request] Anyway to get custom objects/string from Prompts.choice response instead of text?

### ISSUE THREAD

**Issue by AbhishekDutt** [Microsoft/BotBuilder#2264]
Yo, currently response of Prompts.choice is always the button text that the user clicks.

However it would be very useful if along with the button text we can also get some custom metadata which can be used to identify the button's context.

This is especially useful for non-facebook channels where the quick reply buttons do not go away and user can scroll back and click on an old button. If the old button and a later button both have exact same text, it is difficult (impossible??) to identify which button user intended.

FB allows this with "payload" field: Refer [FB Quick Reply](https://developers.facebook.com/docs/messenger-platform/send-api-reference/quick-replies)

Related #1625

Thanks

**Comment by simonwjackson** [comment]
It would also be great to send a "metadata only" message

**Comment by Stevenic** [comment]
So it sounds like your mixing two things together here... If you're call `Prompts.choice()` it will use quick replies as you suggest just so that it avoids the problem of old buttons on cards. If you're calling Prompts.choice() in a waterfall what you can do is save your context data in `session.dialogData` which you can then look up after the user picks their choice.

With that said... I have been thinking about creating a much improved Prompts.choice() so this is good feedback for that work.

**Comment by nwhitmont** [comment]
@AbhishekDutt are you using C# or Node SDK for BotBuilder?

**Comment by nwhitmont** [comment]
@AbhishekDutt - Per the documentation on [Prompts.choice](https://docs.botframework.com/en-us/node/builder/chat/prompts/#promptschoice) you can use an Object that stores any information or metadata that you like.

>When an Object is passed in Objects keys will be used to determine the choices.
 In the code following example, the keys are "west", "east", and "central",  but you can configure your object any way you want and refer to that object at any point in your dialog.

```javascript
var salesData = {
    "west": {
        units: 200,
        total: "$6,000"
    },
    "central": {
        units: 100,
        total: "$3,000"
    },
    "east": {
        units: 300,
        total: "$9,000"
    }
};

bot.dialog('/', [
    function (session) {
        builder.Prompts.choice(session, "Which region would you like sales for?", salesData); 
    },
    function (session, results) {
        if (results.response) {
            var region = salesData[results.response.entity];
            session.send("We sold %(units)d units for a total of %(total)s.", region); 
        } else {
            session.send("ok");
        }
    }
]);
```

For example, you could modify this example and store additional metadata or context related information like this:
```javascript
var salesData = {
    "west": {
        units: 200,
        total: "$6,000",
        context: "Sales data",
        name: "West region sales data 2017 Q1",
        metadata: "Developer defined additional metadata"
    },
    "central": {
        units: 100,
        total: "$3,000",
        context: "Sales data",
        name: "Central region sales data 2017 Q1",
        metadata: "foo bar baz"
    },
    "east": {
        units: 300,
        total: "$9,000",
        context: "Sales data",
        name: "East region sales data 2017 Q1",
        metadata: "1 2 3 foo bar, something"
    }
};
``

**Comment by nwhitmont** [comment]
@simonwjackson Can you provide a code example & use case?

**Comment by sgellock** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botbuilder-channels/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
