### ISSUE TITLE
Unauthorized 401 Error 

### ISSUE THREAD

**Issue by bimaldave** [Microsoft/BotBuilder#2266]
Hi All,

My bot was working perfectly this morning and all of a sudden I started to get this error:

There was an error sending this message to your bot: HTTP status code Unauthorized

I've checked all of the application settings and they have not changed so confused why this is happening all of a sudden? It is SSL encrypted too.

If I run through the emulator it works fine using ngrok. So it looks like the issue is coming from the botframework host itself when it tries to communicate to my IIS server. In the IIS log I see this:

2017-02-15 14:02:39 192.168.1.99 POST /mybot/api/messages - 443 - 40.127.183.64 BF-Telegram+(Microsoft-BotFramework/3.1++https://botframework.com/ua) - 401 0 0 369

Any ideas please?

**Comment by msft-shahins** [comment]
@bimaldave can you share Microsoft App Id for your bot?

**Comment by bimaldave** [comment]
Hi its: d0e03a8e-84cd-4b47-b097-b60aec2e84a6

**Comment by msft-shahins** [comment]
Looking at traces seems that your bot is returning 401 when connector services call into it. Have you changed Microsoft app password for your bot recently? You can follow this troubleshooting guide to diagnose your authentication issues: https://docs.botframework.com/en-us/support/troubleshooting-bot-framework-authentication/

**Comment by bimaldave** [comment]
Hi no I haven't changed it. Also using the same app ID and password via the emulator is working fine so pretty sure that's not the problem. I've also tried creating a second bot app and app id as a test and that throws the same error so I'm wondering how I can find out what is causing this authorisation error. What exactly happens when the call is made to the end point.

**Comment by bimaldave** [comment]
One other thing - if I remove the app ID and password from the web.config and then just hit the test button I get a success message which is odd. Obviously the bot doesn't respond to requests but something funky is happening. Any ideas I'm stumped?!

**Comment by msft-shahins** [comment]
@bimaldave what version of bot builder are you using for your bot? When you remove the MicrosoftAppId and MicrosoftAppPassword, it means that you are disabling BotAuthentication for your bot and the incoming request will succeed. That is the reason that you are seeing success in the dev portal.

**Comment by bimaldave** [comment]
I'm using version 3.2. If there was a problem with the app password wouldn't the emulator also fail? That's working.

**Comment by msft-shahins** [comment]
It shouldn't be related to app password. App password is used to generate tokens for outbound request from bot.

**Comment by dandriscoll** [comment]
Hi @bimaldave, we've taken a look and there's nothing obviously wrong from our side. Here are some potential problems that could cause your bot to reject the token sent by our service:

1) Your web.config file contains an App ID that does not match the one you posted. You said you checked this so it's probably not the issue.
2) Your server's time is incorrect. Our tokens have 20 minutes of validity (5 minutes before the token was issued and 15 minutes after.) Is it possible your server time is different?
3) Your bot encountered a problem retrieving our list of signing keys. Check to make sure you can access these URLs:
https://api.aps.skype.com/v1/keys
https://login.botframework.com/v1/.well-known/keys

Can you check on the server time and access to the above URLs?

**Comment by bimaldave** [comment]
Hi @dandriscoll,

Thanks very much for your tips. After checking the server time I could see it was about 5 mins behind - after correcting this it seems to be back in action. Many thanks for your and @msft-shahins help, much appreciated!

**Comment by roman-polunin-medamerica** [comment]
Omg guys can you please put this last bullet #3 about well-known URLs somewhere in the official help and into the BotFramework? I burned multiple hours trying to figure out what's going on, now discovered this post and this seems to be the case.

**Comment by pksorensen** [comment]
Does  Microsoft.Bot.Connector ConnectorClient automatically renew tokens?

My app started getting Operation returned an invalid status code 'Unauthorized'. 

I did not change password or anything. (the client is registered as a singleton in my app so maybe something token renewable failing?) Does it use tokens or the password credenticals raw?

**Comment by maixuanhan** [comment]
Auto gen JS script uses `MicrosoftAppId`, while autogen TS script uses `MicrosoftAppID`. That caused me an hour after changing from JS to TS. Because the local testing doesn't need those env var, we'll get the painful during deploying.

**Comment by ByIvo** [comment]
Thank you @maixuanhan, this was my problem as well.
