### ISSUE TITLE
Audio playback in Skype call from local resources

### ISSUE THREAD

**Issue by angsm** [Microsoft/BotBuilder#2267]
Hi, 
I saw that prompt was able to handle playback of audio files like wave / wma, but only in http form which needs to be hosted on a site where the extension is exposed. 

Would it be possible to playback a local file, maybe on an azure server? Or is there some other method to playback audio through the bot?

Thank you.

**Comment by KrishnanA** [comment]
You can put the file in Azure blob stores and get a HTTPS URL and use that.
