### ISSUE TITLE
Object Reference exception when validation fails on LUIS entity.

### ISSUE THREAD

**Issue by ankitbko** [Microsoft/BotBuilder#227]
I have a simple LUIS Intent which spawns up a child dialog to fill a form. The form is very simple with just one string field. I have validation setup that does a regex match before assigning. Code snippets are below.
### Problem
If LUIS does not detect an entity fill up the EmployeeID field, the form correctly prompts user input and validation happens as expected. However if LUIS does detect an entity and the validation fails, the framework throws an Object reference not set to an instance of an object exception.
Eg: If LUIS detects some garbage such as m142151231 as entity, the regex validation will fail and ValidationResult will be set to false with feedback. The bot should then prompt the user to enter correct ID along with feedback. Instead of this, the FormComplete delegate is called and Object reference exception is thrown.

```CSharp
[Serializable]
public class Employee
 {
     [Describe("Employee ID")]
     [Prompt("Please enter your ID: ")]
     public string EmployeeId
 }
```
```CSharp
[LuisIntent("DoSomething")]
public async Task DoSomething(IDialogContext context, LuisResult result)
{
     var entities = new List<EntityRecommendation>(result.Entities);
     var unlockForm = new FormDialog<Employee>(new Employee(), BuildForm, FormOptions.PromptInStart, entities);
     context.Call(unlockForm, FormComplete);
}

private async Task FormComplete(IDialogContext context, IAwaitable<Employee> result)
{
    try
    {
        var emp = await result;                            //This is where exception happens

        await context.PostAsync($"Success for {emp.EmployeeId}");

        context.Wait(MessageReceived);
    }
    catch (FormCanceledException<Employee> e)
    {
        string reply;
        if (e.InnerException == null)
        {
            reply = $"You quit --maybe you can finish next time!";
        }
        else
        {
            reply = "Sorry, I've had a short circuit.  Please try again.";
        }
        await context.PostAsync(reply);
    }
}

private static IForm<Employee> BuildForm()
{
    var builder = new FormBuilder<Employee>();
    return builder
        .Field(nameof(Employee.EmployeeId),
            validate: async (state, response) =>
            {
                 ValidateResult valresult = new ValidateResult() { IsValid = true };
                 var mid = (response as string).Trim();
                 if (!Regex.IsMatch(mid, "\\bm?[0-9]{7,7}\\b"))
                 {
                     valresult.IsValid = false;
                     valresult.Feedback = "Employee ID is invalid";
                 }
                 return valresult;
            })
        .AddRemainingFields()
        .Build();
}
```

On further digging, the exception seems to occur at Fiber.cs `IFiberLoop.PollAsync()` `var next = await leaf.PollAsync(this);`

**Comment by chrimc62** [comment]
Are you running the latest version of the framework?  I was not able to repro this issue--if your validation fails no property should be set.

 In any case, we are likely to do a new release today and one of the changes allows a validation function to return the value that should be set.  You should be able to use this to set to null if that is appropriate.

**Comment by ankitbko** [comment]
I am using version 1.1.0.0 of bot builder. I'll wait for the new release. Thanks for the help.

**Comment by ankitbko** [comment]
@chrimc62 This issue is not resolved in 1.2.0.1 version. To reproduce the issue, I have created a sample project https://github.com/ankitbko/Bot-Issue227. 


**Context**
This is a very simple application that uses Cortana pre-built model to recognize send_text intent (builtin.intent.communication.send_text). The intent starts up a FormDialogue which contains one field called `Name`. If `Name` is present in the entity it proceeds otherwise it will prompt the user.
For demonstration I have setup validation on field which checks if the name starts with `b`. If it does not, it fails and returns a feedback.


**Flow**
- Send input as "Text Bob". This flow will work till completion. LUIS will detect entity as Bob which passes validation.
- Send input as "Text". This will prompt user to enter the name. If you enter "Bob", it would proceed to ResumeAfter Event. If you enter "Paul", it would show feedback `Invalid Name` and prompt again.

**Issue**
-  Send input as "Text Paul". LUIS will detect entity as Paul which fails the validation. Ideally at this stage, framework should show feedback and prompt for name again but instead the framework fires the ResumeAfter Event. Here on `var emp = await result;` you will see exception being raised (`Object reference not set to an instance of an object.`).

Also since framework 1.2.0.1, emulator does not receive the response but gets 500 Internal Server Error. This was not happening on version 1.1.

Am I doing something wrong in here?

```CSharp
private static IForm<Employee> BuildForm()
{
    var builder = new FormBuilder<Employee>();
    return builder
        .Field(nameof(Employee.Name),
            validate: async (state, response) =>
            {
                ValidateResult valresult = new ValidateResult() { IsValid = true, Value = response };
                var mid = (response as string).Trim();
                if(!mid.StartsWith("b"))
                {
                    valresult.IsValid = false;
                    valresult.Feedback = "Invalid Name";
                }
                return valresult;
            })
        .AddRemainingFields()
        .Build();
}

[LuisIntent("")]
public async Task None(IDialogContext context, LuisResult result)
{
    await context.PostAsync("I'm sorry. I didn't understand you.");
    context.Wait(MessageReceived);
}

//[LuisIntent("UnlockComputer")]
[LuisIntent("builtin.intent.communication.send_text")]
public async Task TextEmployee(IDialogContext context, LuisResult result)
{
    var entities = new List<EntityRecommendation>(result.Entities);
    EntityRecommendation entityName;
    result.TryFindEntity("builtin.communication.contact_name", out entityName);
    if(entityName != null)
        entities.Add(new EntityRecommendation(type: "Name") { Entity = entityName.Entity });
    var unlockForm = new FormDialog<Employee>(new Employee(), BuildForm, FormOptions.PromptInStart, entities);
    context.Call(unlockForm, TextEmployeeComplete);
}

private async Task TextEmployeeComplete(IDialogContext context, IAwaitable<Employee> result)
{
    try
    {
        var emp = await result;

        await context.PostAsync($"Success for {emp.Name}");

        context.Wait(MessageReceived);
    }
    catch (FormCanceledException<Employee> e)
    {
        string reply;
        if (e.InnerException == null)
        {
            reply = $"You quit --maybe you can finish next time!";
        }
        else
        {
            reply = e.InnerException.Message;
        }
        await context.PostAsync(reply);
    }
}
```

**Comment by chrimc62** [comment]
I'm taking a look now.  The issue had been marked as closed so I missed that you still had an issue.  Sorry about that!

**Comment by chrimc62** [comment]
Thanks for the clean repro and brining this to my attention.  I've fixed the issue and it is in code review now and will be in our next release.  The issue was that when validation failed the form field was left in a responding state which it was not actually in.

**Comment by ankitbko** [comment]
Thanks @chrimc62. Much appreciated.

**Comment by cwdyang** [comment]
hi any idea when this fix will be released? thanks we kinda need it urgently :)

**Comment by chrimc62** [comment]
New nuget release 1.2.2 is out there and should fix the issue.

**Comment by ankitbko** [comment]
@chrimc62 The error is fixed but validation Feedback is not shown. I have updated my github repo to 1.2.2. Input "Text Paul" and it would do the validation but the feedback "Invalid Name" will not be shown.

**Comment by chrimc62** [comment]
I am looking into this again and will make sure it is fixed.

**Comment by chrimc62** [comment]
I have a fix in code review I will check-in tomorrow.  It will do clarification or feedback on validation before going into the form.  Thanks again for the clean repro and patience!

**Comment by ankitbko** [comment]
Thanks a lot.
