### ISSUE TITLE
[Skype Channel] Notification about group call

### ISSUE THREAD

**Issue by soloveyalex** [Microsoft/BotBuilder#2270]
Hi

I know that Bots do support voice calling in 1:1 mode only.

However, Is it possible for Bot to catch a notification that GROUP call is started\finished?

In other words, the Bot should not participate in group call but rather should record the time the call was started/finished. Is that possible?

Regards,
Al

**Comment by nwhitmont** [comment]
@soloveyalex great question. Are you using the C# or Node SDK?

**Comment by soloveyalex** [comment]
Hi, 

I'm using C# 

However, I can tell you now that Bot really CAN participate in group calls despite it is declared as unsupported feature in documentation. So, in fact it receives all necessary notifications.

As of today we do have a test bot, that takes part in our skype group meetings and greets participating people when the call is established.

**Comment by mmatkow** [comment]
Hi Al, at this time IVR calling bots can answer a group calls (receive and send audio) but the bot won't receive updates about call state nor notifications about group call participants.
