### ISSUE TITLE
Restarting bot if user waits too long before sending reply

### ISSUE THREAD

**Issue by mb19** [Microsoft/BotBuilder#2271]
I'm working on a bot in Node.js for Microsoft Teams and I would like it to restart from the beginning dialog if a user attempts to reply to it after being idle for too long, regardless of where they are in any dialog.

I'm able to successfully begin a new dialog at the welcome message endpoint I have implemented as follows, where bot is an instance of UniversalBot:

``` 
   bot.on('receive', function (event) {
        bot.isInConversation(event.address, (err, lastAccess) => {
            var now = new Date();
            if (lastAccess != null) {
                var diff = (now.getTime() - lastAccess.getTime());
                var minutes = diff / 60 / 1000;
                //if user is idle for more than 5 minutes and tries to send a message
                if (minutes > 5) {
                    bot.beginDialog(event.address, '/timeout');
                }
            }
        });
    }); 

    bot.dialog('/timeout', function(session) {
        session.send("Oops. You were idle for too long. We will start over from the beginning.");
        //redirect to initial welcome message again to start over
        session.beginDialog(welcome.endpoint);
    });
```

This will successfully restart the dialog with the bot.beginDialog call, however, the current dialog (prior to the beginDialog call) will still send a response to the user prior to restarting. 

Is it possible to end the current dialog or reset the bot completely so that any current dialog is stopped prior to the reset as soon as a user message is received? Or is there a better way I should be checking for user inactivity outside of the .on() event listener?

**Comment by willportnoy** [comment]
Sorry I don't have a direct answer - https://github.com/Microsoft/BotBuilder/issues/2010#issuecomment-271864874 has some relevant guidance.

**Comment by palmerabollo** [comment]
@mb19 you can try [`session.clearDialogStack()`](https://docs.botframework.com/en-us/node/builder/chat-reference/classes/_botbuilder_d_.session.html#cleardialogstack) or even call `reset` + `endDialog`:

```js
session.send('Oops. You were idle for too long');
session.reset();
session.endDialog();
```

**Comment by mb19** [comment]
Thank you for the responses. @willportnoy I suspected I might have to go one of the routes mentioned in your link so I will give that a look.

@palmerabollo I've tried that, but the trouble is by the time session.send() gets called, or by the time that dialog is even reached, the bot has already sent the response from the previous dialog resulting in a pretty messy output for the user. If I had a way to access the session in my bot.on() call I would be able to cancel it there, but I'm not aware of any way to cancel dialogs without having access to the session object.

**Comment by mb19** [comment]
@willportnoy @palmerabollo Again, thank you for your responses. I ended up finding an effective, if slightly weird solution to this.

By intercepting the session during the routing event, I maintain a timestamp on the sessionState and check to see if the difference between it and the current time exceeds the specified timeout duration. Then, I change the message text to the text for a triggerAction I specified on the dialog I want the bot to restart to.

I imagine it will run into issues if the sessionState, for some reason, is ever undefined or empty. I haven't seen anyone else do this sort of thing yet (and maybe that's for good reason), but so far it has been working for me.


```     bot.on('routing', (session) => {
        //Confirm the session has a message attached to it
        if (session.message) {
            var now = new Date();
            if (session.sessionState && session.sessionState.timeStamp) {
                var last = session.sessionState.timeStamp;
                var diff = (now.getTime() - last);
                var minutes = diff / 60 / 1000;
                if (minutes > config.sessionTimeout) {
                    session.message.text = 'botrestart';
                }
            }
            session.sessionState.timeStamp = now.getTime();
        }   
    });
```

**Comment by willportnoy** [comment]
seems like a nice solution @mb19 :)

**Comment by slidenerd** [comment]
@mb19  where did you add this sessionState code? inside your isInConversation handle? that you wrote earlier

**Comment by mb19** [comment]
@slidenerd I do it inside the routing event handler. In my code it looks like:

```
bot.on('routing', (session) => {
        //Code here

}
