### ISSUE TITLE
https://state.botframework.com/v3/botstate/facebook/conversations failed: [400] Bad Request

### ISSUE THREAD

**Issue by josephktcheung** [Microsoft/BotBuilder#2272]
Does anyone know why one of my user's conversation gets `https://state.botframework.com/v3/botstate/facebook/conversations failed: [400] Bad Request`? I'm using node.js SDK, thanks.

**Comment by willportnoy** [comment]
What's the size of your bot data?  The limit is about 32K if I recall correctly.

**Comment by josephktcheung** [comment]
How can I inspect the bot data?

**Comment by willportnoy** [comment]
The bot data is the data you're storing in the per-user, per-conversation, or per-user-in-conversation data bags:

https://docs.botframework.com/en-us/technical-faq/#is-there-a-limit-on-the-amount-of-data-i-can-store-using-the-state-api

**Comment by carlosscastro** [comment]
@josephktcheung are you still experiencing this issue?

**Comment by josephktcheung** [comment]
Should be fixed after cleaning the userData using REST api. Thank you for your help @willportnoy
