### ISSUE TITLE
[Feature Request] Support threads on Slack Channel

### ISSUE THREAD

**Issue by davidwengier** [Microsoft/BotBuilder#2273]
When a message is received in a thread in a slack channel, a reply using CreateReply is sent to the channel, but not to the thread. The thread_ts identifier from Slack is correctly in the ChannelData, so can be mirrored back to enable threading using a custom reply, however that means crafting the entire Slack message custom reply.

It would be nice if there was a way to augment the reply that will be sent to the client using ChannelData rather than having to provide the whole message. Alternatively, if the Slack connector could automatically reply in-thread when its applicable (ie, the presence of thread_ts in the request) that would be even better.

**Comment by willportnoy** [comment]
@craigjensen can you comment?

**Comment by craigjensen** [comment]
We'll be adding support for threads very soon.  I'll update this thread when we have an update on the timeframe.

**Comment by srogovtsev** [comment]
@craigjensen, it seems like even if I have a (reply) `ChannelData` containing `thread_ts`, it still doesn't make to Slack, i.e. the message is still sent to the channel itself.

**Comment by craigjensen** [comment]
We have a work item to add thread support to Slack but it hasn't been implemented yet.  I'm hoping to get to this in the next week or so.

**Comment by srogovtsev** [comment]
Am I right that unless you complete it even manually crafted `ChannelData` won't be able to pass thread identifier to Slack?

**Comment by craigjensen** [comment]
That's correct - we need to make a couple changes to pass the new thread_ts through.

**Comment by srogovtsev** [comment]
Thank you for the clarification.

**Comment by nwhitmont** [comment]
@craigjensen any updates on threads support in Slack Channel.

**Comment by craigjensen** [comment]
Threading support was deployed sometime last week.  Bots that reply to a threaded conversation should stay in the thread.

**Comment by nwhitmont** [comment]
thanks for the update @craigjensen !

**Comment by davidwengier** [comment]
Thanks guys, works perfectly! My bot got smarter and I didn't have to change a thing :)
