### ISSUE TITLE
[Facebook Channel] Normal Button Instead of account_link for FB Messenger 

### ISSUE THREAD

**Issue by MrOnyancha** [Microsoft/BotBuilder#2274]
This issue is not yet resolved
![screen shot 2017-02-16 at 12 26 18 am](https://cloud.githubusercontent.com/assets/5436153/23008597/accd31ba-f421-11e6-86c1-00dcc2abe807.png) 
It's actually showing that this is to  be coming screens but thus not the case. Instead of this 
![screen shot 2017-02-16 at 12 26 26 am](https://cloud.githubusercontent.com/assets/5436153/23008598/accd66bc-f421-11e6-9c1d-e3d17939ca30.png)
It redirects out side which makes the experience horrible.

How can i make the bot show this screen instead of redirect outside??/

**Comment by craigjensen** [comment]
To enable account linking you need to register the message_account_linking callback for your bot and send a native Facebook log in button via ChannelData/SourceEvent.

**Comment by nwhitmont** [comment]
thanks for the info @craigjensen
