### ISSUE TITLE
Connecting Hubot With AI Module

### ISSUE THREAD

**Issue by Viper702** [Microsoft/BotBuilder#2275]
I have a hubot that has an AI module installed. I want it to respond to the Framework with it's own responses. Can you point me in the right direction on how to do this?

**Comment by maxpert** [comment]
Are you trying to send messages over to botframework from your hubot? In that case you can use the (hubot botframework adapter)[https://www.npmjs.com/package/hubot-botframework]. The adapter is pretty new, but should get the job done.

**Comment by Viper702** [comment]
Hello. 

 

Thank you so much for your reply. I did find the hubot botframework adapter last week and it does get the job done! It also appears to me that the adapter would be a great starting point to create a direct to Kik adapter.

 

Erick
