### ISSUE TITLE
How to change default messages from BotBuilder.json?

### ISSUE THREAD

**Issue by ancashoria** [Microsoft/BotBuilder#2276]
Hi, is it possible to cleanly change the messages from 
https://github.com/Microsoft/BotBuilder/blob/d176385615934d9aedd03d26d27d0b65235174df/Node/core/src/locale/en/BotBuilder.json ?

Thanks

**Comment by palmerabollo** [comment]
Yes, you can put a custom BotBuilder.json under a /locale folder in your project, and load it using the following setting when you create your bot:

```
let settings = {
    localizerSettings: {
        botLocalePath: path.join(__dirname, '..', 'locale'),
    },
    ... other settings
};
```

This is explained in [the official docs, under the Namespaced Prompts section](https://docs.botframework.com/en-us/node/builder/chat/localization/#namespaced-prompts). HTH.

**Comment by willportnoy** [comment]
thank you @palmerabollo !

**Comment by ancashoria** [comment]
Thank you very much @palmerabollo, I didn't think to look under localization.
Also, I want to thank you guys for your excellent work, this framework is proving immensely powerful and extendable.

**Comment by Andrea-Orimoto** [comment]
Thanks @ancashoria! Closing this issue since it seems solved. Feel free to reopen it if this is not the case. Thanks!
