### ISSUE TITLE
Automate the LUIS model training using custom algorithm 

### ISSUE THREAD

**Issue by pvagare** [Microsoft/BotBuilder#2278]
Can I customize the classification & clustering using my own analytics algorithm for LUIS model training ?
reason I asked question because, today I have to manually lookup the LUIS utterances and train the intent according. If so I have 10K message every day. It would be extremely tedious procedure to do training the model ?

**Comment by andradedearthur** [comment]
You could use the LUIS Programmatic API to do this. Link: https://dev.projectoxford.ai/docs/services/56d95961e597ed0f04b76e58/operations/56f8a55119845511c81de483

**Comment by cahann** [comment]
Why do you need to label all those examples? You should only label examples to fill in gaps in the models prediction.

**Comment by pvagare** [comment]
@cahann  Yes I need more concrete predictions.  That why I need to to label those examples.

**Comment by jameslew** [comment]
@pvagare Labeling everything won't necessarily make your model better; you only want to add new labeled utterances for the items that improve your model for cases not well covered, etc.

**Comment by carlosscastro** [comment]
@pvagare I'm closing the issue for now but reopen if you have further questions on this topic.

**Comment by strategist922** [comment]
@cahann, I have similar question, I remember LUIS has batch mode API to retrain or to correct/add uncorrect/new  intent / entities , if I only use batch mode API to do these purpose, still unecessarily?
