### ISSUE TITLE
Single SignOn for multiple chatbot. 

### ISSUE THREAD

**Issue by pvagare** [Microsoft/BotBuilder#2279]
Is there inbuilt support for Single SignOn in the chatbot framework if I have multiple chatbots and many people were using the chatbots?

**Comment by willportnoy** [comment]
Here is how you might handle the Bot Framework authentication requires for multiple chat bots:
https://github.com/Microsoft/BotBuilder/issues/2258#issuecomment-280506334

What kind of SSO are you looking for?

**Comment by pvagare** [comment]
@willportnoy 

Suppose I have one business user who is authenticated with oAuth2 once during his conversation with chatbot X.  If the same user starts conversation with chatbot y in a single Skype session. I do not want to authenticate again same user.

**Comment by willportnoy** [comment]
You might take a look at https://docs.botframework.com/en-us/bot-framework-guide-id/ - many channels scope user ids by bot to avoid leaking user information across bots.
