### ISSUE TITLE
C# Organising Luis intent classes

### ISSUE THREAD

**Issue by jcalixte** [Microsoft/BotBuilder#228]
Hello,
I am currently working on a bot with a lot of intents coming from LUIS (hundreds for sure), I'd like to split and organise classes by group of intents (like splitting your PizzaOrderDialog class sample). Is it possible?

Thank you,

Julien

**Comment by willportnoy** [comment]
You should be able to use partial classes in C# - would that work for you?

**Comment by ankitbko** [comment]
This is something I have been looking for also.  LUIS is meant to get evolved as more intents are added and trained. The code handling LUIS intents will also grow specially if they spawn complicated forms as well. It would be helpful if it is possible to keep LUIS intents in different projects to promote a plugin type of architecture. Specially in enterprise projects, where we could have a single bot which evolves and grows to accomplish multiple automation which can get complicated, it would be better if I could just write and _plugin_ (Register) the LUIS intent as separate project once it is mature enough without having to modify previously written code, or add partial classes.

Also is there a way to have multiple LUIS model in a single bot?

**Comment by willportnoy** [comment]
I agree with the need for modularity in handling LUIS requests.  We would have to add a mechanism to use a single LUIS model with multiple LUIS Dialogs.

To answer your second question, you can have multiple LUIS dialogs for multiple LUIS models in a single bot - perhaps the challenging aspect is dispatching across them.  This is related to the first issue.

**Comment by jcalixte** [comment]
Partial classes aren't enough for our projet maintainability but I'll use it for now.
I am looking forward to how it can be done next. Thank you.

**Comment by Stevenic** [comment]
Please re-open if there's more to discuss around this issue.

**Comment by J3QQ4** [comment]
@Stevenic  and @willportnoy, may I ask if partial C# classes are actually supported by LuisDialog? I am trying to split the intent handlers into separate files, but it seems that LuisDialog doesn't pick up any intent that is handled in another file that is a part of a partial class. 

Here is my main LuisDialog class file: 

    [LuisModel("xxxxxxx", "xxxxxxxx")]
    [LuisModel("xxxxxxx", "xxxxxxxx")]
    [Serializable]
    public partial class LuisRootDialogEnglish : LuisDialog<object>
    {
        
        [LuisIntent("")]
        [LuisIntent("builtin.intent.none")]
        public async Task None(IDialogContext context, LuisResult result)
        {
            await context.PostAsync("didn't get it");
            context.Wait(MessageReceived);
        }

And here is another part of the class in another file:

    public partial class LuisRootDialogEnglish : LuisDialog<object>
    {
        [LuisIntent("get_product")]
        public async Task GetProduct(IDialogContext context, LuisResult result)
        {
    ...

When debugging, the None method is always called, even though in LuisResult I can see that the get_product intent is the highest ranked. 

The files are in the same namespace and I've tried adding [Serializable] and [LuisModels] to the partial classes, but it doesn't work with or without them. 

Is this something that's currently not supported or is there a problem with my code?
