### ISSUE TITLE
 Support for OAuth in bot framework?

### ISSUE THREAD

**Issue by pvagare** [Microsoft/BotBuilder#2280]
Is there inbuilt support for OAuth in Microsoft chatbot framework? How should authenticate the my own business users ?

**Comment by ankitbko** [comment]
You may checkout [Simple Facebook Auth Bot](https://github.com/Microsoft/BotBuilder/tree/master/CSharp/Samples/SimpleFacebookAuthBot) sample for OAuth implementation.

**Comment by stevengum** [comment]
https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-authentication?view=azure-bot-service-3.0
