### ISSUE TITLE
 Support for authorization in the bot framework 

### ISSUE THREAD

**Issue by pvagare** [Microsoft/BotBuilder#2282]
Is there inbuilt support for authorization in the bot framework ? If not then How to do the custom authorization in chatbot framework

**Comment by willportnoy** [comment]
Can you give more details?

@pvagare you might consider opening fewer (than 5) issues if they're pretty closely related questions.

**Comment by carlosscastro** [comment]
@pvagare I'm closing this for now, but feel free to reopen if you want to discuss this further.

**Comment by subhamawasthi** [comment]
Hello all,
I want to authorize various intents in my Bot based to role of user as admin or employee..
Is it possible to have a attribute based authorization(Like the one we have in MVC action methods)?
If a code snippet could be shared it would be helpful.
