### ISSUE TITLE
 Support for Role based Access control (RBAC) in bot framework

### ISSUE THREAD

**Issue by pvagare** [Microsoft/BotBuilder#2283]
Is there inbuilt support for Role based Access control (RBAC) in bot framework ? (internal stakeholders , external stakeholders,anonymous)

**Comment by dandriscoll** [comment]
Hi @pvagare, are you asking about the Bot Framework development portal (https://dev.botframework.com) for owners of the bot, or are you asking about end users of the bot?

**Comment by pvagare** [comment]
@dandriscoll  Yes I am asking for end users of bot. 
Suppose I have one chatbot and using skype as channel. I am using Active Directory for skype to talk with the chatbot. I have some role assigned to me. 
So I am asking that Is there inbuilt support for Role Based access control to access the My chatbot.

Using Role based access I will add my chatbot as different functionality for different types of Role.

**Comment by dandriscoll** [comment]
At the moment there is no built-in support. However, there are some samples you can use to log in a user. For example, AuthBot illustrates how this can work: https://github.com/MicrosoftDX/AuthBot

**Comment by carlosscastro** [comment]
Closing for now. @pvagare feel free to reopen if the answer from @dandriscoll did not make things clear.

**Comment by siddharthpant92** [comment]
@dandriscoll @carlosscastro Is there any update on this? I came across this while searching for the same functionality in the bot framework documentation

**Comment by dandriscoll** [comment]
Yes, we now support native user sign-in across most channels. https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=aadv2%2Ccsharp

**Comment by siddharthpant92** [comment]
I was actually looking for something along the lines in the following scenario: 
User with role type A will see list A of bot command options, but user with role type B will see list B of bot command options. So depending on the role of a user, they will have a different set of bot commands that they can invoke? Is that functionality available? Or would we have to somehow create 2 separate bots within the same application, 1 bot for user role A, and 1 bot for user role B, where each bot has their own separate list of bot command options?

**Comment by dandriscoll** [comment]
I've built something like that in bots that I've authored, and I'm not sure it requires any special support. If you're relying on the user's account as the primary ID, all you need is:

1. Mark the user with the role in your backing datastore (e.g. `role=administrator`)
2. When you load your dialogs, load that flag into a user state variable
3. Your dialogs can then switch on that variable

**Comment by siddharthpant92** [comment]
Is there any documentation for what you've authored? I can have a look to see if it fits our use case?
