### ISSUE TITLE
[Skype Channel] openUrl action in HeroCard is disabled on iPhone skype mobile

### ISSUE THREAD

**Issue by arieschwartzman** [Microsoft/BotBuilder#2287]
For some reason the openUrl action on a hero card on skype mobile for iPhone, does not respond to taps.
The URL is very long with many parameters but it's https. It works fine on Skype on the desktop and WebChat on mobile.

**Comment by arieschwartzman** [comment]
BTW It also works fine on Skype for Android.

**Comment by nickcordrey** [comment]
Please could you share a sample of the URL?

**Comment by nwhitmont** [comment]
@arieschwartzman are you still experiencing this issue?

**Comment by nwhitmont** [comment]
@arieschwartzman reopen if you're still having issues.
