### ISSUE TITLE
Can we attach an image with form field prompt?

### ISSUE THREAD

**Issue by singhsurya** [Microsoft/BotBuilder#2288]
We need to send an image to user during a form field prompt to help user to answer the question. How can achieve this?

**Comment by willportnoy** [comment]
Here is an older answer that might help:

https://github.com/Microsoft/BotBuilder/issues/1102

**Comment by chrimc62** [comment]
@singhsurya were you able to do what you needed?

**Comment by chrimc62** [comment]
Closing for lack of response.
