### ISSUE TITLE
Add support for asp.net core on full .net framework

### ISSUE THREAD

**Issue by berhir** [Microsoft/BotBuilder#2289]
As already discussed with @msft-shahins in my [comment](https://github.com/Microsoft/BotBuilder/issues/1473#issuecomment-280379876) in #1473 the new asp.net core support is for .net core only. But a lot of people are using asp.net core with the full .net framework because not all dependencies are already available for .net core/.net standard.

At least support for .net 4.6.1 can be added with just a few more lines in the project.json file. I have created a branch with support for .net 4.6.1 here:
https://github.com/xeet/BotBuilder/blob/aspnetcore-full-netfx/CSharp/Library/Microsoft.Bot.Connector.AspNetCore/project.json

But a separate nuget package with the assemblies for asp.net core is necessary. The old/existing nuget package should be for web api on .net 4.5 only. And the second/new one for asp.net core on .net461 and .net standard 1.6.

It seems to be a good idea/best practice to have a separate package for asp.net core in any case. At least all projects I know do it this way.

What do you think?

**Comment by andreesteve** [comment]
@berhir I think what you are asking was introduced with PR #2346

**Comment by berhir** [comment]
@andreesteve Yes, that's exactly what I asked for. So this issue can be closed. Thanks!

**Comment by izaaz** [comment]
Hey guys, has this been released to nuget? If yes, which version of Bot.Builder supports this?

**Comment by msft-shahins** [comment]
you need the following nugets for this: [bot.builder.common](https://www.nuget.org/packages/Microsoft.Bot.Builder.Common/3.6.0-alpha) and [bot.connector](https://www.nuget.org/packages/Microsoft.Bot.Connector/3.6.0-alpha).

**Comment by JasonSowers** [comment]
Closing, issue was resolved.

**Comment by izaaz** [comment]
@msft-shahins I tried using bot.builder.common and bot.connector, but I get the following error (in emulator with the app id and password set)

      Connection id "0HL5ACUA2BP05": An unhandled exception was thrown by the application.
System.UnauthorizedAccessException: Authorization for Microsoft App ID <<appid>> failed with status code Unauthorized and reason phrase 'Unauthorized' ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.Bot.Connector.JwtTokenRefresher.<SendAsync>d__2.MoveNext()

When I look at fiddler, I see a successful call to get the access token and I don't see any unauthorized calls. Am I missing something?

Also, is there any aspnetcore sample project that I can look into to make sure I'm not doing something wrong?

Thanks,
Izaaz

**Comment by izaaz** [comment]
I got it to work. I had to add smba.trafficmanager.net as a trusted URL. Any reason why this is not added by default?

**Comment by msft-shahins** [comment]
@izaaz  here is a sample showing how you can use asp net core packages: https://github.com/Microsoft/BotBuilder/tree/master/CSharp/Samples/Microsoft.Bot.Sample.AspNetCore.Echo

Also you need the TrustServiceUrl attribute offered by https://www.nuget.org/packages/Microsoft.Bot.Connector.AspNetCore.Mvc/3.6.0-alpha to have the service url trusted automatically after authentication: https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Samples/Microsoft.Bot.Sample.AspNetCore.Echo/Startup.cs#L37
