### ISSUE TITLE
[Direct Line] bot conversation out of order when answering too quickly

### ISSUE THREAD

**Issue by McGern** [Microsoft/BotBuilder#2293]
Hi,

I'm having an issue with a bot built using the C# framework. The bot is on the server and connected through directline to the webchat interface.

If I respond to a prompt too quickly, the bot session gets confused and responds as if it was the previous prompt. If there is a delay, the bot responds with the correct dialog.

e.g.

Bot - "Hi, would you like to get a quote?"
User - "Yes"
Bot - "Great! Could you give me your first and last name please?"
User (replies within a second) - "Bill Smith"
Bot - "Sorry, I was expecting yes or no. Would you like to get a quote?" 

The bot is now in the first question loop even though it responded to the first answer correctly and seems to pass into the next dialog.

If there is a delay after after the bot's response (say 2 or 3 seconds) then there is no issue, but that means forcing the user to wait an arbitrary amount of time before responding.

The bot is using iDialog for each question and passing to the next dialog with the IDialogContext "Call" method.

Just to note, the emulator does not exhibit this behaviour, even when you answer the next question before it has been asked e.g.

Bot - "Hi, would you like to get a quote?"
User - "Yes"
User - "Bill Smith"
Bot - "Great! Could you give me your first and last name please?"
Bot - "Thanks Bill. Can I take your age please?" 

Any help would be appreciated.

Thanks,
Jarrod

**Comment by McGern** [comment]
Just as an update to this, I have tried another example using the pizza bot formbuilder example (to keep it as vanilla as possible) and it behaves in the same way. I tested it in the dev.botframework.com test section after the bot was published to azure.

It is easy to replicate, just have the next answer primed and send it when the bot responds. I had modified this example for something else I was working on, so the first question is asking for your age. So the test sequence is:-
User - "hello"
Bot - "Can I take your age please?"
User - "50"
Bot - "What kind of sandwich do you want..." (more text follows)
User - "1" (enter it as soon as the bot responds with the previous prompt. This seems to be have less delay than the one I am working with, but it is still present)
Bot - "1 is not an age options" (age out of bounds)

https://webchat.botframework.com/embed/bot_form_test?s=CP5yeTnV0KU.cwA.2p0.u8IcowAv6EBRgHonnvWeJ5B8tVbkvFuw09340VHRZbw

**Comment by McGern** [comment]
I have updated to version 3.5.3 and it seems to be working much better now. Can fire 3 future answers in a row before the bot responds and it (mostly) gets the order right, so the real-life case of actually waiting for a response before sending seems to be fixed.

Could anyone confirm please if this is a fix that has been put in place since 3.5.2 or is it just a side-effect of something else?

**Comment by carlosscastro** [comment]
@willportnoy , could you help clarify this one?

**Comment by willportnoy** [comment]
I don't think there has been a recent fix to the bot builder.  This questions has more information about how the bot builder SDK tries to help with concurrent messages on the same machine:
https://docs.botframework.com/en-us/technical-faq/#how-can-i-fix-precondition-failed-412-or-conflict-409-http-errors

In general, message delivery is not guaranteed to be in order for any channel, and scaling your bot across multiple replicas can also lead to similar issues.

There may have been service updates for DirectLine that would help ensure message ordering - @dandriscoll ?

**Comment by dandriscoll** [comment]
Nothing recently. The last sequencing issue we found/fixed was summer of last year.

**Comment by nwhitmont** [comment]
@McGern Are you still experiencing the issue after upgrading to [BotBuilder 3.8.1](https://www.nuget.org/packages/Microsoft.Bot.Builder/)?

**Comment by McGern** [comment]
@nwhitmont I haven't seen the issue since the 3.5.2 update. Haven't updated to the latest bit sdk because we are about to go live, and didn't want to  have to retest again when it seems to be stable
