### ISSUE TITLE
Invalid conversation ID in teamsChannelId after update to v3.5.3

### ISSUE THREAD

**Issue by AlexanderKovalev** [Microsoft/BotBuilder#2294]
After updating to v3.5.3 receiving error: "Invalid conversation ID in teamsChannelId"
in code (CreateDirectConversationAsync part): 

`            var connector = new ConnectorClient(new Uri(serviceUrl), new MicrosoftAppCredentials());
            var conversationId = await connector.Conversations.CreateDirectConversationAsync(botAccount, userAccount);
`

**Comment by jsiegmund** [comment]
Are you sure it's related to the release? I'm getting the same in 3.5.2 but I'm not completely sure yet whether it's not me own fault.

**Comment by AlexanderKovalev** [comment]
I think yes, because it worked before 3.5.2.
After update to 3.5.2 and 3.5.3 it started to generate this error

**Comment by rjoosen** [comment]
Same issue over here. 3.5.3. Not sure when I updated but code used to work a few days ago.

**Comment by jsiegmund** [comment]
It's probably something server side as that "teamsChannelId" property doesn't exist in the repo. The channel stuff is being done server side somewhere so that might have changed. For 3.5.2., the following code is working for me, but that needs an existing conversation Id to reply to: 

```
var userAccount = new ChannelAccount(cookie.Address.UserId);
var botAccount = new ChannelAccount(cookie.Address.BotId);

Activity activity = cookie.GetMessage();

// need to trust the service URL because otherwise the bot connector authentication will fail
MicrosoftAppCredentials.TrustServiceUrl(cookie.Address.ServiceUrl);

// construct the reply to send back to the user
IMessageActivity messageToSend = Activity.CreateMessageActivity();
messageToSend.ChannelId = cookie.Address.ChannelId;
messageToSend.From = botAccount;
messageToSend.Recipient = userAccount;
messageToSend.Conversation = new ConversationAccount(id: cookie.Address.ConversationId);
messageToSend.Text = replyText;
messageToSend.Locale = "en-Us";
messageToSend.ServiceUrl = cookie.Address.ServiceUrl;

await connector.Conversations.SendToConversationAsync((Activity)messageToSend);
```

**Comment by rjoosen** [comment]
That seems to work, with some minor modifications:
(Only with Skype contacts by the way)

```
var userAccount = new ChannelAccount(bUsers.UserId);
            var botAccount = new ChannelAccount(context.Activity.From.Id);
            MicrosoftAppCredentials creds = new MicrosoftAppCredentials(AppKey, AppPwd); ;
            var connector = new ConnectorClient(new Uri(bUsers.ServiceUrl), creds);

            // need to trust the service URL because otherwise the bot connector authentication will fail
            MicrosoftAppCredentials.TrustServiceUrl(bUsers.ServiceUrl);

            // construct the reply to send back to the user
            IMessageActivity messageToSend = Activity.CreateMessageActivity();
            messageToSend.ChannelId = context.Activity.ChannelId;
            messageToSend.From = botAccount;
            messageToSend.Recipient = userAccount;
            //messageToSend.Conversation = new ConversationAccount(id: context.Activity.Conversation.Id);
            messageToSend.Conversation = new ConversationAccount(id: bUsers.ConversationId);
            messageToSend.Text = "Hello";
            messageToSend.Locale = "en-Us";
            messageToSend.ServiceUrl = bUsers.ServiceUrl;

            await connector.Conversations.SendToConversationAsync((Activity)messageToSend);
```

**Comment by AlexanderKovalev** [comment]
Working for me, but tested only for Skype, not sure if it works for any other channels

**Comment by Stevenic** [comment]
Closing this as fixed.

**Comment by AlexanderKovalev** [comment]
Why closed? Did "CreateDirectConversationAsync" fixed as well?

**Comment by Stevenic** [comment]
Sorry... I thought this was a node issue. Assigned the right dev to it.

**Comment by konstlut** [comment]
@AlexanderKovalev @rjoosen @jsiegmund  This issue was due to a configuration change on the backend that was fixed on Wed, 02/22/2017. It is not related to the client implementation or SDK update.
