### ISSUE TITLE
Keep getting error: I didn't understand. Please choose an option from the list.

### ISSUE THREAD

**Issue by himanshuphirke** [Microsoft/BotBuilder#2295]
I am trying different options available for communication with bot.
I keep changing the app  using the same client id and password. On Skype bot I keep getting error:

**I didn't understand. Please choose an option from the list.**

The console prints _WARN: Dialog '*:/menu' not found in library._

/menu was a dialog in previous example. Running the local bot using ngrok.

Is there are way to reset the channel for a bot. Using SDK for node.js

**Comment by willportnoy** [comment]
Usually you can send a "/deleteprofile" command, but I believe the Node version should reset itself if the dialog stack contains a dialog ID that does not exist anymore.

**Comment by Stevenic** [comment]
I just checked in a fix for this. It will be part of the next release this week.

**Comment by Stevenic** [comment]
Just released v3.7.0 with fix

**Comment by himanshuphirke** [comment]
Got latest v3.7.0
I see the same error again.
No error on console.

It works fine with webchat and slack channels. The problem I see is, its not at all calling the root dialog.

I have to delete the bot and get a new one to have the same node code working

Let me know if any more info is required from my side to fix the issue.

**Comment by willportnoy** [comment]
@Stevenic is there a command in Node to clear the dialog stack?

**Comment by Stevenic** [comment]
If you add the code below to your bot you can then say "goodbye" and it will clear the dialog stack:

```
bot.endConversationAction('goodbyAction', "Ok. See you soon!", { matches: /^goodbye/I });
```

**Comment by Nisthar** [comment]
@Stevenic Any fix for this?

Still getting this error when in group conversation.

The error is due to the "@Bot name" text getting in the session.message.text. I checked for it and removed the "@bot name" part and its working fine. 

But it would be nice if you could fix it at the core.
