### ISSUE TITLE
GUID like value is showing in title on skype web app

### ISSUE THREAD

**Issue by mandarBadve** [Microsoft/BotBuilder#23]
Don't know this is right place to submit issue.

I have added couple of bots from bot directory like Bing new and Bing music to skype. It has been added successfully to Skype. But in contacts list it is showing some GUID like value. Please check the image uploaded.
![image](https://cloud.githubusercontent.com/assets/2083251/14199437/fe9c38b4-f801-11e5-8220-a6bf2f53a0c5.png)

**Comment by Stevenic** [comment]
You need to update skype to the latest version. This will go away.

**Comment by mandarBadve** [comment]
I faced this issue on web app

**Comment by Stevenic** [comment]
Ok... Not sure then. That just looked like what I saw before I updated to the latest version of the app. Could be that their web app hasn't been updated to support bots yet. I know the Mac version of the app hasn't. You might try asking about this on skypes developer forum.

**Comment by mandarBadve** [comment]
Thanks for reply. I will post this issue to Skype team.
