### ISSUE TITLE
BotAuthenticationFromSetting

### ISSUE THREAD

**Issue by wiltodelta** [Microsoft/BotBuilder#230]
`[BotAuthenticationFromSetting("BotAppId", "BotAppSecret")]`

If I use BotAuthenticationFromSetting attribute with custom names of AppId and AppSecret settings, I can't send more than one message from Dialog via content.PostAsync. Messages just don't come.

**Comment by wiltodelta** [comment]
How to use CloudConfigurationManager with BotAuthentication?

**Comment by wiltodelta** [comment]
Any update?

**Comment by willportnoy** [comment]
The way we instantiate the IConnectorClient to send multiple messages uses the credentials stored in the app.config - I'll add some code so that you can override these credentials by using the autofac DI container.

**Comment by willportnoy** [comment]
As a temporary workaround, you can put your credentials in the app.config.

**Comment by willportnoy** [comment]
I checked in https://github.com/Microsoft/BotBuilder/commit/7db048908ef044f07db45340acedf45637ec0c04 which would allow you to resolve ConnectorClientCredentials from the container.  I'll close this issue for now, but feel free to re-open to discuss more.

**Comment by vovanb** [comment]
Helo, saw above code about assigning auth configuration for IConnectorClient , but not exactly understand how to use it from c# template project fro 3.0.1 ? Can you provide example of using it.
Thanks

**Comment by willportnoy** [comment]
You should probably open a new issue - this issue is pretty old and related to V1 of the Bot Framework.

**Comment by vovanb** [comment]
Already did - waiting for answers
