### ISSUE TITLE
Invalid conversation ID in teamsChannelId by using startConversation

### ISSUE THREAD

**Issue by raphael2711** [Microsoft/BotBuilder#2301]
i already build a running function to send a message to a skype user.
i use the nodejs function startConversation and send to send the message.
2 days ago it works fine. 

I don't changed my code but now i got the error "Invalid conversation ID in teamsChannelId",
when i use the startConversation function.

I don't understand the teamsChannelID , i don't use the channel Teams. 
I only use Skype channel.

**Comment by AlexanderKovalev** [comment]
Please check here the same issue: https://github.com/Microsoft/BotBuilder/issues/2294
