### ISSUE TITLE
[Direct Line] Get 502 (bad gateway) randomly

### ISSUE THREAD

**Issue by hyjasonmei** [Microsoft/BotBuilder#2304]
Hi Team

I got 502 bad gateway error randomly.
Most of messages are fine to transfer.
But sometimes we got 502 unexpectedly.

URL: https://directline.botframework.com/v3/directline/conversations/rpG4ckovzx/activities
Request payload:
{"type":"message","text":"hi","from":{"id":"I1sp0R39f9R","name":"You"},"locale":"zh-TW","timestamp":"2017-02-20T06:33:36.768Z","channelData":{"clientActivityId":"1487571796913.1402582621194608.11"}}

Channel:
Web chat: high frequency get 502 error
Slack: high frequency lose message (can't trace)
FB: low frequency lose message (can't trace)
Skype: no issue

Do you know the root cause?
Because I didn't get any log from my web hook.
The message is just disappeared.
Thank you.

**Comment by dandriscoll** [comment]
Hi @hyjasonmei, a 502 from Direct Line 3.0 means your bot threw an error.

The data is reported in the Bot Framework dev portal. Visit your bot's dashboard and click on the "Issues" for each channel.

If you want more detailed errors, you can connect Application Insights for your bot, or you can add tracing internally within your bot's web service.
