### ISSUE TITLE
directline takes too long to get response.

### ISSUE THREAD

**Issue by zhou-xinghai** [Microsoft/BotBuilder#2308]
Please refer to issue #2089.
The issue persist but seems better, not sure if the backend of directline is optimized by the team. I add some log to trace the time cost in each phase and found that 
1. The directline restful api "Sending an Activity to the bot" takes <1.8s.
2. Luis takes around 5s.
3. A polling GET to receiving Activities from the bot takes around 3s.
So, all together is nearly 10 secs. I use in the simplest way which don't contains any context or state in my bot. Just one question with one reply. 
so, is there any way to improve it. thanks in advance.

**Comment by dandriscoll** [comment]
Hi @zhou-xinghai, have you enabled "High-speed storage" on your Direct Line configuration page?

**Comment by zhou-xinghai** [comment]
Just enable this option. Seems don't shorter the time. I will observe it in a longer time.

**Comment by dandriscoll** [comment]
Can you send a conversation ID or your bot's ID?

**Comment by zhou-xinghai** [comment]
hi ,my bot's Microsoft App ID
9f30580a-3c00-4f71-a0b4-c338d248ae62 
Another issue is directline send msg operation return " id: 'retry'". As long it happens, all sending msg on this conversation will return this value and my botframework won't  get msg . So can you tell me why return this error. 
thanks.

**Comment by dandriscoll** [comment]
Good news is that your bot is responding reasonably quickly, around 500ms.

It looks like you've configured Direct Line for high-speed storage, but the conversation ID you sent was created before this setting was applied. Conversations that are already in progress will stay on the stack where they were created. Can you try again with a new conversation?

I've added more detailed logging on our side and will have better timing information when you reproduce the problem.

**Comment by zhou-xinghai** [comment]
Thanks for your help. It seems faster than before. Can you please take a look at this one conversationId: BhZ3UhDKKJR34kssBdBFjS.

**Comment by dandriscoll** [comment]
Hi @zhou-xinghai, some things I observed about this conversation:

- The longest calls were to POST a message from the client to the bot. These typically took 1-2 seconds.
- These POST calls had around 50ms of internal latency. Calling your bot took between 400ms and 500ms.
- As of 50ms into the call, the message is available for clients to receive.
- As of ~450-550ms into the call, message is delivered to the bot.
- The remainder of the call (500-1000ms) is spent making sure the message is reliably delivered to any clients that connected recently. **This part of the call does not count against the total delivery time**, but you do see it in the API.

I'm planning to refactor the code so those extra 500-1000ms are performed on a background thread, but this is not high-priority work at the moment. Let me know if you have any questions.

**Comment by zhou-xinghai** [comment]
Hi dandriscoll,
  Thanks for your message. It's OK If you can keep the post message time in less 2 secs and response time to 500ms （the faster the better）.  But that time is surprisingly unstable today.  Below is the time cost I tried. Can you please take a look at the log why it cost me even 25secs to post a activity msg? And sometimes takes around 10secs to response rather than 500ms. 
5mr0z5S8PzGKo2zzD2dRvs|0000008  25s sendActivity 
5mr0z5S8PzGKo2zzD2dRvs|0000012  3s sendActivity;  10s response 
5mr0z5S8PzGKo2zzD2dRvs|0000016  3s sendActivity  12s response
Besides, if I post an activity msg after a while like 10mins, then the post time will take much longer than post msg consistently. I think the stable post and response time is mattered at this stage.

**Comment by dandriscoll** [comment]
I think these are network issues.

5mr0z5S8PzGKo2zzD2dRvs|0000008 was 25s from your client.
My server saw 13s for this call.
11s of those 13s was spent calling your bot.

Is it possible you're experiencing connection issues?

**Comment by zhou-xinghai** [comment]
I am not sure, but I use AWS Server and the network should be more realiable. 
So from your log, the 13s was cost on calling my bot? Is it possible that different consersation id take different time? For later, when I start a new conversation, the long latency returns normal.

**Comment by zhou-xinghai** [comment]
As to the problem of " After a while like 10mins the post time will take much longer than post msg consistently.". Is it possible that the inactive conversation will turn into sort of "sleep state" while when it reuse again it will take some more time (like allocate the thread or some resources) to activated the consersation session.

**Comment by dandriscoll** [comment]
@zhou-xinghai, yes, it's possible for your hosting platform to put your application into a sleep state. I don't have any details about how this works in AWS, sorry.
