### ISSUE TITLE
Is there a Portable library for DirectLine API , which can be installed in the Xamarin Portable Lib Project in Android Solution

### ISSUE THREAD

**Issue by AnandChitale** [Microsoft/BotBuilder#2309]
I am creating a sample Android application and using Xamarin to develop one.
I want to use DirectLine API to communicate to bot from Android APP.
Is there a portable lib which can be installed in Xamarin Portable project and not in .Droid Project.

The directline API gets installed in .Droid project but not in Portable project , which makes the implementation specific to android and not cross platform.

**Comment by dandriscoll** [comment]
Some developers who have asked for PCL support in the past have found that the .Net Standard 1.3 libraries in our Nuget package (https://www.nuget.org/packages/Microsoft.Bot.Connector.DirectLine) work for them.

If those don't work, the Nuget package is 99% generated code on top of the Direct Line swagger file (https://docs.botframework.com/en-us/restapi/directline3/swagger.json). The remaining code is just to set the Authorization header (Bearer scheme) and to set the endpoint to directline.botframework.com.

**Comment by matvelloso** [comment]
@dandriscoll FYI @angelobelchior seems to be trying to use this in a PCL project without success. It seems this Nuget is still native only.

**Comment by angelobelchior** [comment]
Thanks @matvelloso ! I followed the APIs documented in Swagger and created a library. Soon I publish the source code.

**Comment by fzoccara** [comment]
Hello @angelobelchior,
can you share the source code with us?

Best.
Francesco.

**Comment by Edwardfelix08** [comment]
@fzoccara, Is their source code for the below mention tutorial.
EDIT: I've found this awesome tutorial:
https://mindofai.github.io/Bot-Framework-and-Xamarin.Forms-Application-Integration-using-DirectLineClientAPI/

And will this work for a bot built using TypeScript.

Thanks,
Edward
