### ISSUE TITLE
C# vs. NodeJS

### ISSUE THREAD

**Issue by mikkhait** [Microsoft/BotBuilder#231]
I'm working with NodeJS version of the framework. My question to both C# and TS teams regarding feature synchronization and roadmap. How in-sync are you? Can we expect both versions be 100% in-sync in the future?

**Comment by tomlm** [comment]
They will be philosophically in-sync, except for where they need to deviate to cater to programming patterns which are prevalent in the different environments.

**Comment by mikkhait** [comment]
So, the next logical question is if you guys are planning to make your roadmap public?

**Comment by tomlm** [comment]
We don’t have a plan to publish a roadmap, not because we don’t want to but because everything is moving very fast in this space.  I would expect that we will communicate a roadmap at some point. ☺

**Comment by Stevenic** [comment]
Feel free to reopen if you'd like to discuss this more.

**Comment by mikkhait** [comment]
I guess we will just have to see how this plays out :)

**Comment by CME64** [comment]
As far as I understood, you are trying to sync both frameworks in terms of features. But which one outpaces the other most of the time (in terms of development/features/bugfixes)? surely there is a primary focus here.

**Comment by EricDahlvang** [comment]
Public Roadmap for dotnet and javascript sdk:

https://github.com/Microsoft/botbuilder-dotnet/wiki/Roadmap

https://github.com/Microsoft/botbuilder-js/wiki/Roadmap
