### ISSUE TITLE
Get slack user address without user first interaction  with bot

### ISSUE THREAD

**Issue by aakashvit** [Microsoft/BotBuilder#2311]
[](https://docs.botframework.com/en-us/node/builder/chat/UniversalBot/#proactive-messaging-and-localization)
I want to send notification to user ,Below code is working but only if user interact at-least one time with bot. Whenever slack user will interact with bot I am saving address into db then letter i am using address to send

is it possible to get user address without user interaction with bot.???
this code is working for me 

`server.post('/api/notify', function (req, res) {
    // Process posted notification
    var address = JSON.parse(req.body.address);
    var notification = req.body.notification;

    // Send notification as a proactive message
    var msg = new builder.Message()
        .address(address)
        .text(notification);
    bot.send(msg, function (err) {
        // Return success/failure
        res.status(err ? 500 : 200);
        res.end();
    });
});`

**Comment by aakashvit** [comment]
@Stevenic  Can you  give advice on this issue??

**Comment by Stevenic** [comment]
Adding craig... @aakashvit  you may need to use slacks API's directly to find the list of users for a channel or team. You can then modify the `address.user.id` field of an full address object to tweak who your messaging.  You'll want to delete the `address.conversationId` field to start a new private conversation with each user.

**Comment by aakashvit** [comment]
issue solved. thank you  a lot :)

**Comment by duncanmak** [comment]
@aakashvit Can you elaborate on what you did to fix this?

@Stevenic Is there an event on 'start up' so that I can iterate the list of channels the bot is in? I'm writing a proactive bot, so I don't have access to `session`.

**Comment by aakashvit** [comment]
use https://api.slack.com/methods/users.list to get list of all user with address. (will require token for this. you can get from slack)
or pass your token into lib  https://www.npmjs.com/package/slack-node to get user list

once you get all user address save into db (for leter use)

var msg = new builder.Message().address(address).sourceEvent(listcard);
 bot.send(msg);


or if u want to send from session address
var msg = new builder.Message().address(session.message.address).sourceEvent(listcard);
 bot.send(msg);

**Comment by aakashvit** [comment]
var listcard =  {
                            slack: render.displayList(["msg1,"msg2"],"dummy title","dummy",true)
                    }
var msg = new builder.Message().address(address).sourceEvent(listcard);
bot.send(msg);


//with color , with or without number
	//set numbering is undefine if number not require
	//this will display colorfull list
	displayList:function(msglist,title,fallback,numbering){
		var attachments =[];
		if(typeof fallback  !== 'undefined'){
			var notification_heading={"fallback":fallback}
			    attachments.push(notification_heading); 
		}
	  	if(typeof title  !== 'undefined'){
			var t={"pretext": title}
		  		attachments.push(t);
		}
		colorlist=module.exports.color(msglist.length)   //get n randome color
		if(typeof numbering  !== 'undefined'){
			for (var i = 0; i < msglist.length; i++) {
				var j=i+1
				var onemsg=  {
			    	//"color": colorlist[i],
			    	"text": j.toString()+"."+msglist[i]
				}
				attachments.push(onemsg); 
			}
		}

		else{
			for (var i = 0; i < msglist.length; i++) {
				var onemsg=  {
				    //"color": colorlist[i],
				    "text": msglist[i]
				}
				attachments.push(onemsg); 
			} 
		}
		var slack={"attachments":attachments}
		return slack;
	}
