### ISSUE TITLE
service Url + v3/conversations/"conversation["id"]/activities/"id" works for webChat but not skype channe;

### ISSUE THREAD

**Issue by Ashish-Mahalka** [Microsoft/BotBuilder#2315]
I am able to send response back from my bot to webchat channel but not to the skype channel. Also no error is reported in case of skype channel

response url (skype) = https://smba.trafficmanager.net/apis/ + "v3/conversations/'conversation id'/activities/1487614677117

**Comment by konstlut** [comment]
@Ashish-Mahalka We will need more context from you, such as bot id / conversation id you are sending your activity to. Thanks!

**Comment by konstlut** [comment]
@Ashish-Mahalka I am closing thing item as non-actionable from our side. Please reopen if you see this reproduced and provide bot id/conversation id. Thank you!

**Comment by Ashish-Mahalka** [comment]
Please check the below link in stackoverflow
http://stackoverflow.com/questions/42472989/message-to-skype-bot-framework-results-in-http-response-201-created
