### ISSUE TITLE
Directline is taking too much time to respond.

### ISSUE THREAD

**Issue by siddiq-rehman** [Microsoft/BotBuilder#2316]
Hi,

I have been working on microsoft bot framework for over 3 months. I am using the web-chat as client which I got it from "https://github.com/Microsoft/BotFramework-WebChat". 

The POST request to the directline api is very slow at times and the speed is not consistent. I am working within a corporate proxy. Further it is throwing 503 error after almost 85sec, as shown in the image 

![image](https://cloud.githubusercontent.com/assets/22259730/23154983/8f3f397c-f836-11e6-8cd8-6b4ab322f8b8.png)

**Comment by dandriscoll** [comment]
Hi @siddiq-rehman, it appears this was either an SSL or a proxy connectivity failure. Are you able to reliably establish SSL connections to other Bot Framework sites, like https://dev.botframework.com, from behind your proxy?

**Comment by siddiq-rehman** [comment]
@dandriscoll Thanks for the response... :)

Yeah i am able to establish the connection. I am able to POST the directline link, but only at sometimes it is failing. While I initially started development, the post requests were successful, but now failure has become often. Even when the connection is successful, it is taking almost 3 to 4 sec to respond back, and at the client side the response time is almost 8 to 10 sec.
