### ISSUE TITLE
IOS Skype Mobile Video card crash

### ISSUE THREAD

**Issue by chminnaar** [Microsoft/BotBuilder#2317]
Hi

When using a Videocard Skype mobile crashes.

tested with ios version, not sure if Android have same issue.

**Comment by konstlut** [comment]
@chminnaar Could you provide your bot msa app id, please?

**Comment by chminnaar** [comment]
It is : 07274d8a-846c-4618-b703-ef0a6999650c

**Comment by ftachon** [comment]
Hi All
We have the same issue with Android Skype Mobile.
In Skype desktop the video card works fine.

Thanks

**Comment by aery-aery** [comment]
@chminnaar @ftachon As a workaround try to set one of profiles ("sd" or "hd") for your media (video) object.

**Comment by chminnaar** [comment]
Yes adding the Profile to the media object does make it work. Thanks @aery-aery

**Comment by konstlut** [comment]
@chminnaar Great thank you for confirming. Relevant defects were reported to the iOs and Android dev teams and will be fixed. I am closing this ticket as not further actionable from botfrmamework / skype bot api.
