### ISSUE TITLE
HeroCard Tap Not Working on Skype nor in Web Chat

### ISSUE THREAD

**Issue by Highvolt** [Microsoft/BotBuilder#2318]
I am using Node Botbuilder SDK to create a bot.

I was unable to get a openUrl tap action to work, even though the correct information reaches the client, as shown on this image.

![screen shot 2017-02-21 at 10 29 58](https://cloud.githubusercontent.com/assets/182139/23161169/ec951166-f820-11e6-8849-275fc7af3fc3.png)

For now I am using a button as a workaround.

You can see the code I am using in the link bellow: 
https://github.com/CatalystCode/bot-graph-dialog/blob/master/src/GraphDialog.ts#L456

**Comment by ThisWillDoIt** [comment]
I have the same issue with the Emulator. Couldn't test it on other channels yet.  
Is it working for you in the Bot Emulator?

**Comment by Highvolt** [comment]
Another work around that I were able to implement was defining a tap action for the imageCard that were inside de heroCard. (In skype will only work if the link is https)

@ThisWillDoIt I didn't try in bot emulator, but I think the emulator shares the code base with web chat.

**Comment by eanders-MS** [comment]
Hi @Highvolt, @ThisWillDoIt, Support for tap action on cards will be included in the next emulator release.

**Comment by eanders-MS** [comment]
@Highvolt, tap action on cards was recently added to the Web Chat control (https://github.com/Microsoft/BotFramework-WebChat/pull/336), and will be available in the next update.

**Comment by Highvolt** [comment]
@eanders-MS thanks. What about Skype?

**Comment by nickcordrey** [comment]
This is supported in Skype I think it might be because in Skype button actions (and probably tap actions) are restricted to HTTPS only and your URL is HTTP. Please could you try a HTTPS URL and confirm?

**Comment by carlosscastro** [comment]
@Highvolt Did this work for you? I will close this for now but feel free to reopen if it did not work.
