### ISSUE TITLE
Logging and Exception Handling

### ISSUE THREAD

**Issue by narenkv** [Microsoft/BotBuilder#2319]
Hello All,

What is the best practice to be followed for Bots, to 
-  check the health of the bot application
-  log or handle errors errors for bot applications

/Naren

**Comment by willportnoy** [comment]
We recommend using Application Insights - for example:

http://aihelpwebsite.com/Blog/EntryId/11/Using-Application-Insights-With-Microsoft-Bot-Framework

@jameslew did you have another article about using App Insights for Bots?

**Comment by amitbend** [comment]
@willportnoy Application Insights seems like a bad solution for node.
It sends strange .net exceptions instead of node traces

**Comment by willportnoy** [comment]
@Stevenic do you have experience using App Insights with node?

**Comment by Stevenic** [comment]
@willportnoy no I don't. we have some new logging stuff we're working on but not sure it's going to help with this. We're working to add support for streaming a sessions logs to the emulator for debugging purposes but you want more on going monitoring. There are a couple of 3rd parties like http://botanalytics.co/ which have integrated their tools with the Node SDK. That might be an option.
