### ISSUE TITLE
Luis.ai picks up unwanted entities

### ISSUE THREAD

**Issue by mikob** [Microsoft/BotBuilder#2321]
I have an intent that I specify 2 required action parameters for (neither of which is a datetime). When I try an utterance such as this: "post to biology looking for a lab partner this week - any takers?" I need Biology to be a *class* entity (works fine) and the "looking for a lab partner this week - any takers?" to be a *message* entity. 

The message entity gets thrown off by the "this week" part it seems. "this week" is highlighted as a datetime entity, but I never expect a datetime entity with this intent -- that's why I specified the above mentioned action parameters. Is the purpose of action parameters not to limit the entities that get picked up? If not, what is it for?

**Comment by cahann** [comment]
This feature is meant to help you collect the important information related to this intent. But is doesn't limit the entities that get predicted. Anyway this feature is getting deprecated so please don't take dependency on it.
