### ISSUE TITLE
ImageCard image not showing in Skype

### ISSUE THREAD

**Issue by Highvolt** [Microsoft/BotBuilder#2322]
When rendering a ImageCard when the image is large, skype doesn't render the image.

eg: https://i.ytimg.com/vi/wwgk_GC8Q3U/maxresdefault.jpg

This image is correctly render on the Web chat interface.

Is there any documentation about this limitations?

**Comment by endareBrock** [comment]
Hi, im currently having the same kind of issue with skype. I've tried to narrow it down and it seems that skype just doesn't execute the call to retrieve the image.
When you use for example an image from google, it works flawless. But when i want to retrieve an image from my own server it doesn't work.
You find yourself similar in this ?

**Comment by Highvolt** [comment]
@endareBrock To address this issue I started to resize images on the bot, and then send it as an inline image, when the channel being used is Skype.

**Comment by nickcordrey** [comment]
Just to confirm are you referring to Hero Card? https://docs.botframework.com/en-us/csharp/builder/sdkreference/attachments.html. For Skype images in cards should be HTTPS, up to 1024x1024, up to 1MB in size, and PNG or JPEG (see https://docs.botframework.com/en-us/skype/getting-started/#cards-and-buttons)
