### ISSUE TITLE
How to directly connect to Facebook using BotBuilder

### ISSUE THREAD

**Issue by ebattulga** [Microsoft/BotBuilder#2324]
I want to directly receive message from FB to own server. Because botframework.com respond slowly. Avarage BOT response time is 7 secound. It is too slow. 

I need to directly connect to FB using BotBuilder. Please give me some instruction. don't recommend any other framework or library.

**Comment by Stevenic** [comment]
Are you using the Node SDK? If so you would need to implement a custom connector. Someone built one for the v1 version of the SDK but the v3 SDK is quite a bit different. I had asked them to update it for v3 but they didn't have time so you may be starting from scratch. You could look at the ConsoleConnector code for a simple starting point.

**Comment by ebattulga** [comment]
I'm already making Bot using C#. 30 indents with LUIS. 

I'm trying to send directly to FB using Page Access Token. response time decreased to 5 second. Now i will try directly receive message from FB. But i don't know how to start.

**Comment by willportnoy** [comment]
You can receive messages directly from Facebook by following the APIs and protocols documented by Facebook.  Here is a blog post that talks about writing a Facebook Messenger Bot:

https://developers.facebook.com/blog/post/2016/04/12/bots-for-messenger/

It's likely it's a fair amount of work to support each channel, which is one of the reasons we have developed the Bot Framework to connect your Bot to many different channels.

**Comment by willportnoy** [comment]
I'm going to close this issue for now, but feel free to open a new issue for further discussion.
