### ISSUE TITLE
CardAction show the title when selected

### ISSUE THREAD

**Issue by Deviss14** [Microsoft/BotBuilder#2325]
I have a HeroCard with a list of cardActions attach to it. The cardActions are "PostBack" type but when I click on them, the title of the cardAction selected is sent by the user.

Here's how I create my cardAction :
`CardAction cardDispo = new CardAction()
            {
                Value = new JavaScriptSerializer().Serialize(date),
                Type = ActionTypes.PostBack,
                Title = $"{Disponibilite.FormatHour(date.Date)}"
            };`
And here's how it appears on messenger:
![untitled1](https://cloud.githubusercontent.com/assets/17703436/23203552/484569bc-f8e3-11e6-8d5d-5654ac5757c8.png)

I don't know why it shows to the user even if it's PostBack and not ImBack

**Comment by Stevenic** [comment]
Adding the skype team for further comment as it appears that the behavior of `postBack` has changed recently.

**Comment by nickcordrey** [comment]
Thanks we're investigating

**Comment by konstlut** [comment]
@Deviss14 The behavior you describe is correct. postBack renders the cardAction.title in chat history and delivers the cardAction.value to your bot. In your example these values are the same.

**Comment by nickcordrey** [comment]
@Deviss14 there was a config change that might have resulted in an issue for Skype. This is being addressed but to expedite things please send your Bot ID to us at Skype Bot Support <skypebotsupport@microsoft.com> referencing this github thread, and I'll check it for you.
