### ISSUE TITLE
[Message Formatting] Backtick not working on Skype, Slack and Telegram

### ISSUE THREAD

**Issue by kkarahainko** [Microsoft/BotBuilder#2326]
Hello.

Using **Bot Builder 3.5.3**. 

Trying to implement help for bot, need to highlight commands. But, seems like single (inline) and triple back-tick (code block) not working in Skype, Slack and Telegram, renders as a plain text, without back-ticks, not formatted.

``await context.PostAsync(@"Some `tag` here");``

Any Ideas?

**Comment by kkarahainko** [comment]
Tried to do the same thing using block quote (>), 

Skype (incorrect):

![quotes-skype](https://cloud.githubusercontent.com/assets/1279307/23216892/8e550c60-f928-11e6-9f14-210860fbd178.png)

Slack renders correctly:

![quotes-slack](https://cloud.githubusercontent.com/assets/1279307/23216927/aec1df5a-f928-11e6-9e8b-7f6e14b5b0d0.png)

**Comment by nwhitmont** [comment]
@kkarahainko are you using C# or Node SDK for Bot Framework?

**Comment by nwhitmont** [comment]
@kkarahainko reopen if you're still experiencing this issue
