### ISSUE TITLE
Unwanted caption in picture on Telegram

### ISSUE THREAD

**Issue by LorenzCK** [Microsoft/BotBuilder#2327]
Using botbuilder **3.6.0**.

When sending a simple image (message with no text and one single attachment), on Telegram the message is displayed with an unwanted caption (the picture's filename). The same message is shown correctly (without any text) on Facebook Messenger however.

Code used to send the image:
```
session.send(new builder.Message(session).addAttachment({
    contentType: "image/png",
    contentUrl: "http://botify.it/codyquiz/riddles/1.png"
}));
```

Shown on Telegram as:
<img width="150" alt="tmp" src="https://cloud.githubusercontent.com/assets/1782445/23224023/0b2c8a98-f92d-11e6-9349-0d52625254cf.png">
(Unwanted caption underlined in red.)

Is there a way to prevent the caption from showing up?

**Comment by LorenzCK** [comment]
Also, on Skype the same image is shown with a bold “Picture” title:
<img width="169" alt="tmp" src="https://cloud.githubusercontent.com/assets/1782445/23251299/1ac4fcee-f9ad-11e6-9ec0-e82ab3b73d95.png">

**Comment by Stevenic** [comment]
Adding eric who can confirm but that is most likely the default behavior of Telegram & Skype if you don't provide a title.  May not be anything we can do about that.

**Comment by eanders-MS** [comment]
This is the default behavior of Telegram for images. You can work around it by sending the image as a hero card:
```javascript
    var card = new builder.HeroCard(session)
        .images([builder.CardImage.create(session, 'http://botify.it/codyquiz/riddles/1.png')]);
    var msg = new builder.Message(session)
        .attachments([card]);
    session.send(msg);
```

**Comment by Stevenic** [comment]
Closing this for now. Please feel free to add further comments.
