### ISSUE TITLE
ChatBot is not working fine in own azure web server

### ISSUE THREAD

**Issue by AlavudeenRafiq** [Microsoft/BotBuilder#2328]
Hi,
I have published my bot in my own Azure Server, but I am getting responses randomly. When I publish my bot in Microsoft Azure Web Server using Free Subscription, my bot works fine. Is there anything I have to do with my own Azure Server? Anything I need to install in my own Azure Server?

**Comment by jameslew** [comment]
There shouldn't be anything in specific.  What do you mean by getting responses randomly?

You can configure Azure Application Insights and give the instrumentation key to the Bot Framework (Bot page, edit, paste in instrumentation key).  We'll then log events to your app insights instance that can help you diagnose connectivity problems with your bot.

**Comment by AlavudeenRafiq** [comment]
Hi @jameslew,

Thanks for your response. Getting random responses mean that my Bot can't able to send/recieve messages sometimes. I am getting error in **Directline api(Missing token or secret)**.

I hope that now you understand my issue clearly. Is it only way to configure Azure Application Insights to solve my issue?

**Comment by dandriscoll** [comment]
Hi @AlavudeenRafiq, the "Missing token or secret" error is visible only to your Direct Line (or Web Chat) client. If you're seeing those problems, please make sure your Direct Line secret or token is included in the Authorization header with the Bearer scheme. You can find more details about the Direct Line protocol here: version 3.0: https://docs.botframework.com/en-us/restapi/directline3/#navtitle, version 1.1: https://docs.botframework.com/en-us/restapi/directline/#navtitle

**Comment by nwhitmont** [comment]
Keep in mind Azure Bot Service is still in Preview state -which means it is under active development and some features might not work at all times.
