### ISSUE TITLE
FieldReflector SetValue

### ISSUE THREAD

**Issue by rodzillarr** [Microsoft/BotBuilder#233]
C# / Latest version of the framework

Any insight on how to use the SetValue method on the FieldReflector object?  It seems to want a state object of my type and I'm not sure how to pass that in since this is being called in the static chained FormBuilder BuildForm method and I don't believe I have access to the instance state.  Wasn't able to find any examples and the framework source code didn't seem to provide any help.

Ultimately I'm trying to load values dynamically from a database and provide those as options for user selection in this dialog.

TIA,

-r

**Comment by rodzillarr** [comment]
Nevermind, I figured it out.  Needs to be done in the SetDefine method.  :-)

**Comment by amitger** [comment]
Hi rodzillarr, Can you please share your code as I have stuck in same issue :(
