### ISSUE TITLE
how to trigger another intentDialog

### ISSUE THREAD

**Issue by imshenshen** [Microsoft/BotBuilder#2330]
``` javascript
 intentDialog.matches("askName",[
    function(session){
        builder.Prompts.text(session, "what is you name?");
    },  
    function (session, results, next) {
        if (results.response) {
            session.dialogData.name = results.response;
            session.send('your name is lucy');
        }
        next();
    }
]);
 intentDialog.matches("lucy",function(){
    session.send('something');
})
```

when the bot ask 'what is you name?' , I said 'someWordsTirggerLucyIntent'. I want the bot return 'something', not 'your name is lucy'.
I want the prompts trigger another intentDialog,HOW?

**Comment by Stevenic** [comment]
So I'm trying to understand better what you're wanting to do.  The IntentDialog can only be used to recognize things the user says so what's the conversational flow you'd like?

**Comment by imshenshen** [comment]
@Stevenic sorry for my poor English - -! I use LuisRecognizer.
```javascript
intentDialog.matches("intentA",[
  function(){builder.Prompts.text('i am intentA-waterfall1')} //  this is intentA-waterfall1
  ,function(){} // this is intentA-waterfall2
])
intentDialog.matches("intentB",[
  function(){builder.Prompts.text('i am intentB-waterfall1')} //  this is intentB-waterfall1
  ,function(){} // this is intentB-waterfall2
])
```
User:  'some words trigger intentA'
Bot:    'i am intentA-waterfall1'
User:  'some words that match intentB'    //  this will go to `intentA-waterfall2`, but i want it trigger LuisRecognizer that match intentB and go to `intentB-waterfall1`.

**Comment by Stevenic** [comment]
So for that you could break your waterfalls out into two separate dialogs that use a `triggerAction()` instead of an `IntentDialog`. Example:

```
bot.recognizer(new builder.LuisRecognizer('<luis model>');

bot.dialog('dialogA', [
     function (session) {
          // .. waterfall A
     }
]).triggerAction({ matches: 'IntentA' });

bot.dialog('dialogB', [
     function (session) {
          // .. waterfall B
     }
]).triggerAction({ matches: 'IntentB' });
```

This works very similar to an `IntentDialog` but allows "intents" to interrupt each other. So you could be in the middle of waterfall A and if the user says something to trigger "IntentB" then a new waterfall will be started. It's worth noting that waterfall A would be terminated so there's another way to do it if you don't want that to happen.

**Comment by Stevenic** [comment]
Closing this for now. Please feel free to add further comments.

**Comment by imshenshen** [comment]
`triggerAction` works for me. Thanks!
but how can I combine LuisRecognizer and QnAMakerRecognizer

**Comment by Stevenic** [comment]
You can add multiple recognizers to your bot and we'll compare the scores returned by the recognizers to determine who wins.  You just call `bot.recognizer()` to add each one.

**Comment by imshenshen** [comment]
Yes ,I add two recognizer.
When i entered into a waterfall, i send a message to the Bot ,and the `QnAMakerRecognizer` return with score 1.But the Bot just goto next function of the waterfall. I think the Bot should return the result of QnAMakerRecognizer.
![4321](https://cloud.githubusercontent.com/assets/19701958/23449733/c3317166-fe92-11e6-9831-9e7ec6598c7f.png)

**Comment by palmerabollo** [comment]
@Stevenic is it possible to use a `QnAMakerRecognizer` and default to a secondary `LuisRecognizer` only if it doesn't find a question with a score > threshold? (the plan is to avoid many calls to LUIS and save some bucks).
