### ISSUE TITLE
There was an error sending this message to your bot: HTTP status code InternalServerError

### ISSUE THREAD

**Issue by lonche** [Microsoft/BotBuilder#2332]
Want to use one instance of bot  for multiple bots handling.

I override BotAuthentication method OnActionExecutingAsync.

```
 public class FilterClass: BotAuthentication
    {


        public override async Task OnActionExecutingAsync(HttpActionContext actionContext, CancellationToken cancellationToken)
        {
            
             var pom = actionContext.ActionArguments;
            if (actionContext.Request.RequestUri.AbsoluteUri.ToString().Contains("bot2"))
            {
                MicrosoftAppId = "bot2 id";
                MicrosoftAppPassword = "pass";
                BotClass.BotID = "bot1";
            }
            else if (actionContext.Request.RequestUri.AbsoluteUri.ToString().Contains("bot1"))
            {
                MicrosoftAppId = "bot2 id";
                MicrosoftAppPassword = "pass";
                BotClass.BotID = "bot1";
            }
            else
            {
                MicrosoftAppId = "";
                MicrosoftAppPassword = "";
            }


        }
```

And edit my controller: 

```

 [FilterClass]
    public class MessagesController : ApiController
    {

       
        public async Task<HttpResponseMessage> Post([FromBody]Activity activity)
        {
            if (activity.Type == ActivityTypes.Message)
            {
                try
                {
                    var stateClient = activity.GetStateClient();
                    BotData userData = await stateClient.BotState.GetUserDataAsync(activity.ChannelId, activity.From.Id);
                    userData.SetProperty("ApplicationAccountBotId", BotClass.BotID);
                    await stateClient.BotState.SetUserDataAsync(activity.ChannelId, activity.From.Id, userData);

                    await Conversation.SendAsync(activity, () => new RootDialog());
                }
```

But its not working. It throws an error in botframework dashboard : 

> There was an error sending this message to your bot: HTTP status code InternalServerError

Any idea ?

**Comment by willportnoy** [comment]
I'd run your bot's web service under the debugger, and look for thrown exceptions to help understand the 500 http status code:

https://docs.botframework.com/en-us/technical-faq/#look-for-exceptions

However, since you're using the builder dialog stack, you also need to fix the outgoing authentication calls as well to support "multiple bot in single process" scenarios - for example https://github.com/Microsoft/BotBuilder/issues/2258#issuecomment-280506334

**Comment by lonche** [comment]
I'm using simulator for debugging/testing. There is no exceptions.

**Comment by lonche** [comment]
Btw, i tried this : https://github.com/Microsoft/BotBuilder/issues/2258#issuecomment-280506334

But same exception is thrown. Any idea how to handle multiple bots using one instance ?

**Comment by lonche** [comment]
I used solution you posted. 
When i test it locally, this function : 

```
public Task<bool> IsAuthenticationDisabledAsync()
        {
            return Task.FromResult(!this.Credentials.Any());
        }
```

Should return empty appid and password. But simulator throws an error : 
http://prntscr.com/ecqwly

Why ?

**Comment by rahulsarkar123** [comment]
Hi,

I have created Bots in BotFramework portal and have linked up with BotBuilderSDK and have enabled channels like DirectLine, WebChat. It was working fine till today morning we are getting messages as "Sorry, my bot code is having an issue"..It is not working. Any suggestions?

**Comment by lonche** [comment]
@rahulsarkar123  open new thread and paste your code there.

**Comment by rahulsarkar123** [comment]
created a new thread and have pasted the code

**Comment by willportnoy** [comment]
@lonche are your app ID and password non-empty?

**Comment by lonche** [comment]
They are empty when i use simulator. How to test it properly ?

**Comment by rahulsarkar123** [comment]
The LUIS account trial period got expired, it exceeded 10,000 calls / month, I generated new keys and configured bots.It worked.


Thanks & Regards

Rahul Sarkar

Unique Identity: Emerging Technologies

Accenture

Mobile  : +91 7829306427

Email  : rahul.b.sarkar@accenture.com

________________________________

**Comment by willportnoy** [comment]
@lonche I don't know that the emulator deals well with multiple bot authentication credentials pointing to the same endpoint.  @eanders-MS for visibility.

**Comment by willportnoy** [comment]
@lonche @eanders-MS confirmed in https://github.com/Microsoft/BotBuilder/issues/2352#issuecomment-283803938 that the emulator does not currently support multiple credentials per endpoint.

**Comment by lonche** [comment]
So, how to debug this ? Any idea ?

**Comment by willportnoy** [comment]
Since you can't use the emulator to emulate multiple credentials per endpoint, you can attach your debugger to an instance running in the cloud.

**Comment by lonche** [comment]
Yes. But how to debug that ? Did you try something similar ?

**Comment by arthurtina724** [comment]
@willportnoy for something as simple as context.PostAsync("some message"). Should I be wrapping this code with try/catch to react to a thrown exception? I'm asking because I cannot replicate the 500 errors easily. My bot works fine with the emulator, but once it is deployed in our on prem machines I get these errors inconsistently. I'm thinking I need to catch and log these exceptions somewhere.

**Comment by willportnoy** [comment]
@arthurtina724 that's up to you.  if you don't wrap those calls, they will propagate up the dialog stack.
