### ISSUE TITLE
Direct Line Web chat doesn´t render cards controls.

### ISSUE THREAD

**Issue by jrom20** [Microsoft/BotBuilder#2333]
I was trying to use the Direct Line as an embedded web chat as the follow, https://directline.botframework.com/embed/BOTNAME?s=KEYAPP_FORDIRECTLINE, and it works but when the bot reply options into buttons control it only returns a choose list (Strings), There is any option that I have to enable to render this controls?.

Thanks you in advance.

**Comment by jameslew** [comment]
@jrom20 have you configured your bot to use the new Webchat preview?  If when you edit your bot's "Webchat" control you choose "enable preview" you should see the new features, including card support.

**Comment by jrom20** [comment]
@jameslew Thank you for reply.

Yes, I have configured the 3.0 Preview, and still I'm getting the options as bullet points,

using https://directline.botframework.com/embed/.......
![image](https://cloud.githubusercontent.com/assets/25846426/23289127/522db242-fa0d-11e6-941b-aaed6e85779b.png)

![image](https://cloud.githubusercontent.com/assets/25846426/23289032/cf8d5310-fa0c-11e6-970e-53c983921bcb.png)

if I use https://webchat.botframework.com/embed/.....
I get the nice card render

![image](https://cloud.githubusercontent.com/assets/25846426/23289173/9ae52c7c-fa0d-11e6-9aa2-9c267e4ceb1a.png)

Any other idea to solve this.

**Comment by dandriscoll** [comment]
Hi @jrom20, the URL you are using is not supported. I'm surprised it works.

The correct URL would look like this: https://webchat.botframework.com/embed/BOTNAME?s=KEYAPP_FORWEBCHAT

You can get keys from the Web Chat configuration page within the Bot Framework dev portal.

**Comment by dandriscoll** [comment]
The correct fix for this issue is to update your endpoint. Closing this issue. Please at-mention or open a new issue if you'd like to discuss further.
