### ISSUE TITLE
Unable to install on Slack

### ISSUE THREAD

**Issue by michaeldinsightly** [Microsoft/BotBuilder#2335]
Hi there,

We've ran into an issue where users are unable to install our bot through Slack. When using an existing account, everything works fine. Here is the error that we see:

![image](https://cloud.githubusercontent.com/assets/20196361/23280381/ca9b0c7e-f9cd-11e6-8f8d-2a0ba20ef557.png)

This appears to be a regression, as it was working fine at our original launch.

**Comment by jameslew** [comment]
Can you clarify what you mean by "when you use an existing account"?  You just mean that only adding is broken?

**Comment by michaeldinsightly** [comment]
It's hard to diagnose the problem exactly. When we authorize it with our existing accounts, everything is fine. We have both an enterprise and free Slack account that we use to test.

To recreate the issue, we created a new Slack account under a new email address. We've tried it on free, standard, and plus plans with this new Slack account.

If we invite the new account to a team on our existing accounts, the authentication works when authorizing for that team. But when authorizing for the new account's team, the authorization fails.

We're trying to get more information from our users as to what type of Slack accounts they have, but our only reproduce-able steps so far have come from a new Slack account being created.

Where can we go to see the errors that are occurring on the Bot Framework's side?

I hope this clarifies the issue, let me know if you need more information!

**Comment by jameslew** [comment]
I've verified I can add bots to Slack teams generically, so there must be something specific.  Any possibility you could share your bot handle so we could take a look?  If you're uncomfortable with public, send to BotFramework@microsoft.com and mention @jameslew in the body.

**Comment by jameslew** [comment]
Given I haven't heard any further, I'm going to close this item.
