### ISSUE TITLE
Exception happening in AnnotatedSandwichBot

### ISSUE THREAD

**Issue by ankitbko** [Microsoft/BotBuilder#234]
There is an issue in Annotated Sandwich bot where if you carry on with "No Preference" for Toppings, the form throws exception and the bot shorts circuit. Happens because (value.Contains(ToppingOptions.Everything)) where value is null. Seems to be a bug.

**Comment by chrimc62** [comment]
Thanks for brining this to our attention.  I've fixed the bug and the next release will include the fix.
