### ISSUE TITLE
There was an error sending this message to your bot: HTTP status code InternalServerError

### ISSUE THREAD

**Issue by rahulsarkar123** [Microsoft/BotBuilder#2341]
![httperror](https://cloud.githubusercontent.com/assets/26003233/23302346/6aa78986-fab4-11e6-824b-153ef8ccb6b0.png)
Hi,

I have created Bots in BotFramework portal and have linked up with BotBuilderSDK and have enabled channels like DirectLine, WebChat. It was working fine till today morning we are getting messages as "Sorry, my bot code is having an issue"..It is not working. Any suggestions?..In the error list of DirectLine it is showing as "There was an error sending this message to your bot: HTTP status code InternalServerError"..

Code:

public class MessagesController : ApiController
    {

       
       
        internal static IDialog<CathyFormDialog> MakeRootDialog()
        {
            return Chain.From(() => FormDialog.FromForm(CathyFormDialog.BuildForm));
        }

        /// <summary>
        /// POST: api/Messages
        /// Receive a message from a user and reply to it
        /// </summary>
        /// 
        [ResponseType(typeof(void))]
        public async Task<HttpResponseMessage> Post([FromBody]Activity activity)
        {
            if(activity !=null)
            {
                switch (activity.GetActivityType())
                {
                    case ActivityTypes.Message:

                       

                      
                       await Conversation.SendAsync(activity, () => new TrygBot.TrygDialog());

                        

                        break;
                    case ActivityTypes.ConversationUpdate:
                    case ActivityTypes.ContactRelationUpdate:
                    case ActivityTypes.Typing:
                    case ActivityTypes.DeleteUserData:
                    default:
                        Trace.TraceError($"Unknown activity type ignored: {activity.GetActivityType()}");
                        break;
                }
            }
 
![botframeworkerror](https://cloud.githubusercontent.com/assets/26003233/23301905/42c0c4c0-fab2-11e6-907d-d8098056b90f.png)

![httperror](https://cloud.githubusercontent.com/assets/26003233/23302367/771f0c98-fab4-11e6-9cdd-41cc4e28dcc6.png)

**Comment by lonche** [comment]
It looks like that your bot is not authorized. What about your webconfig ?

**Comment by rahulsarkar123** [comment]
No..It is working fine till last night..from today morning onwards i am getting  this response.
I think there is some issue with the BotFramework server. Can you please check and let me know?
Here is the webconfig code:

WebConfig:  


<?xml version="1.0" encoding="utf-8"?>

<configuration>
  <configSections>
    
    <section name="entityFramework" type="System.Data.Entity.Internal.ConfigFile.EntityFrameworkSection, EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />
  </configSections>
  <appSettings>
    
    <add key="BotId" value="YourBotId" />
    <add key="MicrosoftAppId" value="b74956fb-8058-41c4-a40a-5f6e53318e85" />
    <add key="MicrosoftAppPassword" value="DboHbJBHhhNJcChtZOKoLZW" />
 
    
  </appSettings>
  
  <system.web>
    <customErrors mode="Off" />
    <compilation debug="true" targetFramework="4.6" />
    <httpRuntime targetFramework="4.6" />
  <sessionState timeout="360"></sessionState>
  </system.web>
 
  <system.webServer>
    <defaultDocument>
      <files>
        <clear />
        <add value="default.htm" />
      </files>
    </defaultDocument>
    <handlers>
      <remove name="ExtensionlessUrlHandler-Integrated-4.0" />
      <remove name="OPTIONSVerbHandler" />
      <remove name="TRACEVerbHandler" />
      <add name="ExtensionlessUrlHandler-Integrated-4.0" path="*." verb="*" type="System.Web.Handlers.TransferRequestHandler" preCondition="integratedMode,runtimeVersionv4.0" />
    </handlers>
  <directoryBrowse enabled="true" />
  </system.webServer>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Web.Helpers" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="1.0.0.0-3.0.0.0" newVersion="3.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Web.Mvc" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="1.0.0.0-5.2.3.0" newVersion="5.2.3.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Web.WebPages" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="1.0.0.0-3.0.0.0" newVersion="3.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-8.0.0.0" newVersion="8.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Net.Http.Primitives" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.2.29.0" newVersion="4.2.29.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Net.Http.Formatting" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.2.3.0" newVersion="5.2.3.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Npgsql" publicKeyToken="5d8b90d52f46fda7" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.1.7.0" newVersion="3.1.7.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
  <entityFramework>
    <defaultConnectionFactory type="System.Data.Entity.Infrastructure.LocalDbConnectionFactory, EntityFramework">
      <parameters>
        <parameter value="v12.0" />
      </parameters>
    </defaultConnectionFactory>
    <providers>
      <provider invariantName="System.Data.SqlClient" type="System.Data.Entity.SqlServer.SqlProviderServices, EntityFramework.SqlServer" />
      <provider invariantName="Npgsql" type="Npgsql.NpgsqlServices, EntityFramework6.Npgsql" />
    </providers>
  </entityFramework>



</configuration>
           
           
            return new HttpResponseMessage(System.Net.HttpStatusCode.Accepted);
    }

**Comment by PrasadHonrao** [comment]
I am facing same issue as well

![image](https://cloud.githubusercontent.com/assets/1454174/23327656/d9c45552-fb35-11e6-9174-4ad3406c4e11.png)

**Comment by rahulsarkar123** [comment]
Thanks the issue is resolved now. I resolved it.


Thanks & Regards

Rahul Sarkar

Unique Identity: Emerging Technologies

Accenture

Mobile  : +91 7829306427

Email  : rahul.b.sarkar@accenture.com

________________________________

**Comment by PrasadHonrao** [comment]
@rahulsarkar123 Great! Can you provide details on the root cause of the problem and the solution?

**Comment by andrehe001** [comment]
@rahulsarkar123, 'm having the same issue and it would be great, if you could let us know how you solved it.

**Comment by rahulsarkar123** [comment]
The LUIS account trial period got expired, it exceeded 10,000 calls / month, I generated new keys and configured bots.It worked.

**Comment by rahulsarkar123** [comment]
The LUIS account trial period got expired, it exceeded 10,000 calls / month, I generated new keys and configured bots.It worked.


Thanks & Regards

Rahul Sarkar

Unique Identity: Emerging Technologies

Accenture

Mobile  : +91 7829306427

Email  : rahul.b.sarkar@accenture.com

________________________________

**Comment by stelazh** [comment]
can you please help me ...i regenerate another key ..and still i have this problem
