### ISSUE TITLE
Telegram proactive bot not working

### ISSUE THREAD

**Issue by kkarahainko** [Microsoft/BotBuilder#2347]
Trying to send message to Telegram from a Worker Role:

> Microsoft.Rest.HttpOperationException: Unknown botId at Microsoft.Bot.Connector.ErrorHandling.d__2`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Bot.Connector.ConversationsExtensions.d__7.MoveNext()

**Comment by willportnoy** [comment]
You might consider going through the steps at

https://docs.botframework.com/en-us/technical-faq/#how-can-i-troubleshoot-my-bots-authentication

Are you initializing the ConnectorClient with the proper MicrosoftAppCredentials?

**Comment by kkarahainko** [comment]
Thanks for reply, I use ResumptionCookie. It works fine for Slack and
Skype, but raising Unknown Bot for Telegram. Looks like broken cookie,
wrong bot id.

27 Фев 2017 г. 3:31 пользователь "Will Portnoy" <notifications@github.com>
написал:

**Comment by willportnoy** [comment]
Did you configure your bot for the telegram channel?

**Comment by eanders-MS** [comment]
@kkarahainko, @willportnoy This is a known issue in our Telegram channel. We have a fix incoming, but it isn't ready yet. This issue is also tracking it: https://github.com/Microsoft/BotBuilder/issues/1983

**Comment by chris31389** [comment]
@eanders-MS Did this ever get fixed?

**Comment by Lafannn** [comment]
This error occurs if you only specify the Id "new Channelaccount (botId)" If you add the name "New Channelaccount (botId, botName)", everything will work

**Comment by eanders-MS** [comment]
@chris31389 this work is booked but not yet scheduled. @Lafannn thank you for posting your workaround!

**Comment by castillolj** [comment]
Is this problem resolved?.
