### ISSUE TITLE
All channels except webapp are not allowing other people to communicate with the bot

### ISSUE THREAD

**Issue by endareBrock** [Microsoft/BotBuilder#2351]
When somebody else then me tries to converse with the bot it constantly throws errors. 
My feed looks like this when messages are retrieved
![image](https://cloud.githubusercontent.com/assets/25737301/23356640/eb89850e-fcda-11e6-8ee0-a26d8325d3d7.png)

Same story with skype. But the error messages link to trafficmanager instead.
Can it be that my bot needs to be published for other users to communicate?

**Comment by nwhitmont** [comment]
@endareBrock Are you still experiencing the issue?  There have been a lot of updates to BotBuilder SDK in the past few months so maybe it's been resolved?  reopen if you're still having problems and let us know if you're using C# or Node SDK. thx
