### ISSUE TITLE
There was an error sending this message to your bot: HTTP status code InternalServerError

### ISSUE THREAD

**Issue by lonche** [Microsoft/BotBuilder#2352]
I found this : 
http://stackoverflow.com/questions/42488700/bot-does-not-respond-to-messages
but i have the same issue. 

Any help ?

**Comment by willportnoy** [comment]
https://github.com/Microsoft/BotBuilder/issues/2258#issuecomment-280506334 might help - you need to configure authentication for outgoing messages too.

In addition, when you see a http server error 500, you should attach your debugger to find the exception.

**Comment by lonche** [comment]
It works properly when i'm using one user. I can not start botframework simulator twice  ... any idea ?

**Comment by willportnoy** [comment]
I don't think the emulator supports multiple bot authentication credentials for the same bot web service endpoint.  is that right @eanders-MS ?

**Comment by eanders-MS** [comment]
@lonche Can you provide a url to the docs you're quoting? I'm concerned it might be incorrect and would like to fix or clarify it.

@willportnoy It is a limitation of the emulator UI that you can't assign multiple sets of credentials for a single endpoint. As a work around, use multiple entries of the same endpoint, and add a distinguishing query parameter to each, like this:
`http://locahost:3978/api/messages?bot1`
`http://locahost:3978/api/messages?bot2`
etc.

**Comment by lonche** [comment]
Mhm. 
I used :  

> http://locahost:3978/api/bot1/messages

 and
 `http://locahost:3978/api/bot2/messages.`

I'l try your solution. Thanks.

**Comment by carlosscastro** [comment]
@lonche did that work for you? Are you still experiencing this issue, or could you fix it?

**Comment by lonche** [comment]
No, i didn't fix that. What about you ?

**Comment by Kadae** [comment]
Damn. This is closed again.
