### ISSUE TITLE
Slack Channel for Bot Framework Help / Issues?

### ISSUE THREAD

**Issue by AmitBhatnagar24** [Microsoft/BotBuilder#2353]
Is there a community Slack channel for support / discussions on the bot framework ? 

The ASP.NET / Dotnet slack team doesn't have a botframework channel.. but microsoft-community.slack.com does.. 

It would be nice to be able to chat among bot developers.

**Comment by carlosscastro** [comment]
@AmitBhatnagar24 I don't know of any community. When you post a slack specific question here, other slack users may chime in. Let us know if you hear about any community!

**Comment by carlosscastro** [comment]
Closing the issue, but feel free to reopen if you have follow ups!

**Comment by carlosscastro** [comment]
Also, StackOverflow may be a good place to ask questions and exchange ideas with other fellow bot developers. The Bot Framework team also monitors StackOverflow to provide support.
