### ISSUE TITLE
Bot in review since 2 weeks

### ISSUE THREAD

**Issue by RoDanger** [Microsoft/BotBuilder#2354]
Hi Microsoft Bot Team,

How long does a bot review take? We have a bot (id=bot-ufeseattle) submitted in review 2 weeks ago (Sunday 2/12), still no sign of any progress on the botframework.com page...

**Comment by Andrea-Orimoto** [comment]
@RoDanger, it looks like your bot has been approved today, congrats!. Feel free to reopen this issue if you still have questions or issues. thanks!
