### ISSUE TITLE
Telegram Channel Add Error

### ISSUE THREAD

**Issue by akadelpher** [Microsoft/BotBuilder#2355]
When I enter telegram Access Token and press submit a runtime error occurs.

![default](https://cloud.githubusercontent.com/assets/25675554/23383314/d0d9be6c-fd80-11e6-8a67-16c87ec0f857.PNG)

**Comment by dusterherz** [comment]
+1, I have the exact same error.

**Comment by akadelpher** [comment]
it seems fixed
