### ISSUE TITLE
[Question] How to Transition to new DialogStack in the middle of a FormDialog?

### ISSUE THREAD

**Issue by wbreza** [Microsoft/BotBuilder#2356]
I have a JSON FormDialog that is configured with all the relevant questions for the current topic.  I need to figure out a way to switch context's in the middle of a FormDialog and return to where I was when I complete the nested task.

Example: Say I'm building a Pizza bot and 1/2 through completing my order I ask the bot another unrelated query like "what's the status of my previous order?".  

At this point I would like to invoke a new Dialog, complete it, then return to finishing my pizza order.

I don't believe I can .Forward() or .Call() a new dialog from the middle of a FormDialog.  I've attempted to use the newish DialogTaskManager to create a new DialogTask that has its own DialogStack.  At this point I end up with multiple state keys like DialogState, DialogState1, DialogState2, etc. which seems desired in this case.

I'm able to then invoke the correct DialogTask but it feels a bit hacky.  I don't see a way to remove a DialogTask from the DialogTaskManager when I am done.

Is there a better way?  I've looked into Scoreables, Child Dialogs but neither seem to help in this situation.  I would also need to support switching from 1 FormDialog to another completely different FormDialog and back again.

Any suggestions? I'm using the C# SDK.

**Comment by willportnoy** [comment]
I think you're on the right path - here is an example of interrupting the current dialog stack to call a "calculator dialog":

https://github.com/Microsoft/BotBuilder/blob/497252e8d9949be20baa2cebaa6ce56de04461cf/CSharp/Tests/Microsoft.Bot.Builder.Tests/ScorableDialogTests.cs#L367

As long as you just want to interrupt the FormFlow dialog with some child dialog, and then continue with that child dialog until its done, and then resume the interrupted dialog, you're fine.

However, if you want to override how FormFlow collects information, it's not quite as simple and doesn't compose with other dialogs as well right now.

**Comment by wbreza** [comment]
After I do interrupt the DialogStack - is there a way to have the FormDialog resume and re-ask the last question in the event the interruption was a multi-step process without having the user remember the last question or scroll back up?

User: Order a pizza
Bot: What toppings do you want on your pizza?
User: What did I order last time?
... Finish the interrupting dialog
... Resumes form dialog
Bot: What toppings do you want on your pizza?

**Comment by willportnoy** [comment]
I don't think there's a good option - FormFlow isn't quite as composable with the rest of the dialog system.

We have some sample code for showing a resumption message when returning to an interrupted dialog, but it won't help your poke FormDialog to generate the right response.

https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Tests/Microsoft.Bot.Builder.Tests/BotTests.cs#L224

You might be able to fake it somehow by sending an empty message to the FormDialog when resuming it, but I have not tried that before.
