### ISSUE TITLE
LUIS unable to deserialize response

### ISSUE THREAD

**Issue by angsm** [Microsoft/BotBuilder#2360]
Hi, I encountered this bug:

{
    "message": "An error has occurred.",
    "exceptionMessage": "Unable to deserialize the LUIS response.",
    "exceptionType": "System.ArgumentException",
    "stackTrace": "   at Microsoft.Bot.Builder.Luis.LuisService.<Microsoft-Bot-Builder-Luis-ILuisService-QueryAsync>d__4.MoveNext()\r\n---

It was working fine 2 days ago, does anyone have any idea why?

Thank you.

**Comment by angsm** [comment]
I just tried a simple example from:

https://code.msdn.microsoft.com/LUIS-Language-Understanding-acf9720a

It had the same error too, "An exception happened: One or more errors occurred. with an inner exception of: Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: M. Path '', line 0, position 0."

**Comment by angsm** [comment]
I found the solution, it was due to the baseURI of LUIS call being incorrect. This can be resolved by updating the botbuilder package in NuGet package manager.

After the update, the format of the baseURI has been changed from 

/luis/v1/application?id={id}&subscription-key={subscriptionKey}&q={question}

to 

/luis/v2.0/apps/{id}?subscription-key={subscriptionKey}&q=question}

**Comment by J3QQ4** [comment]
That happened for me when I was trying to call the built-in LUIS app (the one that does Cortana-like functions) using Bot Builder v.3.3.0. 

When I removed that LuisModel, the error ceased.
