### ISSUE TITLE
New Channel -- RocketChat

### ISSUE THREAD

**Issue by forensicsguy20012004** [Microsoft/BotBuilder#2363]
Can we get a RocketChat channel, the company I work for is moving to RocketChat.

**Comment by forensicsguy20012004** [comment]
Thank you for the "enhancement" label. It is much appreciated.

**Comment by Andrea-Orimoto** [comment]
Hi @forensicsguy20012004, there is no plan for this at the moment, but we've added it to our backlog for future consideration. Closing this issue since it's captured in our backlog, feel free to reopen if you have more questions. Thanks a lot.
