### ISSUE TITLE
Best practices for integrating Dialogs with existing APIs / applications

### ISSUE THREAD

**Issue by wbreza** [Microsoft/BotBuilder#2365]
I keep running into various serialization issues when attempting to integrate new Bot Framework Dialogs with my existing APIs and applications.  

I understand the concept of making all the Dialogs Serializable, but how can I make my other code play nice **without** requiring `[Serializable]` attributes down through the whole stack?  

**Example:**
1. Create a basic Dialog Chain with callbacks to cause a side effect in my own application using

```
Chain
    .From(() => new PizzaOrderDialog())
    .Do(async (ctx, result) => {
        var pizzaOrder = await result;
        this.pizzaService.Save(pizzaOrder)
    });
```

In the above example I want to take results from dialogs and store it in my own database.  If you were to modify the Pizza Bot for example and plug in the real code to persist it back to a database or other service where would it go? What are the best practices for writing something similar to the above

The `PizzaService` or containing business logic class isn't serializable and I don't think there should be a requirement to make it so.

Thanks in advance.

**Comment by willportnoy** [comment]
https://docs.botframework.com/en-us/technical-faq/#how-can-i-reference-non-serializable-services-from-my-c-dialogs has some suggestions - happy to discuss more.

**Comment by carlosscastro** [comment]
@wbreza Did the documentation that @willportnoy referenced help you? Could you solve this issue?

**Comment by wbreza** [comment]
I understand the gotcha's and I'm not completely happy about the hoops that are required to jump through.  I do have a hacky workround in place but I would urge you guys to figure out a more elegant solution.  

It sounds like the Node side of the SDK uses a JSON serializer by default which could be a more lightweight solution here as well.

**Comment by carlosscastro** [comment]
@wbreza feel free to share what your hacky workarounds are here - @willportnoy and I can see if we can help get your code be more elegant if it is possible. Seeing the specific hacks you needed to do might also help us understand how to improve the SDK moving forward :)
