### ISSUE TITLE
Unable to store userData in session

### ISSUE THREAD

**Issue by kaushik-sundar** [Microsoft/BotBuilder#2367]
I am using Node. I am trying to store the user profile information inside session.userData. I am unable to access it in other dialogs. Storing in session.userData will it work only for Dialogs and not IntentDialogs? Is there any alternative?

**Comment by willportnoy** [comment]
That UserData should be available in all dialogs - is it the same user on the same channel with the same bot?

**Comment by kaushik-sundar** [comment]
Yes it is all the same. The conversation id is the same.

**Comment by pveller** [comment]
In 3.3 I got used to explicitly calling `session.save()` after each change to `userData` or `dialogData`

**Comment by kaushik-sundar** [comment]
It worked. I haven't seen the session.save() in the docs. Thanks

**Comment by willportnoy** [comment]
I'm happy to hear you were able to resolve the issue - I'm going to close it for now.
