### ISSUE TITLE
Dialogues dont support multiple utterances at one go

### ISSUE THREAD

**Issue by ubreddy** [Microsoft/BotBuilder#2368]
In natural usage of Bot, it is likely that user would chat in multiple broken utterances.

e.g.
bot: what do your opinion on Soccer?
user: a. hmm
b. let me think.
c. I think it is the best game ever.
d...
The issue is the Dialog reacts immediately after a is uttered. There should be a way to debounce before bot can get to react.
Can this be solved in current botbuilder?

**Comment by willportnoy** [comment]
You can add a child "prompt" dialog that "de-bounces" input to combine multiple inputs in whatever you want, and use that to collect the next complete utterance from the user.  Of if you just want to ignore certain inputs, you can likely intercept them with a scorable and don't forward them on to the dialog stack.

**Comment by ubreddy** [comment]
Scorable? Didnt here this earlier. Is there some documentation on this?Child prompt to debounce. I am clueless. Can you please elaborate or point me to an example?On 03-Mar-2017 1:00 AM, Will Portnoy <notifications@github.com> wrote:You can add a child "prompt" dialog that "de-bounces" input to combine multiple inputs in whatever you want, and use that to collect the next complete utterance from the user.  Of if you just want to ignore certain inputs, you can likely intercept them with a scorable and don't forward them on to the dialog stack.

**Comment by ubreddy** [comment]
Any update on this?
There are two types of listeners in botframework
one to the root dialog / where luis handler is attached to.
another is Prompts where an input from user is sought.

in both occassions. it is possible that user enters the inputs in a series of utterances and not necessarily only one. 

how can Prompts in botbuilder collect in debounce pattern, esp when in middle of seeking inputs from user? and how can these be directed to luis while in middle of dialog?

e.g.
1. 
bot: please enter your name
user: 1 sec
user: ok, it is Smith.

2. bot: fetching the details from server... 
( 5 sec pause makes user lose patience)
user: u there?
This should not break the current dialog.

3. bot: what was your experience?
user: well, where shall I begin?
user: it was kind of ok, but...
user: not very good..
user: but would recommend

the prompts should be able to collect these before reacting to each input...

**Comment by willportnoy** [comment]
You can make an implementation of IDialog (call it the "debounce dialog") that concatenates user input spread across multiple utterances until you feel the concatenated user input is "done", and then you can return that concatenated user input to the caller of the dialog.

**Comment by carlosscastro** [comment]
@ubreddy Did you try @willportnoy's suggestion? Let us know if you had issues with that.

**Comment by ubreddy** [comment]
no. I havent. Not sure the design is fully understood yet. Do you have some more suggestions. Uday 

    On Saturday, 11 March 2017 12:54 AM, Carlos Castro <notifications@github.com> wrote:
 

 @ubreddy Did you try @willportnoy's suggestion? Let us know if you had issues with that.—

**Comment by carlosscastro** [comment]
The suggestion from @willportnoy is the best for this scenario in my opinion. Please give it a try. Let us know if that works!
