### ISSUE TITLE
Are only image attachments supported in Skype channel?

### ISSUE THREAD

**Issue by irwinwilliams** [Microsoft/BotBuilder#2369]
Hi,
I'm trying to send an attachment to my users. It's a proactive notification, where I'm including a PDF. 
When I do, I get a HTTP Bad Request, pointing to a traffic manager URL. 
Is this expected behavior? If so, shouldn't your documentation say so? Same message sent via email channel works as expected.

**Comment by nickcordrey** [comment]
Skype doesn't support file attachments today - it is something we have in the backlog. For documentation I'll discuss with the bot framework team how to better articulate the capabilities of each channel.
