### ISSUE TITLE
context.MakeMessage() does not set message.To.Id when running in the Emulator

### ISSUE THREAD

**Issue by jakobpn** [Microsoft/BotBuilder#237]
message.To.Address is set (to User1), but message.To.Id is null.

This happen both when running in the emulator and outside the emulator.

**Comment by willportnoy** [comment]
Thank you for the report - I'll submit a code review to get it fixed.

**Comment by willportnoy** [comment]
I've submitted this code fix - it will be included in the next connector nuget package release.

**Comment by jakobpn** [comment]
Nice!

**Comment by ejadib** [comment]
@willportnoy do you know when the next connector nuget package will be released?
