### ISSUE TITLE
local timestamp of a message from Skype not available

### ISSUE THREAD

**Issue by sharmadine** [Microsoft/BotBuilder#2371]
In Emulator - `session.message.localTimestamp` property returns correct local timestamp of the message. But the same property is returning 'invalid date' when deployed on Azure and accessed from Skype or Bot web test control. 

Debugging Node.js code in VS Code gave a few ways (below) but none of them are working on Azure + Skype.

1.  `session.message.localTimestamp` **<=** works in emulator but not in Azure+Skype where it returns `undefined`

2. `session.domain.members['0'].body.localTimestamp` - a way to extract the value from request body **<=** works in emulator but not in Azure+Skype where it returns `undefined`

**What is the best & consistent way to retrieve user's / message's local timestamp across all bot channels?**

**Comment by nickcordrey** [comment]
Unfortunately not all Skype versions send local timestamp.
