### ISSUE TITLE
[Feature Request] Facebook graph api access or at least access to the page access token 

### ISSUE THREAD

**Issue by bmperrea** [Microsoft/BotBuilder#2375]
It would be nice to support access to the whole [facebook graph api](https://developers.facebook.com/docs/graph-api). Managing page_access tokens ourselves seems to undermine the purpose of the connector. A special case of this is access to the first name as in #1908.

**Comment by bmperrea** [comment]
I think the easiest solution would be to give the developer access to the page access token somehow.

**Comment by bmperrea** [comment]
For now I'm getting permanent access tokens by using the webapp here and clicking on Debug for the specific app I need it for. https://developers.facebook.com/tools/accesstoken/

**Comment by nwhitmont** [comment]
@bmperrea are you using C# or Node SDK for BotBuilder?

**Comment by sgellock** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botbuilder-channels/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
