### ISSUE TITLE
How to show loading animation in web control channel.

### ISSUE THREAD

**Issue by amolghanwat2020** [Microsoft/BotBuilder#2378]
How to show loading animation image until response get from chatbot when user send request to chatbot in web control channel using direct line api?
Which java script event used to handle request and response to set loading animation?

For example when user type and send "Hello" to bot in web control then start loading image below "Hello" in web control and stop loading image when get response from chatbot and replace image with response.

**Comment by willportnoy** [comment]
@danmarshall @eanders-MS do you know?

**Comment by danmarshall** [comment]
Hi @amolghanwat2020 do you mean the "is typing" feature?
see https://github.com/Microsoft/BotBuilder/issues/164

**Comment by danmarshall** [comment]
Hi @amolghanwat2020 , please see the "typing" feature in my previous comment. I am going to close this issue for now, please reopen if your issue is not resolved.

**Comment by sridharbm1991** [comment]
@danmarshall  typing activity is not working in Web chat channel any alternative?

**Comment by danmarshall** [comment]
Hi @sridharbm1991 the `typing` feature requires websockets, which are not turned on in the WebChat channel. However, you can enable them if you [host your own WebChat page](https://github.com/Microsoft/BotFramework-WebChat#websocket).
