### ISSUE TITLE
Image attachments not showing up in Facebook Messenger

### ISSUE THREAD

**Issue by jakobpn** [Microsoft/BotBuilder#238]
They show up in the emulator, WebChat and in Skype, but not in Facebook Messenger. Is image attachments not supported by Messenger or is a particular property I should set?

I'm setting ContentType = "image/png" and ContentUrl on the attachment.

**Comment by tomlm** [comment]
can you send sample JSON data, this works for me.

**Comment by msft-shahins** [comment]
@jakobpn do you still have this issue? This [sampe](https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Samples/EchoBot/EchoAttachmentDialog.cs) shows how to reply back with Image attachments.

**Comment by jakobpn** [comment]
Thanks for providing a link to the sample, Tom. I think the issue that I was running into was related to spaces in the ContentUrl. Once I replaced the spaces with %20 the image attachments started coming through just fine.
