### ISSUE TITLE
Ending conversation anytime with the word “Cancel” in C#

### ISSUE THREAD

**Issue by fercom** [Microsoft/BotBuilder#2381]
I want my bot to stop whatever it is doing when the user sends a key word like "cancel" or "menu".

My question is similar to this one : [http://stackoverflow.com/questions/37233307/ending-conversation](url) but that works only on node.js, I am working with c#. Any ideas?

**Comment by willportnoy** [comment]
you might consider something like this CancelScorable:

https://github.com/Microsoft/BotBuilder/blob/497252e8d9949be20baa2cebaa6ce56de04461cf/CSharp/Tests/Microsoft.Bot.Builder.Tests/ScorableDialogTests.cs#L100

**Comment by carlosscastro** [comment]
Hello @fercom, 

Did the answer from @willportnoy work for you?

**Comment by fercom** [comment]
@carlosscastro No, I used some other code

**Comment by lihka1** [comment]
@fercom I have tried using CancelScorable and it is not working.

Can you please tell how you implemented it?
