### ISSUE TITLE
[Feature Request] Channel specific action (response) types for Prompts.choice

### ISSUE THREAD

**Issue by enby** [Microsoft/BotBuilder#2389]
As of right now, Prompts.choice accepts a list of suggested responses that the user can choose. However, this limits the functionality on Kik (maybe some other channels too). Kik has support for 3 types of suggested response: `text, friend-picker, picture`. I think there should be a way to create a prompt that could be customized based on the channel, allowing the developer to choose what type of buttons to present.

Possible solutions:
1. Expose the message object for the Prompts.choice, so that "sourceEvent" can be set before the prompt is sent. This is messy but better than nothing
2. Allow adding buttons (responses) specific to the channel (something like: `setButtons("*":[b1, b2, b3], "kik":[b4])`. Where b1-4 could be configurable buttons

I realize that prompts can be implemented using a regular dialog (and hence easy to customize based on the platform), but then we lose the awesome convenience of the built in prompts that handle recognition and retries etc.

Were there any plans for something like this? Or am I missing an easy way to achieve this? I've examined the Prompts code, however couldn't find an easy way to update the outgoing message to include custom keyboard types.

**Comment by Stevenic** [comment]
Adding Tom to comment on ability to pass through platform specific action types like "friend-picker" and "picture"

**Comment by sgellock** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botbuilder-channels/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
