### ISSUE TITLE
SMS channel seems to have stopped working

### ISSUE THREAD

**Issue by rodzillarr** [Microsoft/BotBuilder#239]
C# - latest version of the framework (was previously working in this version)

Works fine in the portal test chat box and also via the emulator pointed to the live URL.  However, SMS via Twilio which has been working for weeks all of a sudden now responds only with:

`Sent from your Twilio Trial account - _Sorry, -my bot name- is having a problem responding right now._`

Any ideas?

TIA,
-r

**Comment by craigjensen** [comment]
Are you still seeing this issue?  If so, please add your botId (or email it to bf-reports@microsoft.com) and we'll look in our logs and see if we can determine the cause.

**Comment by rodzillarr** [comment]
Thanks I sent my bot id to the email address you provided.  It is still occurring.  I tried removing the channel and recreating it with my twilio details and it still occurred.  I should mention that even when it was working I regularly got emailed error reports from Twilio such as the one below:

Notification SID
NOed54288900706a12ffcb215e34846b43
Error
11200 HTTP retrieval failure
Description
An attempt to retrieve content from https://sms.botframework.com/api/sms returned the HTTP status code .

**Comment by rodzillarr** [comment]
Thanks for your assistance with this.  Sending /deleteprofile to the framework and clearing my profile data seems to have resolved this.

-r

**Comment by DavidJBarnes** [comment]
I am experiencing the same issue with just Twilio. Using nodejs and botbuilder v3.8.0.
