### ISSUE TITLE
"invalid token. Check bot's app ID & Password" with correct setting

### ISSUE THREAD

**Issue by astrung** [Microsoft/BotBuilder#2390]
this is my code : 

    var connector = new builder.ChatConnector(config.botConnector);
    console.log(connector);
    var bot = new builder.UniversalBot(connector, {
       localizerSettings: {
       defaultLocale: "en"}
    });

and this is my config : 

    config.botConnector.appId = "hidden";
    config.botConnector.appPassword = "hidden";

Everything works well on windows. But when i push this commit to ec2 server, it always send this error : `receive - invalid token. Check bot's app ID & Password.` .But i set it correctly. This is my log about connector on server : 

    ChatConnector {
     settings:
        { appId: 'hidden',
        appPassword: 'hidden',
        endpoint:
           { refreshEndpoint: 'https://login.microsoftonline.com/common/oauth2/v2.0/token',
           refreshScope: 'https://graph.microsoft.com/.default',
           botConnectorOpenIdMetadata: 'https://api.aps.skype.com/v1/.well-known/openidconfiguration',
           botConnectorIssuer: 'https://api.botframework.com',
           botConnectorAudience: '87379ca7-5bee-4118-a61f-b36d0e4a4190',
           msaOpenIdMetadata: 'https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration',
           msaIssuer: 'https://sts.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47/',
           msaAudience: 'https://graph.microsoft.com',
           stateEndpoint: 'https://state.botframework.com' } },
     botConnectorOpenIdMetadata:
        OpenIdMetadata {
          lastUpdated: 0,
          url: 'https://api.aps.skype.com/v1/.well-known/openidconfiguration' },
     msaOpenIdMetadata:
        OpenIdMetadata {
          lastUpdated: 0,
          url: 'https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration' } }

Pls help. I can not identify my problem. I hide my app id and password, but if you need , i will give it to you

**Comment by astrung** [comment]
This is log from Bot Connector : 


    bot-154 token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IkdDeEFyWG9OOFNxbzdQd2VBNy16NjVkZW5KUSIsIng1dCI6IkdDeEFyWG9OOFNxbzdQd2VBNy16NjVkZW5KUSJ9.eyJpc3MiOiJodHRwczovL2FwaS5ib3RmcmFtZXdvcmsuY29tIiwiYXVkIjoiODczNzljYTctNWJlZS00MTE4LWE2MWYtYjM2ZDBlNGE0MTkwIiwiZXhwIjoxNDg4Njg3OTYzLCJuYmYiOjE0ODg2ODczNjN9.oSViKXZe5EFcpR29JR0MA887iVyjK6YzxOM2UEb2Hy-3tNogdJcbFQmBoRa2t4y_iQ9E93kcKJcit5Zxc3fySHdnaIjrjlZjDiXRCKIX9macQUArQuWI5Nq8b2eRHLI4jZ0YTmpWNXxmCybFrhHHwr4jZGXTRS7rMy_KVw1Tq110w0xPEeGoAuy2J5PaxwRCEfjBjV3-bZ0GFsjGksIHwc30_7UHghmVA76fN-zMcLYs__DGMbmj4YSeh2UnjjNiKLm3sWb0SjT9QEAay9hQ4WUx17ELPmgtX6gDGctxNYNG2cyGhLn4xgRj9c5V152U-ffNTQSwA5SQajBWWt5SqQ
    bot-154 key: -----BEGIN RSA PUBLIC KEY-----
      bot-154 MIIBCgKCAQEAuknv8y+QkKiiyc/MecJ1o4JE/5Fz94m1/y4r9+pKmyIMZI3Lx3G+
    bot-154 pyWQzjS0UkpVB0+ujRKrvlMXPJT0npQM1hhbkHZThmHarcXXk84nqq7ZTZavwWVX
    bot-154 jFZTh3CAY5cU65mTivc8j2Sn3u6fP/Mp4E/kyTko0PDPvRh6pum4c1/DSxC5Rg53
    bot-154 iJ1C3r4aaTznZ0yCRw8u+AvV/5JCbPDoCH0aFAWWVB2xN9KHmkAy16ucT3KRhu74
    bot-154 IQVATuSGSK59aqp4ZlcHgu/tGqEpt/uN2Qm0W6c8gI+2V6JTCTql8uet1jS6Fuuq
    bot-154 Xzx325LTSslRJ3CjJ7uP0LOgZbnhBI96xQIDAQAB
    bot-154 -----END RSA PUBLIC KEY-----
      bot-154 { issuer: 'https://api.botframework.com',
    bot-154   audience: '87379ca7-5bee-4118-a61f-b36d0e4a4190',
    bot-154   clockTolerance: 300 }
    bot-154 clockTimestamp
    bot-154 1488712587
    bot-154 compared with
    bot-154 1488688263
    bot-154 ERROR: ChatConnector: receive - invalid token. Check bot's app ID & Password.
    bot-154 { TokenExpiredError: jwt expired
      bot-154     at Object.module.exports [as verify] (/home/ubuntu/TalentWasabi_Bot/node_modules/jsonwebtoken/verify.js:135:19)
      bot-154     at /home/ubuntu/TalentWasabi_Bot/node_modules/botbuilder/lib/bots/ChatConnector.js:106:29
      bot-154     at /home/ubuntu/TalentWasabi_Bot/node_modules/botbuilder/lib/bots/OpenIdMetadata.js:20:17
      bot-154     at Request._callback (/home/ubuntu/TalentWasabi_Bot/node_modules/botbuilder/lib/bots/OpenIdMetadata.js:57:21)
      bot-154     at Request.self.callback (/home/ubuntu/TalentWasabi_Bot/node_modules/request/request.js:187:22)
      bot-154     at emitTwo (events.js:106:13)
      bot-154     at Request.emit (events.js:191:7)
      bot-154     at Request.<anonymous> (/home/ubuntu/TalentWasabi_Bot/node_modules/request/request.js:1126:10)
      bot-154     at emitOne (events.js:96:13)
      bot-154     at Request.emit (events.js:188:7)
      bot-154     at IncomingMessage.<anonymous> (/home/ubuntu/TalentWasabi_Bot/node_modules/request/request.js:1046:12)
      bot-154     at IncomingMessage.g (events.js:286:16)
      bot-154     at emitNone (events.js:91:20)
      bot-154     at IncomingMessage.emit (events.js:185:7)
      bot-154     at endReadableNT (_stream_readable.js:975:12)
      bot-154     at _combinedTickCallback (internal/process/next_tick.js:74:11)
      bot-154   name: 'TokenExpiredError',
      bot-154   message: 'jwt expired',
      bot-154   expiredAt: 2017-03-05T04:26:03.000Z }

**Comment by astrung** [comment]
Can some one explain why we have an expired token here ? I have tried to generate a new key pair in "Application Secret" , but still same error ????

**Comment by astrung** [comment]
I found its reason . I changed system timezone on server . So that token is always expired. But why that token uses my server timezone ?

**Comment by willportnoy** [comment]
@Stevenic can you comment?  this could explain some 401/403 issues.

**Comment by Stevenic** [comment]
Adding Dan for explanation...

**Comment by Stevenic** [comment]
Adding Carlos as well. In talking to Dan we believe there could be a clock skew issue going on here.

**Comment by carlosscastro** [comment]
Thanks @Stevenic, I'm working on a clock skew issue for this. Will update once the fix is out.

**Comment by astrung** [comment]
Well, so should i wait to next version ?

**Comment by astrung** [comment]
Do we have nay updates ?

**Comment by nwhitmont** [comment]
@astrung are you still experiencing the issue when using botbuilder v3.7.0? You can also try the dev version with `npm i --save botbuilder@next`

**Comment by nwhitmont** [comment]
relates to PR #2502 and #1885 @carlosscastro @Stevenic

**Comment by nwhitmont** [comment]
@astrung In your AWS config you can also set the [correctClockSkew]https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#correctClockSkew-property() option.

**Comment by loretoparisi** [comment]
Still having this issue in https://github.com/Microsoft/BotBuilder/issues/710#issuecomment-351025956

I'm running my bot on a local machine (MacBook Pro).
