### ISSUE TITLE
Issue with PromptDialog.Choice and Facebook's Quick Replies

### ISSUE THREAD

**Issue by brunoklein99** [Microsoft/BotBuilder#2391]
Currently when using `PromptDialog.Choice` with Facebook and using `PromptStyle.Keyboard` to map the options to Quick Replies, the framework doesn't handle the returned user response message correctly, causing the prompt to repeat the message and exhaust the retries until we get `too many attemps`.

For instance, the following dialog:

```cs
[Serializable]
public class TestDialog : IDialog<object>
{
    public async Task StartAsync(IDialogContext context)
    {
        PromptDialog.Choice(
            context,
            ResumeAsync,
            new[] { "a", "b", "c" },
            "this is a prompt",
            promptStyle: PromptStyle.Keyboard,
            descriptions: new[] { "1", "2", "3" });
    }

    private async Task ResumeAsync(IDialogContext context, IAwaitable<string> result)
    {
        var message = context.MakeMessage();

        message.Text = $"You chose {await result}";

        await context.PostAsync(message);

        context.Done(new object());
    }
}
```

This dialog creates a prompt for the options, `a`, `b`, `c`, which are presented to the user as `1`, `2`, `3`. Using the web dialog from `botframework.com` we get the expected behavior.

http://i.imgur.com/x17P85E.jpg

But on Facebook, the same dialog behaves differently.

http://i.imgur.com/hsqX99j.jpg 

Messenger removes the buttons after you click them, but you get the idea.

By debugging the incoming Facebook response I could verify that the `Activity` has the proper `ChannelData` property loaded.

```
{
  "sender": {
    "id": "xxx"
  },
  "recipient": {
    "id": "xxx"
  },
  "timestamp": 1488638719106,
  "message": {
    "mid": "mid.1488444714446:4a44e6ff28",
    "seq": 19139,
    "text": "1",
    "is_echo": false,
    "quick_reply": {
      "payload": "a"
    }
  }
}
```

Maybe the framework is using the `message.text` field instead of `message.quick_reply.payload`?

Is this a bug or am I missing something?

**Comment by willportnoy** [comment]
Can you share the activity object being sent from the bot framework facebook connector?  I would expect to see something that fits the `IMessageActivity` schema.

**Comment by brunoklein99** [comment]
Thank you for the response:

```
{
  "type": "message",
  "timestamp": "2017-03-11T12:43:20.743006Z",
  "serviceUrl": "https://facebook.botframework.com",
  "channelId": "facebook",
  "from": {
    "id": "<myid>",
    "name": "<myid>"
  },
  "conversation": {
    "isGroup": false,
    "id": "<myid>-<myid>"
  },
  "recipient": {
    "id": "<myid>",
    "name": "Bruno Klein"
  },
  "attachmentLayout": "list",
  "text": "",
  "attachments": [
    {
      "contentType": "application/vnd.microsoft.card.keyboard",
      "content": {
        "text": "this is a prompt",
        "buttons": [
          {
            "type": "imBack",
            "title": "1",
            "value": "a"
          },
          {
            "type": "imBack",
            "title": "2",
            "value": "b"
          },
          {
            "type": "imBack",
            "title": "3",
            "value": "c"
          }
        ]
      }
    }
  ],
  "entities": [],
  "replyToId": "5DRZ6Hdmia5"
}
```

```
{
  "type": "message",
  "id": "mid.$cAAYbIxjssFBg7q0lW1avWfZul_zA",
  "timestamp": "2017-03-11T12:46:25.115Z",
  "serviceUrl": "https://facebook.botframework.com",
  "channelId": "facebook",
  "from": {
    "id": "<myid>",
    "name": "Bruno Klein"
  },
  "conversation": {
    "isGroup": false,
    "id": "<myid>-<myid>"
  },
  "recipient": {
    "id": "<myid>",
    "name": "<myid>"
  },
  "text": "3",
  "channelData": {
    "sender": {
      "id": "<myid>"
    },
    "recipient": {
      "id": "<myid>"
    },
    "timestamp": 1489236385115,
    "message": {
      "mid": "mid.$cAAYbIxjssFBg7q0lW1avWfZul_zA",
      "seq": 19576,
      "text": "3",
      "is_echo": false,
      "quick_reply": {
        "payload": "c"
      }
    }
  }
}
```

**Comment by willportnoy** [comment]
@msft-shahins is this an issue with the choice prompt?  Does PromptOptions let you enter either the ordinal number or the choice's text description?

**Comment by msft-shahins** [comment]
This might be a behavior change from the Facebook channel. Prompt.Choice expects the payload of quick_reply to be populated in activity.Text when the user clicks on the button. You should be able to work around this for now by inspecting the ChannelData in the incoming activity and promote the payload value to the activity.Text before sending the message to the PromptDialog, e.g. You can write a custom IPostToBot that can work around this. We need to figure out what is the behavior change and try to either introduce a fix to SDK or Facebook channel.

**Comment by Magic73** [comment]
Same issu with the SuggestedActions. It doesn't send the payload within the .Text property.
I had to read it from the ChannelData (thanks @msft-shahins)

**Comment by etbuilder** [comment]
@brunoklein99 @Magic73 try to override the tryparse of prompt choice 

protected override bool TryParse(IMessageActivity message, out T result)
        {
            // pull from channel data if facebook

            if (message.ChannelId == "facebook")
            {
                // read the quick reply from the quick reply payload
                var text = message.ReadFacebookQuickReply();

                if (text != null) message.Text = text;
            }


            return base.TryParse(message, out result);
        }

**Comment by vishwacsena** [comment]
@craigjensen can you take a look and see if this has been fixed in the connector service mapping for FB channel? The issue here is that suggested actions reply is not getting passed along via activity.text to the bot.

**Comment by schiari** [comment]
I have same issue with SuggestedActions where the value property is not sent back inside the text field.
Has it been fixed ?!?

**Comment by sgellock** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botbuilder-channels/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
