### ISSUE TITLE
Bot emulator can't run any test due to network errors

### ISSUE THREAD

**Issue by Nazmerit** [Microsoft/BotBuilder#2393]
I started learning bot framework last week, and i decided to start off with the default bot project that returns your input and its number of character. But unfortunately, I couldn't test the bot application in bot emulator. It can't just send my input. It displays "couldn't send" whenever I forward an input. 
My endpoint url which is http://localhost:3979/api/messages/ is correctly written there. 
What could be wrong? I'm just a starter in bot framework and bot building.

**Comment by eanders-MS** [comment]
Are you seeing this error in the emulator or the bot? Some things to check:
- Make sure your bot is running on localhost and listening on port 3979.
- Ensure you aren't using `https` on localhost.

Can you post your emulator log?

**Comment by Nazmerit** [comment]
The error is in the emulator. And it's running on localhost and on port  3979. Not using https on localhost .
![screenshot 17](https://cloud.githubusercontent.com/assets/21228864/23599136/5f3de7ce-023f-11e7-83a9-ef375d2ddd0f.png)

**Comment by eanders-MS** [comment]
Whoa, it looks like DNS lookup for `localhost` is failing. Difficult to say why that would happen. As a quick experiment, could you try replacing `localhost` in your bot endpoint with `127.0.0.1`?

**Comment by eanders-MS** [comment]
Can you post the entirety of the "write EPROTO" error appearing in your log? It's truncated because the log doesn't text wrap, but what it says might be of interest.

**Comment by Nazmerit** [comment]
![screenshot 19](https://cloud.githubusercontent.com/assets/21228864/23600605/abd7073e-0247-11e7-9121-fe18edaf8883.png)

**Comment by eanders-MS** [comment]
There are several errors happening:
- Name lookup (DNS) is failing generally.
- It's trying to establish an encrypted connection to the bot.

##### DNS failure
Does your network have a proxy configuration? It might be that the emulator isn't using your proxy settings correctly. (Proxy support is still experimental.) 
##### Encrypted connection
For http, I wouldn't expect the network connection to send the SSL23_GET_SERVER_HELLO message. Can you double-check to ensure your bot endpoint doesn't have AppId or Password set? These aren't typically needed for localhost bot connections, and it's simpler to run without them, which makes debugging the connection a bit easier.

**Comment by Nazmerit** [comment]
I notice this whenever i launch bot emulator:
[BotErrors(1).docx](https://github.com/Microsoft/BotBuilder/files/820588/BotErrors.1.docx)
Could it be the problem?

**Comment by Nazmerit** [comment]
[09:49:11]  Checking for new version...
[09:49:20] 
Command failed: 4294967295 System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote name could not be resolved: 'emulator.botframework.com' at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult) at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result) at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Squirrel.Utility.<LogIfThrows>d__35`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Squirrel.FileDownloader.<DownloadUrl>d__3.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Squirrel.Update.Program.<Download>d__7.MoveNext() --- End of inner exception stack trace --- at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) at System.Threading.Tasks.Task`1.get_Result() at Squirrel.Update.Program.executeCommandLine(String[] args) at Squirrel.Update.Program.main(String[] args) at Squirrel.Update.Program.Main(String[] args) ---> (Inner Exception #0) System.Net.WebException: The remote name could not be resolved: 'emulator.botframework.com' at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult) at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result) at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Squirrel.Utility.<LogIfThrows>d__35`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Squirrel.FileDownloader.<DownloadUrl>d__3.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Squirrel.Update.Program.<Download>d__7.MoveNext()<---   
{}

**Comment by eanders-MS** [comment]
The error message seems to indicate this is another case where DNS is failing: `The remote name could not be resolved: 'emulator.botframework.com'`

There seem to be multiple issues happening here. Let's look at the DNS failure a little closer. Can you try this: Open a command prompt and type `nslookup emulator.botframework.com`. Does the output look something like the below? If not, can you paste the output here?
```
Non-authoritative answer:
Name:    waws-prod-bay-049.cloudapp.net
Address:  40.83.182.206
Aliases:  emulator.botframework.com
          botframeworkemulatornuts.azurewebsites.net
          waws-prod-bay-049.vip.azurewebsites.windows.net
```

**Comment by Nazmerit** [comment]
![screenshot 20](https://cloud.githubusercontent.com/assets/21228864/23623046/4706957c-02a1-11e7-847b-4053b587fe88.png)

**Comment by HalwestRasul** [comment]
I have the same problem, :(  see my logs:
`[23:31:37] Emulator listening on http://[::]:47854 
[23:31:37] [err-server] spawn UNKNOWN "Error: spawn UNKNOWN\n at exports._errnoException (util.js:1026:11)\n at ChildProcess.spawn (internal/child_process.js:313:11)\n at exports.spawn (child_process.js:392:9)\n at runNgrok (C:\\Users\\Halwest\\AppData\\Local\\botframework\\app-3.5.25\\resources\\app\\app\\server\\ngrok.js:109:13)\n at run (C:\\Users\\Halwest\\AppData\\Local\\botframework\\app-3.5.25\\resources\\app\\app\\server\\ngrok.js:67:13)\n at C:\\Users\\Halwest\\AppData\\Local\\botframework\\app-3.5.25\\resources\\app\\app\\server\\ngrok.js:77:13\n at lock (C:\\Users\\Halwest\\AppData\\Local\\botframework\\app-3.5.25\\resources\\app\\node_modules\\lock\\index.js:72:7)\n at Object.connect (C:\\Users\\Halwest\\AppData\\Local\\botframework\\app-3.5.25\\resources\\app\\app\\server\\ngrok.js:61:5)\n at startNgrok (C:\\Users\\Halwest\\AppData\\Local\\botframework\\app-3.5.25\\resources\\app\\app\\server\\botFrameworkService.js:95:23)\n at ngrok.kill (C:\\Users\\Halwest\\AppData\\Local\\botframework\\app-3.5.25\\resources\\app\\app\\server\\botFrameworkService.js:129:17)" 
[23:31:37] Checking for new version... 
[23:31:40] Application is up to date. `

**Comment by eanders-MS** [comment]
Hi @HalwestRasul yours looks like a different issue, could you please open a sepcarate issue for it? This issue seems to be due to network failures like DNS not resolving. Yours is failing to spawn ngrok.

**Comment by eanders-MS** [comment]
@Nazmerit what do you see when you run `ipconfig` from the command line?

**Comment by JasonSowers** [comment]
@Nazmerit I am going to close this issue for inactivity.  please feel free to continue the conversation here if needed.  We can always reopen if needed.

**Comment by eanders-MS** [comment]
@Nazmerit It's a shot in the dark, but try changing your the endpoint url to https: `https://127.0.0.1:3979/api/messages`. This solution worked for another user who was seeing plain http attempting to initialize an ssl connection. Network issues like these are very difficult to troubleshoot remotely.

**Comment by xmyLydia** [comment]
@eanders-MS I meet the same problem like this, can you help me?
 
![default](https://user-images.githubusercontent.com/13426579/33495311-8db48ee6-d6ce-11e7-91a8-b6fce2529798.png)
