### ISSUE TITLE
Publish ChatBot Application on Server without using Azure.

### ISSUE THREAD

**Issue by sumitdobhal** [Microsoft/BotBuilder#2396]
I have created a bot application and tested it on local. But now I wan't to publish it on IIS server.
I have hosted the application in the IIS server but while connecting it to Emulator I got the following error.

> 
> Error: The bot is remote, but the callback URL is localhost. Without tunneling software you will not receive replies.
> Fix it: Configure ngrok
> Learn more: Connecting to bots hosted remotely
> -> POST Refresh access token failed with status code: 400

I have given the path of the ngrok.exe file in the Emulator also.

If anyone knows the problem please reply.

Thanks in Advance.

**Comment by willportnoy** [comment]
I'm not clear - when you "publish it on IIS", is IIS running on your local machine?

**Comment by sumitdobhal** [comment]
Thanks for the reply!
My Bot application is published on IIS of a web server not my machine. So when I tried to acess the Bot  application through Emulator it gave me the above mentioned error.

**Comment by willportnoy** [comment]
Did you install ngrok as suggested by the error message?

As an alternative, use the "localhost" form of your machine name.

**Comment by sumitdobhal** [comment]
I am not using my local IIS .
I have deployed the application in IIS of a other server which is accessible on internet. So what's the use of ngrok.

**Comment by willportnoy** [comment]
@sumitdobhal if you're using your bot in the emulator, it needs to be able to speak to the emulator server running on your local machine, and if your bot is on the internet, ngrok can make that local server available to your bot.

**Comment by thakkarjaimini** [comment]
@willportnoy  I am in the same boat. As per the instruction  on the error page, I installed ngrok.  Now from the app settings of emulator i need to save the path of ngrok. I browsed the zip of ngrok and save it. How can I verify? Am I missing something on the path

**Comment by McBacker** [comment]
Unzip the file and point to the executable.

**Comment by thakkarjaimini** [comment]
Now that i have configured it mapped the path correctly in the emulator and 
also changed  the messaging endpoint on my registration portal to http://0cb8fe99.ngrok.io/api/messages from what was before 
< https://westus.api.cognitive.microsoft.com/luis/v2.0/apps/99bbe58a-6560-4cf3-bc26-4f73a0fcbcc6?subscription-key=567c3926939e41eab54ebc7be7c331e2&timezoneOffset=-480&verbose=true&q=>.

If I want a team member or folk to test this application , what should I give to him? I believe the ngrok url. Please correct

**Comment by F-Makhokha** [comment]
@thakkarjaimini  did you manage to get this up from just installing it on your server without going to cloud?

**Comment by EricDahlvang** [comment]
@F-Makhokha 

There is an unofficial and unsupported "offline direct line" here: https://github.com/ryanvolum/offline_dl with npm package here: https://www.npmjs.com/package/offline-directline  Maybe this will provide what you're looking for.
