### ISSUE TITLE
InvalidIntentHandlerException in LuisDialog

### ISSUE THREAD

**Issue by MadhuryaG** [Microsoft/BotBuilder#2397]
Hi,

I am getting this error for LuisDialog for my Bot application using the emulator. However in Luis it respond correctly when the application is trained. Please help!

{
  "message": "An error has occurred.",
  "exceptionMessage": "<IntentName>",
  "exceptionType": "Microsoft.Bot.Builder.Dialogs.InvalidIntentHandlerException",
  "stackTrace": "   at Microsoft.Bot.Builder.Dialogs.LuisDialog.
}

**Comment by willportnoy** [comment]
What do the methods that are decorated with IntentHandler look like?  Do they fit one of these two method signatures?
```
public delegate Task IntentHandler(IDialogContext context, LuisResult luisResult);
public delegate Task IntentActivityHandler(IDialogContext context, IAwaitable<IMessageActivity> message, LuisResult luisResult);
```

https://github.com/Microsoft/BotBuilder/blob/497252e8d9949be20baa2cebaa6ce56de04461cf/CSharp/Library/Microsoft.Bot.Builder/Dialogs/LuisDialog.cs#L87

**Comment by MadhuryaG** [comment]
I was able to resolve this issue by changing the method signature to LuisResult instead of IActivity.

Had this code earlier.
[LuisIntent("Enquiry")]
public async Task Enquiry(IDialogContext context, IActivity activity)

After changing it to LuisResult(as shown below), it worked.
		
[LuisIntent("Enquiry")]
public async Task Enquiry(IDialogContext context, LuisResult result)

Thank you!

**Comment by jatin085** [comment]
I was able to resolve by fixing the return type.

Before

```cs
[LuisIntent("Greet")]
public void GreetAsync(IDialogContext context, LuisResult result)
{
     context.Call(new GreetingsDialog(), this.ResumeAfter);
}
```

After

```cs
[LuisIntent("Greet")]
public Task GreetAsync(IDialogContext context, LuisResult result)
{
    context.Call(new GreetingsDialog(), this.ResumeAfter);
    return Task.CompletedTask;
}
```

**Comment by iliyalesani** [comment]
I accidentally wrote LuisRequest instead of LuisResult and it took me hours to find it.
