### ISSUE TITLE
Is possible identify if referrer is web chat or messenger app on facebook.

### ISSUE THREAD

**Issue by carloscba** [Microsoft/BotBuilder#2398]
I need disable native control on location dialog. Doesn't work in webchat.

UPDATE

Native control don't work only in popup chat.

**Comment by willportnoy** [comment]
You can look at the channel in the incoming activity object - are you using the https://github.com/Microsoft/BotBuilder-Location control?

**Comment by carloscba** [comment]
@willportnoy Channel information don't identify if it's web or app. The control don't work only in popup chat and is fine for me. Thanks
