### ISSUE TITLE
Message displayed two time on ConversationUpdate

### ISSUE THREAD

**Issue by DeLeneMirouze** [Microsoft/BotBuilder#2401]
Why the "hello" message is displayed two times on connexion:

```
connector = new ConnectorClient(new Uri(activity.ServiceUrl));

if (activity.Type == ActivityTypes.Message)
{
	await Conversation.SendAsync(activity, () => new RootDialog());
}
else if (activity.Type == ActivityTypes.ConversationUpdate)
{
   Activity reply = activity.CreateReply("Hello, I am Bot");
	await connector.Conversations.ReplyToActivityAsync(reply);
}
```

ActiveType.Message is not fired and the thread enter only once in ActiveType.ConversationUpdate

Is it a bug?

**Comment by ankitbko** [comment]
@DeLeneMirouze What channel are you using to chat with the bot? If I understood correctly, if user types "hello" then you are getting `activity.Type` as `ConversationUpdate`?

**Comment by DeLeneMirouze** [comment]
hi

I am testing on emulator
This happen when I launch it or when I renew the conversation

**Comment by eanders-MS** [comment]
@DeLeneMirouze When you start a conversation with a bot in the emulator, the emulator sends your bot two `ConversationUpdate` activities: One for the bot joining the conversation, and another for the user joining. This is in preparation for group chat support, where users can come and go from the conversation. It is also possible that multiple users will be batched into one `ConversationUpdate` activity.  Try filtering out the bot from the `MembersAdded` field of the `ConversationUpdate` activity:
```javascript
case ActivityTypes.ConversationUpdate:
    IConversationUpdateActivity update = activity;
    var client = new ConnectorClient(new Uri(activity.ServiceUrl), new MicrosoftAppCredentials());
    if (update.MembersAdded != null && update.MembersAdded.Any())
    {
        foreach (var newMember in update.MembersAdded)
        {
            if (newMember.Id != activity.Recipient.Id)
            {
                var reply = activity.CreateReply();
                reply.Text = $"Welcome {newMember.Name}!";
                await client.Conversations.ReplyToActivityAsync(reply);
            }
        }
    }
    break;
```

**Comment by iMicknl** [comment]
Looks like the same issue as in #1930, you can also find some code snippets (NodeJS) there.

**Comment by duvarajan** [comment]
For me when I used "WebChat" channel, I too used the same code

case ActivityTypes.ConversationUpdate:
    IConversationUpdateActivity update = activity;
    var client = new ConnectorClient(new Uri(activity.ServiceUrl), new MicrosoftAppCredentials());
    if (update.MembersAdded != null && update.MembersAdded.Any())
    {
        foreach (var newMember in update.MembersAdded)
        {
            if (newMember.Id != activity.Recipient.Id)
            {
                var reply = activity.CreateReply();
                reply.Text = $"Welcome {newMember.Name}!";
                await client.Conversations.ReplyToActivityAsync(reply);
            }
        }
    }
    break;

But surprisingly, 
if (newMember.Id != activity.Recipient.Id)
did not display Initial Bot's greeting message. But when I used
if (newMember.Id == activity.Recipient.Id)
it displayed the Bot's Initial message. Also, in the subsequent chats the initial greeting was not repeated and it worked fine!
