### ISSUE TITLE
[Feature Request] Auto voice to text

### ISSUE THREAD

**Issue by awebdeveloper** [Microsoft/BotBuilder#2403]
Could skype bot do auto voice to text. I know that i can currently recognize a small subset of words that i define. But i am looking at a general voice to text.

**Comment by FranciscoPonceGomez** [comment]
Hi awebdeveloper ,

It does. There are three different API that you can use for your speech to text application:

1. The **[Bing Speech API](https://www.microsoft.com/cognitive-services/en-us/speech-api)** provides speech-to-text and text-to-speech conversion capabilities.
2. The **[Custom Recognition Intelligent Service](https://www.microsoft.com/cognitive-services/en-us/custom-recognition-intelligent-service-cris)** (CRIS) allows you to create custom speech recognition models to tailor the speech-to-text conversion to an application’s vocabulary or user’s speaking style.
3. The **[Speaker Recognition API](https://www.microsoft.com/cognitive-services/en-us/speaker-recognition-api)** enables speaker identification and verification through voice.

You can find code examples in the official documentation section:
https://docs.botframework.com/en-us/bot-intelligence/speech/

There is also an article from Microsoft where the author builds a bot for Skype:
https://blogs.msdn.microsoft.com/tsmatsuz/2016/10/22/build-skype-calling-bot-with-microsoft-bot-framework/

And here is another code example:
https://code.msdn.microsoft.com/bing/Speech-To-Text-Bot-using-db55e1d0

**Comment by awebdeveloper** [comment]
This was more of a feature request, than a query.
