### ISSUE TITLE
Private bot

### ISSUE THREAD

**Issue by danechitoaie** [Microsoft/BotBuilder#2405]
Is there a way to make a private bot? I want to do something that will be used just by some users and not by everybody.

I think I can do this in code (i.e. if the user messaging the bot is one of [list of allowed users] then respond and ignore everyone else)

Would that be allowed?

**Comment by ankitbko** [comment]
Well, you could have your users to sign in (authenticate) before using any features of your bot.

**Comment by danechitoaie** [comment]
Yes, solutions can be found. I guess what I'm asking more is if this is allowed. The fact I have to publish the bot and make it public on "Bot Directory" made me think the bot needs to be able to be used by everyone and that you can't restrict access.

**Comment by Andrea-Orimoto** [comment]
Hi @danechitoaie, as long as you comply with the review guidelines you should be fine https://docs.botframework.com/en-us/directory/review-guidelines/. Having a login should not be a problem. Feel free to reopen this issue if you still have questions. Thanks!

**Comment by danechitoaie** [comment]
@Andrea-Orimoto thanks
