### ISSUE TITLE
BotAuthentication attribute not working

### ISSUE THREAD

**Issue by brunoklein99** [Microsoft/BotBuilder#2406]
The SDK is always trying to get `MicrosoftAppId` and `MicrosoftAppPassword` from the `web.config`.

If setting an implementation of `ICredentialProvider` to the `BotAuthentication` attribute it does get called, but I end up getting `OAuthException`.

How to reproduce.

1. Create new project with the [Bot Framework template](http://aka.ms/bf-bc-vstemplate)
2. Update the Bot Framework dependency to latest version (`3.5.5.0`)
3. Comment the tokens in the `web.config` file:
```
<configuration>
  <appSettings>
    <!-- update these with your BotId, Microsoft App Id and your Microsoft App Password-->
    <!--
    <add key="BotId" value="YourBotId" />
    <add key="MicrosoftAppId" value="" />
    <add key="MicrosoftAppPassword" value="" />
    -->
  </appSettings>
  ...
</configuration>
```
4.
- Option 1. Add the AppId and password to the attribute, for example:

```
[BotAuthentication(MicrosoftAppId = "<appid>", MicrosoftAppPassword = "<apppass>")]
public class MessagesController : ApiController
{
   ...
}
```

- Option 2. Add your own implementation of `ICredentialProvider`, for example:

```
[BotAuthentication(CredentialProviderType = typeof(CustomCredentialProvider))]
public class MessagesController : ApiController
```
5. Send a message to the bot.
6. You get `Microsoft.Bot.Connector.MicrosoftAppCredentials.OAuthException`, with message:
`"{"error":"invalid_client","error_description":"AADSTS70002: 'client_assertion' or 'client_secret' is required for the 'client_credentials' grant type.\r\nTrace ID: 39e5294b-9d8a-4f04-9a4b-43c92f7e077c\r\nCorrelation ID: 79105c3d-8621-42fb-b545-a6fdd1622a1b\r\nTimestamp: 2017-03-08 23:34:05Z","error_codes":[70002],"timestamp":"2017-03-08 23:34:05Z","trace_id":"39e5294b-9d8a-4f04-9a4b-43c92f7e077c","correlation_id":"79105c3d-8621-42fb-b545-a6fdd1622a1b"}"`

This is a show stopper because we are unable to host multiple bots in a single service.

**Comment by BenjaBobs** [comment]
This is probably not the solution you're looking for, as it kind of bypasses the BotAuthentication attribute, but you can do manual authentication instead.

```
public static async Task<bool> AuthenticateBotRequest(HttpRequestMessage req, TraceWriter log, Activity activity, CancellationToken token)
{
    var credProvider = new SettingsCredentialProvider();

    var authenticator = new BotAuthenticator(credProvider, JwtConfig.ToBotFromChannelOpenIdMetadataUrl, disableEmulatorTokens: false);

    var authenticated = await authenticator.TryAuthenticateAsync(req, new[] { activity }, token);

    if (authenticated)
    {
        MicrosoftAppCredentials.TrustServiceUrl(activity.ServiceUrl);
    }
    return authenticated;
}
```

**Comment by willportnoy** [comment]
You need to handle authentication for outgoing messages back to the user - see https://docs.botframework.com/en-us/technical-faq/#how-can-i-support-multiple-bots-at-the-same-bot-service-endpoint for more information.

**Comment by brunoklein99** [comment]
This is working now, the missing part was registering the `ClaimsIdentity` in the container and making sure all my `IConnectorClient`s were being resolved from `Conversation.Container`.

Thank you.

**Comment by lonche** [comment]
@brunoklein99 it would be nice if you share your code. How did you fix this issue ? I have the same problem.

**Comment by brunoklein99** [comment]
https://docs.botframework.com/en-us/technical-faq/#how-can-i-support-multiple-bots-at-the-same-bot-service-endpoint

This is all I needed. The issue for me was that I neglected the container
registration part.

**Comment by Magic73** [comment]
I got the same issue, and I can't find a solution.
Using attributes initialization will fail the authentication, using both methods (appid+password or credentialprovider)
