### ISSUE TITLE
Date input is printed incorrectly

### ISSUE THREAD

**Issue by maba4891** [Microsoft/BotBuilder#2409]
Hi,

in my node.js bot I provide a simple builder.Prompts.text to ask the user for a date (I know that Prompts.time exists but since it does not seem to work with German dates yet I use Prompts.text for now and parse the date with the datejs module).

The problem is that if the user enters the date in a German format (e.g. "12. Februar 2017") and presses enter he sees "1. Februar 2017" as his input. The same is true for other dates (e.g. "20. August 2016") which are printed in a similar way like "1. August 2016". This also happens when I provide a date with a dot as an input to any other type of prompt.

Somehow the **dot** seems to be the problem here, 12 Februar 2017 works just fine (as does 12.2.2017). 

The funny thing is also that **internally the right date is saved**, e.g. 12. Februar 2017 even if 1. Februar 2017 is printed (I save the input in session.userData). So it seems the problem is just the way the input is printed.

Any clue what is happening here?

**Comment by maba4891** [comment]
Edit: This problem seems to be only affecting the Emulator and the Web Chat, on Skype and Facebook Messenger everything seems to be fine.

**Comment by danmarshall** [comment]
Thanks for filing this issue @maba4891 . Would you mind filing this issue on the WebChat repo?
https://github.com/Microsoft/BotFramework-WebChat/issues

**Comment by maba4891** [comment]
@danmarshall no problem, I'll post it there

**Comment by danmarshall** [comment]
Thanks!
