### ISSUE TITLE
You have to specificy valid userId or conversationId

### ISSUE THREAD

**Issue by ahmettaha** [Microsoft/BotBuilder#241]
Hello,

I tried your sample, it still doesnt work for me. What am I missing? I still get this error:

 You have to specificy valid userId or conversationId

on this line

            BotData botData = await connectorClient.Bots.GetConversationDataAsync(botAppId, model.ConversationId);

How come a new conversation with a conversationId is not valid.

    string botAppId = CloudConfigurationManager.GetSetting("BotAppId");

            DirectLineClient client = new DirectLineClient(CloudConfigurationManager.GetSetting("BotDirectLineSecret"));
            Conversation conversation = await client.Conversations.NewConversationAsync();

            BotClientModel model = new BotClientModel();
            model.ConversationId = conversation.ConversationId;
            model.ETag = conversation.ETag;
            model.Token = conversation.Token;

            ConnectorClient connectorClient = new ConnectorClient(botAppId, CloudConfigurationManager.GetSetting("BotSecret"));

            BotData botData = await connectorClient.Bots.GetConversationDataAsync(botAppId, model.ConversationId);
            botData.SetProperty("MemberId", this.CurrentMember.Id);

            await connectorClient.Bots.SetConversationDataAsync(botAppId, model.ConversationId, botData);

**Comment by tomlm** [comment]
I think this is because the conversationId that DirectLIne is creating is not the same one which is assigned when messages go through the pipeline. 
Try pushing a message through the system and look at the conversation Id that is assigned in the message.

**Comment by ahmettaha** [comment]
Why would the conversation id change?

Anyways, I was about to try if the conversation ids change, I started to receive the following exception

    Operation returned an invalid status code 'Created'

on the line
   
    Conversation conversation = await client.Conversations.NewConversationAsync();

Is something changed?

**Comment by ahmettaha** [comment]
ok. apperantly, this is another problem. I'll just bypass as suggested in #246 for now and try it

**Comment by ahmettaha** [comment]
ok. so I sent a message, and did a message query. The conversationids seem to match. so the conversation should be valid. is there a chance that the conversationid becomes valid after the first message is sent?

```
{
  "messages": [
    {
      "id": "EC5vdHNO4pD|131072644430454112",
      "conversationId": "EC5vdHNO4pD",
      "created": "2016-05-09T10:47:23.0454112Z",
      "from": "KgaGSE3mOPo",
      "text": "4",
      "images": [],
      "attachments": [],
      "eTag": "W/\"datetime'2016-05-09T10%3A47%3A22.6871039Z'\""
    },
    {
      "id": "EC5vdHNO4pD|131072644484509754",
      "conversationId": "EC5vdHNO4pD",
      "created": "2016-05-09T10:47:28.4509754Z",
      "from": "FitWell-Test",
      "text": "What is the your FitWell account email?",
      "images": [],
      "attachments": [],
      "eTag": "W/\"datetime'2016-05-09T10%3A47%3A28.3413811Z'\""
    }
  ],
  "watermark": "131072644484509754"
}
```

**Comment by ahmettaha** [comment]
Hello,

It it is not possible to set data with ConnectorClient, I'll use alternative methods such as storing the conversationid, and user data on database. However, it would be great if I can just make sure, the above code is not meant to work.

Thanks.

**Comment by ahmettaha** [comment]
@tomlm Is it possible if you could help me? :)

**Comment by ahmettaha** [comment]
Yeah. I ended up storing the conversationid elsewhere, and just recover from there :(
