### ISSUE TITLE
Unable to generate token / 500 Error when attempting to edit channels

### ISSUE THREAD

**Issue by s33r** [Microsoft/BotBuilder#2410]
Hi all, apologies if this isn't the correct forum for this issue. 

The bot: https://dev.botframework.com/bots?id=koan-bot
The webpage trying to use it: http://aaronwillows.com/koan-bot/bot.html
Source: https://github.com/s33r/KoanBot

Yesterday I attempted to integrate the directline channel with my bot. Things seemed to work at first, but soon the api was preforming very slowly, and intermittently failing and then it stopped working at all. 

Currently I get the following error when trying to generate a token from my Node.js bot: 
```
message: 'Invalid token or secret',
statusCode: 403,
body: { error: { code: 'BadArgument', message: 'Invalid token or secret' } },
```

I would assume this was a problem on my end, except that I cannot edit my bots directline configuration in the 'My Bots portal'. The configuration generates an asp 500 error page. Editing the chat channel also fails with the same result. 

Generating the embed code also fails with the message: "An error occured. ID = 2clZt5vCXhk=" When I us the embed I previously generated it 404s.

Oddly enough the chat preview on the portal seems to work correctly. The bot works locally & remotely with the emulator.

My best guess is that my secret keys for chat and directline have been wiped out or corrupted somehow.

**Comment by dandriscoll** [comment]
Hi @s33r, sorry for the interruption, this was caused by a service issue on our side. All functionality has been restored. Can you try again and let us know if you encounter any failures?

**Comment by s33r** [comment]
The features on the portal are working again, thanks! My app is still failing, pretty sure that's on me though.
