### ISSUE TITLE
Stack is empty

### ISSUE THREAD

**Issue by nzthiago** [Microsoft/BotBuilder#2411]
I've updated our [beta version of Azure Bot](https://github.com/Microsoft/AzureBot/tree/beta) to a more recent version of the Bot Builder .NET SDK (3.5.2). It is now working fine with the emulator and on Slack (my test is list vms, list subscriptions, list runbooks and all three work well on those two channels). 

But for some reason on Skype when I try the same commands, the 'list runbooks' one fails and the bot responds with "Sorry, my bot code is having an issue."

I enabled error logging on the Azure Web App for it. The last conversation id with the failure is **29:1iVz4E7ch7dwQaneg4JJ4JtLzOw33MtYW3KsoPJgLBgc** if you can help investigate, and below is the exception from the log. Any ideas what is happening and why only on Skype? 

Buffer="{
  "message": "An error has occurred.",
  "exceptionMessage": "**Stack is empty**",
  "exceptionType": "System.InvalidOperationException",
  "stackTrace": "   at Microsoft.Bot.Builder.Internals.Fibers.Extensions.Peek[T](IReadOnlyList`1 stack)\r\n   at Microsoft.Bot.Builder.Internals.Fibers.Extensions.Pop[T](List`1 stack)\r\n   at Microsoft.Bot.Builder.Internals.Fibers.Fiber`1.<Microsoft-Bot-Builder-Internals-Fibers-IFiberLoop<C>-PollAsync>d__16.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Bot.Builder.Dialogs.Internals.DialogTask.<Microsoft-Bot-Builder-Base-IEventLoop-PollAsync>d__23.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Bot.Builder.Dialogs.Internals.ReactiveDialogTask.<Microsoft-Bot-Builder-Base-IEventLoop-PollAsync>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Bot.Builder.Dialogs.Internals.ScoringEventLoop`1.<Microsoft-Bot-Builder-Base-IEventLoop-PollAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Bot.Builder.Dialogs.Internals.PersistentDialogTask.<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d__4.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.Bot.Builder.Dialogs.Internals.PersistentDialogTask.<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d__4.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Bot.Builder.Dialogs.Internals.ExceptionTranslationDialogTask.<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Bot.Builder.Dialogs.Internals.SerializeByConversation.<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d__4.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Bot.Builder.Dialogs.Internals.SetAmbientThreadCulture.<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Bot.Builder.Dialogs.Internals.PostUnhandledExceptionToUser.<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.Bot.Builder.Dialogs.Internals.PostUnhandledExceptionToUser.<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Bot.Builder.Dialogs.Internals.LogPostToBot.<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Bot.Builder.Dialogs.Conversation.<SendAsync>d__4.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Bot.Builder.Dialogs.Conversation.<SendAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at AzureBot.MessagesController.<Post>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"
}"

**Comment by nzthiago** [comment]
FYI it is also working fine on our [test console app](https://github.com/Microsoft/AzureBot/tree/beta/AzureBot.ConsoleConversation)

**Comment by willportnoy** [comment]
I could see that happening if you have

1. an unbalanced number of pushes and pops
2. you don't have a IDialog.Loop at the root of your dialog stack

As for why you only see it with Skype, perhaps there is an exception thrown only for that channel?

**Comment by nzthiago** [comment]
Hmm, ok thanks. I wonder if the stack got messed up between my user and the Skype channel. How would I reset the stack and context and basically start from scratch with the Skype channel? "/deleteprofile" doesn't seem to work. (sample code would be appreciated it I need to add it as a command to the bot).

**Comment by nzthiago** [comment]
I tried @msft-shahins code from https://github.com/Microsoft/BotBuilder/issues/101 but we've since moved from message to activity and the data bags moved to context, so still can't reset my conversation in Skype. Also, /deleteprofile (with or without a space before it) doesn't work... Any recommendations?

**Comment by FranciscoPonceGomez** [comment]
Check if you have a missing wait operator in your code:

http://stackoverflow.com/questions/42694361/stack-is-empty-in-microsoft-bot-framework

**Comment by McGern** [comment]
Hi,

I am also facing this issue of stack is empty appearing after I do a context.reset(). My scenario is this:-

There is a list of dialogs which simulate a form by asking questions and using context.done() for the answers (sending back to the parent dialog?). If the user answers "no" (or something else that doesn't fit the answer) they go into the "advisor" dialog where there is a point when the user will end the conversation i.e. "no" they don't want to continue. I am using some of the code shown in nzthiago's link to the Azure bot sample.

The problem I am having is that in the example there is an "await this.Help(...)." line that I don't know how to replicate for my script i.e. where do I send the user? From the stuff I have read it seems that I am missing an await somewhere. At this stage each dialog is in it's own class being called with script similar to this

            using (var scope = DialogModule.BeginLifetimeScope(Conversation.Container, message))
            {
                context.Call(scope.Resolve<AgeDialog>(new NamedParameter("forename", forename)), AfterAgeDialog);
            }

So there are probably 3 (?) dialogs in the stack by the time the "reset" command is called.

        private async Task AfterContinueQuote(IDialogContext context, IAwaitable<IMessageActivity> result)
        {
            var message = await result;
            var messageText = message.Text;

            if (RegexCommon.No.IsMatch(messageText))
            {
                context.Reset();
                context.ConversationData.Clear();
                context.UserData.Clear();
                context.PrivateConversationData.Clear();
                await context.FlushAsync(CancellationToken.None);
                await context.PostAsync($"sorry to see you go");
                // where to do from here?
            }

Any help would be appreciated. Nearly everything works as expected i.e. after the "stack is empty" message, if the user says "hello" the conversation starts again from the top - I just don't know how to deal with the "stack is empty" message.

Regards,
Jarrod

**Comment by willportnoy** [comment]
@nzthiago that method to reset the dialog stack is intended for use outside of the dialog system.  When you call IDialogStack.Reset like that, you're still executing in RootDialog which thought it was on the stack.  If you want to escape out of a dialog stack, you can throw an exception which will propagate up the dialog stack and and allow cleanup, and then you can catch that exception at the top of the stack to prevent the user from seeing it.

By the way, if that's your root dialog, what other dialogs are on the stack anyway?

**Comment by nzthiago** [comment]
Oh I see, I can't call that from inside a dialog...
I have other dialogs in the solution, that the root one calls, like this one:
https://github.com/Microsoft/AzureBot/blob/beta/AzureBot.Services.Runbooks/Dialogs/AutomationDialog.cs

**Comment by nzthiago** [comment]
I enabled remote debugging on the web app hosting the beta version of the bot, and looked at the context object and it shows three things in the stack when I go into fiber stack for it:

![screen shot 2017-03-30 at 2 36 13 pm](https://cloud.githubusercontent.com/assets/1563288/24527288/4bd7c54a-1556-11e7-9f1e-87f436566476.png)

Below is the stack trace, with a message "Unknown", so I'm still at a loss on why this only happens for Skype and what the error is, it's right at a "context.PostAsync" call as per the printscreen above...
 
Microsoft.Rest.HttpOperationException occurred
  HResult=-2146233088
  Message=Unknown
  Source=Microsoft.Bot.Connector
  StackTrace:
       at Microsoft.Bot.Connector.ErrorHandling.<HandleErrorAsync>d__2`1.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.Bot.Connector.ConversationsExtensions.<ReplyToActivityAsync>d__7.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.Bot.Builder.Dialogs.Internals.AlwaysSendDirect_BotToUser.<Microsoft-Bot-Builder-Dialogs-Internals-IBotToUser-PostAsync>d__4.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.Bot.Builder.Dialogs.Internals.MapToChannelData_BotToUser.<PostAsync>d__3.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.Bot.Builder.Dialogs.Internals.LogBotToUser.<Microsoft-Bot-Builder-Dialogs-Internals-IBotToUser-PostAsync>d__4.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.Bot.Builder.Dialogs.Internals.DialogContext.<Microsoft-Bot-Builder-Dialogs-Internals-IBotToUser-PostAsync>d__12.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.Bot.Builder.Dialogs.Extensions.<PostAsync>d__2.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
       at AzureBot.Dialogs.AutomationDialog.<ListRunbooksAsync>d__2.MoveNext() in C:\a\1\s\AzureBot.Services.Runbooks\Dialogs\AutomationDialog.cs:line 75
  InnerException:

**Comment by nzthiago** [comment]
I moved the code to reset the stack into the controller and outside the root dialog:
https://github.com/Microsoft/AzureBot/blob/beta/AzureBot/Controllers/MessagesController.cs#L29-L36

This properly resets the stack and the bot starts all over again with an empty stack. But if I run through the same flow (login, list vms, list runbooks) it still fails with the same error messages in Skype as above ("Stack is empty' on the server side) after the 'list runbooks' command. So I'm still not sure why Skype is failing there. 
I even looked for missing wait operators in the code as recommended above but couldn't find any.

Anything else I should try? Can we get someone working in the Skype channel to help perhaps?

**Comment by catcher-in-the-try** [comment]
Not sure if this is related to the original problem but I am getting the "Stack is Empty" exception on this code when I call the dialog using `context.Forward` from another dialog: 

        public async Task StartAsync(IDialogContext context)
        {
            context.Wait(UserProfileStep1);
        }

        public async Task UserProfileStep1(IDialogContext context, IAwaitable<object> original)
        {
            string originalMessage = (string)await original; // <== the exception occurs here
