### ISSUE TITLE
[Direct Line] Scalability Issue or Limitation (for Production) ?

### ISSUE THREAD

**Issue by JpEncausse** [Microsoft/BotBuilder#2413]
Hi,

I'm using the Direct Line Client with v3 for a scalability test (to a server with BotBuilder3.7.0) :
https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node/core-DirectLine/DirectLineClient

Here is my NodeJS code:
```
for (let i = 0 ; i < count ; i++){
  setTimeout(() => {
    sendMessage(client, conversationId, 'Hello ' + i); 
    if (i == count-1) console.log('Sending '+count+' messages in '+(Date.now() - startSend)+'ms');
  }, i*1000)
}
```

I get errors even if I send a message 'only' every seconds

For 2 of them I'm receiving a 500 ServiceError at `node_modules\superagent\lib\node\index.js:626:17` coming from server: 'Microsoft-IIS/8.0',  'x-powered-by': 'ASP.NET'

So I assume it's Microsoft server that closing my messages.

**Questions:**
- Is it a Bug or a limitation ?
- What are DirectLine v3 limitation ?
- How can I load test gently Microsoft Bot Framework AND my end point and emulate Messenger client?

I'm using Restify + BotBuilder on Node-RED to build my bots. Some users (in production) of [our framework](https://github.com/NGRP/node-red-contrib-viseo/tree/master/node-red-contrib-botbuilder) told me there is many messages "lost". And I try to figure out  if it's 
- Microsoft Server, 
- My Server with Restify
- or a side Effect on Node-RED

Thanks

**EDIT 1:**

It seems I have a message on server side in :
`bot.on('error',    (err) => { console.log("Message error:",  err); })`

```
Message error: Error: Request to 'https://directline.botframework.com/v3/conversations/G0mq1XlTqDTAP7gdfMZ8oX/activities/G0mq1XlTqDTAP7gdfMZ8oX%7C0000033' failed: [429]
at Request._callback (/node_modules/botbuilder/lib/bots/ChatConnector.js:452:46)
```

So I assume that the ChatConnector send a request to the DirectLine and get a response error from the service ?

To send back my message I use [bot.send()](https://docs.botframework.com/en-us/node/builder/chat-reference/classes/_botbuilder_d_.universalbot#send) I don't use the session.send() (it's a code design choice) but I assume error do not comes from that.

**What am I doing wrong ?** 
- If the directline can't handle few messages it's a big issue for me
- Is it only directline or also other channels ?
- Spamming MS WebChat also trigger very easily a 429. (I assume it's directline underneath)
- Spamming Facebook is OK

IF it's only an issue tied to DirectLine, I think I should use the WebSocket version instead of the REST version ? Is there a sample like the REST one ?

**Comment by dandriscoll** [comment]
Hi @JpEncausse, the HTTP 500 errors are likely caused by a service interruption we experienced yesterday. If you're using Direct Line 3.0, the service will never throw 500s in normal operation.

The HTTP 429 errors will occur primarily if you're using our default storage. We're adding a new high-speed storage stack, and it does not emit those errors anymore. You can opt-in to the preview for this stack on your Direct Line configuration page (there's a checkbox marked "High-speed storage.") This will become the default storage option eventually.

Can you try that and let me know if you still encounter any 429 or 500 errors? If so, please send a conversation ID.

**Comment by nwhitmont** [comment]
@JpEncausse reopen if you're still having issues.

**Comment by JobaDiniz** [comment]
@dandriscoll 
>The HTTP 429 errors will occur primarily if you're using our default storage. We're adding a new high-speed storage stack, and it does not emit those errors anymore. You can opt-in to the preview for this stack on your Direct Line configuration page (there's a checkbox marked "High-speed storage.") This will become the default storage option eventually.

There is no such configuration.
![image](https://user-images.githubusercontent.com/165290/42104017-77a709da-7ba1-11e8-86ac-1608e37f3ed3.png)

Often, we're getting 429 status, but we have a paid subscription.

**Comment by EricDahlvang** [comment]
Hi @JobaDiniz 

This is an old issue.  High speed storage is now the default.  However, the default state store has been deprecated: https://blog.botframework.com/2017/12/19/bot-state-service-will-soon-retired-march-31st-2018/  Please implement a custom state store, or use on of the Azure Extensions (as explained in the blog post).

**Comment by iliosana** [comment]
I also got a **429** response for the following request:

`https://directline.botframework.com/v3/directline/conversations/XXXXXXXXXXXXXXXXXXXX/activities`

with response:

```
{
  "error": {
    "code": "ServiceError",
    "message": "Included quantity of 10000 transactions has been exceeded. The quantity will reset on 2023-01-27T12:03:49.1473392Z."
  }
}
```

In my case the pricing plan of my **Azure Bot** resource was the issue. Once I changed my pricing plan from F0 to S1 (In the Azure Portal:  open your Azure Bot resource -> Settings -> Pricing), it was working again.
