### ISSUE TITLE
[Performance] LUIS latency issues when using Directline API

### ISSUE THREAD

**Issue by sayyednazeer** [Microsoft/BotBuilder#2414]
I am having a simple BOT application which greets the user.

When i call this application using DIRECT LINE API i have notice some time LUIS Service (which calculate the top scoring intent takes more than 15 seconds) due to which i get 500 internal server error.

I have deployed my BOT on AZURE and my https  WINDOWS 2008 Server to test. 
But i am getting same error on both.

**Comment by sayyednazeer** [comment]
Please Update @dandriscoll  @carlosscastro

**Comment by sayyednazeer** [comment]
Any Update Sir !!

 @dandriscoll @carlosscastro @willportnoy

**Comment by sayyednazeer** [comment]
Still waiting .... @dandriscoll  @carlosscastro @willportnoy 

Is my question is not relevant or you are working on it .. ?
Its 19 days already .

**Comment by nwhitmont** [comment]
@sayyednazeer thanks for reporting this. Are you using BotBuilder SDK for C# or Node? Can you provide example bot code that I can use to reproduce the issue?

**Comment by sayyednazeer** [comment]
@nwhitmont  Thanks!.. i am using C# .

My whole code is mention in this thread #2078 
If you get time you can see i have also attached the snap of my database log to find out where it is taking the time.

And after a lot of R&D i think there is nothing wrong with my code (you can also check).

And also to find out where is the problem i have created a separate project with default code which returns the count of string and nothing more than that, but in that case also i am getting the same LUIS latency issue (some times its take time and some time it works).

**Comment by sayyednazeer** [comment]
Any update @nwhitmont

**Comment by sayyednazeer** [comment]
Any update @nwhitmont @dandriscoll @carlosscastro @willportnoy

**Comment by sayyednazeer** [comment]
any update  @nwhitmont @dandriscoll @carlosscastro @willportnoy

**Comment by willportnoy** [comment]
@sayyednazeer you might consider starting a second request to LUIS (after some delay) if it looks like the first request might time out due to network issues, etc.

**Comment by sayyednazeer** [comment]
@willportnoy 

How to do that..?
