### ISSUE TITLE
Can't connect bots with database !

### ISSUE THREAD

**Issue by HalwestRasul** [Microsoft/BotBuilder#2415]
hi, I wanna Create a translator bot and I have a problem while connecting my bot with mysql !
when I send any message the bot replays is "Oops. Something went wrong and we need to start over."
that my code in je file.
`var builder = require('botbuilder'); 
var restify = require('restify'); 
var mysql = require('mysql');
var connector = new builder.ChatConnector();
var bot = new builder.UniversalBot(connector);
bot.dialog('/', function(session){
    var UserMessage = session.message.text;
    var connection = mysql.createConnection({  
        host     : 'localhost',  
        user     : 'root',  
        password : '',  
        database : 'dictionary'  
    });  
    connection.connect(); 
    connection.query("select Kurdish from en_ku WHERE english LIKE ('%{"+UserMessage+"}%')", function(err, rows, fields)   
    {  
        text = UserMessage;
        if (err) throw err;  
        if (rows[0] != null){
            text = rows[0];  
        }
        else {
            text = "Sorry don't have any result for: %s", text;
        }
    }); 
    connection.end();  
    session.send("Your message in Kurdish:" + text);
});
var server = restify.createServer();
server.listen(process.env.port || process.env.PORT || 3978, function(){
    console.log('%s listening to %s', server.name, server.url);
});
server.post('/api/messages', connector.listen()); `
whats wrong here? how to fix it?

**Comment by carlosscastro** [comment]
@HalwestRasul That means that some of your code is failing. You could start by testing your database code in isolation to make sure it works and the connection to the database and queries are functioning properly.

**Comment by HalwestRasul** [comment]
@carlosscastro thanks for your replay,
first I updated the js code like this 
`var builder = require('botbuilder');
var restify = require('restify');
var mysql = require('mysql');
var utf8 = require('utf8');
var connector = new builder.ChatConnector();
var bot = new builder.UniversalBot(connector);
var connection = mysql.createConnection({  
    host     : 'localhost',  
    user     : 'root',  
    password : '',  
    database : 'dictionary'  
});  
bot.dialog('/', function(session){
    var UserMessage = session.message.text;
    var text = UserMessage;
    connection.connect(); 
    connection.query("SELECT `kurdi` AS 'kurdish' FROM `en_ku` WHERE `english` LIKE ? LIMIT 1", 
    values = [UserMessage] ,
    function(err, rows, fields)   
    {  
        if (err) throw err;  
        if (rows[0] != null){
            text = rows[0].kurdish;  
            session.send("چۆنیت:" + text);
        }
        else {
            text = "هیچ ئەنجامێک نەبوو بۆ : "+ text;
            session.send(text);
        }
    }); 
    connection.end();  
});
var server = restify.createServer();
server.listen(process.env.port || process.env.PORT || 3978, function(){
    console.log('%s listening to %s', server.name, server.url);
});
server.post('/api/messages', connector.listen());`
now while the users send a message and the word message not included in the database the bot replay a custom message like this code `  text = "هیچ ئەنجامێک نەبوو بۆ : "+ text;`,
but if the message-word included in the database the bot emulator was stop working and send this logs
the emulator log have an error when you connect the endpoint URL with the emulator
 `[22:49:57] -> POST connect ECONNREFUSED 127.0.0.1:3978 `

the terminal log :
`WARN: ChatConnector: receive - emulator running without security enabled.
ChatConnector: message received.
/ - waterfall() step 1 of 1
events.js:161
      throw er; // Unhandled 'error' event
      ^`
`Error: Cannot enqueue Handshake after invoking quit.
    at Protocol._validateEnqueue (D:\Chatbot\node_modules\mysql\lib\protocol\Protocol.js:202:16)
    at Protocol._enqueue (D:\Chatbot\node_modules\mysql\lib\protocol\Protocol.js:135:13)
    at Protocol.handshake (D:\Chatbot\node_modules\mysql\lib\protocol\Protocol.js:52:41)
    at Connection.connect (D:\Chatbot\node_modules\mysql\lib\Connection.js:130:18)
    at Array.<anonymous> (D:\Chatbot\hello.js:16:16)
    at SimpleDialog.waterfallAction [as fn] (D:\node_modules\botbuilder\lib\dialogs\SimpleDialog.js:67:25)
    at SimpleDialog.replyReceived (D:\node_modules\botbuilder\lib\dialogs\SimpleDialog.js:21:14)
    at Session.routeToActiveDialog (D:\node_modules\botbuilder\lib\Session.js:497:24)
    at UniversalBot.Library.selectActiveDialogRoute (D:\node_modules\botbuilder\lib\bots\Library.js:138:17)
    at UniversalBot.Library.defaultSelectRoute (D:\node_modules\botbuilder\lib\bots\Library.js:270:22)`
what I should do?

**Comment by carlosscastro** [comment]
Your code that talks to mysql is not working unfortunately. This is not related to bot framework.

I'd advice to just figure out the mysql code outside of the bot, in a separate js file until you get it to work, and then integrate it with the bot framework. Also read the detailed documentation from the mysql library for node: https://github.com/mysqljs/mysql

Unfortunately we can't provide mysql support. If down the road you find issues with bot framework, don't hesitate to ask!

**Comment by aakashkag** [comment]
I written code to connect bot Builder to Mongo db. It will store session data in mongo
https://github.com/aakashkag/BotBuilder-MongoDB
