### ISSUE TITLE
Serializing the context (and BotData items) doesn't work

### ISSUE THREAD

**Issue by nzthiago** [Microsoft/BotBuilder#2418]
The c# App Insights sample in BotBuilder-Samples has [a nice class](https://github.com/Microsoft/BotBuilder-Samples/blob/master/CSharp/core-AppInsights/TelemetryExtensions.cs) to serialize the context data bag objects. But unfortunately it doesn't work, it always serializes to {}. I _suspect_ from looking at the BotBuilder code that this is because the internal 'bag' dictionary property is never exposed and is internal only, so serialization doesn't work. 
It would be great to be able to Serialize context data entries or at least iterate through data bag contents without needing to know the key values, or to find out how to do it if it's already possible.

**Comment by nwhitmont** [comment]
@nzthiago Are you still experiencing the issue after upgrading to [BotBuilder 3.8.1](https://www.nuget.org/packages/Microsoft.Bot.Builder/)?

**Comment by nzthiago** [comment]
Sorry I missed this @nwhitmont . I think it's still happening, if I run the sample again I still get empty PrivateConversationData and ConversationData:  
![screen shot 2017-06-28 at 1 38 20 pm](https://user-images.githubusercontent.com/1563288/27659135-439629e2-5c07-11e7-9aa0-50aee5709dc1.png)

By the way, the sample is provided by the repo maintained by the Bot team, so you can just try it yourself:
https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/core-AppInsights

**Comment by nzthiago** [comment]
But it does have the entry in the it in the ConversationData bag:
![screen shot 2017-06-28 at 1 43 32 pm](https://user-images.githubusercontent.com/1563288/27659307-d2cb70ae-5c07-11e7-86d6-62408837ab20.png)

**Comment by nwhitmont** [comment]
open a new issue if further questions
