### ISSUE TITLE
[Feature Request] Ability to get Platforms Message on Outbound

### ISSUE THREAD

**Issue by patrickml** [Microsoft/BotBuilder#2420]
Outgoing messages seem to be specific to the BotBuilders framework

![image](https://cloud.githubusercontent.com/assets/7581369/23813354/80ccf28e-05ac-11e7-90b2-2435de8eaa5e.png)

Incoming messages seem to contain the actual platform message via the "sourceEvent" object.

We log all incoming and outgoing messages in the platforms format so we can recreate the users experiences visually.

It would be really great if we could get the Platforms messages in their native format for outgoing as well.

**Comment by patrickml** [comment]
@carlosscastro @dandriscoll is this something that is even possible? What I mean by that, is are the platform-specific message structures generated from the bot or are they translated into them from the botframework platform (dev.botframework.com)

**Comment by patrickml** [comment]
@carlosscastro @dandriscoll any updates on this?

**Comment by dandriscoll** [comment]
Hi @patrickml, the messages are translated within our service. I'm not certain how we would get them back to your bot.

**Comment by patrickml** [comment]
Is there anyway to make an external package that takes someone like me can
use to convert it on the out bound?

**Comment by dandriscoll** [comment]
Sure, the types are all documented, you could create one.

**Comment by nwhitmont** [comment]
@patrickml by "Platform" do you mean "Channel"? Eg. Skype, Slack, Facebook, etc.

Are you using C# or Node SDK for BotBuilder?

**Comment by patrickml** [comment]
Yes channel, and we are using the node SDK ATM.

**Comment by sgellock** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botbuilder-channels/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
