### ISSUE TITLE
Prompt issue - I didn't understand. Please choose an option from the list.

### ISSUE THREAD

**Issue by fricke** [Microsoft/BotBuilder#2421]
Hello, we are experiencing an issue when we prompt a user using the builder.Prompt() function and the user then chooses an option, everything is working great except we get this little message out of our control saying

"I didn't understand. Please choose an option from the list."

I'm not sure why the framework itself would be sending a message out w/o our control.

**Comment by iMicknl** [comment]
The [Prompt](https://docs.botframework.com/en-us/node/builder/chat/prompts/) is a built-in Dialog, which will handle the input validation already. You can change the validation response by using [Namespaced Prompts](https://docs.botframework.com/en-us/node/builder/chat/localization/#namespaced-prompts). I am not aware of any other options at the moment, maybe someone from the Bot Framework team knows?

If you want full control of the Dialog, you should not use the built-in prompt but create a new Dialog yourself.

**Comment by carlosscastro** [comment]
Thanks @iMicknl for chiming in, that is correct. @fricke can you give that a try?

Is this Node.js or C#?

**Comment by fricke** [comment]
Thanks for the help guys.  We've discovered that we aren't using Prompts correctly w/ the waterfall method and we are launch tomorrow so in the meantime we are overriding the text that comes back w/ retryPrompt option in the function.  { retryPrompt: ' ' }.  After launch we will be doing a bit of refactoring to get this in line w/ the waterfall dialog method.

**Comment by carlosscastro** [comment]
Great to hear @fricke , hope you enjoy your bot adventures to come :)
