### ISSUE TITLE
Prompt.text inputs should not go to Luis 

### ISSUE THREAD

**Issue by ubreddy** [Microsoft/BotBuilder#2423]
It seems that all Prompt inputs are being passed on to luis. Is there a way to stop sending Prompt responses by users to Luis API ? 

I am using the following option in Luis recognizer builder.RecognizeMode.onBegin
but still these inputs seem to go to Luis.

or, what am I doing wrong?

**Comment by andradedearthur** [comment]
I have never had this problem, as far as I know they go to the callback method, can you share a bit of code?

**Comment by ubreddy** [comment]
It was my code in bot.use which was closing the dialogue. Sorry, my bad. Thank you.
