### ISSUE TITLE
Bot framework cant find /api/messages

### ISSUE THREAD

**Issue by kunoke** [Microsoft/BotBuilder#2426]
Hello I'm working with Microsoft Bot Framework
I try to make a Skype bot but there is whenever i'm in the bot framework test 404 not found, There is no folder /api/messages and I cant find that folder too in de ftp
But when I try it in visual studio can I find /api/messages
Can anyone help me please?

Here is the test connection!
http://pastebin.com/2VsQGwJx

**Comment by angshuman** [comment]
/api/messages refers to the controller path in your project. Are you using the C# or the Node builder? You should be able to find the controller in Visual Studio. This does not exist as a filesystem path. With the Bot Framework Emulator you should be able to send messages to this controller.
