### ISSUE TITLE
No replies making it out of bot on AWS EC2 (related to #693)

### ISSUE THREAD

**Issue by cgarethc** [Microsoft/BotBuilder#2430]
@dandriscoll wrote:
>Hi @cgarethc, the call back to the channel services is an HTTPS POST sent to the URL identified by the "ServiceUrl" property of the activity your bot is replying to. It is accompanied by a JWT token whose characteristics (and instructions for generating one) are described here: https://docs.botframework.com/en-us/restapi/authentication/
>If you're seeing the call back to the ServiceUrl, and that call is succeeding, then something is wrong either in the message or in our service.
>I can help debug Web Chat pretty easily -- can you send a Conversation ID for a case where you observed the error?
>Opening a new issue may be worthwhile, as we're a ways away from the original question about platform support.

Thanks for this help. The ServiceUrl is coming through as https://directline.botframework.com/ and I've confirmed that I can successfully connect to 443 on that host.

An example conversation from Web Chat for you to debug has the ID 50d33752126a48b1a6f4855d8ac19a55

**Comment by carlosscastro** [comment]
@cgarethc could you please clarify what the problem you're experiencing is?
@dandriscoll do you have context to help @cgarethc debug this?

**Comment by cgarethc** [comment]
Hi @carlosscastro - the original context from #693 is:
>I'm replying to this thread because it's the closest to what I've been tearing my hair out over the last couple of days. I have a Node.JS bot hosted on AWS EC2, with a valid Comodo SSL certificate that works in Chrome/Firefox/Safari and I've configured a bot on the bot framework for my endpoint.
>When I launch the bot framework console at https://dev.botframework.com I can click the "test" button and it says "Accepted". I can also send a message in the embedded web chat, and the logging on my bot on AWS shows the message being received, and a message being sent back with a call to session.send()... but the return message never appears back in the web chat. There are no errors logged on the server side or in the bot framework error viewer, the message just seems to be silently dropped. I added a Skype channel and get exactly the same behaviour in Skype.
>When I deploy the same code to an Azure Web App it all works fine in both directions.
>I'm totally stuck... I can't figure out what could be preventing the return message coming back, and I can't see what steps to take next for troubleshooting. It's not clear from the docs how a message is sent back to the framework, is there a particular host/IP/port I should be probing from EC2 to see if something is in the way? There are no outbound rules in my AWS security group that would prevent a connection, e.g. "telnet directline.botframework.com 80" succeeds.

**Comment by carlosscastro** [comment]
Thanks for the details. @dandriscoll please take a look :)

**Comment by cgarethc** [comment]
So it turns out that the problem is that in moving to EC2 I had failed to set the App ID and password for the bot framework (I'm supplying them as environment variables). Supplying an undefined value to the "appId" and "appPassword" parameters of the map to the ChatConnector constructor is a valid input: it appears to the connector as if no values have been set, and the connector enters testing mode and works fine with the emulator.

For some reason the bot framework console (at https://dev.botframework.com/bots) doesn't report an error when a the bot sends a message back to the framework with no authentication, and for some reason the "Test connection to your bot" shows "Accepted" with no authentication. I tried with an invalid appId and appPassword, and it reports "Forbidden". If it did also did this when connecting to a bot running with no appId and appPassword it would help a lot with troubleshooting.

**Comment by Niladri24dutta** [comment]
@cgarethc If my understanding is correct then when I deploy a C#/node js bot to AWS EC2 instance as a REST API , I still need to register it for App id and password to make it available to channels like Skype. 
So in your case how you handled the app id and password in AWS to make it available for Channels.
