### ISSUE TITLE
Problem in azure sites.

### ISSUE THREAD

**Issue by HalwestRasul** [Microsoft/BotBuilder#2431]
hi, I have a problem while I created a site in azure portal, when I visit to my site the site gives me a message "**`You do not have permission to view this directory or page.`**", and while I tested connection in [dev.botframework](https://dev.botframework.com/) it gives me another message "**`MethodNotAllowed The page you are looking for cannot be displayed because an invalid method (HTTP verb) is being used.`**"
# what should I do?

> note: my bot written in Node.js, and my account subscription is free trial :( ,

**Comment by HalwestRasul** [comment]
please advice me! :/
@Stevenic @willportnoy @eanders-MS @carlosscastro

**Comment by bondz** [comment]
@HalwestRasul Can you send your bot a message from the portal?

**Comment by HalwestRasul** [comment]
###   _@bondz_ thanks for your replay, see this image, do you mean this?

![sketch](https://cloud.githubusercontent.com/assets/10852176/23868874/28e71a30-0832-11e7-9bc3-da0667f39d3d.png)

**Comment by bondz** [comment]
Did you create the bot from Azure? If you did, your `messaging endpoint` should look like `https://bot.azurewebsites.net/api/messages?code=AReallyLongAlphanumString==`

You can see how to create a bot on azure [here](https://docs.botframework.com/en-us/azure-bots/build/first-bot/#navtitle)

If you already have a bot on azure, you can setup continuous integration by following the instructions [here](https://docs.botframework.com/en-us/azure-bot-service/manage/setting-up-continuous-integration/#navtitle)

And you can copy your messaging endpoint on the `channels` tab.

**Comment by hailiu2586** [comment]
if you created an Azure bot service, then as @bondz said, the endpoint should contain query param code='...'

At this point, you may want to delete and re-create the azure bot service

**Comment by HalwestRasul** [comment]
@bondz , @hailiu2586 thanks allot,
