### ISSUE TITLE
Reliability issue on botframework

### ISSUE THREAD

**Issue by ubreddy** [Microsoft/BotBuilder#2432]
I keep getting this error, once a while in production and the messages dont end up showing in Skype/ Web.

How can this be overcome in production. It appears unreliable and users are unhappy. Or, am I doing something wrong.

Request to 'https://smba.trafficmanager.net/v3/conversations/29%3A10hZoGeaCfWX4Lpkd33wjtUUC1-HEH3YDQF5csOsZDhc/activities' failed: [400] Bad Request
    at Request._callback (D:\home\site\wwwroot\node_modules\botbuilder\lib\bots\ChatConnector.js:413:46)
    at Request.self.callback (D:\home\site\wwwroot\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:192:7)
    at Request.<anonymous> (D:\home\site\wwwroot\node_modules\request\request.js:1081:10)
    at emitOne (events.js:96:13)

**Comment by konstlut** [comment]
@ubreddy for this conversation the problem happened 6 times on 3/13 and the reason is always the same:

` Response code: BadRequest Body: {"error":{"code":"BadSyntax","message":"Invalid image URI"}} `

which means your message activity contains some card as payload with an invalid image url. 
Could you please share the payload sample you are sending?

**Comment by ubreddy** [comment]
Got it fixed. Thank you.On 14-Mar-2017 7:52 PM, Konstantin Lutskiy <notifications@github.com> wrote:@ubreddy for this conversation the problem happened 6 times on 3/13 and the reason is always the same:
Response code: BadRequest Body: {"error":{"code":"BadSyntax","message":"Invalid image URI"}}
which means your message activity contains some card as payload with an invalid image url.
Could you please share the payload sample you are sending?

**Comment by shekarkadaba** [comment]
@ubreddy are you able to share what the resolution was?
