### ISSUE TITLE
"no security token sent." with Microsoft Teams

### ISSUE THREAD

**Issue by juharris** [Microsoft/BotBuilder#2434]
I'm trying to set up a bot with a Microsoft Teams channel and I get `ERROR: ChatConnector: receive - no security token sent.` when a message is sent in a channel mentioning the bot but replies to individual messages do work fine and the bot replies as expected.

Here's my app.js:
```
require('dotenv-extended').load();

var builder = require('botbuilder');
var restify = require('restify');

var server = restify.createServer();
server.listen(process.env.port || process.env.PORT || 3978, function () {
    console.log('%s listening to %s', server.name, server.url);
});

var connector = new builder.ChatConnector({
    appId: process.env.MICROSOFT_APP_ID,
    appPassword: process.env.MICROSOFT_APP_PASSWORD
});

server.post('/api/messages', connector.listen());

var bot = new builder.UniversalBot(connector, function (session) {
    session.send("Hi");
});
```

The bot does reply to the Teams channel but the message is always "Sorry, there was a problem encountered with your request"

The logs show HTML for a 401 error page. It says:
```
Most likely causes:
   The authenticated user does not have access to a resource needed to process the request.
...
Detailed Error Information:
    ...
    Requested URL	   https://MaDinnerBot:80/app.js
    Physical Path	   D:\home\site\wwwroot\app.js
...
```

Is there somewhere where I should be setting a token? I did get a token when adding the bot to Teams but I'm not sure where to put it. Thanks.

Relates to #1505

**Comment by FranciscoPonceGomez** [comment]
Hi juharris,
I will look into this.

**Comment by FranciscoPonceGomez** [comment]
I tried your code and it worked for me. If you are testing remotely please make sure you have Ngrok installed and correctly configured for tunneling:

https://ngrok.com/
https://github.com/Microsoft/BotFramework-Emulator/wiki/Tunneling-(ngrok)

If you are using the Bot Framework emulator to test, make sure that you have the latest version.

This is the version of the dependencies I have used:
    "botbuilder": "^3.7.0",
    "dotenv-extended": "^1.0.4",
    "restify": "^4.3.0"

Please make sure that everything is up to date.

**Comment by juharris** [comment]
Thanks! I thought that ngrok is just for when you're running locally?  I'm running the bot on Azure. So are you saying that I should set up ngrok on my Azure instance?

**Comment by FranciscoPonceGomez** [comment]
You need kgrok in order to create a tunneling when you debug remotely. It is not necessary if you have the source code in your own machine and want to debug locally.  My guess is that maybe you haven't specified the password and ID correctly in Azure. Here's a small tutorial on how to specify AppID and password when publishing your bot. 

https://docs.botframework.com/en-us/node/builder/guides/deploying-to-azure/#step-3-set-up-continuous-deployment-to-azure-from-your-github-repo

**Comment by juharris** [comment]
I'm not really debugging remotely, I'm just trying to use the bot with Teams.  I wouldn't really call that debugging. So just to be clear, should I set up ngrork when deploying on Azure?

I set the AppID and password in Azure, otherwise I wouldn't get responses from the bot in chat right?  The bot does reply when you send a message directly to it.

**Comment by FranciscoPonceGomez** [comment]
Sorry for the confusion. No. You don't need Ngrok in order to deploy and communicate normally with the bot.  I just mentioned Ngrok in case you wanted to debug your bot in order to see what is going on.  Because otherwise is difficult to spot the problem. I will try to reproduce the issue. Do you use other channels or just MS Teams?

**Comment by juharris** [comment]
Just MS Teams for now.

**Comment by pojer-s** [comment]
Hi,
It's not working with the Teams Conversation. When I check the request header, I can see a problem with the authorization token: it's look like "HMAC TOKEN" instead of "BEARER TOKEN" (expected by the module with this following condition: "if (auth.length == 2 && auth[0].toLowerCase() == 'bearer') {"). The problem can come from that?

**Comment by RichMoeMSFT** [comment]
The original poster's code is very straight forward and should work.  A few things to check:
- Validate you can even hit your bot - easiest to check in Bot Framework
- Bot ID and Password are being set correctly, to match the entries from Bot Framework
- Microsoft Teams has been enabled as a channel in Bot Framework
- (This is a common cause of silent failures:) Ensure the Teams tenant admin has enabled bots and sideloading of bots in the Office Admin portal (https://msdn.microsoft.com/en-us/microsoft-teams/setup#enable-sideloading-of-bots-and-tabs)
- For sideloading a bot onto a team so it will work in channels, follow the instructions here: https://msdn.microsoft.com/en-us/microsoft-teams/sideload

Agree that running locally with ngrok is a great way to debug but it's most likely one of the above steps.

**Comment by juharris** [comment]
Thank you for your response.

* I've made sure that my dependencies are up-to-date:
```
 "dependencies": {
    "botbuilder": "^3.7.0",
    "restify": "^4.3.0",
    "dotenv-extended": "^1.0.4"
  }
```

* Like I said, I can hit the bot as it does reply to personal messages in Teams.  It also replies on dev.botframework.com and the test says Accepted.

* The Bot ID and Password are being set correctly in the Azure instance's "App settings".

* Microsoft Teams has been enabled as a channel in Bot Framework.

* I'm pretty sure that bots are enabled for Teams since I'm a Microsoft employee... BTW Feel free to message me on Teams to discuss this :)

* The docs on sideloading imply that it's mainly for development. The bots I'm making will be pretty simple and internal so I'd rather just test in production since we'll be using them soon anyway.

I also get a new error in the logs that make an HTML page that says:
```
HTTP Error 404.0 - Not Found
The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.
...
Handler	   StaticFile
...
Logon Method	   Anonymous
Logon User	   Anonymous
Requested URL	   https://MaDinnerBot:80/api/messages
Physical Path	   D:\home\site\wwwroot\api\messages
```

* What should I do with the token that I got when I added the bot to the Microsoft Teams team?

Thanks!

**Comment by juharris** [comment]
I tried again even with setting it up a Linux server manually and got the same issue when adding a custom bot with a URL to Microsoft Teams.
Instead, I got it to work when sideloading.

**Comment by flowl** [comment]
I have the same problem and it's not fixed or there is no helpful comment or site. I can do 1on1 chat with the bot by first publishing the bot then add "custom bot" in MS Teams. There is an APP ID, an APP PASSWORD and this security token from MS Teams. I am using node.js from this site: https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-quickstart

None of this is working with MS Teams Channels/Groups.

**Comment by JasonSowers** [comment]
@flowl can you please open a new issue

**Comment by aseemrastogi** [comment]
Hi - I have the exact same issue. Any direction to resolve?

**Comment by justinh00k** [comment]
?
