### ISSUE TITLE
Skype channel in Error Status

### ISSUE THREAD

**Issue by galazzo** [Microsoft/BotBuilder#244]
Using Microsoft Bot Framework I started to use GetBotPerUserInConversationData

Everything works great with webchat and Facebook channels but if message come from Skype I get the following exception:

'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.Bot.Connector.dll

I get also amessage about string.this[int], arguments not valid for best matching overlod method.

Here the very simple code:

var state = message.GetBotPerUserInConversationData<ConversationState>("State");

My class is Serializable

[Serializable]
public class ConversationState
{
    public ConversationState()
    {

By the way, why the same code works great with all channels except Skype?

Sebastiano

**Comment by craigjensen** [comment]
What type are you setting in your call to message.BotPerUserInConversationData = ???.  If this is set to a string any subsequent call to message.GetBotPerUserInConversationData("State") will result in that RuntimeBinderException. To avoid this exception make sure you set BotPerUserInConversationData to a valid object type.

**Comment by inornos** [comment]
Skype channel in Error Status
same problem any solution please
![image](https://cloud.githubusercontent.com/assets/14770190/15505011/3c62283c-21df-11e6-8e2d-3b33a57a6aef.png)

**Comment by craigjensen** [comment]
Please add your botId and we'll investigate

**Comment by inornos** [comment]
Where and how to add botid

**Comment by inornos** [comment]
i have added my bot id and app secret in web.config but still not working for me
please help me

**Comment by inornos** [comment]
I'm using Microsoft Bot Framework Emulator and its working with my online API, its responding me right but in Skype bot not working it not responding correctly its giving me error

![image](https://cloud.githubusercontent.com/assets/14770190/15533912/3966b652-2284-11e6-8f4e-d3f81ee293ef.png)


problem

![image](https://cloud.githubusercontent.com/assets/14770190/15533934/44b7f8cc-2284-11e6-9977-28760ffcfcb1.png)

**Comment by craigjensen** [comment]
![image](https://cloud.githubusercontent.com/assets/18585246/15546976/cc0eb01e-2256-11e6-8ef3-df32b4e004d4.png)
Looks like it's working now.  Would you mind sharing what the fix was so others might benefit?

**Comment by inornos** [comment]
In my Web.config I'm using Bot Registration App ID And App Secret There is the my problem of the getting Forbidden Error
So don't use Bot Registration App ID and App Secret
![image](https://cloud.githubusercontent.com/assets/14770190/15563701/f261ca44-2328-11e6-910f-a7bfc013ef79.png)

To Set Web.config take App ID And App Secret from this section given below in image
![image](https://cloud.githubusercontent.com/assets/14770190/15563826/0bf34a72-232a-11e6-8b87-be8fcf1afd5b.png)

**Comment by v-thgratMSGit** [comment]
Closing this issue.  Thanks for sharing your fix @inornos!  @galazzo - please open a new issue for further discussion if necessary.
