### ISSUE TITLE
Image URL with redirect is considered invalid

### ISSUE THREAD

**Issue by juhamust** [Microsoft/BotBuilder#2442]
Attachment URL like http://lorempixel.com/400/200/sports is not shown in MS Teams or Skype:
```
# Log entry in https://dev.botframework.com/
Attached content from http://lorempixel.com/400/200/sports is invalid
```

This is because the actual URL is http://lorempixel.com/400/200/sports/ (service does return headers correctly).

NOTE: Bot Framework Emulator does show both URLs correctly (so not quite sure if the issue is in Skype and Teams instead of BotBuilder?)

**Comment by RichMoeMSFT** [comment]
Are you attaching to your outbound message with the paperclip icon?

**Comment by juhamust** [comment]
I'm not quite sure what you're after @RichMoeMSFT but this is how I'm building the message:

```
const msg = new builder.Message(session)
  .text('Hello world!')
  .attachments([
    { contentType: 'image/jpeg', contentUrl: 'http://lorempixel.com/400/200/sports/' },
  ]);

bot.send(msg, (err) => {
  session.endDialog();
});
```

**Comment by juhamust** [comment]
Just noticed: Redirection works and image is shown _when used within card_:
```
new builder.HeroCard(session)
  .title('Image of the day')
  .subtitle('Provided to you by Lorempixel')
  .images([
    builder.CardImage.create(session, 'http://lorempixel.com/400/200/sports'),
  ])
```

**Comment by mgbennet** [comment]
It does sound like this is an issue with the channels rather than Bot Framework. Glad you found a solution.
