### ISSUE TITLE
send user data along with user confirm choice to next function

### ISSUE THREAD

**Issue by aakashvit** [Microsoft/BotBuilder#2443]
I want to send some data to next function along with user confirm choice.. How we can do that. OR it is possible to catch user confirm choice in same function , from where we are sending session.confirm..

bot.dialog('/assignchoice', [
    function (session, args) {
	    var data={"key1":"value1","key2":"value2"}
	    builder.Prompts.confirm(session,"Are you sure you want to assign");
	     
	    },
   function (session, result) {
	     //here data
	     console.log(result.response)//will display true or false
	    }
 
]);

**Comment by aakashvit** [comment]
@carlosscastro can you suggest me alternate option for this

**Comment by aakashvit** [comment]
One option i know .to set in session data and we will get from session again.. but that's not right way.. because limit size  of session data..

**Comment by mgbennet** [comment]
You're running into the 65kb limit for session.dialogData or session.conversationData? You could gzip the data by adding `gzipData: true` to the ChatConnector constructor object, which will give you more space to work with, but it's still not unlimited.

There might be alternate work-arounds based on your exact use case, like reducing how much data you need to pass or getting the data within the function, but the preferred way to pass data through dialogs is with session data.

**Comment by tomlm** [comment]
it is also possible to use your own state provider see
https://docs.botframework.com/en-us/node/builder/calling-reference/interfaces/_botbuilder_d_.ibotstorage.html
