### ISSUE TITLE
Pre-Built & Skype

### ISSUE THREAD

**Issue by balasundarr** [Microsoft/BotBuilder#245]
1. In case if I want to define pre-built model. Should I extend Corona? If so how can I do it !.
2, I am facing  an issue in skype intergration. I have created Microsoft App using my account. How Bot is linked with my Microsoft App. Second in skype It is prompting for Application ID with GUID where as my id is text. Appreciate your help

**Comment by Stevenic** [comment]
You can't actually extend the pre-built models. We've had a number of requests to support chaining LUIS models which would be essentially how you'd extend the pre-builts. I provide an example of how to do this today in issue #128.

When you add your Skype channel in the [Bot Framework Developer Portal](http://botframework.com) we walk you through all of the steps to register your bot with skype. Did you have problems following those steps?
