### ISSUE TITLE
[Docs] File missing: csharp/documentation/docs/html/Index.html 

### ISSUE THREAD

**Issue by IAmSequestered** [Microsoft/BotBuilder#2459]
It's referenced in the project, it and it's parent folder are missing from the hard drive, and it's not in Git.

**Comment by nwhitmont** [comment]
@IAmSequestered for reference, what file and line number is pointing to this file?

**Comment by Andrea-Orimoto** [comment]
@IAmSequestered, can you please be more specific and say where this reference is?

**Comment by nwhitmont** [comment]
@IAmSequestered You can find the SDK documentation here: https://docs.botframework.com/en-us/azure-bot-service/templates/proactive/
