### ISSUE TITLE
Release Mode Build failed

### ISSUE THREAD

**Issue by kevinport** [Microsoft/BotBuilder#2461]
Is there any reason for the compiler constant "NET45" in Micorosft.Bot.Connector project?

In Debug mode the whole code compiles without errors, but in release mode not.

In noticed, that in debug mode the compiler symbol is set:
![image](https://cloud.githubusercontent.com/assets/20930799/24071513/fba7074c-0bd3-11e7-85a2-c8f2bcb0e5f0.png)

but in release mode not.
![image](https://cloud.githubusercontent.com/assets/20930799/24071515/0e13a854-0bd4-11e7-9f69-eeea9ae45119.png)

If i add the constant in release mode too, the whole Micorosft.Bot.Builder Solution compiles without any errors...

**Comment by tomlm** [comment]
That is an mistake, it should be set in both platforms.  You can always submit a pull request if we don't get to it.

**Comment by msft-shahins** [comment]
https://github.com/Microsoft/BotBuilder/commit/933995cfe009976ca2f81340009eccf31dee7498 fixes this.

**Comment by kevinport** [comment]
thank you
