### ISSUE TITLE
REST API not working

### ISSUE THREAD

**Issue by baole** [Microsoft/BotBuilder#2467]
I'm creating a bot using REST API. Indeed, I want to send a message from my bot to me as following

Step 1: Authentification
Request:
`curl -k -X POST https://login.microsoftonline.com/botframework.com/oauth2/v2.0/token -d "grant_type=client_credentials&client_id={app_id}&client_secret={app_password}&scope=https://graph.microsoft.com/.default"
`
Response:
```
{
  "token_type": "Bearer",
  "expires_in": 3599,
  "ext_expires_in": 0,
  "access_token": "<access_token>"
}
```

Next, I start a new conversation
Request:
```
POST https://skype.botframework.com/v3/conversations
Authorization: Bearer <access_token>
Content-Type: application/json
{
    "bot": {
        "id": "standupalice",
        "name": "Standup Alice"
    },
    "isGroup": false,
    "members": [
	    {
	        "id": "<my bot id>",
	        "name": "Standup Alice"
	    },
	   {
	        "id": "<my user id>",
	        "name": "Bao"
	    }
    ],
    "topicName": "News Alert"
}
```

NOTE: <my bot id> and <my user id> are obtained from a callback message sent from Skype app to Standup Alice bot.

Response:
```
{
  "id": "<conversation id>"
}
```

It's weird since the conversation ID is identical to  <my user id>. Well, now I compose a message to send to me as following
Request:
```
POST https://skype.botframework.com/v3/conversations/<conversation id>/activities
Authorization: Bearer <access_token>
Content-Type: application/json
{
    "type": "message",
    "from": {
        "id": "<my bot id>",
        "name": "Standup Alice"
    },
    "conversation": {
        "id": "<conversation id>",
        "name": "News Alert"
   },
   "recipient": {
        "id": "<my user id>",
        "name": "Bao"
    },
  "channelId": "skype",
    "text": "My bot's reply"
}
```

Response (http error 400 - bad request):
```
{
  "error": {
    "code": "ServiceError",
    "message": "The conversationId <conversation id>and bot <my bot id> doesn't match a known conversation"
  }
}
```
Do you have an idea what's wrong with my requests and parameters?

PS: I tried to fire request to https://**api**.botframework.com/v3/conversations as described in https://docs.botframework.com/en-us/core-concepts/overview/#navtitle, but always receives http error 404 - Resource not found.

**Comment by baole** [comment]
I just tried the same way for webchat and it works fine, but MS Teams doesn't work

**Comment by baole** [comment]
![image](https://cloud.githubusercontent.com/assets/1460168/24132667/92b463ee-0df7-11e7-8eab-08fa972b0f38.png)

My bot is enabled for webchat, Skype and MS Teams.

**Comment by baole** [comment]
Any one can helps?

**Comment by dandriscoll** [comment]
Hi @baole, did you hardcode skype.botframework.com into your bot?

You can find more information on this issue in #2005.

**Comment by baole** [comment]
It works fine with #2005's solution. Thanks

**Comment by inzi25** [comment]
@baole 
I am trying same for MS team. but i couldn't able to get the conversation ID. Here I have attached the image. Appreciate if you can help.
![image](https://user-images.githubusercontent.com/10509895/30361629-bb6140a6-9875-11e7-83e3-40de351133ca.png)

**Comment by inzi25** [comment]
@baole further to those information, I have doubt on the id what i'm passing. If you can explain where I can get those much appreciated.
