### ISSUE TITLE
IVR calling via Twilio

### ISSUE THREAD

**Issue by lokeshlal** [Microsoft/BotBuilder#2468]
Hello,

I am trying to make botframework work with Twilio calling.

However, I am not sure which api should I be providing as web hook at Twilio.

I tried all urls /api/calling , /api/calling/call , /api/calling/callback

does botframework supports Twillio, and what should be callback, as botframework will require BotAuthentication and other stuff as well.

Thanks,
Lokesh

**Comment by lokeshlal** [comment]
If I save the bot state in local storage and mock the behavior of passing activities in a similar fashion to bot framework..than will it work with Twillio?

**Comment by tomlm** [comment]
I don't think this is supported via the bot framework protocol.  I think you will have to talk to twilio API directly.

**Comment by lokeshlal** [comment]
Thank you for your response.

I used directline to integrate bot with Twilio callback API and it is working absolutely fine.

Thanks

**Comment by chixcancode** [comment]
Do you happen to have any samples of how you did this?  Does this means you mainly just leveraged the Twilio Voice or did you use any speech-to-text api's from microsoft?

**Comment by lokeshlal** [comment]
@chixcancode No twilio voice was not accurate, even watson and google speech to text apis were not accurate in few cases (such as email address). So we decided to drop the concept of running chat bot on IVR. I will post the code sample in a while for your reference.

**Comment by khalid-halo** [comment]
Hi Lokesh, Can you please share the sample? Were you able to pro-actively call certain number?

**Comment by IyyappanAmirthalingam** [comment]
@lokeshlal  Could you please post the code and configuration information in the twilio ?

**Comment by YhorbyMatias** [comment]
anyone here has implemented that?
