### ISSUE TITLE
[Direct Line] Token Generation API 400 Error

### ISSUE THREAD

**Issue by suminksudhi** [Microsoft/BotBuilder#2470]
Hi,

I am using botframework for my chatbot.
The token generation api was working till yesterday but as of today getting issue with token generation api its returning status 400
```
 {
  "error": {
    "code": "ServiceError",
    "message": "Bad request"
  }
}
```
I took reference for implementation from
ref: https://docs.botframework.com/en-us/restapi/directline3/

I am passing the token api generated from the bot panel for directline and passing as header for generating token
However the same api works fine in the webchat panel provided for testing.

**Comment by nwhitmont** [comment]
@suminksudhi are you using C# or Node SDK?

**Comment by nwhitmont** [comment]
@suminksudhi reopen this issue if you are still experiencing problems.

**Comment by suminksudhi** [comment]
@nwhitmont: 
Had wriiten a wrapper in javascript to suite my need based on documentation in directline api documentation and reference to Node sdk. 

Same issue was observed when I latter used the provided Node sdk with my bot

**Comment by suminksudhi** [comment]
@nwhitmont 

I am having a hard time finding how to reopen issue and found something.
http://stackoverflow.com/questions/21333654/how-to-re-open-an-issue-in-github

Please help me out.

**Comment by nwhitmont** [comment]
@suminksudhi are you using Node or C# SDK for BotBuilder? Do you have a code example that reproduces the issue?

**Comment by suminksudhi** [comment]
I think I know the issue. 
I was making a request from browser which return 400 as statuscode PFA for mentioned error
![bot error](https://cloud.githubusercontent.com/assets/2181531/24895410/dd5a36aa-1ead-11e7-9e66-866e3bb488f0.PNG)

I tried reproducing same using nodejs but it works well over there giving statuscode 200
below  is the snippet.

So my next query is why suddenly stop support for browser/xhr requests. Because same code was working earlier for me (about a month back) now it returns 400

var request = require('request');
var options = {
  url: 'https://directline.botframework.com/v3/directline/tokens/generate',
  method: 'POST',
  headers: {
    'Authorization': 'Bearer lOhqisy5gA4.cwA.wxU.f_EMPudetCyPNHo1xevwFZ01PT4ly2U579P2tN8JG-Y'
  }
};
 
function callback(error, response, body) {
  if (error){
	return console.log("error",error);
  }
  
  console.log("response",response.statusCode);
}
 
request(options, callback);

**Comment by nwhitmont** [comment]
@suminksudhi thanks for the update. I'm glad you found a solution to this issue.

As far as why the Direct Line API might have changed, I don't have a specific answer, but keep in mind all Bot Framework services, such as Direct Line, are in Preview state, and are under active development, so things do tend to change as we improve the service.

**Comment by JobaDiniz** [comment]
@suminksudhi  @nwhitmont I'm trying to make a HTTP POST request, without any sdk, using raw http requests in c# and api returns the same error
```
 {
  "error": {
    "code": "ServiceError",
    "message": "Bad request"
  }
}
```
I am following https://docs.microsoft.com/en-us/bot-framework/rest-api/bot-framework-rest-direct-line-3-0-authentication , that is, passing `Bearer: SECRET` in the header
How to solve this?

**Comment by JpEncausse** [comment]
Hi, we have the same issue,
Is there a new API to retrieve a token from a secret ? or does this feature is dead ?

**Comment by EricDahlvang** [comment]
@JpEncausse The api for exchanging a secret for a token has not changed.  Please open a new issue if you are experiencing problems with the API.  https://github.com/Microsoft/BotBuilder/issues/new

**Comment by JpEncausse** [comment]
Ah thanks got it ! We found where the request broke (related to an other component)
