### ISSUE TITLE
dialogData not forwarded to next function?

### ISSUE THREAD

**Issue by maba4891** [Microsoft/BotBuilder#2471]
In my nodejs application I try to forward some data through the dialogData object to the next function:

```
bot.dialog('foo', [
    function (session, args) {
        builder.Prompts.text(session, "What's your name?"); 
        session.dialogData.bar = args.bar; // bar is set to true
        console.log(session.dialogData.bar); // output: true
    },
    function (session, results) {
        console.log(session.dialogData.bar); // output: undefined!
   }
]);
```

I thought that - according to the documentation - session.dialogData is "visible to the current dialog." (see [here](https://docs.botframework.com/en-us/node/builder/chat-reference/classes/_botbuilder_d_.session.html#dialogdata))
So why do I get an undefined in the second function? Shouldn't I have access to the dialogData object in the second function as well? Is this a bug or am I missing something?

If it's not a bug but my stupidity I am happy to bring this to stackoverflow instead :)

**Comment by mgbennet** [comment]
It sort of looks like a bug.... If you move the `session.dialogData.bar = args.bar;` above the prompt, it works fine, with bar being set and available in the next step of the waterfall. The prompt remembers the session data from when it was called, so any changes made in the waterfall step after the prompt is fired will be forgotten in the next step. This is also true of userData and conversationData. 

So in most cases it's easy enough just to call the prompt as the last line of code in a waterfall step.

**Comment by maba4891** [comment]
That fixed it for me, thanks!
