### ISSUE TITLE
Replying to Facebook With Error Response Seems to Result in 200 to Messenger

### ISSUE THREAD

**Issue by devildog** [Microsoft/BotBuilder#2475]
v3.0 of the bot framework
I am replying to a Facebook payment request with a 500 status code, however based upon Facebook's response it doesn't appear the 500 response is sent or makes it to messenger platform.

Payment requests come in as type "invoke" to our controller:
Activity.type == "invoke"  which is then processed and we either return 200 or a 500. However all responses seem to result in a 200 response to Facebook.
 
Attempted:

Standard reply:
```
            ConnectorClient connector = new ConnectorClient(new Uri(activity.ServiceUrl));
            Activity replyToConversation = activity.CreateReply();
            replyToConversation.Recipient = activity.From;
            replyToConversation.Type = "message";
            connector.Conversations.ReplyToActivity(replyToConversation);
```
Or
```
            return Request.CreateResponse(HttpStatusCode.InternalServerError);
```
Or
 ```
              return null;
```

Some details on actual call response in this closed bug
https://github.com/Microsoft/BotBuilder/issues/1859

**Comment by JasonSowers** [comment]
DevilDog, has you issue been resolved or are you still having this issue?

the lastest bot builder version can be found here https://www.nuget.org/packages/Microsoft.Bot.Builder/

**Comment by nwhitmont** [comment]
reopen if you're still experiencing the issue after upgrading to BotBuilder v3.8.1
