### ISSUE TITLE
Skype Error: internal channel failure

### ISSUE THREAD

**Issue by Noc2** [Microsoft/BotBuilder#2476]
In last few days I sometimes get the following message (I think since I updated to 3.5.5):
“There was an error completing this request due to an internal channel failure.”

It appears only on skype. Facebook Messenger seems to work fine. 
Does anyone know what this means?

**Comment by fanidamj** [comment]
[Tips to troubleshoot](https://docs.botframework.com/en-us/technical-faq/#how-can-i-troubleshoot-my-bot) and consider attaching a debugger or using App Insights to get more details.

**Comment by konstlut** [comment]
@Noc2 Could you please share your bot msa app id, and I will search backend logs for errors. Thank you!

**Comment by Noc2** [comment]
Microsoft App ID is 64ba2a82-af90-43f0-8aea-42a95405a1ba
Since a few days I’m using App Insights, but I couldn’t determine the exact source of the problem.
I’m currently rewriting a lot of the code of my bot. I hope that will improve the performance and solve this problem.
At the beginning, I came up with my own solution for multiple dialogs, state, and IScorable, which probably wasn’t a good idea ;-).

**Comment by aery-aery** [comment]
@Noc2 Could you please also share what kind of request and payload did you try to send?

**Comment by Noc2** [comment]
Thanks. Problem seems to be solved.

**Comment by Noc2** [comment]
Since the last week, I have this issue again. After some further testing with ngrok, I think the problem appears when Request.CreateResponse(HttpStatusCode.OK) isn’t send in a certain time window (around 10 seconds, probably because of slow API calls). 
Getting another error message, in this case, might be helpful.

**Comment by annevah** [comment]
I am having the same issue. Getting the message **There was an error completing this request due to an internal channel failure.**  
I am using ngrok to debug my bot code at the ngrok endpoint OPTIONS /api/messages is being invoked instead on POST/api/messages. Any help?
