### ISSUE TITLE
[Feature Request] Use Task-based Asynchronous Pattern (TAP) consistently across SDK especially PromptDialog

### ISSUE THREAD

**Issue by DL-LiveTiles** [Microsoft/BotBuilder#2477]
PromptDialog use asynchronous callback pattern instead of TAP (async and await). This complicates logic implementation and is inconsistent with the rest of the SDK.

**Comment by nwhitmont** [comment]
@DL-LiveTiles are you referring to the C# or Node SDK?

**Comment by DL-LiveTiles** [comment]
@nwhitmont C#

**Comment by EricDahlvang** [comment]
Hi @DL-LiveTiles,

The async methods in PromptDialog.cs seem to me to be consistent with the rest of the SDK.  Would please elaborate on what you mean exactly?  

Thanks.

**Comment by DL-LiveTiles** [comment]
Hi @EricDahlvang,

Implementing a separate call-back method for each prompt makes the bot code messy and long.
Currently the code would be:
`...
   PromptDialog.Text(context, TextProvided, "Enter text value.");
}
async Task TextProvided(IDialogContext context, IAwaitable<string> argument)
{
   string value = await argument;
}` 

I would simply like to do:
`string value = await PromptDialog.Text(context, "Enter text value.");`

This would make the bot code much easier to follow and simpler to implement.
I believe with some changes to the SDK this would be possible using [TaskCompletionSource
](https://msdn.microsoft.com/en-us/library/dd449174(v=vs.110).aspx)

Similar to what is suggested here: [Best way to convert callback-based async method to awaitable task](http://stackoverflow.com/questions/11879967/best-way-to-convert-callback-based-async-method-to-awaitable-task).

Regards,

Douw

**Comment by EricDahlvang** [comment]
Thanks for your suggestion.  I agree, it would be more simple for devs to be able use async/await.  I'm not knowledgeable regarding what the implications would be if we made this change.  I've discussed it with the engineers and:

> async/await  is for the “task augmented value”, not the “wait for user input augmented value”.  

Nonetheless, if you feel up to it, you can make the change and submit a pull request.  Microsoft.BotBuilder is open source.

Again, thanks for your suggestion.

**Comment by Ma3yTa** [comment]
@DL-LiveTiles I tried to do like you say but message doesn't send
![](https://i.gyazo.com/84e6f56414667d4145c1e21971d39311.png)
Did you have success with it?
```
var text = await PromptDialogExt.TextAsync(context, "Enter some text");
......

public static class PromptDialogExt
    {
        public static Task<string> TextAsync(IDialogContext context, string text)
        {
            var tcs = new TaskCompletionSource<string>();
            PromptDialog.Text(context, async (c, r) =>
            {
                try
                {
                    var result = await r;
                    tcs.TrySetResult(result);
                }
                catch (Exception ex)
                {
                    tcs.TrySetException(ex);
                }
            }
            , text);
            return tcs.Task;
        }
    }
```

**Comment by Ma3yTa** [comment]
@willportnoy Could you please check if async dialog prompts can be achieved with current codebase?
Thanks.

**Comment by willportnoy** [comment]
@Ma3yTa that code won't work because the closure is capturing the TaskCompletionSource and that TaskCompletionSource won't useful be persisted until the next turn of conversation (e.g. which could run on another machine entirely).

**Comment by Ma3yTa** [comment]
@willportnoy Thanks for your answer. Does it mean that Task-based Asynchronous Pattern can't be implemented for PromptDialog methods?

**Comment by Ma3yTa** [comment]
@willportnoy I think it can be achieved when IDialogStack.Call method return IAwaitable<T>

``IWaitable<T> Call<R>(IDialog<R> child)``

**Comment by willportnoy** [comment]
@Ma3yTa the difficulty is that when the next message in the conversation is sent to the bot, that code that is [efficiently, asynchronously] waiting on the next message may not be the machine that receives the message because it is behind a load balancer.

**Comment by Ma3yTa** [comment]
@willportnoy Understood now. Thanks for your reply.
I think promise-like interface will look better in code than callbacks.
Then no need to pass context in callbacks because we already have it.
```
PromptDialog.Text(context, "Enter text value.")
.OnComplete(result => ... )
.OnError(ex=>....);
```
