### ISSUE TITLE
Bot becomes slow unless you delete user data

### ISSUE THREAD

**Issue by slidenerd** [Microsoft/BotBuilder#2479]
I am running a custom prompt that is basically a type of Math quiz. It asks a question and gives 3 choices. If the person answers correctly, the game goes on. The game goes indefinitely till the person answers incorrectly. I am noticing some issues in the loop in this scenario.

**Scenario 1**
After playing say 100 questions or so, I notice that the time it takes to register a response after the user clicks the button slowly increases. In simple words the lag is slowly increasing. Here is a GIF demonstrating the lag in action

![bot framework emulator chat connector example](https://cloud.githubusercontent.com/assets/5139030/24187095/7b693aec-0f01-11e7-9f21-eef745b559d0.gif)

**Scenario 2**
I quickly delete user Data and the thing works again with 0 lag. But lets say I play for a good number of questions and slowly the lag starts creeping back in. The 0 lag situation after clearing user data is shown in the GIF below
![bot framework emulator chat connector example2](https://cloud.githubusercontent.com/assets/5139030/24187137/a3c38baa-0f01-11e7-87be-d12f72bad4f9.gif)

I benchmarked my code that generates the quiz and it always runs under 0.001 seconds which means the lag issue is arising from the bot framework

[HERE's](http://pastebin.com/mGMiS4wD) the code. [THIS](http://pastebin.com/uWdBX1Tb) is the code from where I call the custom prompt

The amount of data in the loop is not ever increasing
Would the lag be due to an ever increasing number of GIF images in the chat history?
Any insight into this problem is highly appreciated

Thank you in advance!

**UPDATE 1**
I removed the animation card and replaced it with a Keyboard so that no GIFS are sent and the problem still remains. Here is a GIF showing it

**Scenario 1 Without Animation Card** Lag
![bot framework emulator chat connector example3](https://cloud.githubusercontent.com/assets/5139030/24187996/85c79e58-0f05-11e7-9c7a-e04521fa3ba4.gif)

**Scenario 2 Without Animation Card** No lag after clearing
![bot framework emulator chat connector example4](https://cloud.githubusercontent.com/assets/5139030/24188029/b84321fe-0f05-11e7-8984-7bdba1189e8e.gif)

Since you have a 250 ms delay before you send the message. I assume you have a setTimeout somewhere to execute this logic. Could it be possible that all timeout objects have queued up given the continuous interaction in this case

**UPDATE 2**

Set autoBatchDelay to 0 and the problem still persists

**Comment by tomlm** [comment]
Have you tried outside of the emulator?  I am guessing the emulator is getting slow

**Comment by slidenerd** [comment]
@tomlm As per [THIS ](http://stackoverflow.com/questions/42944447/bot-becomes-slow-over-time-in-loop)question on stackoverflow, one of the moderators of this section has also agreed that the bot becomes slow over a loop after say N times. I have noticed the same problem on messenger as well. This seems to be a bug of some sort in the bot framework as it becomes faster immediately after I clear all the data. I am running a quiz bot that doesnt stop till the user makes a mistake which could run into hundreds of questions and I am facing this lag as the number of questions keep piling up on both the emulator and messenger. Would love to know what is going on behind the scenes

**Comment by nwhitmont** [comment]
Thanks for reporting this issue.  As the Bot Framework is still in Preview phase and under active development, we are actively working to improve the performance of the framework with each new release of the SDK.
