### ISSUE TITLE
HTTP request isn't working on the emulator.

### ISSUE THREAD

**Issue by vishaldotkhanna** [Microsoft/BotBuilder#248]
I'm trying to make a bot which searches for a word's definition over a dictionary's API. The following code works correctly for a TextBot. 

[Code](https://codeshare.io/1LhsV)

	
The `-changename` part works on the emulator but when I try to use the `-meaning` command, I'm taken back to the root dialog.

**Comment by Stevenic** [comment]
Is there a reason you did `-meaning` as a piece of middleware and not just another `.matches('-meaning')` handler off your CommandDialog?  Middleware gets run for every single incoming request before the default processing kicks in.  When you call `next()` within your middleware you're saying now run your default logic which in this case would be to process the root dialog. 

It looks to me like if you take all of the logic you do when you match `-meaning` and move it to a `.matches()` handler your bot will work fine. I don't think you need to `bot.use()` code at all.

**Comment by vishaldotkhanna** [comment]
Thanks for responding, Steve. I included the  `-changename` part withing the `.matches()` handler but still it doesn't work on the emulator.  
[Code](https://codeshare.io/2BVWj)

![1](https://cloud.githubusercontent.com/assets/13077901/15214781/ae78cbb4-186c-11e6-9b34-cdc8b1358e2c.png)
![2](https://cloud.githubusercontent.com/assets/13077901/15214783/b17b046c-186c-11e6-8b23-572f18388037.png)

Also, I get an empty response the first time I enter a new command.

**Comment by Stevenic** [comment]
Found it!

Thanks for sharing the code. Small bug in CommandDialog. There was a `<` where there should have been a `<=`. I just published a fix so if you update to v0.10.2 you should be good.

**Comment by vishaldotkhanna** [comment]
Cool. Thanks for your help. :)

**Comment by Stevenic** [comment]
That's a different issue. If you look at your `/meaning` dialog you'll notice that you call `findMeaning()` with a session but then you call `session.endDialog()`. Once you call endDialog() you're saying you're done and to go back to listening for new commands. Problem is `findMeaning()` is async so when it comes back with a result you've already ended the dialog so you can't reply with your result. You should have findMeaning() end the dialog or restructure your code a bit. 

```
bot.add('/meaning', function(session)	{
	//console.log("test 1 /n");

	if(/-meaning/i.test(session.message.text))	{
		//console.log(/#meaning/i.exec(session.message.text).index);
		//console.log("test 2 /n");

		
		var words = session.message.text.split(" ");  //Won't work for multiple spaces.
		var searchWord = words[findInArray(words)];

		if(searchWord == undefined)
			session.send("Sorry, couldn't find the word you're looking for.");
		else
			findMeaning(searchWord, session); 
	}

	//console.log("test 5 /n");
	//next();

	session.endDialog();
});
```
