### ISSUE TITLE
Carousel not working when we have mixed cards on FB 

### ISSUE THREAD

**Issue by navenduagarwal** [Microsoft/BotBuilder#2481]
such as one item is herocard and another videocard

**Comment by mgbennet** [comment]
Video cards, audio cards, animation cards, and receipt cards do not fit into a carousel in Facebook Messenger. This is an (unfortunate) aspect of the channel, and is out of Bot Framework's ability to address. Video cards display differently on FB Messenger than they do in the emulator, instead resulting in two messages, one of the video and a [generic template card](https://developers.facebook.com/docs/messenger-platform/send-api-reference/generic-template) with the title, text, and any buttons.
