### ISSUE TITLE
[Feature Request] Checking Equality of "ChannelAccount"

### ISSUE THREAD

**Issue by ahendy** [Microsoft/BotBuilder#2486]
Right now ChannelAccount does not implement equals or gethashcode. This means that a method such as: 
`message.MembersRemoved?.Contains(message.Recipient)
`
wont work.

In the case with working on MsTeams, `MembersRemoved` contains `ChannelAccounts` with the Id but not the username but recipient `ChannelAccount`contains Id and username. In reality I would expect that a function is implemented to check equality of UserId between ChannelAccounts.

Let me know if this is something that can be addressed

**Comment by dandriscoll** [comment]
Hi @ahendy, this is a good idea. We're open to pull requests to add this feature.

We did this with Conversation Reference by adding a new file (ConversationReferenceEx.cs) into Microsoft.Bot.Connector.Shared, and adding the Equals and GetHashCode methods into the partial class.

Example: https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Microsoft.Bot.Connector.Shared/ConversationReferenceEx.cs

**Comment by ahendy** [comment]
Cool, I'll give it a go.

**Comment by ahendy** [comment]
@dandriscoll it looks like it has already been done for ChannelAccount https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Microsoft.Bot.Connector.Shared/ChannelAccountEx.cs

I guess this issue then turns into whether or not the name should be included or if the Id is sufficient.

**Comment by EricDahlvang** [comment]
This request has already been completed.  There's already an IEquatable implementation on ChannelAccount that includes name and id.  If you believe this should be improved upon somehow, please elaborate.

Closing the issue.
