### ISSUE TITLE
message to user after maximum attempts in PromptDialog

### ISSUE THREAD

**Issue by eddie1976** [Microsoft/BotBuilder#249]
Now user will see "too many attempts" after maximum attempts. Can we change it in the next code release? Thanks!

private async Task MessageReceived(IDialogContext context, IAwaitable<Message> message)
{
	T result;

	if (this.TryParse(await message, out result))
	{
		context.Done(result);
	}
	else
	{
		--this.attempts;

		if (this.attempts > 0)
		{
			var retry = this.retry ?? this.DefaultRetry;
			await context.PostAsync(retry);
			context.Wait(MessageReceived);
		}
		else
		{
			await context.PostAsync("too many attempts");
			throw new Exception();
		}
	}
}

**Comment by msft-shahins** [comment]
Commit [d77f719](https://github.com/Microsoft/BotBuilder/commit/d77f719ae3c5cf390eec6b26c979a4719129d0ca) adds this feature.
