### ISSUE TITLE
Conversation.SendAsync() not passing specific intent through MakeRoot Function after updating NuGet from 3.2.1 to 3.5.2

### ISSUE THREAD

**Issue by Montacia** [Microsoft/BotBuilder#2493]
After updating the NuGet Package from 3.2.1 to 3.5.2, for one LUIS intent only, Conversation.SendAsync() doesn't pass the activity through to the MakeRoot function when stepping through with breakpoints in debug, but it generates a prompt that comes from the form flow associated with the dialog that processes the intent without stepping into the form builder call. When you reply to the prompt, another prompt from the form flow appears (but in the wrong order) and it doesn't accept the inputs that are supposed to be valid. 

The only form flow customisation being used is the override of builder.Configuration.DefaultPrompt.ChoiceStyle, builder.Configuration.Yes and builder.Configuration.No and this same customisation is used for other forms in other intents that are still working. 

I tried commenting out the fields that were being prompted for in the form flow, but the bot still prompted the same fields after saving, rebuilding and running. I also tried removing the package and reinstalling it, but the problem still persists. 

It seems to me that the dialog stack for that intent has somehow bugged out? It always prompts for the same field in the form first, and it always prompts for the same out of order field which doesn't take valid inputs next.

**Comment by JasonSowers** [comment]
Montacia, is this still an issue for you or has it been resolved by the new release, 3.8.1 currently.

**Comment by JasonSowers** [comment]
@Montacia I am going to close this issue because of inactivity and it is related to an outdated version of the SDK.  please feel free to continue the discussion here if you feel it is needed.  We can always reopen this issue if needed

**Comment by Montacia** [comment]
@JasonSowers Hey Jason, this is still an issue for me even after updating to 3.8.1

**Comment by Montacia** [comment]
@JasonSowers I found the problem... Conversation.SendAsync() is working as it should, the problem lies in the fact that the one intent still has actions (from the deprecated LUIS actions) associated with it, resulting in LUIS creating prompts which were worded the same as the prompts in form flow. For some reason 3.2.1 suppressed these actions and just continued on with the code but newer versions don't?
