### ISSUE TITLE
statusCode: 500 Sorry, <BotName> is having a problem responding right now.*

### ISSUE THREAD

**Issue by chgc** [Microsoft/BotBuilder#25]
Error Message as below.
{
    "error": {
        "code": "ServiceError",
        "message": "*Sorry, BotDemo is having a problem responding right now.*",
        "statusCode": 500
    }
}

it works fine when I test it in Emulator. Not OK with slack. any idea what will cause this problem?

**Comment by Aleksion** [comment]
There's a closed issue where multiple of has has faced the same issue. 
Are you using node or C#?
Are you pointing to an HTTPS domain? 
And have you tested that your endpoint is working? (hit it directly with Postman with a post request. Add appId and appSecret as basic authentication. And debug from there.

**Comment by chgc** [comment]
Are you using node or C#?
     **C#**
Are you pointing to an HTTPS domain? 
    ** YES**
And have you tested that your endpoint is working? (hit it directly with Postman with a post request. Add appId and appSecret as basic authentication. And debug from there.

Here are the debug results for now.
1. return message.CreateReplyMessage($"You sent {length} characters"); => working
2. return await Conversation.SendAsync(message, MakeRootDialog); => not working
    (the code is copied from sample)

**Comment by chgc** [comment]
Found it.
the problem is because message.BotPerUserInConversationData has data from preview Bot testing. It has FormDialog with complete status. and that's what cause the problem.
Somehow. BotConnector kept the message information from previous version of Bot.
therefore, I need to clear the BotPerUserInConversationData. and then Everything is working again.

**Comment by Huskitch** [comment]
Any chance you could expand a bit further on what you did to fix this? Having the same problem.

**Comment by Huskitch** [comment]
@chgc

**Comment by dillongoeda** [comment]
Good find @chgc. For anyone wondering. All you have to do is to make message.BotPerUserInConversationData = null; before you do anything else. Publish it, and then send a message to to the bot from the channel that is giving the problem. Delete the line and publish again.

**Comment by chuckgiddens** [comment]
dillongoeda...you are correct.  That is the ONLY way to fix this issue.  which sucks because anytime you get into an unknown state you are dead in the water.  Has anyone found a way to handle this without having to republish 3 times?

**Comment by evnik** [comment]
Try to send `/deleteprofile` command to avoid republish. Check #101 for details.

**Comment by niyatia** [comment]
Hi there,

I am trying to create an echo bot and running into same issue while connecting it from slack. I am using same configuration as @chgc. However, I do not find message.BotPerUserInConversationData anywhere in my code that was created using the template and EchoBot example in the documentation. I am very new to this. Any guidance in where to reset this flag will be helpful.

Thanks
