### ISSUE TITLE
How to send welcome message using BotConnector bot

### ISSUE THREAD

**Issue by s-rya** [Microsoft/BotBuilder#250]
I am creating a bot for Skype using BotConnector. Is there any way I can send a welcome message when my bot is added as a contact in Skype? I can see that if we create create Bot using Skype bot sdk there is a config 'contactAddedmessage' through which we can achieve this.

And is there any way I can know if the bot is removed as a contact from Skype. Is there any event which can be listened in BotConnector?

**Comment by tomlm** [comment]
Not yet, but we will add support for this

**Comment by v-thgratMSGit** [comment]
Thanks!  We're tracking this suggestion on UserVoice: https://feedback.botframework.com/forums/354219-bot-connector/suggestions/13430715-system-message-to-identify-bot-added-to-contact

**Comment by srisaiswaroop** [comment]
Not having a welcome message was one of the reasons our bot got rejected when we submitted our Skype bot for publishing. 

So I believe its a **must have** for anyone who wants to build a bot using bot-framework and publish it.

**Comment by judavi** [comment]
I agree, this should be a *must have* without this we can't publish bots on the skype directory, so connect the bot with the skype will be just a waste of time

**Comment by stanleycyang** [comment]
Is this issue resolved? @judavi

**Comment by judavi** [comment]
@stanleycyang yes it's fixed

**Comment by McGern** [comment]
Hi,

Is there some sample code of this working please?

Thanks,
Jarrod

**Comment by adekola** [comment]
Hi all. I would also like to know how to implement such a functionality. The proactive bot approach would be overkill for the simple requirement of sending a welcome message when the bot is started. 

Looking forward.

**Comment by VanjuliK** [comment]
Hi all, i want to display a greet message when user clicks on the bot in Skype For Business but it seems SfB interprets "ConversationUpdate" event of Microsoft Bot Framework differently. No message is displayed until user sends a message first. Is there any way that Bot responds first as it's crucial for our project.

**Comment by vijaysaimutyala** [comment]
@VanjuliK Did you find any work around for this ?

**Comment by qinxiaowen** [comment]
i search a solution like this:
https://www.davidezordan.net/blog/?p=8119

**Comment by EricDahlvang** [comment]
Skype sends a ContactRelationUpdate when the bot is added as a contact.  Use this instead of ConversationUpdate for the Skype channel welcome message.
