### ISSUE TITLE
Issue in Microsoft LUIS importing existing application

### ISSUE THREAD

**Issue by rahulsarkar123** [Microsoft/BotBuilder#2500]
Hi Team,

I have exported application from Microsoft LUIS into a .json file but while trying to import that .json file to a new application in LUIS I am getting the following issue:

"values provided in your Text settings are not found in parameters list". Attached is the screenshot. Please suggest.
![cathy_luis_error](https://cloud.githubusercontent.com/assets/26003233/24341308/6e21c4f2-12d6-11e7-96a3-aa73c5ee54f1.png)

**Comment by GhostAtom** [comment]
I fixed it by removing the old json items in actions property.
Maybe an issue with the migration.

**Comment by rahulsarkar123** [comment]
Yes, Even I have removed the old json items in actions property and have solved it.

**Comment by cahann** [comment]
Thanks for point this issue, LUIS should be able to handle action parameters gracefully or throw a more descriptive error message.

**Comment by pragnya01** [comment]
Rplace datetime with datetimeV2 and try again. It was in my case.
