### ISSUE TITLE
XML elements in received messages

### ISSUE THREAD

**Issue by gala132** [Microsoft/BotBuilder#2506]
Hi all!
I was working with the Framework but when I sent my bot to a Group Conversation I stumbled upon a few issues.
The problem is that within the skype conversation, I get xml in the `session.message.text` variable, which is working fine if we have one-to-one conversations.
This happens after mentioning the bot like described in the other issue.
Here is the output of the `session.message` variable.
```
{ text: '<at id="28:xxxx-16b6-4540-a6aa-56923ed0fb58">XBOT</at> asd',
  type: 'message',
  timestamp: '2017-03-27T22:14:49.735Z',
  entities: 
   [ { mentioned: [Object],
       text: '<at id="28:xxxx-16b6-4540-a6aa-56923ed0fb58">XBOT</at>',
       type: 'mention' },
     { locale: 'en-US', platform: 'Web', type: 'clientInfo' } ],
  attachments: [],
  address: 
   { id: '95559454',
     channelId: 'skype',
     user: 
      { id: '29:xxx-XJWQwWw24XpE-IF6pLZWzvl9kLV6sM5iOMJE',
        name: 'XY' },
     conversation: 
      { isGroup: true,
        id: '19:840da69e20484f5f8fadbcf1c8c8a33b@thread.skype' },
     bot: { id: '28:xxxx-16b6-4540-a6aa-56923ed0fb58', name: 'XBOT' },
     serviceUrl: 'https://smba.trafficmanager.net/apis/',
     useAuth: true },
  source: 'skype',
  agent: 'botbuilder',
  user: 
   { id: '29:xxxx-XJWQwWw24XpE-IF6XLZWzvl9kLV6sM5iOMJE',
     name: 'XY' } }
```
For the client side (myself) I am using a skype for linux beta version.
SDK: Node
The botbuilder package version: botbuilder@3.7.0
If any additional details needed I can provide them. (Scrubbed some id's from the dump, so those are not valid.)
It seems that others have such problem too https://github.com/Microsoft/BotFramework-Emulator/issues/104
Although, it could be related to the Botframework itself, but since it is causing issues here too (like described in the 104 issue), it is fine to have it here also.

**Comment by tomlm** [comment]
This is a bug in the skype implementation which is being corrected.  Text should be plain text and markup like this from skype will be in channelData.Text.  In the short term you will have to strip the xml out

**Comment by gala132** [comment]
Okay, @tomlm when can we expect a fix or from where will I know that it has been fixed so I can remove temporary html tag removal?
