### ISSUE TITLE
Facebook Error when showing Herocard with buttons exceeding 1000 characters

### ISSUE THREAD

**Issue by piffarettig** [Microsoft/BotBuilder#2507]
I am having a similar issue to the one described [here](https://github.com/Microsoft/BotBuilder/issues/2150): 

`SendActivityToUserAsync FAILED: {"error":{"message":"(#100) Length of param [elements][0][buttons][0][payload] must be less than or equal to 1000","type":"OAuthException","code":100,"fbtrace_id":"GHoBd3voyLI"}}
`
Basically it throws an exception when the value of a button that's inside a HeroCard exceeds the 1000 characters. What I am passing inside it is a JsonObject that serialised as string and then I deserialize it on the callback of the click event on any of those buttons `AfterUserChoseInitialOption`.

Code goes like this:

```
var reply = context.MakeMessage();
List<CardAction> buttons = GetOptionsAsButtonsFromProducts(userProductsAvailableForTransfer);
var card = new HeroCard("He encontrado los siguientes productos asociados:", "", buttons: buttons);
reply.Attachments = new List<Attachment> { card.ToAttachment() };
wait context.PostAsync(reply);
context.Wait(AfterUserChoseInitialOption);
```

And what `GetOptionsAsButtonsFromProducts` does is:

```
private static List<CardAction> GetOptionsAsButtonsFromProducts(List<Product> matchingProducts)
{
            var buttons = new List<CardAction>();
            foreach (var product in matchingProducts)
            {
                string productNumber = product.ProductNumber;
                string productCurrency = product.Currency.CurrencySymbol;
                string productType = product.ProductType.ValueName;
                string buttonText = $"{productNumber}: {product.GetProductType()} in {productCurrency}";
                string productAsJSON = JsonConvert.SerializeObject(product);
                string hiddenData = $"{buttonText}<meta data='{productAsJSON}'/>";
                var productOptionButton = new CardAction(type: "imBack", title: buttonText, value: hiddenData);
                buttons.Add(productOptionButton);
            }
            return buttons;
}
```

Currently `hiddenData` is having 1222 chars which causes the error. 

Thanks in advance.

**Comment by tomlm** [comment]
This is facebooks limitation, not ours.  You apparently can't do what you are trying to do.
