### ISSUE TITLE
[Direct Line] DirectLine format changed today, is it expected?

### ISSUE THREAD

**Issue by ivmos** [Microsoft/BotBuilder#2508]
Just FYI, as It's bad idea parsing that in our custom client, returning that info through channelData I guess it should be the way to go. But anyway, FYI, this change was a bit unexpected, so not sure if also expected by you:

Since today we receive:

Instead of:

Was:
"* Option 1
Option 2"

Now is:
"Options:
Option 1
Option 2"

Regards,

**Comment by colymore** [comment]
Same problem here :P

**Comment by dandriscoll** [comment]
Hi @ivmos and @colymore, we didn't intend a change here.

Are you using Direct Line 1.1 or 3.0?

Can you send some example JSON showing what the bot is sending? I.e., is this in the Text field or is it in a card, etc.?

**Comment by ivmos** [comment]
We send it as LIST_STYLE this way:

     ```
   builder.Prompts.choice(session, 'Question copy', 'OptionA|OptionB|OptionC', {
            listStyle: LIST_STYLE,
            maxRetries: 0,
        });
```

We now receive it in text field as "text": "Options:\n* OptionA \n\n* Option B"
Our client lib implements Direct Line 1.0 swagger.
Our apps have both 1.1 and 3, enabled. 

(BTW I don't want to try lose focus of issue, but if you can tell us whether we can wait until directLine 3 is out of preliminary or 1.1 is considered major it would be great. I can't find info about 1.0->1.1 changes)

Thanks!

**Comment by dandriscoll** [comment]
I'll take a look, thanks for sending.

The schema and polling GET parts of Direct Line 3.0 are fully available. Only the Web Socket support in Direct Line 3.0 is still in preview.

**Comment by nwhitmont** [comment]
@ivmos reopen if you are still experiencing the issue
