### ISSUE TITLE
Facebook Structured Messages

### ISSUE THREAD

**Issue by matheus208** [Microsoft/BotBuilder#251]
Are Facebook's structured messages supported on this lib?

I'm using Node.js and I saw that on [Session.ts](https://github.com/Microsoft/BotBuilder/blob/master/Node/src/Session.ts#L129) there is a verification whether to send a text or an object. I was expecting this object to be of any type (as long as Facebook supported it).

I am sending a [structured message](https://developers.facebook.com/docs/messenger-platform/send-api-reference#guidelines) JSON, but it is not sent to Facebook :(

This is a console.log output of the object I'm sending:

```
{ 
    attachment: { 
        type: 'template',
        payload: { 
            template_type: 'generic', 
            elements: [Object] 
        } 
    } 
}
```
Is there a way to pass these messages through?

**Comment by eddie1976** [comment]
I followed this and able to send attachment to Facebook via Message.Attachments or Message.ChannelData. 

http://stackoverflow.com/questions/37011994/microsoft-bot-framework-messages-with-buttons-in-facebook-messenger

**Comment by matheus208** [comment]
I couldn't find an equivalent for Node.js

The closest I found was Session.createMessage(), but it assumes that I want to send a text. I guess I might have to fork it and verify if the argument is a string or an object?

**Comment by matheus208** [comment]
Ok, I managed to use "Session.sendMessage()", passing an attachment JSON, as described on the Send API documentation and it worked!
