### ISSUE TITLE
Review process is done, but still getting error #10

### ISSUE THREAD

**Issue by amitbend** [Microsoft/BotBuilder#2510]
Hi, this is quite urgent. @Andrea-Orimoto 
I sent my bot for review in both facebook and botframework.
the review on facebook is done successfully and it was approved for `pages_messaging`

When an outside user is trying to use it, i still get this error: 

`(#10) Cannot message users who are not admins, developers or testers of the app until pages_messaging permission is reviewed and the app is live.","type":"OAuthException","code":10`

Why is that happening?
is that a bug?

**Comment by amitbend** [comment]
Was my bad, did not let it out of development mode

**Comment by SarnenduDe** [comment]
Hi, I am facing the same issue. I have submitted for review. Although it is saying bot is public and available to all users. And error msg saying untill pages_messaging permission is reviewed, it will be available to admin/developer/testers only. strange!!!

**Comment by amitbend** [comment]
Is your bot public?
Follow this instructions :
`To make your app public, please go to the App Review tab of your App's Dashboard (https://developers.facebook.com/apps/<appid>/review-status/) and use the switch at the top ("Make <app-name> public?").`

**Comment by SarnenduDe** [comment]
amitbend, yes, my bot is pubic. Please refer screenshot.
![chatbotissue](https://cloud.githubusercontent.com/assets/26790407/24499231/9d887cec-155e-11e7-8a1c-9cd9c4307977.JPG)

**Comment by SarnenduDe** [comment]
But is not accessible except admin/developer/tester. As mentioned, I have submitted for review.

**Comment by SarnenduDe** [comment]
As per facebook documentation, issue is related to permission. https://developers.facebook.com/docs/messenger-platform/send-api-reference/errors ; 
https://developers.facebook.com/docs/messenger-platform/app-review
