### ISSUE TITLE
Calling / forwarded to another dialog from a scorable

### ISSUE THREAD

**Issue by garypretty** [Microsoft/BotBuilder#2511]
I am trying to forward to a dialog from a scorable dialog, but I am receiving the following error when I do.  The forward method gets call but the target dialog never seems to hit StartAsync.  the error I get is as follows;

**IDialog method execution finished with multiple resume handlers specified through IDialogStack.**

I realize in this simple scenario I could do everything I needed to in the scorable, but I have a more complex scenario where forwarding / calling a dialog from a scorable would be perfect.  Can you provide any insight as to why I am seeing this error?

**Scorable**

`public class CommonResponseHandler : IScorable<IActivity, double>
    {
        private readonly IDialogStack _stack;

        public CommonResponseHandler(IDialogStack stack)
        {
            SetField.NotNull(out _stack, nameof(stack), stack);
        }

        public async Task<object> PrepareAsync(IActivity item, CancellationToken token)
        {
            var message = item?.AsMessageActivity();
            var messageText = message?.Text;
            if (String.IsNullOrWhiteSpace(messageText))
            {
                // No text, no response!
                return Task.FromResult<object>(null);
            }

            if (messageText == "Hi there")
                return "Hello!";
            return null;
        }

        public bool HasScore(IActivity item, object state) => state is string;

        public double GetScore(IActivity item, object state) => state is string ? 1 : 0;

        public async Task PostAsync(IActivity item, object state, CancellationToken token)
        {
            var message = item as IMessageActivity;
            IDialog<object> dialog = new MessageOutputDialog(state as string);
            await _stack.Forward(dialog, AfterMessageOutputDialog, message, CancellationToken.None);
        }

        private Task AfterMessageOutputDialog(IDialogContext context, IAwaitable<object> result)
        {
            return Task.CompletedTask;
        }

        public Task DoneAsync(IActivity item, object state, CancellationToken token)
        => Task.CompletedTask;
    }`

**Dialog being called / forwarded to**

`public class MessageOutputDialog : IDialog<object>
    {
        private readonly string _message;

        public MessageOutputDialog(string message)
        {
            _message = HttpUtility.HtmlDecode(message);
        }

        public async Task StartAsync(IDialogContext context)
        {
            await context.PostAsync(_message);
            context.Done((object)null);
        }

        Task IDialog<object>.StartAsync(IDialogContext context)
        {
            throw new NotImplementedException();
        }
    }`

**Comment by ejadib** [comment]
Hi @garypretty, try doing _stack.PollAsync after the Forward. At least that is what is being done in the [ContosoFlowers sample](https://github.com/Microsoft/BotBuilder-Samples/blob/master/CSharp/demo-ContosoFlowers/ContosoFlowers/Dialogs/SettingsScorable.cs). 

Please note that the PollAsync is not available anymore at the IDialogStack level and instead you would have to use IDialogTask in your scorable.

BTW, it seems there an extension method for the [IDialogTask ](https://github.com/Microsoft/BotBuilder/blob/497252e8d9949be20baa2cebaa6ce56de04461cf/CSharp/Library/Microsoft.Bot.Builder/Dialogs/IDialogTask.cs#L121) that does just that (Forward + PollAsync)

**Comment by garypretty** [comment]
Thanks. That did it :) Much appreciated.
