### ISSUE TITLE
A way to reuse dialog objects

### ISSUE THREAD

**Issue by amoldeshpande** [Microsoft/BotBuilder#252]
I need to make some DB queries during a bot conversation. I tried passing in a repository object in the constructor of my dialog (derived from LuisDialog). dependency injection via the WebAPI controller.

In the released version, my non-default constructor was never called.  Once I built out of github, my constructor was called.
However, in subsequent calls to the luis intents (in the same conversation), it seems like my derived object was created  without the repository reference.  This makes sense as the dialog was probably deserialized into existence and the repository object reference is not serializable.

If I was running against a conventional SQL db with connection pooling, I would not worry about having to recreate the DB connections every time, but I'm using Azure DocumentDB for now.

So, to make a long story short, I would love a way to have stateless objects that are reused in a conversation, instead of serialized/deserialized with every message. I could maintain the required state in my DB.

**Comment by willportnoy** [comment]
In our code, we have singleton objects that we don't want to serialize (and sometime can not be serialized).  We mark these objects in the Autofac container with FiberModule.Key_DoNotSerialize and serialize the object type instead of the object instance, and then on deserialization, we substitute the object instance from the container when we encounter that serialized object type.  Perhaps that might work for you as well?

**Comment by amoldeshpande** [comment]
Yes, that sounds like something I could work with.  As a rule I hate adding more and more frameworks to my code though. 

Would it be a lot of work to make dialog objects not marked as [Serializable] be constructed with the factory method each time ?

I'm fine with Autofac though and probably needlessly neurotic. thanks

**Comment by willportnoy** [comment]
That could work too - it's the way FormDialog<T> works, since we don't want to serialize the IForm<T>, we serialize the Func<IForm<T>> builder instead.

**Comment by amoldeshpande** [comment]
cool, that would be very useful, thanks.

**Comment by willportnoy** [comment]
I've checked in some code to make it possible to instantiate the dialogs from the container.  I'll close this issue for now, but feel free to re-open to discuss more.

I'm not sure it makes sense to add a serialization surrogate to automatically resolve singleton instances from the container - I would assume at that point, you could simply resolve the dialog from the container and get your dependencies automatically.
