### ISSUE TITLE
Keeping a memory of the dialog

### ISSUE THREAD

**Issue by bluekite2000** [Microsoft/BotBuilder#253]
I have a luis intent whenever use says yes. For this dialog 

> Are you doing well?
> Yes
> Are you a male
> Yes.

How do I detect whether the yes comes from the 1st question or the 2nd question?

**Comment by Stevenic** [comment]
Are you using the C# or Node version of the framework. In either case can you show a code sample of you asking the user these questions because it sounds like you want to use the built-in confirm prompt for this.

**Comment by bluekite2000** [comment]
@Stevenic I m using C#. You are right I can use confirm prompt. What about other cases (instead of yes no) is there a way to provide context to the intent?

**Comment by Stevenic** [comment]
Adding Shahin to give you C# specific guidance.

From a LUIS perspective i'd train two different entities. One called __UserName__ which catches "John Smith" and a second called __Visiting__ which catches "Jane Doe". In this particular example the __Intent__ matters a little less than the __Entities__. Focusing on training entities would let you recognize both parts in a response like `My name is John Smith. I'm here to see Jane Doe.`

**Comment by bluekite2000** [comment]
@Stevenic I think you misunderstood my question.
Here is the dialog

> Bot: Hi what is your name?
> Person:  John Smith
> Bot: Who are you here to see?
> Person: Jane Doe
> Bot: Thanks

In this case how do I know John Smith is to answer the 1st question and Jane Doe is to answer the 2nd?
All I get back from luis is the nameintent

**Comment by Stevenic** [comment]
I'll let Shahin answer since the answer is C# specific

**Comment by chrimc62** [comment]
I suspect you have a LUIS dialog and trigger on the intent.  This is great for one-shot intent based things, but you need to tie this to whatever is generating your prompt.  You can use the per conversation or per user data stores to store the state.  Alternatively in this case, it would likely be a lot simpler to use a FormFlow unless you are looking for more general response.

**Comment by msft-shahins** [comment]
As @chrimc mentioned, You can use various contextual stores, i.e. 'UserData, ConversationData,  PerUserInConversationData` to track progress of your LuisDialog.
