### ISSUE TITLE
Does not detect group messages correctly?

### ISSUE THREAD

**Issue by Nisthar** [Microsoft/BotBuilder#2530]
I am wondering why this is not reported yet.

I am using the nodejs sdk. The personal messages with the bot is working fine and the bot is recognizing the messages send.

But in group messages, when we mention "@Bot name command" The message is not recognised since the "@Botname" gets added to the message. I am not sure if its the desired feature. But my messages are not recognized in the group conversations due to this.

**Comment by aakashvit** [comment]
https://github.com/Microsoft/BotBuilder/issues/2196

**Comment by Nisthar** [comment]
@aakashvit Its in C#.

Is there nodejs code for it?

**Comment by Nisthar** [comment]
@aakashvit BTW I think this is not my issue.

**Comment by EricDahlvang** [comment]
related: https://github.com/Microsoft/BotBuilder/issues/2419

**Comment by nwhitmont** [comment]
@Nisthar - What channel are you using for the group messages?

**Comment by nwhitmont** [comment]
@Nisthar are you still experiencing the issue using `botbuilder@3.7.0`?

**Comment by Nisthar** [comment]
@nwhitmont I am using skype

I don't think its fixed. But i managed to temporarily fix it.

It might be still broken in the core library. I mentioned the error in my first post of this issue,

**Comment by aakashkag** [comment]
function public_channel_ensure(session){
  var obj={"isGroup":false,"isAllow":false}
  var address=session.message.address;
  var message=session.message;
  var botname=address.bot.name;
  if(address.conversation.isGroup&&message.text){
    var msgtoken=message.text.toLowerCase().trim().split(/\s+/);
    var attachments=message.attachments||[]
    if(attachments.length==0&&botname&&msgtoken.indexOf("@"+botname.toLowerCase())>-1){
      obj["isGroup"]=true;obj["isAllow"]=true; 
      return obj;
    }
    else{obj["isGroup"]=true;obj["isAllow"]=false; return obj;}
  } 
  else{return obj;} 
}

**Comment by helgeh** [comment]
I feel like this has never been resolved, am I right?
