### ISSUE TITLE
[Skype Mobile iOS] AudioCard as attachment crashes iOS Skype app

### ISSUE THREAD

**Issue by szul** [Microsoft/BotBuilder#2531]
I'm working on [this code](https://github.com/szul/codepunk.bot.node/blob/master/lib/app.ts), and when the bot tries to send the AudioCard in the iOS Skype app, it crashes the app. Works fine in the Skype desktop app though.

**Comment by szul** [comment]
Can confirm that this is happening on the iPad app too:
iOS 10.2.1
Skype 6.34.0.105

**Comment by nwhitmont** [comment]
Confirmed, this is a bug in Skype iOS v6.34.0.105

**Comment by nwhitmont** [comment]
pending investigation by Skype Mobile team

**Comment by nickcordrey** [comment]
We are rolling a fix for this issue into a future client release. For now can you try ensuring that the profile of the attachment is stated. I.e.: on the same level as the url, one should specify “profile”=“audio”.

**Comment by nwhitmont** [comment]
@nickcordrey thanks for the update

**Comment by szul** [comment]
Looks like the Skype update that went out yesterday/this morning has fixed this issue. Thanks @nickcordrey.
