### ISSUE TITLE
[Feature Request] Add staging support to LuisDialog

### ISSUE THREAD

**Issue by DL-LiveTiles** [Microsoft/BotBuilder#2534]
Add staging (optional bool) constructor to LuisDialog allowing targeting of the LUIS staging deployment slot.

**Comment by gregoryfabry** [comment]
Would I be able to contribute this? My main question would be how to let the user indicate that they would like to use the staging endpoint slot instead of the production one.

**Comment by nwhitmont** [comment]
Duplicate of #2498
