### ISSUE TITLE
luis - phrase list feature doesn't works with hierarchical entities

### ISSUE THREAD

**Issue by GhostAtom** [Microsoft/BotBuilder#2545]
Hi, I added a phrase list feature to a hierarchical entity but it's still not labeled as the entity when utterance match. Have an idea?

exemple:
phrase list=[shop]
entity= place::retail
utterance = the shop is in the street

**Comment by stevengum97** [comment]
Hi @GhostAtom, thank you for your submission.
The BotBuilder's Issues section is for bug fixes and feature requests. Can you move this question over to [StackOverflow](https://stackoverflow.com/)? Someone will assist you there. When you create your post, please make sure to include any screenshots or code snippets that you think are relevant.

**Comment by cahann** [comment]
Adding a phrase list doesn't guarantee that the entity will be predicted, its added as a feature to the ML to enhance the model prediction. You may need to label more examples
