### ISSUE TITLE
Install Node Examples

### ISSUE THREAD

**Issue by dimoibiehg** [Microsoft/BotBuilder#2546]
The tutorial to install Node examples is not working properly. Apparently, `url-join` module is necessary, but not installed in the way. Therefore, you need to add this module by the hand like this: `npm install --save url-join`.

**Comment by stevengum97** [comment]
@dimoibiehg Thank you for bringing this to our attention. Our team is looking into this at the moment. Just to verify, did you run `npm install --save url-join` in the BotBuilder/Node directory or inside of BotBuilder/Node/core to that package.json? The core/package.json has the dependency for url-join.

**Comment by nwhitmont** [comment]
I have submitted a PR to fix this issue here: https://github.com/Microsoft/BotBuilder/pull/2549
