### ISSUE TITLE
Direct Line API Can't Reply to PromptDialog

### ISSUE THREAD

**Issue by eddie1976** [Microsoft/BotBuilder#255]
I have a PromptDialog and it works great with Web Chat Control and Facebook Messenger. However, I can't reply to it using Direct Line API. I am sure that I use the same ChannelConversationId (got from /api/conversations), and I noticed that ConversationId is also the same.

Besides conversationId, is there any other property I should take care when I send message (/api/conversations/{conversationId}/messages) to make PromptDialog work?

Thanks!

**Comment by eddie1976** [comment]
I find the answer by myself :D

**Comment by rodzillarr** [comment]
@eddie1976  what was the answer? :-\  

I'm having the same problem.

**Comment by eddie1976** [comment]
When you send a message, remember to put a value in "from".
