### ISSUE TITLE
Can't set LuisRequest to use Staging Endpoint Slot for LuisDialogs

### ISSUE THREAD

**Issue by JonWendorfTallan** [Microsoft/BotBuilder#2554]
I noticed within the LuisService.cs code that the "staging" parameter isn't included when building the query URI for LuisDialogs (via LuisRequests).  Since we can't specify the staging parameter to be true, it appears our development application is making requests to the production endpoint slot rather than the staging endpoint.

Could we have the LuisModelAttribute updated to include a flag stating if the LuisRequests should use the staging endpoint slot for LuisDialogs?

Thank you!

**Comment by cahann** [comment]
@Andrea-Orimoto

**Comment by DL-LiveTiles** [comment]
Same issue logged here: https://github.com/Microsoft/BotBuilder/issues/2534
This is currently a roadblock for us.

**Comment by ddenton87** [comment]
Looks like @chrimc62 added the Staging parameter as an option in develop.  That should resolve this issue.

**Comment by msft-shahins** [comment]
This commit af2b62b will fix this issue.
