### ISSUE TITLE
'System.Net.Sockets.SocketException' when trying to get user response

### ISSUE THREAD

**Issue by RazSoft** [Microsoft/BotBuilder#2557]
I am working on a project that requires getting user response. It's a recursive implementation that requires navigating over a binary tree. I've tried all of following methods but none seem to work. While debugging getting following exception from internal code. OnOptionSelected method is never invoked. 

```cs
var reply = context.MakeMessage();
                        reply.AddHeroCard(
                            promptQuestion,
                            options.Keys.ToArray()
                            );
                        await context.PostAsync(reply);
context.Wait<String>(this.OnOptionSelected);`

`var dialog = new PromptDialog.PromptChoice<string>(options.Keys.ToArray(), "select option :", "Please retry", 1);
context.Call(dialog, this.OnOptionSelected);`

`PromptDialog.Choice<String>(
                            context: context,
                            resume: OnOptionSelected,
                            options: options.Keys.ToArray(),
                            prompt: "Select option",
                            promptStyle: PromptStyle.Auto);
``

**Comment by RazSoft** [comment]
Here is the inner exception: +		$exception	{"Unable to read data from the transport connection: A blocking operation was interrupted by a call to WSACancelBlockingCall."}	System.IO.IOException

**Comment by JasonSowers** [comment]
@RazSoft I am going to close this issue for inactivity.  Feel free to continue this conversation if you would like.  We can always reopen this if needed.
