### ISSUE TITLE
NodeJS UniversalCallBot should call emitError when storage implementation returns an error

### ISSUE THREAD

**Issue by ctstone** [Microsoft/BotBuilder#2562]
When the errorLogger function in UniversalCallBot receives an error, it does not pass the error to `emitError`. There is a stub for `this.emitError` but it is never called. 

This can be reproduced by using an IBotStorage implementation that throws an error on `getData` or `saveData`

Expected behavior is to receive errors generated by the storage implementation in the bot's `on('error`)` listener.

Actual behavior is swallowing of the error message. Must attach a debugger to find out what the exception is.

**Comment by nwhitmont** [comment]
Thanks for submitting this fix @ctstone
