### ISSUE TITLE
high lag in telegram.botframework.com

### ISSUE THREAD

**Issue by dimoibiehg** [Microsoft/BotBuilder#2563]
There is a well known problem which is botframework has high response time. However, we have launched a bot in the market using botframework (C#) and after some analysis, we found that requests to the `telegram.botframework.com` (and sometimes `state.botframework.com`) are so slow in average (as you can see in the following image):

![image](https://cloud.githubusercontent.com/assets/22638310/24760542/38fb8526-1afe-11e7-844d-94af82694141.png)

Why this time should be high? Is this problem specific for Telegram?

**Comment by nwhitmont** [comment]
@dimoibiehg Thank you for reporting this issue.  I have forwarded this to our Telegram Connector API team for further investigation.

**Comment by tomlm** [comment]
This is usually telegram itself, we add about 100-300ms on top of the request, here you can that the bulk of the latency is from the telegram api itself.
![image](https://cloud.githubusercontent.com/assets/17789481/24874244/dc7a2edc-1dd8-11e7-9613-d523b4abe12b.png)
