### ISSUE TITLE
Apostrophe in Enum choice's DescribeAttribute isn't a recognised answer

### ISSUE THREAD

**Issue by BAPostma** [Microsoft/BotBuilder#2567]
Assume the following code where an apostrophe (') is placed in the text:
```
public enum ContinueOptions
{
    [Describe("Ok, let’s get started")]
    OkLetsGetStarted = 1,
    [Describe("Maybe later")]
    MaybeLater
}
```

And it's used like this:
```
[Prompt("Are you ready to proceed? {||}")]
public ContinueOptions Continue { get; set; }
```
The pattern matcher doesn't recognise the text (either when clicked on, or typed in) as demonstrated in this screenshot:

![image](https://cloud.githubusercontent.com/assets/5364372/24770205/04269b6c-1b01-11e7-8987-7c564e06e3be.png)

Answering the following, actually works:
> ok lets get started

**Suggested solution to fix bug:** Discard any characters such as apostrophes when the `Microsoft.Bot.Builder.FormFlow.Advanced.Language.GenerateTerms(string phrase, int maxLength)` method is called internally.

**Comment by JasonSowers** [comment]
@BAPostma does this still happen with the newest SDK 3.8.1 at the time of this post?

**Comment by JasonSowers** [comment]
@BAPostma  I'm curious to know if you have tried the following and what the result was if you did.
```cs
[Describe(@"Ok, let’s get started")]
`
Also is this still an issue in the newest SDK 3.8.1 at the time I am writing this?
