### ISSUE TITLE
Error : Service provider instance was not register

### ISSUE THREAD

**Issue by KarateJB** [Microsoft/BotBuilder#2570]
I followed the sample codes on [Microsoft/BotBuilder](https://github.com/Microsoft/BotBuilder/tree/master/CSharp/Samples/Microsoft.Bot.Sample.AspNetCore.Echo) with [Microsoft.Bot.Connector.AspNetCore 3.6.0-alpha](https://www.nuget.org/packages/Microsoft.Bot.Connector.AspNetCore/3.6.0-alpha)

When I send a message to bot, there was an error meesage like this :

**`The service provider instance was not register. Please call RegisterServiceProvider before using ServiceProvider.Instance.`**

which happened on  `var appCredentials = new MicrosoftAppCredentials(this._configuration);`

Here are my packages in .csproj file.

```
<PropertyGroup>
   <TargetFramework>netcoreapp1.1</TargetFramework>
</PropertyGroup>
<ItemGroup>
   <PackageReference Include="Microsoft.AspNetCore" Version="1.1.1" />
   <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.2" />
   <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="1.1.1" />
   <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="1.1.1" />
   <PackageReference Include="Microsoft.Bot.Connector.AspNetCore" Version="3.6.0-alpha" />
   <PackageReference Include="Microsoft.Bot.Connector.AspNetCore.Mvc" Version="3.6.0-alpha" />
   <PackageReference Include="Microsoft.Bot.Connector.Common" Version="3.6.0-alpha" />
   <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="1.1.1" />
   <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="1.1.1" /> 
<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="1.1.1" />
 </ItemGroup>
```
Other codes are all similar with the sample codes on  [Microsoft/BotBuilder](https://github.com/Microsoft/BotBuilder/tree/master/CSharp/Samples/Microsoft.Bot.Sample.AspNetCore.Echo).  But my code runs fine with [Microsoft.Bot.Connector 3.5.1-alpha](https://www.nuget.org/packages/Microsoft.Bot.Connector/3.5.1-alpha).

PS. I posted my codes in [stackoverflow](https://stackoverflow.com/questions/43268337/microsoft-bot-connector-error-service-provider-instance-was-not-register) as well.

**Comment by luizcarlosfaria** [comment]
Just call `services.UseBotConnector()` on ConfigureServices method of your Startup class.
This method is provided by Microsoft.Bot.Connector.BotServiceProviderExtensions extension class.

**Comment by KarateJB** [comment]
@luizcarlosfaria , thank you for the reply.
But I cannot find the namespace or package of `Microsoft.Bot.Connector.BotServiceProviderExtensions`.
Is the package available in nuget? Thank you so much!

**Comment by andreesteve** [comment]
If you are using ASP.NET, you should be able to register the provider with this snippet before initializing the 
MicrosoftAppCredentials class.

```          
if (!ServiceProvider.IsRegistered)
{
     ServiceProvider.RegisterServiceProvider(new BotServiceProvider());
};
```

If you are using ASP.NET Core, you need this in your [startup](https://github.com/Microsoft/BotBuilder/blob/develop/CSharp/Samples/Microsoft.Bot.Sample.AspNetCore.Echo/Startup.cs#L35):

`services.UseBotConnector();`

Also check this issue for more details #2590

**Comment by luizcarlosfaria** [comment]
@KarateJB add package `Microsoft.Bot.Connector.AspNetCore` to your project references.

**Comment by KarateJB** [comment]
It works! Thank you so much, @luizcarlosfaria and @andreesteve!
