### ISSUE TITLE
InternalServerError - Bot & QnA Maker

### ISSUE THREAD

**Issue by andrzejsobczak** [Microsoft/BotBuilder#2572]
I would like to ask for your help in the following situation: 

1. I created a knowledge sharing service from the knowledge base using the QnA Maker (I created question and answer base and it worked very well). 

2. Then, using the standard steps described in the Bot Framework documentation, without the slightest problem I generated a bot (in C#, I used a template to connect it to a previously created knowledge base in the QnA Maker), and the bot worked without any problem. It was visible at https://dev.botframework.com/ (after logging in to my bots), it responded correctly to the questions asked, clicking on “test connection to your bot” gave the answer “Accepted” – so everything was fine. 

3. Since then, I have not made any changes to the automatically generated code. After a few hours, the bot stopped working – i.e. the source code was missing from the Azure portal. Error like the one in the attached screenshot popped up. 

![image](https://cloud.githubusercontent.com/assets/24848210/24799853/c2bdafd8-1b9d-11e7-91b3-23ef662f378a.png)

Currently, at https://dev.botframework.com (after logging in to my bots), clicking on “Test” gives the following answer:

InternalServerError
<!DOCTYPE html>
<html>
    <head>
        <title>Runtime Error</title>
        <meta name="viewport" content="width=device-width" />
    </head>

    <body bgcolor="white">

            <span><H1>Server Error in '/' Application.<hr width=100% size=1 color=silver></H1>

            <h2> <i>Runtime Error</i> </h2></span>

            <font face="Arial, Helvetica, Geneva, SunSans-Regular, sans-serif ">

            <b> Description: </b>An application error occurred on the server. The current custom error settings for this application prevent the details of the application error from being viewed remotely (for security reasons). It could, however, be viewed by browsers running on the local server machine.
            <br><br>

            <b>Details:</b> To enable the details of this specific error message to be viewable on remote machines, please create a &lt;customErrors&gt; tag within a &quot;web.config&quot; configuration file located in the root directory of the current web application. This &lt;customErrors&gt; tag should then have its &quot;mode&quot; attribute set to &quot;Off&quot;.<br><br>

            <table width=100% bgcolor="#ffffcc">
               <tr>
                  <td>
                      <code><pre>

&lt;!-- Web.Config Configuration File --&gt;

&lt;configuration&gt;
    &lt;system.web&gt;
        &lt;customErrors mode=&quot;Off&quot;/&gt;
    &lt;/system.web&gt;
&lt;/configuration&gt;</pre></code>

                  </td>
               </tr>
            </table>

            <br>

            <b>Notes:</b> The current error page you are seeing can be replaced by a custom error page by modifying the &quot;defaultRedirect&quot; attribute of the application&#39;s &lt;customErrors&gt; configuration tag to point to a custom error page URL.<br><br>

            <table width=100% bgcolor="#ffffcc">
               <tr>
                  <td>
                      <code><pre>

&lt;!-- Web.Config Configuration File --&gt;

&lt;configuration&gt;
    &lt;system.web&gt;
        &lt;customErrors mode=&quot;RemoteOnly&quot; defaultRedirect=&quot;mycustompage.htm&quot;/&gt;
    &lt;/system.web&gt;
&lt;/configuration&gt;</pre></code>
                  </td>
               </tr>
            </table>
            <br>
    </body>
</html>

4. Thinking that something magically broke – I removed everything and repeated the whole step 2 (I generated a new bot by connecting it to the service shared by QnA Maker), and the situation in step 3 repeated. 

I am working on the standard Azure settings, I did not change anything in the code and it breaks itself (?). I will be grateful for help. 

PS. I am using paid Azure subscription.

Best Regards,
Andrzej

**Comment by EricDahlvang** [comment]
Hey andrzejsobczak,

I apologize for not responding sooner.  Your situation sounds frustrating.

The developers believe its a bug on our side. They've been actively investigating and intend on releasing a fix as soon as possible.  Thank you for your patience thus far.

We will leave this issue open until the fix is released.

Peace,
Eric

**Comment by EricDahlvang** [comment]
There is a potential fix being released.

**Comment by EricDahlvang** [comment]
Thank you for reporting this.

I'm closing the issue because its been addressed.  If something like this happens again, please re-open it.

**Comment by stevengum97** [comment]
Due to similarities between issues, reopening this and referencing issue #2577.

**Comment by DonSchenck** [comment]
Any news/updates?

**Comment by EricDahlvang** [comment]
Hey DonSchenck,

The issue has been addressed, but the fix involves a two part roll-out to production.  One piece was released last night, and newly created bots will no longer have this issue.  However, there's another part to the fix that is scheduled to be released this morning.  Once that is released, and verified, I'll close this issue.

Thanks for your patience.

**Comment by DonSchenck** [comment]
Terrific news! Thanks!

**Comment by EricDahlvang** [comment]
Thank you for reporting this.  I'm closing it now since the issue has been resolved.  If you have any other problems, please re-open this one, or create a new issue.

**Comment by andrzejsobczak** [comment]
The nightmare has returned. After about a week of correct work again InternalServerError appeared:
InternalServerError
<!DOCTYPE html>
<html>
    <head>
        <title>Runtime Error</title>
        <meta name="viewport" content="width=device-width" />
            <span><H1>Server Error in '/' Application.<hr width=100% size=1 color=silver></H1>
            <h2> <i>Runtime Error</i> </h2></span>
            <b> Description: </b>An application error occurred on the server. The current custom error settings for this application prevent the details of the application error from being viewed remotely (for security reasons). It could, however, be viewed by browsers running on the local server machine.
            <br><br>

**Comment by nwhitmont** [comment]
relates to #2603
