### ISSUE TITLE
Load the modularize dialog script 

### ISSUE THREAD

**Issue by vvatanabe** [Microsoft/BotBuilder#258]
Modularize the dialog script to other files.
And I want to load the script files.

I want to add a load function to DialogCollection for that.
First of all, I made the extension. Please look at the following.
https://github.com/vvatanabe/botbuilder-load-scripts

It was in reference to the hubot-scripts.

Please consider this suggestion.

**Comment by Stevenic** [comment]
Nice... I had done something similar in  `examples\TestBot`.  I think this is a great extension but I'd want to think about how well it fits in the base library. I've generally been trying to follow how Express.js models things and they leave route mounting up to the developer as there are literally dozens of strategies for how you organize your routes.  They all have pros & cons and there's no one right way.

Could you do me a favor and add this feature to [UserVoice](https://feedback.botframework.com/) for voting?

**Comment by vvatanabe** [comment]
I see.

> I had done something similar in examples\TestBot. 

Wow! It's a good test of how :-)

> They all have pros & cons and there's no one right way.

I think so too. We want to hear everyone's opinion.
OK. I add this feature to UserVoice for voting and I'll contact you again.

Thank you to consider.

**Comment by Stevenic** [comment]
The version I did is a little different. When you load index.js it loads everything else in the directory and essentially adds them to the bot. It was really specialized around making it easy to add new tests. But each test could add as many dialogs as it needed to.
