### ISSUE TITLE
[Azure Portal] Bot Service 500 Error - Unable to view Bot code in portal.

### ISSUE THREAD

**Issue by irwinwilliams** [Microsoft/BotBuilder#2580]
I have four bots listed here: https://dev.botframework.com/bots
when I try to access any of them, I get "Object reference not set to an instance of an object" .
Even curiouser, when I try to access the code for the bots in Azure, I get a 500 error.
What's going on?

**Comment by nwhitmont** [comment]
@irwinwilliams I ran into the same issue yesterday.  I believe this has been fixed but you are loading a old version of the site.  Try logging out of your account, and logging back in & let me know if you are still seeing this issue.

**Comment by irwinwilliams** [comment]
Bot framework works in Edge, but viewing the bot in Azure is still failing.

**Comment by nwhitmont** [comment]
@irwinwilliams thanks for the update. I have reported this error to the Bot Service Azure Portal team for further investigation.

**Comment by EricDahlvang** [comment]
Please download the Azure Storage Explorer from here: [http://storageexplorer.com](http://storageexplorer.com)

Login, and navigate to your resource group's Storage Account.  When you open it, you'll see File Shares.  There you'll find the source for your bot.

![botframeworksupportstorage2](https://cloud.githubusercontent.com/assets/11055362/24989474/ba02d652-1fc1-11e7-88af-cf5005c2809b.png)


This bug has been fixed, so future Bot Service bots will not experience this issue.  The Bot Service and Bot Framework are currently in preview and being improved upon daily.  We apologize for this inconvenience, and hope your future experiences with the Bot Framework are productive and enjoyable.
