### ISSUE TITLE
[Feature Request] Node SDK - Allow user to insert line breaks "\n" in HeroCard.text

### ISSUE THREAD

**Issue by nwhitmont** [Microsoft/BotBuilder#2583]
As a user of the Node SDK for BotBuilder, I would like to have the ability to format the HeroCard's text using `\n` style line breaks.

**Comment by mohit-jcc** [comment]
@nwhitmont  Any update on this sir? I can really use this feature in my project. Thx

**Comment by nwhitmont** [comment]
relates to #1439

**Comment by JasonSowers** [comment]
As a user of the.NET for BotBuilder, I would like to have the ability to format the HeroCard's text using \n, \r\n,  \n\n, or StringBuilder.AppendLine(string s) style line breaks.

**Comment by JasonSowers** [comment]
please refer to #1439 line breaks are now possible in hero cards.
