### ISSUE TITLE
Request to 'https://smba.trafficmanager.net/apis/v3/conversations' failed: [400] Bad Request 

### ISSUE THREAD

**Issue by paulosines** [Microsoft/BotBuilder#2588]
I see this error when sending a message from the Skype channel. No changes have been made in the code.

`
Error: Request to 'https://smba.trafficmanager.net/apis/v3/conversations/29%3A1Qth93NzxHzycTpZAt1kMg22YAFSFb1E-ZzullAy6z60/activities' failed: [400] Bad Request
    at Request._callback (D:\home\site\wwwroot\node_modules\botbuilder\lib\bots\ChatConnector.js:452:46)
    at Request.self.callback (D:\home\site\wwwroot\node_modules\request\request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (D:\home\site\wwwroot\node_modules\request\request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (D:\home\site\wwwroot\node_modules\request\request.js:1091:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
`

**Comment by nwhitmont** [comment]
@RichMoeMSFT any ideas on this one?

**Comment by nwhitmont** [comment]
@paulosines Are you using C# or Node SDK? What version of the SDK do you have?

**Comment by paulosines** [comment]
I'm using 3.7.0
I also noticed that this only happens with one particular skype account. 

I created a new skype account and it seems to work fine.
Could this be related to the fact that the first account has an old conversation ID? 

Yesterday I also noticed that the session.message.address.id returns IDs in a slighty different format (it adds a pipe and a number as a suffix)

**Comment by nwhitmont** [comment]
@pablocastro I'm not completely sure, but it sounds like the Skype conversation ID format has changed, thus causing the API 400 error.  Thanks for the update, I'm glad you found a working solution.

**Comment by paulosines** [comment]
I'm using Node SDK

**Comment by paulosines** [comment]
It seems that an old converstation ID is causing the issue, but I'm just speculating.

**Comment by paulosines** [comment]
Did you fix the issue? I still cannot use my skype account? This could happen with  other accounts.

**Comment by EricDahlvang** [comment]
Hi paulosines,

Have you tried "/deleteprofile"? 

From FAQ:
https://docs.botframework.com/en-us/technical-faq#my-bot-is-stuck--how-can-i-reset-the-conversation

The engineers are aware of channel api changes affecting existing conversations.  Currently, the easiest resolution is to restart the conversation.

**Comment by paulosines** [comment]
Thanks, this worked.

**Comment by fivesquared** [comment]
reopened  https://github.com/Microsoft/BotBuilder/issues/2737 --- /deleteprofile doesn't seem to work in skype.

**Comment by chinchang** [comment]
Facing same issue and /deleteprofile is no command in skype.

**Comment by santiagodoldan** [comment]
I'm having a similar issue while trying to end a conversation manually like `session.endConversation()`

```
Error: Request to 'https://smba.trafficmanager.net/amer-client-ss.msg/v3/conversations/XXX/activities/XXX' failed: [400] Bad Request
```

**Comment by sagarpomal** [comment]
Facing same issue while trying to session.endConversation()
