### ISSUE TITLE
Localization not working in .NET BotBuilder version 3.5.5.0

### ISSUE THREAD

**Issue by MarekLani** [Microsoft/BotBuilder#2589]
Hi, I have been trying to use locale to change language and use default multilingual resources for forms. That means use built in automatic translation. It works in version 3.5.0, however when I updated botbuilder to 3.5.5.0 it stopped working. I observed this for Czech (cs-CZ) end French (fr-FR) locale. Even when I changed locale to one of these I was getting prompts in english (prompt when provided bad value etc. - ""sdf" is not a Ako sa mas? option"). As it was working in 3.5.0 I suspect that this commit has caused the problem: https://github.com/Microsoft/BotBuilder/commit/2956e495068ce431850322954a3295afac3d8c5f

Morover, when trying annotated Sandwich demo a fill the form in French, first prompt is in french, however subsequent steps falls to default language automaticcaly, that means I can choose type of sandwich in French however next prompt regarding size of sandwich switches to English

**Comment by msft-shahins** [comment]
@MarekLani thanks for reporting the regression. I just pushed a [fix](https://github.com/Microsoft/BotBuilder/commit/57b7275ecded52a448cf0333fe0d1e87537118d0) for this to develop branch and it should be resolved with the next release.

**Comment by EricDahlvang** [comment]
Hi MarekLani,

The latest Bot Builder release has addressed the bug: https://www.nuget.org/packages/Microsoft.Bot.Builder/3.5.8

Thank you for reporting this. Please create a new issue if you have any other problems.
