### ISSUE TITLE
Multiple session.send()

### ISSUE THREAD

**Issue by JpEncausse** [Microsoft/BotBuilder#259]
Hi,
I try to do in a function of a waterfall:
```
session.send('how')
session.send('are')
session.send('you')

```
But only the first one is sent, is there some kind of restriction ?
I thought next() was "flushing" the session
Should I concatenate my string ?

**Comment by Stevenic** [comment]
I'm assuming your using the emulator... The node version has an issue with sending multiple messages to the emulator. I have a fix coming very shortly. You can look at `examples\TestBot\BotConnectorBot.js` for a temporary workaround.

**Comment by Stevenic** [comment]
The latest version so fix this for the emulator. Please re-open if the issue is still persisting.

**Comment by JpEncausse** [comment]
I update to latest library and latest emulator
It seems the bug came back

**Comment by v-thgratMSGit** [comment]
Closing this issue due to age. @JpEncausse - please open a new issue if this issue is not fixed and needs further discussion. @Stevenic - reopen if necessary. Thanks!
