### ISSUE TITLE
Instantiating ConnectorClient using connector 3.6.0-alpha fails

### ISSUE THREAD

**Issue by msft-shahins** [Microsoft/BotBuilder#2590]
`new ConnectorClient(serviceUrl)` fails with the following exception:``The service provider instance was not register. Please call RegisterServiceProvider before using ServiceProvider.Instance.``

This happens when Microsoft.Bot.Connector is instantiated directly and BotAuthentication is not referenced on the code path. An example, will be a worker job that runs independently and gets triggered to instantiate connector client to send proactive messages to user. Because of not referencing BotServiceProvider or BotAuthentication on the code (and builder container is not referenced), instantiation of ConnectorClient will fail since no ServiceProvider instance is initialized: https://github.com/Microsoft/BotBuilder/blob/develop/CSharp/Library/Microsoft.Bot.Connector.Shared/ServiceProvider.cs#L82

Also there is a typo in the InvalidOperationException message: 
https://github.com/Microsoft/BotBuilder/blob/develop/CSharp/Library/Microsoft.Bot.Connector.Shared/ServiceProvider.cs#L86

**Comment by luizcarlosfaria** [comment]
Just call `services.UseBotConnector()` on ConfigureServices method of your Startup class.
This method is provided by Microsoft.Bot.Connector.BotServiceProviderExtensions extension class.
