### ISSUE TITLE
[Skype Channel] Unable to add attachments from chat console in bot framework preview?

### ISSUE THREAD

**Issue by atmakurihk** [Microsoft/BotBuilder#2592]
Hi Everyone,
 I deployed a chat bot on azure
-- While conversing with the bot  the bot frame work preview(https://dev.botframework.com/) not accepting attachments added by user this issue is present in web chat channel also where as the same bot is accepting images when tested on skype
--Pleas help me if there is any configuration issues in bot framework
Thanks in advance

**Comment by rahul251993** [comment]
Your bot is accepting attachments on skype and not in other channels? Is that what you mean?

**Comment by atmakurihk** [comment]
Yes
-- while communicating with my bot on skype i am able to upload images and documents
same is not happening in bot framework preview site as well as i frame given by web chat channel

**Comment by nwhitmont** [comment]
@atmakurihk are you using C# or Node SDK?

**Comment by atmakurihk** [comment]
-- i am using node sdk

**Comment by atmakurihk** [comment]
-- Hi guys Thanks for the help
--The issue got resolved and i am able to upload files from chat window both in bot frame work preview and also in web channel
-- But i have no idea what is the cause of this issue from past three days.
