### ISSUE TITLE
[Facebook Messenger] Gifs not working inside facebook attachments templates

### ISSUE THREAD

**Issue by rahul251993** [Microsoft/BotBuilder#2593]
webViewMsg.sourceEvent({
          facebook: {
            attachment: {
              type: 'template',
              payload: {
                'template_type': 'generic',
                elements: [
                  {
                    'title': 'xyz,
                    'subtitle': 'ABC',
                    'image_url' : 'any gif',
                    buttons: [
                      {
                        'type': 'web_url',
                        'url': '.Start',
                        'title': 'Start',
                        'webview_height_ratio': 'compact'
                      },
                      {
                        'type': 'postBack',
                        'title': 'Stop',
                        'payload': 'Stop'
                      }
                    ]
                  }
                ]
              }
            }
          }
        });

**Comment by nwhitmont** [comment]
@rahul251993 are you using C# or Node SDK?  Did you try adding your attachment data to the `channelData` property or your message?

**Comment by JasonSowers** [comment]
closing this issue, please feel free to continue the conversation if needed and we can reopen.
