### ISSUE TITLE
entity resolver

### ISSUE THREAD

**Issue by subhans3tech** [Microsoft/BotBuilder#2594]
how can i assure that unless the entity is resolved bot keep asking question for entity in nodejs. unless it is resolved

**Comment by nwhitmont** [comment]
@subhans3tech can you provide a code example that demonstrates your issue?

**Comment by stevengum97** [comment]
@subhans3tech is this your question on [StackOverflow](http://stackoverflow.com/questions/40657949/how-to-stop-bot-to-not-move-forward-unless-entity-is-resolves)? Is it reasonable to assume you're using the same code, or are you having a different case/issue?

**Comment by subhans3tech** [comment]
var cityEntity = builder.EntityRecognizer.findEntity(args.intent.entities, 'location');
        var number = builder.EntityRecognizer.findEntity(args.intent.entities, 'builtin.number');
		var time = builder.EntityRecognizer.findEntity(args.intent.entities,'builtin.datetime.time');
		var date = builder.EntityRecognizer.findEntity(args.intent.entities,'builtin.datetime.date');



I have these for entities now I want that unless these entities not solved bot sould not move forward

**Comment by stevengum97** [comment]
I've answered your original question over on [StackOverflow](http://stackoverflow.com/questions/40657949/how-to-stop-bot-to-not-move-forward-unless-entity-is-resolves/43441804#43441804). Please only post SDK-related bugs, issues, or suggestions here on GitHub and ask general how-to questions on [StackOverflow.com](https://stackoverflow.com/)

Closing issue.

**Comment by subhans3tech** [comment]
Thanks alot for your help and sorry for using the wrong platform.
Regards,
Subhan
