### ISSUE TITLE
[Facebook Channel] Carousel cards don't show all images on smartphone but works on web

### ISSUE THREAD

**Issue by giorgobiani** [Microsoft/BotBuilder#2595]
Hi,

I have very strange problem with card images: So I have card carousel, which I construct dynamically, from DB. Images are fetched from my service, all images have same dimensions & all are png. So strange thing is that when getting carousel from the web, everything works great, but when talking to bot from android, only 2 of 8 card images are shown. If I open image url directly from the browser, it works. I tried Thumbnail Card & Hero Card, shortened title and subtitle, added buttons, but same problem. 

Any ideas?

**Comment by nwhitmont** [comment]
@giorgobiani are you using C# or Node SDK for BotBuilder?

**Comment by giorgobiani** [comment]
So turned out, I had messed up with Content-Length header, I was not sending it correctly in my image handler. Still the fact that some of the images showed up, despite incorrect Content-Length is interesting, but anyway, problem solved. Closing Issue.
