### ISSUE TITLE
[LUIS]  Pre-built Entities geography not working with countrys

### ISSUE THREAD

**Issue by pkpaul5** [Microsoft/BotBuilder#2598]
I was trying the bre-built entities geography, but apparently does not work for international locations, such as Mexico, Guatemala, Honduras etc.
![bug](https://cloud.githubusercontent.com/assets/27424468/25004984/90c8902a-2074-11e7-80e6-61e413870316.png)

**Comment by stevengum97** [comment]
Hi @pkpaul5,

The geography prebuilt entity does support international locations as indicated in the screencap at the bottom. I've tested the three countries and found that only the words Mexico, Mexico's
and mexico's were properly recognized. As a side note, Canada and Japan are two other countries I tested that were also properly recognized. 

I've contacted the LUIS support team and will update this issue when I receive a response. 

![prebuilt geography description](https://cloud.githubusercontent.com/assets/14935595/25015498/e0c60ee8-2030-11e7-8715-47fca521d0c9.PNG)

**Comment by pkpaul5** [comment]
Hi Steven,

If you see the screen shot that I have attached with the issue, Mexico was not recognized.
There is definitely some issue at LUIS end. Thanks for looking into the issue.

Thanks
Prasenjit

**Comment by stevengum97** [comment]
The LUIS team is aware of the issue and is working on improving the accuracy of the prebuilt geography entity. For the time being I'm recommending creating a **[Closed List](https://dev.projectoxford.ai/docs/services/5890b47c39e2bb17b84a55ff/operations/5890b47c39e2bb052c5b9c14)** which will allow you to make custom hard coded entities. On the documentation it provides an example where abbreviations are provided as synonyms of the places like California (CA, Calif.). Two other alternatives would be to create a custom entity that you train with multiple utterances, or by using a **[phrase list](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/add-features)**, which would require a number of recognized entities to be combined with the list of not-recognized entities. 

Here is what the result looks like from a LUIS endpoint with the utterance, *"Where is Guatemala?"* when using a Closed List:

    "entities": [
        {
            "entity": "guatemala",
            "type": "Locations",
            "startIndex": 9,
            "endIndex": 17,
            "score": 1,
            "resolution": {
                "guatemala": "guatemala"
            }
        }
    ]

**Comment by stevengum97** [comment]
Closing this issue for now.

**Comment by pkpaul5** [comment]
Steven,

Is there a timeline by which this issue will be fixed?

Thanks
Prasenjit

**Comment by stevengum97** [comment]
Hi Prasenjit,
They unfortunately couldn't provide me with a committed ship date, but I will update here when the improved implementation has been released. Thank you for your understanding, and though I've closed this issue please continue to post here if you have any questions regarding the issue.
