### ISSUE TITLE
[Feature Request] An equivalent of the routing event in the outbound message pipeline

### ISSUE THREAD

**Issue by pveller** [Microsoft/BotBuilder#2599]
The good thing about `routing` event is that it carries the `session` object when emitted. It's also *synchronous* thanks to `emit` being synchronous. No other event in the incoming (`receive`, `incoming`) or outgoing (`send`, `outgoing`) does the same. The `session` is not passed to the middleware stack in `eventMiddleware` either. There are valid scenarios, I believe, where bot developers would need to get a hold of the `session` on the way out before the asynchronous batching of the messages starts, and before the `onSave` is triggered. Something like `emit(session, batch)` right before the `onSave` in `Session.prototype.sendBatch`? The only problem is that it's the `Session` that orchestrates the process, not the `UniversalBot`. 

Here's a blog post that I wrote a few days ago that hopefully will explain why I think an event like that is needed: http://www.pveller.com/smarter-conversations-part-4-transcript/

**Comment by nwhitmont** [comment]
@pveller for reference, are you using C# or Node SDK for BotBuilder?

**Comment by pveller** [comment]
node.js

**Comment by sgellock** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botbuilder-channels/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team

**Comment by rjgmail88** [comment]
link https://github.com/microsoft/botbuilder-channels/
<https://github.com/microsoft/botbuilder-channels/issues> gives 404 error.

**Comment by sgellock** [comment]
Sorry for the confusion.

The link should be
https://github.com/microsoft/botframework-services/issues


Scott



On Oct 1, 2018, at 9:08 AM, RnJ <notifications@github.com<mailto:notifications@github.com>> wrote:

link https://github.com/microsoft/botbuilder-channels/
<https://github.com/microsoft/botbuilder-channels/issues> gives 404 error.
