### ISSUE TITLE
Actions not generating response in nodejs Library

### ISSUE THREAD

**Issue by ChristopherMeek** [Microsoft/BotBuilder#260]
In the following waterfall the first method is executed over and over again.

    [
        function (session) {
            session.send({
                "type": "Message",
                "attachments": [{
                    "text": "Pick one:",
                    "actions": [{
                        "title": "Willy's Cheeseburger",
                        "message": "CB"
                    }, {
                        "title": "Curley Fries",
                        "message": "F"
                    }, {
                        "title": "Chocolate Shake",
                        "message": "S"
                    }]
                }]
            });
        },
        function(session, results) {
            session.send(JSON.stringify('did it work?'));
        }
    ]

My bot is connected to facebook (the emulator seems to just swallow the actions :(  ) and displays the actions as links correctly, however when I click on an action the bot responds by sending the same message again rather than the "did it work?" message I'm expecting.

Is this a bug or simply something that's not yet supported in the nodejs version of the libraries?

**Comment by Stevenic** [comment]
Yes... `session.send()` wont trigger the waterfall to advance to the next step. You'd need to either call one of the built-in prompts (which don't support buttons yet) or roll your own button based prompt as a dialog. If you look at issue #236 I provide an example of rolling your own and button support using the built-in `Prompts.choice()` prompt should be ready very soon.

**Comment by ChristopherMeek** [comment]
Thanks for the pointer... I figured as much.  I rolled my own basic one

    var botbuilder = require('botbuilder');
    var util = require('util');

    function ActionsDialog() {
        ActionsDialog.super_.apply(this, arguments);
    }

    util.inherits(ActionsDialog, botbuilder.Dialog);

    /*
    Args:
    {
        text: 'Please Choose one of these',
        actions: [
            { text: 'Option Text', message: 'Option Value' }
        ]
     }
    */

    ActionsDialog.prototype.begin = function begin(session, args) {
        session.send({
            type: 'Message',
            text: args.text,
            attachments: [args]
        });
    };

    ActionsDialog.prototype.replyReceived = function replayReceived(session) {
        log('ending actions dialog with result of ' + session.message.text);
        var dialogResult = {
            response: session.message.text,
            resumed: botbuilder.ResumeReason.completed
        };
        session.endDialog(dialogResult);
    };

    module.exports = ActionsDialog;

Which works fine when called with a session.begingDialog(...), on both the webchat and textbot (allthough the text bot doesn;t display the options it does accept the response).  However through face book the replyReceived is never called, as it the bot is not tracking the state correctly.  Will keep digging or wait for official support!

**Comment by Stevenic** [comment]
Official support will be in the next drop of the SDK. If you look at the commits you'll see I've already checked in one half of this. I'm working on the other half.
