### ISSUE TITLE
postToBot.PostAsync doesn't Invoke StartAsync

### ISSUE THREAD

**Issue by RazSoft** [Microsoft/BotBuilder#2600]
Tried calling a dialog from message controller, Corresponding dialog's  StartAsync is never invoked. Call goes directly to MessageReceivedAsync

`var postToBot = beginLifetimeScope.Resolve<IPostToBot>();
await postToBot.PostAsync(activity, token);`

`var dialog = scope.Resolve<IDialog<object>>();
await Conversation.SendAsync(activity, () => dialog);`

Here is the method from Dialog 

`public class RootDialog : IDialog<object>
    {
public async Task StartAsync(IDialogContext context)
        {
            IMessageActivity msg = (IMessageActivity)context.Activity;

            ResumptionCookie resCookie = new ResumptionCookie(msg);

            ConversationStarter.resumptionCookie = new ResumptionCookie(msg).GZipSerialize();

    }
}`

**Comment by JasonSowers** [comment]
Have you resolved this issue or is it still causing trouble for you?
