### ISSUE TITLE
[WebChat] Same Token can be used to embed chat on multiple sites, Token is not secure.

### ISSUE THREAD

**Issue by HardikShah289** [Microsoft/BotBuilder#2601]
I have created bot which I would like to use on my site in secure way. So, I am using Token instead of Security Key to hide Security  key from others. 
So, I followed below document from bot framework and generate token.
[embed-chat-control2](https://docs.botframework.com/en-us/support/embed-chat-control2/)

I used Postman tool to send request for token and generated token and build below URL to embed in iframe on my web site.
https://webchat.botframework.com/embed/QuizHS?t=[secret_token]

Ideally, this token should work for single device from where it was requested. so, if someone else try to use same token it should not worked, right? 

In my testing, I forwarded above URL to my another device(another mobile, laptop, which is not on same network) and i was able to open link and it displayed chat & chat are getting shared across like group chat. So, now i have two devices sharing the same Secret token. This is security concern as my data is not secure. 

Could you please fix this and is there way to hide token from querystring and use cookie or session or headers to secure it?

**Comment by nwhitmont** [comment]
@HardikShah289 

We recommend configuring your embedded chat widget as described here (Step 2, Option 1):
https://docs.botframework.com/en-us/support/embed-chat-control2/

>Option 1 - Keep your secret hidden, exchange your secret for a token, and generate the embed

>Use this option if you can make a server-to-server call to exchange your web chat secret for a temporary token, and if you want to discourage other websites from embedding your bot in their pages.

>Note that this does not prevent another website from embedding your bot in their pages, but it makes it substantially harder than option 2 below.

>To exchange your secret for a token and generate the embed:

>Issue a server-to-server GET request to “https://webchat.botframework.com/api/tokens” and pass your web chat secret as the Authorization header.
>The Authorization header uses the “BotConnector” scheme and includes your secret. (This auth scheme may also be used with a token but for now we’re using our secret to generate a token.) See example below.
>The call will return a token good for one conversation. If you want to start a new conversation, you must generate a new token.
>Change the “s=” parameter in your iframe embed to “t=”. The “t=” form works with tokens and automatically renews them before they expire.

If you have further questions, I recommend you post the issue in the BotFramework-WebChat repository here: https://github.com/Microsoft/BotFramework-WebChat

**Comment by HardikShah289** [comment]
hi @nwhitmont , I created ticket on WebChat, but it seems like issue with Bot Framework Token generation part. 
I am following Option 2, and issue is people can stole token and use it for the conversation and due to which conversation history can be shared or even they can chat till token is expired.

https://github.com/Microsoft/BotFramework-WebChat/issues/428
