### ISSUE TITLE
DialogAction in C# ?

### ISSUE THREAD

**Issue by kei3004** [Microsoft/BotBuilder#2602]
Hi, Is there a way to bind a function to a button in a Card  in C#? Like dialogAction in Nodejs ?

I want to call a certain method from my dialog when a button is hit.
Thanks.

**Comment by BenjaBobs** [comment]
For the channels that support it, you can use ```postBack``` (see more [here](https://docs.botframework.com/en-us/csharp/builder/sdkreference/attachments.html)) as the action type, to send a message back to the bot that is hidden from the user. You can then catch hidden message and call a function from there. You could even use a scorable to make sure the hidden message is parsed correctly. Example of scorable [here](https://docs.botframework.com/en-us/csharp/builder/sdkreference/d6/de6/_delete_profile_scorable_8cs_source.html).

**Comment by kei3004** [comment]
Nice :) thanks for the help !
