### ISSUE TITLE
[QnA Maker] InternalServerError - Bot & QnA Maker ->again

### ISSUE THREAD

**Issue by andrzejsobczak** [Microsoft/BotBuilder#2603]
Because I can not reopen issue #2572 I created this new one.

The nightmare has returned. After about a week of correct work again InternalServerError appeared:

InternalServerError
<!DOCTYPE html>
<html>
            <span><H1>Server Error in '/' Application.<hr width=100% size=1 color=silver></H1>

            <h2> <i>Runtime Error</i> </h2></span>

            <font face="Arial, Helvetica, Geneva, SunSans-Regular, sans-serif ">

            <b> Description: </b>An application error occurred on the server. The current custom error settings for this application prevent the details of the application error from being viewed remotely (for security reasons). It could, however, be viewed by browsers running on the local server machine.
            <br><br>

**Comment by nwhitmont** [comment]
@andrzejsobczak we have just released an update to the Azure Bot Service to address this issue.

Are you still experiencing the error?

**Comment by andrzejsobczak** [comment]
Hi,

Thanks! I have re-created my bot (fourth time ;)) and now is OK.

Best Regards,
Andrzej

**Comment by nwhitmont** [comment]
@andrzejsobczak awesome! thanks for the update, and good to hear it's working this time ;-)
