### ISSUE TITLE
[SMS Channel] API returns 404 Not Found

### ISSUE THREAD

**Issue by nsingh** [Microsoft/BotBuilder#2605]
I just followed the instructions to enable the SMS channel. The inbound API calls from Twilio to the Botframework at `https://sms.botframework.com/api/sms` is returning a 404.

Attaching debug logs from Twilio:

**Timestamp** `2017-04-17 06:49:04 UTC`
**URL** `https://sms.botframework.com/api/sms`

**POST Request Params** *Some account details x'ed out*
`ToCountry=US&ToState=CA&SmsMessageSid=SMacd6bb25a0f295a047985d14a43dxxxx&NumMedia=0&ToCity=SAN+BRUNO&FromZip=94566&SmsSid=SMacd6bb25a0f295a047985d14a43dxxxx&FromState=CA&SmsStatus=received&FromCity=LIVERxxxx&Body=Help&FromCountry=US&To=650866xxxx&ToZip=94030&NumSegments=1&MessageSid=SMacd6bb25a0f295a047985d14a43dxxxx&AccountSid=xxxxxxxxxxxxxxxxxxx&From=925339xxxx&ApiVersion=2008-08-01`

**Response Code**
`404 Not Found`

**Response Headers**
```
X-Cache MISS from ip-172-18-7-3.ec2.internal
Server Microsoft-IIS/8.0
Strict-Transport-Security max-age=31536000
X-Cache-Lookup MISS from ip-172-18-7-3.ec2.internal:3128
Expires -1
Content-Length 0
Cache-Control no-cache
Content-Type text/xml; charset=utf-8
Pragma no-cache
Date Mon, 17 Apr 2017 06:49:06 GMT
Set-Cookie ARRAffinity=7d0f7e956ad9f3de932d34d054da6b67c25398680fd13e94c7a876463cf5cb14;Path=/;Domain=sms.botframework.com
X-Powered-By ASP.NET
```
**Response Body**
`No body`

**Comment by nwhitmont** [comment]
@nsingh are you using C# or Node.js SDK for BotBuilder?

I just tested the API endpoint at `https://sms.botframework.com/api/sms` and did not see any errors.  Are you still experiencing the issue?

**Comment by nwhitmont** [comment]
@nsingh reopen if you're still having issues.

**Comment by nsingh** [comment]
@nwhitmont Thanks for your response, the issue is still there and i'm using the node SDK . I'd like to borrow your expertise to help test this out. I sent a text message to the phone number I registered and in the Twilio dashboard, I tracked the above API error. 

Is that the ideal way of initiating communication with the SMS channel?  If not, whats the correct way of testing the integration works?

**Comment by mitin001** [comment]
@nsingh Your request headers may be missing content length. I've had the same symptoms until I started counting content lengths and sending them to form ASP.NET endpoints.

**Comment by nboussarsaracn** [comment]
Problem persists .. same setup with the main thread. Any solution?
