### ISSUE TITLE
[Question] Error: Dialog[*:/] not found

### ISSUE THREAD

**Issue by zwang454** [Microsoft/BotBuilder#2607]
Hello,

So my bot started returning me the following error in the emulator even though I haven't changed anything and it was working fine before.

session.beginDialog(/)
Error: Dialog[*:/] not found.

I'm not sure what the specific problem is, LUIS is working fine so I'm guessing its the code. Please take a look?
```
var restify = require('restify');
var builder = require('botbuilder');

//=========================================================
// Bot Setup
//=========================================================

// Setup Restify Server
var server = restify.createServer();
server.listen(process.env.port || process.env.PORT || 3978, function () {
   console.log('%s listening to %s', server.name, server.url); 
});
  
// Create chat bot
var connector = new builder.ChatConnector({
    appId: process.env.MICROSOFT_APP_ID,
    appPassword: process.env.MICROSOFT_APP_PASSWORD
});
var bot = new builder.UniversalBot(connector);
server.post('/api/messages', connector.listen());


//=========================================================
// Bots Dialogs
//=========================================================


var model = 'https://westus.api.cognitive.microsoft.com/luis/v2.0/apps/bd0e8c3f-9a91-4f2a-8086-fdbfc05cc4b2?subscription-key=3c1c88e0cd3842a8819a2b92a2921543&timezoneOffset=0.0&verbose=true&q=';
var recognizer = new builder.LuisRecognizer(model);
bot.recognizer(recognizer);

bot.dialog('hello', [
    function (session) {
        session.sendTyping();
        builder.Prompts.text(session, '你好，请问您叫什么名字');
    },
    function (session, results) {
        session.sendTyping();
        session.send('你好' + results.response);
    },
]).triggerAction({matches:'hello'});
```

**Comment by pveller** [comment]
You don't have a dialog bound to `/` (aka `default` dialog). Anything other than `hello` intent will try to find a default dialog and your bot doesn't have one. As an alternative to explicitly binding a dialog to `/`, you can pass it on to the `UniversalDialog` constructor as a second argument after the `connector`.

**Comment by zwang454** [comment]
Right, so for this I'm only testing the hello intent and its returning that error. Its weird because it was fine when I lasted tested it but after awhile of not touching it, its not working anymore.

by binding it to / do you mean the line 

bot.dialog('/', intents) ?

or do you mean adding / to 

bot.dialog('hello', [

like bot.dialog('/hello', [

**Comment by pveller** [comment]
Try removing the `&q=` from your LUIS endpoint. I believe the Bot Framework will add that. I am speculating but your LUIS recognizer might not be working the way you expect it and you always, even when you think you say `hello`, end up in `/` due to an error.

**Comment by pveller** [comment]
The `bot.dialog('/', intents)` will attach an instance of `IntentDialog` to `/` and then it will take care of the routing within. That's how I used to do until 3.5 and the new routing system. I meant that you would explicitly (via `bot.dialog('/')`) or implicitly (via passing your default dialog to the `UnivesalBot`) define a *confused* dialog. Something that will handle the `None` intent. You might as well attach a dialog to the `None` intent. You have options.

**Comment by zwang454** [comment]
hmm doesn't seem to be the problem with the none intent or the &q=... I will try to set up another bot and fiddle with the LUIS recognizer abit. If you have any recommendations that I can try please let me know. Thanks! P.S. BTW big fan of your eCommerce chatbot-example!

**Comment by stevengum97** [comment]
@zwang, try have you tried to reassign your dialogId to '/hello'? If not please do so and let me know what happens. If you were using an `IntentDialog` then the normal practice would be to create a 'root' dialog: `bot.dialog('/', intents)`

Since you seem to be following a sample and not using `IntentDialog`, I believe you should have a `/` inside of your dialogIds (e.g. '/hello', '/goodbye').

If you want to read more on IntentDialog (I recommend it!), you can find an article/section [here](https://docs.botframework.com/en-us/node/builder/chat/IntentDialog/) and find the actual reference documentation [here](https://docs.botframework.com/en-us/node/builder/chat-reference/classes/_botbuilder_d_.intentdialog.html).

**Comment by nwhitmont** [comment]
In general, it's good to have a default dialog handler that binds to the '/' route.  You can use this route to start out your Bot's dialog and then redirect to other dialogs based on user input. 

For example - the below default dialog ('/') checks for the presence of `session.userData.name` and redirects the user to the `/profile` dialog if the `name` property is not present.
```
bot.dialog('/', [
    function (session, args, next) {
        if (!session.userData.name) {
            session.beginDialog('/profile');
        } else {
            next();
        }
    },
    function (session, results) {
        session.send('Hello %s!', session.userData.name);
    }
]);

bot.dialog('/profile', [
    function (session) {
        builder.Prompts.text(session, 'Hi! What is your name?');
    },
    function (session, results) {
        session.userData.name = results.response;
        session.endDialog();
    }
]);
```

More info on dialog configuration can be found here: https://docs.botframework.com/en-us/node/builder/chat/dialogs/

**Comment by zwang454** [comment]
@stevengum97 even when I add the '/' it still doesn't work unfortunately

**Comment by comalex** [comment]
@zwang454 try: `'*:/'` instead of `'/'`
