### ISSUE TITLE
[Skype Channel] There was an error completing this request due to an internal channel failure.

### ISSUE THREAD

**Issue by vardeg2017** [Microsoft/BotBuilder#2608]
Good day.
I not good at c# and in english, but i'll try to describe my problem.
I took one of the examples and created a bot, create and 
configured hosting. On the "My Bot" page at "dev.botframework.com" i use test button and test chat -all works perfectly. 
But after adding the bot to Skype and trying to write to it - I do not get an answer to Skype and on the page "My bots" in the section appears red issue in which the following is written:: There was an error completing this request due to an internal channel failure.
Have no idea what to do.
My Bot's app id: 10c07d49-125a-4452-afb8-7740a86bad54

**Comment by vardeg2017** [comment]
I added the telegramm channel - I do not have any problems with it. Telegramm works as it should.

**Comment by JasonSowers** [comment]
@vardeg2017 Is this still not working for you?

**Comment by ameyvaert** [comment]
Is there a fix to this issue? I am having the same problem but I see that this problem has been closed.
