### ISSUE TITLE
ConnectorBot in Waterfall model, unable to go back to Waterfall Step2

### ISSUE THREAD

**Issue by officialdharam** [Microsoft/BotBuilder#261]
So, I have a Connector Bot and Slack integration. The Bot talks to LUIS. One of my Intents is to UpdateAddress, which is implemented in a waterfall fashion.  Here is an example.

Me: Please update the shipping address.
Bot: What do you want me to update it to?
Me: Hyderabad
Bot: Sorry! I didn't understand

Now, the exact same code in a Text Bot works and my conversation ends well. 

Here is the difference I found after logging some statements:
In Text Bot, the dialog data for both the statement is:
`{"BotBuilder.Data.Group":"BotBuilder.Id.DefaultGroup","BotBuilder.Data.Intent":"UpdateAddress","BotBuilder.Data.WaterfallStep":0}`

`{"BotBuilder.Data.Group":"BotBuilder.Id.DefaultGroup","BotBuilder.Data.Intent":"UpdateAddress","BotBuilder.Data.WaterfallStep":1}`

For Connector Bot it is:

`{"BotBuilder.Data.Group":"BotBuilder.Id.DefaultGroup","BotBuilder.Data.Intent":"UpdateAddress","BotBuilder.Data.WaterfallStep":0}`

`{"BotBuilder.Data.Group":"BotBuilder.Id.DefaultGroup","BotBuilder.Data.Intent":"None"}`

Is there a bug in the Connector bot?

**My bot name is** restserverbot

Here is the relevant part of the code snippet:

**Dialog for Intent UpdateAddress**
```javascript 
dialog.on('UpdateAddress', 
[
    function (session, args) {
        console.log(JSON.stringify(session.dialogData));     
        builder.Prompts.text(session, "What is the new address you want me to update to?");
    },    
    function (session, results) {
        console.log(JSON.stringify(session.dialogData));
        if (results.response) {
            session.userData.newAddress = results.response;
            session.send('Address Updated');
        }	
    }
]
);

// Dialog for Intent: None

dialog.on('None', function (session, args) {
	console.log(JSON.stringify(session.dialogData));
	session.send("Sorry! I didn't understand");	
});

**Comment by Stevenic** [comment]
I would definitely expect the same behavior on both. Have you tried using the emulator?

**Comment by officialdharam** [comment]
Yes! I have tried the emulator, the behavior is same as I described in the bug. Here is a screenshot of the conversation.

![image](https://cloud.githubusercontent.com/assets/2534571/15205395/83e9ba76-1834-11e6-8224-cceb61b8af2b.png)

**Comment by Stevenic** [comment]
Could you update to v0.10.0 and see if it still reproduces. I did just rewrite most of the code for the builtin prompts.

**Comment by officialdharam** [comment]
Ok! I tried updating the builder's version to 0.10.0. I am afraid, it behaves the same. Here is the JSON responses from the emulator.


[responses.txt](https://github.com/Microsoft/BotBuilder/files/261227/responses.txt)

**Comment by Stevenic** [comment]
Anyway you can send me an actual code file that repro's the problem? I can track it down and fix the issue pretty quickly. Since we're dealing with a LUIS model here you're welcome to email me the code at stevenic@microsoft.com

**Comment by officialdharam** [comment]
Hey Steven!  I have tested with two channels, Skype and Slack. Slack is giving me trouble whereas Skype behaves appropriately.

Thanks for looking into though. I can proceed with Skype, so if you want, you can look at this at your own convenience.

**Comment by Stevenic** [comment]
I actually just looked back through the responses.txt and I notice that when you reply to the prompt in the emulator your callstack is completely gone when the bot replies. This is likely an indication that your code is throwing an exception somewhere. Have you tried debugging with break on all exceptions turned on?

**Comment by officialdharam** [comment]
I see! No I haven't tried debugging with break on all exceptions on. But again, it is really strange that the behavior in Skype is different than the ones in Slack and Emulator. 

I will try debugging with the flag on as you suggested and keep you posted with the update.

**Comment by Stevenic** [comment]
Any luck?

**Comment by Stevenic** [comment]
Could you please re-open if you're still having an issue.
