### ISSUE TITLE
Bot replies Multiple times while initiating the conversation.

### ISSUE THREAD

**Issue by Chitma** [Microsoft/BotBuilder#2611]
Hi Guys,

I want my bot to send welcome message whenever a user uses my iframe for the first time.

I have added code in ActivityType.ConversationUpdate

 case ActivityTypes.ConversationUpdate:
                        IConversationUpdateActivity update = activity;
                        using (var scope = DialogModule.BeginLifetimeScope(Conversation.Container, activity))
                        {
                            var client = scope.Resolve<IConnectorClient>();
                            if (update.MembersAdded.Any())
                            {
                                var reply = activity.CreateReply();
                                foreach (var newMember in update.MembersAdded)
                                {
                                    if (newMember.Id != activity.Recipient.Id)
                                    {
                                        reply.Text = $"Welcome {newMember.Name}!";
                                    }
                                    else
                                    {
                                        reply.Text = $"Welcome {activity.From.Name}";
                                    }
                                    await client.Conversations.ReplyToActivityAsync(reply);
                                }
                            }
                        }
                        break;

Whenever I am trying to initiate conversation, bot replies welcome multiple times. How should I make it single time.

Thanks , 
Manish Chitre.

**Comment by BenjaBobs** [comment]
When the conversation is started, both the user and the bot is added to the conversation. 
You do the correct check with
```
if (newMember.Id != activity.Recipient.Id)
{
    reply.Text = $"Welcome {newMember.Name}!";
}
else
{
    reply.Text = $"Welcome {activity.From.Name}";
}
```
In the case where the bot is added, ```newMember.Id == activity.Recipient.Id``` holds true, so to fix this, you need to remove the else clause.

**Comment by Chitma** [comment]
Thanks a lot @BenjaBobs
