### ISSUE TITLE
[Slack Channel] Button Prompt which works in Web Chat does not work in Slack

### ISSUE THREAD

**Issue by Girimurugan** [Microsoft/BotBuilder#2614]
Dear Team,

We are providing an user prompt (below code) as button asking for a confirmation in our Chat Bot.
builder.Prompts.choice ( *** {listStyle: builder.ListStyle.button});

This works fine in Web Chat. But once we add the same Chat Bot in Slack Channel and click on the button we get the 403_client_error message in slack.

![image](https://cloud.githubusercontent.com/assets/24765686/25129511/05d35e78-245c-11e7-99ac-569e4aa55860.png)

Please let us know if there are any limitations of using buttons in Slack or how this can be resolved in such a way that prompts as buttons work in Web Chat & slack as well.

Best Regards,
Giri

**Comment by nwhitmont** [comment]
@Girimurugan are you using C# or Node.js SDK for BotBuilder?

**Comment by Girimurugan** [comment]
We are using node.js SDK

**Comment by nwhitmont** [comment]
Are you sending the Slack message config via the `channelData` object?  

Also, for reference, you will find the best information in the Slack docs, for example:
https://api.slack.com/tutorials/intro-to-message-buttons
https://api.slack.com/docs/message-buttons

**Comment by nwhitmont** [comment]
@Girimurugan did you enable + configure Interactive Messages in our Slack app's configuration via https://api.slack.com/applications ?

**Comment by Girimurugan** [comment]
We are not using Slack's channelData object. But we have enabled Slack as another channel for our Bot App. So, I am assuming that all the features which work in Web Chat will work for Slack with out need for additional Slack specific handling.

Yes, we have enabled Interactive Messages.

![image](https://cloud.githubusercontent.com/assets/24765686/25170344/d9742004-2507-11e7-9e01-ef9fbfdd8f6a.png)

**Comment by nwhitmont** [comment]
@Girimurugan try removing the `listStyle` option from your `Prompts.choice` code.  When I created a Slack demo bot to test this, I didn't use any `listStyle` options and the bottons worked fine (botbuilder v3.7.0).

WebChat and Slack are two _very different channels_. In general, each channel has distinct configuration options that will different than the others.

**Comment by nwhitmont** [comment]
Check out this project for a working example Slack bot: 
https://github.com/nwhitmont/botframework-slack-support-bot
