### ISSUE TITLE
[Question] Is there any way to scan barcode or QR code in microsoft botframework 

### ISSUE THREAD

**Issue by sumitdobhal** [Microsoft/BotBuilder#2616]
Is there anyway to scan barcode or QR code in microsoft botframework?

**Comment by nwhitmont** [comment]
@sumitdobhal great question. are you using C# or Node.js SDK for BotBuilder?

**Comment by sumitdobhal** [comment]
Yes I am using C#.

**Comment by nwhitmont** [comment]
@sumitdobhal thanks for the update. - Currently BotBuilder SDK does not support QR Code scanning/creation, you would need to use a third party  library to accomplish this.
