### ISSUE TITLE
[Skype Channel] Bot does not accept Add Contact request from Skype

### ISSUE THREAD

**Issue by guestuser123** [Microsoft/BotBuilder#2617]
This is related to Issue #36 - 

On the first registration with Skype, everything went fine and the bot was interactive. The next day Skype / bot did not respond and there was an "Internal channel error" in the bot dashboard.

No code changes were made other than just waiting a few hours.

Could not resolve the issue so removed the Skype channel and re-added it.

I could not get the Bot to show up until I found it in the "New contact list" on Skype. It says "This person is not in your contact list" and I cannot message the bot. When I click the "Add to contacts" button it says "A contact request is sent" 

The bot / channel never accepts the contact request.

The bot handle is #BACMpshChatBot

I am using the latest Skype client.

**Comment by guestuser123** [comment]
Ok after more trial and error.

I do not think the "Add Contact" functionality from Skype works. Registration of the Bot has to happen through that 

https://join.skype.com  link that is presented to you in the bot dashboard.

If your bot is not in your contacts list after pressing the above link, I found there's no way the bot accepts the Skype "Add Contact" request. 


Using that link and a in-private (no cookies, no nothing) browser session, I added the bot. Signed in with credentials (note: the same ones as I signed in with before so not sure what changed) and then looking at Skype the bot is now authorized.

So it might be re-registered something, it might have been a transient Skype issue, or a portal issue. Hard to tell.

**Comment by nwhitmont** [comment]
@guestuser123 are you using C# or Node.js SDK for BotBuilder?

**Comment by guestuser123** [comment]
This is the C# SDK

**Comment by JasonSowers** [comment]
@guestuser123 have you resolved this issue or are you still seeking help with this?

**Comment by guestuser123** [comment]
Well the issue went away after re-registering the bot eventually, but I am sure if this were a production bot you do not have the luxury of re-registering.

So therefore I would say unless the root cause is found it is still an issue. Maybe not for me but for someone's future bot.

**Comment by grisevg** [comment]
Didn't work for me.
