### ISSUE TITLE
[Slack Channel] OAuth scopes 

### ISSUE THREAD

**Issue by pranavv** [Microsoft/BotBuilder#2619]
How can use microsoft oauth for slack with more permission scopes in slack like scope=incoming-webhook,bot,team:read,users:read,users:read.email,users.profile:read , but add to slack button in bot framework page shows scope as bot only , if use with extended scopes then redirect uri isn't working. 
so i tried merging slack oauth (add to slack) with redirect uri to slack.botframework.com and state as my bot name , when i do this im landing into this page with below error

Our apologies, but it looks like something has gone awry. Don’t worry, it’s not your fault, but you won’t be able to install Pico right now. Give me the nerdy details	

Uh oh, (Ur bot) has run into a problem

Invalid permissions requested
Invalid scope: users:read.email;redirect_uri=https://slack.botframework.com/home/auth

**Comment by delight-by** [comment]
To be honest, BotFramework works horribly with the Slack at the moment. All you get is not documented anywhere _installationUpdated_ (aka _bot_token_ RTM event) event which only gives you bot token, but not the user token, so you find yourself in a situation where you have no technical ability to find out what user added the bot to the team.
One solution that works but still sucks is to ask user permissions twice - once with your own redirect_uri (and your own scopes) and once with BotFramework's one.

**Comment by nwhitmont** [comment]
@pranavv What is your specific use-case for Slack? Eg. what are you trying to accomplish here?

Also, are you using C# or Node SDK? What version of the SDK are you using?

**Comment by nwhitmont** [comment]
@delight-by Can you provide more specific details about your scenario? For example, where in your workflow did you encounter the issue. Can you provide a code example that we can use to reproduce the issue? Screenshots of the issue and what triggered it?

**Comment by nwhitmont** [comment]
@pranavv In order to utilize the "Add to Slack" button to distribute your Slack bot app, you will need to officially publish your Slack App to the Slack directory by [following the instructions in the Slack API docs](https://api.slack.com/slack-apps#installing_apps).

**Comment by pranavv** [comment]
My use case is if user adds a bot using add to slack,  I need to read all the users info and email  present in team and send welcome message. , if use with extended scopes then redirect uri to our sit isn't working. You may check this by adding scopes in slack and check add to slack button present in the bot framework portal
