### ISSUE TITLE
Bot Framework version 

### ISSUE THREAD

**Issue by deepaksubramoniam14** [Microsoft/BotBuilder#2620]
hi all,

we created a test bot and deployed the same in one of the server and the same was hosted in iis.
.net framework in server : 4.0

we configured the same url in bots ,getting "unauthorized" error.

can anyone suggests the mandatory .net framework version needs to be available in server .

thanks in advance...
With Regards
Deepak Subramoniam

**Comment by nwhitmont** [comment]
@deepaksubramoniam14 are you using C# or Node SDK for BotBuilder? On your server deployment, are you using Azure App Service, Bot Service, or VM?

**Comment by deepaksubramoniam14** [comment]
HI,

please find the following answers

We are using C# for Bot Builder. We are deploying our bot application in AWS cloud server as a IIS application.

Thanks in Advance...
With Regards
Deepak Subramoniam

**Comment by nwhitmont** [comment]
@deepaksubramoniam14 thanks for the update.  If you are having issues with Amazon Web Services configuration, I recommend you contact AWS support directly.

**Comment by deepaksubramoniam14** [comment]
hi nwhitmont,

can you please guide me the steps i should follow to publish my code in cloud server. i published my code in file system and deployed the application in iis and hosted the same. 

while configuring in bot framework , i am getting error. unauthorized.

while debugging getting

<Error>
<Message>
The requested resource does not support http method 'GET'.
</Message>
</Error>

but if i straight away publish in azure app store, then no issues.

PLease correct me if am doing wrong deployment steps.

Thanks in Advance,...
With Regards
DeepaK Subramoniam
