### ISSUE TITLE
[MS Teams] 403 Forbidden on downloading attachment (with token)

### ISSUE THREAD

**Issue by msimecek** [Microsoft/BotBuilder#2621]
Hello, is there a way to get the proper token for **MS Teams attachments** using the C# SDK? When a user sends my bot an image and I try to download it using MicrosoftAppCredentials.GetTokenAsync it returns 403. The same code works with Skype.

```
using (HttpClient hc = new HttpClient())
{
    if (isSkype) // isSkype is always True in this code
    {
        var token = await new MicrosoftAppCredentials().GetTokenAsync();
        hc.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
    }
    var result = await hc.GetStreamAsync(url);

    result.CopyTo(copy);
    copy.Seek(0, 0);
}
```

**Comment by RichMoeMSFT** [comment]
In general, attaching a file in Teams basically uploads or references that file in Sharepoint.  Bots cannot access those files.  While the bot could access content inline (e.g. paste an image or gif into the body of the message), the attachment of generic files isn't possible at this point.

**Comment by msimecek** [comment]
The issue seems to appear for **my user account only**. When someone else from the organization sends an image to the bot in MS Teams it works fine.

**Comment by JasonSowers** [comment]
@msimecek Still having this problem or has it been resolved?

**Comment by msimecek** [comment]
@JasonSowers It seems to have resolved itself :) Works fine now. Closing.

**Comment by mtestasecca** [comment]
Hi, i'm getting same issue with NodeJs on MS Teams. I inspected the request and the token is provided.

// Request file with Authentication Header
var requestWithToken = function (url) {
    return obtainToken().then(function (token) {
        return request({
            url: url,
            headers: {
                'Authorization': 'Bearer ' + token,
                'Content-Type': 'application/octet-stream'			
            }
       }, function (error, response, body) {
			  console.log('error 1:', error);
			  console.log('statusCode 1:', response && response.statusCode);
			  console.log('body 1:', body); 
		})
    });
};

// Promise for obtaining JWT Token (requested once)
var obtainToken = Promise.promisify(connector.getAccessToken.bind(connector));

var checkRequiresToken = function (message) {
    return message.source === 'skype' || message.source === 'msteams';
};

Isn't an easier solution than needing to make a GET request to download the attached file, like having the content in the attachment object itself? Any ideas or nodeJS sample implementations?

    function (session, results) {
		builder.Prompts.attachment(session, "Attach file please");
	},
	function (session, results) {
		var msg = session.message;
		if (msg.attachments.length) {
			 var attachmentFileName = msg.attachments[0].name;
                         var attachmentContentURL = msg.attachments[0].contentUrl;
                         var attachmentContent = msg.attachments[0].content; // Is empty and useless
                          // ..do something with the file

**Comment by drewB** [comment]
In case anyone else was running into 403s and found this issue.  There is an error in the samples because attachement.contentURL does not include the needed auth token.  See https://github.com/microsoft/BotBuilder-Samples/pull/3947 for the fix.
