### ISSUE TITLE
[LUIS] Intent scores from LUIS before match, and ClosedListEntity

### ISSUE THREAD

**Issue by xitij** [Microsoft/BotBuilder#2624]
I'm currently using the node.js framework latest version. I using LUIS and have programmed a handful of Intents and a `ClosedListEntity` recognizer using the LUIS APIs.

There are some utterances that LUIS matches with a very low scores (< 0.1) that are not hitting my desired dialog. I'm currently using an `onDefault()` handler that I would like to be hit if the score threshold is below some level.

For example:
I have the following intents: `Tickets`, `Hotels`, `Bars`
I have about 70 Entities (cities) defined using the ClosedListEntity.
User types: `"San Francisco"`
LUIS returns:
```
"intents": [
{
"intent": "Tickets",
"score": 0.0918271
},
{
"intent": "Hotels",
"score": 0.08158548
},
{
"intent": "Bars",
"score": 0.0389895
},
{
"intent": "None",
"score": 0.0352892876
}
```
In this case I'd like to hit the `None` intent and then prompt the user with choice.
I realize I can go to Luis.ai and train the `None` intent to hit for the entity `San Francisco` but that would require me training for _every single city_ in my list which will be growing to a large number.

Since I'm using a ClosedListEntity the LUIS website doesn't actually have a list of the entities (I assume because this is a new feature) and I'm unable to train LUIS with something like this: `[$city]`.

My 2 questions are:
1) Is it possible (or will it be possible) to train LUIS with a ClosedListEntity along the lines of:
None = `[$city]`
2) Can I add a handler/trigger that is hit before an intent is "matched" but after the response has been run through LUIS? If that is possible I can check for a threshold score and redirect to `onDefault()` or something along those lines.

Thanks

**Comment by cahann** [comment]
Are you creating the close list entities using the LUIS programmatic APIs? You don't have to label all the city names as none but LUIS should learn the correlation between the List entity and the none intent after few examples.

**Comment by stevengum97** [comment]
Could you post the code for your LuisRecognizer and IntentDialog, if you're using the IntentDialog? I'd also like to see your `onDefault()` code. If the [intentThreshold](https://docs.botframework.com/en-us/node/builder/chat-reference/interfaces/_botbuilder_d_.iintentdialogoptions.html#intentthreshold) and Recognizer aren't working properly, seeing your code could help diagnose the problem. Which SDK are you using?

**Comment by xitij** [comment]
> Are you creating the close list entities using the LUIS programmatic APIs?

Yes
> You don't have to label all the city names as none but LUIS should learn the correlation between the List entity and the none intent after few examples.

This was my thinking as well but in the past, before using a closed list entity (just creating an entity using the GUI on the LUIS.ai page), I had to program most (not sure exactly how many) of the entities before LUIS recognized the correlation. 

> Which version of the SDK are you using?

I'm using v3.6.0

> Could you post the code for your LuisRecognizer and IntentDialog, if you're using the IntentDialog? I'd also like to see your onDefault() code. If the intentThreshold and Recognizer aren't working properly.

I read the docs on the recognizer and the default threshold value, which appears to be `0.1`. After checked the score of some of the intents I do see that they are above this level ~`.12`. So I think the threshold property is working fine. Regardless I'd like to recognize that an `[$entity]` is presented as input and have `None` the selected intent.

I've managed to get a workaround for now where I have defined my own `Recognizer` and passed it to the `intentDialog`. This recognizer checks for an exact match in text of one of the cities. If there is an exact match I assign the `None` intent with a score of 1.
```
const DefaultRecognizer = (options) => ({
  recognize: (context, callback) => {
    let intent = { score: 0.0, intent: null };
    if (context.message.text) {
      const text = context.message.text.trim().toLowerCase();
      return options.SearchHelper.findExactMatch({ q: text })
        .then((hits) => {
          if (hits.length > 0) {
            if (text === hits[0].name.toLowerCase() || hits[0].keywords.indexOf(text) > -1) {
              // Confirm that the text is only the topic/entity and nothing else
              intent = {
                intent: 'None',
                score: 1,
                entities: [text]
              };
            }
          }
          callback.call(null, null, intent);
        })
        .catch((err) => {
          pino.error(err);
          callback.call(null, null, intent);
        });
    }
    callback.call(null, null, intent);
  }
  /* eslint-enable consistent-return */
});
```

I'm using `intentDialog` here is a code snippet:
```
const intentDialog = new builder.IntentDialog({ recognizers: [recognizer, expressionRecognizer, defaultRecognizer] });
...
intentDialog.matches('Hotels', '/hotels')
      .matches('tickets', '/tickets')
      .matches('Bars', '/bars')
      .onDefault((session, args) => {
        if (session.message.text) {
          searchComponent.findExactMatch({ q: session.message.text })
            .then((topics) => {
              if (topics.length > 0) {
                session.beginDialog('/topic', { message: session.message, topic: _.first(topics) });
              } else {
                session.beginDialog('/invalid');
              }
            });
        } else {
          session.beginDialog('/invalid');
        }
      });
```

For now this workaround has seemed to fix my issue.

I'm curious about the UI on the LUIS.ai page though. Since I'm using a closed list entity, which was created through LUIS API and not manually entered on the "Entities" page, LUIS doesn't actually show any entities as being defined. When the bot is tested it recognizes the entities. How come the Closed List Entity isn't displayed anywhere on the LUIS site?

**Comment by stevengum97** [comment]
The Closed List Entities are a new feature, which is they're not showing up right now at [LUIS.ai](https://www.luis.ai/). We're planning on incorporating them into the portal, but it's still a work in progress because we want to do it well. Currently, the only way to see they exist (besides doing an API call) is to download your model. I realize this isn't the same as seeing them within a GUI, but in your model you should be able to see them. 

I'm closing this issue for now, but if you have other questions or concerns please share them here. 

**P.S.** 
If this is going into production, you'll be able to reduce the amount of LUIS calls being performed by arranging your list of recognizers so that LuisRecognizers are last. You'll then add the [recognizeOrder](https://docs.botframework.com/en-us/node/builder/chat-reference/interfaces/_botbuilder_d_.iintentdialogoptions.html#recognizeorder) property to your [IIntentDialogOptions](https://docs.botframework.com/en-us/node/builder/chat-reference/classes/_botbuilder_d_.intentdialog.html#constructor) with a value of `'series'`. The default is `'parallel'` which will run by default 4 recognizers simultaneously (this is changeable by using the [processLimit](https://docs.botframework.com/en-us/node/builder/chat-reference/interfaces/_botbuilder_d_.iintentdialogoptions.html#processlimit) property). To give you and others an example, I've slightly modified your code:

    // I made an assumption that the recognizer is your LuisRecognizer
    const intentDialog = new builder.IntentDialog({ 
        recognizers: [expressionRecognizer, defaultRecognizer, recognizer], 
        recognizeOrder: 'series' 
    });

If anything matches with a score of 1, the rest of the recognizers will not be called.

Just a friendly tip :smiley:

**Comment by cahann** [comment]
@xitij has rolled out today in the GUI under the name of List entities.

**Comment by xitij** [comment]
@cahann Thanks I just saw it.
