### ISSUE TITLE
[Question] Parallel utterances are not processed at IntentDialog or at root

### ISSUE THREAD

**Issue by ubreddy** [Microsoft/BotBuilder#2627]
## System Information
Nodejs 3.4.4
localhost and Azure App Service both.
6.x node version
## Issue Description
When an existing dialogue is going on and say bot is doing something asynchronously or waiting to post back the results to user
     User says some utterances during this period. These utterances are processed within the existing ongoing dialogue callstack -1 instead of at root level.

## Example Code

It is long code to exactly reproduce. But let me write the steps.

Root : intentdialog  ( routes to respective intents)
intentA :  callstackA
callStackA : fn1,fn2, beginDialogEntity1,beginDialogEntity2, beginDialogEntity3, fn3

Entity2 is an api call done asynchronously. and says, "Let me look up the stuff for you"
if user is silent. no worries everything works smooth as per flow.

If user says "ok" or " you there?" the callstack reverts to beginDialogEntity2.
## Expected Behavior

ideally, it should be passed to Root intentdialog. Basically the current entire sessionState.callstack should be suspended till the bot processes the results and responds to revive and continue on the current flow.

User inputs during this time are to be processed as new utterances through intentdialog.

## Actual Results
If user says "ok" or " you there?" the callstack reverts to beginDialogEntity2. Pushed one level above in the sessionState.callstack and not to the root.

**Comment by nwhitmont** [comment]
@ubreddy Update your botbuilder  module to the current version (3.7.0) and let me know if you are still encountering the issue. --> `npm update botbuilder`

You can also use the development version by running `npm install botbuilder@next` which will install 3.8.x-beta development version of the Node SDK.

If you are still experiencing the problem after upgrading your botbuilder npm module, please provide a code example so we can better assist you.
