### ISSUE TITLE
Customize Bot User Interface

### ISSUE THREAD

**Issue by RaviTeza31** [Microsoft/BotBuilder#2628]
Hi,

I am just trying to customize the UI of my web chat bot. could you please give me any suggestions/ help regarding UI customization and If there is another approach to customize the UI.

Currently we are using an 'iframe' of a web chat bot. how do we customize its UI.

Thanks and Regards,
Ravi

**Comment by nwhitmont** [comment]
@RaviTeza31 To customize the WebChat module, head on over to https://github.com/Microsoft/BotFramework-WebChat and fork the repository, then you can add your own CSS customizations and deploy your own custom themed chat interface.  You will find the styling options here: https://github.com/Microsoft/BotFramework-WebChat/tree/master/src/scss

**Comment by RaviTeza31** [comment]
Thank you @nwhitmont. will try this for sure :)

**Comment by RaviTeza31** [comment]
Hi @nwhitmont . 
I have tried to customize the UI for my web chat bot by using the links you have provided. but I am unable to reflect the changes in it. could you please help me regarding this. How to make work this CSS in my iframe?

Thanks and Regards.
Ravi
