### ISSUE TITLE
[Question] How to send messages from background agent ?

### ISSUE THREAD

**Issue by ZOXEXIVO** [Microsoft/BotBuilder#2631]
For some triggers we need to send notifications to users, what subscribes for news.
We have serialized Reply params with ChannelUrl, From, To params to Notify users, but we can't send reply message, because we not have actual connection to bot and all requests rejected with Forbidded result.

Hot to send messages in background ?

**Comment by nwhitmont** [comment]
@ZOXEXIVO are you using C# or Node SDK for BotBuilder?

I'm not sure I understand your use case. You want your bot to send a proactive notification message to a specific user? On what channel? (Slack, Skype, FB, etc?)

**Comment by ZOXEXIVO** [comment]
User subscribes for some news tags and background crawler everytime search news and send notification to subscribers

**Comment by nwhitmont** [comment]
@ZOXEXIVO It sounds like you are looking for a proactive bot that uses Azure Functions to trigger notifications.  Check out this article for more information on integrating Azure Function triggers into your bot app - https://docs.botframework.com/en-us/azure-bot-service/templates/proactive/
