### ISSUE TITLE
[Feature Request: Node] maintainable backend integration

### ISSUE THREAD

**Issue by axelpoise** [Microsoft/BotBuilder#2633]
## Pre-flight checklist
- [X] I have [searched the existing issues](https://github.com/Microsoft/BotBuilder/issues?utf8=%E2%9C%93&q=is%3Aissue) before logging a new one.
---------------------------

## System Information

* **Node.js + npm version**

----------------------------

# Issue - Suggestion
## Description
There are a number of challenges that come along with creating very large bots.
One of these is how to separate backend data models, from the user flow.
The user flow seems to be under constant redesign due to renewed insights of the UX
department, whereas the backend is fully dependent on the backend engineers.

Changing dialogs can become a difficult and error prone process, because of significant differences
in requirements for flow and backend services.
Data is collected over many dialog steps and the collected data is seldom a set of independent parameters.
I hope to clarify the problem by a number of examples, my solutions strive to make the larger bots 
more agile in flow redesign and thus more maintainable.

## Relevance
Companies don't want to have a scattered field of bots to represent them, but rather one bot/ chat to which their users
can connect for any service. Bots will therefore become very large pieces of software with functionality comparable to websites.

### Examples
To start with the following, this is still very atomic and easily maintainable.
Maybe there is some pain because of the if statements and the readability of the code,
but at least there is no problem in moving this code.
```javascript
function(session, args, next) {
    if(args.response.value === 'something'){
        session.userData.api.values.value = 2 * args.response.value;
    } else {
        ...
    }
    
    builder.Prompts.number(session, "get a number");
    
}
```

More painful is the case where we add multiple dialogs and need to pass values between.
Then we need to add a `session.endDialogWithResult({key:value})` which is fine for dialog
logic, but when adding this just for backends, then we have the data persistence
divided over multiple dialogs, and probably multiple files.

Finally there are some APIs that will respond with an object that must be mapped to the object
you want to send to an API. This means that you will have to add this mapping logic in your 
function, making the flow code very dirty. And integrating the requests to the backend can become
very ugly to implement.

## What I want
I would like to separate the data and the flow concerns, such that I can more easily 
change the flow over time with a minimum of impact on my backend connections.
And in the process I would like to keep my code cleaner such that I can read the flow
logic better.

As I see it the problem and solution are two folded. One is passing a value from the dialogs
to a backend object and two is a separate piece of logic where all the mapping and handling is done.

#### A separate data handler 
The data handler must be part of the async flow of the bot. 
Meaning we need to integrate it somewhere. The simplest option would
be to use an extra dialog that must be called every time you want to 
do something with your data.

Inspired by redux (but not redux), I use a switch statement (or hashmap) to add different parameters,
based on their name.

- **Option 1** -> a special dialog

```javascript
bot.dialog('/apiendpoint', 
    
    function(session, args, next) {
        switch (session.userData.key) {
            case "key1":
                session.userData.api = session.userData.value;
                break;
            case "key2":
                ...
            default: "do nothing"
        }
    }
    
)
```

- **Option 2** -> an integrated data handler, just before storage

more beautiful and standardized would be an enhancement of the connector
with an extra parameter. This parameter is simply a function using the data
and giving back a new version of the data.

This function should be set within the connector just before session storage. 

on the top level thus the following code:

```javascript

var connector = new builder.Connector({
    apiEngine:engine
})

var engine = builder.apiEngine(data, cb){
    switch (data.userData.key) {
                case "key1":
                    data.userData.api = data.userData.value;
                    cb(null, data)
                    break;
                case "key2":
                ...
                default: "do nothing"
            }
}

```
and within the connector:
```typescript
...

private msaOpenIdMetadata: OpenIdMetadata;
private emulatorOpenIdMetadata: OpenIdMetadata;
private apiEngine: apiEngine

constructor(private settings: IChatConnectorSettings = {}) {
   this.apiEninge = settings.apiEngine;
   
...

public saveData(context: IBotStorageContext, data: IChatConnectorStorageData, callback?: (err: Error) => void): void {
    this.apiEngine(data, (err, data) => {
    }

...

```
#### Passing the value

Passing through values makes a lot of sense for the flow. However
for passing through data it doesn't. Best would be to pass a value
directly and handle it in the data dialog/engine. 

Using the custom prompt I can easily create such a function, however 
it might be worth standardizing such a solution.
```javascript
exports.beginDialog = function (session, options) {
    session.beginDialog('textAndData', options || {});
}

exports.create = function (bot) {
    var prompt = new builder.IntentDialog()
        .onBegin(function (session, args) {
            session.userData.key = args.key;
            session.send(args.prompt);
        })
        .onDefault(function (session) {
            
            session.userData.value = session.message.text;
            
            session.endDialogWithResult({ response: session.message.text });
            
        });
    bot.dialog('textAndData', prompt);
}

```
and the implementation is also fairly simple
```javascript
bot.dialog('/', [
    function(session, args, next) {
        
        session.beginDialog('textAndData', {prompt:'some text', key:'name'})
    },
    function(session, args, next) {
        
    }
])

```

Ideally this would look more like 

```javascript

bot.dialog('/', [
    function(session, args, next) {
        builder.dataPrompts.text(session, {prompt:'some text', key:'name'})
    },
    function(session, args, next) {
    
    }
])
```
and the corresponding prompt function as part of a data Library

```javascript

var datalibrary = new Library('dataPrompts')
datalibrary.dialog('/text', 
    new builder.IntentDialog()
        .onBegin(function (session, args) {
            session.userData.key = args.key;
            session.send(args.prompt);
        })
        .onDefault(function (session) {
            
            session.userData.value = session.message.text;
            
            session.endDialogWithResult({ response: session.message.text });
            
    })
)
```
This is very easy to implement with the current tools but might be addable as a standard library in the Universal Bot.

```typescript
...

this.localePath('./locale/');
this.library(systemLib);
this.library(dataPrompts);
if (defaultDialog) {

...

```

### Further thoughts, testing large bots

Another advantage of this separation of concerns is the testability of
large bots. Now for the backend there is a number of events that must
be called within a specific order (very straight forward contract test.)

For the bot a certain pattern must be followed, maybe different ones over
different branches but all recordable and checkable (second test, and easily isolated)

**Comment by Stevenic** [comment]
The way we envisioned this separation would happen is that you would use the same basic techniques you'd use to separate the front end of a website from your backend data.  You would have a series of API's that your dialog flows would call to pass data back and forth between the bot and your backend.  The bot really is just an alternate front end to your backend.  Or maybe I'm not following you correctly.

**Comment by axelpoise** [comment]
I completely agree with what you are saying, the bot is just another frontend. And in fact I am connecting them to the same APIs as our websites/ apps. What I am looking for and what I wanted to start a discussion about is a **formalisation** of the implementation of connecting. For example in angular 1 you would have a *controller* to deal with your view logic and call a *service* to deal with the backend API or in polymer you would have a custom ajax element you import to do the same thing.
In the specific case of the bot I need to aggregate the API data over multiple steps and dialogs, therefore I came to the solution described above. I am very curious if some kind of "service" implementation is worth adding for you and if you have a more elegant solution than I have.

**Comment by Stevenic** [comment]
I see... you're thinking of an angular style service. I'd probably prefer personally to see that as a layer above the core SDK but we're starting to think about what a 4.0 version of the SDK might look like so that's worth folding into the thought process.

**Comment by jdnichollsc** [comment]
Guys, see this template for NodeJS https://github.com/proyecto26/Bot-Framework

**Comment by JasonSowers** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
