### ISSUE TITLE
[Question] how to get the attachment original location?

### ISSUE THREAD

**Issue by wolf0x** [Microsoft/BotBuilder#2634]
How can I get the uploaded attachment original location? I dont want to download it but just need the FQDN of the file. e.g. E:\Pic\0001.png etc.. how can I get back the path before/after uploading the file?

For emulator or Skype both.

**Comment by wolf0x** [comment]
we can see the details in logs:
{
  "type": "message",
  "attachments": [
    {
      "contentType": "image/gif",
      "contentUrl": "blob:file:///b4813c39-f892-4c49-9b99-1b72227ec267",
      "name": "kenan.gif"
    }
  ],

how could I convert the blob:file///xxxxx to C:\temp\kenan.gif? I just want the path not file itself.

**Comment by nwhitmont** [comment]
@wolf0x are you using C# or Node SDK?

**Comment by wolf0x** [comment]
@nwhitmont Node.js please, any good suggestions or solution? thanks.

**Comment by nwhitmont** [comment]
@wolf0x This example shows how to get the location of your image attachment. Keep in mind that the image file may be stored in a different location depending on the channel that it is uploaded in. For example, if you bot is on Skype and the user uploads an image, the image could go into Skype internal cloud storage. Or if you are using WebChat on Azure Bot Service, the image file will be stored temporarily in Azure blob storage (which it sounds like is what you are seeing). Jut curious,  why do you need the file URL? Perhaps there is another approach to solving your issue.

Example code:
```javascript
bot.dialog('/', function (session) {
    let msg = session.message;
    
    if (msg.attachments && msg.attachments.length > 0) {
        // Echo back attachment
        let attachment = msg.attachments[0];
        session.send({
            text: `You sent: \n\n**Content Type:** ${attachment.contentType} \n\n**Content URL:** ${attachment.contentUrl} \n\n**Name:** ${attachment.name}`,
            attachments: [
                {
                    contentType: attachment.contentType,
                    contentUrl: attachment.contentUrl,
                    name: attachment.name
                }
            ]
        });
    } else {
        // Echo back users text
        session.send("You said: %s", session.message.text);
    }
});
```

**Comment by wolf0x** [comment]
@nwhitmont 

first I have to thanks for your kindly comment, however, this is what not I want... actually what I want is to get the physical file location of user uploaded, not the content URL after uploaded. e.g. a user uploaded a.jpg from his C:\temp\ folder and then bot convert it to blob with contentURL. however, when I want to call another API to reuse a.jpg, I want to avoid to get from bot but directly to get the user's physical file. you can image one scenario, if the user uploaded a file with big size, e.g. 10 MB, it first go to SKype cloud, and then I need request the stream downto local. then pipe to a file on that bot server. it is really a problem. (the API cannot use stream but need a file directly)

I am also not sure if  the SKype ( a secure channel), the contentURL can be accessed by other application other than bot via access Token only?

**Comment by nwhitmont** [comment]
@wolf0x Bot Framework does not support this functionality. I recommend uploading your image files to cloud storage, a database, or [free image hosting service via API](https://api.imgur.com/endpoints/image), then grab your files from there when you need them.

**Comment by AmolPawarGitHub** [comment]
How to get physical path of the image file in .net SDK for BOT Framework?

**Comment by nwhitmont** [comment]
@AmolPawarGitHub You are commenting on a closed issue. If you have a question or problem, please [open a new issue.](https://github.com/microsoft/botbuilder/issues/new)
