### ISSUE TITLE
Prompt dialog text not showing up in the activity logs

### ISSUE THREAD

**Issue by ManojG1978** [Microsoft/BotBuilder#2635]
## System Information

* **SDK language** - C#
* **SDK version** - 3.0
* **Development environment** - localhost 

## Issue Description

I have setup TableLogger to log all activities to the Table Store. I get all text messages that represent the conversation fine, but the one where a prompt was involved, I am getting an empty string from the logs (the prompt in this case is supposed to show a spelling corrected response). I have used the following snippet:
 `PromptDialog.Confirm(
                            context,
                            OnConfirm,
                            $" Did you mean - {tuple.Item1}?");`

The root dialog is a LuisDialog

**Comment by JasonSowers** [comment]
Hello, Have you resolved this issue on your own or do you still need help?

**Comment by ManojG1978** [comment]
No, I haven't yet found a way to address this. This is particularly needed in proactive dialogs where the prompt text is dynamic and it would important to log/analyze that offline.

**Comment by nwhitmont** [comment]
Thanks for the update @ManojG1978

Can you provide an example?

**Comment by ManojG1978** [comment]
This is the snippet I am using. Here I am using Azure Table Storage as the conversation activity/audit log. The logs are generated by registering the TableLogger (in Microsoft.Bot.Builder.Azure namespace) as a provider for IActivityLogger.  My  limitation is using AsMessageActivity() to get the conversation text and it does not work for Prompts. Any alternative/work around would be appreciated. Thanks for responding.

`const string partitionKey = "<<some key>>;

            var storageAccount = CloudStorageAccount.Parse(
                CloudConfigurationManager.GetSetting("StorageConnectionString"));

            var tableClient = storageAccount.CreateCloudTableClient();

            var table = tableClient.GetTableReference("activitylogs");

            var query = new TableQuery<TableLogger.ActivityEntity>()
                .Where(TableQuery.GenerateFilterCondition("PartitionKey", QueryComparisons.Equal, $"emulator|{partitionKey}"));

            foreach (var entity in table.ExecuteQuery(query))
            {
               
                Console.WriteLine("{0}, {1}\t{2}", entity.From, entity.Recipient,
                    entity.Activity.Type);
                if (entity.Activity.Type == "message")
                {
                    Console.WriteLine(entity.Activity.AsMessageActivity().Text);
                }
            }`

**Comment by fanidamj** [comment]
Hoping that issue has been resolved and closing it. Feel free to reopen for any questions.

**Comment by artemious7** [comment]
So where is the solution?

**Comment by youtoofan** [comment]
Struggling with the same issue here

**Comment by artemious7** [comment]
I think, the `PromptDialog` renders an `Activity` using a hero card, so it's prompt text doesn't appear in `Activity.Text` property, but in `Activity.Attachments`, which contains a card. You'll have to either add special logic to find its prompt text in the card for such activity, or use `ReplayTranscript` like this:

    var source = Conversation.Container.Resolve<IActivitySource>();
    var replay = new ReplayTranscript(context);
    await source.WalkActivitiesAsync(replay.Replay, 
        "telegram" /*or other channel id, or null*/, 
        conversatinId /* or null */, 
        oldest: showAll ? 
            DateTime.MinValue : 
            DateTime.UtcNow.AddDays(-lastDays));
