### ISSUE TITLE
[Feature Request] Slack interactive message menus

### ISSUE THREAD

**Issue by wiltodelta** [Microsoft/BotBuilder#2638]
Hi!

I trying to use Slack interactive message menus (https://api.slack.com/docs/message-menus), but without success.

```
IMessageActivity replyMessage = context.MakeMessage();
replyMessage.ChannelData = new SlackChannelData { ... }
await context.PostAsync(message);
```

```
{
    "text": "Would you like to play a game?",
    "response_type": "in_channel",
    "attachments": [
        {
            "text": "Choose a game to play",
            "fallback": "If you could read this message, you'd be choosing something fun to do right now.",
            "color": "#3AA3E3",
            "attachment_type": "default",
            "callback_id": "game_selection",
            "actions": [
                {
                    "name": "games_list",
                    "text": "Pick a game...",
                    "type": "select",
                    "options": [
                        {
                            "text": "Hearts",
                            "value": "hearts"
                        },
                        {
                            "text": "Bridge",
                            "value": "bridge"
                        },
                        {
                            "text": "Checkers",
                            "value": "checkers"
                        },
                        {
                            "text": "Chess",
                            "value": "chess"
                        },
                        {
                            "text": "Poker",
                            "value": "poker"
                        },
                        {
                            "text": "Falken's Maze",
                            "value": "maze"
                        },
                        {
                            "text": "Global Thermonuclear War",
                            "value": "war"
                        }
                    ]
                }
            ]
        }
    ]
}
```

Result:

<img width="215" alt="screen shot 2017-04-22 at 00 49 45" src="https://cloud.githubusercontent.com/assets/1192743/25302573/9d3e9e44-26f5-11e7-86bf-9fa54f1e5ef2.png">

What's wrong?

**Comment by craigjensen** [comment]
Slack Menu support is coming very soon.  The code updates are complete and are currently being tested and should be deployed to production sometime next week.  Once the code is deployed you will be able to pass the payload above in ChannelData and it render as a menu.

**Comment by wiltodelta** [comment]
@craigjensen Sounds really good! But why ChannelData didn't work?

**Comment by aakashvit** [comment]
@wiltodelta I tried in node js,But same problem it is just displaying message ,not menu.. Is this feature for paid user of slack?

**Comment by craigjensen** [comment]
@wiltodelta - The channel data gets deserialized and inspected before being passed to Slack so we needed to update the schema to pass the data through.  The code should go live in production sometime this week.

**Comment by wiltodelta** [comment]
@aakashvit Thanks!

@craigjensen BotBuilder will always fail for the latest updates to Slack, Facebook, etc. We need a mechanism that allows developers to use the new features without having to wait for updates on your part.

**Comment by wiltodelta** [comment]
@craigjensen @nwhitmont Can you tell me about the release date? Thank you!

**Comment by craigjensen** [comment]
It's live now - give it a try!

**Comment by nwhitmont** [comment]
@craigjensen excellent!
