### ISSUE TITLE
Web Chat Control Keys

### ISSUE THREAD

**Issue by JoeMayo** [Microsoft/BotBuilder#2642]
Why does the Web Chat control have two secret keys? 

The Web Chat control uses only one secret key and that's working fine, but I wonder if there's something more to it that I'm missing.

**Comment by iMicknl** [comment]
_(I am not 100% sure, the BotBuilder (WebChat) team will know for sure)_

Almost all Azure services that work with keys have multiple access / secret keys. This is for 'rolling key changes'. Normally when you want to change the key, you will have some downtime. If you have a secondary key which you can use while your regenerate the primary key, you can avoid downtime.

They describe another scenario on the [msdn blog](https://blogs.msdn.microsoft.com/mast/2013/11/06/why-does-an-azure-storage-account-have-two-access-keys/). If you want to temporary share your access, you can give them your secondary key which you can regenerate whenever you want, without downtime for your own webchat.

**Comment by JoeMayo** [comment]
Thanks - that make sense.
