### ISSUE TITLE
[Feature Request] Allow using custom logger in Node SDK

### ISSUE THREAD

**Issue by thinkkevin** [Microsoft/BotBuilder#2643]
## System Information

* **SDK language** Node
* **SDK version** 3.6
* **Development environment - localhost | other**
* **Node.js + npm version** 6.9 + 3.10

## Issue Description

We want to use our own logger so that our log information follows a consistent format.

**Comment by iMicknl** [comment]
Can't you just use a middleware for this? With a middleware you can intercept all events and incoming/outcoming messages and log them however you want. Or did I misunderstood your question?

**Example**
```javascript
bot.use({
    receive: function (event, next) {
        // Log (event)
        next();
    },
    send: function (event, next) {
        // Log (event);
        next();
    }
});
```

**Comment by thinkkevin** [comment]
@iMicknl 
So I mean that in https://github.com/Microsoft/BotBuilder/blob/master/Node/core/lib/logger.js I want to have console.[warn|error] to be replaced by using our custom logger.

or use our own custom implementation to replace https://github.com/Microsoft/BotBuilder/blob/master/Node/core/lib/logger.js

**Comment by justinwilaby** [comment]
To get by for now, you should be able to overwrite the `logger` exports with your own implementation. The logger usages throughout the code are required in using `const logger = require("../logger");` and `Object.keys(logger)` yields `[ 'error', 'warn', 'info', 'debug', 'trace', 'getPrefix' ]`. This means, you can attempt the following:

```js
const logger = require('path/to/logger);
const customLogger = require('path/to/custom/logger)';
Object.keys(logger).forEach(key => logger[key] = customLogger.prototype[key]); // Not bound
// Or alternately 
const customLogger = new CustomLogger();
Object.keys(logger).forEach(key => logger[key] = customLogger[key].bind(customLogger)); // Bound

// Rest for the program below.
```
I hope this helps. Let me know if this is successful. If not, there are other slightly more complex alternatives.

**Comment by justinwilaby** [comment]
started #4143 for an implementation that should accommodate this

**Comment by JasonSowers** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
