### ISSUE TITLE
Content type for HTML as attachment

### ISSUE THREAD

**Issue by samikroy** [Microsoft/BotBuilder#2654]
Please help with the content type to be specified to render a html file in chat window
---------------------------

## System Information

* **SDK language (C#)**
* **SDK version**
* **Development environment - localhost**

## Issue Description

While trying to render a html file in bot chat window, it does not show with
the content type as "text/html"
## Example Code
_attach.ContentType = "text/html";

**Comment by nwhitmont** [comment]
@samikroy Webchat currently does not support rendering of HTML, but it does support Markdown.
