### ISSUE TITLE
[Question] Adding API's NodeJS

### ISSUE THREAD

**Issue by runeprivate** [Microsoft/BotBuilder#2657]
Hey everyone.

This may be a question outside this topic, but I am creating a bot for Skype.
I succesfully made a code, that responses to my API.
Now, I have things like: randomurl, fact, etc.

`request("www.site.com/apikey", function(error, response, body) {
  session.send(body);`

This works fine. But now I want to add more advanced commands.
Commands like: Is it up?, host to ip, text to cool font, etc.

With that, I have this API site:

https://site.com/font.php?key=mykey&text=<TEXT> 

The question is: How will I make these work?
I want them to do something like this: !coolfont text
The person needs to fill in the text, otherwise it wont work. Please help!

Coded in NodeJS.

**Comment by nwhitmont** [comment]
@runeprivate I recommend consulting the docs on API design for your server framework of choice. For example, you can find the [Restify docs here](http://restify.com/). You will also find some useful info by searching for ["build rest api with node.js"](https://www.google.com/search?q=build+rest+api+with+node.js).
