### ISSUE TITLE
[Question] How do I end a conversation in c# framework

### ISSUE THREAD

**Issue by bgarr33434** [Microsoft/BotBuilder#2660]
## Issue Description
I am using the Echo back template and I've replaced the count of letters, etc, with my own method from a new class which grabs the current conversationID and connects to my SILVIA AI backend webservice, which takes the message.Text, submits it to my engine, which outputs a response.  The way I keep that conversation alive is by using the conversationID to maintain state.  The problem is that I cannot find any documentation in the C# literature on how to break that connection and get the bot framework to send me a whole new customerID, which starts the conversation with SILVIA all over again.  I have asked, and received responses around session.endConversation(), but that is a node.js object.  I can not find a session object in the C# implimentation.

## Example Code
```
public async Task<HttpResponseMessage> Post([FromBody]Activity activity)
        {
            if (activity.Type == ActivityTypes.Message)
            {
                ConnectorClient connector = new ConnectorClient(new Uri(activity.ServiceUrl));
                var holdConversation_Id = activity.Conversation.Id;
                Conversation_ID = holdConversation_Id.ToString();
                string msg = activity.Text;
                if (msg == "start over" || msg == "exit" || msg == "quit" || msg == "done" || msg == "start again" || msg == "restart" || msg == "leave" || msg == "reset")
                {
                    //This is where the conversation needs to get reset!
                    activity.GetStateClient().BotState.DeleteStateForUser(activity.ChannelId, activity.From.Id);
                    var sresponse = Request.CreateResponse(HttpStatusCode.OK);
                    return sresponse;
                }

                string responseText = GetRestResult(activity.Text, Conversation_ID);
                Activity reply = activity.CreateReply(responseText);
                await connector.Conversations.ReplyToActivityAsync(reply);
            }

```

**Comment by bgarr33434** [comment]
as an alternative, since it may be something that was left out of the c# framework, is there some other unique object that I can use to maintain state, but also to exit state so that a new object is created?

**Comment by bgarr33434** [comment]
How can I get an answer to this?  I am frozen without an answer.

**Comment by JasonSowers** [comment]
@bgarr33434 have you found a solution to this?

**Comment by bgarr33434** [comment]
Yes, thanks.

Brian Garr, COO
Cognitive Code
561.271.4750
@garrbrian

click here to set up a call/meeting http://doodle.com/brianlgarr

**Comment by Chitma** [comment]
I am using AuthBot for a bot. Once the bot signs in it has to logoff after a certain time. How do we do that?
