### ISSUE TITLE
[Question] Proactive message from Console application impossible ?

### ISSUE THREAD

**Issue by ZOXEXIVO** [Microsoft/BotBuilder#2661]
Why all of your samples with proactive messages using simple web application with [BotAuthentication] attribute ?
WebApp is not proactive template. 
Basic usage of proactivity - send messages from background deamon. 
Without 
`MicrosoftAppCredentials.TrustServiceUrl(notify.ServiceUrl, DateTime.MaxValue);`
we catched 403 error
With TrustUrl - we catch invalid_client.

Where is samples with C# console application for proactive messages ?

P.S.
With OAUTH you make BotBuiler is terrible for developers.

**Comment by JasonSowers** [comment]
Are you still having this issue?

**Comment by ZOXEXIVO** [comment]
Yes, i have workround with send message with httprequest to bot service, but it is not normal way

**Comment by JasonSowers** [comment]
Can you please provide a code example of what you are doing, and what you consider a "normal way"

**Comment by ZOXEXIVO** [comment]
I have simple bot with user "theme subscriptions" and background crawler.
I want send messages to users, when crawler get subscription data. Crawler - simple console app.

**Comment by McBacker** [comment]
Hi everyone!

Any update on this?

I'm facing a HTTP 403 trying to send a proactive message from a console App.

The code was based on https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-proactive-messages

Thank you

**Comment by EricDahlvang** [comment]
It is possible to use the ConnectorClient in a console application if MicrosoftAppCredentials is provided to the ConnectorClient and MicrosoftAppCredentials.TrustServiceUrl(serviceUrl); is called before sending the message.

reference:
https://github.com/Microsoft/BotBuilder/issues/3111
