### ISSUE TITLE
[Question] How to get Header Info for Skype Secure ContentURL without downloading the whole entity-body?

### ISSUE THREAD

**Issue by wolf0x** [Microsoft/BotBuilder#2662]
#How could I use "HEAD" method on SKYPE ContentURL to just get the attachment size (Content-Length)?

If I request to get the header info for a normal URL that works (request(url, {method: 'HEAD'}, function (err, res, body){). this would work properly.
but if I want to get from Skype ContentURL with below code attached, it will failed and statuscode is 405.

why I need this is because of I want to do something with the user uploaded attachment file, however, if user uploaded file size is too large then I need to notify user, so I just want to get the content-length without request/download the whole entity-body of the attachment. how could I do this validation? or how to request HEADer info without download all data in Skype Security ContentURL?

say this is a Skype ContentURL: https://apis.skype.com/v2/attachments/0-xx-d2-6b00ffcf14a4df3xx7861ace9234e52f/views/original'

```
        if(sec){
            var connector = new builder.ChatConnector({
                appId: process.env.MICROSOFT_APP_ID,
                appPassword: process.env.MICROSOFT_APP_PASSWORD
            });
            connector.getAccessToken(function (error, token) {
                headers['Authorization'] = 'Bearer ' + token;
                headers['Content-Type'] = 'application/octet-stream';
                request.get({ url: AttchContentUrl, headers: headers, method: 'HEAD' }, function(error, response){
                    if (!error && response.statusCode == 200) {
                        filesize = response.headers['content-length'];
                    }
                    else{
                        console.log("=====================<>======" + response);
                        console.log("Download failure =====================>" + response.statusCode);
                    }
                });
```

**Comment by nwhitmont** [comment]
@wolf0x are you using C# or Node SDK?

**Comment by wolf0x** [comment]
from my pasted code, that is for Node SDK, please, have any good solutioNs?

**Comment by wolf0x** [comment]
@nwhitmont from my pasted code, that is for Node SDK, please, have any good solutioNs?

**Comment by nwhitmont** [comment]
@wolf0x Without knowing how long Skype caches their images, your best bet is to store your files in a cloud or other CDN as you will have full control over your resources.

**Comment by wolf0x** [comment]
@nwhitmont Dont understand your word, When user talk to Skype Bot and upload file, the file certainly was uploaded to apis.skype.com, like: https://apis.skype.com/v2/attachments/0-ea-d2-6b00ffcf14a4df3099861ace9234e52f/views/original. this is what I said secure token. however, this URL cannot use HEAD method after obtain the Bearer Token. so I am asking how to get the content-length from such SKYPE's url instead of download the whole body instead.

**Comment by nwhitmont** [comment]
@wolf0x I found a possible solution here -
https://github.com/Microsoft/BotBuilder/issues/662#issuecomment-232223965

**Comment by nwhitmont** [comment]
Also check out the related discussion on SO -
http://stackoverflow.com/questions/38633676/upload-image-to-skype-bot

**Comment by nwhitmont** [comment]
@wolf0x what you are asking for is not currently possible, as you can see by the [405 error](https://httpstatuses.com/405)
