### ISSUE TITLE
[Question] IActivityLogger check if message is incoming or outgoing

### ISSUE THREAD

**Issue by garypretty** [Microsoft/BotBuilder#2664]
Hi.

I am using an implementation of IActivityLogger to log activity in a SQL database.  Is there an easy way of telling if the message is incoming / outgoing?  Similar to Node's send / receive middleware.

One thing to mention is that I need the solution here to be generic as it will be used against a number of bots. I was thinking I might be able to get the bot's ID or Name and check the Recipient / From properties, but not sure how I can get them within the IActivityLogger.

Thanks

Gary

**Comment by nwhitmont** [comment]
@garypretty are you using C# or Node SDK for BotBuilder?

**Comment by garypretty** [comment]
I am using C#.

**Comment by nrobert** [comment]
@garypretty in the implementation of the IActivityLogger you have the LogAsync method, where the parameter is an IActivity. This parameter has From and Recipient fields, so a basic implementation would be to use those fields yes

**Comment by garypretty** [comment]
Yes, thanks, I am using the LogAsync method.  I am trying to use the From and Recipient fields as you suggest, however I am unsure how to identify the bot ID so that I can test to see if the activity is incoming or outgoing. I am looking for a generic implementation, so do you have any idea how I can obtain the bot's ID outside of the activity itself?

**Comment by ejadib** [comment]
Hey @garypretty, you could rely on the BotId defined in the web.config, couldn't you?

**Comment by nrobert** [comment]
@ejadib the BotId is not the Id used in Recipient.Id or From.Id for every channel, isn't it?
@garypretty I quickly checked on the emulator: when the message is from the user, the "ReplyToId" field is null whereas it is not null when the bot is replying. Note that I don't know if it is valid for all channels

**Comment by garypretty** [comment]
@ejadib @nrobert I looked at this, but unfortunately your suspicions are right in that the ReplyTo ID is optional and refers to an activity being replied to, so if a new proactive message is sent for example this will not be populated and I believe certain channels don't populate this either.

@willportnoy do you have any suggestions as to how to determine incoming / outgoing in an activity logger?

**Comment by willportnoy** [comment]
@garypretty maybe you could obtain the incoming Activity from the user in your IActivityLogger implementation's constructor from the DI container and assume all other activities are from the bot.

**Comment by garypretty** [comment]
@willportnoy Thanks, I will give that a go! :)

**Comment by JasonSowers** [comment]
@garypretty did this resolve your issue?

**Comment by nwhitmont** [comment]
reopen if you're still experiencing the issue
