### ISSUE TITLE
Problems hosting bot on Azure (DirectLine issue)

### ISSUE THREAD

**Issue by DavePilks** [Microsoft/BotBuilder#267]
I have a bot that communicates with a server hosted on Azure. When I run the bot locally, using the Directline channel, it can reach the server and receive data back without issue.

When when I host the bot as a webapp on Azure, every POST I make to the server is received (by the server) but the bot hangs for 2 minutes and then I get a 500.

What could be causing this?

**Comment by Stevenic** [comment]
What language are you using? Likely your bots service is missing some dependencies.

**Comment by DavePilks** [comment]
I am using .Net.

I dont think that it is a dependency issue though.

After I hosted the bot, I can connect to it and send messages to it via the emulator. But as soon as the but tries to POST, it doesnt get a response.

Yet, if I try the same POST via Postman, it works.

**Comment by DavePilks** [comment]
On further investigation, the 500 is coming from https://directline.botframework.com/api/conversations/....

And it is happening with GET and POST calls

**Comment by DavePilks** [comment]
Any idea what could be causing this?

**Comment by DavePilks** [comment]
I managed to dig out an error, this is what I am getting

> Microsoft.Rest.HttpOperationException: Access Denied
>   at Microsoft.Bot.Connector.ErrorHandling.HandleError[ObjectT](HttpOperationResponse`1 result)
>   at Microsoft.Bot.Connector.MessagesExtensions.<SendMessageAsync>d__1.MoveNext()
>   --- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>   at Microsoft.Bot.Builder.Dialogs.Internals.SendLastInline_BotToUser.<Microsoft-Bot-Builder-Dialogs-Internals-IBotToUser-PostAsync>d__7.MoveNext()
>   --- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>   at Microsoft.Bot.Builder.Dialogs.Internals.DialogCotext.<Microsoft-Bot-Builder-Dialogs-Internals-IBotToUser-PostAsync>d__21.MoveNext()
>   --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>   at Microsoft.Bot.Builder.Dialogs.Extensions.<PostAsync>d__1.MoveNext()
>   --- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()

**Comment by dandriscoll** [comment]
This issue has been moved to email. Based on the details above, it appears that the bot is timing out and this error is being communicated back through the Direct Line API.
