### ISSUE TITLE
can't run the skypeBot with  nodejs 

### ISSUE THREAD

**Issue by airforce1st** [Microsoft/BotBuilder#268]
when i try  it,get the error message " cannot find module 'skype-sdk'",and then i try to install the " Skype Bot SDK and APIs",but the url "http://www.skype.com/en/developer/signup" always   redirected to "http://skype.gmw.cn/",how can i get the "skype-sdk"?

thanks!

**Comment by Stevenic** [comment]
You'll need to signup to access the beta. once you get whitelisted (shouldn't take too long) you can download the SDK and install it following their instructions.

**Comment by airforce1st** [comment]
thank you Stevenic ,but when i signup,still been redirect to "http://skype.gmw.cn/",can't find any infomation about sdk.

**Comment by Stevenic** [comment]
I'm not sure about that. That's on the skype side of things so you'll need to contact them.
