### ISSUE TITLE
[Bot Portal] Unable to add "Direct Line" channel on Bot configuration

### ISSUE THREAD

**Issue by alexmanie** [Microsoft/BotBuilder#2681]
I'm currently not able to add "Direct Line" channel to a newly created bot.

The bot is brand new, and once I try to add Direct Line, new windows is shown, the secret keys are generated but when I hit "I'm done configuring Direct Line", nothing happens on Bot configuration and Direct Line channel is not added.

Any workaround on that?

Thanks in advance.

**Comment by EricDahlvang** [comment]
This portal issue is currently being addressed.

**Comment by nwhitmont** [comment]
@alexmanie are you using C# or Node SDK?

**Comment by alexmanie** [comment]
hi @nwhitmont . is not a problem with the SDK, is a problem on Botframework portal (dev.botframework.com) when trying to add "Direct Line" channel to the bot.

**Comment by nwhitmont** [comment]
@alexmanie Although the Bot Portal does not reflect the existence of a Direct Line configuration at this time, if you click on "Add" and configure your Direct Line site related keys, it should still work.

**Comment by alexmanie** [comment]
Thanks @nwhitmont .
Works perfect but Direct Line is  not listed on channels.
