### ISSUE TITLE
[Question] Bad base64 padding in JWT token payload?

### ISSUE THREAD

**Issue by beebeeep** [Microsoft/BotBuilder#2682]
I have noticed that payload part of JWT token in Botframework API callbacks has bad base64 padding. For example, I got ```eyJzZXJ2aWNldXJsIjoiaHR0cHM6Ly9zbWJhLnRyYWZmaWNtYW5hZ2VyLm5ldC9kZi1hcGlzLyIsIm5iZiI6MTQ5MzcyNDYxNCwiZXhwIjoxNDkzNzI4MjE0LCJpc3MiOiJodHRwczovL2FwaS5ib3RmcmFtZXdvcmsuY29tIiwiYXVkIjoiZjgwYzFlN2MtNmUxNS00OWM1LTg2MGYtZDU2ZjNmNTk4ZDc0In0```
while correct base64 is, obviously, 
```eyJzZXJ2aWNldXJsIjoiaHR0cHM6Ly9zbWJhLnRyYWZmaWNtYW5hZ2VyLm5ldC9kZi1hcGlzLyIsIm5iZiI6MTQ5MzcyNDYxNCwiZXhwIjoxNDkzNzI4MjE0LCJpc3MiOiJodHRwczovL2FwaS5ib3RmcmFtZXdvcmsuY29tIiwiYXVkIjoiZjgwYzFlN2MtNmUxNS00OWM1LTg2MGYtZDU2ZjNmNTk4ZDc0In0=```
(note the '=' symbol at the end) 

Since payload part comes in the middle of token, it's not a problem with header size etc.

**Comment by nwhitmont** [comment]
@beebeeep are you using C# or Node SDK?

**Comment by nwhitmont** [comment]
@beebeeep Is this causing a problem in your bot implementation? If so, please explain the issue.

**Comment by beebeeep** [comment]
@nwhitmont nope, i'm using REST API, as described [here](https://docs.botframework.com/en-us/restapi/authentication/#connector---bot-step-3-verify-the-jwt-token). 

Actually, I digged into [RFC 7515](https://www.rfc-editor.org/rfc/rfc7515.txt) and it claims that base64 encoding used in JWT do not use any padding characters like `=`, so no issue in botframework, works as designed. Thank you :)
