### ISSUE TITLE
embed image in attachment

### ISSUE THREAD

**Issue by bhanuprakashk** [Microsoft/BotBuilder#269]
I am using c# for bot builder, How can I embed images in attachment, I don't want to send url link for image to client.

**Comment by Stevenic** [comment]
You need to provide a link to the image you wish to send. The user won't get it as a link though. They'll get the downloaded image for most channels.

**Comment by DavePilks** [comment]
This doesnt seem to work for Facebook messenger. How do you go about sending images and links for messenger as it doesnt support markdown

**Comment by Stevenic** [comment]
You need to send the image as an attachment. See the [examples](http://docs.botframework.com/sdkreference/nodejs/interfaces/_botbuilder_d_.iattachment.html) in the docs.

**Comment by v-thgratMSGit** [comment]
Closing this issue. Please open a new issue for further discussion if necessary. Thanks!
