### ISSUE TITLE
[MS Teams] How to get user's location details for BOT using Microsoft Teams

### ISSUE THREAD

**Issue by Malith1994124** [Microsoft/BotBuilder#2690]
I creating a chat bot using Microsoft Teams and i want to know user location and suggest hotels near him.

Example if he is Colombo 07 i want suggest Cinnamon Grand is near to you.

So can you suggest me solution how to get user's location details for bot using MIcrosoft Teams

**Comment by Malith1994124** [comment]
Um using c#

**Comment by Malith1994124** [comment]
Solution???

**Comment by SheriEllisMSFT** [comment]
There is not currently a way to do this. You are invited to post this as a feature request on [UserVoice/Teams](https://microsoftteams.uservoice.com/forums/555103-public/category/182881-developer-platform). Suphatra, from the Product Team, reads all comments and ideas, and will keep you updated on status. While you're there, vote and comment on other ideas as well! We appreciate your feedback.

**Comment by faceoffers28** [comment]
Is there an example of how to do this with a Chat Bot in Teams, using Bot Framework 4??? Specifically, I would like the Bot to send a Location request and then have the user respond with a "Yes", followed with the GPS coordinates in the ChannelData. Is this possible? If not, how do you enable sharing of Location in a Chat Bot? I don't have the option to share Location in the message options, when chatting with a Bot. This is happening on iPhone Teams app version 2.3.1. Thanks!
