### ISSUE TITLE
[Question] Get Token 404

### ISSUE THREAD

**Issue by XiaoZYang** [Microsoft/BotBuilder#2691]
I am new to `bot-framework`, so I follow the document [here](https://docs.botframework.com/en-us/core-concepts/authentication). I got stuck on *step 1*:
> Step 1: POST to the MSA login service
> To get a service-to-service token, send an HTTPS POST request to 
> https://login.microsoftonline.com/common/oauth2/v2.0/token. The body of the request must include the following form-encoded parameters

When I send a post request to target URL `https://login.microsoftonline.com/common/oauth2/v2.0/token HTTP/1.1` I got a 404 error.  Then I try with `POSTMAN` I get the same error.

The code I used to perform it has been attached following.

Anybody has an idea?

**Attachment**:
1. js code
```js
// register.js
const https  = require('https');
const querystring = require('querystring');
                                                
var req_data  = {                           
    grant_type:    "client_credentails",                   
    scope:         querystring.escape("https://graph.microsoft.com/.default"),
    client_id:     "xzy_bupt", 
    client_secret: "xzy8023"          
};     
 
var post_options = {
    hostname:             "login.microsoftonline.com",
    port:                 443,
    path:                 "/common/oauth2/v2.0/token",
    method:               "POST",
    headers:              {
        'Content-Type':   'application/x-www-form-urlencoded',
        accept: '*/*'
    }
};

var req = https.request(post_options, (res) => {
    console.log(`STATUS: ${res.statusCode}`)
    console.log(`HEADERS: ${JSON.stringify(res.headers)}`);
    res.setEncoding('utf-8');
    res.on('data', (chunk) => {
        console.log(`BODY: ${chunk}`);
    });
    res.on('end', () => {
        console.log('no more data in response');
    });

});

req.on('error', (err) => {
    console.log(`problem with request: ${err.message}`);
});

req.write(req_data.toString());
req.end();
```
2.python code
```python
import requests
import urllib

def register():
    url = "https://login.microsoftonline.com/common/oauth2/v2.0/token HTTP/1.1"

    req_data = {
        "grant_type":    "client_credentials",
        "scope":         "https://graph.microsoft.com/.default",
        "client_id":     "xiaozy_bupt",
        "client_secret": "xzy8023"
    }

    res = requests.post(
        url,
        data = urllib.urlencode(req_data)
    )

    print res.status_code
    print res.headers
    print res.text


if __name__ == '__main__':
    register()
```
3.POSTMAN
![](http://www.xiaozongyang.xyz/images/github-issue-05-03-postman.png)

**Comment by nwhitmont** [comment]
@XiaoZYang I recommend registering your bot and generating your access tokens via the [Bot Portal](https://dev.botframework.com/bots/new) rather than the method you are referring to.

In the new bot registration page, scroll down and click on the big blue button that says "Create Microsoft App ID and password". Make sure to save your App ID and password in a secure location.

**Comment by XiaoZYang** [comment]
@nwhitmont  Thx for your advice, buddy.  But it doesn't work for me. I tried in your way, however, I can't see **Create Microsoft App ID and password** button. Then I open the browser console, I found that there is a 401 error. By the Way, my os is **Arch Linux**, is it necessary to do the registry work on **MS Windows** ?  
Following is the error message for my Chrome console:
```Failed to load resource: the server responded with a status of 401 (Unauthorized)
new:1 Refused to display 'https://login.microsoftonline.com/common/oauth2/authorize?response_type=id_…0879&response_mode=form_post&state=%2Flogin%3FrequestUrl%3D%252Fblank.aspx' in a frame because it set 'X-Frame-Options' to 'deny'.
login.microsoftonline.com/common/oauth2/authorize?response_type=id_token+co…0879&response_mode=form_post&state=%2Flogin%3FrequestUrl%3D%252Fblank.aspx
 Failed to load resource: net::ERR_BLOCKED_BY_RESPONSE
```.

**Comment by nwhitmont** [comment]
@XiaoZYang 

1. Go to https://dev.botframework.com/ aka Bot Portal
2. Click "Signin" in upper right corner
3. Signin with your MSA account
4. On Bot Portal page, click "Register a bot" in the top nav menu
5. Fill in bot name, handle, description etc.
6. Under the section "Configuration" click "Create Microsoft App ID and password"
7. You will be redirected to https://apps.dev.microsoft.com/
8. Click the button that says "Generate an app password to continue"
9. Copy App ID and password and save them to a file for later reference
10. Click "Finish and go back to Bot Framework
11. You will be redirected back to Bot Portal page
12. Click "Create Bot" at the bottom
