### ISSUE TITLE
[Question] Not able to see my bot in Skype

### ISSUE THREAD

**Issue by giriganapathy** [Microsoft/BotBuilder#270]
Hello Team,

This is regarding the bot registration for Skype channel.
I have followed as per the documentation, however the bot is though listed, but it says "the bot is not ready to handle chat at the moment"
The status of the bot in "https://developer.microsoft.com/en-us/skype/bots/manage" site is showing as "Preview".

Could you please help me to start the conversation to my bot from Skype.

Regards,
Giri G.

**Comment by giriganapathy** [comment]
Sorry! Please ignore.  I am able to talk to my bot...Very happy to see it in Skype.

Thanks.

**Comment by Stevenic** [comment]
Glad you worked it out :)
