### ISSUE TITLE
Bot Builder handling of multiple messages from the same user

### ISSUE THREAD

**Issue by srozga** [Microsoft/BotBuilder#2700]
Let's say a user sends out 10 messages right after the other. They sit at keyboard and type 1 ENTER 2 ENTER 3 ENTER. etc. 

All messages arrive quickly after another and the API doesn't process the messages before they accumulate. My MessagesController calls Conversation.SendAsync(...). Does the Bot Framework process the user's messages in parallel or serially?

**Comment by JasonSowers** [comment]
Hi, have you been able to answer this question on your own or do you still need an answer?
