### ISSUE TITLE
[Question] Connect bot to custom chat window

### ISSUE THREAD

**Issue by sachinsbucket** [Microsoft/BotBuilder#2701]
I have created a bot program in node.js using microsoft bot framework. Now I want to connect that bot program with my custom chat window UI (index.html) built in HTML ,CSS & JS. I have already created a local express server. Can anyone guide me on how to integrated it as when user send some message on chat window it connects to bot and bot should send the reply back. Please help as I am new to this.

**Comment by nwhitmont** [comment]
You can find detailed instructions for embedding the web chat module in your website here:
https://github.com/Microsoft/BotFramework-WebChat

Additional guide here:
https://docs.botframework.com/en-us/support/embed-chat-control2/

**Comment by sachinsbucket** [comment]
Thanks @nwhitmont . But I don't want to register it and run it under azure/microsoft.
I want to connect bot with my custom chat window and use the functionality. There can be some rest api calls or function I need to write. But I am facing problem because the bot framework expect  message in a particular JSON format with channel id/conversation id and when I dont give it , it reply saying toket not provided.

**Comment by nwhitmont** [comment]
@sachinsbucket , sounds like you are looking for Direct Line, which allows you to configure your own web chat or communicate with your bot via other apps. 

DirectLineJS Client/Server:
https://github.com/Microsoft/BotFramework-DirectLineJS

DirectLine Example Code:
https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node/core-DirectLine

**Comment by sachinsbucket** [comment]
@nwhitmont  Do I need to register my bot on Microsoft bot framework to use DirectLineJS Client/Server?

**Comment by nwhitmont** [comment]
@sachinsbucket yes
