### ISSUE TITLE
[Bug] Bot Framework Upgrade from 3.5.5 to 3.5.8 causes Error

### ISSUE THREAD

**Issue by alokraj68** [Microsoft/BotBuilder#2705]
## System Information (Required)

* **SDK language (C#)**
* **SDK version 3.5.5 upgraded to 3.5.8** 
* **Development environment - localhost | Azure App Service **

## Issue Description

Post upgradations from 3.5.5 to 3.5.8 the bot have started crashing and is not accepting prompt confirm replies that user gives.

Tried degrading and it started working again.

**Comment by ejadib** [comment]
This is [known issue](https://github.com/Microsoft/BotBuilder/pull/2685) that was already fixed and it will be available in the next release

**Comment by ejadib** [comment]
FYI - A new package with fix #2685 was just published (https://www.nuget.org/packages/Microsoft.Bot.Builder/3.5.9)

**Comment by alokraj68** [comment]
Wow, thanks. Is there any ways to tell users that there is known bugs when
we upgrade from nuget?

**Comment by alokraj68** [comment]
Tried the same on latest build 3.5.9 and is working fine.
