### ISSUE TITLE
[Skype] AudioCard does not play audio on iOS app

### ISSUE THREAD

**Issue by nwhitmont** [Microsoft/BotBuilder#2708]
Bot Framework AudioCard does not play audio on Skype mobile app for iOS

![img_9897](https://cloud.githubusercontent.com/assets/3075047/25766510/d28cb268-31a7-11e7-9072-94d6dfdbc961.PNG)

**Comment by nwhitmont** [comment]
Sample code used to test Skype mobile app: https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node/cards-RichCards

**Comment by nwhitmont** [comment]
@nickcordrey

**Comment by nwhitmont** [comment]
@nickcordrey any updates on AudioCard does not play audio in Skype mobile iOS?

**Comment by nwhitmont** [comment]
@aery-aery I updated the audio media URL to `https` & redeployed the bot, but the audio card still doesn't play. You can verify [the bot code here.](https://github.com/nwhitmont/botframework-skype-support-dev/blob/master/server.js#L179)

**Comment by nwhitmont** [comment]
Re-tested on Skype iOS v6.35.0.54 - still not working.

**Comment by aery-aery** [comment]
@nwhitmont From you code sample I see that you use the following url for audio card
```
.media([
            {
                url: 'https://www.wavlist.com/movies/004/father.wav'
            }
        ])
```

This url seems to be unavailable. Can you try to send audio card with some different url?

**Comment by nwhitmont** [comment]
as it turns out, this particular sample site does not support SSL.

**Comment by nwhitmont** [comment]
This issue is happening again. @aery-aery 

Audio cards with HTTPS content URLs will not play in iOS Skype client.
