### ISSUE TITLE
[C# Skype] Problem with Hero cards on Skype Android since 05.05.17.

### ISSUE THREAD

**Issue by Noc2** [Microsoft/BotBuilder#2713]
## Pre-flight checklist

- [x] I have [searched the existing issues](https://github.com/Microsoft/BotBuilder/issues?utf8=%E2%9C%93&q=is%3Aissue) before logging a new one.
---------------------------

## System Information (Required)

* **SDK language (C#)**
* **SDK version 3.5.5 and 3.5.9**
* **Development environment - Azure App Service**

## Issue Description

Since Friday sometimes hero cards don’t show on the skype android app. Instead I get the following message: Card – access it on https://go.skype.com/cards.unsupported. 
It might be related to the issues #2708 and #2709 

## Example Code

```
List<CardImage> cardImages = new List<CardImage>();
List<CardAction> cardButtons = new List<CardAction>();
cardImages.Add(new CardImage(url: "https://florenceblob.blob.core.windows.net/menuimag/reminderelse.png"));
CardAction button1 = new CardAction()
{
Type = "imBack",
Title = "I took it",
Value = "I took it"
};
CardAction button2 = new CardAction()
{
Type = "imBack",
Title = "I didn't take it",
Value = "I didn't take it"
};
CardAction button3 = new CardAction()
{
Type = "imBack",
Title = "Snooze",
Value = "Snooze"
};
cardButtons.Add(button1);
cardButtons.Add(button2);
cardButtons.Add(button3);
HeroCard plCard = new HeroCard()
{
Title = "Reminder",
Text = plCardText,
Buttons = cardButtons,
Images = cardImages
};
```

**Comment by nwhitmont** [comment]
@nickcordrey

**Comment by Noc2** [comment]
Just a short update and a few additional information: 

- This issue also appears with the latest version 3.8.0 on skype android. 
- I am using await connector.Conversations.SendToConversationAsync((Activity)message); to send the hero card to the users. 
- It seems as the first hero card gets through and after that, it stops working. 
- Also, my daily tips aren't sent on skype android, which are based on a KeyboardCard (should be hero card on skype).

**Comment by Noc2** [comment]
Another update:

- On the new skype android preview everything works fine.
- I tried various settings for proactive messages, but nothing helped.

**Comment by Noc2** [comment]
I just got three hero cards in a row, so problem seems to be solved. Thanks!
