### ISSUE TITLE
[Question] bot with multiple companies db communication

### ISSUE THREAD

**Issue by aakashvit** [Microsoft/BotBuilder#2714]
I am working on bot(using node js) where we will provide bot service to multiple companies, Each company will have there own db(SAS), But we will  use only single bot , whenever client request come, we will look ,which company client belong,and bot will connect to respectively db and then give reply to user, How we can handle this in better way.
Note: Bot code and logic will same for all companies

**Comment by nwhitmont** [comment]
@aakashvit are you using C# or Node SDK?

**Comment by aakashvit** [comment]
i am  using node js

**Comment by nwhitmont** [comment]
@aakashvit write a helper function that takes the data source name or id as an input parameter, then execute your database calls as you would normally based on the user provided data source.

For example pseudo code for this type of helper function might look like:
```javascript
function dbHelper(dataSource, action) {
  switch(dataSource) {
    case('db01'):
      // send action to db01
    case('db02'):
      // send action to db02
    default:
      // send action to default database
}
```
