### ISSUE TITLE
[Feature Request] Add PrompDialog option to not post TooManyAttempts error back to user

### ISSUE THREAD

**Issue by LTsLlama** [Microsoft/BotBuilder#2717]
SDK language: C#
SDK version: 3.5.9.0
Development environment: localhost

We have multiple requirements to handle the failed parsing events on prompt dialogs differently.
This is possible by setting the attempts to 0 and handling the TooManyAttemptsException, the only problem is the TooManyAttepts error is still posted to the client before the exception is thrown.

We need an option to turn off the TooManyAttepts error being posted to the client.

**Comment by DL-LiveTiles** [comment]
@nwhitmont This is a feature request, not a question.

**Comment by PrasadGautham** [comment]
Cool...I was looking for something like this!!!

**Comment by chrizy** [comment]
Yes needed, I would also like to inspect the user input, rather then completely fail.

**Comment by gjgriffith** [comment]
We also have the need set the PromptOptions.attempts to 0 and handle the TooManyAttemptsException ourselves, but as previously mentioned, it is presently not possible to prevent a posting of the error back to the user. The best we can do is set the PromptOptions.tooManyAttempts to an empty string, so the user sees a blank message before we handle the error ourselves.

**Comment by JasonSowers** [comment]
#4533

**Comment by vishwacsena** [comment]
Workaround here is to set the retries to a very large number. You can also catch and swallow the too many attempts exception. There are no plans to add support for this to the V3 SDK.
