### ISSUE TITLE
[LUIS] No entities in my query to LUIS

### ISSUE THREAD

**Issue by mahmoudahmedarafa** [Microsoft/BotBuilder#2720]
I have added entities to my utterances, but when I enter query it doesn't return any entities.

Here is my query run [screenshot](https://postimg.org/image/7nrhq5wpt/).

My top-scoring intent is: OrderFood.

And those are [OrderFood entities](https://postimg.org/image/c3od0uovt/faf29e06/) and overall app [entites](https://postimg.org/image/41vp3lnpn/030e1617/).

So any ideas?

**Comment by stevengum97** [comment]
For polling purposes, which SDK are you using; C# or Node.js?

When was the last time you trained and published your model?

**Comment by mahmoudahmedarafa** [comment]
@stevengum97 I am using C#.

Last train: May 7, 2017, 8:25:50 PM | Last publish: May 7, 2017, 12:19:27 PM.

Here are my labeled entities in OrderFood intent ([tokens](https://postimg.org/image/5setgaziv/)).

**Comment by stevengum97** [comment]
@mahmoudahmedarafa, could you export your LUIS model so I can take a look at it?

**Comment by stevengum97** [comment]
It seems likely that the issue is a lack of training for the LUIS model.  For those utterances provided in this [image](https://s4.postimg.org/jjnmmncl9/Entities_in_Order_Food_Intent_Utterances.png) did you label the entities or did LUIS label them? 

The children in Hierarchical Entities aren't specifically tied to any utterances until you begin training the model.  Regarding this scenario, a child entity's "full name" would be "Beef::Bic Mac", but until you label "big mac" with this entity, the two won't be associated.

**Comment by mahmoudahmedarafa** [comment]
@stevengum97 I already trained my model.

Of course your offer to take a look at my LUIS model is appreciated, yet I can't export it because it requires payment. Do you have another idea?

**Comment by mahmoudahmedarafa** [comment]
@stevengum97 Issue solved. I tried the |Beef::Bic Mac" thing and it worked.

**Comment by stevengum97** [comment]
Great! If there are any other questions or comments, please feel free to post them here 😃

**Comment by mahmoudahmedarafa** [comment]
@stevengum97 As a user experience, the app should prevent me from not referencing the hierarchical entity child.

For example, when I selected 'Beef' entity in my intent instead of 'Beef::Bic Mac', the app should prevent referencing to 'beef' and accept only referring to any of its children (i.e. 'Beef::Bic Mac').

**Comment by stevengum97** [comment]
@mahmoudahmedarafa, you're right, I'll look into why users are allowed to do so.

Just to gather more information, did you visit the [LUIS docs](https://docs.microsoft.com/en-us/azure/cognitive-services/LUIS/Home) before or during this issue?

**Comment by mahmoudahmedarafa** [comment]
Yes I read LUIS docs in order to build my app.

**Comment by cahann** [comment]
@mahmoudahmedarafa, the application prevent labeling the parent cause it some cases its important to label the parent 

e.g.  Parent-->Email, Children--> CCemail & ToEmail.  

In context of adding contact you will need the parent ; Add [email] to contact list 
While for sending an email you will need the children ; Send [ToEmail] & [CCemail]

**Comment by mahmoudahmedarafa** [comment]
OK. So as I understand, if we queried by the utterance: "Add [email] to contact list", we won't get any entities from this query, yet the utterance itself will still describe an intent that we train our model on.

In case of adding email, it doesn't concern us whether it was a "CCemail " or a "ToEmail" one; we are concerned more about adding this email anyway.

Please reply back if I got something wrong.

**Comment by cahann** [comment]
No, I mean that in case of adding you need to label the parent which is "Email" but in case of sending its important to label the children. Keeping in mind that the children has all the characteristics of the parent, its an is-A relationship

**Comment by mahmoudahmedarafa** [comment]
@cahann Sure. There is no conflict between my vision and yours; I am taking about the intuition of labeling entities in the above scenario that you presented.
