### ISSUE TITLE
[Direct Line] Custom Web Chat : Channel Inspector Issue

### ISSUE THREAD

**Issue by anirudhaditya** [Microsoft/BotBuilder#2727]
I am trying to use Button feature of Channel Inspector. I can see the button appears on the inbuilt Web chat but not on the Custom Chat bot using direct line. Basically I want to provide two option to select on skype, email & SMS but don't able to get the button on the custom web chat.

**Comment by nwhitmont** [comment]
@anirudhaditya are you using C# or Node SDK?

**Comment by nwhitmont** [comment]
reopen if you're still experiencing the issue
