### ISSUE TITLE
[Feature Request: C#] When will the setPersistentMenu function be added to the C# SDK?

### ISSUE THREAD

**Issue by seca23** [Microsoft/BotBuilder#2728]
## Pre-flight checklist
-  I have [searched the existing issues](https://github.com/Microsoft/BotBuilder/issues?utf8=%E2%9C%93&q=is%3Aissue) before logging a new one.
---------------------------

## System Information (Required)

* **SDK language (C#)**

## Issue Description

I would like to know when the **setPersistentMenu** function will be available for the C# SDK for developing for the Facebook Messenger Platform?

**Comment by seca23** [comment]
Any feedback on this feature request?

**Comment by vishwacsena** [comment]
No plans to add this to the V3 C# SDK. #4360 tracks all up FB channel feature requests.
