### ISSUE TITLE
[SMS Twilio] ERROR: ChatConnector: receive - endorsements validation failure

### ISSUE THREAD

**Issue by DavidJBarnes** [Microsoft/BotBuilder#2729]
Using nodejs and botbuilder v3.8.0. Late last night my bot started throwing errors, specifically:

> ERROR: ChatConnector: receive - endorsements validation failure. channelId in req.body: sms didn't match the endorsements: directline,email,facebook,groupme,kik,slack,telegram,webchat,test.

and

> ERROR: ChatConnector: receive - invalid token. Check bot's app ID & Password.

The bot has been working great for months then got this all the sudden. I see no issues locally via emulator or via web, only seems to happen with Twilio channel. I've tried deleteing the bot registration and rebuilding; no luck. Tried updating password and confirmed appId and password credentials are correct.

**Comment by EricDahlvang** [comment]
The Bot Framework development team is addressing this issue right now. A fix will be released ASAP.

**Comment by EricDahlvang** [comment]
@DavidJBarnes a fix for this has been released.  Would you please verify on your end, and report back here.

Thanks.

**Comment by DavidJBarnes** [comment]
Success. Problem solved. Thank you!

**Comment by DavidJBarnes** [comment]
Although it seems this fix has an impact on: builder.Prompts.choice

My choice options now form a single run-on sentence.

**Comment by stevengum97** [comment]
Hi @DavidJBarnes, could you provide the snippet of code for your dialog with builder.Prompts.choice where you noticed the issue? Additionally could you take a screen capture of the dialog exchange between user and chatbot?

Was builder.Prompts.choice working before the SMS Twilio issue?

**Comment by Stevenic** [comment]
@DavidJBarnes the prompt system was completely re-written in 3.8. Could you please provide a sample of the output you're seeing. I did fix a bug as part of the re-write which may be causing your choice prompt to render using the inline style. This wasn't getting auto selected in some cases which I fixed. If you don't want the inline style to get selected you can force the list style using `builder.Prompts.choice(session, "prompt", "choice1|choices2", { listStyle: builder.ListStyle.list })`

I'd still like to see the prompt you're getting so that I can verify it's working as expected.

**Comment by DavidJBarnes** [comment]
@stevengum97 builder.Prompts.choice was working fine prior to the SMS Twilio issue.

builder.Prompts.choice(session, "Hello. Make a selection:", "Option #1|Option #2|Option #3") will yield: "Hello. Make a selection: (1. Option #1, 2. Option #2, 3.Option #3)"

**Comment by Stevenic** [comment]
That's the inline style. It should have done that before but wasn't due to a bug. You can force the use of the list style using the sample I provided.  As a note it auto selects inline anytime you have less than 4 options.

**Comment by DavidJBarnes** [comment]
Thanks, @Stevenic 

I didn't see that behavior earlier but am happy to use 4 options of force with: { listStyle: builder.ListStyle.list }
