### ISSUE TITLE
Use case question

### ISSUE THREAD

**Issue by rodzillarr** [Microsoft/BotBuilder#273]
My bot responds over 3 different channels (chat, sms, direct).   How in the world can I send a message from one channel and have it show up in another channel?  I've been trying for some time to access a direct conversation from my direct channel and send a message to an in progress conversation in another channel (whatever channel it originated from txt/chat) but my messages seem to disappear into the ether.  Is this a supported use case?  If so, do I need anything beyond the conversationId I'm already using?

Thanks anybody for any information anyone can provide.

-r

**Comment by tomlm** [comment]
You cannot directly send a message from one channel to another.

A bot can receive a message on 1 channel and then initiate or respond to a conversation on another channel.

-Tom

**Comment by rodzillarr** [comment]
> A bot can receive a message on 1 channel and then initiate or respond to a conversation on another channel.

How might a bot do that? :-)

Besides a conversation ID, what other info would I need to provide the API to initiate or respond to a conversation on another channel from the direct channel?
