### ISSUE TITLE
[Bug] Prompt.number stopped working on 3.8.0. 

### ISSUE THREAD

**Issue by arieschwartzman** [Microsoft/BotBuilder#2731]
It's unable to parse the number. Seems something wrong with the regular expression it's usוng
Instead of real expression, it's using number_exp as the expression 
Locale en-us

Node.js 
Localhost

**Comment by stevengum97** [comment]
@arieschwartzman 

Can you give an example of the utterance you gave to Prompt.number()?

**Comment by arieschwartzman** [comment]
Any number. Say "52"

**Comment by stevengum97** [comment]
@arieschwartzman that worked for me... Are you using "Prompt" or "Prompts"? If the former, the latter is the one to use and will provide you with the proper number.

**Comment by arieschwartzman** [comment]
Got it now. You have placed number_exp in the locale folder. So that defaultLocalizer class could read it. I had my own Localizer implementation that did not had this entry.

You can close this issue

**Comment by Stevenic** [comment]
Sorry about that... Can I ask why you're using your own localizer? I'd just like to better understand your scenario

**Comment by arieschwartzman** [comment]
My bot service handles several tenants (each on different endpoint) I was planning to have the localizer have different tables per tenant not just per locale, so I could have different strings for each tenant. Currently I'm not using it really, so I can remove my localizer and leave the default.
