### ISSUE TITLE
[Question] How to insert multiple Blank Lines? #1112

### ISSUE THREAD

**Issue by upendra1588** [Microsoft/BotBuilder#2736]
Hi ,

Emulator and Webchat control is not support multiple Blank line, can any tell how to support multiple blank lines?

I used below option but it does not support. it give only one line
<br/><br/>
"\n\n"

Example.

Hello world 

Requirement is: (2 blank line)

Hello

World

Thanks
Upendra

**Comment by nwhitmont** [comment]
@upendra1588 Are you using C# or Node SDK?

**Comment by upendra1588** [comment]
I m using C# ,

**Comment by nwhitmont** [comment]
@upendra1588 the solution is posted here: https://github.com/Microsoft/BotBuilder/issues/920#issuecomment-243938371

To use the `<br/>` tag, set your Message.text type to 'xml' and make sure to use the self-closing tag version of `<br/>` as `<br>` won't work.

**Comment by upendra1588** [comment]
@nwhitmont if i write <br/><br/> then it is considering only one line break,
