### ISSUE TITLE
[BotBuilder] Connector can't get Conversation ID

### ISSUE THREAD

**Issue by mahmoudahmedarafa** [Microsoft/BotBuilder#2738]
I am using the following code snippet from Bot Framework Tutorial in my 'Post' method:

 ```
                var userAccount = new ChannelAccount(name: "Larry", id: "@UV357341");
                var botAccount = new ChannelAccount(name: "Larry", id: "@UV357341");
                var connector = new ConnectorClient(new Uri(activity.ServiceUrl));
                var conversationId = await 
                          connector.Conversations.CreateDirectConversationAsync(botAccount, userAccount);

                IMessageActivity message_activity = Activity.CreateMessageActivity();
                message_activity.From = botAccount;
                message_activity.Recipient = userAccount;
                message_activity.Conversation = new ConversationAccount(id: conversationId.Id);
                message_activity.Text = reply;
                message_activity.Locale = "en-Us";
                await connector.Conversations.SendToConversationAsync((Activity)message_activity);
```

In line:

`var conversationId = await connector.Conversations.CreateDirectConversationAsync(botAccount, userAccount);`

the method is called and keeps running without returning an id. Any help with this issue?

**Comment by EricDahlvang** [comment]
1. CreateDirectConversationAsync actually creates a conversation.  The variable name is incorrect, it should be:
```
var conversation = await 
                         connector.Conversations.CreateDirectConversationAsync(botAccount, userAccount);
```
2. I just tried the this example: https://github.com/MicrosoftDX/botFramework-proactiveMessages/tree/master/csharp/simpleSendMessage here are the results of calling CreateDirectConversationAsync:
![image](https://cloud.githubusercontent.com/assets/11055362/25920180/ee00c1ce-3585-11e7-8640-f380f0c6d7dc.png)

What do you mean by: "keeps running without returning an id"?  Does that method hang when you call it?

**Comment by JasonSowers** [comment]
Mahmoud, are you still having a problem with this or have you found a way to resolve it?

**Comment by mahmoudahmedarafa** [comment]
`var conversationId = await connector.Conversations.CreateDirectConversationAsync(botAccount, userAccount);`

I was using Botframework Emulator and I was trying to create a 'Conversation' which was already created from the emulator unpragmatically.

```
               var userAccount = new ChannelAccount(name: "Larry", id: "@UV357341");
               var botAccount = new ChannelAccount(name: "Larry", id: "@UV357341");
               var connector = new ConnectorClient(new Uri(activity.ServiceUrl));
               var conversationId = await 
                         connector.Conversations.CreateDirectConversationAsync(botAccount, userAccount);
```

The previous code above simulates what the emulator does pragmatically.
