### ISSUE TITLE
[Telegram] Is Mention Entity supported for Telegram?

### ISSUE THREAD

**Issue by ncksol** [Microsoft/BotBuilder#2740]
## System Information (Required)

* **SDK language C#**
* **SDK version**  3.8
* **Development environment - Azure Bot Service** 
## Issue Description
I am trying to add mention entity to my reply activities as described [in this article](https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-create-messages). When I send the reply constructed with the code below I get no actual reply from the bot in the channel.

## Example Code
```
var reply = activity.CreateReply();
var replyText = "test";

var entity = new Entity();
entity.SetAs(new Mention
{
    Text = replyText,
    Mentioned = new ChannelAccount
    {
        Name = activity.From?.Name,
        Id = activity.From?.Id
    }
});

reply.Entities.Add(entity);

await Connector.Conversations.ReplyToActivityAsync(reply);
```

## Expected Behavior

This is how replies look like in Telegram when you do it as a user from UI:
http://imgur.com/pzYvV2C

**Comment by JasonSowers** [comment]
Have you been able to resolve this issue yet, or are you still having the same problem?

**Comment by ncksol** [comment]
I am still having the same problem

**Comment by ncksol** [comment]
Is there any update on this issue?

**Comment by nwhitmont** [comment]
@eanders-MS Is Mention Entity supported for Telegram?

**Comment by JasonSowers** [comment]
It is possible that `Name` and `Id` are reversed, or missing. can you check that these values are the expected values?  We have another bug in `Activity.From` that may be the reason you are experiencing this.

**Comment by ncksol** [comment]
So I decide to check if this is working few versions later. Nope still doesn't.
@JasonSowers tried switching Name and Id around - didn't help.
