### ISSUE TITLE
[FormFlow]  confirm select "No" doesn't show up choice option list

### ISSUE THREAD

**Issue by GaiaAnn** [Microsoft/BotBuilder#2742]
## System Information (Required)

* **SDK language - C# **
* **SDK version - 3.5.5.0 **
* **Development environment - localhost **

## Issue Description

I set default value in formflow.
I want to show confirm dialog without ask question. Until user choose "NO" then show option list.
This option list can go back to any question and change answer.(Example Code Case 1)
Like this picture
<img width="640" alt="2017-05-11 10 35 00" src="https://cloud.githubusercontent.com/assets/17616235/25930093/cf8b3682-3636-11e7-8ca6-ccb35102c768.png">

But When I set field active = false then option list won't show up.(Example Code Case 2)
If I answer each form question step by step and select "NO" then option list will show up.
like this:
<img width="605" alt="2017-05-11 10 56 28" src="https://cloud.githubusercontent.com/assets/17616235/25930402/93597a78-3638-11e7-8a42-7f1c5e6c1425.png">

Is it possible to do this?

## Example Code
```C#
//Case1 will show up option list and you can go back each question to change answer
return new FormBuilder<LeaveQuery>()
                        .Field(nameof(LeaveQuery.Date), active: (state) =>
                        {
                            return true;
                        })
                        .Field(nameof(LeaveQuery.Time), active: (state) =>
                        {
                            return true;
                        })
                        .Field(nameof(LeaveQuery.LeaveType), active: (state) =>
                        {
                            return true;
                        })
                        .Confirm(async (state) =>
                        {
                            Leave = CustomTime(state);
                            return new PromptAttribute($"Info :\r\n\r\nLeaveType: {state.LeaveType}\r\n\r\n" +
                                            $"Date:{ Leave.SDate.ToString("yyyy/MM/dd HH:mm")} - { Leave.EDate.ToString("yyyy/MM/dd HH:mm")}\r\n\r\n" +
                                            $"OK?" +
                                            "{||}");
                        })
                        .Message("wait...")
                        .AddRemainingFields()
                        .OnCompletion(processLeaveCheck)
                        .Build(); 
```

```C#
//Case2 Fail
return new FormBuilder<LeaveTime>()
                .Field(new FieldReflector<LeaveTime>(nameof(LeaveTime.SDate))
                    .SetActive((state) => SetFieldActive(state, nameof(LeaveTime.SDate))))
                .Field(new FieldReflector<LeaveTime>(nameof(LeaveTime.EDate))
                    .SetActive((state) => SetFieldActive(state, nameof(LeaveTime.EDate))))
                .Field(new FieldReflector<LeaveTime>(nameof(LeaveTime.Type))
                    .SetActive((state) => SetFieldActive(state, nameof(LeaveTime.Type))))

                    .Confirm(async (state) =>
                        {
                            if(CheckState(state))
                            {
                                //set default value
                                state.EDate = leavetime.EDate;
                                state.SDate = leavetime.SDate;
                                state.Type = leavetime.Type;
                            }
                            return new PromptAttribute($"* SDate：{state.SDate.ToString("yyyy/MM/dd HH:mm")}\r\n" +
                            $"* EDate：{state.EDate.ToString("yyyy/MM/dd HH:mm")}" +
                            $"\r\n* LeaveType：{GetLeaveTypeName(state.Type)}\r\n OK?" +
                            "{||}");
                        })
                        .Message("wait...")
                        .AddRemainingFields()
                        .OnCompletion(processLeaveCheck)
                        .Build();
```

## Expected Behavior
<img width="406" alt="2017-05-11 11 07 23" src="https://cloud.githubusercontent.com/assets/17616235/25930664/0d451af8-363a-11e7-8ff0-acf24de89242.png">

## Actual Results
<img width="605" alt="2017-05-11 10 56 28" src="https://cloud.githubusercontent.com/assets/17616235/25930402/93597a78-3638-11e7-8a42-7f1c5e6c1425.png">

Hope anyone can help me Thanks!

**Comment by JasonSowers** [comment]
Hello, Have you been able to resolve this issue on your own?

**Comment by GaiaAnn** [comment]
Hi I think FormFlow can’t do this.. do you have same problem?

**Comment by PawelCiucias** [comment]
I had the same issue but i solved it by creating a field to track whether the form is being filled out vs confirmed, then in the condition parameter of the confirm function i set the field to true. 

        using Microsoft.Bot.Builder.FormFlow;
        using pc.BudapestHotel.Interfaces;
        using System;
        using System.Collections.Generic;
        using System.Linq;
        using System.Web;
        
        namespace pc.BudapestHotel.Forms
        {
            [Serializable]
            class RoomReservationForm : IRoomReservation {
            bool finalConfirmation = false; //HERE IS THE Magic
            #region IRoomReservation 
            public string FullName { get; set; }
            public DateTime? CheckInDate { get; set; }
            public DateTime? CheckOutDate { get; set; }
            public RoomType RoomType { get; set; }
            public int Occupency { get; set; }
            public List<Extras> Extras { get; set; }
            public bool VIPMembership { get; set; }
            #endregion

            #region Constructors
            public RoomReservationForm(params object[] values) {
                foreach (var v in values) {
                    int number;
                    if (v is IDateRange)  {
                        var dateRange = v as IDateRange;
                        this.CheckInDate = dateRange.StartDateTime;
                        this.CheckOutDate = dateRange.EndDateTime;
                    }
                    else if (int.TryParse(v.ToString(), out number))
                    {
                        this.Occupency = number;
                    }
                }
            }
            public RoomReservationForm(IDateRange dateRange)
            {
                this.CheckInDate = dateRange.StartDateTime;
                this.CheckOutDate = dateRange.EndDateTime;
            }

            public RoomReservationForm(IDateRange dateRange, int occupency) : this(dateRange)
            {
                this.Occupency = occupency;
            }
            #endregion

            public static IForm<RoomReservationForm> BuildForm()
                => new FormBuilder<RoomReservationForm>()
                .Message("Let me help you book a room")
                .Field(nameof(FullName))
                .Field(nameof(CheckInDate), state => !state.CheckInDate.HasValue || state.finalConfirmation)
                .Field(nameof(CheckOutDate), state => !state.CheckOutDate.HasValue || state.finalConfirmation)
                .Field(nameof(Occupency), state => state.Occupency == 0 || state.finalConfirmation)
                .AddRemainingFields()
                .Confirm(
                    prompt: "are the following valid?{*}{||}",
                    condition: state => state.finalConfirmation = true,
                    dependencies: typeof(IRoomReservation).GetProperties().Select(p => p.Name))
                .Build();
        }
    }

hope that helps
