### ISSUE TITLE
[BotBuilder] Problem in running CSharp Samples

### ISSUE THREAD

**Issue by mahmoudahmedarafa** [Microsoft/BotBuilder#2745]
I tried running a sample from [CSharp Samples](https://github.com/Microsoft/BotBuilder/tree/master/CSharp/Samples). I got the following [error](https://postimg.org/image/6wpfol22t/).

So how should I fix this?

**Comment by JasonSowers** [comment]
Mahmoud, were you able to figure out the problem or would you still like some help?

**Comment by mahmoudahmedarafa** [comment]
Error was fixed by updating VS, packages, and emulator to the latest version.
