### ISSUE TITLE
MMS: Is there support of Media with SMS ?

### ISSUE THREAD

**Issue by JpEncausse** [Microsoft/BotBuilder#275]
Phone can send SMS but also MMS (with images) should it work ? My bot do not receive the message

**Comment by tomlm** [comment]
Yes image should work.

Are you adding them as attachments?

**Comment by Stevenic** [comment]
The other thing is you need to make sure that your Twilio account has MMS enabled. Not all phone numbers support MMS and if I remember it's off by default.

**Comment by JpEncausse** [comment]
Argsss my bad ! You're right
No MMS using Twilio with French phone number

**Comment by Stevenic** [comment]
I know. Kind of sucks :(
