### ISSUE TITLE
[Bug] Bad extension methods of IMessageActivity - cause exception when called

### ISSUE THREAD

**Issue by tompaana** [Microsoft/BotBuilder#2753]
## System Information (Required)

C#; Version 3.8.0

## Issue Description

Methods `HasContent` and `GetMentions` of `IMessageActivity` cause `StackOverflowException`, because "An extension method with the same name and signature as an instance method will not be called." In other words, the extensions methods (with the same name) are never called. Instead the method call gets stuck in a loop.

## Steps to Reproduce

1. Call `IMessageActivity.HasContent()` or  `IMessageActivity.GetMentions()`

## Expected Behavior

No exception.

## Actual Results

`StackOverflowException` thrown.

**Comment by msft-shahins** [comment]
@brandonh-msft can you take a look? It seems that desired extension methods are not being resolved and as a result HasContent and GetMentions will end up in an infinite loop causing the `StackOverflowException`.

**Comment by msft-shahins** [comment]
builder 3.8.1 should fix this issue.

**Comment by nwhitmont** [comment]
Thanks! @msft-shahins
