### ISSUE TITLE
[Feature Request] Channel for living avatars

### ISSUE THREAD

**Issue by bgarr33434** [Microsoft/BotBuilder#2755]
We have multiple customers that have asked us to add a living avatar to their SILVIA AI driven chatbot, which is handled by the MSFT Bot Framework.

**Comment by nwhitmont** [comment]
@bgarr33434 
1. Are you using C# or Node SDK?
2. Please provide more detail about your request. For example, what is a "living avatar"? Can you include a screenshot or link to information about this?

**Comment by bgarr33434** [comment]
Thanks, we are a MSFT shop, so C#.  Just browsing the web, I see multiple
software companies that allow you to create avatars.  Certainly Unity3D,
but then that rules out an HTML5 website for the bot.  But really, being
able to have any avatar connected to the Bot Framework would be a huge hit,
I think.  By living, I mean lip synch.  Thanks.

Regards,

Brian Garr, COO
Cognitive Code
561.271.4750
@garrbrian

click here to set up a call/meeting http://doodle.com/brianlgarr

**Comment by nwhitmont** [comment]
@bgarr33434 you mean like [Gravatar](https://en.gravatar.com/) for individual users?

**Comment by bgarr33434** [comment]
I found one that looks promising.  Botlibre.com.  I can actually send their
bot right to my ai through a proxy, but it would be better if there was a
direct connect, like with Facebook and Slack.

Regards,

Brian Garr, COO
Cognitive Code
561.271.4750
@garrbrian

click here to set up a call/meeting http://doodle.com/brianlgarr

**Comment by bgarr33434** [comment]
Neils, here is an example that I created on BotLibre.  It is a bot
framework, like  MSFT Bot Framework, but they offer avatars as well.
http://www.botlibre.com/chat?id=17020065&embedded=true&application=118737051139544836

Note that the avatars are pretty rudimentary, and the lip synching is
awful, but you get the idea.  We have clients waiting for this capability
with our bots from MSFT bot framework.

Regards,

Brian Garr, COO
Cognitive Code
561.271.4750
@garrbrian

click here to set up a call/meeting http://doodle.com/brianlgarr

**Comment by haxhilajqi** [comment]
Hello Guys,

Any update about integration of avatar movement (lip sync) to Bot Framework!

Regards
Haxhi Lajqi

**Comment by JasonSowers** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
