### ISSUE TITLE
[Direct Line] Why isn't the source for Microsoft.Bot.Connector.DirectLine in this repo (or another public repo)?

### ISSUE THREAD

**Issue by colbylwilliams** [Microsoft/BotBuilder#2756]
Curious why the source for the Microsoft.Bot.Connector.DirectLine nuget package isn't public?

I understand it's mostly generated code from the swagger file, as @dandriscoll mentions in issue #2309, but I did take the time to recreate the direct line client via the swagger file and found that Bot.Connector.DirectLine has a good bit of code added on top of what's generated by autorest. 

The source would be useful for developers trying to add functionality, helpers, ect. or are trying to use a feature not yet included in the public NuGet package (like myself with AnimationCards a few weeks ago).

Is there a reason it's not public?

**Comment by nwhitmont** [comment]
@colbylwilliams Perhaps you are looking for [Microsoft/BotFramework-DirectLineJS](https://github.com/Microsoft/BotFramework-DirectLineJS)?

**Comment by colbylwilliams** [comment]
@nwhitmont No, I don't think so.  I'm looking for the [Microsoft.Bot.Connector.DirectLine NuGet package][0].  It looks to be made up mostly of code generated by autorest.

[0]:https://www.nuget.org/packages/Microsoft.Bot.Connector.DirectLine

**Comment by nwhitmont** [comment]
@colbylwilliams No it's not open source - it is the swagger.json file run through autorest.

**Comment by colbylwilliams** [comment]
@nwhitmont  I know that it's not open source, and that it's mostly  the swagger file run through autorest.  But as I mentioned in my earlier comments that's not all it is.  There are several interfaces, extension message, in him's, etc. added on top of what autorest generates. 

My question was **why** is it not open source? And if that question can be answered, who owns it?

**Comment by colbylwilliams** [comment]
@nwhitmont Not sure this issue should've been closed as you didn't answer my question, and at the very least it's a feature request.  I'm a Microsoft employee as well so even if it's internal - please let me know who owns that nuget package so I can work with them.

**Comment by shahsaurabh0605** [comment]
How does Microsoft.Bot.Connector.DirectLine use `from` attribute in message activity? I cannot post an activity to the bot if the `from` attribute is not supplied or userId is not supplied.

**Comment by krisrok** [comment]
is the source still closed?

**Comment by EricDahlvang** [comment]
@krisrok we are in the process of open sourcing this library.  You can find the latest source here: https://github.com/microsoft/BotFramework-DirectLine-DotNet  but, this version has not been released to nuget just yet.  But, you can find the latest version here: https://botbuilder.myget.org/feed/experimental/package/nuget/Microsoft.Bot.Connector.DirectLine
