### ISSUE TITLE
[Question] action?library:dialog payload is broken 

### ISSUE THREAD

**Issue by amitbend** [Microsoft/BotBuilder#2758]
## Pre-flight checklist

- [ x ] I have [searched the existing issues](https://github.com/Microsoft/BotBuilder/issues?utf8=%E2%9C%93&q=is%3Aissue) before logging a new one.
---------------------------
## System Information (Required)

* *Node**
* **SDK version 3.8.1**
* **Development environment - localhost **
* **Node.js 6.10.3  npm version 3.10.10 **

## Issue Description

I'm setting up quick replies using the new  `        msg.suggestedActions(
            builder.SuggestedActions.create(session,arr)
        )`
when `arr` is an array of:
  `builder.CardAction.postBack(session,'action?library:dialog' , 'title')`
which supposed to direct to a specific dialog in a library.

when i use it, it does not being redirected to the correct dialog, but to the root dialog

i tried also:
- using `imback` instead

- use it with `get started` facebook button - failed as well 

-  use it with a simple action with `beginDialogAction` - failed

**Comment by amitbend** [comment]
Tested it once again and i can confirm this issue appeared since  v3.8.0 (works fine on v3.7.0)

**Comment by nwhitmont** [comment]
@amitbend can you post your complete bot code that reproduces this issue? thx

**Comment by amitbend** [comment]
@nwhitmont this is a very simplified  version 

**on index.js**
`bot.library(require('./library1'));`

`bot.dialog('/',[(session,args,next)=>{
     let msg = new builder.Message(session).text(["main dialog"])
     msg.addAttachment(new builder.HeroCard(session).buttons([builder.CardAction.imBack(session, "action?library:dialog", "➡")]))
    session.endDialog(msg);
}])`


**on library1.js**

`const library = new builder.Library('library');`

    library.dialog('dialog', [
     (session, args, next) =>{
        session.send('simple dialog here')
     }])

`module.exports = library;`

`
clicking on the imBack button does not redirect to the dialog in the library since v3.8.0

the same outcome can be also achieved by defining a `get_started` button  with the same payload `action?library:dialog`

**Comment by nwhitmont** [comment]
@amitbend Here is an example that demonstrates how to use the Library feature to invoke a dialog: https://github.com/Microsoft/BotBuilder/tree/master/Node/examples/basics-libraries

For example, in `localeTools.js` [L33](https://github.com/Microsoft/BotBuilder/blob/master/Node/examples/basics-libraries/localeTools.js#L33) there is an example starting the dialog by name:
```javascript
exports.chooseLocale = function (session, options) {
    // Start dialog in libraries namespace
    session.beginDialog('localeTools:chooseLocale', options || {});
}
```

I'm not sure why you are using `action?library:dialog` instead of just `library:dialog` as shown in the example code.  

Where did you find the documentation or example that describes prepending `action&` to `library:dialog`?

**Comment by Stevenic** [comment]
@amitbend For the action bindings that use the "action?" syntax you need to add a "named action" that matches your binding. So in your example library this should work:

```
 const library = new builder.Library('library');

    library.dialog('dialog', [
     (session, args, next) =>{
        session.send('simple dialog here')
     }]);
     library.beginDialogAction('library:dialog', 'dialog');

module.exports = library;
```

That should let you push the dialog onto the end of the stack using `action?library:dialog`. With that said we've started recommending that people use `triggerAction()` instead, paired with a simple imBack or postBack. So:

```
 const library = new builder.Library('library');

    library.dialog('dialog', [
     (session, args, next) =>{
        session.send('simple dialog here')
     }]).triggerAction({ matches: /^main dialog/I });

module.exports = library;
```

This would let you trigger the dialog using `builder.CardAction.imBack(session, "main dialog", "➡")`

**Comment by nwhitmont** [comment]
thanks for the example! @Stevenic

**Comment by amitbend** [comment]
Thanks for the answers @Stevenic  and @nwhitmont 

So first of all @nwhitmont the most obvious situation to use it is from Persistent menu, using the method you've described requires me to build many dummy dialogs at the root of the bot to redirect to the libraries, and it doesn't seems like a good practice.

I can't remember where i saw exactly an example using this, but In the docs it is written 
`Can be used anywhere a postBack is valid. You may also statically bind a button to an action for something like Facebooks Persistent Menus. The payload for the button should be action?<action> for actions without data or action?<action>=<data> for actions with data.`
which in case of a bot using libraries it makes sense `library:action` will be possible.

@Stevenic 
1) The first example seems like a good enough solution, but it doesn't work in the global scope - so it is not relevant to a persistent menu for example
2) Using `triggerAction` is my workaround right now, but this is also a problematic solution, as it is not a 1:1 routing and also can be very problematic when using a recognizer like LUIS (am i correct?)

Will it be possible to restore the option to route this way?
For 1:1 routing is seems to me the best and the most efficient solution.

What do you think?

**Comment by Stevenic** [comment]
@amitbend I'll have to try to reproduce why the action binding isn't working but in the meantime you can create a `triggerAction()` with a reg ex that looks for something like `trigger=library:dialog` which should achieve exactly the same thing.

**Comment by amitbend** [comment]
@nwhitmont @Stevenic is it fixed?

**Comment by amitbend** [comment]
@nwhitmont @Stevenic any update?
The issue was closed without specifying a reason.

**Comment by nwhitmont** [comment]
Not a bug

**Comment by amitbend** [comment]
@Stevenic Suggested this solution, but it seems to be a bug.

` const library = new builder.Library('library');

    library.dialog('dialog', [
     (session, args, next) =>{
        session.send('simple dialog here')
     }]);
     library.beginDialogAction('library:dialog', 'dialog');

module.exports = library;`

So currently it is not possible to start an action in a Library(except regex with `triggerAction`) , i believe this is a **bug** @nwhitmont

**Comment by fms-santos** [comment]
> @amitbend I'll have to try to reproduce why the action binding isn't working but in the meantime you can create a `triggerAction()` with a reg ex that looks for something like `trigger=library:dialog` which should achieve exactly the same thing.

Hi @Stevenic, so I'm trying to move to triggerAction instead of the beginDialogAction() but I can't seem to find the right regex pattern to match the button click ``action?loadreference-pt=[Invoice Number]".
and the equivalent to:

`` bot.triggerAction('loadreference-pt', '/loadreference-pt');  `` 

I've tried:

`` .triggerAction({
        matches:  /action?loadreference.pt=\w+/
    }); `` 
But it's not working.
Could you help me out?
