### ISSUE TITLE
.NET Core 2 Preview - TypeLoadException about AuthenticationOptions (changes from Microsoft.AspNetCore.Authentication 1.1.0.0 to 2.0.0.0)

### ISSUE THREAD

**Issue by luizcarlosfaria** [Microsoft/BotBuilder#2760]
## System Information (Required)

* **SDK language: C#**
* **SDK version: 3.6.0-alpha**
* **Development environment - localhost**
* **Runtime:  .NET Core 2.0.0-preview1-005977**

## Issue Description

The assembly _**Microsoft.Bot.Connector.AspNetCore, Version=3.6.0.0**_ has a reference to _**Microsoft.AspNetCore.Authentication, Version=1.1.0.0**_. 
 At new version _**Microsoft.AspNetCore.Authentication, Version=2.0.0.0**_ the class _**Microsoft.AspNetCore.Builder.AuthenticationOptions**_ does not exists anymore.

## Example Code
```
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
{
	if (env.IsDevelopment())
	{
		app.UseDeveloperExceptionPage();
	}

	ICredentialProvider botframeworkCredentialProvider = app.ApplicationServices.GetRequiredService<ICredentialProvider>();
	app.UseBotAuthentication(botframeworkCredentialProvider);
	
	app.UseMvc();
}
```
TypeLoadException  exception occured when call UseBotAuthentication extension.

```
System.TypeLoadException occurred
  HResult=0x80131522
  Message=Could not load type 'Microsoft.AspNetCore.Builder.AuthenticationOptions' from assembly 'Microsoft.AspNetCore.Authentication, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at Microsoft.Bot.Connector.BotAuthenticationAppBuilderExtensions.UseBotAuthentication(IApplicationBuilder app, ICredentialProvider credentialProvider)
   at Ebix.Wbot.API.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) in C:\_dev\WDEV\wbot\src2\Ebix.Wbot.API\Startup.cs:line 39
```

It's occurs because _**Microsoft.Bot.Connector.BotAuthenticationAppBuilderExtensions, Version=3.6.0.0**_ have the extension method `public static IApplicationBuilder UseBotAuthentication(this IApplicationBuilder app, ICredentialProvider credentialProvider)` try create an _**Microsoft.Bot.Connector.BotAuthenticationOptions, Microsoft.Bot.Connector.AspNetCore, Version=3.6.0.0**_ and this type inherits _**Microsoft.AspNetCore.Builder.AuthenticationOptions,
 Microsoft.AspNetCore.Authentication, 1.1.0.0**_, inexistent type on _**2.0.0.0**_ of  same assembly.

**Comment by nwhitmont** [comment]
@luizcarlosfaria Can you upgrade [BotBuilder nuget package](https://www.nuget.org/packages/Microsoft.Bot.Builder/) to the latest version (v3.8.x) and let me know if you are still experiencing the issue?

**Comment by luizcarlosfaria** [comment]
Trying to install this package, i have received a issue about System.IdentityModel.Tokens.Jwt version:
Project uses (>= 5.1.3) , Referenced Library (Microsoft.Bot.Builder) uses 4.0.4.403061554.

This occurs on same environment.
```
Version conflict detected for System.IdentityModel.Tokens.Jwt. 
 Ebix.Wbot.API (>= 1.0.0) 
	-> Microsoft.AspNetCore.All (>= 2.0.0-preview1-final) 
		-> Microsoft.AspNetCore.Identity.Service.Abstractions (>= 1.0.0-preview1-final) 
			-> Microsoft.IdentityModel.Protocols.OpenIdConnect (>= 2.1.3) 
				-> Microsoft.IdentityModel.Protocols (>= 2.1.3) 
					-> System.IdentityModel.Tokens.Jwt (>= 5.1.3) 
 Ebix.Wbot.API (>= 1.0.0) 
	-> Ebix.Wbot.Architecture (>= 1.0.0) 
		-> Microsoft.Bot.Builder (>= 3.8.0)
			-> System.IdentityModel.Tokens.Jwt (>= 4.0.4.403061554).	
```

**Comment by Maarten88** [comment]
I migrated the BotConnector.AspNetCore authentication handler to 2.0:
https://gist.github.com/Maarten88/9aacc25368601a2d65b417dc90945440

Use it like this:

    services
        .AddAuthentication(...)
        .AddBotAuthentication(
                    BotAuthenticationSchemeOptions.AuthenticationScheme, // set to "Bearer"
                    configuration["MicrosoftAppCredentials:MicrosoftAppId"],
                    configuration["MicrosoftAppCredentials:MicrosoftAppPassword"]
        )

Limitation is that the Scheme must be set to "Bearer", if you have other AddJwtBearer authentication then set those to another scheme.
https://gist.github.com/Maarten88/9aacc25368601a2d65b417dc90945440
