### ISSUE TITLE
[Feature Request] IBotDataBag getAll

### ISSUE THREAD

**Issue by jerrak0s** [Microsoft/BotBuilder#2762]
* **SDK language (C#/Node)**

## Issue Description

My suggestion is a function to get all userData as a List when this is needed.
[IBotDataBag](https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Microsoft.Bot.Builder/ConnectorEx/IBotDataBag.cs)

## Expected Behavior

Get all userData with one function as a List.

**Comment by nwhitmont** [comment]
@jerrak0s are you using .NET or Node SDK?

**Comment by jerrak0s** [comment]
@nwhitmont .NET

**Comment by JasonSowers** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
