### ISSUE TITLE
Bot builder SDK C# does not support the new datetimeV2 time in LUIS entities in (builtin.datetimeV2.timerange)

### ISSUE THREAD

**Issue by m-ehxan** [Microsoft/BotBuilder#2764]
Bot builder SDK version 3.5.9 does not support the new datetimeV2. when are we expecting next relase.
I want to extract start and end time values in following JSON: 

`{
      "entity": "from 4 pm to 6 pm",
      "type": "builtin.datetimeV2.timerange",
      "startIndex": 69,
      "endIndex": 85,
      "resolution": {
        "values": [
          {
            "timex": "(T16,T18,PT2H)",
            "type": "timerange",
            "start": "16:00:00",
            "end": "18:00:00"
          }
        ]
      }
    },
`

**Comment by nwhitmont** [comment]
@m-ehxan Can you upgrade BotBuilder to the current version (v3.8.x) and let me know if you are still experiencing the issue?

**Comment by m-ehxan** [comment]
@nwhitmont  I have update the nuget package to **(v3.8.0)** and i still can not access the start and end time values. In SDK **Resolution** is defined as `public IDictionary<string, object> Resolution { get; set; }` and there is no way to directly access the values of  **timex** , **type** , **start** or **end** keys

**Comment by ejadib** [comment]
Just for the record, this is also discussed at https://stackoverflow.com/questions/44552030/json-serializer-error-with-botframework-an-luis and https://stackoverflow.com/questions/44544059/problems-mapping-in-luis-entities-into-form-flow

**Comment by ejadib** [comment]
I just completed the work to add support for the new entity. Tomorrow I will create a PR for this.

**Comment by tellarin** [comment]
@stevengum97, can you close this? :)

**Comment by stevengum97** [comment]
Thank you @tellarin and @JasonSowers!

**Comment by JasonSowers** [comment]
You're welcome @stevengum97!
