### ISSUE TITLE
[BotBuilder] can't view bot reply on emulator

### ISSUE THREAD

**Issue by mahmoudahmedarafa** [Microsoft/BotBuilder#2765]
I could get a reply from the bot, yet I get the following exception:

![capture](https://cloud.githubusercontent.com/assets/22199398/26050735/108ac54a-3960-11e7-82cd-ee3bdebf9c64.PNG)

Any help?

**Comment by nwhitmont** [comment]
@mahmoudahmedarafa are you using .NET or Node SDK for BotBuilder?

**Comment by mahmoudahmedarafa** [comment]
@nwhitmont I solved problem by updating my VS to VS 2017.
