### ISSUE TITLE
[Facebook Messenger] How can I get Referral params?

### ISSUE THREAD

**Issue by trantung2704** [Microsoft/BotBuilder#2766]
Hi 

I want to init some data for facebook user base on link they use to access my bot. I found this article:
https://developers.facebook.com/docs/messenger-platform/referral-params
but I dont know how to get referral params from bot framework (C#). My purpose to set user data base on link like this: https://m.me/{BOT_ID}?ref={SOME_MESSAGE}

Any help will be appreciated.

Thanks

**Comment by nrobert** [comment]
Hi,

I successfully tried to do the same.
Weird point first: note that the value is not at the same place if you previously talk to the bot or not...

So I'm doing the following:
- defined a `FacebookChannelData` class, where RefParameter is the parameter you want, in order to get these fields from the json message received

```C#
public class FacebookChannelData
{
    [JsonProperty("Sender")]
    public Sender Sender { get; set; }
    
    [JsonProperty("Recipient")]
    public Recipient Recipient { get; set; }

    [JsonProperty("Timestamp")]
    public long Timestamp { get; set; }

    [JsonProperty("Postback")]
    public Postback Postback { get; set; }

    [JsonProperty("Referral")]
    public Referral Referral { get; set; }

    public string RefParameter
    {
        get
        {
            string val = "";

            if (Postback != null && Postback.Referral != null && !String.IsNullOrWhiteSpace(Postback.Referral.Reference))
            {
                val = Postback.Referral.Reference;
            }
            else if (Referral != null && !String.IsNullOrWhiteSpace(Referral.Reference))
            {
                val = Referral.Reference;
            }
            return val;
        }
    }
}

public class Recipient
{
    [JsonProperty("Id")]
    public string Id { get; set; }
    [JsonProperty("Name")]
    public string Name { get; set; }
}

public class Sender
{
    [JsonProperty("Id")]
    public string Id { get; set; }

    [JsonProperty("Name")]
    public string Name { get; set; }
}

public class Postback
{
    [JsonProperty("Payload")]
    public string Payload { get; set; }

    [JsonProperty("Referral")]
    public Referral Referral { get; set; }
}

    public class Referral
    {
        [JsonProperty("Ref")]
        public string Reference { get; set; }

        [JsonProperty("Source")]
        public string Source { get; set; }

        [JsonProperty("Type")]
        public string Type { get; set; }
}
```

- so getting the ChannelData of the facebook incoming message is like:
```C#
if (incomingMessage.TryGetChannelData(out FacebookChannelData channelDataInfo))
{
    return channelDataInfo.RefParameter;
}
else
{
    return String.Empty;
}
```

As you can see, the interesting value is the field "Postback.Referral.Reference" OR "Referral.Reference" in this ChannelData (given the fact that it is a new conversation or not), so I'm checking if the 1st one is null and trying to get the 2nd one in that case

Hope it will be helpful.
Nicolas

PS : don't forget to set a Start Button on your Messenger bot settings.

**Comment by trantung2704** [comment]
You made my day :). Thank you so much!

**Comment by nrobert** [comment]
You're welcome.
Maybe you can close this issue?

**Comment by res63661** [comment]
Any dependable way to get referring data from skype or other channels?  I really need it.
Also @nrobert you mentioned "PS : don't forget to set a Start Button on your Messenger bot settings." 
 Can you elaborate?  Is this to workaround the infuriating lack of ability to fire off an initial greeting in most channels? - thx

**Comment by nrobert** [comment]
@res63661 FB messenger & webchat have this ability but I don't know for other channels.
There may be solutions, but it depends on your use case.

And for my mention about adding the start button, it is here to remind people that they get this referral on Facebook Messenger only if they have set this Start Button on Messenger side. This referral process and the button are specific to this channel, and yes it is a proper way to start a conversation for a user: he just has to click, doesn't have to think about what he should write..

For the lack of ability to fire off an initial greeting, it is also a security problem (to avoid bot spam...), but it is still possible in some channels (at least email, SMS, Slack)
