### ISSUE TITLE
Calling Session.endConversation with a message, sometimes results in the message not being delivered to the client. This behaviour appears to be sporadic in nature.

### ISSUE THREAD

**Issue by kev-slater-mhr** [Microsoft/BotBuilder#2767]
#botframework Node.js

Version Information

Node.js v6.3.1
botbuilder v3.7.0

Description of Issue

Calling Session.endConversation with a message, sometimes results in the message not being delivered to the client. This behaviour appears to be sporadic in nature.

Diagnosis

The issue appears to be caused in Session.sendBatch whereby the current outstanding batched messages are referenced by a local variable prior to being cleared down and before this.options.onSave() gets called. This has the ramification that the callback to this.options.onSave will be oblivious to any messages added to the batch collection during the time frame for onSave to complete and the callback to be executed (bearing in mind Nodes single threaded nature), because it only considers the messages referenced by the local variable.

BotBuilder/Node/core/lib/Session.js

```
…
Session.prototype.sendBatch = function (done) {
  var _this = this;
  this.logger.log(this.dialogStack(), 'Session.sendBatch() sending ' + this.batch.length + ' message(s)');
        
  if (this.sendingBatch) {
    return;
  }
  
  if (this.batchTimer) {
    clearTimeout(this.batchTimer);
    this.batchTimer = null;
  }
  this.batchTimer = null;
  var batch = this.batch; 
  this.batch = [];
  this.batchStarted = false;
  this.sendingBatch = true;
  var cur = this.curDialog();
  if (cur) {
    cur.state = this.dialogData;
  }
  this.onSave(function (err) {
    if (!err) {
      _this.onSend(batch, function (err, addresses) {
        _this.onFinishBatch(function () {
          if (_this.batchStarted) {
            _this.startBatch();
          }
…
```

Solution

Don’t de-reference current outstanding batched messages until within logical thread of execution that requires it, so no messages get missed. i.e. something on the lines of:

```
…
Session.prototype.sendBatch = function (done) {
  var _this = this;
  this.logger.log(this.dialogStack(), 'Session.sendBatch() sending ' + this.batch.length + ' message(s)');
        
  if (this.sendingBatch) {
    return;
  }
  
  if (this.batchTimer) {
    clearTimeout(this.batchTimer);
    this.batchTimer = null;
  }
  this.batchTimer = null;
  this.batchStarted = false;
  this.sendingBatch = true;
  var cur = this.curDialog();
  if (cur) {
    cur.state = this.dialogData;
  }
  this.onSave(function (err) {
    if (!err) {
      var batch = _this.batch; 
      _this.batch = [];
      _this.onSend(batch, function (err, addresses) {
        _this.onFinishBatch(function () {
          if (_this.batchStarted) {
            _this.startBatch();
          }
…
```

**Comment by nwhitmont** [comment]
@kev-slater-mhr Can you upgrade botbuilder to v3.8.1 and let me know if you still see the issue? Thx

**Comment by kev-slater-mhr** [comment]
> _"The reason the code saves off the batch of messages before calling onSave() is to essentially commit the batch. Any new messages that come in after the sendBatch() call should land in the next batch."_

And there lies the crux of the problem. We’re dealing with the end of a conversation so no other messages after the last are going to be put forward to the batch, so that final message is lost in the ether.

**Comment by kev-slater-mhr** [comment]
...& thank you both for the quick response! I'll hold off re-testing until the fix is pushed.

**Comment by Stevenic** [comment]
@kev-slater-mhr could you install 3.8.2 and let us know if that resolves the issue?

**Comment by kev-slater-mhr** [comment]
I've tested under 3.8.2 (Direct Line [React Native Android Client], Microsoft Teams, Skype, Slack & Web Chat) and can confirm its fixed the issue.

Thank you for the quick and speedy response + all your help on the matter.
