### ISSUE TITLE
[.NET SDK] Herocard bug - not responding always 

### ISSUE THREAD

**Issue by jerrak0s** [Microsoft/BotBuilder#2769]
## System Information (Required)

* **SDK language (C#)**
* **Development environment -Azure Bot Service**

## Issue Description

I have built a bot and it displays a herocard as a response to a command. I have noticed that if I try to send the command in a new conversation with the bot, the bot does not respond with an answer, but if I send another command first, then the bot will answer with the HeroCard.

## Code
```
List<CardAction> list = new List<CardAction>();
 list.Add(new CardAction { Title = "help", Type = ActionTypes.ImBack, Value = "help" });
 list.Add(new CardAction { Title = "commands", Type = ActionTypes.ImBack, Value = "commands" });
HeroCard hero = new HeroCard();
hero.Title = "Hello";
hero.Text = "text";
hero.Buttons = list;
var msg = ctx.MakeMessage();
msg.Attachments.Add(hero.ToAttachment());
await ctx.PostAsync(msg);
```

## Example

Herocard response --> Hello
Normal response --> Goodbye

If i send first hello and then goodbye, the bot will answer only to the goodbye function. If I send first goodbye and then hello, then the bot will answer as normal both functions.

## Steps to Reproduce
1. Send a herocard response right after the first message of the user.

## Actual Results

There was an error sending this message to your bot: HTTP status code InternalServerError

**Comment by nwhitmont** [comment]
@jerrak0s Can you post the code that reproduces this issue?

**Comment by nwhitmont** [comment]
@jerrak0s What version of BotBuidler nuget package are using? Current version is 3.8.0.

**Comment by jerrak0s** [comment]
@nwhitmont v3.5.5

**Comment by msft-shahins** [comment]
@jerrak0s can you attach debugger and debug your bot? Based on your report, it seems that your bot code is hitting an exception and you see the `internal server error`. Let us know if this is an exception thrown by SDK.

**Comment by jerrak0s** [comment]
@msft-shahins in skype i get this reponse 	
`There was an error completing this request due to an internal channel failure.`

**Comment by EricDahlvang** [comment]
@jerrak0s Are you still experiencing this problem?  Please share more of your bot's code.  It seems there is an issue inside the bot itself.

**Comment by jerrak0s** [comment]
@EricDahlvang I tried the bot again today. 

> There was an error completing this request due to an internal channel failure.

![capture](https://user-images.githubusercontent.com/3514710/28913668-863935c2-7841-11e7-8755-96255c567955.PNG)

**Comment by EricDahlvang** [comment]
@jerrak0s  Please share the code for the bot.

**Comment by JasonSowers** [comment]
please reopen this if needed
