### ISSUE TITLE
Select choice from prompt by text input

### ISSUE THREAD

**Issue by carloscba** [Microsoft/BotBuilder#2772]
## System Information

* SDK Platform: Node
* SDK Version: 3.8
* Development Environment: localhost

## Issue Description

We found that many users don't click on button of Prompts.choice and writes the text of label. When users write with accents don´t work fine.

## Example Code

```javascript
bot.dialog('/', [
    function (session) {
        let options = {
            listStyle : builder.ListStyle['button'],
        };
        builder.Prompts.choice(session, '¿Qué quieres hacer? Presiona el botón de la opción que necesites.',
            [
                'Sí',
                'No',
                'Dónde'
            ], options);
    },
    function (session, results) {
        session.send('Option selected: '+ results.response.index)
    },
]);
```

## Steps to Reproduce
1. Run previous code
2. Don't click option and write label of button without accent ("si" , "donde").

## Expected Behavior

Continue flow with option selected

## Actual Results

Don´t recognize option and retry prompt

**Comment by nwhitmont** [comment]
@carloscba I made a small update to your code it's working fine for me in the emulator.

```javascript
bot.dialog('spanish_choice_prompt', [
    function (session) {
        let options = {
            listStyle : builder.ListStyle['button'],
        };
        builder.Prompts.choice(session, '¿Qué quieres hacer? Presiona el botón de la opción que necesites.',
            [
                'Sí',
                'No',
                'Dónde'
            ], options);
    },
    function (session, results) {
        session.send('Option selected: '+ results.response.entity);
        session.endDialog();
    }
]);
```
Here you can see it working correctly:
<img width="1036" alt="screen shot 2017-05-15 at 4 43 33 pm" src="https://cloud.githubusercontent.com/assets/3075047/26084052/20c9cfd6-398e-11e7-8739-2cc8aea8efd9.png">
<img width="1076" alt="screen shot 2017-05-15 at 4 43 10 pm" src="https://cloud.githubusercontent.com/assets/3075047/26084053/20ccf170-398e-11e7-8270-274f86c166b7.png">
<img width="1033" alt="screen shot 2017-05-15 at 4 42 46 pm" src="https://cloud.githubusercontent.com/assets/3075047/26084051/20c53bf6-398e-11e7-942d-e81faac6b22c.png">

**Comment by carloscba** [comment]
@nwhitmont I am sorry for my mistake on description. The issue occurred when user write with accent.

"si" != "sí"

in this case don't work fine

**Comment by carloscba** [comment]
I found a little solution and close this issue. 

Thank for your help @nwhitmont
