### ISSUE TITLE
[MS Teams] Bot no longer works after upgrading Bot.Builder from version 3.5.5 to 3.8.0

### ISSUE THREAD

**Issue by dreijer** [Microsoft/BotBuilder#2773]
I posted this on the Bot Framework DL and was requested to create an issue here for tracking:

## System Information (Required)

* SDK Pletform: .NET
* SDK Version: 3.8.0
* Development Environment: Azure App Service

## Issue Description

I just upgraded the Microsoft.Bot.Builder .NET package for my MS Teams bot from version 3.5.5 to 3.8.0 and now I can no longer communicate with my bot through Teams. No messages ever make it to the message handler in the bot, nor does any reply ever show up in Teams.

I can send messages to the bot just fine through the Emulator, so I’m not sure what changed.

**Comment by nwhitmont** [comment]
@dreijer Thanks for reporting this issue.  We are investigating.

**Comment by msft-shahins** [comment]
@dreijer can you share your bot id? I cannot repro this issue using bot.builder 3.8 and bot.builder 3.8.1.

**Comment by dreijer** [comment]
@msft-shahins Here you go: 28321538-71cf-4a9c-8b5b-dc90e0e0fd3a

**Comment by dreijer** [comment]
For what it's worth, I just upgraded to 3.8.1 and now I can talk to the bot through Teams again.

**Comment by nwhitmont** [comment]
@dreijer Thanks for the update. Glad its working again.
