### ISSUE TITLE
[Node SDK] Authorization header addition removes User-Agent header

### ISSUE THREAD

**Issue by mtebbs** [Microsoft/BotBuilder#2775]
## Pre-flight checklist
- [x] I have [searched the existing issues](https://github.com/Microsoft/BotBuilder/issues?utf8=%E2%9C%93&q=is%3Aissue) before logging a new one.
---------------------------

## System Information (Required)

* SDK Pletform: Node
* SDK Version: 3.8.1
* Development Environment: localhost with bot emulator

## Issue Description

`ChatConnector. addAccessToken()` replaces headers with the 'Authorization' header and bearer token. Specifically it removes the 'User-Agent' header previously added by `ChatConnector.addUserAgent()`.

## Example Code

`
options.headers = {
  'Authorization': 'Bearer ' + token
};
`

should be

`
if (options.headers == null) {
  options.headers = {};
}
options.headers['Authorization'] = 'Bearer ' + token;
`

## Expected Behavior

User-Agent header to be persisted and present in the HTTP response.

## Actual Results

Absence of this header causes the Bot Emulator to throw a warning about an old version of  SDK being used.

e.g.
[09:22:35] Warning: The Bot is using an SDK version earlier than 3.5.0. 
[09:22:35] Warning: SDK versions earlier than 3.5.0 use an authentication configuration that will no longer work after July 31, 2017. 
[09:22:35] Warning: For your bot to continue working beyond this date, please update your bot to use an SDK version greater than or equal to 3.5.0. 
[09:22:35] Read about the Bot Framework authentication change.

**Comment by iMicknl** [comment]
Did you already try the 3.8.1 update? I believe it was already fixed in this commit, however @Stevenic should be able to confirm for sure.
https://github.com/Microsoft/BotBuilder/commit/7997381d9dfc586e30e199c9757bb4c06a0b441c

**Comment by mtebbs** [comment]
Ah, I mis-typed the version, this issue exists in 3.8.1 due to this commit :) I updated the original report from 3.8.0 -> 3.8.1.

**Comment by Stevenic** [comment]
Just published 3.8.3 which contains a fix.

**Comment by nwhitmont** [comment]
Thanks @Stevenic !

**Comment by nwhitmont** [comment]
@mtebbs @iMicknl  Fix published in botbuilder@3.8.3 - let me know if you're still seeing the issue after upgrading.

**Comment by mtebbs** [comment]
Tested connection to bot built with 3.8.3 from emulator and via channel. No more warning. Thx.

**Comment by nwhitmont** [comment]
@mtebbs excellent!
