### ISSUE TITLE
Skip confirmation step with FormBuilder

### ISSUE THREAD

**Issue by mahmoudahmedarafa** [Microsoft/BotBuilder#2783]
During running my project, after bot's reply to user message, it replies with a confirmation message like the image below:

![msbot](https://cloud.githubusercontent.com/assets/22199398/26161494/5c312988-3b24-11e7-8213-ad297e5972e6.PNG)

Here is the "IForm<T>.BuildForm" I am using:
```
public static IForm<McDonaldsBot> BuildForm()
{
        return new FormBuilder<McDonaldsBot>()
                    .Message(reply)
                    .Build();
}
```

The '[Microsoft.Bot.Builder.FormFlow.FormBuilderBase< T >.Confirm](https://docs.botframework.com/en-us/csharp/builder/sdkreference/de/d9d/class_microsoft_1_1_bot_1_1_builder_1_1_form_flow_1_1_form_builder.html#ad6afa1a95d22eb01298cf73bb7869f39)' method is enforced to be called every time 'IForm <T>.BuildForm' is called.

I tried to overload "IForm<T>.BuildForm" like this:
```
return new FormBuilder<QuestionYourThinking>()
    .AddRemainingFields()
    .Confirm("No verification will be shown", state => false)
    .Message("L'exercice est maintenant terminé. A bientot !")
    .Build();
```
But it didn't work out. It still posts a confirmation message: "Is this your selection?".

**Comment by JasonSowers** [comment]
Have you resolved this issue yet, or are you still having the same problem?

**Comment by mahmoudahmedarafa** [comment]
@JasonSowers I tried to search the documentation for additional overloads for 'Confirm', yet all of them are expecting a confirmation message as an argument.

**Comment by JasonSowers** [comment]
@mahmoudahmedarafa Let me see what I can find out and get back to you on this one.  Thank you for responding.

**Comment by Ma3yTa** [comment]
@mahmoudahmedarafa if you change your code to 

```
return new FormBuilder<QuestionYourThinking>()
    .AddRemainingFields()
    // .Confirm("No verification will be shown", state => false) //delete this line
    .Message("L'exercice est maintenant terminé. A bientot !")
    .Build();
```

confirmation will not show

@JasonSowers I think you can close this issue

**Comment by ashkamble** [comment]
Confirmation message is still populating even after using following code

return new FormBuilder<QuestionYourThinking>()
    .AddRemainingFields()
    .Message("L'exercice est maintenant terminé. A bientot !")
    .Build();

Microsoft.Bot.Builder v3.15.2.2
Emulator v3.5.35
