### ISSUE TITLE
[Question] How to display data in Table format in BOT

### ISSUE THREAD

**Issue by MuraliMohanEdiga** [Microsoft/BotBuilder#2785]
Hi,

Can some one please help me out in displaying the data table format in BOT as below

![table](https://cloud.githubusercontent.com/assets/28749004/26186524/ebfadc4a-3baf-11e7-9576-b8cf764fcdd2.png)

**Comment by nwhitmont** [comment]
@MuraliMohanEdiga Are you using .NET or Node SDK for BotBuilder?

**Comment by stevengum97** [comment]
@MuraliMohanEdiga which channel are you trying to create a table on?

**Comment by nwhitmont** [comment]
To display a table in your message, set your message `textFormat` property to `xml` and use a HTML string as your message text. 

Example (Node SDK):
```javascript
bot.dialog('message_with_table', function (session) {
    var tableHTML = '<table style="padding:10px;border:1px solid black;"><tr style="background-color:#c6c6c6"><th>Countries</th><th>Capitals</th><th>Population</th><th>Language</th></tr><tr><td>USA</td><td>Washington D.C.</td><td>309 million</td><td>English</td></tr><tr><td>Sweden</td><td>Stockholm</td><td>9 million</td><td>Swedish</td></tr></table>';
    var message = {
        type: 'message',
        textFormat: 'xml', 
        text: tableHTML
    };
    session.send(message);
});
```

**Comment by MuraliMohanEdiga** [comment]
@nwhitmont ..Its working for  me to display data in table format. Thank you so much

**Comment by MuraliMohanEdiga** [comment]
Hi @nwhitmont 

Thanks for your reply  about displaying the  data in table format .With reference  to the syntax provided I am trying to create login(html) form in the BOT ,I am able to create the form with some html controls like text boxes(input fields) please find the screenshot given below.

Can you please let me know how to retrieve the  values of the form fields(text boxes/Password fields) created in the bot.

Please find the sample snippet

var tableHTML ='<html><head><title>Login page</title></head><body><h1>Simple Login Page</h1><form name="login">Username<input type="text" name="userid"/>Password<input type="password" name="pswrd"/><input type="button" onclick="check(this.form)" value="Login"/><input type="reset" value="Cancel"/></form>   </body></html>';

    var message = {
        type: 'message',
        textFormat: 'xml', 
        text: tableHTML
    };
    session.send(message);
	session.endDialog();

}

]).triggerAction({ 
matches: [/representative form/i, /loginform/i]
});

 
	function check(form) { /*function to check userid & password*/
                /*the following code checkes whether the entered userid and password are matching*/
                if(form.userid.value == "myuserid" && form.pswrd.value == "mypswrd") {
				alert("success")
                    //window.open('target.html')/*opens the target page while Id & password matches*/
                }
                else {
                    alert("Error Password or Username")/*displays error message*/
                }
            }
			
![capture](https://cloud.githubusercontent.com/assets/28749004/26305302/5b0c61e4-3f0c-11e7-9449-94f25ad1e34b.PNG)

**Comment by himanshu2221** [comment]
hi.. did you get proper table format in slack bot? I am also looking for a similar option.  it would be great if you can share your suggestions.

**Comment by karuneshgurkar10** [comment]
hi..can you please how to display table in bot by .net sdk

**Comment by mamba219** [comment]
yeah, it will be helpful, anybody sends code to display table in bot by .NET SDK

**Comment by kushalnawalakha** [comment]
I tried to set 
IMessageActivity message = Activity.CreateMessageActivity();
message.TextFormat = "xml";
 but that didnt work, anyone has any suggestions?
