### ISSUE TITLE
[Emulator] Failed to upload attachment after upgrade SDK of Bot

### ISSUE THREAD

**Issue by wolf0x** [Microsoft/BotBuilder#2787]
## System Information (Required)

* SDK Pletform: Node?
* SDK Version: 3.8.3
* Development Environment: localhost

## Issue Description

When I upgraded Bot framework SDK to version 3.8.3, it is not possible to upload attachment in Emulator

## Example Code

```
var builder = require("botbuilder");
var restify = require('restify');
require('dotenv-extended').load();

var server = restify.createServer();
server.listen(process.env.port || process.env.PORT || 3978, function () {
    console.log('%s listening to %s', server.name, server.url);
});
var connector = new builder.ChatConnector({
    appId: process.env.MICROSOFT_APP_ID,
    appPassword: process.env.MICROSOFT_APP_PASSWORD
});
server.post('/api/messages', connector.listen());

var bot = new builder.UniversalBot(connector);

bot.dialog('/', [
    function (session) {
        session.beginDialog('/phonePrompt');
    },
    function (session, results) {
        session.send('Got it... Setting number to %s', results.response);
    }
]);
bot.dialog('/phonePrompt', [
    function (session, args) {
        if (args && args.reprompt) {
            builder.Prompts.text(session, "Enter the number using a format of either: '(555) 123-4567' or '555-123-4567' or '5551234567'")
        } else {
            builder.Prompts.text(session, "What's your phone number?");
        }
    },
    function (session, results) {
        var matched = results.response.match(/\d+/g);
        var number = matched ? matched.join('') : '';
        if (number.length == 10 || number.length == 11) {
            session.endDialogWithResult({ response: number });
        } else {
            session.replaceDialog('/phonePrompt', { reprompt: true });
        }
    }
]);
```

## Steps to Reproduce
1. execute the above js code
2. talk to the bot via emulator and it asked "What's your phone number?"
3. try to upload any attachment
4. it will fail and return "I didnt' understand, Please try again"
5. even in Debug mode, it wont catch any trap.

In previous version, there's no such problem...

**Comment by Stevenic** [comment]
You're asking for a phone number using `Prompts.text()` but uploading an attachment. I'm not sure I follow. It's waiting for you to send text not an attachment. It's possible that the new prompt system is a little more strict then the old prompt system and is rejecting empty text.

**Comment by Stevenic** [comment]
I just double checked the new code and it is enforcing that the user actually sent text but I personally think that's a good thing. You can use `Prompts.attachment()` if you want to receive an attachment. You can also add a custom global recognizer that looks for attachments to be uploaded at any time.

**Comment by wolf0x** [comment]
@Stevenic your answer is right, I have to use prompts.attachment... thats very trouble to my code, as I allow user to upload attachment file anytime during any conversation.. so what is your solution details for add a custom global recognizer? how to do it?
