### ISSUE TITLE
[Question] Masking/Encrypting  data for password entry

### ISSUE THREAD

**Issue by ne00346536** [Microsoft/BotBuilder#2788]
Hi ,

In bot we have to authenticate the user with user id and password.  Can someone please let me know how to mask the password data while entering the details.

Thanks.

**Comment by nwhitmont** [comment]
@ne00346536 are you using .NET or Node SDK for BotBuilder?

**Comment by ne00346536** [comment]
@nwhitmont   I am using Node SDK bot builder.

Thanks

**Comment by nwhitmont** [comment]
@ne00346536 What is your sign-in scenario exactly? Are you using WebChat? Or a specific channel? Can you explain the intended user experience you are looking for?

**Comment by nwhitmont** [comment]
One way to approach this scenario: [Integrate your bot with a web browser](https://docs.microsoft.com/en-us/bot-framework/bot-design-pattern-integrate-browser). For example, if you want to direct users to a secure website to complete a task, then direct them back to the bot.

Alternately, you could [embed your bot in a website](https://docs.microsoft.com/en-us/bot-framework/bot-design-pattern-embed-web-site) and require users to login to the site before they can access the bot.

**Comment by nwhitmont** [comment]
As for executing user logins inside the bot, it's not currently a feature as Bot Framework is still in preview phase, but definitely open a Feature Request at [https://botframework.uservoice.com/](https://botframework.uservoice.com/) if you're interested in this type of capability.
