### ISSUE TITLE
No response from /deleteprofile

### ISSUE THREAD

**Issue by mikkhait** [Microsoft/BotBuilder#279]
I know it's some where on my end, but all of a sudden all my bots (including new and fresh with 0.10.2) are not reposting nor doing anything for `/deleteprofile`. This applies to working with **BotConnector** platform as well as with Emulator.

<img width="1353" alt="screenshot 2016-05-13 09 33 07" src="https://cloud.githubusercontent.com/assets/1232731/15254853/be310784-18ed-11e6-97ce-ee47c90da223.png">

**Comment by msft-shahins** [comment]
Emulator doesn't support `/deleteprofile` command, only connector supports `/deleteprofile` command.  It works for the test bots that we have. Can you email, your bot ID and the Microsoft ID associated with your bot to [botframework@microsoft.com](mailto:botframework@microsoft.com) so we can debug the issue?

**Comment by mikkhait** [comment]
done, thanks

**Comment by Stevenic** [comment]
Can you share your code? The blank replies imply that you're call `session.endDialog()` somewhere without sending a message

**Comment by mikkhait** [comment]
Before I share the code, it acts the same on examples as well. I do not have any `endDialog()` without a string.

Simple `HelloWorld` does same thing

**Comment by msft-shahins** [comment]
@mikkhait  we did a deployment today with a fix for `/deleteprofile`. Can you see if it start working for your bot again on production?

**Comment by msft-shahins** [comment]
Closing this issue. Feel free to reopen if you still see the problem.
