### ISSUE TITLE
FormFlow Template attribute throws exception for fields of type string

### ISSUE THREAD

**Issue by maximilianlorent** [Microsoft/BotBuilder#2792]
## System Information

* SDK Pletform: .NET
* SDK Version: 3.8.1
* Development Environment: localhost 

## Issue Description

Today I updated BotBuilder to version 3.8.1. Unfortunately since then I get the following exception for an FormFlow dialog which before was running like a charm.

> Missing resources System.Collections.Generic.List`1[System.String]

I identified that this error is raised when calling the .Build() method on the FormBuilder due to the following reason:

In my FormFlow dialog I am using the following fields and the following attributes

```
[Pattern(@"^[\w\s]+$")]
[Template(TemplateUsage.NotUnderstood, "\"{0}\" ist kein gültiger Wert für den Rezeptnamen.")]
[Prompt("Wie soll das neue Rezept heißen?")]
[Describe("Rezept")]
public string RecipeName;
```

I found out that the attribute causing this exception is the [Template(...)] attribute. I also found out that this problems only occurs for fields of type string (I've got many other fields of many different types in my FormFlow dialog which also use the [Template(...)] attribute, but they don't make any problems).

Before I was using BotBuilder version 3.3.3. There the problem did not occur. Thus I assume that something must have changed.

My question now is: is this a bug or a feature. If it is a feature why do you not support the [Template(...)] attribute for strings anymore. This was quite useful for us.

## Example Code

(see above)

## Steps to Reproduce
1. Create a new FormFlow dialog including the string field and attribute I have posted above.
2. Debug FormBuilder<YourFormFlowDialog>().Build()

## Expected Behavior

> Missing resources System.Collections.Generic.List`1[System.String]

 exception is thrown.

**Comment by kneuLIL** [comment]
The dialog in question uses resource files to generate the prompts and answers in different languages. 
These resources files were generated using the rview tool mentioned in the [documentation](https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-formflow-localizel).

For, at least to me unknown reasons, the tool does not generate a resource key for the NotUnderstood template from the RecipeName property. In the previous sdk version this seems to have been ignored. Now the formflow dialog appears to be stricter and throws the error. 
Manually adding the resource key

    NotUnderstood;RecipeName;TEMPLATE

solved the error.

**Comment by EricDahlvang** [comment]
Thank you for reporting this issue. I'm glad you've found a solution!
