### ISSUE TITLE
[Question] Why Debug can see the object properties but print "undefined" finally?

### ISSUE THREAD

**Issue by wolf0x** [Microsoft/BotBuilder#2798]
* SDK Pletform: Node?
* SDK Version: 3.8.3
* Development Environment: localhost

## Issue Description

Expect to print the object properties, it is visible on debug watch window but print "undefined" finally when used on code.

## Example Code

```
var builder = require("botbuilder");
var restify = require('restify');
require('dotenv-extended').load();

var server = restify.createServer();
server.listen(process.env.port || process.env.PORT || 3978, function () {
    console.log('%s listening to %s', server.name, server.url);
});
var connector = new builder.ChatConnector({
    appId: process.env.MICROSOFT_APP_ID,
    appPassword: process.env.MICROSOFT_APP_PASSWORD
});
server.post('/api/messages', connector.listen());

var bot = new builder.UniversalBot(connector);

bot.dialog('/', [
    function (session) {
        session.beginDialog('phonePrompt');
    },
    function (session, results) {
        session.send('Got it... Setting number to %s', results.response);
    }
]);
bot.dialog('phonePrompt', [
    function (session, args, next) {
        //session.dialogData.profile = args ? args : {};
        if(args){
            session.dialogData.profile = args;
            console.log(session.dialogData.profile);
            next();
        }
        else{
            session.dialogData.profile = {};
            session.dialogData.profile.name = '';
            session.dialogData.profile.coding = '';
            session.dialogData.profile.language = '';
            builder.Prompts.text(session, "Hello... What's your name?");
        }
    },
    function (session, results) {
        if(session.dialogData.profile.name==''){
            session.dialogData.profile.name = results.response;
        }
        console.log(session.dialogData.profile);
        builder.Prompts.text(session, "Hi " + session.dialogData.profile.name + ", How many years have you been coding?");         
    },
    function (session, results) {        
        if (results.response.length == 10 || results.response.length == 11) {
            session.dialogData.profile.coding = results.response;
            builder.Prompts.text(session, "What language do you code Node using?");
        } else {
            session.replaceDialog('phonePrompt',session.dialogData);
        }        
    },
    function (session, results) {
        session.dialogData.profile.language = results.response;
        session.send("Got it... " + session.dialogData.profile.name + 
                     " you've been programming for " + session.dialogData.profile.coding + 
                     " years and use " + session.dialogData.profile.language + ".");
    }
]);
```

## Steps to Reproduce
1. execute the code
2. the first time ask for name, you type "any"
3. then it ask for years, you type "0" or any digital
4. as it didnt met the requirement of length > 10, then it replaceDialog and start from beginning with the session.dialogData saved before
5. when you debug the code, you can see the session.dialogData print out successfully
6. but when you use that properties, you get "undefined"

So, what's wrong on the variable?

**Comment by nwhitmont** [comment]
@wolf0x if you want to persist data across dialogs, use `userData` and not `dialogData`. Nothings wrong with the variable, its designed to work that way. 

Also, you're not checking if the years input is greater than 10, you're checking if it is equal to 10 or equal to 11. That's not the same as checking if a number is greater than 10.

**Comment by wolf0x** [comment]
@nwhitmont 

Please dont close the case yet as it looks that you answered with a std answer but you didnt read my question and my code clear yet.

I know to use userData instead of dialogData, however, please read my code that it used ReplaceDialog to callback the session.dialogData to args, then it transfer the object data to next dialog. I'd suggest you to run my code in advance, and you would debug and understand what I meant.

during debug period, the debug watch window can show the value of profile object, but when print it becomes "undefined" thats my problem and question.
