### ISSUE TITLE
[Question] Authorization for Microsoft App ID failed?

### ISSUE THREAD

**Issue by asubbotin** [Microsoft/BotBuilder#2799]
Hello,

I have a problem. Bot Builder upgraded from version 3.1.0 to 3.8.1.

Code:

```
var connector = new ConnectorClient(new Uri(activity.ServiceUrl), "[AppID]", "[Password]");
newMessage.Type = ActivityTypes.Message;
newMessage.From = new ChannelAccount { Id = activity.Recipient.Id, Name = activity.Recipient.Name };
newMessage.Conversation = new ConversationAccount { Id = activity.Conversation.Id };
newMessage.Recipient = new ChannelAccount { Id = activity.From.Id };
newMessage.ChannelId = activity.ChannelId;
newMessage.Text = "TEST MESSAGE";
connector.Conversations.SendToConversation((Activity)newMessage);
```

And i have error "Authorization for Microsoft App ID [AppID] failed with status code Unauthorized and reason phrase 'Unauthorized'".

If i use constructor as:
`var connector = new ConnectorClient(new Uri(activity.ServiceUrl));`
and app.config contains:
```
<add key="BotId" value="[BotID]" />
<add key="MicrosoftAppId" value="[AppID]" />
<add key="MicrosoftAppPassword" value="[Password]" />
```
then sending message is working.

Before upgrade my code is worked.
Can help me? Thanks!

**Comment by EricDahlvang** [comment]
You need to add a call to 
MicrosoftAppCredentials.TrustServiceUrl(serviceUrl);
This is done automatically when you are replying to a message, but not when using the ConnectorClient

**Comment by asubbotin** [comment]
Thanks! Works now.

**Comment by stevengum97** [comment]
Closing Issue.
