### ISSUE TITLE
LuisDialog doesn't react on questions

### ISSUE THREAD

**Issue by svarnyjunak** [Microsoft/BotBuilder#28]
Hi,
I'm trying to use LuisDialog with "Cortana Models Prebuilt App", but it doesn't work with current API. When I send "turn on my wake up alarm", I get JSON result as below:

```
{
  "query": null,
  "intents": [
    {
      "intent": "builtin.intent.alarm.set_alarm",
      "score": null,
      "actions": null
    }
  ],
  "entities": [
    {
      "entity": "on",
      "type": "builtin.alarm.alarm_state"
    },
    {
      "entity": "wake up",
      "type": "builtin.alarm.title"
    }
  ]
}
```

The result has one intent with already set property score, so the LuisDialog doesn't set score to 1.0 and the intent is completely ignored.

**Comment by Stevenic** [comment]
This is using C# I assume? On the node side of things I catch that and automatically set the score to 1.0. Shahin could you take a look at this?

**Comment by svarnyjunak** [comment]
I am sorry not to specify it before. The trouble is in node.js in LuisDialog class at this line:
`if (result.intents.length == 1 && !result.intents[0].hasOwnProperty('score')) {`

The score property In JSON is specified, but has no value. And that is the reason why score stays null.

**Comment by Stevenic** [comment]
Oh I see... they must have changed their structure on me. Before they weren't returning a score at all. Looks like now they do but it's just null... grrr.... let me work on a fix and I'll publish an updated NPM.

**Comment by Stevenic** [comment]
Can you do me a favor and try replacing that test with.

     if (result.intents.length == 1 && typeof result.intents[0].score !== 'number') {

**Comment by Stevenic** [comment]
We're actually talking to the LUIS guys about fixing this issue

**Comment by Stevenic** [comment]
I'm publishing a fix. Version 0.6.3 should be on npm in a moment.

**Comment by tvmick** [comment]
Please please please go away your driving me mad with your constant emailing

**Comment by svarnyjunak** [comment]
Works fine now. Thanks.
