### ISSUE TITLE
[Question] Multiple users getting the same answer on different queries at the same time

### ISSUE THREAD

**Issue by msBot1111** [Microsoft/BotBuilder#2800]
My Bot is implemented in c#, and the main dialog is LUIS Dialog. So I've detected when different users in the same time ask the bot different queries, the bot detects just one query from the one user and replays the same answer to the both users. I've integrated the bot in skype and in my xamarin app. So, how can I detect more queries in the same time. I'm using chain dialog like this:
  internal static IDialog<object> MainRoot()
        {
            return Chain.From(() => new MainDialog());  // Main dialog is LUIS Dialog 
//  public class MainDialog : LuisDialog<object>
        }
       await Conversation.SendAsync(activity, MainRoot);

**Comment by PrasadGautham** [comment]
I had a similar issue!! But mine was a total blunder from my side!!!! Mine was because I used some static properties!!

**Comment by msBot1111** [comment]
I use static properties too. Are you saying that's because of them? @PrasadGautham

**Comment by PrasadGautham** [comment]
To me that was the issue....I was storing a particular variable through a static property.....So this value was changing with context to the whole users and not just an individual...So I think we used conversationdata to store that....Am not sure if thats the case with you as well... Let the experts say!!! I am not very well aware

**Comment by michaelhutchful** [comment]
Yeah, static properties persist their data over multiple messages. Try and avoid static if you don’t want this behaviour 

Sent from my Windows 10 phone

**Comment by EricDahlvang** [comment]
@msBot1111 please post more code, so we can help determine what the issue is.

**Comment by JasonSowers** [comment]
@msBot1111 did your issue get resolved?

**Comment by msBot1111** [comment]
yes I did, thanks. The issue was with the static properties.
