### ISSUE TITLE
Microsoft Bot Framework: HTTP status code InternalServerError

### ISSUE THREAD

**Issue by auanish** [Microsoft/BotBuilder#2805]
* SDK Pletform: Node
* SDK Version: 3.8.3
* Development Environment: Azure App Service

I have a couple of bots which were working without any issues till today morning. I was given the following warning message on the bot portal:

We've revised our security protocol. Update to Bot Builder 3.5+ or compatible security configuration by July 31, 2017 to keep your bot working.

So I upgraded the botbuilder framework to 3.8.3 using npm install –save botbuilder

Ever since I upgraded one bot stopped working but the other works fine. The error message I get is 

> There was an error sending this message to your bot: HTTP status code InternalServerError.

The bot works perfectly fine on the bot emulator but not after it's deployed to azure. So it's not even a code issue. To think if it's a Microsoft server issue, my other bot works just fine. What could be possibly going wrong?

**Comment by nwhitmont** [comment]
What is the response when you hit your Bot /api/messages endpoint in your
browser?

**Comment by Darksole** [comment]
Also having a what I think is a related issue.
SDK Pletform: Node
SDK Version: 3.8.3, 3.7.0, 3.6.0
Development Environment: AWS EC2

Was originally on SDK 3.7 tried upgrading 3.8.3 to see if issue was resolved, also tried downgrading to 3.6.0. I get the message: There was an error sending this message to your bot. When testing on dev.botframework.com, and when I attempt to post the server at  /api/messages using postman I get:
{
  "code": "InternalError",
  "message": "Unexpected end of input"
}

**Comment by auanish** [comment]
When I try to access it from my browser it says 

> This page isn't loading. bot.azurewebsites.net is currently unable to handle this request. HTTP ERROR 500

**Comment by auanish** [comment]
I figured out the problem and my bot is back up again running now. Apparently its some deployment issues.

I've run the following command first:

> azure site log tail <botsitename>

I got an error message saying:

> Application has thrown an uncaught exception and is terminated:
Error: Cannot find module './dialogs/Prompt'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\home\site\wwwroot\node_modules\botbuilder\lib\logger.js:3:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

So, I've deleted the node_modules folder in the root and reinstalled npm. That brought my bot back to life! :)

**Comment by nwhitmont** [comment]
@auanish I figured some kind of deployment error, so I'm glad you got it back in order.
