### ISSUE TITLE
[Question] Bot prints wrong output.

### ISSUE THREAD

**Issue by sw-ms-roshanparmar** [Microsoft/BotBuilder#2807]
## System Information (Required)

* SDK Pletform: .NET 
* SDK Version: 3.5.5.0
* Development Environment: localhost Emulator
* Production Environment: Azure skype

## Issue Description

Bot Framework prints wrong output in `await context.PostAsync()` method.
## Steps to Reproduce
When we try to print this below string

`"1. Power adapter 2. Desktop Computer  3. Telephone  \r\n \r\n4. Splitter 5. Telephone wall jack 6. Laptop Computer  \r\n \r\na. MODEM interface b. PHONE interface c. LINE interface  \r\n \r\n1.1.2 Getting started  \r\n \r\nAfter connecting the cables, press the On/Off button on the side panel to  \r\n \r\npower on the HG533.  \r\n \r\nThe ADSL indicator lights up and starts blinking. This indicates that the  \r\n \r\nADSL port activation is in progress. The blinking may last less than 3  \r\n \r\nminutes. When the ADSL indicator stops blinking and remains on, the  \r\n \r\nHG533 is working properly.  \r\n \r\n"`

it prints different output as below.
## Actual Results
1. Power adapter 2. Desktop Computer 3. Telephone
**_2. Splitter_** 5. Telephone wall jack 6. Laptop Computer
a. MODEM interface b. PHONE interface c. LINE interface
1.1.2 Getting started
After connecting the cables, press the On/Off button on the side panel to
power on the HG533.
The ADSL indicator lights up and starts blinking. This indicates that the
ADSL port activation is in progress. The blinking may last less than 3
minutes. When the ADSL indicator stops blinking and remains on, the
HG533 is working properly.
 

## Expected Behavior

Here the string should be printed as follow.
1. Power adapter 2. Desktop Computer 3. Telephone
**_4. Splitter_** 5. Telephone wall jack 6. Laptop Computer
a. MODEM interface b. PHONE interface c. LINE interface
1.1.2 Getting started
After connecting the cables, press the On/Off button on the side panel to
power on the HG533.
The ADSL indicator lights up and starts blinking. This indicates that the
ADSL port activation is in progress. The blinking may last less than 3
minutes. When the ADSL indicator stops blinking and remains on, the
HG533 is working properly.

Here, the original text **_4.Splitter_** is always changed to **_2.Splitter_** (tested in emulator and skype). I don't understand why this is happening.

**Comment by JasonSowers** [comment]
Hi, have you found a solution to this issue yet?  Have you tried on a more recent sdk like 3.8.1?

**Comment by sw-ms-roshanparmar** [comment]
Yes, I have tried by updating the framework to latest stable 3.8.1. But the result is same
Sample Code:
```
private async Task MessageReceivedAsync(IDialogContext context, IAwaitable<object> result)
        {
            var activity = await result as Activity;

            string mystr = "1. Power adapter 2. Desktop Computer 3. Telephone \r\n \r\n4. Splitter 5. Telephone wall jack 6. Laptop Computer \r\n \r\na. MODEM interface b. PHONE interface c. LINE interface \r\n \r\n1.1.2 Getting started \r\n \r\nAfter connecting the cables, press the On/Off button on the side panel to \r\n \r\npower on the HG533. \r\n \r\nThe ADSL indicator lights up and starts blinking. This indicates that the \r\n \r\nADSL port activation is in progress. The blinking may last less than 3 \r\n \r\nminutes. When the ADSL indicator stops blinking and remains on, the \r\n \r\nHG533 is working properly. \r\n \r\n";
            await context.PostAsync(mystr);

        }
```

Output:
![capture](https://cloud.githubusercontent.com/assets/19162518/26339802/36a23710-3fa8-11e7-83db-5f661f67007b.PNG)

**Comment by JasonSowers** [comment]
@sw-ms-roshanparmar it looks like it is trying to make an ordered list for you.  

can you try this and see if it helps or changes anything
```cs
            string s = @"1. Power adapter 2. Desktop Computer 3. Telephone"+ "\r\n \r\n"+@"4.Splitter 5.Telephone wall jack 6.Laptop Computer"+"\r\n \r\n"+"a.MODEM interface b. PHONE interface c. LINE interface \r\n \r\n1.1.2 Getting started \r\n \r\nAfter connecting the cables, press the On/Off button on the side panel to \r\n \r\npower on the HG533. \r\n \r\nThe ADSL indicator lights up and starts blinking. This indicates that the \r\n \r\nADSL port activation is in progress.The blinking may last less than 3 \r\n \r\nminutes.When the ADSL indicator stops blinking and remains on, the \r\n \r\nHG533 is working properly. \r\n \r\n";

```

**Comment by sw-ms-roshanparmar** [comment]
yes @JasonSowers , it has started working now. But could not understand where I was making a mistake
