### ISSUE TITLE
[Question] There was an error completing this request due to an internal channel failure

### ISSUE THREAD

**Issue by neetgupta7** [Microsoft/BotBuilder#2809]
Hello
For past 2 weeks i am facing error "There was an error completing this request due to an internal channel failure" with my bot. BOT App id is "cc35e86c-faf5-4032-aef8-448f47bac745".
It used to work fine earlier from different skype ids. Since last week it started throwing above error for infy_97814@outlook.com login. But with other ids there are no issues. 

I am testing my bot from Skype channel by sending messages. I am logged into skype from the same outlook account (as above) and its giving error. I also deployed a new app service for the bot and re-registered it on bot portal but the error remains.

I then added a try catch block and now i see below exception message - "Response status code does not indicate success: 401 (Access Denied)". Please note i m also using LUIS dialog. The same pair of LUIS App id and subscription key works fine for other bot.

Can you please help.

**Comment by nwhitmont** [comment]
@neetgupta7 Are you using .NET or Node SDK?

**Comment by neetgupta7** [comment]
I am using .net. So the issue is now resolved. Problem seems to be with the LUIS key that i was using. I created a new LUIS key from Azure and used it and it worked. What is strange is that the same old key works fine with other chatbot but with this one it was giving error. Any idea about this.

**Comment by nwhitmont** [comment]
@neetgupta7 I'm glad you found the solution! thanks for the update
