### ISSUE TITLE
[Question] Can you please let me know how to retrieve the values of the form fields(text boxes/Password fields) created in the bot.

### ISSUE THREAD

**Issue by MuraliMohanEdiga** [Microsoft/BotBuilder#2812]
## Pre-flight checklist
By the reference of https://github.com/Microsoft/BotBuilder/issues/2785#issuecomment-302429892
created login form in BOT.
---------------------------

## System Information (Required)
* SDK Platform: Node 
* SDK Version: 
* Development Environment: localhost

## Issue Description
I am trying to create login(html) form in the BOT ,I am able to create the form with some html controls like text boxes(input fields) please find the screenshot given below.

Can you please let me know how to retrieve the values of the form fields(text boxes/Password fields) created in the bot.

## Example Code
Please find the sample snippet

![capture1](https://cloud.githubusercontent.com/assets/28749004/26338668/81f67fae-3f9f-11e7-9774-41dc17e3f542.PNG)
```js
var message = {
    type: 'message',
    textFormat: 'xml', 
    text: tableHTML
};
session.send(message);
session.endDialog();
}

]).triggerAction({
matches: [/representative form/i, /loginform/i]
});

function check(form) { /*function to check userid & password*/
            /*the following code checkes whether the entered userid and password are matching*/
            if(form.userid.value == "myuserid" && form.pswrd.value == "mypswrd") {
			alert("success")
                //window.open('target.html')/*opens the target page while Id & password matches*/
            }
            else {
                alert("Error Password or Username")/*displays error message*/
            }
        }
```

## Expected Behavior
In the above function check(form) needs to get the form userid and pwd and after validation need to give success message in the emulator

![capture](https://cloud.githubusercontent.com/assets/28749004/26338680/9c04efe8-3f9f-11e7-9d25-ee6ca27b32ba.PNG)

**Comment by nwhitmont** [comment]
@MuraliMohanEdiga What you are trying to do is not currently a feature of Bot Framework.

To accomplish your goal, you would need to setup a waterfall dialog that prompts the user for the required information using `builder.Prompts.text()`. For more information see: [Prompt users for input](https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-dialog-prompt).

**Comment by MuraliMohanEdiga** [comment]
@nwhitmont Thank you for your time
