### ISSUE TITLE
[Question] How to use custom chat page(e.g. html page) in place of bot emulator to communicate with bot in local IIS?

### ISSUE THREAD

**Issue by Harshjaswal** [Microsoft/BotBuilder#2814]
How to use custom chat page(e.g. html page) in place of bot emulator to communicate with bot in local IIS?

**Comment by nwhitmont** [comment]
Are you using .NET or Node SDK?

**Comment by nwhitmont** [comment]
@Harshjaswal If you would like to embed the chat in your website, use the [BotFramework-WebChat](https://github.com/Microsoft/BotFramework-WebChat) project.

**Comment by Harshjaswal** [comment]
Thanks...but the thing is I don't want to use azure for it..as we use bot
emulator to chat with bot application,  i want to use a custom chat page
created in html...means i want to know can we connect our bot application
with simple html page to communicate..if yes plz tell me how. Thanku

**Comment by Harshjaswal** [comment]
I am using. Net
