### ISSUE TITLE
[Question] Limitations on Custom Entities

### ISSUE THREAD

**Issue by narenkv** [Microsoft/BotBuilder#2815]
Issue : As there are limitations on Custom Entities to 30 , Is there any plans to increase the Entities count?. 

Sample Entities which we created is "Interest Rate" , "Loan types", etc various other attributes. So we are running short of entities creation.  

Can you please guide us on this, and wanted to know if there are chances to increase limit on the custom entities creation.

Thank you

**Comment by nwhitmont** [comment]
@narenkv are you using .NET or Node SDK?

**Comment by stevengum97** [comment]
Currently you may only have 30 entities. One way to "extend" your entity count is to rethink your entities and see what can be converted to List Entities. List Entities are not machine learned and have a separate limit of 50.

If you do need machine learning for your Entities, you should look into creating another LUIS model and plugging that endpoint into your ChatBot as well.

**Comment by narenkv** [comment]
.net

**Comment by nwhitmont** [comment]
@narenkv did @stevengum97 answer resolve your issue?

**Comment by narenkv** [comment]
I see limitations on entities currently, I will now have to figure out to rework on my solution. 

I feel these limitations has to be documented in the docs, so that we know how to take care in the design phase.

I hope the limitations on entities will be addressed soon as 30 or 50 entities will still not be enough for a medium/large scale modules

/Naren

**Comment by stevengum97** [comment]
I understand your frustration on the limitations; these limitations are documented in the documentation. For entities it can be found [here](https://docs.microsoft.com/en-us/azure/cognitive-services/LUIS/luis-concept-entity-types), and for intents that limit can be found [here](https://docs.microsoft.com/en-us/azure/cognitive-services/LUIS/luis-concept-intent).

I'm closing this issue, but if anyone has comments or questions please feel free to place them here.

**Comment by narenkv** [comment]
Hey,

I just signed the petition "India Parliament : NAMO should call for an
emergency parliament session for removing Article 370." and wanted to see
if you could help by adding your name.

Our goal is to reach 5,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/MLTnNhYGYD

Thanks!
Narendra
