### ISSUE TITLE
[Question] Invoking LUIS Application from LUIS Method

### ISSUE THREAD

**Issue by narenkv** [Microsoft/BotBuilder#2816]
We have started exploring multiple options of having multiple LUIS Applications. Example senario

SchoolCoreLUISApplication
SchoolManagementLUISApplication
SchoolAdmissionLUISApplication
SchoolSportAcademyLUISApplication
SchoolNotificationLUISApplication

So we planned to send request to SchoolCoreLUISApplication and based on the intent invoke SchoolManagementLUISApplication and other LUIS Applications.

However we are bit stuck when trying to invoke LUISApplications which the LUIS methods

In the below Sample Code, We don't get error but does not work, As the LUISDialog2 is not invoked.

Can you please guide and help us on this. Below is the sample code
```cs
[LuisIntent("Greetings")]
        public async Task Greetings(IDialogContext context, IAwaitable<IMessageActivity> message, LuisResult result)
        {
            try
            {
                
                Activity activity = await message as Activity;
                //Call the other LUIS Application
                await Conversation.SendAsync(activity, () => (IDialog) new LUISDialog2());
            }
            catch(Exception ex)
            {
                 //Log exception
            }
        }
```

 /Naren

**Comment by narenkv** [comment]
I have found a solution , now it works, happy to share the same to the community

 var cancellationTokenSource = new CancellationTokenSource();
 await context.Forward(new LUISDialog2(), LuisDialogComplete, await message, cancellationTokenSource.Token);

        private async Task LuisDialogComplete(IDialogContext context, IAwaitable<object> result)
        {
            var messageHandled = await result;
            context.Wait(MessageReceived);
        }

**Comment by nwhitmont** [comment]
@narenkv glad you found the solution! thanks for the update
