### ISSUE TITLE
[Direct Line] Not able to generate refresh Token and getting error message

### ISSUE THREAD

**Issue by JeevaJose** [Microsoft/BotBuilder#2817]
I have used rest API service to generate token . I pass the web chat secret key as given below.

https://directline.botframework.com/v3/directline/tokens/generate
Authorization Bearer xxxxxxxxxxxxxxxxxx

I am able to generate the token and got the following response
```json
{
  "conversationId": "xxxxxx",
  "token": "xxxxxxxxxxxxxx.wYsv_1ktrrW-xxx__SgGRFQbxxxxW_IuPAtY",
  "expires_in": 1800
}
```
After getting this token I passed to following url to generate the refresh token after the post method I am getting following error message as given below.

Post : https://directline.botframework.com/v3/directline/tokens/refresh
Authorization Bearer "xxxxxxxxxxxxxx.wYsv_1ktrrW-xxx__SgGRFQbxxxxW_IuPAtY",

Error  Message
```json
{
  "error": {
    "code": "ServiceError",
    "message": "This method can only be used to renew an existing token"
  }
}
```

I have used post man service to test the rest API service. There is any timeline like before 5 minute expire only call the refresh token or can I call any time to generate refresh token. 

Could you please help me to fix this issue.

**Comment by nwhitmont** [comment]
@JeevaJose are you using .NET or Node SDK?

**Comment by JeevaJose** [comment]
I am able to fix the issue. hence I am closing this issue.

**Comment by nwhitmont** [comment]
@JeevaJose thanks for the update.

**Comment by Sid245439** [comment]
@JeevaJose  Hey I am facing the same issue please tell me how to fix this issue

**Comment by JeevaJose** [comment]
First you have to generate a token and once that token is ready pass to the conversation then will generate a new token. Pass that token and generate a refresh token.
https://directline.botframework.com/v3/directline/conversations

without conversation you can’t generate a refresh token. I hope this post will help you to fix the issue.

**Comment by shahbazkhurram** [comment]
1. Generate your token using following code:

`
            var token = string.Empty;
            var clnt = new HttpClient();
            clnt.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", "Your_Directline_Secret");

            var rsp = clnt.PostAsync("https://directline.botframework.com/v3/directline/tokens/generate", new StringContent(string.Empty, Encoding.UTF8, "application/json")).Result;

            if (rsp.IsSuccessStatusCode)
            {
                var str = rsp.Content.ReadAsStringAsync().Result;
                var obj = JsonConvert.DeserializeObject<DirectlineRsp>(str);
                token = obj.token;
            }


        `

Then you can use pass token variable to your page and use it in webchat control:

`BotChat.App({
                                            directLine: { token: token_passed_from_server},
                                            user: { id: usrid },
                                            bot: { id: 'mybot' },
                                            resize: 'detect'
                                        }, document.getElementById("bot"));
`

**Comment by morrisond91** [comment]
Could you help me work something out?

We are not using web-chat, we have built our own react front end and using directlineJs.

We have an API that retrieves a token through https://directline.botframework.com/v3/directline/conversations. Upon API response we connect to DirectLine.

Everything works fine, however the token dies in 30 minutes and the conversation locks up.

What we are now trying to do is send a refresh message to https://directline.botframework.com/v3/directline/tokens/refresh passing in our original token, we get a new token back but are unsure what to do next?
