### ISSUE TITLE
[Feature Request] Add Channel: Workplace by Facebook

### ISSUE THREAD

**Issue by SPACEGHOST904** [Microsoft/BotBuilder#2821]
Add channel: Workplace by Facebook

https://stackoverflow.com/questions/44058021/are-groups-in-workplace-by-facebook-supported-via-the-facebook-channel-on-micros

**Comment by nwhitmont** [comment]
Thumbs up to vote

**Comment by EricDahlvang** [comment]
Closing this issue.  Messenger feature requests are tracked here: https://github.com/Microsoft/BotBuilder/issues/4360  (I've referenced this one there)
