### ISSUE TITLE
[Feature Request] Speak and Say the same text by default in Cortana

### ISSUE THREAD

**Issue by cesarvarela** [Microsoft/BotBuilder#2822]
HI guys, a couple of suggestions regarding Cortana api:

I usually find myself copying and pasting the same text for both say and speak parameters:

 ```
botbuilder.Prompts.text(session, 'Which work order did you want to close?', {
                        speak: 'Which work order did you want to close?',
                        inputHint: botbuilder.InputHint.expectingInput
                    });
```
So maybe be it's better to default the `speak` option to use the same value as message text? 

Also,  having to set `inputHint` to `expectingInput` in a text prompt is redundant.

**Comment by cesarvarela** [comment]
just thinking out loud, but what about making the `speak` property `string` or `bool`, if `string` it says the text, if `true`, it uses the same value as text.

**Comment by nwhitmont** [comment]
@cesarvarela are you using .NET or Node SDK?

**Comment by cesarvarela** [comment]
@nwhitmont node

**Comment by nwhitmont** [comment]
@cesarvarela is this a feature request?

**Comment by rbrundritt** [comment]
Note that the inputHint option is optional. You don't need to specify it every time. Here is a quote from the docs: "If you do not specify input hints in your bot, it will automatically select the one depending on the response. Prompts for instance will be expecting input, while a standard text response may be set to accept input.".

**Comment by cesarvarela** [comment]
If I don't set the `inputHint: botbuilder.InputHint.expectingInput` option in the text prompt, the "expecting input thing" isn't happening automatically, maybe this is a bug?

**Comment by JasonSowers** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
