### ISSUE TITLE
[Bug] LUIS - Request URL is too long

### ISSUE THREAD

**Issue by xitij** [Microsoft/BotBuilder#2823]
## System Information
* SDK Platform: Node.js
* SDK Version: 3.8.1

## Issue Description
This issue is a clone of [this](https://github.com/Microsoft/BotBuilder/issues/2067#issuecomment-303883740) github issue that is filed for .NET. That team said I should post the same issue for the node team.

The issue is produced when a user sends a very long message to the bot which causes it to crash. As far as I can tell the issue is because the bot is performing a `GET` on the encoded LUIS url to fetch the user message, then passing it to the framework. In this case the url is over the limit which leads to an empty string being passed to the framework which causes the JSON parsing to fail.

It would be my assumption that botbuilder could detect this error, not crash, and send a more detailed error describing the issue (`"Message was too long"`).

## Steps to Reproduce
1. Send a long message to the bot on the facebook platform

## Actual Results
Bot crashes with the following dump:
```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Request._callback (/Users/tarikourchane/Development/JSDev/gameon-bot/node_modules/botbuilder/lib/dialogs/LuisRecognizer.js:80:39)
    at Request.init.self.callback (/Users/tarikourchane/Development/JSDev/gameon-bot/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/Users/tarikourchane/Development/JSDev/gameon-bot/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (/Users/tarikourchane/Development/JSDev/gameon-bot/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```
and prints: `"Oops. Something went wrong and we need to start over."`
the response from `request.get()` on `LuisRecognizer.js` line 76 has the following:
```
{
  body: "",
  statusCode: 414,
  statusMessage: "Request URL is too long"
}
```

**Comment by PrasadGautham** [comment]
A message with character length more than 500 I think is required

**Comment by nwhitmont** [comment]
@xitij Can you post an example of a "long message" that causes the error?

The answer posted by @PrasadGautham looks like a good alternative way to check the messages before sending to LUIS. Try it as a work-around.

**Comment by xitij** [comment]
> @xitij Can you post an example of a "long message" that causes the error?

Any message over 500 characters, literally all of them. Here is an example:
```
eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
```
Imagine a case where a user is writing a really long request/response. All of those will fail.

> The answer posted by @PrasadGautham looks like a good alternative way to check the messages before sending to LUIS. Try it as a work-around.

I'm unfamiliar with what he/you are referring to as the "message controller". Can you please specify?

**Comment by PrasadGautham** [comment]
I am using c#, with the bot application template. 
   I actually check the length of the text entered by the user and if its greater than 500, I wouldn't make a call to Luis instead I would return some error message.

**Comment by xitij** [comment]
I'm using Node as the issue suggests so I'm not familiar with "message_controller". I suppose the suggestion is to "identify" these long messages in the middleware and not pass them along to LUIS? Is that possible?

**Comment by nwhitmont** [comment]
@xitij You don't need middleware, you can check the `session.message.text` length in your waterfall dialog before you submit it to LUIS.

**Comment by xitij** [comment]
@nwhitmont Sorry I'm a little confused as to where this would be done. I'm currently only using a single `IntentDialog` with my bot. Something along the lines of this:
```
const intentDialog = new builder.IntentDialog({ recognizers: [recognizer] });
intentDialog.matches('SomeLUISIntent', '/processIntent');
intentDialog.onDefault((session, args) => { /* Some default code */ });
...
bot.dialog('/', intentDialog);
bot.dialog('/processIntent', [ ... ]);
```
So currently the default is to send all user messages to LUIS. You're suggesting using a waterfall, or multiple dialogs, something along the lines of:
```
bot.dialog('/', [
  (session, args, next) => {
    if (// message is too long) {
      session.beginDialog('/invalidMsg');
    } else {
      session.beginDialog('/luisDialog');
    }
  }
]);
bot.dialog('/luisDialog', intentDialog);
```
I know there are multiple ways to implement this I'm just trying to make sure this is where you suggest checking `session.message.text` length before submitting to LUIS.

**Comment by stevengum97** [comment]
@xitij, if you're trying to call LUIS mid waterfall, then you can use the following to do so after checking the message length.

```js
if (session.message.text.length < 500) {
  // Message length acceptable, use LuisRecognizer.
  builder.LuisRecognizer.recognize(session.message.text, '<model url>', function (err, intents, entities) {
     if (entities) {
          var entity = builder.EntityRecognizer.findEntity(entities, 'TYPE');
          // do something with entity...
     }
  });
} else {
  // Handle the user's message and return an error...
}

```
The example of the LuisRecognizer is taken from [this comment](https://github.com/Microsoft/BotBuilder/issues/2741#issuecomment-301888868) in Issue #2741. Does this help or have you discovered an acceptable work-around?

**Comment by xitij** [comment]
This is helpful. Currently we're using a work-around where we check the message length in middleware, and reroute to an error message if needed. Thanks.

**Comment by stevengum97** [comment]
Ok, I'm going to close this issue, and look into the merit of adding a Feature Enhancement for this.

**Comment by stevengum97** [comment]
@xitij May I ask what the context of what you're trying to have recognized by LUIS? LUIS is for parsing utterances and not really suited for tasks like document scanning (or scanning other large bodies of text)

**Comment by xitij** [comment]
>  I ask what the context of what you're trying to have recognized by LUIS? LUIS is for parsing utterances and not really suited for tasks like document scanning (or scanning other large bodies of text)

I'm using it to parse utterances. This specific case I was hitting was Facebook where my users are typing an email length message to the bot (probably not using that it's a bot and thinking it goes to messenger got a human to read). At that point I wanted to catch the errors and say something like:
```
"Your message is too long. Please contact support at support@foo.com"
```

Or something along those lines.

**Comment by DanielNetzeriAm** [comment]
why not split the message into 2 requests from the AI and then concat the response?
