### ISSUE TITLE
[Question] Any plan for Private Review of the MetaData implementation on QnA Model

### ISSUE THREAD

**Issue by anirudhaditya** [Microsoft/BotBuilder#2827]
When is the release date for the meta data implementation on QnA.

**Comment by pchoudhari** [comment]
We don't have a date to announce yet. We are actively working on this feature right now.

**Comment by ankitbko** [comment]
Did I miss this in Build? What is this feature?

**Comment by pchoudhari** [comment]
It wasn't part of the Build announcement. We have had several customers ask for the ability to filter and rank results on metadata associated with QnA pairs.
