### ISSUE TITLE
[Question] How to integrate adaptive-card on Custom Web Chat

### ISSUE THREAD

**Issue by anirudhaditya** [Microsoft/BotBuilder#2829]
I have built my own custom Chat Bot but not able to integrate the AdaptiveCard on it. Infact it just shows text only and no events or styles. How to get it resolved.

**Comment by nwhitmont** [comment]
@anirudhaditya are you using .NET or Node SDK? Please share your bot code so we can assist you.

**Comment by EricDahlvang** [comment]
Adaptive Card support in the BotFramework Web Chat control is currently being implemented.  Please see this PR: https://github.com/Microsoft/BotFramework-WebChat/pull/471  

http://adaptivecards.io is also a resource that might be useful for you.
