### ISSUE TITLE
Bot Framework Support

### ISSUE THREAD

**Issue by DL-LiveTiles** [Microsoft/BotBuilder#2836]
Where can we get direct Bot Framework support? Not Bot Builder, the Bot Framework.
Where can we log feature requests? No user voice available...
Where can we log issues? No git or other method available.
Stack exchange is for general questions only.

**Comment by nwhitmont** [comment]
@DL-LiveTiles Thanks for asking. You can get Bot Framework support right here on GitHub. You can also report feature requests here, as well as log issues.  Additionally, you will find the Bot Framework user voice website here: https://botframework.uservoice.com/
