### ISSUE TITLE
[Feature Request] Use constructor injection and remove static ServiceProvider class

### ISSUE THREAD

**Issue by damienpontifex** [Microsoft/BotBuilder#2837]
## Pre-flight checklist
- [x] I have [searched the existing issues](https://github.com/Microsoft/BotBuilder/issues?utf8=%E2%9C%93&q=is%3Aissue) before logging a new one.
---------------------------

## System Information (Required)
* SDK Platform: All
* SDK Version: Latest
* Development Environment: localhost

## Issue Description
Bot builder creates a `ServiceProvider` class and then uses that to do things like get a logger, get configuration etc. Could it move to using constructor injection for these and setup needed dependencies in a `IServiceCollection` extension method? This way, the developer can use whatever container they wish and the BotBuilder library would just move to a dependency on Microsoft.Extensions.DependencyInjection.Abstractions

e.g. there are quite a few cases of `ServiceProvider.Instance.CreateLogger()` 

## Expected Behavior
As a library, I would expect it to add any dependencies it needs, but not limit the developer to a specific DI container/pattern

I'd be happy to contribute a PR to this end.

**Comment by nwhitmont** [comment]
@damienpontifex For reference, are you using .NET or Node SDK?

**Comment by damienpontifex** [comment]
@nwhitmont .NET

**Comment by JasonSowers** [comment]
@damienpontifex Since you pointed out you are willing to, I think the best plan is to submit it as a pull request. This way we can let the SDK developers make a decision without an immense amount of added work.  Please continue the conversation here and let us know if that is the route you decide to go.

**Comment by damienpontifex** [comment]
@JasonSowers I looked into this and it is a big change that touches every project! At this stage I don't have the time to invest when we were just evaluating. My outcome was that the bot framework is trying to be an application unto itself, rather than another component on in our Web API. We will look at other alternatives to be able to add bot capabilities to our API. Thanks for considering this request anyway.

**Comment by JasonSowers** [comment]
@damienpontifex If only we could write software to make more hours in the day :) best of luck to you!
