### ISSUE TITLE
[Question] Pricing if any for using Microsoft Bot Framework

### ISSUE THREAD

**Issue by sajjanhubale** [Microsoft/BotBuilder#2844]
Hello Team,

I am working on a chat bot using Microsoft bot framework. Can you let me know whether there is any charge for using the bot framework as we are planning to deploy this chat bot on production system ?

**Comment by stevengum97** [comment]
As a polling question, which SDK are you planning on using, C# or NodeJS?

If you use LUIS, other Cognitive Services, or Azure Bot Service for hosting you will have pay for exceeding the free tier or when using the paid plans.

Using the SDK itself will not incur any charges.

**Comment by sajjanhubale** [comment]
Thank you for your reply..
I am using  NodeJs as a SDK and api.ai for Natural language processing.
I have  designed Web application which  is using WebChat channel.
How to deploy this so that other users can make use of it.

**Comment by supra28** [comment]
You can deploy it like any other nodejs application. There are plenty of good tutorials on youtube out there.

**Comment by nwhitmont** [comment]
@sajjanhubale Here is some additional information on [deploying your bot to the cloud](https://docs.microsoft.com/en-us/bot-framework/deploy-bot-overview)

**Comment by sajjanhubale** [comment]
Sorry to bother you all again and again. I am not concerned about the deployment thing right now. It's like  I have used webchat channel and microsoft bot framework in node.js.

Now I just want to know whether these services/tools can be used for free or once I deploy it they will be charged apart from the charges for the deployment by other cloud platforms.

Any help is appreciated. Thanks in advance. (Also I am not thinking right now to deploy it on Azure, instead I may choose any other cloud platforms.

**Comment by sasivarnan** [comment]
I am also having some queries regarding pricing.
I am trying to use Node.js for building a bot using Bot Builder SDK and planning to host it on my own.
Will there be any charge for using the Bot Framework only for integrating various bot channels?
It would be nice to have a documentation on this. Thanks in advance.

**Comment by omkarrajmane** [comment]
Any clarity on this ?

**Comment by p0358** [comment]
@nwhitmont @stevengum Can I create a Bot Channels Registration (as I understand, it costs nothing if I host it myself) without activating Azure free trial? It will give me 200 USD for 30 days and services for 12 months, but I don't want to activate it since I don't plan on using it for now, and I don't want it all to expire totally unused... I'm trying to add it on https://portal.azure.com/ and it prompts me to create free account. Any solution to this? Couldn't find any answer yet.

**Comment by EricDahlvang** [comment]
@p0358 An Azure subscription is required in order to create a Bot Channels Registration.
