### ISSUE TITLE
[Question]How to use conversationData when developing on node.js

### ISSUE THREAD

**Issue by liangstein** [Microsoft/BotBuilder#2847]
How to write variables into conversationData when developing using node.js. Compared to userData, i can write string by session.userData.name=***. Is it similar when writing strings into conversationData?

The Microsoft document on node.js isn't detailed enough.

**Comment by aakashkag** [comment]
Property	Key	Description
User	User Id	Remembering context for a user on a channel
Conversation	Conversation Id	Remembering context all users in a conversation
Private Conversation	Conversation Id + User Id	Remembering context for a user in a conversation
