### ISSUE TITLE
[Question] bot not sending message in basic setup, botbuilder@3.8.3

### ISSUE THREAD

**Issue by suzyahyah** [Microsoft/BotBuilder#2849]
## Pre-flight checklist
- [x] I have [searched the existing issues](https://github.com/Microsoft/BotBuilder/issues?utf8=%E2%9C%93&q=is%3Aissue) before logging a new one.
---------------------------

## System Information (Required)
* SDK Platform: Linux/Ubuntu
* SDK Version: botbuilder 3.8.3, restify 4.3.0, node 0.10.25
* Development Environment: localhost | ngrok server

## Issue Description
The bot registers the POST message but does not send back a response in emulator. Same problem when testing on ngrok server and for localhost.

## Example Code
The code is exactly as in the official documents: https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-use-default-message-handler

````js
var restify = require('restify');
var builder = require('botbuilder');

var server = restify.createServer();
server.listen(process.env.port || process.env.PORT || 3978, function () { });

// Create the chat connector for communicating with the Bot Framework Service
var connector = new builder.ChatConnector({
    appId: process.env.MICROSOFT_APP_ID,
    appPassword: process.env.MICROSOFT_APP_PASSWORD
});

// Listen for messages from users 
server.post('/api/messages', connector.listen());

// Create your bot with a function to receive messages from the user
var bot = new builder.UniversalBot(connector, function (session) {
    // echo the user's message
    session.send("You said: %s", session.message.text);
}); 

````
## Actual Results
Expected "You said ...", but no response posted and no error message.

![image](https://cloud.githubusercontent.com/assets/2980993/26545335/c8700e80-4497-11e7-8f7a-bb440735460b.png)

**Comment by nwhitmont** [comment]
@suzyahyah I noticed you are using a very, very old version of Node.js.  I recommend upgrading your Node.js installation to v6.10.3 LTS or v7.10.0 (current). Let me know if the problem persists after upgrading Node.js.

**Comment by suzyahyah** [comment]
I upgraded to v7.10.0, Thanks it works now!
