### ISSUE TITLE
FormOptions in Luis Filled Forms

### ISSUE THREAD

**Issue by ahmettaha** [Microsoft/BotBuilder#285]
Hello,

I couldn't find the effects of FormOptions in Luis filled forms in the documentation. Where are they explained? I also believe that they are flag enums. What does this mean for example?

PromptInStart | PromptFieldsWithValues

What happens, if I choose None, versus, one of them, versus a combination of them?

Thanks.

**Comment by chrimc62** [comment]
You can find out about PromptWithValues here: http://docs.botframework.com/sdkreference/csharp/forms.html#initialState and PromptInstart means your form starts with the initial message immediately as opposed to waiting for a message.
