### ISSUE TITLE
[Question] Charges for any for using Microsoft Bot Framework in Node.js and WeChat channel 

### ISSUE THREAD

**Issue by sajjanhubale** [Microsoft/BotBuilder#2853]
I have used webchat channel and microsoft bot framework in node.js to make ChatBot.

Now I just want to know whether these services/tools can be used for free or once I deploy it they will be charged apart from the charges for the deployment by other cloud platforms.

Any help is appreciated. Thanks in advance. (Also I am not thinking right now to deploy it on Azure, instead I may choose any other cloud platforms.

**Comment by nwhitmont** [comment]
@sajjanhubale The Bot Framework SDK, aka BotBuilder, is [open source software](https://opensource.com/resources/what-open-source) provided under the [MIT License](https://github.com/Microsoft/BotBuilder/blob/master/LICENSE). 

Additionally, Azure Bot Service is free to use. You pay only for the resources you consume. For more information about related service pricing see:
- Azure Functions - https://azure.microsoft.com/en-us/pricing/details/functions/
- Cognitive Services - https://azure.microsoft.com/en-us/pricing/details/cognitive-services/
- LUIS - https://azure.microsoft.com/en-us/pricing/details/cognitive-services/language-understanding-intelligent-services/
-  Azure - https://azure.microsoft.com/en-us/pricing/
