### ISSUE TITLE
[Question] onDefult Handler for unhandled utterances using LUIS

### ISSUE THREAD

**Issue by JoelReehe** [Microsoft/BotBuilder#2854]
Hi,
I want to give my bot a default dialog which catches every utterance that doesn't match an intent saying "I don't understand". Afterwars the conversation should go on an the bot should listen for new messages.

I've already seen it a lot in other bots. I've tryed using "onDefault()" but i can't figure out how to use it for my case since it it's just working with IntentDialog and not with LUIS.

I'd be glad if somebody helps me figure this out. Thank you

**Comment by ejadib** [comment]
All the details about the issue are empty; please fill them

**Comment by JoelReehe** [comment]
Sorry I hit enter before writing anything - updated now

**Comment by nwhitmont** [comment]
@JoelReehe are you using .NET or Node SDK?

**Comment by JoelReehe** [comment]
I'm using Node

Am 29.05.2017 11:35 nachm. schrieb "Nils" <notifications@github.com>:

**Comment by JoelReehe** [comment]
nobody?

**Comment by rettelx** [comment]
This will send "I don't understand" to the user if no intent matches.

```
//Setup IntentDialog with LUIS
const recognizer = new builder.LuisRecognizer(YOUR_LUIS_URL);
const dialog = new builder.IntentDialog({recognizers: [recognizer]});

//If no intent is recognized
dialog.onDefault(builder.DialogAction.send("I don't understand."));
```

**Comment by stevengum97** [comment]
@JoelReehe, if you provide your code you'll get better assistance. Besides the post by @rettelx, you can find an example in [`onDefault()`](https://github.com/Microsoft/BotBuilder-Samples/blob/27fc42278f1a3b681b75cc845a00f72475ca5f2e/Node/intelligence-Zummer/app.js#L70).

**Comment by JoelReehe** [comment]
Thanks! If I use the solution of @rettelx my other dialogs don't match anymore. This is a part of my code.

```
var bot = new builder.UniversalBot(connector)

//Create LUIS recognizer that points at our model
var model = 'My LUIS_URL';
var recognizer = new builder.LuisRecognizer(model);
bot.recognizer(recognizer);

//This doesn't work as dialog is not defined atm
dialog.onDefault(builder.DialogAction.send("Entschuldige das habe ich nicht verstanden."));

bot.dialog('/', function(session)
{
      session.beginDialog('/getName');
});

bot.dialog('/getName',[
    function(session,results){
        if(results && results.reprompt)
        {
            builder.Prompts.text(session,'Entschuldige, das habe ich nicht verstanden. Versuch es doch nochmal, dein Vorname reicht völlig');
        }
        else{
        builder.Prompts.text(session,"Hi, wie heißt du?");
        }
    },
    function(session,results,next){
        var name=results.response;
        var hasNumber = /\d/;
        
        if((hasNumber.test(name)==false)&&(name.includes(" ")==false))
        {
                session.userData.name=name;
                builder.Prompts.text(session, 'Hi '+ session.userData.name +', ich bin Searcho. Wie kann ich dir behilflich sein?');
        }
        else
        {   
            session.replaceDialog('/getName', { reprompt: true });
        }
    },
]);

//start searching for articles
bot.dialog('Artikelsuche', 
[
    function (session, results, next)
    {
            session.send("Ok, ich denke ich kann dir weiterhelfen.");
            session.replaceDialog('/geschlecht');
    }    
]).triggerAction({matches: 'Artikelsuche'});
```

**Comment by JoelReehe** [comment]
The problem with the second solution from @stevengum97 is, that my bot doesn't only listen through LUIS. I'm also using normal waterfall dialogs. So if I give the recognizer the intents to match like you did in the file under the link you've shared, every not unmatched dialog will result in calling up the onDefault method.

**Comment by JoelReehe** [comment]
I tryed this
````
var model = My_LUIS_Modell';
var recognizer = new builder.LuisRecognizer(model);
var dialog= new builder.IntentDialog({recognizers: [recognizer]})
bot.recognizer(dialog);

dialog.onDefault(builder.DialogAction.send("Entschuldige das habe ich nicht verstanden."));
````
Now the other Dialogs work again but instead of the default dialog the root dialog get's called when no intent is matched.

**Comment by stevengum97** [comment]
If you're using `IntentDialog` you should instead plug it into a dialog, the root dialog specifically:
```js
var recognizer = new builder.LuisRecognizer(model);
var intents = new builder.IntentDialog({ recognizers: [recognizer] }); 
// changed the name from 'dialog' to 'intents' 

bot.dialog('/', intents);

intents.onDefault(function (session, args) {
  session.replaceDialog('getName');
});

bot.dialog('getName', [...]);
```

In the code above you plug the IntentDialog into the root dialog so all activities (messages, attachments, etc.) go through that point.  This will allow any unmatched utterances to go to `intents.onDefault()` . When an intent isn't recognized the chatbot on default will redirect the user to the `'getName'` dialog.

**Comment by nwhitmont** [comment]
@JoelReehe Did @stevengum97 answer solve it?

**Comment by JoelReehe** [comment]
Yes, thanks @stevengum97

Am 06.06.2017 12:23 vorm. schrieb "Nils" <notifications@github.com>:

@JoelReehe <https://github.com/joelreehe> Did @stevengum97
<https://github.com/stevengum97> answer solve it?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/BotBuilder/issues/2854#issuecomment-306327588>,
or mute the thread

**Comment by stevengum97** [comment]
You're welcome! Closing Issue.
