### ISSUE TITLE
[Skype for Business] doesn't support FormFlow in Skype for Business channel.

### ISSUE THREAD

**Issue by Mikhail2k15** [Microsoft/BotBuilder#2856]
I have simple FormFlow. It works in other channel but doesn't work in SfB channel.
The same with PromptDialog.Text.

**Comment by Mikhail2k15** [comment]
Any pointer or confirmation regarding this issue?

**Comment by michaelhutchful** [comment]
You need to give more details, then we can help you. C# or Node? Have you debugged to see why it is not working?

Regards Michael

Sent from Mail for Windows 10
