### ISSUE TITLE
[Question] Direct Line throughput limit?

### ISSUE THREAD

**Issue by srozga** [Microsoft/BotBuilder#2858]
We are running some load tests on one of our bots and we wanted to look into when the bot will break. Our set up is a bit wacky for business reasons; we must connect the bot through the DirectLine , even though it will be exposed through Messenger. A third party owns the FB page, proxies messages over to a connector and we use the DirectLine to send messages to our bot and then back to the third party tool.

Everything works well, except that during our load tests we saw that it seemed we were getting slowed down by DirectLine. Once our load test generated > 2 requests per second, DirectLine slowed down on us. We actually has a "real" simulated scenario that was at about 80 or so users at that point messaging every so often. The actual data on the bot service indicated requests on the bot itself were being processed in the same amount of time, regardless of this behavior. In fact, we had a separate FB page connected directly to the bot via the Microsoft FB Connector, and the bot was not struggling to keep up at all.

So my questions are:
* Is there an actual throughput limit on the DirectLine that we are hitting? I assume it is a combination of # of requests and the length of time it takes the bot to respond. But what is it? Are we getting throttled? 
* If our bot does generate more user throughput than this limit, the current behavior will be that DirectLine will be backed up with the messages. From a user perspective, I assume it will just look as if messages are coming back more slowly but is there anything else we can do?
* We also seem to have observed a timeout on the DirectLine after 15 seconds when sending a message? Does this sound familiar? If so, can you shed more light on this?

Thanks!
-s

**Comment by nwhitmont** [comment]
@srozga are you using .NET or Node SDK?

**Comment by nwhitmont** [comment]
@srozga I'm not aware of any specific limitations on Direct Line API calls, and I couldn't find any mention of it in the [Direct Line v3 API docs](https://docs.botframework.com/en-us/restapi/directline3).

@dandriscoll Any additional considerations we should be aware of?

**Comment by srozga** [comment]
Everything is going through .Net. There may be something going on with the fact that the directline getsbcalled by our API and then the API calls directline again to retrieve the message and I wonder if there's any timing things that may be causing this. Thanks.

**Comment by nwhitmont** [comment]
Thanks for the update. I will dig for more details and setup a test scenario. Examples welcome

**Comment by fanidamj** [comment]
Hoping that issue has been resolved, closing it. Feel free to reopen if any questions.
