### ISSUE TITLE
Send multiple post ?

### ISSUE THREAD

**Issue by FordSoft** [Microsoft/BotBuilder#286]
Hello.

Why in the emulator when I call this code:
await context.PostAsync("1");
await context.PostAsync("2");
await context.PostAsync("3");
bot returns all three values (1,2,3) and webchat/telegram just the first (1)

How do I get all three values ?

ps
I sent three lines, just as an example. But it may be that when the child's dialogue end with the parent dialog does not continue ..

**Comment by willportnoy** [comment]
@eanders-MS is there a specific issue with the telegram channel and sending multiple messages?

When we send 3 messages, the first two are sent by way of IConnectorClient, and the last message is returned inline with the initiated http post.

We use the IConnectorClient to send messages and create the reply message with the connector's CreateReplyMessage.

**Comment by FordSoft** [comment]
In channels Skype, telegrams, webchat, I always get only one (first), sent a message of three.

**Comment by eanders-MS** [comment]
@willportnoy no issue that I'm aware of, but I will try to repro in Telegram.

**Comment by Stevenic** [comment]
@FordSoft are you properly configuring your App ID & App Secret. Those are used when post out of band so if they're not correct your second+ replies won't work

**Comment by tkbox9** [comment]
Yet on this topic. I'm trying the following:

await context.PostAsync("1");
await context.PostAsync("2");
await context.PostAsync(new Message
            {
                Text = "This is a test 3",
                ChannelData = JObject.Parse(escaped)
            });



Messages 1 and 2 are delivered however the message "This is a test 3" never gets to the user. (I've tried from Emulator and Messenger). No error is provided.

**Comment by willportnoy** [comment]
@FordSoft I'm adding some code to make it easier to specify the credentials for out of band messages to fix a similar issue: https://github.com/Microsoft/BotBuilder/issues/230

@tkbox9 you need to fill in more fields on the Message object - for example, the "to" field so the connector knows where to deliver the message.  IBotToUser.MakeMessage is how you should create a properly initialized Message based on replying to the incoming message.

**Comment by eanders-MS** [comment]
@willportnoy, @Stevenic I am able to repro this with Telegram. My bot looks like this:
var bot = new builder.BotConnectorBot(botConnectorOptions);
```
bot.add('/', function (session) {
    session.send("1");
    session.send("2");
    session.send("3");
});
```

Monitoring traffic into the Telegram channel, I can verify it only receives the first message: "1". "2" and "3" never arrive.

**Comment by FordSoft** [comment]
Thanks for reply, but the problem remained.
@Stevenic  I've set up  App ID & App Secret, publish application in azure website. But still only get the first message of the three.

**Comment by Stevenic** [comment]
@eanders-MS Did you configure the proper app id & secret. If those are configured it's likely something in the switch or telegram channel.

**Comment by eanders-MS** [comment]
@Stevenic Yes, they're configured correctly. This is a test bot I've been using for some time. Just thinking aloud: If one send were a synchronous response to the incoming request, while the others were independent, asynchonous posts, that might trigger different behavior in the switch.

**Comment by Stevenic** [comment]
Yes... Might have Tom or Craig try to track it through the switch. It should definitely be getting posted back through the switch as all of the other channels seems to be working ok.

**Comment by FordSoft** [comment]
Such behavior not only in the telegram, but also on Skype, faceebook messenger, webchat. Only in the emulator is ok.

**Comment by Stevenic** [comment]
I'll try to dig into this. I know this works on Kik as I've been sending multiple posts all week.

**Comment by FordSoft** [comment]
Hello, any information update?

**Comment by FordSoft** [comment]
cool with the latest commits this to work, thank you!
