### ISSUE TITLE
[Question] Azure Push Notification in Azure Web Job through Power shell ( Bot web app )

### ISSUE THREAD

**Issue by AmitavaSinha** [Microsoft/BotBuilder#2861]
## Pre-flight checklist
- [ ] 
---------------------------

## System Information (Required)
* SDK Platform: Powershel
* SDK Version: 
* Development Environment:  Azure App Service ( Web Job)

## Issue Description
Connect-MsolService is not recognized while running the Powershell script ( try to get Azure AD details) in Azure Web job 

## Example Code
import-module MSOnline

$username = "**********"
$pass = ConvertTo-SecureString "PWD" -AsPlainText –Force
$cred = New-Object -TypeName pscredential –ArgumentList $username, $pass
Connect-MsolService -credential $cred

$groupOfUsers = Get-MsolUser -MaxResults 40 | where {(New-TimeSpan -start (get-date) -end ($_.LastPasswordChangeTimestamp.adddays(50))).Days -le 5  } | Select-Object DisplayName, PhoneNumber, @{Name="DaystoExpiry"; Expression={(New-TimeSpan -start (get-date) -end ($_.LastPasswordChangeTimestamp.adddays(50))).Days}}
## Steps to Reproduce
1.run this powershell script in Azure function
2.
3.

## Expected Behavior
This should connect the MSOLService and get the Azure AD details

## Actual Results
Getting error "Connect-MsolService cmdlet is not recognized "

**Comment by nwhitmont** [comment]
@AmitavaSinha Are you using .NET or Node.js SDK for BotBuilder?

I don't understand your problem.  How does this issue relate to Bot Framework SDK?
