### ISSUE TITLE
[Question] Add microphone button to record speech?

### ISSUE THREAD

**Issue by msBot1111** [Microsoft/BotBuilder#2864]
I want to add microphone button in my asp.net core app, and to record speech and then using the bing speech-to-text API to convert it to text. I know the implementation of the API but I don't know how to add microphone in the view and then to use the API. I want to create something similar to google keyboard microphone.

**Comment by nwhitmont** [comment]
@msBot1111 Can you provide some context for your project? How does this relate to Bot Framework specifically?

**Comment by msBot1111** [comment]
It's not related to Bot Framework. It's core app.
