### ISSUE TITLE
[Question] Bots recently stopped responding via telegram

### ISSUE THREAD

**Issue by kneuLIL** [Microsoft/BotBuilder#2866]
## System Information (Required)
* SDK Platform: C#
* SDK Version: 3.8.1.0
* Development Environment: Azure Bot Service

## Issue Description
 The bot is not able to answer the user via telegram. Below I've listed versions of responding we tried, all result in the same ServiceError. 
The bots stopped responding within the last 24 hours. They stopped without any deployment or action on our end. Redeploying the project or restarting the machine did not help. The bots do respond like expected in other user channels like directline or skype.

## Example Code

                connector.Conversations.ReplyToActivityAsync(activity)
------------------------------------------
                var message = Activity.CreateMessageActivity();
                message.From = botAccount;
                message.Recipient = userAccount;
                message.Conversation = new ConversationAccount(id: conversationId);
                message.Text = text;
                message.Locale = languageCode;
                message.Attachments = attachments;

                var response = await connector.Conversations.SendToConversationAsync((Activity)message);

-----------------------------------------------
                PromptDialog.Choice(context, AfterLanguageChoicePrompt, new List<string>() {germanOption, englishOption}, "Please choose a language.", attempts: 100, promptStyle: PromptStyle.Auto);

## Steps to Reproduce
1. Write a sample bot.
2. Deploy in Azure
3. Create telegram account for the bot
4. Write the bot a message

## Expected Behavior
The bot answers with whatever message you coded as answer.

## Actual Results
The bot does not answer because it seems that the bot connector fails to send the message to the telegram api. 
![image](https://cloud.githubusercontent.com/assets/29102057/26642385/d40b3f98-462d-11e7-9736-e9c34ae3c90a.png)
![image](https://cloud.githubusercontent.com/assets/29102057/26642462/1931e64e-462e-11e7-8624-719e5454df75.png)
![image](https://cloud.githubusercontent.com/assets/29102057/26642502/3fde785c-462e-11e7-80c6-d91d500bf3c1.png)

## Additional Information
Reconstructing the call in postman gives the following result.
![image](https://cloud.githubusercontent.com/assets/29102057/26642883/b24b5ec2-462f-11e7-81de-eff0b1d64592.png)

**Comment by maximilianlorent** [comment]
Hi everbody,

unfortunately we are experiencing the same issue. All of our bots which are using Telegram started working within the last few hours.

We experience the same behaviour as @kneuLIL. I only would like to add that we also have tried the following:

We tried to remove the Telegram user channel from one of our bot as our hope was that after readding the user channel it would work again. Unfortunately when we tried to readd the user channel we get the following error message:

![telegram channel adding error](https://cloud.githubusercontent.com/assets/19322035/26643135/9e685ca6-4630-11e7-9e48-68b4dfc5ca66.png)

We have not changed anything with our bots. They really just stopped working via Telegram Channel. So I also assume that it must be an issue in the bot connector.

**Comment by nwhitmont** [comment]
@kneuLIL @maximilianlorent Thanks for reporting! We are actively investigating the issue....

**Comment by nwhitmont** [comment]
@kneuLIL @maximilianlorent Looks like Telegram API is having some issues. They [reported an API outage earlier today on Twitter](https://twitter.com/telegram/status/869870878393348096)

**Comment by maximilianlorent** [comment]
Hi everybody,

thanks a lot for investigation. I can confirm that for our bots since 17:45 UTC everything is working fine again. I wish everybody else that DNS caching problems will disappear soon, so that also your bots will be working again with Telegram.

**Comment by nwhitmont** [comment]
https://status.botframework.com/incidents/g84q8p4sgz2b
>We have identified that api.telegram.org is not resolving in Europe. We have routed our traffic to other data centers until Telegram resolves their issue.
Posted about 1 hour ago. May 31, 2017 - 10:17 PDT

**Comment by kneuLIL** [comment]
Thanks a lot for the support and information, our bots started working again.

**Comment by Toadill** [comment]
I am having this same problem in the USA I have not changed anything with the bot. The bot just stopped responding. I have tried getting a new token from bot father but this did not solve the problem.

**Comment by EricDahlvang** [comment]
Hi @Toadill  

This is a closed issue, and closed issues are not monitored by the team.  Please open a new issue in the sdk repository you've developed the bot with, providing the Bot Handle and as much information as possible regarding the error.

V3: https://github.com/microsoft/BotBuilder-V3
V4 dotnet: https://github.com/microsoft/botbuilder-dotnet
V4 javascript: https://github.com/microsoft/botbuilder-js
