### ISSUE TITLE
Web chat control on Safari and apple devices

### ISSUE THREAD

**Issue by AndyEdmonds** [Microsoft/BotBuilder#287]
I have a web chat control that accesses my DarlBot on the front page of my site, http://www.docandys.com. I have accessed it from Edge, FireFox, Chrome on PC, Android and windows phone and the system performs as expected, i.e. messages are correctly passed through to the Bot and it passes through it's expected sequences.
On safari on IPad the process freezes. I have not had the chance to investigate messages yet, but there is clearly a difference in behaviour.

[addition]
Looking with ApplicationInsights and setting exception handling around everything in the MessageController Post method the exception appears to be outside this and is reported as below:

‎15‎/‎05‎/‎2016‎ ‎22‎:‎22‎:‎56 - Exception

A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.

Exception type: System.NullReferenceException

Failed method: System.Web.ThreadContext.AssociateWithCurrentThread

Problem Id: System.NullReferenceException at System.Web.ThreadContext.AssociateWithCurrentThread

Severity level: Critical

**Comment by willportnoy** [comment]
That particular exception occurs when the code has an instance of a Task that was marked as "failed", but no code actually observed its Exception property before that Task instance was lost to the garbage collector, and the garbage collector's finalizer thread decided to take down the process.  (this behavior was changed in later versions of the .NET framework)

It would be interested to see where the NullReferenceException originally occurred in the code - can you break on thrown exceptions and find the call stack?

**Comment by AndyEdmonds** [comment]
Hi Will, The .Net framework is 4.6 and the Bot connector and builder are the most recent.  I tried to set a try/catch at the outermost level of the MessagesController POST, and am not catching it in ApplicationInsights. All we get is the exception above and the uninformative contents. We've tried the web control with every variation of browser and platform we can, and everything works that is not Safari, and all Safari versions fail, whether iPhone, iPad or MacBook.

**Comment by AndyEdmonds** [comment]
Further thoughts:
The crash happens on the second interaction. The bot is intended to demo various expert systems that illustrate our rule language and inference system. In the first screen you get to choose one of the demos. In the second the chosen expert system is loaded in the back end and a much smaller state message is passed to the bot and gets serialized. The Json for the first step is 3480 chars, the next step's json is 4001 chars. Is some size threshold for Safari being exceeded?

**Comment by willportnoy** [comment]
Maybe it's a timing issue with Safari?  It seems likely that you're spawning an asynchronous task and not waiting for its completion:

http://stackoverflow.com/a/20365859
