### ISSUE TITLE
[Question] Pulling Title/Subtitle/Text from Hero Cards after Button Click?

### ISSUE THREAD

**Issue by JoelReehe** [Microsoft/BotBuilder#2875]
hey everybody,

I'm struggling to exctract information from hero cards. I want to f.e. save the title of a card after the button was hit, but I can't figure out how to access the information inside of the hero card.

If I call session.message.text for the example card below, it only returns the String of the Button - in this case 'Artikel kaufen'. But I want to get the title - is this even possible?

```js
msg.attachmentLayout(builder.AttachmentLayout.carousel)

msg.attachments([

new
builder.HeroCard(session)

.title('Nike Girls Sneaker - Roshe One')

.subtitle('High Performance Sneaker')

.text('Some text')

.images([builder.CardImage.create(session,
'some.jpg')])

.buttons([builder.CardAction.postBack(session,
'Artikel kaufen',
'In den Warenkorb legen')])


session.send(msg);
```

**Comment by chetanmekha** [comment]
@JoelReehe  try with below logic, it will resolved your problem,
`
var array = [];
var heroCard= new builder.HeroCard(session);
            heroCard.title(playCorousalType[count]);
            heroCard.images([builder.CardImage.create(session, url)]);
            // heroCard.tap(builder.CardAction.openUrl(session, url));
            heroCard.buttons([builder.CardAction.imBack(session, 'Artikel kaufen', "Select")]);
            array.push(thumbnailCard);
        }

        if (array != undefined && array.length > 0) {
            var msg = new builder.Message(session)
                .textFormat(builder.TextFormat.xml)
                .attachmentLayout(builder.AttachmentLayout.carousel)
                .attachments(array);
            builder.Prompts.choice(session, msg, 'Artikel kaufen');`

**Comment by nwhitmont** [comment]
@JoelReehe Check out this article on [Handling button input](https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-send-rich-cards#handle-button-input).

When you click on a button there is no "event handler" as you might expect in a traditional web application.  The button click sends a message to your bot, so you need to set up a dialog configured with a trigger action. Essentially, you do this by using a keyword in your button `imBack` message, such as "buy" or "kaufen".

>The following example shows a bot for a fictional t-shirt company and shows how to send a carousel of cards in response to the user saying “show shirts”.

```js
// Create your bot with a function to receive messages from the user
// Create bot and default message handler
var bot = new builder.UniversalBot(connector, function (session) {
    session.send("Hi... We sell shirts. Say 'show shirts' to see our products.");
});

// Add dialog to return list of shirts available
bot.dialog('showShirts', function (session) {
    var msg = new builder.Message(session);
    msg.attachmentLayout(builder.AttachmentLayout.carousel)
    msg.attachments([
        new builder.HeroCard(session)
            .title("Classic White T-Shirt")
            .subtitle("100% Soft and Luxurious Cotton")
            .text("Price is $25 and carried in sizes (S, M, L, and XL)")
            .images([builder.CardImage.create(session, 'http://petersapparel.parseapp.com/img/whiteshirt.png')])
            .buttons([
                builder.CardAction.imBack(session, "buy classic white t-shirt", "Buy")
            ]),
        new builder.HeroCard(session)
            .title("Classic Gray T-Shirt")
            .subtitle("100% Soft and Luxurious Cotton")
            .text("Price is $25 and carried in sizes (S, M, L, and XL)")
            .images([builder.CardImage.create(session, 'http://petersapparel.parseapp.com/img/grayshirt.png')])
            .buttons([
                builder.CardAction.imBack(session, "buy classic gray t-shirt", "Buy")
            ])
    ]);
    session.send(msg).endDialog();
}).triggerAction({ matches: /^(show|list)/i });
```

> This example uses the Message class to build a carousel. The carousel is comprised of a list of HeroCard classes that contain an image, text, and a single button that triggers buying the item. Clicking the Buy button triggers sending a message so we need to add a second dialog to catch the button click.

> The buyButtonClick dialog will be triggered any time a message is received that starts with “buy” or “add” and is followed by something containing the word “shirt”. The dialog starts by using a couple of regular expressions to look for the color and optional size shirt that the user asked for. This added flexibility lets you support both button clicks and natural language messages from the user like “please add a large gray shirt to my cart”. If the color is valid but the size is unknown, the bot prompts the user to pick a size from a list before adding the item to the cart. Once the bot has all the information it needs, it puts the item onto a cart that’s persisted using `session.userData` and then sends the user a confirmation message.

```js
// Add dialog to handle 'Buy' button click
bot.dialog('buyButtonClick', [
    function (session, args, next) {
        // Get color and optional size from users utterance
        var utterance = args.intent.matched[0];
        var color = /(white|gray)/i.exec(utterance);
        var size = /\b(Extra Large|Large|Medium|Small)\b/i.exec(utterance);
        if (color) {
            // Initialize cart item
            var item = session.dialogData.item = { 
                product: "classic " + color[0].toLowerCase() + " t-shirt",
                size: size ? size[0].toLowerCase() : null,
                price: 25.0,
                qty: 1
            };
            if (!item.size) {
                // Prompt for size
                builder.Prompts.choice(session, "What size would you like?", "Small|Medium|Large|Extra Large");
            } else {
                //Skip to next waterfall step
                next();
            }
        } else {
            // Invalid product
            session.send("I'm sorry... That product wasn't found.").endDialog();
        }   
    },
    function (session, results) {
        // Save size if prompted
        var item = session.dialogData.item;
        if (results.response) {
            item.size = results.response.entity.toLowerCase();
        }

        // Add to cart
        if (!session.userData.cart) {
            session.userData.cart = [];
        }
        session.userData.cart.push(item);

        // Send confirmation to users
        session.send("A '%(size)s %(product)s' has been added to your cart.", item).endDialog();
    }
]).triggerAction({ matches: /(buy|add)\s.*shirt/i });
```
