### ISSUE TITLE
[Bug] ChatConnector v3.1 emulator authentication fails

### ISSUE THREAD

**Issue by boardofchris** [Microsoft/BotBuilder#2878]
## System Information (Required)
* SDK Platform: Node 
* SDK Version: ?
* Development Environment: localhost 

## Issue Description
The [authentication reference documentation](https://docs.microsoft.com/en-us/bot-framework/rest-api/bot-framework-rest-connector-authentication#security-protocol-changes) version 3.1 differs from the implementation. As a result, version 3.1 emulator authentication attempts fail.

## Example Code
BotBuilder/Node/core/src/bots/ChatConnector.ts Line 106, 107

emulatorAudience: 'https://sts.windows.net/d6d49420-f39b-4df7-a1dc-d59a935871db/',
emulatorIssuer: this.settings.appId,

## Steps to Reproduce
1. Code inspection 

## Expected Behavior
The token contains an "issuer" claim with value of https://sts.windows.net/d6d49420-f39b-4df7-a1dc-d59a935871db/.
The token contains an "audience" claim with a value equal to the bot's Microsoft App ID.

## Actual Results
The issuer and audience fields are reversed.

**Comment by eanders-MS** [comment]
The emulator sends using v3.0 auth in order to remain compatible with bots built on older SDKs while we phase out v3.0 authentication. The BotBuilder SDKs can receive emulator messages using v3.0 or v3.1 authentication.

What is the failure you're seeing?

**Comment by nwhitmont** [comment]
For more information on the security protocol changes see: https://docs.microsoft.com/en-us/bot-framework/rest-api/bot-framework-rest-connector-authentication#security-protocol-changes

**Comment by nwhitmont** [comment]
@boardofchris Did @eanders-MS comments in [BotFramework-Emulator #213](https://github.com/Microsoft/BotFramework-Emulator/issues/213) answer your question?

**Comment by boardofchris** [comment]
Yes, @eanders-MS explained why 3.1 authentication is not fully implemented in the emulator.

**Comment by nwhitmont** [comment]
@boardofchris thanks for the update
