### ISSUE TITLE
Field does not expand the choices with the {||} pattern in the prompt 

### ISSUE THREAD

**Issue by jakobpn** [Microsoft/BotBuilder#288]
I am using the following code to define a string field with a fixed set of choices:

```
   public class SelectWorksheetForm
    {
        public static string[] Worksheets;
        public string WorksheetName;

        public static IForm<SelectWorksheetForm> BuildForm()
        {
            return new FormBuilder<SelectWorksheetForm>()
                .Field(new FieldReflector<SelectWorksheetForm>(nameof(WorksheetName))
                    .SetType(null)
                    .SetActive((state) => true)
                    .SetDefine(async (state, field) =>
                        {
                            foreach (var worksheet in Worksheets)
                            {
                                field
                                    .AddDescription(worksheet, worksheet)
                                    .AddTerms(worksheet, worksheet);
                            }
                            field
                                .SetPrompt(new PromptAttribute("Which worksheet do you want to work with? {||}"));
                            return true;
                        })
                    )
                .Build();
        }
    };
```

The prompt will show "Which worksheet do you want to work with?", but not the available choices. The field accept the choices available in the Worksheets array.

Any ideas on what is going on?

Jakob

**Comment by chrimc62** [comment]
Are you testing this through the emulator?  If so, then this most likely because you need to update it.  We added support for buttons which the old emulator did not know how to render into text.  You should find it works fine in other channels or if you upgrade.

**Comment by jakobpn** [comment]
Yes. This was by testing in the emulator. Updating it to the latest version helped. Thanks!

**Comment by jakobpn** [comment]
I'm surprised that the ChoiceFormat is something like "* ({0}) {1}" which makes the choices render like this:

```
•	(1) Sheet1
•	(2) Sheet2
•	(3) Sheet3
```

instead of...

```
1. Sheet1
2. Sheet2
3. Sheet3
```

**Comment by chrimc62** [comment]
That is because those are buttons and the emulator choose to render them that way.  If you change your choice style to autotext you will get the old behavior.

Sent from Outlook<https://aka.ms/liysn4> on Android



On Tue, May 17, 2016 at 6:50 AM -0700, "Jakob Nielsen-MSFT" <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes. This was by testing in the emulator. Updating it to the latest version helped. Thanks!

-

**Comment by jakobpn** [comment]
OK. Good to know. Is there more documentation on the topic of buttons? For example, which channels currently support them and how?

**Comment by chrimc62** [comment]
All channels support “buttons”—it is up to them how they interpret them.  There is a lot of variation in capabilities.  I think they are currently supported by Facebook, Slack and Telegram, but Lars would know for sure.

**Comment by chrimc62** [comment]
Facebook and Telegram.  For text only channels buttons are displayed as text.


1)      Hamburger

2)      Fries

3)      Nuggets

In the schema they are referred to as “Actions”

  {
        "type": "Message",
        "attachments": [
            {
               "text": "Pick one:",
                "actions": [
                    {
                        "title": "Willy's Cheeseburger",
                        "message": "CB"
                    },
                    {
                        "title": "Curley Fries",
                        "message": "F"
                    },
                    {
                        "title": "Chocolate Shake",
                        "message": "S"
                    }
                ]
            }
        ]
    }




From: Chris McConnell
Sent: Tuesday, May 17, 2016 4:19 PM
To: Microsoft/BotBuilder <reply@reply.github.com>; Microsoft/BotBuilder <BotBuilder@noreply.github.com>
Cc: State change <state_change@noreply.github.com>; Lars Liden <Lars.Liden@microsoft.com>
Subject: RE: [Microsoft/BotBuilder] Field does not expand the choices with the {||} pattern in the prompt (#288)

All channels support “buttons”—it is up to them how they interpret them.  There is a lot of variation in capabilities.  I think they are currently supported by Facebook, Slack and Telegram, but Lars would know for sure.
