### ISSUE TITLE
[Feature Request] Prompts.choice # retry prompt - shows retry message but does not prompt choices again

### ISSUE THREAD

**Issue by sharmadine** [Microsoft/BotBuilder#2880]
## Pre-flight checklist
done
---------------------------

## System Information (Required)
* SDK Platform: Node.js
* SDK Version: 3.8.3
* Development Environment: **localhost** | Azure Bot Service | **Azure App Service** | other
**localhost and azure aoo service**

## Issue Description
Describe the issue here.

**Choice** prompt - If I type a value not in the the choice option list, the Prompt dialog only shows the Retry Message. It does not prompt the values again for selection. This is breaking our Facebook Bot. Downgrading the version to 3.7.0 make things works again. Snapshots below:
```js
builder.Prompts.choice(session, "Choose", "m1|m2", {
            retryPrompt: "invalid choice, please pick you choice",
            listStyle: builder.ListStyle.button,
            maxRetries: 2
});
```

Snapshot attached.

![image](https://cloud.githubusercontent.com/assets/2290501/26740846/cb963f66-47f4-11e7-9116-d7b3a06bb56d.png)

## Example Code
The complete bot code that reproduces the issue.

## Steps to Reproduce
1. Code sample above
2. image snapshot uploaded

## Expected Behavior
What you expected to happen.

RETRY on a Choice Prompt dialog should show the retry message along with options for selection.

## Actual Result
What actually happened. Please give examples and support it with screenshots, copied output or error messages.

Explained above with snapshot.

**Comment by nwhitmont** [comment]
@sharmadine thanks for reporting. we will log this as a feature request.

**Comment by sharmadine** [comment]
@nwhitmont thanks. But it seems to be an issue and not feature enhancement because it works below version 3.7.0 of botbuilder.

**Comment by nwhitmont** [comment]
@sharmadine the prompts system was re-written for the v3.8.0 release of botbuilder.  The current functionality, eg. showing the retry message without the options, is the expected behavior.

**Comment by sharmadine** [comment]
oh, this has broken the FB experience completely because FB does not retain the choice buttons as the case with Skype, which leaves user with no options to choose from :-( How can it be overridden to attain pre v3.8.0 behavior?

**Comment by nwhitmont** [comment]
@sharmadine use botbuilder@3.7.0 if you need this re-prompt behavior.

**Comment by radennis** [comment]
We also prefer the old behavior. Is there some uservoice where we can vote for it? Seems several people have been requesting for it.

We cannot downgrade to 3.7.0 since we need 3.8.0 new features and bug fixes…

**Comment by stevengum97** [comment]
Hi @radennis and @sharmadine, we're currently looking into this and will update with new pertinent info as it arises.

**Comment by stevengum97** [comment]
@sharmadine @radennis,  a fix for the issue, [**PR #2936**](https://github.com/Microsoft/BotBuilder/pull/2936), has been created and is pending approval for a merge. 

Thank you for your patience and understanding.

**Comment by radennis** [comment]
Thank you for looking into it!

**Comment by garyfungwelab** [comment]
I am doing like this:
```
builder.Prompts.choice(session, "Choose", "m1|m2", {
            maxRetries: 0
});
```
and handle it manually:
```
(session, results, next) => {
 if (!results.response) {
  // start over here
 return;
 }
}
```

**Comment by sharmadine** [comment]
@stevengum97 would you know the timeframe of having the botbuilder version with the dialog fix?

**Comment by maba4891** [comment]
@sharmadine upgrading to the recent version 3.9.0 fixed it for me

**Comment by nwhitmont** [comment]
This issue is closed. If you have a question or problem, please open a new issue at: https://github.com/microsoft/botbuilder/issues/new 👍
