### ISSUE TITLE
[Bug] Gender of Skype calling bot is always female

### ISSUE THREAD

**Issue by camer314** [Microsoft/BotBuilder#2885]
## System Information (Required)
* SDK Language: .NET
* SDK Version: 3.8.1
* Development Environment: AZURE APP SERVICE

## Issue Description
Skype calling bot Prompt Gender is always female even if you specify Male

## Code Example
prompt = new Prompt { Value = text, **Voice = VoiceGender.Male**, Emphasize = true };

## Steps to Reproduce
1. Create a Skype calling bot
2. Try and use a Male voice in prompt
3.

## Expected Behavior
If the enumeration exists to choose gender I would expect it to work

## Actual Results
The voice is always female

**Comment by JasonSowers** [comment]
@camer314 are you able to upgrade to the current SDK version 3.8.1 at the time of writing this?

**Comment by camer314** [comment]
Apologies, the SDK version in 3.8.1 but the Skype Calling version is 3.0.4 - both which are most recent

**Comment by JasonSowers** [comment]
please let us know if you are still experiencing this issue

**Comment by james60338** [comment]
Hi, I am using the latest SDK which updated by NuGet package manager on Visual Studio 2017.I have the same issue with the code:

 `var prompt = new Prompt { Value = text, Voice = VoiceGender.Male}`

The voice gender of the IVR bot is always Female.
Please help, thank you.
