### ISSUE TITLE
[Feature Request] Support all Bing Text to Speech voices in Skype calling bot

### ISSUE THREAD

**Issue by camer314** [Microsoft/BotBuilder#2886]
## System Information (Required)
* SDK Language: .NET
* SDK Version: 3.0.4
* Development Environment: AZURE APP SERVICE

## Issue Description
I would like to see the Skype calling bot support all the voice options available to the Bing Text to Speech API. At the moment to get a more natural voice i need to call this API direct, save the WAV and then pass that back to the Skype API which is onerous and time consuming

**Comment by IoTGirl** [comment]
Hi @camer314 

Dev.Skype.Com recently published how to [convert text to speech in a skype bot ](https://devblog.skype.com/blogs/2017/10/06/convert-text-voice-skype-bot/) and this shows both a local and Bing option.

In the bing configuration, it uses `("<voice xml:lang='en-US' name='Microsoft Server Speech Text to Speech Voice (en-US, JessaRUS)'>"); `

Would this SSML designation meet your need?

Sincerely,
IoTGirl

**Comment by frankkilcommins** [comment]
It helps but there should be some focus with aligning the messaging and calling classes. Prompts should be aligned as much as possible. Right now we basically have to have two separate bots to support IM and calling on the same channel. 

I'd also like to see an ability for FormDialogs to be automatically usable in the calling scenario too. Right now its a bit cumbersome to create the various calling trees to manage the different navigational paths

**Comment by frankkilcommins** [comment]
@JasonSowers i see you closed. Does this mean its fixed or scheduled to be included in the master or....? Could you let me know?

**Comment by IoTGirl** [comment]
Hi @frankkilcommins,
As TTS is available your original feature request seems to be addressed.  If there is a bug with that feature you will need to provide full details on how it is repeatable and what scenario it impacts.  If that is the case, I suggest you create a new issue with the full details so others can clearly identify the problem you are having.
Sincerely,
IoTGirl

**Comment by EricDahlvang** [comment]
Also, check these out: 
https://devblog.skype.com/blogs/2017/10/06/convert-text-voice-skype-bot/
https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-real-time-media-concepts?view=azure-bot-service-3.0
