### ISSUE TITLE
[Question] response time interval in microsoft bot

### ISSUE THREAD

**Issue by JajatiMohanta** [Microsoft/BotBuilder#2887]
Hi,
Can we set response time interval manually in Microsoft Bot..??
Ex-Can we set reminder ,alarm in Bot Framework??
Thanks,
Jajati

**Comment by nwhitmont** [comment]
@JajatiMohanta are you using .NET or Node SDK?

**Comment by JasonSowers** [comment]
@JajatiMohanta have you taken a look at this? https://github.com/Microsoft/BotBuilder/tree/master/CSharp/Samples/AlarmBot

**Comment by JasonSowers** [comment]
@JajatiMohanta   This would be possible in theory.  You can save the messaging history to a DB with a timestamp.  If the timestamp is longer than a predetermined time you could not show the conversation history.  If you wanted to you could delete/purge the conversation data after a given amount of time.

**Comment by nwhitmont** [comment]
Hi @JajatiMohanta It sounds like you are asking about proactive bot messages. 

For more information on proactive messaging:
- [.NET SDK - Send proactive messages](https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-proactive-messages)
- [Node SDK - Send proactive messages](https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-proactive-messages)
- Azure Bot Service - [Proactive Bot Template app](https://docs.microsoft.com/en-us/bot-framework/azure/azure-bot-service-template-proactive)
- [YouTube: Proactive Bot](https://www.youtube.com/watch?v=Yn40KxaRUR8) - A proactive bot which message user when a new file is been added to SharePoint library
- Blog article: [Sending Proactive Botframework Messages](https://www.robinosborne.co.uk/2017/01/02/sending-proactive-botframework-messages/)
- Blog article: [How to create Proactive Bot with Microsoft Bot Framework](https://www.codeproject.com/Articles/1176637/How-to-create-Proactive-Bot-with-Microsoft-Bot-Fra)
