### ISSUE TITLE
BotConnector code block formatting issue

### ISSUE THREAD

**Issue by anthonyn60** [Microsoft/BotBuilder#289]
I'm using BotConnector with Slack and I'm running into some formatting issues specifically with code blocks. I append and prepend the code block with the triple backticks as I'm supposed to for Slack, but this results in weird behaviour. Often times, it messes up the indentation and the newlines. Sometimes it does not give me the message in a code block at all.

Here's an example:

The raw text sent looks like this:
![image](https://cloud.githubusercontent.com/assets/6720451/15279057/45c7a61a-1aee-11e6-8065-5a8db524e987.png)

Result in Slack (BotConnector):
![image](https://cloud.githubusercontent.com/assets/6720451/15278966/267ea8f4-1aed-11e6-8c19-128c21ef80fc.png)

I switched from BotConnector to the native BotKit library for Slack and it gives proper formatting (still using BotBuilder though). 
![image](https://cloud.githubusercontent.com/assets/6720451/15279060/622454b6-1aee-11e6-94e7-63159d082517.png)

Could be an issue with BotConnector adding additional encoding.

**Comment by LarsLiden** [comment]
Looks like a bug.  We'll investigate

**Comment by LarsLiden** [comment]
Anthony, can't repro.  One thing to remember is to use a double "\n" for a new line.

This:
"```#code comment\n\nFor element in sequence:\n\n#code to perform\n\n# Loop behavior\n\nFor each\n\n# Code to execute\n\n```"

Results in:
![image](https://cloud.githubusercontent.com/assets/6528486/15412390/fb1a1652-1ddb-11e6-94ef-7d5d56dba855.png)
