### ISSUE TITLE
[Question] The Buttons are not appearing on Kik when using Thumbnail Card. 

### ISSUE THREAD

**Issue by Tracet51** [Microsoft/BotBuilder#2890]
* SDK Language: NODE
* SDK Version: 3.8.4
* Development Environment: AZURE_BOT_SERVICE

## Issue Description
The Buttons for other channels, (Skype, Facebook) appear when using the Thumbnail Card; however; on Kik they do not appear.

## Code Example
```js
let TestCard: builder.Message = new builder.Message(session)
    .addAttachment(new builder.ThumbnailCard(session)
    .title("Order")
    .text("Click the button to order")
    .images([builder.CardImage.create(session, "https://www.actualpicture.png")])
    .buttons([ builder.CardAction.openUrl(session, "https://www.test.com", "Order") ]);
```

## Expected Behavior
Thumbnail Card appears with buttons. 

## Actual Results
Thumbnail card appears but there are no buttons.

**Comment by nwhitmont** [comment]
@Tracet51 can you post your complete bot code so that we may better assist you?

**Comment by nwhitmont** [comment]
@Tracet51 Kik acts a bit differently when it comes to the card display.  When you send a card with buttons to the Kik mobile app, the buttons do not display in the card itself, they are located underneath the text input field. See screenshot. 

Card with buttons in WebChat component:
![emulator card with buttons](https://user-images.githubusercontent.com/3075047/27109989-0a83e642-505b-11e7-9372-24b6684311b9.png)

Card with buttons in Kik mobile app:
![kik card with buttons](https://user-images.githubusercontent.com/3075047/27110048-72d31a06-505b-11e7-83fc-430b5c62e44f.png)

**Comment by nwhitmont** [comment]
To view how different features will render in Kik and other channels, check out the Channel Inspector here: https://docs.botframework.com/en-us/channel-inspector/channels/Kik?f=Buttons&e=example1
