### ISSUE TITLE
[Direct Line] Load tests issues

### ISSUE THREAD

**Issue by ITM3** [Microsoft/BotBuilder#2892]
## System Information (Required)
* SDK Language: C#
* SDK Version: 3.8.1.0
* Development Environment: AZURE_APP_SERVICE

## Issue Description
We've developped a web app that is being called by a bot we have in the bot framework. The web app is deployed in Azure.

We've recently started doing performance load tests using JMeter that connects to the bot framework's direct line. We've made sure that the web app has all the resources it requires in Azure.

As soon as the load tests reach a certain threshold (a very low threshold - 50 users sending messages to the bot at each second), we start getting multiples errors, amongst which, one that occurs quite often: "POST to <name of our bot> timed out after 15s"

Have we reached a load limitation of the bot framework? 

## Actual Results
Here is some details that are found in the exception: "[{"parsedStack":[{"assembly":"Microsoft.Bot.ChannelConnector, Version=3.1.7.14, Culture=neutral, PublicKeyToken=null","method":"Microsoft.Bot.ChannelConnector.BotAPI+<PostActivityToBotAsync>d__29.MoveNext","level":0,"line":0}],"outerId":"0","message":"POST to botdevrc timed out after 15s","type":"Microsoft.Bot.Schema.BotTimeoutException","id":"16058177"}]"

**Comment by dandriscoll** [comment]
Hi @ITM3, please do not load test through Direct Line. You can perform load tests directly against your bot's endpoint.

The performance issue you're seeing may have multiple causes, but I would start by looking at your bot's use of bot state, and whether switching over to using e.g. our BotBuilder-Azure extensions would alleviate the problem. https://github.com/Microsoft/BotBuilder-Azure

**Comment by ITM3** [comment]
Thank you dandriscoll. I will look into that ant get back with the result.

**Comment by ITM3** [comment]
I forgot to mention that the traffic of the laod test is coming from one single static IP address (azure server) Do you think that this can contribute to performance problems?

**Comment by msmohan** [comment]
@ITM3 Direct Line is not designed for load test. We can close this thread. 

Please feel free to contact @Microsoft/bot-framework-support-team, if you face any issues using your Bot's endpoint.

**Comment by dandriscoll** [comment]
Hi @ITM3, a single IP address is unlikely to cause problems given the current design of the system. (It may change in the future.)

**Comment by ITM3** [comment]
Thank you guys for your fast and detailed replies, they're very much appreciated.

**Comment by ITM3** [comment]
Dadriscoll, you were right about directline load testing, we are now testing our bot endpoint directly. We are concern though that when our bot goes live, we might have problems with the load on the bot framework. Our bot will be reachable from messenger and web chat but going through the bot framework. 

Is there any way for us to ensure that the bot framework will handle the load when we go live?

Thanks!

**Comment by alokraj68** [comment]
Hi, We went live in web chat recently and has started to note down issues similar to this.
It says, 

```
Microsoft.Bot.Schema.BotTimeoutException:
   at Microsoft.Bot.ChannelConnector.BotAPI+<PostActivityToBotAsync>d__29.MoveNext (Microsoft.Bot.ChannelConnector, Version=3.1.7.17, Culture=neutral, PublicKeyToken=null: d:\a\1\s\ChannelSDK\Microsoft.Bot.ChannelConnector\API\BotAPI.cs: 292)
```

Can you guys help me?!

**Comment by karinaSC** [comment]
@ITM3  @dandriscoll 

Hello guys. Can  help me with a question? I'm run tests on a microsoft bot from power apps, the power virtual agents. I would like to run a performance test with JMeter. Can't I use a directLine API?


Thanks
