### ISSUE TITLE
[Question] RemoteSessionLogger logging events don't conform to Swagger spec

### ISSUE THREAD

**Issue by tobybrad** [Microsoft/BotBuilder#2893]
## System Information (Required)
* SDK Language: NODE
* SDK Version: 3.8.4
* Development Environment: LOCALHOST

## Issue Description
RemoteSessionLogger events don't conform to Swagger spec.

## Steps to Reproduce

1. Set up a local swagger server based on the ConnectorAPI.json Swagger spec: https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Microsoft.Bot.Connector.Shared/Swagger/ConnectorAPI.json
2. Post a basic message to yourself.

## Expected Behavior

Swagger server should validate the debug event

## Actual Results

Swagger server throws:

> Error: JSON Schema validation error. 
> Data path: "/value" 
> Schema path: "/properties/value/type" 
> Invalid type: array (expected object)

The mismatch is between the value property of the Activity, which is defined like this in the Swagger file:

> "Object": {
> "type": "object",
>    "properties": {}
>  }

i.e. 'value' is an object.

The event created by the RemoteSessionLogger looks like this:

``` node
    RemoteSessionLogger.prototype.createEvent = function () {
        return {
            type: 'event',
            address: this.address,
            name: 'debug',
            value: [],
            relatesTo: this.relatesTo,
            text: "Debug Event"
        };
    };
```

Note that 'value' there is actually an array, not an object.

If you really wanted value to be an array of objects you *could* change the 'value' in the swagger file to: 

>   "Object": {
>      "type": "array",
>      "items" : "object"
>    },

otherwise it's an issue purely in the Node SDK.

**Comment by nwhitmont** [comment]
@tobybrad Can you provide some context, for example, how is this issue affecting your bot's functionality? Is this causing a problem in your bot?

**Comment by nwhitmont** [comment]
@tobybrad reopen if this is affecting your bot's functionality
