### ISSUE TITLE
[Question] FB Messenger WebView (opened with OpenURL) won't follow SSO redirection

### ISSUE THREAD

**Issue by JpEncausse** [Microsoft/BotBuilder#2894]
https://stackoverflow.com/questions/44304002/ms-botframework-sign-in-redirection-fail-in-messenger-webview

I try to Sign-In users from Messenger to Microsoft Graph API.

## System Information 
* SDK Language: NODE
* SDK Version: 3.3.3
* Development Environment: AZURE_APP_SERVICE

## Issue Description
On Messenger OpenURL feature will open a Webview that may have some limitation

## Steps to Reproduce
1. I display a Messenger Card with a Button that OpenURL to Microsoft SignIn
2. Messenger open a WebView to the URL
3. The User Sign-In correctly
4. BUT the redirect to my server fails 

* It works on Messenger (desktop)
* It works when opening the URL in a real browser

## Expected Behavior
The WebView should follow the redirect from Microsoft Graph to my Server.
* Could it be possible that WebView is limited to an URL prefix ?
* Is there a workaround to OpenURL to a real browser ?

## Actual Results
* The webview hangs forever because the redirect is not performed
* Users have to copy/past the URL to a Mobile Browser to make it works

**Comment by msmohan** [comment]
It is possible that, it is redirecting to the Reply URL configured at AAD settings.

![image](https://user-images.githubusercontent.com/29078812/26841042-2e7e6c0c-4a9d-11e7-9dbe-1d50190df808.png)

**Comment by JpEncausse** [comment]
I don't think it comes from redirect configuration because it works with a standard Web Browser like Desktop Messenger or copy/past the URL into a Mobile WebBrowser

May Be ? Messenger's Webview are limited to starting URL. Fonr instance starting with something like http://microsoft.com won't allow a redirect to http://myserver.com

**Comment by msmohan** [comment]
@JpEncausse can you please share the source-code, I can take look into it?

**Comment by JpEncausse** [comment]
The code is wrap in a Node-RED node:
https://github.com/NGRP/node-red-contrib-viseo/blob/master/node-red-contrib-ms-graph/node-ms-graph-oauth.js

The state is the bot userId to store it's data
The callback will redirect to a standard http node /myserver

I'll dig to Implicit Flow but I don't understand why it works with a standard browser and won't work with a Messenger webview

**Comment by JpEncausse** [comment]
I find the issue and answered in StackOverflow:

The redirection will work if the Microsoft Graph App is configured with Web Paltform AND Native Platform. The Callback URL must be set only on the webplatform part but Messenger (app) won't follow the redirection if the Native Platform is not set.
