### ISSUE TITLE
[Question] Regarding Pricing For Microsoft Bot Framework

### ISSUE THREAD

**Issue by RaoVenka** [Microsoft/BotBuilder#2895]
Hello Team,

I am working on a chat bot using Microsoft bot framework.Could you please let me know whether there is any charge for using the bot framework.

If it is paid version , Please send me the all pricing details.

Please do the needful asap.I am waiting for your reply.

Thanks ,
Venkateswara

**Comment by nwhitmont** [comment]
@RaoVenka BotBuilder SDK is [open source software](https://opensource.com/resources/what-open-source) released under the [MIT License](https://github.com/Microsoft/BotBuilder/blob/master/LICENSE).
