### ISSUE TITLE
[Question] Does only use Azure Notification Hubs to send a trigger to the client to open a new conversation with the bot for Directline channel?   

### ISSUE THREAD

**Issue by rainmakerho** [Microsoft/BotBuilder#2896]
I ref #1414 . 
Does any tutorials or code samples? 
Thanks.

**Comment by EricDahlvang** [comment]
@rainmakerho please check out https://github.com/MicrosoftDX/botFramework-proactiveMessages

**Comment by nwhitmont** [comment]
@rainmakerho Are you using .NET or Node SDK?

**Comment by rainmakerho** [comment]
@EricDahlvang I  use Microsoft.Bot.Connector.DirectLine to manipulate bot's conversation in other webapi controller. 
I don't know how let DirectLine to get the message ,when i call "await Conversation.ResumeAsync(state.ConversationReference, message);" .
Thank for your help.

**Comment by EricDahlvang** [comment]
@rainmakerho Please post the code you are using.  I don't think I understand the question.  Please try to rephrase or reword what you are asking.  

By "manipulate bot's conversation in other webapi controller" are you asking how to send a proactive message through the direct line from within a different controller?  (I believe the samples mentioned above work with any channel.)

**Comment by rainmakerho** [comment]
@EricDahlvang The code is at [BotAuth](https://github.com/rainmakerho/BotAuth).
the project have 2 controllers([LineMessagesController.cs](https://github.com/rainmakerho/BotAuth/blob/master/ZimbraBOT/Controllers/LineMessagesController.cs), [MessagesController.cs](https://github.com/rainmakerho/BotAuth/blob/master/ZimbraBOT/Controllers/MessagesController.cs)).
LineMessagesController will use DirectLineClient post message to MessagesController, when i post message to LineMessagesController.
[Login.aspx.cs](https://github.com/rainmakerho/BotAuth/blob/master/ZimbraBOT/OAuth/Login.aspx.cs) will call Conversation.ResumeAsync method after Authentication.
I don't know how to get the Resume Message with DirectLineClient.
Thank for your help.
