### ISSUE TITLE
[Question] Handling custom assemblies and their dependencies for Bot App Services.  Newtonsoft.Json 9.0.1 in azure-functions-core-tools

### ISSUE THREAD

**Issue by MikeDrips** [Microsoft/BotBuilder#2899]
## System Information (Required)
* SDK Language: .NET/C#
* SDK Version: 3.8.0
* Development Environment: AZURE_BOT_SERVICE

## Issue Description
I have an issue pertaining to using custom assemblies within Azure Functions Bot Service and how to handle their dependencies.  

**My Setup:**
I'm developing an Azure Bot Service that runs as an http triggered azure function bot service.  To make development easier and the code source more reusable, all the logic my bot uses has been placed into several separate assemblies. These separate assemblies define models and services (LUIS, Azure ML,  other custom API calls) needed to invoke the bot's logic and construct responses.  All these custom assemblies go into a child directory of the bot service wwwroot (wwwroot\Shared\) along with any other external dependencies my assemblies need at runtime (including eachother).  When the bot is triggered, I've set it's entry point to be a static method from one of these assemblies by adding to function.json,

`"scriptFile": "..\\Shared\\AzureFunctions.Bot.dll",
  "entryPoint": "AzureFunctions.Bot.HttpFunctions.MessagesController",`

This method works very well except that sometimes I need to add as many as 20-30 dependency assemblies to the Shared directory. No problem, I can totally manage doing that (especially because all I have to do to update the bot's functionality is upload new assemblies).  It took me forever to find documentation that I could even do this, but it greatly simplifies things.

**My Issue:**
 My custom assemblies use Newtonsoft.Json.dll to serialize/deserialize objects in API calls. In development locally we use Newtonson.Json 10.0.2.  I quickly found out that azure-functions-core-tools does not. they use Newtonsoft.Json 9.0.1.  This caused exceptions to throw when handling LUIS's "builtin.datetimeV2" objects because getting datetime values out of the EntityRecommendation.Resolution.Value property requires casting a unspecified object to Newtonsoft.Json.Linq.JArray. The error that happens at runtime (both on local and server environment):

(this from server environment)

`Exception message: [A]Newtonsoft.Json.Linq.JArray cannot be cast to [B]Newtonsoft.Json.Linq.JArray. *Type A originates from ‘Newtonsoft.Json, Version=9.0.0.0*, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed’ in the context ‘Default’ at location ‘D:\Program Files (x86)\SiteExtensions\Functions\1.0.11002\bin\Newtonsoft.Json.dll’. *Type B originates from ‘Newtonsoft.Json, Version=10.0.0.0*, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed’ in the context ‘LoadFrom’ at location ‘D:\local\Temporary ASP.NET Files\root\b1535fc1\41a0ab9c\assembly\dl3\8720819d\8001488a_9ddfd201\Newtonsoft.Json.dll’`

As you can see, its the conversion from a JArray made in Newtonsoft 9 (install on the server as tools for the azure function) to a JArray made in Newtonsoft 10 (local dependency of my function). This means that when the LuisResult is getting deserialized after hitting my LUIS model, it uses a different assembly than the dependency to Newtonsoft I'm defining in the project.json.  If I could customize where the function looks for assemblies or at least have the option to add my custom assemblies to that location, this wouldn't be an issue. 

**My fix for local debugging environment:**
I went into the azure-functions-core-tools node_module directory and manually updated the Newtonsoft.Json assembly to 10.0.2.  This at least fixed the error locally so development could continue. 

**Summary/Questions:**
- What is the intended way to handle the dependencies of custom assemblies for an Azure Function?
- Will the azure-functions-core-tools and Azure Functions runtime environment upgrade to Newtonsoft.Json 10 in the near future? 
- Is there a way to add custom assemblies to the functions dependencies so that they get group all the other assemblies to eliminate version mismatch errors?
- Am I approaching this completely wrong? 

**A secondary thought**
This issue may be avoidable if I changed the way the I extract values from EntityRecommendation.Resolution.Value for the new datetimeV2, even though it does work with Newtonsoft 10 as described in my fix.  I cannot find any documentation/examples of handling these datetimeV2 objects.  That is a problem.  Can you please show how these are supposed to handled when they are received in a LuisResult.

**Comment by JasonSowers** [comment]
@MikeDrips did you ever resolve this issue?

**Comment by MikeDrips** [comment]
No, we made our own ai/bot framework that better suited our needs.
