### ISSUE TITLE
C# - Bot Emulator @Mentions Empty in Message object

### ISSUE THREAD

**Issue by warrenbuckley** [Microsoft/BotBuilder#29]
I am using the Bot Emulator and typing into the window the following message:
`What time is it for @paul at 2 in the afternoon?`

In the `Microsoft.Bot.Connector.Message` class I was expecting the mentions property on the object to be populated with `paul` or `@paul`

I am not entirely sure if this is a bug or me not understanding how this property gets populated in the API

**Comment by tomlm** [comment]
oh dang, that's a good idea.  The emulator is currently only detects mentioning the bot by appId, aka @FooBot will show up in the mentions.  But just doing it as a simulated user is a good idea, I will update it.

**Comment by warrenbuckley** [comment]
I am not 100% sure I follow fully @tomlm that I want to ask my bot a question or talk to my bot from a different user, and I thought the emulator already supports this anyway? With that option being found in the top right of the emulator?

So yes this is in the context of a group conversation or in use in say slack, when I am asking my bot `what time is it for @paul` I am wanting to pass Paul as a mentioned user in the channel/team of slack or alternatively I suppose in a group Skype chat.

With LUIS currently I can ask `What time is it for Paul at 2 in the morning?` and get the entity of the user being `Paul` and the other entity of a Time/Date correctly as well. But in the case of my bot I was thinking rather than me trying to manually map the real persons name entity that LUIS finds in this case `Paul` back to a username which may be something like `@mrPaul`

Again this may be myself mis-understanding the usage of mentions in this API and going about it in the wrong approach.

**Comment by tomlm** [comment]
No, you are on the right track.  Many of the channels have the ability to identify a user inline to a conversation, aka an @mention in facebook or twitter will actually result in a structured reference to the user.  When this happens we pass that information via the Mentions data structure, but currently the emulator is not emulating that functionality.  It currently emulates the mentioning of your bot via @AppId , but not for other people (although the connector platform will.)  Make sense?

**Comment by warrenbuckley** [comment]
Ah ok glad I was. Then yes if the emulator can support this that would be great otherwise I need to deploy to Azure setup the bot with the connector and do remote debugging from VS which is probably not the best workflow for fast interation with development.

**Comment by tomlm** [comment]
I just updated the emulator and it supports mentions as described. Thanks

**Comment by warrenbuckley** [comment]
@tomlm will I need to re-download or does the emulator auto update or check for updates?
