### ISSUE TITLE
What actually api key is?

### ISSUE THREAD

**Issue by theotheo** [Microsoft/BotBuilder#290]
Hello. What api key for Bot Connector Rest API is? Where can I get it?

![screenshot_247](https://cloud.githubusercontent.com/assets/1499744/15291204/64ad8cd8-1b85-11e6-97d9-712d7c66ff55.jpg)

**Comment by willportnoy** [comment]
I believe this would be the api key for your bot, once you've registered one.

**Comment by theotheo** [comment]
Thanks! I think I have a problem with something else.
