### ISSUE TITLE
[Question] Facebook Messenger Bot - works for me, not FB reveiwers

### ISSUE THREAD

**Issue by rdy4trvl** [Microsoft/BotBuilder#2900]
I've created a bot using Microsoft QnA Maker connected to Azure. I've set up & connected to FB App. When I visit the FB page, the bot works perfectly for me!

FB App Review tested and did not get a response from the bot. The approval submission provided the questions to use, the proper FB page....any suggestions on what may be missing? (FB feedback is attached)
Thanks

![fb](https://user-images.githubusercontent.com/23514849/26905807-566e770a-4b9e-11e7-9517-b4beda4b2b48.JPG)

**Comment by nwhitmont** [comment]
@rdy4trvl What is your bot name, bot handle, and App ID as you registered it in the Bot Portal? https://dev.botframework.com

**Comment by rdy4trvl** [comment]
Initially, I tried to set this up with Bot Framework but could not and switched to Azure and it worked.  I may be missing the point but I think (??) Azure incorporates Bot Framework.  Azure connects/setup seemed to be the same as Bot Framwork.  Do I still need Bot Framework?

**Comment by nwhitmont** [comment]
@rdy4trvl By "Azure", do you mean the [Azure Bot Service](https://azure.microsoft.com/en-us/services/bot-service/)? Or Azure App Service? Or something else?

Did you not register your bot in the Bot Portal at [https://dev.botframework.com](https://dev.botframework.com)?  You should have gone through a registration step where you configured your Microsoft App ID and password in the bot portal.

**Comment by rdy4trvl** [comment]
Sorry, it was Azure Bot Service.  I didn't go back to Bot Framework because Azure Bot Service seemed to ask for the same FB Page ID, App ID & Page access Token.  Do I still need Bot Framework?  What makes me think the issue is somewhere in FB is that the Bot actually works for me (I presume as a FB Developer?) - when I "View as a Page Visitor" from within our organization's FB page.   So, the systems (FB<->MS QnA +Azure Bot) are working together for me, not FB App Review Team.

![fb m](https://user-images.githubusercontent.com/23514849/26908602-7a76e6e8-4bb0-11e7-885e-04a695d49367.JPG)

**Comment by JasonSowers** [comment]
@rdy4trvl classic "works on my machine" case!  Have you connected the bot to any other channels? Do you notice issues anywhere else?

**Comment by rdy4trvl** [comment]
Good suggestion....will give it a try.

**Comment by JasonSowers** [comment]
@rdy4trvl let me know how that works out for you

**Comment by JasonSowers** [comment]
@rdy4trvl did you get this worked out?

**Comment by rdy4trvl** [comment]
Yes, Success!!  Up and running on Facebook Messenger.  About 100 QnA Maker questions in the knowledge base.  I did apply for Skype but need to follow up on that.  
One of my problems was that I didn't realize I needed to make the bot public for FB to review.   
Thanks for the help!!
https://www.facebook.com/messages/t/MarinCyclists

**Comment by JasonSowers** [comment]
Glad you got it worked out Good luck!
