### ISSUE TITLE
[Question] Multi dialogue .NET bot code example?

### ISSUE THREAD

**Issue by sowsan** [Microsoft/BotBuilder#2901]
Looking for an e.g of multi dialogue sample for .NET bot. The samples currently I have seen is with two dialogues..RootDialogue calling another ChildDialgue. I have a scenario where I have to call sub Child Dialogue form the ChildDilague, but its failing saying that Stack in empty. using Context.Forwrad() for calling the dialgues from RootDialague and then to ChildDialgue and then to SubChildDialgue.

**Comment by Magic73** [comment]
Post your code.

But in general you should do something like this:

RootDialog: context.forward (child....) and then don't call context.wait.
ChildDialog: context.forward (subchild....) and then don't call context.wait.
SubChild: do what you need, and use context.wait to stay on subdialog, or .done to exit and return to child.

**Comment by michaelhutchful** [comment]
Hello,

So I am not sure what the difference is, but I use context.Call to call the SubChildDialogue. This works fine

Regards Michael

Sent from Mail for Windows 10

From: sowmyan soman
Sent: 08 June 2017 01:45
To: Microsoft/BotBuilder
Cc: Subscribed
Subject: [Microsoft/BotBuilder] E.g. for multi dialogue .NET bot (#2901)

Looking for an e.g of multi dialogue sample for .NET bot. The samples currently I have seen is with two dialogues..RootDialogue calling another ChildDialgue. I have a scenario where I have to call sub Child Dialogue form the ChildDilague, but its failing saying that Stack in empty. using Context.Forwrad() for calling the dialgues from RootDialague and then to ChildDialgue and then to SubChildDialgue.

**Comment by Magic73** [comment]
the difference between call and forward is that Call open a new dialog, and wait for the next message.
Forward, instead open a new dialog and pass to it the current message (it is one of the parameter required) so that the dialog process this one.

**Comment by sowsan** [comment]
Thank you so much,  let me try it out in my sample code and I will post it if the concepts is not working. Your inputs cleared the doubts I had 👍
