### ISSUE TITLE
[Question] Conversation Logger

### ISSUE THREAD

**Issue by Magic73** [Microsoft/BotBuilder#2903]
I need to do some analytics with the Bot.
I'm using a TraceLogger: IActivityLogger class.

The issue is with the information that I may use. The LogAsync method, has only the activity parameter. But with this info I can't find a way to know if the activity is from the bot to the user, or from the user to the bot.

Is there a way to get this info?

Checking the BotFramework source code, I saw that the LogAsync method of the logger is called from two classes which do what I need to know:

LogPostToBot and LogBotToUser

Maybe I have to register two custom classes (which implements IPostToBot and IBotToUser)  so that the builder will use mine instead of the predefined one?
In case, how may I do it?

**Comment by nwhitmont** [comment]
@Magic73 are you using .NET or Node SDK?

**Comment by Magic73** [comment]
.Net

**Comment by JasonSowers** [comment]
@Magic73 going to close this issue because of the PR submission.  Feel free to reopen it if you would like to continue discussing here.
