### ISSUE TITLE
Facebook connection broken (Error 500)

### ISSUE THREAD

**Issue by abtoom** [Microsoft/BotBuilder#2904]
## System Information (Required)
* SDK Language: NODE
* SDK Version: botbuilder@3.8.3
* Development Environment: AZURE_APP_SERVICE

## Issue Description

my bot receives messages from a user, but when I want to respond, with session.send(reply), then nothing happens.
In my logs it states an Internal Server error in the facebook connector.

Error: Request to 'https://facebook.botframework.com/v3/conversations/1493255104018333-809272025898455/activities/mid.%24cAAK68avhCENiuXCRnVciCtOmj1MI' failed: [500] Internal Server 

Then, no response is sent back to facebook and the user does not see a response.
The error remains, even when I delete the conversation on facebook and restart the conversation

thank you 

## Code Example
It's not a coding problem, it haved worked this afternoon without code changes

## Steps to Reproduce
---
## Expected Behavior
the user should see the bot's response

## Actual Results

message received from FB user:

2017-06-08T14:53:07.928Z - debug: main dialog message 
{ type: 'message',
  timestamp: '2017-06-08T14:53:06.724Z',
  text: 'ge',
  sourceEvent: 
   { sender: { id: '1493255104018333' },
     recipient: { id: '809272025898455' },
     timestamp: 1496933586724,
     message: 
      { mid: 'mid.$cAAK68avhCENiuXcfJFciDHcKHzpS',
        seq: 4460,
        text: 'hallo',
        is_echo: false } },
  attachments: [],
  entities: [],
  address: 
   { id: 'mid.$cAAK68avhCENiuXcfJFciDHcKHzpS',
     channelId: 'facebook',
     user: { id: '1493255104018333', name: 'xxx' },
     conversation: { isGroup: false, id: '1493255104018333-809272025898455' },
     bot: { id: '809272025898455', name: 'nep-chatbot-dev' },
     serviceUrl: 'https://facebook.botframework.com' },
  source: 'facebook',
  agent: 'botbuilder',
  user: { '$ref': '$["address"]["user"]' } }

Error: 

Error: Request to 'https://facebook.botframework.com/v3/conversations/1493255104018333-809272025898455/activities/mid.%24cAAK68avhCENiuXCRnVciCtOmj1MI' failed: [500] Internal Server Error
    at Request._callback (D:\home\site\wwwroot\node_modules\botbuilder\lib\bots\ChatConnector.js:512:46)
    at Request.self.callback (D:\home\site\wwwroot\node_modules\request\request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (D:\home\site\wwwroot\node_modules\request\request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous>

**Comment by nwhitmont** [comment]
@abtoom We had some errors in the Facebook Channel connector service this morning.  The service has been rebooted and is back to normal status.
