### ISSUE TITLE
[Feature Request] Provide current dialog/step to middleware

### ISSUE THREAD

**Issue by Rodrigora** [Microsoft/BotBuilder#2905]
## System Information (Required)
* SDK Language: NODE
* SDK Version: 3.8.3
* Development Environment: LOCALHOST

## Issue Description
I would like to use the middleware to send chat statistics to a server. From what I researched, the better way to do it would be creating a middleware to intercept all messages.

However, middleware callbacks don't have any information related to the current dialog which the user is currently in.

A possible solution would be to add the session to the `send` function:

## Code Example
```
bot.use({
  send: function (event, session, next) {
    sendDialogAndStepToTheServer(session);  // assuming that the session object has the current dialog/step 
    next();
  }
});

```

## Actual Results
I can't send this info to the server without adding a function call in all waterfall functions.

**Comment by JasonSowers** [comment]
@Rodrigora This project is open source and you are welcome to submit a pull request for our SDK devs to review.  Good luck!

**Comment by nwhitmont** [comment]
@Rodrigora Add the the dialog/step metadata to the session object, then access it from your logging middleware.

**Comment by Rodrigora** [comment]
@nwhitmont thank you for your explanation.

but, as far I now, I'd need to do something like this:

```
bot.dialog('whatever', [
  function (session) {
    session.userData.dialog = 'whatever';
    session.userData.step = 1;
    // ...
  },
  function (session) {
    session.userData.dialog = 'whatever';
    session.userData.step = 1;
    // ...
  },
  function (session) {
    session.userData.dialog = 'whatever';
    session.userData.step = 1;
    // ...
  },
  // ...
]);

bot.use({
  botbuilder: function (session, next) {
    sendDialogAndStepToTheServer(session.userData);
    next();
  }
});

```

Is this what you're suggesting? 

Would be great to have the current dialog/step info in the session object by default, what do you think? Or this use case is very restricted?

**Comment by nwhitmont** [comment]
relates to: https://stackoverflow.com/questions/44438849/microsoft-bot-how-to-log-each-conversation-step

**Comment by iMicknl** [comment]
Have a look at BotBuilder-Instrumentation, @morsh has found a way to catch the beginDialog event. Maybe it is helpful. https://github.com/CatalystCode/botbuilder-instrumentation/blob/master/src/main.ts

**Comment by michaelvol** [comment]
Maybe you can use session.dialogStack() ?

**Comment by JasonSowers** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
