### ISSUE TITLE
[Question] Cards not working in MS Teams?

### ISSUE THREAD

**Issue by meganlcooper** [Microsoft/BotBuilder#2906]
I am using Hero Cards, Receipt Cards, and Adaptive cards in my bot. I am testing it out in ms teams right now and have the following issues:

1. The buttons for my Hero Card are not working properly (pressing them enacts a Luis Intent). Here is the code for said hero card:
```cs       [LuisIntent("Help")]
        public async Task showBotInformation(IDialogContext context, LuisResult result)
        {
            var helpMsg = context.MakeMessage();
            var helpHeroCard = new HeroCard
            {
                Title = "Hi, I'm Bridget.",
                Text = "I'm here to provide easy, information. ",
                Buttons = new List<CardAction> {
                    new CardAction(ActionTypes.PostBack , "Common Qs" , value: "show common questions"),
                    new CardAction(ActionTypes.PostBack , "Settings" , value: "settings")
                }
            };
            helpMsg.Attachments.Add(helpHeroCard.ToAttachment());
            await context.PostAsync(helpMsg);
        }```

2. Receipt cards aren't showing up at all? Are receipt cards not supported?

**Comment by msmohan** [comment]
@meganlcooper can you please share the code, we can review and debug the issue?

**Comment by JasonSowers** [comment]
Adaptive Card support in MS Teams is still officially listed as "Coming Soon"

**Comment by nwhitmont** [comment]
Receipt card + Adaptive Cards are not currently supported in MS Teams.

**Comment by meganlcooper** [comment]
Yes sorry, here is the code for my Hero Card:
`[LuisIntent("Help")]
        public async Task showBotInformation(IDialogContext context, LuisResult result)
        {
            var helpMsg = context.MakeMessage();
            var helpHeroCard = new HeroCard
            {
                Title = "Hi, I'm Bridget.",
                Text = "I'm here to provide easy, information. ",
                Buttons = new List<CardAction> {
                    new CardAction(ActionTypes.PostBack , "Common Qs" , value: "show common questions"),
                    new CardAction(ActionTypes.PostBack , "Settings" , value: "settings")
                }
            };
            helpMsg.Attachments.Add(helpHeroCard.ToAttachment());
            await context.PostAsync(helpMsg);
        }`
The buttons trigger LUIS intents when the postback happens, but for some reason in teams all I see is the postback and the LUIS intent isn't triggered? I am using ngrok to test in teams.

**Comment by RichMoeMSFT** [comment]
@meganlcooper [PostBack is actually not supported in Teams](https://msdn.microsoft.com/en-us/microsoft-teams/botsmessages#card-actions-in-teams).  We have imBack and invoke, which are the separate pieces of PostBack (imBack for the text response, invoke for the silent JSON post.)
