### ISSUE TITLE
[Feature Request] Add LINE channel integration

### ISSUE THREAD

**Issue by nwhitmont** [Microsoft/BotBuilder#2908]
This issue is to track requests for adding a LINE channel integration to Bot Framework. Thumbs up this comment to vote.

LINE
https://line.me/en-US/

LINE Bot SDK Node.js
https://www.npmjs.com/package/@line/bot-sdk

Bot Framework (unofficial) LINE Connector Node.js
https://www.npmjs.com/package/botbuilder-linebot-connector

**Comment by kcw2099** [comment]
Official dev doc
https://developers.line.me/en/

**Comment by JasonSowers** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
