### ISSUE TITLE
how to call luis dialog from general dialog 

### ISSUE THREAD

**Issue by aakashkag** [Microsoft/BotBuilder#2912]
## System Information (Required)
* SDK Language: <NODE>
* SDK Version: <3.6>
* Development Environment: <LOCALHOST>
Node.js + npm version
6.9.5 + 4.5.0

## Issue Description
I want to call Luis dialog within another dialog

dialog.matches('morningUpdate',[    
    function (session, args, next) {
  }
]);

bot.dialog('/work', [
  function (session, args) {
    //how to call here "morningUpdate" dialog here?
  }
]);

how i can call  morningUpdate inside work dialog

**Comment by kpuzyr** [comment]
`bot.dialog('/work', [
   (session, args) {
     session.beginDialog('/morningUpdate', args)
   }
]);
bot.dialog('/morningUpdate',[
   function (session, args, next) {
     session.endDialog('finish');
   }
]);`

**Comment by aakashkag** [comment]
no,it won't help. morningUpdate dialog call when user enter some text then it goes to luis ,then from luis morningUpdate dialog call.

**Comment by stevengum97** [comment]
See here https://github.com/Microsoft/BotBuilder/issues/2741#issuecomment-307430385

**Comment by aakashkag** [comment]
thank u soo much .it's working for me :)
