### ISSUE TITLE
[Question] I've been having issues with "demarrer" word

### ISSUE THREAD

**Issue by stelazh** [Microsoft/BotBuilder#2913]
in my bot when i send "demarrer" as text ( to test Get Started in french  option ) i got some issues : here was an error sending this message to your bot: HTTP status code InternalServerError

I am using luis , and it try to add this word in intent , but still the same thing

**Comment by nwhitmont** [comment]
@stelazh Are you using .NET or Node SDK? Can you post your bot code that is causing the error?

**Comment by stelazh** [comment]
i am using .net

**Comment by nwhitmont** [comment]
@stelazh check out this example code to get you started with .NET SDK - https://github.com/Microsoft/BotBuilder/tree/master/CSharp/Samples/SimpleEchoBot

**Comment by nwhitmont** [comment]
@stelazh were you able to solve your issue by starting from the example code?
