### ISSUE TITLE
[Question]: any suggestion on how to handle multiple messages and then respond after a gap of 2-3 secs?

### ISSUE THREAD

**Issue by ranmax123** [Microsoft/BotBuilder#2914]
## System Information (Required)
* SDK Language: C#
* SDK Version: 3.8
* Development Environment: <LOCALHOST, AZURE_BOT_SERVICE, AZURE_APP_SERVICE, OTHER>

## Question Description
The current behavior of the bot is to process "every" message and respond. Is there any recommendation on how to capture chunk of messages (inputted by pressing enter key), process them as one message?

Usually when people chat with a bot is they input multiple messages each followed by enter key.

Sorry, i'm posting it here since responses on stackoverflow to bot specific questions is usually less.

**Comment by JasonSowers** [comment]
What is your use case here?  what are you trying to accomplish?

**Comment by ranmax123** [comment]
@JasonSowers, usually people will type multiple lines and press enter after each line in a chat window. In the current situation, bot handles each input and process it. I want bot to queue those messages, process those messages as one message and reply. Any suggestion?


Ex: chat

Hi <enter>
I would like to know <enter>
if there is any coupon code <enter>
available <enter>

pause for 2-3 secs.

Bot should treat
"I would like to know if there is any coupon code available" as one message.

**Comment by ranmax123** [comment]
@JasonSowers any help?

**Comment by JasonSowers** [comment]
The only thing I can think of here is to write a helper that would store the lines the concatenate them together, like a `List<string>`.  You would have to write something that waits a given amount of time for a line to show up from the user, then iterate through the list and concatenate all the lines together.  Some pseudocode might be
```cs
var myList = new List<string>()
var done = false
while (!done){
//take input and add to myList
//wait a given amount of time for next input
}
foreach (var item in myList){
message.text+=" "+item.tostring
}
//do stuff with the message
```

**Comment by ranmax123** [comment]
@JasonSowers , thanks, how to do this in bot code, like Post method since there will be simultaneously multiple calls to this method?

public async Task<HttpResponseMessage> Post([FromBody]Activity activity)

**Comment by ranmax123** [comment]
@JasonSowers ?

**Comment by JasonSowers** [comment]
@ranmax123 how do you propose to know when the "chunk of messages" has ended?  Will the user type something specific?  After x amount of messages?

**Comment by ranmax123** [comment]
@JasonSowers no, if new message has not been received in 5-10 secs (this means user is waiting for the bot to respond), then process the messages as chunk.

Appreciate your help since in real world people will chat in chunk of messages

**Comment by ranmax123** [comment]
or after x amount of messages, any code will help

**Comment by ranmax123** [comment]
@JasonSowers ?
