### ISSUE TITLE
[Question] Auth for a Microsoft Teams bot 

### ISSUE THREAD

**Issue by fbessez** [Microsoft/BotBuilder#2915]
Does someone know how to appropriately/successfully auth a bot as a user?
For example, in slack, one would send the user to /addons/slack/authenticate. What is the equivalent for teams?? Can someone point me to some guide for this? THANK YOU!

**Comment by JasonSowers** [comment]
@fbessez  Have you looked at this yet?  It may help https://msdn.microsoft.com/en-us/microsoft-teams/botsadd

**Comment by nwhitmont** [comment]
@fbessez are you using .NET or Node SDK?

**Comment by nwhitmont** [comment]
Use the sign-in card, it's designed exactly for this purpose. You can find an example sign-in card here: https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node/cards-RichCards

**Comment by iMicknl** [comment]
@nwhitmont sign in card isn't supported in Microsoft Teams (yet?). You will need to use a herocard with a openUrL button. https://github.com/Microsoft/BotBuilder/issues/2104

**Comment by nwhitmont** [comment]
@iMicknl Indeed you are correct.  I must have sent that comment through a wormhole from the future ;-)

**Comment by fbessez** [comment]
I am using Node! Basically, I want the Microsoft teams user to authorize my 3rd party app. So if I understand correctly, I have the button redirect me to an auth page and follow that stream of auth dance?

**Comment by JasonSowers** [comment]
For now yes

**Comment by nwhitmont** [comment]
@fbessez Here's a blog article that shows a few different methods to perform authentication with an external website (including sample code) -  [Build BOT with Authentication (Microsoft Bot Framework)](https://blogs.msdn.microsoft.com/tsmatsuz/2016/09/06/microsoft-bot-framework-bot-with-authentication-and-signin-login/)

**Comment by JasonSowers** [comment]
#4768
