### ISSUE TITLE
[Question] Receipt card alternatives for MS Teams?

### ISSUE THREAD

**Issue by meganlcooper** [Microsoft/BotBuilder#2917]
I'm working on a project whose information would be more effectively displayed on receipt cards. This is fine but I'm using MS Teams and I just found out that it doesn't support receipt cards. Is there a way to mimic the receipt card style with text, or hero cards? If so could you provide an example including buttons and images? Thanks!

**Comment by nwhitmont** [comment]
@meganlcooper are you using .NET or Node SDK?

**Comment by meganlcooper** [comment]
I'm using .NET sorry I forgot to clarify

**Comment by SheriEllisMSFT** [comment]
@meganlcooper - Hi Megan! Sorry you're hitting a limitation. You might take a look at our[ Get-Started sample](https://github.com/OfficeDev/microsoft-teams-sample-get-started). It has sample code in both C# and Node which use OpenUrl in bot dialogs. Have you looked at the [BotBuilder reference about Hero cards vs. receipt cards](https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node/cards-RichCards) too? Seems do-able to me, if the images are available, but please feel free to ask specific questions. Hope this helps!

**Comment by billbliss** [comment]
@meganlcooper this is now supported in Teams.
