### ISSUE TITLE
[Question] How to open file using Actions.OpenUrl?

### ISSUE THREAD

**Issue by meganlcooper** [Microsoft/BotBuilder#2918]
I want to open a file from a button on a hero card. Why does using file:///...file or network location... not seem to work? Here is my code:
```
var helpHeroCard = new HeroCard {
      Title = "Build Location",
      Buttons = new List<CardAction> {
            new CardAction(ActionTypes.OpenUrl , "\\\\DUMMY_SERVER\\" , value: "file:\\\\DUMMY_SERVER\\")
      }
};
helpMsg.Attachments.Add(helpHeroCard.ToAttachment());
await context.PostAsync(helpMsg);
```

Thanks!

**Comment by msmohan** [comment]
can you please share the code in order to repro?

**Comment by nwhitmont** [comment]
@meganlcooper are you using .NET or Node SDK?

**Comment by meganlcooper** [comment]
Sorry I'm new to this. Do you me upload all my code to github? I just wanted to know if there's a way to open a file or network location from a HeroCard button. Thanks

**Comment by msmohan** [comment]
you can choose to upload it to GitHub or you could upload it to onedrive and share the link.

**Comment by JasonSowers** [comment]
@meganlcooper can you show the snippet that constructs helpMsg?

**Comment by meganlcooper** [comment]
Its what's mentioned in the orig post:
```
var helpHeroCard = new HeroCard {
      Title = "Build Location",
      Buttons = new List<CardAction> {
            new CardAction(ActionTypes.OpenUrl , "\\\\DUMMY_SERVER\\" , value: "file:\\\\DUMMY_SERVER\\")
      }
};
helpMsg.Attachments.Add(helpHeroCard.ToAttachment());
await context.PostAsync(helpMsg);
```

**Comment by JasonSowers** [comment]
@meganlcooper helpMsg would not exist in this context, what is it and how is it constructed?  can you share that code please?

**Comment by meganlcooper** [comment]
Sorry, I added it in

**Comment by meganlcooper** [comment]
@msmohan Any idea how I can accomplish this? Thanks for the help.

**Comment by JasonSowers** [comment]
please see my previous comment, thanks.

**Comment by msmohan** [comment]
@meganlcooper can you share your code in GitHub or Onedrive?

**Comment by msmohan** [comment]
@meganlcooper can you please explain on "DUMMY_SERVER" ? is it your local pc? or network share?

**Comment by meganlcooper** [comment]
@msmohan Sorry, it is network share. Also I added context for the var helpMsg

**Comment by msmohan** [comment]
@meganlcooper 

You can host the file in local webserver instead.
Using ActionTypes.**OpenUrl** or **DownloadFile**, update your code as shown below

Buttons = new List<CardAction> { new CardAction(ActionTypes.**DownloadFile**, "Help File", value: "http://localhost/HelpFile.txt") }

Network share is not supported in this context.

**Comment by juvchan** [comment]
Do the **ActionTypes.OpenUrl** or **DownloadFile** support Data URL protocol? i.e. **data:**
