### ISSUE TITLE
Can an object be stored in session.userData?

### ISSUE THREAD

**Issue by smanos** [Microsoft/BotBuilder#292]
I am really sorry if this is is an incredibly stupid question (coming back to programming after a 10 year hiatus 👍 )

Can an object can be stored and then retrieved in the session.userData variable?

I'm trying to do this with a basic User object I created (just contains name, ID and an array) but when I run the code below I get `System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object` as the error type

Full code is here: [https://github.com/smanos/Bubo/blob/master/server.js]

`var bot = new builder.BotConnectorBot(botConnectorOptions);`
`...`
`bot.add('/firstRun', [`
`    function (session) {`
`...        `
`        session.userData.user = new User();`
`...`
`    },`
`    function (session, results) {`
`        // It looks like you can't manipulate session.userData.user directly`
`        var user = session.userData.user;  `
`        user.setName(results.response); <-------------------- This is where it fails`
`    }`
`]);`

**Comment by rodzillarr** [comment]
Hi,

The short answer is yes.  The longer answer can be found here: [http://docs.botframework.com/connector/tracking-bot-state/#navtitle](url)

Have fun!

-r

**Comment by slidenerd** [comment]
"The short answer is yes. The longer answer can be found here: http://docs.botframework.com/connector/tracking-bot-state/#navtitle

Have fun!"

that page gives  a 404
