### ISSUE TITLE
[Feature Request] Add WhatsApp channel support

### ISSUE THREAD

**Issue by nwhitmont** [Microsoft/BotBuilder#2920]
This issue is to track interest in [WhatsApp](https://www.whatsapp.com/) channel integration.  Thumbs up this comment to vote.

**Comment by EricDahlvang** [comment]
Has WhatsApp released an external API, or changed their terms of service to allow chat bots?

Check this out: https://medium.com/@AlfredBaudisch/how-a-whatsapp-bot-got-famous-and-evolved-as-the-brazilian-wechat-and-conversational-commerce-e2213262183d

**Comment by nwhitmont** [comment]
https://blog.whatsapp.com/10000631/Connecting-One-Billion-Users-Every-Day

**Comment by catcher-in-the-try** [comment]
WhatsApp explicitly disallows and bans bots, so why should this be supported?

**Comment by catcher-in-the-try** [comment]
Microsoft folks, can you confirm whether you are working on it or would you prefer to get a pull request? I think the community can put something together in a couple of weeks.

**Comment by EricDahlvang** [comment]
@catcher-in-the-try  A pull request would not include the channel connector server side code.  It wouldn't cover legal agreements, and a ton of other things involved with supporting a full fledged channel.  Thank you for your interest though.  It is helpful for the MS Bot Framework Team to receive this type of feedback from the community.

**Comment by jKelio** [comment]
Some of my clients and I also would like to use the MS Bot Framework with the newly publish WhatsApp Business Channel. Since August this year there is now an own API for WhatsApp Business: https://www.whatsapp.com/business/api

**Comment by garridev** [comment]
Is working MS Bot Framework on it?

**Comment by rysbilinski** [comment]
+1

**Comment by rudibr78** [comment]
It's been a very long time now since the WhatsApp API is available, and still we have no comment.

This is absolutely crucial not only for us bot framework users, but for the survival of the entire project.

If there are no plans to integrate WhatsApp, I recon a lot of us, myself included, will be forced to stop using bot framework all togheter.

The lack of an oficial forum for this kind of talk is also not very reassuring.

**Comment by martijnbeumers** [comment]
I'm with rudibr78!

**Comment by JasonSowers** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team

**Comment by EricDahlvang** [comment]
@huan this repository is now only for DCRs.  The WhatsApp channel feature request is being tracked here now: https://github.com/Microsoft/BotFramework-Services/issues/7

**Comment by huan** [comment]
@EricDahlvang Thank you very much for pointing out the way for me, appreciate it.

**Comment by tigertop** [comment]
Hello,
We have built a custom WhatsApp and Viber adapters that we are using in production and considering to publish them open source to Bot Builder Community. If you have any interest let me know and may be I can share the code before the open source release.

**Comment by huan** [comment]
Hi @tigertop , 

It's great news for the community that you have a production solution for the WhatsApp and Viber adapters!

I'm strongly interested in it, please let me know how to involve in it.

P.S. I'm the author of the [Wechaty](https://github.com/wechaty/wechaty) (the most popular Node.js Chatbot SDK for WeChat), and I have created an adapter for connecting the BotFramework with Wechaty: [botbuilder-wechaty-adapter](https://github.com/huan/botbuilder-wechaty-adapter)

**Comment by rodrigobrito** [comment]
> Hello,
> We have built a custom WhatsApp and Viber adapters that we are using in production and considering to publish them open source to Bot Builder Community. If you have any interest let me know and may be I can share the code before the open source release.

Hi @tigertop! Can you share the code with the community? I am working on a project related to COVID-19, and I have this need for integration.

**Comment by TameezAustell** [comment]
@tigertop please can you share example
