### ISSUE TITLE
[Question] Emulators work fine, Slack & Skype do not?

### ISSUE THREAD

**Issue by karam94** [Microsoft/BotBuilder#2922]
I've created a simple bot and published it on Azure.
Both the emulator on my local machine & the web emulator work fine with the bot.

However, despite configuring Slack correctly (& Skype comes pre-configured), my bot seems to ignore me on those platforms & it's driving me insane. No errors are being thrown on azure, everything looks healthy. My slack credentials in the setup section have also validated fine. 

I can add the bot on Skype & I can add the bot in to my Slack channel, successfully, so I presume something is going wrong with whatever is being configured between Microsoft & these third parties behind the scenes.

What could be causing this issue? I've updated my Bot Builder NuGet package to the latest as well as tried a clean install, to no avail. I've tried to recreate the bot configuration more than once both on the Microsoft side & Slack side, still nope. Starting to feel like the solution is out of my hands.

Any ideas?

Thanks!

**Comment by michaelhutchful** [comment]
Hello,

Try using ngrok to debug on skype and see what happens. Set a break point in your message controller and see what happens. For good measure also debug on the ones that work also so you have an idea how it works. Do this with ngrok.

Michael

Sent from my Windows 10 phone

From: Karam
Sent: 10 June 2017 12:11
To: Microsoft/BotBuilder
Cc: Subscribed
Subject: [Microsoft/BotBuilder] [Question] Emulators work fine, Slack & Skypedo not? (#2922)

I've created a simple bot and published it on Azure.
Both the emulator on my local machine & the web emulator work fine with the bot.
However, despite configuring Slack correctly (& Skype comes pre-configured), my bot seems to ignore me on those platforms & it's driving me insane. No errors are being thrown on azure, everything looks healthy. My slack credentials in the setup section have also validated fine.
I can add the bot on Skype & I can add the bot in to my Slack channel, successfully, so I presume something is going wrong with whatever is being configured between Microsoft & these third parties behind the scenes.
What could be causing this issue? I've updated my Bot Builder NuGet package to the latest as well as tried a clean install, to no avail. I've tried to recreate the bot configuration more than once both on the Microsoft side & Slack side, still nope. Starting to feel like the solution is out of my hands.
Any ideas?
Thanks!

**Comment by karam94** [comment]
Hi Michael,

Just tried doing that now. Both Skype & Slack don't even seem to trigger the execution of my code. Whilst the Web Emulator does, it results in a "405 Method Not Allowed" error being displayed on the Post request in ngrok.

Any ideas?
Thanks!

**Comment by karam94** [comment]
Solved the issue. One of the first steps my bot does is identify if any URLs have been sent by users.
Turns out Slack URLs look like <github.com> and Skype URLs have <a href=""> tags around them, so my bot wasn't identifying them.

Thanks for your help! :)

**Comment by michaelhutchful** [comment]
For now, just compare both the web and skype messages in ngrok inspect, i will see whether I can find out more

Michael

Sent from my Windows 10 phone

**Comment by michaelhutchful** [comment]
Ok cool and interesting

Sent from my Windows 10 phone
