### ISSUE TITLE
[Question] Make the bot to understand "Like" button and other emoji

### ISSUE THREAD

**Issue by stelazh** [Microsoft/BotBuilder#2926]
Hello,
I'm using BotFramework, luis.ai  and c# . In Facebook channel i want to program my bot to understand when a user send in chatbot 'thumb up sign' button or , or emoji.

How can i do this using luis.ai ? It is possible ...do you have any other solutions?

**Comment by AndreMantas** [comment]
This looks more like a stackoverflow question to me. 

You could create a list entity and add all the possible emojis and the synonyms btw.

**Comment by JasonSowers** [comment]
please reopen if needed
