### ISSUE TITLE
[Question] Creating own HTTPS Bot Endpoint to be used with embedded Chat

### ISSUE THREAD

**Issue by winterfeldt** [Microsoft/BotBuilder#2927]
We have installed botframework and are running a simple application on our server:

```js
var restify = require('restify');
var builder = require('botbuilder');
var fs = require('fs');

// Setup some https server options
//generated from http://www.selfsignedcertificate.com/
var https_options = {
        key: fs.readFileSync('./innovationslab.de.key'), //on current folder
        certificate: fs.readFileSync('./innovationslab.de.cert')
};


// Setup Restify Server
var server = restify.createServer(https_options);
server.listen(process.env.port || process.env.PORT || 3978, function () {
   console.log('%s listening to %s', server.name, server.url);
});

// Create chat connector for communicating with the Bot Framework Service
var connector = new builder.ChatConnector({
    appId: 'b030f685-a2a2-4b50-acd5-xxxx',
    appPassword: 'JMSDYjyReCxxxxxxx'
});

// Listen for messages from users
server.post('/api/messages', connector.listen());

// Receive messages from the user and respond by echoing each message back (pre$
var bot = new builder.UniversalBot(connector, function (session) {
    session.send("You said: %s", session.message.text);
});
```
We can connect to our endpoint using https. 
But the endpoint is not accepted by the chat control:

https://innovationslab.th-deg.de:3978/api/messages

Anyone an idea what I am doing wrong?? It does work with the emulator!

**Comment by nwhitmont** [comment]
@winterfeldt You need to update your production endpoint to https 443 instead of using the development port number 3978.

For example, your production endpoint should be `https://innovationslab.th-deg.de/api/messages`.

**Comment by winterfeldt** [comment]
Hey Nils,

I did change the endpoint. The bot emulator can now connect (https://innovationslab.th-deg.de/api/messages) 
but the chat channel does not send out the message and asks to repeat sending.
What are we missing? 

The application is quite big. We cannot host on Azure, the test amount (170 Euro) was gone after one week 
without heavy usage..


Mit freundlichem Gruss
Götz Winterfeldt
-----------------------------------------
Prof. Dr. Götz Winterfeldt
TH Deggendorf
Edlmair Str. 8

94469 Deggendorf

http://innovationslab.th-deg.de/ <http://innovationslab.th-deg.de/>
M : 0049  172 865 2312
Goetz.winterfeldt@ <mailto:Goetz.winterfeldt@hdu-deggendorf.de>th-deg.de <http://th-deg.de/>
SKID: goetzwinterfeldt

**Comment by nwhitmont** [comment]
@winterfeldt Herzliche grüße aus Redmond!

Did you register your bot in the "My bots" section of the Bot Portal at https://dev.botframework.com?  

For reference, what is your bot name, bot handle, and App ID used for your bot registration?

**Comment by winterfeldt** [comment]
Good evening,


the name is Toni, 
ToniMartin

APPID b030f685-a2a2-4b50-acd5-880a83b2c2d6
Pss JMSDYjyReCxoJpadZ7iBUWf

The connectot does work. I am currently verifying if we have an issue with the certificates. 
I generated them online.

Mit freundlichem Gruss
Götz Winterfeldt
-----------------------------------------
Prof. Dr. Götz Winterfeldt
TH Deggendorf
Edlmair Str. 8

94469 Deggendorf

http://innovationslab.th-deg.de/ <http://innovationslab.th-deg.de/>
M : 0049  172 865 2312
Goetz.winterfeldt@ <mailto:Goetz.winterfeldt@hdu-deggendorf.de>th-deg.de <http://th-deg.de/>
SKID: goetzwinterfeldt

**Comment by nwhitmont** [comment]
I couldn't find any errors in your bot configuration.  Looks like the problem is on your deployment server.

**Comment by winterfeldt** [comment]
Good morning,

we have checked with another server that was directly positioned in the Internet (exposed system). Again the emulator application does work, while the chat bot refuses to work.
There might be an issue with certificate acceptance in the bot infrastructure? We are using self signed certificates, but will try with issued certificates today. 

Mit freundlichem Gruss
Götz Winterfeldt
-----------------------------------------
Prof. Dr. Götz Winterfeldt
TH Deggendorf
Edlmair Str. 8

94469 Deggendorf

http://innovationslab.th-deg.de/ <http://innovationslab.th-deg.de/>
M : 0049  172 865 2312
Goetz.winterfeldt@ <mailto:Goetz.winterfeldt@hdu-deggendorf.de>th-deg.de <http://th-deg.de/>
SKID: goetzwinterfeldt

**Comment by nwhitmont** [comment]
@winterfeldt did you try deploying the app without the SSL cert?

**Comment by nwhitmont** [comment]
The Bot Framework requires that the x.509v3 certificate exposed by your endpoint be current and valid. Most of the checks for "current and valid" are standard checks for server certs: the CN must match the hostname, it must not be expired, it must not be listed in a CRL, it must have the correct set of EKUs, etc.

Most importantly, your cert must chain to a root certificate authority trusted by Microsoft. The latest list of these CAs is available here: http://social.technet.microsoft.com/wiki/contents/articles/31634.microsoft-trusted-root-certificate-program-participants-v-2016-april.aspx

**Comment by fahadash** [comment]
I resolved this issue by getting a free 90-day cert from ComodoCA. Took me a lot of reading to figure out how to create, sign up for, and incorporate a cert.
