### ISSUE TITLE
[Feature Request] Univeralbot loadSession to use a DialogId and DialogArgs.

### ISSUE THREAD

**Issue by SeanSobey** [Microsoft/BotBuilder#2929]
## System Information (Required)
* SDK Language: NODE
* SDK Version: 3.8.4
* Development Environment: LOCALHOST and Heroku.

## Issue Description
I have implemented an OAuth flow login for my bot, and as one of the steps requires I need to temporarily store and retrieve the bot Address to proactively tell the user the login has succeeded and resume the conversation.

Building on the Univeralbot I am using `loadSession` to do this since `beginDialog` clears the dialog stack and I require the bot to continue the users dialog after this. However, calling loadSession internally starts a dialog with `settings.defaultDialogId || '/'` which makes it unable to redirect to my login dialog at this point. It seems it would make sense to be able to call loadSession with what dialog and args you want to use directly.

## Code Example
To work around this it is possible to do:
```javascript
bot.set('defaultDialogId', this.name + ':endlogin');
bot.set('defaultDialogArgs', { ... });
bot.loadSession(address, (error, session) => {
	bot.set('defaultDialogId', undefined);
	bot.set('defaultDialogArgs', undefined);
	
});
```
But this seems to expose the possibility of bugs cause due to the whole bots defaults now set to one users specific args for a brief period of time. It would be better to do:

To work around this it is possible to do:
```javascript
bot.loadSession(address, this.name + ':endlogin', { ... }, (error, session) => {
});
```

**Comment by SeanSobey** [comment]
I have created a pull request for this feature.

**Comment by xjose97x** [comment]
Any chance this can be ported to the .NET sdk?

**Comment by SeanSobey** [comment]
@xjose97x It appears the .Net SDK does not have this issue since you can maintain the dialog stack between contexts.

I use the Node SDK so am not sure about this, just reading off the [source code](https://github.com/Microsoft/BotBuilder/tree/master/CSharp) and [example usage](https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-proactive-messages), but if you can point out the use case and API's impacted i could take a swing at it.

**Comment by JasonSowers** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
