### ISSUE TITLE
[Question] Why PromptDialog.cs classes are sealed?

### ISSUE THREAD

**Issue by iudelsmann** [Microsoft/BotBuilder#2932]
Hello,

I'm using botframework version 3.8.1 (for .net). The classes in PromptDialog.cs, like PromptString, PromptConfirm are all sealed (with the exception of PromptChoice). I'm trying to create some specialized behavior and basically have to rewrite the code for this classes as I can't extend them. Is there a reason for that?

Thank you

**Comment by nwhitmont** [comment]
@willportnoy @msft-shahins any thoughts?

**Comment by willportnoy** [comment]
You can inherit from `Prompt<string, string>` as a workaround.

(I think the general idea is that PromptString itself wasn't designed for inheritance).

**Comment by JasonSowers** [comment]
@willportnoy PR submitted

**Comment by JasonSowers** [comment]
new PR submitted @willportnoy @msft-shahins

**Comment by iudelsmann** [comment]
Maybe what I'm trying to do is a little hackish, but inheritance will save me from replicating code. Thank you all.

**Comment by nwhitmont** [comment]
follow progress in #2935
