### ISSUE TITLE
[Feature Request] Proactive messages support for Cortana Skills

### ISSUE THREAD

**Issue by nwhitmont** [Microsoft/BotBuilder#2933]
Support proactive messages in Cortana channel.

**Comment by robinsedlaczek** [comment]
I was really confused when I was thinking it is a bug when activities cannot be sent to Cortana after a conversation ended. After discussion with the Azure Functions team, I found this ticket here. We would really appreciate this feature request.

**Comment by gplumb** [comment]
I take it that this hasn't been addressed yet? :-(

**Comment by EricDahlvang** [comment]
This is not yet supported in Cortana, but it is definitely on the radar.

**Comment by gplumb** [comment]
Hi Eric. Presumably its been on the radar since at least June 2017 ;-)  How imminent is this (are we talking weeks or months)?

**Comment by JasonSowers** [comment]
We have no timeline at this time

**Comment by cwhd** [comment]
+1 requesting this feature

**Comment by ak2812** [comment]
This will be a really useful feature. It would be good to know the timeline

**Comment by manishrasrani** [comment]
+1 This feature would be great to have for Cortana initiated conversations on interesting moments.

**Comment by JasonSowers** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
