### ISSUE TITLE
[Question] Unable to integrate with Microsoft Teams

### ISSUE THREAD

**Issue by mobilebilly** [Microsoft/BotBuilder#2938]
## System Information (Required)
* SDK Language: C#
* SDK Version: Microsoft.Bot.Builder 3.8.0.0
* Development Environment: localhost, endpoint exposed via ngrok.io tunneling service

## Issue Description
- I have created a chatbot hosted on my local machine and I have made it public accessible via ngrok.io tunneling service.
- I have registered my bot to botframework.com https://dev.botframework.com/bots?id=travis_dummy
- I was able to integrate it with skype and slack by following the on screen procedure.
- I was able to add my bot "Travis" to Microsoft Teams, but I can never get a response from it.
- The bot is displayed as Bot-f489c62e-a99e-45b6-9686-dc283e5c5fc1 in the Microsoft Team windows client, but displayed as Travis on the Microsoft Teams web application
- There was a warning message at the connector setting of Microsoft Teams at the bot framework portal: "There was a problem synchronizing your bot to Skype."

**Comment by SheriEllisMSFT** [comment]
@mobilebilly  - Hi and thanks for using Teams. I'm a little confused - is this a bot or connector? I thought you said it was a bot and you have registered on the bot framework. If it's a connector, you need to register it on the [Dev portal - here are the instructions](https://msdn.microsoft.com/en-us/microsoft-teams/connectors). And then to sideload it into Teams, you need a manifest.json file. Here are the [packaging instructions on MSDN](https://msdn.microsoft.com/en-us/microsoft-teams/createpackage), and there's a child page with the schema for the manifest. Bots and connectors are populated differently in the manifest. 

If you've created the manifest and sideloaded it, can you poste your manifest here? Thanks and good luck!

**Comment by mobilebilly** [comment]
Hi @SheriEllisMSFT, thanks for your reply. Yes it is a bot (hosted on my local machine), what I did is enable "Microsoft Teams" at the "Connect to channels" section. If it is a bot, do I need to create any connector and/or prepare any manifest files?

![001](https://user-images.githubusercontent.com/795601/27214496-68fc39b8-529f-11e7-9b0f-88bfea78d918.png)
![002](https://user-images.githubusercontent.com/795601/27214497-6915bce4-529f-11e7-9aa3-6a6187fcbf76.png)

There is one warnings message generated,
![003](https://user-images.githubusercontent.com/795601/27214601-e8ae74e6-529f-11e7-92ea-bad152b8213d.png)

**Comment by SheriEllisMSFT** [comment]
@mobilebilly - yes, you need to create a manifest and then sideload it into the desired team in Teams. Here are the [packaging instructions on MSDN](https://msdn.microsoft.com/en-us/microsoft-teams/createpackage), and there's a [child page with the schema for the manifest](https://msdn.microsoft.com/en-us/microsoft-teams/schema). Have you created your manifest yet and did it work? If not, please post your manifest file here and we'll take a look. Good luck!

**Comment by mobilebilly** [comment]
Hi @SheriEllisMSFT , unfortunately, I cannot see any sideload option in the Teams setting, does it require any specific permission under o365?

![teams](https://user-images.githubusercontent.com/795601/27368867-7f155d7e-5687-11e7-8861-920986aed70d.png)

**Comment by SheriEllisMSFT** [comment]
Hi @mobilebilly - take a look at the [Getting Started page on MSDN](https://msdn.microsoft.com/en-us/microsoft-teams/setup). Your 365 Admin needs to enable sideloading of apps for Microsoft Teams. After they do that, down in the bottom right corner, you'll see "Sideload an app" displayed next to "Create a custom bot". Good luck!

**Comment by mobilebilly** [comment]
Hi @SheriEllisMSFT, Thanks for your reply, but our 365 Admin won't allow us to enable the "sideload an app" setting at the moment.

**Comment by bilby91** [comment]
@SheriEllisMSFT Does MS Teams support something like Slack with a shareable link to install the bot ? I guess that all the sideload is for dev testing only.

**Comment by SheriEllisMSFT** [comment]
@bilby91 Yes, sideloading is for testing only. Unfortunately, no, at this time, it is not possible to install bots via a website. But when you publish your app in the Office Store, it will be listed in the appropriate marketplaces. Here is our page describing the store submission process. Hope this helps! Please enquire again if you have additional questions.

**Comment by JasonSowers** [comment]
@SheriEllisMSFT it seems you left out the link you intended to post

**Comment by GomathiSuresh** [comment]
Hi, I have a bot deployed in Azure and has a valid Microsoft App Id and Password , and connected the bot it into Teams and the manifest file follows, but I am not getting reply from bots in teams 
{
    "$schema": "https://statics.teams.microsoft.com/sdk/v1.2/manifest/MicrosoftTeams.schema.json",
    "manifestVersion": "1.2",
    "version": "1.0.0",
    "id": "280b5919-7217-4072-ba52-adaa8e4f8b72",
    "packageName": "com.contoso.helloworld",
    "developer": {
        "name": "Contoso",
        "websiteUrl": "https://www.microsoft.com",
        "privacyUrl": "https://www.microsoft.com/privacy",
        "termsOfUseUrl": "https://www.microsoft.com/termsofuse"
    },
    "name": {
        "short": "BottestHti",
        "full": "To test sample bot in Azure"
    },
    "description": {
        "short": "Hello World App for Microsoft Teams",
        "full": "This sample app provides a very simple app for Microsoft Teams. You can extend this to add more content and capabilities."
    },
    "icons": {
        "outline": "contoso20x20.png",
        "color": "round.png"
    },
    "accentColor": "#60A18E",
    "staticTabs": [{
        "entityId": "com.contoso.helloworld.hellotab",
        "name": "Hello Tab",
        "contentUrl": "https://bottesthti.azurewebsites.net/",
        "scopes": [
            "personal"
        ]
    }],
    "configurableTabs": [{
        "configurationUrl": "https://bottesthti.azurewebsites.net/about",
        "canUpdateConfiguration": true,
        "scopes": [
            "team"
        ]
    }],
    "bots": [{
        "botId": "280b5919-7217-4072-ba52-adaa8e4f8b72",
        "needsChannelSelector": false,
        "isNotificationOnly": false,
        "scopes": [
            "team",
            "personal"
        ]
    }],
    "composeExtensions": [{
        "botId": "280b5919-7217-4072-ba52-adaa8e4f8b72",
        "scopes": [
            "personal",
            "team"
        ],
        "commands": [{
            "id": "getRandomText",
            "description": "Gets some random text and images that you can insert in messages for fun.",
            "title": "Get some random text for fun",
            "initialRun": true,
            "parameters": [{
                "name": "cardTitle",
                "description": "Card title to use",
                "title": "Card title"
            }]
        }]
    }],
    "permissions": [],
    "validDomains": []
}
