### ISSUE TITLE
Can I inspect unrecieved messages?

### ISSUE THREAD

**Issue by rodzillarr** [Microsoft/BotBuilder#294]
Is there somewhere I can go look at messages that have not been received by a client?  For example, messages sent to the direct api that have not been retrieved by the client yet.

**Comment by willportnoy** [comment]
I don't think messages are queued anywhere before they're delivered - all of the messages are sent immediately.  Of course, things like SMS may have their own internal queuing.

**Comment by rodzillarr** [comment]
Is there a way to have messages go to an Azure queue first before being processed, allowing actions to be taken based on some criteria?

**Comment by willportnoy** [comment]
You can have a custom dialog place the messages on the azure queue, to be handled as you desire later by your server code - but then the bot builder SDK is not involved at that point.

Feel free to re-open to discuss more.
