### ISSUE TITLE
[Question] How to access data from excel sheet for bot and display it in table format.

### ISSUE THREAD

**Issue by SGZP** [Microsoft/BotBuilder#2940]
## System Information (Required)
* SDK Language: .NET/C#
* Development Environment: LOCALHOST

## Issue Description
I am using C# for bot development. How can I access excel sheet data (multiple sheets in table structured) and display that data to the bot according to some conditions i.e. How to apply where clause when accessing excel sheet?

**Comment by nrobert** [comment]
This question may be posted on StackOverflow instead of here. Moreover it's more related to accessing Excel Sheet in C# than to Bot Framework problematics

**Comment by msmohan** [comment]
@SGZP Please find an example code here 

[**Excel Bot**](https://github.com/microsoftgraph/botframework-csharp-excelbot-rest-sample) is a sample that demonstrates how to use the Microsoft Graph and specifically the Excel REST API to access Excel workbooks stored in OneDrive for Business through a conversational user interface. It is written in C# and it uses the Microsoft Bot Framework and the Language Understanding Intelligent Service (LUIS).

Note: The code in this sample was originally written for a user experience prototype and does not necessarily demonstrate how to create production quality code.
