### ISSUE TITLE
[Skype Mobile iOS] Signin Card's  button is not responsive on Skype mobile app

### ISSUE THREAD

**Issue by ncomo11** [Microsoft/BotBuilder#2942]
## System Information (Required)
* SDK Language: Node
* SDK Version: 3.8.3
* Development Environment: Bot Service

## Issue Description
SigninCard's  button has below issues on iOS skype bot :
1. Button text is different than what is set in iOS and MacOSX i.e. instead of 'Sign In' it appears as 'Connect'
2. Button click is not working. This issue is even in production environment and URL button is trigerring is a secure url i.e. 'https'

## Code Example
const signInUrl = "https://demo.sumorea.com/login"
    const msg = new Message(session)
        .textFormat(TextFormat.xml)
        .attachments([
            new SigninCard(session)
                .text("Sign in so I know who you are")
                .button("Sign In", signInUrl)
        ]);
    session.send(msg);

## Steps to Reproduce
1. Add a SignCard as in above code
2. Bring the SignIn card in iOS skybot
3. Click on "sign in"/"connect" button

## Expected Behavior
On click of button link should open in browser

## Actual Results
Nothing happens on click of sign in button.

![signcard button not responsive](https://user-images.githubusercontent.com/859748/27121798-4fa34fdc-5106-11e7-85d5-0f5968c5f3e8.jpg)

**Comment by iMicknl** [comment]
Related to #2898. Can you please check which Skype version you are using?

**Comment by fanidamj** [comment]
Hoping that issue has been resolved, closing it. Feel free to reopen if any questions.
