### ISSUE TITLE
[Question] Initiating chat from Bot to user on Microsoft Teams 

### ISSUE THREAD

**Issue by shather** [Microsoft/BotBuilder#2944]
## System Information (Required)
* SDK Language: C#
* SDK Version: 3.8.1.0
* Development Environment: LOCALHOST + ngrok

## Issue Description
When i'm trying to init conversation with user, im getting http 400 Bad Request: "Malformed tenant id"
I've read about https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-connector 
and other issues i.e #2092 
When i'm doing this for Skype, and Skype for Buissnes (preview) it works fine. On MS Teams, im getting this error.

## Code Example
```cs
var botAccount = new ChannelAccount(lastActivity.Recipient.Id, lastActivity.Recipient.Name);
var userAccount = new ChannelAccount(lastActivity.From.Id, lastActivity.From.Name);
var connector = new ConnectorClient(new Uri(lastActivity.ServiceUrl), "appId", "secret");
var conversationId = await connector.Conversations.CreateDirectConversationAsync(botAccount, userAccount); // here im getting http 400
```

I've tried `CreateConversationAsync` as well - with same results. 
I've also tried to pass "tenant" as a Property for bot and user but it didn't help.

## Expected Behavior
conversationId should be fetched.

## Actual Results
HTTP/1.1 400 Bad Request
Content-Length: 65
Content-Type: application/json; charset=utf-8
Server: Microsoft-HTTPAPI/2.0
Date: Wed, 14 Jun 2017 12:50:04 GMT
Connection: close

{"error":{"code":"ServiceError","message":"Malformed tenant id"}}

**Comment by nrobert** [comment]
As described in MS Teams MSDN, you need to provide a tenant to create a 1:1 conversation.

You can use the Nuget package `Microsoft.Bot.Connector.Teams` ([here](https://www.nuget.org/packages/Microsoft.Bot.Connector.Teams)) and use the following method (quite similar as the one already used):
`connector.Conversations.CreateOrGetDirectConversation(channelFrom, channelTo, "yourTenantIdHere");`

In fact if you want to cover all the channels it will look like:
```C#
// Create Conversation
ConversationResourceResponse conversation;
if (channelId != "msteams")
{
    conversation = await connector.Conversations.CreateDirectConversationAsync(channelFrom, channelTo);
}
else
{
    conversation = connector.Conversations.CreateOrGetDirectConversation(channelFrom, channelTo, "yourTenantIdHere");
}
```

I tested it, it's working.

See more documentation here:
https://msdn.microsoft.com/en-us/microsoft-teams/bots1on1#starting-a-11-conversation

**Comment by shather** [comment]
Thanks for your response @nrobert , with that package and your code, it works!

**Comment by pksorensen** [comment]
@nrobert Know if there is a netstandard package solution?  Microsoft.Bot.Connector.Teams is outdated?

**Comment by DamienDoumer** [comment]
@nrobert  This answer might be a few months late, but you can find [here](https://github.com/OfficeDev/BotBuilder-MicrosoftTeams-dotnet) the Microsoft Teams extension, which provides a set of methods to make interactions with Teams easy.

And @shather You can find a detailed post about creating or initiating conversations and sending proactive replies with [your Bot here.](https://doumer.me/proactive-message-bot-in-teams-with-the-botframework-v4-csharp/)

**Comment by Annabelle7989** [comment]
@DamienDoumer how to initiate conversation for 1:1 user, the blog is for sending in a group

**Comment by EricDahlvang** [comment]
@Annabelle7989 This sample demonstrates creating 1:1 conversations for members of a team https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/57.teams-conversation-bot/Bots/TeamsConversationBot.cs#L94

**Comment by Annabelle7989** [comment]
@EricDahlvang No..The members should not be part of a team. I have to send a individual message to 5 people who do not have any team in common.

**Comment by EricDahlvang** [comment]
I haven't tried this, but presumably an Admin could install the app for the users.  At which point the bot should receive an OnTeamsMembersAdded and the bot should be able to message the user in the event handler.  

Here is an example of using Graph to add an App for a user: https://github.com/microsoftgraph/contoso-airlines-teams-sample/blob/283523d45f5ce416111dfc34b8e49728b5012739/project/Models/GraphService.cs#L176
