### ISSUE TITLE
[Slack] ConversationUpdate regression - change in workflow from Slack side

### ISSUE THREAD

**Issue by phillipeloher** [Microsoft/BotBuilder#2945]
Somewhere roughly between May 30th and June 1rst a regression got introduced in botservice for the Slack channel affecting conversationUpdate.  We are using Node.js as our interface into botservice.  Can reproduce on botbuilder@3.8.4.  My guess is that it's likely a change on the Slack side could have regressed the behavior but am not positive.

One common scenario is that we have a bot that stays in a slack channel for long periods of time (e.g. #general channel).  We then trigger off conversationUpdate to capture when new users join the channel.

May 30th behavior (expected) - when a new user (non-bot) joins the channel, that new user is shown in the list of message.membersAdded .

June 1rst behavior - the above is no longer the case.  When a new user (non-bot) joins the channel, that new user is no longer shown in the list message.membersAdded.

**Comment by stevengum97** [comment]
Reading the this [post](https://api.slack.com/changelog/2017-05-rethinking-channel-entrance-and-exit-events-and-messages) from Slack, it looks like they changed their events emitted on users entering channels so the Bot Connector might need to be updated.

It seems that depending on the team/channel size Slack will determine which activities to emit, [`message.channel_join`](https://api.slack.com/events/message/channel_join) (old activity) or [`member_joined_channel`](https://api.slack.com/events/member_joined_channel) (new activity). 

Thanks for reporting this, we'll look into it.

**Comment by craigjensen** [comment]
This is a bug in our Slack channel.  We'll get a fix out asap

**Comment by craigjensen** [comment]
The fix has been deployed.  Please reopen if you are still experiencing the issue.

**Comment by nwhitmont** [comment]
Thank you @craigjensen

**Comment by phillipeloher** [comment]
Fast work, appears fixed.  You guys rock - thank you.
