### ISSUE TITLE
[Question] Prompt Dialog Not Showing Up in Skype

### ISSUE THREAD

**Issue by neetgupta7** [Microsoft/BotBuilder#2947]
Hello
I am making use of PromptDialogs for Confirmation and Choices. While these work fine on emulator and web chat but when I use them on Skype (for personal use on web or ios app) buttons for confirmation and choices do not work. Can somebody please help.
![skype](https://user-images.githubusercontent.com/28854156/27166149-6ad06a50-51b6-11e7-9ce6-6372be5a49e8.PNG)
![web chat screenshot](https://user-images.githubusercontent.com/28854156/27166148-6acbd1fc-51b6-11e7-928b-03681a086e04.PNG)

**Comment by nrobert** [comment]
Can you add more code details of your implementation (or maybe switch to StackOverflow and add all them there)?

I don't have problems on PromptDialog.Choice in a basic case on Skype:

```C#
public async Task StartAsync(IDialogContext context)
{
    List<string> opt = new List<string>
    {
        "One Way",
        "Round Trip"
    };
    PromptDialog.Choice(context, Git2947ResumeChoice, opt, "What type of flight you want to book?");
}

private async Task Git2947ResumeChoice(IDialogContext context, IAwaitable<object> result)
{
    var res = await result;
    await context.PostAsync($"You selected {res}");
}
```

Output is looking like that:
<img width="798" alt="capture d ecran 2017-06-15 a 15 40 04" src="https://user-images.githubusercontent.com/6305666/27183993-ef383316-51e0-11e7-9a9f-19bd0c4c6c31.png">

**Comment by nwhitmont** [comment]
@neetgupta7 Are you using .NET or Node SDK? Can you share the code that is causing the issue?

**Comment by neetgupta7** [comment]
Thanks for your replies. I used Prompt styler as Keyboard instead of auto and that's why it was not working as expected. After making it auto it worked on. BTW I am using .net. Not sure what should be done separately for Keyboard styler.
