### ISSUE TITLE
Dialog stack switch with proactive bots

### ISSUE THREAD

**Issue by ahmettaha** [Microsoft/BotBuilder#295]
I can send the initial message without any problems. However, when the user answers, how can I receive the message as a FormFlow.

For example, the user's dialog stack can be at any state. And if the proactive bots send a message like "How are you?". How can I grab the reply with the appropriate handler, rather then the current dialog stack. Is there a way to change the users active dialog proactively also?

**Comment by chrimc62** [comment]
I'm not sure I understand what you are asking.  When you get a message you can analyze it and decide to launch any dialog including a FormFlow.

**Comment by ahmettaha** [comment]
Sorry. Let me clarify.

Let say the user is messaging with the bot. Like something like below:

User: "Calculate my age"
Bot: "Ok. What day were you born"
User: 23
Bot: "What month were you born"
User: March
Bot: "What year were you born"
User: 1990
Bot: "You are 17 days, 9 months and 26 years old"

Lets assume this is series of prompt dialogs. Because of the nature of prompt dialogs, the bot framework tracks the state of the dialog stack. 

My question is, what would happen if a proactive bot messages the user in the middle of a another dialog. So something like:

User: "Calculate my age"
Bot: "Ok. What day were you born"
User: 23
Bot: "What month were you born"
**Bot: "How are you today"
User: "I'm good thank you"**
User: "March"
Bot: "What year were you born"
User: 1990
Bot: "You are 17 days, 9 months and 26 years old"


At this point how can I push a new dialog to stack by the proactive bot so that the answer would be handled by a different dialog.

**Comment by willportnoy** [comment]
We've started to implement support for interrupting the current dialog stack with a piece of middleware - the current version is at https://github.com/Microsoft/BotBuilder/blob/develop/CSharp/Library/Dialogs/Scorable.cs if you want to give any design feedback.

**Comment by ahmettaha** [comment]
is it possible if you could explain it a little?

**Comment by ahmettaha** [comment]
Also another important aspect is, I'm trying to make use of this in a proactive bot. Would that be possible? When I send a message with a proactive bot, I couldnt really refer it to any existing stack. It seems to just send it as a standalone message that doesnt effect any existing dialog stacks.

**Comment by willportnoy** [comment]
I assume for a proactive bot, it will send its first proactive message then eventually wait for user input.

A piece of "middleware" (implementing IPostToBot) is a decorator for incoming message handling.  The ScoringDialogTask middleware looks at incoming messages and gives components that implement IScorable the opportunity to intercept the message (for example, to look for generic questions like "how are you today") and perform stack manipulations (for example, interrupt the current dialog and add a new dialog at the bottom of the stack).

All of the components that implement IScorable are given an opportunity to score their handling of the incoming message, and the winner actually gets the message delivered to them instead.

IScorable.PrepareAsync allows you do asynchronous work to generate a score, TryScore returns an actual score, and PostAsync is called on the winner with the maximum score.

IScorables can live on the stack or just sit on the side, ready to intercept messages.

**Comment by ahmettaha** [comment]
Got it am I suppose to write something special on here?

Conversation.SendAsync(message, () => XXXX);

The middleware didnt just intercept a regular IDialog by itself. How do I enable it?

**Comment by willportnoy** [comment]
You can either register additional IScorable in the Autofac container, or implement IScorable on your component that implements IDialog, or use the WithScorable fluent-style method to decorate an existing IDialog with an IScorable.

By the way, you're at the bleeding edge here - some of this stuff is subject to change as we learn from implementations.

**Comment by ahmettaha** [comment]
I'll give it a try and let you know how it feels. Thank you. 

Right now, I'am at Microsoft Ventures Accelerator London. We are here to try the bleeding edge :)

**Comment by ahmettaha** [comment]
I have a confusion. From my understanding this is how it works.

I normally extend IDialog. And use Conversation.SendAsync as a starting point. Then I move around the dialogs with Call/Done/Fail methods. I understand the dialog stack structure. 

Now, from my understanding, whenever a message is received, the botbuilder goes through every class that extends IScorable. If they dont exits, then the last IDialog continues from there it was left off. However, if there are multiple IDialogs that also extend IScorable, they they compete to process the new message by comparing their scores. So far correct am I correct?

My confusion is, what is the point of having PostAsync and StartAsync at the same time since I am extending two interfaces of IDialog and IScorable. I see that StartAsync is not called, if I am extending IScorable.


Also, I have never used Autofrac before, how do I register additional IScorable? Does that mean, it becomes global like an MVC Filter? So every message is going to go through all of the registered IScorable extending classes?

Thank you.

**Comment by ahmettaha** [comment]
I got it to work a little. I can make it switch to another dialog in PostAsync like code below. 


    Message toBot = item as Message;
    using (var scope = DialogModule.BeginLifetimeScope(Conversation.Container, toBot))
    {
         var stack = scope.Resolve<IDialogStack>();
        await stack.Forward(new HowAreYouDialog(), null, toBot, CancellationToken.None);
        //stack.Call(new HowAreYouDialog(), null);
    }


But if I use Forward. for some reason I can not return a response with 

    var message = await argument;
    await context.PostAsync(string.Format("You said {0}", message.Text));
    context.Wait(MessageReceivedAsync);


With Call, it doesnt seem to work for some reason.

**Comment by willportnoy** [comment]
We have a "sample" of sorts in the unit test named DialogTask_Frame_Scoring - it's possible that you didn't advance the execution of the underlying fiber with PollAsync.  As we implement IScorable ourselves, we'll have better examples.

**Comment by ahmettaha** [comment]
yeah. I looked into that. It's just difficult to follow because they are unit tests and mock objects. I'll wait for the practical examples I guess. thank you.

**Comment by willportnoy** [comment]
I just checked in one simple example of an IScorable implementation - take at look at https://github.com/Microsoft/BotBuilder/commit/000d1082c99fb54c350d714b9b881de6e575a2c0 - in particular, https://github.com/Microsoft/BotBuilder/blob/000d1082c99fb54c350d714b9b881de6e575a2c0/CSharp/Tests/Microsoft.Bot.Builder.Tests/ScorablesTests.cs.

**Comment by willportnoy** [comment]
I'm going to close this item for now, but feel free to re-open it for further discussion.
