### ISSUE TITLE
[Question] Inconsistency in Activity.Id values on Facebook channel for callback messages

### ISSUE THREAD

**Issue by nrobert** [Microsoft/BotBuilder#2950]
## System Information
* SDK Language: C#
* SDK Version:  Microsoft.Bot.Builder 3.8.1
* Development Environment: Localhost.

Problem is happening for bots deployed on Facebook Messenger channel.

## Issue Description
_The problem here is probably on the non open-source part of the Bot Framework._

There is an inconsistency on the way `Activity.Id` values are managed in Facebook Channel.

- On 'normal' messages, the value of `Activity.Id` is equivalent to Facebook message's id that be can requested from Facebook Graph API (`Activity.Id = "m_" + message.id`)

- On callbacks (like for `CardAction`, or for callback of `Get Started` button), there is no link between those values.

Note: this bug comes from questions on StackOverflow:
https://stackoverflow.com/questions/44546605/callbacks-not-rendered-as-native-facebook-messages
And this question on SO is explaining why the user wants to link Bot and FB Graph API: https://stackoverflow.com/questions/44501474/any-idea-on-how-to-get-this-id-from-the-conversation-between-attendee-and-bot

## Code Example
You can find below a complete Dialog in order to test the behaviour.
It also outputs the values of Activity.Id of each incoming message in order to see the problem.

### Test and display value of Activity.Id
```C#
[Serializable]
public class QuickTesterDialog : IDialog<object>
{
    public async Task StartAsync(IDialogContext context)
    {
        context.Wait(MessageReceivedAsync);
    }

    private async Task MessageReceivedAsync(IDialogContext context, IAwaitable<object> result)
    {
        var activity = await result as Activity;
        await context.PostAsync($"Message received: Activity.Id={activity.Id}, Text={activity.Text}");

        if (activity.Id.StartsWith("mid.$"))
        {
            var msg = context.MakeMessage();

            msg.AttachmentLayout = AttachmentLayoutTypes.Carousel;
            msg.Attachments = new List<Attachment>();
            msg.Text = "updates & support";

            ThumbnailCard thumbnailCard2 = new ThumbnailCard()
            {
                Buttons = new List<CardAction>
            {
                new CardAction ()
                {
                    Value = "Method_HumanSupport",
                    Type = "postBack",
                    Title = "Human support"
                }
            }
            };
            msg.Attachments.Add(thumbnailCard2.ToAttachment());
            await context.PostAsync(msg);
        }
            
        context.Wait(this.MessageReceivedAsync);
    }
}
```

### How to get Facebook Graph API message.Id values:
- Go to [Facebook graph explorer](https://developers.facebook.com/tools/explorer/)
- Select your page in the 1st combobox, get a page access token on the second
- Request `/me/conversations?fields=messages{id,message}`

## Steps to Reproduce
1. Deploy your bot with this Dialog on Facebook Messenger
2. Talk to the bot
3. Check the Activity.Id that will be provided in the reply
4. Click on the "Human support" button on the ThumbnailCard provided in 2nd reply
5. Check the new Activity.Id in reply
6. Compare those 2 Activity.Id with the values in Facebook Graph API.

## Expected Behavior
The Activity.Id value for callback (when clicking the button for example, but also for `Get Started` button) should be equal to the message.Id on facebook graph API for this message (without the `m_`)

## Actual Results
Here is a sample conversation that I made:

<img width="715" alt="exemple valeurs" src="https://user-images.githubusercontent.com/6305666/27175089-640fcbcc-51be-11e7-8c24-0d3b5d8845ee.png">

And the Graph API data corresponding, where I added the _comment fields to explain.
1st message in list is the latest one.
```json
{
    "data": [
        {
            "messages": {
                "data": [
                    {
                        "_comment": "This is the bot reply containing some log info, with the mismatch too",
                        "id": "m_mid.$cAAC3Jml0RcBi3FZcuFcqxEUf0rfE",
                        "message": "Message received: Activity.Id=BiG1AssLxcc, Text=Method_HumanSupport"
                    },
                    {
                        "_comment": "This is the callback when clicking the card",
                        "id": "m_mid.$cAAC3Jml0RcBi3FZWrVcqxEOfnZDq",
                        "message": "Human support"
                    },
                    {
                        "_comment": "This is the message containing the card",
                        "id": "m_mid.$cAAC3Jml0RcBi3FZOLFcqxEE-IjXY",
                        "message": ""
                    },
                    {
                        "_comment": "This is the bot reply containing some log info, here the match is OK",
                        "id": "m_mid.$cAAC3Jml0RcBi3FZL51cqxEDq2cug",
                        "message": "Message received: Activity.Id=mid.$cAAC3Jml0RcBi3FZGm1cqxD-bVYg1, Text=test"
                    },
                    {
                        "_comment": "I'm typing a basic text",
                        "id": "m_mid.$cAAC3Jml0RcBi3FZGm1cqxD-bVYg1",
                        "message": "test"
                    },
                    {
                        "_comment": "This is the bot reply containing some log info, see the mismatch here with previous message id",
                        "id": "m_mid.$cAAC3Jml0RcBi3FY2wFcqxDug04JN",
                        "message": "Message received: Activity.Id=K48z3lUqKTx, Text=customPayload"
                    },
                    {
                        "_comment": "My click on Get Started Button on Facebook which is a callback",
                        "id": "m_mid.$cAAC3Jml0RcBi3FYu4lcqxDmr2oDr",
                        "message": "Get Started"
                    }
                ],
                "paging": {
                    "cursors": {
                        "before": "...",
                        "after": "..."
                    },
                "next": "https://graph.facebook.com/v2.9/...."
                }
            },
            "id": "t_mid.$..."
        }
    ],
    "paging": {
        "cursors": {
            "before": "...",
            "after": "..."
        }
    }
}
```

**Comment by nrobert** [comment]
I would be happy to work on this issue but it's on the connector side, do you think it is possible to discuss with someone working on this side?

**Comment by JasonSowers** [comment]
@msft-shahins  @willportnoy  thoughts?

**Comment by msft-shahins** [comment]
@JasonSowers this is a bug/issue on the connector services. @craigjensen can you take a look?

**Comment by craigjensen** [comment]
It looks like the postback message that Facebook sends when the button is clicked does not contain the original message id [see here](https://developers.facebook.com/docs/messenger-platform/webhook-reference/postback) which is why our Facebook channel creates a new random Activity.Id for the message we send to your bot.  

Maybe you can pass the appropriate message id via the button payload?

**Comment by nrobert** [comment]
Thanks for pointing to this link, I think we cannot do more as long as Postback content is not changed
