### ISSUE TITLE
[Question] Adaptive cards in carousel with Button

### ISSUE THREAD

**Issue by RaoVenka** [Microsoft/BotBuilder#2951]
Is it supporting the carousel cards(Adaptive-Cards with Form Flow or Adaptive-Cards with Dailogs ) with button in  Adaptive cards?. It is possible could you please provide some samples for this.

**Comment by stevengum97** [comment]
To answer your question, here's a [sample ](https://github.com/Microsoft/AdaptiveCards/blob/a91c425a89784130f8e9603762574737d145977c/samples/Integrated/BotFrameworkCarousel.json) from the [AdaptiveCards repo](https://github.com/Microsoft/AdaptiveCards). That said, its availability depends on the channel you are using as some channels are not completely supported.

**Comment by nwhitmont** [comment]
@RaoVenka Are you using .NET or Node SDK?

**Comment by stevengum97** [comment]
I'm marking this as answered and closing it for now. If there are any other questions or comments on the issue, please feel free to post them here.

**Comment by KoenHaemels** [comment]
Is it possible the carrousel doesn't work ?
