### ISSUE TITLE
[Localization] Wrong title for confirm button in Spanish

### ISSUE THREAD

**Issue by vianasw** [Microsoft/BotBuilder#2952]
## System Information (Required)
* SDK Language: NODE
* SDK Version: 3.8.3
* Development Environment: OTHER
## Issue Description
Prompt.confirm with listStyle BotBuilder.ListStyle.button is returning through directline v3 buttons with titles "si" and "no". It should be "sí" with an accent in the letter i.

## Code Example
```
    let options: BotBuilder.IPromptOptions = {
        listStyle: BotBuilder.ListStyle.button,
        maxRetries: 3
    };
    BotBuilder.Prompts.confirm(session, messageText, options);
```

## Expected Behavior
I would expect that this would result in an activity with the buttons 'sí' and 'no'
```
...
 "inputHint": "expectingInput",
      "attachments": [
        {
          "contentType": "application/vnd.microsoft.card.hero",
          "content": {
            "buttons": [
              {
                "type": "imBack",
                "title": "sí",
                "value": "sí"
              },
              {
                "type": "imBack",
                "title": "no",
                "value": "no"
              }
            ]
          }
        }
      ],
...
```
## Actual Results
The actual response contains the button with 'si' without accent (which is incorrect in Spanish).

```
 "inputHint": "expectingInput",
      "attachments": [
        {
          "contentType": "application/vnd.microsoft.card.hero",
          "content": {
            "buttons": [
              {
                "type": "imBack",
                "title": "si",
                "value": "si"
              },
              {
                "type": "imBack",
                "title": "no",
                "value": "no"
              }
            ]
          }
        }
      ],
```

**Comment by greuze** [comment]
Same issue here, it would be nice if the framework would recognize several variations of `yes`: `yep`, `yeah`, `y`, and in Spanish too: `sí`, `si`, `sip`, `s`.

**Comment by nwhitmont** [comment]
@vianasw can you post your code for the Hero Card?

**Comment by nwhitmont** [comment]
Upon further review, it looks like there is a typo in the Spanish localization default phrases where "sí" is listed as "si" (incorrect).

I'll put together a PR with a fix.

**Comment by nwhitmont** [comment]
Follow progress in #2967
