### ISSUE TITLE
[Question] Change string color in MS Teams?

### ISSUE THREAD

**Issue by meganlcooper** [Microsoft/BotBuilder#2955]
Is there a way to change the color of a string that's shown in ms teams? How about the text inside a stringbuilder?

**Comment by SheriEllisMSFT** [comment]
@meganlcooper Hi Megan,
What type of object are you hoping to colorize? You can set the optional TextFormat property to control how your message's text content will be rendered. Here's some more info about [activities, cards and actions](https://msdn.microsoft.com/en-us/microsoft-teams/botsmessages). Does that answer your question? Please post again if not!

**Comment by JasonSowers** [comment]
Going to close this issue, feel free to reopen to continue the discussion.
