### ISSUE TITLE
[Question] Getting exact source accessing Bot Web API

### ISSUE THREAD

**Issue by riteshbhoi** [Microsoft/BotBuilder#2958]
System Information
* SDK Language: <NET/C#>
* SDK Version: <3.8.1.0>
* Development Environment: <AZURE_APP_SERVICE>

I am using Microsoft BOT Builder to create BOT using C#. I have created by Web API and hosted in Azure. I have enabled Microsoft Teams channel for my BOT.

When i try to access my BOT in teams, my Web API gets web requests from a synthetic traffic and that provides incorrect information regarding who is trying to access my BOT. My question is - is it because of Microsoft Team or the Bot Connector which sits between the channel and my BOT web API, and is there any way i can get the real user information who is accessing my BOT web api?

**Comment by nwhitmont** [comment]
@riteshbhoi You can get more detailed information by setting up App Insights in your Azure instance, then register your App Insights ID & Key in the bot portal at https://botframework.com in the Settings page. 

For more information about configuring App Insights for Bot Framework, see:
https://docs.microsoft.com/en-us/bot-framework/resources-app-insights-keys

**Comment by nwhitmont** [comment]
Relates to: https://stackoverflow.com/questions/44577453/incorrect-information-from-source-hitting-bot-web-api

**Comment by riteshbhoi** [comment]
@nwhitmont I am setting up my own Application Insights for the BOT Web API as i want to capture few more telemetry information. Please let me know if there is any way I can resolve above mentioned issue?

**Comment by nwhitmont** [comment]
@riteshbhoi You would need to examine the access logs in your Azure subscription.
