### ISSUE TITLE
[Cortana] SignCard doesn't work with Cortana, but fine with skype

### ISSUE THREAD

**Issue by andy51002000** [Microsoft/BotBuilder#2959]
## System Information (Required)
* SDK Language: C#
* SDK Version: Bot Builder 3.8
* Development Environment: <LOCALHOST with Full IIS>

## Issue Description
My connection button inside the sign-in card disappears when works with Cortana, but Skype is fine. 

## Code Example
```
            var message = activity.CreateReply();
            message.Speak = "This is a Sign-in card";
            message.Summary = "This is a Sign-in card";
            message.Text = "Message Text";
            message.Attachments = new List<Attachment>(){
            new SigninCard("You need to authorize me", new List<CardAction>()
            {
                new CardAction()
                {
                    Value = "https://xxxbot.xxxx.com.tw:8443/account/Login?id="+System.Web.HttpUtility.UrlEncode(activity.From.Id),
                    Type = "signin",
                    Title = "Connect"
                }
            }).ToAttachment()
            };

            await connector.Conversations.SendToConversationAsync(message);
```

## Steps to Reproduce
1. invoke cortana skill
2. Appear sign-in card without connection button

## Actual Results
failed with cirtana
![image](https://user-images.githubusercontent.com/18550249/27209391-09df5aa8-527e-11e7-94ad-3089eb13ffe7.png)

Successed with skype
![image](https://user-images.githubusercontent.com/18550249/27209383-fb847bb4-527d-11e7-8bd6-7befeacb7c9f.png)

**Comment by iMicknl** [comment]
When using a SignIn card on Cortana, you need to add the 'redirect_uri' query string parameter.
https://docs.microsoft.com/en-us/cortana/tutorials/bot-skills/bot-skill-auth

I added `&redirect_uri=http://bing.com/agents/oauth'` to my SignIn Card and it works perfectly. I am not using the redirect uri value in my OAuth login flow, but just adding it to the URL is enough to get the card working in Cortana.

**Comment by nwhitmont** [comment]
Here's a code example for sign-in card for .NET SDK which shows how to configure the URL with `redirect_uri` parameter:
```cs
var message = context.MakeMessage() as IMessageActivity;
message.Speak = "This is a Sign-in card";
message.Summary = "This is a Sign-in card";
message.Text = "Message Text";
message.Attachments = new List<Attachment>(){
    new SigninCard("You need to authorize me", new List<CardAction>()
    {
        new CardAction()
        {
            Value = "https://login.microsoftonline.com/?redirect_uri=http%3a%2f%2fbing.com%2fagents%2foauth",
            Type = "signin",
            Title = "Connect"
        }
    }).ToAttachment()
};
await context.PostAsync(message);
```

**Comment by poumason** [comment]
I also had the problem. 
I already set the redirect_uri in my OAuth URL, such as:
`https://accounts.google.com/o/oauth2/v2/auth?client_id=xxx&redirect_uri=http%3a%2f%2azurewebsites.net/%2fapi%2fOAuthCallback `

But Cortana still can't display Sign-in Card.

I don't know what happened. Please help me, thank you.

**Comment by poumason** [comment]
I try the more sample, such as [SimpleFacebookAuthBot](https://github.com/Microsoft/BotBuilder/tree/master/CSharp/Samples/SimpleFacebookAuthBot) , then the Cortana still doesn't display action button.
Why?

**Comment by iMicknl** [comment]
@poumason what happens if you use the snippet that @nwhitmont provided, which you can also find in the [official documentation](https://docs.microsoft.com/en-us/cortana/tutorials/bot-skills/bot-skill-auth). 

My guess is that the sign-in card only works when you provide the redirect URI for Cortana, `https://www.bing.com/agents/oauth`. I have used this successfully in the past, where adding this redirect_uri was enough to get it to work.

**Comment by poumason** [comment]
I try to use [official documentation](https://docs.microsoft.com/en-us/cortana/tutorials/bot-skills/bot-skill-auth) the sample. 
But it is not work.
I capture my debug log in the Cortana:
`"attachments": [
      {
        "contentType": "application/vnd.microsoft.card.signin",
        "content": {
          "text": "",
          "buttons": [
            {
              "type": "signin",
              "title": "Connect",
              "value": "https://login.microsoftonline.com/?redirect_uri=http%3a%2f%2fbing.com%2fagents%2foauth"
            }
          ]
        }
      }
    ],`

**Comment by nwhitmont** [comment]
@poumason You are commenting on a closed issue. Please open a new issue.

**Comment by nwhitmont** [comment]
Cortana Skills with Bot Framework Developer Preview does not currently support the Sign-In Card workflow on the Cortana channel.

The Cortana team is actively working on integrating this feature, with planned release of this functionality in the next few months.
