### ISSUE TITLE
Handling multiple date with LUIS ?

### ISSUE THREAD

**Issue by JpEncausse** [Microsoft/BotBuilder#296]
Hi,
I'm looking for a best practice, how do you match:

"I want to book a trip to Paris from 17 to 19 of June" (not sure of my english)

- Trip is an intent
- Paris is an entity

But how to match 2 dates ? Using "from/to" ? It's hard if someone say "tomorrow"

**Comment by Stevenic** [comment]
To be honest this is a tricky topic. We're asking the LUIS guys for guidance here. I'll be the first to admit that working with a single date returned from LUIS is difficult and two is even more difficult. They're promising improvements.

**Comment by bluekite2000** [comment]
@Stevenic any update on this? Not just date but also city. For ex from lax to sfo. How can I use luis to distinguish between the 2? Wit.ai has roles. https://wit.ai/docs/recipes#differentiate-several-entities-according-to-their-role-in-the-message

**Comment by Stevenic** [comment]
LUIS has hierarchical entities. You could in theory label the from and to slots as separate "FROM" and "TO" entities. When you get the results back from LUIS you should se 2 separate date entities as well as a separate FROM and TO entities. You can then look at the overlapping character positions to determine which is which

**Comment by v-thgratMSGit** [comment]
Closing this issue. Please open a new issue for further discussion if necessary. Thanks!
