### ISSUE TITLE
[Question] How to deploy botframework on an intranet ?

### ISSUE THREAD

**Issue by Nostreum** [Microsoft/BotBuilder#2962]
Hi ! 

Currently, i've a client accessing the bot framework using directline. So, the bot framework is deployed in Azure. What i want to do is "disconnect" the bot framework from Azure and deploy it locally, on an intranet.  Just for security reason. How can i do that ?

Thanks.

**Comment by nwhitmont** [comment]
The Bot Framework works with bots deployed on any cloud hosting service, as long as you have an internet-accessible endpoint and a valid HTTPS cert.

The Bot Framework requires that the x.509v3 certificate exposed by your endpoint be current and valid. Most of the checks for "current and valid" are standard checks for server certs: the CN must match the hostname, it must not be expired, it must not be listed in a CRL, it must have the correct set of EKUs, etc.

Most importantly, your cert must chain to a root certificate authority trusted by Microsoft. The latest list of these CAs is available here: http://social.technet.microsoft.com/wiki/contents/articles/31634.microsoft-trusted-root-certificate-program-participants-v-2016-april.aspx

For more information on deploying your bot, see: https://docs.microsoft.com/en-us/bot-framework/deploy-bot-overview

Relates to:
https://stackoverflow.com/questions/40888489/bot-framework-without-azure-possible
https://stackoverflow.com/questions/44558760/deploy-bot-in-local-iis-and-incle-it-in-custom-chat-in-a-webpage/44571251#44571251

**Comment by Nostreum** [comment]
Hi,

Thanks for the answer, but after some research and i've some questions. 

1) If i deploy my bot on another cloud hosting service, the bot will still on Azure. Just the connector will be on my cloud, right ? 

2) Can i use the bot framework on a local network ? All channels (directline/webchat...) will not be available, but i just want to know if there is a way to run a code using the botframework on a local network and access it from a client using a "custom directline" that i can create. To resume : Use the botframework without publish it on Azure.

Thanks.

**Comment by nwhitmont** [comment]
#1 - You can deploy your bot to any cloud service as long as it has a valid SSL certificate and supports HTTPS protocol. Your bot will only be on Azure if you deploy it there. 

#2 - You can can expose your bot's API endpoint on your local network or to the public web using NGROK tool. For more information, see: https://ngrok.com/

**Comment by Nordes** [comment]
I guess the short answer is 'NO' you cannot put it on your intranet if you want to keep everything local.
