### ISSUE TITLE
[Direct Line] Unable to add channel to my bot

### ISSUE THREAD

**Issue by ancashoria** [Microsoft/BotBuilder#2965]
## System Information (Required)
* SDK Language: NODE
* SDK Version: 3.7
* Development Environment: LOCALHOST

I am unable to configure Direct Line channel from the botframework portal.

## Steps to Reproduce
1. Create a bot
2. Click on Add Channel -> Direct Line
3. Add a site and click done to save it

## Expected Behavior
Channel is added to the bot

## Actual Results
The error I get is:
<img width="501" alt="screen shot 2017-06-16 at 16 21 52" src="https://user-images.githubusercontent.com/4144110/27228388-10df06a0-52b0-11e7-97ff-f883e8378de4.png">

And the network request returns 
```
Code:  "ServiceError"
Message: "Channel must be configured before it can be enabled"
```

Is there something obvious in the UI that I'm missing? This feature used to work.

**Comment by nwhitmont** [comment]
@ancashoria We are experiencing a problem with the Direct Line channel configuration page in the bot portal at https://botframework.com

We are actively working to fix the issue.

**Comment by nwhitmont** [comment]
The issue has been resolved.

**Comment by ancashoria** [comment]
Thank you very much.
