### ISSUE TITLE
[Skype for Business] Couldn't add skype for business channel to my bot

### ISSUE THREAD

**Issue by kumarss20** [Microsoft/BotBuilder#2966]
## System Information (Required)
* SDK Language: NODE
* SDK Version: v3.7.0
* Development Environment:  AZURE_APP_SERVICE

## Issue Description
When i try to added the Skype for Business channel to my Bot in https://dev.botframework.com/bots?id=MT_BOT site , The website throws an exception

<img width="951" alt="capture" src="https://user-images.githubusercontent.com/29410887/27244517-c5b37a76-529b-11e7-9594-336c4da6cd30.PNG">

**Comment by stevengum97** [comment]
Hi @kumarss20 this issue is currently being investigated by the dev team, we'll provide updates when possible.

**Comment by stevengum97** [comment]
The fix has been deployed so I'm closing this issue. If there are any comments or concerns about the issue, please feel free to discuss it here.
