### ISSUE TITLE
[Question] privateConversationData getting overwritten when 2 concurrent messages are sent at the start of the conversation.

### ISSUE THREAD

**Issue by bhushanvadgave** [Microsoft/BotBuilder#2969]
## System Information (Required)
* SDK Language: NodeJS 7.10
* SDK Version: Bot Builder 3.7
* Development Environment: Bot running locally but accessed by Webchat (through DirectLineJS) over internet through ngrok

## Issue Description
Writing data into privateConversationData not getting saved and accessible to next message dialogs.

## Steps to Reproduce
1. Send 2 messages (concurrently) from webchat using directLineJS APIs.
2. In respective dialogs of these messages set a field into session.privateConversationData.
3. Try to access the these fields in subsequent message dialogs.
4. Only one field set by one of the first 2 messages are seen in session.privateConversationData.

## Expected Behavior
All fields set into session.privateConversationData by all messages should be accessible to subsequent message dialogs.

## Actual Results
Scenario: 
My webchat code sends 2 messages to Bot (using directLine.postActivity) to start the conversation: 1) A Greeting message which invokes greetings:/ dialog and sets GREET:true field in session.privateConversationData. 2) A SetRegion message which invokes setRegion:/ dialogue and sets REGION:UK field in session.privateConversationData and responds with a HeroCard message. 
User clicks on one of the buttons of HeroCard to send a message to Bot. takeAction:/ dialog gets invoked.
In this dialog if I try to access session.privateConversationData, I could see only one field, either GREET:true or REGION:UK, but not both.

My guess is that because 2 messages are send concurrently to initiate the conversation, the bot connector is replacing/overwriting the session created by one message with that of another message.

**Comment by nwhitmont** [comment]
duplicate of #2968?

**Comment by bhushanvadgave** [comment]
Sorry. Issue got posted twice. Closing this issue.
