### ISSUE TITLE
[Question] Authentication through bot framework

### ISSUE THREAD

**Issue by RaoVenka** [Microsoft/BotBuilder#2972]
How to do authentication through Microsoft bot framework.Could please provide some samples too.

**Comment by nwhitmont** [comment]
@RaoVenka are you using .NET or Node SDK?

**Comment by nwhitmont** [comment]
You might want to start by watching this video: https://channel9.msdn.com/Shows/Office-Dev-Show/Office-Dev-Show-Episode-34-Getting-Started-with-Bots-and-the-Microsoft-Graph

Next, you can study this code example which demonstrates a Bot Framework integration with Active Directory. https://github.com/MicrosoftDX/AuthBot

You might also consider looking at the Sign-in Card example, which can also be used to authenticate your bot via web sign-in.

Docs:
- https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-add-rich-card-attachments#add-a-sign-in-card-to-a-message

Code example:
- https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/cards-RichCards
