### ISSUE TITLE
[Question] Can a bot take a parameter from website it is deployed on?

### ISSUE THREAD

**Issue by nupurkamble** [Microsoft/BotBuilder#2975]
I have developed a bot using C# and deployed it using direct line api. I am trying to find a way for the bot to receive a parameter from the website when it initially loads. I want the same bot to work on different websites and want the bot to recognize the website using this parameter sent by the website to the bot and then act according to that website.

**Comment by JasonSowers** [comment]
@nupurkamble Are you able to share your code? Also, can you explain your use cases a little more so we can understand how best to help you?

**Comment by nupurkamble** [comment]
<script>
	var botConnection = new BotChat.DirectLine({
		secret: params['*********']
                token: params['t'],
                domain: params['domain'],
                webSocket: params['webSocket'] && params['webSocket'] === "true" // defaults to true
            });
      BotChat.App({
         botConnection: botConnection,
        user: { id: '***' },
        bot: { id: '***' },
        resize: 'detect'
      }, document.getElementById("bot"));
	  
	  const postButtonMessage = () => {
    botConnection
        .postActivity({type: "event", value: "", from: {id: "me" }, name: "buttonClicked"})
        .subscribe(id => console.log("success"));
    }
    </script>

Okay i saw the link for [Backchannel](https://github.com/microsoft/BotFramework-WebChat) and got the above code.
In this code where do i get the token,domain and websocket values from ?

**Comment by nupurkamble** [comment]
Thanks @JasonSowers 
I saw the link you sent me and it helped. But on [this page](https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-backchannel) is mentioned how to use server side using node.js. Is there a similar code for C# ? i.e how can the bot also listen for events from the client using C#.

**Comment by nupurkamble** [comment]
Thanks @JasonSowers for the link. That is what i was looking for. I'll close the issue.
