### ISSUE TITLE
[Question] Some emojis are not working as true/false values

### ISSUE THREAD

**Issue by greuze** [Microsoft/BotBuilder#2977]
## System Information (Required)
* SDK Language: NODE
* SDK Version: 3.8.3
* Development Environment: LOCALHOST

## Issue Description
In a confirm prompt, some different values can be recognized as `true` or `false`, including [some unicode emijis](https://github.com/Microsoft/BotBuilder/blob/master/Node/core/lib/locale/es/BotBuilder.json#L13). From this 5 unicode characters (\u1F44D,\u1F44C,\u1F44E,\u270B,\u1F590) only one works, the one in the [BMP](https://en.wikipedia.org/wiki/Plane_(Unicode)#Basic_Multilingual_Plane). The other four unicode characters must usesurrogate pairs, in order to work in node.js.

## Code Example
        BotBuilder.Prompts.confirm(session, `True/false question?`);

## Steps to Reproduce
1. The bot uses a confirm prompt.
2. The user replies with 👍 (\u1F44D), 👌(\u1F44C), 👎(\u1F44E) or 🖐(\u1F590)

## Expected Behavior
The unicode characters should be recognized as true/false.

## Actual Results
The reply is not recognized.

**Comment by nwhitmont** [comment]
known issue

**Comment by nwhitmont** [comment]
Thanks for submitting the PR. We will follow the progress there.
