### ISSUE TITLE
[Question] MP4 video as attachment not showing in Microsoft Teams

### ISSUE THREAD

**Issue by tomorgan** [Microsoft/BotBuilder#2980]
## System Information (Required)
* SDK Language: C#
* SDK Version: v4.0.30319
* Development Environment: Azure App Service

## Issue Description
I've created ThumbnailCard with a single Attachment. The attachment links to a MP4 video, using the ContentType 'video/mp4'. I've tested in the Dashboard testing web-embed, and the video renders nicely. However, when deployed to Microsoft Teams the entire reply is not shown.  In the Dashboard, the following Issue is logged: "There was an error completing this request due to an internal channel failure."

**Comment by nwhitmont** [comment]
@tomorgan Thanks for reporting.  Unfortunately MS Teams does not support video card just yet.

**Comment by tomorgan** [comment]
Thanks for the clarification @nwhitmont . Any chance that you could update https://docs.botframework.com/en-us/channel-inspector/channels/Teams?f=Video&e=example1 to mention this? I guess bigger ask is that anywhere in the Channel Inspector, if there is an unsupported combination, this is flagged

**Comment by LizMoreno** [comment]
Hi, @nwhitmont I have error when wanting to show a video card in MS Teams
 MS Teams does not support video card yet?

**Comment by EricDahlvang** [comment]
Hi @LizMoreno 

Video cards are not supported in Teams.  Please refer to the documentation here: https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#cards-not-supported-in-teams
