### ISSUE TITLE
[Question] Idialog Choice not giving an option to select multiple Buttons at the same time

### ISSUE THREAD

**Issue by AmitavaSinha** [Microsoft/BotBuilder#2981]
## System Information (Required)
* SDK Language: C#
* SDK Version: 3.5 
* Development Environment:  Bot Framework, Direct Line

## Issue Description
Multiple Selection is not happening in Bot PromptDialog Choice 

## Code Example
From MessageController 
await Conversation.SendAsync(activity, () => new RootDialog());

RootDialog.cs

1. public virtual async Task MessageReceivedAsync(IDialogContext context, IAwaitable<IMessageActivity> result)
        {
            var message = await result;
           if (message.Text.ToLower().Contains("address"))
           {
                this.ShowAddressOptions(context);
            }
}
2. private void ShowAddressOptions(IDialogContext context)
        { 
             PromptDialog.Choice(context, this.OnAddressOptionSelected, addressOptions, "Do you mean?", "Not a valid option", 3); 
        }
3.  private async Task OnAddressOptionSelected(IDialogContext context, IAwaitable<string> result)
         { 
            try 
             {
                string optionSelected = await result;
                string postMessage = string.Empty;
                string link = string.Empty;
                
                switch (optionSelected) 
                 { 
                     case OfficeOption:
                        string ChangeOfficeAddressMsg = ConfigurationManager.AppSettings["ChangeOfficeAddressMsg"];
                        msgStdURL = objUtility.MakeLink(ChangeOfficeAddressMsg, channelID);
                        await context.PostAsync(msgStdURL);
                        //context.Wait(this.MessageReceivedAsync);
                        //context.Done(true);
                        //await context.PostAsync("Other suggested address change options.");
                        break; 
 
                     case HomeOption:
                        string ChangeHomeAddressMsg = ConfigurationManager.AppSettings["ChangeHomeAddressMsg"];
                        msgStdURL = objUtility.MakeLink(ChangeHomeAddressMsg, channelID);
                        await context.PostAsync(msgStdURL);
                        //context.Wait(this.MessageReceivedAsync);
                        //context.Done(true);
                        
                        break;

                    case NoneOption:
                        string strmsg = "Can you please rephrase your query?";
                        await context.PostAsync(strmsg);
                        //context.Wait(this.MessageReceivedAsync);
                        //context.Done(true);
                        break;
                } 
             } 
            catch (TooManyAttemptsException ex) 
            { 
                 await context.PostAsync($"Ooops! Too many attemps :("); 

                 context.Wait(this.MessageReceivedAsync); 
             }
            finally
            {
                context.Wait(this.MessageReceivedAsync);
            } 
        }
        

## Steps to Reproduce
1. Invoke the RootDialog from Message Controller
2. Makelink to create a hyperlink to show in ChatBot 
3. RootDialog is implemented the PromptDialog Choice

## Expected Behavior
User can select "Home" and "Office" address at a time.

## Actual Results
Currently User can select only one option at a time.

**Comment by nwhitmont** [comment]
not a feature

**Comment by AmitavaSinha** [comment]
So what will be the alternate option ? One clients requirement is that he/she may select more than one option , how to implement the same.

**Comment by EricDahlvang** [comment]
@AmitavaSinha Adaptive Cards might be an option for you.  The ChoiceSet provides for multi-select: http://adaptivecards.io/visualizer/?card=/explorer/cards/Input.ChoiceSet.json

**Comment by AmitavaSinha** [comment]
Thank you Eric, let me implement this and confirm.

**Comment by satyansh-sagar** [comment]
I want this in Skype for business where adaptive card/any card is not supported. Can anyone here help me on this. I want to select multiple items in prompt choices. @msft-shahins @EricDahlvang @nwhitmont

**Comment by EricDahlvang** [comment]
@satyansh-sagar  I do not know of a way to do that in Skype for Business.  I don't think there is a way.
