### ISSUE TITLE
[Question] "Invoke" activity not working for Thumbnail Button on Emulator

### ISSUE THREAD

**Issue by megancooper** [Microsoft/BotBuilder#2983]
## System Information (Required)
* SDK Language: <.NET/C#>

## Issue Description
I want to call a method using a thumbnail card button so I'm using invoke. I can construct the card with no errors but when I click the button nothing happens?

## Code Example

**Code for the Thumbnail Card:**
```
ThumbnailCard card = new ThumbnailCard()
{
        Title = "Thumbnail Card",
        Buttons = new List<CardAction> ()
        {
            new CardAction() { Type = "invoke", Title = "Click Here For Details", Value = "Show Details"}
        }
};
```

**Code in my MessagesController Class**
```
public async Task<HttpResponseMessage> Post([FromBody]Activity activity)
{
      if (activity.Type == ActivityTypes.Invoke)
      {
           // Sends user's Id and Name to BuildDialog Class
           StateClient stateClient = activity.GetStateClient();
           BotData userData = await stateClient.BotState.GetUserDataAsync(activity.ChannelId, activity.From.Id);
           userData.SetProperty<string>("UserId", activity.From.Id);
           userData.SetProperty<string>("Name", activity.From.Name);

           //other properties you want to set.
           await stateClient.BotState.SetUserDataAsync(activity.ChannelId, activity.From.Id, userData);

           await Conversation.SendAsync(activity, () => new Dialogs.BuildDialog());
    }
    var response = Request.CreateResponse(HttpStatusCode.OK);
    return response;
}
```

**Code in the BuildDialog Class that I thought would run but isn't being reached**
```
public Task StartAsync(IDialogContext context)
{
            context.Wait(MessageReceivedAsync);
            return Task.CompletedTask;
}

private async Task MessageReceivedAsync(IDialogContext context, IAwaitable<object> result)
{
       await context.PostAsync($"I've reached DIALOG CLASS");
}
```

## Expected Behavior
For the bot to print: I've reached DIALOG CLASS

## Actual Results
Nothing :/

**Comment by nwhitmont** [comment]
According to the documentation at https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-add-rich-card-attachments#process-events-within-rich-cards

I'm not seeing "Invoke" as a CardAction type.  Can you share where you found the documentation on the "invoke" card action type?

**Comment by megancooper** [comment]
@nwhitmont There was a [post](https://github.com/Microsoft/BotBuilder/issues/2640) on this topic earlier stating that if you specify the card action type as such:
`Type: "invoke"`
It will create an Invoke Activity that can be addressed in the Messages Controller

**Comment by nwhitmont** [comment]
@megancooper Thanks for following up.  Based on [the documentation you linked to](https://msdn.microsoft.com/en-us/microsoft-teams/botsmessages#action---invoke) - the "invoke" `ActivityType` is _specific_ to MS Teams channel.  Are you using MS Teams? If not, then you will need to intercept the message via other methods.

**Comment by megancooper** [comment]
@nwhitmont Yes, I'm using teams. Is my approach correct? So far I've only tried to test this out in the bot emulator. Thanks for the help again!

**Comment by nwhitmont** [comment]
@megancooper Since the "invoke" function you are looking to use is MS Teams specific, you will need to use MS Teams to verify it works. ;-)

**Comment by RichMoeMSFT** [comment]
Correct, this will not work in the Emulator.  In general, your code above looks right, but you'll want to test this in Teams by [creating a Teams app package](https://msdn.microsoft.com/en-us/microsoft-teams/createpackage) and [sideloading](https://msdn.microsoft.com/en-us/microsoft-teams/sideload) into the product.  Or optionally, for 1:1 only, you can start a conversation with your bot using its bot ID from the bot framework.

**Comment by megancooper** [comment]
@nwhitmont @RichMoeMSFT Thanks for the help, these seem to work for me :)
