### ISSUE TITLE
[MS Teams] User ids are inconsistent for the teams channel

### ISSUE THREAD

**Issue by v46** [Microsoft/BotBuilder#2984]
I am seeing that the user ids returned by the bot framework keep changing every few days. 
This prevents us from identifying individual users since their ids are no more the same. 

The problem is observed for the Teams channel. There are no changes made on the Teams admin side, so we are not sure why the framework is returning different ids. I presume the user ids are encrypted, is it expected that clients decrypt this content or use it as-is?

We are using Node js and the latest SDK ^3.8.2.

**Comment by RichMoeMSFT** [comment]
Are you referring to the from.id your bot receives?  In general, the user id should be unique and consistent for a given user for a given bot.  It is an encrypted value based on, among other things, your bot guid, and again should not change.  Please provide more information so we can investigate.

**Comment by v46** [comment]
Yes @RichMoeMSFT. This is the "address.user.id" component returned by the node SDK. 
```
"address":{"id":"1498022462221","channelId":"msteams","user":{"id":"29:1iJ.....","name":"John Doe"}
```
Previously the user's id was ```29:1IivS...``` and now ```29:1iJ3y...``` is returned (sorry, this may not be useful without the full id).

I am happy to share the bot id/tenant id/user id privately if it helps narrow the issue down. Please let me know.

**Comment by RichMoeMSFT** [comment]
We haven't heard any other issues about this, and in fact we have multiple partners caching user information around this ID which would badly break their experience.  I'd like to investigate further, please reach out to me directly.

**Comment by JasonSowers** [comment]
please reopen this issue if needed
