### ISSUE TITLE
Closed

### ISSUE THREAD

**Issue by hardikchoudhary** [Microsoft/BotBuilder#2985]

**Comment by JasonSowers** [comment]
@hardikchoudhary can you please provide information so we can assist you?  Right now we have basically nothing to work with.

**Comment by hardikchoudhary** [comment]
Hi jason

I have the folder of my applicatiob...... Name xyz.... In that folder i
have app.js and other js files and one folder with npm_modules that is
having multiplw folder....

I have deployed it using visual studio

To azure wep app

But wheb debug my bot.
In bot emulator.... Giving url of azure website /api/messages

And app id and passwrd

Connect getting error in logs.... Https://azurewebsite not found

404

Olease helpe me for same... Or m i deploying wrong


Thanks
Hardik

**Comment by JasonSowers** [comment]
Hi Hardik,

Try following this guide to [deploy to Azure](https://blog.botframework.com/2017/04/27/Deploying-Botframework-To-Azure-On-Linux/)

**Comment by hardikchoudhary** [comment]
Hi jason

I have followed same as my files are deployed as I am getting this message 

You do not have permission to view this directory or page.

**Comment by hardikchoudhary** [comment]
I have not added the app id and password in app service in azure

**Comment by hardikchoudhary** [comment]
can you please tell me how i can debug node js bot when it is deployed to azure

**Comment by hardikchoudhary** [comment]
but i have added in app.js file directly app id and password

**Comment by nwhitmont** [comment]
You need to save your Microsoft App ID and password in your Application Settings in order for your bot to function properly.

**Comment by hardikchoudhary** [comment]
nwhitmont  i have added it in application setting as well on azure 

but still the same error
There was an error sending this message to your bot: HTTP status code NotFound

![image](https://user-images.githubusercontent.com/14367146/27343774-94e10c1a-5601-11e7-852e-37a8c044f57b.png)


and error on web chat below my message

**Comment by nwhitmont** [comment]
what is your bot name, bot handle and App ID as you registered in the Bot Portal?

**Comment by hardikchoudhary** [comment]
Bot handle : NearByMetro
url : https://nearbymetro.azurewebsites.net/api/messages
app id
3dfa0867-614d-40d2-8092-08fd56df09f6

Please let me know if you need more info

**Comment by hardikchoudhary** [comment]
Bot name :NearByMetro
Bot handle : NearByMetro
url : https://nearbymetro.azurewebsites.net/api/messages
app id
3dfa0867-614d-40d2-8092-08fd56df09f6

Please let me know if you need more info

**Comment by hardikchoudhary** [comment]
@nwhitmont 
Bot name :NearByMetro
Bot handle : NearByMetro
url : https://nearbymetro.azurewebsites.net/api/messages
app id
3dfa0867-614d-40d2-8092-08fd56df09f6

Please let me know if you need more info

**Comment by nwhitmont** [comment]
Your bot's endpoint is not online.  When I visited your endpoint URL just now I got the error: `The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.`

**Comment by hardikchoudhary** [comment]
how my this url is online???
https://nearbymetro.azurewebsites.net/api/messages

but I am able to run https://nearbymetro.azurewebsites.net/

how bot endpoint is online please help me where I am wrong

I have just published my whole solution 

to http://nearbymetro.azurewebsites.net/ from Visual studio

and in package.json starting path is app.js

**Comment by hardikchoudhary** [comment]
Please tell me for same ???? how this endpoint can be online ???? and you are looking for this url 

but how possible ??

can i hardcode this url in code ???

as locally it is running

**Comment by hardikchoudhary** [comment]
@nwhitmont  can you please help as i am stuck

do i need to change any of these lines

server.listen(process.env.port || process.env.PORT || 3978, function () {
   console.log('%s listening to %s', server.name, server.url); 

});

**Comment by nwhitmont** [comment]
@hardikchoudhary Your bot URL currently returns 500 error, which means there is an error in your deployment. 

Have you tried creating a bot via [Azure Bot Service](https://azure.microsoft.com/en-us/services/bot-service/?v=17.23h)? When you use this method, all the deployment aspects are configured automatically, and there are built-in bot application templates to get you started.

For more information on deploying your bot to Azure, see: [Deploy a bot to Azure from Visual Studio](https://docs.microsoft.com/en-us/bot-framework/deploy-bot-visual-studio)

**Comment by hardikchoudhary** [comment]
solved issue 
now its working thanks


alot sir

and now its working on skype as well as normal chat box 

but it is not working on fb messenger and neither is showing error

**Comment by nwhitmont** [comment]
@hardikchoudhary thanks for the update. Glad to hear you got it working!

**Comment by NehaGawri** [comment]
Hi Team , 

My code is working fine locally . And I have deployed it by following azure official documentation.
But I am getting error as "There was an error sending this message to your bot: HTTP status code NotFound" when testing in web chat . Could you please help ?

**Comment by abhi-freebird** [comment]
> Hi Team ,
> 
> My code is working fine locally . And I have deployed it by following azure official documentation.
> But I am getting error as "There was an error sending this message to your bot: HTTP status code NotFound" when testing in web chat . Could you please help ?

I am facing the same issue. Everything was working fine till previous deployment. Did you manage to find any workaround?

**Comment by AdamRussak** [comment]
hi, 
I'm trying to deploy the echo bot just for testing and I am getting `There was an error sending this message to your bot: HTTP status code NotFound`
I'm using the following manual: https://docs.microsoft.com/en-us/composer/how-to-publish-bot#deploy-bot-to-azure

and its working but in the end, I'm getting the above error.
please assist

**Comment by NereaCabiedasMoreno** [comment]
I have made a bot with Node.js locally, then in the Azure platform I have created a bot channel registration and in the messaging endpoint I have put the address of the server where I have uploaded and the bot is executed (https: // ___ : 3978 / api / messages), with this address the bot in the bot framework emulator works for me, on the other hand, in the channel registration bot I have created a channel to test the web chat but I get the following error "There was an error sending this message to your bot: HTTP status code NotFound ", I need help

**Comment by nadiasorina** [comment]
> I have made a bot with Node.js locally, then in the Azure platform I have created a bot channel registration and in the messaging endpoint I have put the address of the server where I have uploaded and the bot is executed (https: // ___ : 3978 / api / messages), with this address the bot in the bot framework emulator works for me, on the other hand, in the channel registration bot I have created a channel to test the web chat but I get the following error "There was an error sending this message to your bot: HTTP status code NotFound ", I need help

I have the same problem. Did you find the solution?

**Comment by nadiasorina** [comment]
> Hi Team ,
> 
> My code is working fine locally . And I have deployed it by following azure official documentation.
> But I am getting error as "There was an error sending this message to your bot: HTTP status code NotFound" when testing in web chat . Could you please help ?
I have made a bot with Node.js locally, then in the Azure platform I have created a bot channel registration and in the messaging endpoint I have put the address of the server where I have uploaded and the bot is executed (https: // ___ : 3978 / api / messages), with this address the bot in the bot framework emulator works for me, on the other hand, in the channel registration bot I have created a channel to test the web chat but I get the following error "There was an error sending this message to your bot: HTTP status code NotFound ", I need help

I have the same problem. Did you find the solution?

**Comment by JasonSowers** [comment]
Well don't put the port number in the url for one thing, and definitely not spaces in the url like the post you quoted.

  https;//myawesomebot.azurewebsites.net/api/messages
  https://awesomecustomdomain.com/api/messages
  
  
![image](https://user-images.githubusercontent.com/6301037/122592556-0a99fd80-d02a-11eb-97bd-c0ba74c4b87f.png)

**Comment by nadiasorina** [comment]
I don't have a number there, but I still have errors...

vin., 18 iun. 2021, 19:41 D4RKCIDE ***@***.***> a scris:

**Comment by ylt1534** [comment]
Is there any update here? hit the issue still....
