### ISSUE TITLE
[Localization] CurrentCulture is reset after async/await

### ISSUE THREAD

**Issue by NicolasHumann** [Microsoft/BotBuilder#2986]
## System Information
* SDK Language: NET/C#
* SDK Version: 3.8
* Development Environment: AZURE_FUNCTION PRECOMPILED

## Issue Description
Hi, The Thread.CurrentThread.CurrentCulture and Thread.CurrentThread.CurrentUICulture is reset after a async/await call like HttpClient. The Culture is correctly set from the Locale property in SetAmbientThreadCulture and LocalizedScope but is reset after an asyn /await call.
The bug only exist in Azure function with precompiled dll, but it works fine in localhost with AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\func.exe

## Workaround
The workaround is to set  CultureInfo.DefaultThreadCurrentCulture and CultureInfo.DefaultThreadCurrentUICulture.
`public struct MyLocalizedScope : IDisposable
{
    private readonly CultureInfo previousCulture;
    private readonly CultureInfo previousUICulture;

    public MyLocalizedScope(string locale)
    {
        this.previousCulture = Thread.CurrentThread.CurrentCulture;
        this.previousUICulture = Thread.CurrentThread.CurrentUICulture;

        if (!string.IsNullOrWhiteSpace(locale))
        {
            CultureInfo found = null;
            try
            {
                found = CultureInfo.GetCultureInfo(locale);
            }
            catch (CultureNotFoundException)
            {  
            }

            if (found != null)
            {
                Thread.CurrentThread.CurrentCulture = found;
                Thread.CurrentThread.CurrentUICulture = found;

                CultureInfo.DefaultThreadCurrentCulture = found;
                CultureInfo.DefaultThreadCurrentUICulture = found;
            }
        }
    }

    public void Dispose()
    {
        Thread.CurrentThread.CurrentCulture = previousCulture;
        Thread.CurrentThread.CurrentUICulture = previousUICulture;

        CultureInfo.DefaultThreadCurrentCulture = previousCulture;
        CultureInfo.DefaultThreadCurrentUICulture = previousCulture;
    }
}`

**Comment by mindingdata** [comment]
This issue is notorious when apps move to async/await patterns (Mostly in console/windows service apps). 

Check the second answer in this SO question https://stackoverflow.com/questions/30662668/keep-currentculture-in-async-await . Essentially you need to build your own synchronization context that does a "handover" of what culture should be used when a thread picks up an async task.

**Comment by fanidamj** [comment]
Hoping that issue has been resolved, closing it. Feel free to reopen if any questions.
