### ISSUE TITLE
[Skype] Botframework publishing review issue

### ISSUE THREAD

**Issue by Cartman720** [Microsoft/BotBuilder#2988]
## System Information
SDK Language: NODE
SDK Version: 3.8.4
Development Environment: server

## Issue Description
Hi

I have an issue with publishing my bot.
I am trying to submit for review,but system says that my server sent 403 error.
I have looked at my server logs and saw that microsoft sends request and within body of request there is property  `channelId: "test"`, but `ChatConnector` of `botbuilder` package don't accept such `channelId` 
and I got this error

> ChatConnector: receive - endorsements validation failure. channelId in req.body: test didn't match the endorsements: bing,directline,email,facebook,groupme,kik,skype,slack,sms,telegram,webchat.

this is request from [dev.botframework.com](url)

```
{ type: 'ping',
  id: '6rQ0LAG7X2Q',
  timestamp: '0001-01-01T00:00:00',
  serviceUrl: 'https://dev.botframework.com/',
  channelId: 'test',
  from: { id: 'portal' },
  conversation: { id: 'ping' },
  recipient: { id: 'bot' } }

```

What I have missed or how can I submit my app fro review?

**Comment by nwhitmont** [comment]
@Cartman720 Can you post a screenshot of the error you are seeing in the Bot Portal?

**Comment by Cartman720** [comment]
Sure, here it is.

![image](https://user-images.githubusercontent.com/12465135/27343816-2ebeadf4-55f5-11e7-9f8b-6b85820c9a28.png)

**Comment by nwhitmont** [comment]
Relates to #2979

**Comment by nwhitmont** [comment]
There's a problem with the publishing workflow. We are actively working to fix the issue.

**Comment by nwhitmont** [comment]
@Cartman720 Should be fixed now. Can you verify if its working for you?

**Comment by nwhitmont** [comment]
Fix is deployed

**Comment by Cartman720** [comment]
Hi @nwhitmont 

I think it works!
Thanks!
![image](https://user-images.githubusercontent.com/12465135/27361636-d62af360-5639-11e7-9217-5cc6c0effff3.png)
