### ISSUE TITLE
[Facebook] Wrong title text on button carousel on facebook

### ISSUE THREAD

**Issue by iudelsmann** [Microsoft/BotBuilder#2991]
Hello,

I'm using C# version 3.8.1.

When sending buttons to facebook, like when using `PromptDialog.Choice`, with more than 3 buttons, a carousel is used to to display those buttons. I expected the same title to be displayed for each carousel "bubble" (is that how it's called?) but the text **Options** is shown after the first one.

Here is a print for example, you can see the beggining of the second bubble on the right:

![image](https://user-images.githubusercontent.com/13850950/27351876-2b9b4d78-55d5-11e7-8706-835404faaad1.png)

I tried to figure out the problem but could only find that for facebook "generic" template, the JSON to be sent needs a "elements" array and a "title" property for each element. (https://developers.facebook.com/docs/messenger-platform/send-api-reference/generic-template)

PS: It works on Skype (more than 5 buttons).

**Comment by JasonSowers** [comment]
Do you mind posting your code so I can take a look and reproduce?

**Comment by iudelsmann** [comment]
Ok, the method that generates the prompt is inside the root dialog and is like this (I altered unrelated things to simplify):

```csharp
private Task ShowBotOptionDialog(IDialogContext context)
{
        var options = new List<string> { "Buttom 1", "Buttom 2", "Buttom 3", "Buttom 4" };

        PromptOptions<string> promptOptions = new PromptOptions<string>("Text should be displayed on all bubbles", options: options);
        PromptDialog.Choice(context, this.OnOptionSelected, promptOptions);

        return Task.CompletedTask;
}
```

**Comment by iudelsmann** [comment]
Using facebooks endpoint to send the message I'm observing the expected behavior with this JSON

https://graph.facebook.com/v2.6/me/messages?access_token=ACCESS_TOKEN_HERE

```json
{
   "recipient":{
      "id":123456
   },
   "message":{
      "attachment":{
         "type":"template",
         "payload":{
            "template_type":"generic",
            "elements":[
               {
                  "title":"Text should be displayed on all bubbles",
                  "buttons":[
                     {
                        "type":"postback",
                        "title":"Button 1",
                        "payload":"Button 1"
                     },
                     {
                        "type":"postback",
                        "title":"Button 2",
                        "payload":"Button 2"
                     },
                     {
                        "type":"postback",
                        "title":"Button 3",
                        "payload":"Button 3"
                     }
                  ]
               },
               {
                  "title":"Text should be displayed on all bubbles",
                  "buttons":[
                     {
                        "type":"postback",
                        "title":"Button 4",
                        "payload":"Button 4"
                     },
                     {
                        "type":"postback",
                        "title":"Button 5",
                        "payload":"Button 5"
                     },
                     {
                        "type":"postback",
                        "title":"Button 6",
                        "payload":"Button 6"
                     }
                  ]
               }
            ]
         }
      }
   }
}
```

So if my guess that this JSON is being wrongly generated, could this be a connector issue?

**Comment by iudelsmann** [comment]
No one else has this problem? Is anyone looking into this?

**Comment by fanidamj** [comment]
Hoping that issue has been resolved, closing it. Feel free to reopen if any questions.
