### ISSUE TITLE
[Question] Bot using LUIS app without using Azure cloud service

### ISSUE THREAD

**Issue by panosVeran** [Microsoft/BotBuilder#2995]
i built a bot that uses LUIS app. i  want to use the endpoint provided outside azure, with no 1000 limit. so, to my understanding i need a new key to use for production purposes to create an endpoint. how should i do this? do i buy an azure key? how do i add a new valid key?

**Comment by nwhitmont** [comment]
@panosVeran Are you using .NET or Node SDK?

**Comment by panosVeran** [comment]
@nwhitmont node, how is this relevant considering the key and the endpoint however?

**Comment by nwhitmont** [comment]
@panosVeran There are two SDKs managed in this repository. We ask this question to all GitHub users so we can better route your issue to the relevant .NET or Node SDK engineers.

For more information on managing your LUIS application keys, see: [Creating Subscription Keys Via Azure](https://docs.microsoft.com/en-us/azure/cognitive-services/LUIS/azureibizasubscription)

>For unlimited traffic to your HTTP endpoint, you must create a metered key for your account on LUIS. Metered keys provide unlimited traffic to your endpoint following a payment plan. 

See [Cognitive Services pricing](https://azure.microsoft.com/en-us/pricing/details/cognitive-services/language-understanding-intelligent-services/?v=17.23h) for complete pricing details.

**Comment by panosVeran** [comment]
@nwhitmont got it, thnks
