### ISSUE TITLE
[Question] Update to Bot Builder 3.5+ or compatible security configuration by July 31, 2017

### ISSUE THREAD

**Issue by ftachon** [Microsoft/BotBuilder#2996]
## System Information (Required)
* SDK Language: REST API
* SDK Version: 3.1
* Development Environment: OTHER (REST Services)

## Issue Description
The portal https://dev.botframework.com alert me to Update to Bot Builder 3.5+ or compatible security configuration by July 31, 2017

## Code Example
All the security requirement described in https://docs.microsoft.com/en-us/bot-framework/rest-api/bot-framework-rest-connector-authentication
are guaranteed.

## Steps to Reproduce the Issue
1. Go to https://dev.botframework.com -> My Bots
2. Sign in
3. Selected a Bot
4. Now you can see the warning on page top
## Expected Behavior
Be sure my bots will work after July 31

## Actual Results
![botuodate3_1](https://user-images.githubusercontent.com/23745574/27381379-889ffe74-567a-11e7-848c-0512617b9568.png)

**Comment by nwhitmont** [comment]
@ftachon This is a warning for informational purposes only. It does not affect the functioning of your bot.
