### ISSUE TITLE
[Question] The LUISModel doesn't work with subscription key for LUIS Endpoint for EAST US Location

### ISSUE THREAD

**Issue by akashpavate58** [Microsoft/BotBuilder#2998]
## System Information (Required)
* SDK Language: .NET/C#
* SDK Version: Microsoft.Bot.Builder v3.8.1
* Development Environment: LOCALHOST, Facebook Messenger

## Issue Description
My LUIS Model was published with a free trial key (Bootstrap Key) and my code was perfect.
the URL for LUIS was https://westus.api.cognitive.microsoft.com.............

Then I took a new LUIS key from Azure with Location as "EAST US" and added it to my LUIS and published it. Now the URL changed to https://easttus2.api.cognitive.microsoft.com.............

Then I also added the new key to my C# code.
[LuisModel("AppID", "SubscriptionKey")]
    [Serializable]
    public class ParentDialog : LuisDialog<PizzaOrder>
    {}

This started giving me an access denied exception.

## Steps to Reproduce the Issue
1. Build a simple model in LUIS and publish with a Bootstrap key.
2. Integrate it with the C# code and test it.
3. Now add a new key from Azure but while creating the key, set Location to EAST US.
4. Now integrate this new key with LUIS Model and add it to the BotCode.
5. You will get an access denied exception.
6. Now add a key from azure with Location as West US and set it up in LUIS and BotCode.
7. It works properly.

## Expected Behavior
Should work with EAST US Key. 

## Actual Results

##MyDetails:
Please reach me at akashpavate58@gmail.com and I can help you reproduce the same error.

**Comment by stevengum97** [comment]
Hi @akashpavate58, have you tried adding the domain to your C# code? It's probably still pointing at westus by default. You can find details [here ](https://github.com/Microsoft/BotBuilder/issues/513#issuecomment-306667584) from issue #513 that might help you.

Code excerpt from #513:
```csharp
[LuisModel("XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXX", "XXXXXXXXXXXXXXXXX", domain: "eastus2.api.cognitive.microsoft.com", staging: true)]
[Serializable]
public class LocalLUISDialog : LuisDialog
{
```

**Comment by akashpavate58** [comment]
Thank you very much. It works..!! I think this has to go in the documentation.

**Comment by stevengum97** [comment]
I'm glad it worked 🙂 I agree on it needing to go into the documentation. I'm leaving this open for now until a PR is formed update our docs.

**Comment by DeniseMak** [comment]
PR for doc update: https://github.com/MicrosoftDocs/bot-docs-pr/pull/164

**Comment by stevengum97** [comment]
Thanks Denise 🙂 

Closing Issue.
