### ISSUE TITLE
[Channel Configuration] After adding a channel it can't be deleted

### ISSUE THREAD

**Issue by dmitryfd** [Microsoft/BotBuilder#2999]
## System Information (Required)
* SDK Language:  Node
* SDK Version:  3.8.4
* Development Environment:  Azure App Service

## Issue Description

After adding a channel at the portal: [https://dev.botframework.com/bots/channels?id=MyBotId](https://dev.botframework.com/bots/channels?id=MyBotId), it's only possible to disable but not remove it. 

In the case of Skype for Business that has no disable button, this makes the channel active forever.

## Code Example

N/A

## Steps to Reproduce the Issue
1. Create a bot using the portal
2. Add Skype for Business channel
3. Attempt to delete it
4. No luck :(

## Expected Behavior

Being able to delete the channel.

## Actual Results

The channel(s) are stuck in the list forever, with only options to **disable** then (but not delete).

## Need a repro?
Feel free to contact me here or via [dmitc@microsoft.com](mailto:dmitc@microsoft.com)

**Comment by nwhitmont** [comment]
@dmitryfd Thanks for reporting.  Issue tracked internally

**Comment by PieterT2000** [comment]
What is the status of this?
