### ISSUE TITLE
Cannot resolve LUIS date/time because of missing resolution_type

### ISSUE THREAD

**Issue by LukasMasuch** [Microsoft/BotBuilder#30]
I'm not able to resolve the LUIS date/time by using the resolveTime function. The problem seems to be that the resolution_type is not set in the entity.resolution object. As a workaround, I'm currently setting the resolution_type manually for every entity before calling resolveTime:
```JavaScript
args.entities.forEach((entity) => {
    if (entity.resolution) {
        entity.resolution.resolution_type = entity.type;
    }
});
```

**Comment by Stevenic** [comment]
Sorry about that... LUIS pushed a bunch of schema changes at the same time we were rolling out the framework so we're kind of trying to react to that.

**Comment by Stevenic** [comment]
Actually... I just tried the using the built in Cortana app and I see a resolution type. Could you possibly share a dump of the JSON you're getting from LUIS. The prebuilt app and regular apps do tend to return different JSON.

**Comment by Stevenic** [comment]
I just published a fix.
