### ISSUE TITLE
Emulator stopped working

### ISSUE THREAD

**Issue by miguelarian** [Microsoft/BotBuilder#300]
"The emulator has stopped working" do anyone gets the same exception when running the emulator? How can I fix it? I am using Windows 10 64bits

**Comment by tomlm** [comment]
Are you running multiple copies?  It opens a server on a port for callbacks, so only one copy can be run at a time.

**Comment by miguelarian** [comment]
It might be my firewall... What port does the app open? I will double check it, maybe it is not a bug...

**Comment by hradoi** [comment]
When you click run in Studio, it opens the one after localhost.

**Comment by miguelarian** [comment]
Thanks @hradoi but it doesn't work. Please let me know if I am doing something wrong.

1) I click run on Visual Studio. I am using local IIS.
2) I open the executable "Bot Framework Emulator.application"

This is what I get:

![image](https://cloud.githubusercontent.com/assets/10966174/15355836/0b98f29a-1ced-11e6-9152-83f364a76130.png)

**Comment by tomlm** [comment]
9000

Sent from my tumbs
________________________________

**Comment by tomlm** [comment]
The emulator uses port 9000, something has port 9000 open. Run:
netstat -a -o
And it will list the process ID of the process which has port 9000 open.  Go to task Manager and find the process with that Process ID and you will know what process has it open

**Comment by GJPVN** [comment]
AM experiencing the same issue with Bot Emulator. Checked use of port 9000. No such usage seen still error comes. Am running on Windows 8.1 , 64bit OS. Appreciate help to resolve the issue.

![image](https://cloud.githubusercontent.com/assets/9302456/15447295/8da55056-1f5b-11e6-9e40-78322209c6b3.png)

**Comment by G1la0** [comment]
Is there a way to change the emulator port from 9000 to another port? I've a system process using that port and I can't change it.

**Comment by tkbox9** [comment]
@tomlm I'm having the same problem. Also, there's no process using the 9000 port. Is there any other recommended solution?

[Debug]
An unhandled exception of type 'System.NullReferenceException' occurred in Microsoft.Bot.Connector.Emulator.Core.dll

**Comment by ryanvolum** [comment]
@tomlm I'm in the same boat as @tkbox9. The emulator immediately throws the exception even though there doesn't seem to be any other process using port 9000. Any insight would be much appreciated!

**Comment by ryanvolum** [comment]
Issue resolved - the app is storing state in %tmp% in a file called "BotFramework.Emulator.Session". It persists the url, appid and appsecret. Deleting this file should fix the issue!

**Comment by pkrebs01** [comment]
Deleting BotFramework.Emulator.Session file didn't work for me. Deleting BotFramework.Emulator.Port file did.
