### ISSUE TITLE
[Adaptive Cards] Alternative for imBack

### ISSUE THREAD

**Issue by jinot92** [Microsoft/BotBuilder#3001]
I wish to send a message in a manner which is similar to a message sent by imBack. 
I am using adaptive cards in a web chat so I cannot use(rather don't know how to use) imBack on the button click of the adaptive card.
Is there any way to implement this feature. 

## Actual Results

![present](https://user-images.githubusercontent.com/26137758/27404851-3042310c-56ed-11e7-8a69-54ba581d6fc0.png)
## Expected Behavior

![expected](https://user-images.githubusercontent.com/26137758/27404859-35fbefac-56ed-11e7-9c01-fde8a56eff84.png)

**Comment by nwhitmont** [comment]
@jinot92 Are you using .NET or Node SDK for BotBuilder?

**Comment by jinot92** [comment]
Node SDK

**Comment by nwhitmont** [comment]
Adaptive Cards don't support imBack messages. The available [card actions](http://adaptivecards.io/documentation/#create-GettingStarted) are as follows:
Actions add buttons to the card. They don't define the logic of the actions, but use the predefined action types instead.

- Action.OpenUrl - the button opens an external URL for viewing
- Action.ShowCard - Requests a sub-card to be shown to the user.
- Action.Http - Requests that all of the input data is gathered up and sent via an HTTP call
- Action.Submit - Ask for all of the input elements to be gathered up into an object which is then sent to you through some method defined by the host application.

Example Action.Submit: With Skype, an Action.Submit will send a Bot Framework bot activity back to the bot with the Value property containing an object with all of the input data on it.

**Comment by AndreMantas** [comment]
> Example `Action.Submit: With Skype, an Action.Submit will send a Bot Framework bot activity back to the bot with the Value property containing an object with all of the input data on it.

Is this still true?
I'm testing adaptive cards with AdaptiveSubmitAction's in skype and cant get any activity in the bot when user clicks on the buttons.

Tried AdaptiveSubmitAction with plain string in Data and with objects in Data, no luck.
Would be cool to get at least an imBack as happens in webchat, according to [this answer](https://stackoverflow.com/a/49638930/2826794)
