### ISSUE TITLE
[Question] Why I can't connect to azure db which is secured

### ISSUE THREAD

**Issue by msBot1111** [Microsoft/BotBuilder#3006]
I've created azure database in internal network for more security, and when I put the connection string into my web config in my Bot and publish the Bot, I always get Sorry my bot code is having an issue. I know that I can't connect locally in that db and test it in emulator, but why it doesn't work after publish? Before that I've used another db from azure which was not that secure and it worked well. Any idea what can be the problem?

**Comment by nwhitmont** [comment]
@msBot1111 These questions are outside the scope of the BotBuilder SDK. Please contact Azure support for questions about networking, security, and database configuration. These questions are outside the scope of the BotBuilder SDK.
