### ISSUE TITLE
[Emoji] Problem with emojis in the new skype android version

### ISSUE THREAD

**Issue by Noc2** [Microsoft/BotBuilder#3009]
## System Information (Required)
* SDK Language: C#
* SDK Version: 3.8.2
* Development Environment: AZURE

## Issue Description
On the new skype android version, certain emojis disappear when the message is send by a bot and not by the user!  
For example, “med/pill reminder 💊” will be shown as “med/pill reminder”, whereas “weight ⚖️” will be shown as “weight ⚖️”. 
This is a big issue for me, since I am using emojis for my Settings Scorable method to differentiate between “buttons” and real messages. 

## Code Examples
```
...
CardAction button3 = new CardAction()
            {
                Type = "imBack",
                Title = "Med/Pill reminder 💊",
                Value = "Med/Pill reminder 💊"
            };
reply.Attachments = new List<Attachment>();
KeyboardCard plCard = new KeyboardCard(text, cardButtons);
Attachment plAttachment = plCard.ToAttachment();
```
Result: Med/Pill reminder
**also**
```
await context.PostAsync(MessageDesign.AtRepliesPlusCancel(context, "Do you want to enter a goal for your tracker? 🎯"));
```
Result: Do you want to enter a goal for your tracker?

**Comment by nwhitmont** [comment]
@Noc2 Can you post your code for the messages being sent that cause the problem?

**Comment by Noc2** [comment]
Sure. I added a code examples to my original post. If you need a more detailed example feel free to ask. Although in my experience this is more a general issue and not specific to one line of code. I’m using a lot of emojis.

**Comment by JasonSowers** [comment]
@Noc2  Can you please try the following code and see if it works for you,  I used suggested actions instead of keyboard card:

```cs
 var reply = message.CreateReply();
                            reply.Type = ActivityTypes.Message;
                            reply.TextFormat = TextFormatTypes.Plain;

                            reply.SuggestedActions = new SuggestedActions()
                            {
                                Actions = new List<CardAction>()
                                {
                                    new CardAction(){ Title = "Med/Pill reminder 💊", Type=ActionTypes.ImBack, Value="Med/Pill reminder 💊" },
                                }
                            };
                           var reply1 = await connector.Conversations.SendToConversationAsync(reply);
```

**Comment by Noc2** [comment]
Thanks for your quick reply. It works, but suggest actions don’t show on every skype version. And a button without emojis is still better than no button at all 😉. I’m also using hero cards inside a carousel with the following code:
```
HeroCard plCard2 = new HeroCard()
            {
                Title = "Med/Pill reminder",
                Text = reminderText,
                Buttons = new List<CardAction>() { new CardAction(ActionTypes.ImBack, "Select", value: "Med/Pill reminder 💊") },
                Images = new List<CardImage>() { new CardImage(url: "https://florenceblob.blob.core.windows.net/menuimag/reminder.png") }
};
```
The message send by this code is also "Med/Pill reminder " instead of "Med/Pill reminder 💊"

**Comment by JasonSowers** [comment]
Maybe moving the emoji to the beginning will work?  It seems you are trying to use an image for your user to recognize the intent of your message above the text.  This may help.

**Comment by Noc2** [comment]
Thanks for the idea, but it didn’t work. The emojis do not only help users. They also helps my ScorableBase class. For example: if a message by the user contains: “information about xyz”, it's sent to luis. If the message contains “information 🔎”, I’m 99.99 % sure she or he clicked the button “information 🔎”. Of course, it also works without emojis, but I had much better results using them. 

It currently works for some emojis, but not for all. The below image should have an emojis next to every button. 
![image](https://user-images.githubusercontent.com/24638510/27454905-e0b68430-579b-11e7-89ce-4a8536ed212b.png)

**Comment by JasonSowers** [comment]
Please open a new issue if you were unable to resolve this
