### ISSUE TITLE
How to not lose userData starting dialog from bot

### ISSUE THREAD

**Issue by theotheo** [Microsoft/BotBuilder#301]
I'm trying start a conversation from bot, i.e. make a so-called proactive bot. 
Simplified version of my code is: 
`bot.beginDialog({to: user, from: bot, '/conversation', {msg: msg});`

But I faced an issue. When I initialize it this way I realize that data saved in userData earlier is gone. 
What do I do wrong? As I understand, the trouble is that userData belongs to participant from whom the message is being sent. 

How can I get user data when I start the conversation from the bot?

**Comment by Stevenic** [comment]
Tom, does userData not get persisted for proactive messages?

**Comment by tomlm** [comment]
If you want to store data on the next user then use the state api with that user.  The user data on a response object is associated with the user being responded to.
