### ISSUE TITLE
[Question] How can I reply using an O365ConnectorCard?

### ISSUE THREAD

**Issue by DSakura1987** [Microsoft/BotBuilder#3012]
## System Information (Required)
* SDK Language: .NET/C# 
* SDK Version: 3.8.1.0
* Development Environment: Self-hosted IIS

## Issue Description
I made a custom bot for my company. I have tried replied with ThumbnailCard, now I want to reply with O365ConnectorCard. I have installed `Microsoft.Bot.Connector.Teams` 0.5.6, but O365ConnectorCard does not offer a `ToAttachment()` method so I don't know how to add it to the Activity.

Most of my code is from CustomBot sample applecation.

## Code Example
N/A

## Steps to Reproduce the Issue
N/A

## Expected Behavior
Reply in thread with a O365ConnectorCard.

## Actual Results
I don't know how to do it...

**Comment by nwhitmont** [comment]
@DSakura1987 What channel(s) are you using with your bot? 

The O365 [actionable message](https://docs.microsoft.com/en-us/outlook/actionable-messages/actionable-messages-via-connectors) concept exists in Bot Framework, but we use a different name for it: Adaptive Cards.

You can achieve something similar using the [Adaptive Cards](http://adaptivecards.io/) JSON spec to configure card actions that interact with your O365 webhooks.

**Comment by DSakura1987** [comment]
If I understand it correctly, custom bot only lives in teams as a webhook-like thing, right? I always manually add it to a team.
Let me try the Adaptive Cards. Hope it works as I expected - have sections and other functions as O365ConnectorCard.

**Comment by DSakura1987** [comment]
Hi @nwhitmont , I just tried sending back this payload as the body, but the card does not show in the channel. do I need to fill more fields?

```
{
  "title": "Task(s) Summary",
  "text": null,
  "summary": null,
  "themeColor": null,
  "sections": [
    {
      "title": null,
      "text": null,
      "activityTitle": "Product Backlog Item 1",
      "activitySubtitle": null,
      "activityText": null,
      "activityImage": null,
      "facts": [
        {
          "name": "State",
          "value": "New"
        },
        {
          "name": "Assigned to",
          "value": "Somebody "
        }
      ],
      "images": null,
      "potentialAction": [
        {
          "name": "View Product Backlog Item 1",
          "target": [
            "someUrl"
          ],
          "@type": "openUrl"
        }
      ]
    }
  ],
  "$schema": "http://schema.org/extensions",
  "type": "MessageCard"
}
```

**Comment by DSakura1987** [comment]
Update:
Some fun facts:

- The payload needs summary or text field to be sent with a Connector.
  - The server replied 200 even I missed both fields. A bug for Teams dev team?
- The fixed payload does not work with custom bot.

**Comment by nwhitmont** [comment]
@DSakura1987 Thanks for the update.  What do you mean by "the fixed payload does not work with custom bot"?

**Comment by DSakura1987** [comment]
Oh, when I added text field, connector works fine, but my custom bot still
replies nothing.

Nils <notifications@github.com>于2017年6月22日周四 16:13写道：

**Comment by nwhitmont** [comment]
@DSakura1987 Can you post your complete bot code so we can better assist you?

**Comment by benmetheny** [comment]
I've used the O365ConnectorCard in Teams as a reply. You just need to create you own ToAttachment function as there is none supplied. This is how the framework does it:
       
`public static Attachment ToAttachment(this O365ConnectorCard card) {
            return CreateAttachment(card, O365ConnectorCard.ContentType);
        }`

        `private static Attachment CreateAttachment<T>(T card, string contentType) {
            return new Attachment {
                Content = card,
                ContentType = contentType
            };
        }`

**Comment by DSakura1987** [comment]
Thanks @BehnamEmamian ! That works but I still have a small issue with `potentialAction` in a `section` object. Does it work? My card showed without the buttons.
Here is the JSON my bot sent:
```
{
   "type": null,
   "id": null,
   "timestamp": null,
   "localTimestamp": null,
   "serviceUrl": null,
   "channelId": null,
   "from": null,
   "conversation": null,
   "recipient": null,
   "textFormat": null,
   "attachmentLayout": "carousel",
   "membersAdded": [],
   "membersRemoved": [],
   "topicName": null,
   "historyDisclosed": null,
   "locale": null,
   "text": null,
   "speak": null,
   "inputHint": null,
   "summary": null,
   "suggestedActions": null,
   "attachments": [
      {
         "contentType": "application/vnd.microsoft.teams.card.o365connector",
         "contentUrl": null,
         "content": {
            "title": "2 Task(s)",
            "text": null,
            "summary": "Tasks",
            "themeColor": null,
            "sections": [
               {
                  "title": "Task 11411",
                  "text": "Iteration: .....",
                  "activityTitle": null,
                  "activitySubtitle": null,
                  "activityText": null,
                  "activityImage": null,
                  "facts": [
                     {
                        "name": "State",
                        "value": "To Do"
                     },
                     {
                        "name": "Found In",
                        "value": "None"
                     },
                     {
                        "name": "Assigned To",
                        "value": "None"
                     }
                  ],
                  "images": null,
                  "potentialAction": [
                     {
                        "name": "View Task 11411",
                        "targets": [
                           {
                              "os": "default",
                              "uri": "REMOVED"
                           }
                        ],
                        "@type": "OpenUri"
                     }
                  ]
               },
               {
                  "title": "Bug 11422",
                  "text": "Iteration: .....",
                  "activityTitle": null,
                  "activitySubtitle": null,
                  "activityText": null,
                  "activityImage": null,
                  "facts": [
                     {
                        "name": "State",
                        "value": "To Do"
                     },
                     {
                        "name": "Found In",
                        "value": "None"
                     },
                     {
                        "name": "Assigned To",
                        "value": "None"
                     }
                  ],
                  "images": null,
                  "potentialAction": [
                     {
                        "name": "View Bug 11422",
                        "targets": [
                           {
                              "os": "default",
                              "uri": "REMOVED"
                           }
                        ],
                        "@type": "OpenUri"
                     }
                  ]
               }
            ]
         },
         "name": null,
         "thumbnailUrl": null
      }
   ],
   "entities": [],
   "channelData": null,
   "action": null,
   "replyToId": null,
   "value": null,
   "name": null,
   "relatesTo": null,
   "code": null
}
```

**Comment by DSakura1987** [comment]
Thanks @nwhitmont and @benmetheny , I came to use HeroCard instead of O365ConnectionCard, so I am closing this issue.

**Comment by satheeshganji48** [comment]
How to prepare rich card using JSON template in c#
