### ISSUE TITLE
[Question] Bot working on FB & Skype but first message when connected doesn't arrive, but it's working fine when connected to emulator

### ISSUE THREAD

**Issue by hardikchoudhary** [Microsoft/BotBuilder#3014]
On emulator i click on connect then first message comes that is description message

But on skype or fb messenger its is not coming

**Comment by JasonSowers** [comment]
can you please post your code in conversationUpdate section of the message controller?

**Comment by nwhitmont** [comment]
@hardikchoudhary are you using .NET or Node SDK?

**Comment by hardikchoudhary** [comment]
Yes it is in node js..... I have added that message in conversation update
only....

**Comment by hardikchoudhary** [comment]
Its node js.... Its workinh fine on enumelaor when i connect.... But when i open my bot in messanger it doesnt send so

**Comment by hardikchoudhary** [comment]
In bot.on conversation method

**Comment by nwhitmont** [comment]
@hardikchoudhary Can you post your complete bot code that reproduces the error?

**Comment by nwhitmont** [comment]
@hardikchoudhary Did you find a solution to this one as well?

**Comment by hardikchoudhary** [comment]
@nwhitmont  Hi


bot.on('conversationUpdate', function (message) {

    console.log(message.address.bot.name);

    // if(message.membersAdded[0].name== message.address.bot.name){
   if (message.membersAdded && message.membersAdded.length > 0) {
      
            var membersAdded = message.membersAdded
                .map(function (m) {
                    var isSelf = m.id === message.address.bot.id;
                    return (isSelf ? message.address.bot.name : m.name) || '' + ' (Id: ' + m.id + ')';
                }).join(', ');

            bot.send(new builder.Message()
                .address(message.address)
                .text("Hello You can start finding Near By Metro from any place ,By typing from Place city .. Example message me 'from gip noida' or 'from govindpuri delhi' "+message.membersAdded[0].name));
        
   }
	//}
    
    
    

    if (message.membersRemoved && message.membersRemoved.length > 0) {
        var membersRemoved = message.membersRemoved
            .map(function (m) {
                var isSelf = m.id === message.address.bot.id;
                return (isSelf ? message.address.bot.name : m.name) || '' + ' (Id: ' + m.id + ')';
            })
            .join(', ');

        bot.send(new builder.Message()
            .address(message.address)
            .text('The following members ' + membersRemoved + ' were removed or left the conversation :('));
    }
});


This code is working fine on enumelator when i click on connect

but when i open my bot in fb messenger no message comses

**Comment by sir-rois** [comment]
I guess I have same issue.
There is an error on first connection:

`Error: Request to 'https://facebook.botframework.com/v3/conversations/%%%%%' failed: [400] Bad Request
    at Request._callback (D:\home\site\wwwroot\node_modules\botbuilder\lib\bots\ChatConnector.js:452:46)
    at Request.self.callback (D:\home\site\wwwroot\node_modules\request\request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (D:\home\site\wwwroot\node_modules\request\request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (D:\home\site\wwwroot\node_modules\request\request.js:1091:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)`

**Comment by fanidamj** [comment]
Is the issue still persistent.

**Comment by hardikchoudhary** [comment]
I will check again...

**Comment by fanidamj** [comment]
Closing the issue assuming it as resolved. Please reopen a new issue if it still persists.
