### ISSUE TITLE
[Adaptive Cards] suggestedAction and adaptiveCards are not being rendered on  Skype 

### ISSUE THREAD

**Issue by anks333** [Microsoft/BotBuilder#3015]
## System Information
* SDK Language: NODE 
* SDK Version: 3.8.4
* Development Environment: AZURE_BOT_SERVICE, AZURE_APP_SERVICE,

## Issue Description
My bot is working properly on emulator and Skype [web version], but in skype app (for W10 and Ubuntu) some of the component are not getting rendered. 
SuggestedAction and AdaptiveCard are not working.

does skype app support these component?,

**Comment by JasonSowers** [comment]
@anks333 Hello, the official word on adaptive cards support in the skype channel is "Coming soon"

**Comment by nwhitmont** [comment]
Skype does not currently support the Adaptive Cards spec.

Relates to: [[Microsoft/AdaptiveCards] .io site needs Partners/Integration page showing AC support status #367](https://github.com/Microsoft/AdaptiveCards/issues/367)

**Adaptive Cards channel support:**
- Emulator – full support
- WebChat – Full support
- Facebook – render to image + limited mapping to buttons
- Slack – Image + limited mapping to buttons
- Kik – render to Image + limited mapping to keyboard
- Telegram – Render to Image + limited mapping to keyboard
- SMS – Image + text
- GroupMe – Image + text
- Email – Image + limited mapping to links
- Bing – I think supports it via SkypeWeb Chat control which has implementation. Not sure if it is in production yet.
- Skype – Coming Soon
- Teams – Coming Soon
- Cortana – not supported
- Skype for Business – Not supported

**Comment by ImranJaved** [comment]
Hi,
Is there any update for Skype. Latest version of Skype for windows 10 shows adaptive card, but few controls like ChoiceSet, SubmitAction are not shown.
