### ISSUE TITLE
[Question] how to get Past history chat from Azure table storage for C#

### ISSUE THREAD

**Issue by amitgobare23** [Microsoft/BotBuilder#3018]
how to get Past history chat from Azure table storage for C#

**Comment by JasonSowers** [comment]
Here is an implementation of [IActivityLogger](https://github.com/Microsoft/BotBuilder-Azure/blob/master/CSharp/Library/Microsoft.Bot.Builder.Azure/TableLogger.cs#L60) you may find useful.  theres also some more information in []this issue](https://github.com/Microsoft/BotBuilder/issues/2073)  as well as [this issue] (https://github.com/Microsoft/BotBuilder/issues/2970)

**Comment by amitgobare23** [comment]
I already stored data using TableBotDataStore class of Microsoft.Bot.Builder.Azure in Azure table storage but i want to retrived that and diplay when user back again in his chat

when i open chat again then Post method of MessagesController again called and then it goes into HandleSystemMessage() method....then it get ActivityTypes.ConversationUpdate as ActivityType and it's execution finished....my questions is how i get data from Azure table storage....

**Comment by amitgobare23** [comment]
could you please give solution for above problem...thanks in advance!

**Comment by JasonSowers** [comment]
@amitgobare23 this is not something I have personally done before I do not have a pre-made solution to show you.

**Comment by amitgobare23** [comment]
@JasonSowers  so what are other ways to get past history data from azure storage cloud , load and display on chat screen?

**Comment by JasonSowers** [comment]
What channel are you trying to do this on?

**Comment by amitgobare23** [comment]
@JasonSowers  I am using Webchat

**Comment by amitgobare23** [comment]
@JasonSowers  still i don't get any workaround/solution for same.... are you found some workaround/solution for above problem

**Comment by JasonSowers** [comment]
@amitgobare23 I have not, sorry

**Comment by SarahSexton** [comment]
My current approach is from the web "push notification" in the browsers, actually, rather than from the chat framework itself. This WebChatPush project can recall chat history from previous windows by clicking on desktop push notifications: [https://github.com/doristchen/WebChatPush](https://github.com/doristchen/WebChatPush)

**Comment by JasonSowers** [comment]
please reopen this issue if needed

**Comment by sandipdakle** [comment]
Has anyone found anything with this?
