### ISSUE TITLE
Not able to show a welcome message for skype bots using bot connector

### ISSUE THREAD

**Issue by srisaiswaroop** [Microsoft/BotBuilder#302]
I am using the nodejs version of the bot connector. 
Our Skype bot was rejected during the review because it was not showing a welcome message. 
I am right to say we cannot use bot connector to make Skype bots which can be published?
Right now the only way to make Publishable Skype bots is to use Skype SDK? 

I saw #250 was closed saying that its an enhancement.

**Comment by jameslew** [comment]
Hello srirsaiswaroop,

Actually, our current UX is a little misleading. Submitting a bot to the Microsoft Bot Framework only gets it reviewed for the Bot Framework directly.  It neither enables your bot nor blocks it from being listed in another directory.

After you've created your bot in the bot framework (published or not) you can go to the Skype dev portal and submit for review within their portal.

We'll make this clearer in the future.

--jim

**Comment by judavi** [comment]
@jameslew the problem it's because when a user adds the bot, the bot doesn't received the message.type  "BotAddedToConversation". So if you try to publish your bot on the Skype bot directory it's rejected because the bot has to show a welcome message.

**Comment by jameslew** [comment]
I'll look into this Judavi.  We used to generate this event so something isn't working quite right, or alternately it's getting swallowed before it gets displayed.

**Comment by jameslew** [comment]
Okay, we've fixed this; you now will get an event UserAddedToConversation when the Bot is added as a contact.  We're going to look at additional events in the future that map to the Skype "contact added" event as this current mapping is mis-using the intent a little bit in order to get the desired behavior.

**Comment by judavi** [comment]
@jameslew sorry for the late response, today I being doing some tests and works great! also I notice that now it's working the other message types like "UserRemovedFromConversation" :+1:

**Comment by v-thgratMSGit** [comment]
Closing this issue. Please open a new issue for further discussion if necessary. Thanks!

**Comment by stanleycyang** [comment]
Is there a reference for this feature in the NodeJS SDK?
