### ISSUE TITLE
[Question] Any example code for Skype For Business bit to initiate a new conversation (nodejs) 

### ISSUE THREAD

**Issue by ceopk** [Microsoft/BotBuilder#3020]
## System Information (Required)
* SDK Language: node.js

## Issue Description
Looking for example to have Skype for Business bot to initiate a new conversation with user.

**Comment by nwhitmont** [comment]
You can also find many example bot projects demonstrating various features of the Node SDK here:
https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node

**Comment by ceopk** [comment]
The example code does not work. message.membersAdded only contains the bot itself.

I was hoping to find example as in 
Skype For Business] Outbound Bot doesn't work. #3023

**Comment by teachtyler** [comment]
#3023 

Make sure Skype for business bot sip is of the same domain as the user you're trying to reach with outbound. 
In other words, the bot is created as a user in your Active Directory tenant, and needs other measures to reach outside domain.

Example code:
```js
let address = {
            "id": "",
            "channelId": "skypeforbusiness",
            "user": {
                "id": <id of the user you want to message (sip:me@domain.com)>,
            },
            "bot": {
                "id": "sip:bot@domain.com",
                "name": "sip:bot@domain.com"
            },
            "serviceUrl": "https://api.skypeforbusiness.com/platformservice/botframework"
        }


sendProactiveMessage(address, "Tyler")
```


```js
const sendProactiveMessage = (addr, user) => {
  bot.send(new builder.Message().address(addr).text(`${user} is trying to reach you!`));
}
```

**Comment by ceopk** [comment]
Thanks @teachtyler.

It does work!!!
However it only work occasionally and when it works, after click reply on the notification, there is no text message shown.

Every time there is error message from botbuilder(include when notification is shown):
ERROR: ChatConnector: startConversation - error starting conversation.
Error: Request to 'https://api.skypeforbusiness.com/platformservice/botframework/v3/conversations' failed: [500] Internal Server Error
    at Request._callback (/opt/SA_PlatformHandlers/node_modules/botbuilder/lib/bots/ChatConnector.js:512:46)

**Comment by rohankulkarni21** [comment]
@teachtyler Can you please give an example on how you created your bot? Please Help.

The code given by you is always throwing an error for me:
Request to 'https://api.skypeforbusiness.com/platformservice/botframework/v3/conversations' failed: [500] Internal Server Error

**Comment by FreakPirate** [comment]
Hi @ceopk , I am getting the same error. I tried intercepting the options, url and credentials bot framework uses in the backend to communicate with S4B, then tried replicating the request on post man, I still got the same error. Not even once it send any notification or message to the intended user.
![postman_correct_blurred](https://user-images.githubusercontent.com/7129637/37815544-45d3ad22-2e95-11e8-8542-078b2153845e.png)

Please suggest a fix.
