### ISSUE TITLE
[Skype For Business] Outbound Bot doesn't work.

### ISSUE THREAD

**Issue by Mikhail2k15** [Microsoft/BotBuilder#3023]
Every time I try create outbound conversation (no matter WEB API or Console app) I receive an error Microsoft.Rest.TransientFaultHandling.HttpRequestWithStatusException
A 504 (Server Time-Out) response was received from the network and the operation failed. See the exception details for more information.

An error occurred at ConversationResourceResponse response = connector.Conversations.CreateConversation(cpMessage);

My code is from msdn documentation:

> const string trustServiceUri = "https://api.skypeforbusiness.com/platformservice/botframework";
>             MicrosoftAppCredentials.TrustServiceUrl(trustServiceUri, DateTime.MaxValue);
>             Trace.TraceInformation(MicrosoftAppCredentials.IsTrustedServiceUrl(trustServiceUri).ToString());
>             Trace.TraceInformation(MicrosoftAppCredentials.MicrosoftAppIdKey);
>             Trace.TraceInformation(MicrosoftAppCredentials.MicrosoftAppPasswordKey);
>             var to = "sip:msftbot@contoso.com";
>             var connector = new ConnectorClient(new Uri(trustServiceUri));
>             List<ChannelAccount> participants = new List<ChannelAccount>();
>             participants.Add(new ChannelAccount(to, to));
>             ConversationParameters cpMessage = new ConversationParameters(true, new ChannelAccount("sip:skypebot@contoso.com", "skypebot"), 
>                 participants, "My Test Conversation");
>             ConversationResourceResponse response = connector.Conversations.CreateConversation(cpMessage);
>             var conversationID = response.Id;
>             var conversationServiceURL = response.ServiceUrl;

I use the latest version of Bot Framework. 3.8.1 and 3.8.2

**Comment by Mikhail2k15** [comment]
sometimes I see another error code A 480 (Temporarily Unavailable) response was received from the network and the operation failed. See the exception details for more information.

**Comment by Mikhail2k15** [comment]
![proactivebotissue](https://user-images.githubusercontent.com/11201670/27673742-01b8e682-5cab-11e7-86d6-9e97fe2e840d.png)

**Comment by rakeshreddy27** [comment]
Hey @Mikhail2k15 - Did you find a solutions for this problem. I am facing the exact same issue.

**Comment by Mikhail2k15** [comment]
@rakeshreddy27  Unfortunately no.

**Comment by EricDahlvang** [comment]
Please share the MSDN documentation page where you found the code you're trying to use.

**Comment by intranetchris** [comment]
@EricDahlvang His code is from [this MSDN documentation page](https://msdn.microsoft.com/en-us/skype/skype-for-business-bot-framework/docs/overview#create-outbound-bots).

**Comment by benbrown** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botbuilder-channels/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
