### ISSUE TITLE
[Bing Channel] Cannot publish the bot to Bing

### ISSUE THREAD

**Issue by anarchitect** [Microsoft/BotBuilder#3025]
## System Information (Required)
* SDK Language: C#
* SDK Version: 3.5.9.0
* Development Environment: 

## Issue Description
can not publish the bot to bing, the submit for review button is always disabled. 

## Code Example
NA, the bot handle is FindIt
## Steps to Reproduce the Issue
When I submitted the bot for review to bing, the submit for review button is disabled, despite i filled in all the information. 
## Expected Behavior
I should be able to submit the bot bing.
## Actual Results
When I submitted the bot for review to bing, the submit for review button is disabled, despite i filled in all the information. 

Thanks.

**Comment by mgbennet** [comment]
That's a bug in the configuration page. I will take a look at it and get a fix asap.

**Comment by nwhitmont** [comment]
@anarchitect Thanks for reporting. We're working on a fix for this now.

**Comment by Andrea-Orimoto** [comment]
@anarchitect this is fixed now, please verify.
Thanks a lot for reporting the issue.
