### ISSUE TITLE
[Question] How to add datepicker or timepicker in my bot?

### ISSUE THREAD

**Issue by Malith1994124** [Microsoft/BotBuilder#3028]
um creating a bot using c#. so o want like if bot ask what time you want to make your appointment bot show timepicker in chat so user can set time like in mobile app. Can u explane it this possible and how it done??

**Comment by nwhitmont** [comment]
@Malith1994124 It is possible. You would need to prompt the user with a list of time choices, or you could use a test prompt and do input validation to ensure that you have received a time in the response message.
