### ISSUE TITLE
Adding a Bot Channel

### ISSUE THREAD

**Issue by JpEncausse** [Microsoft/BotBuilder#303]
Hi,

I have a home automation framework named SARAH (http://sarah.encausse.net) let's say it's like cortana...

I want to perform speech recognition and send the message to my MS Bot. In that case I have to develop a new "client" or "channel"

1. In the futur, how Microsoft will add new Channel to it's repository ?

2. How can I communicate with my bot from a custom client ? Is there NodeJS implementation ?

**Comment by IanBoggs** [comment]
I can't help with point 1

I did write a simple relay Lync client that forwarded information from a Lync conversation to a Framework Bot using REST. You'll need to add all the relevant message details to the body of the POST you send and then deserialize the response back into the appropriate object.

I'm not saying there aren't other ways to do it mind you

**Comment by tomlm** [comment]
DirectLine API gives you a channel to your bot
Channels allow access to anyones bot, and currently are internal only but we would like someday to open up to trusted parties.
