### ISSUE TITLE
What chars to send to FB Messenger with bot FW to send newline?

### ISSUE THREAD

**Issue by stefandevo** [Microsoft/BotBuilder#3030]
I am trying to send a text with line breaks inside of it.
When I compose a string with Environment.NewLine in it, it shows in FB Messenger as \r\n in clear text. I also tried the \n\n but again \n\n is showed as clear text.
I can I force a new line in a simple FB messenger message?

**Comment by nrobert** [comment]
From my tests it's working with `\n\n`:

**Code sample:**
```C#
await context.PostAsync("message\nline");
await context.PostAsync("message\n\nline");
await context.PostAsync("message\n\n\nline");
await context.PostAsync("message\n\n\n\nline");
await context.PostAsync(@"message
        line");
```

**Output:**
![image](https://user-images.githubusercontent.com/6305666/27530112-7eb30e2a-5a57-11e7-83ae-029cb341cd69.png)

**Comment by stefandevo** [comment]
Ok thanks for confirming this.
In my situation, I am getting the response back from an external service (api call). Then with that response I do a
`await connector.Conversations.ReplyToActivityAsync(reply)`
Maybe the reply I get back from the external service needs to be modified in order to have real new lines in the reply message.
