### ISSUE TITLE
[FormFlow] Custom message for Enum options 

### ISSUE THREAD

**Issue by trantung2704** [Microsoft/BotBuilder#3031]
I am working with MS bot framework and I can't find way to custom message for enum options in form flow. I have tried with prompt attribute but it doesn't work.

What I want is: bot will show options for user like:

1) Yes, I want to be a DayNinja!
2) No, I don't want to unlock flow to achieve my goals.
3) Later, I'll start with the basics

Now, All I get are: "Yes", "No", "Later"

![capture](https://user-images.githubusercontent.com/8099977/27534905-b8d663dc-5a92-11e7-9d27-ca98990b523a.PNG)

Any help will be appreciated Thank you!

**Comment by ejadib** [comment]
Posted at https://stackoverflow.com/questions/44756649/custom-message-for-enum-options-in-formflow-c-sharp-bot-framework. Please don't duplicate post in StackOverflow and GitHub.
