### ISSUE TITLE
[Question] After adding luis integration bot is working only in web chat but not in skype and facebook

### ISSUE THREAD

**Issue by hardikchoudhary** [Microsoft/BotBuilder#3032]
please help me in this

Here greeting is my intent
But its only working in enumelator locally and on azure its working with web chat only

FB and skype doesnt through any error but didnt resspond any thing

```js
bot.dialog('greeting', function (session, args) {
 session.send("Hello hope you are good ,Please start finding nearest metro by messaging me 'PlaceName City' like nearest gip noida or closest to akshardham or way you want");
greeting="";
   }).triggerAction({
    matches: 'greeting'
});
```
Thanks

**Comment by stevengum97** [comment]
On your dev.botframework.com page for your bot are the channels for Skype and FB showing any errors?

**Comment by hardikchoudhary** [comment]
No its not showing any error
@stevengum97

**Comment by hardikchoudhary** [comment]
@stevengum97 can you please help me in this regard as the issue is not stil resolved

**Comment by stevengum97** [comment]
@hardikchoudhary, are you still experiencing this problem? If so, can you provide your bot's app ID?

**Comment by epjm429** [comment]
Hi I have this problem. How did you solve it?
