### ISSUE TITLE
[Question] Properties set for ILuisModel are not taken into account

### ISSUE THREAD

**Issue by shather** [Microsoft/BotBuilder#3033]
## System Information (Required)
* SDK Language: .NET/C#
* SDK Version: 3.8.2.0
* Development Environment: LOCALHOST + ngrok

## Issue Description
After update to Bot.Builder 3.8.2:
If you create Luis Service this way:
`new LuisService(new LuisModelAttribute("id","key") { Verbose = true})`

your uri to luis won't take Verbose into account, and your url will be like:

https://westus.api.cognitive.microsoft.com/luis/v2.0/apps/x?subscription-key=y&q=query&log=True

instead of:
https://westus.api.cognitive.microsoft.com/luis/v2.0/apps/x?subscription-key=y&verbose=true&q=query&log=True

## Expected Behavior
https://westus.api.cognitive.microsoft.com/luis/v2.0/apps/x?subscription-key=y&verbose=true&q=query&log=True
url should be created

## Actual Results
https://westus.api.cognitive.microsoft.com/luis/v2.0/apps/x?subscription-key=y&q=query&log=True url has been created

**Comment by JasonSowers** [comment]
@shather can you please add more code so we can try to help you further.

Neither the [LuisService](https://docs.botframework.com/en-us/csharp/builder/sdkreference/de/daf/class_microsoft_1_1_bot_1_1_builder_1_1_luis_1_1_luis_model_attribute.html)  nor the [LuisModelAttribute](https://docs.botframework.com/en-us/csharp/builder/sdkreference/de/daf/class_microsoft_1_1_bot_1_1_builder_1_1_luis_1_1_luis_model_attribute.html)  havethe Verbose property.  However the [LuisRequest](https://docs.botframework.com/en-us/csharp/builder/sdkreference/d8/da9/class_microsoft_1_1_bot_1_1_builder_1_1_luis_1_1_luis_request.html) has this property.  I may be missing something so i would like to see more of your code if possible
  
another thing I tried that seemed to help was manually adding the query string via `            var x =
            new LuisService(new LuisModelAttribute("eb7500a1-8134-4904-87ef-5b0a026de304", "e24b3becca7e445ea16cc3ce74d45cb9"));
            x.BuildUri("add_to_querystring");`

**Comment by stevengum97** [comment]
Closing this issue due to lack of response.
