### ISSUE TITLE
[Question] There was an error completing this request due to an internal channel failure in skype but same is working with web chat , facebook too

### ISSUE THREAD

**Issue by hardikchoudhary** [Microsoft/BotBuilder#3035]
I am getting error on skype only

There was an error completing this request due to an internal channel failure.

It was working fine but suddenly this error keeps hitting now

Please help me regarding same

Thanks

**Comment by nwhitmont** [comment]
@hardikchoudhary are you using .NET or Node SDK?

**Comment by nwhitmont** [comment]
Hi @hardikchoudhary - Can you post your complete bot code that reproduces the issue?

Also, please provide your bot name, bot handle, and App ID from your bot as registered in the Bot Portal at https://dev.botframework.com

**Comment by auanish** [comment]
Maybe a related issue - I'm trying to share the Skype bot joining link to test and when I click on "Add to Contacts" in Skype it says "Failed to add bot to your contact list". 

In the portal, the health status says "Unknown activity type".

**Comment by nwhitmont** [comment]
@auanish Please open a new issue if the problem persists.

**Comment by hardikchoudhary** [comment]
Hi Team

Sorry this internal error is not showing up, I have not done a single
change in code and neither publish it again.

It automatically get started. May be some backend problem with skype in
communicating

Only two issues remained in my issues 1. onconvestationupdate not working
with fb and skype
2. After adding Luis , fb stop responding neither any issue show in
botdevframework

Thanks
hardik choudhary

**Comment by nwhitmont** [comment]
@hardikchoudhary Thanks for the update. Closing as resolved.
