### ISSUE TITLE
During BOT Registration, when I click the Create App ID and Password, it takes me to new browser and I get the (Bad Request - Request Too Long) Error

### ISSUE THREAD

**Issue by maheshksingh** [Microsoft/BotBuilder#3037]
## System Information (Required)
* SDK Language: 
* SDK Version: 
* Development Environment: 

## Steps to Reproduce the Issue
1.
2.
3.

**Comment by maheshksingh** [comment]
This is resolved now, I figured out myself, it was an issue with my Microsoft User Ids, Since I have two. One is my personal and the other created by my organisation.  And the BOT framework was refrring the wrong Microsoft profile.

**Comment by nwhitmont** [comment]
@maheshksingh Yes, it gets confusing when using two accounts. ;-)
