### ISSUE TITLE
[LUIS] Latency in LUIS request causes Direct Line timeout

### ISSUE THREAD

**Issue by sayyednazeer** [Microsoft/BotBuilder#3038]
Calling my bot using direct line throws 500 internal server error because of LUIS latency which takes long time to give the winning intent.

After the release of the new version there is no change in LUIS performance.

**Comment by amitbend** [comment]
Did you try to update the version?

**Comment by nwhitmont** [comment]
@sayyednazeer Thanks for reporting. There is a 15s timeout on Direct Line requests.

Are you using .NET or Node SDK? Can you provide screenshots of the network requests showing the time it takes to return data? What happens when you call LUIS not using Direct Line?  What is the frequency of the timeouts as a percentage of the number of calls to LUIS?

**Comment by sayyednazeer** [comment]
@nwhitmont  i am using .NET SDK
I know about 15s timeout, but the thing LUIS is taking time find the intent to call in my class.

Some time it works and some time takes more than 15 seconds .

this are the logs for : 

24 second log
Activity ID = 8Z4HXm3yOvxICA1eUEzHdh|0000007
activity.ChannelId =
directlineConversation.Id = 8Z4HXm3yOvxICA1eUEzHdh
Conversation.Name =
activity.From.id = user_8Z4HXm3yOvxICA1eUEzHdh
activity.From.Name =
activity.Recipient.Id =GENIEINHOUSE@MOwX7qwHSxI
activity.Recipient.Name = GENIEINHOUSE
activity.ServiceUrl = https://directline.botframework.com/
activity.Text = hello

25 second log
Activity ID = 8Z4HXm3yOvxICA1eUEzHdh|0000009
activity.ChannelId =
directlineConversation.Id = 8Z4HXm3yOvxICA1eUEzHdh
Conversation.Name =
activity.From.id = user_8Z4HXm3yOvxICA1eUEzHdh
activity.From.Name =
activity.Recipient.Id =GENIEINHOUSE@MOwX7qwHSxI
activity.Recipient.Name = GENIEINHOUSE
activity.ServiceUrl = https://directline.botframework.com/
activity.Text = Hi

![2350c0a0-e2e7-11e6-8c26-3d2ec84cbf33](https://user-images.githubusercontent.com/10753866/27631343-c953bf64-5c15-11e7-89f3-9dd9e1c2d0f5.png)

**Comment by nwhitmont** [comment]
@sayyednazeer Thanks for the update & detailed request info. We are investigating the issue.

**Comment by nwhitmont** [comment]
moving this conversation back to the original issue with history #2078
