### ISSUE TITLE
[Question] How to intercept Messenger errors

### ISSUE THREAD

**Issue by fcioffi** [Microsoft/BotBuilder#3041]
Hi,

i'm using node SDK.

One thing that annoying me is that i can't intercept errors sending proactive (and not) message to user (eg. Facebook Bad Request).

I can add global listening but in error callback I don't have the user info where error happens.

How can I get user info?
Thanks for your help.

Francesco

**Comment by bilby91** [comment]
@fcioffi How did you added the global listener ? Where did you hooked to get the error event for example when you do `bot.beginDialog` with an invalid address.

Thanks!

**Comment by bilby91** [comment]
@fcioffi Maybe this is useful https://github.com/Microsoft/BotBuilder/pull/3138

**Comment by fcioffi** [comment]
Hi @bilby91, thanks for your response.

I added the global listener and listen correctly when the error happens. My problem is that the error parameter of callback doesn't contains any info about the original message.

Do you have any suggestion for get some info about address or a custom parameter about the message that is in error?


Thanks,
Francesco

**Comment by bilby91** [comment]
@fcioffi Did you look at the pull request I referenced (#3138) ? That PR should enrich the error with the information you need. I'm using that for the moment.

**Comment by fcioffi** [comment]
Thank you @bilby91. I'm waiting the merge.

FC

**Comment by JasonSowers** [comment]
going to close this pending the PR merge feel free to reopen or continue the conversation here

**Comment by fcioffi** [comment]
Hi guys,

when do you thnk to merge this PR?
