### ISSUE TITLE
[Question] BotConnect Swagger schema is incomplete.

### ISSUE THREAD

**Issue by james-lawrence** [Microsoft/BotBuilder#3043]
## Issue Description
The entity description for the [botconnect](https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Microsoft.Bot.Connector.Shared/Swagger/ConnectorAPI.json) doesnt properly cover the entities field on activity.

It only generates a object with a string field `type`. meaning a fully functioning client cannot be generated from the swagger file.

I'm not sure of the best way to fix this due to my general unfamiliarity with swagger but here is one possible solution:
```
    "Entity": {
      "description": "Object of schema.org types",
      "allOf": [
        {
          "$ref": "#/definitions/Mention"
        },
        {
          "type": "object",
          "properties": {
            "type": {
              "description": "Entity Type (typically from schema.org types)",
              "type": "string"
            }
          }
        }
      ]
    },
    "Mention": {
      "description": "an account mention",
      "type": "object",
      "properties": {
        "text": {
          "description": "text representation of the mention",
          "type": "string"
        },
        "mentioned": {
          "description": "mention representation",
          "type": "object",
          "properties": {
            "id": {
              "description": "account ID",
              "type": "string"
            },
            "name": {
              "description": "textual representation of the account",
              "type": "string"
            }
          }
        }
      }
    },
```

**Comment by nwhitmont** [comment]
@james-lawrence Is this an observation or is this affecting your bot functionality in some way?

**Comment by james-lawrence** [comment]
Impacting the bot. But I just modified the file to work for my application.

**Comment by nwhitmont** [comment]
@james-lawrence Thanks for the update. Glad to hear you found a solution.
