### ISSUE TITLE
[MS Teams] openUrl() method failing when URL string contains curly braces

### ISSUE THREAD

**Issue by stevenfollis** [Microsoft/BotBuilder#3044]
## System Information
* SDK Language: Node
* SDK Version: 3.8.2
* Development Environment: Azure_App_Service

## Issue Description
A URL string passed into `builder.CardAction.openUrl()` containing a `{` or `}` will fail to open when clicked in a conversation in the MS Teams channel. 

Fictional Example:
```
https://azure.microsoft.com/en-us/services/storage?id={00000000-0000-0000-0000-000000000000}
```

Button works properly in the bot emulator, web chat, and Skype channels. Have not tested others beyond those 3.

## Steps to Reproduce the Issue
1. Deploy the [cards-CarouselCards](https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node/cards-CarouselCards) sample
2. [Create a bot](https://dev.botframework.com/bots/provision) and enable MS Teams channel from My Bots
3. Start a new chat in MS Teams pointed at the bot's Client ID GUID and verify that the default button works for opening a browser tab.
4. Change the `.openUrl()` method by appending a parameter with curly braces
```javascript
builder.CardAction.openUrl(session, 'https://azure.microsoft.com/en-us/services/storage?id={00000000-0000-0000-0000-000000000000}', 'Learn More');
```
5. Re-deploy and restart a conversation in MS Teams with the bot. Now when pressing **Learn More** the browser should not open. The button is dead.

## Expected Behavior
When conversing with a bot in MS Teams and am presented with a button implementing .openUrl() with curly braces in the URL, the button should open a browser window.

## Actual Results
Non-functioning URL was for Dynamics 365 CRM's REST endpoint. They require curly braces when referencing a specific entity instance. I did get this to work by manually encoding the `{ }` characters and passing that into the URL string. 

Using that technique with the `cards-CarouselCards` sample, I adjusted the [url](https://github.com/Microsoft/BotBuilder-Samples/blob/master/Node/cards-CarouselCards/app.js#L42) with escaped `{` and `}`:

Did not work:
```javascript
builder.CardAction.openUrl(session, 'https://azure.microsoft.com/en-us/services/storage?id={00000000-0000-0000-0000-000000000000}', 'Learn More');
``` 

Works:
```javascript
builder.CardAction.openUrl(session, 'https://azure.microsoft.com/en-us/services/storage?id=%7b00000000-0000-0000-0000-000000000000%7d', 'Learn More');
```
> Please note the `%7b` and `%7d` characters in the working line, which escape the `{ }` characters.

When click the the "Browser" button, nothing happens in MS Teams. With the aforementioned channels, the browser opens as expected. Assumed that there would be consistency between how channels encode/decode URIs. 

Happy to provide further context. Thanks!

**Comment by stevenfollis** [comment]
@JasonSowers Hi Jason, saw the Adaptive Cards label added. Wanted to add that my experience was with Hero Cards only; unsure if the same issue is present with Adaptive Cards. Thanks!

**Comment by JasonSowers** [comment]
Thanks for the update Steven

**Comment by nwhitmont** [comment]
@stevenfollis PR submitted

**Comment by stevenfollis** [comment]
@nwhitmont Thanks! Ya'll sure do work quickly :)

**Comment by fanidamj** [comment]
Closing the issue assuming it as resolved. Please reopen a new issue if it still persists.
