### ISSUE TITLE
[Question] Unable to add Skype bot to contacts

### ISSUE THREAD

**Issue by auanish** [Microsoft/BotBuilder#3045]
## System Information (Required)
* SDK Language: Node
* SDK Version: 3.8.3
* Development Environment: AZURE_APP_SERVICE

## Issue Description
I'm trying to share the Skype bot joining link to test and when I click on "Add to Contacts" in Skype it says "Failed to add bot to your contact list".

The bot is added to my personal account from the dashboard without any issues. The problem occurs only when I'm sharing the url.

**Comment by JasonSowers** [comment]
@auanish is your app published?  IF you look in the publish column on the channels tab here https://dev.botframework.com/bots?id=YOUR_BOT_ID does it say approved?

**Comment by auanish** [comment]
No, I haven't published my Skype bot yet (it says '--' under published column). I just want to test it with a selected group of testers, so I've just sent the joining link to them and they are unable to join. But the bot works fine in the Skype account which is linked to the botframework portal.

**Comment by JasonSowers** [comment]
I don't think others can use the link until its published

**Comment by auanish** [comment]
Under the Publish option it says, 

> "Bots in Preview are limited to 100 contacts. If you need more than 100 contacts, Publish your bot...." 

So how do I get it to those 100 contacts without publishing?

**Comment by JasonSowers** [comment]
Just saw that. I checked in my bot that I published and it says [Private Published] screenshot below.  If you publish your bot, the only people that can use it are ones that have your link.  Right now I do not have 100 people around to test if it is fully published or not.  Your bot will only be searchable if it is a "Featured" bot. If I were you I would just publish it, but I do not fully understand your situation so if that is not possible I'm not sure what else it could be. 
  
  
![capture](https://user-images.githubusercontent.com/6301037/27613905-1864d778-5b53-11e7-9821-e503f7b5edc9.PNG)

**Comment by JasonSowers** [comment]
@auanish We just tried to replicate this with multiple bots sent between multiple people, but we weren't able to reproduce your error.
  
Who are you sending the link to, yourself, or others?  
Can you please try sending the link to the email listed in my profile please?

**Comment by nwhitmont** [comment]
@auanish are you still experiencing the issue after publishing the bot to Skype?

**Comment by auanish** [comment]
I have tried sending the link again just now and it's started to work. The bot's added to my contacts list without any error.

@JasonSowers I have a couple of devices with different Skype accounts. I tried sending the link to both the devices and it didn't work yesterday. But working fine on both of them now.

**Comment by nwhitmont** [comment]
@auanish Thanks for the update. Glad to hear it's working now. 👍

**Comment by saifalamstats** [comment]
Hi. Is it necessary to publish my bot before making it public to selected 100 users?
What I need is: I need one another person (selected by me), to open his/her skype account and can start chatting with my bot

Please guide me on this :)

**Comment by auanish** [comment]
No, you don't need to publish it. On your dashboard, just right-click on Skype channel and copy the link. The link will look something like  `join.skype.com/bot/xxxxxxxxx `. Send that link to any person you want and when they click on it, it will open in Skype. They can then add the bot to contacts and start chatting away.

**Comment by saifalamstats** [comment]
Thank you @auanish

**Comment by saifalamstats** [comment]
Hi, I have a query related to QnA Maker Service.

If suppose a question in my knowledge base has multiple possible answers, and to specify, the knowledge base is in the format - 'duplicate questions ---> unique answers', then how will the matching of question done by the QnA Maker Service and what would be the possible outcome

Just to specify, I understand the case, that a 'weak match' of a user query with multiple questions(in case unique) in the knowledge base, will lead to something called 'QnA Maker Active learning Dialog' , but my concern is regarding the fact that what if I have duplicacy in the questions in the knowledge base, where duplicacy is because of multiple answers to the same question

Guidance will be appreciated :)

**Comment by pssplbhavinc** [comment]
Hi, I have issue while adding Bot to skype channel
![image](https://user-images.githubusercontent.com/18394929/36587165-4f744784-18aa-11e8-8ced-1023b59d6990.png)
