### ISSUE TITLE
[Question] How to get form data from adaptive cards?

### ISSUE THREAD

**Issue by arieschwartzman** [Microsoft/BotBuilder#3047]
## System Information (Required)
* SDK Language: Node
* SDK Version: 3.8.4
* Development Environment: Localhost

## Issue Description
Getting form submitted data from Adaptive Card. 
I used a sample adaptive card from [here](http://adaptivecards.io/samples/#InputForm)
When I press submit, I get the following JSON back in the emulator

```
{
  "type": "message",
  "value": {},
  "from": {
    "id": "default-user",
    "name": "User"
  },
  "locale": "en-US",
  "id": "h6knbli1elfkn0j3",
  "channelId": "emulator",
  "timestamp": "2017-06-28T05:37:12.159Z",
  "localTimestamp": "2017-06-28T08:37:12+03:00",
  "recipient": {
    "id": "lfl386b5hlk8ca9i",
    "name": "Bot"
  },
  "conversation": {
    "id": "cjmea5e5i7bm504ii"
  },
  "serviceUrl": "http://127.0.0.1:25869"
}

```
It looks like the form data is not being delivered from the client to the bot. What am I doing wrong? Is there sample code in Node I can use to see the correct implementation of Form adaptive cards.

Thanks

**Comment by nrobert** [comment]
It seems that there is an issue with getting the value when using `ColumnSet` in AdaptiveCards.
There was a similar ticket a few days ago, https://github.com/Microsoft/BotBuilder/issues/3021

I tested on my side with C# and got the same problem, cannot get the value. When I remove the columns it's working.

**Comment by nwhitmont** [comment]
@arieschwartzman For reference, can you post the adaptive card JSON you are using?

**Comment by nwhitmont** [comment]
relates to: https://stackoverflow.com/questions/44388731/how-can-i-read-the-value-from-complex-adaptive-card

>"This was a bug we fixed in the HTML renderer a few weeks back, but doesn't seem to be in your version of the WebChat control/emulator. I'll look into how we can get the build updated" 

FYI @matthidinger @billba @danmarshall

**Comment by nwhitmont** [comment]
@arieschwartzman You can see a working example of Adaptive Cards with form submit action here: https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node/cards-AdaptiveCards
