### ISSUE TITLE
[LUIS] Node.js getting resolution field from IIntentRecognizerResult from LUIS recognizer

### ISSUE THREAD

**Issue by hantxiao** [Microsoft/BotBuilder#3049]
## System Information (Required)
* SDK Language: NODE.js
* SDK Version: 
* Development Environment: localhost

## Issue Description

There seems to be no way in Node.js of getting the resolution field from an entity in the IIntentRecognizerResult received from LUIS recognizer. The field should be part of the entity according to the json returned by LUIS. There seems to be a way of doing this in C# with EntityRecommendation.
## Code Example

```js
const intentResult = args as BotBuilder.IIntentRecognizerResult;
for (let entity of intentResult.entities) {
      console.log(entity.resolution[0].value);
}
```
## Steps to Reproduce the Issue
1.
2.
3.

## Expected Behavior
According to json returned by LUIS the entities should have a resolution field.

## Actual Results
No field resolution for IEntity

**Comment by stevengum97** [comment]
@hantxiao, is this for prebuilt entities or custom entities that you're not seeing the resolution field?

**Comment by hantxiao** [comment]
It's for building.number

**Comment by hantxiao** [comment]
*buildin.number

**Comment by stevengum97** [comment]
For builtin.number, you don't receive an array for `"resolution"`. When LUIS recognizes `3` and sends it in the results JSON to your bot, the `"resolution"` property would look like the following:

```json
"resolution": {
  "value": "3"
}
```

Closing issue. If you have any other questions regarding this, please feel free to post it here.
