### ISSUE TITLE
[Skype for Business] Any example code for Skype For Business Outbound Bot (Nodejs)

### ISSUE THREAD

**Issue by ceopk** [Microsoft/BotBuilder#3050]
## System Information (Required)
* SDK Language: NODE

## Issue Description
Looking for example to have Skype for Business bot out going message.
There is a C# example at https://github.com/tomorgan/BotFrameworkSkypeforBusinessOutbound.
Is there a similar nodejs example?

The example in https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node works for Skype, but not for Skype For Business. It appear that very time user open a new chat window in Skype For Business, a new conversation id is created. When the window is closed, the conversation is will be invalid.

**Comment by Mikhail2k15** [comment]
C# example doesn't work for me on some tenant :( Looks like it is very early preview.

**Comment by rohankulkarni21** [comment]
I am also looking for same. Skype For Business outbound message using Node.js. Any help will be appreciated.

**Comment by mbettan** [comment]
Any updates? Same need

**Comment by ceopk** [comment]
Still no update :(.

**Comment by intranetchris** [comment]
Same need here. Our outbound/proactive messages function on every channel except Skype for Business. Code sample please!

**Comment by MathieuDuboy** [comment]
+1

**Comment by sinhautkarsh2014** [comment]
+1

**Comment by EricDahlvang** [comment]
Has anyone converted this c# code example to node.js? https://msdn.microsoft.com/en-us/skype/skype-for-business-bot-framework/docs/overview#create-outbound-bots

**Comment by charlesrg** [comment]
Looking forward for examples on NodeJS too. The current documentation only mentions reusing pee-existent conversation IDs.

**Comment by intranetchris** [comment]
Even if a node.js example is provided, it is not possible to send a proactive message to SFB. See #3636 or [SFB feedback forum](https://www.skypefeedback.com/forums/299913-generally-available/suggestions/33146980-bot-send-messages-could-not-delivered-if-sfb-wind).

The only scenario where a SFB proactive message works is when the user happens to have a **conversation window already open with the bot at the moment the proactive message is sent**. Personally, I don't keep conversation windows open with every bot I talk to, just waiting to receive a message! This effectively means that outbound/proactive messages in SFB are not supported.

@JasonSowers says in a [comment](https://github.com/Microsoft/BotBuilder/issues/3636#issuecomment-340075742) on #3636 that the BotBuilder team has absolutely no input on the functionality of each channel. And it doesn't seem like anyone from the SFB team follows these forums. Therefore, I believe [the code sample and surrounding text](https://docs.microsoft.com/en-us/skype-sdk/skype-for-business-bot-framework/docs/overview#creating-outbound-bots) should be removed from the documentation. This issue has cost a lot of developers a lot of time, and this wasted effort could be stopped with updated docs that simply say, "Proactive messages are not supported in Skype for Business".

**Comment by charlesrg** [comment]
That's not what the [documentation](https://docs.microsoft.com/en-us/skype-sdk/skype-for-business-bot-framework/docs/overview#create-outbound-bots) say:


> Skype for Business bots can initiate outbound messages to users proactively because they are enabled by a Tenant Administrator. In order to initiate an outbound message, your bot must be Skype for Business tenant-specific (your code must be written for a bot that will only be deployed in a single tenant. Eg. bot@contoso.com)

**Comment by sueess** [comment]
Any news? Where is the point to have a bot integration, if this does not work?

**Comment by charlesrg** [comment]
I feel the best way to go is to forget about Skype and go with MS Teams.

**Comment by benbrown** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botbuilder-channels/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
