### ISSUE TITLE
[Question] Is it possible to display chat history in client?

### ISSUE THREAD

**Issue by sayyednazeer** [Microsoft/BotBuilder#3051]
Is there any way to store the chat conversation in sql server database and display to the user when he comes next time (recent conversation).

I saw this article to store the conversation in sql server but how can i show that conversation to the user on next time..?

http://aihelpwebsite.com/Blog/EntryId/13/Implementing-A-SQL-Server-Database-With-The-Microsoft-Bot-Framework

**Comment by nwhitmont** [comment]
@sayyednazeer what channel are you using?

**Comment by nwhitmont** [comment]
relates to #3018

**Comment by sayyednazeer** [comment]
@nwhitmont  i want it for direct line and webchat both

**Comment by sayyednazeer** [comment]
@nwhitmont  any update..?

**Comment by NehaShaikh786** [comment]
Hi, i want to store user conversation history and use that conversation to analyze user need. Can you please help? do you have any sample code regarding user history storage?

**Comment by sayyednazeer** [comment]
@NehaShaikh786 

With C# or Node..??

**Comment by NehaShaikh786** [comment]
C#

**Comment by NehaShaikh786** [comment]
Is it possible to have a conversation in particular flow? I want a single luis utterance to have different response in a particular conversation flow, how can i do it? because my utterance hits to a single intent and luis can give a single response everytime. please give solution for C# code.

**Comment by sayyednazeer** [comment]
@NehaShaikh786 

can you be more clear or give me some example so that ill help you out in this.

**Comment by sayyednazeer** [comment]
@nwhitmont any update on my question ..?

**Comment by NehaShaikh786** [comment]
@sayyednazeer 
please review this https://github.com/Microsoft/BotBuilder/issues/3092

**Comment by EricDahlvang** [comment]
Hi @sayyednazeer 

There is an interesting discussion on displaying history at startup here: [GitHub\BotFramework-WebChat](https://github.com/Microsoft/BotFramework-WebChat/issues/365)

afaik, there's no public example for displaying chat history via direct line or webchat.  However, the BotBuilder is open source, and contributions are welcome.

**Comment by SarahSexton** [comment]
My current approach is from the web "push notification" in the browsers, actually, rather than from the chat framework itself. This WebChatPush project can recall chat history from previous windows by clicking on desktop push notifications: [https://github.com/doristchen/WebChatPush](https://github.com/doristchen/WebChatPush)

**Comment by sayyednazeer** [comment]
@SarahSexton  and @EricDahlvang 
Thanks...
ill go through the link mention by you.
