### ISSUE TITLE
[Emulator] Multi User missing in new version of bot emulator

### ISSUE THREAD

**Issue by narulasrinivas** [Microsoft/BotBuilder#3052]
I developed something using bot emulator v3.0.0.57. In that, multi user are available on menu section and it was easy to switch between users. But recently I have downloaded v3.5.29 and in that it is missing. Can anyone suggest how that can be achieved.

I was not following botframework for a while, sorry if question was posted earlier.

**v3.0.0.57**
<img width="823" alt="v3 0 0 57" src="https://user-images.githubusercontent.com/2491903/27641254-449d5b1a-5c13-11e7-9405-d74e0950d48b.png">

**v3.5.29**
<img width="888" alt="v3 5 29" src="https://user-images.githubusercontent.com/2491903/27641237-380a03da-5c13-11e7-8d1b-b1e49065e7d7.png">

**Comment by nwhitmont** [comment]
@narulasrinivas Please post Emulator issues on their repository here: https://github.com/Microsoft/BotFramework-Emulator

**Comment by eanders-MS** [comment]
Correct, the new emulator doesn't support this yet. We have an open issue tracking it here: https://github.com/Microsoft/BotFramework-Emulator/issues/101
