### ISSUE TITLE
[Direct Line] API Europe outage?

### ISSUE THREAD

**Issue by vasilkrastev90** [Microsoft/BotBuilder#3053]
Hi,

Can anyone provide information whether DirectLine API should be running 24/7.  I experience issues when sending messages to/from a bot instance.

Most notably yesterday between 6 pm and 10 pm BST.

Here is the type of message I was receiving in my bot:

```
Error: Request to 'https://europe.directline.botframework.com/v3/conversations/LjU2yO53wRB67lMlHNU6Dw/activities/LjU2yO53wRB67lMlHNU6Dw%7C0000001' failed: [503] Service Unavailable
    at Request._callback (...\ChatConnector.js:452:46)
    at Request.self.callback (...request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (...request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous>(...\request.js:1001:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
```

Do you know of any planned outage? Do you expect any further outages?

This is linked to another issue I have commented on: https://github.com/Microsoft/BotBuilder/issues/507

I also experience occasional issues with calls returning 500 status when calling: 
POST https://directline.botframework.com/v3/directline/conversations/<conversation-name>/activities

or 

POST https://directline.botframework.com/v3/directline/conversations

**Comment by nwhitmont** [comment]
We had a temporary interruption on one server in our North Europe datacenter yesterday. This server generated HTTP 500 and 503 errors for less than 30 minutes, and has been repaired. We don’t have any further interruptions planned.

**Comment by vasilkrastev90** [comment]
@nwhitmont  The outage is aparent again for the europe service: Request to 

https://europe.directline.botframework.com/v3/conversations/40Yu0ECXBGvGshq5S2p11K/activities/40Yu0ECXBGvGshq5S2p11K%7C0000001' failed: [503] Service Unavailable

This is the type of error I am getting. The failures seem to be fairly frequent having the last one 20 days ago.

**Comment by McGern** [comment]
Still getting the same error after an hour of trying? Is there any word on the European data centres outages?

Thanks

**Comment by nwhitmont** [comment]
All services had interruptions between 6:30am and 7:30am.

@vasilkrastev90 @McGern You are commenting on a closed issue. In the future, please open a new issue to report problems/questions.

**Comment by McGern** [comment]
Sorry, thought because it's the same unresolved issue that you might open this one back up rather than having a glut of tickets that are the same,  making it harder to search and parse for the relevant issue
