### ISSUE TITLE
[MS Teams] Microsoft Teams is not communicating events

### ISSUE THREAD

**Issue by bilby91** [Microsoft/BotBuilder#3057]
## System Information (Required)
* SDK Language: NODE
* SDK Version: 3.8.4
* Development Environment: Localhost
## Issue Description

Microsoft Team is not communicating events to my bot. 

I have successfully sideloaded my bot and it showing correctly in the Teams. I can mention on public channels or communicate directly but none of the events are communicated to my bot. I have tried re installing the bot in MS Team but it did not work. I also have the same bot running in Slack and Web and is working correctly.

## Expected Behavior
MS Team events get communicated to my bot.

## Actual Results
MS Team events is not communicating events to my bot.

**Comment by iMicknl** [comment]
Which type of events are your looking for? 
Have also a look at https://github.com/OfficeDev/BotBuilder-MicrosoftTeams, this is a connector for the BotBuilder SDK which has more specific Microsoft Teams functionality.

**Comment by bilby91** [comment]
@iMicknl It's messages and all the other events like `conversationUpdate`, etc. Nothing happens on my bot when I talk.

**Comment by nwhitmont** [comment]
@bilby91 Do you see any errors/warnings in the [Bot Portal](https://dev.botframework.com) channels page?  Does your bot work in the WebChat on Bot Portal?

**Comment by bilby91** [comment]
I don't see any errors and my bot works correctly with web and slack. 

Martín Fernández

On Thu, Jun 29, 2017 at 16:06 Nils

<
mailto:Nils <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

https://github.com/bilby91
Do you see any errors/warnings in the
https://dev.botframework.com
channels page? Does your bot work in the WebChat on Bot Portal?

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/Microsoft/BotBuilder/issues/3057#issuecomment-312069554
, or

**Comment by nwhitmont** [comment]
@bilby91 What is the bot name, handle, and appID used to register the bot?

**Comment by bilby91** [comment]
@nwhitmont 

Bot Name: Suttna Dev Bilby
Handle: suttna-dev-bilby  
App ID: 5b410643-435b-4784-ba03-3b1c3a9f1918

**Comment by nwhitmont** [comment]
When I tested [your bot](https://dev.botframework.com/bots?id=suttna-dev-bilby) just now, it was not responding via webchat. There appears to be a problem with your bod code and/or deployment.

**Comment by nwhitmont** [comment]
I noticed you have used a ngrok URL for your bot's messaging endpoint.  You will need to deploy your bot to Azure or other cloud service if you want it to work reliably in Teams.

**Comment by bilby91** [comment]
@nwhitmont I had the bot turned off. As I mentioned before, everything is working except Teams. I just turned it on so you can test anything. Let me know!

**Comment by bilby91** [comment]
@nwhitmont I don't know what changed but is now working. I'm getting the messages. Thanks!

**Comment by nwhitmont** [comment]
@bilby91 Thanks for the update. Glad to hear you got it working. 👍
