### ISSUE TITLE
[Question] Unsupported Media type error while using LUIS programmatic API

### ISSUE THREAD

**Issue by gitmenonsandu** [Microsoft/BotBuilder#3058]
I am using the LUIS programmatic API to create a LUIS App. Every request with a request body type of “application/json” is working.
In the PUT request to assign subscription key to App, in the link https://dev.projectoxford.ai/docs/services/56d95961e597ed0f04b76e58/operations/580c6eea39e2bb161819981d
It is given request body is of type “text/plain”.
I am using C#, and while using the code sample given in the link, setting media type header value as “text/plain” gives a
Http 415 Response of Unsupported Media Type.

If I am to give as a json response, what is the json format ?

**Comment by cahann** [comment]
You will find an sample example in the latest version of the APIs v2 [docs](https://westus.dev.cognitive.microsoft.com/docs/services/5890b47c39e2bb17b84a55ff/operations/5890b47c39e2bb052c5b9c2f).
