### ISSUE TITLE
[Question] PostAsync causes the context Frames (stack) to go empty

### ISSUE THREAD

**Issue by flq** [Microsoft/BotBuilder#3059]
## System Information (Required)
* SDK Language:  .NET/C#
* SDK Version: BotBuilder 3.8.3
* Development Environment: localhost

## Issue Description

I am currently spiking code to see whether the business logic of Dialogs can be put into a more API-Independent Form. Pattern-wise upon a Dialog call back / continuation, a __Saga__ object is called which then returns a `DialogCommand` that describes what the Dialog is supposed to do next.

One of those commands is __EndDialog__ with an optional text to write before ending the Dialog. I now face the situation that when I send out the text with `PostAsync`, the Stack goes empty and the subsequent call to `context.Done` fails. I am currently unclear on why that should happen.

## Code Example
I can't currently provide a Repro, but this is the code to be found when the Dialog is about to do something after it being triggered:

```csharp
//Called either by "WaitForUserToStart" or a callback from an ending dialog
private async void HandleWhatNext(IDialogContext context, S nextState)
{
    ...
    switch (nextState.Next)
    {
        case EndDialog js:
            if (js.Text != null)
            {
                Debug.WriteLine($"WhatNext on {stateType}, Handling {nextState.Next} with Stack \n{MakeStackDiagnostic(context)}");
                await context.PostAsync(js.Text);
                Debug.WriteLine($"WhatNext on {stateType}, Handling {nextState.Next} with Stack \n{MakeStackDiagnostic(context)}");
                context.Done(js.ReturnValue);
            }
...
```

Now, the output of the first debug.writeline is:

```
WhatNext on AddressChangeState, Handling EndDialog with Stack 
Bot.PartnerEvent.Dialogs.CustomerSagaDrivenDialog`1[Bot.PartnerEvent.AppLogic.AddressChangeState].ContinueSaga
Bot.PartnerEvent.Dialogs.CustomerSagaDrivenDialog`1[Bot.PartnerEvent.AppLogic.RootState].ContinueSaga
Microsoft.Bot.Builder.Dialogs.Chain+LoopDialog`1[System.Object].ResumeAsync
Microsoft.Bot.Builder.Dialogs.Chain+LoopDialog`1[System.Object].ResumeAsync
```

then, in the second (after the `PostAsync`) it is

```
WhatNext on AddressChangeState, Handling Bot.PartnerEvent.Dialogs.EndDialog with Stack 
```

This is the code of `MakeStackDiagnostic`:

```csharp
private static string MakeStackDiagnostic(IDialogContext context)
{
    var stack = string.Join(Environment.NewLine, context.Frames.ToList(d => $"{d.Target}.{d.Method.Name}"));
    return stack;
}
```

## Steps to Reproduce the Issue
1. Build out a stack of multiple nested Dialogs
2. Call PostAsync inside a resume. (???)

## Expected Behavior
`PostAsync` should not cause a reset of the stack (?)

## Actual Results
The stack disappeared after calling `PostAsync`

**Comment by nwhitmont** [comment]
@willportnoy @msft-shahins

**Comment by willportnoy** [comment]
It seems very likely an exception is being thrown - can you break on thrown exceptions in the debugger?  We propagate exceptions thrown within dialog methods up the dialog stack, which is perhaps why it seems like the stack is unwound.

**Comment by flq** [comment]
Hm,
I checked all CLR exceptions, but none is raised at `PostAsync`. I also removed the PostAsync call and then Done would unwind the stack just as expected. I am sadly unsure what minimum Repro I could build, the only thing I could try is to try and run against a version built locally, so I can try and see what exactly causes the stack to unwind.

**Comment by willportnoy** [comment]
if you want to put a breakpoint here:
https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Microsoft.Bot.Builder/Fibers/Fiber.cs#L211

you can step through every executed call back and see the state of the stack at every point.
