### ISSUE TITLE
[MS Teams] GetConversationMembers not working for MS Teams

### ISSUE THREAD

**Issue by bilby91** [Microsoft/BotBuilder#3062]
## System Information (Required)
* SDK Language: NODE
* SDK Version: 3.8.4
* Development Environment: LOCALHOST>

## Issue Description
After sideloading the bot in a MS Team, I'm getting the conversationUpdate event with the conversation id from the address object. When using the conversation id I'm getting an error `Failure due to: ThreadNotFound.`. Same code is working for Slack channel.

```
ERROR { url: 'https://smba.trafficmanager.net/v3/conversations/19%3Aec13f7cc858846d1b4487f8a202ae68c%40thread.skype%3Bmessageid%3D1498769716122/members',
  method: 'GET',
  headers:
   { 'content-length': '77',
     'content-type': 'application/json; charset=utf-8',
     server: 'Microsoft-HTTPAPI/2.0',
     date: 'Thu, 29 Jun 2017 21:00:50 GMT',
     connection: 'close' },
  errObj:
   { Error: Not Found
       at Request.callback (/var/www/app/node_modules/superagent/lib/node/index.js:626:17)
       at /var/www/app/node_modules/superagent/lib/node/index.js:795:18
       at IncomingMessage.<anonymous> (/var/www/app/node_modules/superagent/lib/node/parsers/json.js:16:7)
       at emitNone (events.js:91:20)
       at IncomingMessage.emit (events.js:185:7)
       at endReadableNT (_stream_readable.js:974:12)
       at _combinedTickCallback (internal/process/next_tick.js:80:11)
       at process._tickDomainCallback (internal/process/next_tick.js:128:9)
     original: null,
     response:
      Response {
        domain: [Object],
        _events: {},
        _eventsCount: 0,
        _maxListeners: undefined,
        res: [Object],
        request: [Object],
        req: [Object],
        links: {},
        text: '{"error":{"code":"ServiceError","message":"Failure due to: ThreadNotFound."}}',
        body: [Object],
        files: undefined,
        buffered: true,
        headers: [Object],
        header: [Object],
        statusCode: 404,
        status: 404,
        statusType: 4,
        info: false,
        ok: false,
        redirect: false,
        clientError: true,
        serverError: false,
        error: [Object],
        accepted: false,
        noContent: false,
        badRequest: false,
        unauthorized: false,
        notAcceptable: false,
        forbidden: false,
        notFound: true,
        charset: 'utf-8',
        type: 'application/json',
        setEncoding: [Function: bound ],
        redirects: [] },
     status: 404 },
  status: 404,
  statusText: '{"error":{"code":"ServiceError","message":"Failure due to: ThreadNotFound."}}',
  obj:
   { error:
      { code: 'ServiceError',
        message: 'Failure due to: ThreadNotFound.' } },
  data: '{"error":{"code":"ServiceError","message":"Failure due to: ThreadNotFound."}}' }
```

## Expected Behavior
I will be able to get the members of the team.

## Actual Results
`ThreadNotFound` error is returned when calling the GetConversationMembers.

**Comment by nwhitmont** [comment]
@bilby91 "When using the conversation id..." to do what exactly? What are you trying to do with the conversation ID that triggers this error?

**Comment by bilby91** [comment]
@nwhitmont I'm trying to get the members of the conversation using the id that comes with the `conversationUpdate` event.

`https://smba.trafficmanager.net/v3/conversations/:id/members`

**Comment by nwhitmont** [comment]
Have you had a look at this guide? It walks you through the getConversationMembers scenario.
https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node/core-GetConversationMembers

**Comment by nwhitmont** [comment]
See also - [Bot Connector REST API - GetConversationMembers](https://docs.microsoft.com/en-us/bot-framework/rest-api/bot-framework-rest-connector-api-reference#conversation-operations)

**Comment by bilby91** [comment]
@nwhitmont Yep! That is how I got it working for Slack.

I think that the problem is with the different concepts in MS Teams. When you sideload the app to the Team `conversationUpdate` sends a conversation id but I'm not sure what conversation is referring to.

I'm interested too in understanding what are the limitations in the link you provided:

```
They are also supported, with some limitations, in the following channels:

Facebook
Microsoft Teams
```

**Comment by nwhitmont** [comment]
@bilby91 Based on the docs, you are doing it correctly as described - Eg. `GET /v3/conversations/{conversationId}/members` - so I'm not quite sure.  Like you said, possibly an issue specific to Teams.  I will follow up with the MS Teams team to get more details.

**Comment by bilby91** [comment]
@nwhitmont Thanks! I'm trying other situations to see if I get it right. Let me know if you find something and I will do the same. Thanks!

**Comment by bilby91** [comment]
I tried with a conversation id from a channel originated message and the same happens. Let me know what you find @nwhitmont .

**Comment by RichMoeMSFT** [comment]
@bilby91 Try [this](https://msdn.microsoft.com/en-us/microsoft-teams/botapis#fetching-the-team-roster).  You can see the difference here in the call for Teams:  you need the {teamId}, and you need to include the tenant ID in the "X-MsTeamsTenantId" request header.

The difference in Teams is that you are retrieving all members of the team your bot has been added to, whether part of a conversation stream or not.

**Comment by bilby91** [comment]
@RichMoeMSFT Makes a lot of sense. Will try it and post back.

**Comment by bilby91** [comment]
@RichMoeMSFT If this is the case `The difference in Teams is that you are retrieving all members of the team your bot has been added to, whether part of a conversation stream or not.`, what is are  semantics of the conversation_id in this case ? Is the id of the team ?

**Comment by bilby91** [comment]
@RichMoeMSFT I tried adding the `X-MsTeamsTenantId` but still having the same issue here.

**Comment by RichMoeMSFT** [comment]
Did you try the  BotBuilder Teams Extension SDK's fetchMemberList function, or are you calling the REST endpoint directly?  The former takes care of the extra parameter for you.

**Comment by bilby91** [comment]
@RichMoeMSFT  Solved by implementing my own REST client. I was using the Swagger example. Thanks!

**Comment by JasonSowers** [comment]
Glad you fixed this, good luck
