### ISSUE TITLE
[Question] Behaviour of conversation's isGroup property on Slack

### ISSUE THREAD

**Issue by bilby91** [Microsoft/BotBuilder#3063]
## System Information (Required)
* SDK Language: NODE
* SDK Version: 3.8.4
* Development Environment: LOCALHOST

## Issue Description
When adding the bot in a public channel (Slack), the isGroup conversation's attribute of the message address is `true` or `false` depending on the number of members the channel has. If the channel has only two members, the isGroup channel will return false but if a new members is added (3 members), isGroup is `true`. I was assuming that since the bot is in a channel isGroup was going be true always. Is this the correct behaviour ?  

## Expected Behavior
isGroup property should be true always if bot is in added in a public/private channel. 

## Actual Results
isGroup property is true only if the number of members of the channel is > 2

**Comment by stevengum97** [comment]
Per the [documentation](https://docs.microsoft.com/en-us/bot-framework/rest-api/bot-framework-rest-connector-api-reference#a-idobjectsa-schema) (under Conversation object, searching for `isGroup` is probably quicker), conversations include the bot:

>Defines a conversation, **including** the bot and users that are included within the conversation.

So a channel with only two members qualifies as a private conversation as it's only one user and the bot conversing.

**Comment by bilby91** [comment]
Thanks for the reply!

Is there any way to identify if the conversation is a direct message? I want to identify if user is in a public /private  channel or directly talking to the bot. 

Martín Fernández

On Thu, Jun 29, 2017 at 21:03 Steven Gum

<
mailto:Steven Gum <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Per the
https://docs.microsoft.com/en-us/bot-framework/rest-api/bot-framework-rest-connector-api-reference#a-idobjectsa-schema
(under Conversation object, searching for

isGroup

is probably quicker), conversations include the bot:

Defines a conversation,

including

the bot and users that are included within the conversation.

So a channel with only two members qualifies as a private conversation as it's only one user and the bot conversing.

—

You are receiving this because you authored the thread.

Reply to this email directly,
https://github.com/Microsoft/BotBuilder/issues/3063#issuecomment-312139417
, or

**Comment by bilby91** [comment]
@stevengum97 I have read the docs and the isGroup flag is defined as:

> Flag to indicate whether or not this is a group conversation. Set to true if this is a group conversation; otherwise, false. The default is false. To start a group conversation, the channel must support group conversations.

This statement is indicating that a conversation IS a group conversation or not right ? If this indicates that then I guess the behaviour is not correct because a conversation can have `isGroup == true` at a certain point in time but then change to `isGroup == false`. So, a conversation with the same id can change it's isGroup property during its lifetime.

Maybe it's a bad perception from my side but I feel is not intuitive.

**Comment by aakashkag** [comment]
function public_channel_ensure(session){
  var obj={"isGroup":false,"isAllow":false}
  var address=session.message.address;
  var message=session.message;
  var botname=address.bot.name;
  if(address.conversation.isGroup&&message.text){
    var msgtoken=message.text.toLowerCase().trim().split(/\s+/);
    var attachments=message.attachments||[]
    if(attachments.length==0&&botname&&msgtoken.indexOf("@"+botname.toLowerCase())>-1){
      obj["isGroup"]=true;obj["isAllow"]=true; 
      return obj;
    }
    else{obj["isGroup"]=true;obj["isAllow"]=false; return obj;}
  } 
  else{return obj;} 
}

**Comment by bilby91** [comment]
@aakashkag I don't think that code solves the problem. You are assuming that `isGroup` will be true always in case that channel is public and that is not the case. Try removing every member except you and the bot from the channel and introspect the `isGroup` property.

**Comment by nwhitmont** [comment]
@bilby91 The `isGroup` property isn't specifically designed for Slack only, it's meant to work across multiple possible channels that might have different architectural design concepts from those of Slack. 

For example, in Skype, there are no dedicated "channels" or permanent groups as there are in Slack.  In Skype, a "group" exists when there are more than 2 participants.  Eg. you + bot is not a group, but you + bot + one or more users is a group.  From the perspective of Skype, the setting of the `isGroup` makes sense in this regard. 

Technically, with this context in mind, a Slack conversation with only two users is not a group, even though that conversation might happen inside a Slack "channel". And that is why the actual result you are seeing is in fact, the currently expected behavior.

**Comment by bilby91** [comment]
@nwhitmont I understand, probably is my head too used to Slack.

Thanks!
