### ISSUE TITLE
[Skype for Business] Rich Card is not working

### ISSUE THREAD

**Issue by PrasenjitSaha** [Microsoft/BotBuilder#3065]
I have configured SFB. But Rich Cards are not working. Any suggestion?

**Comment by iMicknl** [comment]
> Skype for Business does not support cards and buttons in the Developer Preview. For the Developer Preview, cards and buttons are not shown to the user if they are sent by a bot. Cards and buttons fallback to text support will be added soon.

[Skype for Business Bot Framework (Preview)](https://msdn.microsoft.com/en-us/skype/skype-for-business-bot-framework/docs/overview)

**Comment by nwhitmont** [comment]
@PrasenjitSaha as @iMicknl mentioned above, rich cards are not currently supported in S4B channel.

**Comment by ne00346536** [comment]
@iMicknl can you please let me know if the rich cards feature support released or not for SFB.

Thanks,
Naresh.

**Comment by sequeiradenzil** [comment]
@ne00346536  you can use [Channel Inspector](https://docs.botframework.com/en-us/channel-inspector/channels/Skype/) to see if a particular channel supports a feature. Came across it.. Thought it would be helpful
