### ISSUE TITLE
[Question] Over 1000 hits in two days after submitted to bing channel

### ISSUE THREAD

**Issue by anarchitect** [Microsoft/BotBuilder#3066]
System Information (Required)
SDK Language: C#
SDK Version: 3.5.9.0
Development Environment: 
Issue Description
can not publish the bot to bing, the submit for review button is always disabled.
Code Example
NA, the bot handle is FindIt
Steps to Reproduce the Issue
After I submitted the bot for review to bing, heavy traffic came in within 2 days, is this expected behavior? is this expected behavior?
![botstaic](https://user-images.githubusercontent.com/2878492/27736799-0df8da44-5de9-11e7-82d7-e6888d20e5fe.png)

**Comment by amitbend** [comment]
I've seen it too, It's a bot that sending some nasty words at specific times during the week.

**Comment by mguthman-MS** [comment]
Thank you for submitting your bot on Bing Channel and reporting this issue!

As part of your submission to Bing Channel, we run automated tests to verify the bot is responding and behaving in an appropriate way. That is why you are seeing an increase in traffic to these bots. Additionally, we intentionally send some offensive terms to verify that the bot responds in an appropriate, inoffensive way.

Based on your feedback, we are reducing the number of requests sent from these monitoring tests and will run them less frequently as well.

Thank you again for building on Bot Framework and keep the feedback coming!

**Comment by anarchitect** [comment]
Thanks very much! I would like to highlight that 1K is the monthly limit of the Bootstrap key for LUIS.ai. So this is actually stopped all my bots working which sharing this key for LUIS.ai.   Can we have the limit for LUIS.ai lifted up?
