### ISSUE TITLE
[Question] Q&A Bot won't work in skype group chats

### ISSUE THREAD

**Issue by dblock110** [Microsoft/BotBuilder#3070]
i have succesfully created a simple Q & A bot with 500 rows of Q's and A's

I can PM the bot on skype and it works flawlessly.

As soon as I add the bot to a skype group chat, it does not work..

This article mentions it has to do with how group messages send text to the bot, but i can't figure out how to modify my code to make it work...

https://github.com/Microsoft/BotBuilder/issues/1748

**Comment by JasonSowers** [comment]
Which SDK C# or Node?  Also, can you post your code to provide context?

**Comment by dblock110** [comment]
i used the standard QNA tutorial from MS bot builder  . . all i have done is edit the rows in the knowledge base that i set up. its .NET 4.6 - VS 14 online .. . 

I am building it via the Azure Portal. The provided code with my knowledge base is amazing for my use.  all i need is really having group chat work...

i'm a noob! but this is just my starting point!

**Comment by EricDahlvang** [comment]
Hi @dblock110 

Thank you for reporting this issue.  It seems RemoveRecipientMention doesn't work as expected for bot mentions on skype.  Until this is fixed, you can implement something like the following in your run.csx (manually removing the bot mention before calling the BasicQnAMakerDialog):

```cs
case ActivityTypes.Message:

if (activity.ChannelId == "skype")
{
    var incomingMessage = activity.AsMessageActivity();
    var mentionFound = (incomingMessage.Entities?.Where(entity => String.Compare(entity.Type, "mention", ignoreCase: true) == 0)
                            .Select(e => e.Properties.ToObject<Mention>())
                            .ToArray() ?? new Mention[0])
                            .Where(mention => mention.Mentioned.Id == activity.Recipient.Id)
                            .FirstOrDefault();

    if (mentionFound != null)
    {
        foreach (var mention in activity.GetMentions().Where(mention => mention.Mentioned.Id == activity.Recipient.Id))
        {
            int index = mention.Text.IndexOf('>');
            var nextIndex = mention.Text.IndexOf('<', index);
            var mentionText = mention.Text.Substring(index + 1, nextIndex - index - 1);
            activity.Text = activity.Text.Replace(mentionText, "");
        }
    }
}

await Conversation.SendAsync(activity, () => new BasicQnAMakerDialog());
break;
```

#3067 is tracking the bug, so I'm going to close this issue.

**Comment by dblock110** [comment]
thank you very much

**Comment by nwhitmont** [comment]
relates to #3067
