### ISSUE TITLE
[Question] Invoke activity doesn't pass value

### ISSUE THREAD

**Issue by wslyvh** [Microsoft/BotBuilder#3072]
## System Information (Required)
* SDK Language: NET/C#

## Issue Description
I've followed instructions as per [https://msdn.microsoft.com/en-us/microsoft-teams/botsmessages#action---invoke](url) to add buttons to a reply to my user, with type 'invoke' and a value set. But when the user clicks either buttons, the value remains null (or empty).

I'm testing on MS Teams.

## Code Example

MessagesController
```

            var connector = new ConnectorClient(new Uri(activity.ServiceUrl));

            if (activity.Type == "invoke")
            {
                var invoked = activity.CreateReply($"User {activity.From.Name} invoked: {activity.Value}");
                await connector.Conversations.ReplyToActivityAsync(invoked);
            }
            else
            {
                var good = new CardAction("invoke", "Good", null, "Good");
                var bad = new CardAction("invoke", "Bad", null, false);
                var card = new HeroCard("How are you today?", null, null, null, new List<CardAction>() { good, bad }).ToAttachment();

                var reply = activity.CreateReply();
                reply.Attachments.Add(card);

                await connector.Conversations.ReplyToActivityAsync(reply);
            }

```

## Steps to Reproduce the Issue
1. Post anything to the bot to trigger the reply, with the 2 options
2. Click on either 'Good' or 'Bad'

## Expected Behavior
That in the next message I'd receive; User {username} invoked: Good
(or Bad, depending on which button) 

## Actual Results
User {username} invoked: 

The value remains empty.

How do I retrieve or read back the option the user selected?

**Comment by nrobert** [comment]
Hello here,

The strange thing is that `invoke` is an `ActivityType`, not a valid `CardAction.Type` based on the list available here: https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-add-rich-card-attachments#process-events-within-rich-cards , there is no `invoke` but the following: 

> imBack = Text of the message to send to the bot (from the user who clicked the button or tapped the card). This message (from user to bot) will be visible to all conversation participants via the client application that is hosting the conversation.

So I think this is what you are trying to perform. What is strange is the fact that the documentation on Teams side mentions: 

> Teams does not support postBack, signin or other CardActions.

I tried to test your implementation and got the same conclusion:  invoke is thrown, but cannot have a value.

Here is a sample of the json received in Teams when clicking on the Good button, if it can be useful for further investigation:
```
{
	"type": "invoke",
	"id": "f:6863855948665521944",
	"timestamp": "2017-07-03T15:12:25.057Z",
	"localTimestamp": null,
	"serviceUrl": "https://smba.trafficmanager.net/emea-client-ss.msg/",
	"channelId": "msteams",
	"from": {
		"id": "29:1ar5DNnMK....",
		"name": "Nicolas Robert"
	},
	"conversation": {
		"isGroup": null,
		"id": "a:1vI2_hwOiPhmy2.....",
		"name": null
	},
	"recipient": {
		"id": "28:ae57c.....",
		"name": "BotDemoStart"
	},
	"textFormat": null,
	"attachmentLayout": null,
	"membersAdded": [],
	"membersRemoved": [],
	"topicName": null,
	"historyDisclosed": null,
	"locale": null,
	"text": null,
	"speak": null,
	"inputHint": null,
	"summary": null,
	"suggestedActions": null,
	"attachments": [],
	"entities": [{
		"type": "clientInfo",
		"locale": "fr-CA",
		"country": "CA",
		"platform": "Mac"
	}],
	"channelData": {
		"tenant": {
			"id": "9ffc6712-...."
		}
	},
	"action": null,
	"replyToId": null,
	"value": {},
	"name": null,
	"relatesTo": null,
	"code": null
}
```

**Comment by wslyvh** [comment]
Thanks for the feedback! The link I posted before shows differently though.
https://msdn.microsoft.com/en-us/microsoft-teams/botsmessages#action---invoke

Teams supports the following CardAction Types:
- openUrl
- imBack
- invoke

Teams does not support postBack, signin or other CardActions.

The link you posted is for the Bot Framework in general I guess?

**Comment by nrobert** [comment]
That's what I said: there is a "strange thing" between the implementation of `CardAction` in MS Teams and `CardAction` in Bot Framework.

Anyway, the real problem behind is the fact that the `value` is not populated as you said.

@nwhitmont , is it possible to remove Adaptive Cards label here (it's only Rich cards) and change question label to bug label?

**Comment by RichMoeMSFT** [comment]
@wslyvh Team's invoke requires a JSON payload in the Value field.  

E.g. for your value:
Value = "{\"invokeValue\": \"Good\"}"

And correct per above:  invoke is an ActivityType.

**Comment by nrobert** [comment]
@RichMoeMSFT thanks for the feedback. As far as I remember I tested `invoke` with a JSON payload the other day and that was not working, but I will check twice tomorrow

**Comment by wslyvh** [comment]
Thanks @RichMoeMSFT, missed that part I guess.. I can confirm it works using a JSON payload.

For reference the updated code:

`if (activity.Type == "invoke")
            {
                var invoked = activity.CreateReply($"User {activity.From.Name} invoked. Value: {activity.Value}");
                await connector.Conversations.ReplyToActivityAsync(invoked);
            }
            else
            {
                var good = new CardAction("invoke", "Good", null, "{\"invokeValue\": \"Good\"}");
                var bad = new CardAction("invoke", "Bad", null, "{\"invokeValue\": \"Bad\"}");
                var card = new HeroCard("How are you today?", null, null, null, new List<CardAction> { good, bad }).ToAttachment();

                var reply = activity.CreateReply();
                reply.Attachments.Add(card);

                await connector.Conversations.ReplyToActivityAsync(reply);
            }`

Thanks!

**Comment by nrobert** [comment]
Good to know! Thanks for the feedback @wslyvh I got to see what I did wrong in my tests

**Comment by JasonSowers** [comment]
please reopen this issue if needed
