### ISSUE TITLE
[Question] Retrieve data from DocumentDB/CosmoDB

### ISSUE THREAD

**Issue by xjose97x** [Microsoft/BotBuilder#3077]
## System Information (Required)
* SDK Language: C#
* SDK Version: 3.8.3
* Development Environment: LOCALHOST, AZURE_APP_SERVICE

## Issue Description
I followed the tutorial to setup BotBuilder with DocumentDB(now is named CosmoDB), and it's working fine. When I save stuff at UserData/ConversationData/PrivateConversationData, it is being saved with no issues.
However, I'm trying to retrieve data from a specific user in the facebook channel, (me being any other user), but so far I've had no success.

## Code Example
`var state = activity.GetStateClient();

var userData = state.BotState.GetUserData(ChannelIds.Facebook, "1529807860376664");`

## Expected Behavior
To receive the userData stored in my cosmodb associated to that facebook user

## Actual Results
BotData.Data = null
BotData.ETag = "*"

**Comment by xjose97x** [comment]
And the documents exist on Document DB, that part is doing good.

**Comment by megancooper** [comment]
@xjose97x I am not using DocumentDB/CosmoDB but I am sending certain values to my Dialog class when a message Activity is sent to my bot. Noticed no one had answered this so I wanted to help if I could!

Here are the lines I have in my MessagesController.cs:

```
// Sends user's Id and Name to RootDialog Class
StateClient stateClient = activity.GetStateClient();
BotData userData = await stateClient.BotState.GetUserDataAsync(activity.ChannelId, activity.From.Id);
userData.SetProperty<string>("UserId", activity.From.Id);
userData.SetProperty<string>("Name", activity.From.Name);

// send these values in the Context
await stateClient.BotState.SetUserDataAsync(activity.ChannelId, activity.From.Id, userData);

```

And here is how I actually pull that data. You may be accessing them wrong...? Although I'm not sure.:

Inside my (LUIS) Dialog class:

```
public async Task displayHelpMSG(IDialogContext context, LuisResult result)
{
     var _username = context.UserData.GetValue<string>("Name");
     var _userID      = context.UserData.GetValue<string>("UserId");
} 

```

**Comment by JasonSowers** [comment]
@xjose97x  `var state = activity.GetStateClient();` will always get the default state client, not any custom implementation.

**Comment by xjose97x** [comment]
Thanks @JasonSowers !
Really appreciate it. Saw your answer here: https://github.com/Microsoft/BotBuilder/issues/3448

**Comment by xjose97x** [comment]
@JasonSowers , would be nice if that information could be added here: https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-state-azure-cosmosdb
