### ISSUE TITLE
Simple storage similar to BotKit?

### ISSUE THREAD

**Issue by MiroValchev** [Microsoft/BotBuilder#308]
BotKit has a simple implementation for JSON storage:
https://github.com/howdyai/botkit/blob/master/lib/storage/simple_storage.js

Can we expect such a thing in BotBuilder? 
MemoryStorage is not gonna work for persisting user related info, i.e. logs, orders etc.
I can't imagine saving large amounts of data to session.userData or am I wrong?

**Comment by MiroValchev** [comment]
Ok, just saw this:
https://github.com/Microsoft/BotBuilder/blob/c0a530bdc3cc1e35691ddc11cf0e25c1145979a0/Node/src/bots/BotConnectorBot.ts#L207

It's obviously in development. @Stevenic can you post here when it's ready. Thanks!

**Comment by Stevenic** [comment]
I haven't touted it too much because we keep changing it. I think it's almost in its final form but I'd give it another week or two. Plus I have to finish wiring it up.

**Comment by MiroValchev** [comment]
Thanks mate!

**Comment by Stevenic** [comment]
Since this is underway closing issue.

**Comment by MiroValchev** [comment]
I haven't used BotBuilder for a while. It seems there is some storage implementation, but can't find anything in the repo (aside from MemoryStorage). Anyway, I wrote a simple SQLite storage for Slack. Hope it can be usefull here as well...
https://github.com/MiroValchev/botkit/blob/36cb57d57cd8a3a44617dce7e5b63ae2ab3dbb58/lib/storage/sqlite_storage.js

**Comment by Stevenic** [comment]
Awesome... thanks @MiroValchev !
