### ISSUE TITLE
[Question] Bot Builder resources for portuguese language

### ISSUE THREAD

**Issue by dirugadr** [Microsoft/BotBuilder#3082]
## System Information (Required)
* SDK Language: .NET/C# 
* SDK Version: 3.8.1
* Development Environment: LOCALHOST

## Issue Description
I'd like to know if there a way to add the portuguese language to the available languages included in the SDK.

I mean, I've already downloaded a version from the repository, added the corresponding "Microsoft.Bot.Builder.pt.xlf" file to the project (with all text translated) and now, if I reference into my bot project with "custom" sdk, it works, but what if the sdk is updated?

I'd like to have the language already included.

I can send you the file, if you want it.
Regards,
Adrián

**Comment by EricDahlvang** [comment]
Hi @dirugadr 

The Bot Builder is open source, and a Portuguese contribution would be appreciated.  Please review the [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/). Then, fork the repository, switch to the develop branch, and add your "Microsoft.Bot.Builder.pt.xlf" to [./CSharp/Library/Microsoft.Bot.Builder/MultilingualResources](https://github.com/Microsoft/BotBuilder/tree/develop/CSharp/Library/Microsoft.Bot.Builder/MultilingualResources). Also add the appropriate .resx in [./CSharp/Library/Microsoft.Bot.Builder/Resource](https://github.com/Microsoft/BotBuilder/tree/develop/CSharp/Library/Microsoft.Bot.Builder/Resource)  Then make a pull request and the Bot Framework engineers will review. 

Thanks for using the Microsoft Bot Builder!

**Comment by nwhitmont** [comment]
Contribution workflow:
1. Fork this repository (BotBuilder)
2. Create a new feature branch in your fork
3. Check-in your changes to your feature branch in your fork
4. Submit a Pull Request (PR) from your feature branch in your fork, back to BotBuilder/master
5. BotBuilder team will review PR and merge changes
