### ISSUE TITLE
[Question] imBack and postBack not working for FB Messenger

### ISSUE THREAD

**Issue by GanadiniAkshay** [Microsoft/BotBuilder#3084]
## System Information (Required)
* SDK Language:  NODE 
* SDK Version: 3.8.4
* Development Environment: Localhost, ngrok

## Issue Description
The imBack and postback on cards doesn't work on messenger. The message doesn't even reach the development server. For some reason it gets blocked at the bot connector itself.

## Code Example
```
bot.dialog('/', function(session, args){
    session.send(session.message.text);

    var msg = new builder.Message(session)
                    .attachmentLayout(builder.AttachmentLayout.carousel)
                    .attachments([
                        new builder.HeroCard(session)
                                .title("Thumbnail Card")
                                .subtitle("Pike Place Market is a public market")
                                .images([
                                    builder.CardImage.create(session, "https://upload.wikimedia.org/wikipedia/en/thumb/2/2a/PikePlaceMarket.jpg/320px-PikePlaceMarket.jpg")
                                ])
                                .buttons([
                                    builder.CardAction.openUrl(session, "https://en.wikipedia.org/wiki/Space_Needle","Wikipedia"),
                                    builder.CardAction.imBack(session, "session:100", "Select")
                                ])
                    ])
    session.send(msg);
});
```

## Steps to Reproduce the Issue
1. Create a basic echo bot
2. Send a card message with a imBack button along with the echo message
3. Click on the imBack button on messenger

## Expected Behavior
The bot echoes the imBack text and sends the card with the button again

## Actual Results
Nothing happened. The imBack message just gets ignored after showing a typing message.
![screen shot 2017-07-05 at 5 31 18 pm](https://user-images.githubusercontent.com/4831052/27863453-d1249ee2-61a7-11e7-99c5-8d5de8de4d65.png)

**Comment by Devric** [comment]
Any update to this?

Not just Messenger, even bot emulator behaves the same.
It supposes to advance to the next waterfall dialog.

**Comment by TchuBotin** [comment]
Hi guys, have you solved it, I'm facing the same issue!

**Comment by Nergie** [comment]
enable messaging_postbacks  on facebook to solve it!!
