### ISSUE TITLE
[Question] Dealing with period "." sign from every Cortana input.

### ISSUE THREAD

**Issue by anarchitect** [Microsoft/BotBuilder#3085]
I have a few bots enabled to Cortana channel and find Cortana automatically adding a period "." at the end of each voice input. for example, if I say "hello", the text in the activity object is "hello."  Can Cortana remove this period? or the bot framework might want to remove this period at the end of each sentence when it is from Cortana channel. The impacts of this "." sign are : 

- When use Dialog to have the conversation, if the property is an int, when user say "2", bot framework will receive "2**.**", which result in error because 2. is not a integer. 

- Other channel doesn't add this period sign, so when my bot is configured for multiple channel, and for some reason I will use string.equal, then it won't be equal for Cortana string because of this extra Cortana sign. 

- When I speak to Cortana such as "How are you", it still add a period sign instead of a quesiton mark.

**Comment by nwhitmont** [comment]
@anarchitect Are you using .NET or Node SDK? Can you provide more context, for example a code sample that reproduces the error, and screenshots of the output your are seeing? Thx

**Comment by nwhitmont** [comment]
This is by design and bots should handle this. The reason for this is that Cortana is capable of capturing multiple sentences of speech. Depending on how something is said Cortana will add a period as she thinks it is the end of a sentence.

**Comment by anarchitect** [comment]
Hi, I am using .net sdk, the big deal is integer. "2." Is not recognised as
integer. We had a bot had this issue, but work around by using string
instead of Int.
