### ISSUE TITLE
[Question] Support for .NET 4.5 in SDK v3.5 or greater

### ISSUE THREAD

**Issue by bradbart** [Microsoft/BotBuilder#3088]
## System Information (Required)
* SDK Language: .NET/C# 4.5.2
* SDK Version: 3.2.1
* Development Environment: LOCALHOST

## Issue Description
According to recent announcements, we need to upgrade to v3.5 of the Bot SDK or greater, however the latest available version of the Bot SDK that targets .NET 4.5.2 is 3.2.1. Is there a plan to update the version of the SDK available for version 4.5.2 of .NET or will we need to build from source in order to keep up to date with the Bot SDK?

**Comment by EricDahlvang** [comment]
Hi @bradbart,

There are no plans to update the previous versions of BotBuilder to support .net 4.5  The connector continues to target .net 4.5, but the bot builder core itself was moved up to 4.6 in order to utilize the improvements in culture propagation among threads.

**Comment by bradbart** [comment]
Thanks for the quick response, Eric. I'll investigate the right approach for my bot for migrating to the new version of the SDK.
