### ISSUE TITLE
[Question] session.userData MAX_DATA_LENGTH?

### ISSUE THREAD

**Issue by TrejGun** [Microsoft/BotBuilder#3095]
## System Information (Required)
* SDK Language: NODE
* SDK Version: 0.6.0
* Development Environment: any

## Feature request
Let us set `session.userData` size manually
for now its hardcoded to 
```
var MAX_DATA_LENGTH = 65000;
```
at

https://github.com/Microsoft/BotBuilder/blob/master/Node/core/src/bots/ChatConnector.ts#L51

please change it to something like
```
var MAX_DATA_LENGTH = process.env.MAX_DATA_LENGTH || 65000;
```

**Comment by nwhitmont** [comment]
@TrejGun For reference, the size limit on `userData` is a feature, not a bug.

From the documentation article [Manage state data:](https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-state)

>By default, the Bot Framework SDK stores state data using the Bot Framework State service, **which is intended for prototyping only** and is **not designed for use by bots in a production environment.** For performance and security reasons in the production environment, you should either use the Bot Builder SDK [Azure Extensions](https://github.com/Microsoft/BotBuilder-Azure) to store state data in your own Azure Table storage or Azure DocumentDB store or create a custom implementation of `IBotDataStore` to store state data in the destination that you specify.

## How to setup custom State Service Node
To get started with your own custom state service, check out the article [Manage state data](https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-state)

>The Bot Framework State service enables your bot to store and retrieve state data that is associated with a user, a conversation, or a specific user within the context of a specific conversation. State data can be used for many purposes, such as determining where the prior conversation left off or simply greeting a returning user by name. If you store a user's preferences, you can use that information to customize the conversation the next time you chat. For example, you might alert the user to a news article about a topic that interests her, or alert a user when an appointment becomes available.

>In the BotBuilder SDK for Node.js, the ChatConnector class provides an implementation of this storage system and you can use the session object to store, retrieve, and delete state data.

To create your own Bot State Service, use the [botbuilder-azure](https://github.com/Microsoft/BotBuilder-Azure) extensions library provided on GitHub and [NPM](https://www.npmjs.com/package/botbuilder-azure).

The repository also contains sample implementations for both [Azure Table Storage](https://github.com/Microsoft/BotBuilder-Azure/tree/master/Node/examples/feature-azureTable) and [DocumentDB](https://github.com/Microsoft/BotBuilder-Azure/tree/master/Node/examples/feature-documentDb) integrations. (Note: DocumentDB implementation also supports [CosmosDB](https://docs.microsoft.com/en-us/azure/cosmos-db/introduction), Microsoft's next generation version of DocumentDB)

**Comment by aakashkag** [comment]
you can use Mongo db to store session data.
https://github.com/Manacola/msbotframework-mongo-middlelayer

**Comment by TrejGun** [comment]
@nwhitmont thanks a lot

@aakashkag thanks for your code, i appreciate when people push their code to opensource, unfortunately your code can't be used as is and required a lot of work but it inspired me to create my own middleware

**Comment by TrejGun** [comment]
for any other who is interested in mongo storage
[git](https://github.com/TrejGun/mongo-bot-storage) or npm `mongo-bot-storage`

**Comment by aakashkag** [comment]
@trejgun I updated my code as well as created video to demonstrate bot with mongodb storage.. find video link on my github page

**Comment by aakashkag** [comment]
https://youtu.be/S0oO81oG2GY

**Comment by TrejGun** [comment]
yeah, good video but why did you put `node_modules` dir into git repo?

**Comment by aakashkag** [comment]
I am beginner's in node js. I will learn by my mistake in future and mentor like you :). Thanks for point out my mistake. Hope my code is helping to people who want to use mongo db as  storage
