### ISSUE TITLE
[Question] changed Messaging endpoint, but not applied facebook & telegram

### ISSUE THREAD

**Issue by bestbykim** [Microsoft/BotBuilder#3096]
## System Information (Required)
* SDK Language: .net
* SDK Version: 3.8.0
* Development Environment: bot framework, azure api app, facebook, telegram

## Issue Description
I changed 'Messaging endpoint' on https://dev.botframework.com
It is applied on web chat, but not applied on facebook messanger & telegram.
Even though I have shut down older server, the chatbot on old server still works. 

What should I check?

**Comment by nwhitmont** [comment]
@bestbykim It takes some time for the changes to propagate down to the different channels. Are you still experiencing the issue? How long since you updated the endpoint in the Bot Portal?

**Comment by bestbykim** [comment]
@nwhitmont 
I made four instances (release, dev, two deleted dev)

It seems that telegram and facebook are connected to different endpoints (two deleted dev).
only web chat is connected new endpoint(release).

I will make on new bot on botframe.com, and test to be applied.

**Comment by fanidamj** [comment]
Hoping that issue has been resolved, closing it. Feel free to reopen if any questions.
