### ISSUE TITLE
[Question] Error 401 on C# Facebook Bot using Microsoft Bot Connector

### ISSUE THREAD

**Issue by donromeo** [Microsoft/BotBuilder#3098]
* SDK Language: .NET/C# MS Visual Studio 2915 Community
* SDK Version: Microsoft Bot Builder 3.8.1
* Development Environment: Localhost on VMSphere

## Issue Description
Running the app with the Bot emulator works flawlessly and returns the expected message:
When I deploy the app to IIS, I get the correct request at ngrok, but then the application responds with 401 Unauthorized 22.75s .

From the documentation it is clear to me that the credentials inside Web.config should be MicrosoftAppId and MicrosoftAppPassword, but searching past issues some people suggest changing those to appId ans appPassword, can you please clarify the correct names?

Infrastructure specialists suggest that maybe there is an issue with firewalls that needs to be fixed, but they will like to know the url where the applications tries the authentication to check there is a path to the authenticator.

## Code Example
using System;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Http;
using Microsoft.Bot.Connector;

namespace steRegistroFB
{
    [BotAuthentication]
    public class MessagesController : ApiController
    {
        // Get message from user.
        //-----------------------
        public async Task<HttpResponseMessage> Post([FromBody]Activity activity)
        {
            if (activity.Type == ActivityTypes.Message)
            {
                // Text received must be numeric of size 10.
                //------------------------------------------

                string numg = string.Empty;
                string txt = activity.Text;
                bool itisnumg = false;

                // Check if number comes as first 10 characters.
                //-------------------------------------------------------
                int length = (txt ?? string.Empty).Length;
                long tnumber = 0;
                bool isn = false;
                if (length >= 24) {
                    // Check if number follows #xxxxxxxxxxio and " " or "(".
                    //---------------------------------------------------------------
                    txt = txt.Replace("í", "i").ToLower();
                    if ((txt.Substring(0, 14) == "#xxxxxxxxxxio ") || (txt.Substring(0, 14) == "#xxxxxxxxxxio("))
                    {
                        numg = txt.Substring(14, 10);
                        isn = long.TryParse(numg, out tnumber);
                        if (isn) itisnumg = true;
                    }
                }

                if (itisnumg)
                {
                    // Number is 10 digits, let's proceed.
                    //---------------------------------------------

                    // Extract info from message.
                    //---------------------------
                    var fromid = activity.From.Id;
                    var fromnmca = activity.From.Name;
                    var fromnm = fromnmca.Replace("'", "");

                    ConnectorClient connector = new ConnectorClient(new Uri(activity.ServiceUrl));

                    // Globals.
                    //---------
                    string conStr = String.Empty;
                    string tmp = String.Empty;

                    try
                    {
                        // Number exists, send information message and exit.
                        //-----------------------------------------------------------
                        Activity reply = activity.CreateReply($"Number = {(tnumber)} Fromid = {(fromid)} Fromnm = {(fromnm)}.");
                        await connector.Conversations.ReplyToActivityAsync(reply);
                    }
                    catch (Exception e)
                    {
                        // Exception Rised.
                        //-----------------
                        Console.WriteLine("Exception = " + e.Message + "\n");
                    }
                }
                // DO NOTHING.
            }
            else
            {
                HandleSystemMessage(activity);
            }
            var response = Request.CreateResponse(HttpStatusCode.OK);
            return response;
        }

        private Activity HandleSystemMessage(Activity message)
        {
            if (message.Type == ActivityTypes.DeleteUserData)
            {
                // Implement user deletion here
                // If we handle user deletion, return a real message
            }
            else if (message.Type == ActivityTypes.ConversationUpdate)
            {
                // Handle conversation state changes, like members being added and removed
                // Use Activity.MembersAdded and Activity.MembersRemoved and Activity.Action for info
                // Not available in all channels
            }
            else if (message.Type == ActivityTypes.ContactRelationUpdate)
            {
                // Handle add/remove from contact lists
                // Activity.From + Activity.Action represent what happened
            }
            else if (message.Type == ActivityTypes.Typing)
            {
                // Handle knowing tha the user is typing
            }
            else if (message.Type == ActivityTypes.Ping)
            {
            }

            return null;
        }
    }
}

## Steps to Reproduce the Issue
1. From Facebook Messenger send message: #xxxxxxxxxxio 1234512346 to facebook page Gelste.
2.
3.

## Expected Behavior
Receive message:
Number = 1234512345 Fromid = default-user Fromnm = User.

## Actual Results
No response

## Additional info
The credentials in my Web.config are:
    <add key="BotId" value="dhbot" /> 
    <add key="MicrosoftAppId" value="c01306d8-09d8-44cb-be29-48ff12a56824" />
    <add key="MicrosoftAppPassword" value="wTw******" />

If I remove the MicrosoftAppId and MicrosoftAppPassword, actually changing them to appId and appPassword, the application runs and returns 200 OK, but the user receives nothing.

## Request received at ngrok
{
    "type": "message",
    "id": "mid.$cAAUstCEH4ANjSwEnAldGbwL0ajBf",
    "timestamp": "2017-07-06T21:08:49.026Z",
    "serviceUrl": "https://facebook.botframework.com",
    "channelId": "facebook",
    "from": {
        "id": "1045015032270923",
        "name": "Romeo Marquez"
    },
    "conversation": {
        "isGroup": false,
        "id": "1045015032270923-1456526561026871"
    },
    "recipient": {
        "id": "1456526561026871",
        "name": "dhbot"
    },
    "text": "#xxxxxxxxxxio 1234512345",
    "channelData": {
        "sender": {
            "id": "1045015032270923"
        },
        "recipient": {
            "id": "1456526561026871"
        },
        "timestamp": 1499375329026,
        "message": {
            "mid": "mid.$cAAUstCEH4ANjSwEnAldGbwL0ajBf",
            "seq": 12993,
            "text": "#xxxxxxxxxxio 1234512345",
            "is_echo": false
        }
    }
}

**Comment by nwhitmont** [comment]
@donromeo Does your server have a valid SSL certificate?

**Comment by donromeo** [comment]
Yes it does. We tried first with the SSL certificate, but couldn't see anything so we decided to install ngrok to be able to see the messages flow.

**Comment by JasonSowers** [comment]
If this is still an issue please reopen and continue the conversation.
