### ISSUE TITLE
Better error handling

### ISSUE THREAD

**Issue by mikkhait** [Microsoft/BotBuilder#310]
Currently, when an error occur inside of a waterfall function, the error is swallowed and waterfall continues to the next step. 

This is pretty hard to debug.

Perhaps a better way of handling, bubbling up an exception within a waterfall flow.

**Comment by Stevenic** [comment]
Agree... There are definitely cases where I'm swallowing exceptions. I have logic to bubble it up I'm just being too aggressive in certain cases. I need to write a unit test that throws an exception in every possible callback so I can ensure they all bubble. Just haven't had time to do that yet.

**Comment by Stevenic** [comment]
I just checked in a new errors.js test and found & fixed an issue with the LuisDialog swallowing errors.

**Comment by mikkhait** [comment]
yep, looks good. Thanks a lot!

**Comment by alapiere** [comment]
Hi. I'm a total beginner, and spent a lot of time to understand why I had these 
> ERROR: Too many calls to session.endDialog()
all the time, before I understood there was an underlying error swallowed .. now I understand !
any clue when this next release will happen so we can debug more easily, or any best practice alternative to actually see these errors ?

**Comment by Stevenic** [comment]
I'm trying to get it out this week. I made a pretty big change not related to this issue but it means a bunch of additional testing and documentation work.

**Comment by v-thgratMSGit** [comment]
Closing this issue. Please open a new issue for further discussion if necessary. @Stevenic - reopen if not implemented.  Thanks!
