### ISSUE TITLE
[Question] Is it possible to check whether message has been delivered by postBack or imBack?

### ISSUE THREAD

**Issue by bestbykim** [Microsoft/BotBuilder#3100]
## System Information (Required)
* SDK Language: .net
* SDK Version: 3.8.3
* Development Environment: azure, bot emulator, facebook, telegram.. 

## Issue Description
Is it possible to check whether message has been delivered by postback or imback?

I used message.TextFormat on emurator & webchat, but It always seems to be null on facebook & telegram.

I want to send a user's choice in a hidden json string message.

Are there related properties? If not, I hope it is added.

**Comment by nrobert** [comment]
There seems to be no unique way between channels to identify if a message is imBack or postback.
Moreover some channels have the same behaviour for imBack / postBack (like Facebook with QuickReplies)

**Comment by bestbykim** [comment]
thanks reply.
Using json string for postback has problem on telegram,
I will use the custom url like ' bot:// '.

**Comment by JasonSowers** [comment]
Closing this issue, but if you would like to continue the conversation, please reopen.
