### ISSUE TITLE
[Question] Does the userId change? 

### ISSUE THREAD

**Issue by panosVeran** [Microsoft/BotBuilder#3101]
## System Information (Required)
* anguage: node
* Development Environment: other

## Issue Description
I have a general question regarding userId and I have read all the relevant documentation. I know the userId is uniquely assigned per bot per channel, but does it ever change? (As we go to production and need to use token to authorize users, i need such info). Who issues these ids? my guess is the channels, right? 

If I change some of the info on microsoft's bot framework site about my bot, for example, it's name or something, does the userid or botid change?

thnaks in advance

**Comment by nwhitmont** [comment]
@panosVeran The `user.id` property is specific to the channel, as defined in the [IIdentity interface](https://docs.botframework.com/en-us/node/builder/chat-reference/interfaces/_botbuilder_d_.iidentity.html). The `bot.id` property is also an instance of the IIdenty type and is unique to the channel as well.

**Comment by panosVeran** [comment]
yeap, i know that.

let me give you an example. in my company we have a bot, we stored the userids of the users so we can offer them authorization to be able to access personalized information. However at some point the Userids for a specific channel changed. the users weren't able to access their info because the new ids didn't much the old ones. 

So, why did they change? the channels are responsible for issuing the ids? the framework? what happened in the case i described you?

thanks in advance

**Comment by EricDahlvang** [comment]
Hi @panosVeran 

Please check out [https://docs.microsoft.com/en-us/bot-framework/resources-identifiers-guide](https://docs.microsoft.com/en-us/bot-framework/resources-identifiers-guide) Depending on the channel you are using, the identifier might not be reliable.
