### ISSUE TITLE
[Question] Masking Password field in Adaptive Card?

### ISSUE THREAD

**Issue by RaoVenka** [Microsoft/BotBuilder#3102]
HI,
 I have created a Login page  through adaptive card in Microsoft bot framework. How do I hide the password text ?Is it possible in Adaptive card?Kindly help me regarding this issue.

**Comment by nwhitmont** [comment]
@RaoVenka Password masking is not currently a feature. We recommend using the Sign-in Card workflow.

## Bot Authentication Resources
https://blogs.msdn.microsoft.com/richard_dizeregas_blog/2017/05/15/bot-authentication-in-the-bot-framework/

## Authentication - .NET Examples
You might want to start by watching this video: https://channel9.msdn.com/Shows/Office-Dev-Show/Office-Dev-Show-Episode-34-Getting-Started-with-Bots-and-the-Microsoft-Graph

Next, you can study this code example which demonstrates a Bot Framework integration with Active Directory. https://github.com/MicrosoftDX/AuthBot

You might also consider looking at the Sign-in Card example, which can also be used to authenticate your bot via web sign-in.

Docs:
- https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-add-rich-card-attachments#add-a-sign-in-card-to-a-message

Code example:
- https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/cards-RichCards

Sign-in Card:
```cs
Activity replyToConversation = message.CreateReply("Should go to conversation");
replyToConversation.Attachments = new List<Attachment>();

List<CardAction> cardButtons = new List<CardAction>();

CardAction plButton = new CardAction()
{
    Value = $"https://<OAuthSignInURL",
    Type = "signin",
    Title = "Connect"
};

cardButtons.Add(plButton);

SigninCard plCard = new SigninCard(title: "You need to authorize me", button: plButton);

Attachment plAttachment = plCard.ToAttachment();
replyToConversation.Attachments.Add(plAttachment);

var reply = await connector.Conversations.SendToConversationAsync(replyToConversation);
```

**Comment by jimmyhawkins** [comment]
but that is wrong, I mean with signin card we can not apply userid and password, like classic authorization way
