### ISSUE TITLE
[Skype for Business] 'Could not load file or assembly' server errors 

### ISSUE THREAD

**Issue by v46** [Microsoft/BotBuilder#3103]
## Issue Description

We are seeing 'Could not load file or assembly' Bot framework server side exceptions when the Node SDK attempts to 'reply' to conversations. This seems to happen when we have cards in the payload.

Any help with getting past this error please?

```
{ Error: 
{ Code: 'ServiceError',
Message: 'Could not load file or assembly \'HtmlAgilityPack.NetCore, Version=1.5.0.1,
Culture=neutral, PublicKeyToken=null\' or one of its dependencies. 
A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)' } }

Error: Request to 
'https://webpoolbl....infra.lync.com/platformservice/tgt-f7d4f.../botframework/v3/conversations/YmMz.../activities/5' failed: [500] Internal Server Error
```

## System Information 
* SDK Language: Node js
* SDK Version: 3.8.4

**Comment by JasonSowers** [comment]
Please let us know if you are still having issues
