### ISSUE TITLE
[Question] Incorrect conversation creation parameters (CreateConversationAsync)

### ISSUE THREAD

**Issue by tomasherceg** [Microsoft/BotBuilder#3104]
## System Information (Required)
* SDK Language: C#
* SDK Version: Microsoft.Bot.Connector.Teams (0.5.6), Microsoft.Bot.Builder.Azure (3.2.2)
* Development Environment: Azure App Service

## Issue Description
I am getting the following error from the `CreateConversationAsync`:
```
Incorrect conversation creation parameters
```

The documentation says that the `teamsChannelId` and `teamsTeamId` parameters are obsolete, so I am using `channel`, `team` and `tenant` objects in the `channelData` object.

The workaround mentioned in #3061 didn't work for me, I have tried various combinations of parameters. 

## Code Example
```
            var channelData = new TeamsChannelData
            {
                Channel = new ChannelInfo(subscription.ChannelId),
                Team = new TeamInfo(subscription.TeamId),
                Tenant = new TenantInfo(subscription.TenantId)
            };

            var newMessage = Activity.CreateMessageActivity();
            newMessage.Type = ActivityTypes.Message;
            newMessage.Text = message.ToString();    // about 600 characters
            var conversationParams = new ConversationParameters(
                isGroup: true,
                bot: null,
                members: null,
                topicName: date.ToString("d. M. yyyy"),
                activity: (Activity)newMessage,
                channelData: channelData);

            var connector = new ConnectorClient(new Uri(subscription.ServiceUrl));
            var result = await connector.Conversations.CreateConversationAsync(conversationParams);
```

Can you advise what are the conditions for the `Incorrect conversation creation parameters` error?

**Comment by nrobert** [comment]
During my last tests 2 weeks ago, I couldn't create a conversation on MS Teams using the classic `CreateConversationAsync` of the framework but got to use a method from `Microsoft.Bot.Connector.Teams`, called `CreateOrGetDirectConversation`

The following code works to create a conversation:
```C#
// Connector init
MicrosoftAppCredentials.TrustServiceUrl(connectorClientUrl, DateTime.Now.AddDays(7));
var account = new MicrosoftAppCredentials(msAppId, msAppPassword);
var connector = new ConnectorClient(new Uri(connectorClientUrl), account);

// Conversation members init
ChannelAccount channelFrom = new ChannelAccount(fromId, fromName);
ChannelAccount channelTo = new ChannelAccount(recipientId, recipientName);

// Create Conversation
// Tenant ID can be found on https://portal.azure.com/#blade/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade/Properties
ConversationResourceResponse conversation = connector.Conversations.CreateOrGetDirectConversation(channelFrom, channelTo, myTenantID);
```

Then you can send a message to this conversation:
```C#
// Create message Activity and send it to Conversation
IMessageActivity newMessage = Activity.CreateMessageActivity();
newMessage.Type = ActivityTypes.Message;
newMessage.From = channelFrom;
newMessage.Recipient = channelTo;

newMessage.Locale = (locale ?? "fr-FR");
newMessage.ChannelId = channelId;
newMessage.Conversation = new ConversationAccount(id: conversation.Id);
newMessage.Text = message;

// Send 1st message to the conversation
var resp = await connector.Conversations.SendToConversationAsync((Activity)newMessage);
```

**Comment by tomasherceg** [comment]
Thank you. I don't know whether the `CreateOrGetDirectConversation` can be used when you need to post to a specific channel, but I got my code working by adding this:

```
MicrosoftAppCredentials.TrustServiceUrl(serviceUrl, DateTime.MaxValue);
```

Also, I have specified the app id and password in the constructor of `ConnectorClient` explicitly but I believe I don't have to as they are fetched from the configuration automatically.

**Comment by nrobert** [comment]
If you look at my code you will see that it's using a variable providing the channel yes.

Finally you didn't use it? Looks like what was missing in my old implementation is the channelData containing the tenantId in that case, thanks.
