### ISSUE TITLE
[Question] Can't get bot reply after posting on Slack

### ISSUE THREAD

**Issue by mahmoudahmedarafa** [Microsoft/BotBuilder#3105]
I published my bot from Visual Studio. I configured the app on Bot Framewrok Portal to be published on Slack. After I configured Slack configurations and submitted my credentials; when I try my app on slack I get no reply from the bot.

Here is the issues dialog from my app:
![capture](https://user-images.githubusercontent.com/22199398/27996259-7d097474-64de-11e7-8f4e-6953cb36d740.PNG)

**Comment by nrobert** [comment]
Looks like an error while you setup Slack configuration (or global configuration). Did you check if your bot is responding with the Tester?

**Comment by mahmoudahmedarafa** [comment]
You mean the below testing panel? I tried it and I got no reply. The bot works fine with localhost on my machine.
![capture](https://user-images.githubusercontent.com/22199398/28015789-e2afb412-6571-11e7-945b-b8be7df35d4d.PNG)

**Comment by nrobert** [comment]
Yes!

So you may have an error in your global settings. Can you check the `Settings` panel from this page, and tell us what you got in the `Messaging endpoint` under Configuration?

**Comment by mahmoudahmedarafa** [comment]
This is my message endpoint: https://mcdonaldsbot.azurewebsites.net/api/messages

**Comment by nwhitmont** [comment]
@mahmoudahmedarafa For reference, are you using .NET or Node SDK for BotBuilder?

**Comment by nrobert** [comment]
@mahmoudahmedarafa sorry no more idea with those elements, you should maybe try to deploy a simple echo bot first

**Comment by mahmoudahmedarafa** [comment]
@nwhitmont I am using .NET.

@nrobert Good idea. I will try this.

**Comment by mahmoudahmedarafa** [comment]
@nrobert I tried publishing [Echo Bot Sample]; It is published successfully but after integrating with Slack, I don't get a reply from the bot.
(https://github.com/Microsoft/BotBuilder/tree/master/CSharp/Samples/EchoBot)

**Comment by mahmoudahmedarafa** [comment]
Could anybody tell me how can I chat with the bot from Azure Portal, as it is already published on it before integrating the bot with some channel?

**Comment by nrobert** [comment]
Did you check if at least your Echo bot was responding with the tester?

**Comment by mahmoudahmedarafa** [comment]
Yes, but it didn't respond with the tester too.

**Comment by nrobert** [comment]
So try it with the emulator in local. Then:
 - if it's not working, correct it
 - if it's working, check your publish parameters
