### ISSUE TITLE
[WebChat Carousel] doesn't display right scroll button

### ISSUE THREAD

**Issue by GaiaAnn** [Microsoft/BotBuilder#3106]
## System Information (Required)
* SDK Language: .NET/C# 
* SDK Version: 3.8.2
* Development Environment: LOCALHOST

## Issue Description
I used the standard Bot Framework WebChat channel to get an IFRAME of mybot and embeded in my website.
This is my Carousel. It doesn't show the right button.

<img width="693" alt="2017-07-10 10 32 40" src="https://user-images.githubusercontent.com/17616235/28001222-9bcb466a-655d-11e7-8072-295faf6ed292.png">

So, I go to see iframe's code and I figure out the problem.
I change width to 500px then everything works fine.
But I can't modify iframe's code.

```` html
<!-- react-empty: 338 -->
<div class="wc-carousel" style="width: 500px;">
````

After I change the width it looks like this:

<img width="544" alt="2017-07-10 10 33 15" src="https://user-images.githubusercontent.com/17616235/28001345-6366e774-655e-11e7-96c1-8be8c63d76c2.png">

Hope anyone can help me to fix this problem.

**Comment by nrobert** [comment]
You should log this issue in the `BotFramework-WebChat` github project, located here https://github.com/Microsoft/BotFramework-WebChat, as this problem refers to the webchat part
