### ISSUE TITLE
[Question] How to create bot application using LUIS intents?

### ISSUE THREAD

**Issue by NehaShaikh786** [Microsoft/BotBuilder#3110]
## System Information (Required)
* SDK Language: C# 
* SDK Version: 4.6
* Development Environment:  OTHER 

## Issue Description
How to create an application using LUIS portal, please tell me how to define context of particular conversation flow.

## Code Example
   [LuisIntent("General")]
        public async Task okskin(IDialogContext context, LuisResult result)

        {
            await context.PostAsync("Welcome to my chat bot!");
            
            context.Wait(MessageReceived);
        }

## Steps to Reproduce the Issue
1.
2.
3.

## Expected Behavior
i want an example from which i can define a particular context of my flow. i need code example.

## Actual Results
i am using luis intents, so after hitting to luis intent i get a response which i have specified, i want a flow in context where i can consider the previous answers and can define the new one.

**Comment by JasonSowers** [comment]
[Here is a simple bot using LUIS](https://github.com/Microsoft/BotBuilder/tree/master/CSharp/Samples/Stock_Bot)  
  
[another sample LUIS bot](https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/intelligence-LUIS)

[General .NET documentation can be found here](https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-overview)

**Comment by sayyednazeer** [comment]
@NehaShaikh786 you have to make use of form flow to star doing the conversation.

**Comment by NehaShaikh786** [comment]
@JasonSowers Hi, thanks for your response. I have referred those links given by you.
I am trying to create a bot using LUIS intents and i need a conversation flow. How to implement a context flow from language understanding?
Actual Result- i have intent named as "moisturizer" and its utterance is "do you have moisturizer" but when i retrain the model and test "do you have abcd" it still hit the moisturizer intent, which i don't expect. I want this utterance to hit to "None" intent.
Expected- I have huge data in my model, after hitting to top score intent i am using dialog for further conversation (also adding to this do you have another solution except FormFlow and Dialog?). So i don't want my dialog to initiate when user enters the partial utterance as mentioned above. please provide some solution to this.

**Comment by NehaShaikh786** [comment]
@sayyednazeer i have referred the FormFlow examples, But by using FormFlow there is no Language Understanding. i am trying to use LUIS model. Right now i am facing problem with intent match.  for example-  i have intent named as "moisturizer" and its utterance is "do you have moisturizer" but when i retrain the model and test "do you have abcd" it still hit the moisturizer intent, which i don't expect. I want this utterance to hit to "None" intent.
