### ISSUE TITLE
[Question] Proactive Message from a Console App throws HTTP 403

### ISSUE THREAD

**Issue by McBacker** [Microsoft/BotBuilder#3111]
## System Information (Required)
* SDK Language: C#
* SDK Version: BotBuilder 3.8.4.0
* Development Environment: Local Console App

## Issue Description

I'm facing a HTTP 403 trying to send a proactive message from a console App.

The code was based on https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-proactive-messages

https://github.com/Microsoft/BotBuilder-Samples/blob/master/CSharp/core-proactiveMessages/simpleSendMessage/ConversationStarter.cs

Thank you

## Code Example
        static void SendProactiveMessage()
        {
            string toId = "*";
            string toName = "*";
            string fromId = "*";
            string fromName = "*";
            string serviceUrl = "https://telegram.botframework.com";
            string channelId = "telegram";
            string conversationId = "*";

	   // * All valid. Was taken from a log file with activity properties. -- Tried Facebook and WebChat channels also.

            var userAccount = new ChannelAccount(toId, toName);
            var botAccount = new ChannelAccount(fromId, fromName);
            var connector = new ConnectorClient(new Uri(serviceUrl));

            // Create a new message.
            IMessageActivity message = Activity.CreateMessageActivity();

            if (!string.IsNullOrEmpty(conversationId) && !string.IsNullOrEmpty(channelId))
            {
                // If conversation ID and channel ID was stored previously, use it.
                message.ChannelId = channelId;
            }
            else
            {
                // Conversation ID was not stored previously, so create a conversation. 
                // Note: If the user has an existing conversation in a channel, this will likely create a new conversation window.
                conversationId = (connector.Conversations.CreateDirectConversationAsync(botAccount, userAccount)).Result.Id;
            }

            // Set the address-related properties in the message and send the message.
            message.From = botAccount;
            message.Recipient = userAccount;
            message.Conversation = new ConversationAccount(id: conversationId);
            message.Text = "Hello, this is a notification";
            message.Locale = "pt-Br";
			
			// InnerException	{"O servidor remoto retornou um erro: (403) Proibido."}	System.Exception {System.Net.WebException}
            var result = connector.Conversations.SendToConversationAsync((Activity)message).Result;
        }

## Steps to Reproduce the Issue
1. Create a console App
2. Add BotBuilder NuGet package
3. Paste provided code and call the function

Maybe AppId and AppPassword are bot being provided to SDK? I have both in the app.config file, just like we do within a web.config.

## Expected Behavior
Message sent to the user.

## Actual Results
Throws 403 error at "var result = connector.Conversations.SendToConversationAsync((Activity)message).Result;"

**Comment by EricDahlvang** [comment]
Hi @McBacker 

Using your code in a console application against the **WebChat** channel will work if you supply MicrosoftAppCredentials to the ConnectorClient, and ensure the service url is trusted:

```cs
var connector = new ConnectorClient(new Uri(serviceUrl), new MicrosoftAppCredentials("YourAPPID", "YourAppPassword"));

MicrosoftAppCredentials.TrustServiceUrl(serviceUrl);
```

**Comment by McBacker** [comment]
Well, can't explain why but it works on an Azure WebJob but fails with 403 on my local machine.

Thank you for your help :)
