### ISSUE TITLE
[Question] "NewtonSoft JArray is not serializable" exception when using FormFlow from LUIS dialog

### ISSUE THREAD

**Issue by ChristianRiedl** [Microsoft/BotBuilder#3112]
SDK Language: C#
SDK Version: BotBuilder 3.8.4.0
Development Environment: ASP.Net Bot 

I am working on a prototype app where I invoke a **FormFlow** from a **LuisDialog**, similar to the **intelligence-LUIS**  sample.

When I initialize my form _lightform_ manually from the entities I get from LUIS it works  fine :

`var lightFormDialog = new FormDialog<LightForm>(lightForm, LightForm.BuildForm, FormOptions.PromptInStart, null);
`

But when I let **FormDialog** create the values from the LUIS result using the _result.Entities_ parameter  I get the exception **"NewtonSoft JArray is not serializable"**.

`var lightFormDialog = new FormDialog<LightForm>(lightForm, LightForm.BuildForm, FormOptions.PromptInStart, result.Entities);
`

Do you have an idea whats is going wrong ?

**Comment by ashicertis** [comment]
I had this same issue when I was trying to **map a date range with a date property** in my model. I was using pre-built date in LUIS which sometimes returned a range of date to me and I was mapping it to a single date property which caused the exception.

**Comment by ChristianRiedl** [comment]
My LUIS sample does not use date type entities.

**Comment by JasonSowers** [comment]
I've seen this when the JArray is empty, can you confirm it is not?

**Comment by ashicertis** [comment]
@ChristianRiedl To be clearer, my LuisResult had entity which were not mapped to my model properties. In your case if you view **LuisResult** object, check if any **EntityRecommendations are not mapped to your LightForm model properties**. Once I removed any extra properties, I was able to get rid of this exception.

**Comment by ChristianRiedl** [comment]
Thank you, this was the reason.

**Comment by ashicertis** [comment]
You are welcome  :-)
