### ISSUE TITLE
[Question] Multiple LUIS Services registered with Autofac use only one LUIS Model

### ISSUE THREAD

**Issue by BottDev** [Microsoft/BotBuilder#3114]
## System Information (Required)
* SDK Language:  .NET/C#
* SDK Version: 3.8.3
* Development Environment: LOCALHOST

## Issue Description
When register more than one LuisService with Autofac - Starting from 2nd message LuisDialog uses one model in both luis services

## Code Example
            var model1 = new LuisModelAttribute("model1", "");
            var model2 = new LuisModelAttribute("model2", "");

            builder.RegisterType<LuisService>()
                .WithParameter("model", model1)
                .Keyed<ILuisService>(FiberModule.Key_DoNotSerialize)
                .AsImplementedInterfaces()
                .SingleInstance();

            builder.RegisterType<LuisService>()
                .WithParameter("model", model2)
                .Keyed<ILuisService>(FiberModule.Key_DoNotSerialize)
                .AsImplementedInterfaces()
                .SingleInstance();

RootDialog is derived from LuisDialog

## Steps to Reproduce the Issue
1. Start conversation
2. Send message to bot
3. Send second message to bot

## Expected Behavior
LuisDialog contains two LuisServices that use two different Luis Models (model1 and model2)

## Actual Results
1st message LuisDialog uses two LuisServices with  two different Luis Models
Starting from 2nd message LuisDialog contains two LuisServices with the same Luis Model (latest registered)

**Comment by fanidamj** [comment]
Hoping that issue has been resolved, closing it. Feel free to reopen if any questions.
