### ISSUE TITLE
Issue with Prompts.choice: irrelevant string match if user provide choice as text instead of selecting it from the list of choices provided.

### ISSUE THREAD

**Issue by ncomo11** [Microsoft/BotBuilder#3115]
## System Information (Required)
* SDK Language: NodeJS
* SDK Version:  3.8.3
* Development Environment: Bot Service

## Issue Description
While prompting user a list of choices it allow user to either select an option from the list or enter a text value. I know most convenient is to select from the given choices by tab or click on it but if user want to select same option by typing it manually then bot framework return wrong selected values.
See below example:
Screenshot from attached sample nodeJS application->
![issue](https://user-images.githubusercontent.com/859748/28054168-8963ac4a-6631-11e7-95e5-f178b5048dcf.jpg)

It is weird but what I observed is that if there is any number in the text entered and it doesn't completely matches the provided choices it selects the option at that position. For example I entered cockpit 4 expecting it will match with 3rd option in the list but it actually returns 4th option.

I consider it as bug as its behavior is not documented and is not working as expected.

I have also created a sample/demo app to show case this issue and since above screenshot is from same app you can try out the example I have mentioned.

Download project from below link:
[Demo app at github](https://github.com/Microsoft/BotBuilder/files/1137894/package.zip)
[Demo app at onedrive](https://1drv.ms/f/s!AkRT15xJsa0UdY-Y5FPJ8QvY1aU)

## Code Example
Demo app uploaded at above location

## Steps to Reproduce the Issue
1. type anything
2. a list of choices will appear as in the screenshot at above link
3. type "cockpit 4"

## Expected Behavior
Expected bot return with the choice option matching string "cockpit 4"

## Actual Results
Bot return the wrong choice and in fact it return the option at 4th position instead of matching the complete text entered i.e. "cockpit 4"

**Comment by nrobert** [comment]
I already answered on StackOverflow ([here](https://stackoverflow.com/questions/45026921/issue-with-prompts-choice-irrelevant-string-match-if-user-provide-choice-as-tex)), it is the normal behaviour and you can:
- disable the recognition of ordinals
- or improve the score provided by `PromptRecognizers.findTopEntity(PromptRecognizers.recognizeChoices(utterance, choices, options));`

**Comment by ncomo11** [comment]
Thanks for you reply. Can you please help how can I disable the recognition of ordinals? FYI I am using Prompts.choice to display Choices to the user.

**Comment by nrobert** [comment]
I will let a node.js specialist answer. @nwhitmont  maybe?

**Comment by nsantini** [comment]
Here is how I sorted it.

```
const builder = require('botbuilder');
builder.Prompts.customize(builder.PromptType.choice, new builder.PromptChoice({minScore: 0.5}));
builder.Prompts.choice(...);
```

In my case I wanted to avoid getting answers with low score of certainty, so the prompt choice would ask me again. But you can use the same method to change any PromptChoiceFeature like "recognizeOrdinals"

**Comment by levotragiang** [comment]
@nsantini I've tried yours and it worked for me. Thanks so much!!! 👍

**Comment by vishmonne** [comment]
Hi,

Can u help me in how to disable the recognition ordinal bcz the solution provided by @nsantini  is not working for me.

The issue i am asking is , the prompt choice button (Yes|No) , sometimes when Yes is clicked its giving the correct response and sometimes its giving the other response

**Comment by levotragiang** [comment]
@vishmonne  
Hi there, 
If you want the answer to match exactly "yes" or "no", you should adjust minScore is 1, just like this:

```
const builder = require('botbuilder');
builder.Prompts.customize(builder.PromptType.choice, new builder.PromptChoice({ minScore: 1 }));
builder.Prompts.choice(session, "your question...", "yes|no");
```

Hope this helps :)

**Comment by vishmonne** [comment]
hi @levotragiang  i am giving the same thing above , still its like random , sometimes the bot goes to the function(session,results) and sometimes it goes to recognize the intent

**Comment by vishmonne** [comment]
@nrobert hi how to disable the recongnition of ordinal ?

**Comment by EricDahlvang** [comment]
@vishmonne 

```js
builder.Prompts.customize(builder.PromptType.choice, new builder.PromptChoice({ recognizeOrdinals: false }));

```

**Comment by vishmonne** [comment]
hi @EricDahlvang , i have given this is my code still the same problem exists, the prompt choice button is sometimes working and the other times its going to the default intent classifying ie its ending the dialog .
Can u help me with this ?

**Comment by EricDahlvang** [comment]
@vishmonne  Please ask a question on StackOverflow using the BotFramework tag: https://stackoverflow.com/questions/tagged/botframework  Be sure to provide the code you are using in the question.

**Comment by vishmonne** [comment]
hi all , 
can u help me out with this issue 

https://stackoverflow.com/questions/53279820/prompts-choice-button-result-is-not-working-as-expected-ex-sometimes-its-callin
