### ISSUE TITLE
Hey, how can I hidden password for Users when they input to chat channels

### ISSUE THREAD

**Issue by binhpht** [Microsoft/BotBuilder#3118]
## System Information (Required)
* SDK Language:  NODE OR .NET/C#
* Development Environment: Localhost

## Issue Description
I am struggling to find the method to make what password user input hidden.  Does anyone have experience or solution for this problem. 
Thanks.

**Comment by iMicknl** [comment]
Short answer; you can't. 

Are you using NodeJS or C#? If you want to authenticate the user you should do it using an external webservice via OAuth 2.0 for example. This is a safe authentication method which doesn't require the bot to save their passwords in plain text.

[BotAuth (NodeJS)](https://github.com/MicrosoftDX/botauth)
[AuthBot (C#)](https://github.com/MicrosoftDX/AuthBot)

**Comment by stevengum97** [comment]
This isn't supported at this time. As @iMicknl if you're looking to support logins you should use something like OAuth2.0. Those links posted are good starting points to implement OAuth in your chatbot.

Closing issue.
