### ISSUE TITLE
Send multiple Posts from LuisDialog

### ISSUE THREAD

**Issue by DavePilks** [Microsoft/BotBuilder#312]
I have a Form that I call from my `LuisDialog`. When the form is complete, I send multiple messages via `context.PostAsync`. When I do this in the emulator, it works fine. But when I try it through DirectLine it doesnt work.

**Comment by willportnoy** [comment]
Are your credentials stored in the app.config/web.config?  Do you see any errors?

**Comment by DavePilks** [comment]
@willportnoy All I get from the response is a generic 500.

**Comment by willportnoy** [comment]
Do you have a bot ID we can search the logs for?

**Comment by willportnoy** [comment]
I'm going to close this item for now, but feel free to re-open it for further discussion.
