### ISSUE TITLE
[Feature Request] Add Twitter channel integration

### ISSUE THREAD

**Issue by nwhitmont** [Microsoft/BotBuilder#3123]
This issue is to track requests for adding a Twitter channel integration to Bot Framework. Thumbs up this comment to vote.

**Comment by xjose97x** [comment]
When can we expect for Bot Framework to support Twitter.

**Comment by JasonSowers** [comment]
As of right now, we are gauging interest.  No ETA available.

**Comment by xjose97x** [comment]
@JasonSowers , from what I understand, Twitter currently has "Streams" (which is basically a way to **poll**  the twitter account activity)  and is soon going to support Webhooks (currently beta).

I understand API.AI already supports Twitter Channel, and I guess they do by using streams.

Perhaps you guys should wait for Twitter to fully support a webhook system?

**Comment by piffarettig** [comment]
Twitter has now private beta on Direct Messages: https://dev.twitter.com/rest/direct-messages.

Does this change anything?

**Comment by xjose97x** [comment]
Any update on this @nwhitmont @JasonSowers  ?

Thanks!

**Comment by JasonSowers** [comment]
Not at this time.

**Comment by tompaana** [comment]
Here's a workaround utilizing Direct Line: https://github.com/tompaana/twitter-bot-fw-integration

**Comment by ibrahimonat** [comment]
Is there any improvement in Bot Framework to support Twitter?

**Comment by JasonSowers** [comment]
Not at this time.

**Comment by marcasmar94** [comment]
Any updates to Twitter Channel?

**Comment by cleemullins** [comment]
The public BotBuilderCommunity has built a [Twitter Adapter](https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/tree/develop/libraries/Bot.Builder.Community.Adapters.Twitter).

**Comment by marcasmar94** [comment]
@cleemullins yes I have tried that and faced some issues [https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/issues/140#issue-482469100](url)
