### ISSUE TITLE
[Question] How to know the status of Skype user?

### ISSUE THREAD

**Issue by ersachit** [Microsoft/BotBuilder#3126]
I am working on a skype bot in node.js. I want to know the status of the user, if he is ideal for say 15 minutes, the bot should send him a message or check that if user status is online send him a message. Is there a way in bot framework?

**Comment by nwhitmont** [comment]
@ersachit Detecting Skype user's online status is not currently a feature of Bot Framework Node SDK. 

You could accomplish this by tracking your user's last activity time and send a proactive message after specified elapsed time without activity. 

For more information on proactive messages, check out the article:
- [Send proactive messages](https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-proactive-messages)
- Code example: https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node/core-proactiveMessages

**Comment by band888888** [comment]
There is the some qustion from my side.  We intergrate the bot into skype for business. When we send the proactive message in a certern time, how could know the user whether online or offlinke?

**Comment by band888888** [comment]
Hi @ersachit,  any way to solve this issue at the end?  
I faced the same  issue as well.  Business case is Send notification message to User with Skype. However, if the user offline we could not send the message. Hence, we would like to know the user status before we call the Proactive message API from the Bot to do the sending active.

Grateful if you could give me any suggestion or hits.
