### ISSUE TITLE
PromptDialog should allow ordered list.

### ISSUE THREAD

**Issue by brckelly** [Microsoft/BotBuilder#313]
PromptDialog should have a way to list numbers with text as the options. Right now it is hard coded with the * to just show a bullet list.  I want to give a user options and then they can select the number of the item.

1. Do first thing
2. Do second thing.
3. Do another thing.

When I tried to do PromptDialog.Choice<string>() with an IEnumerable that had "1." in front of all the string, the Bot Emulator crashed.

**Comment by tkbox9** [comment]
Yet on PromptDialog topic. I'm trying to use a  PromptDialog.Confirm from a LuisIntent. However, once user press yes or no, I don't get any confirmation and instead of getting into ResumeAfter<bool> (AfterConfirming_Search) somehow user response is picked by another intent. 

```
    [LuisIntent("find.something")]
        public async Task FindSomething(IDialogContext context, LuisResult result)
        {
            PromptDialog.Confirm(context, AfterConfirming_Search, "Okay, let me see if I get it. You're looking for : " + string.Join(", ", result.Entities.Select(i => i.Entity)));
        }
```
```

       private async Task AfterConfirming_Search(IDialogContext context, IAwaitable<bool> confirmation)
        {
           //Never called.
            if (await confirmation)
            {
            }
          context.Wait(MessageReceived);
       }

```

**Comment by chrimc62** [comment]
I think you have multiple issues here.  As to the format, have you specified the PromptStyle?  By default it is Auto which will generate buttons--which are rendered differently depending on the channel and on the emulator are rendered using *.  If what you want is entirely text, change it to AutoText and it will render on all channels as purely text and it will look more like what you want,

**Comment by msft-shahins** [comment]
@tkbox9 I guess you have another issue in some other parts of your code that causes problems with the dialog stack management and it is not related to PromptDialog.Confirm(...). If you look at [simple alarm bot](https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Samples/SimpleAlarmBot/SimpleAlarmDialog.cs) sample, it is implementing almost the same logic. 

```Csharp
        [LuisIntent("builtin.intent.alarm.turn_off_alarm")]
        public async Task TurnOffAlarm(IDialogContext context, LuisResult result)
        {
            if (TryFindAlarm(result, out this.turnOff))
            {
                PromptDialog.Confirm(context, AfterConfirming_TurnOffAlarm, "Are you sure?");
            }
            else
            {
                await context.PostAsync("did not find alarm");
                context.Wait(MessageReceived);
            }
        }

        public async Task AfterConfirming_TurnOffAlarm(IDialogContext context, IAwaitable<bool> confirmation)
        {
            if (await confirmation)
            {
                this.alarmByWhat.Remove(this.turnOff.What);
                await context.PostAsync($"Ok, alarm {this.turnOff} disabled.");
            }
            else
            {
                await context.PostAsync("Ok! We haven't modified your alarms!");
            }

            context.Wait(MessageReceived);
        }
```

@brckelly, as @chrimc62 mentioned, we added button support in nuget 1.2 and ability for you to change the prompt style generation by changing the prompt style type. You can implement your own prompt styler to generate ordered list from your choices. Here is an example of an ordered list styler: 

```csharp
        [Serializable]
        public class OrderedListPromptStyler : PromptStyler
        {
            public override void Apply<T>(ref Message message, string prompt, IList<T> options)
            {
                var builder = new StringBuilder();
                var pos = 0;
                foreach (var elt in options)
                {
                    builder.Append($"{++pos}. {elt.ToString()}\n");
                }
                message.Text = $"{prompt}\n{builder.ToString()}";
            }
        }
```

We have a bug in the markdown parser of emulator that causes a wrong xaml get generated for the following markdown (* 1. yes\n* 2. no\n). That is the source of emulator crash, we are trying to solve that.

**Comment by tkbox9** [comment]
@msft-shahins and everyone that might have the same problem using             PromptDialog.Confirm(context, OnConfirming, "Okay?").  (read above)

I could never get a continuation (ResumeAfter<bool> PromptDialog.Confirm) to be called after a Yes/No answer from the user because Luis was understanding Yes or No as an intent. So in order to solve my problem I had to train LUIS to not understand yes/no as an intent. 

I hope that can help someone with the same problem.

**Comment by msft-shahins** [comment]
@tkbox9 this shouldn't be the case. When you are initiating a confirmation dialog in your intent handler by calling `PromptDialog.Confirm`, the underlying dialog system will create a new instance of `PromptConfirm` and push it on the stack. From this point, all the messages will be forwarded to the dialog on top of the stack which is `PromptConfirm`. Upon completion of `PromptConfirm` dialog, your LuisDialog will be resumed and the ResumeAfter function will be called with the result of `PromptConfirm` dialog. No code path will call into the Luis service unless your code is causing dialog stack corruption.

**Comment by tkbox9** [comment]
@msft-shahins indeed I have the expected behavior from the emulator. However, when the bot is live on facebook channel that problem happens. Also, something really odd I've just noticed sometimes even when a new published bot version is pushed to Azure. (It seems there're some sort of cache on the facebook channel that doesn't present the same behavior as the emulator). - Specially when recovering from an error (from the last version).

Have anyone experienced anything liked? I'm investigating in order to reproduce it but at this point its only assumptions.
