### ISSUE TITLE
[Question] Character codes (locale) for text in Skype for Business Bot

### ISSUE THREAD

**Issue by dirugadr** [Microsoft/BotBuilder#3133]
## System Information (Required)
* SDK Language: C#
* SDK Version: 3.8
* Development Environment: LOCALHOST

## Issue Description
I'm developing a Bot for a Brazilian customer. I've been translating all text to this language, and it seems it's done. I deployed the bot to be used as a web chat, using direct line, and it's running fine. Last days I was working to have it running on SFB, and today I finally complete it. However, I found some issues with "special" characters (from the brazilian alphabet), and I'm unable to fix it.

I mean, by instance, instead of showing "Não está cadastrado seu e-mail." it's showing "N?o est? cadastrado seu e-mail." If I use Web Chat or Skype as channel, the text is displayed property. 

This issue happens also with spanish.

## Image Examples
[Web chat image](https://i.stack.imgur.com/gpmbb.png)
[SFB Chat](https://i.stack.imgur.com/ywdkE.png)

**Comment by dirugadr** [comment]
Hello again,
I'm wondering if you guys solved the problem. Today I started over my testing with my brazilian customer, and I could see that all "strange" characters now are being displayed properly. Maybe the Skype team did it? Anyway, thank you very much!

**Comment by nwhitmont** [comment]
@dirugadr Thanks for the update!
