### ISSUE TITLE
[Question] Empty member names in Skype group chat

### ISSUE THREAD

**Issue by hdiniz** [Microsoft/BotBuilder#3135]
I am trying to get the member list for a Skype group chat where my bot was added, but the **name** of the members is empty.

When my bot is mentioned, I am using the REST API:

`https://smba.trafficmanager.net/apis/v3/conversations/${conversationId}/members`

And always get the correct number of members and their IDs, but no names...
```js
[  
  {  
    "id":"29:XXXX",
    "name":""
  },
  {  
    "id":"29:YYYY",
    "name":""
  },
  {  
    "id":"29:ZZZZ",
    "name":""
  }
]
```

**Comment by nwhitmont** [comment]
@hdiniz For reference, are you using .NET or Node SDK?

**Comment by hdiniz** [comment]
I am using the Node SDK

**Comment by nwhitmont** [comment]
@hdiniz For reference, what is your bot name, bot handle and App ID as you registered in the Bot Portal at https://dev.botframework.com?

**Comment by nwhitmont** [comment]
@hdiniz I have consulted with the Skype Platform team, and unfortunately, the Skype API does not actually support returning the usernames via this API method, thus the empty fields.

**Comment by hdiniz** [comment]
@nwhitmont thanks for the feedback. That is not a must for what I was planning, but hopefully in the future they can support it.
Best regards
