### ISSUE TITLE
[Question] Dynamic bot code generation? (Form Flow and Root Dialog)

### ISSUE THREAD

**Issue by sayyednazeer** [Microsoft/BotBuilder#3136]
## System Information (Required)
* SDK Language: NET/C# 

* Development Environment:AZURE_BOT_SERVICE

## Question Description

Can we make the bot fully dynamic ... Means without writing any code just there should be a frontend where i can set what are the conversation... Wt are flows etc...

Lets say for example if i had made a bot who will talk about PUMA or NIKE brand .... For both of this i have to create a rootdialoge... Bcz both of there conversations and flow where different...

Now if i want my bot to start talking about ADIDAS brand also.... Then for that i have to manually create a rootdialoge and then i have to manually create the form flow and write some overe there for questioning... So is there any way where i can manipulate this manually creating class and form flow and root dialog with some UI so if in future i want my bot to give the service for ADIDAS OR any other new brand then instead of writing the code ill just go to my UI and do my job from there.... Decide there how the form flow will be or what conversation should be there....

Any body have done like this or have any workaround for this..?

**Comment by megancooper** [comment]
Maybe you could utilize LUIS? Create separate Intents and have ADIDAS, PUMA, NIKE, etc... map to one Enitity like "ShoeBrand". Then in your code simply search for the entity and respond based on which brand the entity held?

**Comment by JasonSowers** [comment]
You could also look into scorables [here is a great video explaining the concept](https://www.youtube.com/watch?v=hnU3lPHhv88)

**Comment by sayyednazeer** [comment]
@megancooper actually i am talking about the code section... Since there are multiple brand so do i have to write the code for each brand .... Is there any seamless way..?

**Comment by sayyednazeer** [comment]
any help.. ??

**Comment by nwhitmont** [comment]
@sayyednazeer you would need to code a custom solution for this feature. feel free to submit a PR with the desired functionality. Contributions welcome!
