### ISSUE TITLE
[Question] Get channel name on MS Teams channel?

### ISSUE THREAD

**Issue by bilby91** [Microsoft/BotBuilder#3137]
## System Information (Required)
* SDK Language: NODE
* SDK Version: 3.8.4
* Development Environment: LOCALHOST

## Issue Description
Is it possible to get the channel name when the bot is interacting in a channel inside MS Teams ? Slack sends the name attribute of the channel in the conversation object inside address. I was expecting the same for MS Teams. If information is not sent on message activities, is it possible to get it in another way ?

Thanks!

**Comment by bilby91** [comment]
For example, when I delete a channel inside my team, I get a `channelDeleted` conversationUpdate event that includes the information in the sourceEvent object. 

```
  sourceEvent:
   { channel:
      { id: '19:XXXX@thread.skype',
        name: 'testing' },
     team: { id: '19:ZZZZ@thread.skype' },
     eventType: 'channelDeleted',
     tenant: { id: 'XXXXXXXX' } },
``` 

For message activities, the name key is removed from the sourceEvent.

**Comment by bilby91** [comment]
I was able to get all the channels with their name using `/v3/teams/:team_id/conversations`. I was wondering if it does make sense to add it in the conversation object the same way Slack does.

**Comment by nwhitmont** [comment]
@bilby91 Thanks for the update, glad you found the solution. 

Contributions are always welcome! If you have an idea or feature request, don't hesitate to submit a pull request with desired functionality.

**Comment by AkshatTR** [comment]
Hi @bilby91, would you mind explaining the HTTP call as in how did you get all channel names with Team ID? I am trying to build a messaging extension and if I try to fetch all channel list it throws error saying  "The bot is not part of a conversation roaster". @nwhitmont
