### ISSUE TITLE
Message with attachment & Facebook

### ISSUE THREAD

**Issue by DrNixx** [Microsoft/BotBuilder#314]
A message with an attachment incorrectly display in Facebook messenger.
For example message
`{
  "conversationId": "8a684db8",
  "language": "en",
  "text": "Test image attachment.",
  "attachments": [
    {
      "contentType": "image",
      "contentUrl": "http://aka.ms/Fo983c"
    }
  ]
  ...
}`
will be display two message with picture, but not display "Test image attachment." text.

The same case happens with cards...

PS Also Facebook require ContentType **image**, not **image/png**, It would be good to bring it to a single mind at the connector level

**Comment by v-thgratMSGit** [comment]
@tomlm Any thoughts?

**Comment by tomlm** [comment]
the facebook connector was completely rewritten for V3, this should work.

**Comment by v-thgratMSGit** [comment]
Thanks for closing!
