### ISSUE TITLE
[Question] Images not showing sometimes in WebChat?

### ISSUE THREAD

**Issue by reddy12345678** [Microsoft/BotBuilder#3141]
images are showing as blank only some times

**Comment by nrobert** [comment]
It will be difficult to provide any help with such an empty issue description.

Please edit your initial message, add relevant information (use the template) to bring more details about your problem.

**Comment by reddy12345678** [comment]
Please find below screens.. some times images not displaying properyl in webchat
![1](https://user-images.githubusercontent.com/28974785/28271322-d7651700-6b25-11e7-8f7b-a7cc266f9b87.jpg)
<img width="223" alt="2" src="https://user-images.githubusercontent.com/28974785/28271323-d779d50a-6b25-11e7-9ea4-c28ff9ddddea.png">

**Comment by reddy12345678** [comment]
Please find below screens.. images are not displaying some times in webchat only
Screen 1: Step1 image is not displaying
Screen 2: step 2 image is not displaying (bot screens same questions)

![1](https://user-images.githubusercontent.com/28974785/28271694-ed6cbe76-6b26-11e7-8874-0b16af52a88f.jpg)
<img width="223" alt="2" src="https://user-images.githubusercontent.com/28974785/28271693-ed671aac-6b26-11e7-9aeb-5cadbb68dedf.png">

**Comment by nwhitmont** [comment]
@reddy12345678 What are the URLs to the images that display vs not display? Are they `https`?

**Comment by reddy12345678** [comment]
i am showing only byte array image.. i think http or https not an issue because same sometimes appearing some times not apperaing

**Comment by EricDahlvang** [comment]
When are these images appearing, and when are they not appearing?  Is the server the images are hosted on down while they are not appearing?
