### ISSUE TITLE
[Question] Can we get the callback if user edit/delete any message or disable options?

### ISSUE THREAD

**Issue by ersachit** [Microsoft/BotBuilder#3142]
Hi @nwhitmont, I am working on a skype bot in node.js. 
1. I want to know that can we get the callback if the user deletes/edit any message from the chat. 
2. Also, on the other side- can we disable menu option from chat so that if the user is communicating with bot, can't do operations on it?

**Comment by nwhitmont** [comment]
@ersachit 
1. No, this is not currently a feature
2. I don't understand your question. Please provide more details.

**Comment by ersachit** [comment]
#2. I mean when we right click on our messages, we see some options like edit, delete etc. Can we disabled that event (right click event) in the case of bot?

**Comment by nwhitmont** [comment]
@ersachit No, that would be in the client that renders the message, which Bot Framework does not have control over.
