### ISSUE TITLE
[Question] Why FormBuilder throws exception when passed IDialogContext as a parameter to Formbuilder IForm<> static method ?

### ISSUE THREAD

**Issue by AmolPawarGitHub** [Microsoft/BotBuilder#3143]
## System Information (Required)
* SDK Language: C#
* SDK Version: 3.8.1.0
* Development Environment: LOCALHOST, VS 2015, EMULATOR

## Issue Description

Why FormBuilder throws an exception when passed IDialogContext as a parameter to Formbuilder IForm<> static method? I get below error,

> Exception: anonymous method closures that capture the environment are not serializable, consider removing environment capture or using a reflection serialization surrogate: FlightBot.FlightManager+<>c__DisplayClass2_0", "attachments": [ { "contentType": "text/plain", "content": " at Microsoft.Bot.Builder.Internals.Fibers.Serialization.ClosureCaptureErrorSurrogate.System.Runtime.Serialization.ISerializationSurrogate.GetObjectData(Object obj, SerializationInfo info, StreamingContext context)

## Code Example 
Note : You can copy complete code and try to reproduce the issue.
```cs
namespace FlightBot
{
[BotAuthentication]
public class MessagesController : ApiController
{
    internal static IDialog<object> MakeRootDialog()
    {
        return Chain.From(() => new FlightManager());
    }

    public async Task<HttpResponseMessage> Post([FromBody]Activity activity)
    {
        if (activity.Type == ActivityTypes.Message)
        {
            await Conversation.SendAsync(activity, MakeRootDialog);
        }
        else
        {
            HandleSystemMessage(activity);
        }
        var response = Request.CreateResponse(HttpStatusCode.OK);
        return response;
    }

    private Activity HandleSystemMessage(Activity message)
    {
        if (message.Type == ActivityTypes.DeleteUserData)
        {
            // Implement user deletion here
            // If we handle user deletion, return a real message
        }
        else if (message.Type == ActivityTypes.ConversationUpdate)
        {
            // Handle conversation state changes, like members being added and removed
            // Use Activity.MembersAdded and Activity.MembersRemoved and Activity.Action for info
            // Not available in all channels
        }
        else if (message.Type == ActivityTypes.ContactRelationUpdate)
        {
            // Handle add/remove from contact lists
            // Activity.From + Activity.Action represent what happened
        }
        else if (message.Type == ActivityTypes.Typing)
        {
            // Handle knowing tha the user is typing
        }
        else if (message.Type == ActivityTypes.Ping)
        {
        }

        return null;
    }
}
}
```

```cs
namespace FlightBot
{
    [LuisModel("luis model key", "luis secret")] 
    [Serializable]
    public class FlightManager : LuisDialog<object>
    {
        public async Task FlightBookingTask(IDialogContext context, LuisResult result)
        {
            PromptDialog.Confirm(
                context: context,
                resume: ResumeAndHandleConfirmAsync,
                prompt: $"It seems you wish to book a flight. Do you wish to continue?",
                retry: "I didn't understand. Please try again.");
        }

        private async Task ResumeAndHandleConfirmAsync(IDialogContext context, IAwaitable<bool> argument)
        {
            FlightBooking cb = new FlightBooking();
            BuildFormDelegate<FlightBooking> MakeFlightBookingForm = () => FlightBooking.BuildForm(context);
            var flightBooking = new FormDialog<FlightBooking>(cb, MakeFlightBookingForm, FormOptions.PromptInStart, null);
            context.Call(flightBooking, FlightBookingComplete);
        }

        private async Task FlightBookingComplete(IDialogContext context, IAwaitable<FlightBooking> result)
        {
            context.Wait(MessageReceived);
        }
    }
}
```

```cs
namespace FlightBot
{
    [Serializable]
    public class FlightBooking
    {
        [Prompt("Enter source :")]
        public string Source { get; set; }

        [Prompt("Enter destination :")]
        public string Destination { get; set; }

        public static IForm<FlightBooking> BuildForm(IDialogContext context)
        {
            return new FormBuilder<FlightBooking>().Message("Tell me about flight details!")
           .Field(nameof(Source))
           .Field(nameof(Destination))
           .Build();

        }
    }
}
```

## Steps to Reproduce the Issue
1.The above code is a complete code of my application, You can copy it as it is.
2.If you try to run the code in the emulator, it will throw an error.

## Expected Behavior
I should get to use context object without any exception so that I can use UserData to save my additional data which is fetched from SQL DB

**Comment by JasonSowers** [comment]
Can you explain your use case a bit?  What exactly are you trying to accomplish?

**Comment by AmolPawarGitHub** [comment]
Sure, Currently we have a web application which we are trying to convert it into BOT. We have a web form in which we have 3 dropdowns and every succeeding dropdown data is dependant on the previous dropdown selection and all those dropdown data is coming from SQL DB. 

From the first dropdown, I get List<Class> which I am going to bind it to the second dropdown, so I want to store that List<Class>to somewhere so that I can use it in  .SetDefine((state, field) =>{}) method of the field for binding.
So is there a way I can store the data in UserData inside fromBuilder.

I hope you got my point.

**Comment by fanidamj** [comment]
Hoping that issue has been resolved, closing it. Feel free to reopen if any questions.

**Comment by waqas-zia-confiz** [comment]
Did you get a solution for this problem?
