### ISSUE TITLE
[Question] Use Invoke buttons in MS Teams and Slack?

### ISSUE THREAD

**Issue by santiagodoldan** [Microsoft/BotBuilder#3144]
## System Information
* SDK Language: NODE
* SDK Version: 3.8.4
* Development Environment: LOCALHOST

## Issue Description
I'm building a menu with buttons to let users configure their bot easily (this needs to work only in teams and slack), the problem I'm facing is that `postBack` isn't supported in MS Teams, so I'm playing with the new `invoke` stuff, but it looks like there isn't an implementation in Node yet, so I modified the CardAction class to play with it for now 👉  https://github.com/suttna/BotBuilder/commit/b1bef0aaf827c4834ad0dba993ccde8e3bc366c3

In MS Teams works ok, but when I use the same message structure in a Slack channel, Slack does not render buttons, it looks like it tries to render a link but it shows plain text (there's an attachment below).

## Code Example
```
// This is using the new function I added in the above GH link
const buttons = [builder.CardAction.invoke(session, 'apple', 'apple'),
                             builder.CardAction.invoke(session, 'orange', 'orange')]

const attachment = new builder.HeroCard(session)
  .title(message).buttons(buttons)

session.send(new builder.Message(session).addAttachment(attachment))
```

## Expected Behavior
Being able to use invoke buttons in Slack.

## Actual Results
<img width="403" alt="screen shot 2017-07-17 at 10 50 32 am" src="https://user-images.githubusercontent.com/1096526/28271171-338946de-6ade-11e7-9c82-86c8e3c836fd.png">

![screen shot 2017-07-17 at 10 50 54 am](https://user-images.githubusercontent.com/1096526/28271172-338cee4c-6ade-11e7-8aea-9bfa9c82ae2b.png)

**Comment by nwhitmont** [comment]
@santiagodoldan The "invoke" action is specific to MS Teams. It can't be used on Slack.

**Comment by santiagodoldan** [comment]
Thanks for the quick response 😃 

I'm now thinking that maybe I can use `dialogAction` for Slack and `invoke` for MS Teams.

What it would be ideal is to receive the `invoke` event in the same dialog/step as the `dialogAction` does.

Not sure if that's possible and if that would be an expected behavior, I can try to adapt the ChatConnector and see if I can route those events to the correct dialog/step, maybe I can start here https://github.com/suttna/BotBuilder/blob/master/Node/core/lib/bots/ChatConnector.js#L411

What do you think @nwhitmont ?

**Comment by nwhitmont** [comment]
@santiagodoldan Did you try using `imBack`?

**Comment by santiagodoldan** [comment]
It looks like it works ok, the router detects correctly the waterfall step where the button was added. here you have again my WIP https://github.com/suttna/BotBuilder/commit/2b1ad4da19ce967c99ada4388cd475620d3311ba

Not sure what's the best way to allow us to do this, maybe passing a specific key to the invoke JSON payload? like `{ "respondBackToWaterfallStep": true }`, if that key isn't available the bot executes the `onInvoke` global callback.

IMO this is super helpful as `dialogAction` and `invoke` can be handled easier and the best part is that the callback of both events will happen in the same context (waterfall step).

**Comment by santiagodoldan** [comment]
@nwhitmont yeah, but i don't like how it works in MS Teams, I'd prefer to not show a message when they click the button, also in Slack the message does not appear

**Comment by santiagodoldan** [comment]
Also, this will allow to use buttons for things like `Prompts.confirm` in ms teams, right?

**Comment by JasonSowers** [comment]
posting the [documentation here](https://msdn.microsoft.com/en-us/microsoft-teams/botsmessages) in case anyone comes accros this issue searching

**Comment by bilby91** [comment]
Any update on this ?

**Comment by nwhitmont** [comment]
@bilby91 what do you mean?

**Comment by nwhitmont** [comment]
@santiagodoldan Back to your original question -- The equivalent of MS Teams "invoke" action in Slack is "postBack".

**Comment by santiagodoldan** [comment]
Are there any plans to route invoke messages to the dialog that added the buttons? like how postBack behaves, you can see what I had to change to get that result, if that's ok, I can work on a better solution to allow devs to get invoke callbacks, maybe passing a parameter like `postBack` and if that flag is true, we can route the invoke message to the correct dialog.

**Comment by nwhitmont** [comment]
@santiagodoldan I'm not aware of any plans to route messages to the dialog that added the buttons. 

If you have a proposal for a feature enhancement, feel free to submit a PR with that functionality for review.
