### ISSUE TITLE
[Question] Cortana does not speak response from bot?

### ISSUE THREAD

**Issue by anarchitect** [Microsoft/BotBuilder#3145]
Hi, on Windows 10, when speak to Cortana using mic, it will speak out the response text.  However, after we configure Cortana channel for a bot as a Cortana skill in dev.botframework.com, when we talk to Cortana, it doesn't speak out the response from the skill.   This is inconsistent Cortana behavior, can you please enable the speak out function in Cortana for a skill? 
I understand I can code in MS Bot Framework to let Cortana speak, but i think it should be smarter. 
Also, with bots from api.ai (MS bot handle "CarRego"), I cannot put code in api.ai to let Cortana speak out the response.

**Comment by nwhitmont** [comment]
@anarchitect Are you using .NET or Node SDK?  

Please provide your code that reproduces the issue.

**Comment by anarchitect** [comment]
Any code, node.js , c#, ported from API.ai.  As an example , you can created a basic bot , ported to Cortana straight away , and it won't speak

**Comment by nwhitmont** [comment]
@anarchitect Please post your code so we can better assist you.

**Comment by anarchitect** [comment]
Will post it tonight, but this is to do with a Cortana channel in general. The should read out the bot response in general.  Also, the code I will post is the same as a Azure bot  Service provisioned out of box.

**Comment by jsiegmund** [comment]
Is the code setting the Speak property on the return message? There's  a Text and a Speak property to set text. The Text property will be displayed, the contents of the Speak property will be spoken by Cortana. If you only set the first one, she will not speak. Bear in mind that this tech is moving fast so samples you use might not have these properties included yet.

**Comment by anarchitect** [comment]
Here is a out of box Azure Bot with QnA template. 
In run.csx . 
` case ActivityTypes.Message:
                    await Conversation.SendAsync(activity, () => new BasicQnAMakerDialog());
                    break;
                case ActivityTypes.ConversationUpdate:
                    var client = new ConnectorClient(new Uri(activity.ServiceUrl));
                    IConversationUpdateActivity update = activity;
                    if (update.MembersAdded.Any())
                    {
                        var reply = activity.CreateReply();
                        var newMembers = update.MembersAdded?.Where(t => t.Id != activity.Recipient.Id);
                        foreach (var newMember in newMembers)
                        {
                            reply.Text = "Welcome";
                            if (!string.IsNullOrEmpty(newMember.Name))
                            {
                                reply.Text += $" {newMember.Name}";
                            }
                            reply.Text += "!";
                            await client.Conversations.ReplyToActivityAsync(reply);
                        }
                    }
                    break;
                case ActivityTypes.ContactRelationUpdate:
                case ActivityTypes.Typing:
                case ActivityTypes.DeleteUserData:
                case ActivityTypes.Ping:
                default:
                    log.Error($"Unknown activity type ignored: {activity.GetActivityType()}");
                    break;
            }
        }
        return req.CreateResponse(HttpStatusCode.Accepted);
    }`

in BasicQnAMakerDialog:
'[Serializable]
public class BasicQnAMakerDialog : QnAMakerDialog
{
    // Go to https://qnamaker.ai and feed data, train & publish your QnA Knowledgebase.
    public BasicQnAMakerDialog() : base(new QnAMakerService(new QnAMakerAttribute(Utils.GetAppSetting("QnASubscriptionKey"), Utils.GetAppSetting("QnAKnowledgebaseId"))))
    {
    }
}'

**Comment by JasonSowers** [comment]
Intentionally, there are 2 different ways for Cortana to send information, audio and visual.  In many situations, you would want to display information differently than you would like to speak information.  This may not come across in the simple example (like a QnA Bot) in which the response is just text that could be read or spoken without any noticeable difference.  There are however many situations in which one would not want these to be the same.  Therefore the speak and text properties exist to account for this.

**Comment by anarchitect** [comment]
@jasonsowers. Yes, I have done speak and display differently for one of my QnA bots. As u mentioned, there are two possibilities. What I am saying is the default should be speaking out, because that is how Cortana behave in other case, such as "hey Cortana, how are you?"

**Comment by anarchitect** [comment]
Also, can you please suggest how many characters or words limit Cortana can speak out? As I think some of  response keep hitting error reading out, and it seems to do with the length of the response.

**Comment by anarchitect** [comment]
It seems the number of Characters or words Cortana can speak on Windows 10 has a limit, below is a paragraph static and it will error saying "Sorry, I can't support that action on this version of Windows. Updating should help. Try asking me about the Windows 10 Creators Update.".  However, Cortana on iOS is working ok.
![word counts](https://user-images.githubusercontent.com/2878492/28369767-e0117d32-6cdb-11e7-9292-2b35596623c5.png)

**Comment by nwhitmont** [comment]
On the [Cortana FAQ page](https://docs.microsoft.com/en-us/cortana/skills-faq) it mentions that responses are limited to 90 seconds, but there isn't a specific mention of character count. 

>Q: How long can Cortana's speech response be?

>A: Cortana can respond with a maximium of 90 seconds of speech. This can be any combination of text, SSML (with or without embedded audio).

Also, for reference, are you running Windows Creators Update?

**Comment by anarchitect** [comment]
Hi @nwhitmont , I reported this as a new issue. https://github.com/Microsoft/BotBuilder/issues/3178. There is an example in it, it doesn't speak long enough for 90 seconds for sure as you tell from code example. it is the number of words matters. I am running a corporate custom build of Windows Enterprise, how can i tell whether it is a WIndows Creators update?

**Comment by nwhitmont** [comment]
See: https://docs.microsoft.com/en-us/cortana/testing/known-issues

## Cortana stops talking after 15 seconds or displays the message "Unfortunately this skill won't work on this version of Windows"

>Cortana in the Windows 10 Anniversary update (version 1607) is limited to 15 seconds of audio. This has been resolved in the Windows 10 Creators update (version 1703). A workaround for Bot Framework-based skills is to break your response up into multiple responses and to return multiple responses to the user.

**Comment by nwhitmont** [comment]
relates to https://github.com/Microsoft/BotBuilder/issues/3178
