### ISSUE TITLE
[Question] Loading Bot using DirectLine in SharePoint - builder.prompts.choice button refresh issue

### ISSUE THREAD

**Issue by winks3** [Microsoft/BotBuilder#3146]
When loading my bot using BotChat.js directline connection to Bot Framework inside of a SharePoint page, any builder.prompts.choice options that contain builder.liststyle.button will cause a page refresh if a user clicks that option.

HTML Button returned from BotChat.js DirectLine channel:

<button class="ac-pushButton" style="overflow: hidden; white-space: nowrap; text-overflow: ellipsis; flex: 0 1 auto;">Test Button</button>

This appears to be down to the HTML button being returned to the user not having a type="button" attribute.

How could I go about loading this attribute in to buttons that are displayed in the Bot Chat?

**Comment by nwhitmont** [comment]
@winks3 Are you using .NET or Node SDK?

**Comment by nwhitmont** [comment]
@winks3 Please post a code example that reproduces this issue so we can better assist you.

**Comment by winks3** [comment]
Sorry for not being clearer @nwhitmont 

I am using the Node SDK for my bot.

I am using BotFramework-WebChat (https://unpkg.com/botframework-webchat@0.11.0/botchat.js) for my DirectLine connection. 

Any button that appears in my webchat window will refresh the page. A button could be initiated by the following code:

```
signInCard = new builder.SigninCard(session)
                .text(actionLabel)
                .button(buttonLabel, authorizationUrl);
```

However, any button that is built in the bot app.js (Node SDK) is returned without type="button". Example: 

` builder.Prompts.choice(session, "Please select the person you are looking for ...", peopleNames, { listStyle: 2 });`

Rendered button HTML:

`<button class="ac-pushButton" style="overflow: hidden; white-space: nowrap; text-overflow: ellipsis; flex: 0 1 auto;">Test Button</button>`

I will try to compile an example package that best demonstrates this issue, if the above is not enough

**Comment by nwhitmont** [comment]
@winks3 Not sure where you are getting `{ listStyle: 2}` (?).

Instead, use:
`{ listStyle: builder.ListStyle.button}`

**Comment by nwhitmont** [comment]
possibly related: https://support.office.com/en-us/article/Allow-or-restrict-the-ability-to-embed-content-on-SharePoint-pages-e7baf83f-09d0-4bd1-9058-4aa483ee137b?ui=en-US&rs=en-US&ad=US

**Comment by nwhitmont** [comment]
@winks3 what browser/version are you using when you experience the error?

**Comment by EricDahlvang** [comment]
@winks3 How are you hosting botchat.js in the sharepoint page?  (iframing the bot in an embed web part works without issue)

**Comment by nwhitmont** [comment]
One thing to try - "Inspect" the button HTML using browser dev tools, and paste in the `type="button"` attribute to the `<button>` tag, then see if the issue persists.

**Comment by winks3** [comment]
@nwhitmont I did actually try this first of all and this rectifies the problem. As soon as I add the type="button" attribute in to Chrome everything works correctly. 

I am referencing a two JS files inside of a SharePoint page layout - file 1 is the unpkg.com botchat.js and file 2 is common.js. Inside of common.js is the following piece of code:

```
var cookieConvId = readCookie('convId');
var botConnection;

if(cookieConvId == null)
{
    botConnection = new BotChat.DirectLine({
        secret: 'XXXXXXXXXXXXXXXXXXXXXX'
    });
}
else
{
    botConnection = new BotChat.DirectLine({
        secret: 'XXXXXXXXXXXXXXXXXXXXXX',
        conversationId: cookieConvId,
        watermark: "01",
        webSocket: false,
        pollingInterval: 5000
    });

}

BotChat.App({
    botConnection: botConnection
    ,user: { id: 'USER_ID', name: 'User' },
    resize: 'detect'
}, document.getElementById("chat_div2"));

botConnection.connectionStatus$.subscribe(function (status) {
    if (status == 2) {  // wait for connection is 'OnLine' to send data to bot
        var convId = botConnection.conversationId;
        createCookie('convId',convId,1);
    }
});

```

I then have a DIV with the Id of chat_div2 within my page layout.

This code is also capturing a conversationId in a cookie so I can reload the conversation if a user reloads the page.

**Comment by nwhitmont** [comment]
Update: Fix has been checked into Adaptive Cards repo.
