### ISSUE TITLE
Bot Framework openUrl not working for suggested action on Facebook Messenger

### ISSUE THREAD

**Issue by MarekLani** [Microsoft/BotBuilder#3147]
## System Information (Required)
* SDK Language: NODE
* SDK Version: 3.8.3

## Issue Description
Bot Framework openUrl not working for suggested action on Facebook Messenger

## Code Example
More details and code example, can be found in this [Stackoverflow post](https://stackoverflow.com/questions/45081848/bot-framework-openurl-not-working-for-suggested-action-on-messenger)

**Comment by nwhitmont** [comment]
Closing as duplicate of https://stackoverflow.com/questions/45081848/bot-framework-openurl-not-working-for-suggested-action-on-messenger

**Comment by mabe-at** [comment]
When will this work?

**Comment by mabe-at** [comment]
Any updates for this issue?
It does not help that there is a similar question (without any solution) on stackoverflow.
