### ISSUE TITLE
[Question] Node typings lack support for invoke events

### ISSUE THREAD

**Issue by oneeman** [Microsoft/BotBuilder#3148]
## System Information (Required)
* SDK Language: NODE
* SDK Version: 3.8.3
* Development Environment: LOCALHOST

## Issue Description
Invoke events are supposed to be handled using ChatConnector's `onInvoke` method.  But its type signature (https://github.com/Microsoft/BotBuilder/blob/3e3c40d6424b19c7d371a5cc4f3a86a68f560b25/Node/core/lib/botbuilder.d.ts#L3950) takes a handler with argument of type `IEvent`, which does not have the properties relevant to invoke events (most importantly, `value`).  

This means that if we want to use invoke actions using typescript, in order to access the `value` property which we receive, we have to cast the event to `any`.

Presumably, there should be an interface for invoke events, and that is what the handler passed to `onInvoke` should take.

**Comment by nwhitmont** [comment]
@oneeman What channel are you using? Invoke action is specific to MS Teams and is not supported on other channels.

**Comment by oneeman** [comment]
Sorry, yes, I forgot to specify this is for MS Teams.

**Comment by oneeman** [comment]
I'm closing this issue because it occurred to me to look in the botbuilder-teams library, which I am also using, and I see that the event type for invokes is in there.  Sorry for the trouble.  For what it's worth, the C# version of botbuilder does include some types for invoke events, which was throwing me off a bit.

**Comment by nwhitmont** [comment]
@oneeman thanks for the update. glad to hear you found a solution
