### ISSUE TITLE
Facebook Channel - Prompt Responses Not Handled

### ISSUE THREAD

**Issue by ChristopherMeek** [Microsoft/BotBuilder#315]
I have a bot configured as followed

    bot.add('/', [
        function(session) {
            session.beginDialog('/postcode', { prompt: 'What is your postcode?' });
        },
        function(session, results) {
            session.send(`You gave me ${results.response}`);
        }
    ]);

    bot.add('/postcode', builder.DialogAction.validatedPrompt(
        builder.PromptType.text,
        function(response) {
            return response === 'W1';
        }
    ));

When I run it locally as a TextBot  or with the emulator connected to my live bot the conversation runs as follows

    Me: Hi
    Bot: What is your postcode?
    Me: W1
    Bot: You gave me W1

When I use the botconnector to connect to facebook I get the following conversation

    Me: Hi
    Bot: What is your postcode?
    Me: W1
    Bot: What is your postcode?

It's as if the facebook channel loses track of the fact it was in a dialog.  

Is this a bug with the Facebook channel or (more likely) have I done something wrong?

**Comment by Stevenic** [comment]
interesting... If you use one of the built-in prompts like `Prompts.text()` does it work correctly? Your sample looks fine.

**Comment by ChristopherMeek** [comment]
So I changed it to 

    bot.add('/', [
        function(session) {
            builder.Prompts.text(session,'What is your postcode?');
        },
        function(session, results) {
            session.send(`You gave me ${results.response}`);
        }
    ]);

And it still never falls into the second function of the waterfall.  Odd eh?

**Comment by Stevenic** [comment]
Very... I'll try to reproduce this. I have like 2 bugs ahead of this though

**Comment by ChristopherMeek** [comment]
No problem at all @Stevenic, I'll dig into my message logs for both the Emulator and Facebook and see if I can spot anything further that may help.

**Comment by ChristopherMeek** [comment]
The only thing I've spotted in my logged messages is that the "botPerUserInConversationData" is significantly different;

When using the emulator (connected to the live bot), I get an object containing things like the waterfall index and other state information the bot uses to track internal state.

When using facebook - the logged botPerUserInConversationData is just a string or seemingly random characters (some encrypted state I guess).  

Not sure whether that helps or is a red herring, but thought I'd post my findings anyway.

**Comment by Stevenic** [comment]
That would be an issue. Can you share the two versions of that field. There should be valid JSON in there for bot cases otherwise it's not going to work.

**Comment by Stevenic** [comment]
It actually sort of sounds like you have data from an old C# bot tied to that account. Could that be possible?  One thing you can try is to send '/deleteUserProfile' to the bot which should clear out any cached state.

**Comment by ChristopherMeek** [comment]
Interesting, I've never had a C# bot tied to that account (at least not that I recall).  The /deleteprofile certainly worked though.

Thanks for your help!

**Comment by Stevenic** [comment]
Glad it helped. We're going to add a way to essentially version your bots dialogs which should help with situations like this.
