### ISSUE TITLE
[NuGet] Microsoft.Bot.Builder.Azure dependency on 3.8.0.0

### ISSUE THREAD

**Issue by jsiegmund** [Microsoft/BotBuilder#3151]
## System Information (Required)
* SDK Language: C#
* SDK Version: 3.8.5.0 (Microsoft.Bot.Builder) / 3.2.2 (Microsoft.Bot.Builder.Azure)
* Development Environment: AZURE_BOT_SERVICE

## Issue Description
It seems that Microsoft.Bot.Builder.Azure holds a dependency on Microsoft.Bot.Builder version 3.8.0. When I upgraded my Builder version to 3.8.5 my bot stopped working giving me errors that it cannot load Microsoft.Bot.Builder version 3.8.0.0. 

The NuGet packages should have proper dependencies on which packages can and cannot be used.

## Steps to Reproduce the Issue
1. Build project with Bot.Builder 3.8.0. and Bot.Builder.Azure 3.2.2; everything works
2. Upgrade Bot.Builder to latest available version 3.8.5
3. Call bot, exception.

## Expected Behavior
I'd expect the packages to have the correct dependency information so the package manager will warm me about these types of incompatibility.

## Actual Results
Exception.

**Comment by nwhitmont** [comment]
@jsiegmund Thanks for reporting. I'll have the team update the packages ASAP. 👍

**Comment by nwhitmont** [comment]
Relates to: https://github.com/Microsoft/BotBuilder-Azure/issues/18

**Comment by nwhitmont** [comment]
Relates to: https://stackoverflow.com/questions/45161505/debugging-published-bot

**Comment by jsiegmund** [comment]
I'm not entirely sure the dependency issue is also the cause of the Cortana issue mentioned in the SO post, but ok fair enough to link them :)

**Comment by JasonSowers** [comment]
@jsiegmund  was your bot using formflow?

**Comment by jsiegmund** [comment]
@JasonSowers nope, just LUIS.

**Comment by nwhitmont** [comment]
Update: BotBuilder .NET SDK v3.9.0 has been released.

**Comment by jsiegmund** [comment]
@nwhitmont should it fix any issues?

**Comment by jsiegmund** [comment]
I already had a PR for 3.8.5 but I can update that one for 3.9.0. https://github.com/Microsoft/BotBuilder-Azure/pull/20

**Comment by JasonSowers** [comment]
Please reopen if you are still experiencing this issue
