### ISSUE TITLE
[Question] QnAMaker API not responding after calling from other js file in Node.js

### ISSUE THREAD

**Issue by sjais789** [Microsoft/BotBuilder#3152]
## System Information (Required)
* SDK Language: 
* SDK Version: 
* Development Environment:

**Comment by nwhitmont** [comment]
Closed as - user did not provide any issue description.

**Comment by sjais789** [comment]
sorry for the  insufficient details. I have added the gist.
https://gist.github.com/sjais789/48eefd4b24da40c2360de1fb212997ba

**Comment by JasonSowers** [comment]
@sjais789 please fill out the post template, you have given us no information to assist you.

**Comment by sjais789** [comment]
I have filled it .

**Comment by jack12171992** [comment]
@sajal2692 is this gets resolved?
Becasue I'm haveing the same issue right now
