### ISSUE TITLE
[0630 - 0730 UTC-7] API Europe outage

### ISSUE THREAD

**Issue by chrisgitrepo** [Microsoft/BotBuilder#3154]
Can you please confirm this is being looked into, production environments are down.

## Issue Description
Error: Request to 'https://europe.directline.botframework.com/v3/' failed: [503] Service Unavailable

**Comment by McGern** [comment]
The US data centre appears to be down as well. Can't even test a bot from the bot framework webchat test on dev.botframework.com. Looks like it has been down for at least an hour and a half.

**Comment by ivmos** [comment]
Same issue here

**Comment by nwhitmont** [comment]
All services had interruptions between 6:30am and 7:30am PDT (UTC-7)

**Comment by McGern** [comment]
The US data centre seems to be fine now, but I am now getting a 500 internal server error for my bots when using the European directline service (the same bot works with the US directline service)

**Comment by chrisgitrepo** [comment]
Europe seems to to work fine now.

Microsoft, any chance for an update as to what happened? Is there a risk it will happen again? Its hard to justify the Bot Framework to clients when it goes down for 2 hours+ during prime time.

**Comment by iMicknl** [comment]
@nwhitmont the status page is still down. Is the team aware of this? https://status.botframework.com
Outages can happen, but it would be great if the history / communication would be available on status.botframework.com.

**Comment by nwhitmont** [comment]
@iMicknl Yes we disabled the status page on purpose since it's not getting updated in real-time and didn't want to confuse users.

**Comment by peterswimm** [comment]
Is there any social media account or something similar we can monitor for outage notifications in the meantime?
