### ISSUE TITLE
[Question] ReceiptCard ImageCard tap doesn't fire 

### ISSUE THREAD

**Issue by valentinewallace** [Microsoft/BotBuilder#3158]
## System Information (Required)
* SDK Language: Node
* SDK Version: 3.5.29
* Development Environment: AZURE_BOT_SERVICE

## Issue Description

When using a ReceiptCard, the `tap` property doesn't work for images embedded in ReceiptItems. You can tap on the item itself, but you can't tap on the image and have it fire a separate event. 
## Code Example

```js
let createCard = session => {
    let tap = builder.CardAction.openUrl(session, 'https://www.google.com', 'hi_link'); 

    let img = builder.CardImage.create(session, 'https://tctechcrunch2011.files.wordpress.com/2008/04/linux-penguin-small.png').tap(tap); 

    return new builder.ReceiptCard(session)
        .items([
            builder.ReceiptItem.create(session, '$ 5.00', 'Food')
                .image(img),
            builder.ReceiptItem.create(session, '$ 45.00', 'App Service')
                .quantity(720)
                .image(builder.CardImage.create(session, 'https://github.com/amido/azure-vector-icons/raw/master/renders/cloud-service.png'))
        ])
        .tax('$ 7.50')
        .total('$ 90.95')
        .buttons([
            builder.CardAction.openUrl(session, 'https://azure.microsoft.com/en-us/pricing/', 'More Information')
                .image('https://raw.githubusercontent.com/amido/azure-vector-icons/master/renders/microsoft-azure.png')
        ]);
}
```
## Steps to Reproduce the Issue
1. Use the above method to return a card in the Bot Framework Emulator. 
2. Clicking on the image does nothing for the first item, which should fire a `tap` event, does nothing. I've also tried different types of tap events and none fire. 

## Expected Behavior

I would expect the `tap` property on the image to result in the URL google.com to open. 
## Actual Results

Nothing happens.

**Comment by nwhitmont** [comment]
@valentinewallace I noticed you are using an older version of `botbuilder` NPM module. Are you still experiencing the issue after upgrading `botbuilder` module to v3.8.4?

**Comment by nwhitmont** [comment]
@valentinewallace For reference, what channel(s) are you using with the Receipt Card where you experience this problem? Some channels will handle the card actions differently... Eg. Skype, Slack, WebChat, etc.?

**Comment by nwhitmont** [comment]
@valentinewallace For reference, what channel(s) are you using with the Receipt Card where you experience this problem? Some channels will handle the card actions differently... Eg. Skype, Slack, WebChat, etc.?

**Comment by nwhitmont** [comment]
@valentinewallace The `tap` attribute is designed to be added as a top-level property of the `ReceiptCard` itself. The `tap` attribute will not function when added to a `CardImage` object as in your example.  The idea is that the user "taps" on the whole card, rather than an individual item within that card. 

From the ReceiptCard definition:
https://docs.botframework.com/en-us/node/builder/chat-reference/classes/_botbuilder_d_.receiptcard.html#tap

*Tap*
>This action will be activated when user taps on the card.

The card with tap attribute configured works like this:
```js
et img = builder.CardImage.create(session, 'https://tctechcrunch2011.files.wordpress.com/2008/04/linux-penguin-small.png'); 

    return new builder.ReceiptCard(session)
        .tap(builder.CardAction.openUrl(session, "https://google.com"))
        .items([
            builder.ReceiptItem.create(session, '$ 5.00', 'Food')
                .image(img),
            builder.ReceiptItem.create(session, '$ 45.00', 'App Service')
                .quantity(720)
                .image(builder.CardImage.create(session, 'https://github.com/amido/azure-vector-icons/raw/master/renders/cloud-service.png'))
        ])
        .tax('$ 7.50')
        .total('$ 90.95')
        .buttons([
            builder.CardAction.openUrl(session, 'https://azure.microsoft.com/en-us/pricing/', 'More Information')
                .image('https://raw.githubusercontent.com/amido/azure-vector-icons/master/renders/microsoft-azure.png')
        ]);
```
