### ISSUE TITLE
[API Endpoint Down] Intermittent Service Unavailable https://webchat.botframework.com/

### ISSUE THREAD

**Issue by tonymathewt** [Microsoft/BotBuilder#3161]
## System Information (Required)
* SDK Language: .NET/C#
* SDK Version: 3.8.0
* Development Environment: AZURE_BOT_SERVICE

## Issue Description

Not sure why now. I am getting error/status 503 Service Unavailable from webchat.botframework.com/api/tokens...
I tried to see my bot configurations (Web channel) loging into https://dev.botframework.com/bots/channels?id=MyBotId&channelId=webchat and this page errors out (YSOD). Wondering anybody else facing this now? Or is it just me. It started happening from today morning.

![capture1](https://user-images.githubusercontent.com/30287135/28360694-dc8d3428-6c93-11e7-832f-1ff1a49a8ff6.PNG)

**Comment by nupurkamble** [comment]
Yes i am have the same issue since 2-3 hours
im also getting these errors on my bot

> VM307:20 WebSocket connection to 'wss://directline.botframework.com/v3/directline/conversations/..' failed: Error during WebSocket handshake: Unexpected response code: 503
> 
> XMLHttpRequest cannot load https://directline.botframework.com/v3/directline/conversations/...?watermark=. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://asirdv2testing.azurewebsites.net' is therefore not allowed access. The response had HTTP status code 503.

**Comment by nikhil-001mehta** [comment]
Yes I am also facing this issue. Can anyone please give some heads up with this. What is the exact issue and by what time will it be fixed.

**Comment by tonymathewt** [comment]
@nupurkamble thanks for confirming/letting me know. @nikhil-001mehta I honestly don't know my friend. I am hoping that it would resolve by itself. I doubt whether this issue is region dependent. Because its behaving better when I tried the same url from a UK VM. The YSOD looks fixed now. But the channel's behaviour is still the same.

**Comment by nwhitmont** [comment]
@tonymathewt @nikhil-001mehta @nupurkamble There was an outage this morning which has since been resolved.
