### ISSUE TITLE
[Bot Portal] Microsoft Bot Framework bots disappeared

### ISSUE THREAD

**Issue by df42** [Microsoft/BotBuilder#3167]
Original post at stackoverflow: https://stackoverflow.com/questions/45189635/microsoft-bot-framework-bots-disappeared

Since a few days we are missing all our bots in the "My Bots" section of the Microsoft Bot Framework at https://dev.botframework.com/

They still do work as expected, but we can not see or edit them. 
Creation and deletion of new bots seems to work fine, but new ones also disappear within 1 day.

Here are some information about 2 of the bots, which might help to understand the problem at Microsofts side (sadly I can not remember the bot names, so I hope Handle & ID are enough):

Bot Handle: dSKettleBotV2-Alpha
Bot App ID: 57631f3b-2b45-4aca-a14e-b9932437122d

Bot Handle: dSKettleBotV2-Beta
Bot App ID: d188f432-e30f-4ff2-8e8d-bf0d9ae51909

Any help is appreciated. 

Thanks in advance and best regards,

- Dominik

**Comment by nwhitmont** [comment]
@df42 Thanks for reporting.  I'm going to get with the platform team today and see if we can figure out what's happening here.  Will update you when I have more details.

**Comment by NickEricson** [comment]
Dominik - We have a different Owner Email address listed for these bots (this is configurable on the settings tab). If you Email me (nericson @ microsoft.com) I will reply with that Email address.

Sorry about all the confusion.

**Comment by df42** [comment]
@NickEricson I'm not sure what you mean, but I've sent you an e-mail 👍

**Comment by nwhitmont** [comment]
reopen if the issue persists.

**Comment by mitkodi** [comment]
I have the same issue - don't have access to my bots.

One of them is:
**BotId**: SBC.Demo-Bot
**MicrosoftAppId**: 31148f7f-3ebb-474b-bc3a-8b16d0ab4f8d

**Comment by JasonSowers** [comment]
@mitkodi you are commenting on a closed issue please open a [new issue](https://github.com/Microsoft/BotBuilder/issues/new).

**Comment by mitkodi** [comment]
Thanks @JasonSowers, I opened new issue #3434.
