### ISSUE TITLE
LuisResult.Entities.Add() causes an Exception?

### ISSUE THREAD

**Issue by megancooper** [Microsoft/BotBuilder#3168]
### System Information
.NET/C#
Testing Bot in: MS Teams and Bot Emulator

I asked this on [StackOverflow](https://stackoverflow.com/questions/45217507/luisresult-entities-add-causes-a-system-notsupportedexception) but wanted to ask here to see if it was a bug?

In my code I dynamically add entities to a Luis Result like this:

    [LuisIntent("Show Color")]
    public async Task displayColor(IDialogContext context, LuisResult result)
    { 
        EntityRecommendation color;
        if (!result.TryFindEntity("color", out color)) {
            color = new EntityRecommendation();
            color.Entity = "white";
            color.Type = "color";
            result.Entities.Add(color); // <-- This Line Causes the Exception
        }
    }

The weird thing is this code was working before, but has stopped working and now shows this Exception in the bot emulator when the line `result.Entities.Add(color);` is hit:

[![Bot Emulator Exception][1]][1]

[![enter image description here][2]][2]

Here is the Exception shown in Visual Studio 2015 : 

[![enter image description here][3]][3]

Could this be related to wrong Nuget Package versions? It was working smoothly before but I added some Authentication services and now this Exception is showing up. Thanks for the help.

  [1]: https://i.stack.imgur.com/uGFBr.png
  [2]: https://i.stack.imgur.com/4VskD.png
  [3]: https://i.stack.imgur.com/0fKrG.png

**Comment by ashicertis** [comment]
I believe that you need to extract the entities object into a new variable and then make changes.

> var entities = new List<EntityRecommendation>(result.Entities);
> entities.Add(new EntityRecommendation());
>

**Comment by megancooper** [comment]
@ashicertis Thanks this seems to work :)

**Comment by ashicertis** [comment]
@megancooper You are welcome.
