### ISSUE TITLE
[Question] Facebook returns error when using list template

### ISSUE THREAD

**Issue by dan-cohn** [Microsoft/BotBuilder#3169]
## System Information (Required)
* SDK Language: NODE
* SDK Version: 3.8.4
* Development Environment: OTHER

## Issue Description
I've been trying to use the Facebook list template with my bot. No matter what I do, it comes back with an error (400 Bad Request). I finally tried sending the JSON directly to Facebook (via curl). It worked! However, the exact same message attachment fails when sent through the bot framework.

I have tried both addAttachment() and sourceEvent() to add the template in my message. It's the same result either way.

I'm using a very simple test message that looks like this:
```{
  "type": "template",
  "payload": {
    "template_type": "list",
    "top_element_style": "compact",
    "sharable": false,
    "elements": [
      {
        "image_url": null,
        "title": "Title 1",
        "subtitle": "Subtitle 1",
        "buttons": [
          {
            "type": "postback",
            "title": "Button Title",
            "payload": "Button Title"
          }
        ]
      },
      {
        "image_url": null,
        "title": "Title 2",
        "subtitle": "Subtitle 2",
        "buttons": [
          {
            "type": "postback",
            "title": "Button Title",
            "payload": "Button Title"
          }
        ]
      },
      {
        "image_url": null,
        "title": "Title 3",
        "subtitle": "Subtitle 3",
        "buttons": [
          {
            "type": "postback",
            "title": "Button Title",
            "payload": "Button Title"
          }
        ]
      }
    ]
  }
}
```
## Code Example
```
        var att = { };  // structure shown above, for example
        var msg = new builder.Message(session)
            .sourceEvent({
                facebook: {
                    attachment: att
                }
            });
        session.send(msg);
```
## Steps to Reproduce the Issue
1. Start a conversation with bot
2. Reach a point in which bot responds with list template
3. Observe error in console

## Expected Behavior
List template should appear in Facebook messenger conversation (as it does when I send the template manually via curl).

## Actual Results
`Error: Request to 'https://state.botframework.com/v3/botstate/facebook/conversations/1567261700015332-1272676849512701/users/1567261700015332' failed: [400] Bad Request`

**Comment by dan-cohn** [comment]
By the way, I also tried using sourceEvent to send
```
{
  facebook: {
    text: "hi"
  }
}
```
Even this doesn't work. I feel like there's an issue with the FB connector, but maybe I'm just missing something.

**Comment by dan-cohn** [comment]
Wow, I just figured out what's wrong.  It has nothing to do with the FB templates!

My problem was that I was storing too much information in the conversation data at the same point where I was sending the message.  I guess there's a limit on how much session data you can have?

Once I removed the excessive data, it started working.

**Comment by JasonSowers** [comment]
32k limit
