### ISSUE TITLE
BotConnectorBot with Skype Channel

### ISSUE THREAD

**Issue by byrner75** [Microsoft/BotBuilder#317]
I have a node.js bot up and running and I am able to converse with it using Telegram. Thanks again for your help on the Telegram channelData issue, its all working great now. So I just tried to add a Skype Channel I followed the instructions however i'm having problems !

My bot is currently using BotConnectorBot, do I need to use the skype-sdk if I want a Skype channel?

What is the messaging webhook I need to configure in the Skype Developer Portal? Is it my bot endpoint or a botconnector endpoint (which seems to be the default) ?

Out of curiosity I created a small test bot based on the skype-sdk and when I set the messaging webhook to my bot endpoint I receive messages in however the session.send() doesn't get the message back to Skype. I've switched on debug (DEBUG=skype-sdk*) and the debug info would indicate that a message is being sent back to Skype however no message arrives !

I've also just tried the Web Page Channel and am unable to see reply messages in the chat !

Any pointers help greatly appreciated.

**Comment by byrner75** [comment]
I've got the Web Channel working.

I needed to add the conversation and recipient coordinates to the session.send method. It didn't work with just passing a string of text.

Still no joy with Skype !

**Comment by Stevenic** [comment]
You should go to the [Skype developer portal](https://www.skype.com/en/developer/) and sign up for access if you haven't done so already. You should just use the BotConnectorBot as you're doing and shouldn't have to change anything code wise. The instructions in our dev portal are to walk you through how to configure things on the skype side of things using their portal.

**Comment by byrner75** [comment]
Went back over the Skype Channel wizard and success. Thanks for your help.
