### ISSUE TITLE
[Question] Editing the message sent by user before it is printed?

### ISSUE THREAD

**Issue by nupurkamble** [Microsoft/BotBuilder#3171]
Is there way to take the text sent by the user to the bot before it prints and edit it and then print it.
example if user writes 'Hellllo'  the wrong spelling is printed as the users message. But i want to print the corrected text instead i.e. 'Hello'. (Shown in image)
I'm already using the bing spell check api for the bot to understand but i don't want the wrong text to show at all

![capture](https://user-images.githubusercontent.com/29529893/28460612-6b87a4e0-6e30-11e7-9a23-1c2b480119c3.PNG)

**Comment by nwhitmont** [comment]
@nupurkamble For reference, are you using .NET or Node SDK?

**Comment by nupurkamble** [comment]
I'm using .Net

**Comment by nrobert** [comment]
I don't see any way to do that, as the message is handled by the channel first

**Comment by nwhitmont** [comment]
Not currently a feature.
