### ISSUE TITLE
[Question] How do I tell LUIS to use this Intent instead of the one it's thinks

### ISSUE THREAD

**Issue by elubinenaptive** [Microsoft/BotBuilder#3175]
What should I do when Luis says "Luis thinks this is the correct intent" and shows me a different intent for my phrase than the Intent I'm looking at. It says 62% chance it's the None intent while my phrase in my current intent says only "30% chance". (Luis thinks this intent is NOT correct for this utterance)

How do I tell Luis it's wrong and that it needs to use this intent for this utterance?

![image](https://user-images.githubusercontent.com/29802090/28478263-aed66ac0-6e25-11e7-8088-0b279d83ab97.png)

**Comment by nwhitmont** [comment]
@elubinenaptive For reference, are you using .NET or Node?

You need to train your model in order for it to recognize things the way you want it to. 

>You should continuously work on your application to refine it and improve its language understanding. Whenever you make updates by adding, editing or deleting entities, intents or utterances in your current model, you’ll need to train your app before testing and publishing. When you "train" a model, LUIS generalizes from the examples you have labeled, and builds model to recognize the relevant intents and entities in the future, thus improving its classification accuracy.

For more information about training your LUIS model, see:
https://docs.microsoft.com/en-us/azure/cognitive-services/LUIS/train-test

**Comment by elubinenaptive** [comment]
I am using C#.

Are the score values just for reference?  Or is there a way to use those values to train Luis?

**Comment by DeniseMak** [comment]
The scores are a hint that tell you which utterances are the most important for training LUIS. A big difference in the scores mean a bigger change in the behavior of the LUIS app if you retrain with that utterance. For example, let's say you have a LUIS app with a None intent and the prebuilt Weather.GetCondition intent, and you've already trained it on just the utterance "hi" in the None intent. Then you add "help", "what time is it" and "what kind of weather does this app get?", and get a result like the following:
<img width="662" alt="luistrainingscores" src="https://user-images.githubusercontent.com/5029189/28484901-15262d8e-6e2a-11e7-83a5-b37c6bccaa62.png">


This means:
- Both "what time is it" and "what kind of weather does this app get" will be misclassified as Weather.GetCondition unless you train the app again with these utterances labeled as None. 
- Re-training with "what kind of weather does this app get" will likely have a greater effect on the behavior of the LUIS app than re-training on "what time is it", although you should probably include both.  The utterance "help" would already be correctly classified, so adding it to the example utterances will have less of an effect.

**Comment by nwhitmont** [comment]
Thanks for the additional info @DeniseMak 👍
