### ISSUE TITLE
[Cortana] Errors when SayAsync long response?

### ISSUE THREAD

**Issue by anarchitect** [Microsoft/BotBuilder#3178]
## System Information (Required)
* SDK Language: C#
* SDK Version: 3.8.3.0
* Development Environment: AZURE_APP_SERVICE

Bot handle: EchoCortana

## Issue Description
when SayAsync too many characters, Cortana on Windows 10 Enterprise will error saying "Sorry, I can't support that action on this version of Windows. Updating should help. Try asking me about the Windows 10 Creators Update.". However, the same response works on Cortana iOS without a problem. 

## Code Example
```
string textToSpeak;
            if (activity.Text.ToLower().Contains("long"))
            {
                textToSpeak = "test too many characters will cause error on Windows 10. But there is no problem on iOS. Consider joining the developer program - Designed for developers who build solutions that extend Office and the Office 365 experience across desktop, web, and mobile platforms.";
              }
```

## Steps to Reproduce the Issue
1. call the bot (bot handle provided as above") say "ask Echo Speaker long". you will see the error above on Windows 10, and using iOS will work
2. Alternatively, put the code above in any bot, provision the bot into Cortana, trigger this code on Windows 10 via Cortana, it will error. on iOS it will work. 

## Expected Behavior
It should speak out all the answers on Windows 10 properly. 

## Actual Results
on windows 10, it will error, the error is provided in the image in this post 
![errorcortanaspeak](https://user-images.githubusercontent.com/2878492/28498858-52489b80-6feb-11e7-9943-5928355b975b.png)

**Comment by nwhitmont** [comment]
The problem, as shown in the Cortana error message screenshot above, is that your version of Windows operating system does not support Cortana Skills completely. This is a known issue.

See: https://docs.microsoft.com/en-us/cortana/testing/known-issues

## Cortana stops talking after 15 seconds or displays the message "Unfortunately this skill won't work on this version of Windows"

>Cortana in the Windows 10 Anniversary update (version 1607) is limited to 15 seconds of audio. This has been resolved in the Windows 10 Creators update (version 1703). A workaround for Bot Framework-based skills is to break your response up into multiple responses and to return multiple responses to the user.
