### ISSUE TITLE
[Question] How to edit "What do you want to change?" prompt and what's shown after that in a FormFlow ?

### ISSUE THREAD

**Issue by nupurkamble** [Microsoft/BotBuilder#3179]
I have a written this formflow and its output on some browsers looks fine but on some it doesnt.

    [Serializable]
    public class InquiryForm
    {
        [Prompt("What is your First Name? {||}")]
        public string FirstName { get; set; }
        [Prompt("What is your Last Name? {||}")]
        public string LastName { get; set; }
        [Prompt("What is your email address? {||}")]
        public string Email { get; set; }
        [Prompt("What is your Contact number?(Enter a 10 digit number) {||}"), Numeric(1000000000, 9999999999)]
        public int MobilePhone { get; set; }
        [Prompt("What is your Procedure name? {||}")]
        public string ProcedureName { get; set; }
        [Prompt("Please write your inquiry here {||}")]
        public string Comment { get; set; }

        public static IForm<InquiryForm> BuildForm()
        {

            return new FormBuilder<InquiryForm>()
                .Message("I just need a few details:")
                .AddRemainingFields()
                .Confirm()
                .Build();
        }
    }

On saying no after the question "What do you want to change?" the following output is shown in **chrome**

![1](https://user-images.githubusercontent.com/29529893/28498891-58968d00-6fc6-11e7-863a-e698c14bd951.PNG)

whereas the same thing in **edge/ mozilla** is shown as

![22](https://user-images.githubusercontent.com/29529893/28498893-6651273e-6fc6-11e7-92ab-2363d3214d14.PNG)

is there a way i could edit the buttons and just show the field names instead.

I would really appreciate some help. This formflow is kinda hard to understand and customize. Even after looking at its documentation

**Comment by ankitbko** [comment]
I am not sure what you want. Do you not want to show the current choices in parenthesis?
One way to do this is by adding following attribute to the `InquiryForm` class.
```csharp
[Template(TemplateUsage.NavigationFormat, "{&}")]
```
![image](https://user-images.githubusercontent.com/3169316/29127247-311bf578-7d3e-11e7-9bbc-23d2a9cba9ec.png)

Let me know if this helps.
