### ISSUE TITLE
Go back to previous chat message or to start convo from beginning

### ISSUE THREAD

**Issue by bluekite2000** [Microsoft/BotBuilder#318]
I m using c# and I have 
```
  async Task IDialog<object>.StartAsync(IDialogContext context)
            {
context.Call<TopChoice>(new FormDialog<TopChoice>(new TopChoice()), WhatDoYouWant);
            }
```
In WhatdoYouwant I call another function and so on up to func nth.
If user is in func nth and  type 

> go back

 how do I go back to nth-1? And how do I go back to func StartAsync when she types 

> reset

**Comment by chrimc62** [comment]
Are you talking about within a form or across dialogs?  If within a form that is the behavior you will already get.  If you want to go across multiple dialogs, @willportnoy  can help describe how you intercept messages and manipulate the dialog stack.

**Comment by willportnoy** [comment]
If the user's input is "reset", you can call whatever function you want.  StartAsync is a little harder to return to, but you can always choose to do nothing in your StartAsync other than waiting for a first message.

**Comment by willportnoy** [comment]
I'm going to close this item for now, but feel free to re-open it for further discussion.

**Comment by bluekite2000** [comment]
@Stevenic I have 
```
dialog.on('book  a flight', [
function (session, args, next) {
}
function (session, results) {
}
```
and so on (from 1st to Nth function)
How do I enable this feature:  a.if user types go back I jump  from Nth to Nth-1 function? b.if user types reset it jumps to 1st function (bot saying hi)

Also I have a 
```
dialog.on('change  a flight', [
function (session, args, next) {
}

```
which have some common functions (for ex the 5th function) w/ book a flight. Is there a way for me to use the same 5th function for both intents?

**Comment by Stevenic** [comment]
To jump back to the first prompt you need to do two things:

1. Break you waterfall out to a separate dialog called /bookFlight or something.
2. To jump back to the first prompt you need to completely re-load your dialog using session.replaceDialog('/bookFlight').

Make sure that when they're through booking a flight you call session.endDialog() somewhere to return control back to your LuisDialog.

**Comment by v-thgratMSGit** [comment]
Closing this issue. Please open a new issue for further discussion if necessary. Thanks!
