### ISSUE TITLE
[Skype] Warning messages “Acl check failed”

### ISSUE THREAD

**Issue by Noc2** [Microsoft/BotBuilder#3184]
## System Information (Required)
* SDK Language: C#
* SDK Version: 3.8.5
* Development Environment: Azure App Service 

## Issue Description
Might be a stupid question but I've never heard of an “Acl check”. I get the following warnings for the skype channel “Acl check failed” for a few days now. Any idea why? 
Microsoft App Id: 64ba2a82-af90-43f0-8aea-42a95405a1ba
![image](https://user-images.githubusercontent.com/24638510/28534451-11fe1f9e-70a1-11e7-8585-7f8d11cea9f1.png)

**Comment by PrasenjitGiri** [comment]
I was facing the same issue, but after refreshing the bot portal I ended up opening the bot in two skype (mac & windows) and added it to contacts list. Somehow the error went away.

**Comment by Noc2** [comment]
I republished my bot on skype and now it seems to be solved.

**Comment by nwhitmont** [comment]
@Noc2 Thanks for the update! Glad to hear it's working now.

**Comment by abharku** [comment]
I have got the same issue. Works with all other providers but skype

Application id = 6fd5b887-635b-4195-9ad9-a6d609e4062e

**Comment by nwhitmont** [comment]
@abharku You are commenting on a closed issue. 

If you have a question or problem, please [open a new issue.](https://github.com/microsoft/botbuilder/issues/new)
