### ISSUE TITLE
[Question] How to implement push notification for chatbot using bot framework

### ISSUE THREAD

**Issue by amitgobare23** [Microsoft/BotBuilder#3186]
I created bot already.but now i have to implement push notification service for same....how i can implement it by using c#...thanks in advance

**Comment by nrobert** [comment]
What exactly do you mean by push notification service:

- what would be the input (what is your use case)?
- on which channels do you want to "push"?

What did you try so far?

**Comment by nwhitmont** [comment]
@amitgobare23 It sounds like you are looking for proactive messaging. 

For more information, check out this article: 
https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-proactive-messages

Code Example:
https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/core-proactiveMessages

**Comment by amitgobare23** [comment]
@nrobert I created bot for ECommerce website so use case as like:
1. Suppose my portal launch new products and i have to notify all subscriber/customer regarding same
So for this I have to send notification(Push Notification) to all of them hence they can click on notification pop-up and navigate directly to my bot.

**Comment by nrobert** [comment]
Where is your bot currently deployed? On a Webchat in the eCommerce website?

**Comment by amitgobare23** [comment]
It is not yet deployed but i am creating chatbot for them....i am looking for both channels facebook chatbot as well as webchat for push notification...

**Comment by nwhitmont** [comment]
@amitgobare23 In Bot Framework, we call it "proactive message". You can find code example and documentation explaining this feature in my previous comment above.
