### ISSUE TITLE
Session not pertaining

### ISSUE THREAD

**Issue by bensun13** [Microsoft/BotBuilder#319]
We are running the bot on Node.js and are running into a problem with it keeping session. The alarm example is stuck in a loop not storing the state. We are also getting a warning "info: Warning: using temporary storage. Data will be lost when process restarts.".

**Comment by Stevenic** [comment]
You're using the `SlackBot` I assume. You'll need to configure storage for BotKit following their documentation. 

I will give you a heads up that the SlackBot connector will probably be going away in a future version. The BotConnectorBot supports connecting to Slack as well and seems to be what most people are using so we'll be focusing our efforts there. It should be minimal work to convert.
