### ISSUE TITLE
[Question] Slack sends events to all bots?

### ISSUE THREAD

**Issue by bilby91** [Microsoft/BotBuilder#3191]
## System Information (Required)
* SDK Language: NODE
* SDK Version: 3.8.4
* Development Environment: LOCALHOST, AWS

## Issue Description
We have multiple bots in https://dev.botframework.com/bots. We have development bots, one for the staging environment and another one for the production environment. 

Every bot has a different App Id and password.

We are experiencing the following problem (only with Slack, Teams doesn't seem to be affected):

When we install the bot in our team in Slack, every single bot gets the `installationUpdate` event. It's not the same event since the payloads (different bot ids and slack api tokens) are different depending on the bot that receives the event. 

The other really strange thing is that we get events from bots that are owned by different botframework accounts! One of our team members has it's own botframework account and has created a development bot for this work, when he installs his bot, the other bots get an `installationUpdate` event. 

We are testing all this under the same Slack team obviously.

## Steps to Reproduce the Issue
1. Create Bot 1 in botframework.com
2. Create Bot 2 in botframework.com
3. Install Bot 1 in a Slack team
4. Install Bot 2 in a Slack team
5. Bot 1 will get a `installationUpdate` event as if he was installed.

## Expected Behavior
Only Bot 2 receives the `installationUpdate` event.

## Actual Results
Bot bots get an `installationUpdate` event.

**Comment by nrobert** [comment]
There is a lack of documentation around all the events. From my point of view, when looking at the documentation of `ActivityTyoes` ([here](https://docs.botframework.com/en-us/csharp/builder/sdkreference/d2/d7d/class_microsoft_1_1_bot_1_1_connector_1_1_activity_types.html#a0eb232e06a6ad4e7798c43b5d024b098)), it says 
`Bot added or removed from channel` so every this event is thrown to every bot in the channel (like `conversationUpdate` or other events).

There are differences between channels that are also not obvious. For example for user messages, Slack is different from Skype: it gets all messages from user, not only those with `@bot` mention

**Comment by bilby91** [comment]
@nrobert I understand that there is a lack of documentation but I don't think my problem is some documentation missing. The `installationUpdate` event should not be triggered for Bot1 if Bot2 is being installed. How would I know if my bot is installed if every time someone installs any bot I get an `installationUpdate` event like if my bot was installed ?  Remember that the event gets triggered with Bot1's ids and Bot2's ids.

**Comment by nrobert** [comment]
@bilby91 it's annoying yes. You are sure that there is absolutely no difference between 2 installationUpdate for 2 bots on the same channel?

Can you post the message (JsonSerialized, to be sure to get every item) that you got in that case? Sorry I can't have a quick look, I got only 1 bot on my slack team

**Comment by bilby91** [comment]
Yes @nrobert, there are differences between the two `installationUpdate` events. One event shows the information of `Bot1` being installed and the other event shows the information of `Bot2` being installed. The problem is that `Bot1` is the only bot that was actually installed in the team.

I'm enriching the logging of our bot and will send more detailed information.

**Comment by nrobert** [comment]
Ok, waiting for your details!

**Comment by bilby91** [comment]
@nrobert You were right! The bot information in the address is correct. The sourceEvent in the slack payload is sending the different bot ids so I'm able to identify if my bot is being added or another one.

Thanks!

**Comment by nrobert** [comment]
My pleasure 👍  can you add an exemple of the payload for future use?

**Comment by bilby91** [comment]
Yes, this is an example of `installationUpdate`


```json
{
   "sourceEvent":{
      "SlackMessage":{
         "type":"bot_added",
         "bot":{
            "id":"BXX",
            "deleted":false,
            "name":"Bot",
            "updated":1501012914,
            "app_id":"AXX",
            "icons":{
               "image_36":"https://s3-us-west-2.amazonaws.com/slack-files2/avatars/2017-07-24/XX_36.png",
               "image_48":"https://s3-us-west-2.amazonaws.com/slack-files2/avatars/2017-07-24/216957844197XX_48.png",
               "image_72":"https://s3-us-west-2.amazonaws.com/slack-files2/avatars/2017-07-24/XX_72.png"
            }
         },
         "cache_ts":1501012914,
         "event_ts":"1501012914.130505"
      },
      "ApiToken":"xoxb-XXX"
   }
}
```
