### ISSUE TITLE
[FB Messenger] How to use private replies?

### ISSUE THREAD

**Issue by amitbend** [Microsoft/BotBuilder#3192]
## System Information (Required)
* SDK Language: Node
* SDK Version: 3.8.4
* Development Environment: LOCALHOST

## Issue Description
I'm trying to use Facebook private replies [more info here](https://developers.facebook.com/docs/graph-api/reference/object/private_replies)
The way to do it is by subscribing to a facebook webhook (feed), just like we are doing for messages.
When I'm trying to send an event through the webhook, I'm not able to see it through the bot, but I get this error through the botframework dashboard:
`Value cannot be null.  Parameter name: source`

Is it possible to configure the endpoint so it will differentiate between bot messages and those private replies?

**Comment by iMicknl** [comment]
I was working on this also, but with a different approach. Would you mind sharing your code?
In my opinion this functionality should be outside of the Bot Framework, since it is super specific. Replies on the 'Private Reply' can be handled by the Bot Framework afterwards.

**Comment by amitbend** [comment]
Hi @iMicknl I didn't start writing code actually.
I looked at the common implementations of this feature and I'll try to explain the flow.

You can subscribe to changes in your feed (meaning posts + comments), and once a new comment appears, you can trigger your bot to send a new private reply.

![image](https://user-images.githubusercontent.com/11259265/28656161-f8898e86-72a8-11e7-978c-6bdbce114024.png)

The way to subscribe is through a webhook called `feed`, which is a webhook just like the messenger webhook.

You can only specify one address for your server that will receive all the webhook events from Facebook, and currently, it's  the botframework link which is being used for the bot.

Hope it's clear enough.

**Comment by fanidamj** [comment]
Hoping that issue has been resolved, closing it. Feel free to reopen if any questions.

**Comment by fanidamj** [comment]
Hoping that issue has been resolved, closing it. Feel free to reopen if any questions.

**Comment by garyfungwelab** [comment]
An alternative way is creating a new Facebook app to do the feed subscription.
One app for messenger -> Botframework, another for feed subscription.

**Comment by Unders0n** [comment]
@garyfungwelab have you succeed in solving this?

**Comment by marcasmar94** [comment]
Any updates on catching Feed events ?
