### ISSUE TITLE
[Performance] Unknown [500] Internal Server Error with Emulator and Bot Dev Portal?

### ISSUE THREAD

**Issue by megancooper** [Microsoft/BotBuilder#3194]
I hate posting this because its such a common issue, but I just started getting a [500] internal server error in the Emulator and on the dev.botframework.com. I have no idea what caused this to happen because I have the correct ID and Pass in my Web.Config which I haven't changed in a long time. I double-checked all the config values and my MessagesController just to be sure `[BotAuthentication]` was uncommented and it was. 

Could this be a package issue? I was not installing or changing Nuget packages when this occurred it kind of just popped up when I tried to refresh my bot emulator. I tried accessing my bot in MS Teams and thats where I saw the same error in dev.botframework.com.

I CAN get the emulator to work if I comment out `[BotAuthentication]` in my MessagesController class but I don't want to do that when it was working before. Also, my bot needs the Authentication to work in Teams.

Could this be an issue with Nuget packages?

Exception in VS 2015 Output window:
```
Exception thrown: 'Microsoft.Bot.Connector.MicrosoftAppCredentials.OAuthException' in mscorlib.dll
The program '[11148] iisexpress.exe' has exited with code 0 (0x0).
```
Exception in emulator:
![err](https://user-images.githubusercontent.com/8683055/28588076-e55d3738-713e-11e7-91d6-5919a298179b.PNG)

My packages.config (That was not touched/changed at all when this ERR occured)
```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Autofac" version="4.6.0" targetFramework="net46" />
  <package id="Chronic.Signed" version="0.3.2" targetFramework="net46" />
  <package id="Microsoft.AspNet.WebApi.Client" version="5.2.3" targetFramework="net46" />
  <package id="Microsoft.AspNet.WebApi.Core" version="5.2.3" targetFramework="net46" />
  <package id="Microsoft.Bot.Builder" version="3.8.5.0" targetFramework="net46" />
  <package id="Microsoft.Cognitive.LUIS" version="2.0.2" targetFramework="net46" />
  <package id="Microsoft.IdentityModel.Clients.ActiveDirectory" version="3.14.1" targetFramework="net46" />
  <package id="Microsoft.IdentityModel.Protocol.Extensions" version="1.0.4.403061554" targetFramework="net46" />
  <package id="Microsoft.Rest.ClientRuntime" version="2.3.8" targetFramework="net46" />
  <package id="Newtonsoft.Json" version="9.0.1" targetFramework="net46" />
  <package id="System.IdentityModel.Tokens.Jwt" version="4.0.4.403061554" targetFramework="net46" />
</packages>
```

After stepping through code I found the error happens on this line
`BotData userData = await stateClient.BotState.GetUserDataAsync(activity.ChannelId, activity.From.Id);`
in my Messages Controller shown below:
```
        public async Task<HttpResponseMessage> Post([FromBody]Activity activity)
        {
            if (activity != null && activity.Type == ActivityTypes.Message)
            {
                // Strip any @mentions
                Mention[] m = activity.GetMentions();
                for (int x = 0; x < m.Length; x++)
                {
                    if (m[x].Mentioned.Id == activity.Recipient.Id)
                    {
                        if (m[x].Text != null)
                        {
                            activity.Text = activity.Text.Replace(m[x].Text, "");
                        }
                    }
                }

                // Sends user's Id and Name to RootDialog Class
                StateClient stateClient = activity.GetStateClient();
                BotData userData = await stateClient.BotState.GetUserDataAsync(activity.ChannelId, activity.From.Id);
                userData.SetProperty<string>("UserId", activity.From.Id);
                userData.SetProperty<string>("Name", activity.From.Name);

                // send these values in the Context
                await stateClient.BotState.SetUserDataAsync(activity.ChannelId, activity.From.Id, userData);

                await Conversation.SendAsync(activity, () => new Dialogs.RootDialog());
            }
            else
            {
                await HandleSystemMessage(activity);
            }
            var response = Request.CreateResponse(HttpStatusCode.OK);
            return response;
        }
```

**Comment by nwhitmont** [comment]
@megancooper Looks like we are experiencing some issues with backend services right now. The team is investigating.

**Comment by megancooper** [comment]
@nwhitmont Okay, thanks

**Comment by nwhitmont** [comment]
@megancooper The incident has been resolved, bots should be back to normal activity now.
