### ISSUE TITLE
[Performance] Getting `Error: Refresh access token failed with status code: 400`

### ISSUE THREAD

**Issue by cesarvarela** [Microsoft/BotBuilder#3195]
## System Information
* SDK Language: NODE
* SDK Version: 3.8.4
* Development Environment: Bluemix Container

## Issue Description
Getting the following error in some of our bots: `Error: Refresh access token failed with status code: 400`
## Code Example
Different bots created at different tines, and all have the same error, I don't think this has to do with our code. 

## Actual Results
Bots don't respond to messages and throw the error mentioned above.

**Comment by jasonmayde** [comment]
I am also getting this issue. It just started about 30 minutes ago.

**Comment by nwhitmont** [comment]
@cesarvarela We are experiencing some slowness in our connector service which is affecting all bots, and all channels.  The team is actively investigating the issue.

**Comment by dan-cohn** [comment]
Same problem here. Not good!

**Comment by nwhitmont** [comment]
@cesarvarela @dan-cohn The incident has been resolved, bots should be back to normal activity now.
