### ISSUE TITLE
[Performance] Refresh access token failed with status code: 400 and  No tenant-identifying information found in either the request or implied by any provided credentials

### ISSUE THREAD

**Issue by Aashish-Amber** [Microsoft/BotBuilder#3197]
## System Information (Required)
* SDK Language:  NODE 
* SDK Version: 3.10.10
* Development Environment: AWS

## Issue Description
1. The bot is unable to connect and is giving error code 400

error: Refresh access token failed with status code: 400
## Code Example
When troubleshooting getting this response

curl -k /common/oauth2/v2.0/token -d "grant_type=client_credentials&client_id=***************&client_secret=***************&scope=https%3A%2F%2Fapi.botframework.com%2F.default"

{"error":"invalid_request","error_description":"AADSTS50059: No tenant-identifying information found in either the request or implied by any provided credentials.\r\nTrace ID: 26b3ec0b-d9ca-4794-9049-c3e6fe624a00\r\nCorrelation ID: 8a42d49d-35bb-4a08-b3e5-a874f25453b2\r\nTimestamp: 2017-07-25 18:59:41Z","error_codes":[50059],"timestamp":"2017-07-25 18:59:41Z","trace_id":"26b3ec0b-d9ca-4794-9049-c3e6fe624a00","correlation_id":"8a42d49d-35bb-4a08-b3e5-a874f25453b2"}

## Steps to Reproduce the Issue
 Try connecting your bot with any platform , send message to bot and see the logs

## Expected Behavior
The bot should connect and respond normally.

## Actual Results
error: Refresh access token failed with status code: 400
    at Request._callback (/home/ubuntu/multichannelchatbot/node_modules/botbuilder/lib/bots/ChatConnector.js:489:28)
    at Request.self.callback (/home/ubuntu/multichannelchatbot/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/ubuntu/multichannelchatbot/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/ubuntu/multichannelchatbot/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

**Comment by nwhitmont** [comment]
@Aashish-Amber Thanks for reporting. We are experiencing a service interruption and we've got multiple engineers looking into it. Will update you when we have more details.

**Comment by Aashish-Amber** [comment]
Thanks for the response , Hope it gets fixed soon.

**Comment by isabellacmor** [comment]
Fantastic! The folks at the OneWeek hackathon thank you :)

**Comment by advl03** [comment]
Same problem here. We are suffering this problem since 8 PM CEST. Can we help you with any kind of test or sending you any logs?
Environment: node.js. We have the development environment running on internal infrastructure at Spain and the production environment running on Azure (North Europe)

**Comment by joshftx** [comment]
This should be updated on the status page, perhaps? Azure Bot Service shows green right now, despite the "service interruption"
https://azure.microsoft.com/en-us/status/

**Comment by McBacker** [comment]
We all know that it is still in Preview, but, for those who have their Bots under BotFramework infraestructure... how do you explain this downtime to your customers?

**Comment by bilby91** [comment]
Same here, our bot stop working suddenly. We are using Slack and Teams and both are affected.

**Comment by sureshgururajan** [comment]
+1

**Comment by DmitryZemlyuk** [comment]
Same problem. Slack, Telegram, Skype version - error 400.

**Comment by YiMeChen** [comment]
Our certificate was expired and took me an hr to actually figure out this was the problem. Yes, same problems here.. 2 bots, all channels. Theres no indication on the Channels page either..

**Comment by YiMeChen** [comment]
seems to be back!

**Comment by DmitryZemlyuk** [comment]
Yes, I can see my bot is working correctly =) 
But how long it can work normally?

**Comment by nwhitmont** [comment]
The incident has been resolved, bots should be back to normal activity now.

**Comment by xjose97x** [comment]
My bot is still not replying?

**Comment by v46** [comment]
@stevengum97 / @nwhitmont  - Any further information on what caused this outage please? 

Any alternatives we, as users of the SDK could have pursued during the service interruption?

**Comment by premaarya** [comment]
My bots are working now ...

**Comment by xjose97x** [comment]
![Image of errors](https://preview.ibb.co/ej42Uk/Captura.png)

**Comment by xjose97x** [comment]
@nwhitmont

**Comment by EricDahlvang** [comment]
@xjose97x 

Please open a new issue.  (The underlying problem related to #3197 has been resolved.)

**Comment by xjose97x** [comment]
@EricDahlvang , the thing is that my bot was working fine until this issue appeared, and since then, it has not been solved.

**Comment by dan-cohn** [comment]
Mine are working again. @xjose97x did you try restarting your bot service? Perhaps it doesn't recover itself from errors (although my Node-based bots were fine).

**Comment by joshftx** [comment]
Works for me now.

**Comment by IanLawrence** [comment]
this is fixed for me

**Comment by xjose97x** [comment]
I apologize, I just found the issue. It made me get confused since the issue appeared along this one and was impossible for me to debug.

So, I changed the namespace and project name of my bot application. Apparently this made Azure app service believe there were multiple API controller endpoints somehow. And that's why the Bot Framework connector couldn't reach my bot application.
So even after cleaning my solution, recompiling, deleting bin and obj folders, etc it didn't work. What I had to do is delete the azure app service and create a new one, and voila!

Sorry for the inconveniences!

**Comment by IanLawrence** [comment]
I think there should be some kind of notification on https://dev.botframework.com/ when errors like this happen. It will stop folks deleting bots and generally doing a bunch of unnecessary things when all that was needed was to wait for MS to sort it out

**Comment by thulasipavankumar** [comment]
I am facing the same issue _"Refresh access token failed with status code: 400"_  from last 30min
