### ISSUE TITLE
[Question] How to use LUIS with WaterFall Dialog?

### ISSUE THREAD

**Issue by PrasadKosaraju** [Microsoft/BotBuilder#3198]
## System Information (Required)
* SDK Language: NODE
* SDK Version: 
* Development Environment:  AZURE_BOT_SERVICE

## Issue Description
I created a Water Fall Dialog model Bot. At one point of user response i want to use LUIS to capture different utterances user can say and then redirect to different dialog. Sample code attached here. In this Login Dialog when the user explain the issue with login(free-form text) I want to use capture that in LUIS instead of regular expression i used below.  Is there way i can map user response to LUIS intent directly?
## Code Example
bot.dialog('/PromptForLogin', [
    function (session) {
        builder.Prompts.text(session, 'Please explain the issue with your login');
	  },
   function (session, results) {
		
	 if(results.response.match(/login/gi)|| results.response.match(/failure/gi)||results.response.match(/access/gi)||results.response.match(/error/gi))
	   {
		    //session.send("Please make sure to use your email address and password. ");
			//session.conversationData.issue="Login Failure";
			session.beginDialog('/PromptForLoginFailure');
	   }

**Comment by dan-cohn** [comment]
I'm no expert, but have you tried using builder.Prompts.text and then passing the user's response to your LUIS recognizer? I am doing something similar, and it works well.

**Comment by stevengum97** [comment]
Have you taken a look at this [comment](https://github.com/Microsoft/BotBuilder/issues/2741#issuecomment-300946349)?  It demonstrates how to set up a custom prompt that uses LUIS. After the user responds, you can use a switch statement to change dialogs.

**Comment by stevengum97** [comment]
You can also do what @dan-cohn just mentioned if you're only planning on doing a one-off prompt that calls LUIS. LuisRecognizer has the static method [`recognize()`](https://github.com/Microsoft/BotBuilder/blob/master/Node/core/lib/botbuilder.d.ts#L3674) which you can use in your next waterfall step without having to instantiate a LuisRecognizer. 

e.g.

```js
function (session, results) {
  LuisRecognizer.recognize(results.response, process.env.LUIS_MODEL, 
    function (err, intents, entities, compositeEntities) {
      intents.forEach(function(intent) {
        switch (intent.intent) {
          case 'PromptForLogin':
            break;
        }
      });
  });
}
```

**Comment by PrasadKosaraju** [comment]
@dan-cohn : Can you please provide same code once

**Comment by PrasadKosaraju** [comment]
@stevengum97 : I tried above code. But some reason it throws me 'Oops. Something went wrong and we need to start over.' I don't see any error in console though. Do i need to define anything else

**Comment by PrasadKosaraju** [comment]
Finally after little change it's able to connect to LUIS. But for some reason any text utterance i use both intents are triggering. Can you please help if i'm missing something here. (LoginError and None are intents in my LUIS)

function (session, results) {
      builder.LuisRecognizer.recognize(results.response, process.env.LUIS_MODEL,
    function (err, intents, entities) {
        if(err){
                    console.log("Some error occurred in calling LUIS");
                  }
   	   intents.forEach(function(intent) {
        switch (intent.intent) {
          case'LoginError':
				session.beginDialog('/PromptForLoginFailure');
            break;
            case'None':
		      session.send('in None block');
            break;
        }
      });
  });
}

**Comment by dan-cohn** [comment]
Sample code (similar to Prasad's example):

```
        builder.Prompts.text('Tell me something...');
...
        (session, result, next) => {
            if (result.response) {
                builder.LuisRecognizer.recognize(session.message.text, process.env.LUIS_MODEL_URL, function (err, intents, entities) {
                    if (intents && intents[0] && intents[0].score > 0.5) {   // for example
                        switch (intents[0].intent) {
...
                        }
```

**Comment by stevengum97** [comment]
Sorry @PrasadKosaraju, you don't actually want to use `intents.forEach`; you should use what @dan-cohn used, which is `intents[0]`. This will prevent triggering every dialog.

```js
switch (intents[0].intent) {
  case 'LoginError':
    session.beginDialog('/PromptForLoginFailure');
    break;
  case 'None':
    ...
}
```

Also, instead of a switch statement, you could potentially just run `session.beginDialog(intents[0].intent);`.

**Comment by stevengum97** [comment]
@PrasadKosaraju were you able achieve the desired results for your bot?

**Comment by PrasadKosaraju** [comment]
@dan-cohn @stevengum97 : Thanks a lot. It helped out to resolve the issue

**Comment by stevengum97** [comment]
Awesome. Closing Issue.

**Comment by crisboarna** [comment]
Hi, is this not an inefficient manner to handle LUIS extraction ? As LUIS is called at every message by default when adding a recognizer, but you only get the intents and entities in the session parameter when in the first step of a waterfall, you have to call LUIS again every time you require entity extraction resulting in doubling of LUIS calls, doubling costs. Is this correct or is there a way to use the framework inbuilt recognizer results at other points in a waterfall step beside first one that I am missing ?

**Comment by stevengum97** [comment]
Hi @crisboarna, can you open a new issue and someone from the team will get back to you regarding this? Please make sure to include any sample code for your bot.
