### ISSUE TITLE
LuisDialog on method never triggers

### ISSUE THREAD

**Issue by Neabfi** [Microsoft/BotBuilder#32]
Hey, I have a very strange issue.
LuisDialog On method never triggers even if I have the good intent.

```javascript
var builder = require('botbuilder');
var model = 'https://api.projectoxford.ai/luis/v1/application...';
var dialog = new builder.LuisDialog(model);
var cortanaBot = new builder.TextBot();
cortanaBot.add('/', dialog);

dialog.on('builtin.intent.alarm.set_alarm', builder.DialogAction.send('Creating Alarm'));
dialog.onDefault(
  function(a, b) { if('builtin.intent.alarm.set_alarm' == b.intents[0].intent) console.log('ok')}
);
cortanaBot.listenStdin();
```
When I say 'Set an alarm' it shows 'ok' so the intent is good but it still calls onDefault method.

**Comment by Stevenic** [comment]
Can you make sure you have the latest version of the npm module. I fixed an issue with that this morning and published a new module. We're up to v0.6.4 now

**Comment by Neabfi** [comment]
It works, tanks !
