### ISSUE TITLE
[Question] How to broadcast a message to a list of all users who are using the Bot through different clients like FB/Slack/Skype?

### ISSUE THREAD

**Issue by Techdhim** [Microsoft/BotBuilder#3200]
## System Information (Required)
* SDK Language: C#
* SDK Version: 4.0 & More 
* Development Environment: Azure App Service 

## Issue Description

I have developed a bot & have hosted it on azure server & I am trying to access it through Facebook/Slack client. I want to log the activity information when the bot is added to the Facebook/Skype contact list.

## Code Example

[BotAuthentication]
    public class MessagesController : ApiController
    {
               public async Task<HttpResponseMessage> Post([FromBody]Activity activity)
        {
            if (activity.Type == ActivityTypes.Message)
            {
                await Conversation.SendAsync(activity, () => new CardsDialog());
            }
            else
            {
                this.HandleSystemMessage(activity);
            }

            var response = Request.CreateResponse(HttpStatusCode.OK);
            return response;
        }

        private Activity HandleSystemMessage(Activity message)
        {
            if (message.Type == ActivityTypes.DeleteUserData)
            {
                // Implement user deletion here
                // If we handle user deletion, return a real message
            }
            else if (message.Type == ActivityTypes.ConversationUpdate)
            {
                // Handle conversation state changes, like members being added and removed
                // Use Activity.MembersAdded and Activity.MembersRemoved and Activity.Action for info
                // Not available in all channels
            }
            else if (message.Type == ActivityTypes.ContactRelationUpdate)
            {
                // Handle add/remove from contact lists
                // Activity.From + Activity.Action represent what happened
            }
            else if (message.Type == ActivityTypes.Typing)
            {
                // Handle knowing tha the user is typing
            }
            else if (message.Type == ActivityTypes.Ping)
            {
            }

            return null;
        }
    }
## Steps to Reproduce the Issue
1. Create a bot & deploy it on azure & configure the bot so as to access it from FB/Skype/Slack
2. Add the bot to the contact list of FB/Slack/Skype.
3. The user info present in the activity needs to be logged into a DB Table to use it to send broadcast messages to all active users of the Bot.

## Expected Behavior

When the bot is added in the contact list of the FB/Skype account of the user the activity is to be logged into a DB so as to have a track of all the clients of all the users through which the bot is being accessed & use this userbase info to broadcast messages to all the users.

**Comment by amitbend** [comment]
You'll need to implement a sign-in with a single Identity connected through pointers to the platform specific user

**Comment by EricDahlvang** [comment]
Hi @Techdhim 

Logging activities can be achieved by implementing the IActivityLogger interface (or, use the Azure Extensions: https://github.com/Microsoft/BotBuilder-Azure ).  Here's a blog post that describes https://blog.botframework.com/2017/05/05/Saving-Bot-Actions-On-Azure-Sql-Server/ how to implement IActivityLogger using Sql Server.

Then, you can use the information stored by IActivityLogger to proactively message all of your users.  Here's some documentation on proactive messages in dotnet:
https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-proactive-messages  And here are some sample projects related to proactive messages: https://github.com/MicrosoftDX/botFramework-proactiveMessages

I hope this helps.
