### ISSUE TITLE
[LUIS] Pre-built Entities builtin.datetimeV2.daterange doesn’t exist in the selected application.

### ISSUE THREAD

**Issue by mukeshzt** [Microsoft/BotBuilder#3202]
## System Information  
* SDK Language: node.js, LUIS, cognitive-services
* SDK Version: 	botbuilder@3.8.4
* Development Environment: LOCALHOST, production

## Issue Description

I'm working on add utterance to LUIS application using cognitive services (LUIS Programmatic API) [Add label.](https://dev.projectoxford.ai/docs/services/5890b47c39e2bb17b84a55ff/operations/5890b47c39e2bb052c5b9c08)

If you check my luis.ai I have already added the pre built entity called datetimeV2
![prebuilt](https://user-images.githubusercontent.com/23474222/28617182-fe7b1350-721c-11e7-9643-defb45c034f7.png)

## Code Example

```
curl -v -X POST "https://westus.api.cognitive.microsoft.com/luis/api/v2.0/apps/{appId}/versions/{versionId}/example"
-H "Content-Type: application/json"
-H "Ocp-Apim-Subscription-Key: {subscription key}"
--data-ascii "{body}"
```

## Steps to Reproduce the Issue
1. Enter the utterance text label to my skype client. (Give me cxxxxxxr order xxxxxx for xxx xxx Chxxse from 02/05 to 05/06)
2. Pass to end point URL to know the best match intent and entity.
3. Validate required data and again pass to LUIS Programmatic API Add label
```json
{ "text":"Give me cxxxxxxr order report for xxx xxx Chxxse from 02/05 to 05/06",
  "intentName":"showxxxxxx",
  "entityLabels" :[
    {"entityName":"hierarchy",
    "startCharIndex":8,
    "endCharIndex":21},
    {"entityName":"builtin.datetimeV2.daterange",
    "startCharIndex":49,
    "endCharIndex":67},
    {"entityName":"builtin.number",
    "startCharIndex":54,
    "endCharIndex":58},
    {"entityName":"builtin.number",
    "startCharIndex":63,
    "endCharIndex":67},
    {"entityName":"comxxxyxxx",
    "startCharIndex":34,
    "endCharIndex":47}
  ]
}
```

4. When I send request it return me an error. 

## Expected Behavior

It should add the utterance for showxxxxxx intent and assign the entity. 

## Actual Results

error message showing me with status code 400

**Error**: The entity extractor builtin.datetimeV2.daterange doesn’t exist in the selected application

**Comment by stevengum97** [comment]
Can you try doing this [GET request](https://dev.projectoxford.ai/docs/services/5890b47c39e2bb17b84a55ff/operations/5890b47c39e2bb052c5b9c18) just to verify that the entity is on the model via the authoring API? That aside, I haven't repro'd this yet, but I'm wondering if it might be an issue with assigning its child, `"daterange"`.  Have you tried just using `"builtin.datetimeV2"`?

**Comment by mukeshzt** [comment]
@stevengum97  Thanks for your reply. I was surprised because It was working previously but suddenly it is giving me an error.

I followed your mentioned steps and results are follows: 

I have made two request one which you mention [GET request](https://dev.projectoxford.ai/docs/services/5890b47c39e2bb17b84a55ff/operations/5890b47c39e2bb052c5b9c18) and another one to know project [Assign pre built Entity](https://westus.dev.cognitive.microsoft.com/docs/services/5890b47c39e2bb17b84a55ff/operations/5890b47c39e2bb052c5b9c17)

1.  [GET request](https://dev.projectoxford.ai/docs/services/5890b47c39e2bb17b84a55ff/operations/5890b47c39e2bb052c5b9c18)
it returns me all the pre built entity. 
![allprebuilt](https://user-images.githubusercontent.com/23474222/28654140-9d0e5bf2-72af-11e7-87ba-29ffb24219c8.png)

2. [Assign pre built Entity](https://westus.dev.cognitive.microsoft.com/docs/services/5890b47c39e2bb17b84a55ff/operations/5890b47c39e2bb052c5b9c17)
This API returns me my project assign entity only 
![onlyprebuilt](https://user-images.githubusercontent.com/23474222/28654143-a401a9d2-72af-11e7-85ae-0801a0e6d94a.png)

3. As you mention I pass the builtin.datetimeV2
```

{ "text":"Give me cxxxxxxr order report for xxx xxx Chxxse from 02/05 to 05/06",
  "intentName":"showxxxxxx",
  "entityLabels" :[
    {"entityName":"hierarchy",
    "startCharIndex":8,
    "endCharIndex":21},
    {"entityName":"builtin.datetimeV2",
    "startCharIndex":49,
    "endCharIndex":67},
    {"entityName":"builtin.number",
    "startCharIndex":54,
    "endCharIndex":58},
    {"entityName":"builtin.number",
    "startCharIndex":63,
    "endCharIndex":67},
    {"entityName":"comxxxyxxx",
    "startCharIndex":34,
    "endCharIndex":47}
  ]
}

```
Still showing me the same error. 

**Error**: The entity extractor builtin.datetimeV2 doesn’t exist in the selected application

![enitityerror](https://user-images.githubusercontent.com/23474222/28654606-3e0ffa6c-72b3-11e7-9b16-4710a3da43b2.png)

**Comment by stevengum97** [comment]
So this was a mistake on my part, but when labeling via Authoring API users are _not_ to use `"prebuilt"` when using prebuilt entities. Instead you should just label as `"datetimeV2"`, `"number"`, etc.

Here is an example using the JSON you provided in your last comment:
```json
{ "text":"Give me cxxxxxxr order report for xxx xxx Chxxse from 02/05 to 05/06",
  "intentName":"showxxxxxx",
  "entityLabels" :[
    {"entityName":"hierarchy",
    "startCharIndex":8,
    "endCharIndex":21},
    {"entityName":"datetimeV2",
    "startCharIndex":49,
    "endCharIndex":67},
    {"entityName":"number",
    "startCharIndex":54,
    "endCharIndex":58},
    {"entityName":"number",
    "startCharIndex":63,
    "endCharIndex":67},
    {"entityName":"comxxxyxxx",
    "startCharIndex":34,
    "endCharIndex":47}
  ]
}
```

**Comment by mukeshzt** [comment]
@stevengum97  It works :+1:  

Thanks for your reply. I'm going to close the issue.
