### ISSUE TITLE
[LUIS] Integrating Bot with Channels - 400 Bad Request

### ISSUE THREAD

**Issue by mahmoudahmedarafa** [Microsoft/BotBuilder#3203]
I have deployed my bot to the cloud and using LUIS SDK. I made sure that my bot is working properly (the bot replies to each user message) before deployment.

1. I tried my bot on "Web Chat":
![web chat](https://user-images.githubusercontent.com/22199398/28621308-ca3a5508-7210-11e7-8ba4-c42e5abed141.PNG)
The deployed bot accepts custom intents: "Hi", "Cairo, Egypt" LUIS Intents. the app doesn't accept "Beef" Intent. Actually the bot doesn't accept the very first message in the conversation (I entered "Hi" twice in order to make him reply.)

2. I made sure that all intents connect to LUIS successfully (including "Beef" Intent on my local host on my machine.

3. I tried using ngrok to debug my bot with both commands: 'ngrok http [port]' and 'ngrok http [port] -host-header="localhost:[port]"﻿', yet I am getting a "400 Bad Request".
![capture](https://user-images.githubusercontent.com/22199398/28621335-e3656b58-7210-11e7-9e5f-beeff79b7e60.PNG)

So how can the external client post his message successfully through the channels?

**Comment by nwhitmont** [comment]
@mahmoudahmedarafa 
1. Are you using .NET or Node SDK?
2. Can you export your LUIS model as JSON and post it here?

To export your LUIS model, go to https://luis.ai - then go to your list of LUIS apps and click the `{ }` curley braces icon on the right-hand side of the page as shown below.
![export model to json - luis my apps](https://user-images.githubusercontent.com/3075047/28628022-4bbba96c-71d8-11e7-94a4-5bb324f4e194.png)

**Comment by mahmoudahmedarafa** [comment]
1. .NET
2. I used Skype and Slack where the same problem exists.
3. I uploaded the JSON Model as JPG.
![mcdonalds bot](https://user-images.githubusercontent.com/22199398/28663149-cc6b59e2-72bc-11e7-8fc8-901f564834c2.jpg)

**Comment by nwhitmont** [comment]
@mahmoudahmedarafa I cannot see your JSON code. Please post your LUIS model JSON as plain text, not an image.

**Comment by mahmoudahmedarafa** [comment]
@nwhitmont Sorry for late reply.
I thought that the problem could be from LUIS, yet there was a problem in my code of opening some text file. The error was misleading and I couldn't debug my bot throw ngrok locally. I knew the error by making a try catch statement and making the bot replying with the exception message:

```
try
{
     // Your logic
}
catch(Exception Ex)
{
     return new Activity[] { activity.CreateReply(Ex.Message) };
}
```

**Comment by nwhitmont** [comment]
Thanks for the update @mahmoudahmedarafa
