### ISSUE TITLE
[FB Messenger] How to create a persistent menu?

### ISSUE THREAD

**Issue by xjose97x** [Microsoft/BotBuilder#3205]
## System Information (Required)
* SDK Language: .NET/C#
* SDK Version: 3.8.5

Hello! I was wondering if someone was able to create a Facebook persistent menu by adding the json required through the channel data of the reply.

I've tried with no success.

Thanks!

**Comment by nrobert** [comment]
@xjose97x , I think you are not going in the right direction.
If you want to create a persistent menu in Facebook, you have to call Facebook API (make a POST with cURL, Postman or another tool) with the required json, not put this json in a channel data of a message from the bot
