### ISSUE TITLE
[Skype for Business] Cannot send attachements (images) to Bot

### ISSUE THREAD

**Issue by RemiChambard** [Microsoft/BotBuilder#3208]
Hi,

It seems that as for now we can't send attachments from the Skype for Business client to a Bot. Can you confirm that the feature is not yet available ? And if possible, tell us if the feature will be implemented soon ?

Thanks

**Comment by nwhitmont** [comment]
@RemiChambard Skype for Business channel integration for Bot Framework is currently in developer preview state. As such, attachments are not yet supported in this channel. 

For more information about Skype for Business channel on Bot Framework, including current feature support, check out this page:
https://msdn.microsoft.com/en-us/skype/Skype-For-Business-Bot-Framework/docs/overview#feature-support

**Comment by sinhautkarsh2014** [comment]
Hi, any estimate on when the support for attachments would come up?
