### ISSUE TITLE
attachments

### ISSUE THREAD

**Issue by rlilov** [Microsoft/BotBuilder#321]
Sorry for cross posting, i posed similar question on stackoverflow, but added azure blob tag and this may confused the people

file attached from user in my chat bot in BotEmulator is posted with below URL:
http://localhost:9000/content/8a684db8?file=IMG-20160503-WA0002.jpg, where i have the filename that i can use in my further processing

file attached by user when bot is deplyoed in production gets posted like this:
https://bcattachmentsprod.blob.core.windows.net/635994216000000000/3DOUR10S0J2IL4
here i am loosing the filename and i need this filename for further processing in my bot logic

is this something that can be considered to be added in further releases or the posting URL structure will remain like this, than i can eventually invent filenames and guess from contentType the correct extension?

**Comment by jameslew** [comment]
Right now the REST API doesn't support passing the file name, just the ContentType and URL for simple attachments.  There is a card style attachment that collects more info that you could use depending on what code you have on the other end, but the emulator doesn't currently support it.

**Comment by tomlm** [comment]
The contenttype is accurate on the url, we don't plan on putting the filename in the url
