### ISSUE TITLE
[Question] Receiving multiple attachments in one request in Telegram channel

### ISSUE THREAD

**Issue by imangoodarzi** [Microsoft/BotBuilder#3210]
## System Information (Required)
* SDK Language: .NET/C#
* SDK Version: 3.8.1
* Development Environment: AZURE_APP_SERVICE

## Issue Description
I have a bot that is enabled in both Messenger and Telegram channels and it is supposed to receive multiple attachments from the user in one message. In Messenger, everything works perfectly and one message is received that contains multiple attachment records, however looks like Telegram is sending multiple messages each containing one attachment. Wanted to ask if this is something implemented in the bot framework's end (can be addressed?) or it is the way that Telegram is behaving?

**Comment by nwhitmont** [comment]
@imangoodarzi This behavior is defined by Telegram, and cannot be configured via Bot Framework.
