### ISSUE TITLE
[Question] What is the Hero Card Attachment limit for a message in MS Teams?

### ISSUE THREAD

**Issue by megancooper** [Microsoft/BotBuilder#3212]
Sorry for the question; I tried to find this in documentation online but could not find it. I know there is a hero card attachment limit for Teams because I was getting an error on the botframework website every so often saying I exceeded it, but I can't find out what the max number of attachments allowed for a message in Teams actually is. I'd like to add checks in my code so that I don't exceed the limit. 

_My code is simple. I read from a database and display a # of hero cards; this # depends on the amount of information pulled from said database:_

```
var msg = context.MakeMessage();
var HeroCardList = new List<Attachment>();
HeroCardList = getDatabaseInfo("name", "date");
foreach (Attachment card in HeroCardList) {
    msg.Attachments.Add(card);
}
await context.PostAsync(msg);
```

Thanks for the help.

**Comment by JasonSowers** [comment]
@megancooper  Hi are you getting different behavior in the emulator or other channels?  Is this only for teams?  What type of numbers are we talking about for attachments?  10's 100's 1000's?

**Comment by JasonSowers** [comment]
Additionally I am unable to get more than 7 hero card attachments to display on MS teams.  Is this the same number you are noticing failure at?

**Comment by megancooper** [comment]
@JasonSowers in the 10's no more than 15. And yes 7 is the number of cards it seemed to give me an exception for. Is this just an MS Teams thing/quirk?

**Comment by JasonSowers** [comment]
My guess is yes since we are both seeing the same number, we will have to wait for someone from the MS teams team to confirm.

**Comment by JasonSowers** [comment]
@megancooper did this resolve itself?

**Comment by megancooper** [comment]
@JasonSowers I resolved it. I'm guessing 7 is the limit, so I just added code to make sure no message went over 7 attachments:
```
var msg = context.MakeMessage();
msg.AttachmentLayout = AttachmentLayoutTypes.Carousel;

var messages = new List<IMessageActivity>();

int cardCount = 0;      // Teams only allows 7 cards per carousel message

var lastList = cards.Last();
var lastCard = lastList.Last();


foreach (List<Attachment> list in cards)
{
     foreach (Attachment card in list)
     {
          bool resetList = false;
          cardCount++;
          if (cardCount == 7)
          {
               cardCount = 0;
               messages.Add(msg);
               msg = context.MakeMessage();
               msg.AttachmentLayout = AttachmentLayoutTypes.Carousel;
               resetList = true;
          }
          msg.Attachments.Add(card);

        // Add last few messages
        if (card.Equals(lastCard) && !resetList)
        {
            messages.Add(msg);
        }
    }
}

return messages;

```
