### ISSUE TITLE
How we can change the shape of a carousel hero card into round shape.

### ISSUE THREAD

**Issue by dijotcr222** [Microsoft/BotBuilder#3213]
var card = new builder.HeroCard(session);
                      card.title("DID YOU MEAN :");
                      card.buttons([
                      builder.CardAction.imBack(session, Array[0],Array[0])                      ]);
                      
                      var msg = new builder.Message(session)
                     .attachmentLayout(builder.AttachmentLayout. carousel)
                     .attachments([card]);
                     session.send(msg);

**Comment by xjose97x** [comment]
I am not aware of there being a way to change the shape of a hero card. After all Hero Cards are rendered by the channel (Facebook, Skype, Slack, etc).
Perhaps you could make something for directline (webchats) in which you have total control in how to display your messages.

**Comment by JasonSowers** [comment]
This is not currently a feature, a Jose says, you might be able to hack something together by modifying the webchat control.
