### ISSUE TITLE
[Question] Skype not showing Attachments

### ISSUE THREAD

**Issue by xjose97x** [Microsoft/BotBuilder#3214]
## System Information (Required)
* SDK Language: .NET/C#
* SDK Version: 3.9.0

Hello! 
When I'm sending an attachment (VideoCard, AnimationCard, AudioCard, etc), I have to add in the MediaUrl a Profile field, otherwise, Skype Android (and maybe ios) crashes. However, if I add this profile field (i either put "sd", or "hd") it makes the attachment not load.

If I do not add this profile field, it renders the attachment perfectly on Skype Desktop, but crashes android app.

Has anyone found a workaround?

Thanks a lot!

**Comment by nwhitmont** [comment]
There are known issues with audio/video card not working on Skype mobile. We're investigating.

**Comment by xjose97x** [comment]
Thanks @nwhitmont !

I do not want to hurry, but is there any ETA?

Just wondering.

**Comment by nwhitmont** [comment]
@xjose97x I don't have a specific ETA, but I do know the Skype mobile team is working on it.

**Comment by xjose97x** [comment]
Alright. Thank you Nils!

**Comment by JasonSowers** [comment]
please continue the conversation here is needed

**Comment by varunreddycs** [comment]
Is there a way to send files or documents as attachments from Bot to User in Skype.
