### ISSUE TITLE
[Question] onSelectAction of cancelAction is called before user has a chance to confirm

### ISSUE THREAD

**Issue by dan-cohn** [Microsoft/BotBuilder#3215]
## System Information (Required)
* SDK Language: NODE
* SDK Version: 3.9.0
* Development Environment: LOCALHOST

## Issue Description
I'd like to perform some behavior (e.g., canceling a timer) when a particular dialog is cancelled. I'm using the `cancelAction` to trigger the cancellation.

I don't see a way to run custom code upon cancellation other than with the `onSelectAction` option. However, this function is called as soon as the user says "cancel" even though I have a `confirmPrompt`.

## Code Example
```js
bot.dialog('/intent', intent.dialog)
    .cancelAction('cancelIntent', 'Cancelled.', {
        matches: cancelKeywords,
        confirmPrompt: 'Are you sure you want to cancel?',
        onSelectAction: function (session, args, next) { doSomething; }
    });
```

## Steps to Reproduce the Issue
1. Start dialog
2. Send 'cancel' to the bot
3. Do not confirm

## Expected Behavior
According to the documentation, the `onSelectAction` "lets you customize the behavior of an action. For instance you could clear the dialog stack before the new dialog is started..." This implies that the action has actually been triggered. If the user hasn't confirmed the action, then I most certainly would not want to clear the dialog stack. Hence, I think this is a bug.

If this is the intended behavior, then please tell me how I can customize the cancellation behavior (when the dialog is actually canceled).

## Actual Results
`onSelectAction` is called before the user has a chance to respond yes or no to the confirmation prompt.

**Comment by dan-cohn** [comment]
The more I think about this, the more I'm convinced it's a bug, not a "question."  The current API behavior isn't useful to anybody. I'd be grateful to learn of a workaround or plan for resolving the issue.

Thanks,
Dan

**Comment by nwhitmont** [comment]
@Stevenic thoughts?

**Comment by dan-cohn** [comment]
Any update on this?

**Comment by nwhitmont** [comment]
@dan-cohn I'm unable to reproduce the issue using only the code snippet. Can you provide a complete working example that reproduces the issue? Thx

**Comment by mpicciolli** [comment]
`// This loads the environment variables from the .env file
var builder = require('botbuilder');
var restify = require('restify');

// Setup Restify Server
var server = restify.createServer();
server.listen(process.env.port || process.env.PORT || 3978, function () {
    console.log('%s listening to %s', server.name, server.url);
});

var useEmulator = (process.env.NODE_ENV == 'development');

var connector = useEmulator ? new builder.ChatConnector() : new builder.ChatConnector({
    appId: process.env.MICROSOFT_APP_ID,
    appPassword: process.env.MICROSOFT_APP_PASSWORD
});
server.post('/api/messages', connector.listen());

// Bot setup
var bot = new builder.UniversalBot(connector, function (session) {
    session.beginDialog("dialog");
});

bot.dialog("dialog", [
    function (session) {
        builder.Prompts.text(session, "Hello... What's your name?");
    },
    function (session, results) {
        session.userData.name = results.response;
        builder.Prompts.number(session, "Hi " + results.response + ", How many years have you been coding?");
    },
    function (session, results) {
        session.userData.coding = results.response;
        builder.Prompts.choice(session, "What language do you code Node using?", ["JavaScript", "CoffeeScript", "TypeScript"]);
    },
    function (session, results) {
        session.userData.language = results.response.entity;
        session.send("Got it... " + session.userData.name +
            " you've been programming for " + session.userData.coding +
            " years and use " + session.userData.language + ".");
    }
]).cancelAction('cancelIntent', 'Cancelled.', {
    matches: /^cancel/i,
    confirmPrompt: 'Are you sure you want to cancel?',
    onSelectAction: function (session, args, next) {
        session.send("onSelectAction");
     }
});
`

**Comment by mpicciolli** [comment]
This code reproduce this issue : https://gist.github.com/mpicciolli/8a867015c880a76dc8b4d33f186ba21e

**Comment by dan-cohn** [comment]
If you need another code sample, I can work one up for you. However, I'm not sure what's so complicated about this. The issue is simple: the `onSelectAction` for a `cancelAction` gets called immediately after the user says "cancel" before the user confirms the cancellation. I believe it was implemented incorrectly from day one. It shouldn't trigger the onSelectAction until the user has confirmed (unless there's no `confirmPrompt`).

**Comment by nwhitmont** [comment]
thanks @mpicciolli for the code example 👍

**Comment by nwhitmont** [comment]
@dan-cohn The issue here is that you're not calling `next()` at the end of your `.onSelectAction()` code.

When I added, the call to `next()`, it prompts the user to confirm the cancel action as expected. 

```js
bot.dialog("dialog", [
    function (session) {
        builder.Prompts.text(session, "Hello... What's your name?");
    },
    function (session, results) {
        session.userData.name = results.response;
        builder.Prompts.number(session, "Hi " + results.response + ", How many years have you been coding?");
    },
    function (session, results) {
        session.userData.coding = results.response;
        builder.Prompts.choice(session, "What language do you code Node using?", ["JavaScript", "CoffeeScript", "TypeScript"]);
    },
    function (session, results) {
        session.userData.language = results.response.entity;
        session.send("Got it... " + session.userData.name +
            " you've been programming for " + session.userData.coding +
            " years and use " + session.userData.language + ".");
    }
]).cancelAction('cancelIntent', 'Cancelled.', {
    matches: /^cancel/i,
    confirmPrompt: 'Are you sure you want to cancel?',
    onSelectAction: function (session, args, next) {
        session.send("onSelectAction");
        next(); // <--- call next() here
     }
});
```
<img width="1440" alt="screen shot 2017-08-28 at 12 58 24 pm" src="https://user-images.githubusercontent.com/3075047/29791102-a6c142e0-8bf0-11e7-8ff3-17a1587a2d66.png">

**Comment by dan-cohn** [comment]
I'm not sure if you understand my concern (which may be different from @mpicciolli's).  I want to know when the user has actually cancelled.  Since the selectAction gets called immediately, and then after next() the user is prompted to confirm, I have no way of running some code when the user confirms the cancellation.  Perhaps onSelectAction isn't what I'm looking for, but so far I haven't found a way to execute specific code when a cancel actually happens (i.e., after the user says yes).

**Comment by dan-cohn** [comment]
I also want to refer back to the documentation which says the onSelectAction "lets you customize the behavior of an action. For instance you could clear the dialog stack before the new dialog is started..."  Why would I want to clear the dialog stack BEFORE asking the user to confirm?  Suppose he/she says no.  It's too late if I've already cleared the stack.

What I want is a way to execute code AFTER the confirmation.  How would I do that?

**Comment by mpicciolli** [comment]
Sorry for the misunderstanding.

You can run this code https://gist.github.com/mpicciolli/a3fdb4c1471d903e8c7ea40999e7919b.

That's what you want ?

**Comment by dan-cohn** [comment]
@mpicciolli Thanks for suggestion! I can use an outer dialog to catch cancellation of an inner dialog. It works great.

@nwhitmont I still feel there's a deficiency with the onSelectAction method or at least the documentation for it. It doesn't get called when the user actually cancels, it gets called when the user requests cancellation and before s/he confirms.
