### ISSUE TITLE
[Question] Skype Bot unable to join group chats (was able to before)

### ISSUE THREAD

**Issue by Rishi321** [Microsoft/BotBuilder#3216]
Originally posted as 
https://stackoverflow.com/questions/45346475/skype-bot-unable-to-join-group-chats-was-able-to-before

## System Information (Required)
* SDK Language: ReST API
* SDK Version: -
* Development Environment: LOCALHOST, AZURE_BOT_SERVICE

## Issue Description
I have a skype bot which was working fine and was able to join and interact in Group Calls Now (July 27th) it seems to have stopped working

If I try to add the bot to a Group Call I get the initial callback. But my Answer Action does not seem to get the subsequent callback from the Skype Channel. Note: The call is successfully joined if it's only 1:1, not a Group Call.

I have Group Messaging "on". (Since it was working earlier) I have tried this on our Production Bot, QA Bot, and even a bot for my local development. All Group Calls have ceased on all (different) bots. I have tried calling the Bot 1:1, successfully, and then adding somebody to the conversation. This also does not work as the third person is unable to join the call (no reason specified).

Has this functionality been removed entirely?

## Steps to Reproduce the Issue
1. Create a group call on a skype client
2. Add Bot
3. Bot does not answer

## Expected Behavior
Answer Action should lead to the webhook being called. Hence letting the Bot answer the call.

## Actual Results
No webhook callback initiated after responding with a Answer Action
(Only in a group call)

**Comment by nwhitmont** [comment]
@Rishi321 What is your bot name, bot handle and App ID as you registered the bot in the Bot Portal at https://dev.botframework.com?

**Comment by Rishi321** [comment]
Bot Name: Enfold Recorder
Bot Handle: EnfoldRecorder
APP ID: 7b2811d2-883d-4f83-bdc6-ee519e6b56b9

**Comment by Rishi321** [comment]
@nwhitmont Any update?

**Comment by JasonSowers** [comment]
@Rishi321 does it work when you  @ mention the bot?

**Comment by Rishi321** [comment]
@nwhitmont anything? The group calls are still not working.

**Comment by MalarGit** [comment]
@Rishi321 Bots in group chats are still allowed but bots in calling has been disabled since end of July because of privacy concerns.

**Comment by nwhitmont** [comment]
relates to: https://github.com/Microsoft/BotBuilder-RealTimeMediaCalling/issues/22
