### ISSUE TITLE
[Cards Customization] Removing tax and total in receipt card?

### ISSUE THREAD

**Issue by RaoVenka** [Microsoft/BotBuilder#3217]
Hi Team ,

I have created one Receipt Card like to display the key value pairs one by one in the card.

In emulator it's working fine.

Below is the screenshot for the same.

![image](https://user-images.githubusercontent.com/28774238/28715928-21af3eae-73b8-11e7-9a08-f1982341197a.png)

Below is the code for created Receipt-card.  👍 
```cs
 var receiptCard = new ReceiptCard
                {
                    Title = "View Order History",
                    Facts = new List<Microsoft.Bot.Connector.Fact> { new Microsoft.Bot.Connector.Fact("ORDER NUMBER :", Datumvieworder.orderid), new Microsoft.Bot.Connector.Fact("STATUS :", Datumvieworder.status), new Microsoft.Bot.Connector.Fact("ORDER DATE :", DateTime.Parse(Datumvieworder.orderdate).ToShortDateString()), new Microsoft.Bot.Connector.Fact("TOTAL :", Datumvieworder.grand_total) },
                };
                reply.Attachments.Add(receiptCard.ToAttachment());
                await context.PostAsync(reply);
}
```
But the same in i have checked in web chat using i frame , Total and Tax fields also automatically added in Receipt-card.I don't want to display the tax and total.

Below is the screen shot .

![image](https://user-images.githubusercontent.com/28774238/28716019-8d933bde-73b8-11e7-97f4-657a7df3f4db.png)

Could you please let me know how to remove Total and Tax fields in receipt card and as well as pls let me know whether Skype,Facebook and Microsoft Teams channels  supports receipt card.

Thanks & Regards ,
Venkateswara

**Comment by EricDahlvang** [comment]
@RaoVenka 

Thank you for reporting this.  A pull request has been added to the BotFramework-WebChat repo to fix this issue.

The difference you're seeing between the Emulator and the iframed webchat is due to the fact that a previous version of the webchat control is embedded inside the Emulator.

**Comment by JasonSowers** [comment]
please reopen if needed

**Comment by Daddymarto01** [comment]
Was this issue ever fixed? I am using facebook channel and seems the same issue is here. I do not want to see Tax and Shipping details. All i need is Total and the rest ive customized. Is there a way one can remove the unwanted from displaying? I also want to have my own currency but seems the receipt card has been customized to display $ only.
