### ISSUE TITLE
[Question] LUIS error: "Response status code does not indicate success: 410 (Gone)"?

### ISSUE THREAD

**Issue by seca23** [Microsoft/BotBuilder#3218]
## System Information (Required)
* SDK Language: C#
* SDK Version: 3.9.0
* Development Environment: LOCALHOST, AZURE_BOT_SERVICE, AZURE_APP_SERVICE

## Issue Description
When calling a LuisDialog in the MessageController, I am all of a sudden intermittently getting the following error: "Response status code does not indicate success: 410 (Gone)."

When checking application insights, I can see that the westus.api.cognitive.microsoft.com returns a dependency result code of 410

## Code Example
```await Conversation.SendAsync(activity, () => new MyLuisDialog());```

**Comment by nwhitmont** [comment]
@seca23 For reference, what API endpoint is your app calling when it hits the error? Also, what is your LUIS App ID?

**Comment by seca23** [comment]
Hi Nils

Just to clarify, I only get the above mentioned issue when I call a dialog that connects to Luis. For all other dialogs that do not inherit from LuisDialog, but IDialog, I have no issues.

In application insights, I saw that the full URL that our app is calling, that returns the 410 error, is https://westus.api.cognitive.microsoft.com:443/luis/v2.0/apps/<my modelid>?subscription-key=<my subscription key>q=Hi&log=True. 

My app id is 7e44beca-c35d-49f0-adcf-7eb3f16d9f83

Thanks

**Comment by seca23** [comment]
Hi Nils

It appears as if we are no longer experiencing this issue.

Many Thanks

**Comment by EricDahlvang** [comment]
@seca23 

Thanks for reporting this.  Good to hear you are no longer experiencing the issue.  Please open a new issue if you experience any more problems.

**Comment by nwhitmont** [comment]
Thanks for the update @seca23
