### ISSUE TITLE
[Question] Adaptive card is not supported in Skype and FB channel?

### ISSUE THREAD

**Issue by RaoVenka** [Microsoft/BotBuilder#3219]
Hi Team,

I am using adaptive card in a sample application in microsoft bot framework but it only works in Web Chat. In any other channels like Skype this adaptive card is not rendering. Even in Facebook only the card text(Button and label text) is coming instead of any other control like HTML textbox button.

As per below link, it says that Adaptive card is supported in Skype but it is not showing now.
http://adaptivecards.io/visualizer/?card=/explorer/cards/Input.ChoiceSet.json

Could you please let us know as of now Adaptive card is supported in Skype or not ? If yes it will be grateful if anyone can provide any sample code and Skype channel screen shot for showing adaptive card appearance.

Please find below the appearance of FB and Emulator Adaptive card images:
FB Image:
![fbimage](https://user-images.githubusercontent.com/28774238/28720558-219969e0-73cb-11e7-85ce-f1b8fddd5c69.PNG)

Emulator Image:
![emulator image](https://user-images.githubusercontent.com/28774238/28720572-35d33db4-73cb-11e7-9d19-edfff7ac8a9d.PNG)

Thanks
Venkat

**Comment by megancooper** [comment]
[https://github.com/Microsoft/BotBuilder/issues/2801](This post says that Adaptive cards in not yet a supported attachment for Skype, but is coming soon).

**Comment by nwhitmont** [comment]
@megancooper Thanks!

**Comment by nwhitmont** [comment]
@RaoVenka Not currently supported in Skype, but coming soon!

You can find the offical channel support matrix here: https://docs.microsoft.com/en-us/adaptive-cards/get-started/bots#channel-status
