### ISSUE TITLE
quit command

### ISSUE THREAD

**Issue by rlilov** [Microsoft/BotBuilder#322]
since the last release, typing "quit" with intention to exit the chat does not seem to work
i get Internl server error. (using c#)

**Comment by chrimc62** [comment]
This is most likely because you are not handling the FormCanceledException.  If you are doing a chain, you need to use DefaultIfException to swallow it.

**Comment by vovanb** [comment]
I got 
`  "text": "Exception: Microsoft.Bot.Builder.FormFlow.FormCanceledException`1[Microsoft.Bot.Sample.AnnotatedSandwichBot.SandwichOrder]: Form quit.\r\n   at Microsoft.Bot.Builder.FormFlow.FormDialog`1.<MessageReceived>d__14.MoveNext() in C:\\PhoneBook\\BotBuilder-master\\CSharp\\Library\\FormFlow\\FormDialog.cs:line 499\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at Microsoft.Bot.Builder.Dialogs.Internals.DialogTask.ThunkResume`1.<Rest>d__4.MoveNext() in C:\\PhoneBook\\BotBuilder-master\\CSharp\\Library\\Dialogs\\DialogTask.cs:line 120\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at Microsoft.Bot.Builder.Internals.Fibers.Wait`2.<Microsoft-Bot-Builder-Internals-Fibers-IWait<C>-PollAsync>d__19.MoveNext() in C:\\PhoneBook\\BotBuilder-master\\CSharp\\Library\\Fibers\\Wait.cs:line 247\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at 
`
using standard sample AnnotatedSandwichBot
Where I need to catch exception to prevent sending it from Bot after 
You quit on Sandwich--maybe you can finish next time!
