### ISSUE TITLE
[Feature Request] Add support for channel events in Slack

### ISSUE THREAD

**Issue by bilby91** [Microsoft/BotBuilder#3221]
## System Information (Required)
* SDK Language: Node.js
* SDK Version: 3.8.4
* Development Environment:  localhost, AWS

## Issue Description
Their are a lot of events that are not being sent to the bot when some actions happen inside a channel in slack. The following events are not being sent and would be really helpful.

From [Slack's events api](https://api.slack.com/events)

- channel_rename 
- channel_archived (this is being "sent". The problem is that this events can be recognized only because the slackbot sends a message to the conversation)
- channel_unarchive
- channel_deleted

For example, Teams sends all this events under `conversationUpdate` type activity. I think all this previously mentioned events can be forwarded to the bot under the same activity type and introspection can be done in the `sourceEvent` to understand the action.

**Comment by bilby91** [comment]
For anyone interested in handling this events using the botbuilder stack take a look at this extension we created.

https://github.com/suttna/botbuilder-slack-extension

**Comment by nwhitmont** [comment]
@bilby91 cool! 👍

**Comment by benbrown** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
