### ISSUE TITLE
If running a locally hosted bot with Direct Line integration, do I need to open more than one port to the internet?

### ISSUE THREAD

**Issue by dividor** [Microsoft/BotBuilder#3222]
We have been testing a bot using the following setup ...

- Bot running on a host internal to our company network
- Local instance of Webchat
- Direct Line integration so that we can pass user-specific information to the bot

It all works wonderfully, and has been tested using ngrok forwarding.

I now need to request our networking folks open an endpoint for the production version.

This answer gives a great summary about opening the port and requirements for the SSL certificate:

https://github.com/Microsoft/BotBuilder/issues/2962

However, when running with ngrok, I notice we have to forward *two* ports ...

```ngrok http –host-header rewrite=9000```
```ngrok http 3978```

I understand the 3978 port, but I'm not sure about the second (9000).

My question is, do we need to open just one port to the internet for our setup, or two?

thanks!

## System Information (Required)
* SDK Language: Node.js
* SDK Version: boatbuilder 3.8.4
* Development Environment: localhost

**Comment by nwhitmont** [comment]
You only need the one port for the bot's `/api/messages` endpoint. Port 3978 is the default development port. Typically when production deployed the bot's port is set to 443 aka `https`.

**Comment by dividor** [comment]
ok, thanks a lot.
