### ISSUE TITLE
[Feature Request] Add support for FB Messenger read receipt

### ISSUE THREAD

**Issue by PierrickGT** [Microsoft/BotBuilder#3228]
## System Information (Required)
* SDK Language: Node.js
* SDK Version: 3.8.4
* Development Environment: Dokku, Redis

## Issue Description
Hi,

I know it is possible to send a typing indicator using [session.sendTyping()](https://docs.botframework.com/en-us/node/builder/chat-reference/classes/_botbuilder_d_.session.html#sendtyping) but I haven't found the same feature to send a read receipt indicator.
Here is the Messenger Send API Reference for this feature: https://developers.facebook.com/docs/messenger-platform/send-api-reference/sender-actions

If this isn't a critical feature on the roadmap, could I know how I can implement it and then make a pull request?

Thank you,
Pierrick

**Comment by PierrickGT** [comment]
Nevermind, my implementation of a custom Redis store was in fault.
I recommend you the following package that implements it well!
suttna/botbuilder-redis-storage

**Comment by benbrown** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
