### ISSUE TITLE
[Question] Change voice of Speech API in botframework

### ISSUE THREAD

**Issue by YanXuHappygela** [Microsoft/BotBuilder#3229]
I have created a bot in botframework node js and it is enabled with speech API. How can I change its voice to a female voice of JessaRUS? Right now it is a male's voice by default. How can I set voiceName to 'Microsoft Server Speech Text to Speech Voice (en-US, JessaRUS)' in the botframework? Thank you!

**Comment by nwhitmont** [comment]
From [Bing Text to Speech API Reference > Voice synthesis request:](https://docs.microsoft.com/en-us/azure/cognitive-services/speech/api-reference-rest/bingvoiceoutput#VoiceSynReq)

**Input parameters**

>Requests to the Bing Text to Speech API are made using HTTP POST calls. The headers are specified in the previous section. **The body contains Speech Synthesis Markup Language (SSML) input that represents the text to be synthesized.** For a description of the markup used to control aspects of speech such as the language and gender of the speaker, see the SSML W3C Specification.

You can specify the voice language `xml:lang`, voice gender `xml:gender`, and name of speaker `name` in the SSML in your request body like this:
```xml
<speak version='1.0' xml:lang='en-US'>
  <voice 
    xml:lang='en-US' 
    xml:gender='Female'
    name='Microsoft Server Speech Text to Speech Voice (en-US, ZiraRUS)'
  >Microsoft Bing Voice Output API</voice>
</speak>

```

**Comment by YanXuHappygela** [comment]
Hi, I have tried this. But the voice remained unchanged. I'm using the RollerSkill demo sample codes:

<speak version="1.0" xml:lang="en-US"><voice name="Microsoft Server Speech Text to Speech Voice (en-US, ZiraRUS)" gender="Female" xml:lang="en-US">I'm roller,
the dice rolling bot. You can say 'roll some dice' or play one of the games I know how to play.</voice></speak>
