### ISSUE TITLE
Facebook channel shows as "Error"

### ISSUE THREAD

**Issue by DavePilks** [Microsoft/BotBuilder#323]
Under my channels, the Facebook one's status is "Error". But I can't see what it is in that state. I have removed the channel and re-added it but it is still the same.

What could be causing this?

**Comment by deivisonrpg** [comment]
I have the same problem here, was working yesterday, today it appears ERROR and not out of it.

**Comment by DavePilks** [comment]
@deivisonrpg So frustrating as everything else is working

**Comment by jameslew** [comment]
Hi all, sorry for the delay.  I've verified the Facebook channel is "generally" working, so lets dig into your individual problems.

First two checks:
1) Check your Facebook app Alerts to see if there are any messages from Facebook
2) Resubmit your Facebook credentials in the Bot Framework Facebook Channel page

Failing those things, can you send a message to botframework@Microsoft.com with your botid so I can investigate logs and see if I can find a pattern?

**Comment by v-thgratMSGit** [comment]
Closing this issue. Please open a new issue for further discussion if necessary. Thanks!
