### ISSUE TITLE
[Cortana] SignCard still doesn't work with Cortana

### ISSUE THREAD

**Issue by poumason** [Microsoft/BotBuilder#3230]
## System Information (Required)
* SDK Language: C#
* SDK Version: Bot Builder 3.9
* Development Environment: Azure App Service

## Issue Description
I try to use Sign-in card in Cortana, and it still is not work.
I also add some comments in the [issues/2959](https://github.com/Microsoft/BotBuilder/issues/2959).
I add the redirect_uri in the Authorization URL, and not help to solve it.

## Code Example
```
private async Task MessageReceivedAsync(IDialogContext context, IAwaitable<object> result
{
    var message = context.MakeMessage() as IMessageActivity;
    message.Speak = "This is a Sign-in card";
    message.Summary = "This is a Sign-in card";
    message.Text = "Message Text";
    message.Attachments = new List<Attachment>(){
    new SigninCard("You need to authorize me", new List<CardAction>()
    {
        new CardAction()
        {
            Value = "https://login.microsoftonline.com/?redirect_uri=http%3a%2f%2fbing.com%2fagents%2foauth",
            Type = "signin",
            Title = "Connect"
        }
    }).ToAttachment()};
await context.PostAsync(message);
context.Wait(MessageReceivedAsync);
```

## Steps to Reproduce the Issue
1. invoke cortana skill
2. Appear sign-in card without connection button

## Expected Behavior
I can see the connection button in the Cortana Skill.

## Actual Results
![error](https://user-images.githubusercontent.com/1639404/28789974-f181b94c-7659-11e7-9220-2f5e37f740ba.png)

**Comment by nwhitmont** [comment]
@poumason Cortana Skills with Bot Framework Developer Preview does not currently support the Sign-In Card workflow on the Cortana channel.

The Cortana team is actively working on integrating this feature, with planned release of this functionality in the next few months.
