### ISSUE TITLE
[Question] Emulator speech - available voice options?

### ISSUE THREAD

**Issue by YanXuHappygela** [Microsoft/BotBuilder#3231]
## System Information (Required)
* SDK Language: Node.js
* Development Environment: localhost, 

I have tried to change the voice of bot, in the RollerSkill example. But the voice remained unchanged in the emulator. I want to change it to a female's voice. The generated SSML is as following:

\<speak version="1.0" xml:lang="en-US"\>\<voice name="Microsoft Server Speech Text to Speech Voice (en-US, ZiraRUS)" gender="Female" xml:lang="en-US"\>I'm roller,
the dice rolling bot. You can say 'roll some dice' or play one of the games I know how to play.\</voice\>\</speak\>

Suppose I have the speech API key. How can I put the information to the bot so that it is integrated?
Anything I missed? Thank you!

**Comment by nwhitmont** [comment]
@YanXuHappygela The SSML voice configuration options are specific to the Bing text to speech API you asked about in your previous question, the Bot Framework Emulator does not support that same level of voice options.

**Comment by YanXuHappygela** [comment]
@nwhitmont Thank you for clarification. So how can I test change of voice, in other channel, like Cortana?

**Comment by nwhitmont** [comment]
@YanXuHappygela Cortana only has one voice available.

**Comment by YanXuHappygela** [comment]
@nwhitmont what channels can SSML take effect? only on voice enabled web?

**Comment by nwhitmont** [comment]
Speech is available in Direct Line WebChat when you enable it via `speechOptions`.

Example:
```js

        BotChat.App({
            directLine: { secret: DIRECTLINE_SECRET_HERE },
            user: { id: 'userid' },
            bot: { id: 'botid' },
            speechOptions: {
                speechRecognizer: new BotChat.Speech.BrowserSpeechRecognizer(),
                speechSynthesizer: new BotChat.Speech.BrowserSpeechSynthesizer()
            }

        }, document.getElementById("bot"));
```

**Comment by w-Yuan** [comment]
So the problem is that in the given ssml. gender is "Female", which is rejected by Cognitive Services. Changing “Female” to "female" will work.

**Comment by nwhitmont** [comment]
thanks for the update @w-Yuan
