### ISSUE TITLE
[Question] Skype channel does not show images on card on Skype desktop

### ISSUE THREAD

**Issue by pomarc** [Microsoft/BotBuilder#3234]
## System Information (Required)
* SDK Language: Node.js
* SDK Version:  3.8.2
* Development Environment: localhost, webhook is on a ubuntu server, in https. 
 
## Issue Description
images in cards are not shown in Skype (the desktop app) but are shown in slack, web, telegram

## Code Example
 msg = new builder.Message(session).addAttachment( 
            
                     new builder.HeroCard(session)
                            .title(keyDescription )
                            .subtitle(session.userData.plant.description)
                            .text(res.chartLast+numberOfHours+res.chartLastHours)

                            .images(
                                [builder.CardImage.create(session,config.imageserverUrl+data.imageId)
                                ]
                                )
                               .buttons([
                                 
                               ])
 
note:                   
    config.ImageServerURL:"https://myserver:3000/images/"

 
## Expected Behavior
that in skype I'd see the images in the card.  

## Actual Results
 the card is shown as a gray square, title and sub and text are correctly shown, there is  empty space where the image should be, but no image.

**Comment by pomarc** [comment]
if I replace my image link with the link you get in the samples, [https://sec.ch9.ms/ch9/7ff5/e07cfef0-aa3b-40bb-9baa-7c9ef8ff7ff5/buildreactionbotframework_960.jpg], the image is shown.
So It must be the way I serve the image that annoys Skype. But  my image is 

- a png file
- less than 20M
- served from https
- has the following headers:
```
    Connection →keep-alive
Date →Tue, 01 Aug 2017 13:04:57 GMT
accept-ranges →bytes
cache-control →no-cache
content-length →51268
content-type →image/png
etag →"6aee4108f557579cc2eb07d253c8be5ec4b208f5"
last-modified →Mon, 24 Jul 2017 15:31:04 GMT
```
what's wrong with this, and how can a dev debug a behaviour like this?

**Comment by brene** [comment]
Hi @pomarc it looks like your server is not a globally reachable server. That's why skype's service can never reach the images. Try opening https://myserver:3000/images/ on an external device that is not tunneled, then you'll see that it's not reachable.
![image](https://user-images.githubusercontent.com/4989523/29115108-ad3a7a0a-7cf6-11e7-8d9f-8635994e634c.png)

**Comment by pomarc** [comment]
@brene "myserver.com" was a placeholder. I cannot write here my real server url. Anyway believe me, the server is reachable and all the others channels show the pics.
thanks

**Comment by nwhitmont** [comment]
@pomarc When you provide a `https` URL, the service will look for the file on port 443 by default. It is likely that your custom port number is the problem. What happened when you served your images over the default `https` port 443?

**Comment by nwhitmont** [comment]
@pomarc were you able to solve the issue by using the default `https` port 443?

**Comment by nwhitmont** [comment]
reopen if you're still having issues
