### ISSUE TITLE
[Question] Cannot display the entire text in the hero card

### ISSUE THREAD

**Issue by dijotcr222** [Microsoft/BotBuilder#3236]

**Comment by stevengum97** [comment]
@dijotcr222, can you provide the code that is producing your issue, the SDK version, your development environment and what is the expected result?

**Comment by dijotcr222** [comment]
var card = new builder.HeroCard(session);
                      card.title("Did you mean one of the options below :");
                      card.buttons([
                      builder.CardAction.imBack(session, DIDYOUMEANARRAY[0],DIDYOUMEANARRAY[0]),
                      builder.CardAction.imBack(session, DIDYOUMEANARRAY[DIDYOUMEANARRAY.length-1],DIDYOUMEANARRAY[DIDYOUMEANARRAY.length-1])
                      ]);

**Comment by nwhitmont** [comment]
@dijotcr222 What text are you trying to display in your Hero Card exactly?

**Comment by nwhitmont** [comment]
reopen if you are still having issues.

**Comment by dijotcr222** [comment]
Yes
