### ISSUE TITLE
[Question] Bot doesn't work in Microsoft Teams but works perfectly in Slack

### ISSUE THREAD

**Issue by dynamicdeploy** [Microsoft/BotBuilder#3237]
## System Information (Required)
* SDK Language:  .NET
* SDK Version:  BotBuilder 3.8.5
* Development Environment:  App Service

## Bot Info 
* Bot name: meelo
* Bot handle: meelo
* App ID: 764e233f-f94d-4e21-9728-fdf768814285
* Connected channels:  Slack, MS Teams, Facebook, Skype

## Issue Description

The bot does not receive any messages from Microsoft Teams. Works perfectly in Slack.
## Code Example

No code to share. Regular code that compiles and runs fine in Slack and Skype.
## Steps to Reproduce the Issue
1.
2.
3.

## Expected Behavior

Expect the bot to work in Microsoft Teams
## Actual Results

No messages received by bot. I remote debugged using VS 2017 and no messages were received from MS Teams. All Slack and Skype messages were received.
For Facebook messenger, bot receives the messages, responds it, but the Facebook messenger doesn't display the response.

**Comment by xjose97x** [comment]
go to dev.botframework.com

in your bots page you'll be able to see the errors you receive per channel. 


![errors](https://user-images.githubusercontent.com/8400149/28836567-0663b1ee-76af-11e7-80fc-069636cdeb25.PNG)

**Comment by dynamicdeploy** [comment]
@xjose97x I don't see any errors on MS Teams.
![image](https://user-images.githubusercontent.com/1393485/28837348-4f98b070-76a1-11e7-9ea7-5234ace96036.png)

**Comment by xjose97x** [comment]
@dynamicdeploy , can you check the errors on webchat? 
I remember that sometimes the errors I received on Skype were actually shown on the webchat.
Not sure if it applies on MS Teams.

**Comment by Meelo** [comment]
Excuse me?

**Comment by dynamicdeploy** [comment]
No, I just double-checked. WebChat messages are the expected ones (timeouts). But MS Teams shows no messages.

**Comment by Meelo** [comment]
I think you have the wrong reference in the bug description. I am not a bot, I think?

**Comment by dynamicdeploy** [comment]
Meelo is the name of my bot ;).

**Comment by Meelo** [comment]
I realise that. That @Meelo just causes me to get notified about everything. But I'll ensure you, it's totally normal for Meelo to not work under microsoft environment.

That being said, I'm unsubscribing this thread before I clutter it too much with off-topic non-sense. Good luck.

**Comment by nwhitmont** [comment]
@dynamicdeploy Did you "Side-Load" your bot into MS Teams app? With JSON manifest file, etc.?

This is a second step after you have added your bot to the Teams channel in the Bot Dev Portal at https://dev.botframework.com/

## How to load your bot into MS Teams
**Quick MS Teams bot deployment checklist:**
- Did your O365 tenant administrator [enable sideloading](https://msdn.microsoft.com/en-us/microsoft-teams/setup) of apps for your organization?
- Did you [create an app package](https://msdn.microsoft.com/en-us/microsoft-teams/createpackage)
- Did you [sideload your bot app](https://msdn.microsoft.com/en-us/microsoft-teams/sideload) into the relevant team?

**Recommended reading:**
   - [Getting Started with Bots for Microsoft Teams](https://msdn.microsoft.com/en-us/microsoft-teams/bots)
   - [Create the package for your Microsoft Teams app](https://msdn.microsoft.com/en-us/microsoft-teams/createpackage) - aka manifest.json file
   - [Sideloading your app in a team](https://msdn.microsoft.com/en-us/microsoft-teams/sideload)
   - [Testing your Bot](https://msdn.microsoft.com/en-us/microsoft-teams/botsadd)

**Comment by dynamicdeploy** [comment]
I added to the dev portal and then just clicked the associated link to enable bot in MS Teams. I will try the procedure in the admin portal.

**Comment by nwhitmont** [comment]
@dynamicdeploy Any luck with enabling the bot in Teams? Let me know if you are still having issues.

**Comment by dynamicdeploy** [comment]
Enabling sideloading worked. Thanks for the help.

**Comment by JasonSowers** [comment]
glad you got this working

**Comment by zlepper** [comment]
I'm also seeing this issue for some reason. The bot seems at best unreliable at receiving the messages. Inspecting the web traffic, i can see that messages from Teams never hits the api endpoint i specified. However messages from the webchat goes through without issues. I have enabled the bot through side-loading, and it does seem to be working _sometimes_.. 

A colleague of mine tried writing messaging the bot from his user, and the first couple of hours didn't go through. Then a couple of messages got through, and then stuff kinda started falling apart again. If there a way of diagnosing this? It's a bit frustrating that the portal doesn't really tell us anything at all.
