### ISSUE TITLE
[MS Teams] Direct messages, from user to bot, do not include new line (\n) characters?

### ISSUE THREAD

**Issue by santiagodoldan** [Microsoft/BotBuilder#3238]
## System Information
* SDK Language: Node.js
* SDK Version: 3.8.4
* Development Environment: localhost

## Issue Description
Direct messages in MS Teams do not include new lines, it uses spaces instead of `\n`, maybe it happens the same in channel conversations, haven't tested there yet.

## Code Example
```
  lib.dialog('/', (session, args) => {
    builder.Prompts.text(session, "This is a test question?")
  }, (session, result) => {
    console.info(result.response)
  })
```

![screen shot 2017-08-01 at 9 56 57 pm](https://user-images.githubusercontent.com/1096526/28853405-c5d8ba40-7706-11e7-9078-306f1679f830.png)

## Expected Behavior
`console.info(result.response) => "'This\nis\na\nmulti\nline\ntext"`

## Actual Results
`console.info(result.response) => "'This is a multi line text"`

If that's the expected behavior, the `session.message` includes a html markup (there's a sample below) that I can parse, saying that, is there a parser to do that?

```
attachments:
   [ { contentType: 'text/html',
       content: '<div><div><div>This</div><div>is</div><div>a</div><div>multi</div><div>line</div><div>text</div></div></div>' } ]
```

**Comment by JasonSowers** [comment]
Can you please try with "\n\n" and see if that works for you?

**Comment by santiagodoldan** [comment]
@JasonSowers sorry if I wasn't clear, the issue is what I get from botframework when a user enters a message with more than 1 line, the bot gets a string with spaces instead of \n or <br>, so i don't have a way to know if the user entered new lines or not.

**Comment by JasonSowers** [comment]
I see, can you please elaborate on your use case, someone may have a workaround that may help you.

**Comment by JasonSowers** [comment]
@RichMoeMSFT thoughts?

**Comment by nwhitmont** [comment]
@santiagodoldan This is a feature, not a bug. MS Teams chat interface does not support rich-text advanced formatting.

**Comment by santiagodoldan** [comment]
Maybe someone could find this useful, we extracted 2 middlewares from our bot app and created a new package to fix this limitation, this is the repo https://github.com/suttna/botbuilder-markdown, adding the middleware will transform the markup that Teams sends to the bot into new lines like `\n`.
