### ISSUE TITLE
[Question] How to embed WebChat in page?

### ISSUE THREAD

**Issue by SiddheshwarKore** [Microsoft/BotBuilder#3239]
## System Information
* SDK Language: .NET
* SDK Version: 3.9.0
* Development Environment: Auzure Bot Service 

## Bot Info 
* Bot name:  faqBot
* Bot handle: 
* App ID: 
* Connected channels: 

## Issue Description

Hi everyone,
Can you suggest me how can I build a chatbot that can be deployed on a website which should not be an embedded web control rather a collapsible chat widget powered by bot framework in the backend. 
Did quite a lot of google search but didnt get a convincing solution.Awaiting your response 
## Steps to Reproduce the Issue
1.
2.
3.

**Comment by nrobert** [comment]
You should read the "Readme" section of BotFramework-Webchat github project: https://github.com/Microsoft/BotFramework-WebChat

**Comment by ankitbko** [comment]
Just simple javascript to collapse the chat div should work out, if you are not looking at anything fancy. You can check out how I did it in my blog (lower right) - http://ankitbko.github.io/

**Comment by JasonSowers** [comment]
Please reopen and continue the conversation if you need more help with this
