### ISSUE TITLE
Prompt choice with reserve words

### ISSUE THREAD

**Issue by mikkhait** [Microsoft/BotBuilder#324]
It looks like we can't have prompts with _reserved_ words.

```
builder.Prompts.choice(session, "Your Action?", ['Cancel','Stop']);
```

I want to be able to treat them as legit options and have `response` in `results`. Currently response looks like this:

**Actual**
```
{ resumed: 2,
  promptType: 3,
  childId: 'BotBuilder.Dialogs.Prompts' }
```

**Expected**
```
{ resumed: 0,
  promptType: 3,
  response: { index: 1, entity: 'Stop', score: 1 },
  childId: 'BotBuilder.Dialogs.Prompts' }
```

**Comment by mikkhait** [comment]
Low priority, for now, I changed labels :)

**Comment by Stevenic** [comment]
I'll have to refactor things some to support that but good feedback.

**Comment by v-thgratMSGit** [comment]
Closing this issue. Please open a new issue for further discussion if necessary. @Stevenic - reopen if you would like to and/or provide a status on this bug/enhancement.  This could also be suggested on [UserVoice](https://feedback.botframework.com/). Thanks!
