### ISSUE TITLE
[Question] Bot error: "404 Not Found" after deleting user state and exiting LUIS dialog

### ISSUE THREAD

**Issue by kneuLIL** [Microsoft/BotBuilder#3240]
## System Information
* SDK Language:  .NET 
* SDK Version: 3.8.1
* Development Environment:  localhost

## Issue Description
Within a luis dialog I have an intent that deletes the user state and exits the luis dialog. Afterwards it hits the resume method of the parent dialog and on exiting this method an exception is thrown and the emulator shows the "Exception: The remote server returned an error: (404) Not Found." as a message.

## Code Examples
* Creation of the parent/main dialog

await Conversation.SendAsync(activity, () => new MainDialog());

* Creation of the luis dialog within the main dialog

context.Call(new DeLuisDialog(), AfterLuisDialog);

* AfterLuisDialog Method
// This method is hit and exits without error
        private async Task AfterLuisDialog(IDialogContext context, IAwaitable<object> result)
        {
            context.Wait(this.MessageReceivedAsync);
        }

* Code that deletes the user state and exits the luis dialog

var client = new StateClient(new Uri(botStateApiBaseUri), credentials);
await client.BotState.DeleteStateForUserAsync(channelId, userId);

await context.PostAsync("User State Deleted");
context.Done<bool>(true);

## Steps to Reproduce the Issue
1. Start a dialog
2. Create sub dialog
3. Delete user state
4. Exit sub dialog
5. Call context.Wait(MessageReceivedAsync) in the resume method of the first dialog

## Expected Behavior
The bot waits for the next message and continues within the "MessageReceivedAsync" of the MainDialog

## Actual Results
An exception is thrown up to the creation of the MainDialog( Conversation.SendAsync(....)).

## Exception:
* Exception message within the emulator
![image](https://user-images.githubusercontent.com/29102057/28864706-a2ec40da-776d-11e7-9314-bdde45ecaf44.png)

* Exception activity
{
  "type": "message",
  "timestamp": "2017-08-01T18:11:44.932Z",
  "localTimestamp": "2017-08-01T20:11:44+02:00",
  "serviceUrl": "https://96545afe.ngrok.io",
  "channelId": "emulator",
  "from": {
    "id": "e8380mk5nl045kmj7c",
    "name": "Bot"
  },
  "conversation": {
    "id": "08e3mlc8m2nag9k2f"
  },
  "recipient": {
    "id": "default-user"
  },
  "membersAdded": [],
  "membersRemoved": [],
  "locale": "de",
  "text": "Exception: The remote server returned an error: (404) Not Found.",
  "attachments": [
    {
      "contentType": "text/plain",
      "content": "   bei Microsoft.Bot.Connector.ErrorHandling.<HandleErrorAsync>d__2`1.MoveNext()\r\n--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   bei Microsoft.Bot.Connector.BotStateExtensions.<SetUserDataAsync>d__3.MoveNext()\r\n--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   bei Microsoft.Bot.Builder.Dialogs.Internals.ConnectorStore.<Microsoft-Bot-Builder-Dialogs-Internals-IBotDataStore<Microsoft-Bot-Connector-BotData>-SaveAsync>d__3.MoveNext()\r\n--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   bei Microsoft.Bot.Builder.Dialogs.Internals.CachingBotDataStore.<Save>d__10.MoveNext()\r\n--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   bei Microsoft.Bot.Builder.Dialogs.Internals.CachingBotDataStore.<Microsoft-Bot-Builder-Dialogs-Internals-IBotDataStore<Microsoft-Bot-Connector-BotData>-FlushAsync>d__5.MoveNext()\r\n--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   bei Microsoft.Bot.Builder.Dialogs.Internals.BotDataBase`1.<FlushAsync>d__9.MoveNext()\r\n--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   bei Microsoft.Bot.Builder.Dialogs.Internals.DialogTaskManagerBotDataLoader.<FlushAsync>d__12.MoveNext()\r\n--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   bei Microsoft.Bot.Builder.Dialogs.Internals.PersistentDialogTask.<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d__3.MoveNext()\r\n--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   bei Microsoft.Bot.Builder.Dialogs.Internals.ExceptionTranslationDialogTask.<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d__2.MoveNext()\r\n--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   bei Microsoft.Bot.Builder.Dialogs.Internals.SerializeByConversation.<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d__4.MoveNext()\r\n--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   bei Microsoft.Bot.Builder.Dialogs.Internals.PostUnhandledExceptionToUser.<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d__5.MoveNext()"
    }
  ],
  "entities": [],
  "replyToId": "770mk6a6nd240ckeac",
  "id": "7491a98eglmhkk9hac"
}

Thanks in advance for your support!

**Comment by EricDahlvang** [comment]
HI @kneuLIL 

Thank you for the clear and concise explanation of the issue. Please try using the dialog's context, instead of creating a state client. You can clear the UserData:

context.UserData.Clear();

You could also try: context.EndConversation(string code);  

The dialog's context has a separate reference to the bot state, and it implements a different interface.  If you create your own botstate, there can end up being a conflict when the dialog's bot state is persisted.

**Comment by kneuLIL** [comment]
Hi @EricDahlvang , 
thanks a lot for the response! 

context.UserData.Clear();

seems to do the trick,

context.EndConversation(string code);
also gives the desired behaviour but im not sure what "code" is and havent really had the time to have a closer look at the docs yet.

Thanks again!
