### ISSUE TITLE
Retrieving User Name and Id in Cortana from Activity

### ISSUE THREAD

**Issue by neetgupta7** [Microsoft/BotBuilder#3242]
Hello
I have a simple echo bot built on .net and enabled on Cortana. I was hoping that once i enable permission for "Request user profile data" for user name and email i will see them in activity.from.name and activity.from.id. But I see a very long from.id and blank name. Is there no way I can capture this information through Cortana Channel.

**Comment by JasonSowers** [comment]
@neetgupta7 This data is not available out of the box.  You would have to implement a solution on your own.  A really good starting place would be to take a look at [AuthBot](https://github.com/MicrosoftDX/AuthBot) and the [Graph API](https://developer.microsoft.com/en-us/graph/)

**Comment by neetgupta7** [comment]
@JasonSowers I was able to extract data using below link-
https://docs.microsoft.com/en-us/cortana/tutorials/bot-skills/bot-entity-channel-data#User-Profile-Information

But it was in below form under activity.entities -
UserInfo : { "Name": { "GivenName": "Sankar", "FamilyName": "Mitra" }, "Id": "infy_627750@outlook.com" }

**Comment by Ragha2207** [comment]
@neetgupta7  can post your code which retrieves the username and email? 
I am trying to retrieve the username and email in my bot through Cortana but the I get blank values..
