### ISSUE TITLE
[Question] Cant find any information about Discord

### ISSUE THREAD

**Issue by EatsLemons** [Microsoft/BotBuilder#3244]
Cant find any issues about Discord integration, can I add feature request with it or is it already there?

https://discordapp.com/features

**Comment by xjose97x** [comment]
Hello @EatsLemons !
Bot Framework does not support Discord natively. You will have to implement it with Directline.

Csharp sample: https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/core-DirectLine
NodeJS sample: https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node/core-DirectLine

**Comment by JasonSowers** [comment]
This has been in the back of my head for a while now I will put in a feature request.  Thanks for bringing this up!
