### ISSUE TITLE
[Question] Retrieve Skype user profile picture

### ISSUE THREAD

**Issue by indiandragon** [Microsoft/BotBuilder#3246]
Can the Skype user profile picture (the user who's chatting with the bot) be retrieved using Bot Framework. I don't see any documentation related to the same.

**Comment by nwhitmont** [comment]
@indiandragon Are you using .NET or Node.js SDK?

**Comment by indiandragon** [comment]
@nwhitmont Hi, I'm using Node.js SDK.

**Comment by nwhitmont** [comment]
Not currently a feature of the BotBuilder SDK. You would need to query the Skype API directly.

see: https://superuser.com/a/860803

**Comment by indiandragon** [comment]
@nwhitmont Thanks for the confirmation, I assume the Skype API could use authentication via botframework to get the profile. But considering, there's no way to obtain original skype id via botframework; obtaining user profile picture is not possible.

Considering all other bot platforms provide user profile picture, is this planned for future?
