### ISSUE TITLE
[Question] Telegram: answerInlineQuery & answerCallbackQuery are not working properly  

### ISSUE THREAD

**Issue by asajm** [Microsoft/BotBuilder#3247]
## System Information
* SDK Language: Node.js
* SDK Version: 3.9.0  &  3.4.4
* Development Environment: localhost, ngrok (2.2.8), visual studio code (1.14.2)

## Bot Info 
* Connected channels: Telegram

## Issue Description

Regarding the utilization of [Telegram-specific actions](https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-channeldata#create-a-telegram-message) through `channelData`.
if I received Telegram update with [InlineQuery](https://core.telegram.org/bots/api#inlinequery) and then I answered by [answerInlineQuery](https://core.telegram.org/bots/api#answerinlinequery) OR even I received Telegram update with [CallbackQuery](https://core.telegram.org/bots/api#callbackquery) and then I answered by [answerCallbackQuery](https://core.telegram.org/bots/api#answercallbackquery), this error occurred `[500] Internal Server Error`. While other methods like [sendMessage](https://core.telegram.org/bots/api#sendmessage) is working properly. 

## Code Example

[BotFramework-Telegram-InlineQuery](https://github.com/eanders-MS/BotFramework-Telegram-InlineQuery)

## Actual Results

the incoming update from telegram contained `InlineQuery`:-
```
{
    "update_id": 875506648,
    "inline_query": {
        "id": "27876010608893950",
        "from": {
            "id": 6490389,
            "first_name": "Ahmed",
            "last_name": "Almalki",
            "username": "ahmedsmalki",
            "language_code": "en-SA"
        },
        "query": "",
        "offset": ""
    }
}
```
this error occurred after sending a message with `channelData` either `answerInlineQuery` or `answerCallbackQuery`:-
```
Error: Request to 'https: //telegram.botframework.com/v3/conversations/6490389/activities/27876010608893950' failed: [500] Internal Server Error
    at Request._callback (/Users/ABC/projects/BotFramework-Telegram-InlineQuery/node_modules/botbuilder/lib/bots/ChatConnector.js:523:46)
    at Request.self.callback (/Users/ABC/projects/BotFramework-Telegram-InlineQuery/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/ABC/projects/BotFramework-Telegram-InlineQuery/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/ABC/projects/BotFramework-Telegram-InlineQuery/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
```

**Comment by asajm** [comment]
is there a solution to this issue?

**Comment by asajm** [comment]
from Telegram side, `answerInlineQuery` & `answerCallbackQuery` methods return TRUE when success, other than the other methods like `snedMessage` which returns an object `Message`.

Could this be the reason of error?
@eanders-MS

**Comment by eanders-MS** [comment]
I'm poking around in the Telegram adapter right now and will have look.

**Comment by eanders-MS** [comment]
@asajm Sorry for the long delay. I've made a fix in our Telegram channel. It should go out in the next update to production (typically happens once every few weeks).

Part of the issue was indeed we weren't handling the response from the Telegram API call correctly when it wasn't a JSON-formatted response. Thanks for the heads up on that!

**Comment by benbrown** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
