### ISSUE TITLE
[Feature Request] Support for Discord as a channel

### ISSUE THREAD

**Issue by JasonSowers** [Microsoft/BotBuilder#3248]
Starting a thread to gauge interest in [Discord](https://discordapp.com) as a supported channel
#3244

**Comment by xjose97x** [comment]
Lol, would be nice for the gamers community haha.

**Comment by JasonSowers** [comment]
Almost every day I wish this and Twitch bot support already existed 👍

**Comment by TaylorAckley** [comment]
+1

**Comment by amitbend** [comment]
+1 as well.
[Promo Bot](https://promo-bot.tk/) would love being there

**Comment by robinsedlaczek** [comment]
+1

**Comment by mvanella** [comment]
+ 1

**Comment by jonatkinson** [comment]
+1

**Comment by benbrown** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
