### ISSUE TITLE
[Question] Works in Bot Framework Emulator but not Skype?

### ISSUE THREAD

**Issue by LH104729** [Microsoft/BotBuilder#3249]
I am hosting my bot on Heroku, then i put the address (https://xxx.herokuapp.com/api/messages) to the end point address, and then i click test, the message was send but no respond, but if i do it in the emulator and put in the same url, it worked.

**Comment by nwhitmont** [comment]
@LH104729 For reference, are you using .NET or Node.js SDK?

Do you have a valid SSL certificate? You need to have a valid SSL certificate for your deployed bot in order to connect to Bot Connector API.

**Comment by LH104729** [comment]
@nwhitmont node.js

**Comment by LH104729** [comment]
@nwhitmont How to get a SSL certificate?

**Comment by nwhitmont** [comment]
@LH104729 You can purchase a SSL certificate from an approved vendor such as [Comodo](https://ssl.comodo.com/)

The Bot Framework works with bots deployed on any cloud hosting service, as long as you have an internet-accessible endpoint and a valid SSL certificate.

The Bot Framework requires that the x.509v3 certificate exposed by your endpoint be current and valid. Most of the checks for "current and valid" are standard checks for server certs: the CN must match the hostname, it must not be expired, it must not be listed in a CRL, it must have the correct set of EKUs, etc.

**Most importantly, your cert must chain to a root certificate authority trusted by Microsoft.** The latest list of these CAs is available here: http://social.technet.microsoft.com/wiki/contents/articles/31634.microsoft-trusted-root-certificate-program-participants-v-2016-april.aspx

For more information on deploying your bot, see: https://docs.microsoft.com/en-us/bot-framework/deploy-bot-overview

**Comment by LH104729** [comment]
@nwhitmont Oh I see, Thanks
