### ISSUE TITLE
[Question] Same function call twice in waterfall model

### ISSUE THREAD

**Issue by ersachit** [Microsoft/BotBuilder#3250]
Hi @nwhitmont, I am working on a skype bot in Node.js. I am using waterfall model as shown in below example. This is something question and answer type bot. So when I type 'start', bot gives first question with five answers but if someone types answer two times within a fraction of time (for example~ type 1, press enter ->type 2, press enter) then the next function called twice. Is it possible to restrict the function being called multiple time. Any help would be appreciable.

```js
bot.dialog('start', [
    function (session) {
        buildQuestionsAndOptions(session, session.userData.questionArray[0]);
    },
    function (session, results) {     
        buildQuestionsAndOptions(session, session.userData.questionArray[1]);
    },
    function (session, results) {
        buildQuestionsAndOptions(session, session.userData.questionArray[2]);
    }
]);
```

**Comment by stevengum97** [comment]
@ersachit Can you provide the code for your `buildQuestionsAnOptions` function?

**Comment by ersachit** [comment]
Sure~

`function (session, results) {
        firebaseOperations.updateLastSentMessageOfPendingFeedback(new Date().getTime(), session.userData.attendeeId,
            session.userData.trainingId);
        var userAnswer = results.response.entity;
        var questionObject = session.userData.questionArray[0];
        questionObject.answer = userAnswer;
        buildQuestionsAndOptions(session, session.userData.questionArray[1]);
    }`

`function buildQuestionsAndOptions(session, questionObject) {
    var question = questionObject.question;
    var options = questionObject.options;
    var questionsType = questionObject.question_type;
    var id = questionObject.id;
    if (questionsType === 'choice') {
        builder.Prompts.choice(
            session,
            id + ". " + question,
            options,
            {
                listStyle: builder.ListStyle.button,
                retryPrompt: i18n.__('retry_prompt')
            });
    } else if (questionsType === 'text') {
        builder.Prompts.text(session, id + ". " + question);
    }
}`

**Comment by ersachit** [comment]
Hey stevengum97, I am using these versions in the application~
node - 6.11.1
botbuilder - 3.9.0

let me know if you required any other information.

**Comment by ersachit** [comment]
Hey @stevengum97, I have also checked the example from [here](https://github.com/Microsoft/BotBuilder/blob/master/Node/examples/basics-waterfall/app.js)  and it's also giving the same behavior. Like when you would ask to type your name and if we type say "Test" multiple times then the next question "Hi Test, How many years have you been coding?" gets printed multiple time. I am also attaching the screenshot of the same.

![screen shot 2017-08-04 at 9 55 53 am](https://user-images.githubusercontent.com/8393960/28954203-28197bc2-78fb-11e7-8bac-0f97c480d404.png)

**Comment by ersachit** [comment]
Hi @stevengum97 , @nwhitmont ~ any updates on this. Actually, I am looking for the urgent solution to this issue.

**Comment by nwhitmont** [comment]
What you describe as your problem is expected behavior. You sent multiple messages to the bot, and it responded multiple times. To address this edge-case, you would need to design a custom solution and write the code yourself to handle it.

**Comment by ersachit** [comment]
Hi @nwhitmont, I agree with your point but why the same function is calling again and again as we are following waterfall model so it should call to the next function I believe? Please suggest.

**Comment by vinayak99999** [comment]
@ersachit I agree with you. Even i am facing problem with water fall model. It asks for same value twice then proceeds for next function.
