### ISSUE TITLE
[MS Teams] "Invoke" action not working on mobile

### ISSUE THREAD

**Issue by espeo196** [Microsoft/BotBuilder#3251]
## Issue Description
As per the documentation [here](https://msdn.microsoft.com/en-us/microsoft-teams/botsmessages#action---invoke), I'm using Microsoft Teams' invoke activity because I want to pass a JSON payload on a button click. Everything works fine when I use Teams on desktop, but on mobile I get no response from clicking the button.

## Code Example (.NET)
`var button = new CardAction()
{
    Title = "Option 1",
    Type = "invoke",
    Value = "{\"option\": \"opt1\"}"
};`

## Expected Behavior
Clicking the button should create an Invoke activity that is received in the MessagesController

## Actual Results
Clicking the button on mobile (Windows, iOS, and Android) creates no response. Nothing is received by the MessagesController. On desktop a response is received as expected.

Note: I have noticed the same behavior with ActionTypes.OpenUrl where the link opens on desktop, but wouldn't work on mobile until I added `Uri.EscapeUriString(uri)`. However, attempting the same fix for invoke returns empty json on desktop and still doesn't hit the MessagesController on mobile.

**Comment by nwhitmont** [comment]
@RichardMoe Is "Invoke" action type supported on MS Teams mobile?

**Comment by RichMoeMSFT** [comment]
I am able to get Invoke to work on all platforms.  

While this wouldn't explain why it works on desktop, please note that "invoke" is an ActivityType not an ActionType and therefore you need to handle activity.Type == ActivityTypes.Invoke in your MessagesController.

**Comment by espeo196** [comment]
I am checking for activity.Type == ActivityTypes.Invoke in the MessagesController and this works fine on desktop, but that code is never hit on mobile. Even if I pass basic or empty json I get no response when pressing the button.

**Comment by espeo196** [comment]
Well, I was able to get this working on Android and iOS, but not Windows. I can work with this for now, but is this a known issue/is there a workaround?

**Comment by JasonSowers** [comment]
Please reopen if you would like to continue the discussion

**Comment by harshavijaya** [comment]
[JasonSowers](https://github.com/JasonSowers)

I am facing the same issue.
CardAction's **type** is of type ActionTypes, not of ActivityTypes.
ActionTypes.invoke is working fine in Desktop messaging extension, but the event is not triggered from Android Mobile app.
