### ISSUE TITLE
[Channel Config] There was a problem synchronizing your bot to Skype.

### ISSUE THREAD

**Issue by SyedAbdullahQamar** [Microsoft/BotBuilder#3253]
![screenshot_1](https://user-images.githubusercontent.com/30691226/28919212-ec49b5f2-7865-11e7-868b-78ef5f4fa68b.png)

There was a problem synchronizing your bot to Skype.

AppID = 153515f0-dbac-41d1-b344-01fd27015cfc
BotHandle = messenger_bot

I am getting continuous error "There was an error sending this message to your bot."
Although i published my bot application on my IIS server and register the url but still no help to get my bot connected to skype and work correctly.
Note: I download the bot template and added to Visual Studio and didn't make many changes in bot template.

**Comment by SyedAbdullahQamar** [comment]
Please Help.! :(

**Comment by nwhitmont** [comment]
@SyedAbdullahQamar - When I tested your bot in the WebChat test window your bot did not respond. This means there is an error in your bot code or deployment method. 

If you are deploying your bot to a custom VM or private server, you will need to have a valid SSL certificate enabled on your server.

**Comment by SyedAbdullahQamar** [comment]
Actually i have a system generated SSL and i don't know it is valid or not.
How to identify that SSL is valid?

**Comment by SyedAbdullahQamar** [comment]
How can there be an error in code. I mean i downloaded a bot application template and didn't make many changes and i also tested my application on Bot emulator its working fine.

**Comment by nwhitmont** [comment]
@SyedAbdullahQamar A self-signed certificate won't work. You need to purchase a SSL cert that is recognized by Microsoft from an approved vendor.

The Bot Framework works with bots deployed on any cloud hosting service, as long as you have an internet-accessible endpoint and a valid HTTPS cert.

The Bot Framework requires that the x.509v3 certificate exposed by your endpoint be current and valid. Most of the checks for "current and valid" are standard checks for server certs: the CN must match the hostname, it must not be expired, it must not be listed in a CRL, it must have the correct set of EKUs, etc.

Most importantly, your cert must chain to a root certificate authority trusted by Microsoft. The latest list of these CAs is available here: http://social.technet.microsoft.com/wiki/contents/articles/31634.microsoft-trusted-root-certificate-program-participants-v-2016-april.aspx

For more information on deploying your bot, see: https://docs.microsoft.com/en-us/bot-framework/deploy-bot-overview

**Comment by SyedAbdullahQamar** [comment]
I am closing this issue now. I deleted my bot and Register a new one with a valid SSL certificate and now  i am getting other issues
