### ISSUE TITLE
[Direct Line] Error: "Precondition Failed 412"?

### ISSUE THREAD

**Issue by anirudhaditya** [Microsoft/BotBuilder#3254]
We have a custom Web chat and using direct line. Recently we have started facing issue with **Precondition Failed 412.** I have going through several articles and blogs but not able to figure out if anyone has found the solution of it. 

I have made both the attempts but failed. Need to know if anyone has already faced and resolved it. It's kind of urgent.

**Step 1:** Setting eTag property value of asterisk (*) indicates that we have not previously saved data for the specified combination of channel, user, and conversation. This did not work. Still faced error.

**Step 2:** IBotDataStore using Bot Builder SDK Azure Extensions as suggested . In this step we used private storage for storing session for Post and Get operations. This also didn't worked.
Information:
https://docs.microsoft.com/en-us/bot-framework/troubleshoot-general-problems
https://docs.microsoft.com/en-us/bot-framework/rest-api/bot-framework-rest-state
https://github.com/Microsoft/BotBuilder/issues/1075

Any help would be highly appreciated.

Thanks
Aniruddha

**Comment by nwhitmont** [comment]
@anirudhaditya What were you doing when you got the error?  What steps did you use to reproduce the error? What code was running when you encountered the error. Please share your code and screenshots of where the error occurred.

**Comment by anirudhaditya** [comment]
1) C#
2) This error comes randomly and mainly when there is more traffic
3) Easy way is to just enter any sentence continuously and repeatedly several times.
4) C#. On Dev we are not able to replicate the issue. As its thrown from the Bot Framework Service.
5) I can't share the entire code due to the SLA but jest of the code is here https://drive.google.com/file/d/0B3qm2bV8_ozdUGlaYWZBamM0VkU/view?usp=sharing

Note: Similar issue https://github.com/Microsoft/BotBuilder/issues?utf8=%E2%9C%93&q=412%20issues
but none has said its been resolved. 

Please advice.

Thanks
Aniruddha

**Comment by anirudhaditya** [comment]
This issue got resolved after eTag(*) & setting global LastWriteWins code. Thanks
