### ISSUE TITLE
Cannot return any type except IMessageActivity from context.Forward()

### ISSUE THREAD

**Issue by lauren-mills** [Microsoft/BotBuilder#3258]
## System Information
* SDK Language: .NET

## Issue Description
I cannot return any type except IMessageActivity to the ResumeAfter handler of a call to context.Forward. If I try to return any other type, I receive the error: "invalid type: expected Microsoft.Bot.Connector.IMessageActivity, have Boolean"

I want to combine my root LuisDialog and my QnAMakerDialog so that all messages go through Luis first, and if the intent is None, to forward the question to QnA maker, and if the result of the QnAMakerDialog is false, to give them the option to contact a human. I want to keep this routing logic in my LuisDialog, so while I could handle the contact piece inside the QnAMakerDialog, I don't think it makes sense. If there are no results from QnAMaker I want to return context.Done(false) and handle that result in my ResumeAfterFAQ handler.

If I am misunderstanding how context.Forward is designed, please let me know, but it seems like it could handle more use cases if it were more flexible.

## Code Example
From my LuisDialog:
```
        public async Task NoIntent(IDialogContext context, LuisResult result)
        {
            await context.Forward(new FAQDialog(), ResumeAfterFAQ, context.Activity, new CancellationToken());
        }

        private async Task ResumeAfterFAQ(IDialogContext context, IAwaitable<object> result)
        {
             try
            {
                var qnaResult = (bool)await result;

                if (!qnaResult)
                {
                    // Give user option to contact a human
                }
            }
            catch (Exception ex)
            {
                await context.PostAsync($"Failed with message: {ex.Message}");
            }
            finally
            {
                context.Wait(this.MessageReceived);
            }
        }
```

QnAMakerDialog:
 ```
public class FAQDialog : QnAMakerDialog
    {       
        protected override async Task DefaultWaitNextMessageAsync(IDialogContext context, IMessageActivity message, QnAMakerResults results)
        {
            if(results.Answers.Count > 0)
            {
                await base.DefaultWaitNextMessageAsync(context, message, results);
            }
            else
            {
                // return false because there were no results
                context.Done(false));
            }
        }
    }

```

**Comment by JasonSowers** [comment]
As the error message says it does not work like that.  Your best bet is to call Context.done and handle the handoff to a human based on `results >0` or not in your luis dialog or something along those lines.  closing this for now, feel free to reopen if you have any more questions.
