### ISSUE TITLE
Object Reference exception when validation fails on LUIS entity. #227

### ISSUE THREAD

**Issue by cwdyang** [Microsoft/BotBuilder#326]
This issue is still unresolved in botbuilder release 1.2.1, when a luis entity property is filled by luis and your formbuilding code invalidates the said property you get an "object reference not set to an instance of an object" exception with the Last property set to the name of the offending property.

We need this fix urgently, any assistance would be appreciated!

**Comment by ejadib** [comment]
I think that the fix was not release yet. Is on the development branch https://github.com/Microsoft/BotBuilder/commit/b142069284809bf2497399cd5a722a8d016c2969

**Comment by chrimc62** [comment]
We are working on a new release today.  Let us know if it does not fix it.
