### ISSUE TITLE
[Skype Web Control] Is showing postback in chat

### ISSUE THREAD

**Issue by wacton** [Microsoft/BotBuilder#3262]
## System Information
* SDK Language: .Net
* SDK Version: 3.9.0
* Development Environment:  App Service

## Bot Info 
* Bot handle: AskMichelleDevelopment
* App ID: cb285cec-f2cb-4043-9c23-2ac2ffae18ac
* Connected channels: Skype, Facebook

## Issue Description
We are using the Skype Web Control on our site. We use a fair amount of postback messages. It used to work fine, but sometime the last couple of days it started posting the postback message in the chat.
![skypewebcontrol](https://user-images.githubusercontent.com/2299141/28952790-fd4a9bb2-7916-11e7-9abf-f58ac4b3d9ad.png)

## Steps to Reproduce the Issue
1.  Create a bot with a postback action
2.  Add the Skype Web Control to any page
3.  Click the postback action 

## Expected Behavior
Expected the postback  to be sent  to the server

## Actual Results
Postback text is posted in chat and sent back as plain text.

**Comment by fms-santos** [comment]
I'm having the same issue since the sdk for the webcontrol has changed to `<script src="https://latest-swc.cdn.skype.com/sdk/0.24.37/sdk.js"></script>`

**Comment by mminchev** [comment]
I am experiencing the same issue. I tried to solve the problem temporarily by loading a previous version of the SDK - https://latest-swc.cdn.skype.com/sdk/0.12.2/sdk.js - however this does not seem to improve the situation.

**Comment by brene** [comment]
@fms-santos @mminchev sorry for the issue! We are actively working on a fix for this bug and marked it as high priority. Please use https://swc.cdn.skype.com/sdk/v1/sdk.min.js moving forward to receive the latest update. I'll update this thread when we have deployed the fix.

**Comment by fms-santos** [comment]
Thanks @brene . We'll do as you say. 
Also, a thing that is a bit annoying to me is the fact that we can't use different colors for the bot and the user's messages.

**Comment by brene** [comment]
@fms-santos actually, you can completely overwrite the CSS of the control. (Just don't mess with the placement of the Skype logo because of legal reasons). Create a <div class="skype-chat' data-css-url="https://yourdomain.com/some.css"></div> and then you can choose whatever color you like.

**Comment by fms-santos** [comment]
Didn't know that! Thanks again @brene, much appreciated ;)

**Comment by mminchev** [comment]
Thanks @brene! I am look forward to the fix as I am depending on Skype Web Control in order to complete a project for a client.

**Comment by brene** [comment]
@mminchev @fms-santos We have rolled out the update to 100% it's fixed now

**Comment by fms-santos** [comment]
Thanks @brene ! I can confirm that my bot is working as it should again. ;)

**Comment by brene** [comment]
@wacton can you close this ticket :-)

**Comment by wacton** [comment]
Thanks @brene !!
All good and working again. Appreciate it.
