### ISSUE TITLE
[Question] Bot posts duplicate messages when bad connectivity

### ISSUE THREAD

**Issue by iamarther** [Microsoft/BotBuilder#3264]
## System Information
* SDK Language: .NET
* SDK Version: v.3.9.0
* Development Environment: 

## Bot Info 
* Bot name: Planner Bot
* Bot handle: taskplannerbot
* App ID: 971ebb48-c75a-471c-bee8-3f85033430b6
* Connected channels: Skype

## Issue Description
Bot posts (random number of) duplicated messages on Skype channel when bad connectivity.

## Steps to Reproduce the Issue
1. Make Skype running in a bad internet connection.
2. Randomly post message out from Bot.

## Expected Behavior
I am not sure if Bot Builder itself has some special ensure of message receive and attempt logic but it should not post duplicate messages even if it failed to ensure message received.

## Actual Results
![b1f361aa00977709c1b1050ea5b1b01ab329f127119b276606 pimgpsh_fullsize_distr](https://user-images.githubusercontent.com/1333459/28964270-43107616-7936-11e7-9f50-a98641a05306.png)

After some repeat post messages it produces an exception that I could catch (in screenshot is when it post "Something went wrong..." message) which already attached here - [log.xlsx](https://github.com/Microsoft/BotBuilder/files/1199972/log.xlsx)

**Comment by JasonSowers** [comment]
@iamarther I have forwarded your question to the Skype team.

**Comment by JasonSowers** [comment]
please ropen if you are still experiencing the issue
