### ISSUE TITLE
[Question] Dialog Dependency Injection?

### ISSUE THREAD

**Issue by chris31389** [Microsoft/BotBuilder#3265]
I want to use Dialogs properly but I want to inject services and I don't want to have to use autofac and mark all my services and classes that use that service as serializable as I want to avoid serializing them as suggested in issue #938.

at the moment I have to add `[NonSerialized]` to the field and inject it like normal.  I then need to add a method like 

```
[Serializable]
public class Dialog : IDialog
{
    [NonSerialized] private IService _service;

    public Dialog(IService service)
    {
        _service = service;
    }

    [OnDeserialized]
    public void DeSerialize(StreamingContext context)
    {
        _service =
            GlobalConfiguration.Configuration.DependencyResolver
                .GetService(typeof(IService)) as IService;
    }

    // Rest of code 
}
```

Is there anyway of creating an attribute that can hook into the serialization and  deserialization event?
e.g. `[NonSerializedInstance]` which would re-inject `IService` from the GlobalConfiguration.Configuration

```
[Serializable]
public class Dialog : IDialog
{
    [NonSerializedInstance] private IService _service;

    public Dialog(IService service)
    {
        _service = service;
    }

    // Rest of code 
}
```

**Comment by JasonSowers** [comment]
@willportnoy @msft-shahins any thoughts?

**Comment by fanidamj** [comment]
Hoping that issue has been resolved, closing it. Feel free to reopen if any questions.
