### ISSUE TITLE
[Question] How are UserIDs generated?

### ISSUE THREAD

**Issue by xjose97x** [Microsoft/BotBuilder#3267]
Hello!

I'd like to know how are UserIDs are generated. I ask this because I have 2 bots connected to Facebook Messenger. I have them say the UserID of the person that is talking to them. And with the same facebook account, the bot is giving me a userid on one bot, and on the other one it is giving me another **different** userid.

I believe this happens as well on Skype and some other channels.

Thanks!

**Comment by JasonSowers** [comment]
@xjose97x  What are you trying to accomplish here?  What is your use case?   I ask because someone may have a work around for you.

I would have to go through the code, but my best guess is that a random string is generated when the conversation is initiated.  This would be why the IDs are different for different bots.

**Comment by xjose97x** [comment]
HI @JasonSowers , thanks for the quick reply!

I have on a database mapped the UserIds to know who the user is in every channel. This way i can know if SkypeUser == FacebookUser and do some logic there.

The thing is that I recently registered a second bot that will point my bot for production (this way I can have my bot for development separated from the production one). And I noticed that everything got messed up because the UserIds were different on this new bot than on my Development one, and therefore the UserIds I got on my database mapped did not work anymore for this instance.

I really doubt is a random generated string, there must be a logic on how those UserIds are generated. Perhaps there's a computation between the FacebookUserId and the BotHandler(BotId) that retrieves the UserID I got access on my activities?

Thanks, I really appreciate the help here!

**Comment by xjose97x** [comment]
Also the UserID we receive on our code (through the activities) must be generated/computed in the BotFrameworkConnector, because there's where the Activities are created and then sent to us on our BotFramework applications.

**Comment by xjose97x** [comment]
@JasonSowers

**Comment by PrasadGautham** [comment]
Just something I noticed, but not sure... I dont think the userids for skype and facebook will be same...because in facebook its the id on our profile link, that becomes our userid..This user id is specific to facebook right?..I think so...Not sure

**Comment by nrobert** [comment]
Hello @xjose97x ,

The User ID on Facebook Messenger Channel is a `Page Scope ID`, that is to say an ID that is depending on both the user AND the page of your bot.
Your 2 bots are connected to 2 different pages, right?

**Comment by EricDahlvang** [comment]
Hi @xjose97x 

Bot Framework documentation describes how ids are generated here: https://docs.microsoft.com/en-us/bot-framework/resources-identifiers-guide#channel-account For channel specific ids, you would need to consult that channel's documentation.  It appears that @nrobert has provided the information you're looking for in regards to Facebook specifically, so I'm closing this issue.
