### ISSUE TITLE
[Skype] ACL check failed

### ISSUE THREAD

**Issue by abharku** [Microsoft/BotBuilder#3268]
## System Information
* SDK Language: Rest Api
* SDK Version: V3.5
* Development Environment: AWS

## Bot Info 
* Bot name: Starfish Me, Starfish Audio, Starfish Track, Starfish UK
* Bot handle: starfish_me,starfish_audio,starfish_track,starfish_uk
* App ID: d9a42ec7-d6b2-4ac5-838c-d944a02ce2e0
* Connected channels: Skype,Telegram,Web,Facebook Meesenger

## Issue Description
Everything works from my account but if I use a different account It keeps giving me ACL check failed warning and the call never reaches our server. Its all approved. Also we can't search them as bot in Skype directory.

## Code Example
No relevant code. 

## Steps to Reproduce the Issue
1. Its not working from my other account so may be try from some other account. Warnings are available to view in the console
2.
3.

## Expected Behavior
Expect it to work for others like its working for me

## Actual Results
ACL Check failed

**Comment by nwhitmont** [comment]
@abharku 

>Everything(1) works from my account(2) but if I use a different account(3) It keeps giving me ACL check failed warning(4) and the call never reaches our server(5). It's all approved(6). Also we can't search them as bot in Skype directory.(7)

Just to clarify:
1. What is "everything" specifically?
2. What is "my account" specifically?
3. What is "a different account"?
4. Where do you see the "ACL check failed" warning exactly? Screenshot?
5. Does your server have a valid SSL certificate?
6. What exactly is "all approved"?
7. Bots are not searchable in the Skype directory. You need to use the "join" URL linked from the "Skype" text label in the Bot Portal channels page.

**Comment by abharku** [comment]
1. All functionality of the bot works which is everything
2. The account which is used to define the bot channels at https://dev.botframework.com/
3. A skype account which is not the owner of the bots
4. screenshot attached 
![screen shot 2017-08-04 at 22 58 36](https://user-images.githubusercontent.com/1357604/28988630-96f1746a-7968-11e7-93d9-745ce092a2a6.png)
5. Yes, Like I said it works for me and SSL is valid otherwise I will have bigger problem than this as it's our production URL and all our resources are secured.
6. We submitted bot for channel approval and its approve on skype so some one must have tested it and it worked for them too.
7. Thanks for clarifying this so marketing of bots is entirely up to us which is fair as long as it's clear.

Hope it's more clear now.

**Comment by nwhitmont** [comment]
@abharku thanks for the update

**Comment by nwhitmont** [comment]
@abharku If I'm understanding you correctly, you have added to bot to the contacts of a Skype user (not the bot owner's Skype account), but the bot does not respond to that user?

**Comment by abharku** [comment]
@nwhitmont Yes I can see you in the logs and that's the correct functionality as all our bots require account linking.

I still can't get it to work from my other accounts though and I had cleared a lot of those warnings when I last logged in so it's definitely happening to other live users as well, who get no response. Any chance we can check the above two entries in the screen shot and see what went wrong with them. It will be likely some account settings which does not allow bots?

**Comment by abharku** [comment]
@nwhitmont Actually one of my bots work with my other account  (not the bot owner's Skype account) as well but 4 others listed above in this issue don't so it can't be users account. Starfish Groove works if you need to compare anything.

**Comment by nwhitmont** [comment]
When the bot sends a message to the user, Skype backend checks that the user has added the bot to user contact list. This is called ACL (access control list) check. If the return code is 403 it means that the user removed the bot from contacts. It may also mean that the check failed for some other reason, and I would expect return code to be 500 or 503.

**Comment by abharku** [comment]
@nwhitmont actually it worked when I right clicked and Added to contacts in the skype chat window. I had previously used the Add to contact link provided at Embed in website link on the development portal.

All the links are listed here https://www.starfishmint.com/bots/#five

When I click Add to contacts it opens up a web page with Add to contacts button and when I click that it takes me straight to skype with chat window open to talk to the bot. Shouldn't that link also add to contacts? I am not sure how I am suppose to explain it to users that you need to add to contact once via this link and then again right click in left panel and Add to contacts?

**Comment by nwhitmont** [comment]
@abharku The "add to contacts" link should add the bot to the user's Skype contacts without any additional steps. If it doesn't, that's a different bug entirely!

**Comment by abharku** [comment]
@nwhitmont thanks for helping. I tested with other users and it appears it adds to their contact straight away. 

I think I must have tried from dev portal to link with a skype which is signed in with not bot owner. I will close this issue. Thanks again for being so responsive

**Comment by nwhitmont** [comment]
@abharku Thanks for the update. Glad to hear you got it working. 👍

**Comment by Ddiazpal** [comment]
Hi, i am having this problem too. I don't know how can I solve this. I would really appreciate if you can help me. 
!
[ima1](https://user-images.githubusercontent.com/35104487/39278284-f4868510-48b7-11e8-9476-10eef1fde29d.PNG)

**Comment by EricDahlvang** [comment]
@Ddiazpal afaik, "ACL check failed" occurs when the user has removed the bot from their contacts and then the bot attempts to send them a message.  Could that be the case for you?

**Comment by Ddiazpal** [comment]
@EricDahlvang I don't Know i add the bot to my Skype contacts and on Skype i send the message but i never get the answer back. I donn't know, Is there any step that i'm missing? 

![image](https://user-images.githubusercontent.com/35104487/39278651-f7e29346-48b9-11e8-8130-bad6533beff0.png)

![image](https://user-images.githubusercontent.com/35104487/39278735-74dd8fa4-48ba-11e8-816e-b537fe977bd1.png)
