### ISSUE TITLE
Recommendation on using multiple LUIS models

### ISSUE THREAD

**Issue by jakobpn** [Microsoft/BotBuilder#327]
My LUIS model has reached the 20 intent limit and I need to split the model into several models to go beyond that. Do you have any recommendations on what to do in order to have a bot work with multiple LUIS models? Is this something that the Bot Framework is already capable of?

**Comment by Stevenic** [comment]
Are you using C# or Node?

**Comment by jakobpn** [comment]
C#

**Comment by IanBoggs** [comment]
I don't know if the Framework makes it feasible or not. Would be nice to know as we have been thinking about this with regards to a situation of having similar utterances for different intents. We were considering having a sort of generic top level LUIS that determined an overall area (such as documentation or diary) and then having a more specific LUIS that covers the utterances in that area. A sort of hierarchy of models.
I would stress that we haven't actually tried this approach as yet

**Comment by msft-shahins** [comment]
This is a limitation on the [luis.ai](https://www.luis.ai/) service and not the bot builder SDK. As @IanBoggs mentioned you can use a command dialog or a broader Luis model to categorize the incoming message and then forward the message to the right Luis model for more fine grained entity and intent recognition.

**Comment by knk1988** [comment]
@msft-shahins I need a recommendation from you. I need to use multiple LUIS model as there is a limitation of only 20 intents per LUIS model. I don't seem to fit all my utterances within these intents and I might need more. So, how would I categorize the incoming message and route it to the appropriate LUIS model? Any help would be much appreciated!

**Comment by msft-shahins** [comment]
@knk1988 you can have a top level Luis model that do the categorization for the incoming message and then forward the message to a more specialized Luis model for intent recognition based on the category.

**Comment by sp2013hem** [comment]
@knk1988 Hi there, I am stuck with same problem, I would like to know, what was your approach on resolving this block?

**Comment by botgas** [comment]
@msft-shahins Once our top level LUIS model does the categorization of the incoming message how do I redirect the message to the specialized LUIS model because everything that goes to the LUIS model is through the myBot.listenStdin() command.

**Comment by msft-shahins** [comment]
@botgas  If you are using C# SDK, you can forward the message to another dialog using context.forward(...). @Stevenic can comment for node.js.

**Comment by botgas** [comment]
@Stevenic can you please tell the way for the same in node.js. I'm sorry, I forgot to mention that I am using the node.js SDK.

**Comment by javi-jamaa** [comment]
HI @Stevenic , can you send me an example to do this Node.js? Huge thanks.

**Comment by Stevenic** [comment]
sure... 

```
var recognizer1 = new builder.LuisRecognizer('<model 1>');
var recognizer2 = new builder.LuisRecognizer('<model 2>');
var intents = new builder.IntentDialog({ recognizers: [recognizer1, recognizer2] });
```

**Comment by b4usat** [comment]
hi @Stevenic can you please give a sample for C# SDK for the same problem. I tried decorated my class with 2 Luis models. But by default it identifies the "None" Intent of one of the model. How can i solve this>
`   [LuisModel("xxxx", "yyyy")]`
  `  [LuisModel("aaaa", "bbbb")]`
   ` [Serializable]`
   ` public class AbacusForm : LuisDialog<object>`
   ` {`
    ` }`

**Comment by suresh-mobilocity** [comment]
Is there a limit to how many entities can be defined for an application? I am not able to add another entity after 10.

**Comment by brandonh-msft** [comment]
@suresh-mobilocity yup - that's the limit :)

**Comment by suresh-mobilocity** [comment]
I did not understand how I can create a model or multiple models under the same application? Is the meaning of "multiple LUSI Model" referred in the original question referring to defining more than one App?

**Comment by brandonh-msft** [comment]
@suresh-mobilocity it's not multiple models under the same app, but rather multiple apps under your LUIS account. 

One way we've seen this done is creating a LUIS App for various "specialties" of your bot.

Example:
bot: "hi, i can help you with applying for a license or paying a fine"
"pay a fine"
all subsequent dialog -> Luis Application A

"apply for a license"
all subsequent dialog -> Luis Application B

**Comment by suresh-mobilocity** [comment]
@brandonh-msft , thank you for clarifying my questions.

**Comment by Chitma** [comment]
@suresh-mobilocity - hi, even I am not able to use multiple Luis Models. Have you got the solution for this issue?.If yes ,can you please provide the solution.
Thanks.

**Comment by ricklove** [comment]
@brandonh-msft Thanks for recommending that!

Selecting the correct luis app and keeping track of that context, makes more sense for performance and preventing collisions than a hierarchy of luis apps.

If you can select the correct luis app at the beginning of the interaction, then you can continue in that context assuming that luis app. (It is also possible to navigate between apps if each app learns an exit intent which sends that request back to the root model.)

In this way, you always assume the user is continuing with the same luis app context unless there is a intent that allows them to navigate to a different context, so most of the time you only need 1 luis request to discern intent and different apps can have similar intents without conflict.

This is better than a hierarchy of luis apps: The problem with a hierarcy of models is that if you have 2 models that have similar intents, the main model may not be able to know which sub model to use for continued processing. Also, every input requires 2 requests (the main luis app, and the sub luis app). This doubles costs and decreases performance.

**Comment by ryzam** [comment]
@ricklove with this method, we need to have same utterance in 2 apps, one in the root app and another one in the specific apps?

**Comment by ricklove** [comment]
@ryzam, Well, each bot has it's own context and you have to have an external logic that chooses the correct one. You might want to look at api.ai if you need many intents more than the 15 supported by luis.ai

**Comment by mikob** [comment]
I currently have 23 intents, it seems the limit was raised. But I can't find in the docs what it was raised to.

**Comment by kcyhm1991** [comment]
It would seem so, likewise, unable to find the documentation stating this, I have created >40 intents to test the limit and have not been hit with an error message yet!

**Comment by BenjaBobs** [comment]
According to [this](https://cognitive.uservoice.com/forums/551524-luis/suggestions/15088233-more-than-20-intents-for-luis#{toggle_previous_statuses}) the limit was raised to 40, but there may be a more recent change.

**Comment by andradedearthur** [comment]
@kcyhm1991 @BenjaBobs @mikob I did some tests and was able to create 79 intents, plus the none intent. So 80 intents in the total. Still a far cry behind IBM Watson's limit.

**Comment by brandonh-msft** [comment]
@andradedearthur and you hit a limit at this point? what was the error message?

**Comment by dev4201** [comment]
@kcyhm1991 @andradedearthur - just curious, how do you guys manage such a large number of intent responses at the application layer, any particular pattern that you found to be most applicable?

**Comment by sdharshraj** [comment]
Now the limit is 80 for Intents and 30 for entities.
That's fine but what next, after 80 intents if i have to use another luis instance how can i manage to use the other luis instance in same project.

**Comment by sdharshraj** [comment]
@dev4201 . it depends on situation you are dealing with, of you are handling FAQ scenario there you can have a pattern configured in some json file or somewhere and you can make one generic method to handle  the questions even you can handle the entities in the configuration and based on entities you can respond back. This flexibility you will not get with Q&A maker

**Comment by henriquehfr** [comment]
@ricklove, sorry for asking almost an year later, but how can this be done?

I can't find a way to isolate the LUIS model for the subsequent dialogs. My application always try to recognize the utterances in all active recognizers.

I'm using one recognizer per library btw.

**Comment by ricklove** [comment]
I'm not sure what you are using to implement it, but basically you need to have a hierarchy of models:

The first NLP model will select the category of your request.
Then you have multiple 2nd level NLP models that would handle requests of a specific category.

That is the concept anyway, whether it works or not is a different question.

Obviously a single model that can identify all intents is the preferred option.

**Comment by henriquehfr** [comment]
@ricklove I've solved this using the [LuisRecognizer `onEnabled` function](https://docs.botframework.com/en-us/node/builder/chat-reference/classes/_botbuilder_d_.luisrecognizer.html#onenabled).

At the `botbuilder` middleware level, I've tracked all messages that matches an specific intent or regex. Then, on the `onEnabled` function I've applied a filter to enable or disable all recognizers accordingly to the current library context.

If it is at the root level, only the main LUIS model will be enabled. Otherwise, all other recognizers will be active, but isolated by the dialog stack scope.

This way they will not conflict with each other.

**Comment by limsammy** [comment]
@henriquehfr @ricklove @brandonh-msft 

I know this is several months old, but my team and I are in this exact same scenario. 

One of our ideas was to utilize the methodology in [this](https://github.com/alyssaong1/botframework-smalltalk#integrating-with-your-existing-luis-model) to map dialogs to intents (we will have far more than the 80 limit threshold).

What that smalltalk module does is create an excel spreadsheet containing utterances and intent messages. This is uploaded to QnA maker. _'In the bot, the result from QnA maker is mapped to a list of possible responses'_ and a response is chosen at random.

Our idea is to use this method to create a large excel dataset of intents and utterances. Does that make sense?
