### ISSUE TITLE
[Question] Starting a dialog from conversationUpdate event

### ISSUE THREAD

**Issue by assaf-cream** [Microsoft/BotBuilder#3270]
Hi everyone
Following issue #1930 which is closed, there is still a problem with starting a dialog at the conversationUpdate event (I'm using Node.js version).

The issue ends with this comment by @Stevenic : 

> Unfortunately, we currently track conversations on a per/user basis so calling bot.beginDialog() when the bot joins isn't going to do what you want. We need to add the ability to start a conversation with a group which we've talked about but haven't implemented yet.

There is still an issue with starting a conversation from this event, as I don't get any answer to a message send using beginDialog

Are there any plans to handle this issue?

Thanks

**Comment by nwhitmont** [comment]
@assaf-cream It's on our roadmap, but I don't have any specific timeline to share right now.
