### ISSUE TITLE
[Question] Video Card does not render in Skype but renders in Emulator

### ISSUE THREAD

**Issue by datasigntist** [Microsoft/BotBuilder#3272]
## System Information
* SDK Language: Node.js
* SDK Version: 3.8.4
* Development Environment: 

## Bot Info 
* Bot name: JustInTimeLearning
* Bot handle: jitLearning 
* App ID: 9c1c33de-b881-4e7d-aba2-d006d90d225f
* Connected channels: Skype

## Issue Description
I am developing using node.js. The video card simply does not render in Skype (mobile or desktop (checked both mac and win 10) whereas the emulator renders picture perfect. Here is my code base, let me know where I am going wrong.

                        var card =  new botBuilder.VideoCard(session)
                        .title(pretrievedContent.contentDescription)
                        .media([{ url: pretrievedContent.contentURL }])
                        .image([{}])
                        .buttons([botBuilder.CardAction.openUrl(session, pretrievedContent.contentURL, 'Full Screen')]);
                        var msg = new botBuilder.Message(session).addAttachment(card);

                        session.send(msg);

## Steps to Reproduce the Issue
1.
2.
3.

**Comment by JasonSowers** [comment]
As per the readme here https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/cards-RichCards  

Note: At the time of writing this sample, Skype requires the Video card to have a Thumbnail Url.

**Comment by JasonSowers** [comment]
Also there is a known issue with audio and video cards not working on skype mobile.  If your problem still persists please reopen this issue.
