### ISSUE TITLE
TesterbotAndrey

### ISSUE THREAD

**Issue by AndreyShakhtarin** [Microsoft/BotBuilder#3273]
## System Information
* SDK Language: 
* SDK Version: 
* Development Environment: 

## Bot Info 
* Bot name: tester bot Andrey
* Bot handle: test_value
* App ID: 
* Connected channels: 

## Steps to Reproduce the Issue
1.
2.
3.

**Comment by stevengum97** [comment]
Please provide the SDK, the version being used, the problem you're running into and the code you're using when you experience the problem.

**Comment by JasonSowers** [comment]
Please reopen when you are able to provide us with details so we can assist you

**Comment by AndreyShakhtarin** [comment]
okey
