### ISSUE TITLE
[Question] Multi-lingual support for "Out of Box" Confirm prompt?

### ISSUE THREAD

**Issue by PrasadKosaraju** [Microsoft/BotBuilder#3275]
## System Information
* Node.js
* Azure Bot Service
Issue:
 I'm using water-fall bot currently which supports English. I'm planning to change to support Multi-lingual using Microsoft Translator API and Text Analytics. For all custom dialog and prompt i can do this. I was stuck how i can do multi-lingual for Confirm prompt. Let's say if the user types something which bot doesn't understand it will ask as below. This OOB capability and want to understand how this can be multi-lingual

"I didn’t understand. Please answer ‘yes’ or ‘no’."

## Code Example
builder.Prompts.confirm(session, 'Are you using your email address as your user name? ', ['yes', 'no']);

Here if the user enters something else other than yes or no. we get below message which is OOB. Need help how that can be mult-lingual
"I didn’t understand. Please answer ‘yes’ or ‘no’."

**Comment by stevengum97** [comment]
Does OOB in this context mean Out-of-bounds? I don't understand what OOB is. 

How many languages are you planning on supporting? Are you just planning on setting it up globally to handle *every* possible language via translator and text analytics API?

**Comment by PrasadKosaraju** [comment]
OOB - Out of Box.  Yes we want to setup globally for all languages eventually but not for pilot launch. i'm stuck how to translate some of them which is coming out of box which i specified below. This is comes from Bot framework and not handled by me

"I didn’t understand. Please answer ‘yes’ or ‘no’."

**Comment by nwhitmont** [comment]
OOB == default messaging text found in BotBuilder.js localization file.

For more information on localizing prompts see:
https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-localization#localize-prompts

>The default localization system for the Bot Builder SDK is file-based and allows a bot to support multiple languages using JSON files stored on disk. By default, the localization system will search for the bot's prompts in the `./locale/<language_tag>/index.json` file where is a valid IETF language tag representing the preferred locale for which to find prompts.

**Comment by PrasadKosaraju** [comment]
Sorry i didn't find this path in Azure Bot Service..

**Comment by nwhitmont** [comment]
@PrasadKosaraju You need to configure Continuous Integration for your bot code, and add the localization files yourself.

**Comment by nwhitmont** [comment]
relates to http://dailydotnettips.com/2017/07/18/setting-up-continuous-integration-for-azure-bot-services/

**Comment by PrasadKosaraju** [comment]
Tried with index.json for localization of confirm prompts..But still it's i enter yes or no it's not routing properly. Please let me know if i'm missing something. Here is the code

function (session) {
        //builder.Prompts.confirm(session, 'Did this re-solve the issue? ', ['yes', 'no']);
		//userLocale= session.preferredLocale();
		userLocale=session.conversationData.locale;
		var confirm_prompt=session.localizer.gettext(userLocale, "confirm_prompt");
			var confirm_yes=session.localizer.gettext(userLocale, "confirm_yes");
			var confirm_no=session.localizer.gettext(userLocale, "confirm_no");
			//console.log("confirm_prompt:::::"+confirm_prompt);
			builder.Prompts.confirm(session, confirm_prompt,[confirm_yes,confirm_no]);
    },
    function (session, results) {
session.send("You entered ::::::'%s'", results.response);

}
