### ISSUE TITLE
[Question] Open Skype Bot with join URL+ query params and pass in data?

### ISSUE THREAD

**Issue by suvamsh** [Microsoft/BotBuilder#3276]
## System Information
* SDK Language: Node.js
* SDK Version: 3.8.4
* Development Environment: localhost or Auzure Bot Service

## Issue Description
How can I open a Skype bot via a link while passing in some data? This is similar to how Facebook Messenger bots can do the same using a m.me/BotName?ref=1234. Is this possible in Skype?

**Comment by nwhitmont** [comment]
@suvamsh This is not currently a feature of Skype.
