### ISSUE TITLE
[Question] Line breaks in Thumbnail/HeroCards working incorrectly in Skype?

### ISSUE THREAD

**Issue by 250blahblah** [Microsoft/BotBuilder#3277]
## System Information
* SDK Language:  .NET
* SDK Version:  
* Development Environment:  App Service, .NET

## Bot Info 
* Bot name: Osmo1
* Bot handle: osmo1
* App ID: bf726d1d-a6dc-46fa-bea6-4d2a240cff1a
* Connected channels:  Skype, WebChat, Emulator

## Issue Description
Line breaks in subtitle+text of Thumbnail+HeroCards function incorrectly in Skype. The line breaks, but only the first line is visible and the rest of the lines are replace by ellipses (Skype mobile on Android) or just simply invisible (Skype web). The line breaks function correctly in the emulator though... 

## Code Example

```
HeroCard plCard = new HeroCard()
{
	Title = "I'm \r\r a hero \n\r card",
	Subtitle = " Wikipedia \r\r Page \n\r test",
	Text = "line 1 \r\r line 2 \n\r line 3 \r line 4"
};
```
## Expected Behavior
Line breaks to function correctly

## Actual Results

Only first line visible, all others invisible (Skype Web) or ellipses (Skype Android).
![bug](https://user-images.githubusercontent.com/23667587/29013722-8948fbd4-7b62-11e7-94f8-0ecbe990550c.PNG)

**Comment by megancooper** [comment]
@250blahblah Does using <br> instead of markdown work for you? I haven't tried this yet with Thumbnail cards but it works great with Hero Cards.

**Comment by JasonSowers** [comment]
@250blahblah Your code shows a hero card, but your question title says thumbnail.  Is this not working for both?

**Comment by 250blahblah** [comment]
Question edited appropriately :)

**Comment by JasonSowers** [comment]
@250blahblah thanks

**Comment by 250blahblah** [comment]
@megancooper the XML markup will only work in Skype though right? Other channels don't have it supported as far as I know. Is there any way to determine what channel the bot is running in, and thus be able to alter the text such that it displays evenly across channels (\n\n works in the emulator, for instance)?

**Comment by megancooper** [comment]
@250blahblah Here is one way you could potentially detect the channel in your code:

public static async Task method(IDialogContext context, IMessageActivity msg)
{
      switch (msg.ChannelId)
      {
                case "skypeforbusiness":
                    // Do Something Specific
                case "emulator":
                case "skype":
                {

                }
                case "msteams":
                {

                }
                default:
                {

                }

        }
}

**Comment by nwhitmont** [comment]
If you use `xml` text type, then use `<br/>` --> must be self-closing tag version of br tag, `<br>` won't work.

**Comment by EricDahlvang** [comment]
@250blahblah Please use the suggestions by nwhitmont and megancooper.  `<br/>` will provide the functionality you're looking for in Title, SubTitle and Text.  

The following code:

```cs
var reply = ((Activity)context.Activity).CreateReply(string.Empty);
reply.Attachments = new List<Attachment>();
string newLine = activity.ChannelId == ChannelIds.Skype ? "<br/>" : "\n\n";
var heroCard = new HeroCard()
    {
        Title = $"Title{newLine}next title line.",
        Subtitle = $"Sub Title{newLine}next sub title line.",
        Text = $"Hero Card Text{newLine}next line!"
    };
reply.Attachments.Add(heroCard.ToAttachment());
               
await context.PostAsync(reply);
```

Will produce the following results in skype web and skype desktop (windows):

![image](https://user-images.githubusercontent.com/11055362/29150223-fcb8af70-7d2d-11e7-9737-3a595ce66e58.png)
