### ISSUE TITLE
How to register BOT with Skype for  business (internal to Microsoft)

### ISSUE THREAD

**Issue by pradeepvengala** [Microsoft/BotBuilder#3278]
Hi Team, 

Could you please provide pointers on how to register bot with Skype for Business for internal to Microsoft?

Please let us know.

**Comment by stevengum97** [comment]
You can find documentation on how to register a bot for Skype for Business [here](https://docs.microsoft.com/en-us/bot-framework/channel-connect-skypeforbusiness) and the continuation of these instructions [here](https://msdn.microsoft.com/en-us/skype/Skype-For-Business-Bot-Framework/docs/overview).
