### ISSUE TITLE
Facebook Messenger bot keeps looping to the same dialog

### ISSUE THREAD

**Issue by jw84** [Microsoft/BotBuilder#328]
Building on BotBuilder with Node.JS and connecting to Facebook Messenger. 

All that's working fine, the issue is that after the user and bot engage the conversation and the user re-engages it gets stuck with the middle part of the conversation.

For example, from ./dialogs/index.js

```
function addDialogs(bot, addressConvert) {
	bot.add('/', new builder.CommandDialog()
		.matches('^(hello|yo|hi|hey)', builder.DialogAction.send(welcomeActions))
		.matches('^(help)', builder.DialogAction.send(prompts.helpMessage))
		.matches('^(new)', '/createCode')
		.matches('^(verify)', '/verifyCode')
		.matches('^(share)', '/shareCode')
		.matches('^(optout)', '/optout')
		.matches('^(optin)', '/optin')
		.matches('^(bye|quit)', builder.DialogAction.endDialog(prompts.endMessage))
		.onDefault(builder.DialogAction.send(randomDefault())))

	// add dialogs for commands
	createCode.addDialogs(bot)
	verifyCode.addDialogs(bot)
	shareCode.addDialogs(bot)
	optout.addDialogs(bot)
	optin.addDialogs(bot)
}
```

The bot skips the "hello", "help" and even skips the slash commands and only loops the verifyCode, shareCode dialogs.

In verifyCode:

```
function addDialogs(bot) {
	bot.add('/verifyCode', [
		function (session) {
			builder.Prompts.text(session, prompts.haveCodeMessage)
		},
		function (session, results) {
			if (verifyCodes(results.response)) {
				session.send(prompts.sendCodeMessage1)
				session.send(prompts.sendCodeMessage2)
				session.beginDialog('/shareCode')
			} else {
				session.send(prompts.codeFailMessage1)
				session.beginDialog('/optin')
			}
		},
	])
}
```

The session keeps going to:

```
function addDialogs(bot) {
	bot.add('/optin', [
		function (session) {
			builder.Prompts.confirm(session, prompts.codeFailMessage2)
		},
		function (session, results) {
			if (results.response) {
				session.send('YOU ARE IN')
			} else {
				session.send('YOU ARE OUT')
			}
			session.endDialog(prompts.endMessage2)
		},
	])
}
```

In Messenger, the conversation will always loops to verifyCode, concludes with endDialog in optin. I can't seem to reset the conversation or trigger the other dialogs.

Any insight?

**Comment by Stevenic** [comment]
You need another waterfall step at the end of the waterfall in '/verifyCode' that calls `endDialog()` to return back to the root '/' dialog. Something like:

```
function (session) {
   session.sendDialog();
} 
```
This is a tricky situation for me. I technically know there's a chance you're going to be stuck in that dialog but I don't know what your logic is so I can't safely call endDialog() for you.

**Comment by Stevenic** [comment]
I'm going to think about this a bit more but I think I may make the waterfall auto-end in this particular situation. The 95% case is you want the waterfall to end and return to the previous dialog. The thing I need to think about is in the 5% case where you don't is there an easy enough way to achieve that.

**Comment by Stevenic** [comment]
The waterfall now ends the dialog automatically in version 1.0.0 so it should work the way you expect now.

**Comment by SunSeaAndPalms** [comment]
Seems like we are experiencing a very close one. BotFramework is able to switch between intents unless NONE intent is received. If NONE it defaults to LAST intent.
