### ISSUE TITLE
[Question] Rich Cards (Attachments) not working in MS Teams & Skype channels

### ISSUE THREAD

**Issue by pradeepvengala** [Microsoft/BotBuilder#3282]
## System Information
* SDK Language: .NET 
* SDK Version: 3.8 (Runtime Version# v4.0.30319)

## Bot Info 
* Bot name: AzureSpendBOT
* Bot handle: azurespendbot   
* App ID: 022a7a28-5407-4edb-9698-45e0e9dc5267
* Connected channels: Skype, MS Teams

## Issue Description
Rich Cards (attachments) are not showing in Microsoft Teams, Skype. I can only see the cards in BOT Emulator. 

## Expected Behavior
Cards should display in Skype, MS Teams & Skype for Business
## Actual Results
Not showing up cards in Skype, MS Teams.
[BOT_CardsNotShowingUpInSkypeMSTeams.docx](https://github.com/Microsoft/BotBuilder/files/1206420/BOT_CardsNotShowingUpInSkypeMSTeams.docx)

**Comment by JasonSowers** [comment]
@pradeepvengala can you please provide the code you are using to construct the card and attachments?

**Comment by pradeepvengala** [comment]
Hi Jason,

Here is the code snippet that construct the card:
public IList<Attachment> GetResourceGroupCards(List<BOTMessage> azureSpendData)
        {
            List<Attachment> botAttachments = new List<Attachment>();

            foreach (BOTMessage azurespend in azureSpendData)
            {
                var azureSpendCard = new ReceiptCard
                {
                    Title = (azurespend.messageType == MessageType.ResourceGroup) ? (azurespend.ResourceGroupName) : (azurespend.ResourceName),
                    Facts = new List<Fact> { new Fact("(Resource", "Group)"), new Fact("Subscription", azurespend.SubscriptionName) },
                    Items = new List<ReceiptItem>
                {
                    new ReceiptItem("Current", price: "$ "+ azurespend.Current, quantity: "", image: new CardImage(url: "https://raw.githubusercontent.com/pradeepvengala/SymbolsTest/master/1-present-traffic-manager.png")),
                    new ReceiptItem("Previous", price: "$ "+ azurespend.Previous, quantity: "", image: new CardImage(url: "https://raw.githubusercontent.com/pradeepvengala/SymbolsTest/master/12-previous-scheduler.png")),
                    new ReceiptItem("Change", price: "$ "+ azurespend.Change, quantity: "", image: new CardImage(url: "https://raw.githubusercontent.com/pradeepvengala/SymbolsTest/master/3-change-cloud-service.png")),
                    new ReceiptItem("WoW", price: azurespend.WoW + " %", quantity: "", image: new CardImage(url: ((azurespend.WoW < 0) ? ("https://raw.githubusercontent.com/pradeepvengala/SymbolsTest/master/4-green-arrow.png") : ("https://raw.githubusercontent.com/pradeepvengala/SymbolsTest/master/5-red-arrow.png"))))
                },
                    Buttons = new List<CardAction>
                {
                    new CardAction(
                        ActionTypes.OpenUrl,
                        "Azure Portal",
                        "https://raw.githubusercontent.com/pradeepvengala/SymbolsTest/master/7-azure.png",
                        string.Format("https://ms.portal.azure.com/?feature.relex=*%2CHubsExtension#resource/subscriptions/{0}/resourceGroups/{1}/overview",azurespend.SubscriptionGUID, azurespend.ResourceGroupName)),

                        new CardAction(
                        ActionTypes.OpenUrl,
                        "Azure Spend",
                        "https://raw.githubusercontent.com/pradeepvengala/SymbolsTest/master/6-azurespend.png",
                        string.Format("https://azurespend.msftcloudes.com/azurespend/Week/ResourceGroup/{0}~2F{1}/Summary",azurespend.SubscriptionGUID, azurespend.ResourceGroupName))


                }
                };

                botAttachments.Add(azureSpendCard.ToAttachment());
            }

            return botAttachments;
        }


Calling the constructed card as below:
message.AttachmentLayout = AttachmentLayoutTypes.Carousel;

                ResourceGroupCard rgCard = new ResourceGroupCard();

                message.Attachments = rgCard.GetResourceGroupCards(azureSpendRGDetails);

                await context.PostAsync(message);

Please let me know what is the issue and fix it.

Thanks,
Pradeep

**Comment by JasonSowers** [comment]
I am able to reproduce this in skype and teams. I have reached out to the skype team. @RichMoeMSFT any thoughts?

**Comment by pradeepvengala** [comment]
Thanks Jason.

This is blocking our GO LIVE date. Could you please provide a solution to make the rich cards work in MS Teams/Skype for business.

Thanks,
Pradeep

**Comment by pradeepvengala** [comment]
Team, any new update please?

**Comment by RichMoeMSFT** [comment]
It looks as if you are using a Receipt Card - they aren't support in Teams yet.

https://msdn.microsoft.com/en-us/microsoft-teams/botsmessages#cards

**Comment by pradeepvengala** [comment]
Hi Richard,

Does Cards supported in Skype for Business?

We would ask our users to use Skype for Business instead MS Teams.

Also, is there any documentation that clearly explains what is supported in Skype for Business, that would avoid unnecessary development cost.

Please let me know.

Thanks,
Pradeep

**Comment by pradeepvengala** [comment]
Hi Richard,

In addition to previous questions, Does Skype for Business support Cards? If no, is there any near in time support?

Appreciate you quick response.

Thanks,
Pradeep

From: Pradeep Vengala (HCL America Inc)
Sent: Tuesday, August 15, 2017 2:43 PM
To: 'Microsoft/BotBuilder' <reply@reply.github.com>; Microsoft/BotBuilder <BotBuilder@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [Microsoft/BotBuilder] [Question] Rich Cards (Attachments) not working in MS Teams & Skype channels (#3282)

Hi Richard,

Does Cards supported in Skype for Business?

We would ask our users to use Skype for Business instead MS Teams.

Also, is there any documentation that clearly explains what is supported in Skype for Business, that would avoid unnecessary development cost.

Please let me know.

Thanks,
Pradeep

**Comment by RichMoeMSFT** [comment]
As I'm not on the SfB team, I can't speak with certainty but the documentation points out that cards are not yet supported: https://msdn.microsoft.com/en-us/skype/skype-for-business-bot-framework/docs/overview

**Comment by pradeepvengala** [comment]
I see cards are supported in MS Teams and Skype.

But it’s not working in MS Teams and Skype, why?

Thanks,
Pradeep

**Comment by EricDahlvang** [comment]
Hi @pradeepvengala 

Some card types are supported in Teams and Skype, but not every card type.  There is currently no hard set timeline or date for these features, but the development teams are actively working on them.  We apologize for the inconvenience.   

Please consider using the supported card types on the channels your bot is deployed on.  Also, please note that the Microsoft Bot Framework is heading towards General Access (hopefully this year), but at this time it is still a preview product. 

Thank you for your patience.
