### ISSUE TITLE
[Question] Maintain chat history in WebChat window?

### ISSUE THREAD

**Issue by rachita0311** [Microsoft/BotBuilder#3284]
I have to maintain chat in chat window whenever I switch my web pages. I am using webchat and I have places the webchat on layout.cshtml whenever I am switching to another page my webchat gets refreshed. Is there a way in which I can persist data in my chat window

**Comment by nrobert** [comment]
Could you please fill the formulary correctly to add more context about your request?

I guess you are using ASP.Net MVC here, so you should have a look on "how to avoid layout refresh" or similar requests on StackOverflow.
For example you will see that this answer suggest to use `PartialView` : https://stackoverflow.com/questions/12501611/how-to-avoid-layout-reloading

**Comment by nwhitmont** [comment]
@rachita0311 Are you using .NET or Node.js SDK?

**Comment by JasonSowers** [comment]
@rachita0311 please reopen and continue the conversation if this does not help, good luck

**Comment by rachita0311** [comment]
I am using. Net

**Comment by brene** [comment]
In case you're interested. Skype Web Control offers chat history persistence through Skype infrastructure. https://dev.skype.com/webcontrol

**Comment by JasonSowers** [comment]
@rachita0311 a solution for this is in the pipeline, no ETA yet.
