### ISSUE TITLE
[Question] Advice on Hardware Scaling of the Bot Service?

### ISSUE THREAD

**Issue by neetgupta7** [Microsoft/BotBuilder#3286]
Are there any guidelines/suggestions on how to scale the bot service considering a .net development.

**Comment by EricDahlvang** [comment]
A bot is just a web service, so the scaling constraints are the same as for any web server stack.

Unless you're using the Bot Service, then the bot is actually an Azure Function: https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale
