### ISSUE TITLE
DirectConversation use case

### ISSUE THREAD

**Issue by ahmettaha** [Microsoft/BotBuilder#329]
Hello,

What is the use case of DirectConversation in EchoBot examples? When I try it I just seem to receive the same message twice?

**Comment by chrimc62** [comment]
Good question.  It is commented out in the sample.  @msft-shahins can you respond?

**Comment by willportnoy** [comment]
It's an example of the AlwaysSendDirect_BotToUser IBotToUser implementation, which uses IConnectorClient to send all messages from the bot to user, without any attempt to keep one last message to return inline to the connector at the completion of the http post message.

**Comment by ahmettaha** [comment]
so the use case is to send multiple replies to a single message received?

**Comment by willportnoy** [comment]
It may be that there is some inadvertent duplication of messages, but generally the IBotToUser implementations exist to help send multiple messages, with varying polices on how that gets done (i.e. always direct through IConnectorClient, or sending the last one inline, or you could imagine an implementation combining all messages into a single message.

**Comment by ahmettaha** [comment]
can it also be used to initiate conversations with a proactive bot. because when i had tried it, i had gotten exceptions about conversationid not existing. is there a need to have a valid conversation id?

**Comment by willportnoy** [comment]
These aren't involved in proactive bots, except when sending messages from the bot to the user.

I'm not sure how to initiate a conversation from the bot - in particular, how to select a conversation id.  @tomlm how do you initiate a conversation from a bot?

**Comment by msft-shahins** [comment]
Here is the [documentation](http://docs.botframework.com/connector/new-conversations/#navtitle) to proactively start a conversation with a user. 

You need, `message.From` and `message.To`, to initiate the conversation. `message.ConversationId` indicates if it is a reply to an already existing conversation or a brand new conversation with the user.
