### ISSUE TITLE
[Question] best practice for load testing?

### ISSUE THREAD

**Issue by zachgoz** [Microsoft/BotBuilder#3291]
## System Information
* SDK Language:  Node.js
* SDK Version: 3.9.0
* Development Environment: AWS 

## Bot Info 
* Bot name: diagnostic-chatbot
* Bot handle: diagnostic-chatbot
* App ID: f5cf319a-4d5c-4797-a7bd-443286bef1f1
* Connected channels: Direct Line

## Issue Description
Trying to figure out how to properly load test my bot. I followed this article: https://blog.botframework.com/2017/06/19/Load-Testing-A-Bot/ and was able to post to https://login.microsoftonline.com/botframework.com/oauth2/v2.0/token and get an access token but I cant seem to post to my messaging endpoint using postman, I just receive a 500 error back with an empty body.  When I use my bot with directline it works fine.

## Code Example
Sending a POST to https://my-message-endpoint with the body:
{
  "type": "message",
  "id": "3d5dddf8-da68-49a4-9182-be316b24e887 (RANDOM GUID)",
  "channelId" : "test", 
  "conversation": { "id": "1" },
  "from": { "id": "user1" },
  "recipient": { "id": "diagnostic-chatbot" },
  "serviceUrl": "https://my-message-endpoint",
}

## Questions
Should I be able to do this with postman or jmeter? What is the recommended approach for load testing the bot?
Is the serviceUrl my messaging endpoint?

**Comment by megancooper** [comment]
How is your bot currently hosted? Are you simply running a local instance using Visual Studio debugging or is this hosted on a service like MSFT Azure? Your endpoint is the SSL url that you enter in when you are registering your bot with the bot framework. For Example: **https://mybotname.azurewebsites.com/api/messages**
Your endpoint MUST include /api/messages!

In terms of load testing you should be able to use post man (at least I currently can) but again a lot varies based on how/where your bot is being hosted while you're testing.

Also--as per the example you gave above--what happens when you send a POST request to:

https://my-message-endpoint/api/messages

**Comment by zachgoz** [comment]
The bot is hosted in AWS Lambda exposed with API Gateway. The API Gateway messaging endpoint is registered in dev.botframework.com and works fine when I use the bot with directline running in a browser with the bot connector but when I try to post to the messaging endpoint using postman and the access token from https://login.microsoftonline.com/botframework.com/oauth2/v2.0/token I just receive a 500 response with an empty body.

**Comment by nwhitmont** [comment]
To get the access token directly with a post request
the post url is: https://login.microsoftonline.com/common/oauth2/v2.0/token
and the scope is: https://graph.microsoft.com/.default

**Comment by nwhitmont** [comment]
relates to https://github.com/Microsoft/BotBuilder/issues/3232

**Comment by zachgoz** [comment]
Yes I was able to get the auth token and pass it in the Authentication header to my messaging endpoint but instead of getting a response back I get a 500 response.

**Comment by nwhitmont** [comment]
@zachgoz When I hit your endpoint in web browser, it showed 502 "internal server error" response.
<img width="776" alt="screen shot 2017-08-10 at 4 58 34 pm" src="https://user-images.githubusercontent.com/3075047/29197183-628d8ada-7dee-11e7-8e1a-e68e366c7653.png">

Looks like there is a problem with your bot code or deployment.

**Comment by nwhitmont** [comment]
@zachgoz reopen if you are still having issues.

**Comment by vivekaditya** [comment]
@nwhitmont Looks like @zachgoz had a similar issue. I too get a ERROR: ChatConnector: receive - invalid signing key or OpenId metadata document and _500 Internal server error_. 
@megancooper You mentioned using postman to do the load testing for your bot. It seems that this method is not working right now. Can you please confirm that you followed the same steps as in the [post](https://blog.botframework.com/2017/06/19/load-testing-a-bot/)?

**Comment by vivekaditya** [comment]
@JasonSowers  It's in node. Please find more details on this [SO question](https://stackoverflow.com/questions/47605699/load-testing-bot-leads-to-error-chatconnector-receive-invalid-signing-key-or).
