### ISSUE TITLE
[Question] The actions type of "OpenUrl" don't work in the Skype?

### ISSUE THREAD

**Issue by CybNat** [Microsoft/BotBuilder#3292]
## System Information
* SDK Language: .NET 
* SDK Version: 3.9.0
* Development Environment: Visual Studio 2017

## Bot Info 
* Bot name: Dssl Preview
* Bot handle: 
* App ID: 91199550-6aea-4840-b63d-16ad8228ab25
* Connected channels: Skype, Telegramm

## Issue Description
I develop bot for skype and telegram. I need use HeroCard, but actions of type "OpenUrl" don't work at skype.... Please help me fix this bug!

**Comment by CybNat** [comment]
I may attach the my code or something else if you need.

**Comment by nwhitmont** [comment]
@CybNat Can you post your bot code which reproduces the issue? Make sure to include your Hero Card code.

**Comment by nwhitmont** [comment]
@CybNat When I tested your bot on Skype, the OpenUrl action was working normally on the Hero Card, you just need to set the target URL to your custom URL. (Looks like all the cards I tested opened the URL: `https://www.microsoft.com/en-us/`)

**Comment by CybNat** [comment]
I found the reason. When url start with "http", not "https" the Skype don't allow open that links...

**Comment by CybNat** [comment]
@nwhitmont That my code with the HeroCard :

`        private async Task prepareAndShowOffers(IDialogContext context, OfferCategoryModel offerCategoryModel)
        {
            var exceptOffers = offerCategoryModel.Offers
                .Except(DialogsLayersHelper.OffersStack)
                .ToList();

            if (!exceptOffers.Any())
            {
                sendChoiseOffersDialog(context, offerCategoryModel);
                return;
            }

            var offersToShow = exceptOffers
                .Take(exceptOffers.Count > 3
                    ? 3
                    : exceptOffers.Count
                ).ToList();

            DialogsLayersHelper.OffersStack.AddRange(offersToShow);

            var reply = context.MakeMessage();
            var cards = getHeroCard(offersToShow);
            reply.Attachments = cards.ToList();

            await context.PostAsync(reply);

            sendChoiseOffersDialog(context, offerCategoryModel);
        }

        private IEnumerable<Attachment> getHeroCard(IEnumerable<OfferModel> offers)
        {
            return offers.Select(i => new HeroCard
            {
                Title = i.Model,
                Subtitle = $"{i.Price} руб",
                Text = i.Description,
                Images = new List<CardImage>
                {
                    new CardImage(i.Picture)
                },
                Buttons = new List<CardAction>
                {
                    new CardAction
                    {
                        Title = "Заказать",
                        Type = ActionTypes.OpenUrl,
                        Value = i.Url.Replace("http","https")
                    }
                }
            }.ToAttachment());
        }


`

**Comment by nwhitmont** [comment]
@CybNat Yes, `https` is required. Glad to hear you got it working. 👍
