### ISSUE TITLE
[Feature Request] Add Salesforce channel integration

### ISSUE THREAD

**Issue by nwhitmont** [Microsoft/BotBuilder#3294]
This issue is to track interest in [Salesforce](https://www.salesforce.com/) channel integration for Bot Framework. 

Thumbs up this comment to vote.

**Comment by xjose97x** [comment]
Having more channels is always better.

However I believe Twitter channel should be a higher priority than others such as Salesforce, Discord, etc.
Twitter has way more users.

**Comment by microsoftly** [comment]
@nwhitmont can we get an idea on what the level of interest/eta on this is? 

@xjose97x , while Twitter has significantly more users, many enterprise customers (e.g. $$$) use salesforce. It would be prudent for Microsoft to go after users that will help monetarily support the botbuilder initiative to help it get more resources and build better solutions.

**Comment by JasonSowers** [comment]
No update at this time

**Comment by raheemdaya** [comment]
@xjose97x Completely agree that twitter has more users.  However, if a user is opening a case through Salesforce, they are probably more serious about requiring assistance.  I tend to think people get on twitter to whine, they use SF to get help.

**Comment by benbrown** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
