### ISSUE TITLE
[Question How to use typing indicator in Web Chat?

### ISSUE THREAD

**Issue by satishsridharanpn** [Microsoft/BotBuilder#3295]

**Comment by satishsridharanpn** [comment]
var connector = new ConnectorClient(new Uri(activity.ServiceUrl));
                        Activity isTypingReply = activity.CreateReply("Bot is typing....");
                        isTypingReply.Type = ActivityTypes.Typing;
                        await connector.Conversations.ReplyToActivityAsync(isTypingReply);

Please help me to resolve this..

**Comment by JasonSowers** [comment]
Please fill out the form in your original post

**Comment by nwhitmont** [comment]
@satishsridharanpn Are you using the websockets enabled version of web chat? Typing indicator only works if you have websockets enabled.
