### ISSUE TITLE
Disable Input Field

### ISSUE THREAD

**Issue by anks333** [Microsoft/BotBuilder#3296]
Is there is any way to disable the textbox, if bot has responded with some cards or suggested action

I'm using Nodejs Boatbuilder SDK

**Comment by ankitbko** [comment]
Do you mean text box of channel? Which channel are you using?

**Comment by anks333** [comment]
I'm using Web Chat and i want to disable input field when bot has responded with some cards or button

**Comment by xjose97x** [comment]
That'd be an interesting feature to have. As far as I know that's not an available feature. I think Facebook Messenger hides the input when you use PromptOptions Choose, but Skype and other channels don't.

However you can code that logic in the webchat: https://github.com/Microsoft/BotFramework-WebChat
You'll have to edit the file shell.tsx (that's the textbox), and in the render function disable it with your logic.

**Comment by EricDahlvang** [comment]
If you are only interested in doing this within the WebChat channel, you could use the backchannel to send a custom message to WebChat that disables the control by adding `style="pointer-events:none;"` to the div with class= **wc-console**, and `disabled="disabled"` to the **wc-shellinput** text input.  You would also need to later send a backchannel event to clear the style and disabled when necessary.

**Comment by LaxmiprasadKumar** [comment]
can any one sent the code to disabled the input field before loading the first message or card from the bot

**Comment by LaxmiprasadKumar** [comment]
I am using webchat channel

**Comment by LaxmiprasadKumar** [comment]
node and reactjs

**Comment by geea-develop** [comment]
This is the way i did it

in ShellContainer (Shell.tsx)
add prop connectionStatus: ConnectionStatus

then at the bottom on connect add
connectionStatus: state.connection.connectionStatus,

and merge the props in the next part
connectionStatus: stateProps.connectionStatus,

finally add something like this to the text input
disabled={this.props.connectionStatus !== ConnectionStatus.Online}
