### ISSUE TITLE
[Skype] "ACL check failed" error 2017-08-10

### ISSUE THREAD

**Issue by YanXuHappygela** [Microsoft/BotBuilder#3297]
## System Information
* SDK Language: Node.js
* Development Environment: Auzure Bot Service

## Issue Description
I have created a bot that is successfully enabled at Cortana channel, with the speak function, text and herocard. When I tried to publish it in Skype, there are warnings saying:

There was a problem synchronizing your bot to Skype.
Acl check failed

I can send message over Skype but receive no reply at all. Does it have anything to do with the speak? A bot that is succesfully deployed at Cortana cannot be directly deployed at Skype?

**Comment by nwhitmont** [comment]
@YanXuHappygela Can you provide your bot information?
1. Bot name
2. Bot handle
3. App ID as registered in https://dev.botframework.com

**Comment by YanXuHappygela** [comment]
@nwhitmont  Here is my bot info:
Bot name: Monet
Bot handle: Monet
App ID: 8c356fc6-26ab-46d7-a67f-482e6f9bd8de

**Comment by nwhitmont** [comment]
Hi @YanXuHappygela - When I tested your bot on Skype just now, I was able to chat with the bot without any errors.

When do you see this problem specifically? Is it happening when you chat with the bot on Skype? Or for one of your users?

**Comment by YanXuHappygela** [comment]
Hi, @nwhitmont , this is happening with my skype. On the webpage, it shows "The bot was added to your contacts!". But in Skype, it shows "This person isn't in your Contact list". Is this possible reason? Thank you.

**Comment by YanXuHappygela** [comment]
I'm able to add the bot to my contact list and it is working now. Thank you for your help @nwhitmont
