### ISSUE TITLE
[.NET SDK] System.IdentityModel.Tokens.Jwt<5.0.0 Dependency conflict with Twilio (requires >=5.1.2)

### ISSUE THREAD

**Issue by muebele** [Microsoft/BotBuilder#3298]
Microsoft.Bot.Builder package requires System.IdentityModel.Tokens.Jwt <5.0.0. Twilio requires >=5.1.2. 

With this conflict, Bot Builder can not be used in the same project as Twilio (or any other package that requires System.IdentityModel.Tokens.Jwt > 5.0.0). Our project is already using Twilio, and we're trying to add Bot Builder as well, but this is causing an issue.

**Comment by EricDahlvang** [comment]
@msft-shahins  any thoughts?

**Comment by wbreza** [comment]
+1

**Comment by DL-LiveTiles** [comment]
We have the same issue, we use a later version of System.IdentityModel.Tokens.Jwt on referenced project and cannot update due to the version constraint.

**Comment by Yalpe** [comment]
We also have the same issue. Please fix!

**Comment by mballou11** [comment]
same issue here

**Comment by d1mnewz** [comment]
same issue, +1

**Comment by KaTXi** [comment]
Same here, would love to see this updated

**Comment by CasperJ** [comment]
FYI We had the same issue regarding Twilio and have forked their repo into a version that does not depend on IdentityModel at all. Downside: You cannot use Chat/TaskRouter-features in Twilio as they rely on JWT, but TextMessages, Calls etc works fine...

https://github.com/WorklifeBarometer/twilio-csharp

**Comment by DL-LiveTiles** [comment]
@fanidamj It has not.

**Comment by branchbark** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Unable to resolve dependencies. 'System.IdentityModel.Tokens.Jwt 5.1.4' is not compatible with 'Microsoft.Bot.Builder 3.11.0 constraint: System.IdentityModel.Tokens.Jwt (>= 4.0.4.403061554 && < 5.0.0)', 'Microsoft.Bot.Connector 3.11.1 constraint: System.IdentityModel.Tokens.Jwt (>= 4.0.4.403061554 && < 5.0.0)'.			0

**Comment by osolo** [comment]
@msft-shahins / @tomlm when do you expect to release a new package with this fix?

**Comment by vishwacsena** [comment]
Latest bot builder https://www.nuget.org/packages/Microsoft.Bot.Builder/3.15.2.2 requires System.IdentityModel.Tokens.Jwt (>= 5.1.4) which should address this issue.
