### ISSUE TITLE
[Question] Video card not working in Cortana channel?

### ISSUE THREAD

**Issue by YanXuHappygela** [Microsoft/BotBuilder#3299]
## System Information
* SDK Language: Node.js
* Development Environment: Auzure Bot Service

## Issue Description
I have added a video card in my message in botframework and set autoplay to be true. I'm able to play the video in Simulator and the test window in bot development. However the video cannot show up in Cortana. Why is this and is there a different way to embed a video in Cortana channel?

## Code Example
        var card = new builder.VideoCard(session)
        .title('Happy birthday')
        .autostart(true)
        .media([
            { url: 'https://youtu.be/rR9i-Mjjsws' }
        ])
        var msg = new builder.Message(session)
        .addAttachment({contentType: 'video/mp4', contentUrl: 'https://youtu.be/rR9i-Mjjsws'})
        .inputHint(builder.InputHint.acceptingInput);
        session.send(msg).endDialog();

**Comment by nwhitmont** [comment]
@YanXuHappygela Cortana currently supports the following Bot Framework cards.

From: https://docs.microsoft.com/en-us/cortana/design-guides/card-design-best-practices#bot-framework-card-designs

1. Hero Card
2. Thumbnail Card
3. Receipt Card
4. Sign-In Card

Video Card is not supported on Cortana channel at this time. You can use a Hero Card to provide a link to the video URL using the card action `openUrl` type.
