### ISSUE TITLE
unable to save and retrieve UserData

### ISSUE THREAD

**Issue by Praggie** [Microsoft/BotBuilder#330]
Hi,  

I am trying connector client to save and retrieve user data but it always throws error that : "You have to specificy userId or conversationId".

 I have tried both sync and async methods. And Both Getter and Setter apis return same error. I tried this with emulator user. Is it not possible to save data for emulator?

 ```
var connector = new ConnectorClient();
                    BotData botData = new BotData();
                    botData.Data = "queryPending";
                    connector.Bots.SetUserData(botId, userId, botData);
```

Returned status code is BadRequest.
Can you please suggest what I might be missing or this a bug?
 
Regards

**Comment by jameslew** [comment]
I think you're right, though I need to verify with @tomlm when he's available.  In my bot I use the code this way and know it works, but it generates an error in the emulator.

var connector = new ConnectorClient();
BotData botData = new BotData();
botData.SetProperty("v1", addedUserData);
connector.Bots.SetUserData(botId, userId, botData);

**Comment by tomlm** [comment]
if you are getting bad request it is because your botId or userId is incorrect
