### ISSUE TITLE
[Direct Line] "endOfConversation" Activity type not working correctly in MS Teams 

### ISSUE THREAD

**Issue by bilby91** [Microsoft/BotBuilder#3300]
## System Information
* SDK Language: Node.js
* SDK Version: 3.8.4
* Development Environment: localhost, AWS

## Bot Info 
* Bot name: Suttna Dev Bilby
* Bot handle: suttna-dev-bilby
* App ID: 5b410643-435b-4784-ba03-3b1c3a9f1918
* Connected channels: Slack, MS Teams

## Issue Description
When ending a conversation in Teams, Directline responds with an error. 

```javascript
{ error: { code: 'BadArgument', message: 'Unknown activity type' } }
```
I verified in the REST api docs and endConversation seems to be a valid activity type.

This is the request data:

```javascript
{ 
method: 'POST',
  url: 'https://smba.trafficmanager.net/amer-client-ss.msg/v3/conversations/19%3A7d548e74f4e240efa494bc305f339621%40thread.skype%3Bmessageid%3D1502406730769/activities/1502406779742',
  body:
   { type: 'endOfConversation',
     code: 'completedSuccessfully',
     localTimestamp: '2017-08-10T23:13:01.597Z',
     from:
      { id: '28:5b410643-435b-4784-ba03-3b1c3a9f1918',
        name: 'Suttna Dev Bilby' },
     recipient:
      { id: '29:1DN_aZMPkDZPvvh6fsbv1j2dX3GE8FTK2TJx5kvaZLBsWAm7ad0T6x9XVSrJh85rdbP9vh3BbirS9ofUwbmB81w',
        name: 'Martin Fernandez' } },
  json: true }
```

## Steps to Reproduce the Issue
1. Send a message to the bot
2. End the conversation

## Expected Behavior
The bot ends the conversation without errors

**Comment by nwhitmont** [comment]
relates to: https://docs.microsoft.com/en-us/bot-framework/rest-api/bot-framework-rest-connector-activities#endofconversation

**Comment by nwhitmont** [comment]
@bilby91 According to your request object's URL parameter, you are not POSTing to the Direct Line API endpoint, which is: `https://directline.botframework.com/v3/directline/conversations/{conversationId}/activities'

**Comment by bilby91** [comment]
That is happening inside botbuilder ChatConnector. I wrongly mentioned direct line

**Comment by RichMoeMSFT** [comment]
That particular type is not supported in Teams, sorry.

**Comment by nwhitmont** [comment]
Thanks for the update @RichMoeMSFT 👍

**Comment by bilby91** [comment]
I guess that of this is not supported that should be contemplated in the SDK right ? At the moment the endConversation method in the session invokes the call.

**Comment by bilby91** [comment]
Any updates con my last comment ?

**Comment by bilby91** [comment]
Is this something that is going to get fixed in teams or the SDK ? Users need to call endConversation on the session to clear the conversation data.
