### ISSUE TITLE
[LUIS]  Composite entities are not returned by published model, but children are?

### ISSUE THREAD

**Issue by MathBunny** [Microsoft/BotBuilder#3302]
## System Information
* SDK Language: Node.js
* SDK Version:3
* Development Environment: localhost

## Issue Description
I have several LUIS instances that use composite entities. Occasionally, LUIS will not return any composite entities but it returns their children. Oddly enough, it works while trained, but even if you publish the trained model, it still doesn't return the composite entity itself. 

## Code Example
_None_, this is only interfacing LUIS.

## Steps to Reproduce the Issue
1. Build LUIS instance that uses composite entries.
2. Train LUIS, such that composite entities work on the web debugger.
3. Publish LUIS, try the composite entity detection.

## Expected Behavior
Entities should be tagged appropriately, like in training.

## Actual Results
The composite entities are not tagged.

**Comment by MathBunny** [comment]
Note that this sometimes works, and sometimes doesn't. For instance, now it works on the published version but not on the trained version.

**Comment by stevengum97** [comment]
Can you provide some screen captures of the behavior that you're seeing? Additionally, can you provide the JSON model for your LUIS app?

**Comment by MathBunny** [comment]
I can't add the JSON for the Luis model, but here is a screenshot: http://i.imgur.com/DB8nCDL.png

Clearly, it uses the same model for the trained one and the published one (see the times posted).

**Comment by stevengum97** [comment]
@MathBunny Your composite entity is supposed to encompass your Security and FixedIncomeSecurityType entities? Just to check via a different route, have you tried plugging in your utterances directly against your LUIS endpoints?

**Comment by MathBunny** [comment]
No, the `Filter Item` (composite) is supposed to encompass the `Argument`. However, the published model just labels the `Argument`, but does not show that it's part of the composite. In the trained it does it correctly.

**Comment by stevengum97** [comment]
The curly braces around `[$Argument ]` mean that the Argument entity is wrapped inside of a composite entity. If you press Ctrl+E, you'll be able to shift between the labels. The default label will show the entities except for the composite entities. The first Ctrl+E will show the composite entities only, and the next Ctrl+E will show the tokens (actual words).

If you want to select the view manually, you can access a dropdown menu over the right side of that training window (over the scores). Below is a screencap of what the menu looks like:

![labels view](https://user-images.githubusercontent.com/14935595/29339567-a4aecff2-81cf-11e7-8a2b-dc18eb207905.PNG)

**Comment by MathBunny** [comment]
The view doesn't matter. I showed you in the screenshot that one shows the entity prediction as being `argument` and `filter`, and another is just `argument`. The published model doesn't show me the `composition` type. 

This isn't a matter of view, I get that, but if you look at the tooltip it clearly outlines the difference.

**Comment by MathBunny** [comment]
My problem is that while the trained model and the published model are the exact same, they're returning different results.

**Comment by stevengum97** [comment]
My mistake @MathBunny, @DeniseMak do you have any idea why this might be happening?

**Comment by stevengum97** [comment]
@MathBunny if you train your model with more utterances eventually the red underline (and tooltip) should go away as the two models (your trained and published model) become more aligned. 

As to _why_ the models aren't providing the same predictions when you train and publish the app within the span of a few seconds I can't say. I'll send an inquiry to the LUIS team and see if they've received any previous reports about this issue.

**Comment by MathBunny** [comment]
Okay. Shouldn't the trained model and the published model be the exact same? That's the confusing part. Since if someone doesn't change it since it was trained it should return the same results.

**Comment by stevengum97** [comment]
Closing this issue and I'll update this thread when I get more info. If you've trained and trained the models but are still running into this problem, feel free to reopen this issue.

**Comment by stevengum97** [comment]
@MathBunny can you type into the labeling component (the area when you're inside an intent and entering new utterances) one of the queries that show a difference in prediction in the training screen and provide a screen capture of what the results are?

**Comment by MathBunny** [comment]
It works fine in the training screen, it only fails in the testing screen (and when requests are made to it).

**Comment by stevengum97** [comment]
Before you used the testing tool, was this utterance already labeled and part of your model?

**Comment by MathBunny** [comment]
Yes

**Comment by MathBunny** [comment]
More info on this: This happens even if it isn't labelled. Sometimes I have the exact phrase as an utterance in the intent, sometimes not, it doesn't change anything. :/

**Comment by stevengum97** [comment]
:/ I'll pass this onto the LUIS dev team and see if we have any answers or need additional information. Sorry about the hassle.

**Comment by MathBunny** [comment]
Sorry, I don't have access to the project anymore (it was an internship project). I'll try my best to answer questions though. Thanks!

**Comment by stevengum97** [comment]
@MathBunny do you by chance know if your former advisors/bosses might be interested in receiving additional assistance? What could be done is to add someone from the LUIS team as a collaborator to the LUIS app and provide them with the utterances throwing discrepancies. It would allow us to start investigate their app.
