### ISSUE TITLE
[FormFlow] Always prompts 1st field when not provided, regardless of its "active" status?

### ISSUE THREAD

**Issue by dagerikhl** [Microsoft/BotBuilder#3303]
## System Information

* SDK Language: .NET.
* SDK Version: 3.9.0.
* Development Environment: localhost and App Service.

## Bot Info 

* Bot name: -
* Bot handle: -
* App ID: -
* Connected channels: MS Teams.

## Issue Description

I'm using a FormFlow to gather information from the user. But I've ran across an issue where prompting for a confirmation causes the first Field of the form to be prompted, regardless of it being an active delegate or not (and always completely disregarding the answer given).

This happens when providing the form with the Field that is _not_ the first one built. So in this case, providing only a `Role`, and not a `Person`, causes the problem.

It is worth mentioning that both of these fields are provided as LUIS entities.

## Code Example

Invocation of the Form:

```C#
var form = new FormDialog<Form>(new Form(), Form.BuildForm, FormOptions.PromptInStart, result.Entities);
```

Excerpt from the Form that is exhibiting the problem, somewhat trimmed (and `true`/`false` forced for active delegates to illustrate problem):

```C#
[Serializable]
public class Form
{
    [Describe("Name")]
    [Prompt("What's the {&} of the person?")]
    public string Person;

    [Describe("Role")]
    [Prompt("What {&} does the person have?")]
    public string Role;

    ...

    public static IForm<Form> BuildForm()
    {
        IFormBuilder<Form> formBuilder = new FormBuilder<T>();

        return formBuilder
            .Field(
                nameof(Person),
                HasActivePerson)
            .Field(
                nameof(Role),
                HasActiveRole)
            .Confirm("Is this correct?")
            .Build();
    }

    private static bool HasActivePerson(Form form)
    {
        return false;
    }

    private static bool HasActiveRole(Form form)
    {
        return true;
    }

    ...
}
```

The issue also persists if I use a confirmation each for both the Fields, like this:

```C#
.Confirm("Is {Person} correct?", dependencies: new string[] { "Person" })
.Confirm("Is {Role} correct?", dependencies: new string[] { "Role" })
```

But if I remove the prompt for `Role`, the problem disappears.

_However_, it reappears if I change the order of the Fields so that `Role` comes before `Person`. Again, removing the prompt for the "not first Field", this time `Person`, resolves the issue.

## Steps to Reproduce the Issue

1. Have a Form with 2 fields.
2. In `BuildForm`: build Field 1, build Field 2, prompt for confirmation.
3. Send a message the routes to the Form containing a LUIS entity for Field 2, but _not_ Field 1.

## Expected Behavior

First, the confirmation is sent. Then, on a `yes` response from the user, the information resulting from a completed form is sent.

## Actual Results

A prompt for Field 1 is sent, requiring input from the user. The bot disregards any answer that is given to the prompt (i.e., it _does not_ store the new value given as the value for Field 1).

An example of a conversation:
`B = Bot, U = User, architect = an entity that maps to Field 2`

```
U: Give me information about architect
B: What is the name of the person?
U: Solenya
B: Is this correct?
U: yes
B: <information about architect>
```

Thanks in advance for any help!

**Comment by JasonSowers** [comment]
this line will not compile for me, are you sure its what you are using?
`IFormBuilder<Form> formBuilder = new FormBuilder<T>();`

**Comment by dagerikhl** [comment]
@JasonSowers Ah, no! I copy-pasted in a bit of a hurry for simplicity, sorry. It's supposed to be `IFormBuilder<Form> formBuilder = new FormBuilder<Form>();`.

**Comment by fanidamj** [comment]
Hoping that issue has been resolved, closing it. Feel free to reopen if any questions.
