### ISSUE TITLE
[Question] First Message to Bot Gives Error?

### ISSUE THREAD

**Issue by neetgupta7** [Microsoft/BotBuilder#3304]
## System Information
* SDK Language:  .NET 
* SDK Version: 3.9.0
* Development Environment: App Service

## Bot Info 
* Bot name: OFBOT
* Bot handle: OFBOT
* App ID: 3ec62770-09bb-4ad3-b175-3e92e961f624
* Connected channels: WebChat

## Issue Description
Whenever i send my first message to bot i see "couldnt send (retry)" in web chat. And it works fine if i resend. This started happening since today. My App ID is 3ec62770-09bb-4ad3-b175-3e92e961f624.

I am calling LUIS dialog to find the intent. 

## Steps to Reproduce the Issue
1. Write "Hi" to the bot you see error
2. Retry and it works fine

**Comment by megancooper** [comment]
I notice this issue as well, but it only happens with WebChat. Try testing it out with the Emulator and see if you see the same error. I think this is just a bug? My bot functions fine in every other channel, but WebChat seems to always give me that first Error. 

Here is the error:
![img](https://user-images.githubusercontent.com/8683055/29218039-25562452-7e79-11e7-8074-e0c7b651bf9a.PNG)

**Comment by neetgupta7** [comment]
On emulator it worked fine. Haven't tried it on Skype or any other channel.

**Comment by JasonSowers** [comment]
@neetgupta7 @megancooper how long has this been happening for? 
  
Looking at OFBOT I see the behavior you are describing.  I also see errors in the webchat channel like below:
![capture](https://user-images.githubusercontent.com/6301037/29221109-62fdb7ae-7e72-11e7-8833-f32e9847e19b.PNG)

**Comment by neetgupta7** [comment]
@JasonSowers I have been since past 8-9 hours

**Comment by megancooper** [comment]
@JasonSowers I noticed it when I first began testing my bot, maybe mid-june

**Comment by JasonSowers** [comment]
@neetgupta7 I tried to take a look at this again today and was unable to test your bot.
![capture](https://user-images.githubusercontent.com/6301037/29426122-7d88dd34-833a-11e7-97e8-c14b7471fd04.PNG)

**Comment by tiloc** [comment]
I experience this when I am using a low hosting tier (free) and allow Azure to put my app to sleep when not used for a while (setting "App Settings" / "Always On" = Off). This will typically timeout the first request while the App Service wakes up again.

**Comment by JasonSowers** [comment]
please continue the conversation if needed.  We can reopen this if you have not resolved it.
