### ISSUE TITLE
[Question] How can I get all the chat history of bot and the user?

### ISSUE THREAD

**Issue by MuraliMohanEdiga** [Microsoft/BotBuilder#3307]
## System Information
* SDK Language: Node.js

* Development Environment: localhost

## Issue Description
Can you please some one help me in getting logs/history of chat (user input and bot reply) by using Node js or if any other way is there to achive this requirement like any tool.

Thanks,
Murali

**Comment by nwhitmont** [comment]
@MuraliMohanEdiga You can use the Skype Web Control (web chat) which supports stored conversation history.

You can find the Skype Web Control options in the Skype channel config page on the Bot Portal at https://dev.botframework.com/
![skype web control - contoso dive finder](https://user-images.githubusercontent.com/3075047/29226761-1a5c2f1a-7e88-11e7-8696-792dac709410.png)

**Comment by MuraliMohanEdiga** [comment]
Hi @nwhitmont ,

Thanks for your reply . But i need logs in server side like azure.
ex:If we deploy bot app in azure, we need logs/history in server side.
I got logs  in  local with below code . Same way required logs in azure if possible.

bot.use({
botbuilder: function (session, next) {
console.log("user input-------"+session.message.text);
next();
},
send: function (event, next) {
console.log("bot output-------"+event.text);
next(); 
}
})




Thanks,
Murali
