### ISSUE TITLE
[Question] Disable action in a dialog

### ISSUE THREAD

**Issue by fcioffi** [Microsoft/BotBuilder#3308]
Hi guys,

i'm using botframework 3.9 and I have a question.

I would like to set a triggerAction on my bot but I would like to disable this action when I'm in a subdialog.

How can i do that, is possible with Node.js SDK?

Thanks,
Francesco

**Comment by nwhitmont** [comment]
Trigger actions are currently global, so you would need to find a different way to implement your desired behavior.
