### ISSUE TITLE
[Question] Can't Connect to Azure Hosted Bot?

### ISSUE THREAD

**Issue by michelpf** [Microsoft/BotBuilder#3309]
## System Information
* SDK Language: .NET
* SDK Version: 3.9
* Development Environment: Azure API

## Bot Info 
* Bot name: BeyondBotEY
* Bot handle: beyondbotey  
* App ID: 75069f6a-5d72-40ab-97fd-2f60d71fde64
* Connected channels: Skype, Web

## Issue Description
When turn on the auth (without auth everything is all right), the bot seems to connect to remote host (I'm using Bot Emulator), but when I try to send some message, I got [500] Internal Server Error.
Using the Fiddler, I got more details, it seems to be something related to OAuth, {
  "message": "An error has occurred.",
  "exceptionMessage": "Unauthorized",
  "exceptionType": "Microsoft.Bot.Connector.MicrosoftAppCredentials+OAuthException",
  "stackTrace": "   at Microsoft.Bot.Connector.MicrosoftAppCredentials.<RefreshTokenAsync

Reading a lot (most time [here](https://docs.microsoft.com/en-us/bot-framework/troubleshoot-authentication-problems)), I even checked the OAuth authorization using curl -k -X POST https://login.microsoftonline.com/botframework.com/oauth2/v2.0/token -d "grant_type=client_credentials&client_id=APP_ID&client_secret=APP_PASSWORD&scope=https%3A%2F%2Fapi.botframework.com%2F.default"
The answer was fine.

I tried to remove LUIS integration, just to make sure there is no issues related with that. But no success.

The auth method is by Web.Config. Tried to remove BotId, but not working...

  <appSettings>
    
    
    <add key="MicrosoftAppId" value="XXX" />
    <add key="MicrosoftAppPassword" value="​XXX" />
  </appSettings>

Change the vms from Free, Shared and S1. My latests tests were with S1 instances.
I remove the bot and created on, same as application. No success.

![capture2](https://user-images.githubusercontent.com/8541053/29222391-aaa746b2-7e98-11e7-92f4-37201040443f.PNG)
![capture3](https://user-images.githubusercontent.com/8541053/29222392-aaad942c-7e98-11e7-91ee-26d5a97f01d1.PNG)
![capture4](https://user-images.githubusercontent.com/8541053/29222393-aab786b2-7e98-11e7-9827-b6796b35bf50.PNG)

What I'm missing? :(

**Comment by JasonSowers** [comment]
There seems to be a problem with your bot code.  Do you have your code in a repo so we can look?  In the dev portal I see a bunch of errors in the webchat channel.  
![capture2](https://user-images.githubusercontent.com/6301037/29223496-9cfd2116-7e7b-11e7-99a5-677b50fc0935.PNG)

**Comment by michelpf** [comment]
The errors are related to connection as related, for example "There was an error sending this message to your bot: HTTP status code InternalServerError", same in bot emutator.

![image](https://user-images.githubusercontent.com/8541053/29223811-47833e78-7e9e-11e7-86a5-04ee773c9073.png)

**Comment by michelpf** [comment]
I don't have the code in a repo. :(

**Comment by michelpf** [comment]
In Microsoft App Dev, there are other configurations that I didn't set up. In some tutorials they don't exist.
For example, I should set a platform or grant any rule to Graph (I don't think so).

![image](https://user-images.githubusercontent.com/8541053/29223909-955d19ac-7e9e-11e7-8c1f-1d6f58cb82a9.png)

**Comment by michelpf** [comment]
Running local, with auth (AppiId and AppPassword), same error:

Microsoft.Bot.Connector.MicrosoftAppCredentials+OAuthException: Unauthorized ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.Bot.Connector.MicrosoftAppCredentials.<RefreshTokenAsync>d__25.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.Bot.Connector.MicrosoftAppCredentials.<RefreshTokenAsync>d__25.MoveNext()

![image](https://user-images.githubusercontent.com/8541053/29224431-aea7c90a-7ea0-11e7-909b-b0f09d26cb1e.png)

**Comment by JasonSowers** [comment]
500 error generally means there is a problem with your bot code.

**Comment by EricDahlvang** [comment]
Hi @michelpf 

Is your bot deployed to the messaging endpoint configured in dev.botframework.com?  https://YourSiteName.azurewebsites.net/api/messages

There are a few ways to debug locally.  The easiest is to remove the MicrosoftAppId and MicrosoftAppPassword from the web.config, and do not supply them in the emulator.  This method doesn't use BotAuthentication security, and doesn't require a bot registration on dev.botframework.com

**Comment by michelpf** [comment]
I don't know what happend, but I solved in the worst way for developers... Deleted bot account, app account, create new ones, create a new bot app, copy from old app and paste same code in the new app and Voilá, started to work. :(

**Comment by EricDahlvang** [comment]
@michelpf  I'm glad you've got it working now.  Thanks for letting us know.  And, I agree: your resolution method is not something any developer wants to do, ever.  Let's just pretend this didn't happen (since we don't know what actually happened anyway).
