### ISSUE TITLE
[Skype] ACL check failed 2017-08-11

### ISSUE THREAD

**Issue by PrimeObjects** [Microsoft/BotBuilder#3310]
## System Information
* SDK Language: .NET
* SDK Version: 3.8
* Development Environment: App Service

## Bot Info 
* Bot name: DuoHub
* Bot handle: https://bot.douhub.com/api/messages
* App ID: 26112111-26a1-4606-8e4d-7b23207b169a
* Connected channels: 

## Issue Description
After I rebuild the bot with new version and in a new project on VS2017, the bot stopped working on skype, seeing Acl check failed on bot framework site. It works fine in other channels.

**Comment by nwhitmont** [comment]
When the bot sends message to the user, Skype backend checks that the user has added the bot to user contact list. This is called ACL (access control list) check.

If the return code is 403 it means that the user removed the bot from contacts.

It may also mean that the check failed for some other reason, and I would expect return code to be 500 or 503.

**Comment by nwhitmont** [comment]
@PrimeObjects When I tested your bot on Skype channel just now, the bot was responding normally. 

Sometimes the bot doesn't get added to the Skype user's contacts correctly, and this causes the Access Control List check to fail. 

Try removing the bot from contacts, and re-adding via the "join" URL.

**Comment by PrimeObjects** [comment]
Hi nwhitmont,

Thank you for the information and help. You are right, it seems something wrong on my Skype account. I tried another account on iPad and it worked.

Please close this issue. 

Thanks again
Gary
