### ISSUE TITLE
[Skype for Business] Markdown-style URL links no longer working

### ISSUE THREAD

**Issue by sujaywork** [Microsoft/BotBuilder#3313]
## System Information
* SDK Language: Node.js
* SDK Version: 3.9.0
* Development Environment: App Service

The links markdown now shows the entire link, did something change recently? It was working fine until a few weeks back. For example if we have a link such as this, it is supposed to show bing as a hyperlink and when clicked, takes you to the actual URL, but now it shows the entire URL, so if we have a long URL, it looks really ugly.

Example markdown style link: ```[bing](http://bing.com)```

Ref: https://blogs.msdn.microsoft.com/jamiedalton/2016/08/22/bot-framework-markdown-support-by-channel/

**Comment by nwhitmont** [comment]
@sujaywork The referenced MSDN article was published before Skype for Business was onboarded to Bot Framework and makes no mention of Skype for Business. 

Markdown is not supported in Skype for Business. 

You can read more about the feature support here:
https://msdn.microsoft.com/en-us/skype/skype-for-business-bot-framework/docs/overview#feature-support

## Feature Support
>Messages : Your bot can send plain text, HTML, and emoticons to a user or group. Users can send rich text, HTML, and emoticons to your bot.

**Comment by sujaywork** [comment]
That's very strange, it was working before. The documentation link you mentioned says html is supported, does it mean we can use html link <a href syntax?

Also any idea when Cards will be supported in SfB, we need this feature for the enterprise rollout of the bot in our company.

**Comment by sujaywork** [comment]
The html <a href syntax now works, thanks! Now if only we get cards support in SfB, that will make it so much more useful for the enterprises.
