### ISSUE TITLE
[Question] Cannot choose"C+E Security IS" in a button in FormFlow?

### ISSUE THREAD

**Issue by radennis** [Microsoft/BotBuilder#3315]
## System Information
* SDK Language: .Net
* SDK Version: 3.8.1.0
* Development Environment: webchat

## Bot Info 
* Bot name: Gaia
* Bot handle: kustobot
* App ID: 
* Connected channels: 

## Issue Description
We compose buttons out of text in our but, in FormFlow. When the button contains "C+E Security IS" it's impossible to click it. 
We get "“C+E Security IS” is not an existing account name option."
Then we specify "2" as the button it the first one, and it chooses a different button.
Then we go back and specify 1 and it finally works. But we cannot click the "C+E Security IS". 

Can you please fix?

![image](https://user-images.githubusercontent.com/28060851/29251174-82695614-8059-11e7-9946-fb32f38972e0.png)
![image](https://user-images.githubusercontent.com/28060851/29251181-95b38686-8059-11e7-9cdc-a009277df75b.png)

**Comment by radennis** [comment]
Using quotes also doesn't work
![image](https://user-images.githubusercontent.com/28060851/29251236-26f810e4-805a-11e7-94ed-56f40e2499f9.png)

**Comment by radennis** [comment]
This is not a question, it's an issue. 
Also any update on this?

**Comment by JasonSowers** [comment]
Can you please share your code, we do not have enough info to help you without it.

**Comment by EricDahlvang** [comment]
@radennis Please upgrade your bot to v 3.9 and let us know if your issue is resolved.  There was a problem with FormFlow fields defined with a Describe attribute, but no Terms: fixed by this PR https://github.com/Microsoft/BotBuilder/pull/2990 (and a few subsequent PRs)

Also, please show how you are defining this form in code, so we are able to reproduce the problem.

Thank you.

**Comment by radennis** [comment]
Thanks, I'll upgrade my bot and see if it helps. 

Here's a code snippet of how I'm doing it:
```
        private static Task<bool> DefineExistingPcCode(KustoOnBoardForm state, Field<KustoOnBoardForm> field)
        {
            foreach (var account in GetExistingPcCodes(state))
            {
                field
                    .AddDescription(account, account)
                    .AddTerms(account, account);
            }

            var newAccountChoice = "I have a different Pc Code";
            field
                .AddDescription(c_newPcCodeRequest, newAccountChoice)
                .AddTerms(c_newPcCodeRequest, newAccountChoice);

            field.SetType(null);
            field.SetActive(IsExistingAccountChosen);
            return Task.FromResult(true);
        }
```

**Comment by radennis** [comment]
Hi, just wanted to update back that I tried upgrading to 3.9.0.0 and still get the same error. 
![image](https://user-images.githubusercontent.com/28060851/29433405-ad58c6a6-83a7-11e7-9a40-a3a0d182db04.png)

Please let us know what can be done.

**Comment by JasonSowers** [comment]
Thanks for the update, we are actively looking into this.

**Comment by JasonSowers** [comment]
@radennis we are unable to repro the same behavior with the code given.  Are you able to share your whole project?  If not can you at least share the code for your form and what is the `IsExistingAccountChosen` code?

**Comment by radennis** [comment]
I've sent you the project code separately as we rather not publish it on the web.
Here's the snippet you asked for:
```
        public string GetAccountName()
        {
            return IsExistingAccountChosen(this)
                ? ExistingAccountName
                : NewAccountName;
        }
        public static bool IsExistingAccountChosen(KustoOnBoardForm state)
        {
            var newAccountCondition = string.IsNullOrEmpty(state.ExistingAccountName) ||
                state.ExistingAccountName.Equals(c_newAccountRequest, StringComparison.InvariantCulture);
            return !newAccountCondition;
        }
```

**Comment by JasonSowers** [comment]
Thank you, I am waiting on approval to view the source.

**Comment by radennis** [comment]
Hi any update on this?

**Comment by JasonSowers** [comment]
We were still not able to reproduce, I am awaiting approval in RAM to view the source to try to repro.

**Comment by JasonSowers** [comment]
Looking into this now

**Comment by JasonSowers** [comment]
@radennis I was able to reproduce, It seems the '+' char is the issue here.  I'm still trying to pin down the exact cause, but if as a workaround, for now, can you try using the work "and" rather than '+' and see if that fixes the problem for you?

**Comment by radennis** [comment]
Thanks @JasonSowers for looking into this. Unfortunatelly I cannot change the content of the button since it is generated by getting the account name. Therefore when the account name if "C + E" I need to show the exact same string to the user...

**Comment by JasonSowers** [comment]
I am still looking into this as a bug, I will update you when I know more.

**Comment by radennis** [comment]
Thanks for the update

**Comment by chrimc62** [comment]
You need to regex escape your string.  The terms we match on our regex and the + is interpreted as a regex.
