### ISSUE TITLE
[Direct Line] Slow responses and websocket disconnections?

### ISSUE THREAD

**Issue by rmimura** [Microsoft/BotBuilder#3317]
## System Information
* SDK Language: Node.js
* SDK Version: 3.9
* Development Environment: other

## Bot Info 
* Bot name: any
* Bot handle: any
* App ID: 
* Connected channels: directline

## Issue Description
directline instabilities - experiencing problems on directline connections, timeout errors and unexpected websocket closings.

## Code Example
basic call flows using directline

## Steps to Reproduce the Issue
1. call bot using directline

## Expected Behavior
Normal conversation, using directline or facebook

## Actual Results
Facebook is ok. Directline presents slow response and websocket disconnection errors

**Comment by seca23** [comment]
We are experiencing the exact same issue. Apart from the slow response, we are continually getting "Unable to deserialize the response" errors in basic form flow prompts.

**Comment by nwhitmont** [comment]
@seca23 thanks for reporting. please open a new issue to track your specific use-case. thx

**Comment by seca23** [comment]
Hi Nils
Thanks, will do.

**Comment by stevengum97** [comment]
We're currently looking into this problem and are working on fixing it. In the meantime users may experience some latency issues.

We'll update this issue as more news comes through.

**Comment by stevengum97** [comment]
It's been resolved.  If you continue to experience issues, please open a new issue.

**Comment by rmimura** [comment]
I'm still getting 503 :
Error: Request to 'https://directline.botframework.com/v3/conversations/LxLtVa4GOWbFbO925JxlXG/activities/LxLtVa4GOWbFbO925JxlXG%7C0000008' failed: [503] Service Unavailable

**Comment by stevengum97** [comment]
@rmimura Are you still getting 503s?

**Comment by rmimura** [comment]
@stevengum97 I've been monitoring for a couple of hours and now seems to be ok. Thank you.
