### ISSUE TITLE
[Direct Line] Unable to deserialize the response

### ISSUE THREAD

**Issue by seca23** [Microsoft/BotBuilder#3318]
## System Information
* SDK Language: .NET (C#)
* SDK Version: 3.9.0
* Development Environment: localhost, Auzure Bot Service

## Issue Description
We are experiencing a major performance decrease in our bot through the directline, and we are continuously getting a "Unable to deserialize the response" while answering basic prompt questions in a form flow.

**Comment by stevengum97** [comment]
We're currently looking into this problem and are working on fixing it. In the meantime users may experience some latency issues.

We'll update this issue as more news comes through.

**Comment by stevengum97** [comment]
It's been resolved.  If you continue to experience issues, please open a new issue.

**Comment by seca23** [comment]
Thank you, Steven

It is much appreciated. I just did a test, and all seems to be working as normal.

**Comment by singhsurya** [comment]
Hello @stevengum97 
Could you please let us know the root cause and the fix you have done for this problem. We face this issue in out Bot application and want to understand what was the issue.

Thanks
