### ISSUE TITLE
[Feature Request] Constant of maximum allowed attachments in a channel

### ISSUE THREAD

**Issue by DSakura1987** [Microsoft/BotBuilder#3319]
## System Information
* SDK Language: .NET
* SDK Version: 3.9
* Development Environment: self-hosted

## Issue Description
Hi MS guys, when I am adding Hero cards to an activity, I received error `Card contains invalid attachment count`. I google it a bit and found #3212 said Teams have a limit of 7 attachments. The limit is reasonable, but can you kindly provide the constant in the framework or its extension? 

Just to avoid magic numbers.

## Expected Behavior
A constant in bot framework or its extension, of maximum allowed attachments in a channel

**Comment by nwhitmont** [comment]
@DSakura1987 I don't understand your request. Can you please provide an example?

**Comment by DSakura1987** [comment]
@nwhitmont 
Example: my bot scans user input and return TFS work item(s) as Hero card(s). The Hero card has a button to send a reply of the item's child items. Sometimes the parent item has more than 7 children, so when my bot send the child items as cards in MS Teams, I got a warning `Card contains invalid attachment count`, and the message is not sent.

I can understand there is a limit, but without a definition in bot framework or its extension, people can feel confused.

I would like to have a constant in bot framework, or in its extension, of the maximum number of attachments allowed.

**Comment by nwhitmont** [comment]
@DSakura1987 You can solve this easily by configuring your app logic to only send 7 cards per carousel message.  No modifications to the SDK are required. 

I will ping the MS Teams group and have them update the documentation to be more specific.

**Comment by nwhitmont** [comment]
https://msdn.microsoft.com/en-us/microsoft-teams/botsmessages#carousel-layout

![max 7 cards per carousel teams](https://user-images.githubusercontent.com/3075047/29338071-95cb0070-81c8-11e7-8959-f09e486ba7a3.png)

**Comment by DSakura1987** [comment]
👍 
Just to make sure you received my thanks :)

**Comment by armstrong-charles** [comment]
How to include more than 10 cards in the reply if i am using v4 SDK. I am inside the waterfall dialog flow, do i need to put 10th card as a more or something to refill the reply with remaining items. I have more than 10 items to provide, how to do that?
