### ISSUE TITLE
PromptDialog within a loop

### ISSUE THREAD

**Issue by arunnanjundaswamy** [Microsoft/BotBuilder#332]
Hi,

How can I add a PromptDialog inside a for loop so that the prompt dialog should be invoked on each iteration.

**Comment by Stevenic** [comment]
Which language? Node or C#?

**Comment by arunnanjundaswamy** [comment]
It is in C#.

**Comment by chrimc62** [comment]
You should be able to just use Chain, look at the documentation: http://docs.botframework.com/sdkreference/csharp/dialogs.html#Fluent 
You have one dialog step which uses PromptDialog and you can loop until you reach the condition that you want to stop on.  All dialog state is maintained with the message so a for loop would have no way of knowing what the count is if your bot crashed and was answered by a different machine.

**Comment by arunnanjundaswamy** [comment]
Just to take an example:

I have a promotdialog inside another dialog which I need to loop. Something like the below example.

If possible can you please post an example.

E.g.
            for (int i = 0; i < 2; i++)
            {
                context.Call(new FormExampleDialog(), FormDialogComplete);
            }

**Comment by gabrielrufus** [comment]
Hi,
Please help me in PromptDialog loop in node js
