### ISSUE TITLE
[MS Teams] HeroCard buttons not working with numbers?

### ISSUE THREAD

**Issue by ashice** [Microsoft/BotBuilder#3322]
## System Information
* SDK Language: .NET
* SDK Version: 3.8.4.0
* Development Environment: App Service

## Bot Info 
* Bot name: ICMTestBot
* Bot handle: ICMTestBot
* App ID: f9cf18d8-9e89-459b-86c2-5ce1840f449a
* Connected channels: Skype,Teams, SMS

## Issue Description
I have a bot deployed on both Skype and Teams but behaves differently. I have a list of cards for which I am adding id's on buttons (eg View) so that I can recognize which button was pressed. On Skype this works fine, when I click on View button on an item, it shows message sent as View but id is sent to api. In Teams, this doesn't work. Only View message is received on the API without any id. To test this when instead of clicking on button, if view {{id}} is sent as text, the bot works as expected. What could be done to resolve this issue?

## Code Example
```cs
 private async Task ActOnSearchResults(IDialogContext context, IAwaitable<IMessageActivity> input)
        {
            var activity = await input;
            var ans = activity.Text.Split(' ');
            var choice = ans[0];
            var selection = Regex.Match(activity.Text, @"\d+").Value;

            await context.PostAsync($"Your activity is {activity.Text}");
            await context.PostAsync($"Your choice is {choice} {selection}");

            switch (choice.ToLowerInvariant())
            {
                 case "view":
                    await ViewSelectedItem(context, selection);
                    break;
           }
}

//Card creation logic

 cards = hits.Select(h => new HeroCard
                    {
                        Title = h.Title,
                        Subtitle = h.Subtitle,
                        Text = h.Description,
                        Buttons = new[]
                        {
                            new CardAction {Value = "Add " + h.Key, Title = "Add Note", Type = ActionTypes.PostBack},
                            new CardAction {Value = "View " + h.Key, Title = "View", Type = ActionTypes.PostBack},
                            new CardAction {Value = "Approve " + h.Key, Title = "Approve", Type = ActionTypes.PostBack},
                            new CardAction {Value = "Reject " + h.Key, Title = "Reject", Type = ActionTypes.PostBack}
                        }
                    });
```

## Steps to Reproduce the Issue
1. Deploy above code to Skype and Teams
2. Skype works
3. Teams doesn't

## Expected Behavior
I expected entire command to be sent to API- eg View 1

## Actual Results
While "View 1" was sent by Skype, only "View" was sent by Teams.

![skype works](https://user-images.githubusercontent.com/29292928/29296120-1d553824-810d-11e7-8228-bafd7f2e9d04.png)

![teams error](https://user-images.githubusercontent.com/29292928/29296127-2543767c-810d-11e7-9b81-75b0f1f622fe.png)

Note: This happens on clicking the buttons. If text is sent directly, the bot works as expected.

Update: 
1. Tried using comma (,) as a separator instead of space, did not work; same issue as above
2. Tried using no separator at all but still activity.Text does not contain any id at all.

![skype works](https://user-images.githubusercontent.com/29292928/29296837-aac5622a-8111-11e7-9a4e-be0e09751267.png)

![team issue](https://user-images.githubusercontent.com/29292928/29296848-bc18f5e6-8111-11e7-82a2-0ec99fbd895e.png)

**Comment by nwhitmont** [comment]
@RichMoeMSFT

**Comment by RichMoeMSFT** [comment]
@ashice The issue is that `postBack` is not supported in Teams. We have `imBack` which sends the message in the chat stream. We have `activityType.Invoke` which sends JSON silently. But we don't have one in between, which is what `postBack` provides.

Please note that we are working on functionality that acts like `postBack` but for now you'd need to leverage one of the other options.

https://msdn.microsoft.com/en-us/microsoft-teams/botsmessages#card-actions-in-teams

**Comment by ashice** [comment]
@RichMoeMSFT What version of Bot Builder supports Invoke ActionType? I upgraded to the latest version v3.9.0 but I don't see it.

**Comment by RichMoeMSFT** [comment]
Invoke is an Activity.Type, not a message ActionType.

**Comment by ashice** [comment]
@RichMoeMSFT As mentioned by Lars on (StackOverflow)[https://stackoverflow.com/questions/41016016/microsoft-bot-framework-hide-text-message-from-users?rq=1], I would have expected the postBack(), if not supported in a channel to default to ImBack(). To quote "Not all channels currently support postBack() so those channels will simply fall back to using imBack()." 

Anyways using ImBack fixed the issue for now even though showing id is not ideal.

**Comment by EricDahlvang** [comment]
@ashice  I'm glad you've found a workaround, until Teams fully supports postBack.  Please open a new issue if you require more assistance.
