### ISSUE TITLE
[Feature Request] Call bot via Skype Number

### ISSUE THREAD

**Issue by sposaro** [Microsoft/BotBuilder#3323]
I would like a way to assign a phone number to the Skype bot so that I can call it with a telephone.

Thanks

**Comment by alexsorokoletov** [comment]
+1 https://github.com/Microsoft/BotBuilder/issues/2055

**Comment by deniercounter** [comment]
+1

**Comment by alyssaong1** [comment]
+1

**Comment by IoTGirl** [comment]
Hi @sposaro ,

As you have not closed this issue based on @alexsorokoletov post at [#2055](https://github.com/Microsoft/BotBuilder/issues/2055) Can you please explain how your feature request differs from the previous request?

Sincere thanks,
IoTGirl

**Comment by IoTGirl** [comment]
Hi @nwhitmont  Can you please review for closure as duplicate?

**Comment by JasonSowers** [comment]
Closing as duplicate

**Comment by sposaro** [comment]
My request is not different from https://github.com/Microsoft/BotBuilder/issues/2055

I just want a way to talk to the bot on the phone and not though Skype

**Comment by IoTGirl** [comment]
It is better to add to the prior issue that is linked to the feature request rather than create a new one as tracking multiple issue request for the same item adds overhead. Many thanks!
