### ISSUE TITLE
[Question] Skype - long message truncated?

### ISSUE THREAD

**Issue by ashice** [Microsoft/BotBuilder#3325]
## System Information
* SDK Language: .NET
* SDK Version: 3.8.4.0
* Development Environment: App Service

## Bot Info 
* Bot name: ICMTestBot
* Bot handle: ICMTestBot
* App ID: f9cf18d8-9e89-459b-86c2-5ce1840f449a
* Connected channels: Skype,Teams, SMS

## Issue Description
Skype Message text is getting truncated.

## Steps to Reproduce the Issue
1. Enter long text in Skype message

## Actual Results
Message is truncated and ellipsis (...) is shown.
![skype Truncate Message](https://user-images.githubusercontent.com/29292928/29298734-bfc9c910-811e-11e7-8bcf-13b148f20093.png)

**Comment by nwhitmont** [comment]
@ashice Use `<br/>` with the closing slash.

**Comment by ashice** [comment]
@nwhitmont Got it.  Longer messages are still truncated though.

**Comment by JasonSowers** [comment]
duplicate of https://stackoverflow.com/questions/45684118/skype-bot-truncating-display
