### ISSUE TITLE
[Question] ACL check failed 2017-08-15 - Bot works for one Skype user but is offline for another?

### ISSUE THREAD

**Issue by Daij-Djan** [Microsoft/BotBuilder#3326]
## System Information
* SDK Language: Node.js
* SDK Version: "botbuilder": "^3.7.0" & "botbuilder-azure": "3.0.2"
* Auzure Bot Service

## Bot Info 
* Bot name: XXX (hidden due to NDA issues) 
* Bot handle: XXX (hidden due to NDA issues) 
* App ID: ee8b3cf1-da60-4e4a-814e-dea4df62ecf1
* Connected channels: Skype

## Issue Description
I have a Skype bot hosted on azure that works for one skype user but is offline for another (same time, room, Skype version)

## Expected result
The bot is online for all users

**Comment by nwhitmont** [comment]
@Daij-Djan Thanks for reporting. 

What happens when you remove the bot from the Skype user's contacts and re-add it using the "join" URL?

**Comment by nwhitmont** [comment]
@Daij-Djan When the bot sends message to the user, Skype backend checks that the user has added the bot to user contact list. This is called ACL (access control list) check. If the return code is 403 it means that the user removed the bot from contacts. It may also mean that the check failed for some other reason, and I would expect return code to be 500 or 503.

**Comment by Daij-Djan** [comment]
@nwhitmont we tried readding it this morning: same result. for user A (me) the bot is there in skype for user B (my colleague) it is offline and doesnt respond -- in the azure portal where we both have access to we can both chat with the bot just fine, so it must be related to skype.

Im afraid I dont get where I should see the status codes you mention OR is it just a general information of how it works. I use the botframework sdk with nodejs your info seems to be more low level.... what should I do next? can you see the issue maybe?

**Comment by Daij-Djan** [comment]
@nwhitmont I use the botframework bundled with azure. Since the azure support cant get any git or npm to work, I cant and wont update the package ;)

**Comment by nwhitmont** [comment]
Hallo @Daij-Djan - Leider, kann ich das Problem nicht reproduzieren. Als ich den Bot zu meinen Skype-Kontakten hinzufügte, konnte ich mit dem Bot ohne Fehler chatten.

Ich werde das Problem zu Skype-Plattform-Team für die Untersuchung eskalieren.

**Comment by nwhitmont** [comment]
Update: The "ACL check failed" error is a known issue affecting new and old Skype bots. 

The Skype Platform team is actively working to fix the issue.

**Comment by Daij-Djan** [comment]
any news? can you update me / tell someone from the team to update me

**Comment by nwhitmont** [comment]
no updates so far, Skype team is actively working on it.

**Comment by brandon1780** [comment]
You are exactly right, run Brandon bot

**Comment by nwhitmont** [comment]
This issue is being tracked by the Skype team

**Comment by sueess** [comment]
I still have this problem. That should be reopened.
