### ISSUE TITLE
Send POST Requests to bot from outside Web Service

### ISSUE THREAD

**Issue by megancooper** [Microsoft/BotBuilder#3329]
## System Information
* SDK Language: .NET
* SDK Version: 3.8.5
* Development Environment: localhost, Azure
* Connected channels:  MS Teams

## Issue Description
I want to create a push notification service for my bot. I created an ApiController in my bot code that responds to and endpoint like this https://mybot.azurewebsites.net/push

This endpoint works, I've tested it with localhost & postman and I can get the expected response back, the only problem is when I deployed the code and started using the actual endpoint and not a localhost enpoint I got an Authorization exception from Microsoft:

```cs
{
    "message": "An error has occurred.",
    "exceptionMessage": "Authorization for Microsoft App ID --MY BOT ID-- failed with status code Unauthorized and reason phrase 'Unauthorized'",
    "exceptionType": "System.UnauthorizedAccessException",
    "stackTrace": "   ...long stack trace...
}
```

How do I account for this in my code? Or is there a way to just manually open then endpoint for traffic on Azure where my bot is hosted? Or is this a weird rule where my endpoint needs to be /api/push? 

## Here is the Code I'm using to send the request (C# Azure Web Job)

All works well when testing locally.

```cs
// testing HTTP POST to My Bot
HttpClient client = new HttpClient();
HttpRequestMessage reqMsg = new HttpRequestMessage( HttpMethod.Post , "https://mybot.azurewebsites.net/push");
reqMsg.Content = new StringContent("MSG CONTENT");
var response = await client.SendAsync(reqMsg);
var responseString = response.Content.ReadAsStringAsync();
Console.WriteLine(response.Content.ToString());
```

## Here is the Controller code I wrote
```cs
        [HttpPost]
        [Route("push")]
        public async Task<HttpResponseMessage> PushNotificationCallback()
        {
            try
            {
                var response = new HttpResponseMessage(HttpStatusCode.OK);

                // Send Push Notifications to Users
                await sendPushNotifications();

                // Send Response to Web server
                response.Content = new StringContent($"Sending Push Notifications to users...");
                return response;
            }
            catch (Exception ex)
            {
                return Request.CreateErrorResponse(HttpStatusCode.BadRequest, ex);
            }
        }
```

**Comment by megancooper** [comment]
I figured out the issue! Needed to add this line before I send the proactive message to other users:
i.e. before the connector client is used

```
private static async Task sendNotification() {
    IMessageActivity message = Activity.CreateMessageActivity();
    // ... Pull Other Conversation Data etc...
    MicrosoftAppCredentials.TrustServiceUrl(--SERVICE URL--);
    // Send Message to User
    await connector.Conversations.SendToConversationAsync((Activity)message);
}
```

**Comment by JasonSowers** [comment]
@megancooper mind sharing your solution so others might benefit?

**Comment by megancooper** [comment]
I figured out the issue. I needed to add this line: 
`MicrosoftAppCredentials.TrustServiceUrl(--SERVICE URL--);`
before I send the proactive message to other users like so:
i.e. before the connector client is used

```
private static async Task sendNotification() {
    IMessageActivity message = Activity.CreateMessageActivity();
    // ... Pull Other Conversation Data etc...
    MicrosoftAppCredentials.TrustServiceUrl(--SERVICE URL--);
    // Send Message to User
    await connector.Conversations.SendToConversationAsync((Activity)message);
}
```

**Comment by JasonSowers** [comment]
@megancooper thanks, glad you figured it out

**Comment by MithunPradeeps** [comment]
Thanks for the info 👍

**Comment by swapabhi** [comment]
@megancooper where do I need to add below code and what would be the "--SERVICE URL--" ?

private static async Task sendNotification() {
    IMessageActivity message = Activity.CreateMessageActivity();
    // ... Pull Other Conversation Data etc...
    MicrosoftAppCredentials.TrustServiceUrl(--SERVICE URL--);
    // Send Message to User
    await connector.Conversations.SendToConversationAsync((Activity)message);
}

**Comment by megancooper** [comment]
@swapabhi The code snippet you posted is a function I made for my push notification service that sends a message to a user. You don't need to copy the function itself, just make sure you call
`MicrosoftAppCredentials.TrustServiceUrl(...)` 
before sending a message to a user.

Check out these resources that have some more detail on how to call `MicrosoftAppCredentials.TrustServiceUrl(...)` and creating connector clients:

- [Microsoft | Send and receive activities](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-connector?view=azure-bot-service-3.0)
- [StackOverflow | Send msg from bot to user botframework](https://stackoverflow.com/questions/42749982/initiate-a-message-from-bot-to-user-on-botframework)

In addition [here's another stackoverflow post](https://stackoverflow.com/questions/42939418/proactive-bot-messaging-createdirectconversation-unauthorized-exception?noredirect=1&lq=1) that says you can solve this problem by sending credentials to the connector like so:

```
var credentials = new MicrosoftAppCredentials("YoursMicrosoftAppId", "YoursMicrosoftAppPassword");
var connector = new ConnectorClient(serviceUrl, credentials);
```
