### ISSUE TITLE
[FB Messenger] Showing error (#105) param message quick_replies has too many elements?

### ISSUE THREAD

**Issue by mukeshzt** [Microsoft/BotBuilder#3331]
## System Information
* SDK Language: Node.js
* SDK Version: 
* Development Environment: localhost and App Service

## Bot Info 
* Bot name:  RITS AppBuilder Bot
* Bot handle: RITSAdvisoryBot
* App ID: 
* Connected channels:  Skype & FB Messanger

## Issue Description

Setup the Bot app on skype channel from past 6 months and working fine. Now I would like to use for Facebook Messanger. 
Done with the [ Enable Messenger ](https://docs.microsoft.com/en-us/bot-framework/channel-connect-facebook) configuration successfully. 
Same development environment working on Skype but not working on FB Messanger.

## Steps to Reproduce the Issue
1. Run node then startup message working. 
2. Once we select any menu and wait for another menu to list and it's not working. 

## Expected Behavior

It should list out the next menu for selection. 

## Actual Results

It was not showing any response to the FB channel and showing error on a command prompt.
![fberror](https://user-images.githubusercontent.com/23474222/29348008-13d3d28a-826e-11e7-8c77-0c323507d3b0.png)

```
restify listening to http://[::]:3978
Error: Request to 'https://facebook.botframework.com/v3/conversations/1587119291359091-898099460343348/activities/mid.%24cAANqJEG9qKhkGp-zPFd6VpqidmT_' failed: [400] Bad Request
    at Request._callback (/home/marcus/advbot/node_modules/botbuilder/lib/bots/ChatConnector.js:512:46)
    at Request.self.callback (/home/marcus/advbot/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/marcus/advbot/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/marcus/advbot/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Comment by kiramishima** [comment]
Have same problem :(

**Comment by carlokhanati** [comment]
Hello,

Did you manage to solve the issue?
I found a workaround, the problem in with the list style elements it only accepts 11 choices, and when the error happens, it stocks in that error and the bot stays in that state no matter what message is sent because the dialog was not closed.
So what I did is redirect the code to my pc using ngrok and with the debugger poped out the array of choices before continuing the request, then my bot resumed normally.
code in /home/marcus/advbot/node_modules/botbuilder/lib/bots/ChatConnector.js: 514 (request(options, function (err, response, body) )

Hope more choices are allowed later.

**Comment by fanidamj** [comment]
Closing the issue assuming it as resolved. Please reopen a new issue if it still persists.

**Comment by aspiringguru** [comment]
I cam across the same error message when using more than 3 options. But not while using Microsoft/BotBuilder. 

also: refer this. max 3 buttons per bubble for generic replies , up to 11 in quick replies.
https://stackoverflow.com/questions/37848437/any-way-around-facebook-bots-button-template-limit

Just dropping this trivia here in case it is useful to others.
