### ISSUE TITLE
[Eumulator] Electron Open SSL error

### ISSUE THREAD

**Issue by ranmax123** [Microsoft/BotBuilder#3332]
## System Information
* SDK Language: .NET
* SDK Version: 3.9
* Development Environment: localhost

## Bot Info 
* Bot name: 
* Bot handle: 
* App ID: bca9ffa2-8bd8-4b82-878f-7bb9a54d5834
* Connected channels: None yet

## Issue Description
I'm getting this error since last 2 weeks, can't debug bot locally...
`write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:c:\e\workspace\electron-win-x64\vendor\node\deps\openssl\openssl\ssl\s23_clnt.c:794:`
![image](https://user-images.githubusercontent.com/8466040/29353314-63e6e992-8287-11e7-9a2a-65f99deac419.png)

## Steps to Reproduce the Issue
1. Open Bot emulator (v 3.5.31)
2. Type the URL, app id and password
3. See the error

## Expected Behavior
I should see my bot working

## Actual Results
Error as pasted above.

**Comment by JasonSowers** [comment]
@eanders-MS any thoughts?

**Comment by eanders-MS** [comment]
Users report this from time to time, and we don't have a reliable solution yet. Things that have worked for others:
- Simplify the scenario by omitting appId and password (from both the bot config and the emulator's bot connection)
- If your bot endpoint begins with `https://`, change it to `http://`
- Conversely, if your bot endpoint begins with `http://`, change it to `https://` (bizarre, I know!)

**Comment by JasonSowers** [comment]
@ranmax123 let us know if that works for you or not.

**Comment by nwhitmont** [comment]
@ranmax123 Thanks for reporting. If you continue to experience problems, please open an issue on the Emulator repository here: https://github.com/Microsoft/BotFramework-Emulator/issues/new

**Comment by ranmax123** [comment]
@nwhitmont  am still getting error, tried every possible way. Can I use postman to test my bot?

Please share sample post requests.

**Comment by JasonSowers** [comment]
@ranmax123 as this issue pertains directly to a project in another repository, please post a new issue there.  [Here is a direct link](https://github.com/Microsoft/BotFramework-Emulator/issues/new)

**Comment by ranmax123** [comment]
solved this after running emulator in admin mode :D
