### ISSUE TITLE
[Question] How to localize bot dialog messages?

### ISSUE THREAD

**Issue by ranmax123** [Microsoft/BotBuilder#3334]
I'm not sure if we can have Bots using Microsoft Bot Framework in non-english language?

I'm assuming I need to convert non-english language input into English using any translation service and then take it forward?

Let me know.

**Comment by neetgupta7** [comment]
You can use cognitive services to identify user language and then translate it to english and pass it on to LUIS or for any other processing.
When your bot reply back you you can translate content to user's original language and reply back.

**Comment by stevengum97** [comment]
@ranmax123 which language and version of the SDK are you using? 

You can use a translation service, but localization support is also available. And might yield better/static results as opposed to constantly calling a translation API.

**Comment by nwhitmont** [comment]
@ranmax123 For more information about localizing your bot content, see: https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-localization

![localization example](https://docs.microsoft.com/en-us/bot-framework/media/locale-dir.png)

>Bot Builder includes a rich localization system for building bots that can communicate with the user in multiple languages. All of your bot's prompts can be localized using JSON files stored in your bot's directory structure. If you’re using a system like LUIS to perform natural language processing, you can configure your LuisRecognizer with a separate model for each language your bot supports and the SDK will automatically select the model that matches the user's preferred locale.

**Comment by rjgmail88** [comment]
@nwhitmont , is it possible to replace the values from index.json ? ex: In my bot my choice prompt says
CCSD2 room is available on March 10 should I go ahead and book ? where I can inject 2 params before passing text to prompt. 
{roomName} room is available on {dateTime} should I go ahead and book ?

**Comment by EricDahlvang** [comment]
@rjgmail88 Please open a new issue, and fill out the issue template, so we can assist you.  This issue is closed.
