### ISSUE TITLE
[Question] Detecting channel scope of a message in Bot's code?

### ISSUE THREAD

**Issue by megancooper** [Microsoft/BotBuilder#3336]
## System Information
* SDK Language: .NET
* SDK Version: 3.8.5
* Channel: MS Teams

I know you can get the name of the channel a message was sent through using the following:
```
public static async Task getChannelName(IDialogContext context, IMessageActivity message) {
    // get channel name:
    var channelName = message.ChannelId;
}
```
Is there a way to get the scope of the message? Whether it was sent in a private chat or in a team scope? (I am using MS Teams) I was wondering if this data was available.

**Comment by EricDahlvang** [comment]
Hi @megancooper 

Have you tried using the Connector.Conversations.GetConversationMembersAsync method?  Here is a .NET example:  https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/core-GetConversationMembers

**Comment by megancooper** [comment]
@EricDahlvang Thanks, exactly what I needed. I did the following in my messages controller before creating a new Dialog:
```
using (var scope = DialogModule.BeginLifetimeScope(Conversation.Container, activity))
{
    var client = scope.Resolve<IConnectorClient>();
    var activityMembers = await client.Conversations.GetConversationMembersAsync(activity.Conversation.Id);
    int numMembers = 0;
    activityMembers.ToList().ForEach(async (member) => numMembers = numMembers + 1);
    userData.SetProperty<int>("members", numMembers);
}
```
Since this was saved in the user's context, I can check the value in my Dialog. If it's above 1 I know its a team and not a private conversation with the bot. Example:
```
if (context.UserData.GetValue<int>("members") > 1) 
{
    await context.PostAsync($"You're in a team!");
}
else
{
    await context.PostAsync($"You're in a personal chat!");
}
```

**Comment by EricDahlvang** [comment]
@megancooper 

There is also the `activity.Conversation.IsGroup` property.
