### ISSUE TITLE
[Question] Hosting the Bot on Enterprise Cloud - Connector IP Whitelist?

### ISSUE THREAD

**Issue by maheshksingh** [Microsoft/BotBuilder#3339]
## System Information
* SDK Language:  .NET
* Development Environment: Bot hosted on Enterprise Cloud

## Bot Info 
* Connected channels: Skype, WebChat

## Issue Description
Hello Team,
We have an enterprise Cloud region where we trying to host the BOT Code with the business logic. We have the BOT registered at Microsoft Dev (dev.botframework.com) and need help for the same.

Now, our Enterprise Cloud server is not open completely for the Internet, and the Network team opens the firewall for requested IP addresses and Ports only,

Is that possible that Microsoft gives us the information about the IP addresses and Ports thru which the BOT communication happens so that we can request our network team here to open them, so that the communication can happen

We do have the Microsoft folks to talk to as well, just thought to put the question here, if anybody has done that, to check if thats possible.

Any help would be a great help for us to move ahead.

Thanks,
Mahesh

**Comment by JasonSowers** [comment]
I have seen other solve this by using something like [Fiddler](http://www.telerik.com/fiddler) to observe traffic.
