### ISSUE TITLE
Bot not responding to other users on Facebook

### ISSUE THREAD

**Issue by DavePilks** [Microsoft/BotBuilder#334]
If I chat to it using the Facebook profile of the user who created it (the Facebook app that is linked to the bot), it responds. But if I try another user, it does nothing.

What could be causing this?

**Comment by DavePilks** [comment]
Apparently the bots have to be reviewed by Facebook before external parties can interact with them. Can you confirm that this is the case?

**Comment by dandriscoll** [comment]
Yep, that's right.

https://developers.facebook.com/docs/messenger-platform/implementation

"When your app is in Development Mode, plugin and API functionality will only work for admins, developers and testers of the app. After your app is approved and public, it will work for the general public."
