### ISSUE TITLE
[Question] How to make Botbuilder wait for API call result?

### ISSUE THREAD

**Issue by SerendioSoftwares** [Microsoft/BotBuilder#3341]
## System Information
* SDK Language: Node.js

## Bot Info 

* Connected channels: Skype

## Issue Description
I am using woocommerce Node.js API( code below). The Botbuilder doesn't wait for the output and proceeds in an asyncronous fashion (console.log updates the result later onto the terminal)  to the next waterfall step. As a result the data variable is not available when I need it. How do I make it wait until the results have been fetched?

## Code Example
```js
lib.dialog('/', [
    function (session) {
    var data=null;
     WooCommerce.get('products', function(err, data, res) {
     console.log(res);  
     data=res;)};
     //Create carousel with product details but data variable empty
},
.....]);
```

**Comment by spawn-guy** [comment]
make the function `async` and then `await` for WooCommerce.get

**Comment by stevengum97** [comment]
You should generate the carousel and perform the rest of your required actions in the callback, not outside of it. Otherwise your code will just proceed as you mentioned above and not do what you want it to.

**Comment by stevengum97** [comment]
Example of what your code _might_ look like:
````js
lib.dialog('/', [
  function (session) {
    WooCommerce.get('products', function(err, data, res) {

      // Helper function to create your carousel, takes res as input.
      var cards = getCardsAttachments(res); 

      // create reply with Carousel AttachmentLayout
      var reply = new builder.Message(session)
          .attachmentLayout(builder.AttachmentLayout.carousel)
          .attachments(cards);

      session.send(reply);
    )};
},
...]);

function getCardsAttachments (productsObj) {
  // generate cards
}
````

The cards and carousel code I added comes from [this example](https://github.com/Microsoft/BotBuilder-Samples/blob/master/Node/cards-CarouselCards/app.js#L22).

Other points you should consider are the version of Node that you're using. If you're using 7.6.x or later you have `async await` available [natively](https://www.infoq.com/news/2017/02/node-76-async-await). If using an older version you may need to use a library like [`asyncawait`](https://www.npmjs.com/package/asyncawait).

**Comment by SerendioSoftwares** [comment]
I've tried the following, unfortunately none work:
1. Creating its own dialog. It simply passes control to the calling (parent) dialog stack to continue execution before WooCommerce API executes.

`lib.dialog('woo_category', 
    [
       function (session) {
          WooCommerce.getAsync('products', await function(err, data, res) 
        {

          // Helper function to create your carousel, takes res as input.
          var cards = getCardsAttachments(JSON.parse(res)); 

          // create reply with Carousel AttachmentLayout
          var reply = new builder.Message(session)
              .attachmentLayout(builder.AttachmentLayout.carousel)
              .attachments(cards);
            console.log('1111111')
          session.send(reply);
        });
},
]);`


2. Similar to the one above except it uses async on the botbuilder function too. Same result.

`lib.dialog('woo_category', 
    [
       async function (session) {
          await WooCommerce.getAsync('products', await function(err, data, res) 
        {

          // Helper function to create your carousel, takes res as input.
          var cards = getCardsAttachments(JSON.parse(res)); 

          // create reply with Carousel AttachmentLayout
          var reply = new builder.Message(session)
              .attachmentLayout(builder.AttachmentLayout.carousel)
              .attachments(cards);
            console.log('1111111')
          session.send(reply);
        });
},
]);`

3. What does work is to call the api, store the result and then access it from somewhere else. This is problematic because I want to use user input to query WooCommerce- which would need real time synchronous input. 

I use to build websites by using timeout function to wait for object creation before listening, is there a similar wait method for BotBuilder?

**Comment by stevengum97** [comment]
What are the error messages that you receive with your two code snippets?

And have you tried the following? 

```js
function (session) {
  WooCommerce.get('products', function(err, data, res) { 
```

**Comment by SerendioSoftwares** [comment]
Thank you for the replies.

They execute Async. The botbuilder function simply passes to the next dialog on the stack after invoking the WooCommerce Function.

I used that code snippet you've posted, and that did not work either.

**Comment by SerendioSoftwares** [comment]
The solution is to create 2 blocks as opposed to one. Use 'next' to transfer control from one function to the next waterfall dialog, or as shown in the ex below start a dialog and when control passes back, it moves to the next waterfall dialog. The crux is to call the function inside the get method:

```
function(session, args, next){
 shop.woo().get('products/categories',  function(err, data, res) {
            console.log("Fetched Categories");
            categories=JSON.parse(res);
            session.beginDialog('category', {categories:categories});         
        });     
        }
}
```
