### ISSUE TITLE
[FB Messenger] When sending proactive message - Error: Invalid channelId='facebook'

### ISSUE THREAD

**Issue by dundas** [Microsoft/BotBuilder#3344]
## System Information
* SDK Language: Node.js

## Bot Info 
* Bot name: Social Assistant
* Bot handle: SocialAssistant
* App ID: e5bd008f-6a12-4c6e-abb4-a66121ebb41d

* Connected channels: Facebook 

## Issue Description

Fatal error when I try to send proactive message with bot framework. 

Error: Invalid channelId='facebook'
    at /dev_env/instabot/v2/helloconvo-bot/app/node_modules/botbuilder/lib/bots/UniversalBot.js:216:31

## Code Example

var address = {
"id": "REMOVED"
, "channelId": "facebook"
, "user": {
"id": "REMOVED"
, "name": "REMOVED"
}
, "conversation": {
"isGroup": "false"
, "id": "REMOVED"
}
, "bot": {
"id": "REMOVED"
, "name": "REMOVED"
}
, "serviceUrl": "https://facebook.botframework.com"
}

var msg = new builder.Message().address(address);
msg.text('Hello, this is a notification');
msg.textLocale('en-US');
bot.send(msg);

## Steps to Reproduce the Issue
1. Run Script 

## Expected Behavior
proactive message sent. 

## Actual Results
proactive message not sent.

**Comment by JasonSowers** [comment]
please reopen if you are still experiencing issues
