### ISSUE TITLE
[Question] Send Ads with Microsoft Bot Framework?

### ISSUE THREAD

**Issue by GINGO2397** [Microsoft/BotBuilder#3345]
Hi, Can I include Ads with my Xamarin app that uses the bot framework with Admob ?  section 4.13. refers to sending ads as messages , however, Admob is not  a "Service Component". Also,  the ads will be in the app and not in the bot. Thanks in advance for the response.

**Comment by nwhitmont** [comment]
Yes, you control the content in your bot.

**Comment by GINGO2397** [comment]
Thanks for the quick response. One last question, can I use interstitial ads with my app that uses the bot frameworks.

**Comment by JasonSowers** [comment]
Closing this issue, please continue the conversation here if needed

**Comment by JasonSowers** [comment]
According to the terms here https://www.botframework.com/Content/Microsoft-Bot-Framework-Preview-Online-Services-Agreement.htm 

> When using the Service Components, you must comply with the terms of this Agreement, the terms of any third-party services, the documentation forming part of the Service Components (including any call volume limitations) and all applicable laws. You must also obey any policies, codes of conduct, and notices Microsoft provides including the Developer Code of Conduct and Review Guidelines. The Service Components may not be available in all countries. You, and any third party working on your behalf, may not:
  

> 13. Send advertising or spam (including unwanted or unsolicited bulk email, postings, contact requests, SMS (text messages), or instant messages);

I am not a lawyer or authorized to give legal advice on anyone's behalf so I will leave you to interpret this as you see fit.

**Comment by GINGO2397** [comment]
Thank for the response. In the terms is mentioned:
"This  Agreement applies to Microsoft Bot Framework and any developer services made  available..."  However if the ads appear through the app and not from the bot itself i am not sure ir the terms apply
