### ISSUE TITLE
[FB Messenger] Cannot share bot with other users?

### ISSUE THREAD

**Issue by hardikchoudhary** [Microsoft/BotBuilder#3346]
My bot replies to me only even the page is public and in app review setting on fb page its showinh publiv

What i am missing can you please help me i t his regardss

I get error on dev. Bot framework...you cant send messages to other person aprt from developers admin till app is in public state

But its showing me public :( in chat fuel or others we dont need to have public app

**Comment by JasonSowers** [comment]
Please fill out the information in the template so we can better assist you.

**Comment by hardikchoudhary** [comment]
I have created a bot using node js template....it works fine on both skype
and messenger

But when other user on fb message my bot...

My bot doesnt reply back

Even my bot is showing public and the page m.using js also publiv..


Please guide me

**Comment by megancooper** [comment]
@hardikchoudhary Do you see any errors listed for the FB Messenger channel on dev.botframework.com? Example shown below:
![err](https://user-images.githubusercontent.com/8683055/29429785-6ea4732e-8357-11e7-8b17-e96b4df43028.PNG)

**Comment by michaelhutchful** [comment]
Your bot had probably not been approved by FB, when it is still in development only the Dev can access it 

Sent from my Windows 10 phone

**Comment by stevengum97** [comment]
@hardikchoudhary Did the answers above help solve your problem?

**Comment by hardikchoudhary** [comment]
Yes it is solved there is ome.more permission that was missinh in
documentaion...


Pages_messaging we need to get it approve :)

Thanks alot for the helppp

**Comment by stevengum97** [comment]
Awesome! Since your problem was solved I'm going to close this issue.

**Comment by hardikchoudhary** [comment]
Yes sureee thankss
