### ISSUE TITLE
[Question] How to connect two user anonymously in a conversation? 

### ISSUE THREAD

**Issue by wethil** [Microsoft/BotBuilder#3348]
I could not found any information about Microsoft chatbot for connect two user in a conversation. NearGroup chatbot does it. I wonder if it is possible via using Microsoft chatbot  framework

**Comment by JasonSowers** [comment]
Can you please explain your use case further so we can try to assist you better?

**Comment by wethil** [comment]
For example, in NearGrop chatbot, you can chat with another chatbot user  via chatbot but, none of you can see each other's information. Basically chatbot take message from you and send other user and vice versa. We can think it as anonymous chat app.

**Comment by nwhitmont** [comment]
@wethil Are you using .NET or Node.js SDK for BotBuilder?

**Comment by wethil** [comment]
Node.js

**Comment by JasonSowers** [comment]
This is not a feature of bot framework.  This would be channel specific.  Bot framework does not control your profile on a channel like facebook.
  
Closing this issue, but feel free to continue the discussion if you would like
