### ISSUE TITLE
[Suggestion] Alternative name to "triggerAction"

### ISSUE THREAD

**Issue by samiraguiar** [Microsoft/BotBuilder#3352]
I'm new to the bot framework and at first I got confused by the semantic meaning of the `triggerAction` function when registering a dialog. It seemed to me that the dialog *would trigger* an action instead of *being triggered* by an action.

My suggestion is to add an alternative function that works in the same way but is named differently, e.g. `triggeredWhenAction` or maybe `triggeredByAction`. The code would then read like this:

```javascript
bot.dialog('orderDinner', [
    //...waterfall steps...
])
.triggeredWhenAction({
    matches: /^order dinner$/i
});
```

Any thoughts?

PS: I apologize if this is not the right channel for this kind of discussion.

**Comment by JasonSowers** [comment]
@samiraguiar thanks for sharing your thoughts.

**Comment by nwhitmont** [comment]
@samiraguiar 
1. BotBuilder SDK is open source project, feel free to submit a pull request with your proposed change or enhancement, and the SDK team will review it.
2. You can easily create an alias to this function with your custom name, if that works better for you.
