### ISSUE TITLE
[Question] SuggestedActions (imBack) with WebChat

### ISSUE THREAD

**Issue by maximilianspringer** [Microsoft/BotBuilder#3353]
## System Information
* SDK Language: Node.js
* SDK Version: 6.11.2
* Development Environment: Amazon EC2 Server

## Issue Description
When using SuggestedActions with WebChat or Emulator, the "title" parameter of the imBack function is displayed as suggestion while the "msg" parameter is displayed after clicking on the suggestion. Since both values are visible to the user, it is not possible to use them to send an internal value to the bot.

In FB messenger it works differently: the "title" is used for the button and for the display after clicking the button.

## Code Example
```
var msg = new builder.Message(session)
		.text("Yes or No?")
		.suggestedActions(
			builder.SuggestedActions.create(
					session, [
						builder.CardAction.imBack(session, "1", "Yes"),
						builder.CardAction.imBack(session, "0", "No")
					]
				));
session.send(msg);
```

## Expected Behavior
The user gets to see two suggestions: "Yes" and "No". After clicking "Yes", "Yes" is displayed in the WebChat as his answer. In my code, I receive the internal value "1".

## Actual Results
The user gets to see two suggestions: "Yes" and "No". After clicking "Yes", "1" is displayed in the WebChat as his answer. In my code, I receive the internal value "1".

**Comment by stevengum97** [comment]
Looks like the same as BotFramework-webchat [issue #459](https://github.com/Microsoft/BotFramework-WebChat/issues/459).

@danmarshall any updates or thoughts on this?

**Comment by stevengum97** [comment]
@maximilianspringer, I spoke with Dan and we're going to close this issue here because it's being tracked over on the [BotFramework-webchat repo](https://github.com/Microsoft/BotFramework-webchat/). Please follow [**#459**](https://github.com/Microsoft/BotFramework-WebChat/issues/459) for updates.
