### ISSUE TITLE
[Question] Change the title of Web Chat from 'Chat' to something else?

### ISSUE THREAD

**Issue by neetgupta7** [Microsoft/BotBuilder#3354]
## System Information
* SDK Language: .NET
* SDK Version: 3.8.0
* Development Environment: App Service

We want to change the title of webchat window which current says chat. Is it possible to pass some parameters like userid and username in the url which can do that.

**Comment by nwhitmont** [comment]
@neetgupta7 You can accomplish this by adding the following Javascript to your WebChat page:
```js
window.onload = function() {
  document.getElementsByClassName("wc-header")[0].lastChild.innerText = "Custom header text";
};
```
