### ISSUE TITLE
[Skype Web Control] Markdown support?

### ISSUE THREAD

**Issue by mminchev** [Microsoft/BotBuilder#3356]
## System Information
* SDK Language: Node.js
* SDK Version: 3.9.1
* Development Environment: Localhost & Azure

## Bot Info 
* Bot name: Test Bot 2
* Bot handle: tv-test-bot-2  
* App ID: bcfdd1f3-1e9d-45d9-8d1e-df5f75682a47
* Connected channels: Skype Web Control

## Issue Description
I am using Skype Web Control and I am experiencing a problem with the Markdown support. More precisely, when I am using bullets + links or bullets + bold text in a message, the bullets are not rendered correctly. When clicked, the links also open inside the iframe of Skype Web Control instead of opening in a new window.

## Code Example 1
When I send the following message:
`
session.send('Here are the options we can offer you: \n\n * Option 1 [link](https://www.microsoft.com) \n\n* Option 2 [link](https://www.microsoft.com) \n\n* Option 3 [link](https://www.microsoft.com)');
`

I get the following result:

![1](https://user-images.githubusercontent.com/1804640/29542435-79e137e2-86e3-11e7-83c6-001a916145cd.png)

When I do not use links or bold in the bullets, everything is rendered as expected.

![2](https://user-images.githubusercontent.com/1804640/29542436-79e415ca-86e3-11e7-9940-0ccdd3876457.png)

## Steps to Reproduce the Issue
1. Open a conversation with a bot via the Skype Web Control.
2. Send a message including markdown with bullets + links from the bot to the user.

## Expected Behavior
The bullets should be rendered with HTML and links should open in a new window/tab when clicked.

## Actual Results
Bullets are not rendered as HTML but as plain text. Also the links open inside the iframe instead of opening in a new tab. They are missing "target=_blank".

**Comment by nwhitmont** [comment]
As of this writing, Skype Web Control does not support Markdown formatted messages. 

See: https://support.skype.com/en/faq/FA34704/what-is-skype-web-control

**What can I send through Skype Web Control?**
>You can send messages, pictures, and files. We're keeping things simple so you can't send emoticons yet. To send attachments, select the attachment icon and then choose a file to send.

**Comment by mminchev** [comment]
Well, apparently it does support Markdown in messages but it does not support it completely.

**Comment by ganesh1190** [comment]
Need only BOLD and ITALIC.
Any idea...? Please share.

**Comment by RishabhTayal** [comment]
Any update on support for markdown? I am trying to show code markdown using ```. and it doesn't work.
