### ISSUE TITLE
[LUIS] Response time slow?

### ISSUE THREAD

**Issue by rahulmistry25425** [Microsoft/BotBuilder#3357]
## System Information
* SDK Language: .Net
* SDK Version: 3.9.0.0
* Development Environment: localhost and VPS

## Bot Info 
* Bot name: Evince Support
* Bot handle: webchat
* App ID: 92b6bf51-8cfe-481b-bddf-7044e3fdb8fe
* Connected channels: not yet

## Issue Description
I have created demo application which is contain greetings and some manual operations. when user greets to bot for ex: Hello or hi , it will check through the Microsoft LUIS and after receiving intents various operations and responses are performed.if user says hi or hello than bot will responses **Hello there,how can i help you today !!!**

while user sending any message lets say hi than its taking 3 to 5 sec to response back, sometimes bot showing **retry** option, when user clicks on retry it is giving two responses **i.e Response of first hi and response of second hi** , also in bot framework its showing **There was an error sending this message to your bot: HTTP status code InternalServerError** as a issues in my app

i am using Microsoft bot framework and my bot is deployed on VPS for development purpose,also integrated LUIS to recognizing intents.development language i have used is **.Net**. 

_**please let me know how can i improve the response time of bot.**_

## Expected Behavior
whenever user asking something to bot,it should be quick in response.

## Actual Results
its taking 3 to 5 seconds of response time, sometime its showing **retry**

**Comment by JasonSowers** [comment]
Is it always the first message that is slow, or are all messages slow?

**Comment by rahulmistry25425** [comment]
not only first message but all messages are slow.my bot is deployed on VPS, does it make any sense

**Comment by rahulmistry25425** [comment]
Is there any solutions or options to improve the response time of bot?

**Comment by rahulmistry25425** [comment]
@JasonSowers any update ? still waiting

**Comment by EricDahlvang** [comment]
@rahulmistry25425 can you share your bots code?  InternalServerError generally means there was an issue within your bot itself.

**Comment by JasonSowers** [comment]
closing this issue, feel free to continue the conversation if needed still
