### ISSUE TITLE
[Question] How to monitor the chat bot logs?

### ISSUE THREAD

**Issue by ne00346536** [Microsoft/BotBuilder#3359]
Hi Team,

I want to monitor user chat history and the response returned by the bot for user query . Kindly let me know how to track and monitor bot and user interactions. 

Thanks,
Naresh

**Comment by nrobert** [comment]
Which implementation: .Net or Node.js?

**Comment by ne00346536** [comment]
@nrobert implementation with Node JS.

**Comment by nrobert** [comment]
You should be looking for "middleware" functionality described here in the documentation: https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-intercept-messages

You will be able to intercept messages and log them wherever you want.
Don't forget to add both `botbuilder` for incoming messages and `send`for outgoing messages

**Comment by ne00346536** [comment]
@nrobert  Thanks for the reply can you please let me know where can i check these logs.

In my local server i am able to find these logs  in my  console but for deployed apps in azure where can i find these logs.

Thanks,
Naresh.

**Comment by nwhitmont** [comment]
@ne00346536 You would need to configure the logging yourself. 

For example, instead of logging to console.log, write your log messages to a text file or database, or use a logging module like [Winston](https://github.com/winstonjs/winston) or [simple-node-logger](https://www.npmjs.com/package/simple-node-logger). It is up to you how to configure it.

**Comment by ne00346536** [comment]
@nwhitmont   we have tried with winston module and able to create a file and saving the logs to the created file , this is working fine in local but when we deployed this source code to azure its not able to create the file.

For ex:  file path mentioned  as  below and created a  logs folder under source code directory  and trying to update the logs to this path.

'filename': './logs/access.log'

Please find the attached screenshot of directory structure in azure .Kindly let me know the issue.

![image](https://user-images.githubusercontent.com/25633986/29859847-8e471bda-8d81-11e7-9c05-a0b05d99c096.png)

Thanks,
Naresh

**Comment by terabytes** [comment]
For those interested in logging chat bot history to a database, I was able to log chat bot conversations to MongoDB by doing [this](https://github.com/Microsoft/BotBuilder/issues/3682#issuecomment-360585870).
