### ISSUE TITLE
Difference between message.SetBotPerUserInConversationData and context.PerUserInConversationData.SetValue?

### ISSUE THREAD

**Issue by Praggie** [Microsoft/BotBuilder#336]
I am finding it bit difficult to understand the difference between 

message.SetBotPerUserInConversationData and context.PerUserInConversationData.SetValue.

Looks like message.PerUserInConversationData and context.PerUserInConversationData are **not in sync.**

If I use context.PerUserInConversationData.SetValue to set the ResumptionCookie then things work fine but not with message.SetBotPerUserInConversationData.

In the facebook auth example if you set ResumptionCookie using  message.SetBotPerUserInConversationData then it is not visible in callback controller using following code.

  IBotData dataBag = new JObjectBotData(reply);
  ResumptionCookie pending;
  if (dataBag.PerUserInConversationData.TryGetValue("persistedCookie", out pending))
{
}
 
pending is always null here.

**Comment by msft-shahins** [comment]
underneath both use JObject to store the <key,value> pairs and they should be in sync if data is loaded and persisted correctly with the connector service. I am suspicious that you are not persisting the data correctly with connector service. We have exact same code path [here](https://github.com/Microsoft/BotBuilder/blob/develop/CSharp/Samples/SimpleFacebookAuthBot/Controllers/OAuthCallbackController.cs#L48) that works and loads the cookie.
