### ISSUE TITLE
[Skype] Error: "Messaging disabled until request is accepted"?

### ISSUE THREAD

**Issue by spefanis** [Microsoft/BotBuilder#3360]
## System Information
* SDK Language: .net
* SDK Version: 
* Development Environment: Azure Website

## Bot Info 
* Bot name: team5_VoiceAsPassword
* Bot handle: team5_VoiceAsPassword
* App ID: c69007fd-056c-411c-bcfe-c2861caf1ce5
* Connected channels: Skype

## Issue Description
Unable to talk to Bot on skype. Comes up with "Messaging disabled until request is accepted". Able to use the web test without any issues. I've checked my endpoints and it seems to be correct. Unsure what else is causing this issue.

**Comment by spefanis** [comment]
Additionaly, when someone else adds the bot to their contact it works fine.

**Comment by JasonSowers** [comment]
Have you tried removing and re-adding the bot?

**Comment by spefanis** [comment]
Yea. I tried removing the bot and adding again. All I end up with is:

[cid:image001.jpg@01D31DDA.BAD3E000]

**Comment by spefanis** [comment]
Anyone have any suggestions? It just seems to not want to add the bot on my PC
![image](https://user-images.githubusercontent.com/19632869/29746180-35f43de6-8b15-11e7-88b9-ef277b5c9e14.png)

**Comment by JasonSowers** [comment]
@spefanis  did you get this working?

**Comment by prasannadeshappriya** [comment]
Hay did you found any solution for this?. I have the same problem
