### ISSUE TITLE
Extract string or number array via luis 

### ISSUE THREAD

**Issue by neetgupta7** [Microsoft/BotBuilder#3362]
## System Information
* SDK Language: .NET
* SDK Version: SDK version
* Development Environment: , App Service

Hello
Can through LUIS or Bot we extract string or integer array from data. e.g. When user says update order lines items 1 to 10, or 1-10 or 1,2,3 and 10 etc. Want this to be extracted as string array. Is there any solution via LUIS or something else that we can do.

**Comment by JasonSowers** [comment]
Could you please further explain your use case so we may better assist you?

**Comment by neetgupta7** [comment]
Let's say the user utterance on luis contains a range of numbers like 1 to 10, 1-10, 2 through 20, or (1,23, and 20) etc. I want luis to intelligently provide the array of numbers that is contained in the range. New date function in luis is very intelligent, on similar lines if we can have array of numbers that can be picked from range would be helpful.

**Comment by JasonSowers** [comment]
There's no native way to accomplish this with LUIS.  You would need to handle this in your c# code prior to sending it to LUIS. Closing this issue, but feel free to continue this conversation.

**Comment by neetgupta7** [comment]
@JasonSowers  Is it possible to add this to the requested feature list.

**Comment by JasonSowers** [comment]
This repo is for bot framework SDK's and what you are asking for would be on the LUIS side.  Please use their [User Voice](https://cognitive.uservoice.com/forums/551524-luis) forum to request a feature.  
  
The fastest and easiest way to accomplish what you need is an implementation in your bot code as I said before.  I'm not sure where this feature request would land on their roadmap or how it would be prioritized.
