### ISSUE TITLE
[Question] Is there an API for creating bot registrations on https://dev.botframework.com?

### ISSUE THREAD

**Issue by VishalWaman** [Microsoft/BotBuilder#3363]
Do we have API for https://dev.botframework.com/
i.e.  
1. Create new Bot and setting AppID and Keys
2. Setting Channels 

Thanks in advance

**Comment by nrobert** [comment]
As far as I know, there is no such API no.

**Comment by JasonSowers** [comment]
This is not currently a feature.

**Comment by nwhitmont** [comment]
Currently not a feature.
