### ISSUE TITLE
Extend documentation and examples for buttons, cards, their actions

### ISSUE THREAD

**Issue by akontsevich** [Microsoft/BotBuilder#3364]
## System Information
* SDK Language: Node.js
* SDK Version: 3.9
* Development Environment: localhost

Is it possible extend documentation and examples for buttons, cards, their actions (postBack, url, etc), layouts, properties, etc? To understand and SEE how they work need to go to the doc, examples, github issues, stackowerflow, blogs, etc. Good if one source in documentation will be enough. Thanks!

**Comment by akontsevich** [comment]
Never mind, after:
- [Rich Cards](https://github.com/Microsoft/BotBuilder-Samples/blob/master/Node/cards-RichCards) and
- [Carousel of Cards](https://github.com/Microsoft/BotBuilder-Samples/blob/master/Node/cards-CarouselCards)

examples mostly clear, have issues however.

**Comment by JasonSowers** [comment]
For adaptive cards there is also adaptivecards.io
