### ISSUE TITLE
[Question] Is there an API for getting a list of QnAMaker services for a subscription?

### ISSUE THREAD

**Issue by pkpaul5** [Microsoft/BotBuilder#3365]
I checked in the list of QnAMaker APIs(https://westus.dev.cognitive.microsoft.com/docs/services/58994a073d9e04097c7ba6fe/operations/58994a073d9e041ad42d9baa).

There is no API for getting list of QnAMaker services.

**Comment by nwhitmont** [comment]
Correct - this information is not currently available via API.

**Comment by pkpaul5** [comment]
is there any plan to include such API in near future

**Comment by JasonSowers** [comment]
The correct place to ask that question would be on [this repo](https://github.com/Microsoft/BotBuilder-CognitiveServices)
