### ISSUE TITLE
[Feature Request, Cortana] "Speak" support for PromptDialog.Text?

### ISSUE THREAD

**Issue by neetgupta7** [Microsoft/BotBuilder#3368]
## System Information
* SDK Language:  .NET
* SDK Version: 3.8.0
* Development Environment: App Service

Hello 
I dont see 'speak' property available for PromptDialog.Text while it is available for PromptDialog.Choice. Is there any plan to add it in immediate future. If not what alternatives are available for Cortana instead of PromptDialog.Text.

**Comment by neetgupta7** [comment]
@nwhitmont @JasonSowers Can this be added as future capabilities.

**Comment by JasonSowers** [comment]
@neetgupta7  We can log this as a feature request, but cannot guarantee it will be added or any timeline for it to be added.

**Comment by jeremy-st** [comment]
Yes this would be very useful. Thanks!

**Comment by vishwacsena** [comment]
Fixed via #4714
