### ISSUE TITLE
Bug in iOS Facebook Messenger

### ISSUE THREAD

**Issue by eddie1976** [Microsoft/BotBuilder#337]
For anyone who is developing Chat Bot for Facebook Messenger, here is a bug I found in iOS Facebook Messenger. In my attached screenshot, I created some bubbles with 3 buttons and 1 bubble with only 1 button. The picture of last bubble is not clickable (item_url is set) in iOS Facebook Messenger (version 71.0) but in Android or Web-based Facebook Messenger, it works fine.

I have reported this to Facebook Messenger team twice but no one reply to me.

![img_1757](https://cloud.githubusercontent.com/assets/8769955/15494320/69fd1f2c-21bc-11e6-8170-fe42b2742d37.PNG)

**Comment by msft-shahins** [comment]
Closing this since it is not bot framework related.
