### ISSUE TITLE
[Cortana] Use of Connected Services authentication?

### ISSUE THREAD

**Issue by neetgupta7** [Microsoft/BotBuilder#3370]
## System Information
* SDK Language: .NET
* SDK Version: 3.8.0
* Development Environment: App Service

Hello
Whats the use of Connected Services authentication in Cortana. It just lets user authenticate for the skill before using it. Can it tell bot service that user id is abc@test.com. 
If the Bot does not actually get to know who it is talking to then whats the use of this authentication.

**Comment by JasonSowers** [comment]
Have you read through this documentation https://docs.microsoft.com/en-us/cortana/tutorials/bot-skills/bot-skill-auth

**Comment by neetgupta7** [comment]
@JasonSowers I read that but can you please validate my understanding. Connected services are not so much useful for your authentication/authorization for the skill but capturing authentication token from entities under activity for Cortana we can use this for offering SSO experience to other resources connected with that MSA id.
