### ISSUE TITLE
[FB Messenger] (1) Adaptive Card not working & (2) Unable to send table formatted message?

### ISSUE THREAD

**Issue by hardikchoudhary** [Microsoft/BotBuilder#3371]
//  var tableHTML = '<table style="padding:10px;border:1px solid black;"><tr style="background-color:#c6c6c6"><th>Station Name</th><th>Distance</th><th></tr><tr><td>' + resultsMetroName[0] + '</td><td>' + data[0].distance + '</td></tr><tr><td>' + resultsMetroName[0] + '</td><td>' + data[0].distance + '</td></tr></table>';
                            //var message = {
                              //  type: 'message',
                                //textFormat: 'xml',
                                //text: tableHTML
                            // };

session.send(msg);

In messenger i am getting same result in string

table style="padding:10px;border:1px solid black;"><tr style="background-color:#c6c6c6"><th>Station Name</th><th>Distance</th><th></tr><tr><td>' + resultsMetroName[0] + '</td><td>' + data[0].distance + '</td></tr><tr><td>' + resultsMetroName[0] + '</td><td>' + data[0].distance + '</td></tr></table>'

How i can send the html

In Adaptive I am getting only the title but the buttonthat i have added in adaptive card is not showi8ng up

**Comment by nwhitmont** [comment]
@hardikchoudhary Are you using .NET or Node.js SDK?

**Comment by hardikchoudhary** [comment]
I am using node js

**Comment by mukeshzt** [comment]
I'm also looking for the same functionality for skype client using nodejs SDK. 
I laready posted the question on [Stackoverflow](https://stackoverflow.com/questions/45433557/how-to-display-the-data-in-table-html-format-in-skype-bot-node-js-sdk)

**Comment by ryaan-web** [comment]
Please help me in this regard

**Comment by hardikchoudhary** [comment]
Please let us know is it possible to send table structure ??? @nwhitmont

**Comment by hardikchoudhary** [comment]
@nw please let me know if we have the solution in this...

**Comment by JasonSowers** [comment]
I was unable to find documentation that says facebook messenger allows for HTML in messages.  I did read from [a blog](https://www.techwalla.com/articles/can-you-put-html-in-facebook-messages) that the HTML will display exactly as the string you put it in as.  This is consistent with the behavior you are seeing so all signs point to HTML not being allowed in facebook messages.
