### ISSUE TITLE
[FB Messenger] Checkbox Plugin support?

### ISSUE THREAD

**Issue by Veikedo** [Microsoft/BotBuilder#3372]
## System Information
* SDK Language: .NET
* SDK Version: 3.9.0

## Issue Description
Hello!
I'm adding [Facebook Checkbox Plugin](https://developers.facebook.com/docs/messenger-platform/plugin-reference/checkbox-plugin), and I have a trouble with getting opt-in callback - it just does not come to our server (I set a breakpoint in my `Application_BeginRequest` method and nothing happened).
As far as I understand it's not supported now? If so, then how can I workaround this issue?

I think I can set my own webhook, where I can switch between callbacks, ie: 
1. a webhook request comes to my server
2. I see if it is an Plugin opt-in callback
3. If it is, then I process my own logic
4. Otherwise I send the request to Bot Framework url

But I wonder is there a more convenient way?

**Comment by Veikedo** [comment]
In case somebody have the same issue. Added my own webhook.

        [HttpPost]
        [HttpGet]
        [Route("api/FacebookWebHook/{*remaining}")]
        public async Task<HttpResponseMessage> CallbackAsync()
        {
            if (Request.Method == HttpMethod.Post)
            {
                await Request.Content.LoadIntoBufferAsync().ConfigureAwait(false);
                string json = await Request.Content.ReadAsStringAsync().ConfigureAwait(false);
                if (!string.IsNullOrEmpty(json))
                {
                    JObject o = JObject.Parse(json);
                    JToken token = o.SelectToken("entry[0].messaging[0].optin");
                    if (token != null)
                    {
                        var userRef = token.SelectToken("user_ref")?.Value<string>();
                        var userEmail = token.SelectToken("ref")?.Value<string>();

                        if (userRef != null && userEmail != null)
                        {
                            dynamic result = await _facebookClient
                                .PostTaskAsync("me/messages", new {
                                    access_token = _appSettings.FacebookPageAccessToken,
                                    recipient = new {
                                        user_ref = userRef,
                                    },
                                    sender_action = "mark_seen"
                                    // message = new {
                                    //     text = "Hi there!"
                                    // }
                                })
                                .ConfigureAwait(false);
                        }
                    }
                }
            }

            const string host = "facebook.botframework.com";
            string forwardUri = $"https://{host}/api/v1/bots/billycom{Request.RequestUri.Query}";

            Request.Headers.Remove("Host");
            Request.RequestUri = new Uri(forwardUri);
            if (Request.Method == HttpMethod.Get)
            {
                Request.Content = null;
            }

            var client = new HttpClient();
            HttpResponseMessage httpResponseMessage = await client
                .SendAsync(Request, HttpCompletionOption.ResponseHeadersRead)
                .ConfigureAwait(false);
            return httpResponseMessage;
        }

**Comment by Veikedo** [comment]
And more question - now I have a table for all my conversations. It looks like this:
![image](https://user-images.githubusercontent.com/5779339/29712955-8d1e9d5a-89c6-11e7-9be7-ff97965f51bd.png)

However, when I use Checkbox Plugin there is no conversation with the user.
So, the question is - can I use `BotId/ServiceUrl/ChannelId` from the other conversation? i.e. is the `BotId` stable within the channel?

**Comment by JasonSowers** [comment]
are you seeing behavior that suggests the BotId does not remain the same?
