### ISSUE TITLE
[Direct Line] Error "message": "Failed to send message: bot returned an error" + InternalServerError

### ISSUE THREAD

**Issue by guneetkalra** [Microsoft/BotBuilder#3373]
## System Information
* SDK Language: .NET
  

## Bot Info 
* Bot name: DlGeneral
* App ID: 0f0b60e2-75de-4e73-bbfc-877e1c186f16
* Connected channels: DirectLine

## Issue Description
Bot Working well with channels such as Webchat Skype but gives error with Directline  Failed to send message: bot returned an error" + InternalServerError

## Code Example
 var conversation = await client.Conversations.StartConversationAsync().ConfigureAwait(false);
         returns null 

 ## Expected Behavior
This should give a conversation ID 

## Actual Results
 "message": "Failed to send message: bot returned an error"

**Comment by JasonSowers** [comment]
Please provide the minimum code required to reproduce the issue.
