### ISSUE TITLE
[Question] How to save custom data in conversion while initiating conversation from bot?

### ISSUE THREAD

**Issue by gomteshhatgine** [Microsoft/BotBuilder#3374]
## System Information
* SDK Language:  .NET 

## Issue Description
Currently from custom API  I successfully initiating conversation using Bot in MS teams channels and sending Hero card into channel **but after that I have to set conversation data** like **SetConversationData** So How can I put that some data after sending Hero card

## Code Example
```cs
       public async Task<HttpResponseMessage> PostCard(ClauseRequest clauseRequest)
          {
            try
            {

                var channelId = "19:" + tempChannelId + "@thread.skype";
                var serviceUrl = ConfigurationManager.AppSettings["ServiceUrl"];
                var connector = new ConnectorClient(new Uri(serviceUrl));
                var channelData = new Dictionary<string, string>();
                channelData["teamsChannelId"] = channelId;
                IMessageActivity newMessage = Activity.CreateMessageActivity();
                newMessage.Type = ActivityTypes.Message;

                var attachment = GetHeroCard(clauseRequest);
                newMessage.Attachments.Add(attachment);

                ConversationParameters conversationParams = new ConversationParameters(
                    isGroup: true,
                    bot: null,
                    members: null,
                    topicName: "Test Conversation",
                    activity: (Activity)newMessage,
                    channelData: channelData);
                MicrosoftAppCredentials.TrustServiceUrl(serviceUrl, DateTime.MaxValue);
                var temp = await connector.Conversations.CreateConversationAsync(conversationParams);

                /**// After this, here I want to save some data into conversation**
              // As this is custom API I dont have Activity object

                var response = Request.CreateResponse(HttpStatusCode.OK);
                return response;
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
```
## Expected Behavior
After initiating conversation by Bot I have to save some state data

**Comment by EricDahlvang** [comment]
Hi @gomteshhatgine 

It is possible to create the default State Client directly:

```cs
StateClient stateClient = new StateClient(new MicrosoftAppCredentials(microsoftAppId, microsoftAppPassword));
```
ref: https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-state#state-client

However, the default state client should only be used for prototyping.  It is not designed for production bots.  The recommended method is to use one of the Azure Extensions (or implement your own custom state client): https://github.com/Microsoft/BotBuilder-Azure  and create the IBotDataStore implementation directly.

Please also review this blog post: https://blog.botframework.com/2017/07/18/saving-state-azure-extensions

**Comment by gomteshhatgine** [comment]
Hi thanks for reply,
As you suggested link in that for save state data for channels i have used **GetConversationData** method

[https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-state#save-state-data]

But here required,

`BotData channelData = await stateClient.BotState.GetConversationData(ChannelId, ConversationId);
channelData .SetProperty<bool>("SentGreeting", true);
await stateClient.BotState.SetConversationDataAsync(ChannelId, ConversationId, userData);`


I got channel Id  from Microsoft Graph API in Graph Explorer
i.e.   "02217c39-3d1d-4102-a04b-88db74bae6aa"
**But when I use this channelId its gives exception**

**Also Another query is where should I get ConversationId  as the conversation initiated throught custom API so I dont have activity object**

**Comment by EricDahlvang** [comment]
You do actually have an activity object: `IMessageActivity newMessage = Activity.CreateMessageActivity();`  The newMessage IS an activity.  

Here is the list of valid channels:ids https://github.com/Microsoft/BotBuilder/blob/605eeceb36c01771d7146b39a6ec8b2184ad41a6/CSharp/Library/Microsoft.Bot.Builder/ConnectorEx/IChannelCapability.cs#L39

The conversation Id is on the object returned from the call to CreatConversationAsync.  

What you are doing is conceptually called Proactive Messaging.  You are proactively trying to send a message to a user on a specific channel.  We have a few examples of proactive messaging here: https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/core-proactiveMessages

**Comment by gomteshhatgine** [comment]
Hi @EricDahlvang ,
   I have now successfully set value in my API method such as

              ` StateClient stateClient = new StateClient(new 
                MicrosoftAppCredentials(ConfigurationManager.AppSettings["MicrosoftAppId"], 
                ConfigurationManager.AppSettings["MicrosoftAppPassword"]));

                BotData userData = stateClient.BotState.GetConversationData("msteams", conversation.Id);
                userData.SetProperty<bool>("SentGreeting", true);
                await stateClient.BotState.SetUserDataAsync("msteams", conversation.Id, userData);`

And when I ping to bot from MS teams channel where I send card, after ping I have written code 

                `  public async Task<HttpResponseMessage> Post([FromBody]Activity activity)
        {
            try
            {
                StateClient stateClient = new StateClient(new MicrosoftAppCredentials(ConfigurationManager.AppSettings["MicrosoftAppId"], ConfigurationManager.AppSettings["MicrosoftAppPassword"]));

                BotData userData = stateClient.BotState.GetConversationData(activity.ChannelId, activity.From.Id);
                var temp = userData.Data;
                var sentGreeting = userData.GetProperty<bool>("SentGreeting");`

**But here in temp I getting null** i.e that state value getting null

**Comment by EricDahlvang** [comment]
1) When the conversation is created in the PostCard method, the bot and members should not be null.  A bot is required for the conversation, and so is a user.

2) Try using UserData, instead of ConversationData. msteams will create the conversation when the user communicates with the bot.  I don't believe you can create a conversation outside of msteams, then communicate with that conversation from the msteams application.

**Comment by gomteshhatgine** [comment]
Its Done 💯  Thank you very much for help 👍
