### ISSUE TITLE
[Question] Extend documentation and examples regarding LUIS

### ISSUE THREAD

**Issue by akontsevich** [Microsoft/BotBuilder#3375]
## System Information
* SDK Language: Node.js
* SDK Version: 3.9.1
* Development Environment: localhost

## Issue Description
Googled through tons of pages before found this: https://github.com/Microsoft/BotBuilder/issues/2741#issuecomment-301888868

## Code Example
```
builder.LuisRecognizer.recognize(session.message.text, '<model url>', function (err, intents, entities) {
     if (entities) {
            var entity = builder.EntityRecognizer.findEntity(entities, 'TYPE');
            // do something with entity...
     }
});
```
Good to extend documentation and examples to include above code and explanation to add simple recognition on desired step, not for whole bot or dialog.

Also question: how to get `topScoringIntent` here?

**Comment by stevengum97** [comment]
@akontsevich, to retrieve the `topScoringIntent` from your code, you can just retrieve the first element in `intents`.

```js
builder.LuisRecognizer.recognize(session.message.text, '<model url>', function (err, intents, entities) {
     switch (intents[0]) {
       case 'HelpIntent':
          session.send('You\'ve triggered the help intent.');
          session.beginDialog('HelpIntent');
          break;
       default:
          session.send('What?');
          session.beginDialog('/');
     }
});
```

Or you can _only_ receive the `topScoringIntent` by configuring your LUIS endpoint by setting the verbose flag to **false** like so:

> https://westus.api.cognitive.microsoft.com/luis/v2.0/apps/app-id?subscription-key=subscription-key&timezoneOffset=0&verbose=false&q=

**Comment by akontsevich** [comment]
Yeah, I've already done this way: `var topScoringIntent = intents[0];`

**Comment by stevengum97** [comment]
I'm closing this issue as the question has been answered. Regarding the improving the documentation, I'll talk with the Docs team to include how to use `LuisRecognizer.recognize()` on a waterfall step.
