### ISSUE TITLE
Get User ID of the Skype Channel

### ISSUE THREAD

**Issue by anirudhaditya** [Microsoft/BotBuilder#3376]
I am using skype channel and need to know how to get the logged in user name and pass it to the bot. During debugging I figured out that I can only pull the display name and not the userID or the email ID. Can anyone assist on this. 

Thanks
Aniruddha

**Comment by mukeshzt** [comment]
@anirudhaditya 
I don't think skype share such info as it affects user privacy. 
v3 version of the API provides the unique user ID per bot.
you can access those by using 

```
session.message.user.id
session.message.address.user.name
```
More about message.address JSON Please [check this post](https://github.com/Microsoft/BotBuilder/issues/1637#issuecomment-259912934)

**Comment by JasonSowers** [comment]
This is not currently a feature of bot framework.  You may however, be able to access this information via the skype API or the graph api depending on your use case

**Comment by Basavarajsk1992** [comment]
Can we get the Skype user profile info?

**Comment by chintan3100** [comment]
How can we get user information (User id) with Skype API?
