### ISSUE TITLE
[Question] There was an error sending this message to your bot: HTTP status code GatewayTimeout

### ISSUE THREAD

**Issue by SyedAbdullahQamar** [Microsoft/BotBuilder#3378]
![screenshot_1](https://user-images.githubusercontent.com/30691226/29664557-784fefc4-88e9-11e7-9b00-f4329f00ca5e.png)

AppID = 51931722-cd5e-474f-8cdc-43612b0dd4e8
BotHandle = bots_m3tech
URL = https://bots.m3tech.com.pk/api/messages

My Bot was working perfectly today till morning 10:00 AM but now i am getting this error "There was an error sending this message to your bot: HTTP status code GatewayTimeout".
Bot isn't responding on Skype and when i checked on developer bot framework Test it shows me this error. My bot is also working fine on Bot Framework Emulator. Kindly Help.

**Comment by nwhitmont** [comment]
@SyedAbdullahQamar For reference, are you using .NET or Node.js SDK?

**Comment by JasonSowers** [comment]
Also is this only happening with the first message you are sending? I tested you bot and this was the case for my test

**Comment by SyedAbdullahQamar** [comment]
Thank you guys. Now my bot is working fine. I don't why it was giving errors yesterday. But i have one more query. My bot didn't respond on the first message we send but it respond to the second message. can u tell me why it is happening?

**Comment by JasonSowers** [comment]
Closing this issue because the original question was answered.

For your next question what channel is this happening on?

**Comment by SyedAbdullahQamar** [comment]
It is happening on Skype.
Actually i added my bot to Skype only, i don't know if it will do the same problem with other channels also.

**Comment by JasonSowers** [comment]
How are you hosting your bot?

**Comment by SyedAbdullahQamar** [comment]
Hosting my bot on Virtual Machine.

**Comment by JasonSowers** [comment]
Are you using a valid certificate?  
  
The Bot Framework requires that the x.509v3 certificate exposed by your endpoint be current and valid. Most of the checks for "current and valid" are standard checks for server SSL certificates: the Certificate Name must match the hostname, it must not be expired, it must not be listed in a CRL, it must have the correct set of EKUs, etc.
Most importantly, your SSL certificate must chain to a root certificate authority trusted by Microsoft. The latest list of these CAs is available here: http://social.technet.microsoft.com/wiki/contents/articles/31634.microsoft-trusted-root-certificate-program-participants-v-2016-april.aspx

**Comment by SyedAbdullahQamar** [comment]
Yes yes. I am using a valid certificate because if i am not using a valid certificate i will never be able to integrate my bot to Skype.
