### ISSUE TITLE
[Question] Is conversationData deleted on channels that don't support endConversation() ?

### ISSUE THREAD

**Issue by bilby91** [Microsoft/BotBuilder#3379]
## System Information
* SDK Language: Node.js
* SDK Version: 3.9
* Development Environment: localhost, other

## Bot Info 
* Bot name: suttna_dev_bilby
* Bot handle: suttna_dev_bilby 
* App ID: 5b410643-435b-4784-ba03-3b1c3a9f1918
* Connected channels: Slack, MS Teams

## Issue Description
I was wondering when is the conversationData deleted on channels that don't support endConversation (like Teams #3300).

Is conversationData stored forever ?

Thanks

**Comment by bilby91** [comment]
Any updates on this ?

**Comment by bilby91** [comment]
Any updates ? From what I found the only way to clear the conversationData and privateConversationData is calling endConversation which thorws an error when calling in a msteams session. This is a problem for anyone that uses teams and need to clear conversation information.

**Comment by JasonSowers** [comment]
Let me reach out to the MS teams team for you.

**Comment by bilby91** [comment]
@JasonSowers Thanks for the reply. I think that a quick fix could be overriding `send` here https://github.com/OfficeDev/BotBuilder-MicrosoftTeams/blob/master/Node/src/TeamsChatConnector.ts

```
public send(messages: IMessage[], done: (err: Error, addresses?: IAddress[]) => void): void {
  return super.send(messages.filter((m) => m.type !== "endOfConversation"), done)
}
```

**Comment by JasonSowers** [comment]
You should put in a pull request with this fix if you think it will work 👍

**Comment by bilby91** [comment]
We are running that in production now and I can confirm that it solves the issue. Will push some code to the office repo.

**Comment by bilby91** [comment]
@JasonSowers Done https://github.com/OfficeDev/BotBuilder-MicrosoftTeams/pull/62/files

**Comment by billbliss** [comment]
@bilby91 your solution is a good one, thanks for the PR. Teams intentionally does not support the ability to delete conversation data for compliance reasons (what happens if the company is sued?) - the ability to delete or archive data is subject to a higher-level policy set at the tenant level. But we missed this error case in the SDK.

**Comment by EricDahlvang** [comment]
@bilby91 Awesome job!

I'll close this issue, since everything seems to be resolved.

**Comment by bilby91** [comment]
@billbliss @EricDahlvang Thanks for the reply. Make sense to not delete data by default and be able to configure at tenant level. I guess that the https://github.com/OfficeDev/BotBuilder-MicrosoftTeams/pull/62/files is a temporary fix since other channels that are being used via the chat connector may not support endOfCoversation too.
