### ISSUE TITLE
Skype Receiving Forbidden error

### ISSUE THREAD

**Issue by inornos** [Microsoft/BotBuilder#338]
Skype Receiving Forbidden error when i'm typing something for getting response
Please help me what i do
![image](https://cloud.githubusercontent.com/assets/14770190/15503820/79e69ac2-21d9-11e6-80b5-df4e35a6393c.png)

**Comment by msft-shahins** [comment]
@inornos have you updated your web.config with the right AppID and AppSecret before deployment? It seems that connector have auth issues calling your bot which is because of not having the right AppID and AppSecret. Forbidden implies that connector gets 403 calling your bot endpoint.

**Comment by inornos** [comment]
Yes my web.config is right I'm applying right App Id and App Secret.
I'm using Microsoft Bot Framework Emulator and its working with my online API, its responding me right

please check this image and please help me what i do for this, I'm excited to work with Skype bot Framework
![image](https://cloud.githubusercontent.com/assets/14770190/15528228/91b4123e-225f-11e6-913a-70d95c9d9730.png)

**Comment by inornos** [comment]
My Error with skype

![image](https://cloud.githubusercontent.com/assets/14770190/15537359/85155fe0-2293-11e6-96ea-5845e2e21b05.png)

**Comment by inornos** [comment]
My Problem is solved by changing bot id and app secret
