### ISSUE TITLE
[MS Teams] Service intermittent for proactive messages?

### ISSUE THREAD

**Issue by toxtli** [Microsoft/BotBuilder#3381]
## System Information
* SDK Language: Node.js
* SDK Version: Last
* Development Environment: Auzure Web Service

## Bot Info 
* Bot name: taskbot-prod
* Bot handle: taskbot-prod
* App ID: 1b435929-3da2-46ed-8ccc-29ecb50cf350
* Connected channels: MS Teams

## Issue Description
It seems that my dialog is not started when I try to send a proactive MS Teams message. I calculate that the 50% of the proactive message arrives. It was working perfectly at 8 am, but since 10 am it was very intermittent.

## Code Example
```js
bot.dialog("/Debug", [
  function (session, args, next) {
    session.endDialog("Hello");
  }
]);

var address = {
	"channelId" : "msteams",
	"bot" : {
		"id" : "28:1b435929-3da2-46ed-8ccc-29ecb50cf350",
		"name" : "taskbot-prod",
		"nickname" : "taskbot-prod"
	},
	"serviceUrl" : "https://smba.trafficmanager.net/amer-client-ss.msg/",
	"user" : {
		"id" : "29:1rf-2Bm6aD0BWc-yRNDFcgOBG1-uSaEjCWtJcoR-rcU-Humz3a_RddsCKifHqYpvNSUosrRpxUnYL907Qa1ZZuw",
		"name" : "John Smith"
	},
	"channelData" : {
		"tenant" : {
			"id" : "adb94d72-6cf3-4244-86ae-aa69c9f2ad43"
		}
	}
};

bot.beginDialog(address, "/Debug", {});
```
## Steps to Reproduce the Issue
1. Send a proactive message using bot.beginDialog

## Expected Behavior
Send the messages all the times.

## Actual Results
No errors, only the dialog is not invoked and the messages are not being delivered.

**Comment by nwhitmont** [comment]
@RichMoeMSFT

**Comment by nwhitmont** [comment]
@toxtli Can you list a specific conversation ID and exact time+timezone when you experienced the error? Thx

**Comment by fanidamj** [comment]
Closing the issue as it seems inactive. Feel free to reopen if you any questions or comments.
