### ISSUE TITLE
[Question] How to get the website's current logged in username into Node.js bot?

### ISSUE THREAD

**Issue by PrasadKosaraju** [Microsoft/BotBuilder#3384]
* SDK Platform: Node.js
* Active Channels: Web
* Deployment Environment:  Auzure Bot Service

## Issue Description
I created Anonymous bot right now and placed on html. The html is integrated with Web application so the bot can help on FAQ. Now we want to get user name from Web application and pass on to html bot which is hosted on webapp. Can one of you please help how we can get details and passed to bot in Node.js Bot.

**Comment by iMicknl** [comment]
Have a look at ['Using the backchannel mechanism'](https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-backchannel), which describes how to pass custom parameters to the chatbot using the WebChat.

**Comment by PrasadKosaraju** [comment]
Thanks. Is there working sample i can try out

**Comment by nwhitmont** [comment]
https://github.com/ryanvolum/backChannelBot
