### ISSUE TITLE
[Feature Request] Support Facebook Chat Extensions

### ISSUE THREAD

**Issue by moontear** [Microsoft/BotBuilder#3385]
## Issue Description
Facebook allows to create chat extensions which in turn allow bots to join / interact with group chats. These are extensions to existing bots: https://developers.facebook.com/docs/messenger-platform/guides/chat-extensions

It would be great if we could add these chat extensions to our bot framework bots, even if they are Facebook only right now - other messengers might add the possibility for bots to chat with a group as well.

**Comment by EricDahlvang** [comment]
Closing this issue. Messenger feature requests are tracked here: #4360 (I've referenced this one there)
