### ISSUE TITLE
[Question] When dialog is loaded dynamically, state is not preserved?

### ISSUE THREAD

**Issue by Enghouse-CCSP-PS** [Microsoft/BotBuilder#3386]
## Bot Info 
* Bot handle: 
* App ID: 
* SDK Platform:  .NET
* SDK Version: 3.9.0.0
* Active Channels: Emulator
* Deployment Environment: Emulator + VS2015
## Issue Description
Hello, we are trying to load dialogs dynamically from dll. When library with dialog is referenced or dll copied into BIN folder of ASP .net project everything is working fine, however when dll is not referenced or copied and only loaded using reflection from own project folder place- the state of conversation is not preserved, we are cycling trough first questions again and again.

## Code Example
Following code is called in API controller, we are getting new IDialog<object> instance from external library and using it for conversation.

```cs
        public async Task<HttpResponseMessage> Post([FromBody]Activity activity)
        {
            if (activity.Type == ActivityTypes.Message)
            {
	            await Conversation.SendAsync(activity, GetDialog);
            } 
            var response = Request.CreateResponse(HttpStatusCode.OK);
            return response;
        }


	    private IDialog<object> GetDialog()
	    {
		    var path = @"..\FirstImplementation.dll";
			var dialogWrapper = PluginLoader.Instance.TryGetOrAddInstanceImplementingInterface<IRootDialogWrapper>(path);  // Here we create object using assembly load and Activator class.
	        return dialogWrapper.GetRootDialog(null);
	    }

```

[FirstDialog.cs.txt](https://github.com/Microsoft/BotBuilder/files/1254478/FirstDialog.cs.txt)
[FirstDialogWrapper.cs.txt](https://github.com/Microsoft/BotBuilder/files/1254480/FirstDialogWrapper.cs.txt)
[dialogSchema.json.txt](https://github.com/Microsoft/BotBuilder/files/1254479/dialogSchema.json.txt)

## Reproduction Steps
1. Create class implementing dialog IDialog<object> in external dll
2. Load it using reflection
3. Write message from emulator to API
4. You will be constantly going in circles of the first question
5. Add reference to external dll or copy it to BIN folder and don't change the code, now you will be able to proceed to next steps after 1st one.

**Comment by jorupp** [comment]
This sounds like the same kind of symptom as #2407, though with a slightly different root cause.  May take a look at the options discussed on that thread and see if any help in this case.

**Comment by Enghouse-CCSP-PS** [comment]
yes - solution in #2407 solve it, thanks
