### ISSUE TITLE
[Question] Bot is not waiting for Prompts.choice input?

### ISSUE THREAD

**Issue by Arpafaucon** [Microsoft/BotBuilder#3387]
**[EDIT: SOLVED]** My mistake ( when calling from another dialog at least): 
> you shouldn't begin a dialog and end a dialog in the same waterfall step

*+ Unknown code-independent param?*

## Bot Info 
* Bot handle: 
* App ID: 5216ce6e-a1e1-41f9-999b-776a5606d377
* SDK Platform:  Node.js
* SDK Version:  botbuilder 3.9.1
* Active Channels:  Microsoft Bot Emulator
* Deployment Environment:  Test
[EDIT: added IDE]
* IDE: VS Code 1.15.1 -> used to launch the bot

## Issue Description

The bot isn't waiting for an input from the user after a `builder.Prompts.choice`. It skips to the next function in the waterfall instead.

## Code Example
```typescript
bot.dialog('qdj', [
    function (session) {
        session.send("Paré pour la QDJ?");
        builder.Prompts.choice(session, "Tu lis les nouvelles?", {
            "sur ton café électronique": 1,
            "en lisant une tartine ouverte à la bonne page": 2
        }, { listStyle: builder.ListStyle.auto });
    },
    function (session, results) {
        console.log("immediate response", results.response);
        session.send("tu as choisi : %s", results.response.entity);
        session.send("Merci d'avoir répondu!");
        session.endDialog();
    }
]).triggerAction({
    matches: /^qdj$/i
});
```

## Reproduction Steps
1. Launch the bot
2. start the `qdj`dialog by typing <kbd>qdj<kbd/>
3. Observe that the bot is not waiting for input after the choice.

## Expected Behavior

Have the bot pause until the user chooses.

## Actual Results

![issuechoice](https://user-images.githubusercontent.com/19834684/29751775-7305b4fc-8b52-11e7-82ba-a35b8bf5f2ab.png)

**Comment by stevengum97** [comment]
@Arpafaucon, I wasn't able to reproduce this using the dialog you provided. Is this `qdj` dialog being called from another dialog perhaps?

___
![issue3387](https://user-images.githubusercontent.com/14935595/29783339-e64b0638-8bd4-11e7-865a-2cf496295472.PNG)

**Comment by Arpafaucon** [comment]
It should have been, but both the normal flow and the triggerAction lead to this result. Below the js module after compilation: 
```javascript
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var builder = require("botbuilder");
var dev_1 = require("./dev");
/**
 * Configure le dialog de la qdj à proprement parler
 * @param {UniversalBot} bot
 * @returns {undefined}
 */
var configQdj = function (bot) {
    bot.dialog('qdj', [
        function (session) {
            dev_1.logDev(bot, 'new QDJ');
            session.send("Paré pour la QDJ?");
            builder.Prompts.choice(session, "Tu lis les nouvelles?", {
                "sur ton café électronique": 1,
                "en lisant une tartine ouverte à la bonne page": 2
            }, { listStyle: builder.ListStyle.auto });
        },
        function (session, results) {
            console.log("immediate response", results.response);
            session.send("tu as choisi : %s", results.response.entity);
            session.send("Merci d'avoir répondu!");
            session.endDialog();
        }
    ]).triggerAction({
        matches: /^qdj$/i
    });
};
exports.default = configQdj;
```
Please also find my `npm-shrinkwrap.json`, `package.json` and `tsconfig.json`: 
[bot.zip](https://github.com/Microsoft/BotBuilder/files/1258374/bot.zip)

Finally regarding the intended behaviour: the dialog should be called by a HeroCard PostBack action

**Comment by stevengum97** [comment]
@Arpafaucon you shouldn't begin a dialog and end a dialog in the same waterfall step. Can you try using the following instead and letting us know if it worked for you?

```js
function (session, results) {
  switch (results.response.entity) {
    case "QDJ":
      session.send("QDJ you said!");
      session.replaceDialog('qdj');
      break;
    case "RER":
      session.send("RER thats'it!");
      session.beginDialog('rer');
      break;
    case "whoami":
      session.send("Qui suis-je ? mmmh...");
      session.replaceDialog('whoami');
      break;
  }
}
```

**Comment by Arpafaucon** [comment]
My apologies, I notice today that the direct call through `triggerAction` works without being to describe what changed. As I didn't work on the project, I would suspect an error solvable by restarting the computer, **without being sure**.
However, **your suggestion solved the problem when calling from another dialog**, thanks!
