### ISSUE TITLE
Can I use different keysets(BotId, MicrosoftAppId, MicrosoftAppPassword) depending on url?

### ISSUE THREAD

**Issue by bestbykim** [Microsoft/BotBuilder#3388]
## Bot Info 
* Bot handle: 
* App ID: 
* SDK Platform: .NET
* SDK Version: 3.8.3
* Active Channels: 
* Deployment Environment: 

## Issue Description

I want to make some bot on one server.

Not use Web.config file, Can I use different keyset depending on url?
(BotId, MicrosoftAppId, MicrosoftAppPassword)

example )
/{code}/api/messages

depending on {code},
I want set key-value on bot framework.

## Reproduction Steps
1.
2.
3.

**Comment by nwhitmont** [comment]
@bestbykim No. It's not going to work.  You need to have a unique App ID + App password for each bot.
