### ISSUE TITLE
[Question] StartAsync is called before Scorable.. why?

### ISSUE THREAD

**Issue by ankitbko** [Microsoft/BotBuilder#3389]
I always believed that Scorable acts like a middleware. So logically, I thought it behaved like – 
> Incoming message -> List [Scorable]’s scoring logic -> winning Scorable.PostAsync

But it seems on first message, `RootDialog.StartAsync` is called before message is intercepted by Scorable (see screenshot below). So it behaves something like this – 
> Incoming message -> RootDialog.StartAsync -> List [Scorable]’s scoring logic -> winning Scorable.PostAsync
 
![image](https://user-images.githubusercontent.com/3169316/29762793-eb8929ae-8bed-11e7-9147-acd5930a4d3c.png)

My requirement is that user should be authenticated before interacting with bot. So it made sense to have a Scorable whose responsibility is to make sure user is authenticated by using AuthBot. It works pretty well in general if I don’t do anything in `RootDialog.StartAsync` method. But now I need to initialize some things in `RootDialog.StartAsync` which requires user’s access token and then I discovered this problem.

Why is it that the Dialog’s `StartAsync` is called before Scorable takes over? This breaks consistency as  `RootDialog.StartAsync` is called **before** Scorable scoring **only** on first message.

How do I achieve what I want? Basically I want to ensure that user is authenticated **before** message is passed to Dialog (including its `StartAsync` method).

**Comment by jorupp** [comment]
I've had good luck doing authentication in a dialog *before* passing control to my main dialog.  My auth dialog just completes immediately if the user is already authenticated, passing out the token to be used by the 'real' dialog.

**Comment by ankitbko** [comment]
@jorupp Ok, that is a good idea. But how do you check for token in every message? Once the control is passed to other dialogs, the auth dialog will not be called.

**Comment by jorupp** [comment]
@ankitbko - keep the token as a private instance variable in your dialog class - it'll get serialized along with the rest of the dialog state.  the bot framework automatically manages making sure users can't steal each other's state.

**Comment by ankitbko** [comment]
@jorupp Do you mean that I pass token to every dialog and check for its validity after every *wait*? I have quite a few dialog classes and many of them have nested conversation. It will distribute lot of `if (valid)` all over the place. I wanted to avoid this situation altogether, that is why I thought of putting all authentication/authorization part  in a `Scorable`.

Any suggestions?

**Comment by jorupp** [comment]
Oh, you're concerned the token may become invalid *during* a dialog conversation?  Oh... hmm... I don't think I'm actually handling that situation.  I just figured that dialogs would be short enough that I wouldn't need to re-auth part-way through.

**Comment by ankitbko** [comment]
Ya dialogs are small enough but user may reply after some time. So all the calls must be checked for tokens.

**Comment by ankitbko** [comment]
@nwhitmont Any update on this?

**Comment by goodoldgrim** [comment]
You can work around this by handling the authentication in the Post method of your controller.

**Comment by JasonSowers** [comment]
I'm assuming this was resolved.  Closing the issue, but reopen if you are still experiencing issues
