### ISSUE TITLE
Command translation problem 

### ISSUE THREAD

**Issue by placentiusz** [Microsoft/BotBuilder#339]
I added files Microsoft.Bot.Builder.pl.xlf and Resources.pl.resx
During The conversation bot displays messages in my language. But  sending a translated command not working.
Ex. (eng. Back -> pol. Powrót) Back - works fine. Powrót - don't work - is not a ... option.
(eng. Help -> pol. Pomoc) help - works - pomoc -don't work

**Comment by chrimc62** [comment]
Did you add the files using MAT?  If so, it should automatically add both files for you.  If you have translated the whole files they should work unless templates or semi-colons got messed up.  Semi-colons are use to separate each word in a list.  In your alternatives for the commands did you keep the semi-colons?  If that is the case, could you send me your .xlf file and I will take a look.

**Comment by placentiusz** [comment]
this is my test file, I translated only Help, back and quit .command
[Microsoft.Bot.Builder.pl.zip](https://github.com/Microsoft/BotBuilder/files/281020/Microsoft.Bot.Builder.pl.zip)

**Comment by chrimc62** [comment]
You did not translate the terms to match for the commands.  Look at the next entry in your .xlf file...
