### ISSUE TITLE
Active Learning

### ISSUE THREAD

**Issue by anirudhaditya** [Microsoft/BotBuilder#3390]
We are in the process of enabling Active Learning (https://qnamaker.ai/Documentation/ActiveLearning). As QnA maker is primarily a key word matching solution only as of date, we are making an attempt to provide active learning process which will allow users to have multiple options. 

One issue is that the default configuration of Active learning is 50 user clicks and I was trying to figure out if we can reduce that to 5 or 6. Have anyone tried this before or can provide me some suggestions.

Thanks
Aniruddha

**Comment by JasonSowers** [comment]
Please post this question in the [cognitive services repo](https://github.com/Microsoft/BotBuilder-CognitiveServices) as it specifically addresses the product you are using.  Closing this issue, but please feel free to continue the conversation here if you would like.
