### ISSUE TITLE
[Question] How to Detect Idle user?

### ISSUE THREAD

**Issue by anks333** [Microsoft/BotBuilder#3394]
Is there is any way to detect, if the user is idle for some period of time?

Node.js

**Comment by nwhitmont** [comment]
@anks333 What did you try so far? What worked? What didn't work?

**Comment by anks333** [comment]
@nwhitmont When my bot Prompts for some input from user, if user doesn't respond for some time then i want to send some message, for this I tried to use setInterval, on hitting the interval time i'm calling next() function explicitly but this doesn't work.

Please help me, if you have any way to do it

**Comment by stevengum97** [comment]
Closing this due to the fact that the base goal is to achieve the same functionality as seen in #3349.  (Duplicate)
