### ISSUE TITLE
[Feature Request] Add option to call loadSession() and not call session.dispatch()

### ISSUE THREAD

**Issue by microsoftly** [Microsoft/BotBuilder#3395]
## System Information
* SDK Langauge: Node.js
* SDK Version: latest

## Issue Description
```UniversalBot```'s ```loadSession``` always calls ```session.dispatch```. An alternative method should be available for cases where one needs to load session but not send it through middleware (e.g. loading session for tests)

**Comment by stevengum97** [comment]
Closing as this was merged.
