### ISSUE TITLE
[Skype for Business] Can not talk to bot on federated tenant?

### ISSUE THREAD

**Issue by stijnmichiels** [Microsoft/BotBuilder#3397]
## Issue Description
My bot is up and running on Skype for Business on my own Skype for Business Online tenant. Other users in my tenant can talk to the bot, but users on a federated domain don't get any reply (they don't get an error message either). The bot service gets hit though (according to app insights).
Federation works great for human to human conversations. 

In a federated Skype for Business conversation, is there a difference between being able to talk to a bot or a human?

## Expected Behavior
Have a user from another (federated) tenant converse with the bot, as if it were available in his own tenant.

## Actual Results
The bot does not reply, but not give me an error message either. Same behavior as talking to a federated user.

**Comment by nwhitmont** [comment]
@stijnmichiels For reference, are you using .NET or Node.js SDK for BotBuilder?

**Comment by stijnmichiels** [comment]
.NET

**Comment by shinykun** [comment]
hello any news? i still have this issue

**Comment by benbrown** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
