### ISSUE TITLE
Link markdown only works in MS Teams

### ISSUE THREAD

**Issue by santiagodoldan** [Microsoft/BotBuilder#3399]
## Bot Info 
* Bot handle: 
* App ID: 
* SDK Platform: Node.js
* SDK Version: 3.8.4
* Active Channels: MS Teams, Slack

## Issue Description
I'm using markdown like `[bing](http://bing.com)` to show a link without showing the whole url (which is very long), it looks like this only works ok in MS Teams, in Slack it appears the url, not the text `bing`.

I know I can use `<http://bing.com|bing>` to show links in Slack, but that won't work ok in MS Teams, isn't there a way to show links correctly in both clients?

## Code Example
`session.say("[bing](http://bing.com)")`

## Expected Behavior
In Slack

#=> [bing](http://bing.com)

In Teams

#=> [bing](http://bing.com)

## Actual Results
In Slack

#=> [http://bing.com](http://bing.com)

In Teams

#=> [bing](http://bing.com)

**Comment by JasonSowers** [comment]
For the slack channel please review their [message formatting documentation](https://get.slack.help/hc/en-us/articles/202288908-Format-your-messages)  it says the following:

- Though we understand many people would love to use Markdown in Slack messages, we have no plans to support it. Our message formatting is similar to other popular services and is intended for a majority of our users who are unfamiliar with Markdown. However, we'll keep it in mind for the future.

- **Note: Hyperlinking words and terms in a Slack message isn't supported — to include a URL, paste it into the message input box. Visit Share links in Slack for more**

**Comment by santiagodoldan** [comment]
Ok, thanks for the quick response.

This blog post https://blogs.msdn.microsoft.com/jamiedalton/2016/08/22/bot-framework-markdown-support-by-channel/ could be a bit confusing though, it says Slack supports markdown and the screenshot of slack shows the link correctly.

Thanks again 👍

**Comment by JasonSowers** [comment]
@santiagodoldan thanks for pointing this out, I'll have the docs team review. Good luck with your Bot(s)!

**Comment by JasonSowers** [comment]
I will try to get in contact with the blogger to correct this, thanks for pointing this out @santiagodoldan Good luck with your Bots!
