### ISSUE TITLE
Dialog with Dynamic Questions

### ISSUE THREAD

**Issue by pagebrooks** [Microsoft/BotBuilder#34]
What guidance can you offer to support database driven dialogs? Based on user input in the dialog, I would like to query a database (or external service) as an intermediate step in the dialog. None of the documentation mentions this, but it seems like it would be a common scenario. For example, the sandwich choices in the sandwich bot sample would most certainly be driven by an external dependency in the real-world.

**Comment by Stevenic** [comment]
@pagebrooks are you asking in regards to the c# or node version of the library? They work a little differently so there would be different answers, I'm assuming you're asking about the C# version of the library given that you referenced the sandwich bot sample. I'm on the node side of things but I don't think the C# version of the form builder supports dynamic values yet. I believe this is something they're investigating.

**Comment by pagebrooks** [comment]
@Stevenic Thanks for your answer. Yes, I was referring to the C# version.

**Comment by chrimc62** [comment]
You can define fields dynamically using the C# Bot Builder.  There are a couple of options:

1)      You can instantiate FieldReflector<T> on a path to a property or field in your C# class and then use the fluent interface to dynamically define values, terms, descriptions, etc.  (Which could come from your database.)

2)      You can derive a class from Field<T> that adds implementation for IFieldState<T>.  (This is the underlying class that supports the fluent declaration of terms, descriptions, etc.)

3)      You can implement IField<T> yourself.
We just haven’t had time to do some good samples in that area yet.  (If you have one to contribute, that would be great!)

**Comment by Stevenic** [comment]
Thanks @chrimc62
