### ISSUE TITLE
Facebook channel vs Emulator?

### ISSUE THREAD

**Issue by tkbox9** [Microsoft/BotBuilder#340]
Hi. 

At first everything worked on both channels (Facebook and Emulator) then after few deploys things were just out of sync. I came up with a very simple scenario to test my assumption. 

I've created an intent called Greetings and every time the user says Hello. It should respond Greetings. Pretty simple and straightforward. Well, from emulator it works (also when I point it to my public end point).

However, from FB I just receive "Bot is having a problem responding right now".  Is there any way to debug or what's the recommended practices in those cases? My AppId: ChatRobot

Many thanks.

**Comment by DavePilks** [comment]
What I have noticed is that FB bots tend to get stuck in an error state. You would have to delete the profile on the bot to reset the `StateData`.  Others have had to recreate the FB page/app combo claiming that the former didnt help.

The devs say that recreating is overkill but that is up to you.

**Comment by tkbox9** [comment]
@DavePilks exactly. Every time I have to re-create page/app. It's really an overkill. @willportnoy is that a known bug? Any suggestions other than recreating the whole thing?

**Comment by msft-shahins** [comment]
@tkbox9 @DavePilks you see the behavior because bot builder persists the dialog stack in the `message.BotPerUserInConversationData`. When there is a code change, you should make sure that your bot is starting from an empty state or you implement the code to do the data migration for you. 

To start from an empty dialog stack, you can send `/deleteprofile` to clear out the user related data and clear out the call stack. Also in your message controller, you can implement the logic to clear out the `BotPerUserInConversationData` based on a bot version you persist in the `BotPerUserInConversationData`.

**Comment by msft-shahins** [comment]
Here is a basic sample code to clear out the dialog stack when bot version changes. 

```csharp
    [BotAuthentication]
    public class MessagesController : ApiController
    {
        /// <summary>
        /// POST: api/Messages
        /// receive a message from a user and reply to it
        /// </summary>
        public async Task<Message> Post([FromBody]Message message)
        {
            string currentBotVersion = "1.0";
            string botVersionKey = "BotVersion";

            using (var scope = DialogModule.BeginLifetimeScope(Conversation.Container, message))
            {
                var botData = scope.Resolve<IBotData>();

                string version = string.Empty;
                if (botData.PerUserInConversationData.TryGetValue(botVersionKey, out version))
                {
                    // remove the dialog stack data if version is different
                    // data migrations can happen here.
                    if (version != currentBotVersion)
                    {
                        botData.PerUserInConversationData.RemoveValue(DialogModule.BlobKey);
                        botData.PerUserInConversationData.SetValue(botVersionKey, currentBotVersion);
                    }
                }
                else
                {
                    botData.PerUserInConversationData.SetValue(botVersionKey, currentBotVersion);
                }
            }

            return await Conversation.SendAsync(message, () => EchoChainDialog.dialog);
        }
    }
```

**Comment by tkbox9** [comment]
@msft-shahins Did a test and it worked. 

Many thanks.
