### ISSUE TITLE
[Feature Request] Support for Twilio Copilot

### ISSUE THREAD

**Issue by rrrodzilla** [Microsoft/BotBuilder#3400]
## Bot Info 
* Bot handle: 
* App ID: 
* SDK Platform: Node.js
* SDK Version: Latest on Azure
* Active Channels: Twilio
* Deployment Environment: Azure Bot Service

## Issue Description
Setting up the Twilio channel requires a Twilio phone number, Account SID and Secret.  This means that all messages go to/from the assigned Twilio phone number.  Since local numbers deliver at 1Message Per Second (MPS) and toll free numbers deliver at 3MPS (but no support for MMS) the bot will not scale.  Twilio has a service called Copilot which handles scaling messaging across many numbers, the only difference to send messages between a single number and the Copilot service is to make API requests with the Account SID, Secret and an Copilot SID instead of a phone number, then Copilot will handle picking the best number for your inventory to deliver messages from for the best performance.  Currently in the Azure Bot Service I can only enable the channel by entering a phone number, Account SID and Secret.  Is there any way I can override that configuration to use a SID instead of a phone number, leaving the Account SID and Secret unchanged?  This would really enable scalability for my bot.

Thanks for any guidance any of you can provide.

**Comment by nwhitmont** [comment]
https://www.twilio.com/copilot

**Comment by nwhitmont** [comment]
@rrrodzilla Thanks for the suggestion! We will add this to our backlog of Feature Requests.

**Comment by rrrodzilla** [comment]
Thanks much.  Are there any workarounds for this? We've got a product we're trying to get to market quickly and can't even use a shortcode which is required to scale messaging over the SMS channel.

**Comment by benbrown** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
