### ISSUE TITLE
[Bug] Skype > Calling > Real-Time Media > Cannot save "enable video" config settings in Bot Portal

### ISSUE THREAD

**Issue by robmeadows** [Microsoft/BotBuilder#3401]
## Bot Info 
* Bot handle: 
* App ID: c8b888e9-c32f-4ac1-ae92-ff5dc9e257fe
* SDK Platform:  .NET
* SDK Version:  
* Active Channels:  Slack
* Deployment Environment:  Azure Cloud Classic

## Issue Description
Cannot enable Video on Skype Real Time Media bot.

## Reproduction Steps
1. Go to Channels -> Edit Skype -> Calling
2. Click to enable Video under Real Time Media
3. Save
4. Click to Analytics, then back to the Calling configuration and notice Video is not checked anymore

## Expected Behavior
Video should be enabled

## Actual Results
When calling the Huebot example, it says Call - error for an audio call, and a video call is not enabled.

**Comment by EricDahlvang** [comment]
These are the checkboxes that do not appear checked after refreshing:

![image](https://user-images.githubusercontent.com/11055362/29946587-cb430bc8-8e5a-11e7-828d-2aa732e3f76f.png)

**Comment by nwhitmont** [comment]
Confirmed, this is a bug.

**Comment by robmeadows** [comment]
As a workaround, I was able to enable video by manually doing a POST to https://dev.botframework.com/api/bots/xxxxx/channels/skype?publishing=false
with the json parameter "enableVideo":"True". The portal is posting it as "false" regardless of whether the Video box is checked or not.

**Comment by fanidamj** [comment]
Closing the issue assuming it as resolved. Please reopen a new issue if it still persists.
