### ISSUE TITLE
[MS Teams] How to configure Card action buttons in O365ConnectorCard to send reply to bot?

### ISSUE THREAD

**Issue by gomteshhatgine** [Microsoft/BotBuilder#3402]
## Bot Info 

* SDK Platform:  .NET 
* SDK Version: 
* Active Channels: 

## Issue Description
I have used "Microsoft.Bot.Connector.Teams.Shared" project to send O365ConnectorCard in MS teams but I not able to send card action button like  **invoke, imBack, messageBack**
.

## Expected Behavior
I want to implement card action buttons in O365ConnectorCard
as mentioned in [https://msdn.microsoft.com/en-us/microsoft-teams/botsmessages#buttons](url)
because I want get reply to my Bot api endpoint using **invoke** card action buttons like **messageBack, invoke etc**

As in attached code when user insert comment and click on button it should send to bot API endpoint like  **invoke, imBack, messageBack**

## Code
[code.txt](https://github.com/Microsoft/BotBuilder/files/1266401/code.txt)

**Comment by JasonSowers** [comment]
Closing as the conversation has been taking place [here](https://github.com/Microsoft/BotBuilder-Samples/issues/177)  and this is not currently a feature in teams, but will be soon.
