### ISSUE TITLE
[Question] Exception messages being sent to the user by Bot Framework before my error handler can act?

### ISSUE THREAD

**Issue by MarkHirst** [Microsoft/BotBuilder#3404]
## Bot Info 
* SDK Platform: .NET 
* SDK Version: 3.9
* Active Channels: Skype for Business, MS Teams, Web, Emulator, Cortana
* Deployment Environment: Azure Bot Service

## Issue Description
In a number of circumstances where an exception occurs, I have code designed to handle those exceptions with the intention of reporting something meaningful and friendly to the user.

Despite the exception handler trapping the error, and so allowing me to report a message to the user, the framework has already sent back the internal error messages directly at the user, meaning that they see what are quite cryptic errors followed by mine.

A specific example (among others) is FormFlow, where the user decides to use QUIT to end the filling of the form. I have an error handler that handles the form quit exception raised by the framework, where I want to tell them that the process has been cancelled. This handler reports to user correctly, but not before the scary internal error has been sent to the user - and of course that's the one they remember !

## Expected Behavior
That I get to handle the error in my code, so I can send a message of my choosing to user, rather than the internal error being sent straight to the user and showing up in the channel interface.

**Comment by JasonSowers** [comment]
@MarkHirst  please see #1136

**Comment by MarkHirst** [comment]
@JasonSowers I did see that code but was having trouble resolving the code so it would compile - thought perhaps it was old code and the framework had changed - I'll take another look - thanks.
