### ISSUE TITLE
[Question] Issue in saving data to ConversationData?

### ISSUE THREAD

**Issue by kunalkamboj** [Microsoft/BotBuilder#3405]
I am building a bot an was trying to save the current conversation history in the CoversationData object but I am getting 412 errors along. I am trying to handle the 412 error as mentioned here: https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-state. but no use.
I am doing the same in IActivityLogger implementation.

can you please take a look the attached code: core- middleware and suggest a fix.

[core-Middleware.zip](https://github.com/Microsoft/BotBuilder/files/1266742/core-Middleware.zip)

**Comment by EricDahlvang** [comment]
Hi @kunalkamboj 

Please share the code you are using to update ConversationData.

Also, there is some discussion about 412 errors in the Bot Builder FAQ that might be helpful for your situation: what-causes-an-error-with-http-status-code-412-precondition-failed-or-http-status-code-409-conflict

**Comment by kunalkamboj** [comment]
Hi @EricDahlvang,

Thanks for the response. I have posted the whole solution in the zip file attached above.
`namespace MiddlewareBot
{
    using System.Diagnostics;
    using System.Threading.Tasks;
    using Microsoft.Bot.Builder.History;
    using Microsoft.Bot.Connector;
    using Microsoft.Bot.Builder.Dialogs.Internals;
    using System.Collections.Generic;
    using Microsoft.Rest;

#pragma warning disable 1998

    public class DebugActivityLogger : IActivityLogger
    {
        private IBotData _botdata;
        public DebugActivityLogger(IBotData botdata)
        {
            _botdata = botdata;
        }
        public async Task LogAsync(IActivity activity)
        {
            try
            {
                var message = activity.AsMessageActivity();
                StateClient stateClient = activity.GetStateClient();
                var botdata = stateClient.BotState.GetConversationData(message.ChannelId, message.Conversation.Id);
                var history = botdata.GetProperty<List<string>>("history");
                if (history == null)
                {
                    history = new List<string>();
                }

                history.Add($"From: {message.From.Name}, Message: {message.Text}");
                botdata.SetProperty<List<string>>("history", history);
                await stateClient.BotState.SetConversationDataAsync(message.ChannelId, message.Conversation.Id, botdata);
            }
            catch (HttpOperationException err)
            {
                throw;
            }
            catch (System.Exception ex)
            {

                throw;
            }
            
        }
    }
}
    `

Pasted a wrong URL above. updating the actual..
https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-state

**Comment by EricDahlvang** [comment]
Interesting idea: to save history in ConversationData.  However, activity.GetStateClient() will retrieve the default state client.  The default state client is meant only for prototyping.  Please see this blog post that explains how to use the Azure Extensions for state: https://blog.botframework.com/2017/07/18/saving-state-azure-extensions/ 

I believe what is happening here is that the state is persisted by your activity logger implementation, then re-saved by the dialog.  I believe the order is 1) the message comes in and Bot Builder loads the state data bags into memory to process the message 2) your IActivityLogger loads the state, and saves it (i.e. SetConversationDataAsync) 3) message is processed by the dialog, and the state data bags are saved afterwards -- which results in a conflict.

The simplest resolution is to save your history list in a different store.  (Also, please use the Azure Extensions mentioned earlier, or implement a custom IBotDataStore<BotData>)

**Comment by kunalkamboj** [comment]
Hi Eric, Thanks for the response, the shared link would be certainly helpful, although I wanted to remove the overhead of making calls to external service as I am not intending to use that persisted data. 

I changed the above code to store data in  UserData that seems to be working fine.

stateClient.BotState.**GetUserData**(message.ChannelId, **message.Conversation.Id**);

I am sure this is a workaround as UserData should not be used to store the conversation data, but am still not clear why userdata works and conversationdata does not.

**Comment by EricDahlvang** [comment]
I'm glad you've found a working solution.  

Note, the default state client is not intended for production bots.  Please use one of the Azure Extensions or implement a custom IBotDataStore.  Here is a blog post describing how to use the Azure Extensions: https://blog.botframework.com/2017/07/18/saving-state-azure-extensions/
