### ISSUE TITLE
[.NET SDK] Error: Invalid Cast Exception while casting "builtin.datetimeV2.daterange" type to Newtonsoft.Json.Linq.JArray after upgrading to Bot Builder 3.9. 

### ISSUE THREAD

**Issue by ManishChitre** [Microsoft/BotBuilder#3406]
* SDK Platform: .NET 
* SDK Version: 3.9
* Active Channels: Web Chat, DirectLine;
* Deployment Environment: Azure App Service

## Issue Description
Exception is raised during runtime whenever I try to cast "Resolution.Values" in "builtin.datetimeV2.daterange" type to Newtonsoft.Json.Linq.JArray after upgrading to Bot Builder 3.9.

## Code Example
           
```C#
//Getting all the entities of type builtin.datetimeV2.daterange into list.
      
var years = result.Entities.Where(x => x.Type.Equals("builtin.datetimeV2.daterange"));

            foreach (var year in years)
            {
                 foreach (var vals in year.Resolution.Values)
                 {
                    //Exception is raised when I try to cast vals to JArray.
                          if (((JArray)vals).First.SelectToken("type").ToString() == "daterange")
                           {
                            _startYear = (DateTime)((JArray)vals).First.SelectToken("start");
                            _endYear = (DateTime)((JArray)vals).First.SelectToken("end");
                            }
                  //custom logic ....
                  }
         }
```
JSON

``` json
"entities": [
    {
      "entity": "attrition",
      "type": "attrition",
      "startIndex": 0,
      "endIndex": 8,
      "score": 0.74733305
    },
    {
      "entity": "this year",
      "type": "builtin.datetimeV2.daterange",
      "startIndex": 14,
      "endIndex": 22,
      "resolution": {
        "values": [
          {
            "timex": "2017",
            "type": "daterange",
            "start": "2017-01-01",
            "end": "2018-01-01"
          }
        ]
      }
    }
  ]
```

## Reproduction Steps
1. Getting all the entities of type builtin.datetimeV2.daterange into years list.
2. Iterating over each year in years list and getting the JArray Object from "year.Resolution.Values".
3. Exception is raised when I am casting each "year.Resolution.Values" type to Newtonsoft.Json.Linq.JArray.

## Expected Behavior
I need to get _startYear and _endYear values from "year.Resolution.Values" which contains list of JArray Objects in the form of <key,value> pair.

## Actual Results
Invalid cast exception is raised when casting "EntityRecommendation.Resolution.Values" After upgrading to BotBuilder 3.9 .However, there were no issues when I was using BotBuilder 3.8.5.

Is there any way to read **start** and **end** values without casting it to Newtonsoft.Json.Linq.JArray type?

**Comment by JasonSowers** [comment]
Are you able to cast to `JObject` in lieu of `JArray`?

**Comment by ManishChitre** [comment]
@JasonSowers - It still throws Invalid Cast Exception when I tried casting to ```JObject``` too. Json posted in the post is not the actual json response but a part of it. The problem is with the "values" under "Resolution" key.

**Comment by stevengum97** [comment]
At the risk of sounding stupid, you tried 
```cs
(((JObject)vals).SelectToken("type").ToString() == "daterange")
``` 

and not the following, right?
```cs
(((JObject)vals).First.SelectToken("type").ToString() == "daterange")
```

**Comment by JasonSowers** [comment]
Are you able to post your complete code to a repo so we can take a look?

**Comment by JasonSowers** [comment]
Did you ever resolve this?

**Comment by anuxps** [comment]
I am also getting the same error. Any solution for that.

**Comment by anuxps** [comment]
I got the alternate solution by converting JSON value to C# Class Properties and Deserialize using JSONConverter Class.

**Comment by JasonSowers** [comment]
Would you mind posting an example of your workaround for others?

**Comment by anuxps** [comment]
Here is the example code. Please follow the below mentioned steps:

**1) Create a Class File with following structure. You can modify the structure based on JSON value. Similarly might be you have to create a class for TimeRange.**


 
using System.Collections.Generic;

namespace BotXYZ
{
    public class CustomDateRange
    {
        public string timex { get; set; }
        public string type { get; set; }
        public string start { get; set; }
        public string end { get; set; }
    }

    public class RootObject
    {
        public List<CustomDateRange> values { get; set; }
    }
}

 

**2) Place the code in RootDialog.cs as per below:**

 
							if (entity.Type == "builtin.datetimeV2.daterange")
                            {
                                object jsonobject;
                                entity.Resolution.TryGetValue("values", out jsonobject);

                                string jsonstringvalue=  JsonConvert.SerializeObject(jsonobject);

                                List<CustomDateRange> lstDateRangeObj = (List<CustomDateRange>)Newtonsoft.Json.JsonConvert.DeserializeObject(jsonstringvalue, typeof(List<CustomDateRange>));

                                foreach (CustomDateRange objCustomDateRange in lstDateRangeObj)
                                {
                                    if (objCustomDateRange.start != null)
                                    {
                                        var start = objCustomDateRange.start;
                                    }

                                    if (objCustomDateRange.end != null)
                                    {
                                        var end = objCustomDateRange.end;
                                    }

                                    if (objCustomDateRange.timex != null)
                                    {
                                        var timex = objCustomDateRange.timex;
                                    }
                                }
                                
                            }

**Comment by fanidamj** [comment]
Hoping that issue has been resolved, closing it. Feel free to reopen if any questions.
