### ISSUE TITLE
[Question] How to Open Google Map application for navigating on Bot by URL button?

### ISSUE THREAD

**Issue by binhpht** [Microsoft/BotBuilder#3407]
## Issue Description
* SDK Platform: Node JS 
Hi, as a title mentioned, I am finding the solution for referring Map Application on mobile to navigate . Does anyone have experience about this
Thanks.

**Comment by JasonSowers** [comment]
Can you please fill out the template so we can better assist you

**Comment by nwhitmont** [comment]
@binhpht Are you using .NET or Node.js SDK? What did you try? What worked? What didn't work?

Please post your code.

**Comment by binhpht** [comment]
@nwhitmont  @JasonSowers  I am sorry because my question dont have enough information.  Im creating a function for bot to search closest  certain locations from current point. For example, if users communicate with the bot via facebook, the bot will send the name of closest shop. Now I use the bing map for gererating route map image. And I just want to add more button to open the map in message.  So I post this topic for asking

**Comment by JasonSowers** [comment]
Thanks for responding.  Are you using the Node or .NET SDK?

**Comment by binhpht** [comment]
@JasonSowers  Im using Node JS. I will it, thanks

**Comment by JasonSowers** [comment]
the suggestion I made was for .NET.  In the documentation, I linked you can view the node equivalent Via the dropdown near the top of the page

**Comment by JasonSowers** [comment]
Did you resolve this?

**Comment by binhpht** [comment]
@JasonSowers  not yet, I didnto found any template for open Google Map for the bot, so Im sill strungging.

**Comment by sphanley** [comment]
There's really nothing bot-specific about this question. You just need to build a Google Maps directions URL for the location you want to navigate to, per the documentation at [Google's documentation](https://developers.google.com/maps/documentation/urls/guide#directions-action), and then set that as the URL that your button will launch.

**Comment by christoslts** [comment]
I have one relevant question in c# microsoft bot framework about how can i import google maps and  get the closest shops using store procedure  that has as parameters latitude and longitude and finally the user when type their coordinates the map will be appear..
