### ISSUE TITLE
[Direct Line] Random 401 responses from skype.botframework.com when sending proactive messages?

### ISSUE THREAD

**Issue by yonahforst** [Microsoft/BotBuilder#3409]
## Bot Info
* Bot handle: Abi
* App ID: 9632ca53-7319-4b65-bf05-3ed84b9824cd
* SDK Platform: n/a
* SDK Version: n/a
* Active Channels: skype
* Deployment Environment: AWS Lambda

## Issue Description
Using the rest API, I randomly get 401 errors when trying to [send a (non-reply) message](https://docs.microsoft.com/en-us/bot-framework/rest-api/bot-framework-rest-connector-send-and-receive-messages#send-message).

It seems to happen when more than 1 hour has passed since my last communication with the user. Is there some sort of time limit to replying (or sending a non-reply message) to a user?

## Code Example

n/a
## Reproduction Steps
BaseUrl: `skype.botframework.com`
1. user sends message to the bot.
2. bot waits one hour+, then starts a conversation (`POST /v3/conversations`)
3. bot sends a non-reply message to that conversation (`POST /v3/conversations/{conversationId}/activities`)

## Expected Behavior

200/201 response from the server

## Actual Results

```
{  "statusCode": 401,
  "statusMessage": "Unauthorized",
  "headers": {
    "content-length": "61",
    "content-type": "application/json; charset=utf-8",
    "server": "Microsoft-HTTPAPI/2.0",
    "date": "Fri, 01 Sep 2017 10:15:07 GMT",
    "connection": "close"
  },
  "body": "{\"message\":\"Authorization has been denied for this request.\"}"
}
```

**Comment by JasonSowers** [comment]
Do you have a valid certificate?

The Bot Framework works with bots deployed on any cloud hosting service, as long as you have an internet-accessible endpoint and a valid SSL certificate.
The Bot Framework requires that the x.509v3 certificate exposed by your endpoint be current and valid. Most of the checks for "current and valid" are standard checks for server SSL certificates: the Certificate Name must match the hostname, it must not be expired, it must not be listed in a CRL, it must have the correct set of EKUs, etc.
Most importantly, your SSL certificate must chain to a root certificate authority trusted by Microsoft. The latest list of these CAs is available here: http://social.technet.microsoft.com/wiki/contents/articles/31634.microsoft-trusted-root-certificate-program-participants-v-2016-april.aspx

**Comment by yonahforst** [comment]
@JasonSowers - yes, the webhook url has valid certificate. But I don't think that's the issue since it happens on outbound requests and only under certain conditions.

**Comment by JasonSowers** [comment]
IIRC from my experience with building Alexa skills on Lambda, after a given amount of time (I think it's an hour)  your function goes to sleep.  This used to cause the first requests to my Alexa skill to fail or take a long time on the first request.  I'm not saying this is the case for sure, but it could be something to look into.
