### ISSUE TITLE
.NET 4.5

### ISSUE THREAD

**Issue by wiltodelta** [Microsoft/BotBuilder#341]
We use Azure CloudServices and GuestOS doesn't support .NET 4.6 for now.
After version 1.1.0.0 you drop support of .NET 4.5. Why? Do you have plans to support .NET 4.5?

**Comment by wiltodelta** [comment]
In Microsoft.Bot.Builder project I changed target framework to 4.5 and built -- success.

**Comment by chrimc62** [comment]
You are right that GuestOS does not include 4.6, but you can use it as described here: https://azure.microsoft.com/en-us/documentation/articles/cloud-services-dotnet-install-dotnet/
It does kind of suck that you need to do this manual step, but it is necessary if you want to support multiple cultures reliably.  I'll look into what we could do to support 4.5, but I seem to remember it was a lot of work for a partial solution.  

You can build the library, but if you handle multiple cultures it will work--most of the time, but not all.   Until .Net 4.6 thread culture was not a part of the context so when you used async the thread culture would change.  

From MSDN documentation https://msdn.microsoft.com/library/system.globalization.cultureinfo.aspx

For apps the target the .NET Framework 4.6 or later versions, culture is part of an asynchronous operation's context. In other words, starting with apps the target the .NET Framework 4.6, asynchronous operations by default inherit the values of the CurrentCulture and CurrentUICulture properties of the thread from which they are launched. If the current culture or current UI culture differs from the system culture, the current culture crosses thread boundaries and becomes the current culture of the thread pool thread that is executing an asynchronous operation.

**Comment by chrimc62** [comment]
Looks like Azure Web Sites and Functions do support 4.6, so the best solution is to either switch to them or to upgrade your OS as outlined above.

**Comment by wiltodelta** [comment]
@chrimc62 good explanation, thanks!

I tried to install .NET 4.6.1 to Azure CloudService GuestOS, it works, but is too slow if your need scale your instances quickly. Azure Web Sites and Functions don't suit for our deploy case.

I'll build a Microsoft.Bot.Builder for .NET 4.5 by myself, while we use only one language (English) for our bot.
