### ISSUE TITLE
[Question] Best practices for unit testing Dialogs in .NET SDK?

### ISSUE THREAD

**Issue by AvishagCs** [Microsoft/BotBuilder#3415]
Hi.
I have a RootDialog which is invokes when the user sends first message.
The RootDialog invokes another dialog named: NameResolutionDialog, which presents a question to the user and then according to the user answer, returns a Contact object (I've created that object) to the RootDialog.

I want to write uni tests for my bot. Can you please explain me how should I start? 
I've looked at : https://github.com/Microsoft/BotBuilder/tree/master/CSharp/Tests
and couldn't really unserstand how should I start..

Do I need to test each dialog separately or should I test them together on each optional flow?
Thanks.

**Comment by nwhitmont** [comment]
See answer here: https://stackoverflow.com/questions/42925624/how-to-unit-test-a-microsoft-bot-dialog-with-a-prompt

**Comment by AvishagCs** [comment]
Which package do I need to import to be able to inherit from DialogBaseTest?

**Comment by EricDahlvang** [comment]
@AvishagCs DialogBaseTest can be found here: https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Tests/Microsoft.Bot.Builder.Tests/DialogTestBase.cs

**Comment by JasonSowers** [comment]
duplicate of https://stackoverflow.com/questions/46058866/how-to-inherit-from-dialogtestbase-for-uni-testing-rootdialog

**Comment by barakyo** [comment]
What's the best way to inherit DialogTestBase? I tried the simple way of just copying the file into my project, but then I needed to copy in a number of other files (FiberTests, etc) which I wasn't able to build. Is there a better way than copying the class into a project and its dependencies?

**Comment by jakubkaczmarek** [comment]
I've developed an easy-to-use bot dialogs unit testing library - it's described here:
https://jakubcodes.wordpress.com/2018/01/24/bot-dialogs-unit-testing-using-stories-concept
Source code available on github:
https://github.com/ObjectivityLtd/Bot.Tests.Stories.Xunit

**Comment by WillRock19** [comment]
@EricDahlvang please, how can I use the DialogBaseTest  in my project? The Microsoft.Bot.Builder.Tests namespace is not avaiable doesn`t metter how I call it. I need some specific nuget package to use it, or just the Microsoft.Bot.Builder itself?

**Comment by WillRock19** [comment]
@EricDahlvang please, how can I use the DialogBaseTest  in my project? The Microsoft.Bot.Builder.Tests namespace is not avaiable doesn`t metter how I call it. I need some specific nuget package to use it, or just the Microsoft.Bot.Builder itself?

![image](https://user-images.githubusercontent.com/6953687/40735390-7837fbb8-6411-11e8-995e-6b910a89b74c.png)

**Comment by EricDahlvang** [comment]
@WillRock19 Currently, you would need to download the repo and reference the project in your solution.
