### ISSUE TITLE
[Question] Common DI technique relies on internal package?

### ISSUE THREAD

**Issue by tiloc** [Microsoft/BotBuilder#3416]
## Bot Info 
* SDK Platform: .NET
* SDK Version: 3.9

## Issue Description
In bots which register services through AutoFac, it is common practice to mark these services as being not serializable. This is done through the FiberModule.Key_DoNotSerialize key. This key is buried deep in a package called "Microsoft.Bot.Builder.Internals.Fibers". The word "Internals" indicates to me that as a 3rd party I should not use anything contained therein. I am not aware of an alternative technique which would not rely on an internal package.

## Code Example
**using Microsoft.Bot.Builder.Internals.Fibers;**

            // Service dependencies
            builder.RegisterType<Services.InMemoryOrdersService>()
                .Keyed<Services.IOrdersService>(**FiberModule.Key_DoNotSerialize**)
                .AsImplementedInterfaces()
                .SingleInstance();

## Expected Behavior
I can use a key or technique with no reliance on an Internal package.

## Actual Results
I have to use an internal package.

**Comment by oflahero** [comment]
:) I remember stumbling on this 'Fibers' business not long after I started working with BotFramework. There's no specific documentation on it - you basically have to accept it as a given. I asked a [question on SO](https://stackoverflow.com/questions/41747379/what-exactly-is-microsoft-bot-builder-internals-fibers-used-for) - Ezequiel is a great guy for helping with bot-related matters, but even his reaction was 'why would you even ask such a thing'. So you're not alone, I'm still none the wiser.

**Comment by EricDahlvang** [comment]
Although the naming of the package contains the word 'Internals', using Key_DoNotSerialize is the recommended practice: https://docs.microsoft.com/en-us/bot-framework/troubleshoot-general-problems#how-can-i-reference-non-serializable-services-from-my-c-dialogs

**Comment by tiloc** [comment]
I am still thinking that the bits and pieces which are required for bot developers and are thus part of your public API should not live in a package called "internals". There are several more such pieces, e.g. DialogModule. How will I know where Microsoft sees the delineation line between their internal soup that they will refactor at liberty and not keep stable, versus the things which are part of the public API and will have proper API handling (get flagged as Obsolete rather than removed)? Usually I look for hints such as classes being marked "internal" or packages being called "Internal" and stay away from those. Going forward I will also have to rationalize this during code reviews of my bot. I think it would still be highly desirable to have some kind of a "Microsoft.Bot.AutoFac" package which contains the AutoFac-related APIs for 3rd party developers.

**Comment by EricDahlvang** [comment]
@tiloc Thanks for your feedback.  I agree that it is confusing, and not intuitive, for developers to be required to use an assembly that is labeled 'Internals'.  

Please note that the **Microsoft Bot Builder** is currently in a preview state.

Also, there is in fact a Microsoft.Bot.Builder.Autofac project here: https://github.com/Microsoft/BotBuilder/tree/fdb443a3257dd62e2bd87727afdea793820a2ec7/CSharp/Library/Microsoft.Bot.Builder.Autofac
