### ISSUE TITLE
[Question] Why am I getting "[500] Internal Server Error" after deploying my bot to server?

### ISSUE THREAD

**Issue by verdysh** [Microsoft/BotBuilder#3418]
* Bot handle: valerchik
* App ID: 2d4718ca-cae4-4d17-8a20-a459ec56ad4e
* SDK Platform: .NET
* SDK Version: 
* Active Channels: Skype, Web Chat
* Deployment Environment: ngrok

## Issue Description
Hi! I was create a bot with VisualStudio 2017 template. It's work good: I send/retrieve messages through emulator.

I was publish bot to web server. When I try send message (through skype, web chat or emulator with ngrok), i get an error 500. On dev portal message is "There was an error sending this message to your bot: HTTP status code InternalServerError", in emulator message is "-> POST Request to 'https://.../api/messages' failed: [500] Internal Server Error "

## Expected Behavior
In Web.config I fill MicrosoftAppId and MicrosoftAppPassword. There is extra setting BotId, but I don't know what is that.

## Actual Results
Please, tell me what else I can do or where to look?

PS. Sorry for my bad english

**Comment by nwhitmont** [comment]
@verdysh Where is your bot hosted? Does your server have a valid SSL certificate?

**Comment by verdysh** [comment]
@nwhitmont, bot hosted on own server with Windows Server 2012 R2 which has access from the outside.

When I published the bot, I decided to cheat. Since it was required to specify a link with https (and I do not really understand the settings of ssl), I asked the system administrator to make the entry point available to the address that starts with http. I.e. entry point there were http://my-server:1234/bot-name/apimessages, became http**s**://my-server:1234/bot-name/apimessages. It will not work?

By the way, if my function just returns http status:

```
public async Task<HttpResponseMessage> Post([FromBody]Activity activity)
{
	return Request.CreateResponse(HttpStatusCode.OK);
}
```

there are no errors 500. But as soon as I add the bot answer:

```
[BotAuthentication]
public class MessagesController : ApiController
{

	public async Task<HttpResponseMessage> Post([FromBody]Activity activity)
	{
		if (activity.Type == ActivityTypes.Message)
		{
			await Conversation.SendAsync(activity, () => new Dialogs.RootDialog());
		}

		else
		{
			HandleSystemMessage(activity);
		}

		var response = Request.CreateResponse(HttpStatusCode.OK);
		return response;
	   
	}

	private Activity HandleSystemMessage(Activity message)
	{
		if (message.Type == ActivityTypes.DeleteUserData)
		{
			// Implement user deletion here
			// If we handle user deletion, return a real message
		}
		else if (message.Type == ActivityTypes.ConversationUpdate)
		{
			// Handle conversation state changes, like members being added and removed
			// Use Activity.MembersAdded and Activity.MembersRemoved and Activity.Action for info
			// Not available in all channels
		}
		else if (message.Type == ActivityTypes.ContactRelationUpdate)
		{
			// Handle add/remove from contact lists
			// Activity.From + Activity.Action represent what happened
		}
		else if (message.Type == ActivityTypes.Typing)
		{
			// Handle knowing tha the user is typing
		}
		else if (message.Type == ActivityTypes.Ping)
		{
		}

		return null;
	}
}

[Serializable]
public class RootDialog : IDialog<object>
{
	public Task StartAsync(IDialogContext context)
	{
		context.Wait(MessageReceivedAsync);
		return Task.CompletedTask;
	}

	private async Task MessageReceivedAsync(IDialogContext context, IAwaitable<object> result)
	{
		var activity = await result as Activity;
		int length = (activity.Text ?? string.Empty).Length;
		await context.PostAsync($"You sent {activity.Text} which was {length} characters");
		context.Wait(MessageReceivedAsync);
	}
}
```
error occurs :( . In the emulator, the full log looks like this:

> [08:29:06] -> POST 200 [conversationUpdate] 
> [08:29:06] -> POST 200 [conversationUpdate] 
> [08:29:07] -> POST Request to 'https://my-server:1234/my-bot/api/messages' failed: [500] Internal Server Error

**Comment by JasonSowers** [comment]
are you able to post your complete code.  from what you are showing, there should be no errors

**Comment by verdysh** [comment]
In [next topic](https://github.com/Microsoft/BotBuilder/issues/3422) I gave a link to the [project](http://www17.zippyshare.com/v/YvIU3bR6/file.html). This is a completely different project (made from a [sample](https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/core-MultiDialogs)). With him, the same trouble :( .

Probably you are right about a valid certificate. I will think something in this direction. 

Thanks for the answer!

**Comment by JasonSowers** [comment]
you're welcome, good luck.
