### ISSUE TITLE
Do not work responses with >in FormFlow

### ISSUE THREAD

**Issue by verdysh** [Microsoft/BotBuilder#3421]
## Bot Info 
* SDK Platform:  .NET
* Active Channels: Emulator

## Issue Description
Hi!
There is a bot created from the template http://aka.ms/bf-bc-vstemplate
In the created project I was update Bot Builder Package.
I try to understand examples of FormFlow from the documentatio: https://docs.microsoft.com/uk-ua/bot-framework/dotnet/bot-builder-dotnet-formflow

The documentation has such information:

>In each interaction, a > symbol indicates the point at which the user enters a response.

> The user can enter "help" at any point in the conversation to get guidance with filling out the form. For example, if the user enters "help" at the sandwich prompt, the bot will respond with this guidance.

> If the user enters "back" at this point in the conversation, the bot will return the previous prompt. The prompt shows the user's current choice ("Black Forest Ham"); the user may change that selection by entering a different number or confirm that selection by entering "c".

There it is said that there are other commands. But I do not work any of them. I tried to enter >help, help, > help, >Help, > Help, Help, but it is not work. Rest of the commands has the same behavior. I'm doing something wrong or the documentation is not really relevant?

**Comment by EricDahlvang** [comment]
Hi @verdysh 

The '>' symbol is not part of the text to be entered, but is a placeholder in the documentation indicating where the user would enter a response in a real-world scenario.

As an example:

```
Please select a bread
 1. Nine Grain Wheat
 2. Nine Grain Honey Oat
 3. Italian
 4. Italian Herbs And Cheese
 5. Flatbread
> nine grain
By "nine grain" bread did you mean (1. Nine Grain Honey Oat, 2. Nine Grain Wheat)
> 1

```

In the above scenerio, the user entered 'nine grain' for bread selection.  Then, the user entered '1' at the disambiguation prompt.

**Comment by verdysh** [comment]
@EricDahlvang, thank you!
