### ISSUE TITLE
ConversationReference's 'GetPostToBotMessage()' doesn't populate this.From.Name correctly

### ISSUE THREAD

**Issue by oflahero** [Microsoft/BotBuilder#3423]
## Bot Info 
* Code check only: v3.9.0

## Issue Description
When using ConversationReference's GetPostToBotMessage() function (in ConversationReferenceEx.cs), the 'From' property is set using `this.User.Id` to initialize both `From.Id` and `From.Name`.

## Code Example
See ConversationReferenceEx.cs, 'GetPostToBotMessage()':

```
                From = new ChannelAccount
                {
                    Id = this.User.Id,
                    Name = this.User.Id
                }
```

## Expected Behavior
I had expected Name to be `this.User.Name`...

## Actual Results
...and not `this.User.Id`.

**Comment by JasonSowers** [comment]
Is there a question here or are you just stating the code doesn't do what you expected?
  
Not all channels have a "Name" for the user so it would be impossible to instantiate an object with a "Name".  Closing this issue but please feel free to continue the conversation

**Comment by oflahero** [comment]
Yes, I suppose my question was 'is this by design?' - to which the answer appears to be 'yes'. :) It looked like a cut'n'paste oversight, but from what you're saying it's a necessity. Cheers.

I'll just let you know what led to my looking into this: in my bot, I keep a list of known channels that have communicated with it, taken from the 'msg' IActivity incoming (to the bot): msg.From.Id and msg.From.Name (and ChannelId).

I also keep a list of ConversationReferences, so that I can send proactive messages when I need to -created using an incoming IActivity 'msg': 

```
new ConversationReference(
  activityId: msg.Id,
  user: new ChannelAccount(id: msg.From.Id, name: msg.From.Name),
  bot: new ChannelAccount(id: msg.Recipient.Id, name: msg.Recipient.Name),
  conversation: msg.Conversation == null ? null : new ConversationAccount(isGroup: 
    msg.Conversation.IsGroup, id: 
    msg.Conversation.Id, 
    name: msg.Conversation.Name),
    channelId: msg.ChannelId,
    serviceUrl: msg.ServiceUrl)
```
Later, when I want to send a proactive message, I use the relevant convReference.GetPostToBotMessage() and use its From.Id and From.Name to match against the channel list I had earlier, which keys against external user info of mine. However, as GetPostToBotMessage() uses User.Id for both Id and Name, it obviously doesn't match against my saved From.Id and From.Name.

I'm currently just matching by Id and ignoring Name anyway.

**Comment by JasonSowers** [comment]
That would be the recommended way to do it, Good Luck!

**Comment by oflahero** [comment]
Thanks, I'll keep on keeping on so...

I guess my niggle with the thing is that you can get out less than you put in. If you initialize a ConversationReference using an IActivity, where that IActivity's 'From' has both an Id and a Name to populate the ConversationReference.User - and then later call ConversationReference.GetPostToBotMessage(), the returned Activity's 'From' has lost the original Name.

No matter, so long as it's expected behaviour.
