### ISSUE TITLE
  builder.Prompts.choice hangs when one of the choices is not picked

### ISSUE THREAD

**Issue by pantherso48** [Microsoft/BotBuilder#3425]
## Bot Info 
* Bot handle: Survey Assistant
* App ID: 794400ca-6645-4435-bf1c-1b297b166994
* SDK Platform: Node.js
* SDK Version: 8.1.3
* Active Channels: Cortana
* Deployment Environment: Azure app service

## Issue Description
Using a hero card and looking to handle when a user says or types something other the 5 button choices. Right now the code hangs at the builder.Prompts.choice(session, reply, choices) line when the incorrect input is given by the user. This is really only a problem with Cortana because she does not the built in 'I didn't understand....' logic when she cannot interpret what she is given.

## Code Example

```js
bot.dialog('Dissatisfied', [
  function (session, args, next) {
    const choices = ['Audio quality', 'Audio drops', 'Unable to connect audio', 'Missing feature/ functionality', 'Other (please specify)'];
    var reply = new builder.Message(session)
                   .text('Please select or tell me the reason that best represent why you are dissatisfied with Skype for Business Audio')
                   .speak('Please select or tell me the reason that best represent why you are dissatisfied with Skype for Business Audio')
                   .inputHint(builder.InputHint.expectingInput)
                   .addAttachment(createHeroCard(session, choices));

    builder.Prompts.choice(session, reply, choices);
  },
  function (session, results, next) {
    // var isOther = (results.response && results.response["index"] && results.response["index"]==4) ? true : false;
    // session.dialogData.isOther = isOther;
    if (results.response && results.response.entity.includes('Other')){
      debugger;
      var reply = new builder.Message(session)
                   .text('Please specify.')
                   .speak('Please specify.')
                   .inputHint(builder.InputHint.expectingInput);

      builder.Prompts.text(session, reply);
    } else {
      session.endConversation();
      session.beginDialog('imSurvey');
    }
  },
  function (session, results, next){
    session.dialogData.OtherSpecify = results.response;
    session.endConversation();
    session.beginDialog('imSurvey');
  }
]);
```

## Reproduction Steps
1. get to the hero card prompt
2. speak or type an answer that is not a choice of the 5 buttons of the hero card
3. repeat endlessly

## Expected Behavior
See the built in functionality in Cortana to tell the user the input is incorrect, but now looking for a way to handle it so the waterfall can move forward.

## Actual Results
'no intent handler found for null' is the error message received and photo of what happens in the emulator is attached
![image](https://user-images.githubusercontent.com/13629866/30085492-b55b47f4-9264-11e7-89f1-a02f904d32db.png)

**Comment by pantherso48** [comment]
Found the issue-actually the session.endConversation(); is the problem. That should only be used once the conversation between the user and bot is complete. In Cortana the bot would just stop where the   session.endConversation() was called but in the emulator it would keep moving forward.

Don't use session.endConversation() unless you are done with your work flow.

**Comment by JasonSowers** [comment]
Glad you found the answer, good luck

**Comment by RedhwanGhailan** [comment]
when a user says or types something other the choices. 
with this you can to specific the number of retries with msg . 
  

 builder.Prompts.choice(session, 'What list would like to show?', allLists, {
                            maxRetries: 3,
                            retryPrompt: ' what you wrote is not a valid option, please try again'
                        });

**Comment by Prayanime** [comment]
do you find the answer?
