### ISSUE TITLE
Cannot display the entire text in the hero card

### ISSUE THREAD

**Issue by dijotcr222** [Microsoft/BotBuilder#3426]
var card = new builder.HeroCard(session);
card.title("Did you mean one of the options below :");
card.buttons([
  builder.CardAction.imBack(session, DIDYOUMEANARRAY[0],DIDYOUMEANARRAY[0]),
  builder.CardAction.imBack(session, DIDYOUMEANARRAY[DIDYOUMEANARRAY.length-1],DIDYOUMEANARRAY[DIDYOUMEANARRAY.length-1])
]);

Text: How to change my password 

## Actual Results

[
<img width="169" alt="screen shot 2017-09-06 at 12 36 39 pm" src="https://user-images.githubusercontent.com/5425577/30092056-1c9fa630-9300-11e7-9816-483d91bfee67.png">
](url)

**Comment by pantherso48** [comment]
It may be easier if you make a function to create your hero card and pass the array of values you have, DIDYOUMEANARRAY[] into the function like so:

function createHeroCard(session, choices) {
    return new builder.HeroCard(session)
        .title('Please say or click your choice')
        .buttons(choices.map(choice => new builder.CardAction.imBack(session, choice, choice)));
}

Also check to make sure you have more than 1 value in your array, if you could post the array that would help too.

**Comment by JasonSowers** [comment]
Can you please fill out the template so we can better assist you.  What channel are you using?

**Comment by dijotcr222** [comment]
Any luck ??

**Comment by JasonSowers** [comment]
There is a limitation on the length of text in buttons in different channels I assume you have hit that limit.  Please reopen if you are willing to provide more details.
