### ISSUE TITLE
[Question] Where is code of business logic of command processing in MultiDialogsBot sample?

### ISSUE THREAD

**Issue by verdysh** [Microsoft/BotBuilder#3427]
## Bot Info 
* SDK Platform:  .NET
* Active Channels: Emulator

## Issue Description
There is a bot from sample [MultiDialogsBot ](https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/core-MultiDialogs)

I can not understand how the bot reacts to the commands (Back, Help, Quit, Reset, Status)?
I'm trying to set a breakpoint in MessagesController.Post and in all methods in RootDialog class. But , for example, when I typing **status** bot answers me, but not one breakpoint does not work.

Where is code of business logic of command processing?

**Comment by JasonSowers** [comment]
@ejadib do you happen to know?

**Comment by JasonSowers** [comment]
Is this what you are looking for?  It comes from the `RootDialog` 
```cs
        public virtual async Task MessageReceivedAsync(IDialogContext context, IAwaitable<IMessageActivity> result)
        {
            var message = await result;

            if (message.Text.ToLower().Contains("help") || message.Text.ToLower().Contains("support") || message.Text.ToLower().Contains("problem"))
            {
                await context.Forward(new SupportDialog(), this.ResumeAfterSupportDialog, message, CancellationToken.None);
            }
            else
            {
                this.ShowOptions(context);
            }
        }
        private async Task ResumeAfterSupportDialog(IDialogContext context, IAwaitable<int> result)
        {
            var ticketNumber = await result;

            await context.PostAsync($"Thanks for contacting our support team. Your ticket number is {ticketNumber}.");
            context.Wait(this.MessageReceivedAsync);
        }
```
Also uses code from `SupportDialog` to populate the ticket number

```cs
        public virtual async Task MessageReceivedAsync(IDialogContext context, IAwaitable<IMessageActivity> result)
        {
            var message = await result;

            var ticketNumber = new Random().Next(0, 20000);

            await context.PostAsync($"Your message '{message.Text}' was registered. Once we resolve it; we will get back to you.");

            context.Done(ticketNumber);
        }
```

**Comment by verdysh** [comment]
It's not really that.

I would like to understand how work the commands "back", "quit", "status", "reset". They are hidden somewhere inside FormBuilder class? Is it possible to call them something else, for example: quit => leave; status => where I am; etc.

**Comment by EricDahlvang** [comment]
Hi @verdysh 

These are FormCommands.  They are initialized here: https://github.com/Microsoft/BotBuilder/blob/497252e8d9949be20baa2cebaa6ce56de04461cf/CSharp/Library/Microsoft.Bot.Builder/FormFlow/IFormBuilder.cs#L395  and logic for handling them is found here: https://github.com/Microsoft/BotBuilder/blob/f9f9110fcf0ad46d335b26371819732899e92990/CSharp/Library/Microsoft.Bot.Builder/FormFlow/FormDialog.cs#L775

**Comment by verdysh** [comment]
Hi @EricDahlvang!
Seems, that is what I need! Thanks!
