### ISSUE TITLE
[Facebook Messenger] ChatConnector: receive - invalid token. Check bot's app ID & Password error

### ISSUE THREAD

**Issue by oualidbarjani** [Microsoft/BotBuilder#3430]
## Bot Info 
* Bot handle: parabot  
* SDK Platform: Node.js 
* Active Channels: messenger
* Deployment Environment:  Azure App Service, other 

## Issue Description

Hello, i'm developping a chatbot and i have a problem with connectivity. 

Sometimes it can happen when the user send a message, or when he hit a button.i have this ERROR: ChatConnector: receive - invalid token. Check bot's app ID & Password.and i don't know where it comes from . in the same conversation sometimes the bot answer normally and sometimes ihave this error . 

if someone can help me I would be very grateful.

thank you

**Comment by nwhitmont** [comment]
Hi @oualidbarjani - Are you still experiencing the problem?

**Comment by fanidamj** [comment]
Closing the issue as it seems inactive. Feel free to reopen if you any questions of comments.
