### ISSUE TITLE
[Question] Node SDK code inconsistency (maybe security bug)

### ISSUE THREAD

**Issue by tg44** [Microsoft/BotBuilder#3433]
https://github.com/Microsoft/BotBuilder/blob/master/Node/core/src/bots/ChatConnector.ts#L185

The `algorithms: algorithms`, missing for purpose or I found a (probably really tiny) security bug?

(If sb fixes this: the algorithms and clock tolerance set can be factored out and can be set only once instead of 4 place. And block starting at 191 could be moved upper to ~154 to make a quicker reply.)

**Comment by stevengum97** [comment]
@Stevenic?

**Comment by nwhitmont** [comment]
Thanks for reporting. Not a bug.
