### ISSUE TITLE
[LUIS] Closed list and synonyms with periods not recognized

### ISSUE THREAD

**Issue by martinoss** [Microsoft/BotBuilder#3436]
## Bot Info 
* Bot handle: 
* SDK Platform: .NET
* Active Channels: Skype, WebChat, Facebook

## Issue Description
I have a closed list with months I need to detect from an intent. I added synonyms like "okt." for october, what is a common way to write a month in german. I also added "oct". But as soon, there is a period in the value, It will not be recognized, "oct" is. ~~If I create a phrase list, say "october: [oct.]" it's going to be recognized~~, but the limit of 10 items makes it totally impractical.

## Expected Behavior
I expect, that the synonyms are matched as they are, even if they have a period in it.

**Comment by stevengum97** [comment]
List Entities are _exactly matched_ using RegEx.  So if you add **oct**, and **okt**, then _oct._ and _okt._ will not be recognized.

Which limit of 10 items are you talking about? As far as I know there isn't any limit like that.

**Comment by martinoss** [comment]
I'm aware hat they should exactly match but they don't.
Let's say the canonical form is "october" and synonyms are "oktober", "okt"
and "okt.", the last one is not recognized if I query like "1. okt. 2017"

The limit of 10 items is for the phrase list feature.


Am 07.09.2017 22:24 schrieb "Steven Gum" <notifications@github.com>:

List Entities are *exactly matched* using RegEx. So if you add *oct*, and
*okt*, then *oct.* and *okt.* will not be recognized.

Which limit of 10 items are you talking about? As far as I know there isn't
any limit like that.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/BotBuilder/issues/3436#issuecomment-327917638>,
or mute the thread

**Comment by JasonSowers** [comment]
As a solution, you could possibly cleanse the user input and remove the period.
