### ISSUE TITLE
What Happen? FB Connector response very very slow In the last few days

### ISSUE THREAD

**Issue by areckkimo** [Microsoft/BotBuilder#3439]
## Bot Info 
* Bot handle: taiwanTrainChatRobot 
* App ID: 9c556648-ca0f-4d77-adbf-0ae66aa3960d
* SDK Platform: Node.js
* SDK Version: 3.9.1
* Active Channels: Facebook
* Deployment Environment: Auzure Bot Service

## Issue Description
What Happen? FB Connector response sometimes very very slow In the last few days

[issue demo video](https://youtu.be/jKJaC-Yb88Q)

user send msg --> fb server --> ms bot connector -->my bot hosting 
<----------------------------1-2secs-------------------------------->

my bot hosting reply msg --> ms bot connector --> fb server --> display msg on messenger
<---------------------------------------30-40secs---------------------------------------->

## Code Example

```
bot.dialog('/howToUseQueryTime',[
   function (session) {
       session.endDialog("好的。請問您要查詢哪一班的火車時刻 ? 您可以說「台北到松山」或則搭配不同的日期、時間或車種，例如「10/6 13:30 台北到高雄自強號列車」。");
   }
]);
```

## Reproduction Steps
1.session.send("XXX");
2.waiting for about 30-40 secs (general 1-2 secs)
3.fb messenger display XXX

**Comment by areckkimo** [comment]
help me

**Comment by JasonSowers** [comment]
please post your app ID and bot handle so we can take a look, thanks

**Comment by areckkimo** [comment]
@JasonSowers 
* Bot handle: taiwanTrainChatRobot 
* App ID: 9c556648-ca0f-4d77-adbf-0ae66aa3960d

thanks

**Comment by areckkimo** [comment]
After sending "session.send (" XXXX ")" does not call the ChatConnector's send function immediately

**Comment by areckkimo** [comment]
I find problem
The bot become fast after remove Botanalytic.

```
//=========================================================
// Botanalytics
//=========================================================

// Initialize the middleware
var BotanalyticsMiddleware = require('botanalytics-microsoftbotframework-middleware').BotanalyticsMiddleware({
    token: process.env.BOTANALYTICS_TOKEN
});

bot.use(
    {
        receive: BotanalyticsMiddleware.receive,
        send: BotanalyticsMiddleware.send
    }
);
```

**Comment by JasonSowers** [comment]
glad you found the problem, Good luck
