### ISSUE TITLE
Non-bots can't talk to non-bots

### ISSUE THREAD

**Issue by brunobrandes** [Microsoft/BotBuilder#344]
Hi,
I need starting a conversation but I receive exception 'Non-bots can't talk to non-bots'

              var connectionCLient = new ConnectorClient("appId", "appSecret");

                Message message = new Message();
                message.From = new ChannelAccount
                {
                    Name = "appId",
                    ChannelId = "emulator",
                    Address = "appId",
                    Id = "appId",
                    IsBot = true
                };
                message.To = new ChannelAccount()
                {

                    Name = "User1",
                    ChannelId = "emulator",
                    Address = "User1",
                    Id = "2c1c7fa3",
                    IsBot = false
                };
                message.Text = "Hey, what up homey";
                message.Language = "en";

               await connectionCLient.Messages.SendMessageAsync(message);

Contains another way to do this?

**Comment by tomlm** [comment]
You are talking to the production environment instead of the emulator

If you are trying to talk to the emulator you need to do:
          var connectionClient = new ConnectorClient(new Uri(http://localhost:9000), new ClientCredentials("appId", "appSecret"));

If you are trying to talk to the prod environment then your channelId is wrong

**Comment by tomlm** [comment]
You are talking to the production environment instead of the emulator

If you are trying to talk to the emulator you need to do:

          var connectionClient = new ConnectorClient(new Uri(http://localhost:9000), new ClientCredentials("appId", "appSecret"));

If you are trying to talk to the prod environment then your channelId is wrong
