### ISSUE TITLE
Location control within FormFlow

### ISSUE THREAD

**Issue by perrein** [Microsoft/BotBuilder#3440]
Hello,
Is it possible to use the Location Control within FormFlow?
For example, fill an address automatically for a field?
Thanks,
Math

**Comment by EricDahlvang** [comment]
Hi @perrein 

FormFlow does not currently support calling a dialog.  This is a popular request though.  The answer on this issue still applies: https://github.com/Microsoft/BotBuilder/issues/1998

Here is a FeatureRequest for an attribute that could call a dialog: https://github.com/Microsoft/BotBuilder/issues/3293  This has not yet been implemented though.

**Comment by Ma3yTa** [comment]
Hi @perrein, if you resolved this please provide your solution.
