### ISSUE TITLE
Can not disable the "High-speed storage" option in the Bot Framework developer portal.

### ISSUE THREAD

**Issue by RikaEndo0** [Microsoft/BotBuilder#3441]
## Bot Info 
* Bot handle: arika-helpbot-1   
* App ID: 4447beaf-00a3-47e1-a5db-2e2dc1776323
* SDK Platform: 
* SDK Version: 
* Active Channels: WebChat
* Deployment Environment: Auzure Bot Service 

## Issue Description
I can not disable the "High-speed storage" option in the Bot Framework developer portal.
Even if  I unchecked and saved it, it will be enabled the next time open it.

## Reproduction Steps
1. Open the Bot Framework developer portal.
2. Visit your bot.
3. Navigate to your Direct Line configuration page.
4. Uncheck the "High-speed storage" option.
5. Select "Done".
6. Navigate again to your Direct Line configuration page.

## Expected Behavior
the "High-speed storage" option Unchecked.

## Actual Results
the "High-speed storage" option checked.

**Comment by EricDahlvang** [comment]
Hi @RikaEndo0 

This option will be exiting preview very soon, and is becoming the default. It will be removed from the UI soon.
