### ISSUE TITLE
Error when bot is deployed on Azure

### ISSUE THREAD

**Issue by kanwal019** [Microsoft/BotBuilder#3442]
## Bot Info 
* Bot handle: BotAppProd
* App ID: 6407709a-6db4-43d2-b9ee-ad63f174fa5b
* SDK Platform: .Net
* SDK Version: 3.9
* Active Channels: DirectLine, Chat
* Deployment Environment: Azure App Service

## Issue Description
Bot works fine with the emulator, but gives 500 error code when deployed on azure. Error is same in the WebChat and DirectLine channel.

## Expected Behavior
Bot works in the similar manner when deployed.

## Actual Results
_There was an error sending this message to your bot: HTTP status code InternalServerError_

This message is displayed on the bot.

**Comment by JasonSowers** [comment]
The 500 error is a generic message that basically means something is wrong within your bot code.  Is there any way you can share your code in a repo, or debug and post the minimum code to reproduce?

**Comment by kanwal019** [comment]
Thank you, the issue is resolved.
