### ISSUE TITLE
microsoft web enabled bot is not working suddenly stopped working

### ISSUE THREAD

**Issue by ReenaPatel2410** [Microsoft/BotBuilder#3443]
## Bot Info 
* Bot handle: 
* App ID: 
* SDK Platform: 
* SDK Version: 
* Active Channels: 
* Deployment Environment: 

## Reproduction Steps
1.
2.
3.

**Comment by EricDahlvang** [comment]
Hi @ReenaPatel2410 

Please fill out the template, so we can better assist you.
