### ISSUE TITLE
Bot Framework direct line throwing HTTP status code 500

### ISSUE THREAD

**Issue by neel92** [Microsoft/BotBuilder#3444]
## Bot Info 
* Bot handle: MarutiTechRequirementGatheringBot
* App ID: d8469ea7-9fe0-424b-af8e-37a24943dfb8
* SDK Platform: .NET
* SDK Version: 3.0.0.0
* Active Channels:  Skype, Direct Line

## Issue Description

From 09/08/2017 `/api/messages` api is throwing  500 HTTP status code. We haven't change any code or tokens since last few months.

Are there any changes deployed for `/api/messages` API?

**Comment by EricDahlvang** [comment]
Hi @neel92 

Please upgrade the Bot Builder SDK to the latest version (3.9.0).  The authentication schema has been changed: https://blog.botframework.com/2017/05/07/bot-framework-auth-change/

**Comment by neel92** [comment]
Thanks @EricDahlvang !!
