### ISSUE TITLE
LUIS Programmatic api Update phraselist feature in Node.js

### ISSUE THREAD

**Issue by nupurkamble** [Microsoft/BotBuilder#3449]
I'm trying to update phraselist of my luis application through LUIS Programmatic api . Sample codes are given on [this website ](https://dev.projectoxford.ai/docs/services/5890b47c39e2bb17b84a55ff/operations/5890b47c39e2bb052c5b9c06) in a few languages but im trying to find a sample code in Node.js.
The basic code in C# is 

    using System;
    using System.Net.Http.Headers;
    using System.Text;
    using System.Net.Http;
    using System.Web;
    namespace CSHttpClientSample

    {
    static class Program
    {
        static void Main()
        {
            MakeRequest();
            Console.WriteLine("Hit ENTER to exit...")
            Console.ReadLine();
        }
        static async void MakeRequest()
        {
            var client = new HttpClient();
            var queryString = HttpUtility.ParseQueryString(string.Empty);
            // Request headers
            client.DefaultRequestHeaders.Add("Ocp-Apim-Subscription-Key", "{subscription key}");

            var uri = "https://westus.api.cognitive.microsoft.com/luis/api/v2.0/apps/{appId}/versions/{versionId}/phraselists/{phraselistId}?" + queryString;

            HttpResponseMessage response;
            // Request body
            byte[] byteData = Encoding.UTF8.GetBytes("{body}");

            using (var content = new ByteArrayContent(byteData))
            {
                content.Headers.ContentType = new MediaTypeHeaderValue("< your content type, i.e. application/json >");
                response = await client.PutAsync(uri, content);
            }
        }
    }}

Where can i find a Node.js code ?

**Comment by GauravDhavale** [comment]
@nupurkamble Did you find a way to implement it in Node JS? I'm trying to implement using https package but facing some issues with headers parameter.

**Comment by RedhwanGhailan** [comment]
i find a way to implement it in Node JS. by LUIS with qnamaker .
