### ISSUE TITLE
Do conversations expire?

### ISSUE THREAD

**Issue by ahmettaha** [Microsoft/BotBuilder#345]
Hello,

Do conversations and conversations ids expire? So for example let's say the user has joined a flow dialog. Answered 2 questions out 5 and stopped there. Can he return to the same dialog after a week and continue from where he left off?

**Comment by tomlm** [comment]
They will not expire

**Comment by tomlm** [comment]
Actually, it’s a bit more nuanced.  ConversationIds are tied to the semantics of conversation for that channel.

Skype -> I think Skype has conversation ids that roll over when there has been a period of inactivity.
Slack -> Tied to slack channel id so does not expire
Email -> Tied to threadId of the email so does not expire
SMS -> Tied to pair of phone numbers so does not expire
Facebook -> Has no conversation semantic so it is tied to user as it is 1:1 conversation
Telegram -> not sure, but I think tied to a chat session
GroupMe -> Tied to group Id and does not expire until the group goes away
WebChat -> Tied to browser session

**Comment by ahmettaha** [comment]
Ok. So does this mean the dialog state and stack is saved forever on the botframework platform? A user can always continue the dialog with infinite duration.

**Comment by tomlm** [comment]
Infinity is a very long time, but yes, there is no data deletion/cleanup policy

**Comment by xtianus79** [comment]
@tomlm for directline specifically as a channel you're saying there is no deletion of conversationId's and when you use a user does the conversationId get associated with the userId?
