### ISSUE TITLE
[Skype for business]  integration with SFB

### ISSUE THREAD

**Issue by mbettan** [Microsoft/BotBuilder#3451]
## Bot Info 
* Bot handle: ithelpchatbot@mbettan.onmicrosoft.com
* App ID: 6f1d5233-80e1-4318-8467-e5a364076516
* SDK Platform: .NET
* SDK Version: 4.7
* Active Channels: Skype for business
* Deployment Environment: Azure Bot Service

## Issue Description
Hello, I really need some help with an issue. I have a working .NET C# bot working on Telegram integration but not with Skype for Business.
I have configured Skype for Business on Office 365 Premium trial and added the integration in Bot Framwork with two powershell command
I can see the new user in my office 365 and add it into my Skype client as end user
But the bot is still offline.... it looks like the discovery is not working? It was done 5 hours ago
Does anyone knows why my bot is not working with Skype for business? How to troubleshoot? How to force the discovery?

## Code Example
Standard example from Azure App Service

## Reproduction Steps
1.
2.
3.

## Expected Behavior
Bot to talk

## Actual Results
Bot is offline on Skype client.... Not connected!!!

**Comment by JasonSowers** [comment]
Have you tried talking to the bot?  I contacted the SFB team and they said presence is not supported.  You can see the bot so discovery is working.

**Comment by mbettan** [comment]
Thanks the issue was the domain...

**Comment by wenrrymontanha** [comment]
Hello guys, my problem is similar to this one, my bot is perfectly functional on MS Teams using azure enviroment..
i've conected the bot with the two powershell cmdlet and it's been created but its still offline (the presence unknown message is not shown!!!) its just OFFLINE, and when i try to talk to it just doesn't work....

MS app ID: a1743f7b-83db-4ce5-ae88-cda52c220be0
-----------------------------------------------
RunspaceId     : 68f56c68-b242-440a-af0c-6a63cab9e9d5
Id             : 02d65798-eb7e-4ead-ac0a-114e1d6b7c29
![captura de tela 2](https://user-images.githubusercontent.com/38286435/38617984-bdb690ce-3d6e-11e8-84d4-545bfb991088.png)
![captura de tela 1](https://user-images.githubusercontent.com/38286435/38617994-c22ed756-3d6e-11e8-9070-9feeb7ee548f.png)
