### ISSUE TITLE
LUIS Date recognition without separator 

### ISSUE THREAD

**Issue by umang0202** [Microsoft/BotBuilder#3452]
## Bot Info 

* SDK Platform: Node
* Active Channels: FB Messenger
* Deployment Environment: Azure App Service

## Issue Description
I'm using LUIS for recognising date ranges for a travel agent chatbot. All works for me, but for some reason, I can't get utterances without a date separator to work. For example "12 13 Sep" is not recognized as a date range, even though "12-13 Sep" is. I read somewhere that LUIS uses [chrono](https://github.com/wanasit/chrono) for date parsing, but "12 13 Sep" works perfectly with [chrono](https://github.com/wanasit/chrono).

I'm in a fix because many of my users are being affected by this. What can I do?

**Comment by JasonSowers** [comment]
Are you using datetimeV2?

Some suggestions you may want to try:

1. In your prompt specify the date format needed to properly recognize the date range.
2. You may be able to create a composite entity like {{startDate}{enDate}{month}} or {{startDate}{enDate}{startMonth}{endMonth}}. This is kind of a hacky solution, but it might work for you.

**Comment by umang0202** [comment]
Yup, I'm using datetimev2.

By specifying the date format in the prompt, do you mean specifying it to the user?

**Comment by JasonSowers** [comment]
I'm assuming you prompt the user i.e. "what days would you like to travel" or "what are your travel dates" adding something like "please format you date as start day - end day month" or something similar may do the trick to help guide your users.

**Comment by JasonSowers** [comment]
going to post this answer on SO and close this Issue here, that way it is indexed for others that may be having the same issue
