### ISSUE TITLE
[Question] Delete messages stored in the directline under a particular conversation id

### ISSUE THREAD

**Issue by MadhuAcc12** [Microsoft/BotBuilder#3453]
How can I delete messages that are stored in the directline? My messages have reached 99 and I am continuously getting the same message as response. For example, if i say "Hi" it responds says "How are you" and if I say "How to contact an agent" still it says "How are you". For any question it gives the same response as if it is stuck somewhere. Can someone please help me with this? How can I delete the messages that are stored in the directline under that particular conversation id?

![image](https://user-images.githubusercontent.com/30169639/30377179-7699da1e-98ac-11e7-974e-b199672df26f.png)

**Comment by EricDahlvang** [comment]
Please post the code for your bot.

Note: The Direct Line is not a message store, but has a temporary cache of messages to aid with connection stability issues.  If you are polling for messages using the Direct LIne, then you should also use the watermark feature to ensure you only retrieve messages from the cache that have not already been retrieved.  There are a some examples here: https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/core-DirectLine and using web sockets: https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/core-DirectLineWebSockets

**Comment by MadhuAcc12** [comment]
The Bot code is perfectly fine. I have checked the logs for the bot, the bot replies with the correct answer. This is a orchestrator code which in turn calls the bot. I am posting the directline call code below please have a look at it. I somehow feel that the messages count has reached 100 in the tempoparay directline cache for that particular conversation id because of which we are getting the repeated response. If i compare the orchestrator logs and the bot logs, I can see that bot gives the correct answer but the orchestrator is giving this repeated answer. I just wanted to try clearing the directline messages for that conversation id and then check if it works fine then.

`using DirectLineClient.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using System.Web;

namespace CathyRestAPI.Models
{
    public class DirectLineClient
    {
       
            private const string host = "https://directline.botframework.com";

            private static string conversationsAPI = $"{host}/api/conversations";

            private readonly string botSecret;

            private static TraceSource _source = new TraceSource("Logs");

            private static string className = "DirectLineClient";

            public static string reply = string.Empty;

            private static string nonrepliederrormsg = "Oops! Something went wrong. Lets try again";
            public DirectLineClient(string botSecret)
            {
                this.botSecret = botSecret;
            }

            public async Task<StartConversationResponse> StartConversationAsync()
            {
                using (var httpClient = new HttpClient())
                {
                    httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("BotConnector", botSecret);
                    httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                    var response = await httpClient.PostAsync(conversationsAPI, null);

                    response.EnsureSuccessStatusCode();

                    return JsonConvert.DeserializeObject<StartConversationResponse>(await response.Content.ReadAsStringAsync());
                }
            }

          public async Task<StartConversationResponse> refreshToken(string tokenToRefresh)
         {
            _source.TraceEvent(TraceEventType.Information, 0, className + DateTime.Now.ToString(" MMM ddd d h:mm:ss tt") + "\t " + "Token to Refresh :" +tokenToRefresh);
            using (var httpClient = new HttpClient())
            {
                httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", tokenToRefresh);
                httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                var response = await httpClient.PostAsync("https://directline.botframework.com/v3/directline/tokens/refresh", null);
                response.EnsureSuccessStatusCode();
                return JsonConvert.DeserializeObject<StartConversationResponse>(await response.Content.ReadAsStringAsync());
            }
        }

        public async Task<string> SendMessageAsync(string conversationId, string from, string text)
            {
                string url = $"{host}/api/conversations/{conversationId}/messages";

                var message = new
                {
                    from = from,
                    text = text
                };

                HttpContent content = new StringContent(JsonConvert.SerializeObject(message), Encoding.UTF8, "application/json");

                using (var httpClient = new HttpClient())
                {
                    httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("BotConnector", botSecret);//BotConnector
                    httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                    var response = await httpClient.PostAsync(url, content);

                    if (response.StatusCode != System.Net.HttpStatusCode.NoContent)
                    {
                        // TODO: response.EnsureSuccessStatusCode();
                    }

                }

                // return JsonConvert.DeserializeObject(await response.Content.ReadAsStringAsync());

                return text;


            }

            public async Task<ConversationMessages> GetMessagesAsync(string conversationId)
            {
                string url = $"{host}/api/conversations/{conversationId}/messages"; //?watermark={watermark}";

                using (var httpClient = new HttpClient())
                {
                    httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("BotConnector", botSecret);
                    var response = await httpClient.GetStringAsync(url);

                    return JsonConvert.DeserializeObject<ConversationMessages>(response);
                }
            }
            public static string directlinecall(CathyRequest request, string secret_key, UserProfile userprofile, string conversationID)
            {
                StartConversationResponse drC1, dlc1;
                ConversationMessages Cm;

            try { 
                string answer = string.Empty;
         //       string conversationId = string.Empty;
                string count = string.Empty;
                DirectLineClient dlc = new DirectLineClient(secret_key);
                /*     Task.Run(async () =>
                     {
                         dlc1 = await dlc.StartConversationAsync();
                         userprofile.LastCathyConversationId = dlc1.ConversationId; ;
                     }).Wait(); */

                //string conv=(dlc1.ConversationId).ToString();
                string reply1 = string.Empty;
                int counter = 0;

                Retry:
                    Task.Run(async () =>
                    {

                        reply1 = await dlc.SendMessageAsync(conversationID, userprofile.SenderName, request.RequestMessage);

                    }).Wait();

                    Console.WriteLine("" + reply1);

                    Task.Run(async () =>
                    {
                                                //count = (i + 1).ToString();
                        Cm = await dlc.GetMessagesAsync(userprofile.LastCathyConversationId);
                        
                        // Cm = await dlc.GetMessagesAsync(conversationID);
                       
                        reply = Cm.Messages[(Cm.Messages.Count - 1)].Text;                       

                    }).Wait();               
               

                    if (reply1 == reply || (reply.ToLower()).Contains("sorry"))
                    {
                    if (!(counter >= 2))
                    {
                        Console.WriteLine("Retrying");
                        counter++;
                        goto Retry;
                    }
                    else
                    {
                        reply = nonrepliederrormsg;
                    }
                 }
            }
            catch (Exception e)
            {
                _source.TraceEvent(TraceEventType.Information, 0, className + DateTime.Now.ToString(" MMM ddd d h:mm:ss tt") + "\t Exception thrown is:  " + e);
                throw e;                
            }            
            return reply;
        }
       
    }
    
  }`

**Comment by MadhuAcc12** [comment]
So I tried executing questions in a loop of more than 100 and noticed that when the messages cache reaches a count of 100 it stops storing new bot messages and hence gives the same repeated response that is there in the 100th element of the messages array. Can someone give me a solution for this? How can I tackle this issue?

**Comment by michaelhutchful** [comment]
As was said earlier, use the water mark parameter to poll for the messages, this will give you all the messages after a particular water mark Retrieve activities with HTTP GET. But I will advice that you use the web socket method rather. This will provide much better performance

Michael 
Sent from Mail for Windows 10

**Comment by MadhuAcc12** [comment]
can you please provide me some links for the same? I don't exactly know what does watermark do.

**Comment by fanidamj** [comment]
Can you please let us know if the issue still persists?

**Comment by vishwacsena** [comment]
@EricDahlvang can you please take a look and add pointers to doc/ a sample?

**Comment by EricDahlvang** [comment]
Documentation on the Watermark can be found here: https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-receive-activities?view=azure-bot-service-3.0#process-messages
