### ISSUE TITLE
adaptive card input value should be available in dialog flows

### ISSUE THREAD

**Issue by macrozone** [Microsoft/BotBuilder#3454]
## Bot Info 
* Bot handle: 
* App ID: 
* SDK Platform: node
* SDK Version: 3.9.1
* Active Channels: DirectLine
* Deployment Environment: 

## Issue Description

with Prompts or Choice you always get the answer in the next function of the dialog. This is not true for adaptive cards. [This example shows how to get dialog value](https://github.com/Microsoft/BotBuilder-Samples/blob/master/Node/cards-AdaptiveCards/app.js), on line 25 there is processSubmitAction which handles the results of a adaptive card. As you can see this function needs to know something about the dialog where the card was built. This is a design flaw and is different than how you work with other user inputs like prompts, confirm and choices.

## Code Example

see above

## Expected Behavior

working with adaptive cards should be similar to other user inputs like confirm, choice and prompt:

```
  bot.dialog('/controlDelivery', [
    function (session) {
      const card = {
        contentType: 'application/vnd.microsoft.card.adaptive',
        content: {
          type: 'AdaptiveCard',
          body: [
            {
              type: 'TextBlock',
              text: 'Delivery date',
            },
            {
              type: 'Input.Date',
              id: 'deliveryDate',
            },
          ],
          actions: [
            {
              type: 'Action.Submit',
              title: 'Submit',
            },
          ],
        },
      };
      const msg = new builder.Message(session).addAttachment(card);
      session.send(msg);
    },
    function (session, result) {
     // would expect the result here like
      console.log(result);
    },
  ]);

``

**Comment by macrozone** [comment]
I found a workaround:

```
bot.dialog('/controlDelivery', [
  function (session, __, next) {
    // 
    const msg = new builder.Message(session).addAttachment(card);
    session.send(msg);
    // this:
    next();
  },
  function(session) {
       const { value } = session.message;
      console.log(value)
   }
])

**Comment by EricDahlvang** [comment]
Hi @macrozone 

I'm glad you found a workaround.

Please note that Adaptive Cards useful in more than just the context of the Bot Builder.  Bot Builder has not necessarily dictated the design characteristics of Adaptive Cards.  Please use the Adaptive Cards GitHub repo for feature requests and suggestions: https://github.com/Microsoft/AdaptiveCards
