### ISSUE TITLE
[Question] Bot currently not working in Skype

### ISSUE THREAD

**Issue by chungweileong94** [Microsoft/BotBuilder#3455]
## Bot Info
* Bot handle: lcw_bot
* App ID: aa43c51d-adb7-413f-b587-4be233270212
* SDK Platform: Node.js
* SDK Version: 3.9.1
* Active Channels: Skype
* Deployment Environment: other

## Issue Description
Currently I trying out the bot framework on Node.js, but it seems like the bot on Skype is broken now, I can't get the bot reply, however the bot did works on Cortana and web chat. I tried the other bots that available to public, same issue. (Note that the code that I wrote is very simple as the documentation)

## Code Example
null

## Reproduction Steps
1. deploy bot
2. add bot as skype contact
3. chat

## Expected Behavior
Bot reply

## Actual Results
Bot did nothing

**Comment by JasonSowers** [comment]
I just tested your bot and was able to use it:
![image](https://user-images.githubusercontent.com/6301037/30389841-e2a32196-9868-11e7-9915-8e0926096919.png)

**Comment by chungweileong94** [comment]
@JasonSowers Hmm, weird...I tried on my PC, W10M, Android, they all got the same issue.

**Comment by JasonSowers** [comment]
Really do not know what to tell you here sorry :(

**Comment by JasonSowers** [comment]
Did it start working for you?

**Comment by chungweileong94** [comment]
Still not working now.
However I did notice that only bot from Foursquare is working normally, that rest of the bot is broken for me.
And one of my old bots that I build using SDK version 1.x or 2.x, it working fine too.
So I suspect that bots which used latest SDK is stop working for me.

**Comment by chungweileong94** [comment]
The bot is start working now on Skype.
