### ISSUE TITLE
[Skype for Business] Issue a Removing a bot – Skype for Business Tenant Administrator

### ISSUE THREAD

**Issue by amitgobare23** [Microsoft/BotBuilder#3458]
Hi....I am facing an issue to removing a Bot from Skype for Business
I follow below step:
1. Download and install the Skype for Business Online Connector module
2. Open Windows PowerShell as Administrator and run the following:

Import-PSSession (New-CsOnlineSession -Credential (Get-Credential))
3. You will be prompted with windows PowerShell credential dialog box. Sign in using the tenant admin credentials.

4. Run the following PowerShell

Remove -CsOnlineApplicationEndpoint -Uri sip:username@yourdomain.com

But it shows below error:
Remove : The term 'Remove' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

anyone please tell me workaround for same....Thanks in Advance:)

**Comment by miyamotoatsushi** [comment]
Exclude space.

Remove-CsOnlineApplicationEndpoint -Uri sip:username@yourdomain.com

**Comment by amitgobare23** [comment]
It's still not working...
I remove it from Azure portal itself by using Administrator credentials but it take some time to remove from skype for business

**Comment by sgellock** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
