### ISSUE TITLE
[Question] Issue in Bot

### ISSUE THREAD

**Issue by imtvase** [Microsoft/BotBuilder#3459]
Hi,

I have created the bot and hosted on my window server using IIS.
 I registered the endpoint on bot framework, but i am not able to communicate with bot.

Please see the attach snap

![bot_issue](https://user-images.githubusercontent.com/31928487/30419335-9d558372-9953-11e7-9f5e-94e7179e2bd3.jpg)

Error - There was an error sending this message to your bot: HTTP status code NotFound

Please help me to resolve this issue.

**Comment by EricDahlvang** [comment]
Please provide the following information, so we can better assist you:

* Bot handle: 
* Microsoft App ID: 
* Node or .NET SDK Platform: 
* Bot Builder SDK Version: 

-----

The Bot Framework works with bots deployed on any cloud hosting service, as long as you have an internet-accessible endpoint and a valid SSL certificate.

The Bot Framework requires that the x.509v3 certificate exposed by your endpoint be current and valid. Most of the checks for "current and valid" are standard checks for server SSL certificates: the Certificate Name must match the hostname, it must not be expired, it must not be listed in a CRL, it must have the correct set of EKUs, etc.

Most importantly, your SSL certificate must chain to a root certificate authority trusted by Microsoft. The latest list of these CAs is available here: 

http://social.technet.microsoft.com/wiki/contents/articles/31634.microsoft-trusted-root-certificate-program-participants-v-2016-april.aspx

**Comment by imtvase** [comment]
Thanks for your valuable input, I will provide you details.

You mean to say that if I want to host the machine on my local window server in IIS, I need https connection with x.509v3 certificate.

**Comment by JasonSowers** [comment]
Yes
