### ISSUE TITLE
Telegram Custom Keyboards

### ISSUE THREAD

**Issue by byrner75** [Microsoft/BotBuilder#346]
Hi,

I have the following function to create the channelData for a Telegram custom keyboard. However it does not work. If I wrap the reply_markup value with a JSON.stringify it does work. Is this by design? 

```
function getTelegramKeyboardChannelData() {
    return {
            "method": "sendMessage",
            "parameters":
            {
                "text": "Test Keyboard Message",
                "reply_markup": {"keyboard":[[{"text":"HELLO"}]]}
            }
        }
}
```

**Comment by eanders-MS** [comment]
Yes, Telegram expects to receive the reply_markup value as a serialized JSON object. Documented here: https://core.telegram.org/bots/api#sendmessage
