### ISSUE TITLE
500 internal server error- Azure web app hosting a botframework solution

### ISSUE THREAD

**Issue by KwstasBol** [Microsoft/BotBuilder#3463]
## Bot Info 
* Bot handle: amvrosiabot
* App ID: fe2f78fd-c257-4e0f-92d6-79906b847172
* SDK Platform:  .NET 
* SDK Version: 4.6.1
* Active Channels: Facebook Messenger
* Deployment Environment:  Azure App Service

## Issue Description
My bot connects to the database of mine, takes the foods of the university restaurant compared to the current day, and displays the results. Although, it was operational, out of the blue we had a 500 internal server error and the message of the user was just sent to my Azure web service, without responding back.

## Expected Behavior
The expected result was the response the the messenger user with the choices as show below at Expected Behavior

## Actual Results
![image](https://user-images.githubusercontent.com/14348315/30437482-678cb8cc-9977-11e7-9460-d38e3959674c.png)

![image](https://user-images.githubusercontent.com/14348315/30437600-b000443e-9977-11e7-96de-bbbaf39f4847.png)

## Expected Behavior
![image](https://user-images.githubusercontent.com/14348315/30437398-2febf630-9977-11e7-9098-bb0fe83e06de.png)

**Comment by JasonSowers** [comment]
What SDK version are you using? It looks like you put in the .NET version in your form.

**Comment by advl03** [comment]
Could you please check if this is the same issue as this one?
https://github.com/Microsoft/BotBuilder/issues/3466

**Comment by KwstasBol** [comment]
yeah i checked it i hope we find a solution soon! 4.6.1 is the version i guess, as i saw...

**Comment by EricDahlvang** [comment]
@KwstasBol  are you still experiencing this issue?

**Comment by KwstasBol** [comment]
Yes @EricDahlvang still the same httphandler-pipeline error..

**Comment by KwstasBol** [comment]
I am closing the issue, because the solution came. I had to change the Azure app service to bot service which is merged with the bot framework developer envinroment.

**Comment by iamthewall** [comment]
Hi @KwstasBol . Could you share some detailed insights of what was happening with your bot and how you fix it? I'm facing a similar issue.

**Comment by KwstasBol** [comment]
Yes @iamthewall. Well all of the sudden after being one year online, the bot stopped. This event was due to my using web app at Azure and because of using the older version of BotFramework SDK. Eventually i made the transition to BotService which you can have for free with an Azure subscription and change the code of your app to the current version of the SDK. To put it in a nutshell, never ever again have a bot solution on a web app,only bot service. For more,inform me.

**Comment by savahmel** [comment]
@KwstasBol Bot service, you mean Azure Functions solution?

**Comment by KwstasBol** [comment]
![image](https://user-images.githubusercontent.com/14348315/31300464-81dfe0be-aafc-11e7-917f-0e28c4df5529.png)
This one, but you must make a subscription firstly. It is said that it is free,but it charged me 1 euro. Nevertheless, it is worth it.

**Comment by savahmel** [comment]
Thanks

**Comment by soloveyalex** [comment]
@KwstasBol I have the same issue. Tried to migrate my existing bot from web app to bot service. However,  I noticed that upon a creation of Bot Service it requires to create a new bot only.
How did you manage to migrate existing bot to the Bot Service?

**Comment by KwstasBol** [comment]
Well, i was not the one migrating the new one,because i do not expertise in C# issues, but there were really small changes. However, i recommend you to consider in developing in Node.js,because it is really fast and more understandable to my opinion and if you have whichever problem in that platfom i could really help you!. So, i could maybe help you if you could provide me with some code, but i dont promise anything as long as it is written in C# :)

**Comment by soloveyalex** [comment]
@KwstasBol It's not a question of programming platform and language. 
The problem is when you create Azure Bot Service it creates a NEW bot. With NEW name and MicrosoftAppID. I see no way to tell it "please create Azure Bot Service for already registered and configured bot"

In this perspective my question was regarding your statement "Eventually i made the transition to BotService". I'm wondering to know how to "transit" EXISTING bot rather then create a NEW one.

So, how did you do that? Or, you didn't and just did register a new one with the same code?

**Comment by KwstasBol** [comment]
Okay.Firstly  i used the new MicrosoftAppId, there is no problem in using this. Nevertheless, you are right about not having the option of already registered bot. Secondly, certainly the new name is needed everywhere.The facebook keys of course stay the same.Last but not least, the answer to your last question,is that i did a new with the same code.That's all,nothing to worry about.(so facebook data remains, bot framework data changes and becomes new). Hope it helps...
