### ISSUE TITLE
My bot in Skype shows message is diabled

### ISSUE THREAD

**Issue by subeed76** [Microsoft/BotBuilder#3465]
## Bot Info 
* Bot handle: MonBOTJnJ
* App ID: 53839ba1-dd7f-4726-8ad8-d84533ed44fc
* SDK Platform: 
* SDK Version: 
* Active Channels: Skype
* Deployment Environment: 

## Issue Description

When I am trying to add BOT to Skype contact, I see the botname as appid, and I cant send message .. I see that messages has been disabled

## Reproduction Steps
1.
2.
3.

**Comment by JasonSowers** [comment]
I was just able to successfully add the bot and talk to it on skype.  How are you trying to add the bot?   I added it via think link from the portal https://join.skype.com/bot/53839ba1-dd7f-4726-8ad8-d84533ed44fc
![image](https://user-images.githubusercontent.com/6301037/30445456-daee1640-993a-11e7-83bd-54b4b5a19503.png)

**Comment by subeed76** [comment]
Thanks Jason.. the link directs me to Add the bot to my Skype contacts... once I do, I get name of the BOT as appID instead of App name.. and the messaging is disabled...  

I have attached the screenshot.. Also note that when I created my firstbot few weeks ago , I didn't face this issue... you can see that bot "SubeedBOT" in my Skype contact list in attachment


![bot issue](https://user-images.githubusercontent.com/31664236/30463344-c91ecac8-99e8-11e7-9815-9e94a52beb33.JPG)

**Comment by subeed76** [comment]
ok.. I found that BOTs are working fine on my mobile... the above issue is with Skype on windows machine.... what could have gone wrong?

**Comment by JasonSowers** [comment]
Are you still having this issue? I am still able to use your bot without any issues.

**Comment by EricDahlvang** [comment]
@subeed76 
What version of skype are you using?

![image](https://user-images.githubusercontent.com/11055362/30619254-5db8bc76-9d53-11e7-9e81-a83b94f6b0ad.png)
