### ISSUE TITLE
500 server error using facebook

### ISSUE THREAD

**Issue by tpowellmeto** [Microsoft/BotBuilder#3466]
## Bot Info 
* Bot handle: informatics-lab-sol
* App ID: c0dd83ca-0370-4310-96a6-c418c924870f
* SDK Platform: Node.js
* SDK Version: 3.9.1
* Active Channels: Facebook
* Deployment Environment: aws ec2

## Issue Description
My service is returning 500s constantly

Error: Request to 'https://state.botframework.com/v3/botstate/facebook/users/1420943404688109' failed: [500] Internal Server Error

**Comment by jeffhee** [comment]
I am experiencing the same thing. Is there a status page somewhere?

**Comment by jacobtomlinson** [comment]
I found this page, but it shows the service as being up.

https://azure.microsoft.com/en-gb/status/

**Comment by advl03** [comment]
Same error 500 here. Like 3 hours ago, we started to have this kind of errors in both our development (own openstack servers) and production environments (azure North EU).
Azure services status page does not show any alarm.
Any help is appreciated...

**Comment by EricDahlvang** [comment]
Thanks for reporting this.  We will investigate, and report back our findings asap.  

(Note, the azure status page does not show Bot Framework connector status.  We are working on a status page.)

**Comment by KwstasBol** [comment]
the service is up, but it keeps having the same issue.. Thanks Eric,hope we find it soon,because it was all of the sudden without any change..

**Comment by tpowellmeto** [comment]
can you give us any more information?

**Comment by yichengsun** [comment]
Would appreciate an update soon, as we have a release slated for later this afternoon that is being impacted...

**Comment by edgarw19** [comment]
I have the exact same issue and this is a serious, high priority bug for our users.

I went into chatconnector.js and printed the body response back from Microsoft, and I get this

{ error: 
    { code: 'ServiceError',
      message: 'Null properties cannot be encrypted. Please assign a default value to the property if you wish to encrypt it.' } }
 Error: Request to 'https://state.botframework.com/v3/botstate/facebook/users/2014981635209074' failed: [500] Internal Server Error
 at Request._callback (/app/node_modules/botbuilder/lib/bots/ChatConnector.js:514:46)
    at Request.self.callback (/app/node_modules/request/request.js:188:22)
     at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/app/node_modules/request/request.js:1171:10)
     at emitOne (events.js:96:13)
     at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:292:16)
     at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
     at endReadableNT (_stream_readable.js:974:12)
     at _combinedTickCallback (internal/process/next_tick.js:80:11)
     at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by dan-cohn** [comment]
Likewise here. We have a user study and demo this afternoon. This is a very serious problem.

**Comment by JasonSowers** [comment]
We are actively investigating this.

**Comment by jphgross** [comment]
We're also experiencing the issue and its having a fairly large impact to us.

**Comment by sonnenhaft** [comment]
ddos? Big brother, speak to us. ETA? 
Seems like SMS chat works, slack should not.
Also guess it is on FB and Slack side.

**Comment by sagarpomal** [comment]
Looks like it has started working.

**Comment by advl03** [comment]
Yes, confirmed. My dev and prod bots are working again! Thanks!

**Comment by tombarton** [comment]
We were experiencing similar issues earlier; looks like things have settled now. Is there any change of getting a status page anytime soon?

**Comment by edgarw19** [comment]
Oh wow, thank goodness, up and running 1.5 hours before our launch. Hopefully it's stable

**Comment by tpowellmeto** [comment]
Yes, thank you! Back up and running now. Any information on what caused this?

**Comment by JasonSowers** [comment]
There was an issue with null values in bot properties.  We have done a rollback to fix the issue and are working on a hot fix to correct it permanently.

**Comment by EricDahlvang** [comment]
Thank you everyone, for reporting this to us.  Please open a new issue if you run into any new problems.

**Comment by EricDahlvang** [comment]
Everyone please note:  "By default, the Bot Framework SDK for .NET stores state data using the Bot Framework State service, which is intended for prototyping only and is not designed for use by bots in a production environment."  https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-state

Please consider using the Azure Extensions, or implementing a custom state client: https://blog.botframework.com/2017/07/18/saving-state-azure-extensions/  

**Note: Bots using a custom state client did not experience these issues on September 15th.**

**Comment by dan-cohn** [comment]
You mention the .NET SDK, but this issue affected my Node.js client as well.

I'm a little surprised to hear that the State Service isn't meant for production.  This is one of the best features of the Bot Framework.  It significantly speeds up bot development and maintenance.  Without it everyone has to implement their own solutions, many of which are likely to incur an operational cost on top of the added dev costs.  Have you considered hardening the service so it's production-ready and perhaps even charging usage fees?

**Comment by EricDahlvang** [comment]
"It significantly speeds up bot development and maintenance."  <-- yes, there are definitely benefits to the default connector state service.  However, it is also relatively simple to include the Azure Extensions and use CosmosDb, Sql Server, or Azure Table Storage in either Node or .NET.  https://github.com/Microsoft/BotBuilder-Azure 

There are Nuget and NPM packages: 
https://www.nuget.org/packages/Microsoft.Bot.Builder.Azure/ 
https://www.npmjs.com/package/botbuilder-azure

I do not know the plans for the current state service.

**Comment by KwstasBol** [comment]
?Thank you for the crucial information. I tried using bot service and it worked, i totally recommend it.

________________________________
Από: Eric Dahlvang <notifications@github.com>
Στάλθηκε: Τρίτη, 19 Σεπτεμβρίου 2017 9:31 πμ
Προς: Microsoft/BotBuilder
Κοιν.: Bolotis Konstantinos; Comment
Θέμα: Re: [Microsoft/BotBuilder] 500 server error using facebook (#3466)


"It significantly speeds up bot development and maintenance." <-- yes, there are definitely benefits to the default connector state service. However, it is also relatively simple to include the Azure Extensions and use CosmosDb, Sql Server, or Azure Table Storage in either Node or .NET. https://github.com/Microsoft/BotBuilder-Azure

There are Nuget and NPM packages:
https://www.nuget.org/packages/Microsoft.Bot.Builder.Azure/
https://www.npmjs.com/package/botbuilder-azure

I do not know the plans for the current state service.

-

**Comment by KwstasBol** [comment]
So, i guess that every bot framework solution already stored in the old way has to change to bot service? I am not capable of understanding this part of the problem.

**Comment by advl03** [comment]
Please confirm:
1) if node.js based bots must also implement a custom state client for storing conversation and user data.
2) if we need to remove every reference to session.userData, session.privateConversationData and son on in order to future proof our bots

Thanks!

**Comment by tombarton** [comment]
@advl03 yes, Node.js based Bots should be using external state storage, as advised in the bot framework documentation. You can then continue to use session based storage (e.g. session.privateConversationData) as normal.

**Comment by EricDahlvang** [comment]
@advl03 

1) node.js bots should use one of the Azure Extensions (documentdb, azure table storage, or sql: coming soon), or implement your own state client (not that difficult).  Also: this is not just for conversation and user data, but dialog data (like in a waterfall in node, or formflow in .net) are also stored in the state client.

2) no need to remove session.userData, etc: if the azure extensions implementation are used.  Azure Extensions will substitute the default.
