### ISSUE TITLE
TS types: IChatConnectorSettings exported data definitions is different from the source file

### ISSUE THREAD

**Issue by peterblazejewicz** [Microsoft/BotBuilder#3467]
Exported interface:
```ts
/** Options used to initialize a ChatConnector instance. */
export interface IChatConnectorSettings {
    /** The bots App ID assigned in the Bot Framework portal. */
    appId?: string;

    /** The bots App Password assigned in the Bot Framework Portal. */
    appPassword?: string;

    /** If true the bots userData, privateConversationData, and conversationData will be gzipped prior to writing to storage. */
    gzipData?: boolean;    
}
```
https://github.com/Microsoft/BotBuilder/blob/6786a6dec1556f702f61e22b06e2e4ad0f5a05ea/Node/core/lib/botbuilder.d.ts#L1161
Actual:
```ts
export interface IChatConnectorSettings {
    appId?: string;
    appPassword?: string;
    gzipData?: boolean;
    endpoint?: IChatConnectorEndpoint;
    stateEndpoint?: string;
    openIdMetadata?: string;
}
```
https://github.com/Microsoft/BotBuilder/blob/e133266e9754b3f0bd8b992e078237ee7bcb963a/Node/core/src/bots/ChatConnector.ts#L55

The most problematic point in this is that official sample from Azure Portal uses source definition, so compilation fails.

Thanks!

```txt
version: 3.9.1
```

**Comment by JasonSowers** [comment]
@Stevenic  any thoughts?

**Comment by stevengum97** [comment]
@peterblazejewicz, The missing definitions were added today and are available in the latest release, [v.3.10.1](https://www.npmjs.com/package/botbuilder). 

Ping one of us if this didn't fix your issue. Closing issue.
