### ISSUE TITLE
GatewayTimeout Error in Facebook working on others

### ISSUE THREAD

**Issue by hardikchoudhary** [Microsoft/BotBuilder#3468]
I have been using node js to make bot
but some time it works and some time gateway error is there
i dont know what is this error for
at same time its working on skype or emulator

This is not a good thing to make commercial product
what we can do.......

**Comment by EricDahlvang** [comment]
Using the bot builder azure extensions for state, or implementing a custom state client, makes a significant difference. The default state service is meant for prototyping only.

https://blog.botframework.com/2017/07/18/saving-state-azure-extensions/

**Comment by hardikchoudhary** [comment]
Actually I am using node js template

and I have make web app with shared price template what i need to can you please tell

and why its not working some times

@EricDahlvang @nwhitmont  @vboctor  @maxpert @bterlson

**Comment by EricDahlvang** [comment]
Hi @hardikchoudhary 

Storing conversation history is provided by the azure extensions. However, Azure Extensions also provide custom state storage: providing the ability to override the default state storage.  Please see here: https://github.com/Microsoft/BotBuilder/blob/50bf16bb52231e1521703b106b16df99de361b2e/Node/core/lib/bots/ChatConnector.js#L33  The Bot Builder node library defaults to using 'https://state.botframework.com' for UserData, ConversationData and PrivateConversationData.  

We have seen increased gateway timeout exceptions for bots that are using the default state client.  This is why I am suggesting that you use Azure Extensions, or implement your own State Client.

I hope this helps.

**Comment by EricDahlvang** [comment]
If you run into other problems, please open a new issue.
