### ISSUE TITLE
Skype shows ASCII codes instead of special characters

### ISSUE THREAD

**Issue by tringtring** [Microsoft/BotBuilder#3469]
## Bot Info 
* Bot handle: GNOME
* App ID: b34db60d-6466-42e1-bb37-3281cc8b6c27
* SDK Platform: .NET
* SDK Version:  3.8.5
* Active Channels: Skype
* Deployment Environment: Azure

## Issue Description
My bot is making use of QNA maker API and is providing answers appropriately. Problem is that the special characters like & , < , > in the QNA maker answers appear as HTML codes in the Skype chat. So & shows as &amp; and so on.

Could you please help?

## Code Example
var response = QNAMakerHelper.GetQNAResponse(userFeedbackFAQs.UserQuestion);
                if (response.Score > 50)
                {
                    await context.PostAsync(response.Answer);

                }

## Expected Behavior
Special characters should be displayed in the chat in place of HTML encodes. In short & should appear as &.

## Actual Results
![image](https://user-images.githubusercontent.com/12736311/30470419-47dc20e4-9a12-11e7-87b9-5508a5addf9e.png)

**Comment by burakkarakus** [comment]
How did you resolve this problem?
