### ISSUE TITLE
[Skype] - Cannot get Sender Name and Topic Name when add Bot to Skype Group

### ISSUE THREAD

**Issue by chuotnhat1985** [Microsoft/BotBuilder#3470]
## Bot Info 
* Bot handle: 
* App ID: d932e635-1cf6-4466-b30a-916c41754b33
* SDK Platform:  .NET
* SDK Version: 3.9.0.0
* Active Channels: Skype
* Deployment Environment: other

## Issue Description
As titled. I want to save the conversation data into the database. But I cannot get sender name and topic name when Bot is added to Skype Group.

## Code Example
```cs
            if (activity.MembersAdded.Any(x => x.Id == message.Recipient.Id))
            {
                var conversationModel = new ConversationModel
                {
                    ChannelId = activity.ChannelId,
                    Id = activity.Conversation.Id,
                    Name = activity.TopicName,
                    Recipient = new ChannelAccountModel
                    {
                        Id = activity.Recipient.Id,
                        Name = activity.Recipient.Name
                    },
                    Sender = new ChannelAccountModel
                    {
                        Id = activity.From.Id,
                        Name = activity.From.Name
                    },
                    IsGroup = activity.Conversation.IsGroup ?? false,
                    ServiceUrl = new Uri(activity.ServiceUrl)
                };
            }
```
## Reproduction Steps
1.
2.
3.

## Expected Behavior
Get the Topic name and From name

## Actual Results
Empty. Just got the Conversation Id and From Id

**Comment by JasonSowers** [comment]
I have confirmed this behavior, looking into if this is intentional or if this is a bug.  Thanks for reporting this.

**Comment by cuttinger** [comment]
I also encountered this issue. when I call client.Conversations.GetConversationMembersAsync() to get SKYPE group member information I just get the correct user ids and empty user names.  this method works well on GROUPME.

**Comment by loopthrough** [comment]
@JasonSowers any progress on this topic? I have the same issue still with the REST approach.
Did you figure out if it is intentional or is it planned for fixing. In the emulator I receive both id and the name, through Skype not.

Thanks.

**Comment by loopthrough** [comment]
I would assume this is intentional. I see, general approach is not to share any data apart from direct conversation with a bot. In this case, contact names in a group can potentially provide to a bot the names of participants which are not in the bot's contact list. In the 1-1 interactions with a bot all data is present. @cuttinger I moved to obtaining this data from the contactRelationshipUpdate when bot gets added as a contact.
