### ISSUE TITLE
why need to save user address data

### ISSUE THREAD

**Issue by ficharts** [Microsoft/BotBuilder#3471]
we use directline to connect to our im server. when to remind user later ,we must send an event first to bot(we get address from event message), then can send message to user.

we what to save every user address, is there other Method? for example just save cannel id or address id, then send remind message with this address and user id for im.

**Comment by JasonSowers** [comment]
What have you tried?  What worked?  What didn't? Also this info is helpful, please fill it out:

* Bot handle: 
* App ID: 
* SDK Platform: 
* SDK Version: 
* Active Channels: 
* Deployment Environment:

**Comment by ficharts** [comment]
Bot handle: https://webotserverhk.webot.p.azurewebsites.net/api/messages
App ID: bbd62af3-47ba-4d0f-9c0f-978ed3d14253
SDK Platform: nodejs
SDK Version: new
Active Channels: directline
Deployment Environment: vscode

**Comment by nwhitmont** [comment]
Yes, you need to save the user's address aka Conversation Reference, in order to know where to send the messages later.  Otherwise, your bot wouldn't know where to send the message.
