### ISSUE TITLE
Issue while performing fallback with Chain.ContinueWith method

### ISSUE THREAD

**Issue by anujupmanyu** [Microsoft/BotBuilder#3474]
```cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Microsoft.Bot.Builder.Dialogs;
using System.Text.RegularExpressions;
using Microsoft.Bot.Builder.FormFlow;
using DialogBOT.ITStore;
using System.Threading.Tasks;

namespace DialogBOT.Dialogs
{
    public class ITStoreDialog
    {
        public static readonly IDialog<string> dialog = Chain.PostToChain()
            .Select(msg => msg.Text)
            .Switch(
            new RegexCase<IDialog<String>>(new Regex("^hi", RegexOptions.IgnoreCase), (cotext, text) =>
            {

                return Chain.ContinueWith(new GreetingDialog(), AfterGreetingContinuation);
            }),
             new DefaultCase<string, IDialog<String>>((context, text) =>

             {
                 return Chain.ContinueWith(FormDialog.FromForm(RoomReservation.BuildForm, FormOptions.PromptInStart), AfterGreetingContinuation);
             }))
            .Unwrap()
            .PostToUser();

          private async static Task<IDialog<string>> AfterGreetingContinuation(IBotContext context, IAwaitable<object> item)
          { 
            var token = await item;
            var name = "user";
            context.UserData.TryGetValue<string>("Name", out name);
            return Chain.Return($"Thank you for using IT Store Bot: {name}");

          }

    }

}
```
![image](https://user-images.githubusercontent.com/30819381/30530295-33b7baee-9c63-11e7-9c73-b862aa9c8343.png)

Please help

**Comment by JasonSowers** [comment]
What is your use case here?  What are you trying to accomplish and why?

**Comment by anujupmanyu** [comment]
Hey Jason,

I am trying to use Form Flow using dialog, I have code it to fallback to another dialog when user type " Hi ". Currently it's giving me error in chain.continuation method.

Really appreciate your help

**Comment by anujupmanyu** [comment]
can anyone help me please

**Comment by JasonSowers** [comment]
Can you please post your complete code in a repo, or post your `GreetingDialog` Code here 
  
when Iimplemented `GreetingDialog`  like this it did not give me an compiler error. 
```cs
    internal class GreetingDialog : IDialog<object>
    {
        public Task StartAsync(IDialogContext context)
        {
            throw new System.NotImplementedException();
        }
    }
```

![image](https://user-images.githubusercontent.com/6301037/30659701-7aa52ad6-9df3-11e7-9f0e-6e5bdc9c7320.png)

**Comment by anujupmanyu** [comment]
I have created 2 dialogs
1. Greetings.cs dialog 2 ITStoredialog.cs which fall back to each other.

Sharing both with you.

1. Greeting.cs

using Microsoft.Bot.Builder.Dialogs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Threading.Tasks;
using Microsoft.Bot.Connector;

namespace DialogBOT.Dialogs
{
    [Serializable]
    public class GreetingDialog : ITStoreDialog
    {
        public async Task StartAsync(IDialogContext context)
        {
            await context.PostAsync("Hello, Welcome to Hatch AskIT BOT. For now my current scope is to help you with queries related to IT store.");
            await Respond(context);

            context.Wait(MessageRecievedAsync);
        }

        private static async Task Respond(IDialogContext context)
        {
            var userName = String.Empty;
            context.UserData.TryGetValue<string>("Name", out userName);
            if (string.IsNullOrEmpty(userName))
            {
                await context.PostAsync("What is your name?");
                context.UserData.SetValue<bool>("GetName", true);

            }
            else
            {
                await context.PostAsync(String.Format("Hi {0}. How can I help you with ITStore today?", userName));

            }

        }

        public async Task MessageRecievedAsync(IDialogContext context, IAwaitable<IMessageActivity> argument)
        {
            var message = await argument;
            var userName = String.Empty;
            var getName = false;

            context.UserData.TryGetValue<string>("Name", out userName);
            context.UserData.TryGetValue<bool>("GetName", out getName);

            if (getName)
            {
                userName = message.Text;
                context.UserData.SetValue<string>("Name", userName);
                context.UserData.SetValue<bool>("GetName", false);
            }

            await Respond(context);
            context.Done(message);
          
        }

    }
}

2. ITStoreDialog.cs

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Microsoft.Bot.Builder.Dialogs;
using System.Text.RegularExpressions;
using Microsoft.Bot.Builder.FormFlow;
using DialogBOT.ITStore;
using System.Threading.Tasks;

namespace DialogBOT.Dialogs
{
    public class ITStoreDialog
    {
        public static readonly IDialog<string> dialog = Chain.PostToChain()
            .Select(msg => msg.Text)
            .Switch(
            new RegexCase<IDialog<String>>(new Regex("^hi", RegexOptions.IgnoreCase), (cotext, text) =>
            {

                return Chain.ContinueWith(new GreetingDialog(), AfterGreetingContinuation);

            }),
             new DefaultCase<string, IDialog<String>>((context, text) =>

             {
                 return Chain.ContinueWith(FormDialog.FromForm(RoomReservation.BuildForm, FormOptions.PromptInStart), AfterGreetingContinuation);
             }))
         .Unwrap()
         .PostToUser();

          private async static Task<IDialog<string>> AfterGreetingContinuation(IBotContext context, IAwaitable<object> item)
          { 
            var token = await item;
            var name = "user";
            context.UserData.TryGetValue<string>("Name", out name);
            return Chain.Return($"Thank you for using IT Store Bot: {name}");

          }

    }

}

I have created another one called roomreservation for dialog box

using Microsoft.Bot.Builder.FormFlow;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DialogBOT.ITStore
{
    public enum Options
    {
        Status,
        NewRequest,
    }

    public enum Softwareoptions
    {
        Application,
        Office
    }

    [Serializable]

    public class RoomReservation
    {
        public Options? order;
        public int? Numberoforders;
        public int? NumberofSoftware;
        public List<Softwareoptions> Software;

        public static IForm<RoomReservation> BuildForm()
        {

            return new FormBuilder<RoomReservation>()

                .Message("Welcome to IT Store BOT! Please make your selection")
                .Build();

        }

        internal static IForm<object> Buildform()
        {
            throw new NotImplementedException();
        }
    }
}

Sorry, but I am unable to find where i can upload the files. 
Thanks for looking into this

**Comment by JasonSowers** [comment]
Thanks, I was able to reproduce with this code.  I was also able to find the problem I think.
  
When I made  `public class ITStoreDialog` into `public class ITStoreDialog : IDialog`  and added the  `public Task StartAsync(IDialogContext context)` method required for the interface it seemed to clear up the problem

**Comment by anujupmanyu** [comment]
thanks a ton for looking in the issue,

i have amend the code as suggested, error gone

but getting an error while compiling

![compile error](https://user-images.githubusercontent.com/30819381/30737505-839e6abe-9fa4-11e7-8302-44c5e1a8aba6.PNG)
![greetings](https://user-images.githubusercontent.com/30819381/30737509-8760f13a-9fa4-11e7-9812-878c431427cb.PNG)

IT Store Dialog BOT

namespace DialogBOT.Dialogs
{
    public class ITStoreDialog : IDialog

    {
        public static readonly IDialog<string> dialog = Chain.PostToChain()
            .Select(msg => msg.Text)
            .Switch(
            new RegexCase<IDialog<String>>(new Regex("^hi", RegexOptions.IgnoreCase), (cotext, text) =>
            {

                return Chain.ContinueWith(new GreetingDialog(), AfterGreetingContinuation);

            }),
             new DefaultCase<string, IDialog<String>>((context, text) =>

             {
                 return Chain.ContinueWith(FormDialog.FromForm(RoomReservation.BuildForm, FormOptions.PromptInStart), AfterGreetingContinuation);
             }))
         .Unwrap()
         .PostToUser();

          private async static Task<IDialog<string>> AfterGreetingContinuation(IBotContext context, IAwaitable<object> item)
          { 
            var token = await item;
            var name = "user";
            context.UserData.TryGetValue<string>("Name", out name);
            return Chain.Return($"Thank you for using IT Store Bot: {name}");

          }

        public Task StartAsync(IDialogContext context)
        {
            throw new NotImplementedException();
        }
    }

}

**Comment by anujupmanyu** [comment]
![image](https://user-images.githubusercontent.com/30819381/30737669-0d21842e-9fa5-11e7-903c-177fa539554c.png)

Thanks for looking in

**Comment by JasonSowers** [comment]
You have to implement that method 
generally it is implemented like this:
```cs
        public Task StartAsync(IDialogContext context)
        {
            context.Wait(MessageReceivedAsync);
            return Task.CompletedTask;
        }
```
If you do it this way you will also need to implement the `MessageReceivedAsync` message.  this is probably where you want to call your switch statement or whatever else you want to dialog to do.
```cs
        private async Task MessageReceivedAsync(IDialogContext context, IAwaitable<object> result)
        {
                    
            // calculate something for us to return
            int length = (activity.Text ?? string.Empty).Length;
            
            // return our reply to the user
            await context.PostAsync($"Hello {name} Topic is {tname}");

            context.Wait(MessageReceivedAsync);
        }
```

**Comment by anujupmanyu** [comment]
Hey Jason,

Thanks for sharing update.

I am still not able to fall back to my switch, can you help me with the whole code.

I want to use QNA but if user says "status" then it will prompt dialog boxes like "Order" etc, for rest of other, it fall back for QNA dialog


namespace AskIT.Dialogs
{
    [Serializable]
    public class RootDialog : IDialog<object>
    {
        public Task StartAsync(IDialogContext context)
        {
            context.Wait(MessageReceivedAsync);

            return Task.CompletedTask;
        }

        private async Task MessageReceivedAsync(IDialogContext context, IAwaitable<object> result)
        {
            var activity = await result as Activity;

            // calculate something for us to return
            int length = (activity.Text ?? string.Empty).Length;

            // return our reply to the user
            await context.PostAsync($"You sent {activity.Text} which was {length} characters");

            context.Wait(MessageReceivedAsync);
        }
    }
}

**Comment by JasonSowers** [comment]
```cs
        private async Task MessageReceivedAsync(IDialogContext context, IAwaitable<object> result)
        {                    
              //you need to put your own code/logic here
              context.Wait(MessageReceivedAsync);
        }
```
