### ISSUE TITLE
 Chat Bot Platform like Chatfuel

### ISSUE THREAD

**Issue by VishalWaman** [Microsoft/BotBuilder#3475]
We are looking for Tech Stack for developing a Chat Bot Platform like Chatfuel, 
Can anyone help in suggesting Tech Stack for this, or some package ?
How can we use MS Bot framework for this ?

**Comment by JasonSowers** [comment]
This is outside of the scope of this forum, please post this question on StackOverflow.
  
Here are some links to get you started:
https://www.codeproject.com/Articles/1110201/Creating-A-Facebook-Bot-Using-Microsoft-Bot-Framew
https://docs.microsoft.com/en-us/bot-framework/channel-connect-facebook
