### ISSUE TITLE
[Skype For Business] Skype for business bot picture configuration issue 

### ISSUE THREAD

**Issue by mbettan** [Microsoft/BotBuilder#3481]
## Bot Info ithelpchatbot
* Bot handle: 
* App ID: 
* SDK Platform: .NET
* SDK Version: C# with Luis
* Active Channels: Skype for business
* Deployment Environment: Azure Bot Service

## Issue Description
I would like to configure a picture in the Skype for business bot to display for the end users. I configured an image in the bot active directory, enabled exchange license and configured the image again but without success 

Any workaround to enable this image ? Can we switch this Application user to normal user to configure an image?

## Reproduction Steps
1.
2.
3.

**Comment by mbettan** [comment]
Any ideas how to solve this ?

I escalate to Office 365 but they push back to Azure support..

**Comment by JasonSowers** [comment]
I will reach out to the sfb team for you today

**Comment by mbettan** [comment]
Did you get an update from them?

**Comment by JasonSowers** [comment]
No response yet, I'll poke again today.

**Comment by mbettan** [comment]
Thank you @JasonSowers

**Comment by mrgorzny** [comment]
Any news about this yet? We're experiencing the same problem. It's not vital but it's frustrating because there are some articles clearly showing screenshots from Skype for business where both user thumbnail and user status are clearly shown. (E.g. https://chatbotsmagazine.com/enterprise-chatbots-on-skype-for-business-af635f346f5c)

**Comment by vishwacsena** [comment]
@EricDahlvang can we please add pointers to relevant docs and resolve?

**Comment by EricDahlvang** [comment]
> The Bot Framework Skype for Business Channel is in Developer Preview and does not support bot display pictures at the current time.

From here: https://docs.microsoft.com/en-us/skype-sdk/skype-for-business-bot-framework/docs/bot-common-errors

Bots on Skype for Business are still in Preview.

**Comment by hufedebe** [comment]
https://stackoverflow.com/questions/44451476/bot-frameworkskype-for-business-how-can-i-set-a-bots-icon-picture-in-a-chat
