### ISSUE TITLE
 GIF to KiK channel

### ISSUE THREAD

**Issue by VishalWaman** [Microsoft/BotBuilder#3486]
We have been trying to send GIF to KiK chat bot.

We have sent Video Card message with GIF link and Autoplay + Loop set to true

But this dont work if user has set to not auto download Videos..

Can you suggest help on this.

**Comment by JasonSowers** [comment]
have you tried an [Animation Card](https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.connector.animationcard?view=botbuilder-3.8)?  I'm not sure it will work, but it also seems if someone has auto-download disabled, what you are seeing completely working as intended by KiK don't you agree?
