### ISSUE TITLE
Get the information of an activity

### ISSUE THREAD

**Issue by bilby91** [Microsoft/BotBuilder#3487]
## Bot Info 
* Bot handle: suttna
* App ID: 220dc633-1f3d-4346-ad61-3805e88be8c0
* SDK Platform: Node
* SDK Version: 3.9
* Active Channels: MS Teams
* Deployment Environment: ngrok, other

## Issue Description
We are trying to implement an update feature in our bot. Users are sending information to the bot and have a fixed period of time were they can edit the information. We want to verify if the information was updated. Since teams doesn't forward the edit events (https://stackoverflow.com/questions/40976069/microsoft-bot-framework-message-edit-event) we thought that it would be possible to query for the current data of the activity using the message id. We verified in the "Build a bot" API reference that is not possible at the moment.

Are their any plans to support this ? Maybe an undocumented endpoint ? Any workaround ?

Thanks!

**Comment by bilby91** [comment]
@santiagodoldan

**Comment by stevengum97** [comment]
Looking into this, but to my knowledge we currently don't have recommended workarounds or plans. Touching on the surface layer of this, I would probably just set up a webhook to track users' edits to their messages.

**Comment by bilby91** [comment]
@stevengum97 `I would probably just set up a webhook to track users' edits to their messages.` is that possible now ?

**Comment by stevengum97** [comment]
I know they have an Incoming Webhook setup... @billbliss, can you comment on any Outgoing Webhooks, if available?

**Comment by bilby91** [comment]
@stevengum97 Yep, if we can configure an outgoing webhook when a message is edited our use case will be the optimal one because we can do the updates of the content in real time.

**Comment by nwhitmont** [comment]
There is no "outgoing" webhook option at this time, only "incoming".
