### ISSUE TITLE
Not able to connect my Bot from skype and Webchat.

### ISSUE THREAD

**Issue by mosin76** [Microsoft/BotBuilder#3489]
## Bot Info 
* Bot handle: QnA_Moz 
* App ID: b2bc75ea-2a39-4263-89bc-ec62804ff18f
* SDK Platform: .NET
* SDK Version: 
* Active Channels: <!-- Skype, WebChat>
* Deployment Environment: Azure Web App

## Issue Description
Not able to connect my Bot from skype and Webchat.

The bot is to Skype and in My Client application for Webchat. But not receiving any Greeting message
from bot.which is not received in Skype and Webchat.

Please help me to get this sorted

**Comment by JasonSowers** [comment]
There is some sort of error with your bot, have you tried debugging locally with ngrok? https://docs.microsoft.com/en-us/bot-framework/debug-bots-emulator

![image](https://user-images.githubusercontent.com/6301037/30653113-0bab2a04-9ddf-11e7-9a30-cc6e59426933.png)
![image](https://user-images.githubusercontent.com/6301037/30653145-280b48aa-9ddf-11e7-8141-a925a0a8fede.png)

**Comment by mosin76** [comment]
Already done testing my hosted API with Emulator and ngrok. It works perfectly fine here. Is this something to do something with AI integrationg with Skype?

**Comment by JasonSowers** [comment]
What version of the botbuilder SDK are you using?

**Comment by fanidamj** [comment]
Closing the issue assuming it as resolved. Feel free to reopen if you questions or comments.
