### ISSUE TITLE
[Performance] Slow response and timeouts when published to Southeast Australia

### ISSUE THREAD

**Issue by LTsLlama** [Microsoft/BotBuilder#3494]
## Bot Info 
* Bot handle: livebot_dev
* App ID: 331e99c1-42d3-49bc-ba05-316c38ca5332
* SDK Platform: .NET
* SDK Version: 3.9.1.0
* Active Channels: WebChat, Direct Line, Teams, Skype
* Deployment Environment: Azure App Service

## Issue Description
We have a bot environment with the messaging endpoint in Southeast Australia and LUIS in Southeast Asia, but are getting worse latency and a lot of timeouts from an Australian Web Chat than when everything was published in the West US. We where expecting an improvement in latency, but this is not the case.

The only explanation we can think of is that the Bot Framework is not available in Australia so all messages go to the US first, then the messaging endpoint in Aus and then LUIS in Asia.

## Questions
1. In which regions is the bot framework currently available?
2. How can we improve the performance in Australia and other regions?

**Comment by DL-LiveTiles** [comment]
We deployed the same bot messaging endpoint and LUIS model to East US2 and the performance is great from a web chat in the east US, confirming that the Bot Framework is the bottleneck in Australia.

**Comment by nicksav** [comment]
Not sure if the same with East AU data center.  This is the remote dependency tree for one Post activity.
![image](https://user-images.githubusercontent.com/9266365/32051354-a1b13910-ba97-11e7-962b-66cb7ae46d32.png)

In average response takes 8-9 secs which is a lot. Dapper + SQL takes less than 25ms to process and save logs and conversations.

**Comment by fanidamj** [comment]
Can you please let us know if the issue still persists?

**Comment by JasonSowers** [comment]
please open a new issue if the issue persists
