### ISSUE TITLE
Recent 404 on updateConversation

### ISSUE THREAD

**Issue by astjohn** [Microsoft/BotBuilder#3495]
## Bot Info 
* Bot handle: Sitata-Lifeline-dev
* App ID: 5561249c-6c2a-4865-a2ed-1f71da70ce5f
* SDK Platform: Node
* SDK Version: 3.9.1
* Active Channels: Skype, Slack, Web
* Deployment Environment: GCE 

## Issue Description
Recently, we noticed that our deployed bot became completely unresponsive after a week or two of success running on GCE. Our load balancer health_check endpoint works fine, but upon inspection via the emulator, clients joining our bot are receiving the following:
`-> POST Request to 'https://sub-domain-here.sitata.com/api/messages' failed: [404] Not Found `

We're at a total loss on why our bot would all of a sudden start responding with 404s. We can't reproduce locally. When testing 100% locally, everything works as usual. When testing via ngrok or pagekite, everything works fine. When running locally in production mode and changing the application's messaging endpoint to point toward an ngrok or pagekite address, everything works well. However, for some reason, our container on GCE is responding with 404s.

We have not changed our GCE environment be it the load balancer or the container's environment/config variables, etc.

## Code Example
```
let bot, connector, defaultDialog;

let server = restify.createServer();
  server.listen(CONFIG.PORT, function() {
    console.log("[Bot] %s listening to %s", server.name, server.url);
  });

// set up other API endpoints here
  server.get("/health_check", function(req, res, next) {
    res.send(200);
    return next();
  });

// etc...

connector = new builder.ChatConnector({
      appId: CONFIG.MICROSOFT_APP_ID,
      appPassword: CONFIG.MICROSOFT_APP_PASSWORD
    });
bot = new builder.UniversalBot(connector, defaultDialog);
    // Wire things together for the server listenting
    server.post("/api/messages", connector.listen());

// etc...

// CONFIG pulls variables from environment or falls back to dev defaults
// confirmed that MS APP ID and PASS are populated correctly on the container.

```

## Expected Behavior
Bot should not have suddenly started producing 404s on typical endpoint setup

## Actual Results
404s.

Any help is greatly appreciated as we're at a bit of a loss.

**Comment by astjohn** [comment]
@JasonSowers - Any ideas?

**Comment by astjohn** [comment]
We have also tried the very basic echo bot.

```
var restify = require("restify");
var builder = require("botbuilder");

// Setup Restify Server
var server = restify.createServer();
server.listen(process.env.port || process.env.PORT || 3978, function() {
  console.log("%s listening to %s", server.name, server.url);
});
server.get("/health_check", function(req, res, next) {
  res.send(200);
  return next();
});

// Create chat connector for communicating with the Bot Framework Service
var connector = new builder.ChatConnector({
  appId: APP_ID_HERE,
  appPassword: APP_PASS_HERE
});

// Listen for messages from users
server.post("/api/messages", connector.listen());

// Receive messages from the user and respond by echoing each message back (prefixed with 'You said:')
var bot = new builder.UniversalBot(connector, function(session) {
  session.send("You said: %s", session.message.text);
});
```

Still receiving 404 on conversationUpdate. This leads me to believe that it's something about the google cloud environment. i.e. headers being stripped out by our load balancer or firewall blocking something important...  any ideas?

**Comment by EricDahlvang** [comment]
The Bot Framework requires that the x.509v3 certificate exposed by your endpoint be current and valid. Most of the checks for "current and valid" are standard checks for server SSL certificates: the Certificate Name must match the hostname, it must not be expired, it must not be listed in a CRL, it must have the correct set of EKUs, etc.

Most importantly, your SSL certificate must chain to a root certificate authority trusted by Microsoft. The latest list of these CAs is available here: 

http://social.technet.microsoft.com/wiki/contents/articles/31634.microsoft-trusted-root-certificate-program-participants-v-2016-april.aspx

Do you have a root certificate from one of the CAs?

**Comment by astjohn** [comment]
@EricDahlvang, Thanks for getting back to me. We have a wildcard cert issued by COMODO. I do see Comodo in the list supported.

**Comment by EricDahlvang** [comment]
When you navigate to https://sub-domain-here.sitata.com/api/messages in a browser, do you receive a response?

**Comment by astjohn** [comment]
@EricDahlvang, Sent you an email.

**Comment by astjohn** [comment]
@EricDahlvang Thank you for taking the time to get back to me. This was indeed a load balancer mis-config. Sorry to waste your time. Cheers.

**Comment by EricDahlvang** [comment]
I'm glad you got it figured out!
