### ISSUE TITLE
How to access message details of conversation by bot

### ISSUE THREAD

**Issue by gomteshhatgine** [Microsoft/BotBuilder#3496]
## Bot Info 
* Bot handle: 
* App ID: 
* SDK Platform: .NET 

* SDK Version: 
* Active Channels: 
* Deployment Environment: 

## Issue Description
My question related to MS teams compose extention
I have  side loaded bot using json  manifest   containing 

` "composeExtensions": [
        {
            "botId": "39b2dead-ccab-4b8c-8c5d-*********",
            "scopes": [
                "personal",
                "team"
            ],
            "commands": [
                {
                    "id": "searchCmd",
                    "title": "Search tasks",
                    "initialRun": false,
                    "description": "Search tasks",
                    "parameters": [
                        {
                            "name": "search",
                            "title": "Search",
                            "description": "Search tasks"
                        }
                    ]
                }
            ]
        }
    ],`
 
I will explain use case step by step:

step 1:  In channel conversion when user clicks on compose extension button there is bot in compose extension popup user clicks on that bot option then it will call bot api endpoint

step 2 : When bot api endpoint is called i.e. Compose extensions come in as Invokes to bot and bot responding in activity.IsComposeExtensionQuery() event then in the response of activity.IsComposeExtensionQuery()  bot create some thumbnail cards CreateComposeExtensionResponse() method and send as response for compose extension such that,

                       `   //Compose extensions come in as Invokes.  Leverage the Teams SDK helper functions
                    if (activity.IsComposeExtensionQuery())
                    {

                        var invokeResponse = await new ComposeExtension(activity).CreateComposeExtensionResponse();

                        // Return the response
                        return Request.CreateResponse<ComposeExtensionResponse>(HttpStatusCode.OK, invokeResponse);

                    }`

Step 3 : Then user see there  are some cards in compose extension popup send by bot as compose extension query response

Step 4 : Then User clicks on one of the card from compose extension popup and send it into channel conversation

Step 5 : As the conversation is initiated by user by selecting card from compose extension popup 
Then that card is the first message of the conversion

Step 6 : There there is some discussion related to that card by users in that channel conversion but when one of the user in that channel discussion conversion ping like @mybot then **how can the bot knows which card from compose extension popup is selected for discussion ** because when on selecting the card from compose extension popup cards there is no call to bot.
 i.e. I want information of that card taken for conversion when user ping @mybot from that conversion 

please reply immediately

## Expected Behavior
Guide on Possible solutions:

1. As that card is first message(thumbnail card) of the conversation discussion,  I will get message id of that card message by **activity.Conversation.Id** but Is this possible that bot will get that card details by message Id or

2. Is there any other way to read that card message of conversation using message Id  or 

3. Is this possible to read that whole current conversation thread  by bot 

4. Is there any event when user select card from compose extension popup:  So my bot can know which card is selected for discussion among multiple cards . 

## Actual Results
Bot not able read conversation thread initiated by user

**Comment by JasonSowers** [comment]
@gomteshhatgine can you please try to rephrase your question and include a code example of what you have tried,.  It's unclear to me what you are asking.

**Comment by gomteshhatgine** [comment]
I have rephrased and added details and use-case please check

**Comment by gomteshhatgine** [comment]
I have rephrased question, added use-case details please check

**Comment by gomteshhatgine** [comment]
Any possible solutions?

**Comment by JasonSowers** [comment]
Sorry for delayed response, been waiting on more info from the MS teams people.  When I spoke with the MS Teams team, they said you are trying to use a feature that exists but is not documented yet. There was no guidance offered.  This is an MS teams specific question you may try to contact them via [this repo](https://github.com/OfficeDev/BotBuilder-MicrosoftTeams)  you might get a better response over there.

**Comment by Wajeed-msft** [comment]
@gomteshhatgine: This has been answered in [BotBuilder-MicrosoftTeams Repo](https://github.com/OfficeDev/BotBuilder-MicrosoftTeams/issues/66#issuecomment-334726374). Could you please close this?
