### ISSUE TITLE
Registering bot just hangs, no error

### ISSUE THREAD

**Issue by LlewellynJones** [Microsoft/BotBuilder#3497]
## Bot Info: Could not complete registration
* Bot handle:  
* App ID:  can't get one
* SDK Platform: .Net
* SDK Version: 3.8.3.0
* Active Channels: None yet
* Deployment Environment: Azure App Service
## Issue Description
I'm trying to register my bot on https://dev.botframework.com/bots/new and when I try to create the app id and get redirected to https://apps.dev.microsoft.com, the page just hangs with no error messages - the wheel keeps on rollin', as they say. 
The bot works fine on the emulator.

**Comment by JasonSowers** [comment]
for tracking purposes:
duplicate of https://stackoverflow.com/questions/46351690/registering-bot-framework-bot-just-hangs

**Comment by LlewellynJones** [comment]
I found out a couple of things: the app name has to be more than three characters, the bot framework registration only works in IE. I have the app id now.
