### ISSUE TITLE
Stickers with Messenger Bots

### ISSUE THREAD

**Issue by BlonDev** [Microsoft/BotBuilder#3498]
REFERRING BACK TO CLOSED ISSUE #1164    
NodeJS - Facebook Stickers

## Issue Description
I would like to include stickers in my BotBuilder Messenger app. Is it still the case that stickers are not supported by the facebook send api?

**Comment by JasonSowers** [comment]
I don't see anything about stickers here https://developers.facebook.com/docs/messenger-platform/send-api-reference

**Comment by BlonDev** [comment]
Is there any other way to use stickers in BotBuilder node.js apps?

**Comment by JasonSowers** [comment]
As of now there is not.
