### ISSUE TITLE
[.Net SDK, DirectLine] Not all files are sent through Direct Line

### ISSUE THREAD

**Issue by verdysh** [Microsoft/BotBuilder#3499]
## Bot Info 
* SDK Platform: .NET
* Active Channels: Direct Line
* Deployment Environment: local IIS

## Issue Description
Hi!

The Direct Line channel is used. When I try to send files with Cyrillic names something goes wrong and in the form of a chat is written: couldn't send retry.

If the same file is renamed Latin, the problem goes away.
Through Skype or Emulator channel there is no such problem.

The HTML page with the chat form looks like this:

```
<!DOCTYPE html>
<html>
<head>
    <link href="https://cdn.botframework.com/botframework-webchat/latest/botchat.css" rel="stylesheet" />
</head>
<body>
    <div id="bot" />
    <script src="https://cdn.botframework.com/botframework-webchat/latest/botchat.js"></script>
    <script>
      BotChat.App({
        directLine: { secret: "my_secret_from_dev_portal"},
        user: { id: 'userid_on_internal_portal', name: 'user_name', custominfo: '...' },
        resize: 'detect'
      }, document.getElementById("bot"));
    </script>
</body>
</html>
```

How to solve the problem with the Cyrillic alphabet?

**Comment by verdysh** [comment]
Guys, help ...

**Comment by JasonSowers** [comment]
Please open a new issue if you are still having trouble with this
