### ISSUE TITLE
[NodeJS/Slack] Attachment Behavior

### ISSUE THREAD

**Issue by deubaka** [Microsoft/BotBuilder#350]
I've used `Botkit` before and used attachment with my Slack messages. One thing I've noticed is the presence of an `x` in a Slack message using `setChannelData` to add attachments.

Normal Slack message with attachment via `Botkit`
<img width="390" alt="screen shot 2016-05-26 at 11 00 44" src="https://cloud.githubusercontent.com/assets/1931819/15562463/015bf0e8-2332-11e6-8a34-6f96025b3aba.png">

Slack message with attachment via `setChannelData` (notice the 'x')
<img width="347" alt="screen shot 2016-05-26 at 11 01 09" src="https://cloud.githubusercontent.com/assets/1931819/15562480/268e4f14-2332-11e6-874d-be9d337bc2d4.png">

Would this difference be from a RTM vs Webhook implementation of the messages or would this be a bug? This I think would also be similar to the difference between the 'is typing' present with `Botkit` but not on the current `botbuilder`

Thanks!

**Comment by deubaka** [comment]
Adding to this issues since its still under Slack attachments. After the recent downtime  (#490), Slack tables have also changed behavior. 

We are sending the following under `channelData` in a message,
```
"attachments": [{
		"footer": "FooBar Pte Ltd",
		"footer_icon": "https://foobar/favicon.ico",
		"ts": 1466505582.911,
		"fields": [{
			"short": true,
			"title": "Date"
		}, {
			"short": true,
			"title": "Hits"
		}, {
			"short": true,
			"value": "Friday, May 20th 2016"
		}, {
			"short": true,
			"value": "4,943"
		}, {
			"short": true,
			"value": "Thursday, May 19th 2016"
		}, {
			"short": true,
			"value": "5,184"
		}, {
			"short": true,
			"value": "Friday, May 13th 2016"
		}, {
			"short": true,
			"value": "1"
		}],
		"mrkdwn_in": ["fields"],
		"color": "#615F72"
	}]
```

This was rendered then as this,
<img width="383" alt="screen shot 2016-06-21 at 18 45 43" src="https://cloud.githubusercontent.com/assets/1931819/16227163/c0cecf22-37e1-11e6-9413-7072044c3299.png">

But after the issue (#490), it became to this,
<img width="325" alt="screen shot 2016-06-21 at 18 50 34" src="https://cloud.githubusercontent.com/assets/1931819/16227185/cf079b64-37e1-11e6-9f07-7477afb708e7.png">

Verified also using [Slack's Message Builder](https://api.slack.com/docs/formatting/builder?msg={"text"%3A"Slack Message"%2C"attachments"%3A[{"footer"%3A"FooBar Pte Ltd"%2C"footer_icon"%3A"https%3A%2F%2Ffoobar%2Ffavicon.ico"%2C"ts"%3A1466505582.911%2C"fields"%3A[{"short"%3Atrue%2C"title"%3A"Date"}%2C{"short"%3Atrue%2C"title"%3A"Hits"}%2C{"short"%3Atrue%2C"value"%3A"Friday%2C May 20th 2016"}%2C{"short"%3Atrue%2C"value"%3A"4%2C943"}%2C{"short"%3Atrue%2C"value"%3A"Thursday%2C May 19th 2016"}%2C{"short"%3Atrue%2C"value"%3A"5%2C184"}%2C{"short"%3Atrue%2C"value"%3A"Friday%2C May 13th 2016"}%2C{"short"%3Atrue%2C"value"%3A"1"}]%2C"mrkdwn_in"%3A["fields"]%2C"color"%3A"%23615F72"}]}), and its working as expected.

Any reason for the change in behavior? If yes, how do we manage this since its a standard Slack Formatting?

**Comment by v-thgratMSGit** [comment]
@LarsLiden Any thoughts?

**Comment by deubaka** [comment]
After upgrading to v3.0.0, the issues seems to be fixed. 

If v3.0.0 API upgrade was causing it, I assume it would be stable now?

Any idea on what may have caused it would be of great help, as it would really help us give something definite reply if this happens again.

Thanks!

**Comment by v-thgratMSGit** [comment]
Closing this issue since it sounds fixed. Thanks!
