### ISSUE TITLE
Integrate Azure chatbot with Twilio

### ISSUE THREAD

**Issue by YazhC** [Microsoft/BotBuilder#3500]
Hi

I have created a azure chatbot and have registered in dev.botframework. I am trying to integrate the chatbot with twilio channel. I have provided the required details such as twilio phonenumber, accnt id, auth token after following the steps in the https://docs.microsoft.com/en-us/bot-framework/channel-connect-twilio

I am able to use the SMS functionality using twilio. Does Azure chatbot only supports SMS as of now?I wanted to enable the calling functionality with twilio to the bot i have created. 
It will be helpful if you guide me through.

Thanks in Advance!

**Comment by JasonSowers** [comment]
At this time Bot Framework only supports the use of SMS with the Twilio channel.  At this time there is no roadmap to support voice.

**Comment by SatyaPavanKumar** [comment]
Hi @YazhC, Can you pls. share code how you integrated chatbot with twilio. I am getting some issues.

**Comment by bommareddysandhya** [comment]
hi i am also facing issue with twillio channel, can u please share the code of bot where u configure sms channel

**Comment by bommareddysandhya** [comment]
i am facing issue with twillio channel, can you please share your code. any extra classes you added to make it work with sms channel.
