### ISSUE TITLE
Post in messagecontroller.cs getting triggered twice for single email when email channel is enabled for bot.

### ISSUE THREAD

**Issue by rajendrasolleti** [Microsoft/BotBuilder#3503]
## Bot Info 
* Bot handle: 
* App ID: 23f5f462-8c96-4b6d-bb21-0bcd60a58f36
* SDK Platform: .NET
* SDK Version: 
* Active Channels: webchat and email
* Deployment Environment: Azure App Service.

## Issue Description
Message controller is getting triggered twice for the same single email.

## Code Example
var message = await argument;
            await context.PostAsync("You said: " + message.Text+ " which is cool.");
            context.Wait(MessageReceivedAsync);

## Reproduction Steps
1. I just created a new app from template and testing the email channel.
2.
3.

## Expected Behavior
public virtual async Task<HttpResponseMessage> Post([FromBody] Activity activity)
in messagecontroller.cs should be called only once instead of twice.

## Actual Results
for single email that i sent i have received 4 replies.

**Comment by JasonSowers** [comment]
can you please post the code from your messages controller  and dialog so we can take a look

**Comment by fanidamj** [comment]
Closing the issue as it seems inactive. Feel free to reopen if you any questions or comments.
