### ISSUE TITLE
BotService suddenly started throwing "Value cannot be null" errors

### ISSUE THREAD

**Issue by s-r-k** [Microsoft/BotBuilder#3504]
## Bot Info 

* BOT ID: byonder 
* AppID: 45a65ff9-5966-4bc4-a09b-f1731c2199bc
* SDK Platform:  .NET 
* SDK Version: Microsoft.Bot.Builder.Azure 3.2.3
* Active Channels: Direct Line
* Deployment Environment: Azure Bot Service

## Issue Description
I am running a Bot on AzureBotService. Suddenly, with no change from my side, I have started seeing this error in the logs: 

2017-09-22T23:25:28.924 Exception while executing function: Functions.messages. Microsoft.Azure .WebJobs.Script: One or more errors occurred. Microsoft.Bot .Connector: Value cannot be null.
Parameter name: connectionString.

The bot throws this error for every incoming message, and fails.

Deploying the identical code on a new BotService instance works. I don't know what has changed.

**Comment by msmohan** [comment]
Hi @s-r-k , What is the bot id (Bot handle in dev.botframework.com) and Microsoft App Id?

**Comment by s-r-k** [comment]
Updated the earlier comment with the Bot id and AppId

**Comment by EricDahlvang** [comment]
We are currently investigating this. Thank you for reporting the issue.  We will update once we have a resolution.

**Comment by EricDahlvang** [comment]
The issue is resolved.  Please try the bot now.

**Comment by s-r-k** [comment]
Thank you.

**Comment by tinuCoder** [comment]
Hi @EricDahlvang i am facing same type of issue my Bot is throwing error Value cannot be null. Parameter name: clientId

I have also created a new issue too https://github.com/microsoft/botframework-sdk/issues/5392
