### ISSUE TITLE
CardAction is disable on Skype

### ISSUE THREAD

**Issue by chungweileong94** [Microsoft/BotBuilder#3505]
## Bot Info
* Bot handle: Daily_Image_Bot  
* App ID: 029f12e8-7c78-4f07-b80c-3187ba220600
* SDK Platform: Node.js
* SDK Version: 3.9.1
* Active Channels: Skype
* Deployment Environment: Heroku

## Issue Description
All CardAction is disable on Skype.
![image](https://user-images.githubusercontent.com/15154097/30769540-8221e522-a04d-11e7-8f41-deb87a8975b8.png)

## Code Example
```
var list: builder.HeroCard[] = new Array<builder.HeroCard>();

rootImages.images.forEach(function (i) {
    var imageLink: string = `https://www.bing.com${i.url}`.replace("1920x1080", size);
    list.push(new builder.HeroCard(session)
        .title(i.copyright)
        .images([builder.CardImage.create(session, imageLink)])
        .buttons([
            builder.CardAction.openUrl(session, i.copyrightlink, "Learn more"),
            builder.CardAction.downloadFile(session, imageLink, "Get the image")
        ]));
});

var msg = new builder.Message(session);
msg.text(list.length == 1 ? "Here's the image I got" : `Here's the ${list.length} images I got`)
msg.attachmentLayout(builder.AttachmentLayout.carousel);
msg.attachments(list);
msg.speak(list.length == 1 ? "Here's the image I got" : `Here's the ${list.length} images I got`);
msg.inputHint(builder.InputHint.acceptingInput);

session.send(msg).endDialog();
```
## Reproduction Steps
1. Send "Get me 5 images" to the bot on Skype
2. The bot will send 5 Hero Card with Card Action(disabled)

## Expected Behavior
The CardAction is clickable

## Actual Results
All CardAction is disabled

**Comment by IoTGirl** [comment]
Hi @chungweileong94 ,

Have you validated that "i.copyrightlink" and "imageLink" translate to valid [url: string](https://docs.botframework.com/en-us/node/builder/chat-reference/classes/_botbuilder_d_.cardaction.html)
``            builder.CardAction.openUrl(session, i.copyrightlink, "Learn more"),
            builder.CardAction.downloadFile(session, imageLink, "Get the image")

**Comment by chungweileong94** [comment]
Hi @IoTGirl ,

Both "i.copyrightlink" and "imageLink" are indeed a valid URL.
Here's the one of the sample URL: https://www.bing.com/search?q=apollo+11&form=hpcapt&filters=HpDate:%2220171004_0700%22

And yes, the issue only appears on Skype.

**Comment by IoTGirl** [comment]
Hi @chungweileong94 ,

I wanted to let you know that I am asking a few other folks about this but I don't have anything helpful yet. 

Sincerely,
IoTGirl

**Comment by nwhitmont** [comment]
@chungweileong94 Your URLs are not properly `urlencoded`, which causes Skype to not recognize your card action "buttons". 

Make sure to run your URL strings through `encodeURI` before adding them to your card actions.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI

**Comment by chungweileong94** [comment]
@nwhitmont I wrap those URL with `encodeURI(...)`, but still get the same result.

**Comment by IoTGirl** [comment]
Hi @chungweileong94 

Can you attempt using a simpler URL without special characters to confirm this is indeed the issue?

Sincerely,
IoTGirl

**Comment by chungweileong94** [comment]
Hi @IoTGirl 
I tested the simple URL, it works fine.
However, I have no idea why this link (https://www.bing.com/az/hprichbg/rb/DerwentDam_ROW9481150609_1920x1080.jpg) won't work?
