### ISSUE TITLE
IIS 401 & Visual Studio Now Also 401 on Known Working Bot

### ISSUE THREAD

**Issue by OliverDolan** [Microsoft/BotBuilder#3507]
## Bot Info 
* Bot handle: Test3333333 
* App ID: 13749234-2e88-4824-8f7b-1c0d5621872c
* SDK Platform: :Net
* SDK Version: Runtime: v4.0.30319 Version:3.9.1.0
* Active Channels: Skype
* Deployment Environment: IIS, Ngrok, Windows 10, Windows Server 2012

## Issue Description
401 Error constantly

## Code Example
Using any form of communication is working fine on my dev pc but replicating on the server install is not functioning, it will work locally without credentials between emulator and iis.

## Reproduction Steps
I am also having a similar issue as described #3461 , I could not get my published bot to run correctly so started testing with running via visual studio on my cloud server.

I am running the same code via visual studio on my local dev pc (win10) and on a cloud server (win server 2012) also started by visual studio.

If i use ngrok command line and run via visual studio f5 (run) button things work fine on my dev pc, messages from both sides.

If i mimic the same setup on the server and also update the botframework website with different ngrok endpoint information I just get 401 all the time.

I have looked in the ngrok web interface and the packets look close enough that you could fairly say there were the same when using a diff tool. Slight differences in timestamps and the bearer token was partially different but most likely I assumed that would be normal due to different devices?

To me it seems to be something strange when deployed on the server 2012 machine, no idea why it wont work...

It is very strange to recieve 401 from everywhere even the bot framework test chat cannot post one way even though the endpoint is available from many devices and firewall disabled etc..

The fun thing is it is complaining about the credentials but they are stored in the web.config and retrieved via svn checkout so almost certainly are the same as well.

## Expected Behavior
Bot to not give 401 error like on my dev machine

## Actual Results
Constant 401 errors

**Comment by JasonSowers** [comment]
Does your server have a valid certificate?

The Bot Framework works with bots deployed on any cloud hosting service, as long as you have an internet-accessible endpoint and a valid SSL certificate.
The Bot Framework requires that the x.509v3 certificate exposed by your endpoint be current and valid. Most of the checks for "current and valid" are standard checks for server SSL certificates: the Certificate Name must match the hostname, it must not be expired, it must not be listed in a CRL, it must have the correct set of EKUs, etc.
Most importantly, your SSL certificate must chain to a root certificate authority trusted by Microsoft. The latest list of these CAs is available here: http://social.technet.microsoft.com/wiki/contents/articles/31634.microsoft-trusted-root-certificate-program-participants-v-2016-april.aspx

**Comment by OliverDolan** [comment]
Is the certificate needed even when using ngrok, this is not needed on my dev pc as things work as expected but when using the same setup on windows server things do not work the same as windows 10. Is the ssl mandatory or can it work via ngrok?

**Comment by JasonSowers** [comment]
As a general rule with bot framework, if it's not deployed on Azure you need a valid certificate.  I have not tried ngrok on a server 2012 machine myself so I'm not 100% sure, but it does seem like this is your issue.

**Comment by OliverDolan** [comment]
closing as it was related to the time not being set within the threshold based on the timezone that the server was configured to run in. eg

it was set to pacific time - which according to google was 10:32pm

but the server time was way off eg:
05:32am

Setting the server to 10:32pm made things work immediately
