### ISSUE TITLE
Microsoft Teams bots channel has suddenly stopped answering

### ISSUE THREAD

**Issue by denisyfrolov** [Microsoft/BotBuilder#3509]
## Bot Info
* Bot handle: msteamstestbot_82bP3Z3pLGN   
* App ID: b75e8ebc-548e-47dd-bddb-b8efcc995232
* SDK Platform: .NET
* SDK Version: Microsoft Bot Builder Azure 3.2.3
* Active Channels: Skype, MS Teams, Telegram, Web Chat
* Deployment Environment: Azure Bot Service
## Issue Description
Microsoft Teams bots channel has suddenly stopped answering to new bots in Azure Bot Service. I figured it out yesterday. I don't know how long it doesn't work, but the week before it works fine. Now if you try to deploy new bot and enable Microsoft Teams, it just won't work. Even if it is the Echo Bot from the default template without any modifications. I send messages to the bot in 1:1 chat, but it just doesn't answer me. In the log-streaming service of the App Service instance I see that Microsoft Teams doesn't even try to communicate to the bots endpoint URL. I see in the logs all the other channels (Skype, Telegram, Web Chat), but MS Teams.

## Code Example
The Echo Bot from the default template in Azure Bot Service.

## Reproduction Steps
1. Deploy the Echo Bot from the default template in Azure Bot Service.
2. Enable the Microsoft Teams channels.
3. Add the bot to 1:1 chat in Microsoft Teams.

## Expected Behavior
It should answers, shouldn't it?

## Actual Results
No error messages, just total silence from Microsoft Teams.

**Comment by denisyfrolov** [comment]
Looks like it has been fixed already by itself

**Comment by JasonSowers** [comment]
Glad its working for you 👍
