### ISSUE TITLE
Cannot install custom bot on bot framework

### ISSUE THREAD

**Issue by LlewellynJones** [Microsoft/BotBuilder#3511]
## Bot Info 
* Bot handle: none
* App ID: none
* SDK Platform: .NET
* SDK Version: 3.8
* Active Channels: NONE!
* Deployment Environment: Auzure Bot Service, Azure App Service

## Issue Description
Cannot install custom bot on bot framework

Tried to install the bot as an app service -> bot works fine, but registering the bot just hangs, see 3497

Tried to install the bot as an bot service -> the bot registers, but I cannot successfully overwrite the basic template by publishing from Visual Studio, 

I get the following error when I try to access the bot in the emulator:

"Could not load file or assembly 'Microsoft.Bot.Connector, Version=3.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)"

In the online_ code editor in azure it looks like the basic template code is unchanged.

**Comment by JasonSowers** [comment]
Please upgrade you botbuilder sdk to 3.9.0 or higher and see if the issue persists.

**Comment by LlewellynJones** [comment]
I found out a couple of things: the app name has to be more than three characters, the bot framework registration only works in IE. I have the app id now.
