### ISSUE TITLE
[LUIS] LUIS losing end user training upon republishing

### ISSUE THREAD

**Issue by Bazorpazorps** [Microsoft/BotBuilder#3514]
## Issue Description
The LUIS (v 0.2) app I'm working with seems to be learning through online user input over time. However, upon adding utterances, training, and republishing the app it seems to lose the user-learned utterance training.  It's not clear what is causing the loss of that training and how it might be kept.

**Comment by stevengum97** [comment]
@Bazorpazorps, when you download the query logs from LUIS are the added utterances missing? After you add, train and publish, where are you seeing behavior that indicates the model has lost the utterances?

**Comment by DL-LiveTiles** [comment]
@stevengum97 To clarify, utterances are not lost, but we are finding that the results seem to be less accurate just after a publish. We have not been able to quantify this, but was wondering if active learning is only achieved through adding suggested utterances or are there other mechanisms that can be used to maintain active learning?

> Once your application is deployed and traffic starts to flow into the system, LUIS uses active learning to improve itself. In the active learning process, LUIS identifies the utterances that it is relatively unsure of, and asks you to label them according to intent and entities. This process has tremendous advantages. LUIS knows what it is unsure of, and asks for your help in the cases that lead to the maximum improvement in system performance. LUIS learns quicker, and takes the minimum amount of your time and effort. This is active machine learning at its best. See Label suggested utterances for an explanation of how to implement active learning using the LUIS web interface.

**Comment by stevengum97** [comment]
@DL-LiveTiles sorry for the delay. Can you provide quantitative findings on the differences in prediction accuracy? It would greatly help to be able to examine these directly. Regarding active learning, you are correct. Labeling Suggested Utterances is the confirmation needed from users to validate the model, and thus the only currently available way to maintain active learning.

**Comment by DL-LiveTiles** [comment]
@stevengum97 We will try to setup some experiments to try and quantify. If you have any documentation or articles on the inner workings of LUIS to help us better create, combine and train the language models that would be a great help.

**Comment by fanidamj** [comment]
Closing the issue assuming it as resolved. If you have any other concerns for LUIS support, please contact luservice@microsoft.com.
