### ISSUE TITLE
Context.Wait() forwarding to RootDialog instead. (Using proactive messaging)

### ISSUE THREAD

**Issue by BelvedereHenrique** [Microsoft/BotBuilder#3519]
## Bot Info 
* Bot handle: gartnerdemo
* App ID: 91676d92-82d2-40d3-8a09-4bf9245a2f79
* SDK Platform: .NET
* SDK Version: 3,9
* Active Channels: Cortana, Facebook
* Deployment Environment: Azure App Service

## Issue Description
context.wait(MessageReceived)  does not forward to "MessageReceived" when response arrives.

## Code Example
        public async Task StartAsync(IDialogContext context)
        {
            var activity = context.Activity as Activity;

            var reply = CreateContinueReply(activity.CreateReply(), "Looks like I've found some new photos! Wanna see it?!");
            await context.PostAsync(reply);
            
            context.Wait(GetUserApprovalForPostingImage);
        }

## Reproduction Steps
1. Create a new proactive Dialog using Microsoft sample https://github.com/Microsoft/BotBuilder-Samples/blob/master/CSharp/core-proactiveMessages/startNewDialog/ConversationStarter.cs
2. Ask a question through Cortana, respond through Facebook.
3. After the response, call context.Wait().

## Expected Behavior
The Yes or No response goes to the method indicated on context.Wait()

## Actual Results
The Yes or No response goes to RootDialog instead

## Comments

The scenario is:
I call Cortana to tell my bot to gather some images. When my bot founds it, it sends me a message on Facebook telling me that it has something to show me, and ask for a Yes or No.
When I respond it, using the promp or not, the message goes for RootDialog instead of going to the method that I just passed for context.Wait()

To create a proactive message for Facebook when the photos are ready to be shown, I used the this example https://github.com/Microsoft/BotBuilder-Samples/blob/master/CSharp/core-proactiveMessages/startNewDialog/ConversationStarter.cs.

I've just called ConversationStarter.Resume(ShowPhotosDialog).

I believe it's something related to the context.

Is there a way to check if my context.Wait() is referencing the recently Facebook dialog context instead Cortana context? If yes, how can I swap them?

Can anyone help me on this?

Thanks!!

**Comment by JasonSowers** [comment]
This is a pretty cool idea! 👍  Are you able to post your code to a repo so we can assist you in troubleshooting better?

**Comment by BelvedereHenrique** [comment]
Yeah, sure. I'm out of the office right now but I can post the code tomorrow.

**Comment by JasonSowers** [comment]
Great, I'll take a look tomorrow.

**Comment by BelvedereHenrique** [comment]
Here his how I pile a new conversation on the stack:

 public static class Starter
    {
        //Note: Of course you don't want this here. Eventually you will need to save this in some table
        //Having this here as static variable means we can only remember one user :)
        public static string ConversationReference;

        public static async Task Resume(ModelImage model, WitResultModel wit)
        {
            var message = JsonConvert.DeserializeObject<ConversationReference>(ConversationReference).GetPostToBotMessage();
            var client = new ConnectorClient(new Uri(message.ServiceUrl));

            using (var scope = DialogModule.BeginLifetimeScope(Conversation.Container, message))
            {
                var botData = scope.Resolve<IBotData>();
                await botData.LoadAsync(CancellationToken.None);

                //This is our dialog stack
                var task = scope.Resolve<IDialogTask>();
                //interrupt the stack. This means that we're stopping whatever conversation that is currently happening with the user
                //Then adding this stack to run and once it's finished, we will be back to the original conversation
                var dialog = new ShowFoundPhotosDialog(model,wit);
                task.Call(dialog.Void<object, IMessageActivity>(), null);
                
                await task.PollAsync(CancellationToken.None);

                //flush dialog stack
                await botData.FlushAsync(CancellationToken.None);

            }
        }
    }

Here is how I'm resuming it:

if (Starter.ConversationReference != null && context.Activity.ChannelId == "cortana")
                    await Starter.Resume(converted, NaturalLanguageResult);

**Comment by BelvedereHenrique** [comment]
I managed to fix it.

It was an [Serializable] annotation missing on one of my dialogs.

I don't really know why my try{}catch{} wasn't catching it or why the bot wasn't showing the Exception on the chat.

Anyway, now it's working like a charm.

Thanks for your attention!
