### ISSUE TITLE
Cannot set endpoint url value

### ISSUE THREAD

**Issue by OliverDolan** [Microsoft/BotBuilder#3521]
* App ID: d2fbcbef-e472-4872-a91f-34433536281d

## Issue Description
Cannot save updates to my endpoint url

## Reproduction Steps
1.Go to the bot settings page on botframework.com
2.Try to update the url to a valid https url
3.The url will not be updated and an error is displayed: "Please correct the errors and try again."
4.After clicking ok the user is scrolled to the url box but no error message is displayed on the front end

The console window in chrome shows:
![image](https://user-images.githubusercontent.com/20300369/30829326-c2d8a156-a240-11e7-8a12-124404c7956c.png)

## Expected Behavior
The url should be updated correctly

## Actual Results
The user is unable to set the https endpoint url

**Comment by stevengum97** [comment]
@OliverDolan, just to double check, there's no whitespace before `https` right?

**Comment by OliverDolan** [comment]
@stevengum97 yes I have checked that there is no leading whitespace

**Comment by OliverDolan** [comment]
in the end i deleted the bot and recreated it as we haven't come so far with things yet, but something had definitely got corrupted in the backend
