### ISSUE TITLE
[Question] Could I send the message for the bot through REST API by conversation ID?

### ISSUE THREAD

**Issue by binhpht** [Microsoft/BotBuilder#3522]
## Bot Info 

 SDK Platform: Node.js
 Active Channels:  Bot Skype and Facebook
 Deployment Environment: ngrok

 Issue Description
Hi, I need to send the data for the bot through API by converstionID and Bot access Token. As I see that each session of bot, i can have conversationID and token. I want send the data for bot based on these data. However, I dont know which the address URI to send that. Could you guide some infor

**Comment by JasonSowers** [comment]
Have you looked over this documentation? https://docs.microsoft.com/en-us/bot-framework/rest-api/bot-framework-rest-connector-api-reference

**Comment by binhpht** [comment]
Yeah, I looked,  I see the service URL may be potential to send request API but  It fail when I checked

**Comment by nwhitmont** [comment]
Use the `serviceUrl` found in the Activity object to route your message to the correct endpoint.

For more information, consult the Bot Connector REST API documentation on sending and receiving messages.

https://docs.microsoft.com/en-us/bot-framework/rest-api/bot-framework-rest-connector-send-and-receive-messages
