### ISSUE TITLE
Dialog with LUIS behind proxy server for C#

### ISSUE THREAD

**Issue by abhinabsarkar** [Microsoft/BotBuilder#3526]
* SDK Platform: C# .NET
* SDK Version: 3.0.0
* Active Channels: Skype
* Deployment Environment: On premise IIS server

## Issue Description
When trying to work with Dialogs using LUIS, I am getting Authorization error 407 due to proxy. I am behind a corporate proxy. Is there a way to work with Dialogs and make it proxy aware by passing the credentials ?

## Expected Behavior
It should invoke the LUIS service

## Actual Results
The remote server returned an error: (407) Proxy Authentication Required.

**Comment by msmohan** [comment]
@abhinabsarkar Please look into one of the closed issue provided with a solution.

**Comment by abhinabsarkar** [comment]
@msmohan Can you please let me know the issue number which has the solution

**Comment by abhinabsarkar** [comment]
@msmohan I got the solutions mostly for emulator and node.js. Can you please help me with the solution where it for C#

**Comment by McBacker** [comment]
As a workaround you cad add this to your WebApp configuration file:

  <system.net>
    <defaultProxy useDefaultCredentials="true">
      <proxy bypassonlocal="True" usesystemdefault="False" proxyaddress="http://ip:port"/>
      <bypasslist>
        <add address="[a-z]+\.myinternal\.net"/> 
      </bypasslist>
    </defaultProxy>
  </system.net>

Ps. Don't forget to remove/comment when deployed to Azure.

**Comment by abhinabsarkar** [comment]
@McBacker Thanks for your response. This did not work but it got me into the right direction. I needed to pass the credentials too along with the proxy details. I was able to pass that by referring to this blog http://lastattacker.blogspot.com/2011/06/configuring-proxy-settings-in-net.html

**Comment by msmohan** [comment]
@abhinabsarkar I am glad you got it working.
