### ISSUE TITLE
Failure in searching entities for the first time in bot framework

### ISSUE THREAD

**Issue by usheveta** [Microsoft/BotBuilder#3527]
## Bot Info 
* SDK Platform: .NET
* SDK Version: 3.9.0
* Active Channels: Bot Emulator

## Issue Description
I have built a bot with 4 entities and based on these entities I'm performing a search on SP list. 
So whenever I search for one entity or multiple entities, first time the entities.count is always '0'.
And second time it will take the same search query and provide me the results.
Example: I search for "Trainings for sharepoint". Here my sharepoint is one entity.
As the entity.count is always 0 for the first search I'm using await.Task.Delay(2000). But I don't want to use 'await', is there any other way I can overcome the issue.

## Code Example

```cs
if (QueryTransformed)
            {
                if (entities.Count == 0)
                {
                    //await context.PostAsync($"Please enter one or more search keywords");
                    await Task.Delay(2000);
                }              
                if (result.TryFindEntity("CourseName", out getCourseName))
                {
                    await context.PostAsync($"Looking for trainings related to '{getCourseName.Entity}'");
                    //// my code 
                }
                //// After getting all the values I'm forming a CAML query to fetch results.
           }
```

## Expected Behavior
It should search for the entity values and provide result in the first go.

## Actual Results
It is showing results in the second go.

**Comment by FranciscoPonceGomez** [comment]
Hi @usheveta,

I am assuming you are referring to LUIS entities (not database entities) and you are using the common patterns for LUIS applications. You might have a dialog with different intents associated to dialog methods like:

```csharp
[LuisIntent("")]
[LuisIntent("None")]
public async Task None(IDialogContext context, IAwaitable<IMessageActivity> result, LuisResult lResult)
        {
            var activity = await result;
            context.PostAsync($"Sorry, I didn't understand your question");
        }

[LuisIntent("CourseName")]
public async Task Search(IDialogContext context, IAwaitable<IMessageActivity> activity, LuisResult result)
        {
            await context.PostAsync($"Looking for trainings related to '{getCourseName.Entity}'");
                    //// my code 
        }
```
I can't really know what is going on from just the small piece of code that you sent me but, I think it could be due to a missing 'await' operand in one of the promises. It could also be happening due to a delayed connection. Can you share the structure of your dialog?

Regards,
Francisco

**Comment by usheveta** [comment]
Hi @FranciscoPonceGomez ,

Yes i have the same code like you have mentioned above. I have added await as well. Please find my code below.
I want to verify if its the correct way.

namespace TrainingAssistantBot.Dialogs
{
    [LuisModel("12159c26-0e28-4faf-a2af-d59d05ff38ca", "1d6c2beacbad4830b5b8f14343ddf772")]
    [Serializable]

    public class SearchRootDialog : LuisDialog<object>
    {
        private string userName = System.Configuration.ConfigurationManager.AppSettings["username"];
        [LuisIntent("")]
        [LuisIntent("None")]
        public async Task None(IDialogContext context, LuisResult result)
        {
            await context.PostAsync("I didn't understand your query. Please try again with different query.");
        }
        
        [LuisIntent("SearchTraining")]
        public async Task SearchFiles(IDialogContext context, LuisResult result)
        {
            //// to search the trainings on basis of course name, mode
            var entities = new List<EntityRecommendation>(result.Entities);

            EntityRecommendation getCourseName = new EntityRecommendation();
            EntityRecommendation getMode = new EntityRecommendation();
            EntityRecommendation getLocation = new EntityRecommendation();
            EntityRecommendation getDate = new EntityRecommendation();
            EntityRecommendation getTime = new EntityRecommendation();
            bool QueryTransformed = true;

            //Search with Entity CourseName

            if (QueryTransformed)
            {
                if (entities.Count == 0)
                {
                    //await context.PostAsync($"Please enter one or more search keywords");
                    // await Task.Delay(2000);
                    context.Wait(MessageReceived);
                }
                else
                {
                    if (result.TryFindEntity("CourseName", out getCourseName))
                    {
                        // await context.PostAsync($"Looking for trainings related to '{getCourseName.Entity}'");
                        string searchTerm_CourseName = string.Empty;
                        searchTerm_CourseName = getCourseName.Entity;
                        if (string.IsNullOrWhiteSpace(searchTerm_CourseName))
                        {
                            await context.PostAsync($"Unable to get search term.");
                        }
                        else
                        {
                            SearchClass scSearchc = new SearchClass(userName);
                            if (searchTerm_CourseName != null)
                            {
                                var courseSearch = scSearchc.FindCourseByName1(searchTerm_CourseName);
                            }
                        }

                    }
			//Search with Entity Mode
	
                    if (result.TryFindEntity("Mode", out getMode))
                    {
                        // await context.PostAsync($"Looking for trainings related to '{getMode.Entity}'");
                        string searchTerm_Mode = string.Empty;
                        searchTerm_Mode = getMode.Entity;
                        if (string.IsNullOrWhiteSpace(searchTerm_Mode))
                        {
                            await context.PostAsync($"Unable to get search term.");
                        }
                        else
                        {
                            SearchClass scSearchMode = new SearchClass(userName);
                            if (searchTerm_Mode != null)
                            {
                                var modeSearch = scSearchMode.FindCourseByMode1(searchTerm_Mode);
                            }
                        }

                    }
                   
                    SearchClass scSearch = new SearchClass(userName);
                    var querySearch = scSearch.SearchCourse();
                    var itemsSearch = scSearch.searchQueryDetails;
                    if (itemsSearch.Count == 0)
                    {
                        await context.PostAsync($"OOPS! No trainings found. Try with different keywords...");
                    }
                    else
                    {
                        await context.PostAsync($"Happy Learning!");
                        foreach (ListItem listItem in itemsSearch)
                        {
                            var resultMessage = context.MakeMessage();
                            resultMessage.AttachmentLayout = AttachmentLayoutTypes.Carousel;
                            resultMessage.Attachments = new List<Microsoft.Bot.Connector.Attachment>();
                             
                            ThumbnailCard thumbnailCard = new ThumbnailCard()
                            
                            {
                                Title = "ABC",
                                Subtitle = "XYZ",
                                Text = "EFG",
			    };

                            await context.PostAsync(resultMessage);
                        }
                    }

                    context.Wait(this.MessageReceived);
                }
            }

            else
            {
                await context.PostAsync($"Search Again");

            }

        }
    }


}

**Comment by JasonSowers** [comment]
can you please provide your implementations of `SearchClass` and `ListItem`
