### ISSUE TITLE
[Feature Request] Endpoint to post slack token

### ISSUE THREAD

**Issue by tommyengstrom** [Microsoft/BotBuilder#3531]
## Bot Info 
* Active Channels: Slack

## Issue Description
The current oauth flow used in bot connector is broken by design for any non trivial bot. Any system already containing information from the users, e.g. if the user is already using some other platform, is left without a way to sync that account with the slack account. The current solution to this is make the user go though the oauth flow twice (or once and then use sign in with slack). This is a pretty bad user experience.

All that would be required to solve this is to provide an endpoint where slack tokens can be posted. Then anyone requiering to sync accounts can use a custom oauth flow. The endpoint would get the same information as in the final step of the oauth flow, meaning it should be simple to implement.

## Reproduction Steps
1. User already has an account 
2. User press add to slack
3. System has no way of knowing how to map the new slack account the an account the the system

## Expected Behavior
There being a way to post the bot token so that a custom oauth flow can be created.

## Actual Results
Users have to do the oauth flow twice, making it possible to end up in a weird half-authorized state.

**Comment by sgellock** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
