### ISSUE TITLE
[Question] MS Teams ChatConnector.delete doesn't seem to work

### ISSUE THREAD

**Issue by santiagodoldan** [Microsoft/BotBuilder#3532]
## Bot Info
* Bot handle: suttna
* App ID: 220dc633-1f3d-4346-ad61-3805e88be8c0
* SDK Platform: Node.js
* SDK Version: 3.9
* Active Channels: MS Teams, Slack
* Deployment Environment: ngrok, other

## Issue Description
I can't delete MS Team messages sent by our bot using the delete function defined in ChatConnector. It does work for Slack messages though.

## Code Example
```
  let address = { /* bot message address */ }

  connector.delete(address, (err) => {
    console.info(err) // this is always undefined
  })
```

**Comment by nwhitmont** [comment]
Delete is not a supported method in MS Teams.

See:https://msdn.microsoft.com/en-us/microsoft-teams/botsconversation

**Deleting messages**
>At this point, there is no way for you to delete messages via your bot. You can update content in your message (see Updating messages earlier in this topic), but there is no platform support to delete messages from users or your bot.
