### ISSUE TITLE
VS2013 project template

### ISSUE THREAD

**Issue by Shamrh** [Microsoft/BotBuilder#3537]
SDK Platform: .NET
 SDK Version: 3.8

## Issue Description
Visual studio project template  does not seems to be working I always get a http 500 error. is there a separate template for VS2013?

**Comment by msmohan** [comment]
You can download templates from here
[Visual Studio project templates](https://docs.microsoft.com/en-us/bot-framework/resources-tools-downloads#get-the-bot-builder-sdk-for-net
)
There is no 2013 template available.

**Comment by msmohan** [comment]
I am closing this thread now. Feel free to contact us here for any questions.
