### ISSUE TITLE
Registered bot missing from dashboard

### ISSUE THREAD

**Issue by lsseckman** [Microsoft/BotBuilder#354]
I'm a bit confused, my bot is still working (SMS & email plugins still functioning) but it isn't showing up on the [dashboard](https://dev.botframework.com/bots). Instead I'm seeing this:

![screen shot 2016-05-26 at 12 25 29 pm](https://cloud.githubusercontent.com/assets/5060910/15583803/f775d7e6-233c-11e6-8149-472bb81d8f12.png)

Anyone have ideas on what could be wrong?

**Comment by tomlm** [comment]
What is your bot name?

**Comment by lsseckman** [comment]
Humble Pie: It was user error, I was signed in with the bot's ```@outlook.com``` email address instead of the one I registered the bot under. Switched to proper login, everything's fine. 

Also going to add the @outlook.com address as an owner so it doesn't happen again.
