### ISSUE TITLE
[Node.js SDK] Best way to save user inputs

### ISSUE THREAD

**Issue by wethil** [Microsoft/BotBuilder#3548]
I am using Microsoft ChatBot Builder NodeJS SDK. I can use Cosmos Db for state storage. But I want to storage all inputs from user on everytime. I want user's old inputs on my database. What is the best way for it? Creating a webserver with database and send all inputs on a single conversion  via http POST requests or Does the BotBuilder has a method for it?

**Comment by stevengum97** [comment]
@wethil the best way to do this would be to intercept the exchanges between user and bot via middleware. You can find an example on implementing your own middleware in the [BotBuilder-Samples repo](https://github.com/Microsoft/BotBuilder-Samples), under [capability-middlewareLogging](https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node/capability-middlewareLogging). You'll be using [`UniversalBot.use()`](https://docs.botframework.com/en-us/node/builder/chat-reference/classes/_botbuilder_d_.universalbot.html#use), and will want to see [IMiddlewareMap](https://docs.botframework.com/en-us/node/builder/chat-reference/interfaces/_botbuilder_d_.imiddlewaremap.html) for the events you can intercept.
