### ISSUE TITLE
Cannot save bot. Getting "Please correct the errors and try again." error in portal

### ISSUE THREAD

**Issue by gcsonka** [Microsoft/BotBuilder#3549]
## Bot Info 
* Bot handle: BotBA
* App ID: e339387d-082c-4fe3-b907-a66b8288eb4b
* SDK Platform:  .NET
* SDK Version: 3.9.1
* Active Channels:  Skype, Slack, Facebook,Kik, Telegram
* Deployment Environment: Azure App Service

## Issue Description
I was able to create the bot, but cannot update the bot settings. I receive the "Please correct the errors and try again." error when I try to change anything on the bot's settings page. The cursor seems to jump back to the "Long Description" field as it;s trying to indicate a missing required field. But I do have a long description, so do every other information on the page.
## Reproduction Steps
1.Log into Bot dev portal
2.Go to settings tab
3.change anything (like logo, or description)
4. click save 
5. get the "Please correct the errors and try again." error

## Expected Behavior
Settings are saved and no error displayed.
## Actual Results
Getting "Please correct the errors and try again." error and no new information is saved on the form.

**Comment by EricDahlvang** [comment]
Are you signed in with one of the accounts that are in the Owners field?

**Comment by gcsonka** [comment]
Yes. Just verified. I'm signed in with the account that was used for
signing up for the bot portal. It is in the owners field.

On Oct 2, 2017 10:17 AM, "Eric Dahlvang" <notifications@github.com> wrote:

Are you signed in with one of the accounts that are in the Owners field?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/BotBuilder/issues/3549#issuecomment-333584840>,
or mute the thread

**Comment by EricDahlvang** [comment]
If you hit F12 in the browser after attempting to save, do you see any errors or more information?

**Comment by gcsonka** [comment]
Yes. I can see this: Get 400 Bad request at the time of page load. PUT 400 error when I click the save button.

![image](https://user-images.githubusercontent.com/21324416/31105811-f19acc68-a7a3-11e7-99da-7f9fd5ef809b.png)

**Comment by gcsonka** [comment]
Hi @EricDahlvang . FYI - I deleted and re-created the bot in the portal along with all of its channels. It is a pain, but I could not find any other way to change my bot.

**Comment by EricDahlvang** [comment]
@gcsonka  That's a bummer.  I'm sorry you were forced to resort to such a drastic measure.  I spent some time looking into this, and eventually escalated to the team.  A root cause of your issue has not yet been determined.

Thank you for reporting your issue.  Hopefully things go smoothly for your bot now.

**Comment by gcsonka** [comment]
Thanks Eric. Appreciate your help.

**Comment by johanfive** [comment]
Hello there, I'd like to reopen this issue.

I'm running into the exact same issue.
The error is:
```
PUT https://dev.botframework.com/api/BotManager?forPublishing=false
400
{"Errors":[{"Field":"MsaAppType","Message":"'MsaAppType' property cannot be changed."}]}
```

The only change I brought in the UI before clicking the `Save changes` button was update the `Messaging endpoint` field with a new ngrok url. Something I've been able to do hundreds of times up until now.

**Comment by stalker8610** [comment]
> **EDIT:** For anyone reading this, the issue is that the platform is trying to set `MsaAppType` to `"0"` instead of `null`. You can just recreate in Postman the same request your browser is making, just make sure to update the payload with the right value for `MsaAppType`
> 
> _Hello there, I'd like to reopen this issue.
> 
> I'm running into the exact same issue. The error is:
> 
> ```
> PUT https://dev.botframework.com/api/BotManager?forPublishing=false
> 400
> {"Errors":[{"Field":"MsaAppType","Message":"'MsaAppType' property cannot be changed."}]}
> ```
> 
> The only change I brought in the UI before clicking the `Save changes` button was update the `Messaging endpoint` field with a new ngrok url. Something I've been able to do hundreds of times up until now._

Hello! As far as I understand, this request can be executed via Postman to save changes in bot. Please tell me how you got around the 401 Unauthorized error? I filled in all the headers as in the request, it doesn't help :(

**Comment by isacarcanjo** [comment]
> **EDIT:** For anyone reading this, the issue is that the platform is trying to set `MsaAppType` to `"0"` instead of `null`. You can just recreate in Postman the same request your browser is making, just make sure to update the payload with the right value for `MsaAppType`
> 
> _Hello there, I'd like to reopen this issue.
> 
> I'm running into the exact same issue. The error is:
> 
> ```
> PUT https://dev.botframework.com/api/BotManager?forPublishing=false
> 400
> {"Errors":[{"Field":"MsaAppType","Message":"'MsaAppType' property cannot be changed."}]}
> ```
> 
> The only change I brought in the UI before clicking the `Save changes` button was update the `Messaging endpoint` field with a new ngrok url. Something I've been able to do hundreds of times up until now._

I've got the same problem

After to save
![image](https://user-images.githubusercontent.com/76750741/144098660-a9992458-96ce-4358-a94e-5cffb228dd69.png)

Back end response 
![image](https://user-images.githubusercontent.com/76750741/144098791-eb39d624-daa5-4c7f-8f25-6c2096e5b0a7.png)

**Comment by ffactory-ofcl** [comment]
> For anyone reading this, the issue is that the platform is trying to set MsaAppType to "0" instead of null.
You can just recreate in Postman the same request your browser is making, just make sure to update the payload with the right value for MsaAppType

Thanks @johanfive, that worked for me!

Steps:
1. Open network tab in the browser
2. Watch the request fail
3. Right-click -> copy request as cURL
4. Open Postman and click new request -> import -> raw text and paste the request
5. Edit the request body to remove the `MsaAppType` key
6. Send it & you're done. Refresh the botframework site to check if it worked

**Comment by adamist521** [comment]
@ffactory-ofcl 
Thanks for sharing. You saved my life 😃

**Comment by fabiank0** [comment]
Thank you @ffactory-ofcl for the fix.
I've run into the same problem as well.

**Comment by Cjericho4** [comment]
I am also getting this same error as everyone else of it trying to set MSaAppType. 

@ffactory-ofcl when I have tried to recreate using your steps I keep getting a 401 forbidden error, any ideas on how to get around that? 
![image](https://user-images.githubusercontent.com/58090256/148086186-7be1af99-c7d6-4d1a-963d-23412898243f.png)

**Comment by fabiank0** [comment]
@Cjericho4  Did you copy the full cURL request? It could also be that you took too long to send the request, I think there are some auth tokens being sent with the request.

**Comment by Cjericho4** [comment]
@fabiank0 I tried a few more times. I right clicked on the put and copied as curl (POSIX) and curl (Windows) and did it within 30 seconds of trying the original push and haven't been able to get it to work. I tried editing a few of the headers but I keep getting the 401 Unauthorized.

**Comment by ffactory-ofcl** [comment]
> @fabiank0 I tried a few more times. I right clicked on the put and copied as curl (POSIX) and curl (Windows) and did it within 30 seconds of trying the original push and haven't been able to get it to work. I tried editing a few of the headers but I keep getting the 401 Unauthorized.

You need to *remove* the MsaAppType key before posting. Did you send it using postman?

**Comment by Cjericho4** [comment]
@ffactory-ofcl yes I removed the MsaAppType Key every time I tried it.

**Comment by fabiank0** [comment]
@Cjericho4 I've just tested it again, and @ffactory-ofcl 's steps still work for me (implying that the problem still exists). I've opened a new issue, since this one is about a different problem and is unlikely to get much visibility.

**Comment by lverre** [comment]
Another way to save changes that doesn't require anything is to remove the input from the DOM:

1. right click "App Type"
2. Click inspect
3. in dev tools, click the "<div class="detail-row">" above the label that's selected
4. press DEL key
5. click "Save Changes"

**Comment by 89hikari** [comment]
> @fabiank0 I tried a few more times. I right clicked on the put and copied as curl (POSIX) and curl (Windows) and did it within 30 seconds of trying the original push and haven't been able to get it to work. I tried editing a few of the headers but I keep getting the 401 Unauthorized.

Do you use web version of Postman? I've tried to do it in web version and also got the 401 Unauthorized. But in desktop version everything worked.

**Comment by Cjericho4** [comment]
@89hikari I will have to try that out.

**Comment by usrb1n** [comment]
Something that just worked for me was to right click on the disabled select box for AppType the click on Inspect and then press DEL to remove that input from the form.
