### ISSUE TITLE
I cannot export my luis model

### ISSUE THREAD

**Issue by Malith1994124** [Microsoft/BotBuilder#3552]
Every time i click export button it give me below error.

{
  "error": {
    "code": "Failure",
    "message": "One or more errors occurred. Corresponding request ID: a3a98aa8-aca0-462f-b23b-f23b779e9246."
  }
}

Someone plz help me

**Comment by romulovll** [comment]
I have the same problem

**Comment by stevengum97** [comment]
We've mitigated the issue and you should be able to export your LUIS models now. If you're still unable to, please @mention me and I'll look into it. Sorry for the inconvenience!

**Comment by GiacomoW** [comment]
Ho lo stesso problema, how can I solve?

**Comment by GiacomoW** [comment]
@stevengum97

**Comment by GiacomoW** [comment]
nobody can help me?

**Comment by v-geberr** [comment]
@GiacomoW Please try again now. If the issue continues, please use UserVoice from inside LUIS.ai to log the issue with support.

**Comment by sinkcup** [comment]
Luis.ai My Apps -> Export App, success on small app, but error on big app, jump to:

https://westus.api.cognitive.microsoft.com/luis/api/v2.0/apps/xxx/versions/0.1/export?subscription-key=yyy

```
{"error": {
"code": "BadArgument",
"message": "Sequence contains more than one matching element"
}}
```
