### ISSUE TITLE
[Feature Request] Suggested actions' behavior is dependent on channel used

### ISSUE THREAD

**Issue by peterbozso** [Microsoft/BotBuilder#3555]
## Issue Description
The suggested actions feature of the .NET SDK behaves differently, depending on which channel is used.

## Code Example
```csharp
var reply = activity.CreateReply("I have colors in mind, but need your help to choose the best one.");
reply.Type = ActivityTypes.Message;
reply.TextFormat = TextFormatTypes.Plain;

reply.SuggestedActions = new SuggestedActions()
{
    Actions = new List<CardAction>()
    {
        new CardAction(){ Title = "Blue", Type=ActionTypes.ImBack, Value="Pick blue" },
        new CardAction(){ Title = "Red", Type=ActionTypes.ImBack, Value="Pick red" },
        new CardAction(){ Title = "Green", Type=ActionTypes.ImBack, Value="Pick green" }
    }
};
```

## Expected Behavior
When a suggested action is displayed, it's **Title** should be inside it's button. When it's clicked, it's **Value** should be sent to the bot. So if I click the button titled "Red", then the text "Pick red" should be sent.

## Actual Results
On the emulator, it works as expected. On Facebook, instead of the **Value**, the **Title** is being sent to the bot. So sticking to the example above: if I click "Red" then "Red" is being sent as well, instead of "Pick red". Haven't checked with other channels.

**Comment by sphanley** [comment]
Related: https://github.com/Microsoft/BotBuilder/issues/1719. Not totally sure why this was written off back then - it definitely seems like non-intuitive behavior.

**Comment by tjsas1** [comment]
I hope this can be done.

**Comment by tjsas1** [comment]
As a work around you may use this

```
if (FacebookHelper.ParseValue(activity.ChannelData) != null)
            {
                text = FacebookHelper.ParseValue(activity.ChannelData);
            }
```

Where as the FacebookHelper is,

```
public class FacebookHelper
    {
        public static string ParseValue(dynamic channelData)
        {
            string payload = null;  
            try
            {
                payload = channelData.message.quick_reply.payload;                
            }
            catch
            {
               
            }

            return payload;
        }

    }
```

**Comment by kienct89** [comment]
## work around solution

you can put this line in the *MessagesController.cs*

`activity.Text = activity.GetChannelData<dynamic>()?.message?.quick_reply?.payload ?? activity.Text;`

**Comment by sgellock** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
