### ISSUE TITLE
[Channel Inspector] documentation incorrectly describes Facebook Location sharing as Mobile-only

### ISSUE THREAD

**Issue by sphanley** [Microsoft/BotBuilder#3556]
In the [Channel Inspector for Facebook](https://docs.botframework.com/en-us/channel-inspector/channels/Facebook?f=Location&e=example1), Location sharing is described as being "mobile-only". However, this is incorrect. Facebook messenger can support location sharing on desktop browsers as well, as long as the user grants the required browser permission. I am working on a bot where I can confirm we're using this functionality on desktop as well as mobile.

**Comment by sphanley** [comment]
This isn't strictly a BotBuilder issue, but I was linked to this issue tracker when I clicked "Send Feedback" on the channel inspector. Hope this helps!

**Comment by fanidamj** [comment]
Can you please let us know if the issue still persists?

**Comment by sphanley** [comment]
Yes, this issue is still valid - you can confirm it by simply clicking the link in my initial post. Location Sharing is still inaccurately listed as being mobile-only.

**Comment by sgellock** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
