### ISSUE TITLE
[Skype] offline and bot does not reply to skype

### ISSUE THREAD

**Issue by vinoth88** [Microsoft/BotBuilder#3557]
Bot handle: trade-bot  
 App ID: 7c5571c3-b5d8-46e9-9a02-0b393c4274c8
 SDK Platform:  Node.js 
 SDK Version: 
Active Channels: Skype, Direct Line, etc. 
Deployment Environment:   Azure App Service 

My bot replies in emulator, web chat in bot dev.botframework.

Whereas it is offline and does not reply to skype.However messages sent from skype are received by my Bot and displayed in log

**Comment by tariksetia** [comment]
@vinoth88
Hi, did you find any solution for this?

**Comment by tariksetia** [comment]
My bot is working now. #3621

**Comment by nwhitmont** [comment]
thanks for the update
