### ISSUE TITLE
web library or reference code?

### ISSUE THREAD

**Issue by xmark** [Microsoft/BotBuilder#356]
I have a small prototype app running at the moment using NodeJS and Restify (very similar to the example code provided).

I can call my app using the emulator, embedded iframe and even slack, but ultimately I want to create my own client.

I have having issues calling the restify API using the javascript botbuilder library since it appears that there is a very particular format that the messages need to conform to.

Is there a JS client library/reference example that I may have missed?

At the moment, I can use the source code to see how it uses and validates Message objects and their associated properties, but that is a slow process...

**Comment by Stevenic** [comment]
You want to look at the [DirectLine REST API](http://docs.botframework.com/sdkreference/restapi-directline/#navtitle). This API lets you talk directly to your bot from your own client. The API has a swagger file which you can use to generate a binding for any language you want.

**Comment by xmark** [comment]
Thanks for that Stevenic, I can see the swagger UI (for those interested: https://directline.botframework.com/swagger/ui/index) but there is really very little detail for each parameter... for example the "from" attribute looks like a string from the swagger doc, but using the bot emulator, it appears to be a complete object.

I will continue to use it however, loving the bot framework. Looking forward to it maturing.

**Comment by Stevenic** [comment]
Thanks... We'll work on improving the docs for DirectLine.
