### ISSUE TITLE
[MS Teams] Sideloaded bot not discoverable for 1:1 chat

### ISSUE THREAD

**Issue by wilcovanesch** [Microsoft/BotBuilder#3561]
## Bot Info
* Bot handle: kirkaldy_KlvHehCPM5Z  
* App ID: 67a4826b-3d7e-44f4-8cfe-432868eff1e7
* SDK Platform: Node.js
* SDK Version: 3.9.1
* Active Channels: MS Teams
* Deployment Environment: Elastic Beanstalk

## Issue Description
Sideloaded bot can be mentioned in team channel yet can't be invited to 1:1 chat by other members of the team, despite manifest.json including "personal" scope.

When opening a new chat, the bot is not available to be invited by anyone except the bot's admin. 

What would I need to do to ensure 1:1 chat can be initiated by anyone in the team the bot is sideloaded to?

**Comment by nwhitmont** [comment]
@wilcovanesch Did you follow all the steps to enable your bot on Teams channel?

## How to load your bot into MS Teams
**Quick MS Teams bot deployment checklist:**
- Did your O365 tenant administrator [enable sideloading](https://msdn.microsoft.com/en-us/microsoft-teams/setup) of apps for your organization?
- Did you [create an app package](https://msdn.microsoft.com/en-us/microsoft-teams/createpackage)
- Did you [sideload your bot app](https://msdn.microsoft.com/en-us/microsoft-teams/sideload) into the relevant team?

**Recommended reading:**
   - [Getting Started with Bots for Microsoft Teams](https://msdn.microsoft.com/en-us/microsoft-teams/bots)
   - [Create the package for your Microsoft Teams app](https://msdn.microsoft.com/en-us/microsoft-teams/createpackage) - aka manifest.json file
   - [Sideloading your app in a team](https://msdn.microsoft.com/en-us/microsoft-teams/sideload)
   - [Testing your Bot](https://msdn.microsoft.com/en-us/microsoft-teams/botsadd)

**Comment by nwhitmont** [comment]
@wilcovanesch see also: https://msdn.microsoft.com/en-us/microsoft-teams/bots1on1

**Comment by wilcovanesch** [comment]
Yes, the app is side-loaded into the relevant team using an app package I validated against [the manifest schema](https://msdn.microsoft.com/en-us/microsoft-teams/schema). 

Each of those articles I've encountered in my journey, but so far haven't found anything in them to give me ideas on why the bot works in a Team context yet not in a 1:1 context with a member of the Team.

**Comment by billbliss** [comment]
@wilcovanesch - how are other users trying to start a conversation with your bot?

**Comment by wilcovanesch** [comment]
They hit the New Chat icon and start typing the name of the bot. I've looked over their shoulders and it just doesn't come up with the bot name (despite them being members of the same Team the bot is side-loaded to).

**Comment by Wajeed-msft** [comment]
@wilcovanesch - were you able to resolve this issue?

**Comment by wilcovanesch** [comment]
@Wajeed-msft - Unfortunately I haven't been able to resolve it.

I'd still be grateful for anyone's help on this.

**Comment by Wajeed-msft** [comment]
@wilcovanesch - We side loaded your bot by creating a new manifest file. We are able to search the bot by name i.e. David Kirkaldy. This worked fine in Teams channel conversation as well as 1:1 conversation.
Could you please share your manifest.json so that we could have a look?

**Comment by wilcovanesch** [comment]
@Wajeed-msft - Many thanks. Hopefully you can find an issue with my manifest. Attached is the app package, containing the manifest.json and icons.

[sideload.zip](https://github.com/Microsoft/BotBuilder/files/1470420/sideload.zip)

**Comment by Wajeed-msft** [comment]
@wilcovanesch - we were able to sideload your manifest and bot was discoverable by admin as well as members in both 1:1 and channel conversation. 
I have attached manifest with a test bot ( name: **MicrosoftTeamsFAQ**). Could you please try to sideload this in your team and check if this is comming up when you search by name (**MicrosoftTeamsFAQ**)?

Also try a scenario where member (not owner) sideloads this app and check if it's discoverable in personal chat.

[package.zip](https://github.com/Microsoft/BotBuilder/files/1474791/package.zip)

**Comment by wilcovanesch** [comment]
Miraculously the bot is discoverable in 1:1 chats now, without having made any change to code or configuration. What I've found after giving more people access is that initially each individual is unable to find the bot, but it shows up after - for example - navigating to Teams and back to Chat. However, it does not show up if the user merely keeps trying the user search or lets it sit for any amount of time.

I'm closing this issue. Thanks for assisting me with it.
