### ISSUE TITLE
Unable to save Facebook channel configuration

### ISSUE THREAD

**Issue by Rigo85** [Microsoft/BotBuilder#3562]
## Bot Info 
* SDK Platform: Node.js
* SDK Version: 3.10.2
* Active Channels: Skype
* Deployment Environment: Azure Bot Service

## Issue Description
I have problems with this issue "Unable to save. Failed to register with Facebook with: BadRequest ID xxxxx"

**Comment by nwhitmont** [comment]
@Rigo85 Please provide your App ID so we can better assist you.

**Comment by Rigo85** [comment]
@nwhitmont App ID: a2323e43-6ab9-4ddd-b163-638c75df1dd9. Thank.

**Comment by ManojAbburi** [comment]
Even i have the same issue, did find the solution ?

**Comment by Rigo85** [comment]
@ManojAbburi No, still the same! I tried again before give you an answer.

**Comment by ManojAbburi** [comment]
I found the solution ! It seems one of the details i entered in bot framework portal is incorrect( in my case "Page access token" i provided is incorrect).Once i correct, i am able to save configuration.

**Comment by fanidamj** [comment]
Closing the issue assuming it as resolved. Feel free to reopen if you any questions or comments.

**Comment by slidenerd** [comment]
I double this, In my case, my error is slightly different
"Unable to save. Failed to register with Facebook with: Forbidden ID: |A/2Fb.b109c71_" I am on node.js as well
