### ISSUE TITLE
Use LUIS in scorable

### ISSUE THREAD

**Issue by chathudev** [Microsoft/BotBuilder#3563]
## Issue Description

I've read that to handle messages globally, I have to use Scorables and set a score based on the user's input. I am wondering if I can use LUIS to parse the user input and set a score based on LUIS intent score.

Is there any way that I can use LUIS inside my Scorable class?

Or do i have to manually call LUIS and get the response and process myself?

**Comment by JasonSowers** [comment]
Yes, you can use LUIS inside a scorable.  You would call LUIS as normal, and process the result the same way you normally would when using LUIS.  This changes the way you use the scorable, but the way you use LUIS is the same.  The scorable changes because you need to inherit from `LuisDialog<Object>` and `[LuisIntent("yourIntent")]` attributes on your methods. here is a SO post about this that may help  https://stackoverflow.com/questions/46557923/bot-framework-use-luis-in-scorables

**Comment by chathudev** [comment]
So when I use LUIS inside scorable, won't it call the LUIS endpoint multiple times? Scorable captures each and every input.If I use LUIS to score the scorable,(1st endpoint call) I can select a scorable and call a dialog. When the dialog is called, since the dialog is a LUIS dialog, it will again call the LUIS to match the LUIS intent inside the LUIS dialog (2nd endpoint call). Am i correct?

**Comment by seca23** [comment]
Hi Jason, 
We are trying to do the same with using LUIS in scorables, and because we are located in South Africa, the concern is that it would slow our bot down to call LUIS for every user message.

**Comment by JasonSowers** [comment]
Sorry for the delay.
Do you guys mind explaining your use cases so I can better understand what you are trying to accomplish, there may be a better way?  thanks

**Comment by chathudev** [comment]
Hi Jason,
I was trying to use LUIS to score a scorable. I was thinking to call LUIS in 'PrepareAsync' method, and based on the resulting intent, I could decide whether or not to further process the scorable. All the examples out there are using keywords to decide this. I find it is a waste since it would call the LUIS for each and every user input.

To resolve this, what I did was, I used keywords in 'PrepareAsync' method to match the scorable and in the 'GetScore' method, I called the LUIS and returned the Score of the matching intent.

Even-though I am unable to match all the scenarios based on keywords, this is OK for me since I am able to reduce the number of LUIS calls.

Is there any other alternative to handle this?

**Comment by JasonSowers** [comment]
If I understand you correctly.  What I would do is this, create your scorable and if your keywords logic gets used the scorable handle the request.  If not the request will be sent to the `RootDialog` here I would forward to a `LuisDialog` to handle the request.  This way you are not calling LUIS every time.  So it sounds like this is what you are doing already.  here is a sample I created using the code from [here](http://www.garypretty.co.uk/2017/04/13/using-scorables-for-global-message-handling-and-interrupt-dialogs-in-bot-framework/)  and just added the functionality you were describing.  It a very simple example located here https://github.com/JasonSowers/scorableLuis

**Comment by JasonSowers** [comment]
Additionally our docs team just posted this blog https://blog.botframework.com/2017/11/10/dialog-management-qna-luis-scorables/
