### ISSUE TITLE
[Skype] Bot not showing in Skype contact list after adding via "Join" URL

### ISSUE THREAD

**Issue by metanite** [Microsoft/BotBuilder#3565]
## Bot Info 
* SDK Platform: Rest
* Active Channels: Skype
* Deployment Environment: ngrok

## Issue Description

I add my bot using the join url to my account and it says that the bot is added but it is not on my contact list. I tried to add the bot to another skype user and it successfully added the bot. Please help me on this. 

## Expected Behavior
Bot will show on contact list

## Actual Results
Not showing

**Comment by IoTGirl** [comment]
Hi @metanite ,
Can you please provide the link to the steps you followed to create and add your bot? You have not provided a bot handle or App ID above.
Sincerely,
IoTGirl

**Comment by nwhitmont** [comment]
@metanite Please provide your bot's App ID so we can better assist you.

**Comment by metanite** [comment]
This is the url https://join.skype.com/bot/46eb8cbe-c9f5-42e0-b256-4c7cb94cbcb0
bot handle is metro_notifier

**Comment by metanite** [comment]
The bot is already to my contact list after several hours. But I still have issues regarding the skype maybe i just create another thread. Thanks

**Comment by JasonSowers** [comment]
Closing as the original issue has been resolved
