### ISSUE TITLE
Bot only works on Emulator. Other channels are displaying 'There was an error sending this message to your bot: HTTP status code GatewayTimeout' error

### ISSUE THREAD

**Issue by nirmalrayan** [Microsoft/BotBuilder#3566]
## Bot Info 
* Bot handle: Medibot_medibuddy
* App ID: dcda60fe-72d4-4796-a728-de8fa3aef2a5
* SDK Platform: Node.js
* SDK Version: Latest
* Active Channels: WebChat, Facebook, Skype
* Deployment Environment: Azure App Service

## Issue Description
Our bot (Medibot, https://medibotmb.azurewebsites.net) has suddenly stopped working on all channels including WebChat. It works perfectly on Emulator though. We've been trying to debug this issue since days and have not been successful with any solutions/suggestions online. I've tried using Log stream and debug console to catch exceptions but there aren't any. Kindly expedite.
![l1](https://user-images.githubusercontent.com/5275500/31172076-ca07b616-a91f-11e7-81b5-3cb8824d8b24.PNG)
![l2](https://user-images.githubusercontent.com/5275500/31172077-ca0b6748-a91f-11e7-8702-c7caae5d0a0a.PNG)
![l3](https://user-images.githubusercontent.com/5275500/31172078-ca0ec244-a91f-11e7-9f29-8785e7fa623d.PNG)

## Code Example
The code is hosted in https://github.com/nirmalrayan/medibot 

## Reproduction Steps
1. Visit medibotmb.azurewebsites.net. This should ideally open WebChat channel's index.html document. 
2. The page tries to load for a long time and throws HTTP status: 500, HTTP subStatus: 1001, HTTP Reason: Internal Server Errror.
3. Bot framework displays the error message 'There was an error sending this message to your bot: HTTP status code GatewayTimeout' for Facebook and Web Chat channels. 

## Expected Behavior
1. Render index.html page with Web Chat iframe.
2. After the user sends first message, the bot welcomes with a hero card. 

## Actual Results
Nothing happens. The page does not get rendered. No exception in thrown in log stream while testing. Even botframework 'Test' does not throw any error in Azure app service log stream. Please assist at the earliest.

<kbd>[node.js](#https://github.com/Microsoft/BotBuilder/issuesq=is%3Aissue+is%3Aopen+label%3A%22Node.js+SDK%22)</kbd>

**Comment by JasonSowers** [comment]
duplicate of https://stackoverflow.com/questions/46564927/why-botframework-bot-only-works-only-on-emulator-and-none-of-the-other-channels

**Comment by nwhitmont** [comment]
closing as duplicate. 

Please don't double-post on GitHub and StackOverflow. We monitor both forums.

**Comment by nirmalrayan** [comment]
This issue has come back to the same bot. I destroyed the entire resource group from Azure and re-created everything, the issue still persists. Currently my bot credentials are:
Bot handle: medibot_4ttx4fdwLSX  
App ID: e3c69ebc-068b-4fa6-a18e-b42b8311adeb
SDK Platform: Node.js
SDK Version: Latest
Active Channels: WebChat, Skype
Deployment Environment: Azure App Service

**Comment by JasonSowers** [comment]
Are you able to post your complete bot code so we can try to reproduce?

**Comment by anilpras** [comment]
@JasonSowers : The code is hosted here https://github.com/nirmalrayan/medibot 
There is a change in the URL https://medibot.azurewebsites.net/

**Comment by nwhitmont** [comment]
@nirmalrayan 
When I checked the new URL, the server returned the following errors:
 
--------
iisnode encountered an error when processing the request.
HRESULT: 0x2
HTTP status: 500
HTTP subStatus: 1001
HTTP reason: Internal Server Error
You are receiving this HTTP 200 response because system.webServer/iisnode/@devErrorsEnabled configuration setting is 'true'.
In addition to the log of stdout and stderr of the node.exe process, consider using debugging and ETW traces to further diagnose the problem.
The node.exe process has not written any information to stderr or iisnode was unable to capture this information. Frequent reason is that the iisnode module is unable to create a log file to capture stdout and stderr output from node.exe. Please check that the identity of the IIS application pool running the node.js application has read and write access permissions to the directory on the server where the node.js application is located. Alternatively you can disable logging by setting system.webServer/iisnode/@loggingEnabled element of web.config to 'false'.
--------
 
It looks like there is a problem with the bot deployment.

**Comment by nirmalrayan** [comment]
Hi Nils,
My code is available at nirmalrayan/medibot. It seems to execute without any errors. I've attached screenshot for reference. 

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
nirmalrayan/medibot

medibot - Conversation Bot for Medi Assist and MediBuddy using Microsoft Bot Framework
 |

 |

 |




Regards,

Nirmal Rayan
M.Tech (Computer Science & Engg.), B.E
+91 99163 68334  

    On Friday, December 8, 2017, 10:39:32 PM GMT+5:30, Nils <notifications@github.com> wrote:  
 
 
@nirmalrayan
When I checked the new URL, the server returned the following errors:

iisnode encountered an error when processing the request.
HRESULT: 0x2
HTTP status: 500
HTTP subStatus: 1001
HTTP reason: Internal Server Error
You are receiving this HTTP 200 response because system.webServer/iisnode/@deverrorsenabled configuration setting is 'true'.
In addition to the log of stdout and stderr of the node.exe process, consider using debugging and ETW traces to further diagnose the problem.
The node.exe process has not written any information to stderr or iisnode was unable to capture this information. Frequent reason is that the iisnode module is unable to create a log file to capture stdout and stderr output from node.exe. Please check that the identity of the IIS application pool running the node.js application has read and write access permissions to the directory on the server where the node.js application is located. Alternatively you can disable logging by setting system.webServer/iisnode/@loggingenabled element of web.config to 'false'.

It looks like there is a problem with the bot deployment.

**Comment by nirmalrayan** [comment]
The only document missing in my code will be the .env file. I could share the file with you if you want to reproduce the issue at your end. Kindly expedite.
Regards,

Nirmal Rayan
M.Tech (Computer Science & Engg.), B.E
+91 99163 68334  

    On Friday, December 8, 2017, 10:45:14 PM GMT+5:30, Nirmal Rayan <nirmal_rayan@yahoo.com> wrote:  
 
 Hi Nils,
My code is available at nirmalrayan/medibot. It seems to execute without any errors. I've attached screenshot for reference. 

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
nirmalrayan/medibot

medibot - Conversation Bot for Medi Assist and MediBuddy using Microsoft Bot Framework
 |

 |

 |




Regards,

Nirmal Rayan
M.Tech (Computer Science & Engg.), B.E
+91 99163 68334  

    On Friday, December 8, 2017, 10:39:32 PM GMT+5:30, Nils <notifications@github.com> wrote:  
 
 
@nirmalrayan
When I checked the new URL, the server returned the following errors:

iisnode encountered an error when processing the request.
HRESULT: 0x2
HTTP status: 500
HTTP subStatus: 1001
HTTP reason: Internal Server Error
You are receiving this HTTP 200 response because system.webServer/iisnode/@deverrorsenabled configuration setting is 'true'.
In addition to the log of stdout and stderr of the node.exe process, consider using debugging and ETW traces to further diagnose the problem.
The node.exe process has not written any information to stderr or iisnode was unable to capture this information. Frequent reason is that the iisnode module is unable to create a log file to capture stdout and stderr output from node.exe. Please check that the identity of the IIS application pool running the node.js application has read and write access permissions to the directory on the server where the node.js application is located. Alternatively you can disable logging by setting system.webServer/iisnode/@loggingenabled element of web.config to 'false'.

It looks like there is a problem with the bot deployment.

**Comment by nirmalrayan** [comment]
Fixed it! Turns out that I had defined TCP port in Azure Application Settings (of my app service) which is in straight violation because Azure uses NamedPipes within IIS. So, if you've defined PORT = <<PORT NUMBER>> in your application settings, remove it and restart your app service. This problem should be resolved.
