### ISSUE TITLE
[Slack] Interactive Messages not working?

### ISSUE THREAD

**Issue by harshil94** [Microsoft/BotBuilder#3567]
## Issue Description
I am sending the same JSON response to Slack Channel, Facebook Channel and Web Channel (Bot framework in built) to display buttons. It works fine on Facebook messenger and bot framework web chat. But it doesn't display the content as buttons in Slack Channel. Instead, it displays all the buttons with a preceding asterisk. Is slack channel supported with same interactive message components as other channels are currently supported?

**Comment by EricDahlvang** [comment]
Please share the .json you're sending.

**Comment by nwhitmont** [comment]
@harshil94 Are you using .NET or Node.js SDK for BotBuilder? Please post your bot code and associated JSON response so we can better assist you.

**Comment by harshil94** [comment]
Here I am creating a response object from the bot_object given by bot builder.
`let response = new builder.Message(bot_object);`

Then I am adding some data to display imBack Herocards on channel and the final json which I am sending in response is something like this.

`
{
  "type":"message",
  "agent":"botbuilder",
  "source":"slack",
  "address":
    {
      "id":"<channel id>",
      "channelId":"slack",
      "user":
        {
          "id":"<user id>",
          "name":"<user name>"
        },
      "conversation":
        {
          "isGroup":false,
          "id":"<conversation id>"
        },
      "bot":
        {
          "id":"B5E70L1SA:T5C069UQZ",
          "name":"<slack bot name>"
        },
      "serviceUrl":"https://slack.botframework.com"
    },
  "text":"Hello! Will be glad to assist for any help required on below incidents.",
  "suggestedActions":
    {
      "to":[],
      "actions":
        [
          {
            "type":"imBack",
            "value":"Create Ticket",
            "title":"Create Ticket"
          },
          {
            "type":"imBack",
            "value":"Check Status",
            "title":"Check Status"
          },
          {
            "type":"imBack",
            "value":"Reopen",
            "title":"Reopen"
          }
        ]
    }
}
`

Funny thing is, when I am sending the same response, it shows hero cards on facebook messanger as well as webchat interface of botframework. But it shows the response on slack channel as plain text. See the response on various channels as below:

Facebook messanger UI for Hero card:
![facebook_herocard](https://user-images.githubusercontent.com/24470608/31212695-9a9e9250-a9bf-11e7-805c-1b2509d34c8d.PNG)

Botframework webchat Interface UI for Hero card:
![webchat_botframework_herocard](https://user-images.githubusercontent.com/24470608/31212696-9aa07606-a9bf-11e7-8596-08d193d2d1bb.PNG)

Slack UI for Hero card:
![slack_herocard](https://user-images.githubusercontent.com/24470608/31212697-9aa08736-a9bf-11e7-91ef-4bc0b1f1f367.PNG)

**Comment by harshil94** [comment]
Any updates please?

**Comment by nwhitmont** [comment]
@harshil94 The `suggestedActions` you have configured in your message object will be displayed differently based on the channel (aka Messenger vs Slack). What you are seeing is the expected behavior of Slack channel.

You can verify this by looking at the [Channel Inspector, set on channel: Slack, feature: Suggested Actions](https://docs.botframework.com/en-us/channel-inspector/channels/Slack?f=SuggestedActions&e=example1)
![slack documentation bot framework](https://user-images.githubusercontent.com/3075047/32017976-3728c15a-b97d-11e7-8c64-07af1244938e.png)


To send Slack-specific formatted messages, you need to put your custom message data in the `channelData` object of your message. 

You can learn more about how to use the `channelData` under the section Create Full Fidelity Slack Messages:
https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-channeldata#create-a-full-fidelity-slack-message

**Comment by Drag13** [comment]
Hi guys!

Here it is 2019  and I am voting for reopening this bug. 

Key concept of the BotFramework is "Write once - use across multiple channels". And now, such obvious control as buttons just not working. Don't you think this break the logic?

**Comment by harshilt94** [comment]
I would like to know if there is any way in which we can create simple action/selection buttons in Slack messenger similar to the buttons in Facebook messenger.

**Comment by Drag13** [comment]
@harshilt94 

I've used  Microsoft.Bot.Schema.HeroCard
It will looks like this:

![image](https://user-images.githubusercontent.com/8222114/51822388-d00e5980-22e4-11e9-888d-2ce38c465493.png)

**Comment by harshilt94** [comment]
@Drag13 , does it behave exactly like a button in Facebook messenger?

**Comment by Drag13** [comment]
@harshilt94 No idea about Facebook, but this is only one options that works as real buttons in Slack for me.

**Comment by harshilt94** [comment]
A button's behavior on Facebook is **When you click on a button, the text inside should get populated as a user message as simple text**. I want something similar to this.

@Drag13 How does hero card behave on slack? Or is there any other component in slack which can mimic the functioning of button as I explained above?
