### ISSUE TITLE
Showing Tables in Bot Framework

### ISSUE THREAD

**Issue by neetgupta7** [Microsoft/BotBuilder#3568]
* SDK Platform:  .NET
* SDK Version: 3.9.1
* Active Channels: All
* Deployment Environment: Azure App Service

## Issue Description
I want to show my data in table structure. I know Adaptive cards can be used for beautiful data depiction. But they are still on road map of many channels (except webchat). Is there any other approach which is channel agnostic and can be used.

**Comment by stevengum97** [comment]
@neetgupta7 there aren't any at this time. What you can do is use a .NET library to create the table then downrender to a simple image, then send the image in a RichCard or as a plain image to your users. An example of this (for the Node.js SDK, unfortunately) is [botbuilder-vega](https://www.npmjs.com/package/botbuilder-vega), where a chart or table is created then converted to an image.

A .NET library that you could use is [oxyplot](https://github.com/oxyplot/oxyplot), which I've seen used in the context of botbuilder.
