### ISSUE TITLE
Skype bot responding to messages erratically [Skype] [BotFramework]

### ISSUE THREAD

**Issue by anujaparikh23** [Microsoft/BotBuilder#3573]
## Bot Info 
* Bot handle: CallScheduleBot 
* App ID: f079f4c0-39a6-4825-81e2-0da3a7c13b53

* SDK Platform:  Node.js 

* Active Channels: Skype, Webchat
* Deployment Environment: ngrok

## Issue Description
Skype bot is responding erratically to messages. Sometimes it responds, sometimes it wont respond at all. I am confused at its behaviour. When it does respond it throws this error at certain specific parts.

Error: Request to 'https://smba.trafficmanager.net/apis/v3/conversations/29%3A1r7M8Z1GxDAsWPxGYOZl6kuBBtX8csrrh5ujE7mGFvyI/activities' failed: [400] Bad Request

## Code Example
There is no issue with the code as the bot works perfectly fine on the webchat channel. Even the bot framework doesnt mention any errors. The requests i send to skype are not posted to my ngrok many times.

## Expected Behavior
I want it to respond properly, the way its doing at the webchat portal.

## Actual Results
![1](https://user-images.githubusercontent.com/17399975/31215719-48de3e7a-a9ce-11e7-9200-557d869950cd.png)

Here the bot responded after saying hi 5times. then again stopped responding. This was from yesterday, today its stopped responding completely

**Comment by JasonSowers** [comment]
Confirmed this behavior in skype and also noticed webchat is not working at all either.

**Comment by anujaparikh23** [comment]
@JasonSowers The bot is enabled by ngrok, that must not be enabled when you checked. I had checked by the webchat many times yesterday and it was working fine. Today i am unable to login to the dev,botframework portal hence cant check it now.

**Comment by anujaparikh23** [comment]
@JasonSowers Currently the bot is responding regularly but throwing this error at certain points. No clue what this error is about:

Error: Request to 'https://smba.trafficmanager.net/apis/v3/conversations/29%3A1r7M8Z1GxDAsWPxGYOZl6kuBBtX8csrrh5ujE7mGFvyI/activities' failed: [400] Bad Request

**Comment by anujaparikh23** [comment]
Hi, was able to solve the issue. you can close the ticket

**Comment by zell12** [comment]
hi anuj. sorry if i'm responding to a close thread, but would you mind sharing how you resolved this? because im facing the same issue.
after a long period of inactivity, the bot wouldn't respond on the skype channel, unless i connect to the bot endpoint via emulator (POST conversationupdate), then he will be able to respond in skype.
i also checked the application insights failures and nothing seem to have logged during those times i chat to the bot thru skype after long idle time.
this always happens and i'm not sure what to check now.

**Comment by nidhisaini28** [comment]
it started responding on its own. No particular thing we did to solve the issue

**Comment by anujaparikh23** [comment]
it started working properly on its own. We din't do anything to solve it.
