### ISSUE TITLE
Bot wont reply on skype

### ISSUE THREAD

**Issue by metanite** [Microsoft/BotBuilder#3574]
## Bot Info 
* Bot handle:  metro_notifier
* App ID:  46eb8cbe-c9f5-42e0-b256-4c7cb94cbcb0
* SDK Platform: Rest
* SDK Version: 
* Active Channels: Skype
* Deployment Environment: ngrok

## Issue Description

I already added my bot to skype and chatted successfully but when i try to change the messaging endpoint the skype will not respond, but it works on webchat. I try to view the ngrok dashboard but it seems that skype can't reach the messaging endpoint.

What is happening here?

Note: the new messaging endpoint has valid ssl

## Reproduction Steps
1. Change messaging endpoint 
2. Chat the bot in skype

## Expected Behavior

Bot will still reply cause the messaging endpoint only is changed
## Actual Results
Bot not replying

**Comment by anujaparikh23** [comment]
I am having a similar issue. Have raised an issue as well https://github.com/Microsoft/BotBuilder/issues/3573

Let me know if you get any solution.

**Comment by JasonSowers** [comment]
confirmed this behavior in skype, but was also unable to get it to work on webchat: 
![image](https://user-images.githubusercontent.com/6301037/31238607-514175c4-a9af-11e7-9fe5-458204596d22.png)

**Comment by metanite** [comment]
It seems that after several hours the bot is working already. I still don't know why it takes hours for skype to reach the messaging endpoint. Thanks.

**Comment by anujaparikh23** [comment]
my bot has also started working on its own all of a sudden

**Comment by JasonSowers** [comment]
Glad you both got them working.  It sounds like there was an issue with Skype, but we are unaware of any known issues.

**Comment by zidaneymar** [comment]
@JasonSowers Maybe you should set up app_id and password.
