### ISSUE TITLE
[LUIS] How to manually trigger call to LUIS app?

### ISSUE THREAD

**Issue by harshithkashyap** [Microsoft/BotBuilder#3575]
* SDK Platform: Node.js
* SDK Version: 3.9.1
* Active Channels: DirectLine
* Deployment Environment: Azure App Service

## Issue Description
Since the following snippet triggers calls to LUIS each time the bot receives a message, we are trying to trigger the call to LUIS app manually.
```javascript
bot.recognizer(new builder.LuisRecognizer(process.env.LUIS_APP_URL));
```

Along with text based input, we provide users a list of buttons to choose input from. The usecase would be "Choose a list a departments" and render the departments as buttons. The buttons are clickable with postback values such as "Customer.Service", "Operations", "Billing" etc. 

Since the above values are preset and can be matched directly in the application using a [custom intent recognizer](https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-recognize-intent-messages) with a simple switch case,  is it possible to trigger the call to LUIS in the final step/default case such as? 

```javascript
bot.recognizer({
  recognize: function (context, done) {
  var intent = { score: 0.0 };

        if (context.message.text) {
            switch (context.message.text) {
                case 'Billing':
                    intent = { score: 1.0, intent: 'Billing' };
                    break;
                case 'Customer.Service':
                    intent = { score: 1.0, intent: 'Customer.Service' };
                    break;
                default:
                      //Trigger call to LUIS.
            }
        }
        done(null, intent);
    }
});
```

**Comment by nwhitmont** [comment]
Reopen if further questions.
