### ISSUE TITLE
context.Wait(); doesn't wait when using Unit Tests

### ISSUE THREAD

**Issue by michaelhutchful** [Microsoft/BotBuilder#3577]
## Bot Info 
* Bot handle: 
* App ID: 
* SDK Platform: .NET
* SDK Version: 3.9.1
* Active Channels: Facebook
* Deployment Environment: Azure App Service

## Issue Description
I am following the tutorial below to unit test my bot, however everytime the unit test hits a context.Wait in a dialog, it will move on to ResumeAfter method.
https://blogs.msdn.microsoft.com/kenakamu/2017/06/20/devops-with-bot-framework-chat-for-business-application-1-en/

## Reproduction Steps
1.
2.
3.

## Expected Behavior
What I expect is that when I send 1 message and it hits context.Wait(method), it should wait for the next input from the test method

## Actual Results
The Dialog continues to propagate to the next ResumeAfter whenever it hits context.Wait(method)

**Comment by EricDahlvang** [comment]
That isn't how context.Wait(method) works.  It is not an async await pattern type of wait.  What actually happens is that a handler is setup internally, so the next incoming message will resume at the method.  This enables dialog flow (having different resume methods inside the same dialog).  There is some documentation describing this here: https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-dialogs#implementation-details 

> When the conversation first starts, the dialog does not contain state, so Conversation.SendAsync constructs EchoDialog and calls its StartAsync method. The StartAsync method calls IDialogContext.Wait with the continuation delegate to specify the method that should be called when a new message is received (MessageReceivedAsync).

Will Portnoy also explains the concept here: https://github.com/Microsoft/BotBuilder/issues/210

Also, for your reference, there are some unit test examples in the Bot Builder source found here: https://github.com/Microsoft/BotBuilder/tree/master/CSharp/Tests/Microsoft.Bot.Sample.Tests

**Comment by michaelhutchful** [comment]
@EricDahlvang I think you missunderstood my question. It was more about the fact that the dialog doesn't wait for the next message before moving to the resume method. That's beside the point. I found the root cause of my issue. I was trying to test a secondary dialog, it seems like the DialogTests were only written for root dialogs. Thank you so much for the docs, a bit more reading helped me find out the real issue.
