### ISSUE TITLE
[LUIS] Cannot assign new key for app

### ISSUE THREAD

**Issue by annevah** [Microsoft/BotBuilder#3579]
I created a new key from azure portal, but I can not assign the key to LUIS. This is what I am getting loding.... Inspite of trying for hours, the result is same.
![image](https://user-images.githubusercontent.com/30615829/31276091-b7d5b94a-aab7-11e7-8fb3-7737512a5e2d.png)
Is there anything else that I have to do?

**Comment by sovietmenace** [comment]
Yeap. Same here. It just sits there. Nothing is loading.

**Comment by stevengum97** [comment]
I'm very sorry for the delay in response! This issue has been replicated and the team is working on a fix.

**Comment by annevah** [comment]
@stevengum97  Though there is a significant delay, it's working now ! 😄 Thanks 
![image](https://user-images.githubusercontent.com/30615829/31368479-b23da560-ad9b-11e7-8a62-33da19b89f6b.png)
