### ISSUE TITLE
How to pass message in Chain to child Dialog.and process it immediately.

### ISSUE THREAD

**Issue by Praggie** [Microsoft/BotBuilder#358]
I have following root dialogue:

```
public class WelcomeDialog
    {
        public static readonly IDialog<string> dialog = Chain.PostToChain()
               .Switch<Message, IDialog<string>>(
                   new Case<Message, IDialog<string>>(msg =>
                   {
                       var text = msg.Text;
                       var regex = new Regex("^query");
                       return regex.Match(text).Success;
                   }, (context, msg) =>
                   {
                       var message = msg;
                       return Chain.From(() => new GenerallQueryDialog());
                   }),
                  new DefaultCase<Message, IDialog<string>>((context, msg) => new HelpDialog()))
               .Unwrap()
               .PostToUser();
    } 
```
What I want is to whenever user message any textstarting with "query", I want to start GeneralQueryDialog. (It is a LuisDialog) and let the dialog respond. Above code does Initialize the dialog, Calls the StartAsync method of dialog , but message is not processed. MessageReceived is not call.Message is being processed second time.  I want to process the message immediately. How to do that?

I tried to pass message variable in GeneralQueryDialog constructor but I got Serialization errors. Please suggest a work around, I am stuck on this.

**Comment by willportnoy** [comment]
We recently added a IDialogStack.Forward method - does that help?

Yes, Message is not marked serializable.  You might consider enabling the reflection serialization surrogate to serialize Messages if IDialogStack.Forward does not work for you.

**Comment by willportnoy** [comment]
I'm going to close this item for now - feel free to re-open to discuss further.
