### ISSUE TITLE
[Question]  How to intercept user intent with "routing" middleware?

### ISSUE THREAD

**Issue by amitbend** [Microsoft/BotBuilder#3581]
## Bot Info 
* SDK Platform: Node.js 
* SDK Version: 3.11.0
* Active Channels: messenger
* Deployment Environment: localhost

I'm trying to intercept messages to send to my analytics server.
I'm looking to send it some data such as: messages, intent, resulting dialog.

I tried to use the routing middleware of universalBot in this fashion:
```js
bot.on('routing',(session)=>{
    console.log(session.intent);
    console.log(session);
})
```
But it seems like the intent is undefined, and the only way I manage to see it is through triggerAction => onFindAction function.

I can use this method but it seems like a hack, is there a good way to intercept the intent data with middleware?

I'm using the Node.js SDK with botbuilder-apiai

**Comment by nwhitmont** [comment]
Assuming you are using Restify server module - you can use Restify's bundled `restify.requestLogger` plugin with the [bunyan](https://www.npmjs.com/package/bunyan) logger as described in this post: https://stackoverflow.com/questions/27440370/how-to-use-restifys-requestlogger

**Comment by JasonSowers** [comment]
Please let us know if it did not resolve your issue
