### ISSUE TITLE
[Node.js SDK] send middleware is not maintaining order

### ISSUE THREAD

**Issue by ubreddy** [Microsoft/BotBuilder#3583]
## Bot Info 
* SDK Platform: Node.js
* SDK Version: 3.9.1
* Active Channels: webchannel
* Deployment Environment: app service

## Issue Description

I am logging the sent messages in the middleware "send" function. Usually the order is maintained except for the scenario below.
```js
session.send(promptText);

builder.Prompts.choice(session, " ", optionsSet, {
    listStyle: builder.ListStyle.list, 
    maxRetries: 0
});
```
the middleware function:

```js
send: function (message, next) {
      console.log(message.text)
}

```
## Code Example

```js
session.send(promptText);

builder.Prompts.choice(session, " ", optionsSet, {
    listStyle: builder.ListStyle.list, 
    maxRetries: 0
});
```
## Expected Behavior

the order should have been maintained. send function called first for promptText and then for the options...

## Actual Results

The order is sometimes. (not all times) reversed.

**Comment by nwhitmont** [comment]
@ubreddy I'm unable to reproduce the problem with the code provided. Can you post a complete working bot that reproduces the issue?

**Comment by ubreddy** [comment]
looks like Nodejs async nature is the cause.
but the botbuilder.Prompts.choice(session,promptText, choices) is being considered as two messages and sometimes "choices" is being logged first and "promptText " next sometimes in my logs.
Isnt it one Send message?

 

    On Tuesday 10 October 2017, 5:58:10 AM IST, Nils <notifications@github.com> wrote:  
 
 
@ubreddy I'm unable to reproduce the problem with the code provided. Can you post a complete working bot that reproduces the issue?

**Comment by nwhitmont** [comment]
As stated in my previous comment, the async nature of Node.js runtime does not guarentee any specific order of the messages unless you are using strict async-waterfall control statements.

For more information on how the Node.js runtime processes events, see:
- https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick/
- https://nodesource.com/blog/understanding-the-nodejs-event-loop/
