### ISSUE TITLE
[LUIS] Inconsistent application of Composite entities

### ISSUE THREAD

**Issue by Bazorpazorps** [Microsoft/BotBuilder#3584]
## Issue Description
LUIS is not consistently wrapping composite entities. It's not clear why it will and will not at times. It's a problem since it creates complexity but doesn't give consistent, helpful results. 

## Example
I have apps that have a composite {$Contact} entity, with child entities such as [$ContactName]. It will work consistently in a standalone app with only one intent and a handful of entities. However, combining the app into a larger app with a complexity of intents and entities throws it off.

## Reproduction Steps
An example of a complex entity setup:
<img width="1236" alt="screen shot 2017-10-09 at 10 22 49" src="https://user-images.githubusercontent.com/32053701/31322119-1cb441a2-acdd-11e7-90c4-54fa0e30f0b1.png">

Behaviour with the standalone app:
<img width="1272" alt="screen shot 2017-10-09 at 10 27 11" src="https://user-images.githubusercontent.com/32053701/31322116-10af4974-acdd-11e7-9179-797a39623623.png">

Behaviour with the more complex app:
<img width="999" alt="screen shot 2017-10-09 at 10 22 27" src="https://user-images.githubusercontent.com/32053701/31322120-2028513e-acdd-11e7-8c43-8c6ece09e917.png">

## Follow-up Question
Taking this into consideration, is LUIS setup to deal better with simple, or with composite entities?

**Comment by stevengum97** [comment]
@Bazorpazorps, I'm afraid I don't understand what the background information is in regards to the question at hand.

Going off of your screenshots,  the last one indicates the `Auto compiled model`'s last training was on September 29th versus `Ability-Contacts` training on October 6th, along with a different version number from your `Ability-Contacts` application. While the versioning difference does make sense, your more complex app doesn't look like it's up to date (with training), which could cause entity recognition differences.
