### ISSUE TITLE
onSelectRoute is does not override the default function

### ISSUE THREAD

**Issue by amitbend** [Microsoft/BotBuilder#3586]
## Bot Info 
* SDK Platform: Node.js 
* SDK Version: 3.11.0
* Active Channels: messenger
* Deployment Environment: localhost

## Issue Description
I created a `onSelectRoute` to override the `selectRoute` function, to use my own logic before calling the original implementation.
It seems like the function is not being called for some reason.

## Code Example
```js
const bot = new builder.UniversalBot(connector);

bot.onSelectRoute(function (session, route) {
    console.log('here');
    // some functionality
    this.defaultSelectRoute(...arguments);
});
```

**Comment by nwhitmont** [comment]
@amitbend What are you trying to accomplish here exactly? 

Can you share more context about your specific use case?

**Comment by amitbend** [comment]
@nwhitmont Yes.
I'm trying to add some logic for a fallback situation when no route has been selected.
I want to use this method as a replacement for middleware - as I can capture the intent information at this point, and send it to my analytics server.
