### ISSUE TITLE
[Question] After redeployment - Failed delivery when talking to my bot on Skype

### ISSUE THREAD

**Issue by carvalThi** [Microsoft/BotBuilder#3587]
## Bot Info 
* Bot handle: wavestone_bot
* App ID: f6cce38c-8cd7-4fb5-86d6-994bdae315da
* SDK Platform: Node.js (wrong, my bad)
* Active Channels: Skype + Webchat
* Deployment Environment: company server

## Issue Description
Hello,

my bot used to work perfectly on Skype, but i have recently deleted it to put it on another Microsoft account. It now works with the webchat, but not on Skype. I receive the failed delivery error.

Could you please help ?

(FYI : the bot is not published yet)

**Comment by EricDahlvang** [comment]
Have you tried removing the Skype Channel, and re-adding it in dev.botframework.com settings ?

**Comment by carvalThi** [comment]
Yes, i have tried removing and re-adding the channel as well as deleting and re-adding the bot contact. It did not solve it.

**Comment by EricDahlvang** [comment]
What version of the node.js sdk are you using?  

Can you share your bot's code?

**Comment by carvalThi** [comment]
Actually, i did a mistake filling up the questionnaire. I'm not using the bot framework Node.js SDK. I'm just using Node.js in general for my bot.
I don't think the issue is in my bot's code as it has not changed in a while and the bot was working before I deleted it to add it to a different microsoft account.

To me, it looks that a similar issue than this topic https://github.com/Microsoft/BotBuilder/issues/1309

**Comment by nwhitmont** [comment]
When I tried to look up your bot via the App ID you provided, the bot name did not match your bot's name "wavestone_bot".

Can you verify your bot's App ID and handle? Also, please provide the Skype "Join" URL for your bot to verify during testing.

**Comment by carvalThi** [comment]
Hi,

my bot's App ID corresponds to the bot handle i provided, as you can see in the screenshot below. The problem may come from there but i don't know how to solve it.

Here is the Skype Join link if you want to try it out : https://join.skype.com/bot/f6cce38c-8cd7-4fb5-86d6-994bdae315da.

I'm not sure i understand your last question. I took the previous API endpoint from the bot on the other account and put it in the new bot.


![bot handle app id](https://user-images.githubusercontent.com/11056913/31374155-168a45ea-ad9d-11e7-9c6b-e64af7390795.PNG)

**Comment by carvalThi** [comment]
Hello, it suddenly started working again ...
Hard to explain. Maybe a synchronization time somewhere ...

Thank you for your time anyway
