### ISSUE TITLE
[LUIS] I am trying to trigger a new dialog whenever a response matches the registered LUIS intent

### ISSUE THREAD

**Issue by teamplumaa** [Microsoft/BotBuilder#3588]
## Expected Behavior
Whenever the intent is matched during the conversation, I want the dialog to be triggered that matches that intent without erasing the entire dialog stack. 

## Actual Results
The intent is not being recognized during the conversation when I use beginDialogAction. However, whenever I used triggerAction, the intent was recognized and the waterfall dialog was loaded. But triggerAction also only worked at the begin of the entire dialog.

Here is the code without the waterfall. 

------------------------------------------

```js
bot.dialog('AskAboutPersonalDetails', [ 
 // waterfall dialog
])
.beginDialogAction('AskPersonalQuestions', 'AskAboutPersonalDetails', {
    matches:'AskAboutPersonalDetails',
});
```

I also tried **bot.beginDialogAction** as well as adding a string like **'/AskAboutPersonalDetails'**. But those options do not work either.

**Comment by nwhitmont** [comment]
@teamplumaa Please post your entire bot code, including the intent recognizer and LUIS setup.  It's difficult to see any problems with the small code snippet.

**Comment by teamplumaa** [comment]
// Listen for messages from users
server.post('/api/messages', connector.listen());

var bot = new builder.UniversalBot(connector, (session) => {
    session.sendTyping();
    setTimeout(function () {
        session.send("Hello there...");
    }, 3000);
    session.endDialog(`I'm sorry, I did not understand '${session.message.text}'.\nType 'help' to know more about me :)`);
});

var luisRecognizer = new builder.LuisRecognizer(process.env.LUIS_MODEL_URL).onEnabled(function (context, callback) {
    var enabled = context.dialogStack().length === 0;
    callback(null, enabled);
});
bot.recognizer(luisRecognizer);

bot.dialog('Pleasantries', [
    (session, args, next) => {
        var greetings = builder.EntityRecognizer.findEntity(args.intent.entities, 'greetings');
        var datetimeV2 = builder.EntityRecognizer.findEntity(args.intent.entities, 'datetimeV2');


        if (greetings && greetings.resolution.values.length > 0) {
            session.dialogData.greetings = greetings.resolution.values[0];
        }

        session.dialogData.firstmessage = session.message.text;

        if (!session.dialogData.greetings) {
     
            builder.Prompts.text(session, `it seems you are having a tough day, but i hope I can make it better by recommending the best pizza place to you`);
        } else {
            next();
        }
    },

(session, result, next) => {
        builder.Prompts.text(session, `But first can you tell me your name please?`);
    },

  
(session, result, next) => {
        session.dialogData.name = result.response;
        session.send(`Glad to meet you ${session.dialogData.name}`);
        builder.Prompts.text(session, `Tell me about yourself ${session.dialogData.name}. What do you do? What do you do for fun?`);
    },

    (session, result, next) => {
        session.dialogData.about = result.response;
        about = session.dialogData.about;
    }
])
.triggerAction({matches: 'Pleasantries'});


bot.dialog('AskAboutPersonalDetails', [
    (session, args, next) => {

        var job = builder.EntityRecognizer.findEntity(args.intent.entities, 'job');  
        var interests = builder.EntityRecognizer.findEntity(args.intent.entities, 'interests');

        if (job && job.resolution.values.length > 0) {
            session.dialogData.job = job.resolution.values[0];
        }

        if (interests && interests.resolution.values.length > 0) {
            session.dialogData.interests = interests.resolution.values[0];
        }

        session.dialogData.about = session.message.text;

        if (!session.dialogData.job) {
            builder.Prompts.text(session, `${session.dialogData.name}, what do you do?`);
        }  else {
            next();
        } 
    },

    (session, result, next) => {
        if (!session.dialogData.job) {
            session.dialogData.job = result.response;
        }

        if (!session.dialogData.interests) {
            
            builder.Prompts.text(session, 'What are the activities that you are passionate about or interested in?');
        }  else {
            next();
        } 
    },
    (session, result, next) => {
        if (!session.dialogData.interests) {
            session.dialogData.interests = result.response;
        }

        builder.Prompts.text(session, `Now that you have told me as much as I need to know, what kind of food do you like?`);
    },
    (session, result, next) => {
        session.beginDialog('/Finish');
    }

])
.beginDialogAction('AskPersonalQuestions', 'AskAboutPersonalDetails', {
matches:'AskAboutPersonalDetails',
});

bot.dialog('/Finish', [
// waterfall dialog to finish conversation will go here
])
.beginDialogAction('FinishAction', '/Finish', {
matches:'/Finish',
});

**Comment by stevengum97** [comment]
So an example might be the user is on the 2nd waterfall step of the `'AskAboutPersonalDetails'` dialog when they decide to say `"Hello"` (or something else) and trigger the `'Pleasantries'` dialog?

You're using this following code:
```js
// reformatted to make it easier to see the code
var luisRecognizer = new builder.LuisRecognizer(process.env.LUIS_MODEL_URL)
  .onEnabled(function (context, callback) {

    var enabled = context.dialogStack().length === 0;
    callback(null, enabled);
});
```

The `var enabled` line means that whenever you're in the middle dialog, you don't want your `LuisRecognizer` to fire. You need to create a different condition to use when you want to enable or disable your recognizer.

**Comment by fanidamj** [comment]
I'm marking this as answered and closing it for now. If there are any other questions or comments on the issue, please feel free to post them here.
