### ISSUE TITLE
[.Net SDK] Sorry, my bot code is having an issue- Giving error in all the channels

### ISSUE THREAD

**Issue by usheveta** [Microsoft/BotBuilder#3590]
## Bot Info 
* Bot handle: 
* App ID: 
* SDK Platform:  .NET 
* SDK Version: 3.9.1
* Active Channels:  Skype, MS Teams, web chat
* Deployment Environment: Azure App Service

## Issue Description
I had registered my bot with 3 different channels - Skype, MS Teams and Web Chat and till yesterday all the channels were working fine and then they stopped working.
Again I tried today, so its working.
I'm not able to understand what is causing the issue.

## Reproduction Steps
1.
2.
3.

## Expected Behavior
Bot was working fine a day before in all the channels.

## Actual Results
Bot started giving error: Sorry, my bot code is having an issue- in all the channels
Its working fine in Emulator.

Thanks,
Sheveta

**Comment by nrobert** [comment]
Can you for example use Application Insights to get the real error behind "my bot code is having an issue", which is the text sent when an error 500 is thrown?

Just like that, it's quite impossible to help

**Comment by usheveta** [comment]
Sorry, I don't know where to find in Application Insight as I'm new to Bot framework and Azure. Could u pls. let me know where exactly I should check in "Application Insights"?

**Comment by usheveta** [comment]
Sure I'll update on the same when I'll get the issue as right now its working fine.
