### ISSUE TITLE
[NodeJS SDK, LUIS] builtin.datetimeV2 doesn't work on EntityRecognizer.resolveTime

### ISSUE THREAD

**Issue by CristianPQ** [Microsoft/BotBuilder#3591]
* SDK Platform: Node.js
* SDK Version: 3.8.4
* Active Channels: Skype, MS Teams, Slack, Direct Line
* Deployment Environment: ngrok, Azure App Service

## Issue Description
builtin.datetime is deprecated for english so I have to use builtin.datetimeV2, and 
`EntityRecognizer.resolveTime` is not working anymore.

## Code Example
```
results.entities = [
    {
        entity: '6th of october',
        type: 'builtin.datetimeV2.date',
        startIndex: 24,
        endIndex: 37,
        resolution: {
            values: [
                { timex: 'XXXX-10-06', type: 'date', value: '2017-10-06' },
                { timex: 'XXXX-10-06', type: 'date', value: '2018-10-06' }
            ]
        }
    },
    {
        entity: 'entityA',
        type: 'entityA.company',
        startIndex: 16,
        endIndex: 19,
        score: 0.963010132
    }
]

let dateTwo = builder.EntityRecognizer.resolveTime(results.entities);
```

## Expected Behavior
dateTwo = '2017-10-06'

## Actual Results
dateTwo = undefined

**Comment by rajarameshvarma** [comment]
Is there a target date to fix this?

**Comment by CristianPQ** [comment]
There is not a deadline, thx

**Comment by fanidamj** [comment]
Can you please let us know if the issue still persists?

**Comment by sgellock** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
