### ISSUE TITLE
[REST API, Node.js SDK, Direct Line] Set User Data not working as expected - returns 500 internal server error

### ISSUE THREAD

**Issue by dhavalpanchalispl** [Microsoft/BotBuilder#3592]
## Bot Info 
* Bot handle: test_autobot
* App ID: 7245165b-6994-405a-9808-41831260a39b
* SDK Platform: Node.js Bot Builder REST API
* Active Channels: Direct Line

## Issue Description
I want to set user specific data to Bot in direct line channel. For this, I am using REST API to set user data to bot as mentioned in [REST API Reference to set user data](https://docs.microsoft.com/en-us/bot-framework/rest-api/bot-framework-rest-connector-api-reference#set-user-data). But whenever we make this REST API request for Direct Line channel, it returns 500 internal server error in response. Check below details for REST request, 

**Request**,

Request Type: POST

URL:
https://directline.botframework.com/v3/botstate/directline/users/1392603704147108

Headers:
Authorization: Bearer w4oLaUMQPEY.dAA.SQBDADMARQBQAFMARgBMAEQAbABkAEkAYgBUAGEAVwBsAEwAdABEAGwAcAA.DP7oSwoc0wE.fvMPwMjKBXc.tx9TeK8fWd432O056x3uHb5jKe_OYFlsStCbGkcn4ds
Content-Type: application/json

Body JSON payload (raw):
{"data":{"myData":"myUserRelatedData"}}

## Reproduction Steps
You need to get Bearer to set in header for direct line channel. You can set any userId and start conversation in direct line. To get Bearer and Start Conversation you can use below sample,
https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node/core-DirectLineWebSockets. Then use this **userId** and **Bearer** in REST API request to set user data as mentioned above. You can use Postman to reproduce this issue.
REST API reference to set user data,
https://docs.microsoft.com/en-us/bot-framework/rest-api/bot-framework-rest-connector-api-reference#set-user-data

**Response**,
Status: 500 internal server error

## Expected Behaviour
REST API for set user data for direct line channel should be done successfully without any error response.

## Actual Results
REST API for set user data for direct line channel returns 500 internal server error.

**Comment by fanidamj** [comment]
Can you please let us know if the issue still persists?

**Comment by stevkan** [comment]
Closing due to lack of response.
