### ISSUE TITLE
[.Net SDK] Pass User Login Information from Sharepoint to Chat Bot Web  app

### ISSUE THREAD

**Issue by satish7389** [Microsoft/BotBuilder#3594]
We build a Chabot using C# bot framework  and embedded in a Sharepoint site using following script.

<!DOCTYPE html>
<html>
  <head>
    <link href="https://cdn.botframework.com/botframework-webchat/latest/botchat.css" rel="stylesheet" />
  </head>
  <body>
    <div id="bot"/>
    <script src="https://cdn.botframework.com/botframework-webchat/latest/botchat.js"></script>
    <script>	 
	  
      BotChat.App({
        directLine: { secret: ****** },
        user: { id: 'user12345', name : 'user1' },
        bot: { id: 'na' },
        resize: 'detect'
      }, document.getElementById("bot"));
	  document.oncontextmenu = function(){return false;};
    </script>
  </body>
</html>

The bot is working fine. But we need to pass user login information from Sharepoint site to C# code. We added User ID & Name properties in the script, but still we not able to receive them in C# code. We are trying to get this(user Information) value from property Message.From.ID,Messgae.From.Name. Please guide us how to achieve this.

**Comment by MithunPradeeps** [comment]
Hi, am also trying to achieve the same please let me know if this functionality is already achieved.

**Comment by sgellock** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
