### ISSUE TITLE
[Azure Bot Service] Chat bot builder with Multitenancy

### ISSUE THREAD

**Issue by midhunCherrylabs** [Microsoft/BotBuilder#3596]
i am looking for one chat bot builder can talk with multiple Microsoft bot ,how it possible ,

A single bot Service to Support Multiple Bot Applications

**Comment by fanidamj** [comment]
Multiple bots can exist at the same endpoint with an ICredentialProvider. Similar thread to be referred: https://github.com/Microsoft/BotBuilder/issues/2258#issuecomment-280506334
Here's another article [Creating a Single Bot Service to Support Multiple Bot Applications](https://www.microsoft.com/developerblog/2017/01/10/creating-a-single-bot-service-to-support-multiple-bot-applications/) which would explain in detail to create a single service using messaging endpoint for multiple bots.
Let us know if it helps!!

**Comment by midhunCherrylabs** [comment]
Thanks for your samples
