### ISSUE TITLE
[Node.js SDK] Send simple FB button

### ISSUE THREAD

**Issue by ouadie-lahdioui** [Microsoft/BotBuilder#3597]
Hello,

i didn't found how to send a simple FaceBook button [like that](https://developers.facebook.com/docs/messenger-platform/send-messages/buttons/url), can you help ?

SDK: Node.js

Thanx

**Comment by IoTGirl** [comment]
Hi @ouadie-lahdioui 

Did you start at [Bot Builder SDK for Node JS](https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-overview)?

There seem to be a number of options for buttons in messages or lists.  Have you tried any of those options? How did they fail for you?

Sincerely,
IoTGirl

**Comment by ouadie-lahdioui** [comment]
Hi @IoTGirl 

i found how to send a button in lists (HeroCard, ....) but i didn't found any example on how to send a simple message plus a button ! 

in my case i can use suggested actions instead of buttons but i still wonder that i didn't found how to send a simple button !!

**Comment by IoTGirl** [comment]
Hi @ouadie-lahdioui 
Maybe take a look at this simple [sample blog](https://blogs.msdn.microsoft.com/tsmatsuz/2016/08/31/microsoft-bot-framework-messages-howto-image-html-card-button-etc/)  I think it demonstrates what you want.
Sincerely,
IoTGirl

**Comment by sphanley** [comment]
Hi @ouadie-lahdioui -- are you hoping to send a FB Button template using the Node or .NET SDK? It's not officially supported, at least in the .NET SDK, but you can achieve it by sending the right payload in ChannelData.

**Comment by ouadie-lahdioui** [comment]
Interesting !

But i juste want to send a simple button not a single hero card with buttons. in the blog post, Tsuyoshi maked some cool rich cards (Hero Card, Thumbnail Card, and Receipt Card) added buttons and send that to Facebook/slack.

I think that it's not possible to send juste a single button without wrapping it in a rich card.

Thank you 👍

**Comment by sphanley** [comment]
@ouadie-lahdioui, are you asking how to send something like [the Facebook Button template](https://developers.facebook.com/docs/messenger-platform/send-messages/template/button)? I know that in the C# SDK, at least, that Facebook template isn't supported by any built-in classes in the Bot Framework, but if you create objects that map to the requisite JSON in ChannelData you can get it to show on Facebook.

**Comment by fanidamj** [comment]
Closing the issue as it seems resolved. Feel free to reopen if you have questions or comments.
