### ISSUE TITLE
[Emulator] Message is being sent to the dialog but I am seeing a "couldn't send message, retry" in emulator

### ISSUE THREAD

**Issue by karun-r** [Microsoft/BotBuilder#3598]
## Bot Info 
* Bot handle: Not yet deployed to Production
* App ID: 
* SDK Platform: .NET
* SDK Version: 
* Active Channels: Skype
* Deployment Environment: Azure

## Issue Description
I am exploring the bot framework and started creating a simple bot which will ask the user for his origin and destinations. It will then calculate the travel time for each of those destinations. Now, my flow is as follows

- Greetings

- User will be prompted to enter his destinations (Handled by DestinationDialog)

- User will be prompted to enter his origin (Handled by OriginDialog)

- Bot will ask user to wait for a moment as it calculates the estimates (Handled by EstimateDialog)

- It will say that it has found the estimates and display the best possible option.

Now when the user enters the origin location in the conversation window, I am calling the EstimateDialog from OriginDialog. The thing is, it is taking some good amount of time to calculate the estimates if there are a number of destination options. During this time, the message which the user sent to notify his origin is shown as Failed saying that "couldn't send message, retry". But I can see the origin location when in debug mode in EstimateDialog. Is there any timeout that is causing this in the background? How do we let the MessageController know that the message sent by the user is received by the application? Should I be using context.Forward instead of context.Call when invoking other dialogs ?

I have pasted the sample code that is being used to call EstimateDialog from OriginDialogResumeAfter. Any help here? The only question in SO about this had no answers from the community.

## Code Example
        private async Task OriginDialogResumeAfter(IDialogContext context, IAwaitable<LocationModel> result)
        {
            LocationModel origin = await result as LocationModel;
            context.Call(new EstimateDialog(origin,destinations), this.ReturnNewChat);
            context.PostAsync("Preparing estimates.. Hold On..");

        }

        private async Task ReturnNewChat(IDialogContext context, IAwaitable<List<TravelModel>> result)
        {
            var res = await result as List<TravelModel>;
            await context.PostAsync("Found the estimates");
        }

## Reproduction Steps
1.
2.
3.

**Comment by karun-r** [comment]
Any help here, please?

**Comment by EricDahlvang** [comment]
Hi @karun-r 

There's a 15 second timeout from the client.  If your responses are taking longer than 15 seconds, you'll need to initiate the slow process on another thread, return a 200 http status code, then proactively send the user the results of the long operation.  Context.Forward doesn't help with the 15 second timeout.

Pseudo code:
1) Send the user a message, stating that the bot is calculating estimates.
2) Initiate the long running process on another thread
3) return Request.CreateResponse(HttpStatusCode.OK);
4) Send a proactive message to the user after the long running process completes (here are a few examples of how to do proactive messages in .net: https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/core-proactiveMessages )

Let us know if you have further questions.

**Comment by karun-r** [comment]
Thanks @EricDahlvang. This helped me fix that annoying issue.

**Comment by MarellaRam** [comment]
@karun-r  may I know the code piece how its resolved? i am into same boat not sure what thread need to be opened to send status code while BOT is preparing it?

**Comment by amitkadu** [comment]
Seems example removed from link provided, can help @EricDahlvang

**Comment by EricDahlvang** [comment]
@amitkadu The v3 samples are in a different branch now: https://github.com/Microsoft/BotBuilder-Samples/tree/v3-sdk-samples/CSharp/core-proactiveMessages
