### ISSUE TITLE
[NodeJS] The bot doesn't accept "add contact" request from skype

### ISSUE THREAD

**Issue by TheGrimmChester** [Microsoft/BotBuilder#36]
[NodeJS] The bot doesn't accept contact request from skype using BotConnectorBot.

**Comment by Stevenic** [comment]
@TheGrimmChester can you provide a few more details. What were you trying to do and what are you seeing? Are you saying that you can't add your bot as a contact in skype? Another question, are you running the latest Skype for windows client? This is the only Skype client that currently supports bots.

**Comment by TheGrimmChester** [comment]
I am trying to add the bot in my contact list with the link provided on developer.microsoft.com : https://join.skype.com/bot/<bot_id>. When I click the "add contact" button, the request is sent but I cannot verify on the bot side because I have no log.

- I run the latest version of Skype (7.22.0.107) on Windows.
- The bot is running when I triy to add it to my contact list.
- I use the latest botbuilder (0.6.4)
- Messaging Webhook (developer.microsoft.com): https://skype.botframework.com/api/bots/messages/<random_string>
- The bot is linked from dev.botframework.com
- I can send message to the bot 
- I can receive message from the bot

**Comment by Stevenic** [comment]
I've forwarded this issue on internally.

**Comment by Stevenic** [comment]
This appears to be a problem on Skypes end of things and we're looking into the issue further.

**Comment by anoopnair** [comment]
I am seeing the same issue as well. Do we have an update on this?

Also, @TheGrimmChester : You mention above that the Windows Skype client is the only one supported for Bots. However, I do see other Microsoft provided bots in my iOS / Web Skype client.

Should I see my custom bot added to my iOS or Web-based Skype client as well?

**Comment by Stevenic** [comment]
Please re-open if this issue is still happening.

**Comment by lilred** [comment]
It is indeed still happening :(

**Comment by 11andy11** [comment]
Same with me, any update on the issue?

**Comment by v-thgratMSGit** [comment]
Closing this issue due to age. @TheGrimmChester @lilred @11andy11  - please open a new issue if this issue is not fixed and needs further discussion. @Stevenic @tomlm - reopen if necessary. Thanks!

**Comment by naeemshaikh27** [comment]
issue still exists, i m not able to add bot to contacts. my colleague was able to add it tough.

**Comment by nickcordrey** [comment]
Skype team will follow up directly via email for more details to see if we can get logs to investigate.

**Comment by lilred** [comment]
Please follow up here rather than via e-mail, that way we have the possibility to subscribe/unsubscribe to the conversation, and any workarounds we find become available to the public! Thanks!

**Comment by grisevg** [comment]
Still not solved? :O

**Comment by prasannadeshappriya** [comment]
I have the same problem, Is there any solution?

**Comment by gerardoemr** [comment]
Hello, I have the same issue

Is there any fix yet?

thanks
