### ISSUE TITLE
how to reset message bot conversation / user data

### ISSUE THREAD

**Issue by cwdyang** [Microsoft/BotBuilder#360]
howdy! @craigjensen

Have this scenario where i am sending a message from my skype bot to an end user trying to include in some contextual data so when the user replies i can reuse the information in a response

send
```
var message = new Message() {.....};
message.SetBotConversationData(Constants.UserDataPatientInfo, "Doris");
```

user responds and I check for the botconversationdata data like so:

```
var person = (message.GetBotConversationData<string>(Constants.UserDataPatientInfo) ?? "");
```

i always get null.

if i use 

```
public async Task<Message> Post([FromBody]Message message)...
message.SetBotUserData(Constants.UserDataPatientInfo, "Doris" );
```

i can successfully read the value "Doris", but i can't set that value to anything else e.g.

```
message.SetBotUserData(Constants.UserDataPatientInfo, "alice" );
```

the value stays "Doris""...

any ideas?

**Comment by craigjensen** [comment]
Have a look [here](http://docs.botframework.com/connector/tracking-bot-state/#navtitle) for examples of how to use bot state.  I think the problem in your first example is that you are not setting the FromId/ConversationId for the message which is how the state is tracked.  If you use srcMessage.CreateReplyMessage() and set your state properties on that object it should work better.

**Comment by cwdyang** [comment]
@craigjensen - hey thanks heaps i have tried that and its still not playing ball: here's our use case: 

user will already have a session open to the bot and a conversation in a suspended state 
(question how can we "kill off" a conversation - can i achieve that by simply doing something on the message object?)

the bot will initiate a conversation out of the blue and send a trigger message to the user (need to store some temporary contextual data e.g. pet's name)

(question, how do i start a new conversation? with the same user when sending a message)

the user will respond and the bot should recognise that the user intends to respond to the message, it also needs to respond back to the user with the data (i.e. oh great you are responding to blah+blah pet's name) 

once this "handshake"'s complete we want to clear the stored user /conversation data.

any help'd be appreciated!

**Comment by cwdyang** [comment]
@msft-shahins @Stevenic 

Hi guys - could you give us a hand with the query above? much appreciated!

**Comment by v-thgratMSGit** [comment]
@craigjensen @msft-shahins @Stevenic Any thoughts?

**Comment by v-thgratMSGit** [comment]
Closing this issue due to age. @cwdyang - please open a new issue if this issue is not fixed and needs further discussion. Thanks!
