### ISSUE TITLE
[Skype for Business] Bot appears offline + "presence unknown"

### ISSUE THREAD

**Issue by papaioannous** [Microsoft/BotBuilder#3607]
* Active Channels: Skype for Business
* Deployment Environment:  Azure App Service

## Issue Description
Bot is successfully added to skype for business and is able to respond but looks offline and has  'presence unknown'.

Any ideas why the bot my appear offline ?

**Comment by nwhitmont** [comment]
@papaioannous Please provide your bot's App ID as you registered in the Bot Developer Portal at https://dev.botframework.com

**Comment by papaioannous** [comment]
@nwhitmont My AppId is a43d1a74-e95a-40b1-bc55-4c3e1c3b9bf4

**Comment by ShujaathKhan** [comment]
This comes to my bot in Skype for Business  as Unknown and presence icon always appears grey never seems it green.
But where in msteams it comes perfectly fine as expected.

Adaptive card supportive totally fails in Skype for Business.

**Comment by papaioannous** [comment]
Hi @ShujaathKhan, I was searching for the same issues and here is what i found: Based on the documentation, cards are not yet supported in Skype for Business but there is a fallback you can see that [here](https://msdn.microsoft.com/en-us/skype/Skype-For-Business-Bot-Framework/docs/overview#feature-support) and also there is an issue with Skype for Business bot status.

**Comment by Shamrh** [comment]
I am also facing the same issue..

**Comment by billygl** [comment]
I also facing the same issue

**Comment by EricDahlvang** [comment]
https://docs.microsoft.com/en-us/skype-sdk/skype-for-business-bot-framework/docs/bot-common-errors
> The Bot Framework Skype for Business Channel is in Developer Preview and does not support presence at the current time.

**Comment by lueyyou** [comment]
Any plans on making this a non-preview bot? We really need presence and a few other enterprise level features. Its a shame because its not far off just a few small minor things to implement.

**Comment by sgellock** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
