### ISSUE TITLE
[Question] Missing some assemblies from Microsoft.Bot.Builder.Azure?

### ISSUE THREAD

**Issue by denisyfrolov** [Microsoft/BotBuilder#3609]
## Bot Info
* SDK Platform: .NET
* SDK Version: Microsoft.Bot.Builder.Azure 3.2.3
* Deployment Environment: ngrok, Azure Bot Service
## Issue Description

Bot works fine, but I see many warnings (which are quite annoying) in console like those:

```
Unable to find assembly 'Microsoft.Bot.Builder.resources, Version=3.9.0.0, Culture=ru, PublicKeyToken=31bf3856ad364e35'. Are you missing
 a private assembly file?
```
```
Unable to find assembly 'f-messages__373364057, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. Are you missing a private assemb
ly file?
```

I have no idea where they come from.

**Comment by fanidamj** [comment]
Can you please let us know if the issue still persists?

**Comment by JasonSowers** [comment]
please open a new issue if you are still having problems.

**Comment by Gudzy** [comment]
I have the same issue. Anyone with an answer?
