### ISSUE TITLE
How to update session.userData in bot with username from browser after a user login 

### ISSUE THREAD

**Issue by rohitdharavath** [Microsoft/BotBuilder#361]
I am trying to greet the user without prompting for username in the bot rather getting it when they login..How to do this?

**Comment by Stevenic** [comment]
This is a super tricky problem. The short answer is you can do it but it's some pretty nasty code. We have a C# example that does it and I started implementing support for doing it in Node but we decided to rewrite a whole bunch of related code so I'm just starting that re-write and it will be a few weeks before I get "official" auth support working.

Basically you have to send the user a link in message that they need to click to login. This link should run through standard oauth flow and the challenge is what do you do when you get to the end of the flow.  As you said you need to store the users token on their `session.userData` object. But that's not actually enough. You should also send a message to the user telling them they're logged in or continue the task they were trying to achieve. 

For the first part we have a REST API you can call that lets you read & write the `userData` object. You just need to save off the conversationId & userId for the person being logged in (this needs to be embedded in your oauth link somewhere.) For the second part you could generate a proactive message by calling `bot.begingDialog()`. That way is sort of the hacked way of achieving this.

The cleaner way that I started implementing does the same basic thing, sends the user a link with conversationId & userId embedded. But on completion of the oauth flow it packs the token into a message and routes it through the dialog system as if it was sent from the user. The advantage of that is that you could be in the middle of a waterfall, decide you need to log someone in, wait for the login to complete, and then simply continue the waterfall. 

I've been calling these __web actions__ and when I'm done there will probably just be a new `Prompts.webAction()` prompt you can use to achieve this. But as I said this is probably a 2-4 weeks out.

**Comment by srinivasamyneni** [comment]
@Stevenic , please share the link of C# example for this. I'm also looking solution for similar requirement of greeting the user upon user login to the site.

**Comment by Stevenic** [comment]
https://github.com/Microsoft/BotBuilder/tree/master/CSharp/Samples/SimpleFacebookAuthBot

**Comment by srinivasamyneni** [comment]
@Stevenic, I'm looking to intgerate web chat with one of out custom .Net application which FBA authentication. I would like to get the user details from session and show on web chat window with greeting user. 

is it possible? is yes can you please share/point me to an example.

**Comment by msft-shahins** [comment]
@srinivasamyneni you can pass the authtoken from your .Net application to the bot and use the auth token in the bot to get the information about user and send back the result to user in the web chat window.

**Comment by rehtinavelmoorthy** [comment]
how to get user name with node to greet with user name?

**Comment by palashjhabak** [comment]
@Stevenic was Prompts.webAction() actually implemented? Cannot see in v3. Also since this is now closed, is there already a good way to achieve this ? 

I want to do oauth and save the auth token in userdata and notify user. as @Stevenic mentioned above routing the callback to the dialog is a cleaner way than starting a proactive message. So was just wondering. 

Thanks,
Palash
