### ISSUE TITLE
[.Net SDK, LUIS] Result Object Has Unreachable Properties?

### ISSUE THREAD

**Issue by kashifkhan** [Microsoft/BotBuilder#3610]
I am running the latest version of the C# BotBuilder SDK. After switching to the new LUIS V2 DateTime the results object comes back with resolutions that just can't be reached. 

Programmatically you can reach up to `result.Entities.Resolution["values"]` but nothing after that. Its not iterable or indexable. The `TryFindEntity("builtin.datetimeV2.date", out startDate)` method as well doesn' resolve to anything. Forcibly trying to cast the object to a `Dictionary<string, object>` still yields null.

**Comment by baendron** [comment]
Not sure if this is the right way to do this, but using Chronic.Parser seems to solve this problem for me.
```
Chronic.Parser parser = new Chronic.Parser();
DateTime dateResult = DateTime.MinValue();

if (result.TryFindEntity("builtin.datetimeV2.date", out dateRecommendation))
            {
                dateResult = DateTime.Parse(parser.Parse(dateRecommendation.Entity).Start.ToString());                
            }
```

**Comment by fanidamj** [comment]
Can you please let us know if the issue still persists?

**Comment by sgellock** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
