### ISSUE TITLE
[Kik] How to pass "Common Attribution Fields" for image attachments?

### ISSUE THREAD

**Issue by qpongo** [Microsoft/BotBuilder#3611]
## Kik requires "Common Attribution Fields" to be set 
In the process of getting approval for our bot on Kik and was told that "link messages need to have their attribution set."

**Repro:**  We tried to submit a hero card with an image that also had an action.

**Expected:**  Need a way to set common attribution fields on images (and link messages).

From [https://dev.kik.com/#/docs/messaging#attribution](https://dev.kik.com/#/docs/messaging#attribution)

Field | Default | Description
-- | -- | --
name | mandatory | The name that will appear in the attribution bar.
iconUrl | placeholder | The URL specifying an icon that will appear in the attribution bar.

There are actually a lot of extra fields and it would be great if there were a way to pass parameters to them -- i.e. no_forward

class kik.messages.LinkMessage(to=None, chat_id=None, url=None, title=None, text=None, pic_url=None, no_forward=None, kik_js_data=None, keyboards=None, attribution=None, mention=None, delay=None, **kwargs)
A full link message object, as documented at [https://dev.kik.com/#/docs/messaging#link](https://dev.kik.com/#/docs/messaging#link).

class kik.messages.PictureMessage(to=None, chat_id=None, pic_url=None, keyboards=None, attribution=None, mention=None, delay=None, **kwargs)
A full picture message object, as documented at [https://dev.kik.com/#/docs/messaging#picture](https://dev.kik.com/#/docs/messaging#picture).

**# Picture** ( [https://dev.kik.com/#/docs/messaging#link](https://dev.kik.com/#/docs/messaging#link) )
```

{
    "messages": [
        {
            "chatId": "b3be3bc15dbe59931666c06290abd944aaa769bb2ecaaf859bfb65678880afab",
            "type": "picture",
            "from": "laura",
            "participants": ["laura"],
            "id": "6d8d060c-3ae4-46fc-bb18-6e7ba3182c0f",
            "picUrl": "http://example.kik.com/apicture.jpg",
            "timestamp": 1399303478832,
            "readReceiptRequested": true,`

            "attribution": {
                "name": "A Title",
                "iconUrl": "http://example.kik.com/anicon.png"
            },

            "mention": null,
            "metadata": null,
            "chatType": "direct"
        }
    ]
}

```

**Comment by nwhitmont** [comment]
@qpongo For reference, are you using .NET or Node.js SDK for BotBuilder?

**Comment by nwhitmont** [comment]
@qpongo Did you try using `channelData` to create a Kik native message?

https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-channeldata#create-a-native-kik-message

**Example:**
```js
"channelData": {
    "messages": [
        {
            "chatId": "c6dd8165…",
            "type": "link",
            "to": "kikhandle",
            "title": "My Webpage",
            "text": "Some text to display",
            "url": "http://botframework.com",
            "picUrl": "http://lorempixel.com/400/200/",
            "attribution": {
                "name": "My App",
                "iconUrl": "http://lorempixel.com/50/50/"
            },
            "noForward": true,
            "kikJsData": {
                    "key": "value"
                }
        }
    ]
}
```

**Comment by qpongo** [comment]
@nwhitmont For reference, are you using .NET or Node.js SDK for BotBuilder?

.NET

No, I'll try using "channelData" and report back.
