### ISSUE TITLE
Embed webchat in a blog

### ISSUE THREAD

**Issue by MAKEADM** [Microsoft/BotBuilder#3612]
Hello! Currently i am developing a bot for my travel blog in order to improve the  search of articles. My web page is financed by ads. I want to know that if I embed my bot throught webchat in my webpage as a widget, I can continue using ads in my blog without infringing any term of the bot framework.

Thanks

**Comment by EricDahlvang** [comment]
Hi @MAKEADM 

This isn't the forum for legal questions, as we are not lawyers.  Nonetheless, here are a couple of answers provided by the Bot Framework team when this has been asked before: https://github.com/Microsoft/BotBuilder/issues/1274 and https://github.com/Microsoft/BotBuilder/issues/3345

Please get advice from a lawyer, and have them read through the Service Agreement: https://www.botframework.com/Content/Microsoft-Bot-Framework-Preview-Online-Services-Agreement.htm
