### ISSUE TITLE
[.Net SDK, Channel Configuration] Failed to connect to Slack due to invalid credentials?

### ISSUE THREAD

**Issue by jeffrey-opdam** [Microsoft/BotBuilder#3613]
## Bot Info 
* Bot handle: vsts_bot
* App ID: b7016a0c-c014-4ebc-bc99-74ef6cb78265
* SDK Platform: .NET
* SDK Version: 3.9.0.0
* Active Channels: Slack, Skype, Microsoft Teams
* Deployment Environment: Azure App Service

## Issue Description
Getting the following error:
Bot integration vstsbot(<random>:<random>) failed to connect to Slack due to invalid credentials and will be disabled. Error: account_inactive

The bot is still active in the slack app store. (So not disabled)
I am assuming the numbers after vstsbot are the identifiers of an user. Could it be that the user removed the bot, and the bot still tried to send a message back?

## Reproduction Steps
1. Not sure, still to random, not sure if the user are actually experience problems.

## Expected Behavior
No such errors in the logs.

## Actual Results
The error described in the Issue Description.

**Comment by nwhitmont** [comment]
@jeffrey-opdam What happens after you remove the Slack channel in the Bot Portal channel configuration page, and then add the channel back again?

**Comment by jeffrey-opdam** [comment]
I removed it and added it back. I will keep monitoring and let you know.

**Comment by jeffrey-opdam** [comment]
10/19/2017, 5:14:22 PM | Bot integration vstsbot(B7MN6BRCN:T02BP27VC) failed to connect to Slack due to invalid credentials and will be disabled. Error: account_inactive

Got another three today, so removing and adding the channel did not work.

**Comment by hrboyceiii** [comment]
@jeffrey-opdam I'm not sure if this helps or not but I was having a similar issue tonight and deleting the channel and recreating it solved my problems. In my case I'm using the Azure Bot Service offering -- not sure how that's different from a standalone App Service but thought I'd call that out as well.

**Comment by lingz** [comment]
I have the same problem of deleting and re-adding causes this exact problem. Even deleting the channel does not help in my case.

**Comment by fanidamj** [comment]
Can you please let us know if the issue still persists?

**Comment by sgellock** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
