### ISSUE TITLE
[Slack] Duplicate messages sent by bot?

### ISSUE THREAD

**Issue by jeffrey-opdam** [Microsoft/BotBuilder#3614]
## Bot Info 
* Bot handle: vsts_bot
* App ID: b7016a0c-c014-4ebc-bc99-74ef6cb78265
* SDK Platform: .NET
* SDK Version: 3.9.0.0
* Active Channels: Slack, Skype, Microsoft Teams
* Deployment Environment: Azure App Service

## Issue Description
When the users starts talking to the bot, she sends duplicate messages back in Slack.
Further investigation, show that we are getting duplicate requests in our MessagesController Post method.
If you turn off the Bot Events in the Slack Subscription, you only get the messages for the ‘event_callback’ type.
For now we filter all other events out, then the ‘event_callback’ ones.

![2](https://user-images.githubusercontent.com/26557058/31576731-3a442eb2-b101-11e7-9f70-c53333f0c174.png)
![1](https://user-images.githubusercontent.com/26557058/31576732-3a8600d0-b101-11e7-8473-561565989758.png)

## Code Example
None

## Reproduction Steps
1. Add bot to your workspace
2. say 'help' 
3.

## Expected Behavior
Request is only send once.

## Actual Results
Getting two request for one message from the user.

**Comment by Ma3yTa** [comment]
@jeffrey-opdam I am experiencing the same in Skype today.

**Comment by nwhitmont** [comment]
@jeffrey-opdam there appears to be a problem with your Slack channel configuration. 

Try deleting the channel from your active channels and adding it back again.

**Comment by jeffrey-opdam** [comment]
Done. I will keep monitoring and let you know the results.

**Comment by jeffrey-opdam** [comment]
Have not seen any reports for this one, so closing. Thank you for your support.
