### ISSUE TITLE
Referencing a .NET Standard 2.0 project makes the Bot crash with a MissingMethodException

### ISSUE THREAD

**Issue by johot** [Microsoft/BotBuilder#3615]
If you create a new bot using Visual Studio 2017 and the template found here:
<https://docs.microsoft.com/en-us/bot-framework/resources-tools-downloads>
and then add a reference to a .NET Standard 2.0 class library (from nuget or by adding a new one in visual studio and referencing that), the bot stops working.

When using the Bot Framework Channel Emulator the following error message is produced when connecting:

```
{
  "message": "An error has occurred.",
  "exceptionMessage": "Method not found: 'System.Net.Http.HttpRequestMessage System.Web.Http.ApiController.get_Request()'.",
  "exceptionType": "System.MissingMethodException",
  "stackTrace": "   at Bot_Application1.MessagesController.<Post>d__0.MoveNext()\r\n   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)\r\n   at Bot_Application1.MessagesController.Post(Activity activity)\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass12.<GetExecutor>b__8(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"
}
```

As soon as the .NET Standard 2.0 reference is removed it starts working again.

I get this error with a Bot created in both .NET Framework 4.6.1 and .NET Framework 4.7.
I also tried updating all references to the latest version which in this case is the Microsoft.Bot.Builder 3.11.0

What to do? Thanks!

**Comment by IoTGirl** [comment]
Hi @johot 
When I look up the .Net API being reported [HttpRequestMessage](https://msdn.microsoft.com/en-us/library/system.net.http.httprequestmessage(v=vs.110).aspx) it states it was made available in .Net 4.5 so I believe the message is correct and it is telling you this method is missing if you attempt to target a .Net 2.0 project.
Sincerely,
IoTGirl

**Comment by johot** [comment]
Hi @IoTGirl but I am targeting .Net framework, only using a .Net standard 2 library. Probably a problem with a binding redirect?

**Comment by IoTGirl** [comment]
Hi @johot 
I can't guess what is going on in your specific case but the answer in the forums to a [similar question](https://social.msdn.microsoft.com/Forums/vstudio/en-US/820a771a-2e5a-47cb-84d3-00a512b69eba/using-a-net-20-library-with-a-net-40-solution?forum=vbgeneral) seems to indicate that major changes between 2.0 and 4.0 could lead to problems using a 2.0 component in a 4.0 context.
To get a more specific answer regarding .Net, MSDN forums might be a better place to ask this question.
Sincerely,
IoTGirl

**Comment by sphanley** [comment]
@IoTGirl, it looks like there's a bit of a miscommunication here. What you're saying would make sense if @johot were talking about the .NET Framework 2.0, which is very old, having been released in 2006. However, what's actually being discussed is [.NET Standard 2.0](https://blogs.msdn.microsoft.com/dotnet/2017/08/14/announcing-net-standard-2-0/), which is a comparatively cutting-edge version that was finalized in August of this year. This is an issue of forward compatibility, not backwards.

**Comment by IoTGirl** [comment]
Hi @sphanley ,
Can you find documentation that shows this API is available in .Net Standard 2.0?  Do you feel the message is incorrect?  This line of investigation leads me to suggest again that MSDN Forums is likely the best place to ask.
Sincerely,
IoTGirl
This line of investigation leads me to suggest again that MSDN Forums is likely the best place to ask

**Comment by johot** [comment]
There is no concept of this API being available in .NET Standard 2.0. The BotBuilder framework is a .NET Framework project that is clear, however all .NET Framework projects should be able to have .NET Standard references without breaking. However I do believe this is not really the BotBuilder projects "fault", rather it's a problem with the integration between .Net Framework 4.5 and .Net standard 2.0 as described here: <https://github.com/dotnet/standard/issues/481>. Hopefully this gets better in the future.

I actually managed to fix this problem in my case today by doing a binding redirect (to version 4.0.0) in my `web.config` file for the System.Net.Http library.

**Comment by IoTGirl** [comment]
Hi @johot ,
Great catch!  Has the suggested change you employed above solved the issue for you? Can this be closed?
Sincerely,
IoTGirl

**Comment by johot** [comment]
Yes it has :) closing!

**Comment by IoTGirl** [comment]
Thanks @johot !
