### ISSUE TITLE
[Skype for Business] Bot throws error, can't reach bot service?

### ISSUE THREAD

**Issue by anujaparikh23** [Microsoft/BotBuilder#3619]
## Bot Info 
* Bot handle: CallScheduleBot
* App ID: f079f4c0-39a6-4825-81e2-0da3a7c13b53
* SDK Platform: Node.js 
* Active Channels: Skype, Webchat, Skype for Business
* Deployment Environment: ngrok

## Issue Description
My bot is running successfully on Skype and Webchat.

I performed the steps mentioned to expose it to Skype for Business Channel.

The bot is created and i can search it in my SFB contacts.

But when i Ping it, it shows me error saying Skype for Business could not reach the bot.

Contact Name in Skype for Business is callschedule. I can see the bot as a user in my office 365 admin center, but not as a Skype for Business user.

## Expected Behavior
I want it to respond properly, the way its doing at the webchat and skype portal.

## Actual Results
![sfb1](https://user-images.githubusercontent.com/17399975/31598499-adbe7df0-b26b-11e7-85ff-f42c0115741d.png)

**Comment by JasonSowers** [comment]
are you still having this issue?  It may have just taken a little time for the change to propagate.

**Comment by JasonSowers** [comment]
please open a new issue if you are still having trouble with this
