### ISSUE TITLE
Adaptive card not displaying on MS Teams

### ISSUE THREAD

**Issue by EnnamGopaulen** [Microsoft/BotBuilder#3620]
## Bot Info 
* App ID: 987f751d-6231-469e-b3dd-cbb56e7f7893
* SDK Platform: Node.js 
* SDK Version: 3.7.0
* Active Channels: MS Teams, WebChat
* Deployment Environment: Azure App Service

## Issue Description
The adaptive card is not displaying on MS teams but working well on emulator and WebChat .
## Code Example

```
displayCustomerCreationForm = function (session, nom, ville) {
  if ((typeof session.message.value === 'undefined' || session.message.value === '')) {
    var outputCard = new builder.Message(session)
      .addAttachment({
        contentType: "application/vnd.microsoft.card.adaptive",
        content: {
          "type": "AdaptiveCard",
          "body": [
            {
              "type": "TextBlock",
              "text": "Nom du client"
            },
            {
              "type": "Input.Text",
              "id": "nom",
              "style": "text"
            },
            {
              "type": "TextBlock",
              "text": "Ville"
            },
            {
              "type": "Input.ChoiceSet",
              "id": "ville",
              "style": "compact",
              "isMultiSelect": false,
              "choices": [
                {
                  "title": "Paris",
                  "value": "Paris",
                  "isSelected": true
                },
                {
                  "title": "Marseille",
                  "value": "Marseille"
                },
                {
                  "title": "Lyon",
                  "value": "Lyon"
                }
              ]
            }
          ], "actions": [
            {
              "type": "Action.Submit",
              "title": "Valider",
              "data": { "btn": "form" }
            },{
              "type": "Action.Submit",
              "title": "Annuler",
              "data": { "btn": "cancel" }
            }]
        }
      });
```

## Expected Behavior
This card should appear 
![image](https://user-images.githubusercontent.com/24710468/31605839-727fa856-b278-11e7-966e-44c98e4b512a.png)

## Actual Results
Nothing appear in MS Teams but displayed successfully on Emulator and WebChat.

**Comment by Wajeed-msft** [comment]
@EnnamGopaulen - Adaptive Cards are not yet supported in Microsoft Team. We are working on support for Adaptive Cards and hope to have a date to share soon. It won't be before January 2018 but it is high on the list of next things to get to.

**Comment by EnnamGopaulen** [comment]
@Wajeed Thanks for your reply

**Comment by Shon-Elias** [comment]
@Wajeed-msft , Is it possible to use Adaptive Card now in Microsoft Teams?

on the [visualizer]( http://adaptivecards.io/visualizer/index.html?hostApp=Microsoft%20Teams%20(Preview)) it shows this is possible, however when I testing it, I could not see the calendar

**Comment by brettmillerb** [comment]
there's been a few dates @Shon-Elias and I think Q1 2018 was the initial date but not official date as of yet afaik.

**Comment by Shon-Elias** [comment]
@brettmillerb Thanks for your reply.

I'm looking forward to using it in Microsoft Teams

**Comment by talencity** [comment]
It currently says that Adaptive Cards are in Preview for MS Teams: 
https://docs.microsoft.com/en-us/adaptive-cards/resources/partners

Is there something that needs to be done to activate the preview? It does not seem to be working yet. @Wajeed-msft

**Comment by Shon-Elias** [comment]
@talencity Thank you!

**Comment by EricDahlvang** [comment]
@Shon-Elias 

You might get a more accurate answer to your question here: https://github.com/Microsoft/AdaptiveCards/issues
