### ISSUE TITLE
Azure Bot Service: Bot offline and not replying on SKYPE. However working smoothly in WebChat (Azure) and cortana.

### ISSUE THREAD

**Issue by tariksetia** [Microsoft/BotBuilder#3621]
## Bot Info 
* Bot handle: eucbot
* App ID: 61b6c1e9-e438-443d-b307-aed48b1f27a8
* SDK Platform: node.js
* SDK Version: ^3.11.0
* Active Channels: Skype(Not Working), Cotrana , Webchat
* Deployment Environment: Azure bot Service

## Issue Description
Bot is deployed on skpe channel. When I add it to contact....it show offline and does  not reply.
The bot is replying in Cortana and Azure WebChat

## Code Example
github = https://github.com/tariksetia/chatops.git

## Reproduction Steps
1. Create a Bot Service in Azure.
2. Under the build section click open online code editor
3. When the code editor is open...delete app.js, package.json and .gitignore
4. open console or Kudu Console (wwwroot) (if editor console do not work, open kudu console)
5. Type `git init`
6. Type `git remote add origin  https://github.com/tariksetia/chatops.git`
7. Type `git pull origin master`
8. `npm install`
9. replace line number 19 in app.js with following
```
var connector = new builder.ChatConnector({
    appId: 'your app id',
    appPassword: 'your app password'
});
```
10. Click run on console.
11. on Azure Portal, in bot service, choose channels.
12. Skype will be running by default . Click on skpye channel
![image](https://user-images.githubusercontent.com/1137658/31625633-5a54ddea-b2c4-11e7-9733-9b000777ab89.png)
13. Now you should see "Add Bot to Skype" page... follow instructions there.
14. type Hi! in skype bot conversation

## Expected Behavior
It should say : Hi! Whats your name?

## Actual Results
In Skpye Windows (Broken)
![image](https://user-images.githubusercontent.com/1137658/31625808-097dc5fc-b2c5-11e7-9937-1f97fd3fe99f.png)

In Skype -Mobile (Broke but messaging is disabled)
![image](https://user-images.githubusercontent.com/1137658/31625886-5384e130-b2c5-11e7-8bff-98c30eb2ea30.png)

In WebChat/Azure (working)
![image](https://user-images.githubusercontent.com/1137658/31625935-7c9689c0-b2c5-11e7-88f6-6f7f5df393b9.png)

Cortana (Working)

![image](https://user-images.githubusercontent.com/1137658/31626055-e6ee05b4-b2c5-11e7-9456-28700801ee38.png)

**Comment by IoTGirl** [comment]
This seems similar to https://github.com/Microsoft/BotBuilder/issues/3557

**Comment by tariksetia** [comment]
I also created a new bot service with vanilla Luis intelligence bot, put my Microsoft credentials in code using online code editor, added bot to Skype....But it also didn't work.... facing same behavior on skype

**Comment by tariksetia** [comment]
This got fixed

Download [https://go.skype.com/skype.preview.download].
Install it. If you are using windows 10, set compatibility mode to Windows 8.
In the left side bar, you will see your bot. Right click the bot and add to contact. This "add to contact" was not available is my default Windows 10 Skype.
