### ISSUE TITLE
[LUIS] How to configure multiple recognizers?

### ISSUE THREAD

**Issue by clari182** [Microsoft/BotBuilder#3622]
## Issue Description
I have a chatbot made in C# that interacts with LUIS and QnAMaker. I need to do something like the Node version where you can define multiple recognizers and add then to the botbuilder.IntentDialog

Now I'm doing it like this:

I have a LuisDialog that receives all the intents and handles them. When the intent is "None" I call the QnAMaker with the message. But I need to do it the other way, in serie, first call QnA and then LUIS if there is no right answer.

## Code Example in NodeJs
How I would do it in Node:
```
const recognizer = new botbuilder.LuisRecognizer(process.env.MICROSOFT_LUIS_MODEL_EN)
var qnarecognizer = new cognitiveservices.QnAMakerRecognizer({
	knowledgeBaseId: process.env.QNA_ID, 
	subscriptionKey: process.env.QNA_KEY,
    top: 4});
const intents = new botbuilder.IntentDialog({ 
	recognizers: [qnarecogizer, recognizer], 
	intentThreshold: parseFloat(process.env.INTENT_THRESHOLD), 
	recognizeOrder: botbuilder.RecognizeOrder.series })
```

Is there a way to do the same in C#?

Thanks!

**Comment by FranciscoPonceGomez** [comment]
Hi @clari182,

What about overriding RespondFromQnAMakerResultAsync so when we receive the answer from QnAMaker we compare it to null or "Not match found!" and then we create an instance of the LUIS Dialog, forwarding the context to it:
```csharp
[Serializable]
public class QnAMakerSettingsAttribute : QnAMakerAttribute
{
            public QnAMakerSettingsAttribute()
                : base(ConfigurationManager.AppSettings["QnASubscriptionKey"], ConfigurationManager.AppSettings["QnAKbId"])
            {
            }
}
protected override async Task RespondFromQnAMakerResultAsync(IDialogContext context, IMessageActivity message, QnAMakerResults result)
{
            var answer = result.Answers.First().Answer;
            Activity reply = ((Activity)context.Activity).CreateReply();

            if (reply.Text.Equals("Not match found!") || reply == null) 
                   await context.Forward(new MyLUISDialog(LuisModel, LUISPassword),ConvEndAsync, activity,  CancellationToken.None);
           else
               await context.PostAsync(reply);
}
```
I haven't tried this yet in code but it should work.
