### ISSUE TITLE
[Skype] Can not receive attachment?

### ISSUE THREAD

**Issue by ZhengKevin25** [Microsoft/BotBuilder#3623]
## Bot Info 

* SDK Platform:  .NET 
* SDK Version: 3.8.0.0
* Active Channels: Skype
* Deployment Environment: Azure App Service

## Issue Description
When I sent a attachment to bot, in my bot I want to get the contents of the attachment.
I used the following code to get it. But has been returning 500 errors.

## Code Example
```cs
public virtual async Task MessageReceivedAsync(IDialogContext context, IAwaitable<IMessageActivity> argument)
        {
            var message = await argument;

            if (message.Attachments != null && message.Attachments.Any())
            {
                using (var connectorClient = new ConnectorClient(new Uri(message.ServiceUrl)))
                {
                    var token = await (connectorClient.Credentials as MicrosoftAppCredentials).GetTokenAsync();
                    var uri = new Uri(message.Attachments[0].ContentUrl);
                    using (var httpClient = new HttpClient())
                    {
                        await context.PostAsync(message.Attachments[0].ContentUrl);
                        await context.PostAsync(uri.Host);
                        //if (uri.Host.EndsWith("skype.com") && uri.Scheme == "https")
                        //{
                        httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
                        httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/octet-stream"));
                        //}

                        try
                        {
                            var data = await httpClient.GetByteArrayAsync(uri);
                            await context.PostAsync(data.Length.ToString());
                        }
                        catch(Exception ex)
                        {
                            if (ex.InnerException!= null)
                            {
                                await context.PostAsync(ex.Message + ":" + ex.InnerException.Message);
                            }
                            else
                            {
                                await context.PostAsync(ex.Message);
                            }   
                        }   
                    }
                }
            }
            
            context.Wait(this.MessageReceivedAsync);
        }
```
## Code Description
1. await context.PostAsync(message.Attachments[0].ContentUrl);  output: https://smba.trafficmanager.net/apis/v3/attachments/0-sa-d1-abd6e64b01d2f5e06ef698e7f05a8bb2/views/original
2. await context.PostAsync(uri.Host);   output: smba.trafficmanager.net
3. var data = await httpClient.GetByteArrayAsync(uri); throw exception: Response status code does not indicate success: 500 (Internal Server Error).

Does anyone have an idea of how I can work around this?

**Comment by IoTGirl** [comment]
Hi @ZhengKevin25,
There is a note in the sample at [https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/core-ReceiveAttachment](https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/core-ReceiveAttachment) that states:

``// Skype & MS Teams attachment URLs are secured by a JwtToken, so we need to pass the token from our bot.
            if ((message.ChannelId.Equals("skype", StringComparison.InvariantCultureIgnoreCase) || message.ChannelId.Equals("msteams", StringComparison.InvariantCultureIgnoreCase)) 
                && new Uri(attachment.ContentUrl).Host.EndsWith("skype.com"))
            {
                var token = await new MicrosoftAppCredentials().GetTokenAsync();
                httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
            }

**Comment by ZhengKevin25** [comment]
Hi @IoTGirl 
I have set the JwtToken of my bot as the authorization header for the HTTP GET request.
But still returned 500 error. And I don't know why I use skype as channel, but the return to my 
**Uri(attachment.ContentUrl).Host**  is **smba.trafficmanager.net** not like **xxx.skype.com**

**Comment by IoTGirl** [comment]
Hi @ZhengKevin25 ,
The 500 indicates an Internal Server error, correct? I am afraid that might be pretty difficult to diagnose.  If it is your server, can you see the error on the server side? 
Sincerely,
IoTGirl

**Comment by ZhengKevin25** [comment]
Hi @IoTGirl 
**I tested in the dev.botframework.com is OK**
![image](https://user-images.githubusercontent.com/21189926/31760667-0556051e-b4e8-11e7-891d-6c1713562c96.png)

**but with skype will be 500 error**

![image](https://user-images.githubusercontent.com/21189926/31760757-542bce76-b4e8-11e7-9c6d-48bde1d7af39.png)

**Comment by konstlut** [comment]
@ZhengKevin25 Thank you for reporting. I will need your bot id and approximate date/ time when the problem was observed. Thank you!

**Comment by ZhengKevin25** [comment]
@konstlut Thank you for your attention.
Bot Id: **PorticoBot**
MicrosoftAppId: **efa92abe-387b-4232-90e2-e8ecc4e74b2d**
approximate date/time  : **2017/10/20 9:20:00 (BJT)**

![image](https://user-images.githubusercontent.com/21189926/31801161-c7d461ae-b578-11e7-81b6-0d12148bb7fd.png)

**Comment by julioct** [comment]
I’m seeing the same issue here with Skype. Any ideas?

**Comment by ZhengKevin25** [comment]
@konstlut Do you have any ideas?

**Comment by mveroukis** [comment]
I'm seeing something very similar, however I'm using Teams instead of Skype.

Using VS2017 Enterprise I was able to attach a debugger to my bot and what I noticed is that the Attachment has a NULL ContentUrl, Name, ThumnailUrl and an empty Properties. However, the ContentType is "text/html" and the Content is some html which contains the name of my bot. It seems to me that the attachment is not the file I attached to the channel but the mention of the bot itself (and no, there are no other attachments associated with the message, just the one).

Interestingly, I can still retrieve the JWT however without a ContentUrl it's not particularly useful. Am I doing something wrong or is this a bug with Teams/Bot Framework?

**Comment by mveroukis** [comment]
I can now confirm that I get the same as the original poster while using Skype. What I reported above for Teams may be a separate issue and I'll create a new issue to track that.

Using Skype, I too get a 500 Internal error when attempting to Get the url from the attachment. I too set the bearer token and if I were doing that wrong, I'd still expect an error other than 500.

I don't set the Accept header, although it doesn't appear to help in this case.

**Comment by kounoupaki** [comment]
We also experience the same problem with Node.js bot using Skype. The same code used to work until a few days ago. Now, we receive a 500 internal error.

**Comment by nickgkan** [comment]
I face the same problem using Node.JS. I use the Bearer JWToken to make a GET request to get the content of the attachment but receive a 500 internal server error. To be more specific, the response body is empty and the status code is 500.

**Comment by msimecek** [comment]
Same problem here - accessing `https://smba.trafficmanager.net/df-apis/v3/attachments/0-neu-d5-<omitted>/views/original` with Bearer token, using Postman and getting 500 Internal Server Error...

**Comment by EricDahlvang** [comment]
I believe the underlying problem causing this has been resolved.  I'd like to close this GitHub issue.  Are any of you still experiencing this problem?

**Comment by gfazzola** [comment]
Initially I followed the guidelines given in
https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/core-ReceiveAttachment

and everything worked fine ..... until it stopped working. :(

Inspecting the values ​​that came in
attachment.ContentUrl
note that the word skype did not come but

https://smba.trafficmanager.net/apis/v3/attachments/0-eus-d5-949de6301a71195d35e2d0d762c2561d/views/original

Remove that portion of the code and everything started working again

The code is as follows

if (message.Attachments! = null && message.Attachments.Any ())
try
{
foreach (var attachment in message.Attachments)
{
Trace.TraceInformation ($ "message.ChannelId: {message.ChannelId}. Attachment.ContentUrl: {attachment.ContentUrl}");
using (HttpClient httpClient = new HttpClient ())
{
// The URLs of Skype & MS Teams attachments are protected by a JwtToken, so we must pass the bot token of our bot.
if ((message.ChannelId.Equals ("skype", StringComparison.InvariantCultureIgnoreCase) ||
message.ChannelId.Equals ("msteams", StringComparison.InvariantCultureIgnoreCase))
&& **1 == 1 / * new Uri (attachment.ContentUrl) .Host.EndsWith ("skype.com") * /**)
{
var token = await new MicrosoftAppCredentials (). GetTokenAsync ();
Trace.TraceInformation ($ "token: {token}");

httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue ("Bearer", token);
}

var responseMessage = wait for httpClient.GetAsync (attachment.ContentUrl);
