### ISSUE TITLE
[Direct Line] How to get list of bot's Skype contacts via REST API?

### ISSUE THREAD

**Issue by leonard88** [Microsoft/BotBuilder#3624]
How is it possible to get the contact list of my Bot?

**Comment by fanidamj** [comment]
I'm sorry I didn't understand clearly can you please specify if it is any specific channel you want to get the contact list from and what framework you are using for the Bot.

**Comment by leonard88** [comment]
Sorry, so I have created my Bot in Python and using REST API interface to connect to BotFramework (my bot is connected to Skype) .

When I start my python app it can handle contactRelationUpdate -s, so that it knows the list of contacts who are connected with my bot, however if I stop my python app and after a while im restarting i would like to know that list of contacts again, and that's why I would like to some REST API call to the botframework and I'm expecting the list of users who are still contacted with my bot. 

For example: 
1. bot_handler.py started, which is handling BobBot's requests (BobBot has skype channel):
2. X joins to BobBot on skype -> bot_handler will get message and know that X joined BobBot
3. Y joins to BobBot on skype -> bot_handler will get message and know that Y joined BobBot
4. bot_handler.py is stopped
5. Z joins to BobBot on skype -> bot_handler will not get this message as it is not running
6. Y leaves BobBot on skype -> bot_handler will not get this message as it is not running
7. bot_handler is restared
8. How can I know the current status? How can bot_handler know the current contact list of BobBot (which is actually: X and Z)

i hope this clarifies my querry, and thanks in advance for the answers!

**Comment by leonard88** [comment]
Anyone please answer.

@fanidamj @nwhitmont

**Comment by JasonSowers** [comment]
@leonard88 I sounds like the issue can be easily resolved with using storage that persists when you bot is restarted.  Please open a new issue if you have any other questions.
