### ISSUE TITLE
[Skype for Business] Activation error - immutableId is invalid

### ISSUE THREAD

**Issue by mikepugh** [Microsoft/BotBuilder#3625]
## Bot Info 
* Bot handle: ITABot
* App ID: 43cd826c-e278-4fdc-84c0-f20be7db3e19
* SDK Platform: Node.js
* SDK Version: Latest
* Active Channels: Web
* Deployment Environment: Azure

## Issue Description
We are trying to enable the Skype for Business channel but receive an error message on the PowerShell commands provided by SfB.

## Code Example
```
Set-CsOnlineApplicationEndpoint -Uri sip:italuis@americansystems.com

Cmdlet invocation error
+ CategoryInfo : NotSpecified: (:) [Set-CsOnlineApplicationEndpoint], CmdletInvocationException
+ FullyQualifiedErrorId : Error processing cmdlet request,Microsoft.Rtc.Management.Hosted.PlatformService.SetPlatformServiceAppE 
ndpointConfigCmdlet
+ PSComputerName : admin0b.online.lync.com

{'odata.error':{'code':'Request_BadRequest','message':{'lang':'en','value':'Property immutableId is invalid.'},'date':'2017-10-16T22:
07:30','requestId':'451ecf9f-186e-4df2-bc7f-899482df7749','values':[{'item':'PropertyName','value':'immutableId'},{'item':'PropertyEr
rorCode','value':'GenericError'}]}}
```
## Reproduction Steps
1. Create a new bot in Azure
2. Activate Skype for Business Channel
3. Follow instructions from SfB (as a tenant administrator)
4. Error message every time

## Expected Behavior
Bot to be active in SfB for our tenant

## Actual Results
Error message

**Comment by EricDahlvang** [comment]
Hi @mikepugh  

Here: https://msdn.microsoft.com/en-us/skype/skype-for-business-bot-framework/docs/bot-common-errors it states 

`This error is caused by running cmdlet on a hybrid topology with a federated domain. Workaround is to use a non-federated domain.`  

Are you on a hybrid topology with a federated domain?

**Comment by mikepugh** [comment]
No, we are not running any on-prem Skype. We do have ADFS on-prem.

**Comment by mikepugh** [comment]
Any guidance available on getting this setup and working?

**Comment by mikepugh** [comment]
Ok we managed to get our bot setup in our Skype for business environment. It was as simple as using a `@tenant.onmicrosoft.com` address for the bot.
