### ISSUE TITLE
[.NET SDK] Get Dialog Result from Scorable, And Posting it

### ISSUE THREAD

**Issue by xjose97x** [Microsoft/BotBuilder#3627]
Hello!

I was wondering if I could call a dialog from a scorable, get it's result, and post it to the dialog on the stack that existed before the scorable was called.

Thanks!

**Comment by xjose97x** [comment]
I'm trying to do a spell check scorable. The scorable calls a spell check service, and if it finds there's an error on the user input, it should call a dialog, with a yes/no prompt saying:

"Perhaps you ment to say *correction goes here*".
If the user presses yes, then the correction is sent back to the dialog he was participating on before the scorable got triggered, else, the text before the spell check is sent.

@JasonSowers  @nwhitmont , Is this possible?

**Comment by JasonSowers** [comment]
Are you planning on sending every message to a scorable?  Do you have an implementation or eve pseudocode for that?

**Comment by xjose97x** [comment]
@JasonSowers , yes. Every message goes through bing spell check, and if it retrieves a correction, the scorable returns a score of 1. At that point I'm triggering a SpellCheck dialog, in which I ask the user if he ment to say what the spell check suggests or not.

I'm sending him to that dialog through this: 

https://pastebin.com/raw/P0dn1tui

Check the PostASync method.

At that point I want to achieve what I mentioned on my previous post.

I'm just not sure how to achieve that.

Thanks!

**Comment by xjose97x** [comment]
Well, I got this to work in a kind of hacky way. I called context.Done twice. Apparently the first context done closes the dialog flow in the scorable, and the second context done, post that result to the dialog i was before the scorable got triggered.

It works, but I'm sure there must be a non-hacky way to achieve this.

**Comment by JasonSowers** [comment]
Awesome glad you got it working!  If you want us to take a look please post the code and we can see if there is a way that is less of a hack.  However given the nature of what you are trying to do, you may have found the best way even if it is hacky.

**Comment by xjose97x** [comment]
@JasonSowers 

The previous pastebin is the scorable, and this is the SpellCheck dialog: https://pastebin.com/HuZrRt7H

In the dialog, I'm asking the user: "Did you ment to say *correction*"? in a confirm prompt. If he says yes, then i change his activity text for the correction, otherwise leave it as the original message. I'm calling twice context.Done() here.
