### ISSUE TITLE
[Emulator] How to upload file(.pdf,.jpg..jpeg) from bot Emulator and convert to binary(base64) without saving file into local drive?

### ISSUE THREAD

**Issue by MuraliMohanEdiga** [Microsoft/BotBuilder#3628]
* SDK Platform: 
Node.js

## Issue Description
Can any one please help to upload file(.pdf,.jpg..jpeg) from bot Emulator and convert to binary(base64) without saving file into local drive.

## Code Example
var url = session.message.attachments[0].contentUrl;
var fileName=session.message.attachments[0].name;
 var encodedData = new Buffer(fs.createWriteStream(url+"/"+fileName), 'binary').toString('base64');

something like above..But it is not working for me.

## Expected Behavior
We need to upload file from BOT emulator and convert file content into binary data.

## Actual Results
NA

**Comment by FranciscoPonceGomez** [comment]
Hi @MuraliMohanEdiga,

This is more a question to ask in StackOverFlow than here. It doesn't look like something specific to the bot framework. 
https://stackoverflow.com/questions/24523532/how-do-i-convert-an-image-to-a-base64-encoded-data-url-in-sails-js-or-generally


Regards,
Francisco

**Comment by nwhitmont** [comment]
You can accomplish this using a module such as [base64-js](https://www.npmjs.com/package/base64-js).

For more information, check out their documentation here:
https://github.com/beatgammit/base64-js

**Comment by EricDahlvang** [comment]
Relates to: https://stackoverflow.com/questions/46924742/how-to-upload-file-pdf-jpg-jpeg-from-bot-emulator-and-convert-to-binary-ba

**Comment by JasonSowers** [comment]
Also related https://stackoverflow.com/questions/45041317/using-locally-stored-images-in-hero-card
