### ISSUE TITLE
[Azure Bot Service] An internal error occured at the server (Can't access bots anymore)

### ISSUE THREAD

**Issue by jochem4207** [Microsoft/BotBuilder#3630]
## Bot Info 
* Deployment Environment: Azure Bot Service

## Issue Description
Can't access my bot due message "Error occured on Server"

## Reproduction Steps
1. Login to Azure
2. Go to resource group
3. Add a Bot Service
- existing subscription (on which multiple working bots were created)
- exisiting resourcegroup (on which ...)
- using a free app service plan (on which 2 or 3 bots are running)
4. Click create
5. Wait to finish
6. Open
7. See error [zipmi7ay](https://user-images.githubusercontent.com/4976335/31707029-4b9f71f2-b3eb-11e7-96f7-26d62404e452.jpg)

## Expected Behavior
The bot settings to open

## Actual Results
a message "An internal error occured at the server"
[zipmi7ay](https://user-images.githubusercontent.com/4976335/31707029-4b9f71f2-b3eb-11e7-96f7-26d62404e452.jpg)
![bot service error](https://user-images.githubusercontent.com/3075047/31746649-4c78856e-b41d-11e7-93ff-1f3b06fdcbc5.jpg)

## Extra info
This happened after I had another issue in Azure Bot Service. Which I contacted @Azure for then they told me to file a bug report about that. When I wanted to that I got this error (this is several days ago).
I created around 5 bots that give this error.

**Comment by EricDahlvang** [comment]
@jochem4207 Thank you for reporting this.  The Bot Framework team is actively investigating the issue.  I'll report back here once we've determined the root cause.

**Comment by petemh** [comment]
Same issue. Just created a new BOT on Azure and getting the "internal error" issue.

**Comment by jochem4207** [comment]
Any update @EricDahlvang ?

**Comment by mlimache** [comment]
Hello everybody.

I had the same issue with the bot service. My solution was to create the bot service in a new account, without tenants suscriptions. I gave access to the new account to my tenant suscription, when the new account created the bot service, it works. The new account was an outlook account.

Hope it could be usefull for someone.

**Comment by EricDahlvang** [comment]
@jochem4207 @mlimache @petemh 

Do you have a guest account in the target tenant for the subscription being used?

**Comment by mlimache** [comment]
Yes. I have a lot of users on that subscription. Just create a new outlook account, gave him a contribuitor role on the Azure subscription and try to create a bot service with the new account. It should works.

**Comment by EricDahlvang** [comment]
@mlimache Thank you for your reply.  However, I am attempting to help determine root cause: not find a work-around.

**Comment by mlimache** [comment]
@EricDahlvang good luck, and don't forget to share your information with us.

**Comment by sebastinovich** [comment]
Hi @EricDahlvang I am a guest in a customer's subscription (they gave me the contributor role) and I am facing the same issue

**Comment by mlimache** [comment]
@sebastinovich do you have another subscriptions in your account? Use a new account, with an only tenant, like the image.
![image](https://user-images.githubusercontent.com/32964056/31913716-9edbfa36-b80d-11e7-9ad4-6443cb351e9b.png)


 It's the solution. The problem is not the role.

**Comment by EricDahlvang** [comment]
@mlimache I appreciate that you've found a temporary solution: but that is not a permanent solution, as it does not address the root cause of the issue.

**Comment by EricDahlvang** [comment]
@sebastinovich 

mlimache has a good point.  When you attempt to access the bot in your customer's subscription, do you first change the **Directory** to the subscription for the customer within the Azure portal?  

I have two subscriptions here:

![image](https://user-images.githubusercontent.com/11055362/31917271-67380edc-b80b-11e7-869f-081ce63c5d8c.png)

**Comment by jochem4207** [comment]
@EricDahlvang for me i've to switch directories indeed

**Comment by EricDahlvang** [comment]
Is anyone still experiencing this issue?

**Comment by jochem4207** [comment]
@EricDahlvang for me its fixed. I will close it, feel free to reopen it as needed. Thank you very much!

**Comment by sebastinovich** [comment]
Fixed. Thank you!
