### ISSUE TITLE
[.Net SDK, Skype, Adaptive Cards] Cards not being rendered on Skype

### ISSUE THREAD

**Issue by BelvedereHenrique** [Microsoft/BotBuilder#3631]
## Bot Info 
* Bot handle: ActmindsEducauseBot  
* App ID: abc985d3-cc5d-43ce-bf58-b267e80b2ee6
* SDK Platform: .NET
* SDK Version: 3.11
* Active Channels: Facebook Messenger, Cortana Skills, Skype
* Deployment Environment: Azure Web App

## Issue Description
Adaptive cards are not being rendered on Skype channel.
I'm using Bot builder SDK and Adaptive Cards SKD, both .NET.
I got this message every time:
"Get the latest version of Skype to view this card <Learn more button>"

I get redirected to the official download website of Skype.
I've already downloaded the latest version of Skype provided on the website mentioned above

Versions:
Skype desktop: 7.40.0.103
Skype Win10: Last available version on Windows store

## Code Example
My Card:

Body = new List<CardElement>()
                    {

                        new TextBlock()
                        {
                            Text = item.Alias,
                            Weight = TextWeight.Bolder,
                            Size = TextSize.ExtraLarge,
                        },
                        new ColumnSet()
                        {
                            Columns = new List<Column>()
                            {
                                new Column()
                                {
                                    Size = "auto",
                                    Items = new List<CardElement>()
                                    {
                                        new Image()
                                        {
                                            Url = item.Professor.ProfilePicture.Url,
                                            Size = ImageSize.Small,
                                            Style = ImageStyle.Person,
                                            HorizontalAlignment = HorizontalAlignment.Left,
                                        }
                                    }
                                },
                                new Column()
                                {
                                    Size = "auto",
                                    Items = new List<CardElement>()
                                    {
                                        new TextBlock()
                                        {
                                            Wrap = true,
                                            Text = item.Professor.Name,
                                            Weight = TextWeight.Bolder,
                                            Size = TextSize.Large
                                        },
                                        new TextBlock()
                                        {
                                            Wrap = true,
                                            Size = TextSize.Medium,
                                            Text = item.Professor.Title,
                                            IsSubtle = true,
                                        },
                                        new TextBlock()
                                        {
                                            HorizontalAlignment = HorizontalAlignment.Right,
                                            Text = " "
                                        }
                                    }
                                },
                                new Column()
                                {
                                    Size = "auto",
                                    Items = new List<CardElement>()
                                    {
                                        new FactSet()
                                        {
                                            Facts = new List<Fact>()
                                            {
                                                new Fact()
                                                {
                                                    Title = "Room",
                                                    Value = item.Room
                                                },
                                                new Fact()
                                                {

                                                    Title = "Date",
                                                    Value = item.FinalExamDate.ToString("MM/dd/yyyy")
                                                },
                                                new Fact()
                                                {
                                                    Title = "Start",
                                                    Value = item.Period.Start
                                                },
                                                new Fact()
                                                {
                                                    Title = "Duration",
                                                    Value = item.ExamDuration
                                                },
                                            }
                                        }
                                    }
                                }
                            }
                        },
                        new TextBlock()
                        {
                            Text =" "
                        }
                    }

## Actual Results
"Get the latest version of Skype to view this card <Learn more button>" is shown:
![capture](https://user-images.githubusercontent.com/24565006/31716162-57a7bf96-b3e5-11e7-8924-4139508e16df.PNG)

Installed version:
![untitled](https://user-images.githubusercontent.com/24565006/31716161-577e83c4-b3e5-11e7-9ad4-8b15009fec3b.png)

I'm missing something?

Thanks!

**Comment by jochem4207** [comment]
I don't think this is the fix but for testing purposes you can try the windows store skype app to see if that thing is working.

**Comment by BelvedereHenrique** [comment]
@jochem4207
Thanks for the reply.
Same issue:
![image](https://user-images.githubusercontent.com/24565006/31718554-25a6eeb8-b3ef-11e7-82a5-e7478a09b071.png)

**Comment by ViktoriaMedvedenko** [comment]
@BelvedereHenrique: Do AdaptiveCards work with the Cortana channel in your application?

**Comment by BelvedereHenrique** [comment]
@ViktoriaMedvedenko 
No. They are not available on Cortana yet.
The only ones available are: HeroCard, ThumbnailCard, SignInCard and ImageCard.

I verify channelID before rendering the cards.

**Comment by sgellock** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
