### ISSUE TITLE
[Feature Request] Register bots programmatically

### ISSUE THREAD

**Issue by nordsam** [Microsoft/BotBuilder#3632]
## Issue Description
At the moment if you want to register your bot you have to do it from [https://dev.botframework.com/](url) manually. It would make deploying bots a lot easier if bots could be registered programmatically using the sdk. 

## Code Example
This is how the syntax could look:
`botbuilder.registerBot({ auth: 'authKey' },
{
name: 'bot name', 
handler: 'bot_name',  
description: 'description', 
endpoint: 'https://example.com/api/messages', 
channels: ['skype', 'slack']
}).then( ({appId, appPassword}) => {} );`

authKey could be obtained from account settings

**Comment by nwhitmont** [comment]
We are working on something to address this. Stay tuned for updates.

**Comment by jeffrey-opdam** [comment]
@nwhitmont That sounds nice. Would love to see, if we can build an extension for VSTS for that 😄

**Comment by yechongbo** [comment]
@nwhitmont  Are there any updates on this one? Since Bot channel registration is now happening on Azure, can I use Azure SDK to achieve this?

**Comment by yochay** [comment]
You can use Azure CLI to create bots. Read more - [Create bots with Azure CLI](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tools-az-cli?view=azure-bot-service-3.0)
