### ISSUE TITLE
[Skype] Unstable activities delivery to bot's endpoint through the Skype channel

### ISSUE THREAD

**Issue by TheGreenEvil** [Microsoft/BotBuilder#3633]
## Bot Info
* Bot handle: OrganizerBot  
* App ID: 6b24e2e7-9aab-42cc-9c57-1a9ab77ecd3b
* SDK Platform: REST API
* Active Channels: Skype, Telegram
* Deployment Environment: Heroku

## Issue Description
Hello. Activities sent from Skype (messages, bot addition to contact list, bot removal from, contact list), mainly does not reach bot's endpoint and like 1 of 20 times reaches it with 3-5 min latency. In the same time, activities sent through Telegram work normal. What can cause that behavior?

**Comment by IoTGirl** [comment]
Hi @TheGreenEvil ,
Can you tell us more about how "activities" are sent in each case?  There really is not enough detail here for anyone to give you much insight.  
Sincerely,
IoTGirl

**Comment by TheGreenEvil** [comment]
Hi @IoTGirl, thanks for responding. When I talked about "activity", I mean [activity object](https://docs.microsoft.com/en-us/bot-framework/rest-api/bot-framework-rest-connector-api-reference#activity-object) that Microsoft Bot Framework sends to my endpoint on every user action , and I really doesn't know how they sent, on bot sides I am dealing only with receiving and handling them

**Comment by IoTGirl** [comment]
Are there specific activity object types that exhibit the issue?

**Comment by TheGreenEvil** [comment]
Yesterday all activities that I am using in my bot (messages, relation updates) behaved that way. But today seems like messages start to work fine, but relation updates still delivering with 3 min latency

**Comment by IoTGirl** [comment]
Just to confirm, the same activity on other channels does not have the latency issue, only Skype?

**Comment by TheGreenEvil** [comment]
Yes

**Comment by IoTGirl** [comment]
Hi @TheGreenEvil ,
I have escalated this issue to the Skype Bot Team and they have added it to their backlog (1184801 for tracking).  They would very much like to thank you for reporting this issue and a link to this thread is attached.  If you have any more detail as to the type of relation updates and any differences in timing involved, please don't hesitate to add more details here.
Please note that because the Team runs on an Agile schedule, I can't give you a definite timeline for this to be reviewed in depth but should the team have more questions, they will ask you through this GIT instance.
Sincerely,
IoTGirl

**Comment by sgellock** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
