### ISSUE TITLE
[WebChat] Typing action not coming when webSocket is false?

### ISSUE THREAD

**Issue by sreeharikm** [Microsoft/BotBuilder#3635]
Hi,

We are using Web Chat client. We set the webSocket to false, when the user has a chat history (previous conversations), otherwise the webSocket will be true. While setting the webSocket to false, the 'typing' action is not returning back and we are not able to show the typing indicator in the front-end. Came to know that the 'typing' action type is only supported in webSocket but wanted to know if there is any option to get the 'typing' action to make the user experience consistent? Tried returning the typing action from MessageContoller class, but it's not working as expected.

Thanks
Sreehari

**Comment by stevengum97** [comment]
Can you provide an example of the code you're using and the version of the SDK being used?

**Comment by sreeharikm** [comment]
We are using v3.5.5. Web Chat version is v10.6.

Below the code, from chat.html, to set the webSocket true/false.

if (convoCookie == null || convoCookie =='undefined' )
            {
                botConnection = new BotChat.DirectLine({
                    secret: params['s'],
                    token: params['t'],
                    domain: params['domain'],
                    webSocket: true
                });
                cnt = 0;
            }
            else
            {
                botConnection = new BotChat.DirectLine({
                    secret: params['s'],
                    token: params['t'],
                    domain: params['domain'],
                    webSocket: false,// defaults to true
                    conversationId: convoCookie
                });
                cnt++;
            }

When the webSocket value is true, the typing action is not returning. In MessageContoller.js, tried returning to typing action like this (Post method).

await connector.Conversations.ReplyToActivityAsync(isTypingReply);

**Comment by sreeharikm** [comment]
Please let me know if there is any way to display 'typing indicator' while using the polling (webSocket=true) method in chat.html.

**Comment by JasonSowers** [comment]
@danmarshall

**Comment by danmarshall** [comment]
Hi @sreeharikm - typing is only available on websockets.

**Comment by sreeharikm** [comment]
@danmarshall thanks for the update. Can you tell me where is the restriction, bot framework is not sending the 'typing' action or at the reactjs level? 
In bot code, tried setting the 'typing' in reply using ReplyToActivityAsync but the action type was not received. Where is it filtered out?

**Comment by danmarshall** [comment]
I will need to check to make sure, but I believe it may be in the DirectLine server

**Comment by eanders-MS** [comment]
Yep, it happens on the server. Typing activities are ephemeral in nature and don't get queued up for delivery later. They're either sent immediately or dropped. For Direct Line, that requires a Web Socket.

**Comment by fanidamj** [comment]
Closing the issue assuming it as resolved. Please reopen a new issue if it still persists.
