### ISSUE TITLE
[Question, bug, State Service] Bot framework fails to save state to Doc DB in Teams 1:1 conversation (and errors dialogue)

### ISSUE THREAD

**Issue by shepwalker** [Microsoft/BotBuilder#3637]
## Bot Info 
* Bot handle: 
* App ID: c2f8e8ca-e563-4ec2-a7ef-a6532b172b14
* SDK Platform: .NET
* SDK Version: 3.9
* Active Channels: **MS Teams**, Slack, Email, Directline
Environment: Other

## Issue Description
When user initiates a new 1:1 conversation in MS Teams, bot errors out.  Digging in, the bot fails to save state to DocDB because the "name" field is too big (258 characters vs 255 max).  I don't know whether this ID could leak information to provide it but happy to provide the ID in DM.  Does not happen consistently - some users work, some don't. 

## Reproduction Steps
1.  Create bot with Teams channel enabled.
2.  Onboard bot to DocDB. 
3.  Initiate conversation with bot account.  

## Expected Behavior
Bot to respond correctly and save dialogue state.

## Actual Results
Returns with "My bot is having an issue".  Fails to save dialogue state.

**Comment by vishwacsena** [comment]
Fixed via microsoft/botbuilder-azure#36
