### ISSUE TITLE
[Question] Allow other Localization implementations (may require refactoring)

### ISSUE THREAD

**Issue by SynerG** [Microsoft/BotBuilder#3639]
* SDK Platform: Node.js

Is it possible to use a different Localization system than the embedded one?

We would like to use the same type of Localization that we use in other parts of our server and client apps. In our case, our current system is based on `FormatJS`, so we do not require `sprintf.vsprintf()` formatting, as ours are based on the `ICU Message Syntax`, and we define our localization messages in files that do not match the `./locale/<language>/library.json`pattern.

I expected that the Localization system was modularized and we could replace it with our own implementation (e.g. implementing the `ILocalizer` interface and injecting our class instead of `DefaultLocalizer`).

However, localization code does not seem to be modularized so we have not found a clear path to replace it:
- The use of a specific `DefaultLocalizer` implementation is hardcoded in `UniversalBot.createSession()`. 
- The localizer instance to be used cannot be defined when the bot is created, only the localization parameters of the current implementation (e.g. `botLocalePath` and `defaultLocale`).
- Calls to `sprintf.vsprintf()` for message formatting are spread in multiple classes and methods. For example, `Session`class has its own methods to format singular/plural form and to apply arguments with their own calls to `sprintf`, while action card classes (e.g. `HeroCard`, `ReceiptCard`) depend on the `Message` class that makes its own call.

Is there a recommended way to replace the Localization system used?
We have found other parts of BotBuilder clearly modularized (e.g. BotConnector service or BotStorage), but we are having a harder time customizing Localization.

**Comment by nwhitmont** [comment]
@SynerG What you are asking for is not currently a feature.

The SDK is open-source, so you are free to modify it to suit your needs. 

We are working on a new v4 SDK which will be much more modularized than the existing v3 line. Stay tuned for updates on our blog.

https://blog.botframework.com/

**Comment by SynerG** [comment]
Thank you very much. Looking forward to what the new v4 SDK will bring.
Is there a public Roadmap and timeframe for v4? I have been skimming the blog and open issues, but I have not seen it.
It would be good to know what is going to change in order to better decide how we are going to use and modify v3 to be prepared for v4.

**Comment by SynerG** [comment]
Thank you very much. Looking forward to what the new v4 SDK will bring.

Is there a public Roadmap and timeframe? I have been skimming the blog and open issues, but I have not found info.

It would be good to know what v4 is going to change, in order to decide how we are going to use and modify v3 to be prepared for v4.
