### ISSUE TITLE
LUIS Program Control Issue

### ISSUE THREAD

**Issue by srijiths** [Microsoft/BotBuilder#364]
```
academyDialog.add('/userDetails',[
        function(session) {
                if(utilities.isEmpty(session.userData.skills)) {
                        builder.Prompts.text(session,prompts.update_Skills);
                        session.beginDialog('/luis');
                } else if(utilities.isEmpty(session.userData.department)) {
                        builder.Prompts.text(session,prompts.update_Department);
                        session.beginDialog('/luis');
                }
        }
]);
```

```
academyDialog.add('/luis', luisDialog.onDefault(builder.DialogAction.send(prompts.default_response)));
luisDialog.on('Current_skills', [getCurrentSkills]);
luisDialog.on('Department', [getDepartment]);
function getCurrentSkills(session, args, next) {
        for(var i=0; i < args.entities.length; i++) {
                var skill = args.entities[i].entity;
                session.userData.skills = session.userData.skills +"," +skill;
                var data = orient.insertUserDetails(session.userData.name,"Skills",skill,"Users","Topic");
        }
        session.beginDialog('/userDetails');
}

function getDepartment(session, args , next) {
        for(var i=0;i<args.entities.length;i++) {
                var dept = args.entities[i].entity;
                session.userData.department = session.userData.department +","+ dept;
                var data = orient.insertUserDetails(session.userData.name,"belongs_to",dept,"Users","Department");
        }
        session.beginDialog('/userDetails');
}
```
Here in /userDetails , i am entering a text and that is been passed to LUIS and getting the results. In the '/luis' , after a function , the focus is set to '/userDetails' and there i am checking whether a condition is met or not.

For the first time , it will execute the block in '/userDetails' IF BLOCK and next time i am expecting to execute the ELSE IF part. I see that control is passing to ELSE IF , second time , but LUIS side its continuously taking the input entered for first IF and its executing recursively by passing the control between '/userDetails" and '/luis". My question here is , i am checking a condition in '/userDetails' , so it should pass the control accoridngly. Whats wrong here in the code. 

Also i am getting some weird behaviour from Bot. Sample screen shots attached.
![screenshot from 2016-05-29 18 08 01](https://cloud.githubusercontent.com/assets/1046319/15633362/e322c5b8-25c8-11e6-98e9-775a52237e7c.png)
![screenshot from 2016-05-29 18 07 45](https://cloud.githubusercontent.com/assets/1046319/15633363/e324fc5c-25c8-11e6-861a-565ccf99f6dc.png)

**Comment by Stevenic** [comment]
The issue is you can't both call an start a dialog from within the same handler. The behavior is undefined right now. You're on the right path but you need to think more in stacks when you construct your waterfalls. Here's a cleaner way of achieving what you're trying to do:

```

academyDialog.add('/luis', luisDialog.onDefault(builder.DialogAction.send(prompts.default_response)));
luisDialog.on('Current_skills', '/getCurrentSkill');
luisDialog.on('Department', '/getCurrentDepartment');

academyDialog.add('/getCurrentSkill', [
    function (session, args) {
        // Store entities if specified by user
        for(var i=0; i < args.entities.length; i++) {
                var skill = args.entities[i].entity;
                session.userData.skills = session.userData.skills +"," +skill;
                var data = orient.insertUserDetails(session.userData.name,"Skills",skill,"Users","Topic");
        }
        
        // Prompt user if skills missing, otherwise return to /luis dialog
        if (utilities.isEmpty(session.userData.skills)) {
            builder.Prompts.text(session,prompts.update_Skills);
        } else {
            session.endDialog();
        }
    },
    function (session, results) {
        if (results.response) {
            // ... save skills ...
        }
        
        // Return to /luis dialog    
        session.endDialog();
    }
]);
```
Define a separate `/getCurrentSkill` & `/getCurrentDepartment` dialogs that each process one user flow.  The `LuisDialog` class lets you pass the ID of a dialog to start as a handler and it will automatically pass that dialog any entities recognized by the LUIS model.  You can then do the logic you were doing to save the skill or department and as a next step conditionally determine if  you need to prompt the user to enter them.  If you do then just send the prompt and catch the results in the next step of your waterfall. If the skills are filled in you can simply call `session.endDialog()` to return to you /luis dialog.

**Comment by srijiths** [comment]
Thank You @Stevenic . I re arranged my program flow and its working fine. Still i have to learn on the Bot program flow. There is one issue. That is when prompted for an input and control come to /luis. But before taking any user input , LUIS is prompting the default message. Screenshot attached.
![01](https://cloud.githubusercontent.com/assets/1046319/15644307/de8ca99a-266f-11e6-9a19-d749964d5f6f.png)

**Comment by srijiths** [comment]
Issue fixed. It was because this code
```
academyDialog.add('/userDetails',[
        function(session) {
                if(utilities.isEmpty(session.userData.skills)) {
                        builder.Prompts.text(session,prompts.update_Skills);
                        session.beginDialog('/luis');
                } 
        }
		
]);
```
changed to 

```
academyDialog.add('/userDetails',[
        function(session) {
                if(utilities.isEmpty(session.userData.skills)) {
                        builder.Prompts.text(session,prompts.update_Skills);
                } 
        },
		function(session,results) {
			session.beginDialog('/luis');
		}
]);
```
