### ISSUE TITLE
[MS teams] authentication 

### ISSUE THREAD

**Issue by MarriWee** [Microsoft/BotBuilder#3640]
## Bot Info 
* Bot handle: BotSaraInfra 
* App ID: efa5dd73-149f-4b37-9d04-9fde465334ca
* SDK Platform: .NET
* SDK Version: 3.8.1
* Active Channels: MS Teams, Direct Line
* Deployment Environment: Azure App Service

## Issue Description
I'm using this example from Ricard DiZerega  (https://blogs.msdn.microsoft.com/richard_dizeregas_blog/2017/02/15/sharepoint-framework-and-contextual-bots-via-back-channel/) on my bot on SharePoint. This is working fine and I can search for dokuments and Lists in SharePoint without authenticat the user. I want my bot to be on MS Teams as well. But the problem I'm facing is that I have to authenticat the user again with a sign in card for searching for documents etc in SharePoint. Is there a way to avoid this? Since the user is already log in

**Comment by JasonSowers** [comment]
Every implementation I have seen uses a method in which the user has to log in again.  It may be possible to accomplish what you would like, but I have never seen it. You may find some help in [botAuth](https://github.com/MicrosoftDX/botauth) or [AuthBot](https://github.com/MicrosoftDX/AuthBot/tree/master/AuthBot).
