### ISSUE TITLE
Unable to integrate Cortana with speech identification api's

### ISSUE THREAD

**Issue by rsandhu123** [Microsoft/BotBuilder#3644]
## Bot Info 
* Bot handle: pay me
* App ID: 41c16bba-5fef-4d1b-8b81-c76ee6d20b6c
* SDK Platform: Node.js
* SDK Version: 3.11
* Active Channels: Cortana
* Deployment Environment: ngrok

## Issue Description
How can your bot with Cortana channel use cognitive voice identification? Since it needs audio stream and from what I know, Cortana doesn't make it available to the bot.

**Comment by nwhitmont** [comment]
@rsandhu123 Correct. Due to privacy & security considerations, the Cortana channel does not provide developer access to the raw audio stream.
