### ISSUE TITLE
[Node.js SDK, Email Channel] triggerActions now behave differently

### ISSUE THREAD

**Issue by MbV93** [Microsoft/BotBuilder#3646]
## Bot Info 
* Bot handle: epTestBot
* App ID: 402574db-395f-4f2d-80fd-a8ca814dd3c9
* SDK Platform: Node.js
* SDK Version: 3.11.0
* Active Channels: Skype, Email, Webchat
* Deployment Environment: Azure App Service

## Issue Description
Hey, I have a bot with some triggers that were working properly on version 3.8.4 on the email channel. If you sent a trigger word to the bot it would return the trigger dialog. Now that I have updated BotBuilder to the latest 3.11.0, the bot on the email channel always sends main dialog first, triggers don't work unless I'm replying directly to that main dialog. This only happens on the email channel, webchat, emulator and skype work fine.

Any insight on how I could correct this behavior would be much appreciated. Thanks!

**Comment by nwhitmont** [comment]
@MbV93 Can you post your code that is causing the problem? For example, how are the `triggerActions` configured? What data is being sent to the bot that is not correctly recognized?

**Comment by MbV93** [comment]
Sure:
```
bot.dialog('help', function(session, args, next){
        session.endConversation('Hi, you can use these words at any point: <br/>'+
         '- Cancel: Ends the conversation and returns to the main menu <br/>'+
         '- Bye: Ends the conversation <br/>'+
         '- Who are you: General information about me and my function <br/>'+
         '- Info: Shows available workflows and their descriptions. <br/>');
    }).triggerAction({
        matches: /^help$/i
    });
```

```
bot.dialog('who', function(session){
        session.endDialog('I am a programmable bot, I can be configured to assist with simple tasks through the botflow.js file');
    }).triggerAction({
        matches: /^who are you$/i,
        onSelectAction: (session, args, next) => {
        // Add the help dialog to the dialog stack 
        // (override the default behavior of replacing the stack)
            session.beginDialog(args.action, args);
        }
    });
```
Pretty standard, they work normally on messaging channels but email channel ignores them I guess and shows the main dialog.

**Comment by MbV93** [comment]
Been doing some testing, downgraded botbuilder to 3.8.4 but it still gave me the same behavior, the bot still sends the main dialog first and for the trigger to work you have to reply to that first message. I also redeployed old commits where the triggers were previously working fine and it still gave me the same behavior.

**Comment by fanidamj** [comment]
Can you please let us know if the issue still persists?

**Comment by JasonSowers** [comment]
Please open a new issue if you are still experiencing problems
