### ISSUE TITLE
[Question] Unique User ID  integration Sharepont Online for WebChat and user identity SSO?

### ISSUE THREAD

**Issue by ShujaathKhan** [Microsoft/BotBuilder#3649]
## Bot Info 
* SDK Platform:  Node.js
* Active Channels: Skype for Business, MS Teams, webchat
* Deployment Environment:  Azure App Service

## Issue Description
User ID is not consistent for same user who comes from different channel.
- MSTeams:29:1eyyudDczxzvqxWTAKGXSREP_xwE1Aga7qZRLHCMhyfwyNzUpm4Tue-6Uj0pBs0Z3BD6dfyLXSKirpWrrAq2ndw
- Skype for Business: sip:test@aaa.onmicrosoft.com
- WebChat :bc22a166acc64d588a4373f9ad71fa2b

## Expected Behavior
Unqiue user ID for the authenticated users

## Actual Results
- MSTeams:29:1eyyudDczxzvqxWTAKGXSREP_xwE1Aga7qZRLHCMhyfwyNzUpm4Tue-6Uj0pBs0Z3BD6dfyLXSKirpWrrAq2ndw
- Skype for Business: sip:test@aaa.onmicrosoft.com
- WebChat: bc22a166acc64d588a4373f9ad71fa2b

If this works then we would be able to precisely get the user context and conversation context and address accordingly.
Or if we've any other way that would also works fine.

**Comment by JasonSowers** [comment]
Each channel is going to have its own way to identify the user.  What exactly is your question?

**Comment by EricDahlvang** [comment]
@ShujaathKhan Message formats and ids are different on the various channels.  The developer is responsible for mapping the disparate ids from the different channels to the authenticated user's id.  You can save the channel's userid with the auth userid in a database, or some storage location, after the user authenticates.

Here https://docs.microsoft.com/en-us/bot-framework/resources-identifiers-guide#channel-account you will find more information about ids.

**Comment by ShujaathKhan** [comment]
@JasonSowers  identity who is the user interacting with BOT

**Comment by ShujaathKhan** [comment]
@EricDahlvang this is long way and is fine, what if we already know current logged is user and he is already authenticated in sharepoint online again asking user to login would be odd way is what i think.
for ex., take Skype of business we do not login again and again and SSO happens with it and sip of user is known.
