### ISSUE TITLE
Session Error: Dialog[/] not found. when trying to talk to Skype Bot [NodeJS]

### ISSUE THREAD

**Issue by alexandrev** [Microsoft/BotBuilder#365]
I'm facing the following error when I'm trying to talk to Skype Bot using the skype-sdk for NodeJS:

```
Session Error: Dialog[/] not found.
```

You can see that in my code I've added / as one of the dialogs:
```
bot.add('/', dialog);
botSkype.add('/', function (session) {
   session.send('Hello World'); 
});
...
// Setup Restify Server
var server = restify.createServer();
server.post('/api/messages', bot.verifyBotFramework(), bot.listen());
server.post('/v1/chat', skype.messagingHandler(botService));
server.listen(process.env.PORT || 8080, function () {
    console.log('%s listening to %s', server.name, server.url);
});
```

Any help?

**Comment by Stevenic** [comment]
Interesting... Have you tried running the more stripped down `hello-SkypeBot` example? Just wondering if you get the same issue. I see you trying to run two different styles of bot. I can't think of any reason why that wouldn't work but it is an added complexity.

**Comment by alexandrev** [comment]
Hi @Stevenic, as you said I'm using two kinds of bot sharing the same logic but I also think that should'nt be related. I'm going to execute the hello-world example I can find in the web and get back to you with the results.

**Comment by alexandrev** [comment]
If I try, exactly, the hello-world I don't get the error message but it doesn't work neither. I'm using ngrok as the tutorial says, and I cand see the request coming to the bot application, but I can't see any reply on the Skype screen:

![image](https://cloud.githubusercontent.com/assets/947041/15635826/33e68680-25ea-11e6-8f59-72fd1e03d6cd.png)

As you can see, no answer:

![image](https://cloud.githubusercontent.com/assets/947041/15635830/3f907cb6-25ea-11e6-983c-05f99f61b47f.png)

**Comment by alexandrev** [comment]
My by band, when I replace my code with the one from the tutorial I replaced the appsecret too. Now, the tutorial is working fine, without any error. Probably, the original error is related to Luis Dialog inside Skype Bot?

**Comment by alexandrev** [comment]
Ok!! I've found the error and fixed, but now I'm not sure if it is a bug or not.. :)

**Comment by Stevenic** [comment]
Glad you found it. What did you have to do? I can tell you if I think it's a bug :)

**Comment by alexandrev** [comment]
I'm going to try to explain the situation: 

The problem was I have two SkypeBots with the same botService object. One without any dialog assigned and the other as you could see with dialogs asigned. When I create the REST server I use the one with the dialogs assigned, but even doing that it seems that it uses the first one without the dialogs.

I'm going to create a small test to reproduce the error and I get back to you and you can decide if it is a bug or not.

**Comment by alexandrev** [comment]
Here is the code without my keys :)

```
var restify = require('restify');
var builder = require('botbuilder');
var assert = require('assert');
const skype = require('skype-sdk');

// Initialize the BotService
const botService = new skype.BotService({
    messaging: {
        botId: "XXX",
        serverUrl : "https://apis.skype.com",
        requestTimeout : 15000,
        appId: "XXX",
        appSecret: "XXXX"
    }
});



// Create bot and add dialogs
var bot = new builder.SkypeBot(botService);
var botSkype = new builder.SkypeBot(botService);
dialog.setThreshold(0.5);

botSkype.add('/', function (session) {
   session.send('Hello World'); 
});

// Setup Restify Server
var server = restify.createServer();
server.post('/v1/chat', skype.messagingHandler(botService));
server.listen(process.env.PORT || 8080, function () {
    console.log('%s listening to %s', server.name, server.url);
});
```

**Comment by alexandrev** [comment]
I think the problem here is that when you link the REST server with the bot you don't use the bot object but the botService object which is related to two bot instances, and it have to choose one of them and I think it chooses the first one.

**Comment by Stevenic** [comment]
The issue is both bots are sharing the same `botService` instance and sharing the same rest endpoint. It will be somewhat random as to which one replies

**Comment by Stevenic** [comment]
you need 2 separate `botService` instances and 2 different endpoints

**Comment by alexandrev** [comment]
I have no problem  closing the issue if you tell me that's expected behavior :)

**Comment by Stevenic** [comment]
Knowing how the Skype service works internally I'd say it's pretty much expected.

**Comment by alexandrev** [comment]
Thank you for all your support :)

**Comment by dharmendracs** [comment]
i am using FormDialog to create form and is getting rendered properly in emulator.

here is the image in emulator
![1](https://cloud.githubusercontent.com/assets/6490489/16900377/16b7f0f8-4c41-11e6-847d-6b8171a6bb57.png)

however when i integrate same thing in skype ,it shows blue screen dialog anf does not dispaly button/choice  to select category.
here is image in skype
![2](https://cloud.githubusercontent.com/assets/6490489/16900387/68fcd946-4c41-11e6-9c05-0fe3fe66c2e5.png)

could you please let me know problem ?

**Comment by santhosh117** [comment]
I cannot publish my skype bot. Plz help for me
![capture](https://cloud.githubusercontent.com/assets/20519603/16951249/d26a2b1c-4de1-11e6-8c82-4d8471f0f558.PNG)

**Comment by dharmendracs** [comment]
As per my understanding,You need to host it somewhere on the cloud/on
premise server. localhost can not be used.

**Comment by santhosh117** [comment]
thanks a lot @dharmendracs. I install ngrok i got https protocol using that as a message endpoint
