### ISSUE TITLE
[Skype] Unable to send .docx file attachment?

### ISSUE THREAD

**Issue by khushboo22singh** [Microsoft/BotBuilder#3650]
## Bot Info 
* Bot handle: ConnectedMarketingBoT
* App ID: a1f26f07-6e24-4048-9b7b-baaa76b38ff4
* SDK Platform: .NET c#
* Active Channels: Skype
* Deployment Environment: Azure App Service

## Issue Description
 My bot is unable to send attachment on Skype, the same code works fine on bot emulator. I receive following error:-  "Sorry, my bot code is having an issue." I am unable to detect the issue. Any help is appreciated

## Code Example
following is the code
```cs
 var imagePath = HttpContext.Current.Server.MapPath("~/images/Bots.docx");

            using (var connector = new ConnectorClient(new Uri(serviceUrl)))
            {
                var attachments = new Attachments(connector);
                var response = await attachments.Client.Conversations.UploadAttachmentAsync(
                    conversationId,
                    new AttachmentData
                    {
                        Name = fileName,
                        OriginalBase64 = File.ReadAllBytes(imagePath),
                        Type = "docx"
                    });

                var attachmentUri = attachments.GetAttachmentUri(response.Id);

                return new Attachment
                {
                    Name = fileName,
                    ContentType = "docx",
                    ContentUrl = attachmentUri
                };
            } 
```

## Expected Behavior
attachment to appear to skype screen to the user, which can be downloaded

![image](https://user-images.githubusercontent.com/33002605/31863289-573df62e-b769-11e7-8234-745dac53fa25.png)

**Comment by nwhitmont** [comment]
@khushboo22singh `.docx` file format is not supported.

To send image attachments, use standard image formats like `.png`, `.jpg`, `.gif`, and set the `type` property as HTML MIME type. Eg. `application/png`.

**Comment by Ma3yTa** [comment]
@nwhitmont What mime types are supported?
