### ISSUE TITLE
Read Location From Messenger using FB Maps

### ISSUE THREAD

**Issue by SerendioSoftwares** [Microsoft/BotBuilder#3651]
## Bot Info 
* Bot handle: 
* App ID: 
* SDK Platform: Nodejs
* SDK Version: 
* Active Channels: FB
* Deployment Environment: ngrok

## Issue Description
I seem to get a blank response on console.log of location dialog. Maybe microsoft middleware dosent convert the data when sending to botbuilder backend?

## Code Example
 var msg = new builder.Message(session).sourceEvent({
    //specify the channel
    facebook: {
      //format according to channel's requirements
      //(in our case, the above JSON required by Facebook)

      "text": "Here's a quick reply!",
    "quick_replies":[
      {
        "content_type":"location"
      }
      ]
    }

          
        
      });
        session.beginDialog('location', {
            prompt: session.send(msg),
            retryPrompt: session.gettext('Invalid Location')
        }); 

         console.log('Message Sent');

bot.dialog('location', basicPrompterWithExpression(function (input){
    console.log(JSON.stringify(input));
    return false;
}));

function basicPrompterWithExpression(expression) {
  return new builder.IntentDialog()
      .onBegin(function (session, args) {
      // console.log(args.check);

          session.dialogData.retryPrompt = args.retryPrompt;
          session.dialogData.check=args.check;
          session.send(args.prompt);
      }).onDefault(function (session, args) {
          var input = session.message.text;
          // console.log(args)
          // console.log(session.message.text)
          if (expression(input, session.dialogData.check)) {
              session.endDialogWithResult({ response: input });
          } else {
              session.send(session.dialogData.retryPrompt);
          }
      });
}

## Expected Behavior
JSON response from FB location.

## Actual Results
Got empty response instead.

**Comment by jochem4207** [comment]
Your formatting is a bit off

**Comment by SerendioSoftwares** [comment]
Solved:
read session.message.entities
Not session.message.text -which is empty
