### ISSUE TITLE
[Question] How to use the bot framework as platform?

### ISSUE THREAD

**Issue by Vincentchhsu** [Microsoft/BotBuilder#3656]
## Bot Info 
SDK Platform: .Net
SDK Version: 3.9
Active Channels: Direct Line

## Issue Description

Hi !
How to use the bot framework as platform where users can use their own bots and LUISs ?
But they need call our functions(through web service) when want to get their LUIS's reply data in db.
We only want to manage common functions(e.g. get the reply data in db or switch LUIS ) 
Thanks.

**Comment by nwhitmont** [comment]
@Vincentchhsu You will need to design a custom solution to achieve this goal as it is beyond the scope of BotBuilder SDK's current functionality.
