### ISSUE TITLE
[Telegram] How correctly retrieve the phone number from the message?

### ISSUE THREAD

**Issue by verdysh** [Microsoft/BotBuilder#3657]
## Bot Info 
SDK Platform: .NET
SDK Version: 3.9.0.0
Active Channels: Telegram

## Issue Description
Hi!

In Telegram it is possible to output 2 special buttons:
- request_contact - If True, the user's phone number will be sent as a contact when the button is pressed. Available in private chats only;
- request_location - If True, the user's current location will be sent when the button is pressed. Available in private chats only.

(this is done in a similar way https://github.com/Microsoft/BotBuilder/issues/3642)

Message from bot I get in the usual way:

```
private async Task MessageReceivedAsync(IDialogContext context, IAwaitable<IMessageActivity> result)
{
    var message = await result;
...
```

If user clicks on the button "request_location", coordinates come in the message.Entities property.
If user clicks on the button "request_contact", there is no phone number in any special property (message.Text, message.Attachments, message.Entities).

The phone number is only present in the message.ChannelData property with a bunch of other service information:

```
"contact":
{  
	"phone_number":"...",
	"first_name":"...",
	"last_name":"...",
	"user_id": 123456789
}
```

How correctly retrieve the phone number?

```
if(
	String.IsNullOrEmpty(message.Text) &&
	message.Attachments.Count == 0 &&
	message.Entities.Count == 0
	) {
	
	// Looking "contact" node in message.ChannelData property
}
```

Or there is a more elegant solution?

**Comment by JasonSowers** [comment]
This seems like a reasonable way considering where the data is stored.  What are your concerns?

**Comment by nwhitmont** [comment]
@verdysh Accessing the `message.ChannelData` property is the correct way of getting this data.

**Comment by verdysh** [comment]
@JasonSowers, this method seemed too cumbersome to me and I had fears that I was doing something wrong. So I decided to clarify this.

@nwhitmont, thanks!
