### ISSUE TITLE
[Channel Configuration] Unable to add Cortana channel?

### ISSUE THREAD

**Issue by alexNML** [Microsoft/BotBuilder#3658]
## Bot Info 
* App ID: 7b493e1e-31a9-49f4-a5cd-e81b568c6bef
* SDK Platform: .NET C#
* SDK Version: v4.7
* Active Channels: Facebook
* Deployment Environment:  Auzure Bot Service

## Issue Description
Cannot add the Cortana channel to Azure.

## Reproduction Steps
1. Add cortana at [https://dev.botframework.com/bots/channels]()
2. Enter the required information(refer to[https://stackoverflow.com/questions/46831777/cant-add-cortana-to-dev-bot-framework]() when encountering first errors)
3. 

## Expected Behavior
Cortana channel should be added when the save button is clicked

## Actual Results
Unable to add the cortana channel. Attached is a word document containing screenshots of each issue(bug) followed by a description for those issues. Bug 1 + 2 was solved through trial and error [https://stackoverflow.com/questions/46831777/cant-add-cortana-to-dev-bot-framework](). Bug 3 cannot be worked around.
[Dev Framework Bugs.docx](https://github.com/Microsoft/BotBuilder/files/1410244/Dev.Framework.Bugs.docx)

**Comment by JasonSowers** [comment]
Thank you for reporting this. This is a known issue that has affected me too.
if you click this button:
![image](https://user-images.githubusercontent.com/6301037/31954583-db02c656-b89a-11e7-944a-b1adc066ecf8.png)

It will open up more options.  If you see the text boxes below outlined in red click the Implicit radio button:
![image](https://user-images.githubusercontent.com/6301037/31954729-3ac85088-b89b-11e7-8a12-856ba13652ff.png)

then go back and disable the "Cortana should manage my users identity" this should clear up your problem and allow you to add the cortana channel

**Comment by nwhitmont** [comment]
@alexNML Did you register the bot using a MSA account? Cortana does not currently support AAD accounts.

**Comment by alexNML** [comment]
Hi @JasonSowers , that did not work for me but thanks for your response. Eventually, after rigorous refreshing and spam clicks on that save button, i was able to add Cortana. The issue arises again when i try to add changes to my Simple Cortana bot - i cannot add more information to it due to this as again, it will **not** save.

**Comment by alexNML** [comment]
Hi @nwhitmont , thanks for your response. I did actually add administrator privileges to my Microsoft account(the one i used to add Cortana channel) using my one from azure(used to create my bot). I cannot however have the Microsoft account be the only one used to create my bot due to the subscriptions and privileges i currently have on my main account. Thankfully, as i said to Jason, i was able to add the channel, however having the same issues trying to edit it.

**Comment by irfanahm** [comment]
I am facing same issue. Do we have any verified workaround so far? While trying to register my bot for Cortana channel, all option are already greyed out and when click on Register option, it throws an error.

**Comment by JasonSowers** [comment]
@irfanahm can you open a new issue please and detail what you are experiencing.

**Comment by WormyOne** [comment]
@irfanahm I am currently seeing the same 'all options greyed out' behaviour in Cortana channel registration.  It would appear from a new issue you raised that you got past this issue.  Can you share how?

**Comment by alokraj68** [comment]
Am facing the same grey out issue. cant register any bots to Cortana now. someone, please help.

**Comment by irfanahm** [comment]
It was an issue with Microsoft side. Around 10 Jan they have fixed it and post that I was able to register my Bot with Cortana.

**Comment by JasonSowers** [comment]
@WormyOne and @alokraj68  please see [this walkthrough](https://help.knowledge.store/tutorials_code_samples/bot_framework/index.html) and let me know if it works for you.

**Comment by vishwacsena** [comment]
Closing this for lack for further activity.
