### ISSUE TITLE
Can't retrieve Telegram update object

### ISSUE THREAD

**Issue by Giacomo411** [Microsoft/BotBuilder#366]
I can't retrieve any incoming update object from Telegram. At present, I am trying to create the inline query answer list but I can't retrieve what the user is writing.

**Comment by eanders-MS** [comment]
You should be able to find the native Telegram message in the channelData field of the incoming connector message. Have you looked there? I admit this is a scenario I've not tested.

**Comment by eanders-MS** [comment]
Looks like we're not forwarding the Telegram message in the inline query case. Working on a fix now.

**Comment by eanders-MS** [comment]
A fix has been deployed to production. Here's a sample inline query reply (in Javascript/Node.js):

```
session.sendMessage( {
	method: "answerInlineQuery",
	parameters: {
		inline_query_id: session.message.channelData.inline_query.id,
		results: JSON.stringify([
			{
				type: "photo",
				id: "1",
				title: "Misty Castle",
				photo_url: "http://www.mrwallpaper.com/wallpapers/misty-castle.jpg",
				thumb_url: "http://www.mrwallpaper.com/wallpapers/misty-castle.jpg"
			},
			{
				type: "photo",
				id:"2",
				title: "Stonehenge",
				photo_url: "http://www.mrwallpaper.com/wallpapers/stonehenge.jpg",
				thumb_url: "http://www.mrwallpaper.com/wallpapers/stonehenge.jpg"
			},
			{
				type: "photo",
				id: "3",
				title: "Dragon",
				photo_url: "http://www.mrwallpaper.com/wallpapers/dragon-art-1920x1200.jpg",
				thumb_url: "http://www.mrwallpaper.com/wallpapers/dragon-art-1920x1200.jpg"
			}
		])
	}
});
```
Please reopen if you're still having issues.

Eric

**Comment by fercom** [comment]
will this work as a inline query reply?
`{
  "method": "answerInlineQuery",
  "Parameters": {
    "inline_query_id": "999490456661941895",
    "results": [
      {
        "type": "photo",
        "id": "",
        "title": "",
        "photo_url": "http://memegen.link/custom/r/tdfgggfsfhlh.jpg?alt=http://www.networkforgood.com/wp-content/uploads/2015/08/bigstock-Test-word-on-white-keyboard-27134336.jpg",
        "thumb_url": "http://memegen.link/custom/r/tdfgggfsfhlh.jpg?alt=http://www.networkforgood.com/wp-content/uploads/2015/08/bigstock-Test-word-on-white-keyboard-27134336.jpg"
      },
      {
        "type": "photo",
        "id": "",
        "title": "",
        "photo_url": "http://memegen.link/custom/r/tdfgggfsfhlh.jpg?alt=http://www.velior.ru/wp-content/uploads/2009/05/Test-Computer-Key-by-Stuart-Miles.jpg",
        "thumb_url": "http://memegen.link/custom/r/tdfgggfsfhlh.jpg?alt=http://www.velior.ru/wp-content/uploads/2009/05/Test-Computer-Key-by-Stuart-Miles.jpg"
      },
      {
        "type": "photo",
        "id": "",
        "title": "",
        "photo_url": "http://memegen.link/custom/r/tdfgggfsfhlh.jpg?alt=https://www.test.com/assets/_slide_image/slide0001.jpg",
        "thumb_url": "http://memegen.link/custom/r/tdfgggfsfhlh.jpg?alt=https://www.test.com/assets/_slide_image/slide0001.jpg"
      }
    ]
  }
}`

**Comment by eanders-MS** [comment]
"Parameters" should be all lowercase: "parameters". "id" is a required field and cannot be left blank.
Here are some links to relevant documentation, which may offer additional help:
https://core.telegram.org/bots/api#inline-mode
https://core.telegram.org/bots/api#inlinequeryresultphoto
and
http://docs.botframework.com/connector/custom-channeldata/#custom-telegram-messages
