### ISSUE TITLE
How to get user name/email(unique user) from skype

### ISSUE THREAD

**Issue by Hiranmayee24** [Microsoft/BotBuilder#3660]
## Issue Description
I am using bot framework and i want skype username/email id (e.g xyz.abc1 as login name).
please let us know how to get user information

**Comment by Hiranmayee24** [comment]
Is there any API available to get User Information?

**Comment by JasonSowers** [comment]
Which version of the SDK are you using c# or node?

**Comment by Hiranmayee24** [comment]
@JasonSowers : We are using Node JS and how can we check the SDK version.
Currently we are using Skype (personal).

Please suggest

**Comment by austinhuang0131** [comment]
@Hiranmayee24 `npm list` then find `botbuilder` on the output and the version number is after the `@`.

You're probably on 3.11.0

**Comment by nrobert** [comment]
Unfortunately I think there is currently no way to get these items, you only have access to user name and user Id which is a computed value

**Comment by Hiranmayee24** [comment]
Basically i want a unique id of the user which i can use to differentiate user activity

**Comment by JasonSowers** [comment]
Which SDK are you using?  in c# you can get to the user id from `Activity.From.Id` or `Activity.Recipient.Id` or from the context `context.Activity.From.Id` or `context.Activity.Recipient.Id`.  In node it is something very similar, please take a look at the [Activity Schema](https://docs.microsoft.com/en-us/bot-framework/rest-api/bot-framework-rest-connector-api-reference#activity-object) Note there is also a `.name` property which some channel populate with the users name that could be useful to you.

**Comment by austinhuang0131** [comment]
@Hiranmayee24 You can try `session.message.address.user.id` as an unique identifer for each users.
