### ISSUE TITLE
[Question] How to know if user has existing dialogs before calling beginDialogAction()?

### ISSUE THREAD

**Issue by austinhuang0131** [Microsoft/BotBuilder#3661]
## Bot Info 
* SDK Platform: Node.js
* SDK Version: 3.11.0

## Issue Description
How to judge if the user has existing dialog(s) before calling `beginDialogAction`?

So basically I have a search command that asks you for a query. Now, if I put the query that collides with another command, how can I let the bot do the search command instead of the "another command"?

For example,
```
ME: Cat
BOT: <Cat image>
ME: Google
BOT: Input query.
```
I want:
```
ME: Cat
BOT: <Google results>
```
instead of
```
ME: Cat
BOT: <Cat image>
```

## Code Example
http://github.com/austinhuang0131/metagon_plus

**Comment by nwhitmont** [comment]
You can't because `beginDialogAction` aka `triggerAction` are globally defined. You will need to define your bot's `beginDialogAction` RegEx triggers in such a way as to avoid this.  It's up to you to define a naming convention that works for your specific use case.
