### ISSUE TITLE
[Localization] Fail to override default messages from botbuilder.json for other locale?

### ISSUE THREAD

**Issue by DarkInsight85** [Microsoft/BotBuilder#3662]
## Issue Description
I am currently following this [thread](https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-localization#use-namespaces-to-customize-and-localize-prompts) to implement overridding of defaults messages. 

What I intend to do is:
1. set defaultLocale as "en"
2. when user joins, set session's preferredLocale accordingly
3. displays different set of default messages based on session's preferredLocale

Under my locale folder, I have put two folders "en" and "zh". Each of these folders have a BotBuilder.json within. Each json file override the "default_choice" with respective langauge.

I have successfully override the message for locale "en", however I am unable to override the message for locale "zh" although the preferredLocale is successfully set.

## Code Example
```js
        const locale = getUserLocale();
        session.preferredLocale(locale, (err) => {
          if (err) {
            console.log("Error setting locale " + locale + " for user");
          } else {
            console.log("Successfully setting locale " + locale + " for user");
          }
          console.log("Proceed to send welcome messages");
        });
```
getUserLocale is my custom method that returns a locale based on user's settings. I can verify that the value of locale is indeed "zh", as I am seeing "Successfully setting locale zh for user" in my log.

## Reproduction Steps
1. Start a conversation
2. Display a choice prompt to user
3. User types some jibberish instead of clicking on the choices button

## Expected Behavior
1. The overridden messages for locale "zh" is shown

## Actual Results
1. The overridden messages for locale "en" is shown instead

**Comment by DarkInsight85** [comment]
Content of BotBuilder.json for locale "en"

    {
      "default_choice": "(test) I don't understand", 
      "default_error": "(test) Oops. Something went wrong and we need to start over."
    }

Content of BotBuilder.json for locale "zh"

    {
      "default_choice": "(test) 我不明白", 
      "default_error": "(test) 错误，请重启"
    }

**Comment by nwhitmont** [comment]
@DarkInsight85 Can you post your bot code which shows how you are sending the messages to your user?

**Comment by DarkInsight85** [comment]
@nwhitmont Hi, this is my handler that sends the choice prompt. But do take note that I am not trying to override the choice prompt enum, only the error message when user fails to click on any of the choices of the prompt.

    async (session, pairId) => {
      session.privateConversationData.feedbackPairId = pairId;

      const prompt = await automatedResponseHelper.getAutomatedResponseForDirectLineConversationId("csat_start1", session.message.address.conversation.id);
      const csatOptionsStr = await automatedResponseHelper.getAutomatedResponseForDirectLineConversationId("csat_options", session.message.address.conversation.id);
      const csatOptions = csatOptionsStr.split(",");
      builder.Prompts.choice(
        session,
        prompt,
        csatOptions,
        { listStyle: builder.ListStyle.button }
      );
    },

**Comment by DarkInsight85** [comment]
Hi, may I know if anyone is looking at this issue?

**Comment by DarkInsight85** [comment]
@FranciscoPonceGomez @nwhitmont Hi May I know if anyone is looking at this issue?

**Comment by FranciscoPonceGomez** [comment]
Hi @DarkInsight85,

I will look into this today.

Regards,
Francisco

**Comment by fanidamj** [comment]
Closing the issue assuming it as resolved. Please reopen a new issue if it still persists.
