### ISSUE TITLE
[.Net SDK, Cortana] Deployment doesn't work?

### ISSUE THREAD

**Issue by BelvedereHenrique** [Microsoft/BotBuilder#3663]
## Bot Info 
* Bot handle: ActmindsEducauseBot
* App ID: abc985d3-cc5d-43ce-bf58-b267e80b2ee6
* SDK Platform: .NET
* SDK Version: 3.11
* Active Channels: Skype, Facebook Messenger, Cortana
* Deployment Environment: Azure Web App

## Issue Description
Cortana Skills deployment does not work.

## Reproduction Steps
1. Edit deployment group
2. Deploy

## Expected Behavior
Cortana starts to work on other machines with the authorized users.

## Actual Results
It works only for the e-mail address used to create the skill.
Here is what is shown on my dashboard:
![image](https://user-images.githubusercontent.com/24565006/31996406-2c6a2a3a-b967-11e7-99b6-cf2246af3eaa.png)

As you can see, there are two deploymens with the same name. Why?
On the first one, I can't finish the deployment process as you can see on this image:

![image](https://user-images.githubusercontent.com/24565006/31996457-63be772a-b967-11e7-840c-61ca3c8b84a2.png)

On the second one it works as expected on the dashboard. I put the e-mails, press "Deploy", take the link, send to the users, they accept the invite. All as expected.
But, at the end of the process, when they try to test the Skill, Cortana simply doesn't work.
It behaves as if the skill did not exist, ignoring the invocation name.

I'm using these e-mails: "bhb_henrique@hotmail.com;cleitonbarbieri@hotmail.com;****@windowslive.com"

I'm missing something?

Thanks!

**Comment by JasonSowers** [comment]
First thing I would try is to delete your deployments and try again, let us know if that helps.

**Comment by JasonSowers** [comment]
@BelvedereHenrique did you ever get this working?

**Comment by BelvedereHenrique** [comment]
No. Not yet.
Tried even changing the PC's.
No success.

**Comment by BelvedereHenrique** [comment]
Sorry for the delay.
I tried deleting and re-creating the deployment, no success.

**Comment by fanidamj** [comment]
Can you please let us know if the issue still persists?

**Comment by BelvedereHenrique** [comment]
No
We can close this issue.
With the new Cortana development panel, everything is working as expected.
