### ISSUE TITLE
[Bug] Only 1 customAction can be defined, others are overwritten

### ISSUE THREAD

**Issue by SynerG** [Microsoft/BotBuilder#3664]
## Bot Info
* SDK Platform: Node.js
* SDK Version: 3.11.0

## Issue Description
If more than one `customAction` is defined for a dialog with a custom `onFindAction` definition, only the last one is retained. Others are overwritten. 

## Code Example
```javascript
const childDialog = bot.dialog('child', [
  function (session, args){
    session.send("this is a child");
  }
]);

childDialog
  .customAction({
    onFindAction: (context, cb)=>{
      console.log("Considering customAction 111...", null);
      if (context.message !== undefined && context.message.text === "111"){
        cb(null, 1.1);
      }else{
        cb(null, 0);
      }
    },
    onSelectAction: (session, args) =>{
      session.send("111 processed!");
    }
  });

childDialog
  .customAction({
    onFindAction: (context, cb)=>{
      console.log("Considering customAction 222...", null);
      if (context.message !== undefined && context.message.text === "222"){
        cb(null, 1.1);
      }else{
        cb(null, 0);
      }
    },
    onSelectAction: (session, args) =>{
      session.send("222 processed!");
    }
  });
```

## Reproduction Steps
1. Define more than one `customAction` on the same dialog or bot
2. Interact with the bot and perform each action

## Expected Behavior
All the defined customActions should be available to be triggered.

## Actual Results
Only the last customAction defined can be triggered. Any other customAction defined has disappeared and cannot be triggered.

The bug is in the file `ActionSet.ts`:
```javascript
    private action(name: string, handler: IActionHandler, options: IDialogActionOptions = {}): this {
        var key = this.uniqueActionName(name);
        this.actions[name] = { handler: handler, options: options };
        return this;
    }
```
A unique `key` is generated for each customAction defined, but the action is registered with the original `name`that is not unique. In particular, all customActions that define the `onFindAction`method share the same name. As a result, previous customActions are overwritten.
`key`should be used instead.

I cannot do a PR now, but I wanted to report the bug.

**Comment by nwhitmont** [comment]
@SynerG You are getting this error because` customAction`(s) cannot be added to dialogs. 

Custom actions can only be added to the `bot` object. 

For more information, check out the section _Action Types > customAction_:
https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-dialog-actions#bind-a-customaction

**Bind a customAction**

>Unlike other action types, customAction does not have any default action defined. It's up to you to define what this action does. The benefit of using customAction is that you have the option to process user requests without manipulating the dialog stack. When a customAction is triggered, the onSelectAction option can process the request without pushing new dialogs onto the stack. Once the action is completed, control is passed back to the dialog that is at the top of the stack and the bot can continue.

>You can use a customAction to provide general and quick action requests such as "What is the temperature outside right now?", "What time is it right now in Paris?", "Remind me to buy milk at 5pm today.", etc. These are general actions that the bot can perform with out manipulating the stack.

>Another key difference with customAction is that it binds to the bot as opposed to a dialog.

**Comment by SynerG** [comment]
Sorry, but that is not the reason.
You can attach the `customActions` to the bot instead of the dialog and the same bug still persists.
You can only invoke the last `customAction` defined with a custom `onFindAction` definition. All the previous ones have been overwritten.
Please, try it.

The bug is in the implementation of the `action()` method in `ActionSet.ts`.
 As I pointed out previously, a unique `key` for the customAction is generated, but it is not used later. That is why the previous actions are overwritten.

Please, reopen the issue.

P.S. I know that the docs state that customActions are bound to bots, not dialogs, but both currently work and both share the same bug. And it makes sense to attach customActions to dialogs, not only bots, so it is good to have this feature. Maybe the docs should be updated. But the common bug should be fixed as it happens also when actions are attached to the bot.

**Comment by SynerG** [comment]
I have submitted the PR #3863 to fix this issue.

**Comment by EricDahlvang** [comment]
@SynerG Thanks for your contribution.  Closing this issue, since your PR has been merged.
