### ISSUE TITLE
[Question] How to enable speech input in WebChat control?

### ISSUE THREAD

**Issue by zxy66481** [Microsoft/BotBuilder#3668]
I have been able to do this interface normally, but when the bot links, link does not include voice service is not normal, I filled out the key has a problem, the red circle of things should be filled in what specific, can explain in detail
![31993387-907dd6e6-b9af-11e7-97e2-1d00984109c0](https://user-images.githubusercontent.com/32949019/32030932-cba243f2-ba30-11e7-821c-d17efcb6f21e.PNG)
![31993439-b4d54db2-b9af-11e7-9b38-62667c2521d2](https://user-images.githubusercontent.com/32949019/32030937-cf932dfa-ba30-11e7-8e80-33e1e6d867ca.PNG)

**Comment by DeniseMak** [comment]
@zxy66481 Can you post what error you get when you do F12 debugging in the web browser?

**Comment by zxy66481** [comment]
No error prompts, just now the microphone can be used, just I do not know how to put my deployment to the cloud of robots and custom web Chat controls linked up, hope to get help as soon as possible, thank you

**Comment by DeniseMak** [comment]
@zxy66481 what browser are you using?

**Comment by zxy66481** [comment]
My browser is Google Chrome, my custom web chat control of the voice recognition has been turned on, now is unable to link deployment in the cloud of the robot, please give you help, extremely grateful!

**Comment by DeniseMak** [comment]
@zxy66481 What happens if you do this: 

1. Put the DirectLine secret in the `s` parameter in the URL in the browser?
For example:
https://myexamplebot.com/my-web-chat.html?s=Y4UhItuBISJ.cwA.RlY.fj5FJ8K_9yK6J4LB-dZVqQJaaJAP9DB_jP6ysYn6DIo

2. Then change the code in the script back to this:

```

BotChat.App({
--
  | directLine: {
  | secret: params['s'],
  | token: params['t'],
  | domain: params['domain'],
  | webSocket: params['webSocket'] && params['webSocket'] === "true" // defaults to true
  | },
  | user: user,
  | bot: bot,
  | locale: params['locale'],
  | resize: 'detect',
  | speechOptions: speechOptions,
  | // sendTyping: true,    // defaults to false. set to true to send 'typing' activities to bot (and other users) when user is typing
  | }


```

**Comment by DeniseMak** [comment]
@zxy66481 What kind of error are you getting that indicates that you can't link to the cloud deployment of your bot?  Also, if you have your microphone working now, can you explain how you got it working?

**Comment by ZXYNYP** [comment]
My web page is jump by pressing the button, can't set to add keys, my microphone is click can identify the content of the talk, identification can be sent, mistake is to send the news has been unable to send，thank you

**Comment by zxy66481** [comment]
My web page is jump by pressing the button, can't set to add keys, my microphone is click can identify the content of the talk, identification can be sent, mistake is to send the news has been unable to send

**Comment by zxy66481** [comment]
I have changed what you said, but the browser prompts for domain name resolution errors, can you give me an example of where the URL in addition to the password need to be replaced, and the script in addition to the key to add what

**Comment by DeniseMak** [comment]
What happens you run it locally? For example:
https://localhost:8080/index.html?s=Y4UhItuBISJ.cwA.RlY.fj5FJ8K_9yK6J4LB-dZVqQJaaJAP9DB_jP6ysYn6DIo

**Comment by fanidamj** [comment]
Closing the issue assuming it as resolved. Feel free to reopen if you any questions or comments.

**Comment by dayachoudekar8** [comment]
Hi, here was same problem. big issue is that.. i got an error in generating token. 

https://directline.botframework.com/v3/directline/conversations
{ "message": "The requested resource does not support http method 'GET'." }

**Comment by EricDahlvang** [comment]
Webchat does not currently support Cognitive Speech keys, but only with Bing Speech keys. Work is in progress to support both.  

Please direct your issue to the WebChat repository: https://github.com/Microsoft/BotFramework-WebChat
