### ISSUE TITLE
[QnA Maker] Add API feature to share KB services

### ISSUE THREAD

**Issue by DL-LiveTiles** [Microsoft/BotBuilder#3670]
The QnA Maker API is great, but we also need to functionality to share a KB service programmatically using the API.
The feature to share KB services is available in the QnA Maker portal, but not available thru the API.

**Comment by stevengum97** [comment]
Thank you for the feedback! For feature requests for our Cognitive Services we recommend visiting [UserVoice][CogServ-UserVoice] ([QnA Maker][Q-UserVoice]) and posting your requests there. This route is more direct, allows for more users to share their opinion on features and is our preferred route for these requests. 

Please limit your feature requests in the BotBuilder repository to being specifically for the BotBuilder SDK, Azure Bot Service and for supported (or not supported) Channels. 

  [CogServ-UserVoice]: https://cognitive.uservoice.com/
  [Q-UserVoice]: https://cognitive.uservoice.com/forums/578689-qna-maker
