### ISSUE TITLE
[Question] How to deploy bot? Getting error: "internal server error"

### ISSUE THREAD

**Issue by zxy66481** [Microsoft/BotBuilder#3672]
I have no change in the code, I just built a new robot, I updated the new bot ID in the Web.config file, the password, the deployment also shows success, is unable to run properly, reported an error: "There is an error sending it message to Your bot: HTTP status Code internal server error"

**Comment by FranciscoPonceGomez** [comment]
Hi @zxy66481,

Are your using .NET SDK or Node.js SDK?
What template/sample have you used to create your bot?
You also need to update the endpoint of you bot. I assume you are deploying to Azure from Visual Studio, in that case, the address where you are deploying the bot has to appeared in the "endpoint" section in your bot configuration on the web portal followed by /api/messages.

Regards,
Francisco

**Comment by JasonSowers** [comment]
Closing due to lack of response
