### ISSUE TITLE
[Node.js SDK, Direct Line] How to handle ECONNRESET when using websocket connection?

### ISSUE THREAD

**Issue by Kannaj** [Microsoft/BotBuilder#3676]
## Bot Info
* App ID:  745ff47b-893c-4438-a83d-699bd57b86ec
* SDK Platform: Node.js
* Active Channels: Directline
* Deployment Environment: Azure/Ngrok

## Issue Description
frequent ECONNRESET errors during websocket connection to streamURL received from POSTing to directline API

## Code Sample
```javascript
var client = new WebSocketClient();

        client.on('connectFailed', function(err) {
            //initial connection successfull
        });

        client.on('connect', function(connection) {
                          //initial connection successfull

            connection.on('error', function(err) {
               // ECONNRESET happens here
            });

            connection.on('close', function() {
               // AFTER 'error' event
            });

            connection.on('message', function(message) {   
               // occassionally message passes through
            });
        });

        client.connect(streamUrl);
```

Are there any specific reasons as to why the `streamURL` connection closes/resets? this has been happening for quite a bit lately. I'm unsure if there is some error on our side - any ideas as to where the source of error could be found would be helpful

**Comment by thiagodosreis** [comment]
Hello Kannaj,

Were you able to figure out how to handle this situation? I'm having the exact same problem here.
It looks like Microsoft is forcing the WSS to close from time to time. So, all my 3 applications are having all websockets connections closing at the same time.

Microsoft Direct Line error: read ECONNRESET

Thank you,
Thiago

**Comment by EricDahlvang** [comment]
@thiagodosreis Please check out how the DirectLineJs library handles websocket connection failures: https://github.com/Microsoft/BotFramework-DirectLineJS/blob/master/src/directLine.ts#L626

The recommendation is to re-connect using a cached watermark.
