### ISSUE TITLE
[Direct Line] Latency & performance issues?

### ISSUE THREAD

**Issue by nicksav** [Microsoft/BotBuilder#3677]
Guys, do you think its acceptable? 11 secs for DirectLine call?
![image](https://user-images.githubusercontent.com/9266365/32081848-143ca3da-bafb-11e7-9b05-d1b68bf1adb7.png)

**Comment by nwhitmont** [comment]
@nicksav Hi Nick, can you provide additional context about your bot scenario?

For example:
- Are you developing with BotBuilder .NET or Node.js SDK?
- Where is your bot deployed? Eg. local development, ngrok, Azure, AWS, etc.
- In what geographic region is your bot deployed? Sometimes different data centers have different response times.
- Does the Direct Line latency happen with all requests, or what % of requests are affected
- What is your bot's App ID as registered in the Bot Portal at https://dev.botframework.com?

**Comment by EricDahlvang** [comment]
Hi @nicksav 

It looks like you're using the default state service.  This is intended for prototyping only, and should not be used with production bots.  Please check out this blog post on using the Azure Extensions for state:  https://blog.botframework.com/2017/07/18/saving-state-azure-extensions/

**Comment by nicksav** [comment]
Guys, 
I have deployed to Azure Web app WEST US 2 (I understand to be close to DirectLine api)
It happens randomly. Sometimes take less than a second, sometimes 20 secs. 
Developing with .Net version

@EricDahlvang I will check now. Thanks for advice.

**Comment by FranciscoPonceGomez** [comment]
Hi @nicksav, 
Where did you get this chart from?

**Comment by nicksav** [comment]
Hi @FranciscoPonceGomez  Its Azure Application Insights

**Comment by nicksav** [comment]
Looks like I am going to give up on Bot Framework for now. 
Already replaced bot state with custom SQL db.
![image](https://user-images.githubusercontent.com/9266365/32149788-c5137916-bd55-11e7-9599-2d5cec5dcb1d.png)

**Comment by FranciscoPonceGomez** [comment]
Hi @nicksav,

The new SDK version will reduce the number of calls to retrieve the token. 

Thanks for your feedback.
Francisco

**Comment by nicksav** [comment]
Hi @FranciscoPonceGomez  Any ETA when new sdk will be released.
btw, I have fond the issue guys and it was related to my bad coding. 

In the Root dialogue I was using context.Done() and somehow it was making an infinite loop. 
The more conversation I start, the worse the performance gets until it gets fully unresponsive. 

Fixing the code, fixed the performance issue.
Thanks
Nick
