### ISSUE TITLE
[WebChat] Getting error on bot when using embedded webchat iframe.

### ISSUE THREAD

**Issue by Pratima1490** [Microsoft/BotBuilder#3678]
## Bot Info 
* App ID: 73e6deac-0225-4188-958f-01846d6c0aa6 
* SDK Platform: .Net
* SDK Version: Visual Studio 2015
* Active Channels: Web Chat
* Deployment Environment: IIS

## Issue Description
I have downloaded Bot template and added Bot Id,Microsoft App Id,Password in web.config.Published the code in IIS on windows server 2012.Its is working in bot emulator with ngrok.
But when i try to embed the code within iframe using secret,its throwing error couldn't send retry.
Even its not working in test mode of  https://dev.botframework.com in mybots.
Please help.Tried all the possibilities given in troubleshoot but no luck.

## Code Example
<iframe src='https://webchat.botframework.com/embed/BFSFAQTestBot?t=WEBCHAT SECRET'></iframe>

## Reproduction Steps
1.
2.
3.

## Expected Behavior
ChatBot should work.

## Actual Results

![error_chatbot](https://user-images.githubusercontent.com/32730541/32093267-544f7d94-bb19-11e7-82f5-357030fdcb82.png)

**Comment by JasonSowers** [comment]
Do you have a valid certificate?
  
The Bot Framework requires that the x.509v3 certificate exposed by your endpoint be current and valid. Most of the checks for "current and valid" are standard checks for server SSL certificates: the Certificate Name must match the hostname, it must not be expired, it must not be listed in a CRL, it must have the correct set of EKUs, etc.
Most importantly, your SSL certificate must chain to a root certificate authority trusted by Microsoft. The latest list of these CAs is available here: http://social.technet.microsoft.com/wiki/contents/articles/31634.microsoft-trusted-root-certificate-program-participants-v-2016-april.aspx
For more information on deploying your bot, see: https://docs.microsoft.com/en-us/bot-framework/deploy-bot-overview
Relates to:
•	https://stackoverflow.com/questions/40888489/bot-framework-without-azure-possible
•	https://stackoverflow.com/questions/44558760/deploy-bot-in-local-iis-and-incle-it-in-custom-chat-in-a-webpage/44571251#44571251

**Comment by FranciscoPonceGomez** [comment]
hi @Pratima1490, as @JasonSowers  mentioned the Bot Framework works with bots deployed on any cloud hosting service, as long as you have an internet-accessible endpoint and a valid HTTPS cert.

Please, review that your end point is internet-accesible in the configuration page.

**Comment by JasonSowers** [comment]
@Pratima1490 please let us know if this did not resolve your issue
