### ISSUE TITLE
[Question] How to send questions to user with session.send()?

### ISSUE THREAD

**Issue by SilvaLA59** [Microsoft/BotBuilder#3680]
## Bot Info 
* SDK Platform: Node.js 
* Active Channels: Direct Line, Facebook Messenger, Skype

## Issue Description
Guys, My bot needs to ask for example the user's name, I'm using builder.Prompts.text() but would like to know if can I do this with session.send()...I tried to use suggestedActions, but I don't have suggestions in this case when I need to ask user name. I need something like the following code:

## Code Example
```
function(session, args, next){
 var msg = new builder.Message(session)
  .**<something>**;
 session.send(msg);
},
function(session, results, next){
 session.conversationData.userName = results.response;
}
```

**Comment by nwhitmont** [comment]
@SilvaLA59 Prompts are the correct way to achieve this.
