### ISSUE TITLE
[Question] Bot stopped working on Skype only? All other channels work fine.

### ISSUE THREAD

**Issue by khushboo22singh** [Microsoft/BotBuilder#3684]
## Bot Info 
* App ID: e69c4c45-427c-4eb1-b329-7551b3535554
* SDK Platform: .NET
* Active Channels: Skype, Webchat
* Deployment Environment: ngrok, Azure App Service

## Issue Description
Bot stopped working on skype. Working fine on webchat, but not on skype.

## Expected Behavior
bot should reply on skype

## Actual Results
bot not replying on skype, bot working perfectly fine on webchat.

![boterror](https://user-images.githubusercontent.com/33002605/32143410-c6f022ac-bcce-11e7-9923-112517203f1c.PNG)

**Comment by JasonSowers** [comment]
Try debugging locally using [ngrok](https://ngrok.com/download).  You can change your endpoint in the [dev portal](https://dev.botframework.com) to the one that ngrok generates when you use this command `ngrok http 3979 -host-header="localhost:3979"` change to the port your bot runs on. 
  
More info:
[Blog Post](https://www.robinosborne.co.uk/2016/09/19/debugging-botframework-locally-using-ngrok/)

**Comment by nwhitmont** [comment]
Hi @khushboo22singh - You need to "publish" your bot to the Skype channel for it to work correctly on Skype. 

To publish your bot to Skype channel:
1. Sign-in to the Bot Developer Portal at https://dev.botframework.com
2. go to the Channels page for your bot
3. on the Skype channel, click "Edit"
4. click on the "Publish" tab 
5. fill out all the required information, including Category (required)
6. at the bottom of the page click "Submit for Review"

Let me know if you have any other questions.

**Comment by kaisunc** [comment]
i can't even see the configure skype page. 

![image](https://user-images.githubusercontent.com/8186855/32266780-a7649a38-bf23-11e7-9e27-65a6a930ecd1.png)

**Comment by usheveta** [comment]
Even I'm getting the same issue. The Skype bot configurations are not getting edited and the speed of bot is very slow and the page on which the Skype bot its added,is getting hanged.

**Comment by liam-sage** [comment]
Same issue here - I am running it locally with ngrok. I am having this issue with Skype only.

**Comment by lucasoliveira01** [comment]
Same issue here. I cant access Skype Bot configuration on Azure.

**Comment by vijaysaimutyala** [comment]
@nwhitmont Same issue here. Unable to access the Skype channel configuration page. Web and Skype for Business configuration works well.

**Comment by khushboo22singh** [comment]
this issues was not resolved. But i created whole new Bot application ans somehow its working fine both on webchat and skype as well.
