### ISSUE TITLE
Creating a function which returns an array of ThumbnailCards

### ISSUE THREAD

**Issue by KwstasBol** [Microsoft/BotBuilder#3686]
* SDK Platform: Node.js 

## Issue Description
I am using foursquare-venues and i want to make 5 different cards with each one being a different Thumbnail Card, having their own image and button. However, all i achieved was only one card with the last venue i got.

## Code Example

```javascript
function createMultipleButtons(session,places){
    var builderas=new builder.ThumbnailCard(session);
    var card=[];
    for(var i=0;i<5;i++){
     builderas
    .buttons([ builder.CardAction.postBack(session,places[i].name,places[i].name)])
    .images([builder.CardImage.create(session,places[i])])
    card.push(builderas);
    }
    return card; /

}
//Invoking the function
 var msg=new builder.Message(session);
            msg.attachmentLayout(builder.AttachmentLayout.carousel);
            msg.attachments([
               createMultipleButtons(session,places)
            ]); 
            builder.Prompts.text(session,msg);
            });
```
## Expected Behavior

Like this one but with the places found from using Foursquare Api ( places)
![image](https://user-images.githubusercontent.com/14348315/32150418-20e2c354-bd1b-11e7-9d0b-db4a6090c104.png)

## Actual Results

![image](https://user-images.githubusercontent.com/14348315/32150411-0bca734a-bd1b-11e7-8fa2-0e91c43c2229.png)

**Comment by sphanley** [comment]
You're only declaring `var builderas=new builder.ThumbnailCard(session);` once, outside of your loop, so in each loop iteration, you're just modifying the reference to the same original card. You need to instantiate a new card inside each iteration, then you'll see the expected result.
