### ISSUE TITLE
[Direct Line] Bad Request Error?

### ISSUE THREAD

**Issue by 10p30pl3** [Microsoft/BotBuilder#3688]
## Bot Info 
* App ID: ee650974-07e9-4fd5-9bf7-049fe02918e1
* SDK Platform: Node.js 
* Active Channels: Direct Line

## Issue Description
My bot is getting error :

Error: Request to 'https://state.botframework.com/v3/botstate/directline/users/dlxxx1' failed: [400] Bad Request

Any problem on Directline interface?

## Reproduction Steps
1.Connect to bot saying hello
2.No response back from directline
3.error 400

## Expected Behavior
Bot normal conversation 

## Actual Results
No responses from bot

**Comment by 10p30pl3** [comment]
Problem was solved by resetting session.userdata. Any idea about relationship of session.userdata and directline?

**Comment by nwhitmont** [comment]
@10p30pl3 thanks for the update. I'm happy to hear your issue was resolved by resetting `session.userData'.
