### ISSUE TITLE
[Skype] Unable to save Skype bot configuration?

### ISSUE THREAD

**Issue by VitalyGorelov** [Microsoft/BotBuilder#3689]
Try to enable "Enable adding to a group" feature in Skype bot confuguration. And I got error "Unable to save", if I enable feature and click Save.  http://clip2net.com/s/3P1SACY
![232b0-clip-59kb](https://user-images.githubusercontent.com/3075047/32189514-2a7a6c94-bd68-11e7-94eb-d09cf938b39d.png)

What can be reason?

**Comment by VitalyGorelov** [comment]
Обратил внимание, что в скриптах возникает ряд ошибок http://clip2net.com/s/3P1TvsM

**Comment by EricDahlvang** [comment]
There is currently a bug in the Skype config page that requires a Category to be selected even if you aren’t publishing. Go to the Publish tab, select a category, and then save again.

Sorry for the inconvenience.  This will be fixed soon.

**Comment by nwhitmont** [comment]
В настоящее время на странице конфигурации Skype есть ошибка, требующая выбора категории, даже если вы не публикуете. Перейдите на вкладку «Опубликовать», выберите категорию и сохраните снова.

Приносим извинения за неудобства. Это будет исправлено в ближайшее время!

**Comment by EricDahlvang** [comment]
This underlying problem has been fixed.  Please open a new issue if you need further assistance.
