### ISSUE TITLE
FormOptions.PromptFieldsWithValues skip fields

### ISSUE THREAD

**Issue by rlilov** [Microsoft/BotBuilder#369]
I am using FormOptions.PromptFieldsWithValues

when during the chat I go back few fields (using back command) to correct some entry and I either provide new value or type 'c' , flow than skips fields with values and jumps to the first field for which there is no value. I think this is not consistent with PromptFieldsWithValues (or at least expected from me ) behavior

**Comment by chrimc62** [comment]
This is by design.  PromptFieldsWithValues is only about how the initial state passed in is treated.  Once someone has entered or confirmed a value we treat that as done--they can always navigate to the field if they really want to change it.
