### ISSUE TITLE
[Feature Request] PowerBI Integration

### ISSUE THREAD

**Issue by nwhitmont** [Microsoft/BotBuilder#3691]
**User Story**
As a bot developer, I would like to have the ability to integrate my bot(s) with PowerBI.

Relates to:
- https://community.powerbi.com/t5/Desktop/How-we-can-integrate-Chatbot-with-PowerBI/m-p/221752
- https://ideas.powerbi.com/forums/265200-power-bi-ideas/suggestions/19737688-power-bi-embedded-should-be-available-for-microsof
- https://ideas.powerbi.com/forums/265200-power-bi-ideas/suggestions/20347345-to-integrate-chat-bot-with-powerbi
- https://ideas.powerbi.com/forums/265200-power-bi-ideas/suggestions/19211770-integrate-q-a-with-microsoft-bot-framework

**Comment by sgellock** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
