### ISSUE TITLE
[Question] How Bot can initiate a conversation  to a user?

### ISSUE THREAD

**Issue by midhunCherrylabs** [Microsoft/BotBuilder#3693]
## Issue Description

Currently i am collecting some data for managing order for user through chat-bot ,now we required to update order status to that particular user after some time ,like BOT sending a message to that User  ,how can i solve this scenario using chat-bot builder.

**Comment by gudwin** [comment]
You can find it in official documentation - https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-proactive-messages

**Comment by nwhitmont** [comment]
@midhunCherrylabs You will find a great guide on this topic in the documentation link posted by @gudwin 

There is also a code example here:
https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node/core-proactiveMessages

**Comment by midhunCherrylabs** [comment]
@nwhitmont @gudwin  thank u , its really helpfull
