### ISSUE TITLE
Adaptive Cards on C#

### ISSUE THREAD

**Issue by zxy66481** [Microsoft/BotBuilder#3698]
Adaptive Cards with C # How to build, Adaptive Cards created button directline can be used?

                                                                                                     Thank   you so  much

**Comment by FranciscoPonceGomez** [comment]
Hi @zxy66481,

I would start taking a look at the sample in our repo:
https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/cards-AdaptiveCards

It contains a step by step tutorial in the readme file.

Regards,
Francisco
