### ISSUE TITLE
Suggestion: Web Chat component initial message

### ISSUE THREAD

**Issue by villasv** [Microsoft/BotBuilder#37]
It would be nice if the initial message from the bot web chat component was the response to "BotAddedToConversation" instead of the default "Hi! I'm {name}. Say "hi" if you'd like to chat"".

This adds to general personalization, but is also necessary for i18n (for I intend to use the bot to chat in Portuguese). I'm not sure this issue belongs to the BotBuilder SDK (Bot Connector instead?), but that's the only issue-tracking I could find.

**Comment by Stevenic** [comment]
Thank you for the suggestion. Sorry for the slow reply. We'll add it to the wish list :)

**Comment by taylorgibb** [comment]
Just seconding this feature.

**Comment by Stevenic** [comment]
Moved to UserVoice:

https://feedback.botframework.com/forums/354219-bot-connector/suggestions/13463595-suggestion-web-chat-component-initial-message

**Comment by villasv** [comment]
has this feature been included? I couldn't find it glancing over the docs.

**Comment by dandriscoll** [comment]
Hi @villasv, we have a new web chat control coming with a fix for this issue. Thanks
--Dan

**Comment by lgmorand** [comment]
I still have the issue. how can we customize the welcome message of a chatbot ?

**Comment by dandriscoll** [comment]
Hi @lgmorand, make sure you select the "Enable preview" option on the Web Chat configuration page.

**Comment by lgmorand** [comment]
@dandriscoll, thanks. so simple. still, I have now graphic issues with my template so I guess some stuff changed on the control (looks like background is now transparent), but that's ok for me. Thanks again :)

**Comment by martabrzeszczyk** [comment]
Similar issue about userName translation. Currently it seems to be hardcoded to "You".
` var model = {
 ...
  "userName": "You",
...
};
`
Would it be possible to translate it?
