### ISSUE TITLE
Show links as images on facebook

### ISSUE THREAD

**Issue by fercom** [Microsoft/BotBuilder#370]
Hi, my bot is connected to facebook messenger and it works, I just want to format the answers in a way that instead of links to images it shows images. (In the web it shows images indeed). Anyone knows how to do that?
The link to the web is: [http://memegeneratorbot.azurewebsites.net/](url)
The link to the facebook page, is [https://www.facebook.com/MemeBot-1118345044889141/](url) click on send message to chat with the bot

**Comment by fercom** [comment]
Solved it, you need to add Attachments to the message.

**Comment by avinb** [comment]
Great. I just used your bot .. Nice idea and implementation. you planning of giving it  a WhatsApp integration too ?

**Comment by fercom** [comment]
Yes but honestly I don't currently know how

**Comment by Stevenic** [comment]
Nice bot :)

**Comment by fercom** [comment]
Thanks @Stevenic , I just Added it to skype, if you want to try it https://join.skype.com/bot/c0b2fa87-3625-43b2-be12-8eb1675818bb
