### ISSUE TITLE
[MS Teams] Bot is side-loaded but unavailable?

### ISSUE THREAD

**Issue by maros-klimovsky** [Microsoft/BotBuilder#3700]
## Bot Info 
* App ID: 4723b22b-fde7-4a4f-954d-7d26295087fd
* SDK Platform: .NET
* SDK Version: 3.11.0
* Active Channels: MS Teams
* Deployment Environment: Azure App Service

## Issue Description
I had working bot side-loaded in MS Teams. Today, I removed it and tried to re-add it with different name.
Now I am unable to use the bot. Side-loading ends without errors but I cannot find my bot by searching for it in chat/mentioning it. 

I also tired to re-add it using original manifest with original name. I can still see chat with the bot from previous side-loading and I can also search for it under old name. It also doesn't respond.

Side-loaded bot IS visible in Apps section.
Bot DOES respond when I try it using webchat on dev.botframework.com.

## Code Example
I redacted personal information. It was not changed between side-loadings so it really shouldn't matter.
> {
  "$schema": "https://statics.teams.microsoft.com/sdk/v1.0/manifest/MicrosoftTeams.schema.json",
  "manifestVersion": "1.0",
  "version": "1.0.0",
  "id": "4723b22b-fde7-4a4f-954d-7d26295087fd",
  "packageName": "<REDACTED>",
  "developer": {
    "name": "<REDACTED>",
    "websiteUrl": "<REDACTED>",
    "privacyUrl": "<REDACTED>",
    "termsOfUseUrl": "<REDACTED>"
  },
  "name": {
    "short": "TestBot"
  },
  "description": {
    "short": "This is a sample bot manifest",
    "full": "This is a sample bot manifest that has the bare minimum you need for a bot, which will work in Teams and Personal scopes."
  },
  "icons": {
    "outline": "contoso20x20.png",
    "color": "contoso96x96.png"
  },
  "accentColor": "#60A18E",
  "bots": [
    {
      "botId": "4723b22b-fde7-4a4f-954d-7d26295087fd",
      "scopes": [
        "team",
        "personal"
      ]
    }
  ],
  "permissions": [
    "identity",
    "messageTeamMembers"
  ]
}

## Reproduction Steps
1. Side-load bot.
2. Try to find it.
3. No results.

## Expected Behavior
Bot name comes app and you can use it.

## Actual Results
Bot is unavailable.

**Comment by FranciscoPonceGomez** [comment]
Hi @maros-klimovsky ,

Did you change the name in the manifest, in the dev portal, or both?

**Comment by maros-klimovsky** [comment]
Hi,
I initially only changed it in the manifest. When it failed I tried changing it in the dev portal and I changed botId in web.config.

Then I actually redeployed the whole thing with new dev portal registration and new Azure deployment.

Currently it is in a state as it was originally (including App ID and bot name).

Some more info as I saw people suggesting these things:
Yes, it does work with emulator.
Yes, my MS Teams client runs in development mode.
No requests are going to my Azure application. I'm logging everything and there are no conversationUpdates since I re-deployed. Other channels (webchat, emulator) are sending events as expected.

**Comment by nwhitmont** [comment]
@maros-klimovsky MS Teams has more configuration steps than most channels, did you cover all the steps?


## How to load your bot into MS Teams
**Quick MS Teams bot deployment checklist:**
- Did your O365 tenant administrator [enable sideloading](https://msdn.microsoft.com/en-us/microsoft-teams/setup) of apps for your organization?
- Did you [create an app package](https://msdn.microsoft.com/en-us/microsoft-teams/createpackage)
- Did you [sideload your bot app](https://msdn.microsoft.com/en-us/microsoft-teams/sideload) into the relevant team?

**Recommended reading:**
   - [Getting Started with Bots for Microsoft Teams](https://msdn.microsoft.com/en-us/microsoft-teams/bots)
   - [Create the package for your Microsoft Teams app](https://msdn.microsoft.com/en-us/microsoft-teams/createpackage) - aka manifest.json file
   - [Sideloading your app in a team](https://msdn.microsoft.com/en-us/microsoft-teams/sideload)
   - [Testing your Bot](https://msdn.microsoft.com/en-us/microsoft-teams/botsadd)
   - [Interact one-on-one (1:1) with a Microsoft Teams bot](https://msdn.microsoft.com/en-us/microsoft-teams/bots1on1)

**Comment by maros-klimovsky** [comment]
I did all steps.

Today, my bot started to respond in existing conversation window (1:1 chat created a week ago).
I'm, however, still unable to redeploy the bot with different name. The main issue is the bot cannot be found in Teams after sideloading.

Also no conversationUpdate messages are received by bot.

**Comment by maros-klimovsky** [comment]
Aaand the bot is ignoring me again. 

Right now I have current situation:

TestBot deployed on Azure with App ID 4723b22b-fde7-4a4f-954d-7d26295087fd
sideloaded to Teams, doesn't work (It stopped recently :( )

DynamicsBot deployed also on Azure (as a different app but with the same code) with App ID 249ef058-8d9c-4156-b568-02fcedf11cd6, sideloaded to the same team and I cannot even find it.

Is the fact that they have the same code a problem? I mean they are deployed separately and I don't see how it could be a problem but what do I know..

Both bots are working normally in webchat. Also an idea. I actually tried to change icons for the first time when it stopped working. Could that be related?

**Comment by maros-klimovsky** [comment]
It works now. I can see all bots and they all respond. I have no idea what changed, but it makes me happy anyway.

Keep up the good work.

**Comment by JasonSowers** [comment]
Glad you got it working, happy bot building
