### ISSUE TITLE
[Question] Proactive message stack cancellation?

### ISSUE THREAD

**Issue by ladeak** [Microsoft/BotBuilder#3703]
* SDK Version: .NET 3.11.0
* Deployment Environment: local dev environment

## Issue Description
Sending dialog based proactive message as detailed:
https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-proactive-messages

(side note: github example uses IDialogTask compared to IDialogStack: https://github.com/Microsoft/BotBuilder-Samples/blob/master/CSharp/core-proactiveMessages/startNewDialogWithPrompt/ConversationStarter.cs )

The proactive message posts a prompt to the user.

When timer hits in again (say 2 minutes later) to send a different proactive message, I would like to 'cancel' out the previous prompt, so if user answers this current prompt we don't return to previous proactive message's stack frames, but to the frame before that.
I am trying to call Done of the stack also trying to call Reset() just before I create the new proactive message, but neither seems to work. They clear out the stack, 

## Code Example
```cs
if(dialogTask.Frames.Any(x => (x.Target as ProactiveDialog) != null)) //check if I had proactive message
{
  dialogTask.Done(EndOfConversationCodes.BotTimedOut);
  //dialogTask.Reset();
}
dialogTask.Call(dialog.Void<object, IMessageActivity>(), null);
```

## Actual Results
In case of dialogTask.Done(EndOfConversationCodes.BotTimedOut); I get an exception for 'wait needed instead of poll'
In case of dialogTask.Reset() I get 'Stack is empty' exception for the message I send right after the answer for the proactive message.

## Expected Results
I have a LuisDialog at the bottom, which I would expect to handle the next message. It only handles the 2nd message correctly.

**Comment by JasonSowers** [comment]
Could you please post your full code so we can better assist you

**Comment by JasonSowers** [comment]
This answer may help you also https://stackoverflow.com/questions/46983438/microsoft-bot-framework-clear-conversation-state/46984144#46984144

**Comment by ladeak** [comment]
Thank you for the quick response.

This is the ProactiveDialog I have (note the prompt) which I would like to 'cancel' out and create a new proactive message instead:

public async override Task StartAsync(IDialogContext context)
{   
      await context.SayAsync($"Hi there! Usually you are t....");
      PromptDialog.Confirm(context, ConfirmScheduleResult, "Can I help you ...?", attempts: 0);
 }

Let me test out the suggested solution and come back here in a few days.

**Comment by JasonSowers** [comment]
Which documentation are you talking about specifically, could you please link it so we can look at updating it.  Glad you got this working, good luck!

**Comment by ladeak** [comment]
I was mainly looking for related info in this:
https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-dialogs (under dialogStack section)
or
https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-manage-conversation-flow
