### ISSUE TITLE
[Question] Bot Framework to On Premise Web API connectivity?

### ISSUE THREAD

**Issue by srini1978** [Microsoft/BotBuilder#3704]
## Issue Description
We have a requirement to deploy the Bot Web API on premise. In this scenario I have the following queries. As I understand from literature, this is possible using the following guidances
1.	We can deploy Bot web API on an on-premise environment . However it has to be an internet facing end point or through a proxy.
2.	The API is just a Web App that can be hosted wherever we want- provided, it has access to the Connector and on the other hand, the Channels that we need for the solution have access to that end point. 
3.	We need to open the 443 port inbound and would probably need to buy a domain name.
4.	We understand that the other components of the solution – Azure search, LUIS,Bing translator API etc. cannot be deployed on premise. 

Questions that I have :
1.	Would Microsoft bot framework updates (since it is preview) continue to be supported even if the services it connects to are on premise.
2. Am assuming that bot connector service would connect to the on premise end point through HTTPS. Am I right ?	
3. I believe the Bot connector service wouldn’t be decrypting or storing any of that data in the data transit from bot->On premise . 
3.	Do we have any general guidance on deploying a bot solution on premise.  Architecture guidance
4.	Would the customer get patches of the bot services even if the Web APIs are on premise

**Comment by JasonSowers** [comment]
5. & 9. Yes, you would just need to update the NuGet packages as with any other application.
6.  Yes, you are correct, HTTPS endpoints are required.
7.  This depends on how you set up your state store.

•	https://blog.botframework.com/2017/07/18/Saving-State-Azure-Extensions/
•	https://github.com/Microsoft/BotBuilder-Azure
  
From the documentation article Manage state data:
By default, the Bot Framework SDK for .NET stores state data using the Bot Framework State service, which is intended for prototyping only and is not designed for use by bots in a production environment. For performance and security reasons in the production environment, you should either use the Bot Builder SDK Azure Extensions to store state data in your own Azure Table storage or Azure DocumentDB store or create a custom implementation of IBotDataStore to store state data in the destination that you specify.
To create your own Bot State Service, use the [BotBuilder-Azure extensions](https://github.com/Microsoft/BotBuilder-Azure) library provided on GitHub.
The repository also contains sample implementations for both Azure Table Storage and DocumentDB integrations. (Note: DocumentDB implementation also supports CosmosDB, Microsoft's next-generation version of DocumentDB)
    
8.  The bot will have the same architecture as any bot only it will be on premise.  no special instructions other that make sure you have a valid certificate on your server.
  
The Bot Framework works with bots deployed on any cloud hosting service (or on premise), as long as you have an internet-accessible endpoint and a valid SSL certificate.
The Bot Framework requires that the x.509v3 certificate exposed by your endpoint be current and valid. Most of the checks for "current and valid" are standard checks for server SSL certificates: the Certificate Name must match the hostname, it must not be expired, it must not be listed in a CRL, it must have the correct set of EKUs, etc.
Most importantly, your SSL certificate must chain to a root certificate authority trusted by Microsoft. The latest list of these CAs is available here: http://social.technet.microsoft.com/wiki/contents/articles/31634.microsoft-trusted-root-certificate-program-participants-v-2016-april.aspx
For more information on deploying your bot, see: https://docs.microsoft.com/en-us/bot-framework/deploy-bot-overview

**Comment by JasonSowers** [comment]
relates to:
https://stackoverflow.com/questions/40888489/bot-framework-without-azure-possible 
https://github.com/Microsoft/BotBuilder/issues/1750 
https://stackoverflow.com/questions/41962827/can-i-host-a-ms-bot-framework-node-js-instance-on-premises

**Comment by srini1978** [comment]
Thanks for the detailed response. One more question. 

If we use the on premise Bot web API , I believe all requests from the bot would first go to Bot connector service and then to Bot framework and then all requests will direct to the Bot Web API. In this chain of message and service routing,  do any of these intermediary services decrypt the data in transit.

**Comment by JasonSowers** [comment]
What exactly do you mean by "data".  There is a databag in the `Context` object that keeps the data encrypted, `PrivateConversationData`

**Comment by srini1978** [comment]
By data, I mean the data entered in bot ui. For our scenario, customers enter SSN, passport numbers etc and they are worried that this data is being decrypted in transit.  I believe bot framework  or any other BCS services does not do this decryption

**Comment by napoleonjones** [comment]
Looking for an answer to the data decryption question.  Any updates?

**Comment by JasonSowers** [comment]
@napoleonjones  none of our services decrypt the data while in transport.

**Comment by harrietdodd** [comment]
how does azure bot authenticate with on Premise AD?
