### ISSUE TITLE
[Skype] Error : "There was a problem synchronizing your bot to Skype."?

### ISSUE THREAD

**Issue by johniw** [Microsoft/BotBuilder#3706]
## Bot Info 
* App ID:  7ce4ecc3-8d2a-482a-b25a-fbd7bcdfc43e
* SDK Platform: REST 
* SDK Version: v3
* Active Channels: Web Chat, Skype
* Deployment Environment: Other 

## Issue Description
Skype channel does not work. I get this error in the logs - 'There was a problem synchronizing your bot to Skype.'. 

Also, I cannot open the embed code link for Skype. When I try to go to this link : https://join.skype.com/bot/7ce4ecc3-8d2a-482a-b25a-fbd7bcdfc43e it just takes awhile and gives me an error (https://join.skype.com/error)

The Web Chat channel works as expected and is responding.

## Reproduction Steps
1. Skype channel is added in https://dev.botframework.com/bots
2. Click on 'Health' 
3. Shows the warning

## Expected Behavior
Skype channel should be added correctly and bot should respond. 

## Actual Results
Skype channel Health shows 'There was a problem synchronizing your bot to Skype.' error

**Comment by xjose97x** [comment]
I've had the same issue this past 2 weeks. Some times it seems to work, though.

**Comment by EricDahlvang** [comment]
This has been fixed. Sorry for the inconvenience and thank you for posting the issue.
