### ISSUE TITLE
[Question] How to design "onmidirectional" chatbots?

### ISSUE THREAD

**Issue by sfratini** [Microsoft/BotBuilder#3708]
I have chosen the word that best describes what I am trying to accomplish however feel free to correct me. As we are building a more and more complex chatbot, it is becoming quite hard to cover all the different input scenarios that you could have, specially when we want to add LUIS shortly. 

As we started playing with the different tools in the framework + Adaptive Cards, it seems there is a little inconsistency like this:

1. Some action responses should be parsed with session.message.text (in the very same dialog step)
2. Some actions responses (AC) need to be parsed with session.message.value
3. postBack and dialogAction should be parsed in the same dialog step too however these send a JSON object. 

Since some of the dialogs are ended by the time the user chooses something (Let's say I sent a HeroCard carrousel with some buttons) I am finding that:

1. In some waterfall dialogs I need to parse on the same dialog
2. On some dialogs that are already finished, I need to parse on the default dialog.

The more we play with chatbots/botframework the more I realize that some of these might be needed to be created in our code or the framework:

1. An "ActionManager" should be created to make all the handling of the action globally. 
2. Think the defaultDialog is basically an ESB that should parse and analyze each message and that responses should not be treated on the same dialog. 
3. A middleware chain should be added to the bot, basically the same as the default dialog. 

I'd would love some thoughts or best practices on this as I feel that on every dialog I need to start adding more complex code to handle all the different scenarios. 

Thanks!

**Comment by nwhitmont** [comment]
@sfratini For reference, are you developing with .NET or Node.js SDK for BotBuilder?

**Comment by sfratini** [comment]
@nwhitmont Hey! I am using the NodeJS SDK. Version 3.11.0 at the moment. That is great news. While so far I have been able to work these out it makes a little harder to create much more complex chatbots. I'll be happy to test v4 preview. Thanks!

**Comment by xjose97x** [comment]
This are great news! 
I've been "simulating" a SpellCheck middleware by using a scorable. Would be nice to have a better way to achieve that.

Thanks!

**Comment by sfratini** [comment]
@xjose97x Would you mind sharing what you are doing? I managed to add another middleware chain to the bot to make some analytics.

**Comment by xjose97x** [comment]
@sfratini take a look a this: https://github.com/Microsoft/BotBuilder/issues/3627

What's the approach you're taking ?

**Comment by sfratini** [comment]
Ah, I see you are using .NET. So, I am making a appointment chatbot, basically so far it works, but I am guiding the user on every step, without taking into account that the user might send or talk about any other subject. This will get tricky once I add LUIS integration as I might be in the middle of a dialog and then the user could say something else. 

On the main dialog, I make the approach of checking every single variable that I need. If I have it, I go to the next step of the dialog, and if I need it, I start another dialog that only gathers that specific type of information. Like this:
```

bot.dialog("request", [
[...]
    function(session, results, next){      
        if (typeof session.privateConversationData.staff.id === 'undefined'){
                session.beginDialog("requestStaff"); 
        }
        else 
            next();
    },
[...]
])
```

Now I have different routes. For example in some dialogs I am getting the information in the very same dialog before I finish it:

```
bot.dialog("requestUserId", [
    function(session, args){
        if (args){
            if (args.notfound)
                builder.Prompts.text(session, "Not found");
            else if (args.multiple)
                builder.Prompts.text(session, "Multiple found");
            else if (args.error)
                builder.Prompts.text(session, "Error");
            else if (args.notallowed)
                builder.Prompts.text(session, "Not allowed");
        } else {
            builder.Prompts.text(session, "Question?");            
        }
    },
    function(session, results, next){
        delete session.message.text;        
        session.sendTyping();
        client.getCustomer(results.response).then((customer => {
                session.privateConversationData.profile = customer;
                session.endDialog("Hola %s!", customer.name);
        }))
        .catch((error => {

            if (error instanceof MultipleCustomersError){
                session.replaceDialog("requestUserId", {multiple: true});
                return;
            }

            if (error instanceof CustomerNotFoundError){
                session.replaceDialog("requestUserId", {notfound: true});
                return;
            }

            if (error instanceof CustomerNotAllowedError){
                session.replaceDialog("requestUserId", {notallowed: true});
                return;
            }

            session.replaceDialog("requestUserId", {error: true});
            return;

        }));
    }
]);
```

See that in that example I am looping in the same dialog until I get valid data. 

Then I have some that require a confirmation:

```
bot.dialog("requestConfirm", [
    function(session){

        if (session.message.text){
            if (session.message.text == 'confirmar'){
                session.endDialogWithResult({confirmed: true});
                return;
            } else if (session.message.text == 'modificar'){
                session.replaceDialog("requestModify");
                return;
            } else {
                session.send('Not understood, please choose another option');
            }
            delete session.message.text;            
        } else {
            session.send('Correct information?');            
        }
        
        let card = new builder.HeroCard(session)
        .title('Mi Turno')
        .text('My Text')
        .buttons([
            builder.CardAction.imBack(session, 'confirmar', "Confirmar"),
            builder.CardAction.imBack(session, 'modificar', "Modificar")            
        ]);
        
        var msg = new builder.Message(session);
        let cards = []; cards.push(card);
        msg.attachments(cards);
        session.send(msg);
    }

]);
```
Now in that dialog see that I need to parse the session.message.text because is a HeroCard. At the same time I delete the text value in order to avoid carrying it to another dialog. But with the AdaptiveCards is the session.message.value that you need to check:

```
bot.dialog("requestService", [
    function(session){

        if (session.message && session.message.value && session.message.value.service) {

            session.sendTyping();
            if (session.message.value.service > -1){
                client.getService().then((service) => {
                    session.privateConversationData.service = service;
                    session.endDialog();
                    return;
                })
                .catch(error => {
                    session.endDialog("An error ocurred");
                    return;
                });
                
            } else 
                session.send('Choose service');
                
        } else {

            let dropdown = {};
            let attachments = [];
            let choices = [];
            
            session.sendTyping();
            client.getServices().then((services) => {
    
                if (services != null && services.length > 0){
    
                    for (var index = 0; index < services.length; index++) {
                        let service = services[index];
                        choices.push({
                            title: service.name,
                            value: service.id
                        });
    
                    }
    
                    let attachment = {};                    
                    attachment.contentType = "application/vnd.microsoft.card.adaptive";
                    attachment.content = {
                        "type": "AdaptiveCard",
                        "version": "1.0",
                        "body": [
                          {
                            "type": "Input.ChoiceSet",
                            "id": "service",
                            "style": "compact",
                            "placeholder": "Elegi el servicio",
                            "value": "-1",
                            "choices": choices
                          }
                        ],
                        "actions": [
                          {
                            "type": "Action.Submit",
                            "title": "Enviar"
                          }
                        ]
                      };
                    attachments.push(attachment);
    
                    dropdown.type = "message";
                    dropdown.text = "Que servicio necesitas?";
                    dropdown.attachments = attachments;
            
                    session.send(dropdown);
    
                } else {
                    session.endDialog("Lo siento, en este momento no podemos recuperar la lista de servicios");
                }
    
            });

        }
        
    }
]);
```

And lastly I use dialogActions too which I either need to check in the same dialog or the defaultDialog in some dialogs that are over by the time I send the action (A button inside a card):

```

bot.dialog("cancelBooking", [
    function(session, args, next){

        try {
            if (session.message.text && session.message.text.indexOf("cancelBooking=") > -1){
                
                let index = session.message.text.indexOf("=") + 1;
                let bookingString = session.message.text.substring(index);
                booking = JSON.parse(bookingString);
    
            }
        } catch (error) {
            console.error(error);            
            session.endDialog("Lo siento, encontramos un error al identificar el turno");
            return;
        }
    
        if (booking != null){
            builder.Prompts.confirm(session,'text');       
        } else {
            session.endDialog("Lo siento, encontramos un error al identificar el turno");            
        }
        
    },
    function(session, results, next){
        if (results.response){

            session.sendTyping();
            client.cancelBooking(booking.id).then(cancelled => {
                if (cancelled){
                    session.endDialog("Gracias! Ya hemos cancelado tu turno");
                } else {
                    session.endDialog("Lo siento, hemos encontrado un error al cancelar el turno");                    
                }
            })
            .catch(error => {
                console.error(error);
                session.endDialog("Lo siento, hemos encontrado un error al cancelar el turno");
            });

        } else {
            session.endDialog("Perfecto, tu turno continua activo.");
        }
    }
]);

```


So that is my issue. Multiple ways of checking for actions. And multiple moments to check them. My first goal was to actually make it work, then I will refactor the code. 

Probably I will ended up using a chain of checks and next() as my first dialog which that actually works fine, because it just checks the info and requests it, kinda like an ESB. And then making every dialog a single function call as often as possible in order to make it simple. 

But again, the big issual will come when the user might end up in any dialog at any time.

**Comment by sfratini** [comment]
I believe I found another way to solve this in a more clean way. I will add a custom recognizer to parse my messages and route the actions, instead of modifying the defaultDialog. Lets see if that works best.
