### ISSUE TITLE
[Question] Getting an error sending this message to your bot: "HTTP status code InternalServerError"

### ISSUE THREAD

**Issue by GurjarMunna** [Microsoft/BotBuilder#3709]
## Bot Info 
* SDK Platform:  .NET 
* Active Channels: Web Chat
* Deployment Environment: IIS Server

**Comment by GurjarMunna** [comment]
![14adf51a-fbe7-47c2-9925-97f26a8efb1d](https://user-images.githubusercontent.com/33365326/32402297-d2127780-c146-11e7-97b7-784590798c82.png)

**Comment by GurjarMunna** [comment]
{
  "type": "message",
  "text": "hi",
  "from": {
    "id": "default-user",
    "name": "User"
  },
  "locale": "en-US",
  "textFormat": "plain",
  "timestamp": "2017-11-04T04:52:41.554Z",
  "channelData": {
    "clientActivityId": "1509771158473.47508236441077845.0"
  },
  "entities": [
    {
      "type": "ClientCapabilities",
      "requiresBotState": true,
      "supportsTts": true,
      "supportsListening": true
    }
  ],
  "id": "retry"
}

**Comment by EricDahlvang** [comment]
@GurjarMunna  Please provide:

## Code Example
- The bot code that reproduces the issue 

## Reproduction Steps
1.
2.
3.

**Comment by GurjarMunna** [comment]
Hello Eric,
Below is the code for bot
public async Task<HttpResponseMessage> Post([FromBody]Activity activity)
        {
            if (activity.Type == ActivityTypes.Message)
            {
                ConnectorClient connector = new ConnectorClient(new Uri(activity.ServiceUrl));
          
                int length = (activity.Text ?? string.Empty).Length;
                // return our reply to the user
                Activity reply = activity.CreateReply($"Hello");
                await connector.Conversations.ReplyToActivityAsync(reply);
                //await Conversation.SendAsync(activity, () => new RootDialog());
            }
            else
            {
                HandleSystemMessage(activity);
            }
            var response = Request.CreateResponse(HttpStatusCode.OK);
            return response;
        }

and the same is not working web chat chanel

**Comment by EricDahlvang** [comment]
Is your bot deployed, or running locally?  What is your botid?  Do you have the MicrosoftAppId and MicrosoftAppPassword in the web.config?

**Comment by GurjarMunna** [comment]
yes, my bot is deployed on iis server and i have declared both MSA id and password in my web.config.
its working fine with Skype Chanel.

**Comment by GurjarMunna** [comment]
When i debug this with ngrok then i gets the error "Security token for MicrosoftAppId: ************************* is unauthorized to post to connector!"

**Comment by EricDahlvang** [comment]
@GurjarMunna 

Which version of the .net bot builder sdk are you using?

**Comment by GurjarMunna** [comment]
**@EricDahlvang** 

There was an issue with the version of .net bot builder. Now its working fine. 
Thanks for your support.

**Comment by GurjarMunna** [comment]
Now i am closing this issue.
