### ISSUE TITLE
[Skype] Truncated text in Hero Cards?

### ISSUE THREAD

**Issue by OFarukCaki** [Microsoft/BotBuilder#3713]
## Bot Info 
* App ID:  haveibeenpwned
* SDK Platform:  Node.js
* Active Channels: 
   - FB Messenger: https://www.messenger.com/t/257187708141828
   - Skype: https://join.skype.com/bot/78434275-b560-4ab1-bf8b-8df8361d6b59
* Deployment Environment: Azure Web Service

## Issue Description
I created my app, I have a hero card inside my chatbot and it just works fine in emulator. But in other platforms my bots are truncating my text inside cards.
Here is a screenshot : https://i.hizliresim.com/ROgLrZ.png
![roglrz](https://user-images.githubusercontent.com/3075047/32518539-baea61c4-c3be-11e7-89e4-e068472755f3.png)

In the Emulator it is just fine: https://i.hizliresim.com/DyOVOZ.png
![dyovoz](https://user-images.githubusercontent.com/3075047/32518545-c258e64c-c3be-11e7-95b5-9111dbfbba1a.png)

## Code Example
```js
msg.attachments([
                    new builder.HeroCard(session)
                        .title(wol.Name)
                        .subtitle("Domain: "+wol.Domain)
                        .text("Breach Date: "+wol.BreachDate+"\n\n"+"\n\n"+
                        "Pwned Accounts: "+wol.PwnCount.toLocaleString()+
                        "\n\n——————\n\nThis breach contains:\n\n"+
                        wol.DataClasses.join("\n\n")),
                        
            
                    new builder.HeroCard(session)
                        .title("About "+wol.Name+" Data Breach")                        
                        .text(striptags(wol.Description)),
                        
                    new builder.HeroCard(session)
                        .subtitle("Other Informations:")                        
                        .text("Is Verified: "+otherI.verified+
                        "\n\nIs Sensitive: "+otherI.sens+
                        "\n\nSpam List: "+otherI.spam+
                        "\n\nIs Retired: "+otherI.retired+
                        "\n\nIs Fabricated: "+otherI.fabricated
                    )          
                ]);
                session.send(msg).endDialog();
```

## Expected Behavior
Text inside the cards should be fully viewable

How can I fix my this issue?

**Comment by OFarukCaki** [comment]
Also my full codes are in here https://github.com/OFarukCaki/deneme

**Comment by nwhitmont** [comment]
@OFarukCaki Think of this as a design problem rather than a HeroCard problem.

You're not really using any of the features of the HeroCard template, like buttons, images, and card actions, so why do you need the HeroCard at all?

If you are only sending text, use normal messages instead of multiple HeroCards packed into a carousel layout.

Example:
```js
let messageWithText = {
    type: "message",
    text: "**Message Title**\n\nLarge amount of text goes here..."
}
session.send(messageWithText);
```

**Comment by OFarukCaki** [comment]
@nwhitmont Thanks for your comment. I'm gonna try it now

**Comment by OFarukCaki** [comment]
@nwhitmont, How can I add more than 1 normal messages in carousel format, I can't find any documentation and I can't figure out

`var msg = new builder.Message(session);
                msg.attachmentLayout(builder.AttachmentLayout.carousel)
                msg.attachments([
                   
                    ......
                          
                ]);`

How can I place my items inside that code block?

**Comment by nwhitmont** [comment]
@OFarukCaki You can only have cards or images in a carousel layout, it is not intended for use with text-only messages.

You can put attachment objects inside the array of attachments like this:
```js
msg.attachments([ 
    {
        contentType: 'image/png',
        contentUrl: 'https://example.com/img/your_image.png',
        name: 'example image attachment'
    },
   {
        contentType: 'image/png',
        contentUrl: 'https://example.com/img/your_image.png',
        name: 'example image attachment'
    }
])
```

**Comment by nwhitmont** [comment]
reopen if you still have questions
