### ISSUE TITLE
[FB Messenger] No messenger notifications?

### ISSUE THREAD

**Issue by k-yle** [Microsoft/BotBuilder#3714]
## Bot Info 
* App ID: 181012929091413 (messenger)
* SDK Platform: Node.js
* SDK Version: 3.11.0
* Active Channels: facebook, skype
* Deployment Environment: azure web app

## Issue Description
facebook messenger notifications are not triggered. 
I've tried doing 

```js
session.send(new builder.Message()
    .text('Hello World!')
    .sourceEvent({ facebook: { notification_type: 'REGULAR' } })
).endDialog();
````
but that doesn't make a difference.

## Code Example
```js
bot.dialog('/whatever', (session) => {
    session.send('Hello');
});
```
or 
```js
session.send(new builder.Message()
    .text('Hello World!')
    .sourceEvent({ facebook: { notification_type: 'REGULAR' } })
).endDialog();
````
 (neither works)
## Reproduction Steps
1. Send any message to a messenger user (e.g. by using `session.send('...')`)

## Expected Behavior
You should get a notification.

## Actual Results
You won't get a notification (but the message is still delivered)

**Comment by nwhitmont** [comment]
@k-yle To get this channel-specific functionality, you need to use the `channelData` property as described in this article:

https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-channeldata#create-a-facebook-notification

Example:
```json
"channelData": {
    "notification_type": "NO_PUSH",
    "attachment": {
        "type": "template"
        "payload": {
            "template_type": "receipt",
            . . .
        }
    }
}
```

**Comment by k-yle** [comment]
How would I use this for a normal text message? -
And how do I do this in the node.js SDK – specifically, where do I put the JSON object from your example – in `session.send` or `sourceEvent` or somewhere else?

Thanks for the help


Sent from Outlook for Android

**Comment by nwhitmont** [comment]
@k-yle The message itself is just another JSON object of `type: "message"`.

You put the `channelData` inside the message object like this:

```js
let exampleMessageWithChannelData = {
  "type": "message",
  "channelData": {
      "notification_type": "NO_PUSH",
      "attachment": {
          "type": "template",
          "payload": {
              "template_type": "receipt"
          }
      }
  }
}
```

**Comment by k-yle** [comment]
Thanks for your help @nwhitmont

If anyone else comes across this issue, there is a shorthand way of setting `channelData` using the `sourceEvent` method:

e.g.
```js
session.send(new builder.Message(session)
    .text('Hello world')
    .sourceEvent({ facebook: { 'notification_type': 'REGULAR' } })
);
```
#### notification_types
`REGULAR`: sound/vibration
`SILENT_PUSH`: on-screen notification only (MS bot framework default)
`NO_PUSH`: no notification
