### ISSUE TITLE
[.Net SDK, LUIS] How does navigation work with LUIS subdialogs?

### ISSUE THREAD

**Issue by Avalaxy** [Microsoft/BotBuilder#3715]
Hi, I have a question... Unfortunately all the samples on the web are too shallow and don't really cover this well:

I have a RootDialog that extends the LuisDialog. This RootDialog is responsible for figuring out what the user wants to do. It could be multiple things, but one of them would be initiating a new order. For this, the RootDialog would forward the call to the NewOrderDialog, and the responsibility of the NewOrderDialog would be to figure out some basic details (what does the user want to order, which address does he like to use) and finally it will confirm the order and return back to the RootDialog.

The code for the RootDialog is very simple:
```cs
    [Serializable]
    public class RootDialog : LuisDialog<object>
    {
        public RootDialog() : base(new LuisService(new LuisModelAttribute(ConfigurationManager.AppSettings["LuisAppId"], ConfigurationManager.AppSettings["LuisAPIKey"], domain: "westus.api.cognitive.microsoft.com")))
        {
        }

        [LuisIntent("Order.Place")]
        public async Task PlaceOrderIntent(IDialogContext context, LuisResult result)
        {
            await context.Forward(new NewOrderDialog(), OnPlaceOrderIntentCompleted, context.Activity, CancellationToken.None);

            context.Wait(MessageReceived);
        }

        private async Task OnPlaceOrderIntentCompleted(IDialogContext context, IAwaitable<object> result)
        {
            await context.PostAsync("Your order has been placed. Thank you for shopping with us.");

            context.Wait(MessageReceived);
        }
    }
```
I also had some code in mind for the NewOrderDialog:
```cs
    [Serializable]
    public class NewOrderDialog : LuisDialog<object>
    {
        private string _product;
        private string _address;

        public NewOrderDialog() : base(new LuisService(new LuisModelAttribute(ConfigurationManager.AppSettings["LuisAppId"], ConfigurationManager.AppSettings["LuisAPIKey"], domain: "westus.api.cognitive.microsoft.com")))
        {
        }

        [LuisIntent("Order.RequestedItem")]
        public async Task RequestItemIntent(IDialogContext context, LuisResult result)
        {
            EntityRecommendation item;
            if (result.TryFindEntity("Item", out item))
            {
                _product = item.Entity;
                await context.PostAsync($"Okay, I understood you want to order: {_product}.");
            }
            else
            {
                await context.PostAsync("I couldn't understand what you would like to buy. Can you try it again?");
            }

            context.Wait(MessageReceived);
        }

        [LuisIntent("Order.AddedAddress")]
        public async Task AddAddressIntent(IDialogContext context, LuisResult result)
        {
            EntityRecommendation item;
            if (result.TryFindEntity("Address", out item))
            {
                _address = item.Entity;
                await context.PostAsync($"Okay, I understood you want to ship the item to: {_address}.");
            }
            else
            {
                await context.PostAsync("I couldn't understand where you would like to ship the item. Can you try it again?");
            }

            context.Wait(MessageReceived);
        }
    }
```

The code as listed doesn't work. Upon entering the Order.Place intent, it immediately executes the 'success' callback, and then throws this exception:

> Exception: IDialog method execution finished with multiple resume handlers specified through IDialogStack.
> [File of type 'text/plain']

So I have a few questions:

1. How do I solve the error that I get?
2. How can I, upon entering the NewOrderDialog, check if we already know what the product and address is, and if not prompt them for the correct info?
3. Why does the NewOrderDialog get closed even though I don't call anything like context.Done()? I only want it to be closed when all the info has been gathered and the order has been confirmed.

**Comment by EricDahlvang** [comment]
It looks like this code is calling `context.Wait(MessageReceived);` AFTER calling `context.Forward(...)`.  If .Forward() or .Call() are used, then a .Wait() should not follow it.

https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-manage-conversation-flow?view=azure-bot-service-3.0#dialog-lifecycle
