### ISSUE TITLE
[Channel Configuration] Unable to save Messenger channel config. Failed to register with Facebook?

### ISSUE THREAD

**Issue by cmnisal** [Microsoft/BotBuilder#3718]
* App ID: 2dfb3ddf-41b0-4090-b3f7-c2ad22718405
* SDK Platform: Node.js
* SDK Version: 3.10.8
* Skype, Web, Facevook
* Deployment Environment: Auzure Bot Service, Azure App Service

## Issue Description
Cannot Save Facebook Channel Configuration

## Reproduction Steps
1. Goto Azure Portal
2. Select Bot App
3. Channels
4. Facebook Messenger
5. Add Configurations (Facebook Page ID,Facebook App ID,Facebook App Secret,Page Access Token)
6. Save

## Expected Behavior
Save and Enable Facebook Channel
 
## Actual Results
Unable to save. Failed to register with Facebook with: BadRequest ID: |/AyJB.a121da27_
#
![image](https://user-images.githubusercontent.com/8001789/32428867-053c912e-c2ee-11e7-9320-41f19cc0b6d9.png)

**Comment by cmnisal** [comment]
I tried with a New Page its also the Same Error

**Comment by JasonSowers** [comment]
Did you follow [these instructions](https://docs.microsoft.com/en-us/bot-framework/channel-connect-facebook)?

**Comment by Rigo85** [comment]
Hi everyone! @JasonSowers, @cmnisal, @fanidamj, I have the same issue #3562, it was closed(don't why!) and the issue still in there! I really don't know what to do.

Best regards.

**Comment by JasonSowers** [comment]
@mgbennet can you take a look at this please?

**Comment by slidenerd** [comment]
I double this,in my case it gives me a forbidden id error
**Unable to save. Failed to register with Facebook with: Forbidden ID: |A/2Fb.b109c71_**
I am on node.js as well with 3.9.1 as the bot framework version on windows

**Comment by krystiangw** [comment]
Same for me. My exact error code is:

"Unable to save. Failed to register with Facebook with: Forbidden ID: |Qmgtp.d42561bf_"

What is more important it used to work for exactly same credentials and I can't even re-save it. Any ideas?

**Comment by slidenerd** [comment]
I cannot delete my app on facebook for any reason as the bot was live for 6+ months and i ll be wiping out my analytics and stuff, I tried the webhook thing a couple of times,

1. Remove existing webhook subscriptions
2. Get a new page access token
3. Update this on my heroku server
4. Paste the page id, app id, facebook secret and facebook page access token, get the callback url and verify token
paste those into the facebook webhook setup and at this point try to save everything on the azure portal where it keeps giving me the forbidden id error. I tested through my emulator connected with my live heroku server and through webchat and those are working perfectly

**Comment by slidenerd** [comment]
![image 2](https://user-images.githubusercontent.com/5139030/37827950-73317d38-2ebf-11e8-97d7-2b6fff3038e1.png)
Could this be the source of the problem? My bot was running 2.9 but now it seems Graph API has gone up to 2.12, since the botframework doesn't directly let you input any graph API urls, i assume it is building these urls behind the scenes

**Comment by EricDahlvang** [comment]
@cmnisal Are you still experiencing issues when configuring Facebook?

**Comment by krystiangw** [comment]
I created support case for the issue and it was resolved on March 24th 2018.
Case no 118032317874099

The issue reason was:
```Facebook started blocking calls to one of their api's that we were using to validate credentials. Fix was to call an approved api that is not blocked.```

I can confirm it was solved for my account.

**Comment by EricDahlvang** [comment]
@cmnisal please open a new issue if you are still experiencing problems with Facebook configuration
