### ISSUE TITLE
[Question] When will BotBuilder SDK support FB List & Menu?

### ISSUE THREAD

**Issue by SerendioSoftwares** [Microsoft/BotBuilder#3720]
## Bot Info 
* SDK Platform: Node.js
* Active Channels: Messenger
* Deployment Environment: ngrok

## Actual Results
When I tried sending native messages (for FB), it produced the infamous api error, and crashed.

**Comment by nwhitmont** [comment]
@SerendioSoftwares Have you tried sending your Messenger specific formatting data via the `channelData` property of the `Message` object?

See:
https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-channeldata

**Comment by nwhitmont** [comment]
@SerendioSoftwares Were you able to solve it using the `channelData` property?

**Comment by nwhitmont** [comment]
closing as no response from user
