### ISSUE TITLE
[Skype] ACL check failed?

### ISSUE THREAD

**Issue by damian1976** [Microsoft/BotBuilder#3721]
* App ID: c6620653-4023-4497-a0bf-8b9bc0d33a92
* SDK Platform: Node.js
* SDK Version: 3.11.0
* Active Channels: Skype
* Deployment Environment: nginx

## Issue Description

ACL warning message keeps appearing when adding and talking to the skype bot. App is in review state for more than 2 weeks now.

## Code Example
No relevant code (a typical HelloWorld bot code)

## Reproduction Steps
1. Add bot to skype contact list
2. Send message to the bot
3. ACL warning appears on the framework web page

## Expected Behavior
User can add a bot to his/her skype contact list and talk with the bot.

## Actual Results
User can add a bot to his/her contact list but no conversation is possible (ACL check failed warning on bot framework website). There's no error when talking with bot using Bot Emulator aid microsoft credentials.

**Comment by nwhitmont** [comment]
@damian1976 This is a known issue which shouldn't affect the functioning of your bot. 

You can safely ignore the "ACL check failed" warnings in the Bot Portal channel warnings.

**Comment by damian1976** [comment]
May it be the case that Bot is still in InReview state (currently for more than 2 weeks)? Is there any chance to find out what's wrong and where's the problem (why it's not published)?

**Comment by nwhitmont** [comment]
@damian1976 I have pinged the bot-reviewers on your behalf.
