### ISSUE TITLE
[.Net SDK, Slack] How do you reply to question by starting a thread?

### ISSUE THREAD

**Issue by Pena012345** [Microsoft/BotBuilder#3722]
How can you reply to question in Slack channel by starting a thread from the question automaticly and not replying to channel?

If there is thread already, the bot answer to the thread but how can you start a thread from the question?

**Comment by nwhitmont** [comment]
@Pena012345 Are you using .NET or Node.js SDK for BotBuilder?

**Comment by Pena012345** [comment]
I'm using .NET.

**Comment by JasonSowers** [comment]
Currently, there is nothing built into the SDK for this.  However, you may be able to put something together using the `ChannelData` property and sending the correct JSON payload to slack.  Looking through the slack [documentation](https://api.slack.com/docs/message-threading#threads_party)  it appears this might be able to be accomplished, but there are no explicit instructions.

**Comment by Pena012345** [comment]
I tried to put thread_ts and text in channeldata and otherwise left message empty and it didn't work. Text was visible but message went straigth to channel, Slack didn't use thread_ts value. Is there somekind of the problem with thread_ts variable? If you check https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-channeldata there is no mention about thread_ts variable.

**Comment by Pena012345** [comment]
Should someone see to this that thread_ts variable is passed ok to slack? When thread is already started the conversation stays on thread but you cannot start thread in slack with current channeldata.

**Comment by jorupp** [comment]
Any word on this?  #2273 indicates that threaded support should work, and if a message is already in a thread, replies are going back to the thread fine, but I can't get my bot to start a thread off a normal message - sending the JObject `{ thread_ts = ... }` where `...` is the ts from the original activities `ChannelData.SlackMessage.event.ts` doesn't seem to have any effect.

**Comment by JasonSowers** [comment]
@Pena012345 and @jorupp 

I was able to accomplish this by using the following code:
```cs
    public async Task MessageReceivedAsync(IDialogContext context, IAwaitable<IMessageActivity> argument)
    {
        var activity = await argument;
        var ts = activity.ChannelData?.SlackMessage?.thread_ts
                 ?? activity.ChannelData?.SlackMessage?.ts
                 ?? activity.ChannelData?.SlackMessage["event"].thread_ts
                 ?? activity.ChannelData?.SlackMessage["event"].ts;

        var reply = (Activity)activity;
        reply = reply.CreateReply();

        reply.ChannelData = JObject.Parse($"{{text:'Some text', thread_ts:'{ts}'}}");
        await context.PostAsync(reply);
    }
```

**Comment by jorupp** [comment]
Wow, that seems so obvious... So in addition to sending the `thread_ts`, you also have to send the `text` in the `ChannelData`.  If you do, it's in the thread.  If you also set `Text` on the `IActivity`, you get a new thread with the message *and* a new message to the channel.  If you only do the one in `ChannelData`, you just get the reply into the thread.

Thanks @JasonSowers.

**Comment by jorupp** [comment]
... and now I have a new problem - replies from the user on that thread seem to start a new conversation, but messages in the channel get processed as part of the original conversation (that I'm intending to be on the thread now).

Are changes needed to the way it looks up the conversation state to include the thread id in?

**Comment by jorupp** [comment]
Appears you can modify the activity before you pass it off to `Conversation.SendAsync` without any apparent adverse side effects...  This actually worked...

```
if (activity.ChannelId == "slack")
{
    // set up the conversation so we'll be in the thread
    string thread_ts = ((dynamic)activity.ChannelData)?.SlackMessage?.@event?.thread_ts;
    string ts = ((dynamic)activity.ChannelData)?.SlackMessage?.@event?.ts;
    if (string.IsNullOrEmpty(thread_ts) && !string.IsNullOrEmpty(ts) && activity.Conversation.Id.Split(':').Length == 3)
    {
        // this is a main-channel conversation - pretend it came in on a thread
        activity.Conversation.Id += $":{ts}";
    }
}
```
Of course, it's reliant on the specific format of the conversation ID, so it's pretty hacky.  Maybe v4 improves the situation, but this looks like it'll work for my quick-hack.

**Comment by JasonSowers** [comment]
Glad you got this working.

**Comment by saiteja21** [comment]
V4 implementation 
`protected override async Task OnMessageActivityAsync(ITurnContext<IMessageActivity> turnContext, CancellationToken cancellationToken)
        {
            if (turnContext.Activity.ChannelId == "slack")
            {
                var t = turnContext.Activity;
                var activity = turnContext.Activity;

                var ts = activity.ChannelData?.SlackMessage?.thread_ts
                         ?? activity.ChannelData?.SlackMessage?.ts
                         ?? activity.ChannelData?.SlackMessage["event"].thread_ts
                         ?? activity.ChannelData?.SlackMessage["event"].ts;

                var replyText = $"Echo: {turnContext.Activity.Text}" + " : " + turnContext.Activity.ChannelId;
                var reply = (Activity)activity;
                reply = reply.CreateReply();
                reply.ChannelData = JObject.Parse($"{{text:'{replyText}', thread_ts:'{ts}'}}");

                //var replyText = $"Echo: {turnContext.Activity.Text}" + t;
                await turnContext.SendActivityAsync(reply, cancellationToken);
            }
            else
            {
                var replyText = $"Echo: {turnContext.Activity.Text}" + " : " + turnContext.Activity.ChannelId;
                await turnContext.SendActivityAsync(MessageFactory.Text(replyText, replyText), cancellationToken);
            }
        }`

**Comment by saiteja21** [comment]
V4 Implementation

```
protected override async Task OnMessageActivityAsync(ITurnContext<IMessageActivity> turnContext, CancellationToken cancellationToken)
        {
            if (turnContext.Activity.ChannelId == "slack")
            {
                var activity = turnContext.Activity;

                var ts = activity.ChannelData?.SlackMessage?.thread_ts
                         ?? activity.ChannelData?.SlackMessage?.ts
                         ?? activity.ChannelData?.SlackMessage["event"].thread_ts
                         ?? activity.ChannelData?.SlackMessage["event"].ts;

                var replyText = $"Echo: {turnContext.Activity.Text}" + " : " + turnContext.Activity.ChannelId;
                var reply = (Activity)activity;
                reply = reply.CreateReply();
                reply.ChannelData = JObject.Parse($"{{text:'{replyText}', thread_ts:'{ts}'}}");

                //var replyText = $"Echo: {turnContext.Activity.Text}" + t;
                await turnContext.SendActivityAsync(reply, cancellationToken);
            }
            else
            {
                var replyText = $"Echo: {turnContext.Activity.Text}" + " : " + turnContext.Activity.ChannelId;
                await turnContext.SendActivityAsync(MessageFactory.Text(replyText, replyText), cancellationToken);
            }
        }
```

**Comment by hrmadduri** [comment]
With the above code I'm able to send a simple text message in thread fine. I'm not able to send a hero card containing some text and buttons in thread.
The card is added to the activity.attachments and the card do not have a property for thread_ts. I have added channel data to the activity with thread_ts but it is not showing any effect. When I give text in the channel data the text is coming in thread and the attachment(hero card) is directly posted to channel.

**Comment by mattlangis** [comment]
If you don't come from a slack thread, it will always reply where the message came from (ex: a channel).
From what I understood, it's because `TurnContext` do a `ApplyConversationReference` which always override any crafted reply with the reference `Conversation`.
See:
https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder/TurnContext.cs#L316
and
https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Schema/ActivityEx.cs#L497

The only way I found to reply in a thread from a channel was to set the `thread_ts` in that reference.

Here's an example:
```
protected override async Task OnMessageActivityAsync(ITurnContext<IMessageActivity> turnContext, CancellationToken cancellationToken)
        {
            var conversationReference = turnContext.Activity.GetConversationReference();
            conversationReference.Conversation.Properties["thread_ts"] = turnContext.Activity.Id; // force the reference to go in a slack thread

            await turnContext.SendActivityAsync(MessageFactory.Text("Some reply"), cancellationToken);
        }
```

Any `turnContext.SendActivityAsync` will be sent in that thread while in scope.

**Comment by mattlangis** [comment]
Replying to my previous comment:
The reason that it wasn't working is that the bot implementation shouldn't be _slack_ specific, the bot should be kept generic.
Use the [SlackAdapter ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.builder.adapters.slack.slackadapter?view=botbuilder-dotnet-stable) instead and add something like that in `SendActivitiesAsync`:

`activity.Conversation.Properties["thread_ts"] = turnContext.Activity.Id;`
