### ISSUE TITLE
[Code Examples] Ad hoc proactive message sample app generates 401 Error?

### ISSUE THREAD

**Issue by verdysh** [Microsoft/BotBuilder#3723]
## Bot Info 
* SDK Platform: .NET
* SDK Version: 3.11.0.0
* Active Channels: Skype, Telegram

## Issue Description
Hi!

I try to send messages as in this example: https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-proactive-messages. Previously, I collected and saved user data (which are specified in the example) in the database. At first there were no problems and the messages were sent.

But after some time when I trying to send a message:

`await connector.Conversations.SendToConversationAsync((Activity)message);`

I get an error 401 (Unauthorized).
I found a similar situation: https://github.com/Microsoft/BotBuilder/issues/2575
@EricDahlvang writes:

> You need to add a call to
> MicrosoftAppCredentials.TrustServiceUrl(serviceUrl);
> This is done automatically when you are replying to a message, but not when using the ConnectorClient

Where to insert this code? Or how can solve this problem?

**Comment by EricDahlvang** [comment]
@verdysh  A call to MicrosoftAppCredentials.TrustServiceUrl(message.ServiceUrl); should be added before the call to SendToConversationAsync

**Comment by verdysh** [comment]
@EricDahlvang, here is the code that is responsible for sending the message (`MicrosoftAppCredentials.TrustServiceUrl(message.ServiceUrl) `I added after reading your message above):

```
public static class AdHocProactiveMessage
{
	public static async Task<bool> Send(string userId, string messageText)
	{
		using (BotBrainsEntities db = new BotBrainsEntities())
		{
			var rows = db.AdHocProactiveMessagesUserData.Where(row => row.UserId == new Guid(userId)).Select(row => row);
			if (!rows.Any())
				return false;

			AdHocProactiveMessagesUserData userData = rows.First();

			var userAccount = new ChannelAccount(userData.ToId, userData.ToName);
			var botAccount = new ChannelAccount(userData.FromId, userData.FromName);
			var connector = new ConnectorClient(new Uri(userData.ServiceUrl));

			IMessageActivity message = Activity.CreateMessageActivity();
			message.ChannelId = userData.ChannelId;

			message.From = botAccount;
			message.Recipient = userAccount;
			message.Conversation = new ConversationAccount(id: userData.ConversationId);
			message.Text = messageText;

			MicrosoftAppCredentials.TrustServiceUrl(message.ServiceUrl);
			await connector.Conversations.SendToConversationAsync((Activity)message);
		}

		return true;
	}
}
```

Here is the code that saves the data for sending the message:

```
private void SaveAdHocProactiveMessagesUserData(IDialogContext context)
{
	using (BotBrainsEntities db = new BotBrainsEntities())
	{
		var data = new AdHocProactiveMessagesUserData
		{
			UserId = _userManager.Id,
			ToId = context.Activity.From.Id,
			ToName = context.Activity.From.Name ?? "",
			FromId = context.Activity.Recipient.Id,
			FromName = context.Activity.Recipient.Name ?? "",
			ServiceUrl = context.Activity.ServiceUrl,
			ChannelId = context.Activity.ChannelId,
			ConversationId = context.Activity.Conversation.Id
		};
		db.AdHocProactiveMessagesUserData.AddOrUpdate(data);
		db.SaveChanges();
	}
}
```

Here is the code that initiates sending a message:

`bool result = await AdHocProactiveMessage.Send(userId, message);`

In the beginning everything works well. But if I try to send a message in ~30 minutes, then the above error occurs. What am I doing wrong?

**Comment by verdysh** [comment]
@EricDahlvang, thank you!
