### ISSUE TITLE
[Skype for Business] Second message is reseting the dialog stack?

### ISSUE THREAD

**Issue by theGusPassos** [Microsoft/BotBuilder#3724]
## Bot Info 
* SDK Platform: .NET
* SDK Version: 3.11.0.0
* Active Channels: Skype for Business
* Deployment Environment: Azure App Service

## Issue Description
When talking to the bot using Skype for Business 2016, the second message resets the dialog stack, so if the first dialog is waiting for an user input it will be canceled before its end. 

## Code Example

**MessagesController.cs**
```
using (var scope = DialogModule.BeginLifetimeScope(Conversation.Container, activity))
{
    var rootDialog = scope.Resolve<RootDialog>();

    await Conversation.SendAsync(activity, () => rootDialog, token);
}
```

**RootDialog.cs**
```
[LuisIntent(Constants.Intents.Greeting)]
public Task GreetingDialog(IDialogContext context, LuisResult result)
{
    context.Call
    (
        dialogFactory.Create<GreetingDialog>(),
        Callback
    );

    return Task.CompletedTask;
}

[LuisIntent(Constants.Intents.RequestWifiPassword)]
public Task RequestWifiAccessDialog(IDialogContext context, LuisResult result)
{
    context.Call
    (
        dialogFactory.Create<RequestWifiPasswordDialog>(),
        CallbackMessage
    );

    return Task.CompletedTask;
}
```

**GreetingDialog.cs**
```
public async Task StartAsync(IDialogContext context)
{
    await context.PostAsync("- This is the greeting dialog");

    context.Done(true);
}
```

**RequestWifiPasswordDialog.cs**
```
public async Task StartAsync(IDialogContext context)
{
    ActivitySender.SendTyping(context.Activity);

    PromptDialog.Confirm
    (
        context,
        AfterConfirmation,
        "Would you like to ask a new wifi password?"
    );
}

private async Task AfterConfirmation(IDialogContext context, IAwaitable<bool> result)
{
    bool answer = await result;

    await context.PostAsync("Your answer was: " + answer);

    context.Done(true);
}
```

## Reproduction Steps
1. Start a dialog that will depend on user input (PromptDialog.Confirm, PromptDialog.Choice, context.Call for new forms...)
2. Give the first input inside the dialog

This example here:
![wrong1](https://user-images.githubusercontent.com/19814544/32463464-16a835c2-c324-11e7-8545-68ebfb3993a2.png)

## Expected Behavior
The bot should continue in the dialog started, as it does in the Bot Framework Emulator.

It works when another dialog with no persistance is called before:
![wrong](https://user-images.githubusercontent.com/19814544/32463499-2f46d23c-c324-11e7-9268-c861d313ff67.png)

## Actual Results
The bot restarts the dialog stack, and the second message is ignored.

**Comment by JasonSowers** [comment]
Please open a new issue if you are still experiencing problems
