### ISSUE TITLE
[Question] How to use triggerAction with regex?

### ISSUE THREAD

**Issue by FlamingDrake** [Microsoft/BotBuilder#3725]
## Bot Info 
* SDK Platform: Node.js
* Active Channels: Emulator
* Deployment Environment: Emulator

## Issue Description
TriggerAction uses whatever the user types and stops using what the recognizer tells is recognized if matched is a regex.

## Code Example
I have a library with a triggerAction attached to it. 
```js
lib.dialog('/', function(session) {
    <code>
}).triggerAction({matches: RegEx})
```

In my case I have that dialog handle listings of things, so my regex was /^Get.*List$/. Should trigger on every recognized intent which starts with Get and ends with List. The recognizer find it but doesn't route to the dialog.

If I switch out the RegEx to a single string (for instance "GetUserList") it works, and the user list dialog starts. But, I have several more lists all which are on the format of `Get<topic>List` which is why that RegEx was so neat.

My recognizer is my own creation and classifies whatever the user types into things my triggerAction can handle. "get user" gets recognized as "GetUserList", "get group" gets recognized as "GetGroupList" etc.

However, if the user types "Get 'random string' List", the triggerAction wakes up. So I think if you use a triggerAction with "matches: RegEx" it starts listening to the message rather than the recognizers. 

## Expected Behavior
Is this the intended behavior of the framework? If that is the case, is there a way around it, so I don't need to type out the name of every single type of list the matches bracket.

**Comment by nwhitmont** [comment]
@FlamingDrake What are you trying to accomplish here exactly? Can you provide more context?

**Comment by FlamingDrake** [comment]
My recognizer generates multiple intents where all have names like GetUserList, GetGroupList etc. Always starts with Get, a topic in the middle and ends with List.
I have a single dialog that can handle all lists, but I don't know how to make it trigger on a multiple intents without having to make an array and fill it with all different lists. 

Or in other words, I would like the RegEx /^Get.*List$/ to listen on intents rather than the message.
