### ISSUE TITLE
web chat and bot framework

### ISSUE THREAD

**Issue by zxy66481** [Microsoft/BotBuilder#3726]
How to pass a custom Web chat interface value to the background processing, request help, extremely grateful!
![default](https://user-images.githubusercontent.com/32949019/32483607-b44bdf64-c3d7-11e7-9763-bd27fcac1a3e.PNG)

**Comment by EricDahlvang** [comment]
The webchat's **BackChannel** provides this functionality: https://github.com/Microsoft/BotFramework-WebChat#the-backchannel

**Comment by zxy66481** [comment]
Backchannel can transmit webchat directly to obtain data, and then directly to the robot, please give detailed instructions. thank you so much

**Comment by zxy66481** [comment]
Backchannel can transmit webchat directly to obtain data, and then directly to the robot, please give detailed instructions. thank you so much @EricDahlvang

**Comment by EricDahlvang** [comment]
@zxy66481 This page shows how to receive a message from the bot, and process it in the webchat's client side code via backchannel: https://github.com/Microsoft/BotFramework-WebChat/blob/master/samples/backchannel/index.html  This doc explains more about the backchannel itself: https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-backchannel

If your bot is built using the .net sdk, this example might also be helpful: https://github.com/EricDahlvang/BackChannelEventTest

**Comment by EricDahlvang** [comment]
Closing this issue.  

If you have further questions, please open a new issue or ask the question on StackOverflow with the BotFramework tag.
