### ISSUE TITLE
[QnA Maker] How to customize the "No match found!" message?

### ISSUE THREAD

**Issue by iantje31** [Microsoft/BotBuilder#3727]
## Bot Info 
* App ID: 8dd6a32f-bb28-4d73-8cc5-a58427ff1696
* SDK Platform: .NET
* SDK Version: QnAmaker
* Active Channels: WebChat, Microsoft Teams
* Deployment Environment: Azure Bot Service

## Issue Description
I am trying to change the default message that is being sent when the bot can't find a match in the Knowledge Base. I searched online and found an article that said you need to change a line in the BasicQnAMakerDialog.cs file. When i change the code in that file, nothing happens.

## Code Example
```
using System;
using System.Configuration;
using System.Linq;
using System.Threading.Tasks;
using System.Threading;
using Microsoft.Bot.Connector;
using Microsoft.Bot.Builder.Dialogs;

using Microsoft.Bot.Builder.CognitiveServices.QnAMaker;

namespace Microsoft.Bot.Sample.QnABot
{
    // For more information about this template visit http://aka.ms/azurebots-csharp-qnamaker
    [Serializable]
    public class BasicQnAMakerDialog : QnAMakerDialog
    {
        // Go to https://qnamaker.ai and feed data, train & publish your QnA Knowledgebase.
        public BasicQnAMakerDialog() : base(new QnAMakerService(new QnAMakerAttribute(Utils.GetAppSetting("QnASubscriptionKey"), Utils.GetAppSetting("QnAKnowledgebaseId"), 'No good match in FAQ.', 0.5)))
        {}

```
## Reproduction Steps
1. Type something random (for example: "gjksfgfs")
2. Send it to the bot
3. The bot replies with: "No match found!"

## Expected Behavior
I expect the bot to reply: "No good match in FAQ" 

## Actual Results
The bot replies with "No match found!"

**Comment by FranciscoPonceGomez** [comment]
Hi @iantje31,

You can override  RespondFromQnAMakerResultAsync in your dialog to customize the response from QnAMaker

```cs
protected override async Task RespondFromQnAMakerResultAsync(IDialogContext context, IMessageActivity message, QnAMakerResults result)
        {
            var answer = result.Answers.First().Answer;
            Activity reply = ((Activity)context.Activity).CreateReply();
            if (reply.Text.equals("Not Match Found!)
                 reply.Text = "No good match in FAQ";
            await context.PostAsync(reply);
        }
```

Regards,
Francisco

**Comment by iantje31** [comment]
@FranciscoPonceGomez Thank you for your reply! I changed the code to the following:

```
using System;
using System.Configuration;
using System.Linq;
using System.Threading.Tasks;
using System.Threading;
using Microsoft.Bot.Connector;
using Microsoft.Bot.Builder.Dialogs;

using Microsoft.Bot.Builder.CognitiveServices.QnAMaker;

namespace Microsoft.Bot.Sample.QnABot
{
    // For more information about this template visit http://aka.ms/azurebots-csharp-qnamaker
    [Serializable]
    public class BasicQnAMakerDialog : QnAMakerDialog
    {
        // Go to https://qnamaker.ai and feed data, train & publish your QnA Knowledgebase.
        public BasicQnAMakerDialog() : base(new QnAMakerService(new QnAMakerAttribute(Utils.GetAppSetting("QnASubscriptionKey"), Utils.GetAppSetting("QnAKnowledgebaseId"), 'No good match in FAQ.', 0.5)))
        {}
protected override async Task RespondFromQnAMakerResultAsync(IDialogContext context, IMessageActivity message, QnAMakerResults result)
        {
            var answer = result.Answers.First().Answer;
            Activity reply = ((Activity)context.Activity).CreateReply();
            if (reply.Text.equals("Not Match Found!))
                 reply.Text = "No good match in FAQ";
            await context.PostAsync(reply);
        }
    }
}
```

After i asked something that isn't a part of the knowledge base, i still get the message "No match found!"

After that i tried changing the code to this:

```
using System;
using System.Configuration;
using System.Linq;
using System.Threading.Tasks;
using System.Threading;
using Microsoft.Bot.Connector;
using Microsoft.Bot.Builder.Dialogs;

using Microsoft.Bot.Builder.CognitiveServices.QnAMaker;

namespace Microsoft.Bot.Sample.QnABot
{
    // For more information about this template visit http://aka.ms/azurebots-csharp-qnamaker
    [Serializable]
    public class BasicQnAMakerDialog : QnAMakerDialog
    {
        // Go to https://qnamaker.ai and feed data, train & publish your QnA Knowledgebase.
        public BasicQnAMakerDialog() : base(new QnAMakerService(new QnAMakerAttribute(ConfigurationManager.AppSettings["QnASubscriptionKey"], ConfigurationManager.AppSettings["QnAKnowledgebaseId"], "No good match in FAQ")))
        {}
    protected override async Task RespondFromQnAMakerResultAsync(IDialogContext context, IMessageActivity message, QnAMakerResults result)
        {
            var answer = result.Answers.First().Answer;
            Activity reply = ((Activity)context.Activity).CreateReply();
            if (reply.Text.equals("Not Match Found!))
                 reply.Text = "No good match in FAQ";
            await context.PostAsync(reply);
        }
    }
}

```
I tried to send the message again and still got: "No match found!"

**Comment by FranciscoPonceGomez** [comment]
Hi @iantje31,

The first option doesn't work indeed. The recommended approach is the second one. It works just fine for me in local:
![image](https://user-images.githubusercontent.com/16775093/32523597-d942d432-c3d0-11e7-995a-9881ae19eed0.png)

This is the exact code that I have used:

```cs
    [Serializable]
    [QnAMakerSettings]
    public class SimpleQnADialog : QnAMakerDialog
    {
        [Serializable]
        public class QnAMakerSettingsAttribute : QnAMakerAttribute
        {
            public QnAMakerSettingsAttribute()
                : base(ConfigurationManager.AppSettings["QnASubscriptionKey"], ConfigurationManager.AppSettings["QnAKbId"], "Not good match found in FAQ", 0.5)
            {
            }
        }
    }
```

Please, bear in mind that if you are testing the final endpoint you need to redeploy your bot again.

Regards,
Francisco

**Comment by iantje31** [comment]
@FranciscoPonceGomez  thank you for your very quick response!
I changed the dialog file to exactly what you have in the Azure Bot Service. But the result is still the same:
![image](https://user-images.githubusercontent.com/32571828/32524429-ed096284-c41f-11e7-95ee-769277da7972.png)

What do you mean exactly with redeploying? Do i need to create a new App Service Plan in Azure?

**Comment by FranciscoPonceGomez** [comment]
I am assuming that you are using ABS and making your changes in the online code editor, right?
In that case, any change you make in the editor need to be redeployed. To do that, click the console icon on the left vertical menu, type "build.cmd" in the console and hit enter. This action should build and deploy your code. Now you can go back to the test window and try again.

![image](https://user-images.githubusercontent.com/16775093/32527355-813eb6a4-c3e2-11e7-8711-b6497300da4c.png)
![image](https://user-images.githubusercontent.com/16775093/32527407-b3b08608-c3e2-11e7-880a-82ee64c5d19f.png)

Regards,
Francisco

**Comment by iantje31** [comment]
@FranciscoPonceGomez it worked! Thank you so much! :D

**Comment by FranciscoPonceGomez** [comment]
Hi @iantje31,

Try restarting the web service in Azure:
![image](https://user-images.githubusercontent.com/16775093/32570847-4d572df6-c47a-11e7-8dfd-97e7e45f2c90.png)

**Comment by iantje31** [comment]
Hi @FranciscoPonceGomez 

I tried restarting the service in Azure, but the issue still occurs. 
I also tried stopping the service and starting it again, but that didn't work either.

**Comment by FranciscoPonceGomez** [comment]
Hi @iantje31,

When you delete your bot, you will lose any updates you made in your code. I believe the error you had earlier was unrelated to the account you are using. It is normally advisable to use Continuous Integration. In the "build" section of your bot service, you have the option to download your bot's code into a .zip file to open it later with Visual Studio, or add it to VSTS.
![image](https://user-images.githubusercontent.com/16775093/32582256-b30a905c-c4a2-11e7-9f20-fb5e828a2e3a.png)

It is normally easier and faster to modify your code locally, test with the [Bot Framework Emulator](https://github.com/Microsoft/BotFramework-Emulator/releases) and when you are satisfied with the results, deploy to Azure.

Let me know if that works for you.
Francisco

**Comment by iantje31** [comment]
Hi @FranciscoPonceGomez ,

I indeed think it works better if i test the bot using the bot emulator before deploying it to Azure.

I was looking for a way to remove the bot from my Microsoft Teams 1:1 chats. Because when i create a new account in my Office 365 subscription and log in to teams with it, the new message is shown. 

When i use my own account the old message appears.

**Comment by FranciscoPonceGomez** [comment]
Hi @iantje31,

Type "/deleteprofile" and send the message. Restart MS Teams. 
That should do the trick. Let me know if that worked.

Regards,
Francisco

**Comment by iantje31** [comment]
Hi @FranciscoPonceGomez,

That worked! :) Thanks a lot for your help! You guys are doing great with helping people!

Regards,
Ian

**Comment by FranciscoPonceGomez** [comment]
Awesome! You are welcome!

**Comment by JorgeCupi** [comment]
I'm having the same issue iantje31 initially had. I'm working locally and the Bot Emulator stills displays 
"No match found!"

**Comment by youssefGirgeis** [comment]
when i type build.cmd i get this:
Installing Kudu Sync
An error has occurred during web site deployment.
'npm' is not recognized as an internal or external command,
operable program or batch file.

**Comment by Rykimaruh** [comment]
I'm looking to do the same thing, except that instead of a text, the default message can be a hero card instead. Is this possible?

**Comment by nagarjuna950** [comment]
> I am assuming that you are using ABS and making your changes in the online code editor, right?
> In that case, any change you make in the editor need to be redeployed. To do that, click the console icon on the left vertical menu, type "build.cmd" in the console and hit enter. This action should build and deploy your code. Now you can go back to the test window and try again.
> 
> ![image](https://user-images.githubusercontent.com/16775093/32527355-813eb6a4-c3e2-11e7-8711-b6497300da4c.png)
> ![image](https://user-images.githubusercontent.com/16775093/32527407-b3b08608-c3e2-11e7-880a-82ee64c5d19f.png)
> 
> Regards,
> Francisco



Same thing i tried what you said but still it is not reflecting, but i'm using Nodejs.

**Comment by nagarjuna950** [comment]
Hi @FranciscoPonceGomez 
I tried same thing what you have mentioned but still, it's not reflecting(Default No Answer) and i'm using Nodejs SDK4
