### ISSUE TITLE
[Question] How to use triggerAction with RecognizerSet?

### ISSUE THREAD

**Issue by sfratini** [Microsoft/BotBuilder#3728]
* SDK Platform: Node.js
* SDK Version: 3.11.0

## Issue Description
Even when the Intent is correctly recognized, the dialog is not triggered. I am using a RecognizerSet that has a custom recognizer, a couple of regex and a LUIS recognizer. 

## Code Example

This is the first part of the custom recognizer:

  ```js
let set = new builder.IntentRecognizerSet({
        recognizeOrder: builder.RecognizeOrder.series,
        stopIfExactMatch: true
   });

   //Recognize Actions
   set.recognizer({
    recognize: function (context, done) {
    var intent = { score: 0.0 };
  
        if (context.message.text){
            //dialogAction/imBack/postBack
            if (context.message.text.indexOf("cancelBooking=") > -1)
                intent = { score: 1.0, intent: 'CancelBooking' };
        }
        if (context.message.value){
            //AdaptiveCards
        }
         
        done(null, intent);

      }
  });

 set.recognizer(new builder.RegExpRecognizer( 
        "App.Modify", { 
            en_us: /^(modify|change)/i, 
            en: /^(modify|change)/i, 
            es_es: /^(modificar|cambiar)$/i, 
            es: /^(modificar|cambiar)$/i, 
        }
    ));
      
    //Recognizers
    if (process.env.LUIS_ENABLED == true){
        console.log("Setting LUIS Recognizer con " + process.env.LUIS_ES);
        set.recognizer(new builder.LuisRecognizer(process.env.LUIS_ES));
    } else {
        console.log("LUIS Not Enabled");
    }

```

And this is my dialog:

```
bot.dialog("cancelBooking", [
    [...]
])
.triggerAction({
    matches: 'CancelBooking'
});
```

## Expected Behavior
The dialog to be triggered

## Actual Results
The defaultDialog gets triggered.

See log:

```
0|Chatbot- | Library("*")recognize() recognized: CancelBooking(1)
0|Chatbot- | Session.beginDialog(/)
0|Chatbot- | / - waterfall() step 1 of 1
0|Chatbot- | / - Session.send()
0|Chatbot- | / - Session.endDialog()
0|Chatbot- | Session.sendBatch() sending 1 message(s)
```

I tried changing the intent name in case that was a problem, or making sure the intent didn't have the same name as the dialog. I also tried making the intent a string for it to be '1.0' instead of just 1. Always the same behavior.

**Comment by nwhitmont** [comment]
@sfratini 

Try changing your triggerAction to:
```js
bot.dialog('cancel-booking', (session) => {
    // do cancel booking stuff here
})
.triggerAction({ matches: /cancelBooking=/ });
```

Using a RegEx as the input to your `matches` option will allow the dialog to detect your `imBack/postBack` message identifier without using a custom recognizer.

**Comment by sfratini** [comment]
@nwhitmont Nice alternative too. For the meantime, I'll keep using the custom recognizer since it is easier to put all the logic in that place instead of every dialog. I'll close this issue for now. Thanks!
