### ISSUE TITLE
[Question] How to set timer on "timely user response" in bot?

### ISSUE THREAD

**Issue by rjgmail88** [Microsoft/BotBuilder#3729]
## Issue Description
	User: “Hey, I need to schedule a meeting”
	Bot: “Sure, who will be attending the meeting?”
	User: “ [says nothing] “
	Bot: “Are you still there?”
	User: “ [mumbled ]”
	Bot: “Looks like we’ll have to schedule this meeting some other time. Let’s talk again soon!”

## Code Example
I am looking for code example ways to achieve above scenarios. How we can set a timer on user response and if user doesn't respond in 3-5 sec we will kill the dialog / conversation.

**Comment by FranciscoPonceGomez** [comment]
Hi @rjgmail88 ,

Are you planing to write your bot using .Net SDK or Node.js SDK?

- Francisco

**Comment by rjgmail88** [comment]
Hi Francisco,
Thanks for your help. Sorry I forgot to mention I'm writing a bot using node.js sdk. I read about Proactive messages but could not tie to my use case. Is there a way to send Proactive messages after certain time and end the conversation ? what I was thinking is there would be some param on   _builder.Prompts.text_ which I can leverage to wait for user input & if doent receive then kill the flow

ex: 
builder.Prompts.text(session, "Who will be attending this meeting?" ) 
if (results.response )
{
//continue
} else if (results.response received after 5 sec) {
//session.endConversation()
}

**Comment by rjgmail88** [comment]
Any update please

**Comment by FranciscoPonceGomez** [comment]
Hi @rjgmail88,

There are some examples in the documentation. I believe all you need to do is set a timer, show your prompt and end the conversation afterwards. If the user answers before the timer finishes you could reset it. I am going to try building a similar bot since it seems that there is something that I am missing.

```javascript
// initiate a dialog proactively 
function startProactiveDialog(address) {
    bot.beginDialog(address, "*:survey");
}

// proactiveDialog dialog
bot.dialog('proactiveDialog', function (session, args) {

    savedAddress = session.message.address;

    var message = 'Hey there, I\'m going to interrupt our conversation and start a survey in five seconds...';
    session.send(message);

    message = `You can also make me send a message by accessing: http://localhost:${server.address().port}/api/CustomWebApi`;
    session.send(message);

    setTimeout(() => {
        startProactiveDialog(savedAddress);
        session.endConversation()
    }, 5000);
});
```
https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-proactive-messages
https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node/core-proactiveMessages

**Comment by aakashkag** [comment]
var server = restify.createServer();
server.listen(process.env.port || process.env.PORT || 3978, function () {
console.log('%s listening to %s', server.name, server.url); 
});

var connector = new builder.ChatConnector({
    appId: '',
    appPassword: ''
});

var bot = new builder.UniversalBot(connector);

server.post('/api/messages', connector.listen());


bot.dialog('/', function (session) {
    if (!session.userData.TimeoutStarted) {
        session.send("I'll answer in 5 seconds");
        session.userData.TimeoutStarted = true;

        setTimeout(function() {
            session.send("Answer after 5 seconds");
            session.userData.TimeoutStarted = false;
        }, 5000);
    } else {
        session.send("Bot is busy");
    }
});

https://stackoverflow.com/questions/38990071/ms-bot-framework-nodejs-session-lifetime-and-delayed-messages
It is working for me

**Comment by vinayak99999** [comment]
I tried using above mentioned code. But even after described timeout the bot does not send any message. I am using node js SDK v 3 along with LUIS.

**Comment by vinayak99999** [comment]
I used [botbuilder-timeout](https://www.npmjs.com/package/botbuilder-timeout) Very easy and simple along with a sample.

**Comment by vaatsalya** [comment]
Hi Team,
I am developing a bot using SDK v4 using node js and trying to implement the 'timeout' functionality using this npm module but i am getting the error saying 'use' is undefined in 'this.bot.use' which is due to change in SDK v4. Is there any module that works for SDK v4?

**Comment by amruthraju87** [comment]
> Hi Team,
> I am developing a bot using SDK v4 using node js and trying to implement the 'timeout' functionality using this npm module but i am getting the error saying 'use' is undefined in 'this.bot.use' which is due to change in SDK v4. Is there any module that works for SDK v4?

@vaatsalya even  I am facing the same problem. Is there any module for SDK4. Did you solve the issue ?

**Comment by crlmas** [comment]
> I used [botbuilder-timeout](https://www.npmjs.com/package/botbuilder-timeout) Very easy and simple along with a sample.

Module for Microsoft Bot Framework to enable your bot to prompt the user if the bot detects inactivity and ultimately end the conversation if no user activity after a defined period of time.

**Comment by crlmas** [comment]
am developing a bot using SDK v4 using node js and trying to implement the 'timeout' functionality using this npm module but i am getting the error saying 'use' is undefined in 'this.bot.use' which might have been changed in SDK v4. Is there any module that works for sdk v4? Any solution

**Comment by crlmas** [comment]
> I used [botbuilder-timeout](https://www.npmjs.com/package/botbuilder-timeout) Very easy and simple along with a sample.

 am developing a bot using SDK v4 using node js and trying to implement the 'timeout' functionality using this npm module but i am getting the error saying 'use' is undefined in 'this.bot.use' which might have been changed in SDK v4. Is there any module that works for sdk v4?
