### ISSUE TITLE
how to prompt for a builtin.datetime.duration value?

### ISSUE THREAD

**Issue by plkumar** [Microsoft/BotBuilder#373]
i need to get the duration (builtin.datetime.duration) via prompt (3 hours or 30 mins, etc.), 

receiving "I didn't recognize the time you entered. Please try again." response.

"builtin.datetime.duration" works if the duration is passed via the intent.

Any help is appreciated.

**Comment by Stevenic** [comment]
So I just tried this and the [chrono](https://github.com/wanasit/chrono) parser used by the time prompt doesn't support recognizing durations like this. :(  In the short term you may need to switch to using `Prompts.text()` to capture the users input and then use RegEx's to parse these durations yourself.

**Comment by v-thgratMSGit** [comment]
Closing this issue. Please open a new issue for further discussion if necessary. @Stevenic - reopen if you would like.  Thanks!
