### ISSUE TITLE
[Question] How to use the "back channel" feature to pass data from WebChat to bot?

### ISSUE THREAD

**Issue by zxy66481** [Microsoft/BotBuilder#3734]
How to use the Web chat to pass the fetched value to the bot,Better give code hints, thank  you so much.

**Comment by FranciscoPonceGomez** [comment]
Hi @zxy66481,

Are you using .NET SDK or Node.js SDK?

Francisco

**Comment by nwhitmont** [comment]
@zxy66481 You can find more information on how to use the "backchannel" mechanism here:

https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-backchannel
