### ISSUE TITLE
[.Net SDk, Channel Config] Can't save Bot settings. Getting "Please correct the errors and try again." error in bot framework portal

### ISSUE THREAD

**Issue by ellnino50** [Microsoft/BotBuilder#3735]
## Bot Info 
* App ID: f57da6e1-6bea-438c-9a54-3b469a89694b
* SDK Platform: .NET
* SDK Version: 3.11
* Active Channels: Skype, WebChat
* Deployment Environment: Azure App Service

## Issue Description
Exactly the same as closed but unresolved Issue #3549 
Only problem is, I cannot recreate the Bot as the gcsonka, as I have a separate problem with the Application Registration Portal, almost like a login loop.

## Reproduction Steps
1. Log in to Bot Framework portal
2. Select Bot
3. Change something
4. Try and save
5. Only get "Please correct the errors and try again." error and nothing saves.

## Expected Behavior
My change to save and update on channels

## Actual Results
Constantly get "Please correct the errors and try again." error and nothing saves.

## Additional
It might be related to my email account, as I have another bot that has both my emails as owners, and that one saves perfectly.
Could the back end be validating against another email than the visible and logged in email?

Error I'm receiving:
![2017-11-08 10_15_40-syspro ken card bot](https://user-images.githubusercontent.com/33135485/32538288-2679b9b2-c46e-11e7-9287-16f92c955ec2.png)

Developer tools error:
![2017-11-08 10_16_57-clipboard](https://user-images.githubusercontent.com/33135485/32538293-2f1598ac-c46e-11e7-9486-f922b89d00ed.png)

**Comment by fanidamj** [comment]
Can you please let us know if the issue still persists?

**Comment by ellnino50** [comment]
Since all the config has moved to Azure, everything has been fine.
Thanks
