### ISSUE TITLE
[LUIS]  Getting HTTP error 429 (Too Many Requests) when LuisService query LUIS apps

### ISSUE THREAD

**Issue by CabuxaMapache** [Microsoft/BotBuilder#3736]
## Bot Info 
* App ID: Can not show it because it's an entrerprise private bot.
* SDK Platform: .NET
* SDK Version: 3.11.0
* Active Channels: Direct Line
* Deployment Environment: other: Self hosted (enterprise)

## Issue Description
I'm implementing DialogFactory strategy as specified here: [stackoverflow](https://stackoverflow.com/questions/40399973/how-do-i-implement-multiple-luis-dialogs-on-a-single-bot-using-the-bot-framework). I have 4 LUIS apps and 4 different dialogs (that inherhit from "BaseDialog<R>") and for a given query (written by the user) I execute the "CanHandle" method on each of them. I'm testing it in the emulator (v3.5.33) and localhost (no ngrok).

- My root dialog executes the same code as [here](https://github.com/Microsoft/AzureBot/blob/master/AzureBot/Dialogs/RootDialog.cs#L28) for the "None" intent.
- DialogFactory class is implemented from [here](https://github.com/Microsoft/AzureBot/blob/master/AzureBot/Dialogs/DialogFactory.cs) (with my own dialogs)
- And finally my "BaseDialog" is in the code example above.

## Code Example
`	
        using Microsoft.Bot.Builder.Dialogs;
	using System.Linq;
	using System.Threading;
	using System.Threading.Tasks;
	using Microsoft.Bot.Builder.Luis;
	using System;

	namespace CodeBot.Dialogs
	{
		[Serializable]
		public class BaseDialog<R> : LuisDialog<R>
		{
			public BaseDialog(LuisModelAttribute luisModel) : base(new LuisService(luisModel))
			{
			}

			public async Task<bool> CanHandle(string query)
			{
				try
				{
					var tasks = services.Select(s => s.QueryAsync(query, CancellationToken.None)).ToArray();
					var results = await Task.WhenAll(tasks); <-- Error!!!

					var winners = from result in results.Select((value, index) => new { value, index })
								  let resultWinner = BestIntentFrom(result.value)
								  where resultWinner != null
								  select new LuisServiceResult(result.value, resultWinner, this.services[result.index]);

					var winner = this.BestResultFrom(winners);

					return winner != null && !winner.BestIntent.Intent.Equals(Constants.NONE, StringComparison.InvariantCultureIgnoreCase);
				}
				catch(Exception e)
				{
					System.Diagnostics.Debug.WriteLine($"CanHandle error: {e.Message}");
					return false;
				}
			}
		}
	}`

## Reproduction Steps
1. 
2.
3.

## Expected Behavior
The method should not fail and return true if the dialog can handle the query

## Actual Results
Http error: 429 (Too Many Requests) when LuisService query LUIS app.

**Comment by stevengum97** [comment]
@CabuxaMapache, if you're using four different LUIS applications concurrently inside of a chatbot, you should set up individual keys for each application. Each Basic Tier key has a throttling limit of 50TPS. In the case of your application, if you use one key for the four apps, you can have only twelve calls (per app) every second. After that you'll start receiving the 429 error code.

As mentioned above the workaround is to generate three additional keys, so you have one key (and 50 TPS) per application.

**Comment by stevengum97** [comment]
@CabuxaMapache, if you're using four different LUIS applications concurrently inside of a chatbot, you should set up individual keys for each application. Each Basic Tier key has a throttling limit of 50TPS. In the case of your application, if you use one key for the four apps, you can have only twelve calls (per app) every second. After that you'll start receiving the 429 error code.

As mentioned above the workaround is to generate three additional keys, so you have one key (and 50 TPS) per application.

**Comment by CabuxaMapache** [comment]
Thank you very much for the info. One point I don't understand is why I'm reaching that limit if I'm only making 4 querys to LUIS (one for each dialog->app).

**Comment by stevengum97** [comment]
I might have misunderstood your layout of LUIS dialogs... Some developers like to call multiple LUIS apps in parallel when processing a user's utterance, which would very quickly hit the rate limit. 

If each LUIS application has its own dialog, but the same key, it's still very likely to hit the rate limit as well. 

For your LUIS applications did you hit the limit on your intents and entities and need to split up one app into four? Is it for easier management?

**Comment by CabuxaMapache** [comment]
Yes, it is for reach the limits and for an easy structure of the bot. Thanks for your info!
