### ISSUE TITLE
[Question] Is there any Bot Builder Management API?

### ISSUE THREAD

**Issue by midhunCherrylabs** [Microsoft/BotBuilder#3737]
is it possible to  create and update chat bot and channels pragmatically

**Comment by FranciscoPonceGomez** [comment]
Hi @midhunCherrylabs,

It is not possible to create a bot and configure its channels programmatically. The best way to do this is by going into the dev portal (https://dev.botframework.com).

Regards,
Francisco

**Comment by midhunCherrylabs** [comment]
@FranciscoPonceGomez Thanks for your response, it is sad :( ,   Microsoft have any road map for releasing management API for bot-framework

**Comment by FranciscoPonceGomez** [comment]
Hi @midhunCherrylabs,

There are no plans at the moment for it. I will get back to you if I hear any news.

Closing...
Francisco

**Comment by midhunCherrylabs** [comment]
@FranciscoPonceGomez thanks 

i hope those Services will be available shortly ,we have a system that working multi-tenant way along with chat bot framework , any method we can contribute or make build it
