### ISSUE TITLE
PromptDialog.Confirm re-prompts when using message actions 

### ISSUE THREAD

**Issue by tkbox9** [Microsoft/BotBuilder#374]
I'm seeing an odd behaviour by using PromptDialog.Confirm with messages containing actions. Basically, after responding with a yes to the Prompt. A new message is shown with two actions (Add to Basket and View Website). So far that's expected. However, when the user clicks on "Add to Basket" the message "add item:XXX" is sent, however, it seems the Bot is still expecting a YES or NO from the previous Prompt. 

So every time the bot re-prompt with the following message:
"I didn't understand. Say something in reply. Hey would you like to see what's on sale? (yes or no)"  

```
        [LuisIntent("robobot.greetings")]
        public async Task Greeting(IDialogContext context, LuisResult result)
        {
            var message = $"Hey would you like to see what's on sale?";
            PromptDialog.Confirm(context, OnGreeting, message);
        }

    private async Task OnGreeting(IDialogContext context, IAwaitable<bool> result)
        {
            if (await result)
                await ShowOnSale(context);
            else
                await TellJoke(context);
            context.Wait(MessageReceived);
        }


       private async Task ShowOnSale(IDialogContext context)
        {
            var message = context.MakeMessage().CreateReplyMessage("Check this on sale:");
            var item = _data.Take(1).Single();

            message.Attachments = new List<Attachment>();
            var attach = new Attachment()
            {
                Title = item.Title,
                Text = item.Text,

                ContentUrl = item.ContentUrl,
                ContentType = item.ContentType,
                Actions = new List<Bot.Action>()
                {
                    new Bot.Action() {Title = "Add to Basket :)", Message = "add item:" + item.Id},
                    new Bot.Action() {Title = "View website", Message = "website", Url = item.Link}
                }
            };

            message.Attachments.Add(attach);
            await context.PostAsync(message);
        }
```

@msft-shahins or anyone have any ideas what could that be?

**Comment by msft-shahins** [comment]
it is probably because of the `context.Wait(MessageReceived);` that you have in your `OnGreetings` function and not handling the message `Message = "add item:" + item.Id` in your Luis model correctly. when the button is clicked.

**Comment by tkbox9** [comment]
@msft-shahins Could you advise the proper usage for that? Also, I don't see nothing wrong with my model since everything is returned as expected. 

https://api.projectoxford.ai/luis/v1/application?id=8dc62ab1-f721-42bb-9111-28c3b285f239&subscription-key=b488d5166ef14ce794ea54349932e524&q=add%20item%20to%20my%20basket%20sneaker%20id%3A00001

Many thanks.
