### ISSUE TITLE
How to implement Chat logs?

### ISSUE THREAD

**Issue by neetgupta7** [Microsoft/BotBuilder#3741]
* SDK Platform: .NET 
* SDK Version: 3.9.1
* Active Channels: Web Chat, Cortana
* Deployment Environment: Azure App Service

## Issue Description
Can somebody please tell me how should we log chat conversation.

**Comment by FranciscoPonceGomez** [comment]
Hi @neetgupta7,

You need to use Microsoft.Bot.Builder.History.IActivityLogger Interface:

```cs

public class DebugActivityLogger : IActivityLogger 
{     
    public async Task LogAsync(IActivity activity)     
    {         
        Debug.WriteLine($"From:{activity.From.Id} - To:{activity.Recipient.Id} - Message {activity.AsMessageActivity()?.Text}");     
     }
}
```
and register in AutoFact

```cs
var builder = new ContainerBuilder(); builder.RegisterType<DebugActivityLogger>().AsImplementedInterfaces().InstancePerDependency(); builder.Update(Conversation.Container);
```

Regards,
Francisco

**Comment by neetgupta7** [comment]
@FranciscoPonceGomez Thanks for this information. I hope this will take care of both types messages i.e. coming from the user and going from the bot.

**Comment by FranciscoPonceGomez** [comment]
Awesome! I am going to close this for now. Let me know if you have more problems and I will reopen,

Cheers,
Francisco
