### ISSUE TITLE
Human Integration in Bot

### ISSUE THREAD

**Issue by Malith1994124** [Microsoft/BotBuilder#3744]
I create a travel bot using luis.ai in C#. In my bot if user ask a question and if bot cannot answer the question i need  that question send to travel agent (human) to answer. How i can do it?

**Comment by papaioannous** [comment]
If you use LUIS then there is an intent called NONE. You could use this to get the text that the user asked and send it to the travel agent.

**Comment by FranciscoPonceGomez** [comment]
Hi @Malith1994124,

We call that scenario "human handoff". There are some resources that you can check on.
This reference explain the design patter for the scenario:
https://docs.microsoft.com/en-us/bot-framework/bot-design-pattern-handoff-human
This is an example in Node.js:
https://www.microsoft.com/developerblog/2017/06/30/bot-to-human-handover-in-node-js/
And another example in C#:
https://blogs.msdn.microsoft.com/jamiedalton/2017/08/10/microsoft-bot-framework-handing-off-to-a-human-for-agentssupervisors-with-c-and-the-botbuilder-sdk/

Regards,
Francisco
