### ISSUE TITLE
[Question] WebChat always executes the default dialog?

### ISSUE THREAD

**Issue by sfratini** [Microsoft/BotBuilder#3745]
* App ID: 255bf592-c724-4afd-881c-1087574afc51
* SDK Platform: Node.JS
* SDK Version: 3.11.0
* Active Channels: Webchat
* Deployment Environment: ngrok / Emulator / Webchat (embed)

## Issue Description
Bot seems to ignore every recognizer and only displays defaultDialog

## Reproduction Steps
1. Test locally with emulator or remotely with emulator + ngrok, everything runs OK. 
2. Either Test from the Bot console or running the bot with the webchat embed url keeps returning the same dialog.

## Expected Behavior
Bot recognizes any of my recognizer set, which is a customer recognizer, some regexs and a LUIS recognizer. 

## Actual Results

My setup is:
- Nginx reverse proxy
- pm2 cluster management
- node 8.8.1 (Needed to handle promises)

I also added NODE_DEBUG='botbuilder' to enable some logs and this is my output:

###Normally with the webchat embed URL:

```
10|Chatbot | restify listening to http://[::]:4101
10|Chatbot | ChatConnector: message received.
10|Chatbot | localizer.load(es-AR)
10|Chatbot | localizer.loadSystemResources(es-AR) - Couldn't find file: /projects/QA/appointment-bot/node_modules/botbuilder/lib/locale/es-AR/BotBuilder.json
10|Chatbot | UniversalBot("*") routing "quiero un turno" from "webchat"
10|Chatbot | Session.beginDialog(/)
10|Chatbot | / - waterfall() step 1 of 1
10|Chatbot | Ejecutando Base
10|Chatbot | / - Session.send()
10|Chatbot | / - Session.endDialog()
10|Chatbot | Session.sendBatch() sending 1 message(s)
10|Chatbot | ChatConnector: sending message.
```

Note: "quiero un turno" is an utterance in Luis that normally matches to an intent. Locally it works great. 

And this is what happens if I use my emulator, pointing to the same endpoint, using ngrok with the same appID and appPassword:

```
10|Chatbot | ChatConnector: message received.
10|Chatbot | localizer.load(es)
10|Chatbot | UniversalBot("*") routing "quiero un turno" from "emulator"
10|Chatbot | Library("*")recognize() recognized: App.Request(0.989332259)
10|Chatbot | Library("*").findRoutes() explanation:
10|Chatbot |    GlobalAction(0.989332259)
10|Chatbot | Session.beginDialog(*:request)
10|Chatbot | request - waterfall() step 1 of 8
10|Chatbot | request - Session.send()
10|Chatbot | request - Session.beginDialog(requestUserId)
10|Chatbot | .requestUserId - waterfall() step 1 of 2
10|Chatbot | .requestUserId - Session.beginDialog(BotBuilder:prompt-text)
10|Chatbot | ..BotBuilder:prompt-text - Session.send()
10|Chatbot | ..BotBuilder:prompt-text - Session.sendBatch() sending 2 message(s)
10|Chatbot | ChatConnector: sending message.
```

A previous version of this chatbot was working fine. The only thing I did was adding LUIS and some recognizer set, which again, works perfect locally or with an emulator + ngrok.

**Comment by FranciscoPonceGomez** [comment]
Hi @sfratini,

Interesting. I wonder if why when using webchat the bot tries to load the "es-AR" localizer (with error) but when using the emulator the bot tries to fetch the "es" localizer (with no error).
```
10|Chatbot | localizer.load(es-AR)
10|Chatbot | localizer.loadSystemResources(es-AR) - Couldn't find file: /projects/QA/appointment-bot/node_modules/botbuilder/lib/locale/es-AR/BotBuilder.json
```
Sometimes with a bot can't recognize a sentence in a particular channel but can recognize it in the emulator or the test window, is due to the channel adding some extra characters to the message.

I will investigate this. @nwhitmont, you have worked in the latest version of the SDK. Do you know what could be causing this problem?

Regards,
Francisco

**Comment by sfratini** [comment]
So, I found the issue. The thing is the locale. As the logs shows, the locale being recognized is es-AR which is fine thing I am in Argentina. 

If I put the same locale in the emulator I can reproduce the issue. 

Now, I already had this:

 set.recognizer(new builder.RegExpRecognizer( 
                "App.Request", { 
                    en_us: /^(request)/i, 
                    en: /^(request)/i, 
                    es_es: /^solicitar/i, 
                    es: /^solicitar/i, 
                }
            ));

Which I assumed it was covering the es_* locales. 

So, if that is intended, then I guess it is a bug.  If not, how can I make a "catch all spanish" locale?

**Comment by sfratini** [comment]
@FranciscoPonceGomez  Definitely a bug. I saw that the code tries the locale and if not, it sees if I have a '*' catch all locale. I wil try to solve it like this however it the recognizer does not find a key in the recognizer it won't keep trying the rest of the set. 

See here:

  ```
let set = new builder.IntentRecognizerSet({
                recognizeOrder: builder.RecognizeOrder.series,
                stopIfExactMatch: true
           });

 set.recognizer(new builder.RegExpRecognizer( 
                "App.Request", { 
                    'en_*': /^(request)/i, 
                    //en: /^(request)/i, 
                    'es_*': /^solicitar/i, 
                    //es: /^solicitar/i, 
                }
            ));
        
            set.recognizer(new builder.RegExpRecognizer( 
                "App.Cancel", { 
                    en_us: /^(cancel|check|verify)/i, 
                    en: /^(cancel|check|verify)/i, 
                    es_es: /^(consultar|cancelar)/i, 
                    es: /^(consultar|cancelar)$/i, 
                }
            ));

            bot.recognizer(set);
```

Logs:

Setup:
Emulator
Locally
Locale: es_es
First recognizer does not have key matching this locale (See that I put a locale that won't match anything, since it is 'en_*'):

```


1|Chatbot- | UniversalBot("*") routing "quiero un turno" from "emulator"
1|Chatbot- | context locale: es_es
1|Chatbot- | expresisons: { 'en_*': /^(request)/i, 'es_*': /^solicitar/i }
1|Chatbot- | Session.beginDialog(/)
1|Chatbot- | / - waterfall() step 1 of 1
1|Chatbot- | / - Session.send()
1|Chatbot- | / - Session.endDialog()
```

Setup 2:
Emulator
Locally
Locale es_es
Recognizer has matching key:

```

1|Chatbot- | UniversalBot("*") routing "quiero un turno" from "emulator"
1|Chatbot- | context locale: es_es
1|Chatbot- | expresisons: { en_en: /^(request)/i, es_es: /^solicitar/i }
1|Chatbot- | context locale: es_es
1|Chatbot- | expresisons: { en_us: /^(cancel|check|verify)/i,
1|Chatbot- |   en: /^(cancel|check|verify)/i,
1|Chatbot- |   es_es: /^(consultar|cancelar)/i,
1|Chatbot- |   es: /^(consultar|cancelar)$/i }
1|Chatbot- | context locale: es_es
1|Chatbot- | expresisons: { en_us: /^(cancel|check|verify)/i,
1|Chatbot- |   en: /^(cancel|check|verify)/i,
1|Chatbot- |   es_es: /^(consultar|cancelar)/i,
1|Chatbot- |   es: /^(consultar|cancelar)$/i }
1|Chatbot- | context locale: es_es
1|Chatbot- | expresisons: { en_us: /^(modify|change)/i,
1|Chatbot- |   en: /^(modify|change)/i,
1|Chatbot- |   es_es: /^(modificar|cambiar)/i,
1|Chatbot- |   es: /^(modificar|cambiar)/i }
1|Chatbot- | { query: 'quiero un turno',
1|Chatbot- |   topScoringIntent: { intent: 'App.Request', score: 0.989332259 },
1|Chatbot- |   intents:
1|Chatbot- |    [ { intent: 'App.Request', score: 0.989332259 },
1|Chatbot- |      { intent: 'App.Cancel', score: 0.01496889 },
1|Chatbot- |      { intent: 'App.Query', score: 0.009798814 },
1|Chatbot- |      { intent: 'None', score: 0.0048374827 },
1|Chatbot- |      { intent: 'App.RequestStaffAuto', score: 0.003447316 } ],
1|Chatbot- |   entities: [] }
1|Chatbot- | Library("*")recognize() recognized: App.Request(0.989332259)
```

See that the second one tried the rest of the recognizers. It would be excellent if the recognizers could support not only a catch all like '*' but a catch all by language like "es_*" or "en_*"

Thanks!
