### ISSUE TITLE
Prevent spam

### ISSUE THREAD

**Issue by xjose97x** [Microsoft/BotBuilder#3747]
Hello everyone!

I was wondering if any of you have a strategy to prevent a user spamming your bot. There are services like LUIS that cost by how much you use it. I think LUIS costs $0.75 per 1,000 transactions. 

I don't want a scenario where a user spams my bot making LUIS or other similar services cost way more.
Is anyone taking a measure for this? 

Thanks!

**Comment by FranciscoPonceGomez** [comment]
Hi @xjose97x,

We don't implement any kind of throttling for our users. You can implement it yourself in your bot easily using any of the multiple standard libraries for throttling.

Cheers.
Francisco

**Comment by JasonSowers** [comment]
@xjose97x Great question!  Let's leave this open as a discussion thread as some people may have excellent solutions for this already.

**Comment by xjose97x** [comment]
Activities have a property named timestamp. I'm considering a strategy in which I check every x messages (maybe 50 or around that) what's been the mean timestamp between each of those and if it's been too low, then ban the user for x minutes. 

This is not yet a priority for our project, but definitely something that every production bot must handle.

**Comment by sgellock** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
