### ISSUE TITLE
[Skype for Business, .NetSDK] Not able to retrieve the state, for the first request (SFB channel only)

### ISSUE THREAD

**Issue by sarunprasath** [Microsoft/BotBuilder#3748]
## Bot Info 
* App ID: 
* SDK Platform:  .NET 
* SDK Version: 3.11.0
* Active Channels: SFB
* Deployment Environment: Azure App Service, 

## Issue Description
Bot is not able to get the state from the state store, When the conversation is initiated as below

![image](https://user-images.githubusercontent.com/33538208/32644766-a157f7aa-c61e-11e7-928a-b85ce313f2c5.png)

My name is stored in the User data state in the previous session, but it can get the state in the 2 response only? This scenario only happening in the SFB channel

## Expected Behavior
The bot has to get the state from the first request

## Actual Results
The bot is getting the state only from the second request

**Comment by sgellock** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
