### ISSUE TITLE
[Skype for Business] Proactive messages not getting sent

### ISSUE THREAD

**Issue by anujaparikh23** [Microsoft/BotBuilder#3749]
## Bot Info 
* App ID: f079f4c0-39a6-4825-81e2-0da3a7c13b53
* SDK Platform: 
* Active Channels: 
* Deployment Environment: 

## Issue Description
We are unable to send a proactive message to the user on SFB when the current conversation window inside SFB is closed.

## Code Example

Here I am trying to send a proactive message to the user on a trigger. The trigger here is that message here is to be sent at a particular time. (Ofcourse the time here is hardcoded for testing purpose, I keep changing the time according to when I am running the code.)

```
//Function for Proactive Message
function sendProactiveMessage(address) {
    var msg = new builder.Message().address(address);
    msg.text('Hello, this is a notification');
    msg.textLocale('en-US');
    bot.send(msg);
}

//I have saved the address of the user, by sesssion.message.address, into this JSON file

fs.readFile('SfbAddress.json',function(err,savedAddress){
    if(err) throw err;
console.log("Saved:\n",savedAddress);
var parseJson = JSON.parse(savedAddress);
//parseJson = JSON.stringify(parseJson);
console.log("Parsed Json:\n",parseJson);
var date = new Date(2017, 10, 9, 12, 23, 0);    //Time at which the message should be sent

var j = schedule.scheduleJob(date, function(){
  console.log('Proactive message sent');
sendProactiveMessage(parseJson)    //Sending the proactive message
});
});
```

## Actual Results
The proactive message works when:
1) Have a conversation between the user and the bot, save the address. 
2) Then use the above code to send proactive message to the user.

The proactive message doesn't work when:
1) The conversation window is closed.
2) After that if I run the above piece of code where in I read the json file where I have previously saved the user address.
3) But in that case i get an error as below:

```
Error: Request to 'https://webpoolsg20r04.infra.lync.com/platformservice/tgt-19654cb966085e1ab4f2cbb6487f9353/botframework/v3/conversations/OWJhOGY3MjEjc2lwOmNhbGxzY2hlZHVsZUBiYWlhaS5vbm1pY3Jvc29mdC5jb20%3D/activities/02740117-635e-4159-8c75-b0dc64b82ff2' failed: [500] Internal Server Error
    at Request._callback (/home/cts565637/Anuja/NovartisBot/node_modules/botbuilder/lib/bots/ChatConnector.js:537:46)
    at Request.self.callback (/home/cts565637/Anuja/NovartisBot/node_modules/request/request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/home/cts565637/Anuja/NovartisBot/node_modules/request/request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/home/cts565637/Anuja/NovartisBot/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)

```

## Expected Behavior
I expect it to work, even when the conversation window is closed or when SFB user is offline. Because thats how Proactive messaging should work.

**Comment by JasonSowers** [comment]
This is a feature request for Skype for Business.  We do not have control over the channels the bot framework connects to, not even the internal Microsoft ones like Skype and Skype for Business.  This is outside of the scope of this forum.
