### ISSUE TITLE
LUIS timeout

### ISSUE THREAD

**Issue by rlbeckett** [Microsoft/BotBuilder#375]
LUIS seems to be having some problems at the moment and I can't find a way for my Slack bot to handle it.  In the last few days LUIS has gone down several times and when this happens, I'm not getting any error messages, console logs or anything.  I can talk to the bot, it hears and sends the message to LUIS for recognition.  Slack shows the bot as 'typing' for a few seconds and then nothing else happens.  

Is there a way to catch a timeout from the LUIS service and send a message to the user on Slack so they know something's wrong and don't keep talking to the bot?  I've tried looking through the source code and there does seem to be error handling in there. However, I can't see anything that will enable me to send a message to Slack telling anyone using it that the bot is temporarily a brainless zombiebot.

**Comment by Stevenic** [comment]
I'm assuming this is using Node.js? Are you not seeing a error logged to the console?

**Comment by rlbeckett** [comment]
Yes I'm using Node.js and I wasn't seeing anything in the console.  After I posted I noticed that there had been a new release which mentions that LUISDialog 'on' had been stopped from eating exceptions (this might have been the cause) so I've installed that now.  However LUIS was back up and running at that point so I haven't managed to test it yet.

**Comment by Stevenic** [comment]
That was definitely an issue.  You should be at least getting an error now. There's not an easy way to report this to users right now but there are some changes coming that may help that.

**Comment by rlbeckett** [comment]
I haven't been able to easily simulate LUIS going down on my development machine so I'll can't even tell you if I get messages. Until LUIS goes down I'll have to put the issue on the backburner.  That said, I'll keep a close watch on your release notes for any helpful changes. 

Thanks for the info.

**Comment by Stevenic** [comment]
I can't mimic this either but there was definitely an issue with LuisDialog eating exceptions. Ive tested that it doesn't do that anymore.

**Comment by mattlanham** [comment]
I'm also having issues with timeout that look as though they are related to using LuisDialog, I'm going to create a quick library to see if accessing Luis via rest works better

**Comment by Stevenic** [comment]
@mattlanham I just use REST under the hood.  You can look at the code for `LuisDialog.recognize()` and see that it only goes through about 10 lines of code while calling the REST API.  The issues are on their side.  Are you at least getting an error?

**Comment by mattlanham** [comment]
I'm getting nothing, I have it deployed on Heroku, and it's just timing out after 30 seconds, but hitting luis directly seems to be fine - so not 100% sure what's going wrong. 

I will have a look at the code and see if I can add some additional debugging console logs to see if I can narrow done where it's getting to @Stevenic

**Comment by Stevenic** [comment]
thanks much

**Comment by mattlanham** [comment]
@Stevenic Is there a function to reset the session in node?

**Comment by mattlanham** [comment]
So, I think i've narrowed my issue down to not calling session.endDialog(); at the end of every function invoked by Luis - so far now seems to be working correctly and not timing out.

**Comment by Stevenic** [comment]
Ok good... I can see how it could look like you're hanging in that situation.

**Comment by rlbeckett** [comment]
LUIS just seems to have gone down again for a few minutes and I quickly logged everything I could in the terminal.  At the time, the LUIS query url simply returned a 503 or kept loading. 
Whilst this was happening, sending a first message to the bot elicited no reply, a second message crashed the server with the logs showing 
```
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: Intent recognition error: Unexpected token <
    at c:\dev\project\node_modules\botbuilder\lib\dialogs\IntentDialog.js:41:44
    at Request._callback (c:\dev\projectBlatter\node_modules\botbuilder\lib\dialogs\LuisDialog.js:41:21)
    at Request.self.callback (c:\dev\project\node_modules\request\request.js:200:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (c:\dev\project\node_modules\request\request.js:1067:10)
    at emitOne (events.js:95:20)
    at Request.emit (events.js:182:7)
    at IncomingMessage.<anonymous> (c:\dev\project\node_modules\request\request.js:988:12)
    at emitNone (events.js:85:20)
```

Should the botbuilder be handling this error or should my code and, if so, what should I be wrapping in a try/catch block?

**Comment by Stevenic** [comment]
We talked and we're going to add a global error handler that fires in the scope of a conversation which gives you a chance to tell your user that the bot is having problems. Will provide a default implementation that 1) resets the dialog stack for the conversation so that the user isn't stuck. and 2) sends a generic "the bot is currently having problems" error message,

May be a couple of weeks before we get this added though,

**Comment by v-thgratMSGit** [comment]
Closing this issue due to age. @rlbeckett - please open a new issue if this issue is not fixed and needs further discussion. @Stevenic - reopen if necessary. Thanks!
