### ISSUE TITLE
Reply Telegram message Node

### ISSUE THREAD

**Issue by MohammadMDSA** [Microsoft/BotBuilder#3752]
## Bot Info 
* SDK Platform: Node.js
* SDK Version: 3.11.0
* Active Channels: Telegram
## Issue Description
Is it possible to reply a message with bot in Telegram with NodeJS SDK?

**Comment by FranciscoPonceGomez** [comment]
Hi @MohammadMDSA,

This looks like a duplicated of your other issue. 
Please, state all your related errors in the same thread.

I will close this one.

Thanks,
Francisco
