### ISSUE TITLE
[Telegram] Is it possible to edit sent messages?

### ISSUE THREAD

**Issue by MohammadMDSA** [Microsoft/BotBuilder#3753]
## Bot Info 
* SDK Platform: Node.js
* SDK Version: 3.11.0
* Active Channels: Telegram
## Issue Description
Is it possible to edit a message bot sent in Telegram with NodeJS SDK?

**Comment by nwhitmont** [comment]
@MohammadMDSA Great question. 

You can edit a "sent" message using the Telegram Bot API. For more information, check out the interface for `editMessageText`:
https://core.telegram.org/bots/api#editmessagetext

Then use the `channelData` property of your bot's message to send this data to the Telegram conversation.
