### ISSUE TITLE
[WebChat] How to call a function on page reload?

### ISSUE THREAD

**Issue by pardeshibhushan** [Microsoft/BotBuilder#3754]
## Bot Info 
 SDK Platform:  Node.js 
 Active Channels: Webchat
 Deployment Environment: Azure Webapp

## Issue Description
To send chat logs when a web page is refreshed using refresh button,f5 key or when a window is closed.Is it possible to detect page refresh or call an event in node.js when a page is refreshed .

**Comment by nwhitmont** [comment]
@pardeshibhushan Great question.  You can solve this using general knowledge of the HTML DOM and `window` events. 

For more information, see:
- https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeunload
- https://stackoverflow.com/questions/11285908/call-a-function-on-page-refresh-using-javascript
