### ISSUE TITLE
[QnA Maker] Service is not responding with correct answers?

### ISSUE THREAD

**Issue by Naveen-Yaragall** [Microsoft/BotBuilder#3755]
## Bot Info 
* SDK Platform: Node.js 
* Active Channels: Webchat
* Deployment Environment:  Azure Web App Service

## Issue Description
QnAmaker responding with the incorrect Answers.

## Expected Behavior
Bot responds with the correct answer even if any number of users chat with the bot simulteneously.

## Actual Results
When the number of users using the bot increases( say more than 5) then the QnAmaker either responds 
1. With the wrong answer when using with REST Api.
2.With No Answer when using with Standard QnAMaker Dialog.

**Comment by nwhitmont** [comment]
@Naveen-Yaragall Please provide your QnA Maker App ID so we can investigate the issue.

**Comment by Naveen-Yaragall** [comment]
Hi All,

Thanks for follow up.
We found the root cause of the issue, whenever the number of the users using the bot increases the bot did not respond, this was due to rate limit of 10 Calls per minute.

Thank you.

**Comment by JasonSowers** [comment]
Glad you found the problem, good luck!
