### ISSUE TITLE
[Question] What is clEntityId value for Get closed list entity info in LUIS API 

### ISSUE THREAD

**Issue by GauravDhavale** [Microsoft/BotBuilder#3759]
## Issue Description
My HTTP request URL is https://westus.api.cognitive.microsoft.com/luis/api/v2.0/apps/5290faa2-2579-4547-815c-ae52ae35d7d6/versions/0.1/closedlists/DetailsType 

where I used clEntityId as a custom entity name of a type List. When I run this using API testing Console I get the error as "Message": "The request is invalid."

May I know where I can find this id or there is something else that is causing this error?

## Reproduction Steps
![image](https://user-images.githubusercontent.com/24877974/32673229-f78689b2-c613-11e7-80ac-b51f77c800a3.png)

## Expected Behavior

I'm expecting Entity list in JSON format in my node js application in below format [sample]
![image](https://user-images.githubusercontent.com/24877974/32673353-83428514-c614-11e7-877e-fb2acc0dee94.png)

## Actual Results

![image](https://user-images.githubusercontent.com/24877974/32673275-2946f374-c614-11e7-92ab-ca2ba42a2fd8.png)

**Comment by stevengum97** [comment]
@GauravDhavale, you're receiving this response because the API is expecting a GUID like e58c####-####-####-####-############, not the List Entity's name. To get the GUID for your DetailsType entity, you can use this [programmatic API](https://westus.dev.cognitive.microsoft.com/docs/services/5890b47c39e2bb17b84a55ff/operations/5890b47c39e2bb052c5b9c0f/console) to retrieve all the entities' GUIDs for your current version.

**Comment by GauravDhavale** [comment]
Hi, @stevengum97 I tried the given API reference but it gives me the GUID of the only list of entities of simple type. I want the list Entity type closed list entities. How can I find the GUID for closed list entities? 

What I got : 
![image](https://user-images.githubusercontent.com/24877974/32681910-71b9355e-c637-11e7-8b30-65768daf89f3.png)

**Comment by stevengum97** [comment]
@GauravDhavale sorry about that, try this API instead [models - Get application version closed list infos](https://westus.dev.cognitive.microsoft.com/docs/services/5890b47c39e2bb17b84a55ff/operations/5890b47c39e2bb052c5b9c15/console).

**Comment by GauravDhavale** [comment]
Thanks. Got the GUID as well as the closed entity list.
