### ISSUE TITLE
Validating user input in form flow with regex specified in Json schema

### ISSUE THREAD

**Issue by manu4rhyme** [Microsoft/BotBuilder#376]
As also given in the sandwich bot example, for numeric inputs, we can specify the minimum and maximum in the json schema, 

    "age": {
      "type": [
        "number",
        "null"
      ],
      "minimum": 18,
      "maximum": 150

this automatically expects a number between 18 and 150,

Similarly , I would like to know if its possible to check input strings with regex specified in the schema, something like ,

    "zipcode": {
      "type": [
        "string",
        "null"
      ],
      "pattern": "[0-9]{6}"

where pattern is also a Json schema keyword if I'm not mistaken. It should accept a 6 digit number, but the above thing doesn't really work, and it accepts any string.

I looked through the documentation and didn't find anything related to this. I need my form filler to be generic, i.e. there could be many different forms with different fields,  all working from the same piece of code but with different form schemas. So, I cannot write custom validation function for fields as they are form dependant.

So is there a way to match user input with a regex that is specified in the Json schema??
If not, I think it would be a great thing to add , since with regex we can check a lot of different inputs!!

**Comment by chrimc62** [comment]
This is a good idea and I will look into adding it.  I've also been thinking I should allow confirmation and messages in JSON schema as well...

**Comment by manu4rhyme** [comment]
Features like these would be of great help in my project, thanks a lot !

**Comment by chrimc62** [comment]
OK, I have added this and it will be in our next release.  Thanks for the suggestion!
