### ISSUE TITLE
[Question] Why does Prompts.Choice dialog interpret a triggerAction message as an attempt to make a choice?

### ISSUE THREAD

**Issue by anvad** [Microsoft/BotBuilder#3760]
## Bot Info 
* SDK Platform: Node.js
* SDK Version: 3.11
* Active Channels: Direct Line, Web Chat
* Deployment Environment: AWS Lambda

## Issue Description
I've setup a `triggerAction` with the `onSelectAction` starting a new dialog. E.g. a trigger action for global help- triggered by message: "global help"
Now, if the user is in the middle of a `Prompts.choice` dialog and types in "global help", the user is taken into the help dialog and later returned to the `Prompts.choice` dialog which presents the `retryPrompt` instead of the original prompt.
Looking at the code, it appears the `Prompts.choice` dialog received the "global help" message first (before `triggerAction` caught it) and processed the message by incrementing `dialogData.turns`.
So, the "global help" message used up one of the retry attempts!

Right now, I am getting around this by decrementing the `dialogData.turns` in my `onSelectAction` function.
e.g.
```javascript
.triggerAction({
        matches: /^global help/i,
        onSelectAction: (session: builder.Session, args, next) => {
            //here, check if we were in the middle of a prompt and reduce the retry count by one
            if (session.dialogData && session.dialogData.turns && typeof session.dialogData.turns === 'number') {
                session.dialogData.turns--;
            }
            session.beginDialog(args.action, args)
        }
    })
```
This is obviously non-optimal as I've become dependent on the internal implementation details of the SDK's Prompts dialog.

## Code Example
```javascript
"use strict";
const builder = require('botbuilder');
const restify = require('restify');

const connector = new builder.ChatConnector({
    appId: process.env.MICROSOFT_APP_ID,
    appPassword: process.env.MICROSOFT_APP_PASSWORD
});

const bot = new builder.UniversalBot(connector, [
    function (session) {
        builder.Prompts.choice(session, "Please make a selection:", [`Choice 1`, `Choice 2`], {
            listStyle: builder.ListStyle.button,
            maxRetries: 0,
        });
    },
    function (session, results) {
        session.send(`Did you already make a choice? The results object passed in to me is: \`${JSON.stringify(results)}\``);
    }
]);

bot.dialog('ghelp', [
    (session, args, next) => {
        session.endDialog("This is global help. Now returning to where we left off. If all goes well, you'll be see the prompt to choose one of the presented options.");
    }
])
    .triggerAction({
        matches: /^global help/i,
        onSelectAction: (session, args, next) => {
            session.beginDialog(args.action, args);
        }
    });

const listener = connector.listen();
const server = restify.createServer();
server.post('/api/messages', listener);
server.listen(process.env.port || process.env.PORT || 3978, function () {
    console.log('%s listening to %s', server.name, server.url);
});
//# sourceMappingURL=test.js.map
```

## Reproduction Steps
1. save the above code as test.js
2. launch the code using: `node test.js`. I am assuming you have a node_modules folder with restify and botbuilder as packages.
3. Use the emulator to launch a conversation and type in "hi"
4. When presented with the choice list, type in the match phrase for the triggerAction.. in our case "global help"
4. This triggers the "ghelp" dialog as expected but, then when the "ghelp" dialog exits, the prompt choice dialog sees it has already used up a turn and then just returns to the next function.

## Expected Behavior
after the "ghelp" dialog is done, user should be returned to the prompt so they can continue where they left off, rather than count the "global help" message as an attempt to answer the prompt.

`triggerAction` should intercept the message ahead of the prompt dialog, or the prompt dialog should not increment `dialogData.turns` till the bot knows for sure that's the dialog that will ultimately respond.

## Actual Results
User was told they had made a selection in the promptChoice dialog when in fact they had made a global help request and were expecting to go back to making their choice.

**Comment by nwhitmont** [comment]
@anvad Great question. 

The `triggerAction` is a global recognizer. This means it can be triggered any time in your bot runtime.
