### ISSUE TITLE
[Feature Request] Support for Alexa as a channel

### ISSUE THREAD

**Issue by robinsedlaczek** [Microsoft/BotBuilder#3761]
## Issue Description
Following the announcement from Microsoft and Amazon that Cortana and Alexa will work together in the future (http://phx.corporate-ir.net/phoenix.zhtml?c=176060&p=irol-newsArticle&ID=2297243), the question is not far away: Will there be a channel for Alex, so that a bot made with the MS Bot Framework can act as an Alexa skill somehow?

**Comment by amitbend** [comment]
Any news?

**Comment by syedhassanabbas** [comment]
Thumbs up, for the feature request. I have the bot but Alexa users cant use it :( I hope Bot framework will support at least most popular channels. Amazon Alexa and Google Assistance are two big names.

**Comment by rjgmail88** [comment]
There was a talk at Build 2018 about Cortana + Alexa integration. I think its on the roadmap but not sure of Alexa can come as a channel.

**Comment by sgellock** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team

**Comment by spawn-guy** [comment]
looks like this might be a solution https://github.com/CatalystCode/alexa-bridge

**Comment by EricDahlvang** [comment]
This library too: https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/tree/master/libraries/Bot.Builder.Community.Adapters.Alexa
