### ISSUE TITLE
[Emulator] Bot returns SUCCESS but no response in Emulator afterwards?

### ISSUE THREAD

**Issue by birender-s** [Microsoft/BotBuilder#3762]
## Bot Info
* App ID: 9bf60e96-6a1b-4cca-ac26-41b0d71d75eb
Endpoint: http://e-com-bot-azure.azurewebsites.net/api/messages
* SDK Platform: Node.js
* SDK Version: 3.7.0
* Active Channels: Skype, Direct Line
* Deployment Environment: Auzure Bot Service 

## Issue Description
When running the bot application on local environment, emulator receives all request responses without any issues. But when the same emulator connects to bot application deployed on MS Azure, initial flows works fine but responses to subsequent request consistently drops out. Adding further, emulator receives SUCCESS (200) to request but no messages afterwards. This is quite strange behavior only on MS Azure deployment whereas same requests works fine when emulator connects to locally running Bot (standalone NodeJs app). 

Note that I am experiencing similar behavior (as emulator) with Directline APIs invoked by sample Android app too. Skype integration with MS Azure however works perfectly fine. Is it something to do with Directline APIs channel alone (as Emulator too uses Directline APIs) ? Please advise.

## Reproduction Steps
1. type "Touring Bikes"
2. Bot returns couple of records. Now select "Show me" button. Bot returns 200 success but no details after wards.

## Expected Behavior
Bot should display product variants list options after #2 above.

## Actual Results
Bot doesn't return any follow up results

**Comment by JasonSowers** [comment]
1. Please upgrade your SDK to the latest version and see if your issue persists
if it continues
2. Can you please try [Debugging locally with ngrok](https://blog.botframework.com/2017/10/19/debug-channel-locally-using-ngrok/)

**Comment by markau** [comment]
Not OP but same behaviour. ngrok can't seem to get to my machine (enabled port forwarding on router and turned off windows firewall temporarily). 

This is the default Node.js "natural language" project - works in Azure, doesn't work locally. Download the zip, `npm install`, launching the application with (verified) LUIS config i.e. `LuisAppId='xxx' LuisAPIKey='xxx' node app.js`. Bot emulator receives a message with `200` and then replies with nothing.

**Comment by markau** [comment]
[This](https://blogs.msdn.microsoft.com/cbtham/2018/01/24/no-response-from-bot-emulator-after-the-new-update-to-bot-frameworkazure-bot-service/) fixed it for me; comment out the table storage locally.

**Comment by markau** [comment]
So the answer to make this work both locally and in Azure

````
if (process.env.BotEnv == 'prod') {
    bot.set('storage', tableStorage);
}
````

@JasonSowers, are the Azure default projects on GitHub for me to be able to contribute this in a PR?
