### ISSUE TITLE
[Telegram] Getting error: 'timed out after 15s' when sending to Telegram channel?

### ISSUE THREAD

**Issue by Ma3yTa** [Microsoft/BotBuilder#3767]
* App ID: 62516114-227c-436c-8e55-e7dcf50e7474
* SDK Platform: .NET
* SDK Version: 3.11.0
* Active Channels: skype, telegram
* Deployment Environment: aws

## Issue Description
Message 'POST to nowinfinity_assistant timed out after 15s' in reply in Telegram channel.
https://ibb.co/kN3osb
In Skype all works well

## Reproduction Steps
1. add bot to contacts
2. send 'abn for Abbott'

## Expected Behavior
no messages like 'POST to nowinfinity_assistant timed out after 15s' in reply to user activity

## Actual Results
https://ibb.co/kN3osb

**Comment by LegeDoos** [comment]
+1
Same error on receiving attachment in telegram
POST to berend_botje timed out after 15s
