### ISSUE TITLE
[Code Example] I deleted the session.message.address.conversation property to start a DM, but it causes ChatConnector to throw error and lose state?

### ISSUE THREAD

**Issue by John-Cerreta** [Microsoft/BotBuilder#3771]
## Bot Info 
* App ID: 0e9cd1d4-1472-4378-a05b-a5e0cf375504
* SDK Platform:  Node.js
* SDK Version:  6.11.2
* Active Channels:  Slack
* Deployment Environment:  IBM Cloud

## Issue Description

Currently following this example: https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node/core-CreateNewConversation

I want my bot to be able to receive a message in a channel it is a part of, then send a survey to gather information via DM. I followed what the example showed, by deleting session.message.address.conversation. The first message of the waterfall dialog is then sent, however when I respond I get an error from ChatConnector saying that it cannot read property id of undefined. After this it exits the dialog and loses state.

After looking into the ChatConnector code a little, I found the error (at line 479). In order to make a post request the conversation ID is a necessary field. I've tried adding back the conversation ID later but then it won't be a direct message. Am I missing something, or is what I want to do not possible with the current iteration of ChatConnector? 

## Code Example

Here is the first snippet, this is where I've deleted the conversation and 
```js
    dialog.matches("RallyAdd", [
        function(session, args, next) {
            console.log("Intent: RallyAdd");
            if (helperUtils.checkMention(session)) {
                // //making bot direct message you
                var conversation = session.message.address.conversation;
                // var newConversationAddress = Object.assign({}, address);
                // console.log("Address", newConversationAddress);
                delete session.message.address.conversation;
                return session.beginDialog("rallyAdd", conversation, args);
            } else {
                session.endDialog();
            }
        }
    ]);
```
This is the second snippet, from RallyAdd. It gets through the first function, but throws the error after the first user message, as it cannot determine a conversation ID (or so I assume).
```js
    module.exports = [
        function(session,conversation,args, next) {
            //Direct messaging
            //session.message.address
            session.userData.kVPairs = "";
            session.userData.kVPairs = session.userData.kVPairs
                ? session.userData.kVPairs
                : [];

            get_type = builder.EntityRecognizer.findEntity(
                args.entities,
                "get_type"
            );
            get_id = builder.EntityRecognizer.findEntity(args.entities, "get_id");
            properties_array = builder.EntityRecognizer.findAllEntities(
               args.entities,
                "get_properties"
            );
            subject_array = builder.EntityRecognizer.findAllEntities(
                args.entities,
                "get_subject"
            );

            console.log("-------");
            console.log(properties_array);
            console.log(subject_array);

            successful = addToUserData(properties_array, subject_array, session);

            // console.log(session.userData.kVPairs);

            // session.endDialog('done');
            if (!get_type) {
                builder.Prompts.text(session, "What type do you want to add?");
            } else if (get_type == "task" && !get_id) {
                builder.Prompts.text(
                    session,
                    "What's the ID of the User Story you'd like to add this task to?"
                );
            } else {
                console.log("Entity " + get_type.entity);
                next({ response: get_type.entity });
            }
        }
```

## Reproduction Steps
1. Run the bot locally on port 3978
2. Use bot emulator to test
3. Message the bot in a channel it is in to start, going through the process like normal

## Expected 
I expected the bot to DM the user messaging it, continue through the waterfall, and complete the dialog.

## Actual Results

The bot DMs me after I message it in a channel. The DM is the first message from step 1 of 6 in the waterfall. After I message it, I get an error saying ChatConnector cannot find id of undefined and exits the dialog.

**Comment by nwhitmont** [comment]
@John-Cerreta Thanks for reporting. It's possible that there is a mistake in the code example instructions.

**Comment by John-Cerreta** [comment]
Is there any chance you could give me an example to do what I want? I just want my bot to start the waterfall in a direct message after being mentioned in a channel it is in.

**Comment by nwhitmont** [comment]
It looks like the explanation provided in the "Code Highlights" section of the README contains a misleading error. 

In the README section "Code Highlights", it says:
```js
// this is the object we should persist if we want to create a new conversation anytime later
// copy it without the conversationId 
var address = session.message.address;
delete address.conversation;
```

But in the actual code, it works differently, they are creating a new object using `Object.assign` and the original `address` object is left unchanged. --> [In app.js - L38](https://github.com/Microsoft/BotBuilder-Samples/blob/master/Node/core-CreateNewConversation/app.js#L380)
```js
// new conversation address, copy without conversationId
var newConversationAddress = Object.assign({}, address);
delete newConversationAddress.conversation;
```

Update your code to make a copy of the `address` object and work with the copy instead of the original `address` object.
