### ISSUE TITLE
[Question] How to manage user inputs in a short time interval?

### ISSUE THREAD

**Issue by diegotrp** [Microsoft/BotBuilder#3772]
**Bot Info**
SDK Platform: .NET
Active Channels: Facebook Messenger

Hi, i would like to implement a way of managing a user sending many messages in a time interval (for example 3 seconds), so that the chatbot only responds to the last one.

Example of inputs (in a gap of 3 seconds):
>-Hi
>-Hi
>-Hi
>-Help

Result: The chatbot only responds to the Help message. 

Thanks in advance.

**Comment by nwhitmont** [comment]
@diegotrp Great question. 

The requested functionality is not built-in to the BotBuilder SDK (Preview) as of yet.  You will need to design a custom code solution to handle this scenario.
