### ISSUE TITLE
[Question] How to call LUIS Programmatic APIs v2.0 via Node.js?

### ISSUE THREAD

**Issue by GauravDhavale** [Microsoft/BotBuilder#3773]
## Issue Description
 I want to access LUIS API in Node JS to [Get closed list entity info](https://westus.dev.cognitive.microsoft.com/docs/services/5890b47c39e2bb17b84a55ff/operations/5890b47c39e2bb052c5b9c26)

## Code Example
 ```js
 var options = {
                host: 'westus.api.cognitive.microsoft.com',
                port: '443',
                path: 'luis/api/v2.0/apps/' + process.env.LUIS_APP_ID + '/versions/0.1/closedlists/' + process.env.LUIS_CLOSED_LIST_ID,
                headers: {
                    "Ocp-Apim-Subscription-Key": process.env.LUIS_SUBSCRIPTION_KEY
                },
                method: 'GET'
            };
  https.request(options, function (res) {
                var body = '';
                res.on('data', function (chunk) {
                    body += chunk;
                });
                res.on('end', function () {
                    var jsonResult = JSON.parse(body);
                     .... some operations 
                      });
                res.on('error', function (err) {
                 console.log('error occured', err);
                });
            }).end();
```

## Expected Behavior
I'm expecting the JSON data of closed entity List 

## Actual Results
Getting Error 400 as 
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Bad Request</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Bad Request - Invalid URL</h2>
<hr><p>HTTP Error 400. The request URL is invalid.</p>
</BODY></HTML>
```

 I have tested it on [this ](https://westus.dev.cognitive.microsoft.com/docs/services/5890b47c39e2bb17b84a55ff/operations/5890b47c39e2bb052c5b9c26) and it's giving me the closed list data but unable to fetch in Node JS.

**Comment by nwhitmont** [comment]
@GauravDhavale Did you follow all the steps described in this article?

https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-get-started-node-get-intent

Based on your error message, there is a problem with the URL you are using to call the LUIS API. 

Try including the subscription key as a URL query parameter instead of sending it in the headers as described in the article.

Example:
```
https://westus.api.cognitive.microsoft.com/luis/v2.0/apps/df67dcdb-c37d-46af-88e1-8b97951ca1c2?subscription-key=<YOUR_API_KEY>&verbose=false&q=turn%20on%20the%20bedroom%20light
```

**Comment by stevengum97** [comment]
It's probably saying invalid URL because it thinks you're trying to access this URL:

```js
https://westus.api.cognitive.microsoft.comluis/api/v2.0/apps/${process.env.LUIS_APP_ID}/versions/0.1/closedlists/${process.env.LUIS_CLOSED_LIST_ID}`
```

Try adding a `'/'` to either the end of your `host` or at the beginning of your `path` and let us know if it fixes the issue.

```js
// example options object
var options = {
  host: 'westus.api.cognitive.microsoft.com',
  port: '443',
  path: '/luis/api/v2.0/apps/' + process.env.LUIS_APP_ID + '/versions/0.1/closedlists/' + process.env.LUIS_CLOSED_LIST_ID,
    headers: {
      "Ocp-Apim-Subscription-Key": process.env.LUIS_SUBSCRIPTION_KEY
    },
  method: 'GET'
};
```

**Comment by GauravDhavale** [comment]
@stevengum97  Adding the '/' at the beginning of the path works. Thanks. 👍  Closing the issue.
