### ISSUE TITLE
[Skype] Why am I getting error: "One or more of the user ids provided is not valid"?

### ISSUE THREAD

**Issue by rposbo** [Microsoft/BotBuilder#3774]
## Bot Info: (Not published)
* App ID: rposbo_demo_bot
* SDK Platform: .Net
* SDK Version: 3.11.0
* Active Channels: Skype, Web
* Deployment Environment: Azure Web App

## Issue Description
Bot receives "One or more of the user ids provided is not valid" via skype all the time. I've deleted and recreated the bot, I've removed and re-added the skype channel, I've changed and updated the app password.

It used to work just fine, then I had to update it once Skype started using a trafficmanager in front of the images.

## Reproduction Steps
1. Register bot with skype
2. Attempt to send message via web skype/skype app
3. See the error in the console

## Expected Behavior
Message to be received by bot; it currently works fine via web (in the botframework test panel) and no errors are logged in the botframework channel

## Actual Results
No message received by bot, instead receive "One or more of the user ids provided is not valid" in console.

**Comment by nwhitmont** [comment]
@rposbo for reference, your bot's App ID is a number. You posted the "bot handle" in the App ID field.

**Comment by nwhitmont** [comment]
relates to #3775

**Comment by JasonSowers** [comment]
I just tested your bot and got no errors, do I have to follow a specific dialog to repro?
   
![image](https://user-images.githubusercontent.com/6301037/32796327-4a2426f4-c923-11e7-87b2-8f0b8ccd5e3f.png)

**Comment by rposbo** [comment]
Closing this as it just seemed to clear up after a while.
