### ISSUE TITLE
[Channel Configuration] Unable to add Skype channel back to bot after deleting channel?

### ISSUE THREAD

**Issue by rposbo** [Microsoft/BotBuilder#3775]
## Bot Info 
* App ID: 516bb5f3-7bf2-4e09-a07f-31cf2268dd98
* SDK Platform: .NET
* SDK Version: 3.11.0
* Active Channels: web, skype
* Deployment Environment: azure web app

## Issue Description
Having deleted the skype channel while trying to debug another issue (#3774) upon recreating the Skype channel when I click the "Skype" link to add the bot to my contacts I get redirected to a "bot not found" skype error page.

Skype bot link: https://join.skype.com/bot/516bb5f3-7bf2-4e09-a07f-31cf2268dd98

## Reproduction Steps
1. Delete skype channel from a bot
2. Add the Skype channel
3. Click the "Skype" link in the active channel listing

## Expected Behavior
Be presented with the "add bot to your contacts" screen

## Actual Results
Skype's "bot not found" (/botnotfound) error page

**Comment by nwhitmont** [comment]
@rposbo When I checked your bot just now, I was able to add the bot to my Skype contacts, but the bot did not respond (on Skype).  Bot appears to be working find on webchat in the Bot Portal, so doesn't look like a bot-code issue. 

I will forward your report to the platform team for investigation.

**Comment by EricDahlvang** [comment]
I was just able to add your bot, and communicate with it on Skype:

![image](https://user-images.githubusercontent.com/11055362/32755900-4e445dc2-c88c-11e7-8a7d-2ff45faca02e.png)

Maybe this is a latency issue.

**Comment by nwhitmont** [comment]
Looks like your bot is working fine on Skype now. resolving.
