### ISSUE TITLE
[Question] openUrl: How can you modify this action so that the url is not opened in a new tab?

### ISSUE THREAD

**Issue by jfantell** [Microsoft/BotBuilder#3776]
SDK Platform: Node.js
SDK Version: 3.11.0
Active Channels: web, direct line
Deployment Environment: localhost

**Issue Description:**
How can you modify the HeroCard openUrl action so that the url is not opened in a new tab? Or alternatively create your own custom action? I want to call an external API instead of opening up a new tab in the browser.

**Comment by nwhitmont** [comment]
@jfantell Great question.

In this scenario, you're not going to want to use the `.openUrl` card action. Instead, send a `imBack` type message, and then setup a dialog with a `triggerAction` to handle it, aka do the API call.

Example:
```js
// in your card, use CardAction.imBack instead of .openUrl:
new builder.HeroCard(session)
    .title("Card title")
    .text("Some card text goes here")
    .buttons([
        builder.CardAction.imBack(session, "trigger-api-call", "Call API")
    ]
);

// setup a dialog handler to detect the postback message and act on it
bot.dialog('handleImBack', (session) => {
    // we got the postback message, now do something
    // make API call here
}).triggerAction({ matches: /trigger-api-call/i });
```

**Comment by jfantell** [comment]
Thank you for your swift reply. :) The way I currently have my chatbot set up is that when a user clicks on this specific dialog, the bot sends the user back a carousel of rich cards. Then the bot immediately sends a button prompt. If the user clicks on the card buttons I do not want that to interfere with the flow of the chat...I want them to still have to select one of the button prompt options. That is why I was curious if there would be some way to log the url without opening a new tab.

**Comment by jfantell** [comment]
I have been looking through the modules but I have not been able to find the code that is actually parsing and opening the url in a new tab yet.

**Comment by EricDahlvang** [comment]
Hi @jfantell 

The code in the WebChat control that opens **openUrl** actions in a new window can be found here: https://github.com/Microsoft/BotFramework-WebChat/blob/88034a804bf438c99d9f47e0d977e7cf4ec76e2b/src/Chat.tsx#L240

**Comment by nwhitmont** [comment]
@jfantell It sounds like your question is really about the WebChat module, not the BotBuilder SDK for Node.js. 

For WebChat assistance, please open a new issue on the BotFramework-WebChat repository here:
https://github.com/Microsoft/BotFramework-WebChat/issues/new
