### ISSUE TITLE
[Question] Parent page refresh on user response?

### ISSUE THREAD

**Issue by BManiKanta001** [Microsoft/BotBuilder#3778]
## Bot Info 
* SDK Platform: .NET
* Active Channels: Direct Line
* Deployment Environment: other (AWS)

## New Feature Request
It would be better to redirect the page based on user response. 
Eg: If the user enters, "redirect to home page", then instead of giving link, better to redirect the parent page.

**Comment by nwhitmont** [comment]
Hi @BManiKanta001 - I do not understand your request. 

What are you trying to accomplish exactly? Please provide more detailed context and use case.

**Comment by nwhitmont** [comment]
@BManiKanta001 Can you provide more details about your specific use case?
