### ISSUE TITLE
Sending line breaks to Slack does not work

### ISSUE THREAD

**Issue by mattlanham** [Microsoft/BotBuilder#378]
Based on the slack documentation it is expected that `\n` should produce a line break, but that is currently not working given the following code:

```
session.send("Hello\nWorld");
```

The result is all on one line in slack - any help appreciated.

**Comment by mattlanham** [comment]
I have now resolved this by changing the code to 

```
session.send("Hello\nWorld");
```

Based on the description in #33

**Comment by BernardTheDog** [comment]
why is this one closed as it should be correct with only one \n ?

**Comment by nwhitmont** [comment]
@BernardTheDog You are commenting on a closed issue. 

If you have a question or problem, please [click here to open a new issue.](https://github.com/microsoft/botbuilder/issues/new)
