### ISSUE TITLE
[Node.js SDK, LUIS] How to reset a LUIS dialog session?

### ISSUE THREAD

**Issue by buehler** [Microsoft/BotBuilder#3782]
* App ID: 05a31b77-1d72-4c41-acf7-923f5efe11c5
* SDK Platform: node.js
* SDK Version: ^3.11.0
* Active Channels: webchat
* Deployment Environment: docker container

## Issue Description
We have a chat bot that guides the user through an ordering process. The user can always abort the current flows with `abort`, so we registered the action to confirm that the user really wants to cancel his flow and start over. Now when we do that, we call it as follows:

```typescript
// register cancel intent
const cancelKeywords = i18next.t('actions.cancel', { joinArrays: '|' });
bot.recognizer(new RegExpRecognizer(
    CustomIntents.Cancel, new RegExp(cancelKeywords, 'i')),
);

// in the cancel dialog:
session.clearDialogStack();
session.replaceDialog('/menu');
```

Now when we do that in a luis dialog, every time we navigate back to the luis dialog (`/luis`), it just resumes the last sent userinput and therefore with the intent that luis assigned to it.

So actually, luis just resumes at the last intent that it matched and not at the cleared state which would be the expected behavior.

## Expected Behavior
The expected behavior would be to start over at the base of the luis intent and ask the user "How may I help?" instead of just assuming the same input of the user.

I'm happy to provide more information if needed :-)

Thanks for any help!

Cheers
Christoph

**Comment by buehler** [comment]
For the records: we need to use a custom dialog since we have multi language (primary german for now) and need to use some more powerful i18n packages.

**Comment by fanidamj** [comment]
Can you please let us know if the issue still persists?

**Comment by compulim** [comment]
I think this is not related to Web Chat.

**Comment by EricDahlvang** [comment]
Closing due to no response.
