### ISSUE TITLE
[State API] How to configure bot to store State data locally?

### ISSUE THREAD

**Issue by Aashish-Amber** [Microsoft/BotBuilder#3785]
## Bot Info 
* App ID: 0ee73907-c213-41ba-a527-3084d615e2fb
* SDK Platform:  Node.js
* SDK Version: 3.12.0
* Active Channels: Facebook
* Deployment Environment: ngrok

## Issue Description
Ms bot builder bot code is throwing that the " Bot State API is deprecated ,Please refer to https://aka.ms/I6swrh for details on how to replace with your own storage."

I followed the documentation and its states that we can implement a custom state client using data storage platform of your choice instead of using Azure service . Can someone guide or provide some information in that direction how to achieve custom state client using local data storage.

So with this change the Microsoft web based connector use will be just a web based platform for conversion of Platform specific request to bot framework specific format and vice versa and state management will be handled locally .

## Reproduction Steps
1. update your bot builder SDK to 3.12.0 and observe your logs

**Comment by EricDahlvang** [comment]
HI @Aashish-Amber 

By "local data storage" are you referring to window.localStorage?

**Comment by nwhitmont** [comment]
@EricDahlvang In-memory storage.

**Comment by EricDahlvang** [comment]
@nwhitmont I realize that.  My question is if they mean local storage, as in server-side.  Or, if they mean local storage as in "client side browser".  Either is possible for the WebChat channel, but browser local storage would not be possible for other channels.  I appreciate your feedback, but I don't think you have enough information provide an answer for @Aashish-Amber

**Comment by Viktorianec** [comment]
What's volume of store data for Skype bot by default?

**Comment by njss** [comment]
I am getting this same error "The Bot State API is deprecated." in vs code, using the latest bot builder version 3.12.0. It runs well in Azure, but when debugging locally I get this error all the time and my code is not executed.

**Comment by JpEncausse** [comment]
I am getting the same error, I tried to avoid it with:

```
let bot = new builder.UniversalBot(connector, {
    persistUserData: false,
    persistConversationData: false,
    autoBatchDelay: 0
});
```

But it doesn't work, I keep receiving this message :-(
We do not use botbuilder storage, we have dedicated steps to store/retrieve data for a given user.

**Comment by graphnode** [comment]
After checking the code I was able to fix this by manually setting the memory storage:
```javascript
var bot = new builder.UniversalBot(connector, {
    storage: new builder.MemoryBotStorage()
});
```

There seems to be a bug (?) when setting the default connector in [UniversalBot.js line 89](https://github.com/Microsoft/BotBuilder/blob/b3aab9f51efea19b7eb771bb7fc785766d075986/Node/core/lib/bots/UniversalBot.js#L89):
```javascript
var asStorage = connector;
if (!this.settings.storage &&
    typeof asStorage.getData === 'function' &&
    typeof asStorage.saveData === 'function') {
    this.settings.storage = asStorage;
}
```
This uses the connector getData and setData which show the deprecated message. 

**WARNING**: This storage is **volatile** and **will not be preserved between bot runs**.

Check [BotStorage.js implementation](https://github.com/Microsoft/BotBuilder/blob/b3aab9f51efea19b7eb771bb7fc785766d075986/Node/core/lib/storage/BotStorage.js) for help on making your own storage class.

**Comment by merttopcu** [comment]
This broke our chatbot with hundreds of daily users.
As MSFT Botframework developers, how can we get notified about these changes?
