### ISSUE TITLE
[WebChat] Security recommendation regarding banner grabbing and Cross Origin Resource Sharing on https://webchat.botframework.com

### ISSUE THREAD

**Issue by PravinShriram** [Microsoft/BotBuilder#3786]
## Issue Description
While Doing security testing our ISG team found CROS and Banner Grabbing Vulnerabilities with URL
https://webchat.botframework.com/v3/directline/conversations/<Token>/activities?watermark=0
https://webchat.botframework.com/embed/HrBotV3?s=<Secret> 

We are using Web Chat channel, Iframe embedded in our website.  

## Code Example
https://webchat.botframework.com/v3/directline/conversations/<Token>/activities?watermark=0
https://webchat.botframework.com/embed/HrBotV3?s=<Secret> 

## Reproduction Steps
1 access https://webchat.botframework.com
2. F12
3.Check the request response headers
![image](https://user-images.githubusercontent.com/30997248/32879231-28d8edba-cacf-11e7-999b-3d12890e274e.png)
![image](https://user-images.githubusercontent.com/30997248/32879266-450bb1f2-cacf-11e7-93b3-57515b37705d.png)

## Expected Behavior
Allow only selected, trusted domains in the Access-ControlAllow-Origin header. 
Network administrators should restrict access to services on their networks and shut down unused or unnecessary services running on network hosts
IIS version information should not be displayed.  
HTTP/1.1 200 OK
Cache-Control: private
Content-Length: 901
Content-Type: text/html; charset=utf-8
Content-Encoding: gzip
Vary: Accept-Encoding
**Server: Microsoft-IIS/8.0**
X-AspNetMvc-Version: 5.2
Request-Context: appId=cid-v1:91e46abb-4ce5-4d98-9375-02378f649011
X-Powered-By: ASP.NET
Strict-Transport-Security: max-age=31536000
Date: Wed, 15 Nov 2017 14:46:54 GMT

## Actual Results

Marked information in below images should not shown in response header.
![image](https://user-images.githubusercontent.com/30997248/32879407-db429d8e-cacf-11e7-81ff-f17db8688560.png)
![image](https://user-images.githubusercontent.com/30997248/32879422-e96b211a-cacf-11e7-8354-bb633b43f877.png)

**Comment by PravinShriram** [comment]
@msft-shahins  @msftgits @willportnoy

**Comment by nwhitmont** [comment]
@PravinShriram Thanks for reporting. I have forwarded this recommendation to our WebChat team.

**Comment by DeepakIoT** [comment]
How can we stop showing Request-Context: appId=cid-v1:91e46abb-4ce5-4d98-9375-02378f649011 in Resposne Header?

**Comment by EricDahlvang** [comment]
@DeepakIoT 

This is the BotBuilder repository.  Please file an issue on the WebChat repo: https://github.com/Microsoft/BotFramework-WebChat/issues
