### ISSUE TITLE
[Question] Why am I getting "EAI_AGAIN" error on server console? Bot not working on WebChat?

### ISSUE THREAD

**Issue by akshay-vijay** [Microsoft/BotBuilder#3788]
* App ID: 7260b447-08a1-46bc-b2e5-4260fe2fde51
* SDK Platform: Node.js
* SDK Version: 
* Active Channels: Skype, Web chat
* Deployment Environment: other

## Issue Description
Getting EAI_AGAIN on server console, unable to chat with bot using Web chat.

## Reproduction Steps
1. go to https://demo.hpesis.com/api/webchat
2. start chatting it
3. on node js server console getting 

Error: getaddrinfo EAI_AGAIN login.microsoftonline.com:443
    at Object.exports._errnoException (util.js:1020:11)
    at errnoException (dns.js:33:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)

## Expected Behavior
When you start with web chat it will greet user with Hello

## Actual Results
Greet message is not coming and whatever I am typing is not going to server

**Comment by Aashish-Amber** [comment]
Check the port on which you are running your bot server , it seems the port is already occupied . You might have restarted the server on the same port without closing the previous instance . Either change the port on which you are running your bot or kill the process which is using your desired port.

**Comment by akshay-vijay** [comment]
Thanks for your comment. Have already tried this. There is no issue with ports. Also web chat iframe is getting loaded that means server/port is up.

**Comment by JasonSowers** [comment]
Do you have a valid certificate on your server?

**Comment by nwhitmont** [comment]
@akshay-vijay When I tested your bot just now, it did not respond. 

Also, your server's webchat page failed to load, returning `502 Bad Gateway` NGINX error. 

There is a problem with your bot code, and likely your deployment configuration. For reference, where is your bot deployed?

Try deploying one of the known-working [sample bots](https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node) to server to verify your deployment configuration is working. 

If you are still having issues, please post your bot code so we can better assist you.

**Comment by akshay-vijay** [comment]
The issue is resolved now. Problem was, server was unable to resolve the DNS for login.microsoftonline.com. I have added google DNS into etc/resolve.conf file. It working fine now.

**Comment by feyli** [comment]
> The issue is resolved now. Problem was, server was unable to resolve the DNS for login.microsoftonline.com. I have added google DNS into etc/resolve.conf file. It working fine now.

Hi! I know it has been closed for a while but it's exactly the answer I searched for and I don't know how to put the DNS in the conf file :(
Where do I place the DNS, in front of what?

Thanks for answering ^^
