### ISSUE TITLE
[LUIS] Log file of the queries sent to the apps HTTP endpoint is empty?

### ISSUE THREAD

**Issue by GauravDhavale** [Microsoft/BotBuilder#3789]
## Bot Info 
* App ID: 2489776e-b4a1-4d55-b2ba-c430142c75fe
* SDK Platform: Node.js
* SDK Version: botbuilder -> 3.11.0
* Active Channels:  Slack, Direct Line, SFB
* Deployment Environment:  Azure App Service
*LUIS App Id: 5290faa2-2579-4547-815c-ae52ae35d7d6

## Issue Description
Whenever I clicked on the highlighted button, I get the empty CSV file. 
![image](https://user-images.githubusercontent.com/24877974/32899838-a20e25ce-cab1-11e7-8038-ec54d34328f0.png)

## Code Example
Download the CSV file from the cloud button as shown in above image

## Expected Behavior
CSV file with the data

## Actual Results
Empty File 
![image](https://user-images.githubusercontent.com/24877974/32899919-d762a4a2-cab1-11e7-83bb-8427a43c6ae6.png)

**Comment by nwhitmont** [comment]
@GauravDhavale Our team has fixed the issue. Can you confirm it's working for you?

**Comment by GauravDhavale** [comment]
@nwhitmont Yes, I'm getting the data now. Thanks.  Closing the issue.
