### ISSUE TITLE
Json schema for carousel in adaptive cards is showing upgrade to new schema. When using this https://docs.microsoft.com/en-us/adaptive-cards/get-started/bots. Can someone help me in getting the new json schema for carousel.

### ISSUE THREAD

**Issue by jagadeeshmarthy** [Microsoft/BotBuilder#3795]
## Bot Info 
* App ID: 
* SDK Platform: 
* SDK Version: 
* Active Channels: 
* Deployment Environment: 

## Reproduction Steps
1.
2.
3.

**Comment by JasonSowers** [comment]
please fill out the template and we will be happy to assist you

**Comment by EricDahlvang** [comment]
Carousel is a Bot Framework construct, and is not part of the AdaptiveCards schema.  http://adaptivecards.io/explorer/ Here is an example of a .json message with a carousel of adaptive card messages: https://github.com/matthidinger/ContosoScubaBot/blob/master/ContosoScuba.Bot/Cards/1-Schools.JSON  Hope this helps.

**Comment by jagadeeshmarthy** [comment]
@EricDahlvang I have taken the same template and sending it in session.send(). But carousel is not coming up in  Facebook or Skype.
