### ISSUE TITLE
[Question] How to write unit tests for simple bot applications

### ISSUE THREAD

**Issue by krishan1kamal** [Microsoft/BotBuilder#3796]
I am new to creating bot application using Luis. i want to write the unit test cases for simple bot application using Luis. I already gone through the examples and spend a lot of time on this to understand the test cases which are given in this website.Still didn't understand anyone.Can anyone please give me the very simple test case for bot application using Luis for understanding purpose.
I am using nodejs

**Comment by FranciscoPonceGomez** [comment]
Hi @krishan1kamal,

Do you want to test communication between LUIS App and your bot or how your bot handles LUIs results?
We have several tests in this section:
https://github.com/Microsoft/BotBuilder/tree/master/Node/core/tests

There are several frameworks for unit testing out there being Mocha a very popular one:
https://github.com/mochajs/mocha
https://stackoverflow.com/questions/4308786/what-is-the-best-testing-framework-to-use-with-node-js

What is the scenario of your application? What kind of bot you want to build? Can you share some code so we can have an idea of your scope?

Cheers,
Francisco

**Comment by krishan1kamal** [comment]
Error: Dialog[/common] already exists in library[*].

**Comment by JasonSowers** [comment]
@bilby91 didn't you write a testing framework for bots in node?

**Comment by bilby91** [comment]
Hey!

@JasonSowers We ended up using and contributing in [BotTester](https://github.com/microsoftly/BotTester). I highly recommend it! We are using it at [Suttna](https://suttna.com) for all our integration tests.

**Comment by JasonSowers** [comment]
Great, thanks for the info and recommendation!

**Comment by fanidamj** [comment]
Closing the issue assuming it as resolved. Feel free to reopen if the issue persists.

**Comment by Edwardfelix08** [comment]
Hi @FranciscoPonceGomez can you check the link which you have mentioned, seems like it has been broken. Thanks in advance

**Comment by EricDahlvang** [comment]
@Edwardfelix08 The Bot Builder V3 node sdk tests are here now: https://github.com/Microsoft/BotBuilder-v3/tree/master/Node/core/tests

**Comment by Edwardfelix08** [comment]
@EricDahlvang Thanks.
