### ISSUE TITLE
[Localization] Help with localization config

### ISSUE THREAD

**Issue by verdysh** [Microsoft/BotBuilder#3799]
## Bot Info 
* SDK Platform: .NET
* SDK Version: 3.11.0.0

## Issue Description
Hi!

There is a task to make so that the user chose language of dialogue with the bot.
Find information how to do this for a bot on .NET I did not succeed (the documentation has a description only for Node.js).

I tried to do the localization as described in the example of ASP .NET Web API applications. I have identified 2 resources: Recourse.resx and Recourse.uk.resx for ukraine language.

I check what happened:

```
await context.PostAsync($"{Resources.Resource.String1}");
Thread.CurrentThread.CurrentCulture = System.Globalization.CultureInfo.CreateSpecificCulture("uk");
await context.PostAsync($"{Resources.Resource.String1}");
```

In both cases I get string from the Resource.resx.
I tried to rename the resource to Resource.uk-UA.resx and set the current culture

`Thread.CurrentThread.CurrentCulture = System.Globalization.CultureInfo.CreateSpecificCulture("uk-UA");`

The result is the same.
How to correctly localize the bot?

**Comment by EricDahlvang** [comment]
Hi @verdysh 

It isn't necessary to set the thread current culture in your bots code.  This will be done automatically by the .net sdk, based on the locale of the message received by the bot: https://github.com/Microsoft/BotBuilder/blob/497252e8d9949be20baa2cebaa6ce56de04461cf/CSharp/Library/Microsoft.Bot.Builder/Base/LocalizedScope.cs

I created a Resource.resx with the following field:

> Name:String1	
> Value: English string value	

Then I created another resource named Resource.uk-UA.resx with the following field:

> Name:String1	
> Value: uk-UA string value

In my bot's code, I have the following:
`await context.PostAsync($"{Resources.Resource.String1}");`

Depending on the value of the locale property, the corresponding .Resource file is used:

![image](https://user-images.githubusercontent.com/11055362/33104283-197f9650-cedc-11e7-9db4-741ae40cc96a.png)

**Comment by verdysh** [comment]
@EricDahlvang, thanks for the answer!
Can I somehow change the user's locale? I want the user through the bot to specify which language is preferable to him. That is, the user writes to the bot "I want the Ukrainian language" and it changes the locale to the corresponding one.

**Comment by abhishekkant** [comment]
I got to say that we need some specific guidance around localisation support in .NET framework. 
I have also created a resx file (alongwith language specific version abc-hi.resx) in App_GlobalResources Folder (and configured as Embedded Resource). I access the resources using - Resources.<resourcename>.<resource string> in the code. 
Even changing the locale via the Bot Emulator didn't change the strings that I was getting in the code. Only default locale is being used.
In addition, I have tried to use the ResourceManager class. 
ResourceManager class's GetString method continues to throw an error: 
```
ResourceManager rm = new ResourceManager("botResponses", Assembly.GetCallingAssembly());
var noSupport = rm.GetString("UnableToHandle");
```

> Exception: Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure \"botResponses.resources\" was correctly embedded or linked into assembly \"mscorlib\" at compile time, or that all the satellite assemblies required are loadable and fully signed.

Anyone else having experience implementing localisation in Bot Framework?

**Comment by EricDahlvang** [comment]
@verdysh Yes, you can change the user's locale before message processing.  I've created an example that allows the user to choose a language, then stores that choice in PrivateConversationData and modifies all incoming message Locale properties to what the user had chosen.  https://github.com/EricDahlvang/ChooseLanguageBot

@abhishekkant I'm not sure why the emulator's Locale setting would not be sent with every message.  I've never seen that problem.  Please open a new issue if you are still experiencing this.

**Comment by verdysh** [comment]
@EricDahlvang, thanks for the answer and for an example! I'll look at my leisure.
