### ISSUE TITLE
FormDialog with initial state does not skip populated fields

### ISSUE THREAD

**Issue by johnsonj** [Microsoft/BotBuilder#38]
Version: master (688932a)
Expected behavior: The step is skipped.
> When you launch a FormDialog, you can optionally pass in an instance of your state. If you do that, any step for filling a field is skipped if that field has a value - [documentation](http://docs.botframework.com/sdkreference/csharp/forms.html#initialState)

Actual: The step is not skipped. The value is known by the bot. It responds like this:
> Please enter favorite color (current choice: blue)

Repro:
```C#
[BotAuthentication]
public class MessagesController : ApiController
{

    [Serializable]
    public class SampleQuestion
    {
        public string FavoriteColor;
        public string FavoritePizza;

        public static IForm<SampleQuestion> BuildForm()
        {
            return new FormBuilder<SampleQuestion>().Build();
        }
    }

    [Serializable]
    class SampleQuestionDialog : IDialog
    {
        async Task IDialog.StartAsync(IDialogContext context)
        {
            var question = new SampleQuestion();
            // Pre-populate a field
            question.FavoriteColor = "blue";
            context.Call<SampleQuestion>(new FormDialog<SampleQuestion>(question), OnSampleQuestionAnswered);
        }
        public async Task OnSampleQuestionAnswered(IDialogContext context, IAwaitable<SampleQuestion> sampleQuestion)
        {
            var result = await sampleQuestion;
        }
    }

    public async Task<Message> Post([FromBody]Message message)
    {
        return await Conversation.SendAsync(message, () => new SampleQuestionDialog());
    }
}
```

**Comment by chrimc62** [comment]
Yes, you are right.  The logic for doing this when passing in LUIS entities does work, but the straight-up passing in state got removed when we refactored some stuff.  Thanks for bringing this to our attention--we will fix it in the next release.

**Comment by chrimc62** [comment]
This has been checked into the develop branch and will be in the next release.

**Comment by johnsonj** [comment]
Thanks!
