### ISSUE TITLE
[Direct Line] Performance issues with end-to-end response times >= 1.5 seconds

### ISSUE THREAD

**Issue by MavyCS** [Microsoft/BotBuilder#3800]
## Issue
My bot is called through directline by a NodeJS client.
The time for receive the response E2E is too high (1.6 seconds).
Reponse time depends on bot execution time and retrieve method, polling or websocket, 
for this reason I would want put the attention on PostActivity that requres 600-1000 msec alone.

From MS documentation a PostAcivity includes:
* Transit time for the HTTP request to travel from the client to the Direct Line service
* Internal processing time within Direct Line (typically less than 120ms)
* Transit time from the Direct Line service to the bot
* Processing time within the bot
* Transit time for the HTTP response to travel back to the client

Transit time should be very low because the VM are all in the same region (South Central US)

The bot state storage used is cosmoDB and the parameter autoBatchDelay is setted 0 and the bot has a single dialog only (it's very simple).
Bot calls LUIS, with only 3 intents, in about 80/100 msec (this timing has no effects on PostActivity request).

Post Activity request is performed using REST request to https://directline.botframework.com/v3/directline/conversations/<conversationID>activities 
Authorization type is with directLine secret.

## Expected Behavior
For a production environment I expect that postActivity takes few msec, about 200, no more.
I know that BotFramework is in preview.

## Actual Results
I have executed many tests with different clients all with an avarage time of postActivity about 600/1000 msec
SWAGGER (v: 2.1.18) and DirectLineJS (v: 0.9.12), postActivity time avarage 750 msec
Custom client using REST calls, with module "request" version 2.83.0, postActivity time is the same of previous.

## Environment
* Operating System: Windows NT 6.2.9200.0

* SDK Platform: 
-Client Node.js version: 8.9.0
-Client NPM version: 5.5.1
-Bor Builder version: 3.12.0
-botbuilder-azure version: 3.0.4
-Bot Node.js version: 6.9.1
-BOT NPM version: 3.10.8

* Development environment (South Central US):
-Azure Web App
-Azure Bot Service App

## Example Code:
We have used both examples at these links with same results:
https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node/core-DirectLine
https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node/core-DirectLineWebSockets

Snippet of custom client for PostActivity :

```
var msgObj = {                                                                            
                textFormat: 'plain',
                text: 'myMessage',
                type: 'message',
                from: {
                    id: 'myUser'
                }
            };
        var msg = JSON.stringify(msgObj);
        logger.debug("["+convid+"] posting activity: "+msg);
        request.post({
            uri:dlBaseUrl+'/v3/directline/conversations/'+convid+'/activities',
            headers: {
                'Content-Type': "application/json",
                'Authorization': config.directLine.headers.authorization 
            },
            time:true,
            //qs: options,
            body: msg
        }, (error, response) => { 
            if(error){
                logger.error('Error postActivity request:'+JSON.stringify(error));
            }else{
                logger.info("["+convid+"] postActivity elapsedTime :"+(response.elapsedTime));
                logger.info("["+convid+"] postActivity :"+(response.body));
            }
        });
```

**Comment by nwhitmont** [comment]
@MavyCS Thanks for reporting. 

Currently, the Direct Line connector service has a default timeout of 15sec, so your reported response times, while possibly different than your expectation, still falls within the range of "normal operation" of this service during Bot Framework's Preview period. 

If you are consistently seeing responses take more than 10sec, or something that causes your bot to timeout entirely (>15s) then that would be a problem, but since you are reporting response times <=2s, this appears within normal range.

**Comment by MavyCS** [comment]
In a future GA version this timing will be different or the same?
When will be available a GA version?

**Comment by EricDahlvang** [comment]
Hi @MavyCS 

Bot Framework is now GA status, as of mid December 2017.

I would like to point out that the list you've provided also includes state retrieval and persistence, and return message transit time through the Direct Line Service:

- Transit time for the HTTP request to travel from the client to the Direct Line service
- Internal processing time within Direct Line (typically less than 120ms)
- Transit time from the Direct Line service to the bot
- Processing time within the bot <-- **includes retrieving and persisting state (dialogdata, conversationdata, privateconversationdata, userdata)**
- Transit time for the HTTP response to travel back to the client <-- **includes transit time to Direct Line service, THEN transit time back to the client**

As mentioned by @nwhitmont , <=2s response times seems entirely reasonable and within normal range.  I'm closing this issue, please open a new issue if you require further assistance.
