### ISSUE TITLE
[LUIS] Model does not identify my custom entity?

### ISSUE THREAD

**Issue by PoojaSha** [Microsoft/BotBuilder#3802]
In my code, resut.entities LUIS return prebuilt entities but not custom entity created by me. Kindly help.

**Comment by FranciscoPonceGomez** [comment]
Hi @PoojaSha,

What SDK are your using to build your bot? Are you following from one of our samples? Can you share an extract of your code so we can understand the problem?

Regards,
Francisco

**Comment by nwhitmont** [comment]
@PoojaSha Thanks for reporting.

What is the LUIS application ID that is having the problem?

Can you export your LUIS model as JSON and link it to this GitHub issue for reference? Thanks.

Click on the `{ }` icon to export LUIS model:
![export model luis my apps](https://user-images.githubusercontent.com/3075047/33243175-eb6a40e0-d295-11e7-82f6-dca7383cde53.png)

**Comment by fanidamj** [comment]
Closing the issue assuming it as resolved. If you have any other concerns for LUIS support, please contact luservice@microsoft.com.
