### ISSUE TITLE
[Skype for Business] Channel reliability issues when bot deployed via ngrok?

### ISSUE THREAD

**Issue by anujaparikh23** [Microsoft/BotBuilder#3803]
## Bot Info 
* App ID: f079f4c0-39a6-4825-81e2-0da3a7c13b53
* SDK Platform:  Node.js 
* Active Channels: Skype, Webchat,Skype For Business 
* Deployment Environment: ngrok

## Issue Description
We have registered a bot as a contact on skype for business. But it has stability issue. Many times the bot goes down all of a sudden. Then after few hrs it starts working on its own.

## Expected Behavior
I expect skype for business to show stability. All channels are very stable and work properly almost everytime. But with Skype for business we face issues, which affects our demos, as the bot goes down many times when we are to give the demo

## Actual Results

![sfb1](https://user-images.githubusercontent.com/17399975/33059510-87281a64-ceba-11e7-862b-2bab7ed3b527.png)

**Comment by JasonSowers** [comment]
Is the inconsistency only occurring on the Skype for Business channel?

**Comment by anujaparikh23** [comment]
Yes only on Skype for Business. Webchat and Skype work almost everytime

**Comment by nwhitmont** [comment]
@anujaparikh23 For reference, can you provide a `conversationId` and the time(s) + timezone when the error happened?
