### ISSUE TITLE
[Skype] Undocumented difference in messages between Skype desktop app and Skype store app

### ISSUE THREAD

**Issue by Raffo84** [Microsoft/BotBuilder#3804]
## Bot Info 
* App ID: 8aa8861d-06ea-4aa9-94c0-7ee9d2193a89
* SDK Platform: .NET
* SDK Version: 3.11.0
* Active Channels: Skype
* Deployment Environment: Azure App Service

## Issue Description
The messages sent from the Skype desktop app (installed manually through the downloaded installer) and from the Skype store app (installed through the Microsoft store) differ slightly, specifically the "From" property of the message activity. In both cases, an anonymous user "From.Id" is provided, but for the desktop app, the "From.Name" property is set to the users display name, while the store app (apparently) always sets this property to _null_.

## Code Example
```
namespace TestBot.Dialogs {
	[Serializable]
	public class RootDialog: IDialog<IMessageActivity> {
		public Task StartAsync(IDialogContext context) {
			context.Wait(MessageReceivedAsync);
			return Task.CompletedTask;
		}

		private async Task MessageReceivedAsync(IDialogContext context, IAwaitable<IMessageActivity> result) {
			Activity activity = await result as Activity;
			string requesterName = activity.From?.Name;
			// requesterName will be
			// -> the user's display name, if the message was sent through the Skype desktop app
			// -> null, if it was sent from the Skype store app
		}
	}
}
```

## Reproduction Steps
1. Prepare a bot to use the sender's name, as taken from the Activity's "From.Name" property
2. (Optional) Route the bot to a local debugging session (ngrok)
3. (Optional) For testing, send a message through webchat or emulator; the username will be set to something generic, but non-null (like "User" or "You")
2. Start the Skype desktop app and send a message to the bot. The From.Name property will be set to a proper string, the sender's display name
3. Start the Skype store app (the desktop app will automatically close) and send a message to the bot. The From.Name property will now be null.

## Expected Behavior
Both apps should behave identically, preferably providing the user's display name in every case.

## Actual Results
Messages from the "skype" channel differ, depending on whether the desktop or the store app was used.

**Comment by JasonSowers** [comment]
Thank you for reporting.

**Comment by nwhitmont** [comment]
@Raffo84 This is a known issue and there's not much we can do from the Bot Framework side of things.  Will have to wait for Skype client team achieves parity.
