### ISSUE TITLE
IActivityLogger doesn't log every activity

### ISSUE THREAD

**Issue by Enghouse-CCSP-PS** [Microsoft/BotBuilder#3805]
* SDK Platform: .NET
* SDK Version: 3.11.0

## Issue Description
We are looking for a way to log inbound and outbound activities to preserve interaction history. 
As we understand this is obvious use case for **IActivityLogger** and as explained [here](https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-middleware) it should 

> intercept all messages that are exchanged between user and bot

However it doesn't. 
As can be seen in code, **IActivityLogger**'s **LogAsync** method being called only in **PostAsync**, which is called, for example, by **SendAsync**, but other cases, such as: 

`			var reply = ((Activity)activity).CreateReply("Hello");
			await new ConnectorClient(new Uri(activity.ServiceUrl), ApplicationId, ApplicationSecret).Conversations.ReplyToActivityAsync(reply);
`
 **LogAsync** is not triggered.

After investigation, it seems like it's intended, but what is the reason behind this and are there 'best practice' to bypass this restriction?

Additional use case that we want to look into is case when we are opening dialog from another dll. What I mean is that in our dialogs we probably can cover all activities, but as long as we are invoking external dialog it lost - it it will not explicitly log activity and use ReplyToActivityAsync, we will have no control / ability to log over that.

Thanks.

**Comment by JasonSowers** [comment]
@Enghouse-CCSP-PS would you mind sharing your implementation of IActivityLogger?  It may help resolve this issue

**Comment by JasonSowers** [comment]
When calling the  `ConnectorClient`  all internal logging will be bypassed.  To solve this, you can manually call your logger, or insert code to manually log the activity.  Let me know if you need a further explanation or if you have any other questions, good luck!

**Comment by Enghouse-CCSP-PS** [comment]
@JasonSowers Thanks for an answer. There is nothing special about our implementation, it just queues activity to write it to DB later. 
Will manually log activity as you're suggesting.

**Comment by JasonSowers** [comment]
Good luck!
