### ISSUE TITLE
[FB Messenger] Why is Postback button Failing?

### ISSUE THREAD

**Issue by JyothishG** [Microsoft/BotBuilder#3810]
## Bot Info 
* App ID: e402d5ef-bcd7-401d-9095-3d6808515c7f
* SDK Platform: Node.js
* Active Channels: messenger
* Deployment Environment: other 

## Issue Description
Postback button Failing **Sometimes**

## Code Example
There is no specific location to mention where it happens. All the postback button have this issue. I defined them correctly (that I'm sure) and it's working in most of the cases. Failure rate is 5 to 6 times out of 100. 

(Please see the attached file of complete error log. Please note that the error location changes. It's one of the several log that I encountered. )

Thanks and regards
Jyothish G

[error log](https://github.com/Microsoft/BotBuilder/files/1495631/error.log)

**Comment by JasonSowers** [comment]
@JyothishG Can you please post your code so we can better assist you?

**Comment by JyothishG** [comment]
@JasonSowers 
This is how I define the carousel: 
`					

                                    var postBackAction = JSON.stringify({'action': 'SelectTopic','entity': topic.id});

					var card = new builder.HeroCard(session)
						.title(topic.name)
						.text(topic.description)
						.images([builder.CardImage.create(session, topic.image)])
						.buttons([builder.CardAction.postBack(session, postBackAction, 'Select')]);
					cards.push(card);

`
and then I uses custom postback recognizer which returns the intent and entities as:

`

            return {
                entities: [{
                    entity: payload.entity,
                    type: 'Entity',
                    score: 1,
                }],
                intent: payload.action,
                score: 1
            };

`

Then I tried to access the returned intent and entities as:    **args['entities'][0]['entity']**

But it causes the error that I mentioned. As I said earlier this is **not** happening always. Most of the cases code works fine. Also there is **no specific code section**  for the error. Sometimes it happens one of the postback button, another time another button. 

Thanks and regards
Jyothish G
