### ISSUE TITLE
[Question] How to test bot in Docker container using ngrok?

### ISSUE THREAD

**Issue by arieschwartzman** [Microsoft/BotBuilder#3813]
## Bot Info 
* SDK Platform: Node.js
* Active Channels: WebChat
* Deployment Environment: ngrok, Windows 10

## Issue Description
I have created a Docker container with the bot service.  Running Docker container locally on port 8081 Docker container exposes 8081 as well. Using ngrok I point to port 8081

Sending message from WebChat to the bot works fine.
 
Bot could not respond to the BotConnector. It looks like it stuck on refreshToken
Needless to say, the same service works running outside the container.

**Comment by bilby91** [comment]
@arieschwartzman Can you show you docker setup ?

**Comment by nwhitmont** [comment]
@bilby91 Cool man! Can you share your working Dockerfile for reference?

**Comment by nwhitmont** [comment]
Hi @arieschwartzman - If you are still having issues with the Docker testing, please share your `Dockerfile` we can reproduce the error.

**Comment by bilby91** [comment]
Nothing fancy here, pretty simple `Dockerfile`.

```
FROM node:8.9.1

ENV APP_HOME /var/www/app
ENV YARN_VERSION 1.3.2

# Install yarn
RUN curl -o- -L https://yarnpkg.com/install.sh | bash -s -- -- --version $YARN_VERSION

# Set the working directory
WORKDIR $APP_HOME

# Copy vendor submodules to let yarn install all the dependencies
COPY vendor/ ./vendor/

# Copy only package.json and yarn.lock for dependencies caching
ADD package.json yarn.lock ./

# Install dependencies
RUN yarn install

# Copy application code
ADD . $APP_HOME

# Compile javascript source
RUN yarn build

# Bot port
EXPOSE 8080
```

**Comment by nwhitmont** [comment]
Thanks for sharing @bilby91 👍

**Comment by nwhitmont** [comment]
reopen if you still have questions.
