### ISSUE TITLE
Mask password entry

### ISSUE THREAD

**Issue by DamienDoumer** [Microsoft/BotBuilder#3815]
## Bot Info 
* App ID: 
* SDK Platform: C#
* SDK Version: 3.11
* Deployment Environment: Auzure Bot Service, Azure App Service

### Mask password entry,
Please, I havn't found anywhere the ability to mask the user's password entry using the botframework
in C#, It will be great if this feature was added, since it will make password input more secure for scenarios where the user should login.

**Comment by xjose97x** [comment]
@DamienDoumer , I'm not aware of any channel that supports that (Facebook, Skype, Slack, etc). If you'd like to have a safe authentication system on your bot, check this video: https://channel9.msdn.com/Shows/Office-Dev-Show/Office-Dev-Show-Episode-34-Getting-Started-with-Bots-and-the-Microsoft-Graph

And here's the repo that you should check: https://github.com/MicrosoftDX/AuthBot

Best regards!

**Comment by DamienDoumer** [comment]
ok, thanks for your reply.

**Comment by EricDahlvang** [comment]
@DamienDoumer @xjose97x BotAuth is replacing AuthBot:
 https://github.com/richdizz/BotAuth/tree/master/CSharp  
https://www.nuget.org/packages/BotAuth/0.1.0-alpha

BotAuth has has providers for Azure AD v1, v2, and B2C applications as well as a generic OAuth2 provider that supports a number of other identities (Facebook, Google, LinkedIn, etc).
