### ISSUE TITLE
[Azure] Problem loading build options after moving bot app service to different subscription

### ISSUE THREAD

**Issue by osvc96** [Microsoft/BotBuilder#3817]
Hi, I'm really not sure if this is the place for an issue like this, so excuse me if I'm wrong.

## Issue Description

I have a Bot App Service in the Azure Portal. I had it in a subscription under a resource group called "pnibot", then I had to move it to another subscription, now under a resource group called "PNI". The app itself is working properly.
My problem is that when I click the resource to open it and get the build options (the view that lets you open the code editor or download the source code), I get this error:
"The Resource 'Microsoft.Web/sites/pnibot' under resource group 'pnibot' was not found."
As I said the bot works properly, and I can open the other tabs with no problem (Channels, Analytics, Settings), but I need to be constantly opening this view to work on the code and sometimes download it, so this is a tedious issue. Can anyone help?

## Reproduction Steps
1. Move an Azure Bot Service to a different subscription
2. Try to open the "Build" view of the resource

## Expected Behavior
Being able to open the code editor and download the source code

## Actual Results
Get error: "The Resource 'Microsoft.Web/sites/pnibot' under resource group 'pnibot' was not found."

**Comment by EricDahlvang** [comment]
Thank you for reporting this issue.

Please try using https://resources.azure.com/  There might be something that did not get moved correctly.

**Comment by JasonSowers** [comment]
@osvc96 We currently do not support moving a bot from one resource group and subscription to another.  You are going to have to create a new bot on the [Dev portal](https://dev.botframework.com).  We do plan to support this before our Preview status is removed (coming soon).

Do you still have your code or do you need help retrieving it?

**Comment by osvc96** [comment]
@JasonSowers I do have it, it can still be accessed but it's way less convenient (I have to go to Settings -> advanced settings ->App Service Editor). It's strange since the bot does work properly, it's only the Build tab that doesn't work.

**Comment by JasonSowers** [comment]
I agree it seems strange, but I assure you there is nothing that can be done on your end to remedy this.  This scenario is just not supported at this time, unfortunately.  Best of luck and let me know if you run into any other troubles.  We would be happy to help get you up and running again.
