### ISSUE TITLE
[Skype Web Control] User name not showing? (Not Recognizing the Email Address when user enter it)

### ISSUE THREAD

**Issue by satyansh-sagar** [Microsoft/BotBuilder#3820]
![skype1](https://user-images.githubusercontent.com/30821164/33195447-a1ee3b18-d0fd-11e7-8e04-e18801216159.PNG)
![skype2](https://user-images.githubusercontent.com/30821164/33195448-a2164b76-d0fd-11e7-9c76-be16c9278f9a.PNG)

I developed a simple chat bot to process which takes user details and email address, but when I'm entering the email address in skype embedded chat control ,I a getting a empty message (empty string) as in screenshot 2. As a result, I'm unable to validate my email address. (While the same code is working fine on web chat control and facebook).

**Comment by Chitma** [comment]
I also have the similar issue. Hope Skype Team fixes this.

**Comment by satyansh-sagar** [comment]
Someone Please Help me here , i'm stuck at this point...

@msftgits  @msgits2 @matvelloso

**Comment by nwhitmont** [comment]
Hi @satyansh-sagar - Thanks for reporting the issue. 

Can you share the bot code that produces this problem?

**Comment by satyansh-sagar** [comment]
@nwhitmont  Below is the Code Snippet, 

Validators().IsValidEmail is a method to validate the email address. 
The code is working perfectly on bot framework web chat channel and direct line , but having issues with skype.




public async Task PhoneNoProcessAsync(IDialogContext context, IAwaitable<string> result)
        {
                PromptDialog.Text(context, this.EmailAddressProcessAsync, "Enter your Email Address, Just type it below!", "Retry", 3);        
           
        }


        public async Task EmailAddressProcessAsync(IDialogContext context, IAwaitable<string> result)
        {
            var _emailAddress = await result;
            _emailAddress = _emailAddress.Trim().ToLower();
            
            bool _isEmailValid = new Validators().IsValidEmail(_emailAddress);
            if (_isEmailValid)
            {
               await context.PostAsync("Email Address is correct");
	       context.Done(True);
            }
            else
            {
                await context.PostAsync("Your Email Address seems to be incorrect.");
                PromptDialog.Text(context, this.EmailAddressProcessAsync, "Just type your E-mail Address below!", "Retry", 3);
            }
        }

**Comment by nwhitmont** [comment]
@satyansh-sagar Thanks for the update. 

For reference, what is the OS/browser/browser version in use where the Skype Web Control is having the error?

**Comment by nwhitmont** [comment]
@brene

**Comment by satyansh-sagar** [comment]
@nwhitmont  Its throwing an error everywhere, in chrome, Edge and IE.

**Comment by brene** [comment]
@satyansh-sagar I'm the PM for the Skype Web Control. I'm sorry that you're experiencing this bug. We're trying to get it fixed ASAP. I'll keep you updated

**Comment by satyansh-sagar** [comment]
Thanks @brene , Will awaiting your response

**Comment by brene** [comment]
@satyansh-sagar we've fixed this issue in our dogfood environment (see img). You can expect this to be on production by the end of this week. Keep the feedback coming!
![image](https://user-images.githubusercontent.com/4989523/33598371-c4b889fc-d9a2-11e7-95f2-5a11752355cf.png)

**Comment by satyansh-sagar** [comment]
@brene  Great Job , Hope to see it live soon.
