### ISSUE TITLE
[Localization] Chinese localizer cannot work when register default dialog is as the second parameter in the constructor of UniversalBot

### ISSUE THREAD

**Issue by lijiarui** [Microsoft/BotBuilder#3824]
## Bot Info 
* SDK Platform:  Node.js
* SDK Version:  3.12.0
* Active Channels:  WeChat ( I write a connector for [Wechaty](https://github.com/chatie/wechaty))
* Deployment Environment: other

## Issue Description

Chinese localizer cannot work when register default dialog is as the second parameter in the constructor of UniversalBot

I read the latest [doc](https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-dialog-overview), it said:
> Prior to Bot Framework version 3.5, a root dialog is defined by adding a dialog named /, which lead to naming conventions similar to that of URLs. This naming convention wasn't appropriate to naming dialogs.
> Starting with version 3.5 of the Bot Framework, the default dialog is registered as the second parameter in the constructor of 

When I use  a dialog named `/`, it can localize to Chinese successfully, but when I register default dialog is as the second parameter, it will throw the following error
```shell
TypeError: _this.library(...).selectRoute is not a function
    at disambiguateRoute (/home/ubuntu/workspace/node_modules/botbuilder/lib/bots/UniversalBot.js:398:62)
    at /home/ubuntu/workspace/node_modules/botbuilder/lib/bots/UniversalBot.js:407:21
    at /home/ubuntu/workspace/node_modules/async/lib/async.js:52:16
    at Object.async.forEachOf.async.eachOf (/home/ubuntu/workspace/node_modules/async/lib/async.js:236:30)
    at Object.async.forEach.async.each (/home/ubuntu/workspace/node_modules/async/lib/async.js:209:22)
    at /home/ubuntu/workspace/node_modules/botbuilder/lib/bots/UniversalBot.js:386:19
    at /home/ubuntu/workspace/node_modules/botbuilder/lib/bots/Library.js:64:17
    at next (/home/ubuntu/workspace/node_modules/botbuilder/lib/dialogs/IntentRecognizer.js:68:17)
    at IntentRecognizerSet.IntentRecognizer.filter (/home/ubuntu/workspace/node_modules/botbuilder/lib/dialogs/IntentRecognizer.js:71:9)
    at /home/ubuntu/workspace/node_modules/botbuilder/lib/dialogs/IntentRecognizer.js:20:31
    at /home/ubuntu/workspace/node_modules/botbuilder/lib/dialogs/IntentRecognizerSet.js:80:17
    at /home/ubuntu/workspace/node_modules/async/lib/async.js:52:16
    at replenish (/home/ubuntu/workspace/node_modules/async/lib/async.js:306:28)
    at /home/ubuntu/workspace/node_modules/async/lib/async.js:326:29
    at /home/ubuntu/workspace/node_modules/async/lib/async.js:44:16
    at /home/ubuntu/workspace/node_modules/botbuilder/lib/dialogs/IntentRecognizerSet.js:72:21
    at TextRequest.<anonymous> (/home/ubuntu/workspace/node_modules/api-ai-recognizer/index.js:86:21)
    at emitOne (events.js:96:13)
    at TextRequest.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/ubuntu/workspace/node_modules/apiai/module/json_api_request.js:46:26)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```
### The follwing code can work as expect
```ts
let Msbot = new builder.UniversalBot(wechatyConnector
    ,{localizerSettings: { defaultLocale: 'zh-Hans' }}
  )
  // See https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-dialog-overview
  Msbot.dialog('/', function (session) {
    session.send('你好，我是你的订票助理.')
  })
```

### The following code cannot work as expected. it will throw an error as just said.

```ts
let Msbot = new builder.UniversalBot(wechatyConnector, 
    // See https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-dialog-overview
    function (session) {
      session.send('你好，我是你的订票助理.')
    }
    ,{localizerSettings: { defaultLocale: 'zh-Hans' }}
  )
```

**Comment by nwhitmont** [comment]
Hi @lijiarui  - In your second code example, you are passing the localizer settings as the third arg to the UniversalBot constructor function, which does not match the function signature.  

See: https://github.com/Microsoft/BotBuilder/blob/master/Node/core/src/bots/UniversalBot.ts#L94

How to define the default dialog using the UniversalBot constructor:
```js
var bot = new builder.UniversalBot(connector, [
    //...Default dialog waterfall steps here
]);

```

**Comment by nwhitmont** [comment]
Hi @lijiarui - Were you able to get it working using the example code I provided? Let me know if you have any other questions.

**Comment by lijiarui** [comment]
Thanks! It works!

Also I have a question, latest [doc](https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-dialog-overview), it said:
> Prior to Bot Framework version 3.5, a root dialog is defined by adding a dialog named /, which lead to naming conventions similar to that of URLs. This naming convention wasn't appropriate to naming dialogs.
> Starting with version 3.5 of the Bot Framework, the default dialog is registered as the second parameter in the constructor of UniversalBot

Then, How to localize to Chinese when the default dialog is registered as the second parameter in the constructor of UniversalBot? Could you help to give a example?

Thanks!

**Comment by nwhitmont** [comment]
I agree, it is confusing because  the `UniversalBot` class has multiple constructors which means the second input parameter could represent different things depending of the number of input parameters to the class constructor. 

If you want to configure your bot with localization settings, you can do that in the constructor without adding a default dialog.  Example:

```js
// create the bot with the locale settings
var bot = new builder.UniversalBot(connector, {
    localizerSettings: { 
        defaultLocale: "cn" 
    }
});

// configure the default dialog
bot.dialog('/', function (session) {
  session.send("Hello world");
});
```

**Comment by lijiarui** [comment]
Thanks for your example!

If I use `session.preferredLocale`, should I write it in each dialog, or I just config it in default dialog, then other dialogs would use this setting as default?

**Comment by nwhitmont** [comment]
@lijiarui If you config the `session.preferredLocale` in your default dialog, then all dialogs after that will use the same settings. 

While doing some further research, I found another way to set `localizerSettings` independent of any dialog:
```js
// Configure bots default locale and locale folder path.
bot.set('localizerSettings', {
    botLocalePath: "./customLocale", 
    defaultLocale: "en" 
});
```

Taken from the localization example available here:
https://github.com/Microsoft/BotBuilder/blob/master/Node/examples/basics-localization/app.js#L64

**Comment by nwhitmont** [comment]
Some additional info on localization you may also find useful:
https://blog.botframework.com/2017/05/24/using-local-reg-exp-recognizer-node/

**Comment by lijiarui** [comment]
Got it, thanks for your explanation!
