### ISSUE TITLE
[Cortana] Channel is only available to Bot Framework accounts associated with a Microsoft account?

### ISSUE THREAD

**Issue by maheshksingh** [Microsoft/BotBuilder#3826]
## Bot Info 
* SDK Platform:.NET
* Active Channels: Skype,Direct Line
* Deployment Environment: Auzure Bot Service

## Issue Description
When I try registering the Cortana channel for my BOT it says "Cortana channel is only available to Bot Framework accounts associated with a Microsoft account". But the one am using is the Microsoft account.

Not sure what to do next?

Please help.
Mahesh

**Comment by maheshksingh** [comment]
I think its both an AAD account and also a Microsoft account at the same time.. is that an issue?

**Comment by nwhitmont** [comment]
@maheshksingh To clarify, you need to use a MSA type personal "Microsoft Account" not an Active Directory (AAD) based account to register the bot and add Cortana channel. 

Let me know if you have any other questions.

**Comment by maheshksingh** [comment]
@nwhitmont, Thanks for the reply...

aaah, not sure why Microsoft has such limitations, now I need to re-register my BOT with my personal MSA account, lets hope thats works,

Thanks again.
Mahesh

**Comment by DanielTizon** [comment]
Yeah, it's a problem for me too. In my company, we have some bots and we want to use cortana channel, but incredibly I have to create a new account and I can't use corporative account. It sounds a bit weird, even for Microsoft.

**Comment by maheshksingh** [comment]
That's the sad fact.... But I  dint really research since  a few weeks if things changed... Had raised a ticket with Microsoft but they never came back.
. If  you found an alternative then let all know..

**Comment by bw-kforce-ms** [comment]
The answer, as of now, if you are building a consumer skill, you still need the "channel" to be owned by an MSA.  So, you can
1/ develop a bot using an AAD account, and host it on a tenant using an appropriate subscription
2/ create a bot channel registration and app registration from an MSA, and point it at the bot message endpoint
3/ update your bot to use the appid and password from 2

It is not ideal, but this is how it works for now, UNLESS you are looking at the enterprise skills, that are created under AAD accounts on azure tenants, and the channel is owned by the AAD account. This tech is approaching private preview, and off/on again there is on boarding through https://docs.microsoft.com/en-us/cortana/enterprise/overview. For the super eager, there is a mail drop cortanae@microsoft.com where you can send questions.
