### ISSUE TITLE
[Cortana] How to setup Chatbot on Raspberry Pi with Voice Recognition?

### ISSUE THREAD

**Issue by maheshksingh** [Microsoft/BotBuilder#3828]
## Bot Info 
* SDK Platform: .NET
* Active Channels: Skype, Slack, Direct Line, (Yet to configure the Cortana Channel)
* Deployment Environment: Azure Bot Service

## Issue Description
Hello there, We at Volvo are trying to make the Microsoft Chatbot go headless, meaning no UI, and that can be used at assembly lines based on voice commands, without physically typing the wake up commands.

Now we have the following options:
Option1: Use the Win 10 IOT core on RPI, and use the Cortana as the channel and use the Cortana to ask our BOT to perform the task for us.

Steps with Option1:
- We haven't tried this yet, but it needs the personal MSA account for BOT registration and the same account should be used for Azure services, as well as for Cortana
- Then install the Win 10 IOT core on RPI, Enable Cortana with the same MSA account, and trigger the Cortana asking to wake up the BOT

Issues with Option1:
- Cannot customize the wake up call (Hello Cortana.. ask BOT to check order status), instead can we wake up the BOT directly?
- Secondly, not sure if we restart the RPI, and say (Hello Cortana), will that automatically trigger the Cortana

Is there any other way/option of making the Microsoft BOT headless, ???

Please suggest 

Thanks.

**Comment by nwhitmont** [comment]
@maheshksingh great question.  

Currently Cortana is available on Windows 10 and the H&K Invoke Speaker.  

For more on supported devices, checkout: https://www.microsoft.com/en-us/cortana/devices

Let me know if you have any questions or contact me at v-niwh@microsoft.com

**Comment by nwhitmont** [comment]
Hi @maheshksingh - I found some additional information which may help.

You can setup Cortana on Windows IoT Core (preview):

>IoT Core is an edition of Windows 10 and is optimized for small-footprint and low-cost IoT devices. Cortana is enabled on IoT Core in the Windows 10 Creators Update. It is in preview now. 

Video overview:
https://channel9.msdn.com/Blogs/One-Dev-Minute/Cortana-on-Windows-10-IoT-Core

For more information:
https://docs.microsoft.com/en-us/windows/iot-core/extend-your-app/cortanaoniotcore

**Comment by mirsaeedi** [comment]
Does it still require a screen?
I couldn't find any information related to this requirement.
If it requires, how have they managed to have in on Harman Kardon Invoke?

**Comment by maheshksingh** [comment]
Hey

Yes we managed to make it work on invoke... With one limitation.. That the
botlet won't work for corporate accounts and works only on Microsoft or
personal id's...

Thanks

**Comment by mirsaeedi** [comment]
Thanks @maheshksingh. 
So, you mean that having a screen is no more a requirement for Cortana on Windows IoT Core? Can you provide me with a link to this change?

**Comment by maheshksingh** [comment]
I don't have a doc... What u do is setup the cortana with the screen
initially... Then login the iot core desktop app and set cortana as the
startup program... Then disconnect the screen and reboot the Raspberry...
Then when it starts the cortana starts by default and you won't need a
screen.. Just say hey cortana and wait for a prompt sound 🔊... You are done

Regards

**Comment by maheshksingh** [comment]
To rephrase the sentence.. By saying... Login win 10 iot core desktop app..
mean.. You need to login ur pi from the iot core desktop app using its ip
address.... Just incase am confusing u.. .

Regards

**Comment by mirsaeedi** [comment]
@maheshksingh Thanks a lot :)
