### ISSUE TITLE
[Question] How to setup Bot Framework messaging endpoint using custom port configuration?

### ISSUE THREAD

**Issue by midhunCherrylabs** [Microsoft/BotBuilder#3829]
is it possible to use Bot-framework Messaging endpoint in custom port , such as 

**https://bot.domain.com:4000/api/messages**

**Comment by msmohan** [comment]
Please follow instructions mentioned [here](https://docs.microsoft.com/en-us/azure/app-service/environment/app-service-app-service-environment-control-inbound-traffic#special-considerations-for-explicit-ip-ssl).

**Comment by nwhitmont** [comment]
As long as you have a **valid SSL certificate** that is configured to run secure traffic over your custom port.  

In general we recommend using the standard HTTPS port 443.

_Details from the above linked article:_

## Special Considerations for Explicit IP-SSL

>If an app is configured with an explicit IP-SSL address (applicable only to ASEs that have a public VIP), instead of using the default IP address of the App Service Environment, both HTTP and HTTPS traffic flows into the subnet over a different set of ports other than ports 80 and 443.

>The individual pair of ports used by each IP-SSL address can be found in the portal user interface from the App Service Environment's details UX blade. Select "All settings" --> "IP addresses". The "IP addresses" blade shows a table of all explicitly configured IP-SSL addresses for the App Service Environment, along with the special port pair that is used to route HTTP and HTTPS traffic associated with each IP-SSL address. It is this port pair that needs to be used for the DestinationPortRange parameters when configuring rules in a network security group.

>When an app on an ASE is configured to use IP-SSL, external customers will not see and do not need to worry about the special port pair mapping. Traffic to the apps will flow normally to the configured IP-SSL address. The translation to the special port pair automatically happens internally during the final leg of routing traffic into the subnet containing the ASE.

**Comment by msmohan** [comment]
@midhunCherrylabs 
Hope you got an answer.
Please feel free to reopen this thread if you have more questions.
