### ISSUE TITLE
Bot not working in inline mode on telegram

### ISSUE THREAD

**Issue by fercom** [Microsoft/BotBuilder#383]
My bot works when you send it a message but if it is in a group and you try to call it it just seems to be loading but nothing happens.
The bot is [https://telegram.me/the_MemeBot](url) if you want to test it.

Inline mode is enabled, I don't know what is happening.

Thanks

**Comment by eanders-MS** [comment]
Looks like we're not forwarding the Telegram message in the inline query case. Working on a fix now.

**Comment by eanders-MS** [comment]
Related: #366

**Comment by eanders-MS** [comment]
Fix deployed to production. Please see #366 for sample inline query reply message.
