### ISSUE TITLE
[Bot Portal] Bots are gone from `My Bots` view in portal (but are still active)

### ISSUE THREAD

**Issue by bramvdl** [Microsoft/BotBuilder#3830]
## Bot Info 
* App ID: multiple (b71c3fa4-397d-4c26-9674-ab39d0f106f7, 0496bd4a-3b96-4bd3-a3d4-9d552bc0231d)
* SDK Platform: Node.js
* SDK Version: 3.6.0
* Active Channels: Messenger
* Deployment Environment: Debian VM

## Issue Description
On of our production bots stopped responding, upon inspecting we found the following error: " ChatConnector: receive - invalid token. Check bot's app ID & Password". When going to the bot portal to find my app id I got a "You don't have any bots or skills yet." screen. This is strange because there should be 3 bot currently running. Zjef (prod / https://www.facebook.com/startzjef/), Zjef Test (test), Azure Zjef (acceptance). I've seen more issues with this error, but did not find a solution. Has there been a change in the portal or bots I missed?

## Expected Behavior
I expected to login to dev.botframework.com with my microsoft account (bram [at] weareblis.com) to see the details of the bots we created (this worked fine 2 weeks ago, when i checked last)

## Actual Results
After login to dev.botframework.com it says i have no bots. Which is strange because i created them, and they are currently running. e.g. working fine or giving errors. 

Kind regards,
Bram van der Linden

**Comment by nwhitmont** [comment]
@bramvdl What happens when you log out of your Microsoft account and log back in?

When I checked on your bot, it was available in the bot portal,  but the bot itself did not respond to messages in the WebChat test control.

**Comment by bramvdl** [comment]
@nwhitmont I tried logging in and out a few times (also using different browsers), but it keeps telling me I don't have any bots or skills yet. Weird thing is I know it's still somewhere because the production bot is logging errors, but i just can't find it in my portal. What's the best solution/workaround here? Because the error log is giving me a wrong app id code, should i just create/connect a new bot?

**Comment by EricDahlvang** [comment]
@bramvdl You mentioned (bram [at] weareblis.com) is the email account these bots are registered with.  Could you be mistaken about this?

**Comment by nwhitmont** [comment]
@bramvdl It looks like the bot is registered to another email address than "bram".  Due to security considerations, I cannot provide this address here.

You need to either:
- A - Login to the bot portal with the email account that you used to register the bot
- B - Create a new bot registration using your current/active email account and point the new registration to your bot's `/api/messages` endpoint.

**Comment by EricDahlvang** [comment]
@bramvdl After further investigation, we've determined that we are able to assist you through other channels.  Closing this issue.
