### ISSUE TITLE
While connecting to MS SQL server(hosted on Azure env with public IP) from Azure bot services I get an error:  {"code":"MethodNotAllowed","message":"GET is not allowed"}. Any idea why?

### ISSUE THREAD

**Issue by suryadeepchatterjee3107** [Microsoft/BotBuilder#3832]
## Bot Info 
* App ID: 
* SDK Platform: 
* SDK Version: 
* Active Channels: 
* Deployment Environment: 

## Reproduction Steps
1.
2.
3.

**Comment by nwhitmont** [comment]
closing as user did not provide any issue description

**Comment by JasonSowers** [comment]
Duplicate of https://stackoverflow.com/questions/47525893/unable-to-connect-to-ms-sql-server-from-azure-bot-services
