### ISSUE TITLE
[Direct Line] WebChat doesn't receive messages but Skype does?

### ISSUE THREAD

**Issue by JWThewes** [Microsoft/BotBuilder#3833]
## Bot Info 
* App ID: 7b2d3f87-a7da-4956-943c-6127ecd10c4b
* SDK Platform: Direct Line
* Active Channels: Skype, Direct Line
* Deployment Environment: CloudFoundry (Pivotal Web Services)

## Issue Description
I've set up an bot and tested successfully with the emulator. I deployed the Bot to CloudFoundry and tried to test it with the BotFramework WebClient (https://github.com/Microsoft/BotFramework-WebChat#easy-in-your-non-react-website-run-web-chat-inline).
I tried to send messages to the bot and this works. But the WebChat doesn't get any messages back. I have no errors on the server side.

What is really strange:
I added the Bot to my Skype account. And here the Bot works as expected. This is the same backend code that is used for the WebChat and in Skype it works.

Response Log I get from the POST to the BotFramework:
"POST /messages HTTP/1.1" 200 531 0 "-" "BF-DirectLine (Microsoft-BotFramework/3.2 +https://botframework.com/ua)" "10.10.2.186:11906" "10.10.149.144:61025" x_forwarded_for:"40.127.186.114, 10.10.2.186" x_forwarded_proto:"https" vcap_request_id:"7b71e4c1-fde3-4603-4c88-8ad2ccd9c92d" response_time:0.116871433 app_id:"18a5b94d-a3dc-478d-954e-12c36c487fae" app_index:"0" x_b3_traceid:"b69dd7fb56afbaef" x_b3_spanid:"b69dd7fb56afbaef" x_b3_parentspanid:"-"

## Expected Behavior
I would expect the WebChat to receive messages.

## Actual Results
WebChat doesn't receive messages but Skype does.

**Comment by nwhitmont** [comment]
@JWThewes Does your hosting server have a valid SSL certificate for your domain serving the bot's `/api/messages` endpoint? If not, then this is your problem.

**Comment by JWThewes** [comment]
@nwhitmont Yeah of course. If that wouldn't be a valid SSL certificate Skype shouldn't work either, correct?

**Comment by JWThewes** [comment]
@nwhitmont You can check it here: https://iko-dev.cfapps.io/messages

**Comment by JWThewes** [comment]
@nwhitmont Any further ideas?
