### ISSUE TITLE
[Card Actions] messageBack does not work on Skype and FB Messenger?

### ISSUE THREAD

**Issue by martinoss** [Microsoft/BotBuilder#3835]
## Bot Info 
* SDK Platform: .NET
* SDK Version: 3.12.2.4
* Active Channels: WebChat, Skype, Facebook
* Deployment Environment: Azure App Service

## Issue Description
I created a carousel, with two HeroCards. Each have a button (CardAction) to select the item. If the user clicks on the button (the button title should be **"select"**), I expect the user to see `displayText`. The bot should receive `value`.
According [this documentation ](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-cards) I changed my code to use "messageBack" as type action.

- ❌ In the emulator, the cards look ok, but pressing the button `select` shows no reaction
- ❌ In Skype, the card does not display the buttons and tapping the card has no effect
- ❌ In Facebook, I get this error:
`SendActivityToUserAsync FAILED: {"error":{"message":"(#100) Web url cannot be empty for url type button","type":"OAuthException","code":100,"error_subcode":2018041,"fbtrace_id":"H6Ks6dWw\/H0"}}`

## Code Example
This is how the message looks in the emulator:

```
...
"attachments": [
    {
      "contentType": "application/vnd.microsoft.card.hero",
      "content": {
        "title": "Title A",
        "text": "Text A",
        "images": [],
        "buttons": [
          {
            "type": "messageBack",
            "title": "select",
            "displayText": "Display Text A",
            "value": "Value A",
            "text": "Value A"
          }
        ]
      }
    },
    {
      "contentType": "application/vnd.microsoft.card.hero",
      "content": {
        "title": "Title B",
        "text": "Text B",
        "images": [],
        "buttons": [
          {
            "type": "messageBack",
            "title": "select",
            "displayText": "Display Text B",
            "value": "Value B",
            "text": "Value B"
          }
        ]
      }
    }
  ],
...
```

**UPDATE 11/29/2017,** @JasonSowers  Code Example

```cs
private Activity CreateCarousel(IDialogContext context, IReadOnlyList<Vehicle> vehicles)
{
	var carouselActivity = (Activity)context.MakeMessage();
	carouselActivity.AttachmentLayout = AttachmentLayoutTypes.Carousel;

	var attachments = new List<Attachment>();

	foreach (var vehicle in vehicles)
	{
		var attachment = CreateHeroCard(
			title: vehicle.Make,
			text: vehicle.Vin,
			cardAction: new CardAction(
				type: ActionTypes.MessageBack,
				displayText: vehicle.Make,
				title: "select",
				text: vehicle.Vin,
				value: $"{{\"vin\": \"{vehicle.Vin}\"}}"));

		attachments.Add(attachment);
	}

	carouselActivity.Attachments = attachments;

	return carouselActivity;
}

private Attachment CreateHeroCard(string title, string text, CardAction cardAction)
{
	var heroCard = new HeroCard
	{
		Title = title,
		Text = text,
		Buttons = new List<CardAction>() { cardAction }
	};

	return heroCard.ToAttachment();
}
```

## Expected Behavior
I expect all channels to behave like this:
Show a carousel with two cards, each having a button called "select". Pressing that button will display the selection to the user (displayText) and the bot receives "value" respective "text".

## Actual Results
see issue description

**Comment by JasonSowers** [comment]
Can you please post your code so we can better assist you

**Comment by JasonSowers** [comment]
Just saw your Update, Sorry for the delayed response.  Try using `ActionType.ImBack` instead of `ActionType.MessageBack`
  
I tested with the following code and it was working with no problems:

```cs
    [Serializable]
    public class RootDialog : IDialog<object>
    {
        public Task StartAsync(IDialogContext context)
        {
            context.Wait(MessageReceivedAsync);

            return Task.CompletedTask;
        }

        private async Task MessageReceivedAsync(IDialogContext context, IAwaitable<object> result)
        {
            var activity = await result as Activity;


            List<Vehicle> vehicles = new List<Vehicle>();
            Vehicle a = new Vehicle();
            a.Make = "1";
            a.Vin = "2";
            vehicles.Add(a);
            Vehicle b = new Vehicle();
            b.Make = "3";
            b.Vin = "4";
            vehicles.Add(b);
            // return our reply to the user
            await context.PostAsync(CreateCarousel(context, vehicles));

            context.Wait(MessageReceivedAsync);
        }

        private Activity CreateCarousel(IDialogContext context, List<Vehicle> vehicles)
        {
            var carouselActivity = (Activity)context.MakeMessage();
            carouselActivity.AttachmentLayout = AttachmentLayoutTypes.Carousel;

            var attachments = new List<Attachment>();

            foreach (var vehicle in vehicles)
            {
                var attachment = CreateHeroCard(
                    title: vehicle.Make,
                    text: vehicle.Vin,
                    cardAction: new CardAction(
                        type: ActionTypes.ImBack,
                        displayText: vehicle.Make,
                        title: "select",
                        text: vehicle.Vin,
                        value: $"{{\"vin\": \"{vehicle.Vin}\"}}"));

                attachments.Add(attachment);
            }

            carouselActivity.Attachments = attachments;

            return carouselActivity;
        }

        private Attachment CreateHeroCard(string title, string text, CardAction cardAction)
        {
            var heroCard = new HeroCard
            {
                Title = title,
                Text = text,
                Buttons = new List<CardAction>() { cardAction }
            };

            return heroCard.ToAttachment();
        }
    }

    public class Vehicle
    {
        public string Vin { get; set; }
        public string Make { get; set; }
    }
}
```

**Comment by martinoss** [comment]
ImBack is what I currently use as workaround. The downside of this is, on Facebook, when pressing the button, the user sees “select“ as his answer. In Skype and webchat its the Vin. 
I wished to have the make of the car as visible reply. 
According the docs for MessageBack this shoud ne possible.

**Comment by JasonSowers** [comment]
Maybe `ActionTypes.PostBack` would be best for your needs?  That way the customer doesn't see the message at all.

**Comment by JasonSowers** [comment]
Closing this, please let me know if you would like to reopen.

**Comment by martinoss** [comment]
@JasonSowers Can you please reopen this issue? `messageBack` does not behave like stated in the documentation and it's a bug in my eyes. 
The behavior described in the docs is actually exactly what I've been looking for and would result the best user experience.
Using `imBack` or `PostBack` is ok as workaround but I hope `messageBack` can be fixed, so I can switch to it later on.

**Comment by JasonSowers** [comment]
@martinoss The documentation in question is titled **Add cards and card actions in a Microsoft Teams bot** and is for **Microsoft Teams** bots only.  There are a few Microsoft teams only `ActionTypes` and `MessageBack` is one of them, that is the reason for the confusion there.

**Comment by martinoss** [comment]
@JasonSowers Ohh, you're right. Sorry, I din't notice that :see_no_evil:

**Comment by JasonSowers** [comment]
Happens to the best of us.  Good luck my friend
