### ISSUE TITLE
[Cortana] Why can't skill be invoked by other users during testing?

### ISSUE THREAD

**Issue by rjgmail88** [Microsoft/BotBuilder#3836]
## Bot Info 
* App ID: **984ede7e-bc35-4767-a19b-60a2d6c5e4be**
* SDK Platform: Node.js
* SDK Version: 
* Active Channels: Cortana , Direct Line
* Deployment Environment: Azure App Service

## Issue Description
I have created a bot service on node.js and added Cortan channel. An issue is my Cortana skill is not getting invoked from any other MSA'a. Ex: I have 4 MSA's described and used as follows. 
Account 1 (my own gmail MSA)- used to register the bot, added Cortana channel and on Manage Cortana dashboard added following 3 accounts to in Deployed to group to deploy my skill to 3 different users. Finally, I Shared the link with following user to accept the skill request. 
Account 2 (gmail) - User accepted the skill request.
Account 3 (outlook) (my own) - User accepted the skill request.
Account 4 (outlook) (someone else) - User accepted the skill request.

Users with account 2,3,4 are not able to invoke a skill by saying 'ask bot' or 'launch bot' or any other invocation phrases in Cortana app. I tried changing the invocation name but did not help. 

Only user with account 1 (owner of everything ) is able to do so.

## Code Example
Not required. 

## Reproduction Steps
1. Login to Cortana notebook with MSA 
2. Say 'open calbot' or  'ask calbot' or  'launch calbot'
3. Bing search open instead Cortana Skill I am expecting. 

## Expected Behavior
User should be getting connected to Cortana skill.  

## Actual Results
Bing search open instead Cortana Skill I am expecting.

**Comment by JasonSowers** [comment]
@rjgmail88 I just check in your [cortana channel page](https://dev.botframework.com/bots/channels?id=cernercalendarhelpbot&channelId=cortana) on the [Bot Portal](https://dev.botframework.com) and found the following error:
  
![image](https://user-images.githubusercontent.com/6301037/33349678-0a7d1e88-d450-11e7-95cb-802ca501f698.png)

**Comment by rjgmail88** [comment]
Hey JasonSowers, I did not get you. Cortana channel is already added for not bot #984ede7e-bc35-4767-a19b-60a2d6c5e4be
An error you mentioned is only possible when you try to add Cortana channel using non-MSA account on Bot Portal.

**Comment by EricDahlvang** [comment]
Based on your configuration, 2,3&4 should be able to invoke the skill.  Can you make sure that users are logged in with the MSA id in Cortana?  You can check by going to Cortana -> Notebook -> About Me section.

There is also this msdn forum, where you might find an answer: https://social.msdn.microsoft.com/Forums/en-US/home?forum=cortanaskillskit

**Comment by rjgmail88** [comment]
Thanks Eric. Yes, configuration looks correct as this same thing used to work for users before. Suddenly, it stoped worked when I added one more user to the group access. I had confirmed with users 2,3 and 4 by navigating to access link and it shows 'Leave this skill' option. So that confirms skill is deployed to their MSA's. 

Thanks for the forum link.

**Comment by JasonSowers** [comment]
@rjgmail88 ignore my comment it seems out admin accounts do not let us look at Cortana configurations.  I see that error on every bot's Cortana channel, apologies.

**Comment by Suneethae7** [comment]
is this issue resolved? facing same issue. after adding the users in group. user not able invoke the Cortana which is published.help me on this

**Comment by rjgmail88** [comment]
Yes, it is resolved for me. Looks like it took a while to update the skill in MS bucket so user could invoke it. You need to make sure following things are in place.

1. Make sure user have accepted the skill request.
2. Yours login to Cortana App with the same MSA account.
3. Cortana invocation name is correct.
4. There is not speech to text issue while invocation. If so you can type 'launch {invocation phrase}'

apart from all of these looks like dev.botframework.com site and other MS sites are under maintenance due to which currently, I don't see an option to 'Configure Cortana'. I'm not sure why its removed. So site maintenance might be causing your issue.

**Comment by EricDahlvang** [comment]
Closing this issue since it appears to be resolved.
