### ISSUE TITLE
[Auth] Getting error "HTTP status code Unauthorized" on .NET SDK v3.8.0?

### ISSUE THREAD

**Issue by sirjohn** [Microsoft/BotBuilder#3839]
## Bot Info 
* App ID: 29215cb0-abae-4b71-92e6-fdf985c918a7
* SDK Platform: .NET (C#, VS2015)
* SDK Version: 3.8.0
* Active Channels: DirectLine
* EndPoint: https://chatbot.hbtrinside.com/

## Issue Description
Hello,

Im trying to test sample.  

I Have used my app id and app passsword in webconfig file, also after I have got an error as unauthorized, I have changed my password again from settings. Still I couldnt connect to bot via direct line and also on test platform in https://dev.botframework.com/bots.  (I have connected to the same bot about to a month before with the same app id and password)

Thanks for the help.

## Actual Results
![image](https://user-images.githubusercontent.com/1131835/33364048-c9c2cf42-d4f3-11e7-80f3-64f72b95ced7.png)

![image](https://user-images.githubusercontent.com/1131835/33364252-9f89013c-d4f4-11e7-80c0-a5e9e02a4a7e.png)

**Comment by EricDahlvang** [comment]
Security protocols have changed since .net sdk 3.8.0.  Please upgrade the .net sdk to the latest version: https://www.nuget.org/packages/Microsoft.Bot.Builder/

From: https://blog.botframework.com/2017/05/07/bot-framework-auth-change/

> UPDATED 08/08/2017: We revised our security protocols on July 31, 2017. Update to Bot Builder 3.9+ or compatible security configuration to keep your bot working

**Comment by sirjohn** [comment]
Thank you. Problem was solved.

**Comment by Nada-Abdelkader** [comment]
How did you solve this?
