### ISSUE TITLE
[Skype Windows Store App] One of my Bots shows "Messaging Unavailable" only on the Skype Windows Store App - 12.9.599.0 

### ISSUE THREAD

**Issue by Kris-Nimmagadda** [Microsoft/BotBuilder#3841]
## Bot Info 
* App ID: edabd4e0-f218-4ab5-8243-2e1709a7de4e
* SDK Platform:  .NET
* Active Channels: Skype, Direct Line 
* Deployment Environment: Azure App Service 

## Issue Description
I recently developed a Bot and added it to my skype. It was working fine. In between I blocked the Bot and unblocked the same.  From then on, on my Windows Store App, it doesn't allow me to type anything and says "Messaging Unavailable", but on my Skype Desktop version, I am able to use it as usual, on Web version also it is fine. I tried uninstalling and installing the Skype Windows App, Tried resetting it too - same thing.  I also tried logging into the Windows 10 Skype App from other machine, there also it was not allowing me to send Message and it says "Messaging unavailable" and the text box to type messages is greyed-out. 
I posted this on Skype community also (https://answers.microsoft.com/en-us/skype/forum/skype_win10-skype_messms-skype_instamessms/one-of-my-bots-shows-messaging-unavailable-only-on/7757a5cb-456f-4732-a81a-97d6a9eab4d2?auth=1), and they redirected me to Bot forum and hence posting it here too.
Any help is appreciated. 

## Reproduction Steps
1. Deploy the Bot to Azure App Service
2. Add the Bot to Windows 10 Skype App
3. Use the Bot for sometime
4. Block the Bot 
5. Unblock the Bot 
6. Now I am not able to send messages using the Windows 10 Skype App - all works fine on Web and Desktop version of skype.

## Expected Behavior
After unblocking the Bot, it should work as usual on Windows 10 Skype App like it is working on Web and Desktop versions of skype.

## Actual Results
On, Windows 10 Skype App the Bot shows "Messaging unavailable" and the text area to type the message is greyed-out (disabled).

**Comment by nwhitmont** [comment]
@Kris-Nimmagadda Thanks for reporting - I have forwarded the issue to the Skype team for investigation.

**Comment by Kris-Nimmagadda** [comment]
Hi @nwhitmont , thank you for the response.  Any quick help is appreciated.

**Comment by Kris-Nimmagadda** [comment]
Hi @nwhitmont ,
Quick update, on the Skype forum, I got a reply that I should install the new version of Skype windows store App, I tried that and there is no change in the behaviour. 

I wonder how the "state" could be different for different facets of an Application [Skype in this case] - like it works in Skype Web, Skype Desktop and not work on Skype Windows 10 App (across devices) - shouldn't all read the "state" from a central (and/or replicated) location and behave accordingly ? 

Quite surprising !

**Comment by Kris-Nimmagadda** [comment]
I am still stuck ! Any help please ?

**Comment by JasonSowers** [comment]
Please reach out to Skype support if you are still experiencing issues with this.
