### ISSUE TITLE
[Cortana] How to save user access token when user connects to skill?

### ISSUE THREAD

**Issue by rjgmail88** [Microsoft/BotBuilder#3850]
## Bot Info 

SDK Platform: Node.js
Active Channels: Cortana , Direct Line
Deployment Environment: Azure App Service

## Issue Description
In bot service ROOT dialog is triggered when non dialog is matched/triggered by LUIS. Also from Cortana Root dialogs is triggered when you just invoke a skill w/o utterance. Ex: launch {skillName}

I have enabled Cortana sign-in at invocation so when user tried to use a skill it will go through login process. In this case I will have access to authToken which I can decode and grab user info. But. I am doing this in ROOT dialog as shows bellow. Is there a way to have global function or some place where I can place this code so it will always set decoded values form auth token ? 

When user says launch {skillName} {utterance} then root dialog code is skipped so I dont have access to user info. 

## Code Example
```js
//ROOT dialog:- This piece of code is only executed when non on the intent is match by LUIS or when I just invoke my skill in Cortana by saying . 'Launch Cal' or 'Open cal' where 'cal' is my skill name.

var bot = new builder.UniversalBot(connector, function (session) {

var authorizationToken = session.message.entities.find((e) => {
            return e.type === 'AuthorizationToken';
        });
var decodedtoken = jwtDecode(authorizationToken.token);

var authusername = decodedtoken.name
var authuseremail = decodedtoken.upn

session.say(`Hi ${authusername} Welcome to "Cal". I am your digital assistant.`, 
     `Hi ${fullName} Welcome to "Cal". I am your digital assistant.`);
}
```

## Reproduction Steps
1. Type/say in Cortana :- Ask cal to schedule something 
2. LUIS will trigger bot.dialog('schedule')... and ROOT dialog code will not run.
3. In 'schedule'  I won't have access to authusername and authuseremail.

## Expected Behavior
When use tries to invoke a skill with or without passing utterance, a default piece of code should run and set authusername, authuseremail from auth token. I have enable Cortana sign-in at invocation. 

## Actual Results
1. When control goes to ROOT dialog then only authusername and authuseremail is set.
2. When control goes to any other LUIS triggered dialogs, authusername and authuseremail is not set.

**Comment by nwhitmont** [comment]
Hi @rjgmail88 - Check out this AuthBot sample - it demonstrates how to handle the user signin scenario. 

https://github.com/richdizz/BotAuth

Try deploying the AuthBot sample and connect it to Cortana channel, then build out your bot based on that working example.

**Comment by rjgmail88** [comment]
Hi nwhitmont, 

Thanks for the example but I was aware of auth bot sample. Original tile of this issue was 'How to run default code in Bot service for Cortana' and what I meant by that is I wanted to know right place to put code which will save the access token. I have 2 apps, one for sign in with AADV1 and one v2.0 to access the graph. In 2nd app I will get access token manually , save and use it to call graph api's. 

I was trying to find correct place to put my code.

**Comment by nwhitmont** [comment]
Hi @rjgmail88 - Sorry about that, I must have misunderstood your question. 

One way to handle this would be to wrap your get auth token code in a function and then call it from one or all of your dialogs. 

Example:
```js
function getAuthTokenData(session) {
  var authorizationToken = session.message.entities.find((e) => {
    return e.type === 'AuthorizationToken';
  });
  var decodedtoken = jwtDecode(authorizationToken.token);

  return {
    name: decodedtoken.name,
    email: decodedtoken.upn
  }
}

// in your dialog of choice:
bot.dialog('schedule', (session) => {
  // get auth data
  var authData = getAuthTokenData(session);
  // do stuff with authData
});
```

**Comment by rjgmail88** [comment]
Yeah, thanks. I got it working.

**Comment by nwhitmont** [comment]
thanks for the update. Glad to hear you got it working! 👍
