### ISSUE TITLE
[Bot Deployment] Why is session.send not working on deployed bot in Azure? But works on emulator.

### ISSUE THREAD

**Issue by yogeshchandra01** [Microsoft/BotBuilder#3851]
Hi,

I am new to Azure deployment. Had tried to run thru pro-active message app. It works at emulator. **session.send** api is not working on deployed bot. I am not getting response back. Though it shows on console log there. Is there anything i am missing to done during deployment or in application ? Please help. 
node JS and npm are on latest version at my machine i.e. 6.11.1 and 3.10.x . where as azure editor have 6.9.x and 3.9.x. Is this something to look at ?
I am simply trying to get response of it too but no success.

**bot.dialog('/', function (session, args) {
	session.send("ping me");
});**

**Comment by nwhitmont** [comment]
Hi @yogeshchandra01 - It's hard to diagnose the problem without the full bot code.  Can you post your complete bot code for reference?

**Comment by nwhitmont** [comment]
closing as no reply from user -- reopen if you're still having issues
