### ISSUE TITLE
[Teams] "mailto" openUrl Card Action doesn't work when including brackets or curly brackets

### ISSUE THREAD

**Issue by MBbrainsonic** [Microsoft/BotBuilder#3854]
## Bot Info 
* SDK Platform: Node.JS
* SDK Version: 3.12.0
* Active Channels: MS Teams, Skype

## Issue Description
I'm experiencing issue with Hero Card with Mailto action on MS Teams (button with openUrl).

MS Teams seems to not support mailto with subject or whatever you put after the destination email.
I've a card with a button in it which got an openUrl action "mailto:ff@ff.fr". This works fine but then I wanted to add a subject to the mailto as "mailto:ff@ff.fr?subject=Bot Email" and now the button is unresponsive. On other platform as Skype, it's working fine.

Is there a way to bypass this issue for MS Teams ?

## Reproduction Steps
1. Create a Hero Card with a button
2. Assign button action URL as : "mailto:ff@ff.fr?subject=hello" (no matter infos you put as email/subject)
3. Send the Card to the user and click on the button (on MS Teams)

## Expected Behavior
Open Email App with fields filled according to the mailto link

## Actual Results
Button is unresponsive when a subject "?subject=" or anything else (body,..) is added to the mailto.

Thanks !

**Comment by nwhitmont** [comment]
@MBbrainsonic Looks like you found a Teams-specific bug. Thanks for reporting!

I have forwarded the issue to the MS Teams team for investigation.

**Comment by xjose97x** [comment]
When sending a herocard through facebook with a "mailto" or "tel" url, facebook didnt't render it and complained about it (could see that through the botframework portal issues),
So as a workaround I'm using the goo.gl or tinyurl API to redirect to those urls.

Hope it helps as a workaround until there's a fix for MS Teams

**Comment by MBbrainsonic** [comment]
@xjose97x Yes I was using this method but it's really anoying because it's opening the web browser. But thx btw ;)

**Comment by billbliss** [comment]
I tried this myself on MS Teams and it worked fine. Can you send a specific code sample?

Here's what I tried:

`buttons.push(builder.CardAction.openUrl(session, "mailto:billbl@microsoft.com?subject=bot email", "Email Bill!"));`

What Teams client are you testing this on? E.g. Windows, Mac, iOS, Android?

**Comment by MBbrainsonic** [comment]
@nwhitmont @billbliss I find out what's the real issue on MS Teams. 

I've tried your example @billbliss  and it's working fine. So I've investigated what was the problem of my mailto. For my purpose, I'm putting "tags" inside subject as

 - "mailto:my@mail.com?subject=**[FIRST][SECOND]** Text".

At this point I've made many tests on subject and body and the final result is that **MS Teams doesn't support '[' or ']' characters** inside a mailto link. I've also tested **'{' and '}' characters and same result**. the button is unresponsive.

**Comment by Wajeed-msft** [comment]
@MBbrainsonic - This is happening because **[** and **]** are not encoded in URL. Please encode the URL as follows and it should work fine.

- "mailto:my@mail.com?subject=**%5BFIRST%5D%5BSECOND%5D**  Text"

**Comment by MBbrainsonic** [comment]
@Wajeed-msft Indeed it works fine ! Curiously Skype support brackets even if they're not encoded but MS Teams not. Thanks to all 👍
