### ISSUE TITLE
Issues with Bot Service on Azure

### ISSUE THREAD

**Issue by dZbear** [Microsoft/BotBuilder#3860]
## Bot Info 
* App ID: relaxmelodies
* SDK Platform: Node.js
* SDK Version: 6.11
* Active Channels: Cortana
* Deployment Environment: Azure Bot Service

## Issue Description
I was writing code for that last 2 days with no issues. Then at some point, hitting "Save" to save my latest code changes erased everything I had in index.js. After rewriting boiler-plate code, I started receiving errors in the console for lines with the following code : 

var restify = require('restify');
var builder = require('botbuilder');

As if restify and botbuilder could not be found.
I have then tried to completely delete my bot + bot service, start over fresh, and I was not able to deploy and got "Unknown errors"

## Expected Behavior
I'm expecting Azure Bot Service to work and not delete my code, and corrupt my account.

## Actual Results
See Attached screenshots

The code
![thecodeandtheerror](https://user-images.githubusercontent.com/3278542/33489782-e3d41e1e-d682-11e7-9ff5-b650f50a4a93.png)

Trying to load the bot
![tryingtoloadbot](https://user-images.githubusercontent.com/3278542/33489783-e3e4c2b4-d682-11e7-85a2-a69745856a81.png)

Trying to deploy the bot
![tryingtodeploy](https://user-images.githubusercontent.com/3278542/33489784-e3f45f3a-d682-11e7-86e4-6d4e96bd4602.png)

**Comment by JasonSowers** [comment]
@dZbear Than you for reporting this.  We will look into this for you.

**Comment by JasonSowers** [comment]
What region are you deployed to on Azure?

**Comment by dZbear** [comment]
Hi Jason, I’m deoyed to CanadaEast

**Comment by JasonSowers** [comment]
@dZbear can you please try again the issue should be addressed and fixed now.

**Comment by dZbear** [comment]
Yes it is working. Thank you for looking into this.

On Monday I will delete everything and start from scratch with the Bot
Service.

Thanks again.
