### ISSUE TITLE
[Feature Request] Expose Slack App Token in addition to Bot Token

### ISSUE THREAD

**Issue by lingz** [Microsoft/BotBuilder#3865]
Currently the API gives us the bot token for each inbound message from MBF. However, when you authenticate with the Slack API, you get both an **app token** and a **bot token**. We need the app token to figure out which user authenticated and to proactively greet them, but it seem MBF is swallowing the app token and only giving up the Bot token. This is related to Feature Request #2655.

**Comment by lingz** [comment]
Exposing the app token would also allow us to use more API calls.

**Comment by sgellock** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
