### ISSUE TITLE
[Direct Line] Chatbot only fully works on Bot Framework Emulator?

### ISSUE THREAD

**Issue by fms-santos** [Microsoft/BotBuilder#3866]
## Bot Info 
* App ID: ab346cac-058f-4627-ad1d-4c1a0e3fdfe1
* SDK Platform:  Node.js
* SDK Version:  3.12.0
* Active Channels:  Skype, Directline
* Deployment Environment:  Azure App Service

## Issue Description
As of today (Dec 4th, 2017), my Azure App deployed chatbot only appears to be working correctly on the Bot Framework Emulator. On every other channel that I have connected, the bot keeps sending the welcome card (default dialog "/") everytime I try to send it a new message.

## Code Example
Just send a type message to the bot and it goes back to the default "/" dialog.

## Reproduction Steps
1. Say something to the bot
2. Bot keeps going back to the "/" dialog on every channel besides Emulator

## Expected Behavior
The bot should proceed with the analysis and show the correct answer like in the emulator as in the picture below.
![Expected behavior](https://user-images.githubusercontent.com/16543301/33552164-d52332c2-d8eb-11e7-80be-93286a766da3.png)

## Actual Results
The results on the directline channel are shown below.
![Wrong Behavior](https://user-images.githubusercontent.com/16543301/33552232-2542f18e-d8ec-11e7-91b7-8fb1beab7d70.png)

**Comment by pascalrijk** [comment]
I have the exact same problem!

**Comment by fms-santos** [comment]
@pascalrijk  I have the same error on other bot as well. This one also works on Skype directly.

**Comment by pbonder** [comment]
I'm having the same problem here.

**Comment by JasonSowers** [comment]
@pascalrijk @pbonder can you please provide app IDs?

**Comment by pbonder** [comment]
App ID: 6cd7cd5b-47ad-40a8-a319-9dd7846977b7

**Comment by JasonSowers** [comment]
@fms-santos @pascalrijk @pbonder   Are your bots using the default state store or have you implemented a custom state store.
  
Additionally,  Are any of you able to capture the JSON your bots are receiving and responding to?  If so please post it in this thread.

**Comment by fms-santos** [comment]
@JasonSowers I'm using the default.
 My bot is working now. I can enter the dialogFlow and it's not stuck anymore.

**Comment by pbonder** [comment]
Using the default, my bot is still answering the first dialogFlow.

**Comment by JasonSowers** [comment]
When testing your bot in the portal @pbonder I am seeing the following dialog flow.  Is this the intended dialog flow or not?
  
![image](https://user-images.githubusercontent.com/6301037/33567224-5962579e-d8d7-11e7-9201-bc0158f5f6b9.png)

**Comment by pbonder** [comment]
the correct flow is this one. It seems that everytime I input something on the keyboard it goes back to the "/" dialog. On the emulator it does the right thing. Also last friday everything was working fine

![untitled](https://user-images.githubusercontent.com/21130822/33567418-041ad0c4-d91b-11e7-9364-68fcbbf1046b.png)

**Comment by JasonSowers** [comment]
it would help us tremendously if you could capture the JSON your bot is receiving and responding to.

**Comment by pbonder** [comment]
from the emulator?

**Comment by JasonSowers** [comment]
directline

**Comment by pbonder** [comment]
I'm using Skype Web Control. How can I capture JSON from directline?
Thanks

**Comment by JasonSowers** [comment]
Apologies, I thought you were using directline as well

**Comment by fms-santos** [comment]
@pbonder  I have another bot using Skype and some userData. I've changed to cosmosDB storage and now it's working again.

**Comment by JasonSowers** [comment]
closing this issue please refer to #3870 for more information
