### ISSUE TITLE
[Question] Why am I getting an invalid type exception when using PromptDialog.Choice forwarding to a custom SuggestedActionDialog??

### ISSUE THREAD

**Issue by youtoofan** [Microsoft/BotBuilder#3868]
* App ID: 5f35fe55-4e26-49d1-b3a0-46a6192f6dd1
* SDK Platform: .NET
* Active Channels: Skype, direct line, webchat
* Deployment Environment: Azure app service

## Issue Description
I'm getting an invalid type exception when using PromptDialog.Choice. 
I am forwarding to a custom SuggestedActionDialog from the QnaMakerDialog. The prompt is supposed to show two or more buttons, which the user must select. The first time the dialog is started, the exception mentioned above is thrown at this line: var selectedButton = await result;
**invalid type: expected TestBot.Model.Button, have Boolean** inside the ResumeAfterConfirmation method.

## Code Example
`[Serializable]
    public class SuggestedActionDialog : IDialog<string>
    {
        private readonly DynafleetSuggestedAction _dynafleetAction;

        public SuggestedActionDialog(DynafleetSuggestedAction dynafleetAction)
        {
            _dynafleetAction = dynafleetAction;
        }

        public Task StartAsync(IDialogContext context)
        {
            context.Wait(MessageReceivedAsync);
            return Task.CompletedTask;
        }

        private async Task MessageReceivedAsync(IDialogContext context, IAwaitable<IMessageActivity> result)
        {
            var activity = await result;
            var nextAction = _dynafleetAction;
            var options = nextAction.Buttons;
            var descriptions = nextAction.Buttons.Select(s => s.Caption);

            PromptDialog.Choice<Button>(context, ResumeAfterConfirmation, options, nextAction.Title, descriptions: descriptions);
        }

        private async Task ResumeAfterConfirmation(IDialogContext context, IAwaitable<Button> result)
        {
            try
            {
                var selectedButton = await result;
                if (selectedButton.SuggestedAction != null)
                {
                    var nextAction = selectedButton.SuggestedAction;
                    var options = nextAction.Buttons.ToList();
                    var descriptions = nextAction.Buttons.Select(s => s.Caption).ToList();

                    PromptDialog.Choice<Button>(context, ResumeAfterConfirmation, options, nextAction.Title, descriptions: descriptions);
                }
                else
                {
                    await context.PostAsync(selectedButton.Value);
                    context.Done(string.Empty);
                }
            }
            catch (Exception e)
            {
                Trace.TraceError(e.ToString());
            }
        }
    }`

Funny thing is: I catch the error in the catch block, the user sees the PromptDialog a second time but can select a button and the dialog continues as expected.

![afbeelding](https://user-images.githubusercontent.com/1804461/33567826-c7a4472e-d924-11e7-821b-bbe9f4327310.png)

**Comment by youtoofan** [comment]
I've tried now with a simpler example:

`private async Task MessageReceivedAsync(IDialogContext context, IAwaitable<IMessageActivity> result)
        {
            var activity = await result;
            PromptDialog.Confirm(context, Confirmed, "Have question");
        }

        public async Task Confirmed(IDialogContext context, IAwaitable<bool> argument)
        {
            bool isCorrect = await argument;
            if (isCorrect)
            { }
            else
            { }
        }`

The bot shows the prompt with 2 buttons, but without selecting an option, the if(isCorrect) statement is handled. When I select the yes button, I get the same prompt once again.

**Comment by JasonSowers** [comment]
I just tested your code example in a dialog (below) in the emulator and got the following results, did I miss something?  It seems I am unable to reproduce.
```cs
        public Task StartAsync(IDialogContext context)
        {
            context.Wait(MessageReceivedAsync);

            return Task.CompletedTask;
        }
        private async Task MessageReceivedAsync(IDialogContext context, IAwaitable<object> result)
        {
            //var activity = await result as Activity;
            var activity = await result;
            PromptDialog.Confirm(context, Confirmed, "Have question");
        }
        public async Task Confirmed(IDialogContext context, IAwaitable<bool> argument)
        {
            bool isCorrect = await argument;
            if (isCorrect)
            { }
            else
            { }
        }
```
![image](https://user-images.githubusercontent.com/6301037/33634285-8947e54a-d9c8-11e7-96b3-7c2dd3cd1be2.png)

**Comment by youtoofan** [comment]
I think the issue starts somewhere in the beginning of my bot code. Take a look at my root dialog:

`public Task StartAsync(IDialogContext context)
        {
            context.Wait(MessageReceivedAsync);
            return Task.CompletedTask;
        }

        private async Task MessageReceivedAsync(IDialogContext context, IAwaitable<object> result)
        {
            if (!await IsRegistered(context))
            {
                Trace.TraceInformation("Calling login dialog first.");
                var loginDialog = new FormDialog<LoginForm>(new LoginForm(), LoginForm.BuildForm, FormOptions.PromptFieldsWithValues);
                await context.Forward(loginDialog, ResumeAfterRegistration, context.Activity, CancellationToken.None);
            }
            else
            {
                Trace.TraceInformation("Calling QnA dialog.");
                await context.Forward(new QnaDialog(), ResumeAfterQna, context.Activity, CancellationToken.None);
            }
        }

        private async Task ResumeAfterRegistration(IDialogContext context, IAwaitable<LoginForm> result)
        {
            var loginData = await result;
            Trace.TraceInformation("Resuming after registration: " + loginData);
            context.Wait(this.MessageReceivedAsync);
        }

        private Task ResumeAfterQna(IDialogContext context, IAwaitable<IMessageActivity> result)
        {
            //var temp = await result;
            Trace.TraceInformation("Resuming after QnA");
            context.Wait(this.MessageReceivedAsync);

            return Task.CompletedTask;
        }`

Notice the **var temp = await result** in comment in the ResumeAfterQna method. If I uncomment this, I get the same Invalid Type exception, expecting an IMessageActivity, but receiving a bool.
Since I don't need the result of the QnA dialog here, I just commented it out. But then I got more or less the same issue in the SuggestedAction Dialog, mentioned in my first post. Expecting a button, instead receiving a bool.

This is the flow:

RootDialog -> Forward to LoginDialog or QnaDialog -> In QnaDialog, either post message or forward to SuggestedAction dialog.

This is the content from the RespondFromQnAMakerResultAsync inside the QnaDialog:

`
var answer = result.Answers.First().Answer;
                var qnaAnswerData = answer.Split(new[] { ";" }, StringSplitOptions.RemoveEmptyEntries);
                var reply = ((Activity)context.Activity).CreateReply();

                foreach (var data in qnaAnswerData)
                {
                    if (data.ContainsVideoLink())
                    {
                        reply.Attachments.Add(new VideoCard()
                        {
                            Media = new List<MediaUrl>() { new MediaUrl(data.Replace(ApplicationConstants.AttachmentPrefix.VIDEO, string.Empty)) },
                            Autoloop = false,
                            Autostart = true,
                            Aspect = "16:9",
                            Image = new ThumbnailUrl("http://www.dynafleethelp.volvotrucks.com/content/dam/volvo/volvo-trucks/masters/dynafleet-help/tutorials/1860x1050-tutorials-basic-administration.jpg/_jcr_content/renditions/1860x1050-tutorials-basic-administration-teaser2.jpg")
                        }
                        .ToAttachment());
                        await context.PostAsync(reply);
                    }
                    else if (data.ContainsImage())
                    {
                        reply.Attachments.Add(new HeroCard()
                        {
                            Images = new List<CardImage>() { new CardImage(data.Replace(ApplicationConstants.AttachmentPrefix.IMAGE, string.Empty)) },
                            Text = "SCREENSHOT"
                        }
                        .ToAttachment());
                        await context.PostAsync(reply);
                    }
                    else if (data.ContainsSuggestedActions())
                    {
                        Trace.TraceInformation("Calling Suggested Action dialog.");
                        var dynafleetAction = JsonConvert.DeserializeObject<DynafleetSuggestedAction>(data.Replace(ApplicationConstants.AttachmentPrefix.SUGGESTEDACTIONS, string.Empty));
                        await context.Forward(new SuggestedActionDialog(dynafleetAction), ResumeAfterSuggestedAction, message, CancellationToken.None);
                    }
                    else
                    {
                        reply.Text = data;
                        await context.PostAsync(reply);
                    }
                }
`

**Comment by youtoofan** [comment]
**Situation update.**

When I switch from the Microsoft.Bot.Builder.CognitiveServices.QnAMaker.QnAMakerDialog to the QnAMakerDialog from Gary Pretty ( [https://www.nuget.org/packages/QnAMakerDialog/](url) ), the issue is resolved. 

Implementation is the same.

So I guess the Microsoft QnAMakerDialog is messing things up?

**Comment by JasonSowers** [comment]
It's possible, but we are not seeing any other reports of this.  In this case you may way to report the issue in the [Conative Services repo](https://github.com/Microsoft/BotBuilder-CognitiveServices)

**Comment by JasonSowers** [comment]
@FranciscoPonceGomez Do you have any insight on this? I know you have been looking into QnAMaker.

**Comment by youtoofan** [comment]
@JasonSowers i think you are right: [https://github.com/Microsoft/BotBuilder-CognitiveServices/issues/39](url)
