### ISSUE TITLE
[Skype] Bot review process too slow with no contact, no feedback?

### ISSUE THREAD

**Issue by bgastaldi** [Microsoft/BotBuilder#3869]
## Bot Info 
* App ID:  e1872933-e622-4263-a273-624aa6c1e749
* Active Channels: Skype
* Deployment Environment: DialogFlow (API.AI)

## Issue Description
I submitted my bot a two month ago an it's still "In Review."
APP ID: e1872933-e622-4263-a273-624aa6c1e749

It's now been approved on Facebook but not on Skype.

Currently only Portuguese language support.
Can someone help?

**Comment by JasonSowers** [comment]
Thanks for reporting. I have reached out to the Skype team asking them to investigate I will report back when we hear from them.

**Comment by bgastaldi** [comment]
Ok. I'm waiting your support.

Tks.

**Comment by nwhitmont** [comment]
@bgastaldi - The Skype review team was unable to certify your bot. You should have received an email containing info on how to fix/update and resubmit your bot for Skype publishing. Please respond to the email with further questions.

**Comment by bgastaldi** [comment]
Hi!,
I fixed the failing certification requirements and resubmited in 20 minutes ago.
Tks

**Comment by JonesAbramoff** [comment]
Hi, my bot is also in review for a long time and I didn´t receive any e-mail or feedback.
I am trying to set Brazil as the publisher country and select Brazilian Portuguese as then language but after saving it changes back to United States and looses the Portuguese selection.
The message end point is https://botzapprices4.azurewebsites.net/api/messages .

**Comment by JonesAbramoff** [comment]
My bot was approved and published but last week I recreated it with the same AppId trying to solve the problem described in issue 4322 but a Skype channel registration bug described in issue https://github.com/Microsoft/skype-dev-bots/issues/15 blocked its use.<br>
I have recreated it again with a new AppId and bot handle and send e-mails to bothelp but no reply yet.<br>
The new AppId is https://join.skype.com/bot/ac573e18-18eb-48e7-856a-51ddeb3b6185 .
