### ISSUE TITLE
[Skype Image Service] Skype UWP image upload generates HTTP 500 error?

### ISSUE THREAD

**Issue by sebastinovich** [Microsoft/BotBuilder#3872]
## Bot Info 
* App ID: e3cd349c-800e-4dc1-b873-57a2703065b2
* SDK Platform: .NET
* SDK Version: 3.12.2.4
* Active Channels: Skype
* Deployment Environment: Azure Bot Service

## Issue Description
I can use my bot to upload an image which is analyzed by a Custom Vision service. I can successfully upload images from Skype for Windows (Desktop application), but it fails when I use the Skype "universal" app (UWP application).
After doing a bit of fiddler, I can see that the URLs generated by the Skype desktop app is slightly different from the ones generate by the Skype UWP app:
UWP: https://smba.trafficmanager.net/apis/v3/attachments/0-neu-d4-5e9aa714f51e6f971f7e26ba999def9a/views/original
Desktop: https://smba.trafficmanager.net/apis/v3/attachments/0-neu-d1-d182f96554870899cddce67637142b93/views/original
Notice the "0-neu-d4" versus "0-neu-d1" portion of the URL. I suspect that they target different servers and that the server "d4" is having some issues.

When my bot queries the URL generated by the Skype UWP app (with the Authorization token of course) it returns an HTTP 500 error, whereas the URL generated by the Skype Desktop app works successfully.

In order to try it, just put the code extract below in a Dialog class and take a look at the responseMessage variable.

## Code Example
```cs
public virtual async Task MessageReceivedAsync(IDialogContext context, IAwaitable<IMessageActivity> argument)
        {
            var message = await argument;

            if (message.Attachments != null && message.Attachments.Any())
            {
                var attachment = message.Attachments.First();
                using (HttpClient httpClient = new HttpClient())
                {
                    await context.PostAsync(message.ChannelId);

                    // Skype & MS Teams attachment URLs are secured by a JwtToken, so we need to pass the token from our bot.
                    if (message.ChannelId.Equals("skype", StringComparison.InvariantCultureIgnoreCase) || message.ChannelId.Equals("msteams", StringComparison.InvariantCultureIgnoreCase))
                    {
                        var token = await new MicrosoftAppCredentials().GetTokenAsync();    
                        httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
                    }

                    var responseMessage = await httpClient.GetAsync(attachment.ContentUrl);
```

## Expected Behavior
I would like to see it work on Skype UWP app :-) (The same code was working pretty fine a few weeks ago).

**Comment by nwhitmont** [comment]
@sebastinovich Thanks for reporting.  We have some known bugs with the Skype image upload/download service that are actively being addressed by the Skype team.  We have to have a fix out soon.

**Comment by sebastinovich** [comment]
Cool! Do you think it can be fixed in the coming hours? I have an important demo to make tomorrow...

**Comment by Mimetis** [comment]
Any update on this issue ?
I have the same problem, using the NodeJS SDK.
