### ISSUE TITLE
[Question] "There was an error sending this message to your bot: HTTP status code GatewayTimeout" (even when no deployment and it worked perfectly fine couple of hours before)

### ISSUE THREAD

**Issue by punithk** [Microsoft/BotBuilder#3877]
## Bot Info 
* App ID: a5775c3f-2d3c-4c13-a1e9-c18d7237528c
* SDK Platform: Node.js 
* SDK Version: 3.13.0
* Active Channels:  Skype, MS Teams, Slack, Direct Line, Skype for Business, Facebook, Twilio, Telegram
* Deployment Environment: Other, IBM Bluemix
## Issue Description
I am getting this error: "There was an error sending this message to your bot: HTTP status code GatewayTimeout". 
I have been using this for a long time and had this issue occasionally(like once in 3 months and for only specific channels) but used to get resolved by itself.
I had last deployed on Friday and tested it working on almost all channels till Tuesday morning. But since noon there has been an issue with connector service i guess due to which it is given this error message. Absolutely no change in the deployed code but this issue persists for a very long time than usual. Also some channels work properly even with this issue like facebook is working properly even with this issue. But on SFB and Skype its not moving any further and i keep getting this annoying message:

![image](https://user-images.githubusercontent.com/14126035/33626787-a03137b2-da21-11e7-8246-43c5ec309eaf.png)

Also server side certificates are perfect. Some people were telling to remove the bot and put it back but this will make me redo the entire linking of channels especially the SFB.

Please help out if anything is wrongly done but to my knowledge and how it has been working till date i dont see any issue from my code.

## Code Example
On log i observed this error but not sure how it helps

Error: POST to 'https://webpoolsg20r04.infra.lync.com/platformservice/tgt-c98ad92f33ed54008a30cbb5bd5314f9/botframework/v3/conversations/YWRhODE4MzUjc2lwOmRyeWljZWx1Y3lAaGNsLmNvbQ%3D%3D/activities/68bb32ca-b675-4418-8e3d-7fd69a342658' failed: [404] Not Found

## Reproduction Steps
Not Sure how to reproduce this. It did not happen due to any code change for sure as that worked fine when deployed.
## Expected Behavior
This should not happen where retry is coming even though its responding:
![image](https://user-images.githubusercontent.com/14126035/33627078-68c7eafe-da22-11e7-90d3-9dfb5c46476e.png)

## Actual Results
this is what is happening:
![image](https://user-images.githubusercontent.com/14126035/33627125-91e2d94e-da22-11e7-9c41-d49a05f907d5.png)

**Comment by JasonSowers** [comment]
@punithk Thanks for reporting.  Can you please try to debug locally using [these steps](https://blog.botframework.com/2017/10/19/debug-channel-locally-using-ngrok/) to see if you can get more information.  The gateway timeout is too generic to go off of with the information given.

**Comment by nwhitmont** [comment]
@punithk - When I tested your bot in the bot portal just now (from West-US region), your bot sometimes worked fine, and other times it just times out.

What geographic region is your bot deployed in? It's possible this is affecting your bot's response time. Is your deployment "serverless", this could also be affecting response times. Hard to say without seeing the bot code.

**Comment by punithk** [comment]
Thanks for responding @JasonSowers and @nwhitmont.

@JasonSowers locally I debugged using emulator found no issues whatsoever. I will try out with Ngrok now and let you know. But it's very confusing as there is absolutely no error logged.

@nwhitmont code is deployed on US South(IBM not Azure, I am not sure whether this started to matter), but this still worked seamless with not much of delay, it is not serverless and I am even using redis for storing bot state. Will share info on code but genuinely I don't think there is an issue with code as it worked perfectly after last deployment. It's baffling that even logs have no issues in them. And yes most of the channels are running fine but on bot framework dashboard I see issues piling up and SFB not responding as others.

**Comment by rajaramcomputers** [comment]
Why this issue is closed

**Comment by sganeshkumar** [comment]
I'm also faced the same issue. After downgrade the botbuilder npm package to ("botbuilder": "3.12.0"). Its working fine. 
"botbuilder": "^3.12.0", changed to "botbuilder": "3.12.0",

**Comment by upsson** [comment]
@sganeshkumar Theres is not a 3.12.0 version i only see a 3.12.2.4 is that correct??

**Comment by Kadae** [comment]
Year 2021. Problem still exists, but issue is Closed. Funny as hell.
