### ISSUE TITLE
[.Net SDK, Localization] The Locale field is missing in messages from Telegram, Skype, MS Teams and so on. Localization doesn't work at all.

### ISSUE THREAD

**Issue by denisyfrolov** [Microsoft/BotBuilder#3878]
## Bot Info 
* SDK Platform: .NET
* SDK Version: Microsoft.Bot.Builder.Azure 3.2.3
* Active Channels: Telegram, Skype, MS Teams, Emulator
* Deployment Environment: Auzure Bot Service

## Issue Description
The activity which is coming from Telegram, Skype or MS Teams doesn't have the Locale field anymore. So that the bot can't localizes any messages for user.

## Code Example
Telegram:
```
{
    "type": "message",
    "id": "**",
    "timestamp": "2017-12-05T18:43:24.6431233Z",
    "serviceUrl": "https://telegram.botframework.com",
    "channelId": "telegram",
    "from": {
        "id": "**",
        "name": "**"
    },
    "conversation": {
        "isGroup": false,
        "id": "**"
    },
    "recipient": {
        "id": "**",
        "name": "**"
    },
    "text": "Text",
    "channelData": {
        "update_id": 418672082,
        "callback_query": {
            "id": "**",
            "from": {
                "id": 134567,
                "is_bot": false,
                "first_name": "**",
                "last_name": "**",
                "username": "**",
                "language_code": "en"
            },
            "message": {
                "message_id": 307,
                "from": {
                    "id": 134567,
                    "is_bot": true,
                    "first_name": "**",
                    "username": "**"
                },
                "chat": {
                    "id": 7654321,
                    "first_name": "**",
                    "last_name": "**",
                    "username": "**",
                    "type": "private"
                },
                "date": 1512498143,
                "text": "Text"
            },
            "chat_instance": "2552744620053388356",
            "data": "Text"
        }
    }
}
```

MS Teams:
```
{
    "text": "Text",
    "textFormat": "plain",
    "type": "message",
    "timestamp": "2017-12-05T18:45:35.351Z",
    "localTimestamp": "2017-12-05T21:45:35.351+03:00",
    "id": "**",
    "channelId": "msteams",
    "serviceUrl": "https://smba.trafficmanager.net/emea-client-ss.msg/",
    "from": {
        "id": "**",
        "name": "**",
        "aadObjectId": "35820c14-8b1a-4ffe-9cfc-a8e8b0858418"
    },
    "conversation": {
        "id": "**"
    },
    "recipient": {
        "id": "**",
        "name": "**"
    },
    "entities": [
        {
            "locale": "ru-RU",
            "country": "RU",
            "platform": "Web",
            "type": "clientInfo"
        }
    ],
    "channelData": {
        "tenant": {
            "id": "**"
        }
    }
}
```

Bot Emulator:
```
{
    "type": "message",
    "text": "Text",
    "from": {
        "id": "default-user",
        "name": "User"
    },
    "locale": "ru-RU",
    "textFormat": "plain",
    "timestamp": "2017-12-05T18:47:38.087Z",
    "channelData": {
        "clientActivityId": "1512499640001.9503766533278897.0"
    },
    "entities": [
        {
            "type": "ClientCapabilities",
            "requiresBotState": true,
            "supportsTts": true,
            "supportsListening": true
        }
    ],
    "id": "m4g22ck45616"
}
```

## Expected Behavior
The channels must have the Locale field exactly as Emulator.

**Comment by nwhitmont** [comment]
@denisyfrolov Thanks for reporting, I have forwarded this to our SDK team for investigation.

**Comment by billbliss** [comment]
For some reason, I don't remember why, ```.locale` has never been set. 

If you look on the MS Teams message, it's in the entities[] array:

```
    [...]
    "entities": [
        {
            "locale": "ru-RU",
            "country": "RU",
            "platform": "Web",
            "type": "clientInfo"
        }
    ],
   [...]
```
If the other channels start setting .locale, MS Teams will switch.

**Comment by nwhitmont** [comment]
Thanks for the info @billbliss 👍

**Comment by denisyfrolov** [comment]
@billbliss I know. Telegram provides something like that too:
'''
[...]
"from": {
    "id": 134567,
    "is_bot": false,
    "first_name": "**",
    "last_name": "**",
    "username": "**",
    **"language_code": "en"**
}
[...]
'''
But the problem is the bot doesn't catch it as localization info. So that localization just doesn't work. But localization works perfectly in emulator which provides the field.

**Comment by denisyfrolov** [comment]
@billbliss @nwhitmont is there a way to set bot's locale without this field? I tried 
```
CultureInfo.CurrentCulture = new CultureInfo("ru-RU");
```
and 
```
Thread.CurrentThread.CurrentCulture = new CultureInfo("ru-RU");
```
But it gave no result. Probably it is because of await/async constructions, but I have no idea how to manage that.

**Comment by nwhitmont** [comment]
To summarize the current situation:
- not all channels provide locale (language code) information in `Activity.locale` 
- some channels have it, but it's not necessarily stored in `Activity.locale`  (Teams, Telegram)

**Comment by denisyfrolov** [comment]
@nwhitmont you forgot Skype. Teams, Telegram and Skype do NOT provide locale. But what channels do? I know the only one. It is the Emulator, but I don't think we can count it.

Also, I want you to understand, the main problem is NOT about having the field or not. The main problem is built-in localization doesn't work at all because of the field is incorrect.

**Comment by denisyfrolov** [comment]
Up

**Comment by sgellock** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
