### ISSUE TITLE
[Skype] How to Delete chat history in Skype App?

### ISSUE THREAD

**Issue by sajal2692** [Microsoft/BotBuilder#3880]
## Bot Info 
* SDK Platform: Node.js
* Active Channels: Skype
* Deployment Environment: Azure App Service
* Skype Version: 8.10.0.4 (Mac OS) 

## Issue Description
Can't find an option to delete the chat history with a bot, on Skype. As we demo the bot to prospective clients, we'd like to clear the history, and start again from a clean slate. Is this possible? To be clear, by chat history, I mean the displayed conversation. You can delete conversations with humans.

I found an option to delete the conversation on web.skype.com, but it doesn't seem to clear the conversation on the Skype app. Also, previous versions of Skype (example:  v 7.59) allows us to delete the conversation with a bot.

**Comment by nwhitmont** [comment]
Try the instructions described in this article:

https://blogs.microsoft.com/firehose/2014/01/17/how-to-clean-up-your-skype-messages-chat-history-and-skype-home/

**Comment by nwhitmont** [comment]
@sajal2692 Were you able to resolve your issue using the suggested methods?

Let me know if you have additional questions.

**Comment by sajal2692** [comment]
Hi @nwhitmont , sorry for the late reply. I tried out the methods you listed, here are the results:

> https://blogs.microsoft.com/firehose/2014/01/17/how-to-clean-up-your-skype-messages-chat-history-and-skype-home/

Couldn't find these options for the latest Skype version for MacOs and Ubuntu 16.04

> You could also try removing the bot from your contacts and re-adding it via the Skype "join" link.

Tried this, doesn't work. It recovers the chat history upon re-adding the bot.
 
> According to this thread - users also have used the web.skype.com method you mentioned.

This has mixed results for me. I could delete the conversation on web.skype.com. On an initial look, it looked like it had no effect on the chat history on the Mac, Ubuntu or iOS versions of skype.

Though, after a few hours, it seems to have deleted the history on the native app versions. So.. it kind-of works? 

Is it possible to have a more streamlined way to do this? :)

**Comment by nwhitmont** [comment]
Yes, deleting bot conversation completely (removing all conversation) is not yet supported on new Skype clients. It is in our backlog.
 
So if this is for demo purpose, I will propose to create a different Skypeid for now. This will allow you to start from a fresh slate.
