### ISSUE TITLE
[Skype Web Control] Does it have video & audio capabilities?

### ISSUE THREAD

**Issue by camilanunes** [Microsoft/BotBuilder#3882]
I am using <script type="text/javascript" src="https://swc.cdn.skype.com/sdk/v1/sdk.min.js"></script>  
but we I run on the web browser, it does not video and audio features.

Is there anything missing?

**Comment by nwhitmont** [comment]
@camilanunes The Skype Web Control does not have the same features as Skype desktop or mobile clients.  If you need audio and video support, use Skype desktop or mobile.

**Comment by camilanunes** [comment]
Yes, there is. Please find the example here. it was exactly where I tried to follow. The chat works well, but I could not see video and camera. At least according to the instructions, I should see.

Have you already used it?

Thanks,

**Comment by nwhitmont** [comment]
@camilanunes can you provide a link to the example you are talking about?

**Comment by camilanunes** [comment]
Yes, sure. It is at:

https://dev.skype.com/webcontrol

<span class="skype-button bubble " data-contact-id=""></span>
<script src="https://swc.cdn.skype.com/sdk/v1/sdk.min.js"></script>

**Comment by nwhitmont** [comment]
Per: https://support.skype.com/en/faq/FA34704/what-is-skype-web-control

**What is Skype Web Control?**
> Skype Web Control is a fast way for website visitors to communicate directly with a company representative in real-time right on the businesses website. It appears as a chat box on their website and is extremely fast and simple. The website owner decides who is on the other end of the chat - it could be the owner themselves, someone else from their business, or even a bot that provides intelligent responses to questions. 

**What can I send through Skype Web Control?**
> You can send messages, pictures, and files. We're keeping things simple so you can't send emoticons yet. 

>To send attachments, select the attachment icon and then choose a file to send.

**Can I make calls on Skype Web Control?**
> Calls are not yet supported.

**Comment by nwhitmont** [comment]
It appears what we have some conflicting documentation on this product.

**Comment by camilanunes** [comment]
Yes, it is strange as they described in a way that it is supported all of the features.
thanks a lot.

**Comment by nwhitmont** [comment]
@camilanunes - I followed up with the Skype Web Control team, and unfortunately they said the audio/video feature of the SWC only works with human user accounts, and is not yet compatible with bots.

**Comment by camilanunes** [comment]
Yes. But even with human user accounts, the features are not available. I used the source code available on the website. Do you know what can be happening?

Thanks
Camila

**Comment by grishutkin** [comment]
Having same problem on Mac in Safari. Used code from dev.skype.com, installed plugin but no video icon

**Comment by mdmetcalf** [comment]
This topic was closed prematurely; the person who closed it specifically assumed that the requestor was asking about chatting with a bot, which is not the case.  I'm experiencing the same issue.  If I provide a user's Skype ID, it opens the chat client to text chat with that person via the web control, but there is no way to do audio or video conversations, in spite of the headline of the Skype Web Control page (linked in the above post) saying "Video Call and Chat on your website with 2 lines of code".

Absolutely nowhere does the Skype team provide information about _how_ to do that in Skype web control.  Their [blog post introducing it](https://devblog.skype.com/blogs/2017/09/18/skype-web-control-2/) even says that one of their next posts will explain how... and that was more than 4 months ago, with no follow up to explain it.

I would very much like somebody from the Skype team to provide the information that is missing from the Skype Web Control page, or provide some more detailed info on how the Web Control works.

**Comment by JasonSowers** [comment]
Unfortunately, we are not the skype team, we are the bot framework team.  We have no control over what the skype team does.  You would need to reach out to the skype team.

**Comment by joychatterjee** [comment]
i also have the same problem with the video and audio call feature and i also have the problem with the chat feature also it is also not working for me
