### ISSUE TITLE
[Question] Bot jumps back to start of dialog when deployed to Slack?

### ISSUE THREAD

**Issue by jetk** [Microsoft/BotBuilder#3883]
## Bot Info
* App ID: a04c710f-ab2a-4d5d-9605-af607b65f80d
* SDK Platform:  Node.js
* SDK Version: 3.8.2
* Active Channels: Slack
* Deployment Environment: pm2 on a DigitalOcean Droplet

## Issue Description
On Slack, my bot seems to go into a dialog, and then get stuck there; instead of behaving based on the function fed into new builder.UniversalBot(..) it jumps back to the start of a dialog that should have ended after the user responds to an email prompt.

## Code Example
```javascript
// Bot controller, governs default dialogues that are launched
var bot = new builder.UniversalBot(connector, function(session) {


    //won't be empty if attempted to log in
    var retrieved_user_email = session.userData[user_email_key]
    console.log("main loop, it thinks the user data is" + retrieved_user_email)

    if (!retrieved_user_email) {
        return session.beginDialog('directMessageAuth')
    }

    var firsttime_api_creds = auth_memory[retrieved_user_email]

    if (firsttime_api_creds) {
        session.userData[retrieved_user_email] = firsttime_api_creds
        var explicit = session.userData[explicit_mode_key];
        if (explicit != true) {
           //should be going down this route
            sessi  on.beginDialog('conduct');
        }
    } else {
        console.log("error error")
        return session.beginDialog('directMessageAuth')
    }

});

bot.dialog('directMessageAuth', function(session, args) {

    var address = session.message.address;
    var newConversationAddress = Object.assign({}, address);
    delete newConversationAddress.conversation;
    bot.beginDialog(newConversationAddress, "survey");

});

bot.dialog('survey', [
    function(session) {
        builder.Prompts.text(session, 'Hello... What\'s your email?');
    },
    function(session, results) {
        var clean_response = clean_email(results.response)
        var email = addrs.parseOneAddress(clean_response)
        if (email.address) {
            session.userData[user_email_key] = clean_response;
            console.log("email should be saved as " + session.userData[user_email_key])
            passwordless(email.address, results.address)
            return session.endDialog('Ok, sending you a magic link at %s', clean_response);
        } else {
            return builder.Prompts.text(session, "Sorry that doesn't look like an email to my robot brains, can you try again?");
        }
    },
    function(session) { session.endDialog() }
]);



```

## Expected Behavior
I currently have a flow that:
- When User posts in a channel that Bot is part of
- Checks if User has told Bot their email (for the Bot to then trigger my service's magic link endpoint, sending them an email with a login link)
- If an email doesn't exist in session.userData, and furthermore Bot has no cached API credentials for that User (which would have been sent to Bot by my service once User clicks the login link), direct message User asking them for their email
- Once the email has been entered, Bot should behave normally (interacting with my service on behalf of User)

## Actual Results
This behaves as expected in the Emulator. However, when deployed as a service on my DO droplet, it behaves strangely:
- Login prompt as usual
- Magic link sent as usual
- When the User chats, gets an unsolicited DM asking for an email even though one has already been entered

**Comment by JasonSowers** [comment]
Please try upgrading to the newest SDK verson and see if that helps.

**Comment by nwhitmont** [comment]
Hi @jetk - Looking over your bot code I notice a few bugs.  

First, you don't need to "return" when you call functions like `session.endDialog()` or when using prompts. 

For example, the "survey" dialog should look like this (eg. remove the return statements)
```js
bot.dialog('survey', [
    function(session) {
        builder.Prompts.text(session, 'Hello... What\'s your email?');
    },
    function(session, results) {
        var clean_response = clean_email(results.response)
        var email = addrs.parseOneAddress(clean_response)
        if (email.address) {
            session.userData[user_email_key] = clean_response;
            console.log("email should be saved as " + session.userData[user_email_key])
            passwordless(email.address, results.address)
            session.endDialog('Ok, sending you a magic link at %s', clean_response);
        } else {
            // this line doesn't need to be a prompt - use regular session.send()
            session.send("Sorry that doesn't look like an email to my robot brains, can you try again?");
           // then restart this dialog
           session.beginDialog('survey');
        }
    }
   // the waterfall dialog will never get to this step, so you can remove it...
    /* function(session) { session.endDialog() } */
]);

```

**Comment by nwhitmont** [comment]
@jetk - Were you able to get it working using the code example?

**Comment by JasonSowers** [comment]
closing as no response from user
