### ISSUE TITLE
[Question] ChatConnector: receive - no security token sent.

### ISSUE THREAD

**Issue by Aethix** [Microsoft/BotBuilder#3886]
I'm trying to make a simple chatbot running on a local Node.js instance and accessed with a simple client. However, when I send my request I get a 401 Response and the error `ChatConnector: receive - no security token sent` is displayed in the console. How do I turn off the requirement for security tokens?

**Comment by stevengum97** [comment]
Can you provide more information? What do you mean by "a simple client"? What does your instantiated `ChatConnector` look like?

**Comment by sherifsarhan** [comment]
@Aethix In your emulator, before connecting, make sure you have these settings filled in.
<img width="794" alt="chatemulator" src="https://user-images.githubusercontent.com/6098862/33721524-4749a412-db35-11e7-8ddb-92b4663781aa.PNG">

**Comment by nwhitmont** [comment]
Hi @Aethix - It is totally normal to see this message when testing your bot with the Emulator during local development. It is just a reminder and there is no "off" setting. 

When your bot is running locally on your machine, you don't need to have the AppId and Password configured in the Emulator to test. Once your bot is deployed to Azure or other cloud, and you want to use the Emulator to test the deployed bot, then you need to use the AppId and Password in the Emulator as described by @sherifsarhan in the comment above.

**Comment by JasonSowers** [comment]
closing as no response from user

**Comment by cext001** [comment]
I am also getting the same issue

**Comment by rkbala** [comment]
Guys, just make the appID and appPassword as null if you don't want to use the same as part of testing from emulator. (Emulator local testing does not need appid and apppassword)

//use this for testing in local and if you don't have appid and app password

var appId = null;
var appPassword = null;

This will resolve this error. Thanks.

**Comment by sagarmodhavaniya** [comment]
i am got the same error when i want to send messages from twilio but i can't get the session 
```

    bot.use({
        receive: function (event, next) {
            console.log("hello")
        },
        send: function (event, next) {
        console.log("hello ")
        }

        })
```
any function are not call
but i received webhook event from the twilio

**Comment by cleemullins** [comment]
@sagarmodhavaniya  The best way to gen resolution for this is to post it to StackOverflow and tag your post with "#botframework". Our support team goes through those every day and drives them to resolution.

**Comment by sagarmodhavaniya** [comment]
okay 
i want to make the bot for whatsapp
