### ISSUE TITLE
[Bot Portal] Issues with Bot Regisration portal?

### ISSUE THREAD

**Issue by jrmcdona** [Microsoft/BotBuilder#3887]
## Bot Info 
* App ID: 0bfc5429-ac88-4a25-b413-538d11d0ce10
* Active Channels:  Skype
* Deployment Environment: localhost/bot emulator

## Issue Description
When I log into the registration portal it seems my bot hygiene is not good.  I see this right away.

Any idea what is wrong with the basic set up?   Also the "Test" button seems to not work in the portal.

![image](https://user-images.githubusercontent.com/4327773/33716026-33897d6e-db1a-11e7-8b24-b6cc52851f76.png)

![image](https://user-images.githubusercontent.com/4327773/33715971-0dfe2554-db1a-11e7-9b84-90c22713330d.png)

**Comment by nwhitmont** [comment]
Hi @jrmcdona - Thanks for reporting. 

It's possible that your bot portal issues automagically resolved themself.  When I checked your bot in the portal just now, the bot was responding normally and I didn't see any errors or warnings. 

Let me know if you are still seeing the issue.

**Comment by jrmcdona** [comment]
Yup stil there.   It is also there for the other FTE team member.
https://dev.botframework.com/bots?id=AmbPreviewSkypeBot

**Comment by jrmcdona** [comment]
@nwhitmont In addition it does not migrate nor does the Test function work
https://dev.botframework.com/bots?id=AmbPreviewSkypeBot

Can you try migrating for us - maybe that will fix the issue or can you look at the backend?  Our botId is already whitelisted for things we are doing with Skype and would rather not have to redo that as those teams are slammed.  

Our bot exists and I am not sure what is up with the portal.

![image](https://user-images.githubusercontent.com/4327773/34007360-21049d1a-e0c7-11e7-8c0c-d93eacac357b.png)

**Comment by nwhitmont** [comment]
Thanks for the update @jrmcdona - Glad to hear you got it working.
