### ISSUE TITLE
[Question] BotBuilder SDK v4 Roadmap?

### ISSUE THREAD

**Issue by SynerG** [Microsoft/BotBuilder#3891]
Some issues such as #3639 (limitations of the current i18n implementation) or #3674 (Waterfall default behaviour) have been closed because there is a **SDK v4** in the works that is expected to solve them or provide the means to do it.

**v4** has been said to be *"a complete re-write"* of the SDK and *"much more modularized"*, but beyond that there is not much information about it.

It would great if you could share info about the Roadmap or development status of v4.

We are delighted, but a little bit scared about this complete re-write of the SDK.

In the current situation, many doubts arise:
- Will v4 be backward compatible with v3? Will bots developed for v3 seamlessly work with v4 or they will need a significant rewrite?
- What is the expected design (architecture and modules) of v4? 
- Which new features will it bring?

Without more info about it, we don't know if investing into using v3 and adapting it to our needs is a good idea. If we do not know how v4 will be, it is hard to prioritize what we should focus our time on, as our adaptations may be already implemented in the upcoming version or (on the other side) may require a complete rewrite in v4.

Both the community and the Bot Framework team could benefit from a public Roadmap of v4 in order to provide feedback about the future version and be prepared for it.

Maybe the Roadmap could be shown in a Github issue or have an alpha branch in the repo with v4 so we can stay tuned on its progress. Any kind of information would be highly welcome.

**Comment by agonbina** [comment]
It would be great if someone from the core team could address this request, regardless if this is doable or not.

I personally would be happy if there is even just an overview of what is coming in the next release and, specifically, backward compatibility with v3. This is critical information for users who are just starting to build their bot services with v3 and need to think ahead of upcoming breaking changes(if any) or new features that would potentially deem unnecessary hacking the existing implementation to do something that would be in the core implementation with the next release.

And last but not least, just taking the opportunity to thank the whole team for open sourcing this wonderful framework for building bots 👏👏👏

**Comment by JasonSowers** [comment]
We will respond to this thread as soon as we can make information publically available.

**Comment by sidecus** [comment]
Looking forward to an update on this topic. Have been waiting for the .net core 2 BotBuilder for a while.

**Comment by nrobert** [comment]
You may have a look there for news about the v4: https://github.com/Microsoft/botbuilder-js/wiki

**Comment by EricDahlvang** [comment]
Closing this, as there is now a public roadmap (thanks for providing the links @nrobert )
