### ISSUE TITLE
[QnA Maker] Repeated response under a conversation id

### ISSUE THREAD

**Issue by MadhuAcc12** [Microsoft/BotBuilder#3892]
I noticed that if the number of messages under the conversation id exceeds 100 the bot keeps giving the response of the 99th question. This is affecting my application's accuracy. One of the conversation id for which I faced this shows only 5 questions under it which means the number of questions did not reach 100 and still I get the response of that question as the same as the 99th question. Could you please help us resolve this?

**Comment by xjose97x** [comment]
Can you please share more information? Are you using DirectLine in .NET or NodeJS?

Usually when you receive repeated answers is because you're not sending a watermark in your request or the watermark is not updated.

**Comment by JasonSowers** [comment]
Have you implemented a state store or are you using the default?

**Comment by MadhuAcc12** [comment]
Why is this post tagged to QnAMaker? I am not using QnAMaker. I am using the Bot framework and I have not implemented anything called as state store.

**Comment by MadhuAcc12** [comment]
Why is this post tagged to QnAMaker? I am not using QnAMaker. I am using the Bot framework and I have not implemented anything called as state store.

**Comment by MadhuAcc12** [comment]
@xjose97x I am using directline in .net

**Comment by xjose97x** [comment]
@MadhuAcc12 The reason why you're facing this issue is most likely due to the watermark not being sent and/or updated.  Did you check that?

**Comment by JasonSowers** [comment]
closing as no response from user
