### ISSUE TITLE
[Node.js]  Why is Echo Bot code not working for me in skype or webchat?

### ISSUE THREAD

**Issue by aseemrastogi** [Microsoft/BotBuilder#3894]
## Bot Info 
* App ID: 0f6277fb-1e76-4a6d-a641-f1de7d8d9f63
* SDK Platform: Node.JS
* SDK Version: 3.13.1
* Active Channels: Skype, WebChat
* Deployment Environment: Self hosted Node over selfsigned SSL certificates. Channel emulator wrks fine

## Issue Description

![image](https://user-images.githubusercontent.com/16461668/33771148-fbccd35c-dc55-11e7-9f10-69e666885ba3.png)

## Code Example
https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-quickstart

Took sample code to echo the same message back to user from MSFT website

## Reproduction Steps
1. Download Sample from MSFT
2. Deploy in Node, Assign selfsigned SSL certs
3. Register Bot in https://dev.botframework.com 
4. Try to test in Webchannel, does not work

## Expected Behavior
Should have communicated with bot the way Emulator can.

## Actual Results
Error showed up on webchannel
![image](https://user-images.githubusercontent.com/16461668/33771329-a9906d46-dc56-11e7-895c-73a00c136a7d.png)

On Skype channel, nothing happens although it shows bot online.

**Comment by JasonSowers** [comment]
Could you please post your complete bot's code as well.

**Comment by JasonSowers** [comment]
Just to clarify I followed [these instructions](https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-quickstart) to build the bot, and [these instructions](https://docs.microsoft.com/en-us/bot-framework/deploy-bot-github) to deploy and it was working for me.

**Comment by aseemrastogi** [comment]
Hi - I see that one of the requirements you listed is a SSL certificate by trusted root CA. As I mentioned, I am using self-signed certificates. Could that be the root cause of issue? Where can I see SSL handshake error or debug?

I mean for testing 'Hello World' it is a very burdensome requirement on developers. 

Please let me know if there are any possible workarounds.

Appreciate your time & help.

**Comment by aseemrastogi** [comment]
Hi - after adding SSL certificates it works fine for webchat.
Skype gives error -

Error: POST to 'https://smba.trafficmanager.net/apis/v3/conversations/29%3A1xxxxxxOp/activities' failed: [400] Bad Request
    at Request._callback (C:\Software\msft-bot\node_modules\botbuilder\lib\bots\ChatConnector.js:545:46)
    at Request.self.callback (C:\Software\msft-bot\node_modules\request\request.js:186:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (C:\Software\msft-bot\node_modules\request\request.js:1163:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (C:\Software\msft-bot\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)

**Comment by JasonSowers** [comment]
@aseemrastogi Hsve you resolved this or are you still having the same issue?

**Comment by aseemrastogi** [comment]
It works fine now. Thanks for your help.
