### ISSUE TITLE
[State Service] session.dialogData issue after switching to in-memory storage?

### ISSUE THREAD

**Issue by mlnewbie** [Microsoft/BotBuilder#3897]
**Bot Info** 
* App ID: cb62b172-3eab-4c33-9fb9-4df68f35cf70
* SDK Platform:  Node.js
* SDK Version: 6.5.0
* Active Channels: Slack, WebChat
* Deployment Environment: Auzure Bot Service (Consumption Plan), LUIS Bot 

**Issue Description**
Updated the bot to use inMemory Bot Storage but session.dialogData variables are not getting stored 

**Code Snippet**

```js
var connector = useEmulator ? new builder.ChatConnector() : new botbuilder_azure.BotServiceConnector({
    appId: process.env['MicrosoftAppId'],
    appPassword: process.env['MicrosoftAppPassword'],
    stateEndpoint: process.env['BotStateEndpoint'],
    openIdMetadata: process.env['BotOpenIdMetadata']
});

var inMemoryStorage = new builder.MemoryBotStorage();
var bot = new builder.UniversalBot(connector).set('storage',inMemoryStorage);
.....
    builder.Prompts.text(session, "Please mention your policy ID");
},
function(session, results, next) {
    if(results.response) {
        session.dialogData.policyNumber = results.response.entity;
        session.send("%s Policy number", session.dialogData.policyNumber);
    }
    builder.Prompts.text(session,"Please enter your Payment Month:");
}, 

```
**Output**
undefined Policy number 

**Package.json**
```js
{
   "name": "luisbot",
   "version": "1.0.0",
   "description": "",
   "main": "index.js",
   "dependencies": {
   "botbuilder": "^3.7.0",
   "botbuilder-azure": "3.0.2",
   "apiai": "^4.0.3",
   "express": "^4.15.4",
   "express-favicon": "^2.0.0"
}
```

**Comment by nwhitmont** [comment]
@mlnewbie What happens after you upgrade `botbuilder` to `3.13.1` (current)?

**Comment by mlnewbie** [comment]
Hi I tried specifying botbuilder directly as 3.13.1 in package.json and then did an npm update but the issue persists. Have reverted back to specifying ^3.7.0 which I think anyway pulls the latest version? Thanks 

-----Nils <notifications@github.com> wrote: -----
To: Microsoft/BotBuilder <BotBuilder@noreply.github.com>

**Comment by pezholio** [comment]
This seems to be an issue to me too (on 3.13.1). `session.dialogData` logs to the console, but I can't output any of the variables in a chat
