### ISSUE TITLE
[WebChat] How to Remove User Name and Bot Name after the messages being sent?

### ISSUE THREAD

**Issue by satyansh-sagar** [Microsoft/BotBuilder#3899]
## Issue Description

I want to remove user name and bot name after each message being sent and received.
Refer the screenshot below : 
![issue](https://user-images.githubusercontent.com/30821164/33796551-6fcec1cc-dd1c-11e7-9b49-e34d420fba6e.PNG)

In  the image i want to remove 'Lindsey from maids in black' and 'userid' after each message.

**Comment by nwhitmont** [comment]
Hi @satyansh-sagar - If you would like to customize the WebChat module, you can find the source code and instructions here:

https://github.com/Microsoft/BotFramework-WebChat
