### ISSUE TITLE
Node: EntityRecognizer.parseBoolean invalid regex

### ISSUE THREAD

**Issue by beebes** [Microsoft/BotBuilder#39]
EntityRecognizer.parseBoolean uses invalid format regexes for yexExp and noExp that cause all values to be recognized as undefined instead of true or false, making Prompts.confirm() unusable.

The regexes use a "\z" character seemingly in an attempt to require an end of line anchor, but this is not valid in JavaScript, so they should use "$" instead.

**Comment by Stevenic** [comment]
Thanks... Nice catch. I ended up just removing the end of line test and leaving it open. This got missed because I failed to add a unit test for Prompts.confirm() which I also added. Thanks again. There's a new 0.6.5 release containing the fix.
