### ISSUE TITLE
Buttons in FormFlow

### ISSUE THREAD

**Issue by ankitbko** [Microsoft/BotBuilder#390]
Is it possible to display an enum/dynamic field in form as buttons with images? I see there is a FormButton class, but I didn't get how do I use it.

**Comment by manu4rhyme** [comment]
In the bot emulator, they automatically get converted to buttons...
It does in my project and also in the sandwich bot. It depends on whether the channel supports it or not. Like buttons are not supported if you channel  the same sandwich bot thing to skype

I'm not sure about images though

**Comment by ankitbko** [comment]
@manu4rhyme It does show up in emulator. However there is no way to modify the button's Title, Image or URL as they are present in FormButton class. I was hoping that Skype would have started supporting buttons as it was shown in Build 2016. 
Do we have a place where we can see each channels capabilities? This would help a lot.

**Comment by Stevenic** [comment]
None of the platforms that support buttons allow this level of customization. Line is probably the closest but we don't currently support Line.

**Comment by willportnoy** [comment]
@LarsLiden do we have any documentation on the various channel capabilities?

**Comment by ankitbko** [comment]
Facebook also seems to have at least some feature supported with Structured Message. https://developers.facebook.com/docs/messenger-platform/implementation

However I was at least looking for Images to be configurable from Form. I can do it if I directly create `Microsoft.Bot.Connector.Action` objects and attach it to the `Message`. How can I achieve the same from Form?
I was hoping to get something like the image below. In Build it was showcased with Skype. It might be that this version of Skype is not released yet. 
![Skype Bot](https://cloud.githubusercontent.com/assets/3169316/15735330/829df434-28b5-11e6-9eea-ca634809810e.png)

**Comment by Stevenic** [comment]
@ankitbko great suggestion

**Comment by v-thgratMSGit** [comment]
Closing this suggestion. Thanks!
