### ISSUE TITLE
[Localization] JSON.parse Unexpected token ﻿ in JSON at position 0  on  DefaultLocalizer.js

### ISSUE THREAD

**Issue by logcorner** [Microsoft/BotBuilder#3900]
Hi, I think there is a bug in botbuilder nodeJs . var entries = JSON.parse(data); throws an exception on file DefaultLocalizer.js the error message is : Unexpected token ﻿ in JSON at position 0 . notes : data = "﻿{"locale_prompt": "test"}" and is retrieved from ressouce file (locale/en/index.json)
but if I hardcode data = '{"locale_prompt": "test"}' it works fine

**Comment by nwhitmont** [comment]
@stevengum97 thoughts?

**Comment by logcorner** [comment]
Hi, if I replace  line 1 by line 2, it works

1. var entries = JSON.parse(data);
2. var entries = JSON.parse(data.toString('utf8').replace(/^\uFEFF/, '')); //JSON.parse(data);

Best regards

**Comment by nwhitmont** [comment]
Thanks for the update @logcorner - Glad to hear you found a solution.
