### ISSUE TITLE
[Question] replaceDialog and builder.Prompts.* does not work when replaceDialog is inside the main dialog?

### ISSUE THREAD

**Issue by sushovannits** [Microsoft/BotBuilder#3902]
## Bot Info 
* App ID: 2521dc1d-4b6d-448a-a886-0317fd07f7a6
* SDK Platform: Node.js
* SDK Version: `botbuilder@3.13.1`
* Active Channels: WebChat
* Deployment Environment: ngrok

## Issue Description
* The bot begins a 'mainBotMenu' dialog that prompts user two choice of QnA and Bye. Clicking on QnA beginDialog 'q&aDialog' whereas 'Bye' should end the conversation.
* Intention is to make this 'mainBotMenu' dialog repeat/reload itself using the replaceDialog method unless the user presses/chooses 'Bye' option.
* If  we do the replaceDialog inside this mainBotMenu dialog and q&aDialog has some builder.Prompts.text inside it, then the prompt does not wait for text input and a error as below is thrown:
Error: Dialog[BotBuilder:mainBotMenu] not found.
<img width="1043" alt="screen shot 2017-12-11 at 4 25 41 pm" src="https://user-images.githubusercontent.com/5388540/33816837-1053e2d4-de90-11e7-93c4-6e48434956a7.png">

## Code Example
```js
var builder = require('botbuilder');
var inMemoryStorage = new builder.MemoryBotStorage();

// Setup bot and root waterfall
// var connector = new builder.ConsoleConnector().listen();
var connector = new builder.ChatConnector({
    appId : '2521dc1d-4b6d-448a-a886-0317fd07f7a6',
    appPassword : '*****************'
});
var bot = new builder.UniversalBot(connector, [
    function (session) {
        session.beginDialog('mainBotMenu');
    },
    function (session, results) {
        session.send("Thanks %(name)s... You're %(age)s and located in %(state)s.", results.response);
    }
]).set('storage', inMemoryStorage); // Register in memory storage

bot.dialog('mainBotMenu', [
    (session,args, next) => {
        if (args && args.resumed && args.resumed == true) {
            session.send('What more can I do today?');
        } else  {
            session.send('Welcome to QnA assistant bot 🤖!!!');
        }
        next();
    },
    (session) => {
        const card = new builder.ThumbnailCard(session);
        card.buttons([
            new builder.CardAction(session).title('QnA').value('QnA').type('imBack'),
            new builder.CardAction(session).title('Bye').value('Bye').type('imBack')
        ]);
        const message = new builder.Message(session);
        message.addAttachment(card);
        session.send('What do you want to do today?');
        builder.Prompts.choice(session, message, ['QnA', 'Bye']);
    },
    (session, result) => {
        if(result.response){
            if (result.response.entity == 'QnA') {
                console.log('here');
                session.beginDialog('q&aDialog');
                console.log('Back from QnA dialog');
            } else if (result.response.entity == 'Bye') {
                console.log('bye');
                session.endDialog();
            }
        }
        session.replaceDialog('mainBotMenu');
    }
]);

// Add Q&A dialog
bot.dialog('q&aDialog', [
    function (session, args) {
        // Save previous state (create on first call)
        session.dialogData.index = args ? args.index : 0;
        session.dialogData.form = args ? args.form : {};

        // Prompt user for next field
        builder.Prompts.text(session, questions[session.dialogData.index].prompt);
    },
    function (session, results) {
        // Save users reply
        var field = questions[session.dialogData.index++].field;
        session.dialogData.form[field] = results.response;

        // Check for end of form
        if (session.dialogData.index >= questions.length) {
            // Return completed form
            session.endDialogWithResult({ response: session.dialogData.form });
        } else {
            // Next field
            session.replaceDialog('q&aDialog', session.dialogData);
        }
    }
]);

var questions = [
    { field: 'name', prompt: "What's your name?" },
    { field: 'age', prompt: "How old are you?" },
    { field: 'state', prompt: "What state are you in?" }
];

var restify = require('restify');
var server = restify.createServer();
server.listen(3978, function() {
    console.log('test bot endpont at http://localhost:3978/api/messages');
});
server.post('/api/messages', connector.listen());
```

## Reproduction Steps
1. Run the bot and connect with emulator
2. Ping the bot and the option menu comes up. Select QnA option

## Expected Behavior
It should wait for the text input and there should not be any Error: Dialog not found!!

## Actual Results
It does not wait for text input and there is a error that Dialog not found though the dialog is there.

## Workaround
If we place the replaceDialog inside the q&aDialog instead of the mainBotMenu dialog after the prompt step then it works fine.

**Comment by sgellock** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
