### ISSUE TITLE
[Question] How to show HTML Content in card or attachment?

### ISSUE THREAD

**Issue by christianfelixmerz** [Microsoft/BotBuilder#3903]
Is it possible to show HTML Content in a Bot Card/Attachment?
In this Case, we retrieve the content field of a Dynamics 365 CRM Knowledge Article which is in HTML Format and want to show it to the customer.

**Comment by FranciscoPonceGomez** [comment]
Hi 
@christianfelixmerz,

HTML is not directly supported. 
https://blog.botframework.com/2017/09/07/html-not-supported-web-chat/

If HTML rendering in Web Chat is a critical feature for your applications, you can clone or fork a copy of the Web Chat source code from GitHub, and enable it (on your own custom Web Chat client):
https://github.com/Microsoft/BotFramework-WebChat#markdown

Regards,
Francisco
