### ISSUE TITLE
[Question] Missing ServiceURL in BotBuilder messages?

### ISSUE THREAD

**Issue by JpEncausse** [Microsoft/BotBuilder#3905]
## Bot Info 
* SDK Platform: Node.js
* SDK Version: 3.13.1
* Active Channels: DirectLine, Emulator, WebChat
* Deployment Environment: Custom Azure Server

## Issue Description

Get the issue `ChatConnector: send - message is missing address or serviceUrl.`
The root cause is that BotBuilder send messages without `ServiceURL`

This **issue is at random**, when a user lost it's ServiceURL url it continue to fail.
 
Sometimes we saw 2 URLs, 
- https://directline.botframework.com/ 
- https://bc-directline-weurope.azurewebsites.net/ 

Yes we are in Europe ;-) may be an A/B testing or loadbalancing issue ?

## Code Example

This is what we received from BotBuilder:

```
{ type: 'message',
 timestamp: '2017-12-11T15:55:02.5878593Z',
 textFormat: 'plain',
text: 'Le 20 à 12h',
textLocale: 'fr',
sourceEvent: { clientActivityId: '1513007017858.5455204729888212.38' },
attachments: [],
entities: [],
 address: {},
source: undefined,
agent: 'botbuilder',
user: { id: '1513007017848', name: 'Vous' } }
```

There is no ServiceURL so it fails.

## Expected Behavior
We should alwayse receive a ServiceURL in order to be able to reply

## Actual Results
No ServiceURL  means no replies

**Comment by nwhitmont** [comment]
Hi @JpEncausse - Thanks for reporting. 

How do you reproduce this error? Or is is just random?

Can you provide a `conversationId` for an instance where the error happened? This is useful for us in tracking down the issue.

**Comment by JpEncausse** [comment]
It seems to be at random until the wrong service URL is triggered.

We don't think it comes from our code because the mesage received from BotBuilder has the very begining missed the serviceURL parameter.

Could it be related to something you are working on with Europe bot-services ?

**Comment by JpEncausse** [comment]
More details:
`bot.dialog('/', [(session) => { /* sometimes the message is completly wrong */ }]);`

But in that case we receive **2 (or 3) messages** ?!!
`bot.on('incoming', (msg) => { info("Message incoming:" + JSON.stringify(msg) ); })`

The first one is OK the second one is KO. It seeems the bot.dialog() receive the second one. We do not understand why we receive 2 messages and why some of those are KO

```
Message incoming:{"type":"message","timestamp":"2017-12-12T14:26:42.1955929Z","textFormat":"plain","text":"hello","textLocale":"fr","sourceEvent":{"clientActivityId":"1513088197764.2002295011765569.2"},"attachments":[],"entities":[],"address":{"id":"9C2bWGLPkAhKMsqeTypPSF|0000001","channelId":"directline","user":{"id":"1513088197751","name":"Vous"},"conversation":{"id":"9C2bWGLPkAhKMsqeTypPSF"},"bot":{"id":"amaline@z4YOxv0iJnY","name":"Hector"},"serviceUrl":"https://directline.botframework.com/"},"source":"directline","agent":"botbuilder","user":{"id":"1513088197751","name":"Vous"}}

Message incoming:{"type":"message","timestamp":"2017-12-12T14:26:42.1955929Z","textFormat":"plain","text":"hello","textLocale":"fr","sourceEvent":{"clientActivityId":"1513088197764.2002295011765569.2"},"attachments":[],"entities":[],"address":{},"agent":"botbuilder","user":{"id":"1513088197751","name":"Vous"}}
```

**Comment by JasonSowers** [comment]
Please open a new issue if you are still experiencing problems after updating to the latest package
