### ISSUE TITLE
[InMemoryDataStore] Throwing "Inconsistent SaveAsync based on ETag!"

### ISSUE THREAD

**Issue by ederbond** [Microsoft/BotBuilder#3906]
## Bot Info: Bot da Toro
* App ID: 0b0170f6-6a74-44a8-889d-2faa73ca62bb
* SDK Platform: .NET
* SDK Version: "Microsoft.Bot.Builder" version="3.12.2.4"
* Active Channels: Direct Line
* Deployment Environment: ngrok + local IIS hosted in Brazil

## Issue Description
I'm frequently receiving this error while interacting with my bot via Directline-JS:
![image](https://user-images.githubusercontent.com/12549812/33849532-13c11f38-de98-11e7-919a-6427c8b2d8aa.png)

**Comment by nwhitmont** [comment]
Hi @ederbond - Direct Line has a 15 second timeout. If your bot is taking more than 15s to respond, then you need look at code or network optimizations to get the response time within range.

**Comment by EricDahlvang** [comment]
@ederbond There is a 40 connections / minute limit on the free tier of ngrok:  https://ngrok.com/pricing  Maybe that limit is being exceeded.

**Comment by ederbond** [comment]
@nwhitmont  My bot is not taking to much to retrive the response. 
According to the application insights it is taking around 2 seconds to retrieve the response. But it is taking an ethernity to flow to the client that is using the DirectLineJS to communicate.

Thank you @EricDahlvang, I'll publish my bot to a public IIS server (without ngrok) and see if the issue persist.

**Comment by ederbond** [comment]
Hey @EricDahlvang, look at this (still using ngrok):
![image](https://user-images.githubusercontent.com/12549812/33896242-7b647dcc-df49-11e7-9a8d-f249dddc323b.png)
Sometimes the same request are taking +37 seconds to be posted to bc-directline-brazils.azurewebsites.net | cid-v1:91e46abb-4ce5-4d98-9375-02378f649011

**Comment by ederbond** [comment]
According to the application insights it is definetly the botconnector (represented by the "bc-directline-brazils.azurewebsites.net | cid-v1:91e46abb-4ce5-4d98-9375-02378f649011" dependency that is slowing my bot response. Am I right ?

**Comment by ederbond** [comment]
Hello @EricDahlvang, the behavior of the bortframework is kind of scaring me:
Now, I'm randomly receiving a message "Sorry, my bot code is having an issue." while interacting with my bot using 4 instances of my DirectLineJS client.

![image](https://user-images.githubusercontent.com/12549812/33900749-ba340920-df56-11e7-839f-e1a14fbe367b.png)

Could you help-me ?

**Comment by ederbond** [comment]
After enabling Elmah on my bot I've find out that the `Microsoft.Bot.Builder.Dialogs.Internals.InMemoryDataStore` is causing an exception that is making my bot return the  "Sorry, my bot code is having an issue." message to my client.

Now the question is:
Is this InMemoryDataStore deprecated or possibly have issues with quick multiple requests ?
How to solve the exception bellow:
![image](https://user-images.githubusercontent.com/12549812/34383743-9f60e8c6-eafe-11e7-8112-bfb96cb0330c.png)

**Comment by ederbond** [comment]
https://github.com/Microsoft/BotBuilder/issues/3973
