### ISSUE TITLE
[Bot Service] Cannot change bot settings- Receive error: "CorrelationID: |eOT3Y.6b19c262_"?

### ISSUE THREAD

**Issue by jldenigris** [Microsoft/BotBuilder#3907]
## Bot Info 
* App ID: c7045879-2c6b-4d1f-bcc8-32a5c46e9da0
* Deployment Environment: Azure Bot Service

## Issue Description
I created a QnA bot via Azure/Microsoft QnA maker. Ever since creation I have been unable to edit any of the settings and save without receiving the error: CorrelationID: `|eOT3Y.6b19c262_`

I would like to be able to change the name of the bot and input my LUIS app ID. 

## Reproduction Steps
1. Login to Azure and Choose my bot PPRBDFAQ
2. Click on settings tab
3. Edit and save updated settings

## Expected Behavior
I expect the settings to be saved. 

## Actual Results
 Continue to receive error code: CorrelationID: |eOT3Y.6b19c262_ - have tried for the last couple of days. I am on a deadline and need to get this information updated. Please help.

**Comment by FranciscoPonceGomez** [comment]
Hi @jldenigris,

Try adding and removing a channel and then hard refresh the page. This is normally just a temporary error and normally goes away after refreshing.
