### ISSUE TITLE
[Question] How can I use my own certificate for bot deployed as an Azure App Service?

### ISSUE THREAD

**Issue by neetgupta7** [Microsoft/BotBuilder#3908]
* SDK Platform: .NET
* SDK Version: 3.11.0
* Active Channels: Webchat, cortana
* Deployment Environment: Azure App Service

Hello
I am interested in using my own certificate for my azure app service for bot. Once do I need to make any changes in bot registration or anywhere else so the seamless communication is not impacted.

**Comment by nwhitmont** [comment]
Hi @neetgupta7 - You don't need to add any extra configuration from the bot registration side of things. As long as your bots messaging endpoint is accessable over HTTPS with valid certificate you are good to go. 

For more info on configuring your SSL certificate in Azure App Service, see:
https://docs.microsoft.com/en-us/azure/app-service/web-sites-purchase-ssl-web-site

**Comment by nwhitmont** [comment]
Hi @neetgupta7 - Were you able to resolve the issue with the SSL certificate?

**Comment by JasonSowers** [comment]
please open a new issue if you are still experiencing problems
