### ISSUE TITLE
[Feature Request] Using observer pattern for logger in Node.js

### ISSUE THREAD

**Issue by t-elcohe** [Microsoft/BotBuilder#3910]
Hi,

I'm working with Node.js and I want to be able to save your logs to Application Insights. 
SessionLogger object is currently printing all the logs to console.

My first thought was to replace SessionLogger with one of my own, but I couldn't find a suitable interface. I consulted Bot Framework Support Engineers group, which really helped and suggested doing a PR and add the relevant interface.

Given it a second thought, I believe it would be better to use Observer design pattern, with some Node.js native module, and allow the user to add their own listeners.

I saw you are following this pattern in .NET environment by using Trace -
https://github.com/Microsoft/BotBuilder/blob/497252e8d9949be20baa2cebaa6ce56de04461cf/CSharp/Library/Microsoft.Bot.Builder/ConnectorEx/IActivityLogger.cs

Please consider changing the logger's logic for Node.js

Thank you very much,
Eldar

**Comment by nwhitmont** [comment]
@t-elcohe Thanks for the suggestion.

**Comment by sgellock** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
