### ISSUE TITLE
[Question] Calling the bot directlty from code?

### ISSUE THREAD

**Issue by ihachani** [Microsoft/BotBuilder#3911]
## Bot Info 
* SDK Platform: Node.js
* SDK Version: 3.13.1
## Issue Description
Is there a way to call the bot created by the bot builder directly using a simple method call without using "restify".

**Comment by nwhitmont** [comment]
Hi @ihachani

The short answer to your question is "no". If you don't wire your bot to the restify server module, your bot would have no way to communicate with other web services, aka the bot connector service, and associated channels. The bot is a server-side web application, essentially an API server that handles your bot's messages,  and restify is the server package.
