### ISSUE TITLE
[Cortana] "endOfConversation" results in Cortana reporting that there was an error in skill

### ISSUE THREAD

**Issue by deybhayden** [Microsoft/BotBuilder#3913]
## Bot Info 
* App ID: c9391606-842e-44a1-a466-28da1d9d7c46
* SDK Platform: REST API
* Active Channels: Skype, Cortana
* Deployment Environment: AWS Elastic Beanstalk

## Issue Description

I can open a new issue if that's preferred, but it looks like Cortana channel also thinks there is something wrong with this activity type. She says "Uh-oh, There was something went wrong with the selected skill".

## JSON Example

```json
{
  "error": {
    "botId": "foobot",
    "botRequest": {
      "type": "message",
      "id": "JvnZMzqix9G",
      "timestamp": "2017-12-11T21:48:47.0859626Z",
      "serviceUrl": "https://CortanaBFChannelEastUs.azurewebsites.net/",
      "channelId": "cortana",
      "from": {
        "id": "11111111"
      },
      "conversation": {
        "id": "22222222"
      },
      "recipient": {
        "id": "foobot"
      },
      "locale": "en-US",
      "text": "No",
      "entities": [
        {
          "type": "Intent",
          "name": "Microsoft.NoIntent",
          "entities": []
        },
        {
          "type": "DeviceInfo",
          "supportsDisplay": "true"
        }
      ],
      "channelData": {
        "skillId": "444444444",
        "skillProductId": "555555555555",
        "isDebug": true
      }
    },
    "botResponse": {
      "type": "endOfConversation",
      "from": {
        "id": "foobot",
        "name": null
      },
      "topicName": null,
      "timestamp": null,
      "textFormat": null,
      "text": null,
      "summary": null,
      "speak": null,
      "serviceUrl": null,
      "replyToId": null,
      "recipient": null,
      "membersRemoved": null,
      "membersAdded": null,
      "locale": null,
      "inputHint": null,
      "id": null,
      "historyDisclosed": null,
      "entities": null,
      "conversation": null,
      "channelId": null,
      "channelData": null,
      "attachments": null,
      "attachmentLayout": null,
      "action": null
    }
  },
  "traceId": "333333333"
}
```
Log

## Reproduction Steps
1. Ending my skill's conversation from my API shouldn't cause a Cortana error per the [documentation](https://docs.microsoft.com/en-us/bot-framework/rest-api/bot-framework-rest-direct-line-3-0-end-conversation).

## Expected Behavior

Ending the conversation should exit the skill and not throw an error.

## Actual Results

Cortana says there was an error in the skill and the skill closes.

**Comment by gtarcoder** [comment]
Developer should fill Activity's Code to EndOfConversationCodes.CompletedSuccessfully if there is nothing wrong with the skill, like

Activity endMessage = activity.CreateReply();
endMessage.Type = ActivityTypes.EndOfConversation;
endMessage.Code = EndOfConversationCodes.CompletedSuccessfully;

**Comment by deybhayden** [comment]
Okay, cool, so in a REST call, it would be something like `"code": "completedSuccessfully"` in my message payload?

**Comment by deybhayden** [comment]
Yep, that works. Thanks.
