### ISSUE TITLE
botbuilder-azure typescript definition file is missing ConnectionOptions, ConnectionConfig definitions from tedious

### ISSUE THREAD

**Issue by renil** [Microsoft/BotBuilder#3915]
## Issue Description
When building bots using NodeJS and typescript, including botbuilder-azure reference to include Cosmos DB for storage causing build issues.

## Packages used
```
"botbuilder": "^3.13.1",
"botbuilder-azure": "^3.0.4"
```

## Code Example
```
import * as builder from 'botbuilder';
import * as azureState from 'botbuilder-azure';
```

## Reproduction Steps
1. Create a new Node JS project
2. Use typescript to create the main files
3. Include the packages and import the packages to the main file
4. Running tsc causing compilation errors

## Expected Behavior
No typescript compile errors.

## Actual Results
`import { ConnectionOptions, ConnectionConfig } from "tedious";` is missing in the type definition file and is causing compilation errors.
```
node_modules/botbuilder-azure/lib/botbuilder-azure.d.ts(252,49): error TS2304: Cannot find name 'ConnectionConfig'.
node_modules/botbuilder-azure/lib/botbuilder-azure.d.ts(259,43): error TS2304: Cannot find name 'ConnectionOptions'.
```

**Comment by nwhitmont** [comment]
Hi @renil - Please report the issue on the `botbuilder-azure` project repository. Thanks

https://github.com/Microsoft/BotBuilder-Azure/issues/new
