### ISSUE TITLE
[WebChat] Passing user info securely through webchat by using default webchat channel?

### ISSUE THREAD

**Issue by neetgupta7** [Microsoft/BotBuilder#3918]
* SDK Platform:  .NET 
* SDK Version: 3.11.0
* Active Channels: webchat
* Deployment Environment: Azure App Service

Hello
I know that the userid information can be passed as a query string parameter to the Bot. But if somebody intercepts the url and changes the user id then that may result into security violation. How can I securely pass user information to bot using webchat.

**Comment by nwhitmont** [comment]
Answer from @EricDahlvang -

>The site that hosts the page with WebChat can exchange the secret for a token before serving up the page itself.  In a .net bot, this can be done with an mvc setup.  

I’ve created an example here: https://github.com/EricDahlvang/TokenBotExample  

The code that exchanges the secret for a token is as follows:
 ```cs
string botChatSecret = ConfigurationManager.AppSettings["BotChatSecret"];
 
var request = new HttpRequestMessage(HttpMethod.Get, "https://webchat.botframework.com/api/tokens");
request.Headers.Add("Authorization", "BOTCONNECTOR " + botChatSecret);
 
using (HttpResponseMessage response = await new HttpClient().SendAsync(request))
{
    string token = await response.Content.ReadAsStringAsync();
    Token = token.Replace("\"", "");
}
 ```
>Then the view uses the model’s token:
 ```
BotChat.App({
directLine: {
token: @Model.Token,
       webSocket: false
});
```

**Comment by compulim** [comment]
@neetgupta7 this is similar to if you are passing a security token using HTTP cookie and someone intercept the URL. You can look for the potential solution at https://github.com/Microsoft/BotFramework-WebChat/issues/840. Thanks!
