### ISSUE TITLE
How to send video attachments on fb messenger

### ISSUE THREAD

**Issue by aniketisin** [Microsoft/BotBuilder#392]
Hi,
I want to send video attachments.
The following code doesn't work

Message replyMessage = new Message();
replyMessage.Text = "Video Attachment";
replyMessage.Attachments = new List\<Attachment\>();
replyMessage.Attachments.Add(new Attachment
{
    ContentUrl = "https://www.youtube.com/watch?v=JaXJkbz5vxk",
    ContentType = "video/mp4"
});
return replyMessage;

Facebook mesenger docs say that it supports mime-type = video/mp4

What is the correct way of sending video attachments?

**Comment by tomlm** [comment]
Facebook Messenger docs say:

attachment.type --> Type of attachment, may be image or template

https://developers.facebook.com/docs/messenger-platform/send-api-reference

Where do you see information that says they will accept video?

**Comment by tomlm** [comment]
This is not supported by facebook messenger.

**Comment by brentzucker** [comment]
Facebook supports videos now. https://developers.facebook.com/docs/messenger-platform/send-api-reference/video-attachment

**Comment by thermous** [comment]
this is supported by us exactly as your original question.
