### ISSUE TITLE
[Skype] Cannot send message to bot - getting "Message Not Sent" error?

### ISSUE THREAD

**Issue by khawarashraf** [Microsoft/BotBuilder#3920]
## Bot Info 
* App ID: 6d31eccc-ea5f-47b7-aaa0-7befb04a17a7
* SDK Platform: .NET
* SDK Version: 3.12.2.4
* Active Channels: Skype
* Deployment Environment: Azure App Service 

## Issue Description
When I add bot to Skype, it says cannot send message to bot.

## Reproduction Steps
1. Add bot to skype
2. send message
3. error "not sent"

## Expected Behavior
Should send message

## Actual Results
Message not sent error

**Comment by JasonSowers** [comment]
I am unable to find a bot with an App ID of 6d31eccc-ea5f-47b7-aaa0-7befb04a17a7.  Could you possibly have given the wrong ID?

**Comment by khawarashraf** [comment]
I have been desperately trying to get it to work. I migrated it to Azure but it still didn't work and now its all messed up. I created a new Bot Channel Registration and it still didn't work. Following is the new ID of the bot in Azure and also the issues I'm facing.

App ID: 63a30e96-b341-47c7-a9fa-4480a59f9d83 

1. If it try to create password for this, I get an error about some graphics issue.
2. If I change display name or icon, then I save it, after I refresh the page, it goes back to default.
3. I add bot to Skype and it keeps on giving error, Message not sent.

I have tried creating new Bot Channel Registration, but still doesn't work and on top of that, I cannot delete all the test registration I created. It says Internal Error. I can't even delete this one.

Thanks,
Khawar

**Comment by JasonSowers** [comment]
@khawarashraf  are you still experiencing these issues?

**Comment by khawarashraf** [comment]
Yes, all issues still the same.

**Comment by JasonSowers** [comment]
We are currently working on a fix for these issues, I will update you as we know more.

**Comment by khawarashraf** [comment]
Thank you, looking forward to get it fixed.

**Comment by khawarashraf** [comment]
any updates?

**Comment by JasonSowers** [comment]
Can you please try again our release finally went out yesterday.

**Comment by hpksp** [comment]
@JasonSowers I've been having the same issue for a while. I tried out my bot on skype. still it's not working

**Comment by khawarashraf** [comment]
There is some progress, I can now create new password so that issue is resolved. Unfortunately, everything else is still broken.

When I change the settings (Name, Icon) the changes don't take effect and you lose them when you next time go into that UI (goes back to default)

When I add the bot to skype, it still keep on saying message not delivered.

I cannot delete a bot service once it is created (keeps on saying cannot be deleted)

Thanks,
Khawar

**Comment by khawarashraf** [comment]
any updates?

**Comment by JasonSowers** [comment]
Are you still experiencing issues?

**Comment by khawarashraf** [comment]
What a coincidence, I actually tried deleting the bot this morning and was able to delete it. So I created it again and so far, it is working as expected. Whatever issues it had seems to have sorted out.
