### ISSUE TITLE
[Skype] Cannot send/receive messages in Skype?

### ISSUE THREAD

**Issue by IvanSheyenko** [Microsoft/BotBuilder#3921]
## Bot Info 
* Bot handle: SitecoreGsBot  
* AppID: c26c4e29-f142-4307-b138-68fa1398d226
* SDK Platform:  .NET
* SDK Version: 3.8.0.0
* Active Channels: Skype, Direct Line
* Deployment Environment: Azure App Service

## Issue Description
I have deployed my bot to Azure and can it works in Test window on dev.botframework.com. However when I add it to Skype no messages are coming from bot and if I try to send a message to it skype says send failed.

Bot is not published. It works if I connect with emulator, but only when "Use version 1.0 authentication tokens" option is enabled. 

Any ideas how can I make it work with Skype? Or how to troubleshoot it?

**Comment by nwhitmont** [comment]
Hi @IvanSheyenko - 

Can you provide your bot's App ID? It is a GUID that looks like this: `67e17624-ea95-428b-ac80-4c3b6b270ad3`

**Comment by IvanSheyenko** [comment]
Hi,

AppId: c26c4e29-f142-4307-b138-68fa1398d226

**Comment by IvanSheyenko** [comment]
Hi,

I have solved this by updating to latest version of SDK.
