### ISSUE TITLE
 [Bot Migration] Azure Bot Service migrating info?

### ISSUE THREAD

**Issue by vovanb** [Microsoft/BotBuilder#3924]
Just discovered that exist mandatory requirements to migrate existing bot to  Azure Bot Service.
We developed bot using c# SDK and it is running on -premise data center. 
1. Does it mean that we need to change architecture?
2. We don't have Azure account and used our MS Bot Free of Charge, does it mean that we need to purchase Azure subscription ? What are costs?
3.What is additional limitation with this migration?
Thanks

**Comment by etbuilder** [comment]
Yes we need explanation, a single user could consume up to 100/1000 message per use and this would cost a lot especially if the code hosted somewhere else.

**Comment by etbuilder** [comment]
Ok, i found more info on the website for pricing, there are two different channels; premium and standard and we will only pay for premium  which are for DirectLine and Web Chat only.

**Comment by nwhitmont** [comment]
Hi @vovanb  - You can find more information on the migration process here:

https://docs.microsoft.com/en-us/Bot-Framework/bot-service-migrate-bot

**Comment by pavei** [comment]
We need info!

Because it was complete free. So i did my Business using this platform. How can i host direcline line API? I cant pay 1 dolar by 1000 messages!

**Comment by vovanb** [comment]
Indeed - we even checked in past with ms account managers that service will be completely free!!!

**Comment by nwhitmont** [comment]
The bot registration (in Azure it's called "Bot Channel Registration") is still free - you only incur costs if you use the Azure Bot Service which includes bot hosting and storage account in addition to the bot registration. 

The full pricing details are available here:
https://azure.microsoft.com/en-us/pricing/details/bot-service/

**Comment by vovanb** [comment]
For webchat since it is premium channel - we should pay after 10k of messages, right?

**Comment by pavei** [comment]
Yes we will need to pay!

**Comment by nwhitmont** [comment]
@vovanb @pavei @etbuilder 

Please [contact Azure Support](https://azure.microsoft.com/en-us/support/options/) for any other billing related questions.

**Comment by pavei** [comment]
And the prices are different!

Sorry for posting this after you close.. 

Web Info:

![image](https://user-images.githubusercontent.com/554537/34018062-7a51dfa2-e10f-11e7-8e6c-c72d98328a6e.png)

Pricing area:

![image](https://user-images.githubusercontent.com/554537/34018118-b02726aa-e10f-11e7-8c6b-00b2cc962921.png)

**Comment by EricDahlvang** [comment]
@pavei Thanks for reporting the pricing inconsistency.  We've created a bug internally to have that fixed.
