### ISSUE TITLE
[Node.js SDK, bug] v3.13.1 release throws error on incoming messages

### ISSUE THREAD

**Issue by harshithkashyap** [Microsoft/BotBuilder#3926]
## Bot Info 
* App ID: 
* SDK Platform: Node.js
* SDK Version: 3.13.1
* Active Channels: DirectLine
* Deployment Environment: Azure app service

## Issue Description
After updating the SDK to 3.13.1, the botbuilder SDK is throwing the following error.
```
Error: Can't set headers after they are sent.
```

It seems like [this commit](https://github.com/Microsoft/BotBuilder/commit/eca181033aa688b3906ef249cf1315420a291176) introduced the change adding a `defaultNext`.

We are using botbuilder with express.js. v3.12 works without any issues.

**Comment by matthewfcarlson** [comment]
I'm also seeing this and have a consistent repo.

**Comment by harshithkashyap** [comment]
@nwhitmont  This issue still exists with botbuilder@3.14. Any chance this could get fixed in the next release as we are missing out on SDK updates?

**Comment by daveta** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues


For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botbuilder-channels/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
