### ISSUE TITLE
[Announcement] General Availability of Azure Bot Service and Language Understanding (LUIS)

### ISSUE THREAD

**Issue by nwhitmont** [Microsoft/BotBuilder#3927]
[Bot Framework](https://dev.botframework.com) team is proud to announce the General Availability (GA) release of [Azure Bot Service](https://azure.microsoft.com/en-us/services/bot-service/) and [Language Understanding Intelligence Service (LUIS)](https://luis.ai). 

For more information:
- [Announcing the General Availability of Azure Bot Service and Language Understanding, enabling developers to build better conversational bots](https://azure.microsoft.com/en-us/blog/announcing-the-general-availability-of-azure-bot-service-and-language-understanding-enabling-developers-to-build-better-conversational-bots/)
- [Conversational Bots Deep Dive – What’s new with the General Availability of Azure Bot Service and Language Understanding](https://azure.microsoft.com/en-us/blog/conversational-bots-deep-dive-what-s-new-with-the-general-availability-of-azure-bot-service-and-language-understanding/)

For bot developers:
- Learn how to migrate your bot: https://docs.microsoft.com/en-us/Bot-Framework/bot-service-migrate-bot

**Comment by xjose97x** [comment]
Thanks a lot!
I appreciate a lot the work you guys do.

Keep the good work :+1:  @nwhitmont @EricDahlvang @JasonSowers @willportnoy @stevengum97 @Stevenic @msft-shahins @tomlm (sorry if I missed someone)
