### ISSUE TITLE
[Slack] Occasionally get 500 posting to bot framework

### ISSUE THREAD

**Issue by abharku** [Microsoft/BotBuilder#3928]
## Bot Info 
* App ID: b0dc1bcd-909a-4bfe-954d-09f6ed453081
* SDK Platform: REST API
* SDK Version: I am assuming latest
* Active Channels: Slack
* Deployment Environment: other

## Issue Description
The framework and bot usually works but lately we have seen we get occasionally 500 posting to Microsoft. We are using REST api and we know it's not our code because it works all the time. We have recently developed a SLACK bot for our client and they are not happy with two failures during their demo. 

## Code Example
Server returned HTTP response code: 500 for URL: https://slack.botframework.com/v3/conversations/{conversationID}/activities/66754f5cadb64b548aa6ccf0cb9d6abe

## Reproduction Steps
I guess if you do loads of post you will get this but not sure how to reproduce as usually we get good response

## Expected Behavior
Response posted back to user

## Actual Results
We sent a sorry response.

**Comment by nwhitmont** [comment]
Hi @abharku  - Thanks for reporting. 

Can you provide a `conversationId` for the conversation where the 500 error happened? This will help us investigate.

**Comment by abharku** [comment]
@nwhitmont conversation id - B7Z3X3YF8:T4825C97G:D7XMNJ5S5 
 and andother one at 
Server returned HTTP response code: 500 for URL: https://slack.botframework.com/v3/conversations/B7Z3X3YF8:T4825C97G:D7Y58863D/activities/5f75f299a9254a9783520b8254e73140

**Comment by abharku** [comment]
We are getting more and more of this. Is Slack supported with some SLA or is it advisable to build for them as a direct to Slack?

**Comment by droidpl** [comment]
I believe that is the same isse we are having in https://github.com/Microsoft/BotBuilder/issues/4066

**Comment by fanidamj** [comment]
Closing the issue assuming it as resolved. Please reopen a new issue if it still persists.
