### ISSUE TITLE
[Question] Waterfall Dialog Skipping a Prompt?

### ISSUE THREAD

**Issue by rupeshgx** [Microsoft/BotBuilder#3930]
## Bot Info 
* SDK Platform: Node.js
* SDK Version: 7.8.0

## Issue Description
I have a waterfall dialog in my code. When I try it in my emulator, I see that one of the prompts is skipped and 2 prompts are sent at the same time. Any ideas on how I could go about debugging this would be much appreciated.

## Code
```js
bot.dialog('waterfallDialog', [

	function (session, args, next) {
		var entities = args.intent.entities;

		var entity1 = builder.EntityRecognizer.findEntity(entities, 'entity1');
		var entity2 = builder.EntityRecognizer.findEntity(entities, 'entity2');

		var slots = session.dialogData.slots = {
			entity1: entity1 ? entity1.entity : null,
			entity2: entity2 ? entity2.entity : null
		};

		// Prompt for entity1
		if (!slots.entity1) {
			builder.Prompts.text(session, 'Can you tell me your entity1 ?');
		} else {
			next();
		}
	},
	function (session, results, next) {
		var slots = session.dialogData.slots;

		if (results.response) {
			slots.entity1 = results.response;
		}

		// Prompt for entity2
		if (!slots.entity2) {
			builder.Prompts.text(session, 'Can you tell me your entity2 ?');
		} else {
			next();
		}
	},
	function (session, results) {
    	var slots = session.dialogData.slots;

	    if (results.response) {
	      slots.entity2 = results.response;
	    }

	    // some processing
  	}
]);
```

## Output
waterfallDialog - waterfall() step 1 of 3
waterfallDialog - Session.beginDialog(BotBuilder:prompt-text)
.BotBuilder:prompt-text - Session.send()
.BotBuilder:prompt-text - Session.endDialog()
waterfallDialog - waterfall() step 2 of 3
waterfallDialog - Session.beginDialog(BotBuilder:prompt-text)
.BotBuilder:prompt-text - Session.send()
.BotBuilder:prompt-text - Session.sendBatch() sending 3 message(s)

**Comment by msmohan** [comment]
@rupeshgx Can you share your code? I will try to repro and find an answer. I am interested in 'conversationUpdate' event.
