### ISSUE TITLE
[Cortana] SSML does not work on the iOS App with session.say()?

### ISSUE THREAD

**Issue by areckkimo** [Microsoft/BotBuilder#3931]
## Bot Info 
* App ID: 46262fcf-124f-4ab1-974f-4a3133ea6f01
* SDK Platform: Node.js
* SDK Version: 3.13.1
* Active Channels: Cortana
* Deployment Environment: Auzure Bot Service

## Issue Description
SSLM does not work on the iOS Cortana.

## Code Example
`session.say("I'm not fine.", "I'm not <emphasis level=\"strong\">fine</emphasis>.", {inputHint: builder.InputHint.acceptingInput});`

## Expected Behavior
Cortana should emphasis "fine"

## Actual Results
Cortana speaks the words, for example, emphasis level strong fine emphasis...

**Comment by JasonSowers** [comment]
@areckkimo is this behaving differently than Cortana on other platforms?
