### ISSUE TITLE
[Direct Line] How to configure HTTP GET polling interval?

### ISSUE THREAD

**Issue by weizhenzhao** [Microsoft/BotBuilder#3933]
My colleague meet a wired problem when he using the sample code of direct line
in our back end we will query data for fusion BI report system
so there may be some latency.
But I find the direct-line will call several times, if it doesn't received the reply for my bot
So this will definitely add more latency .
So my question is how to set the poll interval in c# code?
Because currenty it seems that was config by the code
DirectLineClient client = new DirectLineClient(directLineSecret);

and I find no where to change the poll interval .
Please help with me .

I see it writes that in microsoft offical site:

"
Clients that poll using HTTP GET should choose a polling interval that matches their intended use.

Service-to-service applications often use a polling interval of 5s or 10s.

Client-facing applications often use a polling interval of 1s, and issue an additional request ~300ms after every message that the client sends (to rapidly retrieve a bot's response). This 300ms delay should be adjusted based on the bot's speed and transit time.
"

Thanks
weizhen

**Comment by JasonSowers** [comment]
Are you using directlineJS?

**Comment by JasonSowers** [comment]
@weizhenzhao take a look at the `ReadBotMessagesAsync` method in [this sample](https://github.com/Microsoft/BotBuilder-Samples/blob/master/CSharp/core-DirectLine/DirectLineClient/Program.cs) It seems to be exactly what you need

**Comment by weizhenzhao** [comment]
@JasonSowers  thank you . we've used other way to solve this latency . 
1、we would like to query fusion BI RESTful interface in the botApplication. But I found the
     Bot Application can only send 2.5M data to the other app service
2、So we change our idea .  the Bot application just append the url to the fusion BI RESTfusl interface
     and send it to the other app service
3、And we call the fusion BI RESTful interface , in other app service by httpClient.
      So that we solved the latency problem of Bot application long time no respond problem.
      And also improved the performance.

                                                                                                                                  Thank you  very much

Thanks
WeiZhen

**Comment by JasonSowers** [comment]
Glad you found a solution, good luck!
