### ISSUE TITLE
[FormFlow] How to successfully prompt for values?

### ISSUE THREAD

**Issue by xjose97x** [Microsoft/BotBuilder#3935]
Hello.

I've been playing a bit lately with Forms in the BotFramework, but I've not been able to work with float values.

For instance, I have a field like this:

```
[Prompt("¿How much money would you like to transfer?")
public float Amount { get; set; }
```

But the FormFlow is only recognizing when I enter an int and nothing else. (Ex: 1500)

For instance, it should recognize If I reply with:

- 1500.42
- 1500,42
- $1500
- $1500.42
- $1500,42
- The amount I want to transfer is **$1500.42**
- Here's it: **$1500**

Any suggestions?

**Comment by JasonSowers** [comment]
Thanks for reporting this @xjose97x, we will look into this

**Comment by JasonSowers** [comment]
I was unable to reproduce with the same outcome.  I was able to produce some very strange behavior using `float` type.
    
![image](https://user-images.githubusercontent.com/6301037/34275842-d9a2aa06-e653-11e7-9a31-0b9cae7324ee.png)
  
This was all remedied by using the `decimal` type.
    
  
![image](https://user-images.githubusercontent.com/6301037/34275949-4044eef4-e654-11e7-84f9-176eda67cddd.png)

  
```cs
    [Serializable]
    public class ContactMessage
    {
        public string Name { get; set; }

        [Prompt("How much money would you like to transfer?")]
        public double Amount { get; set; }

        public static IForm<ContactMessage> BuildForm()
        {
            return new FormBuilder<ContactMessage>()
                .Message("I just need a few details to submit your message")
                .Build();
        }
    }
```

**Comment by xjose97x** [comment]
@JasonSowers Will provide you with an example as soon I get back to my office.
In the meantime, were you able to see what happened if you entered a float/double value with comma as decimal separator instead of dot? 
Ex: 1500,50 or 12,44.

Also I'm still not sure if Formflow should be able to recognize when I enter a float value in a sentence such as:

"The answer is 1500.42"

Or with a currency indicator such as: "**$**1500,42"

**Comment by JasonSowers** [comment]
FormFlow would only be able to recognize an actual floating point number anything else will give you results like these:  
  
![image](https://user-images.githubusercontent.com/6301037/34277960-d12333a6-e65c-11e7-802a-7489699a4203.png)

However, in the emulator if I change my locale to spanish:
  
![image](https://user-images.githubusercontent.com/6301037/34278127-cf2b66da-e65d-11e7-82a6-c077cbf2a06e.png)
  
It does recognize using a comma separator:
  
![image](https://user-images.githubusercontent.com/6301037/34278146-0135f3f2-e65e-11e7-8fdc-4cf8f82b7f21.png)
  
  
FormFlow has some regex to help it recognize things that are close to what it is looking for in the context of strings.  In the case of numbers (int, double, float) it does not.  This is a case in which LUIS should give you much better results, if not near perfect results.  Assuming you are able to break out that part of your form into a LUIS intent.

**Comment by JasonSowers** [comment]
@xjose97x any update?

**Comment by xjose97x** [comment]
Oops, sorry @JasonSowers  for the late reply. Been a bit inactive due to holidays.

I decided to handle this by making the "amount" field a string, and using a validate function.
In the validate function I remove any dollar symbol (if found), and then I try to parse the string as a float. If the parse was succesful, then it's a valid amount, otherwise reprompt the field in the form.

Also when parsing the string as a float, I'm using "CultureInfo.InvariantCulture" so it can handle a comma or dot as a separator of decimal values.

I guess with a validator I should be able to handle a scenario where the user replies in a sentence such as:
"The amount is $xxxx.xx"
"The reply to that question is $xxxx.xx"
, etc.

Thanks for the help @JasonSowers !

**Comment by JasonSowers** [comment]
Glad you found a solution
