### ISSUE TITLE
[Direct Line] Why IActivity sent from my bot doesn't have an "Id" ?

### ISSUE THREAD

**Issue by ederbond** [Microsoft/BotBuilder#3936]
## Bot Info 
* App ID: 2e784a99-7642-4f3c-8410-d7c560c6e461
* SDK Platform: .Net
* SDK Version: "Microsoft.Bot.Builder" version="3.12.2.4"
                        "Microsoft.Bot.Connector" version="3.12.2.4
* Active Channels: Direct Line
* Deployment Environment: ngrok

## Issue Description
After implementing a IActivityLogger I've noticed that for the massages sent from my bot to the client, they doesn't have the "Id" property setted, it is always null. But I need it filled in order to be able to mount a chronological history on my CRM.

## Code Example
Here is my Logger:
```csharp
public class SalesForceLogger : IActivityLogger
    {
        public Task LogAsync(IActivity activity)
        {
            if (activity.Type == "message")
            {
                Log.Information(JsonConvert.SerializeObject(new { from = activity.From.Id, messageId = activity.Id } ));
            }
            return Task.CompletedTask;
        }
    }
```

## Reproduction Steps
1. Implement an IActivityLogger and set it to be used by your bot
2. Point a break point inside you Logger
3. Send a message to you bot via directline

## Expected Behavior
I would expect that both incoming message and outgoing messages to have the Id property setted 

## Actual Results
Only messages that have been sent from the client has the "Id" property setted.
Messages sent from my bot to the client doesn't have it setted, it is null.

**Comment by EricDahlvang** [comment]
This discussion by Dan Driscoll might be helpful: https://github.com/Microsoft/BotBuilder/issues/2170  He suggests "If you want to add correlation information, you can do that in the ChannelData field, which will be passed between your client and your bot."

I also saw messages with no Id property, when I implemented an IActivityLogger.  I just added an id as the message came in: https://blog.botframework.com/2017/05/05/saving-bot-actions-on-azure-sql-server/#entity-framework-activity-logger

**Comment by ederbond** [comment]
Hi Eric, 
I dont think that setting a `Guid.NewGuid().ToString()` to the messages with no Id property would help me.
Cause I need to somehow present my bot conversation as a history on Salesforce on the same order that it was presented to the user when he was interacting with the bot. So I was expecting to use the "watermark" part of the message "Id" to sort after on my Salesforce report. Assigning a guid will not help on restoring the conversation history on the same order it was presented to the my customer as when he was live with the bot. 
Should I use "timestamp" to sort the messages ? 
Is it safe ? I mean, will it help to sort the messages of a given conversation in the same order it was presented on my client side (web app using directlineJS) ?

**Comment by EricDahlvang** [comment]
A timestamp should work for ordering, yes.  As long as your client is setting the timestamp field correctly.  

You could also use channeldata, and add whatever custom properties you wish.  Or, set a custom field to whatever you like when you persist the activity in IActivityLogger.LogAsync
