### ISSUE TITLE
[Node.js SDK, MS Teams] ERROR: ChatConnector: receive - no security token sent.

### ISSUE THREAD

**Issue by aseemrastogi** [Microsoft/BotBuilder#3939]
## Bot Info 
* App ID: 65e674a1-0102-4883-831e-ca3857bf0a10
* SDK Platform: Node JS 
* SDK Version: "botbuilder": "^3.11.0",
    "botbuilder-teams": "^0.1.7",
* Active Channels: Skype, MS Teams
* Deployment Environment: On a separate machine with SSL certificates

## Issue Description
My bot is published in MSFT Bot Framework. This is working great with Webchat & Skype For Business. I am trying to connect it in MS-Teams but I cannot see bot in any of the channels. Went to a channel --> Manage Team --> bot --> Create an outgoing WebHook. 

Now by using @BOT_NAME I can hit the backend bot server but get "no security token sent" error
Objective is to run this sample into Teams - 1 message roundtrip.

Actually, I have an additional bot related security token from my Admin. I have no idea how/where to use that.

## Code Example
Took MSFT sample code from git https://github.com/OfficeDev/BotBuilder-MicrosoftTeams.git

## Reproduction Steps
1. Take Code from https://github.com/OfficeDev/BotBuilder-MicrosoftTeams.git
2. Register Bot into dev.framework.com 
3. Add AppId, Pwd, TenantId variables into Node JS code

## Expected Behavior
Should have worked

## Actual Results
no security token sent.
Reference https://github.com/Microsoft/BotBuilder/issues/2434

**Comment by aseemrastogi** [comment]
Please dont put labels - Waiting For Answer
Because even after I provide answer, I cannot change the label and probably you guys think, user still needs to provide answers.

**Comment by cext001** [comment]
Facing the same issue. What am I doing wrong?

**Comment by derekshull** [comment]
Also receiving this error.

**Comment by daveta** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues


For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botbuilder-channels/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
