### ISSUE TITLE
[Adaptive Cards] Invalid column width: Auto and Stretch issue

### ISSUE THREAD

**Issue by yogiderek** [Microsoft/BotBuilder#3942]
SDK Platform: .NET
SDK Version: 3.12.2.4
Bot Emulator Version: 3.5.34
Adaptive Cards NuGet package version: v1.0.0-beta11
Deployment Environment: Not deployed yet

Issue Description

I have a columset with two columns. First column is an image and its width is set to auto and the second is text with its width set to stretch. In the bot emulator, there is a large space between the two columns which cannot be removed. I output my card as json to the VS output window and pasted the json into a window using the Adaptive Card Visualizer. 

The Adaptive Card Visualizer showed up the following errors which the Bot Emulator did not
Invalid column width: Auto
Invalid column width: Stretch

the c# code 

  AdaptiveColumn column1 = new AdaptiveColumn {
        Width = AdaptiveColumnWidth.Auto
  };

 produces the following json

  "type": "Column",
  "width": "Auto",

and 

  AdaptiveColumn column2 = new AdaptiveColumn {
        Width = AdaptiveColumnWidth.Stretch
  };

 produces the following json

  "type": "Column",
  "width": "Stretch",

You can see the Auto and Stretch in the json are capitalised and should be lowercase. If I change the json in the Visualizer to lower case I get the result I expected. However, if I change the c# to Width = "auto" and Width = "stretch" the widths in the json shown in the Details view in the emulator are both still capitalised.

Is this a bug or am I missing something

**Comment by JasonSowers** [comment]
@yogiderek Hello and thank you for reporting.  Since your issue is specific to adaptive cards and not the bot framework I would recommend posting an issue on the [Adaptive cards repo](https://github.com/Microsoft/AdaptiveCards/issues)  They should be able to better address your issue.
