### ISSUE TITLE
[Adaptive Cards] Delete message from context?

### ISSUE THREAD

**Issue by CalvinFengDatacom** [Microsoft/BotBuilder#3943]
Is there any way that I can remove/delete the posted messages from context? I can't find any function that can delete the message.

Expected Behavior
Once user click the button of adaptive card, I would like to remove the adaptive card. So, if I can remove the message, so I can remove the adaptive card.

**Comment by CalvinFengDatacom** [comment]
@nwhitmont  I would like to delete a message from context. Do you know how to delete a certain message I want? Adaptive Card is just an example, but if you have any idea of deleting a certain message, then I can use the same logic to delete adaptive card from the context

**Comment by EricDahlvang** [comment]
Hi @CalvinFengDatacom 

What do you mean by "delete message from context"?  Are you using the WebChat channel, and want to remove a message in the chat window after the user interacts with the Adaptive Card?  Removing messages is not a built in feature of WebChat.  You would need to fork the open source repository, and add support for this.  Here is the WebChat repo: https://github.com/Microsoft/BotFramework-WebChat

Let me know if you have any questions.

**Comment by CalvinFengDatacom** [comment]
Thanks @EricDahlvang

Your are right, I'm using WebChat channel for developing the bot ATM. I would like to remove a message in the chat window after user interacts with the adaptive card. This is my question, and I think you already give me the answer.

I will have a look the repository when I'm free.

**Comment by artus** [comment]
So, any progress on this? I'd like to know how @CalvinFengDatacom managed to fix this issue.
