### ISSUE TITLE
[Bot Service] ngrok testing - Endpoint missing and response GET instead of POST?

### ISSUE THREAD

**Issue by ishita-srivastava5** [Microsoft/BotBuilder#3944]
* App ID: 1962f2ff-5f21-4a34-94d0-53b8d7627bc5
* SDK Platform: Node.js
* SDK Version: 5.6.0
* Active Channels:  web chat,Direct Line
* Deployment Environment:  ngrok, Auzure Bot Service,

## Issue Description
I have created a new bot using the new azure bot service. There are two main problems:

Issue 1.  In my code I am doing post to  '/api/messages' and enabling my bot to listen to it. However it returns a get and thats why shows error code 404.

My code is:
router.post('/api/messages', bot.getConnector().listen());

HTTPS request result is:
GET           /api/messages          404 Not Found
OPTIONS  /api/messages          204 No Content

Issue 2.  The web chat channel shows the issue  "Activity dropped because the bot's endpoint is missing", however in the setting i have correctly placed my url in the messaging endpoint  as "https://42f5d4ba.ngrok.io/api/messages"

Steps:-
1. I created a new bot using Bot Channels Registration.

2. I started my project and started my server by ngrok. I was issued a url, https://42f5d4ba.ngrok.io

3. In the microsoft azure settings for my bot, in the messaging endpoint I pasted https://42f5d4ba.ngrok.io/api/messages and clicked save.

4. In microsoft azure in bot management I pressed Test in web chat. 

5. The bot does not show any messages so I checked the channels.  In the web chat channel the issue says "Activity dropped because the bot's endpoint is missing"

6. Also in the console I get HTTP request result
GET           /api/messages          404 Not Found
OPTIONS  /api/messages          204 No Content

I tested the bot on the emulator and it works because it treats POST as POST  but does not work while testing in azure because it treats POST as GET

**Comment by daveta** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues


For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botbuilder-channels/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
