### ISSUE TITLE
[Node.js SDK, Skype, Question] Dialog not called called upon button click?

### ISSUE THREAD

**Issue by jinot92** [Microsoft/BotBuilder#3945]
## Bot Info 
* SDK Platform: Node.js
* Active Channels: Skype
* Deployment Environment: Azure Bot Service

## Issue Description
I am trying to build a Notification bot, in which the notifications can be approved, rejected or can be scheduled to be reminded on a later date and time.
I am using a trigger function which on an event sends the initial notification to the bot.
When the '__askLaterTime's__' options are clicked the dialog which is supposed to be called is not called instantly, but when the option is clicked again the dialog starts.
I wish to send the remind later options to LUIS to get the proper date and time resolution.
I am bit stumped and hope that y'all can help.

## Code Example
```javascript
//Intent Recognizer
var LaterTimeIntent = new builder.IntentDialog({
    recognizers: [recognizer]
  })
  .matches('IntentName', (session, args) => {
    session.send('Will remind you ' + session.message.text)
    session.endDialog();
  });


bot.on('trigger', function(message) {
  // handle message from trigger function
  bot.beginDialog(message.address, "/ApproveRejectNotification", {
    data: message.value,
    address: message.value.address
  });
});


bot.dialog('/ApproveRejectNotification', [
  function(session, args) {
    var msg = new builder.Message().address(args.address)
      .textFormat(builder.TextFormat.markdown)
      .attachments([
        new builder.HeroCard()
        .title('Notification')
        .buttons([builder.CardAction.postBack(session, 'approved', 'Approve'), 
        builder.CardAction.postBack(session, 'rejected', 'Reject'), 
        builder.CardAction.postBack(session, 'remind_later' + , 'Remind Later')])
      ]);
    session.send(msg);
  }
]);

bot.dialog('/Approved', function(session, args, next) {
    //Send notification
  })
  .triggerAction({
    matches: /^approved/i,
  });

bot.dialog('/Reject', function(session, args, next) {
    //Send notification
  })
  .triggerAction({
    matches: /^rejected/i,
  });

bot.dialog('/GetLaterTime', LaterTimeIntent);

bot.dialog('/RemindLater', [
    function(session, args) {
      var askLaterTime = new builder.Message(session)
        .textFormat(builder.TextFormat.markdown)
        .text('Set reminder for : ')
        .attachments([
          new builder.HeroCard(session)
          .buttons([builder.CardAction.imBack(session, 'Tomorrow', 'Tomorrow'),
            builder.CardAction.imBack(session, 'Day after tomorrow', 'Day after tomorrow'),
            builder.CardAction.imBack(session, 'After 3 days', 'After 3 days')
          ])
        ]);
      builder.Prompts.text(session, askLaterTime)
    },
    function(session, result) {
      bot.beginDialog(session.message.address, '/GetLaterTime', result.response);
    }
  ])
  .triggerAction({
    matches: /^remind_later/i,
  });
```

## Expected Behavior
The __GetLaterTime__ to be called the very first time any of those buttons are clicked.

## Actual Results
"Tomorrow" has to be clicked twice for the  __GetLaterTime__ dialog to be called.

![notification](https://user-images.githubusercontent.com/26137758/34092595-3823b276-e3ea-11e7-8a1f-7b8bb80af59d.jpg)

**Comment by Robloblaw** [comment]
I'm experiencing a similar problem with having to post the button response twice after button prompts for the recognizer to pick it up - also where the button prompt is sat within a triggered dialog - has any solution or workaround been found to this @nwhitmont ?

**Comment by lijiarui** [comment]
Well, I got some problem similar like this too... About the **twice** response, I thought is because using two recognizer.

the fisrt one is:
```
bot = new builder.UniversalBot(connector)
bot.dialog('/', function (session, args) {
....
})
```

the second is :  
```
bot.dialog('/testPrompt', testPrompt);

const testPrompt = new builder.IntentDialog({recognizers: [recognizer]})
.matches('IntentName', (session, args) => {
.....
  })
```

So it has been called twice, but I have no idea how to fix this..... @nwhitmont

**Comment by fanidamj** [comment]
Can you please let us know if the issue still persists?

**Comment by daveta** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues


For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botbuilder-channels/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
