### ISSUE TITLE
[Question] How to publish app from Visual Studio IDE?

### ISSUE THREAD

**Issue by sahootanmay** [Microsoft/BotBuilder#3946]
i am using bot frmework and doing an example by watching the video from udemy and i am getting response in emulator correctly but when i am going to publish my app its not publishing

**Comment by FranciscoPonceGomez** [comment]
Hi @sahootanmay,

You can publish your bot by right clicking your solution and selecting "publish" from the menu. Then you need to select your deployments options and the site endpoint where your users will reach your bot. In addition to this, you need to register your bot in our dev portal (dev.botframework.com)

![image](https://user-images.githubusercontent.com/16775093/34133558-4cbb4864-e40a-11e7-8749-1cba73898716.png)
