### ISSUE TITLE
[Direct Line] Failed to send activity: bot timed out?

### ISSUE THREAD

**Issue by anandvardhandas** [Microsoft/BotBuilder#3947]
## Bot Info 
* App ID: 96f63185-ee3b-4efe-97d0-7733053ba795
* SDK Platform: .NET
* SDK Version: 3.9.0
* Active Channels: Direct Line
* Deployment Environment: Azure App Service

## Issue Description
I am facing the "Failed to send activity: bot timed out" intermittently.
504 error.
Sometimes it works, sometimes in between it gives me this error.
Till bot connector, message is reaching from webchat via directline.
At botconnector I am getting this message "There was an error sending this message to your bot: HTTP status code GatewayTimeout".

## Code Example
Cannot identify the code, as message itself is not reaching the api sometimes during the issue.

## Reproduction Steps
1.  Ping the api via directline
## Expected Behavior
Always reply

## Actual Results
Reponse in chrome browser Developer tool:
{
  "error": {
    "code": "BotError",
    "message": "Failed to send activity: bot timed out"
  },
  "httpStatusCode": 504
}

**Comment by JasonSowers** [comment]
The first thing I would try is upgrading to the latest version of the SDK.   I also see you have not yet migrated your bot.  Please migrate your bot and see if that helps as well.  How often is this happening? every message, 1 out of 5 messages, 1 out of 100, etc?  are you performing any long-running operations like api or database calls?  You can also see my answer [here](https://stackoverflow.com/questions/47697039/microsoft-bot-framework-very-high-response-times/47700484#47700484) for improving performance.

**Comment by JasonSowers** [comment]
Closing due to lack of response let me know if you need to reopen
