### ISSUE TITLE
[Question] There was an error sending this message to your bot: HTTP status code Unauthorized?

### ISSUE THREAD

**Issue by senthilcsk** [Microsoft/BotBuilder#3949]
## Bot Info 
* App ID: c6b91627-a308-47f6-ab1c-d7ba09ce74f3
* SDK Platform:  .NET
* SDK Version: VS 2015 (Framework 4.6)
* Active Channels: FaceBook
* Deployment Environment: Auzure Bot Service,Manual  

There was an error sending this message to your bot: HTTP status code Unauthorized

I got the error message like this

"There was an error sending this message to your bot: HTTP status code Unauthorized" 

I have validate App id and passwords from both sides. its same. updated the components through nuget too. as of now I'm using Microsoft.Bot.Builder- V3.12.2.4 . when i run my code in local emulator  its working fine at the same after deploy the same code my windows server[Windows server 2012]. i published my application like subdomain[https://abc.com/TTBotDemo/TTBot/]. I don't know the way to fix it. please anyone guide me to out of this.

**Comment by senthilcsk** [comment]
Hi guys any update of my issue. i'm struck up whole day.

**Comment by FranciscoPonceGomez** [comment]
Hi @senthilcsk,

I noticed that your bot hasn't been migrated yet. Please migrate your bot to benefit from the latest Auth features.
Let me know if the problem persists afterwards.

Regards,
Francisco

**Comment by senthilcsk** [comment]
Hi FranciscoPonceGomez,
Thanks for the update. Let me know is there any other way to run my bot temporarily.
