### ISSUE TITLE
Exception caused by data format different between preview & production LUIS API

### ISSUE THREAD

**Issue by zixia** [Microsoft/BotBuilder#395]
The json object that Preview API return, does not always contain the key `intents`.

So this line will throw exception when we use Preview API:
https://github.com/Microsoft/BotBuilder/blob/master/Node/src/dialogs/LuisDialog.ts#L66

# Detail:

## If I use **Production** API, the json object return is like
```javascript
{
  "query": "hi",
  "intents": [
    {
      "intent": "Greeting",
      "score": 0.6110722
    },
    {
      "intent": "None",
      "score": 0.451821864
    },
    {
      "intent": "BizPlan",
      "score": 0.000137667419
    }
  ],
  "entities": []
}
```

## If I use **Preview** API, it became like this:
```javascript
{
  "query": "hi",
  "topScoringIntent": {
    "intent": "Greeting",
    "score": 0.6110722
  },
  "entities": []
}
```

**Comment by Stevenic** [comment]
We haven't updated LuisDialog to support the preview API's yet. There are actually a number of issues. It's on our TODO list. But their schema is changing as well so it would be a little premature for us at this point.

**Comment by Johndgnzj** [comment]
i suggest you support two type result.
in my case , i define the class like below
```
public class EmilyBot
    {
        public string query { get; set; }
        public intents[] intents { get; set; }
        public topScoringIntent topScoringIntent { get; set; }
        public Entity[] entities { get; set; }
    }
```

**Comment by Stevenic** [comment]
We kind of have that. the `on('intent')` handers only match on the top intent but if you want to do all of the inten processing yourself you can simply use `onDefault()` which gets passed the raw list of intents. I already let you mix the two approaches as well. If the top intent doesn't have a handler or if things are below a threshold we call `onDefault()`

**Comment by v-thgratMSGit** [comment]
Closing this issue/suggestion due to age. Please reopen if needed. Thanks!
