### ISSUE TITLE
[Feature Request] BotAuthenticationHandler should respect IdentityOptions

### ISSUE THREAD

**Issue by Maarten88** [Microsoft/BotBuilder#3953]
## Bot Info
* SDK Platform: AspNetCore 2.0
* SDK Version: 3.12.2.4
* Active Channels: Direct Line
* Deployment Environment: Auzure Cloud Service

## Issue Description
Using the 

    [Authorize(Roles = "Bot")] 

attribute results in `HTTP status code Unauthorized` errors when using a non-default role claim identity setting.

## Code Example
I use IdentityServer4 as part of a project also containing a bot endpoint. IdentityServer resets the role claimtype from the default `ClaimTypes.Role` ("http://schemas.microsoft.com/ws/2008/06/identity/claims/role") to the Jwt standard `JwtClaimTypes.Role` ("role"), using code like this:

    services.AddIdentity<ApplicationUser, IdentityRole>(options => 
        options.ClaimsIdentity.RoleClaimType = JwtClaimTypes.Role);

BotAuthenticationHandler fails to pickup IdentityOptions using DI, and hardcodes ClaimTypes.Role when adding the Bot role to the claims principal, breaking the [Authorize Roles="Bot"] attribute to in my environment.

## Expected Behavior
I would expect this to just work. BotAuthenticationHandler should request IdentityOptions in its constructor and then use options.ClaimsIdentity.RoleClaimType instead of hardcoding ClaimTypes.Role when building the principal here: 
https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Microsoft.Bot.Connector.AspNetCore2/BotAuthenticationHandler.cs#L100

## Actual Results
Calls to the endpoint by the connector result in `HTTP status code Unauthorized`. I need to build a workaround using an access policy or less specific Authorize attribute on the endpoint.

**Comment by daveta** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
