### ISSUE TITLE
[Card Actions] HeroCard buttons not working on Facebook Messenger channel?

### ISSUE THREAD

**Issue by aleinnocenzi** [Microsoft/BotBuilder#3954]
## Bot Info 
* App ID: 7792dce2-616d-466e-a2d9-bcadcb22dde3
* SDK Platform: .NET
* SDK Version: 3.12.2.4
* Active Channels: WebChat, Facebook Messanger, Skype
* Deployment Environment: Azure Bot Service

## Issue Description
I am showing a carousel with 2 herocards with buttons. In skype everything works correctly, but when I click on the button into the Facebook Messanger channel, the bot doesn't give me a response. I am sure it's an issue of the button because if I send a message typing the same text of the button everything works.

**Comment by nwhitmont** [comment]
Hi @aleinnocenzi - Can you share your code that creates the hero card with buttons?

**Comment by msmohan** [comment]
@aleinnocenzi can you share please your code? I will try to repro and provide you with a solution.

**Comment by JasonSowers** [comment]
What `ActionType` are you using?

**Comment by JasonSowers** [comment]
Closing as no response from user

**Comment by jimmyhawkins** [comment]
Hi am having the same issue, am using HeroCard with ActionType = AmBack, please tell me which cards can I use on facebook messenger channel.

**Comment by AkshayKanchan** [comment]
Facing the same issue with heroCards (in carousel Layout) only for facebook channel.

Below is the code for creating a hero card.
`new builder.HeroCard(session)
            .title(striptags(truncate(data[product].title, 80)))
            .subtitle("Rs." + data[product].final_price + "")
            .text(entities.decodeHTML(striptags(truncate(data[product].details, 80))))
            .images([
                builder.CardImage.create(session, data[product].img),
            ])
            .buttons([
                builder.CardAction.openUrl(session, data[product].scandidUrl, "Buy Now")
            ])`

building message using carousel layout (as shown below).
`
new builder.Message()
            .attachmentLayout(builder.AttachmentLayout.carousel)
            .attachments(cards);
`
