### ISSUE TITLE
[Skype] Chatbot not working on Skype Channel

### ISSUE THREAD

**Issue by fms-santos** [Microsoft/BotBuilder#3959]
## Bot Info 
* App ID: 6cd7cd5b-47ad-40a8-a319-9dd7846977b7
* SDK Platform: Node.js
* SDK Version:  3.13.1
* Active Channels:  Skype, Webchat
* Deployment Environment:  Azure App Service

## Issue Description
Since this morning (20th Dec 2017), my Skype chatbot is not answering back on any dialog flow.
**The bot works fine on the Bot Emulator and also on the Azure Bot Service Test Channel.**
It was working fine on 18th Dec 2017.

Note: After discovering this issue I've migrated my chatbot as suggested by https://blog.botframework.com/2017/12/19/bot-state-service-will-soon-retired-march-31st-2018/ but it didn't work as a fix.

## Reproduction Steps
1. open Skype and talk to the chatbot
2. Chatbot doesn't reply back and there's no sendTyping() activity too.

## Expected Behavior
Chatbot should answer back as normally would like on the Test Channel:
![Expected Behavior](https://user-images.githubusercontent.com/16543301/34207314-dad2f34a-e581-11e7-9d4e-f63fa3bcff73.png)

## Actual Results
The chatbot contact doesn't refresh its name even after deleting and creating again the skype channel.
I've also tried to delete and readd the bot through:
![Skype Add Page](https://user-images.githubusercontent.com/16543301/34207468-7fb85ce2-e582-11e7-92d5-7af6af22aee2.png)

The printscreen above shows the anomally.
![Anomally](https://user-images.githubusercontent.com/16543301/34207415-3e5cc31e-e582-11e7-916d-c66b7b329814.png)

**Comment by konstlut** [comment]
I believe the issue should be fixed now. Thank you for reporting.

**Comment by fms-santos** [comment]
I can confirm that after restarting the webapp this issue is now fixed. Thanks @konstlut
