### ISSUE TITLE
Add Form fields based on external data

### ISSUE THREAD

**Issue by bsoulier** [Microsoft/BotBuilder#396]
Hello everyone,

I saw that in samples fields based on enum or attributes are feasible, how can we offer values in a parameter to be coming from another place (db...) based on user access?

Cheers, Ben

**Comment by willportnoy** [comment]
You might consider using JSON schema to define your form - see

http://docs.botframework.com/sdkreference/csharp/forms.html#jsonForms

**Comment by chrimc62** [comment]
You can also do it via the SetDefine method of off Field as described here: http://docs.botframework.com/sdkreference/csharp/forms.html#dynamicFields
