### ISSUE TITLE
[Direct Line] Error messages keep popping up once a while?

### ISSUE THREAD

**Issue by ubreddy** [Microsoft/BotBuilder#3960]
## Bot Info 
* SDK Platform: Node.js
* SDK Version: 3.11.0
* Active Channels: WebChat, Direct Ling
* Deployment Environment: Azure App Service

## Issue Description
Error: Request to 'https://directline.botframework.com/v3/conversations/D4lZgUWPngxI2VP8HNbess/activities/D4lZgUWPngxI2VP8HNbess%7C0000022' failed: [500] Internal Server Error
Error: Request to 'https://directline.botframework.com/v3/conversations/D4lZgUWPngxI2VP8HNbess/activities/D4lZgUWPngxI2VP8HNbess%7C0000016' failed: [500] Internal

## Code Example
Adaptive cards are used too.

## Expected Behavior
The above errors should not have occurred.
## Actual Results

as above.

**Comment by msmohan** [comment]
There has been transient performance issue this morning, Can you please try again and let us know if the issue still exist?

**Comment by achadha0111** [comment]
Different bot user, but this seems to be happening on one of my bots as well.
