### ISSUE TITLE
[WebChat] Change polling mode/interval

### ISSUE THREAD

**Issue by sreeharikm** [Microsoft/BotBuilder#3962]
## Bot Info 
* SDK Platform: .NET
* SDK Version: 3.5.5
* Active Channels: DirectLine
* Deployment Environment: Azure App Service

## Issue Description
We are using DirectLine with WebChat version is v10.6. To support instant updates at the client side and to retrieve the chat history, we are using polling mode (by passing webSocket=false in chat.html) with a polling interval of 1sec. But this is making the browser hung after some time. Is there a way to switch the mode to webSocket without reloading the chat.html? Or is there an option to change to polling frequency after some time (may be after loading the welcome message, change the frequency to 5sec)? Please share your thoughts.

Thanks
Sreehari

**Comment by sreeharikm** [comment]
Please share if you have any thoughts on this.

**Comment by JasonSowers** [comment]
This might be a better question to ask in the [webchat repo](https://github.com/Microsoft/BotFramework-WebChat/issues/new)

**Comment by JasonSowers** [comment]
Also, there is [this sample](https://github.com/Microsoft/BotBuilder-Samples/blob/master/CSharp/core-DirectLine/DirectLineClient/Program.cs) you can look it that should help.
