### ISSUE TITLE
[Question] How to allow users to give a reply in multiple messages before sending it to LUIS.

### ISSUE THREAD

**Issue by rafadorado** [Microsoft/BotBuilder#3964]
## Bot Info 
* App ID: c86200d2-b98b-412e-b599-00a17053eb7f
* SDK Platform: Node.js 
* SDK Version: 3.13.1 
* Active Channels: Web, Facebook, DirectLine
* Deployment Environment: Ngrok

## Issue Description

My users sometimes  write their questions/answers in multiple messages, not all in one message. Typical case is when the dictionary of the phone changes their answer. 

My idea was to delay processing their message ( in LUIS or Q&A ) until they stop writing so I know I have everything.

I only find the way of the bot sending a Typing event, but what about the other way around? Could we know if the user is typing? 

Is there anyway to allow this behavior?

Thanks

**Comment by JasonSowers** [comment]
There Is no way to know if a user is typing or not.  The Bot Framework does not have any control over the channels.  

In the past, I have seen people store messages in a list and send them after a timer has expired.  So when you receive a message in your bot you can start a timer if no message comes in and the timer expires send that message.  If another message comes in, store that message too and restart the timer.

**Comment by rafadorado** [comment]
Thanks for the answer @JasonSowers. I'll try with the timer.

**Comment by JasonSowers** [comment]
Good Luck @rafadorado!
