### ISSUE TITLE
Couldn't send Retry error in Webchat

### ISSUE THREAD

**Issue by neetgupta7** [Microsoft/BotBuilder#3965]
* SDK Platform:  .NET 
* SDK Version: 3.12
* Active Channels: Webchat, Cortana
* Deployment Environment: Azure App Service, other

Hello
We have a bot available on webchat and cortana. It has to perform multiple operations in the background by connecting to multiple systems. At times and randomlyuser on webchat see 'coudn't send retry'. Even then the message is delivered and i get back the response and can continue with my regular conversation. And this does not happen consistently. Any suggestions on what can be done to improve this behavior.

**Comment by msmohan** [comment]
@neetgupta7 can you  share the code in order to review and resolve the issue?

**Comment by JasonSowers** [comment]
Also please provide your app ID

**Comment by neetgupta7** [comment]
Used HostingEnvironment.QueueBackgroundWorkItem and made it work
