### ISSUE TITLE
[Skype]  Why is my SkypeBot in Review for so Long?

### ISSUE THREAD

**Issue by AlexeyTokarev** [Microsoft/BotBuilder#3966]
## Bot Info 
* App ID: 
* SDK Platform: 
* SDK Version: 
* Active Channels: 
* Deployment Environment: 

## Reproduction Steps
1.
2.
3.

**Comment by msmohan** [comment]
@AlexeyTokarev can you fill in the template provided here and what is your botd?

**Comment by JasonSowers** [comment]
Closing due to lack of response
