### ISSUE TITLE
[Question] dialog.begin() method does not pass results forward?

### ISSUE THREAD

**Issue by rjrahul** [Microsoft/BotBuilder#3968]
I would like to raise an issue where `Dialog.prototype.begin` method in Node.js `botbuilder` SDK does not pass the results to the `replyReceived()` method.

This means we cannot use the recognizer results when intent triggers a dialog, in case we pass the dialogId and register dialog separately with the bot.

For example, I register qnaRecognizer with IntentDialog and then use the intent.matches to trigger QnAMakerDialog. In that case qnaRecognizer would fire again as it would not have the result passed on and therefore would make next network call. It is inefficient.

**Comment by nwhitmont** [comment]
Hi @rjrahul Can you provide a code example that demonstrates this issue end-to-end? Thanks

**Comment by nwhitmont** [comment]
Hi @rjrahul - Are you still having issues?

**Comment by rjrahul** [comment]
Opening an issue in QnAMakerDialog as this should be handled in that service.
