### ISSUE TITLE
Problem generating password when configuring a channel.

### ISSUE THREAD

**Issue by khalidpal** [Microsoft/BotBuilder#3969]
## Bot Info 
* App ID: 7307467b-55b4-4fec-bd3e-69f9e834dfc1
* SDK Platform: .NET
* SDK Version: 3.12.2.4
* Active Channels: none-webchat
* Deployment Environment: ngrok, Azuree App Service

## Issue Description
Cannot create new password here;
https://apps.dev.microsoft.com/?referrer=https%3a%2f%2fportal.azure.com%2f#/application/7307467b-55b4-4fec-bd3e-69f9e834dfc1
## Reproduction Steps
goto;
https://apps.dev.microsoft.com/?referrer=https%3a%2f%2fportal.azure.com%2f#/application/7307467b-55b4-4fec-bd3e-69f9e834dfc1
in application secrets -> create new password
## Expected Behavior
new password to be created

## Actual Results
GraphExcepion thrown
![errorpw](https://user-images.githubusercontent.com/7362356/34335925-93756608-e974-11e7-9bfb-c4993da0f0f5.jpg)

**Comment by khalidpal** [comment]
This is not a temporary problem, experiencing since two days.

**Comment by areckkimo** [comment]
I have same promble

**Comment by FranciscoPonceGomez** [comment]
This is a known problem. We are currently working on a fix. I will keep you updated here.

Regards,
Francisco

**Comment by khalidpal** [comment]
Thanks!

**Comment by gabosdk** [comment]
I have the same issue since yesterdar

**Comment by gabosdk** [comment]
I have the same issue since yesterday

**Comment by gabosdk** [comment]
When this gonna be fixed, several days with the same issue.

**Comment by RubenRFM** [comment]
Somebody knows any time estimate when this will be solved? Thanks in advance

**Comment by EricDahlvang** [comment]
This will be fixed soon.  For now, you can retrieve the auto-generated password using the following method:

MicrosoftAppId and MicrosoftAppPassword can be found by navigating to the ResourceGroup for the Bot Registration, choosing “Deployments”, then the specific deployment for the bot.

![appidpassword](https://user-images.githubusercontent.com/11055362/34492674-9b58fc20-ef9d-11e7-91b9-466337b265c7.png)

**Comment by fanidamj** [comment]
Closing the issue assuming it as resolved. Please reopen a new issue if it still persists.
