### ISSUE TITLE
[Question/NodeJS] Start Waterfall Dialog from Bot 

### ISSUE THREAD

**Issue by deubaka** [Microsoft/BotBuilder#397]
I have a use case wherein, a 'DM' will be sent to the user via the REST API (/messages). Which upon receipt, it should start to ask a few questions (where the waterfall dialog comes in), 1-on-1. 

From what I've read on the docs, I haven't seen a way to 'bridge' them, given that the `session` object only comes from bot-received interactions.

Is there a way or is it at least in the backlogs of functionalities that will be done?

Thanks!

**Comment by Stevenic** [comment]
Are you saying you want your bot to initiate a new conversation with the user based upon some external event? We call those "proactive" messages and you can do them using `BotConnectorBot.beginDialog()` Look at the [basics-naturalLanguage](https://github.com/Microsoft/BotBuilder/tree/master/Node/examples/basics-naturalLanguage) example to see how this is done.

**Comment by deubaka** [comment]
Exactly, basically initiate a 1-on-1 conversation from Bot to User. I managed to 'DM' him, but couldn't find it to 'listen', and then start a new conversation.

Looking at the `BotConnectorBot.beginDialog`, I haven't come across it yet, but based on it, it would initiate a chat similar to the REST API. I'll have to check and test this out if what we are looking for, if it is, then thank god! :)

**Comment by v-thgratMSGit** [comment]
Closing this issue. Thanks!
