### ISSUE TITLE
Unable to Access Bot by others in my facebook page

### ISSUE THREAD

**Issue by Ptstset132** [Microsoft/BotBuilder#3971]
Hi i have made a facebook messenger bot successfully but problem is it only replied me not others on my page. are there any permissions to setup for messenger bot to  public?

**Comment by chathudev** [comment]
Until an app is published, it is in Development Mode. It will only work for admins, developers, and testers. You will have to submit your app for review by facebook.

Checkout the MSFT doc [https://docs.microsoft.com/en-us/bot-framework/bot-service-channel-connect-facebook](here)

And Facebook doc [https://docs.microsoft.com/en-us/bot-framework/bot-service-channel-connect-facebook](here)

**Comment by Ptstset132** [comment]
there is any option to implement javascript in messenger
