### ISSUE TITLE
[FB Messenger] How to POST payload back from FB webview to bot using webhook postback event?

### ISSUE THREAD

**Issue by somak12** [Microsoft/BotBuilder#3972]
## Bot Info 
* SDK Platform: .NET
* SDK Version: 3.5.5
* Active Channels: Facebook
* Deployment Environment: Azure App Service

## Issue Description
Hi, I am trying to use the webview feature of Facebook messenger platform in botframework. Rendering of the webview is working fine. The problem I am facing right now is to POST the payload from the webview back to the chat. 

It seems that exposing an API form the botframework app is one way to do that, but somehow if we can use the webhook to trigger a postback event back to the bot with the JSON payload from the webview would be a better way to do that. 

Is there any way to invoke the webhook URL (https://facebook.botframework.com/api/v1/bots/[BotName]) from the webview. I can run GET against the URL but POST needs some kind of authentication. Can you help me to invoke the POST event for postback to the webhook? Or is there any other better way to achieve this?

**Comment by somak12** [comment]
Hi. Any update on this one?

**Comment by jahangircsebuet** [comment]
please have a look on the following link:
https://stackoverflow.com/questions/45923927/send-message-back-from-facebook-webview-to-bot?noredirect=1&lq=1
