### ISSUE TITLE
[State Service] InMemoryDataStore Throwing "Inconsistent SaveAsync based on ETag!"

### ISSUE THREAD

**Issue by ederbond** [Microsoft/BotBuilder#3973]
## Bot Info 
* App ID: 0b0170f6-6a74-44a8-889d-2faa73ca62bb
* SDK Platform: .NET 
* SDK Version: "Microsoft.Bot.Builder" version="3.12.2.4"
* Active Channels: Direct Line
* Deployment Environment: ngrok + local IIS hosted in Brazil

## Issue Description
While simulating 4 clients (directlineJS) calling my bot simultaneously I've receiving the message "_Sorry, my bot code is having an issue._" very frequently. 
After enabling Elmah logger on my bot, I've find out that this erro message is getting sent to my client because of an error on the default implementation on the `Microsoft.Bot.Builder.Dialogs.Internals.InMemoryDataStore` class as you can see on the image below:

![image](https://user-images.githubusercontent.com/12549812/34383862-8963540e-eaff-11e7-86db-9c54aec55b51.png)

## Code Example
Here is how I'm registering the InMemoryDataStore class on autofac:

```csharp
builder.Register(c => new CachingBotDataStore(new InMemoryDataStore(), CachingBotDataStoreConsistencyPolicy.ETagBasedConsistency))
                       .As<IBotDataStore<BotData>>()
                       .AsSelf()
                       .SingleInstance();
```

## Reproduction Steps
1. Create a simple bot and configure it to user the InMemoryDataStore
2.With 4+ clients opened (I'm using DirectlineJS) start making simultaneous calls to your bot
3. after a few messages sent to you bot the errar will occur.

## Expected Behavior
I was expecting to save the bot state data in memory without having this concurrency issue.

## Actual Results
![image](https://user-images.githubusercontent.com/12549812/34383948-0fdfe18c-eb00-11e7-91d5-648432540ea2.png)

**Comment by ederbond** [comment]
@EricDahlvang is this class deprecated and should not be used ? Or possibly a bug ?

**Comment by ederbond** [comment]
After changing the `CachingBotDataStoreConsistencyPolicy` from ETagBasedConsistency to LastWriteWins the error disapeared, but so far I don't know how the ETagBasedConsitency works...

**Comment by EricDahlvang** [comment]
Hi @ederbond 

This is by design.  With ETagBasedConsistency, writes that overlap will throw an exception.  The code for this can be found here: https://github.com/Microsoft/BotBuilder/blob/db2b8f860a3d8f7744a378930f93c4b0baa97978/CSharp/Library/Microsoft.Bot.Builder/ConnectorEx/BotData.cs#L143  

In most bots, LastWriteWins is a valid option.  If your bot is concerned with ensuring nothing in bot state is overwritten, then use ETagBasedConsistency and write code to handle the PreconditionFailed exception accordingly.

**Comment by ederbond** [comment]
Ok, Thanks @EricDahlvang.
