### ISSUE TITLE
Bot not responding

### ISSUE THREAD

**Issue by mukeshzt** [Microsoft/BotBuilder#3975]
## Bot Info 
* App ID: c1dac1a5-a887-4650-8373-f32a3d6bd6ed
* SDK Platform: Node.js
* SDK Version: 
* Active Channels: Skype
* Deployment Environment: Other

## Issue Description
Bot working well on the local using emulator once I deployed on I tried with Skype channel it's not working, previously it was working on skype channel. Not showing the welcome message and the signed card.

## Reproduction Steps
1.
2.
3.

## Expected Behavior

Should display the welcome message and then sign a card to show singin button. 

## Actual Results

not responding when I started the conversation on skype channel

**Comment by JasonSowers** [comment]
@mukeshzt I just tested your bot in webchat and got this error:
![image](https://user-images.githubusercontent.com/6301037/34417380-098e2980-ebad-11e7-960a-a193d5c59217.png)
  
Are you able to share your code?  How and where is your bot deployed?  I also see you haven't migrated your bot yet.  Please try migrating and see if that helps too.

**Comment by mukeshzt** [comment]
@JasonSowers Thanks for your feedback. Issue resolved. 
I will migrate bot as well.
Thanks
