### ISSUE TITLE
[Node.js SDK, Dialogs] builder.Prompts.choice and Waterfall dialog not waiting for user input?

### ISSUE THREAD

**Issue by SDCA19** [Microsoft/BotBuilder#3976]
## Bot Info 
* SDK Platform: Node.js
* SDK Version: 3.13.1
* Active Channels: Emulator

## Issue Description
builder.Prompts.choice not waiting for user input

## Code Example
```
bot.dialog('/',[
    function (session){
        session.beginDialog('qna');
    },
    function (session,results){
        ........
        session.beginDialog('feedback');
    },
    function (session,results){
        console.log(results.response.entity);
        session.endDialog('Thank you!');
 }
]);

bot.dialog('feedback',[
    function (session){
        builder.Prompts.choice(session, "Was this helpful?","Yes|No",{listStyle:3});
    },
    function (session, results) {
        session.endDialogWithResult(results);
    }
]);
```

## Expected Behavior
As per the documentation: https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-dialog-manage-conversation-flow

The prompt should wait until the user selects an option

## Actual Results
But in my case it returns back to the original waterfall and prints "Thank you!" without taking any user input.

I would appreciate any inputs on the issue! Thanks

**Comment by nwhitmont** [comment]
You are calling `session.endDialogWithResults()` before you do anything with the prompt result, so what you described is expected behavior. 

The result of the prompt choice needs to be handled in the same dialog as the prompt is called from. Eg. in the next waterfall step of the "feedback" dialog, not in the "/" main dialog.

Example:
```js

bot.dialog('/',[
    function (session){
        session.beginDialog('qna');
    },
    function (session,results){
        ........
        session.beginDialog('feedback');
    },
    function (session,results){
        // you can't handle the choice prompt from the 'feedback' dialog here, instead...
        // console.log(results.response.entity); // move this line into the second step of 'feedback' dialog
        session.endDialog('Thank you!');
 }
]);

bot.dialog('feedback',[
    function (session){
        builder.Prompts.choice(session, "Was this helpful?","Yes|No",{listStyle:3});
    },
    function (session, results) {
        //session.endDialogWithResult(results); // remove this line

       // handle the choice prompt results here
      console.log(results.response.entity);

      // it's not necessary to call session.endDialog() since it will redirect back to "/" main dialog anyway
    }
]);
```

**Comment by SDCA19** [comment]
@nwhitmont Thank you for your response..

If I do that, then I get the prompt twice.. The first prompt seems to do nothing whereas the second prompt works as expected..(I was facing this issue earlier as well but just didn't mention..Don't know why!).. Nonetheless, screenshots below:

![image](https://user-images.githubusercontent.com/31275908/34460343-5071b214-ee31-11e7-9f5e-390588b184a5.png)


![image](https://user-images.githubusercontent.com/31275908/34460332-16b122a8-ee31-11e7-8928-1dbf2827381c.png)

**Comment by nwhitmont** [comment]
What's happening in your `dialog('qna')`?  I would need to see the complete bot code (all lines, all files) to troubleshoot this issue further.  It might have something to do with redirecting back and forth between the different dialogs, but hard to say without seeing the complete code. 

One way to isolate the problem would be to move your "yes/no" prompt into the 'qna' dialog so everything is in a single dialog handler.

**Comment by SDCA19** [comment]
@nwhitmont - My apologies for the delay in response.. Was caught up with a few things..
Please find below a minimal code that replicates the issue. In the current code, the prompt doesn't wait for the feedback from the user..

Look forward to some help in figuring this out.. Thanks

```
var restify = require('restify');
var builder = require('botbuilder');
var builder_cognitiveservices = require("botbuilder-cognitiveservices");

// Setup Restify Server
var server = restify.createServer();
server.listen(process.env.port || process.env.PORT || 3978, function () {
   console.log('%s listening to %s', server.name, server.url); 
});
  
// Create chat connector for communicating with the Bot Framework Service
var connector = new builder.ChatConnector();

// Listen for messages from users 
server.post('/api/messages', connector.listen());

var inMemoryStorage = new builder.MemoryBotStorage();
// Create bot with a function to receive messages from the user
var bot = new builder.UniversalBot(connector).set('storage', inMemoryStorage);

var recognizer = new builder_cognitiveservices.QnAMakerRecognizer({
                knowledgeBaseId: '***************************************', 
    subscriptionKey: '*****************************************'
    });

var basicQnAMakerDialog = new builder_cognitiveservices.QnAMakerDialog({
    recognizers: [recognizer],
                defaultMessage: 'Sorry! Please rephrase the question!',
                qnaThreshold: 0.1
});

// Override to also include the knowledgebase question with the answer
basicQnAMakerDialog.respondFromQnAMakerResult = function(session, qnaMakerResult){
    var result = qnaMakerResult;
    var response = result.answers[0].questions[0] + '  \r\n' + result.answers[0].answer;
    session.send(response);
    session.endDialogWithResult(result);
}

bot.dialog('/',[
    function (session){
        session.beginDialog('qna');
    },
    function (session,results){
        //...
        session.dialogData.KB_Q = results.answers[0].questions[0];
        session.dialogData.KB_A = results.answers[0].answer;
        //...
        session.beginDialog('feedback');
    },
    function (session,results){
        session.dialogData.feedback = results.response.entity;
        session.endDialog('Thank you!');
    }
]);

bot.dialog('qna',basicQnAMakerDialog);

bot.dialog('feedback',[
    function (session){
        builder.Prompts.choice(session, "Was this helpful?","Yes|No",{listStyle:3});
    },
    function (session, results) {
        console.log(results.response.entity);
        session.endDialogWithResult(results);
    }
]);
```
Screenshot:

![image](https://user-images.githubusercontent.com/31275908/34763588-bc5c754e-f611-11e7-8dbc-9a58bbcf7aee.png)

**Comment by fanidamj** [comment]
Can you please let us know if the issue still persists?

**Comment by SDCA19** [comment]
I didn’t follow up after that.
