### ISSUE TITLE
demo-facebook example does not show message extra information

### ISSUE THREAD

**Issue by mulyoved** [Microsoft/BotBuilder#398]
Just configured and connected the demo-facebook, normal text seem to work, extended information like images seem to be ignore.

![6-1-2016 7-18-31 pm](https://cloud.githubusercontent.com/assets/2309907/15717295/0519b4ac-282f-11e6-9f75-35da8a565678.png)

**Comment by mulyoved** [comment]
Using node
Notice Bot say **Access Denied**

**Comment by mulyoved** [comment]
Forgot to set BOTFRAMEWORK_APPID and BOTFRAMEWORK_APPSECRET
https://github.com/Microsoft/BotBuilder/pull/401

**Comment by Stevenic** [comment]
Yep... Thanks for updating the comment. I also just checked in a simplification to the carousel example.
