### ISSUE TITLE
[Skype for Business] SfB client does not receive message, when Message is sent from bot to SfB client, if SfB client window is minimized, or not in Right-Down corner of screen, or has multiple conversation added in SfB client.

### ISSUE THREAD

**Issue by ganesh1190** [Microsoft/BotBuilder#3982]
## Bot Info
* SDK Platform: Node.js
* botbuilder Version: 3.8.4
* Active Channels: Skype for Business
* Deployment Environment: Azure Bot Service, Azure App Service

## Issue Description
We have created a bot for Skype for Business to start conversation with SFB clients.  In our case,  when conversation is initiated from bot using following code, SFB client does not receive the message from bot if  - 
user has minimized SFB window, 
OR
if SFB client window is not near right-lower corner of the screen.
OR
If  then only it is able to receive the message from bot.
OR
if user has multiple conversation added in the SFB client, 

SFB client receives the message from Bot if -
User has it SFB window in right -Down corner of the screen, and it has only one coversation (i.e Conversation with Bot) in the SFB client window.

## Code Example
var restify = require('restify');
var builder = require('botbuilder');

var server = restify.createServer();
server.listen(process.env.port || process.env.PORT || 3978, function () {
   console.log('%s listening to %s', server.name, server.url); 
});
  
// Create chat connector for communicating with the Bot Framework Service
var connector = new builder.ChatConnector({
    appId: //GUID,
    appPassword: password,
    stateEndpoint: process.env.BotStateEndpoint,
    openIdMetadata: process.env.BotOpenIdMetadata 
});

// Listen for messages from users 
server.post('/api/messages', connector.listen());

var inMemoryStorage = new builder.MemoryBotStorage();

// Create your bot with a function to receive messages from the user
var bot = new builder.UniversalBot(connector)
                    .set('storage', inMemoryStorage);

let addr1 =
{
    channelId: 'skypeforbusiness',
    user: {
        id: 'sip:xyz@abcd.com'
    },
    channelData: {
        tenant: {
            id: //GUID
        }
    },
    bot:
    {
        id: 'sip:botid@abcd.com',
        name: 'BotName'
    },
    serviceUrl: 'https://api.skypeforbusiness.com/platformservice/botframework/'
};

bot.loadSession(addr1, function (err, session) {
    session.send('hi00');
});

bot.dialog('/', intents);

## Reproduction Steps
1.  Minimize the SFB client window.
2.  Start bot to initiate the conversation  , and send the message to SFB client .
          OR
1. Add another conversation to SFB client (with another contact except BOT). 
2.  Start bot and initiate the conversation from bot to send the message to SFB client.

**In our case we stat debugging in VSCode and attaching debugger to NGRok )**

## Expected Behavior
When Bot is started , SFB client must receive message sent from the bot, whether client window in minimized, or it has multiple conversation adde , or SFB client window it is anywhere on the screen .

## Actual Results
When message is sent from the Bot, if SFB client window is not in Right-Down corner of screen,or if user has multiple conversation in SFB client window,  It does not receive the message from Bot.

error messages. -->
There are no error messages seen while running the bot.

**Comment by rohankulkarni21** [comment]
I am facing the same issue and not able to make my bot live on production. This is making a heavy impact on my product. Guys, can you please resolve this?

**Comment by ganesh1190** [comment]
Any updates on this? Surprised to see no comments.  Guys this is very high priority for us to get it fixed. Please resolve this issue.

**Comment by sgellock** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
