### ISSUE TITLE
[.Net SDK, Skype, bug] If bot is removed from Skype contact list, bot receives contactRelationUpdate activity with 'remove' action property twice?

### ISSUE THREAD

**Issue by jelenasol** [Microsoft/BotBuilder#3983]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.12
* Active Channels: Skype
* Deployment Environment: Auzure Bot Service, Azure App Service

## Issue Description
If bot is removed from Skype contact list, bot receives contactRelationUpdate activity with 'remove' action property twice for the same Skype contact.

## Code Example
-

## Reproduction Steps
1. Add bot to Skype contact list.
2. Remove bot from Skype contact list.

## Expected Behavior
Bot receives only one contactRelationUpdate activity with 'remove' action.

## Actual Results
Bot receives contactRelationUpdate activity with 'remove' action twice for the same contact. If bot is added back to contact list, then bot receives only one contactRelationUpdate  with 'add' action. The problem is only when bot is removed from contact list, i.e. with 'remove' action.

**Comment by fanidamj** [comment]
Closing the issue assuming it as resolved. Please reopen a new issue if it still persists.
