### ISSUE TITLE
[Node.js SDK, FB Messenger] Bad Request when Facebook reviews my bot submission

### ISSUE THREAD

**Issue by arthurbosquette** [Microsoft/BotBuilder#3985]
## Bot Info
* SDK Platform: Node.js
* SDK Version: 3.13
* Active Channels: Facebook
* Deployment Environment: Amazon Instance on Heroku

## Issue Description
When Facebook employees review my bot, they seem to get the following error : 

> 2018-01-02T20:41:40.477456+00:00 heroku[router]: at=info method=POST path="/api/messages" host=... request_id=... fwd="..." dyno=web.1 connect=1ms service=6ms status=202 bytes=100 protocol=https
> 2018-01-02T20:41:42.220193+00:00 app[web.1]: Error: POST to 'https://facebook.botframework.com/v3/conversations/.../activities/...' failed: [400] Bad Request
> 2018-01-02T20:41:42.220244+00:00 app[web.1]:     at Request.self.callback (/app/node_modules/request/request.js:186:22)
> 2018-01-02T20:41:42.220245+00:00 app[web.1]:     at emitTwo (events.js:106:13)
> 2018-01-02T20:41:42.220246+00:00 app[web.1]:     at Request.emit (events.js:191:7)
> 2018-01-02T20:41:42.220247+00:00 app[web.1]:     at Request.<anonymous> (/app/node_modules/request/request.js:1163:10)
> 2018-01-02T20:41:42.220248+00:00 app[web.1]:     at emitOne (events.js:96:13)
> 2018-01-02T20:41:42.220248+00:00 app[web.1]:     at Request.emit (events.js:188:7)
> 2018-01-02T20:41:42.220249+00:00 app[web.1]:     at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1085:12)
> 2018-01-02T20:41:42.220250+00:00 app[web.1]:     at IncomingMessage.g (events.js:291:16)
> 2018-01-02T20:41:42.220250+00:00 app[web.1]:     at emitNone (events.js:91:20)

No other log is prompted.

However, when I or other developers test the bot, everything seems to work just fine.

Where could this error come from ?

Many thanks

**Comment by fanidamj** [comment]
Can you please let us know if the issue still persists?
