### ISSUE TITLE
[FB Messenger] Callback URL generated by Azure gives 404?

### ISSUE THREAD

**Issue by mefree98** [Microsoft/BotBuilder#3986]
## Bot Info
* SDK Platform: .NET 
* Active Channels: Skype, Skype for Business, MS Teams, SMS, Email, Facebook Messenger, Direct Line
* Deployment Environment: Auzure Bot Service on Azure

## Issue Description
I have created a bot that I host in Azure and works fine for all the other channels I have enabled, including SFB, consumer skype, email, SMS, Teams, etc. The only channel I can't complete is the Facebook Messenger channel as the callback URL generated by Azure does not work. I get a 404 error, which is what Facebook also responds back with and doesn't let me proceed. I've tried disabling and re-enabling which has no effect and the URL doesn't change. Please help me figure out how to get the URL working.
https://facebook.botframework.com/api/v1/bots/TrinityBP
Thanks! 

## Code Example
Channel issue, not code/bot issue.

## Reproduction Steps
1.  Attempting to enable Facebook channel, Callback URL provided by Azure gives 404.

## Actual Results
Page gives a 404

**Comment by emanueleleoni** [comment]
I have got the same error. Since yesterday my callbackurl return error 404

**Comment by emanueleleoni** [comment]
@mefree98 Have you solve the error?

**Comment by mefree98** [comment]
It just started working one day.  I'll check to see if it is still working, but I didn't do anything to fix it.

**Comment by EricDahlvang** [comment]
@mefree98 @emanueleleoni 

You may have been experiencing this issue: https://github.com/Microsoft/BotBuilder/issues/4432  The underlying Azure AAD problem has been resolved.  Please follow along there for updates.

**Comment by emanueleleoni** [comment]
@EricDahlvang You're right!
Now It works again.
Thank you

**Comment by LivioGama** [comment]
Look like the problem is back, same on my bot

**Comment by EricDahlvang** [comment]
@LivioGama The team does not actively monitor closed issues.  If you are experiencing a similar problem, please open a new issue.
