### ISSUE TITLE
[Bot Migration] Not able to migrate existing bot?

### ISSUE THREAD

**Issue by mukeshzt** [Microsoft/BotBuilder#3988]
## Bot Info
* SDK Platform: Node.js
* Node.js Version:  node v6.9.1, npm  v3.10.8
* Active Channels: Skype, Slack, facebook 
* Deployment Environment:  Other (nginx - LINUX - Ubuntu 14.04.5 )

## Issue Description 
I have two bots [Bot Framework Portal](https://dev.botframework.com/bots). Now I would like to migrate existing bot. Once I click on the migrate button next to my development Bot then it showing me an error. 
called in pop up. 
"An error occurred
Failed to find any Azure subscriptions for the current user."

I followed steps to migrate 
1. [Migrate Bot](https://docs.microsoft.com/en-us/Bot-Framework/bot-service-migrate-bot)
2. Azure Functions Pack to package the Node.js using.
3. Click on the migrate button next to the My bots. 
4. Showing error as above.  
![migrateerorr](https://user-images.githubusercontent.com/23474222/34509557-27c460fe-f071-11e7-9770-307a5c1d156b.png)

How can I fix this?
Do I need to follow the 
[Bot Service](https://docs.microsoft.com/en-us/Bot-Framework/bot-service-quickstart)
[Register Bot Service](https://docs.microsoft.com/en-us/Bot-Framework/bot-service-quickstart-registration)

Above two are for creating new service but how do I merge the existing bot?

**Comment by nwhitmont** [comment]
Hi @mukeshzt - If you have a bot registration created via the Bot Developer Portal at https://dev.botframework.com - then you can migrate it to the new Azure product called "Bot Channels Registration" -- this requires an Azure account/subscription.  The email account connected to your Azure account must be an admin/owner of the bot for the migration to succeed. 

Let me know if you have additional questions.

**Comment by mukeshzt** [comment]
@nwhitmont thanks your comment helps me, and my account has some issue with the subscription but the support guys help me around and it's solved. I'm Closing this issue.

**Comment by wtam** [comment]
I've the same issue and issue open almost over a month and still not yet solved.  What do you meant your subscription has issue?  How do I know mine has problem, I'm still able to use it for other service creation
