### ISSUE TITLE
[LUIS] How to recognize an address(geography) in other languages?

### ISSUE THREAD

**Issue by victorgarciaesgi** [Microsoft/BotBuilder#3992]
## Bot Info
* SDK Platform:  Node.js 
* Deployment Environment: Heroku

## Issue Description

How can LUIS recognize an address? I've seen that geography prebuilt entity will be deprecated but it was only available in English (I'm doing a French bot). 

For the context I'm doing a google maps chatbot where you can ask questions like "estimated time to travel from paris to madrid".

Right now it only works with cities name or places 
But not with adresses like: "take me to 9 Fosh avenue Paris"
Is it possible to add a regex recognizer to the entities?

[Link to repo](https://github.com/victorgarciaesgi/chatbot-ETA/blob/master/dialogs/SearchTime.ts)

Thanks

**Comment by nwhitmont** [comment]
Hi @victorgarciaesgi - Have you checked out the Bing Location for Bot Framework package?

>The Bing location control for Microsoft Bot Framework makes the process of collecting and validating the user's desired location in a conversation easy and reliable. The control is available for C# and Node.js and works consistently across all channels supported by Bot Framework.

You can find more info here: https://github.com/Microsoft/BotBuilder-Location

**Comment by fanidamj** [comment]
Closing the issue assuming it as resolved. Please reopen a new issue if it still persists.
