### ISSUE TITLE
[Question] Does activity.from.id change for different channels for a same login?

### ISSUE THREAD

**Issue by neetgupta7** [Microsoft/BotBuilder#3996]
## Bot Info
* SDK Platform:  .NET
* SDK Version: 3.12
* Active Channels: Webchat, Cortana
* Deployment Environment: Azure App Service

## Issue Description
Hi
What I know is that channels like Teams, Cortana, Skype do not share the user id (logged in email id) of the person talking to the bot. It shares some information in Activity.From.Id. Can you please tell me if this information would remain the same for this login for that bot and would not change in future or be resued for some other user talking to the bot. e.g. If i m logged in as abc@outlook.com and my activity.From.Id is 46383jhfmkflf74940fnjfnmfne35748945  then it will remain the same forever for my future conversation irrespective of the device i m connected from. And also that this id will not be used for any other user in future.

**Comment by JasonSowers** [comment]
Are you asking if `Activity.From.Id`  will be the same across channel and across devices? Or on the same channel across devices?  Do you have some sort of login mechanism for your webchat version of the bot?

Across channels I know this can change specifically with Skype. Skype adds a "SIP" in front of the Id.

**Comment by neetgupta7** [comment]
@JasonSowers I mean Activity.From.Id on the same channel for the same user across device especially those which support login e.g. Cortana. I have also observed user id getting changed for skype but not sure about other channels supporting logins.

**Comment by EricDahlvang** [comment]
Hi @neetgupta7 

Short answer: ids are specific to the channel, and the rules for the ids are determined by the channel

Long answer: This page explains ids in the Bot Framework: https://docs.microsoft.com/en-us/bot-framework/bot-service-resources-identifiers-guide  Specifically, the **Channel Account** section:

> The relationship between channel accounts and users (actual people) depends on conventions associated with each channel. For example, an SMS number typically refers to one person for a period of time, after which the number may be transferred to someone else. Conversely, a Facebook account typically refers to one person in perpetuity, although it is not uncommon for two people to share a Facebook account.
> 
> In most channels, it's appropriate to think of a channel account as a kind of mailbox where messages can be delivered. It's typical for most channels to allow multiple address to map to a single mailbox; for example, "jdoe@contoso.com" and "john.doe@service.contoso.com" may resolve to the same inbox. Some channels go a step further and alter the account's address based on which bot is accessing it; for example, both Skype and Facebook alter user IDs so every bot has a different address for sending and receiving messages.
> 
> While it's possible in some cases to establish equivalency between addresses, establishing equivalency between mailboxes and equivalency between people requires knowledge of the conventions within the channel, and is in many cases not possible.
> 
> A bot is informed of its channel account address via the recipient field on activities sent to the bot.
> 
> Rules for channel accounts:
> 
> - Channel accounts have meaning only within their associated channel.
> 
> - More than one ID may resolve to the same account.
> 
> - Ordinal comparison may be used to establish that two IDs are the same.
> 
> - There is generally no comparison that can be used to identify whether two different IDs resolve to the same account, bot or person.
> 
> - The stability of associations between IDs, accounts, mailboxes, and people depends on the channel.

**Comment by neetgupta7** [comment]
Thanks @EricDahlvang for the article. So my activity.from.id lets say in cortana channel will be assigned to only one user abc@xyz.com and not to any other user. Also abc@xyz.com may get a new activity.from.id in future but will not be resued for any other user in that channel.
