### ISSUE TITLE
[Direct Line] Getting 400 Error on sending message to bot?

### ISSUE THREAD

**Issue by SamirMatkar** [Microsoft/BotBuilder#3997]
## Bot Info
* SDK Platform:  .NET 
* SDK Version:  3.10
* Active Channels: Direct Line
* Deployment Environment:  Fiddler

## Issue Description
Direct Line API 3 -  Error on sending message to

## Code Example
You sent HELLO which was 5 characters

## Reproduction Steps
1 I am using fiddler to check .

## Actual Results
```json
{
  "error": {
    "code": "BotError",
    "message": "Failed to send activity: bot returned an error"
  },
  "httpStatusCode": 400
}
```

**Comment by EricDahlvang** [comment]
@SamirMatkar Please upgrade to the latest sdk, and try again.  We will need more information in order to assist you, if this doesn't work.  Please provide the code you've used to send the message to the bot.

**Comment by SamirMatkar** [comment]
Thanks for your reply

I am using Bot Builder version 3.12.2.4. and Bot Emulator version  3.5.35
The most funny part it works with Emulator with localhost endpoint. but when using the endpoint of ngrok generate the post message with activities does not work.

I have am using the sample bot from MS  which return the message with length of activity text.

Let me know what code exactly you are looking .

**Comment by EricDahlvang** [comment]
@SamirMatkar How are you setting up ngrok?  Are you changing the Messaging Endpoint in the bot's settings on Azure?

**Comment by SamirMatkar** [comment]
yes, I configure the setting on botnetframework portal like this https://9f961bce.ngrok.io/api/messages

but the issue if i tried the using the ngrok end point with emulator it does not work.

can you explain little bit more on your comment of second point.

**Comment by EricDahlvang** [comment]
Are there any errors in the emulator's log window?  What doesn't work?

Are you using a cmd like this, to start ngrok:
ngrok http 3979 -host-header="localhost:3979"

**Comment by SamirMatkar** [comment]
Hello Eric,

i am able to run the bot locally/ from emulator using the ngrok .

But that is not my goal .Let me explain the case what i trying to achieve.

The Bot deployment is done locally. if i want to use my client application using the DirectLineChannel is that possible. ? if yes How ?

**Comment by EricDahlvang** [comment]
The Direct Line is a channel, like Facebook/Skype/MSTeams/etc.  When using the Direct Line channel, calls are made to the Direct Line connector from a client, then the direct line connector calls your bot.  When the bot responds, a call is made back to the Direct Line connector again.  The Emulator provides this functionality locally, for the sake of developement (it "emulates" a channel).  The emulator uses the WebChat control internally, and the WebChat control uses the DirectLineJs library:

https://github.com/Microsoft/BotFramework-Emulator
https://github.com/Microsoft/BotFramework-WebChat
https://github.com/Microsoft/BotFramework-DirectLineJS/

There are also some "offline" strategies the community has put together such as: https://www.npmjs.com/package/offline-directline However, this package has some limits:

> NOTE: Not all routes (e.g. attachments) are fully implemented in this package. For now this connector functions as a message broker and state store. Further, this package currently facilitates a single conversation between a user and a bot.

I recommend the path with the most features and reliability is a bot hosted on Azure, using the Bot Services Azure provides (including the Direct Line channel).
