### ISSUE TITLE
[Question] Creating a custom IConnector in order to bypass Microsoft servers?

### ISSUE THREAD

**Issue by Xzya** [Microsoft/BotBuilder#3998]
Hello,

Is there a way to use the framework without connecting to Microsoft at all?

I want to use the framework because it makes development easier, and also you can reuse the code for multiple platforms (I am interested in Facebook and Web specifically). (in my case) I do not see why the traffic from Facebook/Web should go trough Microsoft when it could go directly to the bot. I am in a similar position as [this](https://github.com/Microsoft/BotBuilder/issues/1187), I would like to remove any third party service if possible. Also it seems (correct me if I'm wrong) that now you need a subscription on Azure Bot Service to use it, and the WebChat and DirectLine channels are not free anymore (and I'm sure there are some other hidden costs as well).

So I was wondering if it's possible to make my own custom connector which connects to facebook/web etc. (by implementing `IConnector`, similar to how the `ChatConnector` and `ConsoleConnector` work) in order to completely bypass Microsoft ?

This seems possible, but I haven't seen anyone doing this, so I was wondering if I'm missing something (everyone uses the `DirectLine` to make new "Connectors").

Thank you!

**Comment by JasonSowers** [comment]
Yes, it would be entirely possible to write your own connector.  In fact, anything is possible if you work hard and believe in yourself.  People generally do this to connect channels not currently supported by the Bot framework.  You may want to start by looking for one of those and modifying it for the channel you would like to connect.

**Comment by Xzya** [comment]
Thanks! I will try to follow the `ChatConnector` and `ConsoleConnector` and I also found [this one](https://github.com/Wolke/botbuilder-linebot-connector/blob/master/src/LineConnector.ts), should be enough to get me started.

I guess this can be closed,
Cheers
