### ISSUE TITLE
[Question] Is there a Global Variable that exists only for a user to bot session?

### ISSUE THREAD

**Issue by 2015PM** [Microsoft/BotBuilder#3999]
## Bot Info
* SDK Platform: .NET
* Active Channels:  Direct Line
* Deployment Environment: Azure Server

## Issue Description
I saw once that there exists a function that calculates the satisfaction level of a user. Nevertheless, I'm not able to find an example in C#. Therefore, I started my own try... My aim is to store the satisfaction level of an user and if the satisfaction level of an user has a certain value, it will appear a new message which says that "you should contact the human service desk". 
Current State: I generated a global variable that counts the "None" responses, and when these "None" responses occur, the global variable gets global variable + 1. This works, but over the whole application and not for one user<-> bot connection. Where do I have to store the variable that it is set to 0 for each user <-> bot conversation?

Or does someone know a function from bot framework that should cover my case?
Thanks a lot for your support.
Greetings

## Expected Behavior
Each user <-> bot session has its own global variable that starts with 0. 

## Actual Results
The global variable only starts at 0 after the deplyoment process.

**Comment by JasonSowers** [comment]
In the context object, there are 3 databags you could use instead of a global variable.  `ConversationData` ,`PrivateConversationData`, and `UserData`.  My suggestion would be that you should use `UserData` and do something like this:

```cs
            if (!context.UserData.ContainsKey("your key"))
            {
                context.UserData.SetValue("your key", 0);
            }
            else
            {
                int temp = context.UserData.GetValue<int>("your key");
                context.UserData.SetValue("your key", temp++);
            }
```

**Comment by 2015PM** [comment]
thank you 👍
