### ISSUE TITLE
[C#] Exception in PersistBotData when use custom IBotToUser implementation

### ISSUE THREAD

**Issue by evnik** [Microsoft/BotBuilder#400]
I want to use my custom `IBotToUser` implementation. While the `SendLastInline_BotToUser` is sealed, I wraped it and registered my implementation like it done in the [DirectConversation](https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Samples/EchoBot/DirectConversation.cs). That working perfectly in the Bot Emulator, but when deployed it started throwing of exception:
```
Microsoft.Rest.HttpOperationException: The remote server returned an error: (400) Bad Request.
   at Microsoft.Bot.Connector.ErrorHandling.HandleError[ObjectT](HttpOperationResponse`1 result)
   at Microsoft.Bot.Connector.BotsExtensions.<SetConversationDataAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Internals.PersistentDialogTask.<PersistBotData>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Internals.PersistentDialogTask.<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d__5`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MyBot.MessagesController.<SendAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MyBot.MessagesController.<Post>d__2.MoveNext()
```
Looking at the [PersistentDialogTask](https://github.com/Microsoft/BotBuilder/blob/a2a134080ad42ed460ff8b771e00b496b35e96fa/CSharp/Library/Dialogs/DialogTask.cs#L378) I found checking of the type. When I changed the check to take my implementation into account, the exception is gone.

So, I see two possible solutions:
1. Unseal the `SendLastInline_BotToUser` to make the type check working for derived classes.
2. Introduce some property in the `IBotToUser` (or in a new derived interface) to understand if the `PersistBotData` call should be done.
Additionally, I'm not sure what will happen on unconditional call of `PersistBotData` in the [catch](https://github.com/Microsoft/BotBuilder/blob/a2a134080ad42ed460ff8b771e00b496b35e96fa/CSharp/Library/Dialogs/DialogTask.cs#L371).
Let me know if I can make a PR with one of the suggested fixes. Or maybe I'm doing this wrong and there is a better way to use custom `IBotToUser` implementation?

**Comment by msft-shahins** [comment]
`bool inline = botToUser is SendLastInline_BotToUser || botToUser is BotToUserTextWriter;` is only an optimization to minimize number of calls to connector for when IBotToUser is `SendLastInline_BotToUser` and also it bypasses the persistence for `BotToUserTextWriter` since it is used only for debugging purposes. I guess your problem is not having the right properties set on the message, i.e. conversationId, userId, and botId,  and as a result you get a bad request from connector in the `client.Bots.SetConversationDataAsync` call.

Also the unconditional call of `PersistBotData` in the catch is there to make sure that the current call stack is persisted in case of an unhandled exception. Bot builder resets the call stack in case of an unhandled exception and that call make sure that the bot starts from an empty call stack on the next message.

**Comment by evnik** [comment]
@msft-shahins, thank you for clarification but something is wrong with that optimization. When I commented out the `if` condition, making `PersistBotData` call unconditional, I still have the same exception even without my custom implementation of the `IBotToUser`.
I tried to understand what exactly is wrong with the message, but only found that the `BotConversationData` is null.

**Comment by willportnoy** [comment]
Are you instantiated the Message somehow without using IBotToUser.MakeMessage?  We initialize the message with the necessary fields within that method.

**Comment by evnik** [comment]
No, just checked. I either call `Extensions.PostAsync` method and pass a string, or call `IDialogContext.MakeMessage` to create a reply message.

**Comment by evnik** [comment]
How can instantiating of the `Message` matter if `PersistBotData` handles an incoming (to bot) message? And I can confirm that the `BotConversationData` is null right in the incoming message.

**Comment by willportnoy** [comment]
I don't think it's bad that BotConversationData is null, by the way.  That just means it's empty or unchanged.  We store the dialog state in a different data bag named PerUserInConversationData.

The presence of the test before the last PersistBotData call shouldn't have any side-effects - if you remove the test, it should just inefficiently re-send the same data.

Is your IConnectorClient being instantiated with the proper bot credentials?  That last PersistData would be using the IConnectorClient to send the data direct to the connector, and not inline with the message reply.

**Comment by evnik** [comment]
The issue is the `PersistBotData` call definitely has side effect. You can reproduce this by deploying the SimpleAlarmBot sample. It works perfectly, until you comment out the condition: `// if (!inline)`. After redeploying it returns the _500 Internal Server Error_ only. You can check my instance at https://testbot400.azurewebsites.net/api/messages through the Bot Framework Emulator.
I didn't touch anything related to the IConnectorClient. Should I set it up even in the SimpleAlarmBot sample?

**Comment by msft-shahins** [comment]
When you are sending messages to your bot using the emulator, the `channelId` of the message will be set to `emulator` and `IConnectorClientFactory` will configure the `IConnectorClient` with `http://localhost:9000` and as a result all the direct calls to connector will fails including the persist data calls. Try to test your bot through a connector channel and data will be loaded and persisted correctly.

**Comment by evnik** [comment]
Well, I've registered a bot and tested the SimpleAlarmBot sample in the Web Chat. After redeploying without the condition it stopped to respond, which means an unhandled exception:
![image](https://cloud.githubusercontent.com/assets/10916937/15756249/42e2ec00-28b5-11e6-9772-4fcbbc5b59b3.png)
Are you able to reproduce it?

**Comment by msft-shahins** [comment]
It seems that there is a bug in the way that we set the etag. Try `var etag = "*";` and it should fix it for you.

**Comment by msft-shahins** [comment]
Release [1.2.3](https://github.com/Microsoft/BotBuilder/releases/tag/NuGet1.2.3.0) should have this fixed!

**Comment by evnik** [comment]
Great, it seems to work with the new package, thank you!
Another question is how can I apply that performance optimization to my custom `IBotToUser` implementation? Maybe I should create a new issue for that?

**Comment by wbreza** [comment]
@msft-shahins 

I was having this same issue in 1.2.4.  When bot is replying with multiple messages a null reference exception is being thrown in `Bots.SetConversationDataWithHttpMessagesAsync`.  This only happens when switching dialogs.  I tried many workarounds, verified all connector client configuration is valid but still having the same issue.  I had to roll back to 1.2.2.

Any ideas?

**Comment by willportnoy** [comment]
@wbreza @evnik I would open new issues for your questions - feel free to reference this issue, of course.  When the issue is closed, it doesn't appear in the default issues list, so we don't always notice it.

@wbreza can you include the call stack for your issue?

**Comment by evnik** [comment]
@wbreza I don't think your issue is the same, because I had it in the 1.2.2 and it is gone in 1.2.3. Also, I didn't switch dialogs, but I had it reproduced with SimpleAlarmBot sample, which built around a single dialog.
