### ISSUE TITLE
[Slack] Connector service started sending duplicate messages for Slack channel today?

### ISSUE THREAD

**Issue by v46** [Microsoft/BotBuilder#4001]
Hi folks,

We have several bots deployed in production that use the slack channel integration. About 30 minutes ago, our users are reporting duplicate messages. Roughly 90% of our slack bots are impacted.

Our logs are showing two messages sent by the bot framework to our bot service. So each message typed in by the user, the bot framework is sending two messages to us. 

Can you help clarify there are no production outages at this time for the bot framework/slack channels?

Node SDK - botbuilder : 3.11.0
Bots are not using Azure Bot service (they are hosted outside Azure).

**Comment by msmohan** [comment]
@v46  Please provide SDK Platform and SDK Version info as well.

**Comment by v46** [comment]
updated @msmohan. Thanks!

**Comment by nwhitmont** [comment]
Hi @v46 - Can you provide a `conversationId` of (one or more) conversation where you are experiencing the "double response" bug?

Th `conversationId` will help us track down your specific conversation chain in the Slack connector service logs. Thx

**Comment by dkershner6** [comment]
I am having this same issue on the .Net SDK.  I have deleted my profile, with no improvement.

**Comment by v46** [comment]
@nwhitmont - can I send you that conversation id privately?

**Comment by stevengum97** [comment]
@v46 and @dkershner6 can you test your bot's responses across other channels, e.g. visiting the "Test in WebChat" pane and sending your bot some messages?

**Comment by v46** [comment]
SFB works as good as before. No regressions. 

Some of our bots have both SFB and slack channels enabled, slack is sending dups, while SFB is working as "expected".

**Comment by dkershner6** [comment]
Test in the Bot Framework Test section (which I think is what you are talking about) works fine.

I tested in Skype too, and there is an error, but I think its unrelated (I dont really support Skype, and I do some user detection).  BUT, it only responds once.

**Comment by stevengum97** [comment]
@dkershner6 and @v46, a fix has been deployed that addresses this issue; can you confirm if your bots are now behaving normally?

**Comment by dkershner6** [comment]
![image](https://user-images.githubusercontent.com/25798427/34633172-3a20a9a0-f22f-11e7-84a0-836c438492aa.png)

eformabot thanks you too.  Mine appears fixed.

**Comment by v46** [comment]
Looking good @stevengum97. Thank you folks for jumping on this. 👍

**Comment by stevengum97** [comment]
Awesome, I'm going to close this issue for now, Happy Friday!

**Comment by v46** [comment]
@stevengum97 - what was the fix? 

How can we (API users) can detect these in the future?
