### ISSUE TITLE
[.Net SDK, FB Messenger] How to send proactive message on Messenger?

### ISSUE THREAD

**Issue by harigovind511** [Microsoft/BotBuilder#4004]
## Bot Info
* SDK Platform: .NET
* SDK Version:  3.12.2.4 
* Active Channels:  facebook,sms 
* Deployment Environment: Auzure Bot Service

## Issue Description
Unable to send proactive messages on face book channel. I read in document as it requires **pages_messaging_subscriptions** approved. But to test at the time of development, can we do proactive messaging without approval. if so could you please share me steps to follow to send proactive message on facebook.

Thanks in advance..

**Comment by JasonSowers** [comment]
Have you seen [this doc](https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-proactive-messages)?

**Comment by harigovind511** [comment]
Thanks for the response @JasonSowers . Yes I have followed the same and proactive messages are working fine with other channels. But my requirement is specific to face book which is not working with the same code. Am I need to do any sort of settings change in facebook developer page to do this?. And do we need to get approval from face book to send proactive messages to users at development stage?

**Comment by Ma3yTa** [comment]
@harigovind511 I think you can't use proactive messages on Facebook until this Feature request isn't implemented https://github.com/Microsoft/BotBuilder/issues/2924
@JasonSowers Could you please ask developers to implement it?

**Comment by JasonSowers** [comment]
I can ask, but no promises. 👍

**Comment by Ma3yTa** [comment]
@harigovind511  @JasonSowers I found how I can add a tag. I am using C#
```
var activity = (Activity)message;
activity.Properties = new Newtonsoft.Json.Linq.JObject();
activity.Properties.Add("tag", "APPLICATION_UPDATE");
```
I checked it in Facebook and all works fine.

**Comment by Kothakapu** [comment]
Hi @Ma3yTa, Thanks for sharing. Could you please elaborate, how can we use it to send Proactive messages  on facebook. If possible could you please share C# code snippet for the same, which will be more helpful for us.

**Comment by Ma3yTa** [comment]
Hi @Kothakapu ConversationStarter is my helper class for proactive messages:

how to use

```
var conversationReference = NIMapper.Instance.Map<ConversationReference>(session.ConversationReference);
var starter = new ConversationStarter(conversationReference);
await starter.Resume(msg); // or await starter.ResumeAsDialog(new SurveyDialog());
```

```
public class ConversationStarter
    {
        ConversationReference conversationReference;

        public ConversationStarter(ConversationReference cr)
        {
            conversationReference = cr;
        }


        public async Task Resume(string text)
        {
            IMessageActivity message = Activity.CreateMessageActivity();
            message.Text = text;
            message.Locale = "en-Us";
            await Resume(message);
        }

        public async Task Resume(IMessageActivity message)
        {
            var userAccount = conversationReference.User;
            var botAccount = conversationReference.Bot;
            var connector = new ConnectorClient(new Uri(conversationReference.ServiceUrl));

            //unathorized workaround 
            //https://github.com/Microsoft/BotBuilder/issues/2575
            //https://github.com/Microsoft/BotBuilder/issues/2155#issuecomment-276964664
            MicrosoftAppCredentials.TrustServiceUrl(conversationReference.ServiceUrl);

            message.ChannelId = conversationReference.ChannelId ??
                (await connector.Conversations.CreateDirectConversationAsync(botAccount, userAccount)).Id;
            message.From = botAccount;
            message.Recipient = userAccount;
            message.Conversation = new ConversationAccount(id: conversationReference.Conversation.Id);
            var activity = (Activity)message;
            activity.Properties = new Newtonsoft.Json.Linq.JObject();
            activity.Properties.Add("tag", "APPLICATION_UPDATE");
            await connector.Conversations.SendToConversationAsync(activity);
        }

        public async Task ResumeAsDialog<T>(IDialog<T> dialog)
        {
            var message = conversationReference.GetPostToBotMessage();
            var client = new ConnectorClient(new Uri(message.ServiceUrl));

            using (var scope = DialogModule.BeginLifetimeScope(Conversation.Container, message))
            {
                var botData = scope.Resolve<IBotData>();
                await botData.LoadAsync(CancellationToken.None);

                //This is our dialog stack
                var task = scope.Resolve<IDialogTask>();

                //interrupt the stack. This means that we're stopping whatever conversation that is currently happening with the user
                //Then adding this stack to run and once it's finished, we will be back to the original conversation
                task.Call(dialog.Void<T, IMessageActivity>(), null);

                await task.PollAsync(CancellationToken.None);
                //flush dialog stack
                await botData.FlushAsync(CancellationToken.None);

            }
        }
    }
```

**Comment by stelazh** [comment]
@Kothakapu have you find a solution ? I'm creating a messenger bot , and i need to create a module to send broadcast message to users in a specific time .

**Comment by EricDahlvang** [comment]
Messenger bot developer permissions are determined by Facebook.

Please post Bot Framework Facebook Messenger requests here: https://github.com/Microsoft/BotBuilder/issues/4360

Based on Facebook documentation, bots are allowed to send subscription messages to FB Messenger users: https://developers.facebook.com/docs/messenger-platform/send-messages/

Jason has provided a reference to the docs, and some basic proactive messaging samples can be found here: https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/core-proactiveMessages
