### ISSUE TITLE
[Node.js SDK, Atachments, Question] Bot does not process attachments?

### ISSUE THREAD

**Issue by sisense** [Microsoft/BotBuilder#4005]
## Bot Info
* Deployment Environment: Auzure Bot Service
* Bot ID: cca47733-88af-46fb-9787-2c0815083354

## Issue Description
My bots don't respond when user sends attachment. 

## Code Example
```js
this._dialog.onBegin(function (session, args, next)
{


    var userid = session.message.user.id;

    var source = session.message.source;
    
    var msg = session.message;

    //cache the user state
    if(session.userData && session.userData.userExist)
    {
        if (msg.attachments.length && msg.attachments.length > 0) 
        {
        
            session.beginDialog('/processAttachment');
        }
        else
        {
            next();
            return;
        }
    }
```
## Reproduction Steps
1. bot acts normally when user interact with text messages
2. user sends a file
3. no message received at the bot code

## Expected Behavior
message with attachment

**Comment by msmohan** [comment]
@sisense  Have you tried this [sample code](https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node/core-SendAttachment)?

**Comment by fanidamj** [comment]
Closing the issue assuming it as resolved. Please reopen a new issue if it still persists.
