### ISSUE TITLE
[Skype] Check-in on bot review status for Skype publishing?

### ISSUE THREAD

**Issue by eorione** [Microsoft/BotBuilder#4006]
Hi, my Skype bot has been on review for 7 weeks now, is the process that slow?

My app ID is 4b677e52-b283-470d-8c95-b8808a05565b

**Comment by nwhitmont** [comment]
@eorione - Thanks for following up. I will check on the status and get back when I have more info.

**Comment by eorione** [comment]
@nwhitmont thanks! Any news?

**Comment by nwhitmont** [comment]
@eorione Please check your email for followup from the Skype review team.

**Comment by eorione** [comment]
Thank you @nwhitmont !! We corrected the 2 issues and submitted it again, now it should work right?

Thanks!!!!

**Comment by eorione** [comment]
Hi @nwhitmont, can you please help me and see why it is taking so long? thanks!

**Comment by eorione** [comment]
Hi there, how are you?
I'm still waiting, no one is replying on Microsoft. thanks

**Comment by EricDahlvang** [comment]
@eorione 

I apologize for the delay in responding.  Are you still waiting for your bot to be reviewed?

**Comment by eorione** [comment]
@EricDahlvang yes Eric please!!!! Why does it take so long?

**Comment by EricDahlvang** [comment]
There is a large backlog of bots asking for reviews.  I've messaged the review team, asking them to fast track your bot.  Thank you for your patience.

**Comment by EricDahlvang** [comment]
> I reviewed the bot, the following is the feedback please share it with the customer.
> 1.	In the bot profile page, the description about the bot is insufficient.
> 2.	Please add valid links to privacy policy and terms of use.
> Please make these changes and submit the bot again for review.
>

**Comment by fanidamj** [comment]
Closing the issue assuming it as resolved. Please reopen a new issue if it still persists.
