### ISSUE TITLE
[Migration] Bot doesn't respond in WebChat after migration to Azure?

### ISSUE THREAD

**Issue by Ma3yTa** [Microsoft/BotBuilder#4011]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.12.2.4
* Active Channels: Skype, Telegram, Facebook
* Deployment Environment: Azure Bot Service

## Issue Description
Bot doesn't respond in WebChat after migration to Azure.
Bot respond in Skype, Telegram and Facebook.

## Reproduction Steps
1. open https://webchat.botframework.com/embed/nowinfinity_assistant?s=tLpzGsqeh3M.cwA.Kd8.jTeFFmQ6UrwLeSdtXKQLUgMFE3jqcaEJXp_FNkhsxIA
2. type hi

## Expected Behavior
Bot respond.

## Actual Results
Bot doesn't respond.
Log from Azure Portal console:
![](https://i.gyazo.com/8660c9ec83af9334298bd9c8ff62c633.png)
![](https://i.gyazo.com/39bca66c45a4f020792cb3e4d8be5aed.png)

**Comment by msmohan** [comment]
Can you provide bot id / handle?

**Comment by Ma3yTa** [comment]
@msmohan Bot handle: nowinfinity_assistant AppId: 62516114-227c-436c-8e55-e7dcf50e7474

**Comment by Ma3yTa** [comment]
@msmohan all works fine now. looks like the problem was in LUIS configuration I used westus.api.cognitive.microsoft.com instead southeastasia.api.cognitive.microsoft.com. But I don't understand why it worked fine in Skype, Telegram, and Facebook.
