### ISSUE TITLE
[LUIS] Getting datetimeV2 error with accent in French language?

### ISSUE THREAD

**Issue by Loski** [Microsoft/BotBuilder#4012]
## Bot Info
Luis

## Issue Description
Luis doesn’t  recognise the word mercredi (for Wednesday ) for the entity datetimeV2.
Luis has an incorrect behavior for a month with an accent (février / décembre / août). You can bypass it if you send the word without accent.

## Reproduction Steps
1. Luis with French culture
2. Test an utterance with Mercredi / Février

## Expected Behavior
Bot respond a datetimeV2 like other dates.
`{
  "query": "mercredi",
  "topScoringIntent": {
    "intent": "Event.Location.Restoration",
    "score": 0.136376724
  },
  "entities": [
    {
      "entity": "mercredi",
      "type": "builtin.datetimeV2.date",
      "startIndex": 0,
      "endIndex": 8,
      "resolution": {
        "values": [
          {
            "timex": "XXXX-WXX-4",
            "type": "date",
            "value": "2018-01-03"
          },
          {
            "timex": "XXXX-WXX-4",
            "type": "date",
            "value": "2018-01-10"
          }
        ]
      }
    }
  ]
}`

## Actual Results
`{
  "query": "mercredi",
  "topScoringIntent": {
    "intent": "Event.Location.Restoration",
    "score": 0.136376724
  },
  "entities": []
}`

**Comment by nwhitmont** [comment]
Hi @Loski - I have escalated your issue to LUIS team for investigation. Will get back when I have more info.

**Comment by tellarin** [comment]
DatetimeV2 uses Microsoft/Recognizers-Text. I've created this issue there. Fix is on the way.

**Comment by stevengum97** [comment]
@Loski, you can follow the PR that fixes this issue through this link: _[French mercredi fix #263](https://github.com/Microsoft/Recognizers-Text/pull/263)_.

**Comment by matthewshim-ms** [comment]
@stevengum97 I fixed the accent resolution for Dec/Feb/Aug, included test cases + re-built for both frenchDateTime.ts + /French/DateTimeDefinitions.cs for Javascript + .NET respectively

**Comment by tellarin** [comment]
This has been fixed in Microsoft/Recognizers-Text now. LUIS should start using it on the next deployment.
@Loski, thanks for reporting it! Let us know if you find any other issues.

**Comment by stevengum97** [comment]
Closing this issue as the fix is in the pipeline; @Loski if you still see this issue, please feel free to reopen this issue and @-mention me.
