### ISSUE TITLE
[Node.js SDK, FB Messenger, Question] Getting error "Cannot read dialoginterrupted of undefined" after renaming dialog?

### ISSUE THREAD

**Issue by Kyle-MacKinnon** [Microsoft/BotBuilder#4013]
## Bot Info
* SDK Platform: Node.js
* SDK Version: 3.13.0
* Active Channels: Facebook
* Deployment Environment: AWS Elastic Beanstalk

## Issue Description
When a dialog is renamed and redeployed, then anyone with state data containing the old name will generate errors and the bot will no longer respond to them.

## Reproduction Steps
1. Create a dialog
2. Run the chatbot with a live state service
3. Chat to the bot
4. Rename the dialog you were just in
5. Redeploy the chatbot
6. Attempt to talk to the bot again

## Expected Behavior
The user should have their stack cleared so that they start from the beginning again.

## Actual Results
The bot doesn't respond at all and each message they send generates an error.

> Unhandled Rejection at: Promise Promise {
>   _bitField: 18087936,
>   _fulfillmentHandler0: TypeError: Cannot read property 'dialogInterrupted' of undefined
>     at Object.handler (/var/app/current/node_modules/botbuilder/lib/dialogs/ActionSet.js:220:28)
>     at next (/var/app/current/node_modules/botbuilder/lib/dialogs/ActionSet.js:145:19)
>     at ActionSet.selectActionRoute (/var/app/current/node_modules/botbuilder/lib/dialogs/ActionSet.js:153:13)
>     at Library.selectGlobalActionRoute (/var/app/current/node_modules/botbuilder/lib/bots/Library.js:230:22)
>     at Library.defaultSelectRoute (/var/app/current/node_modules/botbuilder/lib/bots/Library.js:307:22)
>     at Library.selectRoute (/var/app/current/node_modules/botbuilder/lib/bots/Library.js:96:18)
>     at disambiguateRoute (/var/app/current/node_modules/botbuilder/lib/bots/UniversalBot.js:398:62)
>     at /var/app/current/node_modules/botbuilder/lib/bots/UniversalBot.js:407:21
>     at /var/app/current/node_modules/async/lib/async.js:52:16
>     at Object.async.forEachOf.async.eachOf (/var/app/current/node_modules/async/lib/async.js:236:30)
>     at Object.async.forEach.async.each (/var/app/current/node_modules/async/lib/async.js:209:22)
>     at /var/app/current/node_modules/botbuilder/lib/bots/UniversalBot.js:386:19
>     at UniversalBot.Library.recognize (/var/app/current/node_modules/botbuilder/lib/bots/Library.js:68:13)
>     at UniversalBot.routeMessage (/var/app/current/node_modules/botbuilder/lib/bots/UniversalBot.js:374:14)
>     at /var/app/current/node_modules/botbuilder/lib/bots/UniversalBot.js:291:23
>     at /var/app/current/node_modules/botbuilder/lib/bots/UniversalBot.js:352:78
>     at next (/var/app/current/node_modules/botbuilder/lib/Session.js:88:17)
>     at /var/app/current/node_modules/botbuilder-facebookextension/lib/middleware/user-profile.js:50:17
>     at tryCatcher (/var/app/current/node_modules/bluebird/js/release/util.js:16:23)
>     at Promise._settlePromiseFromHandler (/var/app/current/node_modules/bluebird/js/release/promise.js:512:31)
>     at Promise._settlePromise (/var/app/current/node_modules/bluebird/js/release/promise.js:569:18)
>     at Promise._settlePromise0 (/var/app/current/node_modules/bluebird/js/release/promise.js:614:10),
>   _rejectionHandler0: undefined,
>   _promise0: undefined,
>   _receiver0: undefined,
>   _cancellationParent:
>    Promise {
>      _bitField: 16777216,
>      _fulfillmentHandler0: TypeError: Cannot read property 'dialogInterrupted' of undefined
>     at Object.handler (/var/app/current/node_modules/botbuilder/lib/dialogs/ActionSet.js:220:28)
>     at next (/var/app/current/node_modules/botbuilder/lib/dialogs/ActionSet.js:145:19)
>     at ActionSet.selectActionRoute (/var/app/current/node_modules/botbuilder/lib/dialogs/ActionSet.js:153:13)
>     at Library.selectGlobalActionRoute (/var/app/current/node_modules/botbuilder/lib/bots/Library.js:230:22)
>     at Library.defaultSelectRoute (/var/app/current/node_modules/botbuilder/lib/bots/Library.js:307:22)
>     at Library.selectRoute (/var/app/current/node_modules/botbuilder/lib/bots/Library.js:96:18)
>     at disambiguateRoute (/var/app/current/node_modules/botbuilder/lib/bots/UniversalBot.js:398:62)
>     at /var/app/current/node_modules/botbuilder/lib/bots/UniversalBot.js:407:21
>     at /var/app/current/node_modules/async/lib/async.js:52:16
>     at Object.async.forEachOf.async.eachOf (/var/app/current/node_modules/async/lib/async.js:236:30)
>     at Object.async.forEach.async.each (/var/app/current/node_modules/async/lib/async.js:209:22)
>     at /var/app/current/node_modules/botbuilder/lib/bots/UniversalBot.js:386:19
>     at UniversalBot.Library.recognize (/var/app/current/node_modules/botbuilder/lib/bots/Library.js:68:13)
>     at UniversalBot.routeMessage (/var/app/current/node_modules/botbuilder/lib/bots/UniversalBot.js:374:14)
>     at /var/app/current/node_modules/botbuilder/lib/bots/UniversalBot.js:291:23
>     at /var/app/current/node_modules/botbuilder/lib/bots/UniversalBot.js:352:78
>     at next (/var/app/current/node_modules/botbuilder/lib/Session.js:88:17)
>     at /var/app/current/node_modules/botbuilder-facebookextension/lib/middleware/user-profile.js:37:17
>     at tryCatcher (/var/app/current/node_modules/bluebird/js/release/util.js:16:23)
>     at Promise._settlePromiseFromHandler (/var/app/current/node_modules/bluebird/js/release/promise.js:512:31)
>     at Promise._settlePromise (/var/app/current/node_modules/bluebird/js/release/promise.js:569:18)
>     at Promise._settlePromise0 (/var/app/current/node_modules/bluebird/js/release/promise.js:614:10),
>      _rejectionHandler0: [Function],
>      _promise0: undefined,
>      _receiver0: undefined,
>      _cancellationParent: undefined,
>      _branchesRemainingToCancel: 1,
>      _onCancelField: undefined } } reason: TypeError: Cannot read property 'dialogInterrupted' of undefined
>     at Object.handler (/var/app/current/node_modules/botbuilder/lib/dialogs/ActionSet.js:220:28)
>     at next (/var/app/current/node_modules/botbuilder/lib/dialogs/ActionSet.js:145:19)
>     at ActionSet.selectActionRoute (/var/app/current/node_modules/botbuilder/lib/dialogs/ActionSet.js:153:13)
>     at Library.selectGlobalActionRoute (/var/app/current/node_modules/botbuilder/lib/bots/Library.js:230:22)
>     at Library.defaultSelectRoute (/var/app/current/node_modules/botbuilder/lib/bots/Library.js:307:22)
>     at Library.selectRoute (/var/app/current/node_modules/botbuilder/lib/bots/Library.js:96:18)
>     at disambiguateRoute (/var/app/current/node_modules/botbuilder/lib/bots/UniversalBot.js:398:62)
>     at /var/app/current/node_modules/botbuilder/lib/bots/UniversalBot.js:407:21
>     at /var/app/current/node_modules/async/lib/async.js:52:16
>     at Object.async.forEachOf.async.eachOf (/var/app/current/node_modules/async/lib/async.js:236:30)
>     at Object.async.forEach.async.each (/var/app/current/node_modules/async/lib/async.js:209:22)
>     at /var/app/current/node_modules/botbuilder/lib/bots/UniversalBot.js:386:19
>     at UniversalBot.Library.recognize (/var/app/current/node_modules/botbuilder/lib/bots/Library.js:68:13)
>     at UniversalBot.routeMessage (/var/app/current/node_modules/botbuilder/lib/bots/UniversalBot.js:374:14)
>     at /var/app/current/node_modules/botbuilder/lib/bots/UniversalBot.js:291:23
>     at /var/app/current/node_modules/botbuilder/lib/bots/UniversalBot.js:352:78
>     at next (/var/app/current/node_modules/botbuilder/lib/Session.js:88:17)
>     at /var/app/current/node_modules/botbuilder-facebookextension/lib/middleware/user-profile.js:50:17
>     at tryCatcher (/var/app/current/node_modules/bluebird/js/release/util.js:16:23)
>     at Promise._settlePromiseFromHandler (/var/app/current/node_modules/bluebird/js/release/promise.js:512:31)
>     at Promise._settlePromise (/var/app/current/node_modules/bluebird/js/release/promise.js:569:18)
>     at Promise._settlePromise0 (/var/app/current/node_modules/bluebird/js/release/promise.js:614:10)

**Comment by EricDahlvang** [comment]
Apologies for the lack of response.  Changing the name of a dialog after the bot has been used is not a supported scenario.  Users of the bot should send '/deleteProfile' to clear out the data bags, or the developer should remove those objects from the state store to prevent users from encountering exceptions.
