### ISSUE TITLE
[Node.js SDK, Slack] How to intercept "Link_Share workspace event" from Slack channel?

### ISSUE THREAD

**Issue by nisingla** [Microsoft/BotBuilder#4016]
## Bot Info
* SDK Platform: Node js
* SDK Version: 3.9.1
* Active Channels: Slack
* Deployment Environment:  local development with ngrok

## Issue Description
I have created a slack app having microsoft bot connected to it using https://docs.microsoft.com/en-us/bot-framework/bot-service-channel-connect-slack. The issue I am facing is that link_shared workspace event for slack app not triggered which is required to support link unfurling described here https://api.slack.com/docs/message-link-unfurling. What I have done is Registered the domains,added links:read and links:write permissions,added link_shared event in the slack app settings. Then I am using the code written below. Here when I receive any event after user posted a message containing link of registered event I just receive event type as message not link_share. I have tested this in few public channels and on OS X platform Slack App. As this event is a workspace event so how can I handle the workspace events of slack using botframework.

## Code Example
registerBotMiddleware() { this.mBot.use(builder.Middleware.sendTyping()); this.mBot.use({ receive: (event, next) => { }, }); } 

## Reproduction Steps
Create a Slack app and try to listen to workspace events.

## Expected Behavior
Get slack workspace events.

## Actual Results
No slack workspace events coming.

**Comment by nwhitmont** [comment]
Relates to: https://stackoverflow.com/questions/48089456/link-shared-event-for-slack-app-not-triggered

**Comment by nisingla** [comment]
@nwhitmont  This question is also posted by me.

**Comment by fanidamj** [comment]
Can you please let us know if the issue still persists?

**Comment by JasonSowers** [comment]
Please open a new issue if you are still experiencing problems
