### ISSUE TITLE
a faster way to use directline 

### ISSUE THREAD

**Issue by bluekite2000** [Microsoft/BotBuilder#402]
Currently when a use says "hi" I then do 3 posts ( start convo, get token, say hi) and 1 get ( to get bot's response to the hi) before I can talk to the bot.  That takes 10s on average. 
Anything I can do to cut time to 1s ?

**Comment by dandriscoll** [comment]
We rolled out a number of perf improvements recently.

Do you need the added security that the token provides? A token is useful when you have a thin client app (like a webpage or an app) working directly against the Direct Line API. If you don't need that, you can skip the token generation and just use your secret directly on every call.

**Comment by dandriscoll** [comment]
Do please take a look at perf and let me know if things haven't improved dramatically. We've added more caching and this API should be a lot faster now.
