### ISSUE TITLE
[Question] Help me understand how Bot Framework connector service works?

### ISSUE THREAD

**Issue by napoleonjones** [Microsoft/BotBuilder#4021]
##Questions
My team is looking at using the bot framework and have a few questions.  We will NOT be hosting this in Azure and would host the bot on our own IIS server.

1.  Is the connector required to use the bot?  We are currently considering webchat only.  I am assuming for some channels the connector is required.

2.  What ports does the connector use?

3.  Does the connector access any of the data sent to/from the user?

4.  How is the data encrypted?

Thank you

**Comment by nwhitmont** [comment]
For Q3 - the data protection and privacy guidelines are available here:

- Bot Framework (Preview) Online Services Agreement: https://www.botframework.com/Content/Microsoft-Bot-Framework-Preview-Online-Services-Agreement.htm
- Bot Framework Developer Code of Conduct: https://www.botframework.com/Content/Developer-Code-of-Conduct-for-Microsoft-Bot-Framework.htm
- Cognitive Services Devloper Code of Conduct: https://azure.microsoft.com/en-us/support/legal/developer-code-of-conduct/?v=17.23h
- Cognitive Services Trust Center: https://www.microsoft.com/en-us/trustcenter/cloudservices/cognitiveservices
- General MS: https://privacy.microsoft.com/en-us/
