### ISSUE TITLE
[Skype for Business] Markdown and Line Break formatting inconsistencies (macOS vs Windows)

### ISSUE THREAD

**Issue by amehta3000** [Microsoft/BotBuilder#4022]
SDK Platform: python
SDK Version: BotBuilder 3.11.0
Active Channels: Skype for Business
Deployment Environment: ngrok

## Issue Description
SFB Markdown for Mac client/ iOS vs PC/Android is inconsistent.  We have taken Bot Framework's recommendation to remove html and use only Markdown.

• We have accepted that Markdown **bold** does not render in either PC nor Mac and have not seen a way to do it without using html (which will completely block output on Mac clients)
• **Bold** on PC renders it as italics
• _Italics_ on PC renders as italics
• Both of the above are ignored on Mac/iOS clients and just give me text no formatting.

Regardless of Markdown formatting, the most important thing we can do with mostly text based formatting, are LINE BREAKS. 

Please advise on how to properly render LINE BREAKS across all channels?
We have been instructed to use `\n\n` but this does not work on SFB standalone clients for PC, MAC, iOS, Android

• On Mac, does not even compute (see screenshot)
• On PC, does not compute (see screenshot)

We've tried several methods including unicode `\u00A0\u00A0\n` and ultimately we came to use the following _hack_:
`\n\n\u200C<br/>` for a single line break.

To make another paragraph separated by a break we have to use this:
`\n\n\u200C<br/>\n\nu200C<br/>`

This is really bothersome, as we have also seen older instances of SFB on PC have even larger breaks perhaps respecting the original `\n\n`.  See attached image

## Code Example
RAW text output that gets sent to json when using the recommend `\n\n` markdown method:
```
This is normal text followed by two slash n line breaks.

This should come after two line breaks.

This markdown text should be **BOLD** and this should be __ITALICS__







→ **This title is wrapped by double asteriks**





1 - Button 1



2 - Button 2



3 - Button 3



**This is a footer wrapped by two asteriks, should be Markdown bold.**



```

## Expected Behavior
I expect to consistently be able to create new lines at will across all platforms, PC, Mac, Android, iOS, Azure testbed

## Actual Results
See screenshot.
![sfb_markdown_linebreaks](https://user-images.githubusercontent.com/151545/34748801-298c3560-f553-11e7-9109-7267bbd5d03a.jpg)

**Comment by rohankulkarni21** [comment]
I am facing the same issue and not able to make my bot live on production. This is making heavy impact on my product. Guys, can you please resolve this?

**Comment by nihalmehdi** [comment]
Below code work for for skype for business
result.AppendFormat(string.Format("{0} : {1}{2}", destinationShortName, status, "\n\n\u200C<br/>\n\n<br/>"));

**Comment by amehta3000** [comment]
@nihalmehdi so you looks like you also went with  `\n\n\u200C\n\n` for the line break, which is still not ideal and I see that you get an extra space indent on mac.

For the color text, basically you are just inserting a string **Under construction** - how does that results in a colored text?

**Comment by ganesh1190** [comment]
two spaces followed by \n again space followed by \n works on all platforms for skype for business

**Comment by amehta3000** [comment]
@ganesh1190 Can you please share screenshots and your output? I just ran this through both PC and Mac and you can get a single carriage return but doubling it will not give you complete line breaks. I would expect `  \n \n  \n \n` to give me a blank line, but it does not.

![sfb_markdown_linebreaksii](https://user-images.githubusercontent.com/151545/35114478-c10f0fba-fc39-11e7-904c-16dc768646f1.jpg)

**Comment by ganesh1190** [comment]
@amehta3000 
![image](https://user-images.githubusercontent.com/31585550/35137701-d1dfe80a-fd10-11e7-9ae3-42fd9e004a0b.png)

**Comment by amehta3000** [comment]
Yes, i see that, but can you make it produce a blank line between Hey / Hi?

`var msgToSend = new builder.Message().text("Hey  \n \n  \n \nHi");`

You would assume that you can do another carriage return, but this does not render properly. When we have a little more complex hierarchy of text, blanks line would be preferable for legibility.

**Comment by ganesh1190** [comment]
For that, few Unicodes are helpful as - 
`var msgToSend = new builder.Message().text("Hey  \n\n\u200C  \n\nHi")` 

`\u200C` followed by  two spaces , follwed by `\n\n` will give you blank line.

![image](https://user-images.githubusercontent.com/31585550/35209952-4587fb78-ff76-11e7-911d-91c04faa272a.png)

**Comment by ganesh1190** [comment]
as per previous comments replace  `\n\n\u200C\n\n` with => `Hey  \n\n\u200C  \n\nHi`
second `\n\n` should have two spaces before it. 
This will give you a blank line 
Testes for all platforms
![image](https://user-images.githubusercontent.com/31585550/35210140-ff22f0ba-ff76-11e7-94bf-22bb4bc14f49.png)

**Comment by nihalmehdi** [comment]
![codesnippet](https://user-images.githubusercontent.com/16753348/36365735-d8a44af0-1570-11e8-8d9f-db301a008691.png)

**Comment by amehta3000** [comment]
@nihalmehdi the <span> text will not work in Mac OS SFB.  MS has indicated that bot framework does not really support HTML across platforms and it better to use Markdown.

**Comment by nihalmehdi** [comment]
Any markdown for bold that works across android,ios and desktop..

**Comment by JasonSowers** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
