### ISSUE TITLE
[Node.js SDK, Question] How to know when message was sent, via callback or other method?

### ISSUE THREAD

**Issue by LucioC** [Microsoft/BotBuilder#4023]
Hello guys,

I have already saw the issue #1558 related to botbuilder on AWS lambda (nodejs). I was able to make it work but now I'm trying to integrate botbuilder (NodeJS) with a library called claudia-bot-builder (https://github.com/claudiajs/claudia-bot-builder), and as far as I investigated I need to now exactly when messages have been completely sent to the network.

I don't completely know the internal code of the claudia library so I'm following the implementations they use for other chatbots to expand for botbuilder. I'm returning a promise to a module of the library and trying to resolve it on the correct moment that the message has been sent. What I tried:
- Resolve it on the 'end' call of the response object of the connector.listen(). Same suggestion as #1558. As I said, it works when I'm using lambda and botbuilder alone but it does not work when I'm integrating it with claudia in this way (not sure why, why lambda would be waiting the message to be send after I called the lambda callback but not after my returned promise is resolved on the second case?)
- Resolve it on the 'send' middleware event of the UniversalBot. I install the middleware on UniversalBot.use and resolve on the send method.
- Add listener to the 'outgoing' event on UniversalBot.on('outgoing', ...).

None of these things worked correctly. The first message from the user does not receive a response. On the second message, the first message is answered (there is something that only finishes execution on the next lambda call). 

Finally I use the setTimeout with a timeout of 1500ms inside the outgoing event and this way the the messages are correctly responded. So the message is taking some time to finish execution and when I resolve the promise lambda stops execution right after it.

Is there some way of knowing when the message was completely sent to make it work?

**Comment by nwhitmont** [comment]
Hi @LucioC - Can you share a code example that demonstrates the issue?

**Comment by LucioC** [comment]
@nwhitmont I'm changing the claudia-bot-builder library code to add botbuilder/cortana support, so I'm not sure how much the example will help.

I add a new endpoint callback using their claudia-api-builder by calling :
```
api.post('/cortana', (event, context) => {
  //my code here
})
```
From what I debugged they only send me the event and context parameters from lambda handler signature, not the callback one.

Objects initialization (runs once):
```
connector = new builder.ChatConnector({
 appId: **my app id***,
 appPassword: **myapppassword**
});

universalBot = new builder.UniversalBot(connector, (session) => {
  session.send('respond to ' + session.message.text);
});

```

So I return a new Promise and tried to resolve it on the 'end' event:
```
return new Promise((resolve) => {
      let reqWrapper = {
        body: event.body,
        headers: event.headers
      };
      let resWrapper = {
        status: () => {
        },
        end: () => {
          resolve();
        }
      };
      connector.listen(reqWrapper, resWrapper);
    });
```

The above does not work and the lambda finishes before responding the message to the user.  I tried to call the context methods like succeed() and done() in this point too.
I also tried to resolve the promise on other events like 'outgoing' and 'send'.

I did find a solution though. I looked at the botbuilder code to find a callback after the message was send and override it to call my resolve().
```
let oldSend = universalBot.send;
universalBot.send = function(messages, done) {
  let newDone = function () {
    done();
    self.resolver();
  };
  oldSend.call(universalBot, messages, newDone);
};
```

**Comment by JasonSowers** [comment]
Please open a new issue if you are still experiencing problems
