### ISSUE TITLE
[Skype] Regular expression not working to find email address in chat message?

### ISSUE THREAD

**Issue by gcfabri** [Microsoft/BotBuilder#4024]
## Bot Info
* SDK Platform: Node.js
* SDK Version: Bot Builder 3.13.1 with Botkit 0.6.7
* Active Channels: Skype, Messenger, Telegram and Web
* Deployment Environment: Azure Bot Service and Azure App Service

## Issue Description
I built a bot using Bot Framework (node.js) with four connected channels (Messenger, Telegram, Skype and Web). At any moment the bot validates an inputted email address using a regular expression like this below:

    /^[-a-z0-9~!$%^&*_=+}{\'?]+(\.[-a-z0-9~!$%^&*_=+}{\'?]+)*@([a-z0-9_][-a-z0-9_]*(\.[-a-z0-9_]+)*\.(aero|arpa|biz|com|coop|edu|gov|info|int|mil|museum|name|net|org|pro|travel|mobi|[a-z][a-z])|([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}))(:[0-9]{1,5})?$/i

It is working properly on all channels, except the Skype. E.g: *gcfabri@gmail.com* match with this regex but on Skype channel it doesn't happens.

## Code Example
`emailRegex.test(`gcfabri@gmail.com`);`

## Expected Behavior
The email address _gcfabri@gmail.com_ should match with the regex above.

## Actual Results
Skype channel just ignore the step with the regex validation.

**Comment by nwhitmont** [comment]
Hi @gcfabri - You need to verify that the content being returned by Skype channel is actually an email address. Sometimes Skype wraps email addresses in HTML tags, so you would need to adjust your RegEx accordingly. 

Example: `<a href="mailto:name@email.com">name@email.com</a>`

**Comment by vcardins** [comment]
I'm facing the same problem with Slack, I tried using the following PromptValidator but still didn't get it to work . (SDK v4)
```csharp
public static PromptValidatorEx.PromptValidator<TextResult> GetEmailValidator(string scapeKeyword = "", string message = null)
	{
		return async (ITurnContext context, TextResult result) => {
			string email = Regex.Replace(result.Value.Trim(), @"(<a[^>]+>)(.*?)(<\/a>)", (m) => m.Groups[2].Value);
			try
			{
				var value = new System.Net.Mail.MailAddress(email);
				result.Value = value.Address;
			}
			catch
			{
				result.Status = PromptStatus.NotRecognized;
				await context.SendActivity(message ?? $"{email} is an invalid email");
			}
		};
	}
```

**Comment by usheveta** [comment]
Hi,

I tried doing the following -
var newGroupMailboxEmailAddress = Regex.Replace(MailboxrequestFormData.GroupMailboxEmailAddress, "</?(a|A).*?>", "");
This will remove the hyperlinks while saving the data and the data gets saved without any error.

Above values are coming from FormFlow.

**Comment by Harshgupta71** [comment]
Hi All, 

I was facing the same issue and I found the below regular express which resolved my issue. 

@"\b(?!mailto\:)([\w-]+(.[\w-]+)@([a-z0-9-]+(.[a-z0-9-]+)?.[a-z]{2,6}|(\d{1,3}.){3}\d{1,3})(:\d{4})?)"

Thanks
