### ISSUE TITLE
[.NET SDK] Microsoft.Bot.Builder and Microsoft.Bot.Builder.Calling are incompatible?

### ISSUE THREAD

**Issue by IvanSheyenko** [Microsoft/BotBuilder#4025]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.12.2.4
* Active Channels:  Skype
* Deployment Environment:  Azure App Service

## Issue Description
Microsoft.Bot.Builder nuget requires:
* System.IdentityModel.Tokens.Jwt (**>= 5.1.4**)

Microsoft.Bot.Builder.Calling nuget requires:
* Microsoft.Bot.Builder (>= 3.12.2.4)
* System.IdentityModel.Tokens.Jwt (>= 4.0.4.403061554 && **< 5.0.0**)

So I am not able to add both components. I there a way to solve it?

## Actual Results
Cant install both Microsoft.Bot.Builder and Microsoft.Bot.Builder.Calling of version 3.12.2.4

**Comment by JasonSowers** [comment]
As a solution, you should be able to use a [binding redirect](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/redirect-assembly-versions).

**Comment by JasonSowers** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
