### ISSUE TITLE
[Cortana] REST API call to external service not working on Cortana channel, works on Emulator?

### ISSUE THREAD

**Issue by irfanahm** [Microsoft/BotBuilder#4026]
## Bot Info
* SDK Platform:  .NET 
* SDK Version: 3.12.2.4
* Active Channels:  Skype, Web Chat, Cortana

## Issue Description
I am trying to call a rest API by taking a File number as input parameter from user and then getting some sample File information from a rest based Web API. This is working perfectly using bot emulator, skype, bot is able to take input and return the output from the Web API, but when using Cortana it is not working. 

## Code Example
 ```cs
                HttpClient client = new HttpClient();
                
                client.BaseAddress = new Uri("http://webapidemo-t2.azurewebsites.net/");
                // Add an Accept header for JSON format.
                client.DefaultRequestHeaders.Accept.Add(
                    new MediaTypeWithQualityHeaderValue("application/json"));

                HttpResponseMessage response = client.GetAsync("api/User/" + FileNumber).Result;

                if (response.IsSuccessStatusCode)
                {
                    Task<string> responseContent = response.Content.ReadAsStringAsync();

                    var strJson = Newtonsoft.Json.Linq.JToken.Parse(responseContent.Result);
                    // FileInfo listMessageCode = JsonConvert.DeserializeObject<FileInfo>(strJson);

                    FileDetails = JsonConvert.DeserializeObject<FileInfo>(strJson.ToString());

          }
```

## Expected Behavior
File information should shown by Cortana like other channels

## Actual Results
Cortana goes work. Enabling Debug mode didn't help. Json doesn't contains any exception information.

**Comment by nwhitmont** [comment]
@irfanahm - Cortana has a 10s timeout, which is shorter than other channels (15s) - if your API call takes longer than 10s to complete it will cause your Cortana skill/bot to timeout.

**Comment by irfanahm** [comment]
Thanks.
I don’t think it’s taking note than 10 seconds
It’s just returning hard code values. You can also test the link I mentioned in my problem description. It’s very fast.

**Comment by aes421** [comment]
Any update?  I'm having this issue too.

**Comment by aes421** [comment]
Here's a link to my stackoverflow question with more info https://stackoverflow.com/questions/48778754/cortana-skill-not-making-rest-api-call

**Comment by shrilekha** [comment]
Facing the same issue, with the error in the channel being "Error calling Cortana backend" and on the console "Error: POST to 'https://CortanaBFChannelWestUS.azurewebsites.net/v3/conversations/9f5b9d9e-1c7c-4487-8462-1c11557ae09f/activities/GRet5x9Yr35' failed: [500] Internal Server Error". 

Have tried using request-promise-native, and the bot works fine in other channels.  When I click on the above Error POST link, it shows "The requested resource does not support http method 'GET'."  and Cortana hangs after the response from the service to which I'm doing a POST, is it a Cortana internal post issue after the response? Please help, thanks! 

Code Snippet:
```
console.time("queryTime"); 
var options = {
		method: 'POST',
		uri: '<hostname>',
		qs: {
			// qs params
		},
	json: true 
};
rp(options)
	.then(function (parsedBody) {
	console.log(parsedBody);
	console.timeEnd("queryTime");
        var msg = "Returned from the web service"; 
	session.say(msg, msg);
```

Output: 
```
<Printed Response from Web service> 
queryTime: 523.541ms
Error: POST to 'https://CortanaBFChannelWestUS.azurewebsites.net/v3/conversations/9f5b9d9e-1c7c-4487-8462-1c11557ae09f/activities/GRet5x9Yr35' failed: [500] Internal Server Error
    at Request._callback (D:\home\site\wwwroot\node_modules\botbuilder\lib\bots\ChatConnector.js:559:46)
    at Request.self.callback (D:\home\site\wwwroot\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (D:\home\site\wwwroot\node_modules\request\request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (D:\home\site\wwwroot\node_modules\request\request.js:1085:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
```

**Comment by EricDahlvang** [comment]
Other channels allow sending messages proactively but the Cortana channel does not currently support this.  With Cortana, the bot has 10 seconds to send messages and acknowledge the call (status 200).  Once the call is acknowledged, the bot cannot send more messages and must wait for Cortana to call the bot in order to respond.

**Comment by shrilekha** [comment]
Thanks @EricDahlvang. Is there any specification as to how long the bot has to wait before Cortana will be listening to it again?  Alternatively, is there any way to override the 10s limit through the bot's code? 
  
The response from my web service is within 0.6 seconds, but Cortana's able to display the output from the call only when I strip off every other bit of processing + session.say statements. Hope this limit's modified soon. Thanks!

**Comment by EricDahlvang** [comment]
There is no way to override the 10s limit.  Replies to Cortana can only be sent while Cortana is in the process of calling the bot.  Once the call is acknowledged, the bot must wait for another call from Cortana before it can send another message.

Proactive calls to Cortana is definitely on the team radar, though we have no timeline to share right now.

**Comment by FranciscoPonceGomez** [comment]
Closing this issue
