### ISSUE TITLE
[Node.js SDK, Cortana] Bug? - Choice prompts don't work with voice clients?

### ISSUE THREAD

**Issue by rjgmail88** [Microsoft/BotBuilder#4027]
## Bot Info
App ID: 984ede7e-bc35-4767-a19b-60a2d6c5e4be
SDK Platform: Node.js
Active Channels: Cortana , Direct Line
Deployment Environment: Azure App Service

## Issue Description
`builder.Prompts.choice` doesn't work with voice clients aka Cortana. 

I have built Cortana skill using BOT API's. In my dialogs I'm using builder.Prompts.choice at multiple places. In chat clients like bot emulator or Cortana iOS app (voice and chat both) `builder.Prompts.choice` works fine. As in it shows multiple options and user can select one my clicking one or choosing number 1,2 etc. 

I'm using the HK Invoke device as voice based client where I'm able to call my custom skill. It is working fine for all the dialogs but when it reaches to code having `builder.Prompts.choice` ...Hk Invoke can't read it out.

## Code Example
```js
session.conversationData.choicesArray = ['ABC', 'XYZ']

builder.Prompts.choice(session, `Okay, I see you have multiple meetings}. Can you choose one by subject?`,session.conversationData.choicesArray,{ listStyle: builder.ListStyle.button },        
            {speak: `Okay, I see you have multiple meetings with}. Can you choose one by subject?`,
            inputHint: builder.InputHint.expectingInput});
```

https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-dialog-prompt#promptschoice

HK invoke can speak only following texts. But doesn't read out the choice options.  
Okay, I see you have multiple meetings
Can you choose one by subject?

## Expected Behavior
Choice prompts should work as expected.

**Comment by rjgmail88** [comment]
Bump...any update/suggestions here please? Our development has blocked due to this limitation.

**Comment by rjgmail88** [comment]
JasonSowers, could not get it.

**Comment by rjgmail88** [comment]
Has anyone faced same issue ?

**Comment by JasonSowers** [comment]
@rjgmail88 We recently acquired an HK invoke.  Are you still seeing this issue?

**Comment by rjgmail88** [comment]
Yes. We have a workaround for now in which we define different value for property **speak** which HK understands. But, downside of that is we need to keep 2 separate forms. One for HK and one for other channels.

**Comment by JasonSowers** [comment]
Glad you were able to find a solution.
