### ISSUE TITLE
[BotFramework Emulator] Command failed: 4294967295

### ISSUE THREAD

**Issue by EvergreenGOD** [Microsoft/BotBuilder#4028]
Hello everybody!
I've a problem when I launch my emulator..
It's checking for new version and just after that, I have a lot of errors written in red 

"Command failed: 4294967295 System.AggregateException: Une ou plusieurs erreurs se sont produites. ---> System.Net.WebException: Impossible de se connecter au serveur distant ---> System.Net.Sockets.SocketException: Aucune connexion n�a pu �tre �tablie car l�ordinateur cible l�a express�ment refus�e 127.0.0.1:8080 � System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult) � System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception) --- Fin de la trace de la pile d'exception interne --- � System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult) � System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result) � System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result) --- Fin de la trace de la pile � partir de l'emplacement pr�c�dent au niveau duquel l'exception a �t� lev�e --- � System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) � System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) � Squirrel.Utility.<LogIfThrows>d__38`1.MoveNext() --- Fin de la trace de la pile � partir de l'emplacement pr�c�dent au niveau duquel l'exception a �t� lev�e --- � System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) � System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) � Squirrel.FileDownloader.<DownloadUrl>d__3.MoveNext() --- Fin de la trace de la pile � partir de l'emplacement pr�c�dent au niveau duquel l'exception a �t� lev�e --- � System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) � System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) � System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) � Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext() --- Fin de la trace de la pile � partir de l'emplacement pr�c�dent au niveau duquel l'exception a �t� lev�e --- � System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) � System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) � Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext() --- Fin de la trace de la pile � partir de l'emplacement pr�c�dent au niveau duquel l'exception a �t� lev�e --- � System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) � System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) � Squirrel.Update.Program.<CheckForUpdate>d__8.MoveNext() --- Fin de la trace de la pile d'exception interne --- � System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) � System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) � System.Threading.Tasks.Task`1.get_Result() � Squirrel.Update.Program.executeCommandLine(String[] args) � Squirrel.Update.Program.main(String[] args) � Squirrel.Update.Program.Main(String[] args) ---> (Exception interne #0) System.Net.WebException: Impossible de se connecter au serveur distant ---> System.Net.Sockets.SocketException: Aucune connexion n�a pu �tre �tablie car l�ordinateur cible l�a express�ment refus�e 127.0.0.1:8080 � System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult) � System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception) --- Fin de la trace de la pile d'exception interne --- � System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult) � System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result) � System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result) --- Fin de la trace de la pile � partir de l'emplacement pr�c�dent au niveau duquel l'exception a �t� lev�e --- � System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) � System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) � Squirrel.Utility.<LogIfThrows>d__38`1.MoveNext() --- Fin de la trace de la pile � partir de l'emplacement pr�c�dent au niveau duquel l'exception a �t� lev�e --- � System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) � System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) � Squirrel.FileDownloader.<DownloadUrl>d__3.MoveNext() --- Fin de la trace de la pile � partir de l'emplacement pr�c�dent au niveau duquel l'exception a �t� lev�e --- � System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) � System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) � System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) � Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext() --- Fin de la trace de la pile � partir de l'emplacement pr�c�dent au niveau duquel l'exception a �t� lev�e --- � System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) � System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) � Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext() --- Fin de la trace de la pile � partir de l'emplacement pr�c�dent au niveau duquel l'exception a �t� lev�e --- � System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) � System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) � Squirrel.Update.Program.<CheckForUpdate>d__8.MoveNext()<--- {} "

I tried to uninstall and install the framework but the errors still there..
Does someone know this problem and could someone help me please?

**Comment by nwhitmont** [comment]
Thanks for reporting.

Please post Emulator issues on the BotFramework-Emulator project repository so the Emulator team will see it. Thanks!

Open new issue here -->
https://github.com/Microsoft/BotFramework-Emulator/issues/new
