### ISSUE TITLE
[Question] Managing state data

### ISSUE THREAD

**Issue by verdysh** [Microsoft/BotBuilder#4029]
## Bot Info
SDK Platform: .NET
SDK Version: 3.12.2.4
Active Channels: Telegram
Deployment Environment: local development

## Issue Description
Hi!

When I debug a project, the following warning appears in the output window: "The Bot State API is being deprecated.  Please refer to https://aka.ms/yr235k for details on how to replace with your own storage.".

But I did not save any state data anywhere.
I read the section "Manage state data" in the documentation https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-state and decided to experiment a little.

One:
```cs
private async Task TestStateData(IDialogContext context, IAwaitable<IMessageActivity> result)
{
	var message = await result;
	var activity = (Activity)message;
	StateClient stateClient = activity.GetStateClient();
	BotData userData = await stateClient.BotState.GetUserDataAsync(activity.ChannelId, activity.From.Id);
	if (message.Text == "save")
	{
		string time = DateTime.Now.ToString();
		userData.SetProperty<string>("Time", time);
		await stateClient.BotState.SetUserDataAsync(activity.ChannelId, activity.From.Id, userData);
		context.PostAsync($"Save {time}");
	}
	else
	{
		string time = userData.GetProperty<string>("Time");
		context.PostAsync($"Saved value {time}");
	}
}
```

Two:
```cs
private async Task TestStateData(IDialogContext context, IAwaitable<IMessageActivity> result)
{
	var message = await result;
	if (message.Text == "save")
	{
		string time = DateTime.Now.ToString();
		context.PrivateConversationData.SetValue<string>("Time", time);
		await context.PostAsync($"Save {time}");
	}
	else
	{
		string time = context.PrivateConversationData.GetValue<string>("Time");
		await context.PostAsync($"Saved value {time}");
	}
}
```

In both cases, I get the same result (if not to say that in the first case an error occurs at some point "Exception: The data is changed", but the values are saved and extracted). Also in both cases a warning occurs "The Bot State API is being deprecated".

Questions:

1. I have not done anything explicitly to manage the state data. That is, as I understand, the mechanism of data storage at me now works by default. Where in this case are the data stored? I thought it was in the application's memory, but the saved data is available even after the debugging restart.

2. What should I do to prevent the warning above?

**Comment by nwhitmont** [comment]
@verdysh - The "state service deprecation warning" is just a warning, and can't be disabled. It has no affect on your code, its just a reminder to setup your own bot state service.

**Comment by verdysh** [comment]
@nwhitmont, with this question it is now clear, thank you!

It would be desirable to understand where saving state data (in case described above).

**Comment by fanidamj** [comment]
Closing the issue assuming it as resolved. Please reopen a new issue if it still persists.
