### ISSUE TITLE
[Question] PromptDialog.Choice text hidden

### ISSUE THREAD

**Issue by luisnatividade** [Microsoft/BotBuilder#4031]
## Bot Info
* SDK Platform:  .NET 
* Active Channels: Web Chat
* Deployment Environment: Azure Bot Service

## Issue Description
Text hidden in PromptDialog.Choice if is too big to fit in the dialog prompt. (see image above)

## Code Example
PromptDialog.Choice(context, this.onAnswerOptionsSelected, new List<string>() { "This is an example that you cannot read because is hidden.", "Example that fits." }, "Please choose an option.", "Not a valid option. Please choose an option.", 3, PromptStyle.Auto);

## Expected Behavior
I dont't want the text to be replace with "..." . Is there any way to make a new line if the text does not fit? 

I don't want to put a "\n" in the message, just want it to automatically make a new line if the text does not fit.

## Actual Results
![image](https://user-images.githubusercontent.com/7551721/34821108-8839a378-f6ba-11e7-9c11-964b404a128b.png)

**Comment by JasonSowers** [comment]
This is a limitation of prompts, there is not a way to make a new line.  You must design your choices to fit within the constraints.

**Comment by luisnatividade** [comment]
Is it possible to change the css files of the bot? Because deleting the "white-space: nowrap;" would solve the problem...

**Comment by JasonSowers** [comment]
WebChat is open source and fully customizable. A good place to start is over on the [WebChat Repo](https://github.com/Microsoft/BotFramework-WebChat).  Going to close this issue, but feel free to continue the conversation here if needed.

**Comment by luisnatividade** [comment]
@JasonSowers I'm using an iframe to include the bot on a webpage. Is it possible to change the css of a promptDialog?  Thanks in advance...

**Comment by JasonSowers** [comment]
Not in an IFrame.
