### ISSUE TITLE
[Question] How to replay previous conversation of a user?

### ISSUE THREAD

**Issue by vamzz1** [Microsoft/BotBuilder#4032]
## Bot Info
* SDK Platform:  Node.js 
* SDK Version:  3.13.1
* Active Channels:Emulator
* Deployment Environment:  local development with Emulator 

## Issue Description 
Hello, For my use case, I need to replay the conversation a user already had with the user before resuming the conversation. Can anybody point me to a solution to achieve this?

**Comment by JasonSowers** [comment]
I see that right now you are using the emulator.  What channel(s) do you plan on using for your bot?

**Comment by nwhitmont** [comment]
It's not a built-in feature of Bot Framework SDK. You would need to design a custom solution.
