### ISSUE TITLE
[Question] How to disable inputs from previous choices?

### ISSUE THREAD

**Issue by vamzz1** [Microsoft/BotBuilder#4033]
## Bot Info
* SDK Platform: Node.js
* SDK Version: 3.13.1
* Active Channels: Emulator
* Deployment Environment: local development with Emulator

## Issue Description
Hello, the open items when using `Prompts.choice` are not disabled in subsequent conversations.

## Reproduction Steps
1. Send a prompts.choice.
2. Send another prompt.
3. The open items of 1st prompt are clickable after the 2nd prompt is sent.

## Expected Behavior
The open items from the 1st prompt should be disabled so that they won't effect the subsequent prompts.

**Comment by nwhitmont** [comment]
@vamzz1 - It's not currently a feature. You would need to design a custom solution.

**Comment by JasonSowers** [comment]
You may want to look into [suggested actions](https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-send-suggested-actions) if this is the behavior you are looking for.  They do not persist beyond when the user makes a selection.
