### ISSUE TITLE
[Feature Request] Provide access to session object for bot events

### ISSUE THREAD

**Issue by harshithkashyap** [Microsoft/BotBuilder#4035]
## Bot Info
* SDK Platform: Node.js
* SDK Version:  3.12.0
* Active Channels: Direct Line
* Deployment Environment: Azure App Service

## Issue Description
When backchannel events are registered with botbuilder, `session` object parameter is missing from bot listener.
```javascript
bot.on('event', event => console.log(event.name));
``` 

We use DirectLine backchannel to send events in the background such as user's timezone, preferences etc. Unlike the following bot dialog code snippet which is used with messages, `session` object is missing with events listener callback function.

```javascript
bot.dialog('greetings', [
    session => {
        builder.Prompts.text(session, 'Hi! What is your name?');
    }
]);
```

## Expected Behavior
1. Provide access to session object such as 
```javascript
bot.on('event', (session, event) => console.log(event.name));
```
**Or**

2. Provide methods to access/modify `session.userData` object via Session class.

**Comment by JasonSowers** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
