### ISSUE TITLE
[Question] Why am I getting: "There was an error sending this message to your bot: HTTP status code InternalServerError"?

### ISSUE THREAD

**Issue by zell12** [Microsoft/BotBuilder#4036]
## Bot Info
* SDK Platform:  .NET
* SDK Version:  3.12.2.4
* Active Channels:  Skype
* Deployment Environment:  Auzure Bot Service, Azure App Service, local development with Emulator?

## Issue Description
Built a simple translator (added API references to google translate) using the Basic template.
Everything works fine in the emulator but when I published the bot to Azure and registered the bot, testing it on the Web chat would always return an (HTTP status code InternalServerError) 'Sorry my bot code is having an issue'.
Things I already checked:
- Microsoft AppId and Password are correctly configured in Web.config
- I'm on Free Trial and have Free App Service plans. One other thing I'm looking into is an SSL authentication issue, however..
   I have two other bots (Qna and Luis) that were both created completely in Azure portal and are on Free App Service Plan, and **both works fine**. Never had this problem on both.

## Code Example
Nothing in particular being suspected. Most of the codes are from the template just added a few lines for the Google API call (authentication is correctly configured).

## Reproduction Steps
1. Build a basic Bot Application in Visual studio using .NET SDK
2. Publish app to Azure.
3. Register bot.
4. Test in Web Chat or Emulator (connecting on https endpoint with appid and password).

## Expected Behavior
Bot should be successfully sending responses as on the emulator when connected **locally**

## Actual Results
Testing it on the Web chat would always return an (HTTP status code InternalServerError) 'Sorry my bot code is having an issue'.

**Comment by nwhitmont** [comment]
Hi @zell12 - Can you share your code that reproduces the issue? Thx

**Comment by zell12** [comment]
Hey,
Just to update, it turns out that the one causing the issue is really the api call, specifically the authentication part. I had to programmatically set the the google API default credential which is set as environment variable on my local machine.
Closing this thread.
