### ISSUE TITLE
[Proactive Messages] Can Bot initiate a new conversation, knowing only the Skype login of the recipient?

### ISSUE THREAD

**Issue by Arpanx** [Microsoft/BotBuilder#4040]
Can Bot initiate a new conversation, knowing only the Skype login of the recipient?
- Suppose that the bot and the recipient added each other in contacts
I can not find an example where the bot itself was the initiator of a new dialogue.
I need the bot not to wait for activity from the user, but the first to take the initiative.
Is it possible to do this?

**Comment by JasonSowers** [comment]
Take a look at [this documentation](https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-proactive-messages) (Also available for node [here](https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-proactive-messages)). What you are looking for is referred to as proactive messaging.  There are also samples [here](https://github.com/MicrosoftDX/botFramework-proactiveMessages)

**Comment by nwhitmont** [comment]
@Arpanx - For reference, are you using .NET or Node.js SDK for BotBuilder?

**Comment by JasonSowers** [comment]
I'm not sure I fully understand your question.  
  
If you lost all your data you would not be able to send a proactive message.  You may be able to grab that data back when the user rejoins the conversation via the conversation update activity. It's kind of hard to answer this question without seeing your code and knowing how your app is set up.  For your second question, I think the answer is no.  If the user removes the bot from skype you will not be able to send a proactive message.
