### ISSUE TITLE
[Question] Getting 404 on BotConnectorClient on deployed app, works locally in emulator?

### ISSUE THREAD

**Issue by shaunmccann-87** [Microsoft/BotBuilder#4041]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.12.2.4
* Active Channels: Facebook
* Deployment Environment: Azure App Service

## Issue Description
Trying to use bot connector but getting 404 when deployed, works finally in emulator locally.

## Expected Behavior
Message to appear in conversation.

## Actual Results
404 resource not found

**Comment by JasonSowers** [comment]
Please provide your code so we can better assist you.

**Comment by nwhitmont** [comment]
Hi @shaunmccann-87 - Can you share your code that produces the problem?

**Comment by shaunmccann-87** [comment]
Hi @nwhitmont I've resolved it was my mistake to be honest. I had assumed that the service url was my API when in actual fact its of course the bot framework endpoint specific to the service type Facebook etc.
