### ISSUE TITLE
[.Net SDK, Emulator, Question] Testing in Emulator & getting error - POST Refresh access token failed with status code: 407?

### ISSUE THREAD

**Issue by tinuCoder** [Microsoft/BotBuilder#4042]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.12.2.4
* Emulator Version: 3.5.35

## Issue Description
POST Refresh access token failed with status code: 407

Need help in solving this issue.
I have already checked my system is synced with Bot timing, Version of Bot sdk is latest and Emulator is also latest version still getting this issue

I also created MS Id and password twice and tried. The issue still persists.

![image](https://user-images.githubusercontent.com/25457761/34915867-2687fa1e-f947-11e7-8cf9-d0cadd589cf6.png)

**Comment by pankajdmishra** [comment]
Can someone help with this?
Anybody who has came across the same issue and resolved it

**Comment by nwhitmont** [comment]
Hi @pankajdmishra - Can you share your bot code that is causing the problem? Thx

**Comment by pankajdmishra** [comment]
Hi I have this code in message controller
    [BotAuthentication]
    public class MessagesController : ApiController
    {
        /// <summary>
        /// POST: api/Messages
        /// Receive a message from a user and reply to it
        /// </summary>
        public async Task<HttpResponseMessage> Post([FromBody]Activity activity)
        {
            ConnectorClient connector = new ConnectorClient(new Uri(activity.ServiceUrl));
            if (activity.Type == ActivityTypes.Message)
            {
                await HandleUserMessage(activity);
            }
            else
            {
                HandleSystemMessage(activity);
            }
            var response = Request.CreateResponse(HttpStatusCode.OK);
            return response;
        }

When i am trying to connect the code with Emulator by providing my credentials in Emulator it is giving Refresh access token error 407.

**Comment by pankajdmishra** [comment]
hi,

I am facing this issue intermittently. I mean when i run my application and refresh emulator it throws
"Refresh access token failed with status code: 407" multiple times.
Later it gives the response. Please see below screen shot for ref. 
I tried everything but still this issue persists.

Awaiting solutions from the experts please help me on this.

![image](https://user-images.githubusercontent.com/25457761/35674468-34cbeafc-075e-11e8-92ba-e9501869b8a9.png)

**Comment by pankajdmishra** [comment]
hi there,

Is there any solution for this one?

I am still facing this issue and unable to understand why is it happening.

I believe "BotAuthentication" code is failing to authorize.

**Comment by cleemullins** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues


For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botbuilder-channels/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
