### ISSUE TITLE
[Skype Web Control] Bug? Not loading on Chrome and Firefox?

### ISSUE THREAD

**Issue by wacton** [Microsoft/BotBuilder#4044]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.12.2.4
* Active Channels: Skype, Web
* Deployment Environment: Azure bot service, web app hosted on Azure VM.

## Issue Description
The Skype Web control seems to have an issue on Chrome (63.0.3239.132) and Firefox (57.0.3).
The chat window starts to load, refreshes twice and then ends up showing a white rectangle as below:
![image](https://user-images.githubusercontent.com/2299141/34926037-0ffdc2b4-fa01-11e7-89c5-b7f6f12016b0.png)
This is the console log: 
[SkypeWebControl.log](https://github.com/Microsoft/BotBuilder/files/1630290/SkypeWebControl.log)

The same bot works fine in the Web Control on Edge (41.16299) however:
![image](https://user-images.githubusercontent.com/2299141/34926071-485302f0-fa01-11e7-9904-87575379fc06.png)

This also only appears to happen on browsers where the Web Control scripts have not been previously cached. Opening an incognito window still shows this issue.

## Code Example
```
<html>
    <body style="background-color:black">
        <span class="skype-button bubble " data-bot-id=""></span>
        <script src="https://swc.cdn.skype.com/sdk/v1/sdk.min.js"></script>
    </body>
</html>
```

## Reproduction Steps
1. Add Skype Web Control to a page
2. Make sure it's not a cached 
3. Open in Chrome, Firefox and Edge

## Expected Behavior
The chat window to load and users be able to send messages

## Actual Results
Shows a white rectangle

**Comment by nwhitmont** [comment]
@wacton - Thanks for reporting - I will forward this information to the Skype Web Control team for further investigation.

**Comment by brene** [comment]
@wacton I'm the PM for Skype Web Control. We unfortunately cannot reproduce this. Can you provide us your bot's ID, so we can test it against that as well?

**Comment by wacton** [comment]
@brene bot ID is **ce0f5873-7d96-477b-94d8-105d6a3923b1**

It seems to be a bit sporadic when I test it. 
Testing it again now, I initially got it to load on Firefox, then opened Firefox in a private window and it doesn't load. Went back into normal mode with Firefox and cleared all site data & cache. Reloaded the page with the bot, I now see the same issue present itself again.

**Comment by Rakin061** [comment]
In chrome... Here's my error log:-

`Failed to load resource: net::ERR_SPDY_INADEQUATE_TRANSPORT_SECURITY
services-bundle.min.js:1 Uncaught (in promise) Object
lwc-chat-index.min.html:1 Uncaught (in promise) Object
lwc-chat-index.min.html:1 Uncaught (in promise) Object
swc.cdn.skype.com/v/0.49.11/calling-bundle.min.js:1 Trouter [Trouter] open connection
services-bundle.min.js:1 Uncaught (in promise) Object
lwc-chat-index.min.html:1 Uncaught (in promise) Object
swc.cdn.skype.com/v/0.49.11/calling-bundle.min.js:1 Trouter [Trouter] auth required
swc.cdn.skype.com/v/0.49.11/calling-bundle.min.js:1 Trouter [Trouter event] authentication failed
swc.cdn.skype.com/v/0.49.11/calling-bundle.min.js:1  trouter telemetry event: trouterinit {"type":"authenticationFailed","registrationId":"4c014f06-7f0c-d26b-8812-443aed05438e","connectionId":"uSoCADFYnMI2V8D7B874_tEq","connectedClientId":"V8D7B874_tEq"}
services-bundle.min.js:1 Uncaught (in promise) Object
chat-bundle.min.js:13 Uncaught (in promise) TypeError: Cannot read property 'then' of undefined
    at chat-bundle.min.js:13
    at <anonymous>
lwc-chat-index.min.html:1 Uncaught (in promise) Object
swc.cdn.skype.com/v/0.49.11/calling-bundle.min.js:6 Uncaught (in promise) TypeError: Cannot read property 'status' of null
    at Array.f (swc.cdn.skype.com/v/0.49.11/calling-bundle.min.js:6)
    at e.publish (swc.cdn.skype.com/v/0.49.11/calling-bundle.min.js:6)
    at swc.cdn.skype.com/v/0.49.11/calling-bundle.min.js:6
    at <anonymous>`

**Comment by brene** [comment]
@Rakin061 @wacton do you mind telling me if your website is running on HTTPS or HTTP? We are still having trouble reproducing the error.

**Comment by Rakin061** [comment]
Hello @brene   

Thanks for your reply.  Actually my website is running on HTTP.

Here's the link :  http://job.erainfotechbd.com:8888/hr/f?p=100:1:2524620618320548

Downside, there is the skype-rounded button named. "Chat with ERA HRM" 

My Google Chrome Version:-  63.0.3239.132 (Official Build) (32-bit)
My Firefox Version:- 57.0.4 (32-bit)

Hopefully, you could reproduce if you use the identical version of the above mentioned browsers.

And, the Web control embed code:-

`<span class="skype-button rounded"
	data-bot-id="404916f0-9fa1-4003-9d26-8e99978614c6" data-text="Chat with ERA HRM"></span> 

	<script src="https://swc.cdn.skype.com/sdk/v1/sdk.min.js"></script>`


Thanks in advance.

**Comment by wacton** [comment]
@brene the website where it normally runs is https, which is where we first picked up the issue.

For my testing locally to exclude any other of our code I just created a basic html page and opened it directly in a browser window. The html page contains only the code referenced in my first post.

**Comment by wacton** [comment]
@brene I've added my test page to a public site.
You can hit it with either http or https:
[http://devwww.appsforops.com/Testbot.html](url) or [https://devwww.appsforops.com/Testbot.html](url)

I can sometimes get it to work when **not** in Incognito/Private browser window. But it always happens when I open a new Incognito window.

**Comment by brene** [comment]
Hm... that's really weird. I just tried it and I can't seem to repro.

**Comment by brene** [comment]
Can you make a screenshot with the network tag open? This could help us out.

**Comment by wacton** [comment]
Sure. Here is the screenshot. 

![image](https://user-images.githubusercontent.com/2299141/35079779-b279a5ea-fc5d-11e7-8c84-cec5a6ecaf91.png)

**Comment by Rakin061** [comment]
Here's my screenshot as well. It is hosted in a Real Ip shown in the image and will be always running.

Link:- http://202.40.190.116:81/ocas/

![skype_frame](https://user-images.githubusercontent.com/27331118/35080992-7e175a4e-fc3b-11e7-914a-1c530695a64b.PNG)

**Comment by chathudev** [comment]
For my bot if i am logged in to skype with the webchat, the webchat works fine. Otherwise webchat does not load. Both in http and https.

**Comment by Rakin061** [comment]
I just checked in Chrome and Firefox clearing caches and browsing data and I found everything fairly Okay!! 

Any news from your end ??  @wacton ??
 
So, @brene  Have you been able to reproduce the problem and fix this problem as well ?  If yes, then I would love to notify all my clients that the problem has been solved.

**Comment by brene** [comment]
@Rakin061 @chathudev @wacton we have rebooted some of our services, where we believe the root cause could be. Can you check again?

**Comment by brene** [comment]
This one is very tricky to debug as sadly no one from the team can reproduce this.

**Comment by wacton** [comment]
@brene I tested it on my side now and can no longer reproduce it. I've asked other members on my team just to confirm they are no longer seeing it either.
It looks like the rebooting of your services fixed it, will confirm once I hear back from them.

**Comment by brene** [comment]
Awesome! Please reopen this when this is still an issue.

**Comment by wacton** [comment]
Just had confirmation from the rest of my team, everything back in working order.
Thanks for your help @brene

**Comment by chathudev** [comment]
Working now

**Comment by Rakin061** [comment]
Everything works absolutely fine !! I just checked back everything once again!

Thanks for your assistance @brene

**Comment by XIAOXIAOSIYU** [comment]
Hi guys: @brene  @wacton @chathudev @Rakin061 , I'm facing the most exactly same question right now, the difference is I'm using Skype User Id instead Bot Id ( I already posted on [StackOverflow](https://stackoverflow.com/questions/49184316/integrating-the-skype-web-control-into-your-own-website)) but got nothing yet!

Please take a look and any ideas, suggestions will be appreciated!!! 
THANKS!

**Comment by Rakin061** [comment]
@XIAOXIAOSIYU 

I just checked my bot service with Skype web control. It's working fine. 

You could generate another new script of the SDK from the web control generator in the similar and then embed the code again in your website. This worked for me at a earlier time. 

Thanks!!

**Comment by XIAOXIAOSIYU** [comment]
Thanks for the really quick reply!

I may didn't clarify myself the question back there, I didn't try the Bot service, I'm using Skype User Id instead.
And I've regenerated the script a few times :-) sometimes, the Skype window will pop up, sometimes not!
But even the window pop up, the Video Call button never worked!

Does the SDK matters in my case BTW? I even don't have a chance to use it.

THANKS!

HAVE A GOOD WEEKEND!!
----- 原始邮件 -----
发件人：Rakin061 <notifications@github.com>
收件人：Microsoft/BotBuilder <BotBuilder@noreply.github.com>
抄送人：Jack Zhao <YIHIU@SINA.COM>,  Mention <mention@noreply.github.com>
主题：Re: [Microsoft/BotBuilder] [Skype Web Control] Bug? Not loading on Chrome and Firefox? (#4044)
日期：2018年03月10日 02点37分

@XIAOXIAOSIYU
I just checked my bot service with Skype web control. It's working fine.
You could generate another new script of the SDK from the web control generator in the similar and then embed the code again in your website. This worked for me at a earlier time.
Thanks!!

&mdash;

**Comment by Rakin061** [comment]
@XIAOXIAOSIYU 

> I may didn't clarify myself the question back there, I didn't try the Bot service, I'm using Skype User Id instead

No. Your question was absolutely clear that you're trying with Skype User ID. But the code generation is same regardless of User ID or Bot. My intention was to make the regeneration of the code which you have already performed few times as you mentioned. So, problem might be resides in their root services.

> Does the SDK matters in my case BTW?

I actually have no idea about their SDK and it's functionalities. But, I just tested your service for your stackoverflow question. There have 2 errors in the console log and both of them are from the skype root services. So, at this moment you have nothing to do but to wait for them to check your id, reproduce your problem and solve it. 

Good Luck!!

**Comment by XIAOXIAOSIYU** [comment]
@Rakin061 
I noticed the errors in the console log and spoke to the Skype Support Team (I guess they are) twice. they couldn't help me more but reboot the Skype services......

I'm stuck here for weeks and for now, almost despaired!!!

**Comment by XIAOXIAOSIYU** [comment]
@brene I know you are the PM for Skype Web Control, Still waiting for your help!!!

**Comment by brene** [comment]
@XIAOXIAOSIYU apologies for the delay. 
Can you confirm that this is your issue: 
![image](https://user-images.githubusercontent.com/4989523/37435291-f00b7fc4-279f-11e8-806b-169ce97dc00f.png)
and not this (which is what this thread is actually about):
![image](https://user-images.githubusercontent.com/4989523/37435329-12a7afc6-27a0-11e8-9abe-e107a4af9d45.png)
Can you give me a test site that I can redirect to our team? Can you also double check if your website runs on HTTPS (not HTTP). That could have been an issue.

**Comment by XIAOXIAOSIYU** [comment]
@brene Thanks for real quick replay!

1. The first screenshot is mine! 
2. The test site is [here](http://skype.jackzc.com) and NO, I don't have an HTTPS certification 

Jack

**Comment by brene** [comment]
@XIAOXIAOSIYU that's exactly the issue then. All calls must be facilitated through HTTPS. This is a security guideline that needs to be enforced.

**Comment by XIAOXIAOSIYU** [comment]
@brene All right, I'll try to get a HTTPS certification and let you know the result.

THANKS!!!

**Comment by XIAOXIAOSIYU** [comment]
@brene Hi Brene, this is Jack, I just regenerate the code from 'Skype Web Generate' and put them into another website which covered by SSL Certificate:[ see here please](https://www.coolerdepotusa.com/aboutus)
This time when I clicked on the 'Video Call' icon, nothing happened!
In the beginning, I thought it was because I don't have a Camera installed on my desktop, and then I turn on my laptop which is the Camera included, they are the same.

And I tried both Chrome[Version 65.0.3325.162 (Official Build) (64-bit)] and Edge[Microsoft Edge 41.16299.248.0], they are the same too.

**Comment by XIAOXIAOSIYU** [comment]
@brene Any updates?

**Comment by brene** [comment]
Can you confirm that the other user is online? You can only call another user if they are online. I just tried it myself and it looks like the user on that site is offline.

**Comment by XIAOXIAOSIYU** [comment]
@brene I'm online! this is another Skype account I've registered before.

**Comment by XIAOXIAOSIYU** [comment]
@brene And I've tested my both Skype account through [Web Skype](https://web.skype.com/en/), everything works fine!

**Comment by brene** [comment]
@XIAOXIAOSIYU can you give me any logs that are in there? I can't repro this.

**Comment by XIAOXIAOSIYU** [comment]
@brene I'm not sure that I understand you correctly, is this what you want?
![logs](https://user-images.githubusercontent.com/5882117/37497062-4cc09a32-2873-11e8-9fd1-c5407ee5d78c.jpg)

**Comment by XIAOXIAOSIYU** [comment]
@brene If not, would you mind give me a little more tips, please?

**Comment by brene** [comment]
@XIAOXIAOSIYU we're investigating this further but I can't promise a fix date yet as we're not sure what's causing it.

**Comment by XIAOXIAOSIYU** [comment]
@brene  It's that possible that you can get this done before the end of this month? I already spent 3 weeks on Web Skype try to make it works because I really love it. If not, please let me know, I have no choice but try WebRTC.

**Comment by XIAOXIAOSIYU** [comment]
@brene  Hope you don't mind If any words I said that makes you feel uncomfortable, I really not good at talk, especially with my limited English :-(. All I want is make Web Skype works in my project, already behind my schedule!!!

**Comment by cmnisal** [comment]
![image](https://user-images.githubusercontent.com/8001789/37928109-6831a704-3159-11e8-84f1-a2cf2f2bcbbe.png)
New messages are coming on the top of chat

**Comment by EricDahlvang** [comment]
@cmnisal Please open a new issue https://github.com/Microsoft/BotBuilder/issues/new

**Comment by bbrucechen** [comment]
i wonder is skype web control still working?my app project use this thing but it's not work anymore.thanks for you reply

**Comment by bbrucechen** [comment]
> @wacton I'm the PM for Skype Web Control. We unfortunately cannot reproduce this. Can you provide us your bot's ID, so we can test it against that as well?

hello，i wonder is skype web control still working?my app project use this thing but it's suddenly not work anymore.any help would be appreciated
