### ISSUE TITLE
[Skype] How to receive all messages in group chats?

### ISSUE THREAD

**Issue by 2670207** [Microsoft/BotBuilder#4046]
## Bot Info
* SDK Platform:  Node.js 
* SDK Version: 
* Active Channels: Skype

## Issue Description
In chat rooms 1:1, messages come in successfully. In group chats you can get the message only **@bot_name**.

How to receive all messages in group chats?
What are the solutions to this problem?

**Comment by nwhitmont** [comment]
@2670207 - It's not a feature for privacy reasons. 

Per https://support.skype.com/en/faq/FA34698/can-i-add-skype-bots-to-a-group-conversation

>**Can I add Skype bots to a Group conversation?**
>Yes. As long as a bot is enabled for groups, you can add it to group chats the same way you add people. You can check the list of available bots to see if they are group enabled. **Bots in a group chat only receive messages directly addressed to them.**

**Comment by 2670207** [comment]
How to develop a bot company sameroom.io. BridgeBot can receive all messages from the group chat, redirect to another chat group

**Comment by skravtsov** [comment]
+1. Sameroom bot can do it why mine can not?

**Comment by ChmilevFA** [comment]
> +1. Sameroom bot can do it why mine can not?
Does anybody know answer?

**Comment by EricDahlvang** [comment]
The only explanation is that Sameroom is not using the Microsoft Bot Framework.

**Comment by skravtsov** [comment]
Visit this project http://evergreen.team/en/box-producs/konnektor.html for more details. Maybe it will explain to you how it can be possible.

**Comment by palmerabollo** [comment]
Konnektor uses [SkPy](https://pypi.org/project/SkPy), an **unofficial** Python library for interacting with an **undocumented** Skype HTTP API. It uses a regular Skype user ([username + password](https://github.com/evergreen-it-dev/Konnektor/blob/master/skype_listener_prod.py#L30-L31)) to connect to Skype. It is not a bot. This is the reason why they can read all messages in a group. It's a clever solution but quite fragile IMO.
