### ISSUE TITLE
[Question] How send message with local file as base64 encoded PDF attachment?

### ISSUE THREAD

**Issue by Ma3yTa** [Microsoft/BotBuilder#4047]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.12.2.4
* Active Channels: Skype, Telegram, Facebook, Slack
* Deployment Environment: Azure Bot Service

## Issue Description
``UploadAttachmentAsync`` works correctly only in Slack. In other channels (Telegram, Facebook), the file is broken and with Skype doesn't work.

## Code Example
```csharp
using (var connector = CreateConnector(new Uri(serviceUrl)))
{
                var attachments = new Attachments(connector);
                var response = await attachments.Client.Conversations.UploadAttachmentAsync(
                    conversationId,
                    new AttachmentData
                    {
                        Name = fileName,
                        OriginalBase64 = content,
                        Type = mimeType
                    });
}
```
On skype channel we got error:
```
Microsoft.Rest.HttpOperationException: Not Found
   at Microsoft.Bot.Connector.ErrorHandling.<HandleErrorAsync>d__2`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Connector.ConversationsExtensions.<UploadAttachmentAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by Ma3yTa** [comment]
Hi @msft-shahins , Could you please check?

**Comment by nwhitmont** [comment]
Hi @Ma3yTa - Where is the image hosted? Are you trying to send an image attachment from a local file on your bot's server - or from a publicly accessible URL?

**Comment by Ma3yTa** [comment]
Hi @nwhitmont , I sent pdf file generated on the fly. The document isn't available by URL.

**Comment by Ma3yTa** [comment]
@nwhitmont 
in Slack channel all works fine:
![Slack](https://i.gyazo.com/2d4c49e4ce5162ce9fda6adec2d0610b.png)

in Telegram and Facebook file is corrupted:
Telegram
![Telegram](https://i.gyazo.com/d0d3724181da43beab61654c7b58f855.png)

Facebook
![Facebook](https://i.gyazo.com/2a67f158b2cc66fd14d6a17f4003a732.png)

In Skype we got ``Microsoft.Rest.HttpOperationException: Not Found``

**Comment by nwhitmont** [comment]
@Ma3yTa - How big is your PDF file? More than 4mb?

**Comment by Ma3yTa** [comment]
@nwhitmont File size 33 KB. I tried both "application/pdf" and "application/octet-stream".

**Comment by Ma3yTa** [comment]
@nwhitmont my pdf file
[BORAT CAPITAL PTY LTD   Company Profile.pdf](https://github.com/Microsoft/BotBuilder/files/1632799/BORAT.CAPITAL.PTY.LTD.Company.Profile.pdf)

**Comment by nwhitmont** [comment]
See discussion of Skype JWT token config for file attachments here: https://github.com/Microsoft/BotBuilder/issues/3623

https://github.com/Microsoft/BotBuilder/issues/3623#issuecomment-337820207

>There is a note in the sample at https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/core-ReceiveAttachment that states:

>Note: The Skype and Microsoft Teams attachment URLs are secured by JwtToken; you should set the JwtToken of your bot as the authorization header for the HTTP GET request your bot initiates to fetch content. Below is the sample code that temporarily works around this issue and set the JwtToken on the HTTP request. You should be careful when you send the bot's JwtToken to a third party server and should always make sure to send it to trusted parties

**Comment by nwhitmont** [comment]
Relates to (discussion): https://stackoverflow.com/questions/43866197/bot-framework-post-pdf-file

**Comment by Ma3yTa** [comment]
@nwhitmont I debugged locally thru ngrok and looks like there is some problem with uploading attachments for Skype. 
The first request for Skype, second for Telegram.
![](https://i.gyazo.com/6e66f6c984173a77461989148160a17c.png)

**Comment by JasonSowers** [comment]
I got the following code working in telegram, not working on skype.  I will keep looking into this.

```cs
        private async Task MessageReceivedAsync(IDialogContext context, IAwaitable<object> result)
        {

            var reply2 = await result as Activity;
            Activity reply = reply2.CreateReply();
            string base64String;
            string image64;
            Attachment qwerty;
            try
            {
                Byte[] bytes = File.ReadAllBytes("C:/Users/v-jassow/Documents/Nachos.pdf");
                base64String = Convert.ToBase64String(bytes);
                image64 = "data:application/pdf;base64," + base64String;
                reply.Attachments = new List<Attachment>();
                qwerty = new Attachment(contentType: "application/pdf", content: image64);
                reply.Attachments.Add(qwerty);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
            await context.PostAsync(reply);
        }
```

**Comment by JasonSowers** [comment]
I have an email out to the Skype team asking about it.  Will update when I talk to them.

**Comment by JasonSowers** [comment]
Still waiting on a response, pinged the skype bot team again today.

**Comment by JasonSowers** [comment]
I got word from Skype, sending attachments such as PDFs is not supported in bots yet due to security concerns.  Skype can only send media attachments such as audio and video.  Unfortunately, you will need to find another solution

**Comment by Ma3yTa** [comment]
@JasonSowers thanks.

**Comment by xiaolangxyz** [comment]
I'm a newbie. I'm also using UploadAttachmentAsync. It works. But I still have some questions. I think this method would send the file to server,right? When will it be deleted? Do I need delete it after download it by myself?
