### ISSUE TITLE
[.Net SDK, Skype for Business]  How to know the status of Skype user on Proactive message sending?

### ISSUE THREAD

**Issue by band888888** [Microsoft/BotBuilder#4048]
There is a same question from my side. We intergrate the bot into skype for business. When we send the Notification message in a specified time from a bot to a skype user, how could we know the user whether online or offline? Any hits for this ?

With .Net bot.

Similar question with the Node.js. [3126](https://github.com/Microsoft/BotBuilder/issues/3126)

**Comment by tkX85** [comment]
This may help you:
https://github.com/sharepoint/sp-dev-fx-webparts/tree/master/samples/js-skype-status

**Comment by band888888** [comment]
@tkX85  thank you very much for your suggestion.
After go through the project i aware of that is use Skype web sdk.

Then i follow the project you suggestion:
https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/js-skype-status
To build the application on the Azure. 

After that i create a new html page and code as below;

 var config = {
        apiKey: 'a42fcebd-5b43-4b89-a065-74450fb91255', // SDK
        apiKeyCC: '9c967f6b-a846-4df2-b43d-5167e47d81e1' // SDK+UI
    }; 

    Skype.initialize({ apiKey: config.apiKey }, (api) => {
        var app = new api.application;
        app.signInManager.signIn({
            username: 'ABC@ABC.COM',
            password: 'XXX',
            client_id: 'XXXXX-d147-4e22-XXXX-XXXXX',
            cors: true,
            origins: ["https://webdir.online.lync.com/autodiscover/autodiscoverservice.svc/root"],
            redirect_uri: 'http://localhost:9099/Home',
        }).then(() => {
            resolve(app);
        }, err => {
            Log.error(Constants.ErrorCategory, new Error(`cannot sign in ${err}`));
            location.assign("https://login.microsoftonline.com/common/oauth2/authorize?response_type=token" +
                "&client_id=xxxxxxxxxxx"+
                "&redirect_uri=" + location.href +
                "&resource=https://webdir.online.lync.com");
            reject(err);
        });
    });

username password use my local information and the clientID use the azure application ID.

however it could not login with the code. Error as below:
![default](https://user-images.githubusercontent.com/30857232/35323321-0bd9d49c-0128-11e8-9a70-6bca64316fb7.png)

![default](https://user-images.githubusercontent.com/30857232/35323344-1aa4b082-0128-11e8-9e0f-d0d546e97963.png)

Grateful if you could give any advise.

**Comment by cleemullins** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues


For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botbuilder-channels/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
