### ISSUE TITLE
[.Net SDK, Question] Unable to test with Emulator after publishing code to Azure?

### ISSUE THREAD

**Issue by amthomas46** [Microsoft/BotBuilder#4049]
## Bot Info
* SDK Platform: .NET
* Active Channels: WebChat
* Deployment Environment: azure bot service

## Issue Description
after publishing code to Azure Bot Service, it works in WebChat through Bot Service, but then when i put the endpoint url (which works generally) with the CORRECT app id and app password, it fails to connect in Emulator.

## Code Example
14:19:24] -> POST 401 [conversationUpdate] 
[14:19:24] Error: The bot's MSA appId or password is incorrect. 

## Reproduction Steps
1. publish a bot to azure bot service
2. open emulator
3. connect with endpoint url and password and id 

## Expected Behavior
to be able to connect and interact with the published bot within the emulator

## Actual Results
not able to

**Comment by JasonSowers** [comment]
Is it working on any other channel like webchat?

**Comment by amthomas46** [comment]
yes - so i found that the work around is to not only setup ngrok (which I already had) but also to check both of the boxes - the critical one appears to be the "use 1.0 auth tokens". but nowhere in the documentation does it state that you need to do this or explain why

**Comment by EricDahlvang** [comment]
"use 1.0 auth tokens" only needs to be checked if you are using an old version of bot builder.  Make sure you upgrade to the latest version: https://www.nuget.org/packages/Microsoft.Bot.Builder/
