### ISSUE TITLE
[WebChat] How to customize my webchat?

### ISSUE THREAD

**Issue by MadhuAcc12** [Microsoft/BotBuilder#4051]
I want to remove the the Bot name and time after each message is sent by the bot. Is it possible to do so? Where can I make the change so that both the name and time of the bot is removed? Thanks in advance.

**Comment by jochem4207** [comment]
@MadhuAcc12 I don't expect this to be a thing. That's why i'm switching over to the Direct Line APi to have a fully configured UI. See my most recent issue when you going to start with it.

**Comment by nwhitmont** [comment]
Hi @MadhuAcc12 - You can find instructions for how to customize and deploy your own version of the WebChat control on the project's repository here:

https://github.com/Microsoft/BotFramework-WebChat

If you have additional WebChat questions, please ask them on the WebChat project repository and the WebChat team will assist you.
