### ISSUE TITLE
[.Net SDK, Direct Line] broken for dev.botframework.com?

### ISSUE THREAD

**Issue by jochem4207** [Microsoft/BotBuilder#4052]
## Bot Info
* SDK Platform: .NET
* Active Channels: DirectLine
* Deployment Environment: dev.botframework.com (side note: when is migrating actually possible for all types of bots?)

Tested local w/ emulator, tested with published bot in Azure. 

## Issue Description
DirectLine functionality is broken for bots still on dev.botframework.com, can't get connection

1) Open an old bot, since creating new is broken
2) Copy direct line id
3) Boot up the solution: https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/core-DirectLine
4) Copy Id in the correct settings
5) Run the client
6) Get no Connection (yes i'm pretty pissed after wasting 6 hours)

## Code Example
```
            var tokenResponse = await new DirectLineClient(directLineSecret).Tokens.GenerateTokenForNewConversationAsync();

```
This is actually enough to make it dead.

Steps to FIX:
1) Create bot on the new Azure platform
2) do step 4-6
3) done

## Expected Behavior
A working direct line message 

## Actual Results
A null pointer
Angry developer
6 hours of wasted time

**Comment by jochem4207** [comment]
For a coworker it worked just fine

**Comment by fanidamj** [comment]
Can you please let us know if the issue still persists?
