### ISSUE TITLE
[.Net SDK, Cortana] Channel doesn't trigger OAuth2 flow when deployed to group?

### ISSUE THREAD

**Issue by hpksp** [Microsoft/BotBuilder#4053]
## Bot Info
* SDK Platform: .NET Framework
* SDK Version: 3.12.2.4
* Active Channels: Skype
* Deployment Environment: Azure App Service
* App Id: 4b33606b-c9d0-4ef7-82eb-7b458cd609e3

## Issue Description
I've configured OAuth2 authentication flow for cortana channel and it's working fine when deployed to self. Once it's deployed to group, Cortana skips the authentication step and send the user query directly to the message endpoint (which is hosted on azure). When the message is received at the web api the AuthorizationToken is not found since Cortana skipped the auth step. 

## Expected Behavior
Cortana must trigger the OAuth2 authentication step before sending query to the message endpoint when the logged in user (MSA) is new or the cached token is not available.

**Comment by JasonSowers** [comment]
can you please share your code so we can better assist you?

**Comment by hpksp** [comment]
@JasonSowers I'm sorry, I cannot share the code. It's a property of the company that I'm working for. However, if you look at the nature of the issue, this is not something related to my bot code. OAuth2 flow working fine when it is deployed to self. When an user of the group (after agreeing to participate to test cortana) try to use the skill for the first time, cortana must prompt the user to authorize him/her self in order to use the skill, which doesn't happen and cortana skips that step and send a blank message to my bot service. I really appreciate if you could investigate into this and provide a solution since we are planning to release a demo to the customers. Thanks in advance.

**Comment by hpksp** [comment]
@JasonSowers any updates?

**Comment by hpksp** [comment]
@JasonSowers Our workaround was to use multiple bot channel registration accounts and deployed to self.

OAuth + Bot Framework integration is not an option for us as the solution architecture is bit more complex. Anyways thanks for sharing the link.
