### ISSUE TITLE
[Node.js SDK, Question] LuisRecognizer Error in Node.js SDK?

### ISSUE THREAD

**Issue by ubreddy** [Microsoft/BotBuilder#4054]
## Bot Info
* SDK Platform: NodeJS
* SDK Version:  3.13.1
* Active Channels: emulator, web
* Deployment Environment: local with emulator

## Issue Description
Sometimes I get the following oops error from luisrecognizer. It is not consistent.
```
Error at Request._callback (c:\Projects\nodejsprojects\test\server\
node_modules\botbuilder\lib\dialogs\LuisRecognizer.js:101:31)
```
and gives an oops error. 

## Code Example
Normal luis intent dialog
```js
let commonIntentDialog = new builder.IntentDialog({
              recognizeMode: builder.RecognizeMode.onBegin,
              recognizers: recognizers,
              intentThreshold: Number(threshold) || 0.6
            });
this.bot.dialog('/common', commonIntentDialog);
this.commonIntentDialog.matches('as.commonintent.command' , callStack);   
```         

## Expected Behavior
no oops error.

## Actual Results
shared above.

**Comment by ubreddy** [comment]
Well, this occurs with LuisRecognizer timesout and this Error object is not being caught anywhere resulting in Oops error when luisrecognizer timesout.
Request more elegant way of error handling please.

**Comment by cleemullins** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues


For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botbuilder-channels/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
