### ISSUE TITLE
[Skype for Business] Error happened in Skype for Business service when reaching bot service

### ISSUE THREAD

**Issue by MohammedAbdulMateen** [Microsoft/BotBuilder#4055]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.12.2.4
* Active Channels: Skype, Skype for Business, MS Teams, Slack, Web Chat
* Deployment Environment: Auzure Bot Service, Azure App Service, ngrok

## Issue Description
Bot is not working on Skype for Business but works in MS Teams, Slack, Emulator & Web Chat, I followed the below articles to deploy bot to Skype for Business

https://msdn.microsoft.com/en-us/skype/Skype-For-Business-Bot-Framework/docs/overview#create-bot
https://skypeappregistration.azurewebsites.net/bot/561bae84-ea1c-4f75-a512-b84566779c2c

After that I searched for the bot in Skype for Business using the -Uri sip i.e. like username@domain.com and messaged it, but it is not working and says "Error happened in Skype for Business service when reaching bot service."

I tried using Azure App endpoint as well as ngrok endpoint both are returning the same error message.

## Reproduction Steps
1.
2.
3.

## Expected Behavior
The bot should respond appropriately if Azure App endpoint is used and if ngrok endpoint is used debugging & app should work from Visual Studio

## Actual Results
"Error happened in Skype for Business service when reaching bot service."

**Comment by MohammedAbdulMateen** [comment]
@nwhitmont @EricDahlvang @JasonSowers 

Any update on this issue, is there any temporary fix at least?

The following is the error I am getting,
```
Error happened in Skype for Business service when reaching bot service.
We saved this conversation. You'll see it soon in the Conversations tab in Skype for Business and in the Conversation History folder in Outlook.
```

These are the similar open issues #3619 #3993 

I waited for about a day after updating the URL to ngrok endpoint but still, the same error is thrown, I removed the `[BotAuthentication]` attribute on the `MessagesController` but still, it is the same.

The bot is working fine in Emulator, WebChat.

**Update**: However today I saw errors in the Channels page in Azure, the following is the error.
`There was an error sending this message to your bot: HTTP status code MethodNotAllowed`

I've updated the bot to Microsoft.Bot.Builder version 3.13.1
and the messaging endpoint in Azure is https://e8eca5ed.ngrok.io/api/messages

Could you please help.

**Comment by adaddeo** [comment]
Experiencing this same issue.

**Comment by waqas-zia-confiz** [comment]
Is there any update on this issue?

**Comment by jjgriff93** [comment]
Hi, I'm getting similar:


26‎/‎06‎/‎2018‎ ‎16‎:‎05‎:‎15 | There was an error sending this message to your bot: HTTP status code GatewayTimeout
-- | --
‎22‎/‎06‎/‎2018‎ ‎11‎:‎26‎:‎13 | There was an error sending this message to your bot: HTTP status code GatewayTimeout
‎19‎/‎06‎/‎2018‎ ‎16‎:‎53‎:‎00 | There was an error sending this message to your bot: HTTP status code InternalServerError

Any update?

**Comment by DrWala** [comment]
Hi guys any news

**Comment by EricDahlvang** [comment]
Please review this comment: https://github.com/Microsoft/BotBuilder/issues/4647#issuecomment-397411409

**Comment by cleemullins** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues


For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botbuilder-channels/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
