### ISSUE TITLE
[Migration] Having trouble migrating bot to Azure / O365

### ISSUE THREAD

**Issue by martinoss** [Microsoft/BotBuilder#4058]
## Bot Info
* SDK Platform: .NET

## Issue

I used to manage bot and channel registrations via https://dev.botframework.com/bots. 
I'm running an app service on azure that is hosting my bot. This app service is under a corporate azure subscription and I login to azure with my **company O365 account** via my organizations's sign-in page.

I use this login for `eu.luis.ai`, `portal.azure.com`, `apps.dev.microsoft.com` and `dev.botframework.com`.

Since i'm trying to migrate the bots, I'm facing **several issues**:

- **The migration button**  
When pressing the migration button, I'm getting the error 
> Failed to find any Azure subscriptions for the current user.

- **From Scratch "Bot Channel Registration"**  
In the Azure portal, when I create a new Bot Channels Registration I'm able to see it on `dev.botframework.com`, but in the azure portal on the blades **Channels**, **Test in Web Chat** and **Analytics** (IFrame to `dev.botframework.com`) I get the error 
> There was an error refreshing your sign-in information. Refresh and try again.  
_**But:** When I open the IFrame source in a new tab, I'm able to access those pages._

- **Where goes my app in the Application Registration Portal?**  
In the newly created "Bot Channel Registration" resource on azure, when I click the **"manage" link** for the Microsoft App Id, I get an error, that the application is not available or not assigned to my account (but I'm still logged in with the same credentials).  

What I tried so far:  
- I asked several collegues to try the same (they all have the same problem)  
- Deleted browser cache, tried in-private sessions, tried different browsers etc., logged out & in, ...  
- I also have no live account with my organizations email address  
- For the migration button problem, I was able to **hack around** the problem using a chrome extension to replace authorizations headers for requests going to https://management.azure.com with the access token from the azure portal.

It looks to me to some kind of token incompatibility but I'm not sure where the problem needs to be fixed.

Any ideas or help appreciated!

see also:  
https://docs.microsoft.com/en-us/Bot-Framework/bot-service-migrate-bot  
https://feedback.azure.com/forums/223579-azure-portal/suggestions/32714965-bot-registration-unusable-after-migration#comments

**Comment by nwhitmont** [comment]
@martinoss Have you created a support request for this issue via the Azure website? If not, please create a support request in the Azure portal.

![bot service azure support request](https://user-images.githubusercontent.com/3075047/35062355-e6653b2a-fb78-11e7-8662-91bfeb2185a2.png)

**Comment by JasonSowers** [comment]
A few follow up questions:
1. Can you please provide a .her file
2. Do you have multiple tenants 
3. Can you please provide more details about your work around as it may help lead to a solution.

**Comment by martinoss** [comment]
@nwhitmont I have created following support request: 118011817484784
@JasonSowers 
- What is a .her file and where can I get it?
- Yes, I have multiple tenants and also a few azure active directories (and the first one listed in the drop down in the azure portal has no subscriptions (FirstOrDefault() issue?). 
- Here some Details about the work around:  

1. Using chrome, I logged in to the Azure portal and opened the developer tools (network tab).
2. In the azure portal, I clicked some menu items, inspected a random api request and copied the Auth-Token:

![image](https://user-images.githubusercontent.com/2587942/35087385-4a7a4fd0-fc30-11e7-80d2-7025e111c88b.png)

3. Then I installed the Chrome extension "Requestly" and added a rule to replace the authorization headers for all requests going to https://management.azure.com. As value, I inserted the token from the last step.

![image](https://user-images.githubusercontent.com/2587942/35087545-d032b1e4-fc30-11e7-873e-97f176982e4b.png)

4. I went to https://dev.botframework.com/bots and pressed "Migrate" for my bot. Then I was able to see the the subscriptions and perform the migration.

![image](https://user-images.githubusercontent.com/2587942/35087701-6cad20a4-fc31-11e7-9e42-f8ce84e6260c.png)

**Comment by JasonSowers** [comment]
Apologies I meant .har file

**Comment by martinoss** [comment]
How can I provide you the file in a secure way?

**Comment by JasonSowers** [comment]
Send it to my email address listed in my profile 👍

**Comment by EricDahlvang** [comment]
Hey @martinoss 

Thank you for the thorough explanation of the issue.  Interesting work around you've come up with as well.  Another possible workaround is:

> 1) From the target directory, add a new user (via email address) that is not a member of the first directory, grant the user contributor role on the subscriptions that are the target of the migration.
> 
> 2) From https://dev.botframework.com, add the user’s email address as co-owners of the bots that should be migrated
> 
> 3) Login in https://dev.botframework.com as the new user and proceed with migrating the bots.

**Comment by martinoss** [comment]
@EricDahlvang This workaround for the migration part is much easier :+1: Thank you for that!

**Comment by markau** [comment]
I never migrated a bot; my work has been just inside the Azure Portal (i.e. since botframework.com was shutdown and redirected to Azure portal). I have previously been to the channels page in Azure Portal ... but now am getting this error `There was an error refreshing your sign-in information. Refresh and try again.`. I have tried multiple browsers.
