### ISSUE TITLE
[Feature Request] How to proactively initiate an audio call from bot to user?

### ISSUE THREAD

**Issue by decv86** [Microsoft/BotBuilder#4059]
Hi!
Help me pls!
Is it possible to initiate a audio call from Bot to the user? 

Thank you!

**Comment by FranciscoPonceGomez** [comment]
Hi decv86,

I am assuming that you refer to Skype calls. There is a series of steps that you need to go through to enable audio call from your bot. You can take a look here:
https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-audio-calls

There is also a sample that you can check here:
https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/skype-CallingBot

Are you using Node or C#?

Regards,
Francisco

**Comment by decv86** [comment]
Hi @FranciscoPonceGomez,
I use C#, I want my bot to call the user on the occurrence of a certain event, until I could find a solution ...

Tnx!

**Comment by metasonic** [comment]
Ola,
@decv86 did you manage to get the bot to initiate a call? If so, any change you can provide a rough code example?
Thank you!

**Comment by decv86** [comment]
@metasonic  hi, it is impossible to do, very sad

**Comment by metasonic** [comment]
@decv86 thank for this.
@FranciscoPonceGomez @fanidamj any idea if we can put in a request for this, having the ability to initiate a call from the bot side would be amazing for monitoring bots  (for both .net and nodejs)

**Comment by EricDahlvang** [comment]
@metasonic Labeled this issue as a feature request.

**Comment by metasonic** [comment]
@EricDahlvang thank you, please let me know if you need any use cases for this.
Also if you have any idea of a workaround, regardless of how hackly please feel free to share:D

**Comment by mslonina** [comment]
Hi, proactive calls would be great for sort of emergency scenarios, where we need to raise a call to a on-duty person - I'm working now on a such scenario using the Skype bot (on top of the NodeJS) - with proactive calls, the bot could send a message to all of the users, and additionally call the on-duty one.

**Comment by metasonic** [comment]
Want to use this for the exact same scenario, having the ability to call the person who is on call will make skype bot an amazing tool for emergencies

**Comment by cleemullins** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues


For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botbuilder-channels/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
