### ISSUE TITLE
Sending messages later using an identifier

### ISSUE THREAD

**Issue by ernanirst** [Microsoft/BotBuilder#406]
I managed to develop and deploy a simple nodejs telegram bot using bot connector. But I have one question, I'm currently tracking users with their `session.message.channelData.message.from.username`, however, some of them have private accounts, and because of that, this returns `null`. An alternative identifier I've found is `session.message.from.id`, but later I want notify this user about something and I don't know if it's possible using this id.

How can I notify an user later (like a couple days later) about something? Is there any function of the SDK that uses one accessible identifier for that?

For now, I only know how to send messages using `builder.Prompts.text `and  `session.endDialog`.

**Comment by eanders-MS** [comment]
It may just be my ignorance, but how is an account made private in Telegram? I don't see a setting for it, but I'd like to try to repro this scenario. That aside, we don't have any more visibility into Telegram accounts than you do. If the username is not on the native Telegram update (the message in the incoming channelData field), then we also have no way of knowing who the user is.

**Comment by ernanirst** [comment]
I'm sorry, I expressed myself poorly. It's not that the account is private, for some reason a few users send a `null` username at `session.message.channelData.message.from.username` . I'm "assuming" that there is a setting that hides it (at least from bots). I asked for a few friends to try the bot, and will ask for their settings to try to identify the reason (4 out of 12 testers had this issue). I will come back to that if I have any conclusion.

That aside, is it possible to send a message to an user "later" using it's `session.message.from.id`? I'm using the node SDK.

**Comment by eanders-MS** [comment]
Yes, it should be no problem to send an out-of-band message to the user, as long as your know their Telegram username. The only caveat is the user must have sent at least one message to your bot in the past. A bot cannot initiate a conversation, but once started, bots can send messages whenever they like to the user (unless the user blocks them).

**Comment by eanders-MS** [comment]
Closing this issue. If you believe this issue is not resolved, just leave a comment here and I'll reopen.
