### ISSUE TITLE
[State Service] How to Use Azure TableLogger to store conversation data?

### ISSUE THREAD

**Issue by jay2deguzman** [Microsoft/BotBuilder#4063]
I already added the tablelogger.cs, and I already migrated from state client to azure table storage, question is how to trigger the tablelogger to log the conversation of the user and the bot and how to retrieve it?

**Comment by JasonSowers** [comment]
Can you please provide the code you have already implemented so we can better assist you

**Comment by jay2deguzman** [comment]
First i changed my global asax from 
`protected void Application_Start()
    {
        var builder = new ContainerBuilder();
        builder.RegisterType<Logger>().AsImplementedInterfaces().InstancePerDependency();
        builder.Update(Conversation.Container);
    GlobalConfiguration.Configure(WebApiConfig.Register);

    }`

to

protected void Application_Start()
    {

        Conversation.UpdateContainer(
            builder =>
            {
                builder.RegisterModule(new AzureModule(Assembly.GetExecutingAssembly()));
                var store = new TableBotDataStore(ConfigurationManager.ConnectionStrings["StorageConnectionString"].ConnectionString);
                builder.Register(c => store)
                   .Keyed<IBotDataStore<BotData>>(AzureModule.Key_DataStore)
                   .AsSelf()
                   .SingleInstance();
            });

        GlobalConfiguration.Configure(WebApiConfig.Register);

    }

conversation data is now being stored in azure table as per Azure storage explorer.

before im using a logger class to log the conversation data.

Logger Class:
`public class Logger:IActivityLogger
{
    public static ConcurrentDictionary<string, List<IActivity>> Messages = new ConcurrentDictionary<string, List<IActivity>>();

    public Task LogAsync(IActivity activity)
    {
        try
        {
            var list = new List<IActivity>() { activity };
            Messages.AddOrUpdate(activity.Conversation.Id, list, (k, v) => { v.Add(activity); return v; });
            return Task.FromResult(false);
        }
        catch (System.Exception)
        {

            throw;
        }

    }


}`

before im using this to get my stored conversation:

` var reply = activity.CreateReply();
            var storedActivities = new List<IActivity>();
            var found = Logger.Messages.TryGetValue(activity.Conversation.Id, out storedActivities);
            if (storedActivities != null)
            {
                foreach (var storedActivity in storedActivities)
                {
                    reply.Text += $" <br /> <b>{storedActivity.From.Name}:</b> {storedActivity.AsMessageActivity().Text}";
                }
                // Get any saved values
                StateClient sc = activity.GetStateClient();
                BotData userData = sc.BotState.GetPrivateConversationData(
                    activity.ChannelId, activity.Conversation.Id, activity.From.Id);
                var UserEmail = userData.GetProperty<string>("Email");
                var Name = userData.GetProperty<string>("Name");`

now im confused on how to use this tablelogger class  [and](https://github.com/Microsoft/BotBuilder-Azure/blob/master/CSharp/Library/Microsoft.Bot.Builder.Azure/TableLogger.cs#L60), i already added the tablelogger.cs question is how will i use it? can i simply change my code above?

**Comment by jay2deguzman** [comment]
anyone?

**Comment by JasonSowers** [comment]
`activity.GetStateClient();` This method will always use the default state client, not the client you have implemented.

**Comment by JasonSowers** [comment]
Take a look at this simple example 

```cs
        private async Task MessageReceivedAsync(IDialogContext context, IAwaitable<object> result)
        {
            

            var activity = await result as Activity;
            var reply = activity.CreateReply();
            reply.Text = "no state";
            if (activity.Text.Contains("state"))
            {
                context.UserData.SetValue("key 1", "value1");
                reply.Text = StateValue(context);
            }
            await context.PostAsync(reply);
            context.Wait(MessageReceivedAsync);
        }

        private string StateValue(IDialogContext context)
        {
            return context.UserData.GetValue<string>("key 1");
        }
```
