### ISSUE TITLE
[.Net SDK, Question] How to handle "No" answer in FormBuilder?

### ISSUE THREAD

**Issue by rachita0311** [Microsoft/BotBuilder#4067]
I have a bot in which one of my form questions is:
"Do you have knowledge on MVC"
If I say "No" , it is doing something wrong. It keeps on asking me the same question again and again. 

**Property**
  [Prompt("Do you have knowledge on MVC?"]
   
        public string HaveMVCSkill { get; set; }

**Method to Build Form**
  var builder = new FormBuilder<HybridVehicleInput>()
                .OnCompletion(processScheduling);
           
            return builder.Build();

What is wrong here?

**Comment by fanidamj** [comment]
Closing the issue assuming it as resolved. Please reopen a new issue if it still persists.
