### ISSUE TITLE
[Node.js SDK, Code Examples] "Node.js quick start" example uses incorrect env variables for MICROSOFT_APP_ID and MICROSOFT_APP_PASSWORD

### ISSUE THREAD

**Issue by pconnell99** [Microsoft/BotBuilder#4068]
## Bot Info
* SDK Platform: Node.js 
* SDK Version: 3.13.1
* Active Channels: MS Teams
* Deployment Environment: Azure Bot Service

## Issue Description
Using the example code at https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-quickstart#edit-your-bot , the webchat/emulator fails when deployed to Azure Bot service.  The example lines:-

```
var connector = new builder.ChatConnector({

    appId: process.env.MICROSOFT_APP_ID,

    appPassword: process.env.MICROSOFT_APP_PASSWORD

});
```
use environment variable names that are different from an Azure Bot deployment.  The environment variables generate for an Azure deployment are `MicrosoftAppId` and `MicrosoftAppPassword`.

## Actual Results
When deploying the example, it will not respond in WebChat or via ngrok (authentication issues possibly) until these lines are fixed.

**Comment by nwhitmont** [comment]
@pconnell99 Thanks for reporting, will forward to docs team.

**Comment by nwhitmont** [comment]
I have created the PR here: https://github.com/MicrosoftDocs/bot-framework-docs/pull/102

**Comment by fanidamj** [comment]
Closing the issue assuming it as resolved. Please reopen a new issue if it still persists.
