### ISSUE TITLE
[Skype for Business] Channel integration not working?

### ISSUE THREAD

**Issue by kpranay** [Microsoft/BotBuilder#4069]
## Issue Description
Skype for business integration from botframework was done as described in https://skypeappregistration.azurewebsites.net/bot/74cff280-6766-4db3-8a7c-25cfc16cc9de .
But still the bot status is offline and its not responding for messages. 

## Code Example
Application id : 74cff280-6766-4db3-8a7c-25cfc16cc9de

## Expected Behavior
Bot should respond to messages.

## Actual Results
Bot not responding to messages.

<img width="663" alt="sfb not responding" src="https://user-images.githubusercontent.com/7565364/35150903-3fd640b2-fd42-11e7-83f7-aa8dfb0818af.PNG">

**Comment by fanidamj** [comment]
The Bot Framework Skype for Business Channel is in Developer Preview and does not support presence at the current time as mentioned [here](https://msdn.microsoft.com/en-us/skype/skype-for-business-bot-framework/docs/bot-common-errors). Hope this helps!!

**Comment by kpranay** [comment]
Thanks for the response @fanidamj .
