### ISSUE TITLE
[.Net SDK, Question] Why am I getting "There was an error sending this message to your bot: HTTP status code InternalServerError"?

### ISSUE THREAD

**Issue by bommareddysandhya** [Microsoft/BotBuilder#4072]
## Bot Info
* SDK Platform: .NET
* SDK Version: 4.6.1
* Active Channels: Skype, Email, etc.
* Deployment Environment:  Azure App Service, and Bot Channels Registration 

## Issue Description
There was an error sending this message to your bot: HTTP status code InternalServerError
for Bot application developed using VS 2017 and deployed bot application as Appservice and registered channels using Bot Channels Registration. the bot is working fine in web chat and emulator and getting error in Skype and email channel. 
Getting these two below error in Email and Skype channels 
1.POST to the bot's endpoint failed with HTTP status 500
2.There was an error sending this message to your bot: HTTP status code InternalServerError

Kindly any one come across the issue please share your resolution steps.

## Code Example
Using default Echo bot

**Comment by bommareddysandhya** [comment]
[Dialogs.zip](https://github.com/Microsoft/BotBuilder/files/1654580/Dialogs.zip)

[MessagesController.zip](https://github.com/Microsoft/BotBuilder/files/1654582/MessagesController.zip)

**Comment by bommareddysandhya** [comment]
Hi nwhitmont,



Git hub Issue url : https://github.com/Microsoft/BotBuilder/issues/4072



I have created simple Echo bot and deployed as web app and registered the
email and skype channel using Web channel registration service in azure.



Bot was working in webchat & emulator , not working in email and skype also
any specific reason for this .

Below are the error screen shot form azure channels.





Thanks & Regards,

Sandhya

**Comment by JasonSowers** [comment]
I am unable to reproduce this

**Comment by bommareddysandhya** [comment]
to get the resolution for the issue what other information do you required.In Application insight I am getting the below error. In Skype and Webchat it was working fine. This is on critical ,any help will be appreciated .
![forbiddenerror](https://user-images.githubusercontent.com/28855176/35608285-58dfbfd6-0650-11e8-8609-01acedf0c3c9.png)

**Comment by bommareddysandhya** [comment]
I am able to debug the code when email received to ID , but reply is not sending and Error getting logged in Application Insight .

**Comment by PriyaB07** [comment]
Hi bommareddysandhya, 
Is issue resolved? I am facing same problem. I have developed Bot in Visual Studio and deployed it to azure and connected to Email . On receiving new email , I am getting same 2 eoors.

**Comment by bommareddysandhya** [comment]
Still my issue not solved , getting the same error in email channel and Application insight exception was logging as "Authorization for Microsoft App ID f7e1dbda-7098-4512-ad6b-29d1fa0e0016 failed with status code Forbidden and reason phrase 'Forbidden'Response status code does not indicate success: 403 (Forbidden)."

**Comment by ChristopherCarver** [comment]
When you publish, is the Site URL http or https? It should be https. This bit me yesterday.

**Comment by EricDahlvang** [comment]
Which version of the BotBuilder SDK are you using?

**Comment by bommareddysandhya** [comment]
Bot builder version is 3.13.0.3 and when publishing the site getting http only, but in configuration of azure channel registration used https://

**Comment by PriyaB07** [comment]
After multiple attempts of saving email ,It started working automatically though while saving the there was same error 'Unable to Save'.

**Comment by fanidamj** [comment]
@PriyaB07 Can you please let us know if the issue still persist?
