### ISSUE TITLE
[Direct Line] Getting 500, 502 and 503 status codes a lot?

### ISSUE THREAD

**Issue by alexandruf** [Microsoft/BotBuilder#4074]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.11.0
* Active Channels: DirectLine
* Deployment Environment: Azure Bot Service, local development with Emulator

## Issue Description
Today I experience some problems with directline API 
More than 50% of time is like this:
POST https://directline.botframework.com/v3/directline/conversations/LWNUQxx9nVADbdBevnehbm/upload?userId=c3463c3d-4238-4d0a-9cbd-c03352cb2059 500 (Internal Server Error)
 Failed to load https://directline.botframework.com/v3/directline/conversations/LWNUQxx9nVADbdBevnehbm/upload?userId=c3463c3d-4238-4d0a-9cbd-c03352cb2059: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'XXXX' is therefore not allowed access. The response had HTTP status code 500.

**Comment by droidpl** [comment]
Same here, today it is quite unstable

**Comment by alexandruf** [comment]
Great! Thank you!

**Comment by droidpl** [comment]
Great. Let us know when is it deployed. I will verify how it affects also the issue I have opened in https://github.com/Microsoft/BotBuilder/issues/4066

**Comment by alexandruf** [comment]
@nwhitmont  do you have any news? Today is kinda worse than yesterday

**Comment by ruicampos** [comment]
Same here. We are experiencing long delays (>1 minute) and messages lost using direct line.

**Comment by alexandruf** [comment]
Hey guys, we would really appreciate an official answer on this. 
Directline is not reliable these days.
Thank you in advance!

**Comment by vincec-msft** [comment]
We believe that Direct Line has stabilized but there are still occasional problems related to load. These impact certain datacenters more than others, so to address specific problems we need to know times (in UTC please) and conversation ids, if available.

**Comment by droidpl** [comment]
Hi @vincec-msft, check the details I provided in https://github.com/Microsoft/BotBuilder/issues/4066. It includes also the logs of what happens in the server and the post we send.

**Comment by artonh** [comment]
I have the same problem, it shows error 502 in diretline, [https://prnt.sc/iwzz4j](https://prnt.sc/iwzz4j)

How to fix this!

**Comment by vincec-msft** [comment]
See https://docs.microsoft.com/en-us/azure/bot-service/bot-service-troubleshoot-general-problems#what-causes-the-direct-line-30-service-to-respond-with-http-status-code-502-bad-gateway

"Direct Line 3.0 returns HTTP status code 502 when it tries to contact your bot but the request does not complete successfully. This error indicates that either the bot returned an error or the request timed out. For more information about errors that your bot generates, go to the bot's dashboard within the Bot Framework Portal and click the "Issues" link for the affected channel. If you have Application Insights configured for your bot, you can also find detailed error information there."

**Comment by vincec-msft** [comment]
The original report and follow-up issues have been resolved.

**Comment by artonh** [comment]
I solved that, my Microsoft.Bot.Builder/Connector it was version 3.14.0.7, I updated to 3.14.1.1 because it was a bug in 3.14.0.7 for that....

So now is good, thank you!

**Comment by Squashy83** [comment]
Hi there!

I'm getting since yesterday '[503] Service Unavailable' quite often from directline...any news MS side?

Thanks

**Comment by vincec-msft** [comment]
Yes, Direct Line had an outage tonight. It should be mitigated now. Updates here: https://azure.microsoft.com/en-us/status/
