### ISSUE TITLE
What channels support outgoing calls?

### ISSUE THREAD

**Issue by medeirosrafael** [Microsoft/BotBuilder#4076]
Sorry for using this space to ask this, but, it's possible use some channel to do Outgoing Audio Calls?

**Comment by nwhitmont** [comment]
Hi @medeirosrafael - You can conduct audio calls using Skype channel. 

>If you are building a bot for Skype, your bot can communicate with users via audio call. Audio calls are useful when the user does not want to or cannot provide input by typing, tapping, or clicking.

Read more about the feature here:
https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-audio-calls

**Comment by medeirosrafael** [comment]
@nwhitmont I did that, but, i wasn't able to make calls, only receive.. I can't find no way to make a call and play a audio, for example

**Comment by FranciscoPonceGomez** [comment]
Outgoing calls were not supported the last time I checked. I am speaking to the Skype team just to make sure.

**Comment by medeirosrafael** [comment]
@FranciscoPonceGomez thanks for that

**Comment by nwhitmont** [comment]
It's not a feature because ... spambots.

**Comment by medeirosrafael** [comment]
@nwhitmont Thank you. Maybe i need to use twilio for that..
