### ISSUE TITLE
[Node.js SDK, state service, Question] Tips on implementing RedisStore as MemoryStorage?

### ISSUE THREAD

**Issue by loretoparisi** [Microsoft/BotBuilder#4078]
Is it possibile to use `RedisStore` as memory storage instead of a in memory storage:

```javascript
var inMemoryStorage = new BotBuilder.MemoryBotStorage();
// Connector
	var connector = new BotBuilder.ChatConnector({
		appId: BotConfig[BotConfig['env']].MS_appId,
		appPassword: BotConfig[BotConfig['env']].MS_appPass
	});
	// Bot
	var bot = new BotBuilder.UniversalBot(connector, function (session, args) {
		session.send( getLocalizedString('RESPONSE_BEGIN_WELCOME','RESPONSE_BEGIN_WELCOME') );
		//session.beginDialog('rootMenu');
		// If the object for storing notes in session.userData doesn't exist yet, initialize it
		if (!session.userData.notes) {
			session.userData.notes = {};
			consoleLogger.info("initializing userData.notes in default message handler");
		}
		
	}).set('storage', inMemoryStorage); // Register in memory storage
	// Recognizer
	bot.recognizer(new BotBuilder.LuisRecognizer(LUISConfig[LUISConfig['env']].model));
```

**Comment by Ma3yTa** [comment]
@loretoparisi try https://github.com/suttna/botbuilder-redis-storage or https://github.com/sebsylvester/botbuilder-storage

**Comment by nwhitmont** [comment]
As @Ma3yTa mentioned - I recommend looking at Suttna's package:

https://github.com/suttna/botbuilder-redis-storage

**Comment by loretoparisi** [comment]
@nwhitmont Thanks, I have checkout and I my understanding the point is

- use the redis node module
- write a wrapper of the `IBotStorage` interface.

That said, since seems to be something simple, is Microsoft providing any official implementation?

**Comment by fanidamj** [comment]
Closing the issue assuming it as resolved. Please reopen a new issue if it still persists.
