### ISSUE TITLE
[.Net SDK, Skype, Proactive messages] How to initiate proactive message from the bot? 

### ISSUE THREAD

**Issue by KiranBastawadi** [Microsoft/BotBuilder#4080]
I am using the bot flat form provided here and it works well for me, going forward how can I use the bot to initiate a chat using a hard coded ID ?

**Comment by JasonSowers** [comment]
What you are looking for is called [proactive messaging](https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-proactive-messages)  there is a [sample here](https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/core-proactiveMessages) with multiple examples.

**Comment by nwhitmont** [comment]
@KiranBastawadi - For reference are you using .NET or Node.js SDK for BotBuilder?  The answer will depend on your programming language.

**Comment by KiranBastawadi** [comment]
.net (c#). Thank you

**Comment by JasonSowers** [comment]
I assume this is resolved now, if not please open a new issue
