### ISSUE TITLE
[.Net SDK, DirectLine, Question] First response from bot sometimes takes over 10 seconds?

### ISSUE THREAD

**Issue by Wenish** [Microsoft/BotBuilder#4088]
## Bot Info
* SDK Platform: **.NET**
* SDK Version:  **3.12.2.4**
* Active Channels: **Direct Line**
* Deployment Environment: Azure Bot Service / local development with Emulator

## Issue Description
When u send a msg to the Bot the first time. The Bot needs 1-10sec or more to respond.

## Reproduction Steps
1. Start Bot
2. Send a msg with the bot emulator

## Expected Behavior
The first respond should always be fast

## Actual Results
Sometimes it takes over 10 sec for the bot to respond to the msg

**Comment by nwhitmont** [comment]
Hi @Wenish - Can you share your bot code that causes the issue?

**Comment by garypretty** [comment]
@Wenish Are you using app service or functions to host your bot in the Bot Service? If it is a web app, have you got 'always on' enabled on your Azure web app?  It sounds like the web app is warming up and that might be what is causing the initial delay.

**Comment by Wenish** [comment]
@garypretty we use the azure bot service which ist set to be always on. but the problem happens on local env too.

@nwhitmont i removed in the webconfig out bot id secret etc. and removed our api call in the ticket dialog because i needs a secret 2..

its a pretty simple bot. u can create support ticket with attachments and text

[Beyond-Bot-Helpdesk.zip](https://github.com/Microsoft/BotBuilder/files/1667803/Beyond-Bot-Helpdesk.zip)

**Comment by Wenish** [comment]
after removing appId and apppasword and connecting with bot emulator the first msg respond is again everytime fast.

as soon i put in appId and apppassword into the webconfig and connecting with the bot emulator using the appid and apppassword the respond takes again really long

**Comment by Wenish** [comment]
so whats the plan on this one?

**Comment by EricDahlvang** [comment]
Hi @Wenish 

Apologies for the lack of response.  We have a blog post with some recommendations to optimize for latency: https://blog.botframework.com/2017/11/02/optimizing-latency-bot-framework/

I hope this helps.
