### ISSUE TITLE
[Skype] Channel not working for Bot Channel Registration and MS Teams enabled

### ISSUE THREAD

**Issue by starlord-daniel** [Microsoft/BotBuilder#4089]
## Bot Info
* SDK Platform: .NET
* SDK Version: Bot Builder 3.12.2.4
* Active Channels: WebChat (works), Cortana (works), Skype (not working), MS Teams (took some time, but working)
* Deployment Environment: Web App and Bot Channel Registration

## Issue Description
I've built a bot with the .Net BotBuilder and configured continuous deployment to publish it to a Web App. The endpoint from the WebApp was then registered with the Bot Channels Registration, to add the mentioned channels. It works fine for WebChat and Cortana, but not for Skype.

## Reproduction Steps
1. Publish a bot to Web App
2. Register the app via Bot Channels Registration
3. Add Cortana first, then Teams, then Skype 

## Expected Behavior
The channels MS Teams and Skype should be able to respond to messages.

## Actual Results
Skype error:

Unable to save. HttpException: Aps call failed - message: NA reasonPhrase: Service Unavailable request content: {"Description":{"displayName":"cafeteria","description":"Order your favorite food from the cafeteria","agentId":"a925d9a8-cae2-48cc-8e66-bd5d0f20636b","developer":"","extra":null,"customProperties":{"ShowInDirectory":false},"userTileSmallUrl":"https://bot-framework.azureedge.net/bot-icons-v1/Cafeteria Bot_6H76x7Aax1DwD9O6rM3SU21qEdh96I7N1WqES43zXDSsAGw.png","userTileMediumUrl":"https://bot-framework.azureedge.net/bot-icons-v1/Cafeteria Bot_6H76x7Aax1DwD9O6rM3SU21qEdh96I7N1WqES43zXDSsAGw.png","userTileLargeUrl":"https://bot-framework.azureedge.net/bot-icons-v1/Cafeteria Bot_6H76x7Aax1DwD9O6rM3SU21qEdh96I7N1WqES43zXDSsAGw.png","userTileExtraLargeUrl":"https://bot-framework.azureedge.net/bot-icons-v1/Cafeteria Bot_6H76x7Aax1DwD9O6rM3SU21qEdh96I7N1WqES43zXDSsAGw.png","userTileStaticUrl":"https://bot-framework.azureedge.net/bot-icons-v1/Cafeteria Bot_6H76x7Aax1DwD9O6rM3SU21qEdh96I7N1WqES43zXDSsAGw.png","webpage":null,"tos":null,"privacyStatement":null,"isTrusted":false,"capabilities":["im.send","im.receive","file.send","moji.send","photo.send","external.media.receive"],"disclosures":null,"supportedLocales":[],"agentType":"Participant","starRating":0.0,"categories":["None"],"keywords":null,"etag":"636523839121527492"},"PublishState":"Preview","Disabled":true,"MsaAppId":"a925d9a8-cae2-48cc-8e66-bd5d0f20636b","BotHandle":"cafeteria","AppInsightsInstrumentationKey":"b55d14ff-3fcc-4b8b-950e-62ae331745ef","Cid":0,"Updated":"2018-01-24T09:45:12.1527492Z","DeveloperId":"deprecated","MessagingApiVersion":"3","MessagesUrl":"https://cafeteria.azurewebsites.net/api/messages","PairwiseIdKey":"eyJLZXlJZCI6IjEiLCJFbmNyeXB0ZWRTZWNyZXQiOiJjdktlVFlweGE3NW5HcTVFTko0ZXRUaU9nYUpxNUJSYzFPL0x3bDNMWEYwRjVKVEdhSTRHWFprUXAya29GVEc5NnRkK2dZNGo2WDZZYmZlZUF2S200Zz09IiwiSVYiOiJvenFwTDQ5d2xhMXZ6VmNvbjgwOXVRPT0ifQ==","AugmentedChatMode":false,"SequencingTimestamp":"2018-01-24T09:56:08.1328413Z","SupportedMarkets":[],"Channels":["msteams"],"Hashtags":"skypedirect,v31auth"}

**Comment by EricDahlvang** [comment]
Skype can take up to 15 minutes to propagate the settings changes.  Do you see any errors or warnings in the Health column on the Channels tab?

**Comment by mcrepy** [comment]
Having the same issue...

**Comment by starlord-daniel** [comment]
I tried this with days between the calls to skype.

**Comment by EricDahlvang** [comment]
If Skype does not respond after waiting a few minutes, please try changing the Messaging Endpoint in the Azure portal, and changing it back.  (Until the underlying propagation issue is fixed, this is a valid workaround)
