### ISSUE TITLE
[.Net SDK, Code Examples] New bot app created in Visual Studio is missing Microsoft.Bot.Connector NuGet package

### ISSUE THREAD

**Issue by curia-damiano** [Microsoft/BotBuilder#4093]
## Bot Info
* SDK Platform: .NET
* SDK Version: latest NuGet package
* Active Channels: Bot Emulator
* Deployment Environment: local development with Emulator

## Issue Description
Creating a new bot app in Visual Studio, it misses the NuGet package Microsoft.Bot.Connector, so it's not possible to test it in the Emulator

## Reproduction Steps
1. With the latest version of Visual Studio, create a new Bot
2. Compile and run it in the emulator
3. It won't run because it misses the Microsoft.Bot.Connector NuGet package

## Expected Behavior
I would expected that the out-of-the-box template works fine

## Actual Results
I can't debug until I add the missing package

**Comment by nwhitmont** [comment]
@curia-damiano What happened when you installed the Microsoft.Bot.Connector package to the app manually?  Were there still problems with the example app?

**Comment by curia-damiano** [comment]
Hi, installing the package manually, everything was fine.
My issue is only about the Visual Studio template that is just missing this package.

**Comment by EricDahlvang** [comment]
Where are you getting the template?

**Comment by fanidamj** [comment]
Closing the issue assuming it as resolved. Please reopen a new issue if it still persists.
