### ISSUE TITLE
[Question] Why am I getting error: "There was an error sending this message to your bot: HTTP status code GatewayTimeout"?

### ISSUE THREAD

**Issue by bibsg** [Microsoft/BotBuilder#4096]
## Bot Info
* Bot handle: sbcbot
* App ID: 5b1d7f0b-6905-4afa-a8a7-ada6e5fc4284
* SDK Platform: .NET
* Active Channels: Skype, Web chat
* Deployment Environment: IIS

## Issue Description
I have developed a bot which is using the qna maker to answer some questions. I have deployed it on the IIS server. But when I try to chat with it on the bot framework's web chat it says "couldn't send retry", with issue "There was an error sending this message to your bot: HTTP status code InternalServerError". the bot works perfectly on localhost without the MAID and Password, but doesn't work with them in the Webconfig. I've tried validating the credentials using curl, and they are correct. I am not able to use ngrok as it gives me an error "Failed to start ngrok: panic: runtime error: invalid memory address or nil pointer dereference...". It doesn't give any reply on skype chat as well. My SDK and emulator are up to date. I doubt there is something wrong with the settings in the IIS, but there are no turorials/blogs that can show the whole process step by step. This is an issue as I am new to IIS. Any help would be really appreciated. Additionally, I have added "POST" verb to the website.

## Code Example
I am not sure if there's something wrong with my code, but here's the main part
```cs
public class MessagesController : ApiController
    {
        public async Task<HttpResponseMessage> Post([FromBody]Activity activity)
        {
            if (activity.Type == ActivityTypes.Message)
            {
                ConnectorClient connector = new ConnectorClient(new Uri(activity.ServiceUrl));
                var responseString = String.Empty;
                var responseMsg = "";

                //De-serialize the response
                QnAMakerResult QnAresponse;

                // Send question to API QnA bot
                if (activity.Text.Length > 0)
                {
                    var query = "hi"; //User Query
                    var knowledgebaseId = "knowledge base id created";
                    var qnamakerSubscriptionKey = "subscription key";

                    //Build the URI
                    Uri qnamakerUriBase = new Uri("https://westus.api.cognitive.microsoft.com/qnamaker/v1.0");
                    var builder = new UriBuilder($"{qnamakerUriBase}/knowledgebases/{knowledgebaseId}/generateAnswer");

                    //Add the question as part of the body
                    var postBody = $"{{\"question\": \"{activity.Text}\"}}";

                    //Send the POST request
                    using (WebClient client = new WebClient())
                    {
                        //Set the encoding to UTF8
                        client.Encoding = System.Text.Encoding.UTF8;

                        //Add the subscription key header
                        client.Headers.Add("Ocp-Apim-Subscription-Key", qnamakerSubscriptionKey);
                        client.Headers.Add("Content-Type", "application/json");
                        responseString = client.UploadString(builder.Uri, postBody);
                    }

                    try
                    {
                        QnAresponse = JsonConvert.DeserializeObject<QnAMakerResult>(responseString);
                        responseMsg = QnAresponse.Answer;
                    }
                    catch
                    {
                        throw new Exception("Unable to deserialize QnA Maker response string.");
                    }
                }

                // return our reply to the user
                if (responseMsg == Convert.ToString("No good match found in the KB"))    
                {
                    await Conversation.SendAsync(activity, () => new Dialogs.RootDialog());
                }
                else
                {
                    Activity reply = activity.CreateReply(responseMsg);
                    await connector.Conversations.ReplyToActivityAsync(reply);
                }                                                                        

            }
            else
            {
                HandleSystemMessage(activity);
            }
            var response = Request.CreateResponse(HttpStatusCode.OK);
            return response;
        }

        private Activity HandleSystemMessage(Activity message)
        {
            if (message.Type == ActivityTypes.DeleteUserData)
            {
                // Implement user deletion here
                // If we handle user deletion, return a real message
            }
            else if (message.Type == ActivityTypes.ConversationUpdate)
            {
                // Handle conversation state changes, like members being added and removed
                // Use Activity.MembersAdded and Activity.MembersRemoved and Activity.Action for info
                // Not available in all channels
            }
            else if (message.Type == ActivityTypes.ContactRelationUpdate)
            {
                // Handle add/remove from contact lists
                // Activity.From + Activity.Action represent what happened
            }
            else if (message.Type == ActivityTypes.Typing)
            {
                // Handle knowing tha the user is typing
            }
            else if (message.Type == ActivityTypes.Ping)
            {
            }

            return null;
        }
    }

```

## Expected Behavior
When the user starts conversation by typing "Hi", the bot should post a reply.

**Comment by EricDahlvang** [comment]
I see you're using the connector client to send a reply.  Try calling `MicrosoftAppCredentials.TrustServiceUrl(activity.ServiceUrl); `before `connector.Conversations.ReplyToActivityAsync(..)`

What error occurs when the appid and password are in the webconfig?

For the ngrok issue, how are you starting ngrok?  Does it work from the command line?
https://github.com/Microsoft/BotFramework-Emulator/issues/301

**Comment by bibsg** [comment]
I tried your first suggestion, and it started working on the emulator on the following link <http://localhost:3979/api/messages> with appid and password set. But ngrok still failed to start. 
I am using Windows 10, and I have set ngrok in the environment variables. It does show the version when asked for, but when I type ngrok http 3978, it gives the error above.

**Comment by mutanttech** [comment]
Hi Guys,
I have configured a Web Chat Channel and a Direct Line Channel on Azure Bot Service. I am using the web chat control on the client side i.e. on a web page to provide a UI to users. For now I am using the Web chat control as it is i.e. included botchat.js in html served from my local server and also botchat.css which I have modified the css to give a custom look n feel. There will be requirement in future where I might have to create a custom build of Web Chat control source code, to reduce the overall size of botchat.js file and do some custom implementation as well. My question is it right way to use the UI for a website. Please share your experience and best practice for the same. Are there any other ways to do UI for Website, because I want to support the flexibility of displaying various types of responses like text, video, hero cards etc. Also, for now I am passing the secret key in the BotChat.App code, but I am confused which secret key to use, the one from WebChat Channel or DirectLine Channel. Please help me guys.
Thanks and Cheers for your efforts..

**Comment by EricDahlvang** [comment]
@bibsg I use the following to start ngrok:

`ngrok http 3979 -host-header="localhost:3979"`

Are you behind a corporate firewall?

**Comment by EricDahlvang** [comment]
@mutanttech Please open a new issue: https://github.com/Microsoft/BotBuilder/issues/new  The issue you are commenting on is about a different topic.

**Comment by bibsg** [comment]
@EricDahlvang  I haven't tried this command. I am on a break and will go back on Wednesday. I'll check it out then. Please do not close this issue. I'll report back on Wednesday. Thanks for your help.
Yes, we do have a corporate firewall.

**Comment by bibsg** [comment]
@EricDahlvang Hi, I tried the above command in ngrok, but still shows an error in the session status. It keeps looping between the messages "reconnecting (x509: certificate signed by unknown authority)", "reconnecting (invalid character '<' looking for beginning of value)", and "reconnecting (dial tcp [2600:1f16:59e:b200:21d7:7eb7:fd6f:f0a9]:443: connectex: A socket operation was attempted to an unreachable network.)".
