### ISSUE TITLE
[Question] [Node.js] Not connecting to LUIS? (intelligence-LUIS sample) 

### ISSUE THREAD

**Issue by belcsy** [Microsoft/BotBuilder#4097]
## Bot Info
* SDK Platform: Node.js
* SDK Version: V3.5.35
* Deployment Environment: Local development with Bot Emulator

## Issue Description
I am currently trying out the 'intelligence-LUIS' sample from [BotBuilder-Samples](https://github.com/Microsoft/BotBuilder-Samples), and I am able to run it in the Bot Emulator with no apparent issues. I have imported the included LuisBot.json file to LUIS, published and entered the link the codes.

However, it seems like I am unable to get a response from LUIS as the response is always the default 'Sorry, I did not understand (what I entered). Type 'help' if you need assistance.' Can I know where did I go wrong?

I have attached the emulator screenshot below. Please let me know if you need more information!

![1](https://user-images.githubusercontent.com/22006107/35378479-e785f262-01ed-11e8-8e97-7df6ce74f9c2.png)

**Comment by JasonSowers** [comment]
I didn't see you mention that you actually trained the LUIS model, did you do that step?  See [here](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-get-started-create-app) for more info

**Comment by belcsy** [comment]
Hi JasonSowers, my bad, I failed to mentioned that. I did train the LUIS model, after I imported LuisBot.json.

**Comment by belcsy** [comment]
I tried to follow another tutorial that did not use the Bot Emulator, but terminal to run the results, but I was also not successful. Attached is my error message.

![2](https://user-images.githubusercontent.com/22006107/35420552-1bd69982-0279-11e8-8bce-c10bace15b5a.png)

I am pretty sure the LUIS link works though, as I added a 'Help' behind and it returns a json file.

**Comment by belcsy** [comment]
Was able to solve this by using the `global-tunnel` package and managed to get a successful response from LUIS. Tried again with the bot emulator but it gave a Parse Error instead. 

Will close this thread tho, as LUIS is now no longer the issue. Thanks!
