### ISSUE TITLE
[Feature Request] Make Connector's (Facebook, Telegram, Skype) source code public?

### ISSUE THREAD

**Issue by Ma3yTa** [Microsoft/BotBuilder#4099]
I would like to implement payments for Telegram and Facebook https://github.com/Microsoft/BotBuilder/issues/4073
Approach is to translate ``application/vnd.microsoft.card.payment`` card to platform-specific requests https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-channeldata.
And translate events like ``shipping`` , ``precheckout`` to common model.

**Comment by nwhitmont** [comment]
At the time of this writing, the BotBuilder SDK is open sourced, and the bot connector service is private Microsoft IP.
