### ISSUE TITLE
Directline API - Always getting a same message from bot (Nodejs)

### ISSUE THREAD

**Issue by giriganapathy** [Microsoft/BotBuilder#410]
Hello dandriscoll,

Yes. Basically, I am reusing the chat.js, and here is the code snippet.  I am able to call the directline api now..however I am always getting the first message (as responses)from my bot, every time I post new messages. Can any one help me here....?. I have attached the snapshot of the scenario below:

![directline_same_message](https://cloud.githubusercontent.com/assets/18748896/15714353/d2f12de4-2837-11e6-8c04-4f187a913d69.jpg)

Regards,
Giri G.

**Comment by giriganapathy** [comment]
Any updates on this dandriscoll?

**Comment by dandriscoll** [comment]
When you call DirectLine, you own the message.From field and have to set it to a static value. Otherwise we assume it's a new user every time.

**Comment by giriganapathy** [comment]
Cool. After setting the from field.., I am able to see the bot messages...Actually, as I did not see the "from" property in Message, it did not strike me:

An extract from chat.js
    var ChatMessage = (function () {
        function ChatMessage() {
            this.messageId = '';
            //public chatId: string = ''; //id for conversation
            this.botId = '';
            this.timestamp = null;
            this.text = '';
            this.contact = '';
            this.lat = '';
            this.long = '';
            this.contentUrl = '';
            this.isBotResponse = false;
            this.msgtype = 'text';
        }
        return ChatMessage;

Anyways...I am very happy to see my bot messages from my own client.  

I appreciate your response in this regard.  This ticket can be closed.

Regards,
Giri G,

**Comment by giriganapathy** [comment]
Hello Dan Driscoll,

This is a general question about Promoting our Bot to Production environment. Please find my questions below:
Deploying Bot in PROD Environment:
1. Is your bot framework released officially?, 
If so:
a. What as an organization, to do when we want to promote the Bot to PROD environment?
b. What kind of contract/license agreement to be made to Microsoft?
c. What are all the efforts involved in terms of cost?

Could you please answer my queries here. Since i dont have your email id, i am posting here for the benefit of others as well.

You can also reply to me: giriganapathy@gmail.com in this regard.

Your early responses are highly appreciated.

Regards,
Giri G.
