### ISSUE TITLE
[Question] How to disable inputs from previous choices in Teams?

### ISSUE THREAD

**Issue by benchan-mobi** [Microsoft/BotBuilder#4102]
## Bot Info
* SDK Platform: Node.js
* SDK Version: 3.13.1
* Active Channels:  MS Teams
* Deployment Environment: Bot on dev.microsoft.com communicate to local server endpoint

## Issue Description
Is there a way to disable buttons after user select any of those?

## Code Example
Tried example code on https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-send-suggested-actions, but the whole suggestedAction is missing on Teams, don't know if this is support by teams.

## Reproduction Steps
Currently mainly using Hero Card, simple message also tried but no luck

## Expected Behavior
Buttons will be disabled after user select any of those input

## Actual Results
User can still select buttons from previous message 

## Extra
I read the https://github.com/Microsoft/BotBuilder/issues/4033 and saw that it may be done through  custom solution on bot-emulator, however we are on Teams so can you please suggest a way to start it if possible?

**Comment by JasonSowers** [comment]
It's not possible to do exactly what you are asking.  The best thing for you to do is add some sort of validation on your inputs.  We are doing so in [this project](https://github.com/JasonSowers/ContosoScubaBot)  which is adaptive cards based but follows the same idea.
