### ISSUE TITLE
[Question] LUIS error: "Response status code does not indicate success: 410 (Gone)"?

### ISSUE THREAD

**Issue by band888888** [Microsoft/BotBuilder#4103]
## Bot Info
* SDK Platform: .Net
* SDK Version: 3.12.2.4
* Active Channels: Skype for business
* Deployment Environment:  Azure Bot Service, Azure App Service

## Issue Description
When calling a LuisDialog in the MessageController, I am all of a sudden intermittently getting the following error: "Response status code does not indicate success: 410 (Gone)."

Yesterday, all things is fine. Today it get brokern and return the error:
Response status code does not indicate success: 410 (Gone).

i did not change any of my code. And i try to deploy again to the Azure the error still there.

My Luis ID is : 9d365832-90ce-428e-aab6-fdd91fff779d

I test with simulator it's work time to time. But for the Skype for business and the web channel broken all the time when use the Luis dialog.

## Code Example
 
    [LuisModel("9d365832-90ce-428e-aab6-fdd91fff779d", "d24a62f2--------------------")]
    [Serializable]
    public class NaNaLuisDialog : LuisDialog<object>
    {
          [LuisIntent("SearchWeather")]
        public async Task SearchWeather(IDialogContext context, IAwaitable<IMessageActivity> argument,LuisResult result)
        {

        }
    }

## Reproduction Steps
This error is suddently appear. 

 Also i checked forum there the sme issue with #3218

Grateful if you could give me suggestion.  @nwhitmont    @EricDahlvang

**Comment by JasonSowers** [comment]
Are you able to post your entire project either here or in a repo so we can try to reproduce?

**Comment by band888888** [comment]
Thanks @JasonSowers  reply. I tested it today. Somehow it's back to normal. So i assume it's the network/Server stabilize problem.   If you have any suggestion grateful if you could let me know.

**Comment by band888888** [comment]
Hello guys @JasonSowers @nwhitmont @EricDahlvang @fanidamj , Unfortunately This issue happan again. 
Like i mentioned My Luis ID is : 9d365832-90ce-428e-aab6-fdd91fff779d 

I do not chang any thing regarding the code. Could you give me some hits or suggestion?

As the bot was intertgate to the Skype for business channel already. For this issue impact our production.

Grateful if you could help me on this.

**Comment by band888888** [comment]
Hello guys @JasonSowers @nwhitmont @EricDahlvang @fanidamj , Unfortunately This issue happan again.
Like i mentioned My Luis ID is : 9d365832-90ce-428e-aab6-fdd91fff779d

I do not chang any thing regarding the code. Could you give me some hits or suggestion?

As the bot was intertgate to the Skype for business channel already. For this issue impact our production.

Grateful if you could help me on this.

**Comment by band888888** [comment]
I found it's strange. I test with the LUIS url:
https://westus.api.cognitive.microsoft.com/luis/v2.0/apps/9d365832-90ce-428e-aab6-fdd91fff779d?subscription-key=xxxx&verbose=true&timezoneOffset=0&q=Test sentense.

It return the message like:  A module xxxxxxx not trained yet, could not return.....after i trained the data again. My Bot back to normal. It could call the Luis again.

However i still confuse, normally i change anything on Luis.ai should not impact current call by our Bot. As the unchange pending on there and not publish yet. 

After that i try to repudurce the case again. I change some of my intention keyword, then without training. Seems the Luis still normally. 

It's strange. However, once appear next time i knew i could solve with training again. Thank you all.
