### ISSUE TITLE
[Skype Web Control] Bot on SWC not working?

### ISSUE THREAD

**Issue by polashivaprasad** [Microsoft/BotBuilder#4104]
**Bot Info**
SDK Platform:  .NET 
BOT ID:bfb7c99b-e303-457a-b8bb-99ec2c203d5e
 Active Channels:  Skype channel

**Issue Description**
Currently I trying out the bot framework onC#.net, but it seems like the bot on Skype is broken now, I can't open the skype window in browser it is works on  web chat and test channel. Till yesterday it is working suddenly it fails.

 **Code Example**
```html
<span class="skype-button bubble " data-bot-id="bfb7c99b-e303-457a-b8bb-99ec2c203d5e">
</span>
<script src="https://swc.cdn.skype.com/sdk/v1/sdk.min.js"></script>
```

 Actual Results
![chrome error](https://user-images.githubusercontent.com/10192487/35446622-34227dce-02ad-11e8-9460-cfb9ff54f04e.png)
![internetexplorer error](https://user-images.githubusercontent.com/10192487/35446623-3429d34e-02ad-11e8-8b10-78beeef0362f.png)

**Comment by nwhitmont** [comment]
Hi @polashivaprasad -- It looks like you are having issues with the Skype Web Control (SWC).

Have you tried using the official Bot Framework WebChat control? You can find the setup instructions here:

**Comment by brene** [comment]
@polashivaprasad can you confirm that this is still broken? I just tried it myself and seemed to work. If it works, please close this ticket.
