### ISSUE TITLE
[.Net SDK, Slack] Sent Attachments over 10 MB are null

### ISSUE THREAD

**Issue by drasticactions** [Microsoft/BotBuilder#4106]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.12.2.4
* Active Channels: Slack
* Deployment Environment: Azure Bot Service

## Issue Description
When a user attaches a file and sends it to my bot, it's expect that it'll take that attached file, upload it to Azure, and give a link back. However, if they're using Slack, when the attachment size is over 10 megabytes, `Attachments` is null. If it's _under_ that size, no matter what format the file is in, it will appear as an attachment. But once it goes over, it will be null, so I can't read the files and then upload them. 

In the web chat client and Teams, it works correctly. But in Slack, it fails.

This did work previously as of a few months ago, but now is broken. I was running a previous version of the SDK so I updated it to see if there was some kind of API break in the older SDK, but it's still broken on the newest SDK for me.

## Code Example
```cs
private async Task UploadFile(IDialogContext context, IMessageActivity message)
        {
            if (message.Attachments != null && message.Attachments.Any())
            {
                var attachment = message.Attachments.First();
                await UploadFile(context, new Uri(attachment.ContentUrl), attachment.Name);
            }
            else
            {
                await context.PostAsync("You need to attach a file to this message for this command to work.");
            }
        }
```

This is the `UploadFile` method that it's hitting, but just attaching a file in a Slack conversation and checking `message.Attachments` is enough to show that it's `null`.

## Reproduction Steps
1. Post a file in a Slack conversation with your bot
2. Check the resulting activity message for `Attachments`

## Expected Behavior
`Attachments` to have at least one value with the file posted.

## Actual Results
`Attachments` is null.

**Comment by JasonSowers** [comment]
This sounds like Slack has a file upload size limit, have you reached out to slack to ask them?  I was unable to find any documentation on their single file upload size limits.

**Comment by drasticactions** [comment]
The upload limit is [1 GB](https://get.slack.help/hc/en-us/articles/201330736-Upload-and-share-files). The files attached to the conversation appear correctly in Slack and can be downloaded from within it. It just seems that the bot can't find it if it's over a specific size.

**Comment by JasonSowers** [comment]
@drasticactions did you ever find a solution to this?

**Comment by drasticactions** [comment]
@JasonSowers Since the original post, we've updated to `3.14.1.1`, and it was still busted there.


I did come up with a workaround for it. Basically, we detect if it's coming from Slack. If it is, we can extract the `url_private_download` and the users ApiToken, and download the file ourselves.

```
if (message.ChannelData.SlackMessage != null)
                {
                    string url = message.ChannelData.SlackMessage.file.url_private_download.ToString();
                    string token = message.ChannelData.ApiToken.ToString();
                    await UploadFile(context, new Uri(url), Path.GetFileName(url), token);
                    return;
                }
```

**Comment by JasonSowers** [comment]
Glad you were able to get this working.

**Comment by KirillOsenkov** [comment]
@JasonSowers I'm running into this as well now. My understanding is that @drasticactions was able to find a temporary workaround to unblock himself, however this doesn't sound like a satisfactory long term solution. 

Would you please consider reopening the issue and seeing if you can fix the root cause? Much appreciated, since this is blocking our team now.
