### ISSUE TITLE
[Node.js SDK, Skype] Bot replies with duplicate messages in Skype channel?

### ISSUE THREAD

**Issue by wacoder** [Microsoft/BotBuilder#4108]
## Bot Info
* SDK Platform: Node.js
* SDK Version: 3.13.1
* Active Channels: Skype
* Deployment Environment: Deploy the bot on AWS lambda, use API.AI for intent detection

## Issue Description

Bot responses work well for the most time. But for some time, the bot responds duplicated messages. 

![image](https://user-images.githubusercontent.com/10132576/35459501-6bbf49f0-02ae-11e8-8920-791ce81f7fec.png)

As in above image, it should response only one welcome message, it turns out to be two. It only happen time by time. The bot is on AWS lambda, I can see that there are two requests from bot connector to the AWS. 

(And I tested it with facebook messager channel, it works well without duplicated messages. )

code: 

```js
bot.dialog('/restaurant.welcome', [
		function(session, args, next) {
			console.log("welcome intent launched.");

			session.privateConversationData.selection = [];
			session.privateConversationData.category = [];
			session.privateConversationData.checkout = false;
			var card = new builder.HeroCard(session)
			.title(welcome.name)
			.subtitle(welcome.subtitle)
			.text(welcome.text)
			.images([
					builder.CardImage.create(session, welcome.image)
			])
			.buttons([
				builder.CardAction.imBack(session, "New Order", "New Order"),
				builder.CardAction.imBack(session, "Reorder", "Reorder")
			]);


			var reply = new builder.Message(session)
				.addAttachment(card);
			session.endDialog(reply);
		}
]);
```

Question: 

Anyone has the same issue, why this happens, and any solution?

Thank you very much.

**Comment by JasonSowers** [comment]
Does this occur only if the user clicks a button or types a response, or if there is no response from the user for a couple minutes does the duplicate message still come?

**Comment by wacoder** [comment]
no, two replies are really close (the time difference between these two messages all under 1 second). 

![image](https://user-images.githubusercontent.com/10132576/35461265-23dcc41c-02b5-11e8-8f9e-6a9e685f989b.png)

As in the above image, most time it works well. But sometimes it replies twice.

**Comment by JasonSowers** [comment]
Are you able to share your code in it's entirety so we can try to reproduce and find the issue?

**Comment by RutgerKnijnenburg** [comment]
I appear to have the same issue using Skype (not for Business) with the dotnet SDK. Response messages are duplicated. The code used for responding to the user: await context.PostAsync(message);. Any fix released yet?

**Comment by cleemullins** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues


For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botbuilder-channels/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
