### ISSUE TITLE
Typescript examples?

### ISSUE THREAD

**Issue by mattlanham** [Microsoft/BotBuilder#411]
Hey, just wondering if this is TypeScript ready and if so, it'd be great to include some examples

**Comment by Stevenic** [comment]
It's written in TypeScript and yes it's TS ready.  In fact you don't even need to do the normal step of manually adding a .d.ts file to your project as there's one already bundled into the NPM module.

The primary reason there aren't any TS specific samples is that all of the examples should work out of the box with TypeScript if you just change the extension to ".ts". We didn't want to have to create and maintain two versions of every sample.

I can look into creating a TS version of one oft the more stable bot samples.

**Comment by mahbh2001** [comment]
I am looking for TS sample to begin. Since all samples are js , would be better to have some ts sample with type usage of botbuilder.

**Comment by kosalanuwan** [comment]
See if this helps you. May be now it's too late. While doing I have noticed there's not much of a difference between the Node version and the TS version.

[Bot Builder TypeScript Examples](https://github.com/alertbox/bot-examples-ts)
