### ISSUE TITLE
[Message Formatting] How to display data in table format?

### ISSUE THREAD

**Issue by mohit-agrawal226** [Microsoft/BotBuilder#4110]
## Bot Info
* SDK Platform: .NET

## Issue Description
I am getting tabular data from API that i want to display in table format.

**Comment by Ma3yTa** [comment]
@mohit-agrawal226 hi. try to use markdown but only skype, slack, telegram, webchat support it.

**Comment by mohit-agrawal226** [comment]
Thank you @Ma3yTa. I am looking for webchat only.

Can you please share some code snippet or link for .net ?

**Comment by Ma3yTa** [comment]
@mohit-agrawal226 

```csharp
var markdown = @"| 1 | 2 | 3 |
|---|---|---|
| 4 | 5 | 6 |
| 7 | 8 | 9 |";
            var message = context.MakeMessage();
            message.Text = markdown;
            message.TextFormat = Microsoft.Bot.Connector.TextFormatTypes.Markdown;
            await context.PostAsync(message);
```
