### ISSUE TITLE
[Skype] Getting error: "One or more of the user ids provided is not valid."

### ISSUE THREAD

**Issue by ranmax123** [Microsoft/BotBuilder#4111]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.12.2.4
* Active Channels: Skype, SfB, Web chat
* Deployment Environment: Azure Bot Service

## Issue Description
My bot is not responding on Skype channel. It gives following error.
400 bad request
"one or more of the user ids provided is not valid".
The bot works just fine on web chat.
You can check the demo of web chat here: https://goo.gl/kk9BMJ

## Code Example
Request URL: 
https://client-s.gateway.messenger.live.com/v1/users/ME/conversations/28:ac5fbb9b-975b-488c-a236-e7a157ae16b8/messages

App id: ac5fbb9b-975b-488c-a236-e7a157ae16b8

## Reproduction Steps
1. Open the bot in Skype
2. Type "hi"
3.

## Expected Behavior
The bot should respond with "hello, how can I help you?"

## Actual Results
400 bad request error

**Comment by nwhitmont** [comment]
Hi @ranmax123 - Great question. -- Can you post the bot code that causes the issue so we can better assist you?

**Comment by ranmax123** [comment]
Hi @nwhitmont the bot is working perfectly fine on web chat, you can try testing and chatting with bot. URL already mentioned above.
I just enabled Skype channel, but unfortunately it's not working. Can't share the code.

Any issue at SDK or MSFT end?

Thanks,

**Comment by ranmax123** [comment]
Glad, it started working now. Probably it takes some time to work
