### ISSUE TITLE
[Question] Why am I getting duplicated conversation message on begin dialog?

### ISSUE THREAD

**Issue by buehler** [Microsoft/BotBuilder#4112]
## Bot Info
* SDK Platform: Node.js v8.6
* SDK Version: v3.13.1
* Active Channels: WebChat
* Deployment Environment: Azure Bot Service

## Issue Description
The Bot does repeat it's welcoming messages. Actually we capture the `conversationUpdate` event of the bot and send some welcoming messages to a user (that is connected via webchat). In local development and as well as the deployed application (on azure via docker), when testing with the botframework-emulator app of microsoft, the error does not occur. However, when we test it with the webchat embedded code, the bot does duplicate those welcome messages (as shown in the screenshot, and the code example).

As soon as the greeting messages are stated, the bot asks the user for a choice (the menu). When the user selects such a choice, the greeting messages are called once again.

## Code Example
```js
// startup

bot.on('conversationUpdate', (update: IConversationUpdate) => {
    Logger.info(
        'Conversation update: %d added, %d removed',
        (update.membersAdded || []).length,
        (update.membersRemoved || []).length,
    );
    if (update.membersAdded && update.membersAdded.length && update.membersAdded[0].name !== 'Bot') {
        bot.beginDialog(update.address, '/');
    }
});

// dialog /

bot.dialog('/', (session) => {
    session.privateConversationData.sessionId = uuidv4();
    session.privateConversationData.sessionStart = new Date().getTime();
    Insights.trackEventWithSession(
        session.privateConversationData.sessionId,
        {
            name: 'DialogView',
            properties: {
                dialog: '/',
            },
        },
    );
    Insights.trackEventWithSession(
        session.privateConversationData.sessionId,
        {
            name: 'StartConversation',
        },
    );

    // Set locale for bot framework default messages
    session.preferredLocale('de', (err) => {
        if (err) {
            Logger.error('Wrong language, could not load.', lng, err);
        }
    });
    // Set locale for custom messages
    const lng = session.preferredLocale().substring(0, 2);
    i18next.changeLanguage(lng, (err) => {
        if (err) {
            Logger.error('Wrong language, could not load.', lng, err);
        }
        session.beginDialog('/menu');
    });
});

// dialog /menu

bot.dialog('/menu', [
    session => this.showOptions(session),
    (session, result) => this.handleUserResponse(session, result),
]);
```

As seen in this example, the bot should only greet the user once.

This is what happens: 
![2018-01-29t14 06 43-d218629e](https://user-images.githubusercontent.com/1067213/35512325-b88a0c9a-04ff-11e8-8898-1d2ffe7284f5.png)

## Reproduction Steps
1. As stated in code example.
2. Use the bot framework to proactively greet the user
3. test the bot on azure with webchat framework (not with the app)

## Expected Behavior
The bot should (like in the botframework-emulator) only greet the user once.

## Actual Results

![2018-01-29t14 24 23-2ef523f9](https://user-images.githubusercontent.com/1067213/35512521-4fc2a6bc-0500-11e8-9b2c-b93bc3790dfc.png)

**Comment by nwhitmont** [comment]
There are two `conversationUpdate` events that get emitted -- one for the bot joining the conversation, and one for the (human) user joining the conversation. 

You can filter out one of those events and respond with a single "welcome message" using the following code:

https://gist.github.com/nwhitmont/d9910fcf7ab4048ee37bd5c789cfc375

**Comment by buehler** [comment]
Hey @nwhitmont 
yea we already saw that.. that was part of the first problem when we used conversation Update :-)

but 
```typescript
if (update.membersAdded && update.membersAdded.length && update.membersAdded[0].name !== 'Bot') {
        bot.beginDialog(update.address, '/');
    }
```

with this snipped it's filtered. the logs we use do state that the update is called exactly once (as it should) but the chat bot does repeat it's messages

**Comment by buehler** [comment]
Ping?
@nwhitmont or @FranciscoPonceGomez  ?

**Comment by buehler** [comment]
IMO this is a bug... and not really a question ;)

**Comment by Stevenic** [comment]
Try changing your filtering code to the below:

```
    if (update.membersAdded && update.membersAdded.length && update.membersAdded[0].id !== update.address.bot.id) {
        bot.beginDialog(update.address, '/');
    }
});
```

Every channel is likely to assign a different `id` & `name` for your bot.

**Comment by buehler** [comment]
Hey @Stevenic 
So I found out something: This _only_ happens when you use webchat and you want to use the `conversationUpdate` event to proactively greet the user. When we comment out the code, and the user needs to say `Hi`, it works.

**Comment by maxwell-k** [comment]
I am seeing exactly the same issue with different code. For me I trigger `beginDialog` which calls `Prompt` and the `Prompt` is unexpectedly repeated a second time.

**Comment by EricDahlvang** [comment]
This is a known issue.  A workaround is explained here: https://github.com/Microsoft/BotBuilder/issues/4245#issuecomment-369311452
