### ISSUE TITLE
[Logging] How to get analytics by messages?

### ISSUE THREAD

**Issue by verdysh** [Microsoft/BotBuilder#4115]
## Bot Info
* SDK Platform: .NET
* Deployment Environment: local development

## Issue Description
Hi!

I included the collection of analytics in the bot with free subscription. Through portal.azure.com I switch to analytics.applicationinsights.io and there I can see what happens with bot.

I'm trying to execute the following query:
```
customEvents
| where customDimensions.from == my_id
```

As a result, I get a set of records. But among the information received, I do not see what exactly the user wrote to the bot.

Can I somehow get statistics about what users are writing to the bot and what does it answer them?

**Comment by JasonSowers** [comment]
Yes, you can implement [IActivityLogger](https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-middleware).  Take a look at [this sample](https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/core-Middleware).  Here is a simple implementation I did which serializes activities into a JSON string and stores then in a SQL DB:
```CS
    public class EntityFrameworkActivityLogger : IActivityLogger
    {

#pragma warning disable 1998
        public async Task LogAsync(IActivity activity)
        {
            IMessageActivity msg = activity.AsMessageActivity();
            if (msg != null)
            {
                using (Data.ConversationDataContext dataContext = new Data.ConversationDataContext())
                {
                    var newActivity = Mapper.Map<IMessageActivity, Data.Activity>(msg);
                    if (string.IsNullOrEmpty(newActivity.Id))
                    {
                        newActivity.Id = Guid.NewGuid().ToString();
                    }
                    newActivity.Json = JsonConvert.SerializeObject(activity);
                    dataContext.Activities.Add(newActivity);
                    dataContext.SaveChanges();
                }
            }
        }
    }
```

**Comment by verdysh** [comment]
@JasonSowers, thanks!
