### ISSUE TITLE
[Skype] Message formatting: Cannot add break line \n\n into the message?

### ISSUE THREAD

**Issue by chuotnhat1985** [Microsoft/BotBuilder#4116]
## Bot Info
* SDK Platform:  .NET 
* SDK Version:  SDK 4.6.1
* Active Channels: Skype 7.40.0.151
* Deployment Environment: IIS 7.0

## Issue Description
As title, I cannot add break line \n\n or <br/> into the message on Skype

## Code Example
                var connector = new ConnectorClient(conversation.ServiceUrl);
                IMessageActivity activityMessage = Activity.CreateMessageActivity();

                activityMessage.ChannelId = conversation.ChannelId;
                activityMessage.From = botAccount;
                activityMessage.Recipient = userAccount;
                activityMessage.Conversation = new ConversationAccount(id: conversation.ConversationId);
                activityMessage.Text = "abc \n\n xyz";
                activityMessage.Locale = "en-Us";
                activityMessage.TextFormat = TextFormatTypes.Markdown;
                Microsoft​App​Credentials.TrustServiceUrl(conversation.ServiceUrl.ToString());

                var result = connector.Conversations.SendToConversationAsync((Activity)activityMessage);

![image](https://user-images.githubusercontent.com/5300869/35561744-ddc0a0a2-05e3-11e8-9303-fc6eddbf1e70.png)

**Comment by chuotnhat1985** [comment]
Skype version 7.40.0.151. Are there any difference between CreateReply and CreateMessageActivity. I made anything, but still not break line in the skype.

**Comment by JasonSowers** [comment]
I tried with your code to reproduce this as well, and was unable to reproduce.

**Comment by chuotnhat1985** [comment]
This is full code that using to send the message to skype group when bot get the data from database. Conversation object is a model. You can change the other one.
`var userAccount = new Microsoft.Bot.Connector.ChannelAccount
                {
                    Id = conversation.Sender.Id,
                    Name = conversation.Sender.Name
                };

                var botAccount = new Microsoft.Bot.Connector.ChannelAccount
                {
                    Id = conversation.Recipient.Id,
                    Name = conversation.Recipient.Name
                };

                var connector = new ConnectorClient(conversation.ServiceUrl);
                IMessageActivity activityMessage = Activity.CreateMessageActivity();

                activityMessage.ChannelId = conversation.ChannelId;
                activityMessage.From = botAccount;
                activityMessage.Recipient = userAccount;
                activityMessage.Conversation = new ConversationAccount(id: conversation.ConversationId);
                activityMessage.Text = message;
                activityMessage.Locale = "en-Us";
                activityMessage.TextFormat = TextFormatTypes.Markdown;
                Microsoft​App​Credentials.TrustServiceUrl(conversation.ServiceUrl.ToString());

                var result = connector.Conversations.SendToConversationAsync((Activity)activityMessage);`

**Comment by band888888** [comment]
hi @JasonSowers on skype for business it's not working with \n\n. I test with bot simulator and web channel it's working. Any suggestion?

**Comment by JasonSowers** [comment]
Please open a new issue if you are experiencing problems still.
