### ISSUE TITLE
[Question] Why am I getting error: "There was an error sending this message to your bot: HTTP status code GatewayTimeout?

### ISSUE THREAD

**Issue by rupjit** [Microsoft/BotBuilder#4118]
## Bot Info
* SDK Platform: .NET
* Active Channels:  Web Chat, Direct Line

## Issue Description
Bot is developed using SDK & deployed on corporate server. Same bot is published on internet (https://testmy.ebharatgas.com/bitsy/api/messages) & registered with Bot channel of azure.Certificate is also vaild.

When we are trying to test the web chat getting following error, 

"There was an error sending this message to your bot: HTTP status code GatewayTimeout". Please suggest. When we test locally inside corporate network its working.

**Comment by JasonSowers** [comment]
Please provide us with your code so we may try to reproduce.

**Comment by rupjit** [comment]
HI , its just the default code (returns no of character entered in chat box ). Only addition is  Microsoft APP ID /Password used in web.config.

**Comment by rupjit** [comment]
Dear Members,

I have an update here,

In the IIS log where my bot is hosted,  i find http code 200,
-------------------------------------------------------------------------------------------------------------
2018-01-31 06:54:35 W3SVC1 CDCVGAEBIZ1T 10.72.54.54 POST /bitsy/api/messages - 80 - 10.72.9.44 BF-DirectLine+(Microsoft-BotFramework/3.2++https://botframework.com/ua) - testmy.ebharatgas.com 200 0 0 62 137.116.153.103
2018-01-31 06:55:26 W3SVC1 CDCVGAEBIZ1T 10.72.54.54 POST /bitsy/api/messages - 80 - 10.72.9.44 BF-DirectLine+(Microsoft-BotFramework/3.2++https://botframework.com/ua) - testmy.ebharatgas.com 200 0 0 46 137.116.153.103
-------------------------------------------------------------------------------------------------------------
But still in azure portal (web chat test) i get following error,

**"There was an error sending this message to your bot: HTTP status code GatewayTimeout"**


PLZ HELP

**Comment by EricDahlvang** [comment]
Hi @rupjit 

What is your BotHandle? What is the Messaging endpoint in the bot's settings?

**Comment by rupjit** [comment]
@EricDahlvang : I want to update that , After enabling [botauthentication] in message controller , now i am getting 401 error, though my credentials are correct .I have a question, do i need to open outgoing connection also from my IIS server to internet. I am reading this post https://github.com/Microsoft/BotBuilder/issues/2266

**Comment by rupjit** [comment]
Just to confirm issue is resolved
