### ISSUE TITLE
Handle inline mode on telegram

### ISSUE THREAD

**Issue by fercom** [Microsoft/BotBuilder#412]
Hi, I am developing my bot using Bot Framework on C#, uses LUIS, currently doesn't supports telegram's inline mode, How do I test an inline mode query using Microsoft Bot Framework Emulator?

Here it is my bot, if you want to test it:

[http://memegeneratorbot.azurewebsites.net](url)

[https://telegram.me/the_MemeBot](url)

[https://join.skype.com/bot/c0b2fa87-3625-43b2-be12-8eb1675818bb](url)

[https://www.facebook.com/MemeBot-1118345044889141/](url)

Thanks

**Comment by eanders-MS** [comment]
We pushed a fix for this yesterday. Telegram's inline query mode should now be supported. See #366 for a sample inline query reply (in Javascript/Node.js).

**Comment by fercom** [comment]
Yes, I know, I just want to know how to to test this functionality using the Microsoft Bot Framework Emulator because I don't know how will my bot handle the inline queries

**Comment by eanders-MS** [comment]
Oh, gotcha. I misunderstood. You can run your bot locally and test from Telegram. Use [Ngrok](https://ngrok.com) to tunnel messages between the Bot Framework service and your bot running on localhost.

1. Install Ngrok
2. Running your bot locally in the debugger
3. Run Ngrok like this `C:\ngrok\ngrok.exe http 3074`, it will give you an endpoint like https://fd538d99.ngrok.io
4. Edit your bot's registration details, making the ngrok address your new endpoint
5. Validate the connection is working using the web form on your bot registration page

Now you should be set up to for local bot debugging from Telegram, or any other service. Don't forget to switch your endpoint back to https://memegeneratorbot.azurewebsites.net when you're done! :)

**Comment by fercom** [comment]
@eanders-MS Excelent, now, how do i create an inline query reply with c#? I am working with images

**Comment by fercom** [comment]
@eanders-MS Ok, I have the inline query reply, but the method returns a Microsoft.Bot.Connector.Message Task, should I create another method for returning the inline query reply? Thanks

**Comment by fercom** [comment]
`  public async Task<Message> Post([FromBody]Message message)
        {

            try
            {
                string requisicion = String.Empty;
                if (string.IsNullOrWhiteSpace(message.Text))
                {
                    if (message.From.ChannelId == "telegram")
                    {
                        JToken token = JObject.Parse(message.ChannelData.ToString());
                        string query = (string)token["inline_query"]["query"];
                        string queryId = (string)token["inline_query"]["id"];

                        message.Text = query;

                        var attachmentsInResponse = await Conversation.SendAsync(message, () => new MemeBotDialog());

                        JObject respuestaInline = 
                            new JObject(
                            new JProperty("method", "answerInlineQuery"),
                            new JProperty("Parameters",
                                new JObject(
                                    new JProperty("inline_query_id", queryId),
                                    new JProperty("results",
                                        new JArray(
                                            from a in attachmentsInResponse.Attachments
                                            select
                                            new JObject(
                                                new JProperty("type", "photo"),
                                                new JProperty("id", ""),
                                                new JProperty("title", ""),
                                                new JProperty("photo_url", a.ContentUrl),
                                                new JProperty("thumb_url", a.ContentUrl)
                                                )

                                            )
                                        )

                                )
                                )


                            );

                        var respuestaJson = respuestaInline.ToString();


                    }
                }



                message.Text = RemoveSpecialCharacters(message.Text);
                var resultadoLuis = await Conversation.SendAsync(message, () => new MemeBotDialog());


                return resultadoLuis;
            }
            catch (Exception e)
            {
                var msj = e.Message;
                throw;
            }


        }`

**Comment by eanders-MS** [comment]
"Parameters" should be all lowercase: "parameters".

**Comment by eanders-MS** [comment]
"id" is a required field and cannot be blank.

**Comment by fercom** [comment]
Ok, I have edited it, I am returning the JObject, still nothing happens in telegram

**Comment by fercom** [comment]
I figured it out! I need to make my Message.ChannelData=attachmentsInResponse 

Thanks for the help!
