### ISSUE TITLE
[.Net SDK, Prompts] How to recognize misspelled choices in PromptDialog

### ISSUE THREAD

**Issue by AyoubHaggui** [Microsoft/BotBuilder#4124]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.12.2.4
* Deployment Environment: Azure Bot Service
## Issue Description
How to recognize misspelled choices in PromptDialog
## Code Example
PromptDialog.Choice<string>(context, ProcessIntentSelection, options);
....
 private async Task ProcessIntentSelection(IDialogContext context, IAwaitable<string> result)
{
      String choice = await result;
}

## Expected Behavior
The prompt dialog should map user choice to one of the prompted choices if it's some form of confirmation

## Actual Results
1. Prompt user to choose Example: yes or no
2. User types "yep" or "yeaah"
3. PromptDialog detects an invalid choice and asks the user to choose again

**Comment by medbenmahmoud** [comment]
You can extend PromptDialog.PromptChoice
Example : https://github.com/Microsoft/BotBuilder-Samples/blob/master/CSharp/demo-ContosoFlowers/ContosoFlowers.BotAssets/Dialogs/CancelablePromptChoice.cs

**Comment by onssatoripop** [comment]
Same issue here, thx for posting it ayoub. 
Hope that someone already found a proper solution and of course that "someone" must be cool enough to post it here so we can use it. 🤣

**Comment by AyoubHaggui** [comment]
@medbenmahmoud problem with this approach is the developer needs to provide all the variations of the choice which is not practical especially if you have nanny prompt dialogs with lots of choices.

**Comment by fanidamj** [comment]
Can you please let us know if the issue still persists?

**Comment by AyoubHaggui** [comment]
I actually gave up using the builtin PromptDialog, I found a workaround using either a HeroCard or SuggestedActions to prompt the user with options, I intercept the text of the response and send it to LUIS to get the entities and map them back to the list of options. This gives the user more flexibility when making his choice. Enough talk, Here is the code sample for a yes/no prompt: 

First of all create a method responsible for hitting LUIS endpoint and getting the response back.

`
public async Task<LuisResult> GetLuisResponse(string message)
        {
            var luisModelID = WebConfigurationManager.AppSettings["LuisModelId"];
            var luisSubscriptionKey = WebConfigurationManager.AppSettings["LuisSubscriptionKey"];
            var luisDomain = WebConfigurationManager.AppSettings["LuisDomaine"];
            var modelAttribute = new LuisModelAttribute(luisModelID, luisSubscriptionKey, apiVersion: LuisApiVersion.V2, domain: luisDomain);
            var luisService = new LuisService(modelAttribute);
            return await luisService.QueryAsync(message, CancellationToken.None);
        }
`
You need to train LUIS to recognize the entity associated with the choice, you can make use of the list entities as such

![confirmation](https://user-images.githubusercontent.com/11796389/41763926-7d22cc14-75f7-11e8-8e77-22263316cf81.PNG)

`
public class RootDialog : IDialog<object>
    {
        public Task StartAsync(IDialogContext context)
        {
            var confirmationSuggestions = new SuggestedActions()
            {
                Actions = new List<CardAction>()
                {
                    new CardAction()
                    {
                        Title = "Yes",
                        Value = "Yes",
                        Type = ActionTypes.PostBack
                    },
                    new CardAction()
                    {
                        Title = "No",
                        Value = "No",
                        Type = ActionTypes.PostBack
                    },
                    new CardAction()
                    {
                        Title = "Not Sure",
                        Value = "Not Sure",
                        Type = ActionTypes.PostBack
                    }
                }
            };
            var reply = context.MakeMessage();
            reply.SuggestedActions = confirmationSuggestions;
            //Wait for usr input
            context.Wait(ConfirmationInput);
        }

        private async Task ConfirmationInput(IDialogContext context, IAwaitable<object> result)
        {
            var activity = await result as Activity;
            var confirmationText = activity.Text;
            //Hit LUIS endpoint to get response
            var LuisResult = await NLUService.GetLuisResponse(confirmationText);
            var confirmationEntity = LuisResult.Entities.FirstOrDefault(entity => entity.Type == "Confirmation");
            if(confirmationEntity != null)
            {
                //Resolve list entity
                var confirmationResolution = confirmationEntity.ResolveListEntity();
                if(String.Equals(confirmationResolution, "Yes"))
                {
                    await context.PostAsync("Positive");
                }
                else if(String.Equals(confirmationResolution, "No"))
                {
                    await context.PostAsync("Negative");
                }
                else
                {
                    await context.PostAsync("User not sure");
                }
            }
            else
                await context.PostAsync("Invalid choice");
            context.Done(string.Empty);
        }
    }
`

**Comment by EricDahlvang** [comment]
Glad you've found a workaround.  Closing this issue.
