### ISSUE TITLE
[Question] Unable to tell it's a button click event or just text message

### ISSUE THREAD

**Issue by boydc2014** [Microsoft/BotBuilder#4125]
## Bot Info
* SDK Platform: .NET
* SDK Version:  3.12.2.4 
* Active Channels: Facebook
* Deployment Environment: Azure App Service 

## Issue Description
My bot would send a series of cards with some buttons on each card. By clicking the button step by step, the user are making choices. 

I'm using **CardAction.Type = ImBack,** because I want the choice is visible to the conversation. 

The problem is some choices may have the same text.  For example
![image](https://user-images.githubusercontent.com/3829387/35614981-cbab9930-06ab-11e8-9753-f334703b3f1c.png)

So, **I cannot tell which button user is clicking, since they have same text value**

Also, at certain steps of the flow,  the bot would collect some info from user, and info user click would also be as same as button title.  For example
![image](https://user-images.githubusercontent.com/3829387/35615453-1f9d1ffe-06ad-11e8-9e59-ed2f474b42db.png)

So **I cannot tell whether user is click the button in card, or user type something to answer my bot's question.**  

## Expected Behavior
I expect either 
a) from the activity object received after button click, I can tell it's a button click (not text message) 
or
b) when ActionType=ImBack, there can also be another hidden field sent to backend to encode sth. Because if using CardAction.Type = PostBack, I can encode sth in the value property, then decode the value, to indicate it's a button click.

## Actual Results

But in this case, from the activity object got after button click, I couldn't tell if it's text message or button click. And with ImBack, nothing is hide from end user.

**Comment by Danieladu** [comment]
Maybe CardAction.DisplayText works. But it seems not work for C# SDK.
We have met the same issue.

**Comment by JasonSowers** [comment]
I am investigating this looking for a workaround.  In the next release, there will be a card action that you can use called `invoke` which send a JSON payload with the button click.  I'm trying to find out when that will be released.

**Comment by boydc2014** [comment]
Hi, @JasonSowers, thanks for quick update. Looking forward to see the update. One remaining question is 
if I use invoke or adaptive card, with JSON payload, can I still make the message visible to users?

I didn't see options like ImBack in adaptive card, their is only ActionSubmit, which looks like won't show in conversation

**Comment by boydc2014** [comment]
@JasonSowers  Tried Adaptive card, submit with Json payload works fine, but doesn't have the ImBack like effect that the message is visible in conversation which isn't ideally. 

Will this new "invoke" approach do that? because If we don't want the message is shown in conversation, we can just encode sth in value property and set the type to PostBack.

**Comment by JasonSowers** [comment]
Honestly, my best advice for the time being right now is to use postback.
