### ISSUE TITLE
iFrame jQuery issues

### ISSUE THREAD

**Issue by NotMyRealName1234** [Microsoft/BotBuilder#4127]
I created a jQuery UI Accordion popout widget 

  $( function() {
    $( "#accordion" ).accordion({
      collapsible: true,
      active: false
    });
  });

This basically makes a little picture in the bottom right of a SharePoint 2013 page act as an accordion. This works but I have noticed it is interfering with the rendered code within the iFrame. 

Specifically the arrows on the carousel within the iFrame channel stop working. 

I have looked at the CSS @ https://webchat.botframework.com/css/webchat-stable/botchat.css and I can see no conflicting ID's.

So far I am stuck and googling has rendered nothing useful to me yet.

**Comment by JasonSowers** [comment]
@NotMyRealName1234  please post this issue on the [webchat repo](https://github.com/Microsoft/BotFramework-WebChat/issues/new).  The question is more appropriate for that forum
