### ISSUE TITLE
DictionaryBotData doesn't work because of deserialisation 

### ISSUE THREAD

**Issue by gareththackeray** [Microsoft/BotBuilder#4128]
## Bot Info
* SDK Platform: .NET
* SDK Version: latest
* Active Channels: any
* Deployment Environment: any

## Issue Description
In the bot builder code there is an `IBotData` implementation called `DictionaryBotData`.  This implementation doesn't work when the `IBotDataBag.Data` (which is an `object`) gets deserialised from the store it gets deserialised to a `JObject`.

## Code Example
       
            Conversation.UpdateContainer(builder =>
            {
                builder.RegisterKeyedType<DictionaryBotData, IBotData>()
                    .AsSelf()
                    .InstancePerLifetimeScope();

                builder.RegisterAdapterChain<IBotData>
                    (
                        typeof(DictionaryBotData),
                        typeof(DialogTaskManagerBotDataLoader)
                    )
                    .InstancePerLifetimeScope();

                builder.Register(c => new DialogTaskManager(DialogModule.BlobKey,
                    c.Resolve<DictionaryBotData>(),
                    c.Resolve<IStackStoreFactory<DialogTask>>(),
                    c.Resolve<Func<IDialogStack, CancellationToken, IDialogContext>>(),
                    c.Resolve<IEventProducer<IActivity>>())).AsSelf()
                    .As<IDialogTaskManager>()
                    .As<IDialogTasks>()
                    .InstancePerLifetimeScope(); ;
            });

## Reproduction Steps
1. Send 2 messages to a bot with the above overrides.

## Expected Behavior
Bot should work as normal.

## Actual Results
On the 2nd message there will be a cast exception from `BotDataBase<Dictionary<string, object>>.LoadAsync()`.

**Comment by gareththackeray** [comment]
Created PR https://github.com/Microsoft/BotBuilder/pull/4129

**Comment by FranciscoPonceGomez** [comment]
Hi gareththackeray,

Thanks for bringing up this issue and providing a fix. I will review it as soon as possible.

Regards,
Francisco

**Comment by FranciscoPonceGomez** [comment]
Can I ask you if there is any reason why you can't use JObjectBotData class instead of DictionaryBotData for your solution?

https://github.com/Microsoft/BotBuilder/blob/db2b8f860a3d8f7744a378930f93c4b0baa97978/CSharp/Library/Microsoft.Bot.Builder/ConnectorEx/BotData.cs#L633

**Comment by gareththackeray** [comment]
Thanks for getting back so quickly @FranciscoPonceGomez.

We have been using JObjectBotData until now.  But the reason we want to use DictionaryBotData is basically so can have one POCO in PrivateConversationData with all the data we might need to store about the conversation.  Then we can get this one object from PrivateConversationData and read or set whatever properties we like, which will be stored in memory until the end of the request when they will be flushed to the underlying store. 

To use JObjectBotData in this way we'd have to remember to call SetValue after each change we make.

I've actually thought about this a bit more and I think the problem might actually be because we implemented our own `IBotDataStore` which doesn't use binary serialisation.

**Comment by FranciscoPonceGomez** [comment]
Awesome. Let me know if you can rework your implementation of IBotDataStore to serialize in a different way. I would prefer not to add the responsibility of type checking/edge cases to DictionaryBotData. 

Let me know if you keep getting this issue.

Francisco

**Comment by JasonSowers** [comment]
Any update on this @gareththackeray?

**Comment by FranciscoPonceGomez** [comment]
Closing this issue.
