### ISSUE TITLE
Receiving Microsoft.Bot.Schema.BotTimeoutException for the past few hours

### ISSUE THREAD

**Issue by Kannaj** [Microsoft/BotBuilder#4130]
## Bot Info
* SDK Platform: Node.js
* SDK Version: 3.11.0
* Active Channels: Directline, Slack, Teams, Cortana
* Deployment Environment: Azure Bot Service, Azure App Service

## Issue Description
On our directline channel , we seem to be constantly getting the below errors (viewed on our app insights). This is affecting both our production and test bots

Microsoft.Bot.Schema.BotTimeoutException

details:
[{"parsedStack":[{"assembly":"Microsoft.Bot.ChannelConnector, Version=3.2.0.3, Culture=neutral, PublicKeyToken=null","method":"Microsoft.Bot.ChannelConnector.BotAPI+<PostActivityToBotAsync>d__29.MoveNext","level":0,"line":0}],"outerId":"0","message":"POST to PocketConfidant timed out after 15s","type":"Microsoft.Bot.Schema.BotTimeoutException","id":"11498889"}]

Can someone please explain what the error is and how one can go about fixing this?

## Expected Behavior
No timeout expected

## Actual Results
consistent Microsoft.Bot.Schema.BotTimeoutException occuring for the past few hours

## Stack
we have 2 servers (one hosting the bot logic and one hosting the webUI - both of these communicate via the directline API)

We're also using azure storage to handle our bot state

any help in deciphering this would be immensely helpful

THanks,
KJ

**Comment by EricDahlvang** [comment]
Hi @Kannaj 

Please supply your Microsoft Application Id, and BotHandle so we can investigate further.

**Comment by Kannaj** [comment]
@EricDahlvang  - 

MSA ID - 71fad264-9fd6-4ecd-808d-becdbc3b7eb1
handle - PocketConfidant

Thank you for your help

**Comment by EricDahlvang** [comment]
I'm not seeing anything specific that would indicate an issue on our end.  Generally, when we see timeout exceptions, it is due to a long running process within the bot's code.  

Some things to check/try:

- Ensure there is no code within the bot that could possibly take more than 15 seconds to process, and make it an asynchronous operation if there is.

- Upgrade to the latest SDK version (3.14.0): https://www.npmjs.com/package/botbuilder (this PR has the potential to improve performance: https://github.com/Microsoft/BotBuilder/commit/3ab2548b872a489e87c82408d1f64a68443ddbbc )

- Review https://blog.botframework.com/2017/11/02/optimizing-latency-bot-framework/ for possible performance improvements

**Comment by Kannaj** [comment]
@EricDahlvang - thanks , will look into the 3 and get back to you.

We currently run 2 separate servers , 1 to handle the webUI bot chat (uses the directline API) and 1 where the bot logic resides.

for users accessing the bot through the WebUI , we give the option of starting specific dialogs right from the beginning (as opposed to starting at the root dialog). To that effect , we send a POST request from the webUI server to the bot logic server to allow starting a new dialog. the handler for the request at the Bot logic server is like the below

    server.post('/beginSpecialDialog', function(req,res,next){
        var _body = req.body;
        bot.beginDialog(_body._directlineAddress, _body._dialogId, _body._specialParams, function(err){
            if(err){
                logger("warn", "server", "error occured on starting main dialog from url", null, {"conversationId": _body._directlineAddress.conversation.id, "err":err});
                res.send(400, {"err": err.stack });
                return next();
            }
            else{
                res.send(200);
                return next();
            }
        });
    });

This route seems to be the main bottleneck with regards to performance. Am i doing something wrong here? Are there better alternatives that allow specific the WebUI to start with specific dialogs

**Comment by EricDahlvang** [comment]
@Kannaj Your method seems valid to me.

I'm closing this issue.  If you run into further problems, please open a new issue.

**Comment by GladysEsther** [comment]
Exception : Microsoft.Bot.Schema.BotTimeoutException 
Exception Message :  POST to <botname> timed out after 15s
Exception Group : Microsoft.Bot.Schema.BotTimeoutException at Microsoft.Bot.ChannelConnector.BotAPI+<PostActivityToBotAsync>d__29.MoveNext

During this error mail did not get picked up by the bot, any idea why this timeout happens ?

**Comment by infact** [comment]
We are getting this error
POST to outbot-test-dev timed out after 15s
Problem Id:Microsoft.Bot.Schema.BotTimeoutException at Microsoft.Bot.ChannelConnector.BotAPI+&lt;PostActivityToBotAsync&gt;d__36.MoveNext

Any solutions ?
