### ISSUE TITLE
[.Net SDK, LUIS] Bot Framework not call LUIS intent after upgrade to 3.13.0.3

### ISSUE THREAD

**Issue by grupobernier** [Microsoft/BotBuilder#4134]
## Bot Info
* SDK Platform: .Net
* SDK Version: 3.13.0.3
* Active Channels: Web
* Deployment Environment: Azure Web App, LUIS and local

## Issue Description

0down votefavorite | I upgrade my bot framework to 3.13.0.3 and my LUIS dialog stop working. My bot start but when I write the word about the intent the bot show again the initial message and stay in this loop.I did verify the app ID and key, If I make a request to LUIS from the browser it works fine, but from the bot is like not make the request.I did train and publish the LUIS model againFrom visual studio and Azure deployment the behavior is the same, when type the LUIS intent the bot shows again the start message. The LUISIntent is in spanish "vacantes" or "registrar"Before the upgrade the bot works fine and the LUIS dialog works.
-- | --

## Code Example
using System;
using System.Threading.Tasks;
using Microsoft.Bot.Builder.Dialogs;
using Microsoft.Bot.Connector;
using MP_BotMVP.SupportClasses;
using Microsoft.Bot.Builder.Luis;
using Microsoft.Bot.Builder.Luis.Models;
using System.Collections.Generic;
using System.Configuration;
using System.Threading;

namespace MP_BotMVP.Dialogs
{
    [Serializable]
    public class RootDialog : LuisDialog<object>
    {
        public RootDialog() : base(new LuisService(new LuisModelAttribute(
            ConfigurationManager.AppSettings["LuisAppId"],
            ConfigurationManager.AppSettings["LuisAPIKey"],
            domain: ConfigurationManager.AppSettings["LuisAPIHostName"])))
        {
        }

        [LuisIntent("")]
        [LuisIntent("None")]
        public async Task None(IDialogContext context, LuisResult result)
        {
            string strUserName = "Usuario";
            try
            {
                strUserName = context.UserData.GetValue<string>(DialogText.UserNameKey);
            }
            catch { }

            string message = string.Format(DialogText.No_Endiendo,strUserName);

            await context.PostAsync(message);

            context.Wait(this.MessageReceived);
        }

        public override Task StartAsync(IDialogContext context)
        {
            context.Wait(this.MessageReceivedAsync);

            return Task.CompletedTask;
        }

        private async Task MessageReceivedAsync(IDialogContext context, IAwaitable<object> result)
        {
            await this.SendWelcomeMessage(context);
        }

        private async Task SendWelcomeMessage(IDialogContext context)
        {
            await context.PostAsync($"{DialogText.Saludo_Inicial}");

            PromptDialog.Text(context, this.GetUserNameAfter, DialogText.Pedir_Nombre);
        }

        private async Task GetUserNameAfter(IDialogContext context, IAwaitable<object> result)
        {
            var userName = await result;

            context.UserData.SetValue(DialogText.UserNameKey, userName);

            await context.PostAsync(string.Format(DialogText.Bienvenido, userName.ToString()));
        }

        [LuisIntent("Saludo y Presentacion")]
        public async Task Greetings(IDialogContext context, IAwaitable<IMessageActivity> activity, LuisResult result)
        {
            await this.SendWelcomeMessage(context);
        }

        [LuisIntent("Registrar CV")]
        public async Task RecordCV(IDialogContext context, IAwaitable<IMessageActivity> activity, LuisResult result)
        {
            string strUserName = context.UserData.GetValue<string>(DialogText.UserNameKey);

            string strLink = System.Configuration.ConfigurationManager.AppSettings["MP_CV_Url"];
            string strResponse = string.Format(DialogText.Registrar_CV, strUserName, strLink);

            await context.PostAsync(strResponse);

            await this.SendMayIHelp(context);
        }

        [LuisIntent("Buscar Vacantes")]
        public Task SearchJob(IDialogContext context, IAwaitable<IMessageActivity> activity, LuisResult result)
        {
            string strUserName = context.UserData.GetValue<string>(DialogText.UserNameKey);

            string strResponse = string.Format(DialogText.Buscar_Vacante, strUserName);

            PromptDialog.Text(context, this.SearchJobAfter, strResponse);

            return Task.CompletedTask;
        }

        private async Task SearchJobAfter(IDialogContext context, IAwaitable<object> result)
        {
            var userCity = await result;

            context.UserData.SetValue(DialogText.UserSelectedCityKey, userCity);

            PromptDialog.Text(context, this.SearchJobAreaAfter, DialogText.Buscar_Area);
        }

        private async Task SearchJobAreaAfter(IDialogContext context, IAwaitable<object> result)
        {
            var userArea = await result;

            context.UserData.SetValue(DialogText.UserSelectAreaKey, userArea);

            string strUserName = context.UserData.GetValue<string>(DialogText.UserNameKey);
            string strUserCity = context.UserData.GetValue<string>(DialogText.UserSelectedCityKey);
            string strUserArea = context.UserData.GetValue<string>(DialogText.UserSelectAreaKey);
            string strLink = System.Configuration.ConfigurationManager.AppSettings["MP_CV_Url"];

            string strResponse = string.Format(DialogText.Buscando_Vacante, strUserName, strUserCity, strUserArea);

            await context.PostAsync(strResponse);

            List<string> l_strOpps = SQLDB.Get_Opportunities(strUserCity, strUserArea);

            if (l_strOpps.Count > 0)
            {
                await context.PostAsync(string.Format(DialogText.Si_Resultados, strUserName, l_strOpps.Count));
                foreach (string str in l_strOpps)
                {
                    await context.PostAsync(str);
                }

                await context.PostAsync(string.Format(DialogText.Vacantes_InfoExtra, strUserName, strLink));

                await this.SendMayIHelp(context);
            }
            else
            {
                await context.PostAsync(DialogText.No_Resultados);

                PromptDialog.Text(context, this.SearchJobAreaAfter, DialogText.No_Resultados_Nuevamente);
            }
        }

        [LuisIntent("Ayuda Adicional")]
        public async Task GetInfo(IDialogContext context, IAwaitable<IMessageActivity> activity, LuisResult result)
        {
            string strUserName = context.UserData.GetValue<string>(DialogText.UserNameKey);

            string strResponse = string.Format(DialogText.Ayuda_Adicional, strUserName);

            await context.PostAsync(strResponse);
        }

        private async Task SendMayIHelp(IDialogContext context)
        {
            await context.PostAsync(DialogText.Mas_Ayuda);
        }

        [LuisIntent("Calificar")]
        public Task GetFeedback(IDialogContext context, IAwaitable<IMessageActivity> activity, LuisResult result)
        {
            foreach (var ent in result.Entities)
            {
                if ((ent.Entity.ToLower() == "si") || (ent.Entity.ToLower() == "calificar"))
                {
                    PromptDialog.Text(context, this.FeedbackAfter, DialogText.Calificar);
                }
            }

            return Task.CompletedTask;
        }

        private async Task FeedbackAfter(IDialogContext context, IAwaitable<object> result)
        {
            var userFeedback = await result;

            //TODO --> Grabar en la DB

            string strUserName = context.UserData.GetValue<string>(DialogText.UserNameKey);
            string strResponse = string.Format(DialogText.Despedida, strUserName);
            await context.PostAsync(strResponse);
        }
    }
}

## Reproduction Steps
1. type "hola"
2. type your name "jhon"
3. type the LUIS intent, there are two opcions "vacantes" or "registrar" and here the bot shows the start message again and stay in this loop

## Expected Behavior
Call the LUIS intent

## Actual Results
{
  "type": "message",
  "timestamp": "2018-02-01T01:07:03.688Z",
  "localTimestamp": "2018-01-31T20:07:03-05:00",
  "serviceUrl": "http://localhost:32443",
  "channelId": "emulator",
  "from": {
    "id": "8jbgkfm83h2a",
    "name": "Bot"
  },
  "conversation": {
    "id": "k9247mmn33ig"
  },
  "recipient": {
    "id": "default-user"
  },
  "membersAdded": [],
  "membersRemoved": [],
  "locale": "en-US",
  "text": "Exception: An error occurred while sending the request.",
  "attachments": [
    {
      "contentType": "text/plain",
      "content": "   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Bot.Builder.Luis.LuisService.<Microsoft-Bot-Builder-Luis-ILuisService-QueryAsync>d__4.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Bot.Builder.Luis.Extensions.<QueryAsync>d__4.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Bot.Builder.Dialogs.LuisDialog`1.<MessageReceived>d__8.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Bot.Builder.Dialogs.Internals.DialogTask.ThunkResume`1.<Rest>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Bot.Builder.Internals.Fibers.Wait`2.<Microsoft-Bot-Builder-Internals-Fibers-IWait<C>-PollAsync>d__19.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Bot.Builder.Internals.Fibers.Frame`1.<Microsoft-Bot-Builder-Internals-Fibers-IFrameLoop<C>-PollAsync>d__9.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Bot.Builder.Internals.Fibers.Fiber`1.<Microsoft-Bot-Builder-Internals-Fibers-IFiberLoop<C>-PollAsync>d__16.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at Microsoft.Bot.Builder.Internals.Fibers.Wait`2.Microsoft.Bot.Builder.Internals.Fibers.IAwaiter<T>.GetResult()\r\n   at Microsoft.Bot.Builder.Dialogs.Chain.LoopDialog`1.<ResumeAsync>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Bot.Builder.Dialogs.Internals.DialogTask.ThunkResume`1.<Rest>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Bot.Builder.Internals.Fibers.Wait`2.<Microsoft-Bot-Builder-Internals-Fibers-IWait<C>-PollAsync>d__19.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Bot.Builder.Internals.Fibers.Frame`1.<Microsoft-Bot-Builder-Internals-Fibers-IFrameLoop<C>-PollAsync>d__9.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Bot.Builder.Internals.Fibers.Fiber`1.<Microsoft-Bot-Builder-Internals-Fibers-IFiberLoop<C>-PollAsync>d__16.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Bot.Builder.Dialogs.Internals.DialogTask.<Microsoft-Bot-Builder-Base-IEventLoop-PollAsync>d__23.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Bot.Builder.Dialogs.Internals.ReactiveDialogTask.<Microsoft-Bot-Builder-Base-IEventLoop-PollAsync>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Bot.Builder.Dialogs.Internals.ScoringEventLoop`1.<Microsoft-Bot-Builder-Base-IEventLoop-PollAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Bot.Builder.Dialogs.Internals.EventLoopDialogTask.<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Bot.Builder.Dialogs.Internals.SetAmbientThreadCulture.<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Bot.Builder.Dialogs.Internals.QueueDrainingDialogTask.<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d__4.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Bot.Builder.Dialogs.Internals.PersistentDialogTask.<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.Bot.Builder.Dialogs.Internals.PersistentDialogTask.<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Bot.Builder.Dialogs.Internals.ExceptionTranslationDialogTask.<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Bot.Builder.Dialogs.Internals.SerializeByConversation.<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d__4.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Bot.Builder.Dialogs.Internals.PostUnhandledExceptionToUser.<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d__5.MoveNext()"
    }
  ],
  "entities": [],
  "replyToId": "6hj7g24i9bgf",
  "id": "974a35c985dd"
}
Log

**Comment by JasonSowers** [comment]
@grupobernier Thanks for reporting, we are looking into this.

**Comment by JasonSowers** [comment]
I am unable to reproduce, can you send me your full code and LUIS model at the email address in my profile.

**Comment by grupobernier** [comment]
Hi Jason, do you have any update? I send you the code to your e-mail.

**Comment by JasonSowers** [comment]
What email did you send this to me from, I do not see it in my inbox.

**Comment by grupobernier** [comment]
Hi Jason, I did send to v-jassow@microsoft.com

You can download the code from http://videos.fermionservices.com/MPBot.zip

**Comment by JasonSowers** [comment]
@grupobernier my Spanish speaking colleague @FranciscoPonceGomez  is going to take over for me on this issue.

**Comment by Wardess** [comment]
Is there an update on this issue ? I have the same problem. My bot keeps going to my initial "GreetingIntent" and never goes into the intent I mean to call.
When I type some gibberish it goes into my "NoneIntent" though.

**Comment by fanidamj** [comment]
Can you please let us know if the issue still persists?
