### ISSUE TITLE
Retrieve SkypeId for Bot in skype channel

### ISSUE THREAD

**Issue by khushboo22singh** [Microsoft/BotBuilder#4135]
Is there any way to get skypeId in microsoft bot? I am only getting name, but i want skypeId?

**Comment by JasonSowers** [comment]
Which SDK are you using C# or Node?

**Comment by JasonSowers** [comment]
In your root dialog does this code send the ID as a message?
```cs
        private async Task MessageReceivedAsync(IDialogContext context, IAwaitable<object> result)
        {
            var activity = await result as Activity;
            await context.PostAsync(activity.From.Id);

           context.Wait(MessageReceivedAsync);
        }
```

**Comment by khushboo22singh** [comment]
JasonSowers Thanks Jason, but i have already tried this option, however this doesn't give me the skype login id. I am using C#

**Comment by JasonSowers** [comment]
What does this this return for you?

**Comment by khushboo22singh** [comment]
It gives me some random id.. 
This is the code that I used:-
 private async Task MessageReceivedAsync(IDialogContext context, IAwaitable<object> result)
        {
            var activity = await result as Activity;

            // calculate something for us to return
            int length = (activity.Text ?? string.Empty).Length;

            // return our reply to the user
            string msg = "activity.From.Id=" + activity.From.Id + " activity.From.Name=" + activity.From.Name +
                " activity.Recipient.Id=" + activity.Recipient.Id + " activity.Recipient.Name=" + activity.Recipient.Name;
            //await context.PostAsync("Hi" + msg);
            //await context.PostAsync($"You sent {activity.Text} which was {length} characters");
            await context.PostAsync($"Hi {activity.From.Id} which was {length} characters");

            context.Wait(MessageReceivedAsync);
        }
When I said Hi to my bot in Skype it replied me this below message:-
"Hi 29:17XDTbC0kFyGr3P6E-zE7QlKwn6gl0pbcgR9DcJwb-913W_X1BfPRnJVmGyDJFKY- which was 2 characters" 
So basicall this is the Id that I am receiving

**Comment by JasonSowers** [comment]
That is the skype Id, what Id are you expecting?

**Comment by khushboo22singh** [comment]
oh k.. I was expecting skype login id of the user, like kh***@gmail.com or something like that.

**Comment by JasonSowers** [comment]
That information is not provided.
