### ISSUE TITLE
Microsoft OAuth Authentication with Dynamics portal

### ISSUE THREAD

**Issue by khushboo22singh** [Microsoft/BotBuilder#4136]
I have a requirement wherein we want to authenticate the users via Bot in Dynamics Portal. I have already tried using Office 365 portal. I wanted to know if that can be achieved in Dynamics Portal?

Any other way around will be appreciated.

Thanks

**Comment by JasonSowers** [comment]
What language are you using C# or Node?

**Comment by stevengum97** [comment]
@khushboo22singh can you provide the information requested in the template, starting with which language of the SDK you're using, the version of the SDK, how you're deploying your bot, and which channels are being used?

**Comment by khushboo22singh** [comment]
@stevengum97 I am using C#, not sure of the version i will be using, but if some latest version of SDK will suffice my need, nothing like it. 
I will be deploying on Azure portal and channels that we need are directline and webchat.
I am not able to find anything regarding this. Is it even possible to authenticate bot for Dynamics portal hosted on azure?

**Comment by stevengum97** [comment]
@khushboo22singh, sorry for the delay, did you find a solution for this? Have you seen this [article](https://community.dynamics.com/crm/b/nishantranaweblog/archive/2017/04/21/integrating-bot-with-dynamics-crm-oauth-2-0-authentication) on Dynamics auth and BotBuilder?
