### ISSUE TITLE
fail rates with regards to retrieving session state from Azure bot storage

### ISSUE THREAD

**Issue by Kannaj** [Microsoft/BotBuilder#4137]
## Bot Info
* SDK Platform: Node.js
* SDK Version: 3.11
* Active Channels: All
* Deployment Environment: Azure app service

## Issue Description
We recently moved bot session state to an azure storage account(table) and are witnessing ~ 10% failure rates with regards to retrieving session information. After trying to log operations done on the storage account, i can see that most of the failures are 404s with regards to QueryEntity. I'm not sure why this happens. Could anyone please help out in debugging this?

Heres an example log

1.0;2018-02-01T00:07:10.6578321Z;QueryEntity;ClientOtherError;404;33;32;authenticated;prodbotstate;prodbotstate;table;"https://prodbotstate.table.core.windows.net:443/botstate(PartitionKey=%27xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxxx%27,RowKey=%27userData%27)"

**Comment by JasonSowers** [comment]
Can you please provide minimum reproducible code so we can investigate?

**Comment by fanidamj** [comment]
Closing the issue assuming it as resolved. Please reopen a new issue if it still persists.
