### ISSUE TITLE
[Skype For Business] Can not send files in skype for business bot

### ISSUE THREAD

**Issue by itvignes09** [Microsoft/BotBuilder#4138]
I have created the bot successfully. It is working fine on Skype. But not on Skype for business. Not able to send image or files on Skype for business.

**Comment by FranciscoPonceGomez** [comment]
Hi itvignes09,

Can you provide more info about your bot? Do you get any errors? What SDK are you using?

Thanks,
Francisco

**Comment by itvignes09** [comment]
Hi Francisco,

Thanks for your reply. Ya sure. we will give more info. We are using the BotBuilder SDK with Nodejs. 

It seems that as for now we can't send attachments from the Skype for the Business client to a Bot. Can you confirm that the feature is available or not yet available? And if not available, tell us when this feature will be available?

Thanks,
Vignes

**Comment by itvignes09** [comment]
Hi Francisco,

Any update on this?

**Comment by cleemullins** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues


For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botbuilder-channels/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
