### ISSUE TITLE
[.Net SDK, Question] Send message after inactivity

### ISSUE THREAD

**Issue by luisnatividade** [Microsoft/BotBuilder#4139]
## Bot Info
* SDK Platform: .NET
* Active Channels: Web Chat
* Deployment Environment: Azure Bot Service

## Issue Description
Send message after X second of inactivity of user.

I want to send a message "I'm still here" to the user when he is inactive (don't sends message) in 60 seconds.
I tried with the proactive messages but I could not set a timer that restarts (or stop) when user sends a message. 

Any idea?

Thanks in advance.

**Comment by JasonSowers** [comment]
Can you please share the code you tried?

**Comment by JasonSowers** [comment]
Looking into this for you.

**Comment by Kothakapu** [comment]
Any update on this. Does anyone have the solution for it. if so could you please post it.

**Comment by JasonSowers** [comment]
@luisnatividade were you able to resolve this, or did you still need help?

**Comment by rjgmail88** [comment]
@luisnatividade , I tried to use this library [https://github.com/User1m/botbuilder-timeout](https://github.com/User1m/botbuilder-timeout) but it has an issue which I fighting to get resolved.
The fix provided isnt working. I would try it once.
Issue:-

[https://github.com/Microsoft/BotBuilder/issues/4608#event-1637804723](https://github.com/Microsoft/BotBuilder/issues/4608#event-1637804723)

**Comment by stevkan** [comment]
Hi @luisnatividade,

Please review the answer provided on [here](https://github.com/Microsoft/BotBuilder/issues/4608) as a possible solution.
