### ISSUE TITLE
[C#] Empty Response is returned when LUIS Entity does not match any Enum value.

### ISSUE THREAD

**Issue by ankitbko** [Microsoft/BotBuilder#414]
This is in continuation of #355 but since the problem is little different, I decided to raise it as  separate issue.
When handling ambiguity from LUIS Entity, if the input does not match any value an empty string is returned from the bot instead of `"<value here>" is not a location option.`.
Repo: https://github.com/ankitbko/Bot-Issue355
Input: Where is London - This works fine.
Input: Where is Delhi - Empty string is returned. Correct output - "Delhi" is not a location option.

<img src="https://cloud.githubusercontent.com/assets/3169316/15771446/7462d208-2988-11e6-97a5-80586b6949db.png" width="250">

**Comment by chrimc62** [comment]
Thanks for finding this.  Has been fixed and will be released in our next release.
