### ISSUE TITLE
Are you guys using the variable "key" in yield return?

### ISSUE THREAD

**Issue by kiranchand** [Microsoft/BotBuilder#4140]
https://github.com/Microsoft/BotBuilder/blob/e927e34aab62c2fd199b6ac7921a37d4d3aa9a66/CSharp/Library/Microsoft.Bot.Builder/Dialogs/LuisDialog.cs#L409

Can you guys use the variable `key` in yield return in the statement below?

**Comment by FranciscoPonceGomez** [comment]
Hi kiranchand,

Thanks for pointing this out. Seems that the key variable was created for it to be later returned in this case. I will review and get back to you. 

Francisco
