### ISSUE TITLE
[Node.js SDK, Cortana] Sign in at invocation for Cortana not working with knowledge.store

### ISSUE THREAD

**Issue by rjgmail88** [Microsoft/BotBuilder#4141]
## Bot Info
* SDK Platform: Node.js
* Active Channels: CORTANA
* Deployment Environment: Azure Bot Service

## Issue Description
We have a Cortana Skill that we had connected to bot in dev.botframework.com. We also had configured authentication for Azure active directory v1. so that when skill is invoked for the first time a user will be authenticated by our corp AD. Here is the documentation link we followed. https://docs.microsoft.com/en-us/cortana/skills/configure-connected-account

With the recent changes we need to manager Cortana settings on my.knowledge.store. So I did migrated by Cortana skill over these and now it shows as a BOTLET. I see my auth settings are showing up now under Authentication > Configs in Vault >. When I open auth setting I don't see an option called 'Sign in at invocation'

Was it removed ? Now my skill no more asks for sign in card.

ref: https://help.knowledge.store/tutorials_code_samples/bot_framework/index.html# enter image description here

## Expected Behavior
User should be logged in to skill by new identity provider.

**Comment by JasonSowers** [comment]
We have an ICM going for this, is someone in contact with you?

**Comment by rjgmail88** [comment]
I am in touch with someone on kstore@microsoft.com. But there not much response yet. I was just asked to republish the skill after adding oAuth settings and try. But it did not work.

**Comment by fanidamj** [comment]
Can you please let us know if the issue still persists?
