### ISSUE TITLE
Activity type of ConversationUpdate doesn't trigger on the event of sideloading on bot package to Teams

### ISSUE THREAD

**Issue by ilanopat** [Microsoft/BotBuilder#4144]
## Bot Info
* SDK Platform: .NET 
* SDK Version: 3.13.0.3
* Active Channels: MS Teams
* Deployment Environment: Local with ngrok and sideloading to Teams

## Issue Description
Activity type of ConversationUpdate doesn't trigger on the event of sideloading on bot package to Teams

Note: Sideloading is obviously enabled in the Office365 Admin center

## Code Example

case ActivityTypes.ConversationUpdate: 
                        
                        IConversationUpdateActivity update = activity;

                        var connector = new ConnectorClient(new Uri(update.ServiceUrl), GetAppCredentials(activity));

                        var channelMembers = await connector.Conversations.GetConversationMembersAsync(activity.Conversation.Id);

                        if ((dynamic)update.ChannelData.eventType.Value == "teamMemberAdded")
                        {
                            foreach (var addedMember in update.MembersAdded)
                            {
                                if (addedMember.Id == update.Recipient.Id)
                                {
                                    foreach (var channelMember in channelMembers.AsTeamsChannelAccounts())
                                    {
                                        var conversation = connector.Conversations.CreateOrGetDirectConversation(update.Recipient, channelMember, update.GetTenantId());
                                        var reply = activity.CreateReply();
                                        reply.Conversation.Id = conversation.Id;
                                        reply.Text = $"Hello {channelMember.GivenName}! Please respond to this message to Get Started with your Asana Account.";

                                        await connector.Conversations.SendToConversationAsync(reply);
                                    }
                                }
                                else 
                                {
                                    foreach (var channelMember in channelMembers.AsTeamsChannelAccounts())
                                    {
                                        if (channelMember.Id == addedMember.Id)
                                        {
                                            var conversation = connector.Conversations.CreateOrGetDirectConversation(update.Recipient, channelMember, update.GetTenantId());

                                            var reply = activity.CreateReply();
                                            reply.Conversation.Id = conversation.Id;
                                            reply.Text = $"Hello {channelMember.GivenName}! Please respond to this message to Get Started with your Asana Account.";
                                            await connector.Conversations.SendToConversationAsync(reply);
                                        }
                                    }
                                }
                            }
                        }
                        break;
## Reproduction Steps
1. Setup local tunnel via ngrok.
2. Run the project.
3. Adding of bot to a channel via Manage Teams.

## Expected Behavior
It should fall on ConversationUpdate case whenever I add/remove the bot to a certain Teams channel.

**Comment by EricDahlvang** [comment]
Hi @ilanopat 

I believe MS Teams does not send a ConversationUpdate when side loading the bot. Sideloading is really a developer feature, not a way to deploy/distribute apps.

**Comment by ilanopat** [comment]
I see though, I figured that it happened only when I replaced the manifest file from the one that i generated using the Teams App Studio app, I reverted my changes back and sideloaded the package again and it falls on the ConversationUpdate now.

**Comment by ilanopat** [comment]
Here is the manifest file from Teams App Studio, which doesn't trigger the ConversationUpdate when I sideload it.

{
    "$schema": "https://statics.teams.microsoft.com/sdk/v1.1/manifest/MicrosoftTeams.schema.json",
    "manifestVersion": "1.1",
    "version": "1.0.0",
    "id": APPID,
    "packageName": "com.Test.Notifier",
    "developer": {
        "name": "Dev8",
        "websiteUrl": "https://www.example.com/",
        "privacyUrl": "https://www.example.com/privacy-policy/",
        "termsOfUseUrl": "https://www.example.com/tos/"
    },
    "icons": {
        "color": "bot_blue.png",
        "outline": "bot_blue.png"
    },
    "name": {
        "short": "Notifier Bot",
        "full": "Notifier Tools Bot"
    },
    "description": {
        "short": "Notifier Tools Bot v1.0",
        "full": "Notifier Tools Bot v1.0"
    },
    "accentColor": "#0079BF",
    "bots": [
        {
            "botId": APPID,
            "scopes": [
                "personal"
            ]
        }
    ],
    "permissions": [
        "identity",
        "messageTeamMembers"
    ],
    "validDomains": []
}

**Comment by ilanopat** [comment]
And here is the one the triggers the ConversationUpdate when sideloaded

{
  "$schema": "https://statics.teams.microsoft.com/sdk/v1.0/manifest/MicrosoftTeams.schema.json",
  "manifestVersion": "1.0",
  "version": "1.0.0",
  "id": APPID,
  "packageName": "com.Test.Notifier",
  "developer": {
    "name": "Dev8",
    "websiteUrl": "https://www.example.com/",
    "privacyUrl": "https://www.example.com/privacy-policy/",
    "termsOfUseUrl": "https://www.example.com/tos/"
  },
  "name": {
    "short": "Notifier Bot",
    "full": "Notifier Tools Bot"
  },
  "description": {
    "short": "Notifier Tools Bot v1.0",
    "full": "Notifier Tools Bot v1.0"
  },
  "icons": {
    "outline": "bot_blue.png",
    "color": "bot_blue.png"
  },
  "accentColor": "#0079bf",
  "configurableTabs": [
    {
      "configurationUrl": "MYBASEURI/tab/tabConfig/index.html",
      "canUpdateConfiguration": true,
      "scopes": [ "team" ]
    }
  ],
  "staticTabs": [
    {
      "entityId": "idForPage",
      "name": "Display name of tab",
      "contentUrl": MYBASEURI,
      "websiteUrl": MYBASEURI,
      "scopes": [ "personal" ]
    }
  ],
  "bots": [
    {
      "botId": APPID,
      "needsChannelSelector": true,
      "isNotificationOnly": false,
      "scopes": [ "team", "personal" ],
      "commandLists": [
        {
          "scopes": [ "team" ],
          "commands": [
            {
              "title": "Command 1",
              "description": "Description of Command 1"
            },
            {
              "title": "Command N",
              "description": "Description of Command N"
            }
          ]
        },
        {
          "scopes": [ "personal" ],
          "commands": [
            {
              "title": "Personal command 1",
              "description": "Description of Personal command 1"
            },
            {
              "title": "Personal command N",
              "description": "Description of Personal command N"
            }
          ]
        }
      ]
    }
  ],
  "connectors": [
    {
      "connectorId": CONNECTORID,
      "scopes": [ "team" ]
    }
  ],
  "composeExtensions": [
    {
      "botId": APPID,
      "canUpdateConfiguration": true,
      "commands": [
        {
          "id": "exampleCmd",
          "title": "Example Command",
          "description": "Command Description; e.g., Search on the web",
          "initialRun": true,
          "parameters": [
            {
              "name": "keyword",
              "title": "Search keywords",
              "description": "Enter the keywords to search for"
            }
          ]
        }
      ]
    }
  ],
  "permissions": [
    "identity",
    "messageTeamMembers"
  ],
  "validDomains": [
    "ngrok.io"

  ]
}

**Comment by EricDahlvang** [comment]
I'm glad you've found something that works!  Thank you for sharing your solution.
