### ISSUE TITLE
Pass additional information in Channel Data while launching webchat

### ISSUE THREAD

**Issue by neetgupta7** [Microsoft/BotBuilder#4145]
## Bot Info
* SDK Platform:  .NET
* SDK Version: 3.12.0
* Active Channels: Webchat
* Deployment Environment: Azure App Service

## Issue Description
Hi
Can i pass some additional info while launching the chatbot. I m trying to do something like below but that doesnt work. Is there some other way we can achieve it.

## Code Example
<!DOCTYPE html>
<html>
  <head>
    <link href="botchat.css" rel="stylesheet" />
  </head>
  <body>
    <div id="bot"/>
    <script src="https://cdn.botframework.com/botframework-webchat/latest/botchat.js"></script>
    <script>
      BotChat.App({
        directLine: { secret: 'ABCDXYZ' },
        user: { id: 'abc@xyz.com', name: 'ABC XYZ' },
        bot: { id: 'MyBOT' },
	**channelData: { token: 'kjlkjwdnlke;ml;ler' },**
        resize: 'detect'
      }, document.getElementById("bot"));
    </script>
  </body>
</html>

**Comment by JasonSowers** [comment]
What you probably want to use the backchannel
  
[Blog here](https://docs.microsoft.com/en-us/bot-framework/bot-service-design-pattern-embed-web-site#) scroll down a little the first part is about the skype web control  
Another [Blog here](https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-backchannel)    
[Sample here](https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/backchannel)

**Comment by neetgupta7** [comment]
@JasonSowers Do you have any .net implementation for the same.

**Comment by JasonSowers** [comment]
I do not personally, sorry

**Comment by bommareddysandhya** [comment]
I tried this (https://github.com/ryanvolum/backChannelBot) example but  it doesnt work. Attached is the html i m trying.
