### ISSUE TITLE
[.Net SDK, LUIS] Intents repeated

### ISSUE THREAD

**Issue by kiranchand** [Microsoft/BotBuilder#4146]
https://github.com/Microsoft/BotBuilder/blob/e927e34aab62c2fd199b6ac7921a37d4d3aa9a66/CSharp/Library/Microsoft.Bot.Builder/Dialogs/LuisDialog.cs#L286

Not sure how, but I am finding the intents being repeated here, creating duplication in keys when creating dictionary and causing exception. Please use distinct keys, if you could; here is the work aroud I did.

``` csharp
return LuisDialog.EnumerateHandlers(this)
        .Distinct(Comparer.Get((KeyValuePair<string, IntentActivityHandler> kvp) => kvp.Key, StringComparer.OrdinalIgnoreCase))
        .ToDictionary(kv => kv.Key, kv => kv.Value);

```
Of course, DeletegateComparer is a few lines of custom code 

Alternately, you may please return the distinct keys when returning the key value pairs at

https://github.com/Microsoft/BotBuilder/blob/e927e34aab62c2fd199b6ac7921a37d4d3aa9a66/CSharp/Library/Microsoft.Bot.Builder/Dialogs/LuisDialog.cs#L405
``` csharp
var intentHandlers = intents.Select(attribute => attribute.IntentName)
    .DefaultIfEmpty(method.Name)
    .Select(intent => intent?.Trim() ?? string.Empty) // Empty if null; else trim
    .Distinct(StringComparer.OrdinalIgnoreCase) // Just use .Distinct() alone, if case insensitivity is not required.
    .Select(intent => new KeyValuePair<string, IntentActivityHandler>(intent, intentHandler));

foreach (var kvp in intentHandlers)
{
    yield return kvp;
}
```
Note: this fixes the intermittent unresponsive scenarios.

**Comment by fanidamj** [comment]
Can you please let us know if the issue still persists?

**Comment by kiranchand** [comment]
Of course, yes! Nobody fixed it as of now. I have created a reusable solution for my code, using AOP and moved on. Why do not you guys fix it and bring it along with your subsequent releases?
--
Kiran Chand

**Comment by JasonSowers** [comment]
@kiranchand if you feel this would be a contribution that could help others please submit a pull request including an explanation of why it is needed.  It is unclear why you needed this code change as there is no explanation or code example in your original post.  So I'm not sure if others will benefit from this, or it is specific to your exact bot.
