### ISSUE TITLE
Issue around customize chatBot web UI.

### ISSUE THREAD

**Issue by JasonParkerX** [Microsoft/BotBuilder#4147]
## Bot Info
* SDK Platform:  Node.js
* SDK Version:  
* Active Channels:  Web
* Deployment Environment:  Azure Bot Service

## Issue Description

Hi, guys, I searched a bit around regarding this issue, I just want to double check, if I run chatBot directly from azure's serve and use the (basic) user interface directly from the Microsoft azure, there is no way for me edit its UI directly right? So if I want to edit its user interface I have to set up my own user interface and use the directline api to connect the chatbot to my interface, that's the only way from me to customize chatBot UI.
## Reproduction Steps
1.
2.
3.

**Comment by JasonSowers** [comment]
This is not possible, that panel is meant for testing your code only.  You can, however, change the look of webchat when it is deployed.  It is open source and fully customizable.  a good place to start is the [webchat repo](https://github.com/Microsoft/BotFramework-WebChat)
