### ISSUE TITLE
How can I prompt a user without redirecting to another method?

### ISSUE THREAD

**Issue by vaditya04** [Microsoft/BotBuilder#415]
I want to use PromptDialog.Text to get a string input from a user.

But, I don't want to redirect to another method (using resume). I want to continue the execution of the same method with the user string input stored in a variable. 

Thanks.

**Comment by willportnoy** [comment]
You can specify the same method as the callback.  If you want that same method take both IAwaitable<Message> (for incoming messages) and IAwaitable<string> (from the prompt dialog), then you'll need to change the method to take IAwaitable<object> and use a is-a type test to see which value was passed in.

**Comment by vaditya04** [comment]
@willportnoy 
Thanks for the response.

However, this method is troublesome if I'm working with LUIS, wherein methods will necessarily have the context and a LUISResult as parameters. Is there any other solution for this? I've opened Issue #428 asking this as a separate question.

**Comment by willportnoy** [comment]
I'll close this issue in favor of #428.
