### ISSUE TITLE
[Question] How to extract username from the Query string

### ISSUE THREAD

**Issue by rupjit** [Microsoft/BotBuilder#4150]
## Bot Info
* SDK Platform: .NET 

* Active Channels:  Direct Line

## Issue Description
Not able to extract username from following Query string in controller side,

<iframe id="myFrame" src='https://webchat.botframework.com/embed/
smilesbot?s=secret_code&username=admin&userid=1234'></iframe>

## Expected Behavior
I want username & userid at controller side

## Actual Results
Not getting username . userid

**Comment by rupjit** [comment]
@danmarshall  i think you have done this before, kindly help.

**Comment by neetgupta7** [comment]
Try to get it from activity.from.id and activity.from.name

**Comment by rupjit** [comment]
Hi, I am getting Name as null & id as some random number   :(

**Comment by neetgupta7** [comment]
I have seen this behavior when activity is of type conversationUpdate but with activity.Messages it works fine.

**Comment by rupjit** [comment]
@neetgupta7  we are using ActivityTypes.Message only.

**Comment by EricDahlvang** [comment]
@rupjit 

https://webchat.botframework.com/embed will convert them to properties on activity.From:

activity.From.Id = userid
activity.From.Name = username

![image](https://user-images.githubusercontent.com/11055362/35832311-ade35742-0a81-11e8-9739-3994dac6e6c5.png)

**Comment by rupjit** [comment]
@EricDahlvang  HI, As i mentioned in previous update,  I am getting Name as null & id as some random number :( . Did you face any issue of this sort & did i miss anything ?

**Comment by rupjit** [comment]
![nameasnull](https://user-images.githubusercontent.com/22374520/35866493-5a5e10d8-0b7d-11e8-9c9d-841704e0b672.jpg)     @EricDahlvang  attaching live debug for your kind reference

**Comment by rupjit** [comment]
@EricDahlvang  I have just discovered  ,i get Name when channel is "web chat". I get name as null when channel is directline......................................I am sure we must encountered this issue before.  :)

**Comment by EricDahlvang** [comment]
What is the client side code where you are using the Direct Line channel?

**Comment by rupjit** [comment]
@EricDahlvang 

<style>
    #botTitleBar {
     text-align: left;
     color:white;
     font-size:16px;
     font-style:oblique;
     padding-top:8px;
     padding-left:15px;
    }
   

</style>

<script src="~/Scripts/jquery-1.10.2.js"></script>

<script>
    (function () {

     var div = document.createElement("div");
    document.getElementsByTagName('body')[0].appendChild(div);
   div.outerHTML = "<div id='botDiv' style='height: 38px; position: fixed; right:0 ; bottom: 0; z-index: 1000; background-color: #fff'><div id='botTitleBar' style='height: 38px; width: 400px; position:fixed; cursor: pointer; background-color:#0099CC'>Need Help ? Ask your Bot</div><iframe width='400px' height='500px' src='https://webchat.botframework.com/embed/BotHandler?s=Directline_Secret_Key&username=MyuserName'></iframe></div>";
    document.querySelector('body').addEventListener('click', function (e) {
        e.target.matches = e.target.matches || e.target.msMatchesSelector;
        if (e.target.matches('#botTitleBar')) {
            var botDiv = document.querySelector('#botDiv');
            botDiv.style.height = botDiv.style.height == '500px' ? '38px' : '500px';
        };
    });
}());
