### ISSUE TITLE
FormBuilderJson enum not longer clickable

### ISSUE THREAD

**Issue by Matti-Koopa** [Microsoft/BotBuilder#4151]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.13.0.3
* Active Channels: Web
* Deployment Environment: local development with Emulator

## Issue Description
Generated choice buttons are no longer clickable. They were with NuGet Microsoft.Bot.Builder version 3.12.2.4.
Might have something to do with removing the deafult type "ImBack" as a similar problem occured with SuggestedActions where their Type was null which no longer worked. FormFlow might generate those choice buttons without an ImBack action type?

## Code Example
```
"FavColor": {
      "Before": [
        {
          "Message": [ "Choose a favorite color" ]
        }
      ],
      "type": "string",
      "enum": [
        "Red",
        "Green",
        "Blue"
      ],
      "Prompt": {
        "Patterns": [ "{&}: {||}" ]
      },
      "Describe": "My favorite color"
    }
```

## Reproduction Steps
1. Get Dialog from JSON file using FormBuilderJson and FormDialog.FromForm
2. Call the dialog to context
3. As soon as the question appears, click one of the options in chat

## Expected Behavior
Choosen options gets set as value.

## Actual Results
Nothing happens. User has to type in his or her response in chat manually.

**Comment by Srinath-Sadda** [comment]
It has been discussing here: https://github.com/Microsoft/BotBuilder/issues/4126

**Comment by JasonSowers** [comment]
we are looking into it, please pay attention the original thread #4126
