### ISSUE TITLE
Skype Bot from a specific page

### ISSUE THREAD

**Issue by alcudia25** [Microsoft/BotBuilder#4152]
Hello,

I have created an external app Bot in Java and I use REST API interface to connect to my Microsoft Azur.
I use "Bot Channels Registration " to register my bot in Microsoft Azur.
I added a Skype channel to connect my Bot.

I'd like to put links in a few web pages to connect my Bot through Skype : how is the link form ?
and is the messaging endpoint can know the origin page of the call ?  

Regards

**Comment by JasonSowers** [comment]
Can you please try rewording your question, I'm not sure what exactly you are asking

**Comment by alcudia25** [comment]
Hi JasonSowers,

There are two questions :-)   :  

**Question1** I would like to put links in some web pages to connect my Bot via Skype, what is the link model ?
I tried  _skype:28:@MyMicrosoftAppID?chat_ , _https://join.skype.com/bot/MyMicrosoftAppID_

**Question2** I'd like my messaging endpoint (https://xxxxxx.ngrok.io/api/messages) can know the origin page of the call,  as in the facebook messenger API (https://m.me / myBot? ref = myRef); is there a solution ?

Thanks

**Comment by alcudia25** [comment]
no proposals ?

**Comment by fanidamj** [comment]
Closing the issue assuming it as resolved. Please reopen a new issue if it still persists.
