### ISSUE TITLE
font colours different on slack and Telegram

### ISSUE THREAD

**Issue by yogiderek** [Microsoft/BotBuilder#4155]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.13.0.3
* Adaptive Cards Version: 1.0.0-beta11
* Active Channels: Chat, Slack, Telegram
* Deployment Environment: Azure Bot Service

## Issue Description
In Web Chat my adaptive card correctly shows notification text related to today and tomorrow in red and 2 days from today in yellow. However, in Slack and Telegram, the notification text colour is swapped around i.e. text related to today and tomorrow is yellow and 2 days from today is now red. 

Note also that the alignment of images is correct in both Slack and Telegram but not in Chat.

## Code Example
                int numDays = (int)(kvp.Key - DateTime.Today).TotalDays;
                string days = string.Format("{0} days' time.", numDays);
                AdaptiveTextColor color = AdaptiveTextColor.Default;
                AdaptiveTextWeight weight = AdaptiveTextWeight.Default;
                bool isSubtle = true;
                if (numDays == 0)
                {
                    days = "Today";
                    color = AdaptiveTextColor.Warning;
                    weight = AdaptiveTextWeight.Bolder;
                    isSubtle = false;
                }
                else if (numDays == 1)
                {
                    days = "Tomorrow";
                    color = AdaptiveTextColor.Warning;
                    weight = AdaptiveTextWeight.Bolder;
                    isSubtle = false;
                }
                else if (numDays == 2)
                {
                    color = AdaptiveTextColor.Attention;
                    weight = AdaptiveTextWeight.Bolder;
                    isSubtle = false;
                }
                else
                {
                }

## Expected Behavior
Text colour to be consistent across all channels.

## Actual Results
See screenshots, image order is Chat, Slack, Telegram

![chat](https://user-images.githubusercontent.com/2614368/35830474-4b2a4740-0abe-11e8-90e0-f934414c340c.png)
![slack](https://user-images.githubusercontent.com/2614368/35830475-4b4dbbda-0abe-11e8-96b4-2343400090f4.png)
![telegram](https://user-images.githubusercontent.com/2614368/35830477-4b71653a-0abe-11e8-9211-36ccf15fb392.png)

**Comment by JasonSowers** [comment]
This is an issue with Adaptive Cards.  Please post your issue on [their repo](https://github.com/Microsoft/AdaptiveCards)
