### ISSUE TITLE
[Question] Create bot dialogs dynamically w/ FormFlow ?

### ISSUE THREAD

**Issue by rjgmail88** [Microsoft/BotBuilder#4156]
## Bot Info
* SDK Platform:  Node.js
* Active Channels: Cortana
* Deployment Environment: Azure Bot Service Azure App Service, ,local development with Emulator 

## Issue Description
I was researching a way to see if I can create a bot dialogs dynamically. Use something like json or txt file descriptor, mentioned all utterances and bot responses. Not sure if **FormFlow** is the right thing I'm looking at. Is there any node.js example ?

Or please share is there is another way to this.

## Expected Behavior
Property file should be loaded and dialogs should be create on the fly by using values from the file.

**Comment by MNHarun** [comment]
see http://tomipaananen.azurewebsites.net/?p=1641
and related sample https://github.com/tompaana/dynamic-form-flow-sample

**Comment by rjgmail88** [comment]
Thanks.
