### ISSUE TITLE
[C#] Enum ambiguity resolution fails if matches contains a number.

### ISSUE THREAD

**Issue by ankitbko** [Microsoft/BotBuilder#416]
When supplying input for an Enum Field Clarification, if the input is a choice number/button click and there is a number present in other possible matches, the resolution fails.
Repo: https://github.com/ankitbko/Bot-Issue355
To reproduce - 
Input: Where is London
Select "London City Airport London"

<img src="https://cloud.githubusercontent.com/assets/3169316/15773135/edf11f94-2992-11e6-87d4-3074ad511803.png" width="250">

This happens because input '5' is resolved as two matches "London City Airport London" and "London Heathrow Airport, T 5 London" in `Step.cs` where if matches are more than 1, it assigns `matches = new TermMatch[0]` essentially discarding the user's input.

![image](https://cloud.githubusercontent.com/assets/3169316/15772985/1f8d07bc-2992-11e6-80eb-171e9f135e54.png)

**Comment by chrimc62** [comment]
Thanks for the bug report.  I have a fix and it should be in our next release.  I had to change how numbers vs terms were recognized.
