### ISSUE TITLE
Pop up a browser window upon selecting a choice

### ISSUE THREAD

**Issue by wkk91193** [Microsoft/BotBuilder#4160]
## Bot Info
* SDK Platform:  Node.js 
* SDK Version: 3.11.0
* Active Channels: Facebook
* Deployment Environment: Azure Bot Service, local development with Emulator

## Issue Description
After the user selecting a certain option from builder.Prompts.choice I need to open up a web page on the browser to show up some results. Only one of the options needs to directed to website.How would do this?

**Comment by JasonSowers** [comment]
I do not think there is a way to accomplish this with prompt.choice.  I would suggest using a Hero card or some other rich card to accomplish this.  there is a `cardAction` type of `openUrl`.  Here is a [sample](https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node/cards-RichCards) of some rich cards and here is the [documentation](https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-send-rich-cards)

```javascript
new builder.HeroCard(session)
            .title("Google")
            .subtitle("")
            .text("Click button to go to google")
            .buttons([
                builder.CardAction.openUrl('http://google.com")
            ])
```

**Comment by wkk91193** [comment]
@JasonSowers  I think there's typo when passing params to openUrl method.
