### ISSUE TITLE
Hyperlinks not working in Skype for business on iOS and Android

### ISSUE THREAD

**Issue by cudran** [Microsoft/BotBuilder#4161]
## Bot Info
* SDK Platform: .NET
* SDK Version: Latest
* Active Channels: Skype For Business
* Deployment Environment: Azure Bot Service

## Issue Description

When we use a anchor tag, Skype for Business on Windows desktop and laptop renders properly, but the entire link is visible in Skype for Business on iOS and Android devices
## Reproduction Steps
1.
2.
3.

**Comment by JasonSowers** [comment]
Unfortunately, this is just the way that skype for business renders text on these clients.  You would have to reach out to skype for business to get them to make this change.  You can contact them on their [uservoice](https://www.skypefeedback.com/)
