### ISSUE TITLE
[.Net SDK, RichCards, WebChat] Microsoft Bot Web Chat unable to display multiple rich cards 

### ISSUE THREAD

**Issue by garylxk** [Microsoft/BotBuilder#4162]
## Bot Info
* SDK Platform: .Net C#
* SDK Version:  3.12.2.4
* Active Channels: Direct Line and Web Chat
* Deployment Environment:  Azure Bot Service, Azure App Service and local development with Emulator

## Issue Description
Local development using emulator, i am able to display multiple Rich Cards when using the emulator

![image](https://user-images.githubusercontent.com/23468490/35905711-17547e02-0c23-11e8-9ca4-d051dc978607.png)

When i host it on azure app service  and test it on the WebChat the output does not tally with the emulator. The webchat only able to display the first rich card, all the following rich card were not able to display. The webchat is working fine with string content only. There are no error message.

![image](https://user-images.githubusercontent.com/23468490/35906406-550270fe-0c25-11e8-9d04-7a9de97bf4c5.png)

## Code Example
**Code to reply the activity**

           if (activity.GetActivityType() == ActivityTypes.Message)
            {
                try
                {
                    //Get User Information
                    GuruModel guru = getUserData(activity);

                    if (guru != null)
                    {
                        string result = await askGuru(guru);
                        JObject json = JObject.Parse(result);

                        List<Activity> messages = JsonConvert.DeserializeObject<List<Activity>>(json["messages"].ToString());

                        foreach (Activity message in messages)
                        {
                           // string userActivity = JsonConvert.SerializeObject(messages);

                            await connector.Conversations.ReplyToActivityAsync(message);
                           // await connector.Conversations.SendToConversationAsync(message);

                          //  await Conversation.SendAsync(activity, () => new IrisDialog(userActivity));
                            //await sendMessage(activity.CreateReply(JsonConvert.SerializeObject(message)));
                            //await sendMessage(message);
                        }

                        //await Conversation.SendAsync(activity, () => new IrisDialog(messages));
                        //// await Conversation.SendAsync(activity, () => new IrisDialog(messages));

                        
                        saveUserData(json);
                    }
                    else
                    {

                        await connector.Conversations.ReplyToActivityAsync(activity.CreateReply("User is not registered"));
                        return new HttpResponseMessage(System.Net.HttpStatusCode.Accepted);
                    }
                }
                catch (Exception e) {
                    await connector.Conversations.ReplyToActivityAsync(activity.CreateReply(e.Message.ToString()));
                }
            }
            else
            {
                HandleSystemMessage(activity);
            }

**Code to generete  hero card**

        public Activity createHeroCard(Activity activity, IntendModel.CardModel node)
        {

            //Extract all the information from xml
            string msg_reply = node.msgReply;
            string msg_title = node.msgTitle;
            string msg_subtitle = node.msgSubTitle;

            //Reply Object
            Activity replyToConversation = activity.CreateReply(msg_reply);
            replyToConversation.Recipient = activity.From;
            replyToConversation.Type = "message";

            //Prepare attachment for reply object
            replyToConversation.Attachments = new List<Attachment>();
            List<CardImage> cardImages = new List<CardImage>();

            foreach (String image in node.images)
            {
                cardImages.Add(new CardImage(image));
            }

            List<CardAction> cardButtons = new List<CardAction>();

            foreach (IntendModel.CardModel.CardButton button in node.buttons)
            {

                string type = button.type;
                string value = button.value;
                string title = button.title;

                CardAction plButton = new CardAction()
                {
                    Value = value,
                    Type = type,
                    Title = title
                };

                cardButtons.Add(plButton);
            }

            HeroCard plCard = new HeroCard()
            {
                Title = msg_title,
                Subtitle = msg_subtitle,
                Images = cardImages,
                Buttons = cardButtons
            };

            Attachment plAttachment = plCard.ToAttachment();
            replyToConversation.Attachments.Add(plAttachment);

            return replyToConversation;

        }

**Code to Generate Hero Card with Carousel**

        public Activity generateSearchItemCard(Activity activity, LuisModel luisObj)
        {
            int countItem = luisObj.searchItems.Count() < 6 ? luisObj.searchItems.Count() : 5;

            Activity replyToConversation = null;

            if (countItem > 0)
            {
                replyToConversation = activity.CreateReply("This is the master's answers");
                replyToConversation.AttachmentLayout = AttachmentLayoutTypes.Carousel;
                replyToConversation.Recipient = activity.From;
                replyToConversation.Type = "message";
                replyToConversation.Attachments = new List<Attachment>();

                for (int x = 0; x < countItem; x++)
                {
                    GoogleSearchModel item = luisObj.searchItems[x];

                    //Extract all the information from xml
                    string msg_title = item.title;
                    string msg_subtitle = item.snippet;

                    List<CardAction> cardButtons = new List<CardAction>();

                    CardAction plButton = new CardAction()
                    {
                        Value = item.link,
                        Type = "openUrl",
                        Title = "Open Link"
                    };

                    cardButtons.Add(plButton);

                    HeroCard plCard = new HeroCard()
                    {
                        Title = msg_title,
                        Subtitle = msg_subtitle,
                        Buttons = cardButtons
                    };

                    Attachment plAttachment = plCard.ToAttachment();
                    replyToConversation.Attachments.Add(plAttachment);
                }
                replyToConversation.AttachmentLayout = AttachmentLayoutTypes.Carousel;
            }
            else
            {

                replyToConversation = activity.CreateReply("Master do not understand you.");
                replyToConversation.Recipient = activity.From;
                replyToConversation.Type = "message";

            }

            return replyToConversation;

        }

## Reproduction Steps
1. Create Multiple Activity Object.
2. Assign the Activity Object with Attachment and AttachmentLayout is courasell
3. Reply all the activity at once using WebChat

## Expected Behavior
![image](https://user-images.githubusercontent.com/23468490/35905711-17547e02-0c23-11e8-9ca4-d051dc978607.png)

## Actual Results
![image](https://user-images.githubusercontent.com/23468490/35906406-550270fe-0c25-11e8-9d04-7a9de97bf4c5.png)

**Comment by garylxk** [comment]
Hi @JasonSowers, I just edited the content, please have a look. Thanks

**Comment by FranciscoPonceGomez** [comment]
Hi garylxk,

Are you still experiencing this issue? I can have a look at it today. Sorry for the delay.

Francisco

**Comment by garylxk** [comment]
Hi FranciscoPonceGomez,

Yes. i am still having this issue.

**Comment by FranciscoPonceGomez** [comment]
Can you provide an example of what input have you given to the bot and what you are expecting? So far what I understand is that the results are different in WebChat and the Emulator.

Could you please provide your BotID and the rest of the code? I haven't been able to reproduce your issue so far.

Thanks,
Francisco

**Comment by garylxk** [comment]
This issue involve in 2 project which you can download from the link below https://drive.google.com/file/d/1RQUyVCocA4e_Od0xos2IdoQ9LARA5I-b/view

- Guroo_Demo-src will send all the chat messages to GurooEngine for processing via HTTP.
- After processing, GurooEngine will return Activities that can be a Rich Card or Plain Text reply via HTTP
- Guroo_Demo-src will reply all the activities that it received.

**Comment by fanidamj** [comment]
Can you please let us know if the issue still persists?

**Comment by EricDahlvang** [comment]
If this is still an issue, please post it on the WebChat repository.  https://github.com/Microsoft/BotFramework-WebChat/issues/new
