### ISSUE TITLE
Master bot integrated with other bots in background (bot talking to bot)

### ISSUE THREAD

**Issue by neetgupta7** [Microsoft/BotBuilder#4163]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.12
* Deployment Environment: Azure App Service

## Issue Description
Hello
I need suggestions on approach to come up with a design where there will be just one Master Bot placed everywhere (lets say webchat) and depending on the type of user request this master bot will channel user conversation to child bot in background. e.g. If user says "i want to buy" channel his/her message on master bot to sales bot in background and if user says "i am facing issues" channel his/her message on master bot to service bot in background .

**Comment by Srinath-Sadda** [comment]
@neetgupta7 Take a look into this sample: https://github.com/ejadib/handoff-to-human-sample

**Comment by fanidamj** [comment]
Closing the issue assuming it as resolved. Please reopen a new issue if it still persists.
