### ISSUE TITLE
ThumbnailCards with CardAction not working anymore in Slack

### ISSUE THREAD

**Issue by Unders0n** [Microsoft/BotBuilder#4164]
## Bot Info
* SDK Platform: .Net
* SDK Version: 3.13.1.0
* Active Channels: Slack
* Deployment Environment:  Azure App Service

## Issue Description
Code worked fine but with some latest update posting message with ThumbnailCard with CardAction in it not showing as a button in Slack anymore.

## Code Example
```csharp
...
{
var buttonOk = new List<CardAction>
            {
                new CardAction {Value = $"{NoNeedToChangeCommand}", Title = "ok, go ahead"}
            };
            await context.PostWithButtonsAsync("...or just press this", buttonOk);
}

...
 public static async Task PostWithButtonsAsync(this IDialogContext context, string text, List<CardAction> buttons)
        {
            var mes = context.MakeMessage();
            mes.Text = text;

            var cardForButton = new ThumbnailCard { Buttons = buttons };
            mes.Attachments.Add(cardForButton.ToAttachment());

            await context.PostAsync(mes);
        }


```

## Reproduction Steps
1.Run code above with ms chatbot connected to Slack

## Expected Behavior
Message with text "...or just press this" and button "ok, go ahead" must be shown

## Actual Results
![default](https://user-images.githubusercontent.com/18035628/35917327-bfbfb9d0-0c1e-11e8-8dcf-1c4191b46d7b.png)

In emulator everything's work fine.
![default](https://user-images.githubusercontent.com/18035628/35917354-dcd1a11e-0c1e-11e8-812e-d6109b40b6bc.png)

Here's payload generated
```
{
  "type": "message",
  "timestamp": "2018-02-07T11:58:26.841Z",
  "localTimestamp": "2018-02-07T14:58:26+03:00",
  "serviceUrl": "http://localhost:6183",
  "channelId": "emulator",
  "from": {
    "id": "9ldiggjil6bj",
    "name": "Bot"
  },
  "conversation": {
    "id": "4b1jm1bbj99j"
  },
  "recipient": {
    "id": "default-user"
  },
  "membersAdded": [],
  "membersRemoved": [],
  "reactionsAdded": [],
  "reactionsRemoved": [],
  "locale": "ru",
  "text": "...or just press this",
  "attachments": [
    {
      "contentType": "application/vnd.microsoft.card.thumbnail",
      "content": {
        "buttons": [
          {
            "title": "ok, go ahead",
            "value": " /ok"
          }
        ]
      }
    }
  ],
  "entities": [],
  "replyToId": "kj39aila7k1e",
  "id": "bfcjlgheg0in"
}
Log
```

Please confirm whether its'a a bug, my mistake or Slack's fault. Thank you.

**Comment by JasonSowers** [comment]
In your card action `new CardAction {Value = $"{NoNeedToChangeCommand}", Title = "ok, go ahead"}` you are missing a `type` parameter you can see the list of actionTypes of [this page](https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-add-rich-card-attachments) a little below the top of the page

**Comment by Unders0n** [comment]
Confirming that setting up Type = "postBack"  worked!
Weird thing that it was working without it somehow. Like it was default value , so what changed is it Slack side or Chatbot framework?

**Comment by EricDahlvang** [comment]
@Unders0n 
This commit removed the default CardAction.Type (which was `ActionTypes.ImBack`): https://github.com/Microsoft/BotBuilder/pull/4123/commits/46c833e031ee1785673bffb42a1b417828dee0d4#diff-22d3aafad398bb6777ae1c317a342eed

**Comment by Unders0n** [comment]
Ok. Thanks for explaining.
