### ISSUE TITLE
Bot Skype in review 

### ISSUE THREAD

**Issue by Polaris-BS** [Microsoft/BotBuilder#4165]
## Bot Info
* SDK Platform: Node.js 
* Active Channels: Skype,
* Deployment Environment: Azure Bot Service

## Issue Description
My bot is in Review since several weeks with no information, no message or mail. 
Is this normal?

**Comment by EricDahlvang** [comment]
@Polaris-BS Please share the Bot Handle and Microsoft App Id, so we can escalate this to the proper team.

**Comment by Polaris-BS** [comment]
Yes :
Microsoft App Id : ad902637-9704-47a3-ada0-140809db6d6b
Bot handle : ByeAndUse

**Comment by Polaris-BS** [comment]
Thanks @EricDahlvang  !

**Comment by Polaris-BS** [comment]
No news ? It's in review , no change :/

**Comment by EricDahlvang** [comment]
@Polaris-BS On February 8th, the response was: "We currently have some backlog with the Bot reviews and hence the delay . Will review the Bot and share feedback ."

I've pinged the review team again.  Thank you for your patience.

**Comment by Polaris-BS** [comment]
Thx EricDahlvang . 
My solution must be in production in 15 days. It's been 8 months since it's in development is all operational except the revision. Many investors are becoming impatient. My first revision date of November 2017 :/

**Comment by EricDahlvang** [comment]
The following is the feedback:
The bot must have links to a valid Privacy Policy and Terms of Use, currently its giving 401 error.

Bot avatar image must be with non-black and non-white background color, now it has white background.

Once customer has addressed these issues resubmit the bot again for review.

**Comment by Polaris-BS** [comment]
ok i will do the necessary
