### ISSUE TITLE
LUIS-Samples app build-app-programmatically-csv syntax issue.

### ISSUE THREAD

**Issue by rjgmail88** [Microsoft/BotBuilder#4168]
## Issue Description
I am looking at this project from LUIS-samples 
https://github.com/Microsoft/LUIS-Samples/tree/master/examples/build-app-programmatically-csv

## Code Example
When I run it I get following error. 

Index.js is importing following files 

**const parse = require('./_parse');**
const createApp = require('./_create');
const addEntities = require('./_entities');
const addIntents = require('./_intents');
const upload = require('./_upload');

and it I comment the line where parse.js is imported. Then same error occurs on next file which is _create. and so on.

I check the syntax of all the files and it it correct.

**Comment by stevengum97** [comment]
@rjgmail88, can you please file LUIS-Samples related issues in the [LUIS-Samples](https://github.com/Microsoft/LUIS-Samples) repository?

@v-geberr or @DeniseMak, can you assist @rjgmail88? Thanks!

Closing issue.

**Comment by rjgmail88** [comment]
Hi stevengum97, I was not able to create one there. I don't see New issue option. Can you reopen it and somehow map it to LUIS ?

**Comment by stevengum97** [comment]
Since an issue was created and you, Dina and I responded there, I'm going to leave this closed :)
