### ISSUE TITLE
endDialog() incorrectly resumes a 'parent' dialog

### ISSUE THREAD

**Issue by SynerG** [Microsoft/BotBuilder#4169]
## Bot Info
* SDK Platform: Node.js
* SDK Version: 3.12.0

## Issue Description

Ending a dialog sometimes has unexpected side effects that corrupts the dialog stack and leaves it in an unexpected state.

The issue is caused by the assumptions made by the `session.endDialog()/.endDialogWithResult()` methods. When called, these methods assume that the next dialog in the stack is its parent and should move forward to the next step or be removed from the stack (if there are no more steps). But sometimes this assumption is not correct.

For example, let's say we a dialog stack that contains a dialog `A`:
```
callstack = [A]
```
Then, an event happens that adds dialog `B` to the stack:
```
callstack = [A,B]
```
The event (e.g. a timer, a external action, or even a command in the conversation) is unrelated to A, so **A is NOT the parent of B**.

## Expected Behavior
When `B` executes `B.endDialog()`, `B` should be removed from the stack, but `A` should be left untouched (as it is unrelated to `B`).

## Actual Results
When `B` executes `B.endDialog()`, the current implementation removes `B` , and CAUSES `A` to move forward to its next step. 

Moreover, if `A` does not have more steps, `A` is also removed from the stack and the *'move forward or delete'* effect cascades to the next dialog in the call stack.

For example, in a callstack where `A` launches a single-step `A_child` that proposes some buttons to the user and will communicate the button pressed to its parent `A`. If an event causes to launch a `B` dialog for a notification, we get this dialog stack:
```
callstack = [A, A_child, B]
```
When `B` executes `B.endDialog()`, the single-step `A_child` dialog is directly removed (although the user has no pressed any button yet), and `A` is resumed at its next step without the result expected from `A_child` button choice.

## Desired Solution
`BotBuilder SDK` should keep track of why the dialog was added to the stack. If the dialog is not a child of the next dialog in the stack, ending the dialog should not have any side effects in the next dialog (no moving forward or removing it).

## Current Workaround
I have seen in the implementation of `WaterfallDialog` that when a dialog is resumed with `ResumeReason.reprompt` the dialog does not move forward, neither executes a step.

So, as a hacky solution, in dialogs that are only added to the stack due to external events, I am ending them with `session.endDialogWithResult({resumed: ResumeReason.reprompt})` to prevent dialog stack corruption.
However, it is not really a `reprompt` and this is an internal implementation detail that could change in the future with unexpected consequences.

`Botbuilder SDK` should directly keep track of why the dialog was added to the stack, and not resume the 'parent' if it is not really its parent.

**Comment by Kyle-MacKinnon** [comment]
This is a problem I have also become intimately familiar with and developed my own solutions for. I would greatly appreciate a BotBuilder managed solution for going backwards in the dialog stack.

Currently I have about 60 lines of code dedicated to solving this problem in the form of a hacky workaround. If that could simply be a session.backDialog() then I would be an extremely happy developer.

**Comment by SynerG** [comment]
Ok, I have found an "official" approach to begin a dialog without a parent.

`BotBuilder SDK` internally implements an `Interruption`dialog (`consts.DialogId.Interruption`).
This special dialog is added to the callstack to act as a wrapper of the real dialog that should begin. When the dialog ends, `Interruption` uses exactly the `ResumeReason.reprompt` tip that I discussed previously to prevent activating the next dialog in the stack (as it is not a parent).

However, you cannot manually wrap the dialog in an `Interruption` directly because the internal `consts.DialogId` is not re-exported. So you cannot use it in your own `customAction()` for example.

AFAIK, the `Interruption` wrapper dialog is only used by the method `beginDialogAction()`.

So, to add a dialog to the stack that is not a child of a previous dialog, it should be started using  `beginDialogAction()`. 

If you start the dialog with `beginDialog()`, there is no parameter you can specify to indicate that it is an interruption and `BotBuilder` does not control where/how the dialog was added, so it is always considered a child of the previous dialog in the stack.

As the `beginDialogAction()` method exists, this issue can be closed. Although it would be great if  `BotBuilder` automatically managed the dialog hierarchy (beyond a stack) or there was a parameter for `beginDialog()` to indicate that the dialog added to the stack is not a child.

**Comment by FranciscoPonceGomez** [comment]
Hi SynerG,

I will take note of this feature request. Thank you for your patience.

Francisco

**Comment by SynerG** [comment]
Gracias Francisco,
Actually, I have realized that not all my previous actions can be replaced with a `beginDialogAction()` to prevent resuming the unrelated 'parent'.
In particular, I have some `customActions()` where I need to dynamically decide which `dialogId` should begin. This decision is currently taken in `onSelectAction()`.
However, `beginDialogAction()` requires to define a single static `dialogId` in order to take advantage of the non-resuming feature, so it is not as flexible.
So, it would be great if the framework provided another strategy to control whether the dialog needs to resume a parent.

Thanks again!
