### ISSUE TITLE
HeroCard buttons don't work on facebook channel, please tell which card can I use on facebook channel

### ISSUE THREAD

**Issue by jimmyhawkins** [Microsoft/BotBuilder#4172]
## Bot Info
* SDK Platform: 
* SDK Version: 
* Active Channels: 
* Deployment Environment: 

## Reproduction Steps
1.
2.
3.

**Comment by JasonSowers** [comment]
Please fill out the template so we can better assist you

**Comment by jimmyhawkins** [comment]
var message = await result as Activity;
var PrincipalMenu = new HeroCard
                    {
                        Title = "Welcome user",
                        Subtitle = "¿What can I help you?",
                        Buttons = new List<CardAction> {
                                new CardAction(ActionTypes.ImBack, "Collections", value: "Collections"),
                                new CardAction(ActionTypes.ImBack, "Information", value: "Information"),
                                new CardAction(ActionTypes.ImBack, "SendMail", value: "SendMail")
                        }
                    };

                    Attachment newAttachment = PrincipalMenu.ToAttachment();
                    message.Attachments.Add(newAttachment);

                    await context.PostAsync(message);
......
when select button like "Information" must show next element, in my case should be another menu, but beside that it returns the message "Sorry, my bot code is having an issue.", and when I type directly on the keyboard that text in the value "Information", then the next menu shows, for now it works on skype and webchat

**Comment by jimmyhawkins** [comment]
var message = await result as Activity;
var PrincipalMenu = new HeroCard
{
Title = "Welcome user",
Subtitle = "¿What can I help you?",
Buttons = new List<CardAction> {
new CardAction(ActionTypes.ImBack, "Collections", value: "Collections"),
new CardAction(ActionTypes.ImBack, "Information", value: "Information"),
new CardAction(ActionTypes.ImBack, "SendMail", value: "SendMail")
}
};

                Attachment newAttachment = PrincipalMenu.ToAttachment();
                message.Attachments.Add(newAttachment);

                await context.PostAsync(message);
......
when select button like "Information" must show next element, in my case should be another menu, but beside that it returns the message "Sorry, my bot code is having an issue.", and when I type directly on the keyboard that text in the value "Information", then the next menu shows, for now it works on skype and webchat

**Comment by jimmyhawkins** [comment]
var message = await result as Activity;
var PrincipalMenu = new HeroCard
{
Title = "Welcome user",
Subtitle = "¿What can I help you?",
Buttons = new List {
new CardAction(ActionTypes.ImBack, "Collections", value: "Collections"),
new CardAction(ActionTypes.ImBack, "Information", value: "Information"),
new CardAction(ActionTypes.ImBack, "SendMail", value: "SendMail")
}
};

            Attachment newAttachment = PrincipalMenu.ToAttachment();
            message.Attachments.Add(newAttachment);

            await context.PostAsync(message);
......
when select button like "Information" must show next element, in my case should be another menu, but instead of that it returns the message "Sorry, my bot code is having an issue.", and when I type directly on the keyboard that text in the value "Information", then the next menu shows, for now it works on skype and webchat

**Comment by JasonSowers** [comment]
What version of the SDK are you using?

**Comment by jimmyhawkins** [comment]
.Net Framework 4.6

Actually, I tried to create another bot with some of the original code and a single herocard, and this works perfectly.

The only different is that I add a try catch into MessageReceivedAsync.
________________________________
De: Jason Sowers <notifications@github.com>
Enviado: jueves, 08 de febrero de 2018 1:55:35 p. m.
Para: Microsoft/BotBuilder
Cc: Jimmy Hawkins; Author
Asunto: Re: [Microsoft/BotBuilder] HeroCard buttons don't work on facebook channel, please tell which card can I use on facebook channel (#4172)


What version of the SDK are you using?

**Comment by jimmyhawkins** [comment]
I don't know yet what is triggering that error, but with the second bot I can try to find what is it on my own.


but thanks.

________________________________
De: Jason Sowers <notifications@github.com>
Enviado: jueves, 08 de febrero de 2018 2:23:13 p. m.
Para: Microsoft/BotBuilder
Cc: Jimmy Hawkins; Author
Asunto: Re: [Microsoft/BotBuilder] HeroCard buttons don't work on facebook channel, please tell which card can I use on facebook channel (#4172)


I meant the botbuilder SDK like it should be 3.x. SO you ?have resolved this on your own

**Comment by jimmyhawkins** [comment]
Thank you very much, I put a try catch into MessageReceivedAsync and into the herocards specified "title:" instead of just the text without the word "title:", and now my bot works perflectly.


Regards.

________________________________
De: Jimmy Hawkins
Enviado: jueves, 08 de febrero de 2018 2:28:11 p. m.
Para: Microsoft/BotBuilder; Microsoft/BotBuilder
Cc: Author
Asunto: Re: [Microsoft/BotBuilder] HeroCard buttons don't work on facebook channel, please tell which card can I use on facebook channel (#4172)


I don't know yet what is triggering that error, but with the second bot I can try to find what is it on my own.


but thanks.

________________________________
De: Jason Sowers <notifications@github.com>
Enviado: jueves, 08 de febrero de 2018 2:23:13 p. m.
Para: Microsoft/BotBuilder
Cc: Jimmy Hawkins; Author
Asunto: Re: [Microsoft/BotBuilder] HeroCard buttons don't work on facebook channel, please tell which card can I use on facebook channel (#4172)


I meant the botbuilder SDK like it should be 3.x. SO you ?have resolved this on your own
