### ISSUE TITLE
How to maintain same chat history in multiple tab of same browser while using web chat?

### ISSUE THREAD

**Issue by Ashish225** [Microsoft/BotBuilder#4174]
## Bot Info
* SDK Platform: .NET
* SDK Version: 
* Active Channels: Web chat
* Deployment Environment: Azure Bot Service

## Issue Description
I am using web chat channel to show chatting window in my WordPress website. It clears chat history and starts chat from beginning when I refresh page or open new page in new browser tab. How can I maintain same chat history between multiple tabs or when I refresh the page?

## Reproduction Steps
1. Start chat
2. Open new browser tab or Refresh current page

## Expected Behavior
It should maintain keep same chat history between multiple browser tabs

## Actual Results
It starts new chat

**Comment by JasonSowers** [comment]
Please take a look at [this project](https://github.com/JasonSowers/ChatHistoryBot-Public) In it I am accomplishing exactly what you are looking for.  Feel free to raise any issues or ask any questions on the repo if you need help.

**Comment by fanidamj** [comment]
Closing the issue assuming it as resolved. Please reopen a new issue if it still persists.
