### ISSUE TITLE
[Node.js SDK, DirectLine, Bug] Directline removes custom adaptive card input types

### ISSUE THREAD

**Issue by harshithkashyap** [Microsoft/BotBuilder#4177]
## Bot Info
* SDK Platform: Node.js
* SDK Version: 3.12.0
* Active Channels: Direct Line
* Deployment Environment: Azure Bot Service

## Issue Description
Custom input elements can be created using [Adaptive Cards HTML SDK](https://docs.microsoft.com/en-us/adaptive-cards/display/libraries/htmlclient#custom-element-rendering).

We created a `Input.Password` element to accept password inputs from user and mask the display. The adaptive card SDK works well with custom password input element but when the adaptive card json is sent from bot to user via directline, the `Input.Password` element is removed from the json.

## Code Example

Original card:
```jsonc
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "TextBlock",
            "text": "Input password"
        },
        {
            "type": "Input.Password", /* Custom Input Type */
            "id": "input3",
            "placeholder": "Input password"
        }
    ]
}
````

JSON from directline websocket stream:
```json
"content": {
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
        "type": "TextBlock",
        "text": "Input password"
        }
    ]
}
```

## Reproduction Steps
1. Send the above adaptive card using botbuilder sdk.
2. Connect to bot via directline on the client.

## Expected Behavior
If I render the above card directly without sending it from backend, the password input field is rendered as expected.

### Rendered directly at client.
![image](https://user-images.githubusercontent.com/4183260/36011993-35d17d4e-0d81-11e8-8f2a-6ee4ca9ebca2.png)

### Rendered via directline.
![image](https://user-images.githubusercontent.com/4183260/36012028-6973718e-0d81-11e8-889c-b1a6c90eb839.png)

**Comment by fanidamj** [comment]
Can you please let us know if the issue still persists?

**Comment by harshithkashyap** [comment]
@fanidamj I just checked it. We are still facing this issue.

**Comment by cleemullins** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues


For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botbuilder-channels/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
