### ISSUE TITLE
[.Net SDK, Adaptive Cards, FB Messenger] Error in adding attachment Adaptive Cards on Facebook Messenger reply

### ISSUE THREAD

**Issue by oyen** [Microsoft/BotBuilder#4183]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.12.2.4
* Active Channels: Skype, Direct Line, Facebook Messenger
* Deployment Environment: Azure Bot Service

## Issue Description

I get the following error in my Facebook channel when my Bot replies with an attachment of Adaptive Cards: 

> Failed with error: Microsoft.Rest.HttpOperationException: SendActivityToUserAsync FAILED: {"error":{"message":"(#194) param name_placeholder[elements] has too few elements.","type":"OAuthException","code":194,"fbtrace_id":"EvKMopV4m\/J"}}

## Code Example

[LuisIntent("GetAllCards")]
public async Task GetAllCards(IDialogContext context, LuisResult result)
{
        var reply = context.MakeMessage();

        reply.Text = "Here's a few sample of cards..."; //does not appear in facebook?
        reply.Attachments = new List<Attachment>();
        reply.AttachmentLayout = AttachmentLayoutTypes.Carousel;

        if (context.ConversationData.GetValue<string>(ContextKeys.ChannelId) == "facebook")
        {
            await context.PostAsync("Here's a few sample of cards...");
        }

        using (var entities = new MyEntities())
        {
            var query = ...get stuff...                              

            var cpList = query.ToList();

            //each item is an attachment in carousel
            foreach (var cp in cpList)
            {
                var card = GetSingleCard(cp);
                var attachment = new Attachment()
                {
                    Content = card,
                    ContentType = "application/vnd.microsoft.card.adaptive",
                    Name = cp.DisplayName //this does not actually appear anywhere on the bot when I tested
                };
                reply.Attachments.Add(attachment);
            }

            await context.PostAsync(reply);                
}

private AdaptiveCard GetSingleCard(MyProduct cc)
{
    var card = new AdaptiveCard();

    card.Title = cc.DisplayName; //this is not shown anywhere in my bot test

    //title
    var title = new Container();
    card.Body.Add(title);

    var titleText = new TextBlock();
    title.Items.Add(titleText);
    titleText.Size = TextSize.Large;
    titleText.Text = $"**{cc.Title}**";

    var subTitleText = new TextBlock();
    title.Items.Add(subTitleText);
    subTitleText.Size = TextSize.Medium;
    subTitleText.Text = cc.SubTitle;
    subTitleText.Wrap = true;
    subTitleText.MaxLines = 1; 

    //image
    var cpImage = new AdaptiveCards.Image();
    card.Body.Add(cpImage);
    cpImage.Url = cc.ImageUrl;
    cpImage.Size = ImageSize.Large;

    //details
    var details = new FactSet();
    card.Body.Add(details);

    details.Facts.Add(new AdaptiveCards.Fact("Customer Rating", cc.Rating);
    details.Facts.Add(new AdaptiveCards.Fact("Detail A", cc.DetailA));
    details.Facts.Add(new AdaptiveCards.Fact("Detail B", cc.DetailB));

        var action = new OpenUrlAction();
        action.Url = $"https://google.com";
        action.Title = $"Read more";
        card.Actions.Add(action);

    return card;
}

## Reproduction Steps
1. Create a reply with carousel attachments
2. Add adaptive cards to attachments
3. Bot sends reply to user as a response

## Expected Behavior

I expected to see the image-rendered Adaptive Cards without errors.

## Actual Results

 The attachments will be received by the user followed by the error message:
> Failed with error: Microsoft.Rest.HttpOperationException: SendActivityToUserAsync FAILED: {"error":{"message":"(#194) param name_placeholder[elements] has too few elements.","type":"OAuthException","code":194,"fbtrace_id":"EvKMopV4m\/J"}}

**Comment by JasonSowers** [comment]
please fill out the information section of your post so we can better assist you.

**Comment by oyen** [comment]
@JasonSowers  I filled it up

**Comment by JasonSowers** [comment]
@oyen were you able to resolve this?

**Comment by oyen** [comment]
@JasonSowers  I checked and the error no longer appears. I did not do anything to fix it.

The image-rendered adaptive cards are still bad: the texts do not always show all lines like there should be 3 but only 1 or 2 appear, and has a weird "Title" element that appears on FB but not on web/emulator.

**Comment by JasonSowers** [comment]
Can you share a screenshot of what you are seeing?

**Comment by oyen** [comment]
I [collated 3 images: emulator vs fb (2 cards) vs fb (3 cards) to highlight the differences]
(https://siritsit.blob.core.windows.net/siritsitcontent/20180703%20emulator%20vs%20fb.png)

**Comment by JasonSowers** [comment]
@oyen I would report this in the [Adaptive Cards](https://github.com/Microsoft/AdaptiveCards) repository

**Comment by oyen** [comment]
Ok I will do that.

**Comment by oyen** [comment]
Got it.

**Comment by JasonSowers** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
