### ISSUE TITLE
BotError : Failed to send activity: bot returned an error. httpStatusCode: 500

### ISSUE THREAD

**Issue by pankajdmishra** [Microsoft/BotBuilder#4184]
## Bot Info
SDK Platform: .NET
SDK Version: 3.12.2.4
Emulator Version: 3.5.35
Active Channels: Directline v3

## Issue Description
calls made to https://directline.botframework.com/v3/directline/conversations/conversationId/activities
 is providing error code 502(Bad gateway)

![image](https://user-images.githubusercontent.com/25457761/36094990-c429cf3a-1009-11e8-84f2-bb06aee34886.png)
----------------------------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/25457761/36095022-e3911e14-1009-11e8-8a9f-526082256676.png)

## Code Example
        BotChat.App({
            botConnection: botapp.botConnection,
            user: botapp.user,
            bot: bot,
            resize: 'detect'
        }, document.getElementById("divbot"));

## Reproduction Steps
trying to test the service from rest client (postman)
1. Generating Token from "https://directline.botframework.com/v3/directline/tokens/generate"
2. Passing the generated token in "https://directline.botframework.com/v3/directline/conversations"
3. Passing the generated conversationId from step2 in "https://directline.botframework.com/v3/directline/conversations/conversationId/activities"
The output result is 

![image](https://user-images.githubusercontent.com/25457761/36095200-a9488d86-100a-11e8-9270-391923caa260.png)

## Expected Behavior
It should give 200 ok

## Actual Results
![image](https://user-images.githubusercontent.com/25457761/36095214-b4842930-100a-11e8-8035-81a92697f35c.png)

community need your expert advice on this. In real tight schedule to deliver this chunk. Need your support.

**Comment by pankajdmishra** [comment]
Even from my UI code this piece is providing 502 error
simplified code for the same is below

![image](https://user-images.githubusercontent.com/25457761/36095743-ece7fcfa-100c-11e8-9c32-1d9b66658c33.png)

From Above mention code it flows to 

![image](https://user-images.githubusercontent.com/25457761/36095808-251179a8-100d-11e8-9f6f-99669bb7c801.png)


Please help me on this issue

**Comment by EricDahlvang** [comment]
@pankajdmishra Please post the code example, not images of the code.

**Comment by shahsaurabh0605** [comment]
I am facing similar error. Just hosted the sample bot framework code on azure and worked on direct line api. Doesn't work.

**Comment by EricDahlvang** [comment]
@shahsaurabh0605 What exactly "doesn't work"?  Please be more specific, and explain the errors or issues you've run into so we can assist you.

**Comment by shahsaurabh0605** [comment]
Issue is clearly mentioned by @pankajdmishra . I follow the 3 steps: 

1) Generating Token from "https://directline.botframework.com/v3/directline/tokens/generate"
2) Passing the generated token in "https://directline.botframework.com/v3/directline/conversations"
3) Passing the generated conversationId from step2 in "https://directline.botframework.com/v3/directline/conversations/conversationId/activities"

And get the similar error on postman:

![36095200-a9488d86-100a-11e8-9270-391923caa260](https://user-images.githubusercontent.com/11133421/36117860-2c4641dc-1061-11e8-891d-fd061b0416fb.png)

**Comment by EricDahlvang** [comment]
1. Generate a Token from https://directline.botframework.com/v3/directline/tokens/generate

![image](https://user-images.githubusercontent.com/11055362/36120920-960d1202-0ff9-11e8-8719-894b994358ca.png)

2. Passing the generated token in https://directline.botframework.com/v3/directline/conversations

![image](https://user-images.githubusercontent.com/11055362/36120971-b4f397cc-0ff9-11e8-8e04-fa393d5acaf4.png)

3. Passing the generated conversationId from step2 in https://directline.botframework.com/v3/directline/conversations/conversationId/activities

![image](https://user-images.githubusercontent.com/11055362/36121063-f98d4ffe-0ff9-11e8-833e-e5a68857d3f1.png)

**Comment by EricDahlvang** [comment]
I've seen the BotError before, but only if the bot is not actually running at the Messaging Endpoint:

![image](https://user-images.githubusercontent.com/11055362/36121781-15e9f51a-0ffc-11e8-8b9e-1e8d183b45c9.png)

**Comment by shahsaurabh0605** [comment]
I have hosted the bot on azure, say with the name "x-bot". Then is "https://x-bot.azurewebsites.net/api/messages" the correct messaging endpoint setup?

**Comment by EricDahlvang** [comment]
@shahsaurabh0605 Yes, that would most likely be the correct endpoint

**Comment by pankajdmishra** [comment]
Hi @EricDahlvang sorry for the late reply. Please find the code below.
1. Firstly on my index page i am reading some user details
-------------------------------------------------------------------------------------------------------------------
        var loggedInUserDetails = {
            botsecret: 'botSecretkeyHere',
            personalNbr: '11002886',
            username: 'pankajMishra',
            EID: 'pmishra.dic',
            IfFirstUser: 'true',
            conversationId: 'ConversationIdHere'
        };
-------------------------------------------------------------------------------------------------------------------
2. Then i am calling a Js function to initialize bot and pass "loggedInUserDetails" to that function
-------------------------------------------------------------------------------------------------------------------
botapp.initilizeBot(loggedInUserDetails);
-------------------------------------------------------------------------------------------------------------------
3. Also every time a user post a query this piece of code gets called.

BotChat.App({
            botConnection: botapp.botConnection,
            user: botapp.user,
            bot: bot,
            resize: 'detect'
        }, document.getElementById("divbot"));
-------------------------------------------------------------------------------------------------------------------
var botapp = {
    params: {},
    botConnection: null,
    user: null,
    initilizeBot: function (loggedInUserDetails) {
        location
            .search
            .substring(1)
            .split("&")
            .forEach(function (pair) {
                var p = pair.split("=");
                botapp.params[p[0]] = decodeURIComponent(p[1]);
            });
        botapp.botConnection = new BotChat.DirectLine({
            secret: loggedInUserDetails.botsecret,
            token: botapp.params['t'],
            domain: botapp.params['domain'],
            conversationId: loggedInUserDetails.conversationId,
            watermark: 0,
            webSocket: false
        });
        botapp.user = {
            id: loggedInUserDetails.personalNbr || 'userid1',
            name: loggedInUserDetails.username || 'you'
        };

        var bot = {
            id: botapp.params['botid'] || 'botid',
            name: botapp.params["botname"] || 'botname'
        };
        BotChat.App({
            botConnection: botapp.botConnection,
            user: botapp.user,
            bot: bot,
            resize: 'detect'
        }, document.getElementById("divbot"));

        botapp.botConnection.activity$
            .filter(function (activity) { return activity.type === "event" })
            .subscribe(function (activity) { return botapp.captureEvents(activity) })
        botapp.botConnection.activity$
           .filter(function (activity) { return activity.topicName === "VerticalOrientation" })
            .subscribe(function (activity) { return botapp.cardLayoutStyle(activity.topicName) })

        if (typeof (loggedInUserDetails.conversationId) == 'undefined' || loggedInUserDetails.conversationId == '')
            botapp.triggerWelcome(loggedInUserDetails.IfFirstUser);
    }
};
-------------------------------------------------------------------------------------------------------------------
4. Ajax call for directline is below
-------------------------------------------------------------------------------------------------------------------
t.prototype.postActivity = function (t) {
                    var e = this;
                    return "message" === t.type && t.attachments && t.attachments.length > 0 ? this.postMessageWithAttachments(t) : (l.log("postActivity", t), this.checkConnection(!0).flatMap(function (n) {
                        return i.Observable.ajax({
                            method: "POST",
                            url: e.domain + "/conversations/" + e.conversationId + "/activities",
                            body: t,
                            timeout: 2e4,
                            headers: {
                                "Content-Type": "application/json",
                                Authorization: "Bearer " + e.token
                            }
                        }).map(function (t) {
                            return t.response.id
                        }).catch(function (t) {
                            return e.catchPostError(t)
                        })
                    }).catch(function (t) {
                        return e.catchExpiredToken(t)
                    }))
                }

**Comment by pankajdmishra** [comment]
Also if you'll see on portal upon checking the channels for direct line its showing errors PFB

![image](https://user-images.githubusercontent.com/25457761/36134987-920b8a14-10a1-11e8-87f4-944c848e9260.png)

@EricDahlvang  need your expert advice here....

**Comment by EricDahlvang** [comment]
@pankajdmishra I'm sorry, but I'm not really understanding what you are attempting to do.  If you are experiencing errors in your bots code, you can try debugging the bot locally: https://blog.botframework.com/2017/10/19/debug-channel-locally-using-ngrok/

Also, please try starting with one of the simple samples: https://github.com/Microsoft/BotBuilder-Samples Once you have a working example, you can build on it.

**Comment by pankajdmishra** [comment]
Hi @shahsaurabh0605 
Were you able to resolve this in any case?

**Comment by t-sashah** [comment]
@pankajdmishra yes. Actual problem was not setting the correct endpoint. I hosted the bot on localhost and with ngrok got the correct endpoint. Refer here:- [https://blogs.msdn.microsoft.com/jamiedalton/2016/07/29/ms-bot-framework-ngrok/](url)

Thanks a lot @EricDahlvang

**Comment by shahsaurabh0605** [comment]
@pankajdmishra yes. Actual problem was not setting the correct endpoint. I hosted the bot on localhost and with ngrok got the correct endpoint. Refer here:- https://blogs.msdn.microsoft.com/jamiedalton/2016/07/29/ms-bot-framework-ngrok/

Thanks a lot @EricDahlvang

**Comment by pankajdmishra** [comment]
hi @EricDahlvang 

i got the root cause for this issue with my code i believe. Below is the code snippet that is failing.

        private async Task HandleUserMessage(Activity activity)
        {
                 MicrosoftAppCredentials.TrustServiceUrl(activity.ServiceUrl, DateTime.MaxValue);
                 ConnectorClient connector = new ConnectorClient(new Uri(activity.ServiceUrl));
        }

I have a method HandleUserMessage() just as we have HandleSystemMessage()
In this i am trying to create a connector with serviceUrl that comes in activity. when the code reaches here it throws error saying 500 internal server error.

**Comment by EricDahlvang** [comment]
@pankajdmishra  The code you've provided in HandleUserMessage should function, if your bot is configured properly.  I just tested it, and it worked.

As I had suggested previously, please try debugging locally: https://blog.botframework.com/2017/10/19/debug-channel-locally-using-ngrok/

Also, please try starting with one of the simple samples: https://github.com/Microsoft/BotBuilder-Samples. Once you have a working example, you can build on it.

**Comment by pankajdmishra** [comment]
Hi @EricDahlvang 

Thanks alot. I tried debugging my code using ngrok.
Steps i performed using ngrok as as below
1. I executed ngrok cmd
2. runned following command (ngrok http 3979 -host-header="localhost:3979")
3. got a forwarding uri. I changed my endpoint on azure portal with this forwarding URI pfb.
![image](https://user-images.githubusercontent.com/25457761/36480928-86225db8-1727-11e8-8b8d-11d756a7b712.png)
4. I runned my code locally in debug mode.
5. Using webchat control from, azure portal i posted few queries and it worked fine. I got expected response when i used ngrok for debugging.

there was no failure.
Now the question is, was there a issue with my endpoint? below screen shots shows configuration of my bot.

![image](https://user-images.githubusercontent.com/25457761/36481053-010d0f00-1728-11e8-84e7-b95f2e69f5f4.png)
This is the service URL for my bot app.

![image](https://user-images.githubusercontent.com/25457761/36481127-44c573ea-1728-11e8-97fe-b2f070e31558.png)
this is my BotId

Endpoint that i previously had before ngrok was 
https://sofeachatbot-stage.azurewebsites.net/api/messages

was this endpoint correct?
If not than how to rectify which is the correct endpoint to configure?

Thanks in advance.

**Comment by pankajdmishra** [comment]
Hi,

I resolved this issue. Very stupid mistake done by me.
While creating the bot the i changed my Password from WebAppBot --> Settings, "manage" PFB

![image](https://user-images.githubusercontent.com/25457761/36640447-4e279a36-1a38-11e8-8f58-253c2109e064.png)

And didn't updated the App service of the bot with the new password. In App service of your bot 
App Service --> Application settings change the password as well. PFB

![image](https://user-images.githubusercontent.com/25457761/36640465-b326f486-1a38-11e8-885a-3106ff6a6626.png)

else this will always through 502 error.

Thanks alot @EricDahlvang  and @shahsaurabh0605  for all your support.

Appreciated 👍 

Closing this issue

**Comment by klamgade** [comment]
@tinuCoder  @EricDahlvang  Even after updating the MicrosoftAppPassword in Application Settings of App service, I am still having this issue. 
In postman, 
`{
    "error": {
        "code": "BotError",
        "message": "Failed to send activity: bot returned an error"
    },
    "httpStatusCode": 417
}`

**Comment by pkaushik23** [comment]
> 
> 
>     1. Generate a Token from https://directline.botframework.com/v3/directline/tokens/generate
> 
> 
> ![image](https://user-images.githubusercontent.com/11055362/36120920-960d1202-0ff9-11e8-8719-894b994358ca.png)
> 
>     1. Passing the generated token in https://directline.botframework.com/v3/directline/conversations
> 
> 
> ![image](https://user-images.githubusercontent.com/11055362/36120971-b4f397cc-0ff9-11e8-8e04-fa393d5acaf4.png)
> 
>     1. Passing the generated conversationId from step2 in https://directline.botframework.com/v3/directline/conversations/conversationId/activities
> 
> 
> ![image](https://user-images.githubusercontent.com/11055362/36121063-f98d4ffe-0ff9-11e8-833e-e5a68857d3f1.png)

Hello @EricDahlvang i am following the exact steps that you pointed out.

1) running locally developed with v4 sdk
2) Bot connector service configured with the ngrok fwrd url
3) have a directline channel configured
4) successfully getting the token and conversationid, with the exception that conversation id is always appended with a -c. example : 
```

{
    "conversationId": "JQfgEvc7if86Qt1CwuV414-c",
    "token": "token that was returned",
    "expires_in": 1800,
    "streamUrl": "wss://directline.botframework.com/v3/directline/conversations/JQfgEvc7if86Qt1CwuV414-c/stream?watermark=-&t=GaM9ExIOdJk.dAA.SgBRAGYAZwBFAHYAYwA3AGkAZgA4ADYAUQB0ADEAQwB3AHUAVgA0ADEANAAtAGMA.eIj5E3vp1AE.GEB8PJfGae4.5rT75D232c9Ht5wDOpuNT5LlEUmvhuLXkqnxUnLRCsU",
    "referenceGrammarId": "88a91a98-2ddc-8a5d-ab4d-f76f2b5c876c"
}
```
5) When i execute following https://directline.botframework.com/v3/directline/conversations/JQfgEvc7if86Qt1CwuV414-c/activities i always get internal server error 

```
{
  "error": {
    "code": "ServiceError"
  }
}
```
Following is my request object 
```
{
    "type": "message",
    "from": {
        "id": "user1"
    },
    "text": "hello"
}
```

Please help me identify the issue.

Thanks,
Prerak

**Comment by pkaushik23** [comment]
this post explains the exact error i am having

https://stackoverflow.com/questions/45047722/500-when-trying-to-send-message-to-bot-via-direct-line-api?rq=1

**Comment by pkaushik23** [comment]
For anyone else facing the same issue, here is the advice.
The issue is, **only the token which was received against 'start conversation'** can be used to 'send an activity'.
refer [this SO answer](https://stackoverflow.com/a/46700094) and read Q3

Thanks.
