### ISSUE TITLE
[Question] Microsoft Bot Framework On-Premise Hybrid Hosting Requirements (with Azure Bot Service) 

### ISSUE THREAD

**Issue by yuwc** [Microsoft/BotBuilder#4185]
**Scenario: Bot Framework On-Premise Hybrid Hosting (with Azure Bot Service)**
- **Azure Bot Service:** On Azure Cloud 
- **Bot Framework:** On-premise .NET solution (behind corporate firewall, web servers by default do not have outgoing internet access and requires hostname & port exclusion / whitelist)

I've yet to find a complete article/guide that specifies the full requirements to hosting a Hybrid Bot Framework scenario. Can I seek help in validating this list, and also adding on if there's any info that I've missed out / not documented?

Here's an attempt to compile what I know so far:
**Requirement 1: Exposing Bot Framework endpoint, with current and valid certificate (For Web server incoming from internet)**
The Bot Framework requires that the x.509v3 certificate exposed by your endpoint be current and valid. 

**Requirement 2: Cert must chain to Microsoft trusted root certificate authority**
Cert must chain to a root certificate authority trusted by Microsoft. The latest list of these CAs is available here: http://social.technet.microsoft.com/wiki/contents/articles/31634.microsoft-trusted-root-certificate-program-participants-v-2016-april.aspx

**Requirement 3: Whitelist URLs in your corporate firewall (For Web server outgoing to internet)**
All URLs to whitelist are HTTPS (port 443).
_Required_
- login.microsoftonline.com (Bot authentication)
- *.botframework.com (Bot authentication, Channels and other API calls) (There's a need to wild card this, as more than one sub-domains are used, increases depending on the connected channel. e.g. login.botframework.com, api.botframework.com, facebook.botframework.com, etc.)

_Optional_
- *.api.cognitive.microsoft.com (Necessary if there are any Cognitive Services calls, see reference 5 for respective region URL)
- cortanabfchanneleastus.azurewebsites.net (Necessary if using Cortana channel)
- cortanabfchannelwestus.azurewebsites.net (Necessary if using Cortana channel)

_Deprecated / Not Needed_

- state.botframework.com (Bot Framework State Service API has been deprecated. But it shall already be covered under Required URL 2.)

## References
1. [Github Issue #2927](https://github.com/Microsoft/BotBuilder/issues/2927)
2. [Which specific URLs do I need to whitelist in my corporate firewall to access bot services](https://docs.microsoft.com/en-us/Bot-Framework/bot-service-resources-bot-framework-faq) (p/s. Microsoft docs team, information here is not up to date as there are more cognitive API regions.)
3. [How bot framework connector authentication works](https://docs.microsoft.com/en-us/bot-framework/rest-api/bot-framework-rest-connector-authentication)
4. [Steps to troubleshoot authentication problems](https://github.com/MicrosoftDocs/bot-framework-docs/blob/live/articles/bot-service-troubleshoot-authentication-problems.md)
5. [List of LUIS Endpoint API by region](https://westus.dev.cognitive.microsoft.com/docs/services/5819c76f40a6350ce09de1ac/operations/5819c77140a63516d81aee78)

**Comment by yuwc** [comment]
Hi guys, with regards to validating the info above, would you have any updates and findings to share? Thanks.

**Comment by yuwc** [comment]
Hi guys, it's been over 2 weeks. Can anyone from Microsoft confirm if the above information is valid?

**Comment by FranciscoPonceGomez** [comment]
Hi yuwc, 

Sorry for the delay. I will check this out today.

Francisco

**Comment by yuwc** [comment]
Thanks Francisco . Appreciate the help, as the client's waiting on this.

**Comment by yuwc** [comment]
hi @FranciscoPonceGomez can you share an estimated time when you can complete verifying?
we're using bot framework for production use, and can't wait indefinitely.
Or will Microsoft's stance be that bot framework cannot be used for on-premise, or will not provide any official support on-premise hosting? Hence why the lack of documentation?

**Comment by FranciscoPonceGomez** [comment]
Hi yucw,
I am escalating your question. I will get back to you shortly.

Currently the bot must have an internet-accessible endpoint for it to work with Bot Connector servers, such as servers for Skype, Microsoft Teams, etc. You can deploy your bot in an on-premise installation as long as its endpoint can be addressed from the internet.

The Bot Builder libraries do not fundamentally rely on internet access, although some features do use internet services. LUIS, for example, is only available on the internet, so you would need to rely on a different technique for classifying text (such as regex intents/dialogs, which are supported but which offer different features than LUIS). Additionally, the service-to-service auth used to verify the authenticity of Bot Framework calls also requires internet access.

Regards,
Francisco

**Comment by FranciscoPonceGomez** [comment]
There is a piece of information that is not clear for me. Is your customer planning on hosting the bot service on Azure or on their servers? What I understood is that they want to host their bot in Azure but they have their own client application is on their machine. Is that correct? 

Have you considered using the Direct Line Service?
https://docs.microsoft.com/en-us/bot-framework/rest-api/bot-framework-rest-direct-line-3-0-concepts

You can enable communication between the bot service and your own client service via REST API easily.

**Comment by yuwc** [comment]
The background of the setup is:

1. **Azure Bot Service**: On Azure Cloud & Connected to the Facebook Channel
2. **Bot Framework**: On-premise Bot Framework .NET solution (behind corporate firewall, web servers by default do not have outgoing internet access and requires hostname & port exclusion / whitelist)

Hence the question is about on-premise server / network requirements to ensure the **(2) On-premise Bot Framework** deployment has all the necessary configurations to enable 2-way communications with **(1) Azure Bot Service**.

**Comment by yuwc** [comment]
Hi @FranciscoPonceGomez any news from your escalation? Thanks.

**Comment by FranciscoPonceGomez** [comment]
Yes. if your using your own .NET solution for the client, you need to use Direct Line. So your list is correct but you need to add DL host names depending on the location:

•	**directline.botframework.com** routes your client to the nearest datacenter. This is the best option if you do not know where your client is located.
•	**asia.directline.botframework.com** routes only to Direct Line servers in Eastern Asia.
•	**europe.directline.botframework.com** routes only to Direct Line servers in Europe.
•	**northamerica.directline.botframework.com** routes only to Direct Line servers in North America.

Regards,
Francisco

**Comment by yuwc** [comment]
Thanks @FranciscoPonceGomez. I'll take this that you're confirming that the above 3 requirements are all correct, and all that's needed to enable Bot Framework On-Premise Hybrid Hosting (with Azure Bot Service).

Thanks also for the additional URLs for directline. However, until there's an officially managed article, that lists all the possible botframework sub-domain URLs (I understand there are some common URLs, and some Channel / Region specific), I think the safest will be to (wildcard) 

> https://*.botframework.com

p/s. I'm using standard Bot framework (Microsoft bot builder SDK) for the client, using Azure Bot Services in Eastern Asia.
