### ISSUE TITLE
[Node.js SDK, FB Messenger] Redirecting requests from my server to the connector

### ISSUE THREAD

**Issue by amitbend** [Microsoft/BotBuilder#4188]
## Bot Info
* SDK Platform:  Node.js 
* SDK Version: 3.14
* Active Channels: fb
* Deployment Environment: bot service

## Issue Description
As a way to handle the inability of Botbuilder to work with multiple page tokens in Facebook (see #1495)
I was wondering if it's possible to redirect requests from my bot server to the connector service.

a scheme what I'm trying to do:
facebook wehbook -> my bot/Azure function -> connector -> my bot -> back to facebook

I tried to redirect the requests from Facebook to `https://facebook.botframework.com/api/v1/bots/<my bot>`, but I'm always getting back an empty response with code 403.

**Comment by JasonSowers** [comment]
You can now register a bot to multiple Facebook pages.  If you are still having trouble please open a new issue.

**Comment by amitbend** [comment]
@JasonSowers Any docs regarding this ability?

**Comment by JasonSowers** [comment]
I was actually mistaken that it was already released, I just got back from a vacation and figured it would have been by now.  Therefore, we did not release any docs yet.  I was also thinking multiple pages to one bot, which should be released in the near future. 

 Let me be more thorough in my explanation as well.  You can register multiple bots to the same page. You would just need a "Bot channels registration" in Azure for each page using the Facebook credentials (page id, secret).  Then you can set your messaging endpoint to your the bot's endpoint.

**Comment by amitbend** [comment]
@JasonSowers This means I will need to create "Bot channels registration" for each page but will be able to register them all to the same Facebook app?
If so - I see it as the Ideal situation, as it keeps the bots as separate identities (like any other channel), but I don't have to provision a new Facebook app for each page.

**Comment by JasonSowers** [comment]
@amitbend When you say 

> This means I will need to create "Bot channels registration" for each page

Do you mean for each bot? If so, yes.  I haven't personally tested this but, there should be nothing on our end preventing you from using your Facebook credentials on multiple bot registrations.

 There are 2 pieces of functionality I may be confusing myself with:

1.  Having multiple Facebook pages registered to a single bot, this is in the works and will be released soon.
2. Having multiple bots registered to a single page.  This should work already by using the process I described above.

I am assuming you are looking for number 2 am I correct?

**Comment by amitbend** [comment]
@JasonSowers 
I'm trying not to mix the MS and Facebook terms here :smile: 

What I actually mean is not any of those cases, but closer to "1". 
The **issue** is that currently, we need to create a Facebook for each page (per bot).
One solution can be option "1" - Multiple Facebook pages registered for a single bot
Another solution (which I find more correct) - Allow to register 1 page per one bot **but** on the same Facebook App that you've previously created (The issue today is that each bot product a different webhook, and Facebook allows specifying only one per app)
The result, in that case, will be - 1 bot with 1 page, registered to a Facebook app with multiple pages.
I hope this is clear enough :thinking:

**Comment by JasonSowers** [comment]
So in your scenario you are using your function to route messages from Facebook to the appropriate bot? Can you elaborate a bit more about th flow you described in your original post? Your situation is unique and I want to make sure it understand it before trying to offer a solution. Maybe if you could share minimal code of how this all works it could help us flush this out.

**Comment by amitbend** [comment]
I was trying to route messages from my single facebook app (`myserver/webhook`) and redirect them to the appropriate instance of the bot (Microsoft bot/app) -> so I can work with just 1 Facebook app.

I ended up **not** doing it because I ran into issues with the redirection so currently I have 1 facebook app per 1 Microsoft bot which require me to approve a Facebook app every time I start a new bot.

**Comment by JasonSowers** [comment]
Do you want to look deeper into the original plan or can we close this issue now?

**Comment by amitbend** [comment]
@JasonSowers Whatever you think, I'm waiting for the release of the multi-page feature to see if will solve my problem

**Comment by JasonSowers** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
