### ISSUE TITLE
Utilizing Keyphrase Analysis in Microsoft Bot

### ISSUE THREAD

**Issue by teamplumaa** [Microsoft/BotBuilder#4189]
Is there a source code or tutorial that shows how to specifically use key-phrase analysis in Microsoft Bot?

**Comment by stevengum97** [comment]
Can you provide more information, such as which language of the SDK you're planning on using?

Also, what do you mean by `"key-phrase analysis"`? If you're inquiring about NLU offerings, there are the [Cognitive Services Language APIs](https://azure.microsoft.com/en-us/services/cognitive-services/directory/lang/) which may assist you in what you're looking for. If you're asking about intent classification and entity extraction, then you'll want to look at the LUIS samples ([C#](https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/intelligence-LUIS) or [Node.js](https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node/intelligence-LUIS)).

**Comment by teamplumaa** [comment]
@stevengum97 I am trying to implement the key phrase component of the Text Analytics API. 

I want to analyze a response by the user to the bot and extract key phrases or words that are in that response.

**Comment by Ma3yTa** [comment]
@teamplumaa you can use Lucene C#
Sample:
```
var analyzer = new StandardAnalyzer(Lucene.Net.Util.Version.LUCENE_30);
        var stringReader = new StringReader("the house id red");
        var tokenStream = analyzer.TokenStream(string.Empty, stringReader);
        var termAtt = tokenStream.GetAttribute<ITermAttribute>();
        while (tokenStream.IncrementToken())
        {
            Console.WriteLine(termAtt.Term);
        }
```

**Comment by stevengum97** [comment]
We don't have a complete sample for using the Text Analytics API but in the documentation for the Node.js SDK there exists some snippets on how to use the Text Analytics API to [support localization](https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-localization#determine-the-locale-by-using-analytics). The Cognitive Service APIs are REST APIs, so to call an API is pretty simple.

Here is a [quickstart guide](https://docs.microsoft.com/en-us/azure/cognitive-services/Text-Analytics/QuickStarts/CSharp) for the Text Analytics API for C#. If you want to see code samples that don't use the Nuget packages for Text Analytics, you can visit the [API reference](https://westus.dev.cognitive.microsoft.com/docs/services/TextAnalytics.V2.0/operations/56f30ceeeda5650db055a3c6?) and scroll to the bottom to find samples for C#, JavaScript, Java, Python, Ruby, etc.

**Comment by stevengum97** [comment]
Closing the issue, as an answer has been provided. If you run into problems regarding the actual implementations of the code provided by the API reference (or other related problems) please feel free to open a new issue with more details.
