### ISSUE TITLE
[Question] How can i load the Custom Client in a Dialog?

### ISSUE THREAD

**Issue by ilanopat** [Microsoft/BotBuilder#4192]
## Bot Info
* SDK Platform: .NET
* SDK Version: latest
* Active Channels: MS Teams
* Deployment Environment: local development tunneling with ngrok sideloading to MS Teams

## Issue Description
I want to load the Custom bot data inside a dialog. I implemented the custom state using Azure SQL.

## Code Example
this is from MessagesController, how can i load the botdata inside a dialog

using (var scope = DialogModule.BeginLifetimeScope(Conversation.Container, activity))
                                {
                                   
                                    var botDataStore = scope.Resolve<IBotDataStore<BotData>>();

                                    var key = Address.FromActivity(update);

                                    var userData = await botDataStore.LoadAsync(key, BotStoreType.BotUserData, CancellationToken.None);

                                    bool isWelcomed = userData.GetProperty<bool>($"{BotStoreType.BotUserData.ToString()}_userWelcomed");
                                    if (!isWelcomed)
                                    {
                                        userData.SetProperty<bool>($"{BotStoreType.BotUserData.ToString()}_userWelcomed", true);
                                        await botDataStore.SaveAsync(key, BotStoreType.BotUserData, userData, CancellationToken.None);
                                        await botDataStore.FlushAsync(key, CancellationToken.None);
                                    }

                                    scope.Dispose();
                                };

**Comment by EricDahlvang** [comment]
Dialogs provide access to the data bags by default through the context object: https://docs.botframework.com/en-us/csharp/builder/sdkreference/d1/d29/interface_microsoft_1_1_bot_1_1_builder_1_1_dialogs_1_1_i_bot_context.html

context.UserData
context.PrivateConversationData
context.ConversationData

**Comment by ilanopat** [comment]
I see, so the custom state data from sqlbotdatastore implementation can be accesed through context inside dialog?

**Comment by EricDahlvang** [comment]
Correct, the dialogs load the databags from the custom state implementation.
