### ISSUE TITLE
The "timeout" error messages

### ISSUE THREAD

**Issue by vsusloparov** [Microsoft/BotBuilder#4193]
## Bot Info
* SDK Platform: .Net
* SDK Version: 3.11
* Active Channels: Direct Line (custom webchat botchat.js)
* Deployment Environment: Azure App Service

## Issue Description
During user conversation in different dialogs the bot is stuck. After page refresh the same dialog workflow (same user's messages) the chatbot is working without issues.
We checked the issue from different networks: company internal and external networks (e.g. mobile hotspot).
**In Edge browser bot stuck match more times than in Chrome browser.**

## Code Example
Initialization of chatbot from js using token, revising activities in MessagesController with father using of LUIS service for entering to proper dialog.

Initialization of chatbot from js using token:

        ...
        vm.speechRecognizer = speechOptions.speechRecognizer = new CognitiveServices.SpeechRecognizer({
            subscriptionKey: data.speech
        });
        vm.speechSynthesizer = speechOptions.speechSynthesizer = new CognitiveServices.SpeechSynthesizer({
               gender: CognitiveServices.SynthesisGender.Female,
               subscriptionKey: data.speech,
               voiceName: 'Microsoft Server Speech Text to Speech Voice (en-US, JessaRUS)'
        });

        vm.botConnection = initDirectLine(data);
        BotChat.App({
            bot: bot,
            locale: false,
            resize: 'detect',
            speechOptions: speechOptions,
            user: user,
            botConnection: vm.botConnection,
        }, document.getElementById('CustomChatBot'));
        ...
        var initDirectLine = function (data) {
            var _botConnection = new BotChat.DirectLine({
                secret: data.token,
            });

            _botConnection.activity$.subscribe(activityGot);

            return _botConnection;
        };

## Reproduction Steps
Open **Edge browser**. Enter to Azure web site. Send any message to chat can cause the issue

## Expected Behavior
The proper work of chatbot without "timeout" errors

## Actual Results
During different dialogs in any point the bot is stuck. In console appear "timeout" error message

![timeout error 1](https://user-images.githubusercontent.com/13465370/36248216-61bd30f2-123f-11e8-8227-189fec889c78.jpg)
![timeout error 2](https://user-images.githubusercontent.com/13465370/36248217-61dce384-123f-11e8-910e-a5288493e5bb.jpg)
![error messages 3](https://user-images.githubusercontent.com/13465370/36253647-cee95046-1250-11e8-986a-276fc1a4f17e.jpg)

**Comment by EricDahlvang** [comment]
Hi @vsusloparov 

The bot has 15 seconds to acknowledge the call with a status 200.  If the bot does not respond within 15 seconds, a timeout occurs.  Is there code in your bot that is taking longer than 15 seconds to reply?

**Comment by vsusloparov** [comment]
We checked our code multiple times for deadlocks or other places where response time can be more than 15 seconds, without luck.

We changed the build in BotState storage to our data storage. After this the problem is not appeared.

Custom data storage article:
https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-state
