### ISSUE TITLE
How do you access conversation data from a controller now the state API has been made obsolete?

### ISSUE THREAD

**Issue by mcinnes01** [Microsoft/BotBuilder#4195]
Using the latest version of BotBuilder, is there a way to access/update UserData from a controller now the State API has been made obsolete?

I used to do something like this:

https://stackoverflow.com/questions/40328134/accessing-conversation-data-from-message-controller-c-sharp

**Comment by EricDahlvang** [comment]
This answer by @JasonSowers provides a solution for accessing the bot state without a context object:

https://stackoverflow.com/questions/46085614/how-can-i-access-bot-framework-conversationdata-outside-of-a-dialog/46085785#46085785

**Comment by mcinnes01** [comment]
Brilliant thank you! Exactly what I was looking for.
