### ISSUE TITLE
Bug con facebook

### ISSUE THREAD

**Issue by gfazzola** [Microsoft/BotBuilder#4196]
## Bot Info
* SDK Platform: .NET 
* SDK Version: 3.13.1
* Active Channels: Skype, Telegram, Facebook
* Deployment Environment: local development without emulator (real clients)

## Issue Description
I have a dialog where basically the bot asks the user if they abort a registration process. When the user responds that YES (aborts), the bot greets him and returns to the previous dialog by returning an object (of the registry type) null.
In this situation, the calling dialogue shows again the menu of options for the user to interact as it should be (all this well).
The behavior is correct in: Telegram, Skype and the Emulator but not in Facebook.
The trace shows the following error message:
Operation returned an invalid status code 'BadRequest'
**_THIS ONLY ON FACEBOOK_**
and the classic
Sorry, my bot code is having an issue

## Code Example
//children dialog
 [Serializable]
    public class Dialogo_NuevoTramite : DialogoBase<Tramite>
    {
.....stuff 

Tramite tramiteNull = null;

//this is the method
private async Task AfterPreguntaVinculacionAEntidad(IDialogContext context, IAwaitable<bool> result)
        {
            var reply = context.MakeMessage();
            var adjunta = await result;
            if (!adjunta)
            {
	//this is where the dialog returns a null object
                reply.Text = $"Muy bien, dejamos el tramite para otro momento";
                await context.PostAsync(reply);
                context.Done(tramiteNull); //<--HERE RETURN WITH NULL OBJECT
            }
            else
            {
	//forward another process
                context.UserData.RemoveValue(Constantes.Entidad);
                context.UserData.SetValue(Constantes.Entidad, entidad );

                var dlg = dialogFactory.Create<Dialogo_IngresoIdentificadorVincularEntidad>();
                context.Call(dlg, this.AfterDialogoIngresoIdentificadorVincularEntidad);

            }
        }

//================================
//father dialog

//here is where the son dialogue returns
private async Task AfterDialogoNuevoTramite(IDialogContext context, IAwaitable<Tramite> result)
        {
            var tramite = await result;
            string msg = tramite != null ? ($"La gestion ha sido registrada con exito con el Id #{tramite.id}. El codigo de referencia es: {tramite.codigo}. Dependiendo de la entidad le haremos saber de cualquier novedad o avance al respecto.") : "";
            await mostrarMenuPrincipalUsuarioRegistrado(context, msg); 
        }

## Reproduction Steps
nor how to show them

## Expected Behavior
The dialog should show the message
"Muy bien, dejamos el tramite para otro momento"
and show the main menu

## Actual Results
The message is displayed but then the classic appears
"Sorry, my bot code is having an issue"
and the trace say

<<Operation returned an invalid status code 'BadRequest' >>

**I do not know if it helps but in channels inside azure says**

{"error":{"message":"(#100) The parameter name_placeholder[text] is required","type":"OAuthException","code":100,"fbtrace_id":"CYJaSZ3KmC1"}}

**Comment by gfazzola** [comment]
Good morning.
Any news with the reported?
Thank you

**Comment by FranciscoPonceGomez** [comment]
Hi gfazzola,

Make sure that you have followed and completed all the steps in the documentation:
https://docs.microsoft.com/en-us/bot-framework/bot-service-channel-connect-facebook
or this video:
https://www.youtube.com/watch?v=igzx9Tn6-6I

If your bot works in other channels but not FB Messeger, there is a big chance that the configuration is incorrect. Looking at the error that you provided (bad request) I'd suggest you to double check the "enable webhook" step:
https://docs.microsoft.com/en-us/bot-framework/bot-service-channel-connect-facebook#enable-webhooks

Let me know if that works.

Regards,
Francisco

**Comment by gfazzola** [comment]
Hello Francisco.
The bot works on Facebook, in fact, we were approved by them and we are waiting for Skype to approve (this review is weeks ago) and finally to publish it.
The bot is being tested (with telegram, skype and facebook).
Everything was good ...
The problem occurs only with facebook and in the portion of the code that you publish (it is an option to return to the previous dialog)
We are not sure if it was from the update to the latest version of the framework or what happened because it is a simple return option.

Finally we emptied the table SqlBotDataEntities and we started again and everything started to work as before.
We do not understand what happened.

I hope it does not happen again.
Thank you

By the way, do you know how long the Skype revision process lasts ??

**Comment by FranciscoPonceGomez** [comment]
Hi gfazzola,

Can you share your bot ID with me so I can take a look at the revision status?

Regards,
Francisco

**Comment by gfazzola** [comment]
sure.

BotId: GestionaBOT


Thanks!!


Ing. en Sistemas Guillermo Fazzolari
[http://www.mtcsistemas.com/Imagenes/banderaArgentina.png]+54 9 298 458-2965
[http://www.mtcsistemas.com/Imagenes/banderaMexico.png]+52-33-84218750


________________________________

**Comment by FranciscoPonceGomez** [comment]
I got feedback for your bot from the review team.

"I have reviewed the bot. The following is the feedback. Please share it with the developer.
In bot profile page:
1.	No Bot avatar image with non-black and non-white background color.
2.	No Publisher name.
After adding it to skype contact page
1.	When a user adds the bot as a contact, the bot must automatically display a welcome message. This increases user engagement and guides the user to success. 
Once the developer have addressed these issues please ask her to resubmit the bot again for review."

I am going to close this issue. Feel free to reopen or open a new one if you continue having problems.

Regards,
Francisco

**Comment by gfazzola** [comment]
very good francisco, we will change them.


Ing. en Sistemas Guillermo Fazzolari
[http://www.mtcsistemas.com/Imagenes/banderaArgentina.png]+54 9 298 458-2965
[http://www.mtcsistemas.com/Imagenes/banderaMexico.png]+52-33-84218750


________________________________

**Comment by gfazzola** [comment]
Francisco
I reloaded the data inside azure (the bot was migrated a while ago) and we save it and it does not save the fields:

* The country or region of the editor (always says Afghanistan)
* The editor's email address (always appears in white)

I am almost one hundred percent sure that the rest of the fields (in their opportunity) we had put them also.

Anyway, I already put them but those that I put up are not updated.
Regarding the welcome message and avatar we will do it shortly


[cid:d9641db3-eb71-4b05-9f4b-23e5cfe6c087]


[cid:3bc088a9-c09c-4829-a71c-f14e2fae0c12]


Ing. en Sistemas Guillermo Fazzolari
[http://www.mtcsistemas.com/Imagenes/banderaArgentina.png]+54 9 298 458-2965
[http://www.mtcsistemas.com/Imagenes/banderaMexico.png]+52-33-84218750


________________________________

**Comment by gfazzola** [comment]
Hi francisco, good afternoon.
Yesterday we made the welcome greeting modifications for skype (which did not fire following the contosoflowers code and we found this help link

https://stackoverflow.com/questions/42943665/how-to-display-a-welcome-message-from-my-bot-using-microsoft-bot-framework
We modify the test and it seems that the welcome greeting is triggered correctly. (in the emulator, telegram and fb worked fine)

ok we did it, we uploaded the update and today when we were going to send everything to review again, we looked (again in azure) and yesterday's data were no longer (eg the website, publisher's name, email, etc)
How we put them back but hopefully they will be placed again.

regards



Ing. en Sistemas Guillermo Fazzolari
[http://www.mtcsistemas.com/Imagenes/banderaArgentina.png]+54 9 298 458-2965
[http://www.mtcsistemas.com/Imagenes/banderaMexico.png]+52-33-84218750


________________________________

**Comment by gfazzola** [comment]
Well finally we found the problem of the bug in facebook.
It is like that.
The code comes in the form

private async Task mostrarMenuPrincipalUsuarioRegistrado(IDialogContext context, string titulo = "")
{
            var reply = context.MakeMessage();
            var opciones = new List<string>() { Cadenas.CMD_NUEVO_TRAMITE, Cadenas.CMD_MIS_TRAMITES };
            var descripciones = new List<string>() { Cadenas.CMD_NUEVO_TRAMITE, Cadenas.CMD_MIS_TRAMITES };
...
...

            reply.AddHeroCard(titulo, opciones, descripciones);
            await context.PostAsync(reply);
}

and the titulo variable, when it is called with the default value (a blank string) produces the error ONLY ON FACEBOOK
