### ISSUE TITLE
[Node.js SDK, FB Messenger] Checkbox Plugin support?

### ISSUE THREAD

**Issue by gilLionKing** [Microsoft/BotBuilder#4199]
## Bot Info
* SDK Platform:  Node.js 
* SDK Version: Latest
* Active Channels:  Facebook

Hello!
I'm adding Facebook Checkbox Plugin, and I have a trouble with getting opt-in callback -
I couldnt find any support for this in the botbuilder so i hooked up my own endpoint for the webook event looking like that : 
app.post('/webhook', function (req, res) {

so now for regular user messages the botbuilder endpoint is responding and for optins my webhook is responding. now i would like to use the botbuilder to send a proactive message but i dont have the session variable. what i have is the refid which is used to send messages in the checkbox plugin

how can i do send a message in this situation with the bot builder ? thank you.

**Comment by JasonSowers** [comment]
I'm a little confused by what exactly you are asking.  Are you asking how to send a proactive message?  please provide a code example and clarify your question.

**Comment by gilLionKing** [comment]
Hi im asking 2 things. 
1) is there any support within the botbuilder to recieve the optin event ? 
2)if not and im using my own webhook like in the following example
this endpoint is receivng the optin event from fb
app.post('/webhook', function (req, res) { }
im asking if i can then use the botbuilder the send a proactive message ?
currently now im posting to fb user the recieved refid to send the user a proactive message like in the example below but i would like to use the bot builder if possible 
unction sendOpeningMessage(refId) {
    var request = require('request');
    var message =  "welcome";
        var myJSONObject =  {"messaging_type": "UPDATE",
            "recipient": {
                "user_ref":refId
            },
            "message": {
                "text": message
            }};

    request({
        url: "https://graph.facebook.com/v2.6/me/messages?access_token=blabla",
        method: "POST",
        json: true,
        body: myJSONObject
    }, function (error, response, body){
        console.log(response);
  
    });
}

**Comment by iMicknl** [comment]
Yes, it should be possible. I wrote a blogpost about it last year, [How to process Facebook Messenger callbacks using the Microsoft Bot Framework
](https://imick.nl/how-to-handle-referrals-optins-postbacks-on-facebook-using-microsoft-bot-framework/). It doesn't work for the Checkbox plugin yet, as you receive a `user_ref` instead of a `user id`.

The code of the Facebook middleware I wrote can be found here; https://github.com/iMicknl/BotBuilder-FacebookExtension. You can use it to catch the optins, however you have to write a function that sends the first message with the `user_ref`.

**Comment by gilLionKing** [comment]
hi  @iMicknl, could you elaborate how to add support for this ? im not even seeing the event coming in through my webhook ngrok gateway so im wondering if its even supported on the microsoft end to pass down the optin event. thanks for the help

**Comment by EricDahlvang** [comment]
We are tracking Facebook feature requests here: https://github.com/Microsoft/BotBuilder/issues/4360 I've added this to that issue, so closing this one.
