### ISSUE TITLE
[Request] BuildBot Sample

### ISSUE THREAD

**Issue by medouederni** [Microsoft/BotBuilder#42]
Are you planning to open source the //build bot ?

**Comment by chrimc62** [comment]
I'll check with the people that created that and let you know.

**Comment by we-CONECT-Joe** [comment]
I would also be interested in the BuildBot sources. It's a more lifelike example =)

**Comment by larsontim** [comment]
I would also be interested in the BuildBot Source and the source for the emulator.

**Comment by Stevenic** [comment]
Moved to UserVoice:

https://feedback.botframework.com/forums/354213-general/suggestions/13463463--request-buildbot-sample
