### ISSUE TITLE
Bot profile pictures aren't uploading

### ISSUE THREAD

**Issue by sohanmaheshwar** [Microsoft/BotBuilder#420]
Hello

Tried creating a Skype bot and for some reason the Bot images aren't uploading.
I tried an image that was exactly 150x150 and under 30kb and a PNG (see image) but got an error. 
Tried another 150x150 image that was > 1 kb and even that didn't work. 

I'm using Google Chrome on El Capitan. 
![screen shot 2016-06-03 at 9 51 28 am](https://cloud.githubusercontent.com/assets/1119120/15782612/a95d89d6-29c8-11e6-906c-d984f6afa261.png)
![screen shot 2016-06-03 at 9 51 38 am](https://cloud.githubusercontent.com/assets/1119120/15782611/a9522078-29c8-11e6-82dd-9f0b03c25411.png)

Not sure if I was doing something wrong. The MS dev twitter handle asked me to post here so I did :)
Thanks!

**Comment by lukkhacoder** [comment]
Have you tried the solution mentioned here: http://stackoverflow.com/questions/37041854/keep-getting-message-bot-profile-pictures-should-be-png-and-less-than-30kb-whi

**Comment by chrimc62** [comment]
Closing this issue.  If you still have it after trying the previous, please reopen.

**Comment by nickcordrey** [comment]
A bug was found which causes this issue and is being fixed.
