### ISSUE TITLE
Bot throwing error System.ArgumentNullException: 'Value cannot be null. Parameter name: connectionString'

### ISSUE THREAD

**Issue by ssachdeva10** [Microsoft/BotBuilder#4202]
## Bot Info
* SDK Platform: .NET 
* SDK Version: 
* Active Channels: 
* Deployment Environment:  local development with Emulator

## Issue Description
While trying the local development getting System.ArgumentNullException: 'Value cannot be null.
Parameter name: connectionString'

## Code Example
Global.asax -> Application_start
var store = new TableBotDataStore(ConfigurationManager.AppSettings["AzureWebJobsStorage"]);
Key 'AzureWebJobsStorage' is not present in config but is available on the portal, shall I add this manually.

## Reproduction Steps
1.
2.
3.

**Comment by EricDahlvang** [comment]
Yes, this should be added to your web.config.  Bots created in Azure have this setting in App settings during the creation process.

**Comment by simra** [comment]
What is the recommended best practice to make this setting available locally but not commit it to a source repo?

**Comment by EricDahlvang** [comment]
HI @simra 

You are asking a question on a closed issue.  The Bot Builder GitHub repository is for issues and feature requests. 

There is some guidance for storing secrets here: 
https://docs.microsoft.com/en-us/azure/key-vault/vs-secure-secret-appsettings
and 
https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?tabs=windows&view=aspnetcore-2.1

**Comment by simra** [comment]
That's a fair criticism but your second answer is a lot safer than the original suggestion. :) Thanks for the pointers.

**Comment by mayankiitg** [comment]
For local testing we can use local azure storage emulator by putting this value in appSettings in web.config

<add key="AzureWebJobsStorage" value="UseDevelopmentStorage=true" />
