### ISSUE TITLE
[Question] Is it possible to Host and run your Bot build with microsoft Botbuilder sdk without registering it on Azure?

### ISSUE THREAD

**Issue by SATACHAKRA** [Microsoft/BotBuilder#4204]
Bot Info:
 .NET  
-- locally deployed-- on Visual Studio IIS express server.

Want to host my bot without registering it on Azure. Are there any templates for such a chatbot UI?
I have been using the Bot Emulator But I want to embed my chatbot ui onto a website and then handle the corresponding conversation from a C# code written locally on my system.
Actually I am using RASA for entity and intent extraction..

**Comment by SATACHAKRA** [comment]
Well I simply don't want to register it with microsoft becoz i dont have a credit card to register with onan azure account.

I have tested it on the emulator and it works fine. nOw i want to embed it onto a website.

**Comment by EricDahlvang** [comment]
Using the Microsoft Bot Framework without registering a bot on Azure is not a supported scenario.  The Emulator provides this functionality locally, for the sake of development (it "emulates" a channel). 

Nonetheless, there are some "offline" strategies the community has put together such as: https://www.npmjs.com/package/offline-directline However, this package has limits:

> NOTE: Not all routes (e.g. attachments) are fully implemented in this package. For now this connector functions as a message broker and state store. Further, this package currently facilitates a single conversation between a user and a bot.

I recommend the path with the most features and reliability is a bot hosted on Azure, using the Bot Services Azure provides.
