### ISSUE TITLE
Hoek security vulnerability via jsonwebtoken package

### ISSUE THREAD

**Issue by benswinburne** [Microsoft/BotBuilder#4206]
## Bot Info
* SDK Platform: Nodejs
* SDK Version: 3.14.0

## Issue Description
Using NSP, (https://nodesecurity.io, https://github.com/nodesecurity/nsp) there's a security advisory which recommends installing botbuilder 4.0.0-alpha2 in order to resolve this.

Is it possible for you to release a 3.x version which updates jsonwebtoken to a version where this vulnerability does not exist. I have installed jsonwebtoken 8.1.1 independently which isn't subject to the same advisory, but obviously that's a major version.

I've not tried any of the 7.x releases as yet. If this is something worth looking at I can try and find a version to update to in the 7.x releases instead of 8.x.

    566 - Prototype pollution attack
    Vulnerable: <= 4.2.0 || >= 5.0.0 < 5.0.3 - Patched: > 4.2.0 < 5.0.0 || >= 5.0.3 - Path: 
    botbuilder@3.14.0 > jsonwebtoken@7.4.3 > joi@6.10.1 > hoek@2.16.3

    How to fix
    Update your package's dependency of botbuilder to at least version 4.0.0-alpha2

    Install botbuilder and nsp then run `nsp check`

**Comment by FranciscoPonceGomez** [comment]
Hi benswinburne,

I don't think we are vulnerable to this threat but we will upgrade soon.

Regards,
Francisco
