### ISSUE TITLE
[Issue] Activity Id is null when creating one from CreateReply()

### ISSUE THREAD

**Issue by ilanopat** [Microsoft/BotBuilder#4208]
## Bot Info
* SDK Platform: .NET 
* SDK Version: 3.13
* Active Channels: MS Teams
* Deployment Environment: local development sideloading to MS Teams with tunneling to ngrok

## Issue Description
I made a proactive bot which messages a particular user an attachment with ThumbnailCard. So I did a CreateReply from activity parameter from a ConversationUpdate trigger. I notice that the new Activity which was created as a reply to the previous activity from the trigger has null Id.

## Code Example
Activity reply = activity.CreateReply();

## Expected Behavior
It should have its own Id.

## Actual Results
![image](https://user-images.githubusercontent.com/12206702/36407627-df122d60-163a-11e8-8fe6-28bf361c2aa8.png)

**Comment by JasonSowers** [comment]
What do you need the `Id` fields for? is there a reason you cannot just generate your own Id property such as
 ```cs
            var reply = activity.CreateReply();
            reply.Id = "12345678";
```

**Comment by ilanopat** [comment]
I need it to do an update on that activity. I should store it in the bot custom state and access it for triggering an update of the activity externally. However I kinda resolved this issue, I'm storing the returned ID of the ReplyToActivityAsync, like this

`var resourceResponse = await connector.Conversations.ReplyToActivityAsync(reply);
user.ActivityId = resourceResponse.Id;
await AccountController.Instance.SaveUser(user);`

and updating externally, like

`string activityId = await AccountController.Instance.GetActivityId(conversationReference.User.Id);
await client.Conversations.UpdateActivityAsync(conversationReference.Conversation.Id, activityId, message, CancellationToken.None);`

I wonder if this is the correct way? As the Activity doesn't have an ID, I'm using the ResourceResponse.Id in which I can access and update the previous Activity. Are they the same ID?

**Comment by JasonSowers** [comment]
I do not see any issues with generating an ID this way.  It is in line with the way I was suggested.

**Comment by ilanopat** [comment]
Okay, I didn't generate ID, I found out that the ResourceResponse which is the return type of ReplyToActivityAsync has ID attribute inside it, so I just stored it and it works when I retrieved and used it as an Activity ID.

**Comment by JasonSowers** [comment]
Doing this or generating one on your own would both be reasonable ways, Good luck.
