### ISSUE TITLE
Bing Channel - Submission In Review for Months

### ISSUE THREAD

**Issue by muhammedyusuf-sermet** [Microsoft/BotBuilder#4209]
## Bot Info
* SDK Platform:  Node.js
* SDK Version:  Latest
* Active Channels:  Bing, Slack, Skype, Messenger, Email, Cortana
* Deployment Environment:  Azure Bot Service

## Issue Description

I submitted my bot for Bing channel through Bot Framework website. However, after about 2 months, it still says InReview under the "Published" column. In the documentation, it says I should expect an answer after a few business days.

I haven't received any kind of confirmation e-mail since I submitted for review.

The website does not allow me to submit for publishing again. The button is faded out.

Is the 2 months of waiting time normal? If not, how can fix this issue?

Thanks.

## Code Example

No code involved for this issue.

## Actual Results

![image](https://user-images.githubusercontent.com/14010967/36410465-bbe02bd0-15d6-11e8-91d7-6a4f3fd68d97.png)

**Comment by FranciscoPonceGomez** [comment]
Good afternoon.

Could you please provide your App Id?

Regards,
Francisco

**Comment by muhammedyusuf-sermet** [comment]
Francisco, thank you for following up. Here is my App ID:

22bf42ae-86d0-45c1-8f6d-570bc2afa149

Thanks,
Yusuf

**Comment by FranciscoPonceGomez** [comment]
Hi muhammedyusuf-sermet,

Bing team is currently reviewing your bot. You can expect an answer soon.
I am going to close this issue. Feel free to reopen if necessary.

Francisco

**Comment by FranciscoPonceGomez** [comment]
Seems that your bot is not working properly / unresponsive.
![image](https://user-images.githubusercontent.com/16775093/36925273-f07d85c4-1e26-11e8-8061-79bee7c4d706.png)

**Comment by muhammedyusuf-sermet** [comment]
I reviewed what caused that issue on Bing, and found out that it is about my organization's Azure subscription. We fixed it now. Thank you for the feedback.

Yusuf
