### ISSUE TITLE
No way to get to PDF content attached to a message on Slack

### ISSUE THREAD

**Issue by lukkhacoder** [Microsoft/BotBuilder#421]
I'm using the following code to send back a PDF file as an attachment to a message. On Slack I see the name of the file, but there is no way to download it. Note that on Skype I do see an option to download the file.  
**Code**
![image](https://cloud.githubusercontent.com/assets/13338812/15788899/7e611aa8-297e-11e6-888e-07c93553a394.png)

**Message on Slack**
![image](https://cloud.githubusercontent.com/assets/13338812/15788942/ae338d56-297e-11e6-81c2-b50bcc89aa0a.png)

**Message on Skype**
![image](https://cloud.githubusercontent.com/assets/13338812/15788953/c48559f4-297e-11e6-8031-ea0250660a70.png)

**Comment by lukkhacoder** [comment]
Any ideas or workarounds?

**Comment by craigjensen** [comment]
Try setting the TitleLink property to the same link as ContentUrl.

**Comment by Ma3yTa** [comment]
@lukkhacoder Does application/pdf works for you in Skype? I used the same code but got ``Unknown attachment type`` error

**Comment by Ma3yTa** [comment]
@craigjensen Is sending of files supported by Bot Builder? Thanks
