### ISSUE TITLE
Testing bot via WebChat

### ISSUE THREAD

**Issue by pchilappagari** [Microsoft/BotBuilder#4212]
## Bot Info
* SDK Platform: Node.js
* Active Channels: Web Chat
* Deployment Environment: Azure Bot Service
## Issue Description

I registered a simple chat bot on Azure. The bot is running on one of our local servers which has a public facing NAT. I have the server listening on port 3978 but when I test this out in WebChat, it says message couldn't be sent to the bot.

Here's messaging endpoint URL I specified on Azure : 

https://X.X.X.X:3978/api/messages (X.X.X.X is the IP that's publicly accessible )

## Code Example

```javascript
var restify = require('restify');
var builder = require('botbuilder');
var https = require('https');
var httpsOptions = {
key: fs.readFileSync('key.pem'),   //Self-generated 
cert:fs.readFileSync('key.cert')
}
server.listen(process.env.port||3978, 'x.x.x.x',  function () {   //x.x.x.x is the private IP of the server
   console.log('%s listening to %s', server.name, server.url); 
});

// Create chat connector for communicating with the Bot Framework Service
var connector = new builder.ChatConnector({
    appId : "msappid",  //app id and password generated during bot registration on Azure
    appPassword:"mspasswd"
});

// Listen for messages from users 
server.post('/api/messages', connector.listen());

// Receive messages from the user and respond by echoing each message back (prefixed with 'You said:')
var bot = new builder.UniversalBot(connector, function (session) {
    console.log(session.message.text);
    session.send("You said: %s", session.message.text);
});
```
## Reproduction Steps
1. Run node test.js on server
2. Test in Web Chat by typing any text

## Expected Behavior
Expect to see "You said : hi" in Web Chat window

## Actual Results
Couldn't send;
From the logs: 
There was an error sending this message to your bot.

There's no error code or explanation as to why it failed. A couple of questions : 

Is port 3978 necessary once we deploy the bot?
Is the messaging endpoint format correct? Do we need to specify the port and /api/messages suffix
Do we need to specify the server's IP  address in server.listen() call?

**Comment by microsoftly** [comment]
@pchilappagari While not directly an answer to your question, I made a package that can programatically test your bot. To narrow the possible error source to the infrastructure vs your bot, you can make some unit/integration tests with the test library. Lmk if you need any help or new features, I'm happily extending functionality to cover more use cases.

You can find out more here -> https://github.com/microsoftly/BotTester

**Comment by FranciscoPonceGomez** [comment]
Hi pchilappagari,

You don't need to specify the port in your endpoint. I am not sure if you have to have in the code. I will verify this.

The Bot Framework also requires that the x.509v3 certificate exposed by your endpoint be current and valid. Most of the checks for "current and valid" are standard checks for server certs: the CN must match the hostname, it must not be expired, it must not be listed in a CRL, it must have the correct set of EKUs, etc.

Most importantly, your cert must chain to a root certificate authority trusted by Microsoft. The latest list of these CAs is available here: http://social.technet.microsoft.com/wiki/contents/articles/31634.microsoft-trusted-root-certificate-program-participants-v-2016-april.aspx

For more information on deploying your bot, see: https://docs.microsoft.com/en-us/bot-framework/deploy-bot-overview

https://stackoverflow.com/questions/40888489/bot-framework-without-azure-possible
https://stackoverflow.com/questions/44558760/deploy-bot-in-local-iis-and-incle-it-in-custom-chat-in-a-webpage/44571251#44571251
