### ISSUE TITLE
Skype Bot Stuck InReview?

### ISSUE THREAD

**Issue by deybhayden** [Microsoft/BotBuilder#4213]
Bot Info
SDK Platform: REST
Active Channels: Skype, Cortana
Deployment Environment: AWS
Microsoft App Id: 19ef44c9-500e-4d35-9480-c64c576e2150
Bot Handle: StatMuse

Issue Description
My bot is in Review, just checking if there's any more information available.

**Comment by JasonSowers** [comment]
They gave the following feedback:
1.	There was no bot description in the profile page of the bot.
2.	There was no developer name on the profile page under bot icon.
3.	There was no auto welcome message to greet the user after adding to the contacts.
Please change these things and resubmit

**Comment by deybhayden** [comment]
Great, thanks!

For 1 & 2 - Is that done via the Azure Bot Framework Channel screen? I've set those both several times but they never seem to stick.

For 3, is there a certain event type that I need to be listening for that? My skill does have a launch greeting, but just need to know when to send it.

**Comment by JasonSowers** [comment]
Yes, 1 and 2 should be in the Azure portal on the publish page, maybe try deleting and adding back the skype channel?  Number 3 I'm not exactly sure, but most likely it's because in skype you do not see the `ConversationUpdate` you see the `ContactRelationUpdate` activity so you need to send your welcome message when that event is received.

**Comment by deybhayden** [comment]
Awesome, I appreciate it 💯

**Comment by deybhayden** [comment]
@JasonSowers I've made the requested changes and have resubmitted - mind to work your magic again and forward to the Skype team? I'd really appreciate it!

**Comment by AkshayKanchan** [comment]
Hi, typically how much time a chatbot for Skype should take to get reviewed and release? I have submitted a chatbot to Skype for review it's been a week, the bot is still "inReview" and I haven't received any emails from Skype yet. Also the same case with Bing channel

Chatbot Info
Microsoft App ID : 77471931-f49d-4501-8755-3ca5fbffc08e
Submitted For Review : Skype, Bing.
Deployment Environment : Azure Bot Service.
