### ISSUE TITLE
Kik Bot Suddenly Stopped Working

### ISSUE THREAD

**Issue by Victini33** [Microsoft/BotBuilder#4217]
As of a yesterday, the Geeking Roleplay bot on Kik suddenly stopped working for me. Normally, the bot is suppose to send you a response and allow you to choose what you want to do (ex. Change bio or topics, etc.), but it stopped doing that all of a sudden. I can send it messages, but it never responds to them, even though it says that the messages were indeed read by the bot. The others botd are working just fine for me except for that one, so I’d really like to know what wrong with that specific bot.

**Comment by craterfalls** [comment]
As of a yesterday, the Geeking Roleplay bot on Kik suddenly stopped working for me. Normally, the bot is suppose to send you a response and allow you to choose what you want to do (ex. Change bio or topics, etc.), but it stopped doing that all of a sudden. I can send it messages, but it never responds to them, even though it says that the messages were indeed read by the bot. The others botd are working just fine for me except for that one, so I’d really like to know what wrong with that specific bot.
SAME HERE

**Comment by JasonSowers** [comment]
Can you share your code so we can reproduce the error please.
