### ISSUE TITLE
Language resources German, several issues

### ISSUE THREAD

**Issue by bashdx** [Microsoft/BotBuilder#4219]
## Bot Info
* SDK Platform: .NET
* SDK Version: Current
* Active Channels: Teams
* Deployment Environment: Azure App Service

## Issue Description

While playing with the Bot SDK I found some translation issues in the `FormBuilder`:

When calling the help dialog via `FormCommand`:

- In "You are filling in field {XYZ]..." there are several issues:
    - Polite "you" should be employed ("Sie") instead of "Du"
    - The referenced field is spelled in lower case, no matter what. German nouns start with a capital letter.
- Overall usage of polite "you" -> using "Sie" instead of "Du" and adapting conjugation of verbs
- In "You can select another field ..." there are also several issues:
    - "Sie" instead of "Du"
    - before "indem" there must be a comma
    - "oder" must not be prepended by a comma

## Expected Behavior

- "Sie befüllen das Feld _XYZ_. Mögliche Antworten: "
- "Sie können alles eingeben (Verwenden Sie '', um eine Zeichenfolge zu erzwingen)."
- "Sie können zu einem anderen Feld wechseln, indem Sie dessen Namen eingeben (_ABC_, _DEF_ oder _GHI_)." -> please see punctuation here 

## Actual Results

![image](https://user-images.githubusercontent.com/28575699/36560600-78a03c06-1811-11e8-831e-2c86829a0e83.png)

**Comment by JasonSowers** [comment]
Please submit a pull request with your proposed fixes

**Comment by bashdx** [comment]
Thank you for your reply, I submitted a pull request, #4232.
Please contact me if there are any issues.

Regards

**Comment by fanidamj** [comment]
Closing the issue assuming it as resolved. Please reopen a new issue if it still persists.
