### ISSUE TITLE
[LUIS AI] endpoint hits not updating in luis.ai dashboard in order to verify & test logging of LUIS AI API calls

### ISSUE THREAD

**Issue by MohammedAbdulMateen** [Microsoft/BotBuilder#4223]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.13.1
* Active Channels: Skype, Skype for Business, MS Teams, Slack, Direct Line, Web Chat (The production app contains all these channels)
* Deployment Environment: Azure Bot Service, Azure App Service, also local development and testing with Emulator and ngrok

## Issue Description
I want to log the calls to LUIS API to track each end-user usage (I can distinguish each user by their customer account details), so I created a new test bot, test LUIS app and wrote logging statements using log4net in all the methods having the `[LuisIntent]` attribute, but in the LUIS AI dashboard I don't see any endpoint hits getting updated, I've been testing for more than an hour, also I see a new issue in LUIS AI website i.e. if we add a new app and add a new intent and add utterances to it and then go to dashboard there are console errors saying source data is missing from a component.

One thing I noticed in another LUIS app is that it is showing the endpoint hits but they aren't updating right away (real-time) also I am confused whether the endpoint hits are of production or stage or both summed up and does each hit to a `[LuisIntent]` method count as one endpoint hit in luis ai?

I want to make sure the statements that are logging the hits for each user inside the `[LuisIntent]` methods are accurate and match the endpoint hits count (LUIS API calls) exactly.

Please provide your suggestions.

## Reproduction Steps
1. Create a new bot application, update all nuget packages
2. Create a new LUIS AI app
3. Add some intents and utterances or train the default None intent, train and publish
4. Configure LuisModel Dialog, now write logging statements in `[LuisIntent]` methods to count the calls/hits for each user
5. Now send some messages to the bot using emulator
6. Now go to dashboard in LUIS AI website for that LUIS app we created earlier
7. No endpoint hits are shown or updated after a long time too
8. The same behavior happens with LUIS app using paid Azure subscription but that one got updated at least twice in dashboard and then stopped updating

## Expected Behavior
The endpoint hits should be shown in the dashboard and also the logging statements should suffice to match the endpoint hits count accurately

## Actual Results
The endpoint hits are not getting updating even after 1 - 2 hours of testing

**Comment by fanidamj** [comment]
It takes couple of days for the dashboard to be updated. And also the endpoint hits are the hits per app not based on each end-user usage as described [here](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/app-dashboard). If you are using specific [resource key ](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/manage-keys)from Azure you can track the resource usage from the metrics in Azure portal. There are chances of using the same Azure resource for multiple apps, in that case it counts all the hits from the apps it is being used. 
Regarding the console error while creating the app, can you please share us the screen shot and .HAR file from the chrome developer console to Luisuservoice@microsoft.com so that can investigate further.

**Comment by MohammedAbdulMateen** [comment]
@fanidamj @JasonSowers 

Could you please re-open this issue, when will the metrics in Azure portal be updated, they too don't seem to show data real-time.

I have come across a challenge, before user logs in or authenticates I can't log messages against that user, so first I would like to know whether the call to MessageReceived (overridden in root LuisDialog) is treated as a LUIS endpoint hit (either querying or authoring request) or not?.

Will it use LUIS endpoint hits even if a [LuisIntent] method is called manually (method invocation) from the overridden MessageReceived or when dialog forwarding is done to an IDialog or another LuisDialog?

Could you please provide an in-detail explanation in which scenarios a call is considered as LUIS endpoint hit in code C#.

**Comment by EricDahlvang** [comment]
Yes, calls to **ILuisService.QueryAsync()** are counted as a LUIS endpoint hit (see here: https://github.com/Microsoft/BotBuilder/blob/c431088029265cbf1f3edd1537fbf17d8aeb3dab/CSharp/Library/Microsoft.Bot.Builder/Dialogs/LuisDialog.cs#L215 ).  Authoring calls are not counted as endpoint hits, just queries.  Manually calling a method with the LuisIntent attribute will not count as a hit because no call is made to the LUIS service: **ILuisService.QueryAsync()**

You can track hits yourself by simply overriding the LuisDialog's MessageReceived.  Each ILuisService will be called once, so something like:

```
    public class HitCountLuisDialog : LuisDialog<object>
    {
        static int _luisHits = 0;
        static object _lockObject = new object();

        protected override Task MessageReceived(IDialogContext context, IAwaitable<IMessageActivity> item)
        {
            var totalHits = services.Count();
            lock (_lockObject)            
                _luisHits += totalHits;
            
            return base.MessageReceived(context, item);
        }
    }
```

**Comment by MohammedAbdulMateen** [comment]
@EricDahlvang thanks a lot for letting me know that ILuisService.QueryAsync calls are counted as LUIS endpoint hit (very useful point as we are using factory pattern for finding the best dialog)

I have a few questions on which I need clarification,

1. As per my understanding the hit to `MessageReceived` isn't counted as a LUIS endpoint hit strictly until unless `base.MessageReceived` is called, am I right about this point?
2. We are having RootDialog and multiple dialogs, in azure metrics I see 2 calls when dialog forwarding happens, i.e. in the following manner

Let's say the intent handler method matching the query is in SettingsDialog,

Start --> RootDialog --> MessageReceived --> base.MessageReceived (1 call) --> None intent method (factory pattern) --> context.Forward(SettingsDialog) --> MessageReceived --> base.MessageReceived (1 call) --> corresponding intent method --> done

is this the expected behavior, does `base.MessageReceived` internally call `ILuisService.QueryAsync`?

Looking for alternatives on the below challenge, i.e. lot of LUIS calls,

1. A call that is involving dialog forwarding from RootDialog (as explained in point 2) seems to cost 4 LUIS endpoint hits due to factory pattern if we are having 2 dialogs apart from the RootDialog.
2. When the control is in a child/specific dialog a call to RootDialog's intent method may involve 5 LUIS endpoint hits

A simple solution would be to use only one LUIS app so only 1 LUIS endpoint hit will happen each time, but we are having a lot of platform integrations to be done which is preventing us from going with single LUIS app.

Another way could be to switch platforms (using scorable) during runtime by asking the user to choose the platform against which they would like to query by having the RootDialog be of type IDialog, this could be undesirable considering from the user's perspective or it could be a good solution too.

So, is it possible to have only one bot application but internally behave as if there are multiple bots each for one platform so that only 1 LUIS call happens for each user query?

I am open to try different solutions, could you please share your thoughts and suggestions.

Thanks in advance.

**Comment by EricDahlvang** [comment]
1. As per my understanding the hit to MessageReceived isn't counted as a LUIS endpoint hit strictly until unless base.MessageReceived is called, am I right about this point?

	Yes.  LUIS is not called until LuisDialog calls s.QueryAsync
	
	You can review the code for LuisDialog here: https://github.com/Microsoft/BotBuilder/blob/c431088029265cbf1f3edd1537fbf17d8aeb3dab/CSharp/Library/Microsoft.Bot.Builder/Dialogs/LuisDialog.cs#L141

2. We are having RootDialog and multiple dialogs, in azure metrics I see 2 calls when dialog forwarding happens, i.e. in the following manner: is this the expected behavior, does base.MessageReceived internally call ILuisService.QueryAsync?

	If RootDialog and SettingsDialog inherit from LuisDialog, then yes this is the expected behavior (please review the code for LuisDialog)
	
3) So, is it possible to have only one bot application but internally behave as if there are multiple bots each for one platform so that only 1 LUIS call happens for each user query?

	I'm not sure I have enough details about your specific application to answer this question.  I'm not sure what you mean by "platform".  However, you should be able to modify your application in such a way that "only one LUIS call happens for each user query".
	
	
If you'd like to know more details about how the internals of LuisDialog functions, you can always download the source and reference it instead of the nuget packages, then step through the code as you debug locally.

**Comment by MohammedAbdulMateen** [comment]
@EricDahlvang thanks a lot for the information, by platform I mean we have to integrate other 3rd party systems and some of them could be very large systems/software. If we say a 3rd system integration as "platform" for simplicity, each platform is having its own LuisDialog class instance and there will also be a RootDialog which is responsible for finding the best matching dialog and the corresponding intent method using the factory pattern (search through all dialogs & all intents to the find best matching dialog and the intent method), besides this... each platform is having it's own LUIS app in luis.ai and RootDialog also has it's own LUIS app for handling general messages.

This is the design we are following for our application, because we don't want to run into the limit of 80 intents in luis.ai as in future the platforms may increase rapidly, I hope this gives you an insight into the application, if you need more details please let me know.

This design seems complex if thought from the perspective of LUIS endpoint hits, but coding wise it is simpler, in such a case how can I modify the application such that "only one LUIS call happens for each user query", do you have idea or solution that could help

**Comment by EricDahlvang** [comment]
The limit for intents is now 500: 
https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-boundaries

**Comment by MohammedAbdulMateen** [comment]
@EricDahlvang @fanidamj thanks for your support, I've merged all the LUIS apps into a single LUIS app now it is easy to log LUIS API calls at just one place i.e. in the overridden `MessageReceived` method in the `LuisDialog` instance. 500 intents is amazing, keep up the good work, wish the entities count was also increased more.

Also, as the luis.ai dashboard update takes time, I see the metrics in Azure for the LUIS subscription key (Cognitive Services) are updating right away almost real-time but sometimes requires to hit the refresh button.

Thanks

**Comment by EricDahlvang** [comment]
@MohammedAbdulMateen Thank you for coming back to share the solution!
