### ISSUE TITLE
How to come out from FormFlow dialog & to go to multiple QnaMaker dialog services 

### ISSUE THREAD

**Issue by rupjit** [Microsoft/BotBuilder#4226]
## Bot Info
* SDK Platform: .NET
* Active Channels:  Direct Line

## Issue Description
How to come out from FormFlow dialog & to go to QnaMaker dialog.

## Code Example
======================================================
**Message Controller:**
=======================================================   
        public async  Task<HttpResponseMessage> Post([FromBody]Activity activity)
        {
       
              if (activity !=null && activity.GetActivityType() == ActivityTypes.Message)
                {

                   switch (activity.Text)
                    {
                        case "A":
                            await Conversation.SendAsync(activity, () => new Dialogs.BitsyQnAMakerDialogA());
                            break;
                        case "B":
                            await Conversation.SendAsync(activity, () => new Dialogs.BitsyQnAMakerDialogB());
                            break;
                        case "C":  
                            await Conversation.SendAsync(activity, () => new 
                                                                                                       Dialogs.BitsyQnAMakerDialogC());
                            break;
                        case "D":
                            await Conversation.SendAsync(activity, () => new Dialogs.BitsyQnAMakerDialogD());
                            break;
                        default:
                     await Conversation.SendAsync(activity, () => { return Chain.From(() => 
                    FormDialog.FromForm(DomainSelectionForm.BuildForm)); });
                              
                            break;
                    }
   
                 }
                else
                {
                    HandleSystemMessage(activity);
                }

                var response = Request.CreateResponse(HttpStatusCode.OK);
                return response;
              }
==========================================
**DomainSelectionForm**
==========================================
[Serializable]
    public class DomainSelectionForm
    {
        public DomainTypes domainType;
     
        public static IForm<DomainSelectionForm> BuildForm()
        {

        return new FormBuilder<DomainSelectionForm>().AddRemainingFields().OnCompletion(async (context, profileForm) =>
             {
                 
           //     throw new System.ApplicationException("Welcome To FAQ Bot Service");

             }).Build();
        }
    }

    [Serializable]
    public enum DomainTypes
    {
               A= 1,B= 2,C= 3,D= 4
    }

=================================

## Expected Behavior

1. User says HI
2. Switch Case default : will hit
3. I Show a form A | B | C | D using BuildForm()
4. User Select A , I take him to Qna Maker A , Next time user type anything it goes to Qna Maker A only. 
same for B, C ,D

## Actual Results

1. I am unable to come out from the formflow stack.
2. Work around ,   Above works only , only if i deliberately throw an exception inside formflow completion .Once exception thrown & then i select A ,it takes me to Qna Maker A , Next time i type anything it goes to Qna Maker A only.

Dear Experts kindly help, i am new to formflow & dialogs

**Comment by EricDahlvang** [comment]
Hi @rupjit 

There are a few ways to accomplish this.  Fortunately, the bot builder sdk manages the dialog stack for you.  The simplest way to take advantage of this is to have a RootDialog that contains the branching logic.  Something like:

```cs
[Serializable]
public class RootDialog : IDialog<object>
{
    public async Task StartAsync(IDialogContext context)
    {
        context.Wait(this.MessageReceivedAsync);
    }

    public virtual async Task MessageReceivedAsync(IDialogContext context, IAwaitable<IMessageActivity> result)
    {
        var activity = await result;
        var reply = context.MakeMessage();

        string qnaMakerSelection = null;
        if (context.ConversationData.TryGetValue("QnAMakerOption", out qnaMakerSelection))
        {
            DomainTypes selection = (DomainTypes)Enum.Parse(typeof(DomainTypes), qnaMakerSelection);
            switch (selection)
            {
                case DomainTypes.Domain1:
                    await context.Forward(new BitsyQnAMakerDialogA(), AfterQnAMakerDialog, activity);
                    break;
                case DomainTypes.Domain2:
                    await context.Forward(new BitsyQnAMakerDialogB(), AfterQnAMakerDialog, activity);
                    break;
                case DomainTypes.Domain3:
                    await context.Forward(new BitsyQnAMakerDialogC(), AfterQnAMakerDialog, activity);
                    break;
                case DomainTypes.Domain4:
                    await context.Forward(new BitsyQnAMakerDialogD(), AfterQnAMakerDialog, activity);
                    break;
            }
        }
        else
        {
            await context.Forward(FormDialog.FromForm(DomainSelectionForm.BuildForm), AfterDomainSelection, activity);
        }
    }

    private async Task AfterQnAMakerDialog(IDialogContext context, IAwaitable<object> result)
    {
        await context.PostAsync("QnAMakerDialog closed");
    }

    private async Task AfterDomainSelection(IDialogContext context, IAwaitable<object> result)
    {
        string qnaMakerSelection = null;
        if (context.ConversationData.TryGetValue("QnAMakerOption", out qnaMakerSelection))
        {
            await context.PostAsync($"Future requests will be routed to QnAMakerDialog {qnaMakerSelection}");
        }
    }
}
```

The MessageReceivedAsync method checks for a "QnAMakerOption" in ConversationData and uses that value to determine which QnAMakerDialog to forward messages to.  The "QnAMakerOption" is set in the FormFlow's OnCompletion like this:

```cs
    [Serializable]
    public class DomainSelectionForm
    {
        public DomainTypes domainType;

        public static IForm<DomainSelectionForm> BuildForm()
        {

            return new FormBuilder<DomainSelectionForm>().AddRemainingFields().OnCompletion(async (context, profileForm) =>
            {
                context.ConversationData.SetValue("QnAMakerOption", profileForm.domainType);

            }).Build();
        }
    }

    [Serializable]
    public enum DomainTypes
    {
        none = 0, Domain1 = 1, Domain2 = 2, Domain3 = 3, Domain4 = 4
    }
```
