### ISSUE TITLE
Authenticate a user in Microsoft Teams 

### ISSUE THREAD

**Issue by rjgmail88** [Microsoft/BotBuilder#4229]
## Bot Info
* SDK Platform:Node.js
* SDK Version: latest
* Active Channels: MS Teams, CORTANA
* Deployment Environment:  Azure Bot Service, Azure App Service

## Issue Description
I have a bot running as Cortana skill which works as meeting room finder. With Cortana channel and using sing-in at skill invocation which popup the sign-in window & authenticates user against Azure  ADv1. Once use signed in I an access user information from token as follows
```
let authorizationToken = session.message.entities.find((e) => {
            return e.type === 'AuthorizationToken';
        });
```
I am trying to find how can I authenticate user for MS teams ? As per this https://docs.microsoft.com/en-us/microsoftteams/add-bots I'm just user botID to add a bot to teams. and 1:1 chat is initiated. I believe our MS teams has o365 talent as a backbone for corporate users.

Is there any strategy/library I can user to pull a user info in bot code and verify before chat initiated.  
OR somehow user AADv1 for user authentication.

**Comment by jotrick** [comment]
Hi @rjgmail88 - it kind of depends on what information you are specifically looking for. If you simply need to know the AAD object.id of the user sending messages to the bot, then this information is included in the incoming message payload. If you actually need a usable token for that user to do things like make Graph calls, then you will need to create an authentication flow similar to this example - https://github.com/OfficeDev/microsoft-teams-sample-auth-node

**Comment by JasonSowers** [comment]
@rjgmail88 I'm not sure I understand your concerns could you please explain further? I think I am missing something here.  The bot has been added to your Teams, so people with access to your teams should be able to talk to it.

**Comment by rjgmail88** [comment]
@JasonSowers , I had this posted in MS team repo where I got the correct answer I'm looking for.
https://github.com/OfficeDev/BotBuilder-MicrosoftTeams/issues/94

Thanks.
