### ISSUE TITLE
How to ask for attachments while building dialogs using FormFlow?

### ISSUE THREAD

**Issue by MNHarun** [Microsoft/BotBuilder#4230]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.14
* Active Channels: emulator
* Deployment Environment: local development with Emulator

## Issue Description
Want to do as per question.

[Found StackOverflow question](https://stackoverflow.com/questions/47849617/how-to-receive-attachment-in-form-dialog)
and pointed me to:
- BotBuilder/CSharp/Library/Microsoft.Bot.Builder/FormFlow/AwaitableAttachment.cs
- BotBuilder/CSharp/Samples/Microsoft.Bot.Sample.FormFlowAttachmentsBot/ImagesForm.cs
I cannot make the sample to work.

[This Stackoverflow answer from april 2017 recommends ](https://stackoverflow.com/questions/43407171/how-to-receive-an-uploaded-file-inside-a-form-flow/43410603) a workaround using message.Attachment. Is this the current way to do this?

**Comment by Ma3yTa** [comment]
@MNHarun maybe this link will help you https://github.com/southworkscom/BotBuilder/blob/a0cc5400a5e886fff9701f3bad8c103bc497adfb/CSharp/Samples/Microsoft.Bot.Sample.FormFlowAttachmentsBot/ImagesForm.cs#L65

**Comment by Ma3yTa** [comment]
@MNHarun look like PR was merged https://github.com/Microsoft/BotBuilder/pull/2870 . But I don't see this functionality in current sources version

**Comment by Ma3yTa** [comment]
@JasonSowers Could you please check with the team if functionality from PR https://github.com/Microsoft/BotBuilder/pull/2870 can be merged into master?

**Comment by MNHarun** [comment]
@Ma3yTa Great help. I was looking at the pointer and decided for the functionality to be added in official release. Or was it already included and I'm missing some related pointers.

**Comment by JasonSowers** [comment]
I'll check this the team on why this was only merged to a development branch

**Comment by JasonSowers** [comment]
I'm workingwith the team to try to get this merged and released in the next SDK version.

**Comment by JasonSowers** [comment]
#4263 has been merged and a new package has been released. [3.14.0.7](https://www.nuget.org/packages/Microsoft.Bot.Builder/3.14.0.7)

**Comment by fanidamj** [comment]
Closing the issue assuming it as resolved. Please reopen a new issue if it still persists.
