### ISSUE TITLE
 [Question] How to handle user id in the webchat?

### ISSUE THREAD

**Issue by ihachani** [Microsoft/BotBuilder#4234]
## Bot Info
* SDK Platform: Node.js
* SDK Version: 3.13.1
* Active Channels:  Direct Line
* Deployment Environment: Azure Bot Service

## Issue Description
Question: How to handle user id in the webchat?

I am using the [web-chat](https://github.com/Microsoft/BotFramework-WebChat) with a Direct Line API as a channel.  The configuration requires setting a user id and a bot id. 

```javascript
      BotChat.App({
        directLine: { secret: direct_line_secret },
        user: { id: 'userid' },
        bot: { id: 'botid' },
        resize: 'detect'
      }, document.getElementById("bot"));
```

I tried to access state information from different chatbot instances and they are the same. What is the recommended way to make sure that user state information stays unique? 

How should choose the ```bot id``` ?

**Comment by nodeomega** [comment]
If you have a way of saving independent user data (assuming you're passing a unique userid for each instance), you can set up an object to store the user data and allow it to persist.  Of course, you'll want to write to a file or database, as the basic example I'm about to show will reset every time app.js is reuploaded.

**Basic Example:**

`function UserData(id) {
    this.userId = id;
    this.messageCount = 0;
}
`
...
`    let user = session.message.address.user.id;
    let userData = users.filter((u) => {return u.userId === user;});
    
    let currentUser = userData.length < 1 ? new UserData(user) : userData[0];

    session.send(`You said ${session.message.text} as Message # ${++currentUser.messageCount}`);

    if (userData.length < 1) users.push(currentUser);
`

I just tested this in a couple browsers, and it persisted the user's message count for each one separately.

If you need the bot ID, it'll be `session.message.address.bot.id`
