### ISSUE TITLE
Review Bot Skype - Try N°2

### ISSUE THREAD

**Issue by Polaris-BS** [Microsoft/BotBuilder#4235]
## Bot Info
* SDK Platform: Node.js 
* Active Channels: Skype,
* Deployment Environment: Azure Bot Service

## Issue Description
Verification for Review Bot Skype. I create this issue because the review team does not respond to the azure platform. 
The validation of my platform can not wait for the site is already in production.
Can you speed things up? Thank you.

Microsoft App Id : ad902637-9704-47a3-ada0-140809db6d6b
Bot handle : ByeAndUse  .

**Comment by EricDahlvang** [comment]
Hi @Polaris-BS 

Have the requested changes been completed?  https://github.com/Microsoft/BotBuilder/issues/4165

**Comment by Polaris-BS** [comment]
No this issue is for a new review published today

**Comment by EricDahlvang** [comment]
> Currently the bot passes all the checkpoints, but to test the functionality of the bot we need to create an account for the following website https://app.buy-and-use.eu/signup as stated by the bot. We tried creating an account but the join button is not enabled ( attached an image for further clarification). It would be helpful if the customer provides us with a test login credentials. 

![image](https://user-images.githubusercontent.com/11055362/36747810-d4a7f40c-1baa-11e8-8502-6b9e6046c8f3.png)

**Comment by Polaris-BS** [comment]
Your password should have minimum 8 caracters and minimum 1 uppercase, 1 lowercase, 1 number

**Comment by Polaris-BS** [comment]
You can use this test login :  william.krieg+conso@web-atrio.com and password :  test01Test
And click and profil to the top right and again profil and tab "Contacts de messageries" for add Skype bot to your profil

**Comment by EricDahlvang** [comment]
> I reviewed the bot, the functionality of the bot is not working consistently. It says “Je n'ai reçu aucun fichier. Veuillez réessayer” for all commands entered. Please ask the developer to fix this issue. I have attached the image for further details.

![image](https://user-images.githubusercontent.com/11055362/36751997-9dc61304-1bb6-11e8-8ba1-3b6f3b0843b3.png)

**Comment by Polaris-BS** [comment]
Ok I look that

**Comment by Polaris-BS** [comment]
Ok do you can test with this new account please ? this account is already use sorry.

Login : william.krieg+SkypeTest@web-atrio.com
password : test01Test

**Comment by EricDahlvang** [comment]
> All the functionalities and checkpoints of the bot works fine. Please make these minor changes and submit the bot again for review.
> 1.	Bot needs to have a clear and descriptive Bot Name and Publisher Name on the profile page. 
> 2.	Bot must have a clear and comprehensive description to help users understand its purpose. 

![image](https://user-images.githubusercontent.com/11055362/36813030-f737cece-1c87-11e8-9faf-3bf7c0c32fce.png)

**Comment by garniergeorges** [comment]
Hello EricDahlvang,

The information (Display name & Long description) has been updated for the review.
As against the image has a background color (#fbfbfc), should I also change. 
It I thought only colors (white & black) were not allowed?

Thank you in advance for your return

**Comment by EricDahlvang** [comment]
Hi @garniergeorges 

I believe the only two things left are:

> Bot needs to have a clear and descriptive Bot Name and Publisher Name on the profile page.
> Bot must have a clear and comprehensive description to help users understand its purpose.

**Comment by garniergeorges** [comment]
OK thanks for you return.
What is the delay of validation ?

For my understanding, we have detailed the use of the bot in English as you requested except, that our bot will be essentially French at the moment.
In your informations of review, there is no language in french, it's expected soon ?

**Comment by EricDahlvang** [comment]
@garniergeorges  Have you heard back from the review team via email?  I'd like to close this GitHub issue if possible.

**Comment by garniergeorges** [comment]
Yes, please. You can close this conversation.
Thanks
