### ISSUE TITLE
Bot Conversational History (Direct Line)

### ISSUE THREAD

**Issue by kev-slater** [Microsoft/BotBuilder#4237]
## Bot Info
* SDK Platform: Node.js
* SDK Version: 3.6.0
* Active Channels: Direct Line
* Deployment Environment: Azure App Service

## Queries
* For what period exactly is conversational history persisted by Direct Line?
* Currently where is this cache held and how is it secured?
* With the recent ability to be able to store and retrieve bot state data within a storage container outside of the Bot Framework State Service API (i.e. [https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-state](https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-state)), are there any future plans to fully support this in respect of historic messages without caching messages elsewhere? This is especially important from a security point of view where full traceability is required in terms of data flow / persistence. Note: I realise it is possible to capture and store historic messages, however what I'm trying to prevent are those messages then being cached elsewhere out of our control.

**Comment by rafaelmaeuer** [comment]
I have the same questions, also building a bot with node.js using directline with a webchat implementation. Its unclear how conversation history is stored by directline. Besides conversation history should be available for websocket too. A feature is needed to store conversation history in a private db and load it on conversation start.

**Comment by kev-slater** [comment]
Thanks for the information.
