### ISSUE TITLE
ChatConnector vs. TeamsChatConnector

### ISSUE THREAD

**Issue by rjgmail88** [Microsoft/BotBuilder#4238]
## Bot Info
* SDK Platform: Node.js
* Active Channels: Skype, MS Teams, Cortana
* Deployment Environment: Azure Bot Service, Azure App Service

## Issue Description
I am not able to decide if I can user builder.ChatConnector() instead teams.TeamsChatConnector() for my nodejs bot service. Can we use ChatConnector for a bot which can be used in MS teams or we can have TeamsChatConnector() for MS teams 1:1 bot & can be used for other channels like Cortana,skype etc. My BOT service currently has ChatConnector() and Cortana channel. We added MS teams channel & thinking if we can just user same bot for 1:1 without having to change ChatConnector & user npm "botbuilder-teams".

## Code Example
//var connector = new builder.ChatConnector({.....})

var connector = new teams.TeamsChatConnector({
    appId: process.env.MICROSOFT_APP_ID,
    appPassword: process.env.MICROSOFT_APP_PASSWORD
});

**Comment by nodeomega** [comment]
You can certainly use the regular ChatConnector in Teams.  You wouldn't need to change to the TeamsChatConnector to be able to use the bot in MS Teams at the same time as in Cortana or other channels.

The TeamsChatConnector has other functionality specifically for Teams, but you can get by without it if you're looking for general connectivity and using the bot with other channels besides MS Teams.
