### ISSUE TITLE
builder.Prompts.text is treated as Intent and executing another Intent.

### ISSUE THREAD

**Issue by plkumar** [Microsoft/BotBuilder#424]
Hi,

builder.Prompts.text is treated as Intent and executing another Intent, Is this an expected behaviour? is there a way to stop until the current dialog is ended.

Thanks
plkumar

**Comment by Stevenic** [comment]
Can you elaborate? Not sure I follow what you're saying. Prompts.text() should capture the very next reply from the user and that's it.

**Comment by plkumar** [comment]
@Stevenic when prompted user with builder.Prompts.text("Enter issue number") and let's say user enter an issue number DT-123 (Jira issue number) then system is treating it as Luis Intent (because it matches an entity type in Luis) instead treating it as reply to previous prompt.

Am i doing it wrongly, or there is a work around??

Thanks in Advance.
Lakshman

**Comment by Stevenic** [comment]
It definitely shouldn't be getting processed by LUIS if you're in a `text()` prompt. Can you share some code?

**Comment by plkumar** [comment]
@Stevenic please see the code screenshot of the code below.

<img width="1098" alt="screen shot 2016-06-10 at 10 36 50 am" src="https://cloud.githubusercontent.com/assets/462615/15954659/53c1d11a-2ef7-11e6-9dfd-6a741bc67411.png">

**Comment by plkumar** [comment]
i have an intent handler that accepts user asking some thing like below, which should trigger another intent "GetIssueDetails", which will also accepts just the issue number as well.

get DT-123
get DT-123 details
issue details for DT-123
DT-123
etc....


should i avoid the just entities as intent utterances?

**Comment by Stevenic** [comment]
no... if you're in a text() prompt you shouldn't be listening for intents at all. To be honest I'm not sure what's going on here.  Can you try running this in the emulator and send me a dump of the JSON returned from the bot before and after the text prompt?  I need to see your dialog stack and then I can probably better tell you whats happening.

**Comment by v-thgratMSGit** [comment]
Closing this issue. Thanks!

**Comment by Stevenic** [comment]
I think this was likely addressed with a recent change to the way the IntentDialog works.

**Comment by Jandisson** [comment]
Hi,

I'm having the same problem with the current version. There is any workaround?

The code below works correctly on the emulator. But when I try to use it in the webchat, after typing my name, the bot tries to fire an intent instead of following the waterfall.

```
// This loads the environment variables from the .env file
require('dotenv-extended').load();

var builder = require('botbuilder');
var restify = require('restify');


//=========================================================
// Server configuration
//=========================================================


var server = restify.createServer();

server.listen(process.env.port || process.env.PORT || 3978, function () {
    console.log('%s listening to %s', server.name, server.url);
});

var connector = new builder.ChatConnector({
   appId: process.env.MICROSOFT_APP_ID,
    appPassword: process.env.MICROSOFT_APP_PASSWORD
});

var bot = new builder.UniversalBot(connector);

var recognizer = new builder.LuisRecognizer(process.env.LUIS_MODEL_URL);
bot.recognizer(recognizer);

var intents = new builder.IntentDialog({ recognizers: [recognizer] });


server.post('/api/messages', connector.listen());

bot.on('conversationUpdate', (message) => {
  
    if (message.membersAdded) {
        message.membersAdded.forEach((identity) => {
            if (identity.id === message.address.bot.id) {
               
                bot.beginDialog(message.address, '/profile');
            }
        });
    }
});

bot.dialog('/', intents);

bot.dialog('/profile', [
  function (session) {
    builder.Prompts.text(session, 'Hi! What is your first name?')
  },
  function (session, results) {
    var firstName = session.userData.firstName = results.response
    builder.Prompts.text(session, 'Hi! What is your last name?')
  },
  function (session, results) {
    var lastName = session.userData.lastName = results.response
    builder.Prompts.text(session, 'Hi! What is your middle name?')
  },
  function (session, results) {
    session.send('Please wait, processing your answer (5s)')
    var firstName = session.userData.firstName 
    var lastName = session.userData.lastName
    var middleName = session.userData.middleName = results.response
    var callbackAddress = session.message.address
    setTimeout(function () {
      var msg = new builder.Message()
        .address(callbackAddress)
        .text("Processed your answer '%s %s %s', thanks.", firstName, middleName, lastName)
      bot.send(msg)
      session.endDialog()
    }, 0)
  }
])
```
