### ISSUE TITLE
What does my company should do to give me permission to access the Microsoft App Registration Portal.

### ISSUE THREAD

**Issue by p-phornthip** [Microsoft/BotBuilder#4240]
Now I have an own subscription and own resource,, but under company domain or under something else of the company. So, they can set up all permission for mine.

And now I have to create an Azure bot for the company, but it failed:

_**Authorization_RequestDenied**_
_Insufficient privileges to complete the operation.
Please check that your account has sufficient access to the Microsoft App Registration Portal link below._

So, I need to tell my boss about this denied and tell them how to let them grant me the permission.

Please suggest me as soon as possible.
Thank you in advance.
Joy.

**Comment by EricDahlvang** [comment]
Hi @p-phornthip 

Please check out these instructions in the FAQ: https://docs.microsoft.com/en-us/bot-framework/bot-service-troubleshoot-general-problems#why-do-i-get-an-authorizationrequestdenied-exception-when-creating-a-bot
