### ISSUE TITLE
Bot Framework, Post Method in MessageController is getting called twice

### ISSUE THREAD

**Issue by tinuCoder** [Microsoft/BotBuilder#4242]
## What i am trying to do.
I want to proactively post welcome message to user.
I am trying to achieve the same by following code

                if (activity.Type == ActivityTypes.ConversationUpdate)
                {
                    Activity welcomeMessage = activity.CreateReply();
                    welcomeMessage.Type = "message";
                    welcomeMessage.Text = $"Hey, how’s it going? how can i help you today?";
                               
                    await connector.Conversations.SendToConversationAsync(welcomeMessage);
                }

I am using conversationUpdate condition for checking if the conversation is new conversation. and if passes the check of conversationUpdate i am pushing welcome message to the user.

##Issue faced.

When i run the bot Post method in messageController files gets called twice. 
Like if someone starts a new conversation with the bot or refresh the chat conversationUpdate is called twice and that is pushing welcome message 2 times to the user. PFB
--------------------------------------------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/25457761/36730873-5060ca42-1be2-11e8-929d-d6c57097bac4.png)

## Code Example

        public async Task<HttpResponseMessage> Post([FromBody]Activity activity)
        {
            if (activity.Type == ActivityTypes.Message)
            {
                await HandleUserMessage(activity);
            }
            else
            {
                await HandleSystemMessage(activity);
            }
            var response = Request.CreateResponse(HttpStatusCode.OK);
            return response;
        }

        private async Task HandleSystemMessage(Activity activity)
        {
                if (activity.Type == ActivityTypes.ConversationUpdate)
                {
                    Activity welcomeMessage = activity.CreateReply();
                    welcomeMessage.Type = "message";
                    welcomeMessage.Text = $"Hey, how’s it going? how can i help you today?";
                               
                    await connector.Conversations.SendToConversationAsync(welcomeMessage);
                }
        }

## Expected Behavior
I need to push welcome message to the user on every new conversation "once"

## Actual Results
currently welcome message is pushed twice.

Thanks in advance :)

**Comment by tinuCoder** [comment]
Anyone who can help me on this?

**Comment by EricDahlvang** [comment]
**ConversationUpdate** is sent once when the bot is added, and once when the user is added.  More information can be found here: https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-activities#conversationupdate

So, only show the welcome message if either the user, or the bot is added by checking the MembersAdded:

```
            if (message.Type == ActivityTypes.ConversationUpdate)
            {
                var iConversationUpdate = message.AsConversationUpdateActivity();
                Activity welcomeMessage = message.CreateReply();
                welcomeMessage.Type = "message";
                welcomeMessage.Text = $"Hey, how’s it going? how can i help you today?";
                foreach (var member in iConversationUpdate.MembersAdded)
                {
                    // if the bot is added, then 
                    if (member.Id == iConversationUpdate.Recipient.Id)
                    {
                        await connector.Conversations.ReplyToActivityAsync(welcomeMessage);
                    }
                }
            }
```

**Comment by tinuCoder** [comment]
Thanks alot @EricDahlvang this worked perfect.
🥇 
closing the issue.
