### ISSUE TITLE
[.Net SDK, WebChat] Webchat: trigger a reply  with .speak("abc") property without speak und get a spoken answer Message

### ISSUE THREAD

**Issue by Tijo1011** [Microsoft/BotBuilder#4243]
## Bot Info
* SDK Version:  v3.13.1 
* Active Channels:  Direct Line, Webchat
* Deployment Environment: Azure App Service

## Issue Description
When the user logs in on the website, the event login starts and the user name is transferred appropriately. The message arrives but is not read aloud. So the  replyLogin.Speak  does not work. 
## Code Example

From MessageController

```cs
public async Task<HttpResponseMessage> Post([FromBody]Activity activity)
        {
            ConnectorClient connector = new ConnectorClient(new Uri(activity.ServiceUrl));
            if (activity.Type == ActivityTypes.Event)
            {
                switch (activity.Name)
                {
                    case "Login":
                        //TODO get User Data from Login
                        var username = activity.Value.ToString();
                        var welcomeUser = $"Hey {username}, welcome to ...";

                        Activity replyLogin = activity.CreateReply(welcomeUser);
                        replyLogin.Speak = $"Hey {username}, welcome to ";
                        replyLogin.InputHint = InputHints.ExpectingInput;
                        await connector.Conversations.ReplyToActivityAsync(replyLogin);
                        break;
                    case "VoiceVerify":
                        Activity replyVoiceVerify = activity.CreateReply("replyVoiceVerify works");
                        await connector.Conversations.ReplyToActivityAsync(replyVoiceVerify);
                        break;
                    default:
                        break;
                }

            }
```

## Reproduction Steps
1. trigger a reply with .speak("abc") property without speak. 
2. the Bot sends the message but do not Speak.
3. trigger a reply  with .speak("abc") property  with speak it works correct

## Expected Behavior
trigger a reply  with .speak("abc") property without speak und get a spoken answer Message

## Actual Results
trigger a reply with .speak("abc") property without speak(writting, event) sends the reply Message but do not speak the answer Message.

**Comment by JasonSowers** [comment]
What browser are you using webchat in?

**Comment by fanidamj** [comment]
Closing the issue assuming it as resolved. Please reopen a new issue if it still persists.
