### ISSUE TITLE
NodeJS SDK: UniversalBot.BeginDialog is throwing "Invalid address" error for proactive messages if there is no serviceUrl

### ISSUE THREAD

**Issue by rajarameshvarma** [Microsoft/BotBuilder#4244]
## Bot Info
* SDK Platform: Node.js
* SDK Version: 3.14.0
* Active Channels: Facebook
* Deployment Environment: Azure Bot Service

## Issue Description
When sending proactive messages to the user (user not already in conversation), if I provide just bot id, user id and channelId (as documented [here](https://docs.botframework.com/en-us/node/builder/chat-reference/classes/_botbuilder_d_.universalbot.html#begindialog)), it throws "address is invalid" error.

## Code Example
```
bot.beginDialog({
            bot: {
                id: "<bit id>",
                name: "BotName"
            },
            channelId: "facebook",
            user: {
                id: "user id obtained from previous conversation",
                name: "Name of the person"
            },
        }, 'test');
```

## Reproduction Steps
Use the above code to start a new dialog with the user who is not in conversation

## Expected Behavior
Bot should start a new conversation with the user

## Actual Results
It fails with an error message

> ChatConnector: startConversation - address is invalid.

## Working Code
```
bot.beginDialog({
            bot: {
                id: "<bit id>",
                name: "BotName"
            },
            channelId: "facebook",
            user: {
                id: "user id obtained from previous conversation",
                name: "Name of the person"
            },
            serviceUrl: "https://facebook.botframework.com"
        }, 'test');
```

adding serviceUrl to the address fixes everything. So I expect on of these things to happen:

1. resolve the serviceUrl using channelId
2. update the documentation with serviceUrl as mandatory for proactive notifications.

or let me know if there is a different way to do this.

**Comment by EricDahlvang** [comment]
It does seem like [IChatConnectorAddress](https://docs.botframework.com/en-us/node/builder/chat-reference/interfaces/_botbuilder_d_.ichatconnectoraddress.html ) should be the interface for **.beginDialog** 
 https://github.com/Microsoft/BotBuilder/blob/7b70cfd/Node/core/lib/botbuilder.d.ts#L3931

**serviceUrl** is definitely required in order to send a message to a user on a channel.  I'll look into this further and get back to you.

**Comment by EricDahlvang** [comment]
I discussed this with the author of the Node sdk.  He mentioned that you should be using a previously stored address when calling .beginDialog(), not constructing your own.
