### ISSUE TITLE
Dictionary keys are saved in lowercase

### ISSUE THREAD

**Issue by Zhashkha** [Microsoft/BotBuilder#4246]
## Bot Info
* SDK Platform: .NET 
* SDK Version: 3.14.0
* Active Channels: Emulator, FB
* Deployment Environment: Azure Bot Service, Azure App Service, local development with Emulator

## Issue Description
Hi guys,

I have a simple question and I wonder is that a bug or it's just should be so. When I'm saving dictionary and then retrieving it back, the keys are happened to be in a lowercase

## Code Example
Dictionary<string, Dictionary<string, string>> someData = userData.GetValueOrDefault<Dictionary<string, Dictionary<string, string>>>(ApplicationConsts.SomePropertyKey);
someData = someData ?? new Dictionary<string, Dictionary<string, string>>();

**Comment by FranciscoPonceGomez** [comment]
Hi Zhashkha,

Dictionaries in .NET do not transform keys to a lowercase form by default. Can you provide a more specific example where this issue happens?
My guessing is that at some point, before or after the keys are saved in the dictionary, the keys are converted to lowercase. If the keys were converted by the dictionary then you would have a case-insensitive (StringComparer.OrdinalIgnoreCase) dictionary. You can test this by manually adding one key with uppercase and then another with lowercase. If you get an error for the duplicated key, then your dictionary is converting to lower case for some reason.

Francisco

**Comment by Zhashkha** [comment]
Hi Francisco,

thanks for reply. Here are provide more descriptive steps:

1. 
Create Bot Application with bot template

https://prnt.sc/iu5154

2. 
install Microsoft.Bot.Builder.Azure

https://prnt.sc/iu54zm

3.
update global.asax with the following code:

protected void Application_Start()
        {
            GlobalConfiguration.Configure(WebApiConfig.Register);

            Conversation.UpdateContainer(
                builder =>
                {
                    var store = new InMemoryDataStore();
                    builder.Register(c => store)
                              .Keyed<IBotDataStore<BotData>>(AzureModule.Key_DataStore)
                              .AsSelf()
                              .SingleInstance();
                });
        }

4.
update RootDialog.cs with the following code:

private async Task MessageReceivedAsync(IDialogContext context, IAwaitable<object> result)
        {
            var activity = await result as Activity;

            StateClient stateClient = activity.GetStateClient();

            BotData userData = await stateClient.BotState.GetUserDataAsync(activity.ChannelId, activity.From.Id);
            var dicData = userData.GetProperty<Dictionary<string, string>>("DicData");

            // save data
            if (dicData == null)
            {
                dicData = new Dictionary<string, string> {
                    { "UPPERCASEKEY", "SomeValue" }
                };

                userData.SetProperty("DicData", dicData);
                await stateClient.BotState.SetUserDataAsync(activity.ChannelId, activity.From.Id, userData);
            }

            // get data
            var dicDataSaved = userData.GetProperty<Dictionary<string, string>>("DicData");

            // return our reply to the user
            await context.PostAsync($"Dictionary key after being saved: {dicDataSaved.Keys.FirstOrDefault()} \n\n Dictionary value after being saved: {dicDataSaved.Values.FirstOrDefault()}");

            context.Wait(MessageReceivedAsync);
        }

So when you run application you will see the result:

https://prnt.sc/iu7zhc

dictionary key is saved in a lower case.

P.S.
I know that I'm using deprecated functionality. It's the same result with sql state management or cosmosdb. It's just to stay short. Thanks in advance

Alex

**Comment by JasonSowers** [comment]
@Zhashkha I am seeing different results,  can you please try upgrading to the newest version of bot.builder (version 3.14.1.1 at the time of writing this) and see if this persists?

**Comment by Zhashkha** [comment]
Hi Jason,

unfortunately, I'm having the same result. Have you used my example or you have tested your own ?

**Comment by JasonSowers** [comment]
I was testing my own I will use your example.  However, this is most likely occurring during serialization/deserialization because of [this class](https://github.com/JamesNK/Newtonsoft.Json/blob/e370fc2e3ae7d01b490483350c51510285f359e3/Src/Newtonsoft.Json/Serialization/CamelCasePropertyNamesContractResolver.cs) we are using with newtonsoft.

**Comment by Zhashkha** [comment]
Thanks for reply Jason. I'm going to close this issue and open new one for newtonsoft. Any ideas ? Are you going to pin it down ?

**Comment by JasonSowers** [comment]
I can look into it further if it is blocking you, most likely it is not something we are not going to change if it is a symptom of using newtonsoft for serialization/deserialization.  However, if I could find it was due to something in our code we could fix it.

**Comment by Zhashkha** [comment]
No, it's not blocking me, but I have to use inconvenient workarounds. I definitely don't think problem is in code. Ok, so I will close the issue. Thanks for your help.
