### ISSUE TITLE
[Question] Can I use my own Cognitive Services API instead of LUIS?

### ISSUE THREAD

**Issue by Dessyk** [Microsoft/BotBuilder#4247]
I am beginner to chat Bot applications. 

And I want to know can I somehow attach my own Cognitive Services API instead of LUIS?
Or maybe it will be  better to create my own implementation to ILuisService interface?

Please help me any suggestions if i can acheive it?

**Comment by JasonSowers** [comment]
The bot framework is just a web API, so you can use it to make any other API calls you want.  You are not limited to LUIS.
