### ISSUE TITLE
[Luis] Programmatic Api - Delete Intents missing query parameter in documentation

### ISSUE THREAD

**Issue by skandyrocks** [Microsoft/BotBuilder#4249]
## Issue Description
I discovered a change in the Luis Programmatic Api. I used to delete intents via Api and discovered recently that all the utterances were moved to the intent 'None'.

I captured the outgoing requests in the luis webapp and recognized the query parameter `deleteUtterances`.
The documentation at https://westus.dev.cognitive.microsoft.com/docs/services/5890b47c39e2bb17b84a55ff/operations/5890b47c39e2bb052c5b9c1c doesn't tell anything about this parameter

## Expected Behavior
Please add the parameter `deleteUtterances` to the documentation page

**Comment by stevengum97** [comment]
Thank your for reporting this to us; I'll ask the docs team to update the reference page :)

**Comment by stevengum97** [comment]
Just an update; we've begun the process to update the docs and are currently planning on keeping this issue open until the update completes.

**Comment by stevengum97** [comment]
The changes have been made and the `deleteUtterances` parameter is now listed in the reference docs. Closing issue.
