### ISSUE TITLE
Service error 404 even after using https endpoint

### ISSUE THREAD

**Issue by pooyadav** [Microsoft/BotBuilder#425]
I am getting this error in BOTFramework,

However, bot works in emulator.
{
"error": {
"code": "ServiceError",
"message": "Sorry, X isn't available right now.",
"statusCode": 404
}
}

Any pointer how to resolve this?

**Comment by dandriscoll** [comment]
Hi @pooyadav, what is the URL you're using?

**Comment by v-thgratMSGit** [comment]
Closing this issue due to age. Thanks!
