### ISSUE TITLE
what is the best way to manage session across multiple users ?

### ISSUE THREAD

**Issue by himanshushukla254** [Microsoft/BotBuilder#4253]
## Bot Info
* SDK Platform: Node JS
* Active Channels: webchat
* Deployment Environment: Azure App Service

## Issue Description
i want to manage session across multiple user ( for the segregation of chat between users who are interacting with bot concurrently)

## Code Example
is **privateConversationData** is enough to handle this ?

**Comment by JasonSowers** [comment]
In your session object you have 3 databags to store state data  `userData`, `conversationData`, and `privateConversationData`.  These are the recommended way to store data.
