### ISSUE TITLE
[Feature Request] Actions on google Channel ?

### ISSUE THREAD

**Issue by florent33700** [Microsoft/BotBuilder#4255]
## Bot Info
* Active Channels: Actions on Google

## Issue Description
Hello,

After multiple searches, I did not find any topic about the actions on Google integration in BotFramework.
Do you plan to add it as a new channel or is it necessary to use DirectLine to create my own implementation?

Thank you in advance for your answer.

**Comment by FranciscoPonceGomez** [comment]
Hi florent33700,

For now there are not plans to work on a Google Hangouts channel that I am aware of. You need to create your own adapter on top of DL. I will investigate today on what are the different approaches that you could take and double check if there is new information on the matter.

Regards,
Francisco

**Comment by florent33700** [comment]
Hi FranciscoPonceGomez,

I'm not talking about "Google Hangouts" but "Google Assistant" to be able to, for example, communicate with a Google home. DialogFlow already offers this channel and I think it would be interesting for Bot connector to do the same.

Regards

**Comment by FranciscoPonceGomez** [comment]
I agree. There are no plans for now but I will keep you updated if anything changes. 
Check these two links. There seems to be a third party effort to integrate Google actions within Bot Framework:
https://www.npmjs.com/package/bot-framework-actions-on-google
https://github.com/Capgemini-AIE/bot-framework-actions-on-google

Best regards,
Francisco

**Comment by florent33700** [comment]
Thank you, I also found these links. It is true that I did not specify it but I am looking for a c# solution (not in node.js)

**Comment by FranciscoPonceGomez** [comment]
Sorry. I am not aware of any at the moment.

**Comment by xjose97x** [comment]
Hi @florent33700 , I'm using the nodejs solution @FranciscoPonceGomez shared with you.

All you have to do is put your directline key in that nodeJS Solution, and it will route the messages to your botframework instance which can be written in C# (as I have it).

**Comment by florent33700** [comment]
Indeed, I tried it this morning and it works properly. I would have preferred a C# solution but it will do the trick.
I hope that one day, "Actions on google" will be integrated as the default channel because it will probably be used by more and more developers :).

**Comment by pedrosancheznaranjo** [comment]
Hi @xjose97x, 

Can you explain this implementation with mor details? Where do we must to indicate our direct line secret? and, Do we need to deploy this nodejs solution in order to test it?

**Comment by DanielTizon** [comment]
I am trying to use this solution:

https://www.npmjs.com/package/bot-framework-actions-on-google
https://github.com/Capgemini-AIE/bot-framework-actions-on-google

But after a few messages with Google Assistant, my botbuilder bot abruptly get a new conversation update, and I lose the context of my current conversation, because I get even a new conversationID.

¿Anybody have got this problem or to know how to fix it? ¿@xJose97x?

Thanks!

**Comment by DanielTizon** [comment]
We finally did our own Google Actions plugin for botbuilder and it is working nice. If anyone is interested we could open our code, so everyone can help to improve it.

**Comment by amitbend** [comment]
@DanielTizon That would be great!

**Comment by jujaryu** [comment]
@DanielTizon it will be so good!

**Comment by LTsLlama** [comment]
@DanielTizon, yes please!

**Comment by tangiable** [comment]
Yes please!!!

Does anyone know if Google Actions can be integrated into Native Android app yet?

**Comment by hpavenge** [comment]
So the node express server routes the message to my bot framework. But it keeps asking for: "Okay. Let's get the test version of my test app.To know who you are, I'll just need to get your name from Google. Is that ok?" after i respond it crashes and the message coming from my bot never gets send. If i debug the server side there are no errors. Cant i disable the permission phase in which it is asking for info?

**Comment by DanielTizon** [comment]
We have started to clean the code to publish it. And we have the agreement of our company to open source it. I'll let you know as soon as it is ready.

**Comment by JasonSowers** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team

**Comment by LTsLlama** [comment]
@DanielTizon,
Are you still planning to open source this?
Did you use the C# or JS SDK?

Thank you,
Douw

**Comment by Ragha2207** [comment]
Hi,

I tried the NodeJs solution. Included my DirectlineSecret of my Microsoft-Bot in the app.use(actionsOnGoogleAdapter(<DirectlineSecret>).router)

but I am getting the following error:

TypeError: Cannot read property 'toLowerCase' of null
    at continueConversation (\bot-framework-actions-on-google\lib\fulfilment.js:71:36)
    at  \bot-framework-actions-on-google\lib\fulfilment.js:122:5
    at ActionsSdkApp.handleRequestAsync (actions-on-google\assistant-app.js:511:29)
    at ActionsSdkApp.handleRequest (actions-on-google\assistant-app.js:419:10)
    at bot-framework-actions-on-google\lib\fulfilment.js:135:9
    at Layer.handle [as handle_request] (express\lib\router\layer.js:95:5)
    at trim_prefix (\express\lib\router\index.js:317:13)
    at express\lib\router\index.js:284:7
    at Function.process_params \express\lib\router\index.js:335:12)
    at next (express\lib\router\index.js:275:10)

**Comment by Am-400** [comment]
I am also facing the same issue as Ragha2207. Kindly help.

**Comment by vignesh-123** [comment]
Even I am having the same issue. Is it working for anyone??

**Comment by tvvignesh** [comment]
Any plans on supporting Google Assistant? Since a lot of people are using it daily, was wondering if you guys had a change in strategy.

**Comment by EricDahlvang** [comment]
Hi @tvvignesh  

The Bot Framework community provides a Google Adapter: https://www.nuget.org/packages/Bot.Builder.Community.Adapters.Google/

Source can be found here: https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/tree/develop/libraries/Bot.Builder.Community.Adapters.Google
