### ISSUE TITLE
Azure Function Bot upgrade from v3.12.2.4 to v3.13.1 causes failure to connect

### ISSUE THREAD

**Issue by RonPeters** [Microsoft/BotBuilder#4257]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.13.1
* Active Channels: Bot Framework Emulator v3.5.35
* Deployment Environment: local development with Function emulator

## Issue Description
I have a Function Bot that works just find with v3.12.2.4. When I update the NuGet libraries to v3.13.1, everything builds. But when I run the function and attempt to connect via Bot Framework Emulator, I get an error in the function emulator window that it can't find the 3.12.2.4 version of Microsoft.Bot.Connector

## Reproduction Steps
1. Create Azure Function from template
2. Copy files from Bot template into function
3. Install 3.12.2.4 Bot libraries
4. Run function from Visual Studio (it will prompt to upgrade the Function environment. do it)
5. Connect to function endpoint from Bot Framework Emulator
6. Have successful conversation with Bot
7. Upgrade to 3.13.1 Bot libraries, run function
8. During connection, observe error 500 in Bot Framework Emulator Log and observe error in function window attempting to locate Microsoft.Bot.Connector v3.12.2.4

## Expected Behavior
Bot Emulator should connect without error

Works:
Microsoft.Bot.Builder v3.12.2.4
Microsoft.Bot.Builder.Azure v3.2.5
Microsoft.Bot.Connector v3.12.2.4
Microsoft.NET.Sdk.Functions v1.0.8

Fails:
Microsoft.Bot.Builder v3.13.1
Microsoft.Bot.Builder.Azure v3.2.5
Microsoft.Bot.Connector v3.13.1
Microsoft.NET.Sdk.Functions v1.0.8

![azure functions cli 1 0 9 log](https://user-images.githubusercontent.com/1635122/36925350-67ee9ec2-1e27-11e8-8193-30f679182421.PNG)
![bot emulator log](https://user-images.githubusercontent.com/1635122/36925354-6b546efc-1e27-11e8-8f91-0578fa9d7148.PNG)

**Comment by RonPeters** [comment]
After researching, I believe this is connected to the fact that Azure Functions has no mechanism for binding redirects. Microsoft.Bot.Builder.Azure v3.2.5 is linked to Bot.Builder v3.12.2.4. Please release an updated Bot.Builder.Azure that links to the current libraries, and that should solve my problem.

Thanks!

**Comment by RonPeters** [comment]
Also, I just tried to update to the alpha of Bot.Builder.Azure. Failure:

Azure Functions requires Newtonsoft.Json = 9.0.1
Microsoft.Bot.Builder.Azure 4.0.0-alpha20180221 requires Newtonsoft.Json >= 10.0.3

So please go back and release a Microsoft.Bot.Builder.Azure v3.2.6 that requires Newtonsoft.Json = 9.0.1 and Microsoft.Bot.Builder = 3.13.0.3. It would be most appreciated.

**Comment by EricDahlvang** [comment]
The v4 alpha version is for Bot Builder v4, not v3.x

You are right, BotBuilder-Azure needs to be updated to use the latest BotBuilder  packages.  In fact, the library itself has already been updated: https://github.com/Microsoft/BotBuilder-Azure/pull/52/files  It just hasn't been released yet.  There is no timeline or schedule for the release, but I assume it will be soon.

Lastly, this is an issue with https://github.com/Microsoft/BotBuilder-Azure not with the BotBuilder.  Please open an issue with that repository if you wish to pursue this further.  Or, wait for the team to release the next nuget package.  Sorry for the inconvenience.
