### ISSUE TITLE
Is it possible to enable Skype for Business channel for multiple o365 tenants?

### ISSUE THREAD

**Issue by hpksp** [Microsoft/BotBuilder#4259]
I have a bot channels registration account pointing to bot api hosted on azure. I want to enable Skype for Business channel for multiple o365 tenants using the same bot channels registration account. Is it possible to achieve this?

**Comment by FranciscoPonceGomez** [comment]
Hi hpksp,

First of all you need to add your bot to SfB. To add your bot to Skype for Business, you must be the Tenant Administrator of a Skype for Business Online environment. You need to follow these steps:
https://skypeappregistration.azurewebsites.net/bot/02ee8528-4bf4-49f0-96ff-a60f72577237

After that You implement ICredentialProvider which is responsible for looking up appPassword by AppId and validating that the password is correct. This means you can have a database of bot AppId/Passwords that one endpoint services, and you look up the appid/secret and validate calls.

[ BotAuthentication(CredentialProviderType=typeof(SimpleCredentialProvider))]

Here is a simple sample implementation https://docs.botframework.com/en-us/csharp/builder/sdkreference/d3/dde/_credential_provider_8cs_source.html

Regards,
Francisco

**Comment by hpksp** [comment]
Hi Francisco,

Thanks for the detailed response :)

I'm already using Multi Credential Provider approach in my project and I use Azure SQL server to store all the credentials.

My question is more related to adding bot to SfB. I want to send out the "Connecting your bot to Skype for Business Online" link to our customers so that they can add our chatbot to their tenants. What I would like to clarify is that can I send the same link to multiple customers or do I need to create dedicated Bot Channel Registrations account for each and every customer. 

Based on your answer what I understood was that one Microsoft App Id (Channel Registration Account) can be associated only with one o365 tenant. Really appreciate if you can clarify this. Thanks in advance. 

Best Regards,
Kasun

**Comment by hpksp** [comment]
Hi @FranciscoPonceGomez. Really appreciate if you could help me out with this question. Thanks :)

**Comment by LoungeFlyZ** [comment]
I would love to know the answer to this also.  We are not using the sfb bot framework stuff currently as we cant tell if multi-tenant is possible without manually registering an appid/secrets in each tenant.  We are an ISV and have hundreds of customers, so this sort of manual setup isnt possible. 

If they could register our bot (one appid/secret) in their tenant that would be "ok".

**Comment by FranciscoPonceGomez** [comment]
I will take a look at this issue today. 

Francisco

**Comment by hpksp** [comment]
@FranciscoPonceGomez This is great news!!!! Thanks for the update :+1:
