### ISSUE TITLE
What is the best way to get user input in this case?

### ISSUE THREAD

**Issue by brunoadamalves** [Microsoft/BotBuilder#4260]
## Bot Info
* SDK Platform: .NET
* Deployment Environment: local development with Emulator

## Issue Description
Hi, I want to validate if the user is passing three specific informations in one utterance; But I don't know exactly what is the best way to check and ask for the missing information in a consecutive way.

## Code Example
        [LuisIntent("some_intent")]
        public async Task someTask(IDialogContext context, LuisResult result)
        {
            var name = result.Entities.FirstOrDefault(c => c.Type == "name")?.Entity;
            var age = result.Entities.FirstOrDefault(c => c.Type == "age")?.Entity;
            var color = result.Entities.FirstOrDefault(c => c.Type == "color")?.Entity;

            if(name == null)
            {
                await context.PostAsync("Please, could you write your name again?");
                
                name = context.Wait(getPersonname); //maybe something like that but how to keep the execution in this scope after getting the informatin?
            }
            else if (color == null)
            {
            ...
            }
            [and the program execution continues here]
            ....

**Comment by flash2048** [comment]
Hi.
Have you tried using **FormFlow** for this task?
I think in this case it will be very convenient.
https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-formflow

**Comment by brunoadamalves** [comment]
Hi,
Thanks for the fast reply, I thinks that it may be the solution, but at same time I was trying to make te conversation with the user more human to make use of the entities recognition in the text

Thanks +1

**Comment by flash2048** [comment]
Also you can use state for filling needed field.
For example, as shown here, or do something similar:
https://github.com/flash2048/LoftBlog_TrainingBot/blob/master/Lesson6/LoftBlog_TrainingBot/LoftBlog_TrainingBot/Commands/Userinfo.cs


```C#
 private UserInfoState? _state;
...
switch (_state)
{
    case UserInfoState.Name:
        Name = activity.Text;break;
    case UserInfoState.Age:
        Age  = activity.Text; break;
    case UserInfoState.Color:
       Color = activity.Text; break;
}

if (String.IsNullOrEmpty(Name)
{
    await context.PostAsync("Please, could you write your name again?");
    _state = UserInfoState.Name; //Change state to write the text in the desired variable
    context.Wait(someTask); //The name of your method is passed
    return;
}
...
```

**Comment by brunoadamalves** [comment]
Hi, Andrei

Thanks for your time and help with this question, I'm rethinking how should I deal with those missing informations based your suggestions

Thanks again +1
