### ISSUE TITLE
Facebook Messenger splits and truncates messages

### ISSUE THREAD

**Issue by etbuilder** [Microsoft/BotBuilder#4261]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.13.1
* Active Channels: FacebookMessenger

## Issue Description
context.postAsync("text") splits messages into 640 character length, while Facebook send api limit is 2000 (https://developers.facebook.com/docs/messenger-platform/reference/send-api)

## Reproduction Steps
1. Send a message with 1500 character with spaces
2. Messenger shows multiple messages

## Expected Behavior
Messenger should show one single message, tried through postman with the same text

## Actual Results
Messenger shows multiple messages

**Comment by nodeomega** [comment]
I have noticed in the Send API documentation stating about the 2000 character limit in UTF-8, as you have said.  However, I am not seeing that change in the [Facebook Messenger Changelog as of March 2nd, 2017](https://developers.facebook.com/docs/messenger-platform/changelog?__mref=message_bubble#20170302) referencing an increase from a 320 character to 640 character limit for messages.  I am also seeing the breaking up of messages via the Botbuilder into 640-character segments, so I have definitely been able to replicate the issue.

My suspicion is that Facebook has increased the limit in one place, but not in another.  I will reach out to Facebook and see if this is indeed the case.  I would recommend yourself doing the same.  But from what I am seeing, this is not specifically a Botbuilder issue but more a Facebook Messenger API issue.

**Comment by nodeomega** [comment]
I have filed a [bug report with Facebook](https://developers.facebook.com/bugs/341070546388612/) regarding clarification of this issue.

**Comment by nodeomega** [comment]
Facebook is looking into their end of things and are going to be checking their docs as well, per reply received overnight.

**Comment by nodeomega** [comment]
From the facebook team:

"[...] we've updated the changelog entry for Nov 20, 2017 to include the increased character limit (https://developers.facebook.com/docs/messenger-platform/changelog?__mref=message_bubble#november-20--2017).

Also, I've received clarification that while we now support 2000-character messages, Botbuilder's implementation is still splitting up messages into smaller chunks."

I'm going to double-check a few things on our end to ensure that this isn't our implementation doing this.

**Comment by nodeomega** [comment]
After further review, it turns out this issue isn't on Facebook's end after all.  I will let you know when a fix has been applied.

**Comment by etbuilder** [comment]
Nice thank you @nodeomega we are already using Facebook API directly for this by passing botframework, but let us know when this is fixed to use botconnecter again.

**Comment by nodeomega** [comment]
@etbuilder A fix has been deployed and Facebook Messenger messages should now be sending as one message up to the Facebook SDK limit (2000 characters).  I've tested this on my end and have verified that the messages are no longer being broken apart, so you should be good to go.  Closing this issue as it is now resolved.
