### ISSUE TITLE
Slack bots not responding on bot framework

### ISSUE THREAD

**Issue by v46** [Microsoft/BotBuilder#4264]
Hi folks, 

We see all our production slack bots on bot framework not responding for the past 15 minutes. App insights is showing these messages:

POST to XXX failed: Certificate not found: 182c40ad.....75e9c94
Certificate not found: 182c40ad.....75e9c94

Microsoft.Bot.Schema.BotException:
   at Microsoft.Bot.ChannelConnector.BotAPI+<PostActivityToBotAsync>d__29.MoveNext (Microsoft.Bot.ChannelConnector, Version=3.2.0.3, Culture=neutral, PublicKeyToken=null)
Inner exception System.Exception handled at Microsoft.Bot.ChannelConnector.BotAPI+<PostActivityToBotAsync>d__29.MoveNext:
   at Microsoft.Bot.ChannelConnector.BotAPI.SetHeaders (Microsoft.Bot.ChannelConnector, Version=3.2.0.3, Culture=neutral, PublicKeyToken=null)
   at Microsoft.Bot.ChannelConnector.BotAPI+<PostActivityToBotAsync>d__29.MoveNext (Microsoft.Bot.ChannelConnector, Version=3.2.0.3, Culture=neutral, PublicKeyToken=null)

## Bot Info
* SDK Platform: node js
* SDK Version: 3.11
* Active Channels: Slack
* Deployment Environment: Azure Bot Service

**Comment by v46** [comment]
Hi folks, can you confirm if there are known outages with bot framework at this time. All our production bots are impacted. They have been 'offline' for more than 30 minutes now.

**Comment by v46** [comment]
Any updates @EricDahlvang? 

We really need some status page to indicate bot framework service health especially now that bot framework is GA.

**Comment by EricDahlvang** [comment]
Thank you for reporting this.  We've resolved the underlying problem.  Please let us know if you run into anything else.

You're right: the Bot Framework needs a status page.

**Comment by v46** [comment]
Bots still not responding. Now we are seeing these messages at the SDK layer:

ERROR: ChatConnector: receive - invalid signing key or OpenId metadata document.

**Comment by EricDahlvang** [comment]
@v46 Apologies, I spoke too soon.  Not every data center has been updated yet.  I will let you know once that is complete.

**Comment by EricDahlvang** [comment]
It looks like the fix has been rolled out to all data centers.  Please let me know if you are still experiencing problems.

**Comment by v46** [comment]
Yes, finally back online. Thank you for the follow up again @EricDahlvang. 

What was the underlying problem you mention?

**Comment by EricDahlvang** [comment]
We are in the process of changing how we configure message subscriptions for slack bots.  Bots should be migrated to use the slack app service instead of the worker role.

Please see here for more information: https://docs.microsoft.com/en-us/bot-framework/bot-service-channel-connect-slack#subscribe-to-bot-events

**Comment by xitij** [comment]
I'm still seeing this issue on all our production bots. Are we sure this is resolved?

**Comment by EricDahlvang** [comment]
@xitij Please restart the bot service.
