### ISSUE TITLE
Skype: Not able to send file attachment to user OR Hyperlink url of file location

### ISSUE THREAD

**Issue by srinathMV** [Microsoft/BotBuilder#4272]

**Comment by JasonSowers** [comment]
please provide details

**Comment by srinathMV** [comment]
Hi Jason,

Please find the details below,

I have a requirement for the Bot to send a file as a downloadable to the users in Skype. The files are in physical path. 

The below mentioned is the code 


 public async Task SelectedOptionAsync(IDialogContext context, IAwaitable<string> argument) 
{ 
 var message = await argument; 
 var replyMessage = context.MakeMessage(); 
 Attachment attachment = null; 
 attachment = GetLocalAttachment(); 
 replyMessage.Attachments = new List<Attachment> { attachment }; 
 await context.PostAsync(replyMessage); 
 await this.DisplayOptionsAsync(context); 
} 

private static Attachment GetLocalAttachment() 
{ 
 var Path = HttpContext.Current.Server.MapPath("~/images/demo.pdf"); 
 var pdfdata = Convert.ToBase64String(File.ReadAllBytes(Path)); 
 return new Attachment 
 { 
 Name = "demo.pdf", 
 ContentType = "application/pdf", 
 ContentUrl = $"data:application/pdf;base64,{pdfdata}" 
 }; 
}



In the above code i am trying to attach the contents of the file in the Message attachment. When I checked the Skype Channel, it displays "MIME type is Invalid"

I am using  Skype Client (desktop application)

Version: 7.40.0.104 & 8.16.0.4

**Note:** This is working in the Emulator & I am not using Skype for Business. Also I am aware that this functionality does not work in the Skype for Business.  -->
	  

2. Also I need to send the location of the file as Hyperlink URL to the user. Currently we were only able to send as String and not as a URL. 


Please help us out which solution to overcome these issues.
