### ISSUE TITLE
Authorization_RequestDenied

### ISSUE THREAD

**Issue by p-phornthip** [Microsoft/BotBuilder#4273]
A week ago, I have stuck with this error:

_**Authorization_RequestDenied**
Insufficient privileges to complete the operation.
Please check that your account has sufficient access to the Microsoft App Registration Portal link below._

This FAQ helped me: https://docs.microsoft.com/en-us/bot-framework/bot-service-troubleshoot-general-problems#why-do-i-get-an-authorizationrequestdenied-exception-when-creating-a-bot

But this time, I deleted the old bot, because I want to create a new bot.
I'm getting the same error. Did I miss something?

Thank you in advance.
Joy.

**Comment by p-phornthip** [comment]
Oh! It's works now.

**Comment by EricDahlvang** [comment]
Hi @p-phornthip 

Did you sign out, and back in?  What solved this issue for you?
