### ISSUE TITLE
[Node.js SDK] Name key is missing in "from" of object. 

### ISSUE THREAD

**Issue by kinghemantraj** [Microsoft/BotBuilder#4274]
## Bot Info
We are using our own node js SDK 

## Issue Description
Name key is missing in "from" (highligted with bold) of object.

{

"text":",l;",

"type":"message",

"timestamp":"2018-01-17T09:08:10.63Z",

"id":"1516180090616",

"channelId":"skype",

"serviceUrl":"https://smba.trafficmanager.net/apis/",

"from":{

"id":"29:1eBdyD_2yXeWkK8uXbeuHGiISKP_6HW-1unx086xl2yk"

},

"conversation":{

"id":"29:1eBdyD_2yXeWkK8uXbeuHGiISKP_6HW-1unx086xl2yk"

},

"recipient":{

"id":"28:d05ace01-9501-4d00-9538-c7d9ea1fd338",

"name":"sbh_sample_xyz"

},

"entities":[

{

"locale":"en-US",

"country":"US",

"platform":"Windows",

"type":"clientInfo"

}

],

"channelData":{

"text":",l;"

}

}

## Expected Behavior
It should give below object 
"from": {
          "id":"29:1eBdyD_2yXeWkK8uXbeuHGiISKP_6HW-1unx086xl2yk"
            "name":"Display Name"
    }

## Actual Results
name is missing in"from" object

**Comment by FranciscoPonceGomez** [comment]
Hi kinghemantraj,

There is very little information here. I need more context to understand the problem. Where does this information come from? What is the architecture of your bot? Is it hosted in Azure and you use your own client? Do you host it yourself?

Regards,
Francisco

**Comment by kinghemantraj** [comment]
Q. Where does this information come from?
A. We registered our bot in https://portal.azure.com (Bot Services).

Q. What is the architecture of your bot? 
A. We registered our API in "Messaging endpoint". 
   If user types something in bot then we are receiving data in above API.
   As per the user context we are replying back to bot using Skype send 
   API(https://apis.skype.com/v3/conversations/).
   In this way whole conversion happens.

Q. Is it hosted in Azure and you use your own client? 
A. We hosted our application at our end.

Q. Do you host it yourself?
A. Yes, We are using our own node application to interact with bot.

**Comment by EricDahlvang** [comment]
Have you tried supplying a name in the from field?  

```js
"from":{
"id":"29:1eBdyD_2yXeWkK8uXbeuHGiISKP_6HW-1unx086xl2yk",
"name":"name goes here"
},
```

We will need to see a code example to reproduce the issue and assist with resolving it.

**Comment by JasonSowers** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
