### ISSUE TITLE
'npm' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by p-phornthip** [Microsoft/BotBuilder#4275]
When I run **Build.cmd**, It said:

_Installing Kudu Sync
An error has occurred during web site deployment.
'npm' is not recognized as an internal or external command,
operable program or batch file._

I have added some source code in **EchoDialog.cs** but it failed, then I remove them out and re-run **Build.cmd** again. But I got the error above! I'm sure that I didn't remove more, because it just a few code.

Thank you in advance.
Joy.

**Comment by EricDahlvang** [comment]
Please try restarting the website itself.

**Comment by p-phornthip** [comment]
@EricDahlvang 

I have restarted the app and the website, also signed out and signed in back. But it happened the same.

**Comment by stevengum97** [comment]
### You'll want to navigate to **`<the-name-of-your-resource>.scm.azurewebsites.net/DebugConsole`**:
![1st](https://user-images.githubusercontent.com/14935595/37175097-52a91fba-22cd-11e8-837c-f2202a255657.PNG)

____
### Then navigate to **`D:\home\site\wwwroot`**:
![2nd](https://user-images.githubusercontent.com/14935595/37175117-618b79b0-22cd-11e8-84b5-2289af67e3d9.png)

____
### From here you can run the `build.cmd`:
![3rd](https://user-images.githubusercontent.com/14935595/37175133-71953db4-22cd-11e8-8d33-dadad2525883.PNG)

There's a weird bug being investigated where calling `build.cmd` from the online code editor doesn't work and throws the error you ran into above. Oddly enough though, typing `npm --version` in the code editor's console will show that npm is indeed detected as the version number will be returned.

**Comment by p-phornthip** [comment]
@stevengum97 Thank you very much! Now I can work on DebugConsole.

**Comment by rwifall** [comment]
You still get this error when following the instructions below, so either the documentation should be fixed, or this bug should be fixed.

[https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-luis-dialogs?view=azure-bot-service-3.0](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-luis-dialogs?view=azure-bot-service-3.0)

**Comment by EricDahlvang** [comment]
@rwifall Yes, sometimes the error still occurs.  @stevengum97 has provided a valid workaround.

**Comment by VanessaOrtiz30** [comment]
This was from a comment I found online (thank you robertalexandrov from msdn) it really helped me; 
I just added onto it as to what I wish it had....

I solved this by clicking into your “open online editor”, and at the top bar (next to app service editor) click on you bots name/title, and then given the drop down menu select "Open Kudu Console".
*Make sure you’re in browser it says the-name-of-your-resource-or-title.scm.azurewebsites.net/DebugConsole*
Then on the “old console” do:
cd site
cd wwwroot
./build.cmd

Microsoft should do a better job of making this clear.
*I hope this helps someone else

**Comment by ceteongvanness** [comment]
still exist in the Visual Studio Online
