### ISSUE TITLE
Something like Gender API in LUIS

### ISSUE THREAD

**Issue by maba4891** [Microsoft/BotBuilder#4278]
Is there something like the functionality of Gender API (https://gender-api.com) in LUIS?

In other words: if a user provides his/her full name to the chatbot can LUIS determine the gender of the user and which part is the first and which is the last name?

I know that this is a duplicate of #2007 where a similar point was brought up by @srirams007. But there the question wasn't really solved and I wanted to check if there have been new developments on this.

Thanks!

**Comment by FranciscoPonceGomez** [comment]
Hi maba-4891,

LUIS doesn't have a built-in gender recognizer but you can train your model to understand the constituents of a name using some examples. You can add phrase lists of names that are males only or females only. Also make sure to label enough data.

Regards,
Francisco
