### ISSUE TITLE
Download Source Code from Azure

### ISSUE THREAD

**Issue by luisnatividade** [Microsoft/BotBuilder#4279]
## Bot Info
* SDK Platform:  .NET 
* Active Channels: Direct Line
* Deployment Environment:  Azure App Service
* MicrosoftAppId: a9846b9a-f1b4-4849-9103-28fd761ee633
## Issue Description
I'm using VS to develop the bot. I've downloaded the code in the beginning of the development and I publish the code everytime I want to change something. 

The problem is that when I try to download the code from Azure using the Download Source Code option, the version downloaded is not the actual version, it's a old version almost from the beginning of the development. 

## Reproduction Steps
![image](https://user-images.githubusercontent.com/7551721/37163349-7664707c-22ef-11e8-95d9-18cf1ec515c6.png)

## Expected Behavior
Last version of code.

## Actual Results
Old version of the code.

## PS. I think this will be a problem when I try to migrate the bot.

**Comment by FranciscoPonceGomez** [comment]
Hi 	luisnatividade,

Try rebuilding the source code online using build.cmd and download the source code again.

**Comment by luisnatividade** [comment]
Hi @FranciscoPonceGomez thanks for the response.

I've done that and didn't work. Still an old version when I download the source code.

Below it's a print of the console.

![image](https://user-images.githubusercontent.com/7551721/37220220-d65ca700-23bd-11e8-9d72-5d95abe377d3.png)

**Comment by Quico20** [comment]
I had the same issue, It turns out that if you updated the nuget packages, the online editor doesnt accept Microsoft.Net.Compiler version greater than 1.2.1 and Microsoft.CodeDom.Providers.DotNetCompilerPlataform version 1.0.1.

I downloaded the version as you did from the azure service right from the beginning and I didnt updated at all, it work well as long as i dont try to add LUIS services, because then i begin to have "Issue code messages"

And if you try to downgrade all your nuget packages as i was default download source code, i remaing broken. believe me I've tried!!!

**Comment by luisnatividade** [comment]
@Quico20  thanks for the answer. Did you find any solution?

@FranciscoPonceGomez any solution to this? I tried to migrate the bot but the old code version was migrated. I had to roll back...

**Comment by FranciscoPonceGomez** [comment]
I will report this and check if there is a workaround. I will get back to you soon.

**Comment by Quico20** [comment]
@FranciscoPonceGomez your welcome, I was able to finished my Bot Framework course, I successfully made my bot worked, but upgrading everything except the libraries mentioned before!!
I'm glad to help!!

**Comment by luisnatividade** [comment]
@FranciscoPonceGomez any update on this? I'm currently unable to migrate the bot...

Thanks.

**Comment by FranciscoPonceGomez** [comment]
We are working on the issue right now. I will get back to you as soon as I have a fix.

**Comment by FranciscoPonceGomez** [comment]
Hi luisnatividade,

I can't reproduce the issue on my end using a bot template. Can you send me your code in a .zip file to my personal email (v-frgome@microsoft.com)?

Thanks,
Francisco

**Comment by FranciscoPonceGomez** [comment]
Can you check if your .csproj file is missing the source targets? It should be at the bottom of the file.

```csharp
  <Import Project="PostDeployScripts\IncludeSources.targets" Condition="Exists('PostDeployScripts\IncludeSources.targets')" />
  <Import Project="..\PostDeployScripts\IncludeSources.targets" Condition="Exists('..\PostDeployScripts\IncludeSources.targets')" />
  
</Project>
```

I was able to reproduce the issue by commenting these two lines. If manually or automatically any of these lines have been modified or removed the publish doesn't actually affect the target sources.

Francisco

**Comment by luisnatividade** [comment]
@FranciscoPonceGomez instead of those lines i had

`<Import Project="PostDeployScripts\IncludeSources.targets" />`

But I put the lines you sent and it did not solve the problem.

I'm not sure, but I think in the beginning the console wasn't with "master". (Check the image below).

![image](https://user-images.githubusercontent.com/7551721/37671583-ef5b9d8e-2c63-11e8-9781-cd3d1b439364.png)

I'm not sure if this can be related to the problem.

Thanks in advance.

**Comment by FranciscoPonceGomez** [comment]
We are looking into this. Thanks for your patience.

**Comment by EricDahlvang** [comment]
@luisnatividade  Are you able to share the code?

**Comment by luisnatividade** [comment]
@FranciscoPonceGomez @EricDahlvang  I can't send the code due to company restrictions. But I can share some specific files if you want.

Thanks.

**Comment by luisnatividade** [comment]
@EricDahlvang file sent.

Thanks.

**Comment by EricDahlvang** [comment]
Please try downloading the source again, and overwrite your project’s PostDeployScripts folder with the downloaded version.  Then, go through these steps to publish:

In Visual Studio, right click on {PROJ_NAME} and select 'Publish'

1. In the publish profiles tab, click 'Import'
2. Browse to 'PostDeployScripts' and pick '{SITE_NAME}.publishSettings'

**Comment by luisnatividade** [comment]
I've done that right now and did not solve the issue.

The {SITE_NAME}.publishSettings (inside PostDeployScripts folder) has 18/01/2018 as the last date modified. Don't know if it is supposed to be like that or not.

Thanks.

**Comment by EricDahlvang** [comment]
Something you could try is to create a brand new web app bot, download the source, and compare the project and PostDeployScripts to the one that is not working.

**Comment by EricDahlvang** [comment]
@luisnatividade Have you tried comparing a newly downloaded web app bot's PostDeployScripts and project to the one that is having issues?

**Comment by EricDahlvang** [comment]
Closing due to no response
