### ISSUE TITLE
Taking simple user input

### ISSUE THREAD

**Issue by vaditya04** [Microsoft/BotBuilder#428]
Is there a simple way I can have a user message passed into a string variable (c#)?

Essentially, I want to take the next user message as an input half way through a method and continue the execution of the method with the message stored as a variable.

I want to avoid the process of using PromptDialog, modifying the enclosing method, etc. (Issue #415)

What I want is the equivalent of taking user inputs through the console, but in this case I would be doing it through the bot framework interface. Nothing fancy is needed, like retries, etc. 

EDIT: I don't want/need the message to go through LUIS either (MessageReceived also puts each message through LUIS)

Thanks!

**Comment by chrimc62** [comment]
It is up to you where you wait for messages.  The built-in dialogs do it themselves but you can always do context.Wait(<Method to call when message comes in>) to wait for a message you want to handle yourself.

**Comment by ankitbko** [comment]
@chrimc62 I saw multiple issues regarding the same issue if I am not mistaken. #453 #332 
I believe essentially what folks are asking for is making PromptDialog a blocking operation(sort of). Basically making the post PromptDialog statement as a continuation to user input. 
For example:
```CSharp
void DoSomething()
{
  A();
  var input = PromptDialog.Text(......)
  B();
}
```
`A()` executes.
`PromptDialog` executes and Bot is suspended.
User sends message. Message is assigned to `var input`.
`B()` executes.

Feature wise something similar to how await works. I don't know how plausible it is or whether it is even possible keeping stateless nature in mind. This would definitely require some kind of compiler support to automatically make the post PromptDialog statement as a continuation method to be executed keeping the current method state in mind. This quickly gets complicated.

**Comment by SageEx** [comment]
This would be a really nice addition to dialogs.

**Comment by chrimc62** [comment]
We did briefly consider being able to do this, but as you note to do it while being stateless requires us to do compiler work.  This is possible, but is a lot of work so explicitly passing in your continuation method continues to be the best choice.
