### ISSUE TITLE
Unable to save settings in bot service

### ISSUE THREAD

**Issue by reshmamkumar** [Microsoft/BotBuilder#4283]
I created a new bot service in azure, but not able to update any settings. No error message shown, but data is not saved.
The following is the error I'm getting.
<img width="507" alt="capture" src="https://user-images.githubusercontent.com/26716124/37194311-90b619bc-23a8-11e8-998d-e1d03359c27d.PNG">

**Comment by FranciscoPonceGomez** [comment]
Hi reshmamkumar,

Please, check that the AppInsight information in your bot if any is correct and reload the Azure portal.

**Comment by reshmamkumar** [comment]
I'm not using application insights in my bot service( it is optional), Anyway, in another subscription also, I'm getting the same issue. Is it anything related to my resource access? 
![image](https://user-images.githubusercontent.com/26716124/37322328-c7a4b0fc-26b7-11e8-9961-5408f9ba4cff.png)

**Comment by fanidamj** [comment]
Closing the issue assuming it as resolved. Please reopen a new issue if it still persists.
