### ISSUE TITLE
[QnAMaker] QnA Maker - Resource Not Found

### ISSUE THREAD

**Issue by BotRate** [Microsoft/BotBuilder#4284]
## Issue Description
I create a new service in QnAMaker, publish it. Than I tried to go for the following link: https://westus.api.cognitive.microsoft.com/qnamaker/v2.0/knowledgebases/{knowledgeBaseID}/train (with my BaseID) and see this: { "error": { "code": "ResourceNotFound", "message": "The requested resource was not found." } }

What I did wrong?

**Comment by FranciscoPonceGomez** [comment]
Hi BotRate,

You can't just access the resource on your browser. You need to build an HTTP request (PATCH in this case) in order to communicate with the API. If you go to the section API 2.0 you would see some samples to build the request for all exposed API endpoints. In your case, you can build your request like this (click on them):

<details>
<summary><h1>cURL:</h1></summary>

@ECHO OFF

curl -v -X PATCH "https://westus.api.cognitive.microsoft.com/qnamaker/v2.0/knowledgebases/{knowledgeBaseID}/train"
-H "Content-Type: application/json"
-H "Ocp-Apim-Subscription-Key: {subscription key}"

--data-ascii "{body}" 

</details>


<details>
<summary><h1>C#</h1></summary>

using System;
using System.Net.Http.Headers;
using System.Text;
using System.Net.Http;
using System.Web;

namespace CSHttpClientSample
{
    static class Program
    {
        static void Main()
        {
            MakeRequest();
            Console.WriteLine("Hit ENTER to exit...");
            Console.ReadLine();
        }
        
        static async void MakeRequest()
        {
            var client = new HttpClient();
            var queryString = HttpUtility.ParseQueryString(string.Empty);

            // Request headers
            client.DefaultRequestHeaders.Add("Ocp-Apim-Subscription-Key", "{subscription key}");

            var uri = "https://westus.api.cognitive.microsoft.com/qnamaker/v2.0/knowledgebases/{knowledgeBaseID}/train?" + queryString;

        }
    }
}

</details>

<details>
<summary><h1>JavaScript</h1></summary>

<!DOCTYPE html>
<html>
<head>
    <title>JSSample</title>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
</head>
<body>

<script type="text/javascript">
    $(function() {
        var params = {
            // Request parameters
        };
      
        $.ajax({
            url: "https://westus.api.cognitive.microsoft.com/qnamaker/v2.0/knowledgebases/{knowledgeBaseID}/train?" + $.param(params),
            beforeSend: function(xhrObj){
                // Request headers
                xhrObj.setRequestHeader("Content-Type","application/json");
                xhrObj.setRequestHeader("Ocp-Apim-Subscription-Key","{subscription key}");
            },
            type: "PATCH",
            // Request body
            data: "{body}",
        })
        .done(function(data) {
            alert("success");
        })
        .fail(function() {
            alert("error");
        });
    });
</script>
</body>
</html>
</details>
Regards,
Francisco

**Comment by jack12171992** [comment]
'use strict';
var request = require('request');

module.exports = function(session, args, next){
	session.sendTyping();
    var question = session.message.text;
	var bodyText = JSON.stringify({question: question});
	var url = `https://westus.api.cognitive.microsoft.com/qnamaker/v4.0/knowledgebases/${process.env.QnAKnowledgebaseId}/generateAnswer`;
	// console.log(url);
	request.post(url, {body: bodyText}, (err, code, body) => {
		if(err){
			console.log(err);
			session.endConversation("Something is wrong!");
		}else{
			var response = JSON.parse(body);
			console.log(response);
            if(response.score > 50) {
                session.endConversation(response.answer);
            } else if (response.score > 0) {
                session.send(`I'm not sure if this is right...`);
                session.endConversation(response.answer);
            } else {
                session.endConversation(`I don't have that answer.`);
            }
		}
	}).setHeader('Ocp-Apim-Subscription-Key', process.env.QnASubscriptionKey);
};





This is my code, but I also get the 
{ error: 
   { code: 'ResourceNotFound',
     message: 'The requested resource was not found.' } }

**Comment by fanidamj** [comment]
Can you please let us know if the issue still persists?

**Comment by dasUtsav** [comment]
Yes, this issue is still present

**Comment by JasonSowers** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
