### ISSUE TITLE
Posting a message to 1:1 guest user on MSTeams

### ISSUE THREAD

**Issue by viperfx** [Microsoft/BotBuilder#4286]
## Bot Info
* SDK Platform: REST
* SDK Version: 
* Active Channels: MSTeams
* Deployment Environment: Azure Bot Service

## Issue Description
Hi, 

I currently have a bot in the app store for MSTeams and I am making use of the REST API for communication. 

I am currently having trouble sending 1:1 messages from the bot to a guest user on MSTeams. Is this a known issue?

URL: https://smba.trafficmanager.net/emea-client-ss.msg/v3/conversations

Payload Data:
{"channelData": {"tenant": {"id": "392167e9-1639-4f8d-870d-25267fb585cb"}}, "bot": {"id": "28:14510476-fa9d-4dad-add9-aa5975a60a8b", "name": "ScrumGenius"}, "members": [{"id": "29:11a4g-GNXjVHbCWXdcutBge3gsT_PSWVo3uY5ioa9dlXZ82xWaPLFN5mJVLVWQM4tI51LcjjP5ff2mQvqZ5fdDg"}], "isGroup": false}

Response: 
{"error": {"message": "Failure due to: AclCheckFailed.", "code": "ServiceError"}}

I can provide more context and request/payload data if debugging further is needed.

**Comment by FranciscoPonceGomez** [comment]
Hi viperfx,

Does your guest have an Azure Active Directory account or is she an external guest?

Francisco

**Comment by viperfx** [comment]
I believe MSTeams must be in Azure Active Directory or Office 365 account. What is an external guest?

**Comment by FranciscoPonceGomez** [comment]
SInce a couple weeks ago, MSTeams allows guests with other accounts like gmail to participate in messages.

Is the bot the one that initiates the conversation?
Currently bots cannot initiate the first message in a conversation (what we call proactive messages) but MS is working on fixing that now.

**Comment by fanidamj** [comment]
Closing the issue assuming it as resolved. Please reopen a new issue if it still persists.
