### ISSUE TITLE
Where can I post issues about the REST API?

### ISSUE THREAD

**Issue by viperfx** [Microsoft/BotBuilder#4287]
Hi

I am having recent stability issues with the REST API for MSTeams. Every now and then I see errors such as 
```

{
u'error': {
u'code': u'ServiceError', 
u'message': u'Failure due to: AclCheckFailed.'
}
}
```

```
{
u'error': {
u'code': u'ServiceError', 
u'message': u'You do not have sufficient privileges to execute this operation.'
}
}
```

Please can you advice on how to contact the right people/devs at MSTeams to ask for help with these issues?

**Comment by FranciscoPonceGomez** [comment]
this seems like the same issue in https://github.com/Microsoft/BotBuilder/issues/4286
Can you please copy this information in the other post?
