### ISSUE TITLE
can I use nodejs part to connect to facebook?

### ISSUE THREAD

**Issue by vinnitu** [Microsoft/BotBuilder#429]
any example?

**Comment by Stevenic** [comment]
we're going to have an example of that coming shortly (within a week or two)

**Comment by andrew-makarenko** [comment]
@vinnitu Here is an FB bot connector https://www.npmjs.com/package/botbuilder-facebook

**Comment by v-thgratMSGit** [comment]
Closing this issue. Thanks!
