### ISSUE TITLE
Alpha version of 4.0.0 ... and docs or samples?

### ISSUE THREAD

**Issue by LoungeFlyZ** [Microsoft/BotBuilder#4290]
Noticed there is an alpha out for 4.0! ... yay!

https://www.nuget.org/packages/Microsoft.Bot.Builder/4.0.0-alpha20180221

Is there any getting started materials, docs or sample projects that we could take a look at to help see where 4.0 is heading?

PS: please don't remove it :)

**Comment by JasonSowers** [comment]
You can fine the v4.0 repo here in which there are samples https://github.com/Microsoft/BotBuilder-dotnet This SDK is a work in progress and is changing constantly.

**Comment by LoungeFlyZ** [comment]
Thanks Jason, this is really great news. Congrats and i look forward to looking into v4.

**Comment by vishwacsena** [comment]
V4 preview docs can be found [here](https://docs.microsoft.com/en-us/azure/bot-service/?view=azure-bot-service-4.0). 

Here are the individual repos - [C#](https://github.com/microsoft/botbuilder-dotnet), [JS](https://github.com/microsoft/botbuilder-js), [Python](https://github.com/microsoft/botbuilder-python), [Java](https://github.com/microsoft/botbuilder-java)
