### ISSUE TITLE
skype bot not working

### ISSUE THREAD

**Issue by 24madaeve** [Microsoft/BotBuilder#4294]
## Bot Info
* SDK Platform: Node.js
* SDK Version: 
* Active Channels: Skype, Direct Line
* Deployment Environment: Azure Bot Service, Azure App Service, local development with Emulator

## Issue Description
my bot on skype suddenly stops replying and after some time it itself starts replying. right now its down

i am getting following error when i send a new message:

POST https://client-s.gateway.messenger.live.com/v1/users/ME/conversations/28:21e02d8b-1daf-4e15-8217-8f4dd8279846/messages 400 (Bad Request)

app id is 21e02d8b-1daf-4e15-8217-8f4dd8279846

{errorCode: 205, message: "One or more of the user ids provided is not valid."}
errorCode
:
205
message
:
"One or more of the user ids provided is not valid."

**Comment by EricDahlvang** [comment]
Changes in the portal can sometimes take up to 20 minutes to propagate to Skype.  Are you still experiencing this issue after waiting for 20 minutes following publishing or configuration changes?

**Comment by EricDahlvang** [comment]
Closing due to lack of response.
