### ISSUE TITLE
how to avoid call twice recognizer when both using `bot.recognizer(recognizer)` and `new builder.IntentDialog({recognizers: [recognizer]})` 

### ISSUE THREAD

**Issue by lijiarui** [Microsoft/BotBuilder#4297]
## Bot Info
* SDK Platform: 
Node.js
* SDK Version: 
3.12.0
* Active Channels: 
none
* Deployment Environment: 
none
### Question:
How to avoid call twice recognizer when both using `bot.recognizer(recognizer)` and `new builder.IntentDialog({recognizers: [recognizer]})` 

## Code Example

```ts
let bot = new builder.UniversalBot(connector)
bot.recognizer(recognizer)

bot.dialog('FlightBookDialog', [
  function (session, args, next) {
    ...
    session.beginDialog('testPrompt', {})
}
]).triggerAction({
    matches:       ['startDialog'],
})

bot.dialog('testPrompt',  testPrompt)
```
the `testPrompt` file as follows
```ts
export const testPrompt = new builder.IntentDialog({recognizers: [recognizer]})

  .onBegin(function (session, args) {
    session.dialogData.retryPrompt = args.retryPrompt || 'say again'
    session.send(args.prompt || 'when to go')
  })

  .matches('ask', function(session, args) {
    .....
  })

  .onDefault(function (session, args) {
      session.send(session.dialogData.retryPrompt)
  })
```

## Questions

When user message matches intent `startDialog`, it will jump into `testPrompt`, but when it jumps into testPrompt, it will call recognizers again, I just want to call recognizers once instead of twice. How can I do this?

**Comment by stevengum97** [comment]
We normally recommend to either plug the recognizers into the bot _or_ to plug the recognizers into an IntentDialog, but not both. Is there a reason you need to do both? Are you using different LUIS applications  for each recognizer?

**Comment by lijiarui** [comment]
Thanks for your reply.

1. The two recognizer is the same one and using the same APP.
2. Yes, I also think the reason is both `plug the recognizers into the bot` and `plug the recognizers into an IntendDialog`, I should do it in one way.  But I don't know how to do it.

The reason why I  `plug the recognizers into the bot` because I need a waterfall.
The reason why I  `plug the recognizers into an IntendDialog` because I need to custom a prompt for the bot waterfall.

Could you help me to modify the code to just use one kind?  I need some suggestion, thanks!

**Comment by lijiarui** [comment]
Update, I think I can add args when matches testIntent in testPrompt dialog to avoid the following error, but I have another question:

How can I add a function list (waterfall) when in rootDialog, while using one function in testPrompt? All this depends on args..

Something like this:
`rootDialog`
```ts
.matches('startDialog', [
function one(){},
function two(){},
]
```

in `testPrompt` 
```ts
.matches('startDialog', 
function one(session, args){
...
},

```

**Comment by lijiarui** [comment]
I think I fix this in a strange way... 

If you have any good suggestion, please let me know, thanks!

**Comment by stevengum97** [comment]
Sorry for the delay! You should be able to pass in a second parameter to your waterfall without running into any problems, this second parameter would be called args or results depending on the waterfall step. Is the following snippet similar to what you ended up doing?

```js
intents.matches('startDialog', [
  function (session, args, next) { ... },
  function (session, results, next) { ... },
  function (session, results) { ... }
]
```

**Comment by lijiarui** [comment]
yes, something like this. And when I change all my code, it seems not that strange now, thanks!
