### ISSUE TITLE
[Skype] bot is in review for long

### ISSUE THREAD

**Issue by RishabhTayal** [Microsoft/BotBuilder#4298]
I have submitted my bot for review. Haven't gotten any response or email from Microsoft yet. Typically how long does it take for review?

Microsoft App ID: `78e0cbae-6abc-4291-aba7-6c2ed1bab0f6`

**Comment by JasonSowers** [comment]
I have sent an email to the skype team asking for details about the review of these bots.

**Comment by JasonSowers** [comment]
feedback from skype:

78e0cbae-6abc-4291-aba7-6c2ed1bab0f6
Please update the following for your bot : 
1.	Your bot must have links to a valid Privacy Policy and Terms of Use.
2.	Bot avatar image with non-black and non-white background color. 
3.	When a user adds the bot as a contact, the bot must automatically display a welcome message. This increases user engagement and guides the user to success.
4.	Display a Help screen when receiving unknown commands.  
Once you have addressed these issues please resubmit the bot again for review
  
  
7792dce2-616d-466e-a2d9-bcadcb22dde3
Please update the following for your bot : 
1.	Bot avatar image with non-black and non-white background color- bot having a white background won’t be visible in some of the skype clients.
Once you have addressed this issues please resubmit the bot again for review

**Comment by riccardo91** [comment]
@JasonSowers 
the image for bot has been changed
7792dce2-616d-466e-a2d9-bcadcb22dde3

**Comment by RishabhTayal** [comment]
@JasonSowers I have updated my app with the required changes. Please review again.

**Comment by JasonSowers** [comment]
@riccardo91 @RishabhTayal I do not actually review these.  It is the Skype team that does Skype bot reviews. I or anyone on the bot framework team is in no way involved in the review process or has any means to review your Skype bots.  All we can do is ask them for status.

**Comment by RishabhTayal** [comment]
@JasonSowers I understand. However since there is no other communication channel with the bot review team, we are forced to reach out to you through Github. Thanks for your support.

Would appreciate if you could ask the team to review again.

**Comment by JasonSowers** [comment]
I have sent a follow-up email and am awaiting a response.  We are happy to help, I just wanted to make it clear that we were not involved in the review process.

**Comment by RishabhTayal** [comment]
@JasonSowers Got it. Thanks.

**Comment by JasonSowers** [comment]
@riccardo91 
7792dce2-616d-466e-a2d9-bcadcb22dde3
1.	Works fine and I will approve and publish the by EOD tomorrow (Tuesday)

@RishabhTayal 
78e0cbae-6abc-4291-aba7-6c2ed1bab0f6
1.	The bot repeats whatever I type in (see attached image), Is there any menu I can use to interact and test the bot
2.	If there is no menu and that’s the main functionality of the bot, then the customer need to implement some functionality for the bot – A bot should have some valid uses cases for the customers to use it productively.

**Comment by RishabhTayal** [comment]
@JasonSowers I have updated the bot instructions.

**Comment by JasonSowers** [comment]
@RishabhTayal 

Please forward the following review to the developer,
1.	Please add a description about what the bot does on the bot profile page.
2.	Still the functionality of the bot is not clear, We get a link when a message is typed. The link is not working.
Please update the bot fixing these issues.

**Comment by RishabhTayal** [comment]
@JasonSowers I have added description in the bot profile page. Hopefully that will explain what exactly the bot does.

**Comment by RishabhTayal** [comment]
@JasonSowers any updates?

**Comment by RishabhTayal** [comment]
I am still waiting for the review update. No response from Skype team.

**Comment by JasonSowers** [comment]
Your bot will be approved by end of day today

**Comment by RishabhTayal** [comment]
Thanks.

**Comment by RishabhTayal** [comment]
@JasonSowers I can see on portal the bot is approved. However I don't see it the bot search result in Skype app. How much time does it usually take to show up?

**Comment by SivaKarthickb** [comment]
> I have sent an email to the skype team asking for details about the review of these bots.

@JasonSowers my bot has been in review for a while, could you please communicate with the review team and let me know the status.

Thanks in advance!

My APP ID: 971b3331-1d1e-44c0-b1bd-510d2c56e8ef
