### ISSUE TITLE
[Feature Request] Prompt choice with images

### ISSUE THREAD

**Issue by Kartik1607** [Microsoft/BotBuilder#4299]
I am trying to make a feedback dialog. As a current solution we send a keyword from bot to our custom directline webpage. The page intercepts the keyword and shows the form like this ![Current Form](https://imgur.com/X2z4q7V.png)

But this approach limits the bot to a single platform and adds a dependency to Directline. 

As a second approach I tried to implement the same using an adaptive card. This is when we ran into some of shortcomings.

1. How do we show images that change when selected? For instance when a user clicks a rating, we would like to update the same image.  Currently the bot can send an action, and we can find out the rating clicked but there was no way to notify the user for same on frontend.
2. Each image needs to have a Action to implement it. We now have an additional task of handling action clicked on image and on submit button. An updated choiceset API would be optimal for this use case.

**Comment by Kartik1607** [comment]
[Update] To handle the situation gracefully, I broke the flow into 2 parts. First for getting the rating. Then, handle the comments totally separately.

**Comment by JasonSowers** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
