### ISSUE TITLE
IDialogStack.Call(IDialog child, ResumeAfter<R> resume) throws serialization exception when receiving lambda expression as ResumeAfter<R> argument

### ISSUE THREAD

**Issue by celper** [Microsoft/BotBuilder#43]
If you pass an anonymous function to the ResumeAfter-parameter of the IDialogStack.Call()-method, you will receive a serialization exception when the dialog is created at runtime.

This code snippet throws the error:
```
context.Call<bool>(pongDialog, async (ctx, result) =>
{
	var r = await result;
	await context.PostAsync(string.Format("Exited pong dialog with result: {0}", r));
	context.Wait(MessageReceivedAsync);
});
```

(The error isn't a big deal. But it can be quite irritating when someone (like me:-)) starts playing arround with the framework.)

This works:
```
context.Call<bool>(pongDialog, AfterPongAsync);

private async Task AfterPongAsync(IDialogContext context, IAwaitable<bool> result)
{
	var r = await result;
	await context.PostAsync(string.Format("PONG: Exited pong dialog with result: {0}", r));
	context.Wait(MessageReceivedAsync);
}
```

Stacktrace:
[stacktrace.txt](https://github.com/Microsoft/BotBuilder/files/201320/stacktrace.txt)

Version:
"Microsoft.Bcl" version="1.1.10" targetFramework="net46" 
"Microsoft.Bcl.Build" version="1.0.21" targetFramework="net46" 
"Microsoft.Bot.Builder" version="1.0.0.0" targetFramework="net46" 
"Microsoft.Bot.Connector" version="1.0.0.0" targetFramework="net46"

**Comment by willportnoy** [comment]
Initially, we had implemented a reflection-based serialization surrogate for types (like anonymous functions) that were not serializable by default.  However, we found it very easy to end up serializing way more than intended due to the environment capture of the closure, so we disabled it by default.  I'll look into providing a method in the next version to enable it for advanced users.

**Comment by celper** [comment]
Thx.

**Comment by willportnoy** [comment]
We've published an updated nuget that allows the usage of the reflection-based serialization surrogate, in the event that your anonymous methods capture variables from the outer scope.
