### ISSUE TITLE
Emulator stopped working, no process using 9000 port.

### ISSUE THREAD

**Issue by tkbox9** [Microsoft/BotBuilder#430]
Few days ago the emulator stopped working. I'm using a VMware.  

Microsoft Windows 10 Enterprise (10.0.10240 Build 10240). Also, I ran a netstat but nothing was blocking the port and no policy changes in my firewall. 

Basically, I'm stuck with Emulator stopped working,

[debug]
An unhandled exception of type 'System.NullReferenceException' occurred in Microsoft.Bot.Connector.Emulator.Core.dll
Additional information: Object reference not set to an instance of an object

Any ideas how to solve it? @tomlm 

Thanks.

**Comment by tkbox9** [comment]
Anyone?

**Comment by pihai** [comment]
I have the same problem. Also no other process listening on port 9000. Temporarily I came up with the following workaround:

- Locate the exe in the AppData Local folder. In my case it was under: %userprofile%\AppData\Local\Apps\2.0\6W3EO1N9.EDP\QTT55V0Q.1BA\botf..tion_c3bce3770c238a49_0001.0000_3493c9887d9128e9
- Or just search for “Bot Framework Emulator.exe”
- Run the exe as admin

This sort of works for me for now. But I have no clue what is going on. Hope this helps.

**Comment by tkbox9** [comment]
@pihai Many thanks. It works when running as admin.

**Comment by tomlm** [comment]
v70 was just pushed and will delete bad file if it can't parse it, as well as allow you set the port. (NOTE: If you change the port you will need to change your code to use an alternate port)

**Comment by fuenfhausen** [comment]
I have the same problem as @tkbox9 and @pihai .  When I install or start the emulator, it immediately flashes the "stopped working" error dialog and dies.

I tried the suggestion of running the .exe as admin, but no luck.  Tried unistalling and reinstalling several times.  Any suggestions?
