### ISSUE TITLE
LUIS datetime issue after daylight saving ended.

### ISSUE THREAD

**Issue by rjgmail88** [Microsoft/BotBuilder#4304]
## Bot Info
* SDK Platform: Node.js 
* Active Channels:  MS Teams, Cortana
* Deployment Environment: Azure Bot Service

## Issue Description
Until Friday 9th March my LUIS model was correctly returning dateTime value with type builtin.datetimeV2.datetime. Ex: If I say 'NOW' it will actually give time and date value for current time in (CST). On Sat. March 10 when daylight saving ended clocks moved 1 hr ahead. So now if I run same query with LUIS it still give timeDate as if daylight saving was not ended. Ex: for now it gives 1 HR lesser than current hour. I am not sure where I can fix this. Is there any param I need to have ?

## Code Example
LUIS entities data for the query "find a meeting room now" where now is an entity type builtin.datetimeV2.datetime
```
  "entities": [
    {
      "entity": "now",
      "type": "builtin.datetimeV2.datetime",
      "startIndex": 12,
      "endIndex": 14,
      "resolution": {
        "values": [
          {
            "timex": "PRESENT_REF",
            "type": "datetime",
            "value": "2018-03-12 10:56:45"
          }
        ]
```

## Expected Behavior
Above value should be  "value": "2018-03-12 11:56:45"
Can I expect LUIS to return updated time as per daylight savings updates ?

## Actual Results
builtin.datetimeV2.datetime still returns CST time as per daylight savings. It is still running 1hr behind. Ex: if CST now is 11pm luis is still returning 10pm for NOW. This would have been true untill friday 9th March.

**Comment by tellarin** [comment]
@rjgmail88 in which region is the app published and what's the selected 'Timezone' setting for it when publishing to production?

**Comment by rjgmail88** [comment]
LUIS app is published in North America Region. The Timezone setting is defaulting to (GMT) Western Europe Time London even though I select Central Time US/Canada and publish.

**Comment by FranciscoPonceGomez** [comment]
By default LUIS resolves datetimes using UTC time. So “now” at this moment returns something like 

```
{
    "timex": "PRESENT_REF",
    "type": "datetime",
    "value": "2018-03-15 03:49:46"
}
```

If you need resolution in a specific timezone, you can use a query parameter named timezoneOffset, that takes a time offset in minutes to be used to compute resolution.
The default offset value is 0. You test it by adding the parameter to a query? For example: “&timezoneOffset=480&q=I%20want%20to%20know%20the%20time%20now”.

Let me know if that works.

**Comment by rjgmail88** [comment]
Yes, I did add timezoneOffset=-360 to my url. But still response is as follows which is 1 hr lesser than local CST. Following shows time 2018-03-16 14:22:50 for NOW it actually 15:22:50. 
As mentioned in title of this thread all this used to work before daylight saving ended. I haven't modified anything. 
```
{
      "entity": "now",
      "type": "builtin.datetimeV2.datetime",
      "startIndex": 12,
      "endIndex": 14,
      "resolution": {
        "values": [
          {
            "timex": "PRESENT_REF",
            "type": "datetime",
            "value": "2018-03-16 14:22:50"
          }
        ]
      }
```
```
https://westus.api.cognitive.microsoft.com/luis/v2.0/apps/{key}?subscription-key={key}&timezoneOffset=-360&verbose=true&q=find a room now
```

**Comment by FranciscoPonceGomez** [comment]
The timezoneOffset is always relative to UTC DateTime. The issue is that after the daylight saving, the actual offset between CST & UTC became 5 hours instead of 6, while the user’s code still uses a 6-hour offset (-360 minutes as you communicated below).

This is not a bug on LUIS, we ask our customers to give the offset relative to UTC DateTime.
A good solution could be to dynamically calculate the offset, for example:
1)	Get the datetime of your target zone
2)	Get UTC DateTime
3)	Subtract them and pass that difference to LUIS in minutes

Example C# code snippet that we will be adding to our documentation:

```csharp
TimeZoneInfo targetZone = TimeZoneInfo.FindSystemTimeZoneById("Central Standard Time");
DateTime utcDatetime = DateTime.UtcNow;
DateTime cstDatetime = TimeZoneInfo.ConvertTimeFromUtc(utcDatetime, targetZone);
int offset = (int)((cstDatetime - utcDatetime).TotalMinutes);
```

**Comment by rjgmail88** [comment]
Thank you.
