### ISSUE TITLE
[Node.js SDK, Teams] NSP check fails

### ISSUE THREAD

**Issue by dekpient** [Microsoft/BotBuilder#4305]
## Bot Info
* SDK Platform: Node.js
* SDK Version: 3.14.0
* Active Channels: MS Teams
* Deployment Environment: AWS Lambda

## Issue Description
Node `botbuilder` pulls in an older version of `jsonwebtoken` which eventually pulls in a version of `hoek` with [a vulnerability](https://nodesecurity.io/advisories/566).

## Code Example
Excerpt from `package.json`:
```
  "devDependencies": {
    ....
    "nsp": "^3.2.1",
    ....
  },
  "dependencies": {
    "bluebird": "^3.5.0",
    "botbuilder": "^3.14.0",
    "botbuilder-aws-lambda": "^1.0.2",
    "lodash": "^4.2.0"
  },
```

## Reproduction Steps
1. Depends on the latest version of `botbuilder` and `nsp`
2. Run `npm install`
3. Run `nsp check`

## Expected Behavior
The check passes with no vulnerability found.

## Actual Results
The check fails with the following output:
```
┌────────────┬────────────────────────────────────────────────────────────────────┐
│            │ Prototype pollution attack                                         │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Name       │ hoek                                                               │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ CVSS       │ 4 (Medium)                                                         │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Installed  │ 2.16.3                                                             │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Vulnerable │ <= 4.2.0 || >= 5.0.0 < 5.0.3                                       │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Patched    │ > 4.2.0 < 5.0.0 || >= 5.0.3                                        │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Path       │ my-bot@0.1.0 > botbuilder@3.14.0 > jsonwebtoken@7.4.3 >            │
│            │ joi@6.10.1 > hoek@2.16.3                                           │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ More Info  │ https://nodesecurity.io/advisories/566                             │
└────────────┴────────────────────────────────────────────────────────────────────┘
```

Botbuilder-Teams is also affected. I've raised a seperate issue OfficeDev/BotBuilder-MicrosoftTeams#102.

**Comment by FranciscoPonceGomez** [comment]
Hi dekpient,

Thanks for bringing this up.
We have talked about the issue here https://github.com/Microsoft/BotBuilder/issues/4206
As I mentioned, we are most likely not vulnerable but are in the process of updating the references to use a newer version of the package.

Regards,
Francisco

**Comment by jcheung-xmatters** [comment]
Hello,  
I notice 3.15.0 was released without having jsonwebtoken updated to 8.x. Will this vulnerability be addressed soon? 

Thanks!

**Comment by JasonSowers** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
