### ISSUE TITLE
How to have a group conversation using Direct Line API

### ISSUE THREAD

**Issue by nirmalaagash** [Microsoft/BotBuilder#4309]
I am trying to create an application using REST API. 
 Is it possible to have a group conversation with the bot using Direct Line API. If it is so, help me how to approach this way of creating a group conversation!

Thanks,
Nirmal

**Comment by EricDahlvang** [comment]
Yes, you can have a group conversation using the DirectLine API.  One client in the group needs to create the conversation.  Then, other clients can send and receive messages using that same conversation id.  What code have you got so far?

**Comment by EricDahlvang** [comment]
Closing this issue due to no response.  If you require further assistance, please open a new issue or post questions on StackOverflow using the BotFramework tag: stackoverflow.com/questions/tagged/botframework
