### ISSUE TITLE
BotBuilder not returning facebook user details

### ISSUE THREAD

**Issue by ryanc200427** [Microsoft/BotBuilder#4310]
session.message.user.name is not returning the user name of the facebook user

i tried to console.log(session) and message.user has no data except user.id

this happens also to my other bot.. is this a botframework problem or facebook api problem?

![image](https://user-images.githubusercontent.com/35627445/37389893-fe00cab6-27a0-11e8-87cf-b983ddd9c279.png)

**Comment by amitbend** [comment]
Facebook bug, and it's already fixed.
please close the issue. 
https://developers.facebook.com/bugs/216019809144177/?ref=messenger_notif_bug_fixready&hc_location=ufi
