### ISSUE TITLE
How to get BotData in IActivityLogger.LogAsync method when returning response to user. 

### ISSUE THREAD

**Issue by deepumi** [Microsoft/BotBuilder#4313]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.14.0
* Active Channels: Webchat
* Deployment Environment: On-premise (Windows Server 2016 Standard)

## Issue Description
I am logging all conversation between user and bot  (request and response) through  IActivityLogger.LogAsync  method. And I do have some information in BotState stored using SQL server. I am able to read BotState data from request using DialogModule.BeginLifetimeScope. However, when return response I do see BotState object is empty / null. 

After debugging I noticed that IAddress object does not have same objects when sending response back to the user. How can I get bot state data when returning response. 

| Request (IAddress)  | Response (IAddress)  |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/554039/37416313-d49aac22-2783-11e8-8641-91d16f1bdd97.png)  | ![image](https://user-images.githubusercontent.com/554039/37416395-082eab10-2784-11e8-8196-8c87c770f469.png) |

```
internal sealed class ActivityLogger : IActivityLogger
{
	async Task IActivityLogger.LogAsync(IActivity activity)
	{
		try
		{
			var message = activity.AsMessageActivity(); 
                        if(message != null)
			{
                                using (var dialoge = new DialogModuleService(message))
				{
					//username is null when sending response back to user.
					var userName = await dialoge.GetValue("UserNameKey", BotStoreType.BotUserData, "default-user");
				}
			}
		}
		catch (Exception e) { }
	}
}

internal sealed class DialogModuleService : IDisposable
{
	private readonly ILifetimeScope _dialog;

	private readonly AddressKey _key;

	private bool disposedValue;

	internal DialogModuleService(IMessageActivity message)
	{
		_dialog = DialogModule.BeginLifetimeScope(Conversation.Container, message);

		_key = new AddressKey
		{
			BotId = message.Recipient.Id,
			ChannelId = message.ChannelId,
			UserId = message.From.Id,
			ConversationId = message.Conversation.Id,
			ServiceUrl = message.ServiceUrl
		};
	}

	internal async Task<T> GetValue<T>(string property, BotStoreType storeType, T defaultValue)
	{
		try
		{
			var botDataStore = _dialog.Resolve<IBotDataStore<BotData>>();
			var data = await botDataStore.LoadAsync(_key, storeType, CancellationToken.None);
			return data == null ? defaultValue : data.GetProperty<T>(property);
		}
		catch
		{
			return defaultValue;
		}
	}
 
	protected virtual void Dispose(bool disposing)
	{
		if (disposedValue) return;

		if (disposing)
		{
			_dialog?.Dispose();
		}

		disposedValue = true;
	}

	public void Dispose() => Dispose(true);
}

   public sealed class AddressKey : IAddress
    {
        public string BotId { get; set; }
        public string ChannelId { get; set; }
        public string ConversationId { get; set; }
        public string ServiceUrl { get; set; }
        public string UserId { get; set; }
    }
```

Would you please answer the following questions. 

## Question
1) How do I get BotState info when sending response back to user.
2) Is it possible to assign or sync UserId and BotId in Response same as request.

**Comment by JasonSowers** [comment]
Take a look at [this sample](https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/core-Middleware), It shows logging of activities going both to and from the bot in the output window. 
![image](https://user-images.githubusercontent.com/6301037/37493653-e8f5023c-2862-11e8-83c0-0ba25d194369.png)

**Comment by JasonSowers** [comment]
This happens because state is stored based on the user, not the bot.  I am looking into a solution for you.

**Comment by deepumi** [comment]
@JasonSowers Thanks. I will try your approach.

**Comment by deepumi** [comment]
Sorry @JasonSowers The above code does not return BotState  when sending response back to user.

NOTE  : I've tested in bot emulator.

**Comment by JasonSowers** [comment]
I will take a deeper look for you.

**Comment by JasonSowers** [comment]
In the emulator the bot Id is set by the emulator and not read from the web config.  make these changes to the code to make it work in the emulator as well:
```cs
        public DialogModuleService(IMessageActivity message)
        {
            _dialog = DialogModule.BeginLifetimeScope(Conversation.Container, message);
            if (message.From.Id.Contains(ConfigurationManager.AppSettings["BotId"]) || (message.ChannelId == ChannelIds.Emulator && message.From.Id != "default-user"))
            {
                _key = new AddressKey
                {
                    BotId = message.From.Id,
                    ChannelId = message.ChannelId,
                    UserId = message.Recipient.Id,
                    ConversationId = message.Conversation.Id,
                    ServiceUrl = message.ServiceUrl
                };
            }
            else
            {
                _key = new AddressKey
                {
                    BotId = message.Recipient.Id,
                    ChannelId = message.ChannelId,
                    UserId = message.From.Id,
                    ConversationId = message.Conversation.Id,
                    ServiceUrl = message.ServiceUrl
                };
            }

        }
```

**Comment by deepumi** [comment]
Thank you @JasonSowers I will try the above pattern and keep you posted.

**Comment by deepumi** [comment]
@JasonSowers Thanks.. this works in emulator. I can see now botstate data. However, I will leave the ticket open until I finish testing in web-chat interface. 

![image](https://user-images.githubusercontent.com/554039/37653352-00818d02-2c15-11e8-88a2-93936ef0a434.png)

Once again, thank you for your.

**Comment by JasonSowers** [comment]
@deepumi I'm going to close this issue, please open a new issue if you need further assistance

**Comment by deepumi** [comment]
@JasonSowers Sure, thank you!
