### ISSUE TITLE
Question - Skype bot not showing after approved

### ISSUE THREAD

**Issue by RishabhTayal** [Microsoft/BotBuilder#4314]
My Skype bot was approved but still doesn't show up in the Skype search results. 

How can I get the bot to show up in search results? I understand you can join the Skype bot using join.skype.com link but this doesn't let me add the bot to a group conversation. 

Really need help here.

**Comment by EricDahlvang** [comment]
Hi @RishabhTayal 

The ability to add to a group can be enabled in the skype configuration page:

![image](https://user-images.githubusercontent.com/11055362/37422608-c81fca8c-2778-11e8-85ab-3bd65039816d.png)

**Comment by RishabhTayal** [comment]
@EricDahlvang Thanks for clarifying.

 How can I get the bot to show up in search results?

**Comment by EricDahlvang** [comment]
@RishabhTayal I've escalated the skype bot directory search question.  I will get back to you.

**Comment by EricDahlvang** [comment]
Response:

> I approved his bot today morning only will publish it by EOD today. Once I publish it he can view his bot under the category he mentioned while building the bot.

**Comment by RishabhTayal** [comment]
@EricDahlvang Thanks for the response. So if I understand correctly, after the bot it 'approved' it needs to be 'published' in order for it to show up in Skype. And the current state of the bot is 'approved', not 'published'. Is that right?

**Comment by RishabhTayal** [comment]
If that's the case, it would be nice and helpful to show these possible states some where on Azure dashboard so the developers are not confused about their bot status.

**Comment by EricDahlvang** [comment]
I think the confusion here is that the bot approver let  you know the bot was approved before they published it to the directory.  The bot was approved just this morning.  The approver said they will add the bot to the directory before EOD.

**Comment by EricDahlvang** [comment]
That is correct.  If your bot does not show up in the directory by tomorrow, please let us know.

**Comment by RishabhTayal** [comment]
👍
