### ISSUE TITLE
Unity Direct Line interface returning [400] 'Missing Property, Invalid or missing activities in http body'

### ISSUE THREAD

**Issue by RarCeth** [Microsoft/BotBuilder#4317]
Creating Direct Line application for use with bot, started using https://github.com/tompaana/bot-direct-line-for-unity. I checked code, seems all good. 

Bot initializes, conversation starts, all in the green. Then, when sending message, bot returns;

BotResponse: [Event type: Error; Code: MissingProperty; Message: Invalid or missing activities in HTTP body]
UnityEngine.Debug:Log(Object)
GameManager:OnBotResponse(Object, BotResponseEventArgs) (at Assets/GameManager.cs:32)
<SendMessageCoroutine>c__Iterator1:MoveNext() (at Assets/bot-direct-line-for-unity-master/bot-direct-line-for-unity-master/BotDirectLine/BotDirectLineManager.cs:160)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

The coroutine used to  send message:
```
public IEnumerator SendMessageCoroutine(string conversationId, string fromId, string message, string fromName = null)
    {
        if (string.IsNullOrEmpty(conversationId))
        {
            throw new ArgumentException("Conversation ID cannot be null or empty");
        }

        if (IsInitialized)
        {
            Debug.Log("SendMessageCoroutine: " + conversationId + "; " + message);

            UnityWebRequest webRequest = CreateWebRequest(
                WebRequestMethods.Post,
                DirectLineConversationsApiUri
                + "/" + conversationId
                + "/" + DirectLineActivitiesApiUriPostfix,
                new MessageActivity(fromId, message, DirectLineChannelId, null, fromName).ToJsonString());
			

            yield return webRequest.Send();

            if (webRequest.isNetworkError)
            {
                Debug.Log("Web request failed: " + webRequest.error);
            }
            else
            {
                string responseAsString = webRequest.downloadHandler.text;

                if (!string.IsNullOrEmpty(responseAsString))
                {
                    //Debug.Log("Received response:\n" + responseAsString);
                    BotResponseEventArgs eventArgs = CreateBotResponseEventArgs(responseAsString);

                    if (BotResponse != null)
                    {
                        BotResponse.Invoke(this, eventArgs);
                    }
                }
                else
                {
                    Debug.Log("Received an empty response");
                }
            }
        }
        else
        {
            Debug.Log("Bot Direct Line manager is not initialized");
            yield return null;
        }
    }
```
## Expected Behaviour
Bot returns with response (In this case, a request for a yes or no answer). 

## Actual Results
Bot returns [400] error and fails.

**Comment by RarCeth** [comment]
Had a thought... does Direct Line support PromptDialog.Choice?

**Comment by RarCeth** [comment]
Adding ```
webRequest.SetRequestHeader("Authorization", "Bearer " + botSecret);
```
Makes the bot either come up with the same error, or "missing token/secret" depending on whether the space is there after "Bearer"

**Comment by stevengum97** [comment]
Cross linking to the external library: https://github.com/tompaana/bot-direct-line-for-unity/issues/1

**Comment by EricDahlvang** [comment]
Yes, DirectLine supports PromptDialog.Choice.

This repository is for BotBuilder issues and feature requests.  I've never personally used the library you've referenced.  @stevengum97 linked the issue you created in that repository.  Hopefully the author responds.  

You could also try asking your question on stackoverflow.com/questions/tagged/botframework
