### ISSUE TITLE
post message to Slack channel

### ISSUE THREAD

**Issue by ahmettaha** [Microsoft/BotBuilder#432]
Hello,

I want to broadcast announcements from users by posting a message to a public slack channel. Is this possible? How do I get the channel account for public slack channels so I can post messages?

Thanks.

**Comment by jameslew** [comment]
The only channels your bot can post to are the ones the user has invited you to; you should have some data from the BotAddedToConversation event.

We're looking at how we might enable developers to generically ask which conversations they've been invited to for a given channel or what the properties are for that channel, but haven't anything to announce yet.
