### ISSUE TITLE
Error enabling Cortana Channel

### ISSUE THREAD

**Issue by neetgupta7** [Microsoft/BotBuilder#4320]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.14
* Active Channels: cortana
* Deployment Environment: Azure App Service

## Issue Description
Hello 
I have registered a bot with app id as '2852e714-d996-48c6-bf3a-931fc1089341' and am trying to enable cortana channel for it . But I am continuously getting below error when i click 'Register' under Discovery and Management section of Cortana channel in Azure.
--------------------------------------------------------------------
Unable to save.
There was an error saving the channel:

Failed to create bot module. Trace Id : 6a42ef51-e116-41a9-bc0a-e25660365a20
--------------------------------------------------------------------
I have already created an organization inside the knowledge store as described [here](https://help.knowledge.store/tutorials_code_samples/bot_framework/index.html).

**Comment by neetgupta7** [comment]
As a workaround, create botlet with a same name (uniqueid and botletid) as used in bot channel registration directly in knowledge store.

**Comment by JasonSowers** [comment]
Please take a look at cortana's documentation and see if it helps you https://help.knowledge.store/getting_started/index.html
