### ISSUE TITLE
matching entity throwing InvalidCastException when using Custom List Entities in ActionBinding.

### ISSUE THREAD

**Issue by SunKyungCho** [Microsoft/BotBuilder#4323]
## Bot Info
* SDK Platform: C#
* Deployment Environment: local development with Emulator

## Issue Description

I'm working on a prototype app bot using the LUIS action binding. I use LUIS list type entity. There was a problem with that. This is very similar to Issue #139. But another solution is needed.

## Code Example

LuisActionResolver.cs (line :520~)
```csharp
    // Prioritize resolution
    if (matchingEntity != null)
    {
        var paramValue = matchingEntity.Resolution != null && matchingEntity.Resolution.Count > 0
                  ? matchingEntity.Resolution.First().Value
                  : matchingEntity.Entity;
       // paramValue is returned type 'System.Collections.Generic.List<object>'
        result &= AssignValue(action, property, paramValue);
     }
```
 paramValue is returned type 'System.Collections.Generic.List<object>'

LuisActionResolver.cs (line:413~)
```csharp
private static object SanitizeInputValue(Type targetType, object value)
        {
            object result = value;

            // handle case where input is JArray returned from LUIS
           if (value is JArray) // false.  because, it's not 'Newtonsoft.Json.Linq.JArray'
            {
                var arrayOfValues = value as JArray;

                if (targetType.IsArray)
                {
                    result = arrayOfValues.AsEnumerable<object>();
                }
                else
                {
                    if (arrayOfValues.Count > 1)
                    {
                        throw new FormatException("Cannot assign multiple values to single field");
                    }

                    result = arrayOfValues[0];
                }
            }

            return result; // type : '{System.Collections.Generic.List<object>} '
        }
```
so, `if (value is JArray)` this code in this section is false. because, `value` is not 'Newtonsoft.Json.Linq.JArray'. it's `System.Collections.Generic.List<object>`

LuisActionResolver.cs (line : 356~)
```csharp
   paramValue = SanitizeInputValue(type, paramValue);

   if (type.IsArray)
   {
        value = BuildArrayOfValues(action, property, type.GetElementType(), paramValue);
   }
   else if (type.IsEnum)
   {
        value = Enum.Parse(type, paramValue.ToString());
   }
   else
   {
        value = Convert.ChangeType(paramValue, type);  //Exception here.
        //Exception message : Object must implement IConvertible.
   }
```
`type` is `string` . `paramValue` is  '{System.Collections.Generic.List<object>} ' I think this should be type string.

## Reproduction Steps
1. Register the list type entity in LUIS.
2. Just match the list entity by example.

## Actual Results

Exception message : Object must implement IConvertible.

**Comment by fanidamj** [comment]
Can you please post the issue in [BotBuilder-CognitiveServices](https://github.com/Microsoft/BotBuilder-CognitiveServices/issues), as this is the right repo to get resolved.
