### ISSUE TITLE
bot don't answer in skype

### ISSUE THREAD

**Issue by Liora87** [Microsoft/BotBuilder#4325]
## Bot Info
SDK Platform: .Net Framework 4.6
SDK Version: 3.14
Active Channels: Web Chat, Cortana, Skype
Deployment Environment: Azure App Service>
https://join.skype.com/bot/7e69ff9e-6103-48e0-a42d-fd3583f454a0?add

## Issue Description
hi everyone, please help me. a made simply bot that check errors in message. it works good in BotFramework Emulator. But in skype and Test in web chat instead check the error you write "you said: ... (my message)"/

https://liorabot.azurewebsites.net/api/messages

please help, i'm breaking out.

**Comment by EricDahlvang** [comment]
There are some latency issues when enabling the skype channel.  Please try after 20 minutes.

If it still isn't working, change the messaging endpoint to something else, and change it back.

This is a known issue.  Apologies for the inconvenience.

**Comment by Liora87** [comment]
hi Eric, i wait, and change endpoint and change back, but it don't work.

**Comment by EricDahlvang** [comment]
Try adding the MSTeams channel

**Comment by Liora87** [comment]
hi, added the MSTeams/ there is no changes:


there is code of rootdialog/ it's simply.
private async Task MessageReceivedAsync(IDialogContext context, IAwaitable<object> result)
        {
            var activity = await result as Activity;

            var text = activity?.Text ?? string.Empty;
            var yandexSpeller = new Speller();

            var yandexSpellerResult = yandexSpeller.CheckText(text);

            var resultText = new System.Text.StringBuilder(text);

            if (yandexSpellerResult.Errors.Any())

            {
                var shift = 0;
                foreach (var error in yandexSpellerResult.Errors)
                {
                    resultText.Insert(error.Position + shift, "**");
                    resultText.Insert(error.Position + error.Length + shift + 2, "**");
                    resultText.Append($"\n\r**{error.Word}**:{error.Steer}");
                    shift += 4;

                }
            }
            await context.PostAsync(resultText.ToString());
            context.Wait(MessageReceivedAsync);
           
        }

**Comment by flash2048** [comment]
Hello.
Are you added your bot to your contact list in Skype?
Now I test bot and it work.
![image](https://user-images.githubusercontent.com/2403385/37551304-7b35d4f4-29ae-11e8-8423-1c218cc5b438.png)

**Comment by Liora87** [comment]
hi, yes of course. bot should write you if you sent message with error/
for example : "hallo" bot should answer **hello**

**Comment by Liora87** [comment]
now i'm change the code for most simply code - bot template.
bot must count letters in message and reply with number of letter.
 but it not work

![capture](https://user-images.githubusercontent.com/37437488/37553471-a0e4b4f4-29d1-11e8-9061-f8200a97e18c.PNG)

**Comment by Liora87** [comment]
hi everyone, i found something intresting 
when i published my bot in azure he change RootDialog with code that i made for EchoDialog.
why?????

**Comment by flash2048** [comment]
@Liora87 
Now your bot is disabled, I can't try use it.
Are you correct published it? What method used for publish?

**Comment by Liora87** [comment]
thank you every one!!!. it work
