### ISSUE TITLE
How To Connect Azure Bot Service channel cortana to windows desktop

### ISSUE THREAD

**Issue by febririzki461** [Microsoft/BotBuilder#4326]
## Bot Info
* SDK Platform: Node.js
* SDK Version: 
* Active Channels: Cortana
* Deployment Environment: Azure Bot Service

## Issue Description
i have problem bot service in azure, i create bot channel cortana and then i cannot see clik save ? do you know ?

## Reproduction Steps
1. create bot service ->function bot
2. click bot in dashboard -> click channel -> add cortana
3. status running but published is no

## Expected Behavior
I want connect cortana to my pc windows 10

## Actual Results
![pep2](https://user-images.githubusercontent.com/17137478/37564219-dcf4dba2-2ac3-11e8-8358-ae334d362a27.png)

![screenshot from 2018-03-18 12-25-57](https://user-images.githubusercontent.com/17137478/37564052-a56461c4-2ac0-11e8-8469-b76945cd137f.png)

**Comment by JasonSowers** [comment]
Please refer to Cortana's official walkthrough on creating a skill https://help.knowledge.store/getting_started/index.html let us know if that helps you.
