### ISSUE TITLE
bot.on('message' is not working

### ISSUE THREAD

**Issue by MiroValchev** [Microsoft/BotBuilder#433]
bot.on('message' is not working.

Quite a simple bug:

https://github.com/Microsoft/BotBuilder/blob/7827c3f64395fbdb84277bb5870c5f6fa637c29d/Node/src/bots/TextBot.ts#L84

vs 

https://github.com/Microsoft/BotBuilder/blob/2e846d283d21d152b53b058ec4de94c918dcb1d0/Node/src/bots/BotConnectorBot.ts#L268

type here is 'Message'

There's inconsistency in naming for events, i.e. some start with small letters and other with capital.

**Comment by Stevenic** [comment]
The bots map through the native events from the underlying services without modifying the case. So yes that's an issue but since every service is different not much we can do about that.

**Comment by MiroValchev** [comment]
I see. How about toLowerCase()? Would that be an improvement or not?

**Comment by Stevenic** [comment]
But that kind of reverses the problem. If you read other docs that have the event names with proper casing and you sue that then your events don't work the other way and I have to say you should have lowercased it.

Let me look around at what other libraries do case wise for events and maybe i'll go the lowercase route.

**Comment by v-thgratMSGit** [comment]
Closing this issue. Thanks!
