### ISSUE TITLE
custom multi-tenant authentication for Bot running in Service Fabric

### ISSUE THREAD

**Issue by rashanke2** [Microsoft/BotBuilder#4330]
## Bot Info
* SDK Platform: 
* SDK Version: 
* Active Channels: 
* Deployment Environment: 

## Issue Description

I am referring the link https://github.com/Microsoft/BotBuilder/issues/2258 to configure the custom bot authentication for my bot deployed in Service Fabric.

Here in the static constructor MessageController(), the credential details are getting fetched using "((ClaimsIdentity)HttpContext.Current.User.Identity).GetCredentialsFromClaims())".

While in context of Service Fabric HttpContext.Current is coming null, I think the reason seems to be https://stackoverflow.com/questions/19509672/why-is-httpcontext-current-null

So Could you please help me to figure out how can I initialize my container in service fabric (Stateless) to resolve the credentials during run time.

## Code Example

[BotAuthentication(CredentialProviderType = typeof(CredentialProvider))]
public class BotConnectorController : Controller
    {

        static BotConnectorController()
        {
            // Update the container to use the right MicorosftAppCredentials based on
            // Identity set by BotAuthentication
                var builder = new ContainerBuilder();

                builder.Register(c => ((ClaimsIdentity)System.Web.HttpContext.Current.User.Identity).GetCredentialsFromClaims())
                    .AsSelf()
                    .InstancePerLifetimeScope();
                builder.Update(Conversation.Container);
        }
        [HttpPost]
        [Route("incoming")]
        public async Task<HttpResponseMessage> HandleIncomingMessage([FromBody]Activity activity)
        {
            if (activity.Type == ActivityTypes.Message)
            {
                await Conversation.SendAsync(activity, () => new RootDialog());
            }
            else
            {
                await this.HandleSystemMessage(activity);
            }
            var response = new HttpResponseMessage(HttpStatusCode.Accepted);
            return response;
        }

## Reproduction Steps
1. Deployed a state service fabric cluster in C# using .NET 4.6.1
2. Create a bot as a web service 
3. Consume the referenced code to initialize the container

## Expected Behavior

I am expecting the HttpContext.Current would be having relevant information filled.

## Actual Results

HttpContext.Current is coming as NULL

**Comment by EricDahlvang** [comment]
I haven't personally deployed a bot on Service Fabric.  However, we do support Azure Functions so I think Service Fabric should also be possible.  Have you tried to use https://github.com/Microsoft/BotBuilder-Azure ?   In an Azure Functions Bot, authentication is done using the BotService class here: https://github.com/Microsoft/BotBuilder-Azure/blob/master/CSharp/Library/Microsoft.Bot.Builder.Azure/BotService.cs 

Within the function itself: 

```cs
public static async Task<object> Run(HttpRequestMessage req, TraceWriter log)
{
    log.Info($"Webhook was triggered!");

    // Initialize the azure bot
    using (BotService.Initialize())
    {
        // Deserialize the incoming activity
        string jsonContent = await req.Content.ReadAsStringAsync();
        var activity = JsonConvert.DeserializeObject<Activity>(jsonContent);
        
        // authenticate incoming request and add activity.ServiceUrl to MicrosoftAppCredentials.TrustedHostNames
        // if request is authenticated
        if (!await BotService.Authenticator.TryAuthenticateAsync(req, new [] {activity}, CancellationToken.None))
        {
            return BotAuthenticator.GenerateUnauthorizedResponse(req);
        }
        
        if (activity != null)
        {
            // one of these will have an interface and process it
            switch (activity.GetActivityType())
            {
                case ActivityTypes.Message:
                    await Conversation.SendAsync(activity, () => new EchoDialog());
                    break;
                case ActivityTypes.ConversationUpdate:
                    var client = new ConnectorClient(new Uri(activity.ServiceUrl));
                    IConversationUpdateActivity update = activity;
                    if (update.MembersAdded.Any())
                    {
                        var reply = activity.CreateReply();
                        var newMembers = update.MembersAdded?.Where(t => t.Id != activity.Recipient.Id);
                        foreach (var newMember in newMembers)
                        {
                            reply.Text = "Welcome";
                            if (!string.IsNullOrEmpty(newMember.Name))
                            {
                                reply.Text += $" {newMember.Name}";
                            }
                            reply.Text += "!";
                            await client.Conversations.ReplyToActivityAsync(reply);
                        }
                    }
                    break;
                case ActivityTypes.ContactRelationUpdate:
                case ActivityTypes.Typing:
                case ActivityTypes.DeleteUserData:
                case ActivityTypes.Ping:
                default:
                    log.Error($"Unknown activity type ignored: {activity.GetActivityType()}");
                    break;
            }
        }
        return req.CreateResponse(HttpStatusCode.Accepted);
    }    
}
```
