### ISSUE TITLE
[.Net SDK, Skype Web Control] Postback message not working in Skype Web Control

### ISSUE THREAD

**Issue by TheoSpyrou** [Microsoft/BotBuilder#4333]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.14.0.7
* Active Channels: Skype, Facebook Messenger, Web Chat
* Deployment Environment: Azure App Service

## Issue Description
I have a bot framework app in which I use the postback feature for some messages in order to send more details without appearing to the user. Everything works fine in Skype, but from Skype Web control messages are sent with only their title and not their value for postback. There is no ChannelData for that either.

The script I'm currently using is this one: [https://swc.cdn.skype.com/sdk/v1/sdk.min.js](https://swc.cdn.skype.com/sdk/v1/sdk.min.js)

## Reproduction Steps
1. Create a bot and configure it for Skype
2. Create and embed in site a Skype Web control from [https://latest-swx.cdn.skype.com/lwc/sdk/0.0.835/index-builder.html](https://latest-swx.cdn.skype.com/lwc/sdk/0.0.835/index-builder.html)
3. Send a message using postback

**Comment by fms-santos** [comment]
Hi, being the dialogAction() button just a postback with "?action" included, can you relate with my issue https://github.com/Microsoft/BotBuilder/issues/4210 ?

**Comment by fanidamj** [comment]
@brene Can you please look into this issue and assist.

**Comment by TheoSpyrou** [comment]
@fms-santos hi I think your issue is the same as mine. Also that issue seems to be non-platform relative as it appears both in node.js and .net

**Comment by fms-santos** [comment]
@TheoSpyrou  Indeed. The thing is, in my case, i do not want to show the response back to the user (like the imBack button does) so I'll wait for a fix. For now, I'm just using the Skype Channel and not the SWC version.

**Comment by fms-santos** [comment]
@TheoSpyrou did you find a fix for this issue?

**Comment by amitbend** [comment]
@brene @fanidamj I encountered this issue as well. any news?

**Comment by JasonSowers** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
