### ISSUE TITLE
LUIS API to get utterences

### ISSUE THREAD

**Issue by PriyankaBirajdar** [Microsoft/BotBuilder#4334]
## Issue Description
I want to get all Utterances of an intent by calling LUIS API. I am able to find LUIS API to get intents but how to get utterances?
https://westus.dev.cognitive.microsoft.com/docs/services/

**Comment by v-geberr** [comment]
Try this [api](https://westus.dev.cognitive.microsoft.com/docs/services/5890b47c39e2bb17b84a55ff/operations/5890b47c39e2bb052c5b9c0a). You have to filter on intent though.

**Comment by PriyankaBirajdar** [comment]
seems this is the only option to get utterances.
