### ISSUE TITLE
context forward and context call examples

### ISSUE THREAD

**Issue by ahmettaha** [Microsoft/BotBuilder#434]
Hello,

In the example, there is only an example about canceling a message stack. Can you please provide examples that will forward the message to a new dialog and also add a new dialog to the stack so that the next message is handled by the new dialog.

I have tried both

    this.stack.Call(new HowAreYouDialog(), GetDone());

    this.stack.Forward(new HowAreYouDialog(), GetDone(), item, CancellationToken.None);

and neither seemed to work.

**Comment by msft-shahins** [comment]
[This test case](https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Tests/Microsoft.Bot.Builder.Tests/DialogTaskTests.cs#L206) shows an example of using `context.Froward(...)` and [PizzaOrderDialog](https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Samples/PizzaBot/PizzaOrderDialog.cs#L34) has an example of the `cotenxt.Call(...)`.

**Comment by ahmettaha** [comment]
sorry, I forgot to mention, I'm trying to achieve this in a IScorable class in PostAsync method. Does it work the same? I am able to get it work elsewhere, but not in PostAsync.

**Comment by willportnoy** [comment]
IDialogStack.Forward should work in IScorable.PostAsync - what issues do you see?

**Comment by ahmettaha** [comment]
it doesnt forward the message. I have put a breakpoint in the HowAreYouDialog dialog, and it doesnt seem to move to there. it just ends execution. no exceptions neither

It would be great if you could also add two tests for forward and call.

thank you.

**Comment by willportnoy** [comment]
I added https://github.com/Microsoft/BotBuilder/commit/fd6deb01a155ded062d079e3f0bb078f68988e9f as an example - feel free to re-open this issue for further discussion.
