### ISSUE TITLE
How much wait between nuspec commit and package publish

### ISSUE THREAD

**Issue by srozga** [Microsoft/BotBuilder#4341]
We noticed a commit that indicate a memory leak that we believe we are consistently running into in our production deployment was fixed. https://github.com/Microsoft/BotBuilder/commit/aa5a37b7e6c2632fd6d960e2b8e8986f6dfc7e5b. Also noticed the nuspec was updated. https://github.com/Microsoft/BotBuilder/commit/aa5a37b7e6c2632fd6d960e2b8e8986f6dfc7e5b. Do you have a timeline of when this will be released? Is there some nuget repo we could get access to to test this without building the solution locally?

**Comment by JasonSowers** [comment]
We do not have an exact timeline for this. We are working on testing it before the release.  as for testing it now.  This is an open source repo and you are able to copy the code locally for testing and debugging at any point.  You can use any branch you would like as well.  You can easily remove the current NuGet packages and include the source code as outlined in [this blog post](https://blog.botframework.com/2017/07/03/debug-bot-builder-source/).

**Comment by JasonSowers** [comment]
We have pushed a new version of the SDK which includes a fix for this issue https://www.nuget.org/packages/Microsoft.Bot.Builder/3.14.1.1
