### ISSUE TITLE
[.Net SDK, Skype] bot dont answer in skype

### ISSUE THREAD

**Issue by Liora87** [Microsoft/BotBuilder#4342]
hi everyone, my bot don't answer me in Skype/
https://join.skype.com/bot/457852f5-7e05-4bdc-a875-fc562a5bab12?add

and in morrning every thing was write/

and in web chat it's work.

bot work with hebrow.

his wait for "היי" and then must aswer/
but however i cant sent a message (only emoje) in skype/
what it can be?

![2](https://user-images.githubusercontent.com/37437488/37663216-6b17ca7c-2c61-11e8-8c3b-aadc6341b54a.PNG)

**Comment by stevengum97** [comment]
Please provide more information (e.g. deployment type, SDK language and SDK version) and any relevant code for your bot.

**Comment by Liora87** [comment]
https://bot-mechirot.azurewebsites.net/api/messages

Bot-Mechirot
Application Id 
457852f5-7e05-4bdc-a875-fc562a5bab12

C#

**Comment by fanidamj** [comment]
Can you please let us know if the issue still persists?

**Comment by EricDahlvang** [comment]
Closing, no response.
