### ISSUE TITLE
Exception is missing intended information

### ISSUE THREAD

**Issue by tiloc** [Microsoft/BotBuilder#4344]
I am trying to create the localization resources for a FormFlow dialog using the RView tool. It crashes in the denoted line in FormBuilder.cs. Unfortunately, the very valuable information what is missing is not being output, as variable "missing" is a list, and the output is thus: 
System.Resources.MissingManifestResourceException: Missing resources **System.Collections.Generic.List`1[System.String]**

https://github.com/Microsoft/BotBuilder/blob/b7b2abbd089b0c0b91f367e4355743f7171dbc26/CSharp/Library/Microsoft.Bot.Builder/FormFlow/FormBuilder.cs#L102

**Comment by EricDahlvang** [comment]
@tiloc That should be changed to something like:

```cs
throw new MissingManifestResourceException($"Missing resources {string.Join(",", missing.ToArray() )}"); 
```

Do you care to submit a pull request?

**Comment by tiloc** [comment]
I am frankly a bit hesitant to submit pull requests. I did so over at the BotBuilder Cognitive Services repository and they have been hanging around since August 2017 now.
