### ISSUE TITLE
[.Net SDK] Is there a way to deal with multiple user messages (related to a same intention)?

### ISSUE THREAD

**Issue by WillRock19** [Microsoft/BotBuilder#4345]
## Bot Info
* SDK Platform: .NET
* SDK Version: Bot Builder version 3.12.2.4

## Issue Description

Hi there! I'm a beginner with BotBuilder, but didn't find nothing like this in my researches... is there a way to wait a few seconds aftera received some user message, so I can process a possible second message with the first one? 

Exemplifying:

Imagine that my user send a message "Do you have a white shirt?" then, in another message "with the superman logo" and, finally, in a third message "and buttons". When my bot receave these three messages, it will look for each one separately, not as one single question. Is there a way to wait a few seconds before start the processing, so I can receive other messages in the case user send's it separately?

Another example (that's already happenning): 

My user sends a message to bot "Hi, do you have shirts"
And then send another one with "?"

The first one will be answered normally, but the second one will return with a "Do not understand what '?' means" message.

So, is there a native way to wait a few seconds, gather all the user messages and use all of then as my logic demands, or I need to create my own custom service to do something like this?

**Comment by JasonSowers** [comment]
There are probably a number of different ways for you to handle this.  The framework is not set up to handle this out of the box though.  One way which I had suggested another time this question came up was to use a timer.  The basic idea would be this:
    
receive a message from the user
start a timer (let's say for 3 seconds)
Add the message text to an array (or concatenate it with `StringBuilder` or something)
another message is received (before the timer expires) 
restart timer
add the message text to an array
(continue this as needed)
if another message does not come in and the timer expires 
concatenate the messages together and set that string to the `Activity.text` 
proceed with your bot logic.

**Comment by himexia** [comment]
I'm trying to handle the same problem in node.js. I get the idea to set the timer and combine messages from same user together, but have little idea how this piece could fit into the sdk.

Should I customizer the listent() function in ChatConnect.js? Appreciate if you could provide more insight.

**Comment by JasonSowers** [comment]
@himexia you could modify the SDK code if you wanted, or you could just do what I suggested in the area of your bot you are normally receiving and processing messages.  This is going to require a custom solution of some sort since it is not something supported in botbuilder.

**Comment by himexia** [comment]
@JasonSowers thanks for the reply! Could you elaborate more about the method you suggested? 
As far as I learn about node.js SDK, the incoming/outgoing messages are handled by SDK function. That's why I asked about modifying the SDK.
Please correct me if I'm wrong, did you suggest that concatenate the message before passing it to the botbuilder?

**Comment by JasonSowers** [comment]
@himexia sorry for the delay, but yes that is exactly what I was suggesting.  Please open a new issue if you still need help.
