### ISSUE TITLE
Using Chain() inside Dialog makes my bot stop working

### ISSUE THREAD

**Issue by WillRock19** [Microsoft/BotBuilder#4346]
## Bot Info
* SDK Platform: .NET
* SDK Version: Bot Builder version 3.12.2.4

## Issue Description

Well, I'm learning about Bot Framework and ran into a doubt. Ive tried to use the joke Chain example that exists in Microsoft documentation (see it below)

![image](https://user-images.githubusercontent.com/6953687/37674589-00d874ea-2c52-11e8-80eb-9e64cc9bb282.png)

Ok, I've used it in my MessagesController to see how it works, and everything work as it would be expected (see it bellow):

![image](https://user-images.githubusercontent.com/6953687/37674635-1aecdf56-2c52-11e8-87e2-3ebbb0356f25.png)

But then, I've tried to use it inside a Dialog (see it below). The Dialog uses the Luis cognitive service so it can redirect intents from the user. When I trie to run this sample of code, nothing happens! Inside the bot framework emulator, i try to contact my bot, but the program does not run. It doesn't generate any kind of build error, but it gets just stuck. 

![image](https://user-images.githubusercontent.com/6953687/37674946-c0cec826-2c52-11e8-844b-1dfcd23ebc7b.png)

I've looked for how the Chain works, but didn't find anything that could explain why in the world it justo stopped working. Do tyou guys have any ideia of what might be happenning? The Chain cannot be used inside an Dialog?

(P.S. I've looked in sample codes, and all I could looking called chain from a Controller, not a dialog... so, maybe this is the problem?)

**Comment by JasonSowers** [comment]
Please post actual code and not screenshots.

**Comment by fanidamj** [comment]
Closing the issue assuming it as resolved. Please reopen a new issue if it still persists.
