### ISSUE TITLE
conservationUpdate not triggered when window close or send "user removed" event from emulator

### ISSUE THREAD

**Issue by chiayenhung** [Microsoft/BotBuilder#4348]
## Bot Info
* SDK Platform: Node.js
* SDK Version: 3.14.0
* Active Channels: Web Chat
* Deployment Environment: Azure Bot Service, local development with Emulator

## Issue Description
`conservationUpdate` not triggered when closing the chat window in Web Chat channel.

In emulator, `Send System Activity` -> `User removed` not triggered as well.

Is there any event will be triggered when chat window is closed.

## Reproduction Steps
1.
2.
3.

## Expected Behavior
Will trigger `conservationUpdate` when user removed.

## Actual Results
Not triggered in every case I tried

**Comment by JasonSowers** [comment]
There is no event that is triggered when the chat window is closed in the Bot Framework.

**Comment by chiayenhung** [comment]
How could we know if user left the chat?

**Comment by JasonSowers** [comment]
There is not a way to do this.  You could probably modify webchat to do what you want it to do.  Generally, conversations are persisted beyond the point of the user closing the window, when the user reopens the window the conversation is resumed.

**Comment by JasonSowers** [comment]
@chiayenhung  After talking to the team they offered some ideas. You may want to try to capture an [onBeforUndload](https://www.w3schools.com/jsref/event_onbeforeunload.asp) event on the front end.  Then in handling this event you can use [the backchannel](https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-backchannel) to send an event to your bot. A simple example taken from [this repo](https://github.com/insanediv/microsoft-bot-framework-webchat-custom-parameters#client-side-1):

Client side 
```javascript
window.onbeforeunload = function() {
    botConnection
        .postActivity({
            type: "endOfConversation",
            from: {
                id: params['userid']
            }
        })
        .subscribe(id => console.log("endOfConversation ack"));
};
```
Bot side
```javascript
bot.on('endOfConversation', function(event){
    var conversationId = event.address.conversation.id;
    delete conversationMap[conversationId];
});
```

**Comment by MatthiasGwiozda** [comment]
> @chiayenhung After talking to the team they offered some ideas. You may want to try to capture an [onBeforUndload](https://www.w3schools.com/jsref/event_onbeforeunload.asp) event on the front end. Then in handling this event you can use [the backchannel](https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-backchannel) to send an event to your bot. A simple example taken from [this repo](https://github.com/insanediv/microsoft-bot-framework-webchat-custom-parameters#client-side-1):
> 
> Client side
> 
> ```js
> window.onbeforeunload = function() {
>     botConnection
>         .postActivity({
>             type: "endOfConversation",
>             from: {
>                 id: params['userid']
>             }
>         })
>         .subscribe(id => console.log("endOfConversation ack"));
> };
> ```
> 
> Bot side
> 
> ```js
> bot.on('endOfConversation', function(event){
>     var conversationId = event.address.conversation.id;
>     delete conversationMap[conversationId];
> });
> ```

The problem with this solution is that if a user reloads the page, the event is triggered as well.

If the the bot saves the conversation, the conversation is not really "ended" because I can continue to talk with the bot after I have reloaded the page.

It depends on what you want to do with this event. But for me unfortunately this is very unhandy.
