### ISSUE TITLE
[c#] Luis Dialog causes a DOS (error 500) when a non-LuisIntent marked async function is part of the dialog class

### ISSUE THREAD

**Issue by mindcrash** [Microsoft/BotBuilder#435]
(Likely) easily reproducable by something like this:

```c#
public class SimpleDialog: LuisDialog<object>
{
   [LuisIntent("")]
   public async Task None(IDialogContext context, LuisResult result)
   {
     context.PostAsync("Nope");
     context.Wait(MessageReceived);
   }

  [LuisIntent("someIntent")]
  public async Task SomeIntent(IDialogContext context, LuisResult result)
  {
    context.PostAsync("Some Intent");
    context.Wait(MessageReceived);
  }

   async Task<string> IAmASampleToKillTheChatbot()
   {
     var text = await Task.FromResult("boom");
     return text;
   }
}
```

When you move the async helper function out of the Dialog everything works fine, but when in place it causes a internal server error. Could have something to do with the way async methods within the dialog are being resolved for a specific intent.

**Comment by willportnoy** [comment]
We have a test to validate that we handle methods that don't match the expected types:

https://github.com/Microsoft/BotBuilder/commit/ba25b18238a1ceda52924b2b435906cc162b57f3

Can you tell us the call stack of the failure?

**Comment by mindcrash** [comment]
For some reason it doesn't throw, just sends back this:

```js
{
    "error": {
        "code": "ServiceError",
        "message": "*Sorry, ThBot is having a problem responding right now.*",
        "statusCode": 500
    }
}
```

Maybe it has something to do with my debugger settings (e.g. Just My Code.). Will have to look into that for a bit though...

**Comment by willportnoy** [comment]
I added

            async Task<string> IAmASampleToKillTheChatbot()
            {
                throw new NotImplementedException();
            }

to our LuisTests.All_Handlers_Are_Found test and it passed fine - there must be something else.  I'll keep looking.

**Comment by willportnoy** [comment]
I've been unable to reproduce this issue - if it continues to be a problem, feel free to open a new issue and reference this one.
