### ISSUE TITLE
Best methods to implement DirectLine Api

### ISSUE THREAD

**Issue by varunreddycs** [Microsoft/BotBuilder#4350]
## Bot Info
* SDK Platform:.NET 
* SDK Version: 3.13.1
* Active Channels: Direct Line (Mobile App), Skype, Facebook Messenger
* Deployment Environment:  Azure Bot Service

## Issue Description
I am writing a Mobile Application which will interact with Bot using DirectLine Api. As on basis, what is the recommended interval we call Conversations.GetActivitiesAsync? Any best practices ?

**Comment by JasonSowers** [comment]
A good thing to do is mimic what Webchat does which is once a second.  Webchat is widely used so it is a good reference for you looking to use directline.  Also take a look the [DirectlineJS](https://github.com/Microsoft/BotFramework-DirectLineJS) repository.  There is also some samples in the [botbuilder-samples repository](https://github.com/Microsoft/BotBuilder-Samples).  This [sample](https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/core-DirectLine) is the base directline sample, and this [sample](https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/core-DirectLineWebSockets) uses websockets
