### ISSUE TITLE
Twilio SMS Channel: Bot Authenticator failed to authenticate incoming request

### ISSUE THREAD

**Issue by SatyaPavanKumar** [Microsoft/BotBuilder#4353]
Hi, I had created azure chat bot , registered bot framework and published in azure. I am trying to integrate chat bot with Twilio SMS channel. I had created account and bought mobile number in Twilio as a free trail account. I also added few numbers and verified in account. I configured SMS Messaging to TwiML App by creating  a new TWilML app with proper request URL (HTTP POST) in Twilio account. I have provided required details such as AccountSID, AuthToken ,Mobile number while enabling SMS channel in azure chat bot by referring below link.

https://docs.microsoft.com/en-us/bot-framework/channel-connect-twilio

But whenever i send message to twilio number from verified mobile number , i am getting below error message in twilio account console.

Error Details:

Error - 11200 : HTTP retrieval failure
401 Unauthorized: Bot Authenticator failed to authenticate incoming request.

With reference to below link, I would like to know how he/she integrated Twilio channel in chat bot. Pls. share code if possible . Did he/she used Messaging Service / TwiML App ? 

https://github.com/Microsoft/BotBuilder/issues/3500

**Did i missed any configuration in my chat bot?**

**Comment by EricDahlvang** [comment]
Which version of the BotBuilder sdk are you using?  Please try upgrading to the latest version, and let us know if that resolves your issue.

**Comment by microsoftly** [comment]
+1 I'm also having similar bugs

**Comment by microsoftly** [comment]
I'm getting a 403 Forbidden when hitting https://sms.botframework.com/api/sms

**Comment by EricDahlvang** [comment]
@microsoftly Which version of the Bot Builder SDK are you using?

**Comment by EricDahlvang** [comment]
Closing due to no response
