### ISSUE TITLE
Can not add an Image to herocard, it shows the following exception Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by waleedabuyahia** [Microsoft/BotBuilder#4354]
## Bot Info
SDK Platform .Net
Latest version 
Channel Emulator

Whenever you add image to herocard it breaks showing object reference null 

Sample code:

    HeroCard _myBotWelcomeCard = new HeroCard();
            _myBotWelcomeCard.Title = "Welcome to my Bot";
            _bpBotWelcomeCard.Text = "I am Bot Please let me know how can I help you?";
            CardImage _imageLogo = new CardImage(url: "Path", alt: null, tap: null);
            _myBotWelcomeCard.Images.Add(_imageLogo ); // it breaks in this line

**Comment by JasonSowers** [comment]
Using code similar to the [rich cards sample from the samples repo](https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/cards-RichCards)  it seems to work fine using SDK version 3.14.1 in the emulator.

![image](https://user-images.githubusercontent.com/6301037/37733916-df103b1c-2d06-11e8-80e8-2789c37d8cd9.png)

```cs
            var heroCard = new HeroCard
            {
                Title = "BotFramework Hero Card",
                Text = "Do you like nachos?",
                Images = new List<CardImage> { new CardImage("https://sec.ch9.ms/ch9/7ff5/e07cfef0-aa3b-40bb-9baa-7c9ef8ff7ff5/buildreactionbotframework_960.jpg") },
                Buttons = new List<CardAction> { new CardAction(ActionTypes.PostBack, "YES", value:"YES"), new CardAction(ActionTypes.PostBack, "NO", value:"NO") } 
            };
```

**Comment by waleedabuyahia** [comment]
Thank you it is solved, the only difference was in sample code you create new instance from the list, my code I add directly to the list with creating new instance, by the way it was working in the pervious SDK. Thank you
