### ISSUE TITLE
sendgrid issue in azure using web bot

### ISSUE THREAD

**Issue by shpsyte** [Microsoft/BotBuilder#4357]
## Bot Info
* SDK Platform: .NET
* Bot Builder: 3.14.0.7
* Active Channels:  Direct Line, Web Chat
* Deployment Environment: Azure Bot Service, 

## Issue Description
I'm using the sendgrid library so the bot can send email notifications.
Locally everything works, but when I deploy to the azure the Bot does not send the emails. I've already passed the fixed API key in the code, also to work to.
How to debug this?
Am I doing something wrong?

## Code Example
```csharp
private Task ExecuteEmailAsync(string nameCustomer,string subject, string from, string body, string replayto, string to, string templateId, string[] cc = null, string[] bcc = null)
        {
            var client = new SendGridClient("my_key_send_grid");
            var msg = new SendGridMessage()
            {
                From = new EmailAddress(from, "Ian da Isco Sistemas"),
                Subject = subject,
                // PlainTextContent = body,
                HtmlContent = string.Concat(HtmlEmailHeader, body, HtmlEmailFooter),
                ReplyTo = new EmailAddress(replayto),

            };
            msg.AddTo(new EmailAddress(to));
            msg.SetSubject(subject);

            return client.SendEmailAsync(msg);
}
```

I try
```csharp
      client.SendEmailAsync(msg).Wait();
```

If I use a smtp itself the email is send, but I want to use sendgrid.

I dont get any error....

**Comment by FranciscoPonceGomez** [comment]
Other users seem to be using sendgrid with no issues. Take a look at:
https://github.com/ankitbko/MeBot/blob/part4/MeBot/Internal/EmailSender.cs
https://ankitbko.github.io/2016/09/ChatBot-using-Microsoft-Bot-Framework-Part-4/

You can also try to capture the messages from your bot to sendgrid in your browser from the webchat test in Azure Portal.
![image](https://user-images.githubusercontent.com/16775093/37782621-93e60e8c-2db0-11e8-8ecb-aedf46f35e73.png)

**Comment by JasonSowers** [comment]
Here is a snippet from a bot that is deployed on Azure I run daily that runs with no issues. Hopefully, it helps you:

```cs
            var apiKey = ConfigurationManager.AppSettings["SendGrid"];
            var client = new SendGridClient(apiKey);
            var msg = new SendGridMessage();

            msg.SetFrom(new EmailAddress("BFSupportReports@Microsoft.com", "BFSupport"));

            var recipients = new List<EmailAddress>
            {
                new EmailAddress("Omitted", "Omitted"),
            };
            msg.AddTos(recipients);

            msg.SetSubject("Daily Report " + DateTime.Now.Date.ToString().Substring(0, 10));

            msg.AddContent(MimeType.Html, text);

            await client.SendEmailAsync(msg);
```

**Comment by shpsyte** [comment]
Tks, Works
