### ISSUE TITLE
Directline for tranquilcounty.com bot not working

### ISSUE THREAD

**Issue by kjsingla** [Microsoft/BotBuilder#4359]
## Bot Info
* SDK Platform: .Net
* SDK Version: 3.11
* Active Channels: Directline
* Deployment Environment: Azure registration. Deployed on an Azure VM,

## Issue Description
One of our bots deployed on tranquilcounty.com is not working. When we try testing in web chat in azure portal, its showing error "couldn't send". There were few errors (unauthorized) shown in directline channel too. It was working just fine few hours ago. Many other bots built exactly like this one are working fine. Check www.halcyonphoenix.com.

## Reproduction Steps
1. Check bot on tranquilcounty.com
2.
3.

## Expected Behavior
Messages should reach service deployed on azure VM.

## Actual Results
Bot not working. Messages couldn't be send.

**Comment by EricDahlvang** [comment]
I loaded the bot in a browser using:

https://www.kenyt.ai/botapp/BotChat/kenytchat.html?bot=Tranquil_County&key=M8VpS0Bnmo0.cwA.-_k.L9_FouobTDyye1020UZnwBFRdDLXW1XEPX-QfYeyJJ4&ref=http://tranquilcounty.com/

Console window shows:

> Failed to load resource: the server responded with a status of 429 (Included quantity of 10000 transactions has been exceeded. The quantity will reset on 2018-03-23T09:52:29.7783737.)

**Comment by kjsingla** [comment]
Thanks Eric. I have moved it to paid pricing model. Its working now. Thanks for debugging this. We will keep an eye on message count.
