### ISSUE TITLE
[Feature Request] Facebook Messenger Feature Requests

### ISSUE THREAD

**Issue by EricDahlvang** [Microsoft/BotBuilder#4360]
We are reviewing Facebook Messenger features and support.  We would like feedback from the community on which features would be most useful.  I've looked through the current Feature Requests on this repository, and compiled this list of what seems to be most requested:

~~Multiple Facebook page access tokens
https://github.com/Microsoft/BotBuilder/issues/1495~~ (implemented)

Show Facebook Webview 
https://github.com/Microsoft/BotBuilder/issues/2250

Add Channel: Workplace by Facebook
https://github.com/Microsoft/BotBuilder/issues/2821

Add support for Facebook Message Tags
https://github.com/Microsoft/BotBuilder/issues/2924

Support Facebook Chat Extensions
https://github.com/Microsoft/BotBuilder/issues/3385

Please let us know what Facebook Messenger features or functionality you would like to see in the Bot Builder sdk.

**Comment by hpksp** [comment]
@EricDahlvang I would vote for having Multiple Facebook page access tokens. In our case we want to link the same bot to different FB pages owned by different customers (Multi-tenant scenario). Thanks for asking our opinion :+1:

**Comment by amitbend** [comment]
I would ask for support to ref params, and special quick replies such as location, email, phone number etc.

**Comment by cove-ming** [comment]
We would like support for the Facebook handover protocol. We are able to able to pass thread control from the bot since it's just an HTTP call, but are unable to receive the `messaging_handovers` event via the Bot Connector. 

One solution apparently is to put a proxy between Facebook and Bot Connector to capture that event, but that's far less than ideal as it's added latency. 

https://developers.facebook.com/docs/messenger-platform/handover-protocol#handovers

**Comment by glasody** [comment]
We would love to see multiple page access tokens get implemented which would mean changes in the Bot connector also in azure. We recently ran into a problem trying to use the same bot for different pages. If this isn't implemented, we would have to create new fb apps, get then approved again and register new bot channels in azure.

**Comment by xjose97x** [comment]
I believe Facebook Webview would be a great feature.
The Spotify chatbot (in their facebook page) uses it heavily and provide a great user experience.

Thanks for asking our opinion @EricDahlvang  :+1:

**Comment by millimoose** [comment]
Subscribing a single bot application to an arbitrary number of pages for the same FB app is essential to what our team is trying to accomplish. (Serve many locations of similar businesses with slightly varying offerings between them.)

**Comment by rysbilinski** [comment]
+1 for multiple facebook page access tokens. Thanks

**Comment by EricDahlvang** [comment]
Add support for Facebook Checkbox Plugin opt-in

https://github.com/Microsoft/BotBuilder/issues/4199

**Comment by jhaala** [comment]
There's so many important features needed for Facebook. I've had to start bypassing core functionality to make bots work with it. BotBuilder has the best dialog handling, so I haven't given up on it yet in hopes that necessary features like these will start being added.

+100 Multiple page access tokens (Essential for development companies)

+1 Facebook Message Tags

+1 Webviews

+1 Facebook Checkbox Plugin

+1 Buy Buttons using Stripe Payments
#4664 

+1 Special buttons (share, location, email, phone number)

**Comment by EricDahlvang** [comment]
setPersistentMenu

**Comment by Sire** [comment]
Chat Extensions for their excellent sharing functionality. Without a powerful way of sharing the bot with your friends, it will never be discovered.

https://developers.facebook.com/docs/messenger-platform/chat-extensions/best-practices

**Comment by EricDahlvang** [comment]
Provide a way to set `messenger_extensions `without requiring the entire message be built using the FB native format in .sourceEvent or .channelData

ref: https://github.com/Microsoft/BotBuilder/issues/4852

**Comment by Alexander-0x80** [comment]
+1000 Multiple Facebook page access tokens

**Comment by kevinport** [comment]
+1000 To Multiple Facebook Page Access Tokens

**Comment by amitbend** [comment]
@EricDahlvang  Multiple Facebook Page Access Tokens was not about to be released a few weeks ago?

**Comment by giladaya** [comment]
Supporting multiple page access tokens is mandatory for many use cases. It's literally a show stopper for me in my current project :/

**Comment by rysbilinski** [comment]
Great news @mgbennet 

Will there be an API available to add new tokens to an existing bot?

**Comment by mgbennet** [comment]
@rysbilinski Currently we don't have a public API for configuring channels. You'll have to go through the configuration page.

**Comment by rysbilinski** [comment]
Thanks for the response Mike.

Is a public API on the roadmap?

**Comment by amitbend** [comment]
@mgbennet Any updates?

**Comment by mgbennet** [comment]
@rysbilinski I don't think we have a public API for channel configuration on the road map. It may come some day, but I don't believe any work is being done on that front right now.

Multipage Facebook configuration should be available in the next couple days. I'll post again when it's live.

**Comment by mgbennet** [comment]
It's live! Go to the Facebook channel configuration page, and you can add multiple pages. Let us know if you encounter any bugs.

**Comment by SPACEGHOST904** [comment]
So, not clear from this thread.
Was Workplace by Facebook channel added?

**Comment by EricDahlvang** [comment]
@SPACEGHOST904  No, MBF support for **Workplace by Facebook** has not yet been added.

**Comment by SPACEGHOST904** [comment]
Thanks

**Comment by marcasmar94** [comment]
These would be great if added as they make a great UX 
we currently use them by sending them as channel specific data

**- Media Template** 
**- Email Quick Reply**
**- Phone Quick Reply**
**- List Template**
**- Receipt Template**

**Comment by JasonSowers** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team

**Comment by EricDahlvang** [comment]
Note: Message tags can be done with the Bot Builder by using Channel Data:

```cs
activity.ChannelData = JObject.FromObject(new { tag = "APPLICATION_UPDATE", messaging_type = "MESSAGE_TAG" });
```

Note: Message tags can be done with the Bot Builder by using Channel Data:

```cs
activity.ChannelData = JObject.FromObject(new { tag = "APPLICATION_UPDATE", messaging_type = "MESSAGE_TAG" });
```

```js
   let msg = new builder.Message(session).sourceEvent({ facebook: {         
      "messaging_type": "MESSAGE_TAG",
      "tag": "NON_PROMOTIONAL_SUBSCRIPTION",
      "text": "Hello Facebook!"
    } });
```

**Comment by gostore-aicom** [comment]
+1 Handover protocol

**Comment by Alexander-0x80** [comment]
+1 to Handover Protocol

**Comment by odannyc** [comment]
+1 Handover protocol

**Comment by Unders0n** [comment]
@EricDahlvang trying to know if we can use botbuilder in FB group chats, is messenger_extensions is the only way to address that and so i should track #4852 ? Thanks

**Comment by EricDahlvang** [comment]
@Unders0n  I have not heard of bots in FB Group Chats. I do not know if it is possible right now.  Please file an issue here: https://github.com/Microsoft/BotFramework-Services and we can flag it as a Feature Request for the Messenger channel (if it is not already supported).

**Comment by chathudev** [comment]
Can we use the same bot in Facebook Messenger and Workplace by Facebook at same time? There is no option in channel settings to configure both at the same time. Any solution?

**Comment by Unders0n** [comment]
@EricDahlvang , hi any updates on Webview and Stripe/Facebook Payments features? If not implemented natively, how do you think would it be possible to address using workaround like ChannelData and webhooks?

**Comment by EricDahlvang** [comment]
Hi @Unders0n 

I don't know about Facebook Payments, but you can do WebViews with ChannelData.  Please find a node.js example here: https://stackoverflow.com/questions/55087150/messenger-webview-for-botframework-v4/55128551#55128551

The Bot Framework Services team might have more information.  If you wish to pursue this further, please open a feature request here:  https://github.com/microsoft/BotFramework-Services/issues

**Comment by chybisov** [comment]
Any updates on Facebook Checkbox Plugin opt-in?

**Comment by thejvdagaang** [comment]
have the ability to pin chats on top

**Comment by shayandaneshvar** [comment]
Delete Spam messages automatically after some fixed time range, e.g. a week or a month.
I have Spam messages that are 10 years old!!!
