### ISSUE TITLE
[Question] Can FormFlow capture entities from user answers using LUIS?

### ISSUE THREAD

**Issue by raulfmiranda** [Microsoft/BotBuilder#4361]
I want a BotBuilder FormFlow to recognize and capture entities in a user response. For example, if the user responds: my email is jose@gmail.com, then FormFlow would have to capture, as an answer to his question only the email (jose@gmail.com), ignoring the initial part of the text (my email is). Is it possible to do this only with FormFlow or do I need to use LUIS to do this? Should I use regex in FormFlow? How can LUIS be used together with FormFlow?

**Comment by EricDahlvang** [comment]
It is possible to create a LuisService directly in code:

`var luis = new LuisService(new LuisModelAttribute("ModelId", "SubscriptionKey"));`

This is what the LuisDialog does internally: https://github.com/Microsoft/BotBuilder/blob/c431088029265cbf1f3edd1537fbf17d8aeb3dab/CSharp/Library/Microsoft.Bot.Builder/Dialogs/LuisDialog.cs#L149
https://github.com/Microsoft/BotBuilder/blob/c431088029265cbf1f3edd1537fbf17d8aeb3dab/CSharp/Library/Microsoft.Bot.Builder/Dialogs/LuisDialog.cs#L215

However, as you mentioned, using a Regex is probably a better plan for email address validation:

```cs
    [Serializable]
    public class TestForm
    {
        public string EmailAddress { get; set; }

        public static IForm<TestForm> BuildForm()
        {
            return new FormBuilder<TestForm>()
                .Field(new FieldReflector<TestForm>(nameof(EmailAddress))
                            .SetValidate(ValidateEmail)).Build();
        }

        private static async Task<ValidateResult> ValidateEmail(TestForm state, object value)
        {
            var asString = value as string;
            var result = new ValidateResult() { IsValid = false, Value = value };
            if (!string.IsNullOrEmpty(asString))
            {
//you could make a call to LUIS here, but does not seem necessary for email address validation
                var extracted = ExtractEmail(asString);
                if (string.IsNullOrEmpty(extracted))
                {
                    result.Value = string.Empty;
                    result.Feedback = "That is not a valid email address.  Please enter a valid email address.";
                }
                else
                {
                    result.Value = extracted;
                    result.IsValid = true;
                }                
            }

            return result;
        }

        public static string ExtractEmail(string email)
        {
            Regex emailRegex = new Regex(@"\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*", RegexOptions.IgnoreCase);
            MatchCollection emailMatches = emailRegex.Matches(email);

            if (emailMatches.Count < 1)
                return string.Empty;

            return emailMatches[0].Value;
        }
```
