### ISSUE TITLE
Unable to save. Failed to register with Facebook with: Forbidden ID: |TT55v.b98b376a_

### ISSUE THREAD

**Issue by slidenerd** [Microsoft/BotBuilder#4363]
## Bot Info
* SDK Platform: Node.js
* SDK Version: 3.9.1
* Active Channels: Web, Facebook
* Deployment Environment: Azure Bot Service

## Issue Description
[mod: removed .gif with secrets]
I am trying to save settings on my azure bot portal and it doesn't save the settings at all. The bot works perfectly on the emulator (both webchat and bot emulator connected to my remote heroku url)

## Code Example
The attached GIF above shows the issue in detail

## Reproduction Steps
1. Go to Azure portal and create a bot
2. Add the facebook app id, page id, app password
3. Generate a page access token from facebook
4. Setup webhook
5. Try to save the bot with settings on Azure
6. It fails

## Expected Behavior
It should save the settings

## Actual Results
**Unable to save. Failed to register with Facebook with: Forbidden ID: |TT55v.b98b3fa8_** is the message that crops up while trying to save

## Similar issues
#3718 
#3562

**Comment by thstarshine** [comment]
Same problem here.

Have created a new facebook app, a new facebook page, and a new bot service in Azure
but still got the same error.

**Comment by EricDahlvang** [comment]
@slidenerd & @thstarshine Thank you for taking the time to report this.  We are investigating.

**Comment by jhiori** [comment]
I have the same problem!
Could be by the new Facebook´s polities??

**Comment by JasonSowers** [comment]
We will update this issue as we have more information.

**Comment by EricDahlvang** [comment]
This appears to be out of our control at this time, and is apparently due to some changes facebook is making: https://developers.facebook.com/status/issues/205942813488872/

**Comment by JasonSowers** [comment]
We are currently testing a fix and plan to have it rolled out within a few hours.  I will update this issue if anything changes and/or when the fix is live

**Comment by JasonSowers** [comment]
We have rolled out a fix, please let us know if you are still experiencing issues.

**Comment by slidenerd** [comment]
While it saves the data, I dont see any responses being generated currently, still works perfectly from the emulator
 UniversalBot("*") routing "hey" from "emulator"
2018-03-24T01:16:53.642768+00:00 app[web.1]: Session.beginDialog(/)
2018-03-24T01:16:53.893197+00:00 app[web.1]: / - Session.sendBatch() sending 0 message(s)
2018-03-24T01:16:54.028766+00:00 app[web.1]: / - IntentDialog.onDefault()
2018-03-24T01:16:54.028948+00:00 app[web.1]: / - waterfall() step 1 of 1
2018-03-24T01:16:54.029320+00:00 app[web.1]: hey
2018-03-24T01:16:54.029960+00:00 app[web.1]: / - Session.send()
2018-03-24T01:16:54.080677+00:00 app[web.1]: / - Session.sendBatch() sending 1 message(s)
2018-03-24T01:16:54.750888+00:00 app[web.1]: / - Session.sendBatch() sending 1 message(s)

But I did not get any responses while messaging my page, anyone else experiencing the same issue?

**Comment by JasonSowers** [comment]
@slidenerd if you are still experiencing issues unrelated to saving the facebook settings please open a new issue with details.

**Comment by thstarshine** [comment]
@JasonSowers everything works fine now, thanks!

**Comment by slidenerd** [comment]
Everything works!! Thank you very much
