### ISSUE TITLE
Azure web app bot with LUIS (nl-nl) stoppped working

### ISSUE THREAD

**Issue by jbeek11** [Microsoft/BotBuilder#4369]
## Bot Info
* SDK Platform: .NET
* SDK Version: 4.6
* Active Channels: Web channel, Direct Line, Facebook, Slack
* Deployment Environment: local development in VS2017 with Emulator
* Created with Azure template for LUIS bot in C#

## Issue Description
I had a working bot up until last Tuesday (March 20th), combined with a Dutch (nl-nl) LUIS app. All resources reside in West US domain (incl LUIS app). 

## Code Example
I have not changed anything to the code, the bot simply stopped working. It looks like it is related to the integration with LUIS.

## Reproduction Steps
1. I have redeployed the bot to standard state at beginning. This is with standard LUIS app in 'en-us' locale. Then the bot works again. When switching back to the nl-nl app, only response that is given is 'Sorry, my bot code is having an issue' (in Azure Testin Web Chat) or in Dutch equivalent message (in local bot emulator). Switching back agian to en-us at first made the bot work again. But now, whatever LUIS appID I use, the bot just gives an error message.
2. I have setup a completely new bot in West US as well, this gives the exact same result as for #1
3. I have setup a completely new Azure bot and nl-nl app in LUIS for West Europe region, this too produces the exact same result.
4. In all above mentioned stept it made no difference if I used a 'Starter' key or if I generated new keys (Cognitive Services in Azure) and added these keys to Publish page for the corresponding region in LUIS app.

## Expected Behavior
I expected my bot to just keep working if I did not change the code. Secondly I would expect to be able to create a completely new bot from scratch and switch to nl-nl LUIS app without getting errors. And at last, IF this is caused by a change, I would have expected to be notified or contacted in advance so I could have taken action to prevent this.

## Actual Results
I have not been able to create a new app that works with a nl-nl LUIS app since last Tuesday. Either it simply answers with 'Sorry, my bot code is having an issue' or (locally) I get a very vague error message about a System.ArgumentNullException in mscorlib.dll (CallStack gives no further clue either).

**Comment by youtoofan** [comment]
Which version of the botbuilder are you using? I had the same problem, the service would throw an authentication error after one hour of inactivity. Rolling back to the previous version resolved this.
The latest version of the botbuilder now includes a fix for this.

**Comment by JasonSowers** [comment]
If you are using version 3.14.0.7 please either upgrade to 3.14.1.1 or downgrade to 3.13.1

**Comment by jbeek11** [comment]
Hi, first of all thank you for trying to help me! Much appreciated. Unfortunately your suggestions will not help me in this situation as I'm already working with the latest version 3.14.1.1 in VS2017 (see picture). If I'm wrong here and this is not what you mean, then please give me some more pointers for where to look or what to do. Thanks in advance.
Regards,
Joris.
![3 14 1 1](https://user-images.githubusercontent.com/11049531/37923137-b70cc80c-312e-11e8-8ec9-2438123a985f.jpg)

**Comment by fanidamj** [comment]
@jbeek11 and @youtoofan Please send your LUIS App ID and .HAR file from the chrome developer console while accessing the LUIS app to **Luisuservoice@microsoft.com** so that we investigate further and assist you.

**Comment by jbeek11** [comment]
I have no idea what you mean with a .HAR file. I don't work with the chrome developer console.
Since posting this issue, I have opened another account and followed the exact same steps I was trying before. Under this new account everything works perfectly. So, I'm now in contact with Microsoft to see what has changed with regard to my account. To my knowledge, absolutely nothing, but obviously that is not the whole story. ;) Thank you everybody here for trying to help me out!

**Comment by fanidamj** [comment]
Thanks for the update @jbeek11. 

@youtoofan Can you please provide us your update or provide us the info asked earlier so that we can help you.

**Comment by fanidamj** [comment]
Feel free to reopen the issue or contact at Luisuservoice@microsoft.com if the issue still persists.
