### ISSUE TITLE
Create pdf in bot builder

### ISSUE THREAD

**Issue by mantaplatte** [Microsoft/BotBuilder#4370]
## Bot Info
.NET
Azure Bot Service

## Issue Description
I'm trying to edit a PDF file on the fly and upload it to my azure storage blob, which works in a .NET console App. 
If I use the same code in the bot, it just stops working. Hope somebody can help me.

## Code Example
`public static class ObjectToPdf
   {
      public static async Task CreatePdf(Invention invention)
      {
         var account = new CloudStorageAccount(new StorageCredentials("APPNAME", "APPKEY"), true);
         var blobClient = account.CreateCloudBlobClient();
         var container = blobClient.GetContainerReference("CONTAINERNAME");
         var fileNameExisting = download();
         fileNameExisting.Wait();
         var pdfReader = new PdfReader(fileNameExisting.Result);

         // PdfStamper, which will create
         using (MemoryStream _output = new MemoryStream())
         {
            using (PdfStamper stamper = new PdfStamper(pdfReader, _output))
            {
               var form = stamper.AcroFields;
               var fieldKeys = form.Fields.Keys;

               foreach (string fieldKey in fieldKeys)
               {
                  var props = fieldKey.Split('.');
                  string t = GetProp(props, invention);
                  form.SetField(fieldKey, t);
               }
            }
            var byteArray = _output.ToArray();
            var blobName = "hello-world.pdf";
            var blob = container.GetBlockBlobReference(blobName);
            blob.Properties.ContentType = "application/pdf";
            blob.UploadFromByteArray(byteArray, 0, byteArray.Length);
         }

      }
      public async static Task<byte[]> download()
      {
         return await new WebClient().DownloadDataTaskAsync("https://MYAPPNAME.blob.core.windows.net/CONTAINER/FILE.pdf");
      }
      public static string GetProp(string[] classes, object oldObj)
      {
         var obj = oldObj.GetType().GetProperty(classes[0]).GetValue(oldObj, null);
         if (classes.Length > 1)
         {
            classes = classes.Skip(1).ToArray();
            return GetProp(classes, obj);
         }
         return obj.ToString();
      }
   }`

**Comment by JasonSowers** [comment]
Duplicate of https://stackoverflow.com/questions/49486577/create-pdf-from-existing-pdf-with-azure-storage
