### ISSUE TITLE
BotBuilder download blob file

### ISSUE THREAD

**Issue by mantaplatte** [Microsoft/BotBuilder#4371]
## Bot Info
.NET

## Issue Description
Hello I made a bot and want to download a file from my azure blob storage. But the bot just stops working. There is no Exception, it just hangs at that position. Here is the code:

## Code Example

```
public async static Task<byte[]> download(IDialogContext dialog)
  {
     try
     {

        return await new WebClient().DownloadDataTaskAsync(new Uri("https://storageName.blob.core.windows.net/container/file.pdf"));
     }
     catch (Exception ex)
     {

        await dialog.PostAsync(ex);
        return null;
     }

  }


```

**Comment by JasonSowers** [comment]
Which channel(s) are you using? Some channel only allow for bots to send certain types of files.
