### ISSUE TITLE
Integrate MS Bot Framework with Facebook Workplace Bot

### ISSUE THREAD

**Issue by neetgupta7** [Microsoft/BotBuilder#4372]
## Bot Info
* SDK Platform: .NET 
* SDK Version: 3.12
* Active Channels: FB Messenger
* Deployment Environment: Azure App Service

## Issue Description
Can Microsoft Bot Framework be integrated with Facebook Workplace Bot or one will have to do a fresh development for the workplace bot.

**Comment by FranciscoPonceGomez** [comment]
Hi meetgupta7,
At the moment we don't offer support for Facebook Workplace. We have no specific details to announce at this time but might consider the option depending on user demand and other factors.
Can you tell me more about the scenario for your bot? 

Regards,
Francisco
