### ISSUE TITLE
[Feature Request] Message flow diagram for Microsoft Bot framework

### ISSUE THREAD

**Issue by waleedabuyahia** [Microsoft/BotBuilder#4375]
## Bot Info
* SDK Platform: .Net
* SDK Version: Latest
* Active Channels: All
* Deployment Environment: All

## Issue Description
I went through Microsoft Bot Framework documentation and I could not find any message flow diagram or flow diagram describes how the bot framework works and how the message flows through the framework, what I think all programmers (not developers) need is a message flow diagram shows the message flow between different internal components inside bot framework, like the message will be received in the MessageController then it will be send to Conversation class which is a static implementation the Idialog context has been established which implements another interfaces and continue......  so we can have better understating how framework works internally, in my case because I like how things work internally I download the source code of the framework and I start debugging everything to understand..

**Comment by EricDahlvang** [comment]
I'm not aware of a diagram describing the internal workings of the Bot Builder sdk.

I've labeled this as a feature request.

**Comment by xjose97x** [comment]
Would be interesting to have a sort of "white paper" which explains the architecture of the Microsoft Bot Framework. For instance the framework (v3 does, not sure if v4) works with fibers and stacks, and having information on how and why that is used would be very useful.

**Comment by EricDahlvang** [comment]
This is not a flow diagram, but these specs provide some low level information about the MBF:

https://github.com/Microsoft/BotBuilder/blob/1045a9e02e9eb14d353509c1562808dced23c29e/specs/botframework-activity/botframework-activity.md

https://github.com/Microsoft/BotBuilder/blob/1045a9e02e9eb14d353509c1562808dced23c29e/specs/botframework-activity/botframework-cards.md

https://github.com/Microsoft/BotBuilder/blob/1045a9e02e9eb14d353509c1562808dced23c29e/specs/transcript/transcript.md

**Comment by JasonSowers** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
