### ISSUE TITLE
Custom IBotDataStore<BotData> doesn't save anything if not wrapped by CachingBotDataStore

### ISSUE THREAD

**Issue by smourier** [Microsoft/BotBuilder#4376]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.14.1.1
* Deployment Environment:  local development with Emulator

## Issue Description
I'm not using SQL Azure neither Cosmos DB to store state, but a custom class.

I think the current implementation of BotBuilder doesn't support a custom state service if this custom state service is not wrapped by the `CachingBotDataStore`. Took me hours to figure that out...

## Code Example
If I do this

        context.UserData.SetValue("whatever", "whatever");

in some dialog code, with a custom state service registered in global.asax just like this:

                builder.Register(c => new MyBotDataStore())
                    .Keyed<IBotDataStore<BotData>>(MyKey_DataStore)
                    .AsSelf()
                    .SingleInstance();

then no save happens (Prior load operations do work). But, if I wrap my `IBotDataStore<BotData>` implementation with the `CachingBotDataStore`, like this:

                builder.Register(c => new CachingBotDataStore(c.ResolveKeyed<IBotDataStore<BotData>>(MyKey_DataStore),
                                        CachingBotDataStoreConsistencyPolicy.ETagBasedConsistency))
                                    .As<IBotDataStore<BotData>>()
                                    .AsSelf()
                                    .InstancePerLifetimeScope();

Then it works! In fact the (deprecated) `Connector `service and the newer SQL Azure and Cosmos DB stores are currently always demonstrated wrapped by the `CachingBotDataStore`.

## Expected Behavior
I would expect an` IBotDataStore<BotData>` implementation to work as is, w/o using the `CachingBotDataStore`

For information, I've taken a look at BotBuilder's code, and in the `BotDataBase<T>` class in BotData.cs, no SaveXXX method is ever called (only in LoadData, which is quite strange, but that's another story). It works with the CachingBotDataStore wrapper because this store calls Save after a Flush. All this may be by design, but I can't find any documentation that clearly states that.

**Comment by EricDahlvang** [comment]
This whole thing is confusing.  There are a few ways to register your custom bot data store.  

1) if you are using your own keyed registration, you also need to replace the CachingBotDataStore (as you discovered).

2) if you are using BotBuilder-Azure, then you need to register the AzureModule first:

```cs
 builder.RegisterModule(new AzureModule(Assembly.GetExecutingAssembly()));
 builder.Register(c => new MyBotDataStore())
                        .Keyed<IBotDataStore<BotData>>(AzureModule.Key_DataStore)
                        .AsSelf()
                        .SingleInstance();
```

3) If you aren't using BotBuilder-Azure, and also not registering your custom store with a custom key, you can replace the ConnectorStore like this:

```cs
builder
      .RegisterType<MyBotDataStore>()
     .Keyed<IBotDataStore<BotData>>(typeof(ConnectorStore));
```

The last one is probably the implementation you were searching for.  We should point this out in our documentation.  I will forward this to the docs team to have this page updated: https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-state

**Comment by smourier** [comment]
Thanks for your reply.

I originally didn't use keys, I added the key because precisely I had to "chain" the `CachingBotDataStore` to have the Save methods called when custom data is Set somewhere in dialogs.

So it does mean there's must always be a CachingBotDataStore  acting as a facade to the botbuilder code "in front" of a custom `IBotDataStore<BotData>`, right ?

IMHO, it seems a pretty strange design. You have all that Autofac plumbing (which honestly doesn't make things simple, you always have to go to the botbuilder code to really understand what's going on - thankfully, it's open source 👍), you have an interface `IBotDataStore<BotData>`, well designed, that seems to suffice for itself, and yet, you can't just replace its implementation (implementing an interface is very natural in .NET world) but you must pretend your class is of the ConnectorStore type.

I mean, today's documentation does make sense, I'm more troubled by the implementation.

**Comment by EricDahlvang** [comment]
If it is any consolation, version 4 of the SDK does not use this pattern: https://github.com/Microsoft/BotBuilder-dotnet

**Comment by smourier** [comment]
Wow. Yes it's probably a consolation... :-)

I wasn't aware of that new version. It's good news. And I'm wondering if it's also bad news.... Is it due for release any time soon? I mean... Should I throw my existing code now?

**Comment by EricDahlvang** [comment]
No need to throw out your existing code.  The Roadmap here: https://github.com/Microsoft/botbuilder-dotnet/wiki/Roadmap mentions there will be "V3 -> V4 migration helpers"

**Comment by smourier** [comment]
Ok, thanks a lot.
