### ISSUE TITLE
[Feature Request] Please add sample to each Channel Inspector at their corresponding page

### ISSUE THREAD

**Issue by hamiltonjose** [Microsoft/BotBuilder#4378]
## Bot Info
* SDK Platform: 
* SDK Version: 
* Active Channels: 
* Deployment Environment: 

## Issue Description
Please add sample to each Channel Inspector at their respective page (https://docs.botframework.com/en-us/channel-inspector/channels/WebChat?f=Buttons&e=example1)

## Code Example
var reply = ((Activity)message).CreateReply();
reply.Text = "Growth mindset! Here you go:";
reply.AttachmentLayout = AttachmentLayoutTypes.List;
reply.Attachments = sites.items.ToAttachmentList();
var connector = new ConnectorClient(new Uri(reply.ServiceUrl));
return connector.Conversations.SendToConversationAsync(reply);

## Reproduction Steps
1. Not applicable

## Expected Behavior
Have sample code for each Channel Inspector

## Actual Results
There's no sample for each Channel Inspector at their corresponding page

**Comment by JasonSowers** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
