### ISSUE TITLE
Cortana - OAuth2 Redirect URL Configuration not changing

### ISSUE THREAD

**Issue by prtdomingo** [Microsoft/BotBuilder#4379]
I'm currently implementing an OAuth2 authentication using Microsoft Bot Framework and Cortana as one of my channels. However, as I was setting up my OAuth2 configuration with the following details in where I properly set the **Redirect URL** both from **Knowledge Store** and **apps.dev.microsoft.com** 

Knowledge Store:
[![enter image description here][1]][1]

apps.dev.microsoft.com:
[![enter image description here][2]][2]

Whenever I authenticate to Cortana based from the OAuth2 that I've configured, the redirect URI seems to be always set as **https://www.bing.com/agents/oauth**. Here's a screenshot of the http request from Cortana Authentication that I got from fiddler:

[![enter image description here][3]][3]

Which causes this error message:

[![enter image description here][4]][4]

Any idea how to fix this?

  [1]: https://i.stack.imgur.com/1l4ca.png
  [2]: https://i.stack.imgur.com/vQfvc.png
  [3]: https://i.stack.imgur.com/WBRaj.png
  [4]: https://i.stack.imgur.com/yEEr0.png

**Comment by EricDahlvang** [comment]
Closing as duplicate https://stackoverflow.com/questions/49531586/cortana-oauth2-redirect-url-configuration-not-changing
