### ISSUE TITLE
How to protect against replay attacks in Bot Builder?

### ISSUE THREAD

**Issue by whatsdis** [Microsoft/BotBuilder#438]
First an example of a replay attack from wikipedia:

> Suppose Alice wants to prove her identity to Bob. Bob requests her password as proof of identity, which Alice dutifully provides (possibly after some transformation like a hash function); meanwhile, Eve is eavesdropping on the conversation and keeps the password (or the hash). After the interchange is over, Eve (posing as Alice) connects to Bob; when asked for a proof of identity, Eve sends Alice's password (or hash) read from the last session, which Bob accepts thus granting access to Eve.

1) How does Bot Builder distinguish devices via SMS? How are the userdata being associated with the end user through SMS? Does it look at the originating phone number and able to connect the relevant userdata to it? Is this secure enough? What if somebody takes a look at the conversationId and userId , and use it launch replay attacks using those intercepted or stolen pieces of data?

2) How does Bot Builder make the contents of the SMS texts going back and forth from the user to the Bot Builder instance running on Azure?

3) Are there other security concerns/vulnerability in using Bot Builder that I should be aware of?

**Comment by whatsdis** [comment]
It seems like userId and conversationId is generated and linked to the address which is the SMS phone number of the recipient. Could I get some more insight as to how this works, it seems to be somebody could spoof an SMS using the same credentials. 

More specifically I'm using Twilio SMS and there's some mention of a header that contains some token which needs to be validated to ensure that it's coming from Twilio and not a stranger. Is this already implemented?

And if you are using the authorization token from Active Directory B2C, would it be secure to store it in the UserData? Since B2C does not seem to send the MFA mobile number to the policy claim. Would it not make sense to pass in the MFA mobile number from B2C to a claim so that on the Bot Builder side you would verify that the user indeed is the same guy? Right now the sample code just seems to check if AuthorizationToken in the UserData is set or not, doesn't actually do a verification.

I know this is quite a mouthful but really would appreciate it if somebody could get in touch and address these security concerns.

Many thanks.

**Comment by tomlm** [comment]
Our SMS channel should be verifying that twilio token is valid before we use our secret to call to your bot.

Our bot data is stored in azure table storage encrypted, with the Encryption keys stored in a Azure Key Vault.  The bot data is only ever sent to the bot, not downstream.

**Comment by whatsdis** [comment]
Can you elaborate? so how does bot connector know that it's talking to the right mobile phone user? is this done through phone number? if I'm using AD B2C and storing the authentication token provided by AD, how can I verify that it really is them? Is it possible to restrict it so the user can only use his phone number that is linked to the MFA'd number on B2C? How would this be done without the MFA number being made available in the policy claims?

**Comment by tomlm** [comment]
Twilio is the one that controls the security of SMS numbers coming in. If you want to know if identity is spoofable or not you should direct your questions to them.

We validate the calls from twilio using the signed security process described here.
https://www.twilio.com/docs/api/security 

We secure our communication with you using SSL and shared secret.

We secure your bot data that you store with us using Encryption (which you don't have to use, you can store in whatever compliant store you want.

**Comment by whatsdis** [comment]
I see so the phone number and combination of those twilio data is used to concoct the userId and conversationId am I correct?

What about when used with AD B2C? Does bot builder do anything else beside check if AuthorizationToken UserData is set or not? Is it enough to just verify the id_token sent by B2C?

Are there any potential/theoretical vulnerabilities here? Like is there a chance that somebody could intercept SMS going through twilio and bot connector?

**Comment by tomlm** [comment]
This is not a question for us.  You are asking about the security of SMS, which I think you should be asking Twilio about

**Comment by whatsdis** [comment]
fair enough, thank you.
