### ISSUE TITLE
[Feature Request] Adding IDialogContext to IForm

### ISSUE THREAD

**Issue by mitkodi** [Microsoft/BotBuilder#4381]
Hello,

What about adding ```IDialogContext``` to ```IForm```. I did it in the past (in my BotBuilder's clone) when I had to make authenticated requests at some IForm steps and authentication was done through Authbot, but I think that it could be useful in other scenarios also.
To accomplish that I just added ```_form.Context = context``` in ```FormDialog.MessageReceived```.

**Comment by JasonSowers** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
