### ISSUE TITLE
Skype Bot goes offline when pinged from external network

### ISSUE THREAD

**Issue by AnushkaKatyayan** [Microsoft/BotBuilder#4382]
## Bot Info
* SDK Platform: 
* SDK Version: 
* Active Channels: 
* Deployment Environment: <local development with Emulator? -->

## Issue Description
<-- Our Skype Bot was technically developed for inter company use. As the skype is federated across other companies too , we are planning to restrict the bot response only to employees with the company. When the Skype Bot is pinged from an external domain, it goes offline for all of us. Can somebody please suggest a solution to this ? -->

## Reproduction Steps
1.
2.
3.

## Expected Behavior
<The Bot Should not give back any response to the external pings and should still be online >

**Comment by nodeomega** [comment]
What platform are you using? C#? Node?

Are you capturing any errors in your code (error logging, etc.)?

A code sample would be helpful.

**Comment by nodeomega** [comment]
Closing this issue as there has been no reply for an extended period.  If this issue persists, feel free to open a new support request.  Thank you.
