### ISSUE TITLE
[Feature Request] Carousal should render each card with same height.

### ISSUE THREAD

**Issue by Kartik1607** [Microsoft/BotBuilder#4385]
Currently carousel simply renders the card. Instead it should be able to adjust the height of the cards by pulling the action buttons and empty space to the bottom.

**Comment by stevengum97** [comment]
@Kartik1607, which channel is this for?

**Comment by Kartik1607** [comment]
We have currently deployed to bot to only webchat, and are planning to deploy it to FB Messenger and skype. 
I can only confirm for webchat (and emulator), that this issue exists. Our carousel displays multiple adaptive cards (each of same Json Schema but different  text values). Due to different text values, we have to make sure that each text field should span exactly same number of lines. 
If just one of text field in any one of card span to an extra line, the card gets taller while other cards remain of same height and the UI breaks from a UX perspective.

**Comment by JasonSowers** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
