### ISSUE TITLE
There was a problem synchronizing your bot to Skype.

### ISSUE THREAD

**Issue by agpalma59** [Microsoft/BotBuilder#4388]
## Bot Info
* SDK Platform: 
* Active Channels: 
* Deployment Environment: 

## Issue Description
I'm trying to publish a Bot on Skype but it always has the same "there was a problem synchronizing your bot to Skype." and basic registration information is not saved, for example email and privacy policy url

**Comment by stevengum97** [comment]
Closing for now, please follow issue #4402 where we are tracking this problem.
