### ISSUE TITLE
[.NET SDK] Bot won't work on self-host IIS: There was an error sending this message to your bot: HTTP status code Unauthorized

### ISSUE THREAD

**Issue by MichaelBartlettGitHub** [Microsoft/BotBuilder#4389]
## Bot Info
* SDK Platform: .NET (C#)
* SDK Version: 3.14.1.1
* Active Channels: Web only
* Deployment Environment: Brinkster.com - IIS - ASP.NET 4.6
* AppID and Password are correct
* Has an approved SSL cert (https://www.ccxpexamsimulator.com/bot/api/messages)
* Embed code: https://webchat.botframework.com/embed/BrinksterBot?s=_V55Nlrk.cwA.vJQ.l8CbKmOuntnXGDlwCH31TISJ89iOLXtnrrYbRzHacXQ (Don't worry - I will regenerate when this is all solved so not worried about ppl seeing the secret)

## Issue Description
Bot works fine locally (via Emulator) and on Azure.  Put it on my web hosting platform and cannot get it to work.

## Reproduction Steps
1. Log into Azure (set to EST as is my host)
2. Find my bot
3. Click "Test in Web Chat"
4. Go to Channels after it doesn't work and retrieve error
The error is: "There was an error sending this message to your bot: HTTP status code Unauthorized"

## Expected Behavior
It should respond with an adaptive card

## Actual Results
the bot says: couldn't send retry

**Comment by MichaelBartlettGitHub** [comment]
Here is the embed code: https://webchat.botframework.com/embed/BrinksterBot?s=c72_V55Nlrk.cwA.vJQ.l8CbKmOuntnXGDlwCH31TISJ89iOLXtnrrYbRzHacXQ

**Comment by MichaelBartlettGitHub** [comment]
I have the bot inside the emulator on my local machine using ngrok and it is working ok although the adaptive cards are not displaying

**Comment by MichaelBartlettGitHub** [comment]
I have been working on this all morning and I now have it working.  The server time needed to be adjusted and that seemed to fix the issue.  It would be great if it was possible as part of the open source project to return an error explaining this.

**Comment by EricDahlvang** [comment]
Hey @MichaelBartlettGitHub 

Would you mind explaining how you changed the server time?  Meaning, "time was x, and i changed it to y"?  Or, did you change the timezone?  What change exactly did you make in order to get passed this?

**Comment by MichaelBartlettGitHub** [comment]
Hi Eric,


I read on another forum that someone did this, so I sent it over to my host and asked them to troubleshoot and then the ticket was closed and marked as resolved (Brinkster.com).


At the same time I also recreated a brand new resource group in EST because the previous one was in CST.  So either could have fixed it.


I can fwd you the original thread that I sent to them if you would like?


-Mike



________________________________

**Comment by EricDahlvang** [comment]
Yes, please forward me all the information you can about this.  I'm working with a couple other Bot Framework users hosting on-prem that are having a similar issue.  My email address is on my profile: https://github.com/EricDahlvang

Thank you so much!

**Comment by MichaelBartlettGitHub** [comment]
Hi Eric,



Here is the thread I had Brinkster use:

https://github.com/Microsoft/BotBuilder/issues/2266



To get it working, here is what I ended up doing:


1) Deleted everything on Azure

2) Set up new resource in eastern standard time (As that is where my host is located and not where I am).

3) generated the bot info on Azure

4) Uploaded my code into a director brinkster enabled for me.

5) The site in general has an https via comodo

6) Made sure the endpoint was set and also obviously make sure appid and pwd are correct

7) Made sure brinkster's servers were accurate as possible with their clocks (not sure how they do this - there must be some central place the big companies check against?)


I did notice that one I changed the endpoint the applications settings were 'no longer found' which was irritating as if u lose your id and pwd u need to regenerate a bot from scratch.  Maybe changing the endpoint back to the original azure will help but I haven't tried.


I have an extra bit of free space on my brinkster server in a second account so if u need help with anything I am happy to upload your code for you there if necessary.


Here is my bot running - it's a mess - just happy I got it working with an adaptive card.


https://webchat.botframework.com/embed/BrinksterBot2?s=zKQrz8iS4gE.cwA.XL0.tDLlqCreWA6xx1Rxz7NO82v6mHbMQf1-FlNK9hUsWTM


-Mike

417.365.3034

email or call any time.



________________________________

**Comment by MichaelBartlettGitHub** [comment]
Oh there was one other step I took:


I installed ngrok locally and used that to test the bot on brinkster - doubt it made much difference but I did it incase their was a bug with 'web chat' but not with the emulator.


-Mike


________________________________

**Comment by EricDahlvang** [comment]
Thank you for sharing how you've resolved the issue.

fyi: 
I looked at https://webchat.botframework.com/embed/BrinksterBot2?s=zKQrz8iS4gE.cwA.XL0.tDLlqCreWA6xx1Rxz7NO82v6mHbMQf1-FlNK9hUsWTM and noticed that your welcome message isn't accepting input the first time it is displayed.  This can be remedied by following the process described here: https://github.com/Microsoft/BotFramework-WebChat/issues/536  (there is no option for showing an interactive adaptive card, or dialog, while using the iframed version of webchat)

**Comment by MichaelBartlettGitHub** [comment]
Thanks, Eric.


The issue I am actually noticing is that on Webchat I get the ConversationUpdate fired 2 times in a row which is why the adaptive card up twice.


-Mike


________________________________
