### ISSUE TITLE
Bot emulator crashes when clicking on Action

### ISSUE THREAD

**Issue by v-tbert** [Microsoft/BotBuilder#439]
I added an attachment with actions similar to how its described at the bottom of this link: http://docs.botframework.com/connector/message-actions/#navtitle

It works fine for displaying my action items in the bot emulator but as soon as I click on one of the options it crashes. I presume it isn't properly null checking and I am not providing a url.

**Comment by chrimc62** [comment]
Sorry for the delay in responding.  Added @LarsLiden who should be able to comment.

**Comment by v-thgratMSGit** [comment]
Closing this issue due to age. @v-tbert - please open a new issue if this issue is not fixed and needs further discussion. Thanks!
