### ISSUE TITLE
[.NET SDK] Azure Functions Bot won't localize built-in messages/texts

### ISSUE THREAD

**Issue by dogfuntom** [Microsoft/BotBuilder#4390]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.14.1.1
* Active Channels: Telegram, Emulator
* Deployment Environment: Azure Functions Bot, Emulator

## Issue Description
Even if locale is forced explicitly and emulator shows that all incoming and outcoming messages has that locale, the bot still uses English texts ("yes", "I didn't understand. Say something in reply.", etc.) instead of localized texts.

(But if the same is repeated in Azure App Service Bot, then all such texts are localized correctly.)

## Code Example
```
if (activity != null)
{
    activity.Locale = "ru-RU";
    ...
}
```

## Reproduction Steps
1. Create an Azure Functions Bot from basic template.
2. (optional) Forcibly set locale as in code example above.
3. Launch in emulator with needed locale. Observe English texts despite locale is correct in details in both incoming and outcoming messages.
4. (optional) Observe the same behaviour in all possible environments: Visual Studio + Emulator, Azure + Emulator, and in actual channel (I tried Telegram).

## Expected Behavior
Localized texts ("yes" → "да", etc.).
Note that unlike Functions Bot, App Service Bot shows localized built-in text in the identical circumstances.

## Actual Results
English texts despite locale is correct and supported (e.g. by App Service Bot).
![image 1](https://user-images.githubusercontent.com/905138/38119008-70adaa66-33c7-11e8-87b9-aa5cc782bab3.png)

**Comment by JasonSowers** [comment]
I will look into this for you and see if we can find the cause.

**Comment by JasonSowers** [comment]
I am looking into this, will update you when I have some information.

**Comment by JasonSowers** [comment]
Still looking into this

**Comment by gopal300** [comment]
Hi JasonSowers, did you find any information about this because i am facing the similar problem.

**Comment by JasonSowers** [comment]
@gopal300 @dogfuntom Apologies for the delay in the response, this fell on the back burner for a bit.  I will continue to look into this.

**Comment by JasonSowers** [comment]
Sorry for the delay this fell off my radar and I had been out of the country.

In your image you are using the emulator.  If you set the locale in the emulator itself it will show up with the yes/no options in Russian as you need.  Are you seeing this in other channels as well?

![image](https://user-images.githubusercontent.com/6301037/41990800-576d684e-79f8-11e8-9647-e2af58d69551.png)

**Comment by JasonSowers** [comment]
Going to assume this is resolved now, if you have any other issues please open a new issue.
