### ISSUE TITLE
[Feature Request] Google Hangouts Channel

### ISSUE THREAD

**Issue by rohankulkarni21** [Microsoft/BotBuilder#4397]
## Bot Info
* Active Channels: Google Hangouts

## Issue Description
Are there any plans to support Google Hangouts as a channel in Bot Framework?
Are there any approaches by which we can integrate Hangouts channel?

**Comment by xjose97x** [comment]
@rohankulkarni21 If a channel is not by default available for Microsoft Bot Framework, you have to code to establish the connection through the Bot Framework DirectLine SDK.

**Comment by jschumann** [comment]
@xjose97x Can you point us to some docs or code examples for how to do this in a chat service we don't control? All the docs I've seen about Direct Line talk about implementing it within your own chat service, not using it to communicate with a third party service.

**Comment by xjose97x** [comment]
@jschumann As far as I know, Google Hangouts allow subscribing to incoming messages through Webhooks: https://developers.google.com/hangouts/chat/how-tos/webhooks

That means, that if a user sends a message to your account, hangouts will do an HTTP call to whatever URL you set as webhook.
So you have to create a server which receives this webhook, and in that server with the Microsoft Bot Framework DirectLine SDK send that message to your bot. And on that same server, receive the response from the bot. Once you have the response, you'll send it back to Hangouts through it's REST API: https://developers.google.com/hangouts/chat/how-tos/rest-api

Here you have more resources:
https://developers.google.com/hangouts/chat/concepts/bots
https://developers.google.com/hangouts/chat/how-tos/bots-publish

Note I haven't read the Hangouts documentation myself, but I've instead applied this concepts on other custom channels.

**Comment by annevah** [comment]
I was able to integrate my chatbot to hangouts but there is a significant delay in passing the message. Would love to have a hangouts channel !

**Comment by JasonSowers** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team

**Comment by rodrigorodriguez** [comment]
Hey, we built this on top of BOT Framework, please check out: https://www.youtube.com/watch?v=Y4R9EOoaw0k. It's here: https://github.com/generalbots.
