### ISSUE TITLE
[NodeJS] sending back-to-back replies with BotConnectorBot isn't working

### ISSUE THREAD

**Issue by Stevenic** [Microsoft/BotBuilder#44]
We need to add a queue that slows down the rate at which we send back-to-back messages from a bot. Looks like when we send an inline reply using session.send() and immediately follow it with a Prompts.choice() call the second call never makes it through. Could be that out-of-band messages are still broken or their just clobbering each other. Either way something is up.

**Comment by runxc1** [comment]
Is this a problem with the framework underneath then?   I have been trying to send two messages using context.PostAsync() one after the other in order to put a natural break between messages as carriage returns don't seem to be preserved and thought it was odd the second message never went through.

**Comment by Stevenic** [comment]
Interesting... I haven't had time to investigate yet but the user that reported this issue was definitely seeing that second message gets dropped. @willportnoy can you comment on the use of PostAsync() for back-to-back calls?

**Comment by Stevenic** [comment]
Just checked in a fix for this. As of v0.7.2 back-to-back messages should be working for both Bot Connector and Slack.  I still need to add a queue to slow down calls which I'll work on next.
