### ISSUE TITLE
Wrong Japanese localizations through ArgumentException in FormBuilder

### ISSUE THREAD

**Issue by kanoh-k** [Microsoft/BotBuilder#440]
Hello, 

I was running SimpleSandwitchBot (http://docs.botframework.com/sdkreference/csharp/forms.html) with ja-JP locale, and found some Japanese localization are wrong.
Some of them contains "{|}" this pattern, which raises ArgumentException with illegal pattern. (for instance, TemplateClarify in BotBuilder/CSharp/Library/Resource/Resources.ja.resx)

Can you please modify "{|}" this wrong pattern to correct one?

**Comment by chrimc62** [comment]
Thanks for bringing this to our attention.  I have fixed the issue and our next release will work.
