### ISSUE TITLE
[Migration] Error 400 Azure Bot Migration

### ISSUE THREAD

**Issue by Irbis377** [Microsoft/BotBuilder#4400]
## Bot Info
* SDK Platform: .NET 
* SDK Version: 3.12.2.4
* Active Channels: Skype, Telegram
* Deployment Environment:  Azure Bot Service

## Issue Description
Can not migrate my bot.

## Reproduction Steps
1. sing up https://dev.botframework.com
2. click "My Bots"
3. click "Migrate" 
4. click "Migrate" - my bot's name+'upgrade', Azure  Subscription, Azure resource group and  Bot service pricing tier cannot change and mark as gray
![11](https://user-images.githubusercontent.com/24790338/38139728-6917bdce-3439-11e8-9b00-b967740427fd.png)
5. accept two Agreement 

## Expected Behavior
My Bot migrated without any exception 

## Actual Results
I have error 400. 
![image](https://user-images.githubusercontent.com/24790338/38135541-6c43fb10-3421-11e8-83dd-19ca20ccbbbf.png)

What I need to do to fix it?

**Comment by PulseDiver** [comment]
i think u need azure subcription before start migrate

**Comment by Irbis377** [comment]
But I have this one
![subscribe](https://user-images.githubusercontent.com/24790338/38138894-b40b16e0-3435-11e8-9595-7b0a222e697c.png)

**Comment by fanidamj** [comment]
@Irbis377 thanks for reporting this issue we are currently investigating.

**Comment by Irbis377** [comment]
@fanidamj thank you, I will wait any solution.

**Comment by Polaris-BS** [comment]
I have exactly the same problem and my Bot is in production . 
I need a quick fix please. My Bot App ID : ad902637-9704-47a3-ada0-140809db6d6b

**Comment by Andrea-Orimoto** [comment]
hi @Irbis377, sorry for the inconvenience. The error in the log says that "The value of deployment parameter 'botEnv' is null". Do you have the "BotEnv" App Settings set to "Prod"? If not, can you add it and retry?

**Comment by Andrea-Orimoto** [comment]
@Polaris-BS, the error in your case is slightly different, but points me in the same direction. Can you try the the same thing? Your error says "The template variable 'currentConfig' is not valid: The language expression property 'bau.eu' doesn't exist, available properties are '[omitted], prod'". If my theory is correct, you do have a BotEnv app setting, but is value is bau.eu. If so, please change it to "prod".

**Comment by Irbis377** [comment]
Hi @Andrea-Orimoto 
Do you mean this? 
![11](https://user-images.githubusercontent.com/24790338/38607807-554768ec-3d82-11e8-9c67-0845f7f73cd9.PNG)
or this?
![22](https://user-images.githubusercontent.com/24790338/38608423-f4f994fe-3d83-11e8-8148-e30d3618649e.PNG)

Or I need to set BotEnv in any another place? 

I have error 400 again

**Comment by Andrea-Orimoto** [comment]
@Irbis377, no, please got to the Azure Portal, look for your bot in App Services, open it, go to settings, and open Application Settings. You should add/modify BotEnv in there.
![image](https://user-images.githubusercontent.com/17152540/38634961-db998128-3d78-11e8-8856-183e5be9e83c.png)

![image](https://user-images.githubusercontent.com/17152540/38634990-eaa953d2-3d78-11e8-9428-929d6937b685.png)

**Comment by Irbis377** [comment]
@Andrea-Orimoto  
i have no this area 
![11212](https://user-images.githubusercontent.com/24790338/38805316-0f1c6188-417e-11e8-846b-bdc868021ad4.png)

i have only this 
![bot](https://user-images.githubusercontent.com/24790338/38805235-cba9a49c-417d-11e8-9570-ccf948be7984.png)


how i can create it?

**Comment by Irbis377** [comment]
Hi @Andrea-Orimoto 

i have no this area 
![11212](https://user-images.githubusercontent.com/24790338/38805464-939559a6-417e-11e8-9ba1-54f8adfc1c95.png)

i have only this and i set BotEnv = prod like you said
![bot](https://user-images.githubusercontent.com/24790338/38805609-11e49164-417f-11e8-82ca-fc24f27da0e5.png)

but i still have error 400

**Comment by Andrea-Orimoto** [comment]
Awesome! glad you figured it out. Closing this issue.
