### ISSUE TITLE
[Skype] There was a problem synchronizing your bot to Skype.

### ISSUE THREAD

**Issue by sudeep-cedcoss** [Microsoft/BotBuilder#4402]
## Bot Info
* SDK Platform: Node.js
* SDK Version: 6.0.0
* Active Channels: Skype
* Deployment Environment: local development with Emulator

## Issue Description
On sending message to bot no request is send to my server. When reload dev.botframework.com/bots/channels?id=<bot-name> then I recieve an error of 500: Internal server error.
When I am sending message through emulator it works totally fine.
![bot-emulator](https://user-images.githubusercontent.com/30074883/38138091-74575804-3446-11e8-83f5-704ffd760f8d.png)

![bot-issue](https://user-images.githubusercontent.com/30074883/38137992-b96e3666-3445-11e8-8ba9-1f6ac771a2a1.png)

## Actual Results
On sending message to bot no request is send to my server.

**Comment by PulseDiver** [comment]
i have same errors, all tests **bot <->myservice** is ok, but **bot <-> skype** i see errors - There was a problem synchronizing your bot to Skype.

**Comment by sudeep-cedcoss** [comment]
Can anyone help me regarding this please?

**Comment by stevengum97** [comment]
Cross-linking similar issues #4401, #4388, #4394.

@sudeep-cedcoss,  @PulseDiver @agpalma59, @Ananya-96, please follow this issue for now as it appears you're all running into the same problem.

The dev team is currently investigating this problem and we will be posting updates on the situation here. 

If there are any changes in your bot's status or if you have any new/different information please share it here.

**Comment by stevengum97** [comment]
@sudeep-cedcoss, @PulseDiver, @agpalma59, @Ananya-96 the issue has been mitigated, can you verify that the problem has been fixed for you?

**Comment by PulseDiver** [comment]
@stevengum97 old bot not work in skype, but new created bot  works fine! thanx

**Comment by Ananya-96** [comment]
@stevengum97  Yes errors got fixed. Thanks

**Comment by stevengum97** [comment]
Closing issue due to a released fix and inactivity. If anyone is still having problems please file a new issue.
