### ISSUE TITLE
Cortana channel stopped working

### ISSUE THREAD

**Issue by achekh** [Microsoft/BotBuilder#4403]
## Bot Info
* SDK Platform: Node.js
* SDK Version: 3.14.1
* Active Channels: Cortana, Skype, Web Chat
* Deployment Environment: Azure Web App Bot

## Issue Description
The Cortana channel stopped working for the bot today. 
We traced the issue to the bot response, the response is generated properly, but the channel doesn't wait for the response and displays error I'm sorry... in around a second.
The azure portal displays errors for the Cortana channel saying "There was an error sending this message to your bot: HTTP status code GatewayTimeout".

## Reproduction Steps
1. Invoke bot in Cortana with any command (ask eeva hello)

## Expected Behavior
Welcome message from the bot.

## Actual Results
Cortana displays: I'm sorry something went wrong. Try again later.
![2018-03-30_1818](https://user-images.githubusercontent.com/2707700/38145108-6da92ad2-3450-11e8-9bb8-8010882174cc.png)
![2018-03-30_1817](https://user-images.githubusercontent.com/2707700/38145116-7190ab34-3450-11e8-9e6c-5822a44249f0.png)
![error](https://user-images.githubusercontent.com/2707700/38145131-7fe1c254-3450-11e8-9b7d-e7cd54cdf9ab.png)

**Comment by EricDahlvang** [comment]
Hi @achekh 

The Cortana had some issues last week, but they have been resolved.  Are you still experiencing problems?

**Comment by achekh** [comment]
No, the issue has disappeared over the weekend.
