### ISSUE TITLE
Skype channel Approved but not published

### ISSUE THREAD

**Issue by smartchatco** [Microsoft/BotBuilder#4404]
## Bot Info
* SDK Platform: .Net
* SDK Version: latest
* Active Channels:  Skype, Webchat, Bing, Skype for Business 
* Deployment Environment:  Azure Bot Service, Azure Web App Service,

## Issue Description
I submitted my skype bot "Item Finder" for review, and it finally got to approved status.  It has been a couple days and I do not see it in the skype directory.  Is there something else I need to do?

## Reproduction Steps
1. Submit bot for review
2. Wait until it is approved
3. Noticed it was approved, but not published in skype bot directory

## Expected Behavior
Expected it should have been published upon approval.

## Actual Results
It was not published as far as I can tell.

![capture](https://user-images.githubusercontent.com/37940893/38151522-a709c986-3431-11e8-83ea-0b88a3f28931.PNG)

**Comment by JasonSowers** [comment]
Publishing does not instantly occur after approval.  Is your bot still not published at this point?

**Comment by smartchatco** [comment]
@JasonSowers Nope still not published.  At least I don't see it.

**Comment by JasonSowers** [comment]
Please provide your app ID so I can reach out to the Skype team for you.

**Comment by JasonSowers** [comment]
I will update you when I have some information for you.

**Comment by JasonSowers** [comment]
@smartchatco From the skype team:

> There is a bug on our side. Newly approved/published bots are not getting displayed on the skype client. We have investigated what is causing this bug, hopefully by the end of this week the issue will be resolved.

**Comment by JasonSowers** [comment]
Are you able to see your bot yet?

**Comment by smartchatco** [comment]
Not yet, I appreciate you checking though.

**Comment by JasonSowers** [comment]
If on Monday it is still not published I will reach out again since they did say "end of the week".

**Comment by smartchatco** [comment]
I don't think so. The reason I am not sure is on Windows client, it does not show up in the bot directory, nor  when I search for it.  In Android it does not show up in the bot directory (the place with all the categories), but when I search for it it does show up, although it also finds a bunch of non-certified bots that was as well.  I had thought those were not searchable, but I could be wrong. Thanks

**Comment by JasonSowers** [comment]
I have been informed that this should now be fully working as per the Skype team.  Can you confirm it is now working?

**Comment by smartchatco** [comment]
Yes it is @JasonSowers  thanks so much.
