### ISSUE TITLE
[Feature Request] LUIS API to retrieve all entities

### ISSUE THREAD

**Issue by alucard001** [Microsoft/BotBuilder#4410]
## Bot Info
* SDK Platform: Node.js
* SDK Version: Latest
* Active Channels: - 
* Deployment Environment: Local development

## Issue Description
I am currently working on a custom UI to manage (Create/Read/Update/Delete) an entity and its values.  All I did was to get a list of all entities first and then let our user to do anything they like.

I have gone through the LUIS API 2.0 several times and, surprising, there is no such API that will list out all the entities I have created in MS LUIS backend admin. 

<img width="1046" alt="2018-04-02 21 06 00" src="https://user-images.githubusercontent.com/1968244/38197339-3509a276-36ba-11e8-964c-05c30d2ddd41.png">

Is there any way I can do that?  Without that, it seems that I cannot use all the other API that requires entities IDs.

Thank you.

**Comment by stevengum97** [comment]
Unfortunately as you noted, there is no API that performs this service at this time. What I've done in the past is to write a python script that iterates over the _exported app file's_ training data to extract entities.

**Comment by stevengum97** [comment]
If there isn't a user suggestion on [UserVoice](https://cognitive.uservoice.com/forums/551524-luis) so far please feel free to create one!

**Comment by JasonSowers** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
