### ISSUE TITLE
Get intention that was consulted in LUIS

### ISSUE THREAD

**Issue by odirleiborgert** [Microsoft/BotBuilder#4411]
## Bot Info
* SDK Platform: Node.js
* SDK Version: 3.14.0
* Active Channels: Skype, Messenger
* Deployment Environment: Emulator

## Issue Description
Every time I have an appointment for LUIS I want to pick up the intention and do some kind of treatment. My question is where I do it.
The treatment I want to do is to send this to my private API.

**Comment by fanidamj** [comment]
If I understand your question correctly, you can use [Middleware](https://github.com/Microsoft/BotBuilder-Samples/blob/master/Node/capability-middlewareLogging/app.js) for treating intents. If not can you please brief the question again. Hope this helps!!

**Comment by odirleiborgert** [comment]
HI @fanidamj , thanks for the feedback

I would like that after the intent is returned from LUIS I could get this value and send it to my API, however I did not find this property using the middleware.

[Imgur](https://i.imgur.com/tohTjqt.png)

**Comment by odirleiborgert** [comment]
Resolved with:

```
bot.dialog('sms', (session, args, next) => {
       if (args && args.intent) {
             console.log(args.intent);
       }
});
```
