### ISSUE TITLE
[Cortana & .NET SDK] Cortana FormFlow problems

### ISSUE THREAD

**Issue by fr6087** [Microsoft/BotBuilder#4414]
## Bot Info
* SDK Platform: .NET
* SDK Version: 
* Active Channels: Cortana, Skype, Direct Line, Web Chat
* Deployment Environment: Azure Bot Service, local development with Emulator, Cortana

## Issue Description
I created a .json file for my FormFlow Dialoge. It contains a .Before Message Property in the first properties object as in the AnnotatedSandwich.json. Cortana does not interpret the Before message correctly. It is displaying the message AFTER asking the first question. And then, Cortana is unable to proceed with the other questions.

## Code Example
`"properties": {

    "Vorname": {
      "Before": [
        {
          "Message": [
            "Welcome at form section 1"
          ]
        }
      ],
        "Prompt":
        {
          "Patterns": [ "What is your given name?" ]
        },
        "type":
        [
          "string",
          "null"
        ]
    },
`

## Reproduction Steps
1. create json file in Bot Temlate as described in AnnotatedSandwich, add a "Before-property"
2. let the Formbuilder access the JSON file
3. publish the Bot to Azure
4. register the Bot for Cortana channel
5. check that your device's settings are for USA
6. invoke the Bot as Cortana Skill by invocation <tell INVOCATION_NAME something>

## Expected Behavior
I expected the before message to be displayed before the question prompting for the particular property.

## Actual Results
After answering "what is your given name"
the before message appears and the formflow dialoge stops. The canvas is not refreshed with the next question.

**Comment by EricDahlvang** [comment]
I'll look into this and get back to you soon.

**Comment by fr6087** [comment]
I know, it's not strictly issue related, but suppose I want to access the UserInfo.GivenName property from the Cortana Notebook and integrate that into the prompt "what is your given name?" Like "I got your given name from the notebook as <user's name>. Is that correct?" How would I express that in json code? I know I can attach Validate functions. But they are executed after the prompt. Can I call a function before a prompt?

**Comment by EricDahlvang** [comment]
It seems the "Before" is actually being sent, but it is followed immediately by the next message.   If "Before" is not read by cortana, it just flashes on the canvas.  I found some code here: https://stackoverflow.com/questions/44464575/formflow-prompts-are-not-being-spoken-in-cortana-skills that might help.  If you add a **IMessageActivityMapper** that checks for and empty .Speak, it seems to then read out the Before followed by the next message.  Please try this, and let me know if it solves your issue:

```
            Conversation.UpdateContainer(
                builder =>
                {
                    builder
                       .RegisterType<TextToSpeakActivityMapper>()
                       .AsImplementedInterfaces()
                       .SingleInstance();
                });
```

```
public sealed class TextToSpeakActivityMapper : IMessageActivityMapper
{
    public IMessageActivity Map(IMessageActivity message)
    {
        // only set the speak if it is not set by the developer.
        var channelCapability = new ChannelCapability(Address.FromActivity(message));

        if (channelCapability.SupportsSpeak() && string.IsNullOrEmpty(message.Speak))
        {
            message.Speak = message.Text;
        }

        return message;
    }
}
```

I haven't tried this, but I think you should be able to  get the username via c# script in a Define property.  
https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-formflow-json-schema#additional-properties-as-peers-of-the-type-property

**Comment by EricDahlvang** [comment]
@fr6087  Is the above code a valid workaround for you?

**Comment by fr6087** [comment]
@EricDahlvang I don't think that is going to solve the problem. I have already added this code snippet from Jadib to my bot earlier. By the way, I think that code sample has a spelling mistake, at least my bot code is only finding "TextToSpeechActivityMapper". Also, I am using a modified version of the code as follows (maybe related to the problem)
``

**Comment by EricDahlvang** [comment]
Using this .json file:

```
{
  "type": "object",
  "Templates": {
    "NotUnderstood": {
      "Patterns": [ "I do not understand \"{0}\".", "Try again, I don't get \"{0}\"." ]
    },
    "EnumSelectOne": {
      "Patterns": [ "What kind of {&} would you like on your sandwich? {||}" ],
      "ChoiceStyle": "Auto"
    }
  },
  "properties": {
    "Sandwich": {
      "Prompt": { "Patterns": [ "What kind of {&} would you like? {||}" ] },
      "Before": [ { "Message": [ "Welcome to the sandwich order bot!" ] } ],
      "Describe": { "Image": "https://placeholdit.imgix.net/~text?txtsize=16&txt=Sandwich&w=125&h=40&txttrack=0&txtclr=000&txtfont=bold" },
      "type": [
        "string",
        "null"
      ],
      "enum": [
        "BLT",
        "BlackForestHam",
        "BuffaloChicken",
        "ChickenAndBaconRanchMelt"
      ]
    },
    "Length": {
      "Prompt": {
        "Patterns": [ "What size of sandwich do you want? {||}" ]
      },
      "type": [
        "string",
        "null"
      ],
      "enum": [
        "SixInch",
        "FootLong"
      ]
    },
    "Rating": {
      "Describe": "your experience today",
      "type": [
        "number",
        "null"
      ],
      "minimum": 1,
      "maximum": 5,
      "After": [ { "Message": [ "Thanks for ordering your sandwich!" ] } ]
    }
  }
}
```
With this global.asax.cs:

```
public class WebApiApplication : System.Web.HttpApplication
    {
        protected void Application_Start()
        {
            GlobalConfiguration.Configure(WebApiConfig.Register);

            Conversation.UpdateContainer(
                builder =>
                {
                    builder
                       .RegisterType<TexttoSpeech>()
                       .AsImplementedInterfaces()
                       .SingleInstance();
                });
        }

        public sealed class TexttoSpeech : IMessageActivityMapper
        {
            public IMessageActivity Map(IMessageActivity message)
            {
                var channelCapability = new ChannelCapability(Address.FromActivity(message));

                if (channelCapability.SupportsSpeak() && string.IsNullOrEmpty(message.Speak))
                {
                        message.Speak = message.Text;
                }

                return message;
            }
        }
    }
```

Results in:
![cortanabefore](https://user-images.githubusercontent.com/11055362/38888369-44cb0d22-4230-11e8-84e9-57c8f188e5f2.gif)
