### ISSUE TITLE
[.NET SDK] FormFlow "hidden" messages localization

### ISSUE THREAD

**Issue by asfyra** [Microsoft/BotBuilder#4415]
## Bot Info
* SDK Version: 3.14.1.1
* Active Channels: Emulator
* Deployment Environment: local development with Emulator

I want to ask how would i be able to localize the help, status and generaly all the messages that formflow generates.
I am interested in localizing all the "hidden"  form flow messages, that are not exposed through RView to the generated resx file.

I would also like to ask if it's possible to localize formfolw command keywords such as help, back, quit etc.

Thanks in advance
Alex

**Comment by fanidamj** [comment]
You can go through Localization [document](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-formflow-localize) and let us know if there is something missing or need to be documented.
And to answer your second question, can you please explain what you mean by "hidden" form?
And to answer you third question, the keywords have already been localized as [described here](https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Resource/Resources.nl.resx) and you need do it again.

**Comment by fr6087** [comment]
[Resources.de.zip](https://github.com/Microsoft/BotBuilder/files/1879031/Resources.de.zip)
Ah, but thanks for asking the question. I translated the Resource.nl.resx file to German (in the attachment). After reading that submitting it requires signing a contributer agreement and other technical stuff I decided that I'm too lazy to read into the details of that process :)

**Comment by asfyra** [comment]
After further researh, i think the only solution to translate the built-in form flow messages, is to follow the instructions from this [post](https://github.com/Microsoft/BotBuilder/issues/3082), for the Greek language.
