### ISSUE TITLE
[.NET SDK] System.web.Exception "Not found" thrown using SaveAsync and FlushAsync functions while storing state in azure table store.

### ISSUE THREAD

**Issue by priyankasyal** [Microsoft/BotBuilder#4417]
## Bot Info
* SDK Platform: .NET
* SDK Version : Microsoft.Bot.Builder version=3.12.2.4
                        Microsoft.Bot.Builder.Azure  version=3.2.5
* Active Channels:Chat, Cortana
* Deployment Environment: Local + Azure

## Issue Description
System.web.Exception "Not found" thrown using SaveAsync and FlushAsync functions while storing state in azure table store.
This works and throws exception inconsistently.
Sometimes if I remove FlushAsync and the start and stop my bot and then add FlushAsync function and then start my bot again, I don't see this exception.

## Code Example
Register azure table storage as bot data store:
					   var store = new TableBotDataStore(ConfigurationManager.ConnectionStrings["StorageConnectionString"].ConnectionString);
					   builder.Register(c => store)
						   .Keyed<IBotDataStore<BotData>>(AzureModule.Key_DataStore)
						   .AsSelf()
						   .SingleInstance();

Then use botDataStore functions to save data in the table

await botDataStore.SaveAsync(key, BotStoreType.BotPrivateConversationData, botData, CancellationToken.None);
await botDataStore.FlushAsync(key, CancellationToken.None);

## Reproduction Steps
1. Use Azure Table Store
2. saving conversation data using SaveAsync and FlushAsync Function
If I remove FlushAsync and then use , this exception is not seen, then if I add it again it works for a while but then starts giving exception at FlushAsync 
Without FlushAsync my flow does not work properly. Latest data is not written to azure table.

## Expected Behavior
Data should be saved.

## Actual Results
exception -
	{"Not Found"}	System.Web.HttpException
Stack trace - 
	"   at Microsoft.Bot.Builder.Azure.TableBotDataStore.<Microsoft-Bot-Builder-Dialogs-Internals-IBotDataStore<Microsoft-Bot-Connector-BotData>-SaveAsync>d__9.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Bot.Builder.Dialogs.Internals.CachingBotDataStore.<Save>d__10.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Bot.Builder.Dialogs.Internals.CachingBotDataStore.<Microsoft-Bot-Builder-Dialogs-Internals-IBotDataStore<Microsoft-Bot-Connector-BotData>-FlushAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at csibot.BotState.<SetPrivateConversationDataAsync>d__6.MoveNext() in

**Comment by EricDahlvang** [comment]
Please provide the surrounding code, or a minimal project that reproduces the issue.  Where/when exactly are you calling SaveAsync and FlushAsync?

**Comment by EricDahlvang** [comment]
Closing due to no response.
