### ISSUE TITLE
[Azure Bot Service] Endpoint URL must be a valid HTTPS URL

### ISSUE THREAD

**Issue by waqasyousafy** [Microsoft/BotBuilder#4418]
getting this defined error while registering bot . 
while putting the https url in the configuration end point box
![error](https://user-images.githubusercontent.com/22340353/38290942-f9324422-37f6-11e8-9d6b-9f04e43ae5df.png)

**Comment by EricDahlvang** [comment]
Do you have spaces in front of "https"?

**Comment by waqasyousafy** [comment]
not

**Comment by EricDahlvang** [comment]
The only way I'm able to reproduce this is by having a space in front of the url.  Can you paste here the url you are using?

**Comment by waqasyousafy** [comment]
in the above uploaded secreenshort the url is mentioned

**Comment by EricDahlvang** [comment]
I'm not able to repeat this.  I see the screenshot, but I'm asking you to paste the url.  Do you have some other suggestion for how I should help you resolve this issue?

**Comment by JasonSowers** [comment]
Can you try another https url and see if that works? Try a new ngrok URL or any https URL really.  We are unable to reproduce this error.
