### ISSUE TITLE
[Node.js SDK] How to handle ETIMEDOUT error in nodejs bot?

### ISSUE THREAD

**Issue by pyephyoeaung** [Microsoft/BotBuilder#4419]
error ocurred { Error: connect ETIMEDOUT x.x.x.x:443

    at new Error (native)

    at Object.exports._errnoException (util.js:1026:11)

    at exports._exceptionWithHostPort (util.js:1049:20)

    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)

    code: 'ETIMEDOUT',

    errno: 'ETIMEDOUT',

    syscall: 'connect',

    address: 'x.x.x.x',

    port: 443 }

**Comment by EricDahlvang** [comment]
This blog post might help: https://blog.botframework.com/2018/03/05/fix-snat-exhaustion-node-js-bots/

**Comment by EricDahlvang** [comment]
Which version of the sdk is the bot using?

How many requests per minute is the bot processing?

What type of server is the bot hosted on?

Can you share your bot's code, or a minimal project we can use to reproduce this?

**Comment by pyephyoeaung** [comment]
Node6.9.1
800 requests per min
S1 small size

**Comment by EricDahlvang** [comment]
Which version of the Bot Builder SDK? 
https://www.npmjs.com/package/botbuilder

**Comment by pyephyoeaung** [comment]
Thanks , my Botbuilder version is  3.14.0

**Comment by EricDahlvang** [comment]
Please upgrade to 3.14.1 https://www.npmjs.com/package/botbuilder

There have been a number of changes since 3.14.0:
https://github.com/Microsoft/BotBuilder/commits/master

**Comment by EricDahlvang** [comment]
@pyephyoeaung  Are you still experiencing this issue after upgrading to 3.14.1?

**Comment by pyephyoeaung** [comment]
sure @EricDahlvang 
What kind of instance size do you recommended for production chat bot?

**Comment by EricDahlvang** [comment]
@pyephyoeaung Because we have no way of knowing what your bot is actually doing when a message is processed, we cannot make an instance size recommendation.  You will need to experiment with different instance sizes and possibly also scale sideways to multiple nodes in order to handle the load.

**Comment by pyephyoeaung** [comment]
Thanks @EricDahlvang . I think this timeout issue can cause of small instance size.
When I scale up and scale out instance I didn't found that issue again.

**Comment by vamzz1** [comment]
I think scaling up and scaling out might be a temporary fix as it won't hit the SNAT thresholds under high load. Not sure if this is the best way to solve this issue. I've been struggling to get the configuration right with the keepaliveAgent module.

**Comment by vamzz1** [comment]
We were using `websockets` as true with directline. We set `webSockets` as false and things started to work as expected. No more delay between messages. No more timeouts.
