### ISSUE TITLE
direct line: channelData always null

### ISSUE THREAD

**Issue by berhir** [Microsoft/BotBuilder#442]
We have built our own direct line channel but we are facing some problems with the channelData field.

1. The C# NuGet package is out of date: channelData is now a JSON object and not a string. The Conversations.GetMessages method throws an "Unable to deserialize the response."  exception.
As a workaround we have created our own client to access the direct line api. But we hope there will be an updated version of the NuGet package very soon.
2. No matter what we try to pass as channelData, in the bot application the message.ChannelData field is always null.

**Comment by dandriscoll** [comment]
Yes, we're working on a revised version right now. Thanks very much for your patience -- we should have it available soon.

**Comment by dandriscoll** [comment]
The new version is available at http://www.nuget.org/packages/Microsoft.Bot.Connector.DirectLine/1.0.2 and it should fix this problem. Let me know if it doesn't. Thanks!

**Comment by v-thgratMSGit** [comment]
Closing this issue. Thanks!
