### ISSUE TITLE
[Node.js SDK] Speech is not working on Emulator and channels.

### ISSUE THREAD

**Issue by sourabhlodha** [Microsoft/BotBuilder#4421]
I used session.say() and iMessage.speak but It doesn't work in channels.Can you Help me out in resolving the issue? 
Below is mention code which I used in waterfall model.
session.say('Your insurance ploicy number is 123', 
    'Your insurance ploicy number is 123.', 
    { inputHint: builder.InputHint.ignoringInput }
);

**Comment by nodeomega** [comment]
Which channels are you trying to  use Speak in?

**Comment by sourabhlodha** [comment]
I am trying on Skype and Facebook messenger But it doesn't support.Even For the Testing purpose, I try on bot emulator.
Yes, I try both Speak In and session say .

**Comment by nodeomega** [comment]
Right now there seems to be an issue with speech on the bot emulator, as I have just learned today.  I'm checking on the availability of Skype and Facebook Messenger and speech, but I don't *think* Facebook Messenger* has that capability.  Allow me to double-check this.

**Comment by sourabhlodha** [comment]
@nodeomega  Yes Facebook Messenger doesn't have the capability but Can you check with Skype and bot emulator.Thank you for helping me in resolving the issue.

**Comment by sourabhlodha** [comment]
@nodeomega Can you please Update me the speech for skype or any alternative function to use the speech in skype.

**Comment by sourabhlodha** [comment]
@nodeomega Any Updates Team.

**Comment by nodeomega** [comment]
As far as I know, one would have to use the botbuilder-calling NPM package to use speech in Skype.  I am still investigating this issue and do not have a definite solution at this time.

**Comment by sourabhlodha** [comment]
Can you provide me any one sample which is working for the speech on skype channel?

**Comment by nodeomega** [comment]
Ok, here's what I have found so far with this:
- As far as speech working on emulator (mentioned earlier in the thread), it seems to only speak when you use the microphone function to speak to the bot.  Otherwise the bot will use text.
- As far as Skype is concerned, I have only been able to get any speech to work with the bot myself when in a call with Skype.  I do not know if you are using a mobile version of Skype or desktop version, but I did find that if I tried to use the microphone control on iOS skype, the bot did not recognize the recording as input (as far as interpreting the text from sound), and the desktop version doesn't seem to have that microphone option at all.

Are you using the calling function or normal chat functions?  Because if you're just using chat, I don't think the bot will speak in Skype.  Just calls.

**Comment by sourabhlodha** [comment]
@nodeomega I try on emulator but it doesn't working can you provide me with any sample which is working on the emulator on speech. Only in direct line channel, it's working.

As its critical for me. Please help me with that.

**Comment by nodeomega** [comment]
Sample code for the bot and the dialog I was using to make it work in the Emulator when using the microphone/speak mode:

    var bot = new builder.UniversalBot(connector);
    bot.set('storage', tableStorage);

    bot.use({ 
        botbuilder: (session, next) => {
            session.sendTyping(); 
            console.log(session.message); 
            next(); 
        }, 
        send: (event, next) => {
            console.log(event); next(); 
        } 
    });

    bot.dialog('/', function (session) {
        let msg = new builder.Message(session)
        .speak(`You said ${session.message.text}`)
        .text(`You said ${session.message.text}`)
        .inputHint(builder.InputHint.acceptingInput);

        session.send(msg).endDialog();
        //session.send('You said ' + session.message.text);
    });

Tested with Bot Framework Emulator v3.5.36

When I spoke into it (I said "test"), it did speak to me and put in chat "you said test."  Does this at least work in your emulator?  The rest of the code for this particular dialog is pretty much the default setup when creating a Node.JS Echo Bot on Azure.  (Minus the skype callbot part.  I can add the entire app.js file I have if this doesn't work).

**Comment by stevkan** [comment]
Closed due to lack of response.
