### ISSUE TITLE
FormFlow and LuisDialog

### ISSUE THREAD

**Issue by ganeshnj** [Microsoft/BotBuilder#443]
I would like to use both FormFlow and LuisDialog in a combination.

For example, if you have an Intent OrderSandwich that initiate the conversation. This should follows a FormFlow that will ask the question and user can give the response in Natural Language with the help of Luis.

Conversation
User: I want to buy a sandwich?
Bot: Off course, we have A, B, C types
User: What is A? (Optional)
Bot: Its made up of......
User: Okay, I would like to take B
Bot: Would you like to have a medium or large
User: What is the difference between medium and large (Optional)
Bot: Medium cost xx.xx while large cost xx.xx but.....
User: Okay I will take the large one
Bot: Do you have any other questions
User: No thanks, bye
Bot: Have a nice day

Even one can ask more details about the types of Sandwich, but such queries are optional.

Anyone has tried or is it possible with current version of Bot Framework?

**Comment by alexdrenea** [comment]
I've been trying to achieve similar things in the past few days and my conclusion is that it's not possible with the current implementation.
There are a few built-in commands in the form flow dialog (help, ?, status, quit, back) and I was thinking of adding a new one: "define" to achieve exactly what you described. Didn't have time to write the code though...

**Comment by chrimc62** [comment]
There is no way to do this in the current framework, but we are working on a general way of composing together dialogs that should help.

**Comment by alexdrenea** [comment]
Do you have an open issue you could link so we can keep track on that progress? Would be interested to get notifications on this.

**Comment by ganeshnj** [comment]
I've tried with LuisDialog by making intents and for each message exchange but its really difficult to maintain the conversation flow. I'd be more than happy to see such a conversational logic in the coming versions.

**Comment by ankitbko** [comment]
@chrimc62 In addition to above, the control words such as help, status, back should also be interfaced with Luis. For example to change a previous entered form field PizzaSize, allow user to enter "I want to change size". Similarly help, status etc would also follow.

**Comment by NehaShaikh786** [comment]
@ganeshnj @ankitbko @chrimc62 @alexdrenea 
Hi,
I am trying to create a bot using LUIS intents and i need a conversation flow. How to implement a context flow from language understanding?
Actual Result- i have intent named as "moisturizer" and its utterance is "do you have moisturizer" but when i retrain the model and test "do you have abcd" it still hit the moisturizer intent, which i don't expect. I want this utterance to hit to "None" intent.
Expected - I have huge data in my model, after hitting to top score intent i am using dialog for further conversation (also adding to this do you have another solution except FormFlow and Dialog?). So i don't want my dialog to initiate when user enters the partial utterance as mentioned above. please provide some solution to this.
