### ISSUE TITLE
Error 404 on Facebook Callback Url in Azure Bot

### ISSUE THREAD

**Issue by emanueleleoni** [Microsoft/BotBuilder#4437]
I've created a bot with Bot Framework hosted in Microsoft Azure and It worked fine until yesterday. From that moment when the bot tries to call the RootDialog, It generates an exception
```
await Conversation.SendAsync(activity, () => new RootDialog());
```
The exception message is
> Bad Request 
> in Microsoft.Bot.Connector.MicrosoftAppCredentials.<RefreshTokenAsync>d__26.MoveNext()

If I call my callback url I get an error 404. 
Any helps is appreciated. 
Thanks

**Comment by emanueleleoni** [comment]
I don't know why, but now It works fine and I don't have the exception anymore. 
Could you explain me why?

**Comment by JasonSowers** [comment]
SO post duplicate https://stackoverflow.com/questions/49691469/error-404-on-facebook-callback-url-in-azure-bot
