### ISSUE TITLE
[Slack] Slow incoming messages from bot framework to bot 

### ISSUE THREAD

**Issue by v46** [Microsoft/BotBuilder#4439]
Hi folks,

Starting about an hour or so we are seeing a latency of 10 seconds for all our slack channel bots. This is the time taken from when a user types a message and our bot receiving it from bot framework.

Outgoing messages are fast and SFB bots don't seem to be impacted. Are you aware of a production outage?

We are running 3.8 of the Node SDK as a Bot Service (outside Azure). Our bots are migrated and use a custom (in-memory store). We have also configured bot framework to use Slack's event API for (bot framework) integration.

Several of our customers are starting to report these latency issues today, can you please advise if there are known issues you are tracking?

**Comment by EricDahlvang** [comment]
We will investigate, and get back to you shortly

**Comment by EricDahlvang** [comment]
There appears to have been a temporary issue with Slack bots isolated to a data center in Europe.  It seems to have corrected itself after just a few minutes.  Are any if your bots still experiencing issues?

**Comment by v46** [comment]
Thanks for the update Eric. We are still seeing latency issues with our slack bots.

**Comment by pradgnyak** [comment]
We are also seeing the same problem for our slack bots. Any insights?

**Comment by EricDahlvang** [comment]
Apologies, I spoke too soon.  And my investigation was incorrect.

Someone higher up than myself has isolated the problem, and is actively working on a resolution.  I will post updates as I get them.

**Comment by EricDahlvang** [comment]
Okay, NOW things are back to normal.

Please let me know if you're still experiencing latency issues.

**Comment by v46** [comment]
Thanks, it’s working now.
