### ISSUE TITLE
enter/send button in webchat window is not working for some browsers

### ISSUE THREAD

**Issue by himanshushukla254** [Microsoft/BotBuilder#4441]
## Bot Info
* SDK Platform:Nodejs
* Active Channels: webchat using iframe tag on website
* Deployment Environment: Azure Bot service

## Issue Description
For some browsers enter/send button in chat bot window is not working.
For eg, It is working for chrome 66 beta but not for chrome 65.
similarly it is not working for Microsoft edge. After typing any text the button should be greyed out.
But it's coming up as expected. 

PFA screenshot for clarification. 

PS: Everything is working fine in test in webchat window provided on azure portal.

## Expected Behavior

It should turn to blue and on enter or click on send button the message should go.

## Actual Results
Not even greying out. Enter/send button not working.

![test](https://user-images.githubusercontent.com/15158684/38488147-18bf233e-3c00-11e8-8e57-45a811f6977a.JPG)

**Comment by JasonSowers** [comment]
This issue would be best to file over in the [webchat repo](https://github.com/Microsoft/BotFramework-WebChat).  That way the webchat team is aware of this and the experts over there can look into it.
