### ISSUE TITLE
[C#] Flexibility in presentation of a Form field

### ISSUE THREAD

**Issue by ankitbko** [Microsoft/BotBuilder#445]
How do I change how a Form field is displayed in the channel. For example, an enum is displayed as button in Facebook and a list on other channels(not supporting buttons). But how do I make it so it _always_ displays as a list?
The issue is that I am not able to customize exactly _how_ a field is displayed. Strings are always displayed as plane text and enum are always generated as buttons. One might want to display a particular field with increasing level of details in Generic Template in Facebook like below.
![Generic Template](https://scontent.fmaa1-1.fna.fbcdn.net/t39.2178-6/12995604_817115938419079_1836906465_n.png)
It also extends to sending a message or confirmation. One might want to send a message as a Receipt before/after confirming the order or send it as part of confirmation.
<img src="https://scontent.fmaa1-1.fna.fbcdn.net/t39.2178-6/12995563_1078829122181414_346103097_n.png" width="200px"/>
How do I achieve this? Also how do I utilize the [Message.ChannelData](http://docs.botframework.com/connector/custom-channeldata/) feature to tailor make response for a field?  What am I missing here?

**Comment by chrimc62** [comment]
You can control text/buttons by the setting your ChoiceStyle either in the form configuration, your templates or prompts.  Auto will be buttons unless multiple selects are allowed, AutoText will decide on inline vs. multi-line text.  We don't yet have easy to use ways to manipulate ChannelData unless you add middleware which manipulates the message as it flows through.
