### ISSUE TITLE
Teams API responding with 500

### ISSUE THREAD

**Issue by bilby91** [Microsoft/BotBuilder#4451]
## Bot Info
* SDK Platform: Node.js
* SDK Version: Latest
* Active Channels: MS Teams, Slack
* Deployment Environment: AWS

## Issue Description
We are getting 500 errors when trying to interact with Teams API. When getting the channels of team, getting members, etc.

## Expected Behavior
API should respond correctly.

## Actual Results
We are getting an error message with the following information.

```
The page cannot be displayed because an internal server error has occurred.
```

**Comment by EricDahlvang** [comment]
Hi @bilby91 

Are you using this library: https://www.npmjs.com/package/botbuilder-teams ?  

Please share the code you are using to get "the channels of a team" and "getting members".  So we can reproduce the issue.

**Comment by bilby91** [comment]
@EricDahlvang We are using the botbuilder-teams library. Either way it seems to be working now. 

Thanks
