### ISSUE TITLE
Value of activity is "{}" when it should be equal to custom data from Action.Submit

### ISSUE THREAD

**Issue by rcasto** [Microsoft/BotBuilder#4452]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.8.5
* Active Channels: Direct Line
* Deployment Environment: local development with/without Emulator

## Issue Description
Whenever an Action.Submit has a custom data object, this data object is not sent or retrievable/accessible on the .NET controller

## Code Example
Here is the Adaptive Card I am sending to the client for a test:
![image](https://user-images.githubusercontent.com/869330/38582348-467c23ca-3cc4-11e8-9d41-a1586e687cb6.png)

Fiddler trace of activity sent from emulator:
![image](https://user-images.githubusercontent.com/869330/38583300-69a25d76-3cc7-11e8-8f12-6109b4a8af1b.png)

## Reproduction Steps
1. Send Adaptive Card to client pictured above 
2. Click the "Click me" button
3. Notice controller only receives empty object instead of actual object payload attached to card

## Expected Behavior
Value should be a serialized string of the object or be the object sent up in the initial activity

## Actual Results
Activity received in .NET controller:
![image](https://user-images.githubusercontent.com/869330/38584498-5874033e-3ccb-11e8-848f-a24f04710cd3.png)

Serialized version of Value on Activity:
![image](https://user-images.githubusercontent.com/869330/38584564-8f9eba70-3ccb-11e8-9c71-fc15727919a6.png)

**Comment by EricDahlvang** [comment]
Please try upgrading the BotBuilder package to the latest: https://www.nuget.org/packages/Microsoft.Bot.Builder/

```cs
reply.Attachments = new List<Attachment>(){new Attachment()
{
    ContentType = AdaptiveCard.ContentType,
    Content = new AdaptiveCard()
    {
        Actions = new List<AdaptiveAction>()
        {
            new AdaptiveSubmitAction()
            {
                Title = "Click me",
                DataJson = JsonConvert.SerializeObject(new
                {
                    Testing = "here is some data",
                    List = new List<string>()
                    {
                        "item 1",
                        "item 2"
                    }
                })
            }
        }
    }
}};
```
![image](https://user-images.githubusercontent.com/11055362/38644224-aee33b1c-3d94-11e8-9f1f-cb9be65e3413.png)
![image](https://user-images.githubusercontent.com/11055362/38644230-b39bbfb2-3d94-11e8-8493-0b9c1da86f5d.png)

**Comment by rcasto** [comment]
Hey Eric, thanks for getting back on this!  Haven't had a chance to update all of our Bot.Builder packages yet, but will do and see if that resolves it.  Looks like it should as you point out above.

**Comment by EricDahlvang** [comment]
Closing due to no response.

**Comment by EricDahlvang** [comment]
Which version of the emulator are you using?

**Comment by rcasto** [comment]
![image](https://user-images.githubusercontent.com/869330/39439793-b255358e-4c5d-11e8-898a-1eec0dea0aa5.png)

**Comment by EricDahlvang** [comment]
Please provide the rest of the code you are using to send the adaptive card in a reply.  I'm unable to reproduce the issue here.  Also , how exactly are you connecting to the emulator?

**Comment by EricDahlvang** [comment]
Yes, you are correct.  This behavior (strings submitted as is and objects are sent as raw JSON).  This behavior is described in the webchat repository here: https://github.com/Microsoft/BotFramework-WebChat/blob/master/AdaptiveCards.md#actions



Action.Submit | Supported. The data property of the action may be a string or it may be an object. A string is passed back to your bot as a Bot Builder SDK imBack activity, and an object is passed as a postBackactivity. Activities with imBack appear in the chat stream as a user-entered reply. The postBackactivities are not displayed.
-- | --

**Comment by rcasto** [comment]
Ok, thanks for that, but I guess I'm just a little confused.  Is postBack an activity type I should be receiving sent to the botframework messages api on our service via MBF?  I seem to only be receiving a message activity type when the Action.Submit button is clicked with a Value property that when serialized is `"{}"` not the actual object I had.  Or does this object need to be constructed in a special way within the Action.Submit data property?

**Comment by EricDahlvang** [comment]
postBack is not an activity type https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Microsoft.Bot.Connector.Shared/ConnectorAPI/Models/ActivityTypes.cs  but an action type https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Microsoft.Bot.Connector.Shared/ConnectorAPI/Models/ActionTypes.cs
