### ISSUE TITLE
[Node.js SDK, Skype] I want my bot to send message every-time a user get connected 

### ISSUE THREAD

**Issue by SasankaSengupta** [Microsoft/BotBuilder#4453]
## Bot Info
* SDK Platform:  Node.js 

* Active Channels: Skype
* Deployment Environment:  Azure Bot Service

## Issue Description
I want my bot to send message every-time a user get connected to in skype

## Code Example
I'm doing this way:

**bot.on('conversationUpdate', function (message) {
    if (message.membersAdded) {
        message.membersAdded.forEach(function (identity) {
            if (identity.id === message.address.bot.id) {
                bot.beginDialog(message.address, 'showPromo');
            }
            
        });
    }
     
});**
But bot is replying for the first time only.

## Expected Behavior
Bot will reply everytime user connected to skype.

## Actual Results
Bot replying first time only.

**Comment by fanidamj** [comment]
The code you are using is only used for the bot to handle events such as user joining a conversation, adding a bot to contacts list for the first time or when a bot is being removed from the conversation as mentioned [here](https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-handle-conversation-events).
Since the conversationUpdate and the contactRelationUpdate event are not supported by all channels, a universal way to greet a **user who joins a conversation** is to add a [first-run dialog](https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-handle-conversation-events#add-a-first-run-dialog) which you are implementing. It should response everytime there is a new conversation with the user. You can try session.conversationData instead of session.UserData an see if it works.

**Comment by SasankaSengupta** [comment]
Thanks for the advice @fanidamj .
Ok, what I am doing is sending a link to users to join Skype. The first-run dialog or the conversationUpdate events will greet a user the first time user added bot contact to Skype. What I'm asking is whenever a user hits the link, and open-up skype, it will send a message to the User. Please let me know how to do this.

**Comment by fanidamj** [comment]
@SasankaSengupta Have you tried using session.userData?

**Comment by SasankaSengupta** [comment]
Hi @fanidamj ,  session.userData only works with **'first-run dialog'** , that is only firing when someone adding my skype bot in their group chat. I want my skype bot to send message as soon as the user clicking the link and open up skype bot. And that functionality only working when **conversationUpdate** event is fired. Is there anyway to do it?

**Comment by fanidamj** [comment]
Unfortunately we don't have that feature right now. Thanks for your patience.

**Comment by alexandrenunes-cs** [comment]
@fanidamj Is it possible to send a message to a specific Skype Account using nodejs?

Example: I'm trying to send a message to a specific Skype account (Person 2) if my bot does not have the answer. Then, catch again the answer to resend to the first user (Person 1).
Thanks

**Comment by stevkan** [comment]
@alexandrenunes-cs, yes it is possible to send a message to a specific Skype account. The short answer is the user of the Skype account will need to have had a previous converesation with the bot. The conversationId and the user Id will need to be saved. Later, the bot can 'rejoin' this conversation for a message to be sent to that account.

You can find the full discussion [here](https://github.com/Microsoft/BotBuilder/issues/1670) for reference.

**Comment by alexandrenunes-cs** [comment]
@stevkan I'm writing in nodejs, and I am new as a developer. Do you have an example on NodeJs or where I can understand what is done?

**Comment by stevkan** [comment]
@alexandrenunes-cs, As you may have noticed, the BotBuilder repos have been reorganized following the v4 release. I'm not sure which version of the SDK you are using, but please create a new issue on either the [v3 repo](https://github.com/Microsoft/BotBuilder-v3/issues) or the [v4 repo](https://github.com/Microsoft/botbuilder-js/issues). Once done, leave a message for me here with a link and I'll assist you there.

**Comment by alexandrenunes-cs** [comment]
Hi @stevkan ,
I did what you asked me. Here are the links to the issues.
https://github.com/Microsoft/botbuilder-js/issues/555
https://github.com/Microsoft/BotBuilder-V3/issues/32

any help will be grateful.
