### ISSUE TITLE
[.Net SDK, Azure Bot Service] Changes made in Bot Code not Replicating in azure web test bot.

### ISSUE THREAD

**Issue by yalalasai** [Microsoft/BotBuilder#4454]
## Bot Info
* SDK Platform:  .NET
* Active Channels:  MS Teams
* Deployment Environment:  Azure Bot Service, Azure App Service 

## Issue Description
 As given in the guidelines in readme.md I did made changes in my code and did  run in console but it is giving out an error.

## Code Example
 call npm install kudusync -g --silent 

## Expected Behavior
 To deploy the bot with newly created Intents.

## Actual Results

![after changes in code](https://user-images.githubusercontent.com/22302859/38611406-387e6412-3da1-11e8-9b8e-ca98dc704671.PNG)
![console](https://user-images.githubusercontent.com/22302859/38611408-38bc4200-3da1-11e8-81bb-f3d515fe5029.PNG)

**Comment by EricDahlvang** [comment]
I see you are getting a "Type or namespace definition, or end of file expected" exception.  Please share the BasicLuisDialog.cs

**Comment by EricDahlvang** [comment]
Closing due to no response.
