### ISSUE TITLE
Error when adding Skype Channel - Error synchronising your Bot to Skype

### ISSUE THREAD

**Issue by MarkHirst** [Microsoft/BotBuilder#4455]
## Bot Info
* SDK Platform: .NET
* SDK Version: SDK version
* Active Channels: Skype
* Deployment Environment: Azure VM

## Issue Description
Similar to issue 4402, I'm having no luck contacting my bot through Skype. On initial registration of the bot and adding the Skype channel (as a 1:1 calling bot), I see 'There was a problem synchronizing your bot to Skype' appearing in errors shown against the channel.

There are no further errors shown after that. however when clicking the Skype channel to add the bot to my Skype contacts, the bot is not functional, and the call button is not enabled in the Skype client.

The test page in Azure portal does work, so the messages controller is functioning correctly.

I've registered the bot three times (removing previous registration first) and all three attempts have had the same problem. On previous attempts, I've also seen ACL check fail errors, although on the current registration haven't seen those yet.

## Code Example
I'm using the EmergencyServices bot from the samples. It's registration handle is FlexNeonDevIVR2.

## Expected Behavior
I've also deployed this sample https://azure.microsoft.com/en-gb/solutions/architecture/interactive-voice-response-bot/ using its deployment tools into the same subscription and that works fine with Skype, so am hoping for the same outcome.

**Comment by JasonSowers** [comment]
Hi @MarkHirst we are currently investigating this issue with the skype team.  We are tracking this issue here #4356  please post and track the status there.  Some people have found luck recreating their bots, if this is an option for you please try that.  If it is not  an option we are looking for the cause and will update the other issue as we have more information.
