### ISSUE TITLE
[.Net SDK, FB Messenger] Typing activity not disappearing before message arrives IOS

### ISSUE THREAD

**Issue by schafferer** [Microsoft/BotBuilder#4456]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.14.1.1
* Active Channels: Facebook
* Deployment Environment: App Service

## Issue Description
When sending a TypingActivity, the "typing" bubble does not dissapear when the actual message arrives. Its delayed by a few seconds, creating a "bouncing"-effect. This only seems to be a problem in messenger on IOS. 

## Code Example
    // Send "typing" information
    var typeReply = context.MakeMessage();
    typeReply.Type = ActivityTypes.Typing;
    typeReply.Text = null;
    await context.PostAsync(typeReply);

    // some other code

    // send actual message
    await context.PostAsync(actualMessage);

## Expected Behavior
Typing bubble disappearing the moment the actual message is delivered.

## Actual Results
Typing indicator not disappearing when the message arrives, it's delayed about a second. Works fine on web and android.

**Comment by JasonSowers** [comment]
I will look into this to see if there is something on our end causing this, but it sounds like an issue with the facebook IOS app and I highly encourage you to reach out to Facebook support as well.  On our side, the behavior of the typing indicator should not change when using different platforms.  As I said I will look into this to confirm.

**Comment by schafferer** [comment]
Ok, a little more research led to the conclusion this is a Messenger on IOS-bug, not BotBuilder. The problem persists even if there is a human typing the message. I have filed a bug report at Facebook.

**Comment by JasonSowers** [comment]
Thanks for the update, good luck!
