### ISSUE TITLE
PromptDialog.Confirm punctuation

### ISSUE THREAD

**Issue by aklein53** [Microsoft/BotBuilder#446]
PromptDialog.Confirm does not accept "Yes." or "No." as an answer. It would be nice if it could strip punctuation and accept either of those as an answer.

**Comment by chrimc62** [comment]
Pass in PromptOptions.Options with whatever list you think is appropriate.

**Comment by aklein53** [comment]
Apologies if I'm mistaken, but PromptDialog.Confirm does not take an options list.

There is an internal method that does, but the accessible method does not. https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Dialogs/PromptDialog.cs#L264

Perhaps the internal one should be public?

**Comment by chrimc62** [comment]
You are right that should be public not internal.  Our next release will fix that.  In the meantime you can use PromptDialogs.Choice which does take an options list to build your own.
