### ISSUE TITLE
[.Net SDK, Azure Bot Service] Error message 'ajaxExtended call failed' on creating bot on Azure portal

### ISSUE THREAD

**Issue by julia-chursova** [Microsoft/BotBuilder#4464]
## Bot Info
* SDK Platform: .NET
* SDK Version: 
* Active Channels: 
* Deployment Environment: Azure Bot Service

## Issue Description
When I'm trying to create new Web Bot with Proactive C# template I keep getting 'ajaxExtended call failed' error

## Reproduction Steps
1. Click 'create new resource' on Azure portal
2. Choose Web Bot
3. Fill all required fields with template as 'Proactive C#'
4. Click 'Create'

## Expected Behavior
Bot has been created

## Actual Results
Bot has not been created, error 'ajaxExtended call failed' has appered

**Comment by julia-chursova** [comment]
![untitled](https://user-images.githubusercontent.com/5188548/38695182-962bd2a6-3e9c-11e8-9cdf-42b964e3f96c.png)

**Comment by fanidamj** [comment]
We are looking into this issue and will get back to you soon.

**Comment by fanidamj** [comment]
Closing this issue as there is no response from the user yet. Please reopen a new issue if the issue still persists.
