### ISSUE TITLE
[.Net SDK, LUIS] Multilingual Chatbot.

### ISSUE THREAD

**Issue by gopal300** [Microsoft/BotBuilder#4467]
I have created the Multilingual chatbot using LUIS (where i trained it in Spanish) and Microsoft Translate API. For most of the part it´s working fine but the problem is everytime i insert E-mail address it converts it takes English as the default user language while i would like to proceed in language other than English. Another thing is there isn´t much resources which explains how to use translate API while dealing with Formflow (Prompt class in particular). 

Thanks in advance for your help!

![image](https://user-images.githubusercontent.com/29302147/38732250-d4c9f336-3f1d-11e8-935f-ff66b8812819.png)

**Comment by JasonSowers** [comment]
Are you using the .NET or Node SDK?

**Comment by gopal300** [comment]
I am using .NET.

**Comment by gopal300** [comment]
Any solution or the suggestion for the issue ?

**Comment by fanidamj** [comment]
Can you please share the code related to it so that we can reproduce the issue.

**Comment by gopal300** [comment]
For FormFlow:
`namespace LuisBot
{
    public enum TypeRoom
    {
        [Describe("Individual")]
        Individual = 1,
        [Describe("Doble")]
        Doble,
        [Describe("Matrimonial")]
        Matrimonial,
        [Describe("Triple")]
        Triple,
        [Describe("Suite")]
        Suite
    }

    [Serializable]

    public class BookingForm1
    {

        [Prompt("¿Para qué fecha quieres reservar la habitación?")]
        public DateTime Fecha { get; set; }
    
        /*
        [Prompt("¿A qué hora prefieres registrarte? Utiliza el formato HH:mm. \n\n Por ejemplo las 10.30 p.m. serían las 22:30")]
        public DateTime Hora { get; set; }*/

        [Prompt("¿Por cuántas noches quieres reservar la habitación?")]
        public int Noches { get; set; }

        [Prompt("¿Para cuántas personas quieres la habitación?")]
        public int No_Huespedes { get; set; }

        [Prompt("¿Cuántos niños?")]
        public int Niños { get; set; }

        [Describe("Seleccione la opción deseada: ")]
        [Prompt("Que tipo de habitación quiere? {||}")]
        public TypeRoom TipoHabitacion { get; set; }


       

        public static IForm<BookingForm1> BuildForm1()
        {
            
            return new FormBuilder<BookingForm1>()
                
                .Field(nameof(Fecha), validate: ValidateDate)
                //.Field(nameof(Hora), validate: ValidateTime)
                .Field(nameof(Noches), validate: ValidateNights)
                .Field(nameof(No_Huespedes), validate: ValidateNumPeople)
                .Field(nameof(Niños), validate: ValidateKids)
                .Field(nameof(TipoHabitacion))
 
                .Build();
        }`

**Comment by gopal300** [comment]
I tried to to use Multilingual App toolkit and generated xlf file for 2 languages English and French. Now the problem is when the bot emulator environment is set to Spanish (the formflow is in spanish) it works fine and proceed with the form build but when i change the enviroment to English the prompt dialog doesn´t enter the formflow. 
![git doubt english-1](https://user-images.githubusercontent.com/29302147/39574895-fda068c4-4ed8-11e8-8216-e6d6b8091a2b.PNG)
![git doubt english-2](https://user-images.githubusercontent.com/29302147/39574897-fdbfd1f0-4ed8-11e8-8542-405f8cede256.PNG)
![git doubt spanish](https://user-images.githubusercontent.com/29302147/39574898-fdd9829e-4ed8-11e8-936d-67fe8b9a1fdc.PNG)

**Comment by gopal300** [comment]
Any updates ??

**Comment by nyxsys** [comment]
Apologies for the wait, unfortunately we need a bit more context to this before its solvable. Could you provide a minimal version of your bot so we can build it and try it out? In the meanwhile, [here ](https://github.com/EricDahlvang/ChooseLanguageBot)is a sample bot that utilizes multiple languages dynamically. It is not using form flow, but it might provide a starting point.

**Comment by nyxsys** [comment]
Closing for now, but reopen if you want to follow up on this problem
