### ISSUE TITLE
Masking sensitive user data

### ISSUE THREAD

**Issue by waleedabuyahia** [Microsoft/BotBuilder#4468]
* SDK Platform: .Net
* SDK Version: Latest
* Active Channels: Facebook, Webchat
* Deployment Environment: Azure

I have a chat bot where the user will input some sensitive data, I would like to mask the user input, like account number, bank credit card number, pin, etc...

**Comment by EricDahlvang** [comment]
Hi @waleedabuyahia 

The bot builder sdk does not contain client side rendered controls.  In order to have a masking control client side, you would need to work with the client library itself.
