### ISSUE TITLE
Unable to create Slack channel for example bot

### ISSUE THREAD

**Issue by StephenKWalsh** [Microsoft/BotBuilder#4469]
## Bot Info
* SDK Platform: .Net
* SDK Version: latest
* Active Channels: Web Chat
* Deployment Environment: Azure Bot Service

## Issue Description
I created the example bot, and tested it in Web Chat. I am trying to connect it to Slack, so I have followed the Slack bot instructions, then have entered the Slack credentials on the Configure Slack channel, when I click 'Save' the credentials 1) opens a blank browser window and 2) sits there Waiting. At a loss how to resolve this.

## Code Example
The default example bot

## Reproduction Steps
1. Create the example bot
2. Create the bot in Slack
3. Connect to the Slack channel

## Expected Behavior
I would expect to see a Slack Authentication screen

## Actual Results
1) opens a blank browser window and 
2) sits there Waiting.

**Comment by stevkan** [comment]
@StephenKWalsh Can you tell me what browser you are using? I came across this same issue yesterday while in Edge. I switched to Chrome for this one task and it worked with no issues.

**Comment by StephenKWalsh** [comment]
@stevkan Yes, I was working in Edge. I'll try it with Chrome tomorrow - definitely not the answer I was expecting!

**Comment by StephenKWalsh** [comment]
@stevkan No problems doing exactly the same thing in Chrome. Many thanks for pointing me in the right direction on that one. Now remind me how I get those 2 wasted days back.

**Comment by stevkan** [comment]
@StephenKWalsh Glad it worked out for you.
