### ISSUE TITLE
Inline mode on telegram always responding with error, even when working right

### ISSUE THREAD

**Issue by fercom** [Microsoft/BotBuilder#447]
While using my bot on inline mode it always responds with:

> @Fer Galván Sorry, MemeBot is having a problem responding right now.

Even when it indeed works. What could be happening? 

An example of a requisition in inline mode would be like: "spongebob meme, hello, world, please"

Thanks for your help

My bot, for testing:
[https://telegram.me/The_MemeBot](url)

**Comment by eanders-MS** [comment]
Are you using ngrok by chance? Looking at the Telegram logs, I see this error "Operation returned an invalid status code 'BadGateway'". This looks suspiciously like the error returned by ngrok when it can't forward a message to an app. I wonder if you have an ngrok address set as your bot endpoint, but your bot isn't running locally.

**Comment by fercom** [comment]
Just for testing, right now is on azure

**Comment by eanders-MS** [comment]
Does it work on other channels? Is it only having issues on Telegram?

**Comment by fercom** [comment]
It is only having issues in the inline mode in telegram, it works fine in facebook, skype and web, even in telegram when not called in inline mode but in direct chat

**Comment by fercom** [comment]
I just solved it, it seems that the problem is that while the user is contructing the inline request the bot can throw a "bad request exception", just returning 'null' for that requests solves the problem
