### ISSUE TITLE
[LUIS] Unable to log into Luis Dashboard

### ISSUE THREAD

**Issue by teamplumaa** [Microsoft/BotBuilder#4473]
I am unable to log into the Luis.ai dashboard. I am getting an error at this link

https://api.luis.ai/webapi/v2.0/auth/signin?redirect=https://api.luis.ai/Identity/SignIn

**Comment by tsuwandy** [comment]
Is this issue still happening for you?

**Comment by teamplumaa** [comment]
yes it is. 

The error im getting is as follows:



<configuration>
    <system.web>
        <customErrors mode="Off"/>
    </system.web>
</configuration>

**Comment by teamplumaa** [comment]
<configuration>
    <system.web>
        <customErrors mode="Off"/>
    </system.web>
</configuration>

**Comment by fanidamj** [comment]
Can you please share .HAR file from the chrome developer console and the Email Id with which you are trying to login to **luisuservoice@microsoft.com** so that we can investigate further.

**Comment by cahann** [comment]
+Congyong can you please look into this issue

**Comment by fanidamj** [comment]
@teamplumaa Can you please confirm if the issue still persists?

**Comment by fanidamj** [comment]
Closing the issue assuming it as resolved. Please reopen a new issue if there is any.
