### ISSUE TITLE
Cortana Mike not enabled after Clicking on Adaptive Card Action Button 

### ISSUE THREAD

**Issue by SwetalinaGitHub** [Microsoft/BotBuilder#4475]
## Bot Info
* SDK Platform: .NET
* SDK Version: Adaptive Cards 1.0.0.0
* Active Channels: Cortana
* Deployment Environment: Azure Bot Service, Azure App Service, Cortana

## Issue Description
Mike is appearing disabled in Cortana for Android if we click on Adaptive card submit action button. It appears enabled only if we speak the button text to move to the next step.

## Code Example
```
 public Attachment CreateAdapativeActionButton1()
 {
            AdaptiveCard card = new AdaptiveCard();
                        
            card.Actions.Add(new AdaptiveSubmitAction()
            {
                Type = "Action.Submit",
                Data = "Button A",
                Title = "Button A"                
            });
            
            Attachment attachment = new Attachment()
            {
                ContentType = AdaptiveCard.ContentType,
                Content = card
            };
            return attachment;            
 }

Activity reply = activity.CreateReply(message);
reply.Speak = message;
reply.Text = message;
reply.InputHint = InputHints.ExpectingInput;

MenuActions m = new MenuActions();
Attachment attachment = m.CreateAdapativeActionButton1();

```
## Reproduction Steps
1. 
2.
3.

## Expected Behavior
Cortana mike should be enabled if we click the action button.

## Actual Results
When we click on an action button, it moves to the next step but the mike appears disabled. Even if we speak, it will not listen, hence not accept next input to process further request.

**Comment by EricDahlvang** [comment]
Thank you for reporting this.  It appears to be a bug in Cortana on Android.  I will notify the Cortana team.

**Comment by Kannan2018** [comment]
hi, speak not working for adaptive cards in text block content and body title .Below are the my code. please give me suggestion

     AdaptiveCard card = new AdaptiveCard();
                card.BackgroundImage = "";
                card.Version = "1.0";
                card.Type = "AdaptiveCard";
                card.Speak = "this sample";


    new TextBlock()
                                       {
                                           Text = "Applications",
                                           Speak="this on sample"
                                           Color = TextColor.Light,
                                           Size = TextSize.ExtraLarge,
                                           HorizontalAlignment = HorizontalAlignment.Center
                                           }

**Comment by EricDahlvang** [comment]
@Kannan2018 The .Speak property on TextBlock has been deprecated.  Also, please upgrade your AdaptiveCard library to the latest: https://www.nuget.org/packages/AdaptiveCards/

**Comment by EricDahlvang** [comment]
This bug has been fixed.
