### ISSUE TITLE
[.NET SDK] Code not working in deployment mode

### ISSUE THREAD

**Issue by SATACHAKRA** [Microsoft/BotBuilder#4476]
## Bot Info
* SDK Platform:  .NET  
* Active Channels: Direct Line
* Deployment Environment: < Azure App Service and local development with Emulator >

## Issue Description:
Our bot is continously deployed via a bitbucket repo..it was working great until last friday..then we had to change some luis keys. after updating and syncing the latest code our bot is just not replying anything. The code works perfectly fine in the emulator...but once it is up in continous deployment it just stops responding (i.e: it shows the welcome message but doesn't respond to anything after that).

it is strange as the same code is working fine locally on emulator. I am totally confused. i have checked the LUIS endpoint, it is active..and have given the correct license keys in the code.
Has anyone else faced a similar problem??plz help asap.

**Comment by stevengum97** [comment]
Can you copy-paste the section of the code where you use the license keys in the code? Are you plain-text adding the keys to your bot or are you using environmental variables? If the latter, did you update the environment variables in Azure App Service?

**Comment by SATACHAKRA** [comment]
`<?xml version="1.0" encoding="utf-8"?>

<configuration>
  <appSettings>
    
    <add key="MicrosoftAppId" value="XXXXXXXXXXXXXXXXXXXXXXXXXX" />
    <add key="MicrosoftAppPassword" value="XXXXXXXXXXXXXXXXXXXX" />
    <add key="MicrosoftSpeechApiKey" value="XXXXXXXXXXXXXXXXXXXXXXX" />
    <add key="LuisAppId" value="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" />
    <add key="LuisAPIKey" value="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" />
    <add key="LuisAPIHostName" value="westus.api.cognitive.microsoft.com" />
    
  </appSettings>
 
  <system.web>
    <customErrors mode="Off" /> 
    <compilation debug="true" targetFramework="4.6" />
    <httpRuntime targetFramework="4.6" />
  </system.web>
  <system.webServer>
    <defaultDocument>
      <files>
        <clear />
        <add value="default.htm" />
      </files>
    </defaultDocument>
    
  <handlers>
      <remove name="ExtensionlessUrlHandler-Integrated-4.0" />
      <remove name="OPTIONSVerbHandler" />
      <remove name="TRACEVerbHandler" />
      <add name="ExtensionlessUrlHandler-Integrated-4.0" path="*." verb="*" type="System.Web.Handlers.TransferRequestHandler" preCondition="integratedMode,runtimeVersionv4.0" />
    </handlers></system.webServer>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Web.Helpers" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="1.0.0.0-3.0.0.0" newVersion="3.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Web.Mvc" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="1.0.0.0-5.2.3.0" newVersion="5.2.3.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Web.WebPages" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="1.0.0.0-3.0.0.0" newVersion="3.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-11.0.0.0" newVersion="11.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Net.Http.Primitives" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.2.29.0" newVersion="4.2.29.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Net.Http.Formatting" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.2.4.0" newVersion="5.2.4.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.IdentityModel.Tokens.Jwt" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.2.1.0" newVersion="5.2.1.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Autofac" publicKeyToken="17863af14b0044da" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.7.0.0" newVersion="4.7.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Web.Http" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.2.4.0" newVersion="5.2.4.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.IdentityModel.Tokens" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.2.1.0" newVersion="5.2.1.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.IdentityModel.Protocols" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.2.1.0" newVersion="5.2.1.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.IdentityModel.Protocols.OpenIdConnect" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.2.1.0" newVersion="5.2.1.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
`

This is my web config file. And as I said before the code is running fine locally i.e via the emulator. Once I push it into continous deployment, it just stops responding.

**Comment by SATACHAKRA** [comment]
As of now all our bots that are configured for continous deployment via BitBucket are not working...none of them. I completely confused as to what went wrong..someone plz help

**Comment by stevengum97** [comment]
Are these migration bots or are these new bots?

**Comment by SATACHAKRA** [comment]
I don't know what that means.
All the bots have been already migrated to the azure portal long before 31st march. And they were working fine.

**Comment by fanidamj** [comment]
Can you please let us know if the issue still persists?

**Comment by EricDahlvang** [comment]
Closing, no response.
