### ISSUE TITLE
[Feature Request] Can't get topicName when the bot is added to the group

### ISSUE THREAD

**Issue by yaninah** [Microsoft/BotBuilder#4479]
## Bot Info
* SDK Platform:  REST
* SDK Version: 
* Active Channels: Skype
* Deployment Environment: local development + Bot Channels Registration 
## Issue Description
When the bot is added to the group the topicName doesn't come in the request. But when the topicName changes while the bot is already in the group there's a topicName. Is there any way to get topic name when the bot is just added to the group?

## Reproduction Steps
1. Add bot to the group
2. Change name of the group while bot is in

## Expected Behavior
Json that comes to the bot whent it added to the group
{
  &nbsp;&nbsp;&nbsp;&nbsp; "recipient":{
     &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;"name":"BotName",
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"id":"1111111"
  &nbsp;&nbsp;&nbsp;&nbsp; },
  &nbsp;&nbsp;&nbsp;&nbsp; "timestamp":"2018-04-16T08:13:23.27Z",
&nbsp;&nbsp;&nbsp;&nbsp;   "membersAdded":[
  &nbsp;&nbsp;&nbsp;&nbsp;    {
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;       "id":"1111111"
  &nbsp;&nbsp;&nbsp;&nbsp;    }
 &nbsp;&nbsp;&nbsp;&nbsp;  ],
 &nbsp;&nbsp;&nbsp;&nbsp;  "type":"conversationUpdate",
   &nbsp;&nbsp;&nbsp;&nbsp;"serviceUrl":"https://smba.trafficmanager.net/apis/",
&nbsp;&nbsp;&nbsp;&nbsp;   "channelId":"skype",
  &nbsp;&nbsp;&nbsp;&nbsp; "from":{
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;     "id":"2222222"
  &nbsp;&nbsp;&nbsp;&nbsp; },
  &nbsp;&nbsp;&nbsp;&nbsp; "id":"3333",
&nbsp;&nbsp;&nbsp;&nbsp;   "conversation":{
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;     "isGroup":true,
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;     "id":"1243567",
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;     "topicName": "TestGroup"
&nbsp;&nbsp;&nbsp;&nbsp;   }
}

or (as it come when topic name is changed while the bot is in)

{
   ...
  &nbsp;&nbsp;&nbsp;&nbsp; "topicName": "TestGroup",
 &nbsp;&nbsp;&nbsp;&nbsp;  "conversation":{
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    "isGroup":true,
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;     "id":"1243567"
 &nbsp;&nbsp;&nbsp;&nbsp;  }
}

## Actual Results

{
  ...
 &nbsp;&nbsp;&nbsp;&nbsp;  "conversation":{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;      "isGroup":true,
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    "id":"1243567"
  &nbsp;&nbsp;&nbsp;&nbsp; }
}

**Comment by JasonSowers** [comment]
I will have to double check, but I do not think that data is provided until it is set with the bot in the conversation.

**Comment by yaninah** [comment]
@JasonSowers , but why not? It's clear that the name of the topic isn't under some privacy protection since it available in the request body when someone in the group changes it and bot receives the details of conversation update. So why it has to be unavailable when the bot just joined the group conversation?

**Comment by JasonSowers** [comment]
My best guess is that it is a deficiency on Skype's end, I haven't had the chance to look into it to give you a more concrete answer.  I will try my best to take a look today.

**Comment by graphnode** [comment]
I asked this back on 2016 in #969. There is also #1175.

Would love to get a update regarding this.

**Comment by nyxsys** [comment]
We'll look into adding this field to the skype API in the future.

**Comment by JasonSowers** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
