### ISSUE TITLE
Bot exits for not apparent reason

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/BotBuilder#448]
I'm following your tutorial and at [this step](http://docs.botframework.com/builder/node/guides/core-concepts/#handling-commands), I ended up with the following code:

```es6
const builder = require('botbuilder');
const bot = new builder.TextBot();

bot.add('/', new builder.CommandDialog()
  .matches('^set name', builder.DialogAction.beginDialog('/profile'))
  .matches('^quit', builder.DialogAction.endDialog())
  .onDefault([
    (s, args, next) => {
      if (!s.userData.name) {
        s.beginDialog('/profile');
      } else {
        next();
      }
    },
    s => s.send(`Hello ${ s.userData.name }!`)
  ])
);

bot.add('/profile', [
  s => {
    if (s.userData.name) {
      builder.Prompts.text(s, 'What would you like to change it to?');
    } else {
      builder.Prompts.text(s, 'Hi! What\'s your name?');
    }
  },
  (s, res) => {
    s.userData.name = res.response;
    s.endDialog();
  }
]);

bot.listenStdin();
```

The bot always exists once I reset the name, though. I can't figure out why that is:

```
$ node index.js
hey
Hi! What's your name?
joao
Hello joao!
hi back
Hello joao!
set name
What would you like to change it to?
oh no
// process ends with exit code 0
```

What is wrong with my code?

**Comment by joaomoreno** [comment]
@Stevenic am I doing something obviously wrong here?

**Comment by brendanarnold** [comment]
I get the exact same

Node version 6.2.1
Botbuilder 1.0.1

**Comment by Stevenic** [comment]
Several people are reporting this. Let me give it a try... I had tested it to work correctly but quite possible I broke something in 1.0.1

**Comment by Stevenic** [comment]
Ok... I see what's happening, A change I made to the way waterfalls work in 1.0 is tripping this up. When you use the `builder.DialogAction.beginDialog()` function the current dialog ends up closing once that call completes and since this is the root dialog your root dialog closes which causes the app to close. I've update the sample to not do this and will update the documentation.

```
var builder = require('../../');

var helloBot = new builder.TextBot();
helloBot.add('/', new builder.CommandDialog()
    .matches('^set name', [
        function (session) {
            session.beginDialog('/profile');
        },
        function (session, results) {
            session.send("Name changed to %s", session.userData.name);
        }
    ])
    .matches('^quit', builder.DialogAction.endDialog())
    .onDefault([
        function (session, args, next) {
            if (!session.userData.name) {
                session.beginDialog('/profile');
            } else {
                next();
            }
        },
        function (session, results) {
            session.send('Hello %s!', session.userData.name);
        }
    ]));
helloBot.add('/profile',  [
    function (session) {
        if (session.userData.name) {
            builder.Prompts.text(session, 'What would you like to change it to?');
        } else {
            builder.Prompts.text(session, 'Hi! What is your name?');
        }
    },
    function (session, results) {
        session.userData.name = results.response;
        session.endDialog();
    }
]);

helloBot.listenStdin();
```

**Comment by thewhitetulip** [comment]
@Stevenic Is this why we get the "ERROR: too many calls to endDialog"?

**Comment by NTruchaud** [comment]
I don't know if I did somtething wrong, but it's always sending me on the Default answer ...
Any idea ?
`require('dotenv').config();
var builder = require('botbuilder');
var jade = require('jade');
var restify = require('restify');
var request = require('request');

var server = restify.createServer();

var iframeUrl = 'https://webchat.botframework.com/embed/' + process.env.APP_ID + '?s=' +
    process.env.APP_IFRAME_SECRET;

var helloBot = new builder.BotConnectorBot();
console.log("Change test");
helloBot.add('/', new builder.CommandDialog()
    .matches('^set name', [
        function (session) {
            session.beginDialog('/profile');
        },
        function (session, results) {
            session.send("Name changed to %s", session.userData.name);
        }
    ])
    .matches('^quit', builder.DialogAction.endDialog())
    .matches('^what is the best IDE', [
        function(session) {
            console.log("The Best IDE ?");
            session.beginDialog('/sourcelair');
        }
    ])
    .matches('^help', [
        function(session) {
            console.log("help");
            session.beginDialog('/help');
        }
    ])
    .onDefault([
        function (session, args, next) {
            if (!session.userData.name) {
                session.beginDialog('/profile');
            } else {
                session.send('Hm, I did not understand you %s :(', session.userData.name);
                next();
            }
        },
        function (session, results) {
            session.send('Hello %s!', session.userData.name);
        }
    ]));

helloBot.add('/profile',  [
    function(session) {
        if (session.userData.name) {
            builder.Prompts.text(session, 'What would you like to change it to?');
        } else {
            builder.Prompts.text(session, 'Hi! What is your name?');
        }
    },
    function(session, results) {
        session.userData.name = results.response;
        session.send('Hello %s, it\'s great to meet you. I\'m bot.', session.userData.name);
        session.endDialog();
    }
]);
helloBot.add('/sourcelair',  [
    function(session) {
        session.send('It\'s SourceLair of course <3');
        session.endDialog();
    }
]);
helloBot.add('/help', [
    function(session) {
        session.send('You can always ask me some questions, for example what is my favorite IDE');
        session.endDialog();
    }
]);

server.get('/', function indexHTML(req, res, next) {
    res.setHeader('Content-Type', 'text/html');
    res.writeHead(200);
    res.end(
        jade.renderFile('index.jade', {iframeUrl: iframeUrl}));
    next();
});

server.use(helloBot.verifyBotFramework({appId: process.env.APP_ID, appSecret: process.env.APP_SECRET}));
server.post('/v1/messages', helloBot.listen());

server.listen(process.env.PORT || 3005, function () {
    console.log('%s listening to %s', server.name, server.url);
});
`

**Comment by Stevenic** [comment]
@NTruchaud sorry for the delay. still having problems?

**Comment by v-thgratMSGit** [comment]
Closing this issue. @NTruchaud @joaomoreno - please open a new issue if you're still experiencing. Thanks!

**Comment by Stevenic** [comment]
Yes... update to v3.x and let us know if you're having issues.
