### ISSUE TITLE
[Skype] bot is in review but in my bot it's necessary to make LOGIN

### ISSUE THREAD

**Issue by ShadeyCN** [Microsoft/BotBuilder#4480]
We've developed a bot that is connected to an API, and that in turn requires a login, which we've called Hand Shake.
The bot has already been several days in review (5 days), I've corrected all the observations that Skype have given me and yet I still have no answer.
Shoul I wait much longer? Or do you think it's due to the Hand Shake?

AppId= 590a8009-4b90-4947-bcd1-a9b27ab3197a

**Comment by stevkan** [comment]
Hi @ShadeyCN,

I'm reaching out to the Skype team and will post a response when I know more.

**Comment by ShadeyCN** [comment]
Hi @stevkan  
Thanks for answering.
We've received this from Skype, our bot has been rejected! However, the reason they give us is the following:
![img_17042018_142220_0](https://user-images.githubusercontent.com/38435039/38892053-c93c94fc-424b-11e8-94b8-02879664a653.png)

On our side is working correctly, you can verify that the bot does respond with these accesses:
LastName : TestSkype
Token: 9d82c5cc-1658-4696-8332-b69edefbe35c

**Comment by stevkan** [comment]
Hi @ShadeyCN,

What kind of response should be expected upon input? As you can see in the see below image, the bot isn't responding to input, at all. 

![unresponsive](https://user-images.githubusercontent.com/18403946/38893829-5a09f206-4240-11e8-8bc3-02e0692733f8.jpg)

**Comment by ShadeyCN** [comment]
Hi @JasonSowers 

I see in your screenshot that you use Skype from Windows 10, I decided to try it on that and I saw that it does not work either, I use desktop Skype and skype for mobile and everything is fine there.

**What do you think that is the reason of the trouble?**

**This is the respond that should show**
![captura](https://user-images.githubusercontent.com/38435039/38896601-be961156-4258-11e8-8fe2-89f400580bd7.PNG)

**Comment by stevkan** [comment]
Hi @ShadeyCN,

Good news. I was able to confirm your bot works in other Skype clients (desktop, web, phone) and forwarded this information on to the Skype bot approver. He has requested that you resubmit your bot and he will have it approved by EOD tomorrow.

As for the UWP/Windows 10 Skype client, it appears to be a known bug.

Steve.

**Comment by ShadeyCN** [comment]
Thank you very much @stevkan 

It's very good news, I'm keeping an eye on anything that may happen, and I hope very soon our bot can be approved.

We already sent the bot to review again

Thanks :)

**Comment by stevkan** [comment]
@ShadeyCN, you're welcome. And, best of luck!!
