### ISSUE TITLE
[Azure Bot Service] Empty channels page

### ISSUE THREAD

**Issue by metgens** [Microsoft/BotBuilder#4481]
## Bot Info
* SDK Platform: .NET
* SDK Version: not important
* Active Channels: none because of error
* Deployment Environment: Azure Bot Service

## Issue Description
When I click on **Channels** button under **Bot Management** I got empty page, no buttons, no text.. nothing, just empty white page. So I cannot add new channels to my bot service. I tried on **Chrome, Edge** browsers. I have bot api deployed on my server and it works (tested in azure web chat)

## Reproduction Steps
1. Sign in to the Azure Portal (Polish UI version)
2. Select the bot that you want to configure.
3. In the Bot Service blade, click Channels under Bot Management.

## Expected Behavior
I expected to see a page like in docs: https://docs.microsoft.com/en-us/azure/bot-service/bot-service-manage-channels

## Actual Results
![chrome_2018-04-17_08-55-35](https://user-images.githubusercontent.com/18053595/38854120-c3b495f6-421f-11e8-9c9d-a674ced9793a.png)

**Comment by mgbennet** [comment]
A fix has been deployed for this issue.

**Comment by GuruPrasathD** [comment]
@JasonSowers Even I facing the same issue. I have my language settings as English though.
