### ISSUE TITLE
Best Practices to Deploy onprem SFB

### ISSUE THREAD

**Issue by varunreddycs** [Microsoft/BotBuilder#4482]
## Bot Info
* SDK Platform: .NET
* SDK Version: not important
* Active Channels: not important
* Deployment Environment: Azure Bot Service +may be need few suggestions here

## Issue Description
What are the best practices to deploy the the Bot on premise SFB.

**Comment by stevengum97** [comment]
I've reached out to the SfB Bots team for guidance and will get back to you with updates.

**Comment by stevengum97** [comment]
@varunreddycs, the SfB team indicated that what you're probably looking for can be found on this page: https://msdn.microsoft.com/en-us/skype/skype-for-business-bot-framework/docs/bot-hybrid-support

Hope this helps.
