### ISSUE TITLE
[Skype, API REST] Is there any way to get activities in conversations like in DirectLine?

### ISSUE THREAD

**Issue by emimontesdeoca** [Microsoft/BotBuilder#4485]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.14.1.1
* Active Channels: Skype, DirectLine, webchat
* Deployment Environment: local

## Issue Description

I am trying to get the information from the conversation just like I did with DirectLine.

But instead of directline I am using this endpoint: `https://skype.botframework.com`, and when I am doing the **GET** to `https://skype.botframework.com/v3/conversations/<id-conversation>/activities`, I get the following message:

```
{
    "message": "The requested resource does not support http method 'GET'."
}
```

**Is it possible to get the conversation information without using DirectLine? just using the API REST?** Maybe it's only a feature only in the DirectLine.

## Reproduction Steps
First get token

```
POST /common/oauth2/v2.0/token HTTP/1.1
Host: login.microsoftonline.com
Content-Type: application/x-www-form-urlencoded
Cache-Control: no-cache
Postman-Token: 5c42e368-c9ee-47e7-91dc-2ce03f0aaa43

grant_type=client_credentials&client_id=e32ac4c0-bd36-4507-bde2-08f56c555970&client_secret=juidsecret!&scope=https%3A%2F%2Fapi.botframework.com%2F.default
```

Create conversation between person and bot and bot sends message to person

```
POST /v3/conversations HTTP/1.1
Host: skype.botframework.com
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLasdasdzI1NiIsIng1dCI6IkZTaW11RnJGTm9DMHNKWEdtdjEzbk5aY2VEYyIsImtpZCI6IkZTaW11RnJGTm9DMHNKWEdtdjEzbk5aY2VEYyJ9.eyJhdWQiOiJodHRwczovL2FwaS5ib3RmcmFtZXdvcmsuY29tIiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvZDZkNDk0MjAtZjM5Yi00ZGY3LWExZGMtZDU5YTkzNTg3MWRiLyIsImasdasdRiIiwidXRpIjoiVlNoMktWbXBHMHFnRURFNjd0NDlBQSIsInZlciI6IjEuMCJ9.qa4GasdasdLlwVb4QEny1Q3IYOG8ez7K1TVWp_dORh6uH9cBKoeGQZ7iY6vL8Z7OozcdRIBQuwrsOS0pxyLsnu1m74LM18PYSvxu03n_aCGojkuWjqXyDZLlRsGrT3vcvVnboi3WtUzvMjntQ5aUjPz3YYoP9_SjIu3EQHR25Evo1yutG799-QQWEU98f3bKImCDBB-Vpz8mnnN1dBnPMSkR6AXk-wA
Cache-Control: no-cache
Postman-Token: 3416d9ce-d1dc-49aa-a154-21c3d8c61b9e

{
    "bot": {
        "id": "28:e32ac4c0-bd36-4507-bde2-08f56c555970",
        "name": "integration-test"
    },
    "isGroup": false,
    "members": [
		 {
	        "id": "29:1IdC8PfMkYasdasdasdasd3LzepgXtWC6H8L7fs",
	        "name": "Emiliano Montesdeoca"
	    }
    ]
}
```

This returns conversation ID:

```
{
    "id": "8:emontesdeoc"
}
```

Now try to get all the messages from the conversation

```
GET /v3/conversations/8:emontesdeoc/activities HTTP/1.1
Host: skype.botframework.com
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIngasdGTm9DMHNKWEdtdjEzbk5aY2VEYyIsImtpZCI6IkZTaW11RnJGTm9DMHNKWEdtdjEzbk5aY2VEYyJ9.eyJhdWQiOiJodHRwczovL2FwaS5ib3RmcmFtZXdvcmsuY29tIiwiaXNzIjoiasdadsdasdasdoiVlNoMktWbXBHMHFnRURFNjd0NDlBQSIsInZlciI6IjEuMCJ9.qa4GcTbKuXIxfukZQ3YDAzDLMGrQljxaLf2UhsSSrvZv2mtXkHtd9S5Ed480OwFl1z5SN_wojbxj6trE6tCCf7HIWjtD3ydIsE0nZz2mdr-rzOcXUowD9xcSR8FUSU0_aLlwVb4QEny1Q3IYOG8ez7K1TVWp_dORh6uH9cBKoeGQZ7iY6vL8Z7OozcdRIBQuwrsOS0pxyLsnu1m74LM18PYasdad8f3bKImCDBB-Vpz8mnnN1dBnPMSkR6AXk-wA
Cache-Control: no-cache
Postman-Token: 97eb0a1c-eacb-4f5b-8c16-70eb7d9d864a

```
And it returns an error:

```
{
    "message": "The requested resource does not support http method 'GET'."
}
```

## Expected Behavior
When doing the call to `GET /v3/conversations/8:emontesdeoc/activities` it should return a list of activities and a watermark, just like it does with DirectLine.

## Actual Results
I get the following:

```
{
    "message": "The requested resource does not support http method 'GET'."
}
```

**Comment by emimontesdeoca** [comment]
I've been reading documentation and might have found something useful, but still can't make it work, in [this documentation](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-state) it talks abous states, which seem to have the conversation information.

Making a **`GET`** to **`/v3/botstate/{channelId}/conversations/{conversationId}`** seems to return conversation information but I can't make it work with my current URI: `skype.botframework.com`.

In other posts I've seen that people try with this other url so I tried a **`GET `** to **`https://state.botframework.com/v3/botstate/skype/conversations/<conversation-id>`**, it returns 401 Unauthorized. 

Maybe I should get the bearer from another url?

**Comment by JasonSowers** [comment]
The documentation you are referencing deals with state data.  This is the `userData`, `conversationData`, and `privateConversationData` databags.  It is not the conversation history.  The reason you are able to do this with Directline is that conversations are cached for 24 hours.  If you want to the conversation history  you are going to need to store and retieve it somehow.  I'm a little confused how your bot is setup, you say you are using the .Net SDK but also using rest calls.  Can you explain this a bit?  In the .Net SDK   there is a class `IActivityLogger`  that you may want to use for this.  As far as I can see there is no Skype endpoint to get conversation history.

**Comment by JasonSowers** [comment]
1. How can I, using the API REST, get all the messages from a determied conversationid?
    There is no method in the REST API that will provide this.
2. Is there any way that I can send a message as an user instead of as a bot? I can create a in the DirectLine and send a message which the bot will answer.
    You may be able to hack something together.  I would be really surprised if you could though because of the security implications of impersonating a user in skype.   If you do not mean impersonating a specific user (like a skype user)  you could just send an `activity` to the bot you basically need to construct a conversation and activity and then send it to the bots endpoint  this is an example where i was doing this from another controller in a test I made:

```cs
            MicrosoftAppCredentials.TrustServiceUrl(activity.ServiceUrl);
            ConnectorClient connector = new ConnectorClient(new Uri(activity.ServiceUrl));

            var reply = activity.CreateReply(activity.Text);
//swap the to and from
            var replyFrom = reply.Recipient;
            var replyRecipient = reply.From;

            reply.From = replyFrom;
            reply.Recipient = replyRecipient;
            reply.ReplyToId = activity.ReplyToId;
            
            var jsonReply = JsonConvert.SerializeObject(reply);

            await connector.Conversations.ReplyToActivityAsync(reply);
            TrafficController.AddMessage(jsonReply);

            var response = Request.CreateResponse(HttpStatusCode.OK);
            return response;
```

**Comment by emimontesdeoca** [comment]
Well,

thank you @JasonSowers, I'll see what I can do, I'm closing this since you answered my question.
