### ISSUE TITLE
Microsoft documentation: Good tutorial, not clear on the next step

### ISSUE THREAD

**Issue by I-cycle** [Microsoft/BotBuilder#4490]
## Bot Info
* SDK Platform: Node.js
* SDK Version: newest/current stable
* Active Channels: local development
* Deployment Environment: none

## Issue Description
I read the microsoft website and get the bot up and running in Eclipse with the bot-emulator. I have been trying to read the SDK to figure out what options are available in each command and struggling to know what is available. I have read the "Bot Builder SDK Chat Reference Library" but seems to lack what to do with each method and lacks API that is shown in the tutorials. How should one proceed to fill in the blanks?

I have good knowledge of Java programming but I am new to javascript and Node.js.

I can use the basic find command to find the missing API, but I still have trouble identifying what to do to change the behaviors of methods like "universalbot.on," "new builder.UniversalBot(connector, function (session) {}," and the restify server.

An example of what I mean by "missing API" in the reference library:
I go to Interfaces->IMessage->address and there is no reference to address->"id".
Also, Interfaces->IMessage->membersAdded doesn't exist but my code copied from the tutorial clearly uses it successfully. See your documentation [here for reference](https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node/core-GetConversationMembers). I copied over the if statement but I can't find the documentation that describes "membersAdded."

**Comment by JasonSowers** [comment]
I have forwarded this issue to the docs team.

**Comment by stevengum97** [comment]
Could you provide the code you're using from the sample? Are you just attempting to spin up the sample and running into issues? Correct me if I'm wrong, but I believe you have questions on the operations generated from the Swagger file, namely the [GetConversationMembers](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference#get-conversation-members) operation?

**Comment by I-cycle** [comment]
Hello, I am having issues reading the documentation. For example, I am using the node.js version and wanted to implement functionality such as [this sample](https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node/core-GetConversationMembers). The problem for me is that I am a beginner at this and the documentation appears to have several references to [the azure site](https://docs.microsoft.com/en-us/azure/bot-service/), [bot framework api site](https://docs.botframework.com/en-us/node/builder/chat-reference/modules/_botbuilder_d_.html), and the [sdk site](https://github.com/Microsoft/BotBuilder/tree/master/Node/core) but is **unclear** as how to connect the three together effectively to get started. Right now I am having trouble reading it and understanding how to alter the behavior in a customized way.

Basically, I am currently using the Eclipse IDE and does not give code recommendations like it would for regular Java code. I am forced to know what to do before it is programmed without that kind of assistance.

Again, I am new to javascript so I was not expecting to grasp it right away, but I have been spending approximately 8-12 hours per week for several weeks now and am making limited progress. Could you at least explain how the API is structured? For example:
 - what do the interfaces do and how do they contribute to the main javascript files? 
 - how should I know what variables will be available in each package, like UniversalBot or connector?
 - what can I do to assist in understanding how to extract and log information from user interactions with the bot?

P.S. I already have a functioning bot code (with a good logging function) thanks to the tutorial, my problem exists with customizing the code.

**Comment by I-cycle** [comment]
Sorry, is it a stupid question to ask how to read the documentation?

**Comment by fanidamj** [comment]
Closing the issue assuming it as resolved. Please reopen a new issue if it still persists.
