### ISSUE TITLE
ChatConnector: receive - no security token sent.

### ISSUE THREAD

**Issue by cext001** [Microsoft/BotBuilder#4497]
I am trying to integrate my Dialogflow agent with Skype. I follow this link https://github.com/dialogflow/dialogflow-nodejs-client/tree/master/samples/skype to customize my bot responses. The webhook is deployed on Heroku. The issue is that I am getting this error "error: chatconnector: receive - no security token sent" always. The below CURL request looks fine

curl -X POST \
  https://login.microsoftonline.com/botframework.com/oauth2/v2.0/token \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/x-www-form-urlencoded' \
  -H 'postman-token: 2774cb69-14bb-7247-d3bb-7bdda2de0e4c' \
  -d 'grant_type=client_credentials&client_id=f6f66a29-f184-48a0-9913-bda96c22be4f&client_secret=bkVCGV20*%25%2BfoicfITP333%40&scope=https%3A%2F%2Fapi.botframework.com%2F.default'

You can test this code and it clearly says there is no issue with Microsoft API regarding authentication. I am really stuck with this. Please help me in solving this.

## Bot Info
* SDK Platform: 
* SDK Version: 
* Active Channels: 
* Deployment Environment: 

## Reproduction Steps
1.
2.
3.

**Comment by JasonSowers** [comment]
Closing as duplicate of https://stackoverflow.com/questions/49927821/dialogflow-nodejs-client-showing-no-security-token-sent-error

**Comment by rkbala** [comment]
Guys, just make the appID and appPassword as null if you don't want to use the same as part of testing from emulator. (Emulator local testing does not need appid and apppassword)

//use this for testing in local and if you don't have appid and app password

var appId = null;
var appPassword = null;

This will resolve this error. Thanks.
