### ISSUE TITLE
Replying to a Teams message with a Like reaction via C#

### ISSUE THREAD

**Issue by tomorgan** [Microsoft/BotBuilder#4499]
## Bot Info
* SDK Platform: NET
* SDK Version: Microsoft.Bot.Connection v3.15.0
* Active Channels: MS Teams
* Deployment Environment: local via ngrok and testing in Teams client

## Issue Description
I'm trying to write code to have my Bot respond to a message with a Like. I'm replicating what I'm seeing when someone else Likes a bot message, and trying to do the same, as I can't find this documented anywhere. (so I could be doing it wrong)

## Code Example
~~~~
 var connector = new ConnectorClient(new Uri(serviceURL));
 Activity newMessage = (Activity)Activity.CreateMessageActivity();
 newMessage.Type = ActivityTypes.MessageReaction;               
 var reactions = new List<MessageReaction>
                {
                    new MessageReaction("like")
                };
                newMessage.ReactionsAdded = reactions;
                var res =  await connector.Conversations.ReplyToActivityAsync(conversationID, activityID, newMessage);
~~~~

## Reproduction Steps
1. Mention the bot in a channel message (i.e. "@bot hey do you like this?"
2. In the bot code, catch the message, and reply with the code above
3. Error is thrown (see below)

## Expected Behavior
The bot should Like the message

## Actual Results
{"Operation returned an invalid status code 'BadRequest'"}
at Microsoft.Bot.Connector.Conversations.<ReplyToActivityWithHttpMessagesAsync>d__8.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Bot.Connector.ConversationsExtensions.<ReplyToActivityAsync>d__7.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown 

Here are the Request / Response messages from the Exception:
Request Content: "{\r\n  \"type\": \"messageReaction\",\r\n  \"reactionsAdded\": [\r\n    {\r\n      \"type\": \"like\"\r\n    }\r\n  ],\r\n  \"attachments\": [],\r\n  \"entities\": []\r\n}"

Response Content: 
"{\"error\":{\"code\":\"BadArgument\",\"message\":\"Unknown activity type\"}}"

**Comment by JasonSowers** [comment]
I am looking into this

**Comment by JasonSowers** [comment]
So upon some investigation, since I had never actually seen someone use the message reaction activity type.  You are trying to use it not as it was intended to be used.  This activity type will update the bot when someone has liked (or some sort of reaction)  to an activity.  It is not intended to actually send and registed a reaction from the bot.

[From the docs:](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-activities#messagereaction)

> Some channels will send messageReaction activities to your bot when a user reacted to an existing activity. For example, a user clicks the "Like" button on a message. The ReplyToId property will indicate which activity the user reacted to.

The messageReaction activity may correspond to any number of messageReactionTypes that the channel defined. For example, "Like" or "PlusOne" as reaction types that a channel may send.

**Comment by tomorgan** [comment]
Hmm interesting. Any reason why it shouldn’t work like this (other than it not being coded in)? Can I add it to the backlog? For me, it seems to be a nice subtle way for the bot code to acknowledge that it’s received and understood the message: for instance, if you send a message to a bot to do something, a like is a good way of saying “ok, I understand what you asked and I’m doing it” where a full reply isn’t needed.

**Comment by JasonSowers** [comment]
Feel free to Submit a pull request if you would like.  With V4 coming out soon we are not looking to add features to V3 at this point.

**Comment by attozk** [comment]
+1 for this

**Comment by mohsinhere** [comment]
Hi,

I'm also looking for a way for my teams bot to respond to a message. Eg: Instead of saying "Thank you".

Is this on the road map by any chance?
