### ISSUE TITLE
[Azure] Cannot show bot user/message stats

### ISSUE THREAD

**Issue by austinhuang0131** [Microsoft/BotBuilder#4501]
## Bot Info
* SDK Platform: 
* SDK Version: 
* Active Channels: 
* Deployment Environment: Azure Bot Service
## Issue Description
![image](https://user-images.githubusercontent.com/16656689/39055390-1d010e5a-4482-11e8-83f1-d871c2c8dd41.png)

Cannot show users or messages stats. Only the "Retention" is visible.

## Reproduction Steps
1. Enable Application Insight in Azure.
2. Enable analytics in bot channel reg.
3. Go to analytics.

## Expected Behavior
Show stats and the graph.

## Actual Results
See screenshot.

**Comment by ItsMeArthur** [comment]
I'm facing the same issue. Reported it here #4500.

**Comment by austinhuang0131** [comment]
ok merged
