### ISSUE TITLE
[Node.js, Skype For Business] Cannot initiate a conversation with Skype For Business bot using an ended conversation’s id.

### ISSUE THREAD

**Issue by nickgkan** [Microsoft/BotBuilder#4512]
**Description:** We try to have the bot trigger a conversation asynchronously, without any users’ input. Based on the sample found here https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node/core-CreateNewConversation it seems that a sufficient way could be `bot.beginDialog(address, 'survey');`. Information about different channels’ support to the feature above are also found in the same link. We noticed however, that there is no mention for Skype For Business, so we experimented further with this channel.

**Experiments**
_Experiment #1_: Try to use the proposed method.
This approach did not work. The address object seems to be retrieved fine and the dialog is indeed triggered, but no message is sent to the user. After thorough examination of the log files, it seems that the whole flow ran smoothly, but when calling session.endConversation(‘message’), a 500 Internal Server error is raised. The whole error message is:
Error: POST to 'https://webpooldb40r04.infra.lync.com/platformservice/tgt-9b3b1dce44145cc6971596f90f099b47/botframework/v3/conversations/MTMwMTcyYWEjc2lwOmN5YmVyYm90ZGV2QG1ldGlzLnRlY2g%3D/activities/0' failed: [500] Internal Server Error
    at Request._callback (/usr/src/app/node_modules/botbuilder/lib/bots/ChatConnector.js:559:46)
    at Request.self.callback (/usr/src/app/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

Note that a similar error (different status code) is also encountered when terminating a conversation with Skype, but that does not affect its functionality.

_Experiment #2_: Do not terminate a conversation and try the proposed method
The approach did work, but when terminating conversation once, it stops working, throwing the same error as in experiment 1. Another interesting observation is that the messages never get delivered if the conversation window is closed, although there is a notification about an incoming message, similar to [3749](https://github.com/Microsoft/BotBuilder/issues/3749) and [3636](https://github.com/Microsoft/BotBuilder/issues/3636) . 

**Experimentation results**
It seems that a conversation in Skype for Business channel can only be accessed once. When users send a message to the bot and it answers back with session.endConversation(‘message’), the conversation is considered closed and further communication using the address object that contains this conversation id is impossible. In fact, immediately after the bot’s answer, Skype for Business sends the message “We saved this conversation. You'll see it soon in the Conversations tab in Skype for Business and in the Conversation History folder in Outlook.”, that is usually sent when a conversation is considered closed.
We also tried to preserve a conversation and not terminate it, but this had serious effects in our system’s stability, as the message flow could not be controlled as desired.
Therefore, it seems that a Skype for Business bot is not able to trigger a conversation and send a message to the user.

Any suggestions?

**Comment by EricDahlvang** [comment]
Have you tried creating a new conversation, and using that conversation.id to send the message?  There's a c# example of this here: https://msdn.microsoft.com/en-us/skype/skype-for-business-bot-framework/docs/overview#create-outbound-bots

**Comment by nickgkan** [comment]
Well, I can not figure out how to make it work with Node.js, I see there is already an open issue related to this [3050](https://github.com/Microsoft/BotBuilder/issues/3050).

**Comment by EricDahlvang** [comment]
Closing this, since https://github.com/Microsoft/BotBuilder/issues/3050 is older and tracking the same issue.
