### ISSUE TITLE
[Nodejs, Fb Messenger] Error Changing Settings For Facebook Messenger in Azure Portal

### ISSUE THREAD

**Issue by rongyao2006** [Microsoft/BotBuilder#4516]
Hi, am still having the issue, unable to change my settings in the azure portal.

## Bot Info
* SDK Platform: NodeJS
* SDK Version: 8.11.1
* Active Channels: Facebook
* Deployment Environment: Google Cloud Compute Engine

## Issue Description
Whenever I try to change any settings for Facebook Channel, I get the following error

Unable to save. Failed to validate Facebook credentials: invalid token ID: <token>

## Reproduction Steps
1. Go to Azure Portal
2. Go to bot channel registration resource
3. Go to channels
4. Amend settings for Facebook Messenger
5. Save Changes
6. Error message in red bar appears on top

**Comment by JasonSowers** [comment]
Can you please provide your app ID?

**Comment by rongyao2006** [comment]
@JasonSowers Here's my app ID: bb0b6524-2c77-4cb3-97b9-4777a4e48d54

Pretty sure I the credentials are correct, and i tried like more than 10 times but it just refuse to go through.

**Comment by rongyao2006** [comment]
I tried deleting the channel and adding again, but that failed too.

**Comment by JasonSowers** [comment]
Are your credentials perhaps in use by another bot?

**Comment by LMEdwards** [comment]
I'm experiencing the same issue - unable to save any changes to the Facebook channel settings with the following error:

Unable to save. Failed to validate Facebook credentials: invalid token ID: 

App ID is
2573bec2-891f-4ade-b5ac-65d3e2f7148e

**Comment by mminchev** [comment]
I get the exact same error when I create a new Bot Channel Registration in Azure and try to configure a Facebook Messenger channel. I am using the correct Facebook credentials for sure but I get the "Unable to save. Failed to validate Facebook credentials" error. This must be a problem coming from Azure. 

Do you know when this will be resolved?

**Comment by otiunov** [comment]
I have the same error when try to configure Facebook channel:

"Unable to save. Failed to validate Facebook credentials: invalid token ID:"
App ID: 7e440ebd-e3df-4876-9168-dc1938d1e8d9

I have only one Bot Channel Registration now. 
A month ago I configured FB channel without any problem, but yesterday I changed Messaging endpoint and try to reconnect FB page and got the error. Then I deleted old Channel Registration and create a new one, during configuring FB channel got the same error.

Any updates from Azure guys ?

**Comment by craigjensen** [comment]
Invalid Token errors typically mean that there's a problem with either the AppId, AppSecret or AccessToken.  We validate those parameters via Facebook's [debug_token](https://developers.facebook.com/docs/graph-api/reference/v3.0/debug_token) api.  You can try it yourself by making a get call in your browser to https://graph.facebook.com/v3.0/debug_token?input_token={accessToken}&access_token={appId}|{appSecret} and see what error comes back.

**Comment by craigjensen** [comment]
Would you mind sending me the debug_token output at cjensen (at) microsoft.com?

**Comment by otiunov** [comment]
@craigjensen Done. Please check email

**Comment by otiunov** [comment]
It works!!! 
Thanks

**Comment by JasonSowers** [comment]
Is this not resolved for anyone?

**Comment by pavlovps** [comment]
@JasonSowers at 9 or 10th of May I was capable to create new Facebook channel. Looks like something was changed on the Facebook side and at least at that moment it was fine

**Comment by priyatharshiniSundaram** [comment]
hi i too experienced the same issue ,can anybody please suggest me to resolve this error

**Comment by craigjensen** [comment]
Try hitting the debug_token endpoint directly from your browser and see if it provides any clues as to what the problem might be: https://graph.facebook.com/v3.0/debug_token?input_token={accessToken}&access_token={appId}|{appSecret}  (Make sure you substitute your accessToken, appId and appSecret)

**Comment by priyatharshiniSundaram** [comment]
Hi Thanks for your reply my app is valid ,it returns the following output while the debug_token endpoint,


{
   "data": {
      "app_id": "963093917231833",
      "type": "PAGE",
      "application": "Priya's first app",
      "expires_at": 0,
      "is_valid": true,
      "issued_at": 1539156433,
      "profile_id": "930024693860368",
      "scopes": [
         "pages_messaging",
         "pages_messaging_subscriptions",
         "public_profile"
      ],
      "user_id": "1109534122528768"
   }
}

after that i tried to pass the facebook credentials to bot channel it shows the below error

[cid:df28f098-8cf1-4b4b-8862-220d585cb48f]

could you please help me out on this,how to troubleshoot this.

Thanks & Regards,
Priya.S
________________________________

**Comment by craigjensen** [comment]
Please also verify that the returned profile_id matches the PageId that you entered into the Facebook settings page.

**Comment by priyatharshiniSundaram** [comment]
hi thanks for your support.


Its working now,could you able to help me to automate my bot messenger in FB,any reference article.


Thanks & Regards,

Priyatharshini.S


________________________________

**Comment by prasanthrpadharthi** [comment]
We are facing the above issue all of a sudden from today morning. Our bot is working fine for the past one year and from today we are getting this error. **_"This Page access token belongs to a Page that is not accessible"_**

**Comment by prasanthrpadharthi** [comment]
Any quick help on how to solve the same. Advance thanks

**Comment by craigjensen** [comment]
Were any changes recently made to your Facebook page?  You might try generating a new page access token in Facebook and updating your bot's configuration. See [here ](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-facebook?view=azure-bot-service-4.0)for details.

**Comment by prasanthrpadharthi** [comment]
@craigjensen Thanks for replying back.
Yes i tried generating new token but no luck.

The changes that were made is submitting for review for the page_messages for continuous subscription messaging top send notifications to all the employees.

Also observed that no page information is displayed under the ChiaHCM page when i use https://graphapi.com/me/accounts API.

Where as undisturbed Test Page is still working fine, shows all the pages tied up with the account.
![graph api accounts response](https://user-images.githubusercontent.com/36985649/50941201-dc11b300-14be-11e9-8ac1-945a7542ff5e.png)

**Comment by craigjensen** [comment]
I'm not sure what the problem is.  You may need to open a support ticket with Facebook.  Please post your findings when you hear back from them.
