### ISSUE TITLE
Documentation unclear about how to use the wechat channel

### ISSUE THREAD

**Issue by catcher-in-the-try** [Microsoft/BotBuilder#4519]
According to the documentation here:

https://docs.botframework.com/en-us/channel-inspector/channels/WeChat/

Microsoft Bot Framework supports the WeChat messenger.

However, I could not find any mention of it anywhere else in the documentation, and it is unclear how to initialize a wechat bot.

Can you clarify please and improve the docs?

**Comment by JasonSowers** [comment]
WeChat is not officially supported at this time.  I have filed a bug against the channel inspector as it should not show up there at this time.

**Comment by sanjeevgaut** [comment]
Hey Jason and Fanidamj, 
Can you please give steps to connect Microsoft bot with wechat. I have requirement to connect ms bot with  wechat. 

I am using nodejs and v4 for development.

Thanks
Sanjeev Gautam
