### ISSUE TITLE
Difference in performance when using and not using webSockets with direct line

### ISSUE THREAD

**Issue by vamzz1** [Microsoft/BotBuilder#4520]
## Bot Info
* SDK Platform: Node.js 
* SDK Version:  3.14.1
* Active Channels: Direct Line, fb 
* Deployment Environment:  Azure App Service

## Issue Description
 When creating the directline bot connection, the value of the flag `webSocket` is leading to undesired/misleading effects.

## Code Example
        var botConnection = new BotChat.DirectLine({
            domain: XXXXX,
            secret: XXXXX,
            token: XXXXX,
            webSocket: false
        });

## Reproduction Steps
1. When `webSocket is true` a lot of bot messages are throwing timeout or internal server error.
2. When `webSocket is false`, the `sendTyping` message is not being displayed.

## Expected Behavior
1. Ideally one would expect webSockets to outperform it's counterpart when it comes to latency related issues which clearly doesn't seem to be the case.
2. Also I'm not sure why the choice of using or not using webSockets has an impact on whether sendTyping is rendered.

## Concern
* I want to understand what other side effects are possible when choosing to use or not use `webSockets` while initializing the directline connection.
* What is the recommended option when initialzing the directline bot connection. Currently we have fallbacked to not using webSockets due to the high number of errors while sending bot messages.

**Comment by stevkan** [comment]
Hi @vamzz1,

Is the code snippet above exactly how you are using it? Are you using both a secret and a token and are you using the default Direct Line endpoint? You are only allowed to use a secret or a token, not both. The domain you can leave out unless you are trying to use a region-specific endpoint (which then needs to be the full URL).

I did spin up a bot using the direct line channel with web sockets enabled. I also implemented a small check to verify the web socket is opening. I am not experiencing any timeouts/errors or missing messages when interacting with the bot.

Could you post the code for your bot as well as the botchat.app call in the client so I can see how you are implementing (please remove any AppIDs, secrets/tokens, or passwords)?

Steve.

**Comment by vamzz1** [comment]
var model = {
            "userId": XXXXX,
            "userName": "You",
            "botId": "XXXXX",
            "botIconUrl": "//bot-framework.azureedge.net/bot-icons-v1/bot-framework-default.png",
            "botName": "XXXXX",
            "secret": "XXXXX",
            "iconUrl": "//bot-framework.azureedge.net/bot-icons-v1/bot-framework-default.png",
            "directLineUrl": "https://webchat.botframework.com/v3/directline",
            "webSocketEnabled": "false",
            "speechTokenEndpoint": "https://api.botframework.com/v3/speechtoken"
        };

        var botConnection = new BotChat.DirectLine({
            secret: model.secret,
            webSocket: false
        });

        BotChat.App({
            botConnection: botConnection,
            user: { id: model.userId, name: model.userName},
            bot: { id: model.botId, name: model.botName },
            resize: 'window',
            locale: 'en'
        }, document.getElementById("BotChatElement"));


Also I'm no longer facing any timeout based issues after scaling out the instance from S1 to S3. I maybe wrong but I'm guessing when the server is under load, disabling webSockets is performing better.

**Comment by stevkan** [comment]
Hi @vamzz1,

It looks like you are using an older implementation for building BotChat.App. If you follow the instructions located [here](https://blog.botframework.com/2017/10/11/customize-web-chat-websites/) you'll see that creating the botConnection variable is no longer necessary. The direct line params are included in the BotChat.App code. This convention follows the current v3 SDK.

When I use your code (webSocket set to true or false) with the direct line params included in BotChat.App I am able to run the bot without any issues. My Facebook app responds with no latency or missing messages. Please see my included code, for reference.

One other point to consider, are you running this behind a firewall?

Try it out and let me know.

```
    var model = {
        "userId": "1234",
        "userName": "User",
        "botId": "directBot",
        "botIconUrl": "//bot-framework.azureedge.net/bot-icons-v1/bot-framework-default.png",
        "botName": "directBot",
        "secret": "XXXXXXXXXXXXXXXXXXXXXXXXX",
        "iconUrl": "//bot-framework.azureedge.net/bot-icons-v1/bot-framework-default.png",
        "directLineUrl": "https://webchat.botframework.com/v3/directline",
        "webSocketEnabled": 'true',
        "speechTokenEndpoint": "https://api.botframework.com/v3/speechtoken"
    };

    BotChat.App({
        directLine: {
		secret: model.secret,
		webSocket: model.webSocketEnabled
	},
        //you can dynamically retrieve the logged in user info in your mvc View
        //and pass thoes info to your bot
        user: { id: model.userId, name: model.userName},
        bot: { id: model.botId },
        resize: 'window',
        locale: 'en'
    }, document.getElementById("BotChatElement"));
```

**Comment by stevkan** [comment]
Closing issue as resolved due to no response. Please reopen, if necessary.

**Comment by roshan1109** [comment]
Hi @stevkan ,

Here is my chatbot call from my HTML page:
    var user = {
        id: 'xxxxx',
        name:'xxxxx'
    };

    var botConnection = new BotChat.DirectLine({ secret: 'blablabla' });
    BotChat.App({
        user: { id: 'Roshan' },
        botConnection: botConnection,
        bot: { id: 'xxxx', name: 'xxx' },
        resize: 'detect',
        webSocket: true
    }, document.getElementById("bot"));

    botConnection.postActivity({
            from: user,
            name: 'requestWelcomeDialog',
            type: 'event',
            value: ''
        })
        .subscribe(function (id) {
            console.log('"trigger requestWelcomeDialog" sent');
        });

-----------------------------------------------------------
As you can see(from attached file), I am able to connect to my bot from my web app(asp.net Mvc ) successfully. But, issue is I keep getting those "re-send" messages during the entire chat. This is not expected. Please advise where I could be going wrong,
![Re-try errors](https://user-images.githubusercontent.com/49524453/55961040-a7fb8900-5c8b-11e9-9e62-ddd2ebb505ce.PNG)


Thanks
Roshan

**Comment by roshan1109** [comment]
Would like to also add that in my home wi-fi network, it works fine but as soon as I enter my organization LAN , this behavior starts kicking in more consistently. Could this be firewall issue? In that case, should it not disallow any chat to happen itself? Please advise.
