### ISSUE TITLE
Cannot consume 'Microsoft.Bot.Builder.Calling' in Asp.Net Core 2.0

### ISSUE THREAD

**Issue by weng5e** [Microsoft/BotBuilder#4523]
## Bot Info
* SDK Platform: .NET (Asp.Net Core 2.0 Web API application, targeting net 461, win7-x64 runtime)
* SDK Version: 3.15.0 
* Active Channels: 
* Deployment Environment: Azure App Service and local development  

## Issue Description

The top level entry point for the 'Microsoft.Bot.Builder.Calling' nuget is the [CallingConversation ](https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Microsoft.Bot.Builder.Calling/CallingConversation.cs)static class. One parameter of the 'SendAsync' method is of type [HttpRequestMessage](https://msdn.microsoft.com/en-us/library/system.net.http.httprequestmessage(v=vs.118).aspx), which can be easily accessed in classic [Asp.Net ApiController](https://msdn.microsoft.com/en-us/library/system.web.http.apicontroller(v=vs.118).aspx). But it cannot be accessed in Asp.Net Core 2.0's [Controller class](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.controller?view=aspnetcore-2.0) or [ControllerBase Class](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.controllerbase?view=aspnetcore-2.0). What should be the best practice for using this API?

## Code Example

[CallingBotAspNetCore20.zip](https://github.com/Microsoft/BotBuilder/files/1944197/CallingBotAspNetCore20.zip)

## Expected Behavior

'Microsoft.Bot.Builder.Calling' is not bind to a classic Asp.Net implementation. It can also support Asp.Net Core 2.0.

**Comment by JasonSowers** [comment]
The 'Microsoft.Bot.Builder.Calling'  package was not built with the intention of using it with AspNetCore.  So we really don't have any best practices or guidelines for doing this.

**Comment by weng5e** [comment]
Do we have any plans or ETAs to make it easier to use in Asp.Net Core?

**Comment by JasonSowers** [comment]
At this time there are no plans for it that I know of.  I would assume that Skype would want a version compatible with botbuilder v4, but as of right now there is nothing on the roadmap for it.  With that being said, if you end up modifying the package to make it work directly with core, I highly encourage you to release a package for it.
