### ISSUE TITLE
Not able to add the bot back to the contact list properly

### ISSUE THREAD

**Issue by yaninah** [Microsoft/BotBuilder#4529]
## Bot Info
* SDK Platform: REST
* Active Channels: Skype
* Deployment Environment: local development + Bot Channels Registration

## Issue Description and  Reproduction Steps
I've faced really strange behaviour while trying to add bot back to the contact list after it has been deleted.
I've tested the scenarios in Skype for Linux (version 8.18.0.6) and Web Skype.

### Skype for Linux:
1. User adds the bot to the contacts using https://join.skype.com/bot/<id\> link. The bot receive a payload with "action":"add" and "type":"contactRelationUpdate". And now bot is able to send messages to user and user is able to message the bot.
2. User deletes the bot (right click on the conversation with bot -> “Delete BotName”). Bot doesn’t receive a payload with "action":"remove" and "type":"contactRelationUpdate".The conversation disappears from the list in application and the bot is no longer able to message to the user. 
3. User tried to add the bot back using https://join.skype.com/bot/<id\> link. The bot receives a payload with "action":"add" and "type":"contactRelationUpdate", BUT user’s contact list isn’t updated and the bot can’t message the user (in response - 403 error code and following content: {"error":{"code":"ServiceError","message":"Acl check failed"}}
4. User tries to add the bot from the inside of the Skype app (if some group conversations (where the bot is included) are left in the user's left bar list of conversations user can click on the bot’s icon near some bot's message in group chat and press “Add to Contacts) . In this case the bot doesn’t receive a payload with "action":"add" and "type":"contactRelationUpdate". But user’s contact list is updated and the bot is able to send messages now.

### Web Skype
Very similar behaviour, but there are a few differences (only differences with behaviour mentioned above are pointed):
2. User deletes the bot (right click on the conversation with bot -> “Delete BotName”). Bot RECEIVES a payload with "action":"remove" and "type":"contactRelationUpdate".
3. User tried to add the bot back using https://join.skype.com/bot/<id\> link. The bot receives a payload with "action":"add" and "type":"contactRelationUpdate" ->
THAT’S WHERE STRANGE THINGS HAPPEN 
User’s contact list isn’t updated, BUT the conversation with the bot appears on the UI, but the typing field is disabled for user, but at the same time the bot is actually able to message to user without limits.

**Comment by stevengum97** [comment]
Sorry for the delay, if you are still running into this issue, which distro of Linux are you using?

**Comment by yaninah** [comment]
@stevengum97 Still having this issue. Ubuntu 16.04

**Comment by JasonSowers** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
