### ISSUE TITLE
[QnA Maker] Invoking API through code returns Bad request error.

### ISSUE THREAD

**Issue by rajendrasolleti** [Microsoft/BotBuilder#4530]
## Bot Info
* SDK Platform: .NET
* Active Channels: Cortana, MS Teams, Email, Direct Line
* Deployment Environment:  Azure App Service

## Issue Description
unable to update qna maker to add/delete new qna pairs through code.

## Code Example
var client = new RestClient(uri);
client.AddDefaultHeader("Ocp-Apim-Subscription-Key", KBSubscriptionKey);
var request = new RestRequest(Method.PATCH);                    
request.AddHeader("Content-Type", "application/json");
request.AddBody(postBody);
response = client.Execute(request);

## Expected Behavior
the Qna maker should get updated with the new qna makers sent in the body of the request

## Actual Results
Qna maker doesn't get updated and returns an error of bad request.

**Comment by EricDahlvang** [comment]
Is your postBody serialized as .json?  The QnAMaker service is serializing the body here: https://github.com/Microsoft/BotBuilder-CognitiveServices/blob/master/CSharp/Library/QnAMaker/QnAMaker/QnAMakerService/QnAMakerService.cs#L169

**Comment by arafattehsin** [comment]
I'm facing the same issue.

**Comment by arafattehsin** [comment]
Hi rajendrasolleti, are you able to fetch or generate the answer successfully or are you getting the same error there?

**Comment by EricDahlvang** [comment]
Closing due to no response.
