### ISSUE TITLE
[Feature Request] Skype recognize cannot support speech recognition without choices

### ISSUE THREAD

**Issue by weng5e** [Microsoft/BotBuilder#4531]
## Bot Info
* SDK Platform: .NET 
* SDK Version: 3.15.0 
* Active Channels: Skype 

## Issue Description
The '[Recognize action](https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Microsoft.Bot.Builder.Calling/Models/Contracts/Recognize.cs)' provided in the Microsoft.Bot.Builder.Calling nuget requires providing either '[choices](https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Microsoft.Bot.Builder.Calling/Models/Contracts/RecognitionOption.cs)' or '[collect digits](https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Microsoft.Bot.Builder.Calling/Models/Contracts/CollectDigits.cs)'. This make it impossible to gather open-ended questions' responses from users. All questions through the 'Recognize action' must have deterministic answers or expecting dtmf digits. 

Is it possible to expose an API to gather plain speech recognition result without choices? Similar to [Twilio's Gather](https://www.twilio.com/docs/voice/twiml/gather) action.

**Comment by JasonSowers** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
