### ISSUE TITLE
User should have the ability to suppress TooManyAttempts message in PromptConfirm Dialog

### ISSUE THREAD

**Issue by egracer** [Microsoft/BotBuilder#4533]
## Bot Info

SDK Platform: .NET
SDK Version: 3.14.0
Deployment Environment: Azure Bot Service
Channels: All

## Issue Description

The text in `TooManyAttempts` is always sent when PromptConfirm Dialog attempts are exhausted. There is no way to suppress this message.

## Code Example

https://github.com/Microsoft/BotBuilder/blob/b7d9b2e2bf26e918dc507167d3c868ee0e8d2b43/CSharp/Library/Microsoft.Bot.Builder/Dialogs/PromptDialog.cs#L1178

## Expected Behavior

As a consumer of the SDK, I would prefer that the SDK not send messages unless I choose that they be sent. There is no way for me to disable this message informing the user that they have exceeded the attempt count. I can customize it, but not get rid of it entirely.

As a workaround, at the moment I had to copy the file and make a new PromptConfirm dialog which overrides the `MessageReceivedAsync` method linked above so that the `TooManyAttempts` message is never sent.

**Comment by JasonSowers** [comment]
Feel free to submit a pull request to modify the `PromptDialog` class to do what you would like, or in the spirit of open source, you can use your own modified version of `PromptDialog` that exhibits the behavior you would like to see.

**Comment by egracer** [comment]
Great - happy to do that, figured I'd file this first to see if there was interest / willingness to accept a PR. Thanks for the response!

**Comment by JasonSowers** [comment]
Honestly, at this point when we are actively working on releasing the [V4 version of the SDK](https://github.com/Microsoft/BotBuilder-dotnet), we are not really looking to add features to V3.  It is probably just best to use your own custom PromptDialog.  Additionally, FWIW I have been here for about a year and this is the first request I have seen on the subject.

**Comment by JasonSowers** [comment]
Looks like a few weeks before I joined the team there was a feature request for this #2717 that didn't gain much traction.  going to close this issue and reference in that one.
