### ISSUE TITLE
FormFlow DateTime Kind Varies

### ISSUE THREAD

**Issue by rosskyl** [Microsoft/BotBuilder#4534]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.15.0
* Active Channels: 
* Deployment Environment: Local development with emulator

## Issue Description
When I use FormFlow to get a DateTime, the kind varies based on whether the user enters a time or a word. When they enter a time (i.e. 3 pm) the resulting DateTime has a kind of Unspecified. When they enter a word (i.e. now, yesterday, tomorrow) the resulting DateTime has a kind of Local.

## Code Example
Form class
```
[Serializable]
public class CallbackForm
{
	[Prompt("What is your name?")]
	public string Name { get; set; }

	[Prompt("What is your phone number?")]
	[Pattern("1?\\W*([2-9][0-8][0-9])\\W*([2-9][0-9]{2})\\W*([0-9]{4})(\\se?x?t?(\\d*))?")]
	public string PhoneNumber { get; set; }

	[Prompt("When would you like an agent to call you?")]
	public DateTime? Time { get; set; }

	public static IForm<CallbackForm> BuildForm()
	{
		IFormBuilder<CallbackForm> formBuilder = GetFormbuilder();

		return formBuilder.Field(nameof(Time), validate: ValidateDate)
						  .Confirm("Is this information correct?{*}")
						  .Build();
	}

	private static Task<ValidateResult> ValidateDate(CallbackForm state, object value)
	{
		DateTime now = DateTime.UtcNow;
		DateTime originalTime = (DateTime)value;

		if (originalTime.Kind != DateTimeKind.Unspecified)
			originalTime = DateTime.SpecifyKind(originalTime, DateTimeKind.Unspecified);

		ValidateResult result = new ValidateResult()
		{
			IsValid = true,
			Value = originalTime
		};

		string timeZoneName = ConfigurationManager.AppSettings["baseTimeZone"];
		TimeZoneInfo timeZone = TimeZoneInfo.FindSystemTimeZoneById(timeZoneName);
		DateTime utcTime = TimeZoneInfo.ConvertTimeToUtc(originalTime, timeZone);

		if (utcTime < now)
		{
			result.IsValid = false;
			result.Feedback = "The date you entered is in the past";
		}
		return Task.FromResult(result);
	}

	private static IFormBuilder<CallbackForm> GetFormbuilder()
	{
		IFormBuilder<CallbackForm> formBuilder = new FormBuilder<CallbackForm>()
					.Message("Please enter your information to schedule a callback.")
					.Field(nameof(Name))
					.Field(nameof(PhoneNumber));

		var noPrefTemplate = formBuilder.Configuration.Templates.Find(t => t.Usage == TemplateUsage.NoPreference);
		noPrefTemplate.Patterns = new string[] { "No Changes", "Cancel" };

		formBuilder.Configuration.NoPreference = noPrefTemplate.Patterns;

		return formBuilder;
	}
}
```
Method used to call the form
```
IFormDialog<CallbackForm> form = new FormDialog<CallbackForm>(new CallbackForm(), CallbackForm.BuildFormLater, FormOptions.PromptInStart);
context.Call(form, AfterForm);
```

## Expected Behavior
The resulting DateTime object to have the same kind regardless of what the user enters.

## Actual Results
When the user enters "now", the DateTime kind is Local.
When the user enters "3 pm", the DateTime kind is Unspecified.

**Comment by JasonSowers** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
