### ISSUE TITLE
Getting conversation ID for Skype group

### ISSUE THREAD

**Issue by hrmun-webimpact** [Microsoft/BotBuilder#4536]
Hi, this is the first time I use the framework and I am struggling to get the result.
I am trying to create a conversation by requesting 

> https://smba.trafficmanager.net/apis/v3/conversations/

with the following JSON using PHP

```
{ 
  "bot":
        { 
    	"id":"28:b80e8a23....",
  	},
  "isGroup":true,
  "members":[
    	{
          "id":"28:b80e8a23....", // Bot itself
        },
        {
          "id":"29:1zMqXe6EG7OK....", // User A
        },
        {	
          "id":"29:1PxVyh0ulPcE....", // User B
        }
  ],
  "topicName":"Test bot",
}

```
and wish to get the conversation ID. 

But the result always return the Skype ID of the first user in JSON  **"id":"8:live_userA"**

When I try to switch the position of first and second user such that

```
{ 
  "bot":
        { 
    	"id":"28:b80e8a23....",
  	},
  "isGroup":true,
  "members":[
    	{
          "id":"28:b80e8a23....", // Bot itself
        },
        {
          "id":"29:1PxVyh0ulPcE....", // User B
        },
        {	
          "id":"29:1zMqXe6EG7OK....", // User A
        }
  ],
  "topicName":"Test bot",
}
```

The result will be **"id":"8:live_userB"** and it will never be the actual conversation ID of the group.

 I am also not sure what is the meaning of those prefixes like 19, 28, 29, etc.

Any help or explanation will be much appreciated!

**Comment by EricDahlvang** [comment]
Skype uses the contact id for the conversation id.  This is explained some on this answer: https://github.com/ShyykoSerhiy/skyweb/issues/16#issuecomment-159226849

**Comment by hrmun-webimpact** [comment]
d

**Comment by hrmun-webimpact** [comment]
@EricDahlvang Hello thanks for response!
I understand that it uses contact ID for conversation ID, but what I am trying to achieve is that sending a message to a Skype group instead of individual. For example in my application, I have a text field that allows user to enter multiple Skype IDs and once it is submitted, a message will be sent to all the users in a Skype group but not one by one to the user.

**Comment by lunyi** [comment]
> @EricDahlvang Hello thanks for response!
> I understand that it uses contact ID for conversation ID, but what I am trying to achieve is that sending a message to a Skype group instead of individual. For example in my application, I have a text field that allows user to enter multiple Skype IDs and once it is submitted, a message will be sent to all the members in a Skype group but not one by one to the member. Basically I need a Skype group ID, is there any way to do it?

@wi-hrmun Did you get the answer? I am also new to bot framework recently and meet this problem.

**Comment by jous** [comment]
@wi-hrmun @lunyi, 
You need to generate Skype Group Chat Id somehow. If you have already created the group, you can get it's id by using skype web and looking at the requests with developer tools. This answer worked for me: https://stackoverflow.com/a/58405033/481918
