### ISSUE TITLE
How to identify which version of Skype client ?

### ISSUE THREAD

**Issue by JonesAbramoff** [Microsoft/BotBuilder#4539]
## Issue Description
Skype clients behave differently and I would like to distinguish between them.

For example, if I have a herocard with a button that opens an URL like http://www.zapprices.com/zp779.html?779A9 it will work fine in Android Skype but not in PC Skype 7.41 because this PC version only allows https. It shows the button with the correct link but simply doesn´t work.

Knowing which client Skype version, I would avoid herocard since it wouldn´t work.

**Comment by austinhuang0131** [comment]
Not official answer...But I think that client version should not be revealed to anyone except the system (even if you're the one that's conversing with the user) since this is a common practice in the IM industry.

**Comment by JonesAbramoff** [comment]
Hi, I wouldn't need to distinguish between Skype versions if they had the same behaviour besides visual aspects. The same herocard works fine in Android but in pc did not because of http vs https issue.

**Comment by EricDahlvang** [comment]
Closing this issue.  There is not currently a way to differentiate between Skype clients from within a bot.
