### ISSUE TITLE
[C#] message.Language is null

### ISSUE THREAD

**Issue by rlilov** [Microsoft/BotBuilder#454]
I translated my bot adding french language using MAT tool.
All works very well in emulator, Culture is respected.

When I deploy, testing from Telegram and FB Messenger, bot speaks only in English (default language) Inspecting Language field of the message coming from user (according to documentation this is where culture comes from) it is always null.

Is this a bug or there are alternative ways for the bot to know what language he needs to talk?

p.s. I am not using LUIS and have disabled Bing translation as it does not translate fields etc. and automatic translation is marginal quality considering the specific business domain that bot works in.
p.s.2 devices I am testing from have French set as language

**Comment by chrimc62** [comment]
This is determined by the channel and not all channels report language.  When messages come in if the language is null you could either:
a) Use cognitive services to detect the language. https://www.microsoft.com/cognitive-services/en-us/text-analytics-api
b) Ask the user and store in the per-user store their language preference.  (And even here you probably want to use the prior API to decide what language to ask.)
