### ISSUE TITLE
Channels, Test in Web Chat and Analytics sections are blank

### ISSUE THREAD

**Issue by alexeymkh** [Microsoft/BotBuilder#4541]
## Bot Info
* SDK Platform: Node.js
* SDK Version: 3.14.1
* Active Channels: Facebook, Telegram
* Deployment Environment: Dokku

## Issue Description
The "Channels" section, "Test in Web Chat" section and "Analytics" section in the Azure Portal are blank. I can't do any manipulations with them. Language in my Azure account is English.

## Code Example
N/a

## Reproduction Steps
1. I go on my resources page on Azure Protal
2. Click on my bot resource
3. Click on "Channels"
4. Click on "Test in Web Chat"
5. Click on "Analytics"

## Expected Behavior
I expect to see the this sections when I click on their names.

## Actual Results
Empty screen in every mentioned section.
https://i.imgur.com/h2lxMA3.png
https://i.imgur.com/xhZQa4V.png
https://i.imgur.com/i8zk9fs.png

**Comment by austinhuang0131** [comment]
Check adblock or firewall? I can't reproduce this issue.
