### ISSUE TITLE
Service Error:A task was canceled

### ISSUE THREAD

**Issue by matheus208** [Microsoft/BotBuilder#455]
We have recently published our bot and with the increase in users, we have been getting this error more frequently now.

I could not pinpoint the cause and I'm not able to replicate it, but sometimes users will send a message to our bot, and it will reply with "Service Error:A task was canceled."

I assume it is from the framework service, since this error would not be thrown within our app.

Do you have an idea what might be the cause?

Thank you in advance!

**Comment by chrimc62** [comment]
This should not be happening.  Added @dandriscoll who should be able to help you narrow this down.

**Comment by rociocastillo** [comment]
Hi, my bot is returning me the same message "A task was canceled", but in this case I am the only one who knows this usando.Does anyone know why this might be?

thank you very much.

**Comment by dandriscoll** [comment]
Are you seeing this coming back from our service, or is it entirely within the bot's process? If the former, do you have a URL that's producing the error?

**Comment by matheus208** [comment]
It's hard to pinpoint where it's coming from, since it has never happened to me. But now that we have released a preview version of our bot on Messenger and people have started to use it, I've see this sent to users when I check the messaging history.

We are using Heroku to host our bot, so it might be an exception from their side thrown back to bot framework and it gets interpreted as a message?

Here is the page (you can message a zip code like 01311-300 to get results) : https://www.facebook.com/IFood-Assistente-783015081834627/

**Comment by dudeofawesome** [comment]
Has anyone been able to track this down? I just started experiencing the `Service Error:A task was canceled.` error today with my own bot.

This appears to be a C# error, which makes me think it's a server error since my bot is written in Javascript.

**Comment by ernanirst** [comment]
I'm also getting this error. I didn't manage to reproduce it locally, only on Azure. I'm using NodeJS and facebook. The error only happens if I receive an emoticon from the user, the bot sends the message `Service Error:A task was canceled.` only if I stop talking with the bot for a few seconds (if I keep talking to the bot, the message will be postergated, but it will come).

I'm using bot framework service to connect my bot to the facebook channel, that's why I think it might be an error at the service, on Microsoft side.

I could run more tests if needed @dandriscoll and @chrimc62

**Comment by Stevenic** [comment]
There's nothing in the SDK that returns that so would have to be a service error.

**Comment by Thegaram** [comment]
Any updates on this? I'm experiencing the same issue (V3, C#, Azure) on Facebook and Twilio. Interestingly, if I message the bot with the FB page admin, it works, but with any other user the messages do not reach the bot and on the bot admin page I see `Service Error: A task was canceled`. (On Twilio it's `BotException: POST to [botname] failed: A task was canceled. TaskCanceledException: A task was canceled`.)

**Comment by danmarshall** [comment]
Hello, are people still seeing this issue?

**Comment by ernanirst** [comment]
No, this error was on v1 with Facebook, since I've upgraded to v3, no more issues.

**Comment by Thegaram** [comment]
I experienced this on V3 as well (on multiple channels), but now it seems to be resolved.

**Comment by DrWala** [comment]
Hi, I've experienced this error on Telegram and Slack as well. It randomly occurs. What diagnostic information should I provide the next time it happens? I'm using V3.

**Comment by jfversluis** [comment]
Encountering this problem now as well with Telegram

**Comment by dandriscoll** [comment]
Hi folks, a TaskCanceledException is a timeout when connecting to your bot. We try for 15 seconds and give up and log that exception.

You can try to issue a command to your bot with the Bot Framework Emulator. If you notice the connection is slow the first time you connect, that is likely the problem.

**Comment by alokraj68** [comment]
Experincing this now in Telegram :(

**Comment by dandriscoll** [comment]
Hi @alokraj68, this error occurs when we time out trying to contact your bot.

**Comment by alokraj68** [comment]
What is the timeout in seconds? Because this happens in between
conversations.

**Comment by eanders-MS** [comment]
@alokraj68 What is your botId?

**Comment by dandriscoll** [comment]
Hi @alokraj68, the timeout is 15 seconds. This FAQ has some additional detail about keeping your bot from going to sleep: https://docs.botframework.com/en-us/technical-faq/#my-bot-is-slow-to-respond-to-the-first-message-it-receives-how-can-i-make-it-faster

**Comment by alokraj68** [comment]
@eanders-MS This is my bot page https://dev.botframework.com/bot?id=Horoscope_Bot
I don't experience any problem in facebook chats but in KIK, Telegram and skype bot restarts to beginning point in between a conversation waiting for users reply.

**Comment by alokraj68** [comment]
@dandriscoll It never takes 15 seconds. it restarts in just a sec or so. but in fb the point user left is retained even after days.

**Comment by alokraj68** [comment]
@dandriscoll I could see it time out in less than 15 seconds

13/01/2017, 18:43:13 - REQUEST
POST messages
Request URL: https://****..azurewebsites.net/api/messagesResponse code: 500Server response time: 9.65 sRequest URL path: /api/messages

**Comment by dandriscoll** [comment]
Hi @alokraj68, the error you pasted is an internal error from your bot. We tried contacting your bot, and it took 9.65s before it returned an HTTP 500 error (which indicates an internal error). Unfortunately, I don't have any more detail than that -- you would need to check your bot's internal logs to understand the failure.

Looking through our Facebook logs, however, most of the failures coming from your bot are timeouts.

**Comment by alokraj68** [comment]
@dandriscoll 
Thanks a lot for letting me know its slow.
How can i write an internal log to know where it is slowing down? can you help me out?

**Comment by alokraj68** [comment]
@dandriscoll is there anyway to increase the time out from 15 seconds?

**Comment by dandriscoll** [comment]
Hi @alokraj68, the timeout is not configurable.

**Comment by alokraj68** [comment]
Hi, i did a deep check for the error and could not find any other than some
dependency calls. But am confued why it come in kik and telegram so often
and very less in FB
