### ISSUE TITLE
Facing "There was a problem synchronizing your bot to Skype" when adding bot in skype contacts

### ISSUE THREAD

**Issue by live-abhishek** [Microsoft/BotBuilder#4550]
## Bot Info
* SDK Platform: Node.js
* SDK Version: Node.js v9.2.0
* BotBuilder Version: 3.14.0
* Active Channels: Skype, Facebook, Webchat, Direct Line, etc.
* Deployment Environment: Azure App Service connected to local development via ngrok

## Issue Description
Facing *There was a problem synchronizing your bot to Skype.* Not able to add bot to my skype contacts. The same bot works in emulator, webchat and facebook correctly. I am facing this issue on one particular instance of bot. My other older bots are working fine with skype.

## Reproduction Steps
1. Create Bot on azure.
2. Configure the skype channel.
3. Use the bot's skype link to open the link in browser, and then add the bot in skype contacts.

## Expected Behavior
I should be able to use the link to add bot to my skype contacts.

## Actual Results

![image](https://user-images.githubusercontent.com/18739197/39510917-1c1c75ac-4e09-11e8-8694-db9867fcf38a.png)

Also the date of issue is quite old. See screenshot below. Time should have today's (2nd May 2018) date.

![image](https://user-images.githubusercontent.com/18739197/39510953-44db053a-4e09-11e8-856b-20950e792fe7.png)

**Comment by live-abhishek** [comment]
@EricDahlvang  Yes, I have this problem since last week.
I have two bots which are using the same code. This one points to my local environment using ngrok. I don't think there is any issue with code itself.

**Comment by sourabhlodha** [comment]
Can you check with Test in Webchat.If it runs then you have to again sync the skype or If not then check with console regarding error.

**Comment by EricDahlvang** [comment]
@live-abhishek 

Please share your MicrosoftAppId and BotHandle so we can investigate further.

**Comment by live-abhishek** [comment]
@sourabhlodha Yes bot runs correctly in **Test in Webchat**. What do you mean by agan sync the skype.

**Comment by sourabhlodha** [comment]
@live-abhishek  Try to delete the configuration and setup again skype sometimes it also has the sync issue.

**Comment by live-abhishek** [comment]
@sourabhlodha I have already done that, multiple times to no avail.

**Comment by sourabhlodha** [comment]
@live-abhishek  Try to delete and again create again bot service that resolves your issue.

**Comment by sajal2692** [comment]
Hi. I think I'm facing a similar issue. See #4584

**Comment by sourabhlodha** [comment]
@sajal2692  When you add the bot and reply as Hi please share me the screenshot of Skype Log and output Log.

**Comment by live-abhishek** [comment]
@sajal2692 I cannot enter the bot's skype channel. If I type something in other channels, will the skype channel respond as well so as to generate any kind of log

**Comment by NickEricson** [comment]
This has been fixed. Sorry for the inconvenience and thank you for posting the issue.
