### ISSUE TITLE
Sending custom data with conversationUpdate

### ISSUE THREAD

**Issue by vamzz1** [Microsoft/BotBuilder#4551]
## Bot Info
* SDK Platform: Node.js 
* SDK Version: 3.14.1
* Active Channels: Direct Line
* Deployment Environment: Azure App Service
## Issue Description
How to send custom data in the event data of `conversationUpdate` so that different dialogs can be triggered based on the context provided by the client

**Comment by vamzz1** [comment]
If it's not possible to send custom data with `conversationUpdate` event, I think probably one could rely on the custom events that can be sent through back channel mechanism to do this and render different dialogs accordingly.

**Comment by EricDahlvang** [comment]
ConversationUpdate is sent by the Direct Line connector.  So, there's no way to add custom information to the message.  However, you can implement something like what is described here: https://github.com/Microsoft/BotBuilder/issues/4245#issuecomment-369311452  (post an event activity in client side code. Then in the bot code, respond to the event with the desired welcome message.)

**Comment by vamzz1** [comment]
Yes. @EricDahlvang Thanks for the quick response. Closing the issue.
