### ISSUE TITLE
[Direct Line API] Set Private ConversationData not working as expected - returns 500 internal server error

### ISSUE THREAD

**Issue by SatyaPavanKumar** [Microsoft/BotBuilder#4557]
## Bot Info
SDK Platform: C# .NET Bot Builder REST API
Active Channels: Direct Line

## Issue Description
I want to set private conversation data for the specified user within the context of the specified conversation on the specified channel. For this, I am using REST API to set private data to bot as mentioned in REST API Reference . But whenever we make this REST API request for Direct Line channel, it returns 500 internal server error in response. Check below details for REST request,

**Request:**
https://directline.botframework.com/v3/directline/conversations/{conversationid}/users/{userid}

MethodType: POST

**Headers:**
Authorization: Bearer <DirectLine secret key>
Content-Type: application/json

**Body:** 
Body JSON payload (raw):
{"data":{"PrivateData":"UserPrivateDataforSpecifiedChannel"}}

**Response:**
Status: 500 internal server error

What am i doing wrong?

**Comment by stevengum** [comment]
@SatyaPavanKumar the directline endpoints don't have anything to do with state, which can be found at state.botframework.com. However, users [**aren't supposed to be using the default state service found at state.botframework.com**](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-state?view=azure-bot-service-3.0) and should instead be implementing their own [**_custom state store_**](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-state?view=azure-bot-service-3.0).

Hope this helps.
