### ISSUE TITLE
Skipping fields in Form Flow by passing a sliced object.

### ISSUE THREAD

**Issue by harsh-soni** [Microsoft/BotBuilder#4558]
## Bot Info
* SDK Platform: .NET 
* SDK Version: 3.15 for both BotBuilder and BotConnector
* Active Channels: None
* Deployment Environment: Local development with Emulator

## Issue Description
Inside a form flow, bot is prompting for fields that already contains values through provided state. I tried changing FormOptions but doesn't seem to work somehow. 

## Code Example
```cs
// Object which is being provided before Form Flow.

EvalEff effort = new EvalEff()
                    {
                        COId = 1
                        testProp=3
                    };


// Creating form flow without FormOptions.PromptFieldsWithValues

                    var formDialog = new FormDialog<EvalEff>(effort, EvalEff.BuildForm, options: FormOptions.None);

                    await context.Forward(formDialog, EvalEffRecorded, messageReceived, CancellationToken.None);

//Code inside Class

[Serializable]
    public class EvalEff
    {
        public int COId { get; set; }

        public int testProp { get; set; }

        [Prompt("How many scripts?")]
        public int ScriptsEvalCount { get; set; }

        public static IForm<EvalEff> BuildForm()
        {

            return new FormBuilder<EvalEff>()
                    .Message("Submission Form Flow here")
                    .Build();
        }
    }
```

## Expected Behavior
I do not want the bot to prompt me for first 2 fields: COId and testProp.

## Actual Results
Bot is prompting for those fields, and displaying supplied values as "current choice"

Raising an issue for first time. Excuse mistakes if any.

**Comment by nodeomega** [comment]
@harsh-soni To be skipped when declaring values before the FormFlow, the fields being set up beforehand must be nullable.  

If they are not nullable, they will be queried even with values declared beforehand and even with `FormOptions.None`

Try this:

    [Serializable]
    public class EvalEff
    {
        public int? COId { get; set; }

        public int? testProp { get; set; }

        [Prompt("How many scripts?")]
        public int? ScriptsEvalCount { get; set; }

        public static IForm<EvalEff> BuildForm()
        {

            return new FormBuilder<EvalEff>()
                    .Message("Submission Form Flow here")
                    .Build();
        }
    }
