### ISSUE TITLE
Sorry, my bot code is having an issue

### ISSUE THREAD

**Issue by mohd2sh** [Microsoft/BotBuilder#4566]
## Bot Info
* SDK Platform: .Net
* SDK Version: 3.12.2
* Active Channels: Skype, Kik and Web Chat
* Deployment Environment: Azure app service, Channels Registration

## Issue Description
 I got error message "Sorry, my bot code is having an issue" in all channels and Acl Check failed issue, my web.config contains the app id and password , and when I run the app localy it is working correctly , but on the channels its failed, I search for what the error could be and I guess it is from Manage state data,I have many dialogs but the root dialog is checking the user Recipint id from msg activity and check if there a match in the database,I changed the starup dialog to the luis dialog and the app works so the error is from the Checking user info, any sulotion?

## Code Example

  private async Task MessageReceivedAsync(IDialogContext context, IAwaitable<object> result)
        {
            var a = await result as Activity;
            
            DBConnection db = new DBConnection();
            var user = db.getProfile(a.ChannelId, a.Recipient.Id);
            if (user != null)
            {
                var _reply = a.CreateReply("");
                a.ReplyToId = _reply.ReplyToId;
               
                db.updateActivty(a);
               await context.PostAsync(reply);

                context.Call<object>(new NlpDialog(), unreachable);
            }
            else
            {
                context.Call<object>(new UserDataDialog(), AfterUserData);
            }
}

## Reproduction Steps
1.
2.
3.

## Actual Results
![1](https://user-images.githubusercontent.com/22896420/39667981-01187b1a-50cb-11e8-9b59-99d921a88063.JPG)

**Comment by JasonSowers** [comment]
Without having your data connection this is going to be hard to reproduce, I was not able to reproduce with this code minus the data connection (just using a mock data object).  Try wrapping the code inside the method in a try catch and putting a breakpoint in the catch block to get the error and the stack trace.  `InternalServerError`  is the generic error we generate when there is an issue or error thrown in the code that is not handled.  So it will be hard to diagnose without your full code and all dependencies.

**Comment by mohd2sh** [comment]
I try all the solution but did not work, i cant track the error because on the localhost the project works fine, I use the app insight to check the failure request and it is in 

Remote dependency name | POST /api/usertoken/emulateOAuthCards

My App ID : b7ebc878-5126-405b-b741-c20cc6e445f4
Any Idea?

**Comment by JasonSowers** [comment]
Are you using an OAuth card? 

[Here are instructions on how to locally debug your bot on any channel]}(https://blog.botframework.com/2017/10/19/debug-channel-locally-using-ngrok/) (including KIK)  this should help you at least get more information if not solve the problem.

**Comment by mohd2sh** [comment]
Thanks, JasonSowers , The problem is solved, it was from two cause one is in cosmosDb and on from the incompatibles between nuggets I used.

**Comment by JasonSowers** [comment]
you are welcome, good luck

**Comment by DeepSelvaraj** [comment]
Hello even I am facing the same issue "Sorry, my bot code is having an issue" it is just a plain ChatBot deployed in the Azure. It works totally fine locally and when deployed it shows the above error and while debugging the exception shows "Operation returned an invalid status code 'MethodNotAllowed". What would be the exact nugget versions for this.

Thank you

**Comment by EricDahlvang** [comment]
Hi @DeepSelvaraj 

MethodNotAllowed could be related to not having a valid state store setup when using the V3 sdk: https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-state?view=azure-bot-service-3.0  

This is a closed issue.  Closed issues are not monitored, and this repository is now only for DCRs.  If you need further assistance, please open a new issue on the dotnet sdk repository: https://github.com/Microsoft/botbuilder-dotnet or https://github.com/Microsoft/BotBuilder-V3 for the V3 sdk

**Comment by DeepSelvaraj** [comment]
Hi Eric,

Thanks for your response. I have created a new issue under
botbuilder-dotnet (
https://github.com/Microsoft/botbuilder-dotnet/issues/1272).

Regards,
Deepak S
