### ISSUE TITLE
ver.3.15.2 not work for bot emulator

### ISSUE THREAD

**Issue by iangithub** [Microsoft/BotBuilder#4571]
I use the bot framework template project (https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-quickstart?view=azure-bot-service-3.0) to create a bot , if i don't upgrade Bot.Builder to ver.3.15.2 (use ver.3.8.0), the bot emulator work fine , but if i upgrade Bot.Builder to 3.15.2 , the emulator always show can't send message

Can't work environment :
1.Bot.Builder ver.3.15.2
2. .Net framework 4.6
3. bot emulator 3.5.36

work fine environment
1.Bot.Builder ver.3.8.0
2. .Net framework 4.6
3. bot emulator 3.5.36

 SDK Platform: .NET
 SDK Version: ver.3.15.2
 Deployment Environment: local development with Emulator

**Comment by eanders-MS** [comment]
Hi @iangithub Thank you for reporting this issue. It was a due to a bug in the SDK that affected emulator connections. We've put out a new version: 3.15.2.1. Please let us know if you still see the problem after updating.

**Comment by iangithub** [comment]
Hi @eanders-MS , Thank you , new version: 3.15.2.1 is work 💃
