### ISSUE TITLE
Is there a way to debug the code from the browser webchat rather than Bot emulator?

### ISSUE THREAD

**Issue by bhanuprakash857** [Microsoft/BotBuilder#4576]
@EricDahlvang 

I have few buttons in default.html, on click of that button i want to capture that value in Iframe webchat.
As event is generated in browser, I'm not able to debug the code.

Is there a way to debug the code by attaching the process or something??

Thanks,
Bhanu

**Comment by EricDahlvang** [comment]
Yes, you can debug any channel locally (including webchat).  This blog post describes how to change the messaging endpoint, and debug a channel: https://blog.botframework.com/2017/10/19/debug-channel-locally-using-ngrok/

Instructions for setting up WebChat on a web page can be found here: https://github.com/Microsoft/BotFramework-WebChat#easy-in-your-non-react-website-run-web-chat-inline

**Comment by bhanuprakash857** [comment]
@EricDahlvang 
Thanks for the information.I'm facing problem in debugging as explained below.

1. open the ngrok and ran the below command
ngrok http 3980 -host-header="localhost:3980"
![image](https://user-images.githubusercontent.com/12428545/39747460-f80a6216-52ca-11e8-8de9-91a558fcdff7.png)
2. Copy the url from cmd https://b39c8d0d.ngrok.io and updated in bot settings endpoint(https://b39c8d0d.ngrok.io/api/messages)
3. When i browse the url I'm getting below error
![image](https://user-images.githubusercontent.com/12428545/39747638-72095234-52cb-11e8-8659-9871e38e93e4.png)

**Comment by bhanuprakash857** [comment]
I'm able to debug the code. Thank you
