### ISSUE TITLE
Getting Directline GET /api/conversations/{conversationId}/messages to return "to"  

### ISSUE THREAD

**Issue by jakobpn** [Microsoft/BotBuilder#458]
I'm creating a bot prototype using the Directline API and a custom version of the web chat control. The message object returned by the GET /api/conversations/{conversationId}/messages API has a "from" property, but there is no "to" property. 

It would be awesome to have "to" included so thata custom chat control could behave differently based on who the message is directed to.

**Comment by dandriscoll** [comment]
Yes, that would be neat, although in every chat service we've seen, messages sent to a group chat are sent to the conversation (or the "room," depending on how it's modeled) and not an individual user. For example, a Slack message is posted to the channel. An email message is sent to a list of recipients, not just the user who sent the last mail.

One thing that is useful would be an equivalent of the "replyToMessageId" field so replies can be nested/threaded. I'll definitely look at that for the future. Thanks!
