### ISSUE TITLE
Sending a Reply with text and buttons

### ISSUE THREAD

**Issue by odannyc** [Microsoft/BotBuilder#4581]
## Bot Info
* SDK Platform: .NET
* SDK Version: v3.15
* Active Channels: Facebook Messenger
* Deployment Environment: local development with Emulator

## Issue Description
Im trying to create a message that contains text + buttons.
Roughly, this is what im aiming for:
![screen shot 2018-05-08 at 10 17 26 am](https://user-images.githubusercontent.com/12864641/39772076-0ae94694-52a9-11e8-94fa-cc1d96696ed3.png)

Unfortunately, you can't add buttons directly to a reply.
So the only solution would be to use adaptive cards with text and a button and add that as an attachment to a reply. Is this right?
I tried using a `BasicCard` but there seems to be no support for that and the emulator doesnt render it.
Ideally, I would like to avoid using AdaptiveCards, can anyone point me in the right direction?
Thanks

**Comment by JasonSowers** [comment]
You can use [Rich Cards](https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/cards-RichCards) (a hero card is probably your best bet), or [suggested actions](https://stackoverflow.com/questions/46138575/quick-replies-in-microsoft-bot-framework-web-chat-platform) to achieve this.  Since you are using facebook, you also have the option to use quick replies.

**Comment by odannyc** [comment]
@JasonSowers 
Thanks. But if I use a HeroCard with just text and a button, will that render correctly on messenger (like the image I posted)?

If not, will the only option be to use AdaptiveCards?

**Comment by JasonSowers** [comment]
This code 
```cs
        private async Task MessageReceivedAsync(IDialogContext context, IAwaitable<object> result)
        {
            var message = await result as Activity;
            message = message.CreateReply();

            var heroCard = new HeroCard
            {
                Text = "I am some text",
                Buttons = new List<CardAction> {new CardAction(ActionTypes.PostBack, "I am a button", value: "things")}
            };
            message.Attachments.Add(heroCard.ToAttachment());

            try
            {
                await context.PostAsync(message);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
        }
```
Will look like this 
![image](https://user-images.githubusercontent.com/6301037/39845783-aff06420-53ac-11e8-8db9-d7184b0c79c7.png)
