### ISSUE TITLE
New QnA is not working in Azure. No response from 'Test in web chat'.

### ISSUE THREAD

**Issue by imdineshgrewal** [Microsoft/BotBuilder#4583]
New QnA is not working in Azure. I have done following steps:
a. Created a QnA cognitive service in Azure.
b. With the Azure service, i have created a KB in new QnA portal. Uploaded QnA content.
c. Created a bot using 'Bot services in Azure'. configured it using following keys in the app setting : 
  1. QnAKnowledgebaseId
  2. QnAAuthKey
  3. QnAEndpointHostName
  4. QnASubscriptionKey

Please assist me if i need to config something else in the Azure bot app setting.?
Regards,

**Comment by stevengum97** [comment]
Which language are you using, and which version of the SDK are you using?

**Comment by imdineshgrewal** [comment]
@stevengum97 I'm not using direct C# configuration in the Azure portal. Old QnA is still working fine there but when I'm configuring new QnA using the following keys, it is not working.
QnAKnowledgebaseId
QnAAuthKey
QnAEndpointHostName
QnASubscriptionKey

**Comment by imdineshgrewal** [comment]
@stevengum97 Hi, QnA Maker(new) is working fine with the Azure bot's configurations now! Only following Keys are needed:
QnAKnowledgebaseId
QnAAuthKey
QnAEndpointHostName

Thanks

**Comment by vanucci** [comment]
@imdineshgrewal Im struggling to fint he QnAEnpointHostName

Where can i find it ?

**Comment by EricDahlvang** [comment]
@vanucci  Go to the Settings tab of the knowledge base, and scroll down to the Deployment details:

![image](https://user-images.githubusercontent.com/11055362/43098994-98f10b72-8e75-11e8-9573-5f82f1876f27.png)
