### ISSUE TITLE
How to create a CardAction webhook?

### ISSUE THREAD

**Issue by blakeandrewwood** [Microsoft/BotBuilder#4587]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.14.1.1
* Active Channels: Emulator
* Deployment Environment: Local

## Issue Description

I'm curious if there is a way to create webhook buttons similar to Facebook webhook postback buttons. I want to send some JSON as the button payload to the bot and handle it differently from an ActivityType.Message.

Is there currently a way to do this? The only thing I see close to this is the AcitvityType.Invoke which seems to only be supported by MS Team.

**Comment by EricDahlvang** [comment]
I'm not sure if this is the same thing as a Facebook postback webhook, but you could use an Adaptive Card attachment with Adaptive Submit Action containing .json in the Data Property:

```cs
var reply = temp.CreateReply();

reply.Attachments = new List<Attachment>();
AdaptiveCard card = new AdaptiveCard();
card.Body.Add(new AdaptiveTextBlock()
{
    Text = "Click 1 or 2",
    Size = AdaptiveTextSize.Large,
    Weight = AdaptiveTextWeight.Bolder
});
card.Actions.Add(new AdaptiveSubmitAction()
{
    Title = "Submit 1",
    Data = JsonConvert.SerializeObject(new
    {
        @customField = "User Submitted 1",
        @customProperty = new {
            @field1 = 2,
            @field2 = "some text"
        }
    })
});
card.Actions.Add(new AdaptiveSubmitAction()
{
    Title = "Submit 2",
    Data = JsonConvert.SerializeObject(new
    {
        @customField = "User Submitted 2",
        @customProperty = new
        {
            @field1 = 2,
            @field2 = "some text"
        }
    })
});
Attachment cardAttachment = new Attachment()
{
    ContentType = AdaptiveCard.ContentType,
    Content = card
};
reply.Attachments.Add(cardAttachment);

await context.PostAsync(reply);
```

When a button is clicked in Messenger, the json will come in the .ChannelData property (also in the .Text property):

![image](https://user-images.githubusercontent.com/11055362/39900029-0a031da0-5474-11e8-9e4e-fc9a48750222.png)
