### ISSUE TITLE
Getting Slack authorization token

### ISSUE THREAD

**Issue by srogovtsev** [Microsoft/BotBuilder#459]
I need my bot to be able to access Slack API (to read user information and so on). For that I have to provide an access token - which is usually generated during "Add to Slack" process, and, I suppose, is stored somewhere in Bot Connector data, so that Bot Connector can seamlessly integrate bot and Slack.

Is there any way of getting this token?

**Comment by craigjensen** [comment]
You can't get access to the token that's used by the BotFramework but you can create your own token at https://api.slack.com/docs/oauth-test-tokens.

What specific information from Slack are you wanting to access?

**Comment by srogovtsev** [comment]
> You can't get access to the token that's used by the BotFramework but you can create your own token at https://api.slack.com/docs/oauth-test-tokens.

That will be a test token, not a production one.

> What specific information from Slack are you wanting to access?

I want to get a list of all the users, with emails, full names and Slack handles. I need it to remap some external information (e.g. Jira item activity) from external users (defined by emails) to Slack users, so that instead of "blah@com.con fixed a bug" I could post "@blah fixed a bug".

**Comment by craigjensen** [comment]
You should get their Id and slack handle in the Participants list of the message.  We currently don't expose a way to get additional user information from Slack

**Comment by srogovtsev** [comment]
Okay, and can that be done another way around - if I get the token from Slack myself, can I pass it to Bot Connector somehow?

**Comment by craigjensen** [comment]
No, but we are looking into ways of passing extended Slack data in the next release.

**Comment by v-thgratMSGit** [comment]
Closing this issue. Thanks!

**Comment by craigjensen** [comment]
We are working on an update that will send the token as part of the ChannelData on every message. You can then extract the token and make your own Slack RTM Api calls. The update should be published soon - hopefully in the next couple days.

**Comment by craigjensen** [comment]
Update is deployed in production.  Please give it a try and reopen if needed.

**Comment by dandriscoll** [comment]
Hi @srogovtsev, we have this available and working now. If you have any trouble using this feature, please open anew issue.

**Comment by neotheicebird** [comment]
Hi. I am able to get the slack token with every message from botframework, but this creates the limitation that the bot cannot start the very first conversation, (say the bot wants to thank a user for installing the app). How can I achieve it?
