### ISSUE TITLE
[Question] Can I fetch all users of a MS Teams organization?

### ISSUE THREAD

**Issue by nguyendn** [Microsoft/BotBuilder#4592]
Can I fetch all users of an MS Teams organization? and so that I can broadcast conversation to all users? 
Edit: if I know the email of the user which use MS Teams, does it help?

**Comment by EricDahlvang** [comment]
This documentation page provides information on how to query the team roster: https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-context#fetching-the-team-roster

**Comment by EricDahlvang** [comment]
This would involve interacting with the MS Teams API, and is not specifically related to the Bot Framework. 
 This functionality is not built into the Bot Framework directly, but there might be a way to use the graph api and get a list of all teams members: I don't know.  

Please ask this question on StackOverflow: https://stackoverflow.com/questions
