### ISSUE TITLE
[Skype For Business] I need to have form in "Skype for business" while using Microsoft bot framework

### ISSUE THREAD

**Issue by amitkadu** [Microsoft/BotBuilder#4594]
## Issue Description
I want to make single code compatible with various channels.
Is there any way to render adaptive card on different channel by making channel specific changes to it.

**Comment by amitkadu** [comment]
I will use Activity.ChannelId for Skype for Business, but how to create form in SFB??

**Comment by JasonSowers** [comment]
If you want to implement a visual form, there is no built-in solution that will work with SFB at this time.  You do have the option of using [FormFlow](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-formflow?view=azure-bot-service-3.0), but I am not sure if this would suit your needs.

**Comment by amitkadu** [comment]
If forms not supported, every time I have to go and get user input for each and every field, from User Experience prospective its not good.
Again same issue for drop down and radio buttons where choices I will put from configuration file.
And for sensitive information, if I want to mark * then what?

**Comment by JasonSowers** [comment]
I do not know of any options in the Skype for Business channel for what you want to do.  For what you are trying to do, generally Adaptive cards are used, but Skype for Business does not support adaptive cards yet.

**Comment by JasonSowers** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
