### ISSUE TITLE
[FB Messenger] Bot chat taking long time to response back to Facebook Messenger.

### ISSUE THREAD

**Issue by praveens3190** [Microsoft/BotBuilder#4595]
## Bot Info
* SDK Platform: 
* SDK Version: 
* Active Channels: 
* Deployment Environment: 

## Issue Description
Based on some activity message, I want to send a proactive message from Bot side to a specific user on its contact list using any of the supported messaging channels like FBMessenger/Webchat. WebChat will get quick response from BOT. But for facebook it is taking too much to time to get the response from Bot and initial communication from facebook will starts quickly unfortunately once communication session was end and customer starts new communication from same messenger then Bot is not sending response back to user It is taking long time to respond back.   

## Reproduction Steps
1.
2.
3.

**Comment by stevkan** [comment]
Can you tell me which SDK and version you are using?

**Comment by praveens3190** [comment]
I resolved the issue by gave context.Done(this) at dialog. so for second time the response comes quickly.
