### ISSUE TITLE
[Samples] Unused dialog left in AlarmBot C# sample

### ISSUE THREAD

**Issue by BrainCrumbz** [Microsoft/BotBuilder#4596]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.13.0.3
* Active Channels: Not applicable
* Deployment Environment: local development with Emulator

## Issue Description
In [CSharp/Samples/AlarmBot project](https://github.com/Microsoft/BotBuilder/tree/31fbc42d23fbd4701fef38d5d6374c7902be2f22/CSharp/Samples/AlarmBot), both in * 	README.md* and in *AlarmLuisDialog.cs* code comments, `AlarmLuisDialog` is described as the root dialog of that sample. 

But searching in code, there's actually no reference to such class. Instead there's another dialog, `AlarmDispatchDialog` whose comment also says that's the root dialog. That dialog is actually referenced in code, being registered in `AlarmModule`.

## Code Example

Dialog registration: https://github.com/Microsoft/BotBuilder/blob/31fbc42d23fbd4701fef38d5d6374c7902be2f22/CSharp/Samples/AlarmBot/Models/AlarmModule.cs#L27

## Reproduction Steps

Not applicable.

## Expected Behavior

Readme should mention `AlarmDispatchDialog`. *AlarmLuisDialog.cs* should not exist or its role should be properly explained.

## Actual Results

Readme ignores `AlarmDispatchDialog`. Module registration ignores `AlarmLuisDialog`.

**Comment by EricDahlvang** [comment]
This looks like an oversight (not updating the readme) introduced here: https://github.com/Microsoft/BotBuilder/commit/db5bc1b27cae149ed1fe67820b2e2f7c620aa4d3#diff-35238b01be3de4e1e950b4bfee4feac7

Do you care to submit a PR to fix the Readme?  (I wouldn't remove the AlarmLuisDialog though, since it is a good example of how this sample could use a LuisDialog instead of a DispatchDialog.  Maybe the readme should mention this as well)

**Comment by BrainCrumbz** [comment]
Yes, why not. So, before moving on with PR, are the next guidelines correct?

1. Update AlarmModule with a (commented out) line to register AlarmLuisDialog instead of AlarmDispatchDialog
1. Add a comment on AlarmLuisDialog describing it as a LuisDialog example usage, and that either one of the two should be registered
1. Add a comment on AlarmDispatchDialog describing it as a DispatchDialog example usage, and that either one of the two should be registered
1. Mention both alternatives in readme

**Comment by EricDahlvang** [comment]
@BrainCrumbz Those all seem like good changes to me.

**Comment by BrainCrumbz** [comment]
Please have a look at it, if it fits this project comment/doc guidelines, etc.
