### ISSUE TITLE
[QnA Maker, Question] Problem with new QnA bot

### ISSUE THREAD

**Issue by bettina86** [Microsoft/BotBuilder#4597]
I created a new web app bot with question and answer from the azure portal and i created a services qna for this web app. i have a qnamaker created , but is the old version, the preview.
In the settings application it requires auth key what is in the new qnamaker.
How do I run the old version, at the moment I do not want to migrate the old qnamaker?

**Comment by stevengum97** [comment]
@bettina86 which SDK and version of the SDK are you using?

**Comment by bettina86** [comment]
I'm using the platform azure and his editor online.

**Comment by stevengum97** [comment]
@bettina86 the QnAMaker Dialog will default to the preview (v3) QnA Maker API. There are no major differences in using the v3 BotBuilder SDKs with QnA Maker. Under the App Service Settings tab for your web app bot, you simply need to provide it with two values for these two keys:

- `QnAKnowledgebaseId`
- `QnAAuthKey`

![capture](https://user-images.githubusercontent.com/14935595/40993313-1cd18d10-68ae-11e8-9a4e-9513fa1440f3.PNG)
