### ISSUE TITLE
[Question] Maintenance of table storage holding the bot state data

### ISSUE THREAD

**Issue by asfyra** [Microsoft/BotBuilder#4598]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.15.2.2
* Active Channels:  Direct Line
* Deployment Environment: Azure Bot Service, Azure App Service, local development with Emulator

## Issue Description
I use azure table storage for my bot' s state. 
I  wanted to ask if this table will be growing forever, or it's been taken care of the bot framework and cleaned up as needed.
Do table rows get deleted on conversation end for example ? 
For how long will the state data live there?
Should I build a mechanism to keep the table in shape ? 

Thanks in advance 
    Alex

**Comment by JasonSowers** [comment]
There is nothing natively built in to do this for you, this will be a situation where you would have to roll your own solution.

**Comment by asfyra** [comment]
Thank you for your reply.
Alex
