### ISSUE TITLE
FormFlow quit command seems to fail

### ISSUE THREAD

**Issue by IntranetFactory** [Microsoft/BotBuilder#46]
I'm testing the "AnnotatedSandwichBot". It works as expected - with the exception of the quit command.

After I enter `quit` I though that the "session" ends and new starts. But what ever I enter after `quit` is only answered with an empty message from the bot.

Is `quit` broken or did I misunderstand the purpose of that command?

![image](https://cloud.githubusercontent.com/assets/7462342/14239958/d05a3af0-fa0e-11e5-80ec-88d51f404a20.png)

**Comment by willportnoy** [comment]
Quit from the FormDialog<T> will return a cancelled IAwaitable<T> to the caller of that FormDialog<T>, so it doesn't really send any messages by itself.  In your calling dialog, you can send a message if the form dialog was cancelled with "quit".
