### ISSUE TITLE
async mathod lacks error

### ISSUE THREAD

**Issue by kaki104** [Microsoft/BotBuilder#460]
I create a sample using the AnnotatedSandwichBot
The error occured when using async in BuildForm
How can I do?

error
This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.

source
            return new FormBuilder<KakiSandwichOrder>()
                .Message("안녕하세요 카키 샌드위치 주문 봇입니다. help 혹은 ? 를 입력하시면 도움말을 보실 수 있습니다.")
                .Field(nameof(Menu))
                .Field(nameof(Bread))
                .Field(nameof(Addition))
                .Field(nameof(Vegetable))
                .Message("아래의 야채들을 선택 하셨습니다.{Vegetable}")
                .Field(nameof(Source))
                .Field(nameof(Set))
                .Field(nameof(OrderCount))
                .Field(new FieldReflector<KakiSandwichOrder>(nameof(Specials))
                    .SetType(null)
                    .SetActive((state) => state.Menu == KakiMenuOptions.Menu30cm)
                    .SetDefine(**async (state, field) =>
                    {
                        field
                            .AddDescription("cookie", "Free cookie")
                            .AddTerms("cookie", "cookie", "free cookie")
                            .AddDescription("drink", "Free large drink")
                            .AddTerms("drink", "drink", "free drink");
                        return true;
                    }))
                .Confirm(async (state) =>
                {
                    var cost = 0.0;
                    switch (state.Menu)
                    {
                        case KakiMenuOptions.Menu15cm: cost = 5000 * state.OrderCount; break;
                        case KakiMenuOptions.Menu30cm: cost = 6500 * state.OrderCount; break;
                        case KakiMenuOptions.찹샐러드: cost = 7500 * state.OrderCount; break;
                    }
                    return new PromptAttribute($"고객님이 주문하신 총 금액은 {cost:D}\\  입니다. 금액 확인 부탁드립니다.");
                }**)
                .Confirm("Do you want to order your?")
                .AddRemainingFields()
                .Message("Thanks for ordering a sandwich!")
                .OnCompletionAsync(processOrder)
                .Build();

**Comment by willportnoy** [comment]
The warning is safe to ignore.  By using async, you guarantee that any thrown exceptions are wrapped into the Task.  There are alternate ways you can write that method without async, for example:

try
{
your code
return Task.FromResult(result);
}
catch (Exception error)
{
return Task.FromException<ResultType>(error);
}

**Comment by kaki104** [comment]
I found the code is entered incorrectly.
{cost:D} -> {cost:C0}
And, it does not display a warning message.
#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously

Thank you
