### ISSUE TITLE
[Feature Request] Specify the tenant id for multi tenant bot auth

### ISSUE THREAD

**Issue by weshackett** [Microsoft/BotBuilder#4600]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.15.2
* Active Channels: MS Teams
* Deployment Environment:  Azure App Service, local development with Emulator

## Issue Description
For a bot being used in MS Teams and connecting to MS Graph using 'common' for a guest user means the auth returns a token for the home tenant rather than the tenant for the Team the user is in, is there any way to set the tenant id (as a multiple tenant scenario will be quite common for Teams)

## Code Example
Code from the sample AADv1 can be used within Teams

## Reproduction Steps
1. Use the AAD v1 sample
2. Create MS Teams app
3. Add Guest user to Teams
4. Login with that guest user
5. You'll see a token only valid for the guests home tenant not the one for the MS Team they are guest within

## Expected Behavior
Be able to specify tenant id  use

**Comment by Jeffders** [comment]
Hi Jason,
Right now you cannot dynamically specify the tenant or other login parameters. However this is near the top of the list of further improvements we want to do for OAuthCards.

**Comment by JasonSowers** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
