### ISSUE TITLE
How to make an interactive call bot using Bot Framework?

### ISSUE THREAD

**Issue by neetgupta7** [Microsoft/BotBuilder#4604]
## Bot Info
* SDK Platform: .NET
* SDK Version: Latest
* Active Channels: Thats the question
* Deployment Environment:  Azure App Service

## Issue Description
I want to make a calling bot, where the user can call, user's speech can be converted to text, analysed by an NLP and then bot processes this information and prepare a text response and post to user after converting into speech. Am not sure how to accomplish this, skype call project works more like an IVR and does not appear it can handle normal conversation. Please help.

**Comment by JasonSowers** [comment]
Take a look at [Bing Speech API](https://azure.microsoft.com/en-us/services/cognitive-services/speech/)  and [LUIS](https://www.luis.ai/) you can accomplish what you are asking about with this services.
