### ISSUE TITLE
[Node.js, Cortana] 500 error when using node js to send data to cortana on windows 10 (botframework-emulator works)

### ISSUE THREAD

**Issue by jimmy-tfp** [Microsoft/BotBuilder#4606]
## Bot Info
* SDK Platform: Node
* SDK Version: 3.14.1
* Active Channels: Cortana Windows 10
* Deployment Environment: Azure Bot Service

## Issue Description
my bot calls an api for answers to questions and returns the answer with session.send().
when running in sims it works fine.
when running on Cortana from windows 10 I get an error

## Code Example
request({
            url: url,
            method: 'POST',
            json: args
        }, function (err, httpResponse, body) {
            session.send("%s", JSON.stringify(body));
            session.say(body.ssml);
        });

## Reproduction Steps
run it
## Expected Behavior
200 ok message

## Actual Results

on the console

May 14 08:54:50am error Error: POST to 'https://CortanaBFChannelWestUS.azurewebsites.net/v3/conversations/25e2ec3d-314e-41f5-821f-3241d161aa07/activities/EiJdLUUWkpF' failed: [500] Internal Server Error at Request._callback (D:\home\site\wwwroot ode_modules\botbuilder\lib\bots\ChatConnector.js:559:46) at Request.self.callback (D:\home\site\wwwroot ode_modules\request\request.js:186:22) at emitTwo (events.js:106:13) at Request.emit (events.js:191:7) at Request.<anonymous> (D:\home\site\wwwroot ode_modules\request\request.js:1163:10) at emitOne (events.js:96:13) at Request.emit (events.js:188:7) at IncomingMessage.<anonymous> (D:\home\site\wwwroot ode_modules\request\request.js:1085:12) at IncomingMessage.g (events.js:291:16) at emitNone (events.js:91:20)

**Comment by nodeomega** [comment]
When running in the simulator, how long is it before the bot responds?  Is it longer than 10 seconds?  Or is the API returning the data sooner than that interval usually?

**Comment by nodeomega** [comment]
Closing this issue as there has been no reply for an extended period.  If this issue persists, feel free to open a new support request.  Thank you.
