### ISSUE TITLE
Debugging from console

### ISSUE THREAD

**Issue by sixpi** [Microsoft/BotBuilder#461]
In the getting started page for C#, there is a code snippet for how to debug a dialog from the console, which references the non-existent interface `IDialogTask`. There appears to be a file named `IDialogTask.cs`, but it contains the interface `IDialogStack`.

**Comment by willportnoy** [comment]
I found the reference at http://docs.botframework.com/sdkreference/csharp/#debugging - will see about getting it fixed.  @Andrea-Orimoto the docs from https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Documentation/Overview.cs include https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Tests/FormTest/Program.cs but the published version doesn't match that source - can we update it?

**Comment by Andrea-Orimoto** [comment]
This has been fixed [http://docs.botframework.com/sdkreference/csharp/#debugging](http://docs.botframework.com/sdkreference/csharp/#debugging)

Thanks a lot for bringing this to our attention!
Andrea
