### ISSUE TITLE
[Node.js, Slack] What Slack events are supported?

### ISSUE THREAD

**Issue by bohdanbirdie** [Microsoft/BotBuilder#4611]
## Bot Info
* SDK Platform: Node.js
* SDK Version: `"botbuilder": "^3.15.0"`
* Active Channels: Slack, Telegram
* Deployment Environment: Local env, messages received via ngrok tunnel 
  `(slack -> azure -> ngrok -> local)`
* Storage: mongoDB

## Issue Description
Can't find any info about supported Slack events, the only thing that I'm able to receive is a direct message and a message on the channel.

## Expected Behavior
Being able to receive at least few of these events:
- `team_join`
- `member_joined_channel`
- `member_left_channel`

## Actual Results
Nothing happens when those specific events triggered, bot triggered only when the message was sent.

## Source code
I found a great article on Medium on how to make a bot with Nest.js https://medium.com/@mathieupicciolli/lets-make-a-chatbot-microsoft-bot-framework-nest-js-e27b25280934
So my code at this point is pretty much the same.

**Comment by fanidamj** [comment]
The Slack channel handles the following Slack message types and sends them to bots:
•	Message sent as _MessageActivity_
•	Bot_added sent as _InstallationUpdateActivity_
•	Member_joined_channel, Member_left_channel send at _ConversationUpdateActivity_
•	(Old worker role only) User_typing sent as _TypingActivity_
Hope this helps!!
