### ISSUE TITLE
Bot reply significantly slow after App Pool recycle

### ISSUE THREAD

**Issue by ahqiu89** [Microsoft/BotBuilder#4612]
Hi MS team, 

I am experiencing massive delay for the 1st response from Bot whenever after App Pool is recycled.

Normal bot reply: 1-3 seconds.
1st reply after App Pool recycled : 10 seconds.

This is only observed for the first reply after App Pool recycled, and subsequent reply is as normal.

Please advise any best practice or strategy to be implemented so that the bot could function 24/7 without any delay, even after App Pool recycle.

Appreciate your prompt help on this.

**Bot Channel:** Facebook Messenger

Thanks,

**Comment by EricDahlvang** [comment]
App Pool recycling is a standard IIS startup issue, and standard strategies for handling it will work for bots as well (since they are just websites).  reference: https://serverfault.com/questions/333907/what-should-i-do-to-make-sure-that-iis-does-not-recycle-my-application
