### ISSUE TITLE
[.Net, Email] Adding Email Channel to Microsoft Bot Framework Shows Timeout errors

### ISSUE THREAD

**Issue by aramkoukia** [Microsoft/BotBuilder#4615]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.15.2.2
* Active Channels: Skype, Slack, Direct Line, (Email channel has issues)
* Deployment Environment: Azure Bot Service

## Issue Description
I have a Chat Bot and already have a Slack channel and works fine. When I try to Save an Email I am getting the following error: 
https://i.stack.imgur.com/62sDE.png
`Unable to save. The Operation did not complete within the specified timeout.`
Based on the documentations I am using an O365 email

## Code Example
NA

## Expected Behavior
Should be able to add Email Channel

## Actual Results
Not able to add Email channel

Also posted the issue here:
[https://stackoverflow.com/questions/50342655/adding-email-channel-to-microsoft-bot-framework-shows-timeout-errors](https://stackoverflow.com/questions/50342655/adding-email-channel-to-microsoft-bot-framework-shows-timeout-errors)

**Comment by JasonSowers** [comment]
FYI our expert on the email channel is out today so most likely we will have to look at this tomorrow.

**Comment by craigjensen** [comment]
Did you get this working?  I see that the bot in now registered to an outlook.com email address which is OK for testing but should not be used in production due to various limitations.  We only O365 email accounts in production

**Comment by aramkoukia** [comment]
@craigjensen No, still same error when I use my Work's O365 email account I get the above error when I try to save, but using a regular personal outlook.com account works fine...

**Comment by craigjensen** [comment]
Have you tried running the [connectivity tool](https://testconnectivity.microsoft.com/) against the account in question and see if it provides any insight into what the problem might be?  Start with the Exchange Web Services - Service Account Access (Developers) test and see if it comes back with any errors/warnings.

**Comment by aramkoukia** [comment]
* I see a couple errors:

**First Error:**
The Microsoft Connectivity Analyzer is attempting to retrieve an XML Autodiscover response from URL https://www.lgm.ca/Autodiscover/Autodiscover.xml for user aram.koukia@lgm.ca.
--
  | The Microsoft Connectivity Analyzer failed to obtain an Autodiscover XML response.
  | Additional Details A Web exception occurred because an HTTP 404 - NotFound response was received from Unknown.HTTP Response Headers:Transfer-Encoding: chunkedConnection: keep-alivePragma: no-cacheVary: CookieLink: <https://www.lgm.ca/wp-json/>; rel="https://api.w.org/"Cache-Control: no-cache, must-revalidate, max-age=0Content-Type: text/html; charset=UTF-8Date: Wed, 23 May 2018 17:09:36 GMTExpires: Wed, 11 Jan 1984 05:00:00 GMTSet-Cookie: PHPSESSID=b08elchc4q5ct7occ2br3kn5n5; path=/Server: nginxX-Powered-By: PHP/5.6.36,PleskLinElapsed Time: 1738 ms. |   | Additional Details |   | A Web exception occurred because an HTTP 404 - NotFound response was received from Unknown.HTTP Response Headers:Transfer-Encoding: chunkedConnection: keep-alivePragma: no-cacheVary: CookieLink: <https://www.lgm.ca/wp-json/>; rel="https://api.w.org/"Cache-Control: no-cache, must-revalidate, max-age=0Content-Type: text/html; charset=UTF-8Date: Wed, 23 May 2018 17:09:36 GMTExpires: Wed, 11 Jan 1984 05:00:00 GMTSet-Cookie: PHPSESSID=b08elchc4q5ct7occ2br3kn5n5; path=/Server: nginxX-Powered-By: PHP/5.6.36,PleskLinElapsed Time: 1738 ms.
  | Additional Details
  | A Web exception occurred because an HTTP 404 - NotFound response was received from Unknown.HTTP Response Headers:Transfer-Encoding: chunkedConnection: keep-alivePragma: no-cacheVary: CookieLink: <https://www.lgm.ca/wp-json/>; rel="https://api.w.org/"Cache-Control: no-cache, must-revalidate, max-age=0Content-Type: text/html; charset=UTF-8Date: Wed, 23 May 2018 17:09:36 GMTExpires: Wed, 11 Jan 1984 05:00:00 GMTSet-Cookie: PHPSESSID=b08elchc4q5ct7occ2br3kn5n5; path=/Server: nginxX-Powered-By: PHP/5.6.36,PleskLinElapsed Time: 1738 ms.


**Second Error:**

Attempting to resolve the host name autodiscover.lgm.ca in DNS.
--
  | The host name couldn't be resolved.
  | Tell me more about this issue and how to resolve it
  | Additional Details Host autodiscover.lgm.ca couldn't be resolved in DNS InfoDomainNonexistent.Elapsed Time: 307 ms. |   | Additional Details |   | Host autodiscover.lgm.ca couldn't be resolved in DNS InfoDomainNonexistent.Elapsed Time: 307 ms.
  | Additional Details
  | Host autodiscover.lgm.ca couldn't be resolved in DNS InfoDomainNonexistent.Elapsed Time: 307 ms.


Not sure how I can fix this.

**Comment by JasonSowers** [comment]
@aramkoukia were you able to resolve these issues?

**Comment by JasonSowers** [comment]
Closing this issue as there is nothing we can do on our end to fix this.

**Comment by aramkoukia** [comment]
Looks like the Email channel does not work with Federated emails (which I think most companies have Federated AD) and only works with just O365 emails and outlook.com.
Not too many companies were setup in the cloud from the get go, and will have Federated/Migrated email.

**Comment by EricDahlvang** [comment]
@aramkoukia You are correct.  O365 emails are currently the only email account types supported.  The email channel configuration code performs auto discover using EWS apis.  It is similar to this: https://github.com/EricDahlvang/ExchangeConnectivityTest
