### ISSUE TITLE
Integrate Speech to Text to .Net Core 2 bot?

### ISSUE THREAD

**Issue by parvathysarat** [Microsoft/BotBuilder#4617]
* SDK Platform:  .NET Core 2
* Deployment Environment: Azure Bot Service

I have a simple bot that takes text input that I'd like to add speech to text capability to. I've been trying to find any sample bots where this has been done but could find no help.
I could find documentation on Cognitive Services but nothing as to how exactly it can be integrated to a bot (.Net Core 2).
Any help is much appreciated. Thanks!

**Comment by parvathysarat** [comment]
Yes, I'm trying to create a V4 bot that supports speech to text. Being new to C# I've been relying on the Sample docs to build a basic bot, but I have no idea where to add the API call from the docs.

**Comment by JasonSowers** [comment]
Which sample are you starting with, I can take a look and try to provide some direction.

**Comment by JasonSowers** [comment]
The speech to text sample you are looking at is a v3 sample.  Try looking at [this one]( https://github.com/Azure-Samples/Cognitive-Speech-TTS/tree/master/Samples-Http/NETCore)  It's specifically for dotnet core.  As far as where you would make the call, it would be in this area of the sample you linked

```cs
using Microsoft.Bot.Builder;
using Microsoft.Bot.Schema;
using System.Threading.Tasks;

namespace Microsoft.Bot.Samples
{
    public class HelloBot : IBot
    {
        public async Task OnTurn(ITurnContext context)
        {
            if (context.Activity.Type is ActivityTypes.Message)
            {
                //send this text in your api call ans the text. 
                var text = context.Activity.Text;
                //make the call to the bing speech API

                //send something back to the user  
                await context.SendActivity($"Hello world.");
            }
        }
    }
}
```

**Comment by parvathysarat** [comment]
This worked!
Thanks a lot :)

**Comment by SanaWaseem** [comment]
//make the call to the bing speech API here 
To convert text to speech ? Will that send the response in spoken form
