### ISSUE TITLE
Future of Bot Framework v4.0

### ISSUE THREAD

**Issue by thomasryck** [Microsoft/BotBuilder#4620]
I had a question regarding the future of the framework. I saw that there is a nuget package to access V3 functionalities in the V4 framework. Is this package has been developed to ensure continuality and the V3 functionalities will disappear in the future. Or is the package has been developed because the framework will offer in the future the V3 functionalities and the V4 functionalities ?

**Comment by stevengum97** [comment]
@thomasryck, there are plans to allow users to plugin their v3 code into v4 bots.  Does this help?

**Comment by stevengum97** [comment]
Also, for questions like these, you would be better served by going to the v4 repo itself, [botbuilder-dotnet](https://github.com/Microsoft/botbuilder-dotnet/) and asking your question there.
