### ISSUE TITLE
Custom Bot performance in Microsoft Teams after a periods of inactivity

### ISSUE THREAD

**Issue by prejeanb** [Microsoft/BotBuilder#4622]
## Bot Info
* SDK Platform:  .NET
* SDK Version: 3.15.0
* Active Channels:  MS Teams, Web Chat
* Deployment Environment: Azure App Service

## Issue Description
Our Bot that is running in MS Teams 1:1 and Web Chat is often slow to respond, times out, or never responds after a period inactivity
## Code Example
N/A - there isn't specific code to show here, it is throughout the entire bot

## Reproduction Steps
1. Engage in a MS Teams 1:1 conversation with a custom bot
2. Allow for a period of time to expire in the chat
3. Pose a question to the custom bot in the conversation
4. Following steps 1-3 in a Web Chat 

## Expected Behavior
A bot running in the MS Teams channel will have a similar level of performance / responsiveness as other Channels

## Actual Results
The bot will often be slow to respond, time out, or never respond to the question in MS Teams.  Web Chat does not exhibit this behavior

**Comment by EricDahlvang** [comment]
Please provide your Microsoft App Id and Bot Handle so we can investigate further.

**Comment by mitch726** [comment]
We started seeing this 2 days ago as well and it consistently repros in all of our environments.
cora_rbsa - 32347725-bed3-49b5-a5d0-17f7afcfa817
preview_cora_advisor - 9468b07c-dea1-4c21-8133-9910b44caeb8
dev_cora_advisor - 094e061b-7682-4bdd-8524-d35359dfcf67

**Comment by EricDahlvang** [comment]
@mitch726 Thanks, we are investigating.

**Comment by prejeanb** [comment]
@EricDahlvang Leader-Bot - 5a793aab-c3d3-46a4-824b-650730d2a6b2

**Comment by JasonSowers** [comment]
@prejeanb  is this still an issue for you after upgrading the packages? @mitch726 did you try upgrading and did that help you?  If not, what version are you on?

**Comment by prejeanb** [comment]
The issue for me was resolved after upgrading the packages.  Everything has been smooth since then.
