### ISSUE TITLE
enum values in FormBuilder (.Net Chatbot)

### ISSUE THREAD

**Issue by bhanuprakash857** [Microsoft/BotBuilder#4624]
Can anyone tell me How to access enum values in FormBuilder (.Net Chatbot) 

e.g. public Types type { get; set; }

 public enum Types
    {
        BuildingContarctor = 1,
        BuildingMaintenance = 2,
        Contractors = 3,
        Interview = 4,
        LearningCenter = 5,
        MultiPurposeRoom = 6,
        Other = 7,
        SolutionCenter = 8,
        TrainingCenter = 9,
        UnAnnouncedEmployee = 10,
        UnAnnouncedVisitor = 11,
        UserGroup = 12,
        VendorVisit = 13
    }
return new FormBuilder<GuestRegistration>()
.Field(nameof(type))
.OnCompletion(processOrder)
.Build();

**Comment by nodeomega** [comment]
You would be able to access those values in the processOrder function that is referenced in `OnCompletion(processOrder)` in this instance.

Example:

    public enum SideOptions
    {
        Pickle = 1,
        Chips = 2,
        ColeSlaw = 3,
        Apple = 4,
        Banana = 5,
        Orange = 6
    }

...

        public SideOptions Side;

        public static IForm<SandwichOrder> BuildForm()
        {
            OnCompletionAsyncDelegate<SandwichOrder> processOrder = async (context, state) =>
            {
                await context.PostAsync($"You have chosen {state.Side}, corresponding to {(int)state.Side}!");
            };

            return new FormBuilder<SandwichOrder>()
                    .Message("Welcome to the simple sandwich order bot!")
                    .Field(nameof(Side))
                    .OnCompletion(processOrder)
                    .Build();
        }

`state` will hold the Side object in this instance, and we can access the user's answer by either calling `state.Side` directly, or map it to the integer value with `(int)state.Side`.

**Comment by nodeomega** [comment]
And to build on that example, the resulting output would be "You have chosen Apple, corresponding to 4!" if the user selected Apple.

Is this what you are looking for?

**Comment by nodeomega** [comment]
Closing this issue as there has been no reply for an extended period.  If this issue persists, feel free to open a new support request.  Thank you.
