### ISSUE TITLE
Rendering of KB article in Facebook Messenger not working as expected after migration

### ISSUE THREAD

**Issue by priyankasyal** [Microsoft/BotBuilder#4626]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.12.2.4
* Active Channels: Facebook Messenger
* Deployment Environment: All

## Issue Description
We have migrated our bot to make use of azure storage from state storage as prescribed by the Azure Bot Service Team. 
However, post making the changes, we are seeing issues with the rendering of content within the Bot Conversation Flow. One of the core scenarios within the Conversation flow is displaying relevant Knowledge Articles (KB). These KB are presented in the form of a card based carousel. Each KB can be opened in full view within the browser, or can be viewed within Messenger through chunks of messages (added pictures for reference).  It is w.r.t the latter use case, (displaying information through chunks) which has undergone change in rendering. We are using the standard message format to display the text and handling content truncation at backend. We have not done any changes at the code level that involve crafting and sending this message, yet the behaviour is different post the migration. Can you suggest what could be the issue?
Kb articles : 
<img width="360" alt="kb cards" src="https://user-images.githubusercontent.com/4937735/40222684-f579d664-5a9d-11e8-9507-cba1951b5b2a.png">

We have replaced the store with botdatastore and used that to get data. A sample is listed below
var store = new TableBotDataStore(ConfigurationManager.ConnectionStrings["StorageConnectionString"].ConnectionString);
					builder.Register(c => store)
					.Keyed<IBotDataStore<BotData>>(AzureModule.Key_DataStore)
					.AsSelf()
					.SingleInstance();

                        var botDataStore = scope.Resolve<IBotDataStore<BotData>>();
			var key = Address.FromActivity(message);
			BotData botData = await botDataStore.LoadAsync(key, BotStoreType.BotUserData, CancellationToken.None);
	

## Expected Behavior
The rendering should not have changed because of migration to azure storage.
![before_migration 2](https://user-images.githubusercontent.com/4937735/40222829-785f99e2-5a9e-11e8-8e40-f6848650b23b.jpg)

## Actual Results
The rendering has changed and full text is not visible now. Attaching images of before and after for reference.
![after_migration 2](https://user-images.githubusercontent.com/4937735/40222805-61e8ea88-5a9e-11e8-95b1-e36ced85c229.jpg)

**Comment by JasonSowers** [comment]
The only changes to you bot were adding the azure table as your state store?  Did you happen to upgrade nuget packages as well or change any other code?  If possible your whole project would be ideal for us to look at, if you are able to share that please let me know.  If not ,are you able to provide a snippet of how you are creating and sending the cards?  Also a snippet of how you are truncating the text would be helpful.  As for what channel(s) you are using you said messanger, is this facebook messanger, is there any other channels?  Are you able to test in webchat on Azure and see what the resul is there? 

Probably not related, but I figured I would mention it, you are not using `cachingBotDataStore` (or at least did not show it in your code you posted) generally your global will look something like this when you are using azure tables storage:

```cs
        protected void Application_Start()
        {
            Conversation.UpdateContainer(
                builder =>
                {
                   builder.RegisterModule(new AzureModule(Assembly.GetExecutingAssembly()));
                    var store = new TableBotDataStore(ConfigurationManager.ConnectionStrings["StorageConnectionString"].ConnectionString);
                    builder.Register(c => store)
                        .Keyed<IBotDataStore<BotData>>(AzureModule.Key_DataStore)
                        .AsSelf()
                        .SingleInstance();

                    builder.Register(c => new CachingBotDataStore(store,
                            CachingBotDataStoreConsistencyPolicy
                                .ETagBasedConsistency))
                        .As<IBotDataStore<BotData>>()
                        .AsSelf()
                        .InstancePerLifetimeScope();
                });
            GlobalConfiguration.Configure(WebApiConfig.Register);
        }
```

**Comment by JasonSowers** [comment]
Closing as no response
