### ISSUE TITLE
[.Net SDK, FB Messenger, Proactive messages] Microsoft.Bot.Connector.ErrorResponseException in CreateConversationAsync() method

### ISSUE THREAD

**Issue by Sandeepmahala** [Microsoft/BotBuilder#4627]
## Bot Info
* SDK Platform: .Net
* SDK Version: 3.15
* Active Channels: Messenger
* Deployment Environment: IIS

## Issue Description
Here I am trying to send a proactive message to multiple users but getting error in last line, CreateConversationAsync() method. It throws Microsoft.Bot.Connector.ErrorResponseException

## Code Example
```cs
string appId = ConfigurationManager.AppSettings["MicrosoftAppId"];
 string appPassword = ConfigurationManager.AppSettings["MicrosoftAppPassword"];
 var appCredentials = new MicrosoftAppCredentials(appId, appPassword);
 var connector = new ConnectorClient(new Uri(serviceUrl), appCredentials);
 MicrosoftAppCredentials.TrustServiceUrl(serviceUrl, DateTime.MaxValue);
 IMessageActivity message2 = Activity.CreateMessageActivity();
 message2.Type = ActivityTypes.Message;
 message2.Text = "Testing group proactive message";
 List<ChannelAccount> accounts = new List<ChannelAccount>()
                {
                    new ChannelAccount("userid", "Username"),
                    new ChannelAccount("userid", "Username")
                };
 ConversationParameters parameters = new ConversationParameters(false, botAccount, accounts, "Testing Proactive", (Activity)message2, null);
 await connector.Conversations.CreateConversationAsync(parameters);
```

## Reproduction Steps
1. Run the above code

## Expected Behavior
Should send the proactive message to the user id's passed

## Actual Results

> An error has occurred. Operation returned an invalid status code 'BadRequest'
ExceptionType - Microsoft.Bot.Connector.ErrorResponseException
StackTrace - at Microsoft.Bot.Connector.Conversations.d__5.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Bot.Connector.ConversationsExtensions.d__1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at Indigo_ProactiveMessages.ConversationStarter.d__7.MoveNext() in C:\Users\documents\visual studio 2015\Projects\ProactiveMessages\ProactiveMessages\ConversationStarter.cs:line 102 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter.GetResult() at Indigo_ProactiveMessages.CustomWebAPIController.d__0.MoveNext() in C:\Users\documents\visual studio 2015\Projects\ProactiveMessages\ProactiveMessages\Controllers\CustomWebAPIController.cs:line 25

**Comment by fanidamj** [comment]
[Duplicate](https://stackoverflow.com/questions/50407463/microsoft-bot-connector-errorresponseexception-in-createconversationasync-meth) of StackOverFlow Question.
