### ISSUE TITLE
[Node.js SDK, Azure Bot Service] Failed to download bot code from Azure Portal

### ISSUE THREAD

**Issue by genloz** [Microsoft/BotBuilder#4628]
## Bot Info
* SDK Platform: Node.js
* SDK Version: 3
* Deployment Environment: Azure Bot Service

## Issue Description
Unable to download the sample source code zip. 
The error is: 
File download error
Failed to dynamically fetch target download uri.

## Code Example
n/a unable to get to the code

## Reproduction Steps
1. Login to the Azure Portal and select the App
2. Click Build
3. Click Download Zip File

## Expected Behavior
Code downloads

## Actual Results
Error message above

**Comment by customcoops77** [comment]
Can't believe how much I see about maybe winning . I feel like I'm just being hurt.

**Comment by fanidamj** [comment]
Can you please let us know the App Name and try if the issue persists for your other Apps too.

**Comment by genloz** [comment]
The app name is ITInnovationBot
The issue is persisting, I can't download any of the code or access the code editor.

**Comment by Andrea-Orimoto** [comment]
@genloz sorry about the inconvenience. Can you please try downloading from Kudu? In the meantime we'll look at the logs.
- open kudu via https://itinnovationbot.scm.azurewebsites.net/DebugConsole
- click on site
- click the download icon next to wwwroot
Hope this helps
Andrea

**Comment by fanidamj** [comment]
@genloz Can you please confirm if the issue still persists?

**Comment by shelwig** [comment]
I also ran into this issue tonight. Here is my bot URL: https://buzibot.azurewebsites.net/api/messages

**Comment by fanidamj** [comment]
@shelwig Have you tried the above steps mentioned by Andrea?

**Comment by GeorgeKouk** [comment]
@fanidamj I am experiencing the same issue, unable to download any of the code from the build page for a new bot service. "Failed to download the file. Error details: error 404 Not Found". Any other ways to download the source code?

**Comment by Harshi25** [comment]
Tried downloading from debug console but it says unauthorised user ....

**Comment by libihan** [comment]
I meet the same problem. 
Suddenly I could not open the Open online code editor and could not Download zip file.
 I don't know why these happened.
Here is my bot URL: https://exonetworkfaqbotv1.azurewebsites.net/api/messages

**Comment by EricDahlvang** [comment]
@libihan have you tried signing into an incognito window ?

**Comment by libihan** [comment]
@EricDahlvang Hello, **the problem has been repaired**. 
At that time, when I clicked "Open online code", the website was redirected to another url, then it shows that "You are unauthorized". When I click "Download zip file", it shows that "Failed to dynamically fetch target download uri.".
However, **in the evening(On July 4, 2018, at 5 pm - Beijing) I can open the Open online code editor and download zip file sucessfully** ~
I don't know why these happened. Maybe the server is being repaired

**Comment by stevkan** [comment]
Hi @shelwig, @GeorgeKouk, @libihan, are yous still experiencing issues in downloading? If so, please try restarting the app service and then attempting a download.

**Comment by libihan** [comment]
Hello, @stevka. I can download the code successfully~  Just in a few hours in the past, the problems occured. Thanks~

**Comment by stevkan** [comment]
Closing as resolved.

**Comment by hubert17** [comment]
Happening to me right now... "Failed to dynamically fetch target download uri."

**Comment by manoj1201** [comment]
I am also facing same issue. I created a Bot using V4 (C#). -> When I try to download the bot source code -> It gives option to download bot source code, when i click button -> Got " File download error " Please suggest.

**Comment by vitorquezada** [comment]
I'm having the same issue. I created a WebBotService and when I will download the code, appear the message "error 404 Not Found".

**Comment by EricDahlvang** [comment]
@vitorquezada This is a closed issue.  If you are still having this problem, please open a new issue on the Services repository: https://github.com/Microsoft/BotFramework-Services
