### ISSUE TITLE
Getting BotTimeoutException

### ISSUE THREAD

**Issue by sandeep1756** [Microsoft/BotBuilder#4629]
## Bot Info
* SDK Platform: .NET 
* SDK Version: 3.15.2.1
* Deployment Environment: Azure App Service, local development with Emulator

## Issue Description
When working on emulator, the bot responds properly. But when deployed, it gives exception as Microsoft.Bot.Schema.BotTimeoutException:
   at Microsoft.Bot.ChannelConnector.BotAPI+<PostActivityToBotAsync>d__30.MoveNext (Microsoft.Bot.ChannelConnector, Version=3.2.2.0, Culture=neutral, PublicKeyToken=null)

## Expected Behavior
No Timeout expected. 

## Actual Results
It was working earlier somehow started giving error: Microsoft.Bot.Schema.BotTimeoutException

**Comment by JasonSowers** [comment]
There was an issue with 3.15.2.1 can you please upgrade to 3.15.2.2 and report the results.

**Comment by sandeep1756** [comment]
Thanks for replying Jason. I tried upgrading to 3.15.2.2, still the same issue.

I cannot share the complete project, below is the snapshot for LuisDialog instantiation. Let me know what other pieces of code you will need, I will check with team if I can share.
![luisdialog](https://user-images.githubusercontent.com/27923411/40291132-8a269af6-5ce0-11e8-9fa9-dbbd9a502e92.png)

**Comment by neetgupta7** [comment]
@sandeep1756 Were you able to fix it?

**Comment by sandeep1756** [comment]
@neetgupta7 Yes. The problem was not with BotBuilder version. We were using ServiceStack and had removed it as UnitTesting it with ServiceStack seemed like impossible. Had replaced it with FluentApi and BotTimeout exception started in the hindsight. Took some time to understand the root cause.
Hope this helps!

**Comment by neetgupta7** [comment]
@sandeep1756 Great! For me our production bots have stopped working without any deployment or modification.

**Comment by sandeep1756** [comment]
@neetgupta7 Did you happen to check if the threshold for hits to LUIS api has exhausted for the month (if using LUIS)?

**Comment by neetgupta7** [comment]
It happens with non LUIS bot as well. Something as simple as QnA maker bot.
