### ISSUE TITLE
Bots can't talk to bots response on eMail channel

### ISSUE THREAD

**Issue by FelixSFX** [Microsoft/BotBuilder#463]
I have a bot based on NodeJS BotFramework with email channel configuration. The bots email is an outlook mail (i.e xxx@outlook.com).
When i contact the bot from my email (i.e. yyy@zzz.com), the bots response 'from-address' is xxx@outlook.com and the 'to-address' is yyy@zzz.com; xxx@outlook.com. The mail was sent to 2 different recipients, myself and the bot. After a little while i start getting mails from the bot with the body  "Bots can't talk to bots". I assume it has to do with the fact that the bot email was part of the recipients on the original bot response and a messaging cycle is created. The bot got an eMail from itself (a bot), sends the fail message and the cycle goes on.

The code used for the reply goes like: 
function process_text_result(session, messageText) 
{
    var reply = new builder.Message().setText(session, messageTxt);
    
    session.send(reply);
}

**Comment by craigjensen** [comment]
Please add your botId and i'll take a look in our logs and see if I can figure out what's happening.

**Comment by FelixSFX** [comment]
The AppID is 'StockdioBot', thanks for looking into it.
