### ISSUE TITLE
[Question] Can I use the same CosmosDB or Table Storage account to store data pertaining to multiple bots?

### ISSUE THREAD

**Issue by ItsMeArthur** [Microsoft/BotBuilder#4631]
Assuming that I have a company that wants several chatbots, does it make sense to use a single CosmosDB database or a single Azure Table Storage to store state data of multiple chatbots? Is this approach reasonable or should I have a database for each chatbot?

**Comment by JasonSowers** [comment]
You can do it either way.  Many people have multiple instances of their data store and many people use the same data store.  Records are stored with bot Id, user Id, and conversation Id as the key. so it is completely up to you.  The only piece that may lean you one way or another would be how much traffic your bot(s) will be getting with respect to the performance of your data store.  Hope this helps

**Comment by ItsMeArthur** [comment]
@JasonSowers Thank you for the information!

**Comment by nstejaswini** [comment]
How to connect the Cosmos DB to Bot and fetch answers ?
