### ISSUE TITLE
Release timeframe for v4

### ISSUE THREAD

**Issue by jackbond** [Microsoft/BotBuilder#4633]
I see that 4.0.1-preview targets .netstandard, do you guys have a rough estimate for when this will be released? We're converting over to .netcore, and this is one of our remaining blockers. Thanks.

**Comment by EricDahlvang** [comment]
Hi @jackbond 

There's a new repository for v4: https://github.com/Microsoft/BotBuilder-dotnet and there is a roadmap on the wiki: https://github.com/Microsoft/BotBuilder-dotnet/wiki/Roadmap

Hope this helps.
