### ISSUE TITLE
MicrosoftPayMethodData.MechantId Typo

### ISSUE THREAD

**Issue by james-r-lewis** [Microsoft/BotBuilder#4634]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.14.1.1
* Active Channels: N/A
* Deployment Environment: Development

## Issue Description
Not sure if this qualifies as an issue, but the class MicrosoftPayMethodData had a property called "MerchantId" which I used in version 3.8.1. After upgrading to 3.14.1.1 it's now "MechantId" (missing the 'r'). 

Just a typo, but the overload methods for this class contradict each other. Just  https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.schema.microsoftpaymethoddata?view=botbuilder-4.0.0-alpha 

MicrosoftPayMethodData(string, IList, IList) has property mechantId (typo)
MicrosoftPayMethodData(string, IList, IList, Boolean) has property merchantId (correct).

Anyways, this is small stuff, just something that bugged me and I had to get it off my chest lol. Keep up the good work. Thanks!

## Expected Behavior
MerchantId

## Actual Results
MechantId (missing 'r') for MicrosoftPayMethodData(string, IList, IList), but not for MicrosoftPayMethodData(string, IList, IList, Boolean)

**Comment by JasonSowers** [comment]
Thanks for reporting this, we will look into correcting it.

**Comment by JasonSowers** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
