### ISSUE TITLE
ConversationUpdate event is able  to start a new dialog but not able to store userData?

### ISSUE THREAD

**Issue by Shishirnaresh** [Microsoft/BotBuilder#4635]
## Bot Info
* SDK Platform: 
* SDK Version: 
* Active Channels: 
* Deployment Environment: 

## Reproduction Steps
1.
2.
3.

**Comment by EricDahlvang** [comment]
This is a known issue with 'conversationUpdate' and the Direct Line (or webchat).  A workaround is described here: 
https://github.com/Microsoft/BotBuilder/issues/4245#issuecomment-369311452
