### ISSUE TITLE
Session doesnt reset on some flows

### ISSUE THREAD

**Issue by Kannaj** [Microsoft/BotBuilder#4638]
## Bot Info
* SDK Platform: Node.js
* SDK Version: 3.11
* Active Channels: All
* Deployment Environment: Azure App Service

## Issue Description
`session.reset('/')` doesnt properly and the bot just hangs 

## Code Example
```
function(deleteUser){

//on delete success
session.send('your acc has been deleted')
session.userData = {}
//session.save()
session.reset('/')
}

```

## Expected Behavior
the bot should notify the user that his account has been deleted and take the user back to our root dialog.

## Actual Results
bot just hangs , no message is sent.

**Comment by stevkan** [comment]
HI @Kannaj, if you call your above code simply as part of the dialog flow it should work fine for you. When I call the dialog below the user data is deleted and runs as expected.

```
bot.dialog('deleteDialog', [
    function(session) {
            session.send('your acc has been deleted');
            session.userData = {};
            //session.save()
            session.reset('/');
    }
```

**Comment by stevkan** [comment]
Closing as this should be resolved. Please reopen if you need further help.
