### ISSUE TITLE
How to get the original raw JSON payload from channel

### ISSUE THREAD

**Issue by odannyc** [Microsoft/BotBuilder#4640]
## Bot Info
* SDK Platform: .NET Framework 4.6
* SDK Version: 3.15
* Active Channels: Facebook Messenger, Direct Line & Emulator
* Deployment Environment: Local development with Emulator

## Issue Description
I'm trying to get the current raw message from the activity. For example, if Im connected to facebook messenger, and an activity gets sent to the bot, how can I get the raw json that messenger sends to botframework? is that possible?

## Code Example
N/A

## Reproduction Steps
N/A

**Comment by stevengum97** [comment]
@odannyc have you tried accessing the `ChannelData` property on the Activity? This should have the native channel's schema, i.e. for this case, the Facebook Messenger message.

You can find the `ChannelData` property listed [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.schema.activity?view=botbuilder-4.0.0-alpha&viewFallbackFrom=botbuilder-3.12.2.4#properties-).
