### ISSUE TITLE
Kik Review process declined - Bot not responding to 'start-chatting' message

### ISSUE THREAD

**Issue by mbrk** [Microsoft/BotBuilder#4643]
## Bot Info
* Node.js
* SDK Version: latest from npm (3.15.0)
* Skype, Telegram, Kik
* Azure Bot Service, Azure App Service

## Issue Description
Our Bot is declined by the review process of Kik because it is not responding to the "start-chatting" messages. 

We are catching all events (and logging them for debugging purposes) but we don't get any "start-chatting" events.

This event seems to "disappear" somewhere in the Bot Framework. Any events triggered by sending a message 'actively' from Kik are received and handled. So the general connection is existing and working.

Variants with  'conversationUpdate' and 'contactRelationUpdate' as events (working with Skype, taken from here: https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-handle-conversation-events?view=azure-bot-service-3.0) are not working with Kik.

## Expected Behavior
Either receive the message of "start-chatting" so we can handle it, or receiving 'conversationUpdate' or 'contactRelationUpdate' as events to handle this.

## Actual Results
![kik_decline](https://user-images.githubusercontent.com/7399208/40359825-60a8cc14-5dc4-11e8-9b30-717b2411f703.jpg)

In my understanding Kik expects the Bot to respond to this event without any prior interaction by humans. Therefore we can't handly anything as we don't get our code triggered until it is too late.

**Comment by craigjensen** [comment]
The Bot Framework supports start-chatting messages by sending a ContactRelationUpdateActivity to your bot and responding appropriately.  Since you are not seeing this, please provide your bot handle and i'll look into our logs and see if I can determine where the problem is

**Comment by mbrk** [comment]
Bothandle: novi-app-bot
App Id: 82b2e58f-dec7-4704-89ef-702edfd1aad3

**Comment by craigjensen** [comment]
I looked through our logs and I see over 100 messages from Kik to your bot and they all returned 200's back to Kik so i'm not sure why they would be reporting that your bot is not responding.  

Is it possible that there could have been messages sent before you configured your bot in the Azure portal (i.e. set the name and api key)?

Did you try to resubmit your bat and see if it's working better now?

**Comment by bsde** [comment]
Yes, the bot is generally working and responds to messages.  
But not to the KIK message type "start-chatting". 
From the submission status: "**Your bot failed to respond to messages of the following types: start-chatting**"

**Comment by craigjensen** [comment]
I'd suggest resubmitting your bot and see if Kik rejects it again.  If they do I'd then ask them for more details about the failing calls because I don't see any failed calls in our logs.

**Comment by bsde** [comment]
We already resubmitted the bot to Kik and it was reject again.

Does the botframework/botbuilder handle this message type: https://dev.kik.com/#/docs/messaging#start-chatting? We do not see this or a similar event in the logs.

**Comment by craigjensen** [comment]
We do handle start-chatting messages and send them to the bot as ContactRelationUpdate activities.

**Comment by mbrk** [comment]
We solved this issue. So closing it. Thanks for your effort!

**Comment by bsde** [comment]
We finally fixed the issue with a extra workaround for kik.

If kik sends the "start-chatting" message. It will be received by the bot twice.

1. a empty text message (type:message). Within the sourceEvent you see it is a "start-chatting" message.
2. a contactRelationUpdate event but without the expected "action" property (https://docs.botframework.com/en-us/node/builder/chat-reference/interfaces/_botbuilder_d_.icontactrelationupdate.html, https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-handle-conversation-events?view=azure-bot-service-3.0)

Our quickfix:

1. check the message.sourceEvent for "start-chatting" and discard that message
2. on "contactRelationUpdate" beside the check (message.action === 'add') for the other platforms, we check if the source is 'kik' and then respond with a welcome message. 

While this solution works, the "contactRelationUpdate" event still behaves differently on "kik".

**Comment by craigjensen** [comment]
Thanks for the feedback.  It sounds like we should add the Action='add' and include the raw Kik message in the ContactRelationUpdate message we send.  I'll open a work item on our end to get this done.
