### ISSUE TITLE
[QUESTION] Did we just had a temporary instability with the Microsoft Bot Framework services?

### ISSUE THREAD

**Issue by ItsMeArthur** [Microsoft/BotBuilder#4645]
I have a lot of chatbots created using the Microsoft Bot Framework. A few minutes ago I received alerts from multiple users that my bots weren't able to give responses. Any responses at all, not even error messages. I tried to send messages to multiple bots, but no responses. I've checked the Azure portal at the moment and got an weird error while trying to open the test tab (I tried on the company network and on my 4G, without any proxies):

![error_bot_framework_azure](https://user-images.githubusercontent.com/11617999/40385185-27717ca8-5ddc-11e8-8c6c-c54c2aabb8f8.png)

Then I tried another chatbot, that I've created a few days just for test purposes and that it is integrated just with the standard webchat (iframe code that I've got from Azure):

![error_bot_framework_webchat](https://user-images.githubusercontent.com/11617999/40385241-50efdb2e-5ddc-11e8-9539-4f36a9d0bf97.png)

I've never had this kind of issues before. About 15 minutes later the bots wend back to being responsive again. I'm really unsure of what happened, as they went down, and back up without any interference of mine. Was this something in the Microsoft services?

**Comment by EricDahlvang** [comment]
Hi @ItsMeArthur 

Thank you for reporting this.  What data center are your bots deployed to?
