### ISSUE TITLE
I would like to add One Time Password Functionality to my bot.

### ISSUE THREAD

**Issue by saranyuavh** [Microsoft/BotBuilder#4648]
## Bot Info
* SDK Platform: Node.js
* SDK Version: v8.11.1
* Deployment Environment: local development with Emulator

## Issue Description
I am new to Bot Development, please be kind :)
I would like to add OTP Functionality to my bot through an email and I have no idea how to implement it, I would like to have some leads to add the functionality.

## Expected Behavior
 Bot Requests username, checks it in the database whether the username exists or not and confirms the email with the user. Once the user confirms, an email containing the OTP shall be sent to the user automatically. The user enters the OTP in the Bot, OTP is verified with the OTP in the DB.

**Comment by stevkan** [comment]
I'm taking a look into possible solutions and will get back to you.

**Comment by saranyuavh** [comment]
BotBuilder SDK v4.0

**Comment by stevkan** [comment]
Hi @saranyuavh,

To do this, you will need to create an [email bot](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-email?view=azure-bot-service-4.0). Following creating the email bot, you will need to build OAuth into the project. You can reference docs on [DirectLine API 3.0](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-authentication?view=azure-bot-service-4.0) authentication or [Authentication via ABS](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-authentication?view=azure-bot-service-4.0) depending on your needs. There is also an [OAuth](https://github.com/Microsoft/botbuilder-js/blob/master/samples/oauth-prompt-bot-es6/app.js) example you can review.

As I don't know what service you plan on authenticating thru, Azure offers a variety of options for authenticating thru. This is done via the bot settings. The following image shows some of the options available.

Hope of help!

![newauthconnection](https://user-images.githubusercontent.com/18403946/42477588-80ce9040-8386-11e8-92b9-90c4e1a9bbaf.jpg)
