### ISSUE TITLE
Stack trace loss on throw in Wait<C, T>.GetResult()

### ISSUE THREAD

**Issue by evnik** [Microsoft/BotBuilder#465]
There is a throw of an exception stored in `fail` in the [GetResult](
https://github.com/Microsoft/BotBuilder/blob/fe946ccab88f35022c6ac9cde1578b45efcd37ca/CSharp/Library/Fibers/Wait.cs#L325) method:
```c#
T IAwaiter<T>.GetResult()
{
    if (this.fail != null)
    {
        throw this.fail;
    }
    ...
}
```
While the exception is rethrown its stack trace is lost, which makes investigation of its source not easy task. That might me fixed by wrapping of original exception into a new one:
```c#
throw new AggregateException(this.fail);
```
I can make a PR, but I'm not sure if you are OK with `AggregateException`.

**Comment by willportnoy** [comment]
http://stackoverflow.com/a/17091351 may be a nicer solution, using the same method await does.

**Comment by willportnoy** [comment]
I'll make a commit that fixes the issue - thank you for the report.

**Comment by willportnoy** [comment]
I've checked in this fix - if it's not right, feel free to re-open the issue.

**Comment by evnik** [comment]
@willportnoy thank you for a quick fix. Looks almost as expected, so I'd like to wait integration into the master to check it.
BTW, I don't see any way to re-open the issue. How do you suggest to do it?

**Comment by willportnoy** [comment]
On my screen, I see "reopen and comment" under the comment box.  It's useful because the closed issues don't appear by default in the issues list and I would only notice replies if I happen to read the email notification.

**Comment by evnik** [comment]
@willportnoy according to [this](http://stackoverflow.com/a/21333938) I cannot re-open an issue if you or another repo collaborator closed it. That means your suggestion to re-open doesn't make sense.
However you can check replies on the [notifications](https://github.com/notifications) page, all threads you participated in should be there until you visit it or unsubscribe from it.

**Comment by willportnoy** [comment]
Right - good feedback.  Thank you for the information about the notification page.
