### ISSUE TITLE
Session.send() on Email channel does not use Reply feature instead of creating a new Thread

### ISSUE THREAD

**Issue by marcoswicket** [Microsoft/BotBuilder#4650]
## Bot Info
* SDK Platform: Node.JS
* SDK Version: 3.15
* Active Channels: Email (Outlook 315)
* Deployment Environment: Local and Azure

## Issue Description
Can't find a way to set the bot messages through the e-mail channel as a Reply and referencing past e-mails instead of creating a new thread.

## Code Example
Regular session.send() is creating new threads.

## Reproduction Steps
1. Any dialog thread just use Session.send()

## Expected Behavior
Reply the thread.

## Actual Results
Create new thread for e-mail answer.

**Comment by nodeomega** [comment]
I need a little more information:
When replying to the bot via email, are you changing the subject line in any way?
What email client are you using to send to the bot?

In my testing, when I reply to the bot's message, it sends in the same thread, but is creating a new thread when I change the subject line.  So I am at least partially replicating this issue.

**Comment by marcoswicket** [comment]
I'm currently replying with the bot using the regular session.send(string), where the string is a message I made with data. For example, the bot prompts user for something, like a date, user selects it and I answer with session.send("The date you choose was " + dateParsedToString); , when the answer arrives to my e-mail it's on an entirely new thread, it doesn't contain the past information of the conversation.

**Comment by marcoswicket** [comment]
Sending an e-mail to the bot with the correct dialog he replies by creating a new e-mail thread. The method that triggers the answer is the session.send() like he was in a chat.

bot.dialog('list', [
	function (session) {
		calendarAPI.listEventsAPI(function (events, answer) {
			var na = {};
			answer = "";

			for (e of events) {
				//console.log(e);
				const start = new Date(e.start.dateTime);
				answer += e.summary;
				answer += start.getDate();
				answer += "   "
			}

			console.log("End of the function: " + answer);
			session.send(answer);
			session.endDialog();
		});
	}
]);

**Comment by marcoswicket** [comment]
I think I understood what you mean by reply, what I want is that the reply works like I'm a regular e-mail reply where the past e-mails / conversation are quoted. Is that possible?

**Comment by nodeomega** [comment]
hmm.... and the calendarAPI call, that's the Google calendar API, correct?

**Comment by nodeomega** [comment]
oh, ok.  I think I get what you're saying now.  so we want the previous replies quotes as well as the new reply in the chain as well, correct?

**Comment by marcoswicket** [comment]
Thats correct!

**Comment by marcoswicket** [comment]
This works! Just need to refine it into something close to what I want. Thanks a bunch! Gonna close the issue.
