### ISSUE TITLE
Prompt.Choice not working

### ISSUE THREAD

**Issue by amitkadu** [Microsoft/BotBuilder#4652]
Prompt.Choice not working if I am providing input for arraylist in Chinese or Spanish language.

            softwareList.Add("Adobe Reader");
            softwareList.Add("FireFox Browser");
            softwareList.Add("Java");
            softwareList.Add("开发办公室");
            softwareList.Add("jugador");
            
          
                PromptDialog.Choice(context,
                                     this.InstallSoftwareAsync,
                                     softwareList,
                                    "Could you select the software that you want me to install?"
                                    );
                return;

**Comment by nodeomega** [comment]
Further questions:
- Does the code run if you comment out the Chinese/Spanish choices?
- Does the code run if you completely omit the Chinese/Spanish choices?

I do not see how the Spanish language choice would affect this, to be honest, as there does not seem to be anything Unicode-based in "jugador".

Do you have any more of a code sample so we can see the context that this is being used in?  Right now I am unable to replicate the issue, and in my testing so far the provided code sample in the original post does seem to be working for me.

Also, are you calling a context.Wait anywhere in the same method as the `PromptDialog.Choice`?

**Comment by amitkadu** [comment]
Hey
1. I didnt get any prompt for unicode
2. Prompt reprompt itself if I am clicking on Chinese/Spanish button
3. If I click on English button code works fine

I am not using context.Wait

Code snippet as:

 List<string> sList = new List<string>(){ "FireFox Browser", "jugador", "开发办公室", "Webex Player"};
        
        public async Task StartAsync(IDialogContext context)
        {
    if (String.IsNullOrEmpty(softwareName))
            {
                context.UserData.TryGetValue("LanguageCode", out userLanguageCode);
                PromptDialog.Choice(context,
                                     this.InstallSoftwareAsync,
                                     sList,
                                    "Could you select the software that you want me to install?"
                                    );
                return;
            }
}

**Comment by nodeomega** [comment]
After further investigation, I believe StartAsync may not be the best place to put that prompt, and it may be at the core of the trouble you are experiencing.  I am adapting a suggestion as per [#2182](https://github.com/Microsoft/BotBuilder/issues/2182).  In my troubleshooting I was also running into the prompt being brought up twice, and if you had that issue, this should help with that as well.

`MessagesController.cs`:

        public virtual async Task<HttpResponseMessage> Post([FromBody] Activity activity)
        {
            try
            {
                if (activity?.GetActivityType() == ActivityTypes.Message)
                {
                    await Conversation.SendAsync(activity, () => new EchoDialog());
                }
                else if (activity?.GetActivityType() == ActivityTypes.ConversationUpdate)
                {
                    IConversationUpdateActivity update = activity;
                    update.MembersAdded = update.MembersAdded.Where(member => member.Id != update.Recipient.Id).ToList();

                    if (update.MembersAdded.Count == 0)
                    {
                        return new HttpResponseMessage(System.Net.HttpStatusCode.Accepted);
                    }
                    await Conversation.SendAsync(activity, () => new EchoDialog());
                }
                else
                {
                    HandleSystemMessage(activity);
                }
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex.Message);
                Debug.WriteLine(ex.StackTrace);
                if (ex.InnerException != null)
                {
                    Debug.WriteLine(ex.InnerException.Message);
                    Debug.WriteLine(ex.InnerException.StackTrace);
                }
            }
            // check if activity is of type message
            return new HttpResponseMessage(System.Net.HttpStatusCode.Accepted);
        }

'EchoDialog.cs` (or whatever your dialog C# file is):

    public class EchoDialog : IDialog<object>
    {
        protected int count = 1;

        protected List<string> softwareList = new List<string>();

        protected string softwareName;
        protected string userLanguageCode;

        public async Task StartAsync(IDialogContext context)
        {
            context.Wait(MessageReceivedAsync);
        }

        public async Task MessageReceivedAsync(IDialogContext context, IAwaitable<IMessageActivity> argument)
        {
            var message = await argument;

            if (softwareList.Count == 0)
            {
                softwareList.Add("Adobe Reader");
                softwareList.Add("FireFox Browser");
                softwareList.Add("Java");
                softwareList.Add("开发办公室");
                softwareList.Add("jugador");
            }
            switch (message.Type) {
                case ActivityTypes.ConversationUpdate:
                    {
                        context.UserData.TryGetValue("LanguageCode", out userLanguageCode);
                        await context.PostAsync("OH hey.");
                        PromptDialog.Choice(context,
                                             InstallSoftwareAsync,
                                             softwareList,
                                            "Could you select the software that you want me to install?",
                                            "Huh?", 5, PromptStyle.Auto);
                        break;
                    }
                case ActivityTypes.Message:
                    {
                        if (message.Text == "reset")
                        {
                            PromptDialog.Confirm(
                                context,
                                AfterResetAsync,
                                "Are you sure you want to reset the count?",
                                "Didn't get that!",
                                promptStyle: PromptStyle.Auto);
                        }
                        else
                        {
                            await context.PostAsync($"{this.count++}: You said {message.Text}");
                            context.Wait(MessageReceivedAsync);
                        }
                        break;
                    }
                default:
                    {
                        context.Wait(MessageReceivedAsync);
                        break;
                    }
            }
        }

        public async Task AfterResetAsync(IDialogContext context, IAwaitable<bool> argument)
        {
            var confirm = await argument;
            if (confirm)
            {
                this.count = 1;
                await context.PostAsync("Reset count.");
            }
            else
            {
                await context.PostAsync("Did not reset count.");
            }
            context.Wait(MessageReceivedAsync);
        }

        public async Task InstallSoftwareAsync(IDialogContext context, IAwaitable<string> state)
        {
            var choice = await state;
            await context.PostAsync($"You have chosen {choice}!");
            context.Wait(MessageReceivedAsync);
        }
    }

When I used this, the Chinese entry did not result in the prompt redisplaying.

Is this of any help?

**Comment by nodeomega** [comment]
Closing this issue as there has been no reply for an extended period.  If this issue persists, feel free to open a new support request.  Thank you.

**Comment by amitkadu** [comment]
@nodeomega this didn't work for me.
Even tried to change file encoding to Unicode, but issue remains same.
