### ISSUE TITLE
Connecting chatbot to sharepoint online directly possiblity

### ISSUE THREAD

**Issue by Rykimaruh** [Microsoft/BotBuilder#4653]
is it possible to connect the ms bot framework to Sharepoint Online so that it can read custom lists? I noticed there is rarely any information about this

**Comment by fanidamj** [comment]
Yes, it is possible to connect the botframework to Sharepoint online. 

There are a number of .net examples online: 

[microsoft-bot-framework-transparent-authentication-with-the-webchat-control](https://stephaneeyskens.wordpress.com/2017/01/04/microsoft-bot-framework-transparent-authentication-with-the-webchat-control/)

[SharePointBot](https://github.com/Ellerbach/SharePointBot)

[contextual-authentication-webchat-control](https://www.rickvanrousselt.com/contextual-authentication-webchat-control/)

[chat-bot-luis-sharepoint-part-one-akshay-deshmukh](https://www.linkedin.com/pulse/chat-bot-luis-sharepoint-part-one-akshay-deshmukh/)

You can find more information from this [StackOverFlow answer](https://stackoverflow.com/questions/50293550/bot-builder-how-to-create-a-bot-using-oauth-2-implicit-grant-flow-method-in-sh). Hope this helps!!

**Comment by Ashwakum** [comment]
Hi,
Is there any video for integrating bot with SharePoint Online by using Visual Studio 2019? Please suggest me. I would be glad of that.

**Comment by jagdishkumawat30** [comment]
Here is one of the video I found in youtube - https://youtu.be/EonSHy6I5j4
