### ISSUE TITLE
[Feature Request] Cannot view full LUIS intent name while reassigning intent 

### ISSUE THREAD

**Issue by annevah** [Microsoft/BotBuilder#4654]
## Issue Description

My Luis intent names are quite long and I wanted to reassign a number of utterances to a different intent. On clicking the drop-down for selecting the new intent I cannot view the whole intent name. It would be so helpful if you could add a tooltip to the dropdown.

## Actual Results

I have intents such as 
     - space.vacation.stats
     - space.vacation.stats.taken
     - space.vacation.stats.left
     - space.vacation.stats.carryover

On clicking the drop-down I can't differentiate the intents. 
![image](https://user-images.githubusercontent.com/30615829/40474578-0bae223c-5f5d-11e8-8065-f0be2af6906d.png)

**Comment by nyxsys** [comment]
While this is looked at for a more permanent fix, I suggest adding an override for the width of this dropdown via stylish theme. Get stylish for your browser ([here](https://chrome.google.com/webstore/detail/stylish-custom-themes-for/fjnbnpbmkenffdnngjfgmeleoegfcffe?hl=en) if you're in chrome and [here](https://addons.mozilla.org/en-US/firefox/addon/stylish/) if you're in firefox. 

Add the following to a new style:

```
@-moz-document url-prefix("https://www.luis.ai/") {

.reassign-intent-dropdown .m-dropdown-panel-comp-bottom {
    width: calc(100% + 100px) !important;
}

}
```

Adjust the buffer (the 100px value) as needed to make sure all your intents show up fully.

**Comment by JasonSowers** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
