### ISSUE TITLE
Conversation ID was expired.

### ISSUE THREAD

**Issue by p-phornthip** [Microsoft/BotBuilder#4655]
I have created Telegram bot and otter bots. But the conversation id has an expired. Could you suggest me, how to keep it active forever or use another thing instead? Thanks in advance.

**Comment by JasonSowers** [comment]
Can you please provide some context and information about your bot?

**Comment by EricDahlvang** [comment]
What are you trying to accomplish with the Conversation.Id ?

**Comment by EricDahlvang** [comment]
Closing due to no response.
