### ISSUE TITLE
New GA qnamaker portal, can't find how to deploy the bot to web chat

### ISSUE THREAD

**Issue by iantje31** [Microsoft/BotBuilder#4656]
## Bot Info
* Active Channels: None
* Deployment Environment: Azure Bot Service,

## Issue Description
I created a new knowledge base in the new GA portal of QnAmaker. After i deployed the bot i can't find the channels tab in Azure. How can i deploy the bot to web chat and Microsoft Teams? 

## Reproduction Steps
1. Create the bot in QnAmaker
2. Open the bot in Azure
3. Try to find the channels section

## Expected Behavior
I expected a tab in Azure where you can deploy the bot to different channels

## Actual Results
There is no channels tab, so i can't deploy the bot

**Comment by stevengum97** [comment]
Can you provide a screenshot of the page you see?

**Comment by iantje31** [comment]
Hi @stevengum97,
I found the solution. I only created the qnamaker endpoint. All i needed to do was create a web app bot and copy the subscriptionid.

**Comment by stevengum97** [comment]
Great! If you run into this problem again please reopen the issue.
