### ISSUE TITLE
How to make the conversation Id continue with the directline API?

### ISSUE THREAD

**Issue by weizhenzhao** [Microsoft/BotBuilder#4657]
## Bot Info
* SDK Platform:  .NET
* SDK Version: 3.15.22
* Active Channels: Direct Line,
* Deployment Environment: Azure Bot Service

## Issue Description
1、The I see  the offical description says that if  I want to create a conversation
     first I should use the directline secret to obtain a token , and the token will expire in 1800 s
     then use the token to create an conversation , and the conversation a run as long as I have the valid token
     And I can refresh the token using the api :  
     **POST https://directline.botframework.com/v3/directline/tokens/refresh
     Authorization: Bearer TOKEN_TO_BE_REFRESHED**
  2、 But my problem is how can I using the BotBuilder.Directline sdk to make the token refreshed?
         And after the token is refreshed , should I do something with the existing conversation by the 
         directline sdk?

Thank you very much if someone can help
WeiZhen

## Code Example

```cs
using Bot.App_Alice;
using Bot.App_Common;
using Microsoft.Bot.Connector.DirectLine;
using Newtonsoft.Json;
using Pactera.Common;
using Pactera.Common.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using System.Web.Http;

namespace Bot.Controllers
{
    public class WeiXinController : ApiController
    {

        private static Dictionary<String, String> conversationIdMap = new Dictionary<string, string>();

[HttpPost]
        public async Task<HttpResponseMessage> Post()
        {
         
            var weiXinMessage = await Request.Content.ReadAsStringAsync();
            if (string.IsNullOrEmpty(weiXinMessage))
            {
                var responseData = new BotInterfaceEntity();
                responseData.Result = Pactera.Common.Enums.BotResult.Exception;
                responseData.Argument = "Sorry, please input a word";
                return new HttpResponseMessage { StatusCode = HttpStatusCode.OK, Content = new StringContent(JsonConvert.SerializeObject(responseData), Encoding.UTF8, "application/json") };
            }

            var conversationStart = DateTime.Now;
            var client = new DirectLineClient("SecretRemoved");

            //get weixin message entity
            WeiXinEntity weiXinEntity = JsonConvert.DeserializeObject<WeiXinEntity>(weiXinMessage);
            string conversationId = string.Empty;
            if (conversationIdMap.ContainsKey(weiXinEntity.openId))
            {
                conversationIdMap.TryGetValue(weiXinEntity.openId, out conversationId);
            }
            else {
                //create new conversation
                var conversation = await client.Conversations.StartConversationAsync();
                conversationId = conversation.ConversationId;
                //add new conversation id to the map
                conversationIdMap.Add(weiXinEntity.openId, conversationId);
                //compute create new conversation time
                var conversationStartCost = (DateTime.Now - conversationStart).TotalSeconds;
                LogHelper.Instance.PacteraWrite($"===> New DirectLine Conversation '{weiXinEntity.content}' Time Cost: {conversationStartCost}s <===", "Bot.Controllers", "WeiXinController", "Post");
                //===>
            }

            //===>
            var detectedStart = DateTime.Now;
            var language = await Translator.Instance.DetectedLanguage(weiXinEntity.content);
            var detectedCost = (DateTime.Now - detectedStart).TotalSeconds;
            LogHelper.Instance.PacteraWrite($"===> Bing Language detected '{weiXinEntity.content}' Time Cost: {detectedCost}s <===", "Bot.Controllers", "WeiXinController", "Post");
            //===>
            if ("Failed" == language)
            {
                var responseData = new BotInterfaceEntity();
                responseData.ChartFlg = Enums.WeiXinShowFlag.None;
                responseData.Result = Pactera.Common.Enums.BotResult.Exception;
                responseData.Argument = Alice.Instance.AliceAnswer(weiXinEntity.content);
                return new HttpResponseMessage { StatusCode = HttpStatusCode.OK, Content = new StringContent(JsonConvert.SerializeObject(responseData), Encoding.UTF8, "application/json") };
            }

            if (language != "en")
            {
                //===>
                var translateStart = DateTime.Now;
                weiXinEntity.content = await Translator.Instance.TranslateTextToEn(weiXinEntity.content);
                var translateCost = (DateTime.Now - detectedStart).TotalSeconds;
                LogHelper.Instance.PacteraWrite($"===> Bing Language translate '{weiXinEntity.content}' Time Cost: {translateCost}s <===", "Bot.Controllers", "WeiXinController", "Post");
                //===>
            }
            var activity = new Activity();
            activity.From = new ChannelAccount("weixin");
            activity.Text = weiXinEntity.content.Replace("\n", "").Replace("\r", "").Replace("\t", "").Trim();
            activity.Summary = language;
            activity.Type = ActivityTypes.Message;

            //call bot for advice
            //===>
            var callBot = DateTime.Now;
            var directLineResponse = await client.Conversations.PostActivityWithHttpMessagesAsync(conversationId, activity);
            var directLineResult = JsonConvert.DeserializeObject<DirectLineEntity>(await directLineResponse.Response.Content.ReadAsStringAsync());
            var callBotCost = (DateTime.Now - callBot).TotalSeconds;
            LogHelper.Instance.PacteraWrite($"===> Bot Http request '{weiXinEntity.content}' Time Cost: {callBotCost}s <===", "Bot.Controllers", "WeiXinController", "Post");
            //===>

            //OK
            string watermark = null;
            var activitySet = await client.Conversations.GetActivitiesAsync(conversationId);
            watermark = activitySet?.Watermark;
            var botActivity = from x in activitySet.Activities
                             where x.From.Id == "CRMChatBot-ChannelBot"
                             select x;
            List<Activity> activities = botActivity.ToList<Activity>();
            String text = string.Empty;
            if (activities != null && activities.Count > 0) {
                text = activities[activities.Count - 1].Text;
            }
            return new HttpResponseMessage { StatusCode = HttpStatusCode.OK, Content = new StringContent(text, Encoding.UTF8, "application/json") };
        }


    }
}
```
I'm using conversationIdMap to store the conversationId , and a message sent by wechat will give me an unique openId , and I use the openId as the key , conversationId as the value.
If an openId already has a conversationId , the new message will goes to the existing conversation correctly
But the conversationId will expire with the token in 1800s
So my problem is how can I update the conversationId?

**Comment by EricDahlvang** [comment]
ConversationIds do not expire.  The token retrieved when the conversation is created does expire, but not the conversation id.  If you wish to re-connect to the existing conversation, you will need to refresh the token and use that when constructing the DirectLineClient:

```cs
var client = new DirectLineClient("ExpiredToken");
client.Tokens.RefreshToken();
client.Conversations.ReconnectToConversation("conversationid", "watermark");
```

**Comment by weizhenzhao** [comment]
@EricDahlvang 
Hi EricDahlvang I've change my code.
Can you have a look if I'm right or not? 
in my comprehensive  when I execute the code
`var client = new DirectLineClient("k9R71se3nqg.cwA.GfE.4Xx7jxdr5wFAC6tkulSb9z2CK5nTt_szFevTWdUvp14");
`
I will generate a new token , so I always generate the new token  using the create new directline method,
and post the message to the existing conversation using 
` var directLineResponse = await client.Conversations.PostActivityWithHttpMessagesAsync(conversationId, activity);`


` //create DirectLineClient
            var conversationStart = DateTime.Now;
            var client = new DirectLineClient("k9R71se3nqg.cwA.GfE.4Xx7jxdr5wFAC6tkulSb9z2CK5nTt_szFevTWdUvp14");

            //get weixin message entity
            WeiXinEntity weiXinEntity = JsonConvert.DeserializeObject<WeiXinEntity>(weiXinMessage);
            string conversationId = string.Empty;
            //if conversation id exist in the conversation map
            if (conversationIdMap.ContainsKey(weiXinEntity.openId))
            {
                ConversationTime conversationTime = new ConversationTime();
                conversationIdMap.TryGetValue(weiXinEntity.openId, out conversationTime);
                conversationId = conversationTime.conversationId;
                client.Conversations.ReconnectToConversation(conversationTime.conversationId);
            }
            else {
                //create new conversation
                var conversation = await client.Conversations.StartConversationAsync();
                conversationId = conversation.ConversationId;
                //add new conversation id to the map
                ConversationTime conversationTime = new ConversationTime();
                conversationTime.conversationId = conversationId;
                conversationIdMap.Add(weiXinEntity.openId, conversationTime);
                //compute create new conversation time
                var conversationStartCost = (DateTime.Now - conversationStart).TotalSeconds;
                LogHelper.Instance.PacteraWrite($"===> New DirectLine Conversation '{weiXinEntity.content}' Time Cost: {conversationStartCost}s <===", "Bot.Controllers", "WeiXinController", "Post");
                //===>
            }
            //===>`

Do you see any problem ?

**Comment by EricDahlvang** [comment]
@weizhenzhao   I have no idea what WeiXinEntity is, or what the converationIdMap is.  I haven't tried your code.  Did you try it? If it works, then I don't see a problem.  👍
