### ISSUE TITLE
User not able to see anything (Error), when Bot Service returns status code 403

### ISSUE THREAD

**Issue by imailer2015** [Microsoft/BotBuilder#4658]
## Bot Info
* SDK Platform: Bot REST Connector
* SDK Version: N.A.
* Active Channels: MS Teams
* Deployment Environment: Own deployment environment

## Issue Description
Hi Folks,

I was trying out authentication for Microsoft Bot messages and noticed that user doesn't receives any notification / message / error when the request is rejected with HTTP  403 (forbidden).

User should be able to see something / error for that.

## Reproduction Steps
1. Create a bot with Microsoft and use the app id / password to configure you simple bot service.
2. User sends "Hi" message from the bot. Bot Connector makes a post request to the bot service endpoint.
3. Try explicitly sending HTTP 403 message as status for the request.
4. User doesn't see anything / Error on the chat UI.

## Expected Behavior
User should be able to see some error message indicating the message wasn't sent/delivered

## Actual Results
User is not able to see anything. It appears to user as if the message has been sent.

**Comment by imailer2015** [comment]
Hi Jason,
Any updates for the issue ?

**Comment by imailer2015** [comment]
Hi Jason,
Any updates for the issue ?

**Comment by stevkan** [comment]
Hi @imailer2015,

Unfortunately, this isn't a Bot Framework issue and changes made in the BF code will have no effect. It is related to how MS Teams reports a 403 error back to the user when received from the bot.

**Comment by imailer2015** [comment]
So, MS-Teams team should take the bug in their cart. Why on the earth are they making HTTP-200 & HTTP-403 the same ?

**Comment by stevkan** [comment]
Unfortunately, I don't have an answer to that question. But, yes, it should be raised as a bug.

**Comment by JasonSowers** [comment]
@imailer2015 you could try reporting the issue here https://github.com/OfficeDev/BotBuilder-MicrosoftTeams I'm not sure how active they are on that GitHub though.

**Comment by customcoops77** [comment]
Help me!

Thomas
