### ISSUE TITLE
[Node.js SDK, Cortana] Cortana doesn't trigger NONE intent first.

### ISSUE THREAD

**Issue by rjgmail88** [Microsoft/BotBuilder#4661]
## Bot Info
* SDK Platform: Node.js
* SDK Version: V3
* Active Channels: MS Teams, Coratana
* Deployment Environment: Azure App Service, local development with Emulator

## Issue Description
I have v3 BOT with above mentioned channels. I am also using QnA and LUIS to get intent match and better results. My LUIS model has 4 intents RoomFinder,PersonInfo,CampusInfo and None. I trained NONE intent with something that is outside of my bot domain, which is HR related questions ex:- where can I find 401k info etc. 
There are 2 ways I am making QnA service call. One, if NONE intent is detected and two, from RootDialog. So in a nutshell, when LUIS doesn't trigger any dialog matching intents [RoomFinder,PersonInfo,CampusInfo] my default would be QnA which will serve answer by None intent or final fallback would be root Dialog. 
Issue:- In MS teams and chat emulator flow works really well. I mean all LUIS stuff works as expected. If I type something outside of predefined intents, then None intent will be triggered, else root dialog will take care of a term. But, there is an issue when I work with Cortana. Here is my flow with  Cortana

**Happy path:**
user:Hey Cortana, Launch {skillName}
Cortana:"Good morning, how can i help you." This is happening in RootDialog. 

User: "try any term which can trigger predefined intents " ex:- Who is person {Name}? PersonInfo intent.
Cortana:- Gives person info in plain text.

User: Ask something which will trigger none intent. ex:- where is my payroll info?
Cortana: will answer back

**Broken Path:-**
user:Hey Cortana, Launch {skillName}
Cortana:"Good morning, how can i help you." This is happening in RootDialog. 

User: Ask something which will trigger none intent. ex:- where is my payroll info?
Cortana: no response. None intent will not triggered on first input from user.
also, rootDialog will not be triggered, in case there is no intent match or dialog stack is empty. 

In order to get to None intent or rootDialog I have to trigger some intent first in Cortana and then say a term which will fall under None or Root. On the first flow it doesn't work. 

## Code Example
```
bot.dialog('None', function (session) {
    callQnA( );
}).triggerAction({
    matches: 'None'
});
```
//RootDialog

```
var bot = new builder.UniversalBot(connector, function (session, args) {
callQnA( );
}
```

## Reproduction Steps
Full flow mentioned in the issue Description.

## Expected Behavior
Cortana should  be able to work with first input from user and, either none intent should be triggered or pass it to root dialog. 

## Actual Results
None intent or RootDialog only works if it was followed by some other intent trigger.

**Comment by JasonSowers** [comment]
I ran into this issue myself when I was first learning to build bots with LUIS.  Have you trained any utterances in your none intent?  The issue here is that LUIS will always try to match the best fit rather than default to not matching. If you are using QnA with your none intent, try adding all your QnA questions as utterances in your none intent and you should have better results.

**Comment by rjgmail88** [comment]
@JasonSowers , Yes I have added all utterances in NONE intent and trained it. So it works well even thought I type some crap it goes to none intent. I can set a intentThreshold to avoid this so only things I trained will be answered by QnA (by triggering none intent.)
The issue I do not understand is why Cortana doesn't get it on first try.?

Ex: I launch a skill on Cortana , and say / type crap or defined/trained utterance (None intent)  --> cortana just dies/timeouts after 2 secs
**But**
I launch a skill on Cortana , and say / type defined/trained utterance (Any intent but None) ,  cortana just replies , then I say/type crap or defined/trained utterance (None intent)  --> cortana just replies

**Comment by fanidamj** [comment]
Did you check [Review Label Suggested Utternces](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/label-suggested-utterances) in LUIS so that you can label and train if anything is mislabeled. All the endpoint hits should be reflected there. Let us know if it works!!

**Comment by rjgmail88** [comment]
@fanidamj , I think there is some misunderstanding the issue I'm facing or I might have not explained it in best possible way. This isn't an issue with LUIS intent recognition as you can see 'Happy Path' section of the description. The probable is 
why Cortana's behavior is different for NONE intent when its triggered first or triggered followed by some other intent.

**Comment by drewlane** [comment]
I don't know if this helps but there is a know issue at the bottom of this page:
https://docs.microsoft.com/en-us/cortana/skills/known-issues

I ended up checking for null in the default handler since I couldn't get the None Intent to trigger.

**Comment by EricDahlvang** [comment]
@rjgmail88 Please share a small sample application demonstrating this issue.

Also, have you tried debugging the bot locally while responding to Cortana?  https://blog.botframework.com/2017/10/19/debug-channel-locally-using-ngrok/

**Comment by JasonSowers** [comment]
@rjgmail88 does this resolve your issue?

**Comment by rjgmail88** [comment]
I will try above and let you know.

**Comment by EricDahlvang** [comment]
Closing due to no response.
