### ISSUE TITLE
[Feature Request] Support for Facebook payments

### ISSUE THREAD

**Issue by jhaala** [Microsoft/BotBuilder#4664]
## Bot Info
* SDK Platform: Node.js
* SDK Version: 3.15.0
* Active Channels: Facebook
* Deployment Environment: Channel Registration

## Issue Description
I have a lot invested in Bot Framework, and now realized it's not capable of handling Stripe payments natively through Facebook. I had been led to believe that I could just use SourceEvent to pass the code.

Am I correct in assuming that I will need to bypass Microsoft's channel registration, and write my own Facebook webhook connection to allow this? The apps are hosted on my own servers.

**Comment by EricDahlvang** [comment]
This issue is tracking all Feature Requests for FB Messenger: https://github.com/Microsoft/BotBuilder/issues/4360

**Comment by customcoops77** [comment]
Help me!

Thomas
