### ISSUE TITLE
Grant type for azure bot service?

### ISSUE THREAD

**Issue by Rykimaruh** [Microsoft/BotBuilder#4665]
![types](https://user-images.githubusercontent.com/5460795/40580378-eb91c8d2-610a-11e8-93a6-3b6e78ef2616.png)

So I'm  trying out the connection in Azure, but stumbled upon this. I got the information for most fields, but I have no idea what Grant Type is. 

Following this link: [Here](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-authentication?view=azure-bot-service-3.0) 

It states: "For Grant Type, enter authorization_code", but I don't know what that means

**Comment by JasonSowers** [comment]
Try this `client_credentials`

**Comment by EricDahlvang** [comment]
This doc explains a little more about what authorization_code is: https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-protocols-oauth-code

**Comment by JasonSowers** [comment]
Closing as no response
