### ISSUE TITLE
Cortana Connected Home skill

### ISSUE THREAD

**Issue by lukasvolf** [Microsoft/BotBuilder#4668]
## Bot Info
* SDK Platform: .NET
* SDK Version: 4
* Active Channels: Cortana
* Deployment Environment: Azure Bot Service

## Issue Description
How can I create a Cortana skill that integrates with the Connected Home feature? (Cortana Notebook -> Manage Skills -> Connected Home)
 It seems like for creating Cortana Skills I have to use the Bot framework. So I created a bot hosted on my backend that uses my custom OAuth2 provider for authenticating users. All that works well, except it is just a standard bot that does not know anything about the context (e.g. the user has configured four devices with custom names and I want to be able to control these devices so the voice recognition should take those 4 device names configured by the user and use them as a "phrase list" just for that user).

## Expected Behavior
I should be able to create a Cortana skill similar to the Hue/Insteon/Nest skills in the Cortana skill store that are all listed in the Connected Home category.

## Actual Results
I haven't found any mentions of the Connected Home in the documentation. The article describing a bot that could do similar things I want it to do is here: https://docs.microsoft.com/en-us/azure/bot-service/bot-service-scenario-internet-things?view=azure-bot-service-3.0
Unfortunately, such bot has the 2 main problems I listed above:
1) It requires the user to remember the name of the skill which must be opened prior to interacting with it
2) It does not allow the user to define his own devices, name them (to anything he wants to) to and then get responses that include only those existing device names with some probability and not some completely unrelated words that Cortana thinks she's heard.

**Comment by lukasvolf** [comment]
So I tried to ignore the limitation number 1 for now and instead focus on somehow solving limitation number 2 for now in a custom skill. I tried using LUIS list entity to specify a list of predefined words to look for in my intents and then some utterances using those intents. In the future I planned on having the user to upload an autogenerated LUIS model using you API that would contain all the entities available in the system. I enabled Speech Priming in a hope that Cortana would obtain this list and match the voice input against the List entity. It turned out it does not work, the intent is invoked but it does not contain any entity matching the List entity. Can I force LUIS to always attempt to find the closest matching entity?

**Comment by lukasvolf** [comment]
I'd appreciate somebody to answer the question, but from the silence I think I can already guess the answer...

**Comment by EricDahlvang** [comment]
Hi @lukasvolf 

I've read through everything you've written here, but I'm not clear on what the question is.  Have you already solved the issue?

**Comment by lukasvolf** [comment]
Hi @EricDahlvang, thanks for responding. The question is: How can I create a Cortana skill that integrates with the Connected Home feature?

**Comment by EricDahlvang** [comment]
That is an open ended question.  I'm not sure how to respond.  I've never personally written a Cortana Skill that interacts with Connected Home.  I will reach out to some Cortana people, and let you know what they say.

**Comment by EricDahlvang** [comment]
Connected Home platform is not self-service at this time.  There is an internal Microsoft path in order to onboard into Cortana Connected Home.  If you wish to pursue this, please email me at the address on my profile: https://github.com/EricDahlvang and I will provide more information.
