### ISSUE TITLE
Same variable value of every person

### ISSUE THREAD

**Issue by MrKafr** [Microsoft/BotBuilder#4669]
## Bot Info
* SDK Platform: .NET
* Active Channels: Skype
* Deployment Environment: Azure Bot Service

## Issue Description
Hello. I´m building bot for fun for my skype group but i got stuck on one problem. First, i would like to mention, that I have no experience in C# or .NET and i learn as i go along. But back to my problem, i need to make one variable for everybody. Let´s say (see code-strip below) , that A wrote 2 messages and B 3 messages. If A wants to show the count variable, he get 2 and  B get 3. I want both to get 5. Is there some easy way to do it?

## Code Example

```
[Serializable]
public class EchoDialog : IDialog<object>
{
protected int count = 1;

     public async Task StartAsync(IDialogContext context)
     {
         context.Wait(MessageReceivedAsync);
     }

     public virtual async Task MessageReceivedAsync(IDialogContext context, IAwaitable<IMessageActivity> argument)
    {
	var messageNS = await argument;
	string message = messageNS.Text.ToString();
	if (message.Contains("show")
        {
            await context.PostAsync($"{this.count}");
            context.Wait(MessageReceivedAsync);
        }
	else{
	    await context.PostAsync("counted");
            context.Wait(MessageReceivedAsync);
	{
    }
}

**Comment by EricDahlvang** [comment]
If the count variable static then it will be shared by all threads (and all users).  Also, since different .net threads will be adding to the variable at the same time, use Interlocked.Increment() to ensure they will not overwrite one another:

```cs
    [Serializable]
    public class EchoDialog : IDialog<object>
    {
        static int count = 0;

        public async Task StartAsync(IDialogContext context)
        {
            context.Wait(MessageReceivedAsync);
        }

        public virtual async Task MessageReceivedAsync(IDialogContext context, IAwaitable<IMessageActivity> argument)
        {
            var messageNS = await argument;
            string message = messageNS.Text.ToString();
            if (message.Contains("show"))
            {
                await context.PostAsync($"{count}");
            }
            else
            {
                Interlocked.Increment(ref count);

                await context.PostAsync("counted");
            }

            context.Wait(MessageReceivedAsync);
        }
    }
```

**Comment by MrKafr** [comment]
Thank you very much... I have one more question... is there some way to keep that value in count even after new code deployment? Because everytime i deploy, my variable resets...

**Comment by MrKafr** [comment]
Thank you very much... I have one more question... is there some way to keep that value in count even after new code deployment? Because everytime i deploy, my variable resets, which make sence, but its there any way how to save them?

**Comment by EricDahlvang** [comment]
You would need to save it in a database, or somewhere.  The Bot Builder sdk does not have a built in mechanism for state 'shared across all users'.
