### ISSUE TITLE
[.Net SDK, QnA Maker] How to lower confidence score threshold?

### ISSUE THREAD

**Issue by iantje31** [Microsoft/BotBuilder#4670]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3
* Active Channels: Web chat, Microsoft Teams
* Deployment Environment: Azure Bot Service

## Issue Description
Ever since i migrated my bot to the GA QnAmaker portal. It seems like the amount of confidence score required to get an answer is higher than the preview version. Is there any way to lower this.

## Reproduction Steps
1. Ask the bot: Hoe krijg ik FutureFit?
![image](https://user-images.githubusercontent.com/32571828/40616670-317019c6-628c-11e8-8e51-5b975d6607cc.png)

## Expected Behavior
I expect the bot to answer the question.

## Actual Results
The bot sends back: No good match in FAQ. While in application insights, the right answer is displayed:
![image](https://user-images.githubusercontent.com/32571828/40616861-bcf2ea46-628c-11e8-9c00-382bf929d6ba.png)

**Comment by fanidamj** [comment]
You will need to update the confidence threshold in your code to a lower value in order for the answers to be returned. The C# QnA template, the default threshold is 50%.  Maybe playing with this threshold will help:

`public BasicQnAMakerDialog() : base(new QnAMakerService(new QnAMakerAttribute(Utils.GetAppSetting('QnASubscriptionKey'), Utils.GetAppSetting('QnAKnowledgebaseId'), 'No good match in FAQ.', 0.5)))`
