### ISSUE TITLE
[LUIS] Delete multiple suggested utterances with LUIS api

### ISSUE THREAD

**Issue by chetanclozio** [Microsoft/BotBuilder#4671]
Hi Team,
I want to delete multiple suggested utterances from LUIS api. I tried with delete request "https://westus.api.cognitive.microsoft.com/luis/api/v2.0/apps/{appId}/versions/{versionId}/suggest" and below are my findings,
1) Above request works well for deleting single utterances
2) Dn't know how to pass multiple utterances to above request. 
3) Tried with passing data in body like as "Test","Test1" but getting badArgument response.
`{
    "error": {
        "code": "BadArgument",
        "message": "Cannot find an unlabeled query with the given text."
    }
}`

**Comment by fanidamj** [comment]
Unfortunately we currently **don't support** deleting multiple utterances through Programmatic API. The only solution is through [dashboard](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/label-suggested-utterances#delete-several-utterances).
