### ISSUE TITLE
Storage containers for V4 Bot ?

### ISSUE THREAD

**Issue by rjgmail88** [Microsoft/BotBuilder#4675]
## Bot Info
* SDK Platform: Node.js 
* SDK Version: V4
* Active Channels: MS Teams
* Deployment Environment: Azure App Service

## Issue Description
How to access/use Storage containers for V4 Bot?. Here is the link for v3 but I am not sure if same concept follows in V4?

V3 Link:- [https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-state?view=azure-bot-service-3.0#storage-containers](https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-state?view=azure-bot-service-3.0#storage-containers)

**Comment by rjgmail88** [comment]
Any update on this ?

**Comment by stevkan** [comment]
Hi @rjgmail88,

Here are the docs that discuss Nodejs V4 state storage. Please take a look over. They should provide you with all the information you need. I'm going to close this for now as answered. Reopen if you additional related questions. If you have any "how-to" questions, please post them on [stackoverflow.com](http://www.stackoverflow.com) so the larger community can benefit.

[Save state and access data](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-storage-concept?view=azure-bot-service-4.0)
[Save data directly to storage](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-storage?view=azure-bot-service-4.0&tabs=jsechoproperty%2Ccsetagoverwrite%2Ccsetag)
[Save state using conversation and user properties](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-state?view=azure-bot-service-4.0&tabs=js)
