### ISSUE TITLE
Cannot Fully Register Bot with S4B Online with AD Sync Enabled

### ISSUE THREAD

**Issue by brprigge** [Microsoft/BotBuilder#4678]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3
* Active Channels: Skype for Business
* Deployment Environment: Azure Bot Service

## Issue Description
After running the commandlet to register the bot in S4B online, it expects us to run the On-Prem equivalent as we are using AD Sync, but we do not have an S4B server on prem, we exclusively use online.

## Reproduction Steps
1. Create New Bot
2. Register with S4B online
3. Observe message to register locally
4. Attempt to IM bot
5. Receive message saying that the message was not sent due to company policy

## Expected Behavior
On-Prem Registration is only required when S4B is in hybrid mode.

## Actual Results
On_Prem registration is required when AD is in hybrid mode.

**Comment by nodeomega** [comment]
We do not have a tenant with Skype for Business in which we would be able to help troubleshoot this issue.  Please reach out to the [Skype for Business team](https://www.skypefeedback.com/) and they should be able to assist you.

**Comment by brprigge** [comment]
And the Skype for Business team says they are unable to help with bots....
