### ISSUE TITLE
Resolve date from day

### ISSUE THREAD

**Issue by hgjkant** [Microsoft/BotBuilder#468]
Hi,

I've created a bot with builder v1.0.1, and am trying to get a date from only a day. For example, for 'set deadline to monday' I expect a date object set to Monday (possibly at midnight), but I'm getting nothing. Same for abbreviated or capitalized, and the day is also ignored in 'set deadline for Monday 2pm' (but the time works fine). 

The code to get the date object (as from docs):
`var time = builder.EntityRecognizer.resolveTime(args.entities);`

with `args.entities` being

```js 
[ { entity: 'monday',
    type: 'builtin.datetime.date',
    startIndex: 17,
    endIndex: 22,
    resolution: { date: 'XXXX-WXX-1' } } ]
```
Should this be possible?

**Comment by IanBoggs** [comment]
I've found that Luis can be a bit vague when it comes to dates. In your example you haven't specified _which_ Monday you want the deadline setting for. Hence it has returned a string that is representing the first day of the week. If you said 'set deadline to next Monday' then the resolution would give you the date of the next Monday. 
You get the same type of response if you say something like Christmas Day. You get 'XXXX-12-25'

**Comment by v-thgratMSGit** [comment]
Closing this issue. Please open a new issue for further discussion if necessary. Thanks!
