### ISSUE TITLE
Embed the web chat control in your website using the secret (iframe using secret)

### ISSUE THREAD

**Issue by jolienai** [Microsoft/BotBuilder#4680]
## Bot Info
* SDK Platform:  .NET
* SDK Version: latest version
* Active Channels: Skype, Direct Line, Telegram. -->
* Deployment Environment: local development with Emulator.

## Issue Description
I have to connect my bot to web chat and I am trying to do so using an iframe but I have got this error:
botchat.js:34 Uncaught TypeError: Cannot read property 'offsetWidth' of null
at e.componentDidUpdate (botchat.js:34)
at t.notifyAll (botchat.js:34)
at r.close (botchat.js:34)
at r.closeAll (botchat.js:20)
at r.perform (botchat.js:20)
at o.perform (botchat.js:20)
at o.perform (botchat.js:20)
at Object.S [as flushBatchedUpdates] (botchat.js:20)
at r.closeAll (botchat.js:20)
at r.perform (botchat.js:20)

## Code Example

HTML code

    
    <div class="modal left fade" id="myModalBot" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-body">
                    <iframe style="border:hidden; width:100%;height:300px;" src='https://webchat.botframework.com/embed/botapplication20180524?s=B7ivbsCdRRM.cwA.-R0.PkCid9dZtCpfsW39qklUo-HT_3Be_plu27vCD7iPgMU'></iframe>
                </div>
            </div>
        </div>
    </div>

## Reproduction Steps
1. 
2.
3.

## Expected Behavior
Webchat running without any issues.

## Actual Results
botchat.js:34 Uncaught TypeError: Cannot read property 'offsetWidth' of null
    at e.componentDidUpdate (botchat.js:34)
    at t.notifyAll (botchat.js:34)
    at r.close (botchat.js:34)
    at r.closeAll (botchat.js:20)
    at r.perform (botchat.js:20)
    at o.perform (botchat.js:20)
    at o.perform (botchat.js:20)
    at Object.S [as flushBatchedUpdates] (botchat.js:20)
    at r.closeAll (botchat.js:20)
    at r.perform (botchat.js:20)

**Comment by jolienai** [comment]
This issue only happen when the. iframe is inside other div tags

**Comment by jolienai** [comment]
Here the html code of my page:

<!doctype html>
<html lang="en">
<head>
    <title>Salon Booking - Software and Bot</title>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Mobland - Mobile App Landing Page Template">
    <meta name="keywords" content="HTML5, bootstrap, mobile, app, landing, ios, android, responsive">
    
    <link rel="dns-prefetch" href="//fonts.googleapis.com">
    <link href="https://fonts.googleapis.com/css?family=Rubik:300,400,500" rel="stylesheet">
    
    <link rel="stylesheet" href="~/css/bootstrap.min.css">
    
    <link rel="stylesheet" href="~/css/themify-icons.css">
    
    <link rel="stylesheet" href="~/css/owl.carousel.min.css">
    
    <link href="css/style.css" rel="stylesheet">
   
</head>
<body data-spy="scroll" data-target="#navbar" data-offset="30">
    
    <div class="nav-menu fixed-top">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <nav class="navbar navbar-dark navbar-expand-lg">
                        <a class="navbar-brand" href="~/Home"><img src="~/images/logo.png" class="img-fluid" alt="logo"></a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation"> <span class="navbar-toggler-icon"></span> </button>
                        <div class="collapse navbar-collapse" id="navbar">
                            <ul class="navbar-nav ml-auto">
                                <li class="nav-item"> <a class="nav-link active" href="#home">HOME <span class="sr-only">(current)</span></a> </li>
                                <li class="nav-item"> <a class="nav-link" href="#features">FEATURES</a> </li>
                                <li class="nav-item"> <a class="nav-link" href="#gallery">GALLERY</a> </li>
                                <li class="nav-item"> <a class="nav-link" href="#pricing">PRICING</a> </li>
                                <li class="nav-item"> <a class="nav-link" href="#contact">CONTACT</a> </li>
                                <li class="nav-item"><a href="#" class="btn btn-outline-light my-3 my-sm-0 ml-lg-3">Download</a></li>

                                <li class="nav-item" data-toggle="modal" data-target="#myModalBot">
                                    <a href="#" class="btn btn-outline-light my-3 my-sm-0 ml-lg-3">Web chat</a>
                                </li>

                            </ul>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </div>

    
    <div class="modal left fade" id="myModalBot" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-body">
                    <iframe style="border:hidden; width:100%;height:300px;" src='https://webchat.botframework.com/embed/botapplication20180524?s=B7ivbsCdRRM.cwA.-R0.PkCid9dZtCpfsW39qklUo-HT_3Be_plu27vCD7iPgMU'></iframe>
                </div>
            </div>
        </div>
    </div>


    @RenderBody()

    <footer class="my-5 text-center">
        
        <p class="mb-2"><small>COPYRIGHT © 2017. ALL RIGHTS RESERVED. MOBAPP TEMPLATE BY <a href="https://colorlib.com">COLORLIB</a></small></p>
        <small>
            <a href="#" class="m-2">PRESS</a>
            <a href="#" class="m-2">TERMS</a>
            <a href="#" class="m-2">PRIVACY</a>
        </small>
    </footer>
    
    <script src="~/js/jquery-3.2.1.min.js"></script>
    <script src="~/js/bootstrap.bundle.min.js"></script>
    
    <script src="~/js/owl.carousel.min.js"></script>
    
    <script src="js/script.js"></script>
</body>
</html>

**Comment by jolienai** [comment]
How is it working on Microsoft Education home page? https://blog.botframework.com/2017/10/11/customize-web-chat-websites

**Comment by EricDahlvang** [comment]
@jolienai It looks like education.microsoft.com no longer has that bot on their page.

I've never used hemify-icons or owl so I haven't duplicated your exact setup, but this works: http://modaldialogbot.azurewebsites.net/

![modalwebchat](https://user-images.githubusercontent.com/11055362/41443240-9017e456-6ff0-11e8-9797-e61a3e8d5593.gif)

**Comment by jolienai** [comment]
Hi Eric,

Thank you very much for sharing it.
