### ISSUE TITLE
[Feature Request] Visual Studio 2017 Project template for Azure Bot Service + Azure Functions C# (v2) ?

### ISSUE THREAD

**Issue by TonyHenrique** [Microsoft/BotBuilder#4681]
Is there a Visual Studio 2017 Project template for Azure Bot Service + Azure Functions C# (v2 , precompiled) ?

I tried to convert the Bot Function App to v(2) precompiled, 
but for example, in Azure Functions v2 uses  `HttpRequest`
but the Bot Function code had `HttpRequestMessage
`

**Can you release a Visual Studio 2017 Project template for Azure Bot Service + Azure Functions C# (v2, precompiled) ?**

**Comment by JasonSowers** [comment]
This is not something that currently exists.  We will take a look at implementing this in the future.

**Comment by JasonSowers** [comment]
After talking to the team, this does not look like something we will likely implement in the future.  However, I will keep the feature request open so it can be reviewed at a later date.

**Comment by TonyHenrique** [comment]
Thanks.
Serverless is trending high. Bots also are trending. I wonder how do develop a more complex bot if not using Visual Studio and precompiled.

It would be nice to be able to use it on Azure Functions (v2, C#, precompiled)

**Comment by JasonSowers** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
