### ISSUE TITLE
Bot is failing to recognize intents always going to default handler

### ISSUE THREAD

**Issue by RPraveen26** [Microsoft/BotBuilder#4684]
Bot was working well but suddenly it stopped working in the way it was. It is not able to react to the inputs and always giving response from the default handler. Got 502 bad gateway error while trying from bot framework hope it is not sync'ing well with LUIS. What is the resolution for this?

**Comment by JasonSowers** [comment]
Are you still experiencing this issue?

**Comment by RPraveen26** [comment]
Hi Jason,

Yes still experiencing the problem. When I hit the bot http endpoint from
LUIS that returns error out of volume quota limit with timeframe. Just
would like to know the exact root cause of the issue.

Thanks
Praveen.

**Comment by JasonSowers** [comment]
I'm not sure of your pricing tier on LUIS but maybe you exceeding these [rate limits](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-boundaries#key-limits) or these  [model boundries](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-boundaries)?

**Comment by RPraveen26** [comment]
Hi Jason,

Yes we have been using F0 free tier, I have been informed by Azure support
that is due to limit exceed. It has resolved now.

Thanks for your follow-up .

**Comment by JasonSowers** [comment]
Glad you figured it out. Good luck!
