### ISSUE TITLE
[Slack] Bot framework not relaying messages from slack

### ISSUE THREAD

**Issue by v46** [Microsoft/BotBuilder#4685]
Folks,

We just started seeing several of our slack bots on the bot framework have stopped responding.

Requests from the bot framework are not coming to our servers that host bot services. SFB looks to be working fine for the same (bot) accounts. Are you aware of a production outage?

We are running 3.11.0 of the Node SDK as a Bot Service (outside Azure). Our bots are migrated and use a custom (in-memory store). We have also configured bot framework to use Slack's event API for (bot framework) integration.

Several of our customers are starting to report these issues now, can you please advise if there are known issues you are tracking?

**Comment by EricDahlvang** [comment]
Thank you for reporting this.  I'll investigate, and get back to you asap.

**Comment by EricDahlvang** [comment]
There appears to be some issue on the Slack side: https://status.slack.com/2018-05/0d2ff93220aa25a3

> **Issues with apps/integrations/APIs and link previews**
> We're investigating reports that apps/integrations, threads and link previews are not working. We're looking into it at this very moment.

I will monitor this, and let you know what I find out.  Please report back here if you notice any changes on your side.

**Comment by v46** [comment]
Thank you @EricDahlvang. We are monitoring as well and will post back.

**Comment by v46** [comment]
@EricDahlvang - things back to normal. You can close this ticket. Thanks.
