### ISSUE TITLE
Frequent "My bot code has an issue." error when running a load test.

### ISSUE THREAD

**Issue by whizlingo** [Microsoft/BotBuilder#4688]
## Bot Info
* SDK Platform: .NET 
* Active Channels: Direct Line, etc. 
* Deployment Environment:Azure App Service

## Issue Description
We are currently trying to run a load test on Bot using the approach [here ](https://blog.botframework.com/2017/06/19/load-testing-a-bot/). Running a simple test with 5 concurrent users is leading to error "My bot code has an issue". Is this due to default state api ?. I just want to call out , we do not have any specific state requirements but the question is "Does Bot internally uses that for managing conversation ?."

**Comment by EricDahlvang** [comment]
Yes, the bot internally uses the default state api to manage dialog state, user data, private conversation data, and conversation data.  Please update your bot to use the Azure Extensions or a custom state client.  reference: **https://blog.botframework.com/2018/04/02/reminder-the-bot-framework-state-service-has-been-retired-what-you-need-to-know/**

**Comment by whizlingo** [comment]
Thanks @EricDahlvang
