### ISSUE TITLE
[Feature Request] Facebook CheckBox Plugin

### ISSUE THREAD

**Issue by TonyHenrique** [Microsoft/BotBuilder#4690]
I am developing a proactive Bot using Azure Functions (V2, C#, Precompiled) using the _Facebook CheckBox Plugin_ to allow my bot to talk to the users
https://developers.facebook.com/docs/messenger-platform/discovery/checkbox-plugin#requirements

I generate the current view ref, and the plug sucessfully renders on the page:
![optin](https://user-images.githubusercontent.com/6307623/40876878-f0ca6f3e-6650-11e8-9fcc-712eae2130fe.png)

**How can I receive the optin _messaging_optins_ webhook from facebook to my Azure Bot Service?**
https://developers.facebook.com/docs/messenger-platform/webhook#setup

On facebook docs it says:

5. Handle the messaging_optins webhook event
After the opt-in event, we will post a webhook event to your server if the checkbox state was checked. This callback has the same format as the opt-in callback, but instead of a sender field, it has an optin object with a user_ref field.
```
{
  "recipient":{
    "id":"<PAGE_ID>"
  },
  "timestamp":<UNIX_TIMESTAMP>,
  "optin":{
    "ref":"<PASS_THROUGH_PARAM>",
    "user_ref":"<UNIQUE_REF_PARAM>"
  }
}
```

6. Send a message with user_ref
After you receive the callback event, you can call the Send API to start messaging the user using the user_ref identifier in recipient as shown below. Note that this field is the same as the unique user_ref param used before when the plugin was rendered and in confirming the opt-in.
```
curl -X POST -H "Content-Type: application/json" -d '{
  "recipient": {
    "user_ref":"<UNIQUE_REF_PARAM>"
  }, 
  "message": {
    "text":"hello, world!"
  }
}' "https://graph.facebook.com/v2.6/me/messages?access_token=<PAGE_ACCESS_TOKEN>" 

```
On success, the Send API will respond with a message_id:
```
{
  "message_id": "mid.1456970487936:c34767dfe57ee6e339"
}
```

**Comment by EricDahlvang** [comment]
Facebook Feature Requests are tracked in this issue: https://github.com/Microsoft/BotBuilder/issues/4360
