### ISSUE TITLE
[Skype For Business] Skype for Business could not reach the bot. Please contact admin of the bot for help.

### ISSUE THREAD

**Issue by waqas-zia-confiz** [Microsoft/BotBuilder#4692]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.15
* Active Channels: Skype For Business
* Deployment Environment: Local Environment with the emulator and ngrok

## Issue Description
When trying to chat with Skype for business BOT I get, "Skype for Business could not reach the bot. Please contact admin of the bot for help." error sometimes. It usually happens on the first message and after that, it works normally. I have tried debugging this issue with ngrok but in such cases, I receive this message even before I get an activity locally. It is working fine on other channels such as web chat.

## Reproduction Steps
1. Setup Skype for Business channel for your BOT.
2. Start a conversation with the BOT.

## Expected Behavior
BOT should reply normally as it does in local and webchat environment.

## Actual Results
We get, "Skype for Business could not reach the bot. Please contact admin of the bot for help." error message.

**Comment by waqas-zia-confiz** [comment]
Is there any update on this?

**Comment by waqas-zia-confiz** [comment]
Any updates?

**Comment by furkankatman** [comment]
I am now having this too ? Any updates friends?

**Comment by JasonSowers** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
