### ISSUE TITLE
Web chat channel - parameters 

### ISSUE THREAD

**Issue by Jagan-rajan** [Microsoft/BotBuilder#4697]
## Bot Info
* SDK Platform:  .NET 
* Active Channels: Webchat
* Deployment Environment:  Azure Bot Service
##Question
I have a question regarding webchat channel since direct line is not exactly needed in my project since i need to embed the channel to my website.
My req. is to pass user name and user id to the bot code not just the channel. Any ways of getting that done. If yes, can you please share the sample code which will be very helpful.

**Comment by EricDahlvang** [comment]
WebChat uses directline internally.  There are some examples of embedding webchat on a page, and providing the userid and username here: https://github.com/Microsoft/BotFramework-WebChat/blob/master/samples/fullwindow/index.html

**Comment by Jagan-rajan** [comment]
Can you please let me know how can i retrieve he parameters in the bot code. 

Note : I am using .Net as my base to build the bot.

**Comment by compulim** [comment]
We have a [feature request](https://github.com/Microsoft/BotFramework-WebChat/issues/832) on Web Chat for sending message to bot without user typing anything. That would fit this case.

@Jagan-rajan can you post a comment over there about your scenario so we can track it down while we are doing the revamp work?

**Comment by EricDahlvang** [comment]
Parameters are not sent with messages.  However, you can use the BackChannel and send information from the client to the bot in a custom event or message: https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-backchannel?view=azure-bot-service-3.0
