### ISSUE TITLE
context.Wait() is not waiting in the loop when I am trying to get the user input in for loop

### ISSUE THREAD

**Issue by adarshpatel30** [Microsoft/BotBuilder#4699]
I am trying to set few values in my list for example and trying to iterate that list.
For every iteration I am doing context.PostAsync("list_element"); in foreach loop.
for that post async I want the user to enter a value.
lets say I have a list of pizza attributes {type,size,topping}
I want to display type(which is first element) and want user to input veg or non veg
Next I want to display size and get the user's input like large or small and  so on for all the remaining elements of that list.
I wrote another function for the same and I am trying to call it for every iteration in foreach loop for all the values of list.
But context.wait() is not working as expecting.
It is displaying every list values available and not even waiting for user's input

**Comment by EricDahlvang** [comment]
context.Wait(methodname) is not a wait handle, as in multi-threading.  But, it is a 'continuation delegate' that allows execution of the next message to resume at the wait method.  More information can be found here: https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-dialogs?view=azure-bot-service-3.0#implementation-details
