### ISSUE TITLE
When a user deletes conversation and restart, session stay in the state of previous conversation

### ISSUE THREAD

**Issue by Winangel** [Microsoft/BotBuilder#470]
When I delete a conversation with my chatbot on facebook messenger while I am in a specific dialog and I start a completely new conversation, I would like the bot to start over from the beginning.

For now, if I start a new conversation, The bot is restarting at the point where I left.

This seems awkward to me as the action of deleting the conversation is an equivalent of uninstalling an application and should bring me back to the beginning of the experience.

**Comment by msft-shahins** [comment]
how do you delete the conversation? are you using `/deleteprofile` command to restart the conversation?

**Comment by Winangel** [comment]
Hi,

In fact, in my use case, the user deletes the conversation from facebook messenger (he does not send any request to /deleteprofile).
The thing I want to know is if the user actually removes the conversation from facebook messenger, then I could trigger the /deleteprofile command.

**Comment by msft-shahins** [comment]
Currently Facebook messenger platform doesn't fire `delete conversation event` through send API when the user deletes a conversation. You should educate users to use `/deleteprofile` or a custom command that you introduce for your bot, to delete their profiles and historic data with your bots.

**Comment by seb0zz** [comment]
@msft-shahins do you know if that's still an issue or does facebook send any event on deleting conversions now?

**Comment by msft-shahins** [comment]
@seb0zz I cannot see any changes on the Facebook side by skimming through their documentation.
