### ISSUE TITLE
Generic Oauth 2 provider results in Bad Request to bot token service

### ISSUE THREAD

**Issue by ukphillips** [Microsoft/BotBuilder#4703]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.15.2.2
* Active Channels: DirectLine, WebChat
* Deployment Environment: Azure Bot Service, Azure App Service, local development with Emulator

## Issue Description
I have configured a custom OAuth2 provider using the Generic OAuth 2 settings in the Azure portal for the bot:

![image](https://user-images.githubusercontent.com/18452981/40992757-a7449692-68c5-11e8-9acc-a74243fa30a5.png)

When I test the connection I get a Bad Request result. After watching fiddler a bit here is the flow when I click test connection:

https://token.botframework.com/api/oauth/signin?settingId=eae8dfc7-3d85-f12d-80c2-449848325ea9_f2d80ad0-9766-d588-1a57&redirectUri=https%3a%2f%2ftoken.botframework.com%2fapi%2foauth%2fPostTestConnectionCallback%3fstate%3dew0KICAiY29ubmVjdGlvbk5hbWUiOiAiQ3VzdG9tSWRhIiwNCiAgImNvbnZlcnNhdGlvbiI6IHsNCiAgICAiYm90Ijogew0KICAgICAgIm5hbWUiOiAidGluYWhyY21ib3R3YWJhIg0KICAgIH0NCiAgfQ0KfQ%3d%3d%26userId%3d0b2da555-8362-800a-b6af-b575437c39b7

which results in a 302 directing me to:

https://token.botframework.com/.auth/web/login/eae8dfc7-3d85-f12d-80c2-449848325ea9_f2d80ad0-9766-d588-1a57?redirect_uri=https%3a%2f%2ftoken.botframework.com%2fapi%2foauth%2fPostTestConnectionCallback%3fstate%3dew0KICAiY29ubmVjdGlvbk5hbWUiOiAiQ3VzdG9tSWRhIiwNCiAgImNvbnZlcnNhdGlvbiI6IHsNCiAgICAiYm90Ijogew0KICAgICAgIm5hbWUiOiAidGluYWhyY21ib3R3YWJhIg0KICAgIH0NCiAgfQ0KfQ%3d%3d%26userId%3d0b2da555-8362-800a-b6af-b575437c39b7

which results in a 302 directing me to my auth server:

https://REDACTED.azurewebsites.net/connect/authorize?client_id=REDACTED&response_type=code&redirect_uri=https%3a%2f%2ftoken.botframework.com%2f.auth%2fweb%2fredirect&scope=openid+profile&state=349973cee4d44b44bb62148e4fb5020a

Once I authenticate on the identity provider as is typical I navigate back to the caller with the authorization code - but the bot framework results in a bad request result:

https://token.botframework.com/.auth/web/redirect?code=943b2e3d77a8d111f3ef5948fba2c35e474cf27d612a8df243f4330b2b983f63&scope=openid%20profile&state=349973cee4d44b44bb62148e4fb5020a&session_state=mjxV4KUwd9uwLpAph-FtMJmKN3SJRSwmieknDnJ2uy8.76ee7ff6f6217b96c22738b89a7e5da8

I also tried this with my emulator pointing at the remote service and had the same result to make sure it was not a bug with the test functionality.

## Code Example
N/A

## Reproduction Steps
1. Configure a Generic OAuth 2 provider in bot service 
2. Test Connection 

## Expected Behavior
Authentication to be successful

## Actual Results
Bad result is returned

**Comment by JasonSowers** [comment]
Are you using AAD v2 as your provider?

**Comment by JasonSowers** [comment]
Glad you got this working, Good luck!

**Comment by anjireddy543** [comment]
>The underlying issue was using IdentityServer4 with a client secret that was not hashed on the server side, which all token requests expect to match the client secret with a hashed version.

Hi, I am also getting similar problem but i didnt get exactly how you are doing(based on above sentence).
I have posted my query in stackoverflow(https://stackoverflow.com/questions/53606838/bad-request-while-authenication-in-bot-sdk4-using-own-generic-oauth-2-connection). Please help me out.

**Comment by arkiaconsulting** [comment]
I’m having the same issue with bad request. Looking at the IdentityServer logs, the token endpoint is never called. Could this be due to the fact that the SSL certificate for the IdentityServer I use is self-signed ?
