### ISSUE TITLE
[Node.js SDK] Vulnerable Dependencies: jsonwebtoken and base64url

### ISSUE THREAD

**Issue by naugtur** [Microsoft/BotBuilder#4706]
## Bot Info
* SDK Platform: Node.js
* SDK Version: 3.15.0
* Active Channels:  MS Teams
* Deployment Environment: any

## Issue Description
Vulnerabilities in dependencies are listed by npm audit
jsonwebtoken requires an update by a major version
base64url requires an update

## Reproduction Steps
npm i botbuilder
npm audit

## Expected Behavior
audit passes with everything ok

## Actual Results
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Prototype pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ hoek                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ > 4.2.0 < 5.0.0 || >= 5.0.3                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ botbuilder                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ botbuilder > jsonwebtoken > joi > hoek                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/566                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Prototype pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ hoek                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ > 4.2.0 < 5.0.0 || >= 5.0.3                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ botbuilder                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ botbuilder > jsonwebtoken > joi > topo > hoek                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/566                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Out-of-bounds Read                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ base64url                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=3.0.0                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ botbuilder                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ botbuilder > base64url                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/658                       │
└───────────────┴──────────────────────────────────────────────────────────────┘

**Comment by stevengum97** [comment]
@naugtur thanks for reporting this, I'll look into it and see if we can't bump the versions without any problems 😄

**Comment by jesus-seijas-sp** [comment]
Hello @stevengum , can we have an estimation of when https://github.com/Microsoft/BotBuilder/pull/4715 will be merged? Has been 2 months there, and the problem is that right now when you install botbuilder a warning appears

![image](https://user-images.githubusercontent.com/15154218/43716856-e319d81c-9985-11e8-82b7-984e1e954e92.png)

And well, when you have npm audit and nsp in the CI pipeline, today there is no way to deploy a chatbot using any version of botbuilder, so it's becoming a blocking issue.

**Comment by naugtur** [comment]
As a workaround to continue running audit in CI while depending on this, I ended up building https://www.npmjs.com/package/npm-audit-resolver and my team uses it now for maintaining over 20 apps.

**Comment by jesus-seijas-sp** [comment]
Thank you @naugtur , it's a great tool. I see that is also proposed as RFC at npm, and I see that both kat and ljharb are on it. That's great :)

**Comment by stevengum** [comment]
@jesus-seijas-sp, @naugtur, really sorry about the delay regarding this; #4715 was finally merged! @stevenic is out atm, but once he gets back we should have a new release shortly. Closing this issue.
