### ISSUE TITLE
[Bot Framework, Messenger]FB Messenger does not give review to my bot

### ISSUE THREAD

**Issue by ShadeyCN** [Microsoft/BotBuilder#4707]
Hello Everybody

I sent my bot framework to Messenger Channel to review a week ago, I don't have response still
How can I get Facebook to review my bot? I need to release it...

I am writing this from Mexico

**Comment by stevengum97** [comment]
Please contact the [Facebook Messenger bot review team](https://developers.facebook.com/docs/messenger-platform/app-review), as their review process is separate from ours.

Closing issue as this will be resolved by Facebook.
