### ISSUE TITLE
[.NET SDK, Facebook, Direct Line] Get filename of received attachments?

### ISSUE THREAD

**Issue by kofarrell1076** [Microsoft/BotBuilder#4708]
HI all,
Running this on .net with 3.15.2.2 installed. 
Any way to get the filename of the attachment - attachment.name is  always null coming from facebook and directline.

thanks

**Comment by JasonSowers** [comment]
Unfortunately, Facebook does not provide the file name for us to get the name from as you can see in their [API documentation](https://developers.facebook.com/docs/messenger-platform/reference/webhook-events/messages) the only values they are providing are type and URL.  So you will have to set a file name in your code.

As for directLine could you please share your client implementation so we can take a look and try to help?

**Comment by kofarrell1076** [comment]
Ah ok. Yes that's what we're doing now.  We're testing the directline again tomorrow on attachments and will come back.
thanks

**Comment by JasonSowers** [comment]
@kofarrell1076 Any luck with directLine?

**Comment by kofarrell1076** [comment]
Got Directline working - Our fault. Blame the dev. Do have an issue with sending attachements on facebook and long azure storage sas links but need to test a little more to narrow it down.

**Comment by JasonSowers** [comment]
@kofarrell1076 were you able to figure this out, or are you still having issues?

**Comment by kofarrell1076** [comment]
Facebook incoming is sorted (we generate a filename). Directline is working.
