### ISSUE TITLE
[.NET SDK, AADv1] Problems when testing out the AADv1 Auth Sample

### ISSUE THREAD

**Issue by Rykimaruh** [Microsoft/BotBuilder#4709]
I have been following the Microsoft tutorial [here](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-authentication?view=azure-bot-service-3.0#create-your-bot-and-an-authentication-application) and I used "AADv1" connection as sample.

I don't know if anyone has read or done this article demo before, however I feel there are some things not clear in it.

When I run the bot, there are two things don't seem to fully work and they are:

1. Retrieving the mails from last 30 mins
2. Displaying logged in user information

1. Retrieving the mails from last 30 mins
When I type "recents", the bot only displays an adaptive card with the "Here are all of your unread Inbox emails from the last 5 minutes:" message only. There are functions in the source code to show any mail in the last 30 mins and yet nothing appears. Perhaps I'm missing something or misunderstanding?

2. When I try to write "me" to display my information, the bot emulator only displays "Response code 500 (Internal Server Error) " with "Sorry, my bot code is having an issue". It feels like there is no connection to Azure AD?

The only task the bot is able to do is send an email message on the logged in user's behalf.

[AADv1 Root Dialog](https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Samples/AadV1Bot/Dialogs/RootDialog.cs). 

Lines 46 and 66 are the calls to "recents" and "me" respectively. 

Functions related to finding recent mails:
Line 95 is `private GetTokenDialog CreateGetTokenDialog()`
Line 107 for `ListRecentMail(IDialogContext context, IAwaitable<GetTokenResponse> tokenResponse)`

[The SimpleGraphClient class](https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Samples/AadV1Bot/SimpleGraphClient.cs)

[The web.config file](https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Samples/AadV1Bot/Web.config)

Anyone know that's up?

**Comment by JasonSowers** [comment]
Thanks for reporting this, we will investigate.

**Comment by Rykimaruh** [comment]
I would like to update this issue saying that I was able to get "recent" working. I am able to see unread emails from the last 30 minutes. 

However I am still having problems when typing "me", still getting the same error.

**Comment by Jeffders** [comment]
Have you stepped through the code to see that you are getting an access token? That would be the first thing I'd check because there isn't a lot of error handling in the sample. I'd be curious if you do get an access token if you get an exception when trying to call into the graph api, or if the issue is that you are just not receiving a token.

**Comment by Rykimaruh** [comment]
Yes, I do get an access token to authenticate and I am able to send email or see my unread emails, however the bot doesn't let me see who i am and who i report to

**Comment by ukphillips** [comment]
@Rykimaruh can you post the contents of that token in here. I want to make sure the scopes are correct in the token. Perhaps this is just missing one of the scopes?

**Comment by ukphillips** [comment]
@Rykimaruh a 6 digit number sounds like the magic code issued from the token service. The Token should be a JWT in the form of:

eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c

You should be able to see it when debugging here:
```
private async Task ListMe(IDialogContext context, IAwaitable<GetTokenResponse> tokenResponse)
        {
            var token = await tokenResponse;
            var client = new SimpleGraphClient(token.Token);

            var me = await client.GetMe();
            var manager = await client.GetManager();

            await context.PostAsync($"You are {me.DisplayName} and you report to {manager.DisplayName}.");
}
```

by inspecting token.Token

**Comment by Rykimaruh** [comment]
@ukphillips 

Would you like me to send it privately or something? I am not sure if posting the token that gives personal info like email and other things related would be ok in a public forum.

However, do let me know if it's ok or safe to do so, just wanted to be careful of posting info that pay show personal info.

**Comment by ukphillips** [comment]
@Rykimaruh fair enough, can you decode it and redact the sensitive information for posting? Really I'm just interested in the claim types and the scopes it contains - both of which should be insensitive data.

**Comment by Rykimaruh** [comment]
`{
  "typ": "JWT",
 }`

---------------

{

  "scp": "email Mail.Read Mail.Send profile User.Read",
  
}

is t his enough? let me know

**Comment by Rykimaruh** [comment]
i take this was not enough information?

**Comment by Rykimaruh** [comment]
@JasonSowers , yeah I still do. I've yet to receive any additional information regarding as to why the "me" function doesn't work and just gives the error

**Comment by JasonSowers** [comment]
@Rykimaruh sorry for the delay, I am looking into this today and trying to troubleshoot for you.  Right now I am blocked by a tenant issue, but will hopefully have something for you later today.

**Comment by Rykimaruh** [comment]
@JasonSowers wel, they are two different issues within same bot, not sure if I should consolidate it into one  issue or have them apart to tell the different issue type.

**Comment by JasonSowers** [comment]
Ok we will reopen this one.  

I'm not sure where you are seeing the "Unread email from the last 5 minutes" from. I am seeing 30 minutes everywhere. 
in the bot:
![image](https://user-images.githubusercontent.com/6301037/42538848-fb9ba976-844d-11e8-8716-2e7ab33647c7.png)

in the code : 
```cs
    Text = "Here are all of your unread Inbox emails from the last 30 minutes:",
```
```cs
    DateTime from = DateTime.Now.Subtract(TimeSpan.FromMinutes(30));
```
```cs
    if (message.ReceivedDateTime.HasValue && message.ReceivedDateTime.Value >= from)
```

The "recents" command is working fine for me and I cannot find anything that references 5 minutes rather than 30 minutes.  Could you please add more detail here?

For the "me" command, I am seeing the same issue you are.

![image](https://user-images.githubusercontent.com/6301037/42539243-632f2d00-844f-11e8-9095-10e6a415708b.png)


I wrapped the `ListMe` function's code in a try catch and got this error:

> Code: Authorization_RequestDenied
Message: Insufficient privileges to complete the operation.
Inner error

Could you please add a try catch and confirm you are getting the same error? Thie is all I did:

```cs
        private async Task ListMe(IDialogContext context, IAwaitable<GetTokenResponse> tokenResponse)
        {
            try
            {
                var token = await tokenResponse;
                var client = new SimpleGraphClient(token.Token);

                var me = await client.GetMe();
                var manager = await client.GetManager();

                await context.PostAsync($"You are {me.DisplayName} and you report to {manager.DisplayName}.");
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
        }
```


  I will investigate this further. As this should be working out of the box as per the walkthrough instructions.

**Comment by JasonSowers** [comment]
If you update your AADv1 app to include the `read all user' basic profiles ` permissiong the "me" command should work as well.

**Comment by Rykimaruh** [comment]
@JasonSowers  i will check it out and update as soon as I can

**Comment by Rykimaruh** [comment]
@JasonSowers 

**Update:** So I tested the new pushed version and I can confirm that the cached token does work correctly. I tested with asking to send email or check recent emails after initial sign in and it doesn't ask me for sign in again as it is recognizing previous token cached. 

This is more of a question, but because I am in wifi (does the cached token stay as long as my O365 session? For example I have it that i only can last 8 hours before I have to re-sign in to my O365 account using MFA. Is the token lifecycle similar? I'm assuming that if I'm connected with SSO in my workspace LAN it won't require even a login). 

On the other hand, I tried the "me" command it still gives me the same error. The message is the same: not enough privileges for some odd reason. Does it have to with using emulator and not some "authenticated" channel? 

I used fiddler to determine the exact error message and it's this:
`{"Message":"An error has occurred.","ExceptionMessage":"Code: Authorization_RequestDenied\r\nMessage: Insufficient privileges to complete the operation.\r\n\r\nInner error\r\n","ExceptionType":"Microsoft.Graph.ServiceException","StackTrace":"   at Microsoft.Graph.HttpProvider.<SendAsync>d__19.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown --.`

Upon closer inspection it makes me think it has to do MS Graph. Could it be the App registered in the AD?

**Comment by JasonSowers** [comment]
I did 100% of my testing in the emulator, so this will all work completely fine in the emulator.  I will hae to ask about the token timeout.

Yes the AAD app needs this permission added to it: read all users' basic profiles 

![image](https://user-images.githubusercontent.com/6301037/42548295-4efaa1e4-847b-11e8-94b2-6fc7f88e6788.png)

make sure to grant permissions after you save:

![image](https://user-images.githubusercontent.com/6301037/42548344-7792ce74-847b-11e8-9af3-a2d17998255c.png)

After you have enabled this permission, make sure to sign out of the sample so it forces you to sign back in.  You can sign out by simply typing signout

**Comment by JasonSowers** [comment]
Glad we could get this working for you.  I have also had the docs team submit an update to the walkthrough you were using to include that permission in the list of permissions.  Hopefully, it will help others.  Apologies that it took so long to get a response from us, thank you for being so patient.

**Comment by JasonSowers** [comment]
@Rykimaruh For tokens,  when you sign in you get 2 tokens a sign in token and a refresh token.  The refresh token duration is set by your tenant admin, so I am unable to tell you how long that will last.  The sign in token lasts 1 hour but will be refreshed without having to sign in again while your refresh token is still valid.

**Comment by prarthanaC** [comment]
@JasonSowers I have used only "me " part from AADv1 sample bot.Everything works fine except that it displays the user information till the user signs out.Even if I refresh the bot in emulator,it is directly saying "you are xxxxx" without asking for Sign In .Please help


Please refer to the below code:

rootdialog.cs

 private GetTokenDialog CreateGetTokenDialog()
        {
            return new GetTokenDialog(
                              ConnectionName,
                              $"Please sign in to {ConnectionName} to proceed.",
                              "Sign In",
                              1,
                              "Hmm. Something went wrong, let's try again.");
        }
public static async Task Signout(IDialogContext context)
        {
            await context.SignOutUserAsync(ConnectionName);
            await context.PostAsync($"You have been signed out.");
        }
       
    private async Task ListMe(IDialogContext context, IAwaitable<GetTokenResponse> tokenResponse)
        {
           var token = await tokenResponse;
          

            var client = new SimpleGraphClient(token.Token);

            var me = await client.GetMe();
 await context.PostAsync($"Hi {me.DisplayName},you have successfully signed in.Please proceed. .");
}
