### ISSUE TITLE
[.NET SDK] Send Message while loop is executing. 

### ISSUE THREAD

**Issue by Daddymarto01** [Microsoft/BotBuilder#4713]
## Bot Info
.NET 
facebook ,skype
 

## Issue Description
Is it possible for bot to listen to messages while a loop is being executed?
I am working on a taxi bot and  trying  to give multiple options for my bot to check status or cancel ride whilst executing a loop which responds on status of ride.  

## Code Example

```cs
int prev = 2; 
    while (prev <= 5)
    { 
        int ride_status =prev; 
        context.UserData.TryGetValue<int>("ride_status", out ride_status); 
        string trip_status = CheckTripStatus(res[3].ToString()); 
        prev = ride_status;
        int current = Convert.ToInt32(trip_status);
        
        if (prev!=current)
        { 
            if (current == 2)
            {
                reply.Text = "Your driver is coming to pick you.";

                await context.PostAsync(reply); 
                context.UserData.SetValue<int>("ride_status",current);
            }
            else if (current == 3)
            {
                reply.Text = "Your driver has arrived.";
                await context.PostAsync(reply); 
                context.UserData.SetValue<int>("ride_status", current);
            }
            else if (current == 4)
            {
                reply.Text = "Your trip has started.";
                await context.PostAsync(reply); 
                context.UserData.SetValue<int>("ride_status", current);
            }
            else if (current == 5)
            {
                reply.Text = "Your trip has ended.";
                await context.PostAsync(reply); 
                context.UserData.SetValue<int>("ride_status", current);
                break; 
            }
            else
            {
                StatusOption(reply);
                context.Wait(StatusSelected); 
            } 
        } 
        Thread.Sleep(5000);
    }
```

## Reproduction Steps
The bot checks trip status using the CheckTripStatus function and returns results which are compared for the next postasync action to happen.
 
## Expected Behavior
I expect in the course  of the loop, I should be able to post something to the bot and make it interpret  and return a response whilst the loop is still executing. 

## Actual Results
The bot only takes new commands after stage 5 where I break when the result I wanted is achieved.

**Comment by stevengum97** [comment]
Closing this issue as a duplicate exists on StackOverflow.  

https://stackoverflow.com/questions/50739814/send-message-to-chat-bot-when-while-loop-is-executing
