### ISSUE TITLE
[.NET SDK, Azure Bot Service] Web chat channel - Rest API service calls don't work on Azure

### ISSUE THREAD

**Issue by Jagan-rajan** [Microsoft/BotBuilder#4717]
## Bot Info
* SDK Platform: >.net
* Active Channels: Web Chat
* Deployment Environment:  Azure Bot Service

## Issue Description
I have developed a bot which is embedded using a web chat channel. I wanted to call a Web API service method. It is all working fine in emulators and local code. But if i publish my bot code to Azure the Web api service call is not working. Can you please help here?. Am i missing something basic.?

**Comment by stevengum97** [comment]
Can you provide the code you're using, and the version of the SDK?

**Comment by ddo88** [comment]
same problem here

**Comment by stevkan** [comment]
Closed due to lack of response.
