### ISSUE TITLE
[Question, .NET SDK] Azure Function Bot with SDK v4

### ISSUE THREAD

**Issue by Beliaz** [Microsoft/BotBuilder#4719]
## Bot Info
* SDK Platform: .NET
* SDK Version: v4.0.1-preview
* Active Channels: -
* Deployment Environment: local development with Emulator, Azure Functions Core Tools v2

## Issue Description
Is it possible to create a Azure Function Bot with the v4 SDK? I tried to build a Azure Function using the Visual Studio tempalte for compiled C# functions and the adapted sample code for v3 but since Microsoft.Bot.Builder.Azure.BotService is not available in the v4 Microsoft.Bot.Builder.Azure package it does not work. I see that there are fundamental differences between v3 and v4 but I could not find any sample which shows how to use the new SDK to build a Azure Functions Bot with the Visual Studio template. Every .NET sample for v4 requires a ASP.NET Core web application which obviously does not apply for Azure Functions. 

Finally if there is no way to use Azure Functions with v4 is there some kind of workaround to use v3? Or are there no plans for Function Bots going forward?

Related: #4681

**Comment by stevengum97** [comment]
Sorry @Beliaz, can you ask your question in the [botbuilder-dotnet](https://github.com/Microsoft/botbuilder-dotnet/issues) repo? The v4 devs and activity take place there, so you're more likely to quickly receive the assistance you're looking for.

Closing issue.
