### ISSUE TITLE
Using Json to Create FormDialog

### ISSUE THREAD

**Issue by wjvii** [Microsoft/BotBuilder#472]
I am trying to build user and conversation specific dialogs using json schema and I have the LINQ queries generating the json perfectly. If I save a sample of the json to disk and use it like the annotatedsandwich example where it is read from a file on disk, it works great. The json is unique per user and conversation and instead of writing to disk I want to use it in memory. I do not see how to pass the json string or JObject to the BuildJsonForm method or alternately how to get the userID information in the BuildJsonForm method in order to generate the json based on the user and conversation. I know I am missing something that will let me do this but I am not finding it. Any assistance with how this should be done would be appreciated. Thank you.

**Comment by willportnoy** [comment]
Some options come to mind:

1. Configure the Autofac container with the reflection surrogate serializer.
2. Resolve your root FormDialog<T> from the Autofac container, and provide it with a BuildFormDelegate<T> from the container as well.  For example, your BuildFormDelegate<T> might look at the Message's from user id to pick which json schema to use.  This is a recent commit for a test that shows resolving a root dialog from the container: https://github.com/Microsoft/BotBuilder/commit/28213255d53813699964f1844f8b66e265974941

I'll see if I can find a example for number 2.

**Comment by willportnoy** [comment]
I just pushed commit https://github.com/Microsoft/BotBuilder/commit/c0d9acaf2f0eba760b98789b3953fa0bbbe17470 to show a particularly complicated scenario where you might want the BuildJsonForm to depend on properties of the Message, and you were willing to resolve your root dialog through the Autofac container.

You might find that you can still accomplish your scenario in a simpler way with

1. an implementation of BuildJsonForm that was a static method and didn't capture the environment and therefore could be trivially serialized
2. delegate methods based to IForm's fields that did capture something from the environment that helped you define a more dynamic form.

In additional, there's still option 1 above, though you run the risk that the automatic serialization may include large portions of your state, captured through the environment closure.

@chrimc62 may have more ideas.

**Comment by wjvii** [comment]
Will thank you so much for the sample yesterday. I thought I had it figured out after reviewing it but apparently not. I took your example and created what I believe is a container with the form and then I tried several different ways to get an instance of that form and use it to create the dialog but none worked as expected so I think I am just trying to build the dialog from the container incorrectly. Should I be using the FormDialog.FromForm and the scope resolved BuildFormDelegate<JObject> or am I going down the wrong path? Thank you!

**Comment by willportnoy** [comment]
Is your form dialog the root dialog?  If so, the IPostToBot middleware will create the root dialog instance when the conversation state is new, by asking the container for the Func < IDialog < object > > factory, which will satisfy its BuildFormDelegate dependency from the container, which can follow whatever dynamic data-dependent logic you like.

**Comment by willportnoy** [comment]
I'm going to close this item for now, but feel free to open a new item if you have any more questions.
