### ISSUE TITLE
[.NET SDK] Need Help changing currency sign in receipt card and do more customization.

### ISSUE THREAD

**Issue by Daddymarto01** [Microsoft/BotBuilder#4720]
## Bot Info
.NET
faceboook
azure, emulator

## Issue Description
I can not remove tax from receipt.  i also can not change currency from usd.

## Code Example
  CardAction pbv = new CardAction()
            {
                Value = "Check Status",
                Type = "imBack" 
            };

            ReceiptCard plCard = new ReceiptCard()
            {
                Title = "Little Live Fare",
                Items = new List<ReceiptItem>
  {

      new ReceiptItem("TRIP STATUS",subtitle:status, image: new CardImage(url: img_url)),

},
                Total = res[13],
                //Tax = res[15],
                Tap = pbv
               

            };
 return plCard.ToAttachment();

## Reproduction Steps
1. The user prompts receipt which populates values as shown
 
## Expected Behavior
I dont want to see the tax as well as the dollar sign on published version.
 

## Actual Results
dollar sign persists and tax still showing

**Comment by JasonSowers** [comment]
Could you please post the JSON that is being sent to the emulator from your bot so we can take a look?

**Comment by JasonSowers** [comment]
I just realized you were talking about Facebook, I saw emulator and assumed that's where you were having trouble.  It looks like on the facebook end they make all these changes, let me look for a workaround.

**Comment by owen-sammut** [comment]
Hi Jason,

Im experiencing the same issues

**Comment by JasonSowers** [comment]
@Daddymarto01 @owen-sammut I am going to respod to the StackOverflow question as it is easier for people to find. https://stackoverflow.com/questions/50759325/change-default-currency-to-preferred-currency-in-receipt-card-bot-framework

**Comment by JasonSowers** [comment]
Answer posted

**Comment by Daddymarto01** [comment]
This was so helpful @JasonSowers . Currency issue is fixed now and tested on all channels
