### ISSUE TITLE
[Question, DirectLine] Microsoft.Rest.SerializationException: Unable to deserialize the response.

### ISSUE THREAD

**Issue by Kartik1607** [Microsoft/BotBuilder#4724]
Hi, during log analysis we found that we  were getting lots of `Microsoft.Rest.SerializationException: Unable to deserialize the response.` on 1 June 2018 on the directline channel..  Timestamp : 2018-06-01T20:10:29.9738394Z

Was bot service down during that time? Was it from Microsoft end or on our end?

**Comment by JasonSowers** [comment]
Can you please provide a conversation ID, channel, and time range?

**Comment by Kartik1607** [comment]
It happened on 1 June on lots of conversations. Some of the id's are
* 6iWVu4Imyc0BYgSpmRXu7n - 2018-06-01T19:50:56.2583326Z
* G9ulqyzmOSID9A6tqCjXcP - 2018-06-01T19:51:54.711801Z
* I2TYtc9F1ZKFvXaydCiGMc - 2018-06-01T21:01:01.1870446Z
* DnzJguQILQLBDXw1O4Agev - 2018-06-01T21:01:31.2501516Z
* CUZ8Bsyds1iAF9SBiED6vI - 2018-06-01T21:06:42.6035772Z
* 9GgREiA46po32RV2v5KIdm - 2018-06-01T22:52:54.1930937Z

The channel is directline.

**Comment by JasonSowers** [comment]
Thanks, we will take a look

**Comment by JasonSowers** [comment]
Sorry that it took so long to get back to you, there was no outage on June 1st.
