### ISSUE TITLE
How to call BestResultFrom from an overrided MessageReceived's LuisDialog?

### ISSUE THREAD

**Issue by WillRock19** [Microsoft/BotBuilder#4725]
## Bot Info
* SDK Platform: .NET 
* SDK Version: 3.15.2.2 

## Issue Description
I want to my bot to look out for luis intention result and, if the score is bellow a given number (like, 0.5), it will generate a promptDialog asking the user if "that's really what he means". So, I've look at this git issue (https://github.com/Microsoft/BotBuilder/issues/3757) and got some ideas about how to do it... but when I'm overriding the MessageReceived, I have no clue of how to instantiate a LuisResult to send to **BestResultFrom** method. Can you help me out, please?

**Comment by ukphillips** [comment]
If you are extending the LuisDialog object, you should get the LuisResult for free:

https://github.com/Microsoft/LUIS-Samples/blob/master/documentation-samples/tutorial-web-app-bot/csharp/BasicLuisDialog.cs

You may need to initialize the LuisService with a lower threshold to allow for less confident results to come back. (In the sample they are not setting a value on the LuisService constructor)

**Comment by nyxsys** [comment]
Just to build on what the previous commentor said, here's what the call to the constructor looks like in my LUIS bot to get low-threshold intents:
       ```
 public BasicLuisDialog() : base(new LuisService(new LuisModelAttribute(
            ConfigurationManager.AppSettings["LuisAppId"], 
            ConfigurationManager.AppSettings["LuisAPIKey"], 
            domain: ConfigurationManager.AppSettings["LuisAPIHostName"], threshold: 0.001)))
        {
        }
```

And to actually check if a low scoring intent won, it might look something like this:

```
public async Task somethingIntent(IDialogContext context, LuisResult result)
        {
            if(result.Intents[0].Score < threshold)
            {
                //do low threshold warning stuff
            }
            await this.ShowLuisResult(context, result);
        }
```

If you'd still like to work on the BestResultFrom approach, I can dig further into that to help you there.
