### ISSUE TITLE
Microsoft Bot Framework Queries

### ISSUE THREAD

**Issue by imailer2015** [Microsoft/BotBuilder#4726]
## Bot Info
* Active Channels: MS Teams

## Issue Description

1. What is the max / ideal message size of the message Microsoft bot connector sends to the chat bot ?
2. What is the maximum number of connections Microsoft Bot Framework allows ?
3. What is the maximum number of messages (message per minute / sec) that is permitted by Microsoft Bot Framework ?
4. How does app-id behave when a bot / resource is deployed for multiple data centers ? (Is app id specific to the data center?)

**Comment by nyxsys** [comment]
What is the max / ideal message size of the message Microsoft bot connector sends to the chat bot?

There is no set limit within the bot framework itself, however as you've mentioned this is dependent on the channel connector itself. In your case, with respect to Microsoft teams the documentation on message length can be found [here](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams#messaging) 

What is the maximum number of connections Microsoft Bot Framework allows ?

Aside from the throttling mentioned in the answer to the next question, there is no set or official connection limit currently. Discussion on this can also be found [here](https://github.com/Microsoft/BotBuilder/issues/1250)

I'd like to note that the free tier allows for 10k messages a month, with the bot shutting down after that, however there is not a concurrent connection limit set on how these are used.

What is the maximum number of messages (message per minute / sec) that is permitted by Microsoft Bot Framework ?

Taken from [this documentation](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-send-and-receive-messages?view=azure-bot-service-3.0#send-message)

"The Bot Framework does not impose any restrictions on the number of messages that a bot may send. However, most channels enforce throttling limits to restrict bots from sending a large number of messages in a short period of time. Additionally, if the bot sends multiple messages in quick succession, the channel may not always render the messages in the proper sequence."

With respect to rate limiting in MS teams in particular, this is in flux so the reccomendation is to follow the documentation [here](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/general/rate-limit)

How does app-id behave when a bot / resource is deployed for multiple data centers ? (Is app id specific to the data center?)

The appID is specific to your bot, however your bot is tied to a specific data center on creation. Effectively the answer to this is yes, each instance of your bot will have an appID and if you choose to create multiple instances with different data centers each of those will have a different appID.

**Comment by imailer2015** [comment]
Hi Team,
For the last question, i understand that the appID is tied to the Microsoft DC where the resource was created. If there is a requirement to keep the appID constant for a particular region / globally, will that be possible in any way ?

**Comment by nyxsys** [comment]
Regionally is possible, but globally is not unless you route all requests to the same bot instance. However this might result in a slower experience the further out the instance is from your customers.
