### ISSUE TITLE
using context.call or forward between Luis based dialogs

### ISSUE THREAD

**Issue by Rykimaruh** [Microsoft/BotBuilder#4728]
Hello,

I am trying to call a a Dialog that has Luis intent from within the root dialog which also has Luis.

`context.Call(new Class1(), ResumeAfterDialog);`

When I call Class1() it only shows a message I have in ResumeAfterDialog(), it is as if it doesn't stay in the child dialog Class 1.

Is there an equivalent of MessageReceivedAsync using LUIS? Is it the "None", "" Luis intents? 

Any help is greatly appreciated

**Comment by ukphillips** [comment]
There is a LuisDialog class that you may find useful. Take a look at this sample: https://github.com/Microsoft/LUIS-Samples/blob/master/documentation-samples/tutorial-web-app-bot/csharp/BasicLuisDialog.cs
for an example of how to extent that class and use the LuisIntent attribute.

**Comment by JasonSowers** [comment]
Are you using a single LUIS model?  If yes, why do you need multiple LuisDoalogs, what is your scenario?

> Is there an equivalent of MessageReceivedAsync using LUIS? Is it the "None", "" Luis intents?

no

**Comment by Rykimaruh** [comment]
@JasonSowers , it's using the same LUIS model. My scenario is that I have a bot that offers 2 areas of support, Tech and HR for example. However I have a root dialog with LUIS that determines the intent of the user and then depending on the utterance, it "directs" the conversation to the corresponding area of support which are in separate classes.

If a user write about HR support, then the intent would be something containing hr support utterance which the bot reads it and then directs to the hr support class. In that class, then the user asks or type something that either triggers the qna dialog or some other service.

**Comment by JasonSowers** [comment]
I do know of a way to have multiple LuisDialogs for the same model, but I have never tried.  I think you are going to have to use a single LuisDialog and let that dialog route things accordingly.  You can still do exactly what you want as you can have an intent call any other dialog/service/class/etc.

**Comment by fanidamj** [comment]
Closing the issue assuming it as resolved. Please reopen a new issue if it still persists.
