### ISSUE TITLE
[.Net SDK, Auth, Emulator] BasicOAuth example code reuses existing token from bot service

### ISSUE THREAD

**Issue by ukphillips** [Microsoft/BotBuilder#4729]
## Bot Info
* SDK Platform: .NET 
* SDK Version: 3.15.2.2
* Active Channels: 
* Deployment Environment: Local Emulator

## Issue Description
When using the basic oauth sample with the emulator, previous sign ins are used rather than re prompting for credentials. Once I have logged in the bot framework is continually retrieving the same token, even when I create a new chat session. This also seems to be the case for the deployed bot at well. 

```
          var oauthClient = activity.GetOAuthClient();
                var token = await oauthClient.OAuthApi.GetUserTokenAsync(activity.From.Id, ConnectionName).ConfigureAwait(false);
```

this code snippet seems to the the culprit, the activity.From.Id is always set to "default-user" when the conversation starts up. So new conversations are finding the token of the previous user. I have found outside the emulator I can control this by setting a new userid on the initialization of the chat client, but this seems a little too risky to depend on the client for providing the userid to authenticate with. Am I missing something here with how the userid should be used? It seems like once the user logs in anyone could run the javascript to initialize a new chat window with just knowing another user's id. 

I could initialize with a userid + generated value when the page is loaded so someone from any machine can't just try a userid, but then if the user reloads the chat page, they would have to sign in again - which I don't want either. I'm not sure how best to proceed.

## Reproduction Steps
1. Configure bot for auth
2. Use the BasicOAuth sample
3. Once authenticated create new emulator sessions

## Expected Behavior
The ability to create new user sessions

## Actual Results
Existing token is used and the user is "signed in" regardless of who the token belongs to.

**Comment by ukphillips** [comment]
So I did find this: https://stackoverflow.com/questions/44906266/ms-bot-framework-emulator-chang-user-id 

Where you can change the default settings of the emulator, which is cumbersome, but doable, I'm curious though how this should be working in the bot service in terms of keeping track of the tokens without just trusting what the user passes in.

**Comment by EricDahlvang** [comment]
If you need to restart a session with the emulator, you can send ' /deleteProfile' and it should clear out UserData.

UserId should be kept private (hashed, or encrypted).  It is specific to the user.

**Comment by EricDahlvang** [comment]
This is more of an emulator issue than a bot builder issue.  Please post this to the emulator repository if you require further assistance: https://github.com/Microsoft/BotFramework-Emulator/issues/new
