### ISSUE TITLE
Getting "There was an error sending this message to your bot: HTTP status code BadGateway"

### ISSUE THREAD

**Issue by deepratdello** [Microsoft/BotBuilder#4730]
## Bot Info
* SDK Platform: .NET
* SDK Version: 
* Active Channels: Web Chat from Azure.
* Deployment Environment: On Premise deployment

## Issue Description
Getting the error "There was an error sending this message to your bot: HTTP status code BadGateway" when try to debug using ngrok when sending the message from Azure Web Chat Channel.
Normally when not debugging I'm getting the error "There was an error sending this message to your bot: HTTP status code GatewayTimeout".
Even I have removed the additional code just using the RootDialog in MessageController.

![image](https://user-images.githubusercontent.com/40060791/41271976-ebb34218-6e30-11e8-8d34-9fe4705dd373.png)
![ngrokissue](https://user-images.githubusercontent.com/40060791/41272009-0e7decd0-6e31-11e8-8c44-ab4e4a32aef8.png)

**Comment by nyxsys** [comment]
Try the following and see if they fix your issue:

- use the following ngrok command to start forwarding:  ngrok http <port> -host-header="localhost:<port>"

- Check your Web.config file and make sure you've set your AppId and AppPassword properly

- update ngrok and update your bot-related dependency packages 

Please follow up if the previous solutions don't work for you.

**Comment by deepratdello** [comment]
Hi nyxsys,
I updated the BOT SDK and checked the AppId and Password it's correct.
Is there anything else I can try?

**Comment by nyxsys** [comment]
So just a quick run-through on how to use ngrok, just because I'm not sure which step is missing:

- Copy over AppId and password from azure portal to bot

- Start Bot
 
- Copy over the port from your bot to ngrok http <port> -host-header="localhost:<port>"
 
- Copy over the https ngrok endpoint that is published by that command to the azure portal messaging endpoint https://<id>.ngrok.io/api/messages
 
- save and send a message from the webchat

**Comment by keithmartinkinyua** [comment]
what is ngrok?

**Comment by EricDahlvang** [comment]
@keithmartinkinyua 

More information about how to use ngrok to debug a bot can be found here: 
https://github.com/Microsoft/BotFramework-Emulator/wiki/Tunneling-%28ngrok%29
