### ISSUE TITLE
Simple Bot return "There was an error sending this message to your bot."

### ISSUE THREAD

**Issue by Kafar** [Microsoft/BotBuilder#4732]
## Bot Info
* SDK Platform: .NET
* SDK Version: 4.7
* Active Channels: Web Chat
* Deployment Environment: VStudio publish as Azure Service

## Issue Description
I followed this tutorial https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-deploy-azure?view=azure-bot-service-3.0 creating on Visual Studio a sample project using the Bot template. I deployed succesfully on Azure. But when I try to test from Azure with Test in Chat typing a word, i.e. "Hello" it return There was an error sending this message to your bot.

## Code Example
Same code included in Bot Template for VS

## Reproduction Steps
1. Deploy to Azure the project in Bot Template
2. Follow the steps in https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-deploy-azure?view=azure-bot-service-3.0

## Expected Behavior
The bot reply the words I wrote

## Actual Results
The bot reply with There was an error sending this message to your bot

**Comment by stevkan** [comment]
Can you verify that you entered 'MicrosoftAppId' and 'MicrosoftAppPassword and their respective (correct) values into the Application Settings of the App Service for your bot?

Unfortunately, you can't view the password after it's created. However, you can generate a new password (deleting the old one) and replace it in the Application Settings. Visit the [Apps](https://v-stkanb-simplebot1.azurewebsites.net/api/messages) site to make changes to your registered bot.

**Comment by Kafar** [comment]
I tried to generate a new password and checked values but the issue persist.
Thanks

**Comment by stevkan** [comment]
Hi @Kafar,

Can you make another attempt and then check these items and post the results? It may take a couple minutes for any events to be logged. 1) Click on the bots Channels blade and click on any issues that may be posted for Web Chat. What's the full error(s) listed there? 2) Click on the bots Activity Log, look for the error, click on the JSON option for that error, copy and paste it here. (Sorry for the blob of text...the text editor isn't playing nice for me).

**Comment by Kafar** [comment]
1) "There was an error sending this message to your bot."
2) No error in Activity Log

Thanks

**Comment by stevkan** [comment]
Closing due to lack of response.
