### ISSUE TITLE
[Telegram, .NET SDK] Request mobile number and location from Telegram bot

### ISSUE THREAD

**Issue by Daddymarto01** [Microsoft/BotBuilder#4736]
## Bot Info
.NET 
telegram,facebook,slack
 

## Issue Description 
I need to automatically prompt user to input mobile number and location on suggested action just like it is done on facebook  messenger
## Code Example
 
                    if (reply.ChannelId.Equals("facebook", StringComparison.InvariantCultureIgnoreCase))
                    {
                        var channelData = JObject.FromObject(new
                        {
                            quick_replies = new dynamic[]
                            {
                         new
                         {
                             content_type = "location",
                         }
                            }
                        });

                        replymessage.ChannelData = channelData;
                    }
                    else if(reply.ChannelId.Equals("telegram", StringComparison.InvariantCultureIgnoreCase))
                    {
                    //get suggested action to enter mobile or share location here
                    }
## Reproduction Steps
//mobile_number
1.User is prompted to share mobile number on click of button
2.Use info is picked and an sms is sent to him for verification

//location
1. User is prompted to share location
2. Use coordinates picked from shared location

## Expected Behavior
User is expected to tap suggested button to share any of the above

**Comment by stevengum** [comment]
Just to clarify, you're asking for the bot to send a suggestedAction to the user. This suggestedAction that the user checks, it has their phone number; and by clicking the suggestedAction the user shares their phone number with the bot?

**Comment by Daddymarto01** [comment]
I finally found a solution @stevengum ... Will share the solution in the morning please. I can now share location and mobile from suggested actions on telegram and facebook channels. Another dilemma now is Skype.

**Comment by stevengum** [comment]
Glad to hear that! Am looking forward to seeing your solution 😄 

You're now trying to get the phone number and location from a user via Skype through suggestedActions as well?

**Comment by Daddymarto01** [comment]
Here is the solution ....sorry for the delay. 

I added [Telegram Package](https://www.nuget.org/packages/Telegram.Bot/) latest version from Nuget.
After that, I  edited my code to 
`var replymessage = context.MakeMessage();
                    replymessage.Text = "Please send your pickup location";

                    if (reply.ChannelId.Equals("facebook", StringComparison.InvariantCultureIgnoreCase))
                    {
                        var channelData = JObject.FromObject(new
                        {
                            quick_replies = new dynamic[]
                            {
                         new
                         {
                             content_type = "location",
                         }
                            }
                        });

                        replymessage.ChannelData = channelData;
                    }

                    else if (reply.ChannelId.Equals("telegram", StringComparison.InvariantCultureIgnoreCase))
                    { 
                        markup.ResizeKeyboard = true;

                        markup.Keyboard = new KeyboardButton[][]
                        {
                            new KeyboardButton[]
                            {

                                new KeyboardButton("Send Current Location"){
                                                         RequestLocation = true
                                                }
                            }

                        };
                        await Bot.SendTextMessageAsync(context.Activity.From.Id, "Share Location", Telegram.Bot.Types.Enums.ParseMode.Default, false, false, 0, markup);

                    }`

Also add these two lines of code before you implement the above.
`private static readonly TelegramBotClient Bot = new TelegramBotClient("ADD_BOT_KEY_HERE");
 static ReplyKeyboardMarkup markup = new ReplyKeyboardMarkup();`

**Comment by stevengum** [comment]
Awesome, thank you for providing your solution! Closing issue as it appears resolved.
