### ISSUE TITLE
cannot save OAuth settings for Skype for business

### ISSUE THREAD

**Issue by mclark4873** [Microsoft/BotBuilder#4737]
## Bot Info
* SDK Platform: .Net
* SDK Version: 
* Active Channels: 
* Deployment Environment: Azure Bot Service

## Issue Description
 

Skype for business requires settings which I believe I would add via the OAuth settings under the settings tab in Azure for my chatbot.  I click the add button, fill in the settings and hit save.  The save button says "validating", and then it goes back to the previous screen and nothing has been saved.  Thre are no error messages. 

## Reproduction Steps
1.
2.
3.

**Comment by nyxsys** [comment]
Could you please double check your OAuth settings again (and retry adding your new one if needed). This issue appears to have been transient, as I was able to reproduce it this morning but have since seen these OAuth connection settings appear.

**Comment by mclark4873** [comment]
When I looked this morning they we visible again. Thanks. However the channel interface now throws exceptions when I try to edit the normal Skype channel.  Wondering if Azure services are ready for prime time at this point.  This is annoying while in development but would be catastrophic to need to wait daysfor “transient” problems to resolved when I need to resolve problems iwith applications in production.
