### ISSUE TITLE
Activity events are not getting logged in App insights while using from cortana

### ISSUE THREAD

**Issue by Kumar-Ashwin-Hubert** [Microsoft/BotBuilder#4739]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.15.2.2
* Active Channels: Cortana, Webchat
* Deployment Environment: Azure Bot Service

## Issue Description
The `Activity` events are not getting logged in App insights while using from **cortana** channel, thus not showing in Analytics as well. Other channels like webchat, directline's  Activities are getting logged. Issue also discussed at https://stackoverflow.com/questions/50840018/cortana-channel-user-bot-messages-doesnt-appear-in-app-insights-and-analytics/50852487
## Reproduction Steps
1. Create a sample Azure web app bot
2. Enable Cortana channel and hit the bot from Cortana channel as well as from webchat  
3. Open analytics / App insights and you would see that messages from Cortana are not getting logged.

![stackoveflow1](https://user-images.githubusercontent.com/25590394/41406225-771dd8ea-6fe9-11e8-8dda-da7fd0916114.PNG)
![stackoveflow2](https://user-images.githubusercontent.com/25590394/41406231-7c93bef2-6fe9-11e8-95a6-497f284fa515.PNG)

## Expected Behavior
`Activity` events from Cortana to be logged in Application insights.

**Comment by stevkan** [comment]
Hi @Kumar-Ashwin-Hubert, this is a known issue. Please reference [#4500](https://github.com/Microsoft/BotBuilder/issues/4500) for further information. Closing as duplicate.
