### ISSUE TITLE
[CSharp] Add PromDialog.Attachment method for asking the user to upload a file

### ISSUE THREAD

**Issue by TechWatching** [Microsoft/BotBuilder#474]
This feature has been brought to Bot Builder SDK for NodeJS but not yet to the C# part [(see this issue)](https://github.com/Microsoft/BotBuilder/issues/74). The use case is the bot wants to prompt the user to upload a file (eventually corresponding to a certain content type). A new method Attachment for PromptDialog class could easily bring this feature.

**Comment by msft-shahins** [comment]
I took the pull request. I will make refinements to it and add appropriate test cases.

**Comment by TechWatching** [comment]
Sorry I was not available the past few days so I couldn't add the test cases on time. Thanks for taking the pull request anyway.
