### ISSUE TITLE
 OnHangupCompleted is never raised in Skype calls

### ISSUE THREAD

**Issue by Rufus1123** [Microsoft/BotBuilder#4743]
* SDK Platform: .NET
* SDK Version: 3.15.2.2
* Active Channels: Skype
* Deployment Environment: Azure App Service

## Issue Description
The event OnHangupCompleted is never raised; neither when the call is ended by the user, nor when the bot executes a Hangup action. 

## Code Example
```
private Task OnHangupCompleted(HangupOutcomeEvent hangupOutcomeEvent)
{
    System.Diagnostics.Trace.TraceInformation(hangupOutcomeEvent.ConversationResult.Id);
    hangupOutcomeEvent.ResultingWorkflow = null;

    return Task.FromResult(true);
 }
```

## Reproduction Steps
1. Using the Skype-calling-bot example
2. Deploy to Azure
3. Set a breakpoint and remote debug
4. Call the bot and hangup or make the bot hangup after receiving my message

## Expected Behavior
I expected the breakpoint to be hit.

## Actual Results
Breakpoint is not hit. OnHangupCompleted is never raised.

**Edit 1:**
I found out that onHangupCompleted calls the callback url:
Requested URL | https://xxxxxxxxxxx:80/api/calling/callback
I think it should be:
Requested URL | https://xxxxxxxxxxx.azurewebsites.net:80/api/calling/callback
The correct callback url is hit for other cases, but just not on hang-up, so I don't think there is something wrong with my configuration.

Is this a bug? Can I set the callback url somewhere when onHangupComplete is raised?

**Comment by stevkan** [comment]
Hi @Rufus1123, I'm working on duplicating the issue and am curious if you set break points elsewhere in the IVRbot.cs file, do any hit?

**Comment by Rufus1123** [comment]
@stevkan yes, other breakpoints do hit when I set them, e.g. In onRecordCompleted

**Comment by stevkan** [comment]
@Rufus1123, where did you see that the OnHangupCompleted callback Url is https://xxxxxxxxxxx:80/api/calling/callback? All the references I have seen point to the latter implementation.

**Comment by Rufus1123** [comment]
@stevkan When I enable Application Logging in Diagnostics Logs in the Azure portal, I get the html code for a website in the Log Stream. I have copied this to a file and opened that in my browser. See the screenshot below.
![image](https://user-images.githubusercontent.com/32542901/41762741-036dca68-75fc-11e8-81b3-6e9bdf24c868.png)

**Comment by stevkan** [comment]
Hi @Rufus1123 - Fyi, we are looking closer at this. Thank you for being patient.

**Comment by stevkan** [comment]
Hi @Rufus1123,

This does appear to be a legitimate bug in the code. There is no immediate fix and no ETA. As the code is open source, you are welcome to research a solution and submit it as a PR against the [Microsoft/BotBuilder-Samples](https://github.com/Microsoft/BotBuilder-Samples/issues) repo. In the mean time, this issue will be closed and a bug opened on that repo for future consideration.
