### ISSUE TITLE
GetTokenDialog causes error with login card

### ISSUE THREAD

**Issue by ukphillips** [Microsoft/BotBuilder#4745]
## Bot Info
* SDK Platform: .NET 
* SDK Version: 3.15.2.2
* Active Channels: Direct Line
* Deployment Environment: Azure App Service

## Issue Description
I have been trying to use the GetTokenDialog for triggering a login card for my generic oauth authentication. The card is rendering fine, but once I click it, it redirects me for authentication, but my bot chat window becomes unusable, all entries immediately get a "couldn't send retry" response with no network traffic. The bot can accept messages before the login button is clicked.

I noticed in the network traffic when I click the button I get this call:
GET https://directline.botframework.com/v3/directline/session/getsessionid resulting in a 403 with a response of: ServiceError - Trusted Origin list is empty.

I had used oauth cards successfully before so I looked at the difference between the generic and the token dialog that wraps it, and it seems like internally the GetTokenDialog has: 
```
            private async Task SendOAuthCardAsync(IDialogContext context, Activity activity)
            {
                var reply = await activity.CreateOAuthReplyAsync(_connectionName, _signInMessage, _buttonLabel);
                await context.PostAsync(reply);
                context.Wait(WaitForToken);
            }
```

when I duplicated this dialog functionality, and used my own version, I modified the oauth reply to set the asSignInCard to true, and it resolved my issue, it no longer throws the 403 from the card click

 ```
private async Task SendOAuthCardAsync(IDialogContext context, Activity activity)
            {
                var reply = await activity.CreateOAuthReplyAsync(_connectionName, _signInMessage, _buttonLabel, true);
                await context.PostAsync(reply);
                context.Wait(WaitForToken);
            }
```
I'm not sure if this is expected or not, or if something else needs to be in place to prevent this.

## Code Example
`        
context.Call(this.CreateGetTokenDialog(), Callback);

        private GetTokenDialog CreateGetTokenDialog()
        {
            return new GetTokenDialog(
                              ConnectionName,
                              $"Please sign in to {ConnectionName} to proceed.",
                              "Sign In",
                              2,
                              "Hmm. Something went wrong, let's try again.");
        }
`

## Reproduction Steps
1. Return GetTokenDialog

## Expected Behavior
The bot to be responsive after clicking the link

## Actual Results
Bot can not accept any input

**Comment by ukphillips** [comment]
Worked through this with @Jeffders 

When I started out I was just testing around with initializing the webchat client with the master key. I ended up switching to exchanging the master secret for a conversation token on the server side which would be best practice anyways, but I needed to make sure to add the trusted origins to my token generate request:

```
           using (var tokenClient = new HttpClient())
            {
                tokenClient.DefaultRequestHeaders.TransferEncodingChunked = false;
                tokenClient.DefaultRequestHeaders.Add("Accept", "application/json");
                tokenClient.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", "DIRECTLINE SECRET");
                var httpContent = new StringContent(JsonConvert.SerializeObject(new { TrustedOrigins = new String[] { "http://URL WHERE THE BOT IS RUNNING" } }), Encoding.UTF8, "application/json");
                var tokenResult = await tokenClient.PostAsync("https://directline.botframework.com/v3/directline/tokens/generate", httpContent);
                var tokenJson = await tokenResult.Content.ReadAsStringAsync();

                token = JObject.Parse(tokenJson)["token"].ToString();
//Use token to initialize webchat
            }
```

Once I initialized my conversations this way, I could go back to using GetTokenDialog with the asSignInCard flag set to false. It also did not require the magic code anymore when handling the oauth flow!

Beware to make sure the content is **NOT** chunked or it will return a bad token

**Comment by premaarya** [comment]
I'm facing the exact same issue with latest Bot builder SDK 3.15.3 using DirectLine and WebChat same error. Making the copy of GetTokenDialog asking for magic code to sign. 

@ukphillips  how do you initialize the webchat/directline from server side with the token(I get the token using your code) ? do you mind sharing code snippet?

**Comment by premaarya** [comment]
Like @mkovel has described in[ #71](https://github.com/Microsoft/BotFramework-DirectLineJS/issues/71)?

**Comment by ukphillips** [comment]
@premaarya I added the code sample above the resulting token is then used to initialize the webchat. This was done in an MVC project that rendered the page with the token and then the js initialized.

The key component of the code was passing in the trusted url origin:

`var httpContent = new StringContent(JsonConvert.SerializeObject(new { TrustedOrigins = new String[] { "http://URL WHERE THE BOT IS RUNNING" } }), Encoding.UTF8, "application/json");
`
`
var tokenResult = await tokenClient.PostAsync("https://directline.botframework.com/v3/directline/tokens/generate", httpContent);
`

**Comment by premaarya** [comment]
@ukphillips  thanks ! my client is SharePoint spfx .. I will try this.

**Comment by premaarya** [comment]
@ukphillips  finally i tried using the approach .. i am trying to get  token from my SPFx chat control ... getting Cross-Origin error 
`ApplicationCustomizer.ts:318 Failed to load https://directline.botframework.com/v3/directline/tokens/generate: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'https://domain.sharepoint.com' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.`

the TypeScript equivalent : 
```
     let tokenClient: XMLHttpRequest = new XMLHttpRequest();
      tokenClient.open("POST", botTokenGenerateUrl, false);
      tokenClient.setRequestHeader("Cache-Control", "no-cache");
      tokenClient.setRequestHeader("TransferEncodingChunked", "false");
      tokenClient.setRequestHeader("Accept", "application/json");
      tokenClient.withCredentials = true;
      tokenClient.setRequestHeader("Authorization", "Bearer " + this.directlineKey);
      tokenClient.onreadystatechange = function() {
        if (tokenClient.readyState === 4 && tokenClient.status === 200) {
           let tokenResponse : any = JSON.parse(tokenClient.responseText);
        }
    };
      tokenClient.send(jsonTokenBody);
```
I was able to get the token in C# bot code. The http://URL WHERE THE BOT IS RUNNING has CORS set to * and also tried setting specific sharepoint url.
 Any idea what could be the issue?

**Comment by premaarya** [comment]
The issue above is fixed, how ever with directline the authentication ask for magic code .. and after providing the magic code there is no response..with missingToken error..

Working code:
    `let tokenClient: XMLHttpRequest = new XMLHttpRequest();

      tokenClient.open("POST", botTokenGenerateUrl, false);

      tokenClient.setRequestHeader("Content-Type", "application/json");   
      tokenClient.setRequestHeader("Authorization", "Bearer " + this.directlineKey);
      tokenClient.onreadystatechange = function() {
        if (tokenClient.readyState === 4 && tokenClient.status === 200) {
           let tokenResponse : any = JSON.parse(tokenClient.responseText);
        }
    };
      tokenClient.send(jsonTokenBody);`
