### ISSUE TITLE
Cannot build Microsoft.Bot.Builder.Samples.sln as a standalone solution

### ISSUE THREAD

**Issue by arturl** [Microsoft/BotBuilder#4749]
## Reproduction Steps
1. Load `Microsoft.Bot.Builder.Samples.sln` in VS 2017
2. Build solution

## Expected Behavior
Successful build

## Actual Results
Errors like this:
```
14>C:\g\BotBuilder\CSharp\Samples\AadV1Bot\Controllers\MessagesController.cs(6,21,6,28): error CS0234: The type or namespace name 'Builder' does not exist in the namespace 'Microsoft.Bot' (are you missing an assembly reference?)
14>C:\g\BotBuilder\CSharp\Samples\AadV1Bot\Controllers\MessagesController.cs(7,21,7,30): error CS0234: The type or namespace name 'Connector' does not exist in the namespace 'Microsoft.Bot' (are you missing an assembly reference?)
14>C:\g\BotBuilder\CSharp\Samples\AadV1Bot\Dialogs\RootDialog.cs(4,21,4,28): error CS0234: The type or namespace name 'Builder' does not exist in the namespace 'Microsoft.Bot' (are you missing an assembly reference?)
14>C:\g\BotBuilder\CSharp\Samples\AadV1Bot\Dialogs\RootDialog.cs(5,21,5,30): error CS0234: The type or namespace name 'Connector' does not exist in the namespace 'Microsoft.Bot' (are you missing an assembly reference?)
```

The issue is in the csproj files that refers to binaries in the `..\..\Library` directory where they don't exist until they are built by the main solution (`Microsoft.Bot.Builder.sln`). 

The Samples solution should be self-contained. Either consume the packages from NuGet, or include dependent projects from the main solution into the Samples solution.

**Comment by EricDahlvang** [comment]
Thanks for reporting this @arturl    

This PR ensures all samples build and are using the latest nuget packages: https://github.com/Microsoft/BotBuilder/pull/4844
