### ISSUE TITLE
Multiple Hits to ProcessCallingEventAsync() in Skype Call for every Record Event

### ISSUE THREAD

**Issue by flatmath** [Microsoft/BotBuilder#4751]
## Bot Info
* SDK Platform: .NET 
* SDK Version: 3.14.0.7
* Active Channels: Skype
* Deployment Environment: Azure Bot Service, Azure App Service

## Issue Description
We have:

````C#
[Route("callback")]
public async Task<HttpResponseMessage> ProcessCallingEventAsync()
{
    return await CallingConversation.SendAsync(this.Request, CallRequestType.CallingEvent);
}

````
Sometimes (but almost always, at least 4-5 times in a call), this method is hit thrice in a row for the same event. 
Before the first fired event can finish processing, this event is hit a second and then third time, which causes some flags set in the code to change and ruin the intended flow.

Similar to https://github.com/Microsoft/BotBuilder/issues/2016.

## Reproduction Steps
1. Speak into the bot as required.
2. Wait for issue to occur.

## Expected Behavior
For every Record event, the **ProcessCallingEventAsync()** method should be hit once.
Hence, the event handler **OnRecordCompleted()** should be hit just once.

## Actual Results
The method is hit thrice in a row - causing the **OnRecordCompleted()** event to fired thrice.
This muddles the intended flow.

Re-open of issue https://github.com/Microsoft/BotBuilder/issues/4644

AppId is [80dbaddf-68d0-40ee-9326-edbf49a636da].

**Comment by flatmath** [comment]
@stevkan @JasonSowers Re-opened issue https://github.com/Microsoft/BotBuilder/issues/4644.

**Comment by flatmath** [comment]
@stevkan the AppId is [80dbaddf-68d0-40ee-9326-edbf49a636da]

**Comment by stevkan** [comment]
Closing as referencing/duplicate issue, #4644, is resolved.
