### ISSUE TITLE
FB messenger not sending attachments from Azure SAS

### ISSUE THREAD

**Issue by kofarrell1076** [Microsoft/BotBuilder#4759]
## Bot Info
* SDK Platform: .net
* SDK Version: 
* Active Channels: fb, directline
* Deployment Environment: Azure app service

Having trouble sending attachments back out to FB messenger. Works ok if I have an attachment outside of Azure, but fails always if attachment is from Azure sas.

I'm using send reply from a previously saved activity context. The message body get's through ok but never any attachments.
-----------------
 var status =  await connector.Conversations.SendToConversationAsync((Activity)message);
--------------------
and the contenturl is:

https://apptimistorage.blob.core.windows.net/512/M5CBFQIWFF.jpg?sv=2017-04-17&sr=b&sig=78eFzR2YOe2FgT4g%2Fn8XrtgfgERKF8on0ccA0QSjGws%3D&se=2018-06-19T21%3A00%3A33Z&sp=r&rscd=attachment%3B%20filename%3DM5CBFQIWFF.jpg

Can it be a url length issue? is there a limit on the url size?

thanks

**Comment by JasonSowers** [comment]
Can you please post the code you are using to construct the activity and the atachment, you have only shared how you are sending the activity.  Also can you please describe what you are using in Azure for storage so we can try to reproduce.  If you could also post another valid URL for us to take a look at that would be great as well.

**Comment by JasonSowers** [comment]
Using the following code, I was able to render an image as an attachment:

```cs
    public async Task MessageReceivedAsync(IDialogContext context, IAwaitable<IMessageActivity> argument)
    {
        var activity = await argument;

        var reply = (Activity)activity;
        
        var a = new Attachment();
        a.ContentUrl = @"https://jasonazurestorage.blob.core.windows.net/files/bomb300.png?sp=r&st=2018-07-02T19:16:38Z&se=2018-07-03T03:16:38Z&spr=https&sv=2017-11-09&sig=bHwxltvAs7t5drytU%2FH7vaq03FBYqEkTOv%2BUaKuhmSY%3D&sr=b";
        a.ContentType = "image/png";
        a.Name = "image 1";

        reply = reply.CreateReply();
        reply.Attachments = new List<Attachment> {a};

        await context.PostAsync(reply);
    }
```

**Comment by JasonSowers** [comment]
Going to assume you were able to get this code working from your 👍 .  Good luck.
