### ISSUE TITLE
[.Net SDK, DirectLine] Reusing obtained token when doing PostActivityAsync on DirectLineClient

### ISSUE THREAD

**Issue by devedse** [Microsoft/BotBuilder#4761]
## Bot Info
* SDK Platform: .NET
* SDK Version: Microsoft.Bot.Connector.DirectLine (3.0.2.0)
* Active Channels: -
* Deployment Environment: -

## Issue Description

I'm trying to build a Skype Voice Bot that makes use of the DirectLine channel in C# using the NuGet package: Microsoft.Bot.Connector.DirectLine (3.0.2.0)

In the REST documentation https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-start-conversation?view=azure-bot-service-3.0 it describes how you can obtain a token to be used for a specific conversation. This functionality exists in C# with the DirectLineClient.Conversations.StartConversation() method.

In the REST documentation here: https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-send-activity?view=azure-bot-service-3.0 it describes how to use this token when sending an Activity to the service. This functionality seems to be missing however. As the only methods available for posting an Acitivy are these ones:

```
public static ResourceResponse PostActivity(this IConversations operations, string conversationId, Activity activity);
public static Task<ResourceResponse> PostActivityAsync(this IConversations operations, string conversationId, Activity activity, CancellationToken cancellationToken = default(CancellationToken));
```

## Expected Behavior
I would expect there to be an optional parameter where one can provide the token.

## Actual Results
There's no parameter to specify the token for the bot so all authentication is being done by the secret that has been provided to the DirectLineClient in the beginning, which gives it the Authority to access all conversations.

## More
Also it would be really helpful if there would also exist some more documentation regarding the DirectLineClient for C# as there's only a few samples available now that don't focus on multiple clients connecting.

What I could also assume is that you need to create a new DirectLineClient for every user that's connecting to the Skype Voice Bot. But would this be something that you need to store in the callstate?

**Comment by ukphillips** [comment]
@devedse Once you have the conversation token, you would initialize the directline client with that token, which is now scoped to the conversation:

```
      var client = new DirectLineClient(token);
      var result = await client.Conversations.PostActivityAsync(conversationId, new Microsoft.Bot.Connector.DirectLine.Activity() { COOL ACTIVITY }
```
Your token generation should have also returned a conversationId property to pass into the post method.

**Comment by devedse** [comment]
Should that DirectClient then be stored? Or can I recreate a new one every request?

**Comment by ukphillips** [comment]
I have only worked with creating one for each request, but that was also only in the context of starting a conversation so I didn't have to reuse it again. I suppose it depends on how often things are going to be pushed through client (if it's worth the initialization overhead). It's IDisposable so just make sure you dispose it once you are done (whether that's per request in a using block, or when that conversation ends and you don't need it stored)

**Comment by nyxsys** [comment]
If you cache the conversationtoken recieved during your initial creation of the DirectLineClient, it can be used to reconnect later on by setting your current conversationid back to that and sending activities with that Id. This can be seen in [this example](https://github.com/Microsoft/BotBuilder-Samples/blob/master/CSharp/core-DirectLine/DirectLineClient/Program.cs) You would be utilizing the saved conversation in these calls:

`await client.Conversations.GetActivitiesAsync(conversationId, watermark);`
Which will get all the new conversation updates since the last message to the conversation.

and
`await client.Conversations.PostActivityAsync(conversation.ConversationId, userMessage);`
Which will let you post additional messages to the saved conversation.

**Comment by nyxsys** [comment]
please reopen if you have any more issues with this.
