### ISSUE TITLE
Slack: Extremely slow responses for production slack bots

### ISSUE THREAD

**Issue by v46** [Microsoft/BotBuilder#4762]
We are seeing a lot of degradation in performance for our production Slack bots. 
Messages from slack are slow when reaching our "Bot Service" (round trip is about ~11 minutes).

There are no outage reports on Slack's status page or on the Azure Bot service status page. Nothing in app insights to indicate any errors.

Our bots run on node js bot SDK 3.11.0 and we host our bots outside Azure.

**Comment by EricDahlvang** [comment]
HI @v46 

Thank you for reporting this.  

How long has the issue been occurring?  

Is it consistent, or intermittent?  

Are your bots hosted on a specific data center?

**Comment by v46** [comment]
We started noticing this since yesterday afternoon PST. It went away in a couple of hours and it started showing up again this morning for about 30-45 minutes again (intermittently delayed messages that do not reach out service). We don't host our bots on Azure (if this is what you mean by the data center question) - our servers on hosted the US North West region.

Things are back to normal now, but I am not certain if this is a temporary relief and if the service will degrade again.

**Comment by EricDahlvang** [comment]
There have been some issues with North Europe data centers this morning https://azure.microsoft.com/en-us/status/  

There has also been some issues with the Azure Bot Service the past few days:

> The Azure Bot Service is experiencing degraded performance that is impacting customers under certain conditions. Our engineering team has identified a root cause and implemented a solution that should mitigate the problem. Yesterday (6/18/2018), the fix was deployed to a subset of datacenters where it’s undergoing validation. Pending further verification the team will continue to deploy the fix to datacenters worldwide

I'll let you know when the deployment has been completed.

**Comment by EricDahlvang** [comment]
The deployment has been completed worldwide.
