### ISSUE TITLE
[.NET SDK] UserAgent String associated with the BotBuilder SDK .NET changed sometime after 3.12.2.4 

### ISSUE THREAD

**Issue by jameslew** [Microsoft/BotBuilder#4763]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.15+
* Active Channels: Any
* Deployment Environment: Any

## Issue Description
UserAgent String associated with the BotBuilder SDK .NET changed sometime after 3.12.2.4 .

Prior to 3.12.2.4 it looked like:
","FxVersion/4.7.2563.0 OSName/Windows_Server_2016_Datacenter OSVersion/6.3.14393 Microsoft.Bot.Connector.ConnectorClient/3.12.2.4 Microsoft-BotFramework/3.1 (BotBuilder .Net/3.12.2.4)"

and afterward:

"FxVersion/4.7.2671.0 OSName/WindowsServer2016Datacenter OSVersion/6.3.14393 Microsoft.Bot.Connector.ConnectorClient/3.14.1.1"

Specifically - the "Microsoft-BotFramework/3.1 (BotBuilder .Net/3.12.2.4)" section was dropped.

## Expected Behavior
UA String to maintain consistency

**Comment by EricDahlvang** [comment]
Thanks for reporting this @jameslew 

Addressed with this PR: https://github.com/Microsoft/BotBuilder/pull/4766

**Comment by EricDahlvang** [comment]
Closing ... fix has been merged.  It will be in the next nuget release.
