### ISSUE TITLE
[Direct Line] Debug Direct Line Bot ngrok

### ISSUE THREAD

**Issue by diegolanda** [Microsoft/BotBuilder#4773]
## Bot Info
* SDK Platform: Node.js
* SDK Version: 3.12.0
* Active Channels: Direct Line
* Deployment Environment: Azure Bot Service, local development, Sharepoint Webpart

## Issue Description

I am not able to create a tunnel using ngrok so I can communicate my Sharepoint webpart with webchat (direct line) to my local bot and develop new features to my bot or debug a deployed bot in Azure.

## Code Example

Using webpart with react:

```
         <Chat
            adaptiveCardsHostConfig={chat.adaptiveCardsHostConfig}
            bot={chat.bot}
            user={chat.user}
            botConnection={botConnection}
            speechOptions={chat.speechOptions}
          />
```

Bot:

```
const connector = new builder.ChatConnector({
    appId: process.env.MicrosoftAppId,
    appPassword: process.env.MicrosoftAppPassword,
    openIdMetadata: process.env.openIdMetadata
});

const bot = new builder.UniversalBot(connector).set('storage', new builder.MemoryBotStorage());
```

## Reproduction Steps
1. Start ngrok and point to localhost:3879 
2. With a deployed bot in azure, change messages endpoint to point <ngrok>/api/message in azure settings
3. Verify AppId and AppPassword is creating an Authorization Token with cURL
4. Launch local sharepoint workbench with webchat
5. Start local bot
6. Send a message
7. Ngrok is throwing 502 Bad Gateway and bot is not getting any message

## Expected Behavior

Ngrok should tunnel messages to develop locally

## Actual Results

- Azure Application settings breaks in Azure portal and throws `Failed to Load`

![image](https://user-images.githubusercontent.com/1644517/41697567-5ba83f76-74e7-11e8-9231-3946bd35a7ce.png)

- Ngrok is receiving a post message

![image](https://user-images.githubusercontent.com/1644517/41697591-772f3fe2-74e7-11e8-9ca5-51ab0ff211fb.png)

- Webpart returning

```
{
  "error": {
    "code": "BotError",
    "message": "Failed to send activity: bot returned an error"
  },
  "httpStatusCode": 502
}
```

**Comment by nyxsys** [comment]
Does your ngrok endpoint work from other channels or is it failing on non-directline locations as well? Consider double-checking the steps on [here](https://blog.botframework.com/2017/10/19/debug-channel-locally-using-ngrok/). Especially using `ngrok http <port> -host-header="localhost:<port>"` to run ngrok. Regarding the issue with application settings, we are going to look into this further.

**Comment by diegolanda** [comment]
Hi @nyxsys , tried the link you shared but still getting the same issue.

![image](https://user-images.githubusercontent.com/1644517/41855508-d168bfb6-7860-11e8-9084-057e718bc0ef.png)


![image](https://user-images.githubusercontent.com/1644517/41855525-dc7afb26-7860-11e8-8425-14a74459f8b0.png)


Bot Replied:
```
{
  "error": {
    "code": "BotError",
    "message": "Failed to send activity: bot returned an error"
  },
  "httpStatusCode": 502
}
```
Tested with webchat on azure portal.

I get 502 when I don't start the bot and telling me that no service is running on that 

![image](https://user-images.githubusercontent.com/1644517/41855456-b6a65850-7860-11e8-8b0e-401d21f83cdb.png)

Once I start neither POST/OPTIONS returns anything and stays empty

![image](https://user-images.githubusercontent.com/1644517/41855554-e8305c4a-7860-11e8-8b36-9525e37db697.png)

**Comment by nyxsys** [comment]
Just double checking, but are you using a baseline echo bot for this or have you made any changes? If so, could you please post a minimal version of your code.

Are you getting any errors or logs (or even just breakpoint hits) within the actual bot when you send messages to it via ngrok?

**Comment by diegolanda** [comment]
Not sure I understand about the baseline echo bot, but I'd say I haven't made any changes.

My dependencies are: 

```
"dependencies": {
    "@microsoft/microsoft-graph-client": "git+https://github.com/microsoftgraph/msgraph-sdk-javascript.git",
    "@microsoft/microsoft-graph-types": "https://github.com/microsoftgraph/msgraph-typescript-typings.git",
    "adaptivecards": "^1.0.0",
    "axios": "^0.18.0",
    "body-parser": "^1.18.2",
    "botauth": "next",
    "botbuilder": "3.12.0",
    "dotenv": "^5.0.1",
    "express": "4.15.3",
    "express-session": "1.15.3",
    "lodash": "^4.17.5",
    "moment": "^2.22.0",
    "passport-azure-ad": "3.0.8",
    "restify": "^4.3.0",
    "tedious": "^2.0.0",
    "tedious-connection-pool": "^1.0.5"
  },
  "devDependencies": {
    "@types/express": "4.0.35",
    "@types/node": "^6.0.52",
    "@types/restify": "^2.0.35",
    "chai": "^4.1.2",
    "eslint": "^4.18.2",
    "mocha": "^5.0.4"
  }
```

**Sample Code**

```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require('dotenv').config();
const fs = require("fs");
const path = require("path");
const restify = require("restify");
const builder = require("botbuilder");

const https_options = {
    key: fs.readFileSync(path.join(__dirname, './src/etc/ssl/server.key')),
    certificate: fs.readFileSync(path.join(__dirname, './src/etc/ssl/server.crt'))
};

let server;

if (process.env.port || process.env.PORT) {
    server = restify.createServer();
} else {
    server = restify.createServer(https_options);
}

server.use(restify.bodyParser({ mapParams: true }));

const connector = new builder.ChatConnector({
    appId: process.env.MicrosoftAppId,
    appPassword: process.env.MicrosoftAppPassword,
    openIdMetadata: process.env.BotOpenIdMetadata
});

server.listen(process.env.port || process.env.PORT || 3978, () => console.log(`${server.name} listening to ${server.url}`));

const intents = new builder.IntentDialog({ });

const bot = new builder.UniversalBot(connector).set('storage', new builder.MemoryBotStorage());

server.post('/api/messages', connector.listen());

server.use(restify.queryParser());
server.use(restify.bodyParser());

intents.onDefault(function (session) {
    session.send("Hmmm I don’t understand just yet");
});

bot.use({
    receive: (event, next) => {
        botRequest = event;
        next();
    },
    send: (event, next) => {
        botResponse = event.text;
        next();
    }
});

bot.dialog('/', intents); 
```

The code above works fine when using emulator, but with ngrok I don't get anything on azure portal test web chat

**Comment by nyxsys** [comment]
I've got your bot working on ngrok and local emulator, but I've commented out some of the code. Most of this is related to making your bot work as an api unto itself (adding additional endpoints) so please tell me if you are actually using it. If this is a sample bot you've downloaded and were just trying to set up, it should not be an issue.

Posting the whole file as I've got it set up for simplicity, but basically I've removed https_options and the restify.xParser lines.

```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require('dotenv').config();
const fs = require("fs");
const path = require("path");
const restify = require("restify");
const builder = require("botbuilder");
/*
const https_options = {
    key: fs.readFileSync(path.join(__dirname, './src/etc/ssl/server.key')),
    certificate: fs.readFileSync(path.join(__dirname, './src/etc/ssl/server.crt'))
};
*/
let server;

if (process.env.port || process.env.PORT) {
    server = restify.createServer();
} else {
    server = restify.createServer(/*https_options*/);
}

//server.use(restify.bodyParser({ mapParams: true }));

const connector = new builder.ChatConnector({
    appId: "f8a072af-b663-4cde-8199-9b3a6f7e0b83",//process.env.MicrosoftAppId,
    appPassword: "{6oeVu9B4@+02y9(",//process.env.MicrosoftAppPassword,
    openIdMetadata: process.env.BotOpenIdMetadata
});

server.listen(process.env.port || process.env.PORT || 3978, () => console.log(`${server.name} listening to ${server.url}`));

const intents = new builder.IntentDialog({ });

const bot = new builder.UniversalBot(connector).set('storage', new builder.MemoryBotStorage());

server.post('/api/messages', connector.listen());

//server.use(restify.queryParser());
//server.use(restify.bodyParser());

intents.onDefault(function (session) {
    session.send("Hmmm I don’t understand just yet");
});

bot.use({
    receive: (event, next) => {
        botRequest = event;
        next();
    },
    send: (event, next) => {
        botResponse = event.text;
        next();
    }
});

bot.dialog('/', intents); 
```

**Comment by diegolanda** [comment]
Sorry I''ve being quite for a while, had some other things to take care.

The bot seems to actually listen now even though is not replying anything, but will take a look and comment.

![image](https://user-images.githubusercontent.com/1644517/42326935-89a97bcc-8038-11e8-9342-e817c70f21ad.png)

On the other hand the Application Settings are still failing to load on azure portal

**Comment by nyxsys** [comment]
At the moment Application settings will stop loading until you've changed the messaging endpoint back from the ngrok endpoint to the one that was there originally. The hostname can be found on the bot webapp within the resource group.  It'll end up being <hostname>/api/messages

**Comment by nyxsys** [comment]
Note: you should now be able to see your application settings in azure if your ngrok endpoint is running.

**Comment by nyxsys** [comment]
Closing this issue for now, please reopen on stackoverflow with your code if this persists.
