### ISSUE TITLE
[.Net SDK, DirectLine] Using in memory cache in BOT 

### ISSUE THREAD

**Issue by whizlingo** [Microsoft/BotBuilder#4776]
## Bot Info
* SDK Platform: .NET 
* Active Channels: Direct Line
* Deployment Environment:  Azure App Service

## Issue Description

We are currently using Memory cache (https://github.com/aspnet/Caching/tree/dev/src/Microsoft.Extensions.Caching.Memory) in our BOT and experiencing some issues around cached items not being available at times, which is causing intermittent failures. The deployment environment is ASE (1 isolated node) with Server farm configured with "currentNumberOfWorkers": 2.  Does BOT maintain sticky sessions, especially when we have more than one worker process , so like all calls within a conversation go to the same instance of BOT worker process) ?. If not , Would you recommend using a distributed cache (Redis e.t.c ) in this case ?.

**Comment by ukphillips** [comment]
I think in all cases outside initial prototyping/testing you should be using some external store for persisting the bot state/conversation. Hoping your app service does not recycle or hits the same node every time is going to be a really bad expectation. Redis could store the data but it doesn't seem like the right fit for data persistence. I would look into the heavy favorites with extension support Table storage and CosmosDB (detailed here https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-state?view=azure-bot-service-3.0).

**Comment by whizlingo** [comment]
@ukphillips  This is not for persisting the bot state/conversation. We are using table storage as per the recommended approach. The question is specifically around using in memory cache for anything which is specific for the application. Based on what i saw initially , it did feel like it has sticky sessions. I think it makes sense to externalize any such state with a distributed cache....

**Comment by EricDahlvang** [comment]
The .net bot framework sdk is just an asp.net web api application.  There is no 'sticky session' support built into asp.net web api applications.  This is something you would need to provide yourself, with a Traffic Manager or Message Broker of some sort as the Messaging Endpoint.  

More details about the internal workings of the SDK related to message processing order can be found at this answer: https://stackoverflow.com/questions/50915504/ms-bot-framework-timing-issues/50938745?noredirect=1#comment88903141_50938745  You could write a DistributedMutualExclusion implementation of IScope<T> that uses Redis and keys on Conversation.Id, or some other distributed locking mechanism, and replace the internal LocalMutualExclusion implementation via Autofac registration.  More information can be found in this answer: https://github.com/Microsoft/BotBuilder/issues/3383#issuecomment-325053806

**Comment by ukphillips** [comment]
Sorry for the misunderstanding. If you are just using some cached reference or configuration data that the bot always needs for any conversation. Then yes could easily use redis for your distributed cache. You may also consider the cache-aside pattern (https://docs.microsoft.com/en-us/azure/architecture/patterns/cache-aside) and still leverage storing some of that data in a memory cache after it's looked up to prevent having to make another hop. It really depends on the volatility and scope of the data you are using this for.

**Comment by EricDahlvang** [comment]
I think everything has been answered in this thread, so I'm closing the GitHub issue.

**Comment by whizlingo** [comment]
Yes  @EricDahlvang and @ukphillips  - Thanks for the suggestion, we are going to proceed with Cosmos based implementation for Distributed mutual exclusion.
