### ISSUE TITLE
[Feature Request] BotBuilder misses support of sentimentAnlaysis

### ISSUE THREAD

**Issue by DHOFM** [Microsoft/BotBuilder#4777]
Hi,
maybe it is a general problem, so I open a new issue here: Also mentioned this in the node-js section: https://github.com/Microsoft/botbuilder-js/issues/280

## Bot Info
* SDK Platform: 
* SDK Version: <3.15.0->

* Deployment Environment: 

## Issue Description
<feature request -->
Support of SentimentAnalysis
## Code Example

LuisRecognizer needs to be changed like this:

...
LuisRecognizer.recognize(utterance, model, function (err, intents, entities, compositeEntities,**sentimentAnalysis**) {
                    if (!err) {
                        **result.sentimentAnalysis = sentimentAnalysis;**

...

LuisRecognizer.recognize = function (utterance, modelUrl, callback) {
        try {
            var uri = url.parse(modelUrl, true);
            uri.query['q'] = utterance || '';
            if (uri.search) {
                delete uri.search;
            }
            request.get(url.format(uri), function (err, res, body) {
                var result;
                try {
                    if (res && res.statusCode === 200) {
                        result = JSON.parse(body);
                        **result.sentimentAnalysis = result.sentimentAnalysis || [];**
                        result.intents = result.intents || [];
...

Also we need support of a property to read the sentimental data - I would suggest  a property in IActionRouteData of botbuilder then we can use the data in the triggered event...

The bold lines in the code above are inserted from me, so that code is not part of the original code...

**Comment by JasonSowers** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
