### ISSUE TITLE
[.Net SDK, FB Messenger] .NET SDK AzureBotServiceClient.Channels.Update don't working

### ISSUE THREAD

**Issue by MickaelPuygcerver** [Microsoft/BotBuilder#4779]
## Bot Info
* SDK Platform: >.NET
* Active Channels: Facebook Messenger
* Deployment Environment: Azure Bot Service

## Issue Description
Hi,
I'm trying auto registre bots in azure channel registration.
I can use method (Create) :

```cs
azureBotServiceClient.Channels.Create(resourceGroupName,
                                      resourceName,
                                      ChannelName.FacebookChannel,
                                      botChannel);
```

It works.

But update method don't work, and result is only "internal server error".
Example:

```cs
azureBotServiceClient.Channels.Update(resourceGroupName: resourceGroupName,
                                                         resourceName: resourceName,
                                                         channelName: ChannelName.FacebookChannel,
                                                         properties: properties);
```

What do I need to send? do not have any documentation and did not find anything anywhere
The parameter properties, I get direct from the azure, with method "ListWithKeys"

"Create", "Delete", "Get" and "ListWithKeys" work perfectly, only "Update" not working

**Comment by stevengum** [comment]
Sorry for the delay, I've reached out to one of the devs behind this SDK for further guidance.

**Comment by stevengum** [comment]
Friendly ping to @carlosscastro 😄

**Comment by JasonSowers** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
