### ISSUE TITLE
Waterfall Model in a Proactive Bot

### ISSUE THREAD

**Issue by officialdharam** [Microsoft/BotBuilder#478]
I have written a proactive bot, which works fine. Unfortunately, I am not able to get the waterfall model working. Somehow, it never goes to the waterfall step after user responds back to a Prompt.

Here is the code:
```
function notify(mode, oid){ 
   if(mode == "skype"){
      bot.beginDialog({
	to: { "address": "8:live:officialdharam", "channelId": "skype" , "id": "7JitRpa2At5", "isBot": false},
	from: { "address": "notificationbot", "channelId": "skype", "id": "notificationbot", "isBot": true},
	text: "Review Usecase"
     }, '/');
  }
}


dialog.on('Review', [function(session, args) {
	Util.logger.log('info', 'Received a Review intent with args %s', args);
	builder.Prompts.text(session, "We just received an urgent order. Would you like to review it?");	
}, function(session, results){
	console.log(results.response);
}]);
```

When my nodejs program starts, it invokes the notify method, which begins a dialog and resolves to the Review intent. 

This makes it prompt a message. When I respond back to the message in skype, it never prints the response.

Any help in this regard would be highly appreciated. Thanks

**Comment by officialdharam** [comment]
Here is an update on the issue! I was able to get the waterfall working. It seems like there was some issue with all the app ids and integration through various channels. 

But I still find it strange that when the prompt is presented to the user and the user replies. It again prompts back.

So, I have to answer the prompt twice and then everything seems to be ok.

**Comment by v-thgratMSGit** [comment]
Closing this issue due to age. @officialdharam - please open a new issue if this issue is not fixed and needs further discussion. Thanks!

**Comment by Stevenic** [comment]
There was a bug preventing this from working correctly. Please try again with v3.2.3. I'll re-open the issue if it's still not working.

**Comment by officialdharam** [comment]
@Stevenic  this is a good news... Thanks a lot of your help!
