### ISSUE TITLE
[.Net SDK, QnA Maker, MS Teams] The new QnA Bot doesn't answer in Teams, but working in the WebChat

### ISSUE THREAD

**Issue by Jessica1980** [Microsoft/BotBuilder#4780]
## Bot Info
SDK Platform: .NET
SDK Version: current Azure version (do not know where I can check it in Azure)
Active Channels: MS Teams, Direct Line
Deployment Environment: Azure Bot Service

## Issue Description
I've created the QnA Bot, activated the channel MS Teams (have status "run"). But the bot doesn't answer in MS Teams. In the WebChat all is ok.
![teams](https://user-images.githubusercontent.com/40513670/41806680-787df2b8-76cb-11e8-96f1-b5673fca08a6.png)
![webchat](https://user-images.githubusercontent.com/40513670/41806681-789cc0e4-76cb-11e8-96ce-656873d21d92.png)

## Code Example
Standard QnA Bot in Azure, I haven't edited the code.

## Reproduction Steps
1. Activated the channel MS Teams
2. Get the link for MS Teams
3. Send the messages to the bot in MS Teams - no answers
4. Send the message to the bot in the WebChat - receive the answer

## Expected Behavior
I expect the answer in MS Teams.

## Actual Results
No error messages. Just have no answer in MS Teams. But in the WebChat all is ok.

**Comment by brandon1780** [comment]
Web chat descrambled in the build _freged itself true buffer built for an hour then extracted its in the time of march web chat install err accured

**Comment by brandon1780** [comment]
Its missing support plug for mic

**Comment by brandon1780** [comment]
Hello world

**Comment by JasonSowers** [comment]
@Jessica1980 I'm not sure I follow what your issue is, can you please share your code and explain what is going wrong for you?

@brandon1780 I have no idea what you are talking about here, can you please open a new issue detailing what your issue is?

**Comment by JasonSowers** [comment]
Closing as no response
