### ISSUE TITLE
[.Net SDK, Skype] Mention one bot from another doesn't work

### ISSUE THREAD

**Issue by khawarashraf** [Microsoft/BotBuilder#4782]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.15.2.2
* Active Channels: Skype
* Deployment Environment: Azure Bot Service

## Issue Description
I have a Bot1, a user send a message to Bot1 in group chat, Bot1 responds and mentions user in reply. It correctly tiggers for user that his/her name is mentioned. 

I have another Bot2 in the same group chat, when Bot1 mention it in the reply, Bot2 does not get any notification.

## Code Example
replyActivity.Text = $"Hello <at id=\"{Bot2ID}\">Bot2</at>";
replyActivity.Entities.Add(new Mention() { Mentioned = new ChannelAccount() { Id = $"{Bot2ID}" }, Text = $"<at id=\"{Bot2ID}\">Bot2</at>", Type = "mention" });
replyActivity.ChannelData = new JObject() { ["text"] = $"Hello <at id=\"{Bot2ID}\">Bot2</at>" };
await context.PostAsync(replyActivity);

## Reproduction Steps
1. Add two bots in group chat
2. Post a message in the group chat from Bot1 mentioning Bot2
3. Bot2 does not receive any message.

## Expected Behavior
Bot2 should get message.

## Actual Results
Bot2 does not receive any message

**Comment by nyxsys** [comment]
As mentioned in [this stackoverflow](https://stackoverflow.com/questions/41156529/bot-listening-to-another-bot-in-group-conversation) question bots cannot actually directly message other bots within channels like skype, slack etc to prevent them from getting into an infinite conversation. 

If you want to pass information from one bot to another a bot to could post a message to skype and then also [send a directline message](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-concepts?view=azure-bot-service-3.0#sending-messages) to your other bot, which it could respond to.

**Comment by khawarashraf** [comment]
Thank you.
