### ISSUE TITLE
[Node.js SDK] Userdata state out of sync in middleware send/receive

### ISSUE THREAD

**Issue by tmikest** [Microsoft/BotBuilder#4784]
## Bot Info
* SDK Platform: Node.js
* SDK Version: 3.13.1
* Active Channels:  Bot emulator
* Deployment Environment: local development with Emulator

## Issue Description
I want to log text sent by user and bot. I am using the bot middleware and the session.userData object for this. I push an object into an array in the userData object. However, the values in the array are not the same every time it is updated. The userData object contains different data during handling of the "receive" event than it does when handling "send" for example. This sounds confusing, the reproduction below illustrates it better.

Perhaps it is an async issue I'm having. I don't have a lot of experience with nodejs.
## Code Example
```
bot.use({
  receive: function(event, next) {
   
    var turn_data = {
      speaker: "user",
      text: event.text
    };

    logConversationData(event, turn_data, next);
    
  },
  send: function(event, next) {
    var turn_data = {
      speaker: "bot",
      text: event.text
    };

    logConversationData(event, turn_data, next);
    
  }
});

function logConversationData(event, turnData, next) {
  if (!turnData) {
    console.log("error: no turnData object");
    next();
    return;
  }

  if(event.type === "conversationUpdate"){
      next();
      return;
  }

  if(!turnData.text){
      next();
      return;
  }

  turnData.date_time = new Date();

  bot.loadSession(event.address, function(error, session) {
    var conversationId = event.address.conversation.id;

    if (!session.userData.conversations) {
      session.userData.conversations = {};
    }

    if (!(conversationId in session.userData.conversations)) {
      session.userData.conversations[conversationId] = [];
    }

    session.userData.conversations[conversationId].push(turnData);
    session.save();
    next();
  });
  
}

---- greetings.js -----
lib.dialog("/", [function (session, result, next) {
    session.send("hello");
    next();
}, function (session) {
    session.replaceDialog("common.misc:/how_can_i_help");
}]);

---- common.misc.js -----
lib.dialog("/how_can_i_help", function (session, result, next) {
    session.endConversation("how can I help?");
});
```
## Reproduction Steps
1. User joins chat -> bot sends "welcome" -> gets logged
State of array: userData.conversations[id][{"welcome"}]
State of cosmosDb: {id: [{"welcome"}]}
2. user says "hi" -> "hi" gets logged in userData
State of array: userData.conversations[id][{"welcome"}, {"hi"}]
State of cosmosDb: {id: [{"welcome"},{"hi"}]}
3. bot replies  with "hello"
State of array: userData.conversations[id][{"welcome"}, {"hi"}, {"hello"}]
State of cosmosDb: {id: [{"welcome"},{"hi"}]} <- cosmosDb not updated correctly?
4. bot sends "how can I help?"
State of array: userData.conversations[id][{"welcome"}, {"hi"}, {"how can I help?"}] <- first reply from bot not present in userData array for some reason. 
State of cosmosDb: {id: [{"welcome"},{"hi"}, {"how can I help?"}]} 

## Expected Behavior
At the time the bot sends its second message in reply to "hi": "how can I help" I expect the userData object to contain the data set after sending the first message.
State of array: userData.conversations[id][{"welcome"}, {"hi"}, {"hello"}, {"how can I help?"}] 
State of cosmosDb: {id: [{"welcome"},{"hi"}, {"hello"}, {"how can I help?"}]} 

## Actual Results
State of array: userData.conversations[id][{"welcome"}, {"hi"}, {"how can I help?"}] 
State of cosmosDb: {id: [{"welcome"},{"hi"}, {"how can I help?"}]} 

How can I make sure the data in the array (and cosmosDb) stays in sync?
I have tried using async-lock around the operation where userData gets updated, but it doesn't seem to help.

Perhaps the issue occurs because I do a replaceDialog after sending "hello" from the bot?

Should I just write to cosmosDb directly using my own functions instead of using session.userData?

**Comment by stevengum** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
