### ISSUE TITLE
[Node.js SDK, DirectLine] message arrive late to client side from connector bot

### ISSUE THREAD

**Issue by ibrahemw** [Microsoft/BotBuilder#4785]
## Bot Info
* SDK Platform: Node.js
* SDK Version: 3.15.0
* Active Channels: Direct Line
* Deployment Environment: Azure Bot Service, Azure App Service

## Issue Description
sometimes from 4 - 10 min take for the message to arrive to client side from the connector bot.  we are facing this issue in daily basis... this behavior is not all the time but it is happens a lot.

## Reproduction Steps
run any flow, sometimes it is getting stuck for long time before the message arrive to the client.

## Expected Behavior
message received within a milliseconds to the client.

## Actual Results
message received after 4 min and sometimes after 10 min....

**Comment by stevkan** [comment]
Hi @ibrahemw,

You are using a slightly outdated version. The newest is v3.15.2.3. Can you please update and test again?

Also, are you performing any external calls that might interfere with the flow?

**Comment by ibrahemw** [comment]
Hi,

This is fine, we already had contact in Microsoft for Amdocs. And they identify the problem and they are delivering fix on 29.


This is the guys who Is handling us : Jose Pendao Jose.Pendao@microsoft.com<mailto:Jose.Pendao@microsoft.com>

And this is the SR number 118062718470907

**Comment by stevkan** [comment]
Hi @ibrahemw, thank you for the update. I will close this issue as resolved since a fix is being supplied externally from this.
