### ISSUE TITLE
[Node.js SDK, Azure App Service] Bot analytics doesn't show channel specific data

### ISSUE THREAD

**Issue by rjgmail88** [Microsoft/BotBuilder#4786]
## Bot Info
* SDK Platform:  Node.js 
* SDK Version: v3
* Active Channels: MS Teams, Skype, cortana
* Deployment Environment:  Azure App Service

## Issue Description
I have configured bot analytics as described here [https://docs.microsoft.com/en-us/azure/bot-service/bot-service-manage-analytics?view=azure-bot-service-3.0](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-manage-analytics?view=azure-bot-service-3.0)
After 2 days of activity I do not see anything data for RETENTION, USERS and Channel specific USERS. 
My bot has 3 channels (MS Teams, Skype, cortana) so as per the document I should be able to see messages, user volume for each channel separately. 
Why do I only see WebChat as the only channel in analytics. 

## Reproduction Steps
Configure analytics for any bot.

## Expected Behavior
I should be able to see dashboard as shows here [https://docs.microsoft.com/en-us/azure/bot-service/bot-service-manage-analytics?view=azure-bot-service-3.0#user](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-manage-analytics?view=azure-bot-service-3.0#user)

## Actual Results
![image](https://user-images.githubusercontent.com/32375467/41857936-3a260ae8-785e-11e8-89ed-59be7c293d28.png)
![image](https://user-images.githubusercontent.com/32375467/41857940-3c250f60-785e-11e8-89c2-48f08e0d8ed6.png)
![image](https://user-images.githubusercontent.com/32375467/41858019-6f7d67f4-785e-11e8-9236-fb44ff2b018d.png)

**Comment by nyxsys** [comment]
This is a known issue, and we are tracking its resolution in [this issue](https://github.com/Microsoft/BotBuilder/issues/4769)

**Comment by rjgmail88** [comment]
Thank you. Any ETA on the fix ?

**Comment by rjgmail88** [comment]
@nyxsys , any update on this ?

**Comment by EricDahlvang** [comment]
Analytics not showing is being tracked here: #4500 I'm closing this issue as a duplicate. Please follow along @ #4500

**Comment by rjgmail88** [comment]
@EricDahlvang , #4500 is closed and not sure why. Quick glance at the end in comments shows it fixed but I still see issue with my Bot #984ede7e-bc35-4767-a19b-60a2d6c5e4be

**Comment by EricDahlvang** [comment]
#4500 is not closed.  I'm not seeing anything about it being fixed.
