### ISSUE TITLE
[.Net SDK, Skype, RichCards] Skype bot herocard image not shown in Android 5.1.1

### ISSUE THREAD

**Issue by JonesAbramoff** [Microsoft/BotBuilder#4787]
## Bot Info
* SDK Platform: .NET
* SDK Version: 15.2.2
* Active Channels: Skype and others
* Deployment Environment: Azure App Service

## Issue Description
Herocard works perfectly in Skype bots in PC and more recent Android versions but in Android 5.1.1 the image is not shown. The same chat in Android and in PC, one works right and the other does not.

The Skype app was installed today and I checked that there was no update in play store for it.

## Code Example
heroCard.Images = new List<CardImage>
                        {
                            new CardImage(objRet.CardFigura)
                        };

## Expected Behavior
Show image

## Actual Results
The herocard is show with title, buttons but no image.

**Comment by stevengum** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
