### ISSUE TITLE
[.Net SDK, WebChat] When user clicks the adaptive card... The chat window does not scroll automatically 

### ISSUE THREAD

**Issue by maheshksingh** [Microsoft/BotBuilder#4789]
## Bot Info
* SDK Platform: .NET
* Active Channels: web chat 
* Deployment Environment: 

## Issue Description
When the user selects an adaptive card, the chat window does not auto scroll down to show the chat response

Please help

## Expected Behavior
The chat window shud auto scroll top show the chat response

## Actual Results
The user needs to scroll manually to see the response... Sometimes he ends up clicking the button multiple times

**Comment by compulim** [comment]
Dupe of https://github.com/Microsoft/BotFramework-WebChat/issues/470.

**Comment by vishwacsena** [comment]
Resolving as dupe to the issue in the webchat repo.

**Comment by maheshksingh** [comment]
Thanks all.. Will try the JS solution...
