### ISSUE TITLE
Facebook Bot

### ISSUE THREAD

**Issue by mikkhait** [Microsoft/BotBuilder#479]
Sorry for [cross-posting](https://feedback.botframework.com/forums/354222-bot-builder-sdk/suggestions/14794734-facebook-bot)

We already have a good number of [official bots](https://github.com/Microsoft/BotBuilder/tree/master/Node/lib/bots). We also have [unofficial](http://docs.botframework.com/builder/node/bots/other-platforms).

I would like to request an official Facebook Bot.

Pretty, please...

**Comment by willportnoy** [comment]
Facebook Messenger is a supported channel in the Bot Framework:

http://docs.botframework.com/faq/#is-facebook-messenger-a-supported-channel

**Comment by mikkhait** [comment]
Thanks @willportnoy, but I'm looking for a standalone bot, without Bot Connector framework. I want to connect it directly to FB.

**Comment by mikkhait** [comment]
Hey @Stevenic, your thoughts?

**Comment by Stevenic** [comment]
I would suggest waiting a couple of weeks. We're working on the initial drop of BotBuilder 2.x and for the Node side there's a new UniversalBot that replaces all of the existing bots. It's connector based so it would be pretty straight forward to build a FacebookConnector that lets your UniversalBot speak natively to Facebook. It's probably not a connector we would build but if the community wanted to build that connector we would definitely support the effort.

**Comment by Stevenic** [comment]
By the way... The old `BotBuilderBot` and `TextBot` classes will still be there, they're just marked as deprecated so log a warning to the console.  The `LuisDialog` and `CommandDialog` classes are also deprecated.  There's a new `IntentDialog` class that combine the functionality of both.  You now create one or more `LuisRecognizer` instances which you pass to an `IntentDialog`. All of the new classes are way more flexible and in many cases simpler to use.

**Comment by andrew-makarenko** [comment]
I haven't found even unofficial standalone FB bot connector, so here is mine: https://www.npmjs.com/package/botbuilder-facebook

Maybe it will be useful for somebody

**Comment by Stevenic** [comment]
awesome @andrew-makarenko. Would be great if you could update this to the new connector model when 2.x is released in a few weeks. Should be simpler then implementing a FacebookBot as you no longer have to deal with implementing the management of sessions or support for storage. The new UniversalBot takes care of that for you.

As a preview here's part of the code for the new ConsoleConnector. I left out the attachment rendering code I wrote (its nasty) but you get the gist.  There are 3 required methods: onMessage(), send(), and startConversation().  There's some new schema elements you'll need to map into but should be pretty straight forward. 

```

import readline = require('readline');
import ub = require('./UniversalBot');
import mb = require('../Message');
import utils = require('../utils');

export class ConsoleConnector implements ub.IConnector {
    private handler: (messages: IMessage[], cb?: (err: Error) => void) => void;
    private rl: readline.ReadLine;
    private replyCnt = 0;
    
    public listen(): this {
        this.rl = readline.createInterface({ input: process.stdin, output: process.stdout, terminal: false });
        this.rl.on('line', (line: string) => {
            this.replyCnt = 0;
            line = line || '';
            if (line.toLowerCase() == 'quit') {
                this.rl.close();
                process.exit();
            } else if (this.handler) {
                // TODO: Add some sort of logic to support attachment uploads.
                var msg = new mb.Message()
                    .address({
                        channelId: 'console',
                        user: { id: 'user', name: 'User1' },
                        bot: { id: 'bot', name: 'Bot' },
                        conversation: { id: 'Convo1' }
                    })
                    .timestamp()
                    .text(line);
                this.handler([msg.toMessage()]);
            }
        });
        return this;
    }
    
    public onMessage(handler: (messages: IMessage[], cb?: (err: Error) => void) => void): void {
        this.handler = handler;
    }
    
    public send(messages: IMessage[], cb: (err: Error, conversationId?: string) => void): void {
        for (var i = 0; i < messages.length; i++ ){
            if (this.replyCnt++ > 0) {
                console.log();
            }
            var msg = messages[i];
            if (msg.text) {
                log(msg.text);
            }
            if (msg.attachments && msg.attachments.length > 0) {
                for (var i = 0; i < msg.attachments.length; i++) {
                    if (i > 0) {
                        console.log();
                    }
                    renderAttachment(msg.attachments[i]);
                }
            }
        }        
    }

    public startConversation(address: IAddress, cb: (err: Error, address?: IAddress) => void): void {
        var adr = utils.clone(address);
        adr.conversation = { id: 'Convo1' };
        cb(null, adr);
    }
}
```

**Comment by andrew-makarenko** [comment]
@Stevenic Thanks! I will implement the new UniversalBot soon in a 'develop' branch and will publish it to npm as  soon as botbuilder 2.x released.

**Comment by v-thgratMSGit** [comment]
Closing this issue. Thanks!
