### ISSUE TITLE
[.Net SDK] Context Wait randomly fails/The same "Wait Method" is called two times in a row

### ISSUE THREAD

**Issue by petergoat** [Microsoft/BotBuilder#4792]
## Bot Info
* SDK Platform: NET
* SDK Version: 3.15
* Active Channels: Facebook
* Deployment Environment: Azure App Service and Azure Table for Bot Data

## Issue Description
Hi, we've developed a BOT with some dialog connected each other with the Context.Wait(Method).
Each post a message and set another method dialog in wait for the next message.

## Code Example
Our Message Controller:

`        [ResponseType(typeof(void))]
        public async Task<HttpResponseMessage> Post([FromBody]Activity activity)
        {
            if (activity.GetActivityType() == ActivityTypes.ConversationUpdate)
            {
                if (activity.MembersAdded.Any(m => m.Id != activity.Recipient.Id))
                {
                    activity.Type = ActivityTypes.Message;
                    activity.Text = _startGreetingsMessage;
                }
            }

            if (activity.GetActivityType() == ActivityTypes.Message)
            {
                using (var scope = DialogModule.BeginLifetimeScope(Conversation.Container, activity))
                {
                    var dialog = scope.Resolve<IDialog<object>>();
                    await Conversation.SendAsync(activity, () => dialog);
                }
            }
            else
            {
                HandleSystemMessage(activity);
            }

            var response = Request.CreateResponse(HttpStatusCode.Accepted);
            return response;
        }
`
Our RootDialog inherits from Luis:
`
    [Serializable]
    public class RootDialog : LuisDialog<object>
    {
        private readonly IDialogFactory _dialogFactory;

        public RootDialog(ILuisService luisService, IDialogFactory dialogFactory)
            : base(luisService)
        {
            _dialogFactory = dialogFactory;
        }

        [LuisIntent("None")]
        public async Task NoneIntent(IDialogContext context, LuisResult result)
        {
             await context.PostAsync(MessagesResource.CourtesyError);
             context.Call(_dialogFactory.Create<GreetingDialog>(), Callback);
        }

        [LuisIntent("Greetings")]
        public async Task GreetingsIntent(IDialogContext context, LuisResult result)
        {
            context.Call(_dialogFactory.Create<GreetingDialog>(), Callback);
        }

        [LuisIntent("CreateNewList")]
        public async Task CreateNewListIntent(IDialogContext context, LuisResult result)
        {
            context.Call(_dialogFactory.Create<CreateNewShoppingListDialog>(), Callback);
        }

        [LuisIntent("OpenLastList")]
        public async Task OpenLastListIntent(IDialogContext context, LuisResult result)
        {
            context.Call(_dialogFactory.Create<OpenLastShoppingListDialog>(), Callback);
        }

        [LuisIntent("GetTimetables")]
        public async Task GetTimetablesIntent(IDialogContext context, LuisResult result)
        {
            context.Call(_dialogFactory.Create<OpeningHoursDialog>(), Callback);
        }

        [LuisIntent("GetPromo")]
        public async Task GetPromoIntent(IDialogContext context, LuisResult result)
        {
            context.Call(_dialogFactory.Create<PromoProductsByCategoryDialog>(), Callback);
        }

        [LuisIntent("")]
        public async Task CancelIntent(IDialogContext context, LuisResult result)
        {
            await context.PostAsync(MessagesResource.CourtesyError);
            context.Call(_dialogFactory.Create<GreetingDialog>(), Callback);
        }

        private async Task Callback(IDialogContext context, IAwaitable<object> result)
        {
            await result;
            context.Done(true);
        }
    }
`
Example how we se the wait between dialog parts:
`
    [Serializable]
    public class AskIfAddAnotherProductTask
    {
        private readonly IShoppingListsService _shoppingListsService;
        private readonly IDialogFactory _dialogFactory;
        private readonly ILogger _logger;

        public AskIfAddAnotherProductTask(IDialogFactory dialogFactory, IShoppingListsService shoppingListsService, ILogger logger)
        {
            _shoppingListsService = shoppingListsService;
            _dialogFactory = dialogFactory;
            _logger = logger;
        }
        public async Task GetTask(IDialogContext context, IAwaitable<IMessageActivity> result)
        {
            var userResponse = await result;
            var channel = context.Activity.ChannelId;

            var dict = new Dictionary<string, object>() { { "context", context } };

            var luisResult = await LuisHelper.GetIntentAndEntitiesFromLUIS(userResponse.Text);

            switch (luisResult.TopScoringIntent.Intent)
            {
                case LuisIntent.Yes:
                    {
                        await context.PostAsync(MessagesResource.AddOtherProducts);
                        context.Wait(_dialogFactory.Create<GetProductsByUserTask>().GetTask);
                        break;
                    }
                case LuisIntent.No:
                    {
                        var sender = _dialogFactory.Create<SendCorrectYesOrNoCard>(dict);
                        await sender.Send(channel, MessagesResource.AskIfWantSuggestions);

                        var handler = _dialogFactory.Create<HandleUserIncorrectInput>(dict);
                        handler.ResetCounter();

                        context.Wait(_dialogFactory.Create<AskIfWantSuggestionProductsTask>().GetTask);
                        break;
                    }
                default:
                    {
						await context.PostAsync(MessagesResource.CourtesyChooseError);

						var sender = _dialogFactory.Create<SendCorrectYesOrNoCard>(dict);

						await sender.Send(channel, MessagesResource.AskIfWantAddProduct);

						context.Wait(GetTask);
                        break;
                    }
            }
        }
    }
`

## Reproduction Steps
It's randomly, there is no specific step to reproduce.

## Expected Behavior
Always callback the right method :-)

## Actual Results
Some times, randomly, we experienced the fact that the same "method in wait" is called two time in a row... like something is failing in the last insert of a method in wait or something like that....
Anyone have some ideas about that? We've tried several option and workaround with no success...

> ##UPDATE:
> 
> Basically we have this situation: RootDialog -> context.call(DialogA, RootDialogCallback) -> context.wait(MethodFromAnotherClass1) .... -> context.wait(MethodFromAnotherClassN) -> context.done() -> RootDialogCallback -> context.done()
> 
> This is working approximately 70-80% of the times... So my question is: it's correct to link method from different classes with the Context.Wait or this kind of approach could lead to some random issue like the one we are experiencing?

**Comment by nyxsys** [comment]
closing this so we can track it in [your SO question](https://stackoverflow.com/questions/51041554/context-wait-randomly-fails-the-same-wait-method-is-called-two-times-in-a-ro).
