### ISSUE TITLE
[Skype For Business] Deploying to Skype For Business not working at all

### ISSUE THREAD

**Issue by Rykimaruh** [Microsoft/BotBuilder#4794]
Hi,

So we are trying to deploy a bot that is in Azure to Skype For Business for our organization. However we followed the instructions given where you need to install and run some cmdlets that has AppId, sip and bot name. We tried it and nothing but an error. This is what happens.

I erased or partially erased some info for sake of privacy:
![errorr](https://user-images.githubusercontent.com/5460795/41919005-80d72dc8-792b-11e8-8632-a989ca8ec0d3.png)

We called Microsoft for support and they said that since it's in Preview they don't offer that support yet which I find very strange...considering that a lot of companies most likely have used skype for business to deploy...

Anyone can help out with this issue, know what could be the cause? 

Thank you!

**Comment by stevengum** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
