### ISSUE TITLE
Skype 12 shutting down when bot sends card with video

### ISSUE THREAD

**Issue by ivan-zarudnyi** [Microsoft/BotBuilder#4797]
## Bot Info
* SDK Platform: Node.js 
* SDK Version: 3.15.0
* Active Channels: Skype 
Windows 10 Pro x64
Skype 12.1815.209.0
* Deployment Environment: Azure App Service

## Issue Description
When bot sends rich card with video skype application shutting down

## Code Example
```
let attachmentsConf =  new builder.VideoCard(session)
            .title("Video card title")
            .media([{url: "https://aliabot818b.blob.core.windows.net/aliabot/c6a35b94-31d5-4c7a-80de-e422c5a2dae2.mp4"}])
            .autostart(true)
        ;


        let msg = new builder.Message(session)
            .attachments([attachmentsConf]);

        session.send(msg);
```

## Reproduction Steps
1. Send rich card with video to user

## Expected Behavior
Message with video card appears in skype

## Actual Results
Skype shutting down after a second

Issue reproduction video https://drive.google.com/open?id=18PVeDzks1ovlQbDC2Oh67OtNEb-9feK2
The same issue with audio card.
All cards works fine is Skype 8.*, facebook, webchat and emulator

**Comment by EricDahlvang** [comment]
@ivan-zarudnyi  Thank you for reporting this.  

The Skype team is aware of this bug.  We will report back here as we hear updates from them.

**Comment by stevengum** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
