### ISSUE TITLE
C# waterfall validate input from adaptive card

### ISSUE THREAD

**Issue by mennolaan** [Microsoft/BotBuilder#4798]
## Bot Info
* SDK Platform: .net
* SDK Version: 4.0
* Active Channels: Direct Line
* Deployment Environment:  local development with Emulator? -->

#found the solution with decrement a step.

**Comment by tauseefiftm** [comment]
Hi 
Kindly share the solution for validation of input with adaptive cards as in my case i wanted to validate Phone number and email.
Kindly guide me.
