### ISSUE TITLE
https://join.skype.com/bot not adding the contact in Android

### ISSUE THREAD

**Issue by JonesAbramoff** [Microsoft/BotBuilder#4799]
Hi,

I would like to promote my page with icons to start chats with my bots in smartphones and it is working fine with FB Messenger, Telegram and other channels.

Using https://join.skype.com/bot/ac573e18-18eb-48e7-856a-51ddeb3b6185 in Android opens Skype app but don´t show the page to add the bot as a contact.

I am not sure if its because it was previously added and removed.

**Comment by nyxsys** [comment]
Can you please tell me what version of android and skype you are using and if you are still seeing this problem? I was able to add your bot as a contact via that link in android on the most recent version of skype.

**Comment by JonesAbramoff** [comment]
Hi,

I am using Android 6.0.1 and Skype

**Comment by EricDahlvang** [comment]
Hi @JonesAbramoff 

Would you please confirm if this issue is still occurring?

**Comment by JonesAbramoff** [comment]
Hi,

It seems to be fixed,

Thanks.
