### ISSUE TITLE
Messenger channel has stopped working

### ISSUE THREAD

**Issue by stuartd** [Microsoft/BotBuilder#4800]
## Bot Info
* SDK Platform:  .NET 
* SDK Version: 3.15.2.2
* Active Channels: Messenger, DirectLine
* Deployment Environment: Azure Bot Service (S1 tier) , Azure App Service, (Standard 1: Medium)

## Issue Description
Since last Friday our Messenger channel has stopped working. We receive messages from Messenger, but when sending the response - any response, even the "IsTyping" message - we receive a 400 error (BadRequest):

    Microsoft.Bot.Connector.ErrorResponseException: Operation returned an invalid status code 'BadRequest'  

This code has not been changed recently, and the DirectLine and WebChat channels work correctly with the same code.

I've downloaded all the logs from the App Service - Web server logging, Failed request tracing, Application logs - but I can't find any clue in there as to why this is happening. I've checked the Facebook developer console but everything there is 'green'.

Is there any way of finding out why this is happening? Any suggestions on things to try to fix it?

**Comment by JasonSowers** [comment]
@stuartd can you share a code snippet so we can try to reproduce as you are doing this?

**Comment by stuartd** [comment]
@JasonSowers here's the code that sends the IsTyping response:

```c#
// 'activity' is the incoming message
var connector = activity.CreateConnectorClient();
var isTypingReply = activity.CreateReply();
isTypingReply.Type = ActivityTypes.Typing;
await connector.ReplyAsync(isTypingReply);
```

**Comment by stuartd** [comment]
The stack trace of the error is this:

> Microsoft.Bot.Connector.ErrorResponseException: Operation returned an invalid status code 'BadRequest'  
   at async Task<HttpOperationResponse<ResourceResponse>> Microsoft.Bot.Connector.Conversations.ReplyToActivityWithHttpMessagesAsync(string conversationId, string activityId, Activity activity, Dictionary<string, List<string>> customHeaders, CancellationToken cancellationToken)  
   at async Task<ResourceResponse> Microsoft.Bot.Connector.ConversationsExtensions.ReplyToActivityAsync(IConversations operations, string conversationId, string activityId, Activity activity, CancellationToken cancellationToken)  
   at async Task<ResourceResponse> MSBotExtensions.ReplyAsync(ConnectorClient client, Activity reply) in MSBotExtensions.cs:line 23  
   at async Task Controllers.MessagesController.SendIsTypingResponse(Activity activity, ConnectorClient connector) in MessagesController.cs:line 506  
   at async Task Controllers.MessagesController.processIncomingMessage(Activity message) in MessagesController.cs:line 331  
   at async Task<HttpResponseMessage> Controllers.MessagesController.Post(Activity activity) in MessagesController.cs:line 102

**Comment by JasonSowers** [comment]
Is the bot still functioning normally, but just this error is coming through as well? I'm not exactly sure what you mean by this in yout original post:

> We receive messages from Messenger

**Comment by stuartd** [comment]
> Is the bot still functioning normally,

No: we receive messages _from_ Messenger, but whenever we try to _respond_ to the message we get this error.

Other channels work with the same code.

**Comment by stuartd** [comment]
I'm wondering now if the Messenger registration (page access token etc) has somehow expired and needs to be refreshed. Is that a possibility?

**Comment by JasonSowers** [comment]
It may be, but that is not something I have experienced.  I did get a warning in the facebook dev portal on one of my bots earlier this week regarding something about having to get reapproved by facebook.  I wonder if this might be the cause as well.  I honestly didn't really read it because it is just a test bot, so I do not recall the exact details.

**Comment by stuartd** [comment]
That's this one:

> App Review submission required by August 1, 2018 to retain access to Facebook Platform APIs

I'm going to refresh the registration.

**Comment by stuartd** [comment]
Going to open an issue with FB to try and get some visibility into why this is failing.

**Comment by JasonSowers** [comment]
@stuartd would you mind letting us know what you find as it may help others as well?

**Comment by stuartd** [comment]
@JasonSowers of course..

**Comment by stuartd** [comment]
Using [ngrok to debug locally](https://blog.botframework.com/2017/10/19/debug-channel-locally-using-ngrok/) I have determined the underlying issue:

```json
{
  "error": {
    "code": "MissingProperty",
    "message": "The bot referenced by the 'from' field is unrecognized"
  }
}
```

This is now with Azure support for resolution.

**Comment by JasonSowers** [comment]
Have you tried deploying a test bot to Facebook to see if the issue occurs in another bot for you? I was just doing some Facebook testing yesterday with no issues still.

**Comment by stuartd** [comment]
Turns out there was an internal misconfiguration. This was the resolution from MS Support:

> The Product Group has checked the records and there is a record for the Facebook Channel that does not match the configuration you set up... The Product Group has fixed the record for the Facebook channel and now the bot should be working.

And [it is working](https://www.messenger.com/t/SfCabBot).
