### ISSUE TITLE
Hero card text not showing in facebook

### ISSUE THREAD

**Issue by pankajGODB** [Microsoft/BotBuilder#4803]
For hero card text wrap is not possible?
In Emulator its worked but in fb the same is not working kindly can you guys provide any solution for this

![heroemulator](https://user-images.githubusercontent.com/30646163/42028449-ed50c3fa-7ae9-11e8-8e8d-743d5903ea08.png) ===> Emulator screenshot
![herofb](https://user-images.githubusercontent.com/30646163/42028450-ed85c88e-7ae9-11e8-80a7-704e10dbe534.png) ===> Fb screenshot

Below is the used code

`var card = new builder.HeroCard(session)
						.title('BotFramework Hero Card')
						.subtitle('Your bots — wherever your users are talking')
						.text('Build and connect intelligent bots to interact with your users naturally wherever they are, from text/sms to Skype, Slack, Office 365 mail and other popular services.')
						.images([
							builder.CardImage.create(session, 'https://sec.ch9.ms/ch9/7ff5/e07cfef0-aa3b-40bb-9baa-7c9ef8ff7ff5/buildreactionbotframework_960.jpg')
						])
						.buttons([
							builder.CardAction.imBack(session, 'GetMessage', 'Get Started')
						]);
						var msg = new builder.Message(session).addAttachment(card);
						 session.send(msg);`

**Comment by Kartik1607** [comment]
Facebook controls how a card is rendered on messenger platform. For now, [facebook template](https://developers.facebook.com/docs/messenger-platform/reference/template/generic#elements) only have a field for title and subtitle. This is why you can't see the text which you are sending in hero card.

For now, you can try to use [adaptive cards](http://adaptivecards.io), if it fits your use case scenario. Be aware, that for now adaptive cards are also not fully supported and are down-rendered to image in many cases.

**Comment by JasonSowers** [comment]
To extend on what @Kartik1607  said every channel has their own limitation on how rich content is rendered.  THis includes text length, title length, number of buttons, etc.

**Comment by pankajGODB** [comment]
@Kartik1607 Thanks for your advice.
I have tried the same using Adaptive card but that too is not working. Is there any other alternative to use text as wraped with images and button?

@JasonSowers Then how will we use bot for facebook with these features?

**Comment by JasonSowers** [comment]
If the restrictions on generic templates, which are [documented here](https://developers.facebook.com/docs/messenger-platform/reference/template/generic/#elements) of the Facebook API do not work to suit your needs, you will need to find another way to display your information in the bot.  There isnt any changes we can make to the SDK to allow this.  It is a limitation of Facebook messenger.  If you need to display an image with text and buttons you could try the combination of sending the image and text and using suggested actions/quick replys for your buttons.

**Comment by pankajGODB** [comment]
@JasonSowers Thanks for your help.
Really looking for further more features ifs there please suggest me.

**Comment by Kartik1607** [comment]
@pankajGODB You would need to think of creative ways how you can send information to user overcoming the limitation of a channel. 
 
You do not need to provide a single card for all channels. I would recommend going to channel documents, and learning best practices for that channel. Then you can always send different cards on different channels.

**Comment by pankajGODB** [comment]
@Kartik1607  I have tried many features but while trying some more things, not worked for fb. That's why come here for help. I have already went through the document.
Thank for you help.

**Comment by JasonSowers** [comment]
Good luck!

**Comment by pankajGODB** [comment]
In hero card button text is not showing can you please help on this?

![screenshot 18](https://user-images.githubusercontent.com/30646163/43306569-3ddce7de-9199-11e8-9257-18cfa24c751c.png)

**Comment by Noc2** [comment]
Same here. I'm using c# and recently update my bot, now all buttons are just 3 dots!

**Comment by fj4870** [comment]
Same here.. It was working fine since morning but now I am getting 3 dots in all the buttons..

**Comment by JasonSowers** [comment]
@pankajGODB @Noc2 @fj4870 You are commenting on a closed issue that is not related to what you are reporting, please open a new issue and we can address the problem there

**Comment by Noc2** [comment]
@JasonSowers  Thanks, but Facebook already fixed it.

**Comment by JasonSowers** [comment]
Good to hear
