### ISSUE TITLE
Facebook user name is empty for non english language

### ISSUE THREAD

**Issue by DrNixx** [Microsoft/BotBuilder#481]
If Facebook user have only name for native language and don't have english name, incoming bot message have empty string for Message.From.Name.
Maybe it is Facebook bag?

**Comment by tomlm** [comment]
We call into facebook graph
https://graph.facebook.com/v2.6/{envelope.sender.id}
and use the $"{facebookUser?.first_name} {facebookUser?.last_name}", fields.

Facebook must not be returning the infromation
