### ISSUE TITLE
Testing BotFramework Authentication Code

### ISSUE THREAD

**Issue by xitij** [Microsoft/BotBuilder#4811]
## Bot Info
* SDK Platform: Node.js
* SDK Version: v3.14.1
* Active Channels: Skype, Facebook, Slack, Kik, Telegram, Emulator
* Deployment Environment: local development with Emulator

## Issue Description
Hi, I've recently been going through the authentication [docs](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-authentication?view=azure-bot-service-3.0) and am attempting to authenticate requests coming into my bot. I've got what I believe to a be a proper authentication service based on the docs and I'm now looking to write some unit tests to confirm this. 

Currently I'm able to use breakpoints in local dev to grab the `Bearer Token` that I'm receiving from the Bot Framework API, but I was wondering if it's possible to generate one of these token on my own via an API (with my bot's credentials) for testing purposes? Is this currently possible?

Currently I'm attempting to get a token via "Step 1" on the linked docs but I'm having some issues. I'm not sure if this is due to the token I'm using or my authentication code.

## Code Example
Here is an example of my test (I've left out some code and used comments in some places):
```
const fetch = require('node-fetch');
const formUrlEncoded = require('form-urlencoded');

const getAuthTokenFromMicrosoft = async (appId, appSecret) => {
  const res = await fetch('https://login.microsoftonline.com/botframework.com/oauth2/v2.0/token', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
    },
    body: formUrlEncoded.default({
      scope: 'https://api.botframework.com/.default',
      grant_type: 'client_credentials',
      client_id: appId,
      client_secret: appSecret,
    }),
  });
  const json = await res.json();
  if (json.error) throw new Error(`${json.error}: ${json.error_description}`);
  return json;
};

const getAppKey = async (keyId) => {
  const url = 'https://login.microsoftonline.com/botframework.com/v2.0/.well-known/openid-configuration';
    const res = await fetch(url, {
      method: 'GET',
    });
    const openIdConfig = await res.json();
    // Check for errors here...

    const openIdRes = await fetch(openIdConfig.jwks_uri, {
      method: 'GET',
    });
    const data = await openIdRes.json();
    // Error check here...
    const keys = data.keys;
    const appKey = keys.find(key => key.kid === keyId);
    assert(appKey, `Unable to find Microsoft key with keyId: ${keyId}`);
    assert(appKey.n, 'Microsoft Key missing modulus');
    assert(appKey.e, 'Microsoft Key missing exponent');

    return { key: getPem(base64url.toBase64(appKey.n), appKey.e), endorsements: appKey.endorsements };
};

const authenticateRequest = async (req) => {
  const authHeader = req.headers ? req.headers['authorization'] || req.headers['Authorization']
      : undefined;
  let token;
  if (authHeader) {
    const auth = authHeader.trim().split(' ');
    if (2 === auth.length && 'bearer' === auth[0].toLowerCase()) {
      token = auth[1];
    }
  }
  if (token) {
    const decodedToken = jwt.decode(token, { complete: true });
    // Check the auth version here... via decodedToken.payload.ver (should be 1.0 or 2.0)
    // Check the appId here...via decodedToken.payload.azp or decodedToken.payload.appId
    // Check issuer here...via decodedToken.payload.iss
    const verifyOptions = {
      algorithms: ['RS256', 'RS384', 'RS512'],
      issuer: decodedToken.payload.iss,
      audience: MSAPP_ID,
      clockTolerance: 300,
    };
    const appKey = await getAppKey(decodedToken.header.kid);
    if (appKey) {
      try {
        jwt.verify(token, appKey.key, verifyOptions);
      } catch (err) {
        log.error(`authoken: ${token}, appId: ${this.appId}`);
        throw new Error('Invalid AuthToken. Check app ID and password');
      }
    }
  }
  return { id: this.appId, type: IBMS_APP_TYPE };  
};

describe('microsoft authenticator', () => {
  const req = {
    headers: {
    },
    body: {
      channelId: 'emulator',
      type: 'message',
      app: 'test-app',
      recipient: { id: '1123', name: 'foo' },
      from: { id: '12356' },
      conversation: { id: '1123-12356' },
      id: '98765',
      serviceUrl: 'https://service-url',
      channelData: { text: 'some text' },
      text: 'some text',
      locale: 'en',
    },
  };

  it('should run authenticator successfully for auth emulator', async () => {
    const bearer = await getAuthTokenFromMicrosoft(APP_ID, APP_PASSWORD);
    req.headers.authorization = `Bearer ${bearer.access_token}`;
    try {
      await authenticateRequest(req);
    } catch (e) {
      // some error handling
    }
  });
});
```

## Reproduction Steps
1. `POST https://login.microsoftonline.com/botframework.com/oauth2/v2.0/token
Content-Type: application/x-www-form-urlencoded
grant_type=client_credentials&client_id=MICROSOFT-APP-ID&client_secret=MICROSOFT-APP-PASSWORD&scope=https%3A%2F%2Fapi.botframework.com%2F.default`
2. Parse out `Bearer Token`
3. Decode the key via `jwt.decode()`
4. Get Bot key via OpenIdConfig
5. verify key via `jwt.verify()`
6. Authentication code throws error.

I realize that there are 2 separate urls for OpenId Config for emulator vs other channels. The code snippet above only uses the emulator one and I'm always failing on the `jwt.verify()` step. I'm wondering if I'm getting the token from the correct url? Is there a way better test this process without waiting for actual traffic to me bot via the BotFramework API?

## Expected Behavior
I'd like to be able to make a call to an API with my bot credentials and get back a valid token that I can use to test my bot's authentication service.

## Actual Results
Not that.

Thanks in advance.

**Comment by stevkan** [comment]
Hi @xitij, I'm looking into this issue and will reach back to you with questions.

**Comment by xitij** [comment]
Thanks.

**Comment by JasonSowers** [comment]
@xitij It looks like you are comparing a raw bearer token to the decoded key id here `jwt.verify(token, appKey.key, verifyOptions);`.  These would not match.  I'm not 100% sure what is going on with this code, but that is what it looks like to me.  What exactly are you trying to test?


> I was wondering if it's possible to generate one of these token on my own via an API (with my bot's credentials) for testing purposes? Is this currently possible?

To my knowledge, you would need the certificate we use to generate this (or at least the secret key).  I Will ask someone more knowledgeable about this topic than myself, but I think the answer would be no.

**Comment by xitij** [comment]
> It looks like you are comparing a raw bearer token to the decoded key id here `jwt.verify(token, appKey.key, verifyOptions);`.

The above section of code that you quoted works in the case that I receive the Bearer Token from you (Microsoft) via a "real" request.

It also matches the code you linked in the "Verify Token Section" which is what I originally looked at.

> To my knowledge, you would need the certificate we use to generate this (or at least the secret key). I think the answer would be no.

This is what I figured.

> What exactly are you trying to test?

I want to test that my "authentication" code works. To do that I want to be able to "generate" a valid Bearer Token that will `jwt.decode()` and `jwt.verify()` in my test to prove that my code is correct. I can use the token I receive via a "real" request but eventually that token times out. Ideally I would be able to generate a token each time the test is run to verify my code.

I hope that's clear...please let me know otherwise.

Thanks again for the response.

**Comment by JasonSowers** [comment]
I get what you are saying. I'm not much of a ts/js dev so I wasn't exactly sure what that method was doing.  I don't hang out in the node SDK much :smiley:

You aren't going to be able to generate a new token on demand within your tests, but as long as you have valid credentials you can make the call for one.  You also have the option of generating a similar token, but again it wouldn't actually be one from our service.

**Comment by xitij** [comment]
> I get what you are saying. I'm not much of a ts/js dev so I wasn't exactly sure what that method was doing. I don't hang out in the node SDK much

No problem, thanks for the attention to this thread.

> You aren't going to be able to generate a new token on demand within your tests, but as long as you have valid credentials you can make the call for one.

So I can make a call with my credentials to get the `Bearer Token` in my test and then peel that out and verify my code? Just want to make sure I understand what you are suggesting.

**Comment by JasonSowers** [comment]
Yes that is exactly what I am suggesting. I have not personally tried to test this but I do not see why it wouldn’t work for your test.  Let me know the results and we can further look into this if needed.

**Comment by JasonSowers** [comment]
Please open a new issue if you are still experiencing problems
