### ISSUE TITLE
LuisDialog Doesn't Support Sentiment

### ISSUE THREAD

**Issue by JranZu** [Microsoft/BotBuilder#4819]
LUIS now support Sentiment, but LuisDialog doesn't pull that info in. It would be nice if it did.

https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-quickstart-intent-and-sentiment-analysis#query-the-endpoint-with-an-utterance

```
...
"sentimentAnalysis": {
    "label": "positive",
    "score": 0.8694164
  }
```

**Comment by jwiley84** [comment]
Duplicate of #4806
