### ISSUE TITLE
Matching menu entries must match with or without acents in builderPromptschoice

### ISSUE THREAD

**Issue by rouscast** [Microsoft/BotBuilder#482]
When creating a bot that displays a list of options (builder.prompts.choise)
containing accented words, writing any of them without accents is not recognized as part of the list, and the user gets the message: ". I did not Understand Please Choose an option from the list.".
In Spanish at least, a meny entry should be able to match with and without accents, because people usually do not write accents over vowels during an informal chat (like with a  bot).

**Comment by chrimc62** [comment]
Are you talking about the node or C# SDK?

**Comment by rouscast** [comment]
Hi,in node

**Comment by v-thgratMSGit** [comment]
Closing this issue due to age. @rouscast - please open a new issue if this issue is not fixed and needs further discussion. Thanks!

**Comment by Stevenic** [comment]
Good bug... We can look into improving this. @chrimc62 what does C# do in this case?

**Comment by Andrea-Orimoto** [comment]
Added to our bug backlog, closing the issue.
