### ISSUE TITLE
Unicode query String containing special character is truncated and query with non special character is sent for quering solr Indexing backend

### ISSUE THREAD

**Issue by pra527vin** [Microsoft/BotBuilder#4826]
I am running janusgraph with cassandra as storage backend and solr as Indexing backind .When I index unicode string with UTF-8 character sequenc it is successfully store and index but when searching the query string is truncated before it is sent to solr server from janusgraph server

my query looks like this 
 g.V().has('contentNepali',textContains('आइतबार'))

but query string becomes "आइतब" when the request goes from janusgraph to solr
I have seen the query string in janusgraph log

**Comment by EricDahlvang** [comment]
Hi @pra527vin 

This is the Microsoft BotBuilder repository, for BotBuilder issues and feature requests.  Your issue appears to be related to janusgraph, cassandra and solr.  Have you tried their forums?
