### ISSUE TITLE
[Nodejs] Sudden openID failure on our production servers

### ISSUE THREAD

**Issue by Kannaj** [Microsoft/BotBuilder#4828]
## Bot Info
* SDK Platform:  Node.js 
* Active Channels: All
* Deployment Environment: Azure App service

## Issue Description
Our production bot was working fine until 1 hour ago when our logs started showing the below error
```
ERROR: Error retrieving OpenId metadata at https://login.botframework.com/v1/.well-known/openidconfiguration, error: Error: Failed to load openID config: 500
ERROR: ChatConnector: receive - invalid signing key or OpenId metadata document.
```

There were no new changes added to our system for almost 2 days. The bot no longer seems to be responding to our messages

our MSA app id - 71fad264-9fd6-4ecd-808d-becdbc3b7eb1

**Comment by EricDahlvang** [comment]
Hi @Kannaj 

Are you still having this issue?

**Comment by rjgmail88** [comment]
We are also facing the same issue on production Bot.

**Comment by EricDahlvang** [comment]
There were some intermittent service issues this morning, but they have since been resolved.  @rjgmail88 is your bot experiencing this right now?  or was it earlier?

**Comment by rjgmail88** [comment]
I saw it this morning now sure if its now.

**Comment by Kannaj** [comment]
Still seeing this on an intermittent basis unfortunately . Will get you a timestamp -
my bot id - 71fad264-9fd6-4ecd-808d-becdbc3b7eb1

**Comment by EricDahlvang** [comment]
This appears to have been a transient issue.  We apologize for the inconvenience.
