### ISSUE TITLE
Error in Directline

### ISSUE THREAD

**Issue by neetgupta7** [Microsoft/BotBuilder#4829]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.15.2
* Active Channels: Direct Line
* Deployment Environment:  Azure App Service

## Issue Description
Facing error "There was an error sending this message to your bot: HTTP status code GatewayTimeout" on directline channel. Started coming up suddenly this morning. There has been no deployment or setting change for over a week now. And is happening with 4 bots. One of our MS App id is 9d73ce60-e9ef-4295-af99-3ddf32e8d6fd. Please help fix this.

**Comment by JasonSowers** [comment]
please track this issue in #4833
