### ISSUE TITLE
Receiving OpenId Error in Bot Service

### ISSUE THREAD

**Issue by jrios6** [Microsoft/BotBuilder#4836]
I have a Azure Bot Service deployed with LUIS and QnA Maker integration. I am occasionally receiving the following errors, with the chatbot crashing. After a while, the chatbot starts working again without error. Please help.

ERROR: Error retrieving OpenId metadata at https://login.botframework.com/v1/.well-known/openidconfiguration, error: Error: Failed to load openID config: 500

ERROR: Error retrieving OpenId metadata at https://login.botframework.com/v1/.well-known/openidconfiguration, error: Error: Failed to load Keys: 503
ERROR: ChatConnector: receive - invalid signing key or OpenId metadata document.

**Comment by JasonSowers** [comment]
@jrios6 can you please post in #4828 where a similar issue has been reported.  This way we do not 2 issues for the same thing going, thanks for reporting this.
