### ISSUE TITLE
Need access to conversation id of webchat bot

### ISSUE THREAD

**Issue by vaditya04** [Microsoft/BotBuilder#484]
I've embedded the chat bot into my webpage using the iframe method detailed in http://docs.botframework.com/connector/embed-chat-control/#navtitle

I want to get access to the conversation id of the web chat so I can programmatically send the bot messages without user involvement.

My idea is to start off the web chat using a POST request to /api/conversations and get a conversation id and token, start the iframe using the token, and programmatically message the bot using the conversation id.

Would this work? Is it supported? Is there a better way?
Thanks!

**Comment by vaditya04** [comment]
@tomlm Hi - any insights on this?

**Comment by dandriscoll** [comment]
You should use the Direct Line API. Web Chat and Direct Line share a service and are currently able to cross conversations, but the conversation-crossing ability will go away soon and the protocols may diverge eventually (although no current plans to do that -- just no guarantees they'll stay the same).

If you use the Direct Line side, you keep complete control over your conversations, and you can use access that conversation from more than one place as long as you a) know the conversation ID, and b) have a secret or token that grants you access to that conversation.

**Comment by vaditya04** [comment]
@dandriscoll Is there a chat box interface that comes along with the Direct Line API? I would prefer not to write my own UI. The web chat was convenient because I could embed it, it was ready out of the  box.

**Comment by Lipa9963** [comment]
@vaditya04  you find some chat box interface for the Direct Line AP?
Thanks

**Comment by dandriscoll** [comment]
Hi @Lipa9963 and @vaditya04, the new Bot Framework Web Chat control is now open-source and forkable if you want deeper access to the API. https://github.com/Microsoft/BotFramework-WebChat

**Comment by Lipa9963** [comment]
Hi,
you can find it too for C# web app ?

Thanks!

**Comment by dandriscoll** [comment]
Hi @Lipa9963, the chat control is JavaScript and is run in the client browser. You can serve the page from a website coded in C#.
