### ISSUE TITLE
Bot no longer responding in Teams chat

### ISSUE THREAD

**Issue by PerrineJaccard** [Microsoft/BotBuilder#4840]
Hi, 

I've built a C# bot which has been working very well, but on Friday it stopped responding completely. I still get a 'bot is typing' message for a while then it goes away with no reply.

The bot works as expected in the Azure test chat, and also replies in my Teams group but not in private chat.

I've tried changing the messaging endpoint, adding the skype channel then removing it, removing the Teams channel and re-adding it, re built the code but nothing makes a difference. 

<img width="785" alt="screen shot 2018-07-09 at 09 24 51" src="https://user-images.githubusercontent.com/38947937/42440538-eef831e4-835d-11e8-882e-f3b2b8ce2612.png">

<img width="348" alt="screen shot 2018-07-09 at 09 53 50" src="https://user-images.githubusercontent.com/38947937/42440600-1cfa4ad2-835e-11e8-95c6-14dd9a84c829.png">

**Comment by PerrineJaccard** [comment]
Problem solved - was a looping issue in the code.

**Comment by jwiley84** [comment]
Thank you for the update!
