### ISSUE TITLE
Skype bot message end point updating issue

### ISSUE THREAD

**Issue by Prathibha-Prakash** [Microsoft/BotBuilder#4841]
@Hi everyone, my bot is working properly in emulator while i updating with a new message endpoint .
But through skype channel it shows an error “There was a problem synchronizing your bot to Skype.” 

My  Bot details :
   
    App ID : 6d3b7574-6049-4377-8c27-34908d3602bb
    BotHandle : cars_finds
    Active Channels: Skype, Web Chat
    Message endpoint : https://7bf9c8e8.ngrok.io/api/gogoDevice/skype?secretkey=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhcGlUb2tlbiI6IjZkM2I3NTc0LTYwNDktNDM3Ny04YzI3LTM0OTA4ZDM2MDJiYiIsImJvdE1lc3NhZ2UiOiJxZ25jaGF1S1k3NTQ3QH1eT0ZMTFE5KCIsImlhdCI6MTUzMTEyMDA4OX0.hJJpRpp2AbqHuTMPDP377G0abvDf3d4YzAe1H_7x6rM
Plz guide me .

**Comment by EricDahlvang** [comment]
@Prathibha-Prakash I apologize for the delayed response.  Have you been able to work passed this issue?

It is sometimes necessary to change the messaging endpoint multiple times, in order to force propagation of the settings to the Skype connector services.

**Comment by EricDahlvang** [comment]
Closing due to no response.
