### ISSUE TITLE
[Feature Request] Skype calling bot voice support for Bing voices

### ISSUE THREAD

**Issue by camer314** [Microsoft/BotBuilder#4845]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.15
* Active Channels: Skype
* Deployment Environment: Azure Bot Service

## Issue Description
I am opening a new issue that is the same as #2886 

The answers provided require a call to the Bing API (or alternatively using a local TTS) however my explicit request was that for a Skype CALLING bot that it natively supports the Bing voices. I do not want to have to use an external TTS, the Skype bot API on the Prompt should allow you to configure the voice to use, you do not have any option other than the single voice Skype provides.

As mentioned, if you use an external TTS that takes time, you then need to send back an WAV file to the client. All i want to do is send back the text and the voice and let Skype sort it out, this seems by far the most efficient way.

## Code Example
None

## Reproduction Steps
Try and change the voice Skype using in its calling bot!

## Expected Behavior
As per description

## Actual Results
You cannot change the voice and for that matter even the gender - it is always female!

**Comment by JasonSowers** [comment]
Thank you for your input.  This is not something that is currently on our radar but is something we could look at adding in the future.

**Comment by stevengum** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
