### ISSUE TITLE
Token issues with the AADv1 sample bot

### ISSUE THREAD

**Issue by Rykimaruh** [Microsoft/BotBuilder#4846]
Greetings,

I've been following an article that talks about adding authentication to a bot and how to set up an application and a bot so that I may be able to use some of the tasks with MS Graph

Link [here](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-authentication?view=azure-bot-service-3.0)

The bot has 3 simple tasks:
1. recents - checks any unread email in the last 30 mins
2. send - sends email on your behalf
3. me - shows your name and who you report to if any

When i write "recents", the bot will ask me to sign in using an oauth card. I sign in and then get a 6 digit magic number. I copy/paste it to the chatbot and it then validates me.

The problem happens when I write "recents" again, the bot prompts me to sign in again. It doesn't cache the token as it should or at least I expect it to...should which is to recognize me. 

Is there something missing from that article?  I am using AADv1 to test authentication[ link](https://github.com/Microsoft/BotBuilder/tree/master/CSharp/Samples/AadV1Bot)

**Comment by xiaolangxyz** [comment]
I have the same problem. But I even cant get magic number. the login in window just closed automatically.

**Comment by Rykimaruh** [comment]
@xiaolangxyz , did you enable authentication in the emulator?

**Comment by xiaolangxyz** [comment]
@Rykimaruh No. Just waiting for someone who can help.

**Comment by JasonSowers** [comment]
Thank you for reporting this, I am currently troubleshooting this walkthrough, I will update you when I have more information.

**Comment by JasonSowers** [comment]
Ok, I have this working and am seeing the same behavior as you are.  This may be intentional behavior, I am not sure.  I will update you when I have more information.

**Comment by JasonSowers** [comment]
@Rykimaruh we just pushed a fix and caching the token should be enabled now!  Please try again and let us know your results.

**Comment by JasonSowers** [comment]
@Rykimaruh this is working for you now correct?

**Comment by Rykimaruh** [comment]
@JasonSowers , yes! thank you very much! 

before wrapping all of this up, do you have any idea or information about dealing with authentication behind a corporate network that uses proxy and firewall? 

I noticed that this works perfect in wifi, however when i connect to my corporate network that has a proxy it denies any attempts. We have Microsoft whitelisted, but not sure if there are certificates that need to be added or what.

**Comment by JasonSowers** [comment]
There is currently a bug in Webchat that the identity team is looking into.

**Comment by Rykimaruh** [comment]
@JasonSowers , thanks for the update!

**Comment by JasonSowers** [comment]
Closing this as it seems resolved please open a new issue if you experience more problems
