### ISSUE TITLE
Bot Framework VS Template Malformed html in default.htm

### ISSUE THREAD

**Issue by TraGicCode** [Microsoft/BotBuilder#485]
It looks like there is a missing closing 'pre' tag in the default.htm file generated by the Visual studio bot framework project template.  Causes a bit of an annoyance for developers who are using tools that perform static/live code analysis.

![image](https://cloud.githubusercontent.com/assets/6224270/16076683/29541656-32ba-11e6-80f4-16609dfcc7b6.png)

**Comment by dandriscoll** [comment]
Thank you, will fix!
