### ISSUE TITLE
Getting Dependency Errors (404) in Application Insights, while using Cosmos DB as State Store in .Net based Bot.

### ISSUE THREAD

**Issue by mutanttech** [Microsoft/BotBuilder#4850]
## Bot Info
* SDK Platform: .NET
SDK Version: 3.12.2.4
Active Channels: Direct Line
Deployment Environment: Azure Bot Service, Azure App Service

## Issue Description
Getting Dependency Errors (404) in Application Insights, while using Cosmos DB as State Store for the Bot.
The Bot SDK is probably unable to fetch the documents from the Cosmos DB and recording 404, while I am able to see the documents in the DB.

## Code Example
N/A

## Reproduction Steps
1. Look into other bots having Cosmos DB as data store and DB provisioned in one region only.

## Expected Behavior
Ideally, there should be no 404 errors while reading data from Cosmos DB. I am not sure how to fix it as it is being done through SDK.

## Actual Results
Application Insights shows 404 errors while getting documents which probably are accessed by the Bot SDK. The url that are shown as failure have the format:
http://[CosmosDBServiceName]-[Location].documents.azure.com/

I have provisioned only one Cosmos Instance in West Europe Region. In fact the Application Map under App Insights shows two Azure Document DB, I am not sure know why. I have experimented with both ETagBaseConsistency and LastWriteWins. Let me know which one to use.

Below is compiled picture to speak more about the error, some names are removed. Please help me how to fix this issue.
![image](https://user-images.githubusercontent.com/98785/42614176-41f3b5ec-85c2-11e8-8322-bef6af910934.png)

**Comment by EricDahlvang** [comment]
Which version of BotBuilder-Azure are you using?  

404's when querying DocumentDb/CosmosDb are a known issue: https://github.com/Azure/azure-documentdb-dotnet/issues/219

You can see in the source for DocumentDbBotDataStore.cs that HttpStatusCode.NotFound exceptions are caught, and handled accordingly: https://github.com/Microsoft/BotBuilder-Azure/blob/master/CSharp/Library/Microsoft.Bot.Builder.Azure/DocumentDbBotDataStore.cs

**Comment by mutanttech** [comment]
Eric, thanks for responding, I am using **BotBuilder-Azure 3.2.5**. 
I am not directly querying the documents from State Log, I believe SDK is doing so but failing with 404's which are getting recorded in AppInsights. 
I don't see the source code of BotBuilder-Azure v3.2.5 on [github](https://github.com/Microsoft/BotBuilder-Azure/releases)
I checked the code is handling the NotFound exception, but it seems to be a newer version.

**Comment by mutanttech** [comment]
Please advice..

**Comment by EricDahlvang** [comment]
The point i was trying to make is that the 404's are not real errors.  https://github.com/Azure/azure-documentdb-dotnet/issues/219  The underlying library used by BotBuilder-Azure produces 404 exceptions when attempting to retrieve a document that does not exist.  This is a known issue with querying DocumentDb/CosmosDb.  For now, you will need to just filter them out of your analytics.
