### ISSUE TITLE
PSID, webview and the messenger_extensions parameter

### ISSUE THREAD

**Issue by catcher-in-the-try** [Microsoft/BotBuilder#4852]
## Bot Info
* SDK Platform: Node.js
* SDK Version: 3.15
* Active Channels: Facebook
* Deployment Environment: Azure App Service

## Issue Description
Some features in Facebook Messenger's webview do not work if the incoming message does not contain the `messenger_extensions: true` property. In particular, one cannot get the user ID (PSID) of the user and execute the `getContext()` function of the Facebook SDK.

Currently `botbuilder` does not provide a way to set the `messenger_extensions` parameter, unless you create the entire message by yourself in the Facebook native format and place it into the `channelData` property of the message.

## Expected Behavior
- For HeroCards, there needs to be a way to set a parameter which ultimately results in this: the message sent from Bot Framework to Facebook contains the property `messenger_extensions: true`.

**Comment by EricDahlvang** [comment]
Hi @catcher-in-the-try 

Thank you for this suggestion.  I've added it to the Facebook Messenger Feature Request issue: https://github.com/Microsoft/BotBuilder/issues/4360  We are currently using this to track all Facebook Messenger feature requests.
