### ISSUE TITLE
Same conversation ID being generated for a user when they message for second time via Skype channel

### ISSUE THREAD

**Issue by ashi1702** [Microsoft/BotBuilder#4853]
**Bot Info**
* SDK Platform: Node.js 
* SDK Version: v3
* Active Channels: Skype
* Deployment Environment: Azure Bot Service

**Issue Description**
same value of `message.address.conversation.id` is being generated whenever a user comes back and chats again via skype channel (not business). The previous chat is ended using `session.endConversation`  before he comes back and chats again. 
I'm using Mongo Db to store user conversations. The user has logged into skype using the web control generator explained here [https://dev.skype.com/webcontrol](url)

## Expected Behavior
Everytime a user chats via skype channel, i want a new conversation ID to be generated even if the same user comes back (provided the previous chat is ended). Why I want this is because in the middleware code (node modules/botbuilder-handoff/handoff.js) provided by MS 
(`const conversation = yield this.getConversation({ customerConversationId: message.address.conversation.id }, message.address);`) 
creates a new DB object whenever a new/unique conversation ID is being encountered. But in my case same conversation ID is being generated due to which user's transcript is being appended to the old DB object. I want a new Db object created based on conversationId whenever a user starts chat via skype.

## Actual Results
**message object from console:**
 `{ text: 'hi',
  type: 'message',
  timestamp: '2018-07-11T12:12:38.86Z',
[ { locale: 'en-US',
       country: 'US',
       platform: 'Windows',
       type: 'clientInfo' } ],
  sourceEvent: { text: 'hi' },
  attachments: [],
  address:
   { id: '1531311158852',
     channelId: 'skype',
     user: { id: '29:1LAFIMGBY8uSW9-Nf9jfHnAGiS-6qUT0zq9NYjxcEvu8' },
     conversation: { id: '29:1LAFIMGBY8uSW9-Nf9jfHnAGiS-6qUT0zq9NYjxcEvu8' },
     bot:
      { id: '******',
        name: '******' },
     serviceUrl: 'https://smba.trafficmanager.net/apis/'
	 },
  source: 'skype',
  agent: 'botbuilder',
  user: { id: '29:1LAFIMGBY8uSW9-Nf9jfHnAGiS-6qUT0zq9NYjxcEvu8' } }`

**Stored Database object:**
`	"_id" : ObjectId("5b3b390139994f2f40fa74ca"),
	"customer" : {
		"serviceUrl" : "https://smba.trafficmanager.net/apis/",
		"bot" : {
			"name" : "*******",
			"id" : "*******"
		},
		"conversation" : {
			"id" : "29:1LAFIMGBY8uSW9-Nf9jfHnAGiS-6qUT0zq9NYjxcEvu8"
		},
		"user" : {
			"name" : "Shilpa A R",
			"id" : "29:1LAFIMGBY8uSW9-Nf9jfHnAGiS-6qUT0zq9NYjxcEvu8"
		},
		"channelId" : "skype",
		"id" : "1530607871887"
	},
`

**Screenshot from MongoDB** - all the chats for this user is being appended to the same DB object
![skype output](https://user-images.githubusercontent.com/22766446/42629061-bf1b62ae-85ef-11e8-83c6-b18280124b0e.PNG)

1. I'm not able to figure out why this is happening.
2. Also, on another observation i found that user ID and conversation ID are same for skype channel - is this normal ?
>

**Comment by corinagum** [comment]
Hi ashi1702, 

What you have listed as your issue is actually the expected behavior of a Skype channel bot. [link](https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-state?view=azure-bot-service-3.0)

The Skype channel persists conversation data with the same user between sessions - conversation data is initiated when the user adds the bot to contacts, as opposed to each time the conversation starts. 

If you're interested in having your bot delete the data every time the conversation ends, I've found some helpful information [here](https://stackoverflow.com/questions/42936592/how-to-call-deleteuserdata-or-deleteprofile-on-skype-bot). You can use this to delete the conversationData from you db if the user hasn't spoken to the bot for a set amount of time.

**Comment by ashi1702** [comment]
Hi Corinagum,

Thanks for your prompt reply!

I did check the [https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-state?view=azure-bot-service-3.0](link) that tells about state data. These have already been handled in my bot code, is there any other link which explicitly tells about Skype channel state data ?

Also, I don't want to delete the data every time the conversation ends, in-fact I want a unique entry every time a conversation starts. What would be the best approach to do this ? I need to use this to display bot metrics about total conversations happening via different channels. 

Thanks!

**Comment by corinagum** [comment]
Hey ashi1702, 
I'm sorry to say that there doesn't seem to be any documentation explicitly explaining that Skype channel handles the conversationID as being the userID. I have found a few links that anecdotally point this out though.

[Build Skype bot with Bot Framework](https://tsmatz.wordpress.com/2016/08/19/build-skype-bot-with-microsoft-bot-framework-oauth-and-rest-api/)

> The “29%3A1iFtpwQ…” in the uri fragment (which is url-encoded) is the conversation id. When your bot is sending the message to some user, **this conversation id is the user id itself**.

(emphasis mine)

[Question: Inconsistent Conversation IDs for Skype](https://github.com/Microsoft/BotBuilder/issues/3263)

> ... the takeaway is that Skype conversationIds are not reliable and we should not use it to store BotData. ... PS: As a workaround we ignore the conversationId Skype sends back and use the users id, but that will fail when/if Skype changes the way they create/handle conversationIds.

[How to get conversationID for sending Skype message](https://github.com/Microsoft/BotBuilder/issues/1196)

> It's possible to obtain conversationId by sending /get name to specified group chat (doesn't work for 1-1 chats), answer will be like this: name=19:6bdf98504....9@thread.skype

Hope that helps.
