### ISSUE TITLE
Proactive message to Facebook Messenger rejected

### ISSUE THREAD

**Issue by JpEncausse** [Microsoft/BotBuilder#4854]
## Bot Info
* SDK Platform: Nodejs
* SDK Version: 3.x
* Active Channels: Messenger
* Deployment Environment: Production on Bot Chanel Registration

## Issue Description

Our platform use Bot Framework to send proactive message 
https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-proactive-messages?view=azure-bot-service-3.0

Facebook updates it's policy a month ago and require custom message type for  NON_PROMOTIONAL_SUBSCRIPTION after 24hrs
https://developers.facebook.com/docs/messenger-platform/send-messages/message-tags

See documentation
https://developers.facebook.com/docs/messenger-platform/reference/send-api/

In a Nutshell, 

- since 07/05/2018 and Messenger v2.2 messaging_type must be set in all message. 
- since 31/12/2017 and Messenger v2.3 proactive message are sent to page not app.
- It seems there is no clear answer for that https://github.com/Microsoft/BotBuilder/issues/4154

## Reproduction Steps
Very Hard
1. Plusblish a bot on Messenger
2. Wait +24h
3. Send a proactive message
4. Get an error on Messenger Page (not app)

## Expected Behavior
- An option, description, documentation of how to override the messaging_type
- Is there a way to check the JSON message when Bot Registration forward it to Facebook Messenger to validate the option is correctly set ?

## Actual Results

Our app is rejected **in production** by Facebook since few days because of the missing or wrong messaging_type after a given amount of time.

**Comment by JasonSowers** [comment]
From their documentation it looks like Facebook is intentionally blocking many types of proactive messaging outside their 24 and 24+1 windows.  I was able to send a message of a recipt card and a message with just text using the code below to set the [channel data](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-channeldata?view=azure-bot-service-3.0). I did not test proactive messaging after 24 hours and I only tested the text message in node. I was just testing that you could set the `message_type` and `tag`, but with this information you should be able to use this for what you are trying to accomplish.

### C#
Recipt Card:
```cs
reply.ChannelData = JObject.Parse($"{{messaging_type: 'MESSAGE_TAG', tag: 'PAYMENT_UPDATE'}}");
```
And also just text:
```cs
reply.ChannelData = JObject.Parse($"{{messaging_type: 'MESSAGE_TAG', tag: 'GAME_EVENT'}}");
```

Here is the full code for the text only message (I'll spare you the recipt card):
```cs
        var activity = await argument as Activity;
        var reply = activity.CreateReply("your game is starting");
        reply.ChannelData = JObject.Parse($"{{messaging_type: 'MESSAGE_TAG', tag: 'GAME_EVENT'}}");
        await context.PostAsync(reply);
```

----------

### Node.JS
you would similarly set the `message_type` and `tag` the Node SDK like this:

```js
        msg.sourceEvent({
            facebook: {
                messaging_type: 'MESSAGE_TAG',
                tag: 'GAME_EVENT'
            }
        });
```

With the full code I used to make the message being:
```js
server.post('/api/messages', connector.listen());
var bot = new builder.UniversalBot(connector, function(session) {
    try {
        let msg = new builder.Message(session);
        msg.text("your game is starting")
        msg.sourceEvent({
            facebook: {
                messaging_type: 'MESSAGE_TAG',
                tag: 'GAME_EVENT'
            }
        });
        session.send(msg);
    } catch (e) {
        console.log(e);
    }
});
```

**Comment by josephktcheung** [comment]
I've tested with node.js that this FB button template source event seems to work:
```ts
const message = new Message(session);

message.sourceEvent({
  facebook: {
    tag: 'NON_PROMOTIONAL_SUBSCRIPTION',
    messaging_type: 'MESSAGE_TAG',
    attachment: {
      type: 'template',
      payload: {
        template_type: 'button',
        text: 'Button template',
        buttons: [
          {
            type: 'web_url',
            url: 'https://google.com',
            title: 'Google',
            messenger_extensions: true,
            webview_share_button: 'hide',
            webview_height_ratio: 'full',
          },
        ],
      },
    },
  },
});

session.send(message);
```
I guess it works because when I change `tag` from `NON_PROMOTIONAL_SUBSCRIPTION` to `lol` the bot throws `400 Bad Request` like you said. But I agree @JpEncausse that we should be able to check the JSON message generated by Bot Framework which is forwarded to Facebook just to make sure that the format is correct. Right now it's a bit of guess work.

Take the above source event as example, It's a bit confusing because from FB the format of a generic template message is like this:
```ts
{
  "recipient":{
    "id":"<PSID>"
  },
  "message":{
    "attachment":{
      "type":"template",
      "payload":{
        "template_type":"<TEMPLATE_TYPE>",
        ...
      }
    }
  }
}
```
and to use message tag the format is like this:
```
curl -X POST -H "Content-Type: application/json" -d '{
  "recipient": { 
    "id": "<PSID>"
  },
  "message":{
    ...
  },
  "messaging_type": "MESSAGE_TAG",
  "tag": "SHIPPING_UPDATE"
}' "https://graph.facebook.com/v2.6/me/messages?access_token=<PAGE_ACCESS_TOKEN>"  
```
So one would expect in botbuilder we should construct the `sourceEvent` like this (nesting `attachment` in `message`):
```ts
message.sourceEvent({
  facebook: {
    tag: 'NON_PROMOTIONAL_SUBSCRIPTION',
    messaging_type: 'MESSAGE_TAG',
    message: {
      attachment: {
        type: 'template',
        payload: {
          template_type: 'button',
          text: 'Button template',
          buttons: [
            {
              type: 'web_url',
              url: 'https://google.com',
              title: 'Google',
              messenger_extensions: true,
              webview_share_button: 'hide',
              webview_height_ratio: 'full',
            },
          ],
        },
      },
    },
  },
});
```
But in reality `attachment` doesn't need to be nested in `message`. My guess is that MS pick certain attributes from `sourceEvent` and put them in `message` object and set the other attributes at the same level of `message`?
That's why letting us know the final JSON message created by bot framework that get sent to the channel would be very helpful, since we know how to construct `sourceEvent` correctly.

**Comment by JasonSowers** [comment]
@josephktcheung I completely understand your concern about seeing the final JSON sent to Facebook (and other channels for that matter).  This has been a pain point for us as well as our customers.  We are investigating ways we can make this possible.

**Comment by JasonSowers** [comment]
I have submitted a feature request for us to track this in GitHub #4858

**Comment by JasonSowers** [comment]
@JpEncausse and @josephktcheung  please let us know your results outside the 24 and 24+1 window.

**Comment by JasonSowers** [comment]
Going to close this issue as I assume it is resolved for all participating.  Please open a new issue if you require further assistance.
