### ISSUE TITLE
Skype for Business: Request does not reach server, "There was an error sending this message to your bot." is the only error

### ISSUE THREAD

**Issue by iniq** [Microsoft/BotBuilder#4855]
## Bot Info
* SDK Platform: Node.js
* Active Channels: Skype for Business, WebChat
* Deployment Environment: Azure Bot Service

## Issue Description
We have an Azure Bot Service integration that is currently working properly on two URLs and consistently generates an error message on a 3rd URL when triggered by the Skype for Business channel, but works perfectly for WebChat.

I have this specific bot pointed at an ngrok URL, and can verify that when invoked through Skype for Business no traffic/requests are recorded at all on our side.

When invoked through WebChat, the traffic/requests are received, recorded, and responded to by our integration without issue.

![image](https://user-images.githubusercontent.com/1020424/42655208-5ef95238-85e9-11e8-933f-8baa2f8b4323.png)

In chat, Skype for Business consistently gives this message:
`Error happened in Skype for Business service when reaching bot service.`

![image](https://user-images.githubusercontent.com/1020424/42655063-daa6c6aa-85e8-11e8-8513-7b6b1fd1941d.png)

In the Azure channels 'Health' report, the only error message given is:
`There was an error sending this message to your bot.` (There are no messages for the WebChat channel; its Health is green/'Running')

![image](https://user-images.githubusercontent.com/1020424/42654961-74ca2494-85e8-11e8-9549-7176439cb24b.png)

I have tried changing and resetting the messaging endpoint URL in case a bad value was cached in any way, but this has been happening for multiple weeks at this point (we gave up on the integration due to this issue for a while, but now need it).

We did have this working previously, and it works with the other two Bot Channels Registration entries that run from the same codebase (just different data = bots for different customers). We are unable to pinpoint what we could have changed to trigger this, and reverting our code makes no impact (the request continues to fail to even hit our servers).

At this point, we are unable to progress with our integration.
I'm more than happy to provide any additional information.

**Comment by kosset** [comment]
@iniq I've been developing bots on Skype for Business for the past 5 months and from my experience, I've found that Skype For Business has some trouble in setting the new Messaging Endpoint URL if you edit it through Azure Bot Service. 

When you edit the Messaging endpoint I would suggest you try deleting the Application Endpoint of Skype for Business, through cmdlets and Powershell and resetting it, or just edit it (for example try changing the friendly name). This might configure the new Messaging Endpoint for Skype for Bussiness, too. I'm not sure, but give it a try. :)

Cheers

**Comment by EricDahlvang** [comment]
@iniq Have you tried the suggestion from kosset?

**Comment by EricDahlvang** [comment]
Closing due to no response.

**Comment by iniq** [comment]
Thanks for the suggestions - I ended up having to just create a new bot.
These tricks for resetting it didn't seem to get it going again.
