### ISSUE TITLE
Private Message slack user?

### ISSUE THREAD

**Issue by TraGicCode** [Microsoft/BotBuilder#486]
This doesn't currently seem possible but all i am wanting to do is create a reply message, from a user from a public slack channel, and send them a private message that contains some temp password that was generated on the fly.  Is it possible to send a private message using the bot framework?  If so is can an example be provided?

**Comment by craigjensen** [comment]
You should be able to reply via a private message by setting the ConversationId and ChannelConversationId to null in the replay as follows:

replyMessage = message.CreateReplyMessage("reply text ...", "en");
replyMessage.ConversationId = null;
replyMessage.ChannelConversationId = null;
// send

**Comment by TraGicCode** [comment]
I'll give this a shot when i have the chance.  Do you also know how to address this the the user so they recieve the message as a private/direct message?  Which property on the Message type should be set and how?

**Comment by TraGicCode** [comment]
@craigjensen I got it working using the following code below.  The message comes in as a direct message on the slackbot private channel.  Do you know if its possible to have the bot actually start a direct message with the user instead of the communication happening through slackbot private message?

// Example of replying to a user.  This will actually reply to the user via slackbot
var replyMessage = message.CreateReplyMessage("reply text ...", "en");
replyMessage.ChannelConversationId = "@username";
return replyMessage;

**Comment by craigjensen** [comment]
Another way is to create a new message and set only the To and From fields.

var replyMessage = new Message()
{
   Text = "reply text",
   From = message.To,
   To = message.From
};
