### ISSUE TITLE
Welcome messages in skype are taking delay of around 5 sec. time to showup

### ISSUE THREAD

**Issue by saleemnasa** [Microsoft/BotBuilder#4861]
I have published my bot to skype channel, I am using "conversationUpdate" event to send welcome messages to user.

Its working as expected for web chat, but for skype channel which I integrated in to my site is taking delay in showing welcome messages to delay. I am using latest versions of sdk's

Thank You

**Comment by corinagum** [comment]
Hi saleemnasa, 

The Skype channel for Bot Framework does not have the **conversationUpdate** event. [Please see this related question](https://github.com/Microsoft/BotBuilder/issues/4831). Instead, you should use **contactRelationUpdate**. However, this functions differently from **conversationUpdate** in that it is only triggered when the bot is added or removed as a Skype contact.
