### ISSUE TITLE
[Bug] BotBuilder Prompt interruption by triggerAction causes bug

### ISSUE THREAD

**Issue by crisboarna** [Microsoft/BotBuilder#4864]
## Bot Info
* SDK Platform: Node.js
* SDK Version: 3.15.3, 3.15.0, 3.14.0, 3.13.0, 3.12.0, 3.11.0, 3.10.0 ...
* Active Channels: Facebook, Emulator
* Deployment Environment: Local Express + Emulator / AWS Lambda + ngrok / AWS Lambda + Messenger

## Issue Description
If a dialog that is waiting for a Prompt is interrupted by a dialog with a trigger that does not clear the stack (onSelectAction used) once the triggered dialog ends, the interrupted Prompt prints 'I didn't understand. Please try again.' message and does nothing else until I type something else, then it triggers next function in waterfall.

## Code Example
```typescript
var bot = new builder.UniversalBot(connector, [
    function (session) {
        session.send("Welcome to the dinner reservation.");
        session.beginDialog('askForName');
    },
    function (session, results) {
        session.dialogData.reservationName = results.response;
        session.endDialog();
    }
]).set('storage', inMemoryStorage); // Register in-memory storage 

// Dialog to ask for a name
bot.dialog('askForName', [
    function (session) {
        builder.Prompts.text(session, "Please provide a name for the reservation");
    },

    function (session, results) {
        session.endDialogWithResult(results);
    }
]);

bot.dialog('help', function (session, args, next) {
    //Send a help message
   session.send('Help');
    session.endDialog();
})
// Once triggered, will start a new dialog as specified by
// the 'onSelectAction' option.
.triggerAction({
    matches: /^help$/i,
    onSelectAction: (session, args, next) => {
        // Add the help dialog to the top of the dialog stack 
        // (override the default behavior of replacing the stack)
        session.beginDialog(args.action, args);
    }
});
```

## Reproduction Steps
1. Be at `askForName` dialog `Prompts.text` waiting for user input
2. Type help
3. Incorrect message `I didn’t understand. Please try again.` is sent.

## Expected Behavior
`Please provide a name for the reservation` to be sent to user.

## Actual Results
`I didn’t understand. Please try again.` is sent without resending the `Please provide a name for the reservation` message.

It seems that the Prompt is getting the dialog returned as a message event and although I also tried `endDialogWithResult` instead of `endDialog` it has not changed the behaviour, it is still detecting no input and stopping.

Could you please have a look at this as it is a serious issue that prevents usage of `.triggerAction` for more complex bots to handle conversational jumps to different sections of the conversation via LUIS.

#3391 ran into same issue but I cannot use the workaround with `.beginDialogAction` as I am using LUIS NLP Recognizer to trigger jumps in different sections/waterfalls which from my tests only works with `.triggerAction`.

**Comment by stevkan** [comment]
Hi @crisboarna, the bot isn't repeating the initial question because it has already passed that point of the code when the interruption occurs. Hence, when the dialog continues in the parent dialog it doesn't recognize the event that occurred and responds with the 'I didn't understand. Please try again.' message.

To mitigate this, use the 'retryPrompt' option in your Prompts code. When the parent 'askForName' dialog resumes, the prompt will be resent and the flow will continue as expected.

Hope of help!

```js
// Dialog to ask for a name
bot.dialog('askForName', [
    function (session) {
        builder.Prompts.text(session, "Please provide a name for the reservation", {
            retryPrompt: "Please provide a name for the reservation"
        });
    },
    function (session, results) {
        session.endDialogWithResult(results);
    }
]);
```

**Comment by stevkan** [comment]
Closing as resolved.
