### ISSUE TITLE
DirectLine Conversation Formatted Text only?

### ISSUE THREAD

**Issue by joewood** [Microsoft/BotBuilder#487]
Is there a way to receive message response metadata (e.g. action buttons etc..) with the DirectLine API?  When I use the DirectLine interface the messages only contain formatted text and no other metadata even though the Bot Service is providing action button information.

**Comment by XelaMon** [comment]
I'm having issues with this as well. The 'Attachments' specifically, seem to lack a lot of the data that I put into it with my bot. For example, the FallbackText, Title, TitleLink, etc. don't seem to come in through direct line. Also, the URLs that come in through attachments seem to be formatted differently than what I set them to. Do I need to call Direct Line again to get these images?

**Comment by dandriscoll** [comment]
Direct Line is currently simplifying some of these fields, and it recreates the attachment on its own service as they may not pass through from the bot. We're going to add more fidelity to a future version of the API, but I hadn't thought about changing the hosting URLs for attachments. Is it a problem that we copy the attachment to our own service before making it available through the API?

**Comment by XelaMon** [comment]
No, I realized later that I needed to prepend the 'directline.botframework.com' host to the beginning of the attachment ID that was given by the API
