### ISSUE TITLE
Microsoft.Bot.Connector.Directline.ChannelAccount does not have Properties field

### ISSUE THREAD

**Issue by ssong3k** [Microsoft/BotBuilder#4870]
Currently I am using the Directline package for C# and I noticed that I cannot specify additional properties to be passed to my bot using ChannelAccount. Why is there a different implementation of ChannelAccount in Microsoft.Bot.Connector.Directline vs Microsoft.Bot.Schema?

**Comment by stevengum** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
