### ISSUE TITLE
Group messages in SkypeBot

### ISSUE THREAD

**Issue by kelposun** [Microsoft/BotBuilder#4871]
In our company we need to transmit messages, that sent in Skype from our client to our developers Slack room. We develop a bot, that can do it, but, we can't listen all messages in group chat (without @botname mention). 
In [GitHub](https://github.com/Microsoft/BotBuilder/issues/1669) I was seen message, that say: "...developers can choose private mode or all messages mode". 

We really need this functional. How we can use it?

**Comment by kelposun** [comment]
But Sameroom bot for example can get all messages in group chat. Konnektor has connecting like a user, this feature allows you to get all group messages. This is sad ...

**Comment by EricDahlvang** [comment]
@kelposun I agree.
