### ISSUE TITLE
channelData deprecation

### ISSUE THREAD

**Issue by bswieser** [Microsoft/BotBuilder#4873]
## Bot Info
* SDK Platform: Node.js 
* SDK Version: 3.1
* Active Channels: Cortana
* Deployment Environment: Azure Bot Service

## Issue Description
channelData is deprecated - needs an update to sourceEvent 

## Code Example
new builder.Message(session)
    .setChannelData({
        action: {
            type: 'LaunchUri',
            uri: 'http://example.com/'
        }
    })

## Reproduction Steps
1. channel data is deprecated
2. sourceEvent doesn't seem to include information required to get cortana to response
3.

## Expected Behavior
Cortana should be able to assist the skill in performing actions on the appropriate device.

## Actual Results
Nothing.

**Comment by corinagum** [comment]
Are you able to share your code? Please feel free to add me privately so that I can take a look. 

Thank you!
