### ISSUE TITLE
LUIS api

### ISSUE THREAD

**Issue by usheveta** [Microsoft/BotBuilder#4877]
I need to create the dashboard present in LUIS in my site.
Are there any API's which can be used to create similar charts as present in LUIS dashboard?

**Comment by Zerryth** [comment]
Hi @usheveta! Succintly, there is currently not an API part of the Bot Framework / Cognitive Services that would all you to display the charts that you see in your LUIS AI Dashboard.

Any front end display you'd like to make on your website would have to be done by manually gathering information from LUIS and building out your own code from there.
