### ISSUE TITLE
How to call a Microsoft bot using a php script from botize?

### ISSUE THREAD

**Issue by fercom** [Microsoft/BotBuilder#488]
I have a bot created with Microsoft Bot Framework, it currently works on telegram, skype, facebook and web, I want to call it from twitter using Botize, they use php scripts but my bot is on C#. Is it posible to call my bot using a php script? if yes, how?

Thank you.

Here it is my bot, if you want to test it:

The memebot web [http://thememebot.com/](url)
on telegram [https://telegram.me/The_MemeBot](url)
on facebook [https://www.facebook.com/MemeBot-1118345044889141](url)
on skype [https://join.skype.com/bot/c0b2fa87-3625-43b2-be12-8eb1675818bb](url)

**Comment by chrimc62** [comment]
It is definitely possible.  You need to call it using either the Bot Connector Rest API: http://docs.botframework.com/sdkreference/restapi/#navtitle

or the Direct Line REST API: http://docs.botframework.com/sdkreference/restapi-directline/#navtitle

Please reopen if you need more information.
