### ISSUE TITLE
Webchat bot takes 20-30 seconds to answer the first message; works fine afterwards

### ISSUE THREAD

**Issue by anton-imago** [Microsoft/BotBuilder#4882]
## Bot Info
* SDK Platform: Node.js
* SDK Version: 3.15
* Active Channels: Webchat
* Deployment Environment: Azure App Service

## Issue Description

My webchat bot works as follows:

```
Browser (botchat.js) 
  => Microsoft Bot Framework servers 
    => My code (Azure App Service, Node.js, botbuilder) 
      => Another webservice 
        => Natural languge understanding engine
```

When the user sends the first message to the bot, it takes around 20-30 seconds for my code to receive it. My app service is set to "Always On" which means it does not need time to spin up.

If the users sends multiple messages, all of them arrive at the same time 20-30 seconds later, according to IIS logs. Then the bot responds to all of them immediately.

Subsequent messages are quick, unless the user stops talking to the bot for a few minutes.

The browser connection is stable, my app service is running, so it leaves the Microsoft Bot Framework service. Can you confirm that the Bot Framework servers need some time to start up when the conversation is just initiated?

## Expected Behavior
Webchat bot responds immediately.

## Actual Results
Webchat bot responds immediately, except on the first message from user to bot.

**Comment by corygehr** [comment]
+1 having the same issue using the C# libraries. I'm mostly using Teams but this tells me that there's something happening by using the Bot Framework service.

**Comment by corinagum** [comment]
@corygehr @anton-imago Thank you for your inquiry. Could one or both of you please provide me your Bot Handle ID in order to help me investigate further?

**Comment by corinagum** [comment]
Currently investigating with @corygehr's team's bot.

**Comment by corinagum** [comment]
@anton-imago I've worked with @corygehr on his bot, which looks like to be a known C# issue and unrelated to the problem with your Node bot. If you still would like support on this item, please get back to me with your BotHandleId and/or code base, and I'll be happy to help. Otherwise I'll be closing this issue tomorrow. Thanks!
