### ISSUE TITLE
Train Knowledge Base of QnAMaker does not work at GA/API4.0 ?

### ISSUE THREAD

**Issue by areckkimo** [Microsoft/BotBuilder#4884]
## Bot Info
* SDK Platform:Node.js
* SDK Version: 
* Active Channels: 
* Deployment Environment: Azure Bot Service

## Issue Description
Train Knowledge Base of QnAMaker (https://westus.dev.cognitive.microsoft.com/docs/services/58994a073d9e04097c7ba6fe/operations/58edd31c3d9e041ffcef000f) does not work at GA/API4.0?

If yes, does it has the alternative API?

thanks

## Reproduction Steps
1.
2.
3.

**Comment by EricDahlvang** [comment]
Hi @areckkimo 

The GA version of QnAMaker api does not currently provide training and active learning.  There is no workaround right now.  This issue is tracking the feature request: https://github.com/Microsoft/BotBuilder-CognitiveServices/issues/123  Please follow along there for updates.
