### ISSUE TITLE
Dispatch tool doesn't support v3 bot ?

### ISSUE THREAD

**Issue by rjgmail88** [Microsoft/BotBuilder#4886]
## Bot Info
* SDK Platform: Node.js
* SDK Version: 3.15
* Active Channels: MS Teams
* Deployment Environment: Azure App Service

## Issue Description
I see sample code here [https://github.com/Microsoft/botbuilder-js/blob/master/samples/dispatch-es6/app.js](https://github.com/Microsoft/botbuilder-js/blob/master/samples/dispatch-es6/app.js)
demonstrates how to use a LUIS model generated by the Dispatch tool [https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&tabs=jsaddref%2Cjsbotconfig#integrate-multiple-luis-apps-and-qna-services-with-the-dispatch-tool](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&tabs=jsaddref%2Cjsbotconfig#integrate-multiple-luis-apps-and-qna-services-with-the-dispatch-tool)

Is it possible to use SDK V3 Bot with Dispatch tool  ? We have v3 bot that's in production and we have gone so far now so its difficult to switch over v4 Bot. However, there are awesome capabilities like LUIS dispatch tool that we would like to leverage.

## Code Example
Is there any similar example in V3 like v4 [https://github.com/Microsoft/botbuilder-js/tree/master/samples/dispatch-es6](https://github.com/Microsoft/botbuilder-js/tree/master/samples/dispatch-es6)

## Expected Behavior
I should be able to use dispatch-tool in v3 bot.

**Comment by Kartik1607** [comment]
Dispatch tool has nothing to do with version of the bot. What dispatcher does is create a new luis model, which now contains intents which are nothing but the culmination of utterances from different models.
If you add say 2 luis models to a dispatcher, the dispatcher will now contain 2 intent, where each intent will contain all the utterances from that model.

You can call this dispatcher just like any other luis model. Dispatcher would return the list of intents (corresponding to LUIS model) and their confidence score. Through this you would get to know, which luis model to call to get the real intent and entities for the utterance.

**Comment by rjgmail88** [comment]
@Kartik1607 , thanks for you advice. following code from [example](https://github.com/Microsoft/botbuilder-js/blob/master/samples/dispatch-es6/app.js) shows/doing what you have shown above. 

```
const luisResults = dispatcher.get(context);

            // Extract the top intent from LUIS and use it to select which LUIS application to dispatch to
            const **topIntent** = LuisRecognizer.topIntent(luisResults);

const isMessage = context.activity.type === 'message';
            if (isMessage) {
                switch (**topIntent**) {
                    case 'l_homeautomation':
                        const homeAutoResults = await homeAutomation.recognize(context);
                        const **topHomeAutoIntent** = LuisRecognizer.topIntent(homeAutoResults);
                        await dc.begin(**topHomeAutoIntent**, homeAutoResults);
                        break;
```

but I trying to understand how can I get it working for v3 botbuilder because there are following differences.  

This isnt possible in v3
```
const faq = new QnAMaker(...)
```

adding luis recognizer isnt ready in v3

```
const weather = new LuisRecognizer({
    appId: '',
    subscriptionKey: process.env.LUIS_SUBSCRIPTION_KEY,
    serviceEndpoint: 'https://westus.api.cognitive.microsoft.com/',
    verbose: true
});
``` 
and finally 

```
const { LuisRecognizer, QnAMaker } = require('botbuilder-ai');
```

You said

> You can call this dispatcher just like any other luis model. Dispatcher would return the list of intents (corresponding to LUIS model) and their confidence score. Through this you would get to know, which luis model to call to get the real intent and entities for the utterance.

I tried using this approach on v3 bot by just adding Dispatcher app as LuisRecognizer on my bol. Just same as what I would do to existing any luis app.

```
var recognizer = new builder.LuisRecognizer(process.env.LUIS_MODEL_URL);
```

and that return me just array of intents as you mentioned. 

```

query | "turn the lights off"
-- | --
topScoringIntent |  
intent | "l_homeautomation"
score | 0.9976286
intents |  
0 |  
intent | "l_homeautomation"
score | 0.9976286
1 |  
intent | "q_GinaFAQ"
score | 0.00330403377
2 |  
intent | "l_weather"
score | 0.00276926183
3 |  
intent | "None"
score | 0.00148475915
entities | []

```
But these are not actual intents from my app. ex:- l_homeautomation isn't an intent so I cant simply call trigger dialog on it.  What I need is intents from Intent **l_homeautomation**

**Comment by Kartik1607** [comment]
@rjgmail88 you got it till half way. The **l_homeautomation** intents tells you which LUIS model to call to get the final intent (which would trigger the dialog). There will be 2 calls to Luis basically. First one will tell you which LUIS to call. And second call is the call to that Luis app. Does it make sense? Let me know if you need more help understanding it.

**Comment by rjgmail88** [comment]
@Kartik1607 , that totally make sense now. One last thing would be how to make second call with app l_homeautomatiom which will return another intent that will be used to trigger dialog. Unless I do separate http request to luis app homeautomatiom? and keep doing this for every suggested app by dispatcher. 


Currently in v3 bot it is all done by just 3 lines. 
```
var recognizer = new builder.LuisRecognizer(process.env.LUIS_MODEL_URL);
bot.recognizer(recognizer);
bot.dialog('HelpME', function (session, results) {}
```

**Comment by rjgmail88** [comment]
Also, we would lose the power of triggerAction() is we call luis app separately in 2nd call. I am not sure if I am missing something here.

**Comment by Kartik1607** [comment]
Hi,

You would have to use a custom **recognizer**, something like this, although you could make it more  generic like LuisRecongnizer.

```JS
bot.recognizer({
  recognize: function (context, done) {
  var intent = { score: 0.0 };

        if (context.message.text) {
           request.get(Dispatcher-query, (err, res, body) => {
                // Based on result from dispatcher 
                request.get(LUIS-query,(err, res, body) => {
                    // Set intent and score here 
                    intent = { score: 1.0, intent: 'Greet' };
                    // This will trigger action matching Greet
                    done(null, intent);
                })
           })
        }

    }
});
```

For reference you can look at documentation for [recognizer](https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-recognize-intent-messages?view=azure-bot-service-3.0#register-a-custom-intent-recognizer) and see how [LuisRecognizer](https://github.com/Microsoft/BotBuilder/blob/master/Node/core/src/dialogs/LuisRecognizer.ts) is implemented.

**Comment by rjgmail88** [comment]
Thanks Karthik.

**Comment by stevengum** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
