### ISSUE TITLE
Documentation which doesn't require users to install 3 external tools?

### ISSUE THREAD

**Issue by DaveVoyles** [Microsoft/BotBuilder#4887]
Is there any version of the documentation which doesn't require 3 different tool installs? 

EX: HTML, Markdown, etc

**Comment by DaveVoyles** [comment]
Sorry for the confusion, I didn't realize GitHub doesn't link to the actual page I was referring to.I think we may be talking about two different things. 

I understand that we can build bots in the Azure portal as well, but for the documentation, is there any way to view this without having to use all of these tools?

**Source:** [https://github.com/Microsoft/BotBuilder/tree/master/CSharp](https://github.com/Microsoft/BotBuilder/tree/master/CSharp)

> The code itself uses Nuget which restores all needed files when built. If you want to build the documentation, you will need to install Doxygen, GraphViz and Mscgen Here are step by step instructions:

> Download and install from the Doxygen Windows Installer.
Download and install from the GraphViz Windows Installer
Download and install from the Mscgen Windows Installer
If versions have changed you can find the latest through the core pages above, although you may need to update the Doxygen config file with the appropriate version of tools.

> If you want to do localization you should also install the Multilingual App Toolkit which allows you to edit the localization files and make use of tools like automatic translation.

**Comment by EricDahlvang** [comment]
Sorry, as far as I know those tools are required for this: https://github.com/Microsoft/BotBuilder/tree/master/CSharp/Documentation
