### ISSUE TITLE
Can we access chatbots from other apps besides the 10 channels available?

### ISSUE THREAD

**Issue by hvining** [Microsoft/BotBuilder#489]
I'm interesting in knowing if chatbots made in the with the Builder and FormFlow are available for interaction through other means such as a custom mobile app rather than just Slack, Facebook Messenger, etc.

Thanks

**Comment by XelaMon** [comment]
@hvining I believe the Direct Line API http://docs.botframework.com/sdkreference/restapi-directline/ is meant for interactions on channels outside of Slack, FB Messenger, etc.

**Comment by hvining** [comment]
Thanks @XelaMon!
Server-to-Server in Direct Line is actually what I needed!
