### ISSUE TITLE
call of cardAction not working facebook

### ISSUE THREAD

**Issue by areckkimo** [Microsoft/BotBuilder#4890]
## Bot Info
* SDK Platform: Node.js
* SDK Version: 3.14.1
* Active Channels: FB
* Deployment Environment: Azure Bot Service
## Issue Description
call of cardAction not working on facebook and not display the message on messenger
-->the channel of azure has issues that「Action.Value is not a valid url: +8860001111」

I try to use openurl method still not working on facebook and not display the message on messenger
-->the channel of azure has issues that「Action.Value is not a valid url: tel://+8860001111」

## Code Example
builder.CardAction.call(session, "+8860001111", "Call"),
builder.CardAction.openUrl(session, "tel://+8860001111", "Call")

## Reproduction Steps
1.
2.
3.

**Comment by areckkimo** [comment]
I have resolved the issue
I try to use the openUrl method with "tel:+886123456789 (I delete //)
but the call method still not support for facebook

**Comment by jwiley84** [comment]
Hi areckkimo! Were you trying to call out with the bot or recieve a call?

**Comment by jwiley84** [comment]
Closing for lack of response.
