### ISSUE TITLE
"ajaxExtended call failed" error while attempting to create a Web App Bot Service

### ISSUE THREAD

**Issue by luimode** [Microsoft/BotBuilder#4892]
## Bot Info
* SDK Platform: Node.js
* SDK Version: SDK v3
* Deployment Environment: Azure Bot Service

## Issue Description
I see an "ajaxExtended call failed" error while attempting to create an Azure Web App bot through the Azure portal.  The error seems to occur even for several variation of the parameters.

## Reproduction Steps
Create a Web App Bot in the Azure Portal
Set the parameters (values do not seem to matter)
Press "create"

## Expected Behavior
A web app bot service is created

## Actual Results
I see an "ajaxExtended call failed" error:
![image](https://user-images.githubusercontent.com/16374221/43050033-87cc72c8-8e02-11e8-9877-4aa1e6a9f24f.png)

**Comment by luimode** [comment]
error from the console:
![image](https://user-images.githubusercontent.com/16374221/43050057-02076796-8e03-11e8-8684-1985ccf0e8ec.png)

**Comment by EricDahlvang** [comment]
Thank you for reporting this.  The issue has been escalated, and we will be releasing a fix asap.

**Comment by EricDahlvang** [comment]
@luimode  Which region were you attempting to create the bot in?

**Comment by EricDahlvang** [comment]
@luimode  A fix for this has been deployed.  Creating bots with the LUIS template is functional is all regions.  Please try again, and let us know if you run into any other issues.

**Comment by luimode** [comment]
I can confirm that it works now. Thx and Good job!
