### ISSUE TITLE
Ajax Failed

### ISSUE THREAD

**Issue by apichafoko** [Microsoft/BotBuilder#4893]
Bot Info
Deployment Environment: Azure Bot Service
Issue Description
I got "ajaxExtended call failed" error when i'm trying to create Azure Web App bot (With LUIS template). 

Reproduction Steps
Start creating Web App Bot in Azure Portal
Set the parameters (in my case I'm using a new resource group)
Press "create" button
Expected Behavior
The bot should be created without any errors.

Error:
![untitled](https://user-images.githubusercontent.com/35902150/43050742-80c874fe-8de4-11e8-86b9-b703b78323b2.png)

**Comment by aamuz** [comment]
same here. I can register apps directly. Looks like error creating LUIS app ??


`8BjuiWTgucMN.js:6 [Microsoft_Azure_BotService]  14:12:33 Resource/Create/ViewModels/CreateBladeViewModel 5 CreateBladeViewModel: Failed creating LUIS app _errorData: undefined
_sourceErrorLevel: undefined
baseTypes: ["MsPortalFx.Errors.AjaxError","MsPortalFx.Errors.Error"]
code: undefined
data: {"type":"POST","requestId":"bfd35b2f-653b-4610-9ade-ad15621a4067","sessionId":"06609b39bd504ce5ad43dd4920c055ed","status":500,"statusText":"Internal Server Error","duration":1337.000000057742}
errorLevel: 2
errorThrown: Internal Server Error
extension: Microsoft_Azure_BotService
handled: undefined
innerErrors: []
jqXHR: {"readyState":4,"responseText":"{\"Error\":{\"Code\":\"ServiceError\",\"Message\":null,\"InnerHttpError\":null}}","responseJSON":{"Error":{"Code":"ServiceError","Message":null,"InnerHttpError":null}},"status":500,"statusText":"Internal Server Error"}
message: ajaxExtended call failed
name: Error
source: undefined
stack: null
textStatus: error
timestamp: 2194611.499999999
type: MsPortalFx.Errors.AjaxError`

**Comment by EricDahlvang** [comment]
Thank you for reporting this.  The issue has been escalated, and we will be releasing a fix asap.

**Comment by EricDahlvang** [comment]
@apichafoko and @aamuz Which region were you attempting to create the bot in?

**Comment by aamuz** [comment]
@EricDahlvang  I was trying to create in West Europe. I tried the qna template and that works. It's just the luis template that is not working.

**Comment by apichafoko** [comment]
@EricDahlvang the same for me. I've tested all diferent options and combinations (Changing different bot regions with different luis regions, the same regions, etc) but it always ends in the same error.

**Comment by EricDahlvang** [comment]
@aamuz @apichafoko  A fix for this has been deployed.  Creating bots with the LUIS template is functional is all regions.  Please try again, and let us know if you run into any other issues.
