### ISSUE TITLE
LUIS bot creations fails with "ajaxExtended Call Failed" error

### ISSUE THREAD

**Issue by SiddharthSinghMOD** [Microsoft/BotBuilder#4894]
## Bot Info
* SDK Platform: 
* SDK Version: 
* Active Channels: 
* Deployment Environment: 

## Issue Description
LUIS bot framework fails with error "ajaxExtended Call "

## Reproduction Steps
1.
2.
3.

**Comment by EricDahlvang** [comment]
This is a duplicate of https://github.com/Microsoft/BotBuilder/issues/4893 and https://github.com/Microsoft/BotBuilder/issues/4892
