### ISSUE TITLE
Submit action not working in Adaptive cards : Channel Skype

### ISSUE THREAD

**Issue by rachita0311** [Microsoft/BotBuilder#4896]
I have published a bot on skype. And it is able to render adaptive cards as well. Bot nothing is happening if i click on any button in my adaptive cards (Submit Action). I am using latest version of adaptive cards.

![image](https://user-images.githubusercontent.com/29450622/43131128-ea95efca-8f55-11e8-8175-bd3eecf912b7.png)

Expected Behavior:
Submit Action should be handled

Actual Behavior:
No response in skype window

**Comment by Kartik1607** [comment]
Skype does not *fully* support adaptive cards. Before serving an adaptive card, you should check the channel of user, and if that channel does not support a certain adaptive card  feature, then you should try some other method of providing the information to the user.

You can see which channels support adaptive card at the [channel inspector](https://docs.botframework.com/en-us/channel-inspector/channels/Skype?f=AdaptiveCards&e=example1) .

**Comment by jwiley84** [comment]
Closing as the above answer is correct and complete.
