### ISSUE TITLE
Microsoft.Bot.Connector / Microsoft.Bot.Connector.Utilities sources missing?

### ISSUE THREAD

**Issue by IntranetFactory** [Microsoft/BotBuilder#49]
The BotConnectorBot.js sources are available.

But when I tried to find the sources for Microsoft.Bot.Connector / Microsoft.Bot.Connector.Utilities dll I didn't find them.

Will their sources also be published or will they remain closed source?

**Comment by willportnoy** [comment]
@tomlm can you comment?  As far as I know, most of the connector library is auto-generated from the REST api.

**Comment by tomlm** [comment]
They are autogenerated. 
There is actually only 1 helper function in the utilities which implements basic auth using AppId/AppSecret.

**Comment by IntranetFactory** [comment]
It seems that they include more then just 1 helper:

![2016-04-05_0805](https://cloud.githubusercontent.com/assets/7462342/14281173/75e26bd6-fb05-11e5-8cbb-adf05afbd67d.png)

**Comment by tomlm** [comment]
All of those classes are auto generated from the swagger file.  The only custom classes are a simple helper class for implementing basic authentication and the Message.GetXBotData/SetXBotData() methods which are typed wrappers around 2 methods:

 private static TypeT GetPropertyData<TypeT>(dynamic dynamicData, string property)
        {
            if (dynamicData?[property] == null)
                return default(TypeT);
            else if (typeof(TypeT) == typeof(byte[]))
                return (TypeT)(dynamic)Convert.FromBase64String((string)dynamicData?[property]);
            else if (typeof(TypeT).IsValueType)
                return (TypeT)dynamicData?[property];
            return dynamicData?[property]?.ToObject<TypeT>();
        }

        private static dynamic SetPropertyData(dynamic dynamicData, string property, object data)
        {
            if (data == null)
                dynamicData.Remove(property);
            else if (data is byte[])
                dynamicData[property] = Convert.ToBase64String((byte[])data);
            else if (data is string)
                dynamicData[property] = (string)data;
            else if (data.GetType().IsValueType)
                dynamicData[property] = JValue.FromObject(data);
            else if (data.GetType().IsArray)
                dynamicData[property] = JArray.FromObject(data);
            else
                dynamicData[property] = JObject.FromObject(data);
            return dynamicData;
        }

We do not plan on open sourcing this because of these reasons, not because there is special secret sauce.

**Comment by TyllerDaniel** [comment]
Hi am quite new at programming however i am trying to locate the microsoft.Bot.Connector.Utilities but i am unable to find it.When i use (using Microsoft.Bot.Connector.utilities;) it says the type or name space name utilities does not exist in the name space microsoft.bot.connector.(Are you missing a refference?)
There is the image that proves i dont have the microsft.bot.connecotr.utilities library.
Kindly help
![utilities](https://cloud.githubusercontent.com/assets/20435570/17022613/a47e5e18-4f57-11e6-9262-ec3402c419ed.PNG)
