### ISSUE TITLE
[API] Channels 'Disabled'

### ISSUE THREAD

**Issue by deubaka** [Microsoft/BotBuilder#490]
Hi, what would cause channels added to BotFramework its status be set to 'Disabled'?

We suddenly experienced this (during a demo) out of nowhere since there were no changes since we've added that to BotFramework's console.

Here is a capture of the console,
<img width="794" alt="screen shot 2016-06-16 at 10 54 19" src="https://cloud.githubusercontent.com/assets/1931819/16105246/23c85ba0-33bb-11e6-9c9b-dcc4e6dc0712.png">

I tried re-authenticating to now avail. Slack authentications works.

Further tested it by sending the `/messages` API and this is the response.
<img width="579" alt="screen shot 2016-06-16 at 11 30 08" src="https://cloud.githubusercontent.com/assets/1931819/16105259/3fa80136-33bb-11e6-9455-e5ae42a96bea.png">

Edit: Upon retesting the `/messages` API, I am able to send a message, however, to bot won't still go online and status is still set to 'Disabled' even after enabling/disabling the option in the console.

To add, I've tried create a new bot on a new BotFramework account to no avail.

This is quite a problem since we were demoing to client prospects and we couldn't demo a thing.

**Comment by matt-sdg** [comment]
My slack bot is running, however it doesn't work at the moment. I've verified that the bot is working, but either messages aren't coming to the bot or the reply doesn't get to slack...

**Comment by deubaka** [comment]
@matt-sdg Mine is just disabled. Already did regenerate my Slack secret and re-authenticated, still nothing.

Tried reverting back to `SlackBot` with `botkit` this morning and its working fine, so there is a problem in either `BotConnector` or the botframework. Weird thing is, we haven't changed a thing in both the `BotConnector` initialisation and in the console. It just suddenly showed 'Disabled'.

IIRC when there is an error on your bot code, it would show a 'Error' status in the console, so I'm pretty clueless on this. I hope somebody will shed some light on this on whats happening.

**Comment by baktakt** [comment]
We're experiencing the same issue. Bot was working fine on slack yesterday, now it just shows up as offline on all teams we try adding it to. No messages seem to go through. I have talked to a developer at slack but he just said we need to make sure we're using the RTM API.

**Comment by dtzar** [comment]
This also just happend to http://aka.ms/AzureBot sometime between last night and this morning.  The Bot still shows as the slack channel is enabled AND the API is working directly. Slack shows the bot offline and no way to get it back I can see.

**Comment by vianairan** [comment]
I have the same issue. However, the direct messages to Slack bots seem to work fine now. But, the messages to group slack channels do not seem to work yet. Any work arounds?

**Comment by deubaka** [comment]
Just checked the status today, and its status is now 'Running', and receiving.

<img width="784" alt="screen shot 2016-06-20 at 09 06 56" src="https://cloud.githubusercontent.com/assets/1931819/16181016/d8130156-36c6-11e6-9fc3-19200800044a.png">

We have made no changes, since it was doing nothing. The question is, what caused the issue and if there is, what do we as devs who've invested in the platform mitigate once a similar/same issue arrises again? Anyone from the BotFramework Team that could shed some light?

Thanks!

**Comment by vianairan** [comment]
@deubaka : can you please verify if your bot works on group slack channels? For me, it only works when I send a direct private message to the bot. Not on group channels.

**Comment by deubaka** [comment]
@vianairan Confirmed that its working on a group channel. I have the `Listen to all messages` ticked off by the way in my console.

**Comment by vianairan** [comment]
@deubaka : Thanks for checking. I re-added the bot to my channel and it started working again. As you mentioned, would be great if we can get a feedback from Microsoft on the issue. So, we can access the reliability of the Bot Connector before using it.

**Comment by tomlm** [comment]
We had a bad setting get on our server which impeded the autoscale/alerting system.  It has been fixed and things should be stable now.  Sorry for the down-time.
