### ISSUE TITLE
Bot Service nos responding or too slow

### ISSUE THREAD

**Issue by gabosdk** [Microsoft/BotBuilder#4902]
**Bot Info**

SDK Platform: .NET
SDK Version: 3.14.1
Active Channels: DirectLine, WEBCHAT
Deployment Environment: Azure App Service

**Issue Description**

The bot is not responding to the received messages. No changes in bot in the last few weeks, not sure why this is happening. The same issue with another 2 bots, endpoint are up and listening. 

![5zxcsvth](https://user-images.githubusercontent.com/4503517/43231579-9f7d93fc-9032-11e8-96b4-ed2163a645d0.jpg)

**Code Example**

var bot = new builder.UniversalBot(connector, function (session) {
//send welcomecard when bot initiate
   session.send( '/faq#'+ session.gettext('beforestat'));
   session.sendTyping(); //choose a languange
   var gifcard =  new builder.AnimationCard(session)
            .media([
                    { url: _conf.gifs.wl1  }
             ])
            .buttons([
            builder.CardAction.imBack(session, session.gettext(MainOptions.start), MainOptions.start)
            //builder.CardAction.imBack(session, session.gettext(MainOptions.cancel), MainOptions.cancel)
        ]);
             
    session.send(new builder.Message(session)
        .addAttachment(gifcard));     
    session.sendTyping();

    }        
    //session.send("question1");
}).set('storage', inMemoryStorage);

The bot should reply with a message and a Card

**Actual Results**

The bot don't answer or it is too slow. 

![5zxcsvth](https://user-images.githubusercontent.com/4503517/43231599-ad494e22-9032-11e8-88fc-58af5869e1d3.jpg)

**Comment by EricDahlvang** [comment]
Hi @gabosdk 

Please provide a botid for one of the bots? (Bot Handle in the Azure Portal)  Also, please provide the corresponding MicrosoftAppId.

Which data center is the bot hosted in?

**Comment by EricDahlvang** [comment]
Closing due to no response.
