### ISSUE TITLE
[Direct Line] Is it possible to configure the expiry time of issue token?

### ISSUE THREAD

**Issue by DarkInsight85** [Microsoft/BotBuilder#4904]
As the topic, the default expires_in value is 1800, is it possible to configure this value?

**Comment by nyxsys** [comment]
Unfortunately, this is not possible to configure within bot framework. Was there anything in particular you were thinking of utilizing by extending this time period?

**Comment by DarkInsight85** [comment]
My application recently went through a PENTEST. And the results came back suggesting we to lower the expiry time from 30 minutes to 15 minutes.

**Comment by nyxsys** [comment]
So it wouldn't technically be possible without changing some stuff within the SDK. However a workaround there is probably doable. Which SDK are you using?

**Comment by nyxsys** [comment]
Closing, but please open a new issue and link to this one if you have further trouble.
