### ISSUE TITLE
[Feature Request] Not able to see sentimentAnalysis on LUIS trigger dialog 

### ISSUE THREAD

**Issue by rjgmail88** [Microsoft/BotBuilder#4905]
## Bot Info
* SDK Platform: Node.js
* SDK Version: v3
* Active Channels: MS Teams
* Deployment Environment: Azure App Service

## Issue Description

I followed this doc [https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-quickstart-intent-and-sentiment-analysis#before-you-begin](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-quickstart-intent-and-sentiment-analysis#before-you-begin)
to turn ON sentiment analysis on my existing LUIS app. 

I am using 

## Code Example
```
    bot.dialog('GetAddress', [
        function (session, args, next) {
            session.conversationData.currentIntent = args
        },
        function (session, results, next) {
            session.endDialog()
        }
    ]).triggerAction({
        matches: 'Address'
    })
```

## Reproduction Steps
Put a breakpoint at any line in the dialog triggered by triggerAction() and look at args. You can only see intent and entities data. Nothing for sentimentAnalysis which is part of original luis json output. 

## Expected Behavior
I should be able to grab sentimentAnalysis object in luis triggered dialog. 

```
"sentimentAnalysis": {
    "label": "negative",
    "score": 0.0258086324
  }
```

## Actual Results
No data about sentimentAnalysis in args object.

**Comment by corinagum** [comment]
hi @rjgmail88, 

Unfortunately the Node SDK does not currently have support for sentiment analysis via LUIS. Although there is a PR currently in the works for the C# SDK, at the moment there is not one for Node. I've added the tag Feature Request to your issue. Thank you.

**Comment by rjgmail88** [comment]
Thank you @corinagum

**Comment by stevengum** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
