### ISSUE TITLE
Unable to use VSTS application for OAuth with bot

### ISSUE THREAD

**Issue by JasonSowers** [Microsoft/BotBuilder#4906]
## Bot Info
* SDK Platform: Applies to All SDK's
* SDK Version: Applies to All Versions
* Active Channels: Applies to all channels
* Deployment Environment: Will effect all environments

## Issue Description
When trying to save the redirect URL in the VSTS app there is an error that indicates the URL is already in use.  There are also reports of VSTS applications not working with our OAuth such as [this](https://stackoverflow.com/questions/51411683/not-able-to-log-into-visual-studio-services-using-oauth).  Currently no one is able to help troubleshoot because of the issue with the redirect URL

## Code Example
Not a code issue

## Reproduction Steps
1. Follow [this guide](https://stackoverflow.com/questions/51411683/not-able-to-log-into-visual-studio-services-using-oauth) to add auth to your bot
2. Add a setting for VSTS OAuth
3. Configure your VSTS app

## Expected Behavior
For the redirect URL to be accepted, and for OAuth to work with bots

## Actual Results
Error when saving VSTS app.  Bot not working with VSTS OAuth provider.

**Comment by JasonSowers** [comment]
We are removing VSTS/VSO from the list of available OAuth providers until this is resolved.

**Comment by enufacas** [comment]
Hey @JasonSowers do you know if this is being tracked anywhere in the Bot Framework or Azure DevOps worlds? 

I added a community problem to https://developercommunity.visualstudio.com/content/problem/395510/redirecturialreadyexistsexception-httpsappvsaexvis.html but that can be a bit of black hole. VSTS Chatbots need to be a thing! Thanks in advance.

**Comment by JasonSowers** [comment]
@enufacas I am actually not on this team anymore, but at my house, we fly the W so let's see if we can get someones attention.

@jwiley84 @Zerryth @stevkan can one of you check with @Jeffders and see if this was ever resolved?  I know he had a work item in vsts for it, I'm just not sure if it was ever fixed and/or if vsts/vso was put back in the list of available OAuth providers.

**Comment by CoHealer** [comment]
Assigned to @stevkan for follow up

**Comment by CoHealer** [comment]
Assigned to @jwiley84 for follow up

**Comment by enufacas** [comment]
Cubs Win for like the second time ever. Very kind and thank you all for the hand.

**Comment by CoHealer** [comment]
@enufacas, I followed up and I'm sorry to report that work to enable the VSTS OAuth provider is not in scope for the near future. The recommendation is to use generic OAuth provider.
