### ISSUE TITLE
I have used hero card in facebook messenger channel and everything was working fine since morning but now suddenly hero card button text start showing 3 dots?

### ISSUE THREAD

**Issue by fj4870** [Microsoft/BotBuilder#4907]
## Bot Info
* SDK Platform: 
* SDK Version: 
* Active Channels: 
* Deployment Environment: 

## Reproduction Steps
1.
2.
3.

**Comment by JasonSowers** [comment]
It appears Facebook has addressed this issue already.  If you are still seeing the issue please fill out the template and provide a code example of your hero card.
