### ISSUE TITLE
Error Running the Sample c#  Microsoft.Bot.Sample.AadV2Bot

### ISSUE THREAD

**Issue by premaarya** [Microsoft/BotBuilder#4908]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.15.3
* Active Channels:  Direct Line, Emulator
* Deployment Environment:  Azure Bot Service, Azure App Service, local development with Emulator.

I am trying the run the ADD V2 sample code with the latest .NET SDK 3.15.3. Followed the V2 configuration provided [here ](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-authentication?view=azure-bot-service-3.0&WT.mc_id=email)
the setting provided here succeeds the Test Connection : 
![image](https://user-images.githubusercontent.com/20116758/43246185-15bdf68e-906e-11e8-9f85-5a8cdd46c436.png)

When doing a test in WebChat getting Post error -
{
  "error": {
    "code": "BadArgument",
    "message": "Missing token or secret"
  }
}

And emulator error : 
![image](https://user-images.githubusercontent.com/20116758/43246284-6648601c-906e-11e8-9f75-126430bdedba.png)

Is this a known issue? How to  resolve?

**Comment by premaarya** [comment]
My ngrok settings are correct 
After deployment ..i get the auth card when I sign in getting the magic code and the control never returns back to the bot. 
I get following error on click of SignIn button 
![image](https://user-images.githubusercontent.com/20116758/43375625-72662926-9373-11e8-9924-a081d5b7e25f.png)

**Comment by nyxsys** [comment]
Can you provide some more information on how you've got your AADv2 OAuth set up? Have you included all the listed permissions as well as "scope"?

**Comment by premaarya** [comment]
I Tested the connection i get the token successfully. My Scope string is: openid profile Calendars.Read Calendars.Read.Shared Calendars.ReadWrite Contacts.Read Contacts.ReadWrite Files.Read Files.Read.All Files.ReadWrite Files.ReadWrite.All Mail.Read Mail.ReadWrite Mail.ReadWrite Mail.Send User.Read User.Read.All User.ReadWrite User.ReadWrite.All User.ReadBasic.All
with and without offline_access 
then reduced the permissions list to just openid... setting test succeeds but not able to get the flow back from auth flow. Got another thread describing same issue i am facing  [#71](https://github.com/Microsoft/BotFramework-DirectLineJS/issues/71)  AND #4745

**Comment by JasonSowers** [comment]
Have you made any changes to the sample code?

**Comment by premaarya** [comment]
@nyxsys in my bot application the faq before the authdialog working good. I didn't try the sample without Auth, i can try will let you know.
@JasonSowers  I think I updated the Nuget packages it was not building as I downloaded, also unloaded all other projects.

**Comment by JasonSowers** [comment]
@premaarya  can you please try running something like the echobot sample in that solution and see if you get the same result?

**Comment by nyxsys** [comment]
If you are connecting to azure directly from emulator, please make sure you've set up your AppId and Secret correctly, as the error code you are receiving is generally related to that.

**Comment by nyxsys** [comment]
Are you still having this problem? We're going to close this issue soon.

**Comment by nyxsys** [comment]
Closing, please open a new issue if you have this problem again.
