### ISSUE TITLE
File Uploading From User Stopped Working on Slack

### ISSUE THREAD

**Issue by byu-apttus-com** [Microsoft/BotBuilder#4909]
## Bot Info
* SDK Platform: Node.js
* SDK Version: Bot Service (Bot Channels Registration)
* Active Channels: Slack
* Deployment Environment: Azure Bot Service

## Issue Description
Our production version file uploading suddenly stopped accepting file on Slack.  This is a critical issue on our production server used by live users.  

It was working just file, but it suddenly does not accept files from users anymore.  The "attachments" parameter is now just an empty array.  We can tell it is a bug because if no file is uploaded, the "attachments" variable would be null, when we upload a file from Slack, attachments will be an empty array.

We are using Node.js

## Code Example
    // This is part of our code that check for attachment, it would print:
    // ! Hash Attachments: []
    // ! No File
    // This show us that attachments is not null but is an empty array
    static hasAttachment(req) {
        console.error("!! Checking for attachments");
        if (!util_1.isNullOrUndefined(req.body) && !util_1.isNullOrUndefined(req.body.attachments)) {
            console.error("!! Has Attachments: "+JSON.stringify(req.body));
            if (req.body.attachments.length > 0) {
                console.error("! Has File");
                return true;
            }
            else {
                console.error("! No File");
                return false;
            }
        }
        else{
            console.error("! No File");
            return false;
        }
    }
## Reproduction Steps
1.  Log on Slack Bot
2.  upload a File
3.  No File is uploaded

## Expected Behavior
The uploaded file information to be in the "attachments" field

## Actual Results
No file upload information in the attachments field.

**Comment by stevkan** [comment]
Hi @byu-apttus-com, I'm looking into this issue and will reach back to you shortly with questions.

**Comment by byu-apttus-com** [comment]
Sounds good, thank you.

APTTUS | Bill (Yongke Yu)

**Comment by byu-apttus-com** [comment]
Hi Stevkan

I also opened a premier support ticket from Microsoft, here is the ticket number:  118072718673522.

**Comment by stevkan** [comment]
It looks like a fix is being applied via your support ticket. I will monitor this issue for the time being and close once I see it is completed.

**Comment by stevkan** [comment]
Closing as resolved.
