### ISSUE TITLE
Chat bot Azure AD single sign on

### ISSUE THREAD

**Issue by ravisha22** [Microsoft/BotBuilder#4911]
I'm working on a Azure Bot framework chat bot based on web chat client. My users would be logged in to their corporate laptops (Using on-premises AD credentials synced with AAD) and using Office 365 services using Azure AD credentials.

I don't want them to be prompted for credentials if they are already signed in to any of the Office 365 services. Is this possible to achieve?

**Comment by jwiley84** [comment]
Apologies for the delay in answering. I've been told this isn't possible, but I'm investigating it.

**Comment by stevengum** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
