### ISSUE TITLE
Log messages send out from Bot Connector to Channels

### ISSUE THREAD

**Issue by ankitbko** [Microsoft/BotBuilder#492]
If I understand correctly, bot connector modifies the `Message` to adopt to the particular channel's specification. Is it possible to have a feature in the portal to see last 'N' JSON messages sent from the connector to specific channels in its final form?
The problem I faced was that I was trying to get the images in button in Facebook channel but it was not working. This created a confusion that whether the feature is yet not supported or if I was doing something wrong. The logs from connector would help us in discerning the actual problem quickly.
Is something like this possible?

**Comment by v-thgratMSGit** [comment]
Closing this issue due to age. @ankitbko - please open a new issue if this issue is not fixed and needs further discussion. Thanks!
