### ISSUE TITLE
ngrok GET failed 405 Method not allowed

### ISSUE THREAD

**Issue by WhiteMaple13** [Microsoft/BotBuilder#4925]
## Bot Info
* SDK Platform: Node.js
* SDK Version: Botbuilder 3.15.0
* Active Channels: Emulator, Skype, WebChat
* Deployment Environment: Emulator, Skype, WebChat

## Issue Description
When trying to test my bot on webchat and Skype using ngrok, i get the following error message in the console of the bot and no reply: 

```
Error: GET to 'https://state.botframework.com/v3/botstate/skype/conversations/****/users/****' failed: [405] Method Not Allowed
    at Request._callback (C:\Users\wiet020\Documents\botTest\node_modules\botbuilder\lib\bots\ChatConnector.js:647:46)
    at Request.self.callback (C:\Users\wiet020\Documents\botTest\node_modules\request\request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\wiet020\Documents\botTest\node_modules\request\request.js:1157:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\Users\wiet020\Documents\botTest\node_modules\request\request.js:1079:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
```

I already triple checked AppId, AppPassword, ngrok-URL and the "api/messages" added to it etc. and the bot does work when tested locally on the emulator.

## Code Example
```
var restify = require('restify');
var builder = require('botbuilder');

// Setup Restify Server
var server = restify.createServer();
server.listen(process.env.port || process.env.PORT || 3978, function () {
console.log('%s listening to %s', server.name, server.url);
});

// Create chat connector for communicating with the Bot Framework Service
var connector = new builder.ChatConnector({
appId: _myAppId_,
appPassword: _myAppPassword_
});

// Listen for messages from users
server.post('/api/messages', connector.listen());

// Receive messages from the user and respond by echoing each message back (prefixed with 'You said:')
var bot = new builder.UniversalBot(connector, function (session) {
session.send("You said: %s", session.message.text);
});
```

## Reproduction Steps
1. Run `ngrok http 3978 -host-header localhost:3978`
2. Paste the given https-address to the Bot Portal and add "/api/messages" to it.
3. Run `node app.js`
4. Send a message to the bot using skype / the testing Webchat of the Bot Portal

## Expected Behavior
The message gets send back prefixed with "You said:" 

## Actual Results
The above mentioned error in the console where the bot was started.

**Comment by EricDahlvang** [comment]
Hi @WhiteMaple13 

Please review this announcement: https://blog.botframework.com/2017/12/19/bot-state-service-will-soon-retired-march-31st-2018/

For testing purposes, it is trivial to add MemoryBotStorage:

```js
var inMemoryStorage = new builder.MemoryBotStorage();
var bot = new builder.UniversalBot(connector, function (session) {
     session.send("You said: %s", session.message.text);
}).set('storage', inMemoryStorage); // Register in memory storage
```

(The emulator has an internal state service, which is why it is still working.)

**Comment by WhiteMaple13** [comment]
Thank you very much, that solved it.
