### ISSUE TITLE
Cannot use Visual Studio Online as an Auth provider

### ISSUE THREAD

**Issue by JimiSmith** [Microsoft/BotBuilder#4927]
## Bot Info

* SDK Platform: .NET
* SDK Version: .NET 3.15.2.2
* Active Channels: affects all channels
* Deployment Environment: bot channels registration

## Issue Description
Adding authentication via Visual Studio Online seems to be impossible. When registering a Visual Studio Online app the redirect URL is required to be globally unique. Given that the bot auth service seems to use a static url that is the same for everyone, it isn't possible to create a Visual Studio Online app.

## Reproduction Steps
1. Click 'Add Setting' under the 'OAuth Connection Settings' section in the Azure Portal
2. Select Visual Studio Online from dropdown
3. Observe that a client id and secret are needed
4. Go to https://app.vsaex.visualstudio.com/app/register and attempt to register a new app
5. Enter https://token.botframework.com/.auth/web/redirect as the redirect url

## Actual Results
Get error that says 'RedirectUriAlreadyExistsException'
![image](https://user-images.githubusercontent.com/914634/43572886-d1f3db5c-9640-11e8-9d18-f7139c5b6ad8.png)

## Expected Behavior
I should be able to get a unique redirect url per bot. Or the Visual Studio Online team should drop the unique redirect url requirement (but I don't know where to file that request)

**Comment by JasonSowers** [comment]
@JimiSmith thanks for reporting, we are aware of this issue and tracking this in #4906. If you could just copy and paste your post into there for tracking purposes we would appreciate it.  Thanks
