### ISSUE TITLE
Handling commands tutorial crashes node process

### ISSUE THREAD

**Issue by glenchao** [Microsoft/BotBuilder#493]
Follow the **Handling Commands** section of this tutorial http://docs.botframework.com/builder/node/guides/core-concepts/ 

**Expected result:** 
hello
Hi! What is your name?
John
Hello John!
set name
What would you like to change it to?
John Smith
hello
Hello John Smith!
quit

**Actual Result:**
hello
Hi! What is your name?
John
Hello John!
set name
What would you like to change it to?
John Smith
--crash--

**Comment by brene** [comment]
This seems to be the same bug that I wrote thoroughly about [here](https://github.com/Microsoft/BotBuilder/issues/532). We should link these bugs together.

**Comment by v-thgratMSGit** [comment]
Closing this issue which looks like it was solved with V3 via #532 . Thanks!

**Comment by Stevenic** [comment]
great
