### ISSUE TITLE
"AadV2Bot" Sample is failing. Authentication problem.

### ISSUE THREAD

**Issue by SuperJMN** [Microsoft/BotBuilder#4932]
## Bot Info
* SDK Platform: .NET
* SDK Version: Current code in GitHub
* Active Channels: N/A
* Deployment Environment: Local deployment (Emulator V4 Preview)

## Issue Description
Please, check the video to see the wrong behavior:
https://youtu.be/38PTpwyO1zE

## Code Example
Run the sample "AadV2Bot" with no modifications (other than setting the appropriate bot settings)

## Reproduction Steps
(Watch the video)

## Expected Behavior
The window shouldn't auto close silently.

## Actual Results
The window closes without actually doing anything.

NOTE: There are times when the window shows up correctly, but after login it's closed (expected) and nothing happens in the bot. In this case, after the windows is closed (login successful), the bot should resume the operation that required the authentication. This doesn't happen.

**Comment by EricDahlvang** [comment]
Hi @SuperJMN 

The issue you've described here appears to be an Emulator bug.  Please post this on the BotFramework-Emulator repository: https://github.com/Microsoft/BotFramework-Emulator/issues/new
