### ISSUE TITLE
Whatsapp Support 

### ISSUE THREAD

**Issue by MickaelPuygcerver** [Microsoft/BotBuilder#4935]
Hi, i don't know if this is the correct place to asked this question.
So, day one of this month, facebook has noticed API to whatsapp.
I know thats is only begin of process, only some companies has access to API.
But BotFramework alredy working in a support to whatsapp?
It's very important to my company. 

Sorry if this is not the ideal place to ask it, i don't know where ask.
Thanks

**Comment by EricDahlvang** [comment]
This issue is tracking WhatsApp interest: https://github.com/Microsoft/BotBuilder/issues/2920  Please ask your question on that issue.
