### ISSUE TITLE
Go lang support

### ISSUE THREAD

**Issue by Tjird** [Microsoft/BotBuilder#4936]
A bump to an earlier feature request, are there any plans yet for Go Lang support?
The earlier request is 2 years ago so yeah..
https://github.com/Microsoft/BotBuilder/issues/1214

**Comment by stevengum** [comment]
@Tjird thanks for opening this issue and voicing your support for Go support. I've reopened the original issue and am going to close this one to keep the repo cleaner, please make sure to add a reaction to the original issue to  lend your voice to it.
