### ISSUE TITLE
WaitForToken of GetTokenDialog is invoked again after the dialog completion

### ISSUE THREAD

**Issue by skyovi** [Microsoft/BotBuilder#4938]
## Bot Info
SDK Platform: .NET Framework 4.6
SDK Version: 3.15.2.2
Active Channels: Direct Line, Teams 
Deployment Environment: Azure App Service

## Issue Description
Users are intermittently getting an error message after GetTokenDialog .  As per our telemetry log, we have observed (getting System.ArgumentNullException) that the WaitForToken of GetTokenDialog is invoked with null text or value activity even after the dialog completion.

Attached the exception details

## Reproduction Steps

1.	User types message in the bot channel
2.	Message controller passes the message to RootDispacthDialog (inherits from DispatchDialog)
3.	RootDispatchDialog calls GetTokenDialog
4.	RootDispatchDialog calls PartnerSelectionDialog (shows drop down selection card) when it receives token from GetTokenDialog 
5.	RootDispatchDialog calls RootLuisDialog after it receives response from the PartnerSelectionDialog.

User are getting the error message after the step 5

Calling RootDispatchDialog from the message control when the message, token response and team verification events are received.  

We are using our own version of GetTokenDialog class (passing true to asSignInCard argument of CreateOAuthReplyAsync function calling). It is working fine and returns the user token successfully.  
Changes done in our version of GetTokenDialog

**Changes done in our version of GetTokenDialog**

- Sending true value to asSignInCard argument of  CreateOAuthReplyAsync function call SendOAuthCardAsync method
`var reply = await activity.CreateOAuthReplyAsync(this.connectionName, signInMessage, SignInButtonLabel, true);
`

- Verification code comes with trailing spaces or newline character sometime when Bot users copy paste the magic code into bot channel. To fix this, We just added regex match statement to extract only the number part from the activity text or value in WaitForToken method. 

`verificationCode = Regex.Match(verificationCode, @"\d+").Value;
 tokenResponse = await context.GetUserTokenAsync(this.connectionName, verificationCode);
`
 getting System.ArgumentNullException at the Regex.Match statement in the above code. 

**Bot State**
We are using the Cosmos DB for storing the bot state.
`
Var documentDbBotDataStore = DocumentDbBotDataStore(uri, docDbKey);
builder.Register(botData => documentDbBotDataStore)
                                .Keyed<IBotDataStore<BotData>>(AzureModule.Key_DataStore)
                                .AsSelf()
                                .SingleInstance();
            builder.Register(c => new CachingBotDataStore(documentDbBotDataStore, CachingBotDataStoreConsistencyPolicy.LastWriteWins))
                .As<IBotDataStore<BotData>>()
                .AsSelf()
                .InstancePerLifetimeScope();
`

[ExceptionDetails.txt](https://github.com/Microsoft/BotBuilder/files/2260435/ExceptionDetails.txt)

**Comment by JasonSowers** [comment]
@skyovi There was a bug prior to 3.15.2.3 that involved the cache for the state service.  The bug was causing errors in the use of the dialog stack by vacating entries and making things execute "out of order".  The bug was addressed in this [pull request](https://github.com/Microsoft/BotBuilder/pull/4810).  The symptoms you are experiencing seem to be this bug.  Can you please try to upgrade to 3.15.2.3+ and see if the problem persists?

**Comment by skyovi** [comment]
@JasonSowers  Thanks for your prompt response.
we will update to 3.15.2.3+ and test it

**Comment by skyovi** [comment]
@JasonSowers  It seems to be working fine after upgrading the library to 3.15.2.3.

But If we upgrade to 3.15.3 version, we are experiencing the below issue:

The information that is stored in BotData (loaded using scope.Resolve<IBotDataStore<BotData>>()), cannot be retrieved using context.PrivateConversationData (IBotDataBag)

- From UI portal, We are sending some information to the Bot service using the custom events 
- In MessageController, storing the information the user private conversation using the below code.
`
using (var scope = DialogModule.BeginLifetimeScope(Conversation.Container, activity))
{
 var botDataStore = scope.Resolve<IBotDataStore<BotData>>();
                var userData = await botDataStore.LoadAsync(key, BotStoreType.BotPrivateConversationData, CancellationToken.None);
userData.SetProperty(key,val);
}
`
- In the subsequent dialogs, we are not able to retrieve the information using IDataBag ( IDialogContext.PrivateConversationData) and getting null value.

**Comment by JasonSowers** [comment]
What are you using for your data store? Default, azure tables, cosmos, in memory?

**Comment by skyovi** [comment]
Thanks @JasonSowers .  after calling the SaveAsync and FlushAsync methods, we are able get the data in the subsequent dialogs. 

with the <3.15.3 version, the bot store is working fine even if we don't call Save and Flush methods.

we are using CosmosDB for data store. 
```CS
Var documentDbBotDataStore = DocumentDbBotDataStore(uri, docDbKey); 
builder.Register(botData => documentDbBotDataStore) .Keyed<IBotDataStore<BotData>>(AzureModule.Key_DataStore) .AsSelf() .SingleInstance(); 
builder.Register(c => new CachingBotDataStore(documentDbBotDataStore, CachingBotDataStoreConsistencyPolicy.LastWriteWins)) 
                   .As<IBotDataStore<BotData>>() 
                  .AsSelf()
                  .InstancePerLifetimeScope();
```

**Comment by JasonSowers** [comment]
That would be news to me if that was working, interesting.  So are you all good now?

**Comment by JasonSowers** [comment]
Please open a new issue if you require further assistance.
