### ISSUE TITLE
Using Constructor Injection with the MessagesController

### ISSUE THREAD

**Issue by DavePilks** [Microsoft/BotBuilder#494]
I have a service that I want to inject into my `MessagesController` but I can't as it says that it requires a parameterless constructor. I know, from reading earlier that you already use AutoFac which is what I want to use. 

But what is the best way to inject this dependency into the controller? @willportnoy has mentioned elsewhere that it is best to avoid using the Service Locator pattern so I am at a bit of a loss here.

How do you advise I move forward?

**Comment by chrimc62** [comment]
Add @willportnoy  to comment.

**Comment by willportnoy** [comment]
What container are you using to resolve your MessagesController?  Can you specify the constructor you want to use?

http://docs.autofac.org/en/latest/register/registration.html#specifying-a-constructor

**Comment by DavePilks** [comment]
I managed to get this working by setting the `HttpConfiguration` property on the `HttpConfiguration` in the `WebApiConfig`
