### ISSUE TITLE
How to get Authentication token for a User with Bot over Skype for Business channel

### ISSUE THREAD

**Issue by satyansh-sagar** [Microsoft/BotBuilder#4940]
I have developed a bot using bot service and deployed it on SFB channel. I want to make graph API call on behalf of the user. in activity object, I am getting the username from the SFB, is there any way to get the bearer token without using the OAuth flow , as the user is already signed in into SFB.
@msft-shahins @brandonh-msft @matvelloso @msftgits

**Comment by JasonSowers** [comment]
Unfortunately, the auth feature in bot framework is not built to natively support this scenario.  That is not to say that it would be impossible, but it would take some sort of custom implementation of the auth feature on your end.

**Comment by satyansh-sagar** [comment]
How can I implement this feature? @JasonSowers

**Comment by JasonSowers** [comment]
Sorry, I do not have a sample because this is not a scenario we support with the current state of our auth features.

**Comment by satyansh-sagar** [comment]
That's what my team is looking for. Their concern is if a user is already logged in SFB then why there is the need of token.

**Comment by JasonSowers** [comment]
I apologize but this is not currently a feature of botbuilder.

**Comment by JasonSowers** [comment]
To my knowledge, it is not currently on our roadmap, but let me confirm that and get back to you.

**Comment by JasonSowers** [comment]
This is currently on our radar for MS Teams, but no timeline to report.  We are exploring this, but the feature would be available on MS Teams before anything else.  Skype for Business is not something we are exploring at his time.
