### ISSUE TITLE
Send Proactive Message using HeroCard.

### ISSUE THREAD

**Issue by jay58** [Microsoft/BotBuilder#4941]
## SDK
* SDK Platform: Node.js

## Issue Description
I am able to send a proactive message without the session.
But the problem is Building a HeroCardor CardImage I need Session object. And because of that, I cannot send HeroCard proactively. So I tried keeping the session null but it didn't work.

I referred following issue: [4057](https://github.com/Microsoft/BotBuilder/issues/4057)

## Tried Code (but not working)
var msg = new builder.Message()
            .address(address)
            .textFormat(builder.TextFormat.xml)
            .attachmentLayout(builder.AttachmentLayout.carousel)
            .attachments([
                new builder.HeroCard()
                    .text("1")
                    .images([builder.CardImage.create(null, 'http://xyz.com/images/green.png')]),
                new builder.HeroCard()
                    .title("2")
                    .images([builder.CardImage.create(null, 'http://xyz.com/images/red.png')]),
                new builder.HeroCard()
                    .title("3")
                    .images([builder.CardImage.create(null, 'http://xyz.com/images/blue.png')]),
            ]);
bot.send(msg)

**Comment by stevkan** [comment]
Can you tell me what version of BotBuilder you are running? Also, are you calling this as part of a normal dialog flow or at some other point?

**Comment by amitbend** [comment]
@jay58 I think you cannot send a carousel proactively to Facebook if this is the case. try to look into their docs

**Comment by Kartik1607** [comment]
Hmm. I don't know why session is getting used here for node SDK. 
Where as in .Net, all we need to do is give url like `new CardImage('http:_URL_HERE')`

**Comment by jay58** [comment]
@amitbend I am trying to send it to Skype, not Facebook right now.
I already looked into the doc. But same thing I can achieve through REST

**Comment by stevkan** [comment]
@jay58, You can create a new instance of session and pass that into the new message you are creating, like so:

```js
var sessionAddress;

var bot = new builder.UniversalBot(connector, function (session) {
    session.send('Welcome');
    session.beginDialog('/main');
    sessionAddress = session.message.address;
})
    .set('storage', new builder.MemoryBotStorage()); 

var msg = new builder.Message(sessionAddress)
    .address(sessionAddress)
    .textFormat(builder.TextFormat.xml)
    .attachmentLayout(builder.AttachmentLayout.carousel)
    .attachments([
        new builder.HeroCard()
            .text("1")
            .images([builder.CardImage.create(null, 'http://www.nurturedinnorfolk.co.uk/image/cache/data/Mizuna%20Green-600x400w.jpg')]),
        new builder.HeroCard()
            .title("2")
            .images([builder.CardImage.create(null, 'https://cdn.zmescience.com/wp-content/uploads/2015/02/blue-600x400.jpg')]),
        new builder.HeroCard()
            .title("3")
            .images([builder.CardImage.create(null, 'http://www.journaldugeek.com/files/2014/07/PowerShot-SX400-IS-RED-FSL-600x400.jpg')]),
    ]);

bot.dialog('/main', [
    function (session, args) {
        session.send("Glad you could join.");
        session.send(msg);
    }
]);
```

Hope of help!
Steve.

**Comment by johnataylor** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
