### ISSUE TITLE
Issue Stating HTTP Status code Forbidden  while using Direct Line

### ISSUE THREAD

**Issue by Archit454** [Microsoft/BotBuilder#4942]
## Bot Info
* SDK Platform: 
* SDK Version: 
* Active Channels: 
* Deployment Environment: 

## Reproduction Steps
1.
2.
3.

**Comment by Archit454** [comment]
Hi. I am facing an issue like **ERROR: that connector: receive - invalid token. Check bot's app ID & Password** in the command prompt while running node js code. But after sometimes the issue is getting resolved automatically and the bot is working fine. I have connected with Direct Line Channel and when I am checking there it is stating that **There was an error sending this message to your bot: HTTP status code Forbidden.** This is occurring randomly and after a few hours, it is getting resolved automatically. I am giving correct AppId and Password within the node js code. I am unable to understand the issue of why I am facing frequently for a few hours. Can anyone help me with understanding in this

**Comment by EricDahlvang** [comment]
Please share the following information, so we can investigate:
-SDK Version
-Bot Handle
-MicrosoftAppId
-ConversationId of failed messages if possible
-UTC timestamp when the issue occurred
-Bot hosting location (Azure Data Center, on prem)

**Comment by EricDahlvang** [comment]
Closing due to no response.
