### ISSUE TITLE
How to transfer data of bot framework state service to own state storage

### ISSUE THREAD

**Issue by areckkimo** [Microsoft/BotBuilder#4943]
## Bot Info
* SDK Platform: Node.js
* SDK Version: 3.13.1
* Active Channels: FB
* Deployment Environment: Azure Bot Service

## Issue Description
About  https://blog.botframework.com/2018/04/02/reminder-the-bot-framework-state-service-has-been-retired-what-you-need-to-know/
I have to change the old way to own state storage
But my bot save some user data on the bot framework state service
How to transfer data of bot framework state service to own state storage

**Comment by EricDahlvang** [comment]
`exportBotStateData`  [link](https://github.com/Microsoft/BotBuilder/blob/master/Node/core/lib/bots/ChatConnector.js#L307) was added with this PR: https://github.com/Microsoft/BotBuilder/pull/4465 

After all data is exported, it can then be re-imported into your own state data store.  The process of importing is left to the developer.

**Comment by EricDahlvang** [comment]
Closing due to no response.

**Comment by areckkimo** [comment]
How to get data?
Can you give me an example code?
thanks
