### ISSUE TITLE
Internal Server Error 500

### ISSUE THREAD

**Issue by amjad-elkanio** [Microsoft/BotBuilder#4944]
## Bot Info
* SDK Platform: .NET 4.7 
* SDK Version:  3.15 
* Active Channels:  Web App bot 
* Deployment Environment:  Azure Bot Service, Azure App Service

## Issue Description
Suddenly bot showing Internal server error 500. Was working  till 11:30AM IST. suddenly it stopped working and throwing errors.  Our development server showing error which is located in Central US. One of our chatbot deployed in East Asia has not encountered any issue.

## Expected Behavior
The published version which were working yesterday currently stalls.

## Actual Results
POST Response code 500 (Internal Server Error)

**Comment by sachin-code-21** [comment]
I am also experiencing the same issue with the bots i have connected to LUIS with. This is urgent!!

**Comment by EricDahlvang** [comment]
Please share the following information, so we can investigate:
-Bot Handle
-MicrosoftAppId
-Channel (WebChat, DirectLine, Messenger, etc.)
-ConversationId of failed messages if possible
-UTC timestamp when the issue occurred

**Comment by EricDahlvang** [comment]
Closing due to no response.
