### ISSUE TITLE
Requesting thread control from Page Inbox on FB Messenger not working

### ISSUE THREAD

**Issue by 1110770MiguelSilva** [Microsoft/BotBuilder#4946]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.15.3
* Active Channels: FB Messenger
* Deployment Environment: Azure Bot Service

## Issue Description

I have developed a bot and set it as the Primary Receiver on my Page, and set the Inbox as the Secondary Receiver. Everything is working okay except that when I manually send a conversation from "Done" to the Inbox, after a user sends a new message it automatically resends the conversation to the Done folder and for the bot to answer.

This does not happen if I use the "pass_thread_control" graph API request, on these cases the handover works as expected.

I found this documentation: https://developers.facebook.com/docs/messenger-platform/handover-protocol/request-thread-control#page_inbox

And it says that the Primary Receiver has to honor the request thread control event. My question is, how do I ensure this?

**Comment by jwiley84** [comment]
Hi 1110770MiguelSilva! I'm investigating this.

**Comment by amitbend** [comment]
@jwiley84 Any news? I'm using the Node SDK but it seems to be an issue with the connector

**Comment by 1110770MiguelSilva** [comment]
Yes, from what I could gather, although I'm not sure, it seems that when the message gets to the connector it already doesn't have some properties that would be required to handle this issue, like the standby event.
https://developers.facebook.com/docs/messenger-platform/reference/webhook-events/standby/

But further than that I still haven't figured out how to handle the issue, any luck @jwiley84 ?

**Comment by jwiley84** [comment]
@1110770MiguelSilva, my apologies for the delay in responding. I was unable to find a solution for this, as Facebook Handover is not currently supported by the Bot Framework, and is not on our roadmap, however, it is something we might be able to look into in the future if there’s enough demand.

**Comment by 1110770MiguelSilva** [comment]
Hello.

I've just seen that in the latest update to the framework a new ActivityType was added, the Handoff.
https://github.com/Microsoft/BotBuilder/pull/4947

Could this be used to solve my issue? I've tried to test it, see if the handover from facebook would use that activity type, but from what I've seen it doesn't.

Thank you.
