### ISSUE TITLE
[ChatConnector.startConversation] Call to Skype for Business serviceUrl returns keys in PascalCase

### ISSUE THREAD

**Issue by ramonmata** [Microsoft/BotBuilder#4948]
## Bot Info
* SDK Platform: Node.js
* SDK Version: 3.13.1
* Active Channels: Skype for Business, Web Chat
* Deployment Environment: Azure Bot Service

## Issue Description

I am trying to start a converstion directly with botbuilder.ChatConnector and skype for business channel.
Once I execute connector.startConversation, ChartConnector.js sends the request to Skype service URL and this is returned:

```
{ ActivityId: null,
  ServiceUrl: 'https://webpoolbl20r04.infra.lync.com/platformservice/tgt-acc62d52086051e09e91da76d64b2160/botframework',
  Id: 'NDE4YzY4ZDgjc2lwOnN1cnZleS5ib3RAc3RrdGVzdDIub25taWNyb3NvZnQuY29t' }
```

As we can see in JSON data, first char for key **Id** is a capitalized, thus failing the formation of the new address that should be returned by the call to `connector.startConversation`.

Also the key **ServiceUrl** comes with the first char capitalized.

I think it is more related to the Skype for Business team, but I was unable to find their GitHub repo. So maybe you can tell them.

## Code Example
File: node_modules/botbuilder/lib/bots/ChatConnector.js
Ln: 235, 237, 238, 239
```
            this.authenticatedRequest(options, function (err, response, body) {
                var adr;
                if (!err) {
                    try {
                        var obj = typeof body === 'string' ? JSON.parse(body) : body;
                        if (obj && obj.hasOwnProperty('id')) {
                            adr = utils.clone(address);
                            adr.conversation = { id: obj['id'] };
                            if (obj['serviceUrl']) {
                                adr.serviceUrl = obj['serviceUrl'];
                            }
                            if (adr.id) {
                                delete adr.id;
                            }
                        }
```

## Reproduction Steps
1. Use connector to start a conversation
2. Change ChatConnector.js to print into console the body argument from authenticatedRequest (ln 230)
3. Run

## Expected Behavior
connector.startConversation returns a Conversation ID

## Actual Results
```
Error: Failed to start conversation: no conversation ID returned.
    at N:\ms-bot\node_modules\botbuilder\lib\bots\ChatConnector.js:246:35
    at Request._callback (N:\ms-bot\node_modules\botbuilder\lib\bots\ChatConnector.js:643:37)
    at Request.self.callback (N:\ms-bot\node_modules\request\request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (N:\ms-bot\node_modules\request\request.js:1157:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (N:\ms-bot\node_modules\request\request.js:1079:12)
    at Object.onceWrapper (events.js:313:30)
```

**Comment by EricDahlvang** [comment]
Hi @ramonmata 

Thank you for reporting this.  We have an old PR with a fix: https://github.com/Microsoft/BotBuilder/pull/3492  I'm going to investigate why this has not been merged.  I'll get back to you soon.

**Comment by EricDahlvang** [comment]
Status: we have a bug filed for fixing this on the backend service.  No eta right now.

**Comment by johnataylor** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
