### ISSUE TITLE
Last choice options in choice prompt is not in the same style in Skype for business channel

### ISSUE THREAD

**Issue by Basavarajsk1992** [Microsoft/BotBuilder#4949]
## Bot Info
* SDK Platform: Node.js 
* SDK Version: 3
* Active Channels: Skype for business
* Deployment Environment: Azure web Bot Service,
## Issue Description
prompt choice: last choice is not in the same style in Skype for business channel

## Code Example
builder.Prompts.choice(session, 'Sure, please enter the appropriate option and reference number ', ["Order #","Requisition #","PO #","Delivery #"], {listStyle: builder.ListStyle.list},{
                        maxRetries: 3,
                        retryPrompt: 'Please provide the valid option, please try again'
                    });   

## Reproduction Steps
1.
2.
3.

## Expected Behavior
Sure, please enter the appropriate option and reference number

1. Order #
2. Requisition #
3. PO #
4. Delivery #

## Actual Results
Sure, please enter the appropriate option and reference number

**1.** Order #
2. Requisition #
3. PO #
_4._ Delivery #

**Comment by johnataylor** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
