### ISSUE TITLE
Retrieving utterance intent from 'args' in second step of dialog waterfall

### ISSUE THREAD

**Issue by justinpchang** [Microsoft/BotBuilder#4950]
## Bot Info
* SDK Platform: Node.js
* SDK Version: Latest
* Active Channels: Slack, MS Teams, WebChat
* Deployment Environment: Emulator

## Issue Description

In my application, I am programmatically building dialogs from a json config. I want to include the feature to have the option to prompt before completing a dialog body. To accomplish this, I am trying to use a waterfall. I plan on having a first waterfall step that does a confirmation prompt inserted into the dialog if needed.

However, the main step of the waterfall (the post-confirmation step), relies on the args parameter to get the utterance intent. For the first step, I can retrieve the args object by using the function signature of ```(session, args) => {},``` but I can't find any way to pass this object to the next step. Additionally, the second function seems to have the signature of ```(session, results, next?)=>{},``` but none of these parameters include intent that I can use.

Is there a feature to manually add data to the results object or is there a better way to accomplish what I'm trying to do?

## Code Example

This is the function that gets called on each dialog config object in my json file.
```JavaScript
// Creates each dialog
const composeDialog = (bot, config, _dialog, builder) => {
  // Return and create dialog
  return bot.dialog(_dialog.name, [
    (session, args) => {
      // PROMPT HERE???
      dlog(JSON.stringify(args)); // << args.intent exists
    },
    async (session, results) => {
      session.sendTyping();
      // Copy of dialog that gets mutated
      let dialog = _.cloneDeep(_dialog);
      // State check and state error message
      if(utils.invalidState(session, dialog)) return;
      // Set relevant entities to session data
      attributeChecker.checkEntities(session, args, builder, dialog); // << want to pass args with intent here
      // Sift the dialog config using data object for session data replacement within dialog
      let sift = (query) => dataProcessor.siftString(query, dialog.data, session);
      await deepSifter.deepSiftPromiseHandler(dialog, sift);
      // Check requests object for POST or GET requests
      await utils.serialExecute(attributeChecker.checkRequests(session, dialog));
      // Create and send message based on contentType attribute
      await typeHandler.decide(session, dialog);
      // Post-dialog state handling
      utils.setConversationState(session, dialog.states.sets);
      session.endDialog();
      if(dialog.begin) {
        session.beginDialog(dialog.begin);
      }
    }
  ]).triggerAction({
    matches: _dialog.matches // LUIS matching
  });
}
```

**Comment by srozga** [comment]
In the first step, you can set `session.dialogData.originalArgs = args` and then in your second step, you can read the `session.dialogData.originalArgs` property.

**Comment by justinpchang** [comment]
Not sure why I didn't think of that. Thank you @srozga
