### ISSUE TITLE
How to access all intents and their scores returned from the LuisRecognizer?

### ISSUE THREAD

**Issue by bankotsu** [Microsoft/BotBuilder#4957]
## System Information
* SDK language (Node)
* Development environment - localhost
* Node.js + npm version
 8.11.3 + 4.0.5

## Issue Description
I want to find the two top intents in case a user's utterance contains two separate intents.
When I query LUIS with such an utterance through an http request I get the following result which contains all the defined intents and their scores:
{
  "query": "i want to call verizon about cancelling my service",
  "topScoringIntent": {
    "intent": "cancel service",
    "score": 0.521127462
  },
  "intents": [
    {
      "intent": "cancel service",
      "score": 0.521127462
    },
    {
      "intent": "contact no issue",
      "score": 0.201207742
    },
    {
      "intent": "None",
      "score": 0.0116497586
    },
    {
      "intent": "credentials",
      "score": 0.0110876216
    }
  ],
  "entities": [
    {
      "entity": "verizon",
      "type": "company",
      "startIndex": 15,
      "endIndex": 21,
      "resolution": {
        "values": [
          "Verizon"
        ]
      }
    },
    {
      "entity": "call",
      "type": "contact_method",
      "startIndex": 10,
      "endIndex": 13,
      "resolution": {
        "values": [
          "call"
        ]
      }
    }
  ]
}

But when a dialog is triggered by the LuisRecognizer in the bot builder and the recognition result is passed to the dialog through the args parameter, I can only see one intent. 
args.intent.intents which I thought should include all the intents (sorted by decreasing probability) is an array of size 1 containing only the top scoring intent.
Is there a way to get access from the bot builder to all the intents as seen in the query above?

I tried to do something like:
`builder.LuisRecognizer.recognize(session.message.text, '<model url>', function (err, intents, entities) {
     // do something with intents
});
`
But intents was still an array of size 1 containing only the top intent.
(The LUIS model I used for the http query and in the bot builder is the same one)

**Comment by poul-kg** [comment]
Try to call your LUIS url manually. with proper query `https://your-luis-app-url/some/path?q=your utterance` and see if you receive multiple intents there. If you see only one intent. then you need to configure your LUIS app to be verbose (I believe there's a checkbox) so it returns more intents.

**Comment by Kartik1607** [comment]
For verbose all you need to do is add a query param `&verbose=true` in LUIS url.
