### ISSUE TITLE
Botframework responses with intent with lower score

### ISSUE THREAD

**Issue by phuonglv6** [Microsoft/BotBuilder#4958]
System Information

SDK language (Node)
Development environment - localhost
Node.js + npm version
v8.7.0+ 5.6.0
Issue Description

**I tried to do something like:**
builder.LuisRecognizer.recognize(session.message.text, '<model url>', function (err, intents, entities) { // do something with intents });
But responses with intent with lower score than when I directly make a request to webservice  to LUIS

**Comment by corinagum** [comment]
Hi @phuonglv6, 

Would you be willing to share your codebase with me temporarily? I'd also like to take a look at your exported LUIS JSON if possible. Please feel free to add my email, v-corgum@microsoft.com

Could you also provide some examples of the score differences that you're receiving? Thank you.

**Comment by phuonglv6** [comment]
hi @corinagum
I fixed it, it is my mistake. Thank you

**Comment by corinagum** [comment]
Great! Glad you figured it out.
