### ISSUE TITLE
Setting session data to proactive message doesn't work

### ISSUE THREAD

**Issue by whatsdis** [Microsoft/BotBuilder#496]
I first send a proactive message to the user via sms channel inside OAuthCallback method

```
            var connector = new ConnectorClient();
            Message message = new Message();
            message.From = new ChannelAccount { Id = Constants.botId, Address = "+12312311", ChannelId = "sms", IsBot = true };
            message.To = new ChannelAccount { Id = newUserId, Address = "+18768763", ChannelId = "sms", IsBot = false };
            message.Text = $"How are you doing? ";
            message.Language = "en";
            connector.Messages.SendMessage(message);

            IBotData myDataBag = new JObjectBotData(message);

            myDataBag.UserData.SetValue("Username", "Bob");
            myDataBag.PerUserInConversationData.SetValue("Newuser", "yes");
```

Then in my main Dialog.cs I try to access it

```
public static readonly IDialog<string> dialog = Chain
            .PostToChain()            
            .Switch(new Case<Message, IDialog<string>>((msg) =>
                {
                    var regex = new Regex("hello$", RegexOptions.IgnoreCase);
                    return regex.IsMatch(msg.Text);
                }, (ctx, msg) =>
                {
                    // Clearing user related data upon logout
                    string isnewuser = ctx.PerUserInConversationData.TryGetValue("Newuser");
                    string username = ctx.UserData.TryGetValue("Username");
                    return Chain.Return($"Welcome {username}");
                })
             ).Unwrap().PostToUser();
```

I receive the message on my phone. However, I am not able to get back the username and newuser session data saved inside OAuthCallback.

I suspect that this is happening because the proactive message does not have conversationId set. And the conversationId must differ somehow.

**Comment by whatsdis** [comment]
well I've had the weekend to think this through and it's probably the case that you need to trigger a conversation first to get the userid and conversationId. I'm guessing that it's not possible to set a session data to a proactive message because it won't have the conversationId....

The only approach I'm thinking that might work is if I just stored all the session data on KV directly and pulling stuff from KV without using bot builder's session at all...but not sure of the security ramification of this since I'm not using certificates to communicate with KV (you need a basic plan and up $67 CAD / month just to be able to upload certificates!)...

**Comment by whatsdis** [comment]
Any ideas on using KV with expiry to set the relevant session information to carry it over to other dialogues after the proactive message is sent? I'm still not 100% sure if this is a good idea or not.

**Comment by msft-shahins** [comment]
In the new v3 API, you can call [CreateDirectConversationAsync](https://github.com/Microsoft/BotBuilder/blob/c4dbb7183cc1c23837b6d6c8bc03fe8c54ba1f55/CSharp/Library/Microsoft.Bot.Connector/ConversationsEx.cs#L56) to get a ConversationId for that user address and then you can use [StateClient](https://github.com/Microsoft/BotBuilder/blob/c4dbb7183cc1c23837b6d6c8bc03fe8c54ba1f55/CSharp/Library/Microsoft.Bot.Connector/StateClientEx.cs) to store data for that conversation before sending the proactive message.
