### ISSUE TITLE
High Latency Direct Line Channel

### ISSUE THREAD

**Issue by DanielTizon** [Microsoft/BotBuilder#4960]
## Bot Info
* SDK Platform: NodeJS
* SDK Version: 3.15.0
* Active Channels: Direct Line
* Deployment Environment: Azure Bot Service

## Issue Description
We are having very high latency problems, our bots are taking up to 15-20 secs to answer to the clients. It has started to happens today, 4 hours ago. The code haven't been modified for 2-3 months, and it was working nice until today

**Comment by nrobert** [comment]
Same here, since this morning we have issue with bots not responding / responding slowly.

- SDK Platform: C#
- SDK Version: 3.15.
- Active Channels: Direct Line / Webchat
- Deployment Environment: Azure Bot Service

This is highly impacting on production bots

**Comment by vincec-msft** [comment]
We removed the West Europe datacenter from Traffic Manager to get some diagnostics and restart it. That caused additional load on the North Europe datacenter which then scaled out.

Both datacenters are back online and traffic has stabilize. I'm watching the counters now to make sure.

**Comment by nrobert** [comment]
Thanks for this feedback @vincec-msft . How long should it take to get a normal state? Currently it is still in error on our side.

**Comment by vincec-msft** [comment]
North Europe has stabilized. West Europe is still throwing occasional errors. Still looking.

**Comment by vincec-msft** [comment]
System has been stable since 2018-08-10T13:57:00Z.

This was load related. Our instances scaled out but not quickly enough. We will set the scaling values such that there is no delay in handling the traffic.

**Comment by nrobert** [comment]
> We will set the scaling values such that there is no delay in handling the traffic.

We hope this will be efficient, because we are loosing a lot of confidence from our customers when there are such problems

**Comment by sharmadine** [comment]
@vincec-msft DirectLine errors has started appearing again in our bot services hosted in West Europe. We are seeing these error since `2018-08-13T08:12:09.407Z`

`Error: POST to 'https://directline.botframework.com/v3/conversations/1bneerxxxxD3/activities/1bneerxxxxxxx%7C0000013'`

We already have an escalation from our customer. Please suggest if anyone is looking at it?

**Comment by bhushanvadgave** [comment]
@vincec-msft Our bot services have again started giving directline errors (503 - Service Unavailable). Can you please check and update? May I also know why these errors are recurring? Our bot experience in production is getting skewed every now and then.

**Comment by vincec-msft** [comment]
This is a different problem. Load related. We're working on both helping the developer reduce their load and we're looking to expand our capacity.

By the way, if you're using polling with Direct Line, please consider switching to websockets. They're much more efficient and your customers and fellow Direct Line users will be grateful.

https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-receive-activities?view=azure-bot-service-3.0#connect-via-websocket

**Comment by DanielTizon** [comment]
Same here, other time happening the same....  What is the solution? Host bot Services in EEUU? That looks the only solution, because Europe and Asia are having problems everyday. And it's supposed to be a production ready service since beginning this year.

**Comment by alexandruf** [comment]
Same here, bot satisfaction dropped :)

**Comment by sharmadine** [comment]
@vincec-msft Thanks for the update. Would you have projected timeframe to overcome the load challenges? It will help us to let our customers know in advance of the downtime duration.

**Comment by vincec-msft** [comment]
We made several changes and optimizations today and do not expect the issue to reoccur.

I know those are famous last words, but in all seriousness the team worked very hard on short-term mitigations and is continuing to work on long-term architecture so that scale will not be a problem. It's a good problem to have, but it's also extremely frustrating for all of us when things don't run smoothly.

Thank you for your support.
