### ISSUE TITLE
Cortana manage on dev.botframework.com 

### ISSUE THREAD

**Issue by rjgmail88** [Microsoft/BotBuilder#4961]
I created a new Bot on **dev.botframework.com** and added Cortana channel on it.  Previously (1 month ago ), when I clicked on Manage button I was able to add Cortana auth setting right on **dev.botframework.com** but today it's taking me to [https://my.knowledge.store/](https://my.knowledge.store/)

I was told from Msoft that my.knowledge.store will go away and dev.botframework.com will be stable portal. What should we do at this point ? 

![image](https://user-images.githubusercontent.com/32375467/43964683-04d638a6-9c83-11e8-8d19-e095daa665c3.png)

**Comment by EricDahlvang** [comment]
This experience is currently different, depending on the account type being used.  Are you signing in with an MSA account, AAD on @microsoft.com, or what type of account are you signing in with?

**Comment by jwiley84** [comment]
Hi RJ!

This experience is currently different depending on the account type being used. Are you signing in with an MSA account, AAD on @microsoft.com, or a different type of account all together?

**Comment by rjgmail88** [comment]
I am using MSA account because of Cortana channel limitation. I can't add Cortana channel with my corp AAD account. I was under impression on person MSA's are supported and not work msa's. Just out of curiosity what other types of accounts are supported ? Is there any chance I can use my corporate AAD tenant account ?

**Comment by jwiley84** [comment]
You have it correct: personal MSAs work, @microsoft AADs currently are bugged, and other types of tenant accounts aren't set to work with Cortana yet. I just needed to make sure. 

I'm trying to track down alerts that my.knowledge.store is being deprecated, but I'm not seeing any information. Can you link me to where it says this? Or forward me an email at my github listed email address? 

The dev.botframework.com portal IS deprecated for the purpose of creating new bots; attempts to navigate it to create new bots should bring you to the Azure Portal, or if you find the one loop hole that allows you to create a bot there, it will warn you that it needs to be migrated to Azure. While it does work at a portal, bots should be created and maintained on portal.azure.com

**Comment by jwiley84** [comment]
Closing for lack of response from OP.
