### ISSUE TITLE
Can't configure Cortana Channel on Bot

### ISSUE THREAD

**Issue by Rykimaruh** [Microsoft/BotBuilder#4964]
I'm trying to configure Cortana Channel on a Web App Bot and this shows up regardless. Is the channel down?

![image](https://user-images.githubusercontent.com/5460795/43978862-b9322df4-9cb6-11e8-8207-44d8e8feca34.png)

**Comment by EricDahlvang** [comment]
Are you using an MSA account, or AAD within @microsoft.com ?

**Comment by EricDahlvang** [comment]
This issue does not affect all accounts.  A fix is expected to be released soon.

**Comment by EricDahlvang** [comment]
@Rykimaruh  Is this still an issue for you?  (a fix has been deployed)

**Comment by EricDahlvang** [comment]
I am no longer able to repeat this.  Please open a new issue if you are continuing to experience this, or any other problems with the portal.
