### ISSUE TITLE
Message text is below Hero Card in Facebook Messenger

### ISSUE THREAD

**Issue by Zhashkha** [Microsoft/BotBuilder#4966]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.15.3
* Active Channels: Facebook
* Deployment Environment: Azure Bot Service, Azure App Service

## Issue Description
I'm sending attachment Hero Card and simple text message in Facebook channel with  channelData property. Somehow text is always below the Hero Card and I can't find out why it's happening. 

https://prnt.sc/khgeen

## Code Example
// add text to message
            string messageText = OperatorHelper.ReminderNotificationTextGet(operatorCode);

            string cardImage = OperatorHelper.OperatorCardImageGet(operatorCode);
            var channelData = new
            {
                type = "template",
                payload = new
                {
                    template_type = "generic",
                    elements = new[]
                    {
                        new
                        {
                            title = OperatorHelper.ReminderNotificationOperatorTitleGet(operatorCode),
                            subtitle = balance,
                            image_url = imageUrl,
                            buttons = new[]
                            {
                                new
                                {
                                    type = ActionTypes.PostBack,
                                    title = TemplateTexts.ReminderNotificationLinkRedirectionTitle,
                                    payload = BotticelliApplicationConsts.ReminderNotificationLinkRedirectionValue
                                },
                                new
                                {
                                    type = ActionTypes.PostBack,
                                    title = TemplateTexts.ReminderNotificationSumTitle,
                                    payload = BotticelliApplicationConsts.ReminderNotificationSumValue
                                }
                            }
                        }
                    }
                }
            };

            replyToConversation.ChannelData = JObject.FromObject(
                new
                {
                    messaging_type = "RESPONSE",
                    notification_type = "REGULAR",
                    attachment = channelData,
                    text = messageText
                });

**Comment by JasonSowers** [comment]
This is happening because that is the way that hero cards are rendered.  You can see how most features will render on different channels by using the [Channel Inspector](https://docs.botframework.com/en-us/channel-inspector/channels/Skype/).  It is not 100% accurate and up to date because channels are constantly changing things, but it will give you a good general idea.

If you need fully customizable cards, please look into [Adaptive Cards](https://adaptivecards.io/).  Adaptive cards will give you much more control over how your rich content will look. They are not fully supported on Facebook, as they will be rendered to an image then have mapping to buttons. This may suffice for your needs though.

**Comment by Zhashkha** [comment]
Thanks for reply Jason.

Adaptive cards are poorly supported on Facebook, you simply can't rely on them. Now the reason why I've asked you is that if create a Hero card without ChannelData property, but with simple Bot Framework class, it would work normally. The text will be above the card attachment. That's why I thought it's possible with channel specific data too. Now the reason why I'm using channel specific data is that I have to push reminder notifications on Android. Native Bot Framework messages are just sent, but don't give any signal and don't appear in Messenger without your proactivity. It's a different issue, but maybe you can help me with that. Thanks in advance.

**Comment by JasonSowers** [comment]
I'm not sure I follow your second question.  Are you running into issues with the 24+1 policy with proactive messages?  Or is this an issue with no notification being sent?  Could you please try to explain the issue?

**Comment by Zhashkha** [comment]
I'm talking about notifications not being sent. I've started with this issue [#1339](https://github.com/Microsoft/BotBuilder/issues/1339) and it seems there is no workaround with native Bot Framework message to be pushed on mobile Messenger. So now I'm using channel specific message and getting message text below message attachment, which doesn't satisfy me. Any ideas would be greatly appreciated.

**Comment by JasonSowers** [comment]
Using channel specific data for Facebook is the way this would have to be accomplished.  If you have a better solution in mind you could always submit a pull request.

**Comment by Zhashkha** [comment]
Thank you for you effort Jason. I'm closing this issue.
