### ISSUE TITLE
Skype channel web control for bot framework not responding in IE9,10, 11. But works fine in Chrome.

### ISSUE THREAD

**Issue by nvikey** [Microsoft/BotBuilder#4969]
Skype channel web control for bot framework not responding in IE9,10, 11. But works fine in Chrome.

## Bot Info
* SDK Platform: 
* SDK Version: 
* Active Channels: 
* Deployment Environment: 

## Reproduction Steps
1.
2.
3.

**Comment by JasonSowers** [comment]
This repository is for issues with the Bot Framework SDK.  You will have to contact Skype for support with the Skype web control as it is not part of our code base. You can find their [uservoice here](https://skype.uservoice.com/forums/914527-skype-ideas)
