### ISSUE TITLE
Connecting a MS bot framework user to someone on Skype

### ISSUE THREAD

**Issue by vaditya04** [Microsoft/BotBuilder#497]
I've made a chat bot using Microsoft Bot Framework which answers a user's questions. When the bot is unable to answer the user's questions, I want to be able to redirect the user question to a customer rep on Skype.

The person on Skype will see the messages posted by the user, and his answers will be sent to the user.

Basically I need a bot which can interact with two people at once from different mediums (Skype, browser chat window).

Is this possible with the current framework? Any simpler solution for it?

**Comment by chrimc62** [comment]
This is definitely a good idea and something we have started to look at.

**Comment by nmzaheer** [comment]
Another way of accomplishing this would be to just add the customer rep to the Skype conversation with the user's permission.

Personally, i prefer this over your way bcoz the bot doesn't pretend to handle something it wasn't built for. Also, what would happen if all your backend customer reps are busy? How would you ask the user to wait?

**Comment by vaditya04** [comment]
@nmzaheer That would have been my solution if my user was also on Skype. **However, my user is constrained to use the Web Chat bot connector.** So I can't add them both to the same conversation. The bot has to act as an intermediary in this scenario.

**Comment by dmdnkv** [comment]
I wonder whether it is possible or not to get skype `username` when user added bot to contacts? Currently, we have just long encrypted or hashed id and display name.

**Comment by v-thgratMSGit** [comment]
Closing this issue. Thanks!
