### ISSUE TITLE
Bot emulator isn't able to connect to bot. Direct line issue ? 

### ISSUE THREAD

**Issue by rjgmail88** [Microsoft/BotBuilder#4971]
## Bot Info
* SDK Platform:Node.js 
* SDK Version: v3
* Active Channels: MS Teams

## Issue Description
Error in the v3 emulator 

![image](https://user-images.githubusercontent.com/32375467/44067360-b39d0a90-9f3a-11e8-9b63-2ed081bd514c.png)

error in V4 emulator 

![image](https://user-images.githubusercontent.com/32375467/44067291-6644a334-9f3a-11e8-8a83-da09b52f0468.png)

## Code Example
Running existing v3 bot code which were working fine as of today morning. 

## Reproduction Steps
Emulator is giving unknown error.

**Comment by jwiley84** [comment]
Hi RJ! We're going to need a bit more info. What do you mean by the bot code? Like, an app.js file? And are you using tunneling software such as ngrok?

**Comment by rjgmail88** [comment]
I meant app.js file. I see following path to ngrok in emulators settings. But i didnt configure it. 

```
/usr/local/bin/ngrok
```

**Comment by jwiley84** [comment]
So not tunneling. I asked because you have MS Teams listed as a channel. There isn't anything as far as the emulators are concerned going on, so I can I get a link to your code? You're more then welcome to email it to me if you would like.

**Comment by jwiley84** [comment]
Closing from lack of response from OP.
