### ISSUE TITLE
LUIS bot framework fails with error "ajaxExtended Call "

### ISSUE THREAD

**Issue by ciceka** [Microsoft/BotBuilder#4972]
## Bot Info
Deployment Environment: Azure Bot Service

## Issue Description
LUIS bot framework fails with error "ajaxExtended Call "

## Reproduction Steps
-Start creating Web App Bot in Azure Portal
-Set the parameters (in my case I'm using an existing resource group, creating Asure Storage)
- use luis API
-Press "create" button

![2018_08_14_09_14_24_bot_vorlage_microsoft_azure](https://user-images.githubusercontent.com/42337825/44077029-975add22-9fa2-11e8-8241-1b3bcf593b84.png)

I use West Europe and West US
Both didn't work

**Comment by Andrea-Orimoto** [comment]
Hi @ciceka , sorry for the inconvenience, do you happen to remember the botIds you used when you received this error?

**Comment by ciceka** [comment]
No, i don't remember but i used the same BotId with an another template for example "question and ask" and it works.
So i don't think that the problem was/is the BodID.

**Comment by Zerryth** [comment]
@ciceka  we've identified the issue, which happens intermittently in the LUIS API that prevents user authentication when attempting to create the bot from that specific template.

As of now it only occurs during extremely high traffic, and the team is working on a permanent fix. Before then, you can actually make a bot at a different time during "non-peak hours", that way you can get the ball rolling right away. 

Apologies for the inconvenience! And thank you for bringing up the issue.

**Comment by johnataylor** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
