### ISSUE TITLE
Unable to update logo in Bot Channels Registration

### ISSUE THREAD

**Issue by JonesAbramoff** [Microsoft/BotBuilder#4974]
Unable to update logo in portal.azure.com "Bot Channels Registration" resource, "Settings" tab.

It saves but doesn´t change.

I have tried in windows 10 Chrome and Edge.

Below is the trace in Edge.

=======================================================

 HTTP401: NEGADO - o recurso solicitado requer autenticação do usuário.
(XHR)GET - https://dev.botframework.com/api/Account

2 SCRIPT5007: Unable to get property 'prototype' of undefined or null reference
Util.ts (496,28)

 SCRIPT5007: Object expected
all_cf5e1cc9a93ce2278222.js (5,1140764)

 SCRIPT5007: Unable to get property 'prototype' of undefined or null reference
Util.ts (496,28)

 HTTP400: SOLICITAÇÃO INCORRETA - a solicitação não pôde ser processada pelo servidor devido a uma sintaxe inválida.
(XHR)PATCH - https://management.azure.com/subscriptions/aa0db728-6fb8-432b-ac76-4350c553aab8/resourceGroups/botzapprices/providers/Microsoft.BotService/botServices/NewFrog?api-version=2017-12-01

 [Microsoft_Azure_BotService]  ‎3‎:‎36‎:‎32‎ ‎PM Resource/ResourceArea 19 ResourceArea: patch bot service failed /subscriptions/aa0db728-6fb8-432b-ac76-4350c553aab8/resourceGroups/botzapprices/providers/Microsoft.BotService/botServices/NewFrog

 [Microsoft_Azure_BotService]  ‎3‎:‎36‎:‎32‎ ‎PM Resource/BotSettings/BotSettingsBlade 13 BotSettingsBlade: Failed patching resource entity _errorData: undefined

_sourceErrorLevel: undefined

baseTypes: ["MsPortalFx.Errors.AjaxError","MsPortalFx.Errors.Error"]

code: undefined

data: {"type":"PATCH","requestId":"ff1c3024-1479-479a-b394-8cad12f1001f","sessionId":"4c18672134534db98ee107cb6a20eb7f","status":400,"statusText":"Bad Request","duration":7129.600084975944}

description: ajaxExtended call failed

errorLevel: 2

errorThrown: Bad Request

extension: Microsoft_Azure_BotService

handled: undefined

innerErrors: []

jqXHR: {"readyState":4,"responseText":"{\"error\":{\"code\":\"InvalidBotData\",\"message\":\"message: The remote server returned an error: (404) Not Found. original trace:    at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndExecuteAsync[T](IAsyncResult result)\\r\\n   at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.>c__DisplayClass2`1.CreateCallback>b__0(IAsyncResult ar)\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()\\r\\n   at Intercom.ResourceProvider.DataProviders.BlobIconProvider.FreeUrl>d__2.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()\\r\\n   at Intercom.ResourceProvider.DataProviders.ResourceDataProvider.ReplaceResourceAsync>d__2.MoveNext()\"}}","responseJSON":{"error":{"code":"InvalidBotData","message":"message: The remote server returned an error: (404) Not Found. original trace:    at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndExecuteAsync[T](IAsyncResult result)\r\n   at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.>c__DisplayClass2`1.CreateCallback>b__0(IAsyncResult ar)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()\r\n   at Intercom.ResourceProvider.DataProviders.BlobIconProvider.FreeUrl>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()\r\n   at Intercom.ResourceProvider.DataProviders.ResourceDataProvider.ReplaceResourceAsync>d__2.MoveNext()"}},"status":400,"statusText":"Bad Request"}

message: ajaxExtended call failed

name: Error

source: undefined

stack: null

textStatus: error

timestamp: 595363.7024767651

type: MsPortalFx.Errors.AjaxError

 [Microsoft_Azure_BotService]  ‎3‎:‎36‎:‎32‎ ‎PM Resource/BotSettings/BotSettingsBlade 12 BotSettingsBlade: Failed refreshing resource entity _errorData: undefined

_sourceErrorLevel: undefined

baseTypes: ["MsPortalFx.Errors.AjaxError","MsPortalFx.Errors.Error"]

code: undefined

data: {"type":"PATCH","requestId":"ff1c3024-1479-479a-b394-8cad12f1001f","sessionId":"4c18672134534db98ee107cb6a20eb7f","status":400,"statusText":"Bad Request","duration":7129.600084975944}

description: ajaxExtended call failed

errorLevel: 2

errorThrown: Bad Request

extension: Microsoft_Azure_BotService

handled: undefined

innerErrors: []

jqXHR: {"readyState":4,"responseText":"{\"error\":{\"code\":\"InvalidBotData\",\"message\":\"message: The remote server returned an error: (404) Not Found. original trace:    at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndExecuteAsync[T](IAsyncResult result)\\r\\n   at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.>c__DisplayClass2`1.CreateCallback>b__0(IAsyncResult ar)\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()\\r\\n   at Intercom.ResourceProvider.DataProviders.BlobIconProvider.FreeUrl>d__2.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()\\r\\n   at Intercom.ResourceProvider.DataProviders.ResourceDataProvider.ReplaceResourceAsync>d__2.MoveNext()\"}}","responseJSON":{"error":{"code":"InvalidBotData","message":"message: The remote server returned an error: (404) Not Found. original trace:    at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndExecuteAsync[T](IAsyncResult result)\r\n   at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.>c__DisplayClass2`1.CreateCallback>b__0(IAsyncResult ar)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()\r\n   at Intercom.ResourceProvider.DataProviders.BlobIconProvider.FreeUrl>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()\r\n   at Intercom.ResourceProvider.DataProviders.ResourceDataProvider.ReplaceResourceAsync>d__2.MoveNext()"}},"status":400,"statusText":"Bad Request"}

message: ajaxExtended call failed

name: Error

source: undefined

stack: null

textStatus: error

timestamp: 595363.7024767651

type: MsPortalFx.Errors.AjaxError

3 [Microsoft_Azure_BotService]  ‎3‎:‎36‎:‎40‎ ‎PM MsPortalFx.Base.Diagnostics.ErrorReporter 1 MsPortalFx.Base.Diagnostics.ErrorReporter: _errorData: undefined

_sourceErrorLevel: undefined

baseTypes: ["MsPortalFx.Errors.AjaxError","MsPortalFx.Errors.Error"]

code: undefined

data: {"type":"PATCH","requestId":"ff1c3024-1479-479a-b394-8cad12f1001f","sessionId":"4c18672134534db98ee107cb6a20eb7f","status":400,"statusText":"Bad Request","duration":7129.600084975944}

description: ajaxExtended call failed

errorLevel: 2

errorThrown: Bad Request

extension: Microsoft_Azure_BotService

handled: undefined

innerErrors: []

jqXHR: {"readyState":4,"responseText":"{\"error\":{\"code\":\"InvalidBotData\",\"message\":\"message: The remote server returned an error: (404) Not Found. original trace:    at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndExecuteAsync[T](IAsyncResult result)\\r\\n   at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.>c__DisplayClass2`1.CreateCallback>b__0(IAsyncResult ar)\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()\\r\\n   at Intercom.ResourceProvider.DataProviders.BlobIconProvider.FreeUrl>d__2.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()\\r\\n   at Intercom.ResourceProvider.DataProviders.ResourceDataProvider.ReplaceResourceAsync>d__2.MoveNext()\"}}","responseJSON":{"error":{"code":"InvalidBotData","message":"message: The remote server returned an error: (404) Not Found. original trace:    at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndExecuteAsync[T](IAsyncResult result)\r\n   at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.>c__DisplayClass2`1.CreateCallback>b__0(IAsyncResult ar)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()\r\n   at Intercom.ResourceProvider.DataProviders.BlobIconProvider.FreeUrl>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()\r\n   at Intercom.ResourceProvider.DataProviders.ResourceDataProvider.ReplaceResourceAsync>d__2.MoveNext()"}},"status":400,"statusText":"Bad Request"}

message: ajaxExtended call failed

name: Error

source: undefined

stack: null

textStatus: error

timestamp: 595363.7024767651

type: MsPortalFx.Errors.AjaxError

**Comment by JasonSowers** [comment]
@JonesAbramoff sorry for the inconvenience there is a bug in the portal causing this.  You can either wait for it to be fixed, or you can put your image here with your bot handle and/or app id and we can upload it for you.

**Comment by JonesAbramoff** [comment]
Hi,

The bot handle is NewFrog and the logo is attached.

Thanks,

Jones
![logo4](https://user-images.githubusercontent.com/12601400/44164405-5408b800-a09c-11e8-8547-c97fd9ec7073.png)

**Comment by JasonSowers** [comment]
Done 👍 Again, sorry for the existence of this bug.

**Comment by johnataylor** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
