### ISSUE TITLE
Supporting ALL Messenger Webhook Events

### ISSUE THREAD

**Issue by odannyc** [Microsoft/BotBuilder#4975]
## Bot Info
* SDK Platform: .NET 
* SDK Version: 3.14
* Active Channels: Facebook Messenger

## Issue Description
I have built a bot that supports the facebook handover protocol.
So, if a user wants to talk to a human, they click a button and the code will pass_thread_control to a facebook page/app. When the user wants to come back and talk to the bot they have to say a keyword like "QUIT". To make this work I have to subscribe to "message_echoes" in the facebook developer options of the app. What this does is that facebook will send messages to the bot even if it doesn't have thread control. Unfortunately, botframework throws those events away, never making it to my actual code to process.
I want to know if we can have botframework support all these different events and forward them to my bot /api/messages endpoint.

I found another issues here where the person had to build a proxy infront of botframework to handle those messages. I would like to avoid this if possible.

Thanks!

**Comment by EricDahlvang** [comment]
Hi @odannyc 

Thank you for taking the time to post this feature request.  We've created an issue specifically for Facebook Messenger Feature Requests: https://github.com/Microsoft/BotBuilder/issues/4360  Please contribute to the discussion on that page.
