### ISSUE TITLE
There was an error sending this message to your bot: HTTP status code GatewayTimeout

### ISSUE THREAD

**Issue by sanket03** [Microsoft/BotBuilder#4977]
## Bot Info
* SDK Platform: > .Net
* SDK Version:  3.15.2.2
* Active Channels: Web chat
* Deployment Environment: Azure APP Service

## Issue Description
We are developing a web chatbot. Our Bot is functioning fine when we are testing in the localhost, but when we published the bot, we are not able to send the message to the bot. We are getting the error like " There was an error sending this message to your bot: HTTP status code GatewayTimeout ".

## Code Example

 We are not able to figure out the code, which part of the code is generating the issue. 

## Reproduction Steps
1.
2.
3.

## Expected Behavior
We should be able to send the message to the bot.

## Actual Results

The actual behavior for the bot :
After prompting the authentication required, we will get a code through which we will validate the user.
That behavior is working fine when we tested on the local host.
After publishing we are facing this issue when we tested in the web chat:

![2018-08-15 19_12_48-window](https://user-images.githubusercontent.com/13510656/44151141-48aaffa4-a0bf-11e8-99e1-79a03fed98b9.png)
![2018-08-15 19_11_38-window](https://user-images.githubusercontent.com/13510656/44151152-4eac2a4a-a0bf-11e8-8bc5-a9c55672cf87.png)

**Comment by jwiley84** [comment]
Hi Sanket! I know you said you’re not sure which part is causing the error, and unfortunatly 500s are hard to diagnose. Can you go ahead and put a link to your bot’s github repo so we can take a look?

**Comment by sanket03** [comment]
Hi Jessica! I can share the code over the email. will you please provide me your Email I'd.

**Comment by jwiley84** [comment]
Hi @sanket03! It's v-jewail@microsoft.com

**Comment by jwiley84** [comment]
Closing from lack of response from user.
