### ISSUE TITLE
Error 400 in inline mode on Telegram, WEBPAGE_MEDIA_EMPTY

### ISSUE THREAD

**Issue by fercom** [Microsoft/BotBuilder#498]
My bot was working fine a few days ago, but just recently started responding with "messages.sendInlineBotResult error 400 WEBPAGE_MEDIA_EMPTY". In my code there is no exception thrown.

You can call the bot in inline mode as this: "@the_memebot spongebob meme, nobody, cares please"

An example of the response I send to telegram:
{
  "method": "answerInlineQuery",
  "parameters": {
    "inline_query_id": "999490456007211111",
    "results": [
      {
        "type": "photo",
        "id": "1e515976-f9b1-4f35-ada0-b93c71ca3a5d",
        "title": "response from the_memebot",
        "photo_url": "http://memegen.link/custom/nobody/cares.jpg?alt=http://nick.mtvnimages.com/nick/video/images/spongebob-squarepants/spongebob-squarepants-179-full-episode-4x3.jpg?quality=0.51&maxdimension=600",
        "thumb_url": "http://memegen.link/custom/nobody/cares.jpg?alt=http://nick.mtvnimages.com/nick/video/images/spongebob-squarepants/spongebob-squarepants-179-full-episode-4x3.jpg?quality=0.51&maxdimension=600"
      },
      {
        "type": "photo",
        "id": "f09b914b-2597-4672-bf39-4212d3325042",
        "title": "response from the_memebot",
        "photo_url": "http://memegen.link/custom/nobody/cares.jpg?alt=http://www.shescribes.com/wp-content/uploads/2014/12/Spongebob_Squarepants_005.jpg",
        "thumb_url": "http://memegen.link/custom/nobody/cares.jpg?alt=http://www.shescribes.com/wp-content/uploads/2014/12/Spongebob_Squarepants_005.jpg"
      },
      {
        "type": "photo",
        "id": "82ce0831-fce0-4678-bacb-51025ead2998",
        "title": "response from the_memebot",
        "photo_url": "http://memegen.link/custom/nobody/cares.jpg?alt=http://www.nick.com/spongebob-squarepants/games/",
        "thumb_url": "http://memegen.link/custom/nobody/cares.jpg?alt=http://www.nick.com/spongebob-squarepants/games/"
      },
      {
        "type": "photo",
        "id": "ca25bfd6-05c2-4a25-b9a5-a8b54c8f274e",
        "title": "response from the_memebot",
        "photo_url": "http://memegen.link/custom/nobody/cares.jpg?alt=http://ia.media-imdb.com/images/M/MV5BMTU3NDgzMzgzNF5BMl5BanBnXkFtZTcwMDgyNjc2MQ@@._V1_CR0,30,250,141_AL_UX477_CR0,0,477,268_AL_.jpg",
        "thumb_url": "http://memegen.link/custom/nobody/cares.jpg?alt=http://ia.media-imdb.com/images/M/MV5BMTU3NDgzMzgzNF5BMl5BanBnXkFtZTcwMDgyNjc2MQ@@._V1_CR0,30,250,141_AL_UX477_CR0,0,477,268_AL_.jpg"
      }
    ]
  }
}

**Comment by eanders-MS** [comment]
Hi fercom, I just tried, and seems to work for me:
![image](https://cloud.githubusercontent.com/assets/12176807/16175011/bbb61054-3593-11e6-80fa-d470b2bb2d1e.png)
Blip in Telegram? Let me know if I can assist further.

**Comment by fercom** [comment]
Yes, it gives results, but when you try to send it if fails, in mobile gives error, in Computer just doesn't show the image

**Comment by eanders-MS** [comment]
@fercom It appears that your handler at http://memegen.link/custom/nobody/cares.jpg is not returning an image, but rather html, e.g.:

```html
<!DOCTYPE html>
<html>
<head>

  <title>NOBODY / CARES</title>

  <style>
    body {
      background-image: url("http://memegen.link/custom/nobody/cares.jpg?alt=http:%2F%2Fnick.mtvnimages.com%2Fnick%2Fvideo%2Fimages%2Fspongebob-squarepants%2Fspongebob-squarepants-179-full-episode-4x3.jpg%3Fquality=0.51&maxdimension=600");
      background-repeat: no-repeat;
    }
  </style>

  <!-- Google Analytics -->
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-6468614-10', 'auto');
    ga('send', 'pageview');
  </script>

</head>
<body>
</body>
</html>
```

I think Telegram is expecting a jpg.

**Comment by fercom** [comment]
Yes, but that's the way the http://memegen.link api gives the results, even if you copy the background-image url from the page it redirects you to the same page, this way worked fine a few days ago, telegram changed the way of receiving inline mode images (in direct chat with the bot it still works fine). Any sugestions to make it work?

**Comment by eanders-MS** [comment]
You might be able to accomplish this by extracting the image yourself:
1. Have the inline query URLs point back to your bot service at a different path, e.g.: /api/images
2. Have your service call memegen.link and get the html
3. Extract the background image url from the body style: `background-image: url("...")`
4. Request the contents of that url image url and get the jpeg bits
5. Pass jpeg bits back to caller

**Comment by fercom** [comment]
I will try it, but background-image: url("...") points to the original url

**Comment by eanders-MS** [comment]
They look the same to us humans, but in the second one the parameter is URL-encoded, so it's represented differently in the request. They must be handling the two differently.

Hey that makes me think you could just rewrite the memegen url directly, rather than doing all that work I listed out. Just url-encode everything after the first ? character.

**Comment by fercom** [comment]
I did it already:
`http://memegen.link/custom/nobody/cares.jpg?alt%3Dhttp%3A%2F%2Fwww.shescribes.com%2Fwp-content%2Fuploads%2F2014%2F12%2FSpongebob_Squarepants_005.jpg`
but the answer of the api seems to be the same

**Comment by eanders-MS** [comment]
I think you need to preserve the equal symbol in "cares.jpg?alt=", so that a parameter assignment is made. If you encode everything after that, I think it will work.

**Comment by fercom** [comment]
It doesn't :(
`http://memegen.link/custom/hello/world.jpg?alt=http%3A%2F%2Fboykinsbasketball.com%2Fwp-content%2Fuploads%2F2015%2F10%2F5451a9bac173c.preview-699.jpg`

**Comment by fercom** [comment]
I have changed the way of my response, but it still fails, any idea?
`{
  "method": "answerInlineQuery",
  "parameters": {
    "inline_query_id": "999490456424917205",
    "results": [
      {
        "type": "photo",
        "id": "86c7683a-c2aa-4700-b96e-b0b81197ed3a",
        "title": "response from the_memebot",
        "photo_url": "https://memebotstorage.blob.core.windows.net/savedmemes/e81b2f60-4f1f-4a59-8661-250d81cd4f10.png",
        "thumb_url": "https://memebotstorage.blob.core.windows.net/savedmemes/e81b2f60-4f1f-4a59-8661-250d81cd4f10.png"
      },
      {
        "type": "photo",
        "id": "3179b9fa-a45d-4644-8e90-da7f17a703f4",
        "title": "response from the_memebot",
        "photo_url": "https://memebotstorage.blob.core.windows.net/savedmemes/5c04de79-7ed2-49c1-ac97-8f1fd5449096.png",
        "thumb_url": "https://memebotstorage.blob.core.windows.net/savedmemes/5c04de79-7ed2-49c1-ac97-8f1fd5449096.png"
      },
      {
        "type": "photo",
        "id": "86ac1d74-b2e5-4cc5-85e1-d053db19aa9d",
        "title": "response from the_memebot",
        "photo_url": "https://memebotstorage.blob.core.windows.net/savedmemes/2330f9a3-0ca3-4388-a7aa-d798b1c86f19.png",
        "thumb_url": "https://memebotstorage.blob.core.windows.net/savedmemes/2330f9a3-0ca3-4388-a7aa-d798b1c86f19.png"
      },
      {
        "type": "photo",
        "id": "32b74138-ec17-4d08-bdbb-927d6ea7d73a",
        "title": "response from the_memebot",
        "photo_url": "https://memebotstorage.blob.core.windows.net/savedmemes/47deef2b-6885-4520-9d36-7f0b777b85e5.png",
        "thumb_url": "https://memebotstorage.blob.core.windows.net/savedmemes/47deef2b-6885-4520-9d36-7f0b777b85e5.png"
      }
    ]
  }
}`

**Comment by eanders-MS** [comment]
I believe Telegram expects the result field of anserInlineQuery to be stringified JSON: https://core.telegram.org/bots/api#answerinlinequery. Try wrapping it in a call to JSON.stringify().

**Comment by fercom** [comment]
Like this?
{
  "method": "answerInlineQuery",
  "parameters": {
    "inline_query_id": "999490456104457744",
    "results": "[{\"type\":\"photo\",\"id\":\"f08b7f98-2abe-4c4c-9b9c-22306d992e9b\",\"title\":\"response from the_memebot\",\"photo_url\":\"https://memebotstorage.blob.core.windows.net/savedmemes/1313cb52-f383-40e6-84c9-b1d9e8c360e9.png\",\"thumb_url\":\"https://memebotstorage.blob.core.windows.net/savedmemes/1313cb52-f383-40e6-84c9-b1d9e8c360e9.png\"},{\"type\":\"photo\",\"id\":\"70737462-b0ce-4ce6-b7e3-6f7557ce8057\",\"title\":\"response from the_memebot\",\"photo_url\":\"https://memebotstorage.blob.core.windows.net/savedmemes/5afb7f22-f2e1-47a5-880d-7c8d615b04a1.png\",\"thumb_url\":\"https://memebotstorage.blob.core.windows.net/savedmemes/5afb7f22-f2e1-47a5-880d-7c8d615b04a1.png\"},{\"type\":\"photo\",\"id\":\"5346b889-7d10-4a40-96a4-9ca5ebb365bd\",\"title\":\"response from the_memebot\",\"photo_url\":\"https://memebotstorage.blob.core.windows.net/savedmemes/4b402fb9-9ae2-42e2-b145-942a63b65343.png\",\"thumb_url\":\"https://memebotstorage.blob.core.windows.net/savedmemes/4b402fb9-9ae2-42e2-b145-942a63b65343.png\"},{\"type\":\"photo\",\"id\":\"8d6573b0-2061-4641-b4c7-ce379f71c8ef\",\"title\":\"response from the_memebot\",\"photo_url\":\"https://memebotstorage.blob.core.windows.net/savedmemes/2945bf18-6dbc-47f4-9a0c-5667ffe7d2e4.png\",\"thumb_url\":\"https://memebotstorage.blob.core.windows.net/savedmemes/2945bf18-6dbc-47f4-9a0c-5667ffe7d2e4.png\"}]"
  }
}

**Comment by fercom** [comment]
{"method":"answerInlineQuery","parameters":{"inline_query_id":"999490456393856090","results":[{"type":"photo","id":"012f8a39-fa28-4868-a28e-4aa2b9c7840f","title":"response from the_memebot","photo_url":"https://memebotstorage.blob.core.windows.net/savedmemes/f5873ae9-7f1d-4d9c-9de0-4eb063dd1903.png","thumb_url":"https://memebotstorage.blob.core.windows.net/savedmemes/f5873ae9-7f1d-4d9c-9de0-4eb063dd1903.png"},{"type":"photo","id":"ab8f2cde-1a44-4bfd-b92c-80353df219c8","title":"response from the_memebot","photo_url":"https://memebotstorage.blob.core.windows.net/savedmemes/1cc1ae98-032a-4564-a232-a4f66f96d8ff.png","thumb_url":"https://memebotstorage.blob.core.windows.net/savedmemes/1cc1ae98-032a-4564-a232-a4f66f96d8ff.png"},{"type":"photo","id":"4d508042-e25b-4ddb-82e1-78dfcd43c9fc","title":"response from the_memebot","photo_url":"https://memebotstorage.blob.core.windows.net/savedmemes/3a52d17d-d0c0-4295-9d00-ec588c613a0b.png","thumb_url":"https://memebotstorage.blob.core.windows.net/savedmemes/3a52d17d-d0c0-4295-9d00-ec588c613a0b.png"},{"type":"photo","id":"70106dd7-7bba-40fa-8606-13044a5c4279","title":"response from the_memebot","photo_url":"https://memebotstorage.blob.core.windows.net/savedmemes/59c441e3-61b6-4342-be61-d5a495b5aaec.png","thumb_url":"https://memebotstorage.blob.core.windows.net/savedmemes/59c441e3-61b6-4342-be61-d5a495b5aaec.png"}]}} gives me: 
![image](https://cloud.githubusercontent.com/assets/19654168/16470754/a6403d2a-3e1d-11e6-92d1-0d569e8ed16f.png)

**Comment by eanders-MS** [comment]
I tested your reply message with my test bot, and it worked mostly as I would have expected:
![image](https://cloud.githubusercontent.com/assets/12176807/16477079/8e30bdd8-3e43-11e6-9a48-3bf4908127de.png)
After making a selection, it shows a black rectangle in the chat stream where I would have expected to see the thumbnail:
![image](https://cloud.githubusercontent.com/assets/12176807/16477113/c1a5d112-3e43-11e6-8e2f-f8f04e5fc4e0.png)
Could it be the thumbnail is too high-res? Just a guess.
Clicking on the rectangle, I am able to view the selected image at full resolution.
Here's the exact format of my reply message:
```javascript
var reply = {
	method:"answerInlineQuery",
	parameters:{
		inline_query_id: session.message.channelData.inline_query.id,
		results:JSON.stringify([
			{
				"type":"photo",
				"id":"86c7683a-c2aa-4700-b96e-b0b81197ed3a",
				"title":"response from the_memebot",
				"photo_url":"https://memebotstorage.blob.core.windows.net/savedmemes/e81b2f60-4f1f-4a59-8661-250d81cd4f10.png",
				"thumb_url":"https://memebotstorage.blob.core.windows.net/savedmemes/e81b2f60-4f1f-4a59-8661-250d81cd4f10.png"
			},
			{
				"type":"photo",
				"id":"3179b9fa-a45d-4644-8e90-da7f17a703f4",
				"title":"response from the_memebot",
				"photo_url":"https://memebotstorage.blob.core.windows.net/savedmemes/5c04de79-7ed2-49c1-ac97-8f1fd5449096.png",
				"thumb_url":"https://memebotstorage.blob.core.windows.net/savedmemes/5c04de79-7ed2-49c1-ac97-8f1fd5449096.png"
			},
			{
				"type":"photo",
				"id":"86ac1d74-b2e5-4cc5-85e1-d053db19aa9d",
				"title":"response from the_memebot",
				"photo_url":"https://memebotstorage.blob.core.windows.net/savedmemes/2330f9a3-0ca3-4388-a7aa-d798b1c86f19.png",
				"thumb_url":"https://memebotstorage.blob.core.windows.net/savedmemes/2330f9a3-0ca3-4388-a7aa-d798b1c86f19.png"
			},
			{
				"type":"photo",
				"id":"32b74138-ec17-4d08-bdbb-927d6ea7d73a",
				"title":"response from the_memebot",
				"photo_url":"https://memebotstorage.blob.core.windows.net/savedmemes/47deef2b-6885-4520-9d36-7f0b777b85e5.png",
				"thumb_url":"https://memebotstorage.blob.core.windows.net/savedmemes/47deef2b-6885-4520-9d36-7f0b777b85e5.png"
			}
		])
	}
};
session.sendMessage(reply);
```

**Comment by fercom** [comment]
That is exactly how it currently works, it is not because of the thumbnail resolution, the thumbnail is used in the results preview,  have you tested it on mobile? It gives an "empty media" error. I dont know what else can I do

**Comment by eanders-MS** [comment]
I think your best bet might be to chat with Telegram Bot Support [@BotSupport](https://web.telegram.org/#/im?p=@BotSupport). If you find a solution, please do post it here.

**Comment by fercom** [comment]
I already did but they do not answer

**Comment by fercom** [comment]
It is solved. Because my images were stored in a blob on azure I need to change the content type to "image/jpeg". More info on: [http://stackoverflow.com/questions/10040403/set-content-type-of-media-files-stored-on-blob](url)
