### ISSUE TITLE
validating a JWT access token returned by GetTokenDialog

### ISSUE THREAD

**Issue by skyovi** [Microsoft/BotBuilder#4980]
SDK Platform: .NET Framework 4.6
SDK Version: 3.15.2.2
Active Channels: Direct Line, Teams
OAuth Provider: AAD v1
Deployment Environment: Azure App Service
OAuth Service Provider: AAD v1

Does the Bot framework (token.botframework.com) validate (issuer, audience, nonce and expiration) the JWT token before returning it the bot app  or Do I need to manually validate the JWT access token before process it in the app? 

I am using JwtSecurityToken instead of GraphServiceClient  to extract the required claims from the access token, since GraphServiceClient is not returning the required properties (given name and surname) for AAD guest users.

**Comment by mingweiw** [comment]
Bot framework doesn't validate the JWT token before returning it to the bot app. You should do your own validation.

**Comment by skyovi** [comment]
Thanks @mingweiw  . I will add custom validation logic to our app.
