### ISSUE TITLE
Email Channel Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by clari182** [Microsoft/BotBuilder#4981]
## Bot Info
* SDK Platform:  Node.js
* SDK Version: 
* Active Channels:  Email
* Deployment Environment:  Azure Bot Service

## Issue Description
Hi, I created a Node.js Bot on Azure and connected it to  the Email Channel.

Whenever I send an email to that address I get an error in the botbuilder module.
When debugging, the message.user comes null and also the message.address

```
TypeError: Cannot read property 'id' of undefined
UniversalBot.js:548
    at c:\Project\The Bot Makers\terminus\terminus-bot\node_modules\botbuilder\lib\bots\UniversalBot.js:144:51
    at c:\Project\The Bot Makers\terminus\terminus-bot\node_modules\botbuilder\lib\bots\UniversalBot.js:427:53
    at UniversalBot.tryCatch (c:\Project\The Bot Makers\terminus\terminus-bot\node_modules\botbuilder\lib\bots\UniversalBot.js:516:13)
    at next (c:\Project\The Bot Makers\terminus\terminus-bot\node_modules\botbuilder\lib\bots\UniversalBot.js:427:23)
    at UniversalBot.eventMiddleware (c:\Project\The Bot Makers\terminus\terminus-bot\node_modules\botbuilder\lib\bots\UniversalBot.js:430:9)
    at c:\Project\The Bot Makers\terminus\terminus-bot\node_modules\botbuilder\lib\bots\UniversalBot.js:141:23
    at c:\Project\The Bot Makers\terminus\terminus-bot\node_modules\botbuilder\lib\bots\UniversalBot.js:472:53
    at UniversalBot.tryCatch (c:\Project\The Bot Makers\terminus\terminus-bot\node_modules\botbuilder\lib\bots\UniversalBot.js:516:13)
    at c:\Project\The Bot Makers\terminus\terminus-bot\node_modules\botbuilder\lib\bots\UniversalBot.js:472:23
    at UniversalBot.tryCatch (c:\Project\The Bot Makers\terminus\terminus-bot\node_modules\botbuilder\lib\bots\UniversalBot.js:516:13)
```
I bought an Office 365 for a month and then created the outlook email.

## Code Example
```javascript
var connector = new builder.ChatConnector({
        appId: process.env.MICROSOFT_APP_ID,
        appPassword: process.env.MICROSOFT_APP_PASSWORD
    });

var bot = new builder.UniversalBot(connector);
```
The Microsoft App ID is:
 dc11036f-4731-4c1e-8c3f-f001e17e9df0

**Comment by jwiley84** [comment]
Hi Clara! I'm looking into this for you!

**Comment by jwiley84** [comment]
Hi @clari182!

Just for clarification, did you create the node bot on Azure, connect the email channel, and now you're using the standard echo bot dialog that the basic node bot comes templated with? Or are you using separate code with tunneling software, such as ngrok? If so, can you post the app.js (or similar) code?

**Comment by jwiley84** [comment]
Hi @clari182!

I'm still working with your original bot, as it has a different error (HTTP 400) then from the new one (HTTP 502). However, when I run queries for 10 day and older, I get responses no newer then 18 August, and when I try to run specifically for errors or successes in the last 3 days I get "Unable to find the bot with the specified id." Have you taken it offline, or deleted it in the last 3 days?

**Comment by jwiley84** [comment]
Closing for lack of response from OP.
