### ISSUE TITLE
DirectLine endOfConversation activity doesn't actually end conversation

### ISSUE THREAD

**Issue by chaoteng** [Microsoft/BotBuilder#4982]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.15.3
* Active Channels: DirectLine
* Deployment Environment: Azure Bot Service

## Issue Description
As described in https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-end-conversation?view=azure-bot-service-3.0#send-an-endofconversation-activity, after an endOfConversation activity is sent, "neither the client nor the bot can send any additional messages to the conversation". It seems to say the Direct Line channel will end the conversation automatically when it sees the endOfConversation activity. However, it's not the case. After we post endOfConversation activity, the conversation is just like normal. Do I misunderstand the document? Does it just say it's a placeholder event so that bot can use as an indicator?

## Code Example
```
var event = activity.CreateReply();
event.Type = ActivityTypes.EndOfConversation;
await context.PostAsync(event);
```

## Expected Behavior
After the event is sent, neither the client nor the bot can send any additional messages to the conversation.

## Actual Results
Both client and bot can continue conversation without as problem.

**Comment by nyxsys** [comment]
I've been able to reproduce this. It appears to be a bug, going to look into it further.

**Comment by chaoteng** [comment]
Thank you. I will implement the feature in the client side then.
