### ISSUE TITLE
Channel Inspector is completely broken

### ISSUE THREAD

**Issue by artemious7** [Microsoft/BotBuilder#4983]
## Bot Info
Not applicable.

## Issue Description
[The Channel Inspector web page](https://docs.botframework.com/en-us/channel-inspector/channels/Telegram?f=AdaptiveCards&e=example1) is completely broken - it fails to load any resources - styles, scripts, images. All of them return 404 (Not Found) error.

## Code Example
Not applicable.

## Reproduction Steps
1. Open the web page https://docs.botframework.com/en-us/channel-inspector/channels/Telegram?f=AdaptiveCards&e=example1
2. The web page is almost plain text

## Expected Behavior
The web page should display correctly.

## Actual Results
The web page is almost plain text

![image](https://user-images.githubusercontent.com/16724889/44282958-700b8580-a265-11e8-9bdd-ac7322b816f5.png)

**Comment by EricDahlvang** [comment]
Hi @artemious7 

Thank you for taking the time to post this.  I've escalated the issue to the docs team.

**Comment by EricDahlvang** [comment]
@artemious7 This has been fixed.
