### ISSUE TITLE
Direct Line error on intializing

### ISSUE THREAD

**Issue by 10p30pl3** [Microsoft/BotBuilder#4984]
## Bot Info
* SDK Platform: Node.js
* SDK Version: 3
* Active Channels: Direct Line 
* Deployment Environment: Azure Bot Service 

## Issue Description
Since about one hour ago I started getting error on direct line application

## Code Example
    var directLineClient = rp(directLineSpecUrl)
        .then(function (spec) {
            // Client
            return new Swagger({
                spec: JSON.parse(spec.trim()),
                usePromise: true
            });
        })
        .then(function (client) {
            // Obtain a token using the Direct Line secret
            // First, add the Direct Line Secret to the client's auth header
            client.clientAuthorizations.add('AuthorizationBotConnector', new Swagger.ApiKeyAuthorization('Authorization', 'Bearer ' + directLineSecret, 'header'));
            return client;
        });

## Reproduction Steps
1. initiate directline script
2. error on initialization

## Expected Behavior
Run normally

## Actual Results
2018-08-17T18:48:13.369Z - error: Error initializing DirectLine client StatusCodeError: 404 - "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable."
    at new StatusCodeError (/home/people/mbot/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/home/people/mbot/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/home/people/mbot/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/home/people/mbot/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.EventEmitter.emit (domain.js:442:20)
    at Request.<anonymous> (/home/people/mbot/node_modules/request/request.js:1157:10)
    at Request.emit (events.js:182:13)
    at Request.EventEmitter.emit (domain.js:442:20)
    at IncomingMessage.<anonymous> (/home/people/mbot/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:275:13)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:442:20)
    at endReadableNT (_stream_readable.js:1091:14)
    at process._tickCallback (internal/process/next_tick.js:174:19)

**Comment by EricDahlvang** [comment]
Hi @10p30pl3

Please share the
-BotHandle
-MicrosoftAppId
-Where does the DirectLineClient code reside? (what data center)

**Comment by 10p30pl3** [comment]
Calling:
https://docs.botframework.com/en-us/restapi/directline3/swagger.json
 I'm getting:
The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

Swagger endpoint has changed for directline V3?

**Comment by EricDahlvang** [comment]
@10p30pl3 Thank you for reporting this.  I've escalated this issue to the docs team, and I'll report back once I hear from them.

**Comment by EricDahlvang** [comment]
@10p30pl3 This has been fixed.

**Comment by 10p30pl3** [comment]
Thank you

**Comment by EricDahlvang** [comment]
The swagger file is again available at: https://docs.botframework.com/en-us/restapi/directline3/swagger.json

What sort of errors are you seeing?

**Comment by 10p30pl3** [comment]
It is initializing ok. But when I try to send any message 


            // Send message

            client.Conversations.Conversations_PostActivity(

                {

                    conversationId: conversationId,

                    activity: {

                        textFormat: 'plain',

                        text: input,

                        type: 'message',

                        from: {

                            id: directLineUserId,

                            name: directLineUserId

                        }

                    }

                }).catch(function (err) {

                    console.error('Error sending message:', err);

                });


I just get error

**Comment by 10p30pl3** [comment]
Error:

{ url: 'https://directline.botframework.com/v3/directline/conversations/LS7eaamiZAU4IwZ2NzlkM5/activities',
  method: 'POST',
  headers:
   { 'cache-control': 'no-cache',
     pragma: 'no-cache',
     'content-length': '116',
     'content-type': 'application/json; charset=utf-8',
     expires: '-1',
     server: 'Microsoft-IIS/10.0',
     'x-powered-by': 'ASP.NET',
     'strict-transport-security': 'max-age=31536000',
     date: 'Fri, 17 Aug 2018 23:11:18 GMT',
     connection: 'close' },
  errObj:
   { Error: Forbidden
    at Request.callback (/home/people/mbot/node_modules/superagent/lib/node/index.js:698:17)
    at IncomingMessage.<anonymous> (/home/people/mbot/node_modules/superagent/lib/node/index.js:922:12)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:442:20)
    at endReadableNT (_stream_readable.js:1091:14)
    at process._tickCallback (internal/process/next_tick.js:174:19)
     original: null,
     response:
      Response {
        domain: null,
        _events: {},
        _eventsCount: 0,
        _maxListeners: undefined,
        res: [IncomingMessage],
        request: [Request],
        req: [ClientRequest],
        links: {},
        text: '{\r\n  "error": {\r\n    "code": "BadArgument",\r\n    "message": "Security token not valid for this conversation"\r\n  }\r\n}',
        body: [Object],
        files: {},
        buffered: true,
        headers: [Object],
        header: [Object],
        statusCode: 403,
        status: 403,
        statusType: 4,
        info: false,
        ok: false,
        redirect: false,
        clientError: true,
        serverError: false,
        error: [Error],
        accepted: false,
        noContent: false,
        badRequest: false,
        unauthorized: false,
        notAcceptable: false,
        forbidden: true,
        notFound: false,
        charset: 'utf-8',
        type: 'application/json',
        setEncoding: [Function: bound ],
        redirects: [] },
     status: 403 },
  status: 403,
  statusText: '{\r\n  "error": {\r\n    "code": "BadArgument",\r\n    "message": "Security token not valid for this conversation"\r\n  }\r\n}',
  obj:
   { error:
      { code: 'BadArgument',
        message: 'Security token not valid for this conversation' } },
  data: '{\r\n  "error": {\r\n    "code": "BadArgument",\r\n    "message": "Security token not valid for this conversation"\r\n  }\r\n}' }

**Comment by 10p30pl3** [comment]
I am able to get a new token and conversation ID. 
But whenever I try to use this conversation ID I get "Security token not valid for this conversation".
I tried to regenerate keys, but no success.

**Comment by 10p30pl3** [comment]
Anyone else with this problem??

**Comment by sunilsoniudaipur** [comment]
https://docs.botframework.com/en-us/restapi/directline3/swagger.json is again redirecting to another url
https://docs.microsoft.com/en-us/azure/bot-service/?view=azure-bot-service-4.0 and bot having an error initializing

**Comment by EricDahlvang** [comment]
Thanks for reporting this.  I'll look into it and get back to you.

**Comment by kamalpaliwal** [comment]
The same issue we are facing when we can expect resolution as it is impacting our live application and we have not alternate solution. Either suggest some alternate solution or please do the needful ASAP.

**Comment by 10p30pl3** [comment]
System down again.
Getting error on initialization
06022019-09:49:35:142 - error: Error initializing DirectLine client SECRET.... SyntaxError: Unexpected token < in JSON at position 0

Same problem again??

**Comment by kamalpaliwal** [comment]
could you please share the swagger.json file

**Comment by 10p30pl3** [comment]
email?

**Comment by kamalpaliwal** [comment]
> email?

kamalkant.paliwal@advaiya.com

**Comment by 10p30pl3** [comment]
sent

**Comment by gandarezt** [comment]
hey. I also have the same problem. could you please send me a swagger file?
email: gandarez.t@gmail.com

Thank you.

**Comment by EricDahlvang** [comment]
@10p30pl3 thanks, i've put it in a gist: https://gist.github.com/EricDahlvang/ab4197b85dba47212df804d6245a5061 until we can find out where this file is hosted now.

Note: It is probably a good idea to not take an external dependency on a file located in the docs.

**Comment by EricDahlvang** [comment]
The directline swagger file can now be found here: https://github.com/Microsoft/BotBuilder/blob/master/specs/botframework-protocol/directline-3.0.json

The path or filename might change in the future, so please make a copy if you are planning to use it at runtime.

**Comment by kamalpaliwal** [comment]
> sent

Thanks a lot... your shared file is working perfectly.

**Comment by thiagodosreis** [comment]
Having the same problem.
@EricDahlvang any update on the problem, please?

**Comment by EricDahlvang** [comment]
The latest swagger file is here: https://github.com/Microsoft/BotBuilder/blob/master/specs/botframework-protocol/directline-3.0.json (note: for it to work with swagger-client you will need to set the tokenParameters required to false https://github.com/Microsoft/BotBuilder/pull/5289/files )

Please download and host it locally, rather than retrieving it at runtime.

**Comment by sunilsoniudaipur** [comment]
Thanks, @EricDahlvang
