### ISSUE TITLE
Difference between Bot / Bot Service -/ Bot Connector Service / Bot Builder and the bot in the webchat

### ISSUE THREAD

**Issue by DMZ011** [Microsoft/BotBuilder#4987]
I am reading the docs, but I am a little bit confused regarding the terms being used, so if someone can clarify things for me, it would be great.

Currently, I am trying to build a bot that will be available as Web Chat and Skype. I am using NodeJS to build the bot that's hosted in Azure. Would I be right if I say the bot itself is the Nodejs app hosted in Azure and the bot service is the Web App Bot in azure? in this case, where would I see Bot Connector Service in Azure? 

If I am using Web Chat, is the web chat referred to as the bot or as the channel or a client for the bot? Same for Skype?

Any clarification would be much appreciated.

**Comment by EricDahlvang** [comment]
Bots need Bot Registration resource in Azure, for the settings and channel configuration info.  For a WebApp bot, the registration is tied directly to the Web App resource.  For a registration only bot, the registration information is its own resource, and the web application can be hosted anywhere.  

The node.js app IS the bot code itself.  The Bot Service, would be the channel connectors ... these are hosted by Microsoft, and not something you will see in your Azure resources.

WebChat is both a channel, and a client.  A list of channels can be found here:  https://github.com/Microsoft/BotBuilder/blob/master/Node/core/src/Channel.ts#L37  The webchat control ( https://github.com/Microsoft/BotFramework-WebChat/ ) uses the WebChat channel, OR the DirectLine channel (depending on how WebChat is constructed).

**Comment by DMZ011** [comment]
Thanks @EricDahlvang  .. so in Azure, the resource that's called: 'Web App Bot' that's actually the registration, and the 'App Service' This is the website for the bot? am I right with my understanding? If I want to host the bot somewhere on premises, how do I create the 'Web App Bot' without it provisioning the 'App Service' then?

**Comment by EricDahlvang** [comment]
In order to have a registration without an associated web app, you create a **Bot Channels Registration** instead of a **Web App Bot**

![image](https://user-images.githubusercontent.com/11055362/44365881-d370ff80-a47f-11e8-834d-a383d607ac87.png)

**Comment by DMZ011** [comment]
@EricDahlvang Thank you. That clears things up.
