### ISSUE TITLE
Improving overall documentation

### ISSUE THREAD

**Issue by thewhitetulip** [Microsoft/BotBuilder#499]
The bot framework is amazing, it just needs two things
1. Portable documentation
2. More examples

**Comment by chrimc62** [comment]
Not sure what you mean by portable documentation, but definitely agree more examples would be great.  We continue to work on adding examples and documentation, but we have our hands full trying to advance the builder so any help the community can provide would be appreciated.

**Comment by thewhitetulip** [comment]
I would love to help in any way possible, what I mean by portable documentation is a PDF version which will be portable.

When I am writing my bot, I'd like to have the PDF in handy like the SQL manual or the Python docs or even the Go documentation.

How do I contribute to the documentation? I didn't find a link to do so. Please guide me in the right way, I'll contribute the examples and easy to understand documentation.

**Comment by thewhitetulip** [comment]
@chrimc62 Is the documentation open sourced?

**Comment by chrimc62** [comment]
That would be great!  I believe Doxygen can be coaxed to also generate a PDF, but the HTML is pretty portable as well.

**Comment by thewhitetulip** [comment]
@chrimc62 I am still unsure how the docs are generated, can you pls guide me? which files should I be looking for this?

**Comment by chrimc62** [comment]
If you clone this repository you will see a documentation directory.  The documentation is written primarily using the DOxygen mark down format.  If you look at Forms.cs you can see the FormFlow documentation.  If you install DOxygen, there is a help file describing the format.  It is generally pretty straightforward and there are lots of examples in the docs.  Let me know if you need more.

What kind of examples are you thinking of adding?  If it were on dialogs in general you would add to the dialogs.cs file.

**Comment by thewhitetulip** [comment]
I want to add more examples, not complete bot example like the todoBot, but explaining basic concepts using small practical examples, and a few strategies of building a bot, from basic to advanced.

**Comment by thewhitetulip** [comment]
@chrimc62 any thoughts?

**Comment by chrimc62** [comment]
@Stevenic is the best person to cooridinate with on node.js examples.  I know he has done a bunch of examples, but not sure where he is on documenting them and I'm sure he would appreciate the help.  The node code is documented using typedoc.

**Comment by v-thgratMSGit** [comment]
Closing this issue. @Stevenic - please comment if you have anything to add regarding node.js examples. Thanks!

**Comment by Stevenic** [comment]
We're always working towards more examples and better docs.
