### ISSUE TITLE
Skype for Business channel stops working after changing Azure bot messaging endpoint

### ISSUE THREAD

**Issue by spacether** [Microsoft/BotBuilder#4991]
## Bot Info
* SDK Platform: N/A
* SDK Version: N/A
* Active Channels: Skype for Business, Webchat
* Deployment Environment: Azure Bot Channels Registration

## Issue Description
When a user creates an Azure bot channels registration, adds the Skype for Business channel, and then later changes the bot messaging endpoint in Azure, messages are incorrectly routed to the old messaging endpoint, when they should be routed to the new Azure bot messaging endpoint.

## Code Example
N/A

## Reproduction Steps
1. create a bot channels registration in MS Azure and point it to endpoint_1
2. add the webchat channel and the Skype for Business (SFB) channel
3. confirm that both channels receive and respond to SFB events using one of the MS Bot examples
4. change you messaging endpoint from old endpoint_1 to a new different endpoint_2
5. confirm that webchat still works and the bot can receive and respond to messages (SUCCEEDS)
6. confirm that SFB still works and the bot can receive and respond to messages (FAILS)

## Expected Behavior
When one changes the bot messaging endpoint in Azure, the SFB channel should keep working.

## Actual Results
The SFB channel stops working and SFB attempts to contact the old endpoint_1 and does not use the new endpoint_2.

**Comment by spacether** [comment]
Note:
A end user can get endpoint_2 working despite this bug by following the below steps:
- Deleted the "Skype for Business" channel in the bot channels registration
- Added the "Skype for Business" channel in the bot channels registration
Note: I did not uninstall the bot from the office365 org, and I did not run the New-CsOnlineApplicationEndpoint command to reinstall the bot.

**Comment by EricDahlvang** [comment]
Hi @spacether 

This is a known issue with **Skype for Business** bots (preview).  This comment explains the issue in detail: https://github.com/Microsoft/BotBuilder/issues/4647#issuecomment-397411409
