### ISSUE TITLE
Fetch unique encrypted user Id for MS Teams without user interacting with bot

### ISSUE THREAD

**Issue by savi-ganesh** [Microsoft/BotBuilder#4992]
## Bot should be able to send a proactive notification to users present in my active directory.
How do I get unique encrypted user ID of a user who is present in my active directory without the user having to send a message to bot or how can I construct the unique user id using active directory's object id and app id of bot (was encryption algorithm is used).**.

## 
* REST API
* Active Channels: MS Teams.
* Deployment Environment: Azure Bot Service
## Issue Description

Availability of RESt API to get teams specific user id
Bot should be able to send a proactive notification to users present in my active directory.
How do I get unique encrypted user ID of a user who is present in my active directory without the user having to send a message to bot or how can I construct the unique user id using active directory's object id and app id of bot (was encryption algorithm is used)

**Comment by stevkan** [comment]
Issue #[4339](https://github.com/Microsoft/BotBuilder/issues/4339) provides information that is directly relevant to your question. You can find additional information around starting personal conversations [here](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bot-conversations/bots-conv-proactive#starting-personal-conversations).
