### ISSUE TITLE
Using Form Flow with SDK v-4 in .Net Core

### ISSUE THREAD

**Issue by Souvik04** [Microsoft/BotBuilder#4993]
## Bot Info
* SDK Platform: .Net Core 2.0
* SDK Version: 4
* Active Channels: DirectLine, Skype, Cortana
* Deployment Environment: Azure

## Issue Description
I am unable to use FormFlow in SDK v-4. FormFlow seems to be now part of `Microsoft.Bot.Builder.Classic` which is a .Net 4.6.1 library for SDK v-4. However, as per this link- https://github.com/Microsoft/botbuilder-dotnet/wiki/Using-Classic-V3-Dialogs-with-V4-SDK it is not supported in .Net Core.
I posted this issue on below link. The solution provided here did not work and the issue is now closed.
https://github.com/MicrosoftDocs/bot-docs/issues/227
I have also raised this on Stackoverflow- https://stackoverflow.com/questions/51963724/using-formflow-dialog-in-bot-framework
but haven't got any response yet. Any help with this please?

**Update-1**

I got the exception details. `System.Runtime.Serialization.SerializationException: Type 'System.RuntimeType' in Assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' is not marked as serializable.`. Although my HelpForm class is marked with `Serializable`.

Also, looking at the metadata for FormFlow class it is not marked with `Serializable` attribute.

![image](https://user-images.githubusercontent.com/17876015/44719415-dd7aaa00-aae0-11e8-929f-36994eee2dcc.png)

## Code Example

Form implementation:
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Bot.Builder.Dialogs;
using Microsoft.Bot.Builder.Classic.FormFlow;

namespace BotFrameworkDev.Forms
{
    [Serializable]
    public class HelpForm
    {
        public string FullName { get; set; }
        public string EmailID { get; set; }
        public string Question { get; set; }
        public DateTime BestTimeToContact { get; set; }
        public List<Priority> Priority { get; set; }
        public static IForm<HelpForm> BuildForm()
        {
            return new FormBuilder<HelpForm>()
                .Message("Please fill out the details as prompted.")
                .Build();
        }
    }

    public enum Priority
    {
        Low,
        Medium,
        High
    }
}
```
Calling the FormFlow within the `OnTurn` of Bot class:
```
public async Task OnTurn(ITurnContext context)
{
	if (context.Activity.Type == ActivityTypes.ConversationUpdate)
	{
		//some code
	}
	else if (context.Activity.Type == ActivityTypes.Message)
	{
		await Microsoft.Bot.Builder.Classic.Dialogs.Conversation.SendAsync(context, () => FormDialog.FromForm(HelpForm.BuildForm));
	}
}
```

## Reproduction Steps
1. Run the code in Visual Studio
2. Use Bot Framework emulator to test

## Expected Behavior
Get the Form Flow prompts from the bot in the chat window.

## Actual Results

"Sorry, my bot code is having an issue" in the chat window.

**Comment by jwiley84** [comment]
Investigating!

**Comment by Souvik04** [comment]
@jwiley84 I tried using the Waterfall steps dialog to achieve something similar but it needs some tweaks and tricks to make it work similar to Form Flow dialog. Any update yet?

**Comment by jwiley84** [comment]
Hi @Souvik04! I'm waiting for word from one of my coworkers this morning! I should have an update NLT this afternoon!

**Comment by Souvik04** [comment]
@jwiley84 Ok, thanks.

**Comment by Souvik04** [comment]
@jwiley84 I have added some more details into my original StackOverflow post- https://stackoverflow.com/questions/51963724/using-formflow-dialog-in-bot-framework. Would you be able to take a look please? Thanks!

**Comment by jwiley84** [comment]
Hi @Souvik04!
My coworkers are still working on a workaround/ making .Classic work with ASP.Net Core.

**Comment by tomlm** [comment]
You can't use classic in Asp.NET core.

**Comment by Souvik04** [comment]
@tomlm What would be the alternate solution for using the Form flow dialog?

**Comment by Unders0n** [comment]
any updates? no formflow in v4?

**Comment by EricDahlvang** [comment]
The Bot Builder Community has released a FormFlow implementation for V4: https://www.nuget.org/packages/Bot.Builder.Community.Dialogs.FormFlow/  with source here: https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/blob/master/libraries/Bot.Builder.Community.Dialogs.FormFlow/README.md
