### ISSUE TITLE
Bot gets stuck in OAuthCard dialog

### ISSUE THREAD

**Issue by mandreab** [Microsoft/BotBuilder#4997]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.15.3
* Active Channels: Direct Line
* Deployment Environment: Azure App Service

## Issue Description
I am trying to switch my bot's authentication to the new OAuthCard flow, following [this](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-authentication?view=azure-bot-service-3.0). 

I am presented with the OAuth card and when I click Sign In, it redirects me to the login page. After entering my credentials, this tab closes and my bot just sits there. If I try to type any commands, I get a 504 timeout. If I refresh the page and type the command to kick off the OAuth card, it recognizes that I am already signed in, so I know it is getting the correct token.

An F12 trace doesn't show any errors (apart from the 504 timeouts after coming back from authentication) and Fiddler also doesn't show any errors that I could see. It seems as though the OAuth process is stuck in a dialog.

## Code Example
I launch my bot using a token because the OAuth card would still prompt for a magic number when launching using a secret:
```
var link = '';
if (refreshToken) {
	link = '/Bot/RefreshToken?token=-1';
	link = link.replace("-1", tokenVal);
}
else {
	link = '/Bot/GetToken';
}
$.ajax({
	url: link,
	success: function (result) {
		$("#botToken script").html("");
		tokenVal = result;
		$("#botToken script").html("BotChat.App({ directLine: { token: tokenVal }, user: { id: userid }, resize: 'detect' }, document.getElementById('botDiv'));");
	},
	error: function (result) { }
});
```
Below is how I call the OAuth dialog. The ListMe function just has a simple context.PostAsync which never gets printed to the screen. This makes me think that the OAuth flow is not returning properly.

`context.Call(await CreateGetTokenDialog(), ListMe);`
```
private static async Task<GetTokenDialog> CreateGetTokenDialog()
{
     return new GetTokenDialog(
     ConfigurationManager.AppSettings["ConnectionName"],
     $"Please sign in to {ConfigurationManager.AppSettings["ConnectionName"]} to proceed.",
     "Sign In",
     1,
     "Hmm. Something went wrong, let's try again.");
}
```
```
private static async Task ListMe(IDialogContext context, IAwaitable<GetTokenResponse> tokenResponse)
{
     var token = await tokenResponse;
     await context.PostAsync("Signed In");         
}
```
## Expected Behavior
After authenticating, the dialog should return to the bot and continue where it left off.

## Actual Results
The bot does not continue, and any subsequent messages to the bot result in a timeout:
![image](https://user-images.githubusercontent.com/14082853/44547000-4fb54e00-a6df-11e8-947d-976329e1b047.png)
![image](https://user-images.githubusercontent.com/14082853/44546628-20eaa800-a6de-11e8-940e-306d8644faaa.png)
 If I refresh the page and type the command to kick off the OAuth card, it recognizes that I am already signed in and prints the message contained in my ListMe function

**Comment by JasonSowers** [comment]
Hi @mandreab Thanks for reporting this, we are looking into this.

**Comment by Jeffders** [comment]
When there is no magic code (such as using the Emulator or when configured for WebChat), the token comes back as an Activity with type Event. Look in this sample (in the MessageController): 

https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Samples/AadV2Bot/Controllers/MessagesController.cs

If you look at lines 57-64, you see that EventActivities need to be passed back into the Dialog stack for the GetTokenDialog to finish. You can set a breakpoint where messages first come into your bot (in the MessageController) and see if this breakpoint is hit.

**Comment by mandreab** [comment]
@Jeffders Sorry for not including that in my code samples. I do have that exact same code (lines 57-64) in my MessageController. My code never breaks there. In fact, I put a breakpoint at the very start of my MessageController and it never hits it. So as far as I can tell, once I hit the sign in button, it never returns back to the MessageController.

**Comment by JasonSowers** [comment]
When you say the breakpoint never gets hit, do you mean actually **never** gets hit or do you mean that you are not seeing the event activity returned?

**Comment by mandreab** [comment]
Hi @JasonSowers After I hit the signin button, nothing comes back to the MessageController.

**Comment by mandreab** [comment]
I did some more digging and it appears to be a bug with using Azure SQL for state storage. If using Azure SQL, it won't ever return to the MessageController. If I change my bot to use Azure table storage instead, it will return with the token event activity.

However, even with using table storage, it still failed when forwarding to my root dialog. It wouldn't go anywhere, it would just fail with the "Sorry, my bot code is having an issue" error. I switched my controller with the one from the AADv2Bot example, and it started working. The only change I've made to the MessageController is adding this piece of code, taken from [here](https://github.com/Microsoft/BotBuilder/issues/2401#issuecomment-284793713):
```
if (activity.Type == ActivityTypes.ConversationUpdate)
{
     ConversationUpdateActivity update = activity;
     var client = new ConnectorClient(new Uri(activity.ServiceUrl), new MicrosoftAppCredentials());
     if (update.MembersAdded != null && update.MembersAdded.Any())
     {
           foreach (var newMember in update.MembersAdded)
           {
                 if (newMember.Id == activity.Recipient.Id)
                {
                    // display specific messages on launch
                }
            }
     }
}
```
I've removed these lines and instead launch the messages via js in my default.html, which resolves that issue:
```
<script>
// bot launch code

// display messages on bot launch
	botConnection
		.postActivity({
			from: user,
			name: 'WelcomeMessage',
			type: 'event',
			value: ''
		})
		.subscribe(function (id) {
			console.log('"trigger WelcomeMessage" sent');
		});
</script>
```
So it looks like the remaining issue is why it won't return back to the MessageController when using Azure SQL for state storage.

**Comment by JasonSowers** [comment]
Let me try to plug in SQL as my state store and see what behavior I get this afternoon. Can you try another channel using SQL and see if the issue persists in skype or something. With or without the magic code (depending on channel)

**Comment by JasonSowers** [comment]
I am not seeing the same behavior as you, I am able to use SQL data store for state and it works well.  If you are able to get me a reproduction project I will be happy to help troubleshoot it with you.

**Comment by mandreab** [comment]
Unfortunately, I am unable to share my code. After discussing this with my team, we switched to using table storage and haven't run into any issues since.
