### ISSUE TITLE
Dialog prompt button can't be clicked sometimes

### ISSUE THREAD

**Issue by rjgmail88** [Microsoft/BotBuilder#4999]
## Bot Info
* SDK Platform:Node.js
* SDK Version: V3
* Active Channels: MS Teams
* Deployment Environment:  Azure App Service

## Issue Description
There's a weird bug when a dialogue box pops up and user tries to click a button on the prompts which doesn't work. We have to type the button text in the text box. 

## Code Example
```
builder.Prompts.choice(session, "Which color?", "red|green|blue", { listStyle: builder.ListStyle.button });
```

## Reproduction Steps
Build a prompt using in v3 bot having ms teams channel.  [https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-dialog-prompt?view=azure-bot-service-3.0#promptschoice](https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-dialog-prompt?view=azure-bot-service-3.0#promptschoice)

## Expected Behavior
If there is choice prompt button then it should be clickable 100% times.  

## Actual Results
Sometime click is not recognized.

**Comment by nyxsys** [comment]
How often is this reproducible and can you provide more specific circumstances under which it occurs? Is there anything you can do that seems to increase the chances of it occurring?

**Comment by nyxsys** [comment]
Without further updates, this will be closed soon.

**Comment by nyxsys** [comment]
Closing this one, please open another issue with more reproduction steps if you continue to see this issue and would like to follow up later on.
