### ISSUE TITLE
ResourceArea: Failed to ping bot endpoint, results to Bad Gateway 502

### ISSUE THREAD

**Issue by gtabasa1012** [Microsoft/BotBuilder#5009]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.15
* Active Channels: Web
* Deployment Environment: 
Deployed on Azure , Premium plan

## Issue Description
For some reason, I cannot get the bot response to me, this is just the basic bot, one that comes from template of VS bot builder. But it's giving me the error of bad gateway 502.

## Code Example
can't identify the issue coz it runs perfectly on emulator on locahost

## Reproduction Steps
1. Use bot template
2. build and deploy to azure
3. test using web channel on azure

## Expected Behavior
Coudn't send retry error

## Actual Results
When I created the resources, I picked Web Api on "Web" category and "bot registration" on bot category

**Comment by nyxsys** [comment]
With regard to "bot registration" do you mean that you created two different azure resources, a webapp and a bot registration channel, or did you create a single bot app?

**Comment by nyxsys** [comment]
Please provide more details, otherwise this issue will be closed.

**Comment by gtabasa1012** [comment]
Yes both this issue has been resolved

**Comment by nyxsys** [comment]
That's good, closing this issue then.
