### ISSUE TITLE
FB Messenger on Android 3 replies on domain name text

### ISSUE THREAD

**Issue by Zhashkha** [Microsoft/BotBuilder#5011]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.16.0
* Active Channels: Facebook
* Deployment Environment: Azure Bot Service, Azure App Service

## Issue Description
When I enter text on Andriod that matches any domain name [anydomain.com] all bots across the globe reply with 3 same message. That's happening only on Facebook Android, Desktop is fine. Can you provide me any info on that ?

**Comment by EricDahlvang** [comment]
Hi @Zhashkha 

Please share the relevant code for the bot.  

What do you mean by "all bots across the globe reply with 3 same message"?

**Comment by EricDahlvang** [comment]
Fascinating.  Thanks for bringing this to our attention.  My guess is that this bug is somehow on the Android Facebook Messenger side.  Have you filed an issue with Facebook?

**Comment by Zhashkha** [comment]
I'll report bug to Facebook and comment their answer here. Thanks for advice.

**Comment by Zhashkha** [comment]
No response. May I ask you to try with Facebook ? (Sorry, for 7 days delay)
