### ISSUE TITLE
Json FormFlow Template questions

### ISSUE THREAD

**Issue by manu4rhyme** [Microsoft/BotBuilder#502]
I'm building a Json FormFlow , for a field I have this template defined in the schema,

```
"Templates": {
        "NotUnderstood": {
          "Patterns": [ "Please enter a valid choice !" ]
        },
        "Feedback": {
          "Patterns": [ "You selected {field}." ],          
          "FeedbackOptions" : "Always"
        }
}

```
I want to always get the feedback for this field. I still get the feedback only when a mismatch occurs.
How do I set it to always?

Also, regarding the DateTime attribute, 
```

"date": {
      "Prompt": { "Patterns": [ "What is your {&} ?" ] },
      "Templates": {
          "NotUnderstood": {
            "Patterns": [ "Please enter a valid Date !" ]
          }
        },
      "type": [
        "string",
        "null"
      ],
      "DateTime": true
    },
```
This accepts even values like "200", and considers it like "current Date 2:00", I really don't want the time, just the date...I saw a TemplateUsage.DateTime to change how datetime is asked...but not sure how to use it...
how do I accept only a date?

**Comment by chrimc62** [comment]
Two things to get feedback:
1) It is controlled off the Prompt (or Template if no Prompt is specified) which is where you need the attribute.
2) The attribute is "Feedback", i.e. "Feedback":"Always" on your Prompt or Template.

For the second issue, you need to add validation to your field which can check and transform the value.  In the current release you can only do that through code, i.e. .Field(schema, "date", null, async (state, value) => { var result = new ValidateResult(); ... ; return result;}. However the next release (hopefully today) will let you do this by putting the code in your JSON file.
