### ISSUE TITLE
[Skype for Business] Abnormally continuing numbering from two different text groups

### ISSUE THREAD

**Issue by joemar53** [Microsoft/BotBuilder#5021]
## Bot Info
* SDK Platform:  .NET
* SDK Version:  Not Sure
* Active Channels:  Skype For Business
* Deployment Environment:  Skype for Business

## Issue Description

Skype for Business continuing the numbering from two different set of text.

## Code Example

The actual string
```
Method 1: Using the Report Editor \n1. From your Power BI workspace, select Get Data > Samples > Retail Analysis Sample > Connect.\n2. The dashboard contains an area chart tile for \"Last Year Sales and This Year Sales.\"Select
 this tile.\n' If this tile was created with Q&A, selecting the tile will open Q&A.\n' But this tile was created in a report, so the report opens to the page that contains this visualization.\n3. Open the report in Editing View by selecting Edit Report. If
 you are not an owner of a report, you will not have the option to open the report in Editing view.\n4. Select the area chart and review the settings in the Fields pane. The report creator built this chart by selecting these 3 values (Time > FiscalMonth, Sales
 > This Year Sales, Sales >Last Year Sales >Value) and organizing them in the Axis and Valueswells.\n\nMethod 2: Using Q & A\n1. Navigate back to the Retail Analysis Sample dashboard.\n2. Using natural language, type something like this into the question box:\nwhat
 were this year sales and last year sales by month as area chart\nAs you type your question, Q&A picks the best visualization to display your answer; and the visualization changes dynamically as you modify the question. Also, Q&A helps you format your question
 with suggestions, auto-complete, and spelling corrections.\nWhen you finish typing your question, the result is the exact same chart that we saw in the report. But creating it this way was much faster!\n3. Similar to working with reports, within Q&A you have
 access to the Visualizations, Filters and Fields panes. Open these panes to further explore and modify your visual.\n4. To pin the chart to your dashboard, select the pin icon.
```

## Expected Behavior

Taken from other channel but want to make it look like this
![test](https://user-images.githubusercontent.com/22390815/44842332-231dab00-ac78-11e8-8224-9b9f47cbcf75.png)

## Actual Results

![capture](https://user-images.githubusercontent.com/22390815/44842187-c9b57c00-ac77-11e8-8ff5-161a8c7479e0.PNG)

**Comment by EricDahlvang** [comment]
Hi @joemar53 

Which Skype for Business client are you using?

Note: Skype for Business bots are currently in preview.  Edge case issues like this are currently not a high priority for their team.  I've labeled this as a bug, but it is not likely to be addressed soon (see https://github.com/Microsoft/BotBuilder/issues/3808 for reference).

Something you could do as a workaround is to just send two separate messages if the channel is Skype for Business.

**Comment by johnataylor** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
