### ISSUE TITLE
Bot does not respond in Teams Free but works in Teams (paid service)

### ISSUE THREAD

**Issue by desflan** [Microsoft/BotBuilder#5022]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.16.0.38344
* Active Channels: MS Teams (paid & free), Skype
* Deployment Environment:  Azure Bot Service
* Bot name: blueybot
* App ID: 86a089d9-add4-4b71-9466-afb23474ccec

## Issue Description
My simple bot receives messages & replies with text. I have published it to Microsoft Teams (paid service) & Microsoft Teams FREE using the "upload a custom app" link. The scope in manifest.json is both "team" and "personal".   

In Teams FREE - When I send a message to the bot in a team using @mention, it does not reply. 
In Teams FREE -When I send a message to the bot in a personal 1:1 chat, it does not reply. This had worked a few hours ago, with no app changes made since. 

In Microsoft Teams (paid service) the bot works perfectly in both a team channel & 1:1 personal chat.
In Skype, the bot works perfectly also.

The same Manifest.json was upload to Teams FREE and Teams (paid service).

In Azure Portal Bot Channel Registration, no issues are reported for Microsoft Teams channel.

## Code Example
No code to share. Regular code that compiles and runs fine in Skype and paid version of MS Teams

## Reproduction Steps
1.
2.
3.

## Expected Behavior
In Microsoft Teams FREE I expected to receive replies from the bot in both a team channel & 1:1 chat

## Actual Results
In Microsoft Teams FREE there are no message received from the bot in a team channel or a 1:1 chat.
Tried remote debugging using VS and no message received by the bot.

**Comment by jwiley84** [comment]
investigating!

**Comment by jwiley84** [comment]
Hi @desflan! I'm trying to reproduce this, however, currently I only have access to the PAID Teams. It was the version of Teams I connected to when I connected my bot to the Teams channel. How are you connecting your bot to the FREE channel? And how are you building the bot, on the Teams Studio App?

**Comment by desflan** [comment]
I published it to Teams FREE through the "upload a custom app" link.  I built the manifest.json using Teams App Studio.

Thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by desflan** [comment]
Hi @jwiley84 would you have any update on this? Thanks!

**Comment by desflan** [comment]
Hi team, any update on this issue?

**Comment by jwiley84** [comment]
Hi @desflan! I'm still working on this! No worries, you haven't been forgotten!

**Comment by jwiley84** [comment]
@desflan: what error (if any) shows on the developer console when you try to start a conversation in Free with your bot?

**Comment by desflan** [comment]
Hi @jwiley84 I set up the messaging endpoint on Free in the same way I set it up for the Paid service - I turned on the Teams channel in Azure Portal Bot Registration, and set the bot's endpoint to the usual /api/messages . 
There are no developer console errors showing when I try to start a conversation on Free, Application Insights show that no request is received by the Bot when I try to start a conversation on Free.
Thank you.

**Comment by desflan** [comment]
Hi @jwiley84 did you get any feedback from the MS Teams team on this issue?

**Comment by johnataylor** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
