### ISSUE TITLE
How to structure my Bot Conversation

### ISSUE THREAD

**Issue by dkonyayev** [Microsoft/BotBuilder#5027]
## Bot Info
* SDK Platform: .NET
* SDK Version: Microsoft.Bot.Builder 3.5.9
* Active Channels: Skype for Business, Webchat 
* Deployment Environment: Hosted on enterprise server with internet access

## Issue Description
This is not an issue but looking for guidance. I have a scenario that deals with Personal Time Off (PTO). We have 4 user cases
* Employee trying to check their available PTO
* Employee trying to ask a question about PTO against QnA 1
* Manager approving a PTO request for a subordinate
* Manager trying to ask a question about PTO for subordinates against QnA 2

How do I structure my conversion so that I know what dialog to invoke depending on request? The intents are different but utterances are very similar.

## Code Example
n/a

## Reproduction Steps
n/a

**Comment by Kartik1607** [comment]
I think your bot would be used in a private environment. One solution approach is bot can ask user for employee code etc, and then fetch user's data including operation user can perform. (For ex for managers it would be viewing and approving PTO) 

The bot can then guide the user accordingly.

**Comment by stevkan** [comment]
Hi @dkonyayev, are you still needing guidance on this or has a solution been found?
