### ISSUE TITLE
ConversationUpdate is not working well the first time after deploying in MS Teams

### ISSUE THREAD

**Issue by xiaolangxyz** [Microsoft/BotBuilder#5028]
## Bot Info
* SDK Platform: .NET 
* SDK Version: SDK3
* Active Channels:  MS Teams
* Deployment Environment:  Azure App Service

## Issue Description
In MS Teams, using the code below, "This is what I want" will be showed when a new member is added in to group chat which has already added a bot.
basically It works. 
But it doesn't  the first time to add a member after deploying. Is it a correct?

By the way, **any suggestions about sending existing users a message when a bot is added?**

## Code Example

    ```
    /// <summary>
        /// POST: api/Messages
        /// Receive a message from a user and reply to it
        /// </summary>
        public async Task<HttpResponseMessage> Post([FromBody]Activity activity)
        {
            if (activity.Type == ActivityTypes.Message)
            {
                await Conversation.SendAsync(activity, () => new RootDialog());
                
            }
            else if (activity.Type == ActivityTypes.Invoke) // Received an invoke
            {
                // Handle ComposeExtension query
                if (activity.IsComposeExtensionQuery())
                {
                    var invokeResponse = this.GetComposeExtensionResponse(activity);
                    return Request.CreateResponse<ComposeExtensionResponse>(HttpStatusCode.OK, invokeResponse);
                }
                else
                {
                    // Handle other types of invoke
                    return Request.CreateResponse(HttpStatusCode.OK);
                }
            }
            else
            {
                 HandleSystemMessage(activity);
            }
            var response = Request.CreateResponse(HttpStatusCode.OK);
            return response;
        }

        private  Activity HandleSystemMessage(Activity message)
        {
            if (message.Type == ActivityTypes.DeleteUserData)
            {
                // Implement user deletion here
                // If we handle user deletion, return a real message
            }
            else if (message.Type == ActivityTypes.ConversationUpdate)
            {
                // Handle conversation state changes, like members being added and removed
                // Use Activity.MembersAdded and Activity.MembersRemoved and Activity.Action for info
                // Not available in all channels

                bool addedBot = false;
                Activity newMessage = new Activity();
                string res = "";
                for (int i = 0; i < message.MembersAdded.Count; i++)
                {
                    if (message.MembersAdded[i].Id == message.Recipient.Id)
                    {
                        addedBot = true;
                        break;
                    }
                }

                if (message.MembersAdded.Count > 0 && addedBot == false)
                {

                    ConnectorClient connector = new ConnectorClient(new Uri(message.ServiceUrl));
                    Activity reply = message.CreateReply("This is what I want");
                    connector.Conversations.ReplyToActivityAsync(reply);

                }

            }
            else if (message.Type == ActivityTypes.ContactRelationUpdate)
            {
                // Handle add/remove from contact lists
                // Activity.From + Activity.Action represent what happened
            }
            else if (message.Type == ActivityTypes.Typing)
            {
                // Handle knowing tha the user is typing
            }
            //else if (message.Type == ActivityTypes.Ping)
            //{
            //}

            return null;
        }

```

**Comment by corinagum** [comment]
What you are looking to implement is called proactive messaging, which is available on Microsoft Teams bots. Another term is "Welcome message". One caveat for sending these messages is that you need the user's unique ID and tenant ID to send a proactive message.
 
You can peruse [this link to learn more about proactive messages](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-proactive-messages?view=azure-bot-service-3.0).
 
More specifically, this [link is a tutorial on proactive messaging for Microsoft Teams bots.](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bot-conversations/bots-conv-proactive#creating-a-channel-conversation) This includes individual welcome messages and channels messages.
         
            //Set the Last Dialog in Conversation Data
            context.UserData.SetValue(Strings.LastDialogKey, Strings.LastDialogSend1on1Dialog);`
 
            var userId = context.Activity.From.Id;
            var botId = context.Activity.Recipient.Id;
            var botName = context.Activity.Recipient.Name;
 
            var channelData = context.Activity.GetChannelData<TeamsChannelData>();
            var connectorClient = new ConnectorClient(new Uri(context.Activity.ServiceUrl));
 
            var parameters = new ConversationParameters
            {
                Bot = new ChannelAccount(botId, botName),
                Members = new ChannelAccount[] { new ChannelAccount(userId) },
                ChannelData = new TeamsChannelData
                {
                    Tenant = channelData.Tenant
                }
            };
 
            var conversationResource = await connectorClient.Conversations.CreateConversationAsync(parameters);
 
            var message = Activity.CreateMessageActivity();
            message.From = new ChannelAccount(botId, botName);
            message.Conversation = new ConversationAccount(id: conversationResource.Id.ToString());
            message.Text = Strings.Send1on1Prompt;
 
            await connectorClient.Conversations.SendToConversationAsync((Activity)message);`
 
 
 
Is this right? https://github.com/Microsoft/BotBuilder/issues/5028 Should I respond and close?
