### ISSUE TITLE
.matches method always send to OnDefault

### ISSUE THREAD

**Issue by NTruchaud** [Microsoft/BotBuilder#503]
Hi, I've got the feeling that I can't make the .matches method work well.
I have something like :

```
helloBot.add('/', new builder.CommandDialog()
    // .matches('^set name', builder.DialogAction.send('Hi !'))
    .matches('^name', function(session, results) {
        console.log("I'm in.");
        if (results && results.response) {
            session.send(results.response);
        } else {
            session.beginDialog('/profile');
        }
    })
    // .matches('^quit', builder.DialogAction.endDialog())
    // .matches('^what is the best IDE', builder.DialogAction.beginDialog('/sourcelair'))
    .onDefault([
        function (session, args, next) {
            console.log("In the default");
            if (!session.userData.name) {
                session.beginDialog('/profile');
            } else {
                session.endDialog("Je n'ai pas compris :/");
            }
        },
        function (session, results) {
            session.send('Hello %s!', session.userData.name);
        }
    ]));
```
I don't know if the problem is from my .matches method or the cycle of beginDialog / endDialog.
Thank you !

**Comment by brene** [comment]
Maybe, it would be great, if you could describe your issue a little bit more? It would be great if you could upload your example output of what happens when you enter your desired input and what the expected output is.
Can you also check if this problem, that I described here #532 is the same as yours? If, so we should link it.

**Comment by NTruchaud** [comment]
I'm sorry, that's just my bad, I'm making a bot in French and I had not to check the translate checkbox on the Microsoft website.

Thanks for your answer anyway.
