### ISSUE TITLE
[Question] Tabs on Bot MS Teams (1vs1)

### ISSUE THREAD

**Issue by andregouveia8** [Microsoft/BotBuilder#5030]
Hello everyone, i need some help to resolve one problem.

Im creating a bot to MS Teams and it work very well.
Now i need to put tabs on my bot. Im using static tabs on manifest.json.

So, in some cases the tabs works  fine, but in case of some websites the tab does not render.

Anyone know something about that? Script problems? Security problems?

Thank You Guys!

**Comment by jwiley84** [comment]
Hi @andregouveia8!

Things sometimes render differently on different channels. This question would be better answered on the BotBuilder-Teams repo [here](https://github.com/OfficeDev/BotBuilder-MicrosoftTeams).

**Comment by andregouveia8** [comment]
Thanks @jwiley84 !

I can see the problem [here](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/tabs/tabs-requirements). :)

Close Issue.
