### ISSUE TITLE
session.say() function array input for speak not working

### ISSUE THREAD

**Issue by kepy97** [Microsoft/BotBuilder#5042]
`session.say(['hello','hey'],['Which work order did you want to close?']);`
**When I execute above line it did not work with array input for speak.
I have attached output screenshot.**
Let me know, How speak element working for taking array element. 
![untitled](https://user-images.githubusercontent.com/20126840/45222774-0534f380-b2d3-11e8-95ac-b0f7996d1720.png)

**Comment by nyxsys** [comment]
`[session.say()](https://docs.botframework.com/en-us/node/builder/chat-reference/classes/_botbuilder_d_.session.html#say)` [does not support an array as input](https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-text-to-speech?view=azure-bot-service-3.0#session-say), just strings for the spoken text and the written text. If you make your selection for which string you would like to use for each before calling the method it should work.
