### ISSUE TITLE
sendTyping not working with Slack

### ISSUE THREAD

**Issue by anvad** [Microsoft/BotBuilder#5043]
## Bot Info
* SDK Platform: Node.js
* SDK Version: 3.14.0
* Active Channels: Slack, WebChat
* Deployment Environment: local development with Emulator
* Production Environment: AWS Lambda

## Issue Description
session.sendTyping() appears to work fine in the emulator and in the test WebChat client provided in the Azure portal.  
However, I do not see the "bot is typing" message in Slack.  

The [Channel Inspector](https://docs.botframework.com/en-us/channel-inspector/channels/Slack?f=Typing&e=example1) shows this is supported.

Looking at Slack documentation, the only way I see to directly send this kind of message is via Slack's RTM API rather than their Events API (which is what we appear to be configuring when setting up Bot Framework to Slack connectivity).

So, at the very least this is a doc bug as it is not clear from the bot framework docs if I need to tweak additional settings in Slack.

## Code Example
I used two variants
### Variation 1
```javascript
bot.use({
    botbuilder: [(session, next) => {
        session.sendTyping();
        next();
    }]
})
```
> This first variation sometimes won't show the "typing" indicator even in the WebChat since we send the "typing" activity after we load the session and there may not be enough time between sending the "typing" event and the actual message.

### Variation 2
```javascript
bot.use({
    receive: function (event: builder.IEvent, next) {
        interceptIncomingEvents(event, next, bot);
    });

function interceptIncomingEvents(event, next, bot) { // bot is an instance of builder.UniversalBot
	const { address, agent, source } = event;
	const typingIndicator = {
		type: 'typing', address, agent, 
		source, user: address.user,
		sourceEvent: '',
		text: ''
	};
	bot.send(typingIndicator, (err, addresses) => {
		if (err) {
			log(`error sending typing indicator to users at ${JSON.stringify(addresses)}. \n\nError: ${err}`);
		} else {
			log(`sent 'typing' indicator to user`);
		}
	});
} 
```
> This 2nd variation does not wait for the session to be loaded and hence always shows up in the emulator and Test WebChat client in azure portal but still, never in Slack.

## Reproduction Steps
1. Create a basic echo bot in NodeJS and save it in the variable `bot`. In my case, the bot is making a call to LUIS API for NLP and that introduces a delay, but this delay could be simulated with a setTimeout before bot's reply is sent back to slack.
2. Use either of the above variations of code to register middleware to the bot.
3. create a slack app following instructions from [here](https://docs.microsoft.com/en-us/bot-framework/bot-service-channel-connect-slack)
3. In azure, register the slack channel
4. send a message from Slack desktop client app to the bot.
5. Slack desktop client app never shows the "bot is typing" message

## Expected Behavior
I expected to see a "Bot is typing" message show up in the Slack desktop client (see <mark>highlighted</mark> portion at the bottom of the screenshot), while waiting for bot's reply.
![image](https://user-images.githubusercontent.com/1834582/45256635-38689880-b34e-11e8-8e61-e96f9c5ffaa5.png)

## Actual Results
I don't see "bot is typing" in the <mark>highlighted</mark> area (see screenshot below).
![image](https://user-images.githubusercontent.com/1834582/45256669-8ed5d700-b34e-11e8-9786-baf40fef6142.png)

**Comment by sgellock** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
