### ISSUE TITLE
exportBotStateData's result is null

### ISSUE THREAD

**Issue by areckkimo** [Microsoft/BotBuilder#5044]
## Bot Info
* SDK Platform: Node.js
* SDK Version: 3.13.1
* Active Channels: Facebook
* Deployment Environment: Azure Bot Service
* Bot Type: Function Bot

## Issue Description
I want to export data of Bot Framework State Service with exportBotStateData method to own state storage. But return result is null

## Code Example
```
var useEmulator = (process.env.NODE_ENV == 'development');

var connector = useEmulator ? new builder.ChatConnector() : new botbuilder_azure.BotServiceConnector({
    appId: process.env['MicrosoftAppId'],
    appPassword: process.env['MicrosoftAppPassword'],
    openIdMetadata: process.env['BotOpenIdMetadata']
});
connector.exportBotStateData("https://facebook.botframework.com/","facebook","123",function(error, results){
    var options = {
        method: "GET",
        url: "http://xxx.xxx.xxx.xx:1035/get",
        qs:{results:JSON.stringify(results)}
    }
    request(options,function (error, response, body){

    })
})

var bot = new builder.UniversalBot(connector);

//bot dialog ...

if (useEmulator) {
    var restify = require('restify');
    var server = restify.createServer();
    server.listen(3978, function() {
        console.log('test bot endpont at http://localhost:3978/api/messages');
    });
    server.post('/api/messages', connector.listen());    
} else {
    module.exports = connector.listen();
}
```

**Comment by jwiley84** [comment]
What is your end goal? Are you trying to save general state data to storage such as CosmosDB or Azure table? Additionally, I don't think https://facebook.botframework.com/ is an actual site for using for state storage.

**Comment by areckkimo** [comment]
> What is your end goal? Are you trying to save general state data to storage such as CosmosDB or Azure table? Additionally, I don't think https://facebook.botframework.com/ is an actual site for using for state storage.

Because of Bot state service will be retired.
I will export old user data on Bot state service
https://facebook.botframework.com/ from the address.serviceUrl
I referred SDK document
it says that
```
/**
     * Exports bot state data persisted for a given channel.
     * @param serviceUrl The service url for the channel being queried. This can be found in the `address.serviceUrl` for a message sent to the bot.
     * @param channelId ID of the channel being exported. This can be found in the `address.channelId` for a message sent to the bot.
     * @param continuationToken The continuation token for the next page of results to fetch.  This should be `undefined` for the first page requested.
     * @param done Callback to recieve the next page of results.
     */
    exportBotStateData(serviceUrl: string, channelId: string, continuationToken: string|undefined, done: (err: Error, results: IBotStateDataResult) => void): void;

```

**Comment by jwiley84** [comment]
Hi @areckkimo! just wanted to let you know i'm still working on this.

**Comment by sgellock** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
