### ISSUE TITLE
QnA Maker - Support for password protected websites

### ISSUE THREAD

**Issue by jamessmith81** [Microsoft/BotBuilder#5045]
## Bot Info
* SDK Platform: https://www.qnamaker.ai/
* SDK Version: https://www.qnamaker.ai/
* Active Channels: https://www.qnamaker.ai/
* Deployment Environment: Azure Bot Service
## Issue Description
Trying to create a Chat Bot from QnA Maker - https://www.qnamaker.ai/Create. 

FAQ is hosted on extranet but website is protected with username / password (Basic Authentication).

Creation of bot fails with;

Failed to extract QnAs from the source "Website Name" - Unsupported / Invalid url(s). Failed to extract Q&A from the source.

## Code Example
N/A - bot is auto generated.

## Reproduction Steps
1. Point bot to FAQ using - https://www.qnamaker.ai/Create
2.
3.

## Expected Behavior
URL with access to chat bot of be created

## Actual Results
Failed to extract QnAs from the source "Website Name" - Unsupported / Invalid url(s). Failed to extract Q&A from the source

**Comment by corinagum** [comment]
Unfortunately, data protected behind a login is not supported for QnA Maker. I recommend downloading the content manually and uploading that to your app.
