### ISSUE TITLE
Microsoft Bot Integration with Facebook Messanger - Slow network response

### ISSUE THREAD

**Issue by Mike-tech** [Microsoft/BotBuilder#5046]
Hoping someone can help...

We have setup a bot developed with Microsoft Bot Framework, hosted in Azure. This has been connected to Facebook Messenger channel. This is being used for FB Workplace Chat.

When you test the bot in Azure using the "Test in Web Chat" the responses are instantaneous, but when testing in Workplace chat, the communication is really slow. When displaying content with multiple attachments, it's loading one by one  - taking up to a minute for a 32 item collection to load in FB Workplace chat. Whereas in Azure it's loads all at once.

Now the Azure web server is location is in North Europe, while i'm not sure where FB Workplace is hosted, i'm guessing it's in US. Could this be the issue? Would we have to host our Azure service in US to improve performance or is this a configuration settings. If the latter which side is this, Facebook or Azure?

PS: Also for some reason the bot welcome message is not displaying in FB Workplace chat, but welcome message display when you initially connect when testing in emulator and in Azure. Again any reason why this is?

Thanks in advance

**Comment by Mike-tech** [comment]
Apology i forgot to add, i am calling a secure Azure Function which is also in North Europe. This function app is access with a access token and makes a call to Azure AD to retrieve some user profile information. 

Now could this add to the lag in latency?

**Comment by sbui2** [comment]
hi Mike-tech, what version of bot are you using?

**Comment by Mike-tech** [comment]
@sbui2 I'm using version 3.16.1.38846

I'm actually going to close this thread because i setup a replica and hosted all the services and resources in the US, where i believe Workplace is hosted and it made no significant difference. 

The end users seems ok with the performance. I will be looking at ramping up the resources on my App service. Also not sure if using web api rather the function app may improve performance.
