### ISSUE TITLE
How to support multiple credentials (sets of appId & appPassword) in single NodeJS bot service

### ISSUE THREAD

**Issue by bhushanvadgave** [Microsoft/BotBuilder#5047]
## Bot Info
* SDK Platform: NodeJS
* Active Channels: All
* Deployment Environment: Bot service (with NodeJS botbuilder SDK) deployed in our infrastructure

## Requirement Description
We have a bot NodeJS service deployed which exposes /api/messages APIs for bot connector to forward user messages. We want to make the same single deployed bot service to be used for multiple bots registered in Azure portal.

## Expected Behavior
Found a documentation https://blog.botframework.com/2017/11/02/optimizing-latency-bot-framework/ but this has CSharp code examples. Is any way BotBuilder NodeJS SDK provides support for multiple credentials?

**Comment by jwiley84** [comment]
Hi @bhushanvadgave!

There is a tutorial  [here](https://www.microsoft.com/developerblog/2017/01/10/creating-a-single-bot-service-to-support-multiple-bot-applications/) that outlines how to connect multiple bot applications to a single bot service by using unique ids for each bot (in the case of this tutorial, it was customer IDs).

**Comment by jwiley84** [comment]
Duplicate of [Issue 5041](https://github.com/Microsoft/BotBuilder/issues/5041)
