### ISSUE TITLE
Facebook Messenger channel - Welcome message not showing

### ISSUE THREAD

**Issue by Mike-tech** [Microsoft/BotBuilder#5048]
I've developed Microsoft bot framework that seems to work very well in dev and testing in web chat in Azure. When you initially connect to the chat a welcome message is shown.

When using this in Facebook workplace chat, no welcome message is shown. I don't know why this is happening.

This is the method for the welcome message:

` async Task HandleConversationUpdateAsync(ConnectorClient connector, IConversationUpdateActivity activity)

        {
           const string WelcomeMessage = "Welcome to Botland! I can help you to find specific users profile information.\n\n";

            Func<ChannelAccount, bool> isChatbot = channelAcct => channelAcct.Id == activity.Recipient.Id;
            if (activity.MembersAdded.Any(isChatbot))
            {
                Activity reply = (activity as Activity).CreateReply(WelcomeMessage);
                activity.Recipient.Name = "Botland";
                await connector.Conversations.ReplyToActivityAsync(reply);
            }
        }
`

Thanks

**Comment by sbui2** [comment]
I'm struggling with any guide that allow me to send a welcome message whenever user first connect to bot.
Currently, I know that I can check context.activity.type === 'conversationUpdate' to know when the conversation get started but i think that it's not good way to do that purpose.
Thanks.

**Comment by sgellock** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
