### ISSUE TITLE
Facebook Messenger channel support- Creating Rich text/Attachments

### ISSUE THREAD

**Issue by Mike-tech** [Microsoft/BotBuilder#5049]
I'm struggling to find any support for rich text and attachment for Facebook channels. The standard text is boring and I would like to jazz my render text up. I've tried Hero, Adaptive card, Thumbnail Card , Markdown. None of them seems to be supported.

Adaptive card seems to be converted to an image in Workplace chat, and also carousel didn't display properly.

Hero cards and Thumbnail card seems to generate an error when tested on Fb Workplace chat. Looking at the channel inspector page, i can't work out if it is supported or not?
[https://docs.botframework.com/en-us/channel-inspector/channels/Facebook?f=Markdown&e=example1](https://docs.botframework.com/en-us/channel-inspector/channels/Facebook?f=Markdown&e=example1)

When i test all these in emulator, Azure Web chat, they all works no problem. But my end users need this in Workplace Facebook.

Can you please suggest any supported Rich text or attachments that is supported for the Facebook Messenger channel. Sample code would be nice :)

Thanks

**Comment by jwiley84** [comment]
Hi @Mike-tech! Both Hero Cards and Adaptive Cards are supported in the Facebook Messsenger channel. This might be an issue with the channel actually being Facebook Workplace, but I'll ask today.

**Comment by Mike-tech** [comment]
@jwiley84 thanks for your response. You forgot to mention that when using Adaptive Cards, they are rendered as images on Facebook channels - in my case that just slowed things up so much and not acceptable for my use case.

Hero Cards does work - i finally got it working in the last few hours. I was mainly interested in the Text/Subtitle properties, but then in Facebook channel (Workplace chat) there are limits to the number of characters that can be used. So again this was a huge limitation to the current project i'm working on.

I tried to use Receipt Card, which seems to accept lots of text display, this didn't work i kept getting Sorry, my bot code is having an issue. 

It's really annoying finding a solution that fit my needs. I'm having to result to standard text which looks horrible when returning list collection. 

If there is any real solution anyone can suggest then please let me know.

Cheers

**Comment by sgellock** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
