### ISSUE TITLE
Add authentication to bot via Azure bot service

### ISSUE THREAD

**Issue by JasmeetVirdi** [Microsoft/BotBuilder#5053]
I want to authenticate my bot using Azure AD oauthcard,
I m referring the [](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-authentication?view=azure-bot-service-3.0) to configure my bot.
The article ultimately takes you to [](https://github.com/Microsoft/BotBuilder) and using the C# sample AaDV2Bot.But it is said the article is deprecated now. 
I want to use the similar project but i can't find a similar non-deprecated sample.
Any help?
I want a oauth signin card to pop up and the user authentication using Azure AD credentials (in my organization)

**Comment by stevkan** [comment]
Hi @JasmeetVirdi,

Can you clarify whether you are wanting to use C# or Node?

An additional note, the v4 SDK for both languages is currently under preview but is set to go GA in the near future. I would recommend using v4 for your development. You can read more about it [here](https://docs.microsoft.com/en-us/azure/bot-service/?view=azure-bot-service-4.0).

There are samples available, either way.

**Comment by stevkan** [comment]
If this is still an issue, please reopen.
