### ISSUE TITLE
Direct Line not responding despite using Geographic Endpoints

### ISSUE THREAD

**Issue by mutanttech** [Microsoft/BotBuilder#5059]
## Bot Info
* SDK Platform:  .NET
* SDK Version: 3.15.3
* Active Channels: Direct Line
* Deployment Environment:  Azure Bot Service, Azure App Service

## Issue Description
Directline Geographic Endpoint behaving highly inconsistent in responding, I believe it was working fine some time back due to which I made a decision to use it in production, after reading the following article:
[https://blog.botframework.com/2017/02/02/Direct-Line-performance-improvements/](https://blog.botframework.com/2017/02/02/Direct-Line-performance-improvements/)

Currently I am using europe.directline.botframework.com but European users are facing issues, along side India.

Directline is becoming a big hurdle at times for production bots functioning. Please recommend if using the geographic endpoint is okay or we fallback to directline.botframework.com again.

## Code Example
No Code

## Reproduction Steps
1. Open any bot that connects with Direct Line Channel, and see the network calls

## Expected Behavior
Direct line should respond as there is aggressive 15 ms timeout in Bot.

## Actual Results
Directline Europe Endpoint behaving inconsistently.

**Comment by sgellock** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
