### ISSUE TITLE
Operation returned an invalid status code ‘MethodNotAllowed’

### ISSUE THREAD

**Issue by mahathota** [Microsoft/BotBuilder#5066]
Getting this error in web chat. Same code working fine in other app. Only difference to connecting to Cosmos DB. Tried to use the same, but still seeing the same issue.

Event time | 9/20/2018, 12:16:22 PM |  
-- | -- | --
Message | POST to timed out after 15s |  
Exception type | Microsoft.Bot.Schema.BotTimeoutException |  
Failed method | Microsoft.Bot.ChannelConnector.BotAPI+<PostActivityToBotAsync>d__30.MoveNext |

**Comment by nyxsys** [comment]
A few questions,
Can you post some code? 
Which SDK are you using?
Are you adding or removing cosmos DB for state storage?

**Comment by sgellock** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
