### ISSUE TITLE
Bot Framework returning --There was an error sending this message to your bot: HTTP status code InternalServerError

### ISSUE THREAD

**Issue by fj4870** [Microsoft/BotBuilder#5067]
Hi,

I have deployed Chat Bot into window server but since yesterday sometime I am getting following error in Bot “There was an error sending this message to your bot: HTTP status code InternalServerError”.

What does it mean
1)	Messages are not able to reach to the window server.
2)	Messages are reaching to the server and Chat bot is having some issue.
3)	It’s an issue at the Microsoft end

I am using 3.15.3 version (Bot.builder).

Has anyone run into the same problem?

**Comment by JasonSowers** [comment]
The error you are experiencing is a generic error that just lets us know that something went wrong in the bot.  Can you please try to debug locally and get more information.  [Here is a great blog](https://blog.botframework.com/2017/10/19/debug-channel-locally-using-ngrok/) about how to debug locally.

**Comment by sgellock** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
