### ISSUE TITLE
[Direct Line] Microsoft.Bot.Connector.DirectLine silent retrys

### ISSUE THREAD

**Issue by jvolo** [Microsoft/BotBuilder#5068]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.0.2
* Active Channels: Direct Line
* Deployment Environment: Azure Bot Service, Azure App Service

## Issue Description
If the server calculates something which takes longer than 15 seconds the client sends the message again which leads to an unexpected state.

client sends 1 msg and expects 1 answer, but if it takes longer than 15 seconds to answer, the client sends under the hood multiple retrys and at the end the client becomme multiple answers from the server

![multimsgs](https://user-images.githubusercontent.com/43243922/45884820-273f7300-bdb5-11e8-8fce-51876291e1dc.png)

## Code Example
```csharp
Thread.Sleep(60000)
```
this in a dialog code will produce the issue

or just set a break point and wait there

## Reproduction Steps
1. Send msg to bot
2. wait 1 minute till bot sends msgs

## Expected Behavior
if the client sends 1 msgs and bot recieves the msg the client should not send retry msgs

## Actual Results

1 msg from the client answers multiple questions from the bot.

In this screenshot the bot ask if the users has some additional informations.
User answers with "no".
The Bot recieves the no and calculates something which takes a while (longer than 15 seconds)
client sends silently again the "no" to the bot.
Now the bot is finished with calculations and asks the client if he wants to send the ticket.
but because of the silent "no" he takes this as the answer and will not send the ticket.

![multianswers](https://user-images.githubusercontent.com/43243922/45884862-48a05f00-bdb5-11e8-84f5-d1faec0a3bbc.png)

**Comment by corinagum** [comment]
This is related to [Issue 3122](https://github.com/Microsoft/BotBuilder/issues/3122#issuecomment-366387495) and [Issue 4559](https://github.com/Microsoft/BotBuilder/issues/4559#issuecomment-407142186)

May I ask what client you are using?

Unfortunately, the fifteen second timeout cannot be changed, and the recommended solution to this problem is to have the bot acknowledge the activity before sleep. Issue #3122 has a sample that you can use in your bot.

**Comment by Wenish** [comment]
@corinagum its a uwp app.

with the web-chat the bot works fine.

**Comment by jvolo** [comment]
@corinagum its a uwp app

**Comment by EricDahlvang** [comment]
@jvolo If you are using the DirectLineClient, you can setthe retry policy to zero:

```cs
DirectLineClientCredentials creds = new DirectLineClientCredentials(directLineSecret);
DirectLineClient directLineClient = new DirectLineClient(new Uri("https://directline.botframework.com"), creds);
directLineClient.SetRetryPolicy(new Microsoft.Rest.TransientFaultHandling.RetryPolicy(new Microsoft.Rest.TransientFaultHandling.HttpStatusCodeErrorDetectionStrategy(), 0));
```
