### ISSUE TITLE
Error in Bot Framework Directline connector

### ISSUE THREAD

**Issue by hmishra2250** [Microsoft/BotBuilder#507]
My application incurred errors in contacting the Bot through the directline connector. When i checked, i found the following error in the Directline page.
I guess it is associated with the web app of Bot Framework. 
Please look into this.
![screenshot 18](https://cloud.githubusercontent.com/assets/9528717/16218202/6821861a-3798-11e6-97db-58e0115814ac.png)

**Comment by TexAgg** [comment]
I have this same error pop up whenever I debug my bot in visual studio.

**Comment by dandriscoll** [comment]
Yes, we're diagnosing this now.

**Comment by dandriscoll** [comment]
The service should be back now. Sorry for the outage.

**Comment by hmishra2250** [comment]
Yeah its working now, but not through the Jquery code that i wrote earlier. It was working initially with the same piece of code, but now it keeps failing.
It however is hitting the directline link through GET and POST request on Postman.

Image on Postman, working with direct POST:
![screenshot 20](https://cloud.githubusercontent.com/assets/9528717/16226835/e79cdd7c-37ca-11e6-802b-74f14fadb6ee.png)

Screen Shot of C# POST code:
![screenshot 22](https://cloud.githubusercontent.com/assets/9528717/16226850/f4ee52f8-37ca-11e6-905c-749157334259.png)

screen shot of error on web app failing at the same Jquery $.ajax call :
![screenshot 19](https://cloud.githubusercontent.com/assets/9528717/16226858/015d44fe-37cb-11e6-83a7-4d4a0ba1a0ed.png)

**Comment by dandriscoll** [comment]
Taking a look now.

**Comment by dandriscoll** [comment]
I think this is working now. I'm getting a 405 on the OPTIONS request but it's setting the Access-Control-Allow-Origin header now. Can you try again?

**Comment by hmishra2250** [comment]
Yeah, 
It works like a charm now. Thanks for the help Dan !

**Comment by vasilkrastev90** [comment]
I am getting Access-Controll-Allow-Origin errors when trying to connect to DirectLine API at the moment. Is the reason because of the API? Or do I need to look into my client.

**Comment by dandriscoll** [comment]
Hi @vasilkrastev90, are you still seeing errors? If so, can you post a new issue?

**Comment by vasilkrastev90** [comment]
Not so much but to me it looks like the DirectLine API has some issues. Sometimes posting activities fails with 502 or takes too much time for example. And sometimes at certain times of the day may API calls return 502. I am not sure if this is expected as the framework in preview but it definitely happens. I will only open an issue if this is not expected behaviour.

**Comment by dandriscoll** [comment]
Hi @vasilkrastev90, HTTP 502 status codes means your bot generated an error. That's the only situation in which we send a 502. Do you have any internal tracing in your bot that shows what the errors are?

**Comment by vasilkrastev90** [comment]
I am quite sure it was not the bot that generated those errors. But you might be right, I might be mistaken about the error codes. I will put the trace here once I manage to reproduce.

**Comment by dandriscoll** [comment]
Yes, Direct Line is designed to be a 24/7 service. Unfortunately all services are subject to interruption and occasionally we see those, although we do monitor and repair them as quickly as possible.

External factors that could cause problems include any issues in connectivity between the Direct Line datacenter and your datacenter, any hosting issues  on your side, and broad factors like global DDoS attacks.

**Comment by alundiak** [comment]
@dandriscoll I somehow get working version with DirectLineJS, but I faced with 400 bad request, and dont known conversationID. No idea why. 
But in regards to simple connection via `https://smba.trafficmanager.net/apis` I'm doing steps with Auth as described in docs, and I can't fix CORS issue.
Is it true, that I can't use simple AJAX POST/GET request to MS server from localhost http server? Should I deploy to real server like Heroku or Azure and make server--server requests? As it's described/explained here https://stackoverflow.com/a/38318068
