### ISSUE TITLE
Microsoft bot framework doesn't support Facebook handover protocol

### ISSUE THREAD

**Issue by Nada-Abdelkader** [Microsoft/BotBuilder#5070]
## Bot Info
* SDK Platform: .NET
* SDK Version: v3
* Active Channels: Facebook
* Deployment Environment: Azure Bot Service

## Issue Description
To pass the thread control, I can call the HTTP request from the bot builder code (However, I don't know how to get the recipient ID (PSID)) but the part i am stuck in is the other way, How can i handle it when the secondary receiver passes the thread control back to the bot connector as the primary receiver to be able to start the conversation with the bot again?

**Comment by jwiley84** [comment]
investigating.

**Comment by jwiley84** [comment]
This is on the list of feature to be explored for the facebook channel. Please see reference github issue. #4360

**Comment by jwiley84** [comment]
#4360
