### ISSUE TITLE
Bug: QnAPair not syncing with Azure Search

### ISSUE THREAD

**Issue by kiwikoda** [Microsoft/BotBuilder#5075]
I have a QnAMaker knowledge base with 73 entries in it.

I found an issue where a certain answer would return fine when we tested in the QnAMaker portal, but was not coming up at all in the bot emulator when the same question was asked.

Looking in the Azure Search portal I noticed it had only 72 documents in the index. Interrogating the index directly I found that the QnAPair in question did not exist in the index.

No amount of training and publishing would make the QnAPair appear in the index.

Eventually I had to recreate the entry from scratch in QnAMaker in order to get it to sync with Azure Search and then appear as an answer in my bot.

**Comment by stevkan** [comment]
If you export the knowledge base is the missing QnA pair present?

**Comment by kiwikoda** [comment]
Yes. In fact we considered exporting and reimporting the data as a way to possibly fix the issue, as we took that approach on a smaller KB that had a similar issue and that fixed it. But we decided not to as this was a large KB that was in production.

The issue on this other KB was that the metadata on a number of pairs was not synching with Azure Search.

**Comment by sgellock** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team

**Comment by sgellock** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
