### ISSUE TITLE
Generic OAuth Provider in Azure Bot channels registration

### ISSUE THREAD

**Issue by absinghal** [Microsoft/BotBuilder#5076]
Hello

Trying to add a new OAuth setting in Azure bot channel registration using generic OAuth provider.

It is asking fields such as query string template and body template.

Need documentation or a sample filled form so that entries can be made accordingly. 

Thx

**Comment by Zerryth** [comment]
The Microsoft Bot Framework team prefers that **how to** questions be submitted on [StackOverflow](https://stackoverflow.com/search?q=%23botframework). 

The official [Bot Framework GitHub](https://github.com/Microsoft/BotBuilder/issues) repo is the preferred platform for submitting **bug fixes** and **feature requests** to the framework itself.

Closing the issue, as this does not appear to be a bug within the framework itself. Please post your question on GitHub so the community could assist! Also, regarding your question in particular, specify what SDK you're using (e.g. Node, C#) and what version (v3? v4?) to be helped as quickly as possible

**Comment by absinghal** [comment]
Thanks Zerryth - was asked by @AzureSupport to post here but will keep in mind nevertheless.

C# - v4

**Comment by absinghal** [comment]
Posted at https://stackoverflow.com/questions/52544143/generic-oauth-provider-in-azure-bot-channels-registration
