### ISSUE TITLE
Error: Dialog[BotBuilder:**] not found.     at Session.beginDialog 

### ISSUE THREAD

**Issue by Mwalima** [Microsoft/BotBuilder#5077]
I created a bot.dialog and want to call an other dialog inside it.  It keeps failing on  "  session.beginDialog('geholpen');"

![image](https://user-images.githubusercontent.com/4654945/46067214-9aab0100-c176-11e8-845d-2f2249d62c1f.png)

error message
![image](https://user-images.githubusercontent.com/4654945/46067177-8109b980-c176-11e8-9381-a20cfac933fb.png)

can someone help please?

**Comment by Zerryth** [comment]
The Microsoft Bot Framework team prefers that **how to** questions be submitted on [StackOverflow](https://stackoverflow.com/search?q=%23botframework). 

The official [Bot Framework GitHub](https://github.com/Microsoft/BotBuilder/issues) repo is the preferred platform for submitting **bug fixes** and **feature requests** to the framework itself.

Closing the issue, as this does not appear to be a bug within the framework itself. Please post your question on GitHub so the community could assist!
