### ISSUE TITLE
AADV2 Sample gives null reference exception while retrieving token

### ISSUE THREAD

**Issue by jaiswati** [Microsoft/BotBuilder#5079]
This always gives the null reference exception (highlighted in bold)
// First ask Bot Service if it already has a token for this user highlighted in the bold
                **var token = await context.GetUserTokenAsync(ConnectionName).ConfigureAwait(false);**
                if (token != null)
                {
                    // use the token to do exciting things!
                }
                else
                {
                    // If Bot Service does not have a token, send an OAuth card to sign in
                    await SendOAuthCardAsync(context, (Activity)context.Activity);
                }

**Comment by JasonSowers** [comment]
Have you tested the connection in the portal to make sure your connection is correctly configured?  I assume you are talking about [this sample](https://github.com/Microsoft/BotBuilder-V3/tree/master/CSharp/Samples/AadV2Bot)?

**Comment by jaiswati** [comment]
Hi ,

we had referred the sample described [here](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-authentication?view=azure-bot-service-3.0), but seems  this sample  is moved to some other[ repository](https://github.com/Microsoft/BotBuilder/tree/master/CSharp/Samples/AadV2Bot)..
Also we had referred the steps to create the [Connection](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-authentication?view=azure-bot-service-3.0) ,Could you please confirm if steps to create connection is still valid?

**Comment by sgellock** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
