### ISSUE TITLE
Error: Could not find a part of the path 'D:\home\site\artifacts\manifest'. build.cmd FAILING

### ISSUE THREAD

**Issue by upsilondynamics** [Microsoft/BotBuilder#5080]
Trying to get setup with a new Azure Web Bot and the online build.cmd script fails everytime when using the online code editor to make tweaks, I can deploy remotely using Visual Studio - please help.

KuduSync.NET from: 'D:\local\Temp\___deployTemp9033' to: 'D:\home\site\wwwroot'
Copying file: 'BasicBot.deps.json'
Copying file: 'BasicBot.dll'
Copying file: 'BasicBot.pdb'
Copying file: 'BasicBot.PrecompiledViews.dll'
Copying file: 'BasicBot.PrecompiledViews.pdb'
Copying file: 'BasicBot.runtimeconfig.json'
Error: Could not find a part of the path 'D:\home\site\artifacts\manifest'.
Failed exitCode=1, command="kudusync" -v 50 -f "D:\local\Temp\___deployTemp9033" -t "D:\home\site\wwwroot\." -n "D:\home\site\wwwroot\..\artifacts\manifest" -p "D:\home\site\wwwroot\..\artifacts\manifest" -i ".git;.hg;.deployment;deploy.cmd"
An error has occurred during web site deployment.

**Comment by upsilondynamics** [comment]
Changing this line:
SET ARTIFACTS=%~dp0%..\artifacts

To:
SET ARTIFACTS=%~dp0%

Fixes the problem, I am assuming there is some permission issue because even if I try to chmod 777 the directory it doesn't allow it, this seeems to have worked as a crude workaround but I'd like to see Microsoft fix the deployment/build scripts so they just work and save people pain and suffering of having to modify their "canned" out of the box deployment/build scripts..

**Comment by sgellock** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
