### ISSUE TITLE
Bot Builder 3.x settings 

### ISSUE THREAD

**Issue by diberry** [Microsoft/BotBuilder#5081]
Once I build my bot, how can I tell what settings I chose such as 3.x vs 4.x in the resulting azure portal web app bot settings?

**Comment by EricDahlvang** [comment]
I don't think there is a way to tell from the portal's bot settings page.  You could determine which template was used by looking at the Resource's Deployments, and checking the zipurl for which template was used:

![image](https://user-images.githubusercontent.com/11055362/46180769-1db38080-c277-11e8-87f4-d10c9ca10bf4.png)


There might be somewhere else this information is stored, but I'm not aware of it.

**Comment by sgellock** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
