### ISSUE TITLE
Bot C# 3.x LUIS template doesn't build locally

### ISSUE THREAD

**Issue by diberry** [Microsoft/BotBuilder#5082]
I built and downloaded the C# 3.x LUIS bot. When I built it in local Visual Studio Community, HttpClient can't be found. 

Is it supposed to build without having to fix NuGet packages? I just want to fix this one error but is says there are 27 packages that need updates.

**Comment by EricDahlvang** [comment]
Hi @diberry 

Can you share more information about the compile error you are seeing?  (It should not be necessary to update any of the nuget packages, but it is necessary to restore nuget packages.)  The Community edition of Visual Studio should work without issue.

I just created a LUIS v3 bot:

![image](https://user-images.githubusercontent.com/11055362/46180497-a3cec780-c275-11e8-82e0-7aa4337daafd.png)

It also has 27 outdated packages, but it builds without updating them.

![image](https://user-images.githubusercontent.com/11055362/46180525-c4971d00-c275-11e8-9d57-eec07e058045.png)

**Comment by sgellock** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
