### ISSUE TITLE
LUIS Node BOT not able to show correct dialog 

### ISSUE THREAD

**Issue by Dekapri** [Microsoft/BotBuilder#5083]
LUIS simple Node BOT not able to show correct dialog in emulator (Bot Builder SDK V3 Javascript)
-------------------------------------------
**_Scenario:_**
Node JS code deployed locally with Bot Framework Emulator V3.5.36
Node version: 7.9
 Visual Studio Code Version : 1.24.0

_**Node JS libraries Versions:**_
botbuilder: 3.15.0
dotenv-extended: 2.3.0
restify: 7.2.1

_**Use Case**_
I 'would like to make a very simple LUIS Bot that could disting between the 4 basic intents
CANCEL ,GREETINGS, HELP and NONE, and when i write something in emulator, the bot
tell me which intent has been selected.

_**Expected behavior**_
For example if I say "Hi" to emulator bot has to tell  me that is the GREATING dialog.
For example if  say   "Cancel" to emulator bot has to  tell me that is the CANCEL dialog.
For example if I say "Hi" to emulator bot has to tell me that is the GREATING dialog.
For example if  say   "Something extrange" to emulator bot tell me that is the NONE dialog.

Please see the actual behavior in image below:

![emulator_chat](https://user-images.githubusercontent.com/34340214/46155246-26a45200-c277-11e8-8fe8-3cbe7fdc6d9a.JPG)

_**Real behavior**_

The bot always make the link between utterance and intents properly, but when the bot has to
"draw" the corresponding dialog in emulator sometimes show the default message and sometimes show the correct dialog.

If I sent the query directly to LUIS service URL, always works fine (To the URL and service that I got set in my code, in the  .env file) and give me correct intent, and in the logs showed in Visual studio always match properly between utterance and LUIS intentes, please see logs here:

_**LOGS**_
__________________________________________________

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

D:\BOT8>node app.js
restify listening to http://[::]:3978
WARN: ChatConnector: receive - emulator running without security enabled.
ChatConnector: message received.
The Bot State API is deprecated.  Please refer to https://aka.ms/I6swrh for details on how to replace with your own storage.
UniversalBot("*") routing "hi" from "emulator"
Library("*")recognize() recognized: Greeting(0.9110797)
Library("*").findRoutes() explanation:
        ActiveDialog(0.1)
/ - waterfall() step 1 of 1
/ - Session.send()
/ - Session.sendBatch() sending 1 message(s)
The Bot State API is deprecated.  Please refer to https://aka.ms/I6swrh for details on how to replace with your own storage.
WARN: ChatConnector: receive - emulator running without security enabled.
ChatConnector: message received.
The Bot State API is deprecated.  Please refer to https://aka.ms/I6swrh for details on how to replace with your own storage.
UniversalBot("*") routing "cancel" from "emulator"
Library("*")recognize() recognized: Cancel(0.958188951)
Library("*").findRoutes() explanation:
        ActiveDialog(0.1)
        GlobalAction(0.958188951)
Session.beginDialog(*:Cancel)
Cancel - waterfall() step 1 of 1
Cancel - Session.send()
Cancel - Session.endDialog()
Session.sendBatch() sending 1 message(s)
The Bot State API is deprecated.  Please refer to https://aka.ms/I6swrh for details on how to replace with your own storage.
WARN: ChatConnector: receive - emulator running without security enabled.
ChatConnector: message received.
The Bot State API is deprecated.  Please refer to https://aka.ms/I6swrh for details on how to replace with your own storage.
UniversalBot("*") routing "hi" from "emulator"
Library("*")recognize() recognized: Greeting(0.9110797)
Session.beginDialog(/)
/ - waterfall() step 1 of 1
/ - Session.send()
/ - Session.sendBatch() sending 1 message(s)
The Bot State API is deprecated.  Please refer to https://aka.ms/I6swrh for details on how to replace with your own storage.
WARN: ChatConnector: receive - emulator running without security enabled.
ChatConnector: message received.
The Bot State API is deprecated.  Please refer to https://aka.ms/I6swrh for details on how to replace with your own storage.
UniversalBot("*") routing "cancel" from "emulator"
Library("*")recognize() recognized: Cancel(0.958188951)
Library("*").findRoutes() explanation:
        ActiveDialog(0.1)
        GlobalAction(0.958188951)
Session.beginDialog(*:Cancel)
Cancel - waterfall() step 1 of 1
Cancel - Session.send()
Cancel - Session.endDialog()
Session.sendBatch() sending 1 message(s)
The Bot State API is deprecated.  Please refer to https://aka.ms/I6swrh for details on how to replace with your own storage.
WARN: ChatConnector: receive - emulator running without security enabled.
ChatConnector: message received.
The Bot State API is deprecated.  Please refer to https://aka.ms/I6swrh for details on how to replace with your own storage.
UniversalBot("*") routing "good bye" from "emulator"
Library("*")recognize() recognized: Greeting(0.964646935)
Session.beginDialog(/)
/ - waterfall() step 1 of 1
/ - Session.send()
/ - Session.sendBatch() sending 1 message(s)
The Bot State API is deprecated.  Please refer to hWARN: ChatConnector: receive - emulator running witChatConnector: message received.
The Bot State API is deprecated.  Please refer to hUniversalBot("*") routing "cancel" from "emulator"
Library("*")recognize() recognized: Cancel(0.958188Library("*").findRoutes() explanation:
        ActiveDialog(0.1)
        GlobalAction(0.958188951)
Session.beginDialog(*:Cancel)
Cancel - waterfall() step 1 of 1
Cancel - Session.send()
Cancel - Session.endDialog()
Session.sendBatch() sending 1 message(s)
The Bot State API is deprecated.  Please refer to hWARN: ChatConnector: receive - emulator running without security enabled.
ChatConnector: message received.
The Bot State API is deprecated.  Please refer to https://aka.ms/I6swrh for details on how to replace with your own storage.
UniversalBot("*") routing "hi" from "emulator"
Library("*")recognize() recognized: Greeting(0.9110797)
Session.beginDialog(/)
/ - waterfall() step 1 of 1
/ - Session.send()
/ - Session.sendBatch() sending 1 message(s)
The Bot State API is deprecated.  Please refer to https://aka.ms/I6swrh for details on how to replace with your own storage.

__________________________________________________

As you can see in the image bellow extracted from previous logs sometimes the bot show the dialog properly but sometimes not.

_**WORKING**_
![image1_cancel_working](https://user-images.githubusercontent.com/34340214/46207504-ec46bd80-c327-11e8-9f04-cd2da830f883.JPG)

_**NOT WORKING**_
![image2_hi_not_working](https://user-images.githubusercontent.com/34340214/46207517-f8cb1600-c327-11e8-8ecd-0b4d8246551c.JPG)

_**THE CODE**_
```javascript
/*-----------------------------------------------------------------------------
A simple Language Understanding (LUIS) bot for the Microsoft Bot Framework. 
-----------------------------------------------------------------------------*/
require('dotenv-extended').load();
var restify = require('restify');
var builder = require('botbuilder');
//var botbuilder_azure = require("botbuilder-azure");

// Setup Restify Server
var server = restify.createServer();
server.listen(process.env.port || process.env.PORT || 3978, function () {
    console.log('%s listening to %s', server.name, server.url);
});
  
// Create chat connector for communicating with the Bot Framework Service
var connector = new builder.ChatConnector({
    appId: process.env.MicrosoftAppId,
    appPassword: process.env.MicrosoftAppPassword,
    openIdMetadata: process.env.BotOpenIdMetadata
});

// Listen for messages from users 
server.post('/api/messages', connector.listen());



// Create your bot with a function to receive messages from the user
// This default message handler is invoked if the user's utterance doesn't
// match any intents handled by other dialogs.

var bot = new builder.UniversalBot(connector, function (session, args) {
    session.send('Has llegado al default  message handler. You said \'%s\'.', session.message.text);
});


// Make sure you add code to validate these fields
var luisAppId = process.env.LuisAppId;
var luisAPIKey = process.env.LuisAPIKey;
var luisAPIHostName = process.env.LuisAPIHostName || 'westus.api.cognitive.microsoft.com';

const LuisModelUrl = 'https://' + luisAPIHostName + '/luis/v2.0/apps/' + luisAppId + '?subscription-key=' + luisAPIKey;

// Create a recognizer that gets intents from LUIS, and add it to the bot
var recognizer = new builder.LuisRecognizer(LuisModelUrl);
bot.recognizer(recognizer);

//console.log(bot.recognizer);



// Add a dialog for each intent that the LUIS app recognizes.
// See https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-recognize-intent-luis 

bot.dialog('Cancel',
    (session) => {
        session.send('You reached the Cancel intent. You said \'%s\'.', session.message.text);
        session.endDialog();

    }
    ).triggerAction({
    matches: 'Cancel'
})

bot.dialog('Help',
    (session) => {
        session.send('You reached the Help intent. You said \'%s\'.', session.message.text);
        session.endDialog();
    }
    ).triggerAction({
    matches: 'Help'
 })

   
 bot.dialog('None',
    (session) => {
        session.send('You reached the None intent. You said \'%s\'.', session.message.text);
        session.endDialog();
    }
    ).triggerAction({
    matches: 'None' 
 
 })

 bot.dialog('Greating',
 (session) => {
        session.send('You reached the Greating intent. You said \'%s\'.', session.message.text);
        session.endDialog();
 }
 ).triggerAction({
 matches: 'Greating' 

});
```
Thanks and regards!

**Comment by stevengum** [comment]
The intent `"Greeting"` doesn't match your code, which says `"Greating"`. Changing it so both are the same should solve your problem.

```js
// This should be 'Greeting', not 'Greating'
bot.dialog('Greating',
  (session) => {
        session.send('You reached the Greating intent. You said \'%s\'.', session.message.text);
        session.endDialog();
   }
 ).triggerAction({
 matches: 'Greating' 
});
```

**Comment by Dekapri** [comment]
Hi,
The code is working properly now. If you are agree we can close the issue.
**Thanks for your help!!**

**Comment by stevengum** [comment]
Awesome @Dekapri, I'm glad it works 😄 

Closing issue
