### ISSUE TITLE
Access token requests optimization

### ISSUE THREAD

**Issue by mitkodi** [Microsoft/BotBuilder#5084]
The requests for a JWT token take about 3s. To improve that I tried [Periodic token refreshing](https://blog.botframework.com/2017/11/02/optimizing-latency-bot-framework/), but as I can see (from the application insights), during the bot activity periods, it requests a token (calls https://login.microsoftonline.com/botframework.com/oauth2/v2.0/token) almost every 10 minutes and that calls are part of the bot activity, not standalone output requests from the token refresher process.
So, I don't understand, why during the activity hours it requests a new token every 10 minutes in case the tokens expire in 3600 seconds and as a result of that the refresher that is scheduled to request token every 30min. particularly has no effect on the performance.
(*the bot.builder's version is 3.16.0*)

![accesstokenrequests](https://user-images.githubusercontent.com/5601143/46287143-1c34d180-c571-11e8-9eaf-32108030871d.jpg)

_Originally posted by @mitkodi in https://github.com/Microsoft/BotBuilder/issues/4322#issuecomment-422804975_

**Comment by EricDahlvang** [comment]
Hi @mitkodi 

There have been numerous updates to the token refresh code since that blog post was written.  There is now an AutoTokenRefreshTimeSpan of 10 minutes: https://github.com/Microsoft/BotBuilder-V3/blob/master/CSharp/Library/Microsoft.Bot.Connector.Shared/MicrosoftAppCredentials.cs#L94
