### ISSUE TITLE
Microsoft Bot Framework - Email channel Issue - Unable to save Credentials

### ISSUE THREAD

**Issue by fj4870** [Microsoft/BotBuilder#5085]
Unable to register Microsoft bot framework Email channel as getting following error "Unable to save. Unable to validate the given credentials" while saving email id and password.

 I have tried using different emails including Office 365, @outlook.com etc but none of them working. Has anyone run into the same problem?

**Comment by tomlm** [comment]
This issue was moved to Microsoft/BotFramework-Services#4

**Comment by EricDahlvang** [comment]
@fj4870 Does the email address you are using pass the Microsoft Exchange Web Services Connectivity Tests here: https://testconnectivity.microsoft.com/  Usually, when an email address configuration issue occurs, it is related to Auto Discovery.

Are you able to save this same email address into a different bot's configuration?

Also, there have historically been times where the email channel saves correctly even though there has been an exception in the UI: https://github.com/Microsoft/BotBuilder/issues/3201
