### ISSUE TITLE
Problem adding script in FormFlow Json

### ISSUE THREAD

**Issue by manu4rhyme** [Microsoft/BotBuilder#510]
So my Json looks like this, 

```
  "References": ["SkeletonBot.dll"],
  "Imports": [ "SkeletonBot.Dialogs.FormFillDialog", "SkeletonBot.FormFill.ProcessForm" ],
   ...
   ...
   ...
   ...

   "OnCompletion": "await context.PostAsync(\"We are currently processing your form\");"
```
When I run, I get the exception, 

"message": "An error has occurred.",
  "exceptionMessage": "error CS0234: The type or namespace name 'Bot' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)",
  "exceptionType": "Microsoft.CodeAnalysis.Scripting.CompilationErrorException",
  "stackTrace": "   at Microsoft.Bot.Builder.FormFlow.Json.FormBuilderJson.Compile[G,R](String code)\r\n   at ......................................................................

From what I read in the documentation, reference to Microsoft.Bot.Builder.dll is already added by default ? Also tried adding it manually, still the same error.

**Comment by chrimc62** [comment]
You are doing it exactly right.  I've repro'ed the problem and am investigating.  It is very weird...

**Comment by chrimc62** [comment]
The issue is with URI escaping.  If your project is on a path without spaces it should work.  I'm working on a fix for the next release.

**Comment by manu4rhyme** [comment]
Ohhk, so i moved my project to a path without spaces. The default imports including the normal context.PostAsync works well...

But i am unable to add my own imports, the following thing gives error 

```
"References": ["SkeletonBot.dll"],
  "Imports": [ "SkeletonBot.Dialogs.FormFillDialog", "SkeletonBot.FormFill.ProcessForm" ],
   ...
   ...
   ...
   ...

   "OnCompletion": "await context.PostAsync((new ProcessForm(state)).process());"

```

The above thing gives this error:
error CS0246: The type or namespace name 'ProcessForm' could not be found...

Its not very clear, how i should add reference for that class? I already added the namespace in the
import list above...But it doesn't seem to work. Do i need to change the build action of that file from compile to assembly reference?? Can i please get a detailed process/example to get custom imports working?

**Comment by manu4rhyme** [comment]
Please ignore the above, I got it working ! The imports were incorrect.
