### ISSUE TITLE
SSO Authentication using Azure AD - Webchat Botbuilder V3

### ISSUE THREAD

**Issue by kesavanpurushothaman** [Microsoft/BotBuilder#5104]
Hi all,

We are planning to integrate webchat created using Bot Builder V3 within an authenticated website.
For authentication, we are planning to use SSO of the website.

Please suggest the best practice to authenticate Chatbot users.

Thanks,
Kesavan Purushothaman

**Comment by JasonSowers** [comment]
Take a look at this blog https://blog.botframework.com/2018/08/28/sign-in-experiences/ It should get you started.

Please post v3 questions in the [v3 repo](https://github.com/Microsoft/BotBuilder-v3) in the future.

**Comment by JasonSowers** [comment]
Sorry, I do not have a working example to share.
