### ISSUE TITLE
DCR - Add Partition Key to CosmosDB (proposed for v4.2.0)

### ISSUE THREAD

**Issue by cleemullins** [Microsoft/BotBuilder#5107]
# Goal
Enable the CosmosDB Provider to support developer defined Partitions. This is needed for 2 reasons:
1. Part of the maturity & credibility story around using CosmosDB. Developers expect access to the Partition keys. 
2. Support (potentially) large bots.

# Compatability
Any solution must have defaults that are back-compatable with v4.0.X bots. This means any new functionality needs to be either additive, a new switch of some time, or fully back-compat. 

# Proposal
Allow developers, on each request, to participate in the data flow and specify a partition key. 

To accomplish this, the following DB related operations in CosmosDBStorage need to be updates:
1. DeleteAsync (C#), Delete (JS)
2. ReadAsync (C#), Read (JS)
3. WriteAsync (C#), Write(JS)

The proposal is to add a new class, PartitionedDocumentStoreItem, alongside DocumentStoreItem. To help insure compatability, this class would NOT be created using inheritence, and would instead simply be a new POCO/POJO. 
```cs
private class DocumentStoreItem
{
    [JsonProperty("partitionKey")]
    public string PartitionKey { get; set; }
    [JsonProperty("id")]
    public string Id { get; set; }
    [JsonProperty("realId")]
    public string ReadlId { get; internal set; }
    [JsonProperty("document")]
    public JObject Document { get; set; }
    [JsonProperty("_etag")]
    public string ETag { get; set; }
}
```
```js
interface DocumentStoreItem {
   partitionKey: string;
   id: string;
   realId: string;
   document: any;
}
```

## DB Initialization
A new "usePartitions" flag is added to the CosmosDbStorageOptions POCO/POJO. If set, the database is initialized as having the partition key in the document collection set to the PartitionKey path. 

```cs
var documentCollection = new DocumentCollection
{
    Id = _collectionId,
};
documentCollection.PartitionKey.Paths.Add("/partitionKey");
```
```js
let docCollection = client.createCollection(
    databaseLink, 
    { id: collectionId }, 
    (err2: any, collectionLink: any) => {
        if (err2) { return reject(err2); }
        resolve(collectionLink._self);
    });
docCollection.PartitionKey.Paths.Add("/partitionKey");
```

# Developer Participation
Developers inherit from CosmosDBStore and override the GetPartitionKey method. This is called on every read/write, and allows the developer to specify an arbitrary string. 
```cs
public overridable string GetPartitionKey(TurnContext context)
{
    return "someKey";
}
```

**Comment by mdrichardson** [comment]
I've got [a working implementation](https://github.com/mdrichardson/botbuilder-js/blob/cosmosPull/libraries/botbuilder-azure/src/cosmosDbStorage.ts) in Node with written and passing tests. It was 90% written before I came across the above design guidelines, but I think it still matches the intent. I'm hoping to get to a dotnet/C# version, but I'm still new to C# and am busy working on support tickets, so somebody else might be able to implement faster than I.

**Comment by mdrichardson** [comment]
I'm starting to work on the C# implementation, but I'm still new to C#, so anybody can feel free to take it if this becomes a priority. Just a note: the Node implementation uses the new `@azure/cosmos`, replacing the deprecated `documentdb`. The equivalent on the .NET side is [Azure Cosmos DB .NET SDK V3](https://github.com/Azure/azure-cosmos-dotnet-v3), which is still in prerelease.

**Comment by mdrichardson** [comment]
Quick update: The C# Cosmos SDK doesn't currently support non-partitioned databases at all, which breaks backwards compatibility. They're supposed to be releasing an update that allows for this "soon," but it has stalled progress on the C# port. See https://github.com/Azure/azure-cosmos-dotnet-v3/issues/5

**Comment by cleemullins** [comment]
As an update: We've got PRs in both the C# and JS repos for this fix:
JS [860] (https://github.com/Microsoft/botbuilder-js/pull/860)
C# [1537] (https://github.com/Microsoft/botbuilder-dotnet/pull/1537)

**Comment by cleemullins** [comment]
Done in both C# and JS. Closing.
