### ISSUE TITLE
Align SDK V4 version numbers

### ISSUE THREAD

**Issue by yochay** [Microsoft/BotBuilder#5110]
## Issue
*Describe the issue you are addressing*
Align emitted SDK Version numbers between JS and C# (Java and Python) 

## Proposed change
Align the format of the version numbers between JS and .NET to improve usage reporting 

Currently 
.NETCoreApp | 4.0.6.0 | BotBuilder | 
.Net | 4.0.7.0 | BotBuilder |
Node.js | 4.0.6 | BotBuilder | 
.Net | 4.0.0.46 | BotBuilder | 

Python | 4.0.0.a6 | BotBuilder | 

There is an 'extra' zero for .NET, which doesn't show up for node.js.   We should align on one format across languages. 

## Component Impact 
minor change

## Customer Impact 
required to improve usage reporting

## Tracking Status
**Dotnet SDK**
- [ ] PR
- [ ] Merged

**Javascript SDK**
- [ ] PR
- [ ] Merged

**Java SDK**
- [ ] PR
- [ ] Merged

**Python SDK**
- [ ] PR
- [ ] Merged

**Emulator**
- [ ] PR
- [ ] Merged

**Samples**
- [ ] PR
- [ ] Merged

**Docs**
- [ ] PR
- [ ] Merged

**Tools**
- [ ] PR
- [ ] Merged

[dcr]

**Comment by sgellock** [comment]
by design
