### ISSUE TITLE
Getting Dependency failures related to table storage in app insights while loading botstate

### ISSUE THREAD

**Issue by aniketk1264** [Microsoft/BotBuilder#5111]
### **Bot Info**

- SDK Platform: .NET
- SDK Version: Version=3.15.3.0
- Active Channels: WebChat
- Deployment Environment: Azure App Service

### **Issue Description**

We are using azure table storage for maintaining botstate. When user tries to login in our application and tries to initiate dialog with bot for 1st time, we only had userData in table storage at that point of time. Before initiating dialog, we are loading the botstate(userData/ConversationData/PrivateConversationData). Since we don't have conversation data/PrivateConversationData in table storage at that point of time, dependency failures for table storage with response code : 404 are getting logged in Application Insights.

Initially we were using BotBuilder V3.11 and had our own custom implementation for maintaining botstate. So we were handling it by verifying if that botdata exists in table storage and then only used to load it. 

Recently we have upgraded the Bot Builder version to 3.15.3 and we are overriding the Microsoft implementation instead of having the custom implementation. With this implementation, when we try to load botstate for user when he initiates dialog with bot for 1st time, dependency failures for conversation data/private Conversation Data are getting logged in Application Insights.

**Below are the requests for which 404 dependency failures are getting logged**
https://sa7364dipaprd.table.core.windows.net:443/botdata(PartitionKey='webchat:conversation',RowKey=<conversationId>)
https://sa7364dipaprd.table.core.windows.net:443/botdata(PartitionKey='webchat:private',RowKey=<conversationId:UserId>)

**Please find below the code change we applied for handling the 404 failures when we were using Bot Builder v3.11**

### **Code Example**

```
async Task<BotData> IBotDataStore<BotData>.LoadAsync(IAddress key, BotStoreType botStoreType, CancellationToken cancellationToken)
        {
            //await WriteTraceFileLogsInfo("Entered LoadAsync in Bot.Builder.Azure");
            var entityKey = BotDataEntity.GetEntityKey(key, botStoreType);
            
            
            try
            {
                bool isExists = await EntityExists(entityKey.PartitionKey, entityKey.RowKey);

                if (isExists)
                {
                    var result = await this.Table.ExecuteAsync(TableOperation.Retrieve<BotDataEntity>(entityKey.PartitionKey, entityKey.RowKey));
                    BotDataEntity entity = (BotDataEntity)result.Result;

                    //await WriteTraceFileLogsInfo(string.Format("Data in storage for UserId : {0}", key.UserId));

                    if (entity == null)
                        // empty record ready to be saved
                        return new BotData(eTag: String.Empty, data: null);

                    //await WriteTraceFileLogsInfo("Exit LoadAsync in Bot.Builder.Azure");
                    // return botdata 
                    return new BotData(entity.ETag, entity.GetData());
                }
                else
                {
                    return new BotData(eTag: String.Empty, data: null);
                }
            }
            catch (StorageException err)
            {
                //await WriteTraceFileLogsInfo("Error in LoadAsync in Bot.Builder.Azure :" + err);
                throw new HttpException(err.RequestInformation.HttpStatusCode, err.RequestInformation.HttpStatusMessage);
            }
        }

 /// <summary>
        /// 
        /// </summary>
        /// <param name="partitionKey"></param>
        /// <param name="rowKey"></param>
        /// <returns></returns>
        public async Task<bool> EntityExists(string partitionKey, string rowKey)
        {
            bool isExists = false;
            TableQuery<BotDataEntity> tableQuery = new TableQuery<BotDataEntity>().Where(TableQuery.CombineFilters(
                    TableQuery.GenerateFilterCondition("PartitionKey", QueryComparisons.Equal, partitionKey),
                    TableOperators.And,
                    TableQuery.GenerateFilterCondition("RowKey", QueryComparisons.Equal, rowKey)));


            TableContinuationToken token = null;
            do
            {
               
                    TableQuerySegment<BotDataEntity> result = await this.Table.ExecuteQuerySegmentedAsync(tableQuery, token);
                    token = result.ContinuationToken;
                    if (result.Results.Any())
                        isExists = true;
               
            }
            while (token != null);

            return isExists;
        }

```

In the above code, we used to check if botdata exists in table storage using **EntityExists()** before retrieving it from azure table storage and we have handled 404 dependency failures

Below is the State implementation when we upgraded Bot Builder to V3.15.3 for loading botState.

```
public static async Task<BotData> GetBotDataAsync(string channelId, string userId)
        {
            BotData botData = new BotData();
            using (var scope = Conversation.Container.BeginLifetimeScope())
            {
                IBotDataStore<BotData> botDataStore = scope.ResolveKeyed<IBotDataStore<BotData>>(AzureModule.Key_DataStore);
                var key = new AddressKey()
                {
                    BotId = "",
                    ChannelId = channelId,
                    UserId = userId,
                    ConversationId = "",
                    ServiceUrl = ""
                };
                botData = await botDataStore.LoadAsync(key, BotStoreType.BotUserData, CancellationToken.None);
                await botDataStore.FlushAsync(key, CancellationToken.None);
            }
            return botData;
        }
```

**In the above code could you please suggest how to check if botData exists in table storage before retrieving it using loadAsync() so that we can handle 404 failures related to conversationData/PrivateConversationData which are getting logged in application insights.**

### **Steps to Reproduce Failure**

- Login to our application
- Load BotState and Initiate Dialog with bot for 1st time

### **Actual Result**
Since conversationData/PrivateConversationData is not maintained in storage at that point of time and only userData is maintained in it, 404 dependency failures are getting logged in application insights

### **Expected Result,** 
We need to handle these failures before loading botstate when user initiates dialog with bot for 1st time

**Comment by sgellock** [comment]
This issue was moved to Microsoft/BotBuilder-V3#31
