### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by teamplumaa** [Microsoft/BotBuilder#5114]
Bot Info
SDK Platform: Nodejs
SDK Version: 3.14.0
Active Channels: Webchat, Directline
Deployment Environment: Bot Channels Registration, Azure App Service
Bot Handle: TB12

Issue Description
Bot is not able to respond back, throwing "503 Service Unavailable".

URL
The bot is live at http://testst.bombeohq.com/ 

Reproduction Steps
The bot is supposed to send a proactive message to begin the conversation, after which the user replies with "I will like to sell a house", and the rest of the dialogflow is initiated.

I thought this was an issue with my code, but I experienced the same 503 error with the bot not responding back to messages sent.

Actual Results
Directline Throwing "503 Service Unavailable"

**Comment by teamplumaa** [comment]
`require('dotenv').config();
const restify = require('restify');

const builder = require('botbuilder');

var fs = require('fs');

var clients = require('restify-clients');

var azure = require('botbuilder-azure');

var now = require('currently');

// PORT
var listenPort = process.env.port || process.env.PORT || 3978;

// Setup Restify Server

var server = restify.createServer()

server.listen(listenPort, '::', () => {
  console.log(`smooth like a baby's bottom`)
});

// Create chat connector for communicating with the Bot Framework Service

var connector = new builder.ChatConnector({
    appId: process.env.MICROSOFT_APP_ID,
    appPassword: process.env.MICROSOFT_APP_PASSWORD
});

// Receive messages from the user and respond

var bot = new builder.UniversalBot(connector, function (session) {
    session.beginDialog('sell:Sell');
});

// Listen for messages from users
server.post('/api/messages', connector.listen());

bot.on('conversationUpdate', function (message) {
  if (message.membersAdded) {

    greetings = now.timeOfDay + 'welcome to Dream Realty, my name is Tony. How can I be of help this afternoon?'

    message.membersAdded.forEach(function (identity) {
      if (identity.id === message.address.bot.id) {
        bot.send(new builder.Message()
          .address(message.address)
          .text(greetings)
        )
      }
    })
  }
});

bot.library(require('./dialogs/sell').createLibrary())`

**Comment by teamplumaa** [comment]
@vincec-msft is it possible to get someone to take a look as to why the bot is not returning a response after the user initially replies.

the conversations work perfectly in local bot emulator

**Comment by vincec-msft** [comment]
Looks like your bot is using the default bot state service. That service was deprecated in March so calls to it will return HTTP 405 Method Not Allowed.

See https://blog.botframework.com/2017/12/19/bot-state-service-will-soon-retired-march-31st-2018/
