### ISSUE TITLE
Bot takes > 10 seconds for the first response and At very First load bot gives error "Bot Code is having an issue"

### ISSUE THREAD

**Issue by PrernaGupta1** [Microsoft/BotBuilder#5115]
Bot Info
•SDK Platform: .NET
•SDK Version: 3.8.1.0
•Active Channels: Direct Line
•Deployment Environment: Azure App Service deployed version

Issue Description

1. Bot takes > 10 seconds for the first response 
2. At very First load bot gives error "Bot Code is having an issue" and to resolve the issue we need to start app service

Expected Behavior

Response time should remain similar around 500ms.
Bot should be  up and running without restarting an app service

**Comment by PrernaGupta1** [comment]
Below is the exception details:

Exception 1 :
Event time	10/22/2018, 4:33:37 PM	 
Message	POST to BotCR-7220-Dev failed: POST to the bot's endpoint failed with HTTP status 503 POST to the bot's endpoint failed with HTTP status 503	 
Exception type	System.Exception	 
Failed method	Microsoft.Bot.ChannelConnector.BotAPI+<PostActivityToBotAsync>d__31.MoveNext	 
Sample rate	1	 
Telemetry type	exception	 
Device type	PC	 
Client IP address	0.0.0.0	 
City	Singapore	 
State or province	Central Singapore Community Development Council	 
Country or region	Singapore	 
Application version	Thu 10/18/2018 0:19:19.04 UTC (factoryvm-az361) [Build 41682] [Repo Intercom] [Branch prod] [Commit 0da15ddb4e2ea9f3f2b01674eae3a93e96d3a159] 	 
SDK version	dotnet:2.7.2-23439	 
Cloud role name	bc-directline-southeastasia	 
Cloud role instance	RD00155D63EFA1	 
Operation Id	b88847881033c74fbaf4a9d48d003d76	 
Parent Id	|b88847881033c74fbaf4a9d48d003d76.729dcbb0_	 
Problem Id	System.Exception at Microsoft.Bot.ChannelConnector.BotAPI+<PostActivityToBotAsync>d__31.MoveNext	
Assembly	Microsoft.Bot.ChannelConnector, Version=3.2.2.4, Culture=neutral, PublicKeyToken=null	

Exception 2 :

Event time	10/22/2018, 4:33:05 PM	 
Message	POST to BotCR-7220-Dev timed out after 15s	 
Exception type	Microsoft.Bot.Schema.BotTimeoutException	 
Failed method	Microsoft.Bot.ChannelConnector.BotAPI+<PostActivityToBotAsync>d__31.MoveNext	 
Sample rate	1	 
Telemetry type	exception	 
Device type	PC	 
Client IP address	0.0.0.0	 
City	Boydton	 
State or province	Virginia	 
Country or region	United States	 
Application version	Thu 10/18/2018 0:19:19.04 UTC (factoryvm-az361) [Build 41682] [Repo Intercom] [Branch prod] [Commit 0da15ddb4e2ea9f3f2b01674eae3a93e96d3a159] 	 
SDK version	dotnet:2.7.2-23439	 
Cloud role name	bc-directline-eastus	 
Cloud role instance	RD0003FFA9AB0C	 
Operation Id	6c4c572019aa2440bfb1d23cf8c8aa04	 
Parent Id	|6c4c572019aa2440bfb1d23cf8c8aa04.d3b48b4f_	 
Problem Id	Microsoft.Bot.Schema.BotTimeoutException at Microsoft.Bot.ChannelConnector.BotAPI+<PostActivityToBotAsync>d__31.MoveNext	
Assembly	Microsoft.Bot.ChannelConnector, Version=3.2.2.4, Culture=neutral, PublicKeyToken=null

**Comment by PrernaGupta1** [comment]
Exception 1 :
Event time	10/22/2018, 4:33:37 PM	 
Message	POST to BotCR-7220-Dev failed: POST to the bot's endpoint failed with HTTP status 503 POST to the bot's endpoint failed with HTTP status 503	 
Exception type	System.Exception	 
Failed method	Microsoft.Bot.ChannelConnector.BotAPI+<PostActivityToBotAsync>d__31.MoveNext	 
Sample rate	1	 
Telemetry type	exception	 
Device type	PC	 
Client IP address	0.0.0.0	 
City	Singapore	 
State or province	Central Singapore Community Development Council	 
Country or region	Singapore	 
Application version	Thu 10/18/2018 0:19:19.04 UTC (factoryvm-az361) [Build 41682] [Repo Intercom] [Branch prod] [Commit 0da15ddb4e2ea9f3f2b01674eae3a93e96d3a159] 	 
SDK version	dotnet:2.7.2-23439	 
Cloud role name	bc-directline-southeastasia	 
Cloud role instance	RD00155D63EFA1	 
Operation Id	b88847881033c74fbaf4a9d48d003d76	 
Parent Id	|b88847881033c74fbaf4a9d48d003d76.729dcbb0_	 
Problem Id	System.Exception at Microsoft.Bot.ChannelConnector.BotAPI+<PostActivityToBotAsync>d__31.MoveNext	
Assembly	Microsoft.Bot.ChannelConnector, Version=3.2.2.4, Culture=neutral, PublicKeyToken=null	

Exception 2 :

Event time	10/22/2018, 4:33:05 PM	 
Message	POST to BotCR-7220-Dev timed out after 15s	 
Exception type	Microsoft.Bot.Schema.BotTimeoutException	 
Failed method	Microsoft.Bot.ChannelConnector.BotAPI+<PostActivityToBotAsync>d__31.MoveNext	 
Sample rate	1	 
Telemetry type	exception	 
Device type	PC	 
Client IP address	0.0.0.0	 
City	Boydton	 
State or province	Virginia	 
Country or region	United States	 
Application version	Thu 10/18/2018 0:19:19.04 UTC (factoryvm-az361) [Build 41682] [Repo Intercom] [Branch prod] [Commit 0da15ddb4e2ea9f3f2b01674eae3a93e96d3a159] 	 
SDK version	dotnet:2.7.2-23439	 
Cloud role name	bc-directline-eastus	 
Cloud role instance	RD0003FFA9AB0C	 
Operation Id	6c4c572019aa2440bfb1d23cf8c8aa04	 
Parent Id	|6c4c572019aa2440bfb1d23cf8c8aa04.d3b48b4f_	 
Problem Id	Microsoft.Bot.Schema.BotTimeoutException at Microsoft.Bot.ChannelConnector.BotAPI+<PostActivityToBotAsync>d__31.MoveNext	
Assembly	Microsoft.Bot.ChannelConnector, Version=3.2.2.4, Culture=neutral, PublicKeyToken=null

**Comment by sgellock** [comment]
This issue was moved to Microsoft/BotBuilder-V3#37

**Comment by yochay** [comment]
This issue was moved to Microsoft/BotBuilder-V3#39
