### ISSUE TITLE
Middleware with session.beginDialog

### ISSUE THREAD

**Issue by arnaldobadin** [Microsoft/BotBuilder#5117]
So, I'm calling session.beginDialog() into a middleware:

```
    // main_middleware
    bot.use({botbuilder :  [
        (session, next) => {
            ... code ...
            session.beginDialog(...);
        },
        (session, next) => {
            ... don't even get there ...
            ... do stuff ...
        }
    }
]);
```
Works nicely, the problem is: when the dialog called by session.beginDialog(...) finish, it won't return to the next function in middle waterfall schema.

The flow should be like that: func1 -> beginDialog -> func2.
But don't even get to func2, just stops.

**Comment by nyxsys** [comment]
Can you go a bit deeper on how you are using your middleware stack? What is in the actual bot code vs your middleware?

**Comment by yochay** [comment]
Thank you for your questions about using the Bot Framework SDK.

The goal of this github repo issue tracker is to identify code defects and enhancement to the SDK. The Bot Framework has a great community. We recommend asking questions on - https://stackoverflow.com/questions/tagged/botframework.

Closing this issue.
