### ISSUE TITLE
Issues with published bot in Azure

### ISSUE THREAD

**Issue by Rykimaruh** [Microsoft/BotBuilder#5119]
Hi,

I'm having a published bot in Azure throw the annoying "Sorry, my bot code is having an issue" when testing it.

I checked int the App Insight of the bot and this is the message that pops up everytime:

> POST to OurPeopleBot failed: POST to the bot&#39;s endpoint failed with HTTP status 500
> Problem Id:System.Exception at Microsoft.Bot.ChannelConnector.BotAPI+&lt;PostActivityToBotAsync&gt;d__31.MoveNext

Any help appreciated!

**Comment by nyxsys** [comment]
This means there's an internal issue with your bot code, so you will have to [run a local setup with ngrok](https://blog.botframework.com/2017/10/19/debug-channel-locally-using-ngrok/) to debug it directly and figure out whats going wrong.

**Comment by yochay** [comment]
Thank you for your questions about using the Bot Framework SDK.

The goal of this github repo issue tracker is to identify code defects and enhancement to the SDK. The Bot Framework has a great community. We recommend asking questions on - https://stackoverflow.com/questions/tagged/botframework.

Closing this issue.
