### ISSUE TITLE
Add a Duration property to media card types

### ISSUE THREAD

**Issue by yochay** [Microsoft/BotBuilder#5120]
_From @JonathanFingold on October 25, 2018 19:28_

**Is your feature request related to a problem? Please describe.**
The [cards spec](https://github.com/Microsoft/BotBuilder/blob/master/specs/botframework-activity/botframework-cards.md) was [updated to include a media duration](https://github.com/Microsoft/BotBuilder/pull/5094). I can't find a corresponding member in the Microsoft.Bot.Schema namespace, or a PR containing one.

**Describe the solution you'd like**
1. Add a `Duration` property to media cards.
1. Bonus: update the **06.using-cards** samples.

**Describe alternatives you've considered**
Just pointing users to the Card schema spec.

**Additional context**
https://github.com/Microsoft/BotBuilder/pull/5094

[enhancement]

_Copied from original issue: Microsoft/botbuilder-dotnet#1062_

**Comment by yochay** [comment]
Need to tag botbuilder and regenerate schema lib for C# and JS (and Java , Python).

**Comment by yochay** [comment]
_From @JonathanFingold on October 25, 2018 21:14_

@yochay Do you have an ETA? I was hoping to use this issue to flag when the fix was in, so I could update the docs.

**Comment by yochay** [comment]
Moved from https://github.com/Microsoft/botbuilder-dotnet/issues/1062 
Requires updates for all SDK Language.

**Comment by sgellock** [comment]
General consensus in standup is that you should do this and Kernel Major will review.

**Comment by sgellock** [comment]
Per conversations with @yochay, resolving won't fix

**Comment by JonathanFingold** [comment]
@sgellock , I still need to do something about this in the docs. What is the gist of the conversation you had with Yochay?

**Comment by yochay** [comment]
@sgellock  and @JonathanFingold  this should be resolved as **fixed**. Duration is in the the _schema_ for both JS and C# for 4 types of cards - see pointers to Schema and classes here under. 

Duration is missing from WebChat control. @compulim has more info on that. 

We can update the Cards sample, but without ability to show the duration in the cards (See WebChat comment above), there is little value in it. 

@JonathanFingold , what updates do you need for the docs? Can you point to the current docs to get idea of how you refer to other properties on cards?  

### schema updates
- AnimationCards:  ([C#](https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Swagger/ConnectorAPI.json#L1539)); [JS](https://github.com/Microsoft/botbuilder-js/blob/master/libraries/swagger/ConnectorAPI.json#L1531)

- AudioCard: [C#](https://github.com/Microsoft/botbuilder-js/blob/master/libraries/swagger/ConnectorAPI.json#L1627); [JS](https://github.com/Microsoft/botbuilder-js/blob/master/libraries/swagger/ConnectorAPI.json#L1619)

- MediaCard: [C#](https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Swagger/ConnectorAPI.json#L1723); [JS](https://github.com/Microsoft/botbuilder-js/blob/master/libraries/swagger/ConnectorAPI.json#L1715)

- VideoCard:  [C#](https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Swagger/ConnectorAPI.json#L1952) ; [JS](https://github.com/Microsoft/botbuilder-js/blob/master/libraries/swagger/ConnectorAPI.json#L1944)

### autogenerated classes include Duration
- AnimationCard: [C#](https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Schema/AnimationCard.cs#L66) ; [JS](https://github.com/Microsoft/botbuilder-js/blob/master/libraries/botframework-schema/src/index.ts#L748)

- AudioCard: [C#](https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Schema/AudioCard.cs#L66) ; [JS](https://github.com/Microsoft/botbuilder-js/blob/master/libraries/botframework-schema/src/index.ts#L804)

- MediaCard: [C#](https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Schema/MediaCard.cs#L66) ; [JS](https://github.com/Microsoft/botbuilder-js/blob/master/libraries/botframework-schema/src/index.ts#L890)

- VideoCard: [C#](https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Schema/VideoCard.cs#L66) ; [JS](https://github.com/Microsoft/botbuilder-js/blob/master/libraries/botframework-schema/src/index.ts#L1096)

**Comment by JonathanFingold** [comment]
@yochay I think the changes in the Schema namespace address my concern, which was mainly about the mismatch between the spec and the SDK.
