### ISSUE TITLE
DCR: Add ability to create a ConversationReference from a TurnContext + ResourceResponse

### ISSUE THREAD

**Issue by yochay** [Microsoft/BotBuilder#5128]
_From @benbrown on October 29, 2018 20:0_

SendActivities returns an array of ResourceResponses.

These ResourceResponses contain the activity id, which is a key value needed to call updateActivity or deleteActivity in the future. However, ResourceResponse does not necessarily contain all of the information required to construct a ConversationReference needed to actually call these methods.

Since the type of messages that will be deleted or updated are most likely to be those sent by the bot itself, we need to provide an easy to use method that takes a ResourceResponse returned from sendActivity and combines it with a TurnContext to create a reusable (and data-complete) ConversationReference.

_Copied from original issue: Microsoft/botbuilder-js#586_

**Comment by yochay** [comment]
@benbrown , please ping @johnataylor  once you are done with this.

**Comment by benbrown** [comment]
@johnataylor see attached PR on the Javascript repo! Turned out to be a very simple little function.

NOTE: The emulator does not support the update or delete activity methods, making this tricky to test.

**Comment by benbrown** [comment]
Re-opening so that we can track the c# version!
