### ISSUE TITLE
Directline Service Down/Transient Failures

### ISSUE THREAD

**Issue by brett-1hw** [Microsoft/BotBuilder#5133]
Bot Info:
SDK Platform: .NET
SDK Version: 3.16.1.40077
Active Channels: Directline

Issue Description
Directline API returns errors fairly consistently when creating new conversations and attempting to connect to a WebSocket stream URL. 

![image](https://user-images.githubusercontent.com/20304811/47887393-83b29b00-de15-11e8-81b4-ed04f134a5b2.png)

Given that all our bots seem affected, I'm assuming an outage though the Azure Status page does not have any information indicating. Our services appear to have been down for at least 4-5 hours now. 

In addition, our logs indicate these types of errors have been occurring sporadically throughout the last few weeks.

**Comment by vbhatt** [comment]
Started again:
Error: POST to 'https://directline.botframework.com/v3/conversations/48dMN4ewvowBsWn4J4op72/activities/E8Mul8N9fIL' failed: [500]  
    at new Error (native)
    at Request._callback Error: POST to 'https://directline.botframework.com/v3/conversations/48dMN4ewvowBsWn4J4op72/activities/E8Mul8N9fIL' failed: [500]  
    at new Error (native)
    at Request._callback

**Comment by vincec-msft** [comment]
@vbhatt , thanks for the report. This was not a recurrence of yesterday's problem.

At 2018-11-02T19:48:00Z a machine in the EastUS datacenter lost its connection to the caching layer. The platform automatically detected the problem and restarted the machine 19:51 and all errors had stopped by 19:52.

We're looking at ways to remove sick machines from rotation more quickly.

**Comment by vincec-msft** [comment]
@brett-1hw , we deployed a hotfix last night at 2018-11-02T02:30:00Z and the system has been stable since then.

I'm not sure why the Azure status page was not updated. The issue was posted here:

https://ms.portal.azure.com/#blade/Microsoft_Azure_Health/AzureHealthBrowseBlade/serviceIssues
