### ISSUE TITLE
Skype id encrypt (skype id change or encrypt when service receive a request from any user)

### ISSUE THREAD

**Issue by inornos** [Microsoft/BotBuilder#514]
my Skype id change when it reaches to the service

My skype id is **fssxyz** but when service receive my message and i check the log for me it showing me this **1KiQp6oLcQ8sVyB4uswRvIy6DSOkzBzg4_OKPJFXlf-c** this skype id as request
please help i'm in problem

**Comment by tomlm** [comment]
This is a change which was made by the Skype team.  They now encrypt the skypeids.  You can still send to them, but when you receive them they will be unique per bot.
