### ISSUE TITLE
Skype bot error

### ISSUE THREAD

**Issue by angeluskinyua** [Microsoft/BotBuilder#5140]
Skype for Business could not reach the bot. Please contact admin of the bot for help.

**Comment by sgellock** [comment]
@angeluskinyua I'm closing this as there really isn't enough data here for the team to debug or to provide assistance.  Additionally, this repo is not intended for framework bugs.  We ask that you open bugs in the specific language repos, or if you are looking for specific help, we have an active community on StackOverflow.com

Here are a list of all the language specific repos that might be helpful
https://github.com/Microsoft/botbuilder/blob/master/README.md
