### ISSUE TITLE
add new GetAnswersAsync method with QnAMakerOptions param

### ISSUE THREAD

**Issue by sgellock** [Microsoft/BotBuilder#5143]
## Issue
There is an issue and a PR to track this work in the dotnet repo
https://github.com/Microsoft/botbuilder-dotnet/issues/1083
https://github.com/Microsoft/botbuilder-dotnet/pull/1099

We need to also do this work for the other language SDKs

## Tracking Status
**Dotnet SDK**
- [ ] PR
- [ ] Merged

**Javascript SDK**
- [ ] PR
- [ ] Merged

**Java SDK**
- [ ] PR
- [ ] Merged

**Python SDK**
- [ ] PR
- [ ] Merged

**Docs**
- [ ] PR
- [ ] Merged

[dcr]

**Comment by vishwacsena** [comment]
@MeghaChaitanya FYI

**Comment by johnataylor** [comment]
Fixed by https://github.com/Microsoft/botbuilder-js/pull/683

Specifically fixed for C# and JavaScript. When this work is done for Java and Python it will follow this model. There shouldn't be any need to track this specific issue outside of porting the whole component.
