### ISSUE TITLE
Duplicate Appinsight Events registered by QnaMaker based Bot

### ISSUE THREAD

**Issue by vbhatt** [Microsoft/BotBuilder#5145]
I am seeing duplicate AppInsight events registered for the same question. The events do not have the same timestamp. I have tried using different channels, i.e., TestChat, WebChat, DirectLine, Telegram but get the same result of duplicate events in Appinsight. However, I see only a single event in the "Information" logging output window on Azure.

**Comment by jwiley84** [comment]
This repro is currently only taking Design Change Requests (DCR) issues. For submitting **bug fixes** and **feature requests**, please go to one of the following repos:

- **Bot Builder V4 SDK**
    - [**C#** (stable release)](https://github.com/microsoft/botbuilder-dotnet)
    - [**JS** (stable release)](https://github.com/microsoft/botbuilder-js)
    - [**Java** (preview release)](https://github.com/microsoft/botbuilder-java)
    - [**Python** (preview release)](https://github.com/microsoft/botbuilder-python).
