### ISSUE TITLE
how to get sender name (how to get name of the person who send message on the skype bot)

### ISSUE THREAD

**Issue by inornos** [Microsoft/BotBuilder#515]
how to get name of the person who send me message on Skype bot
i want manage log with sender name time and message so anyone help me to get sender name who send the message on my skype bot

**Comment by tomlm** [comment]
The sender name should be in the From.Name field

**Comment by inornos** [comment]
ya i know i'm using From.Address Property but its encrypted so i'm not identifying my user please help me

**Comment by inornos** [comment]
my Skype id change when it reaches to the service

My skype id is fssxyz but when service receive my message and i check the log for me it showing me this 1KiQp6oLcQ8sVyB4uswRvIy6DSOkzBzg4_OKPJFXlf-c this as skype id as request
please help i'm in problem

**Comment by tomlm** [comment]
Yes, we don’t expose skype id or live id to bots anymore. Instead we send them pairwise identity that is calculated basing on encrypting (bot id + user id) pair.
But we still accept all the identities for incoming to Skype messages (such as 8:skypeId, 1:live@email.com, 19:threadId or 29:pairwiseId)
Regardless the .Name field should have user name.

**Comment by safiresh** [comment]
@tomlm  We can't identify based on .Name because its not unique user can change any time. we can't track which user order this like that. We need to map our internal system too.
