### ISSUE TITLE
"-" character markdown error when send message

### ISSUE THREAD

**Issue by huyjack178** [Microsoft/BotBuilder#5159]
I got the Bad Request exception when send this message to Bot Service
Hello \n - This is message

I figured out the problem is "-" character, stand for List in Markdown concept. Can anyone help me?

**Comment by jwiley84** [comment]
This repro is currently only taking Design Change Requests (DCR) issues. For submitting **bug fixes** and **feature requests**, please go to the following repos **[Botbuilder-dotnet](https://github.com/Microsoft/botbuilder-dotnet)** or **[Botbuilder-js](https://github.com/Microsoft/Botbuilder-js)**.
