### ISSUE TITLE
[Question][C#]Proactive Bot Example

### ISSUE THREAD

**Issue by alex182** [Microsoft/BotBuilder#516]
I am trying to create a proactive bot that forwards the message that is sent to it from User1 to User2.  Is there example code for this?  Is this possible using the emulator or do I need to put my bot on Azure? 
[C#]

**Comment by tomlm** [comment]
You can do this by simply creating a new message.
`
Message message = new Message("text")
{ 
   From = bot,
   To = user
}
`
NOTE: you can only send a message to a user that has already interacted with your bot.
