### ISSUE TITLE
Slack integration: output format

### ISSUE THREAD

**Issue by loretoparisi** [Microsoft/BotBuilder#517]
When in the slack integration, the output of BotBuilder.session.send seems to be `text`, while within Slack application the rendered text seems to be `html`. 
Like having as output a sentence of more lines (separator is `\n`), the slack bot will print a one line string, ignoring the return chars. Do I have to convert to html entities before sending contents?

**Comment by tomlm** [comment]
The output is interpreted as markdown. With markdown, you need a blank line to signify paragraph break. 

This means the following:
one
two

three

Will render as:
one two
three

**Comment by loretoparisi** [comment]
@tomlm all right that makes sense, so I have to replace `\n` to `\n\n`.
