### ISSUE TITLE
Problem with Skype Web Control

### ISSUE THREAD

**Issue by odysseus1973** [Microsoft/BotBuilder#5172]
Hi!

Skype Web Control Skype web control does not show icons
![google chrome 2018-11-13 18 02 43](https://user-images.githubusercontent.com/7000262/48422440-b9d61000-e76f-11e8-9eb3-022e0bdb5bec.png)

What could be the problem?

```
<span class="skype-button bubble " data-bot-id="myid"></span>
<script src="https://swc.cdn.skype.com/sdk/v1/sdk.min.js"></script>
```

Thanks!

**Comment by jwiley84** [comment]
This repro is currently only taking Design Change Requests (DCR) issues. For submitting **bug fixes** and **feature requests** related to the skype channel, please go to the following repo **[BotFramework-Services]**(https://github.com/Microsoft/BotFramework-Services).
