### ISSUE TITLE
EXTERNAL: Enable ABS to enable Application Insights

### ISSUE THREAD

**Issue by Kaiqb** [Microsoft/BotBuilder#5174]
https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Ffuselabs.visualstudio.com%2FBotFramework%2F_workitems%2Fedit%2F25693&data=02%7C01%7CKamran.Iqbal%40microsoft.com%7C7a7bdf3fe39b4632c60a08d64699228c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636774020865216917&sdata=AX0LCzxWGGPg%2F%2FvFGmrYC%2BHEjuu8ZCiJkql7XpITL%2BE%3D&reserved=0

**Comment by yochay** [comment]
This is complete from ABS side.

We are also adding the telemetry dashboards to the generator and to ARM templates.
