### ISSUE TITLE
[C#] 1.2.4 Localization issue

### ISSUE THREAD

**Issue by rlilov** [Microsoft/BotBuilder#518]
I have localized by bot with English (neutral language) + 2 other languages using 2 Forms, chained with ContinueWith. First form takes language choice from user and passes it to the second form. All worked very well with 1.2.3 version.

When I installed 1.2.4, selecting any of the none English languages, results in the bot being stuck at the end of language choice form. This behavior is the same in emulator and when deployed to Azure.
I have read release notes announcing: "Missing resources causes an error to be thrown", but I do not seem to get any errors. Inspecting my resource files, I can not see anything obviously missing.

Will appreciate some guidance where to look for a clue .

**Comment by willportnoy** [comment]
You might temporarily turn off "tools, options, debugging, enable just my code" and turn on "break when thrown" on all "common language runtime exceptions" in Visual Studio to catch the exception to get more information.

**Comment by chrimc62** [comment]
The exception (if it is occurring) will list the missing resources.

**Comment by rlilov** [comment]
Thanks
Exception that is thrown is: departed is one of my terms, can not immediately relate this to missing resource
 
  System.ArgumentException occurred
  HResult=-2147024809
  Message=parsing "(\b1\b)|(__qqqq__)\b)|((?:departeds\s+?))" - Too many )'s.
  Source=System
  StackTrace:
       at System.Text.RegularExpressions.RegexParser.ScanRegex()
  InnerException:

**Comment by rlilov** [comment]
my terms were translated sometimes adding space after question mark i.e. "term ?"
1.2.3 was tolerant on this, 1.2.4 obviously not
I removed the spaces and all works.
thanks a lot for your assistance, my problem is solved.
