### ISSUE TITLE
Azure Web Bot App Scoring System, is there a way to get confidence score which exactly using inside qnamaker? currently bot only returns prediction score.

### ISSUE THREAD

**Issue by nmssalman** [Microsoft/BotBuilder#5180]

**Comment by jwiley84** [comment]
This repo is currently only taking Design Change Requests (DCR) issues. For submitting **bug fixes** and **feature requests**, please go to the following repo [Botbuilder-CognitiveServices](https://github.com/Microsoft/BotBuilder-CognitiveServices).
