### ISSUE TITLE
Luis api- create application which is public by default

### ISSUE THREAD

**Issue by DeepakDonde** [Microsoft/BotBuilder#5181]
I am trying to create app on Luis which is accessible by non-contributors so that they can

 query this app with a valid key. I am able to create app with the following request body

`{
	"name": "MyFirstDummyApp",
	"description": "This is my first dummy application",
	"culture": "en-us",
	"usageScenario": "IoT",
	"domain": "Comics",
	"initialVersionId": "1.0"
}`

But i don't find any flag or key in request body which can be use to make app public or non-public.

Below is the screenshot from Luis app information under manage tab:
![luis_public](https://user-images.githubusercontent.com/14233168/48930052-c139ae00-ef13-11e8-82aa-cbc606b1b541.PNG)

**Comment by jwiley84** [comment]
This repo is currently only taking Design Change Requests (DCR) issues. For submitting **bug fixes** and **feature requests**, please go to the following repo [Botbuilder-CognitiveServices](https://github.com/Microsoft/BotBuilder-CognitiveServices).
