### ISSUE TITLE
Enable channel for Google Hangouts

### ISSUE THREAD

**Issue by maqnirajj** [Microsoft/BotBuilder#5182]
## Is there any plan to support Google Hangouts as a channel in Bot Framework?
If no, is there please suggest recommended workaround. I read through related issues which were closed since V4 came out. However, I don't see any recommended solution which can work at scale.

**Comment by jwiley84** [comment]
This repo is currently only taking Design Change Requests (DCR) issues. For submitting **bug fixes** and **feature requests**, please go to the following repo [BotFramework-Services](https://github.com/Microsoft/BotFramework-Services).
