### ISSUE TITLE
[Question] How to display Suggested Action Cards on Skype for Business?

### ISSUE THREAD

**Issue by maqnirajj** [Microsoft/BotBuilder#5183]
## How to display Suggested Action Cards on Skype for Business?

I know current version does not support cards. Is there a workaround?

**Comment by jwiley84** [comment]
This repo is currently only taking Design Change Requests (DCR) issues. For submitting **bug fixes** and **feature requests**, please go to the following repo [BotFramework-Services](https://github.com/Microsoft/BotFramework-Services).
