### ISSUE TITLE
Client certificate authentication in SDK

### ISSUE THREAD

**Issue by ahleeny** [Microsoft/BotBuilder#5184]
The current bot builder SDK only support Client ID and Secret and not client certificate. Is there plans on incorporating this into the SDK? Appreciate if you can help if you have found a way around this issue as well.

**Comment by benbrown** [comment]
We have no plans to add this at this time.

**Comment by ahleeny** [comment]
@benbrown any guidance you can give specifically for cert authentication?

I have done some research on cert authentication and did a small test by following the guide below:
-	https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow
-	https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-certificate-credentials
-	Uploaded certificate into the chatbot app in Azure and manifest was automatically created. 

However, it seems like the self-generated JWT token does not work when authenticating with Azure. Appreciate if u can help.
