### ISSUE TITLE
Ms Teams channel giving error when used with Cosmos DB for state management - Enterprise Bot Template V4

### ISSUE THREAD

**Issue by sw-ms-roshanparmar** [Microsoft/BotBuilder#5185]
## MS Teams channel is giving exception when Comsmos DB is used for state managment in Enterprise Bot Template V4.

**Description**

Currently I am using Enterprise Bot Template v4 SDK C# for developing the bot. I am using Cosmos DB for user state management. Everything works fine with enterprise bot template , but when configure the bot on MS Teams channel , at that point of time Bot fails to write the state data to Cosmos DB and gives an error.

**What is actually happening..**

Cosmos DB(document DB) handles every individual row/data uniquely by "id" column. Cosmos DB is having a limitation of the length of the "Id" which is 255 characters. 
Now, when bot tries to store the user state for MS Teams channel in cosmos db , at that point of time Enterprise bot template/ bot framework v4 automatically creates an unique id which has length more than 255 characters. So this gives an exception in code.

Please someone look into this issue as this is a blocking issue for ms teams.

As a workaround of this issue i managed to store the state in blob storage and deployed my bot.

**Comment by jwiley84** [comment]
This repo is currently only taking Design Change Requests (DCR) issues. For submitting **bug fixes** and **feature requests**, please go to the following repo [BotFramework-Services](https://github.com/Microsoft/BotFramework-Services).
