### ISSUE TITLE
Ability to wrap text in buttons on cards

### ISSUE THREAD

**Issue by dividor** [Microsoft/BotBuilder#5192]
## Issue
We are using QnA maker to expose FAQs in our bot. For cases where we don't have a very high-scoring match, we present the user with the top 5 nearest questions as buttons, so they can choose their answer (if they confirm the answer, we use that to further train the QnA model).

The issue is, the text in buttons does not wrap, it gets truncated. This means that on mobile and even sometimes on Teams desktop, the user can be confused as they don't have the full question text for each question candidate.

We have tried other options, eg (i) using adaptive cards and selectAction to make the question candidates look like links. Trouble is, they don't look like buttons so users get confused; (ii) Using a carousel with a card for each question candidate. Again, in usability testing, users got confused.

Bottom line - in this scenario where we want to user to choose from a set of FAQs, users like choosing from a vertical stack of buttons, and so we really need to be able to wrap text and show the full question.

In fact, my question would be, why do we truncate text in buttons as the default? By truncating it makes the button useless as we lose information.

This issue is to ask if we can activate text wrapping for buttons, ideally in all cards, but our immediate need is for adaptive cards.

SDK: nodejs
Channels: Teams desktop+mobile; Webchat (though we can use CSS to wrap text in that channel)

## Proposed change
Enable text wrapping in adaptive card buttons

## Component Impact 
botbuilde.CardFactory.adaptiveCard

## Customer Impact 
In our case, a big usability hit on FAQ chatbots

## SDK
javascript_nodejs (latest)

[dcr]

**Comment by jwiley84** [comment]
This repo is currently only taking Design Change Requests (DCR) issues. For submitting **bug fixes** and **feature requests**, please go to the following repo [Botframework-Services](https://github.com/Microsoft/BotFramework-Services).
