### ISSUE TITLE
Bot Builder Dynamic Field Error

### ISSUE THREAD

**Issue by chocvanstraw** [Microsoft/BotBuilder#520]
I just upgraded to Bot.Builder 1.2.4 and am getting the following error when building dynamic fields:
<pre>
parsing "(\b1\b)|(__qqqq__)\b)|(__qqqq__)" - Too many )'s.
</pre>
<pre>
undefined:
   at Microsoft.Bot.Builder.FormFlow.FormDialog`1+<MessageReceived>d__14.MoveNext (Microsoft.Bot.Builder, Version=1.2.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at 
System.Text.RegularExpressions.RegexParser.ScanRegex
</pre>

This worked fine prior to the upgrade.  

Below is the relevant code
<pre>
.Field(
new FieldReflector<OrderDialog>(nameof(Restaurant))
.SetType(null)
.SetValidate(ValidateRestaurantDelegate)
.SetDefine(SearchRestaurantsDelegate)
)
</pre>
I originally thought it might be an issue with the mark down I was using to display a map link but I receive the same error if I remove all the mark down
<pre>
DefineAsyncDelegate<OrderDialog> SearchRestaurantsDelegate = (state, field) =>
{
        field.RemoveValues();
        if (state.City != null && state.City.Length > 0)
        {
            var stores = new RestaurantApi();
            var results = stores.GetByCity(state.City);
            foreach (var result in results)
            {
                string map = String.Format("https://maps.google.com?q={0},{1}", result.Latitude, result.Longitude);
                string restaurantId = result.RestaurantId.ToString();
                string text = String.Format("{0}-{1} [map] ({2})", result.State, result.Address1, map);
                field.AddDescription(restaurantId, text).AddTerms(restaurantId, "");
            }
        }
        return Task.FromResult(true); 
};
</pre>

**Comment by chrimc62** [comment]
Thanks for the bug report.  AddTerms are the terms people can type to match that entry.  Ideally in this case you would either just remove AddTerms altogether or call it with no terms, i.e. AddTerms(restaurantId).  For now you could just put a nonsense term there, like qqqqq.  I'll fix it in the next release so that no terms works.
