### ISSUE TITLE
JSON data displays as part of the message text in Telegram

### ISSUE THREAD

**Issue by designdit** [Microsoft/BotBuilder#521]
I'm using BotConnector to send messages and have tried a number of formats for Telegram, but none works as expected.  Any suggestions on what else to try?  Do some/all of the quotes need to be escaped when using JSON.stringify or should the message parameters be sent in a different format?

Here are a couple of ways I've tried (using node.js botbuilder version 1.3.21):

Option 1. 

         session.send(JSON.stringify({
           
            channelData:
            {
                "method": "sendSticker",
                "parameters":
                {
                    "sticker":
                    {
                        "url": "https://upload.wikimedia.org/wikipedia/commons/3/33/LittleCarron.gif",
                        "mediaType": "image/gif"
                    }
                }
            }
        }));

This results in the message being sent to the Telegram client but it includes the stringified text above the animated gif.  The message appears in Telegram as follows:

{"channelData:{"method": "sendSticker","parameters":{"sticker":{"url": "https://upload.wikimedia.org /wikipedia/commons/3/33/LittleCarron.gif","mediaType": "image/gif"}}}}
               ... and below this text, the animated gif is displayed (gif is displayed correctly)

Option 2.  If I remove the "JSON.stringify" function, the message is sent to the Telegram client and there is no text (good), but the gif is not animated, it is a still picture.

Option 3.  If I place quotes around the entire JSON object or escape the quotes throughout the message with a \, the message does not come through (the error message is that the bot is having a problem responding right now).

Appreciate any suggestions on the correct formatting to display the animated gif without the channelData text appearing in the message ("Custom Telegram messages #283" indicates that option 1 or 2 should work but I seem to be missing something). 

Thanks

**Comment by eanders-MS** [comment]
Try this:

```javascript
session.sendMessage({
		"method": "sendSticker",
		"parameters":
		{
			"sticker":
			{
				"url": "https://upload.wikimedia.org/wikipedia/commons/3/33/LittleCarron.gif",
				"mediaType": "image/gif"
			}
		}
	}
});
```

**Comment by eanders-MS** [comment]
Unsure why Option 2 didn't work for you; it should have, I think. I will investigate that one.

**Comment by eanders-MS** [comment]
Option 2 worked for me in Telegram desktop and web (gif was animating), but returned a non-animated gif to the iOS client. I had better results sending the gif as a document:
```javascript
session.sendMessage({
	method: "sendDocument",
	parameters: {
		document: {
			url: "https://upload.wikimedia.org/wikipedia/commons/3/33/LittleCarron.gif"
		}
	}
});
```
That one animated on all clients.

**Comment by eanders-MS** [comment]
Closing issue. If you're still having problems please comment here and I will reopen.

**Comment by designdit** [comment]
Thank you for your quick replies!  I tried the "sendDocument" suggestion on Telegram and it worked great. Had an issue with the initial sendMessage suggestion (without the document) on an Android Telegram client - received the "bot is having a problem" error message. Glad to have the document solution. Thanks.

**Comment by designdit** [comment]
Hi, (in case anyone else gives it a try) the first "sendMessage" suggestion has an extra right curly bracket...I missed that when I first tried it.  No longer getting the "bot is having a problem error" after removing it, but it results in a still picture and not an animated gif on my Android Telegram client.

**Comment by eanders-MS** [comment]
Edited first "sendMessage" suggestion to remove extra right curly bracket, thanks.
