### ISSUE TITLE
HTTP error not authorized in webchat

### ISSUE THREAD

**Issue by OBrien1510** [Microsoft/BotBuilder#5215]
Bot Version: 3.15.3
.NET Version: 4.7

I've been working on the bot for sometime now and I recently took a few weeks off. The bot was working perfectly on skype before I left (I rarely tested it on webchat but I assume if it worked on skype it would work in webchat).  When I came back the bot had stopped working and wouldn't let me send a message to it. In the channels tab on azure, I was getting the error HTTP status code: Not Authorized. It works perfectly well locally. The endpoint it correct and is set to https. 

The app ID is a59e7670-6105-46bb-a00e-9c81cfe3b913. I can't see why the password would suddenly be incorrect but I haven't tried regenerating the password, but I need to ask someone above me to do that so I'm trying to leave that as a last resort for now.

Nuget Packages:

`<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="AdaptiveCards" version="1.0.3" targetFramework="net461" />
  <package id="Autofac" version="4.8.1" targetFramework="net461" />
  <package id="Chronic.Signed" version="0.3.2" targetFramework="net461" />
  <package id="DnsClient" version="1.1.1" targetFramework="net461" />
  <package id="GData.Spreadsheets.Helpers" version="2.2.0.0" targetFramework="net461" />
  <package id="Google.Apis" version="1.35.1" targetFramework="net461" />
  <package id="Google.Apis.Auth" version="1.35.1" targetFramework="net461" />
  <package id="Google.Apis.Core" version="1.35.1" targetFramework="net461" />
  <package id="Google.Apis.Sheets.v4" version="1.34.0.1240" targetFramework="net461" />
  <package id="Google.GData.Client" version="2.2.0.0" targetFramework="net461" />
  <package id="Google.GData.Extensions" version="2.2.0.0" targetFramework="net461" />
  <package id="Google.GData.Spreadsheets" version="2.2.0.0" targetFramework="net461" />
  <package id="Microsoft.AspNet.WebApi" version="5.2.6" targetFramework="net461" />
  <package id="Microsoft.AspNet.WebApi.Client" version="5.2.6" targetFramework="net461" />
  <package id="Microsoft.AspNet.WebApi.Core" version="5.2.6" targetFramework="net461" />
  <package id="Microsoft.AspNet.WebApi.WebHost" version="5.2.6" targetFramework="net461" />
  <package id="Microsoft.Azure.CognitiveServices.Language.LUIS.Authoring" version="2.0.0" targetFramework="net461" />
  <package id="Microsoft.Azure.CognitiveServices.Language.LUIS.Runtime" version="2.0.0" targetFramework="net461" />
  <package id="Microsoft.Azure.CognitiveServices.Language.TextAnalytics" version="2.8.0-preview" targetFramework="net461" />
  <package id="Microsoft.Azure.KeyVault.Core" version="1.0.0" targetFramework="net461" />
  <package id="Microsoft.Bot.Builder" version="3.15.3" targetFramework="net461" />
  <package id="Microsoft.Bot.Builder.CognitiveServices" version="1.1.7" targetFramework="net461" />
  <package id="Microsoft.Bot.Builder.PersonalityChat" version="3.0.0-alpha-m1.0" targetFramework="net461" />
  <package id="Microsoft.Bot.Builder.PersonalityChat.Core" version="1.0.0-alpha-m1.0" targetFramework="net461" />
  <package id="Microsoft.Bot.Connector" version="3.15.3" targetFramework="net461" />
  <package id="Microsoft.Bot.Connector.Teams" version="0.9.0" targetFramework="net461" />
  <package id="Microsoft.CognitiveServices.Speech" version="0.5.0" targetFramework="net461" />
  <package id="Microsoft.CSharp" version="4.5.0" targetFramework="net461" />
  <package id="Microsoft.IdentityModel.JsonWebTokens" version="5.2.4" targetFramework="net461" />
  <package id="Microsoft.IdentityModel.Logging" version="5.2.4" targetFramework="net461" />
  <package id="Microsoft.IdentityModel.Protocol.Extensions" version="1.0.4.403061554" targetFramework="net461" />
  <package id="Microsoft.IdentityModel.Protocols" version="5.2.4" targetFramework="net461" />
  <package id="Microsoft.IdentityModel.Protocols.OpenIdConnect" version="5.2.4" targetFramework="net461" />
  <package id="Microsoft.IdentityModel.Tokens" version="5.2.4" targetFramework="net461" />
  <package id="Microsoft.Rest.ClientRuntime" version="2.3.17" targetFramework="net461" />
  <package id="Microsoft.Rest.ClientRuntime.Azure" version="3.3.18" targetFramework="net461" />
  <package id="Microsoft.WindowsAzure.ConfigurationManager" version="3.2.3" targetFramework="net461" />
  <package id="mongocsharpdriver" version="2.7.0" targetFramework="net461" />
  <package id="MongoDB.Bson" version="2.7.0" targetFramework="net461" />
  <package id="MongoDB.Driver" version="2.7.0" targetFramework="net461" />
  <package id="MongoDB.Driver.Core" version="2.7.0" targetFramework="net461" />
  <package id="NAudio" version="1.8.4" targetFramework="net461" />
  <package id="Newtonsoft.Json" version="11.0.2" targetFramework="net461" />
  <package id="Polly-Signed" version="5.9.0" targetFramework="net461" />
  <package id="RestSharp" version="106.3.1" targetFramework="net461" />
  <package id="System.Buffers" version="4.5.0" targetFramework="net461" />
  <package id="System.IdentityModel.Tokens.Jwt" version="5.2.4" targetFramework="net461" />
  <package id="System.Net.Http" version="4.3.3" targetFramework="net461" />
  <package id="System.Runtime.InteropServices.RuntimeInformation" version="4.0.0" targetFramework="net461" />
  <package id="System.Security.Cryptography.Algorithms" version="4.3.1" targetFramework="net461" />
  <package id="System.Security.Cryptography.Encoding" version="4.3.0" targetFramework="net461" />
  <package id="System.Security.Cryptography.Primitives" version="4.3.0" targetFramework="net461" />
  <package id="System.Security.Cryptography.X509Certificates" version="4.3.2" targetFramework="net461" />
  <package id="WindowsAzure.Storage" version="9.3.1" targetFramework="net461" />
</packages>`

EDIT: I should also mention that I have two different bot channels. Neither of them are working

**Comment by jwiley84** [comment]
Hi @OBrien1510! 
This particular repo is for DCRs only, so I'm going to go ahead and copy-pasta this issue into a repo where it will get more traction and then close this one. As soon as I do, I"ll tag you on it so you can still get the assistance you need. A bot that stops for no reason is never a good thing.

**Comment by jwiley84** [comment]
Moved to [V3 - #92](https://github.com/Microsoft/BotBuilder-V3/issues/92)
