### ISSUE TITLE
Cortana does support adaptive cards.

### ISSUE THREAD

**Issue by v-daturc** [Microsoft/BotBuilder#5216]
On the Channel Inspector page, the note says that "Cortana does not render Adaptive Cards." Cortana has supported them since February 2018, so you should remove the note.

**Comment by jwiley84** [comment]
Hi @v-daturc! This repo is currently only taking Design Change Requests (DCR) issues. For submitting **bug fixes** and **feature requests**, please go to the following repo: [Botframework-Services](https://github.com/Microsoft/Botframework-Services). That being said, I'll go ahead and pass this on to the docs team, as you're correct, the Channel Inspector page is a wee bit outdated (it still shows the Bing channel, afterall).

**Comment by v-daturc** [comment]
Hi, Jessica—

Thanks for letting me know, and for passing the bug along.

--David T.
