### ISSUE TITLE
Consider de-listing obsoleted primitive prompting libraries from NuGet and NPM to avoid confusion

### ISSUE THREAD

**Issue by drub0y** [Microsoft/BotBuilder#5219]
The libraries for the prompt primitives from the v4 preview time frame are still listed on NuGet ([Microsoft.Bot.Builder.Prompts](https://www.nuget.org/packages/Microsoft.Bot.Builder.Prompts/4.0.1-preview)) and NPM ([botbuilder-prompts](https://www.npmjs.com/package/botbuilder-prompts)) right now which can lead to a little bit of confusion as people start to search for how to prompt in v4.

On NuGet I know you can delist the library so it no longer appears in search results yet is still available for anyone who is maybe still using preview bits. I'm pretty sure the same is possible on NPM as well.

**Comment by Stevenic** [comment]
This has already been done for NPM

**Comment by sgellock** [comment]
@cleemullins can you deprecate the assembly referenced above from NuGet
