### ISSUE TITLE
Attempting to send multiple messages with bot?

### ISSUE THREAD

**Issue by epitone** [Microsoft/BotBuilder#522]
I'm currently using the Bot Framework Emulator to test out my bot - I've been running into 500 Internal Server Errors when I attempt to send multiple PostAsync calls when the bot responds to a messag - my code is simply:

                await context.PostAsync("2");
                await context.PostAsync("3");
                await context.PostAsync("4");

I'm having trouble understanding the stacktrace, but I'm seeing something along the lines of: `"System.Net.Http.HttpRequestException",
  "stackTrace": "   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess` - I'm guessing it's trying to connect to something but I don't actually know *what* that something is, and how to fix it.

Any help would be greatl

**Edit:** Adding in a bit more of the stacktrace to give a bit more clarity: `"exceptionMessage": "No connection could be made because the target machine actively refused it 127.0.0.1:9000",
      "exceptionType": "System.Net.Sockets.SocketException",
      "stackTrace": "   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)"`

**Comment by DavePilks** [comment]
Are you hosting the bot externally?

**Comment by epitone** [comment]
No I'm not - it's got the default API Key and default AppSecret - haven't published it anywhere

**Comment by DavePilks** [comment]
Ah ok, I know that there are issues with the emulator talking to externally hosted bots.

**Comment by srijiths** [comment]
As per documentation , yes it will work. But when i tried with many variations , it never succeeded. Please refer this issue for NodeJs #451

**Comment by willportnoy** [comment]
Is the emulator actually running on port 9000?  Can you use "netstat -ab" and see whether there is a process listening on 9000?

**Comment by epitone** [comment]
@willportnoy no there isn't anything listening on the port strangely enough, when I run the Bot Framework Application it sometimes will tell me "Failed to start server on port 3978 (the default port for the bot I'm assuming)" there seem to be things listening on those ports already, but I don't know if that would be the cause for that error.

**Comment by epitone** [comment]
@willportnoy I fixed the port issue but now, only the last message (in my earlier example - "4") appears - the other two are not posted.

**Comment by willportnoy** [comment]
The last message is sent inline with the response.  The first two messages are sent with the help of the IConnectorClient.  They (just the first two messages) would fail to send if the Emulator wasn't listening on port 9000 or your bot credentials were incorrect.

**Comment by epitone** [comment]
@willportnoy all right I'm guessing my bot credentials are incorrect then, I'll look into that.

**Comment by wbreza** [comment]
@willportnoy How do I programatically set the credentials that the IConnectorClient uses?  My bot endpoint needs to support multiple bots.

**Comment by willportnoy** [comment]
@wbreza You could follow the example of "DetectEmulatorFactory", where it both sets the IConnectorClient credentials and uses the Message in a data-dependent fashion (i.e. you could switch your credentials based on which bot the message was sent to):

https://github.com/Microsoft/BotBuilder/blob/develop/CSharp/Library/Dialogs/IConnectorClientFactory.cs#L57

**Comment by willportnoy** [comment]
I'm going to close this issue for now - @wbreza or @epitone feel free to open a new issue as needed.

**Comment by wbreza** [comment]
@willportnoy  - One more question related to this:

The project I'm working with uses Unity for DI.  Bot framework uses Autofac.  If I create my own implementation of IConnectorClient how do I get access to the bot framework DI container to register my type registration?

**Comment by willportnoy** [comment]
The top-level Conversation.SendAsync API is a thin wrapper around our container:

https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Dialogs/Conversation.cs#L76

You can use the global one we have here:

https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Dialogs/Conversation.cs#L49

Or you may prefer to build and customize your own, like we do for our unit tests:

https://github.com/Microsoft/BotBuilder/blob/develop/CSharp/Tests/Microsoft.Bot.Builder.Tests/DialogTestBase.cs#L58
