### ISSUE TITLE
Directline CORS question

### ISSUE THREAD

**Issue by kesavanpurushothaman** [Microsoft/BotBuilder#5220]
We are using Directline Channel and botchat.js for front end.
Call to BotChat app is made as follows.
BotChat.App({
            directLine: { secret: '@Model.Token' },
            user: { id: '@Model.UserId', name : '@Model.Name' },
            bot: { id: 'botname' },
            resize: 'detect',
        }, document.getElementById("ChatID"));

Chat is not loaded with the below error.

"1 Access to XMLHttpRequest at 'https://directline.botframework.com/v3/directline/conversations' from origin 'https://xxxxxxxxxxxxxxxx.azurewebsites.net' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
directline.botframework.com/v3/directline/conversations:1"

Can you please help us with a solution?

**Comment by tdurnford** [comment]
This repo is currently only taking Design Change Requests (DCR) issues. For submitting **bug fixes** and **feature requests**, please go to the [Webchat](https://github.com/Microsoft/botframework-webchat) repository.

**Comment by felipe-coelho** [comment]
Hi @kesavanpurushothaman. I have the same problem, did you manage to solve it?
