### ISSUE TITLE
bot builder routing not changing. It matches the intent trigger, but still routing to the other intent action.

### ISSUE THREAD

**Issue by shruti-12** [Microsoft/BotBuilder#5223]
_Originally posted by @shruti-12 in https://github.com/Microsoft/BotBuilder/issues/3490#issuecomment-446868293_

I am trying to call an intent of sending an email. The bot builder recognize the intent using the  trigger. But still redirects me to the welcome intent. In terminal window for this particular intent:email , getting message as Library("*").findRoutes() explanation:
        ActiveDialog(0.1)......

Also, this is happening only for one intent, send email. for all other intents it is working as expected. 
Please help. I have tried using sess.endDialog(); as well.

**Comment by shruti-12** [comment]
also,the console.log is not working suddenly

**Comment by jwiley84** [comment]
This repo is currently only taking Design Change Requests (DCR) for tracking major changes to the Bot Framework architecture. For submitting **bug fixes** and **feature requests**, please go to the repo of the SDK you're utilizing: [Javascript](https://github.com/Microsoft/botbuilder-js) or [C#](https://github.com/Microsoft/botbuilder-dotnet).

**Comment by stevengum** [comment]
@shruti-12 please post your issue in the [BotBuilder-v3](https://github.com/Microsoft/BotBuilder-V3) repository using this [issue template](https://github.com/Microsoft/BotBuilder-V3/issues/new?template=v3-javascript-sdk-bug-.md).
