### ISSUE TITLE
msbot utility and .bot file encryption unnecessarily complicates source control management and deployment

### ISSUE THREAD

**Issue by lucashuet93** [Microsoft/BotBuilder#5226]
Storing service properties with encryption steps in the .bot file overcomplicates a process that already has a widespread simple solution in the .env file. Requiring encryption and knowledge of the .bot file and associated msbot utility adds a number of steps that makes source control management and deployment of bots decidedly more complicated than other Azure services.

**Comment by stevkan** [comment]
The Botbuilder repository has been restructured to better handle issues. You can read more about it [here](https://github.com/Microsoft/BotBuilder). Please submit this issue to the [Botbuilder-Samples](https://github.com/microsoft/botbuilder-samples/issues) repository.
