### ISSUE TITLE
Embedding a "Title" in the Markdown link url is not supported correctly

### ISSUE THREAD

**Issue by vbhatt** [Microsoft/BotBuilder#5227]
The WebChat window should render the "Title" correctly for Accessibility (ADA) compliance. See the example below.
["How To"](https://stackoverflow.com/help/how-to-ask "Some Title Here")

**Comment by stevkan** [comment]
The Botbuilder repository has been restructured to better handle issues. You can read more about it [here](https://github.com/Microsoft/BotBuilder). Please submit this issue to the [BotFramework-Webchat](https://github.com/microsoft/botframework-webchat/issues) repository.
