### ISSUE TITLE
Not receiving the entities in my application

### ISSUE THREAD

**Issue by stalera** [Microsoft/BotBuilder#5229]
When I browse the URL to get the response from my model, I get the json with all the information like multiple intents with their scores and entities. But in my c# code, I get only the top scoring intent, nothing else.
Anything I'm missing?

**Comment by stevkan** [comment]
The Botbuilder repository has been restructured to better handle issues. You can read more about it [here](https://github.com/Microsoft/BotBuilder/). Please submit this issue on the [Botbuilder-CognetiveServices](https://github.com/Microsoft/BotBuilder-CognitiveServices/issues) repository.
