### ISSUE TITLE
Installing Emulator on Ubuntu 16

### ISSUE THREAD

**Issue by pmathur08** [Microsoft/BotBuilder#523]
Hello!

I was trying to install the emulator on my linux machine and I ran into some trouble. Following instructions in the documentation i installed mono and unzipped BFEmulator zip package.

However when I run mono BFEmulator.exe  this is what I get:
Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.
File name: 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.
File name: 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

Please advise

**Comment by tomlm** [comment]
Hmm..do you have mono installed?  This worked for me on my ubuntu

**Comment by tomlm** [comment]
I'm running 15.10

**Comment by pmathur08** [comment]
Hey! Thanks for your reply!

I do have mono installed. It didn't work for me but then I downloaded Wine
and it worked using Wine.
