### ISSUE TITLE
DirectLine object is not initiating the bot conversation 

### ISSUE THREAD

**Issue by DivyashriV** [Microsoft/BotBuilder#5230]
Hi Team,
 We are using Direcline channel in our bot for conversation and the directline object is not initiating the bot conversation and its throwing exception like "Authentication failed because the remote party has closed the transport stream",below is the line which throws the exception:
var conversation = await client.Conversations.StartConversationAsync();

Note:The same solution was working fine and all of a sudden it stopped working.

Thanks
Divyashri.V

**Comment by stevkan** [comment]
The Botbuilder repository has been restructured to better handle issues. You can read more about it [here](https://github.com/Microsoft/BotBuilder). Please submit this issue to the [Botbuilder-DotNet](https://github.com/microsoft/botbuilder-dotnet/issues) repository.
