### ISSUE TITLE
Publish documentation for Application Insights

### ISSUE THREAD

**Issue by daveta** [Microsoft/BotBuilder#5234]
There are a few topics to cover:
- Walk the user through how to set up Application Insights using the SDK elements.
- Describe IBotTelemetryClient and how to overload the Dialog.TelemetryClient property.
- Describe the telemetry being logged by the Waterfall Dialog.

[Source material is here](https://github.com/daveta/analytics/blob/master/appinsights_blog_42/bot_application_insights.md)..

**Comment by Kaiqb** [comment]
[Telemetry](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-telemetry?view=azure-bot-service-4.0) content published.
