### ISSUE TITLE
Telemetry: Add KeyPhrases to LUIS Telemetry

### ISSUE THREAD

**Issue by daveta** [Microsoft/BotBuilder#5240]
## Issue
Currently, we don't log KeyPhrases from LUIS telemetry.

## Proposed change
Add KeyPhrases to results that get logged into Application Insights.

## Tracking Status
**Dotnet SDK**
- [ ] PR
- [ ] Merged

**Javascript SDK**
- [ ] PR
- [ ] Merged

**Samples**
- [ ] PR
- [ ] Merged

**Docs**
- [ ] PR
- [ ] Merged

**Tools**
- [ ] PR
- [ ] Merged

[dcr]

**Comment by sgellock** [comment]
@daveta since you're now a LUIS dev, how about helping?  :-).

**Comment by daveta** [comment]
This must have been fixed a while back - I just tested and keyPhrase is a form of entity, and those flow all the way back.  We can consider that we introduce type (in the underlying Luis Recognizer), but don't really see a need at this point - the chance of collision is pretty low.

**Comment by daveta** [comment]
(Also, this is in both js and C# - and the key phrase itself does flow through.  I think some prebuilt types were being filtered out before at the recognizer level).
