### ISSUE TITLE
Unknown conversation

### ISSUE THREAD

**Issue by eskivelevolution** [Microsoft/BotBuilder#5248]
Hello,

My users reported that the webchat bot stopped. 

In an anonymous tab (generating a new conversation) works, but when an old conversationId is used, it does not work.

Has the botframework service changed anything?

1. All users who were a long time without talking bot stopped.
2. I have not changed anything.

![image](https://user-images.githubusercontent.com/19326711/50791689-b790bd80-12a9-11e9-97ed-43a016ae68b0.png)

Thank you.

**Comment by stevkan** [comment]
@eskivelevolution, I'm looking into this for you.

**Comment by stevkan** [comment]
Messages remain accessible for 24 hours after which they expire. In some cases a conversationId _may_ be accessible for longer than 24 hours but it would not contain any message data. The accessibility of the conversationId is based on the last active communication.

This is true for both the Direct Line and Web Chat channels.

**Comment by eskivelevolution** [comment]
Thank you @stevkan .

Based on Microsoft Oficial Engineers:

Web Chat conversation IDs live for a while but expire after a few weeks of inactivity. We do this because we can’t keep the metadata forever but also don’t want to time out after a reasonable period of return, like an hour or two.

Both Web Chat and Direct Line rely on your user model. I.e., we don’t have a native notion of a user – it’s whatever you provide (be it an AAD object ID, or a GitHub ID, or a Pinterest ID, etc.). Accordingly, we don’t have a notion of a user that exists outside of a conversation, and we pass responsibility for managing that user interaction to the bot/client developer.
