### ISSUE TITLE
Map activities to On* messages

### ISSUE THREAD

**Issue by johnataylor** [Microsoft/BotBuilder#5253]
Relates to https://github.com/Microsoft/BotBuilder/issues/5235 

Need to map activity protocol members and types to On*Messages. For example 
```
turnContext.activity.hasOwnProperty('membersAdded')
```

the output should be a list (table) of Bot Framework activities to specific code that translates into On*Message

[dcr]

**Comment by yochay** [comment]
This item is part of https://github.com/Microsoft/botbuilder-dotnet/pull/1358. Closing this one
