### ISSUE TITLE
DCR: Add Complete LUIS Endpoint as overload param for LuisRecognizer

### ISSUE THREAD

**Issue by stevengum** [Microsoft/BotBuilder#5255]
## Proposed change
Add LUIS Endpoints as an overload constructor param for the LuisRecognizer classes. A complete LUIS endpoint contains all of the necessary information for the bot to call LUIS. A LUIS endpoint can be obtained from visiting the portal. Calling a couple Authoring APIs can also yield the necessary information to construct a endpoint.

Example endpoint with LuisRecognizer-necessary information identified (e.g. **\<Endpoint\>**)

> https://westus.api.cognitive.microsoft.com/luis/v2.0/apps/########-####-####-####-############?subscription-key=################################&q=

> **\<Endpoint>**/luis/v2.0/apps/**\<AppID\>**?subscription-key=**\<Subscription-Key\>**&q=

## Customer Impact 
By having endpoint be a supported param for constructing a LuisRecognizer, developers using flat-formats for storing their LUIS information do not need to separate each required param for a `LuisRecognizer`.

E.g. a `.env` file can now look like this:
```
LUIS_WEATHER_ENDPOINT=https://westus.api.cognitive.microsoft.com/luis/v2.0/apps/<AppId>?subscription-key=<SubscriptionKey>&q=
```

And `appsettings.json` can look like this:
```json
{
  "LuisWeatherEndpoint": "https://westus.api.cognitive.microsoft.com/luis/v2.0/apps/<AppId>?subscription-key=<SubscriptionKey>&q="
}
```

Instead of
```
LUIS_WEATHER_ENDPOINT=
LUIS_WEATHER_APP_ID=
LUIS_WEATHER_SUBSCRIPTION_KEY=
```

And

```json
{
  "LuisWeatherEndpoint": "https://westus.api.cognitive.microsoft.com",
  "LuisWeatherAppId": "<AppId>",
  "LuisWeatherSubscriptionKey": "<SubscriptionKey>"
}
```
___

To construct a new LuisRecognizer in Node.js, one could use the following line:

```js
const recognizer = new LuisRecognizer(process.env.LUIS_WEATHER_ENDPOINT);
```

Instead of
```js
const recognizer = new LuisRecognizer({
  applicationId: process.env.LUIS_WEATHER_APP_ID,
  endpoint: process.env.LUIS_WEATHER_ENDPOINT,
  endpointKey: process.env.LUIS_WEATHER_SUBSCRIPTION_KEY
});
```

## Tracking Status
**Dotnet SDK**
- [x] PR
- [ ] Merged

**Javascript SDK**
- [ ] PR
- [ ] Merged

**Java SDK**
- [ ] PR
- [ ] Merged

**~Python SDK~** _(`botbuilder-ai` Not yet implemented)_
- ~[ ] PR~
- ~[ ] Merged~

[dcr]

**Comment by johnataylor** [comment]
Note the C# implementation actually adds the overload to a class called LuisApplication in addition to the LuisRecognizer class. In the TypeScript this is just an interface so we should add the code directly into the LuisRecognizer constructor.

**Comment by johnataylor** [comment]
assigning to @stevengum 
This https://github.com/Microsoft/botbuilder-dotnet/pull/1378 is approved and waiting on your PR for JavaScript.
