### ISSUE TITLE
How to call a formflow dialog from a QnAMakerDialog at a certain condition on botbuilder-v3 or V4

### ISSUE THREAD

**Issue by tutul2010** [Microsoft/BotBuilder#5258]
Hi,
I am new to Bot-framework and making a chatbot that communicates with QnA-Maker type with KB services(FAQ type), and depending on a certain answer returning ,try to call or start a guided conversation by FormFlow . I'm using SDK-V3(C#.net) and QnAMakerDialog .
So,
IS IT POSSIBLE TO CALL a formflow dialog or a Normal Dialog  from a QnAMakerDialog at a certain condition on botbuilder-v3 or V4(C#.net)?

Thanks,

**Comment by EricDahlvang** [comment]
Hi @tutul2010 

I've provided an answer to your question here: https://github.com/Microsoft/BotBuilder-Samples/issues/1147#issuecomment-454576774

In the future, please use [StackOverflow](https://stackoverflow.com/questions/tagged/botframework) for usage questions.  The GitHub repositories are for DCRs, Bug Reports and Feature Requests.
