### ISSUE TITLE
Skype Web Control - 500 error when replying using actions/buttons returned by bots

### ISSUE THREAD

**Issue by robsonmafra** [Microsoft/BotBuilder#5259]
## Issue
Error in **Skype Web Control** when replying in an action/button returned by bots. I have the error in my bot, but it also happens in the bots in https://dev.skype.com/bots

Here I tested the **Heston Bot**, you can see the 500 errors every time I clicked on "Continue":
![screen shot 2019-01-19 at 21 31 48](https://user-images.githubusercontent.com/1108243/51432614-48648300-1c32-11e9-8a16-4eab14a769fc.png)

Here the error of the 500 error request:
```
curl 'https://client-s.gateway.messenger.live.com/v1/users/ME/conversations/28:7036b7fa-28aa-4eba-9ad0-0f33b3ca0533/messages' -H 'Pragma: no-cache' -H 'BehaviorOverride: redirectAs404' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36' -H 'ClientInfo: os=Windows; osVer=10; proc=Win32; lcid=en-us; deviceType=1; country=IE; clientName=swc; clientVer=912/0.95.0.31//swc' -H 'ContextId: tcid=75537d17-3753-1df3-73b3-15993dbb5775' -H 'RegistrationToken: registrationToken=...' -H 'Referer: https://swc.cdn.skype.com/v/0.95.31/services.html?ver=0.95.31&platform=undefined&env=prod' -H 'Content-Type: text/plain;charset=UTF-8' -H 'Origin: https://swc.cdn.skype.com' -H 'Expires: 0' --data-binary '{"contenttype":"text","composetime":"2019-01-19T21:31:48.113Z","clientmessageid":"1547933508113","content":"Continue","properties":"https://swc.cdn.skype.com/v/0.95.31/Continue","messagetype":"RichText","processedcontent":"Continue","imdisplayname":"Robson Mafra"}' --compressed
```

Here I tested the other bot, the **StubHub**, same error when replying using the quick answers options:
![screen shot 2019-01-19 at 21 40 02](https://user-images.githubusercontent.com/1108243/51432647-e6584d80-1c32-11e9-9dc9-3c9ac753f65a.png)

Here the error of the 500 error request:
```
curl 'https://client-s.gateway.messenger.live.com/v1/users/ME/conversations/28:e33eb54a-e562-4cc5-891f-73c8087e47e1/messages' -H 'Pragma: no-cache' -H 'BehaviorOverride: redirectAs404' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36' -H 'ClientInfo: os=Windows; osVer=10; proc=Win32; lcid=en-us; deviceType=1; country=IE; clientName=swc; clientVer=912/0.95.0.31//swc' -H 'ContextId: tcid=7dd3351d-d79b-d73b-f951-1b3f717b7131' -H 'RegistrationToken: registrationToken=...' -H 'Referer: https://swc.cdn.skype.com/v/0.95.31/services.html?ver=0.95.31&platform=undefined&env=prod' -H 'Content-Type: text/plain;charset=UTF-8' -H 'Origin: https://swc.cdn.skype.com' -H 'Expires: 0' --data-binary '{"contenttype":"text","composetime":"2019-01-19T21:39:58.358Z","clientmessageid":"1547933998358","content":"Find events","properties":"https://swc.cdn.skype.com/v/0.95.31/*Find%20events","messagetype":"RichText","processedcontent":"Find events","imdisplayname":"Robson Mafra"}' --compressed
```

## Reproduction Steps
- Access https://dev.skype.com/bots
- Talk to any bot example using Skype Web Control
- Interact with the Bot until it reply with options or buttons
- Click on the option/button
- Expected behaviour should be send the message, however, the API is returning 500 error.

## Component Impact 
Skype Web Control

## Customer Impact 
All users that have bots with **Skype Web Control** can be impacted and not able to receive the answers/reply when the user select the option/button.

**Comment by stevkan** [comment]
@robsonmafra, the Skype Web Control is, effectively, a dead product and is no longer being supported by the Skype team. Similarly, the https://dev.skype.com/bots you tested were developed by Skype and were largely for demonstration. They do not receive much in the way of current support, either.

Users would best be served by utilizing the [BotFramework-WebChat](https://github.com/Microsoft/BotFramework-WebChat) library in their sites. It offers a lot of features, but most importantly: it is actively supported.
