### ISSUE TITLE
Return 403 Forbiden when run Demo-Facebook on Microsoft Bot Framework Emulator

### ISSUE THREAD

**Issue by vmthanh** [Microsoft/BotBuilder#526]
Hi.
I'm beginner with Microsoft Bot Framework, so that I want to try with your demo. When I follow the instruction in demo-facebook, I cannot run with the demo. Please help me and correct me if I'm wrong with which step.
As far as I understand, here is the step I did:
1. I download and install ngrok. and run it with port 4000 (I chose a different port instead using 3978 and also I updated new port in code).
![capture1](https://cloud.githubusercontent.com/assets/8940457/16291422/ec1d87f4-3930-11e6-9e55-519ae673ff70.PNG)
2. I create a bot in https://dev.botframework.com, give it a bot ID and the endpoint with the url given from ngrok.
![capture2](https://cloud.githubusercontent.com/assets/8940457/16291449/505b84dc-3931-11e6-9462-b4908aede124.PNG)
3. From the botID and app secret I got, I copy and update it directly in code (not using set set BOTFRAMEWORK_APPID and BOTFRAMEWORK_APPSECRET in console)
![capture3](https://cloud.githubusercontent.com/assets/8940457/16291508/d8b575ea-3931-11e6-8d44-4bbf480cabab.PNG)
4. Now the critical point, I start the server. It worked well. Then, I config the url and port in Microsoft Bot Framework Emulator. 
![capture5](https://cloud.githubusercontent.com/assets/8940457/16291582/af416394-3932-11e6-9997-70f125ae6d08.PNG)

![capture4](https://cloud.githubusercontent.com/assets/8940457/16291565/78e3be96-3932-11e6-848a-048067b38441.PNG)
You see, I got the 404 Forbiden which I cannot figure out what's wrong with me. And this is info I got from ngrok console
![capture6](https://cloud.githubusercontent.com/assets/8940457/16291588/c2b36422-3932-11e6-8c36-8afb239752ea.PNG)
I think I had follow instruction right but still don't know why i cannot run the program. 
Very appreciate to help me resolve the problem.
Thank you and best regards.

**Comment by tomlm** [comment]
OK, you got your wires crossed here.

The emulator has an internal server which listens on whatever port is in the UI.  The default is 9000.
Your bot runs in the local debugger under whatever port it is configured with (4000?) 

In the emulator UI you put your bot's url, so it would be http://localhost:4000/api/messages 

You can then use the emulator with your local running bot without involving ngrok at all.

If you want to test your auth, you can register, get an appid/secret, put it into the UI and the emulator will start to validate the auth headers (again without any ngrok)

If you want to run ngrok, then you can run ngrok pointing at your bot (4000) and register that ngrok url in the portal.  Any of the configured connectors will then talk with directly your service via the ngrok url and you can debug locally.  

So given all of this information, you can see that you have set up the emulator to run on port 4000, which ngrok is pointing as the url for the bot.  When you try to send a message to the bot, the emulator is sending it to the ngrok url which is the emulator itself.  Naturally it rejects that as forbidden.

**Comment by vmthanh** [comment]
@tomlm 
Hi. Sr for disturbing you again.
After your reply. I shut down ngrok and then run as follow
![capture](https://cloud.githubusercontent.com/assets/8940457/16367080/06d76f26-3c4a-11e6-97f8-22195baf94c1.PNG)
and then
![capture2](https://cloud.githubusercontent.com/assets/8940457/16367084/0f093cb0-3c4a-11e6-9447-16a07bb1cc65.PNG)
I got this error, Can you figure out which step I'm wrong again?
Thank you.

**Comment by tomlm** [comment]
Change the UI Port to 9000.  You have configured the UI to use the same port as your node service.
should be
Port: 9000
Url: http://localhost:4000/api/messages

**Comment by vmthanh** [comment]
@tomlm 
Hi. Still get the same error and do not know why.
![capture](https://cloud.githubusercontent.com/assets/8940457/16402030/70bca4fa-3d13-11e6-82a3-79e8e8fd6168.PNG)

**Comment by tomlm** [comment]
that is what your bot is returning.  The emulator is working correctly, you will have to figure out why your bot is returning that error.
