### ISSUE TITLE
Unable to connect to API from BOT and get response

### ISSUE THREAD

**Issue by drvvgopalareddy** [Microsoft/BotBuilder#5260]
## Issue
Unable to connect to the API and get the data from the API using Bot Emulator. The following is the issue
Cannot post activity. Unauthorized
POST 401 directline.postActivity

**Comment by jwiley84** [comment]
@drvvgopalareddy, I edited your issue to remove all the excess templating. I'm going to need further information in order to assist you with this. Please post a screenshot of the emulator screen as well as what SDK you're using, otherwise I"m assuming you're using directline.

**Comment by CoHealer** [comment]
@drvvgopalareddy, do you still need help?

**Comment by CoHealer** [comment]
Stale thread, closing

**Comment by CoHealer** [comment]
No response from author
