### ISSUE TITLE
Make `ListStyle` easier to use

### ISSUE THREAD

**Issue by v-kydela** [Microsoft/BotBuilder#5263]
## Issue

Choice prompts and confirm prompts provide the ability to choose a list style (inline, suggested actions, etc.) but in V4 the way to do this is [awkward](https://stackoverflow.com/questions/54311585/using-promptoptionss-promptstyler-class-with-microsoft-bot-builder-4-0/54318349#54318349) and [not very discoverable](https://github.com/MicrosoftDocs/bot-docs/issues/632).

Dialogs are meant to be instantiated and added to the dialog set on [one line each](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-prompts?view=azure-bot-service-4.0&tabs=csharp#create-a-dialog-set-and-prompts):

> ```c#
> _dialogSet.Add(new NumberPrompt<int>(PartySizePrompt, PartySizeValidatorAsync));
> _dialogSet.Add(new ChoicePrompt(LocationPrompt));
> _dialogSet.Add(new DateTimePrompt(ReservationDatePrompt, DateValidatorAsync));
> ```

But in order to set a prompt's `ListStyle` property you must set the dialog to a variable so you can set the property on its own line.

> ```c#
> var cp = new ChoicePrompt(LocationPrompt);
> cp.Style = Bot.Builder.Dialogs.Choices.ListStyle.None;
> _dialogSet.Add(cp);
> ```

This does not seem very fluent and does not seem to align with the syntactic conventions seen elsewhere in the SDK.

## Proposed change

I can think of two potential changes that would fix this (and they could be implemented simultaneously).

1. Provide an optional style parameter in the constructors for `ChoicePrompt` and `ConfirmPrompt`
2. Include a `ListStyle` property in the `PromptOptions` class (like in V3)

## Component Impact 

Updating the `ChoicePrompt` and `ConfirmPrompt` constructors should be very easy since the classes already contain `Style` properties. If `PromptOptions` is updated then `ChoicePrompt.OnPromptAsync` and `ConfirmPrompt.OnPromptAsync` will also need to be updated so that they can override the dialog's list style with the options' list style.

## Customer Impact 

This would make it easier for customers to customize choice prompts and confirm prompts.

## Tracking Status
**Dotnet SDK**
- [ ] PR
- [ ] Merged

**Javascript SDK**
- [ ] PR
- [ ] Merged

**Java SDK**
- [ ] PR
- [ ] Merged

**Python SDK**
- [ ] PR
- [ ] Merged

**Emulator**
- [ ] PR
- [ ] Merged

**Samples**
- [ ] PR
- [ ] Merged

**Docs**
- [ ] PR
- [ ] Merged

**Tools**
- [ ] PR
- [ ] Merged

[dcr]

**Comment by v-kydela** [comment]
I forgot about object initializer syntax in C#:

```c#
_dialogSet.Add(new ChoicePrompt(LocationPrompt) {Style = Bot.Builder.Dialogs.Choices.ListStyle.None});
```

However, that doesn't help with JavaScript as far as I know.

**Comment by Stevenic** [comment]
We've added the ability to dynamically set the list style via the prompt options.  There's a new set of prompts coming in 4.5 that will make statically styling the prompts (and all dialogs) more fluent. Closing this for now.
