### ISSUE TITLE
Custom User ID with DirectLineClient

### ISSUE THREAD

**Issue by mrThirsty** [Microsoft/BotBuilder#5265]
Hi,

When using the C# library DirectLineClient I am not able to specify the user ID of the member unlike when configuring the web-chat js library.

Our App logs the user in and then uses the DirectLineClient to allow the user to chat to the bot as one of its features, since we have a logged in user we want to pass this ID to the bot so it can auto respond back to the user with out them having to send a message first.

The bot waits for a ConverstationUpdate event and then pulls the membersAdded and responds to the member with data from the system to give a personalised experience.

This works well with the wb-chat embedded on our user site since we can provide a custom UserId to the Directline create call, but I can't do this on the C# DirectLineClient and this always generates a random user ID when the ConversationUpdate is made on the DirectLineClient.StartConversation() call from our App.

As a work around I have put some checks into the ConversationUpdate handler in my bot to look for our User ID format and if the Id on the MemberAdded record doesn't fit it, then I ignore that MemberAdd.

Then in the App, I create a DirectLineClient, call StartConversation() and then Post an Activity with type of ConversationUpdate and a custom From ChannelAccount to use the logged in user's Id.

This then gives the logged in user in the App the same experience if they had logged in on the website, but this is just a lot of workaround for me.

Surely the DirectLineClient should allow me to specify the User ID to use when I call StartConversation so when the bot recieves the automated ConversationUpdate, the correct ID is on the memberAdded Record?

**Comment by EricDahlvang** [comment]
There is an underlying Direct Line protocol issue here. This is not necessarily a DirectLineClient issue. (ref: https://blog.botframework.com/2018/07/12/how-to-properly-send-a-greeting-message-and-common-issues-from-customers/ ) 

The Direct Line rest api's StartConversation endpoint does not have a userid parameter: https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-api-reference?view=azure-bot-service-4.0#start-conversation  DirectLineJs (used by WebChat) allows you to supply a userid, but it does not generate a conversationUpdate or use the userid during [StartConversation](https://github.com/Microsoft/BotFramework-DirectLineJS/blob/master/src/directLine.ts#L538)  WebChat now generates a conversationUpdate event: https://github.com/Microsoft/BotFramework-WebChat/blob/master/packages/core/src/sagas/sendConversationUpdateOnConnectSaga.js 


This can also be done with the DirectLineClient, as it sounds you have also done as a workaround.

Something like this:

```cs
//server side, retrieve token from secret
           string directLineSecret = ConfigurationManager.AppSettings["DirectLineSecret"];
           HttpClient httpClient = new HttpClient();
            HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Post,$"https://directline.botframework.com/v3/directline/tokens/generate");
            request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", directLineSecret);
            var fromUser = $"dl_{Guid.NewGuid()}";
            request.Content = new StringContent(
                JsonConvert.SerializeObject(
                    new { User = new { Id = fromUser } }),
                    Encoding.UTF8,
                    "application/json");
            var response = await httpClient.SendAsync(request);
            DirectLineToken dlToken = null;
            if (response.IsSuccessStatusCode)
            {
                var body = await response.Content.ReadAsStringAsync();
                dlToken = JsonConvert.DeserializeObject<DirectLineToken>(body);
            }
            string token = dlToken.token;

//create token from secret client side
            DirectLineClient client = new DirectLineClient(token);            
            var conversation = await client.Conversations.StartConversationAsync();            
            new System.Threading.Thread(async () => await ReadBotMessagesAsync(client, conversation.ConversationId)).Start();

//send conversationUpdate
            var user = new ChannelAccount(fromUser);
            await client.Conversations.PostActivityAsync(conversation.ConversationId,
                                         new Activity
                                         {
                                             From = user,
                                             Text = string.Empty,
                                             Type = ActivityTypes.ConversationUpdate,
                                             MembersAdded = new[] { user }
                                         }
                                    );
            TimeSpan delayTime = TimeSpan.FromSeconds(dlToken.expires_in) - TimeSpan.FromMinutes(5);
            Task.Factory.StartNew(async () =>
            {
                while (!_getTokenAsyncCancellation.IsCancellationRequested)
                {
                    var t = await client.Tokens.RefreshTokenAsync().ConfigureAwait(false);

                    await Task.Delay(delayTime, _getTokenAsyncCancellation.Token).ConfigureAwait(false);
                }
            }).ConfigureAwait(false);

```

There has been some discussion about open sourcing the DirectLineClient.  Hopefully that will happen soon.  Until then, or until the Direct Line protocol changes: these workarounds are the way to go.

**Comment by hansmbakker** [comment]
@EricDahlvang @mdrichardson I found this issue via https://stackoverflow.com/questions/58815026/how-to-set-activity-from-id-member-id-or-activity-recipient-id-using-dir.

I was wondering if specifying a user account in the `TokenParameters` parameter of `GenerateTokenForNewConversation` would be a solution? For me that seems to generate a `conversationUpdate` event?

Also: where is stated that `DirectLineClient` is deprecated? It is still recommended on https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-net-client?view=azure-bot-service-4.0

**Comment by EricDahlvang** [comment]
DirectLineClient is not deprecated.   You are correct that specifying a user.id while generating a token will now send conversationupdate for the user.  This was an update to the service, completed sometime in the past year (after this post was resolved).

We've also been working on open sourcing a new version of the DirectLineClient. In fact, I was just working on that earlier this week!  :)

**Comment by hansmbakker** [comment]
Oh, that is great to hear!

@mdrichardson could you please update [your stackoverflow answer](https://stackoverflow.com/a/58824040/1114918) to avoid confusion?

**Comment by mdrichardson** [comment]
@hansmbakker Will do. I made that comment awhile ago and I believe it was because we were just about to start actively working on the new version, which *would have* deprecated the old.

**Comment by hansmbakker** [comment]
Thank you!
