### ISSUE TITLE
How to retry until successful?

### ISSUE THREAD

**Issue by Botship** [Microsoft/BotBuilder#527]
I am trying to get a dialog loop e.g prompt user to enter email address, and loop until its right email address format. I am unable to find a good example of this. Could someone please point me how to do it? I am using LuisDialog

     private void CompleteProfile(IDialogContext context)
        {
            if (HaveEmailAddress == false)
            {
                PromptDialog.Text(context, GetEmailAddress, "Please provide your email address.",
                    "That seems invalid email address. Please try again. ");
            }
        }
        public async Task GetEmailAddress(IDialogContext context, IAwaitable<string> awaitEmailAddress)
        {
            var curEmailAddr = await awaitEmailAddress;
            if (!string.IsNullOrEmpty(curEmailAddr))
            {
                if (new EmailAddressAttribute().IsValid(curEmailAddr))
                {
                    HaveEmailAddress = true;
                    await context.PostAsync($"Ok, saving {this.EmailAddress} to your profile.");
                }
                else
                {
                    PromptDialog.Text(context, GetEmailAddress, "That seems invalid email address. Please let me know again. ");
                }
            }
            else
            {
                HaveEmailAddress = false;
                await context.PostAsync("Ok, you can provide it later.");
            }
}

I am unable to use the "retry" prompt of PromptDialog.Text() and the above code leads to exception.
 "exceptionMessage": "invalid need: expected Wait, have Done",
  "exceptionType": "Microsoft.Bot.Builder.Internals.Fibers.InvalidNeedException",

**Comment by brene** [comment]
I'm not familiar with the C# syntax for this project. But in Javascript I would just invoke this:
```javascript
// let "/retry" be the dialog you want to retry until it works.
if (!fullfilled) {
    session.replaceDialog('/retry');
}
```

**Comment by willportnoy** [comment]
@brene is on the right track - in C#, you need to specify the next action you want to take in the "is valid" and "is empty" branches of your logic.  Either you should wait for user input by specifying context.Wait(some callback like MessageReceived) or use context.Done(some result) to wrap up this dialog and pop the stack.

**Comment by Botship** [comment]
I tried the suggestions specify action, but get the same error. Is there a documentation/example to demonstrate what I am trying?

How can I retry for say 3 times to prompt user to enter right email address? Changed this to while but get the same exception.

```C#
 private void CompleteProfile(IDialogContext context)
    {
      while (HaveEmailAddress == false)
        {
            PromptDialog.Text(context, GetEmailAddress, "Please provide your email address.",
                "That seems invalid email address. Please try again. ");
        }
    }

**Comment by willportnoy** [comment]
You can't call PromptDialog.Text in a while loop like that, because you need to wait for user input, and the bot code won't be running while you wait for user input.  Can you model your retries based on this code?

https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Dialogs/PromptDialog.cs#L581

In this method, you can see that if the parsing is successful, it returns a result with context.Done.  Otherwise, if the maximum of retries hasn't been reached, it context.Waits for user input.  Otherwise, it throws an exception.

**Comment by artemious7** [comment]
The `PromptDialog.Text()` method calls a `PromptString` dialog internally, and it will only trigger a retry if `message.Text` is empty or whitespace. Our goal is to make it trigger a retry if `message.Text` is not a valid email within the given number of attempts. This can be achieved by creating a new `PromptDialog` like this:

```
#region Usings
using System;
using Microsoft.Bot.Builder.Dialogs;
using Microsoft.Bot.Builder.Dialogs.Internals;
using Microsoft.Bot.Connector;
using System.Collections.Generic;
using System.Linq;
#endregion

namespace MyBot.Dialogs
{
    [Serializable]
    public class PromptEmail : Prompt<string, string>
    {
        public PromptEmail(string prompt, string retry = null, string tooManyAttempts = null, int attempts = 3, IEnumerable<string> quitWords = null)
          : base(new PromptOptions<string>(prompt, retry, tooManyAttempts, attempts: attempts))
        {
            this.quitWords = quitWords;
        }

        protected override bool TryParse(IMessageActivity message, out string text)
        {
            text = message.Text;
            return IsValidEmail(message.Text) || (quitWords ?? DefaultQuitWords).Any(r => message.Text.Equals(r, StringComparison.CurrentCultureIgnoreCase));
        }

        private bool IsValidEmail(string text)
        {
            // TODO: return true if email is valid
            throw new NotImplementedException();
        }

        private readonly IEnumerable<string> quitWords;
        public static readonly IEnumerable<string> DefaultQuitWords = new List<string> { "quit", "cancel", "exit", "back" }.AsReadOnly();
    }
}

```

This dialog can be called like this:

```
var promptEmail = new PromptEmail("What is your email?", "That is not an email. Please, try again.", "Wrong again. Too many attempts.", 3, quitWords: new string[] { "go back", "I give up", "why?" }.Concat(PromptEmail.DefaultQuitWords).Distinct().ToList());
context.Call(promptEmail, MessageReceivedAsync);
```
