### ISSUE TITLE
.bot file is "encrypted" but still human readable - leads to errors

### ISSUE THREAD

**Issue by ayako** [Microsoft/BotBuilder#5275]
By making the .bot file still human readable after encryption, it leads the developer to think they can change things like endpoint, app id, environment names and the file will still work when this is in fact not the case. Either encrypt the whole file or none of it so as not to lead the developer to an incorrect inference

**Comment by pkirch** [comment]
I had the same confusion as @ayako but still like to have only some settings being encrypted instead the whole file. Maybe use different setting names for encrypted content. E.g. appPassword and encryptedAppPassword.
