### ISSUE TITLE
The abstractions available to integrate with external services aren't at the right level; they should be higher with less code, less work to get them woven in 

### ISSUE THREAD

**Issue by msolhab** [Microsoft/BotBuilder#5278]
The abstractions available to integrate with external services such as LUIS, QnA Maker, Azure Search, etc., aren't at the right level. They should be higher with less code, less work to get them woven in, where the bot developer simply points to the desired service at the right point in the conversational flow, with an easy interface linking inputs and outputs to the flow. For e.g., submitting a question to QnA Maker and expecting a response should be a simple bot SDK call that abstracts the integration, sending a question to the service and expecting a text response.

**Comment by sgellock** [comment]
We'd like you to review the coming 4.5 preview work we will show at //Build.  We have some new constructs that we believe may be helpful here.
