### ISSUE TITLE
Where can I access BotUserData from? How can I set BotUserData for any user?

### ISSUE THREAD

**Issue by vaditya04** [Microsoft/BotBuilder#528]
I am using dummy messages with user ids to set BotUserData for a particular user, so that the bot can access it elsewhere via the same method.

Example:
```

            message.From.Id = someUserId;            
            message.SetBotUserData("someObject", someObject);

```

Later,
when another user is interacting with the bot, I execute
```

            message.From.Id = someUserId
            someObject = message.GetBotUserData<objectType>("someObject")


```
But someObject is returned as NULL

Note that these two snippets are being executed on different channels, conversations

**Comment by msft-shahins** [comment]
Currently we don't have support for user linking across different channels. user data for a specific user id should be available across different conversations for a fixed channel.
