### ISSUE TITLE
Bot to Human Handoff in SDKv4 (Node.js)

### ISSUE THREAD

**Issue by Basavarajsk1992** [Microsoft/BotBuilder#5280]
Need a solution for Bot to Human handoff in sdk v4 using nodejs.
Thanks

**Comment by jwiley84** [comment]
Hi Basavaraj! I'm going to close this issue, as I see you've opened an identical question on StackOverflow [here](https://stackoverflow.com/questions/54457426/hand-off-bot-to-human-in-azure-bot-framework-sdk-v4).
This particular repo is currently only taking Design Change Requests (DCR) issues.
