### ISSUE TITLE
DCR: Make OAuthAPIs and OAuthPrompt unit testable

### ISSUE THREAD

**Issue by Jeffders** [Microsoft/BotBuilder#5286]
## Issue
Currently the BotFrameworkAdapter has non-virtual methods that implement several OAuth APIs that help bots collect and ask for user tokens. This makes this functionality impossible to test because you cannot override them and the OAuthPrompt takes a hard dependency on BotFrameworkAdapter so there is no way to mock this.

## Proposed change
Three things:
1. Add an interface for all of the OAuth APIs for user tokens, and have BotFrameworkAdapter implement it
2. Make the User token methods on BotFrameworkAdapter virtual
3. Provide mock implementations of this functionality in TestAdapter and show how to use it in TestFlow

## Component Impact 
BotFrameworkAdatper, TestAdapter, OAuthPrompt

## Customer Impact 
Makes testing when the bot needs a token possible.

## Tracking Status
**Dotnet SDK**
- [X] PR https://github.com/Microsoft/botbuilder-dotnet/pull/1357 
- [x] Merged

**Javascript SDK**
- [x] PR https://github.com/Microsoft/botbuilder-js/pull/759
- [x] Merged

**Samples**
- [ ] PR
- [ ] Merged

**Docs**
- [ ] PR
- [ ] Merged

[dcr]

**Comment by cleemullins** [comment]
The PR for this in C# was great. More testable, more tests, and non-breaking. 

Let's get the JS version in ASAP.

**Comment by sgellock** [comment]
Both the C# and JS versions have been merged into their respective repos.
