### ISSUE TITLE
Some questions about Bot framework

### ISSUE THREAD

**Issue by EyesHuang** [Microsoft/BotBuilder#529]
Hi, Sir
Here are my questions.

1. How to send message to Channel by program but not Human Manually Input?
2. Is it possible to select bot of channel from Bot framework?
3. How to connect current MSFT bots? 
4. How to combine speech and Bot framework?

Thanks.
Eyes

**Comment by brene** [comment]
Please take a look at the [guidelines for contributing](https://github.com/Microsoft/BotBuilder/blob/master/Contributing.md). 
In order to qualify as an issue, you should append a bug or a suggestion to your issue.

**Comment by v-thgratMSGit** [comment]
Closing this issue. @EyesHuang - please open a new issue with more specific questions if you have them. Thanks!
