### ISSUE TITLE
DirectLine Conversation Ids get expired?

### ISSUE THREAD

**Issue by hpksp** [Microsoft/BotBuilder#5291]
We store conversation ids (direct line) against our application users which will be later used to resume conversations. However, when trying to resume a conversation after keeping them inactive for several days, directline service returns HTTP 404 error. Please refer the [issue](https://github.com/Microsoft/BotBuilder/issues/4657)  where it's mentioned that conversation ids do not expire. Is this the expected behavior?

**Comment by EricDahlvang** [comment]
I am not aware of an expiration for Conversation Ids.  As Dan Driscoll stated here: https://github.com/Microsoft/BotFramework-DirectLineJS/issues/9#issuecomment-283555436

> * **Are conversation IDs valid forever?** The ID doesn't have a lifetime, but the contents of the conversation slowly expire, and I've heard requests for us to support the user/bot sending EndOfConversation, which would terminate communication.

What code are you using to re-connect to the conversation?  What call is resulting in a 404?

**Comment by EricDahlvang** [comment]
Update: apparently conversation ids do now expire.

https://github.com/Microsoft/BotFramework-DirectLineJS/issues/119#issuecomment-445066667

> Conversation messages are only stored for 24 hours in DirectLine. Conversation metadata (such as conversation id and couple other housekeeping data) are removed after a period of inactivity (between 15 to 20 days).

**Comment by hpksp** [comment]
Thanks for the update @EricDahlvang. Well, if that's case, the only option we have is to re-create conversations. Need to figure out a way to expire the user/conversation/private conversation state automatically as well. I'm thinking of using [Time to live](https://docs.microsoft.com/en-us/azure/cosmos-db/time-to-live) feature as we are using CosmosDB for state persistence. Is there a recommended approach?

**Comment by EricDahlvang** [comment]
I'm not aware of a recommended approach to expiring a conversation in Direct Line.  Using [time-to-live](https://docs.microsoft.com/en-us/azure/cosmos-db/time-to-live) sounds like a great idea for the bot and storage side.  Something else might be required for the client.

I'm closing this, as the question has been answered.  Thank you for opening this issue.  I was not aware of the protocol change with expiring conversation ids until today. (I've updated my previous comment)

**Comment by hpksp** [comment]
We will update the client accordingly. Many thanks @EricDahlvang.

**Comment by neetibirla** [comment]
Then how can we handle the old conversation data of the user. If we need to show the transcript history of the user. Is there any recommended way of that ?

**Comment by EricDahlvang** [comment]
@neetibirla If you use TranscriptLoggerMiddleware and a Transcript Store implementation, you can retrieve conversation history at any time and send it to the Direct Line service using the SendConversationHistory  API.  A Node.js example can be found in this closed pull request: https://github.com/Microsoft/BotBuilder-Samples/pull/1266

Mapping multiple conversations to a single user, and managing conversations with conversation history for a specific user is left to the developer.
