### ISSUE TITLE
[Slack Channel] Multiple Slack Apps into Slack channels

### ISSUE THREAD

**Issue by ubreddy** [Microsoft/BotBuilder#5297]
## Issue
*Describe the issue you are addressing*
I would like to register more than on slack app ( to integrate the bot into multiple workspaces where each workspace has the bot app registered separately)
Currently the bot channels allow to register only one client. 
## Proposed change
*Describe the proposed solution*
Provide a way to register more than one slack app as channel to the botframework
## Component Impact 
*Describe which components need to be updated*
Slack Channel
## Customer Impact 
*Describe the impact on customers*
Allow multiple workspaces to utilize the same bot.
## Tracking Status
**Dotnet SDK**
- [ ] PR
- [ ] Merged

**Javascript SDK**
- [ ] PR
- [ ] Merged

**Java SDK**
- [ ] PR
- [ ] Merged

**Python SDK**
- [ ] PR
- [ ] Merged

**Emulator**
- [ ] PR
- [ ] Merged

**Samples**
- [ ] PR
- [ ] Merged

**Docs**
- [ ] PR
- [ ] Merged

**Tools**
- [ ] PR
- [ ] Merged

[dcr]

**Comment by jwiley84** [comment]
Closing this issue as you have already asked it [here](https://stackoverflow.com/questions/54671750/multiple-slack-channel-support-for-botframework). Addiotnally, this repo is currently only taking Design Change Requests (DCR) issues. For submitting **bug fixes** and **feature requests**, please go to the following repo [BotFramework-Services](https://github.com/Microsoft/BotFramework-Services).
