### ISSUE TITLE
Bot Framework now requires endpoints to be HTTPS

### ISSUE THREAD

**Issue by DavePilks** [Microsoft/BotBuilder#530]
Is this something new that was changed? This requirement was not there a few days ago when I first created my bot. Today I tried to change the logo for the bot and it wouldn't let me as it said that my endpoint had to be HTTPS.

**Comment by srijiths** [comment]
Yes ,I also seen this. Right now it seems like they are allowing existing HTTP bots. But its better to migrate.Not sure how long they maintain this.

**Comment by brene** [comment]
Why is this an issue? Because it seems that this should be a standard. 
Please take a look at the [guidelines for contributing](https://github.com/Microsoft/BotBuilder/blob/master/Contributing.md). 
In order to qualify as an issue, you should append a bug or a suggestion to your issue.

**Comment by DavePilks** [comment]
@brene I will append a suggestion then : 

Either notify users that they change has occurred or allow them to have both HTTP and HTTPS endpoints.

**Comment by dandriscoll** [comment]
That's a good observation. I'll make a note that v1 bots upgrading to v3 should consider the HTTPS requirement.

**Comment by v-thgratMSGit** [comment]
Closing this issue. Thanks!

**Comment by JPThorne** [comment]
Same issue here. We're trying to spin up a number of quick demoable bots, and don't have https certs lying around. For a production environment https would be fine, but it is slowing us down in terms of demoing.

**Comment by brene** [comment]
You can try using ngrok. This allows you to easily create an HTTPS tunnel. I use that for all my demos.

**Comment by JPThorne** [comment]
Ah ok cool, thanks. That would work for the emulator hey? Sorry, to be more specific - I'm trying to demo via the messenger channel.

**Comment by brene** [comment]
You just specify your endpoint in your bot directory as the URL that ngrok gives you. That way it should be completely independent of your messenger channels. (Personally tested it a lot on Skype and worked like a charm)

**Comment by JPThorne** [comment]
Ah, awesome! That totally worked. Thanks.

**Comment by deubaka** [comment]
@JPThorne `ngrok` is the way to go as also suggested by the official docs ([localtunnel](localtunnel.github.io/www/) is also one). However, I've quickly found that I was changing the endpoint whenever a new run of `ngrok` is made, so instead, I've just gone through using [Let's Encrypt It](https://letsencrypt.org/) and use their free certs (for 3 months, can be auto-renewed) and have just environment set up to use those cert when run locally.

**Comment by meets7** [comment]
I am using localtunnel for testing from local. It allows you to reserver a static subdomain. eg. xyz.localtunnel.me using the --subdomain option. 
`eg. lt --port 5000 --subdomain mycompany
`That way you don't have to change the bot settings everytime.
