### ISSUE TITLE
Max size limit for attachment and message using Direct-line channel 

### ISSUE THREAD

**Issue by pranavdhundhia** [Microsoft/BotBuilder#5302]
What is the max size for conversation message(MAX_MESSAGE_LENGTH) and Max size for File attachment (MAX_FILE_SIZE) using direct line connection. 
Any why to limit MAX_MESSAGE_LENGTH and  MAX_FILE_SIZE with direct line configuration.

Please let me know if you have any of the information. Thank You

**Comment by CoHealer** [comment]
Per [https://docs.microsoft.com/da-dk/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-api-reference?view=azure-bot-service-3.0#activities](url)
The total size of the activity, when serialized to JSON, must not exceed 300K characters.

This thread asserts the attachment limit is 4MB:
https://github.com/Microsoft/BotFramework-WebChat/issues/789 

It refers to this (although it doesn't official state the limit):
https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-send-activity?view=azure-bot-service-4.0#upload-attachments

These values are not configurable & anything > than 4MB should be hosted elsewhere.
