### ISSUE TITLE
The deployment procedure of downloading a .bot file to overwrite my local .bot file is counter-intuitive

### ISSUE THREAD

**Issue by brandonh-msft** [Microsoft/BotBuilder#5311]
Following the deployment guidance [here](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0), I am instructed to create a bot in Azure, then download the .bot file from it to overwrite my local one. But I already have a bot locally, I also already have a .bot file in this local bot. Why am I having to create a .bot file out on the portal then download that and stamp it over top? This feels unnatural and unnecessary. I should simply be able to push the bot I've created & tested locally out to the service on which I wish to host it.

**Comment by sgellock** [comment]
There will be an update to the Azure portal that will stop using .bot files, as this is our model moving forward, starting with 4.3.  The applications settings that currently live in .bot files will not moved into appsettings.json or .env files for C# and JS respectively

**Comment by brandonh-msft** [comment]
@sgellock can you check your last sentence there? Not sure if that's supposed to be "will get moved" or "will not be moved" :) thanks!

**Comment by sgellock** [comment]
@brandonh-msft thanks for calling that out.  I've updated my grammatical errors.  TL;DR:  .bot files are not what we are recommending you use for application configuration settings.  some customers find value in the .bot file, and for those customers that do, then they option exists.  but for the large majority of customer feedback we've gotten, language/platform existing mechanism are expected and preferred.  e.g. appsettings.json and .env files
