### ISSUE TITLE
DCR: Add support for LINE in the SDK

### ISSUE THREAD

**Issue by iMicknl** [Microsoft/BotBuilder#5313]
## Issue
The [Line channel](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-line?view=azure-bot-service-4.0) just got released, but the SDK (JS/.NET) is missing channel specific context.

## Proposed change
Add a channel constant for LINE and a buttonCount / cardCount for `SupportsSuggestedActions` and `SupportsCardActions`

## Component Impact 
[Connector.Channels](https://github.com/Microsoft/botbuilder-dotnet/blob/c3297158bc9ff8148c9e221719b3ffe564a82227/libraries/Microsoft.Bot.Connector/Channels.cs)
[Channel.cs](https://github.com/Microsoft/botbuilder-dotnet/blob/28f6c88a02c86ea01f01b140eeed5f5fd1b009fb/libraries/Microsoft.Bot.Builder.Dialogs/Choices/Channel.cs)

## Customer Impact 
No breaking changes, just resolves issues like https://github.com/Microsoft/BotFramework-Services/issues/56

## Tracking Status
**Dotnet SDK**
- [x] PR
- [x] Merged

**Javascript SDK**
- [x] PR
- [x] Merged

[dcr]

**Comment by youyu16** [comment]
@iMicknl max number of suggested actions should be 13 and max number of card action should be 4 depend on LINE document.

**Comment by cleemullins** [comment]
As an amusing coincidence, I'm creating these Issues now for tracking.

**Comment by EricDahlvang** [comment]
@youyu16 I've tested these, and the max Suggested Actions for Line is indeed 13, however the Maximum Number of Card Actions appears to be much larger:

![image](https://user-images.githubusercontent.com/11055362/54777734-39696500-4bd0-11e9-985f-286d83aac75e.png)


Has this changed since your last comment?

**Comment by youyu16** [comment]
@EricDahlvang Most of the cards are LINE flex card.  it's not have the clear limitation on these card actions with one exception, the animation card. LINE don't have the it natively and flex card only support jpg and png. So animation card will be the template message in LINE, and template message have a clear limitation on action number(up to 4). 
To be honest, LINE only support jpg and png in cards depend on there document, but actually template message support gif and short video depend on my test.
![image](https://user-images.githubusercontent.com/17819112/54797202-23ba7500-4c8e-11e9-93f9-3455012db224.png)

![image](https://user-images.githubusercontent.com/17819112/54797472-3aad9700-4c8f-11e9-8566-6409074db5d9.png)
