### ISSUE TITLE
[BUG] session.beginDialog(...) wrong behavior

### ISSUE THREAD

**Issue by brene** [Microsoft/BotBuilder#532]
Hi, 

I have conducted a few thorough tests to determine this issue. Essentially it boils down to this:
```javascript
helloBot.add('/', new builder.CommandDialog().matches('^profile', '/profile'));
```
is not the same as 
```javascript
helloBot.add('/', new builder.CommandDialog().matches('^profile', 
    builder.DialogAction.beginDialog("/profile")));
```

To give you a detailed analysis let's look at this: I have a root dialog "/" and a dialog "/profile" that should begin from "/".
Working code:
```javascript
var builder = require('botbuilder');
var helloBot = new builder.TextBot();

helloBot.add('/', new builder.CommandDialog().matches('^profile', '/profile'));

helloBot.add('/profile', builder.DialogAction.endDialog("ending"));
```
Using this snippet, I started the conversation in "/" and entered into "/profile" by typing "profile" then it should just go back to the "/" and could continue typing "profile" again to get back into the profile dialog.

But when I use this method to begin a new Dialog:
```javascript
var builder = require('botbuilder');
var helloBot = new builder.TextBot();

helloBot.add('/', new builder.CommandDialog().matches('^profile', 
    builder.DialogAction.beginDialog("/profile")));

helloBot.add('/profile', builder.DialogAction.endDialog("ending"));
```
or this:
```javascript
helloBot.add('/', new builder.CommandDialog().matches('^profile', function(session) {
  session.beginDialog('/profile');
}));
```
it would would end the entire conversation. Meaning also ending "/" dialog.
I believe that the expected behavior is like a stated in the working code, not like it's in the second code snippet.
Therefore the examples on this [official tutorial page](http://docs.botframework.com/builder/node/guides/core-concepts/#handling-commands) doesn't even work. 
In this example it would just quit after the user enters "John Smith". Like it is shown in this image.
![image](https://cloud.githubusercontent.com/assets/4989523/16306383/ce68950a-395d-11e6-880d-36fc7297ca13.png)
This is a different output than the one shown on the website here:
![image](https://cloud.githubusercontent.com/assets/4989523/16306410/e818f44a-395d-11e6-9372-ac8893d307b8.png)

Also interesting to note that calling this:
```javascript
helloBot.add('/', new builder.CommandDialog().matches('^profile', function(session) {
  builder.DialogAction.beginDialog('/profile');
}));
```
does nothing at all. As in it's not beginning a new dialog or ending the current one.

**Comment by JacopoDaeli** [comment]
Same guys. After a bit of research I realised that `this.delayedEmit('quit');` is called in `Session.prototype.endDialog`. Anyone fixed this already?

**Comment by JacopoDaeli** [comment]
To be more precise:

[Session.prototype.endDialog]
```
else {
            this.send(m);
            if (r.error) {
                this.emit('error', r.error);
            }
            else {
                if (!result) {
                  this.delayedEmit('quit');
                }
            }
        }
```

**Comment by brene** [comment]
This problems seems to be solved with the V3. So I'll close this issue.

**Comment by Stevenic** [comment]
Good to hear
