### ISSUE TITLE
Skype web control suddenly not working

### ISSUE THREAD

**Issue by lemonkazi** [Microsoft/BotBuilder#5325]
I used Skype Web Control Generator in order to integrate video call in my html page. Everything was working perfectly until some days ago, when the skype button disappeared and i got the following error:

"GET https://swc.cdn.skype.com/vendors/uicomponent-bundle.js  net::ERR_ABORTED 404".

Can you help me in fixing it ?
I have connected skyway by below code
```
<script type="text/javascript" src="https://cdn.webrtc.ecl.ntt.com/skyway-latest.js"></script>
        <script type="text/javascript" src="<?php echo $BASE_URL ?>/skyway/js/skyway.js"></script>
        <script type="text/javascript" src="<?php echo $BASE_URL ?>/skyway/js/skyway-setup.js"></script>
```
thanks

**Comment by jwiley84** [comment]
Hi @lemonkazi ! We've noticed the issue and are tracking here: https://github.com/Microsoft/BotBuilder/issues/5324

I'm going to close this so it's all centralized in one location.
