### ISSUE TITLE
[Question] How can I setup intent?

### ISSUE THREAD

**Issue by angie4u** [Microsoft/BotBuilder#5328]
I setup the dashboard using Application Insights Key, but the intent value is not loaded, so I cannot retrieve conversation history!
![image](https://user-images.githubusercontent.com/16282358/54706853-3ac07080-4b83-11e9-923e-e0e15a4f3ba0.png)
Is there any way to solve this situation? :)

**Comment by Zerryth** [comment]
connecting with Dave

**Comment by Zerryth** [comment]
Hey @angie4u apologies for the delay! Got caught up in multiple tasks of course.

Is this still an issue for you or have you and the customer gotten passed it now?
