### ISSUE TITLE
[Feature Tracking] Add the optional HTTP Security Header for Firewall Traversal

### ISSUE THREAD

**Issue by cleemullins** [Microsoft/BotBuilder#5331]
Add the optional HTTP Security Header for Firewall Traversal

# Tracking

## v3 SDK
- [x] v3 C# SDK
- [x] v3 Javascript SDK

## v4 SDK
- [x] v4 C# SDK
- [x] v4 Javascript SDK
- [ ] v4 Python SDK
- [ ] v4 Java SDK

**Comment by cleemullins** [comment]
V3 C# Commit [is here](https://github.com/Microsoft/BotBuilder-V3/commit/a2a261e822dbf88eb58e82be364cd3d0da35f20c).

**Comment by cleemullins** [comment]
JS v3 change is merged. https://github.com/Microsoft/BotBuilder-V3/pull/80/files

**Comment by mingweiw** [comment]
C# v4 change is merged. https://github.com/Microsoft/botbuilder-dotnet/pull/1576

**Comment by cleemullins** [comment]
JS V4 PR is here: 
https://github.com/Microsoft/botbuilder-js/pull/841

**Comment by cleemullins** [comment]
The Tracking issue for Python SDK is here:
https://github.com/Microsoft/botbuilder-python/issues/136

The Tracking issue for Java SDK is here:
https://github.com/Microsoft/botbuilder-java/issues/72

**Comment by cleemullins** [comment]
Closing this as completed, as it's done in the main SDKs with tracking issues in the Preview platforms.
