### ISSUE TITLE
[LUIS] Luis does not recognize German numbers properly 

### ISSUE THREAD

**Issue by PeterSchoell** [Microsoft/BotBuilder#5332]
## Issue
Attempt to convert the Recognizer result to an integer. This SHOULD works for "a dozen", "twelve", "12", and so on.  Correspondingly for the German terms like "Zwölf" or "Zehn"

const results = Recognizers.recognizeNumber(input, Recognizers.Culture.German);

This works fine for English culture, but not for German culture.

## Proposed change
Add German prebuilt entities

See also https://github.com/Microsoft/BotBuilder/issues/3540

**Comment by iMicknl** [comment]
Are you using the .NET (C#) or Javascript?

**Comment by PeterSchoell** [comment]
> Are you using the .NET (C#) or Javascript? The source of the Recognizers can be found in the [following repo](https://github.com/Microsoft/Recognizers-Text).

I use Javascript

**Comment by iMicknl** [comment]
I would recommend creating an issue in the [Recognizers-Text repository](https://github.com/Microsoft/Recognizers-Text). It looks like `Zwölf` (12) and `Zehn` (10) are already recognized as a number in the .NET version, didn't try the latest Javascript yet.

Do you also face this issue in LUIS or are you trying to achieve this using the local recognizer?

**Comment by anusharavindrar** [comment]
Closing the issue due to unresponsive user. If you are experiencing the issue in LUIS itself and not the bot and need further assistance, then you can file the issue in the [Recognizers-Text repository. ](https://github.com/Microsoft/Recognizers-Text)
