### ISSUE TITLE
Bot State seems to be messed up. Dialog not working as expected

### ISSUE THREAD

**Issue by sagnikm95** [Microsoft/BotBuilder#5336]
I am using SDK V3 version 3.15.3.  In my bot I am simulating a conversation flow using Dialogs. But instead of hitting the call back function mentioned in context.wait(), after hitting Message.Controller the control is going to StartAsync function in my root dialog and as a result the whole dialog flow is restarting from the beginning rather than proceeding to the function mentioned in the callback for context.wait(). This behavior is also quite random as in few cases ( specially when debugging locally) the bot is acting as expected.

**Comment by EricDahlvang** [comment]
Hi @sagnikm95 

I'm sorry you've run into this issue.  We will address your duplicate question here: https://github.com/Microsoft/BotBuilder-V3/issues/127

In the future, please note: the Bot Framework Support team monitors both repositories, so there is no need to cross-post.
