### ISSUE TITLE
BotAddedToConversation in Slack

### ISSUE THREAD

**Issue by wiltodelta** [Microsoft/BotBuilder#534]
I install new bot for the team and select channel #general. Bot does not receive BotAddedToConversation event.

**Comment by craigjensen** [comment]
The "Add To Slack" button authorizes a bot on a Slack team but does not actually add the bot to any Slack channels.  You still have to use the "/invite @botname" command to add the bot to a channel at which time your bot should receive the BotAddedToConversation event.

**Comment by berhir** [comment]
There seems to be a problem with the slack implementation. Since at least five days we do not receive the BotAddedToConversation event when we add our bot to a new channel.

**Comment by wiltodelta** [comment]
@craigjensen No. When you add bot for team, you need select channel. The BotAddedToConversation event not fired.

**Comment by craigjensen** [comment]
There are two issues here.  

First, while the UX does ask for a channel during registration, the bot is NOT added to the channel so the BotAdded event is not fired.  A bug has been opened to address this.

Second, when you /invite a bot to a channel, that's when the event should get fired.  We'll look into this and file a bug if it's not firing as expected.

**Comment by berhir** [comment]
@craigjensen We tested it Yesterday and it is working again. Thanks for fixing this!
