### ISSUE TITLE
How can I forcibly shut down a conversation with a user?

### ISSUE THREAD

**Issue by vaditya04** [Microsoft/BotBuilder#535]
Question says it all.

If context is needed (though if someone answers it without reading the text below it's totally fine)...

I need to get users from two different channels talking to each other using the bot as an intermediary (see Issue #497 )

user1 sends message to user2's channelaccount, starting a new conversation for user2 in the process.

user2 replies, in which the message is addressed to user1 in his current conversation id.

The problem here is that m2 is not visible to User1 until he interacts with the bot (Issue #536). I'm not sure why.

My solution is to shut down user1's conversation after he messages user2. user2 will do the same thing, and so on.

(Note: assume they have each others' channel accounts)

**Comment by tomlm** [comment]
User 1 talks to Bot on Conversation X
User 2 talks to Bot on Conversation Y
When a message comes in from User 1 on Conversation X, bot should send a new message with User2 Conversation Y 
When a message comes in from User 2 on Conversation Y, bot should send a new message with User1 Conversation X

This should work, we've had people do this before

**Comment by vaditya04** [comment]
@tomlm Thanks for the response, reason why I'm asking for this is because of Issue #536)

User 1 talks to bot which messages User 2 on conversation Y, what happens is User 2 doesn't see anything. But when User 2 talks to the bot, both the User 1 message and the bot's response appear on screen for User 2

(This is happening on Web chat)

**Comment by vaditya04** [comment]
@tomlm Also, are there any code samples I can look at, if people have done this before?
