### ISSUE TITLE
Getting 403 forbidden when trying to use the bot in teams but works in bot framework emulator

### ISSUE THREAD

**Issue by theCorb1nator** [Microsoft/BotBuilder#5373]
Hi,

I have created a Bot using the BotBuilder SDK.

I am getting a 403 forbidden error shown in ngrok when trying to use the bot in teams.

I have ngrok running and have tested using the Bot Framework Emulator connected to the ngrok endpoint and it behaves as it should

Is there a reason why it would be returning a 403.. its as if the bot does not have permission ?

**Comment by dmvtech** [comment]
@theCorb1nator This is likely because _something_ is not lined up somehow. Typically this could be the botFilePath, botFileSecret, MicrosoftAppId or MicrosoftAppPassword. 

Does the Test in Web Chat functionality work? Are you using a .bot file (being phased out currently), or handing configuration in the code?

**Comment by theCorb1nator** [comment]
> @theCorb1nator This is likely because _something_ is not lined up somehow. Typically this could be the botFilePath, botFileSecret, MicrosoftAppId or MicrosoftAppPassword.
> 
> Does the Test in Web Chat functionality work? Are you using a .bot file (being phased out currently), or handing configuration in the code?

You are correct. i did not put my AppId, Password in the .bot file, it works now 

What do you mean by its being phased out? whats the alternative.. appsettings.json?

**Comment by dmvtech** [comment]
> What do you mean by its being phased out? whats the alternative.. appsettings.json?

That's exactly correct. See documentation [here](https://docs.microsoft.com/en-us/azure/bot-service/bot-file-basics?view=azure-bot-service-4.0&tabs=csharp).
