### ISSUE TITLE
[NodeJs] Emulator/Web Chat Client is not able to connect to HTTPS

### ISSUE THREAD

**Issue by srijiths** [Microsoft/BotBuilder#539]
I registered a new bot with HTTPS end point. Created a self signed certificate and key for my node restify server. Then i instantiate the HTTPS node server. But when i am trying to connect with Emulator and Web Chat Client its not able to connect to my Bot. Its throwing exceptions
![01](https://cloud.githubusercontent.com/assets/1046319/16328787/27829da0-39fb-11e6-891c-4de5e7fab858.png)
![02](https://cloud.githubusercontent.com/assets/1046319/16328789/2d4796aa-39fb-11e6-96f6-1256fbbdb944.png)

I think , since i am using MSFT Web Chat Client , i am unable to do much on this. Is it possible to force authenticate ? Or is there any thing i should consider when using HTTPS Bot and Web Chat Client ?

**Comment by willportnoy** [comment]
It may be easiest to get a signed certificate that can be validated - otherwise the web chat and emulator code would have to be changed to allow connections where the https stack could not validate it; for example, that there wasn't a "man in the middle" attack.

**Comment by srijiths** [comment]
@willportnoy I understand about the security loop hole which i am talking about. But why i raised this issue is because , a C# bot published to Azure is still able to access using HTTP. Its not demanding for HTTPs. What about i am deploying my bot not in Azure and creating a HTTPS server with certificate and key ? Can you please clarify and give me some pointers on this.

**Comment by srijiths** [comment]
@willportnoy Yes , i understand the security look hole which am talking about. Please clarify below points

1. Is a self-signed certificate not acceptable ?
2. A HTTPS registered Bot published on Azure is operating on HTTP ? with out any certificate issues ?

Thanks

**Comment by willportnoy** [comment]
1. For https, we use the default ServicePointManager.ServerCertificateValidationCallback from the framework which checks the certificate.
2. There is no certificate involved in the http protocol.  I don't know all of the details of the extent of our intended support for http.

**Comment by willportnoy** [comment]
I'm going to close this issue for now, but feel free to re-open another issue if you have more questions.
