### ISSUE TITLE
Detect ongoing Conversation Channel

### ISSUE THREAD

**Issue by loretoparisi** [Microsoft/BotBuilder#540]
I'm trying to keep my bot as possible as general purpose. I'm not going to use `BotKit` for `Slack` etc. I prefer to go with `BotBuilder.BotConnectorBot` and `bot.listen`.
Said, that, when connected on multiple channels like `Skype` and `Slack`, how to detect which channel the ongoing conversation belongs to?

**Comment by tomlm** [comment]
there is a property on every message called channelId which will have "skype" or "slack" in it.

**Comment by loretoparisi** [comment]
@tomlm could you please point me to the relative docs?
Thank you.

**Comment by tomlm** [comment]
http://docs.botframework.com/connector/channelaccounts/#navtitle
