### ISSUE TITLE
DialogState is not being cleared allowing me to move on to a new Dialog

### ISSUE THREAD

**Issue by nate-garvey** [Microsoft/BotBuilder#543]
I implemented a similar version of authentication that the sample facebook solution uses.  After the user logs in, I want to then switch to a LuisDialog.  However, the app gets stuck on the authentication dialog and never presents the LuisDialog.

			if (message.Type == "Message")
			{
				string authToken = message.GetBotPerUserInConversationData<string>(SignInDialog.AuthTokenKey);
				if (String.IsNullOrEmpty(authToken))
				{
					return await Conversation.SendAsync(message, () => SignInDialog.Dialog, cancellationToken);
				}

				return await Conversation.SendAsync(message, () => new ManagerDialog() { UserName = message.From.Name }, cancellationToken);
			}
			else
			{
				
and then in the callback, I end the dialog by calling context.Done();

		private async Task MessageReceivedAsync(IDialogContext context, IAwaitable<Message> argument)
		{
			var msg = await (argument);
			if (msg.Text.StartsWith("token:"))
			{
				// Dialog is resumed by the OAuth callback and access token
				// is encoded in the message.Text
				var token = msg.Text.Remove(0, "token:".Length);
				context.PerUserInConversationData.SetValue(SignInDialog.AuthTokenKey, token);

				await context.FlushAsync();
				context.Done(token);
			}
			else
			{
				await this.SignIn(context);
			}
		}

![image](https://cloud.githubusercontent.com/assets/5540179/16343811/e45fa7bc-39fe-11e6-8991-c5a4bd00fd04.png)

**Comment by v-thgratMSGit** [comment]
Closing this issue due to age. @nate-garvey - please open a new issue if this issue is not fixed and needs further discussion. Thanks!
