### ISSUE TITLE
Url preview in skype doesn't work

### ISSUE THREAD

**Issue by irynabond** [Microsoft/BotBuilder#544]
Hello,
I have built the bot and connected it to skype.  That bot will respond with sending some images (urls)  to the user. (it's the most important functionality of my bot). I want these urls to be displayed for user as images, but now url is displayed as text. 
To send pictures I used the following syntax:
`        await context.PostAsync("![picture](" + imageUrl + ")");             `   
In my case:
` await context.PostAsync("![Show picture](https://cdn.traitify.com/slides/01de2be5-aa86-48c3-ba1e-53a74d0f964b/desktop)");       `        
This is the result in [skype]( https://s32.postimg.org/63ojya4xh/url.png). This is desirable [result](https://s32.postimg.org/o66nytnqt/res_PNG.png)
Reference [dev.botfrmaework.com](http://docs.botframework.com/connector/message-content/#navtitle), The Text property is Markdown section (image link `![duck](http://aka.ms/Fo983c)`  ) clearly mention how to link an image to reply message.      
But it doesn't work for me. I am using Skype for Windows. 

Also I noticed that 'Getty Images - Preview' bot in Skype has this feature. When I send request (some word), the bot responds by sending picture link and this link is [displayed as image](https://s32.postimg.org/lwy5gfm4l/getty.png)

How can I do the same in case with my bot?

Thank you in advance,
Iryna Bondarenko

**Comment by tomlm** [comment]
Skype doesn’t the ability to have images inline in text, and so when we render the markdown the image is rendered as a link.  To send an image via skype you need to use add an Attachment with ContentType,ContentUrl properties

**Comment by irynabond** [comment]
Thank you, it works!
