### ISSUE TITLE
I am not getting response in Skype, where as i can get it in Web chat

### ISSUE THREAD

**Issue by prakashin77** [Microsoft/BotBuilder#545]
I have deployed the sample solution provided. Then i have configured Skype, web chat. However after deploying i am able to receive responses from web chat but not from skype. Please Help.
TIA

**Comment by msft-shahins** [comment]
@prakashin77 do you still have the issue? Can you provide your bot id?

**Comment by prakashin77** [comment]
Hi Shahin,

Thanks for replying.
My BOT ID: ctsssamplebot

**Comment by craigjensen** [comment]
What did you set for the Application Id and Messaging webhook when you created your Skype bot at https://developer.microsoft.com/en-us/skype/bots ?

**Comment by prakashin77** [comment]
Please find the attached image
![image](https://cloud.githubusercontent.com/assets/11087990/16400259/92aa641a-3c8e-11e6-907b-6bc6f6880ed4.png)

**Comment by craigjensen** [comment]
Looks like your webhook callback is not correct.  Make sure it matches the value from the Skype channel developer configuration page https://skype.botframework.com/Dev/?botId=ctsssamplebot

**Comment by prakashin77** [comment]
Hi craigjensen,
I just updated the call back messaging Url and its working now. Thanks for the pointer.
Can you please point me for a sample code that reads the value from user and responds to it (a two way communication) and also the way for connecting with LUIS

**Comment by msft-shahins** [comment]
@prakashin77 you can look at the [EchoBot](https://github.com/Microsoft/BotBuilder/tree/master/CSharp/Samples/EchoBot) for a simple bot that echos back what the user say, and [SimpleAlarmBot](https://github.com/Microsoft/BotBuilder/tree/master/CSharp/Samples/SimpleAlarmBot) on how to use Luis. For node.js equivalent, you can look at [basics-firstRun](https://github.com/Microsoft/BotBuilder/blob/master/Node/examples/basics-firstRun/app.js) and [basics-naturalLanguage](https://github.com/Microsoft/BotBuilder/blob/master/Node/examples/basics-naturalLanguage/app.js).
