### ISSUE TITLE
[Question] How to make user2user chat and ignore their utterances in LUIS learning

### ISSUE THREAD

**Issue by OleksandrBezhan** [Microsoft/BotBuilder#547]
I want to join 2 users in a chat in facebook messenger. Basically two users ask my bot to start a chat with a stranger and the bot "links" them, so that when the first user writes something, the bot sends this message to the second user.

Technically what I do is once the user expressed intent to join a chat, I do something like `beginDialog("/chat/conversation")` and all the messages go there until the user ends the chat.

My question is how can I tell LUIS to ignore those messages and don't inlcude them as utterances?

**Comment by willportnoy** [comment]
I wonder if you could use replaceDialog to change your root dialog from a LUIS dialog to a conversation dialog - @Stevenic is that correct?

**Comment by v-thgratMSGit** [comment]
Closing this issue due to age. @OleksandrBezhan - please open a new issue if this issue is not fixed and needs further discussion. Thanks!
