### ISSUE TITLE
LUIS entity contains punctuation in its name

### ISSUE THREAD

**Issue by OleksandrBezhan** [Microsoft/BotBuilder#548]
So I have an entity called `Hero` and it may have value "D.Va". The problem is that LUIS recognizes it as two different entities: "d" and ". va". I tried to help him by creating Phrase List Feature called `Heroes` and putting "D.VA" there as one of values, but no luck. 

How can I make LUIS recognize it as a single entity ?

**Comment by alex182** [comment]
Just highlight all of "d .va" with your cursor and then you should be able to choose the entity you want to label it as.  I was having issues with this earlier as well.

**Comment by willportnoy** [comment]
If you want to access the LUIS experts, you may also want to post on the LUIS forum: https://social.msdn.microsoft.com/forums/azure/en-US/home?forum=LUIS

**Comment by willportnoy** [comment]
I'm going to close this issue for now, but feel free to re-open another issue if you have more questions.

If you did post to the LUIS forum, you might consider leaving a link here for future searchers.  Thank you!
