### ISSUE TITLE
Is there a way to set the LuisModel modelId and subscriptionKey outside of the class attribute.

### ISSUE THREAD

**Issue by cmchenry** [Microsoft/BotBuilder#549]
I'm wanting to check a sample I built into Github, but I don't want to checkin the modelId and subscriptionKey.  Is there a way to set the LuisModel attributes in code (so I can do it through appsettings?

**Comment by willportnoy** [comment]
The LuisDialog constructor

https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Dialogs/LuisDialog.cs#L130

takes ILuisService implementations

https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Luis/LuisService.cs#L78

which you can construct with a "new LuisModelAttribute()"

https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Luis/LuisModel.cs#L48

with values from somewhere other than your checked-in code.

**Comment by willportnoy** [comment]
I'm going to close this issue for now, but feel free to re-open another issue if you have more questions.

**Comment by cmchenry** [comment]
Thanks, overriding the constructor with the LuisModelAttribute was perfect!

**Comment by davidlfox** [comment]
I don't quite follow @willportnoy's recommendation or @cglong's enhancement--do you have a gist or sample for this type of implementation? @cmchenry makes a good point about not storing keys in source control!

**Comment by cglong** [comment]
@davidlfox, @willportnoy's suggestion is basically to instantiate your own `LuisModelAttribute` using `modelId`s and `subscriptionKey`s obtained from elsewhere. For instance, you can store them in a [file referenced by your `Web.config`](https://msdn.microsoft.com/en-us/library/aa903313(v=vs.71).aspx) that doesn't get checked into source:

````csharp
var modelId = ConfigurationManager.AppSettings.Get("LuisModelId");
var subscriptionKey = ConfigurationManager.AppSettings.Get("LuisSubscriptionKey");
var luisModel = new LuisModelAttribute(modelId, subscriptionKey)
var dialog = new MyDialog(new LuisService(luisModel));
````

My change was mostly to handle Inversion of Control scenarios (e.g. [Unity](https://github.com/unitycontainer/unity)). We have a custom class that implements `ILuisModel`, which gets injected into the `LuisService` constructor, which is then used when instantiating our Dialog.
