### ISSUE TITLE
Error Registering a Bot: Error converting value {null} to type 'System.Int32'...

### ISSUE THREAD

**Issue by designdit** [Microsoft/BotBuilder#550]
Hello,

I'm trying to register a bot and have filled in all of the required fields as per https://dev.botframework.com/bots/new. I was able to successfully register two bots several weeks ago, but as of yesterday encounter this error:

Error converting value {null} to type 'System.Int32'. Path 'value[0].subscriptionsLimit', line 1, position 203.

Prior to this (about a week ago), I had registered a bot with the same name and Bot ID and as far as I know it registered successfully, however, I was automatically logged out and yesterday, when I logged in again, the bot did not appear under "My bots". So, I tried to register it (again). I initially received a message that the Bot ID is not available. I tried again with a slightly different Bot ID but everything else the same, and now receive the message mentioned above.

I suspect that the bot name and/or ID are somehow partially registered or somehow locked but not completely registered. Could someone contact me so that I can share more info to help check? I have tried MS chat and phone support, they couldn't provide botframework help.

Thank You

**Comment by dandriscoll** [comment]
Yes, we're working on this now.

**Comment by dandriscoll** [comment]
Bot creation is reenabled. We've been looking in to the missing bot problem but haven't pinned it down yet.

**Comment by designdit** [comment]
Thank you - was able to create the bot and was able to use the original bot ID I wanted (did not receive a message that the ID was unavailable).  The new bot appears under "My bots" now.  I'm closing this issue.  Thanks
