### ISSUE TITLE
Tasks - Tasks can be fetched

### ISSUE THREAD

**Issue by Virtual-Josh** [Microsoft/BotBuilder#5508]
- [x] C#
- [ ] JavaScript

https://docs.microsoft.com/en-us/microsoftteams/platform/#pivot=samples-demos-templates

**Comment by EricDahlvang** [comment]
Apparently Teams does not like how HttpHelper.WriteResponse is creating the Content:

```cs
response.Content = new ObjectContent(
                        invokeResponse.Body.GetType(),
                        invokeResponse.Body,
                        BotMessageMediaTypeFormatters[0]);
```

Eventually got it to work with:

```cs
_request.CreateResponse(HttpStatusCode.OK, taskEnvelope);
```

See hack here: [TeamsBot.cs#L60](https://github.com/microsoft/BotBuilder-Samples/blob/teams-samples/experimental/teams/csharp-dotnetcore/Scenarios/TaskModule_NetFramework/Microsoft.Teams.Samples.TaskModule.Web/Bots/TeamsBot.cs#L60)


A similar issues exists with Microsoft.Bot.Builder.Integration.AspNet.Core

**Comment by EricDahlvang** [comment]
Got passed the serialization issue with @johnataylor 's help.

```cs
_request.CreateResponse(HttpStatusCode.OK, taskEnvelope);
```
was serializing enums as strings:
```json
{
  "task": {
    "value": {
      "url": "https://1df911ea.ngrok.io/youtube",
      "title": "Microsoft Ignite 2018 Vision Keynote",
      "height": 700,
      "width": 1000,
      "fallbackUrl": "https://1df911ea.ngrok.io/youtube"
    },
    "type": "continue"
  }
}
```

 while HttpHelper.WriteResponse is serializing enums as int (see "type":1):

```json
{"task":{"value":{"url":"https://1df911ea.ngrok.io/youtube","title":"Microsoft Ignite 2018 Vision Keynote","height":700,"width":1000,"fallbackUrl":"https://1df911ea.ngrok.io/youtube"},"type":1}}
```

Adding [JsonConverter(typeof(StringEnumConverter))] to TaskType for TeamsTask resolved the issue:

```cs
    public class TeamsTask
    {
        [JsonProperty("value")]
        public TaskInfo TaskInfo { get; set; }

        [JsonProperty("type")]
        [JsonConverter(typeof(StringEnumConverter))]
        public TaskType Type { get; set; }
    }
```

**Comment by EricDahlvang** [comment]
https://github.com/microsoft/BotBuilder-Samples/blob/teams-samples/experimental/teams/csharp-dotnetcore/Scenarios/TasksModule_NetCore/TeamsTasksBot/Bots/TasksBot.cs#L57
