### ISSUE TITLE
Tasks - Submit action works for adaptive cards (Action.Submit)

### ISSUE THREAD

**Issue by Virtual-Josh** [Microsoft/BotBuilder#5509]
- [x] C#
- [ ] Javascript

**Comment by EricDahlvang** [comment]
C# scenario example:

[OnTaskModuleSubmitAsync](https://github.com/microsoft/BotBuilder-Samples/blob/teams-samples/experimental/teams/csharp-dotnetcore/Scenarios/TaskModule_NetFramework/Microsoft.Teams.Samples.TaskModule.Web/Bots/TeamsBot.cs#L78)
