### ISSUE TITLE
Stability of BotBuilder?

### ISSUE THREAD

**Issue by Orbyt** [Microsoft/BotBuilder#551]
Hi all, BotBuilder looks intruiging, how stable is the platform? It's quite new and as such there aren't too many resources on it yet.

Are there any well known bots built on it? (Other than the showcase ones)

**Comment by DavePilks** [comment]
For the most part I have found it pretty stable if your bot is simple enough. I have some serious issues when I try to make async calls inside the bot though.

**Comment by willportnoy** [comment]
@DavePilks I understand this is in reference to https://github.com/Microsoft/BotBuilder/issues/513 - but in generic, async methods are just fine.  In fact, all of the dialog methods fit the pattern of an async (task-returning) method:

Task MethodName(IDialogContext context, IAwaitable<T> item)

**Comment by willportnoy** [comment]
I'm going to close this issue for now, but feel free to re-open another issue if you have more questions.
