### ISSUE TITLE
Tasks - Submit work for Bot Framework card (Task card)

### ISSUE THREAD

**Issue by Virtual-Josh** [Microsoft/BotBuilder#5510]

**Comment by EricDahlvang** [comment]
C# scenario example:

[OnTaskModuleSubmitAsync](https://github.com/microsoft/BotBuilder-Samples/blob/teams-samples/experimental/teams/csharp-dotnetcore/Scenarios/TaskModule_NetFramework/Microsoft.Teams.Samples.TaskModule.Web/Bots/TeamsBot.cs#L78)
