### ISSUE TITLE
Tasks - Bot sends card with deeplink

### ISSUE THREAD

**Issue by Virtual-Josh** [Microsoft/BotBuilder#5513]
- [ ] C#
- [ ] Javascript

**Comment by EricDahlvang** [comment]
C# Adaptive Card scenario example:

https://github.com/microsoft/BotBuilder-Samples/blob/teams-samples/experimental/teams/csharp-dotnetcore/Scenarios/TaskModule_NetFramework/Microsoft.Teams.Samples.TaskModule.Web/Bots/TeamsBot.cs#L133

C# Thumnail Card scenario example:

https://github.com/microsoft/BotBuilder-Samples/blob/teams-samples/experimental/teams/csharp-dotnetcore/Scenarios/TaskModule_NetFramework/Microsoft.Teams.Samples.TaskModule.Web/Bots/TeamsBot.cs#L186
