### ISSUE TITLE
Wrong property name.

### ISSUE THREAD

**Issue by vvatanabe** [Microsoft/BotBuilder#552]
Property name of the Session class is different in botbuilder.d.ts
Look at the following:

current => Session#ISessionState
correct => Session#sessionState

https://github.com/vvatanabe/BotBuilder/blob/master/Node/src/botbuilder.d.ts#L746

**Comment by v-thgratMSGit** [comment]
Closing this issue. Thanks!

**Comment by Stevenic** [comment]
I don't see where this issue is
