### ISSUE TITLE
Build2016 Bot

### ISSUE THREAD

**Issue by GrischaJJ** [Microsoft/BotBuilder#553]
Hi,

would it be possible to share the bot you deployed for Build2016?
https://bots.botframework.com/bot?id=BuildBot

king regrads

**Comment by ronnelsantiago** [comment]
was looking for the same, all i can found are these.. https://github.com/Microsoft/BotBuilder/tree/master/CSharp/Samples. anyone...???

**Comment by jameslew** [comment]
The BuildBot sample as it stands was put together specifically for Build and before we had a number of our design patterns in place.  We're looking at putting out a similar sample, but don't have anything ready quite yet.
