### ISSUE TITLE
Guide to Publish Bot with Node on Azure?

### ISSUE THREAD

**Issue by thewhitetulip** [Microsoft/BotBuilder#556]
On the page: http://docs.botframework.com/connector/getstarted/#publishing-your-bot-application-to-microsoft-azure

I can find the doc to publish bot using c#, I don't think there is a doc detailing how to publish app in Node.

**Comment by AmineIzumi** [comment]
I personnaly used a private git repo and enabled continuous deployment from this repository on an azure website. Azure then automatically install modules and dependencies if it founds a "package.json" file. Need a detailed explanation ?

**Comment by willportnoy** [comment]
@danmarshall did you have a sample for publishing node to azure?

**Comment by msft-shahins** [comment]
[here](http://docs.botframework.com/builder/node/guides/deploying-to-azure/) is the guid for deploying to azure.

**Comment by thewhitetulip** [comment]
@msft-shahins Can we add this link to the link I added in the description?
