### ISSUE TITLE
[C#] Exception when validation fails in form. 

### ISSUE THREAD

**Issue by ankitbko** [Microsoft/BotBuilder#557]
Repo: https://github.com/ankitbko/Bot-Issue-557

Input: Text Paul

In case validation fails when building a form, there is an Unauthorized followed by Access Denied exception is thrown. This happens when integrating with Skype but works fine in emulator. I haven't checked it with other channels. This issue started with 1.2.4 release.
```
Exception thrown: 'Microsoft.Rest.TransientFaultHandling.HttpRequestWithStatusException' in Microsoft.Rest.ClientRuntime.dll ("Response status code indicates server error: 401 (Unauthorized).")
```

```
Exception thrown: 'Microsoft.Rest.HttpOperationException' in mscorlib.dll ("Access Denied")	Microsoft.Rest.HttpOperationException
```

This might or might not be related to #513

**Comment by chrimc62** [comment]
I suspect that this might be related to sending multiple messages.  I've added @tomlm to comment.

**Comment by tomlm** [comment]
if you are getting unauthorized it is because you don't have your credentials set up correctly.

**Comment by ankitbko** [comment]
@chrimc62 Seems correct. The issue is it sends down the Validation Feedback and post that it should ask for the field again which it is not doing.
@tomlm Which credentials are not setup? The issue seems to arise only when validation fails.

In general, is there a way to open a github issue once it is closed?

**Comment by evnik** [comment]
@ankitbko According to [this](http://stackoverflow.com/a/21333938), you cannot re-open an issue if any repository collaborator closed it.

**Comment by chrimc62** [comment]
I reopened it,

**Comment by ankitbko** [comment]
Oh, I am sorry for the confusion. The issue happens only if I use aspnet core(rtm) to run the project. The project still targets net46. The same thing works fine for classical project.
I have updated the repo to reflect both aspnetcore project and the classical project.
Please do replace the bot credentials accordingly.

**Comment by ankitbko** [comment]
@chrimc62 @tomlm Any update on this? It only happens if I port the project to .net core template where the bot id and secret are stored in json file instead of web.config. It might be that Microsoft.Bot.Connector is still expecting creds in web.config?

**Comment by tomlm** [comment]
we use ConfigurationManager.AppSettings to pull from the config.  You can override this by passing the setting directly into the attribute:
[BotAuthentication(MicrosoftAppId="123123123123123123")]
