### ISSUE TITLE
Can't add bot to group chat or team chat

### ISSUE THREAD

**Issue by Virtual-Josh** [Microsoft/BotBuilder#5573]
I'm currently unable to upload echo bot to the group chat, or team chat scopes via Teams App Studio, or manually sideloading the app. When I try to click the last button to submit it I'm met with an error message saying there was an issue. Can you tell us if this is a bug, or an issue with the manifest? 

Here's a copy of the echo bot project. 
[echo bot.zip](https://github.com/microsoft/botframework-sdk/files/3548503/echo.bot.zip)

**Comment by sergiosanchezd** [comment]
Hi @Virtual-Josh, I'm trying to do the same, deploy an echo bot and make some test on group conversations. Did you change something special on the echo bot to make this works?
Thanks in advance,

**Comment by Virtual-Josh** [comment]
Hi @sergiosanchezd,

I'd recommend looking at the teams samples, specifically the teams-conversation-bot to start, located [here](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples).
