### ISSUE TITLE
Question: Is there a way to specify UserData/ConversationData/PerUserInConversationData through DirectLine?

### ISSUE THREAD

**Issue by ejadib** [Microsoft/BotBuilder#560]
I'm trying to write some functional tests against a Bot that store some information in UserData/ConversationData data bags and I'm not being able to find a way to set values for those directly through DirectLine. Is that even possible?

Thanks,
Ez.

**Comment by dandriscoll** [comment]
The "channel" side of the Bot Connector doesn't expose this, but you can send your custom data to/from the bot via the ChannelData field on the DirectLine message -- it shows up verbatim on the bot side.

Would this solve the problem? If not, I'm interested to hear about your requirements.

**Comment by v-thgratMSGit** [comment]
Closing this issue. @ejadib - please open a new issue if this needs further discussion. Thanks!
