### ISSUE TITLE
error in sample project SimpleAlarmDialog

### ISSUE THREAD

**Issue by dimak72** [Microsoft/BotBuilder#561]
the object's constructor calls into the base thus creating a null object of ILuisService type.

```
        public SimpleAlarmDialog(ILuisService service = null)
            : base(service)
        {
        }
```

which in turn fails in QueryAsync of LuisService.cs

**Comment by msft-shahins** [comment]
Similar to issue #509. Commit [7df89b](https://github.com/Microsoft/BotBuilder/commit/7df89b947ec8a59757cbee4c7526660e2ddad3d0) should have the fix.

**Comment by willportnoy** [comment]
right, here was the pull request: https://github.com/Microsoft/BotBuilder/pull/512
