### ISSUE TITLE
Two way conversation Bot that interacts with LUIS and replies to requestor

### ISSUE THREAD

**Issue by prakashin77** [Microsoft/BotBuilder#562]
Hi Everyone,

I am looking for a sample code which interacts with LUIS and replies back to requestor based upon the query we passed.
Example: If i type SharePoint access, the given keyword should interact with LUIS and then provide the necessary step to requestor from LUIS.

Thanks in Advance

**Comment by willportnoy** [comment]
The Pizza sample uses the LUIS service as a top-level dialog and then dispatches to a FormFlow dialog when appropriate

https://github.com/Microsoft/BotBuilder/blob/develop/CSharp/Samples/PizzaBot/PizzaOrderDialog.cs

Is that what you're looking for?  If you want to call the LUIS service at any point, you can instantiate our implementation of ILuisService and use it at any point as well.  We provide the LuisDialog as an example of calling the LUIS service, where the LUIS intents/entities are used to dispatch to various C# methods that handle the bot's logic.

**Comment by willportnoy** [comment]
I'm going to close this issue for now, but feel free to re-open another issue if you have more questions.
