### ISSUE TITLE
Choice Prompt not working on Telegram

### ISSUE THREAD

**Issue by abhishekkant** [Microsoft/BotBuilder#563]
Hi 

I have a Node.js application using Choice Prompt. In the Bot Emulator the choice prompt works seamlessly but when connected to Telegram, the choice prompt doesn't show any message. however, the prompt still seems to be active as it expects an input. 

Can you suggest what could be wrong?

**Comment by eanders-MS** [comment]
Hi @abhishekkant. Are you sending a text prompt with the choice? Telegram requires a non-empty text prompt to accompany choices.

The expectation of a reply is state maintained in the BotBuilder's dialog system, it isn't part of Telegram.

**Comment by eanders-MS** [comment]
Closing this issue. If you're still having a problem please create a new issue and we'll troubleshoot.
