### ISSUE TITLE
SKype for business as channel

### ISSUE THREAD

**Issue by tahazayed** [Microsoft/BotBuilder#565]
I want to support Skype for business as a channel, can I use this DLL Microsoft.Bot.Connector.Emulator.Core.dll (included in Bot Framework Emulator)?

**Comment by jameslew** [comment]
Skype for Business isn't yet added as a channel to the Bot Framework, though it's high on our priority list.   

I'm not sure how you'd use the emulator core for that, but you've peaked my curiosity :).

**Comment by ronnelsantiago** [comment]
do you have any timeline on this one? is this currently being worked on? can you give us an indication here please.

**Comment by tomlm** [comment]
I can assure you that it is being worked on, but not timeline.

**Comment by ronnelsantiago** [comment]
sounds good enough for me.. thanks.

**Comment by tahazayed** [comment]
I built skype for bussiness client using lync sdk and I am using Microsoft.Bot.Connector.Emulator.Core.dll to send message to the bot connector<->conversation and it is working fine with me, I am asking about is it legal or not?

**Comment by naoya0731** [comment]
@tahazayed it's great! Can I use it?

**Comment by tahazayed** [comment]
https://github.com/tahazayed/BotConnectorSkypeForBusiness

**Comment by b4usat** [comment]
@tahazayed i tried the sample in the repo. When i tried sending message to my deployed bot, its returning no response. Can you please help me here?

**Comment by tahazayed** [comment]
@b4usat, close any conversation window then ask someone to start a conversation and it will work

**Comment by abhishan** [comment]
I found this blog post by @adoprog
http://devopssnippets.blogspot.co.uk/2016/08/integrating-lyncskype-for-business-with.html
This uses Direct Line channel and Lync API (UCMA can also be potentially used). I haven't tried this yet, but its worth a shot.
The only challenge is that this **wont work for Skype for Business Online.**

~Abhishek
Acuvate Software

**Comment by tahazayed** [comment]
@abhishan I already built another one with lynk sdk https://github.com/tahazayed/BotConnectorSkypeForBusiness 
And it works with skype for business online as it  just a client not server application

**Comment by abhishan** [comment]
@tahazayed - Thanks for the link. Will check it out.
Few questions:
Do we run it on every user desktop that needs access to the bot? OR, Do we need to dedicate a PC that acts as the Bot's Skype client?
If a user is using Skype on mobile, will it support this scenario?
Thanks in advance...

~ Abhishek
Acuvate Software

**Comment by tahazayed** [comment]
You will need one dedicate pc for the bot.
Any user can talk to it

**Comment by abhishan** [comment]
@tahazayed Cool. This would work in the interim, while we wait for an official MS release... Thank you!

**Comment by shankarmuppalla** [comment]
@tahazayed I tried the code from repository .There is no response from my deployed bot in SFB even after closing all conversation windows but when i tried with ngrok with forwarding url in emulator , there is a response. Can you plz help if i'm missing anything here.

**Comment by tahazayed** [comment]
@shankarmuppalla 
Happy new year
1-Change BotURL in App.config with yours
2-Debug MainForm.cs

**Comment by shankarmuppalla** [comment]
@tahazayed Thank you Wish you the same.

1- BotURL Changed in App.Config
2- During Debugging MainForm.cs ,There is a "System.NullReferenceException" thrown as oBotResult.attachments is NULL .
and Under oResponse--> Message -->Text displayed as " 500 Internal Server Error".
How do i come out of this ? Thanks in Advance!

**Comment by tahazayed** [comment]
The issue in WCF
Disable custom error in WCF web.config

**Comment by romanNedzelsky** [comment]
I changed BotURL, changed ID and Secure, but still has "Additional information: Could not load file or assembly 'Microsoft.Office.Uc, Version=15.0.4603.1000" when try to run. I read somewhere, that it shuold be coused by bad versions of Lync SDK and Lync Client, which has to be installed to install SDK. I has those versions: 
SDK: 15.0.4603.1000
Client: 15.0.4420.1017

Would it be possible to help me somehow? I really want to run this great solution :/

**Comment by tahazayed** [comment]
Copy this file from lync sdk installation folder under program files to your bin folder

**Comment by romanNedzelsky** [comment]
Great, thank you, this works, now the code is runing, but somehow, when I write "Hi", I have no response at all even I know, that bot is functional via normaln skype, slack or webchat...

**Comment by tahazayed** [comment]
Debug MainForm.cs

**Comment by shankarmuppalla** [comment]
@tahazayed Disabled custom errors and now there is this "401 unauthorized error" during debug . My bot is deployed to Azure with url something like this https://mybot.azurewebsites.net/api/messages and provided AppId and AppSecret respectively in the code as well.

**Comment by miau4** [comment]
I've got the exact same error as @shankarmuppalla

**Comment by romanNedzelsky** [comment]
I've also got exactly the same eror as @shankarmuppalla and @miau4...do you have any ideas?

**Comment by tahazayed** [comment]
I will debug as well to check the issue and give you feedback ASAP

**Comment by yevsh** [comment]
One question:
Is it possible to use local (intranet) bot with the BOT Framework? 
As we can't/won't publish our bot for all to see/use, the bot is for local use only.

**Comment by romanNedzelsky** [comment]
Hello @tahazayed, any progress on debuging? thank you very much.

**Comment by virendrak** [comment]
@romanNedzelsky ,  Please find the solution below provided by @ankitbko in ticket -https://github.com/ankitbko/SkypeForBusinessBot/issues/1

> In properties of Microsoft.Office.Uc "Embed Interos Types" was set to True which made "Copy Local" to false. Just changing it will work.

**Comment by ankitbko** [comment]
@romanNedzelsky Also make sure Copy Local is set to true once you change Embed Interops to False

**Comment by shankarmuppalla** [comment]
@tahazayed Any solution for the error? Thanks!

**Comment by ankitbko** [comment]
@yevsh Yes you can create a bot which works locally. You can see the example [here](https://github.com/ankitbko/SkypeForBusinessBot). The bot is hosted locally and is not registered with Bot Connector. The only *outside* communication is to LUIS which you can replace with any on-premise implementations which are available.

**Comment by miau4** [comment]
The problem about the "401 unauthorized error" during debug is still there.. does someone have a solution?

**Comment by romanNedzelsky** [comment]
I still cannot make this solution working :( any progress @tahazayed ? Or anyone else? something?

**Comment by tahazayed** [comment]
Hello, sorry I will finish my master's exams by tomorrow and I will check the error intensely.

**Comment by tahazayed** [comment]
Hello,I fixed the reference issue also I uploaded the web service that used by the bot

**Comment by tahazayed** [comment]
@romanNedzelsky kindly get the latest version and use my web service under this folder"sampleservice"

**Comment by romanNedzelsky** [comment]
@tahazayed thank you for the update, will try, just quick question, is it possible using your solution use of some graphical objects in the conversation like choice buttons, herocards, or images? I am asking, because we tried to use directconnect channel, it works, but text only, so all the selection you have to do using writing numbers, you havent any herocards with thumbails or images (or we dont know how to do it, that the other possibility ;) ) thank you very much

**Comment by tahazayed** [comment]
@romanNedzelsky check this https://docs.botframework.com/en-us/csharp/builder/sdkreference/attachments.html

**Comment by tahazayed** [comment]
@romanNedzelsky I think we can build a game, or sending tasks and get approvals

**Comment by romanNedzelsky** [comment]
@tahazayed well the reference is related to bot and skype, so the question is, if I will connect to bot with skype for business, will it work?

**Comment by tahazayed** [comment]
Theoretically it will work as Skype for business is just a channel, give it a try you have the source code

**Comment by nikhilpularru** [comment]
@tahazayed I really liked your implementation and have just 1 question in mind, how can we modify your code to handle multiple conversation at once?

**Comment by tahazayed** [comment]
@nikhilpularru Thanks, actually it handles, I use myRemoteParticipantUri as conversation's ID

**Comment by abhishan** [comment]
We have developed and launched a commercial version of a Skype for Business connector by leveraging UCWA and DirectLine. You can read more at this blog post here: http://acuvate.com/blog/chatbots-on-skype-for-business/

**Comment by ankitbko** [comment]
@abhishan Great work. I had also written a blog on how to create SFB connector using UCWA - https://ankitbko.github.io/2017/02/Sykpe-For-Business-Bot-Using-UCWA/

**Comment by sjwaight** [comment]
Now officially supported as a Channel. Details here: https://msdn.microsoft.com/en-us/skype/skype-for-business-bot-framework/docs/overview

**Comment by tahazayed** [comment]
@sjwaight: The Skype for Business Bot Framework channel is currently supported for Skype for Business Online. Skype for Business Server 2015 is not supported.
However I support Skype for Business Server 2015

**Comment by vikasr111** [comment]
@tahazayed I am also trying to setup bot on Skype for Business Server 2015.
If you have successfully setup, can you please guide me through?

**Comment by kapil-p-jain** [comment]
> I built skype for bussiness client using lync sdk and I am using Microsoft.Bot.Connector.Emulator.Core.dll to send message to the bot connector<->conversation and it is working fine with me, I am asking about is it legal or not?

Hey can you help .. how you did that?

**Comment by kapil-p-jain** [comment]
> I found this blog post by @adoprog
> http://devopssnippets.blogspot.co.uk/2016/08/integrating-lyncskype-for-business-with.html
> This uses Direct Line channel and Lync API (UCMA can also be potentially used). I haven't tried this yet, but its worth a shot.
> The only challenge is that this **wont work for Skype for Business Online.**
> 
> ~Abhishek
> Acuvate Software

hey how you achieve that
