### ISSUE TITLE
.Field conflicts with initial state

### ISSUE THREAD

**Issue by amoldeshpande** [Microsoft/BotBuilder#567]
If I have a dialog
`
class Foo
{
 public String SomeState;

public static IForm<Foo> BuildForm()
{
    return new FormBuilder<Foo>()
     .Message("fill out foo form, will ya")
     .Field(nameof(SomeState),
         validate:  etc., etc.
     )
}
}

I cannot then prevent the form from always prompting for this field, even if I pass in a constructed object to FormDialog. for example:

instanceOfFoo.SomeState = "SomeString";
 FormDialog<Foo>(instanceOfFoo, Foo.BuildForm, FormOptions.PromptInStart)

`

**Comment by chrimc62** [comment]
This seems to work fine in the current version.  What version are you running?

**Comment by amoldeshpande** [comment]
1.2.4.

**Comment by chrimc62** [comment]
I do not see this behavior unless I pass in FormOptions.PromptFieldsWithValues.  If you are not doing that, I will need a more specific repro.
        [Serializable]
        class Foo
        {
            public String SomeState;

            public static IForm<Foo> BuildForm()
            {
                return new FormBuilder<Foo>()
                .Message("fill out foo form, will ya")
                .Field(nameof(SomeState))
                .Build();
            }
        }

            Interactive(Chain
                .From(() => new FormDialog<Foo>(new Foo() { SomeState = "done" } , Foo.BuildForm, FormOptions.PromptInStart))
                .Select((foo) => foo.SomeState)
                .PostToUser()
                .Loop()).GetAwaiter().GetResult();

**Comment by amoldeshpande** [comment]
ok I figured out what my issue was. I had a validate lambda that I did not realize was being run (because the result.Feedback is not sent unless the input is interactive apparently.)

Sorry about the false alarm.
