### ISSUE TITLE
Kik example with multiple session.send only sends first message

### ISSUE THREAD

**Issue by designdit** [Microsoft/BotBuilder#568]
Hello,

The node kik example:

https://github.com/Microsoft/BotBuilder/tree/master/Node/examples/demo-kik

no longer seems to work.  I tried it a few weeks ago and it worked fine, but now only the first message seems to be sent (or only the first is received?).  

For example, for the initial message in the example, the greeting is received, but not the "Hi..." message and not the beginDialog /menu:

 function (session) {
// Send a greeting and start the menu.
var msg = new builder.Message()
.addAttachment({
thumbnailUrl: "http://....png",
title: "Microsoft Bot Framework",
text: "Your bots — wherever your users are talking.",
titleLink: "https://dev.botframework.com/",
});
session.send(msg);  (RECEIVED)
session.send("Hi... I'm the Microsoft Bot Framework demo bot for Kik. I can show you everything you can use our Bot Builder SDK to do on Kik.");  (NOT RECEIVED)
session.beginDialog('/menu');  (NOT RECEIVED)
},

The bot still expects a response to the prompt, even though the user didn't receive the options. When the user replies, the bot says it doesn't understand and then delivers the /menu prompts.

Has something changed for sending multiple messages?

This may have the same root cause as:
https://github.com/Microsoft/BotBuilder/issues/451
https://github.com/Microsoft/BotBuilder/issues/522

Thanks

**Comment by designdit** [comment]
Hi, 

Any update on this? I believe it worked before the 1.0 update. Does something need to be changed for 1.0?

Thanks

**Comment by v-thgratMSGit** [comment]
Closing this issue due to age. @designdit - please open a new issue if this issue is not fixed and needs further discussion. Thanks!
