### ISSUE TITLE
How to skip field or ask to enter previous filed value in FormBuilder Dialog

### ISSUE THREAD

**Issue by OmShrivastava** [Microsoft/BotBuilder#569]
Hi 

I am developing chat bot for user registration

First step I am asking to user "Please enter name and date of birth" 

if user provide name and date of birth then I want to assign both to respective filed 
In this case skip next step where Form Builder dialog will ask for date of birth.
else if user provide only name or only date of birth then Dialog should ask remaining item only

Once I get both name and date of birth I am validating against existing user data
If user with same name and date of birth exist
then I need to ask to user to enter name & date of birth again
else I am asking to enter rest filed like mobile number and address.

**Comment by chrimc62** [comment]
There is not an easy way to do this right now.  You can skip the next step by having your validate fill in the date.  Re-executing is a little harder. Two options: 1) Duplicate your fields in the confirmation. 2)  What you could do is to derive a class from Field<T> and override the Next method to control what step is executed next.  I'll look into adding the ability to specify a delegate to Field<T> to make it easier in the future.  

Let me know if that doesn't work.

**Comment by amoldeshpande** [comment]
I can't get setting of a field (Field2)   in the validate for another field (Field1)  work. Is there a trick to that ? I always get prompted for Field2 even if "status" shows the value I set in the validate for Field1.

**Comment by chrimc62** [comment]
Are you passing in FormOptions.PromptFieldsWithValues?  If you are not passing that in and you are using the latest bot builder release this should work.

**Comment by amoldeshpande** [comment]
does indeed work with .5. thanks!
