### ISSUE TITLE
Save form input

### ISSUE THREAD

**Issue by bluekite2000** [Microsoft/BotBuilder#57]
I have a FormBuilder that I deploy to azure. How do I save what the user types in?

**Comment by chgc** [comment]
you can add 
`.OnCompletionAsync((ctx, state) =>
   {
     var sand = state.Sandwich;
                 ....
     return null;
    })`
to FormBuilder chain code. "state" will contain user input. you can do whatever you want to do after user complete the form.
 
you can check the source code. 
>   FormFlow/IFormDialog.cs line:  81.
