### ISSUE TITLE
How to ask for attachments while building dialogs using FormFlow?

### ISSUE THREAD

**Issue by vsotov** [Microsoft/BotBuilder#570]
I need to create a simple bot, that accepts text and image or video from user and add additional field if image or video doesn't have location embedded. 

The only problem I have is asking user for attachments in form builder. How to do it correctly?

**Comment by willportnoy** [comment]
Attachment prompt dialogs were recently added (https://github.com/Microsoft/BotBuilder/commit/22f5739052bd036a8e733658a09b681d1dcdd31d) though I'm not sure how you might prompt for attachments within FormFlow.  @chrimc62 ?

**Comment by chrimc62** [comment]
The only way to do this to implement your own IRecognizer over the system dialog and override the field recognizer with SetRecognizer that uses it.  There is not a simpler way now.  If you end up doing that, we would love to add it to Bot Builder.

**Comment by vsotov** [comment]
@chrimc62 Thanks for suggestion. I looked through code and if I understand correctly only text input is passed to each field on the form. Is it ok to modify FormDialog to make it pass attachments to its fields?

**Comment by chrimc62** [comment]
I'm not quite sure what you are trying to do.  What does it mean to "pass an attachment" to a field?  Could you show me the kind of interaction you are trying to implement?

**Comment by vsotov** [comment]
@chrimc62 last comment is about your suggestion for custom IRecognizer implementation and inability to get attachments within it.

The interaction I'm implementing is asking a user for problem description and related photos/video.

**Comment by chrimc62** [comment]
But isn't that all text?  i.e. "my pipe is rusted", "http://onedrive.microsoft.com/mypictures/rustedpipe.jpg".  I can imagine a browse conversation that might make it easier to find the URL, is that what you are thinking?

**Comment by vsotov** [comment]
I was thinking about users attaching pictures in their messengers like facebook or skype. When you sent it like attachments they are found under Message.Attachments and not in text. I think it will be hard to make users fill out URLs of their photos :)

**Comment by chrimc62** [comment]
Got it.  You can do this now.  When you call your form dialog, just fill in your state object with the attachments from the message.  Depending on your needs you could either:
a) Put it into a private field/property that is not exposed to FormFlow.
b) Put it in as the value of field that is exposed to form flow.
c) Use the private property to dynamically generate a field that allows choosing between them.

**Comment by chrimc62** [comment]
I'm going to close this for now.  If you need more help, just respond and I will reopen it.

**Comment by raminzandvakili** [comment]
@chrimc62 Would you please provide a sample code?
