### ISSUE TITLE
How to debug bot conversation on WebChat or Slack channels

### ISSUE THREAD

**Issue by loretoparisi** [Microsoft/BotBuilder#573]
I have my test bot running on several channels like WebChat, Slack or Skype, etc.
I would like to debug it when on the channel, since I have errors that I cannot reproduce running it as a text bot like:

```javascript
bot = new BotBuilder.TextBot();
```

while running as a service

```javascript
bot = new BotBuilder.BotConnectorBot( { appId : Config.appId, appSecret : Config.appSecret } );		
```

When I'm running the `TextBot` I get all `console.log` in the shell of course, but
Is it possibile to do this in some way like a debugging console in the WebChat or special debugging messages in the channels?

This would aid debugging things on the fly instead of looking at server logs, etc.

**Note.**
I want to remark that since my BotBuilder is running on Azure, I can get `console.log` messages setting the WebSite logging to "Detailed" level from `Settings>Diagnostic Logs`.
I'm searching something different more like a Firebug console logging tool.

**Comment by willportnoy** [comment]
That's an interesting idea.  One simple option you might consider is simply sending your debug messages through the normal "send message" interface, prefixed with something like "DEBUG:", when you match a specific channel and user information for which you want to get more debug information.

**Comment by v-thgratMSGit** [comment]
Closing this issue. Thanks!
