### ISSUE TITLE
Behavioral difference between builder.DialogAction.send() and session.Prompt.text() in a LUIS .onBegin()

### ISSUE THREAD

**Issue by jeffreyhyun** [Microsoft/BotBuilder#574]
I've been trying to understand why one will work in a LUIS dialog .onBegin() and the other won't. Could you help? Semantically, they seem like they would serve the same purpose, but the behavior is different.

I am using a beginDialog() to a luis dialog from another luis dialog without getting a user input in the previous dialog. The reasoning behind this is to make each luis dialog self contained in a directed, funnel type interaction. To create a funnel otherwise would require a waterfall step prompting the user for the intent handlers in the previous dialog then calling the new dialog which has the intent handlers.

`[some luis dialog].onBegin(builder.DialogAction.send('blah blah blah'));`

The line above will wait for a user input and then send that input to luis to process an intent which will then trigger the appropriate handler.

`[some luis dialog].onBegin( function( session ) {
   return session.Prompt.text("blah blah blah");
});`

If you use a closure along with the session prompt, the prompt call will never be executed and tries to go directly to luis without an input.

**Comment by v-thgratMSGit** [comment]
Closing this issue due to age. @jeffreyhyun - please open a new issue if this is not fixed and needs further discussion. Thanks!
