### ISSUE TITLE
Filtering attachment post?

### ISSUE THREAD

**Issue by felipe98** [Microsoft/BotBuilder#575]
I looked over the issues and didn't find an answer for this (apologies if I missed it). When a user sends an image attachment to the bot, it looks like I end up getting the content-url and not the actual stream. Is there a way to control where that content gets store. The emulator creates a magincal /content location and provides a url for it. It would be nicer to have control of the content and determine how long it should be storage, or whether the analysis should be run in memory and never store.

**Comment by tomlm** [comment]
Most of the channels provide only temporary storage for urls, so if you want the raw data you suck it down and store it in more permanent location.

**Comment by v-thgratMSGit** [comment]
Closing this issue. Thanks!
