### ISSUE TITLE
Send message to user| Permanently identify user

### ISSUE THREAD

**Issue by NanashiGIT** [Microsoft/BotBuilder#576]
**UPDATE:**
So i've been trying different things out and it appears, that i had to fill the From-Property in the message.
The solution is like this:
```cs
var conClient = new ConnectorClient();
Message message2 = new Message();
message2.From = new ChannelAccount { ChannelId = message.From.ChannelId, Address = botAddress};
message2.To = new ChannelAccount { ChannelId = message.From.ChannelId, Address = userAddress};
message2.Text = "Hello other user!";
message2.Language = "en";
await conClient.Messages.SendMessageAsync(message2);
```

Now i'd like to use this thread here to discuss another question, that i had for quite some time:
If i want to --permanently-- identify a user/bot, what should i use?
I am guessing that a combination of "ChannelID" and "Address" is an unique identifier of a user for a channel.
But what about the "id" ? I dont really understand the reason for that ID. What value does it have for me? Because it seems like the id is also a unique identifier for a user for just one channel.
What reasons are there to store the "id"?
Is it possible, to get all ChannelID-Address combinations of a user with the id? (if the id is globally unique)

Greetings!

--------------------------------------------**Initial Question**------------------------------------------------------------

Hello!
What i want to do is to message a user with my bot, only knowing the channelID/UserID/UserAddress.
Because i need to handle a message from my backend, which tells me something like "message that user", so i have no conversation info or anything.

So is it possible to just message a user?
If so, how does it work?
Im using the C# Builder.
Im currently testing it with skype.

What ive tried:
```cs
var conClient = new ConnectorClient();
var msg = new Message() { To = new ChannelAccount { Id = "hisID", ChannelId = "skype", Address = "his address", IsBot = false }, Text = $"Hello!" };
await conClient.Messages.SendMessageAsync(msg);
            
```
That doesnt work for some reason.
Am i missing a required message property? Thats what im thinking.

Greetings!

**Comment by jameslew** [comment]
Hi there NanashiGit,

The ID currently represents the Bot Framework ID for this user. In upcoming releases we'll be simplifying the ChannelAccount data to just the channel service's user Id and Name; with ChannelId being at the message level.

**Comment by tomlm** [comment]
Jim is correct.  The idea of id vs address was that id would be a global user id across addresses.  In our new version we have removed it, so channelId/Address is the unique id for a user on a channel

**Comment by garvitgupta543** [comment]
can we send messages to user just by knowing their email address now?
