### ISSUE TITLE
Severity Code	Description Project	File Line Suppression State Error NU1001 The dependency Microsoft.AspNetCore.Authentication.OpenIdConnect >= 1.0.0-rc2-final could not be resolved.Microsoft.Bot.Sample.GraphBot

### ISSUE THREAD

**Issue by vk4421** [Microsoft/BotBuilder#577]
Please help me to solve this issue

**Comment by willportnoy** [comment]
Do you have .NET Core installed? e.g. https://www.microsoft.com/net/core#windows

**Comment by vk4421** [comment]
Yes

**Comment by willportnoy** [comment]
If you right-click on the project, can you click "restore packages"?  Does it give any more diagnostics in the output window?

**Comment by vk4421** [comment]
No "restore package" option. nothing sorted.

**Comment by willportnoy** [comment]
The lack of a "restore packages" option makes me think you don't have the .NET Core tooling for Visual Studio installed - e.g. https://www.visualstudio.com/news/releasenotes/vs2015-update3-vs

**Comment by willportnoy** [comment]
I'm going to close this issue - feel free to open a new issue for further discussion.
