### ISSUE TITLE
Is there a sample code for the Direct Line API?

### ISSUE THREAD

**Issue by vaditya04** [Microsoft/BotBuilder#579]
I'd like to have something to work with, a piece of code that handles the basic text send and receive functionality. C# preferably or JS
It would be great if the sample is tied to some sort of interface (such as a basic browser chat box)

**Comment by vaditya04** [comment]
Also, the sdk reference page links to itself : 
http://docs.botframework.com/sdkreference/restapi-directline

**Comment by hmishra2250** [comment]
Hey, I was working on the same and found the following resources helpfull:

1. [Basic Idea how to send and receive messages using directline API](http://stackoverflow.com/questions/36568438/where-is-the-host-and-port-coming-from-when-i-am-reading-direct-line-api-doc-fro)
2. [Format of the messages](http://docs.botframework.com/sdkreference/restapi-directline/)

The combination of above two worked for me :)
You just need to figure how to send GET and POST messgaes.
