### ISSUE TITLE
Colon in message causes crash in CommandDialog.js

### ISSUE THREAD

**Issue by michaelkantor** [Microsoft/BotBuilder#58]
Using the [TODO sample application](https://github.com/Microsoft/BotBuilder/tree/master/Node/examples/todoBot), CommandDialog.js generates the following regular expression:
```
expression = /^(?:new|save|create|add)(?: (.+))?/i;
```

Sending a Message of "new: Do Something", causes the following exec:

```
var matches = expression.exec(text);
```
Which returns `['new', undefined]`

The `replyReceived` function in CommandDialog.js then iterates over these results, throws an error and dies on trying to access `undefined` as though it were a string.

Run in chrome, but presumed to evaluate regex the same way in all browsers.

**Comment by msft-shahins** [comment]
Thanks for pointing this out. I pushed a [fix](https://github.com/Microsoft/BotBuilder/commit/6cadd42a89e7f46c3fc38f299167fb6d6251d494) that make the CommandDialog robust against these cases. Next release of the bot builder should have the fix.
