### ISSUE TITLE
Passing string var to PromptString in Chain

### ISSUE THREAD

**Issue by zxed** [Microsoft/BotBuilder#580]
I'm pretty sure I'm doing something wrong...

I started looking at Dialog Chain's as some conversations require additional questions based on certain criteria.

From the code below (stubbed out code)

```
                        string optionListString = "";
.......
                        optionListString += "-- or enter any thing else to cancel\n\n";

                        return Chain.From(() => new PromptDialog.PromptString(optionListString, null, 1)).ContinueWith<string, string>(async (ctx, res) =>
                        {
                            var selected = await res;
                            string reply = "";

                            return Chain.Return(reply);
                        });
```

I get the this exception. 

> anonymous method closures that capture the environment are not serializable, consider removing environment capture or using a reflection serialization surrogate

It's because I'm passing a string variable optionListString rather than actual literal text. The prompt is generated based on conditions and has some runtime text added to it.

What is the correct way of doing this?

**Comment by zxed** [comment]
p.s. I ended up looking at chaining because I wanted to implement waterfall dialog - and wanted to loop back when needed; is chaining the only way to get that done?

**Comment by willportnoy** [comment]
https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Tests/Microsoft.Bot.Builder.Tests/ChainTests.cs#L343 is another example of a data-dependent chain.

But for looping back earlier in the chain, you might find it easier to implement an IDialog, where you can choose what code executes next (after each message received from the user) based on whatever internal IDialog state you maintain.

**Comment by zxed** [comment]
Thanks! I'll give it a try and post my code next week so that I can explain
it better.

**Comment by zxed** [comment]
I appreciate your help; I've added more info.


Here is the code I currently have

```
public static readonly IDialog<string> dialog = Chain.PostToChain()
            .Select(msg => msg.Text)
            .Switch(
                new Case<string, IDialog<string>>(text =>
                {
                    var regex = new Regex(".*?(CASE-A)");
                    return regex.Match(text).Success;
                }, (context, txt) =>
                {
                    var calResponse = getSomeComplexObject();
                                        
                    string myBotOutput = "";

                    if (calResponse.data.Count == 1)
                    {
                        myBotOutput = (string.Format("There is only one on complex object called {1}", myBotOutput.data[0].name));
                        return Chain.Return(myBotOutput);

                    }
                    else if (calResponse.data.Count > 1)
                    {

                        myBotOutput = "There are multiple complex objects - which would you like details on?\n\n";
                        myBotOutput += "0) All \n\n";
                        foreach (var item in calResponse.data)
                        {
                            myBotOutput += "" + (calResponse.data.IndexOf(item) + 1) + ") " + item.name + "\n\n";
                        }

                        myBotOutput += "-- or enter any thing else to cancel\n\n";


                        return Chain.From(() => new PromptDialog.PromptString(myBotOutput, null, 1)).ContinueWith<string, string>(async (ctx, res) =>
                        {
                            //capture and process the next step
                            var selected = await res;
                            string reply = "";

                            return Chain.Return(reply);
                            // or maybe there are additional child steps.... 
                        });

                    }
                    else
                    {
                        myBotOutput = (string.Format("Looks like there are no compled objects"));
                        return Chain.Return(myBotOutput);
                    }

                    
                }),
```

I stubbed as much as possible, while still keeping it readable.

Prior to looking at chains; I was calling the various tasks and the task itself had the dialog (Example below).

```
if (Regex.IsMatch(message.Text, ".*?(CASE-A)"))
{
await outputAndgetSomeComplexObject(context, argument);
}
else
```

and lastly - I think your suggestion was to use something like the following

```
if (message.Text == "reset")
            {
                PromptDialog.Confirm(
                    context,
                    AfterResetAsync,
                    "Are you sure you want to reset the count?",
                    "Didn't get that!",
                    promptStyle: PromptStyle.None);
            }
```

I also created a simple waterfall below with repeat portions to make the question even more generic

U: send an email
B: What is the subject?
U: Dinner
B: What is the body?
U: Lets have dinner on Friday
B: Who do you want to send it to?
U: Mark
B: I found Mark Anthony - should I add?
U: Yes
B: I added Mark Anthony - do you want to add more?
U: Yes
B: Who else do you want to send it to?
U: Jim
B: I found more than one Jim, please select the corresponding # for the Jim you want me to add
B: 1) Jim John
B: 2) Jim Smith
U: 1
B: I added Jim John - do you want to add more?
U: No
B: Sending your email
B: Email sent

- After looking at the above, one might say that FormFlow is better for something like this than dialog's... but having not completed gotten the hang of dialog and its capability i'd rather not jump yet.

Am I going about this the wrong way?

**Comment by willportnoy** [comment]
if you can represent the state of your conversation by a C# class that FormFlow can fill in, then that may make it easier for you to encode the experience you want.

Compared to chaining, I personally find it easier to write out an IDialog implementation for the dialogue I want.

Overall though, the chains are composable pieces.  I'd put them together in small chunks and test them separately and make sure they do what you want before putting together the final solution.

**Comment by dgkanatsios** [comment]
@willportnoy, can a single dialog (that is easily maintained and altered) be created for the flow @zxed specified? If we want to implement many small dialogs (to separate the concerns) with the fluent API, what would be the correct approach? Let's say that we have 3 dialogs, we want to show them to the user consecutively and do an action after each one, would the following approach work?

`
//string s1,s2,s3; //defined as class members
//CustomDialogs return strings on context.Done
//...
var textDialog = from x in new CustomDialog1().ContinueWith(async (x1,y1)=> { s1 = await y1; return Chain.Return(await y1); })
                       from y in new CustomDialog2()ContinueWith(async (x2,y2)=> { s2 = await y2; return Chain.Return(await y2); })
                       from z in new CustomDialog3()ContinueWith(async (x3,y3)=> { s3 = await y3; return Chain.Return(await y3); })
                       select new { piece = x + y + z };

ctx.Call(textDialog, async (x, y) => { var o = await y; await x.PostAsync(o.piece.ToString()); });`

The above, btw, crashes with *anonymous method closures that capture the environment are not serializable, consider removing environment capture or using a reflection serialization surrogate*

**Comment by willportnoy** [comment]
Are you following this code as an example?

https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Tests/Microsoft.Bot.Builder.Tests/ChainTests.cs#L66

It's a method of calling a sequence of dialogs and combining the results in some way.

Instead of concatenating x/y/z, you can project them into an anonymous class that is the result of the chained dialog.

That exception is caused because one of the lambda expressions refer to a variable in an outer scope, so it's captured in the closure.  We could automatically serialize all of the environment captured by closures, but then there's the risk of impractically large amounts of state being serialized automatically.

**Comment by zxed** [comment]
I figured it was likely due to "one of the lambda expressions refer to a variable in an outer scope" - since the string was being concatenated based on a dynamic scenario.

What I've now ended up doing is staying away from chained dialogs, and instead; doing something like this 

```
public virtual async Task MessageReceivedAsync(IDialogContext context, IAwaitable<Message> argument)
{
.
.

if (X)
await someFunctionA(context, argument);
else if (Y)
await someFunctionB(context, argument);
.
.
.
context.Wait(MessageReceivedAsync);
```

and then within those someFunction's I have additional nesting 

```
public async Task someFunctionA(IDialogContext context, IAwaitable<Message> argument)
{
.
.
if (A.1)
await someFunctionA1(context, argument);
.
.
}
```

**Comment by willportnoy** [comment]
I added this commit https://github.com/Microsoft/BotBuilder/commit/f0b6a9ea4291c7461c4b8688b84ceb5285d7d1e6 as an example of control flow logic that was similar to a while loop.

**Comment by willportnoy** [comment]
I'm going to close this issue - feel free to open a new issue for further discussion.
