### ISSUE TITLE
Emulator doesnt allow double messages to bot?

### ISSUE THREAD

**Issue by Orbyt** [Microsoft/BotBuilder#582]
I noticed that if you send a message through the emulator to your bot, and the bot is programmed to not send a message back, the emulator doesnt seem to allow you to send another message.

Also, is there a way to "restart" everything in the emulator? I find myself having to close the emulator and restart it every few minutes.

**Comment by willportnoy** [comment]
You're correct that the emulator waits for a response from the bot's web endpoint.  I'm not sure if it eventually times out.

We tend to "restart" the emulator by changing the user and/or conversation ID.  I'm not sure that stops the emulator's current http request, though.

**Comment by tomlm** [comment]
you need to reply with at the very least a status code such as OK.  You don't have to return a message. Otherwise the emulator will wait for a response until it times out (probably 2 minutes).
