### ISSUE TITLE
Skype : Rich card attachments not rendering on skype

### ISSUE THREAD

**Issue by t-makish** [Microsoft/BotBuilder#583]
I am trying to send rich card attachment  using Bot Framework from my BotConnectorBot to Skype but the message do not contains any rich card attachment only the name of the image.

It works with fine with the Emulator but doesn't render on Skype 
Code:

`public async Task<Message> Post([FromBody]Message message)
        {
            if (message.Type == "Message")
            {
                message.Attachments = new List<Attachment>();

                message.Attachments.Add(new Attachment()
                {
                    Title = "Bender",
                    TitleLink = "https://en.wikipedia.org/wiki/Bender_(Futurama)",
                    ThumbnailUrl = "http://www.theoldrobots.com/images62/Bender-18.JPG",
                    Text = "Bender Bending Rodríguez, commonly known as Bender, is a main character in the animated television series Futurama.",
                    FallbackText = "Bender: http://www.theoldrobots.com/images62/Bender-18.JPG"
                });
                return message;
            }
            else
            {
                return HandleSystemMessage(message);
            }
        }`

**Comment by willportnoy** [comment]
You might consider adding a content type for your attachment:

https://github.com/Microsoft/BotBuilder/blob/42f2cb26615692b8cd4241641802d5778c409c52/CSharp/Tests/Microsoft.Bot.Builder.Tests/PromptTests.cs#L121

**Comment by tomlm** [comment]
ContentType = "application/vnd.microsoft.card.hero"

**Comment by tomlm** [comment]
you can also simple use the strong type message.Attachments.Add(new HeroCard() { .... }) and the contenttype will be property set
