### ISSUE TITLE
Roadmap to implement new facebook messenger 1.1 features like quickreply?

### ISSUE THREAD

**Issue by Praggie** [Microsoft/BotBuilder#585]
Hi,
     Is there any plans to implement new feature  like "quick reply" for facebook in Botbuilder?
http://messengerblog.com/bots/messenger-platform-1-1-ratings-quick-replies-account-linking-and-more/

Thanks,

**Comment by jameslew** [comment]
We're definitely interested in providing support for quick replies/keyboards in the Bot Framework.  In addition, Steve may have additional thoughts about the constructs we'd use in the BotBuilder.

**Comment by byrner75** [comment]
+1 for account linking, i've been trying it out however not getting through the Account Linking Callback message.

**Comment by Stevenic** [comment]
we're trying to get a few bugs with 3.0 of the SDK ironed out and then we'll be looking into adding support for these new features.

**Comment by matheus208** [comment]
Is there a way to listen for the event with v1? Apparently [the callback](https://developers.facebook.com/docs/messenger-platform/webhook-reference/account-linking) is not even forwarded to my endpoint after the linking is successful by Facebook.

**Comment by davyme** [comment]
Are you also thinking about adding Facebook Messenger Persistent menu & Welcome screen as new features?

**Comment by v-thgratMSGit** [comment]
Closing this issue. @Stevenic @jameslew - please comment if you have something to add relating to @davyme's question. Thanks!

**Comment by Stevenic** [comment]
The Node SDK supports both.

**Comment by davyme** [comment]
Thanks @Stevenic for the feedback. Any plans for the C# SDK?

**Comment by Stevenic** [comment]
It will be coming soon

**Comment by Praggie** [comment]
@Stevenic , Any updates on quick replies implementation in c# sdk?

**Comment by danmarshall** [comment]
@msft-shahins is a C# implementation planned?

**Comment by msft-shahins** [comment]
@danmarshall It is in our backlog.
