### ISSUE TITLE
Buttons in Skype

### ISSUE THREAD

**Issue by manu4rhyme** [Microsoft/BotBuilder#586]
So, I hosted my Bot on Azure, and connected it to Skype.
Everything works fine as on the Emulator, but there are no buttons at all in Skype?

Then i also tried connecting it to Telegram and Facebook. The buttons seem to be working pretty well there..

I did some exploring and found that buttons/cards are not supported in the current version of Skype.
Will there be any support for buttons/cards in Skype in the near future? And will the bot framework connector automatically provide support for it? And if so, when can we expect it to be there?

**Comment by msft-shahins** [comment]
With new [release](http://blogs.skype.com/2016/07/08/skype-bot-developer-update-cards-groups-and-more/) buttons and cards are supported in Skype.
