### ISSUE TITLE
Using Automapper in Dialogs

### ISSUE THREAD

**Issue by DavePilks** [Microsoft/BotBuilder#587]
I am trying to use `Automapper` in one of my `LuisDialogs`. But there is quite an issue that I have come across.

I make use of `AutoFac` and dependency injection to inject an instance of `IMapper` into the dialog's constructor. This is then assigned to a private field on the class and used throughout.

The issue comes in after the initial message has been sent by the dialog. After the message has been sent, the dialog is serialised and then deserialised upon receiving a new message. This means that I cannot make use of the constructor injection to get a reference to the automapper mapper. 

This is then further compounded by the fact that the mapper itself is not serialisable and thus cannot simply be serialised with the dialog.

Has anyone come with a solution to this? Or a different approach?

**Comment by willportnoy** [comment]
We use FiberModule.Key_DoNotSerialize

https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Fibers/FiberModule.cs#L52

to recover services from the container when deserializing the dialogs instead of serializing them directly.

**Comment by willportnoy** [comment]
I'm going to close this issue.  Feel free to open a new one for further discussion.
