### ISSUE TITLE
Ignore Attachments

### ISSUE THREAD

**Issue by ernanirst** [Microsoft/BotBuilder#588]
When my bot receives an attachment (I'm using the NodeJS SDK and the facebook channel), such as an image or a file, my bot stops working. This is due the fact that when I received an attachment the field `results.response` is `""`.

One solution is to put an if statement in every single dialog I have, but that doesn't seems to be the right way of doing this.

Is there any proper way of ignoring messages that are not text?

**Comment by willportnoy** [comment]
You may be able to use middleware to filter messages across all dialogs:

https://github.com/Microsoft/BotBuilder/blob/9a0f543fa2adc493ac53edeca769c101bd22512f/Node/examples/basics-logging/app.js

**Comment by ernanirst** [comment]
Thanks a lot, that was exactly what I was looking for.

**Comment by ernanirst** [comment]
I tried to add a middleware on v3 and I can't see my function been called. Here is my code:

// create the bot
var connector = new builder.ChatConnector({
    appId: process.env.MICROSOFT_APP_ID,
    appPassword: process.env.MICROSOFT_APP_PASSWORD
});
var bot = new builder.UniversalBot(connector);

bot.use(
    function (session, next) {
        console.log("Middleware: " + session.message.text);
});

**Comment by ernanirst** [comment]
A friend on gitter help solve the issue, not sure why, but the code below replaces the old one.

```javascript
bot.use({
    botbuilder: (session, next) => {
        console.log("Middleware: " + session.message.text);
        next();
    }
});
```

**Comment by Stevenic** [comment]
If you don't ever call next() from middleware then your bot won't process any incoming messages.
