### ISSUE TITLE
WebChat embed + oAuth: parameters passing

### ISSUE THREAD

**Issue by loretoparisi** [Microsoft/BotBuilder#589]
Supposed to have connected a `WebChat` channel, and to use the template for web embed so something like `https://webchat.botframework.com/embed/%s?t=%s` where you place you `appId` and a `apiToken` obtained as explained [here](http://docs.botframework.com/connector/embed-chat-control/#navtitle). This will embed an iframe with the bot fully operating as a web chat.
It becomes natural to put this inside a web site where users may be logged in (likely using a oauth service), so having a user profile/info.

Then it could help to let this embed page to be configured in some way with user info and details coming from the oauth results like the user's `displayName` and the oauth `access_token`, in order to be used within the web service that uses the BotBuilder.

```
oAuth   ---> UserInfo   --->  WebChat (diplayName, access_token)

```

This would be very helpful in a scenario where the `WebChat` is embedded in a web site with oauth, letting users to chat with the bot that will have then knowledge of the logged in user.

**Comment by uservous** [comment]
@loretoparisi Did you find any temporary solution for this one in the mean somebody responds to this?

**Comment by loretoparisi** [comment]
@uservous I'm looking for a temporary solution that starts from this: Since the embed url has the `s` and `t` parameters (app secret or api token), this must be passed to the `BotBuilder` framework somewhere in order to be initialized since when you initialize a bot you must pass it's configuration like

```javascript
		bot = new BotBuilder.BotConnectorBot( { appId : Config[ Config['env'] ].appId, appSecret : Config[ Config['env'] ].appSecret } );
	
```

so I wonder how internally this is managed and if it can handle generic input parameters. Of course this could be done by some server side code.

**Comment by dandriscoll** [comment]
We don't have a way to pass this through but it's a good use case and I'll take a look for the next version,

**Comment by loretoparisi** [comment]
@dandriscoll thank you, that would be useful and help to reduce use friction in accessing `Webchat` bot channel.

**Comment by Andrea-Orimoto** [comment]
Thanks for the suggestion, we've added it to our backlog.

**Comment by loretoparisi** [comment]
@Andrea-Orimoto thank you, can't wait to get it working!
