### ISSUE TITLE
Serialized Dialog State Limits

### ISSUE THREAD

**Issue by pagebrooks** [Microsoft/BotBuilder#59]
Is there a limitation with the BotConnector on the size of the serialized dialog state within botPerUserInConversationData? I am asking because I have a dialog that contains fairly complex state and it works just fine in the emulator, but does not work in the bot tester tool on botframework.com. The tester tool does not return any meaningful information so I can't diagnose my issue. What are the constraints here? Thanks for your help!

**Comment by Stevenic** [comment]
There are limits but they're fairly large if I remember. @tomlm can provide specific sizes.

**Comment by tomlm** [comment]
We limit overall message size to 256k serialized as json. 
For the BotData there are 3 potential BotData fields so we recommend 64k each, but it's not a hard limit.

**Comment by pagebrooks** [comment]
@tomlm Thanks!
