### ISSUE TITLE
Exceptions silently swallowed in Node SDK 2.0.2

### ISSUE THREAD

**Issue by elpollouk** [Microsoft/BotBuilder#590]
Exceptions are currently being silently swallowed in the Node SDK 2.0.2.

To reproduce the issue, create a bot with the following dialog:
```
bot.dialog('/', function (session) {
    throw new Error("This shouldn't be silently swallowed");
});
```

And then send a message to the bot.

The user will see the message "Sorry. Something went wrong." from the bot twice, but there will be nothing written to stdout or stderr indicating a problem.

The problem looks to be in the UniversalBot.errorLogger. The emitError function is just being referenced, but not called.
emitError not being called as a function:
```
    UniversalBot.prototype.errorLogger = function (done) {
        var _this = this;
        return function (err) {
            if (err) {
                _this.emitError;
            }
            if (done) {
                done(err);
                done = null;
            }
        };
    };
```

**Comment by willportnoy** [comment]
Thank you for the report - does this issue still exist in the latest code?  I don't see a naked call to emitError in UniversalBot:

https://github.com/Microsoft/BotBuilder/blob/master/Node/src/bots/UniversalBot.ts

**Comment by Stevenic** [comment]
Just fixed this in v3..0.1
