### ISSUE TITLE
Noob Question: If have no https. Is there a way create a bot unless?

### ISSUE THREAD

**Issue by michaelMobitainment** [Microsoft/BotBuilder#591]

**Comment by willportnoy** [comment]
We use the bot credentials to secure your bot endpoint so that you know incoming http requests are coming from the Bot Connector.  These bot credentials are passed only when https is used.

And in general, using https is something we would like to encourage.

**Comment by willportnoy** [comment]
I'm going to close this issue, but feel free to open a new issue for more discussion.
