### ISSUE TITLE
Group join/leave events are not fired in Skype connector

### ISSUE THREAD

**Issue by gplumb** [Microsoft/BotBuilder#593]
As it stands, join/leave events aren't being fired for Skype-enabled bots in a group scenario.  This means that a bot has to wait to be explicitly messaged before it can send any welcome messages or "set the scene" for any group-specific scenarios that its' presence enables.

**Comment by v-thgratMSGit** [comment]
Thanks for the suggestion @gplumb. Closing this issue for now. The team is aware and it's under consideration. Thanks!
