### ISSUE TITLE
User entering invalid prompt option at the root level twice causes an error in Node SDK 2.0.2

### ISSUE THREAD

**Issue by elpollouk** [Microsoft/BotBuilder#594]
A prompt at the root level dialog will produce errors if the users enters and invalid choice twice in a row.

Repro:
Create a bot with the following dialog:
```
bot.dialog('/', [function (session) {
    var msg = new builder.Message(session)
        .attachments([
            new builder.HeroCard(session)
                .title("Test Card")
                .text("Select an option")
                .buttons([
                    builder.CardAction.imBack(session, "yes", "Yes"),
                    builder.CardAction.imBack(session, "no", "No")
                ])
        ]);
    builder.Prompts.choice(session, msg, "yes|no");
}, function (session, results) {
	session.send(`You chose ${results.response.entity}`);
}]);
```

When prompted, enter junk text twice in a row.

Result:
Bot will respond with "Sorry. Something went wrong." and "ERROR: Too many calls to session.endDialog()." will be logged to the Node.JS output.

**Comment by danmarshall** [comment]
Hi @elpollouk I am not able to repro - the bot will show the Yes/No dialog again if I use junk input. Please open a new issue if you see this behavior again, thanks.
