### ISSUE TITLE
Is there is any way to check the analytics of the bot? 

### ISSUE THREAD

**Issue by rohit2912911** [Microsoft/BotBuilder#595]

**Comment by willportnoy** [comment]
On the bot registration screen, you can fill in the "Azure App Insights key" field to "Provide your Azure App Insights Key if you want to receive analytics about your bot.".

**Comment by rohit2912911** [comment]
thanks

**Comment by alexsorokoletov** [comment]
I've provided the key and have been using the bot for a while. My insights shows no data. What am I doing wrong?

**Comment by willportnoy** [comment]
Are you able to log other events to your app insights container?

**Comment by alexsorokoletov** [comment]
How do I do that with Node.js SDK?

**Comment by willportnoy** [comment]
There is a node application insights sdk:

https://www.npmjs.com/package/applicationinsights

and here is an article describing it:

https://azure.microsoft.com/en-us/documentation/articles/app-insights-nodejs/

**Comment by alexsorokoletov** [comment]
@willportnoy, thank you. Why do I have to enter the Insights Key when I configure a bot then?

**Comment by willportnoy** [comment]
We can additional logging to your application insights container - for example, how long it took us to call your bot, including the round-trip.

**Comment by alexsorokoletov** [comment]
So that's my question, how do I see these analytics? The resource, which key I used in the bot properties, has no events or metrics logged so far.

**Comment by danmarshall** [comment]
@alexsorokoletov I followed the guide provided by @willportnoy and was able to see metrics in the Azure  portal within a minute or so.

**Comment by willportnoy** [comment]
I'm going to close this issue - feel free to open a new issue for further discussion.
