### ISSUE TITLE
how to publish bot automatically via website?

### ISSUE THREAD

**Issue by Botship** [Microsoft/BotBuilder#597]
In my use case, visitors to my website can come and sign up for a bot. So, I need to create a new instance of a bot for each sign up.

Could you do that automatically? Currently, I understand that I need to publish the bot via visual studio and go through multiple manual steps. What advice/recommendation can you provide for auto creating an instance of a bot?

**Comment by LarsLiden** [comment]
Currently we do not support programmatic provisioning of bots.
