### ISSUE TITLE
Preview mode LUIS model does not work with LuisRecognizer

### ISSUE THREAD

**Issue by sachinkundu** [Microsoft/BotBuilder#599]
I have a **preview mode** model in luis.ai and when I try to use it with 
```
var model = process.env.model || 'luis_model_url';
var recognizer = new builder.LuisRecognizer(model);
var dialog = new builder.IntentDialog({ recognizers: [recognizer] });
```
then it is not possible to detect the intent and intent handler is not called. It falls back to my default handler. Production mode models work fine.

```
C:\Users\Sachin\source\botiag>npm show botbuilder version
1.0.1
```

**Comment by willportnoy** [comment]
I believe the luis.ai schema has changed with the preview version - here are some previous discussions: https://github.com/Microsoft/BotBuilder/issues/395 and https://github.com/Microsoft/BotBuilder/issues/222.

**Comment by msft-shahins** [comment]
Currently we are not supporting any preview features of Luis.ai. We will look into supporting the new features when they are out of preview.
