### ISSUE TITLE
skype-sdk NPM isn't published

### ISSUE THREAD

**Issue by roymap** [Microsoft/BotBuilder#6]
You can see this in packages.json:

"dependencies": {
    "botkit": "0.0.14",
    "restify": "^4.0.4",
    "skype-sdk": "file:///C:\\Source\\skype-sdk.tar.gz"
}

**Comment by Stevenic** [comment]
Thanks.. Fixed that. The Skype Bot SDK is in private preview so you have to download the SDK when you're approved for the program. I removed the broken link from the example package.json file and will update the skype docs.
