### ISSUE TITLE
Newline in string not working C#

### ISSUE THREAD

**Issue by inornos** [Microsoft/BotBuilder#600]
Newline in string not working C# what i do help me

Problematic image
![image](https://cloud.githubusercontent.com/assets/14770190/16615463/88ff4bee-4394-11e6-94e5-fe639ccc4826.png)

i want this
![image](https://cloud.githubusercontent.com/assets/14770190/16615471/93f11410-4394-11e6-89f2-56412ac561f6.png)

**Comment by b4usat** [comment]
Yes this would really helpful. Even i tried with the markdown options given in the [link](http://stackoverflow.com/questions/22385334/how-to-write-one-new-line-in-bitbucket-markdown)

**Comment by DavePilks** [comment]
I have found that if I use a `StringBuilder` and do the following, it works

```
sb.AppendLine(myText);
sb.AppendLine("");
db.AppendLine(otherText);
```

**Comment by berhir** [comment]
To create a line break in markdown you have to end a line with two spaces.
Take a look at the sample on Wikipedia: https://en.wikipedia.org/wiki/Markdown

**Comment by chrimc62** [comment]
Let is know if that does not work for you.

**Comment by inornos** [comment]
Its not working for me, In Microsoft Bot Framework Emulator it working fine but when i upload on web for final check and try on the skype its same as before its not working in skype
Please help me what i do

**Comment by jayasuryajeyakodi** [comment]
@inornos  hey!  '\n' works when i deployed it on skype. However in emulator two spaces gives a new line.

**Comment by akontsevich** [comment]
`<br/>` work for me in emulator
