### ISSUE TITLE
[Question] What is the preferred way to send emojis

### ISSUE THREAD

**Issue by berhir** [Microsoft/BotBuilder#601]
I have experimented with emojis for some time now and can't figure out how to send emojis in a way that they look good on all platforms. I have tried this on Skype, Slack and Telegram:
```
return message.CreateReplyMessage(":smile: , :ok_hand: , :+1: , :thumbsup:, 😊 , 😎 , 😕 , ✌");
```
Most of the emojis look good on Telegram and Slack, but Skype doesn't understand the `:shortname:` notation and unicode emojis look different from "normal" Skype emojis. I guess the problem will be more complex when I try it on further messenger platforms.

So is there a good way to send emojis and let them look native on all platforms?

**Comment by tomlm** [comment]
Everybody supports the Unicode charset, but there isn't that much consistency for emoji markup.  Skype uses parens around their short commands, see here for list:

https://support.skype.com/en/faq/FA12330/what-is-the-full-list-of-emoticons
