### ISSUE TITLE
how  can I identify that the user  is left the chat? Is there is any event to identify this? 

### ISSUE THREAD

**Issue by rohit2912911** [Microsoft/BotBuilder#604]

**Comment by dandriscoll** [comment]
Both the v1 and v3 protocols have support for this, but most channels never report this information. (For example, on SMS, the user never actually leaves the conversation.)

**Comment by rohit2912911** [comment]
Thanks.. Can you tell me how to do this in webchat?

**Comment by tomlm** [comment]
Webchat doesn't support it.
