### ISSUE TITLE
[Issue] Unable to create new bot or edit existing bot

### ISSUE THREAD

**Issue by ankitbko** [Microsoft/BotBuilder#605]
The bot registration portal is throwing `The remote server returned an error: (409) Conflict.` whenever I try to create a new bot. Moreover unable to edit any existing bot as page does not load when I click on "edit". It throws exception `all.js?v=119:4551 Uncaught TypeError: Cannot read property 'Version' of undefined`. 
If I manually set `Version` property of `endpoint` to "1.0", the page does loads but edits are not saved.

**Comment by jameslew** [comment]
Apologies for this, we missed your report last night.  We've deployed a fix for this this morning.
