### ISSUE TITLE
Not receiving any response from Skype.

### ISSUE THREAD

**Issue by simranhanda** [Microsoft/BotBuilder#607]
I have connected my MS Bot with Skype. The bot is working fine on Emulator as well as the end point. But when i tested it with Skype, it worked fine for the first time but started generating error:

 statusCode: 500 Sorry, <BotName> is having a problem responding right now.

Please help on the same.

**Comment by jameslew** [comment]
Usually that message means your bot is returning a 500 Internal Server Error to the message we're sending it.  Are you using Azure App Insights to look at the logs?

**Comment by brene** [comment]
Maybe you have forgotten to add "/api/messages" to your endpoint? Since the sample code uses Restify to listen to POST requests to "baseurl + '/api/messages'".

**Comment by santhosh117** [comment]
use same port in ngrok and your app running terminal also

**Comment by danmarshall** [comment]
Closing this issue, please open a new issue if this happens again.
