### ISSUE TITLE
Unable to register new bot

### ISSUE THREAD

**Issue by rebekkaalv** [Microsoft/BotBuilder#609]
I get the following error message when I try to register a new bot:

> "Entity with the given ID already exists. Specify ETag, or '*' for unconditional update."

Is there currently a problem with the server, web page (https://dev.botframework.com/bots/new) or an other known issue?

**Comment by ankitbko** [comment]
Yes. I have raised the same issue before #605 . It seems they are updating the framework to "v3" which broke this. It is yet to be fixed. I am not able to edit the bots also.

**Comment by rebekkaalv** [comment]
@ankitbko Thanks for the info!

**Comment by chrimc62** [comment]
@tomlm @dandriscoll @jameslew you guys aware of this?

**Comment by jameslew** [comment]
We are investigating now.  Thanks for the report.  Expect it to be fixed shortly :).

**Comment by jameslew** [comment]
We've deployed a fix for this.  Sorry for the interruption.

**Comment by rebekkaalv** [comment]
I tried register a new bot now, but it still return the same error message as before.

**Comment by ankitbko** [comment]
@rebekkaalv It seems to be working. I just created a bot few minutes ago.

**Comment by rebekkaalv** [comment]
Okay that's good! :) Than it's maybe something wrong with my inputs. What is the meaning of the form field "Bot handle"?

**Comment by rebekkaalv** [comment]
@ankitbko Okay that's good! :) Then it's maybe something wrong with my inputs. What is the meaning of the form field "Bot handle"? I get an error message that says "Invalid character" but I have just typed a simple name consisting only of the letters i,a,n,m,l,b,o and t.

**Comment by ankitbko** [comment]
@rebekkaalv Bot handle represents an unique id to your bot. In .net, this value goes into AppId in web.config. It can contain Alphanumeric and underscore only. It should work if you are only entering letters. Check if there are no unintentional spaces in the beginning or end.
Also it needs to be unique. So try changing it to something different.
During the outage yesterday, it seems the Bot handle was getting taken but bot was not registering, therefore if you are using same handle as of yesterday, you would need to change it.

**Comment by rebekkaalv** [comment]
@ankitbko Thank you so much for solving my problem! That was the exact issue!
