### ISSUE TITLE
Non-Image Attachments in Web Chat Control

### ISSUE THREAD

**Issue by XelaMon** [Microsoft/BotBuilder#610]
In my bot, I attach some csv files when sending a response back to the user. In the Direct Line API response, this shows up in the "attachments" array with the contentType of "text/csv". However, in the web chat control, this attachment doesn't show up at all. 

Is it possible to at least get the URL of attachments to show up in the bot's response in the Web Chat Control?

**Comment by dandriscoll** [comment]
This is a known limitation if the current version of the web chat control. We're planning to release a new version in the future.

**Comment by stanleycyang** [comment]
@dandriscoll what's the timeline on CSV uploading?

**Comment by dandriscoll** [comment]
We're actively working on this but I don't have a timeline to announce yet. Please stay tuned.

**Comment by stanleycyang** [comment]
@dandriscoll I noticed that you guys do offer a link to download the CSV on response. I'm going to try and see if I can stream the data into the bot. If it works, I'll send a PR your way as well

**Comment by stanleycyang** [comment]
I actually fixed this problem by streaming it with **https**.
