### ISSUE TITLE
(Urgent - need to deploy on Monday) Empty context.MakeMessage().To.Name; (Facebook) -

### ISSUE THREAD

**Issue by tkbox9** [Microsoft/BotBuilder#613]
Hello, 

It seems I cannot get the user name from the facebook channel.  However, I do receive the channelId (Facebook) and the address. When testing from emulator everything works. 

      public async Task Greeting(IDialogContext context, LuisResult result)
        {
           var message = $"Hi {context.MakeMessage().To.Name}, what’s up?";
            await context.PostAsync(message);
            context.Wait(MessageReceived);
        }

If anyone had the same problem. I would appreciate any insight.

Many thanks.

**Comment by willportnoy** [comment]
https://github.com/Microsoft/BotBuilder/issues/291 and https://github.com/Microsoft/BotBuilder/issues/481 are relevant issues from the past.  @tomlm @jameslew do we return Facebook user names?

**Comment by tomlm** [comment]
We do, we do exactly this call to get the user name 
https://developers.facebook.com/docs/messenger-platform/user-profile

If it is failing then it is because there is something wrong with the access token you have given us in the portal.
