### ISSUE TITLE
Old screenshot in getting started for C#

### ISSUE THREAD

**Issue by sixpi** [Microsoft/BotBuilder#615]
The bot emulator screenshot in the getting started page is out of date (http://docs.botframework.com/en-us/images/connector/connector-getstarted-test-conversation-emulator.png),

I took a new screenshot, how would I contribute it to the documentation? Should I make a pull request against the gh-pages branch?

**Comment by Andrea-Orimoto** [comment]
thanks sixpi! we'll update the screenshot, no need to do a pull request.

thank you very much for bringing this to our attention.

**Comment by sixpi** [comment]
Cool, thanks. I was partly asking to learn the process for contributing to the project (either code or documentation).

**Comment by msft-shahins** [comment]
@sixpi we accept pull requests for bug fixes and new features. You can read more about our contribution guidelines [here](https://github.com/Microsoft/BotBuilder/blob/master/Contributing.md).
