### ISSUE TITLE
BotBuilder NuGet version 3.0 is missing Bot.Connector types ?

### ISSUE THREAD

**Issue by dpakpaul** [Microsoft/BotBuilder#616]
Tried following the instructions to upgrade an existing v1 Bot to v3 (http://docs.botframework.com/en-us/support/upgrade-code-to-v3)

I updated the BotBuilder SDK via NuGet to 3.0 . Object browser for the Microsoft.Bot.Builder reference that was added does not show anything from the Bot.Connector namespace (like the Activity class) . The docs suggest that the SDK for builder and connector were merged so I was expecting to find all the types I need in the updated v3 NuGet for BotBuilder.

**Comment by Thegaram** [comment]
Works for me. Did you remove the old Microsoft.Bot.Connector package?

**Comment by dpakpaul** [comment]
Ok, it did not work the first time. Removed everything and re-nuget'ed the bot builder and its happy now. Thanks.

**Comment by TexAgg** [comment]
What exactly did you do to fix this? I am having the same problem, where the Activity class and whatnot are not defined, so if I remove references to the Bot.Connecter namespace i get errors

**Comment by dpakpaul** [comment]
Uninstall the Microsoft.BotBuilder (the new one you might already have dropped in), then manually remove the reference to Microsoft.Bot.Connector if its still left behind and then re-add the BotBuilder package via NuGet. Not the best way to go about things, but it worked on my machine.

**Comment by TexAgg** [comment]
I removed it from my packages and from all my using statements but I'm still getting errors
