### ISSUE TITLE
V3 need to pass RegExp object to match, documentation needs to be fixed

### ISSUE THREAD

**Issue by arieschwartzman** [Microsoft/BotBuilder#617]
You state in your examples that:

intents.matches('^change name', [
    function (session) {
        session.beginDialog('/profile');
    },
    function (session, results) {
        session.send('Ok... Changed your name to %s', session.userData.name);
    }
]);

However I found that you must pass RegExp object in order it to work for example:

intents.matches(new RegExp(dialog.intent), [
            function(session) {
                session.beginDialog(dialog.name)
            }
        ]);

In some places you do state that regex is passed i,.e /somereg/ but in others, you use strings

**Comment by Stevenic** [comment]
thanks for the catch. they used to be strings but now they're a RegExp. which example are you seeing this in so I can fix them? thanks

**Comment by Stevenic** [comment]
I see it. that explains why someone said that example didn't work. thanks for catching that.

**Comment by Stevenic** [comment]
fixed the doc. thanks again
