### ISSUE TITLE
not receiving any response on emulator

### ISSUE THREAD

**Issue by ubreddy** [Microsoft/BotBuilder#620]
Node SDK
getting 202 accepted message on emulator.
none of the examples work. 
e.g. hello-Chatconnector... no response received even on postman.

need readme files to be updated to test on using emulator.

**Comment by chazwoza** [comment]
same issue for me since changing to V3 framework and v3 emulator... getting a "202 Accepted" but no responses/messages showing in emulator. Using console.log debug in my node.js bot, it is definitely actioning the response but the emulator not showing anything

**Comment by AmineI** [comment]
Have you enabled auth ?
[Emulator doesn’t work when configured with the bots appId & appPassword] (http://docs.botframework.com/en-us/node/builder/libraries/latest/#known-issues)

**Comment by chazwoza** [comment]
Yep saw that - i get a 202 Accepted but the emulator still doesn't show the bot's responses

**Comment by AmineI** [comment]
Erm, that's strange. I myself ran into some issues, but I actually got the basic hellobot sample working with the emulator just by disabling auth like above.
May I see a bit of your code ?

**Comment by chazwoza** [comment]
var restify = require('restify');
var builder = require('botbuilder');
var request = require('request');

// Create chat bot
var connector = new builder.ChatConnector({
//    appId: process.env.MICROSOFT_APP_ID,
//    appPassword: process.env.MICROSOFT_APP_PASSWORD
});
var bot = new builder.UniversalBot(connector);

bot.dialog('/', function (session) {
  console.log("Hello world");
  session.send("Hello World");
});

// Setup Restify Server
var server = restify.createServer();
server.post('/api/messages', connector.listen());
server.listen(process.env.port || process.env.PORT || 3978, function () {
   console.log('%s listening to %s', server.name, server.url); 
});

**Comment by AmineI** [comment]
Definitely working here, without any code modifications. Probably a dumb question but have you updated the botbuilder module or the emulator correctly ? (You can check with npm ls botbuilder). Sometimes updating the module can be a bit tricky.

**Comment by chazwoza** [comment]
Really? I'm getting nothing. Maybe its a problem with the emulator then.

npm ls botbuilder = 

└── botbuilder@3.0.0

Does that look right to you?

**Comment by AmineI** [comment]
Yeah, that's the last and the same as mine !
I don't understand what's going on. Emulator version 3.0.0.54 too, right ?

**Comment by chazwoza** [comment]
Yep I'm on 3.0.0.54

What version of nodejs? I'm on 4.4.3 / Windows 10

**Comment by AmineI** [comment]
Ahhhh that's probably it. I have read somewhere that some new dependencies needs a new version of nodejs. I'm myself on 6.2.2 / Windows 10, you should try updating :)

**Comment by chazwoza** [comment]
Upgraded to 6.3 - still not working :(

Works fine with Console Connector instead of chat connector...

**Comment by ubreddy** [comment]
you need to set the emaulator url to localhost:9000 Uday 

    On Sunday, 10 July 2016 8:15 AM, Amine I. <notifications@github.com> wrote:
 

 Erm, that's strange. I myself ran into some issues, but I actually got the basic hellobot sample working with the emulator just by disabling auth like above.
May I see a bit of your code ?—

**Comment by AmineI** [comment]
Isn't it the default preset ? Plus why would I receives the 202 Accept if it was not set ? But well let's try anyway.

**Comment by chazwoza** [comment]
Ok, setting it from 127.0.0.1 to localhost has done the trick - emulator working now.

Thanks :) :+1:

**Comment by AmineI** [comment]
Great to know. What about the initial issue @ubreddy ? The hellobot-ChatConnector works on my side with disabled auth too.

**Comment by ubreddy** [comment]
the emulator runs a server @ port 9000. so, the emulator url should be localhost:9000. Not documented well.@Amine what initial issue?  Uday 

    On Sunday, 10 July 2016 9:17 AM, Amine I. <notifications@github.com> wrote:
 

 Great to know. What about the initial issue @ubreddy ? The hellobot-ChatConnector works on my side with disabled auth too.—

**Comment by AmineI** [comment]
"getting 202 accepted message on emulator.
none of the examples work. 
e.g. hello-Chatconnector... no response received even on postman."
Is it working now ? I personally receive response in the emulator

**Comment by ubreddy** [comment]
yes. it is working. Uday 

    On Sunday, 10 July 2016 9:44 PM, Amine I. <notifications@github.com> wrote:
 

 "getting 202 accepted message on emulator.
none of the examples work. 
e.g. hello-Chatconnector... no response received even on postman."
Is it working now ? I personally receive response in the emulator—

**Comment by saibimajdi** [comment]
Have the same issue here, I got 202 Accepted but I don't receive any message from the Bot !

**Comment by saibimajdi** [comment]
It's working, after deleting the auth informations (APP_ID & APP_PASSWORD)!
![capture](https://cloud.githubusercontent.com/assets/8198978/19412327/4fbfc392-930b-11e6-996f-d7c7002be5ee.PNG)

**Comment by Jaeuk-YOO** [comment]
I have a same issue.

1. I usually use win10 insider preview bash.
2. I can get '202 accepted' too. (I deleted auth informations)
3. In bash terminal, I can get 'Chatconnector: message received.' log, but still can not received any message from the bot in emulator. (Exactly 'hello world' that I expect to receiv.e)

At this moment, what can I solve this problem ?

**Comment by OR13** [comment]
When debugging a local node.js bot with vscode and bot emulator, I needed to clear App Id and Password in order to receive responses in the emulator.

It seems like the emulator should be able to warn you about this, because if the bot endpoint contains localhost, App Id and Password should never be provided, or the emulator will not work.

alternatively, the emulator could simply ignore these fields when testing localhost is present in the bot endpoint url.

either solution would likely save new users a few minutes of head scratching before they google and find this thread.
