### ISSUE TITLE
[CSharp] v3 - Skype showing neither list nor buttons

### ISSUE THREAD

**Issue by ankitbko** [Microsoft/BotBuilder#622]
Using v3 of framework, I published AnnotatedSandwichBot and added it to skype channel. Skype is not displaying the enum options as buttons or as a plain list. It shows up as an image. My skype version is - 
7.25.0.106
![image](https://cloud.githubusercontent.com/assets/3169316/16707395/432bbf1a-45e9-11e6-8f3f-ac297dd23012.png)

Also in facebook, the list of sandwich option is not shown - 
![image](https://cloud.githubusercontent.com/assets/3169316/16707403/a4a151ec-45e9-11e6-97f4-73ffe11e4a8a.png)

**Comment by jrbaldwin** [comment]
We're experiencing this issue as well.

**Comment by gosha1** [comment]
These cards aren't supported in the current version of skype. 
 Please see this - http://docs.botframework.com/en-us/skype/getting-started/#developer-version-of-the-skype-web-app

You should test Skype bots using the developer version of the Skype Web App until updated Skype apps for desktop and mobile are available at the end of July.
•Go to https://web.skype.com
•Sign in using your Skype credentials
•Copy and paste the following URL into the address bar of the browser https://web.skype.com/en/?ecsoverride=developer

**Comment by Stevenic** [comment]
yes... you have to use the developer version of the skype client to see the cards.

**Comment by ankitbko** [comment]
@gosha1 Thanks for the info. 
@Stevenic There is an issue with fb also which I have posted above. Am I the only one facing this?
