### ISSUE TITLE
V3 bot.send 401 Unauthorized - node.js

### ISSUE THREAD

**Issue by stevepkr84** [Microsoft/BotBuilder#626]
I am implementing my bot using aws lambda. Everything was working ok with bot framework 1.0. I upgraded to 3.0 and can't seem to get it to work. The incoming requests are in this format:  http://pastebin.com/tSP2DkZW

I am then trying to send a reply using the code below:

`var reply = new builder.Message()
            .address({ bot: replyFrom, user: replyTo, channelId: channel, serviceUrl: serviceUrl })            
            .text("Hello everyone!");            
        bot.send(reply, function (err) {
            console.log(err);
        });`

The variables for address I am pulling from the incoming event.
I am getting results like: [Error: Request to 'https://telegram.botframework.com/v3/conversations/231538055/activities' failed: [401] Unauthorized]

This occurs for skype/facebook/telegram. Slack doesn't return an error, but still doesn't work.

**Comment by Stevenic** [comment]
so you shouldn't really tamper with the internals of the address object as you're risking things not working. You should take the address object from an incoming message, save it somewhere, and then assign that to your outgoing reply.

Can you maybe share more of your code so I can get a better sense for what you're trying to achieve?

**Comment by Stevenic** [comment]
CLosing this as we worked through this on gitter

**Comment by JLarky** [comment]
https://gitter.im/Microsoft/BotBuilder?at=5782be357aeb0805279eb5ab --- it seems like "working" was happening there
