### ISSUE TITLE
Images/Attachments from bot to user not sending on Skype

### ISSUE THREAD

**Issue by farizluqman** [Microsoft/BotBuilder#627]
This is the message I received on the terminal when the bot try to send an image (using Node.js):

"Using old attachment schema. Upgrade to new card schema."

And there will only be a blue card with the link "Open"...

Why is this happening? And how to fix this?

**Comment by gosha1** [comment]
These cards aren't supported in the current version of skype. 
Please see this - http://docs.botframework.com/en-us/skype/getting-started/#developer-version-of-the-skype-web-app

You should test Skype bots using the developer version of the Skype Web App until updated Skype apps for desktop and mobile are available at the end of July.
•Go to https://web.skype.com
•Sign in using your Skype credentials
•Copy and paste the following URL into the address bar of the browser https://web.skype.com/en/?ecsoverride=developer

**Comment by Stevenic** [comment]
As @gosha1 said, you need to upgrade to the developer version of the skype client.  To get rid of the warning you're seeing use the new card builders to create your attachments.  see the demo-skype bot in the examples directory for samples of this.

**Comment by possan** [comment]
I am seeing the same issues still, how do i verify that i have switched to the correct Skype web version? the only indication of a version number in the HTML is one in the feedback url: 0.219.0
