### ISSUE TITLE
Basics-logging example middleware not running

### ISSUE THREAD

**Issue by TheoRomain** [Microsoft/BotBuilder#628]
There is a small bug in the Basics-logging example [app.js](https://github.com/Microsoft/BotBuilder/blob/master/Node/examples/basics-logging/app.js) that causes the middleware to not run.

Botbuilder Version:
3.0.0

Reproduced by:
Running node app.js

Expected behavior:
Use of middleware to display "Logging is now turned on", "Logging is now turned off", "Message received: [message]"

Actual behavior:
bot wrote "UniversalBot.use: no compatible middleware hook found to install." to the console and middleware was not running at all.

Fix:
Changing
`bot.use({
    dialog: function`
to
`bot.use({
    botbuilder: function`
to match the IMiddlewareMap interface allows the example to run as expected.

**Comment by Stevenic** [comment]
good catch. I'll update that. The schema for that changed early last week. forgot to go through the examples.

**Comment by Stevenic** [comment]
fixes checked in
