### ISSUE TITLE
c# - Chronic.Parser

### ISSUE THREAD

**Issue by dendle** [Microsoft/BotBuilder#63]
Hello All,

I'm using C#, and building a LuisDialog.  Luis is passing me the builtin date & time entities, but I need them to be translated into real dates and times.

Looking at the example in the docs for the alarmbot, http://docs.botframework.com/sdkreference/csharp/dialogs.html#alarmBot

`var parser = new Chronic.Parser();`

Google tells me that Chronic is a ruby framework, at which point I regurgitated some of my tea.  (only joking)

I cant find this in the bot builder SDK, or in the Luis namespace - what am I missing? Should I brush up my ruby skills?

Cheers for any help in advance,
Kind Regards,
Matt

**Comment by dendle** [comment]
Oh - is it nChronic? [nChronic](https://github.com/robertwilczynski/nChronic)

**Comment by dendle** [comment]
Yes, its [nChronic](https://github.com/robertwilczynski/nChronic)

**Comment by rahul251993** [comment]
Its 'chrono', so try using chrono.parseDate( xyz); .
i hope it works now. :+1:
