### ISSUE TITLE
emulator returns 200 but no text with v1 of bot

### ISSUE THREAD

**Issue by kiwidave72** [Microsoft/BotBuilder#630]
seems to be an issue with the latest emulator working with and old bot.

the sample "You sent {length} characters" template runs ok, but the emulator isnt displaying the text from the bot.

ive tried the console and it to has the same issue.

i can debug the Message object and see that the text is set. but its just not getting displayed with in the emulator.

i havent looked with fiddler yet, but the fact its getting 200's seems to me that its working...but its not.

kind of a show stopper for me right now.

**Comment by Stevenic** [comment]
I believe you have to use the old emulator with old bots. adding Tom to confirm that.

**Comment by tomlm** [comment]
Correct, the v3 emulator I s called Bot Framework CHANNEL emulator and only works with v3 schema
.
The old emulator is "Bot Framework Emulator" and only works with V1 schema
