### ISSUE TITLE
Slack not working after upgrading to version 3.0

### ISSUE THREAD

**Issue by gosha1** [Microsoft/BotBuilder#632]
Slack status is shown as *Sorry, \<Bot-Name\> is having a problem responding right now.*
The bot works fine in emulator and in skype. I'm using C#.

**Comment by sarthak-k** [comment]
There is any solution for above problem?

**Comment by gosha1** [comment]
I created 2 bots and both had the same problem. Looks like I configured something wrong. 
App IDs: 
ffe50500-ef47-48f3-b6b1-2bfc29bcee33
aade4815-56b7-4512-9c1d-be726c25c821

**Comment by gosha1** [comment]
Its working for me now. 
I had given my BotHandle for BotId. When I changed it to the Name of the AppId created in the apps.dev.microsoft.com portal, Slack started working.
