### ISSUE TITLE
Examples are missing Slack integration

### ISSUE THREAD

**Issue by pke** [Microsoft/BotBuilder#633]
The blog post about version 3.0 promised an all new unified way to communicate with slack. Yet, no explaination is given how this works. Worse, the examples still feature the `SlackBot` which was removed in v3.0

So give us some guidelines how to use BotBuilder with Slack again. Thanks

**Comment by Stevenic** [comment]
Just realized we didn't update the Readme.md for the examples to reflect the current samples. I'm planning to rework the old samples to show great examples for each channel as to what you can do. If you look at the demo-skype example it should mostly work for Slack.

**Comment by pke** [comment]
I see. I'm especially interested in the slack action buttons, since the blog entry promised support for them.

**Comment by Stevenic** [comment]
Using `channelData` (`sourceEvent` in the node SDK) you can support just about any native feature of the underlying channel. If you look at the docs below that should get you started.

http://docs.botframework.com/en-us/csharp/builder/sdkreference/channels.html#customslackmessages

You just need to use [Message.sourceEvent({ slack: {} )](http://docs.botframework.com/en-us/node/builder/chat-reference/classes/_botbuilder_d_.message.html#sourceevent) to add your custom attachment to an outgoing event. When a button is clicked on the slack side the card will be returned as part of `session.message.sourceEvent`.

The thing we don't have a great story for yet is how you deal with these dynamic buttons being clicked at any point in the bots conversation flow.  I have a feature called __Actions__ that I'm planning to add which should solve this as they can globally handle a button being clicked at any time. Look for that to be add within the next week or so.
