### ISSUE TITLE
Some Prompt types do not work - v3, node, kik

### ISSUE THREAD

**Issue by designdit** [Microsoft/BotBuilder#635]
Hello,

Tried the following to send a message and then a prompt immediately after.  The prompt types for text, number, attachment, and time work - they are all received by the message recipient, whether or not they are the sent after an initial "session.send" message.

The prompt types for choice and confirm do not work - only the "session.send" message is received and if it is commented, then nothing is received by the recipient.

You can test by commenting and uncommenting individual prompt types from the following example:

bot.dialog('/', [function (session) {

	session.send('Hello');

//these four Prompt types work - prompt message is received
	//builder.Prompts.text(session, "2nd message");
	//builder.Prompts.number(session, "How many would you like to order?");
	//builder.Prompts.attachment(session, "Upload a picture for me to transform.");
        //builder.Prompts.time(session, "What time would you like to set an alarm for?");

//the next two Prompt types do not work - no prompt message is received
	//builder.Prompts.confirm(session, "Agree?");
	builder.Prompts.choice(session, "Which color?", ["red","green","blue"]);	
}, 
  function (session, results) {
    session.send("You chose " + results.response);
}]);

I am using the kik channel.  By the way, even for the choice and confirm prompts, which are never received, the bot is waiting for a response.

**Comment by 0GiS0** [comment]
I tested with Skype and you get an attachment, not the choices

![prompt choices](https://cloud.githubusercontent.com/assets/175379/16744283/aae0ecca-47b0-11e6-89e9-bae8692c21c1.PNG)

**Comment by 0GiS0** [comment]
It looks like if you set the listStyle it works... at least in Skype:

  builder.Prompts.choice(session,"Propmt demo","a|b|c",{listStyle: builder.ListStyle["list"]});

**Comment by designdit** [comment]
Thanks - setting the listStyle with builder.Prompts.choice also works in kik.

**Comment by designdit** [comment]
listStyle "button" doesn't work on kik - the prompt is not received by the user, same as if listStyle isn't used at all for the choice prompt.

**Comment by v-thgratMSGit** [comment]
Closing this issue. Please open a new issue if this needs further discussion. Thanks!
