### ISSUE TITLE
Thumbnail Card doesn't render correctly in Skype

### ISSUE THREAD

**Issue by ChuckkNorris** [Microsoft/BotBuilder#638]
It works fine in the emulator, but when I deploy it renders as a picture link I need to open - once clicked, it navigates to Skype Online.

Bot ID: 865c519c-ef60-4db4-9f83-fb88e077fc81
The bot is located here: https://homeadvisortestbot.azurewebsites.net/api/messages

I'm fairly sure I'm setting the ContentType attribute correctly, but if not, an enum would be nice and provide some direction.

![Image of Conversation](http://image.prntscr.com/image/c81e011e5a674debabf9df15dd2eb640.png)

```
Activity replyToConversation = activity.CreateReply("Should go to conversation, with a thumbnail card");
replyToConversation.Recipient = activity.From;
replyToConversation.Type = "message";
replyToConversation.Attachments = new List<Attachment>();
List<CardImage> cardImages = new List<CardImage>();
cardImages.Add(new CardImage(url: "https://upload.wikimedia.org/wikipedia/commons/f/ff/Aminah_Cendrakasih%2C_c._1959%2C_by_Tati_Photo_Studio.jpg"));
List<CardAction> cardButtons = new List<CardAction>();
CardAction plButton = new CardAction() {
    Value = "https://en.wikipedia.org/wiki/Pig_Latin",
    Type = "openUrl",
    Title = "WikiPedia Page"
};
cardButtons.Add(plButton);
ThumbnailCard plCard = new ThumbnailCard() {
    Title = "I'm a thumbnail card",
    Subtitle = "Pig Latin Wikipedia Page",
    Images = cardImages,
    Buttons = cardButtons
};
Attachment plAttachment = plCard.ToAttachment();
plAttachment.ContentType = "application/vnd.microsoft.card.hero";

replyToConversation.Attachments.Add(plAttachment);
APIResponse reply = await connector.Conversations.SendToConversationAsync(replyToConversation);
```

**Comment by ankitbko** [comment]
You will need to use Skype Developer web app for v3 bots. http://docs.botframework.com/en-us/skype/getting-started/#navtitle 

> Developer version of the Skype Web App

>You should test Skype bots using the developer version of the Skype Web App until updated Skype apps for desktop and mobile are available at the end of July.

>Go to https://web.skype.com
>Sign in using your Skype credentials
>Copy and paste the following URL into the address bar of the browser https://web.skype.com/en/?ecsoverride=developer

**Comment by ChuckkNorris** [comment]
Thanks, buddy!
Do you have any idea if any of the V3 stuff will be available within Facebook or Slack integrations?

**Comment by tomlm** [comment]
It is supported today.
