### ISSUE TITLE
V3 bot getting 500 error- .net 

### ISSUE THREAD

**Issue by rohit2912911** [Microsoft/BotBuilder#639]

**Comment by rohit2912911** [comment]
facing this issue in the sample code..

**Comment by ankitbko** [comment]
Can you provide more information such as which sample code is throwing error and stack trace of the error?

**Comment by rohit2912911** [comment]
public async Task<HttpResponseMessage> Post([FromBody]Activity activity)
        {
            if (activity.Type == ActivityTypes.Message)
            {
                ConnectorClient connector = new ConnectorClient(new Uri(activity.ServiceUrl));
                // calculate something for us to return
                int length = (activity.Text ?? string.Empty).Length;

                // return our reply to the user
                Activity reply = activity.CreateReply($"You sent {activity.Text} which was {length} characters");
                await connector.Conversations.ReplyToActivityAsync(reply);
            }
            else
            {
                HandleSystemMessage(activity);
            }
            var response = Request.CreateResponse(HttpStatusCode.OK);
            return response;
        }


getting stack trace error on  
 await connector.Conversations.ReplyToActivityAsync(reply);

**Comment by ankitbko** [comment]
Can you post the stack trace of the error? I assume you are testing though emulator.

**Comment by rohit2912911** [comment]
yes i running this in emulator version 3.0.0.54..    >

while call stack I am getting this 	
Bot Application1.dll!Bot_Application9.MessagesController.Post(Microsoft.Bot.Connector.Activity activity) Line 30

**Comment by willportnoy** [comment]
Your stack trace doesn't seem to be complete.  Does your web.config have the correct settings?

http://docs.botframework.com/en-us/support/upgrade-to-v3/#updates-to-the-auth-properties-in-webconfig

**Comment by rohit2912911** [comment]
web.config setting..tell me if something wrong in it...

<appSettings>
    
    <add key="BotId" value="YourBotId" />
    <add key="MicrosoftAppId" value="" />
    <add key="MicrosoftAppPassword" value="" />
  </appSettings>

**Comment by rohit2912911** [comment]
<appSettings>
    
    <add key="BotId" value="YourBotId" />
    <add key="MicrosoftAppId" value="" />
    <add key="MicrosoftAppPassword" value="" />
  </appSettings>

**Comment by willportnoy** [comment]
Do those authentication settings match the settings you're using in the emulator?

**Comment by rohit2912911** [comment]
yes..

**Comment by willportnoy** [comment]
I'm going to close this issue - feel free to open a new issue for further discussion or if you have more information.
