### ISSUE TITLE
Request: basics-naturalLanguage/app.js example for BotConnectorBot

### ISSUE THREAD

**Issue by FedericoElles** [Microsoft/BotBuilder#64]
At 
https://github.com/Microsoft/BotBuilder/blob/master/Node/examples/basics-naturalLanguage/app.js
there is a nice example how to use 
`cortanaBot.beginDialog`
to make to bot say something by an external event, not by replying to a chat message
I tried this 
```
bot.send(msg);
builder.DialogAction.send(msg);
slackBot.bot.say(msg);
```
but could not make it work. Can you help with an example?

**Comment by Stevenic** [comment]
you should be able to say SlackBot.beginDialog(). Let me try and see if I can make it work.

**Comment by Stevenic** [comment]
This should be working as of v0.7.2. I just checked in a fix and published a new version. For an example look at the new TestBot sample.
