### ISSUE TITLE
Sign-In card not rendering in developer version of skype web app - V3

### ISSUE THREAD

**Issue by gosha1** [Microsoft/BotBuilder#640]
All other cards are being rendered properly in skype. Also, the sign-in card is displaced correctly in emulator. 
The below error is shown. When can we expect the card to render properly in skype developer version?

![capture](https://cloud.githubusercontent.com/assets/20385477/16722600/532f4d32-4765-11e6-917f-eb85d7012e32.PNG)

**Comment by danmarshall** [comment]
Hi @gosha1 , I just did a quick test and can see a sign-in card in Skype Developer version. Can you give more details, what are you trying to sign in to?

**Comment by gosha1** [comment]
I'm using to send a message back from client, using the Type "imBack". Can you share your sample code for which it's showing in skype? Here's my code. Also, the card rendered properly in emulator.
```
replyToConversation = activity.CreateReply("sign in card");
                        replyToConversation.Recipient = activity.From;
                        replyToConversation.Type = "message";
                        replyToConversation.Attachments = new List<Attachment>();
                        List<CardAction> sbuttons = new List<CardAction>();
                        CardAction plsButton = new CardAction()
                        {
                            Value = "hello",
                            Type = "imBack",
                            Title = "WikiPedia Page"
                        };
                        sbuttons.Add(plsButton);
                        SigninCard scard = new SigninCard(text: "Hello world", buttons: sbuttons);
                        Attachment sAttachment = scard.ToAttachment();
                        replyToConversation.Attachments.Add(sAttachment);
                        reply = await connector.Conversations.SendToConversationAsync(replyToConversation);
```

**Comment by v-thgratMSGit** [comment]
Closing this issue. @gosha1 - please open a new issue if this issue is not fixed and needs further discussion. @danmarshall - reopen if necessary. Thanks!
