### ISSUE TITLE
[C#] Skype buttons with images not showing up from FormFlow.

### ISSUE THREAD

**Issue by ankitbko** [Microsoft/BotBuilder#641]
So I have a dynamic field in a form and in `SetDefine` I add image to the field like `field.AddDescription(car.Name, Language.CamelCase(car.Name), car.Image)` where car.Image is a http link to a png. I have set prompt choice style to Auto.
This shows up in emulator as button with image at side, but doesn't in skype (developer). 

In general, with new support such as Hero Card, Reciept card, Carousel etc, FormFlow is somewhat restricting or unclear as to how to specify which type of output should be sent to user for each field.

**Comment by v-thgratMSGit** [comment]
Closing this issue due to age. @ankitbko - please open a new issue if this is not fixed and needs further discussion.
