### ISSUE TITLE
Facebook list with more than 3 members not diplaying

### ISSUE THREAD

**Issue by ankitbko** [Microsoft/BotBuilder#642]
In facebook messenger, buttons are just not displayed if the choices exceed 3. This used to work earlier. The buttons in fb used to display as groups of 3.

Below is the screenshot of Annotated Sandwich Bot, notice how the initial list of sandwich options are not displayed. 

![](https://cloud.githubusercontent.com/assets/3169316/16707403/a4a151ec-45e9-11e6-97f4-73ffe11e4a8a.png)

**Comment by tomlm** [comment]
hmmm. this is working for me. Are you setting title or text property on the attachment?

**Comment by ankitbko** [comment]
@tomlm I just published annotated sandwich bot. It is only happening in v3. I also checked with my other bots and all are facing same issue. If I switch back to v1 it works fine.

**Comment by yuyuvn** [comment]
my bot not even show buttons when there are 2 choices
```
builder.Prompts.choice(session, "Tell me what can I do for you.", ["option A", "option B"]);
```
<img width="195" alt="capture" src="https://cloud.githubusercontent.com/assets/6410496/16755189/06c6d4fa-4824-11e6-87fd-fb1c7e9db75f.PNG">

**Comment by msft-shahins** [comment]
this should be fixed now: 

![image](https://cloud.githubusercontent.com/assets/17562300/16817888/c4046cfa-48f9-11e6-910e-bd23adebc459.png)
