### ISSUE TITLE
Is there Direct Line API V3.0?

### ISSUE THREAD

**Issue by eddie1976** [Microsoft/BotBuilder#645]
I found Direct Line API V1.0 is not working after upgrading Bot Framework Version 3.0. So please clarify.

1. Direct Line API V1.0 is not working in Bot Framework Version 3.0?
2. There will be Direct Line API V3.0?

Thanks!

**Comment by willportnoy** [comment]
Are you using the latest nuget package?

https://www.nuget.org/packages/Microsoft.Bot.Connector.DirectLine/

It should be working, as far as I know.  Do you see a specific error message?

**Comment by eddie1976** [comment]
I didn't use nuget package. I got "(500) Internal Server Error" when I send Message. So should I use the latest nuget package released on 2016/7/8?

**Comment by willportnoy** [comment]
Yes, I would use the latest nuget package.

**Comment by eddie1976** [comment]
Okay. I will try it later today. And may I know that is there any change to Direct Line after Bot Framework Version V3.0 released?

**Comment by dandriscoll** [comment]
The existing version of Direct Line will work with v1 and v3 Bot Framework bots. We'll release a new version of Direct Line in the future.

Cheers
--Dan

**Comment by JasonBSteele** [comment]
Hi, unfortunately Microsoft.Bot.Connector.DirectLine v1.0.2 uses Microsoft.Rest.ClientRuntime v1.8.2, but Microsoft.Bot.Builder v3.2.1 is using Microsoft.Rest.ClientRuntime v2.3.2. So any solution that references both DirectLine and Bot.Builder will have a compatibility problem with the Rest.ClientRuntime. 

I have this problem as my API project provides endpoints for client apps using DirectLine as well as being the final destination for the bot calls.

Can we have an ETA on the updated DirectLine package?

**Comment by willportnoy** [comment]
@JasonBSteele you may want to open a new top level issue for the ClientRuntime issue so we can triage it separately.

**Comment by JasonBSteele** [comment]
HI @willportnoy, thanks for the suggestion. There is a top level issue logged at https://github.com/Microsoft/BotBuilder/issues/138. It includes a workaround for including both versions of Microsoft.Rest.ClientRuntime in your solution.

**Comment by alin-nemet** [comment]
Hi guys, I have a question: I have custom storage for my bot, configured through the ChatConnector, ie replaced state.botframework.com with a custom endpoint; our client uses direct client api; does direct line store data, maybe temporarily? I mean, when I start a conversation, then invoke get messages, it appears direct line gives me messages without hitting my bot connector's api getData, which makes me think it somehow has received it at some point through some interaction direct-line and my bot app; is there a way to know how the whole flow works? I also invoked get message directly for a conversationId:
userMessageSet = userConversations.GetMessages(conversationId);
and it didn't hit the bot connector from my app at all, which seems to tell that direct client (https://directline.botframework.com) somehow stored or cached the answer to a previous conversation.
Thanks.

**Comment by willportnoy** [comment]
@alin-nemet you should probably open a top-level issue for new questions.

To try to answer your question, DirectLine and the Bot State service are unrelated services, so calling DirectLine shouldn't have much to do your custom Bot State service.

**Comment by alin-nemet** [comment]
thanks for answering, but can you please elaborate a bit? How does direct line interact with the bot app, is direct http calls, or do they happen through microsoft botframework hub (where we register the bot, with appid and secret)? Does direct line store converastion data somewhere in the cloud or just in memory, and for how long? Thanks a lot!

**Comment by willportnoy** [comment]
DirectLine uses the same web service bot endpoint that other channels use.  There is an intermediate "Direct Line" service.  It stores conversation data for a short period of time (to enable queuing) in the cloud (for fault tolerance), for that short period of time.  I think the "short period of time" is something less than a day, but it's subject to change over time.

Open a new issue for further questions please - we don't necessarily pay attention to closed issues.

**Comment by alin-nemet** [comment]
that clarifies it, thanks a bunch :) sure, no more posting here.

**Comment by dandriscoll** [comment]
Hi @JasonBSteele, the latest release of Microsoft.Bot.Connector.DirectLine uses Microsoft.Rest.ClientRuntime 2.3.2

**Comment by JasonBSteele** [comment]
@dandriscoll - that's great news - thanks for letting me know! 😃
