### ISSUE TITLE
Skype not working when switching back to v1

### ISSUE THREAD

**Issue by ankitbko** [Microsoft/BotBuilder#646]
I was testing out v3 and migrated my bot. But due to unavailability of skype application, I reverted back to v1. But now the skype channel is no more working whereas facebook channel works. Also I am not able to open my application [here](https://developer.microsoft.com/en-us/skype/bots/manage). It is just showing following message.
![image](https://cloud.githubusercontent.com/assets/3169316/16732764/544fcdfe-479c-11e6-911f-ab266f5f2abf.png)

I tested out using ngrok and the messages are not coming to my bot through skype.

**Comment by gosha1** [comment]
+1

**Comment by rmatosaw** [comment]
The same for me. Also, e-mail Office 365 is not running.

All the other channels are running well (it was necessary to resubmit Telegram key).

**Comment by v-thgratMSGit** [comment]
Closing this issue. @ankitbko - please open a new issue if this issue is not fixed and needs further discussion. Thanks!
