### ISSUE TITLE
Node.js - Attachments, Cards and Actions

### ISSUE THREAD

**Issue by filipeperdigaosousa** [Microsoft/BotBuilder#647]
Hi, 
I'm currently lookup the bot builder capabilities for the new version.
I saw that there are some examples about how to use cards, attachments and this kind of stuff through the .Net SDK.
Where can I found some example of that for Node.js?

Thanks

**Comment by stevepkr84** [comment]
Some good examples here: https://github.com/Microsoft/BotBuilder/blob/master/Node/examples/demo-skype/app.js

**Comment by Stevenic** [comment]
Yes... Start with the demo bot. Better docs and more examples are coming.

**Comment by filipeperdigaosousa** [comment]
Thank for your answers.
They were very usefull

**Comment by safiresh** [comment]
When we will expect the Skype app (mac & web) will support new features like cards & carasouls.
Any date microsoft  allowance ?
