### ISSUE TITLE
Severity Code Description Project File Line Suppression State Error Unable to resolve dependencies. 'Microsoft.Rest.ClientRuntime 2.3.0' is not compatible with 'Microsoft.Bot.Connector 1.1.0 constraint: Microsoft.Rest.ClientRuntime (>= 1.8.2 && < 2.0.0)'.

### ISSUE THREAD

**Issue by vk4421** [Microsoft/BotBuilder#650]
Please help me to resolve this issue. Microsoft.Rest.ClientRuntime is not updating and i need to update my bot to get it working ASAP.

![image](https://cloud.githubusercontent.com/assets/11028951/16743331/6817032a-47c9-11e6-8e41-9bb63775b3fd.png)

**Comment by vk4421** [comment]
I got this error when i published my bot to azure and tested my connection with bot (published bot to azure ignoring above error in screenshot).  

InternalServerError
{
  "message": "An error has occurred.",
  "exceptionMessage": "Could not load type 'System.IdentityModel.Tokens.TokenValidationParameters' from assembly 'System.IdentityModel.Tokens.Jwt, Version=5.0.0.127, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.",
  "exceptionType": "System.TypeLoadException",
  "stackTrace": "   at Microsoft.Bot.Connector.BotAuthentication.<OnAuthorizationAsync>d__16.MoveNext()\r\n   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)\r\n   at Microsoft.Bot.Connector.BotAuthentication.OnAuthorizationAsync(HttpActionContext actionContext, CancellationToken cancellationToken)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"
}

**Comment by vk4421** [comment]
There is same error everywhere

![image](https://cloud.githubusercontent.com/assets/11028951/16744715/f7ba27d6-47cf-11e6-8d19-ccc8fa3ca04a.png)

![capture](https://cloud.githubusercontent.com/assets/11028951/16744744/21f38ac4-47d0-11e6-99d7-9978feb25b93.PNG)

**Comment by msft-shahins** [comment]
I am seeing `Microsoft.Bot.Connector 1.1.0` in the title of the issue. Make sure to remove the dependency to Microsoft.Bot.Connector from your project since connector.dll is now packaged inside Microsoft.Bot.Builder.

**Comment by vk4421** [comment]
Thanks... but what about Internal server error even after resolving nuget error

**Comment by msft-shahins** [comment]
@vk4421, the error that you are seeing is because emulator url is set to localhost and your bot from azure is trying to make a post to ServiceUrl set for the message which is `http://localhost:9000`. In the new messaging model, replies are sent to emulator or channel by a direct HTTP post to the ServiceUrl set in the incoming message. You can read more about it [here](http://docs.botframework.com/en-us/support/upgrade-to-v3/#sending-replies). 

To fix your issue, you can either run your bot locally and then posts to localhost from bot should work or you can use a tunneling tool to localhost, e.g. [ngrok](https://ngrok.com/), to have an addressable url to your localhost.

**Comment by magupisoft** [comment]
May be you have FIPS enabled. For Disabled FIPS:  run GPEDIT.MSC and navigate to Computer Configuration > Windows Settings > Security Settings > Local Policies > Security Options and disable "System cryptography: Use FIPS compliant algorithms for ..."

**Comment by nwhitmont** [comment]
@magupisoft You are commenting on a closed issue. 

If you have a question or problem, please [open a new issue.](https://github.com/microsoft/botbuilder/issues/new)
