### ISSUE TITLE
Sample tutorial doesn't work on new build

### ISSUE THREAD

**Issue by joannapod** [Microsoft/BotBuilder#655]
I am getting the following errors when running the sample tutorial code with the latest Nuget update (3.0.1) and the latest Bot Framework Emulator:

"An error occurred while sending request --> The underlying connection was closed: Unexpected error occurred on send. 
System.IO.IOException: The handshake failed due to an unexpected packet format"

Is there a bug? Everything was working fine last week. Thanks!

**Comment by willportnoy** [comment]
I don't know of any relevant bugs.  Usually I see that error when there is a mismatch between http and https.

**Comment by willportnoy** [comment]
I'm going to close this issue - feel free to open a new issue for further discussion.
