### ISSUE TITLE
I am facing this issue.....Do anyone have solution for this..? Severity Code Description Project File Line Source Suppression State Error  Unable to connect to Address='192.168.1.**' with User='S*** MAC Mini' CC.iOS C:\Program Files (x86)\MSBuild\Xamarin\iOS\Xamarin.iOS.Windows.After.targets 54 Build

### ISSUE THREAD

**Issue by Amol8475** [Microsoft/BotBuilder#658]

**Comment by willportnoy** [comment]
Is this related to the bot framework?

I don't think we use anything in the private network IP space (192.168.1.* - see https://en.wikipedia.org/wiki/Private_network#Private_IPv4_address_spaces for more details).

**Comment by willportnoy** [comment]
I'm going to close this issue - feel free to open a new issue for further discussion.
