### ISSUE TITLE
Send message bot to user 

### ISSUE THREAD

**Issue by safiresh** [Microsoft/BotBuilder#659]
I am new for bot framework. I want to send message  without session object. My user order  other applications (web)  means  i want to send msg to his skype via bot.  I am using nodeJS

**Comment by liiver** [comment]
I am also having same issues. My but was using V1 and I used SendMessageAsync to initiate messages to Skype groups. Now in V3 they say its not supported now. This is unacceptable as it is like a paramount feature.

**Comment by niktechie** [comment]
I am also facing the same issue in nodejs. Please let me know if anybody is able to do that

**Comment by eanders-MS** [comment]
@safiresh @niktechie, the Node SDK's `UniversalBot` has a `send` method that takes a message parameter. Because it isn't a reply, the `message.address` field must be filled out.

@liiver I am less familiar with the C# SDK. Let me research that...

**Comment by eanders-MS** [comment]
One detail worth mentioning: Different channels have different requirements for whether they will allow an unsolicited message from a bot. In Telegram for example, the user must have sent at least one message to the bot previously.

**Comment by safiresh** [comment]
Thanks @eanders-MS already done . I forgot to mention & close this issue. But In skype need conversion ID . we cant send message using skype username or email. So we need to store that conversionId for address while sending message.

**Comment by Rexmundier** [comment]
Noticed this topic here, I am having similar issues right now. Can you tell us how you solved it please?

**Comment by mecampbellsoup** [comment]
https://github.com/Microsoft/BotBuilder/issues/659#issuecomment-237695913

@eanders-MS do you know if this applies to Skype as well? I'm trying to start a convo via Node SDK `BotFrameworkAdapter.createConversation` but it only seems to work when I already have a DM convo with the bot established...

**Comment by eanders-MS** [comment]
@mecampbellsoup Sorry I don't have the answer. @Stevenic do you know Skype's requirements here?
