### ISSUE TITLE
Connectors not able to switch language whose name consists more than one word (e.g. Chinese Traditional)

### ISSUE THREAD

**Issue by StephenTung-CR** [Microsoft/BotBuilder#66]
We can switch the bot's output language according to http://docs.botframework.com/connector/bot-options/#navtitle

> User: I would like to speak spanish
> Bot: Voy a usar el español. Déjeme saber si usted quiere cambiar hacia atrás.

While this works with languages like Spanish, languages that consists of more than one word like Chinese Tradition, Serbian Cyrillic doesn't not work. I suspect this is a simple string parsing issue but since the code for this is not open I can't really contribute.

> User: I would like to speak Chinese Traditional
> Bot: I can use any of the following languages:
> Arabic
> * Bosnian
> * Bulgarian
> * Catalan
> * Chinese Simplified
> * Chinese Traditional
> * Croatian
> * Czech
> * Danish
> * Dutch
> * English
> * Estonian
> * Finnish
> * French
> * German
> * Greek
> * Haitian Creole
> * Hebrew
> * Hindi
> * Hmong Daw
> * Hungarian
> * Indonesian
> * Italian
> * Japanese
> * Kiswahili
> * Korean
> * Klingon
> * Latvian
> * Lithuanian
> * Malay
> * Maltese
> * Norwegian
> * Persian
> * Polish
> * Portuguese
> * Querétaro Otomi
> * Romanian
> * Russian
> * Serbian Cyrillic
> * Serbian Latin
> * Slovak
> * Slovenian
> * Spanish
> * Swedish
> * Thai
> * Turkish
> * Ukrainian
> * Urdu
> * Vietnamese
> * Welsh
> * Yucatec Maya

**Comment by tomlm** [comment]
This is now fixed.
