### ISSUE TITLE
LuisRecognizer and "none" intent: why are entities removed?

### ISSUE THREAD

**Issue by thingista** [Microsoft/BotBuilder#660]
At the moment, if the LuisRecognizer finds a "none" intent, the data from Luis seems to get completely deleted by the framework.
On the bot side, in `onDefault`, we only get:

`{"score":0,"intent":null}`

instead of:

`{
    "score": 0,
    "intent": null,
    "intents": [
        {
            "intent": "None",
            "score": 0.928112447
        },
        {
            "intent": "findCar",
            "score": 0.005508761
        },
    ],
    "entities": [
        {
            "entity": "from Audi",
            "type": "brand",
            "startIndex": 4,
            "endIndex": 12,
            "score": 0.977639735
        }
    ]
}`

Is there a reason why this is like this? Should the onus of ignoring the additional data be on the bot's side?

For instance in our case we do need these entities even if no intent was found. We use them to trigger further questions to the user.

**Comment by willportnoy** [comment]
It looks like the entities are copied independently of intent:

https://github.com/Microsoft/BotBuilder/blob/master/Node/core/src/dialogs/LuisRecognizer.ts#L64

@Stevenic ?

**Comment by Stevenic** [comment]
This should be resolved in the latest version of the SDK. Let me know if it's still happening and I'l lre-open the issue.

**Comment by yaalisri** [comment]
I also have the same issue as @thingista. I need to extract the entities and as further questions even there is no intent found. Please let me know how to acheive this using node.js

**Comment by Stevenic** [comment]
You should be able to listen for "None" now.
