### ISSUE TITLE
Skype bot responds with long delays

### ISSUE THREAD

**Issue by qatestolegmig** [Microsoft/BotBuilder#6620]
## Version
Botframework 4.14.0 (latest)
Language: Node.js
Channel: Skype

## Describe the bug
Starting on 26 Oct 2023 my skype bot started responding with long delays. Every stage (local, dev, rc, prod) is affected. To ensure this isn't connected to my codebase I just cloned folder with node.js echo bot sample and ran it - and the issue is still here. I tried to do this with different servers, with ngrok usage or without it - nothing helped. Usually delays are from 10 to 40 seconds, and they're very annoying for my clients.

## To Reproduce
1. Clone the official sample **02.echo-bot** folder from this repository
2. Add appId/appPassword of your skype bot registered in azure portal
3. Run the app
4. Type something to the bot

## Actual behavior
Bot responds in 10+ seconds

## Expected behavior
Bot responds in several seconds

## Additional context
My bot is registered in Azure. I tried to move the bot's resource group to another region - it didn't help. I searched for open Azure incidents or outages but found nothing.
I don't know which support team is responsible for this issue, but it's happening for 5 days and I don't know what to do.
Please let me know if this issue is related to the botframework sdk or not.

**Comment by dmvtech** [comment]
If it is happening for sample 02, it is likely not SDK related. 

- Is the issue still occurring? 
- Does the issue happen if you test with locally running bot and ngrok? Or does it only reproduce with a deployed bot?
- You could try and look at the Application Insights logging for your bot and see if you are able to confirm there. Additionally, you could look at times in ngrok as well to see if you could narrow down where the delay is happening.

**Comment by dmvtech** [comment]
Closing due to lack of response.
