### ISSUE TITLE
[Question] IntentDialog for C#?

### ISSUE THREAD

**Issue by garypretty** [Microsoft/BotBuilder#663]
Hi,

With the recent release of the v3 of the framework it appears that LUISDialog has been deprecated and replaced with IntentDialog for Node, but for C# there is no mention of IntentDialog.  Can anybody confirm if we should still be using LUISDialog for .NET bots?

Thanks

Gary

**Comment by msft-shahins** [comment]
LuisDialog are still functional in C# and should be used for .Net bots. The plan is adding a similar intent dialog to C# in the long run but LuisDialog + CommandDialog covers all of the cases that IntentDialog in node.js covers for C#.
