### ISSUE TITLE
3.01 - Kik - Message with multiple hero card attachments w/buttons

### ISSUE THREAD

**Issue by stevepkr84** [Microsoft/BotBuilder#665]
Due to how Kik tends to work, sending a button causes a popup. If you send a message with say 3 attachment hero cards, each with a button, then only one popup will show, and is only there temporarily. 

My requirement is for the cards to link out to an external url. In v1 this was ok, I simply disabled buttons (actions) for kik and the setting of the titleLink property caused the card itself to link out to the right URL. However in V3, there is no such property, and in the case of the below code, the card links out to the image.

            var att = new builder.HeroCard(session)
                .title(myTitle)
                .text(myText)
                .images([
                    builder.CardImage.create(session, myLogoUrl)
                ])
                .buttons([
                    builder.CardAction.openUrl(session, myExternalUrl, myButtonText)
                ]);

            attachments.push(att);

As far as I can tell none of the other attachment types allow the card to link out to a url.

**Comment by stevepkr84** [comment]
Closing this as I worked it out, apologies for any time wasted.
The answer for interested parties was to add a call to .tap(myExternalUrl) to the declaration of the hero card.

**Comment by somprabhsharma** [comment]
Hi @stevepkr84, can you tell how did it worked for you ? please send the syntax ?
