### ISSUE TITLE
Slack interactive messages error - 5XX_service_error

### ISSUE THREAD

**Issue by garypretty** [Microsoft/BotBuilder#666]
I have just published my V3 version of my bot which is available in slack.  The seems to be working well apart from buttons in slack.  This is a .NET based bot - are slack buttons even supported in .NET v3?

I have added the https://slack.botframework.com/api/Actions as the Request URL for interactive messages, but when I click a button served up in an options prompt by my bot I get the following message;

**'Darn – that didn't work (error message: `5XX_service_error`).**

Buttons presented and selected in the emulator work fine.

Does anyone have any idea what is happening here?

Thanks

**Comment by craigjensen** [comment]
Please add your BotId anf we'll take a look.

**Comment by garypretty** [comment]
Thanks for the quick response, appreciate it! 
My AppId is ca6148b6-486d-4e45-b2af-96f683de5e05

**Comment by craigjensen** [comment]
Your bot doesn't have a verification token which is required to use buttons.  Go to the dev portal and edit your config and follow the instructions to enable interactive messages.

**Comment by garypretty** [comment]
Fantastic. As this was optional when I first setup the Slack connection I hadn't thought to go back and supply this. It is all working now. Thanks for your swift assistance.

**Comment by deepthakannan** [comment]
I'm facing this issue though I have configured my app with verification token from slack. My app id:  c8c4dacd-f7f9-4c9a-a32c-0e7758c3f665. Does anyone have any idea what I could be missing?
