### ISSUE TITLE
V3 api, SendAsync no longer returns a Task<Message>

### ISSUE THREAD

**Issue by mephisto83** [Microsoft/BotBuilder#668]
V3 api, SendAsync no longer returns a message. For our solution this is a problem, we are creating a distributed bot system where functional teams will create dialogs for specific pieces of our system. We are  expecting to cover over 400 modules with a single bot entity. In order to do that, we need to control the messages sent to the user in our system. Since the SendAsync no longer returns Task<Message> we no longer have control over this integral part of the system. We are trying to build a scalable system with pluggable pieces of functionality, and controlling the messages is crucial. I hope that I am missing some piece of code that will give me access to the messages that are emitted from the system. Any help is appreciated.

**Comment by chon219** [comment]
We are also facing the same problem, as SendAsync no longer returns a Task<Message>, it is impossible for us to access bot's replies from dialogs. Any solutions? Please.

**Comment by willportnoy** [comment]
You can provide an implementation of IBotToUser like this:

https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Dialogs/DialogModule.cs#L173

where you can hook all outgoing messages to modify or log them as you wish.

In V1, only the last message out of multiple replies was returned through the SendAsync method - the others were sent directly through IBotToUser.

**Comment by willportnoy** [comment]
I'm going to close this issue - feel free to open a new issue for further discussion.
