### ISSUE TITLE
Problems with v3.0.1 and ChatConnector in slack using node.js

### ISSUE THREAD

**Issue by javi-jamaa** [Microsoft/BotBuilder#670]
In slack when I send a direct message to the boot, randomly I don't get the answer and the following error appears in the trace: "ERROR: ChatConnector: receive - invalid token. Check bots app ID & Password.")
I'm using the node framework.

**Comment by javi-jamaa** [comment]
There was one similar

**Comment by cnrudd** [comment]
getting the same issue.   also getting The remote server returned an error: (409) Conflict. when I try to save the upgrade of my bot in the dev.botframework site.
I've set my api/messages endpoint to SSL, updated my appId and appPassword.  My bot works using the consoleConnector, so, I have correctly updated my code for v3.0.1.

I also see this ERROR: ChatConnector: receive - invalid token. Check bots app ID & Password. in the logs.

**Comment by DirkSonguer** [comment]
For reference, it was this one: https://github.com/Microsoft/BotBuilder/issues/657

**Comment by cnrudd** [comment]
I had to delete my old v1 bot, and create a new v3 bot from scratch at dev.botframwork.com -- and  create new MS App -- for the 'The remote server returned an error: (409) Conflict.' error to go away.  My newly created bot had no problem connecting to my newly migrated v3 code.

-Colin
