### ISSUE TITLE
V3 Emulator Not working

### ISSUE THREAD

**Issue by b4usat** [Microsoft/BotBuilder#675]
I am surprised may be am the one who is facing this issue. I upgraded to V3 BotBuilder via Nuget. Also i updated my emulator to 3.0 version. When i execute the code with default Method in it for `Post ` itself throws error. Interesting thing is my chats in emulator reaching my code takes more than one minute. I haven't put anything in MS App Id and Secret Key. Morethan that i not even put a single line of code, its all scaffold templates are there. No idea why i am getting this weird behavior.  Please help. I tried uninstalling the emulator and re-install. No luck

**Comment by Thegaram** [comment]
What is the error that you're seeing?

**Comment by danmarshall** [comment]
Hello @b4usat, if you see this error again please open a new issue, I am closing this for now, thanks.
