### ISSUE TITLE
LUIS connectivity first attempt

### ISSUE THREAD

**Issue by vvvlad** [Microsoft/BotBuilder#676]
Hi,
I'm getting the following exception when trying to use LuisDialog.

> A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 104.42.105.69:443

Bot.Builder version 3.0.1
Emulator version 3.0.0.54

any suggestion what can be done and what is going on?

**Comment by msft-shahins** [comment]
Have you set the right subscription key and model id for your LuisDialog? The error looks like a timeout error because of networking issue. Can you check if you can query your luis.ai model directly from your computer?

**Comment by vvvlad** [comment]
Hi,
Thanks for your reply!
I've copied the exact key and model id from the LUIS configuration page, also verified against the rest URL that is generated when publish.
I'm not sure what you mean by directly from my computer. If you mean pasting the rest address to a browser with search key, then I did that and it works as expected.
Any additional information I should look for? Anything else that can help pinpointing the source of the issue?

Thanks again

**Comment by NanashiGIT** [comment]
Im not sure whether you tried that, but to rule out that your PC is the culprit:
Have you tried publishing the bot to azure and then trying out, whether its able to connect to luis?
If it can, then it has something to do with your local machine.

**Comment by willportnoy** [comment]
@vvvlad do you use a web proxy?

**Comment by vvvlad** [comment]
Thanks for your replies.
@NanashiGIT I don't have that option right now
@willportnoy Not sure what web proxy is. I do work inside enterprise network and browser has proxy configuration. Can the Emulator be configured to work with proxy?

I've also tried to configure proxy as a global system variable (for example it helps to work with Python packages), but that didn't help either.

**Comment by danmarshall** [comment]
Hi @vvvlad are you still having this issue?

**Comment by vvvlad** [comment]
I discovered it was not supposed to work :(
Thanks again for all the support!
