### ISSUE TITLE
CardAction with call not working

### ISSUE THREAD

**Issue by NicolasHumann** [Microsoft/BotBuilder#677]
Hi

I tried to create a CardAction with the type call, but the card is not diplayed on FB Messenger. Am I doing something wrong ?

` CardAction telButton = new CardAction()
                {
                    Value = "tel:0474111196",
                    Type = "call",
                    Title = "Call Me"
                };`

**Comment by tomlm** [comment]
There is now cardaction of type "call".  Use type="openUrl"
