### ISSUE TITLE
Skype connector stopped working

### ISSUE THREAD

**Issue by arieschwartzman** [Microsoft/BotBuilder#678]
It was working before in 3.0 no I get this message when trying to add the Skype channel

Sad bot is sad because skype failed to register ChannelAccount for bot: 0000000040192E34 - System.IO.FileLoadException: Could not load file or assembly 'HtmlAgilityPack, Version=1.4.9.0, Culture=neutral, PublicKeyToken=bd319b19eaf3b43a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) File name: 'HtmlAgilityPack, Version=1.4.9.0, Culture=neutral, PublicKeyToken=bd319b19eaf3b43a' at Intercom.Models.Storage.SanitizeHtmlLink(String input) at Intercom.Models.Storage.<SetBotContactForChannelAsync>d__64.MoveNext() in C:\a\1\s\Intercom.Models\Storage\BotOperators.cs:line 392 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at SkypeChannel.Controllers.DevController.<ConfigureNewSkypeChannel>d__17.MoveNext() in C:\a\1\s\Channels\SkypeChannel\Controllers\DevController.cs:line 463 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) at SkypeChannel.Controllers.DevController.<Index>d__9.MoveNext() in C:\a\1\s\Channels\SkypeChannel\Controllers\DevController.cs:line 72 WRN: Assembly binding logging is turned OFF. To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1. Note: There is some performance penalty associated with assembly bind failure logging. To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

**Comment by dandriscoll** [comment]
Do you get this consistently or did it only happen once?

**Comment by arieschwartzman** [comment]
I get it constantly. I have now created new BOT and Skype connector is already there. It is does work.

**Comment by pietie** [comment]
I get the same error. I'm using v3 but removed the Skype channel that was automatically added. When I try and add it back I get this error.

**Comment by tomfurrier** [comment]
+1, switched to v3, then tried to add a Skype channel, and it gives this same error.

**Comment by lokijota** [comment]
Same here.

**Comment by wtam** [comment]
I use V3 and its works in the past few days till yesterday , my  skype bot  on PC suddenly show "Messaging Unavailable" and I can't typing anything from Skype.  but the bot still show online?  Anyone see the same thing?

**Comment by wtam** [comment]
found the work around for "Messaging Unavailable" issue is to delete the skype bot contact and add it back again then its works again.
