### ISSUE TITLE
Something bad happend to the last commit of ChatConnector

### ISSUE THREAD

**Issue by arieschwartzman** [Microsoft/BotBuilder#680]
These lines seems to be totally broken. Notice the hardcoded url, decodedPayload does not have the appid property (should be aud?)
What gives?
```
ChatConnector.prototype.verifyEmulatorToken = function (decodedPayload) {
        var now = new Date().getTime() / 1000;
        return decodedPayload.appid == this.settings.appId &&
            decodedPayload.iss == "https://sts.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47/" &&
            now < decodedPayload.exp && now > decodedPayload.nbf;
    };
```

**Comment by msft-shahins** [comment]
This is a special case for tokens generated by emulator (different than tokens generated by connector channels). They have a data payload that have the appid in them. The data payload in the tokens generated by emulator looks like below: 

{
  "aud": "https://graph.microsoft.com",
  "iss": "https://sts.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47/",
  "iat": 1468444418,
  "nbf": 1468444418,
  "exp": 1468448318,
  "appid": "fc8b70c8-951b-482e-9b75-29a4a2da5361",
  "appidacr": "1",
  "idp": "https://sts.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47/",
  "tid": "72f988bf-86f1-41af-91ab-2d7cd011db47",
  "ver": "1.0"
}
