### ISSUE TITLE
Direct Line Attachment File Extensions

### ISSUE THREAD

**Issue by XelaMon** [Microsoft/BotBuilder#682]
Whenever I try to get an attachment from Direct Line, it shows up in the browser's download manager with the name '0', despite there having been a name assigned to the file on the bot server. There is also no extension. 

Is there anyway to be able to download the file with the proper extension from the Direct Line API?

**Comment by Samurais** [comment]
hi, @XelaMon 

I also want to use Direct Line API, but I couldn't get messages from bot, may you have a look at #672 ?

Thanks.

**Comment by dandriscoll** [comment]
Is your bot talking the v1 protocol or the v3 protocol?

**Comment by Samurais** [comment]
v3 protocol

**Comment by XelaMon** [comment]
@dandriscoll I'm looking at moving to v3 in the near future, but as of now my bot is on v1. If I can see attachment extensions if I upgrade to v3, I'd definitely do that!

**Comment by danmarshall** [comment]
Hi @XelaMon have you had a chance to update to v3 ?
