### ISSUE TITLE
[Node.js] Do we still need bot.verifyBotFramework() in v3?

### ISSUE THREAD

**Issue by Orbyt** [Microsoft/BotBuilder#683]
The old examples said to use `server.post('/api/messages', bot.verifyBotFramework(), bot.listen());`, but I noticed that when upgrading to v3 (and subsequently using `UniversalBot` and `ChatConnector`) , it just uses `server.post('/api/messages', connector.listen());`

Do we no longer need `bot.verifyBotFramework()`?

**Comment by brene** [comment]
No, you don't seem to need it anymore. Since it automatically verifies it now for you ;-). 

Please close this issue, if this is a good enough answer 😄

**Comment by Stevenic** [comment]
Yes... `connector.listen()` is all that's needed in v3. You're basically forced to use verifyBotFramework() now.
