### ISSUE TITLE
How is the new Middleware class used?

### ISSUE THREAD

**Issue by Orbyt** [Microsoft/BotBuilder#684]
How is `firstRun` supposed to be used? http://docs.botframework.com/en-us/node/builder/chat-reference/classes/_botbuilder_d_.middleware.html#firstrun

I checked out the first run example and it looks exactly the same as the old way (storing a first run boolean in the session and checking it on startup).

So how is it supposed to be done now?

**Comment by willportnoy** [comment]
I'm not sure I understand your question.  This looks like an example of using the middleware to have a first run experience:

https://github.com/Microsoft/BotBuilder/blob/c834e21787fc48b253276b94e2ff66d4a5ebd720/Node/examples/basics-firstRun/app.js#L34

and the firstRun middleware is a standardized implementation of that middleware:

https://github.com/Microsoft/BotBuilder/blob/c4dbb7183cc1c23837b6d6c8bc03fe8c54ba1f55/Node/core/lib/middleware/Middleware.js#L27

**Comment by Orbyt** [comment]
Yes, how is `Middleware.firstRun` supposed to be used?

In the first example you linked, `session.userData.firstRun` is a user defined variable, and could be named anything as its just a boolean. How is the built-in `firstRun` used?

**Comment by Stevenic** [comment]
I've updated the firstRun example to use the new middleware. Sorry for the delay.
