### ISSUE TITLE
Problem installing Microsoft.Bot.Connector

### ISSUE THREAD

**Issue by joannapod** [Microsoft/BotBuilder#685]
Hello, trying to install the Microsoft.Bot.Connector package and getting this error. Can someone suggest a solution?

Attempting to resolve dependencies for package 'microsoft.bot.connector.1.1.0' with DependencyBehavior 'Lowest'
install-package : Unable to find a version of 'Microsoft.Rest.ClientRuntime' that is compatible with 'Microsoft.Bot.Builder 3.0.1 constraint: 
Microsoft.Rest.ClientRuntime (>= 1.8.2)', 'Microsoft.Bot.Connector 1.1.0 constraint: Microsoft.Rest.ClientRuntime (>= 1.8.2 && < 2.0.0)'.
At line:1 char:1
+ install-package microsoft.bot.connector
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by joannapod** [comment]
P.s trying to install the previous version doesn't work either (v1.0.0)

**Comment by willportnoy** [comment]
What version of Microsoft.Rest.ClientRuntime do you have installed now?

**Comment by msft-shahins** [comment]
Also make sure to uninstall Microsoft.Bot.Connector nuget from your project before installing the new Builder nuget.
