### ISSUE TITLE
[Suggestion] PromptDialog + Quick Replies (FB)

### ISSUE THREAD

**Issue by eddie1976** [Microsoft/BotBuilder#686]
It will be very convenient for users to use "Quick Replies" to answer "PromptDialog" in FB Messenger.

**Comment by danmarshall** [comment]
Thanks for the suggestion @eddie1976 - it has been added to our backlog.

**Comment by ejadib** [comment]
@eddie1976 I [wrote basic](http://southworks.com/blog/2016/09/21/using-facebooks-quickreplies-with-promptdialogs/) PromptStyler to take care of this.
