### ISSUE TITLE
[NodeJS] How to attach an image to reply via node.js BotConnector SDK?

### ISSUE THREAD

**Issue by kkso** [Microsoft/BotBuilder#69]
Hi,

I send text like this:
```
bot.add('/', function (session) {
    session.send('Hello World');
});
```

Is there a way to send an attachment in same way?

Like this or somehow:
```
bot.add('/', function (session) {
    session.send({attachments: [{contenttype: 'image/jpg', contenturl: 'http://location.jpg'}]});
});
```

Thanks!

**Comment by Stevenic** [comment]
Sorry for the delay... Yes... That's how you have to do it today. At some point I'm may add something like a session.addAttachment() method which you can use to add attachments as a separate step before calling session.send()

**Comment by Stevenic** [comment]
I should add that to send an attachment today you need to actually fill out the complete message object. So in addition to the list of attachments you need to specify the text as well. We were just talking about this internally and I think the direction we're leaning is not the session.addAttachment() idea I floated but instead we'll probably create a fluent style MessageBuilder class that helps you construct your message and send it.

**Comment by Stevenic** [comment]
I just checked in a new Message builder class that simplifies sending attachments to the user. It'll be in the next build of the node module (probably EOD tomorrow.) If you look at the TestBot example you'll see a new send-attachment.js test which shows how to send an image as an attachment.

I should also note that if you're using Slack you can use session.sendMessage() to send a message using slacks native message format. This would let you create attachments using all of slacks various advanced features.

**Comment by kkso** [comment]
Great! Thank you!

**Comment by kmain4** [comment]
@Stevenic is it possible currently to send a picture attachment and text in the same message?

**Comment by suryavtkt** [comment]
how can I create interactive chart/graph in node.js and send via node.js connector SDK

**Comment by Stevenic** [comment]
You'll need to use a 3rd party library for node that can return the chart/graph as an image. I haven't looked but I'm sure there are several.

**Comment by Jordanjun98** [comment]
how can i set the bot to reply an image for exp: "congratz.jpg" if it fulfil my condition cause i am planning to a quiz chatterbot.
