### ISSUE TITLE
Nodejs automated tests

### ISSUE THREAD

**Issue by hgjkant** [Microsoft/BotBuilder#691]
Hi,
is it currently possible to do automated tests on a bot? I.e. passing a string to a bot and inspecting the result, like done in the TextBot tests?
```js
bot.processMessage({ text: 'hello' }, function (err, reply) {
    assert(reply && reply.text == 'Hello World');
    done();
});
```

**Comment by Stevenic** [comment]
Yes... look at the updated mocha tests. You just need a way to pass the ConsoleConnector into your bot so you may have to export a test function that your test harness can call to initialize the bot with a different connector.

**Comment by hgjkant** [comment]
Thank you very much
