### ISSUE TITLE
activities from facebook channel have empty Name in From

### ISSUE THREAD

**Issue by nexxuno** [Microsoft/BotBuilder#692]
Hello since yesterday activities coming from facebook channel do not have Name filled in the From property, only the Id is correct. Moreover the response is not received by facebook anymore (my REST service was working till yesterday and I already upgraded to v3 and all was working fine). Looks like something was broken on MS part somewhere and the activities are broken both incoming and outgoing on the facebook channel.

Again, my code didn't change and it doesn't throw any exception.

**Comment by willportnoy** [comment]
related to https://github.com/Microsoft/BotBuilder/issues/613

**Comment by msft-shahins** [comment]
Can you share your MicrosoftAppId so we can investigate the problem? For my bots on Facebook, I see Name property in the From field of the incoming activity is getting populated correctly and all my replies are getting delivered to Facebook.

**Comment by nexxuno** [comment]
<add key="MicrosoftAppID" value="1cfa33f8-09a9-4a67-ae93-a2d5d791dc9d"

And here is the activity as received by the Post, actually there is a space and not an empty string... (see bold)

-		message	{Microsoft.Bot.Connector.Activity}	Microsoft.Bot.Connector.Activity
		Action	null	string
		AttachmentLayout	null	string
		Attachments	null	System.Collections.Generic.IList<Microsoft.Bot.Connector.Attachment>
+		ChannelData	{{
  "sender": {
    "id": "1099232223481168"
  },
  "recipient": {
    "id": "541364609405319"
  },
  "timestamp": 1468526903317,
  "message": {
    "mid": "mid.1468526903309:dbd6c48817929e6372",
    "seq": 2152,
    "text": "Ricomincio"
  }
}}	object {Newtonsoft.Json.Linq.JObject}
		ChannelId	"facebook"	string
+		Conversation	{Microsoft.Bot.Connector.ConversationAccount}	Microsoft.Bot.Connector.ConversationAccount
		Entities	null	System.Collections.Generic.IList<Microsoft.Bot.Connector.Entity>
-		From	{Microsoft.Bot.Connector.ChannelAccount}	Microsoft.Bot.Connector.ChannelAccount
		Id	"1099232223481168"	string
		**_Name	" "	string_**
		HistoryDisclosed	null	bool?
		Id	"mid.1468526903309:dbd6c48817929e6372"	string
		Locale	null	string
		MembersAdded	null	System.Collections.Generic.IList<Microsoft.Bot.Connector.ChannelAccount>
		MembersRemoved	null	System.Collections.Generic.IList<Microsoft.Bot.Connector.ChannelAccount>
+		Properties	null	Newtonsoft.Json.Linq.JObject
+		Recipient	{Microsoft.Bot.Connector.ChannelAccount}	Microsoft.Bot.Connector.ChannelAccount
		ReplyToId	null	string
		ServiceUrl	"https://facebook.botframework.com"	string
		Summary	null	string
		Text	"Ricomincio"	string

**Comment by nexxuno** [comment]
P.s. it works on emulator too

**Comment by msft-shahins** [comment]
@nexxuno it seems that you Facebook page access token has been expired and as a result our calls to facebook graph api and send api failr with the error below. Have you changed your password or page password? It seems that can invalidate the page access tokens. Generate a new page access token and update your Facebook channel registration in bot framework with the new access token: 

```json
{
    "error": {
        "message": "Error validating access token: The session has been invalidated because the user has changed the password.",
        "type": "OAuthException",
        "code": 190,
        "error_subcode": 460,
        "fbtrace_id": "########"
    }
}
```

**Comment by nexxuno** [comment]
Thank you! Yes I reset my user password so that's the problem for sure! Thank you! Didn't know the two were related...

Was that an error I could see somehow? So that I will debug it without your support next time?

**Comment by msft-shahins** [comment]
We had a bug in Facebook channel connector that wasn't returning Facebook API failures to caller. After next deployment, your bot's posts to channel should fail in case of Facebook API call failures. Also you should see failures in the ChannelStatus of Facebook channel in the dev portal and if you have provided your application insights key, we will log Facebook failures to your AppInsight container.

**Comment by nexxuno** [comment]
Ok, thank you the posts failures propagation is a very much needed change.

**Comment by msft-shahins** [comment]
This change should be in production now. Feel free to open it again if you still see the issue.
