### ISSUE TITLE
500 internal server error in emulator during resuming conversation.

### ISSUE THREAD

**Issue by Praggie** [Microsoft/BotBuilder#694]
Hi, 
I am resuming conversation similar to what is done in facebook authentication sample. This was working fine in V1 but now I have upgraded to V3 then I am not able to resume the conversation. While no exception is thrown in debugger but I can see "black post" in emulator with "500 internal error". I used following code to send the message
> await connector.Conversations.SendToConversationAsync((Activity)msg);

this seems to be regression. What could be going wrong?

Thanks

**Comment by Thegaram** [comment]
Are you sure there's no exception? Could you include some more details from you code (e.g. how you construct `msg`)? That might help us resolve the issue.

**Comment by msft-shahins** [comment]
@Praggie the resumption should work, one things that have been changed from v1 is that [ResumptionCookie](https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Dialogs/ResumptionCookie.cs#L81) needs a ServiceUrl. Also there should be an exception happening in your code and as a result emulator showing 500 internal error.

**Comment by Praggie** [comment]
Though there was no exception thrown, but i got the hint from Thegaram's comment about message construction that helped in diagnosing the issue. Actually I was getting the message from resumption cookie and sending the same message as reply. I needed to swap From and Recipient to make this work otherwise black error message is seen in the  the emulator without throwing an exception. 

This issue can be closed now.
