### ISSUE TITLE
Expected Wait, Have Done issues

### ISSUE THREAD

**Issue by jamesrlewis** [Microsoft/BotBuilder#695]
I have a LuisAPI class which calls different intents based on user input. I'm trying to call different classes from within each intent to do something special for each one. 

This is part of my LuisAPI class that processes user intents:
`public class LuisAPI : LuisDialog<object>
    {
        public IProcessIntents Processor { get; }
        public LuisAPI(params ILuisService[] services)
        {
            
        }

        [LuisIntent("Greet")]
        public async Task Greet(IDialogContext context, LuisResult result)
        {
            await context.PostAsync("Hello!");
            GreetIntentProcessor Greet = new GreetIntentProcessor();
            await Greet.StartAsync(context);
            //context.Wait(MessageReceived);
        }`

It calls GreetIntentProcessor.StartAsync() which is here:

`[Serializable]
    public class GreetIntentProcessor : IDialog<object>
    {
        private string username;
        private string password;

        public async Task Login(IDialogContext context, IAwaitable<string> result)
        {
            password = await result;
            await context.PostAsync(username + " " + password);
            myOtherAPI api = new myOtherAPI();
            bool success = await api.PostAccessTokenAsync(username, password);
            if (success)
            {
                await context.PostAsync("okay, all logged in");
                Customersummary cust = await api.GetCustomer("customer");
                await context.PostAsync(String.Format("Hello, {0}.", cust.firstName));   
            }
            else
            {
                await context.PostAsync("yikes, didn't work");
            }
        }

        public async Task StartAsync(IDialogContext context)
        {
            //context.Wait<Message>(GetUsername);
            PromptDialog.Text(context, GetPassword, "What's your username?");
        }

        private async Task GetPassword(IDialogContext context, IAwaitable<string> result)
        {
            username = await result;
            PromptDialog.Text(context, Login, "Okay, and what's your password (don't worry, it's 100% confidential)?");
        }`

Essentially, the GreetIntentProcessor creates PromptDialogs to retrieve username and password and log the user in via an api call. Using the emulator, i can walk through the entire login process and successfully login, but when I try to enter another user statement to go to a different intent, I get the following error: 

"message": "An error has occurred.",
  "exceptionMessage": "invalid need: expected Wait, have Done",
  "exceptionType": "Microsoft.Bot.Builder.Internals.Fibers.InvalidNeedException"

If I try uncommenting the context.Wait(MessageReceived) within the [Greet] method, I get this error instead:

"message": "An error has occurred.",
  "exceptionMessage": "invalid need: expected Call, have Poll",
  "exceptionType": "Microsoft.Bot.Builder.Internals.Fibers.InvalidNeedException"

Any ideas?

**Comment by willportnoy** [comment]
You should call child dialogs with the

context.Call(Greet, TheMethodThatReceivesTheResultFromTheGreetChildDialog)

method so we can add that dialog to the stack (and the framework will then call StartAsync on it).

**Comment by jamesrlewis** [comment]
Or what if I don't want really want to return anything from the child dialog? I just want to go through the dialog, make API calls within that dialog, and then return for the user to continue talking to LUIS

**Comment by willportnoy** [comment]
We don't really have "void" child dialogs.  I'd make up a dummy return value (null is fine) to call context.Done(dummy) in your child dialog to return from it.

**Comment by jamesrlewis** [comment]
I can do that. But now when I try to pass in MessageReceived as the ResumeAfter parameter for context.Call, I get the following error: cannot convert from 'method group' to 'ResumeAfter<object>'

**Comment by willportnoy** [comment]
the type of the second parameter for MessageReceived is likely IAwaitable<Message>, but you need a method with a second parameter of IAwaitable<object>, for example, if you're passing null as the result value and the type of your child dialog is IDialog<object>.

**Comment by jamesrlewis** [comment]
Okay. So I can't call MessageReceived? I'm returning context.Done<object>(null)

Also, thanks for your help. It's really appreciated

**Comment by jamesrlewis** [comment]
I think I missed your earlier point since the types of IAwaitables weren't shown.

**Comment by jamesrlewis** [comment]
Actually, nevermind! I think I got it. Here's my solution:

`[LuisIntent("Greet")]
        public async Task Greet(IDialogContext context, LuisResult result)
        {
            GreetIntentProcessor GreetIntent = new GreetIntentProcessor();
            context.Call(GreetIntent, GetUserResponse);
        }

        private async Task GetUserResponse(IDialogContext context, IAwaitable<object> result)
        {
            context.Wait(MessageReceived);
        }`

Thanks for the help

**Comment by willportnoy** [comment]
Sure thing.  Sorry, I should have hit "preview" to see that the generic types were swallowed.

**Comment by willportnoy** [comment]
I'm going to close this issue - feel free to open a new issue for further discussion.
