### ISSUE TITLE
Grabbing the message from an IDialogContext/adding things to IDialogContext?

### ISSUE THREAD

**Issue by epitone** [Microsoft/BotBuilder#700]
Essentially what the title says, I'm following along in one of the doc tutorials and am a bit confused on how I could grab the message a user sends to the bot from a "StartAsync" method - I know that it passes an IDialogContext, is there any way to read the message they've sent from the parameter? I've attempted to copy the code from the example - I'd like to know if it's possible to grab the message the user has sent in the Post method (and is subsequently sent to StartAsync in EchoDialog) through the "IDialogContext context" parameter in StartAsync.

`        public virtual async Task<HttpResponseMessage> Post([FromBody] Activity activity)
        {
            // check if activity is of type message
            if (activity != null && activity.GetActivityType() == ActivityTypes.Message)
            {
                await Conversation.SendAsync(activity, () => new EchoDialog());
            }
            else
            {
                HandleSystemMessage(activity);
            }
            return new HttpResponseMessage(System.Net.HttpStatusCode.Accepted);
        }`

`    [Serializable]
    public class EchoDialog : IDialog<object>
    {
        public async Task StartAsync(IDialogContext context)
        {
            context.Wait(MessageReceivedAsync);
        }
        public async Task MessageReceivedAsync(IDialogContext context, IAwaitable<IMessageActivity> argument)
        {
            var message = await argument;
            await context.PostAsync("You said: " + message.Text);
            context.Wait(MessageReceivedAsync);
        }
    }`

**Comment by msft-shahins** [comment]
You don't have access to the message in StartAsync(...) function. the StartAsync(...) is called first when the dialog is getting constructed ( you can think of it as the init for your dialog). 

Here is the description of the data flow for the EchoDialog: When your conversation first starts, there is no dialog state in the IBotDataStore so the delegate passed to Conversation.SendAsync (MakeRoot) will be used to construct the EchoDialog and it's StartAsync method will be called. In this case, StartAsync  calls IDialogContext.Wait with the continuation delegate (our MessageReceivedAsync method) to call when there is a new message.  

In the initial case there is an immediate message available (the one that launched the dialog) and it is immediately passed To MessageReceivedAsync. Within MessageReceivedAsync we wait for the message to come in and then post our response and wait for the next message. In this simple case the next message would again be processed by MessageReceivedAsync.
