### ISSUE TITLE
LuisDialog trying to match PromptDialog options to intent instead of calling resume method

### ISSUE THREAD

**Issue by craigomatic** [Microsoft/BotBuilder#701]
I've run into what I think might be a bug with the `LuisDialog `and the `PromptDialog`.

In LUIS, I have a LastActionForUser intent which is setup to match firstname/lastname pairs, ie "when did craig last perform an action".

My dataset contains multiple "craig" users, so I show a `PromptDialog `to resolve the correct craig, which results in JSON with a text property "craig 1" or "craig 2".

The `LuisDialog `then seems to be trying to match this to an intent instead of the resume method being called so I can display data for the correct craig.

I'm not sure if this is a bug, expected behaviour or a lack of understanding on my part...

Using v3.0.1 in C#

**Comment by ankitbko** [comment]
Is it possible for you to post code snippets?

**Comment by garypretty** [comment]
If it helps, below is how I am using a choice prompt in a LUIS dialog.

In your intent method you call your dialog as shown below. You need to make sure you use content.call so you pass off to a child dialog.

```
var dialog = new PromptDialog.PromptChoice<string>(new string[] { "Choice 1", "Choice 2" }, "Which one would you like?", "Sorry, that wans't a valid option", 3);
context.Call(dialog, AfterUserHasChosenAsync);
```

Then, you can get the result of the prompt like so in the method below.

```
private async Task AfterUserHasChosenAsync(IDialogContext context, IAwaitable<string> result)
        {
            string userChoice = await result;
            await context.PostAsync("You chose: " + userChoice);
            context.Wait(MessageReceived);
        }

```
Hope that helps.

**Comment by craigomatic** [comment]
Thanks for the suggestion, that's basically what I'm doing.

My `MessagesController `looks like this:

```
internal static IDialog<object> MakeRoot()
        {
            return Chain.From(() => new MemberDialog());
        }

        /// <summary>
        /// POST: api/Messages
        /// Receive a message from a user and reply to it
        /// </summary>
        public async Task<HttpResponseMessage> Post([FromBody]Activity activity)
        {
            // check if activity is of type message
            if (activity != null && activity.GetActivityType() == ActivityTypes.Message)
            {
                await Conversation.SendAsync(activity, MakeRoot);
            }
            else
            {
                HandleSystemMessage(activity);
            }
            return new HttpResponseMessage(System.Net.HttpStatusCode.Accepted);
        }
```

I then have my `MemberDialog` with a simple intent:

```
[LuisIntent("FindMember")]
        public async Task FindMember(IDialogContext context, LuisResult result)
        {
            EntityRecommendation firstNameRecommendation;
            EntityRecommendation lastNameRecommendation;

            var foundFirstName = result.TryFindEntity(EntityConstants.FirstName, out firstNameRecommendation);
            var foundLastName = result.TryFindEntity(EntityConstants.LastName, out lastNameRecommendation);

            if (foundFirstName || foundLastName)
            {
                //search DB, discover multiple, need to work out which one
                var members = _QueryDB(foundFirstName, foundLastName);

                PromptDialog.Choice(context,
                        _ResolveMemberResult,
                        members.Select(s => $"{s.FirstName} {s.LastName}"),
                        "Which one?");
            }
        }

private async Task _ResolveMemberResult(IDialogContext context, IAwaitable<string> memberId)
        {
            await memberId;

            await context.PostAsync("Member found!");

            context.Wait(MessageReceived);
        }
```

I don't seem to be able to get the _ResolveMemberResult method to be invoked, instead the response ends up at my None intent.

```
 [LuisIntent("")]
        public async Task None(IDialogContext context, LuisResult result)
        {
            string message = $"Sorry I did not understand: " + string.Join(", ", result.Intents.Select(i => i.Intent));
            await context.PostAsync(message);
            context.Wait(MessageReceived);
        }
```

The pizza example works as expected and I modeled my code based on it which is why I thought maybe it was something to do with the LUIS matching?

**Comment by garypretty** [comment]
Try replacing

```
            if (foundFirstName || foundLastName)
            {
                //search DB, discover multiple, need to work out which one
                var members = _QueryDB(foundFirstName, foundLastName);

                PromptDialog.Choice(context,
                        _ResolveMemberResult,
                        members.Select(s => $"{s.FirstName} {s.LastName}"),
                        "Which one?");
            }
```

with something like this 

```
            if (foundFirstName || foundLastName)
            {
                //search DB, discover multiple, need to work out which one
                var members = _QueryDB(foundFirstName, foundLastName);
var dialog = PromptDialog.Choice<string>(members.Select(s => $"{s.FirstName} {s.LastName}"), "Which one?", "Sorry, not a valid option, try again", 3);
context.call(dialog, _ResolveMemberResult); 
}
```

The above will create a prompt choice dialog. The first param is your list of options for the user to pick from. The second is the prompt text.  The third is the text to display is the user doesn't pick a valid option and finally the forth is the number of times we should retry taking the choice from the user before failing out.

Once the dialog has been created the context.call adds it as a child dialog and this should ensure that when the user responds they are routed correctly to _ResolveMemberResult.

Let me know if that gets your any further.

**Comment by craigomatic** [comment]
Unfortunately that doesn't get me any further :/

Internally, the static method is calling context.Call with the dialog/resume method (see [PromptDialog.cs](https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Dialogs/PromptDialog.cs)) so it's basically doing the same thing as the code I posted, minus one layer of abstraction.

**Comment by willportnoy** [comment]
@craigomatic are there any thrown exceptions?  You may want to turn on "break on thrown exceptions" or look in your output window.

**Comment by craigomatic** [comment]
Ahhh, yes there is an interesting exception in there!

In `Microsoft.Bot.Builder.Internals.Fibers.FormatterStore<T>` `Save `method: 

> Type 'Framework.Cloud.Storage.MemberRepository' in Assembly Framework.Cloud, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' is not marked as serializable.

My dialog has some instance variables that access Azure Table Storage using the repository pattern, which aren't serializable.

Do the instance variables really need to be serializable? 

In my case they are created in the constructor, so will be recreated when deserialized

**Comment by willportnoy** [comment]
There are a few options:

* don't store that dependency so it won't be serialized (probably not helpful)
* use the reflection serialization surrogate (may not work and risks serializing too much)
* resolve the dependency through autofac and FiberModule.Key_DoNotSerialize (cleanest solution)
https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Fibers/FiberModule.cs#L59
* Use [NonSerialized] and [OnDeserialized] attributes to restore the dependency on deserialization (simplest solution)
https://msdn.microsoft.com/en-us/library/system.nonserializedattribute(v=vs.110).aspx 
https://msdn.microsoft.com/en-us/library/system.runtime.serialization.ondeserializedattribute(v=vs.110).aspx

**Comment by willportnoy** [comment]
I'm going to close this issue, but feel free to open a new issue for further discussions.

**Comment by craigomatic** [comment]
Thanks Will, I forgot to respond earlier, your suggestions were helpful and solved the problem for me :)
