### ISSUE TITLE
Internal Server Error - Any ideas for workaround?

### ISSUE THREAD

**Issue by vk4421** [Microsoft/BotBuilder#703]
InternalServerError
{
  "message": "An error has occurred.",
  "exceptionMessage": "Could not load type 'System.IdentityModel.Tokens.TokenValidationParameters' from assembly 'System.IdentityModel.Tokens.Jwt, Version=5.0.0.127, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.",
  "exceptionType": "System.TypeLoadException",
  "stackTrace": "   at Microsoft.Bot.Connector.BotAuthentication.<OnAuthorizationAsync>d__16.MoveNext()\r\n   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)\r\n   at Microsoft.Bot.Connector.BotAuthentication.OnAuthorizationAsync(HttpActionContext actionContext, CancellationToken cancellationToken)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"
}

**Comment by msimecek** [comment]
Make sure you have the right Jwt package (**4.0.2.206221351**): 
`<package id="System.IdentityModel.Tokens.Jwt" version="4.0.2.206221351" targetFramework="net46" />`

**Comment by lokijota** [comment]
I too am having this error exact same error, after updating to v3 of BotFramework. Some notes:

- I'm having this error in the "Test connection to your bot" window of https://dev.botframework.com;
- the reference in packages.config is as @msimecek says;
- the project doesn't refer to Bot.Connector.

Ideas?

**Comment by lokijota** [comment]
Eventually solved it, but the simplest way around is to create a new project and copy the code and settings.
