### ISSUE TITLE
Exceptions not reporting call stacks in Node SDK 3.01

### ISSUE THREAD

**Issue by elpollouk** [Microsoft/BotBuilder#704]
If an exception occurs in the bot code, all that'll logged is the exception message, e.g.:
ReferenceError: builder is not defined

That in itself is often not enough to track down the error. Would it be possible to log out the call stack as well please?

**Comment by danmarshall** [comment]
Can you share a code sample?

**Comment by danmarshall** [comment]
Thanks for the suggestion, it has been added to our backlog.
