### ISSUE TITLE
Markdown-Issues with Telegram

### ISSUE THREAD

**Issue by NanashiGIT** [Microsoft/BotBuilder#705]
Hello!
I've been trying to send unordered lists with markdown to a telegram client.
The problem is, that the message doesnt pop up at all, while it does work for skype.
I found a related topic on stackoverflow:
[Here](http://stackoverflow.com/questions/36551160/are-there-known-limitations-and-workarounds-for-botframework-messages-delivered)

Now i'm wondering whether thats an issue thats being resolved or whether its already fixed and im missing something?

Greetings

**Comment by eanders-MS** [comment]
Hi @NanashiGIT, What is the name of your bot? Can you paste an example of the markdown you're sending?

**Comment by NanashiGIT** [comment]
My Microsoft App Id is:
4998a523-b204-4f22-b137-37ba8e808e3a

My string is pretty much:
"Your team members are:\n\n* Member1 \n\n* Member2 \n\n* Member3"

All I want is an unordered list like:
Your team members are:
* Member1
* Member2
* Member3

Greetings

**Comment by eanders-MS** [comment]
Thanks for the info. I am still investigating your issue, but did happen to notice that typing activity is broken in Telegram and throwing an exception. I have a fix incoming for this. In the meantime you might try not sending typing activity.

**Comment by NanashiGIT** [comment]
Thanks for you looking into it. 

And yes, i noticed that Typing-Activity doesnt work on Telegram. But it also doesn't work for me on Skype. Maybe your fix applies to that aswell?

**Comment by eanders-MS** [comment]
There are two issues at play here. First, we have a bug in our markdown parser causing invalid markdown to be sent to Telegram. Telegram is very picky about markdown syntax and returns an error code. The second issue is the fact that we are not surfacing this error back to the bot. I will address these issues and let you know when a fix goes out.

**Comment by eanders-MS** [comment]
We've rolled out an updated Telegram channel that includes:
- Fixed typing activity message
- Telegram failure reporting to developer's App Insights key.

Can you give another try?

**Comment by NanashiGIT** [comment]
Typing works now.
I dont have a connected Azure Insight thingy, if thats what you mean and cant check that.

Thanks for the quick fix of the typing activity.

**Comment by eanders-MS** [comment]
Yes meant Azure Insights, sorry.

I didn't get a chance to uncover the root issue of the markdown unordered list failure. It was working in our test environment when I attempted to repro there (likely another dev encountered it and made a fix in the meantime). It is working for me now in prod. Is it working for you?

**Comment by NanashiGIT** [comment]
I'll try in a second.

Btw have you changed something different in the telegram channel that might have something to do with my new issue: 
[https://github.com/Microsoft/BotBuilder/issues/769](https://github.com/Microsoft/BotBuilder/issues/769) ?

Greetings

**Comment by NanashiGIT** [comment]
Oh. The unordered list works now.
Thanks for your quick help.
