### ISSUE TITLE
ERROR ChatConnector: receive - invalid token. Check bots app ID & Password

### ISSUE THREAD

**Issue by 0GiS0** [Microsoft/BotBuilder#706]
Hi folks,

I've created a new bot from scratch. I did the registration and I get my app Id and my password ID. It doesn't work with ChatConnector, I get this error all the time:

![ms bot fw - error](https://cloud.githubusercontent.com/assets/175379/16873241/2d6b74a6-4a92-11e6-938e-5fb8cea07770.png)

I re-generated the password but I get the same error.

**Comment by brene** [comment]
I have this problem as well. I don't know why but constantly changing the "s=APP_SECRET" in the iframe to "t=APP_SECRET" back and forth, fixes this problem temporarily.

**Comment by 0GiS0** [comment]
It seems like it loses the connection and it needs to restart the server....

**Comment by dandriscoll** [comment]
3.1.1 contains fixes that should address this. Please let us know if you see this after updating to that package.
