### ISSUE TITLE
Accessing Activity with LUIS to save state

### ISSUE THREAD

**Issue by jamesrlewis** [Microsoft/BotBuilder#707]
I'm using C# and integrating the LuisDialog class. Within my implementation, I need to save the state of a  boolean property indicating the user has provided credentials. This boolean needs to be preserved throughout the entire conversation so that the user only needs to login once and then be remembered for the duration of the session. 

I'm not sure how to access the Activity from this example intent:
`[LuisIntent("ChangeBilling")]
        public async Task ChangeBilling(IDialogContext context, LuisResult result)
        {
            //check if login boolean is true/false
            //if not, call Authenticate class and set boolean value to true
        }` 

Any ideas?

**Comment by msft-shahins** [comment]
You have 3 different bot data stores available off of [IDialogContext](https://docs.botframework.com/en-us/csharp/builder/sdkreference/db/d9b/interface_microsoft_1_1_bot_1_1_builder_1_1_dialogs_1_1_internals_1_1_i_bot_data.html). You can keep the boolean value in the user data bag.

**Comment by garypretty** [comment]
+1 for this.  I have a similar requirement and I am storing a value in the ConversationData bag.
The 3 bags you have are;

- **User Data** - data about the user that is available across all channels and conversations
- **Private Conversation Data** - data about the user that is specific to that specific conversation
- **Conversation Data** - data associated with a conversation (could be applicable to multiple users. i.e. group conversation)

To add a value to the data bag you can call something like;

`context.UserData.SetValue("IsUserAuthenticated", yourbooleanvalue);`

Hope that helps.

**Comment by kienct89** [comment]
I want to implement OAUTH authorization flow using **ResumptionCookie** inside **LuisDialog**
Therefore, I need to be able to access the origin activity

Any idea?
Thanks.

**Comment by jamesrlewis** [comment]
Thanks for the responses! @garypretty  your example was very helpful and worked like a charm.
