### ISSUE TITLE
Moving into another dialog from inside a dialog?

### ISSUE THREAD

**Issue by epitone** [Microsoft/BotBuilder#709]
So what I have here are a series of if-statements (depending on the user's input) - once a user enters a specific block, I know that they've satisfied certain conditions - and I would like to forward them to another dialog to continue the conversation, but I cannot figure out how to do that? The documentation isn't really clear to me (perhaps I'm just not well-versed in C#) and I've been stuck on this for a few days.

Once the user enters the "validSeller" if block, I want to forwrad to another part of the conversation. Right now I have "context.Wait(GetAppNameFromUser)" in that block but every time I try to reach this code, the bot throws a 500 error.

My code is as follows:

```
        public virtual async Task MessageReceivedAsync(IDialogContext context, IAwaitable<IMessageActivity> argument)
        {
            var message = await argument;
            //check if input string is entirely numeric (used to find out if this is a publisher ID or not)
            var isNumeric = Regex.IsMatch(message.Text, @"^\d+$");
            string botResponse;
            //If user said "hi" or "hello"
            if(message.Text.StartsWith("Hi", StringComparison.OrdinalIgnoreCase) || message.Text.StartsWith("Hello", StringComparison.OrdinalIgnoreCase)) {
                await context.PostAsync("Hi! I'm your Assistant. What can I help you with today?");
            }
            //If user's message is entirely digits, it's most likely an ID, check it and then continue
            else if(isNumeric)
            {
                bool validSeller = await Utils.ValidateSellerId(message.Text);
                //if valid seller ID, continue to conversation, otherwise, user must input valid ID
                if(validSeller)
                {
                    //TODO: Figure out how to pass appID in context variable, for now just use class variable
                    sellerID = message.Text;
                    context.Wait(GetAppNameFromUser);
                    //TODO: figure out how to pass apps list to the user with the context
                    //context.Wait(MessageReceivedAsync);
                }
                //if invalid, loop back around and ask the user for a proper ID
                //TODO: keep track of how many times the bot has failed
                else
                {
                    await context.PostAsync("Sorry! Looks like you entered an invalid ID. Could you try again?");
                }
            }
            else
            {
                //Queries LUIS for which intent the user's message matches.
                InitialIntentLUIS initialIntent = await InitialIntentLUIS.GetIntentMatchFromLUIS(message.Text);
                var initialIntentGuess = initialIntent.intents[0].intent;
                //Begin routing to different intent conversations
                if (initialIntentGuess == "Help")
                {
                    await context.PostAsync("Here are the things I'm capable of doing: \n\n• Help you find missing apps in the store \n\n • Forward you to a support representative");
                }
                else if(initialIntentGuess == "AppNotFound")
                {
                    //TODO: If the user has given an appName already, store it somewhere
                    await context.PostAsync("Looks like you're trying to find an app. To help faciltiate this, can I get your Publisher ID?");
                }
                //Otherwise, something broke, alert the user and kick out.
                else
                {
                    botResponse = "Uh-oh, looks like my wires got crossed.  Sorry! I've filed a bug and someone will check things out shortly!";
                    await context.PostAsync(botResponse);
                }
            }
            //return back to the top of the dialog
            context.Wait(MessageReceivedAsync);
        }
public virtual async Task GetAppNameAsync(IDialogContext context, IAwaitable<IMessageActivity> argument)
        {
            await context.PostAsync("Great! What are you looking for exactly?");
            var userMessage = await argument;
            AppRecognitionLUIS appNameEntities = await AppRecognitionLUIS.GetAppRecognitionEntityFromLUIS(userMessage.Text);
            if (appNameEntities.entities.Length > 1)
            {
                await context.PostAsync("Checking if valid name given");
            }
        }
```

**Comment by msft-shahins** [comment]
You can use [Context.Call(...)](https://docs.botframework.com/en-us/csharp/builder/sdkreference/de/db4/interface_microsoft_1_1_bot_1_1_builder_1_1_dialogs_1_1_internals_1_1_i_dialog_stack.html#a49c6523645f574c7712e5155fb3b4973) and [Context.Froward(...)](https://docs.botframework.com/en-us/csharp/builder/sdkreference/de/db4/interface_microsoft_1_1_bot_1_1_builder_1_1_dialogs_1_1_internals_1_1_i_dialog_stack.html#ac4a3046691345fd43e183a99ff7372f5) to create child dialogs from root Dialog and then use [Context.Done(...)](https://docs.botframework.com/en-us/csharp/builder/sdkreference/de/db4/interface_microsoft_1_1_bot_1_1_builder_1_1_dialogs_1_1_internals_1_1_i_dialog_stack.html#ac925ad5a83a7d931925c575d31eb9575) to return the result from child dialog to root dialog. You can also leverage the [system prompts](https://docs.botframework.com/en-us/csharp/builder/sdkreference/d9/d03/class_microsoft_1_1_bot_1_1_builder_1_1_dialogs_1_1_prompt_dialog.html) if you want to ask questions from user and have system prompts return the validated results.

Here are some examples: 
- [Context.Call(...) into form dialog](https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Samples/PizzaBot/PizzaOrderDialog.cs#L61)
- [Context.Done(...) to return result](https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Dialogs/PromptDialog.cs#L647)

**Comment by epitone** [comment]
I'm attempting to use the system prompts, and getting consistent errors - the bot responds with a 500 Error, and in my Output window, I seem to be getting:

```
Exception thrown: 'Microsoft.Bot.Builder.Internals.Fibers.InvalidNeedException' in Microsoft.Bot.Builder.dll
Exception thrown: 'Microsoft.Bot.Builder.Internals.Fibers.InvalidNeedException' in mscorlib.dll
Exception thrown: 'Microsoft.Bot.Builder.Internals.Fibers.InvalidNeedException' in mscorlib.dll
```
This isn't really telling me anything and I'm not sure what to do about it.

**Comment by epitone** [comment]
I managed to fix it somehow by stepping away from my computer - I think I misnamed a method or something somewhere, it works now! I'm going to go ahead and close this myself.
