### ISSUE TITLE
[v3] [Node] Prompts.choice and Prompts.confirm writing more text than wanted

### ISSUE THREAD

**Issue by dudeofawesome** [Microsoft/BotBuilder#711]
It appears that since the v3 update, the way that a choice gets rendered to Facebook Messenger has changed.
```typescript
Prompts.choice(session, `How would you describe your gender?`, ['Male', 'Female']);
```
The above snippet used to output this:
![image](https://cloud.githubusercontent.com/assets/1683595/16886359/a47752d6-4a88-11e6-9e1f-99b693f595c0.png)
<img src="https://cloud.githubusercontent.com/assets/1683595/16887149/3a95d3ce-4a8d-11e6-98d6-fc93abf6c0a4.png" width="320px" />

But now, it outputs this:
![image](https://cloud.githubusercontent.com/assets/1683595/16886381/c60a948a-4a88-11e6-80a5-8859abf61255.png)
<img src="https://cloud.githubusercontent.com/assets/1683595/16887157/4100e906-4a8d-11e6-8c6c-183a7b89a00d.png" width="310px" />

Is there any way to remove the "options" message, and just have the question and the buttons?

**Comment by Stevenic** [comment]
Adding Tom. Think this may have gotten introduced with a recent change.

**Comment by tomlm** [comment]
This has been fixed.
