### ISSUE TITLE
LUIS date response "2016-W29" can not be resolved

### ISSUE THREAD

**Issue by pke** [Microsoft/BotBuilder#712]
The following LUIS response entity `next week` cannot be resolved
```
{
  "query": "next week",
  "intents": [
    {
      "intent": "showMenu",
      "score": 0.9952397
    },
    {
      "intent": "None",
      "score": 0.0144623639
    },
    {
      "intent": "orderMenu",
      "score": 0.00063242513
    },
    {
      "intent": "getBalance",
      "score": 2.645871E-06
    }
  ],
  "entities": [
    {
      "entity": "next week",
      "type": "builtin.datetime.date",
      "startIndex": 0,
      "endIndex": 8,
      "resolution": {
        "date": "2016-W29"
      }
    }
  ]
}
```

calling:
`builder.EntityRecognizer.resolveTime(entities)` on it returns `undefined`.
Shouldn't the returned `resolution` be `chrono.duration` anyway?

And resolveTime should return the `startTime` and `endTime` of the specified week.

**Comment by garypretty** [comment]
I have never found that week numbers automatically resolve, although agree that it would make sense for them to. I have been parsing them myself so I will be interested to know if this is something that will come.

**Comment by pke** [comment]
Well I just assumed the `EntityRecognizer` could handle everything LUIS throws out :) `momentjs` can handle this.

**Comment by Stevenic** [comment]
We have a bug we're already tracking to re-work all of the entity recognizer resolving logic. I may look into just adopting moments.js for a lot of this stuff.

**Comment by pke** [comment]
That's what I am doing at the moment. Using `momenjs`.

**Comment by Stevenic** [comment]
@pke do they have functions to resolve the various ISO placeholders like "2016-W29"?
