### ISSUE TITLE
Telegram bot doesnt seem to be working properly since v3

### ISSUE THREAD

**Issue by Orbyt** [Microsoft/BotBuilder#713]
Recently upgraded to v3 and redeployed to telegram. When starting a new converstation, I get the following in bold:

"**Sorry, MyBot is forbidden for us to talk to.**"

I did not find any information on this error from Telegram, and since i've only seen this happen since upgrading to v3 I would assume the issue is something on BotBuilder's end. Has anyone seen this error?

**Edit:** Seems to be related: https://github.com/Microsoft/BotBuilder/issues/618#issuecomment-231798914

**Comment by eanders-MS** [comment]
Hi @Orbyt, this error message is returned when the connector tries to send your bot a message, and your bot service returns a 401 (Unauthorized) or a 403 (Forbidden). This could happen for a number of reasons. We are requiring https endpoints now. Is your bot using http by chance?

**Comment by Orbyt** [comment]
@eanders-MS No, the messaging endpoint is https. What else could cause this error?

Also note, the bot seems to work fine on both the emulator and Facebook Messenger.

**Comment by dandriscoll** [comment]
We're tracing down some issues in the auth validation path.

Is your bot written in C#, Node.js, or another language?

**Comment by Orbyt** [comment]
@dandriscoll Node.js

**Comment by pietie** [comment]
I also get this with my Node.js bot(v3). It actually works fine for a bit and will just hit 403s all of a sudden. When I then resubmit the *same* auth key it works again for a bit.
My bot is running on https on an Azure free account.

**Comment by alisiikh** [comment]
Same issue for me with Telegram running on v3. Appears randomly, and normally everything works. The rate is about 10% or so.

**Comment by eanders-MS** [comment]
We're still working to track down intermittent auth issues. We've added additional instrumentation to the Telegram channel. Are you still seeing the problem there?

**Comment by danmarshall** [comment]
@Orbyt @pietie @alisiikh We've recently made some updates, do you still see the issue?

**Comment by alisiikh** [comment]
@danmarshall nope, works good for me, thanks a lot for your work! :+1:
