### ISSUE TITLE
Method not found HttpOperationException setter

### ISSUE THREAD

**Issue by nzthiago** [Microsoft/BotBuilder#714]
I'm updating the AzureBot to V3 (this branch in my AzureBot fork https://github.com/nzthiago/azurebot/tree/botbuilderV3). 

When I run it locally and with the emulator v3 I'm getting the following error and stack trace. Any ideas? It could be related to the nuget packages/dlls I ended up with after updating the Azure packages...

> System.MissingMethodException occurred
>   HResult=-2146233069
>   Message=Method not found: 'Void Microsoft.Rest.HttpOperationException.set_Request(System.Net.Http.HttpRequestMessage)'.
>   Source=Microsoft.Bot.Connector
>   StackTrace:
>        at Microsoft.Bot.Connector.BotState.<GetConversationDataWithHttpMessagesAsync>d__8.MoveNext()
>        at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
>        at Microsoft.Bot.Connector.BotState.GetConversationDataWithHttpMessagesAsync(String channelId, String conversationId, Dictionary`2 customHeaders, CancellationToken cancellationToken)
>        at Microsoft.Bot.Connector.BotStateExtensions.<GetConversationDataAsync>d__7.MoveNext()
>     --- End of stack trace from previous location where exception was thrown ---
>        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>        at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>        at Microsoft.Bot.Builder.Dialogs.Internals.ConnectorStore.<Microsoft-Bot-Builder-Dialogs-Internals-IBotDataStore<Microsoft-Bot-Connector-BotData>-LoadAsync>d__2.MoveNext()
>     --- End of stack trace from previous location where exception was thrown ---
>        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>        at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>        at Microsoft.Bot.Builder.Dialogs.Internals.CachingBotDataStore_LastWriteWins.<Microsoft-Bot-Builder-Dialogs-Internals-IBotDataStore<System-Object>-LoadAsync>d__5.MoveNext()
>     --- End of stack trace from previous location where exception was thrown ---
>        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>        at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>        at Microsoft.Bot.Builder.Dialogs.Internals.BotDataBase`1.<LoadData>d__16.MoveNext()
>     --- End of stack trace from previous location where exception was thrown ---
>        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>        at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>        at Microsoft.Bot.Builder.Dialogs.Internals.BotDataBase`1.<LoadAsync>d__8.MoveNext()
>     --- End of stack trace from previous location where exception was thrown ---
>        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>        at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>        at Microsoft.Bot.Builder.Dialogs.Internals.PersistentDialogTask.<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d__6`1.MoveNext()
>     --- End of stack trace from previous location where exception was thrown ---
>        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>        at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>        at Microsoft.Bot.Builder.Dialogs.Conversation.<SendAsync>d__4.MoveNext()
>     --- End of stack trace from previous location where exception was thrown ---
>        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>        at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>        at Microsoft.Bot.Builder.Dialogs.Conversation.<SendAsync>d__2.MoveNext()
>     --- End of stack trace from previous location where exception was thrown ---
>        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>        at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>        at AzureBot.MessagesController.<Post>d__0.MoveNext() in C:\code\AzureBot\AzureBot\Controllers\MessagesController.cs:line 27
>   InnerException: 
>

**Comment by nzthiago** [comment]
duplicate

**Comment by rzmoz** [comment]
+1
