### ISSUE TITLE
Method not found HttpOperationException setter

### ISSUE THREAD

**Issue by nzthiago** [Microsoft/BotBuilder#715]
I'm updating the AzureBot to V3 (this branch in my AzureBot fork https://github.com/nzthiago/azurebot/tree/botbuilderV3). 

When I run it locally and with the emulator v3 I'm getting the following error and stack trace. Any ideas? It could be related to the nuget packages/dlls I ended up with after updating the Azure packages...

> System.MissingMethodException occurred
>   HResult=-2146233069
>   Message=Method not found: 'Void Microsoft.Rest.HttpOperationException.set_Request(System.Net.Http.HttpRequestMessage)'.
>   Source=Microsoft.Bot.Connector
>   StackTrace:
>        at Microsoft.Bot.Connector.BotState.\<GetConversationDataWithHttpMessagesAsync\>d__8.MoveNext()
>        at System.Runtime.CompilerServices.AsyncTaskMethodBuilder\`1.Start\[TStateMachine\](TStateMachine& stateMachine)
>        at Microsoft.Bot.Connector.BotState.GetConversationDataWithHttpMessagesAsync(String channelId, String conversationId, Dictionary\`2 customHeaders, CancellationToken cancellationToken)
>        at Microsoft.Bot.Connector.BotStateExtensions.\<GetConversationDataAsync\>d__7.MoveNext()
>     --- End of stack trace from previous location where exception was thrown ---
>        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>        at System.Runtime.CompilerServices.TaskAwaiter\`1.GetResult()
>        at Microsoft.Bot.Builder.Dialogs.Internals.ConnectorStore.\<Microsoft-Bot-Builder-Dialogs-Internals-IBotDataStore\<Microsoft-Bot-Connector-BotData\>-LoadAsync\>d__2.MoveNext()
>     --- End of stack trace from previous location where exception was thrown ---
>        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>        at System.Runtime.CompilerServices.TaskAwaiter\`1.GetResult()
>        at Microsoft.Bot.Builder.Dialogs.Internals.CachingBotDataStore_LastWriteWins.\<Microsoft-Bot-Builder-Dialogs-Internals-IBotDataStore\<System-Object\>-LoadAsync\>d__5.MoveNext()
>     --- End of stack trace from previous location where exception was thrown ---
>        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>        at System.Runtime.CompilerServices.TaskAwaiter\`1.GetResult()
>        at Microsoft.Bot.Builder.Dialogs.Internals.BotDataBase\`1.\<LoadData\>d__16.MoveNext()
>     --- End of stack trace from previous location where exception was thrown ---
>        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>        at System.Runtime.CompilerServices.TaskAwaiter\`1.GetResult()
>        at Microsoft.Bot.Builder.Dialogs.Internals.BotDataBase\`1.\<LoadAsync\>d__8.MoveNext()
>     --- End of stack trace from previous location where exception was thrown ---
>        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>        at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>        at Microsoft.Bot.Builder.Dialogs.Internals.PersistentDialogTask.\<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync\>d__6\`1.MoveNext()
>     --- End of stack trace from previous location where exception was thrown ---
>        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>        at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>        at Microsoft.Bot.Builder.Dialogs.Conversation.\<SendAsync\>d__4.MoveNext()
>     --- End of stack trace from previous location where exception was thrown ---
>        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>        at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>        at Microsoft.Bot.Builder.Dialogs.Conversation.\<SendAsync\>d__2.MoveNext()
>     --- End of stack trace from previous location where exception was thrown ---
>        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>        at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>        at AzureBot.MessagesController.\<Post\>d__0.MoveNext() in C:\code\AzureBot\AzureBot\Controllers\MessagesController.cs:line 27
>   InnerException: 
>

**Comment by nzthiago** [comment]
I believe this is a conflict between Microsoft.Rest.ClientRuntime version 1.8.2 needed by the Bot Framework, and Microsoft.Rest.ClientRuntime > 2.0.0 needed by Microsoft.Azure.Management.ResourceManager via Microsoft.Rest.ClientRuntime.Azure that I'm using on another project which I reference from my bot project.

**Comment by nzthiago** [comment]
Yes, confirmed. It was the same problem as we had before. The dependency the bot framework has on Microsoft.Rest.ClientRuntime version 1.8.2 is stopping us from using the latest non-deprecated version of the Azure nuget packages. 
Can link this issue to the previous one we raised: #208

**Comment by nzthiago** [comment]
#208

**Comment by danmarshall** [comment]
Hi @nzthiago Thiago, is this issue resolved?

**Comment by msft-shahins** [comment]
Bot Builder is dependent on Microsoft.Rest.ClientRuntime 1.8.2 and that is the main cause of the exception that you are seeing because of the breaking change in Rest.ClientRuntime. We are looking into upgrading the builder dependencies to depend on the lastest Rest.ClirentRuntime.

**Comment by nzthiago** [comment]
Thanks @msft-shahins  - I only tried again as Dan asked, I thought maybe this had been fixed with Bot Builder 3.1.0 that has come out a couple of days ago. No problem, will keep an eye out for the update that fixes the dependency on 1.8.2

**Comment by msft-shahins** [comment]
Closing this since it is going to be resolved in the next release of the builder. This [commit](https://github.com/Microsoft/BotBuilder/commit/3017675bbb27c6060503eec2068bc4c1cbfdd707) have all the changes upgrading Rest.ClientRuntime to 2.3.2.
