### ISSUE TITLE
Microsoft Bot Framework : SigninCard not showing in telegram

### ISSUE THREAD

**Issue by Varooneh** [Microsoft/BotBuilder#718]
I tried create Telegram bot client with Microsoft Bot Framework, when I create signincard with this framework, signincard created successfully and I can see buttons in Microsoft Bot Emulator but when I publish to server and test it with Telegram, signincard not showing in bot, please tell me how to fix it.

code :

`
Activity reply = null;
            ConnectorClient connector = new ConnectorClient(new Uri(activity.ServiceUrl), "", "");

            if (activity.Type == ActivityTypes.Message)
            {                    
                if (activity.Text == "/start")
                {
                    reply = activity.CreateReply($"Welcome, please select an option");
                    reply.Recipient = activity.From;
                    reply.Type = ActivityTypes.Message;
                    reply.Attachments = new List<Attachment>();

                    List<CardAction> cardButtons = new List<CardAction>();
                    var helpAction = new CardAction()
                    {
                        Image = "",
                        Title = "Get Menu",
                        Type = "imBack",
                        Value = "help"
                    };

                    var contactAction = new CardAction()
                    {
                        Image = "",
                        Title = "Contact Us",
                        Type = "imBack",
                        Value = "contact"
                    };
                    cardButtons.Add(helpAction);
                    cardButtons.Add(contactAction);

                    var sc = new SigninCard()
                    {
                        Buttons = cardButtons,
                        Text = ""
                    };

                    Attachment attach = sc.ToAttachment();
                    reply.Attachments.Add(attach);
                }
                else
                {

                }
            }
            await connector.Conversations.ReplyToActivityAsync(reply);
`

sorry for bad english

**Comment by eanders-MS** [comment]
Apologies for the slow response. Are you still experiencing this issue?

**Comment by Varooneh** [comment]
Your're welcome @eanders-MS , yes, but I fixed this issue with this approach :

`
replyActivity.Attachments = new List<Attachment>();

var cardButtons = new List<CardAction>();
var plButton = new CardAction
{
    Value = auth.SessionUrl,
    Type = "signin",
    Title = "Connect"
};
cardButtons.Add(plButton);
var plCard = new SigninCard("You need to authorize to use Quick Book feature", cardButtons);

var plAttachment = plCard.ToAttachment();
replyActivity.Attachments.Add(plAttachment);
replyActivity.Text = "Should go to conversation, sign-in card";
`
[http://i.stack.imgur.com/Ys4Lg.png](url)

but I've error from my code.

help link : [http://stackoverflow.com/questions/38409461/microsoft-bot-framework-signincard-not-showing-in-telegram](url)

**Comment by eanders-MS** [comment]
Ok, great. From the screenshot it appears the SigninCard is working for you now, so I will go ahead and close this issue. If you're still having a problem, please comment here and I will reopen it.

**Comment by Varooneh** [comment]
Ok, Thank you @eanders-MS
