### ISSUE TITLE
Add User-Agent HTTP header when communicating from channel to bot

### ISSUE THREAD

**Issue by kenrick95** [Microsoft/BotBuilder#719]
There are times where User-Agent is useful for debug at the bot server side (to determine which client channel is buggy or spammy). There are other times when it is required to do so, one example is on [Wikimedia servers](https://meta.wikimedia.org/wiki/User-Agent_policy)

In my case, I'm trying to deploy a Node.js-based bot using BotBuilder to [WMF's Tool Labs](https://wikitech.wikimedia.org/wiki/Help:Tool_Labs/Web), but the messages sent to the bot (be it from "Test connection to your bot" at the MS Bot Framework page, the MS Bot Framework Channel Emulator, or from the Channel itself) are denied by the server since WMF have a User-Agent policy enforced here. (i.e. 403 Forbidden, "Requests must have a user agent" are returned from the bot server)

My suggestion is to add a User-Agent when sending a HTTP request from the channels to the bot. I hope that this place is the right channel to give this suggestion. Thanks.

**Comment by dandriscoll** [comment]
Interesting suggestion; we'll look into it. Do you know of any other servers requiring User-Agent strings beyond WMF?

**Comment by kenrick95** [comment]
A quick web search shows that there are few other companies requiring User-Agent header to access their API (e.g. [Jumio](https://www.jumio.com/2013/10/mandatory-user-agent-latest-release-notes/), [GitHub](https://developer.github.com/changes/2013-04-24-user-agent-required/)), but I can't find any other companies that allows hosting stuff on their server requiring this policy beyond WMF.

**Comment by Andrea-Orimoto** [comment]
Thanks for the suggestion, we've added it to our backlog.
