### ISSUE TITLE
TryParse method in PromptConfirm class does not ignore casing

### ISSUE THREAD

**Issue by pagebrooks** [Microsoft/BotBuilder#72]
When replying to a PromptConfirm, the logic does not properly interpret answers that are not lowercased.  It is common for smart phones to "autocorrect" response casing so the bug is quite noticeable when interacting with a bot through a smartphone. PR #71

**Comment by msft-shahins** [comment]
Merged your pull request. Commit [a00b8](https://github.com/Microsoft/BotBuilder/commit/a00b8ce3632bd308f6126b441d6cb6ab674fbe27) will have your fix.
