### ISSUE TITLE
Intermittent Check bots app ID & Password message with skype 

### ISSUE THREAD

**Issue by alexsorokoletov** [Microsoft/BotBuilder#722]
For some reason today when debugging bot locally and using skype I see intermittent messages
`ERROR: ChatConnector: receive - invalid token. Check bots app ID & Password.`

During same debug session (bot runs and I test the script) I see the message in the logs sometimes. 
In the same dialog answering same question (basically simple dialog with one function) sometimes fails and sometimes works. 
Went to the source code and looks like check for `now < decoded.payload.nbf` doesn’t work.
<img width="1016" alt="screenshot 2016-07-16 17 16 23" src="https://cloud.githubusercontent.com/assets/1788581/16897255/988cdb70-4b79-11e6-97be-42e395e0e9ad.png">

Wondering is it related to the floating part of the `now` variable?

I'm using Node.js SDK v3.0.1

**Comment by dandriscoll** [comment]
Yes, that's probably it. Thank you for noting that. We're seeing validation errors in other places but this is definitely a problem.

**Comment by arieschwartzman** [comment]
Same here. It happens on some machines, maybe to do with how internal clocks are synced across local and cloud machines?

**Comment by alexsorokoletov** [comment]
Looks like, hope the fix is easy. So far for workaround I'm counting to 10 before sending reply when testing. But this will not work for customers in production.

**Comment by jesiah-hackinglife** [comment]
Will this be a repository level fix, or a system fix on the microsoft side?

**Comment by dandriscoll** [comment]
This will be a set of fixes to the SDK.

**Comment by dandriscoll** [comment]
Hi @alexsorokoletov , @arieschwartzman , and @jesiah-hackinglife , the latest Node release, 3.1.1, has a fix for this bug.

**Comment by ejadib** [comment]
@dandriscoll @Stevenic Please note that is issue is also happening on the [CallConnector](https://github.com/Microsoft/BotBuilder/blob/master/Node/calling/src/bots/CallConnector.ts#L200-L201)
