### ISSUE TITLE
401 when using Start without Debugging

### ISSUE THREAD

**Issue by chocvanstraw** [Microsoft/BotBuilder#723]
I recently started using V3.  If I run the bot web api locally using Start without Debugging in VS 2015 I get a 401 error as I have the MicrosoftAppId and MicrosoftAppPassword empty.  if I run the bot web api locally in Debug it works fine.  This wasn't an issue with V1.  Is this by design?

**Comment by dandriscoll** [comment]
Yes, this is by design. Auth is only disabled when your app ID is empty AND a debugger is attached.

**Comment by garypretty** [comment]
This does appear to be by design.  The BotAuthentication class in the connector checks to see if the Debugger is attached AND if the MicrosoftAppId is empty.  If both are true then it will skip authentication.  However, as you are starting without debugging, it is trying to authenticate.

**Comment by garypretty** [comment]
@dandriscoll beat me to it!

**Comment by garypretty** [comment]
@chocvanstraw best thing to do here if you want to run without the debugger attached is to register your bot in the dev portal.  You don't need to provide a messages endpoint as you haven't published, but you will be able to get an App Id and Password to use in your config.

**Comment by chocvanstraw** [comment]
10-4!  Thanks for the quick replies
