### ISSUE TITLE
Dynamic fields odd behavior in V3 Channel Emulator

### ISSUE THREAD

**Issue by chocvanstraw** [Microsoft/BotBuilder#724]
In V1 dynamic fields generated using FieldReflector displayed the list of items as a nice ordered list and the item text supported markdown in the Bot Emulator.  After upgrading to V3 framework and the V3 channel emulator the items appear in the emulator with no numbers and the item text appears inside a box.  Markdown isn't rendered at all.  If I click the box it will select the item.  Also, if I happen to know the item's number in the list it will select it as well but this isn't ideal.

**Comment by garypretty** [comment]
I believe the behavior you are seeing in the emulator is the prompt being represented as buttons.  Try clicking on one of the items to choose it in the emulator.  This method of presenting the user a series of buttons is supported on some channels, such as Slack, and it is what you see in the emulator if you use a simple prompt dialog.

On channels where buttons are not supported, I believe you should still see the plain text lists being output.

**Comment by chocvanstraw** [comment]
So the v3 emulator defaults to buttons for dynamic fields whereas v1 defaulted to an ordered list?  When I added my v1 bot to slack it displayed as the ordered list rather than the buttons.  I also noticed that the text in the buttons is center aligned and gets truncated if it's too long rather than wrapping as the v1 ordered list did.  Thanks

**Comment by chocvanstraw** [comment]
Is there a way to get dynamic fields created using FieldReflector<T> to render the results as an ordered list as they did in V1?  In V3 these fields are rendered as buttons or hero cards, which truncates the text making it difficult to know what the possible values are.  thanks!

**Comment by msft-shahins** [comment]
you can change the ChoiceStyle of the form to ChoiceStyleOptions.AutoText and FormBuilder will generate text lists instead of buttons. Here is an example on how to set it: https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Samples/AnnotatedSandwichBot/AnnotatedSandwich.cs#L340
