### ISSUE TITLE
Skype call bot calling webhook does not support query string parameters

### ISSUE THREAD

**Issue by mghimp** [Microsoft/BotBuilder#725]
I wish to be able to append query parameters to Skype Bot Calling webhook URL and to have these parameters deserialized in IncomingCallEvent. This will allow me to create a stateless bot and to control its functionality by configuration from Call URL.

I was able to workaround this with Skype Bot SDK but it seems impossible to workaround with Bot Framwork SDK v3, so since Skype Bot SDK is phasing out, I would like to have the support I requested.

I also posted this on [botfamework feedback site](https://feedback.botframework.com/forums/354222-bot-builder-sdk/suggestions/15184149-support-skype-call-url-query-parameters).

I already have the fix for this issue ready waiting to be submitted as PR. Please approve this issue to get the PR, as requested by [contribution terms](https://github.com/Microsoft/BotBuilder/blob/master/Contributing.md#contributing-bug-fixes-and-features).

**Comment by mghimp** [comment]
Created Pull Request https://github.com/Microsoft/BotBuilder/pull/764

**Comment by mayuanyang** [comment]
@mghimp , did you manage to get Skype Bot Calling to send request to your bot? i got my bot setup with the new api controller named CallingController with the following medhot

[Route("call")]
        public async Task<HttpResponseMessage> ProcessIncomingCallAsync()

I set the followings as the Calling Webhook, however they never get hit when i am making the call, any thought?
https://eddybot.azurewebsites.net/api/calling
https://eddybot.azurewebsites.net/api/calling/call

**Comment by mghimp** [comment]
@mayuanyang , there might be several issues:
1. The webhook should be 'https://eddybot.azurewebsites.net/api/calling/call'. In respect to the fact that you don't see it hit, I assume that you verified the web server traffic log.
2. In regards to Controller, My controller is `public class CallingController : ApiController`, i.e. derives from System.Web.Http.ApiController. In addition, the method signature is `public async Task<HttpResponseMessage> ProcessIncomingCallAsync()`.

I suggest to debug using ngrok and run your bot locally. This will make the debugging easier. In addition, you can use this [tutorial](https://docs.botframework.com/en-us/csharp/builder/sdkreference/calling.html#tutorialivr) to get started.

**Comment by mayuanyang** [comment]
@mghimp i am actually doing exactly the same thing, in fact the code is copied from the bot framework simpleIVRSample project, will try ngrok to debug and see how it goes, thanks

**Comment by Andrea-Orimoto** [comment]
@mayuanyang I see that @msft-shahins has replied to your CR, I'm closing this issue. Thanks!

**Comment by mghimp** [comment]
Please reopen the issue as it has not been resolved. I opened this issue and my PR #764 is still pending.

**Comment by msft-shahins** [comment]
@mghimp I commented on the PR. We can continue talking about this in the PR comment section.
