### ISSUE TITLE
Send message on V3 returns internal error 500

### ISSUE THREAD

**Issue by lmessinger** [Microsoft/BotBuilder#726]
I need to send a message, but i dont want to use a dialog

Here's what I do:

 var bot = new builder.UniversalBot(connector);
       var msg = new builder.Message();
       msg.address = address; //from = ses.message.to;
       msg.text = message;
       msg.textLocale("en");

       bot.send([msg],function (err) {

         //.... and here I get 500 error
       })

* The incoming message is received from a session (bot.use({botbuilder: function (session, next) ...)
* I'm using the address of the incoming message for the address of the message

any ideas what's going on?

thank you VERY much
Lior

**Comment by tomlm** [comment]
does it work in the emulator?

**Comment by lmessinger** [comment]
I'm not using the emulator... does the sequence look right?

**Comment by Varooneh** [comment]
@tomlm I've error 500 on 3.0.1 version

**Comment by danmarshall** [comment]
I'm going to close this issue for now, but feel free to open a new issue for further discussion.
