### ISSUE TITLE
Use direct line from web page

### ISSUE THREAD

**Issue by mayuanyang** [Microsoft/BotBuilder#727]
Hi
I got Direct Line  with secret key setup on my bot, add a new html page and use javascript to send requests, request token get generated fine, conversationId is also returned, post a message with the conversationId got http 204 which also looks good, but when i try to get the messages it always return a empty list, e.g. messages: [], any idea?

I am using V3, however i am not too sure if i need to use Microsoft.Bot.Connector.DirectLine nuget for my case, i am currently referencing it but not actually using it.

thanks

**Comment by dandriscoll** [comment]
Hi @mayuanyang, sorry to hear you're having trouble. You're following the correct approach for posting messages to the DirectLine channel and then getting them. You are not required to use the Nuget package; you can call from either service code or Javascript (or any other code) and as long as you adhere to the HTTP Direct Line protocol, everything should work.

If you can send me a bot ID or conversation ID, I can take a look at the metadata to see whether messages were posted.

**Comment by Samurais** [comment]
hi, @dandriscoll,  I have made a directline api library for node.js.
https://www.npmjs.com/package/directline-api

But it is not friendly to use. It is a bit complicated, the POST API get nothing, and should write another method to retrieve and parse the messages in GET API. Is there any plan to enhance it? Such as just return the reply in POST API?

**Comment by mayuanyang** [comment]
Hi @dandriscoll 
The app Id is 1b3e574b-8aab-437c-a7d9-5f8b52469c02
I am using AngularJS 1.5 as the client, here are my client side code
`getRequestToken() {
     
        return this.$http.get('https://directline.botframework.com/api/tokens');
    }

    startConversation() {
        return this.$http.post('https://directline.botframework.com/api/conversations', '');
        
    }

    postMessage() {
        
        return this.$http({
            method: 'POST',
            url: 'https://directline.botframework.com/api/conversations/'+ this.conversationId + '/messages',
            
            data: { message: {
                "id": "string",
                "conversationId": this.conversationId,
                "created": "2016-07-17T11:02:01.374Z",
                "from": "test",
                "text": "get account for 46012345678",
                "channelData": {},
                "images": [],
                "attachments": [],
                "eTag": ""
            } }
        });
    }

    getMessages() {
        this.$http.get('https://directline.botframework.com/api/conversations/' + this.conversationId + '/messages')
            .success(data => {
                console.log(data);
            });

    }
`
and here is the server side code
`  public async Task Post([FromBody]Activity message)
        {
            try
            {

                var serviceUri = new Uri(message.ServiceUrl);
                var connector = new ConnectorClient(serviceUri);
                
                if (message.Type.ToUpper() == "MESSAGE")
                {
                    var msg = message.CreateReply("Message received");
                    await connector.Conversations.SendToConversationAsync(msg);

                    var luis = await _engine.ProcessMessage(message);

                    if (luis.intents[0].intent == "GetAccountInfo")
                    {
                        if (luis.entities.Length > 0)
                        {
                            
                            var account = _accRepository.SingleOrDefault(x => x.AccountId == luis.entities[0].entity);
                            msg.Attachments = new List<Attachment>();
                            msg.Attachments.Add(new Attachment("application/json", "", account));
                            await connector.Conversations.SendToConversationAsync(msg);
                           
                        }
                        else
                        {
                            await connector.Conversations.SendToConversationAsync(msg);
                        }
                        
                    }
                    if (luis.intents[0].intent == "GetPayments")
                    {
                        if (luis.entities.Length > 0)
                        {

                            //var stateClient = message.GetStateClient();
                            //var userData = await stateClient.BotState.GetUserDataAsync(message.ChannelId, message.From.Id);
                            //userData.SetProperty("Data", account);
                            //await stateClient.BotState.SetUserDataAsync(message.ChannelId, message.From.Id, userData);
                            var payments = _txRepository.Where(x => x.AccountId == luis.entities[0].entity).ToList();
                            msg =
                                message.CreateReply(
                                    $"The intent is {luis.intents[0].intent} and entity is {luis.entities[0].entity}");
                            msg.Attachments = new List<Attachment>();
                            msg.Attachments.Add(new Attachment("application/json", "", payments));

                            await connector.Conversations.SendToConversationAsync(msg);
                        }
                        else
                        {
                            msg = message.CreateReply("Transaction not found");
                            await connector.Conversations.SendToConversationAsync(msg);
                        }
                    }
                    if (luis.intents[0].intent == "AddPayment")
                    {
                        await connector.Conversations.SendToConversationAsync(message.CreateReply($"The intent is {luis.intents[0].intent} and entity is {luis.entities[0].entity}"));
                    }
                  
                }
                else
                {
                    await connector.Conversations.SendToConversationAsync(HandleSystemMessage(message));
                }
                
            }
            catch (Exception ex)
            {
                _logger.Error(ex, "An error has occured");
                //throw;
                
            }
        }
`

**Comment by mayuanyang** [comment]
The message contract from the document is a bit confused, i manage to get it working by just sending the "text" property in the post data
