### ISSUE TITLE
Node.js indicate bot is typing?

### ISSUE THREAD

**Issue by Orbyt** [Microsoft/BotBuilder#729]
With v3 I noticed that, at least in the C# version, there is a way to indicate the bot is "typing". I'm fairly certain its called a typing activity. I've gone through the node.js sdk and cant seem to find any kind of reference on something like this.

Is this functionality not yet in the Node.js SDK? If it is, how is it used?

**Comment by garypretty** [comment]
In case anybody hits this thread who isn't on the Gitter channel, it is worth noting that @Stevenic has indicated that from node the typing activity can currently be sent using **session.send({ type: 'typing' });**.  This may be replaced by a helper method at some stage.

**Comment by Orbyt** [comment]
I guess i'll close this for now. @Stevenic has indicated this functionality is not yet documented but will be soon. Thanks again.

**Comment by Stevenic** [comment]
I've already added a new `session.sendTyping()` method.  Will be in next release :)

**Comment by slidenerd** [comment]
To add to stevenic s point, this is what the method looks like
 Session.prototype.sendTyping = function () {
        this.msgSent = true;
        var m = { type: 'typing' };
        this.prepareMessage(m);
        this.batch.push(m);
        logger.info(this, 'session.sendTyping()');
        this.startBatch();
        return this;
    };

Notice the call to startBatch which has this line inside
this.batchTimer = setTimeout(function () {
                _this.sendBatch();
            }, this.options.autoBatchDelay);

So the sendTyping is valid for 250 ms if I am not mistaken , saw this somewhere in code this.options.autoBatchDelay = 250;
