### ISSUE TITLE
playing youtube video on web.skype.com web client window..

### ISSUE THREAD

**Issue by ronnelsantiago** [Microsoft/BotBuilder#731]
I'm using https://web.skype.com/en/?ecsoverride=developer and I just want to simply show user a youtube video, i know that the bing music bot does this ok, im setting it like so:

```csharp
new Attachment
{
    ContentUrl = "https://www.youtube.com/watch?v=tcPVzzyB7OI",
    ContentType = "video/mp4"
};
```

but im getting this instead:
![capture](https://cloud.githubusercontent.com/assets/1751062/16905606/0b10b48c-4cec-11e6-9728-fc427a71d0ff.PNG)

what I might be missing?

**Comment by ronnelsantiago** [comment]
As advised by @Stevenic I need to set the Text property of the Message like so:
```csharp
var reply = context.MakeMessage(); 
reply.Text = "https://www.youtube.com/watch?v=tcPVzzyB7OI"; 
await context.PostAsync(reply); 
context.Wait(MessageReceived);
```
The weird thing with this is that this did not work for me before and what I did next it you use the youtube url like:
```
https://youtu.be/tcPVzzyB7OI
```
as the value of the Text property and that actually shows up and web skype plays it as well. and then I switch back and tried using:
```
https://www.youtube.com/watch?v=tcPVzzyB7OI
```
and that one worked as well, for which that particular url link before wont show up at all.. any developer from the skype team look at this one please.. or will i just accept that it worked this time? assumming that the web skype client was updated? still puzzled.

**Comment by tomlm** [comment]
Yes, Ronnelsantiago is correct.
