### ISSUE TITLE
PrivateConversationData is not being saved in V3.0 (C# SDK)

### ISSUE THREAD

**Issue by kienct89** [Microsoft/BotBuilder#732]
Hi,

I'm having problems with saving and retrieving **PrivateConversationData** using new **BotStateClient** in latest C# v3.0 SDK.

Code Sample:

1. **Save**

```
public static void SavePrivateConversationData(this Activity activity, params KeyValuePair<string, object>[] keyValues)
{
     var stateClient = activity.GetStateClient();
     var privateConversationData = stateClient.BotState.GetPrivateConversationData(activity.ChannelId, activity.Conversation.Id, activity.From.Id);
     foreach (var keyValue in keyValues)
     {
          privateConversationData.SetProperty(keyValue.Key, keyValue.Value);
     }
     stateClient.BotState.SetPrivateConversationData(activity.ChannelId, activity.Conversation.Id, activity.From.Id, privateConversationData);
}
```

```
activity.SavePrivateConversationData(new KeyValuePair<string, object>("persistedCookie", resumptionCookie));
```

2. **Load**

```
public static TType LoadPrivateConversationData<TType>(this Activity activity, string key = null) where TType : class
{
     var stateClient = activity.GetStateClient();
     var privateConversationData = stateClient.BotState.GetPrivateConversationData(activity.ChannelId, activity.Conversation.Id, activity.From.Id);
     var property = privateConversationData.GetProperty<TType>(key);
     return property;
}
```

`
var pending = activity.LoadPrivateConversationData<ResumptionCookie>("persistedCookie");
`

Additional Notes:
- if I debug or load the private conversation data **right after it being added**, the data is there. However, on the next request, the data is gone
- `IBotContext.PrivateConversationData.SetValue();` => this method is still working as expected.

Thanks,

**Comment by glenchao** [comment]
[similar problem](https://github.com/Microsoft/BotBuilder/issues/730) to what i was experience in js

**Comment by NanashiGIT** [comment]
Pretty much the same problem i have, not just with PrivateConversationData:
[https://github.com/Microsoft/BotBuilder/issues/643](https://github.com/Microsoft/BotBuilder/issues/643)

**Comment by kienct89** [comment]
@NanashiGIT do you have any workround for now?

**Comment by NanashiGIT** [comment]
Not really. I have to save my data in an azure table storage... but i still hope they can help us on this one.

**Comment by glenchao** [comment]
@kienct89 i have a temporary work around for JS... not sure if you could find a similar thing for c#
In JS, change `body.data` to `body.Data` in `ChatConnector.getData`. 

That said, I don't think that's the right fix... I think the problem might be the emulator? 


Another workaround is to use ConsoleConnector first, then switch back to ChatConnector before deploying...

**Comment by msft-shahins** [comment]
@kienct89, @NanashiGIT does this only happen when you test against emulator? or does it happen against the production state API service too?

**Comment by msft-shahins** [comment]
@kienct89, also are you using the builder SDK and use the StateClient to save the data in your dialog? Is there a reason not to use the IDialogContext? 

Builder is using [CachingBotDataStore_LastWriteWins](https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Dialogs/BotData.cs#L244) as its default IBotDataStore implementation which means that when [PersistentDailogCotext](https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Dialogs/DialogTask.cs#L355) flushes, it will overwrite all the cached data with etag="*" to resemble `Last Write Wins` data consistency model. All the data written to dialog context will get flushed and persisted to StateAPI. We are planing to implement a consistent IBotDataStore based on etags too, to enable a more restrictive data consistency model.

**Comment by kienct89** [comment]
@msft-shahins 

Hi shahins, I only tested on emulator because I don't want affect live clients.

Also I cannot use **IDialogContext** because I want to perform state save inside **LuisDialog** where the context is not available to use.

If you have any solution for now (work around or not), please let me know.

Thanks.

**Comment by msft-shahins** [comment]
You have IDialogContext available in all of the Luis intent handlers that you define for your LuisDialog. Assuming that those are the entry points to your dialog, you can pass around IDialogContext to all other methods in your dialog.

**Comment by kienct89** [comment]
@msft-shahins 
hi shahins,

I'm trying to pass context to LuisDialog, but I got this exception

`Type 'Microsoft.Bot.Builder.Dialogs.Internals.DialogContext' in Assembly 'Microsoft.Bot.Builder, Version=3.0.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' is not marked as serializable.`

What did I do wrong?

thanks for your help in advance

**Comment by msft-shahins** [comment]
@kienct89 DialogContext implementation is not serialize, you shouldn't keep a local variable in your class referencing the IDialogContext. If you want to have access to IDialogContext in your LuisDialog methods, I recommend passing a reference to it as an argument of the function rather than keeping it as a member variable in your class.

**Comment by kienct89** [comment]
@msft-shahins 

perfect, thanks for your advice,
another question: is there anyway I can remove one record based on the key in **PrivateConversationData** using **StateClient**.

As in the documentation, there are get/set methods, but there's no **RemoveValue**

**Comment by tomlm** [comment]
You can just set it it to null.  That is effectively a delete.

**Comment by kienct89** [comment]
@tomlm 

When I tried to set it to null, it throw the exception "value cannot be null".

**Comment by SageEx** [comment]
I too got a null exception when trying to set a null value to a string. This used to work in v1.0.
```c#
context.UserData.SetValue<string>("keyWanted", null);
```

However, this works.
```c#
context.UserData.SetValue<string>("keyWanted", "");
```
