### ISSUE TITLE
Direct Line: How to really use upload function to upload image?

### ISSUE THREAD

**Issue by kenakamu** [Microsoft/BotBuilder#733]
Hi there,

I cannot figure out how to upload image via Direct Line. Is there any comprehensive samples?
Thanks!

**Comment by Samurais** [comment]
hi, if you are using nodejs, take a look at this module. 
https://www.npmjs.com/package/directline-api

It is in ``` client.postFileMessage(token, conversationId, formData); ```. 

```
    // check out form data format
    // https://www.npmjs.com/package/request#multipartform-data-multipart-form-uploads
    directLineAPI.getToken(conf.DIRECT_LINE_SECRET)
        .then(function(token) {
            return directLineAPI.createConversation(token);
        })
        .then(function(result) {
            // console.log('postFileMessage>> ' + JSON.stringify(result));
            return directLineAPI.postFileMessage(result.token, result.conversationId, {
                my_file: fs.createReadStream(__dirname + '/unicycle.jpeg'),
            })
        })
        .then(function(result) {
            t.pass();
            t.end();
        })
        .fail(function(err) {
            t.fail();
            t.end();
        });
```

**Comment by kenakamu** [comment]
Thanks,
I tried by using C# and the upload one returns status of 204, which is expected. 
However, it doesn't actually sending Activity to bot framework. Do you have sample to send the message after you do upload?

**Comment by dandriscoll** [comment]
We have a bug in uploading attachments to v3 bots that we hope to have fixed soon. The C# client should work fine once that bug is fixed.

**Comment by kenakamu** [comment]
Thanks dandriscoll. So we cannot upload image for now? Please also fix DirectLine SDK client, as upload method only accept conversationId.

**Comment by danmarshall** [comment]
I'm going to close this issue for now, but feel free to open a new issue for further discussion.

**Comment by palmerabollo** [comment]
@dandriscoll I see a http 500 status code when I try to upload a file using direct line. Is the bug already fixed in v3?

**Comment by dandriscoll** [comment]
The documentation is a little thin on this (it's in the backlog) but the upload method works just like a regular web upload endpoint. It accepts multipart MIME content.

**Comment by dandriscoll** [comment]
If you use our Web Chat control, you can observe the requests coming from the browser to the Web Chat service, which talks the same protocol as Direct Line.
