### ISSUE TITLE
@ tags making formflow to fail

### ISSUE THREAD

**Issue by upendrareddy2003** [Microsoft/BotBuilder#734]
Hi Team,

I am trying to build a bot using FormFlow. I deployed the service to Azure and calling the service from Skype. When I press the button on a Field enum list, I am getting @ tag in the activity.Text. The text(acticity.Text) that I am getting is _&lt;at id="28:c442d87d-4945-4f16-bd2e-3efc69fe01d0"&gt;@BuildHDFCBot  &lt;/at&gt; 1_.  As a result FormFlow is throwing an error like _"@BuildHDFCBot 1" is not an option_. How can we handle this ? 

Thanks,
Upendra

**Comment by chrimc62** [comment]
Can you share your enumeration and any attributes or settings you have on it?  By default the button text returned is a number if numbers are allowed.  If numbers are not allowed it should be a copy of your enumeration value which should never include an at symbol.  If it does then there is a bug.

**Comment by upendrareddy2003** [comment]
Skype upgrade has fixed the problem. Now i don't see @ tags are coming up.
