### ISSUE TITLE
Error in node.js documentation page for Dialogs

### ISSUE THREAD

**Issue by glenchao** [Microsoft/BotBuilder#735]
[documentation page for Dialogs](https://docs.botframework.com/en-us/node/builder/chat/dialogs/#dialog-handlers)

The second example code block for Waterfall uses `session.endDialogWithResults`. 
It should be [session.endDialogWithResult](https://docs.botframework.com/en-us/node/builder/chat-reference/classes/_botbuilder_d_.session.html#enddialogwithresult) instead.

**Comment by Stevenic** [comment]
Fixed :)
