### ISSUE TITLE
Skype attachment

### ISSUE THREAD

**Issue by asubbotin** [Microsoft/BotBuilder#737]
Hi all!

I have a problem. The object contains list of attachments if incoming message has one. But ContentUrl don't work. For example object have
ContentUrl=https://df-apis.skype.com/v2/attachments/0-neu-d5-faac5db55162e82d9261c8777066c6d3/views/original
or
ThumbnailUrl=https://df-apis.skype.com/v2/attachments/0-neu-d5-faac5db55162e82d9261c8777066c6d3/views/thumbnail
But if open a url in browser, then it's empty.

**Comment by msft-shahins** [comment]
Similar to #662. Skype attachments are secured by bot JwtToken, you need bot JwtToken as a bearer token to be able to access those urls.
