### ISSUE TITLE
Redundant text with herocards and prompts in Facebook Messenger

### ISSUE THREAD

**Issue by jrmienna** [Microsoft/BotBuilder#739]
When you send herocards or prompts, the bots sends **redundant** text saying "Options" in Facebook Messenger. 

![capture](https://cloud.githubusercontent.com/assets/6793075/16921250/036c273c-4d11-11e6-8214-e3a3fae728f7.PNG)

Here's the code:
```
let msg = new builder.Message(session)
  .text('This is what I can help you with :angel:');
  msg.addAttachment(
      new builder.HeroCard(session)
                    .buttons([
                        builder.CardAction.imBack(session, "Add grocery", "Add grocery"),
                        builder.CardAction.imBack(session, "Remove grocery", "Remove grocery"),
                        builder.CardAction.imBack(session, "Change pick-up time", "Change pick-up time")
                    ])
            );
```

**Comment by garypretty** [comment]
This is a currently known issue (https://github.com/Microsoft/BotBuilder/issues/711) and has been marked as a bug so the team are aware of it. Hopefully there should be a fix soon.

**Comment by tomlm** [comment]
this is fixed.
