### ISSUE TITLE
"is having a problem responding right now" with every bot message only on facebook

### ISSUE THREAD

**Issue by apuyana** [Microsoft/BotBuilder#741]
After I upgraded the bot to V3 everythings seems to work, I use skype channel, web chat and facebook, on all the channels the bot is working as expected, except with facebook, after every message the bot sends back, there is another message that says "<botName> is having a problem responding right now" 
I have already used /deleteprofile command and the problem still happends.

The status of the channels is "Running".

**Comment by msft-shahins** [comment]
Can you share you the Microsoft App Id of your bot?

**Comment by apuyana** [comment]
Sure, the App Id is "99e647a2-f3cd-46cb-826c-beac3e1cd85e"

**Comment by tomlm** [comment]
Can you add your bot handle?

**Comment by tomlm** [comment]
You might try going to the facebook configuration page and resubmitting your credentials.

**Comment by apuyana** [comment]
Bot handle "ParceroProduction".
I did removed the credentials and resubmit them. I also removed the webhook on the facebook app and reconfigured it. I just notice today that some messages in the facebook channel are sent twice.

**Comment by apuyana** [comment]
I just notice this error in the status of the channel 

Facebook graph API call failed with: BadRequest {"error":{"message":"(#194) param [elements] has too few elements.","type":"OAuthException","code":194,"fbtrace_id":"Hz7T5FoCxCl"}}

**Comment by apuyana** [comment]
I deleted the bot and recreate it, created new application Id and everything and the problem keeps showing, new handle "Parcerobot" new Microsoft App Id "c5982bc8-c332-4a82-8ff6-1630027a2283"

**Comment by apuyana** [comment]
I finally found the problem, there was an error in a dialog serialization. I fixed the dialog and the problem disappeared. I do not understand why the problem was only reflected on the facebook channel.

**Comment by MCKRUZ** [comment]
apuyana, I'm having the same issue can you elaborate on what you did to fix it.

**Comment by apuyana** [comment]
@MCKRUZ I found the problem by adding a Try/Catch on the service entry point, the exception message was that the dialog I was creating had enviroment variables that could not be serialized
So to fix it I changed the root dialog creation from:
`await Conversation.SendAsync(activity, () => { return MakeRoot(activity); });`

to:

`await Conversation.SendAsync(activity, MakeRoot);`

I needed the activity in the dialog because when I created a replay message from the IDialogContext, some field were null, so in the end I fixed the problem in the CreateReplay method and that way did not need the activity.

Check the fixes in my branch https://github.com/anuracode/BotBuilder

**Comment by fcioffi** [comment]
Sorry, I have the same problem on nodeJS SDK can you suggest a solution language independent?

**Comment by apuyana** [comment]
@fcioffi The fix I made was in the creation of the replay message I completed the values of ServiceUrl and ChannelId that were null and not copied.

I am now using the Microsoft.Bot.Builder nuget package 3.5.1 and do not have this problem.

Hope this helps
