### ISSUE TITLE
DirectLine API - how to post messages as the same user and same address for session.message?

### ISSUE THREAD

**Issue by Samurais** [Microsoft/BotBuilder#747]
# Description

I have tested with Postman 4.4.2, the Direct Line API can talk with botbuilder. But I got trouble to make it work well in my nodejs application - botbuilder get random user/address from session.message. But it can be the same address and user with Postman.  

### Post a message 
![image](https://cloud.githubusercontent.com/assets/3538629/16936647/dd00a692-4d9a-11e6-9c52-a5f86ec222cd.png)

### session.message in botbuilder
```
{
  "type": "message",
  "timestamp": "2016-07-19T02:19:55.3482054Z",
  "text": "sure3",
  "address": {
    "id": "8CuiRZcLz8q",
    "channelId": "directline",
    "user": {
      "id": "5G9CZKxecDr",
      "name": "5G9CZKxecDr"
    },
    "conversation": {
      "id": "BwsNQTCBsgK"
    },
    "bot": {
      "id": "dagama_rebecca",
      "name": "Rebecca"
    },
    "serviceUrl": "https://directline.botframework.com",
    "useAuth": true
  },
  "source": "directline",
  "attachments": [],
  "entities": [],
  "agent": "botbuilder",
  "user": {
    "id": "5G9CZKxecDr",
    "name": "5G9CZKxecDr"
  }
}
```
### Post another message
![image](https://cloud.githubusercontent.com/assets/3538629/16936654/e928a01e-4d9a-11e6-9356-9debbf69d5dd.png)

### session.message in botbuilder
```
{
  "type": "message",
  "timestamp": "2016-07-19T02:20:07.0360006Z",
  "text": "sure4",
  "address": {
    "id": "3d7VE1JetB2p",
    "channelId": "directline",
    "user": {
      "id": "5G9CZKxecDr",
      "name": "5G9CZKxecDr"
    },
    "conversation": {
      "id": "BwsNQTCBsgK"
    },
    "bot": {
      "id": "dagama_rebecca",
      "name": "Rebecca"
    },
    "serviceUrl": "https://directline.botframework.com",
    "useAuth": true
  },
  "source": "directline",
  "attachments": [],
  "entities": [],
  "agent": "botbuilder",
  "user": {
    "id": "5G9CZKxecDr",
    "name": "5G9CZKxecDr"
  }
}
```

**So, the two session.messages are in the same address with the same user**.

## Request with nodejs application

POST with the same conversationId and same token in the same machine.
the two session.messages are like

* 1st message
```
{
  "type": "message",
  "timestamp": "2016-07-19T01:00:06.2493742Z",
  "text": "fio",
  "address": {
    "id": "2lPpKVkaySw",
    "channelId": "directline",
    "user": {
      "id": "5Xz7sYcIsiq",
      "name": "5Xz7sYcIsiq"
    },
    "conversation": {
      "id": "5A3Ia0DjSUd"
    },
    "bot": {
      "id": "dagama_rebecca",
      "name": "Rebecca"
    },
    "serviceUrl": "https://directline.botframework.com",
    "useAuth": true
  },
  "source": "directline",
  "attachments": [],
  "entities": [],
  "agent": "botbuilder",
  "user": {
    "id": "5Xz7sYcIsiq",
    "name": "5Xz7sYcIsiq"
  }
}
```

* 2nd message
```
{
  "type": "message",
  "timestamp": "2016-07-19T01:00:20.4549559Z",
  "text": "hain",
  "address": {
    "id": "AofzmJEng5L",
    "channelId": "directline",
    "user": {
      "id": "8HaElCwhqes",
      "name": "8HaElCwhqes"
    },
    "conversation": {
      "id": "5A3Ia0DjSUd"
    },
    "bot": {
      "id": "dagama_rebecca",
      "name": "Rebecca"
    },
    "serviceUrl": "https://directline.botframework.com",
    "useAuth": true
  },
  "source": "directline",
  "attachments": [],
  "entities": [],
  "agent": "botbuilder",
  "user": {
    "id": "8HaElCwhqes",
    "name": "8HaElCwhqes"
  }
}
```

**Now, the address and user are different.**

So, why this happens? the requests are all made against the Direct Line API, how to post as the same user and same address?

I am using Direct Line API lib https://www.npmjs.com/package/directline-api .

**Comment by Samurais** [comment]
In the body of POST /api/conversations/{conversationId}/messages, there is a property named ** from** in body schema. What does it used for? Is it can be used to identify the same user?

**Comment by Samurais** [comment]
It is the **from** solving my problem. If I assign it a unique value for each user, it works. In the botbuilder, I get the same address, so, thanks so much for help.

![image](https://cloud.githubusercontent.com/assets/3538629/16940518/177439a2-4dbd-11e6-872f-7dc201262a38.png)

**Comment by dandriscoll** [comment]
One additional note: the From field is required for most applications to behave properly. If you don't choose a value for the From field, we auto-assign a value for each message, which results in a new user. We'll be changing this behavior in a future release but for now it's stuck how it is.
