### ISSUE TITLE
Messenger channel debugging

### ISSUE THREAD

**Issue by pietie** [Microsoft/BotBuilder#748]
Is there a way to debug the comms on the FB Messengers channel?

I have messenger setup and it shows the status as **Running** on the dashboard but my bot is not receiving any http requests from it at all. I'm using v3 of the API and Nodejs.

I've tested by sending messages to the test page using my FB dev account. I also added my own personal FB account as developer and tried sending messages from it...but nothing.

**Comment by tomlm** [comment]
Try resubmitting your credentials.  Facebook is pretty aggressive about disabling registrations if they fail for several hours.

As far as getting more info, create an Azure App Insights and register it on your bot and we will log information from facebook into your azure App Insights logging where you can search and view them.
