### ISSUE TITLE
How to send a message to all channels based on external event?

### ISSUE THREAD

**Issue by FedericoElles** [Microsoft/BotBuilder#75]
I'm trying to create a news bot which should inform all connected chats/channels/users if for example any "breaking news" did happen. So I need to run for example based on an external API call:

    bot.beginDialog(...)

which requires address.user && address.channel

**Questions:** Do I need to remember all users and channels in my app, or is there a way in the BotFramework to retrive all connected users/channels?

This could be also useful to tell users if a bot has learned new features or any maintainance will occure.

Thanks a lot.

**Comment by LarsLiden** [comment]
We currently do not support the ability to retrieve a list of all the users / channels that have authorized your bot.  For the moment, you will need to store that on your own.

**Comment by tomlm** [comment]
lars is correct

**Comment by andrecordeiro** [comment]
@FedericoElles  , you could make sending news ? I'm also hitting me with this. Best regards.
