### ISSUE TITLE
NodeJS Vs .NET SDK Support

### ISSUE THREAD

**Issue by renjurajwm** [Microsoft/BotBuilder#750]
I have started a small project using NodeJS SDK. Then when i compare the SDK reference for NodeJS and .NET, I see NodeJS has very less docs compared to .NET. 
Is it that, currently all features are not implemented in NodeJS SDK ? Or Its only missing the documents reference ?

https://docs.botframework.com/en-us/node/builder/overview
https://docs.botframework.com/en-us/csharp/builder/sdkreference/index.html

**Comment by Thegaram** [comment]
I cannot talk for the team (I'm just an SDK user), but I'd say it's because Node.js and C# are different languages with different styles and advantages. Having exactly the same API might no work out well, as what seems logical on one side (e.g. custom dialog classes in C#) would not work with the other (or at least go against it's philosophy).

Well, that's my guess at least :smiley:

**Comment by alexsorokoletov** [comment]
as far as I know both SDKs are feature-equal.

**Comment by ankitbko** [comment]
I think this is answered in #231

**Comment by chrimc62** [comment]
@Thegaram did a good job of answering.  We try to keep the concepts and features roughly similar between the two but we also make the architecture reflect the way people actually use those languages.  Was there a particular feature you felt was missing in one or the other?

**Comment by Samurais** [comment]
If the SKDs are using the same backend APIs, they can support the same features sooner or later.

**Comment by renjurajwm** [comment]
Thanks for the response. 
@chrimc62, yes i am looking for a particular feature were BOT will start a conversation. 
For C# reference i am able to see the topic "Starting Conversations"  under "[Sending and Receiving Activities](https://docs.botframework.com/en-us/csharp/builder/sdkreference/routing.html)". But I could not see any similar information for NodeJS.

**Comment by slidenerd** [comment]
I double side @renjurajwm I cannot see the activities part for node.js as well. I even browsed the source code. Its not there inside the botbuilder.d.ts or Session.js or Middelware.js where exactly is this implemented
