### ISSUE TITLE
For Phone Call Function and Map Navigation

### ISSUE THREAD

**Issue by cheahengsoon** [Microsoft/BotBuilder#753]
Currently I had Developed an app that need to use Phone Call Functions (Not include Skype) and Map Navigation? 
May I know had any solutions for that for the bot framework?
Thank You.

**Comment by msft-shahins** [comment]
@cheahengsoon  Can you elaborate on this? What do yo mean by `Phone Call Function`? Are you referring to `Skype Calling` API? It would be good to understand what is the scenario that you want to implement?
