### ISSUE TITLE
ContentType in Skype attacment

### ISSUE THREAD

**Issue by asubbotin** [Microsoft/BotBuilder#754]
Hello!

How I can get ContentType in attachment in Skype? For example:
1. If attach Image, ContentType always "image" (not "image/jpeg", "image/gif" etc.)
2. If attach MSWord, MSExcel file, ContentType always "application/octet-stream"

Original filename in attachment object missing too. And I can't determine by extension: 
https://df-apis.skype.com/v2/attachments/0-neu-d5-faac5db55162e82d9261c8777066c6d3/views/original

**Comment by mmalbergier** [comment]
Is this still open?

**Comment by danmarshall** [comment]
Hello @asubbotin are you still experiencing this issue?

**Comment by TechWatching** [comment]
I have similar issues. The gif image I send have the contentType application/octet-stream. Moreover I am having trouble downloading it, even if I have no issue on the iframe chat or on the channel emulator.

**Comment by TechWatching** [comment]
My mistake, the issue (at least for the content type) is solved for me (see https://github.com/Microsoft/BotBuilder/issues/662).

**Comment by Andrea-Orimoto** [comment]
Thanks @TechWatching. @asubbotin we're closing this issue, let us know if you still need help. Thank you!
