### ISSUE TITLE
Bot Emulator 500 error

### ISSUE THREAD

**Issue by JagatheeshMenon2016** [Microsoft/BotBuilder#755]
Hi team,

Having followed all the suggestions I am still getting Error 500: Internal error. The code is executing fine until **"Activity reply = activity.CreateReply($"You sent {activity.Text} which was {length} characters");"**

but then when it goes to the next line "await connector.Conversations.ReplyToActivityAsync(reply);" its throwing error 500 snapshot is attached for further reference.

**webconfig details**

<configuration>
  <appSettings>
    
    <add key="BotId" value="testbot" />
    <add key="MicrosoftAppId" value="test" />
    <add key="MicrosoftAppPassword" value="password" />
  </appSettings>

**MessageController.cs**

 public async Task<HttpResponseMessage> Post([FromBody]Activity activity)
        {
            ConnectorClient connector = new ConnectorClient(new Uri(activity.ServiceUrl));
            if (activity.Type == ActivityTypes.Message)
            {
   
                // calculate something for us to return
                int length = (activity.Text ?? string.Empty).Length;

                // return our reply to the user
                Activity reply = activity.CreateReply($"You sent {activity.Text} which was {length} characters");
                await connector.Conversations.ReplyToActivityAsync(reply);
            }

Looking for help.
![error500](https://cloud.githubusercontent.com/assets/20538181/16953348/4d9023e8-4dea-11e6-83e7-5464be49236d.jpg)

**Comment by Thegaram** [comment]
In version V3 (that you're using) you have to manually send back an HTTP response. I suppose the lack of response from your code is interpreted as an error in the emulator.

Change your function signature to:

```js
public async Task<HttpResponseMessage> Post([FromBody]Activity activity)
```

If everything is fine, send back a response at the end of your function, for example:

```js
return Request.CreateResponse(HttpStatusCode.OK);
```

If this does not solve the problem, it's likely that an exception is thrown. In that case, please post here the exception message.

**Comment by tomlm** [comment]
remove appid and password from the emulator and your bot, the values in your screen shot are definitely not right.

**Comment by JagatheeshMenon2016** [comment]
Hi,

Please find attached update image, even after making the modification it still shows the same error. I have removed appid and password.
![bot](https://cloud.githubusercontent.com/assets/20538181/16987249/dc435600-4ea8-11e6-870a-b3f557a0b00e.png)
![webconfig](https://cloud.githubusercontent.com/assets/20538181/16987250/dc4d6f8c-4ea8-11e6-8e7d-e2c53e2824ac.png)
![messagecontroller](https://cloud.githubusercontent.com/assets/20538181/16987251/dc4df970-4ea8-11e6-887c-05b740f4d5b2.png)

**Comment by willportnoy** [comment]
The emulator URL in your screenshot is also incorrect.  The "Emulator Url" should be "http://localhost:9000" and the "Local Port" should be "9000".  This is always a different endpoint from your "Bot Url" which corresponds to your web project.

**Comment by willportnoy** [comment]
I'm going to close this issue, but feel free to open a new issue for further discussions.
