### ISSUE TITLE
Bot Emulator crashes due to bad Emulator Url or bad bot url

### ISSUE THREAD

**Issue by Mashakal** [Microsoft/BotBuilder#758]
I am not sure which the problem is.  I edited the port number of the emulator url instead of the bot url and now I can't edit anything because every time I run the emulator it crashes.  Where can I go to delete the cached data it's pulling these from?  I've tried uninstalling and reinstalling, but its still pulling the bad info.

![image](https://cloud.githubusercontent.com/assets/11655107/16960351/fce87df6-4d9d-11e6-837c-8d9d6c69b402.png)

**Comment by willportnoy** [comment]
I believe it's a file in your temp path called "emulator.service".

**Comment by tomlm** [comment]
erase %temp%\*emul*

**Comment by Mashakal** [comment]
Deleting emulator.service in C:\Users\Alex\AppData\Local\Temp worked.  I appreciate it!
