### ISSUE TITLE
Cannot connect Twilio Channel

### ISSUE THREAD

**Issue by macklee** [Microsoft/BotBuilder#760]
I tried to connect my Bot to Twilio and followed the steps in the guide but it will not move to my channels. I validated my credentials too.

**Comment by dandriscoll** [comment]
Hi @macklee, can you send your bot's App ID or Bot ID with me here or privately and I can take a look?

**Comment by danmarshall** [comment]
I'm going to close this issue for now, but feel free to open a new issue for further discussion.
