### ISSUE TITLE
Bot Framework Channel Emulator crashing on launch

### ISSUE THREAD

**Issue by RyanLy** [Microsoft/BotBuilder#763]
I'm getting this error when I start the Bot Framework Channel Emulator (v 3.0.0.58). It crashes immediately before I can do anything on the UI. I'm suspecting there to be some invalid form data that's causing the crash. 

Is there a way to reset the form data for the app?

Below is the error message I get when I try to debug it.
```
An unhandled exception of type 'System.UriFormatException` occured in mscorlib.dll

Additional information: Invalid URI: The URI is empty.
```
![emulatorcrash](https://cloud.githubusercontent.com/assets/4211689/16975450/695cb80a-4dfb-11e6-873f-bd1dab4c7291.png)
![uriexception](https://cloud.githubusercontent.com/assets/4211689/16975457/71c2f964-4dfb-11e6-8240-358ab071ee9d.PNG)

**Comment by willportnoy** [comment]
You can use the same solution as https://github.com/Microsoft/BotBuilder/issues/758:

erase %temp%*emul*

**Comment by RyanLy** [comment]
@willportnoy Thanks! It worked.

**Comment by letmaik** [comment]
I just stumbled upon the same thing. Why is this issue closed? It's obviously a bug.

**Comment by willportnoy** [comment]
We've been closing some of the issues that have not had recent activity.  I agree, it's definitely a bug.

In this case,

1. There is a workaround above for invalid data saved to the configuration file.
2. Also, I believe I had fixed this bug and prevented the emulator from crashing when there's invalid data in the url field.
