### ISSUE TITLE
Skype connector not working

### ISSUE THREAD

**Issue by suprak** [Microsoft/BotBuilder#765]
I tried to link my bot with Skype, however I received the following error,
``` 
Sad bot is sad because Unexpected error happened when trying to load the page. 
```
The connection appears after page refresh however I can't edit it and the test link does not work.

**Comment by pietie** [comment]
Is that the full error? I used to get the exception like in #678 but I tried again this morning and it is working for me.

**Comment by suprak** [comment]
Yup, and I can't remove/re-add the connector.
![capture](https://cloud.githubusercontent.com/assets/1128553/16992026/a2576022-4e52-11e6-9d35-0a5c6904bfa5.PNG)

**Comment by dandriscoll** [comment]
Can you send your bot ID or your MSA app ID?

**Comment by suprak** [comment]
The issue appears to have been because I had the 'Privacy statement' url and 'Terms of Use' url set to 'http://localhost'. Setting it a (more) valid value, removed the error.

**Comment by dandriscoll** [comment]
Thanks for tracing that down :) We'll fix this.
