### ISSUE TITLE
Nodejs bot server (3.0+) received empty attachments array message with image message sent from web chat.

### ISSUE THREAD

**Issue by lanma** [Microsoft/BotBuilder#767]
I tested the Nodejs SDK 3.0+ and found that I received an empty text and attachments array message with image message sent from web chat. I received correct attachments data from slack and facebook channel with the same test server code. Also I found that after I sent image from web chat and the server response slowly, the message sent back from server may be showed one step delay to web chat.

**Comment by Stevenic** [comment]
Adding dan

**Comment by dandriscoll** [comment]
Hi @lanma, upload in web chat was broken a few weeks ago but should be working now. I'm seeing it work correctly with my bots. Can you try again and see if it's still broken?

**Comment by lanma** [comment]
@dandriscoll It works now! Thank you very much!
