### ISSUE TITLE
Telegram: Authorization failed when sending activity to new conversation

### ISSUE THREAD

**Issue by NanashiGIT** [Microsoft/BotBuilder#769]
Hello!
For some reason i get the Exception:
"Authorization for Microsoft App ID 4998a523-b204-4f22-b137-37ba8e808e3a failed with status code Forbidden"
when i send a new activity to a new conversation i created in telegram.

The code is:
```cs
var activity = new Activity();
conClient = new ConnectorClient(new Uri("https://telegram.botframework.com/"), MicrosoftAppId, MicrosoftAppPassword);
activity.From = new ChannelAccount { Id = strChannelId };
activity.Recipient = new ChannelAccount { Id = ChannelUserAddress };
var Conversation = await conClient.Conversations.CreateDirectConversationAsync(activity.From, activity.Recipient);
activity.ChannelId = strChannelId;
activity.Locale = "en-Us";
activity.Conversation = new ConversationAccount(id: Conversation.Id);
activity.Type = ActivityTypes.Message;
activity.Text = strMessage;
var resultApi = await conClient.Conversations.SendToConversationAsync(activity);
```

The exception gets thrown at the last line, when i try to actually send the message. The conversationID is valid.

The strange thing is, that it works perfectly with Skype (same code, just different Uri ofc).
Whats even more strange is that this exact same code worked for telegram a few days ago.
I'm 100% sure that MicrosoftAppID and Password are correct. (it wouldnt work with skype, if they werent correct)
I even deleted the whole bot from telegram and my bot configuration and created a new one. Still doesnt work.

Oh and i can perfectly send messages to my bot and get replies. That is working.

Any thoughts?

Greetings

**Comment by dandriscoll** [comment]
Hi @NanashiGIT, I can see the failed requests on my side and am taking a closer look.

**Comment by dandriscoll** [comment]
This is a bug in the C# SDK and we'll have a revision available for you soon.

**Comment by NanashiGIT** [comment]
Thank you.
I'm looking forward to it.

**Comment by dandriscoll** [comment]
The latest C# SDK includes auth reliability fixes. Please upgrade to >= 3.1.0. Thanks!

**Comment by fercom** [comment]
I have updated to 3.1.0 version and still facing this bug

**Comment by eanders-MS** [comment]
@fercom, what is your bot handle? Also, does anything look awry on your bot's dashboard page? In particular, are there any errors logged for Telegram?
