### ISSUE TITLE
Activity.CreateReply(...) sets Conversation.IsGroup to null.

### ISSUE THREAD

**Issue by mikalets** [Microsoft/BotBuilder#770]
These two lines in the CreateReply method in [ActivityEx.cs](https://github.com/Microsoft/BotBuilder/blob/c4dbb7183cc1c23837b6d6c8bc03fe8c54ba1f55/CSharp/Library/Microsoft.Bot.Connector/ActivityEx.cs) has the (presumably unintended) side effect of overwriting Conversation.IsGroup on the original activity:
```C#
reply.Conversation = this.Conversation; 
reply.Conversation.IsGroup = null; // don't need to send in a reply 
```

Easy way to repro this bug, assuming you already have an `activity` from your controller being posted to:

```C#
Console.WriteLine(activity.Conversation.IsGroup); // false
var reply = activity.CreateReply("hi");
Console.WriteLine(activity.Conversation.IsGroup); // null
```

Suggested fix would be replacing the offending two lines with:
```C#
reply.Conversation = new ConversationAccount
{
    Id = this.Conversation.Id,
    Name = this.Conversation.Name,
    IsGroup = null // don't need to send in a reply
};
```

**Comment by msft-shahins** [comment]
This is fixed in the latest nuget 3.1 release.
