### ISSUE TITLE
Updating to 3.0.1 - 500 InternalServerError

### ISSUE THREAD

**Issue by maxklock** [Microsoft/BotBuilder#773]
After updating all NuGet-Packages to Bot.builder 3.0.1 my Bot doesn't work anymore. When starting it and using Bot Emulator, I'm getting "500 InternalServerError" and when Publishing to Azure in Telegram I get "Sorry, XXX is having a problem responding right now."

**Comment by dandriscoll** [comment]
In the Bot Framework dev portal, does the "Test Connection to your Bot" pane show that you can communicate with your bot?

**Comment by maxklock** [comment]
Bevor updating, I was able to communicate with my bot, but now it says:

> InternalServerError
> {
>   "message": "An error has occurred.",
>   "exceptionMessage": "Could not load type 'System.IdentityModel.Tokens.TokenValidationParameters' from assembly 'System.IdentityModel.Tokens.Jwt, Version=5.0.0.127, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.",
>   "exceptionType": "System.TypeLoadException",
>   "stackTrace": "   at Microsoft.Bot.Connector.BotAuthentication.<OnAuthorizationAsync>d__16.MoveNext()\r\n   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)\r\n   at Microsoft.Bot.Connector.BotAuthentication.OnAuthorizationAsync(HttpActionContext actionContext, CancellationToken cancellationToken)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"
> }

But I tried different JWT versions.

**Comment by dandriscoll** [comment]
We rely on version 4.0.2.206221351 of the System.IdentityModel.Tokens.Jwt package. Can you try that?

**Comment by maxklock** [comment]
Now, i get "Endpoint authorization succeeded" in the Bot Framework dev Portal, but the Emulator still throws the error and in Telegram I'm still getting "Sorry, X is having a Problem...."

**Comment by maxklock** [comment]
After some restarts i found the Point, the error is thrown:

await connector.Conversations.ReplyToActivityAsync(activity.CreateReply("MyMessage"));
> Invalid token. System.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException: IDX10500: Signature validation failed. Unable to resolve SecurityKeyIdentifier: 'SecurityKeyIdentifier

And the connector I'm getting this way:
> var connector = new ConnectorClient(new Uri(activity.ServiceUrl));

**Comment by dandriscoll** [comment]
Do you have a bot ID or MSA ID, and the channel where this failure occurred?

**Comment by maxklock** [comment]
The Bot Id is "werewolf" and I'm using the emulator and telegram.
If you need, I can give you access to my repository.

**Comment by maxklock** [comment]
Creating a new Bot and copy MessageController and web.conf solves the Problem.
