### ISSUE TITLE
Question about context.Done and multiple dialogs

### ISSUE THREAD

**Issue by asram363** [Microsoft/BotBuilder#775]
I have 3 LuisDialogs: a rootdialog, dialog2, and dialog3. What I want is for my RootDialog to call either Dialog2 or Dialog3 based on what the input is. Each time there is a new message, I want it to first go to my RootDialog and from there to one of the other dialogs. I am using context.Forward in my RootDialog to do this. The forwarding seems to work, but then once it goes into dialog2 or dialog3, it seems to stay there and not come out. How do I make it so that each time there is a new message, it first goes to RootDialog? Should I use something like context.Done in dialog2 and dialog3?

**Comment by willportnoy** [comment]
context.Done is the only way to pop a dialog off the stack.  context.Call is the normal way to push a dialog on the stack.

context.Forward is a mechanism to reuse child dialogs (which normally StartAsync and then wait for a message) by pushing them on the stack and pretending that the incoming message was actually sent to them.

**Comment by asram363** [comment]
Ok, so when you use context.Forward, does it automatically return back to the calling dialog?

**Comment by willportnoy** [comment]
When the child dialog completes and calls context.Done itself, it returns to the ResumeAfter method passed to the context.Forward(child, resumeAfter, item, token) call made by the parent.

**Comment by asram363** [comment]
So would I need to explicitly call context.Done somewhere in my child dialog, or does context.Forward take care of that as well?

**Comment by willportnoy** [comment]
You would need to call context.Done to exit from the child dialog.  Initially, we didn't have Forward.  In that world, you would Call a child dialog, and it would complete with Done.  That allows the child dialog to be a composable piece you can stitch together to construct your bot.  Forward just makes it convenient to forward the incoming IAwaitable's item to a child dialog to enhance the possibilities for reuse.

**Comment by willportnoy** [comment]
I'm going to close this issue, but feel free to open a new issue for further discussions.
