### ISSUE TITLE
Support for wit.ai within bot framework

### ISSUE THREAD

**Issue by satyajit-behera** [Microsoft/BotBuilder#777]
Will bot builder support wit.ai within the bot framework in addition to the luis framework?

**Comment by willportnoy** [comment]
We have an item where you can vote for this feature:

https://feedback.botframework.com/forums/354222-bot-builder-sdk/suggestions/13494474--nocejs-add-a-wit-ai-dialog-class-similar-to-luis

**Comment by satyajit-behera** [comment]
voted

**Comment by Andrea-Orimoto** [comment]
Thanks for the suggestion, we've added it to our backlog.

**Comment by viralgandhi** [comment]
Any updates on this? can we use wit.ai with bot framework now? I wanted to use wit.ai because it supports more languages than LUIS for NLP

**Comment by willportnoy** [comment]
@viralgandhi, the idea behind the dialog stack is that you can compose your bot of multiple, distinct services - so for example, you could have a wit.ai dialog instead of a luis dialog if you want to use the wit.ai service.

**Comment by Rclemens** [comment]
@willportnoy does that mean we have to implement the wit.ai service ourselves? I don't fully understand your answer. 
It would be great if we could implement it the same way we do when implementing Luis just by adding the data annotations on the dialogclass

**Comment by willportnoy** [comment]
@Rclemens one method you might choose is to implement the ILuisService interface against the wit.ai service, and then you can reuse the LuisDialog directly.

Note, I have not tried this myself, but it's seems like the most direct path from within the code, at the very least.

**Comment by adebisi-fa** [comment]
@Rclemens @willportnoy  There is a prototype of LUIS implementation for [Wit.Ai (C#) here](https://github.com/adebisi-fa/Bot.Builder.WitAi).  It implements the **ILuisService** for [Wit.Ai](http://wit.ai).  Sample will be added to the repo, asap.  It's available on [NuGet here](https://www.nuget.org/packages/Adfa.Bot.Builder.WitAi/0.1.0).  

Hope it helps.

**Comment by willportnoy** [comment]
thank you for sharing @adebisi-fa !

**Comment by salunkheshubham1995** [comment]
how to connect wit.ai with bot framework to get http response?
