### ISSUE TITLE
got 500 InternalServerError from Luis when tried the SimpleAlarmBot

### ISSUE THREAD

**Issue by Yabo** [Microsoft/BotBuilder#780]
I simply sync'ed the latest code, built the sample and gave a try from emulator. The other simple samples without Luis works. Any special configuration I need to do before run the samples with Luis?
thanks

**Comment by Yabo** [comment]
It failed all the time yesterday, but works today..., might be Luis transient problem

**Comment by willportnoy** [comment]
That seems possible.  Thank you for the report.  I'm going to close this issue now, but feel free to open new issues..
