### ISSUE TITLE
Method not found: 'Void Microsoft.Rest.HttpOperationException.set_Request(System.Net.Http.HttpRequestMessage)'.

### ISSUE THREAD

**Issue by kbrimble** [Microsoft/BotBuilder#783]
When receiving any message with a simple `MessagesController` like:
```
        public async Task<HttpResponseMessage> Post([FromBody] Activity activity)
        {

            if (activity != null)
            {
                // one of these will have an interface and process it
                switch (activity.GetActivityType())
                {
                    case ActivityTypes.Message:
                        await Conversation.SendAsync(activity, MakeRoot);
                        break;

                    case ActivityTypes.ConversationUpdate:
                        //await SetCustomerId(activity);
                        break;
                    case ActivityTypes.ContactRelationUpdate:
                    case ActivityTypes.DeleteUserData:
                    case ActivityTypes.Ping:
                    case ActivityTypes.Typing:
                        _logger.Debug($"Activity type {activity.GetActivityType()}");
                        break;
                    default:
                        _logger.Error($"Unknown activity type ignored: {activity.GetActivityType()}");
                        break;
                }
            }
            return new HttpResponseMessage(HttpStatusCode.Accepted);
        }
```
We are getting the message:

> Method not found: 'Void Microsoft.Rest.HttpOperationException.set_Request(System.Net.Http.HttpRequestMessage)'

This exception in thrown from the `BotState` class for all of the `Get<DataKind>DataWithHttpMessagesAsync` methods. It seems to specifically relate to code trying to contact the BotState REST service.

Part of my question is how does all of this behave when the bot state service is down? The other part is obviously how do I solve this?

**Comment by dandriscoll** [comment]
This looks like an assembly binding failure -- are you using Microsoft.Rest.ClientRuntime 1.8.2?

**Comment by kbrimble** [comment]
Yes I am. I found the problem in the end. I had the emulator open which was
opening Microsoft.Rest.ClientRuntime 1.0.0.0 and then I was having the
"first loaded wins" problem.
