### ISSUE TITLE
DirectLine return http 500 if the ChannelData is an array

### ISSUE THREAD

**Issue by mayuanyang** [Microsoft/BotBuilder#784]
The bot is implemented in C#
DirectLine return http 500 if the ChannelData is an array

**Comment by dandriscoll** [comment]
The clients for the current version assume it's an object. As a workaround, you can nest the array inside an object. We'll take a look in a future release but strongly typed languages (C#, but eventually others) typically force us to choose one.

**Comment by mayuanyang** [comment]
Sure, that was what i did as well, thanks for your help
