### ISSUE TITLE
Self signing certificate at Messaging endpoint

### ISSUE THREAD

**Issue by arieschwartzman** [Microsoft/BotBuilder#786]
Can I use self signing certificate when defining a messaging endpoint?  In previous version, I could use http, now I must use https. 

How can I debug skype bot (without using nrgrok)

**Comment by dandriscoll** [comment]
Hi @arieschwartzman, we require a chain-trusted certificate, sorry.

Some hosting providers offer low-cost or free SSL hosting solutions. Azure is an example -- you can get a trial subscription and host a web app on SSL there for free. Others are available, too.

**Comment by Varooneh** [comment]
Hi @arieschwartzman , you can get free ssl for one year from https://www.startssl.com/ for 5 domain or subdomain, I used this service and this is very good or if you need unlimited free ssl you can use https://www.sslforfree.com/, SSL's is valid but not tested.

**Comment by arieschwartzman** [comment]
That's cool. Thanks a lot

**Comment by Varooneh** [comment]
@arieschwartzman your're welcome.

**Comment by JpEncausse** [comment]
A little feedback, 
- It's great to have a chain of trust 
- BUT asking a developer to put a trusted SSL certifcate on it's "hello bot" code is a very strong NoGo 

In many companies, the developers is not the guy who own the trusted certificate and we lose a lot of time.

**Comment by Varooneh** [comment]
@JpEncausse I think, azure has default ssl for all acounts (when I register account on azure, I get https://projectname.azure.com), with startssl.com I can register subdomain and get ssl for this but I don't know how to install ssl on azure (can not help you), also you can get ssl from https://www.sslforfree.com/ for any domain or subdomain (different way for install sslforfree like attached image) . (sorry for bad english)

![sslforfree](https://cloud.githubusercontent.com/assets/16257304/17420383/8d4aff42-5ab7-11e6-9610-eadc7d1c764e.png)

**Comment by JpEncausse** [comment]
Yes I did that but the request is rejected because of the key word "azure" in devsomething.westeurope.cloudapp.azure.com 

I'll dig deeper...

**Comment by JpEncausse** [comment]
Ok, so my lowcost workaround was to subscribe a little SSL Account on Gandi (12€/y) for a subdomain with A Record link to Azure IP Address.
