### ISSUE TITLE
Node demo-skype bot.on('typing'.. not firing when user is typing

### ISSUE THREAD

**Issue by oztheozoz** [Microsoft/BotBuilder#788]
I loaded up and ran the demo-skype app (2a6cc97). The following code on line 98 does not fire when the user on Skype is typing. I made sure the Skype client had the option "Send typing notification" selected in the preferences. I may be interpreting the usage of this event incorrectly. If so, please correct me. If not, then this could be a bug.

```
bot.on('typing', function(message) {
  // User is typing
});
```

**Comment by danmarshall** [comment]
Hello @oztheozoz are you still seeing this error?

**Comment by oztheozoz** [comment]
I haven't been working with the botbuilder library as of late and thus did not test it with the latest builds. I assume it is still a problem in 2a6cc97.

As a clarification, isn't the function supposed to fire when the user starts typing?

**Comment by danmarshall** [comment]
yes, it should. Do you have the latest Skype client?

**Comment by oztheozoz** [comment]
I have version 7.31 for Mac
I believe the latest is 7.33

**Comment by danmarshall** [comment]
Can you npm update to the latest BotBuilder and verify ?

**Comment by oztheozoz** [comment]
I can do that next week.

**Comment by oztheozoz** [comment]
Tested with botbuilder 3.2.3 and it did not work.

**Comment by danmarshall** [comment]
Hi @oztheozoz I just looked into this and it appears that it is not yet implemented for Skype.

**Comment by danmarshall** [comment]
Right now it seems that Slack has it implemented

**Comment by nickcordrey** [comment]
Confirming Skype doesn't support sending typing indicator, we'll remove it from the sample.
