### ISSUE TITLE
Unable to generate receipt card for facebook messenger

### ISSUE THREAD

**Issue by manojkota** [Microsoft/BotBuilder#789]
Hi, I am unable to generate receipt card for facebook messenger.

Exception Message 
Facebook graph API call failed with: BadRequest {"error":{"message":"(#100) The parameter is required","type":"OAuthException","code":100,"fbtrace_id":"EMwZFz9wR2A"}}

**Comment by matheus208** [comment]
Are you using the ReceiptCard class? I just managed to send the card using Message.sourceEvent :/

**Comment by manojkota** [comment]
Yes, I am using the Receipt class. Followed the [documentation](https://docs.botframework.com/en-us/csharp/builder/sdkreference/attachments.html). I have tried with the same example they have mentioned on the page. I am able to send hero & thumbnail cards. The only problem is with Receipt card.

**Comment by danmarshall** [comment]
Hello are you still having this issue?

**Comment by manojkota** [comment]
Yes.

**Comment by J3QQ4** [comment]
Same here, never got a ReceiptCard to work, although it shows up fine in the bot emulator. Judging by #644 the ReceiptCard may be broken now.

**Comment by ejadib** [comment]
@msft-shahins @willportnoy FYI, the receipt card on Facebook is now throwing this error: 	

> Facebook graph API call failed with: BadRequest {"error":{"message":"(#100) The parameter [summary][total_cost] is required","type":"OAuthException","code":100,"fbtrace_id":"D7N\/8qwkicg"}}

but the code is setting the ReceiptCard.Total prop

**Comment by AlexeyGrishinActimind** [comment]
+1

**Comment by maheshcv** [comment]
Same problem with builder.ReceiptCard() - It crashes

**Comment by leroibeukes** [comment]
Problem still persists.... works fine on Skype and emulator

**Comment by craigjensen** [comment]
Can you post the raw message json that your bot is sending?

**Comment by leroibeukes** [comment]
Hi

I got it working by supplying the Tax and Total properties with a value of '1' - Apparently FB does not like 0's in those fields.... Overall the Receipt card in FB is just that - to be used as a receipt , in Skype you can wangle it for other purposes but in FB it has currency symbols and other info added.
