### ISSUE TITLE
PromptDialog.Choice doesn't display choices. (C#)

### ISSUE THREAD

**Issue by alexyak** [Microsoft/BotBuilder#79]
It looks like the call to PromptDialog.Choice  doesn't display choices for selection. My code:

 var choices = new[] { "one", "two", "three" };
 PromptDialog.Choice<string>(context, OnSelected, choices, "Please select a number");

**Comment by alexyak** [comment]
Ok, for now I fixed it by adding another constructor to the Prompt<T> class:

` public Prompt(IEnumerable<T> options, string prompt, string retry, int attempts)
        {
            if (options != null && prompt != null)
            {
                var builder = new StringBuilder();
                builder.Append($"{prompt}\n");

                foreach (var option in options)
                {
                    builder.Append(option.ToString() + "\n");
                }

                this.prompt = builder.ToString();
            }
            else
            {
                SetField.NotNull(out this.prompt, nameof(prompt), prompt);
            }
            
            SetField.NotNull(out this.retry, nameof(retry), retry ?? prompt);
            this.attempts = attempts;
        }`

This may not be the best solution and the better one would be to just modify an existing constructor, but I didn't want to modify the code in all other implementations of the Promp<T> such as PrompConfirm, PromptString, etc...

**Comment by msft-shahins** [comment]
You can generate the right prompt string and retry prompt string based on your choices before instantiating the PromptDialog. A more general way to solve it is modifying the prompts to get a template for prompt string generation.

**Comment by alexyak** [comment]
I am sorry, but what do you mean? Could show a sample how to do it?
