### ISSUE TITLE
FormFlow functionality: Executing custom logic, sending custom reply and accessing bot state

### ISSUE THREAD

**Issue by jigneshs123** [Microsoft/BotBuilder#790]
I'm trying to see if I could run some custom business logic after certain field input is provided by the user, access context object, get/set Bot State (for e.g. PrivateConversationData), and send some custom message/attachments. Is it possible to do any of this while building Form?

It seems to have support for validating input and send text reply as message, but I'm looking to run some business logic to get/set state and therefore access context, and then send custom reply to user that could contain attachments etc. (basically reply). And possibly, use the bot state information to construct dynamic field?

Having something similar to what OnCompletionAsyncDelegate can do while user if filling the form would probably work but it seems like that is only fired OnCompletion.

**Comment by chrimc62** [comment]
ValidateAsync does allow you to get/set state, but does not allow you to send messages.  (Or rather you can return a string as feedback, but it does not allow attachments--this is a good idea and I will look into expanding what you can return.)  
You can dynamically construct fields, check out the documentation here: https://docs.botframework.com/en-us/csharp/builder/sdkreference/forms.html#dynamicFields

**Comment by chrimc62** [comment]
The new release out soon should allow you to return multiple choices which can generate one or more cards.  You can also return feedback that is richer than just text.

**Comment by jigneshs123** [comment]
Thanks @chrimc62 for reply and adding support for it. Looking forward to it. Btw, ValidateAsync only seem to give form state but not the context state (e.g. PrivateConversationData).

Is it possible to send attachment as part of form options or is that something going to be supported?

**Comment by dchumpitaz** [comment]
Hi @chrimc62, I'm trying to get values from the PrivateConversationData or UserData from the context in the ValidateAsync without success. It's possible access the context from ValidateAsync?

Hi @jigneshs123 , can you solve your issue?
