### ISSUE TITLE
Calling chat.update in Slack

### ISSUE THREAD

**Issue by MCKRUZ** [Microsoft/BotBuilder#792]
Is there any way besides a direct API call to call chat.update in slack.

https://api.slack.com/methods/chat.update

**Comment by craigjensen** [comment]
Currently, there is no way for a bot to call chat.update directly because we don't expose the slack token that you need to make the call.  What functionality are you looking to support that requires a call to chat.update?

**Comment by MCKRUZ** [comment]
Utilizing Chat.update you can update the message on the chat.  See this example.

 

https://medium.com/slack-developer-blog/message-buttons-and-the-slack-api-ab938174af70#.mzbcwirr6

**Comment by craigjensen** [comment]
Thanks for the feedback.  We're investigating how we can support this scenario in a future release.

**Comment by craigjensen** [comment]
We are working on an update that will send the token as part of the ChannelData on every message. You can then extract the token and make your own Slack RTM Api calls. The update should be published soon - hopefully in the next couple days.

**Comment by MCKRUZ** [comment]
Ok thank you Craig.
