### ISSUE TITLE
Id of an user on a channel

### ISSUE THREAD

**Issue by nexxuno** [Microsoft/BotBuilder#795]
Hello,
maybe this is a stupid question but I need to be sure for my project...
are user Ids granted on a given channel? I am developing a bot that uses the facebook channel, each user has an alphanumeric id, can this id change in time? (the doubt comes from the fact that I expected emails or phone numbers and not this random id). Can I use it to store user data in my DB and be sure that it won't change in time?

Another question which is related to the first one, how could I develop a bot that can switch between channels, i.e. serve a client on FB and then go on with skype if the user switches to it? I guess it is not feasible without some account management on my side that links the various identities of the user from each channel with a master account but maybe there was a well known approach to the problem.

Thank you for you time.

**Comment by msft-shahins** [comment]
@nexxuno user ids are stable for each channel and will not change. If you need to track a user across different channels, you need to implement an account linking mechanism across different channels, i.e. mapping user's facebook id to skype id.
