### ISSUE TITLE
Message Not recevied BOT To USER

### ISSUE THREAD

**Issue by safiresh** [Microsoft/BotBuilder#796]
Hi, 
I cant receive any messages from bot in my web.skype(dev) & mac skype too. My Bot working perfectly until Today 7AM [IST] . 
KIndly inform to use there is going on any maintenance work in Bot framework

**Comment by danmarshall** [comment]
hello @safiresh are you still seeing this issue?

**Comment by safiresh** [comment]
@danmarshall  No. Its resolved same day. But sometime message not delivered properly. This is rare scenario i cant find that. My bot used near 80 user and I got  minimum 2 issue from end user daily

**Comment by danmarshall** [comment]
Can you implement logging in your bot to help us know more about the issue?

**Comment by danmarshall** [comment]
I'm going to close this issue for now, but feel free to open a new issue for further discussion.
