### ISSUE TITLE
BotData not persisting

### ISSUE THREAD

**Issue by garypretty** [Microsoft/BotBuilder#798]
I have a LUISDialog where I am persisting some data to the conversationData store with the code below;

`context.ConversationData.SetValue("Name", r);`

but on subsequent calls when I call the following code from the MessagesController, the value of name is never populated.

`                    BotData conversationData = await stateClient.BotState.GetConversationDataAsync(activity.ChannelId, activity.From.Id);
                    var name = conversationData.GetProperty<string>("Name");`

I am running 3.0.1 from Nuget. Appreciate any help you can offer.

Gary

**Comment by NanashiGIT** [comment]
Had the same problem.
My solution was to use the IDialogContext, which has some functions to save data too.

**Comment by garypretty** [comment]
I am using the context within the LUISDialog, is that now what you are referring to?

**Comment by NanashiGIT** [comment]
Hm i only tried it with the IDialogContext that you get as a parameter while using normal Dialogs.
Im not sure about LUISDialogs, maybe those contexts also have the needed functions.
Just look whether the context has a BotData (or similar) property with get and set.

**Comment by NanashiGIT** [comment]
Just looked it up. The LUIS-Dialog Methods get the same context as the normal dialog methods.
So you should be fine.

**Comment by garypretty** [comment]
@willportnoy is this a known issuelyou have seen?  I seem to remember a similar issue being reported a short time ago but I cannot find it.

**Comment by willportnoy** [comment]
The IDialogContext bot data bags wrap the IStateClient interface, but we don't flush immediately on every write.  If you use IStateClient to go directly to the servers, you would see updates that are being held in memory until the dialog methods exit and the IDialogContext implementation flushes those updates to the durable store.

**Comment by garypretty** [comment]
Hi Will. Thanks for that.  How can I use the IStateClient in a LUIS dialog when I don't have the activity in order to create the state client?  Is there another way of creating an instance of the IStateClient?

**Comment by garypretty** [comment]
Actually, looks like I found my issue.  My mistake. All sorted. Thanks for your help :)
