### ISSUE TITLE
Skype web not showing cards if AttachmentLayout is "carousel"

### ISSUE THREAD

**Issue by manojkota** [Microsoft/BotBuilder#799]
Hi,

While playing with cards, I came to know that if I have one or more attachments, skype web & facebook messenger displaying the items as a list. If I change the AttachmentLayout to carousel like below, then carousel is working on facebook but it is not working in Skype. It is not at all showing any messages.

`replyToConversation.AttachmentLayout = AttachmentLayoutTypes.Carousel;`

**Comment by msft-shahins** [comment]
Carousel should work, unless you have more than 5 cards in your attachments. Skype ignores the messages that have more than 5 cards with carousel layout.

**Comment by manojkota** [comment]
Hey....Thanks for your help. That worked. But it is not at all showing any buttons. The same card carousel is working fine in Facebook messenger and when I clicked on the button it is returning the postback payload as well. This is not working in Skype.

**Comment by msft-shahins** [comment]
"postBack" is not supported by skype, use "imBack". [here](https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Samples/EchoBot/EchoAttachmentDialog.cs#L31) is a sample of a carousel working on skype.

**Comment by manojkota** [comment]
Hi,

I have changed "postBack" to "ActionTypes.ImBack". Now it is displaying the buttons. FB is still working and returning the channel data with payload value but skype is not returning the channel data. Skype is returning it as a message and no other information.

**Comment by msft-shahins** [comment]
That is the expected behavior with Skype. With the `imBack` Skype sends a message to the bot with the value of the clicked button in the text field.
