### ISSUE TITLE
Facebook messenger forbidden every other message

### ISSUE THREAD

**Issue by erlbe** [Microsoft/BotBuilder#801]
Without having touched the code or configurations over the weekend, my bot is forbidden to talk on Facebook messenger every few messages. 
When it is accepted, and when it gets rejected seems rather random.
![issue](https://cloud.githubusercontent.com/assets/6637964/17096004/9b1d0592-5257-11e6-83c9-e6fd8cb1afdb.png)

On other channels it works without errors. And when testing the connection in "My Bots" it is Accepted.

**Comment by msft-shahins** [comment]
@erlbe do you still see this issue? There was an issue with some of the JwtTokens issued by our Auth service over the weekend. This should be fixed now. What is the Microsoft App Id for your bot?

**Comment by erlbe** [comment]
@msft-shahins yes the issue is still there. It feels like it's 5 seconds with the connection working, then 5 seconds off.
The Microsoft App ID is: 1898cca9-1bab-434c-a0a8-5f1654fa54d3

**Comment by oztheozoz** [comment]
You should make sure to upgrade to the latest botbuilder 3.1.0. They added a fix for this.

**Comment by danmarshall** [comment]
I'm going to close this issue for now, but feel free to open a new issue for further discussion.
