### ISSUE TITLE
Skype Bot Calling not calling my api

### ISSUE THREAD

**Issue by mayuanyang** [Microsoft/BotBuilder#802]
I got my bot setup with the new api controller named CallingController with the following method

[Route("call")]
        public async Task<HttpResponseMessage> ProcessIncomingCallAsync()

I set the followings as the Calling Webhook, however they never get hit when i am making the call, any thought?
https://eddybot.azurewebsites.net/api/calling
https://eddybot.azurewebsites.net/api/calling/call

**Comment by msft-shahins** [comment]
Have you enabled calling for your bot in developer portal and registered the calling endpoint?

**Comment by mayuanyang** [comment]
Yes, when you say registered the calling endpoint, do you mean put the url in the Calling Webhook?

**Comment by msft-shahins** [comment]
yes. I recommend testing your bot's endpoints locally by sending a json to it using fiddler or postman and making sure that your endpoints in your controller are exposed correctly.

**Comment by mayuanyang** [comment]
I also try that by using postman, and the bot can handle the request with no problem

**Comment by mayuanyang** [comment]
Eventually i figured out what the problem is, my api controller is missing the [BotAuthentication] attribute, it is all good now

**Comment by Sid245439** [comment]
I am not getting what to set the 1:1 webhook in developer window of skype and in code. Please help
