### ISSUE TITLE
Test Connection ValidationException

### ISSUE THREAD

**Issue by Thegaram** [Microsoft/BotBuilder#804]
When clicking on *Test* in the *Test connection to your bot* section on my bot's admin page, sometimes I get `Accepted`, but sometimes I get the following validation error (coming from my service apparently).

```json
InternalServerError
{
  "message": "An error has occurred.",
  "exceptionMessage": "'activityId' cannot be null.",
  "exceptionType": "Microsoft.Rest.ValidationException",
  "stackTrace":
    "at Microsoft.Bot.Connector.Conversations.<ReplyToActivityWithHttpMessagesAsync>d__7.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n
     at Microsoft.Bot.Connector.ConversationsExtensions.<ReplyToActivityAsync>d__15.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n
     ..."
}
```

This suggests the `Activity` sent for testing the connection has no `activityId`, so the reply has no id either (but my service is reachable). I was wondering if this was intentional, or if this could mean there's a problem in the connection testing / my service / the bot SDK.

**Comment by saikrishnav** [comment]
I am also facing the same issue. I uploaded a bot in Bot Framework, but unable to publish due to this issue. 

When I test with my local machine and emulator, everything works. 
After uploading to Azure web apps, the URL provided by azure throws Internal Server Error (500). I am unsure what I am missing here.

**Comment by dandriscoll** [comment]
It looks like we're omitting the "Id" field on the activity we're sending, so I'll fix that.

**Comment by Andrea-Orimoto** [comment]
This has been fixed a while ago.
