### ISSUE TITLE
BadImage format exeception when compiling the sample bot code with other custom dlls

### ISSUE THREAD

**Issue by ramlnu** [Microsoft/BotBuilder#806]
I am trying to build in a custom dll that needs to  be built as x64 target platform. Compilation works fine but when I  launch the sample I see this:

Exception Details: System.BadImageFormatException: Could not load file or assembly 'ENSBot' or one of its dependencies. An attempt was made to load a program with an incorrect format in the browser.

When I  switch to "Any CPU" I get the same error for my custom DLLs that I am trying to build in.

Any help will be appreciated.

**Comment by willportnoy** [comment]
You need to consistently set the architecture of your assemblies to x64 or "any cpu" and make sure that the process is also x64 as well.

**Comment by willportnoy** [comment]
I'm going to close this issue, but feel free to open a new issue for further discussions.
