### ISSUE TITLE
Cannot create a message that doesn't include the @username mention in GroupMe

### ISSUE THREAD

**Issue by etriebe** [Microsoft/BotBuilder#807]
I cannot seem to get the framework to create a message that *doesn't* have an @ mention for the user who requested the message. I want to remove this so GroupMe will only post the URL of the image I'm trying to post so it automatically renders in the chat, as opposed to having the @ mention preceding the URL which will mean someone has to click on each link to view the image. 

`string url = "http://www.someurl.com";
Activity testActivity = activity.CreateReply($"Hey, I found the following image!");
await connector.Conversations.ReplyToActivityAsync(testActivity);

IMessageActivity newMessage = Activity.CreateMessageActivity();
newMessage.Type = ActivityTypes.Message;
newMessage.From = testActivity.From;
newMessage.Recipient = testActivity.Recipient;
newMessage.Conversation = testActivity.Conversation;
newMessage.TextFormat = "plain";
newMessage.Text = url;
await connector.Conversations.SendToConversationAsync((Activity) newMessage);
`

**Comment by LarsLiden** [comment]
Thank you.  We will address this issue in the next build.
