### ISSUE TITLE
Facebook channel status showing Error but its still working

### ISSUE THREAD

**Issue by wtam** [Microsoft/BotBuilder#808]
Though the facebook channel status suddenly show error (it was fine last week) below but the bot seems still working.  Could someone help to explain what's wrong and any consequence of this error?

Facebook Messenger status
Facebook graph API call failed with: BadRequest {"error":{"message":"(#100) Failed to fetch the file from the url","type":"OAuthException","code":100,"fbtrace_id":"DVZU7bscqxL"}}

This is my app id : 379a3e85-2a5b-4fa1-a1e7-45b6a9df278c

**Comment by msft-shahins** [comment]
It means that for some of the messages sent by your bot to Facebook, that error message is returned by Facebook graph API. 

``` json
     "error": {
         "message": "(#100) Failed to fetch the file from the url",
         "type": "OAuthException",
         "code": 100,
         "fbtrace_id": "DVZU7bscqxL"
     }
```

**Comment by will285** [comment]
how do you handle that?

**Comment by danmarshall** [comment]
Hi @wtam , sometimes your channel status may show the errors that happen intermittently, but if you refresh the page in the dev portal, you will get the current status.

**Comment by msft-shahins** [comment]
@will285 the errors from Facebook graph API calls will be relayed back to your bot in response of the POST your bot makes to connector API. You can log the messages in your bot that are causing these types of Facebook API failures. My guess is that the image attachment URL your bot sends in its attachment is not a valid URL and Facebook services return this error.

**Comment by wtam** [comment]
Thanks Dan Marshakll you're right, its back to normal again now, guess wait and refresh is the best solution for now
