### ISSUE TITLE
Simple Attachments on Skype Channel

### ISSUE THREAD

**Issue by XelaMon** [Microsoft/BotBuilder#809]
My bot attaches some messages to its activities before replying to a user. Right now, I have them all as the simple Media Attachment example with the ContentType, ContentUrl, and Name fields populated.

I have the bot exposed on Direct Line and some information about those attachments comes through on that channel. However, I have added my bot to the Skype channel and I don't see the attachments come through on that channel.

I am using the v3 version of the Bot Framework with the .NET Bot Builder. I am testing this on Skype Web with the developer options enabled.

**Comment by msft-shahins** [comment]
ContentUrl should be either `https` for skype or a valid [base64 encoded data url](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs)

**Comment by XelaMon** [comment]
Awesome, thanks!

**Comment by thingista** [comment]
@msft-shahins I might need to open a different issue, but it looks like there is a bug with the Skype channel if the base64 encoded data URL is above a certain length.

- if I send the same image to Slack it works fine
- if I send a smaller image to Skype it works

I am getting errors like this:

`Error: Request to 'https://skype.botframework.com/v3/conversations/xyz/activities' failed: [500] Internal Server Error`

**Comment by msft-shahins** [comment]
@thingista feel free to open a separate issue about this.

**Comment by vinodjoseph62** [comment]
What is the size limit for attachments using base64 encoded data url, because I am sending a 254kb file as attachment (base64 encoded) it always gives error : 400 bad request, but the same works fine in case of 25-30 KB files.
