### ISSUE TITLE
Question on stringbuilder in pizza.cs

### ISSUE THREAD

**Issue by bluekite2000** [Microsoft/BotBuilder#81]
Hi @willportnoy. Can you explain what tostring() in pizza.cs does? I see you dont have that in other sample projects.

**Comment by willportnoy** [comment]
It's a mechanism to make the output more readable.  The default ToString will serialize the class name.  This ToString override helps when the dialog writes the completed form back to the user.  The other samples either use the json serializer to make a string out of the completed form or don't output the completed form.
