### ISSUE TITLE
Skypebot: how to get sender timezone

### ISSUE THREAD

**Issue by Botship** [Microsoft/BotBuilder#813]
How can I get the local timezone information of the sender? There is name and Id  information in ChannelAccount. But don't see timezone info.

I am hoping to avoid asking the user that "1pm" is 1 PM PST and not UTC.

**Comment by LarsLiden** [comment]
Channels vary on whether they support location information. There is currently no way to get location information for users on Slack. Telegram, for instance, does. When location data is available it will returned in the Attachment data structure and in the channel's native format in the ChannelData field. Note that the user needs to opt into sending this data (to protect their privacy). The bot developer can send a message to the user requesting that they share their location data, but they cannot get it from the channel it w/o user action to share it.
