### ISSUE TITLE
Dialog property in LuisResult missing (preview mode) 

### ISSUE THREAD

**Issue by NTTLuke** [Microsoft/BotBuilder#814]
I updated Luis editor in preview mode that provides dialog property.
I'm using Dialog with LuisIntent attribute as shown in documentation.

```
[LuisIntent("TodoCreation")]
public async Task TodoCreation(IDialogContext context, LuisResult result){


}
```
When result comes back the dialog property is missing. 
I downloaded also preview nuget packages  but I didn't find anything.
I tried also to develop a custom DialogLuisResult class ( that inherits from LuisResult) with missing properties but it seems doesn't work

any suggestions?
Thx

**Comment by msft-shahins** [comment]
Luis preview features are not currently supported in builder's Luis dialog. You can either implement a custom dialog yourself that make calls to Luis preview API or use the builder's dialog system to achieve your goal of having a dialog started with the user given different intents.
