### ISSUE TITLE
How to handle Luis intent with several required action parameters (that are missing)

### ISSUE THREAD

**Issue by accelerande** [Microsoft/BotBuilder#815]
Setup:
1. We have two or more required action parameters.
2. (in Luis preview we can also set the Prompt for each parameter)
3. We have a LuisDialog with an LuisIntent handler member.
4. When checking the entities with TryFindEntity() they are always null/not found (when not entered in the message).

Questions:
1. The bot is not asking for the lacking parameters (even if the Prompts are set in Luis). Why? Is there a way to get the prompts automatically?
2. Or is there a simple way to ask for all the missing parameters in the LuisIntent handler method?
We have tried using PromptDialog with LINQ and calling another dialog (built with formbuilder) but nothing is easy/simple.

**Comment by msft-shahins** [comment]
Luis preview features are not currently supported in builder's Luis dialog. You can prompt the user using PromptDialog in the intent handler of builder's LuisDialog. You can look at [PizzaOrderDialog](https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Samples/PizzaBot/PizzaOrderDialog.cs#L32) on how it starts a new Form based on "pizza order" intent or [SimpleAlarmDialog](https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Samples/SimpleAlarmBot/SimpleAlarmDialog.cs#L174) on how it prompts the user.
