### ISSUE TITLE
SimpleIVRBot

### ISSUE THREAD

**Issue by falvarezoliva** [Microsoft/BotBuilder#817]
I´m trying to startup the SimpleIVRBot proyect. I´have register the bot using ngrok url as follow

Messaging endpoint
https://f0103bea.ngrok.io/api/calling/call

Under skype configuration form:
Calling Webhook
https://f0103bea.ngrok.io/api/calling/callback

Nothing happens when make a call with Skype. When I send text the code breaks on function
 [Route("callback")]
        public async Task<HttpResponseMessage> ProcessCallingEventAsync()
        {
            return await CallingConversation.SendAsync(Request, CallRequestType.CallingEvent);
        }

but an exception ocurred with message "Required property 'participants' not found in JSON. Path '', line 37, position 1."

**Comment by falvarezoliva** [comment]
The problem was on skype profesional. On web Skype version the param OperationOutcome is missing.

**Comment by msft-shahins** [comment]
https://f0103bea.ngrok.io/api/calling/call should be your calling webhook under skype configuration and https://f0103bea.ngrok.io/api/calling/callback should be in your web.config [CallbackUrl](https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Samples/SimpleIVRBot/Web.config#L12).
