### ISSUE TITLE
Replies not reaching user on Skype

### ISSUE THREAD

**Issue by Thegaram** [Microsoft/BotBuilder#818]
Although last week it worked fine, my bot's replies to the Skype Channel don't reach the user now. There's no exception from my service. The bot admin page first said:

```Calls to your bot are failing with: ArgumentNullException Value cannot be null. Parameter name: message```

and now:

```Calls to your bot are failing with: BotException POST to [botname] failed: A task was canceled.```

This issue is probably related to #455. As there's no exception from my code, and the same code worked well last week, I suppose the error was introduced by some recent changes to the Skype Connector Service.

**Comment by Thegaram** [comment]
After disabling and reenabling the Skype channel it works again. I'm not sure I should close the issue though, the problem causing this is still not solved I suppose.

**Comment by danmarshall** [comment]
Thanks @Thegaram , we will close this issue, but please open a new issue if you see this again.
