### ISSUE TITLE
Direct Line Duplicates Posting Messages

### ISSUE THREAD

**Issue by XelaMon** [Microsoft/BotBuilder#819]
I seem to be having an issue with Direct Line after upgrading to v3 of the Bot Framework. I am getting duplicates of messages that I post using Direct Line.

I've run a remote debugger and noticed that, when I send a message through Direct Line, multiple copies of the message are posted to my bot. Each of these activities have the same text field, but have different IDs and timestamps.

As far as I can tell, this only happens on Direct Line (I don't have any other channels set up, but this isn't happening on the emulator either locally or in the cloud) and only happens when I send the first message in a Direct Line conversation.

I am currently interacting with Direct Line using the published .NET Client Library (1.0.2) and this was not a problem when I was using v1 on the same version of the Client Library.

**Comment by XelaMon** [comment]
Some more updates, it seems that this issue isn't necessarily linked to a new Direct Line conversation. When I first use the emulator to make the first message to the bot after restarting my web server, and then use a Direct Line client to make another request, everything works fine.

The problem seems to be when a message is sent to the bot which causes the web server it is on to move out of a suspended state. My bot has to load about 3 GB of data into memory on the first request to it so that I can answer queries. This process takes somewhere between 20 seconds and a minute.

Perhaps Direct Line is noticing that the bot isn't responding within a certain period of time, and then sending a duplicate message to try and get a response? It seems to be a Direct Line specific issue. I just added my bot to the Skype channel as a test, and am not running into the same issue.

**Comment by danmarshall** [comment]
Hi @XelaMon this does sound like an HTTP retry issue. If your responses take a long time perhaps you should consider returning a 204 No Content and then replying later.

**Comment by msft-shahins** [comment]
@XelaMon current implementation that you are describing makes your bot to look unresponsive when first message is coming to your bot. As @danmarshall suggested you should send a 204 and probably an optional message that the bot is warming up. Then send the response whenever your bot is ready as a proactive message to the user.

**Comment by jamesaarondevlin** [comment]
Hey @XelaMon - how'd you go with this?

I'm noticing the same behaviour using DirectLine V3. I'm using React with DirectLineJS to interface with my bot. What I am seeing is multiple messages being sent, the knock-on effect being that my client receives multiple messages back from the bot. If I interact with my bot using the emulator I do not notice this behaviour.

I have tried returning HTTP 204 which made no difference. I have confirmed my suspicion that my application is receiving multiple calls from DirectLine by using Application Insights.

I was wondering if you found any other areas worth investigating as part of this. I will continue investigating my own area and if I found a solution I will post it here.

Best regards,
James

**Comment by an0o0nym** [comment]
Well done!

**Comment by vishnuvardhanpatel1** [comment]
I had faced the same issue. But it wasnt because of the Direct line API issue. It was because of code issue. I will explain here with few code snippets.
While starting conversation string value user = "testuser" was being passed for the given conversation id.

public async Task StartConversationAsync(string user)
        {
            var conversation = await client.Conversations.StartConversationAsync();
            Activity userMessage = new Activity
            {
                From = new ChannelAccount(user),
                Text = user,
                Type = ActivityTypes.Message
            };
            await client.Conversations.PostActivityAsync(conversation.ConversationId, userMessage);
        }

And while sending messages post the conversation was initialized, string value user = "testuser@xyz.com" was being passed for the same conversation id. Due to which the conversation was getting initilized twice for same conversation id but different user resulting into duplicate messages from bot service for same conversation id. 
public async Task SendMessageAsync(string text, string user, string conversationId)
        {
            Activity userMessage = new Activity
            {
                From = new ChannelAccount(user),
                Text = text,                
                Type = ActivityTypes.Message
            };
            await client.Conversations.PostActivityAsync(conversationId, userMessage);
        }

Phew, It took me 3 days to rectify this silly mistake :)
