### ISSUE TITLE
Setting state twice results in 404

### ISSUE THREAD

**Issue by Thegaram** [Microsoft/BotBuilder#820]
I have this code for resetting the bot state:

``` c#
StateClient sc = activity.GetStateClient();
BotData botData = new BotData(eTag: "*");
await sc.BotState.SetPrivateConversationDataAsync(activity.ChannelId, activity.Conversation.Id, activity.From.Id, botData);
```

If I reach this part once, everything works fine and the bot's state is reset. If I reach these lines again without setting the state, the third line throws an exception:

```
{
  Request: {
    Method: POST,
    RequestUri: https://state.botframework.com/v3/botstate/groupme/conversations/22764295/users/39013361,
    Version: 1.1,
    Headers: {
      User-Agent: Microsoft.Bot.Connector.StateClient/3.0.0.0,
      Authorization: Bearer ...,
      Content-Type: application/json; charset=utf-8,
      ...
    },
    ...
  },
  Response: {
    StatusCode: 404,
    ReasonPhrase: 'Not Found',
    Version: 1.1,
    ...
  }
}
```

Experienced this on multiple channels (tested on Skype, Slack, Kik, GroupMe). This behavior doesn't seem correct to me, am I missing something? Also, this started happening this week. This part in the documentation suggests I should get `null` instead of an error:

> NOTE: If the record doesn't exist, it will return a new BotData() record with a null .Data field and an ETag = "*", so that is suitable for changing and passing back to be saved

After the exception the bot's admin page says `POST to [botname] failed: A task was canceled` or `BotException: POST to [botname] failed: A task was canceled. TaskCanceledException: A task was canceled` or `Calls to your bot are failing with: BotException POST to [botname] failed: A task was canceled`, so the issue might be related to #455.

**Comment by Andrea-Orimoto** [comment]
@Thegaram is this still an issue?

**Comment by Thegaram** [comment]
Yes, it's throwing a `Microsoft.Rest.HttpOperationException`. It's coming from the `ErrorHandling.HandleError` `HttpOperationResponse` extension. I'm not sure if this is by design, but it's definitely not the behavior specified in the docs.

**Comment by tomlm** [comment]
This is fixed and should be deployed to our server soon
