### ISSUE TITLE
Problems with Facebook Messenger Channel

### ISSUE THREAD

**Issue by oztheozoz** [Microsoft/BotBuilder#822]
I am running node and BotBuilder 3.1.1
Last week I was able to run the bot demo-skype which is one of BotBuilder's demo apps on Skype and FB Messenger. This week I am able to run demo-skype on the Skype channel but it won't run consistently on the Facebook Messenger Channel. It runs for a couple of messages and then the message never reaches my bot server.

To reproduce:
1) Start up the demo-skype app under BotBuilder/Node/examples/demo-skype/app.js
2) Go to your FB developers page and unsubscribe your FB page from your app and then subscribe. The purpose of doing this is that it makes the FB Messenger channel work for a couple of messages.
3) Go to FB messenger on your phone (I have v80 on iOS) or on the web and start interacting with the demo bot. Go through all the menu demo items. You should reach a point where your message is sent but you receive no response. You have to repeat step 2 again before things start working again for a little while. 

Some notes and thoughts:
- I hooked up my debugger to ChatConnector.js line 40 where the request finishes coming in and verified after the first few successful messages, I receive no more requests. This tells me there may be something wrong on the MS - FB side of things.
- The Skype channel still works normally.

**Comment by jonathanhds** [comment]
+1

**Comment by msft-shahins** [comment]
@oztheozoz and @jonathanhds can you share Microsoft App Id for the bot that you are seeing this issue with?

**Comment by oztheozoz** [comment]
It actually works again for me today. @jonathanhds , does it work for you?

**Comment by jonathanhds** [comment]
It's working here as well. Feel free to close this issue!
