### ISSUE TITLE
PromptDialog.Confirm doesn't show up properly on Skype web app or skype desktop client

### ISSUE THREAD

**Issue by satheeshravi** [Microsoft/BotBuilder#824]
Hello,

I am working with PromptDialog.Confirm styled dialog prompt and noticed that it doesn't render properly on desktop skype/SkypeWebApp. But it does properly render the buttons in Iphone's skype  app.
I had the PromptStyle set to PromptStyle.Auto. 

Kindly look into this and let me know.

Thanks in advance.

**Comment by alex182** [comment]
I have the same issue, the only way to get the prompt to render properly is to the use the development version of skype web chat  

https://web.skype.com/en/?ecsoverride=developer

**Comment by SamuelTassell** [comment]
It's just the way it is at the moment I'm afraid until it gets pushed to the other versions of Skype.

**Comment by b4usat** [comment]
Even the buttons are not rendering in Embeded Web Chat control. But working perfectly with Emulator v3 version

**Comment by msft-shahins** [comment]
I guess with the release of Skype clients with card support this is issue is resolved. Feel free to open another issue if you still see this issue.
