### ISSUE TITLE
Generic Questions with Bot framework

### ISSUE THREAD

**Issue by satheeshravi** [Microsoft/BotBuilder#825]
Hello,

I have got couple of quick questions:

1. Is there any possible way to get the current geo location of the user ? (I am using skype in this case)
2. I was investigating at the "Locale" property in the _Microsoft.Bot.Connector.Activity_ object inside the Post method(MessageController.cs). 
value of "Locale" property was null. Is this expected ? Shouldn't it be having the language code of the message from the user ?

Thanks in advance.

**Comment by LarsLiden** [comment]
Channels vary on whether they support location information. There is currently no way to get location information for users on Slack. Telegram, for instance, does. When location data is available it will returned in the Attachment data structure and in the channel's native format in the ChannelData field. Note that the user needs to opt into sending this data (to protect their privacy). The bot developer can send a message to the user requesting that they share their location data, but they cannot get it from the channel it w/o user action to share it.

**Comment by satheeshravi** [comment]
@LarsLiden : Thanks for your reply. I am using skype as the channel. I am aware that the user needs to give permission to share the location, but I didn't find clear instructions on how to prompt for sharing the location from the user.

**Comment by palashjhabak** [comment]
Hi @satheeshravi  and @LarsLiden any further update on this ? I could not find any mention of location sharing in skype bot documentation, nor could I find the location sharing icon in my skype when I interact with a bot. Although its present when chatting with other skype non-bot users. 

Thanks,
Palash

**Comment by LarsLiden** [comment]
You cannot find the icon because the Skype channel currently does not support sharing of location.  @nickcordrey

**Comment by vrnmthr** [comment]
Possibly reopening this issue? Since Skype does now support sharing of location (on Android mobile for instance)
