### ISSUE TITLE
`session.privateConversationData`never expires in Slack channel

### ISSUE THREAD

**Issue by javi-jamaa** [Microsoft/BotBuilder#827]
Hi 
The data stored in `session.privateConversationData`never expires even I log off from Slack app.
BR
Javier

**Comment by dandriscoll** [comment]
Hi @javi-jamaa, privateConversationData is controlled by the conversation lifetime, not whether or not you are logged in to Slack. The conversation lifetime in Slack is very long -- if you're in a channel, it's the lifetime of that channel; if you're in a direct-message conversation, it's the lifetime of the user account.

If you would like your bot to expire its privateConversationData, you could add a timestamp whenever you write it, and compare the timestamp with an expiration whenever you read it.

**Comment by dandriscoll** [comment]
Please feel free to open a new issue if you have further questions. Thanks!
