### ISSUE TITLE
BotConnector API

### ISSUE THREAD

**Issue by mikkhait** [Microsoft/BotBuilder#83]
This might not be the right place to ask this but nevertheless. Is there a plan for BotConnector API?

So that we can register bots on the BotFramework portal programmatically?

**Comment by jameslew** [comment]
We have heard that suggestion and are considering it; we definitely think it would be a valuable addition to our service.  I don't currently have a timeline for you however.

Thanks!

**Comment by mikkhait** [comment]
Thanks. I would recommend keeping this thread opens so people can watch as things develop.

**Comment by Stevenic** [comment]
Moved to UserVoice:

https://feedback.botframework.com/forums/354219-bot-connector/suggestions/13463493-botconnector-publish-api
