### ISSUE TITLE
Getting ERROR: ChatConnector: receive - invalid token. Check bots app ID & Password with every message.

### ISSUE THREAD

**Issue by vlttnv** [Microsoft/BotBuilder#830]
After upgrading to `v3.1.1` is tarted getting `ERROR: ChatConnector: receive - invalid token. Check bots app ID & Password` on every received message.
This started happening with no change in the code or any modification.

#742 claims that the fix is in `v3.1.1`

**Comment by msft-shahins** [comment]
This means that you don't have your bot configured with the right Microsoft App Id and Password. As a result we cannot validate JwtTokens sent to your bot. [Here](https://docs.botframework.com/en-us/support/troubleshooting-bot-framework-authentication/#navtitle) is a step by step troubleshoot guide for auth issues.

**Comment by vlttnv** [comment]
I had a working bot for several weeks then once I updated the npm package to `v.3.1.1` it started happening. I verified a few times that I am using the correct credentials and I also created a second bot with completely new credentials. It still happens.
This is how I add the credentials to the configuration:
```
var connector = new builder.ChatConnector({
    appId: process.env.MICROSOFT_APP_ID,
    appPassword: process.env.MICROSOFT_APP_PASSWORD
});
```

Am I doing something wrong?

**Comment by stijnvdb88** [comment]
If everything is definitely configured correctly, be sure to confirm your (or whatever machine your bot is running on) system time is accurate.
Three hours of my life I'll never get back.

**Comment by graphnode** [comment]
I'm also having the same problem. I double checked and triple checked the credentials and the time. 
The jwt.verify function in ChatConnector always fails.

**Comment by Andrea-Orimoto** [comment]
@vlttnv I'm assuming you solved this issue, if not please reopen. Thanks!

**Comment by loretoparisi** [comment]
@Andrea-Orimoto I'm still facing this issue in https://github.com/Microsoft/BotBuilder/issues/710#issuecomment-351025956

**Comment by vlttnv** [comment]
@loretoparisi Are you running this in docker? I was experiencing clock drift in my containers. Google for `docker clock/time drift` and you see some solutions.
