### ISSUE TITLE
[NodeSDK] Sending messages via Skype with <> does not work

### ISSUE THREAD

**Issue by frisco82** [Microsoft/BotBuilder#831]
I have tried xml escaping, as it was needed in Skype, it does not work but it does fix the error on the bot framework simulator.

**Comment by Thegaram** [comment]
What is it exactly that you'r experiencing? It sounds like it's because the default formatting is Markdown. (Similar as in #696.)

**Comment by frisco82** [comment]
The behaviour has changed, unescaped I get an exception like this:

> server-0 Error: Request to 'https://skype.botframework.com/v3/conversations/29%3A1NXxqy1VAjKzicqM5Cb-Eam7lh7LTQ3I8e0jRqqVrijI/activities' failed: [400] Bad Request
server-0     at Request._callback (/home/frisco/node/skype-bot/node_modules/botbuilder/lib/bots/ChatConnector.js:356:46)

If I use xml escaping then depending on the message it is shown correctly others it shows the message escaped.

This is being shown correctly: 
```
  Usage:  [options] [command]
  Commands:
help [cmd]                                display help for [cmd]
codinglove                                send random coding love gif
btc [options]                             Gets latest Bitcoin price
ltc [options]                             Gets latest Litecoin price
eth [options]                             Gets latest Ethereum price
coin [options] <base coin> [target coin]  Gets trade price for a coin pair, if target is not set USD will be used
cron                                      Program commands
abstract [topic]                          Returns an abstract on any topic
flip                                      Bot flips the table 
hello [name]                              Typical hello world
meme [options] <id> <"text1"> ["text2"]   Create a meme
ping                                      Echo
rain [options] [city]                     Check if it is raining in a city (Madrid by default) use --CP for postal code search
  Options:
-h, --help  output usage information
```

This one shows the text still escaped (it is :

```
error: missing required argument &quot;text1&quot;
 Usage: meme [options] &lt;id&gt; &lt;&quot;text1&quot;&gt; [&quot;text2&quot;]
   Create a meme
  Options:
-h, --help  output usage information
-l, --link  Returns the link instead of sending the image
```


I am using the same function to send both of them:
`session.send(entities.encodeXML(msg));`

The last day I tried (on monday) I was getting the error escaped or unescaped.

**Comment by chrimc62** [comment]
Closing because of age.  If you are still having an issue please raise the issue again.
