### ISSUE TITLE
Activity.From does not support user profile information

### ISSUE THREAD

**Issue by brentzucker** [Microsoft/BotBuilder#835]
Activity.From supports Id and Name (Screen Name) but not other user information like email, first name, last name even though it is provided in the messaging API's. 

For example: https://api.slack.com/types/user returns 
{
    "id": "U023BECGF",
    "name": "bobby",
    "deleted": false,
    "color": "9f69e7",
    "profile": {
        "**first_name**": "Bobby",
        "**last_name**": "Tables",
        "**real_name**": "Bobby Tables",
        "**email**": "bobby@slack.com",
        "**skype**": "my-skype-name",
        "**phone**": "+1 (123) 456 7890",
        "image_24": "https:\/\/...",
        "image_32": "https:\/\/...",
        "image_48": "https:\/\/...",
        "image_72": "https:\/\/...",
        "image_192": "https:\/\/...",
        "image_512": "https:\/\/..."
    },
    "is_admin": true,
    "is_owner": true,
    "is_primary_owner": true,
    "is_restricted": false,
    "is_ultra_restricted": false,
    "has_2fa": false,
    "two_factor_type": 'sms',
    "has_files": true
}

This user profile information (first name, last name, email, phone, etc) currently is not accessible within the bot framework even though the API supports it.

**Comment by craigjensen** [comment]
We are working on an update that will send the Slack token as part of the ChannelData on every message. You can then extract the token and make your own Slack RTM Api calls. The update should be published soon - hopefully in the next couple days.

**Comment by craigjensen** [comment]
Update is deployed in production.  Please give it a try and reopen if needed.
