### ISSUE TITLE
skype carousel playing video using CardAction of type playVideo

### ISSUE THREAD

**Issue by ronnelsantiago** [Microsoft/BotBuilder#838]
I have a CardAction that i want to display in a carousel and i have set the cardaction type as playVideo and its value as a valid https url for the mp4 to play but i could not get it to work.. anyone manage to get this playVideo working? how is this suppose to work?

```csharp
var reply = context.MakeMessage();
reply.Text = "some text here";
reply.Attachments = new List < Attachment > ();
var actions = new List < CardAction > ();
for (int i = 0; i < 2; i++) {
    actions.Add(new CardAction {
        Title = "Play Video",
        Value = "https://server.com/iknowthisisavalidvideofile.mp4",
        Type = ActionTypes.PlayVideo
    });
}
reply.AttachmentLayout = AttachmentLayoutTypes.Carousel;
for (int i = 0; i < 5; i++) {
    reply.Attachments.Add(new HeroCard {
        Title = $ "{i}. Velit nonumy dolor in amet eros laoreet ipsum nonumy soluta",
        Subtitle = $ "{i}. Word this plutonian more window il raven no nevermore faster",
        Buttons = actions
    }.ToAttachment());
}
await context.PostAsync(reply);
context.Wait(MessageReceived);
```
this is what i would see if i run it on https://web.skype.com/en/?ecsoverride=developer 
![capture](https://cloud.githubusercontent.com/assets/1751062/17198140/49a20968-54b6-11e6-8706-b1c64e062ea8.JPG)

on a skype mac client this is what i can see but when i click on the play video button nothing is happening
![untitled picture](https://cloud.githubusercontent.com/assets/1751062/17198229/e9a96cda-54b6-11e6-8db3-698718e81683.png)

and this is what the bot emulator spits out to me
```json
"attachments": [{
    "contentType": "application/vnd.microsoft.card.hero",
    "content": {
        "title": "0. Velit nonum ....",
        "subtitle": "0. Word this plutonian more ....",
        "buttons": [{
            "type": "playVideo",
            "title": "Play Video",
            "value": "https://server.com/iknowthisisavalidvideofile.mp4"
        }]
    }
}]
```
can someone from the team please give me a bit of guidance here... little help @Stevenic ??

**Comment by ronnelsantiago** [comment]
maybe @msft-shahins you could help? would appreciate it if you could at least pass this to skype devs? TIA

**Comment by ronnelsantiago** [comment]
Today I have updated my windows skype client to 7.26.**_80_**.101 the type playVideo now actually opens the browser and plays the video.. which is good.. now my question is.. any plans on actually playing to video on the same conversation skype window? how does the playVideo type supposed to work?

note: i have win skype client version 7.26.**0**.101 and invoking the "check updates" button within skype did not pull down the new version of 7.26.**80**.101.. i have to download the 7.26.**80**.101 installer for me to get the latest build.

**Comment by nickcordrey** [comment]
Unfortunately playing video in a Skype card is not yet supported. You will need to send video as regular attachments instead.

**Comment by ronnelsantiago** [comment]
but if supported what is the behavior to expect? i just want to know so that i can gear my bot towards it in the future.. i have a requirement to have it played on the same skype conversation window.. let me know

**Comment by msft-shahins** [comment]
Playing video in a Skype card is not supported.

**Comment by ronnelsantiago** [comment]
can u at least let us know whether or not this will be supported soon or will be added on your backlog? this kind of information is important to me so just give an indication of whether this feature will be supported at all in the near future..
