### ISSUE TITLE
PromptDialog.Confirm is functionally incorrect in Group conversations in skype

### ISSUE THREAD

**Issue by satheeshravi** [Microsoft/BotBuilder#839]
Hi,

I was facing another issue with PromptDialog.Confirm.
When yes or no is replied to the PromptDialog (like @(Bot) yes) in a group conversation - it doesn't treat the response as a valid response.

But in a 1-1 conversation window, it works fine. 
Note: I used Skype web app for this.

Thanks in advance for looking into this.

**Comment by danmarshall** [comment]
Hi @satheeshravi , are you still seeing this issue?

**Comment by satheeshravi** [comment]
When I tried couple of days back, it still had this issue. Is there a fix pushed for this, during this week ?

**Comment by danmarshall** [comment]
Yes, Skype has released an update.

**Comment by Andrea-Orimoto** [comment]
@satheeshravi was this fixed?

**Comment by satheeshravi** [comment]
@Andrea-Orimoto : Sorry about the delay. I will try it out and update you folks by the weekend.

**Comment by Andrea-Orimoto** [comment]
@satheeshravi did you have a chance to look at this?

**Comment by dandriscoll** [comment]
Hi @satheeshravi, if you see this problem, please open a new issue. Thanks!
