### ISSUE TITLE
microsoft nodejs skype bot issue on azure

### ISSUE THREAD

**Issue by subhans3tech** [Microsoft/BotBuilder#841]
I want to deploy nodejs skype bot on azure but it give me 5xx error anyhelp how to remove 5xx error should be appreciated

**Comment by Thegaram** [comment]
Please give more details. What gives the error? Which channel did you test it on? What's the error message on the bot admin site? Did you correctly configure your https endpoint and your credentials? Can you reach your endpoint manually (e.g. with Fiddler)? 500 can mean that your code threw an exception.

**Comment by subhans3tech** [comment]
*this is my code it run perfectly fine with ngrok but at the end if I
uncomment these two lines for azure it also not work in ngrok  *
 that are underlined
var express = require('express'),
  config = require('./config/config');

var app = express();

require('./config/express')(app, config);

const fs = require('fs');
const restify = require('restify');
const skype = require('skype-sdk');
var builder = require('botbuilder');
var dialog = new builder.LuisDialog('
https://api.projectoxford.ai/luis/v1/application?id=&q=');
/*********************get json response from lui ***************/
var request = require("request")
var dt=
"computer reply",data_question="your ParametreNAme was ";
var question ;
var user_replied="";

var url1="https://api.projectoxford.ai/luis/v1/application/preview?id=&q="

/**********************************************************************************/
const botService = new skype.BotService({
    messaging: {
        botId:'baf92f40-2a99-4893-98b9-a5c655172d72',
        serverUrl : "https://apis.skype.com",
        requestTimeout : 15000,
     // for skpe
      appId:'baf92f40-2a99-4893-98b9-a5c655172d72',
//for simple    appId:'592af334-739f-4c3a-b385-06d5fbf088d6',
       //for skype
        appSecret:'
         // for simple  appSecret:'t'
}
});


/***************************lui id and
key*********************************************/
/* 6f23f938-4331-4302-86cc-f37568027ba5 lui key
c85fbd7acac043ca98eea345e3648fd4
***************************************************************************************/

 botService.on('contactAdded', (bot, data) => {

    bot.reply(`Hello ${data.fromDisplayName}!`, true);
});
var user_id="";
botService.on('personalMessage', (bot, data) => {

var flag=0;

 var url2 =url1+data.content;

url2+="&contextId=";
url2+=user_id;

  request({
    url: url2,
    json: true
}, function (error, response, body) {

    if (!error && response.statusCode === 200) {

data_question+=body.dialog.parameterName;
//dt+=data_question;
question=body.query;
        if(body.dialog.status=="Finished")
flag=1;
//sleep(1000);
question+=dt;
user_id=body.dialog.contextId;
dt+=body.dialog.prompt;
//console.log(dt);
    }
if(flag==0)
{bot.reply(dt, true);
}else
{ bot.reply("thanks for you cooperation please ask question if you need any
help", true);
flag=0;
user_id="";
}
 dt="somo ask ";

})


//url2=url1;

});

const server = restify.createServer();

*// Uncomment following lines to enable https verification for Azure.*
*/*  server.use(skype.ensureHttps(false, 404));/*these line when i un
comment code did not work */*
*server.use(skype.verifySkypeCert({}));    */*
server.post('https://skypeluis.azurewebsites.net/v1/chat',
skype.messagingHandler(botService));
const port = process.env.PORT || 8080;
server.listen(port);
console.log('Listening for incoming requests on port ' + port);

**Comment by Thegaram** [comment]
Please format your code properly, it's very hard to make sense of it this way. (See https://help.github.com/articles/creating-and-highlighting-code-blocks/.)

Your question does not seem relevant to the Bot Builder SDK as you're not using it. You only use it to create a dialog which you don't use afterwards (or am I missing something?). Please follow the Getting Started guide in the documentation to create a bot using the SDK. If you follow the steps there, it should work. (https://docs.botframework.com/en-us/node/builder/overview/#navtitle)

**Comment by subhans3tech** [comment]
this is my simple code that i want to deploy but it give me same error 401
 i am using same key and password please tell me what i am doing wrong




var restify = require('restify');
var builder = require('botbuilder');

//=========================================================
// Bot Setup
//=========================================================

// Setup Restify Server
var server = restify.createServer();
server.listen(process.env.port || process.env.PORT || 3978, function () {
   console.log('%s listening to %s', server.name, server.url);
});

// Create chat bot
var connector = new builder.ChatConnector({
    appId: '7b0135b8-ea7b-4cb0-',
    appPassword: 'tegtVbYoA6T'
});
var bot = new builder.UniversalBot(connector);
server.post('/api/messages', connector.listen());

//=========================================================
// Bots Dialogs
//=========================================================

bot.dialog('/', function (session) {
    session.send("Hello World");
});

**Comment by Thegaram** [comment]
Let's review your scenario.

1. You register a bot on `dev.botframework.com`, creating a Microsoft App ID (e.g. "ABC") and password (e.g. "XYZ").

2. You write the code above. You make your server listen on port 3978 for POST requests on `/api/messages`, and also replace the credentials like this:

    ```js
    var connector = new builder.ChatConnector({
        appId: 'ABC',
        appPassword: 'XYZ'
    });
    ```

3.  You run your code locally and make it available using ngrok (`ngrok http 3978`).

4. You go to your bot registration and change *Messaging endpoint* to the HTTPS URL ngrok gave you including your messaging path (e.g. `https://92832de0.ngrok.io/api/messages`).

What happens if you test your bot with a channel (e.g. Skype)? What happens when you try to access your endpoint using the emulator?

**Comment by subhans3tech** [comment]
when i run it on my emulator it gives me 401 authentication error and in
skype channel it did not reply me back

On Mon, Aug 1, 2016 at 10:13 PM, Péter Garamvölgyi <notifications@github.com

**Comment by subhans3tech** [comment]
when i test it from bot test button it is successful but when i test it on
emulator when i sen message it give me error of 401  un authorized

**Comment by Thegaram** [comment]
Are you sure the emulator is configured properly? Can you share a screenshot of your emulator window?

**Comment by danmarshall** [comment]
It this really your appid?
```
appId: '7b0135b8-ea7b-4cb0-',
```

**Comment by Andrea-Orimoto** [comment]
@subhans3tech are you still having this issue? was the appid correct?

**Comment by Andrea-Orimoto** [comment]
@subhans3tech I'm closing this issue, I'm assuming it was due to a wrong appId. Please reopen it if the problem still persists and you need more help. Thanks!

**Comment by subhans3tech** [comment]
please can you guide me how can i authenticate the user in microsoft  bot
on skype channel
by using azure active directory
