### ISSUE TITLE
Information about who added the bot to a group is missing

### ISSUE THREAD

**Issue by berhir** [Microsoft/BotBuilder#843]
We have started to upgrade our bot from V1 to V3. It is essential for our use case to know who added the bot to a group.

In V1 we were able to extract this information in different ways on telegram, slack and skype. For slack we got this information from the ChannelData field in the BotAddedToConversation event. But in V3 the ChannelData field is not set on activities of type conversationUpdate. And the From-field contains the bot (who is also the recipient).

Can you add the ChannelData field to activities of type conversationUpdate? There might be more scenarios where it is helpful to have this additional information.
And why does the From-field contain the bot and not the user who initiated the activity? Same problem exists on slack when you add another user. The From-field contains the user who was added instead of the user who added the new member. But this works correctly on telegram for example.

For now this is a show-stopper for us to upgrade to V3.

**Comment by eanders-MS** [comment]
Sounds like a bug. Thank you for reporting. I will investigate.

**Comment by eanders-MS** [comment]
@berhir Thanks for your patience. This has been fixed internally. Telegram's conversationUpdate messages will now include ChannelData. This fix will go live the with the next push to production. We typically update production every week or so.
