### ISSUE TITLE
Issues with the Bot Builder SDK 3.0.1

### ISSUE THREAD

**Issue by Andy-Tarasov** [Microsoft/BotBuilder#844]
Hello.
I'm using last version 3.0.1 of Bot Builder SDK from [nuget](https://www.nuget.org/packages/Microsoft.Bot.Builder/3.0.1)

1st issue:
Skype channel. Action type = postBack. From docs: "Text of message which client will post to bot. 
Client applications **will not display** this message". But it's not true. When I click button with postBack type, I see postBack messege.

2nd issue:
Skype channel. When using the buttons on the carousel has problems. Buttons with the type of postBack does not send message in the my webhook. And if use buttons with the type of openUrl, then this carousel does not appear in Skype. If I use a AttachmentLayoutTypes.List, then everything is OK.

`var connector = new ConnectorClient(new Uri(IncomingMessage.serviceUrl), AppId, AppPassword);

var newMessage = Activity.CreateMessageActivity();
newMessage.Recipient = new ChannelAccount() { Id = IncomingMessage.from.id, Name = IncomingMessage.from.name };
newMessage.Type = "message";
newMessage.Attachments = new List<Attachment>();
newMessage.Conversation = new ConversationAccount() { Id = IncomingMessage.conversation.id, IsGroup = false, Name = "" };

foreach (var slider in userResponse.sliders)
{
    List<CardAction> cardButtons = new List<CardAction>();

    for (int i = 0; i < slider.buttons.Count(); i++)
    {
        CardAction plButton = new CardAction()
        {
            Value = (slider.buttons[i].type.Contains("web_url")) ? slider.buttons[i].url : slider.buttons[i].payload,
            Type = slider.buttons[i].type.Replace("web_url", "openUrl").Replace("postback", "postBack"),
            Title = slider.buttons[i].title
        };
        cardButtons.Add(plButton);
    }

    List<CardImage> cardImages = new List<CardImage>();
    cardImages.Add(new CardImage(url: slider.image_url));

    HeroCard heroCard = new HeroCard()
    {
        Title = slider.title,
        Subtitle = slider.subtitle,
        Images = cardImages,
        Buttons = cardButtons
    };
    Attachment attachment = heroCard.ToAttachment();
                    
    newMessage.Attachments.Add(attachment);
}

**newMessage.AttachmentLayout = AttachmentLayoutTypes.Carousel;**
connector.Conversations.SendToConversation((Activity)newMessage);`

Fix these bugs, please. Thank you for good Bot Builder!!!)

**Comment by Andy-Tarasov** [comment]
I've found solution [here](https://github.com/Microsoft/BotBuilder/issues/799)
1. postBack is not supported by skype, use imBack. [here ](https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Samples/EchoBot/EchoAttachmentDialog.cs#L31) is a sample of a carousel working on skype.
2. Carousel should work, unless you have more than 5 cards in your attachments. Skype ignores the messages that have more than 5 cards with carousel layout.

**Comment by msft-shahins** [comment]
@Andy-Tarasov  that is true, Skype currently does NOT support following action types: postBack, playAudio, playVideo, downloadFile. Also maximum number of cards support in a Carousel in skype is 5 but for Facebook it is 10.
