### ISSUE TITLE
SignIn card not showing in skype as we assign facebook oauth url

### ISSUE THREAD

**Issue by sruthi-chelukala** [Microsoft/BotBuilder#845]
Hi ,Am using facebook Oauth in my bot.Initially it need to be authorized to continue with the other flow.
Following is the code where am assigning the fb outh url to the value of the signin card.Even when i debug i could see the value is properly assigned but the card is showing a different text .You can find it in the screeshot attached below.
The code I am using is as follows:

var fbLogin = $"{FacebookHelpers.GetFacebookLoginURL(ResumptionCookie, FacebookOauthCallback.ToString())}";

                var replytoconversation = context.MakeMessage();
                replytoconversation.Text = "Please sign in using this card";
                //replytoconversation.recipient = activity.from;
                //replytoconversation.type = "message";
                replytoconversation.Attachments = new List<Attachment>();

                var cardbuttons = new List<CardAction>();

                cardbuttons.Add(new CardAction
                {
                    Title = "connect",
                    Value = fbLogin,
                    Type = ActionTypes.Signin

                });

                SigninCard plcard = new SigninCard("you need to authorize me", cardbuttons);

                Attachment plattachment = plcard.ToAttachment();
                replytoconversation.Attachments.Add(new SigninCard("you need to authorize me", cardbuttons).ToAttachment());
                await context.PostAsync(replytoconversation);
                context.Wait(MessageReceivedAsync);

Fblogin Variable is holding the oauth url .If I assign the url directly its working fine,but I need the generated url to be used in the current context.

**The screenshot of Signin card which is not working properly is as shown**

![boterror](https://cloud.githubusercontent.com/assets/20094783/17213159/c7601f4a-54f0-11e6-9863-8981a6fd95bb.png).

Please help me out solving this issue.Thank you in advance.

**Comment by stucko** [comment]
Hi i have the similar issue, but without using cards, and via facebook channel, seems that the url i passed to the user is cut into pieces (2 halves in my case) as such the url has missing parameters needed for the callback

**Comment by msft-shahins** [comment]
@sruthi-chelukala here is a sample code with the sigin card that works across different channels: 

```csharp
var reply = context.MakeMessage();
var url = FacebookHelpers.GetFacebookLoginURL(ResumptionCookie, FacebookOauthCallback.ToString());
reply.Text = "Please sign in using this card";
var loginCard = new SigninCard {
	Buttons = new List<CardAction> {
		new CardAction {
			Title = "Login to Facebook!",
			Type = ActionTypes.Signin,
			Value = url }
	},
	Text = "you need to authorize me"
};
reply.Attachments.Add(loginCard.ToAttachment());
   

await context.PostAsync(reply);
```
Skype desktop
![image](https://cloud.githubusercontent.com/assets/17562300/18217217/66a4a90a-7110-11e6-8ec6-fcce8436dd2f.png)

Skype webcliet
![image](https://cloud.githubusercontent.com/assets/17562300/18217235/8b278c02-7110-11e6-8a6c-e604aa9769af.png)

Facebook
![image](https://cloud.githubusercontent.com/assets/17562300/18217250/9e7768fe-7110-11e6-98da-702e4d46bd94.png)

Slack
![image](https://cloud.githubusercontent.com/assets/17562300/18217254/adff98f0-7110-11e6-8d67-5118d919a374.png)

Webchat
![image](https://cloud.githubusercontent.com/assets/17562300/18217278/cb9890b0-7110-11e6-9016-7f054ef1aced.png)

**Comment by msft-shahins** [comment]
@stucko That is a limit that facebook is enforcing on number of characters. You can only have 320 character in a text message: https://developers.facebook.com/docs/messenger-platform/send-api-reference/text-message

I recommend using a url shortener to work around this limitation.
