### ISSUE TITLE
New error message - Telegram

### ISSUE THREAD

**Issue by rmatosaw** [Microsoft/BotBuilder#846]
Hi guys,

After download and install new version CSharp, I received a new error message in the dashboard for Telegram Bot:

**{"ok":false,"error_code":400,"description":"Bad Request: Can't parse message text: Can't find end of the entity starting at byte offset 89"}**

(Despite this problem, the robot answers well)

How can I solve it?

Thanks!

**Comment by eanders-MS** [comment]
This is the response we get from Telegram when they receive malformed markdown. The bad formatting could have come from your original message, or it could have been due some processing done by our service. An example would be if you included a single asterisk in your message. Telegram tries to interpret this as markdown, and never finds the closing asterisk. Can you check your outgoing message for unmatched markdown symbols?

**Comment by rmatosaw** [comment]
Hi.

Thank for the answer.

I checked the messages that I am sending and there is none of the characters of the markdown table.
In addition, just now I I configured the TextFormat property to "plain". Even so, the error message on the dashboard remains. Is it necessary to wait some time to check dashboard?

**Comment by eanders-MS** [comment]
@rmatosaw I've only ever seen this error message in the invalid markdown case, but there could certainly be other scenarios. Could you post a some sample text?

After doing some research, I see that our Telegram handler doesn't recognize the "plain" text format; it unconditionally treats it as markdown. I will log a bug on this and get a fix in.

**Comment by eanders-MS** [comment]
Oh wait, further investigation reveals we do handle "plain" correctly in Telegram. Sorry for any confusion. Removing bug label.

**Comment by Avartarus-Testicus** [comment]
Hi guys, 
today  I got a quite similar issue like @rmatosaw. Yesterday I added telegram to my channels and it worked fine, but today nothing works. 
![test2](https://cloud.githubusercontent.com/assets/20560750/17439439/6b4c6e96-5b28-11e6-906a-40300d81b916.PNG)

Has anybody a clue what to do ?

**Comment by eanders-MS** [comment]
@Avartarus-Testicus Could you post a sample of message text that causes this error to be returned? This error is returned by Telegram when we send them invalid markdown. Note: Telegram does not natively support a plaintext message format. It is up to us to strip markdown symbols when your bot specifies plain formatting. Your sample message might help determine whether we have a bug in that process.

**Comment by eanders-MS** [comment]
Re-adding bug tag. Telegram channel needs to strip markdown when text format is plain.

**Comment by eanders-MS** [comment]
Ok, it looks like your bot is having trouble responding, but when we try to post a message to this effect back to the user via Telegram, Telegram rejects the message for having invalid markup. Here is the error message we're trying to send:
```
POST to lord_of_the_bots failed: *Sorry, Lord of the Bots is having a problem responding right now.*
```
The bot id contains three underscore characters. Telegram is trying to interpret them as markdown, and failing to match the third one.

**Comment by Avartarus-Testicus** [comment]
Hi @eanders-MS , thanks for your fast response. Today I registered a new bot on the microsoft page with no underscore characters in the bot id. I hoped it would be enough, to work with telegram correctly again. But this time again, an issue occurred
![abc1](https://cloud.githubusercontent.com/assets/20560750/17473684/138f9a80-5d52-11e6-95b1-c9b3d42cccb9.PNG)
![abc2](https://cloud.githubusercontent.com/assets/20560750/17473685/1392577a-5d52-11e6-894e-0d41717e0175.PNG)

**Comment by eanders-MS** [comment]
Sorry for the slow response this time! Are you still seeing this issue?

**Comment by eanders-MS** [comment]
@Avartarus-Testicus Closing this issue. Please post a comment here if you need additional assistance and I will reopen.
