### ISSUE TITLE
New error message - Kik

### ISSUE THREAD

**Issue by rmatosaw** [Microsoft/BotBuilder#847]
Hi guys,

After the new Csharp version, Kik generates this message on botframewrok dashboard:

BotException: POST to {MYBOT name} failed: *Sorry, {MYBOT name} is having a problem responding right now.* Exception: *Sorry, {MYBOT name} is having a problem responding right now.* 

Despite this message, robot runs well.

Thanks

**Comment by LarsLiden** [comment]
This message is displayed when the call to your bot throws an error (i.e. http status >= 400).

**Comment by rmatosaw** [comment]
Hi LarsLiden.

Would you help me to try to detect where this Exception occurs? 
All my channels has apparently the same problem. 
I use try/catch in Post and logging the eventual exception. But there is no exception log, and the message is collected properly.

Thanks
