### ISSUE TITLE
Attachments in version 3.0

### ISSUE THREAD

**Issue by lucasmdesousa** [Microsoft/BotBuilder#848]
Hello, 

Can anyone tell me what's the right way to send attachments in new API version (3.0>)? 
I've tried it of several ways without success. The only thing I could was send image using base64 encoding. Example:

type: message/image
attachments: [ { contentType: 'image/jpg', contentUrl: 'data:image/jpg;base64,[content of file here]' } ]

However, according with documentation, in contentUrl parameter, the url of my image/file would be enough.

I'd really like to know what's the final way to do this, considering images and other types of attachments. Thank you.

**Comment by lucasmdesousa** [comment]
@rajarameshvarma I'm using REST API and it seems it doesn't have all the new Skype Bot features... 
I think it works to you because you are using .NET. I will test again later.

Anyway, thank you.

**Comment by msft-shahins** [comment]
@lucasmdesousa .NET SDK calls into the same REST API documented [here](https://docs.botframework.com/en-us/restapi/connector/#navtitle).

**Comment by puneetsngh** [comment]
@lucasmdesousa me too unable to send image from bot.

**Comment by Andrea-Orimoto** [comment]
@lucasmdesousa is this still an issue or was it resolved? thanks.

**Comment by lucasmdesousa** [comment]
@Andrea-Orimoto I have not tested these last days... I'll do it soon.

**Comment by dandriscoll** [comment]
Hi @lucasmdesousa, I'm going to close this issue as it's been inactive for a while. If you encounter problems, please file a new issue. Thanks!
