### ISSUE TITLE
Handle multiple response from the fromflow

### ISSUE THREAD

**Issue by Sams4u** [Microsoft/BotBuilder#850]
I have a formflow which has one Field with 4 choices. Problem is if the user clicks multiple buttons quickly the formflow object will be returned multiple times. How to handle this. I want to wait for the bot to respond once user clicks a button. Any solution?

**Comment by willportnoy** [comment]
You would need some method to serialize posts to your bot, so that each action could be handled as a atomic transaction.  You might consider using some sort of external locking (e.g. optimistic concurrency through etag of state service, or ASP.NET exclusive session state locks, etc).

**Comment by Sams4u** [comment]
If possible can you help me with some sample code? Also since the field options are enums and when the user clicks it, chat window shows corresponding number. Is there a way to show text instead of value?

**Comment by chrimc62** [comment]
The next release out soon will show the text as the message rather than the number.
