### ISSUE TITLE
Context Data not available in Case Condition C#

### ISSUE THREAD

**Issue by rzmoz** [Microsoft/BotBuilder#853]
Hi, I'm making a conversation based on Cases: Microsoft.Bot.Builder.Dialogs.ICase<in T, R>

https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Dialogs/Chain.cs Line 738

I would like to make a case trigger on data from the DataBags available in the Conversation context: **context.ConversationData, context.UserData and context.PrivateConversationData**

But the ICase interface doesn't pass a handle for the databags in the Condition clause: 

**Observed:**
Func&lt;T, bool&gt; Condition { get; }

**Wished for** 
something where I could write this in my condition delegate
(context,activity)=>
{
  bool myConditionMet;
  return context.ConversationData.TryGetValue("MyCondition", out myConditionMet);
}

**Comment by willportnoy** [comment]
In general, we haven't been passing IBotContext to any of the pure-functional predicates, for example While:
https://github.com/Microsoft/BotBuilder/blob/develop/CSharp/Library/Dialogs/Chain.cs#L263

or Select:
https://github.com/Microsoft/BotBuilder/blob/develop/CSharp/Library/Dialogs/Chain.cs#L138

@msft-shahins what do you think?

**Comment by msft-shahins** [comment]
@willportnoy I can see the added value for accessing bot data bags in chain predicates. Adding contextual predicates in addition to pure-functional ones might be a good idea.

**Comment by Andrea-Orimoto** [comment]
Thanks for the suggestion, we've added it to our backlog.
