### ISSUE TITLE
Adding a button causes 500 error for FB

### ISSUE THREAD

**Issue by MironV** [Microsoft/BotBuilder#855]
Adding a button of action type "call" to a hero card intended for Facebook causes a 500 error. Facebook cards allow for a phone_number type which hooks directly into the dialer. Should be supported by "call".

**Comment by LarsLiden** [comment]
See https://github.com/Microsoft/BotBuilder/issues/677

**Comment by tomlm** [comment]
There is no card action type = "call" use type='openUrl' and value="tel:#########"

**Comment by tomlm** [comment]
note: we will see the tel: in the url and promote into the facebook  phone_number type of button

**Comment by ejadib** [comment]
@tomlm I think the problem is that the type "call" is being mentioned [here](https://docs.botframework.com/en-us/csharp/builder/sdkreference/attachments.html#cardaction)

**Comment by scottmcconnell** [comment]
@tomlm; I have tried using openUrl for FB messengers button type 'phone_number' with no avail using the following:
```
builder.CardAction.openUrl(session, 'tel:XXXXX', 'button title');
```

Is this still a valid way of getting this to work within the bot builder?

Thanks,
Scott
