### ISSUE TITLE
Actions or intents should allow an array of RegEx

### ISSUE THREAD

**Issue by MironV** [Microsoft/BotBuilder#857]
Currently, you can only have one RegEx action or intent. The reason this is problematic is that you may have multiple RegEx templates for extracting data that all ultimately correspond to the same thing. Combining them into one massive RegEx is very impractical, especially if you then need to extract the data using a match array.

Currently the workaround is to create multiple actions and append a number to them (getweather1, getweather2, etc.) then map them to the same dialog. This seems pretty messy.

**Comment by Stevenic** [comment]
In v3.2.1 there's a new `IntentDialog.matchesAny()` method.
