### ISSUE TITLE
Cannot receive imgs sent from Skype

### ISSUE THREAD

**Issue by htaunay** [Microsoft/BotBuilder#859]
When working with the `session.Prompts.attachment` function, the image url I receive from Skype is always empty, while when working with the Telegram client it seems to work fine.

From what I understand of the framework, when a user sends an image to the bot, **someone** (its still not clear to me if its the BotFramework or the client) uploads the image to a server and the uploaded image's url is made available. Here is an example of a working link generated from Telegram, and a empty image url generated from Skype:

Telegram: https://bcattachmentsprod.blob.core.windows.net/636055812000000000/E6M94I105D18
Skype: https://df-apis.skype.com/v2/attachments/0-cus-d2-5b3840dafc2ac9f295bcc33c62e97154/views/original

Does anyone have an idea of how I can work around this?

**Comment by msft-shahins** [comment]
Similar to #662. Skype attachments are secured by bot JwtToken, you need bot's JwtToken as a bearer token to be able to access those urls.

**Comment by htaunay** [comment]
Thanks @msft-shahins ! I can confirm the solution form #662 worked successfully
