### ISSUE TITLE
How I disable basic authentication

### ISSUE THREAD

**Issue by ignatandrei** [Microsoft/BotBuilder#86]
When running Microsrof Bot Framework emulator for http://infovalutar.ro/bot/api/messages it says:

"You are using HTTP with basic auth, which is not a secure way to pass credentials. If you want to use an unsecured HTTP endpoint then you should disable basic authentication. We recommend you use HTTPS with basic auth to ensure your bot can only be called by trusted parties. Parameter name: Unauthorized - Using unsecure HTTP endpoint"
How I disable basic authentication ??

**Comment by tomlm** [comment]
For C# you comment out the "[BotAuthentication]" attribute
For NodeJS There is a Verify() call that does the basic auth, just disable that.

**Comment by avinb** [comment]
is there any other Authentication type supported by Bots ?
