### ISSUE TITLE
Bot status Error in the Microsoft dev portal for bot and away in slack.

### ISSUE THREAD

**Issue by niyatia** [Microsoft/BotBuilder#863]
I have a custom bot that was made in c# using Microsoft's bot framework. The bot has been running without problems for a few weeks until today. I can send the bot messages in emulator and it responds, but the bot is offline in Slack. The status of slack connection on microsoft dev portal is Error with message "Sorry. Bot is having problem responding right now". I have tried to reauthorize, re-add, and re-publish the bot to Slack and none of the above are working. 

Is anyone else having this problem or know what else I can do to try and get the bot to come back online in Slack?

**Comment by Thegaram** [comment]
I'd suggest remote debugging; this message often means your code threw an exception. Does it work on other channels?

**Comment by danmarshall** [comment]
This seems like it may have been an intermittent issue, please feel free to open a new issue if you experience this again.
