### ISSUE TITLE
Skype buttons are disabled while they work fine in Messenger for hero cards

### ISSUE THREAD

**Issue by MironV** [Microsoft/BotBuilder#864]
I've been checking the hero cards in Messenger and for openUrl type they seem to be working without issue. On Skype, the buttons show up but are not clickable (they are greyed out).

**Comment by ronnelsantiago** [comment]
what skype client you are referring to? is it the skype web client? https://web.skype.com/en/?ecsoverride=developer 

as detailed on the [doc](https://docs.botframework.com/en-us/skype/getting-started/#creating-a-skype-bot)  you ought to be using the web client for the cards to work until they have released the updated skype clients which they said it will end of July

**Comment by danmarshall** [comment]
@MironV can you verify now that the new client is RTM?

**Comment by MironV** [comment]
@danmarshall On the web client I'm not seeing the disabled buttons at all. "tel" works fine. The buttons are just URL's and work fine in Messenger. On my Mac, on the latest version of Skype I see the buttons but they are disabled.

**Comment by nickcordrey** [comment]
The latest Skype clients on desktop and mobile all have support for cards now. Please could you confirm you are using HTTPS for your open URL links as this is required in Skype.

**Comment by MironV** [comment]
Aha, that's probably it, I'll check in a bit!

However, this seems pretty extreme. I use a bunch of 3rd party APIs (Yelp, VFRMap, etc.) that don't provide HTTPS URLs in their APIs and some don't even have a HTTPS url to link to. What is the suggested approach there?

**Comment by danmarshall** [comment]
Perhaps you can use a URL shortener?

**Comment by MironV** [comment]
@danmarshall @nickcordrey If I can work around this by using a URL shortener why is this restriction in place?

**Comment by ajit-drag** [comment]
In the example of **signin card** for **Skype** [https://github.com/Microsoft/BotBuilder/blob/master/Node/examples/demo-skype/app.js](url)

```
var msg = new builder.Message(session) 
            .attachments([ 
                new builder.SigninCard(session) 
                    .text("You must first signin to your account.") 
                    .button("signin", "http://example.com/") 
            ]); 
```

url is http while http url is not working. 

as@MironV said - some third party APIs are not providing https, is there any way to use http for openUrl.

**Comment by chrimc62** [comment]
Closing because of age.  If you are still having an issue please raise the issue again.

**Comment by andrecarlucci** [comment]
Hi guys,

Skype signin button not working (it's, there, but it's not clickable) for me on the desktop version.
Version:  7.37.0.103

It works just fine on my Android.

Any fix on this?

**Comment by nwhitmont** [comment]
@andrecarlucci You are commenting on a closed issue. 

If you have a question or problem, please [open a new issue.](https://github.com/microsoft/botbuilder/issues/new)
