### ISSUE TITLE
Incorrect documentation [node]

### ISSUE THREAD

**Issue by Xunnamius** [Microsoft/BotBuilder#868]
https://docs.botframework.com/en-us/node/builder/chat-reference/classes/_botbuilder_d_.middleware.html

It makes a reference to a `builder.Middleware.sendTyping` (let `builder` equal the required `BotBuilder` package) but this does not seem to exist in the actual BotBuilder package. If I try to use it, I get an undefined error. Exploring the Middleware object shows that it does not exist.

`builder.Middleware = { [Function: Middleware] dialogVersion: [Function], firstRun: [Function] }`

I'm using the latest version of the botbuilder from npm `botbuilder@3.1.1`

Followed the example from here: https://github.com/Microsoft/BotBuilder/blob/master/Node/examples/basics-firstRun/app.js

**Comment by muzahmed** [comment]
@Xunnamius good catch, @Stevenic fixed last week, should be in the next version!

**Comment by Stevenic** [comment]
Try it in 3.2.1 and I'll re-open if still exists.
