### ISSUE TITLE
Error in documentation Sign-In Card (Attachments, cards and actions)

### ISSUE THREAD

**Issue by TechWatching** [Microsoft/BotBuilder#869]
Hello,

The "Sign-In Card" documentation is incorrect. It seems to be a duplication of a previous card documentation.

**Comment by willportnoy** [comment]
I believe this has been fixed - I see

> Sign-In Card
> The Sign-In card is a card representing a request to sign in the user

on

https://docs.botframework.com/en-us/csharp/builder/sdkreference/attachments.html

I'm going to close this issue, but feel free to open new issues for further discussion.
