### ISSUE TITLE
Bot Framework Emulator download link broken

### ISSUE THREAD

**Issue by ezkhan** [Microsoft/BotBuilder#87]
The download subdomain doesn't seem to exist.
The following just downloads the publish.htm page itself:
download.botframework.com/botconnector/tools/emulator/publish.htm

It is the target link from the Getting started documentation:
http://docs.botframework.com/connector/getstarted/#use-the-bot-framework-emulator-to-test-your-bot-application

**Comment by thermous** [comment]
I was not able to repro this, all of the links worked.

**Comment by KiriMihi** [comment]
@thermous When I download this setup it installes IoT dashboard
