### ISSUE TITLE
How to add channels?

### ISSUE THREAD

**Issue by sekhar4233** [Microsoft/BotBuilder#870]
How to add channels? We have one application where we want to add chat bots like Facebook and Slack. How can i add my application as channel?

**Comment by Thegaram** [comment]
I believe at this point only the bot framework team (at Microsoft) can add new channels. You can use the bot form your application through the Direct Line API.

**Comment by Samurais** [comment]
For Direct Line API, there is a nodejs client https://www.npmjs.com/package/directline-api.

**Comment by Andrea-Orimoto** [comment]
You can use DirectLine to embed your bot in any app or channel https://docs.botframework.com/en-us/restapi/directline/. hope this helps. feel free to reopen if needed. Thanks!
