### ISSUE TITLE
Changing colors on Bot Framework webchat window

### ISSUE THREAD

**Issue by katrina7g** [Microsoft/BotBuilder#872]
Is it possible to change the color scheme of the Microsoft Bot Framework's webchat channel display? Here is a sample of the default webchat window view. This display is added as a one line in html for the web page. I&#39;d be looking to change the colors, border, anything else, even adding a logo. Any advice?
![webchat_standard](https://cloud.githubusercontent.com/assets/6834237/17304060/79a925ae-57d8-11e6-91c3-faa2ece451d2.jpg)

**Comment by ciprianJijie** [comment]
Any solution ?

**Comment by danmarshall** [comment]
Hi @katrina7g we are looking at ways of letting developers customize their web chat control. We don't have an immediate solution but your feedback will help us design the next revision.

**Comment by Andrea-Orimoto** [comment]
Added to our backlog. thanks!

**Comment by pandubalraj** [comment]
Hi @dandriscoll,

Is there any ETA for the customization of webchat window UI. So that it would be more useful to not getting into Direct Line REST APIs. 

Thanks.

**Comment by dandriscoll** [comment]
Hi @pandubalraj, I don't have a date I can share at this time.

**Comment by pandubalraj** [comment]
Ok Thanks @dandriscoll. We are expecting soon :)

**Comment by ryanvolum** [comment]
https://github.com/Microsoft/BotFramework-WebChat
