### ISSUE TITLE
Bot only receives messages from specific users on Facebook

### ISSUE THREAD

**Issue by Thegaram** [Microsoft/BotBuilder#873]
I have a bot deployed on Azure, developed using the C# SDK (3.0). When I message it on Facebook from the account with which I created the Facebook Page/App, everything works well. When I message it using another account, the message does not even reach my controller, and on the dev page I see the uninformative "*POST to [botname] failed: *Sorry, [Bot] is having a problem responding right now*" error message.

I believe this might be because of some misconfiguration on my side. Any help is appreciated.

**Comment by muzahmed** [comment]
@Thegaram is your Facebook App public? if not, you will need to add developers or testers for them to interact with it (https://developers.facebook.com/apps/__YOUR FB APP ID HERE__/roles/)

**Comment by Thegaram** [comment]
@muzahmed You're right, thanks for the help!
