### ISSUE TITLE
Test errors

### ISSUE THREAD

**Issue by nicolasjustSnoopConsulting** [Microsoft/BotBuilder#877]
Hi,
I'm trying to create test for a bot. I am relying on the core test that you created, but the tests fail.
Can you fix it?

I run 
> mocha Node/core/tests/

and de output is:
Library
    1) should have BotBuilder exports

  Dialogs
TextBot class is deprecated. Use UniversalBot with a ConsoleConnector class.
TextBot.processMessage() is no longer supported. The schema for messages has changed and you should update your code to use the new UniversalBot class.
    2) should redirect to another dialog with arguments
TextBot class is deprecated. Use UniversalBot with a ConsoleConnector class.
TextBot.processMessage() is no longer supported. The schema for messages has changed and you should update your code to use the new UniversalBot class.
    3) should process a waterfall of all built-in prompt types

  TextBot
TextBot class is deprecated. Use UniversalBot with a ConsoleConnector class.
TextBot.processMessage() is no longer supported. The schema for messages has changed and you should update your code to use the new UniversalBot class.
    4) should reply inline with "Hello World"
TextBot class is deprecated. Use UniversalBot with a ConsoleConnector class.
TextBot.processMessage() is no longer supported. The schema for messages has changed and you should update your code to use the new UniversalBot class.
    5) should reply via event with "Hello World"
TextBot class is deprecated. Use UniversalBot with a ConsoleConnector class.
TextBot.processMessage() is no longer supported. The schema for messages has changed and you should update your code to use the new UniversalBot class.
    6) should reply inline with "msg1" and then reply via event with "msg2"
TextBot class is deprecated. Use UniversalBot with a ConsoleConnector class.
TextBot.processMessage() is no longer supported. The schema for messages has changed and you should update your code to use the new UniversalBot class.
    7) should reply inline with "msg1" and then quit

  errors
Oops. Something went wrong and we need to start over.
    ✓ should catch an exception from a Dialog based on a closure.
Oops. Something went wrong and we need to start over.
    ✓ should catch an exception from a Dialog based on a waterfall.
Oops. Something went wrong and we need to start over.
    ✓ should catch an exception from a IntentDialog.onBegin() handler.
Oops. Something went wrong and we need to start over.
    ✓ should catch an exception from a IntentDialog.matches() handler based on a closure.
Oops. Something went wrong and we need to start over.
    ✓ should catch an exception from a IntentDialog.matches() handler based on a waterfall.
Oops. Something went wrong and we need to start over.
    ✓ should catch an exception from a IntentDialog.onDefault() handler based on a closure.
Oops. Something went wrong and we need to start over.
    ✓ should catch an exception from a IntentDialog.onDefault() handler based on a waterfall.

  7 passing (21ms)
  7 failing

  1) Library should have BotBuilder exports:
     AssertionError: undefined == true
      at Context.<anonymous> (Node/core/tests/BotBuilder.js:11:9)

  2) Dialogs should redirect to another dialog with arguments:
     Error: TextBot.processMessage() is no longer supported.
      at TextBot.processMessage (Node/core/lib/deprecated/TextBot.js:58:15)
      at Context.<anonymous> (Node/core/tests/Dialogs.js:25:13)

  3) Dialogs should process a waterfall of all built-in prompt types:
     Error: TextBot.processMessage() is no longer supported.
      at TextBot.processMessage (Node/core/lib/deprecated/TextBot.js:58:15)
      at Context.<anonymous> (Node/core/tests/Dialogs.js:83:13)

  4) TextBot should reply inline with "Hello World":
     Error: TextBot.processMessage() is no longer supported.
      at TextBot.processMessage (Node/core/lib/deprecated/TextBot.js:58:15)
      at Context.<anonymous> (Node/core/tests/TextBot.js:12:13)

  5) TextBot should reply via event with "Hello World":
     Error: TextBot.processMessage() is no longer supported.
      at TextBot.processMessage (Node/core/lib/deprecated/TextBot.js:58:15)
      at Context.<anonymous> (Node/core/tests/TextBot.js:27:13)

  6) TextBot should reply inline with "msg1" and then reply via event with "msg2":
     Error: TextBot.processMessage() is no longer supported.
      at TextBot.processMessage (Node/core/lib/deprecated/TextBot.js:58:15)
      at Context.<anonymous> (Node/core/tests/TextBot.js:42:13)

  7) TextBot should reply inline with "msg1" and then quit:
     Error: TextBot.processMessage() is no longer supported.
      at TextBot.processMessage (Node/core/lib/deprecated/TextBot.js:58:15)
      at Context.<anonymous> (Node/core/tests/TextBot.js:60:13)
`

**Comment by Stevenic** [comment]
Just checked in fixes. Sorry for the delay
