### ISSUE TITLE
Slack/Skype connectors are stuck

### ISSUE THREAD

**Issue by arieschwartzman** [Microsoft/BotBuilder#878]
Slack channel stopped responding for one user while another user of slack BOT continues to work. I have created a new user and this once works fine. The bot was restarted this did not help. I have the same issue with Skype connector 

I have heard about /deleteprofile. Tried it, did not help for Skye.

**Comment by danmarshall** [comment]
This sounds like that first user may have gotten into a "dead end" in the session state. Are you using the Node.js or C# SDK ?

**Comment by arieschwartzman** [comment]
Node.js

**Comment by danmarshall** [comment]
Make sure you are calling session.endDialog or session.endDialogWithResult in your dialogs.
See https://docs.botframework.com/en-us/node/builder/chat/dialogs/ for examples.

**Comment by arieschwartzman** [comment]
This is all well and true, but in case there is unhandled exception occurs, how can I release the session once BOT has crashed?

**Comment by danmarshall** [comment]
@Stevenic , can you give some guidance?

**Comment by Stevenic** [comment]
@arieschwartzman first have you updated to 3.2.1 of the SDK? There were some improvements made in this specific area... Second, you can add the dialogVersion() middleware below which will add a 'reset' command.  

```
// Anytime the major version is incremented any existing conversations will be restarted.
bot.use(builder.Middleware.dialogVersion({ version: 1.0, resetCommand: /^reset/i }));
```

That's really intended for a developer to use so the other thing to do is to add a global endConversationAction() that listens for a user to say goodbye:

```
bot.endConversationAction('goodbye', 'Goodbye :)', { matches: /^goodbye/i });
```

**Comment by arieschwartzman** [comment]
@Stevenic Thanks for your reply. 
I have already implemented bot.endConversationAction which is a good idea anyway when you want to exit a conversation

**Comment by Stevenic** [comment]
Did that resolve your situation?

**Comment by Andrea-Orimoto** [comment]
assuming this was fixed. please open a new issue or reply to this one asking us to reopen if needed. Thanks!
