### ISSUE TITLE
Custom FieldReflector / Form Field _recognizer bug?

### ISSUE THREAD

**Issue by tomfurrier** [Microsoft/BotBuilder#879]
Hi there,

I've tried to create a custom FormFlow FIeld recognizer, however it didn't work as mentioned here: http://stackoverflow.com/questions/38745499/custom-fields-with-formbuilder-in-the-microsoft-bot-framework-not-working

I'm using 3.0.1 version of the BotBuilder.

I've tracked back until I found that at line 656 in Field.cs , the prompt recognizer is set there only once. 

`_prompt = new Prompter<T>(_promptDefinition, _form, _recognizer);`

Then the SetRecognize method of the Field only sets the Field's recognizer, not the prompt's. However at line 119 in Steps.cs the prompt's recognizer is used to find Match for Terms.

`matches = _field.Prompt.Recognizer.Matches(input, _field.GetValue(state));`

I don't really see what is the purpose of the Field's and the Prompt's different recognizers, or is there a bug related to this?

Thanks

**Comment by chrimc62** [comment]
Thanks for reporting the detailed information on this bug.  I have made a fix and it will be in our next release which should be soon.
