### ISSUE TITLE
Proxy authentication for Bot Framework emulator

### ISSUE THREAD

**Issue by silverjack3303** [Microsoft/BotBuilder#88]
Is there any way I can add proxy authentication to install the Bot Framework Emulator. I tried to install it and got a proxy authentication error (407).

**Comment by jameslew** [comment]
Currently ClickOnce packages don't support proxy authentication.  There are some workarounds on the web but they're a bit ugly.  You could try one of those, or alternately use the command line version of the emulator described here: http://docs.botframework.com/connector/tools/bot-framework-emulator/#navtitle.

**Comment by Stevenic** [comment]
Closing this as 'wontfix' since there isn't anything we can do.

**Comment by McMatty** [comment]
An installer without clickOnce is out of the question or source on github itself?
Sorry I've just hit the same issue myself

**Comment by clockwisemusic** [comment]
Well that's just annoying.

**Comment by iparry7979** [comment]
I managed to get around this by installing and running Fiddler 4 to intercept traffic and selecting "Rules > Automatically Authenticate"

**Comment by kylepolich** [comment]
This issue was the reason we finally gave up on botframework.  It's a nice tool but isn't production ready due to configuration difficulties.
