### ISSUE TITLE
What is a "Need" ? What is a "Wait" ? 

### ISSUE THREAD

**Issue by Kris-Nimmagadda** [Microsoft/BotBuilder#880]
what is the reason for setting the Need value multiple times ? Can somebody throw some light on the whole Fiber + Wait + Thunk + Need ?  When I make a FormBuilder.Confirm the last one is throwing an error that the Need should be "Wait" but it is "Poll". I am calling a New Dialog from within a Root Dialog. I used dialogContext.Call(mydialog, null).  Do we need a ResumeAfter ? Lot of questions, but I am strugging to understand the real reason behind this for a couple of days now. As I debug, I get into this loop of Wait, Thunk, Need etc and I have no clue what they are. Request help !!

My Scenario is, I should have a RootFormDialog which will have 4 Nested FormDialogs, and after each Dialog Completion, I should come back to the Root and from there I should allow the user to select other option (fill the form with a different option) and then take the user to the respective FormDialog  So I am calling "context.Call(pnrDialog , null);" from the MessageReceivedAsync callback of the rootDialog. But towards the end, after the last confirmation response to "yes" it fails saying that the Need is not matched to Wait but it is Poll :-(

**Comment by willportnoy** [comment]
The Need enum represents the state of the fiber as it waits for external input (e.g. the message).

Often you will see these exceptions if you call context.Wait more than once or not at all.

You need to pass a ResumeAfter callback to context.Wait - it shouldn't be a null reference.

You should follow this rule while writing your IDialog methods:

https://docs.botframework.com/en-us/technical-faq/#ensure-all-dialog-methods-end-with-a-plan-to-handle-the-next-message

**Comment by Kris-Nimmagadda** [comment]
Awesome ! You guys are doing great job !! Thank you for the direction. We are able to move forward and closer to what we want to achieve. 

However a quick light on "Thunk" and its purpose will also help us quickly understand the "Fibers" infrastructure while we debug through.  Just a quick direction and we will take care of the rest...

**Comment by willportnoy** [comment]
The purpose of the thunk class is to convert from the dialog's StartAsync/ResumeAfter delegate to the fiber's Rest delegate, since they take slightly different parameters.  The fiber is a more generic layer, the dialog adds things like the IDialogContext.

**Comment by willportnoy** [comment]
I'm going to close this issue, but feel free to open a new issue for further discussions.
