### ISSUE TITLE
Coding a new line in a Skype response?

### ISSUE THREAD

**Issue by epitone** [Microsoft/BotBuilder#881]
I'm posting a response to the user from the bot and am attempting to format my message so that it lists options on new lines - but using \r\n doesn't work, and neither does <br />, is there something specific I need to do to get the items on separate lines?

**Comment by danmarshall** [comment]
Can you try \n\n - this is the way to do it in markdown.

**Comment by danmarshall** [comment]
Hi @epitone, did this work for you?

**Comment by euanlau** [comment]
I ran into the same issue. Then I tried \n\n and it works.
