### ISSUE TITLE
bot.send or bot.beginDialog returns 401 Unauthorized

### ISSUE THREAD

**Issue by changhc** [Microsoft/BotBuilder#882]
I'm working on my bot with Node.js. I want to send some proactive messages to users, and I record users' addresses in the following format:  

{
	'channelId': set[i].ChannelId,
	'conversation': {
		'id': set[i].ConvId
	},
	'user': {
		'id': set[i].UserId
	},
	'bot': {
		'id': set[i].BotId
	},
	'serviceUrl': set[i].ServiceURL
};

I'm sure that this format is correct. Then I call bot.beginDialog(address, '/SomeDialog', params), session.send(text) and test this with the emulator. Here's the reply:

{
  "type": "message",
  "text": [text],
  "from": {
    "id": [id]
  },
  "recipient": {
    "id": [id]
  }
}
401 Unauthorized
Connection: close
Content-Length: [length]
Content-Type: application/json
Accept: application/json
Host: [host]

Also, if I deploy my bot to Azure Web app and run it on Web Chat or Skype, I can talk to them normally but they don't send me proactive messages. **(This is my main problem)**

I'm sure my AppId and AppPassword are set correctly. While testing on the emulator, I also set AppId and AppPassword in both my code (explicitly, not process.env) and the emulator. If I remove the AppId and AppPassword from the emulator (but still set in my code), I can receive proactive messages normally. This is weird.

Please help me figure out how to solve this. Thanks!

**Comment by LarsLiden** [comment]
Have you taken a look at the [auth troubleshooting guide](https://docs.botframework.com/en-us/support/troubleshooting-bot-framework-authentication/#navtitle)?

**Comment by changhc** [comment]
Hi,

Thank you for your reply, but I think I'm not understood enough.
In my system, as the server receives some specific requests, my bot would send some messages to all registered users, and I use bot.beginDialog(address, Dialog, params) to do this.
 
These screenshots may help:
1. When I'm testing my bot on azure, it works normally.
![p1](https://cloud.githubusercontent.com/assets/4591982/17388169/f7eebb12-5a2c-11e6-98c0-295c93d92d95.png)

2. On receiving requests, my bot sends messages to my emulator, but you can see that the status code is 401 now.
![p2](https://cloud.githubusercontent.com/assets/4591982/17388170/f7f24980-5a2c-11e6-889d-52550107dc61.png)

3. After I remove the AppId and AppPassword from the emulator, incoming messages are received normally.
![p3](https://cloud.githubusercontent.com/assets/4591982/17388171/f7f383b8-5a2c-11e6-90d2-4fc5c0252a7c.png)

I think this is not my problem. I just don't know why the authentication fails, and this may be the reason why I can't receive these messages on skype.

**Comment by changhc** [comment]
I've solved this, accidentally. It's your documentation's problem. Opening a new issue .

**Comment by CPerill** [comment]
Can you share what you did?

**Comment by CPerill** [comment]
I removed the AppID and AppID and it worked locally.

**Comment by changhc** [comment]
Hi @CPerill.

Aside from the four properties mentioned in the docs, you need to add two additional ones:

serviceUrl: you can get this from session.message.address
useAuth: set this **true** -- **this is the main point**

However, this solution is actually not recommended and perhaps temporary. Since the properties of interface IAddress may be modified in the future, this is only temporary. According to [this issue](https://github.com/Microsoft/BotBuilder/issues/895) (also published by me), it's better to save the whole session.message as a variable, and push it back whenever you need. 

If you need to save user session in a database or something like me, you can just save the session.message.address as a string. It's also okay to save all properties respectively.
