### ISSUE TITLE
Documentation mistake

### ISSUE THREAD

**Issue by mephisto83** [Microsoft/BotBuilder#886]
The method is marked async because the Bot Builder makes use of the C# facilities for handling asynchronous communication. It returns a Task<Message> which is the reply to the passed in Message. 

https://docs.botframework.com/en-us/csharp/builder/sdkreference/dialogs.html

It no longer returns "Task<Message>". This is making it difficult to understand whats going on.

**Comment by willportnoy** [comment]
Yes, I agree.  We should fix.

**Comment by msft-shahins** [comment]
this [Commit](https://github.com/Microsoft/BotBuilder/commit/34cfaa3c2da3de37e74ec2c983e15043069b1dda) should solve this issue.
