### ISSUE TITLE
Cannot download bot emulator framework

### ISSUE THREAD

**Issue by jeromekjerome** [Microsoft/BotBuilder#89]
Clicking on the link to download Microsoft Bot Emulator Framework results in an HTML file being downloaded.  I cannot find a link that actually downloads and installer.  Anyone got a clue what's happening?

**Comment by Stevenic** [comment]
Can you share the link that's being downloaded?

**Comment by jeromekjerome** [comment]
https://aka.ms/bf-bc-emulator

**Comment by jeromekjerome** [comment]
Here's what I get when I click that link:

file:///C:/Users/Jerome/Desktop/publish.htm

It's an HTML file with one line.

**Comment by jeromekjerome** [comment]
if I go to this link: https://aka.ms/ I get redirected to this:

https://login.microsoftonline.com/microsoft.onmicrosoft.com/wsfed?wa=wsignin1.0&wtrealm=http%3a%2f%2fsxp.cloudapp.net%2f&wctx=rm%3d0%26id%3dpassive%26ru%3d%252f&wct=2016-04-10T19%3a25%3a22Z#

**Comment by tomlm** [comment]
What happens if you go to http://download.botframework.com/botconnector/tools/emulator/publish.htm ?

Sent from my tumbs
________________________________

**Comment by zack456** [comment]
I can second that. Same issue from Chrome but not Edge.

**Comment by tomlm** [comment]
OH snap.  The tool I used to upload the new bits reset the content type to application/octet-stream.  It should work now.

**Comment by zack456** [comment]
Yup. That fixed it.

**Comment by jeromekjerome** [comment]
Yes, fixed.
