### ISSUE TITLE
[Question] How to handle dynamic questions in Node JS.

### ISSUE THREAD

**Issue by giriganapathy** [Microsoft/BotBuilder#890]
Hello Steve,

I have a scenario where instead of hardcoding the question text, I am going to make a webservice call to another system to ask for the question, and I need to show this question to user.  
For example: If user types "hi", then I do the following in the code:
a. getQuestion(1) - 1 is the question index.
and the response from other system will be like:
{"question": "Do you like to watch HD channels",
"question-type": "confirm"
}

So in my bot code, for the above response, though I can inspect the "question-type" and issue the appropriate commands like builder.Prompts.confirm, if question-type is confirm,  but i don't know how to have the next method in the stack (waterfall).  Basically, when we say prompts.confirm, then the control goes to next method in the array, and there we check the value normally.  So in this case, as the questions are going to be dynamic, not able to visualize how to handle the method for the response.

Could you please help me here, by referring any existing samples or show me some light on this.

Regards,
Giri G.

**Comment by giriganapathy** [comment]
Hello Steve,
Did u get a chance to review my question?  Could you please, if not.
Regards,
Giri G.

**Comment by Stevenic** [comment]
Here's what you'd want to do:

```
bot.dialog('/', function (session) {
    lookupQuestion(session.message.text, function (q) {
        switch (q.question-type) {
            case 'confirm':
                session.beginDialog('/dynamicConfirm', { prompt: q.question});
                break;
            case 'text':
                session.beginDialog('/dynamicText', { prompt: q.question});
                break;
        }
    });  
});

bot.dialog('/dynamicConfirm', [
    function (session, args) {
        builder.Prompts.confrim(session, args.prompt);
    },
    function (session, result) {
        // ... Do something with result.response

        // Make sure you return to root
        session.endDialog();
    } 
]);

bot.dialog('/dynamicText', [
    function (session, args) {
        builder.Prompts.text(session, args.prompt);
    },
    function (session, result) {
        // ... Do something with result.response

        // Make sure you return to root
        session.endDialog();
    } 
]);
```

**Comment by giriganapathy** [comment]
Thanks for the direction Steve.  Appreciate your swift responses in this regard.

**Comment by Stevenic** [comment]
no problem.
