### ISSUE TITLE
Why are interfaces prefixed with I?

### ISSUE THREAD

**Issue by letmaik** [Microsoft/BotBuilder#894]
The second point on the [TypeScript coding guidelines](https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines) says:

> Do not use "I" as a prefix for interface names.

So I was wondering, is this some historical artifact?

**Comment by willportnoy** [comment]
It seems likely it's a habit from programming in other languages, e.g. C# or Java:
https://msdn.microsoft.com/en-us/library/8bc1fexb(v=vs.71).aspx

I understand the reasoning for suggesting that interfaces should not have the 'I' prefix as well.

**Comment by danmarshall** [comment]
The guidelines you linked to are specifically for contributions to the TypeScript project itself, they aren't meant to prescribe a global style guide for language usage. 

To answer your question though, I would say some of us are just "old school" coders =D
