### ISSUE TITLE
Documentation needs to be revised (NodeJS)

### ISSUE THREAD

**Issue by changhc** [Microsoft/BotBuilder#895]
In your documentation about interface **IAddress**, something is missing:

[Here](https://github.com/Microsoft/BotBuilder/blob/4e7e7c600d2cfa5ba3750899eedfab9aa967c48f/Node/core/lib/bots/ChatConnector.js#L566) you wrote about what a **toAddress** should have, but [here](https://docs.botframework.com/en-us/node/builder/chat-reference/interfaces/_botbuilder_d_.iaddress.html) you only mention four properties, which would lead to big problems when using method **beginDialog** or **send** or any other method that would call **send**. Please add **serviceUrl** and **useAuth** to the doc. Thanks.

**Comment by Stevenic** [comment]
I hid those properties intentionally.  The properties I documented are essentially public well known properties of the address object. The connector is free to add any other properties it likes so serviceUrl and useAuth are connector specific properties that may be added to or removed at some point in the future.  Building a new address object up from scratch isn't supported. You should always save the object you got from the connector and then feed it back to the connector when you want to contact the user at some point in the future.

**Comment by slidenerd** [comment]
thank you so much for the above comment @Stevenic I was going to open an issue citing how come 3 properties are not documented but you made it all clear 🎯
