### ISSUE TITLE
List of events incomplete [node]

### ISSUE THREAD

**Issue by letmaik** [Microsoft/BotBuilder#898]
I tried to get an overview of bot events I can listen to but could not find useful information from the docs:

https://docs.botframework.com/en-us/node/builder/chat-reference/classes/_botbuilder_d_.universalbot.html#on This just has a single event type.

 https://stackoverflow.com/questions/37531558/testing-microsoft-bot-framework-async-replies So apparently there's a `reply` event.

Is there a list of all event types and examples on how to use them?

**Comment by Stevenic** [comment]
I need to add docs for all of the event types. I'll work on that,

**Comment by Stevenic** [comment]
I just updated the docs for [UniversalBot.on()](https://docs.botframework.com/en-us/node/builder/chat-reference/classes/_botbuilder_d_.universalbot.html#on)

**Comment by letmaik** [comment]
Great, thanks!

**Comment by letmaik** [comment]
I just noticed that the `outgoing` event is not described in the parameters section. Can you add that? I may actually have to use that.

**Comment by chrimc62** [comment]
@Stevenic or @maxpert can you please see if this is fixed in the latest documentation?

**Comment by Stevenic** [comment]
I've added the documentation for t he missing event and will be part of docs for 3.5 release.

**Comment by slidenerd** [comment]
Best to add firstRun as an event to this list that gets triggered once when the user uses the bot for the first time, a lot of boilerplate will be eliminated on the developer's end
