### ISSUE TITLE
supported languages?

### ISSUE THREAD

**Issue by bnusunny** [Microsoft/BotBuilder#9]
what nature languages does this framework support beside English?  For example, can the bot understand Chinese in text and/or audio?

**Comment by tomlm** [comment]
Text, yes, audio, no
 See here for list of languages https://msdn.microsoft.com/en-us/library/hh456380.aspx 

To switch to a language (for a bot that has the translation turned on) simply type in:
     "I want to speak __language___" 
Example:
    "I would like to speak in Chinese"
And the bot should start replying in Chinese.

NOTE: In the bot registration it can list the languages it supports.  If an incoming language doesn't match the bots' language, translation will be invoked.  If a bot is using a LUIS model that was trained for a language then the model will be matching against the translation, and should work without modification. The response is then translated to match the conversation language.

See: http://docs.botframework.com/connector/bot-options/#navtitle for description of translation.

**Comment by bnusunny** [comment]
Great! I will try it using the example bots.

**Comment by MathBunny** [comment]
FYI, the translation through bot connector was disabled in V3 I believe.

**Comment by nwhitmont** [comment]
@MathBunny You are commenting on a closed issue. 

If you have a question or problem, please [open a new issue.](https://github.com/microsoft/botbuilder/issues/new)

**Comment by MathBunny** [comment]
I know just doing it for future readers
