### ISSUE TITLE
An unhandled exception of type 'System.NullReferenceException' occurred in Microsoft.Bot.Connector.Emulator.Core.dll

### ISSUE THREAD

**Issue by tungnt244** [Microsoft/BotBuilder#900]
![image](https://cloud.githubusercontent.com/assets/20721437/17409356/203890f4-5a99-11e6-84ef-28892c0cca63.png)
My emulator is crash right after i open "Bot Framework Channel Emulator.exe". Can anyone show me the way to fix it.

**Comment by willportnoy** [comment]
Can you share the call stack?

**Comment by tungnt244** [comment]
i'm very new with this, could u show me how to see the call stack. Thanks a lot.

**Comment by willportnoy** [comment]
Click on the "call stack" tab and show external code.  It sometimes helps to tell Visual Studio to break on thrown exceptions in the "exceptions" tab.

**Comment by tungnt244** [comment]
![image](https://cloud.githubusercontent.com/assets/20721437/17453601/910fae10-5ba8-11e6-91ae-4be8ba83e4d0.png)
![image](https://cloud.githubusercontent.com/assets/20721437/17453603/a0cac470-5ba8-11e6-905e-bb50916301e9.png)

Here are my call stack,

**Comment by willportnoy** [comment]
Thank you for the call stack - that's useful.  Does resetting the emulator help avoid the issue?

https://docs.botframework.com/en-us/technical-faq/#how-can-i-reset-the-bot-framework-emulators-settings

**Comment by tungnt244** [comment]
Thanks a lot, My problem was solved.

**Comment by willportnoy** [comment]
I'm going to close this issue, but feel free to open a new issue for further discussions.

**Comment by ThibautCantet** [comment]
I had the same problem. Deleting the emulator.service fixed the crash !
