### ISSUE TITLE
Use the IDialog instance variables or the BotStateService to persist state?

### ISSUE THREAD

**Issue by brendanarnold** [Microsoft/BotBuilder#901]
The example of the "Echo Bot with State" given at https://docs.botframework.com/en-us/csharp/builder/sdkreference/dialogs.html shows using class variables to persist state

However later in the docs it seems to suggest using the BotStateService i.e. https://docs.botframework.com/en-us/csharp/builder/sdkreference/stateapi.html#contextualproperties

Which should I use? The former is far easier but it isn't clear if the protected/private variables are serialized inline with the JSON passed between client/bot and so persisted at scale ...

**Comment by willportnoy** [comment]
We tend to prefer the class variables solution.  You can mark your dialog as [Serializable] and follow the normal rules for tweaking what gets serialized with your dialog (e.g. you can exclude things with [NonSerialized]).

**Comment by willportnoy** [comment]
I'm going to close this issue, but feel free to open a new issue for further discussions.
