### ISSUE TITLE
Card containing only buttons

### ISSUE THREAD

**Issue by brendanarnold** [Microsoft/BotBuilder#902]
On the main bot framework page we see an example bot that has a card that only contains buttons - see image below.

In the framework we only have cards that contain images (Hero/Thumbnail) and others (Receipt etc.) that don't fit this pattern.

How do we get activities as in the image of a few button choices?

![2016-08-04](https://cloud.githubusercontent.com/assets/584658/17410174/7e160532-5a6a-11e6-8b16-debd5c93a4f0.png)

**Comment by MironV** [comment]
I've had success simply providing nothing for the image. Did you give that a try?

**Comment by msft-shahins** [comment]
As @MironV mentioned a HeroCard or ThumbnailCard that only has buttons should be rendered in that way.
