### ISSUE TITLE
Dialogand Intent node

### ISSUE THREAD

**Issue by VishalWaman** [Microsoft/BotBuilder#903]
Below case.
Need to handle a dialog for "welcome" and intent for "welcome" 
To handle both (dialog and intent) I need to write separate dialog and intent function arrays with same code redundant!!

Can have common to handle both?

**Comment by Stevenic** [comment]
You can write a waterfall for your "welcome" intent handler so there's no need to break it out to a separate dialog.  If I'm misunderstanding please share your code and I'll re-open the issue.
