### ISSUE TITLE
LUIS models and service functionality should be in it's own DLL.

### ISSUE THREAD

**Issue by jwittner** [Microsoft/BotBuilder#904]
I'm looking at writing some .NET Standard Library targeted applications that leverage LUIS. The bot framework has a wonderful setup for modelling the LUIS api and leveraging the service, but it's currently embedded in the .NET Framework targeted DLL.

I'm hoping we can pull that out of BotBuilder, make it a cross platform DLL, and then depend on it here in Bot Builder.

**Comment by willportnoy** [comment]
When you say ".NET Standard Library", do you mean:

https://www.nuget.org/packages/NETStandard.Library/
https://docs.microsoft.com/en-us/dotnet/articles/standard/library

Or do you mean .NET Core? as in this issue: https://github.com/Microsoft/BotBuilder/issues/572

**Comment by jwittner** [comment]
@willportnoy Hi! Yes, I was referring to the Standard Library referred to in those links, not .NET Core. Though the distinction is admittedly blurry to me still. What do we think about extracting and generalizing just this functionality? I noticed that it has dependencies on the bot fibers, but I'm not sure how necessary that stuff is for just this portion of the implementation.

**Comment by jwittner** [comment]
Looking through the Microsoft.Bot.Builder.Luis namespace, I think there are a small set of changes to extract the LuisService dependency on LuisModelAttribute. At that point if this were packaged as .NET Standard Library compatible DLL people would have a good starting place for communicating with their LUIS apis.

**Comment by Andrea-Orimoto** [comment]
This feature request has been added to our backlog for future consideration. Thanks!
