### ISSUE TITLE
LUIS

### ISSUE THREAD

**Issue by VishalWaman** [Microsoft/BotBuilder#905]
When have 2 intent in an utterance.

Either is selected as "intent" 

What decides the intent that will be selected as top intent.

Eg: I want to have breakfast and lunch together,
INTENT: Breakfast and lunch = Intent.

What factor decides top intent?

**Comment by danmarshall** [comment]
In LUIS, have you bound these Intents to Actions?

**Comment by eanders-MS** [comment]
@VishalWaman The LUIS team may be able to answer you. I believe they have contact info on their About page: https://www.luis.ai/Home/About

**Comment by VishalWaman** [comment]
@danmarshall yes i have entity added for intent.

Intent: Balance,credit card.
Utterance: Get my credit card balance..
LUIS intent matched to "balance"...

I am ok with result but want  know how and which

**Comment by willportnoy** [comment]
LUIS provides a score for each intent they assign to a query for a user's utterance.  In the LuisDialog, we select the intent that will be used for the method dispatch by selecting the intent with the highest score:

https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Dialogs/LuisDialog.cs#L157

**Comment by VishalWaman** [comment]
Thanks all.
