### ISSUE TITLE
Target for .NET Standard Library 

### ISSUE THREAD

**Issue by jwittner** [Microsoft/BotBuilder#906]
I'd love to get a version of Bot Builder that targets the .NET Standard Library.

I've forked and started some work to bring over as much functionality as possible.

**Comment by willportnoy** [comment]
Related discussion on https://github.com/Microsoft/BotBuilder/issues/904.

**Comment by jwittner** [comment]
Having read through #572 and put some effort into digging through the project I think this work is a bit out of scope for me right now so I'm closing it.
