### ISSUE TITLE
Delivery Method not shown on Facebook Receipt Card

### ISSUE THREAD

**Issue by ernanirst** [Microsoft/BotBuilder#907]
I'm building a Receipt Card for my customers on facebook. I developed it using this [examples](https://github.com/Microsoft/BotBuilder/blob/81d8aa1d4e4fda2054066695a7746961d11e9128/Node/examples/demo-skype/app.js#L354).

My doubt is, on this example the delivery method is set, and I can see it on the bot emulator. However facebook does not show the delivery method in any way.

Doesn't facebook support it?

**Comment by msft-shahins** [comment]
It is not supported by [Facebook's receipt template](https://developers.facebook.com/docs/messenger-platform/send-api-reference/receipt-template). Currently only facts that will be mapped by Facebook connector to receipt template are: `order_number` and `payment_method`.

**Comment by ernanirst** [comment]
@msft-shahins thanks for making that clear. But in the page that you mentioned, it shows that facebook maps shipping_cost and subtotal, are these implemented as Facts on the SDK?

**Comment by msft-shahins** [comment]
currently only `total_tax` and `total_cost` are mapped using the ReceiptCard.Tax and ReceiptCard.Total. Keep in mind that you can always send your custom object based on Facebook schema in the `channel data`.

**Comment by ernanirst** [comment]
Thanks,  I didn't know that was possible with `channel data`. I will check if I can find any examples with it.
