### ISSUE TITLE
Passing user response from prompt dialog to chain dialog

### ISSUE THREAD

**Issue by wswijaya** [Microsoft/BotBuilder#908]
The problem i am trying to address is a conversation that flows like a decision tree. For example, conversation starts on a chain dialog. Then user is prompted with PromptDialog. is that possible to pass the respond back to the same chain dialog. Like a recursive method.

**Comment by danmarshall** [comment]
Are you using C# or Node.js ?

**Comment by wswijaya** [comment]
Hi, I am using C#.
I've written experimental Dialog.  Could you help to verify if it is an acceptable way to implement.
What it does is to continue prompting for dialog as long as user choose 'continue'.

` 
   [Serializable]
    public sealed class CommonDialog : IDialog<IMessageActivity>
    {
        public async Task StartAsync(IDialogContext context)
        {
            context.Wait(MessageReceivedAsync);
        }

        public async Task MessageReceivedAsync(IDialogContext context, IAwaitable<IMessageActivity> argument)
        {
            var message = await argument;

            if (message.Text == "end")
            {
                await context.PostAsync("Ended");
                context.Done(string.Empty);
            }
            //Todo:  insert perform some operation to decide if bot needs to respond with a prompt
            if (message.Text == "hi" || message.Text == "continue")
            {
                List<string> options = new List<string>() { "continue", "end" };
                PromptDialog.Choice(context: context, resume: this.ForwardToDialog, options: options, prompt: "Do you want to continue", retry: null, attempts: 3);
            } else
            {
                await context.PostAsync($"Bot says: {message.Text}");
                context.Wait(MessageReceivedAsync);
            }
        }

        private async Task ForwardToDialog(IDialogContext context, IAwaitable<string> argument)
        {
            //await context.Call(new)
            IMessageActivity message = context.MakeMessage();
            message.Text = await argument;
            await context.Forward(new CommonDialog(), this.ResumeAfterGpf, message, CancellationToken.None);
        }

        private async Task ResumeAfterGpf(IDialogContext context, IAwaitable<IMessageActivity> result)
        {
            context.Done(string.Empty);
        }
    }
`

**Comment by msft-shahins** [comment]
It is fine to have the pattern to loop over your logic. An alternative is using Chain dialogs to achieve the logic above: 

```csharp


        public static readonly IDialog<string> altDialog = Chain.PostToChain()
            .Select(msg => msg.Text)            
            .Switch(new RegexCase<IDialog<string>>(new Regex("^hi"), (context, txt) => {
                return Chain.Return("You can say continue or end.");
            })
            ,new RegexCase<IDialog<string>>(new Regex("^continue"), (context, txt) => {
                // conduct continuation logic
                return Chain.Return("You can say continue or end.");
            })
            ,
            new RegexCase<IDialog<string>>(new Regex("^end"), (context, txt) => {
                return Chain.Return("Ended");
            }),
            new DefaultCase<string, IDialog<string>>((context, txt) => {
                return Chain.Return($"Bot says: {txt}");
            }))
            .Unwrap()
            .PostToUser();

```
