### ISSUE TITLE
Cards on FormFlow

### ISSUE THREAD

**Issue by ankitbko** [Microsoft/BotBuilder#909]
First, kudos to Microsoft team on [excellent bots](http://www.theverge.com/2016/8/4/12373748/microsoft-adds-five-skype-bots-skyscanner-ifttt). I tried couple of them and they were awesome. 
I have a quick question though. How do you get to display Hero Card from Form Flow something like in image below.

![image](https://cloud.githubusercontent.com/assets/3169316/17425602/c3b3b4ae-5aec-11e6-9317-e76d323cd139.png)

**Comment by chrimc62** [comment]
Thanks for the feedback.  This will be in the next release which should be soon.
