### ISSUE TITLE
Web Installer will not run

### ISSUE THREAD

**Issue by jeromekjerome** [Microsoft/BotBuilder#91]
To make the bot framework work, I also need to install the VS2015 Azure Pack but I can't seem to get the web installer package to run.  Is there any way I can get a remote installation package?

**Comment by willportnoy** [comment]
I don't see anything obvious - there's a process to make the web installer run offline, but I'm not sure that will help you.

https://technet.microsoft.com/en-us/library/dn756546.aspx

What is the error message you see from the web installer?

**Comment by jeromekjerome** [comment]
Here is a screenshot of the error message and a directory of the C drive from the command prompt.  Please notice the Junction on C:/Users.  I suspect this is the problem but I can't change it.

**Comment by jeromekjerome** [comment]
![20160417 microsoft web installer error message](https://cloud.githubusercontent.com/assets/18381705/14618349/3bd8d166-0580-11e6-9e9c-b7f2b14e0064.png)

**Comment by willportnoy** [comment]
I believe the bot builder azure dependencies are limited to the configuration reading library, which we get from nuget.  Is there another dependency that is blocking you?
