### ISSUE TITLE
[C#] Integrating with Bing Speech

### ISSUE THREAD

**Issue by ankitbko** [Microsoft/BotBuilder#910]
I tried Bing Speech and it worked well. It recognizes my voice, communicates with LUIS and gets back to me with correct LuisResult. I already have an existing bot and I was trying to integrate calling feature into it. Is it possible to seamlessly integrate calling feature with FormFlow? 
What I want is to respond as text if user is texting and reply as voice if user is calling while in behind having FormFlow? 
In short flow will be
Call -> Recording -> Bing Speech API returns with LuisResult -> FormFlow -> Ask next question (voice)
Text -> LuisDialog ------------------------------------------------> FormFlow -> Ask next question (text)
Currently FormFlow goes ahead and automatically ask questions for next property as text. Is there a way for FormFlow to 'return' the next question so that I can pass it to calling sdk and attach it as PlayPromt to workflow?

**Comment by mghimp** [comment]
To support the Call only bot, I would like to ask that in addition to _**Call -> Recording**_ flow, the flow _**Call -> Text**_ flow to be supported by Bing Speech integration as well because currently in order to get text out of recording I have to use consecutive 3d party Speech-To-Text service which impacts badly UX by significant delay

**Comment by msft-shahins** [comment]
@ankitbko  you can achieve that by using [BotToUserQueue](https://github.com/Microsoft/BotBuilder/blob/c4dbb7183cc1c23837b6d6c8bc03fe8c54ba1f55/CSharp/Library/Dialogs/BotToUser.cs#L67) as the IBotToUser for your bot. You can find an example of how you can configure your bot to use a custom IBotToUser [here](https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Tests/FormTest/Program.cs#L118). 

This causes messages from FormFlow to be accumulated in the queue and then you can send the messages in the queue as the text response to the calling API.

**Comment by msft-shahins** [comment]
@mghimp thanks for the feedback, currently I am not aware of any plans for adding support for `Call -> Text` path to Skype Calling API. I will send your feedback to the Skype development team for consideration.

**Comment by Deep-Ak** [comment]
I'm trying to integrate bing speech into my cortana bot(.NET). Currently it works great with just text, when I click the mic button in the bot framework I get an error "Could not retreive cognitive services speech token". I have a file that looks exactly like this [https://github.com/Azure-Samples/SpeechToText-REST/blob/master/SpeechSample-CSharp.cs](url), Where do I initialize an object of class Authentication? Is there a sample project that I can look into?
