### ISSUE TITLE
202 Accepted but no response

### ISSUE THREAD

**Issue by YohannPuri** [Microsoft/BotBuilder#913]
Hey MBF,

I have a bot published on Azure and after republishing yesterday it just stopped responding. Responses work absolutely fine on the emulator. The test on the Bot connector page hits accepted. I tried using Direct line and that generates a conversation id/token correctly but after that when I try to get messages it's all empty. No responses of any kind. I've tried attaching a remote debugger but symbols fail to load and so cant attach! 
This is on republishing a working bot after barely changing any code!
Thanks for any help that you can provide.

**Comment by danmarshall** [comment]
Can you revert your code changes and republish back to a working state? That is what I would try first.

**Comment by YohannPuri** [comment]
Hey Dan,
I reverted back to an old version which was working and published that. Same thing! No replies!
As an additional test I took another bot I had which was working and responding and republished it with no changes at all and that has stopped responding as well!

**Comment by Stevenic** [comment]
Are you using Node or C#?

**Comment by YohannPuri** [comment]
All my code is C#!

**Comment by YohannPuri** [comment]
So I tried republishing again today. Still not working. Interestingly though, I tried sending it a picture and that works by calling my LUIS model, going to the none intent and printing that although the response takes well over a minute to come back. Any help is appreciated

**Comment by danmarshall** [comment]
following up offline
