### ISSUE TITLE
Skype Bot "session.sendTyping();"

### ISSUE THREAD

**Issue by VishalWaman** [Microsoft/BotBuilder#914]
## Skype Bot " session.sendTyping();" Node.js (Brevity added)

We tried this some places and seems not working in our case.

`
//LEDGER INTENT HANDLER FROM LUIS
intents.matches('ledger',  [

    function (session, args) {
        var ClientCode = session.dialogData.ClientCode = builder.EntityRecognizer.findEntity(args.entities, bothelper.testent);

        if(ClientCode) {
            var ledger = testhelper.test(ClientCode);
            session.send('You ledger amount : ' + ledger);
            builder.Prompts.text(session,'What more we can do ?');
        }
        else {
            // MAKE SESSION NULL
            session.dialogData.ClientCode = null;
            builder.Prompts.text(session, ''+ bothelper.ClientCode);
        }
    },
    function (session, results) {

      session.sendTyping();
        testhelper.testhelper(results.response,function (result) {

            if (bothelper.validReply(result)) {
                session.send('You ledger amount : ' + result + ' (y)');
            }
            builder.Prompts.text(session,'What more we can do ?');

        });
    }
]);`

**Comment by NanashiGIT** [comment]
Just wanted to mention, that sending a Typing-Message over skype doesnt work with the C# SDK aswell.

**Comment by Stevenic** [comment]
I don't believe they currently support bots sending a typing indication. I'll let them comment.

**Comment by VishalWaman** [comment]
This works with channel emulator.

**Comment by Stevenic** [comment]
The emulator supports everything so it's not an accurate simulation of any one channel.

**Comment by nickcordrey** [comment]
Confirming Skype doesn't support typing indicator for bots today.

**Comment by 0GiS0** [comment]
Hi folks,

do you know which channels support this?

thanks!

**Comment by VishalWaman** [comment]
Facebook does. I have tried it..

**Comment by Yudner** [comment]
in c# ????

**Comment by nwhitmont** [comment]
@Yudner You are commenting on a closed issue. 

If you have a question or problem, please [open a new issue.](https://github.com/microsoft/botbuilder/issues/new)
