### ISSUE TITLE
Skype Preview wrong message on button click

### ISSUE THREAD

**Issue by Thegaram** [Microsoft/BotBuilder#918]
When I click on a button in the new Skype Preview (which is part of the Windows 10 Anniversary Update), the answer sent to the bot is in this format:

```
<at id="[id]">@[botname]</at> [msgtext]
```

It seems like the Connector Service for Skype is not prepared for this, as the bot also receives the message in this format instead of only receiving the message text. As a consequence, the dialog logic won't be able to handle the answer.

Example:

![image](https://cloud.githubusercontent.com/assets/7571518/17449488/c36b937c-5b0f-11e6-912b-089d78d26da7.png)

**Comment by nickcordrey** [comment]
Thanks I've flagged this issue to the Skype team.

**Comment by nickcordrey** [comment]
This issue has been fixed and will be available in a subsequent release. Thanks again for raising it.
