### ISSUE TITLE
Put sensitive data (appid/appsecret) on config file, and add it to .gitignore

### ISSUE THREAD

**Issue by jieverson** [Microsoft/BotBuilder#92]
I'm using the **Node.js** Bot Builder Framework.
As I think loots of people are going to keep bots public at github, it would be great if sensitive data (as _appId_ and _appSecret_) was storage at a config file. For safety, this file could come added at **.gitignore**.
In my case I have created `/.bot/secrets.json` to storage sensitive information. If I don't have the file, my server just use some default strings like: `YOUR_APP_ID` and `YOUR_APP_SECRET`.
I'm not sure if I did it in the best way. I accept suggestions.

**Comment by Stevenic** [comment]
In my latest examples I've started using process.env.BOTFRAMEWORK_APPID & process.env.BOTFRAMEWORK_APPSECRET to pass the AppId & AppSecret. If you're deploying your bot to Azure this will let you use their configure those values from the service dashboard.

In general you should avoid EVER checking in keys & secrets. I should be more consistent in my examples.

**Comment by jieverson** [comment]
yes, I'm using Azure. Using the Azure settings is a great idea. But, how could I test it localy, if the keys are keeped at Azure? I'm using the BFEmulator to test it at localhost most part of the time.

**Comment by Stevenic** [comment]
from the command line before you run your bot type "set BOTFRAMEWORK_APPID=YourAppId" and then put a breakpoint to make sure they're getting set.  This isn't required when running local though. You have to communicate with the emulator over HTTP and these ID's get ignored when using HTTP so you don't even need to set them when running local.

**Comment by jieverson** [comment]
Thanks. I think I'm Ok with this solution. :+1:

**Comment by zack456** [comment]
I'd like to see something like this in the C# library too. I had to redo my repo with a sample config and ignore the primary config file while still keeping both in the solution so I can continue to deployment.

**Comment by jieverson** [comment]
In C#, I'm pretty sure you can just configure variables at your azure `app settings`. 
For localhost test, just add `environment variables` to windows (from control panel, or start menu search).

**Comment by zack456** [comment]
Thanks. I'll try it out.
