### ISSUE TITLE
beginDialog does not work with Skype group chat

### ISSUE THREAD

**Issue by euanlau** [Microsoft/BotBuilder#921]
Version 3.2.1

`bot.beginDialog(address, '/someroute')` always send the message to the 1-1 conversation that belongs to the user object in `address.user` even if `address.conversation` is pointing to a group conversation.

It seems that the problem is associated with `bot.ensureConversation`. It retrieves the conversation by using the single user inside `address.user` and the bot in `address.bot`.

I think we should use`conversation.id` if such exists in the `address` object.

**Comment by Stevenic** [comment]
That's a reasonable ask... It just means removing the logic from `UniversalBot.beginDialog()` that automatically deletes the `address.conversation` field. This would let you proactively start a new dialog stack with a user or group within the context of an existing conversation. I can see that being useful.

**Comment by Stevenic** [comment]
Should be fixed... I just published v3.2.3

**Comment by euanlau** [comment]
The fix looks good. Thanks!
