### ISSUE TITLE
Bing News Card format

### ISSUE THREAD

**Issue by euanlau** [Microsoft/BotBuilder#922]
I tried the Bing News Bot on Skype. The layout for articles is not the same as HeroCard. 

Is Bing News using custom attachment layout on Skype?

**Comment by v-ms** [comment]
Bing News - Preview bot does not use cards, instead it sends just text messages which consist just of a single url. Then Skype clients use their URL preview feature to show previews for those links.

**Comment by Andrea-Orimoto** [comment]
Assuming v-ms's answered the issue. Please open a new issue or reply to this one asking us to reopen if needed. Thanks!

**Comment by euanlau** [comment]
A follow up question. How do you hide the URL text like Bing News (i.e. showing only the preview image)?

**Comment by euanlau** [comment]
@v-ms Is it possible hide the URL text like Bing News (i.e. showing only the preview image)?
