### ISSUE TITLE
Actions should support array matches

### ISSUE THREAD

**Issue by MironV** [Microsoft/BotBuilder#923]
It would be great to have actions support array matches as well, just like intents.matchesAny. This way it'd be cleaner to handle "good bye" messages and things like that.

**Comment by Stevenic** [comment]
So the reason I didn't do that is that it's actually really easy (and way more efficient) to just combine multiple expressions into a regex using parens... So `/^(goodbye|see ya|bye|so long)/I` would matchany of those expressions

**Comment by Stevenic** [comment]
For what it's worth I am planning to support arrays of intents for actions matches in 3.5.

**Comment by chrimc62** [comment]
@Stevenic or @maxpert was this fixed in 3.5?  If so, can you comment and close?

**Comment by Stevenic** [comment]
Yes it was
