### ISSUE TITLE
IConnectorClient and BotAuthentication custom settings

### ISSUE THREAD

**Issue by wiltodelta** [Microsoft/BotBuilder#927]
We get settings using CloudConfigurationManager. IConnectorClient resolved automatically in the dialog when calling context.PostAsync. How to pass the correct parameters (MicrosoftAppId, MicrosoftAppPassword)?

In the case BotAuthentication we wrote a simple custom attribute:

```
public class CustomBotAuthenticationAttribute : BotAuthentication
	{
		public override Task OnActionExecutingAsync(
			HttpActionContext actionContext, CancellationToken cancellationToken)
		{
			MicrosoftAppId = CloudConfigHelper.GetSetting(MicrosoftAppIdSettingName);
			return base.OnActionExecutingAsync(actionContext, cancellationToken);
		}
	}
```

**Comment by willportnoy** [comment]
You might consider dynamically instantiating the BotAthentication attribute (and inheriting from it) with the proper parameters.  @msft-shahins do we have a pattern for this?

**Comment by wiltodelta** [comment]
It is not clear how to write custom implementation IConnectorClientFactory. And in what container to register it. Confused by the constructor in ConnectorClientFactory passing IMessageActivity.

**Comment by willportnoy** [comment]
If you like, you can reuse the global static container on the Conversations class to register your custom implementation:
https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Dialogs/Conversation.cs#L49

The reason the ConnectorClientFactory takes an IMessageActivity is because it needs information like the ServiceUrl:
https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Dialogs/IConnectorClientFactory.cs#L69

I wonder if you could just provide a MicrosoftAppCredentials in a per-request manner and just use the standard IConnectorClientor instead:
https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Dialogs/DialogModule.cs#L85

**Comment by wiltodelta** [comment]
Providing MicrosoftAppCredentials is a best option I think, but I can't understand how to do it.

**Comment by willportnoy** [comment]
Here is some untested, not fully formed code to update the Conversations class static Autofac container.  You'll need to figure out what data to pass to MicrosoftAppCredentials, and whether it's a singleton or per-request.  You might consider providing an Autofac factory Func<MicrosoftAppCredentials> as another option.

            var builder = new ContainerBuilder();
            builder.Register(c => new MicrosoftAppCredentials());
            builder.Update(Conversation.Container);

**Comment by wiltodelta** [comment]
I register BotIdResolver and MicrosoftAppCredentials. And I use custom BotAuthentication attribute (https://github.com/Microsoft/BotBuilder/issues/927#issue-169796892).

It works! Thanks!

```
		public static void RegisterBotDependencies()
		{
			var builder = new ContainerBuilder();

			builder.Register(c => new BotIdResolver(
				CloudConfigHelper.GetSetting("_BotId")))
				.As<IBotIdResolver>()
				.SingleInstance();

			builder.Register(c => new MicrosoftAppCredentials(
				CloudConfigHelper.GetSetting("_MicrosoftAppId"),
				CloudConfigHelper.GetSetting("_MicrosoftAppPassword")))
				.SingleInstance();

			builder.Update(Conversation.Container);
		}
```

**Comment by vovanb** [comment]
Where do you call RegisterBotDependencies ? From  
 public async Task<HttpResponseMessage> Post([FromBody] Activity activity) ?
Can you provide full example?

**Comment by lonche** [comment]
@wiltodelta where do you call RegisterBotDependencies function ?

**Comment by willportnoy** [comment]
@vovanb @lonche usually you can call something like RegisterBotDependencies just once and early in your application, perhaps in a static constructor.
