### ISSUE TITLE
Sending multiple hero card carousel throws a 500 error on Kik

### ISSUE THREAD

**Issue by MironV** [Microsoft/BotBuilder#928]
I'm testing out my hero card carousel on Kik and I get a 500 error. The card is simple: title, subtitle, image, and 2-3 openUrl buttons. It works fine on other services.

**Comment by MironV** [comment]
I'm also getting a 500 error on Kik periodically when I send pure text messages.

**Comment by LarsLiden** [comment]
Can you provide a sample payload that replicates the 500?  Thanks!

**Comment by MironV** [comment]
Here's a simple string that gives me a 500 error: "16/34 (Lighted): 3402' x 75'\n"

Here's another: Set attachmentLayout as "carousel". Then, attach 4 items:

'[{"contentType":"application/vnd.microsoft.card.hero","content":{"title":"Muy Macho Taqueria • 4★","subtitle":"8515 14th Ave S\nSouth Park\nSeattle, WA 98108\n","images":[{"url":"https://s3-media3.fl.yelpcdn.com/bphoto/0cdMS-AxxHv-sokWA6xFBw/ms.jpg","tap":{"type":"openUrl","value":"http://www.yelp.com/biz/muy-macho-taqueria-seattle?utm_campaign=yelp_api&utm_medium=api_v2_search&utm_source=siC8kc5ssN3MtSBk9xFJ3g"}}],"buttons":[{"type":"openUrl","value":"http://maps.google.com/?q=47.5268135070801,-122.31517791748","title":"0.7 mi from KBFI"},{"type":"openUrl","value":"http://www.yelp.com/biz/muy-macho-taqueria-seattle?utm_campaign=yelp_api&utm_medium=api_v2_search&utm_source=siC8kc5ssN3MtSBk9xFJ3g","title":"View Yelp Page"},{"type":"openUrl","value":"tel:+12067633484","title":"Call Restaurant"}]}},{"contentType":"application/vnd.microsoft.card.hero","content":{"title":"Loretta's Northwesterner • 4.5★","subtitle":"8617 14th Ave S\nSouth Park\nSeattle, WA 98108\n","images":[{"url":"https://s3-media3.fl.yelpcdn.com/bphoto/So3XJ5EELeuyK-qRwvQyDg/ms.jpg","tap":{"type":"openUrl","value":"http://www.yelp.com/biz/lorettas-northwesterner-seattle?utm_campaign=yelp_api&utm_medium=api_v2_search&utm_source=siC8kc5ssN3MtSBk9xFJ3g"}}],"buttons":[{"type":"openUrl","value":"http://maps.google.com/?q=47.52587,-122.31513","title":"0.7 mi from KBFI"},{"type":"openUrl","value":"http://www.yelp.com/biz/lorettas-northwesterner-seattle?utm_campaign=yelp_api&utm_medium=api_v2_search&utm_source=siC8kc5ssN3MtSBk9xFJ3g","title":"View Yelp Page"},{"type":"openUrl","value":"tel:+12063279649","title":"Call Restaurant"}]}},{"contentType":"application/vnd.microsoft.card.hero","content":{"title":"Windy City Pie • 5★","subtitle":"Georgetown\nSeattle, WA 98108\n","images":[{"url":"https://s3-media3.fl.yelpcdn.com/bphoto/L6bKEGoAQVVdpbCgNjre0w/ms.jpg","tap":{"type":"openUrl","value":"http://www.yelp.com/biz/windy-city-pie-seattle?utm_campaign=yelp_api&utm_medium=api_v2_search&utm_source=siC8kc5ssN3MtSBk9xFJ3g"}}],"buttons":[{"type":"openUrl","value":"http://maps.google.com/?q=47.5410270690918,-122.312492370605","title":"0.7 mi from KBFI"},{"type":"openUrl","value":"http://www.yelp.com/biz/windy-city-pie-seattle?utm_campaign=yelp_api&utm_medium=api_v2_search&utm_source=siC8kc5ssN3MtSBk9xFJ3g","title":"View Yelp Page"},{"type":"openUrl","value":"tel:+12064864743","title":"Call Restaurant"}]}},{"contentType":"application/vnd.microsoft.card.hero","content":{"title":"Phorale • 5★","subtitle":"8909 14th Ave S\nSouth Park\nSeattle, WA 98108\n","images":[{"url":"https://s3-media1.fl.yelpcdn.com/bphoto/1wEPO5c9b80i0OcJmnKgHg/ms.jpg","tap":{"type":"openUrl","value":"http://www.yelp.com/biz/phorale-seattle?utm_campaign=yelp_api&utm_medium=api_v2_search&utm_source=siC8kc5ssN3MtSBk9xFJ3g"}}],"buttons":[{"type":"openUrl","value":"http://maps.google.com/?q=47.52365,-122.31553","title":"0.8 mi from KBFI"},{"type":"openUrl","value":"http://www.yelp.com/biz/phorale-seattle?utm_campaign=yelp_api&utm_medium=api_v2_search&utm_source=siC8kc5ssN3MtSBk9xFJ3g","title":"View Yelp Page"},{"type":"openUrl","value":"tel:+12065190810","title":"Call Restaurant"}]}}]'

**Comment by LarsLiden** [comment]
At a high level, Kik doesn't support opening URLs from a button.  Kik keyboards will only echo back the text that is displayed on the button as if the user had typed it.   It shouldn't be throwing a 500 though.  Looking into that.

**Comment by MironV** [comment]
Thanks! Even the simple string above (no buttons, no attachments) seems to produce a 500 error. Perhaps it's something to do with special characters used in the string?

**Comment by LarsLiden** [comment]
Bug has been fixed.  Will be included in our next publish.  Thanks for pointing this out.
