### ISSUE TITLE
How to filter and customize group chat messages?

### ISSUE THREAD

**Issue by MironV** [Microsoft/BotBuilder#929]
When a bot is part of a group, it seems to receive all texts in the group. Is there a way to set a filter so the bot only comments when directly addressed or mentioned (i.e., with @bot)? Similarly, when the bot replies how can one control whether the reply is directly addressed to the user (but visible by the group), generic to the group, or private to the user?

**Comment by euanlau** [comment]
I just ran into the same problem when I just tried to use regex to match the message. 

For example, I have `help` as a command. `/^help/i`only works for 1-1 convo. I have to do something like `/^(<at)?.*(at> )?help/`in order to make it work for group convo.

**Comment by hazzik** [comment]
@MironV 
I use following snippet to filter bot mentions in public groups or private messages:
```csharp
protected override async Task MessageReceived(
    IDialogContext context,
    IAwaitable<IMessageActivity> item)
{
    var message = await item;
    if (message.Conversation.IsGroup == false ||
        message.Conversation.IsGroup.HasValue == false ||
        message.GetMentions().Any(m => m.Mentioned.Id == message.Recipient.Id))
    {
        await base.MessageReceived(context, item);
    }
    else
    {
        context.Wait(MessageReceived);
    }
}
```
