### ISSUE TITLE
Create an example of bot sending images

### ISSUE THREAD

**Issue by jieverson** [Microsoft/BotBuilder#93]
I know it's not possible at console. But at Skype/Slack/iFrame it's possible.
In console it could just send a link. (or cacaview, if you are using bash)

**Comment by Stevenic** [comment]
Can I ask which version of Bot Builder you're using? C# or Node.js? For the Node.js version there's an example of sending an image. Look at the TestBot/tests/send-attachment.js test.

For both versions of the library you can send an image by sending a message with an image attachment. The attachment should have a contentType of 'image/jpeg' or something and then return the image link using the contentUrl field.

**Comment by jieverson** [comment]
Thanks for helping. I'm using the Node.js version. You are right. There is an example of sending image. I really hadn't find this example for myself. Maybe it should be more highlighted like the LUIS one (since I think it's actually an important think).

**Comment by jieverson** [comment]
Is it supose to throw Exceptions at console? Or it will just ignore the image?

**Comment by Stevenic** [comment]
It should just ignore the image... I didn't create a basics-sendAttachment example because all of the basics use the TextBot class. I guess I could at least return the link to the image. Let me work on that.

So are you seeing an exception? Whats the exception?

**Comment by Stevenic** [comment]
I'll need to modify the way TextBot prints out messages to also print the links for attachments so I'll try to include this in the next update to the node module and then I'll create an example. look for it towards the end of the week

**Comment by jieverson** [comment]
Actually, I think the problem is that I'm inside a LuisDialog intent handler. You can check at the picture:
![problem_image](https://cloud.githubusercontent.com/assets/1031323/14418739/496679d0-ff97-11e5-9060-2d3cb093981f.PNG)


I'm not sure if I can use that:
`new builder.Message().setText(session, text).addAttachment(...)`
Inside the intent handler.

I think I should send the image with something like:
`session.send({my image result here});`

**Comment by Stevenic** [comment]
Should work fine from within a LuisDialog. You could probably just use `session.send(reply)` instead of `session.endDialog(reply)`. The endDialog() called from the root '/' the way you're doing ends the conversation with the user so could potentially trigger a 'goodbye' message.

**Comment by jieverson** [comment]
Thanks, It seens to be working with this:
```
var reply = 
    new builder.Message()
        .setText(session, text)
        .addAttachment({ fallbackText: text, contentType: 'image/jpeg', contentUrl: picture });
session.send(reply);
```
About the terminal emulator: it actually shows the image url in a json.

**Comment by Orbyt** [comment]
@Stevenic TestBot/tests/send-attachment.js doesnt seem to exist anywhere. Are there any current examples of basic image or attachment sending?

**Comment by Stevenic** [comment]
```
bot.dialog('/picture', [
    function (session) {
        session.send("You can easily send pictures to a user...");
        var msg = new builder.Message(session)
            .attachments([{
                contentType: "image/jpeg",
                contentUrl: "http://www.theoldrobots.com/images62/Bender-18.JPG"
            }]);
        session.endDialog(msg);
    }
]);
```

**Comment by stackty** [comment]
@Stevenic Hello, I just tried to implement this into my code and every time I try to run the code it crashes the Microsoft Bot Framework Channel Emulator. its version is 3.0.0.58 is there an updated emulator or is there another problem?

**Comment by michhar** [comment]
I got @Stevenic's code above for sending an image attachment working in the Command Line Emulator with the addition of `.text()` (returns the json payload):

```js
bot.dialog('/picture', [
    function (session) {
        session.send("You can easily send pictures to a user...");
        var msg = new builder.Message(session)
            .text("Here you go:")
            .attachments([{
                contentType: "image/jpeg",
                contentUrl: "http://www.theoldrobots.com/images62/Bender-18.JPG"
            }]);
        session.endDialog(msg);
    }
]);
```
