### ISSUE TITLE
Skype not playing animated GIFs

### ISSUE THREAD

**Issue by MironV** [Microsoft/BotBuilder#930]
When I send an animated GIF to Skype, it never comes out animated on the other end. It works fine on other channels. Is this just not supported?

**Comment by nickcordrey** [comment]
Yes unfortunately this is not yet supported in Skype.

**Comment by MironV** [comment]
Oh, that's unfortunate. :( Any timeline on when support will be added?

**Comment by chrimc62** [comment]
Closing due to age.

**Comment by Andrea-Orimoto** [comment]
Animated gifs are now supported (since dec 2016), please check the documentation at https://docs.botframework.com/en-us/skype/getting-started/#cards-and-buttons. Closing this issue as resolved, please let us know if you still have questions. Thanks!
