### ISSUE TITLE
Way to specify graceful fallback for hero cards

### ISSUE THREAD

**Issue by MironV** [Microsoft/BotBuilder#931]
It would be nice if there was a way to specify graceful fallback for hero cards so that they would look good on each channel. For example, my standard card carousel with 1 image, some text, and 3 buttons ends up with wildly different results across Messenger, Skype, Kik, GroupMe, Slack, and Telegram.

Right now, I'll be doing if-statements for each channel and tuning but it would be nice if there was a cleaner way to specify how I'd want fallback to be handled.

**Comment by LarsLiden** [comment]
Agreed, but it's a difficult problem as each platform has different constrains around what can be rendered.  Any specific suggestions are more than welcome.   We're also working on a doc to illustrate how each card will be displayed on each platform.

**Comment by MironV** [comment]
It's definitely tough. Some thoughts:

1. A way to specify, per attribute (e.g., buttons) whether to do "strict" or "loose" fallback. Strict would simply not render that part.

2. A way to specify "alt" text for a component. If buttons or some other part can't be rendered, perhaps I can specify alternative text?

3. A way to easily specify what parts should be shown for each channel. This would be easier than figuring out the syntax to send channel-specific commands, but would still allow tailoring for each channel's capabilities.

**Comment by Andrea-Orimoto** [comment]
@MironV we've added this to our backlog, thanks a lot for the suggestions!
