### ISSUE TITLE
Time prompt doesn't allow escape words

### ISSUE THREAD

**Issue by MironV** [Microsoft/BotBuilder#932]
According to the documentation, the built-in prompts allow the user to say things like "cancel" or "nevermind" to get out of the prompt. However, if I try that with the Time prompt, it simply says it didn't recognize the time and to try again.

**Comment by hgjkant** [comment]
It seems I opened a duplicate (#962), since I didn't get it to work with other prompts as well.

**Comment by Stevenic** [comment]
Currently you have to wrap the prompt with a cancel action. Can you point me to the docs you were referring to? It's dated documentation that I should update.

**Comment by chrimc62** [comment]
Closing due to age.  If you still have the problem, please reopen.
