### ISSUE TITLE
Keyboard helper class exists but is not exported

### ISSUE THREAD

**Issue by MironV** [Microsoft/BotBuilder#934]
It seems like the Keyboard helper class exists but is not exported by botkit.js so it's unavailable for external use.

**Comment by Stevenic** [comment]
Good catch. Just checked in a fix. Will be in next build.

**Comment by Andrea-Orimoto** [comment]
Closing this issue, commit is here https://github.com/Microsoft/BotBuilder/commit/c0eb2beffec350254ed099ff50f8c27df063e35b. Will be in the next npm package. Thanks!
