### ISSUE TITLE
[Skype] Allow integration of 3rd party Text to Speech in Skype Calls.

### ISSUE THREAD

**Issue by ankitbko** [Microsoft/BotBuilder#936]
Present Text to Speech functionality of Skype seems to be fairly limited. For instance, it pronounces "16224" as individual digits rather than "sixteen thousand two hundred and twenty four". Whereas Bing Speech supports this. Moreover Skype only supports en-us.
In current SDK I do not see any way for me to plugin 3rd party TTS, I can only pass plain string which is passed to Skype TTS or pass in File URI. It would be great if I could pass raw stream to be played back to user.

I am already using Bing Speech API's for Speech to Text and Intent Recognition, and Bing's TTS seems better that Skype's, using this capability only seems fitting. Bing's Speech returns back raw payload as Content-Type: audio/x-wav. Ability to pass the same to be played by Skype is something which is needed.

**Comment by mghimp** [comment]
In Skype call scenario, you can save the raw audio into file on public storage and give it to Skype to be played as playprompt

**Comment by ankitbko** [comment]
@mghimp But that is too slow. For every response (which changes for every interaction) I will have to save a temporary file first and then give the URI. This approach brings its own set of problems. It would be much better if I could just pass in raw bytes. It is similar to how I get raw stream for "Record" workflow rather than just a file URI. Even Bing Speech returns audio payload rather than file URI. 
It just does not make much sense that my bot, which in this case is just acting as a middleman (taking speech payload from Bing and passing it to skype), will have to do file I/O for every request.

**Comment by mghimp** [comment]
No doubt that would impact performance. I just stated what is currently possible.

**Comment by ankitbko** [comment]
@msft-shahins Do we have alternate way to achieve the above other than first saving to the file? Can we currently pass raw audio stream to be played by skype?

**Comment by msft-shahins** [comment]
@ankitbko I am not sure about Skype plans but currently using custom text to speech engine is not supported. @mghimp solution is the only way that I can think of, if you want to achieve this given the current functionality.

**Comment by KrishnanA** [comment]
Could you try using the SayAs optional parameter in PlayPrompt and see if that helps?

**Comment by aaronfranke** [comment]
How do you use the existing text-to-speech functionality?
