### ISSUE TITLE
Node-RED Connector

### ISSUE THREAD

**Issue by JpEncausse** [Microsoft/BotBuilder#939]
Hi,

I'd like to make a Node-RED connector on top of MS Bot Framework. There is already connectors for some bots.

How can I gracefully insert into the MS Bot Framework without breaking everything? The workflow should be:

- An HTTP POST Request arrives on /path/v1/messages
- Then it so forwarded to a ChatConnector.listen() <= here I need to split request and response and Extract the JSON.
- Then the request is forwarded from the connector to a LUIS node <= here I need a smart dialog "node" that take a string, ask LUIS, return the intent
- Then the intent is forwarded a smart dialog return a string
- Then the string is returned throught the HTTP response in JSON

Any suggestion ?

**Comment by danmarshall** [comment]
Hi @JpEncausse this is a very cool idea. I'm not sure that the concepts of a bot will map directly into a visualization, since there can be multiple entry and exit points. The diagram may end up looking like spaghetti for even a simple bot :)

**Comment by JpEncausse** [comment]
Agreed, Node-RED handle multiple input and output.

My Idea was to build 2 kind of graph:
- a Dialog graph to display a kind of waterfall
- a Bot graph that will link multiple Dialog graph

Then I still look for a smart way to split dialog's text and code because it's not the same people doing that.

I dig a little bit in MS code and see that a Dialog quickly answer HTTP 202 then it seems session.send() will later send a request ? So it seem possible to split request and response. 

An other tricky thing I didn"'t figure out is how to keep discussions step in the graph.

**Comment by danmarshall** [comment]
Hi @JpEncausse I am going to close this since there is nothing much for us to track. I suggest creating your own open source project for this cool idea :)

**Comment by JpEncausse** [comment]
My question was about how to do that without breaking BotBuilder. 
- What best entry point to use ?
- Do you have already that usecase in mind ? 

I guess I should implement a custom Dialog.

**Comment by danmarshall** [comment]
@willportnoy do you have any suggestion here?

**Comment by willportnoy** [comment]
I don't have a lot to suggest.  Custom IDialogs are good for custom, self-contained components to be reused.  Using graphical representations of state transitions seems to be a common theme in visual programming languages.

The messages to the bot and the messages to the user are always on separate http requests in version 3.
