### ISSUE TITLE
WebChat doesnt fire "UserAddedToConversation" when page is loaded.

### ISSUE THREAD

**Issue by taylorgibb** [Microsoft/BotBuilder#94]
Currently we get the generic say "Hi" if you want to chat. It would be great if that was done away with - if for nothing else it will make translations of the initial message possible. Instead, could we fire the "UserAddedToConversation" message type when a user opens the chat. That way we can customize the greetings.

**Comment by Stevenic** [comment]
Merging with an existing request on UserVoice:

https://feedback.botframework.com/forums/354219-bot-connector/suggestions/13463595-suggestion-web-chat-component-initial-message
