### ISSUE TITLE
Intent and dialog handler Node.JS

### ISSUE THREAD

**Issue by VishalWaman** [Microsoft/BotBuilder#947]
I have case where we need common code to handle intent =  help and dialog= help.

Now I need to write separate code for dialog and intent 

`bot.dialog('menu', [
    function (session) {....`

`intents.matches('menu', [
    function (session) {
`

Is there any way that manages both at common function ?

**Comment by jorenl** [comment]
The easiest solution is probably to just invoke the menu dialog from your intent handler:

```
var intents = new builder.IntentDialog();
bot.dialog('/', intents);
intents.matches(menu, function(session) {
    session.beginDialog('menu');
});

bot.dialog('menu', [
    function (session, args, next) {
        ....
    },
    ....
]);
```

Does that work?

**Comment by VishalWaman** [comment]
Yes to works for me...
