### ISSUE TITLE
Beginner Questions

### ISSUE THREAD

**Issue by jeromekjerome** [Microsoft/BotBuilder#95]
I've been writing bots since 2008 and have used VS on and off in the process but I've been out of the loop for a long time so getting up to speed is going to take some time.  I'm trying to work my way through the bot template and I'm not able to match up the instructions with the tool.  Can anyone suggest a detailed walkthru?  

Here's where I'm at.  I got all the installation issues fixed and installed except for the VS2015AsurePack.  I assume this should not prevent me from completing a test of the template bot.  Now I've reached the words "When the application is built and deployed the web browser will open and display the application Default.htm file (which is part of the Bot Application project)."  VS has a build tab so I can build it without errors.  

Next step?  "Deploy?"  Connect to Azure Subscription?  If yes, publish to App Service or publish to API Apps?  And then?

Obviously, I need some handholding that is probably a little too intense for this forum.  Can anyone suggest a walkthru or tutorial?

**Comment by tomlm** [comment]
You can deploy to any environment you want, you don't have to deploy to Azure.  Whatever you are comfortable with, but the end requirement is that there is a URL which you register as an endpoint with the system. 

That said, publish to azure is a almost one-click solution to getting yourself on the web.
