### ISSUE TITLE
Welcome Message

### ISSUE THREAD

**Issue by filipeperdigaosousa** [Microsoft/BotBuilder#950]
Hi.

Since the new version was lanched I can't see references to welcome messages.

Is it possible to use something like that on this new version?

**Comment by willportnoy** [comment]
Do you mean the Node firstRun middleware?

https://docs.botframework.com/en-us/node/builder/chat-reference/classes/_botbuilder_d_.middleware.html#firstrun

**Comment by filipeperdigaosousa** [comment]
This implies a first user interaction to wake up the bot. There are some
feature that can trigger the bot when the user joins to the conversation?

Filipe Sousa

Skype: filipe.p.sousa
Telemóvel: (+351) 934405929
LinkedIn: pt.linkedin.com/in/filipeperdigaosousa


2016-08-09 21:16 GMT+01:00 Will Portnoy <notifications@github.com>:

**Comment by willportnoy** [comment]
You can look for other activity types e.g. https://docs.botframework.com/en-us/csharp/builder/sdkreference/activities.html but I believe some channels have requirements that require the user to interact with the bot first.

**Comment by kevinport** [comment]
It would be nice that the bot can tell the user what he can do in a welcome message,in every activity and channel.

With out these the user doesnt know what to do, so the user first have to test what the bot understands

**Comment by willportnoy** [comment]
@kevinport I agree that's a good feature to have any bot - some sort of welcome message.

I think the per-channel requirements that the user talk to the bot first (even with just a "hello") is to prevent spam bots.

I'm going to close this issue for now, but feel free to open a new issue for further discussion.

**Comment by kevinport** [comment]
This problem is solved very well in the webchat. It would be nice if you can make this static text editable. But in all other channel i miss this function.. to prevent spam bots, i think a welcome message doest help, if some one wants to write a spam bot he simply writes it.

The skype bot and the summarizer and the bing news bot already use a welcome message...

How did they do this?

**Comment by willportnoy** [comment]
Yes, that's an often request feature for WebChat.  It's on our backlog.

It seems likely those bots use one of the other types of activities to send the welcome message:
https://docs.botframework.com/en-us/csharp/builder/sdkreference/activities.html

**Comment by stanleycyang** [comment]
I was looking into building a welcome request for Slack @willportnoy. Is there a way to handle that scenario already?
