### ISSUE TITLE
How does dialog.matches work?

### ISSUE THREAD

**Issue by slidenerd** [Microsoft/BotBuilder#951]
Sorry if this seems like a silly question but when I debugged the multiturn example, I see that it fires the answerQuestion for anything and everything and there is no output on the screen. Can someone please tell me what dialog.matches is doing in below. It matches with Acquistions , IpoDate, Description and everything thing else. One more question would be the fact that in all other examples, the waterfall model would involve a bunch of different dialogs and several functions inside the same dialog. How come only 2 functions were needed here. 

![test](https://cloud.githubusercontent.com/assets/5139030/17524905/18272cb6-5e7e-11e6-892f-55cdf8bc85bf.gif)

**Comment by Stevenic** [comment]
So in the GIF you've put your breakpoints on the outer function... Those breakpoints would be hit every time you run the bot. Are you saying the multi-turn example isn't working for you?

**Comment by chrimc62** [comment]
Closing due to age.  If you still have the issue please reopen.
