### ISSUE TITLE
Intercepting every message between bot and user

### ISSUE THREAD

**Issue by srozga** [Microsoft/BotBuilder#954]
I want to log every message between the user and the bot. There are parts of the bot framework that I cannot access to insert this type of behavior. Specifically, the FormDialog. The class is sealed. Even if it weren't, there is no way to override a private PostAsync to catch all the calls. Is there any other mechanism to intercept the messages through the IDialogContext short of copy/pasting the entire class into my project?

**Comment by willportnoy** [comment]
You can register your own IBotToUser implementation:

https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Dialogs/DialogModule.cs#L183

For example, this is something we do in the unit tests to capture all outgoing messages.

https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Tests/Microsoft.Bot.Builder.Tests/DialogTestBase.cs#L99

You can also intercept from user to bot with IPostToBot.

**Comment by willportnoy** [comment]
I've added this question/answer to the technical faq:

https://docs.botframework.com/en-us/technical-faq/#how-can-i-intercept-all-messages-between-the-user-and-my-bot

**Comment by willportnoy** [comment]
I'm going to close this issue, but feel free to open a new issue for further discussion.
