### ISSUE TITLE
Maintain state for conversations

### ISSUE THREAD

**Issue by afficionaddo** [Microsoft/BotBuilder#958]
Hi, I am new to bots...I recently worked on a bot for maintaining state of the conversation.

I used BotState for a start.

My doubts are below:

1. Where is there data stored and for how long does it persist.
2. Is it recommended to maintain state of the conversation or should I go for something else?
3. Any example of state-maintain of a conversation you may recommend?

**Comment by willportnoy** [comment]
1. @msft-shahins do you know the lifetime of the bot state data?
2. It's a good place to start, when developing your bot.  It's pretty easy to transition to a different store by implementing the appropriate interfaces.
3. In the C# version of the BotBuilder, this is where the serialized dialog state lives.  In Node, it's the dialog state property bag.  In both versions, the user, group, and private data bags are all stored here.

**Comment by afficionaddo** [comment]
Thanks for the informative reply @willportnoy .

Currently, I am developing an ecommerce bot which shall have around 5,000 end-users.

Now for the type of a bot; to maintain state of the conversation, do you think BotState is the correct approach?
or
I should save up the data in a database and perform "to & fro" for the conversation state data?

**Comment by willportnoy** [comment]
There is a limitation on how much data you can store in the bot data bags - about 64K, if I recall correctly.  But each user and conversation can have their data bags.  So I would start there until it becomes an actual issue.

**Comment by msft-shahins** [comment]
BotState is persisted and they are not getting expired by the State API service.

**Comment by afficionaddo** [comment]
Thnx @willportnoy and @msft-shahins for the reply.

But this arises a risk in my mind:
1. BotState service shall be a dependancy.
2. Is the storage for BotState pluggable?

**Comment by willportnoy** [comment]
If you use the Bot Framework's default implementation of IStateClient, then it would be a dependency for your bot.

Yes, you can implement your own IStateClient or IBotData.

**Comment by willportnoy** [comment]
I'm going to close this issue - feel free to open a new issue for further discussion.
