### ISSUE TITLE
oauth2 authentication

### ISSUE THREAD

**Issue by ahmettaha** [Microsoft/BotBuilder#96]
Hello
Is it possible to add a login feature or a auth2 authentication with the bot builder?

**Comment by Stevenic** [comment]
I'm actually working on something that will enable that for the node.js version. Are you using C# or Node?

**Comment by ahmettaha** [comment]
C# :)

**Comment by Stevenic** [comment]
moved to UserVoice:

https://feedback.botframework.com/forums/354222-bot-builder-sdk/suggestions/13463451--c-oauth2-authentication
