### ISSUE TITLE
[Node] Entities are lower case

### ISSUE THREAD

**Issue by hgjkant** [Microsoft/BotBuilder#963]
Hi,
In my bot (v3.2.2) entities directly passed in an utterance are transformed to lowercase. If I respond to a prompt the response is case sensitive though.

**Comment by willportnoy** [comment]
I assume this is the Node version of the SDK?

**Comment by hgjkant** [comment]
Oh my bad, it is.

**Comment by Stevenic** [comment]
Can you provide an example? I'm not completely following you? Are you using LUIS?

**Comment by hgjkant** [comment]
I am using LUIS. For example, a user can change the name the bot uses to refer to the user by saying either `Change my name to FooBar` or `Change my name`, after which the bot prompts for the new name. In the first case, the bot responds with `Hi foobar` (all lowercase), but in the second case (after the prompt) the bot responds with `Hi FooBar`. 

I've tried the same utterance on luis.ai itself (in the `publish current application` dialog), and there the entity was also lowercase, so it seems to be a LUIS issue.

**Comment by willportnoy** [comment]
The LUIS response includes a pointer to the offset within the original query string - maybe you can use that.  For example, here is the C# exposition of that:

https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Luis/Models/EntityRecommendation.cs#L61

**Comment by CarolHanna** [comment]
This is by design the entities detected are all lowercase. Will add this as request to our backlog

**Comment by yshahin** [comment]
as @willportnoy mentioned the start and end index are char indexes on the original text lower-cased, so you can store the raw text and use them to extract the unmodified text.

**Comment by hgjkant** [comment]
I see, I will use this as a workaround, thanks.

**Comment by praneethnooli** [comment]
I'm facing the same issue now. May I know how to resolve this?
