### ISSUE TITLE
Messages History

### ISSUE THREAD

**Issue by filipeperdigaosousa** [Microsoft/BotBuilder#966]
Is it possible to store the message history for a conversation? Enabling to leave the bot page and return to it in the future and see the previous messages?

**Comment by willportnoy** [comment]
The DirectLine api will buffer messages for just a limited time:

"The Direct Line API does not store messages indefinitely. Your client application must pick them up quickly before they are deleted."
https://docs.botframework.com/en-us/restapi/directline/

But your question is probably more oriented toward a specific channel.  I don't think the WebChat channel will store message history, for example.
