### ISSUE TITLE
Get Skype Group Name

### ISSUE THREAD

**Issue by graphnode** [Microsoft/BotBuilder#969]
Hello,

I noticed that [IIdentity](https://docs.botframework.com/en-us/node/builder/chat-reference/interfaces/_botbuilder_d_.iidentity.html) contains an optional [name property](https://docs.botframework.com/en-us/node/builder/chat-reference/interfaces/_botbuilder_d_.iidentity.html#name) which is used to get an User's name.

When it is used to identify skype groups, no name is available. Could this feature be implemented?

Kind regards.

**Comment by nickcordrey** [comment]
Thanks for the feedback and yes we will definitely consider this for a future release.

**Comment by graphnode** [comment]
Any update on this?
