### ISSUE TITLE
Bot deployed in Azure calls MakeRoot numerous times

### ISSUE THREAD

**Issue by srozga** [Microsoft/BotBuilder#970]
I know I have seen this issue before if my Dialog was not Serializable, but I have since solved it and I have tested my bot on the emulator without a problem.

MakeRoot is referring to the MakeRoot func in Conversation.SendAsync(activity, MakeRoot); The method only gets called once per conversation (I believe).

We have now deployed the Bot into Azure and are speaking to it using the DirectLine API. We are having a problem in that when any message is received by the bot, the Dialog is re-instantiated using MakeRoot. Any tips on how to debug this if it works through the emulator with a local bot without a problem?

**Comment by willportnoy** [comment]
There's a few things to consider.

1. If your bot is throwing an exception in some dialog (due to running in azure), then that exception is propagated back through the dialog call stack until it escapes through the root.  On the next message, MakeRoot will be called again to restart the conversation.
2. If you fail to call context.Wait or context.Done on all code paths, there could be an exception that leads to the first situation.
3. If you added a custom IStateClient, then the dialog stack might not be serializing properly and could lead to the appearance that the conversation should be freshly started each time.

**Comment by srozga** [comment]
In all of these cases, is there some sort of logging that the framework provides? For example, if 1 or 2 occur, am I guaranteed to see an exception float up the chain to Conversation.SendAsync?

**Comment by srozga** [comment]
We managed to reproduce this issue using the EchoStateDialog. The "weird" thing we are doing is that we are doing a Conversation.SendAsync to the dialog from the ConversationUpdate event. The reason we are doing this is that when we want to welcome the user back with an intelligent message. The user's response will then be processed by the dialog.

This works perfectly fine in the emulator but not Azure. Very curious. We do have a workaround but I wonder if you could see any reason why there would be a problem with this approach in the Azure context?

```
        private IDialog<object> MakeRoot()
        {
            return new EchoStateDialog();
        }

        [HttpPost]
        public async Task Post([FromBody] Activity activity)
        {
            if (activity != null && activity.GetActivityType() == ActivityTypes.Message)
            {
                try
                {
                    await Conversation.SendAsync(activity, MakeRoot);
                }
                catch (Exception ex)
                {
                    _logger.LogError("Error while posting Activity into Conversation.\n" + ex);
                }
            }
            else
            {
                await HandleSystemMessage(activity);
            }
        }

        private async Task<Activity> HandleSystemMessage(Activity activity)
        {
            if (activity.Type == ActivityTypes.DeleteUserData)
            {
                // Implement user deletion here
                // If we handle user deletion, return a real message
            }
            else if (activity.Type == ActivityTypes.ConversationUpdate)
            {
                await Conversation.SendAsync(activity, MakeRoot);
            }
            else if (activity.Type == ActivityTypes.ContactRelationUpdate)
            {
                // Handle add/remove from contact lists
                // Activity.From + Activity.Action represent what happened
            }
            else if (activity.Type == ActivityTypes.Typing)
            {
                // Handle knowing tha the user is typing
            }
            else if (activity.Type == ActivityTypes.Ping)
            {
            }

            return null;
        }
```

**Comment by willportnoy** [comment]
Here is the test for the "root dialog throws exception propagate to user":

https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Tests/Microsoft.Bot.Builder.Tests/DialogTaskTests.cs#L62

It should occur if "await" is applied to all IAwaitables.

In the latest version, we will also post the exception to the user if the debugger is attached:

https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Dialogs/DialogTask.cs#L443

I can't imagine why there would be a difference in Azure.  Do other aspects of the bot work in Azure?  i.e. can it send messages back to the user?

**Comment by srozga** [comment]
Thanks, no exceptions happening. Everything worked in the bot except that one part. We refactored the code so that we dont call SendAsync until an actual message comes in. The refactor actually makes more sense in our case. That being said, this behavior was strange. Maybe we will get a better chance to dig into it later on.

**Comment by willportnoy** [comment]
Thank you for the update!  I'm going to close this issue for now, until we get any further information.
