### ISSUE TITLE
[Node.js]Is it possible to have carousel cards with dialog action?

### ISSUE THREAD

**Issue by yaalisri** [Microsoft/BotBuilder#972]
I need to display carousel card with dialog action. It supports only **imback** which prompts the user to select any option. But in my case, user can either select any one of the option or can start a new flow by sending a new message to the bot. Is there any way to achieve this?
Also is there a limit to the number of cards when we use carousel? Because it allows only 3 for me.

**Comment by Stevenic** [comment]
The carousel card limits are technically dependent on the channel (skype or facebook) but both currently have a 10 card limit.  As for the use of __imBack__ to invoke a dialog action. If you register a `{ matches: /^command/i }` for your dialog action that will invoke the action when the imBack button is pressed.  Just make `command` equal to your imBack value.

**Comment by yaalisri** [comment]
Thanks Steve. I will try this and let you know if it works.

**Comment by Stevenic** [comment]
any luck?
