### ISSUE TITLE
[Node.js]How to extract entity from a sentence which doesn't have any intent

### ISSUE THREAD

**Issue by yaalisri** [Microsoft/BotBuilder#974]
I have to extract entity from a phrase if even it doesn't have any intent. Since we cannot check **None** intent, is there any other possibility to extract the entity?

**Comment by jorenl** [comment]
The most recent version of the Node SDK no longer ignores None intents (if they are given the highest score by LUIS). You should be able to attach an intent handler for none, and then read out the entities.

You might have to run `npm install botbuilder --save` to upgrade your SDK and store the dependency.

Let me know if that doesn't resolve your issue!

**Comment by Stevenic** [comment]
Yes... You should be able to handle None now.
