### ISSUE TITLE
Emulator recycles conversation ids

### ISSUE THREAD

**Issue by srozga** [Microsoft/BotBuilder#975]
It seems like the bot emulator recycles conversation ids every time that it restarts. Every time I restart the emulator, the new conversation id is 8a684db5. I assume this is because the conversation id is based on the conversation name, is that correct?

**Comment by willportnoy** [comment]
The emulator might recycle conversation ids, but the emulator is also implicitly clearing the bot data bag storage when it restarts, because it's stored in the process memory.

Yes, it looks like the conversation ID is the hexadecimal encoding of the conversation name hash code.

**Comment by willportnoy** [comment]
I'm going to close this issue for now, but feel free to open a new issue for further discussion.
