### ISSUE TITLE
Got InternalServerError while try deploying to azure from github

### ISSUE THREAD

**Issue by tungnt244** [Microsoft/BotBuilder#976]
```
var restify = require('restify');
var builder = require('botbuilder');

//=========================================================
// Bot Setup
//=========================================================

// Setup Restify Server
var server = restify.createServer();
server.listen(process.env.port || process.env.PORT || 3978, function () {
   console.log('%s listening to %s', server.name, server.url); 
});
  
// Create chat bot
var connector = new builder.ChatConnector({
    appId: process.env.MICROSOFT_APP_ID,
    appPassword: process.env.MICROSOFT_APP_PASSWORD
});
var bot = new builder.UniversalBot(connector);
server.post('/api/messages', connector.listen());

//=========================================================
// Bots Dialogs
//=========================================================

bot.dialog('/', function (session) {
    session.send("Hello World");
});

// Serve a static web page
server.get(/.*/, restify.serveStatic({
	'directory': '.',
	'default': 'index.html'
}));
```
![image](https://cloud.githubusercontent.com/assets/20721437/17591670/56d937ec-6009-11e6-8e1a-21d4f84b80f9.png)
![image](https://cloud.githubusercontent.com/assets/20721437/17591698/71d6c582-6009-11e6-8448-0a6099c5abfd.png)
Could anyone help me. I have no idea to deal with this.

**Comment by danmarshall** [comment]
Can you change this line of code:
```
server.post('/api/messages', connector.listen());
```

to:
```
server.post('/api/messages', connector.verifyBotFramework(), connector.listen());
```

**Comment by tungnt244** [comment]
I folow this tutorial https://github.com/fuselabs/echobot , but i replace the code in server.js with the sample code hello-ChatConnector

**Comment by danmarshall** [comment]
I see you are serving the static index.html file - which means that you ought to be able to see https://tungchatbot.azurewebsites.net , but that returns a 500. Can you run this locally?

**Comment by tungnt244** [comment]
when i run server.js locally i can see it on localhost:3978

**Comment by tungnt244** [comment]
I found my problem, i'm new with nodejs so i don't change the package.json file ( dependencies) when i change the code using new feature.
