### ISSUE TITLE
Typing activity exception

### ISSUE THREAD

**Issue by wiltodelta** [Microsoft/BotBuilder#977]
I get an exception when trying to handle typing activity. I tried in Slack channel.

Exception: Microsoft.Rest.HttpOperationException: Precondition Failed    at Microsoft.Bot.Connector.ErrorHandling.HandleError<HttpOperationResponse`1 result|ObjectT> in C:\Projects\GitHub\BotBuilder-NuGet3.1.0\CSharp\Library\Microsoft.Bot.Connector\ErrorHandling.cs:line 32    at Microsoft.Bot.Connector.BotStateExtensions.<SetConversationDataAsync>d*9.MoveNext() in C:\Projects\GitHub\BotBuilder-NuGet3.1.0\CSharp\Library\Microsoft.Bot.Connector\StateAPI\BotStateExtensions.cs:line 227 --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Microsoft.Bot.Builder.Dialogs.Internals.ConnectorStore.<Microsoft-Bot-Builder-Dialogs-Internals-IBotDataStore<Microsoft-Bot-Connector-BotData>-SaveAsync>d*3.MoveNext() in C:\Projects\GitHub\BotBuilder-NuGet3.1.0\CSharp\Library\Dialogs\BotData.cs:line 211 --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Microsoft.Bot.Builder.Dialogs.Internals.CachingBotDataStore.<Save>d*10.MoveNext() in C:\Projects\GitHub\BotBuilder-NuGet3.1.0\CSharp\Library\Dialogs\BotData.cs:line 421 --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Microsoft.Bot.Builder.Dialogs.Internals.CachingBotDataStore.<Microsoft-Bot-Builder-Dialogs-Internals-IBotDataStore<Microsoft-Bot-Connector-BotData>-FlushAsync>d*5.MoveNext() in C:\Projects\GitHub\BotBuilder-NuGet3.1.0\CSharp\Library\Dialogs\BotData.cs:line 281 --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Microsoft.Bot.Builder.Dialogs.Internals.BotDataBase1.<FlushAsync>d__9.MoveNext() in C:\Projects\GitHub\BotBuilder-NuGet3.1.0\CSharp\Library\Dialogs\BotData.cs:line 456 --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Microsoft.Bot.Builder.Dialogs.Internals.PersistentDialogTask.<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d__61.MoveNext() in C:\Projects\GitHub\BotBuilder-NuGet3.1.0\CSharp\Library\Dialogs\DialogTask.cs:line 413 --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Microsoft.Bot.Builder.Dialogs.Internals.PostUnhandledExceptionToUserTask.<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d__5`1.MoveNext() in C:\Projects\GitHub\BotBuilder-NuGet3.1.0\CSharp\Library\Dialogs\DialogTask.cs:line 437

```
	[BotAuthentication]
	public class ActivityController : ApiController
	{
		private readonly List<string> _supportedActivityTypes = new List<string>
		{
			ActivityTypes.Message,
			ActivityTypes.ContactRelationUpdate,
			ActivityTypes.ConversationUpdate,
			ActivityTypes.Typing
		};

		[HttpPost]
		[Route("Api/Activities")]
		public async Task<IHttpActionResult> ReceiveAsync(
			[FromBody] Activity activity)
		{
			if (_supportedActivityTypes.Contains(activity.Type))
			{
				await Conversation.SendAsync(activity, () => new BotDialog());
			}

			return StatusCode(HttpStatusCode.Accepted);
		}
	}
```

```
	[Serializable]
	public class BotDialog : IDialog
	{
		public async Task StartAsync(IDialogContext context)
		{
			context.Wait(ActivityReceivedAsync);
		}

		public async Task ActivityReceivedAsync(IDialogContext context, IAwaitable<IActivity> argument)
		{
			IActivity activity = await argument;

			switch (activity.Type)
			{
				case ActivityTypes.Message:
					await MessageReceivedAsync(context, (IMessageActivity) activity);
					break;
				case ActivityTypes.ContactRelationUpdate:
					await ConversationUpdateReceivedAsync(context, (IConversationUpdateActivity) activity);
					break;
				case ActivityTypes.ConversationUpdate:
					await ContactRelationUpdateReceivedAsync(context, (IContactRelationUpdateActivity) activity);
					break;
				case ActivityTypes.Typing:
					await TypingReceivedAsync(context, (ITypingActivity)activity);
					break;
			}
		}

		public async Task MessageReceivedAsync(IDialogContext context, IMessageActivity argument)
		{
			await context.PostAsync(string.Format("Message Received: {0}", argument.Text));
			context.Wait(ActivityReceivedAsync);
		}

		public async Task ConversationUpdateReceivedAsync(
			IDialogContext context, IConversationUpdateActivity argument)
		{
			await context.PostAsync("Conversation Update Received");
			context.Wait(ActivityReceivedAsync);
		}

		public async Task ContactRelationUpdateReceivedAsync(
			IDialogContext context, IContactRelationUpdateActivity argument)
		{
			await context.PostAsync("Contact Relation Update Received");
			context.Wait(ActivityReceivedAsync);
		}

		public async Task TypingReceivedAsync(
			IDialogContext context, ITypingActivity argument)
		{
			await context.PostAsync("Typing Received");
			context.Wait(ActivityReceivedAsync);
		}
	}
```

**Comment by willportnoy** [comment]
@msft-shahins for visibility - this might be related to https://github.com/Microsoft/BotBuilder/issues/960

**Comment by willportnoy** [comment]
This commit will help serialize message handling within the scope of a conversation/user: https://github.com/Microsoft/BotBuilder/commit/8f441469e1e80b5d7712cbf81bc3eacc9f71e3a4

**Comment by willportnoy** [comment]
This commit has been released: https://github.com/Microsoft/BotBuilder/releases/tag/NuGet3.2.0

I'm going to close this issue - feel free to open a new issue for further discussion.
