### ISSUE TITLE
context.Forward sometimes not working

### ISSUE THREAD

**Issue by asram363** [Microsoft/BotBuilder#978]
I have a Luis dialog, where each intent handler forwards to another Luis dialog. For instance, I have something like this:
[LuisIntent("intent.first")]
public async Task FirstDialog(IDialogContext context, LuisResult result)
{
	await context.Forward(new NextDialog(), ResumeAfter, new Activity { Text = result.Query }, CancellationToken.None);
}

Sometimes, when I type something to the bot, it gets to the context.Forward line but then just goes to the next line and ends without actually going into NextDialog. Other times, when I type the exact same thing, it does go into NextDialog and works properly. 
Any ideas on what the issue could be with it sometimes working and sometimes not? How could it get to the context.Forward line but then not actually go into the NextDialog?

**Comment by willportnoy** [comment]
What does NextDialog do?

For example, does NextDialog.StartAsync call context.Wait(MessageReceived) on all code paths?

**Comment by willportnoy** [comment]
I'm going to close this issue - @asram363 feel free to open a new issue with more information.
