### ISSUE TITLE
Could not test my bot in "Test Bot" link

### ISSUE THREAD

**Issue by giriganapathy** [Microsoft/BotBuilder#979]
Hello Steve,

I created a new bot today using the v3 botbuilder sdk.  I faced couple of issues:
1. Using Emulator, got the below error: ChatConnector: receive - no security token sent BOT
2. After registered in Botconnector, I could not do a Test Bot due to the below error:
"NotFound: The resource you are looking for has been removed, had its name changed, or is temporarily unavailable."

This is my endpoint url:
https://vzentapp.azurewebsites.net/api/messages

Bot Id: 56fbf306-c96a-4e82-bfbc-af0a095980d3

Could you please take a look and let me know at the earliest.

Regards,
Giri G.

**Comment by Thegaram** [comment]
Can you manually reach your endpoint (e.g. using Postman)? Are you using the correct id and secret in the emulator?

**Comment by danmarshall** [comment]
Hi @giriganapathy this seems to be an issue within Azure itself. Can you redeploy using a different name? I have seen this issue when re-using the same name for an Azure website, for example, if you delete the website and re-create a new one with the same name.

**Comment by giriganapathy** [comment]
Hello dan, It worked after creating  a new set of files in azure. Thanks.

Btw, is there any online reference available to understand the various examples (say: carousel, herocard) in node js platform.  Could you please give me a pointer to start.

Regards,
Giri G.

**Comment by danmarshall** [comment]
Hi Giri, please see the examples for Skype and Facebook for example code for cards and carousels: https://github.com/Microsoft/BotBuilder/tree/master/Node/examples
Glad your bot is working now :)

**Comment by giriganapathy** [comment]
Thanks.
