### ISSUE TITLE
Unauthorized 401 for any call made to luis-actions.cloudapp.net

### ISSUE THREAD

**Issue by aravindbaskaran** [Microsoft/BotBuilder#981]
I'm trying to use action fulfillment to get parameters missing in the intent. The intent gets saved, and the model API returns
```json
{
  "query": "what's the status huh?",
  "topScoringIntent": {
    "intent": "Status",
    "score": 0.9957357,
    "actions": [
      {
        "triggered": false,
        "name": "Status",
        "parameters": [
          {
            "name": "username",
            "required": true,
            "value": null
          }
        ]
      }
    ]
  },
  "entities": [],
  "dialog": {
    "prompt": "What's your username?",
    "parameterName": "username",
    "contextId": "e147a5b1-dde2-40f1-b24b-e1c141dbeb56",
    "status": "Question"
  }
}
```

However the actions endpoint configured for the bot framework always throws 401 Unauthorized - https://luis-actions.cloudapp.net/api/v1/botframework?app-id=18543d0e-e419-4aac-bae4-c662a75e9f54&subscription-key=**********

What am I missing? Appreciate any info.

Thanks!

**Comment by CarolHanna** [comment]
We have a issue resulting from deprecating botframework v1 UI. Will working on migrating to v3 to fix this.

**Comment by aravindbaskaran** [comment]
OK, I'm on v3, the model APIs still work, but unable to do the actions fulfillment because of the schema difference in preview

**Comment by CarolHanna** [comment]
LUIS our fulfillment is not compatible with v3 it an issue from the LUIS side and we are working on the fix. Can I ask which fulfillment channel are you using?

**Comment by aravindbaskaran** [comment]
HTTP JSON request type

**Comment by yshahin** [comment]
We are working on a fix and it will be out soon

**Comment by Andrea-Orimoto** [comment]
@aravindbaskaran I'm closing this issue, since it's being addressed by the LUIS team. Please reopen or let us know if you need anything else. Thank you!
