### ISSUE TITLE
Suggestion: Process audio input inside IntentDialog module

### ISSUE THREAD

**Issue by javi-jamaa** [Microsoft/BotBuilder#983]
Currently ```IntentDialog``` is implemented to use only text as an input and to call a service, i.e: LUIS using ```LuisRecognizer```  to discover the intent.
Would be nice that ```IntentDialog``` will let also audio as an input and internally it will call to Bing Speech (or another  speech-to-text) to translate the voice to text and after it call to the favourite ```*Recognizer```.

**Comment by Andrea-Orimoto** [comment]
Thanks for the suggestion, we've added it to our backlog.
