### ISSUE TITLE
Using Cards with LuisDialog C#

### ISSUE THREAD

**Issue by GerryWilko** [Microsoft/BotBuilder#986]
Hi,

What is the best practice for returning Attachments or more specifically Cards in conjunction with Luis?

It seems to be half there at the moment... Node.JS has the LuisRecognizer but C# still using legacy Luis structure?

So once in the LuisDialog you don't have access to the activity unless you keep track of this manually, is this the best practice? Seems messy

Or ditch LuisDialog for now and handle all requests to Luis manually until the new Bot Framework is updated.

Thanks,
Gerard

**Comment by willportnoy** [comment]
I recently made a commit to make it possible to access the activity in the intent handler:

https://github.com/Microsoft/BotBuilder/commit/f156a60880e86f7b853b1f94a5546386436ac3d0

**Comment by willportnoy** [comment]
Regarding "best practice for returning Attachments or more specifically Cards in conjunction with Luis", what do you mean?  if you use the MakeMessage method off the context passed to the intent handlers, you'll be able to fill it in with all the cards and attachments.

**Comment by GerryWilko** [comment]
Thank you Will. I was following the SimpleAlarm example and missed that you can use the MakeMessage method.
