### ISSUE TITLE
Bot Framework Emulator crashes with responses containing angle brackets and text

### ISSUE THREAD

**Issue by rodtoll** [Microsoft/BotBuilder#99]
When sending a response from my bot which takes the form of angle brackets with text in them followed by more text the bot framework emulator crashes everytime.

Example text:
<a> a

Taking the text out of the angle bracket or the trailing text out avoids the crash. So these don't crash:
<> 
<a>

**Comment by tomlm** [comment]
I just fixed, update your emulator.

**Comment by rodtoll** [comment]
Confirmed: That did the trick, thank you!
