### ISSUE TITLE
How to send "greeting page" to FB messenger bot

### ISSUE THREAD

**Issue by afficionaddo** [Microsoft/BotBuilder#991]
Hi, I am building a bot and would like to ask:
What's the way to send a greeting page to FB messenger bot through Bot framework c#? You know when a bot user comes and uses it for the first time?

**Comment by willportnoy** [comment]
You might consider storing a flag in the per-user bot data bag to track whether you've sent the initial greeting message to a particular user:

https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Dialogs/IBotData.cs#L47

**Comment by afficionaddo** [comment]
Thanks for the reply @willportnoy !

But actually my query was 
1. How to initiate message for GreetingPage through BOT framework?
2. Do I need to use "channel" field to send FB-specific json for greeting screen?
3. How will I load this screen initially....any ideas?

**Comment by willportnoy** [comment]
Do you receive a non-message activity for when the user initiates a conversation with the bot?

https://docs.botframework.com/en-us/csharp/builder/sdkreference/activities.html

Generally, we recommend the ChannelData field for native channel data.

**Comment by willportnoy** [comment]
I'm going to close this issue, but feel free to open a new issue for further discussions.

**Comment by JpEncausse** [comment]
Hi,
I'm in NodeJS, I set a flag on "contactRelationUpdate" but I don't understand how to display the "greeting" in facebook messenger 

The GetStarted explained here:
https://developers.facebook.com/docs/messenger-platform/thread-settings/get-started-button

**Comment by willportnoy** [comment]
@JpEncausse you may want to open a new issue for your question.  I suspect it may require channel data, but I'm not sure.
