### ISSUE TITLE
media attachment contentType issue

### ISSUE THREAD

**Issue by puneetsngh** [Microsoft/BotBuilder#992]
I am sending a gif. So using `contentType=image/gif` but it is showing me only static image.

**Comment by alexsorokoletov** [comment]
@puneetsngh which channel are you using? There is a way to make it work in Telegram, not sure about other channels

**Comment by puneetsngh** [comment]
skype

**Comment by nickcordrey** [comment]
Unfortunately not all Skype clients support animated gifs today.
