### ISSUE TITLE
Is FormFlow Message with Attachments planned? 

### ISSUE THREAD

**Issue by tomfurrier** [Microsoft/BotBuilder#994]
Hi,

I miss this functionality, so I tried to implement it. I've managed to add the functionality to the C# SDK in a quite hacky way and touching many parts of the codebase...(I had to reference Connector in Builder code). 

Are there any plans that you add this functionality, or any advice how I should implement it properly so I can make a PR out of it?

**Comment by chrimc62** [comment]
You can override the IFormBuilder.Prompter with your own implementation of PromptAsyncDelegate which can do any mapping you like.  The default will now also automatically generate attachements from the extended attributes available in DescribeAttribute.
