### ISSUE TITLE
Facebook linking

### ISSUE THREAD

**Issue by VishalWaman** [Microsoft/BotBuilder#995]
Hi I am a bit confused with FB linking to BOT...

I am using node.js and my bot works fine with skype and web chat... Now I am looking for FB... Need help on Webhook un node.js.

**Comment by alexsorokoletov** [comment]
@VishalWaman when you configure Facebook channel on the dev.botframework.com website, there is a guide.

**Comment by VishalWaman** [comment]
Thanks, i already went through them... Seems i am missing something.

How to create we hook?

Any reference or snippet?

**Comment by alexsorokoletov** [comment]
Hook is created for you by the bot framework. 

Alex

**Comment by VishalWaman** [comment]
Yes... Thanks
