### ISSUE TITLE
Can't testing Microsoft Bot Framework Emulator?

### ISSUE THREAD

**Issue by Englbach** [Microsoft/BotBuilder#996]
I'm new developer for skype bot. After I have created a bot application and then testing it but I can't.
![untitled](https://cloud.githubusercontent.com/assets/11801842/17655427/6b57524a-62d8-11e6-8461-5916aceae23a.png)
![untitled1](https://cloud.githubusercontent.com/assets/11801842/17655428/6b8509f6-62d8-11e6-8d48-67fc0f773ee3.png)

**Comment by Thegaram** [comment]
You have to specify *Microsoft App Id* and *Microsoft App Password* in the fields on the top.

**Comment by Englbach** [comment]
Where is Microsoft App Password?. I just create bot application and haven't programming yet.

**Comment by Thegaram** [comment]
Should be the same as in your `Web.config`. For local testing, these can be anything, but the values in the emulator should match the ones in your configuration. Later, you'll acquire these during the bot registration.

**Comment by willportnoy** [comment]
The exception message in your screen shot implies it's something related to SSL:

"System.IO.IOException: The handshake failed due to an unexpected packet format"

When using the emulator, you should be able to skip authentication by leaving those fields blank.

**Comment by msft-shahins** [comment]
`https` is not enabled by default for `localhost`. Change the `bot url` to `http://localhost:3979/api/messages` instead of `https://...`.

**Comment by Englbach** [comment]
https://docs.botframework.com/en-us/csharp/builder/sdkreference/gettingstarted.html. I can see it that don't use microsoft app id...

**Comment by msft-shahins** [comment]
@Englbach you don't need the `MicrosoftAppId` and `MicrosoftAppPassword` if you want to debug your bot locally. When you are not indicating those values the bot authentication will be disabled the for the bot.

**Comment by Englbach** [comment]
thanks msft-shahins.

**Comment by timsmolka** [comment]
If I wanted to Debug it from Azure where is the AppPassword?  The source code came from Azure.  Where is the documentation on adding an AppPassword...
