### ISSUE TITLE
Skype: PostBack is not hidden

### ISSUE THREAD

**Issue by NanashiGIT** [Microsoft/BotBuilder#997]
Hello!
I've got the problem, that in skype, when i click on a button that has the Actiontype "PostBack", the client does show the "Value" of the button.
The Docs say: 
"Text of message which client will post to bot. Client applications will not display this message. "

The problem for me is, that depending on the value I do stuff in my bot. But the value might be a long hex code or something more ugly and I really dont want the user to see that.

That behavior happens on both, the desktop and mobile version of skype.

Greetings

**Comment by puneetsngh** [comment]
postBack doesn't work on skype yet, it must be imBack?

**Comment by NanashiGIT** [comment]
imBack has the exact same behaviour for me (and I think for imBack its correct)

**Comment by puneetsngh** [comment]
In imBack you can send the information in meta tags to hide them from user.

see rhis issue [#993](https://github.com/Microsoft/BotBuilder/issues/993)

**Comment by nickcordrey** [comment]
For example:
"Visible text<meta hiddenId=’10’/>"

**Comment by nickcordrey** [comment]
For example:
`"Visible text<meta hiddenID=’10’/>"`

**Comment by puneetsngh** [comment]
But I link the issue [#993](https://github.com/Microsoft/BotBuilder/issues/993) where I am sending meta which is not hiding on some clients
